### ISSUE TITLE
Unexpected end of input error uploading images

### ISSUE THREAD

**Issue by Ullarah** [directus/directus#1000]
Pulled the latest commits, a lovely error seems to occur when uploading an image, whether it be uploading an avatar, or an image inside a table.

Using developer tools yields this error:
```
Uncaught SyntaxError: Unexpected end of input
  BasePageView.extend.save.model.save.error  @ EditView.js?bust=85857a46c9df008e270e16f5a45f6c343d7a0e48:189
  options.error                              @ backbone.js?bust=85857a46c9df008e270e16f5a45f6c343d7a0e48:1566
  $.when.done.Backbone.sync.errorCodeHandler @ main.js:322
  n.Callbacks.j                              @ jquery-1.11.0.js:3099
  n.Callbacks.k.fireWith                     @ jquery-1.11.0.js:3211
  x                                          @ jquery-1.11.0.js:9312
  n.ajaxTransport.send.b                     @ jquery-1.11.0.js:9720
```

Also, it seems odd that it's trying to call jquery-1.11.0.js when the file doesn't exist? I tried copying the jquery.js to jquery-1.11.0.js with the same results unfortunately.

*Although I could be doing something wrong on my end, which sometimes is usually the case!*

**Comment by WellingGuzman** [comment]
@Ullarah the error seems odd, if I'm correct what it is saying there's a syntax error, but I try to upload a file and it works.

Now I'm to solve this, which branch did you use, and how did you install it? can you show me a screenshot of what is it at:
```
EditView.js?bust=85857a46c9df008e270e16f5a45f6c343d7a0e48:189
```

Also, about jquery-1.11.0.js being loaded without existing I believe this is the jquery.min.map  working its magics.

**Comment by Ullarah** [comment]
Using the master branch, from commit 85857a4

Installed by git clone, using the standard installer.

Although, I did forget to mention that I had to add some entries to the Apache configuration.

```
<Directory />
    AllowOverride all
    Require all granted
    Satisfy any
</Directory>
```

For some reason, if I don't add the 'Require all granted' line, I get a 500 error.

Here is a screenshot of the line from that file.
![image](https://cloud.githubusercontent.com/assets/5225506/9623123/dc0a2744-517f-11e5-9ccb-79eeb53037e9.png)

**Comment by WellingGuzman** [comment]
@Ullarah Is the server returning a response after you try to upload the image?
Are you running under what server configuration?

I'm concern why is giving and error in that line, please send me any related information with that request as well, that I may be forgetting.

Thanks!

**Comment by Ullarah** [comment]
@WellingGuzman Using the standard apache configuration with no changes to httpd.conf. Followed the install instructions as per the wiki. Everything is set to default. Here is the configuration for the site that I use:

```
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    DocumentRoot /opt/Directus

    <Directory />
        AllowOverride all
        Require all granted
        Satisfy any
    </Directory>

    ErrorLog /opt/directus.log
</VirtualHost>
```

Here is the 500 error that I get if the ```Required all granted``` line does not exist.

![image](https://cloud.githubusercontent.com/assets/5225506/9645745/fee84868-5210-11e5-85db-253f7feff361.png)

I just tried with a fresh install (new server and new Directus install) just in case, with the same results unfortunately!

**Comment by WellingGuzman** [comment]
@Ullarah to be honest this have been our biggest issue so far, we have couple of server setups and we have tried install on everything and it's works, but it seems there's so much variety.

Can you give me all the details, are you using Mac OS, Linux, or Windows? a software such as MAMP/WAMP? apache with php fpm? nginx with apache? 

I'd like to resolve this issue.

**Comment by Mahjouba91** [comment]
@WellingGuzman I got this error when I'm trying to upload an avatar : 
Fatal error: Class 'finfo' not found in C:\xampp\htdocs\Directus\api\core\Directus\Files\Storage\Adapter\Adapter.php on line 108

Don't know if it's a matter of php extension or if it's related to this issue.

**Comment by WellingGuzman** [comment]
We have been fixing lots of bugs with uploading files so I assume this was fixed along the way.

@Mahjouba91 About Class 'finfo' not found, was odd to me, but I found this extension is disabled by some hosting and/or php installation. I added a requirement check on installation this may help a bit.

Thanks, I will close this, if this a issue that still persist I will open it up again.
