### ISSUE TITLE
API refresh token (cookie mode) fails the second time

### ISSUE THREAD

**Issue by Eicher-MA** [directus/directus#10007]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Using the refresh endpoint to get a new access token works only once. (mode: cookie)

### To Reproduce

Login
`mutation Auth_Login($email: String!, $password: String!) {
	auth_login(email: $email, password: $password, mode: cookie) {
		access_token
	}
}`

Request:
`mutation refresh {
	auth_refresh {
		access_token
	}
}`

First time ✔
Second time: `{
  "errors": [
    {
      "message": "Invalid user credentials.",
      "locations": [
        {
          "line": 2,
          "column": 2
        }
      ],
      "path": [
        "auth_refresh"
      ],
      "extensions": {}
    }
  ],
  "data": {
    "auth_refresh": null
  }
}`

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

MSSQL 2019

### What browser are you using?

Testing in Insomnia

### What operating system are you using?

Windows 10

### How are you deploying Directus?

locally

**Comment by Eicher-MA** [comment]
Ok I solved it by using the **REST API** for the refresh. The **graphql** request doesn't replace the refresh cookie...

**Comment by rijkvanzanten** [comment]
You have to tell the refresh mutation to use the cookie mode, similar to the login mutation where you already pass it 🙂 

When using 

```graphql
mutation refresh { auth_refresh(mode: cookie) { access_token } }
```

it'll correctly set the refresh token in the cookie 👍🏻

**Comment by Eicher-MA** [comment]
Cheers for the follow up. 👍
The [docs](https://docs.directus.io/reference/authentication/#refresh)  aren't really clear about it.

**Comment by benhaynes** [comment]
We'll update the docs and then close this...
