### ISSUE TITLE
Unchecked checkbox doesn't apply color

### ISSUE THREAD

**Issue by jacobrienstra** [directus/directus#10016]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Very minor thing, might be intentional; The checkbox component doesn't apply the selected color when the value isn't checked.

https://github.com/directus/directus/blob/2f0e305796f2230ef8c447304c1e8c8f4ba51c75/app/src/components/v-checkbox/v-checkbox.vue#L216

<img width="499" alt="Screen Shot 2021-11-23 at 10 15 54 PM" src="https://user-images.githubusercontent.com/10411238/143168568-0b2dc30f-1915-4999-84f0-94fd8486dd42.png">
<img width="468" alt="Screen Shot 2021-11-23 at 10 17 22 PM" src="https://user-images.githubusercontent.com/10411238/143168487-f43ba5c8-d0d5-499f-aca0-de5e079090f3.png">
<img width="442" alt="Screen Shot 2021-11-23 at 10 15 59 PM" src="https://user-images.githubusercontent.com/10411238/143168533-7a27224d-7fd6-468d-bb34-6052457b0c0d.png">

### To Reproduce

Just set the color on the checkbox interface options! Or use a condition to set the color specifically on unchecked or indeterminate

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

local

**Comment by benhaynes** [comment]
This is the intended behavior, but to that end, it might be nice to update the options to:

* `Color On`
* `Color Off`

This would clarify, and add more flexibility. I'll leave this open so someone can add that option.
