### ISSUE TITLE
I can't run it with sqlite

### ISSUE THREAD

**Issue by mustafaugurlu973** [directus/directus#10022]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

<img width="656" alt="Ekran Resmi 2021-11-24 15 15 57" src="https://user-images.githubusercontent.com/32219762/143236894-9ac3812c-bd89-4a20-b374-d0b282113c06.png">

### To Reproduce

I can't run it with sqlite
Installation screenshot is attached.

### What version of Directus are you using?

9.01

### What version of Node.js are you using?

14.18.1

### What database are you using?

Sqlite

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by Oreilles** [comment]
Could you share the values of `DB_CLIENT` and `DB_FILENAME` in your `.env` file ?

**Comment by mustafaugurlu973** [comment]
## Database

DB_CLIENT="sqlite3"
DB_FILENAME="/Users/mustafaugurlu/Documents/directus/directus-project/data.db"

**Comment by Oreilles** [comment]
The main repository is only compatible with node 16 and upper, so maybe that's where the issue come from. Could you try upgrading to the latest node version and create the project again ?

**Comment by mustafaugurlu973** [comment]
<img width="1276" alt="Ekran Resmi 2021-11-24 17 06 38" src="https://user-images.githubusercontent.com/32219762/143253399-d48c630f-89bd-4394-a0b2-405ae57a7033.png">

**Comment by mustafaugurlu973** [comment]
DB_CLIENT="sqlite3"
DB_FILENAME="/Users/mustafaugurlu/Documents/directus/node17-test/new-project/data.db"

**Comment by Oreilles** [comment]
I am unable to replicate your issue, using node 14, 16 or 17.
Maybe try running `npm cache clean --force` and try again ?
Or could there be an issue with sqlite ? What result do you get when running `sqlite3 -v` ?

**Comment by mustafaugurlu973** [comment]
I've tried these before.

sqlite3 -version
3.36.0 2021-06-18 18:58:49 d24547a13b6b119c43ca2ede05fecaa707068f18c7430d47fc95fb5a2232aapl

I didn't have this problem in previous versions

I just reinstalled it with the brew reinstall sqlite command.
I reinstalled directus and tried it, same result. 


<img width="1278" alt="Ekran Resmi 2021-11-24 17 41 41" src="https://user-images.githubusercontent.com/32219762/143259804-350bfdff-1e3f-4013-88dd-4d45f1371995.png">

**Comment by Oreilles** [comment]
Could you share the full output of your `.env` file ?

**Comment by mustafaugurlu973** [comment]
####################################################################################################
## General

PORT=8055
PUBLIC_URL="/"

####################################################################################################
## Database

DB_CLIENT="sqlite3"
DB_FILENAME="/Users/mustafaugurlu/Documents/directus/node17-2/last-last/data.db"


####################################################################################################
## Rate Limiting

RATE_LIMITER_ENABLED=false
RATE_LIMITER_STORE=memory
RATE_LIMITER_POINTS=25
RATE_LIMITER_DURATION=1

####################################################################################################
## Cache

CACHE_ENABLED=false

####################################################################################################
## File Storage

STORAGE_LOCATIONS="local"
STORAGE_LOCAL_DRIVER="local"
STORAGE_LOCAL_ROOT="./uploads"

####################################################################################################
## Security

KEY="b8fb3fa9-2a50-408c-a3d0-f614ebfc7988"
SECRET="FQgzMTUqGsaKNFddUtfZYcIqsen8j4hN"


ACCESS_TOKEN_TTL="15m"
REFRESH_TOKEN_TTL="7d"
REFRESH_TOKEN_COOKIE_SECURE=false
REFRESH_TOKEN_COOKIE_SAME_SITE="lax"
REFRESH_TOKEN_COOKIE_NAME="directus_refresh_token"

####################################################################################################
## Auth Providers

AUTH_PROVIDERS=""

####################################################################################################
## Extensions

EXTENSIONS_PATH="./extensions"

####################################################################################################
## Email

EMAIL_FROM="no-reply@directus.io"
EMAIL_TRANSPORT="sendmail"
EMAIL_SENDMAIL_NEW_LINE="unix"
EMAIL_SENDMAIL_PATH="/usr/sbin/sendmail"

**Comment by mustafaugurlu973** [comment]
I have uploaded all the files. If you want, you can find it here.

https://1drv.ms/u/s!AjJc-qSyR0QvjzORp5x7c7OupP_F?e=IDFVW0

**Comment by joselcvarela** [comment]
Hello @mustafaugurlu973 
Are you running this on your machine or on some container?
Can you share the output of `echo $DB_CONNECTION_STRING`?

**Comment by mustafaugurlu973** [comment]
I run this locally. Since the Connection is not established, I cannot echo $DB_CONNECTION_STRING. 

Is there a file I can find this?

**Comment by Oreilles** [comment]
` echo $DB_CONNECTION_STRING` is just a bash command, you can run it in your terminal.
Does changing the `DB_FILENAME` to `"./data.db"` change anything ?

**Comment by mustafaugurlu973** [comment]
echo $DB_CONNECTION_STRING is not working. :( (i am a beginner)

<img width="718" alt="Ekran Resmi 2021-11-25 20 28 42" src="https://user-images.githubusercontent.com/32219762/143482870-38882d31-3211-4d5b-811b-dbb4d7b4c605.png">

**Comment by mustafaugurlu973** [comment]
<img width="749" alt="Ekran Resmi 2021-11-25 20 32 09" src="https://user-images.githubusercontent.com/32219762/143483205-4d6baee6-44ab-403b-9753-eac33db4b9a6.png">

**Comment by Oreilles** [comment]
Since no one ever encounter this issue and we're not able to replicate it, it probably isn't related to Directus.
I'll close this as we cannot help any further, but will re-open it if other people face it.

**Comment by mustafaugurlu973** [comment]
I can install another application that works with SQLite without any problems. Thank you for your interest. I will follow.

**Comment by uyanikislam** [comment]
Mustafa Bey selamlar. Ben de aynı soruna sahibim fakat bende en başta yüklerken aynı hatayı veriyor bir türlü çözemedim. Öneriniz varsa çok makbule geçer.

**Comment by uyanikislam** [comment]
> Since no one ever encounter this issue and we're not able to replicate it, it probably isn't related to Directus.
> I'll close this as we cannot help any further, but will re-open it if other people face it.

I have this problem also. Please help. When i create with sql db this happens. :(

**Comment by erdemaytek** [comment]
> Since no one ever encounter this issue and we're not able to replicate it, it probably isn't related to Directus. I'll close this as we cannot help any further, but will re-open it if other people face it.

I have this problem also.  When i create with sql db this happens.

**Comment by mustafaugurlu973** [comment]
> Mustafa Bey selamlar. Ben de aynı soruna sahibim fakat bende en başta yüklerken aynı hatayı veriyor bir türlü çözemedim. Öneriniz varsa çok makbule geçer.

Selamlar, Çok uğraştım ama çözemedim. Bir kaç tane tahminim var bu konuda ama çok can sıkıcı olduğu için uğraşmaktan vazgeçtim. Aklıma gelen sorun çıkarabilecek noktalar birincisi işletim sistemi dili...(tr kullanıyorum) ikincisi node version manager, üçüncüsü python.. Docker üzerinde postgre sql çalıştırmak daha doğru geldi bana.. bu şekilde sorusuz çalışıyor.

**Comment by uyanikislam** [comment]
> > Mustafa Bey selamlar. Ben de aynı soruna sahibim fakat bende en başta yüklerken aynı hatayı veriyor bir türlü çözemedim. Öneriniz varsa çok makbule geçer.
> 
> Selamlar, Çok uğraştım ama çözemedim. Bir kaç tane tahminim var bu konuda ama çok can sıkıcı olduğu için uğraşmaktan vazgeçtim. Aklıma gelen sorun çıkarabilecek noktalar birincisi işletim sistemi dili...(tr kullanıyorum) ikincisi node version manager, üçüncüsü python.. Docker üzerinde postgre sql çalıştırmak daha doğru geldi bana.. bu şekilde sorusuz çalışıyor. 

Ben de mysql kullanarak çözdüm. Windows sqllite uyumsuzluğu olabiliyormuş bazı bilgisayarlarda. Demek ki bize bu denk geldi. Teşekkürler cevap için.
