### ISSUE TITLE
Creating a new user with an already used e-mail address returns error 400 with no clear status

### ISSUE THREAD

**Issue by ravolta-io** [directus/directus#10026]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Registering a new user with a POST to /users works fine, but if the email is already in use Directus just returns a 400 error. When setting LOG_LEVEL="debug", the Directus log shows 'Field "email" has to be unique".
Expected behaviour would be to return the proper error codes so error handling can be correctly implemented on the client side.

<img width="545" alt="Schermafbeelding 2021-11-24 om 14 59 09" src="https://user-images.githubusercontent.com/47642986/143252156-5f1ca5ab-c6ff-47d9-9f9e-7871a7bd0da5.png">

### To Reproduce

1. Install Directus with PostGreSQL database
2. Create a user, either through the REST API or admin dashboard.
3. Create another user through the REST API with the same email as the one created in step 2.
4. Observe the received error.

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

MySQL

### What browser are you using?

React Native / Expo

### What operating system are you using?

macOS

### How are you deploying Directus?

Google Cloud

**Comment by licitdev** [comment]
Directus returns an Error 400 with the following error message in the response body.

```json
{
    "errors": [
        {
            "message": "Field \"email\" has to be unique.",
            "extensions": {
                "code": "RECORD_NOT_UNIQUE",
                "collection": "directus_users",
                "field": "email",
                "invalid": "duplicate@email.com"
            }
        }
    ]
}
```

Please check on the response body, you may have to surround your API request with `Try-catch`.

**Comment by rijkvanzanten** [comment]
Hey wie hebben we daar! Alles lekker Tristan?

I'll close this for now, as the detailed error can be found in the API response, which in turn allows for proper error handling in the end project.

**Comment by ravolta-io** [comment]
@rijkvanzanten Gaat lekker hoor :) Met jou ook zo te merken ;)

We did wrap the whole request in a try-catch, as we do with all our async calls. I'm putting my colleague on it to try different methods so we can present you with more details and examples.

**Comment by rijkvanzanten** [comment]
@ravolta-io that works! I don't think anything changed around error returning or its structure since the early alpha versions, so it should be good from that end.
