### ISSUE TITLE
Referencing column 'recipient' and referenced column 'id' in foreign key constraint 'directus_notifications_recipient_foreign' are incompatible.

### ISSUE THREAD

**Issue by cdwmhcc** [directus/directus#10037]
### Preflight Checklist

- [x] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

09:08:49 🚨 alter table `directus_notifications` add constraint `directus_notifications_recipient_foreign` foreign key (`recipient`) references `directus_users` (`id`) on delete CASCADE - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'recipient' and referenced column 'id' in foreign key constraint 'directus_notifications_recipient_foreign' are incompatible. 

Error: UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'recipient' and referenced column 'id' in foreign key constraint 'directus_notifications_recipient_foreign' are incompatible.

### To Reproduce

npx directus database migrate:latest

### What version of Directus are you using?

v9.1.0

### What version of Node.js are you using?

16.12.0

### What database are you using?

mysql 8.0

### What browser are you using?

chrome

### What operating system are you using?

Centos 8.3

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
What's your setting for the DB_CHARSET environment variable, if at all set?

**Comment by cdwmhcc** [comment]
> What's your setting for the DB_CHARSET environment variable, if at all set?

DB_CHARSET="UTF8MB4"

**Comment by cdwmhcc** [comment]
> What's your setting for the DB_CHARSET environment variable, if at all set?

`npx directus database migrate:latest`
Where can I find the SQL executed by this command line?
I'll add it manually.

**Comment by licitdev** [comment]
> Where can I find the SQL executed by this command line?

The migration scripts can be found in https://github.com/directus/directus/tree/main/api/src/database/migrations

**Comment by cdwmhcc** [comment]
> > Where can I find the SQL executed by this command line?
> 
> The migration scripts can be found in https://github.com/directus/directus/tree/main/api/src/database/migrations

Thank you!

**Comment by joelkennedy** [comment]
I'm also getting this error when updating from 9.0.1 to 9.1.2

```
$ npx directus database migrate:latest
12:58:54 ✨ Running migrations...
12:58:54 ✨ Applying Add Notifications...
12:58:54 🚨 alter table `directus_notifications` add constraint `directus_notifications_recipient_foreign` foreign key (`recipient`) references `directus_users` (`id`) on delete CASCADE - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'recipient' and referenced column 'id' in foreign key constraint 'directus_notifications_recipient_foreign' are incompatible. 
Error: UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'recipient' and referenced column 'id' in foreign key constraint 'directus_notifications_recipient_foreign' are incompatible.
```

My charset is utf8mb4, and I did notice that the directus_notifications table the migration script created didn't seem to have a charset set when checked it via Sequel Ace, it was just blank. My other tables had utf8mb4 set.

MySQL version is 8

**Comment by rijkvanzanten** [comment]
> My charset is utf8mb4

@joelkennedy is that what your `DB_CHARSET` is set to as well?

**Comment by joelkennedy** [comment]
@rijkvanzanten whoops, I hadn't set it. I added it (and set to UTF8MB4) and the DB migrated fine. I'll real the manual next time! Thanks for the quick reply.

**Comment by rijkvanzanten** [comment]
Closing this, as it seems like OPs questions have been answered.
