### ISSUE TITLE
slow down and crash

### ISSUE THREAD

**Issue by ztob** [directus/directus#10034]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

We have 3-40 concurrent requests on directus api, get, update, insert, etc.
One collection have 320k rows.
I use to insert up to 200 rows in some requests but directus starts after few minutes to slow down and crash.

### To Reproduce

Collection have about 15 fields, String, Integer, Boolean.

### Errors Shown

```
8:43:19 🚨 KnexTimeoutError Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection (/directus/node_modules/knex/lib/client.js:305:26)
    at async Runner.ensureConnection (/directus/node_modules/knex/lib/execution/runner.js:259:28)
    at async Runner.run (/directus/node_modules/knex/lib/execution/runner.js:30:19)
    at async /directus/api/dist/middleware/authenticate.js:80:26
```

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

PostgreSQL  13
2 GB RAM / 1vCPU

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker, Kubernates

**Comment by rijkvanzanten** [comment]
That particular error sounds more like a problem with the maximum amount of connections your database allows, than something in Directus itself 🤔 How are you running Directus currently? Are you using any horizontal scaling? How many connections does your database allow for? Did you use any custom settings for DB_POOL_MIN / DB_POOL_MAX  ?

**Comment by ztob** [comment]
yes it was a problem with the database
will close the issue
thank you

**Comment by botzill** [comment]
Are there any other env variables we can set for the knex pool? Seems that connections are kept open for too  long and it reaches the max pool.

thanks

**Comment by azrikahar** [comment]
@botzill the comment above from @rijkvanzanten does mention about the env variables, namely `DB_POOL_MIN` and `DB_POOL_MAX` for the [Knex pooling config](https://knexjs.org/#Installation-pooling). It is also documented here: https://docs.directus.io/configuration/config-options/#database 👍

**Comment by botzill** [comment]
hi @azrikahar

I'm asking about another options besides min and max as described here: https://github.com/vincit/tarn.js/#usage

**Comment by botzill** [comment]
But I will try as per documentation it says:

```
All the DB_POOL_ prefixed options are passed to tarn.js (opens new window)through Knex
```
