### ISSUE TITLE
Error on /admin/settings/roles 

### ISSUE THREAD

**Issue by laurin** [directus/directus#10047]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Directus throws an error when navigating to `/admin/settings/roles`.

### To Reproduce

1. start Directus 9.1.1
2. Log in
3. Navigate to `/admin/settings/roles`

### Errors Shown

**Error in UI**
```json
{
  "errors": [
    {
      "message": "select * from (select \"directus_users\".\"role\", count(\"directus_users\".\"id\") as \"count->id\" from \"directus_users\" where \"directus_users\".\"role\" = $1 order by \"directus_users\".\"id\" asc limit $2) as \"foo\" - column \"directus_users.role\" must appear in the GROUP BY clause or be used in an aggregate function",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

**Error in logs**
```
server_1  | 2021-11-25T09:26:02.855482345Z 09:26:02 🔍 [0.549ms] select "directus_roles"."id", "directus_roles"."name", "directus_roles"."description", "directus_roles"."icon" from "directus_roles" order by "directus_roles"."name" asc []
db_1      | 2021-11-25T09:26:02.856992324Z 2021-11-25 09:26:02.856 UTC [121] ERROR:  column "directus_users.role" must appear in the GROUP BY clause or be used in an aggregate function at character 23
db_1      | 2021-11-25T09:26:02.857035688Z 2021-11-25 09:26:02.856 UTC [121] STATEMENT:  select * from (select "directus_users"."role", count("directus_users"."id") as "count->id" from "directus_users" where "directus_users"."role" = $1 order by "directus_users"."id" asc limit $2) as "foo"
server_1  | 2021-11-25T09:26:02.857728557Z 09:26:02 🚨 error select * from (select "directus_users"."role", count("directus_users"."id") as "count->id" from "directus_users" where "directus_users"."role" = $1 order by "directus_users"."id" asc limit $2) as "foo" - column "directus_users.role" must appear in the GROUP BY clause or be used in an aggregate function
server_1  | 2021-11-25T09:26:02.857768684Z error: select * from (select "directus_users"."role", count("directus_users"."id") as "count->id" from "directus_users" where "directus_users"."role" = $1 order by "directus_users"."id" asc limit $2) as "foo" - column "directus_users.role" must appear in the GROUP BY clause or be used in an aggregate function
server_1  | 2021-11-25T09:26:02.857788643Z     at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:287:98)
server_1  | 2021-11-25T09:26:02.857791558Z     at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
server_1  | 2021-11-25T09:26:02.857794063Z     at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
server_1  | 2021-11-25T09:26:02.857796377Z     at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:11:42)
server_1  | 2021-11-25T09:26:02.857798892Z     at Socket.emit (node:events:390:28)
server_1  | 2021-11-25T09:26:02.857801146Z     at addChunk (node:internal/streams/readable:315:12)
server_1  | 2021-11-25T09:26:02.857803390Z     at readableAddChunk (node:internal/streams/readable:289:9)
server_1  | 2021-11-25T09:26:02.857805665Z     at Socket.Readable.push (node:internal/streams/readable:228:10)
server_1  | 2021-11-25T09:26:02.857807949Z     at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
server_1  | 2021-11-25T09:26:02.858958177Z 09:26:02 ✨ request errored GET 500 /roles?limit=-1&fields=id,name,description,icon,users.role&deep=%7B%22users%22:%7B%22_aggregate%22:%7B%22count%22:%22id%22%7D%7D%7D&sort=name 12ms

```

### What version of Directus are you using?

9.1.1

### What version of Node.js are you using?

v16.13.0

### What database are you using?

postgis:13-master

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker-Compose

**Comment by laurin** [comment]
This might be related to #9994

**Comment by Enhed** [comment]
![image](https://user-images.githubusercontent.com/36981278/143435187-a3058cf1-f935-49ed-b6c9-add856bd4340.png)
same and i wrote abut it here: [9808 discussion](https://github.com/directus/directus/discussions/9808)\
api not working with deep aggregate

**Comment by azrikahar** [comment]
@laurin @Enhed Would you guys mind to help test the following via REST API: `/roles?deep={%22users%22:{%22_aggregate%22:{%22count%22:%22id%22%20},%22_groupBy%22:[%22role%22],%22_sort%22:%22role%22,%22_limit%22:-1}}`, does it work and return the correct count?

Make sure to use `access_token` or give permissions to roles and users to prevent permissions error when testing 👍

**Comment by Enhed** [comment]
> @laurin @Enhed Would you guys mind to help test the following via REST API: `/roles?deep={%22users%22:{%22_aggregate%22:{%22count%22:%22id%22%20},%22_groupBy%22:[%22role%22],%22_sort%22:%22role%22,%22_limit%22:-1}}`, does it work and return the correct count?
> 
> Make sure to use `access_token` or give permissions to roles and users to prevent permissions error when testing 👍

![image](https://user-images.githubusercontent.com/36981278/143439120-1666a011-1034-41c0-b7a4-e38d9eda60e7.png)

**Comment by azrikahar** [comment]
@Enhed are you on `9.1.1`? deep groupBy didn't work properly before this, and since your query (the one returned by the api) didn't include groupBy, it should mean you're not on the latest version yet.

**Comment by Enhed** [comment]
@azrikahar im sorry, missed project, its working on latest

**Comment by laurin** [comment]
@azrikahar that query returns the roles without an error, the count is correct
```json
{
    "data": [
        {
            "id": "fa9bd5b4-7073-42ba-914f-93881674e914",
            "name": "testrole",
            "icon": "supervised_user_circle",
            "description": null,
            "ip_access": null,
            "enforce_tfa": false,
            "admin_access": false,
            "app_access": true,
            "users": [
                {
                    "count": {
                        "id": "2"
                    }
                }
            ]
        },
        {
            "id": "fe10d8e7-b66e-4c7a-b8d4-72fb19a8738f",
            "name": "Admin",
            "icon": "supervised_user_circle",
            "description": null,
            "ip_access": null,
            "enforce_tfa": false,
            "admin_access": true,
            "app_access": true,
            "users": [
                {
                    "count": {
                        "id": "1"
                    }
                }
            ]
        }
    ]
}
```

**Comment by licitdev** [comment]
Facing the same issue when running from the main branch, but with slightly longer error message.

<img width="421" alt="Screenshot 2021-11-25 at 8 10 20 PM" src="https://user-images.githubusercontent.com/26413686/143445404-7c199a39-c261-4b4c-9f0a-9252d1ade4cf.png">

**Comment by danieljwestman** [comment]
Same error here, I'm on the latest commit as per now.

Not able to manage roles and permissions at all...

**Comment by azrikahar** [comment]
@licitdev @danieljwestman may I know does #10050 fix it for you guys? Thanks for confirming this.

**Comment by licitdev** [comment]
@azrikahar Thank you for the fast fix!
I can confirm #10050 fixed the issue for me, on Postgres 11.

**Comment by danieljwestman** [comment]
That works for me 👍🏼

**Comment by laurin** [comment]
@azrikahar thank you!
