### ISSUE TITLE
Error when creating map field: type "geometry" does not exist

### ISSUE THREAD

**Issue by laurin** [directus/directus#10046]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Directus throws an error when trying to create a map field in a collection

### To Reproduce

1. Create a collection
1. Add a map field
1. Save

### Errors Shown

**UI Popup**
```
{
  "errors": [
    {
      "message": "alter table \"test_collection\" add column \"location\" geometry(Point, 4326) null - type \"geometry\" does not exist",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

**Backend Log**
```
server_1  | 2021-11-25T08:16:28.450870302Z 08:16:28 🚨 error alter table "test_collection" add column "location" geometry(Point, 4326) null - type "geometry" does not exist
server_1  | 2021-11-25T08:16:28.450907643Z error: alter table "test_collection" add column "location" geometry(Point, 4326) null - type "geometry" does not exist
server_1  | 2021-11-25T08:16:28.450919246Z     at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:287:98)
server_1  | 2021-11-25T08:16:28.450922652Z     at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
server_1  | 2021-11-25T08:16:28.450925407Z     at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
server_1  | 2021-11-25T08:16:28.450928082Z     at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:11:42)
server_1  | 2021-11-25T08:16:28.450931258Z     at Socket.emit (node:events:390:28)
server_1  | 2021-11-25T08:16:28.450933843Z     at addChunk (node:internal/streams/readable:315:12)
server_1  | 2021-11-25T08:16:28.450936408Z     at readableAddChunk (node:internal/streams/readable:289:9)
server_1  | 2021-11-25T08:16:28.450939485Z     at Socket.Readable.push (node:internal/streams/readable:228:10)
server_1  | 2021-11-25T08:16:28.450942119Z     at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
server_1  | 2021-11-25T08:16:28.451985732Z 08:16:28 ✨ request errored POST 500 /fields/test_collection 11ms
```

### What version of Directus are you using?

9.1.1

### What version of Node.js are you using?

v16.13.0

### What database are you using?

Postgres 12

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker-Compose

**Comment by laurin** [comment]
Ok this error does not appear when using PostGIS instead of postgres, I guess this is intended behaviour?

**Comment by rijkvanzanten** [comment]
Yup! PostGIS is required for the geometry types to function. This is logged on startup as well: `PostGIS isn't installed. Geometry type support will be limited.`

**Comment by fodurrr** [comment]
Should not it be a part of `npx directus bootstrap` process? If it is needed then the extension should have been created during bootstrap with `CREATE EXTENSION postgis;` or not?
Initial postgres database should be setup with all necessary extensions, don't you think?

Thanks

**Comment by rijkvanzanten** [comment]
@fodurrr Postgis isn't guaranteed to exist in the postgres server, and you may or may not want to have it enabled on your database (it adds a large number of functions and some additional tables/views that you might want to leave out of your DB)
