### ISSUE TITLE
Cannot delete users from database using back-end admin.

### ISSUE THREAD

**Issue by andriusign** [directus/directus#10049]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [ ] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Select users to delete in back-end, click delete. Check console and network. Request fails.

### To Reproduce

Select users to delete in back-end, click delete. Check console and network. Request fails.

### Errors Shown

13:04:50 🚨 error delete from "directus_users" where "id" in ($1, $2, $3) - update or delete on table "directus_users" violates foreign key constraint "directus_files_uploaded_by_foreign" on table "directus_files" 
error: delete from "directus_users" where "id" in ($1, $2, $3) - update or delete on table "directus_users" violates foreign key constraint "directus_files_uploaded_by_foreign" on table "directus_files"
    at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
13:04:50 ✨ request errored DELETE 500 /users 45ms

### What version of Directus are you using?

Version: v9.0.0-rc.85

### What version of Node.js are you using?

14

### What database are you using?

Postgresql

### What browser are you using?

any

### What operating system are you using?

any

### How are you deploying Directus?

Docker

**Comment by andriusign** [comment]
Cannot update to latest version yet, can anyone confirm that this has been fixed with latest release?

**Comment by benhaynes** [comment]
Appreciate you reporting this, but we can't troubleshoot outdated versions.

**Comment by azrikahar** [comment]
Duplicate of #9507.

@andriusign this is technically working as expected in terms of foreign key constraint, more info in this comment here: https://github.com/directus/directus/issues/9507#issuecomment-961913172. The issue linked also intends to refine this particular interaction.

**Comment by andriusign** [comment]
> 



> Appreciate you reporting this, but we can't troubleshoot outdated versions.

I think you misunderstood, I don't expect anything of you to fix any issue. I am trying to understand, if this issue has been fixed or not. Unfortunately I cannot and will not be updating anything at this point. With Directus it is super easy to have things broken after updating, so until we test everything (including all endpoints, permissions, roles, etc...) in test environments, update is not possible now. We had several similar issues in the past that updating Directus fixed one issue and led to several new ones.

**Comment by benhaynes** [comment]
@andriusign — then you should open a Discussion asking a question, not an Issue reporting a bug. Also, this question is asking others to check if this is resolved... but you could simply spin up an instance on the new version and test this yourself.
