### ISSUE TITLE
Maximum call stack size exceeded when using filter query param

### ISSUE THREAD

**Issue by darioguarascio** [directus/directus#10056]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Immediately after updating from 9.0.1 to 9.1.1 I get the following:
```
RangeError: Maximum call stack size exceeded
    at /directus/node_modules/@directus/shared/dist/cjs/utils/parse-filter.js:12:9
    at Array.reduce (<anonymous>)
    at parseFilter (/directus/node_modules/@directus/shared/dist/cjs/utils/parse-filter.js:11:35)
    at /directus/node_modules/@directus/shared/dist/cjs/utils/parse-filter.js:22:27
    at Array.reduce (<anonymous>)
    at parseFilter (/directus/node_modules/@directus/shared/dist/cjs/utils/parse-filter.js:11:35)
    at /directus/node_modules/@directus/shared/dist/cjs/utils/parse-filter.js:22:27
    at Array.reduce (<anonymous>)
    at parseFilter (/directus/node_modules/@directus/shared/dist/cjs/utils/parse-filter.js:11:35)
    at /directus/node_modules/@directus/shared/dist/cjs/utils/parse-filter.js:22:27
```

### To Reproduce

This happens with an API call in the following format
```
✨ request errored GET 500 /items/website?access_token=<token>&filter[project][status]=published&fields=project.git,domain,project.code&limit=-1 16ms
```

### What version of Directus are you using?

9.1.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

postgres:13

### What browser are you using?

Chrome

### What operating system are you using?

Linux 5.11.0-40-generic

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
Can you try it with `&filter[project][status][_eq]=published`? Your filter is missing the operator

**Comment by darioguarascio** [comment]
@rijkvanzanten Adding `[_eq]` fixed the issue.  I just reported a probably breaking backwards compatibility issue

**Comment by ssthiago** [comment]
I have same problem Immediately after updating from 9.0.1 to 9.1.1 .  But with me the error happens when I try to access http://localhost:8055/admin/  
Any idea?  should i open a new issue?

**Comment by droptablespace** [comment]
Hi, I have the same issue with all versions above 9.0.1. Any type of API call via REST or GraphQL, or accessing admin panel leads to 
`Maximum call stack size exceeded 

RangeError: Maximum call stack size exceeded

    at /directus/node_modules/@directus/shared/dist/cjs/utils/parse-filter.js:12:9

    at Array.reduce (<anonymous>)

    at parseFilter (/directus/node_modules/@directus/shared/dist/cjs/utils/parse-filter.js:11:35)

    at /directus/node_modules/@directus/shared/dist/cjs/utils/parse-filter.js:22:27

    at Array.reduce (<anonymous>)

    at parseFilter (/directus/node_modules/@directus/shared/dist/cjs/utils/parse-filter.js:11:35)

    at /directus/node_modules/@directus/shared/dist/cjs/utils/parse-filter.js:22:27

    at Array.reduce (<anonymous>)

    at parseFilter (/directus/node_modules/@directus/shared/dist/cjs/utils/parse-filter.js:11:35)

    at /directus/node_modules/@directus/shared/dist/cjs/utils/parse-filter.js:22:27`
for any type of objects(standard collection or singleton).

**Comment by domdus** [comment]
Update from 9.0.1 to 9.1.2 broke my external app using the directus api also. (Maximum call stack size exceeded)
As mentioned on top make sure use format operators such as `[_eq]` in EVERY filter request.

The directus app itself is working fine for me.

**Comment by ssthiago** [comment]
> Update from 9.0.1 to 9.1.2 broke my external app using the directus api also. (Maximum call stack size exceeded) As mentioned on top make sure to use format operators such as `[_eq]` in EVERY filtering request.
> 
> The directus app itself is working fine for me.

I am trying to access only the admin panel. Sorry if the question sounds silly, but where can I find use of the _eq operator to replace [_eq]? Would it be directly in the database?

**Comment by domdus** [comment]
Oh my post was confusing maybe, I was pointing to on API requests you do in with an external client or e.g. JS app.
I found my app breaking after the directus update because of simply missing the format of filter query parameters.

As example:
While `?filter[title]=foo` was accepted previously - v9.1.2 requires it to be `?filter[title][_eq]=foo`

For the admin panel there should be nothing to be taken care of from your side . The admin app should build it correctly - and it does here on my end.

**Comment by ssthiago** [comment]
> 

Now it was clear. However, in my case, after the update Directus simply does not enter the admin panel. The error occurs when I access http://localhost:8055/admin/ . I just don't know where to start =(

**Comment by ssthiago** [comment]
> Oh my post was confusing maybe, I was pointing to API requests you do in with an external client or e.g. JS app. I found my app breaking after the directus update because of simply missing the format of filter query parameters.
> 
> As example: While `?filter[title]=foo` was accepted previously - v9.1.2 requires it to be `?filter[title][_eq]=foo`
> 
> For the admin panel there should be nothing to be taken care of from your side . The admin app should handle it correctly - it does here on my end.

Now it was clear. However, in my case, after the update Directus simply does not enter the admin panel. The error occurs when I access http://localhost:8055/admin/ . I just don't know where to start =(

**Comment by bcartier** [comment]
I'm having the same issue - not being able to log in to the control panel, but only with certain user accounts. Maybe it's a saved preset or cache that is missing the now-required [eq]?

**Comment by rijkvanzanten** [comment]
It's _technically_ not a bug, as it was never officially/documented supported to omit the "_eq". That being said, enough people are running into this to start officially supporting the shorthand across the platform anyways.

**Comment by bcartier** [comment]
Thanks for looking into this @rijkvanzanten!

I have not written any filters myself, and I'm still experiencing this issue - the Directus app just suddenly started failing to load. I would say that it might _technically_ be a bug since it was the Directus app itself that assembled the filters without "_eq" 

:-P

**Comment by Enhed** [comment]
that is not working in rules too!
![image](https://user-images.githubusercontent.com/36981278/144218206-86305d4c-a77f-40d0-bbff-8167620788f7.png)

**Comment by Enhed** [comment]
roles not working cos in Files settings have field presets lika that:
```json
{
    "account": "$CURRENT_USER.account"
}
```

**Comment by mfeitoza** [comment]
> I have same problem Immediately after updating from 9.0.1 to 9.1.1 . But with me the error happens when I try to access http://localhost:8055/admin/ Any idea? should i open a new issue?

Same problem here after update to 9.1.2
