### ISSUE TITLE
Adding Custom Field to Directus Users Breaks Form Layout

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#10059]
Adding a custom field to Directus Users correctly shows up at the end of the form, but for some reason breaks the form flow at the beginning by adding a blank space.

![Screen Shot 2021-11-24 at 11 06 17 AM](https://user-images.githubusercontent.com/522079/143479994-c5feafc6-2f04-4fa9-9882-30f36df23b7e.png)

**Comment by benhaynes** [comment]
Also, I _might_ love if we enabled the ability to reorder system fields. I agree we want to control that experience, but at the same time, adding custom fields go WAY at the bottom. Open to discuss!

**Comment by rijkvanzanten** [comment]
> Also, I might love if we enabled the ability to reorder system fields.

This is not technically possible at the moment. The system fields aren't managed in the database, which means they're not user editable.

**Comment by azrikahar** [comment]
This should be related to #8560, and requires "adding custom fields + sort the custom fields" (second step is the crucial reproduction step here).
