### ISSUE TITLE
Decouple and allow for Google/Facebook auth

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1005]
In addition to the typical login, you should be able to confirm your identity (email address) through either Google or Facebook authentication.

**Comment by WellingGuzman** [comment]
@benhaynes we have a ticket for Google Auth #368? so should we close that one?

**Comment by benhaynes** [comment]
Yes, closed. I remembered that one but couldn't find it – this one should include Facebook, and/or other common methods.

**Comment by WellingGuzman** [comment]
Great, we should also include our friendly neighborhood, GitHub.

**Comment by benhaynes** [comment]
Good call ;)

**Comment by benhaynes** [comment]
@WellingGuzman – How hard is it to include the option to authenticate your email address with Google/Facebook/Github? I'm curious how long it would take to code this since these libraries are so common.

**Comment by WellingGuzman** [comment]
We should rewrite the authentication code, so we can be extensible and we can add more services easily. but with current authentication library will not be easy to do.

**Comment by benhaynes** [comment]
OK, well then a total rewrite will be hard, but good.

**Comment by benhaynes** [comment]
**[Migrated to FeatHub](http://feathub.com/directus/directus/+43)**

Please use the [Directus FeatHub](http://feathub.com/directus/directus) to vote for features or make new request. Accepted feature requests will be added to GitHub Issues.
