### ISSUE TITLE
Conditional options for datetime

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#10061]
While my main goal is to get this interface completely overhauled into a nicer calendar view, we need to make `include seconds` and `use 24 hour format` conditional so they don't show for the date type.

![Screen Shot 2021-11-25 at 12 13 42 PM](https://user-images.githubusercontent.com/522079/143481407-545fa9f6-5991-4d57-80d9-bd0d8c510b0c.png)

**Comment by u12206050** [comment]
You are welcome to use this: https://github.com/u12206050/directus-9-date-picker-interface

**Comment by benhaynes** [comment]
> You are welcome to use this: https://github.com/u12206050/directus-9-date-picker-interface

Would love to check this one out, thank you! I think the main thing we'd have to figure out is internationalization and accessibility... since those come with the browser/system input. But I'd prefer to have this nice pretty one!

Maybe there's someone on the @directus/team who can take a look into this interface? Would love to get it in Core! ❤️
