### ISSUE TITLE
Undefined (reading 'primary') errors on fresh install

### ISSUE THREAD

**Issue by gurumark** [directus/directus#10063]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

 I have "Undefined (reading 'primary') error" using Docker directus/directus 9.1.2. It prevents creating a data model for a table.

### To Reproduce

Create a table like the following with a natural primary key:

```sql
CREATE TABLE cronmon (
domain varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
cronrun datetime DEFAULT NULL,
dbbackup datetime DEFAULT NULL,
dbbackuppurge datetime DEFAULT NULL,
updated datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE cronmon
ADD PRIMARY KEY (domain);
COMMIT;
```

### Errors Shown

```
13:56:12 🚨 Cannot read properties of undefined (reading 'primary') 
TypeError: Cannot read properties of undefined (reading 'primary')
    at RevisionsService.createOne (/directus/node_modules/directus/dist/services/items.js:48:74)
    at /directus/node_modules/directus/dist/services/items.js:129:61
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### What version of Directus are you using?

9.1.2

### What version of Node.js are you using?

Docker

### What database are you using?

Mariadb - 10.6.5

### What browser are you using?

Chrome

### What operating system are you using?

Docker

### How are you deploying Directus?

Docker

**Comment by Oreilles** [comment]
Thanks for reporting, we're gonna need a few more info to solve this though: Were you on a previous version and faced this issue after a migration ? Did you create your table from another database administration tool, then tried plugging Directus into it - or did you try creating the table with the Application ?

**Comment by Oreilles** [comment]
Did you create the table before or after the migration ?
And after which exact steps was the error shown ?

**Comment by gurumark** [comment]
I've dropped all the directus tables and just left the table. Now the primary key error is gone but a related one comes up:

09:56:32 🚨 Cannot read properties of undefined (reading 'substring') 
TypeError: Cannot read properties of undefined (reading 'substring')
    at PayloadService.processDates (/directus/node_modules/directus/dist/services/payload.js:262:68)
    at PayloadService.processValues (/directus/node_modules/directus/dist/services/payload.js:137:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /directus/node_modules/directus/dist/services/items.js:326:44

**Comment by gurumark** [comment]
Ok. I've dropped my table and RECREATED it using the app. The same error:
10:20:09 🚨 Cannot read properties of undefined (reading 'substring') 
TypeError: Cannot read properties of undefined (reading 'substring')
    at PayloadService.processDates (/directus/node_modules/directus/dist/services/payload.js:262:68)
    at PayloadService.processValues (/directus/node_modules/directus/dist/services/payload.js:137:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /directus/node_modules/directus/dist/services/items.js:326:44
file:///home/guruadm/Downloads/Screenshot%20(1).png

**Comment by gurumark** [comment]
@rijkvanzanten Did I answer your question?

**Comment by rijkvanzanten** [comment]
I just tried reproducing this on a fresh installation on MariaDB 10.6.4 using the exact query provided in the OP:

```sql
CREATE TABLE cronmon (
domain varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
cronrun datetime DEFAULT NULL,
dbbackup datetime DEFAULT NULL,
dbbackuppurge datetime DEFAULT NULL,
updated datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE cronmon
ADD PRIMARY KEY (domain);
COMMIT;
```

and everything seems to behave as expected:

<img width="1805" alt="CleanShot 2021-12-03 at 13 45 12@2x" src="https://user-images.githubusercontent.com/9141017/144656393-02b811d0-9e60-4f5e-9c1d-764476feeb8e.png">

I'm not sure what other things happened in that database over time that were causing issues, but I don't think it's this particular table.

Can you provide a database dump of a minimal reproduction where this is happening?
