### ISSUE TITLE
$NOW filter doesn't consider DB_TIMEZONE

### ISSUE THREAD

**Issue by Mario-Amos** [directus/directus#10079]
### Describe the Bug

$NOW filter doesn't consider the .env's parameter named "DB_TIMEZONE".

**Temporary fix**
I have to request the API with the filter's value set to "$NOW(+1 hours)" in order to get the correct values.
I don't think that this is intended, but I'm not totally sure.

May also be related to #7383

### To Reproduce

1. Create a Directus project with "DB_TIMETONE" set to "+01:00"
2. Create a datetime field in a collection
3. Fill an element of the collection
4. Use SDK to execute a query:
    `directus.items("my_collection").readyMany({'date':  {'_lt': '$NOW'}}).then(() => {...})`

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

14.18.0

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### What operating system are you using?

Windows 11

### How are you deploying Directus?

Self-hosted

**Comment by Mario-Amos** [comment]
May also be related to #7383

**Comment by saerdnaer** [comment]
@Mario-Amos How did you solve the issue?

**Comment by saerdnaer** [comment]
At the time of writing the cloud version had the exact bug you described in your issue, so I my opinion the issue is not resolved yet.
