### ISSUE TITLE
No disabling of field types in Advanced Field Creation Mode

### ISSUE THREAD

**Issue by licitdev** [directus/directus#10088]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The types are limited when in the normal field creation flow.
However when entering the Advanced Field Creation Mode, other invalid field types can be set.
For example, creating a toggle field but set the type as float.

For field types that are of alias type, there is no issue as the dropdown isn't displayed.

Randomly tested Many to One, realised that the field type is locked when entering the Advanced Field Creation Mode.

### To Reproduce

https://user-images.githubusercontent.com/26413686/143588875-0dacdd39-d057-4f83-b165-70eed0c8a736.mov

https://user-images.githubusercontent.com/26413686/143588879-9305ae35-2a96-4874-aa01-da4ab6d74a98.mov

https://user-images.githubusercontent.com/26413686/143589565-cc78b1a1-bf84-46f2-8923-0688a26a9fa6.mov

### What version of Directus are you using?

main branch 9.1.2

### What version of Node.js are you using?

v16

### What database are you using?

Postgres 11

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by Oreilles** [comment]
This is intended. In easy field creation, the type list is locked depending on the interface picked. In advanced field creation, it's the interface list that is locked depending on the type picked. Thank you for reporting this though, because it made me notice another bug in here!

**Comment by licitdev** [comment]
@Oreilles Found this issue while looking into #10065. Hence for toggle field, setting of the type to integer or string is allowed?

**Comment by Oreilles** [comment]
It is allowed, because the type isn't locked at all in advanced mode - it's the interface (in the interface tab) list that is filtered to only show the one compatible with the field type ( and should be reset if the new type selected isn't compatible ).
