### ISSUE TITLE
date wrong value in the App

### ISSUE THREAD

**Issue by AndreyKindin** [directus/directus#10093]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I save the date (field type date) e.g. September 1, 2021 in the Directus app, then the DB says 2021-09-01(correct) but the app shows August 31, 2021, so saved date -1 day.

### To Reproduce

^^ create date field

### What version of Directus are you using?

9.1.2

### What version of Node.js are you using?

14.17.6

### What database are you using?

MariaDB

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Ubuntu Linux

**Comment by u12206050** [comment]
Are you using `timestamp` type or `dateTime`?
Only timestamp keeps track of timezone, so it will display correct, whereas dateTime is UTC and will therefor offset to what ever timezone you are in when displaying it.

**Comment by AndreyKindin** [comment]
In my test I use type `date` both `timestamp` and `datetime` work correctly,  in the database it is also stored correctly only the display in directus is not correct

**Comment by rijkvanzanten** [comment]
Duplicate of https://github.com/directus/directus/issues/7383
