### ISSUE TITLE
Not able to filter record with value "1.0" with GraphQL

### ISSUE THREAD

**Issue by atularvind** [directus/directus#10107]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

it is a weird issue.
I have created a data model `version` which has several columns including `name`
When I try to filter the record using the REST it searches the record perfectly. 
`http://localhost:8055/items/version?filter[name][_eq]="1.0"`
the result I am receiving is 

```
{
    "data": {
        "version": [
            {
                "name": "1.0",
                "desc": "test description",
            }
        ]
    }
}
```

but when I try to run the same query with GraphQL, it won't give me any result. here is my query

```
query VersionQuery {
    version (filter: { name: { _eq: "1.0" } }){
        name
        desc
    }
}
```

here is the result. 

```
{
    "data": {
        "version": []
    }
}
```

when I search for version `1.1` using GraphQL, it works perfectly. hope I am not missing anything.

### To Reproduce

To reproduce the issue you need to create a Data model with a field with any name,
and try to run the GraphQL query as mentioned in the bug description. 

```
query VersionQuery {
    version (filter: { name: { _eq: "1.0" } }){
        name
        desc
    }
}
```

### Errors Shown

No error shown, just not getting the expected result. 

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

14.17.0

### What database are you using?

SQLite

### What browser are you using?

Chrome

### What operating system are you using?

macOS Catalina (10.15)

### How are you deploying Directus?

Running locally

**Comment by Oreilles** [comment]
I can replicate this. The problem might be that all filter values that can be parsed as numbers are casted to numbers, then casted back to string if the field isn't a number. Here, `1.0` would be casted to the number `1`, which is different than the string `1.0`. It works with `1.1` because the representation won't change. Although I just tested with `1.10` and the filter works properly so...
