### ISSUE TITLE
Radio buttons not working with type int

### ISSUE THREAD

**Issue by u12206050** [directus/directus#10111]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I changed the default type from string to int using the `advanced mode`, However even though I am able to set the values and they update correctly it seems that when being loaded again (after refresh) it doesn't show any radio selected.

<img width="1151" alt="Screenshot 2021-11-28 at 11 07 50" src="https://user-images.githubusercontent.com/6641242/143763665-7b440228-b818-4eb2-b47e-ffee5089cc79.png">

Here `perm_*` relates to a radio button group. No value is shown as selected though.

### To Reproduce

1. Create a Radio Button field
2. Switch to advance mode and change type to `Integer`
3. Add a resource with one of the radio buttons selected
4. Refresh the page (Has to load from the backend again)
5. No radio buttons should be selected.

### Errors Shown

None

### What version of Directus are you using?

9.1.2

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

chrome

### What operating system are you using?

osx

### How are you deploying Directus?

Locally

**Comment by Oreilles** [comment]
Closing in favor of https://github.com/directus/directus/issues/10122

**Comment by u12206050** [comment]
Fixed in #10267
