### ISSUE TITLE
Mention UI in comment has some inheriated CSS problem

### ISSUE THREAD

**Issue by torstenhoegel** [directus/directus#10126]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The following window appears while using chrome and trying to mention someone:

![Bildschirmfoto 2021-11-29 um 11 55 14](https://user-images.githubusercontent.com/22012025/143856328-1659fb39-9fac-4377-8e9f-43994eea07ae.png)
_I had to blank out some user information for privacy concerns._

Digging down to the html classes the following creates the problem:

![Bildschirmfoto 2021-11-29 um 11 57 36](https://user-images.githubusercontent.com/22012025/143856674-fee15039-25d8-4a57-bef0-27c3143888b9.png)

Although the inner class fits exactly how it should be:

![Bildschirmfoto 2021-11-29 um 11 57 21](https://user-images.githubusercontent.com/22012025/143856867-5cfa433e-c5e2-4621-9726-5d00af3b58fe.png)

### To Reproduce

try to mention a user with chrome or firefox

### What version of Directus are you using?

v9.1.2

### What version of Node.js are you using?

-

### What database are you using?

-

### What browser are you using?

Chrome / Firefox / Safari

### What operating system are you using?

macOS / IOS

### How are you deploying Directus?

locally, Docker, PaaS

**Comment by uebmaster** [comment]
I got this when i submit a mention in a comment

![image](https://user-images.githubusercontent.com/5565506/144273206-0438ae14-d641-45fe-83a1-cf1b8604ae2c.png)

**Comment by rijkvanzanten** [comment]
@uebmaster that seems to be an unrelated issue to the OP. Mind opening a new issue?

**Comment by rijkvanzanten** [comment]
Are you using any custom CSS @torstenhoegel? I can't reproduce this on macOS Big Sur 11.6 w/ Chrome 96

**Comment by torstenhoegel** [comment]
Well somehow this went away after updating all instances and deleting all chaches on all devices :/ 

thank you
