### ISSUE TITLE
object in many_to_one relation not visible

### ISSUE THREAD

**Issue by Pawnerd** [directus/directus#1013]
After creating a new [many-to-one column](http://puu.sh/jZvPq/56ae7a2ab9.png) in Directus with some [UI settings](http://puu.sh/jZvPM/98faef3840.png), it is possible to [see the column value while adding a row](http://puu.sh/jZvRC/707104f5b5.png), but when I [list all rows](http://puu.sh/jZvTr/ec0cdb08ab.png), it is not visible anymore! Instead, I can only see the '=> formaat' part.

**Comment by WellingGuzman** [comment]
Thanks @Pawnerd I'll take a look into this.

**Comment by WellingGuzman** [comment]
hey @Pawnerd  can you please tell me what `product_id.product_identifier` is?

**Comment by Pawnerd** [comment]
Yes, there are three tables. Products, attributes and values. A value is linked to an attribute with attribute_id. An attribute is linked to a product with product_id. product_id is therefore a column in attributes. If I refer to product_id.public_identifier, it should show the value of the public_identifier column of the product of the attribute which is selected in the table values.

Op 5 sep. 2015 om 04:56 heeft Welling Guzman <notifications@github.com> het volgende geschreven:

hey @Pawnerd can you please tell me what product_id.product_identifier is?

**Comment by benhaynes** [comment]
@WellingGuzman Do you need more info to help debug this?

**Comment by WellingGuzman** [comment]
From what @Pawnerd  mentioned I found the issue with this @benhaynes 

Here bring the issue we talked about getting related data, when you are editing a page, all the data gets requested (including related) while on table listing is not. at least not the second level deep.

I can show more details later about how this works and why is not getting the data as it's expected.

**Comment by benhaynes** [comment]
@WellingGuzman Is this fetching the relational data on the listing page now?

**Comment by WellingGuzman** [comment]
@benhaynes Yes, it's working on the listing page.

**Comment by benhaynes** [comment]
Had to roll-back for stability. A new fix is forthcoming...

**Comment by benhaynes** [comment]
This data is now shown correctly on the listing page for M2O and M2O-Typeahead
