### ISSUE TITLE
Image thumbnails are not displayed in table view

### ISSUE THREAD

**Issue by christianrr** [directus/directus#10134]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When using an image field, thumbnails are no longer visible in the table view (this was working in RC releases).

When a thumbnail is specified for the display of the image field, the table view renders "--". If no display template is specified, the UUID is rendered.

Similar to #10105.

![image](https://user-images.githubusercontent.com/10274479/143889070-7ca375de-f8ab-4d11-a133-d5f6e1a9c0b0.png)
![image](https://user-images.githubusercontent.com/10274479/143889211-5122970b-66c3-4478-b36f-3a28e99500d1.png)

### To Reproduce

- Create table "test"
- Create image field "image"
- Create entry in "test" and upload image
- Display table view of "test"
- No thumbnail is visible, neither with thumbnail display nor raw display

### What version of Directus are you using?

9.1.2

### What version of Node.js are you using?

12.2

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
Seems like things are working as expected on my end 🤔 

https://user-images.githubusercontent.com/9141017/144517189-cbe76991-724d-43ce-b068-ac8220061d7b.mp4

(feat. my 🐈‍⬛)


You mentioned you were using the "Thumbnail" display. Did you mean the Image display like I did in my screencast?

**Comment by christianrr** [comment]
Hmm, version 9.1.2 -> no "Image" display available (see below). Same on updated 9.2.0. Any Ideas?

What I originally meant was that I've created a "Related Values" display with thumbnail option.

<img width="2278" alt="Screenshot 2021-12-06 at 13 20 37" src="https://user-images.githubusercontent.com/10274479/144845173-b2baaa39-2b83-418a-b88f-94ff49e14a20.png">

**Comment by christianrr** [comment]
Just tried your workflow with a clean 9.2.0 setup:

"Image" and "File" displays only appear in "Continue Advanced Field Creation Mode". If you "Save" the field first and then call the field's displays by clicking it in fields list, "Image" and "File" display options are gone.

**Comment by christianrr** [comment]
My current workaround: Updating the display option for all image fields manually in the DB:
`UPDATE directus_fields SET display = 'image' where interface = 'file-image'`

**Comment by rijkvanzanten** [comment]
@christianrr I'm not seeing that particular issue under 9.2.1 on my end 🤔 Could you try it in 9.2.1 and let me know if the problem persists?

**Comment by christianrr** [comment]
@rijkvanzanten Nope, still the same... Video is from a clean install with 9.2.1 and SQLite, however the same issue appears on an updated instance with MySQL.

https://user-images.githubusercontent.com/10274479/144915878-9b2bba72-d8d6-4e7d-ae7a-bae15cc62de1.mp4

**Comment by rijkvanzanten** [comment]
@christianrr so weird! @azrikahar Would you be able to take a look?

**Comment by azrikahar** [comment]
Can confirm this still happens on v9.3.0 for SQLite and MySQL, but _not_ PostgreSQL. Seems like the issue is when the file-image interface is added to the two databases, the field type ended up being `String` (not sure was this ever _not_ String in the past for them) whereas it's `UUID` in PostgreSQL.

We can also confirm this in @christianrr latest video, at the 0:32 mark where it showed the image field is of type `String`. Since interfaces like file-image are only shown for type `UUID`, it will not be shown for SQLite or MySQL:

https://github.com/directus/directus/blob/530db94c53fefcca785a81033665b8ba2861acfc/app/src/interfaces/file-image/index.ts#L10

@christianrr has this worked before, perhaps in RC releases as you mentioned? If it ever did, there may be some regressions happening here since file-image has been limited to type uuid one year ago 🤔

**Comment by christianrr** [comment]
Can confirm that the image thumbnail worked in RC releases, for instance in rc.94.

Maybe the issue was introduced with the new "quick field" feature, because beforehand you were explicitly choosing the option "Single file" from "Create field" options and there UUID was set as field type (see pictures).

![image](https://user-images.githubusercontent.com/10274479/146908001-1076905e-fd60-40c1-962b-147e142edc95.png)

![image](https://user-images.githubusercontent.com/10274479/146908108-f660bd7b-f95b-49b3-b821-346ba2ff08d7.png)

**Comment by robertosanval** [comment]
Same problem here, I've solved it temporarily with the SQL query mentioned by @christianrr
