### ISSUE TITLE
Directus 9.1 breaks support for PostgreSQL 10.

### ISSUE THREAD

**Issue by schlensen** [directus/directus#10136]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Switching to version 9.1 the support for postgreSQL-databases of version 10 is broken. We're running directus in dockerized mode, when starting up the container the error-message (see below) appears because there is no field "indnkeyatts" in the table "pg_index". This field was first introduced in postgres version 11 (search for "indnkeyatts"):

Version 10: https://www.postgresql.org/docs/10/catalog-pg-index.html
Version 11: https://www.postgresql.org/docs/11/catalog-pg-index.html

We are currently using AWS Aurora Serverless because of its big advantage in scaling up and down automatically but Serverless is only supported for postgreSQL 10 (at least for now). 

The incompatibility was introduced because of the changes in the knex-schema-inspector, see the following issue and the according commit:

https://github.com/directus/directus/issues/9217
https://github.com/knex/knex-schema-inspector/commit/3b40c2c2348518caac0b65978161d0e9e876e07a

### To Reproduce

Run directus in version >= 9.1. against a PostgreSQL-Database in version 10.

### Errors Shown

> error:
        SELECT relname as table_name
          , pg_attribute.attname as column_name
        FROM pg_index
          , pg_class
          , pg_attribute
          , pg_namespace
        WHERE
          indrelid = pg_class.oid
          AND nspname IN ($1)
          AND pg_class.relnamespace = pg_namespace.oid
          AND pg_attribute.attrelid = pg_class.oid
          AND pg_attribute.attnum = ANY (pg_index.indkey)
          AND indisprimary
          AND indnkeyatts = 1
       - column "indnkeyatts" does not exist
    at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
  length: 176,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: 'Perhaps you meant to reference the column "pg_index.indnatts".',
  position: '463',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3293',
  routine: 'errorMissingColumn'
}

### What version of Directus are you using?

9.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

Postgres 10.14

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rogersanick** [comment]
I am also having this bug thanks to @licitdev for pointing me here!
