### ISSUE TITLE
wysiwyg alignment changes access_token

### ISSUE THREAD

**Issue by jacksbrand** [directus/directus#10145]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When using the 'align left' 'align right' 'align center' 'align justify' formatting options on an image inside a wysiwyg field - setting anything other than what it was originally imported into the field as causes the default access_token (which has been set in the interface) to become an automatically generated token.

**1. Importing an image / publishing etc:**
![1](https://user-images.githubusercontent.com/69592559/143959403-4078743f-9673-4eae-9052-299cab92c909.png)
 
**2. Leaving the import alone - notice the access_token is what I've set it to be in the interface "web-app-public-token":**
![2](https://user-images.githubusercontent.com/69592559/143959465-69681ff8-2176-4f08-877b-a6e13e1546c8.png)

**3. Centering the image and then publishing etc:**
![3](https://user-images.githubusercontent.com/69592559/143959572-8f57148c-790f-42ab-b26f-691180acfc57.png)

**4. Notice how the centered image uses a completely random token.** 
![4](https://user-images.githubusercontent.com/69592559/143959604-35545644-b84c-4dbb-800c-b3a15162825a.png)

**5. If you move the image back to the alignment option it had when it was first imported, it starts using the token set in the interface again.** 

### To Reproduce

1. Create a brand new database and directus instance.
2. Create a collection with a wysiwyg field.
3. Take steps listed above - set the innerHtml somewhere in a client or use postman etc to see it.

### Errors Shown

After some time (15 mins?) 'unauthorised' when trying to render the wysiwyg content if it does not have the access_token set to what has been set in the interface. 

### What version of Directus are you using?

Latest / 9.1.2 / Docker (9.0.1?)

### What version of Node.js are you using?

LTS & latest

### What database are you using?

Postgres & MySQL

### What browser are you using?

Chrome, Firefox, Brave (completely stock - incognito - no extensions etc)

### What operating system are you using?

Ubuntu

### How are you deploying Directus?

Locally & Docker (not at the same time)

**Comment by jacksbrand** [comment]
Any help on this guys is much appreciated - a client requires the ability to format their images left / right / center etc in various places. Directus is great and have had good feedback from the client.

Let me know if there's anything else I can help with.

I think this is related to #9831

**Comment by rijkvanzanten** [comment]
@jacksbrand Is that access token saved to the database? It's correct behavior that the preview within the app uses the temporary token

**Comment by jacksbrand** [comment]
@rijkvanzanten - thanks for getting back to me on this - yeah the database has saved the img element with the access token set to the temp string. 

![5](https://user-images.githubusercontent.com/69592559/144157526-dc7b8ace-53bc-49b9-b750-e9ae57b572fa.png)

**Comment by jacksbrand** [comment]
@rijkvanzanten - just confirmed - when I import the image it saves with the token I've set in the interface:
![6](https://user-images.githubusercontent.com/69592559/144158333-c7c7a7de-9dfb-4b1b-a88a-53b4e8b7b43d.png)

But when I center it:
![7](https://user-images.githubusercontent.com/69592559/144158355-b0792368-e122-463f-bab8-82fd2c60e2b9.png)

Strangely enough - when I set it back to where it was originally (justify it seems in this case) the original and correct token is written back to the db:
![8](https://user-images.githubusercontent.com/69592559/144158538-9b6417ef-fe48-4d23-b10f-c4c3fbe3d423.png)

**Comment by rijkvanzanten** [comment]
The regex used to replace the temporary token fails on img tags that have an inline style attribute, which is the case when using alignment in tinymce:

https://github.com/directus/directus/blob/74db449432580fba91b12dcd99ad0f4b2e6a8f8a/app/src/interfaces/input-rich-text-html/input-rich-text-html.vue#L273-L278

With `style` attribute:

<img width="910" alt="CleanShot 2021-12-02 at 14 11 28@2x" src="https://user-images.githubusercontent.com/9141017/144487418-1e04b9b0-93b4-4a53-8729-ec2c51508a7a.png">


Without `style` attribute:

<img width="853" alt="CleanShot 2021-12-02 at 14 11 51@2x" src="https://user-images.githubusercontent.com/9141017/144487470-a39a0464-0ba1-4db2-9974-dd7a46cdb40b.png">

Most definitely within the first capture group here: `(<[^=]+=")`. Time to brush up on my RegEx syntax ᕕ( ᐛ )ᕗ

**Comment by jacksbrand** [comment]
@rijkvanzanten - legendn nice spot - thank you. #RegexIsFun
