### ISSUE TITLE
Exception break directus and show me "Network error" when get the exception inside custom hooks

### ISSUE THREAD

**Issue by hermesalvesbr** [directus/directus#10157]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I'm developing a custom hook to check if value it's the same hour scheduled for a teacher. The hooks find in the collection, compare and show a "InvalidPayload" if the hour already exist in database. 

When i call the the exception after the if condition, the directus show me: "Network error" and turn off the directus instance. 

```
HourA  07    HourB   07
/directus/seda/extensions/hooks/teacherHourBusy/index.js:116
                        throw new InvalidPayloadException("Hour is busy for this teacher");
                              ^

InvalidPayloadException [Error]: Hour is busy for this teacher
    at /directus/seda/extensions/hooks/teacherHourBusy/index.js:116:31
    at Array.map (<anonymous>)
    at /directus/seda/extensions/hooks/teacherHourBusy/index.js:112:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 400,
  code: 'INVALID_PAYLOAD',
  extensions: {}
```

![Captura_de_Tela_2021-11-29_as_16 19 01](https://user-images.githubusercontent.com/379850/144035354-d54d36b2-9fba-488c-a62b-aab1af857eea.png)

### To Reproduce

I wrote this code: 

```js
filter('items.update', async (payload, { keys, collection }) => {
        if (collection == 'grade_curricular') {
            const res = searchPayload(payload, "inicio"); // encontra no directus var com 'inicio'
            const retorn = Object.keys(res); //[ 'segunda_hora_inicio', 'terca_hora_inicio' ]
            const compareREs = await retorn.map(async (fieldPayload) => {
                const resDirectus = payload[fieldPayload];
                const [hourB, ...minutesB] = resDirectus.split(':');
                const consulta = await findParams({ id: keys, field: fieldPayload });
                consulta.map((v) => {
                    const [hourA, ...minutesA] = v[fieldPayload].split(':');
                    console.log('HourA  ' + hourA + "    HourB   " + hourB);
                    if (hourA == hourB) {
                        throw new InvalidPayloadException("Hour is busy for this teacher");
                    } else {
                        console.log('Nothing to do.');
                    }
                });
            });
        }
    });
```

The error is after if condition when i call the "throw new InvalidPayloadException". 

### Errors Shown

status: 400,
code: 'INVALID_PAYLOAD',
extensions: {}

### What version of Directus are you using?

9.1.2

### What version of Node.js are you using?

v16.13.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by hckhanh** [comment]
Me too, I have to rollback to v9.0.1

**Comment by rijkvanzanten** [comment]
I believe the problem exists within the specific implementation of the hook, rather than the use of the exception. I just tried it with this minimal reproduction:

```js
module.exports = function registerHook({ filter }, { exceptions }) {
	const { InvalidPayloadException } = exceptions;

	filter('items.update', async () => {
		throw new InvalidPayloadException('It works');
	});
};
```

which works exactly as it should:

<img width="733" alt="CleanShot 2021-12-02 at 16 28 00@2x" src="https://user-images.githubusercontent.com/9141017/144505867-0baf3de6-95a0-47c4-a2b4-f274e21a08eb.png">

---

I think the problem in your hook stems from the fact that you're throwing that error _inside_ an async function _inside_ a `map`. When this bubbles up, it turns into an unexpected error up the tree.

Try replacing the nested (async) maps with something like:

```js
filter('items.update', async (payload, { keys, collection }) => {
	if (collection == 'grade_curricular') {
		const res = searchPayload(payload, 'inicio'); // encontra no directus var com 'inicio'
		const retorn = Object.keys(res); //[ 'segunda_hora_inicio', 'terca_hora_inicio' ]

		for (const fieldPayload of retorn) {
			const resDirectus = payload[fieldPayload];
			const [hourB, ...minutesB] = resDirectus.split(':');
			const consulta = await findParams({ id: keys, field: fieldPayload });

			for (const v of consulta) {
				const [hourA, ...minutesA] = v[fieldPayload].split(':');
				console.log('HourA  ' + hourA + '    HourB   ' + hourB);

				if (hourA == hourB) {
					throw new InvalidPayloadException('Hour is busy for this teacher');
				} else {
					console.log('Nothing to do.');
				}
			}
		}
	}
});
```

(note: i haven't tested the above code; simply refactored it to be sequential rather than a nested semi-synchronous map)

**Comment by hermesalvesbr** [comment]
It's worked. Thanks 👍
