### ISSUE TITLE
Add items.read Hook Filter

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#10164]
### Discussed in https://github.com/directus/directus/discussions/7837, https://github.com/directus/directus/discussions/4847, https://github.com/directus/directus/discussions/3736, and https://github.com/directus/directus/discussions/4812

This issue is to track adding a hook for `ITEMS.READ` (both before and after) so that read responses can be altered or trigger logic. With this feature, we also need to update the docs and include a large warning about the potential for performance issues and breaking the Directus app itself.

**Comment by Oreilles** [comment]
Apparently this was already added and documented with https://github.com/directus/directus/pull/8027 :

https://github.com/directus/directus/blob/481d03df7d4aaa78e0eb78b05aed63d5f49bfbbe/api/src/services/items.ts#L291-L303

**Comment by rijkvanzanten** [comment]
@Oreilles That's an _action_. What those tickets are asking for would be a _filter_ 🙂

**Comment by Sarajin** [comment]
> Apparently this was already added and documented with #8027 #10195 

I'm evaluating DIrectus to use in a project, and this feature is required.  I believe this is only handling the post 'items.read'.  What is needed is a pre-'items.read' (i.e. an emitFilter on items.read).

**Comment by Oreilles** [comment]
> @Oreilles That's an _action_. What those tickets are asking for would be a _filter_ 🙂

Oops, that's true! Allowing modifying the payload feels sketchy since the app will expect specific columns and specific types for those for every query, but I assume the admin's mistakes will be on them...

**Comment by stylefieber** [comment]
> > @Oreilles That's an _action_. What those tickets are asking for would be a _filter_ 🙂
> 
> Oops, that's true! Allowing modifying the payload feels sketchy since the app will expect specific columns and specific types for those for every query, but I assume the admin's mistakes will be on them...

To control what you are doing, you should be able to see if the request is coming from the app or if it's an external API call. We, for example, currently try to manipulate the data which is returned to the client (but there is no hook for this currently).
