### ISSUE TITLE
Updating M2A relationship through snapshot not working

### ISSUE THREAD

**Issue by faridsaud** [directus/directus#10167]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When applying a snapshot that contains an update on the field one_allowed_collections in a M2A relationship, the update doesn't persist, although Directus detect some kind of update.

![directus_update](https://user-images.githubusercontent.com/13280283/144095816-c6724ced-03db-41b9-8bb8-e0700489d0e8.png)

Expected behavior:

`update.yaml` is adding `entity_3` and `entity_4` as part of the `one_allowed_collections` in a M2A relationship for `entity_1_translations`.

If I go to the CMS UI after applying the snapshot, the entities `entity_3` and `entity_4` should be part of the relationship.
![expected](https://user-images.githubusercontent.com/13280283/144095031-ec9b4007-5bf3-4d62-a772-474ee9926cab.png)

Current behavior:
`update.yaml` is not adding `entity_3` and `entity_4` as part of the `one_allowed_collections` in a M2A relationship for `entity_1_translations`.

If I go to the CMS UI after applying the snapshot, the entities `entity_3` and `entity_4` are not part of the relationship.
![wrong](https://user-images.githubusercontent.com/13280283/144095243-07a3cb31-85cd-4f6f-af8d-c67dc5697d39.png)

Snapshots:
[snapshots.zip](https://github.com/directus/directus/files/7627508/snapshots.zip)

### To Reproduce

1. Apply snapshot create.yaml
2. Apply snapshot update.yaml

### What version of Directus are you using?

9.1.2

### What version of Node.js are you using?

v16.13.9

### What database are you using?

Postgres 13-alpine

### What browser are you using?

Chrome

### What operating system are you using?

Directus is running on linux (docker image). Browser is running over macOS.

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
It does seem to realize something changed within relations, but then doesn't properly apply it:

<img width="340" alt="CleanShot 2021-12-02 at 17 09 37@2x" src="https://user-images.githubusercontent.com/9141017/144511196-0ccfa3a7-1f82-40be-ac88-7bacb8f9ab43.png">
