### ISSUE TITLE
Expiration token time from Api is always the same

### ISSUE THREAD

**Issue by NickSettler** [directus/directus#10176]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When sedning POST request to SignIn endpoint API returns object with tokens and expiration time. Expiration time is always the same - `900000`. It doesn't look like being a proper way of how it must work. Using this value I can't detect, if access token has expired or not. Some earlier versions were returning a current time when the token will expire, so it have been enabling to create a proper auto refresh logic

### To Reproduce

1) Deploy a fresh Directus CMS app
2) Send a POST sign in request

### What version of Directus are you using?

9.0.1 - 9.1.2 (maybe even earlier than 9.0.1)

### What version of Node.js are you using?

14.18.0

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu 20.04

### How are you deploying Directus?

docker-compose

**Comment by rijkvanzanten** [comment]
It's the expiration time in milliseconds, eg the amount of milliseconds from the time the token was created until it expires. (https://docs.directus.io/reference/authentication/#response-attributes). The access token's payload also contains the `exp` flag, which is the unix timestamp of when it expires.
