### ISSUE TITLE
Look into supporting/integrating with Docker

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1019]
We need to better understand what is involved in turning Directus into a container on [Docker](https://www.docker.com/)

**Comment by bobmulder** [comment]
Hi guys,

I am looking for a smooth way to add directus to my docker-containerized application... Is there any progress or source I can use?

Greetz

Bob

**Comment by WellingGuzman** [comment]
Hey @bobmulder we are planning on turning Directus into a docker container, but we have nothing yet, I'll get back to you after it's done to let you know.

**Comment by bobmulder** [comment]
Great to hear! Maybe I can help you guys? I am at gitter: gitter.im/bobmulder if you need me ;)

Good luck!

**Comment by beevelop** [comment]
@bobmulder I'm currently playing around with a [dockerized version of Directus](https://github.com/beevelop/docker-directus) and got a first version running. It might suit your needs, but is still WIP.
@benhaynes Is there a way to fix Directus' version? Is there some kind of versioning available at all (as you don't seem to use tags)? I'd like to version the Dockerfile accordingly.

**Comment by bobmulder** [comment]
@beevelop I will take a look at it as soon as possible!

**Comment by WellingGuzman** [comment]
hey @beevelop, actually there's not version at all in term of git tags, we had talked about this, and how I did not push any tags before, so for the next release we are going to publish releases.

Right now what I can do is create a tag with the current version, let me know if that helps.

**Comment by bobmulder** [comment]
I think that would be helpfull using version tags in docker. However @WellingGuzman, what do you think about sticking our heads together to make the container of @beevelop up and running? We could have a chat via gitter together...

**Comment by beevelop** [comment]
Hey @WellingGuzman, @bobmulder and @benhaynes 
sorry for the late reply. It took me some time to get a version running that features a completely automated installation (and afterwards realising you already provide an *undocumented (?)* solution to install via CLI through `bin/directus`).

To give it a shot you can run it with [docker-compose](https://docs.docker.com/compose/) (this simplifies linking the containers and defining the ENVs):
```bash
git clone https://github.com/beevelop/docker-directus
# Adapt docker-compose.yml for your needs (update VIRTUAL_HOST / remove nginx-reverse, etc.)
docker-compose up
```
You should then be able to access your Directus installation by browsing the specified `VIRTUAL_HOST`.

----
@WellingGuzman: Thank you for tagging the last release. I fixed the version in the **Dockerfile** to ensure compatibility between the provided environment (container) and Directus' requirements.

**Comment by WellingGuzman** [comment]
Thank you so much @beevelop.

I'm trying to run this docker container, but after several tries I couldn't.

First I tried this:

```
docker pull beevelop/directus:latest
docker run -it beevelop/directus bash
```

it seemed to work, I logged into the VM, but Directus didn't get installed, and I didn't know how to access this with the default virtual host or any host I put. What am I doing wrong? with vagrant when I run the box (which could be similar to the container) it let me access the server via the IP/Host I configured right away.

Then I tried your solution

```
git clone https://github.com/beevelop/docker-directus
# Adapt docker-compose.yml for your needs (update VIRTUAL_HOST / remove nginx-reverse, etc.)
docker-compose up
```

It keeps throwing me `Illegal instruction: 4` error.

I tried to reinstall using this documentation, https://docs.docker.com/compose/install/ and just hitting `docker-compose --version` throw the same error.

So I tried to install pip and install it via pip, but then I get a different type of error.

```
$ docker-compose up
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.5.2', 'console_scripts', 'docker-compose')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Library/Python/2.7/site-packages/compose/cli/main.py", line 21, in <module>
    from ..progress_stream import StreamOutputError
  File "/Library/Python/2.7/site-packages/compose/progress_stream.py", line 1, in <module>
    from compose import utils
  File "/Library/Python/2.7/site-packages/compose/utils.py", line 11, in <module>
    from six.moves.queue import Empty
ImportError: No module named queue
```

so I need to understand how really docker works first.

----

I'll keep trying until I got it, or you or someone can help me make it works, whichever come first.

Thanks again.

**Comment by beevelop** [comment]
@WellingGuzman seems like your docker-compose installation is kinda broken.

You can launch the containers manually too:
```bash
# CD to a directory where you want to persist the files – e.g.:
mkdir ~/directus && cd ~/directus

# Start the mysql database
docker run -e MYSQL_ROOT_PASSWORD=Un1c0rns_4r3_4w3s0m3 -e MYSQL_DATABASE=directus -e MYSQL_USER=directus -e MYSQL_PASSWORD=Un1c0rn -v `pwd`/db/:/var/lib/mysql/ --name mysql -d mysql:5.5

# Start directus
docker run -e ADMIN_EMAIL=directus@example.com -e SITE_NAME=Dockerectus -e ADMIN_PASSWORD=Un1c0rn -v `pwd`/logs/:/var/www/html/api/logs -v `pwd`/media/:/var/www/html/media --name directus --link mysql:mysql -p 8080:80 -d beevelop/directus
```

You should the be able to access your installation on Port **8080** (change `-p 8080:80` if the port is already in use). Replace `-d` with `-it` to watch the logs flowing.

**Comment by beevelop** [comment]
@WellingGuzman Sorry to bother you again. Unfortunately v6.0.6 is broken for Docker due to the bug you fixed in 26801855580d9bea757d9650cbc11682fd83e52b. So you need to pull the **v6.0.5** explicitly.

**Comment by benhaynes** [comment]
Hey @beevelop – we're wrapping up some new and exciting features for Directus (more info to come) so we're all a bit swamped right now. @WellingGuzman and I will try to get this resolved when we can, but that may be a week or two.

Apologies about the delay... let us know if you have any luck getting this working (pull-request) and we'll review and merge.

Thanks!

**Comment by mkly** [comment]
I see this was changed to Ready and Testing but didn't see any images available so I ended up making one for my use. Is it available somewhere I haven't noticed?

https://github.com/mkly/directus-docker

**Comment by mkly** [comment]
Oh found it, thanks
https://github.com/directus/directus-docker

**Comment by benhaynes** [comment]
That's the one! We'd love any support or contributions to the Directus Docker repo – looks like you have some experience in the matter ;)

**Comment by mkly** [comment]
@benhaynes The supervisor usage pretty much puts it outside of my use case, but it looks great. I'm sure a lot of people will find it useful. :beer:

**Comment by WellingGuzman** [comment]
We already have docker container https://github.com/directus/directus-docker
