### ISSUE TITLE
Trying to change related value display, getting  UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'product_id' and referenced column 'id' in foreign key constraint 'orders_product_id_foreign' are incompatible

### ISSUE THREAD

**Issue by terion-name** [directus/directus#10201]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Given products and orders.

Added a one-to-many relation from product to orders.

Went to orders model to make product display properly:

<img width="1212" alt="Снимок экрана 2021-12-01 в 18 52 08" src="https://user-images.githubusercontent.com/1060205/144278525-9d662faa-7700-42e8-bef7-854c9deb3cd1.png">

<img width="848" alt="Снимок экрана 2021-12-01 в 18 52 12" src="https://user-images.githubusercontent.com/1060205/144278587-020ccbd6-9e98-4a2a-b62b-9e8c46477d02.png">

<img width="846" alt="Снимок экрана 2021-12-01 в 18 52 33" src="https://user-images.githubusercontent.com/1060205/144278619-17197bef-2e92-43a2-9d50-153dbeb51351.png">

Relation field in default state:
<img width="856" alt="Снимок экрана 2021-12-01 в 18 52 46" src="https://user-images.githubusercontent.com/1060205/144278656-7f696e2b-6eed-4a93-b906-572edf26a4ff.png">

Adding this:
<img width="855" alt="Снимок экрана 2021-12-01 в 18 53 08" src="https://user-images.githubusercontent.com/1060205/144278678-4a7f4f98-4075-4442-9a13-916fb1c253b1.png">

Saving and...
<img width="589" alt="Снимок экрана 2021-12-01 в 18 53 14" src="https://user-images.githubusercontent.com/1060205/144278748-5ac37138-9558-45c2-bc5c-60fb682a09f1.png">

### To Reproduce

Create two any models, add a one-to-many relation to first, go to second and repeat steps described above

### Errors Shown

```
{
  "errors": [
    {
      "message": "alter table `orders` modify `product_id` int null - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'product_id' and referenced column 'id' in foreign key constraint 'orders_product_id_foreign' are incompatible.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### What version of Directus are you using?

9.1.2

### What version of Node.js are you using?

v16.12.0

### What database are you using?

mysql

### What browser are you using?

brave

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by terion-name** [comment]
UPDATE!
this happens ONLY if added there a translated field, `title` in this case

<img width="661" alt="Снимок экрана 2021-12-01 в 19 06 22" src="https://user-images.githubusercontent.com/1060205/144280031-38d85df1-5056-4f32-8fcc-187b618a5072.png">

**Comment by rijkvanzanten** [comment]
@terion-name Did you configure the `DB_CHARSET` to match the character set of your database? This issue most often pops up when the character set used in Directus is different from the one used on the database, causing type discrepancies where Directus tries to create relations to columns of the wrong type.

If the problem still persists with that environment variable configured, we'll reopen and keep investigating 👍🏻

**Comment by terion-name** [comment]
@rijkvanzanten where to configure this? I didn't set anything like this, all is default. 
also db charset is utf8mb4, seems to be default for directus?

**Comment by rijkvanzanten** [comment]
@terion-name There's [a `DB_CHARSET` environment variable](https://docs.directus.io/configuration/config-options/#database) you can set. That defaults to `UTF8_GENERAL_CI`.

**Comment by terion-name** [comment]
@rijkvanzanten changed to DB_CHARSET=UTF8MB4, restarted. Didn't help:

<img width="590" alt="Снимок экрана 2021-12-06 в 18 11 00" src="https://user-images.githubusercontent.com/1060205/144880997-925e0681-60cb-4119-9096-6139e59c88d2.png">

**Comment by terion-name** [comment]
and also I want to highlight:

>  This issue most often pops up when the character set used in Directus is different from the one used on the database, causing type discrepancies where Directus tries to create relations to columns of the wrong type.

Problem IS NOT in relations, relation are fine. Problem is only in `display` setting for admin panel

**Comment by beschneider** [comment]
I am getting this exact same error for the same example that the OP has described. I followed the advice as well about DB_CHARSET and still experience the error.

**Comment by rijkvanzanten** [comment]
@beschneider Did you also check all the existing tables in your database to confirm they're all using the same / correct collation?

**Comment by beschneider** [comment]
@rijkvanzanten , I'm not quite sure how to check that (not familiar with that terminology), but all tables and relationships were created through Directus. Is there a screenshot from TablePlus of the MySQL database that would help if I posted, or a query I could execute?

I can't actually test any fixes anymore because I destroyed the Directus app to recreate using SQLite. I didn't delete the old MySQL database, though, so I can check something if it helps.

**Comment by rijkvanzanten** [comment]
@beschneider In TablePlus, you'd want to make sure that these values are the same for every column / table that has it:

![CleanShot 2022-01-03 at 15 14 01@2x](https://user-images.githubusercontent.com/9141017/147975796-6b06e920-11d3-4ced-a039-f0b4c3962e28.png)

(This is on the "Structure" tab in TablePlus)

**Comment by beschneider** [comment]
@rijkvanzanten , ok, that may be it. This first screenshot is of the referencing field, and the second screenshot is of the referenced field. They do not have matching data in the character set and collation columns.

I first created all tables, fields, and relationships through Directus. Is there a possible reason why the character set and collation columns weren't populated by Directus?

<img width="992" alt="Screen Shot 2022-01-03 at 2 39 38 PM" src="https://user-images.githubusercontent.com/75515236/147978100-73232565-ada1-4d3c-8403-55e2aeb6e528.png">

<img width="1015" alt="Screen Shot 2022-01-03 at 2 39 50 PM" src="https://user-images.githubusercontent.com/75515236/147978110-b2236774-42ab-4824-b1bf-4c209c4112f3.png">

**Comment by rijkvanzanten** [comment]
The bottom screenshot actually shows the wrong column. The `food` column in `nutrition_details` references `foods(id)`, not `foods(name)` 🙂

**Comment by beschneider** [comment]
Sorry, you are right! Foods(name) is the field I was trying to reference through the Directus UI that was giving me the error. Ok, here's the correct screenshot:

<img width="1012" alt="Screen Shot 2022-01-03 at 2 55 53 PM" src="https://user-images.githubusercontent.com/75515236/147979495-b0c92dd9-80de-4b44-a17f-be6ecfef0acd.png">

**Comment by rijkvanzanten** [comment]
> Foods(name) is the field I was trying to reference through the Directus UI that was giving me the error. 

Ah interesting! How / where were you trying to reference it from? 🤔

**Comment by beschneider** [comment]
I was trying to reference the food name within the Display Template of Nutrition Details (see screenshot). Every time I tried to add "Name" in that template dialog and save, I would get the same error that the OP posted (sorry, I never took a screenshot of the error). This error occurred in other tables/fields across the app when I would try to reference related fields in the Display Template dialog.

I destroyed the app and rebuilt it verbatim on an SQLite database, and I haven't gotten these errors like I did with the MySQL version of the app.

<img width="852" alt="Screen Shot 2022-01-03 at 3 33 16 PM" src="https://user-images.githubusercontent.com/75515236/147982765-2d75af85-3a8a-416e-bb14-f87be7ff9f3a.png">

**Comment by NecoHorne** [comment]
Did anyone figure out a solution to this problem? 

I still have this issue on the latest version 9.4.3. 

![image](https://user-images.githubusercontent.com/30078491/150327719-346515d1-e1d3-4738-86e8-553bc4946079.png)

![image](https://user-images.githubusercontent.com/30078491/150327758-a7bbda53-cc29-4139-9696-a8c1ed01d454.png)

```
13:09:36 ­ƒÜ¿ alter table `enquiry` modify `vehicle` int null - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'vehicle' and referenced column 'id' in foreign key constraint 'enquiry_vehicle_foreign' are incompatible.
Error: UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'vehicle' and referenced column 'id' in foreign key constraint 'enquiry_vehicle_foreign' are incompatible.

```
![image](https://user-images.githubusercontent.com/30078491/150329600-d2d9722b-ecc2-4c21-bc57-a79366f60a9d.png)

![image](https://user-images.githubusercontent.com/30078491/150329844-79fbfd01-da2f-42cd-8ec1-5896dff68177.png)

**Comment by joselcvarela** [comment]
It seems you are using different types on column `enquiry` from table `vehicle` and the other side of the relation (you didn't posted). Can you check those types?
