### ISSUE TITLE
Permission error on basic file access

### ISSUE THREAD

**Issue by yoanntalagrand** [directus/directus#10203]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Files are no longer publicly accessible via /assets/uuid
Files are loading correctly in the backend but are loaded with a token.
The url displays an error page of type FORBIDDEN You don't have permission to access this.

### To Reproduce

1. Install latest version of directus
2. Create a table with a file field
3. Uploaded a file
4. Try to access via directus.url/assets/uuid

### Errors Shown

FORBIDDEN You don't have permission to access this.

### What version of Directus are you using?

9.1.2

### What version of Node.js are you using?

14.16.0

### What database are you using?

mariadb-server/stable,now 1:10.5.12-0+deb11u1 all

### What browser are you using?

Firefox

### What operating system are you using?

Linux 5.11.22-4-pve

### How are you deploying Directus?

locally, npx

**Comment by rijkvanzanten** [comment]
Make sure to give read access to Directus Files to the Public role if you want files to be publicly accessible 🙂
