### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1020]
This would be an amazing jump forward and would greatly extend Directus' reach – but would require a dedicated dev to take on. Next steps are to find a dev that is interested in working with our team to build out this alternate database type.

If anyone is interested please contact me: ben(a)rngr.org

**Comment by benhaynes** [comment]
This will happen, but it's not an issue – moving this to the roadmap instead (will be published on the repo's wiki soon)

**Comment by HauntedSmores** [comment]
Im looking to use Directus with Heroku and this would be incredible. Just my 2 cents, thanks!

**Comment by benhaynes** [comment]
For those looking to upvote the new feature (Postgres support):

http://feathub.com/directus/directus/+99

Or, let us know if someone wants to help add this to the codebase! We sure do love PRs! 😄

**Comment by puco** [comment]
Guys, what is the status of this? It is hanging on the top as the most requested feature after all.
