### ISSUE TITLE
When I go back to items list from an item page, the page goes back on top and page 1

### ISSUE THREAD

**Issue by alexleboucher** [directus/directus#10223]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

In an items list in table view, if I go on an other page than page 1, I click on an item and I save it or I click on the back arrow button, the items list goes back to the top and on page 1. It should go back to the last position I had before clicking on the item.
It's really annoying...

https://user-images.githubusercontent.com/91946849/144448399-e39719db-6840-4457-9cac-2180b4328856.mov

### To Reproduce

Go on item list
Go to page 2
Click on an item
Go back with the back arrow button or save the item

### What version of Directus are you using?

9.1.2

### What version of Node.js are you using?

10

### What database are you using?

Posgres

### What browser are you using?

Chrome

### What operating system are you using?

macOs

### How are you deploying Directus?

Docker

**Comment by ihsan-96** [comment]
This issue was happening after adding a new item as well.
Would that also be solved with this fix?

**Comment by rijkvanzanten** [comment]
@ihsan-96 yeah same problem 👍🏻
