### ISSUE TITLE
Time series insight doesn't work on SQLite DB

### ISSUE THREAD

**Issue by ffranchina** [directus/directus#10253]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Whenever you try to create a dashboard that makes use of time series, it will silently fail and the result will be an empty graph without any hint on what went wrong.

### Cause
I digged more into the weird behavior and I found the cause:

1. the application queries via API the data to build the graph (eg: `http://example.io/items/temp?groupBy[]=year(date),month(date),day(date)&aggregate={"sum_distinct":["val"]}&filter={"_and":[{"date":{"_gte":"$NOW(-3+months)"}},{"date":{"_lte":"$NOW"}},{}]}&limit=-1`)
2.  the request gets translated into a query like ```select strftime('%Y', `temp`.`date`) AS `date_year`, strftime('%m', `temp`.`date`) AS `date_month`, strftime('%d', `temp`.`date`) AS `date_day`, avg(`temp`.`value`) as `count->null` from `temp` where (`temp`.`date` >= '1630618168068' and `temp`.`date` <= '1638480568069') group by `date_year`, `date_month`, `date_day` order by strftime('%Y', `temp`.`date`) asc;```
3.  it returns `{"data":[{"date_year":null,"date_month":null,"date_day":null}]}` and therefore nothing is produced.

The root cause is the fact that SQLite out of the box does not expect a date formatted as a unix timestamp (https://sqlite.org/lang_datefunc.html#time_values). The desired result can be obtained by using a so called "modifier" (as explained here https://sqlite.org/lang_datefunc.html#modifiers), hence the functions `strftime` should become ```strftime('%Y', `column`, 'unixepoch')```.

But it doesn't end here: having a quick look to the code I could not locate how/where it happens but it seems the timestamps stored in the DB are unusually long (I suspect the dot that separates the seconds from the milliseconds is just trimmed away), therefore now usable for the SQLite logic, the trick is to remove the last part of the date in order to make SQLite understand our timestamp. The final code becomes ```strftime('%Y', `column`/1000, 'unixepoch')```. 

I am quite sure there are more elegant solutions but I don't know the codebase enough to suggest it and, unfortunately, I don't speak TypeScript. I would have liked to solve it by myself and publish a PR but I think it's better I leave this to your specialized hands hoping that my analysis made you spare some time :)

I would be happy to contribute anyway with some guidance! Thanks for your time and this amazing project! :D

### To Reproduce

Just install directus, create a collection of values that could be displayed (eg: id, date, float_value) as a time series and create a dashboard that aims at visualizing it.

### Errors Shown

No errors. The query runs succefully but is not correct to retrieve the correct data.

### What version of Directus are you using?

9.1.2

### What version of Node.js are you using?

16.13.0

### What database are you using?

3.34.0

### What browser are you using?

Firefox

### What operating system are you using?

Linux

### How are you deploying Directus?

npx

**Comment by Oreilles** [comment]
That was very helpful, thanks for the investigation!
