### ISSUE TITLE
Custom module not shown after upgrading to 9.1.2

### ISSUE THREAD

**Issue by MichelSc** [directus/directus#10259]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I  upgraded from 9.0.0 to 9.1.2
I had a custom module (the very example from https://docs.directus.io/extensions/modules/
It worked ok in 9.0.0.
After upgrade to 9.1.2:
- no error message nowhere (server or browser)
- custom extension is mentionned in the start of the server log: OK
- no button for custom module in the module bar: NOK

### To Reproduce

Make the custom module as described in https://docs.directus.io/extensions/modules/.

It did show up in 9.0.0
It does not show up in 9.1.2

### What version of Directus are you using?

9.1.2

### What version of Node.js are you using?

12.22

### What database are you using?

SQLServer Express 2019

### What browser are you using?

Chrome/Firefox

### What operating system are you using?

Windows/Linux

### How are you deploying Directus?

locally

**Comment by benhaynes** [comment]
I assume you enabled it via the project settings?

**Comment by MichelSc** [comment]
No.
Was not aware of this setting.
I now enabled it and it shows up OK.
You may close the issue.
Would be useful to mention in the doc https://docs.directus.io/extensions/modules/
(I re-read it a number of time since yesterday)
Many thanks for your help

**Comment by benhaynes** [comment]
Awesome! We'll leave it open until the docs are updated. 👍
