### ISSUE TITLE
Lost password first install

### ISSUE THREAD

**Issue by ychoucha** [directus/directus#1025]
Hello,

well i can't connect on my directus, how reset the password please ?

when i cliqu on the ?  from the login password forms i have the error : Server error occurred!

so how connect without my password please, or how reset password thanks

**Comment by WellingGuzman** [comment]
Hi @ychoucha as right now, the only way to reset your password is through clicking "?" next to password field. You can hard code it, if you like by doing this:
```php
$composite = $salt . $password;
$newPassword = sha1( $composite );
```
And update `directus_users.password` with `$newPassword`

Is your browser console/server response showing some error?
I'm having difficulties to troubleshoots this type of error, as I can't replicate them.

Are you using your install at a localhost? 

Thanks

**Comment by ychoucha** [comment]
i have this error : 
ok modifie directly on the database with u code i try it this night thanks :)

![directuserror](https://cloud.githubusercontent.com/assets/301074/9831307/7cd871f2-5951-11e5-8893-8e09a80a6c32.jpg)

**Comment by WellingGuzman** [comment]
This issue was happening after we implement phpmailer library, and were having some issues with it, I'm going to try this again.

@benhaynes there's a huge bug I'd say huge but just medium large? anyway, a bug when resetting password, it would reset without asking the user (by email) if he/she wants to actually reset the password.

**Comment by benhaynes** [comment]
Ahh, that is a big issue. Here's what it should be doing:

1. Password reset request
2. Saves `reset_token` and `reset_expiration` in `directus_users`
3. Email goes to user to confirm with URL to reset
4. If the user clicks that link (with the token) before the reset_expiration time then the framework resets the salt/password

This is how it was working previously, @WellingGuzman could you look into what is going wrong? Also, the server error seems to be another problem altogether.

**Comment by benhaynes** [comment]
@WellingGuzman 
This is marked as resolved – is it working? I just tested locally and I never got an email. Do I need to set something specific up?

**Comment by WellingGuzman** [comment]
I lost track of this issue, @benhaynes what happen if we are testing locally, and email doesn't work? what possible solutions should implement? one good one is to add a script that change the password, like this:

```
$ directus user:update_password -uid=1 -upass=123456
```

**Comment by benhaynes** [comment]
Hopefully now that admins can set up email through mandrill or php this should be less of an issue. But yes, a command to change the password on the server would be good to add! We can close this once that script is available.

**Comment by WellingGuzman** [comment]
A better solution will be using a Directus CLI.

Something like this:

```bash
$ directus user:update password <user-id> <new-password> 
```

**Comment by benhaynes** [comment]
Even better – how difficult is this to implement?

@mrwho – any experience with CLI?

**Comment by Wedjaa** [comment]
@benhaynes Will look into it - I havent' used the PHP CLI in a while, but I was already looking into the `directus`  command line for the configuration part of the Docker.

**Comment by WellingGuzman** [comment]
we definitely needs to write the Directus CLI to accept different commands, we can write ourself a simple one or look for simple php cli library.

right now directus cli is basically a way to install directus with three built-in command.

**Comment by benhaynes** [comment]
@Wedjaa 
Just out of curiosity (since I haven't used it yet) – does/will the CLI install ask for setup options (individua prompts) like the GUI install page? (eg: host, port, example content)

**Comment by Wedjaa** [comment]
Not currently -- but it could be easily implemented.

**Comment by benhaynes** [comment]
Excellent! I'll try it out in a few days when I spin up a new client server. This is super exciting, I like how extensible this is becoming...

**Comment by WellingGuzman** [comment]
I made a hotfix for this issue, hopefully this will better done by @Wedjaa PR.

Closed by https://github.com/directus/directus/commit/d8f1bbd0d057ceb8da9f90e4b3690d3dd745daf4

**Comment by YounessTayer** [comment]
Hi;
I never get Directus working on my linux mint local machine. I create a valid user from the phpmyadmin interface (password with SHA1encyption).

Why I get always the following error messge : Wrong username/password?

Thanks;
