### ISSUE TITLE
Broken filter types in SDK

### ISSUE THREAD

**Issue by andrenarchy** [directus/directus#10262]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

In https://github.com/directus/directus/pull/9965, filter types were adjusted but unfortunately it rendered some filters usable.

### To Reproduce

Assume we have a collection `test` with a string field `code`. Then the following filters now give type errors:
```typescript
client.items('test').readMany({ filter: { code: {_in: ['foo', 'bar']} } }) // string[] not assignable to string
client.items('test').readMany({ filter: { code: {_null: true } } }) // true not assignable to string
```
There are probably more filters that fail since the mentioned change.

### What version of Directus are you using?

9.1.2

### What version of Node.js are you using?

16.5.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying Directus?

locally

**Comment by nickrum** [comment]
I think this has been fixed by #10133.
