### ISSUE TITLE
Condition on collection based on the status does not work

### ISSUE THREAD

**Issue by dewita97** [directus/directus#10273]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hello !

I'm encountering a very strange "bug". 

I'm currently trying to make the fields mandatory ONLY when the status of the item is "published". 

Here is the **collection**:

<img width="825" alt="Capture d’écran 2021-12-03 à 16 01 12" src="https://user-images.githubusercontent.com/51268792/144625738-6bd68b14-4cf9-42e5-ab63-26a922c88e81.png">

No field is mandatory, I add this **condition** when i need that a field must be filled in the published state (see below) :

<img width="944" alt="Capture d’écran 2021-12-03 à 16 01 33" src="https://user-images.githubusercontent.com/51268792/144625776-8922675e-a0dc-4f0d-85a7-e894dc9e870d.png">

When I create a new product and it **hasn't been saved in the database yet**, the check is done correctly, and I can't publish my product if it doesn't have all the conditionally required fields filled. 

<img width="1501" alt="Capture d’écran 2021-12-03 à 16 02 23" src="https://user-images.githubusercontent.com/51268792/144625617-0197e021-fc2f-407a-b66f-6622ef93bb30.png">

On the other hand, **once the product is published or drafted once**, the condition no longer takes effect. Even if there is an asterisk next to the field when on the published status, I can still publish my product even if the fields are empty. 

Maybe I'm doing it wrong, but it doesn't seem to work as expected. 

### To Reproduce

1. Create a collection with status option
2. Add some field that you want mandatory (but don't select the required field check box yet !)
3. Click on one field and create a condition based on the status (published) and set the required field for this condition
4. Save
5. Create an item with this new collection and test the published state with empty field. You will see that it works (mandatory field not filled)
6. Save the item with all the required fields in the published state
7. Modify the item by emptying an obligatory field
8. Save as published. 
9. You will see that the item is still published...

### Errors Shown

No error

### What version of Directus are you using?

9.1.2

### What version of Node.js are you using?

16.13.0

### What database are you using?

Mysql 8.0.26

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
Ah, this does actually work as expected, though I can see how it is confusing / not-ideal for this particular use case. The required flag only fires on the create action, as it requires a value to be _submitted_. It doesn't check whether or not a value exists at time of save.

Mind opening a feature request / q&a discussion so we can keep discussing how to optimize this particular use case? 🙂
