### ISSUE TITLE
Unable to read other users information

### ISSUE THREAD

**Issue by juancarlosjr97** [directus/directus#10305]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

A user with app access cannot see any other user even if it has all permissions as enabled.

### To Reproduce

1. Create a new Directus project `npx create-directus-project test-user-role`
2. Complete the installation using SQLite
3. Create a new role named `Noadmin` without admin access but access to all users and roles
4. Create two new users and give them `Noadmin` role 
5. Sign in with one of the new users with the `Noadmin` and check the users available and it will only be their own account

This has been tested locally using Dockerized PostgreSQL v13 and Directus image too and the same error, the only difference is the Dockerized Directus has custom migrations coming from rc version of Directus.

### Errors Shown

No errors, only no users besides their account available. Only a user with a role with admin access can see other users and roles.

### What version of Directus are you using?

9.2.0

### What version of Node.js are you using?

14.17.3 - 16.13.0

### What database are you using?

PostgreSQL 13 - Sqlite 

### What browser are you using?

Chrome, Safari, Firefox

### What operating system are you using?

Linux 4.4.0 - macOS Monterrey

### How are you deploying Directus?

Running Locally - Docker | Bootstrapped Directus

**Comment by licitdev** [comment]
Thank you for your report. It seems to be related to PR #10236. 

@joselcvarela what was the cause behind the empty permissions fix?

**Comment by joselcvarela** [comment]
@licitdev 
I have updated the description of the PR.
The issue I were having was about `permissions.permissions` being null, which should not be handled on filter (I suppose).
