### ISSUE TITLE
Updating schema drops relationships in SQLite

### ISSUE THREAD

**Issue by mslonina** [directus/directus#10307]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Whenever I update the field schema (i.e. changing the default value), the Files references are lost on the content items I have.

I've seen this issue also with other M2A, M2M fields, however I couldn't track it down.

### To Reproduce

1. Create a test model - `Test model`
2. Add a `Files` reference field
3. Add a `TestField` field (it can be a string)
4. Add some content to `Test model`, including uploading/selecting files
5. The files should be referenced and visible when editing the content item
6. Now change the `Default value` in the `TestField`schema and save the field
7. References to files are lost on `Test model`

### Errors Shown

None

### What version of Directus are you using?

9.2.0

### What version of Node.js are you using?

16.3.0

### What database are you using?

Sqlite

### What browser are you using?

Safari, Chrome, Firefox

### What operating system are you using?

macOsS

### How are you deploying Directus?

locally

**Comment by licitdev** [comment]
@mslonina Thank you for your report.

### Notes
- Tested the issue to exist on sqlite but not on postgres.
- The foreign key `test_model_id` in the M2M `test_model_files` gets nullified after updating the default value of another field in `test_model`.

**Comment by rijkvanzanten** [comment]
This is technically a bug in `knex` (https://github.com/knex/knex/issues/4155), but we'll leave the issue open here for visibility, as a lot of duplicates get created.

**Comment by liho00** [comment]
> This is technically a bug in `knex` ([knex/knex#4155](https://github.com/knex/knex/issues/4155)), but we'll leave the issue open here for visibility, as a lot of duplicates get created.

@rijkvanzanten  I suggest to pin this issue or add notes to the documentation for those users who choose to use sqlite, because sqlite is not yet ready for production.

Why do I say so? Imagine that in production, we have a hundred posts with translation content entered, and the content is lost after adding a new field. Writers and developers gonna having hard time on this.


https://user-images.githubusercontent.com/77238199/144959653-add14375-5455-45d3-9aa9-9782e85135b6.mp4

**Comment by rijkvanzanten** [comment]
knex/knex#4155 was fixed. Closing this now, as the next release of knex will include the fix, which therefore fixes this automatically 🎉
