### ISSUE TITLE
Translations removed when added new field to data model

### ISSUE THREAD

**Issue by liho00** [directus/directus#10312]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Translations content missing when added a new field to data model. Besides, deleting the field also removed the translation contents.

Imagine in production, I have hundred posts with keyed in translation contents, and the contents missing after added a single new field. The writer & developer will be having a hard time.

### To Reproduce

1. add new content to translation field.
2. go to the data model, add a new file field.
3. go back to content dashboard, the translation is removed.

video demostration

https://user-images.githubusercontent.com/77238199/144748654-8a14b3c6-04e9-47a6-bffb-c1a0dc5feb9d.mp4

### Errors Shown

checked no error.

### What version of Directus are you using?

9.2.0 (checked latest version 9.2.0)

### What version of Node.js are you using?

14.17.1

### What database are you using?

SQLite3 v5.0.2

### What browser are you using?

chrome

### What operating system are you using?

macOS Big Sur (11)

### How are you deploying Directus?

locally

**Comment by licitdev** [comment]
@liho00 Thank you for your report.

### Notes
- Seems to be the same issue as #10307 where foreign keys get nullified on sqlite.

**Comment by azrikahar** [comment]
As @licitdev pointed out, this is indeed a knex+sqlite specific issue with a more-recent duplicate #9987, and currently it's tracked over at knex/knex#4155 with in-works PR knex/knex#4189.

Hopefully this comment https://github.com/directus/directus/issues/8142#issuecomment-928952629 can shed some light on it as well.

**Comment by liho00** [comment]
> As @licitdev pointed out, this is indeed a knex+sqlite specific issue with a more-recent duplicate #9987, and currently it's tracked over at [knex/knex#4155](https://github.com/knex/knex/issues/4155) with in-works PR [knex/knex#4189](https://github.com/knex/knex/pull/4189).
> 
> Hopefully this comment [#8142 (comment)](https://github.com/directus/directus/issues/8142#issuecomment-928952629) can shed some light on it as well.

@azrikahar  Since you said its sqlite specific issue, I have a question on it, because im now looking for alternate solution. 

Can i use postgresql instead of sqlite? Just want to double confirm postgresql does not having this issue before i migrate the database.

Thanks in advance.

**Comment by azrikahar** [comment]
> Can i merge the pr locally? cuz i saw the PR has been created about a year, but not yet merge.

Unfortunately I can't confirm it'll work as it is still a draft.

> Or can i use postgresql instead of sqlite? Just want to double confirm postgresql does not having this issue before i migrate the database.

Yup! Postgresql will not have this specific issue, so rest assured 👍

**Comment by firatoezcan** [comment]
Can this be merged now? The knex issue is merged and it makes it seem like the application just doesnt handle that case when evaluating the free tier on the cloud.

If I wouldn't have found this issue, I would have dismissed Directus as a viable option now and I can imagine more people would think the same (which is sad because everything else is super nice, it just makes it seem like an issue)

**Comment by rijkvanzanten** [comment]
> Can this be merged now? The knex issue is merged and it makes it seem like the application just doesnt handle that case when evaluating the free tier on the cloud.
> 
> If I wouldn't have found this issue, I would have dismissed Directus as a viable option now and I can imagine more people would think the same (which is sad because everything else is super nice, it just makes it seem like an issue)

Yeah! We fixed the underlying issue on the knex side of things, but there was another big breaking change in knex itself that prevented us from upgrading it Directus side earlier. We're tracking the efforts over on #10842 🙂

**Comment by firatoezcan** [comment]
> > Can this be merged now? The knex issue is merged and it makes it seem like the application just doesnt handle that case when evaluating the free tier on the cloud.
> > If I wouldn't have found this issue, I would have dismissed Directus as a viable option now and I can imagine more people would think the same (which is sad because everything else is super nice, it just makes it seem like an issue)
> 
> Yeah! We fixed the underlying issue on the knex side of things, but there was another big breaking change in knex itself that prevented us from upgrading it Directus side earlier. We're tracking the efforts over on #10842 slightly_smiling_face

Ah wel, then at least future people know where to look at. Thanks for the pointer!
