### ISSUE TITLE
Set UI "default" option values at creation

### ISSUE THREAD

**Issue by WellingGuzman** [directus/directus#1031]
Make the default UI values works, when you add a UI for the first time, without editing the options it wont make use of its default values.

Ex: I found this while creating multiple_files UI, by default you should be able to add files by adding new ones or browse the files you already had uploaded. but as there's not option _yet_ saved on the database it won't let me do it, until I go to settings and save the UI options.

@benhaynes I think you mentioned something related to this but couldn't find the ticket so I open this as I reminder.

**Comment by benhaynes** [comment]
@WellingGuzman Yeah, I mentioned exactly this... not sure if there's a ticket though. Basically defaults need to be gone through to ensure they are the UI default, not only the settings default... since settings aren't entered in the database until you save the first time.

**Comment by WellingGuzman** [comment]
I'm going to add `In-Progress` I'm working on this one, it does work on listview, but I found out it's not working on the UIView itself, neither on UI settings.

**Comment by benhaynes** [comment]
OK, thanks!

**Comment by benhaynes** [comment]
@WellingGuzman 
Does it save the defaults into `directus_ui` or does it just fallback within the UI code? I just created a new TEXT column in the database, then saved it as a WYSIWYG in directus... and it didn't save any options within `directus_ui`.

**Comment by WellingGuzman** [comment]
It does fallback within the UI default variables. let me know if this works for you.
