### ISSUE TITLE
Can not apply schema

### ISSUE THREAD

**Issue by u12206050** [directus/directus#10323]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When running `directus schema apply snapshot.yaml` I get the errors shown below.

### To Reproduce

Setup a new Directus project.
Try applying schema from a different project.

### Errors Shown

```
Would you like to continue? Yes
08:48:17 🚨 "collection" is required
Error: "collection" is required
    at RelationsService.createOne (/opt/homebrew/lib/node_modules/directus/dist/services/relations.js:127:19)
    at /opt/homebrew/lib/node_modules/directus/dist/utils/apply-snapshot.js:77:40
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

The schema is from a 9.0.1 project

### What version of Directus are you using?

9.2.0

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

chrome

### What operating system are you using?

osx

### How are you deploying Directus?

locally

**Comment by u12206050** [comment]
Nevermind, seems like I forgot to update my global directus version as well.
However now I get the following:
```
Would you like to continue? Yes
08:48:17 🚨 "collection" is required
Error: "collection" is required
    at RelationsService.createOne (/opt/homebrew/lib/node_modules/directus/dist/services/relations.js:127:19)
    at /opt/homebrew/lib/node_modules/directus/dist/utils/apply-snapshot.js:77:40
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by rijkvanzanten** [comment]
@u12206050 Could you share the schema snapshot in question?

**Comment by rijkvanzanten** [comment]
I'll close this for now. Happy to take a look if you wanna share the offending schema snapshot 🙂
