### ISSUE TITLE
Missing translation (Dutch)

### ISSUE THREAD

**Issue by Attacler** [directus/directus#10330]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The notifications are not fully translated:
![image](https://user-images.githubusercontent.com/42644889/144833740-8a5169ac-7654-4c32-b7ed-f217b5b46d32.png)
Everything is translated in this printscreen except for the table headers + "You where mentioned in "

### To Reproduce

Switch to the dutch version.
Ping yourself in a comment.
Open the notifications

### What version of Directus are you using?

9.1.2

### What version of Node.js are you using?

17.0.0

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying Directus?

PM2

**Comment by rijkvanzanten** [comment]
This is a bigger discussion on how to do translatable (email) messages, which is tracked here: https://github.com/directus/directus/discussions/8239
