### ISSUE TITLE
/users/me nesting sends just id at some point

### ISSUE THREAD

**Issue by torstenhoegel** [directus/directus#10345]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hi there,

I have the following setup:

m2m connection between a model called project <-> directus_users
I am requesting the /users/me route. But at some point of deep nesting the result just sends me the id as follows:

```
{
data: "731ff9e9-ca87-........." // here is my users id, i am requesting 
}
```

I am sending the following params for fields:

```
          "*",
          "avatar.*",
          "project.id",
          "project.title",
          "project.img",
          "project.description",
          "project.instance.ram",
          "project.viewers.directus_users_id.id",
          "project.viewers.directus_users_id.first_name",
          "project.viewers.directus_users_id.last_name",
          "project.viewers.directus_users_id.email",
          "project.viewers.directus_users_id.avatar",
          "projectviewers.project_id.id",
          "projectviewers.project_id.owner",
          "projectviewers.project_id.title",
          "projectviewers.project_id.img",
          "projectviewers.project_id.description",
          "projectviewers.project_id.instance.ram",
          "projectviewers.project_id.viewers.directus_users_id.id",
          "projectviewers.project_id.viewers.directus_users_id.avatar",

// after this line, the result is just the id, all other stuff is not being sent

          "projectviewers.project_id.viewers.directus_users_id.first_name",
          "projectviewers.project_id.viewers.directus_users_id.last_name",
          "projectviewers.project_id.viewers.directus_users_id.email",
```

Is this some sort of limit or bug?

### To Reproduce

.

### Errors Shown

just id is being sent as response

### What version of Directus are you using?

v9.2.0

### What version of Node.js are you using?

.

### What database are you using?

Postgres 13

### What browser are you using?

.

### What operating system are you using?

.

### How are you deploying Directus?

paas, docker, locally

**Comment by rijkvanzanten** [comment]
To confirm,

```
          "projectviewers.project_id.instance.ram",
          "projectviewers.project_id.viewers.directus_users_id.id",
          "projectviewers.project_id.viewers.directus_users_id.avatar",

// after this line, the result is just the id, all other stuff is not being sent

          "projectviewers.project_id.viewers.directus_users_id.first_name",
          "projectviewers.project_id.viewers.directus_users_id.last_name",
          "projectviewers.project_id.viewers.directus_users_id.email",
```

so `projectviewers.project_id.viewers.directus_users_id.id` and avatar are working, but the other 3 only return the uuid under directus_users_id?

**Comment by torstenhoegel** [comment]
@rijkvanzanten nearly, after putting any more that avatar, the api just gives me back a id as provided above and nothing else.

**Comment by rijkvanzanten** [comment]
Is it based on the amount of fields you're requesting? 🤔 Like if you remove some of the earlier ones like "project.title" etc, do the nested ones start working?

FWIW there isn't any hardcoded limits to this iirc

**Comment by torstenhoegel** [comment]
ok well this makes a lot of sense. actually when i remove anything from above, e.g. project.title the same thing still happens. So probably it's not the length but somewhat part of the nesting or any field

**Comment by rijkvanzanten** [comment]
Very odd! Would you be able to share a schema snapshot / database dump with a minimal reproduction, so I can make sure I'm looking at the exact same setup? 🙂

**Comment by torstenhoegel** [comment]
For sure, I'll export them rn

**Comment by rijkvanzanten** [comment]
@torstenhoegel Do you have CLI access? A `directus schema snapshot ./schema.yaml` generated file would be super helpful in this case as well 🙂

**Comment by torstenhoegel** [comment]
Thank you! That saved tons of time :) 
in terms of github uploads i've added a .txt to the yaml fil
[schema.yaml.txt](https://github.com/directus/directus/files/7663158/schema.yaml.txt)
e

**Comment by torstenhoegel** [comment]
@joselcvarela any ideas on how this happens? :)

**Comment by rijkvanzanten** [comment]
> i've removed some unnecessary collections from the top of the file

This actually caused some conflicts trying to use the schema 😬 The fields / relations for those collections still existed, causing the schema file to be corrupted. 

I've removed all fields/relations that weren't associated to a collection here:
[schema.yaml.txt](https://github.com/directus/directus/files/7713870/schema.yaml.txt)

**Comment by rijkvanzanten** [comment]
I'll close this for now, as I think there might be some data corruption problem going on, rather than a bug in Directus' fields parameter handling.

@torstenhoegel Happy to take a look tho! Would you be able share a database dump with the actual content that's causing this problem? You can share it in private to rijk@directus.io

**Comment by torstenhoegel** [comment]
Thank you for investigating further :) I'll send you a dump tomorrow!
