### ISSUE TITLE
Fields disappear when creating new data model / new fields

### ISSUE THREAD

**Issue by wahyuhenditya** [directus/directus#10361]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When creating new data model / new fields, sometimes the fields disappear from the view but all XHR Requests is returning status code 200 and no console error appear and also sometimes it shows FORBIDDEN error when creating the new fields. On testing, the latency is showing "Excellent connection" and with account that has Administrator privilege

Here's the video to show the bugs
https://streamable.com/4070k8

### To Reproduce

1. Create new data model / Create new fields
2. Fields will disappear

### Errors Shown

No errors on browser console / error log

### What version of Directus are you using?

9.1.2

### What version of Node.js are you using?

14

### What database are you using?

MySQL 5.7.21-21-log

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying Directus?

Docker

**Comment by wahyuhenditya** [comment]
Currently trying to upgrade to version 9.2.1, need to do some further testing on the new version

**Comment by wahyuhenditya** [comment]
Issue still happening on version 9.2.1

**Comment by rijkvanzanten** [comment]
@wahyuhenditya Any caching configuration we should be aware of to debug this?

**Comment by wahyuhenditya** [comment]
@rijkvanzanten cache is not enabled on my app. Apparently I found out that the issue could be from the session, I'm using docker and kubernetes to serve my app and my app actually using 2 container when the issue happening. I reduce the container to only 1 and suddenly the issue resolved itself. Maybe that could help to reproduce the issue.
