### ISSUE TITLE
"Collection doesn't exist"  when adding system fields to new collection

### ISSUE THREAD

**Issue by raphaeltm** [directus/directus#10381]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Running Directus 9.2.1 using `directus/directus:latest` in k8s against a DigitalOcean managed Postgres database.

I just started getting this error today, so I assume it's a bug in the latest version which I see was released yesterday. 

Whenever I try to create a new collection with system fields, I get the following message:
<img width="549" alt="Screen Shot 2021-12-07 at 09 24 21" src="https://user-images.githubusercontent.com/910895/145077492-a08cf592-4f90-4f8e-9613-a6d3cf53fd59.png">

The collection actually gets created, but without the system fields. 

### To Reproduce

I don't have the bandwidth to replicate from scratch at the moment, but if I open up the admin app on Directus 9.2.1 using `directus/directus:latest` in k8s against a DigitalOcean managed Postgres database and I try to create a new collection and check off any of the system fields, I get the error.

### Errors Shown

In the container logs, all I see is:
`request completed POST 400 /relations 28ms`

In the app I see the error screenshotted above. In its copied form from the app:
```
{
  "errors": [
    {
      "message": "Collection \"test_two\" doesn't exist",
      "extensions": {
        "code": "INVALID_PAYLOAD"
      }
    }
  ]
}
```

### What version of Directus are you using?

9.2.1

### What version of Node.js are you using?

16.13.1

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker on K8s

**Comment by raphaeltm** [comment]
I've downgraded to `9.1` in the hopes that it would fix the issue, but that didn't do anything, so there might be another variable causing the issue... The only thing I can think of, which I would assume to be unrelated to any of this but... who knows... is that I didn't have any folders previously. Last night I moved a couple collections into folders. I believe the only things that changed between yesterday (when everything worked) and today are the upgrade and the folders.

**Comment by ulvidamirli** [comment]
Recently, I had this problem. This problem occurred in previous versions of Directus on me. Currently, I'm using Directus 9.0.1.

This occurs when I try to build an M2M relationship with custom table and field names. Also, once happened when I was building an M2O relationship with a table which have a varchar PK field.

I think it would be better to have a code alternative of building tables in Directus. It is a horrible experience when I build tables with SQL and then need to readjust all fields by hand. It really takes time when there is lots of tables and relationhips.

**Comment by raphaeltm** [comment]
@ulvidamirli interesting. In my case it was just a standalone table. Nothing special. 

By the way, as I understand it, you can create tables programmatically using [custom migrations](https://docs.directus.io/extensions/migrations/) 🙂 I haven't used it myself, though.

**Comment by raphaeltm** [comment]
Heya @rijkvanzanten, I've emailed you a db dump from the db where this is happening consistently. Hopefully that's helpful!

We aren't using any caches, so I don't think it's that, unfortunately.

**Comment by rijkvanzanten** [comment]
> We aren't using any caches, so I don't think it's that, unfortunately.
 
@raphaeltm For what it's worth, the schema cache is enabled by default, so it's worth a shot regardless 🙂 Thanks for the dump!

**Comment by raphaeltm** [comment]
@rijkvanzanten I have yet to use the API from anywhere other than a public context. I tried creating a token for my admin user and then adding that to the endpoint to try the mutation [here](https://docs.directus.io/reference/system/utilities/#graphql-5), but it's not showing up in my client, and when I try to run it, I get:

```
{
  "errors": [
    {
      "message": "GraphQL validation error.",
      "extensions": {
        "code": "GRAPHQL_VALIDATION_EXCEPTION",
        "graphqlErrors": [
          {
            "message": "Cannot query field \"utils_cache_clear\" on type \"Mutation\".",
            "locations": [
              {
                "line": 2,
                "column": 3
              }
            ]
          }
        ]
      }
    }
  ],
  "data": null
}
``` 

I _do_ get a bunch of mutations for our content, which I didn't get from the public context, but no `utils_cache_clear`.

Is there a place in the admin UI to clear cache? That would be practical.

**Comment by rijkvanzanten** [comment]
@raphaeltm That mutation exists in the `/graphql/system` endpoint, or as a POST to `/utils/cache/clear` 👍🏻

**Comment by rijkvanzanten** [comment]
> Is there a place in the admin UI to clear cache? That would be practical.

Not as of right now, but I agree! That'd be a great little addition to the settings module.

**Comment by raphaeltm** [comment]
Shoot. I managed to clear cache, but I'm still getting the same error 😕
Hmmm... I'm trying to think of what other context I could provide that would be helpful.
I don't see any traces or anything in the container logs. Is there a way to enable more verbose error logs on the server?

**Comment by raphaeltm** [comment]
Nvm, found it. Setting LOG_LEVEL to trace and trying again... maybe that will help.

**Comment by raphaeltm** [comment]
I found the issue!

We're running Directus in a load-balanced environment, with two instances (in part because we saw intermittent shutdowns/restarts so we wanted to mitigate against that). When scaled down to one instance, everything is fine. When there's more than one instance, it fails.

I'm guessing there's either some sort of race condition, or that the Directus server isn't, as I had assumed, stateless? Is the schema held in memory somehow? (since you mentioned caching, but I'm unsure about how that works under the hood) I'm guessing the process is split into a couple requests; the first goes to one server whose cache is invalidated, but the second still has the old schema cached. The second server gets the request to create the system columns, and fails.

I thought cache was disabled by default, but I see the schema is cached. Since we don't have an external cache, I guess the solution is either to disable schema caching, setup a redis instance, or scale down to 1 and figure out why Directus occasionally schutz down and starts up again.

**Comment by rijkvanzanten** [comment]
Ah yes that's definitely it. By default, the schema cache is enabled and the memory cache is used. When you scale up horizontally to multiple Directus instances, make sure you rely on a shared resources for caches, rate limiting, and file storage to prevent issues like these 👍🏻
