### ISSUE TITLE
Nested Translation fields don't respect required or min/max attributes

### ISSUE THREAD

**Issue by bposman** [directus/directus#10394]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When saving content with translation fields set to be required or with min/max values, the form saves without error regardless of what is contained in the fields.

### To Reproduce

1. Create a collection
2. Add translations field to the collection
3. Add one or more fields to the related translation collection, setting the required attribute on them.
4. Create new item for collection
5. Enter values into the field(s)
6. Click save button
7. Reload previously created item
8. Clear values in field(s)
9. Click save button
10. No errors are shown, form submits even with empty values

https://user-images.githubusercontent.com/94536727/145212819-a7efaea3-1ec2-46d9-98cf-a45ebddaad6f.mp4

### Errors Shown

No errors shown

### What version of Directus are you using?

9.2.1

### What version of Node.js are you using?

14.18.1

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
Required only checks whether or not a value is submitted on creation. Please see and leave any thoughts on https://github.com/directus/directus/discussions/10276#discussioncomment-1745224 for a more in-depth discussion on how this should / will work in the (near) future 🙂

**Comment by bposman** [comment]
Thanks for looking at this @rijkvanzanten. I will check out that issue as I was not aware that required fields were only for creation.

However, this issue with translation sub-fields **occurs on creation** as well as updates. Also numeric field max values are not respected either.

https://user-images.githubusercontent.com/94536727/145244648-60513aee-bd16-45cc-97be-5aaa5ab4f122.mp4

**Comment by mr-sanders** [comment]
@bposman it starts to respect required rules if I make the "translations" field itself required. But it works silently: you won't see any GUI errors. Only network ones.
