### ISSUE TITLE
JWT Token not passed to auth.jwt Event

### ISSUE THREAD

**Issue by nicam** [directus/directus#10414]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

According to the documentation on the Filter events, the `auth.jwt` filter should receive the auth token but all it receives is the users id.

![Screenshot 2021-12-09 at 12 48 40](https://user-images.githubusercontent.com/182071/145392633-9bb534c8-815a-4251-b57a-ea0cb2e4404f.png)

This is visible in the core here: https://github.com/directus/directus/blob/ca19cb1a999a030ee69703eda26dea809014665b/api/src/services/authentication.ts#L278

 We're trying to assign the correct role based on the contents of the JWT token. In Directus 9.0.0 we were able to do this with the event hook `oauth.*.login.before` but at the moment it seems there's no more way to access the access_token to retrieve the roles from it.

Thanks for your help!

### To Reproduce

Login with Oauth or OpenidConnect, create a filter for `auth.login`.

### What version of Directus are you using?

9.2.1

### What version of Node.js are you using?

16.13.1

### What database are you using?

MariaDB

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
The `auth.jwt` event triggers when a JWT is generated for the auth session, not when the JWT is decoded in the API. The only data that's available in the payload of the event is the data that Directus will encode into the token when the JWT is generated 👍🏻

**Comment by nicam** [comment]
Thanks for the Feedback. I'll open a PR to add the capability into another Event.
