### ISSUE TITLE
Non admin role permissions issue (403 error) when adding new items from child collection to parent

### ISSUE THREAD

**Issue by pchebro** [directus/directus#10442]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Directus version: 9.0.0-rc.64

I have created a new role to manage content with less privilege's compared to Admin. The new role permissions are set to have create, read and update permissions to all custom collections. I'm getting permission denied error when creating child item from parent collection. Is there any custom code we have to write? Attaching the permissions screenshot for our new role. 

### To Reproduce

Create a parent and child collection, add many to one relation ship of parent collection id to child collection. Try to add new item from parent collection. On clicking save (green check), getting permission denied error.

![image](https://user-images.githubusercontent.com/89423003/145622512-e700dd8d-bc08-4193-9bc3-a45e6fc3e2f2.png)

### Errors Shown

Permission denied error

### What version of Directus are you using?

9.0.0-rc.64

### What version of Node.js are you using?

12

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

PaaS

**Comment by pchebro** [comment]
This issue is same as the one described in https://github.com/directus/directus/discussions/9972

**Comment by rijkvanzanten** [comment]
Please make sure you're on the latest version. If the problem persists in the latest version, we can reopen and investigate 👍🏻

**Comment by pchebro** [comment]
Thanks for your response. 
What is the recommended latest Directus version to install? Also, any plans to address the bug mentioned above in version 9.0.0.rc64?

**Comment by rijkvanzanten** [comment]
The latest version is always the recommended version.

> Also, any plans to address the bug mentioned above in version 9.0.0.rc64?

Addressing a bug in a particular version means releasing a new version with the fix. Every release includes fixes for bugs that existed in previous versions 👍🏻
