### ISSUE TITLE
Auto Refresh in JS SDK not working

### ISSUE THREAD

**Issue by NickSettler** [directus/directus#10456]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Setting the option to use authRefresh does nothing. Auto refresh is not happening when I have an expired token

### To Reproduce

1) Set up a clear project with directus JS SDK
2) Init a new DirectusSDK object and set the following configuration
```js
auth: {
  mode: "json",
  autoRefresh: true,
},
storage: {
  mode: "LocalStorage",
},
```
3) Auth using SDK
4) Wait until the auth_token will expire
5) Try to make read request to any model without public access permissions

### Errors Shown

Error: Token expired.
    at Transport.request (interopRequireDefault.js:8)
    at async Transport.get (interopRequireDefault.js:8)
    at async ItemsHandler.readMany (interopRequireDefault.js:8)

### What version of Directus are you using?

9.2.2

### What version of Node.js are you using?

14.18.0

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu 20.04

### How are you deploying Directus?

docker-compose

**Comment by paescuj** [comment]
Do you see any other errors in the console? Especially from the auth refresh request?

**Comment by joselcvarela** [comment]
Hello @NickSettler 
I am just testing this and cannot reproduce, can you provide a working repo or at least the code you are using?

**Comment by NickSettler** [comment]
Here is the gist with a part of code how I create Directus singleton instance

https://gist.github.com/NickSettler/6894f0d9a3c799d93d36959b0b4b881a

**Comment by NickSettler** [comment]
There are methods for the API class I use to sign in and sign out

https://gist.github.com/NickSettler/bbd32896bb3c4a8a51c8bc2256c084a0

**Comment by joselcvarela** [comment]
Can you tell what do you have on these env variables?
```sh
ACCESS_TOKEN_TTL=
REFRESH_TOKEN_TTL=
REFRESH_TOKEN_COOKIE_DOMAIN=
REFRESH_TOKEN_COOKIE_SECURE=
REFRESH_TOKEN_COOKIE_SAME_SITE=
REFRESH_TOKEN_COOKIE_NAME=
```

**Comment by NickSettler** [comment]
No, there are no such variables in .env file

**Comment by developer-appdam** [comment]
Same issue here. What's the outcome?

**Comment by joselcvarela** [comment]
@developer-appdam without a reproduction repository it's not possible to figure what's the problem.
Are you able to provide one?

**Comment by developer-appdam** [comment]
> @developer-appdam without a reproduction repository it's not possible to figure what's the problem. Are you able to provide one?

Yes, pretty simple. I just followed the implementation on the site. 
As soon as I do the login, after 15 minutes it keeps saying Token expired but it doesn't autorefresh...

**Comment by krazyjakee** [comment]
I can confirm an absolute minimal set up using copy pasted code from the documentation produces this issue.

**Comment by krazyjakee** [comment]
I notice more reports are coming through. If we're doing nothing special with the base software then it would be more productive for someone to provide a reproduction repository where the automatic token refresh actually works because I've tried everything for weeks and this is pretty core functionality to the SDK auth flow.

@joselcvarela can you tell us what you have for these vars? Maybe we can start there.

```
ACCESS_TOKEN_TTL=
REFRESH_TOKEN_TTL=
REFRESH_TOKEN_COOKIE_DOMAIN=
REFRESH_TOKEN_COOKIE_SECURE=
REFRESH_TOKEN_COOKIE_SAME_SITE=
REFRESH_TOKEN_COOKIE_NAME=
```

**Comment by dataexcess** [comment]
> I notice more reports are coming through. If we're doing nothing special than the base software defaults then it would be more productive for someone to provide a reproduction repository where the automatic token refresh **actually works** because I've tried everything for weeks and this is pretty core functionality to the SDK auth flow.
> 
> @joselcvarela can you tell us what you have for these vars? Maybe we can start there.
> 
> ```
> ACCESS_TOKEN_TTL=
> REFRESH_TOKEN_TTL=
> REFRESH_TOKEN_COOKIE_DOMAIN=
> REFRESH_TOKEN_COOKIE_SECURE=
> REFRESH_TOKEN_COOKIE_SAME_SITE=
> REFRESH_TOKEN_COOKIE_NAME=
> ```

Exactly my thoughts! I have the exact same problem, and to inititalise the SDK I am not using any config object (which should mean it should use the defaults which is autorefresh=on). To help with things I will share what I have for my .env vars:

ACCESS_TOKEN_TTL="15m"
REFRESH_TOKEN_TTL="7d"
REFRESH_TOKEN_COOKIE_SECURE=false
REFRESH_TOKEN_COOKIE_SAME_SITE="lax"

(I am not using REFRESH_TOKEN_COOKIE_DOMAIN or REFRESH_TOKEN_COOKIE_NAME it seems... Should I ?)

Please Directus devs, I love Directus so much! But this core feature not functioning properly is a real blocker for my website. Only way to fix my website not working after this error appears is telling my users to clear their cookies... and disable login.

**Comment by jeverduzco** [comment]
I have the same problem; I log in correctly but after 15 minutes the requests fail with the error "Token expired".

**Comment by gustavodipietrogva** [comment]
Same, this issue is making the web-app we built on Directus unusable since the users keep on getting disconnected after a short period of time.

**Comment by metalmarco** [comment]
Same here. Minimal setup. We don't want to use static tokens for security concerns.

**Comment by NilsBaumgartner1994** [comment]
Same here. Minimal setup. We don't want to use static tokens for security concerns.

**Comment by NilsBaumgartner1994** [comment]
I am also facing this issue that the auto refresh is not working. Thats not very cool.

**Comment by br41nslug** [comment]
@NilsBaumgartner1994 Are you still using the old SDK this issue was about? Please do open a new issue if you're running into a new issue.

**Comment by NilsBaumgartner1994** [comment]
I found a workaround for this, which I use in my native app

**Comment by NilsBaumgartner1994** [comment]
```
static createAuthentificationStorage(
        get: () => Promise<AuthenticationData | null> | AuthenticationData | null,
        set: (value: AuthenticationData | null) => Promise<void> | void
    ){
        //console.log("createAuthentificationStorage called")
        if(!ServerAPI.simpleAuthentificationStorage){
            //console.log("createAuthentificationStorage first time created")
            ServerAPI.simpleAuthentificationStorage = {
                get: async () => {
                    let result = await get();
                    //console.log("simpleAuthentificationStorage get", result)
                    return result;
                },
                set: async (value: AuthenticationData | null) => {
                    //console.log("simpleAuthentificationStorage set", value)
                    await set(value);
                    //console.log("simpleAuthentificationStorage set done")
                }
            }
        }
    }


 let authconfig:  Partial<AuthenticationConfig> = {
                    autoRefresh: true,
                    //msRefreshBeforeExpires: number;
                    credentials: "include",
                    storage: authentificationStorage
                }

                const client = createDirectus(ServerAPI.getServerUrl())
                    .with(authentication('json', authconfig))
                    .with(graphql())
                    .with(rest());
                ServerAPI.client = client;
```

**Comment by NilsBaumgartner1994** [comment]
This method allows me to save credentials in a secured storage, so that I am able to reload them at app restart
