### ISSUE TITLE
Improvement: Enable customization of subject line for password reset

### ISSUE THREAD

**Issue by eikaramba** [directus/directus#10460]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

although the users service allows a custom subject line, the value is not set by the actual reset endpoint. i would argue to pass that variable along to support i18n. currently the subject line is always english.

see https://github.com/directus/directus/search?q=requestPasswordReset to understand the logic

### To Reproduce

execute password reset

### What version of Directus are you using?

9.2.2

### What version of Node.js are you using?

16.6.1

### What database are you using?

SQLITE

### What browser are you using?

FF

### What operating system are you using?

win64

### How are you deploying Directus?

locally

**Comment by eikaramba** [comment]
i mean this is quite easy to do. if approved, i can even pass a PR. but maybe you do not like to include the subject line into the endpoint, but instead want to make this configurable from the admin UI

**Comment by eikaramba** [comment]
i also have some other ideas in regard to the email service.
- add backend api url as a variable (currently only logo and color is there, but the actual backend url needs to be hardcoded). maybe one could even pass any abritrary environment variable.
- if template has .mjml ending, e.g.  mytemplate.mjml.liquid use mjml renderer before using liquid. i use this in other projects and it is an incredible advantage for every developer to just use mjml instead of html. it is easy to implement.

i really don't know how much time i should spent doing this if this is maybe not wanted. just leaving this here for now and if anyone says "go for it" then i will make my hands dirty :)

**Comment by rijkvanzanten** [comment]
Heya!

I'd rather treat this as a single sprint to add I18N to all emails (including subjects) and notifications (as per https://github.com/directus/directus/discussions/8239).

As for the MJML support; I hadn't heard of that before! Looks useful. That being said, I think we should choose between liquid or mjml based on the extension, rather than trying to do both. Is there any way to pass variables to an MJML template during render?

**Comment by rijkvanzanten** [comment]
Lets keep the discussion around translations on the referenced discussion (#8239) and lets create a new discussion to add support for MJML 🙂

**Comment by azrikahar** [comment]
For reference purpose, the aforementioned new discussion for MJML support can be found here: #10809
