### ISSUE TITLE
Images show as broken once added to wysiwyg editor

### ISSUE THREAD

**Issue by daveharrisonbcc** [directus/directus#10469]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When I insert an image into a wysiwyg editor sometimes it shows as broken. If I save and refresh the page the image usually shows.

[**maltejur** recommended opening an issue](https://github.com/directus/directus/pull/10054#issuecomment-991105116) and made this suggestion:

> ..it seems like the access token that is added to the image url temporarily doesn't become valid only until a few seconds after the picture has failed to load in the editor (You can inspect the broken image in the browser inspector, open it in a new tab, refresh with Ctrl+F5 and see that the image actually works).

### To Reproduce

Create a wysiwyg editor and use the toolbar to insert an image
Upload a new image to add to the editor
Image appears broken
Save and refresh, image will show

### What version of Directus are you using?

9.2.2

### What version of Node.js are you using?

14.17.6

### What database are you using?

MySQL

### What browser are you using?

Chrome, Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment]
Unfortunately I can't seem to reproduce this on my end. Would you mind reviewing the following clip and see whether I've misunderstood the reproduction steps?

https://user-images.githubusercontent.com/42867097/145789359-73666581-3db9-4875-a2fc-10742ef43466.mp4

> When I insert an image into a wysiwyg editor sometimes it shows as broken

Just to clarify, based the clip above, does it show as broken within the drawer right after uploading, or in the WYSIWYG editor _after_ we close the drawer?

**Comment by daveharrisonbcc** [comment]
Hi, thanks for looking into this.

It looks like you're using the exact steps that I am. The image isn't broken in the drawer after uploading, only once it is added to the editor when you close the drawer.

https://user-images.githubusercontent.com/66117030/145793610-9bb352d6-4e8b-43b5-8e52-4a1c74650d4b.mp4

**Comment by rijkvanzanten** [comment]
@daveharrisonbcc Would you be able to inspect that `<img>` tag using the browser dev tools? Directus should add your users temporary session access token to the image url for access control in the preview, but something seems to be going south in there 🤔

**Comment by daveharrisonbcc** [comment]
If I inspect the <img> tag it shows the url with the access token. If I open that link in a new tab and refresh, the image loads. I think **maltejur** was onto something with the idea that the token wasn't valid at the point the image loads into the editor but becomes valid afterwards.

Is it possible that there's the temporary token isn't validating quick enough on my install?

**Comment by maltejur** [comment]
After trying it out a bit myself, it seems that this happens every time a image was just uploaded (at least for me). If the image already is from the file library, everything works as expected.

Also again the thing that the URLs are valid when visiting them manually.

https://user-images.githubusercontent.com/48161361/145851004-312dda1f-0540-4c62-b1e4-25f282ee6d4d.mp4

On Firefox 94.0.2 (Arch Linux)

**Comment by daveharrisonbcc** [comment]
@maltejur I think you might be right about it being only when you upload. I thought I'd had a few images do it that were already in the library but I might have been mistaken.

**Comment by daveharrisonbcc** [comment]
I've just done another test. If I upload an image into the library directly, then I go from the library to add an image to the article (or any collection) wysiwyg it comes in as a broken image. I have to refresh the browser for it to load.

**Comment by arladmin** [comment]
I'm also facing the same issue: Image appears broken once added to the WYSIWYG editor.
![image](https://user-images.githubusercontent.com/64059154/156098097-95bfa9f7-983c-4c98-b802-3da63bf5c1de.png)

Also, if i try to access the image by its URL in the browser, i get this error:
```
{"errors":[{"message":"You don't have permission to access this.","extensions":{"code":"FORBIDDEN"}}]}
```

**Comment by licitdev** [comment]
@arladmin Is a static access token provided? 

https://user-images.githubusercontent.com/26413686/156100489-84f86d7e-77e0-454b-8bca-a9443cc7f3c2.mov

**Comment by arladmin** [comment]
> @arladmin Is a static access token provided?
> 
>  Screen.Recording.2022-03-01.at.11.39.08.AM.mov

@licitdev Nope. Didn't know about this.
Which static token to provide here?

**Comment by licitdev** [comment]
@arladmin You have to add a token to a user. For me, I created a new role without `App` and `Admin` Access. This new role only allows for read access to `directus_files`.

![Screenshot 2022-03-01 at 11 58 38 AM](https://user-images.githubusercontent.com/26413686/156102928-4b001bf2-07e2-453a-8e44-9b6d34784613.png)

> Added a static token to the field. Still the same issue.

Please test if you can access the file via `http://{server url}/files/{file id}?access_token={access token}`. Please also verify if the role has read permissions to `directus_files`. Thank you.

**Comment by arladmin** [comment]
@licitdev Thanks!!
This works

**Comment by hhimanshu** [comment]
Things have change since then it seems. Now,
1. You have to first go to the User Preferences and Click on `+` icon to generate a new randomly generated token. Copy this token value.
2. Then, you edit the `WYSIWYG` field and paste the token value and save it.
3. Next, you upload the image and save.
4. Come back to your content again, and you will see the images lined up correctly.
