### ISSUE TITLE
SQLITE hangs when updating M2M relationships with one_deselect_action=delete

### ISSUE THREAD

**Issue by eikaramba** [directus/directus#10462]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

sqlite hangs due to multiple transactions at the same time
see also

https://github.com/directus/directus/discussions/6888

### To Reproduce

Follow https://docs.directus.io/getting-started/installation/cli/ starter guide

1) use sqlite
2) start directus and create 2 data models (add name text field to both to be able to save data)
- posts
- tags
3) create m2m model between the 2 upper models (tags has posts, posts has tags)
4) allow public role ALL CRUD operations
5) **set on deselete action to cascase to posts.tags field**
![grafik](https://user-images.githubusercontent.com/1320525/145731553-71470983-4607-4b66-b65b-3fbeb5db2098.png)

6) add 1 item into each model (just add name)
7) execute this TWO times (first one succeeds)

```
PATCH http://localhost:8055/items/posts/1
{
    "name":"post name changed",
    "tags":[
        {"tags_id":1}
        ]
}
```

8) second one: server hangs with `Knex: Timeout acquiring a connection. The pool is probably full.`

### What version of Directus are you using?

9.2.2

### What version of Node.js are you using?

16.6.1

### What database are you using?

SQLITE

### What browser are you using?

FF

### What operating system are you using?

win64

### How are you deploying Directus?

locally

**Comment by eikaramba** [comment]
i wanted to try to avoid the ghost entries which happen when you update the item with a new relation, as you see above. then the old entries always remain in the database, thus i thought i might update to cascade. but unfortunately it seems directus is then maybe trying to delete everything and is doing this in multiple transactions which sqlite does not support (this is only my guess)

**Comment by eikaramba** [comment]
in regards to the clean up i am now using a action. but honestly this feels wrong

```js
action("posts_tags.items.create", async ( {payload,key}, { accountability,schema,database }) => {
    //clean up
    const junctionServiceAdmin = new ItemsService("posts_tags",{ schema, knex: database });
    await junctionServiceAdmin.deleteByQuery({ filter: { _or:[{posts_id: {_null:true} },{tags_id: {_null:true} }]}});
  });
```

**Comment by eikaramba** [comment]
this problem is still there on 9.10.0

it seems the authorizationService is somehow stalling the knex transaction pool? Will further try to debug and see what i can do.

![grafik](https://user-images.githubusercontent.com/1320525/168498589-bc252b54-7d80-40a9-acb9-5220b0906254.png)

**Comment by eikaramba** [comment]
i think i found it! this is missing. I will push a PR. from my initial tests at least sqlite is now working with cascading on_delete foreign contraints :) YEAHH
![grafik](https://user-images.githubusercontent.com/1320525/168498782-5d1314d2-1478-40bf-b1e0-3aaa44db91f5.png)

**Comment by rijkvanzanten** [comment]
> i think i found it! this is missing. I will push a PR (my first for directus ❤️ ). from my initial tests at least sqlite is now working with cascading on_delete foreign contraints :) YEAHH

Yeeeeeeeeeeeeehaw 🤠 


> I will push a PR (my first for directus ❤️ )

technically already your second! 🙊 https://github.com/directus/directus/pull/10569 was the first ❤️
