### ISSUE TITLE
Error Message when trying to create a new User Group

### ISSUE THREAD

**Issue by Mahjouba91** [directus/directus#1047]
When I try to add a new User Group, after entering the User group name, I got this error message :

```
Error
Error: Uncaught TypeError: Cannot read property 'get' of undefined File: http://127.0.0.1/Directus/app/helpers/model.js?bust=4776f82f973683283d27100867e1f2f319c9bb34 Line:11
```

By the way, The page display the loader spinner without a stop.

When I try to reload the page, the user group is created

**Comment by Mahjouba91** [comment]
Is it possible that a git pull of your project to have your last commits corrupt the database ? 

I tried some things on my personnal user, and since this moment I can't see any user in the user table, even when I created a new one. It's strange.

**Comment by WellingGuzman** [comment]
@Mahjouba91 This is certainly strange, thanks for letting us knows, we are taking care of this right now.

It also seems relatad with #1045 and #1046 

Thanks

**Comment by benhaynes** [comment]
This has been resolved – it was due to an issue with the implementation of custom primary key. Please let us know if you continue to have problem with this.
