### ISSUE TITLE
App: uploading a file without extension breaks interface

### ISSUE THREAD

**Issue by joselcvarela** [directus/directus#10475]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

After uploading a file without file extension the image interface does not appear properly.
Can't click on buttons, but I was able to override image by clicking on `Clear Value`.

![image](https://user-images.githubusercontent.com/14039341/145841663-ae9bb296-a4fb-44af-b1a1-68e67182b015.png)

Possible solutions: 
- API: Deny uploads without file extension (Nope, I believe)
- API: Try to guess file extension using some technique like file magic numbers (could be helpful in some use cases)
- App: Show some placeholder / warning (easier to implement)

### To Reproduce

In my use case:
1. Create an image field on some collection
2. Upload an image without file extension using that interface

### Errors Shown

No errors, just ugly and unusable UI.

### What version of Directus are you using?

9.2.2 (73faf14d4)

### What version of Node.js are you using?

v16.13.0

### What database are you using?

-

### What browser are you using?

Edge

### What operating system are you using?

macOS

### How are you deploying Directus?

Locally

**Comment by rijkvanzanten** [comment]
> App: Show some placeholder / warning (easier to implement)

**Comment by azrikahar** [comment]
Just a note for reference: although #11898 is technically a different component (`<file-preview>` rather than `<file-image>` for this issue), perhaps we can reuse the placeholder design here once it gets finalized over there.
