### ISSUE TITLE
M2A's items doesn't appear at every time

### ISSUE THREAD

**Issue by vhaguet** [directus/directus#10474]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Constructor's items (M2A) actually doesn't appear at every time when I refresh my detail page. Maybe is it related to pull-request [10368](https://github.com/directus/directus/pull/10368).

https://user-images.githubusercontent.com/66834462/145810350-af1f3c04-3a20-43ba-8e5d-467884637b56.mov

### To Reproduce

- Create table m2a (constructor) and add items to it
- Upgrade directus from 9.2.1 to 9.2.2
- Items are not visible everytime I refresh the detail page

### What version of Directus are you using?

9.2.2

### What version of Node.js are you using?

16.13.1

### What database are you using?

Postgis 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by avatarbabe** [comment]
Having the same problem with 9.2.2. But for me the related items never show up.  Works fine with 9.2.1 though.

**Comment by RaphaelBP** [comment]
Same problem with 9.3.0
