### ISSUE TITLE
GCS error messages.

### ISSUE THREAD

**Issue by dunods** [directus/directus#10498]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

i got an error 'A bucket name is needed to use Cloud Storage.'
with .env as below

```
STORAGE_LOCATIONS="local,gcs"
STORAGE_LOCAL_DRIVER="gcs"
STORAGE_LOCAL_ROOT="./uploads"

STORAGE_GCS_KEY_FILENAME="./gcs_key.json"
STORAGE_GCS_BUCKET="https://storage.googleapis.com/mybucket/images"
```

using directus 9.0.0

### To Reproduce

STORAGE_LOCATIONS="local,gcs"
STORAGE_LOCAL_DRIVER="gcs"
STORAGE_LOCAL_ROOT="./uploads"

STORAGE_GCS_KEY_FILENAME="./gcs_key.json"
STORAGE_GCS_BUCKET="https://storage.googleapis.com/mybucket/images"

### Errors Shown

i got an error 'A bucket name is needed to use Cloud Storage.'

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

16.13.0

### What database are you using?

postgres 13

### What browser are you using?

chrome

### What operating system are you using?

mac

### How are you deploying Directus?

linux

**Comment by rijkvanzanten** [comment]
You're missing the driver used for the GCS location:

```
STORAGE_GCS_DRIVER="gcs"
```

It also looks like you're configuring your local location to use gcs as well, which feels like a mistake. Try using the following:

```
STORAGE_LOCATIONS="gcs"

STORAGE_GCS_DRIVER="gcs"
STORAGE_GCS_KEY_FILENAME="./gcs_key.json"
STORAGE_GCS_BUCKET="https://storage.googleapis.com/mybucket/images"
```

**Comment by dunods** [comment]
finally manage to upload using this following code

`STORAGE_GCS_DRIVER="gcs"`
`STORAGE_GCS_ROOT="images"`
`STORAGE_GCS_KEY_FILENAME="./gcs_key.json"`
`STORAGE_GCS_BUCKET="mybucket"`

is there any chance to use multiple storage location driver ?

**Comment by rijkvanzanten** [comment]
The API already supports it, but the app hasn't caught up yet. If you configure more than 1 storage location, the app will only use the first one for uploads
