### ISSUE TITLE
`@directus/gatsby-source-directus` Doesn't get my content from directus

### ISSUE THREAD

**Issue by AhmedMesawer** [directus/directus#10495]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

after installing the plugin and configuring it like the docs and opening gatsby query explorer I can't find my content data returned
![image](https://user-images.githubusercontent.com/35766435/145972983-34bf5241-95dc-4e19-aac3-74e3c77ff8f2.png)

### To Reproduce

install `@directus/gatsby-source-directus` on gatsby app and configure it for public directus api

### What version of Directus are you using?

9.2.1

### What version of Node.js are you using?

14.17.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying Directus?

Docker

**Comment by joselcvarela** [comment]
Hello @AhmedMesawer 
Can you show your `gatsby-node.js` file?
It seems to be working properly here.

**Comment by rijkvanzanten** [comment]
Also make sure you're on the latest version. IIRC there were a quite a few Gatsby related fixes and tweaks in v9.2.2

**Comment by AhmedMesawer** [comment]
@rijkvanzanten I updated to version 9.2.2 now the plugin gives me 500 status code I think this last commit of the plugin related to something to fix this https://github.com/directus/directus/commit/116e683e1f11fc5ba075fcc1deec9540b445aba0

**Comment by AhmedMesawer** [comment]
@joselcvarela I don't think that my `gatsby-node.js` will affect anything I just query the content and use it to create pages

**Comment by joselcvarela** [comment]
> @rijkvanzanten I updated to version 9.2.2 now the plugin gives me 500 status code I think this last commit of the plugin related to something to fix this [116e683](https://github.com/directus/directus/commit/116e683e1f11fc5ba075fcc1deec9540b445aba0)

That's not posible because that commit is not released yet.


> @joselcvarela I don't think that my `gatsby-node.js` will affect anything I just query the content and use it to create pages

Yes it can affect if you misconfigured the plugin.
But about Gatsby, what  version are you using?

**Comment by AhmedMesawer** [comment]
@joselcvarela oh I found `"gatsby": "^3.2.1"`, so I will upgrade gatsby and try again

**Comment by AhmedMesawer** [comment]
>

**Comment by joselcvarela** [comment]
Hey @AhmedMesawer, did upgrade work?

**Comment by AhmedMesawer** [comment]
@joselcvarela unfortunately upgrading causes more issues because of `graphql` package `Error: Cannot find module 'graphql'` and when install it gives me another error 
```
Error: Cannot use GraphQLScalarType "JSON" from another module or realm.
  Ensure that there is only one instance of "graphql" in the node_modules
  directory. If different versions of "graphql" are the dependencies of other
  relied on modules, use "resolutions" to ensure only one version is installed.
  https://yarnpkg.com/en/docs/selective-version-resolutions
  Duplicate "graphql" modules cannot be used at the same time since different
  versions may have different capabilities and behavior. The data from one
  version used in the function from another could produce confusing and
  spurious results.
  ```

**Comment by joselcvarela** [comment]
Yeah it seems some plugin is accessing or creating another instance of "JSON", but Gatsby only allows a single plugin to create a certain type with that name.

If you want to use our latest Gatsby plugin, then you need Gatsby 4, but you need to follow this steps to upgrade: https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v3-to-v4/
Otherwise you can stick to a previous version 
https://www.npmjs.com/package/@directus/gatsby-source-directus

Since the original issue seems to be solved, I am closing this.

**Comment by AhmedMesawer** [comment]
@joselcvarela now gives me this
```
 ERROR #11321  PLUGIN

"@directus/gatsby-source-directus" threw an error while running the createSchemaCustomization lifecycle:

Source GraphQL API: HTTP error 500 Internal Server Error

  Error: Source GraphQL API: HTTP error 500 Internal Server Error
  ```

**Comment by joselcvarela** [comment]
Can you tell what plugins are you using?
Also, have you set the authorisation on the plugin?
