### ISSUE TITLE
Should schema updates propagate correctly when load balancing multiple instances?

### ISSUE THREAD

**Issue by jake-subvrsive** [directus/directus#10508]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

We've noticed an issue on one of our projects where, when running two directus instances behind a load balancer, schema updates are not propagated correctly to both instances.

For example, after creating a new collection/table, we can proceed to add fields/row with requests that hit one of our server instances, but the other server instance returns a 403 on any requests about this new table.

After restarting both instances, all requests work as expected.  My assumption here is that the instances are caching schema information and so one server isn't loading the updates made by the other?  Hoping someone more familiar with the interworking on the projects can provide a little guidance here.

### To Reproduce

Run two directus instances behind a load balancer that round-robins requests.  Create a new collection and try to make updates to that collection.  Observe only ~half of the requests work as expected, presumably only ones that hit the server instance that created the collection.

### Errors Shown

Requests to update the new collection return 403 errors from one of the servers.

### What version of Directus are you using?

Currently 9.0.1, can test on most recent release if this behavior sounds unexpected.

### What version of Node.js are you using?

14.18.1

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

Windwos

### How are you deploying Directus?

Custom docker image

**Comment by rijkvanzanten** [comment]
Yes, but you need to make sure you use a shared resource for caches, rate limiting, and file storage, like Redis and S3 respectively. Alternatively, you can disable all caches, but this will negatively affect the performance of Directus.

**Comment by jake-subvrsive** [comment]
> Yes, but you need to make sure you use a shared resource for caches, rate limiting, and file storage, like Redis and S3 respectively. Alternatively, you can disable all caches, but this will negatively affect the performance of Directus.

Appreciate the quick reply!

We are currently using a shared Postgres database, rate limiting is disabled, and CACHE_ENABLED is also set to false in the env.  Are there any other configurable caches that would cause the described behavior?

**Comment by rijkvanzanten** [comment]
@jake-subvrsive yeah, there's a `CACHE_SCHEMA` and `CACHE_PERMISSIONS` flag as well (see https://docs.directus.io/configuration/config-options/#cache). I would highly recommend using Redis when using a multi-instance Directus setup though, as it vastly improves performance and reduces cpu usage on the directus instances 👍🏻

**Comment by jake-subvrsive** [comment]
> @jake-subvrsive yeah, there's a `CACHE_SCHEMA` and `CACHE_PERMISSIONS` flag as well (see https://docs.directus.io/configuration/config-options/#cache). I would highly recommend using Redis when using a multi-instance Directus setup though, as it vastly improves performance and reduces cpu usage on the directus instances 👍🏻

Ah, I did not notice those config flags underneath.  Apologies for not being a thorough reader.

And thanks for the redis recommendation, we'll monitor performance and see if that migration makes sense.

**Comment by rijkvanzanten** [comment]
> And thanks for the redis recommendation, we'll monitor performance and see if that migration makes sense.

There shouldn't be any migrations! Redis is an additional service to hook up, not something that will replace the database 👍🏻
