### ISSUE TITLE
Add PATCH /users/me to docs and GraphQL

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#10500]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

We have a /users/me endpoint that can be used to retrieve the current user. However, there's also a (currently undocumented) PATCH /users/me, that allows to easily update the current user. We should make sure this is documented.

While we do that, we should also make sure there's a users_me mutation to align the feature parity between the REST and GraphQL operations.

### To Reproduce

—

### What version of Directus are you using?

9.2.2

### What version of Node.js are you using?

16

### What database are you using?

Postgres 13

### What browser are you using?

Safari

### What operating system are you using?

macOS Big Sur

### How are you deploying Directus?

Locally

**Comment by w0ryn** [comment]
I'm super new to directus, but would love to take this one!

**Comment by rijkvanzanten** [comment]
More than welcome to! 

The docs update should be straightforward enough (in here: https://github.com/directus/directus/blob/main/docs/reference/system/users.md). The GraphQL change is a little more involved.

There's a "injectSystemResolvers" function that injects all the system resolvers based on the users permission. This is where we'd have to add one for "update_users_me":

https://github.com/directus/directus/blob/e92b8c0415731f639c9811e808c5e5ea0a42fa40/api/src/services/graphql.ts#L1576

Word of warning: the GraphQL service is fairly complex, as nearly everything in the GraphQL Schema is generated on the fly based on the actual database schema.
