### ISSUE TITLE
File upload mime setting displays incorrect type, null files cause 500 errors

### ISSUE THREAD

**Issue by stockHuman** [directus/directus#10503]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Files uploaded through chunked formData using [`react-native-blob-util`](https://github.com/RonRadtke/react-native-blob-util) do not render correctly, appearing as binary data in the UI. They are however downloadable as intended. Appending `type` as suggested in another issue leads to a 500 server error.
![blank files](https://user-images.githubusercontent.com/13852458/146058078-41964b49-d3b8-4c32-ba05-190aab560a18.png)

Upon successful upload, Directus reports them as `"type": "application/octet-stream"`

```ts
{
  "data": {
    "id": "1585d02c-57c0-4283-8809-b5dd9750a554",
    "storage": "local",
    "filename_disk": "1585d02c-57c0-4283-8809-b5dd9750a554.jpg",
    "filename_download": "marker-62569f22-72c3-478a-b384-693896966a02.jpg",
    "title": "marker-62569f22-72c3-478a-b384-693896966a02",
    "type": "application/octet-stream",
    "folder": "e4f88a43-1d70-4c33-8967-6ddbf3d6b2f5",
    "uploaded_by": "3a1cd6e1-1e87-48a3-9236-3645c4483a17",
    "uploaded_on": "2021-12-14T18:18:35.000Z",
    "modified_by": null,
    "modified_on": "2021-12-14T18:18:35.000Z",
    "charset": null,
    "filesize": 0,
    "width": null,
    "height": null,
    "duration": null,
    "embed": null,
    "description": null,
    "location": null,
    "tags": null,
    "metadata": null
  }
}
```

<details>
<summary><b>Upload logic</b> (React-Native 0.64.2, iOS 15.1)

</summary>

```ts
import RNBlob from 'react-native-blob-util'
import { DATABASE } from 'react-native-dotenv'


/**
 * Uploads an asset to Directus
 */
export async function uploadFile(
  /** filesystem path to asset */
  uri: string,
  /** name of file, including extension */
  filename: string,
  /** Directus folder save */
  location: 'assets' | 'previews' | 'markers' | null,
  /** Asset mime-type */
  mime?: 'model/gltf-binary' | 'image/png' | 'image/jpeg', // I am aware 'model/gltf-binary' is unsupported.
) {
  let authToken = functionThatGetsToken()
  const path = uri.startsWith('file') ? uri.substring(6) : uri // removes the file:// prefix

  const res = await RNBlob.fetch(
    'POST',
    `${DATABASE}/files`,
    {
      Authorization: `Bearer ${authToken}`,
      Accept: 'application/json',
    },
    [
      { name: 'folder', data: omittedFunction(location) },
      { name: 'title', data: filename.split('.')[0] },
      { name: 'type', data: mime || location === 'assets' ? 'model/gltf-binary' : 'image/png' }, // no effect
      { name: 'file', filename: filename, data: path }, // adding `type` in here results in null jpg bug described in errors
    ],
  )
    .then(res => res.json())
    .catch(err => console.warn('[Directus File Upload]', err))

  return res as OmittedFileUploadResponseType
}

```

</details>

### To Reproduce

I am unsure how easily this may be reproduced, given the number of moving parts needed to isolate the issue and the real hardware required.

However:

1. Create a [react-native app](https://reactnative.dev/blog/2017/03/13/introducing-create-react-native-app)
2. Install [`react-native-blob-util`](https://github.com/RonRadtke/react-native-blob-util) and run it on a real iOS device.
3. Upload an image file via the logic above to a Directus server

If need be, I can help with these steps. I have not tested android, but I don't think that would change the outcome.

---

Unfortunately, Postman returns data from another file on upload, and I'm unsure why.

![Screen Shot 2021-12-14 at 2 01 46 PM](https://user-images.githubusercontent.com/13852458/146062811-44b577fa-2093-4e37-b2d9-e42eb52c6faa.png)

### Errors Shown

The only error so far observable is sent when an extra chunk is appended as suggested in the only vaguely related issue (#6671), implemented on the device as follows:

```ts
// ... same as above
{ name: 'file', filename: filename, data: path, type: mime },
```
Note, sending a chunk before the file, as suggested in the docs has no effect:

```ts
// title, etc. works
{ name: 'type', data: mime }, // no effect
// the file
```

The error, when sending an errant `type` in the file chunk.

```json
{
  "errors": [
    {
      "message": "An unexpected error occurred.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

_However_, in submitting this bug I discovered that setting the type chunk produced a zero-size jpg. Attempting to download the file leads to a bare page with the following text:

```
{"errors":[{"message":"E_UNKNOWN: An unknown error happened with the file null.\n\nError code: ERR_INVALID_ARG_TYPE\nOriginal stack:\nTypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string. Received null\n    at new NodeError (internal/errors.js:322:7)\n    at validateString (internal/validators.js:124:11)\n    at join (path.js:1148:7)\n    at LocalFileSystemStorage._fullPath (/root/elysium-db/node_modules/@directus/drive/dist/LocalFileSystemStorage.js:51:61)\n    at LocalFileSystemStorage.exists (/root/elysium-db/node_modules/@directus/drive/dist/LocalFileSystemStorage.js:104:54)\n    at AssetsService.getAsset (/root/elysium-db/node_modules/directus/dist/services/assets.js:69:71)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /root/elysium-db/node_modules/directus/dist/controllers/assets.js:115:36","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}
```
![null-files](https://user-images.githubusercontent.com/13852458/146058248-0a4375aa-de7f-45e3-827a-cfd5c9c5d64c.png)

Note the file of the left downloads properly, despite being mislabelled, and the file on the right (with no preview, size or other details that should've been rejected if Directus could not parse it) correctly describes itself as a jpg.

### What version of Directus are you using?

9.2.1

### What version of Node.js are you using?

v16.13.1

### What database are you using?

MariaDB 10.5.12

### What browser are you using?

Chrome, Safari, Firefox

### What operating system are you using?

Debian GNU/Linux 11 (bullseye) x86_64 

### How are you deploying Directus?

Sole app running on a DigitalOcean droplet

**Comment by rijkvanzanten** [comment]
@stockHuman Could you share an example of the HTTP request that that library/code actually sends? I'm not familiar with the tools used in your example unfortunately.

The missing mime-type to me indicates a discrepancy in the actual POST body 🤔

**Comment by stockHuman** [comment]
Hi @rijkvanzanten, after further investigation, it seems it was merely a lack of mime type, or rather, Directus could not infer the filetype without content-type being sent, and the particular library used in this example honoured placement so a final `type: mime` _after_ the file blob caused the above / the strange responses with other elements returned instead.

Thanks!

**Comment by rijkvanzanten** [comment]
Gotcha! Thanks for confirming that 👍🏻
