### ISSUE TITLE
Don't trigger webhooks on nested relational updates

### ISSUE THREAD

**Issue by Attacler** [directus/directus#10509]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have 2 collections:
categories and products.
Between those 2 there is a m2m (catagories_products).
Whenever i add a product to a categorie, it will trigger a hook for all products that are already there.
I had a webhook configured on the join table and it basicly tiggered 170 times because there where 170 products in 1 categorie.
It gave a big load on Directus and the target.

### To Reproduce

Create 2 collections:
 - Categories
 - products

Add a M2M to them.
Make some way to see if a hook is triggered (for example console.log(1) inside a update hook);
Now add some products to the categories and you will see it getting triggered on the join table.

### What version of Directus are you using?

9.2.2

### What version of Node.js are you using?

17.1.0

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying Directus?

PM2

**Comment by rijkvanzanten** [comment]
The fact that the hook fires is expected, as the actual nested item is being updated. That being said, the webhook should only be fired once for the whole (nested) relational update tree

**Comment by rijkvanzanten** [comment]
Ref [#11172](https://github.com/directus/directus/issues/11172)

**Comment by rijkvanzanten** [comment]
Linear: [ENG-285](https://linear.app/directus/issue/ENG-285/dont-trigger-webhooks-on-nested-relational-updates)

**Comment by rijkvanzanten** [comment]
I believe this was resolved as part of https://github.com/directus/directus/pull/14981, but happy to reopen if I'm mistaken
