### ISSUE TITLE
Can't filter by nested relation translations 

### ISSUE THREAD

**Issue by alihassan161820** [directus/directus#10516]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I tried to filter model using nested relation but it doesn't work

### To Reproduce

categories has many news which has translations ( o2m ) 
i need to retrieve categories which has news which has translations where code = en-US but it retrieve all categories which has news without checking for languages code
my filter : 

```
{
   "_and":[
      {
         "news":{
            "translations":{
               "languages_code":{
                  "_eq":"en-US"
               }
            }
         }
      }
   ]
}
```

relation : 
![Screenshot from 2021-12-15 18-10-54](https://user-images.githubusercontent.com/22984580/146222704-c9ffac7b-09fb-402b-98bf-4bfc06304487.png)

### Errors Shown

Retrieving unexpected data 

### What version of Directus are you using?

9.2.2

### What version of Node.js are you using?

16.13.0

### What database are you using?

mysql

### What browser are you using?

chrome

### What operating system are you using?

Linux 4.4.0-210-generic

### How are you deploying Directus?

docker

**Comment by azrikahar** [comment]
Assuming you are retrieving via the API, I believe you should use the [deep](https://docs.directus.io/reference/query/#deep) query param here to achieve the nested filter you're looking for. Closing this as it seems to be more of a usage problem rather than an actual bug, but do get back to us if `deep` doesn't work in your case.

**Comment by alihassan161820** [comment]
using deep will return category object even if have no news which has this translations
but using filter should return only categories which has news which has this translations 
@azrikahar

**Comment by rijkvanzanten** [comment]
@alihassan161820 You can combine both! `filter` will filter the top-level items based on a condition, and `deep` allows you to perform any query on the nested data set, combining both allows you to say "Fetch all categories that have a Dutch translation, and only return the Dutch translations":

```
GET /items/categories
  ?filter[translations][language_code][_eq]=nl-NL
  &deep[translations][_filter][language_code][_eq]=nl-NL
```

**Comment by alihassan161820** [comment]
@rijkvanzanten filter by collection translations is work well but the problem is in filter by collection relation translations
ex : 
GET /items/categories
  ?filter[news][translations][language_code][_eq]=nl-NL

this doesn't work

**Comment by rijkvanzanten** [comment]
What doesn't work?

**Comment by alihassan161820** [comment]
@rijkvanzanten  
I got all categories even if category doesn't have news which have translations -> languages_code = nl-NL

in this example i filtered categories by language code which doesn't exist
expected result : zero categories 

![Screenshot from 2021-12-25 15-04-08](https://user-images.githubusercontent.com/22984580/147385512-b5c916fa-7add-4be2-a612-cdd68dcd8cf6.png)

**Comment by rijkvanzanten** [comment]
> i need to return categories have news which have translations nl-NL ONLY

Ah, so you want to exclude the items that do not have nl-NL at all?

**Comment by alihassan161820** [comment]
yes i want to exclude categories that don't have news in nl-NL

**Comment by rijkvanzanten** [comment]
Would you be able to share a database dump with this schema? I believe the above example should do the trick, but something else might be up

**Comment by alihassan161820** [comment]
https://we.tl/t-bZ6VCrPAyU this is my db schema 

This is my request : 

`curl --location -g --request GET 'http://localhost:8055/items/categories?fields[]=id&fields[]=news.translations.languages_code&sort=-id&filter[news][translations][languages_code][_eq]=dummy language '`

**Comment by fblackburn** [comment]
Just a head's up that we're having the same issue since 9.2.

**Comment by eXsiLe95** [comment]
I just now found this issue by following the link from #11445 by @azrikahar and I think I might have additional info on this in my own ticket here: #11655 (which then may be a duplicate).

I'd like to help find this issue! Let me know if you need something (additional information, dumps, or even a contribution).

**Comment by jaycammarano** [comment]
> I just now found this issue by following the link from #11445 by @azrikahar and I think I might have additional info on this in my own ticket here: #11655 (which then may be a duplicate).
> 
> I'd like to help find this issue! Let me know if you need something (additional information, dumps, or even a contribution).

A contribution is always welcome!

**Comment by eXsiLe95** [comment]
Hey @alihassan161820, can you check again with Directus v9.6.0?

**Comment by rijkvanzanten** [comment]
Good one @eXsiLe95! This should be fixed by https://github.com/directus/directus/pull/11768. Let us know if that's not the case, and we'll reopen 👍🏻
