### ISSUE TITLE
graphql: filtering user only works if filtering on relationship instead of directly on the users field

### ISSUE THREAD

**Issue by eikaramba** [directus/directus#10515]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

according to the docs https://docs.directus.io/configuration/filter-rules/#examples
this should be possible (SEARCH specs used here, but i would argue that should be possible with graphql too no?):
```
{
	"owner": {
		"_eq": "$CURRENT_USER"
	}
}
```
however in my tests both $CURRENT_USER and the actual uuid are resulting in graphql error

### To Reproduce

execute graphql endpoint with
```
query {
	posts: ( filter: { user: { _eq: "$CURRENT_USER"} } ) {
             ....
	}
}
```

however it works when i explicitly search for the id
posts: ( filter: { user: { _eq: "$CURRENT_USER"} } ) {
```
query {
	posts: ( filter: { user: { id: {_eq: "$CURRENT_USER"} } } ) {
             ....
	}
}
```

### Errors Shown

`Field \"_eq\" is not defined by type \"directus_users_filter\". Did you mean \"_or\"?"`

### What version of Directus are you using?

9.2.2

### What version of Node.js are you using?

16.6.1

### What database are you using?

SQLITE

### What browser are you using?

FF

### What operating system are you using?

win64

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
GraphQL as a spec doesn't allow for multiple input types on the same argument. For example, in Directus, the following two are equal:

```json
{
  "user":{
    "_eq": "$CURRENT_USER"
  }
}
```

```json
{
  "user":{
    "id": {
      "_eq": "$CURRENT_USER"
    }
  }
}
```

however, in a GraphQL spec, you can only have one of these max. In this particular case, only the latter exists in the GraphQL attributes.

**Comment by eikaramba** [comment]
ok got it. thanks for the response. if you add the documentation flag to this ticket i think it is valuable addition to the docs to quickly mentioning this. :)

**Comment by benhaynes** [comment]
@rijkvanzanten — what is our protocol for these? If they stay closed (even with the `documentation` tag), will it even get prioritized and accomplished? Shall we re-open?

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten — what is our protocol for these? If they stay closed (even with the `documentation` tag), will it even get prioritized and accomplished? Shall we re-open?

We track all the topics that could use some love in the internal documentation board. Topics aren't necessarily 1-1 linked to user issues, but are aggregated based on all user feedback.

I don't want to keep original bug reports open, as that causes quite a bit of noise in the issue tracker (or we'd have to give every open issue a new title and update the description to make sure it's clear we left it for docs). If you wanna have issues for those docs topics in this repo, we should make new issues instead. (Though I'd rather just keep aggregating topics in a centralized board, and then divide and conquer from there)

**Comment by rijkvanzanten** [comment]
> i have an addition to this ticket here: I disabled "app access" to my users role, but now when i do the query above i get `Field \"id\" is not defined by type \"directus_users_filter` if i enable "app access" again everything works accordingly.
> 
> i can access the rest of my endpoints but filtering the user relation does not work anymore. before i create another (invalid) ticket, i wanted to ask whether this is a bug or not?
> 
> background. i don't want users necessarly to be able to accces the /admin ui, even if they cannot do anything bad there.

App access sets some default permissions that the app requires to run. It's most likely not a bug, but simply some missing permissions for your current role 👍🏻

**Comment by eikaramba** [comment]
ok got it. i needed to manually set id=$CURRENT_USER to all directus_users permissions.
rest seems to work fine even without any access
![grafik](https://user-images.githubusercontent.com/1320525/146780438-5d65c950-a7f5-46d8-a2ec-e54570de36f0.png)

**Comment by rijkvanzanten** [comment]
> the only thing was i needed to first give ALL access to every permission, then set custom. very strange

That's certainly odd 🤔 That would indeed force the permissions to be recreated, but that shouldn't have been required. Is that a situation you can accurately reproduce? If so, worth creating a new issue for!

**Comment by eikaramba** [comment]
i think it is fine. after testing i suspect directus is not actually changing the tables content when changing the app access boolean right? more an internal method which handles it? because everytime i flip the app access switch it remembers the "old" values i set manually. so i suspect i had a wrong setting there. anyhow... i wasn't able to reproduce it.

**Comment by rijkvanzanten** [comment]
Ahhhhh I think I know what's causing that! The permissions are cached between requests to improve performance, and are flushed whenever permissions are changed. _However_, when you flip the "app access" toggle, that (like you correctly stated) flips a switch on directus_roles, not permissions. Therefore, that permissions cache isn't flushed correctly.
