### ISSUE TITLE
Custom Permission Filter not working properly

### ISSUE THREAD

**Issue by kuuroo3** [directus/directus#10538]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Custom permission filter do not work properly. 

Given there are 3 collections: `collection B -M2M- collection A -O2M- collection C`.
Also there are 2 different roles, one higher privileged (e.g. admin) and a restricted one.

The **goal** is to only grant **read access** to those users of the restricted role, who are either the **creator of the item A or** have the **same email address as stated in item B**.

When setting permission filters for collection A the user can only see one item: the one he created himself and has the same email as in item B.
![image](https://user-images.githubusercontent.com/43739995/146322575-41d9d6f5-50f2-4e29-aca8-5a9d25293656.png)

When also setting permission filters for collection C the user gets an error when opening the page of collection C.
When not setting permission filters the user can see all items of collection C, but cannot read the field of collection A. (But the aim here is to also just show the items, where the user was creator of A or has the same address as in B.)
![image](https://user-images.githubusercontent.com/43739995/146322982-37062f95-100c-470d-95fe-39ec4c2b22fb.png)

### To Reproduce

1. Create 3 Collections A, B, C
![image](https://user-images.githubusercontent.com/43739995/146321781-7bcd38a9-7aab-4fe9-af0b-97a90ef29f5c.png)
![image](https://user-images.githubusercontent.com/43739995/146321823-8016d284-f320-4e9b-a8c8-091b9499fbd5.png)
![image](https://user-images.githubusercontent.com/43739995/146321877-2a3b78d8-1135-4b57-8810-03ad26ece77a.png)

2. Create another role (e.g. "non-admin") without admin permissions
3. Create a user for this role or just assign the role to an existing one
4. Grant full access to A,B, (A B) and C
5. Restrict reading access for A + C
![image](https://user-images.githubusercontent.com/43739995/146322575-41d9d6f5-50f2-4e29-aca8-5a9d25293656.png)
![image](https://user-images.githubusercontent.com/43739995/146322982-37062f95-100c-470d-95fe-39ec4c2b22fb.png)

6. Create 2 items in collection B
  6.1 same mail as new user
  6.2 different mail than new user
7. Create 4 items in collection A
  7.1 Created with new user, link item B with same email as new user
  7.2 Created with new user, link item B with different email as new user
  7.3 Created with admin, link item B with same email as new user
  7.4 Created with admin, link item B with different email as new user
8. Create 4 items in collection C
  8.1 One for each item in collection A

Now test which items the user can see.

**EXPECTED**:
New user can see 7.1, 7.2 and 7.3 because he was either creator or has the same email.
New user can see 3 items of collection C (the ones which are linked to the items new user can see in collection A).

### Errors Shown

🚨 error select "c"."a", "c"."status", "c"."id" from "c" left join "a" as "wxfgy" on "c"."a" = "wxfgy"."id" left join "directus_users" as "ccoqq" on "wxfgy"."user_created" = "ccoqq"."id" left join "a" as "nfksk" on "c"."a" = "nfksk"."id" left join "a_b" as "uzbhm" on "nfksk"."id" = "uzbhm"."a_id" where (not "c"."status" = $1 and ("ccoqq"."email" = $2 and "b"."mail" = $3)) order by "c"."id" asc limit $4 - missing FROM-clause entry for table "b"

error: select "c"."a", "c"."status", "c"."id" from "c" left join "a" as "wxfgy" on "c"."a" = "wxfgy"."id" left join "directus_users" as "ccoqq" on "wxfgy"."user_created" = "ccoqq"."id" left join "a" as "nfksk" on "c"."a" = "nfksk"."id" left join "a_b" as "uzbhm" on "nfksk"."id" = "uzbhm"."a_id" where (not "c"."status" = $1 and ("ccoqq"."email" = $2 and "b"."mail" = $3)) order by "c"."id" asc limit $4 - missing FROM-clause entry for table "b"

    at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)

### What version of Directus are you using?

9.2.2

### What version of Node.js are you using?

inside Docker: 16.13.1

### What database are you using?

Postgres 12

### What browser are you using?

Vivaldi

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
Could you share a [schema snapshot](https://docs.directus.io/reference/cli/#migrate-schema-to-a-different-environment) and a copy of the permissions you've configured to reproduce this? 

It could be the same as https://github.com/directus/directus/issues/5747, but a little tricky to confirm without testing it out ourselves.

**Comment by kuuroo3** [comment]
Oh I didn't see that issue. Yea for the second part it looks quite similar, maybe it's the same.
But that doesn't cover the first part, I'm afraid.

Unfortunately I get an error trying to provide the snapshot... 
`PS C:\Users\<me>\Projekte\cms> npx directus schema snapshot ./snapshot.yaml
09:12:17 ÔÜá´©Å  Couldn't load extensions
09:12:17 ÔÜá´©Å  Current folder does not contain a package.json file
09:12:17 ­ƒÜ¿ "DB_CLIENT" Environment Variable is missing.
Error: EPERM: operation not permitted, unlink 'C:\Users\<me>\AppData\Roaming\npm-cache\_npx\18776\node_modules\directus\node_modules\argon2\lib\binding\napi-v3\argon2.node'
    at Object.unlinkSync (fs.js:1251:3)
    at fixWinEPERMSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:219:13)
    at rimrafSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:319:28)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:350:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:349:26)
    at rmdirSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:342:7)
    at fixWinEPERMSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:217:5)
    at rimrafSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:319:28)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:350:5 {
  errno: -4048,
  syscall: 'unlink',
  code: 'EPERM',
  path: 'C:\\Users\\<me>\\AppData\\Roaming\\npm-cache\\_npx\\18776\\node_modules\\directus\\node_modules\\argon2\\lib\\binding\\napi-v3\\argon2.node'
}
`

[permissions.zip](https://github.com/directus/directus/files/7733659/permissions.zip)

**Comment by kuuroo3** [comment]
nevermind. connected into the container and got it...
[snapshot.zip](https://github.com/directus/directus/files/7733787/snapshot.zip)

**Comment by licitdev** [comment]
@kuuroo3 When using the `any` or `and` filter, the conditions has to be positioned as a child shown in below screenshot. Please kindly confirm if the issue persists after you have updated the filter. 

![Screenshot 2021-12-20 at 4 10 43 PM](https://user-images.githubusercontent.com/26413686/146734104-5322e544-c442-4ec2-9986-f598c241af19.png)
 
The above filter in the image requires a matching ID and also the float to be in one of the ranges.

**Comment by kuuroo3** [comment]
Oh wow, I didn't even try that... thanks :D 

It works for the collection A, but the linked collection C still fires that error.

**Comment by kuuroo3** [comment]
I tried to simplify things and use the directus users instead of my Collection B (Persons), but that didn't change anything.

read permissions for jobs (collection A):
![image](https://user-images.githubusercontent.com/43739995/147077935-7d387131-ecde-4cd6-b4ee-ad7a986623d4.png)
page as non-admin:
![image](https://user-images.githubusercontent.com/43739995/147078007-31cecb5c-f0df-4983-bf7e-f93a310da351.png)

fk is my non-admin. So these 2 items were both created by the non-admin with an admin-email and with an non-admin-email.
the user should also be able to see "admin for fk"...

page as admin:
![image](https://user-images.githubusercontent.com/43739995/147078843-1ab975fd-8da5-4c13-9855-9e0b0cfff169.png)

For the linked collection C it's still the same error.

**Comment by rijkvanzanten** [comment]
I believe this was fixed by https://github.com/directus/directus/pull/11159

**Comment by kuuroo3** [comment]
Yes, thank you, it works now!
