### ISSUE TITLE
Image optimization not working

### ISSUE THREAD

**Issue by dstoyanoff** [directus/directus#10539]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Can't get the image optimizations working (format, quality).

I have the following image - https://cms-uat.betian.co/assets/5830c7f7-ce1b-465e-903b-c94144f9c2f5. It's a 146KB JPEG.

When I try to request it in a different format/quality, I still get exactly the same image.

I have tried 2 options:
https://cms-uat.betian.co/assets/5830c7f7-ce1b-465e-903b-c94144f9c2f5?format=webp&quality=25

Created a preset within Directus: 
https://cms-uat.betian.co/assets/5830c7f7-ce1b-465e-903b-c94144f9c2f5?key=optimized
![image](https://user-images.githubusercontent.com/5079334/146326114-9d7cdfcd-6fbb-412b-9261-2db1448b18cf.png)

### To Reproduce

-

### What version of Directus are you using?

9.2.2

### What version of Node.js are you using?

16

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Hmm it seems to work on my end:

https://user-images.githubusercontent.com/42867097/146328753-692bab10-a073-49d3-934a-86901576ff6a.mp4

Could it be some form of cache (though it should probably say fetched from disk cache in devtools)? Perhaps you can try enabling the "Disable cache" on top of the Network tab?

Or one wilder guess is could it be query strings aren't being passed for some reason, like a reverse proxy?

**Comment by dstoyanoff** [comment]
Oh, my bad. I had the CDN configured to ignore the query string. Sorry for wasting your time.
