### ISSUE TITLE
Upload Files in Item shows 2 added Files when uploading 1

### ISSUE THREAD

**Issue by kuuroo3** [directus/directus#10542]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

UI shows 2 added files when uploading just one file.

![image](https://user-images.githubusercontent.com/43739995/146351103-43c17b69-9096-4446-9e22-0eed9db2b2f9.png)

When adding multiple files, this happens for every file.

### To Reproduce

![image](https://user-images.githubusercontent.com/43739995/146350981-8adcf16a-aa3d-4485-b2d8-d8c0a4deb1ba.png)

I clicked on "Upload File" and chose 1 File to upload.

![image](https://user-images.githubusercontent.com/43739995/146351103-43c17b69-9096-4446-9e22-0eed9db2b2f9.png)

After saving it's just 1 File again.
![image](https://user-images.githubusercontent.com/43739995/146351196-eb158084-33e2-4116-89b5-6881f4248b27.png)

### Errors Shown

none

### What version of Directus are you using?

9.2.2

### What version of Node.js are you using?

inside Docker: 16.13.1

### What database are you using?

Postgres 12

### What browser are you using?

Vivaldi

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
This may be related/regressed from the PR #10368 as well. Seems like Files interface worked on v9.2.1.

**Comment by kuuroo3** [comment]
After taking another look at my raw values it looks just like your demo in #10550 
#10565 also happens at my end - is that fixed with your PR as well?

**Comment by azrikahar** [comment]
Thanks for following up! Unfortunately I think that PR may not be the correct approach as the issue should stem from M2M relation (it's what Files interface uses under the hood), so we may need to look for a fix from that angle instead of being files-interface-specific.

**Comment by stx-chris** [comment]
Is there a workaround available for this behaviour? Our customers keep deleting files since they think they are duplicates. Thanks

**Comment by rijkvanzanten** [comment]
> Is there a workaround available for this behaviour? Our customers keep deleting files since they think they are duplicates. Thanks

I'm not aware of a configuration workaround. #12082 aims to fix this though 👍🏻

**Comment by elplaza** [comment]
Same issue for me with docker:9.8.0:
![screenshot-localhost_8056-2022 04 12-10_02_36](https://user-images.githubusercontent.com/10348142/162911744-4a98984e-efc3-47eb-9da1-396e4213db16.png)

**Comment by kuuroo3** [comment]
This still doesn't seem to work right.
I checked out v9.9.0 and had a look at it. When I now add files nothing gets shown at all. Only in the raw section I can see that there were indeed files added. (Only when uploading files, chosing already existing files seems to be working)

![image](https://user-images.githubusercontent.com/43739995/164160879-6325a037-1779-4291-b713-fbdcdf965976.png)
`{
	"create": [],
	"update": [
		{
			"applications_id": "+",
			"directus_files_id": {
				"id": "ea86482e-d0c1-489b-a40c-b859fdfd4751"
			}
		},
		{
			"applications_id": "+",
			"directus_files_id": {
				"id": "b02809c5-2c1e-4a14-aa5e-8c15ee8bd17c"
			}
		}
	],
	"delete": []
}`

**Comment by azrikahar** [comment]
@kuuroo3 That is indeed an actual bug on `v9.9.0`, but rest assured it was resolved recently in #12821 (not released yet as of now) 👍

## Before that PR

https://user-images.githubusercontent.com/42867097/164179236-9d260c4e-c014-44d1-b9de-afdd6c447d43.mp4

## After that PR

https://user-images.githubusercontent.com/42867097/164179204-ddb42bd9-8929-4932-87d4-f6ea1e257a88.mp4

**Comment by kuuroo3** [comment]
@azrikahar nice! Thank you :)
