### ISSUE TITLE
Updating translations

### ISSUE THREAD

**Issue by kuuroo3** [directus/directus#10547]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Adding translations via API doesn't make any problems. But if you want to update an existing one...

When adding a new one it will be added to the array of translations for this item. It seems like this takes around 5min to complete. (Why??)

So if you are trying to update it before and you just get all existing translations, check for the most filled one and translate all the others... others do not exist and will be created newly. This way you end up having more translations than languages. Since all the translations are the same (just doubled,..) I can't even tell which one you get provided when opening the item, because the translations dropdown will only give you the selection for the languages.

After waiting for the array to contain all entries I cannot update the translations because the ID is not unique. But I thought when providing the ID of the translations item it will just update the existing one. How else should one update the translation?

### To Reproduce

1) Create any collection with translations
2) Make a POST call with the translated item to <your-url>/items/<your-collection>_translations
  2.1) I also tried with:
  fields=*
  limit=-1
  filter=encodeURI(`{"<your-collection>_id":{"_eq":"<existing_translation_id>"}}`)

Check with GET if translations are added to the translations array.
If not, repeat 2) and see your translations doubled.
If present in the array try 2) again and see the ID-not-unique-error.

### Errors Shown

Log:
request completed POST 400 /items/jobs_translations?fields=*&limit=-1&filter=%7B%22jobs_id%22:%7B%22_eq%22:%22a83fe0d8-5d3f-4342-a95b-6e153279be58%22%7D%7D

Browser shows:
![image](https://user-images.githubusercontent.com/43739995/146376566-2710af5c-f481-4823-9a79-625bd312f53e.png)

### What version of Directus are you using?

9.2.2

### What version of Node.js are you using?

inside Docker: 16.13.1

### What database are you using?

Postgres 12

### What browser are you using?

Vivaldi

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
I'm not really sure what the issue is here.. Is it the fact that you're getting an error when creating a new item with an ID that already exists? 

> But I thought when providing the ID of the translations item it will just update the existing one. How else should one update the translation?

The translations collection is no different from any other collection, so the same endpoints apply, see https://docs.directus.io/reference/items/#update-an-item 👍🏻

**Comment by kuuroo3** [comment]
Okay, strike updating from the list, I was being stupid with updating because I forgot to set the right permissions for that. BUT the rest is still a problem...


I have 4 Locales: german, english, french and brazil.


> So if you are trying to update it before and you just get all existing translations, check for the most filled one and translate all the others... others do not exist and will be created newly. This way you end up having more translations than languages. Since all the translations are the same (just doubled,..) I can't even tell which one you get provided when opening the item, because the translations dropdown will only give you the selection for the languages.

I create a new item in my collection with just one given translation.
![image](https://user-images.githubusercontent.com/43739995/146509392-d6cf81c3-2ebf-4b1f-9b08-027342c425ad.png)
![image](https://user-images.githubusercontent.com/43739995/146509470-4fba0c5a-b3d1-4464-96e7-74d1bc1edb77.png)

Then I let my service translate the missing locales. Since there is just one existing translation there will be post calls to create the new ones.
![image](https://user-images.githubusercontent.com/43739995/146509625-bd9857ab-d9ee-4a76-ad88-af9549e213ed.png)
Now I have 4 translations in the app, but getting the translations again will not provide them too. 
![image](https://user-images.githubusercontent.com/43739995/146509685-5e2de713-c259-48d1-932a-09bc58ee4bf8.png)

**(Not waiting 5 minutes)**
Imagine I changed a field because I missspelled something or whatever and fire my service again. Like we saw in the screenshot from RESTED I do not get the already existing translations, so instead of doing a patch call there will be a post call again. Resulting in more new translations...
![image](https://user-images.githubusercontent.com/43739995/146509867-60c411c4-de7f-4bb2-944c-b2d74dcaacaf.png)

----------------------

**(Waiting 5 minutes)**
![image](https://user-images.githubusercontent.com/43739995/146510164-8a126960-2b20-451b-be11-c3e021a42064.png)
If I fire my service again _now_ there will be patch calls instead and no more new translations.
![image](https://user-images.githubusercontent.com/43739995/146510305-8dd44b9e-0d49-4c19-81c0-d8bc7ba3fefe.png)

**Comment by rijkvanzanten** [comment]
@kuuroo3 I'm having some trouble understanding exactly what your services are doing based on the screenshots and points above. Would you be able to provide a small flow-chart to elaborate?

Also, the timing you mentioned make me think there could be some caching going on somewhere that might be causing issues. Are you using a particular user/role? How is your service accessing the data in directus?

**Comment by kuuroo3** [comment]
I used my service with public permissions and later assigned a role but that didn't make any difference.
I tried to create you a flowchart, hope it helps and is understandable :D

[flowchart.drawio.pdf](https://github.com/directus/directus/files/7800871/flowchart.drawio.pdf)

caching might be the problem but I wouldn't know where this could come from since I haven't set anything for that

**Comment by kuuroo3** [comment]
Ah, new year's break didn't do me any favors... Since I was using the default configuration for docker I couldn't remember setting any cache values, however cache was set to enabled. set that to false and now it works like a charm.
