### ISSUE TITLE
Responses with not content are wrongly set to status Code 200

### ISSUE THREAD

**Issue by eikaramba** [directus/directus#10558]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

i stumpled upon this while using the okhttp library on android. it tries to parse the response body as json, which is not set. this is due to directus setting the http code to 200 even if no content is provided

### To Reproduce

i tried this with DELETE operation on REST for an item endpoint. it returns no content and thus should have status code 204 instead of 200.

### What version of Directus are you using?

9.2.2

### What version of Node.js are you using?

16.6.1

### What database are you using?

SQLITE

### What browser are you using?

FF

### What operating system are you using?

win64

### How are you deploying Directus?

locally

**Comment by eikaramba** [comment]
i think this should to it:
change
https://github.com/directus/directus/blob/main/api/src/middleware/respond.ts#L83
```js
if (Buffer.isBuffer(res.locals.payload)) {
	return res.end(res.locals.payload);
} else {
	return res.json(res.locals.payload);
}
```
to
```js
if (Buffer.isBuffer(res.locals.payload)) {
	return res.end(res.locals.payload);
}else if(res.locals.payload){
	return res.json(res.locals.payload);
}else {
	return res.status(204).end();
}
```

unfortunately it does not help me with my problem as i still get the error. once i figure out what the problem is i will do a PR

**Comment by eikaramba** [comment]
ok everything is clear now. the whole 204 issue was not really the problem in my case (of course lol), but it is nevertheless correct to fix this. made a PR https://github.com/directus/directus/pull/10569

**Comment by rijkvanzanten** [comment]
> ok everything is clear now. the whole 204 issue was not really the problem in my case (of course lol)

Haha nice! What _was_ the issue? 😁 

I'll leave the issue open until the PR is merged, just to make sure we don't miss anything 👍🏻

**Comment by eikaramba** [comment]
actually some is still not clear for me, as i got an "Unexpected end of JSON input" on a simple console.log(myobject). so let's better just ignore that now and speak never of it again :)

the real issue was that i used a method which would itself use a method which would then do JSON.parse on the result. which was empty. so it failed. this is all on a mobile app with nativescript btw.

currently using
- sveltekit for frontend
- sveltekit for frontend SSR (which itselfs currently proxies ALL authentication requests as directus is only setting the refresh_token as a token. you might recall the discussion around that https://github.com/directus/directus/discussions/10103)
- directus for the backend
- nativescript for the mobile apps
