### ISSUE TITLE
Loading overlay on smaller resolution

### ISSUE THREAD

**Issue by WellingGuzman** [directus/directus#1056]
@benhaynes on smaller screen the page loading blocker get just a part of the screen.

![screen shot 2015-10-09 at 8 06 32 pm](https://cloud.githubusercontent.com/assets/1531291/10411746/158e9e88-6f3e-11e5-8b07-91f12d52a957.jpg)

**Comment by benhaynes** [comment]
Thanks for finding this @WellingGuzman ! I'll fix this asap...

**Comment by benhaynes** [comment]
Not quite asap ;)
