### ISSUE TITLE
Merge all date/date time/time/year UIs

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1057]
We'll consolidate all these UIs into one, for cleaner and more manageable code.

**Comment by benhaynes** [comment]
@WellingGuzman Didn't you already do this during our sprints a few weeks ago?

**Comment by WellingGuzman** [comment]
@benhaynes end up merging datetime and date, leaving time as a separate UI. (didn't delete date UI file though)

**Comment by benhaynes** [comment]
Why leave the time separate from datetime? Or just for now?

**Comment by benhaynes** [comment]
@WellingGuzman Removed `Testing` since we need to figure out the time UI integration...

**Comment by WellingGuzman** [comment]
@benhaynes I made datetime extends from date UI, and share the same template.

**Comment by benhaynes** [comment]
Other than UI option defaults not showing up when created, this is all set!
