### ISSUE TITLE
Organizing Migrations

### ISSUE THREAD

**Issue by WellingGuzman** [directus/directus#1058]
We have been adding functionality, fixing bugs and schema changes that are not backward compatible, so updating to new version has been not as smooth as I thought, so I'm opening a ticket as a reminder or a better organization of the Migrations.

So This is how I look at it.
```
Migrations
|---latest
|---upgrades
|------upgrade-6-0-4
|------upgrade-6-1-0
```

`latest` would be the current migrations "configuration".
Inside `upgrades` would be a directory with a version upgrade containing migration pieces for each version bump, like changing column name, adding column, dropping tables, etc.

So it would be easier to check which are the current version, and execute proper upgrades.

@benhaynes what do you think?

**Comment by benhaynes** [comment]
@WellingGuzman 
Yeah, this sounds great. I've had 1 or 2 people come to me with issues doing big upgrades because of schema changes... so this will definitely help!
