### ISSUE TITLE
'SyntaxError: No identifiers allowed directly after numeric literal' in Safari

### ISSUE THREAD

**Issue by maggie0002** [directus/directus#10621]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I am running Directus 9.3 and accessing it using Safari (15.2). It has been working fine, but now for a second time when I access the admin panel I just see nothing at all except white. In the console there is the following message and nothing else:

`SyntaxError: No identifiers allowed directly after numeric literal`

In the tab at the top of the Safari page it is stuck on `Loading...`.

There are no errors reported in the console of the running Directus instance other than a received and successful request:

`22:36:00 ✨ request completed GET 200 /admin 4ms`

I have tried clearing cookies, disabling all ad blockers, and still no joy. I have also tried in a Private Window on Safari and getting the same error. The API responses still work as expected. And when accessing the same URL from Firefox, it is working fine.

Directus is running on a VPS and accessed over the internet, using https. It is behind an NGINX instance acting as a reverse proxy:

  ```
      location / {
            resolver 127.0.0.11 valid=30s;
            set $directus http://directus:8055;
            proxy_pass $directus;
            proxy_http_version 1.1;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_pass_request_headers on;
        }
```

### To Reproduce

I am not sure what causes the issue so haven't been able to reproduce it. It is the second time I has occurred over the course of about 8 hours of work over 2 days. 

Wish I could provide more details but there isn't anything else in the console. 

### Errors Shown

In the tab at the top of the Safari page it is stuck on `Loading...`.

<img width="1385" alt="Screenshot 2021-12-20 at 22 38 05" src="https://user-images.githubusercontent.com/64841595/146842066-6ca8219e-7d88-4bdc-aecc-636f7d750905.png">

### What version of Directus are you using?

9.3

### What version of Node.js are you using?

v16.13.1

### What database are you using?

Postgres

### What browser are you using?

Safari

### What operating system are you using?

Mac OS 

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
@maggie0002 Could you try it with all extensions disabled and in an incognito window?

That error indicates that there's a syntax error in some JavaScript that's being ran. The JS bundle of the app doesn't change when you refresh the page; and if it was a problem in the Directus bundle, I would've expected it to show up every time you load the page, rather than sporadically.

**Comment by maggie0002** [comment]
> I have also tried in a Private Window on Safari

'Private Window' is Safari's equivalent of 'Incognito'.

**Comment by rijkvanzanten** [comment]
Do you have any custom Directus (app) extensions? 🤔

**Comment by rijkvanzanten** [comment]
The strange thing to me is that Safari doesn't mention any stack trace. If there's bugs in the directus code, you'd normally find a "vendor.107cvgx.js" or something on the right hand side 🤔 

![CleanShot 2021-12-20 at 18 52 47@2x](https://user-images.githubusercontent.com/9141017/146847860-55c94a37-b9e0-4dd9-892e-1ff6431c3e24.png)

**Comment by maggie0002** [comment]
> Do you have any custom Directus (app) extensions? 🤔

Nope, no custom extensions.

Here it is again, just reoccurred after closing all the windows with Command+Q, reopening and then going to the url again. Here is the Private Browser screenshot:

<img width="1379" alt="Screenshot 2021-12-21 at 00 07 19" src="https://user-images.githubusercontent.com/64841595/146848969-f04494db-7837-49c9-bea2-5b9d5126c806.png">

I definitely haven't ruled out this being something Safari related, but as I haven't seen this anywhere else presumably a Safari bug + something about the Directus environment.

**Comment by rijkvanzanten** [comment]
Just out of curiosity, what's this and what does it do?

<img width="86" alt="CleanShot 2021-12-20 at 19 11 00@2x" src="https://user-images.githubusercontent.com/9141017/146849243-40e967c3-d2cc-47fd-ae03-5adf25e2ac2e.png">

For what it's worth, I use Safari as my daily driver (15.2 on macOS Monterey 12.1 currently), and haven't seen this before 🤔

**Comment by maggie0002** [comment]
> Just out of curiosity, what's this and what does it do?
> 
> <img alt="CleanShot 2021-12-20 at 19 11 00@2x" width="86" src="https://user-images.githubusercontent.com/9141017/146849243-40e967c3-d2cc-47fd-ae03-5adf25e2ac2e.png">
> 
> For what it's worth, I use Safari as my daily driver (15.2 on macOS Monterey 12.1 currently), and haven't seen this before 🤔

It's AdGuard, and the logo indicates it's paused for this website (i.e. turned off for this website). 

There is some source code returned. Not seeing it as super helpful, but I'm clutching at straws here to provide something useful. 

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <base href="/admin/"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=1, viewport-fit=cover"/>
    <meta name="format-detection" content="telephone=no,date=no,address=no,email=no,url=no"/>
    <meta name="HandheldFriendly" content="true"/>
    <meta name="MobileOptimized" content="width"/>
    <meta name="msapplication-TileColor" content="#263238"/>
    <meta name="theme-color" content="#263238"/>
    <meta name="mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="default"/>
    <link rel="manifest" href="manifest.webmanifest"/>
    <link rel="mask-icon" href="img/icons/safari-pinned-tab.svg" color="#263238"/>
    <link rel="icon" type="image/png" sizes="512x512" href="img/icons/android-chrome-512x512.png"/>
    <link rel="icon" type="image/png" sizes="192x192" href="img/icons/android-chrome-192x192.png"/>
    <link rel="apple-touch-icon" href="img/icons/apple-touch-icon.png"/>
    <link rel="apple-touch-icon" sizes="152x152" href="img/icons/apple-touch-icon-152x152.png"/>
    <link rel="apple-touch-startup-image" href="img/splashscreens/apple-splash-2048-2732.jpg" media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"/>
    <link rel="apple-touch-startup-image" href="img/splashscreens/apple-splash-2732-2048.jpg" media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"/>
    <link rel="apple-touch-startup-image" href="img/splashscreens/apple-splash-1668-2388.jpg" media="(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"/>
    <link rel="apple-touch-startup-image" href="img/splashscreens/apple-splash-2388-1668.jpg" media="(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"/>
    <link rel="apple-touch-startup-image" href="img/splashscreens/apple-splash-1536-2048.jpg" media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"/>
    <link rel="apple-touch-startup-image" href="img/splashscreens/apple-splash-2048-1536.jpg" media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"/>
    <link rel="apple-touch-startup-image" href="img/splashscreens/apple-splash-1668-2224.jpg" media="(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"/>
    <link rel="apple-touch-startup-image" href="img/splashscreens/apple-splash-2224-1668.jpg" media="(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"/>
    <link rel="apple-touch-startup-image" href="img/splashscreens/apple-splash-1620-2160.jpg" media="(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"/>
    <link rel="apple-touch-startup-image" href="img/splashscreens/apple-splash-2160-1620.jpg" media="(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"/>
    <link rel="apple-touch-startup-image" href="img/splashscreens/apple-splash-1242-2688.jpg" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"/>
    <link rel="apple-touch-startup-image" href="img/splashscreens/apple-splash-2688-1242.jpg" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"/>
    <link rel="apple-touch-startup-image" href="img/splashscreens/apple-splash-1125-2436.jpg" media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"/>
    <link rel="apple-touch-startup-image" href="img/splashscreens/apple-splash-2436-1125.jpg" media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"/>
    <link rel="apple-touch-startup-image" href="img/splashscreens/apple-splash-828-1792.jpg" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"/>
    <link rel="apple-touch-startup-image" href="img/splashscreens/apple-splash-1792-828.jpg" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"/>
    <link rel="apple-touch-startup-image" href="img/splashscreens/apple-splash-1242-2208.jpg" media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"/>
    <link rel="apple-touch-startup-image" href="img/splashscreens/apple-splash-2208-1242.jpg" media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"/>
    <link rel="apple-touch-startup-image" href="img/splashscreens/apple-splash-750-1334.jpg" media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"/>
    <link rel="apple-touch-startup-image" href="img/splashscreens/apple-splash-1334-750.jpg" media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"/>
    <link rel="apple-touch-startup-image" href="img/splashscreens/apple-splash-640-1136.jpg" media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"/>
    <link rel="apple-touch-startup-image" href="img/splashscreens/apple-splash-1136-640.jpg" media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"/>
    <title>Loading&hellip;</title>
    <style id="custom-css"></style>
    <script type="module" crossorigin src="index.10616d79.js"></script>
    <link rel="modulepreload" href="assets/vendor.764dd834.js">
    <link rel="modulepreload" href="assets/use-sync.03a52ddb.js">
    <link rel="stylesheet" href="assets/vendor.fe7856f0.css">
    <link rel="stylesheet" href="assets/index.a35643ef.css">
</head>
<body class="light">
    <noscript>
        <strong>We're sorry but Directus doesn't work without JavaScript enabled. Please enable it to continue.</strong>
    </noscript>
    <div id="app"></div>
    <div id="dialog-outlet"></div>
    <div id="menu-outlet"></div>
    <script defer src="https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194" integrity="sha512-Gi7xpJR8tSkrpF7aordPZQlW2DLtzUlZcumS8dMQjwDHEnw9I7ZLyiOj/6tZStRBGtGgN6ceN6cMH8z7etPGlw==" data-cf-beacon='{"rayId":"6c0ce2b76aabf427","version":"2021.12.0","r":1,"token":"d1ed37ed1f8544788b95689cab6d75d6","si":100}' crossorigin="anonymous"></script>
</body>
</html>
```

**Comment by rijkvanzanten** [comment]
Does cloudflare have any asset transformation magic? Something must be altering the JavaScript that's ran, but no clue what that something could be at this point..

**Comment by maggie0002** [comment]
> Does cloudflare have any asset transformation magic? Something must be altering the JavaScript that's ran, but no clue what that something could be at this point..

Not that I am aware of, other than some compression of static JS. Strange that it is an intermittent issue, and only Safari (Firefox shows no problem on the same Cloudflare proxy). My money is on something triggering a bug in Safari but no worldly idea how to debug it. I will try and investigate further, and will also keep an eye out for the next Safari release to test on.

**Comment by rijkvanzanten** [comment]
@maggie0002 See https://github.com/directus/directus/issues/10826#issuecomment-1004372023. Seems like disabling _Auto Minify_ and purging the cloudflare caches should help in this scenario 👍🏻

**Comment by Fell-x27** [comment]
> @maggie0002 See [#10826 (comment)](https://github.com/directus/directus/issues/10826#issuecomment-1004372023). Seems like disabling _Auto Minify_ and purging the cloudflare caches should help in this scenario 👍🏻

But do you know what causes it? Safari doesn't understand the JS native BigInt format. If there is a number like "123n" encountered, Safari treats it as a variable with an incorrect name.

**Comment by ricricucit** [comment]
Also getting this, which kills sessions and logs out users, with Auth0 (with or without standard login enabled).

**✅ removing Auto Minify of JS solved it.** 

Thanks @rijkvanzanten for the hint and @Fell-x27 for the insights! 🤗
