### ISSUE TITLE
WYSIWYG header buttons are added in order checkboxes were selected

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#10639]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When selecting the header buttons in the wysiwyg options, the buttons are added in the order in which you clicked the checkboxes, rather than the order of the dropdown list. This can cause some very funky toolbars.

### To Reproduce

In the wysiwyg interface options, (re-)select the toolbar options in a random order.

### Errors Shown

n/a

### What version of Directus are you using?

894293a61e34c2305b71cd4a77b47ee604f9078f

### What version of Node.js are you using?

v16.13.1

### What database are you using?

any

### What browser are you using?

any

### What operating system are you using?

any

### How are you deploying Directus?

locally

**Comment by himanshu007-creator** [comment]
Hi!
I am new here, can you guide me on how to replicate this behavior?
I would like to work on this issue.

**Comment by joselcvarela** [comment]
Hello @himanshu007-creator
To contribute to this repository you should follow this guide https://docs.directus.io/contributing/running-locally/
After your changes you need to commit them, push and then open a new PR on this repo.
Hope you find this useful, but let me know if you have any questions.
