### ISSUE TITLE
Filter interface doesn't allow the _contains operator for JSON fields anymore

### ISSUE THREAD

**Issue by AstroViking** [directus/directus#10635]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Previously (on RC83) we relied heavily on being able to filter our collections by json fields that contain specific text/json in the tabular view.

After the update to 9.3 this is sadly not possible anymore.  However, filtering through the API directly (with something like `https://directus.instance/items/collection?filter=%7B"json_field":%7B"_contains":"test"%7D%7D`), it is still possible to use `_contains` without a problem (with MariaDB 10.7 at least). 

The change was introduced in this commit: 
https://github.com/directus/directus/pull/7501

Right now it looks like this in `get-filter-operators-for-type.ts` (https://github.com/directus/directus/blob/main/packages/shared/src/utils/get-filter-operators-for-type.ts):
```
case 'json':
    return ['null', 'nnull'];
```

Would it be possible to change this to:
```
case 'json':
    return ['null', 'nnull', 'contains'];
```

As a side note, [this](https://github.com/directus/directus/discussions/7277) would be even better, but I imagine, that takes some additional time and thought to properly implement.

### To Reproduce

1. Create a collection with a field of type JSON
2. Try to use the filter interface on the tabular view of the collection
3. Select the JSON field
4. Try to use `_contains` as operator

### What version of Directus are you using?

9.3

### What version of Node.js are you using?

16

### What database are you using?

MariaDB

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
> Would it be possible to change this to:

I'm afraid it's not. The `_contains` filter uses a text substring search (through SQL LIKE), which only works in some databases where the JSON is stored as plain text rather than a binary representation of the value (like is the case in Postgres). Therefore, even though it might work in some database vendors, we can't expose it in the app, as it will fail for other users.

There's an ongoing discussion on how to implement dedicated filtering magic for JSON values in https://github.com/directus/directus/discussions/7277. I'd love to hear your thoughts and use cases on this topic there 🙂

**Comment by julbd** [comment]
@rijkvanzanten If I may insist, we had an important use of the `_contains` filter on JSON fields. Now, we have no way to search or filter inside repeaters fields in our admin interface, while those fields contains most of our datas and classification. This is a huge restriction.

What do you think about re-enabling it when supported, despite consistency issues, until a better solution like #7277 (or a fallback for binary-stored JSON) is implemented ?

**Comment by rijkvanzanten** [comment]
The API will still allow for it, so you could setup custom bookmarks / presets through settings that include the _contains still. I don't think we'll add it to UI of the filter input at this point, cause of the reasons mentioned above.

**Comment by keyofd** [comment]
Also need to search for json, hope there can be a configuration, let us decide whether to enable
