### ISSUE TITLE
Hy everyone,how to fix this problem in Maps?

### ISSUE THREAD

**Issue by Ivann-2612** [directus/directus#10648]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

{
  "message": "insert into `Maps` (`date_created`, `maps`) values ('2021-12-23 10:05:31.447', st_geomfromtext('POINT (20.470335637359682 44.798384278334936)', 4326)) - SQLITE_ERROR: no such function: st_geomfromtext",
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR"
  }
}

### To Reproduce

When i want to save maps i have this bug

### What version of Directus are you using?

9.2.2

### What version of Node.js are you using?

16.13.1

### What database are you using?

SQLite

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Locally

**Comment by Oreilles** [comment]
Spatialite is required to fully enable geospatial feature when using Directus with SQLite (https://github.com/directus/directus/issues/7625)
A draft PR is on the work where you can find instructions on how to install and setup Spatialite for use with Directus https://github.com/directus/directus/pull/9917
If that's not something you can do, you can also chose JSON as a geometry storage type when creating a "Map" field, which won't require any further configuration.

In the future, please take some time to try and find if you issue have already been posted by someone else before submitting a new one.
