### ISSUE TITLE
Cannot set display templates while creating a new M2M field

### ISSUE THREAD

**Issue by HitomiTenshi** [directus/directus#10649]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When creating a new M2M field you cannot set display templates in the Display or Interface section.

![firefox_2021-12-23_10-14-06](https://user-images.githubusercontent.com/7304212/147217937-c2ad561a-972f-4698-b8c5-1c7cb4e0c884.png)

![firefox_2021-12-23_10-14-22](https://user-images.githubusercontent.com/7304212/147217943-a893d74f-6874-4f65-b42a-64201b0fa7df.png)

This behavior is probably intended, because M2M fields create an intermediary collection only after the field has been finalized. Since the user can go back and change the target M2M collection it might not make sense to allow the user to create display templates during creation (unless you want to implement a bunch of validation checks).

It would be nice though if you could display some kind of notice that display templates can be created after the M2M field has been finalized instead of showing an empty dropdown which looks like a bug.

### To Reproduce

Start creating a new M2M field and go to either the Display or Interface section and try to create a display template.

### Errors Shown

N/A

### What version of Directus are you using?

9.3.0

### What version of Node.js are you using?

16.13.1

### What database are you using?

MariaDB 10.3.32

### What browser are you using?

Firefox Latest

### What operating system are you using?

Windows 10

### How are you deploying Directus?

Ubuntu Server 20.04, npm installation with a systemd service running it

**Comment by rijkvanzanten** [comment]
> This behavior is probably intended, because M2M fields create an intermediary collection only after the field has been finalized. Since the user can go back and change the target M2M collection it might not make sense to allow the user to create display templates during creation (unless you want to implement a bunch of validation checks).

This is exactly the case. There are no fields yet, heck the whole collection might not even exist at that point, so it's a little tricky to configure things at that stage.

> It would be nice though if you could display some kind of notice that display templates can be created after the M2M field has been finalized instead of showing an empty dropdown which looks like a bug.

Agreed 👍🏻
