### ISSUE TITLE
Builder (M2A) interface show no results

### ISSUE THREAD

**Issue by idflood** [directus/directus#10650]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The builder interface is empty on 9.2 and 9.3.

![Screenshot 2021-12-23 at 10 12 50](https://user-images.githubusercontent.com/197418/147218097-c014608f-5f7c-435a-893b-ecb1f0530c53.png)

On the list page it correctly show that there should be 2 items:
![Screenshot 2021-12-23 at 10 13 00](https://user-images.githubusercontent.com/197418/147218193-15246097-c55d-4659-8cf8-8807814c4165.png)

After downgrading to Directus 9.1 the builder shows the correct content:
![Screenshot 2021-12-23 at 10 12 08](https://user-images.githubusercontent.com/197418/147218265-a232ae76-bbe1-4ab0-ac4f-5c4236e97ae1.png)

### To Reproduce

1. Create one or two hidden collections which will be used for the builder field later. For ex:
  - `module_text`:
  -- enable the _sort_ field
  -- add a _title_ and a _text_ field
  - `module_cta`:
  -- also with the _sort_ field, and a _title_ field
2. Create a `page` collection, with a title. Select the 2 previously created collections for the relationship.
3. Add a builder field `content` to the page. In advanced mode I added a `sort` sort field but it may not be required

Now if you add a page content, when creating a `module_text` or `module_cta` in the _content_ field there is no error shown but it stays empty. Going on the page collection the correct number of items is shown in the "content".

### Errors Shown

No error in console or in docker logs

### What version of Directus are you using?

9.3.0 and 9.1

### What version of Node.js are you using?

The one provided with the docker image

### What database are you using?

Postgres 13 and mariadb

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

locally (Docker)

**Comment by paescuj** [comment]
Duplicate of #10617

**Comment by idflood** [comment]
Oops sorry, forgot to check the merge requests
