### ISSUE TITLE
Show sample data on install

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1065]
On installation, if you choose to add "Sample Data" it adds tables into the database but you can't see the table (ui_gallery) in the sidebar. It should add in the extra settings/data needed to show the actual table in the UI. 

![screen shot 2015-11-04 at 9 33 06 pm](https://cloud.githubusercontent.com/assets/522079/10958424/cd3a5746-833b-11e5-857c-ccf98a24dc2d.png)

**Comment by benhaynes** [comment]
Good! But can we not show the `ui_files` and `ui_users` tables? They are junction tables and wouldn't be editable. We should clean up this demo table so it's really useful...

**Comment by WellingGuzman** [comment]
@benhaynes [this commit](f76ea7d9cce7e1516e12955998087d0bb7208cab) hides `ui_files` and `ui_users` tables.

**Comment by benhaynes** [comment]
Perfect!
