### ISSUE TITLE
Graphql not working in custom interface since 9.4

### ISSUE THREAD

**Issue by fouss** [directus/directus#10668]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a custom interface with a graphql request (using useApi()), since 9.4, the call from the interface return a 500 error : 
`[
    {
        "message": "TypeError[directus_shares.collection]: Definition object should contain 'type' property: Object({ type: undefined, resolve: [function resolve] })",
        "extensions": {
            "code": "INTERNAL_SERVER_ERROR"
        }
    }
]`
But the call works like before from an API platform (Thunder & Postman). Does anyone have an idea of what am I missing ?
thanks

### To Reproduce

send graphql request from a custom interface

### What version of Directus are you using?

9.4

### What version of Node.js are you using?

16.13.1

### What database are you using?

MySQL:8

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying Directus?

Docker

**Comment by Nik96i** [comment]
I also have this problem, I don't have any custom code or custom interfaces. i upgrade my project to 9.4.0 and all GraphQL requests stop working. the REST APIs is OK, and also the GraphQL public requests is ok, but when i add a Bearer token and send authenticated request, it returns this:
`{
  "errors": [
    {
      "message": "An unexpected error occurred.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}`
