### ISSUE TITLE
Latest docker image isn't applying necessary database migrations

### ISSUE THREAD

**Issue by donaldrich80** [directus/directus#10687]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

It appears the newest release version of the docker image isn't applying the necessary additions to the database schema, causing both loss of ability to log in and perform queries.

### Issue no.1:

I have been able to fix the login issue by adding the missing `data` field in `directus_sessions` with the following:

```sql
ALTER TABLE directus_sessions
ADD COLUMN data JSON;
```

### Issue no.2:

Attempting to perform graphql queries results in the following error message: 

```json
{
  "errors": [
    {
      "message": "TypeError[directus_shares.collection]: Definition object should contain 'type' property: Object({ type: undefined, resolve: [function resolve] })",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```
I haven't yet had a chance to determine what Issue no.2 looks like at the database level.  But given the nature of the impacts, wanted to give awareness to things.

### To Reproduce

Create a working Directus instance using docker image version 9.3, then upgrade to latest

### Errors Shown

Didn't get a chance to save the login error message, but was descriptive enough to identify the problem

Here is the error message related to the query problem:

```json
{
  "errors": [
    {
      "message": "TypeError[directus_shares.collection]: Definition object should contain 'type' property: Object({ type: undefined, resolve: [function resolve] })",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### What version of Directus are you using?

9.3 to 9.4

### What version of Node.js are you using?

whatever docker image is using

### What database are you using?

postgres:13-alpine docker image

### What browser are you using?

Chrome

### What operating system are you using?

Chromebook

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Regarding the first issue, can you confirm whether the error also stems from the Add Shares migration as described by #10669? Basically whether the error logged before you used the SQL script to patch it is the same. With that said, let's track your first issue over at #10669 as it's a prior and more specific ticket. Feel free to reply over there as well.

As for the second issue, no worries. It has been reported by #10668 and resolved by #10674 👍
