### ISSUE TITLE
Adding an existing table under settings

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1068]
If you have added a table into the database, and then add it through Directus /settings/tables... if you add one table it works, but if you add a second (without refreshing the page) then you get a "This table already exists" error. This is related to https://github.com/RNGR/Directus/issues/1067
 
![screen shot 2015-11-10 at 8 42 54 pm](https://cloud.githubusercontent.com/assets/522079/11081586/e572ac50-87eb-11e5-9062-7f8ed5d8197a.png)

**Comment by benhaynes** [comment]
@WellingGuzman Also, is there a reason we can't find any tables in the DB (not added to Directus) and show them in the Settings/Tables list... even if we gray them out and put a "Add" button next to them? That would be easier for importing tables that you already have in the database. Thoughts?

**Comment by WellingGuzman** [comment]
@benhaynes we can add an option on Directus to users can enable or disable weather or not they want to Directus to get all tables from the database, and it will be enabled by default. __*But*__ all these tables will be listed without any permission, so at the end users won't be able to perform any task on none of these tables.

It can be in the same list but grayed out, or (What I prefer) being all grayed out but under the main (active) list, and with the "Add" button next to them, and when you click "Add" it will give the current group "view" permission.

What do you think?

**Comment by benhaynes** [comment]
I think that's perfect – but they should be listed in gray (with an "Add" button) only on the Settings>Tables page... not in the actual user interface. Clicking the add button would insert the privileges needed to manage the tables.

I like it!

**Comment by WellingGuzman** [comment]
Exactly it will only be visible on Settings>Tables page, but what do you think about having the tables in a separate list (of inactive or not in directus) under the main/active list, same as we do with inactive users in Users?

**Comment by benhaynes** [comment]
I think that's a great idea... keep them separate so it's less confusing!

**Comment by benhaynes** [comment]
@WellingGuzman what do you think time-wise for this?
