### ISSUE TITLE
Changing UI to Single File is not saving relational settings in directus_columns

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1069]
In the screenshot below, you can see that the demo table (ui_gallery) has the appropriate relational settings, but the column that I changed to be a "Single File" does not. 

I added this table/column in the database directly, then added the table into directus on `/settings/tables` and then went in and changed the UI type to Single File. It _should_ set all the needed `directus_columns` data so that the UI functions properly. 

Using the most recent development branch commit (f72a474467b488c4661ce18ac9e0bb8b9e2b9d1e) with a clean DB install.

**Comment by WellingGuzman** [comment]
@benhaynes there's not screenshot below :smile: 

Is this happening on all relational column? I'd take a look and get back at you.

**Comment by benhaynes** [comment]
@WellingGuzman 
Whoops! Here's another screenshot. I can test on other relational columns, but it's definitely happening on Single File. If you *change* a UI type to be relational... it needs to create the right `directus_column` data for the relationship.

![screen shot 2015-11-16 at 11 38 49 am](https://cloud.githubusercontent.com/assets/522079/11187969/ac08cf34-8c56-11e5-9e9e-f3b5e9afd117.png)

**Comment by benhaynes** [comment]
It works!

Although it's odd – it's saving "ui" in the `directus_columns.junction_key_right` field... I *think* it is supposed to save the column name. @WellingGuzman thoughts?
