### ISSUE TITLE
Upgrading to 9.4.0 Fails with DB Error while running migration

### ISSUE THREAD

**Issue by Prochy20** [directus/directus#10693]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hello, 

I recently got this issue when upgrading from directus 9.3.0 to directus 9.4.0

```create table `directus_shares` (`id` char(36), `name` varchar(255), `collection` varchar(64), `item` varchar(255), `role` char(36), `password` varchar(255), `user_created` char(36), `date_created` timestamp default CURRENT_TIMESTAMP, `date_start` timestamp, `date_end` timestamp, `times_used` int default '0', `max_uses` int) - ER_INVALID_DEFAULT: Invalid default value for 'date_start```

My Environment:

APP: Directus 9.3.0
OS: Ubuntu 18.04 LTS
MySQL:  Ver 14.14 Distrib 5.7.36, for Linux (x86_64) using  EditLine wrapper
Node: 14.18.2

### To Reproduce

1. Install directus v. 9.3.0
2. Execute ``` npm update ```
3. Execute ```npx directus database migrate:latest```

### Errors Shown

create table `directus_shares` (`id` char(36), `name` varchar(255), `collection` varchar(64), `item` varchar(255), `role` char(36), `password` varchar(255), `user_created` char(36), `date_created` timestamp default CURRENT_TIMESTAMP, `date_start` timestamp, `date_end` timestamp, `times_used` int default '0', `max_uses` int) - ER_INVALID_DEFAULT: Invalid default value for 'date_start

### What version of Directus are you using?

9.3.0

### What version of Node.js are you using?

14.18.2

### What database are you using?

MySQL:  Ver 14.14 Distrib 5.7.36, for Linux (x86_64) using  EditLine wrapper

### What browser are you using?

Google Chrome v 96.0.4664.110

### What operating system are you using?

Desktop: MacOS Monterey 12.1 | Server: Ubuntu 18.04 LTS

### How are you deploying Directus?

Digital Ocean VPS (Using Ubuntu 18.04 LTS)

**Comment by eikaramba** [comment]
i can share my experience as well:
I upgraded from 9.3.0 to 9.4.0 and then started directus. i saw "Database migrations have not all been run". sure enough no "directus_shares" table. then i executed "npx directus database migrate:latest". it seems to work now.

**Comment by samfroggy** [comment]
Hi @Prochy20 and @eikaramba 
This is because your MySQL Server has `NO_ZERO_DATE` option turned on, the migration script doesn't have a default value, hence your MySQL Server not allowing that database query to run.

Remove `NO_ZERO_DATE` in your MySQL Server config file `my.ini`, the Directus Team might be able to weigh in on whether they want to add a default value to those fields.

**Comment by Prochy20** [comment]
> Hi @Prochy20 and @eikaramba This is because your MySQL Server has `NO_ZERO_DATE` option turned on, the migration script doesn't have a default value, hence your MySQL Server not allowing that database query to run.
> 
> Remove `NO_ZERO_DATE` in your MySQL Server config file `my.ini`, the Directus Team might be able to weigh in on whether they want to add a default value to those fields.

Thanks, this was the issue. I found this tutorial for solution: https://kevdees.com/disable-mysql-strict-mode-and-no_zero_date-errors-in-homestead/ .

Closing the ticket.

**Comment by eikaramba** [comment]
i am using sqlite not mysql. i suppose however  that https://github.com/directus/directus/pull/10736/files fixes the issue i have with refreshing the tokens. will try once 9.4.1 is out

**Comment by rijkvanzanten** [comment]
> the Directus Team might be able to weigh in on whether they want to add a default value to those fields.

@samfroggy I don't think we'd want to set default values for date_start and date_end on the share, as those values are optional.
