### ISSUE TITLE
[API] Cannot use filter operators the O2M field itself

### ISSUE THREAD

**Issue by julbd** [directus/directus#10695]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When attempting to filter items that have an empty O2M field (= there is no relations), Directus always thinks the operators (`_null`, `_nnull`, `_empty`, `_nempty`, etc...) are nested field names and throw `column bar._null does not exist`. I did not found others way to tell Directus to check the relation itself (does it exists or not) and not the related fields.

As a workaround, passing a field name like `filter[bar_relations][id][operator]=true` could work for the `_nnull` operator (`id` is always set), but not for `_null` (non-existent relations cannot have their `id` field tested and the parent item will not be returned)

I did not checked this error for others relation types.

### To Reproduce

```
GET /items/foo?fields=id%2Cbar_relations&filter[bar_relations][_null]=true
```

### Errors Shown

```
{
  errors: [
    {
      message: 'select "foo"."id", from "foo" where ("foo"."id" in (select "bar"."foo_relation" as "foo_relation" from "bar" where "bar"."_null" is null)) order by "foo"."id" asc limit $1 - column bar._nnull does not exist',
    }
  ]
}
```

### Solution

When the field to filter is a relation, check whether the passed property is a _logical operator_ that can be used on the relation itself (`_null`, `_nnull` ; maybe`_empty` and `_nempty` ; `_eq`, `_neq`, `_lt`, `_lte`, `gt`, `gte`, `_in`, `_nin` and `_between` if tested against the ID). If not, or if its does not start with `_`, we can process it as a nested field name.

### What version of Directus are you using?

9.3.0

### What version of Node.js are you using?

14.15.4

### What database are you using?

Postgres 13

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
This is correct. There's currently no filter operators that can be used to check against the one to many "value" itself, as it technically doesn't exist as a column. There's a couple discussions around how to add dedicated filter operators that can be used to filter against the state of the related items (eg check against the count of related items, which in turn allows for things like "where no items are related" or "where no more than 5 items are related"), see for example https://github.com/directus/directus/discussions/7178
