### ISSUE TITLE
Title sometimes hangs on Loading...

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#10707]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Most of the times, the title on the loading page hangs on `Loading...`. Sometimes, when refreshing the page while the app is already open, the correct title appears.

### To Reproduce

Open a production bundle, and throttle the network speed in the devtools

### Errors Shown

n/a

### What version of Directus are you using?

9.3.0

### What version of Node.js are you using?

16

### What database are you using?

Postgres 13

### What browser are you using?

Edge

### What operating system are you using?

macOS Monterrey

### How are you deploying Directus?

Cloud, locally

**Comment by licitdev** [comment]
This issue exists for me if there are custom displays. The loading text remains when visiting the login page. 

Somehow shifting `registerDisplays(app)` in https://github.com/directus/directus/blob/40ec3229983f22ddf478d6bc191df4dd45ba4500/app/src/main.ts#L46-L54 to after `app.mount('#app')` seems to resolve the issue...
