### ISSUE TITLE
Incorrect graphql api for M2M relations on create (and probably in other cases)

### ISSUE THREAD

**Issue by terion-name** [directus/directus#10717]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Given M2M relation (e.g. orders and products)

<img width="753" alt="Снимок экрана 2021-12-27 в 23 20 34" src="https://user-images.githubusercontent.com/1060205/147507969-1bd83148-8881-490f-aa0f-1d46787d8cb3.png">

Giving public access for creating `orders` and `orders products`

<img width="683" alt="Снимок экрана 2021-12-27 в 23 18 26" src="https://user-images.githubusercontent.com/1060205/147507900-00bb9a1b-68bc-4edd-ae0b-74d6ef91498e.png">

GraphQL API for `create_orders_item` has such schema:

<img width="896" alt="Снимок экрана 2021-12-27 в 23 22 32" src="https://user-images.githubusercontent.com/1060205/147508067-f433194b-d04c-4747-8b96-e38f94673f16.png">

`create_orders_products_input` in `create_orders_item` should not have `product_id` input (e.g. it should be a different type alike `create_orders_products_without_orders_input`) because it is a nested relationship for product and it should be binded to parent product that is being created

Also if I remove access for `orders products` creation or remove `orders products → products_id` creation filed access — input schema becomes `{..., products_id: String}` — what string is it supposed to be isn't clear

### To Reproduce

n/a

### What version of Directus are you using?

9.4.0

### What version of Node.js are you using?

16.2.0

### What database are you using?

mysql

### What browser are you using?

brave

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
> create_orders_products_input in create_orders_item should not have product_id input (e.g. it should be a different type alike create_orders_products_without_orders_input) because it is a nested relationship for product and it should be binded to parent product that is being created

I might be misunderstanding what you're saying, but this sounds like it's working as intended. Please see https://docs.directus.io/reference/introduction/#relational-data for more information about nested m2m/m2a structures.

**Comment by terion-name** [comment]
@rijkvanzanten well it's maybe kinda working as intended, but it is a bad graphql api design — that's what I'm talking about.

**Comment by rijkvanzanten** [comment]
@terion-name A many-to-many is inherently a one-to-many to the junction table, followed by another many-to-one to the related table. The junction table is no different from any other collection, and can have it's own fields etc.

> but it is a bad graphql api design

This is a pointless comment without elaborating on _why_ you think it is, what you suggest doing differently, and how you'd solve all the design challenges that come with those changes.

**Comment by terion-name** [comment]
> The junction table is no different from any other collection, and can have it's own fields etc.

It is not about junction table, it is about creating child relations

> This is a pointless comment without elaborating on why you think it is, what you suggest doing differently, and how you'd solve all the design challenges that come with those changes.

@rijkvanzanten For context: I work with graphql almost from it's early public release, build complex integrated systems upon it, client and server side, gateways and federated graphs of own design, frameworks and tools. In short that means: I've kinda experienced probably all the pain that is related to graphql 🤣 🤣 🤣 

The whole point and joy of graphql is it's strong typing. And by strong I mean **strong** and strict and without redundancies. This provides magical possibilities for very big amount of usecases. In case of subject, when one creates not a  junction table record by itself but a nested record through parent creation, link to this parent must be filled internally with newly created item id — and it does so, but this also means that input should not contain the field for this link: I can't create a nested record with different parent id, so I should have no possibility to provide this id and break data integrity. So this input should have different type with different fieldset.
Example of good graphql api design (probably because of graphql's core team members participation) is prisma graphql and their `open-crud` spec (spec is old and was not updated for a long time, currently their api developed further, but ideas where settled there). Their api is strict as hell and yes, this opens up endless possibilities to work with it. Downsides of this are complexity of generation logic and in bigger projects types definitions list and introspections can grow **huge**, but this is a fair price.

Currently directus graphql api is just a simple layer over rest api (and even without possibility to add custom queries as I can see) and being such it has some flaws, but I would recommend to take a look at design concept and maybe spin up a process of building more graphql-dedicated api. It is a great tool if implemented wisely. Obviously it is complex and not fast process, but a point to think about, IMHO.

PS
I hope that my formulations are understandable properly, I'm not a native speaker

**Comment by rijkvanzanten** [comment]
> but this also means that input should not contain the field for this link: I can't create a nested record with different parent id, so I should have no possibility to provide this id and break data integrity. So this input should have different type with different fieldset.

Yup! This is a known issue https://github.com/directus/directus/issues/10451.

> Currently directus graphql api is just a simple layer over rest api

This is not true. GraphQL isn't layered on top of the REST endpoints. They're standalone. The GraphQL service is a custom implementation with its own design.
