### ISSUE TITLE
Getting 404 for custom endpoint extensions

### ISSUE THREAD

**Issue by kadiresen** [directus/directus#10742]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

My sample endpoint code is:

```javascript
export default (router) => {
	router.get('/', (req, res) => res.send('Hello, World!'));
};
```

### To Reproduce

I've created an endpoint extension via ```npm init directus-exntension``` and built it. I can see my custom endpoint extension when Directus is starting up:

![image](https://user-images.githubusercontent.com/6187546/147607577-2c5c8c83-2d6d-4e3a-ac8f-4d82d608de95.png)

I've also tried these urls:
http://localhost:8055/mytest
http://localhost:8055/custom/mytest
http://localhost:8055/extensions/endpoints/mytest

### Errors Shown

![image](https://user-images.githubusercontent.com/6187546/147607419-33ae9bbe-bcab-4518-ac40-6b66b4a6c722.png)

### What version of Directus are you using?

9.4.0

### What version of Node.js are you using?

16.13.1

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

macOS Monterey (12)

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment]
Hmm I've just created the exact same extension via `npm init directus-extension` and it seems to work on my end. Here's some detail:

### Options chosen

![WindowsTerminal_QrrPMDx791](https://user-images.githubusercontent.com/42867097/147629359-b92c6bb2-4907-4acd-84df-ab8b582452c1.png)

### Terminal logs

![WindowsTerminal_v8l7bLYAHC](https://user-images.githubusercontent.com/42867097/147629374-f372c049-faed-4e24-8049-4e78a055dc5e.png)

### Accessing `/mytest` endpoint

![chrome_ZWCasbbghQ](https://user-images.githubusercontent.com/42867097/147629380-b4aa7e1f-9bee-4d13-a9fd-a57ad9727cbb.png)

---

> I've also tried these urls:
> http://localhost:8055/mytest
> http://localhost:8055/custom/mytest
> http://localhost:8055/extensions/endpoints/mytest

The first one should be the correct one. Just wondering, were you able to replicate this issue with a fresh install of Directus? unless it already is.

Would you mind to provide the resulting folder/file structure of your built extension? Did you put it in `/extensions/mytest/index.js`?

![Code_QOIxEhjOjN](https://user-images.githubusercontent.com/42867097/147629489-a7c48b41-c369-4591-baef-c307ea785223.png)

**Comment by kadiresen** [comment]
Yes, trying it with fresh install of Directus. Here is the whole summary:

![image](https://user-images.githubusercontent.com/6187546/147631711-c7f133b6-e4a9-4c29-b2ec-afbfa6436735.png)

Project tree:

![image](https://user-images.githubusercontent.com/6187546/147631994-c747b9fa-dbbc-4b16-9bcb-b8254df7f89c.png)

and the result:

![image](https://user-images.githubusercontent.com/6187546/147631862-ba9370fa-787a-4981-b7c3-866e973cdd17.png)

**Comment by azrikahar** [comment]
Thanks for the detailed screenshots. You should create the `mytest` extension project _outside_ of your directus project, not inside the `extensions` folder. Notice how my screenshot showed `/extensions/endpoints/mytest/index.js` only, no package.json file or other files. You can also see the error shown to you saying it failed to find that file.

Just to clarify, it should look something like this:

```
.
├── directus
│   ├── extensions/
│   │   └── endpoints/
│   │       └── mytest/
│   │           └── index.js <--------------- Paste that file here
│   ├── uploads/
│   ├── .env
│   └── package.json
│ 
└── mytest/
    ├── dist/
    │   └── index.js <--------------- Copy this file
    ├── src/
    ├── package.json
    └── package-lock.json
```

Hope that clears things up. I'll proceed to close this issue since it's more of a setup problem rather than an actual bug 👍
