### ISSUE TITLE
Error accessing data after adjusting one of its UI options

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1075]
After updating a UI option ("rows" under `projects.client`) and then trying to view that table... I get the following SQL error:

![screen shot 2015-11-12 at 11 29 20 pm](https://cloud.githubusercontent.com/assets/522079/11138827/6ab1946c-8995-11e5-9217-a3902de1debe.png)

**Comment by WellingGuzman** [comment]
@benhaynes we should define what `primary_column` means, does it means _*primary_key_column*_ OR _*primary_table_representation_column*_?

**Comment by benhaynes** [comment]
Good question @WellingGuzman 

But first off, let's verify we still need this. Where is `primary_column` used? I remember it was mostly in `activity` and `messages`. Is there anywhere else? Also, sometimes you need to represent the row with more than one column (`first_name last_name`) – so maybe there's a better way to choose columns.

Other than that, I think that, since it's within `directus_tables` I don't think it needs to say "table". So if we keep this column I think it should be called: `item_representation` or `item_title` or `item_display`

Thoughts?

**Comment by benhaynes** [comment]
Working!

For `primary_column` – it looks like you've removed this from the interface (good!) where is this value referenced in the system?
