### ISSUE TITLE
Data Sharing  "Error"

### ISSUE THREAD

**Issue by hugopvl** [directus/directus#10783]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I think that this situation had already been communicated, and was already corrected, but the same thing continues to happen to me. every time I do a share: image attached
<img width="656" alt="Captura de ecrã 2021-12-31, às 10 28 29" src="https://user-images.githubusercontent.com/81326296/147818427-1595c29a-9592-4fba-9e15-566fca4a8d2b.png">
<img width="557" alt="Captura de ecrã 2021-12-31, às 10 35 57" src="https://user-images.githubusercontent.com/81326296/147818694-8599a57e-bd89-4ccd-bc14-dba458c4ad0f.png">

.

### To Reproduce

just create a new share and share it

### What version of Directus are you using?

9.4.2

### What version of Node.js are you using?

16.13.0

### What database are you using?

MSSQLSERVER

### What browser are you using?

Chrome

### What operating system are you using?

macOS / Windows

### How are you deploying Directus?

locally on debian server

**Comment by rijkvanzanten** [comment]
Heya! That message shows up when the share isn't or is no longer available. Just to confirm, did you wait until 12pm before checking the share link? I noticed in your screenshot it said "created 9:49" 🙂

if that wasn't the issue, could you try nullifying the time restriction to see if that's where the problem lies? Thanks!

**Comment by hugopvl** [comment]
by chance I hadn't thought about it, because in reality the database keeps the correct day but the time is 1h early I think because time zone, I need to check this situation. @rijkvanzanten  you have hawk eyes 🤣

Thanks

**Comment by hugopvl** [comment]
well, you are right, it was really the problem of the hour, thank you and sorry for opening an issues for that.  Happy New Year to everyone 😎🎆

**Comment by azrikahar** [comment]
@hugopvl thanks for the update! I'll proceed to close this now 👍
