### ISSUE TITLE
Directus 9 stuck at Loading

### ISSUE THREAD

**Issue by anjovanovic** [directus/directus#10806]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hi,

After fresh install I cannot access to webapp.

![image](https://user-images.githubusercontent.com/87826818/147879295-723d0e94-db3e-4b30-ad05-a448f0eec4b1.png)

It seems like some path are forced to ssl...

<details>
<summary>.env file here</summary>

```
####################################################################################################
## General

PORT=8055
PUBLIC_URL="http://10.84.10.62:8055"
LOG_LEVEL="info"
LOG_STYLE="pretty"

####################################################################################################
## Database

DB_CLIENT="mysql"
DB_HOST="127.0.0.1"
DB_PORT="3306"
DB_DATABASE="directus"
DB_USER="root"
DB_PASSWORD="******"


####################################################################################################
## Rate Limiting

RATE_LIMITER_ENABLED=false
RATE_LIMITER_STORE=memory
RATE_LIMITER_POINTS=25
RATE_LIMITER_DURATION=1

####################################################################################################
## Cache

CACHE_ENABLED=false

####################################################################################################
## File Storage

STORAGE_LOCATIONS="local"
STORAGE_LOCAL_DRIVER="local"
STORAGE_LOCAL_ROOT="./uploads"

####################################################################################################
## Security

KEY="397cdbb6-f844-4cf3-9984-3c34a3573b43"
SECRET="CsfiVWlATjaienCUvfzA5Hzp3s3C11ES"


ACCESS_TOKEN_TTL="15m"
REFRESH_TOKEN_TTL="7d"
REFRESH_TOKEN_COOKIE_SECURE="false"
REFRESH_TOKEN_COOKIE_SAME_SITE="lax"
REFRESH_TOKEN_COOKIE_NAME="directus_refresh_token"

CORS_ENABLED="true"
CORS_ORIGIN="true"
CORS_METHODS=GET,POST,PATCH,DELETE
CORS_ALLOWED_HEADERS=Content-Type,Authorization
CORS_EXPOSED_HEADERS=Content-Range
CORS_CREDENTIALS="true"
CORS_MAX_AGE=18000


####################################################################################################
## Auth Providers

AUTH_PROVIDERS=""

####################################################################################################
## Extensions

EXTENSIONS_PATH="./extensions"

####################################################################################################
## Email

#EMAIL_FROM="no-reply@directus.io"
#EMAIL_TRANSPORT="sendmail"
#EMAIL_SENDMAIL_NEW_LINE="unix"
```

</details>

```shell
[root@d9-test classic]# npx directus start
15:36:05 ⚠️  DB_CHARSET hasn't been set. Please make sure DB_CHARSET matches your database's collation.
15:36:05 ✨ Server started at http://localhost:8055
15:36:08 ✨ request completed GET 200 /admin 6ms
```

there is no errors in console... 

### To Reproduce

EDIT: This can also be reproduced by using the Docker image on a VPS, even with PUBLIC_URL set as `http://<ip-address>:8055`.

Alternatively:

1. Follow [installation](https://docs.directus.io/getting-started/installation/cli/) steps

   ```shell
   cd dir
   npx directus start
   ```

### Errors Shown

no

### What version of Directus are you using?

9.4.2

### What version of Node.js are you using?

v14.17.5

### What database are you using?

mysql 8

### What browser are you using?

Chrome, Firefox, Internet Explorer

### What operating system are you using?

Server: Oracle Linux 8, Web client on windows 10

### How are you deploying Directus?

locally

**Comment by Olyno** [comment]
I can confirm this problem, i used the DigitalOcean one click way, and i'm getting stuck without touching to anything, on Ubuntu 18.

**Comment by Olyno** [comment]
Okay i'm coming back with some news. I fixed this issue by setting HTTPS using the steps below
![image](https://user-images.githubusercontent.com/25107942/147897973-00a2d502-321d-432b-bf6b-d9b9fb0d4d93.png)

**Comment by azrikahar** [comment]
Can confirm this happens on 9.4.2, but not 9.4.1. This is caused by a [change in 9.4.2]](https://github.com/directus/directus/commit/98cf1349fdb8b0f468c00edb1714c81e2f0f90d9) for security reasons, but may need to be reevaluated to prevent this from interrupting non HTTPS setups (even though this may not be recommended for production setups). 

@anjovanovic can you try downgrading to 9.4.1 instead for now and let us know how it goes?

**Comment by azrikahar** [comment]
@anjovanovic on second thought, would you mind using adding this environment variable in your `.env` file:

```
CONTENT_SECURITY_POLICY_DIRECTIVES__UPGRADE_INSECURE_REQUESTS=null
```

This will prevent the scripts/styles from being automatically upgraded from HTTP to HTTPS.

**Comment by anjovanovic** [comment]
CONTENT_SECURITY_POLICY_DIRECTIVES__UPGRADE_INSECURE_REQUESTS=null
Now is everything ok with this line.

This is permanent or this be fixed in a different way in the source code in next release?

**Comment by azrikahar** [comment]
> Now is everything ok with this line.

Thanks for confirming!

> This is permanent or this will be fixed in a different way in the source code in next release?

We'll need to discuss further to come to a finalized approach as there's pros and cons between making it opt-in vs opt-out, but we'll be sure to give an update when we reach a consensus on this new configuration 👍

**Comment by beschneider** [comment]
This worked for me as well! Should I remove the line once I deploy to a production server that has https?

**Comment by rijkvanzanten** [comment]
@beschneider It's safer to have that header enabled, so we do recommend leaving it on if/when you can. 

That being said, I think we might have to make it opt-in by default rather than opt-out, as it's a tricky one to debug if you aren't aware of that particular header 🤔

**Comment by eikaramba** [comment]
for me that header wasn't making problems so i would like to enable it. however i am not sure how now that it is opt-in.
i guess i need to set `CONTENT_SECURITY_POLICY_DIRECTIVES__UPGRADE_INSECURE_REQUESTS`. but to what value?

**Comment by azrikahar** [comment]
I believe setting the value as `true` should work 👍

**Comment by chrisbartley** [comment]
> I believe setting the value as `true` should work 👍

Recently upgraded from Directus 9.3.0 to 9.4.2 (macOS 11.6.1, MySQL 5.7.19).  My Directus Admin running on localhost (my dev environment) works fine in Brave 1.33.106, but in Safari 15.1 I get the SSL errors when it tries to load some files from assets.

I tried adding the `CONTENT_SECURITY_POLICY_DIRECTIVES__UPGRADE_INSECURE_REQUESTS` property to my dev config file (I use .js config files rather than .env, if that matters?), but values of `null`, `false`, `"false"`, and `true` all produce the same error when I restart Directus:

```
Error: Content-Security-Policy received an invalid directive value for "upgrade-insecure-requests"
```

Perhaps interestingly, setting the property to a (string) value of `"null"` doesn't produce an error, but also doesn't fix the SSL problem in Safari.

Do I need to use a different property and/or value when using a .js Directus config file?

**Comment by eikaramba** [comment]
> I believe setting the value as `true` should work 👍

are you sure about that? i set `CONTENT_SECURITY_POLICY_DIRECTIVES__UPGRADE_INSECURE_REQUESTS=true` and now get
```
directiveValue is not iterable
    at normalizeDirectives (xxxxxx\node_modules\helmet\dist\middlewares\content-security-policy\index.js:64:25)
```
upon starting the server

**Comment by azrikahar** [comment]
@eikaramba oddly enough it was recommended to set as `true` [as seen here](https://github.com/helmetjs/csp/issues/36#issuecomment-218545243), but in hindsight it's probably outdated.

Setting it as an empty array seems to work for me, as that's what interpreted as a valid value now: `CONTENT_SECURITY_POLICY_DIRECTIVES__UPGRADE_INSECURE_REQUESTS="[]"`. Can you confirm this on your end?

**Comment by chrisbartley** [comment]
> @eikaramba oddly enough it was recommended to set as `true` [as seen here](https://github.com/helmetjs/csp/issues/36#issuecomment-218545243), but in hindsight it's probably outdated.
> 
> Setting it as an empty array seems to work for me, as that's what interpreted as a valid value now: `CONTENT_SECURITY_POLICY_DIRECTIVES__UPGRADE_INSECURE_REQUESTS="[]"`. Can you confirm this on your end?

I don't know about .env config files, but for .js config files at least, setting it to an empty array (`CONTENT_SECURITY_POLICY_DIRECTIVES__UPGRADE_INSECURE_REQUESTS: []`) doesn't produce an error, but also has no effect for me as far as removing the directive:

```shell
$ curl --HEAD  http://localhost:8055/admin
HTTP/1.1 200 OK
Content-Security-Policy: script-src 'self' 'unsafe-eval';upgrade-insecure-requests;default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src-attr 'none';style-src 'self' https: 'unsafe-inline'
X-Powered-By: Directus
Vary: Origin
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Content-Range
Cache-Control: no-cache
Content-Type: text/html; charset=utf-8
Content-Length: 7007
ETag: W/"1b5f-eFGdBFQclEM8kJtZn8HTA8dFm+8"
Date: Wed, 05 Jan 2022 04:27:16 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

**Comment by azrikahar** [comment]
>  but also has no effect for me as far as removing the directive

@chrisbartley they are actually looking to _enable_ it, hence setting it as an empty array will indeed enable it. 

Can you share how are you configuring it in your said js file? I have just tried it with the following syntax and it seems to work for me:

```js
module.exports = {
    // other configs
    
    CONTENT_SECURITY_POLICY_DIRECTIVES__UPGRADE_INSECURE_REQUESTS: 'null'
}
```

And when you say the above solution doesn't solve it for you on safari, can you verify does `upgrade-insecure-requests` still exist in the Content-Security-Policy header there?

**Comment by chrisbartley** [comment]
> they are actually looking to _enable_ it, hence setting it as an empty array will indeed enable it.

@azrikahar Thanks for the reply.  If I understand correctly, it's enabled by default for anyone using 9.4.2 (as I am, and the OP).  That's what #10830 fixes. The problem I (and presumably others) am having for 9.4.2 is not how to enable it, but how to _disable_ it.

> Can you share how are you configuring it in your said js file? 

It's in the parenthetical part of my last post, but here it is again:

```
CONTENT_SECURITY_POLICY_DIRECTIVES__UPGRADE_INSECURE_REQUESTS: []
```

Also, as I mentioned [above](https://github.com/directus/directus/issues/10806#issuecomment-1004927502), all of these as values produce an error: `null`, `false`, `"false"`, and `true`.  Using `"null"` produces no error, but also doesn't change anything.
  
> I have just tried it with the following syntax and it seems to work for me:
> 
> ```js
> module.exports = {
>     // other configs
>     
>     CONTENT_SECURITY_POLICY_DIRECTIVES__UPGRADE_INSECURE_REQUESTS: 'null'
> }
> ```

It works as in there are no errors upon startup, or works as in it actually has the effect of removing `upgrade-insecure-requests` from the CSP?  Because, for me, it has no effect at all on the CSP.  That's what I was intending to show by including the output from curl in my last message.  What do you get when you have the directive set to `'null'` and test with `curl --HEAD  http://localhost:8055/admin`?

> And when you say the above solution doesn't solve it for you on safari, can you verify does `upgrade-insecure-requests` still exist in the Content-Security-Policy header there?

Yes, see curl output from [above](https://github.com/directus/directus/issues/10806#issuecomment-1004927502).  The directive is there, it's just that Safari is apparently more strict than Brave.

Thanks!

**Comment by azrikahar** [comment]
> It works as in there are no errors upon startup, or works as in it actually has the effect of removing upgrade-insecure-requests from the CSP?

@chrisbartley this is what's quite odd to me, since it does work for me. I've just spun up another new instance on a VPS and here's the before/after (top half is before, bottom half is after) I add that flag I've shared, `CONTENT_SECURITY_POLICY_DIRECTIVES__UPGRADE_INSECURE_REQUESTS: 'null'`:

![WindowsTerminal_SIA6oBf3rg](https://user-images.githubusercontent.com/42867097/148230841-e151e0f7-c2b5-4b30-841d-2da3f320acea.png)

We can see that `upgrade-insecure-requests` is no longer in the CSP header in my case. I'm not sure what could be the reason why it doesn't work for you to be honest 🤔

---

Just to share the minimal setup I tested above, here are the relevant files:

### docker-compose.yml

```yaml
services:
    directus:
        image: directus/directus:9.4.2
        container_name: directus
        restart: unless-stopped
        volumes:
            - ./env.js:/directus/env.js
        environment:
            - CONFIG_PATH=./env.js
        ports:
            - 8989:8055
```

### env.js

```js
module.exports = {
    KEY: 'KEY',
    SECRET: 'SECRET',
    ADMIN_EMAIL: 'admin@example.com',
    ADMIN_PASSWORD: 'password',
    CONTENT_SECURITY_POLICY_DIRECTIVES__UPGRADE_INSECURE_REQUESTS: 'null'
}
```

**Comment by eikaramba** [comment]
i can confirm what @azrikahar  is saying. 'null' removes the header. '[]' includes it. i am using the normal .env file on windows. 9.4.2

**Comment by chrisbartley** [comment]
@azrikahar @eikaramba Ah, ok, thanks to you both!  I just tried with a new Directus project and disabling did indeed work fine. 🤔 

Apparently my other, original project was just in some sort of "special" state, perhaps a result of multiple upgrades from previous versions of Directus?  I decided to just blow away the existing `node_modules` directory, did an `npm install` and tried again with and without the `CONTENT_SECURITY_POLICY_DIRECTIVES__UPGRADE_INSECURE_REQUESTS: 'null'` and can now confirm that the null setting does indeed cause the directive to be removed from the CSP.  Crazy.  Sorry for the false alarm, but maybe this will help someone else having the same problem.

Before adding the config param:

```shell
$ curl --HEAD http://localhost:8055/admin
HTTP/1.1 200 OK
Content-Security-Policy: script-src 'self' 'unsafe-eval';upgrade-insecure-requests;default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src-attr 'none';style-src 'self' https: 'unsafe-inline'
X-Powered-By: Directus
Vary: Origin
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Content-Range
Cache-Control: no-cache
Content-Type: text/html; charset=utf-8
Content-Length: 7007
ETag: W/"1b5f-eFGdBFQclEM8kJtZn8HTA8dFm+8"
Date: Wed, 05 Jan 2022 15:03:39 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

...and after...

```shell
$ curl --HEAD http://localhost:8055/admin
HTTP/1.1 200 OK
Content-Security-Policy: script-src 'self' 'unsafe-eval';default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src-attr 'none';style-src 'self' https: 'unsafe-inline'
X-Powered-By: Directus
Vary: Origin
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Content-Range
Cache-Control: no-cache
Content-Type: text/html; charset=utf-8
Content-Length: 7007
ETag: W/"1b5f-eFGdBFQclEM8kJtZn8HTA8dFm+8"
Date: Wed, 05 Jan 2022 15:16:22 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

Good! 🎉

**Comment by PranehSrinivsan** [comment]
> ### Preflight Checklist
> * [x]  I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
> * [x]  I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
> * [x]  There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.
> 
> ### Describe the Bug
> Hi,
> 
> After fresh install I cannot access to webapp.
> 
> ![image](https://user-images.githubusercontent.com/87826818/147879295-723d0e94-db3e-4b30-ad05-a448f0eec4b1.png)
> 
> It seems like some path are forced to ssl...
> 
> .env file here
> ```shell
> [root@d9-test classic]# npx directus start
> 15:36:05 ⚠️  DB_CHARSET hasn't been set. Please make sure DB_CHARSET matches your database's collation.
> 15:36:05 ✨ Server started at http://localhost:8055
> 15:36:08 ✨ request completed GET 200 /admin 6ms
> ```
> 
> there is no errors in console...
> 
> ### To Reproduce
> EDIT: This can also be reproduced by using the Docker image on a VPS, even with PUBLIC_URL set as `http://<ip-address>:8055`.
> 
> Alternatively:
> 
> 1. Follow [installation](https://docs.directus.io/getting-started/installation/cli/) steps
>    ```shell
>    cd dir
>    npx directus start
>    ```
> 
> ### Errors Shown
> no
> 
> ### What version of Directus are you using?
> 9.4.2
> 
> ### What version of Node.js are you using?
> v14.17.5
> 
> ### What database are you using?
> mysql 8
> 
> ### What browser are you using?
> Chrome, Firefox, Internet Explorer
> 
> ### What operating system are you using?
> Server: Oracle Linux 8, Web client on windows 10
> 
> ### How are you deploying Directus?
> locally


17:25:09 Γ£¿ request completed POST 400 /auth/refresh 49ms
17:25:09 Γ£¿ request completed GET 200 /extensions/layouts/index.js 82ms
17:25:09 ≡ƒÜ¿ select `directus_settings`.`project_name`, `directus_settings`.`project_descriptor`, `directus_settings`.`project_logo`, `directus_settings`.`project_color`, `directus_settings`.`public_foreground`, `directus_settings`.`public_background`, `directus_settings`.`public_note`, `directus_settings`.`custom_css`, `directus_settings`.`id` from `directus_settings` order by `directus_settings`.`id` asc limit 1 - ER_BAD_FIELD_ERROR: Unknown column 'directus_settings.project_descriptor' in 'field list' 
Error: ER_BAD_FIELD_ERROR: Unknown column 'directus_settings.project_descriptor' in 'field list'

help me out wit this error

**Comment by benhaynes** [comment]
@PranehSrinivsan ... Looks like you need to run migrations.

**Comment by azrikahar** [comment]
@PranehSrinivsan I believe you have not run the latest migration as mentioned by @benhaynes. You can do so by running `npx directus database migrate:latest`. You can also refer here for more info: https://docs.directus.io/configuration/upgrades-migrations/#upgrading-updating-a-project 

Side note: What you have shared is a very different error from OP, so please do keep it on topic or open a separate issue if needed.

**Comment by vahidreza** [comment]
I don't know if this is related to this bug or I should post another issue, but I had the same bug described here and upgraded to docker image 9.4.3 and I verify that directus loads up now but unfortunately all of my resources get 403 (Forbidden) including photos, font files etc. I'm using directus on a private plan setup with no SSL involved.

<img width="1785" alt="Screen Shot 1400-10-18 at 14 59 29" src="https://user-images.githubusercontent.com/3737551/148642472-8278a1b8-aff3-4413-a9cd-f244d584e1a4.png">

as you can see the library is not showing any thumbnail or preview neighther:
<img width="848" alt="Screen Shot 1400-10-18 at 14 59 53" src="https://user-images.githubusercontent.com/3737551/148642475-0c610e49-d36a-4de2-9ac3-3da3aec1a331.png">

**Comment by azrikahar** [comment]
@vahidreza It's not not totally unrelated per se, but as the error suggests, seems like you are using custom fonts from `http://db.onlinewebfonts.com` which is violating the current [Content Security Policy `font-src` directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/font-src) of `'self' https: data:`.

You should be able to manually allow it by using the following environment variable & value:

```
CONTENT_SECURITY_POLICY_DIRECTIVES__FONT_SRC="'self' https: data: http://db.onlinewebfonts.com"
```

---

As for the photos throwing 403 error, based on your docker run command, I believe the error is correct since now your uploaded files are missing. You should make sure to persist the uploaded files by adding `-v /path/on/the/host:/directus/uploads` to your docker run command.

Do check all 3 potential locations that you may want to persist, depending on your current/future usage, which are listed over here: https://docs.directus.io/getting-started/installation/docker/#persistence

**Comment by vahidreza** [comment]
@azrikahar tnx. it worked. the only thing was that having set the volumes, the file upload service stopped working and [this comment](https://github.com/directus/directus/discussions/6480#discussioncomment-917708) helped me to resolve it.
