### ISSUE TITLE
Referencing a file id to an item cannot be done through the API

### ISSUE THREAD

**Issue by krazyjakee** [directus/directus#10804]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I cannot add a reference of a file to an item as the ID field is expected to be an integer but files can only be referenced by UUIDs

### To Reproduce

- Create a content type with a files reference.
- Upload a file
- Attempt to create a new piece of content that references the file...

```graphql
mutation {
	create_content_item(data: {
		name: "Content Title",
		images: [{ id: "92ba16da-6b89-497e-b100-db28859d2813" }]
		status: "published"
	})
	{
		id
		name
	}
}
```

### Errors Shown

`"message": "select \"id\" from \"content_files\" where \"id\" = $1 limit $2 - invalid input syntax for type integer: \"92ba16da-6b89-497e-b100-db28859d2813\"",`

### What version of Directus are you using?

9.4.2

### What version of Node.js are you using?

16.13.1

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
I believe your `images` field here is a many to many to directus_files, meaning that your schema would look a little something like:

```
content
  images
    id
    file_id
    content_id
```

When associating the file, you need to set the `file_id`[^1] rather than the primary key of the junction table.

[^1]: Actual field name based on your exact schema
