### ISSUE TITLE
update 9.4.2

### ISSUE THREAD

**Issue by genfild** [directus/directus#10825]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Не запускается

### To Reproduce

A warning occurs when upgrading to version 9.4.2:
 WARN  Issues with peer dependencies found
.
└─┬ directus
  └─┬ @directus/extensions-sdk
    └─┬ rollup-plugin-typescript2
      ├── ✕ missing peer typescript@>=2.4.0
      └─┬ @yarn-tool/resolve-package
        ├─┬ @ts-type/package-dts
        │ └─┬ ts-type
        │   ├── ✕ missing peer @types/bluebird@"*"
        │   ├── ✕ missing peer @types/node@"*"
        │   └── ✕ missing peer ts-toolbelt@^9.6.0
        └─┬ upath2
          └── ✕ missing peer @types/node@"*"
Peer dependencies that should be installed:
  @types/bluebird@"*"  @types/node@"*"      ts-toolbelt@^9.6.0   typescript@>=2.4.0   

### Errors Shown

data-model:137 GET .../admin/assets/index.22c0e154.entry.js net::ERR_CONNECTION_REFUSED
data-model:138 GET .../admin/assets/vendor.275c9c53.js net::ERR_CONNECTION_REFUSED
data-model:140 GET .../admin/assets/vendor.fe7856f0.css net::ERR_CONNECTION_REFUSED
data-model:141 GET .../admin/assets/index.ca954ed3.css net::ERR_CONNECTION_REFUSED
data-model:139 GET .../admin/assets/use-sync.7375bbee.js net::ERR_CONNECTION_REFUSED

### What version of Directus are you using?

9.4.2

### What version of Node.js are you using?

17.0.1

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu 20.04.3 LTS

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment]
Hi! Would you mind trying the solution here: https://github.com/directus/directus/issues/10806#issuecomment-1003876201? The warnings with peer dependencies aside, the errors seems somewhat similar, though not entirely. 

Let us know how it goes. If it still persists, I'll re-open this issue 👍 It'd also be very helpful if you can share more details such as 

- Which version are you upgrading _from_? 
- What are the actual step by steps/commands you have ran during said upgrade?
