### ISSUE TITLE
map does not show because of no default value of CONTENT_SECURITY_POLICY

### ISSUE THREAD

**Issue by torstenhoegel** [directus/directus#10834]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Since version 9.4.2 and the addition of Content Security Policy if there's no CONTENT_SECURITY_POLICY .env variable setup, the map functionality breaks.

This returns in the map showing like this:

<img width="753" alt="Bildschirmfoto 2022-01-04 um 00 25 33" src="https://user-images.githubusercontent.com/22012025/147991083-79df4e89-7f06-47eb-b5e6-253d1fd239ca.png">

and the following error in console:
```
vendor.2d8e5ab3.js:formatted:63994 Refused to create a worker from 'blob:https://mydomain.com/5c07e2bf-4d45-4b06-b03d-4600a69181e2' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.
```

### To Reproduce

.

### What version of Directus are you using?

v9.4.2

### What version of Node.js are you using?

.

### What database are you using?

.

### What browser are you using?

Chrome

### What operating system are you using?

.

### How are you deploying Directus?

PaaS, Docker

**Comment by roelvan** [comment]
Running into the same issue. I tried setting the CONTENT_SECURITY_POLICY in .env without success. How should this env var be configured correctly?

**Comment by azrikahar** [comment]
@roelvan Can you try `CONTENT_SECURITY_POLICY_DIRECTIVES__WORKER_SRC=array:blob:`? Note that there's double underscores between `DIRECTIVES` and `WORKER_SRC`, and `array:` prefix casts it as an array. More info here: https://docs.directus.io/configuration/config-options/#type-casting-and-nesting

So we're aiming to use the above env variable to create:

```js
{
    directive: {
        workerSrc: ["blob:"]
    }
}

based on [Helmet's docs](https://helmetjs.github.io/).

**Comment by sebastienklaus** [comment]
I got approximately the same issue :  `Refused to connect to 'https://c.tile.openstreetmap.org/16/33877/22609.png' because it violates the document's Content Security Policy. vendor.275c9c53.js:152 `

**Comment by azrikahar** [comment]
@sebastienklaus can you try adding two environment variables:

- `CONTENT_SECURITY_POLICY_DIRECTIVES__CONNECT_SRC="'self' https://*"`: This will allow the loading of tiles from openstreetmap.org.

- `CONTENT_SECURITY_POLICY_DIRECTIVES__WORKER_SRC="'self' blob:"`: This is to prevent the "Refused to create worker" faced by OP.

**Comment by roelvan** [comment]
> @sebastienklaus can you try adding two environment variables:
> 
>     * `CONTENT_SECURITY_POLICY_DIRECTIVES__CONNECT_SRC="'self' https://*"`: This will allow the loading of tiles from openstreetmap.org.
> 
>     * `CONTENT_SECURITY_POLICY_DIRECTIVES__WORKER_SRC="'self' blob:"`: This is to prevent the "Refused to create worker" faced by OP.

Thanks for posting the exact values! Helped me a lot understanding this.

**Comment by roelvan** [comment]
For those who want to make the map work, these worked for me:
```
CONTENT_SECURITY_POLICY_DIRECTIVES__CONNECT_SRC="'self' *.mapbox.com *.openstreetmap.org"
CONTENT_SECURITY_POLICY_DIRECTIVES__WORKER_SRC="'self' blob:"
CONTENT_SECURITY_POLICY_DIRECTIVES__IMG_SRC="'self' data: blob:"
CONTENT_SECURITY_POLICY_DIRECTIVES__SCRIPT_SRC="'self' 'unsafe-eval' *.mapbox.com"
CONTENT_SECURITY_POLICY_DIRECTIVES__DEFAULT_SRC="'self' *.mapbox.com"
```

**Comment by sebastienklaus** [comment]
> For those who want to make the map work, these worked for me:
> 
> ```
> CONTENT_SECURITY_POLICY_DIRECTIVES__CONNECT_SRC="'self' *.mapbox.com *.openstreetmap.org"
> CONTENT_SECURITY_POLICY_DIRECTIVES__WORKER_SRC="'self' blob:"
> CONTENT_SECURITY_POLICY_DIRECTIVES__IMG_SRC="'self' data: blob:"
> CONTENT_SECURITY_POLICY_DIRECTIVES__SCRIPT_SRC="'self' 'unsafe-eval' *.mapbox.com"
> CONTENT_SECURITY_POLICY_DIRECTIVES__DEFAULT_SRC="'self' *.mapbox.com"
> ```
Thanks, that solved my issue !
![image](https://user-images.githubusercontent.com/91227615/148204635-209a81f9-0098-4c2a-906b-31def6c56ef9.png)
