### ISSUE TITLE
Creating User - Generating new password, hide it after input lost focus.

### ISSUE THREAD

**Issue by WellingGuzman** [directus/directus#1084]
Don't know if this is how we wanted to happen, but at least if we do, we don't need the blocker to show up.

Any thoughts @benhaynes ?

![screen shot 2015-11-18 at 11 54 10 pm](https://cloud.githubusercontent.com/assets/1531291/11261926/ae57df28-8e4f-11e5-905a-151df0e4e779.png)

**Comment by benhaynes** [comment]
@WellingGuzman 
The user types in their password and then on focus Directus salts/hashes (encrypts) it before saving. The whole thing is blocked (••••••), but I think that's OK.

Do you think the password and hash should be plaintext?

**Comment by WellingGuzman** [comment]
@benhaynes Looking back I didn't explain myself well, so the thing is, when you write your password it's all good and how it works it's all good, but my concern is when is "encrypting" the page set itself as "loading data" (showing the moving square bottom right).

Plus: When you click "Reveal Password" it just reveal the hashed password.

Just feel that that second of "loading" makes it feel slow to me. haha, just wondering if you feel the same on this one.

**Comment by benhaynes** [comment]
@WellingGuzman 
The "loading data" is really fast (for me) so it doesn't bother me. And the reveal password shows that we don't have access to their original/plaintext password. We could add UI options to disable the "reveal" button – or an option to not encrypt passwords (store them in plaintext).

**Comment by WellingGuzman** [comment]
@benhaynes oh, but then it doesn't "reveal" you the password, I was expecting at least while, it's not saved, to get the value in plaintext, maybe I'm wrong but that's what I was expecting to work. because seeing the hash doesn't do much for me. but maybe it's just me. but we can have the option to disable the "reveal" though.

**Comment by benhaynes** [comment]
I see what you mean. If you haven't saved then it makes sense to reveal the password you typed. Let's add a quick UI option for disabling/hiding the reveal button (default = no reveal button).

**Comment by benhaynes** [comment]
Did you hide it or make a UI option to hide it? Either way... this is good.

**Comment by WellingGuzman** [comment]
I just hide it. (Commented out)
