### ISSUE TITLE
Role permission field preset filled item not valid

### ISSUE THREAD

**Issue by krwrang** [directus/directus#10854]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Create collection item no longer accepts M2O field filled by field preset.

We have a setup with a common organization collection and several different content collections that all have a M2O relation to the organization collection. Both author (with app access) and reader (no app access) roles are created for each organization. These roles validate that for each collection permission is only allowed to items that relate to their specific organization. This is done manually with item permission

> Organization -> ID Equals 1
(or whatever the correct ID is)

When adding new items to collections a field preset is used to set the correct organization automatically, so that the user does not have to select from a list of one possible option. The field preset is simply:
`{
    "organization": 1
}`

In Directus versions prior to 9.1.0 this worked perfectly. The correct item is already selected when "Create item" selected and display template properly shows the name of the organization.

In 9.1.0 this was broken so that nothing was automatically selected. Proper item could be selected from list but save wouldn't work due to error during POST. This has been fixed, but a different issue is present in the latest version of 9.4.2.

When creating a new item the field preset correctly selects the proper organization automatically. However when saving the item a validation error of "Value is required" is presented on the M2O field. Raw value for the field is 1.

### To Reproduce

1. Create item collection, for example "organization"
2. Create another item collection, for example "news"
3. In "news" add M2O field to "organization"
4. Add item in "organization"
5. Add author role "organizer"
6. For author role, set "organization" read permission where item id = 1 (or whatever is the id of the item created in step 4.)
7. For author role, set "news" create permission with all field permissions, field validation Organization -> ID Equals 1 AND field preset { "organization": 1}
8. Add user to author role, login with user
9. Attempt to create "news" item
-> "Value is required" validation error visible in organization M2O field -> Item cannot be saved

![image](https://user-images.githubusercontent.com/42867097/148186691-3f5c5f89-52f4-4365-b803-c0d37d2a94af.png)

### What version of Directus are you using?

9.4.2

### What version of Node.js are you using?

16.13.1

### What database are you using?

AWS Aurora MySQL 5.7

### What browser are you using?

Chrome and Firefox

### What operating system are you using?

Fedora

### How are you deploying Directus?

AWS ECS, Fargate

**Comment by azrikahar** [comment]
Note: Seems like the preset is not being staged as edit (refer screenshot in above issue), hence the "Value is required" kicks in even though there is in fact value set already.
