### ISSUE TITLE
Update api/configuration.php root path

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1085]
It seems that we need to change the default root path variable in the api/configuration.php file:

Within the filesystem array:
```
'root' => realpath(BASE_PATH . '/../media'),
```

**Comment by WellingGuzman** [comment]
@benhaynes Oh by default we have the media directory on the root. so it should be this the correct way:
```
'root' => realpath(BASE_PATH . '/media'),
```

What we need to specify is that `BASE_PATH` is the base/root directory of Directus, and it doesn't have trailing slash .

We need to move this to the documentation.

Any thoughts?

**Comment by benhaynes** [comment]
@WellingGuzman 
By default we have the media path in the root of Directus? Oh, I thought it was one directory "above" Directus.

Can we add a quick comment in the code explaining this? Also, if you add a quick note in the Docs I will clean it up.

**Comment by benhaynes** [comment]
Looks good! I cleaned up the comments
