### ISSUE TITLE
Fix filtering using GeoJSON data

### ISSUE THREAD

**Issue by kostopravby** [directus/directus#10869]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

After upgrading from 9.0.1 to 9.4.2 I can't use geometric filter operators like `_intersects`
got error `{"errors":[{"message":"\"_intersects\" has to be a valid GeoJSON object","extensions":{"code":"INVALID_QUERY"}}]}`

### To Reproduce

Create collection with field geometry and type multi polygon. Insert items. Check with the following query:

```
items/some_collection?filter[geo][_intersects]={"type": "Point","coordinates":[31.0,41.0]}
```

### Errors Shown

`{"errors":[{"message":"\"_intersects\" has to be a valid GeoJSON object","extensions":{"code":"INVALID_QUERY"}}]`

### What version of Directus are you using?

9.4.2

### What version of Node.js are you using?

16.13.1

### What database are you using?

PostgreSQL 10 with postgis

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### How are you deploying Directus?

docker

**Comment by rijkvanzanten** [comment]
@Oreilles seems like this is caused by the fact that the JSON value in the filter is used as a string rather than an object, causing the `stringify` validator from `wellknown` to fail here:

https://github.com/directus/directus/blob/8cdb6edfca1c217b02d8bc7965cd20116c30f075/api/src/utils/validate-query.ts#L138-L142

A potential fix would be to always try parsing the filter value as JSON, meaning that nested JSON objects are properly treated as an object rather than a string holding JSON (see linked PR).

**Comment by rijkvanzanten** [comment]
Also ensure that the filtering UI in the app works as expected with the GeoJSON input for the API filter as per https://github.com/directus/directus/issues/12793

**Comment by rijkvanzanten** [comment]
Linear: [ENG-281](https://linear.app/directus/issue/ENG-281/fix-filtering-using-geojson-data)

**Comment by michaeltoohig** [comment]
Is this coming out in a release soon?

**Comment by rijkvanzanten** [comment]
@michaeltoohig this was released in 10.4+ 👍🏻

**Comment by michaeltoohig** [comment]
I'm using 10.7.2 but seeing this issue, could you show me a resource on what a valid request would look like using `_intersects` and `_intersects_bbox`

```
const response = await directus.items('Land').readByQuery({
  limit: 100,
  fields: ['id', 'name', 'center'],
  filter: {
    center: {
      _intersects_bbox: {
        type: "Feature",
        bbox: [-10.0, -10.0, 10.0, 10.0],
      },
    },
  },
});
```
or
```
const response = await directus.items('Land').readByQuery({
  limit: 100,
  fields: ['id', 'name', 'center'],
  filter: {
    center: {
      _intersects_bbox: [-10.0, -10.0, 10.0, 10.0],
    },
  },
});
```
Because neither of these is working for me and I get a response such as
```
{"errors":[{"message":"Invalid query. \"_intersects_bbox\" has to be a valid GeoJSON object.","extensions":{"code":"INVALID_QUERY","reason":"\"_intersects_bbox\" has to be a valid GeoJSON object"}}]}
```

**Comment by michaeltoohig** [comment]
@rijkvanzanten can you provide a working example of a request using this filter?

**Comment by michaeltoohig** [comment]
For anyone wanted to know how to use this feature here is an example. And as https://github.com/directus/directus/discussions/19329 states `_intersects` appears to be the same as `_intersects_bbox`.

```
const response = await directus.items('Land').readByQuery({
  limit: 100,
  fields: ['id', 'name', 'center', 'geometry'],
  filter: {
    center: {
      _intersects: {
        "type": "Feature",
        "geometry": {
          "coordinates": [
            [
              [
                168.2947501099543,
                -17.723682144590242
              ],
              [
                168.2947501099543,
                -17.727328428851507
              ],
              [
                168.29840874403044,
                -17.727328428851507
              ],
              [
                168.29840874403044,
                -17.723682144590242
              ],
              [
                168.2947501099543,
                -17.723682144590242
              ]
            ]
          ],
          "type": "Polygon"
        }
      }
    },
  },
});
```
