### ISSUE TITLE
In SQLite, a "Foreign Key constraint failed" error occurs when adding a relational field to a collection

### ISSUE THREAD

**Issue by rmartin-sc** [directus/directus#10874]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

1. If there is a collection, C1, with a M2O field referencing another collection, C2 (i.e., table C1 has a foreign key referencing table C2)
2. AND the "On delete..." trigger for that relational field is set to "Prevent the deletion", (i.e., table C1's FK has `ON DELETE NO ACTION`)
3. then, if you try to add another relational field to collection C2, a "Foreign Key constraint failed" error occurs (see below)

This issue does NOT appear to occur when...
- the "On delete..." trigger for the M2O field on collection C1 is set to any of the options other than "Prevent the deletion"
- you add a field to collection C2 that is NOT a relational field

### To Reproduce

1. Spin up a new Directus instance on an empty SQLite database
2. Create a new Collection named C2 with the default id field and a text field
2. Create a new Collection named C1 with the default id field and a text field
3. Add a M2O relational field in C1 that references C2
4. Set the 'On delete of C2...' trigger for this new field to "Prevent the deletion"
4. Add some C2 items
5. Add some C1 items and link them to the C2 items
6. Add a M2O relational field in C2 that references C1
7. After saving this field, the error occurs

### Errors Shown

```
{
  "errors": [
    {
      "message": "DROP TABLE \"C2\" - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### What version of Directus are you using?

9.4.2

### What version of Node.js are you using?

16.13.1

### What database are you using?

SQLite 3

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
I believe this is the same issue as https://github.com/directus/directus/issues/10307 and https://github.com/directus/directus/issues/10842. @nickrum could you confirm that to be the case?

(long story short, there was a bug in `knex` that was subsequently fixed. We're waiting for a release in knex to upgrade and resolve the issue in Directus)

**Comment by nickrum** [comment]
Can confirm 👍Knex needs to recreate the table to add a foreign keys constraint.

**Comment by rijkvanzanten** [comment]
We'll leave #10842 as the primary aggregator for these sqlite issues 👍🏻
