### ISSUE TITLE
Drag and Drop images isn't working for Multiple Files UI

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1089]
Choose and manual upload seem to work, but not drag and drop.

**Comment by jel-massih** [comment]
Cant replicate. What browser are you using and still occurring in development branch?

**Comment by benhaynes** [comment]
This is working for me too now – @WellingGuzman is this one that you fixed the other day?

**Comment by WellingGuzman** [comment]
@jel-massih I found out that I've fixed this but I've not push it :-1: 
@benhaynes the issue was when the junction table didn't have `sort` field.

pushing now... :muscle:

**Comment by WellingGuzman** [comment]
Fixed by 40c800fd2675670401dee8c57f2e9284513a58e5

@benhaynes by the way, not, this wasn't the one I fixed the other day.

Closing it.
