### ISSUE TITLE
Color interface has inconsistent ui "sometimes"

### ISSUE THREAD

**Issue by LasseRosenow** [directus/directus#10894]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

A picture is worth a thousand words:

![image](https://user-images.githubusercontent.com/10547444/148440713-5d7e6858-40b8-40f8-bba7-860fadfbb68a.png)

On the left side is the correct interface, but on the right side its looking very weird.

### To Reproduce

I just have a two column layout with two colorpickers with each having opacity flag enabled.

### What version of Directus are you using?

9.4.2

### What version of Node.js are you using?

16

### What database are you using?

MariaDB

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

On a remote Debian server

**Comment by rijkvanzanten** [comment]
Fascinating! Happens with non-alpha color inputs too:

https://user-images.githubusercontent.com/9141017/148447076-e64342da-71b5-46a9-97fa-5cf6c66d5043.mp4
