### ISSUE TITLE
Dashboard orders dates wrong

### ISSUE THREAD

**Issue by Nitwel** [directus/directus#10896]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When grouping the data by week, the dates get displayed / connected in the wrong order.
Could be caused by turning the year + month + week info into a date.

![grafik](https://user-images.githubusercontent.com/22577866/148461625-eda09794-bbdb-4cfc-8291-02d2699055b3.png)

### To Reproduce

Data returned from the api:
```
{
    "data": [
        { "timestamp_year": 2021, "timestamp_month": 10, "timestamp_week": 40, "sum": { "value": 716 } },
        { "timestamp_year": 2021, "timestamp_month": 10, "timestamp_week": 41, "sum": { "value": 3285 } },
        { "timestamp_year": 2021, "timestamp_month": 10, "timestamp_week": 42, "sum": { "value": 3944 } },
        { "timestamp_year": 2021, "timestamp_month": 10, "timestamp_week": 43, "sum": { "value": 8510 } },
        { "timestamp_year": 2021, "timestamp_month": 10, "timestamp_week": 44, "sum": { "value": 1278 } },
        { "timestamp_year": 2021, "timestamp_month": 11, "timestamp_week": 44, "sum": { "value": 1348 } },
        { "timestamp_year": 2021, "timestamp_month": 11, "timestamp_week": 45, "sum": { "value": 2516 } },
        { "timestamp_year": 2021, "timestamp_month": 11, "timestamp_week": 46, "sum": { "value": 8424 } },
        { "timestamp_year": 2021, "timestamp_month": 11, "timestamp_week": 47, "sum": { "value": 7472 } },
        { "timestamp_year": 2021, "timestamp_month": 11, "timestamp_week": 48, "sum": { "value": 1600 } },
        { "timestamp_year": 2021, "timestamp_month": 12, "timestamp_week": 48, "sum": { "value": 862 } },
        { "timestamp_year": 2021, "timestamp_month": 12, "timestamp_week": 49, "sum": { "value": 3778 } },
        { "timestamp_year": 2021, "timestamp_month": 12, "timestamp_week": 50, "sum": { "value": 3906 } },
        { "timestamp_year": 2021, "timestamp_month": 12, "timestamp_week": 51, "sum": { "value": 5448 } },
        { "timestamp_year": 2021, "timestamp_month": 12, "timestamp_week": 52, "sum": { "value": 7165 } },
        { "timestamp_year": 2022, "timestamp_month": 1, "timestamp_week": 0, "sum": { "value": 135 } },
        { "timestamp_year": 2022, "timestamp_month": 1, "timestamp_week": 1, "sum": { "value": 1948 } }
    ]
}

```

Panel settings:
![grafik](https://user-images.githubusercontent.com/22577866/148461824-715af376-fd5f-4192-a520-fced0d0b8b32.png)

Collection:
[metrics.csv](https://github.com/directus/directus/files/7825108/metrics.csv)

### What version of Directus are you using?

Latest

### What version of Node.js are you using?

Latest

### What database are you using?

MariaDB

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment]
Technically this also happens for grouping by days as reported back in #8701, but (for better or for worse) grouping by weeks seems to have made it easier to reproduce. Very likely something to do with groupBy. Let's consolidate this in that same issue 👍
