### ISSUE TITLE
Drawers open behind modals

### ISSUE THREAD

**Issue by dimitrov-adrian** [directus/directus#10892]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Items drawer appears behind the v-modal in upload dialog.

### To Reproduce

Create text field with markdown interface, allow image tool. With the new field add image and pick "Choose from library"

https://user-images.githubusercontent.com/1009639/148432167-c1ba97b2-6f8f-4cd1-98cb-86b6a94b2993.mov

### What version of Directus are you using?

9.4.2

### What version of Node.js are you using?

16

### What database are you using?

mysql5.7

### What browser are you using?

Chrome

### What operating system are you using?

macOS Big sur

### How are you deploying Directus?

locally

**Comment by ijpatricio** [comment]
I came to add this Issue, and noticed is already here. 
Can confirm.
I started using with docker, but will try to install in local, so I can try to solve this.

**Comment by log4shell** [comment]
I can confirm the same issue on my local instance of Directus 9.4.2. As a manual work-around in the browser, you can right-click and "inspect" to file upload dialog and then delete the `<div>` block that holds this dialog:
 
![image](https://user-images.githubusercontent.com/93653909/149167364-c5d25f20-66e1-4843-b52d-cf12d5190e04.png)

After it's removed, you can select files from the file library that was blocked behind the dialog.

**Comment by rijkvanzanten** [comment]
This is caused by my update to the drawer handling here: https://github.com/directus/directus/commit/6e439db6b28ce5608bff05a07b0301a5abf401c1 that wrongly assumes that dialogs should always be above drawers

**Comment by ijpatricio** [comment]
I should have had time to look into it, but time is very tight here.
I'll try my best

**Comment by rijkvanzanten** [comment]
No worries @ijpatricio, I know how that goes.. 👀 

The reason I split up the two "stacks" is that I relied on CSS's `nth-of-type` operator to do the stacked drawer effect. We might be able to revert that split by using a different tag (`div` vs.. `span`? is `<dialog>` supported enough yet?) as `nth-of-type` only checks against used `tag`
