### ISSUE TITLE
Show previous listing item

### ISSUE THREAD

**Issue by RNGR** [directus/directus#109]
When going back to list view (browser back) from an item, the item should be highlighted in the light yellow briefly to show which item you are coming from.

http://try.discourse.org/

**Comment by WellingGuzman** [comment]
@benhaynes we've made something roughly that does this so far, should we keep this open until we optimize it or close it? or didn't it work as expected?

**Comment by benhaynes** [comment]
I'd say this one is done! What we have works well... if there are issues we can open a new ticket.
