### ISSUE TITLE
Incomplete fields when managing relationship details

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1091]
This looks good for many-to-**one** but is missing some fields for many-to-**many**:

* Junction Table
* Key Left
* Key Right

![screen shot 2015-11-22 at 2 35 30 pm](https://cloud.githubusercontent.com/assets/522079/11325839/75563ca4-9126-11e5-821f-7b8b2a89cf1d.png)

**Comment by jel-massih** [comment]
Unable to replicate this? Do you see this in dev branch (Or @WellingGuzman have you already fixed this)?

**Comment by WellingGuzman** [comment]
@jel-massih I haven't fixed this yet.
If I'm correct, the issue (_what's missing_) here, it is that many-to-many doesn't have the option to edit relationship (after it has been created), there's not **junction table**, or **left/right** key field.

If you go to any table with a many-to-many field, and click on the relationship icon, can you see the "Junction Table" field?

**Comment by benhaynes** [comment]
Any ideas on this one? It seems like it would be pretty straightforward to add in these fields again... but let me know @WellingGuzman

**Comment by benhaynes** [comment]
This is looking great – especially the disabled relational options for Single File and O2M. I know it's manually edited still... we can open a ticket for making this dynamic or any adjustments. Thanks @WellingGuzman
