### ISSUE TITLE
Bad contrast in image previews since new directus version

### ISSUE THREAD

**Issue by LasseRosenow** [directus/directus#10917]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I use a lot of white images with transparent backgrounds. In the old directus version the default background for images was a somewhat darker variant of the default directus background i think. But I just updated directus to the most recent version and now the background of images is just white. So I end up with this:

![image](https://user-images.githubusercontent.com/10547444/148624069-ddd515f8-cddd-4a40-b548-7f5f542e55e4.png)

How it was:
![image](https://user-images.githubusercontent.com/10547444/148624236-dec14a20-af7b-4c41-9536-35aa2998da5f.png)

I think the old behaviour looked so good and i don't see why this was changed :(

### To Reproduce

Create a collection and add a image field.
Upload a white image with a transparent background to directus (I am using directus in dark theme)

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

16

### What database are you using?

MariaDB

### What browser are you using?

Chrome, Firefox

### What operating system are you using?

Windows

### How are you deploying Directus?

On a remote Debian server

**Comment by LasseRosenow** [comment]
Side info: 

The Gallery still works as expected. It uses `var(--background-normal)` as background, while the inside collections `var(--background-inverted)` is used.

**Comment by LasseRosenow** [comment]
Also it seems like only single instance collections are affected

**Comment by benhaynes** [comment]
I agree. We can darken this background up, but I'd like to make sure we don't have a grid of **high-contrast** boxes before images/assets load. This slightly darker color should only apply to SVGs, PNGs, and other assets that support alpha and need contrast.

**Comment by LasseRosenow** [comment]
Im not quite sure what you mean. I think the logic is already there its just a small bug that only affects single instance collections it seems like 🤔 

Also Im not sure what you mean with preventing high-contrast boxes? because right now white is a very high contrast. having a background shade would be a much smaller contrast and much less distracting also for normal images with backgrounds.

Or is this some sort of misunderstanding because you are thinking about the light mode in which something darker than white would be used as well which could be disruptive at places where not necessary?

**Comment by LasseRosenow** [comment]
Funny thing. On white mode it uses the background that it is supposed to use on dark mode:

![image](https://user-images.githubusercontent.com/10547444/148629163-f0f641b1-d2f6-43c9-8c8a-8aa575cf5895.png)

**Comment by LasseRosenow** [comment]
Also interesting: colored svgs get the correct backgrounds in light and dark mode:

dark:

![image](https://user-images.githubusercontent.com/10547444/148629482-feda942f-0591-43c8-8c9f-b3d183b59524.png)


light:

![image](https://user-images.githubusercontent.com/10547444/148629500-c258386a-4b90-46e8-bd43-002ae4981d15.png)

**Comment by benhaynes** [comment]
Well that's... interesting! Perhaps this is just a bug then. We'll check it out! 👍

**Comment by LasseRosenow** [comment]
Okay i managed to nail it down a bit more:

I got a bit confused, because I thought I was using svgs, at places where it weren't.

SO:

The issue is with Transparent PNGs. They get the wrong background color. 
Transparent SVGs however work. Thats why the Instagram Logo worked.
