### ISSUE TITLE
one to many relationship drawer get's first item value on all items

### ISSUE THREAD

**Issue by ranaharoon3222** [directus/directus#10929]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When I create an item with one to many relationship. And when i open drawer by clicking a create a new item button. and i create 3 items but when I reopen 2nd item drawer its value is the same 

here is the small video that shows error

https://www.loom.com/share/a8631e9782684ff39a61064eb86a1c07

### To Reproduce

here is video
https://www.loom.com/share/a8631e9782684ff39a61064eb86a1c07

### Errors Shown

no

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

v14.16.1

### What database are you using?

mysql

### What browser are you using?

chrome

### What operating system are you using?

windows 10

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment]
Can confirm #11520 has resolved this issue as well, and it will be released in the next version 👍

## Before

![aupxQzxbIT](https://user-images.githubusercontent.com/42867097/153383110-a87e1312-60c6-4cc9-941b-238963467d0f.gif)

## After

![fqqUljxfv4](https://user-images.githubusercontent.com/42867097/153383090-731a8137-77e2-41b3-b6a6-0db171fa81d9.gif)
