### ISSUE TITLE
Transparent images get scaled up too much in preview

### ISSUE THREAD

**Issue by LasseRosenow** [directus/directus#10925]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When rendering images in previews, directus uses `cover` so that the preview box is always completely filled. This is very good for images that have a background, but for images with a transparent background this is very much unnecessary and usually creates a bad visual:

![image](https://user-images.githubusercontent.com/10547444/148651216-14c9d8a0-ee61-4933-946d-1f337934580a.png)

I think if images with transparent background are rendered with `contain` by default, this would improve the default UI a lot :)

### To Reproduce

Self explanatory 

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

16

### What database are you using?

MariaDB

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

On a remote Debian server

**Comment by LasseRosenow** [comment]
I did not mean it in a way, that the alpha value is the problem. And no it is not the text that I want to see. I just think that in general all images that have alpha values always look better if they are rendered with `contain` instead of `cover`.

The only reason to render something with `cover` is so that it fits the box and there are no weird paddings and stuff, but if an image has alpha values, it does not fill the box no matter if it is scaled up or not so they would look better if they are scaled down instead of scaled up

**Comment by rijkvanzanten** [comment]
I don't think there's a way for us to default that behavior in an unopinionated way 🤔 What @benhaynes said is correct; there's a dedicated toggle to control the cover vs contain that I'd recommend using in this case:

<img width="533" alt="CleanShot 2022-01-10 at 13 33 22@2x" src="https://user-images.githubusercontent.com/9141017/148819930-82cbc622-50bb-49a4-8aa0-9974da27b681.png">

**Comment by LasseRosenow** [comment]
> I do believe that we have options for cover versus contain on the File Library and each Field Interface... so these options are there... just not on an automatic case-by-case basis. Please correct me if I'm wrong!

This is ture, but it only works on a per image field basis. Not for the gallery for example. I could change it for the whole gallery, but then all images with backgrounds would look bad.

This idea of using `cover` for images with full colored backgrounds and `contain` for images with transparent backgrounds is just my approach on how to have better defaults.

My Idea would also be to update the interface so that there would be 3 options:
1. `auto`: images with alpha use `contain` images with full colored backgrounds use `cover`
2.  `cover`: image will be forced to be displayed as `cover`
3.  `contain`: image will be forced to be displayed as `contain`
