### ISSUE TITLE
CONTENT_SECURITY_POLICY_DIRECTIVES__UPGRADE_INSECURE_REQUESTS is undocumented

### ISSUE THREAD

**Issue by thepurpleblob** [directus/directus#10935]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

If you want to access directus using https then it appears to be required to specify

CONTENT_SECURITY_POLICY_DIRECTIVES__UPGRADE_INSECURE_REQUESTS: 'null'

However, this is completely undocumented excepting an obscure bug report. 

Version: 9.4.2

### To Reproduce

Install Directus using standard docker instructions. 

Access over network (http)

Sticks at 'Loading'

### Errors Shown

In console CORS errors about various https://... resources (due to Upgrade-Insecure_Requests: 1 header)

### What version of Directus are you using?

9.4.2

### What version of Node.js are you using?

image: directus/directus:latest (don't know)

### What database are you using?

SQLite

### What browser are you using?

Tested in Chrome and Firefox

### What operating system are you using?

macos

### How are you deploying Directus?

Docker

**Comment by nickrum** [comment]
This has already been reported in #10806 and was fixed in `9.4.3` by turning upgrade-insecure-requests to off by default.

**Comment by thepurpleblob** [comment]
...actually, there's no documentation for CONTENT_SECURITY_POLICY. It just refers you to some other library. Unless I'm particularly stupid, I can't see how you would infer setting 'CONTENT_SECURITY_POLICY_DIRECTIVES__UPGRADE_INSECURE_REQUESTS' from the information provided. 

Sorry to be annoying, but as a new user I think it's sometimes helpful to point out things that are opaque to new users.

**Comment by nickrum** [comment]
@thepurpleblob no need to apologize! This helps a lot in finding any loose ends in our docs.

The info on how to do nesting when the config variable expects an object can be found [here](https://docs.directus.io/configuration/config-options/#type-casting-and-nesting). Not sure how we can clarify this. Maybe an additional _Type_ column would help?

**Comment by rijkvanzanten** [comment]
We offer loads of options through the same strategy, where the env vars are automatically converted into an object and passed to a third party library. We wouldn't want to document every possible value, as that would result in hundreds and hundreds of flags, most of which you'd never need to use. It also means we won't be able to properly maintain that list, as these third party libraries update over time 🤔 

In this particular case, everything is passed straight to Helmet, so the best reference we have is to point you straight to Helmet's documentation itself

**Comment by thepurpleblob** [comment]
My point was that I couldn't see where the double underscore form came from. However, you're right, it is documented elsewhere. I wonder, in these cases, that another mention might help. Nobody ever reads the instructions properly.

**Comment by rijkvanzanten** [comment]
> My point was that I couldn't see where the double underscore form came from

Fair, though that isn't required for the env var necessarily. A JSON object of what you want to pass to Helmet would work as well (eg `CONTENT_SECURITY_POLICY={"directives":{"upgradeInsecureRequests":null}}`) 🙂 

More than happy to hear any and all thoughts on how to make this more obvious, as you're absolutely right in saying that _Nobody ever reads the instructions properly._ 😄
