### ISSUE TITLE
Deleting on the item detail should be instant

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1093]
Currently you have to fill in all required fields... if you're deleting something then you wouldn't care what's in each field... it should be a button, not a radio select. Ben to provide a design.

**Comment by benhaynes** [comment]
Actually, because the statuses can be adjusted by the admin, it would be difficult to know how to handle this.

I think what we should do it make a `enforce_validation` flag for each status. That way, you can set whether each status should enforce validation.

active: `enforce_validation` = *true*
draft: `enforce_validation` = *false*
delete: `enforce_validation` = *false*

What do you think @WellingGuzman ?

**Comment by benhaynes** [comment]
This would also solve the following Feature Request:
http://feathub.com/directus/directus/+15

**Comment by benhaynes** [comment]
In terms of UI:

* User clicks on `delete` for an item
* It would show a Directus notification confirmation (`Are you sure you would like to permanently delete this item? Yes, Cancel`
* The item is deleted and the user is returned to the listing page.

**Comment by WellingGuzman** [comment]
It actually delete the item if is a delete value.

Maybe we should add the new options `enforce_validation` into 6.4?
