### ISSUE TITLE
Embeds aren't storing all values

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1095]
`date_uploaded`
`title`
`size` (might be working?) should be the number of seconds in the video

**Comment by benhaynes** [comment]
Thanks @jel-massih !!! I just pulled and added an API key but am getting a *Server Error* (Vimeo upload is working). Any ideas?:

https://www.youtube.com/watch?v=uxpDa-c-4Mc

![screen shot 2015-11-29 at 5 46 47 pm](https://cloud.githubusercontent.com/assets/522079/11460809/23a86804-96c2-11e5-8276-a535fbc80230.png)

**Comment by WellingGuzman** [comment]
@benhaynes I tried and it worked, pulling the title, description, tag and size (time) as well.

maybe that's what you get for using a drake video haha. jk.

**Comment by benhaynes** [comment]
Haha, Hotline Bling is (unfortunately) stuck in my head...

Hmm, maybe it's my local setup or API key? Let me try testing again

**Comment by benhaynes** [comment]
Welp – it helps if you enable the YouTube API v3 for that key!

Looks good and works great!! The only thing (which I found out the hard way) is that if you have a bad API key it just says "Server error". Is it possible to give a "Error: Bad YouTube API Key"?

**Comment by jel-massih** [comment]
Yeah, in PR 1099

**Comment by WellingGuzman** [comment]
@benhaynes did you test @jel-massih PR?

**Comment by jel-massih** [comment]
Sorry, PR = Pull Request

**Comment by benhaynes** [comment]
Yes, just tested now and this is working perfectly. The only questions I have (I can open in a new ticket if the answers here warrant it) are about a few unused fields:

* `url` versus `embed_id` columns. It seems that `embed_id` is not being used.
* `user` doesn't seem to be getting filled in (mine says "0" for all)
* `charset` isn't being filled in for embeds, is that correct?
* what does `needs_index` do?

**Comment by WellingGuzman** [comment]
@jel-massih I got you. :fist: 

> what does needs_index do?
Good question. Nothing! :no_good: 

if @jel-massih you are not going to work on this one, I can take it now.

**Comment by WellingGuzman** [comment]
@benhaynes 
> charset isn't being filled in for embeds, is that correct?

`type` is the one used to specify is a embedded file.

> url versus embed_id columns. It seems that embed_id is not being used.

`embed_id` is not being used, url store the id of the embedded url, the UIs are expecting a url, and to make things easy, the id it's kept on the url instead of the embed_id.

We should talk about this table structure, will be better to just drop `embed_id` or make things clear and use the `embed_id` instead of the url?

**Comment by WellingGuzman** [comment]
Adding user_id done here: d1d801445b9b112d459332633db171aff5ac7354
