### ISSUE TITLE
It is not possible to delete a collection after another collection with Translations has been added

### ISSUE THREAD

**Issue by Pachat** [directus/directus#10988]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

After clicking on Delete Collection, nothing happens. The Collection is still there, even after refreshing the page.

### To Reproduce

- New installation
- Create a collection (I added one input field)
- Click on Delete Collection: it is normally deleted
- Create a collection (add a Translation field)
- Click on Delete Collection: it does not delete
- Create a second collection (without a Translation field)
- Click on Delete Collection: it does not delete either

You may try to delete any collection in this database: [data.zip](https://github.com/directus/directus/files/7853767/data.zip)  with Username=Password=admin-directus-local@localhost.com

### Errors Shown

No erross

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

14.17.1

### What database are you using?

SQLite version 3.37.0

### What browser are you using?

Firefox

### What operating system are you using?

Windows_NT 10.0.19043

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
Wondering if this is the same cause / solution as https://github.com/directus/directus/issues/10842

**Comment by azrikahar** [comment]
I can't seem to reproduce this issue both with and without the provided SQLite database on the latest version, so I'll proceed to close this issue. If these exact same steps can still reproduce this issue on your end with `v9.8.0`, please do let us know 👍

**Comment by Pachat** [comment]
Hope to be able to test with v9.8.0 on my app in development as soon as  #12529 / #10842 are closed. These issues are not in the pipe of [v9-next](https://github.com/directus/directus/milestone/104)
