### ISSUE TITLE
Error on pressing Enter

### ISSUE THREAD

**Issue by richjenks** [directus/directus#1100]
Press Enter anywhere

1. Error "This table already exists!" shows twice
1. Current form isn't submitted (but escape does cancel)
1. If there are no entries on current page, additional error "Uncaught TypeError: Cannot read property 'privileges' of undefined File: http://scotchbox/assets/js/directus.min.js?bust=ojne2cd1mn3doendcti69q13d5 Line:15"

**Comment by benhaynes** [comment]
Hey @richjenks – is this happening on a specific page?

**Comment by WellingGuzman** [comment]
@richjenks I think there's a ticket open for this issue, but I found right now that's happening on `Settings > Tables`.

@benhaynes if you go to `Settings > Tables & Fields` and click on any table, and hit enter, it will throw the "This table already exists!".

**Comment by WellingGuzman** [comment]
Plus: it's happening on listing page, go to any listing page and hit enter.

**Comment by benhaynes** [comment]
Maybe this is only in the `build` branch? I am not seeing this on any of the mentioned pages...

**Comment by richjenks** [comment]
Update: It's not a fixed message, rather it shows every error that has been shown since the page was reloaded:

1. Control case: Load Directus and press Enter > nothing happens
1. Settings > Tables > New
1. Leave name empty and press Enter > shows error "Empty Table Name"
1. When returned to Settings page, press Enter again to see "Empty Table Name"
1. Repeat to show multiple errors on pressing Enter

Note this also works with alert errors, e.g. when trying to add a Bookmark with no name.

**Comment by richjenks** [comment]
I've also had errors shown a few steps after submitting via pressing Enter. For example, on a fresh install create a group with no permissions and then create a table:

![image](https://cloud.githubusercontent.com/assets/1795615/11501553/fdbfb82e-982c-11e5-928a-cc9893346abb.png)

I'd hypothesise that Directus is saving things in the database when save/submit buttons are clicked but not when Enter is pressed and this is probably a separate issue from the one above.

PS Sorry to be hounding you guys with issues, I just see a lot of value in Directus and there are several places I'd really like to be able to use it. Hopefully I'm more help than hindrance :)

**Comment by WellingGuzman** [comment]
@richjenks don't have to be sorry, this is great what you are doing, this helps us and we appreciate it, Thanks.

I'll look into it.

**Comment by WellingGuzman** [comment]
@richjenks Regarding the second issue, it seems you are using PHP 5.6.x, and `$HTTP_RAW_POST_DATA` is deprecated, but the weird part is not that is deprecated is that we are not using it, and it's a php bug [bug#66763](https://bugs.php.net/bug.php?id=66763)

To solve this add/use/update this on your php.ini
```
always_populate_raw_post_data = -1
```

Let me know if that works for you.

**Comment by benhaynes** [comment]
OK – assuming this is a fix for the issue. I have added this into the FAQ section of the NEW docs.
