### ISSUE TITLE
Problem creating collections with system fields

### ISSUE THREAD

**Issue by Alv-sys** [directus/directus#11013]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hi there,
I am having an issue when creating collections. It seems to be a kind of similar issue to #10876, but the errors I receive are different. In order to make it a bit clearer and help to share more information about it, I am creating this new report.

When creating collections, I receive errors if all system fields are selected, but still, the collection is created as a database only, plus a folder with the same name. When I try with no system collections included, I receive an authorization error (I am connected as root)

I am using my local environment,  with the database, tables and fields using `utf8mb4_general_ci` as suggested in issue #10876, but still always happens.

https://user-images.githubusercontent.com/47535920/149264422-f8dbe173-8601-453f-a248-f73f57a10399.mp4

### To Reproduce

1.-Install Directus
2.-Try to create a collection including all system fields.
3.-Try to create a collection without system fields.

### Errors Shown

```
{
  "errors": [
    {
      "message": "Collection \"Blogstest\" doesn't exist",
      "extensions": {
        "code": "INVALID_PAYLOAD"
      }
    }
  ]
}
```

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

16.13.2

### What database are you using?

MySQL Community server 8.0.27

### What browser are you using?

Tested on Chrome and Firefox

### What operating system are you using?

Windows 11

### How are you deploying Directus?

locally

**Comment by Oreilles** [comment]
This is the same issue as https://github.com/directus/directus/issues/10876, I'm closing this one as a duplicate but please add any information you think relevant as a comment to the first one. 👍
