### ISSUE TITLE
Save dropdown (e.g. "Save and Stay") is in serif

### ISSUE THREAD

**Issue by richjenks** [directus/directus#1101]

**Comment by benhaynes** [comment]
This one seems odd – the "Save and Stay" dropdown should be a system input... so we don't actually style it. Could you sent a screenshot and browser/OS details?

Thanks!

**Comment by richjenks** [comment]
![image](https://cloud.githubusercontent.com/assets/1795615/11500671/6fa8626c-9826-11e5-8a25-eef3fd644a61.png)

Looks like it's `inherit`ing the font "Directus" and set to green from `.header1 .primary-row .tools .select-and-circle label.icon-triangle-down`.

**Comment by WellingGuzman** [comment]
@richjenks what Operating System are you using?

**Comment by richjenks** [comment]
Sorry for delayed reply, it's Chrome 47.0.2526.106 m on Windows 10

**Comment by benhaynes** [comment]
**[Migrated to FeatHub](http://feathub.com/directus/directus/+23)**

Please use the [Directus FeatHub](http://feathub.com/directus/directus) to vote for features or make new request. Accepted feature requests will be added to GitHub Issues.
