### ISSUE TITLE
CACHE_ENABLED="false" is not respected when CACHE_STORE="redis"

### ISSUE THREAD

**Issue by rc1** [directus/directus#11029]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I was following the [docker installation guide](https://docs.directus.io/getting-started/installation/docker/) by using the docker compose example.

However, I didn't want to use Redis. I removed the redis container and set the `CACHE_ENABLED: 'false'`.

The guide states:

```
      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'
 ```

But I changes this to 

```
      CACHE_ENABLED: 'false' # changes here
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'
 ```
 
On running the compose file, errors about the cache were presented.

### To Reproduce

Copy the docker compose example from [here](https://docs.directus.io/getting-started/installation/docker/).

Comment out these lines:

```
  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus
```
    
Set this environment variable to 'false':

```
CACHE_ENABLED: 'true'
```

### Errors Shown

```
[cache] Error: getaddrinfo ENOTFOUND cache
```

### What version of Directus are you using?

directus/directus:latest (9.4.3)

### What version of Node.js are you using?

Same as official the docker image

### What database are you using?

Postgres

### What browser are you using?

n/a

### What operating system are you using?

n/a

### How are you deploying Directus?

docker

**Comment by rijkvanzanten** [comment]
Can you try it with 

```
 CACHE_ENABLED: false
```

instead of

```
 CACHE_ENABLED: 'false'
```

?

**Comment by rijkvanzanten** [comment]
I believe this is a configuration problem, rather than a bug. The system cache will also rely on the configured cache driver, so make sure to set `CACHE_SCHEMA=false`
`CACHE_PERMISSIONS=false` as well as `CACHE_ENABLED=false` if you want to disable all caches 👍🏻

**Comment by rc1** [comment]
It would be helpful if the guide used 

    =true

Instead of 

    ='true'

So prevent people getting tripped up like myself.

Minor nit on a great system, thanks.

**Comment by rijkvanzanten** [comment]
Those two should be parsed the same in directus' env var casting 👍🏻 I believe my other comment is the source of your confusion 🙂

**Comment by Rar9** [comment]
The redis cache should be updated when something gets added /deleted

**Comment by azrikahar** [comment]
> The redis cache should be updated when something gets added /deleted

This behavior can be enabled via the `CACHE_AUTO_PURGE` environment variable 🙂 Link to docs: https://docs.directus.io/self-hosted/config-options.html#cache

Let's do keep comments on topic and opt to create a new discussion/question when possible.
