### ISSUE TITLE
Cannot add M2O field with string id after update 9.2.2 -> 9.4.3: [INVALID_PAYLOAD]: field X doesn't exist in collection Y. 

### ISSUE THREAD

**Issue by mslonina** [directus/directus#11028]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

After migration from 9.2.2 to 9.4.3 I cannot add M2O relationships. I did multiple M2O relations in 9.2.2 and worked perfectly. I've updated Directus by changing the version in the docker image. The log reports that migrations were run.

The env is set from docker-compose, following docs.

### To Reproduce

1) Create a "country" collection with id as string, set to be unique
2) Create a "region" collection in which I create a reference to a single country - using M2O relation
3) Error occur - field is actually created but without reference collection set

If I try to delete such a field later on, it reappears within the interface with orange triangle - I have to remove it manually from db.

### Errors Shown

The following error occurs:

```json
{
  "errors": [
    {
      "message": "Field \"country\" doesn't exist in collection \"region\"",
      "extensions": {
        "code": "INVALID_PAYLOAD"
      }
    }
  ]
}
```

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

From provided docker image

### What database are you using?

Postgis 13

### What browser are you using?

Safari, Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by mslonina** [comment]
This is how charsets looks like:  

```
                                  List of databases
       Name       |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges   
------------------+----------+----------+------------+------------+-----------------------
 directus         | directus | UTF8     | en_US.utf8 | en_US.utf8 | 
 postgres         | directus | UTF8     | en_US.utf8 | en_US.utf8 | 
 template0        | directus | UTF8     | en_US.utf8 | en_US.utf8 | =c/directus          +
                  |          |          |            |            | directus=CTc/directus
 template1        | directus | UTF8     | en_US.utf8 | en_US.utf8 | =c/directus          +
                  |          |          |            |            | directus=CTc/directus
 template_postgis | directus | UTF8     | en_US.utf8 | en_US.utf8 | 
```

**Comment by Oreilles** [comment]
When you create the M2O field, are you seeing any error ? Is the field actually created (do you see it in the app ?)
What does the `schema` and `relationship` section of the field details page for collection region looks like ?
If you could send us a video capture of the whole process, and the server logs if you have access to them, it would help us greatly understanding what's going on here.

**Comment by mslonina** [comment]
Hi, this might have been an issue with Redis cache (#11029). Generally:

- I did a full backup of the db and restored it
- I couldn't migrate down using docker image, I struggled a bit, but I was able to restore the db to 9.4.3
- Directus queried few extra fields that weren't present in the backup (such as country and region) - I started to think where this information is cached and recalled #11029 
- Once I stopped redis and commented out its settings in docker-compose, adding M2O fields with string id started to work again

Could be that after 9.2.2->9.4.3 migration some cache wasn't invalidated and the problem occured (I don't have screenshots, this is what I recall):

1) Creating collection with id as manually entered string worked
2) M2O with this collection didn't worked - but the field was actually created in the db, but without reference
3) Directus UI said the field didn't have properly configured references

**Comment by rijkvanzanten** [comment]
I'll close this for now then, as it sounds like the problem was resolved. We can reopen / open a new issue if it turns out that there's something (besides #11029) consistently going wrong in the redis handling that should be resolved 🙂
