### ISSUE TITLE
Sqlite3 DB migration 9.0.0-rc.92 to 9.4.3 fails

### ISSUE THREAD

**Issue by mooori** [directus/directus#11032]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

`npx directus database migrate:latest` fails with the error shown below.

**Notes**
- After the migration failed, I connected to the db using `sqlite3` and ran `drop table directus_users`. It dropped the table without errors. Therefore I don't know where to start digging into this.
- Migration from `rc.92` to `rc.94` works fine. Migration to `rc.95` fails.
- There are issues related to the db migration, however I couldn't find a solution to the problem described here.

(This [comment](https://github.com/directus/directus/issues/9655#issuecomment-967130716) mentions the issue and they say they fixed it by modifying the migration. In `9.4.3` the migration has been adjusted accordingly, still it fails.)

### To Reproduce

`npx directus database migrate:latest` for the migration from `rc.92` to `9.4.3` (or to `rc.95`)

### Errors Shown

```
18:55:13 ✨ Running migrations...
18:55:13 ✨ Applying Add Insights...
18:55:13 ✨ Applying Add Auth Provider...
18:55:13 🚨 DROP TABLE "directus_users" - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed 
Error: DROP TABLE "directus_users" - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed
```

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

12.22.8

### What database are you using?

SQLite 3.37.2

### What browser are you using?

NA

### What operating system are you using?

archlinux

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
@Oreilles Fairly sure it's the same underlying cause as https://github.com/directus/directus/issues/10842 which was already fixed in Knex. We're just waiting for a knex release to finally resolve the issue in directus as well 👍🏻

**Comment by mooori** [comment]
The migration is not urgent, so for now seems like the most reasonable thing to do is wait for the knex fix to land. Thank you for the feedback!

**Comment by mooori** [comment]
@roelvan thanks for the heads-up!

**Comment by stloc** [comment]
So how to solve ?

**Comment by mooori** [comment]
@stloc we have to wait for a new directus release which upgrades the knex dependency to v1. Then the db migration should work.

**Comment by rijkvanzanten** [comment]
@roelvan @stloc @mooori Knex v1 relies on a different SQLite package (`@vscode/sqlite` instead of `node-sqlite`), which doesn't ship with pre-built binaries. This could cause installation problems if people don't have the required build tools in their local path (like python, gcc, and whatever else sqlite might need). We're doing some more research into this before upgrading and causing a 💥 (cc @nickrum)
