### ISSUE TITLE
Filter on M2M on Directus Users ↔ Directus Roles does not work properly

### ISSUE THREAD

**Issue by Pachat** [directus/directus#11043]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Users may have multiple roles: an M2M field `other_roles` is therefore added to Directus Users in relation with Directus Roles
![M2M](https://user-images.githubusercontent.com/13746133/149495828-08eb7bc4-dd44-4e0f-b3a8-c86bedcce510.png)

Here is the full list a `Member` can see when the Directus Users filter is set to All.
![Full list](https://user-images.githubusercontent.com/13746133/149494625-52c46800-244e-4306-a942-7e7997a21334.png)
The Manager who is also a Member has 2 roles: the Role `Manager Role` and an other_roles `Member Role`.

What I'd like to build is a filter that allows a `Member` to see any other user that has a Role `Member Role` **or** an other_roles `Member Role` i.e. with the present data:
- Member who has a `Member Role` in `Role`
- Member 2 who has a `Member Role` in `Role`
- Manager who's role is  `Manager Role` but has  a `Member Role` in `other_roles`

First step: showing the users that have a Role `Member Role` 
Below, under the filter (in admin) you see the users list (seen by the member)
![Members](https://user-images.githubusercontent.com/13746133/149496517-5a1ea9b2-4ee9-41ec-a720-d05e9607be39.png)

Second step: we expect the users that have a Role `Member Role` or an other_roles `Member Role`, 
that is Member, Member 2 and Manager
Below, under the filter (in admin) you see the users list (seen by the member)
![Member](https://user-images.githubusercontent.com/13746133/149497040-b27181af-45dc-4d54-b874-2933aa9914b8.png)
But here, we have only the user itself.

I suspect that Directus cannot resolve properly the M2M here, and therefore, goes to the default minimal filter: the user itself.

### To Reproduce

You may use this Database: [data.2.zip](https://github.com/directus/directus/files/7869545/data.2.zip)

1. Connect as member@localhost.com / member@localhost.com : see the full list of users
2. Connect as admin@localhost.com / admin@localhost.com : set the filter for `Member Role` as described in the First step 
3. Connect as member@localhost.com / member@localhost.com : see the list of the 2 Users with `Member Role`
4. Connect as admin@localhost.com / admin@localhost.com : set the filter for `Member Role` as described in the Second step 
5. Connect as member@localhost.com / member@localhost.com : you will see only the user itself in the list

### Errors Shown

The filter reduces the Users list to the user itself instead of enlarging it to
- Member
- Member 2
- Manager

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

14.17.1

### What database are you using?

SQLite version 3.37.0

### What browser are you using?

Firefox

### What operating system are you using?

Windows_NT 10.0.19043

### How are you deploying Directus?

locally

**Comment by Oreilles** [comment]
On your second image, your filter isn't configured properly: when using a `and/or` block, its children will be identified by a increased left margin. 
Here's how it should look like:
<img width="428" alt="Capture d’écran 2022-01-14 à 11 37 35" src="https://user-images.githubusercontent.com/33065839/149502445-fb9c08c3-d998-4a39-aaae-b4afa6e2d3ee.png">

**Comment by Pachat** [comment]
@Oreilles  Awesome! Directus is really fantastic! Thanks.

BTW: I'm not sure the documentation shows a configuration of "Any of the following" with the block feature.

**Comment by benhaynes** [comment]
A note and good screenshot in the docs would help! CC @erondpowell
