### ISSUE TITLE
request entity too large

### ISSUE THREAD

**Issue by shi-rudo** [directus/directus#11049]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When updating multiple translations of one article I got sometimes the message "**request entity too large**". 

**Article** Aggregate/
├─ English translation payload (> 6000 words)
├─ Spanish translation payload (> 6000 words)
├─ German translation payload (> 6000 words)

### To Reproduce

none specific way, does not happen all the time

### Errors Shown

`{
  "message": "request entity too large",
  "extensions": {
    "code": "INVALID_PAYLOAD"
  }
}`

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

16.13.1

### What database are you using?

postgres 14.1

### What browser are you using?

safari 15.2

### What operating system are you using?

macOS 12.1

### How are you deploying Directus?

docker

**Comment by Oreilles** [comment]
The query result might be exceeding the server maximum request/response size, which is configurable with `MAX_PAYLOAD_SIZE` and default to 100kb. You might want to try and increase it, to find a value that fits your usage.

**Comment by shi-rudo** [comment]
> The query result might be exceeding the server maximum request/response size, which is configurable with `MAX_PAYLOAD_SIZE` and default to 100kb. You might want to try and increase it, to find a value that fits your usage.

thanks for letting me know :-)
added MAX_PAYLOAD_SIZE to docker-compose file.
