### ISSUE TITLE
Organize the API

### ISSUE THREAD

**Issue by WellingGuzman** [directus/directus#1105]
Right now all our API code resides in on single file, making it a large file with a lots of code, which makes it harder to look at it, and look for a specific endpoint.

Slim now supports class as callable, which we can do something like this:

``` php
$app->get('/users', 'UserController:indexAction');
```

Instead of:

``` php
$app->get('/users', function() {
   // code here 
});
```

we can also take the advantage of grouping to group endpoints:

``` php
// Example from slim documentation
<?php
$app = new \Slim\Slim();

// API group
$app->group('/api', function () use ($app) {

    // Library group
    $app->group('/library', function () use ($app) {

        // Get book with ID
        $app->get('/books/:id', function ($id) {

        });

        // Update book with ID
        $app->put('/books/:id', function ($id) {

        });

        // Delete book with ID
        $app->delete('/books/:id', function ($id) {

        });

    });

});
```

We can expand the discussing into this, but this is the idea what we can accomplish.

**Comment by benhaynes** [comment]
The API will now be a huge focus of our attention – this is amazing and I can't wait to see it reorganized. We should also look at any endpoints we're missing, and how best to structure params and other options.

**Comment by benhaynes** [comment]
[Reminder to format "friendly" error responses...](https://github.com/directus/directus/issues/1226#issuecomment-237451877)

**Comment by WellingGuzman** [comment]
We could reduce the code in the `api.php` file, but the API is not organized into a separate files.

I'm going to call it organized by the terms we agreed on this ticket.

The friendly responses are going to be handled here https://github.com/directus/directus/issues/1226#issuecomment-237451877
