### ISSUE TITLE
"Required" isn't checked on _update_

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#11057]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When setting a field to _Required_ (either on field settings or through conditions), the required state is only checked on _Create_ (not on _Update_).

This is caused by the fact that the original implementation of Required stemmed from "A value has to be submitted", which isn't checked on update as the value may or may not already exist. While it can be defended from a technical perspective, it's not a good UX.

To resolve this, we have to make sure we fetch the currently saved item on update, and check if all the required fields have been set[^1]. 

This does raise another question: _When does something match the required state?_ An obvious one is `null` vs a value, however, you may or may not expect `''`, `0`, or `false` to fail the "Required" state as well.

I personally believe we should only check for null vs not-null, and have Validation settings handle everything else. The text interfaces already have options to choose whether or not to send `''` as `null`, so that should take care of (what i think) are the most common cases.

[^1]: Rather than reading the whole item, we could only fetch the "required" fields where value = null to save some bandwidth

### To Reproduce

1. Add a collection (`articles`) with a field (`title`)
2. Make `title` required
3. Add a new `articles` item, set `title` to something
4. Update the previously created item, remove the value from `title` (either by backspacing, or using "Clear Value" on the field dropdown)

Observe how it still lets you save the item, even though the required value is missing

### Errors Shown

n/a

### What version of Directus are you using?

9.4.2

### What version of Node.js are you using?

16.13.1

### What database are you using?

Postgres 13

### What browser are you using?

Safari 15.2

### What operating system are you using?

macOS Monterrey

### How are you deploying Directus?

Locally

**Comment by acuenca-facephi** [comment]
There is the same error when create/update required translations fields.
**To reproduce:** 

1. Add a collection (articles) with a translations field
2. Make translations required
3. Add a new field for articles_translations (title)
4. Make title required and not nullable
5. Add a new articles item, before to save, write something in title field (any language) and then delete or clear the field.
6. Click save.

A new article is created without the required (and not nullable) title field. 

There is also other problem with this, when you want to set the field required in multiple languages at the same time, the data model conditions doesn't works as expected, attached example:
![Captura de pantalla 2022-02-24 a las 10 44 15](https://user-images.githubusercontent.com/57618470/155499804-59a7298f-4406-43ff-8109-cf26b12f3d78.png)

I am running **Directus 9.4.3** in docker container with a **MacOs Monterey with Apple Silicon architecture**.

**Comment by TheFarmer1** [comment]
I think this stems from a deeper problem that required fields aren't validated at all in the backend.  Using the REST API, you can both insert new records and update records with a blank or missing required field.

**Comment by rijkvanzanten** [comment]
> I think this stems from a deeper problem that required fields aren't validated at all in the backend. Using the REST API, you can both insert new records and update records with a blank or missing required field.

That's not correct. Validation is checked against the submitted payload on creation 👍🏻

**Comment by TheFarmer1** [comment]
> > I think this stems from a deeper problem that required fields aren't validated at all in the backend. Using the REST API, you can both insert new records and update records with a blank or missing required field.
> 
> That's not correct. Validation is checked against the submitted payload on creation 👍🏻

Oh, I see now, checking the "Required" field does nothing as far as using the REST API.  You have to uncheck the "Nullable" field in order to make the field required.  Then it does restrict both create and update.

**Comment by ConnorSimply** [comment]
@rijkvanzanten From my testing, this is now enforced on updating. When you follow your reproduction steps, it now requires it.

**Comment by rijkvanzanten** [comment]
@ConnorSimply How did you test it? IIRC we didn't change this yet 🤔

**Comment by ConnorSimply** [comment]
@rijkvanzanten Unless I am understanding this issue wrong, it does require the field to not be null on save regardless if it is a create or edit. I tried looking through the PR's to find if there was a change somewhere but couldn't find anything quickly. I can confirm the below behavior is the same on 9.16.1 and 9.18.1.

**Set Up**
- Create a String Field called Name
  - Allow NULL Value = true
  - Required to be set on creation = true
- Create a String Field called Description
  - Allow NULL Value = true
  - Required to be set on creation = false

**Testing**
- Attempt to create item with NULL Name
  - Validation Error: `Name: Value can't be null`
- Create item with "test" Name, Save, Edit item, Clear Name input, Attempt to Save 
  - Validation Error: `Name: Value can't be null`
- Manually create db row with blank Name column, add input for Description but not Name (leave name blank)
  - Validation Error: `Name: Value can't be null`

**Comment by rijkvanzanten** [comment]
Linear: [ENG-279](https://linear.app/directus/issue/ENG-279/required-isnt-checked-on-update)

**Comment by ConnorSimply** [comment]
@paescuj Can you confirm that this is no longer an issue and can be closed? Followed repro steps and was not able to reproduce this still.

**Comment by rijkvanzanten** [comment]
No longer an issue
