### ISSUE TITLE
Email configuration

### ISSUE THREAD

**Issue by WellingGuzman** [directus/directus#1106]
This is a mistake and right now all email are being sent by `noreply@getdirectus.com` we should be able to configure different options.

**Comment by benhaynes** [comment]
@WellingGuzman – Did we just fix this for Hosted?

**Comment by WellingGuzman** [comment]
I forgot we had this ticket, yes, this was solved by: https://github.com/directus/directus/commit/b8176078ae8d77f7bebf38c79c7c02445143635e

**Comment by benhaynes** [comment]
Great!
