### ISSUE TITLE
New Item has changes even without any modifications

### ISSUE THREAD

**Issue by joselcvarela** [directus/directus#11088]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When I am trying to leave the New Item view without any changes the confirmation modal appears.
Also, when I click `Discard Changes` it shows the confirmation modal again and this process repeats and I am not able to quit this view.

### To Reproduce

I am not sure why this started happened now, but this is easy reproducible:

1. Create a collection
2. Open the New Item view on this collection
3. Try to leave. Confirm leave modal must appear.

### Errors Shown

See this screenshot
<img width="888" alt="Screenshot 2022-01-17 at 06 46 25" src="https://user-images.githubusercontent.com/14039341/149721351-a5e6e429-ff0d-4897-b039-d1b4e33b8642.png">

Those are the edits, but I didn't make any change 🤔
The `nextval` thing comes from the default value from PostgreSQL

### What version of Directus are you using?

9.4.3 (e258f3d28 - main)

### What version of Node.js are you using?

v16.13.0

### What database are you using?

postgis/postgis:13-3.1-alpine

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
I noticed you have a `status` field in there too. What other fields exist in this collection?

**Comment by joselcvarela** [comment]
I just created a collection without any fields, only ID (automatically created), and have the same issue 😕

**Comment by felipe-santos** [comment]
Hi friends, 
for me, fixed:
https://github.com/directus/directus/blob/b3f43ff1a29e2e7da58f480de002ecdc8ce1de5c/app/src/modules/content/routes/item.vue#L299

change to:
return Object.keys(edits.value).length > 0 || hasEdits.value;

changes "defaults.value" to "edits.value"

**Comment by joselcvarela** [comment]
> Hi friends, for me, fixed:
> 
> https://github.com/directus/directus/blob/b3f43ff1a29e2e7da58f480de002ecdc8ce1de5c/app/src/modules/content/routes/item.vue#L299
> 
> change to: return Object.keys(edits.value).length > 0 || hasEdits.value;
> 
> changes "defaults.value" to "edits.value"

`Object.keys(edits.value).length > 0` and `hasEdits.value` are the same, so not necessary.
The thing is: default value comes from database vendor, in this case Postgresql.

Maybe we need to differentiate default values created by users and other default values, and only do the check for default values created by user: `Object.keys(defaultsByUser.value).length > 0` 🤔

**Comment by rijkvanzanten** [comment]
> Maybe we need to differentiate default values created by users and other default values

There's no way to differentiate between the two. They're stored and returned in the same location by the database 👍🏻

**Comment by rijkvanzanten** [comment]
Yeah! There's also an active discussion on the knex-schema-inspector around a way to split up generated default values (like nextval()) and "regular" static ones (https://github.com/knex/knex-schema-inspector/pull/73) cc @Oreilles
