### ISSUE TITLE
installation stopped 

### ISSUE THREAD

**Issue by crashtainer** [directus/directus#1108]
hi ,
while installing directus, i filled all required data, when i press install, it refresh the same page without any error, all configuration are fine except the following:

Composer Dependencies Installed (../api/composer.json) 	No 
Imagick PHP Extension For TIFF, PSD, and PDF thumbnails 	No

 PS.directus is installed locally using xampp 3.2.1

thank you in advance

**Comment by jel-massih** [comment]
Composer Dependencies are required to install Directus. Try running
`curl -s https://getcomposer.org/installer | php`
`php composer.phar install`

within the /api directory

**Comment by WellingGuzman** [comment]
@crashtainer you can also use the build branch instead which already has all the dependencies. https://github.com/directus/directus/tree/build

You can download the zip [here](https://github.com/directus/directus/archive/build.zip)

**Comment by benhaynes** [comment]
It seems that this is caused by not installing the composer dependencies – installing these (as @jel-massih mentioned), or using the build branch (as @WellingGuzman mentioned) will resolve this. 

If you have further issues, reopen this or submit a new ticket.

**Comment by cantstopthi** [comment]
I have the same error. I  tried the build zip and i tried to install composer via the provided exe, still not working.

**Comment by WellingGuzman** [comment]
@cantstopthi can you open a new ticket with more details? such as the Operative System, and what version of Directus you are using and what are the errors? So I can understand your problem better.

Thanks
