### ISSUE TITLE
Content - NumberList functionality is not working.

### ISSUE THREAD

**Issue by Jigar123modi** [directus/directus#11092]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

content number list functionality is not working.

![image](https://user-images.githubusercontent.com/57913162/149745623-d8bf8377-8a2a-4559-91f0-0a6dc9954e73.png)

![image](https://user-images.githubusercontent.com/57913162/149745763-b3374422-d090-4506-9750-e3bfec8ee9a4.png)

### To Reproduce

just add the list number and test it.

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

14.18.1

### What database are you using?

Postgres

### What browser are you using?

crome,firebox,safari

### What operating system are you using?

linux,windows,apple

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Hi, would you be able to verify what is the raw JSON payload you are getting from the API? Are you also using a CSS framework such as Tailwind CSS by any chance? Tailwind CSS for example will [remove styling from lists in their Preflight](https://tailwindcss.com/docs/preflight#lists-are-unstyled). 

I've tested this on my end and it seems like it is working:

- Directus

  ![chrome_51ObXKbfuT](https://user-images.githubusercontent.com/42867097/149749512-06d264dd-e4b9-4844-ae27-3c01b4d897b1.png)

- Payload from `/items/test`

  Note the `<ol>` and `<li>` tags here

  ```js
  {
    "data": {
      "id": 1,
      "body": "<p>This is a paragraph.</p>\n<ol>\n<li>Ordered list item 1</li>\n<li>Ordered list item 
  2</li>\n<li>Ordered list item 3</li>\n</ol>"
    }
  }
  ```

I'll close this for now as I believe it's a CSS issue on your frontend here, but if you can confirm that tags such as `<ol>` and `<li>` are not present at all when you retrieve that field via the API, we'll reopen it and investigate further 👍
