### ISSUE TITLE
Add First/Last name to root user on install

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1109]
Since `first_name` and `last_name` are required, but empty for the first user, we should add in a default value when installing:

First Name: *Admin*
Last Name: *User*

What do you think @WellingGuzman ?

**Comment by WellingGuzman** [comment]
@benhaynes This is perfect, I think the same, and it turns kind of annoying at first, when it keep asking for an empty fields that was empty at first place. :+1: :100:
