### ISSUE TITLE
New text for emails

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1110]
## New Directus Instance
**Subject:** `Your New Directus Instance: My Project`

**Body:**
Your new Instance of Directus is ready to go! You can access it using the following credentials:

http://my-directus-install.com/admin/

**Main Configuration**
Project Name: My Project
Admin Email: ben@rngr.org
Admin Password: ***
Installed Version: 6.03

**Database Configuration**
Host Name: localhost
Username: root
Password	: ***
Database Name: my_project

Love,
The Directus Team

**Comment by benhaynes** [comment]
Directus Core Framework should use the same HTML templates as Hosted.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/2e3245b0edad13c006ce80d0b6ffee92d6e67196
