### ISSUE TITLE
Disable login form when AUTH_DISABLE_DEFAULT is enabled

### ISSUE THREAD

**Issue by diegoleme** [directus/directus#11114]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When the AUTH_DISABLE_DEFAULT setting is enabled, the login form should not appear.

### To Reproduce

Enable AUTH_DISABLE_DEFAULT config.

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

16

### What database are you using?

Postgres 10

### What browser are you using?

Chrome

### What operating system are you using?

Linux (Manjaro)

### How are you deploying Directus?

Docker

**Comment by Udai1931** [comment]
Hey @diegoleme, Can I try to fix this?

**Comment by joselcvarela** [comment]
@Udai1931 he already opened a PR for it https://github.com/directus/directus/pull/11116 👍

**Comment by azrikahar** [comment]
Resolved by #11116
