### ISSUE TITLE
Look into Installers

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1112]
Users can install it globally and do this `directus-installer create project-name`, and it downloads directus and copy it in the current directory

**Comment by WellingGuzman** [comment]
Let's look into [Symfony Installer](https://github.com/symfony/symfony-installer) as well.

```
$ symfony new my_project 2.8.1
```

**Comment by benhaynes** [comment]
**[Migrated to FeatHub](http://feathub.com/directus/directus/+44)**

Please use the [Directus FeatHub](http://feathub.com/directus/directus) to vote for features or make new request. Accepted feature requests will be added to GitHub Issues.
