### ISSUE TITLE
v table wiki documentation  show-select="multiple" 

### ISSUE THREAD

**Issue by hermesalvesbr** [directus/directus#11135]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The documentation about v-table: https://github.com/directus/directus/wiki/v-table

The documentation reference needs to add the "multiple" options in show-select, because today show only true and false, but   show-select="multiple" works with select all. 

### To Reproduce

 <v-table
        :items="items"
        item-key="id"
        v-model:headers="headers"
        v-model="selection"
        show-resize
        must-sort
        @click:row="onRowClick()"
        @item-selected="checkDisable()"
        @select="checkUnselect()"
        fixed-header
        show-select="multiple"
      >
        <template #header.columnOne="{ header }">
          <v-checkbox @click="toggleAll" />
          {{ header.text }}
        </template>
      </v-table>

### What version of Directus are you using?

9.4.3.

### What version of Node.js are you using?

v16.13.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by joselcvarela** [comment]
Thank you @hermesalvesbr
Just updated it 👍
