### ISSUE TITLE
400 Error on /auth/refresh endpoint 

### ISSUE THREAD

**Issue by Jason-CKY** [directus/directus#11146]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I'm trying to deploy directus with HA. The app is deployed on kubernetes with 2 replicas connecting to an external postgres database. I've set keycloak SSO to login for users.

With 1 replica of directus app, users are able to login via keycloak SSO without any issues. Setting the number of replicas to 2 causes the SSO to fail sometimes with error code 400. This issue is intermittent as users were able to login with keycloak after repeated tries. 

It is able to authenticate the user on keycloak, but the browser did not save any refresh_token in the cookie during times where it fails to login via keycloak.

### To Reproduce

2 replicas of directus with a load-balancer at the front, connected to external postgres database and keycloak integration.

### Errors Shown

request completed POST 400 /auth/refresh 17ms

### What version of Directus are you using?

9.0.0-rc.91

### What version of Node.js are you using?

-

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by joselcvarela** [comment]
Hey
Thank you for taking your time to open this issue.
Unfortunately, we cannot support patch fixes for every release.
My advice is try to running on latest release - 9.4.3

In the meantime I am going to close the issue, but feel free to reach us in order to reopen if the same behaviour occurs on the latest release.

**Comment by esonesson** [comment]
@Jason-CKY Did you solve this? We're having the same issue on 10.7.2.
