### ISSUE TITLE
Relationship M2M do not display the items assigned

### ISSUE THREAD

**Issue by alejandroTecDam** [directus/directus#11153]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a list of cancellations related Many to one with orders.
The orders have relationship M2M with the list of cancellations.
But when I create a cancellation and assign the order associated, it not shown in the order listing.
I can select manually the cancellation and it displays in the list. But not automatically when I create a cancellation item.

![Screenshot 2022-01-19 at 13 31 51](https://user-images.githubusercontent.com/86365078/150129994-be7c70bc-469d-483a-81d3-80324574de5c.png)
![Screenshot 2022-01-19 at 13 35 39](https://user-images.githubusercontent.com/86365078/150131590-321700fb-c761-44c2-a311-158fca428604.png)
![Screenshot 2022-01-19 at 13 37 23](https://user-images.githubusercontent.com/86365078/150132158-667c6d1f-278e-4e7c-8cc2-d62f23a1b535.png)

### To Reproduce

First I created the cancellation table and all worked properly, but I needed remove the table because I needed add the date_created param. Since then, the relationship doesn't works.

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

14.18.3

### What database are you using?

PostgreSQL 12.9

### What browser are you using?

Firefox and Chrome

### What operating system are you using?

macOs

### How are you deploying Directus?

Digital Ocean setup

**Comment by joselcvarela** [comment]
Can you provide a short video showing the behaviour?
I am not understanding what you intend and what is the issue 🤔

**Comment by alejandroTecDam** [comment]
Thanks for your answer joselcvarela
When I create cancellations, I assign a drop (order)
![Screenshot 2022-01-19 at 17 11 48](https://user-images.githubusercontent.com/86365078/150170218-abf3049b-dd2d-448d-9a6e-3fd2d440bf44.png)

But in this drop the list looks empty when it have a relationship M2M and must display the cancellations.
![Screenshot 2022-01-19 at 17 13 19](https://user-images.githubusercontent.com/86365078/150170410-b014febf-d357-4db9-8f21-c2c8aa584c1f.png)

If I edit to add an existing cancellation, I can add manually the cancellation
![Screenshot 2022-01-19 at 17 14 10](https://user-images.githubusercontent.com/86365078/150170561-a95f2631-649d-4e39-93ab-5441aafe8e7c.png)

**Comment by alejandroTecDam** [comment]
Add with some of context:

My structure is the following. We have two type of roles, the normal users and the managers. Users can create orders. When those orders are created, they have no manager assigned. Managers can assign themselves to the orders, to start doing whatever is ordered.
In some cases, the initial manager will deliver the order as expected(changing a status within the orders for user visibility) and sometimes, they will not be able to deliver the order.

We want to have a list of “cancellations” within an order, which basically it’s a relation between the order, the manager and a table that contains what we call “Reason/Explanation”. The idea is that we can track why the manager decided not to go further and how many times has this happened for a specific order.

The main issue is that for some reason, the relation within the order is not visible. We can see it under the cancellations table, but within the order, the relation is not triggered.
We basically create a cancellation, where we choose a manager and an order.

**Comment by joselcvarela** [comment]
Odd, can you check the `Raw Value` on the "Cancellations List" field and post it here?

**Comment by alejandroTecDam** [comment]
Hi, here is the capture, thank
![Screenshot 2022-01-24 at 08 11 01](https://user-images.githubusercontent.com/86365078/150737669-a7b7647b-d414-4500-bc81-6e8cd0e00add.png)
s

**Comment by joselcvarela** [comment]
Check here how to get the Raw Value of the field:

https://user-images.githubusercontent.com/14039341/150820366-26b8b7c1-85e8-4f7b-bdff-dd045592a845.mp4

**Comment by alejandroTecDam** [comment]
Hi joselcvarela!
Look the problem, when I try to assign a cancellation item to a drop, this doesn't display

https://user-images.githubusercontent.com/86365078/150824399-f40d5ad5-852f-4cc8-b956-4f68feb542df.mp4

**Comment by alejandroTecDam** [comment]
Here is the schema (I cannot upload yaml files): https://we.tl/t-hIHUuDx8tC

**Comment by rijkvanzanten** [comment]
Reuploading so it doesn't disappear after a week:

[snapshot.yaml.zip](https://github.com/directus/directus/files/7935579/snapshot.yaml.zip)

**Comment by log4shell** [comment]
@alejandroTecDam - I had a similar problem once with my M2M-relationships, the issue was that I had created the relationship independently from both sides so they used different joining tables depending on which side you added the relationship from. The trick was to only create the M2M-relationship from one side and tick the box to automatically create the corresponding field in the other collection like shown in this screenshot:

![image](https://user-images.githubusercontent.com/93653909/151200424-88b52920-77fa-4ed2-be29-a47b2fdccf5a.png)

I don't know if this is the same issue you're facing but my guess is that there's 2 different relationships that are not tied together in your model.

**Comment by jaycammarano** [comment]
I'm trying to apply this schema and it says

20:40:39 🚨 Failed to create collection "About_arborist"
20:40:39 🚨 Invalid foreign key in field "group". 

I don't know if I'm doing something wrong though.

**Comment by alejandroTecDam** [comment]
@log4shell Thank a lot, your solution has solved my problem.
Close the issue.
