### ISSUE TITLE
Cleanup directus_bookmarks

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1115]
Could we remove `directus_bookmarks.icon_class` and any references to it?

Are we using the `directus_bookmarks.active` field? If not, can we remove it?

Are we using the `directus_bookmarks.section` field? If not, can we remove it?

Should we add a `directus_bookmarks.preference_id` field? It seems like it's currently matching the bookmark preference based on the `directus_preferences.title` field... does that seem correct?

Do we need to store `Activity`, `Files`, `Messages`, and `Users` here? Aren't we saving the navigation here: `directus_groups.nav_override` and `directus_groups.show_messages` etc? Can we remove all of these so Bookmarks is only for new/custom bookmarks?

**Comment by WellingGuzman** [comment]
> Could we remove directus_bookmarks.icon_class and any references to it?

Aren't we using `icon_class` to let the user customize with any icon they desired? aren't we going to bring back the icons?

> Are we using the directus_bookmarks.active field? If not, can we remove it?

Not in used (_Or it has always seems like it, never found anything related to this field_), let's removed.

> Are we using the directus_bookmarks.section field? If not, can we remove it?

This is the category on where the bookmark, is going to be displayed under, **other** are system item such as Users and files, **search** are bookmarks and tables, are well, tables, although, we are going to remove "Activity, Files, Messages and Users" from here. I think we can remove this as all this entries are going to be bookmarks.

> Should we add a directus_bookmarks.preference_id field? It seems like it's currently matching the bookmark preference based on the directus_preferences.title field... does that seem correct?

Okay this one can be done this way, it seems more easy to handle, but at the end with will need the title to check if wether or not an entry with this name exists so it wont be duplicated. (or it can be with the magic of icon next to it who knows). **NOTE** make title field field unique.

**Comment by benhaynes** [comment]
>Could we remove directus_bookmarks.icon_class and any references to it?
>>Aren't we using icon_class to let the user customize with any icon they desired? aren't we going to bring back the icons?

The problem with the icons is that they take up a lot of width in the nav... and the tables/bookmarks are already cut-off. Also, it's unclear if we would add an icon for all first level nav items (Files, Users... *and* also each table).

>Are we using the directus_bookmarks.active field? If not, can we remove it?
>>Not in used (Or it has always seems like it, never found anything related to this field), let's removed.

Great!! Maybe one last search though ;)

>Are we using the directus_bookmarks.section field? If not, can we remove it?
>>This is the category on where the bookmark, is going to be displayed under, other are system item such as Users and files, search are bookmarks and tables, are well, tables, although, we are going to remove "Activity, Files, Messages and Users" from here. I think we can remove this as all this entries are going to be bookmarks.

Yeah, the table says "directus_bookmarks"... I think it'd be good to remove the system ones and have it only be for bookmarks.

>Should we add a directus_bookmarks.preference_id field? It seems like it's currently matching the bookmark preference based on the directus_preferences.title field... does that seem correct?
>>Okay this one can be done this way, it seems more easy to handle, but at the end with will need the title to check if wether or not an entry with this name exists so it wont be duplicated. (or it can be with the magic of icon next to it who knows). NOTE make title field field unique.

If the title is unique doesn't that mean that if I add a bookmark that's the same name as one *you* added... it would fail/override? Bookmarks are per user (**but we should have an option to make them per group/global**) so they should only be unique to that user... not the whole table.

**Comment by WellingGuzman** [comment]
> The problem with the icons is that they take up a lot of width in the nav... and the tables/bookmarks are already cut-off. Also, it's unclear if we would add an icon for all first level nav items (Files, Users... and also each table).

It's true, I also think what you said about taking up the space, and I'm talking about all first level item.

> Great!! Maybe one last search though ;)

Just to make everything sure.

> Yeah, the table says "directus_bookmarks"... I think it'd be good to remove the system ones and have it only be for bookmarks.

This is a good thing to do, we also need to change bookmarks to referencing the sidebar nav, everything is not a bookmarks, that's what makes confusing, what is bookmarks, and what's not, when table list is stored in bookmarks (sidebar).

> If the title is unique doesn't that mean that if I add a bookmark that's the same name as one you added... it would fail/override? Bookmarks are per user (but we should have an option to make them per group/global) so they should only be unique to that user... not the whole table.

I need to make it unique per user then, but that's going to be the quickest way to fix this. How about implementing the 3 options? and see if it works (_Check whether or not is easy to implement_) Otherwise we move it to far later:

- User Bookmarks
- Group Bookmarks
- Global Bookmarks

**Comment by benhaynes** [comment]
Another option for Bookmarks being assigned to individual users:

Each record is either assigned to a specific user (store `id`) or is global (`NULL`) for the `user` column.

Would this be easier than trying to do all three of these?
* User Bookmarks
* Group Bookmarks
* Global Bookmarks

**Comment by WellingGuzman** [comment]
We have removed all references of `active` and `icon_class` from `directus_bookmarks` table.

We didn't force deletion of these columns, only new install will install without it.

**Comment by WellingGuzman** [comment]
> Another option for Bookmarks being assigned to individual users:
> 
> Each record is either assigned to a specific user (store id) or is global (NULL) for the user column.
> 
> Would this be easier than trying to do all three of these?
> 
> User Bookmarks
> Group Bookmarks
> Global Bookmarks

This will be a new feature.

Closed by https://github.com/directus/directus/commit/63be46defebe95a2f51be426be9f0cd15521561c

Feathub http://feathub.com/directus/directus/+117
