### ISSUE TITLE
Field for M2O. O2M, M2M Display Template does not scroll right

### ISSUE THREAD

**Issue by Dumpstar56** [directus/directus#11157]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When adding fields to the display template of M2O, O2M, or M2M relations, the cursor to add fields or characters does not scroll right. Once the display template field is full, I can still add fields, but I cannot see or edit them to the right.

### To Reproduce

Create M2O, O2M, or M2M relation and add many fields to the display template. Try to scroll right
![Display Template](https://user-images.githubusercontent.com/94397183/150151017-35c9fed3-0bdf-4565-b6e5-a1088f8ea37b.png)
.

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

v14.18.1

### What database are you using?

Postgres 10.14

### What browser are you using?

Firefox

### What operating system are you using?

Windows 10

### How are you deploying Directus?

AWS EC2, pm2 for app management, nginx reverse proxy.

**Comment by joselcvarela** [comment]
In fact you can click between the fields (white spaces) and with the cursor go to very right of the field.
Although, I believe whenever you add a new field it should scroll to the end.
Thoughts @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
This works like any other regular input with text overflowing:

https://user-images.githubusercontent.com/9141017/150189148-8c417986-ff1b-4e50-8da4-d17b1d357a43.mp4

I believe this is working as expected, always happy to discuss any improvements in a new Discussion though 🙂

**Comment by joselcvarela** [comment]
The thing is if you add more fields it stays on the left.
I think we could put the cursor at the end, every time we add a new field.

This is more like an improvement than a bug, sorry for the confusion 😕

**Comment by benhaynes** [comment]
I agree, @joselcvarela — let's track this as a new ticket/Discussion...
