### ISSUE TITLE
Fix directus_groups.restrict_to_ip_whitelist

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1116]
Since we removed the `directus_ip_whitelist` table, we still need a way to limit IP addresses. My thinking is that we would use the existing field as a CSV of IPs to limit the user group to. If it's NULL, then there's no limitation.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/6cb5614f7538159b98fdff5edfb69208d0b3c2d7 and https://github.com/directus/directus/commit/826fb2b335daebe0f03f7b3cd976ad39dcff8c47
