### ISSUE TITLE
Unable to display an assets in an interface extension

### ISSUE THREAD

**Issue by Djiit** [directus/directus#11168]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hey team, I'm not able to find any documentation on using assets in an **interface extension**.
I tried to : 
- use the SDK directly, but it's a noop.
- Look at 5+ extensions (thanks github tags!) but none was displaying other objects' assets.
- try to allow Everyone to access all the files and folder of Directus: WORKED! But, ahem, who wants this in prod?
- Ask on Discord a couple time, message was just ignored

Thanks for your help! I'm happy to open a PR to improve the extension sdk doc afterward.

Cheers

### To Reproduce

Load an assets, say in a img tag, after you fetched it from the API using `useApi()` for instance. it fails because you're not allowed to fetch it unless "Everyone" as View access on your Files/Folder.

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

14

### What database are you using?

sqlite3

### What browser are you using?

Firefox and Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
Right now, you'll have to add the current user's access token to the URL, like `<img src="example/assets/123-456?access_token=abc.def.ghi">`. Once https://github.com/directus/directus/pull/10592 is merged, there will be a `<v-image>` component that can be used to abstract this away 🙂

**Comment by Djiit** [comment]
Thanks. How can I access the current user from the sdk or extension sdk ?

**Comment by Djiit** [comment]
i'm able to track down this to this commit: https://github.com/directus/directus/commit/bb8112993ed218eded1a6ced4607676e195202ce

**Comment by rijkvanzanten** [comment]
@Djiit You should be able to pull in the stores using `useStores` from the extensions-sdk, that includes a userStore with the current user details. The axios instance that you get from useApi holds the auth token in it's header configuration, so you can use something like:

```js
function getToken(): string | null {
	return api.defaults.headers.common['Authorization']?.split(' ')[1] || null;
}

function addTokenToURL(url: string, token?: string): string {
	const accessToken = token || getToken();
	if (!accessToken) return url;

	return addQueryToPath(url, { access_token: accessToken });
}

function addQueryToPath(path: string, query: Record<string, string>): string {
	const queryParams = new URLSearchParams(path.split('?')[1] || '');

	for (const [key, value] of Object.entries(query)) {
		queryParams.set(key, value);
	}

	return path.split('?')[0] + '?' + queryParams;
}
```

as util functions to easily add the token to any given url 👍🏻
