### ISSUE TITLE
A float field is shown as a string field

### ISSUE THREAD

**Issue by Gio1995** [directus/directus#11185]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Using the API to populate the tables I realized that sending a string value to a float field Directus accepts it without returning an error. 

### To Reproduce

- Create a collection with a float field
- Send a json object with a string into the field in question to "/items/:collection"

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

16.13.1

### What database are you using?

SQLite

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
That's working as expected. We simply pass the value on to the database driver. If that accepts the value as the type for the column, it'll insert as expected 👍🏻 

Feel free to open [a new feature request Discussion](https://github.com/directus/directus/discussions/new) if you think this should/could be improved upon 🙂
