### ISSUE TITLE
Hard to see "Nothing to see here"

### ISSUE THREAD

**Issue by WellingGuzman** [directus/directus#1118]
@benhaynes Is it me or this text "Nothing to see here" is hard to differentiate from the background?

![screen shot 2016-01-03 at 9 59 54 pm](https://cloud.githubusercontent.com/assets/1531291/12082325/4ffc32bc-b267-11e5-8714-926a942a5d5e.png)

**Comment by benhaynes** [comment]
Darkened!

**Comment by WellingGuzman** [comment]
@benhaynes Thanks :+1:
