### ISSUE TITLE
Default values on revisions

### ISSUE THREAD

**Issue by DavidPLamas** [directus/directus#11182]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a collection named `cookies` which contains a radio button field `state` with a default value of `raw`.
If you create an item using the UI and use the default value shown to you by the UI, it looks fine. The item is created with it's default value and if you later try to get the item details you see that it contains its default value. On the database side, the corresponding table column is also assigned the correct value.

But I found what I think might be a bug on the revisions table. So, if you try to get the revision for that resource, you can see that the field `state` and it's corresponding value is not available on the first revision of that particular resource. It only appears on the second to last revisions. 

Is this is actually a problem or is it intended working feature? If it is intended, is there any way to work around this ?

### To Reproduce

* Start a fresh installation of directus using a postgres database
* Import the schema attached bellow (npx directus schema apply `...`)
* Create a new item for the `cookies` collection: do not change the `state` field, let it use the default value
* Use Chrome DevTools or any other tool to check the result of the call for the /revisions endpoint: you will see that the `state` field is not available. 

<details>
    <summary>Click to expand snapshot</summary>

```
version: 1
directus: 9.4.3
collections:
  - collection: Cookies
    meta:
      collection: Cookies
      icon: null
      note: null
      display_template: null
      hidden: false
      singleton: false
      translations: null
      archive_field: null
      archive_app_filter: true
      archive_value: null
      unarchive_value: null
      sort_field: null
      accountability: all
      color: null
      item_duplication_fields: null
      sort: null
      group: null
      collapse: open
    schema:
      name: Cookies
      schema: public
      comment: null
fields:
  - collection: Cookies
    field: id
    type: integer
    schema:
      name: id
      table: Cookies
      data_type: integer
      default_value: nextval('"Cookies_id_seq"'::regclass)
      generation_expression: null
      max_length: null
      numeric_precision: 32
      numeric_scale: 0
      is_generated: false
      is_nullable: false
      is_unique: true
      is_primary_key: true
      has_auto_increment: true
      comment: null
      schema: public
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: Cookies
      field: id
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: true
      hidden: true
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: Cookies
    field: state
    type: string
    schema:
      name: state
      table: Cookies
      data_type: character varying
      default_value: raw
      generation_expression: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_generated: false
      is_nullable: true
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      comment: null
      schema: public
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: Cookies
      field: state
      special: null
      interface: select-radio
      options:
        choices:
          - text: Raw
            value: raw
          - text: Baked
            value: baked
          - text: Overcooked
            value: overcooked
        color: '#00C897'
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: Cookies
    field: name
    type: string
    schema:
      name: name
      table: Cookies
      data_type: character varying
      default_value: null
      generation_expression: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_generated: false
      is_nullable: true
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      comment: null
      schema: public
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: Cookies
      field: name
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
relations: []

```
</details>

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

v16.13.0

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu 20.04.3 LTS

### How are you deploying Directus?

Running locally

**Comment by joselcvarela** [comment]
This does not seems to be a bug for me.
If you didn't change the value, why it should store the diff? Think like git, it only saves the changes you made.
Although, I am not 100% sure if I am correct, what do you think @rijkvanzanten ?

**Comment by DavidPLamas** [comment]
@joselcvarela @rijkvanzanten are you sure this is how a revision should be handled? 
I might not have been clear enough, but I'm not referring to the `delta` field of the `revisions` table. I'm referring to the `data` field. By looking at the database on my local instance, I can clearly see that `delta` is, in fact, storing the diff but `data` looks like it is storing the snapshot of the item at that current time. Otherwise, how would you explain the fact that the second revision contains the radio field even thought it wasn't changed (it is not on the `delta` field)?

**Comment by joselcvarela** [comment]
This only happens on item creation, because default values are populated by database.
On subsequent updates, the value should be there since it was already populated by database.

**Comment by eduardoPinto12** [comment]
Hi, I'm having this exact same problem, and on V8 it had the default values on the `data` field as well, not the `delta` one if I remember correctly, because as you said it shouldn't be on `delta` but I think it should be on `data` so that when creating we can have access to it, and when updating use `delta`, just my two cents :sweat_smile:
