### ISSUE TITLE
Add boilerplate SQL dropdown to installation

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1119]
We should add a dropdown on the installation page that pulls from a repo of SQL files (and JSON for meta data). Each SQL file represents a starter-schema (boilerplate) for different types of projects. Each would have to be thoroughly tested since we can't roll-back Table Creation.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/9094275250c5d69f428e270c5f41d2ca19a87c68
