### ISSUE TITLE
Server Error When Trying To Upload Images

### ISSUE THREAD

**Issue by BraydenGirard** [directus/directus#1120]
Hello, I am getting the following error when trying to upload images.

![screen shot 2016-01-11 at 12 05 13 pm](https://cloud.githubusercontent.com/assets/3247657/12240729/180aaf36-b85d-11e5-9945-f5b330b60a25.png)

**Comment by WellingGuzman** [comment]
@BraydenGirard Thanks for letting us know, I fixed the issue, tomorrow I'm going to merge it with master/build branch tomorrow.

**Comment by BraydenGirard** [comment]
Thank you for the quick fix.
