### ISSUE TITLE
Sign Out/Settings button are transparents

### ISSUE THREAD

**Issue by WellingGuzman** [directus/directus#1122]
@benhaynes I opened the devtools and notice the Sign Out and settings button are transparent and you can see the text on the sidebar underneath.

![screen shot 2016-01-17 at 11 25 17 pm](https://cloud.githubusercontent.com/assets/1531291/12382559/a216b832-bd71-11e5-89ac-3fd5daebeabc.png)

**Comment by benhaynes** [comment]
All set!

**Comment by WellingGuzman** [comment]
@benhaynes I found out the avatar is transparent on hover so, don't know if this should be result or is it the same problem.

![screen shot 2016-01-21 at 10 08 03 am](https://cloud.githubusercontent.com/assets/1531291/12482612/fe7f1314-c026-11e5-8463-82e4be11364a.png)

**Comment by benhaynes** [comment]
Yeah, this was part of the fix, thanks for checking though!

![screen shot 2016-01-21 at 9 31 26 am](https://cloud.githubusercontent.com/assets/522079/12483243/d385a34e-c021-11e5-9edd-88b2b07f80c7.png)

**Comment by WellingGuzman** [comment]
Perfect, didn't know why it was not working for me. :+1:
