### ISSUE TITLE
directus.min.css missing ?

### ISSUE THREAD

**Issue by neyric** [directus/directus#1123]
Hi, 

I've installed Directus using the following guide : https://github.com/directus/directus/wiki/1.-Installation-&-Configuration

Installation worked fine (except many undocumented steps, which I might try to document later), but a file is missing in : https://github.com/directus/directus/tree/build/assets/css

/assets/css/directus.min.css?bust=1bq92ispnkkte7o4adnsskfqv4

Any idea ?

**Comment by WellingGuzman** [comment]
hey @neyric, that should be a problem with the gulp build task, I'd take a look.

And we would be glad if you step in and document what's missing we will appreciate.

Thanks.

**Comment by WellingGuzman** [comment]
I've fixed the problem you get pull the recent version or use the build branch.

Thanks for letting us know.

If you bump into any problem let us know.

**Comment by neyric** [comment]
It works, thanks !
