### ISSUE TITLE
Making relation field readonly failes

### ISSUE THREAD

**Issue by terion-name** [directus/directus#11242]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Making relation field readonly immediately after creation failes

### To Reproduce

1. Create a new data model
2. Add a relational field (Many-to-one)
3. After this edit it and set it to readonly

### Errors Shown

```
{
  "errors": [
    {
      "message": "alter table `wayforpay_payments` modify `order` int null - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'order' and referenced column 'id' in foreign key constraint 'wayforpay_payments_order_foreign' are incompatible.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

v16.12.0

### What database are you using?

mysql

### What browser are you using?

brave

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by jaycammarano** [comment]
I haven't been able to reproduce this with a many to one or a many to many.
 
I want to make sure I'm reading your schema correctly.
`wayforpay_payments` and `order` are tables?
and the column for the many to one is also called `order`?

**Comment by rijkvanzanten** [comment]
@jaycammarano I'm fairly sure this is a very similar underlying cause as https://github.com/directus/directus/issues/10564. Long story short: MySQL has a lot of different variations of charset/collation available, which causes these sorts of issues as one of the options there doesn't align with all of the others. https://github.com/directus/directus/pull/11069 should resolve this

**Comment by terion-name** [comment]
@jaycammarano @rijkvanzanten FYI: it seems to be a heisenbug, cause I've deleted that field, created another one with different name and with that worked...

However, this can be the problem: relational field in subj was named `order` - maybe there somewhere is not enough quotes and this as a reserved word breaks query
