### ISSUE TITLE
user_created read by form if disabled too

### ISSUE THREAD

**Issue by massimoliani** [directus/directus#11243]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When loading an item in the content tab the system look for the user data, I think due to the user_created field present in the item.
But the user_created is disabled in the collection setup.
Consider the collection can have item created by a user with higher privilege that declare the item public to be seen by other users.
Here when the system look for the user_created data there is a permission error.

### To Reproduce

Have two user, one admin and one with less privilege.
Make a collection with user_created and data_created automatic fields.
Make a collection having a field "public" and in the role permission allow lower permission user to browse item with public field on.
In this way lower permission user can see items created as public by admin.
Now open with lower permission user the item and you'll have a permission error due to the system looking for user_created data.
user_created is an hidden field in the collection setup.

Could be possible to avoid reading releational field if disabled?

Now the solution is to remove user_created from browse field of low permission user role.

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

16.0.0

### What database are you using?

MySql 8

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
> user_created is an hidden field in the collection setup.

Try removing read-access for this particular field for your lesser privileged user 👍🏻 If the role isn't allowed to read the field, it won't even show up in the app, which in turn also means it won't try to read any relational data

**Comment by massimoliani** [comment]
I did in this way.
But if I need the user_created id without knowing any additional data about the user?
For example the user_created can be used by the backend using admin privilege.

Sorry was not correct bug potential, but potential improvement.

**Comment by rijkvanzanten** [comment]
Ahh gotcha. Yeah that makes sense. The real improvement here would be to have the Many to One dropdown interface gracefully handle the loading error, and then still show the primary key of the thing it tried loading. So you end up with something like:

```
⚠️ Couldn't load preview for item (5)
```

**Comment by massimoliani** [comment]
Important is to avoid a permission exception to the user, especially when the field is hidden and no need any additional data.
Right now a permission exception is issued, you click ok and continue to work, but the final call you?

**Comment by rijkvanzanten** [comment]
Yeah, that's what I meant above 🙂 So instead of throwing that forbidden error with the dialog, it just shows a message inline in the dropdown interface

**Comment by massimoliani** [comment]
Perfect.

Thank you.
