### ISSUE TITLE
Translations in a relation disappears when editing after a save

### ISSUE THREAD

**Issue by TheAzack9** [directus/directus#11259]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When editing translations in e.g a M2M, M2O or O2M relation it seems that in some cases the current saved data will be removed from the other languages. 

Video showing the bug in action

https://user-images.githubusercontent.com/2140448/150926715-ab9b41ab-744b-4539-bbae-084b225d822a.mp4

 

### To Reproduce

1. Create a collection named page_section with a translation field
2. go to the translation field and add e.g a text area field
3. create another collection page and add a M2M relation with the page_section field.
4. Go to the page collection and create an item.
5. Add at least one page_section and fill some text for both languages
6. Save the item and re-open
7. Go back to the same item and open the page_section. Edit one of the languages..
8. Click the checkmark to close the page_section
9. Open the page_section again and the other language will be missing

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

v14.18.2

### What database are you using?

SQLite and MySQL

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Locally and Docker

**Comment by jaycammarano** [comment]
@Nitwel Was this solved in #9421 🙏

**Comment by Nitwel** [comment]
That PR was a fix for the translations display not the interface.

**Comment by jaycammarano** [comment]
Thanks!
