### ISSUE TITLE
latency indicator in v9.5 UI cannot be seen

### ISSUE THREAD

**Issue by altezza04** [directus/directus#11260]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

It seem the latency indicator pop up is too high and cannot be see

<img width="298" alt="Screenshot 2022-01-25 at 6 16 58 PM" src="https://user-images.githubusercontent.com/59946405/150958547-c3d76771-4424-42b4-8787-9fee618dc608.png">

### To Reproduce

Just mouse over the latency indicator

### What version of Directus are you using?

9.5

### What version of Node.js are you using?

16

### What database are you using?

PQ

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

PaaS

**Comment by abdonrd** [comment]
Yeah, I have the same issue.
