### ISSUE TITLE
Delete Table/Field within Directus

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1126]
This will be required for certain platforms that don't have direct access to the DB. I think we just need an "X" on the tables on the Settings page with 2-3 confirmations. I'll have to look into a design for this.

**Comment by benhaynes** [comment]
The interfaces for these have been added to `Settings > Tables & Inputs` and `Settings > Tables & Inputs > Table`. Let's have them delete on click after 2-3 directus style confirmations.

**Comment by benhaynes** [comment]
Looks good! Two comments:

Can we throw an alert if the user types the wrong column/table name when trying to delete? Right now it just closes and says nothing.

And can we add the column/table name at the top of the second alert so they can see what to type? The overlay blocks the name below...

**Comment by WellingGuzman** [comment]
Sure thing. how do you want the second alerted to styled or showed the column/table name?

_**Note:** I was testing the reaction thing. I've never saw that before._

**Comment by benhaynes** [comment]
`This cannot be undone. To confirm, please type the name of the table ("table_name") to delete.`

**Comment by benhaynes** [comment]
Actually:
`This cannot be undone. To confirm, please type the name of the table to delete: (table_name)`

**Comment by WellingGuzman** [comment]
seems about right. and without changing much. I like it.

**Comment by benhaynes** [comment]
This looks great!
