### ISSUE TITLE
Shares don't work with grouped fields

### ISSUE THREAD

**Issue by HitomiTenshi** [directus/directus#11278]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Only ungrouped fields are displayed.

### To Reproduce

Create a share for an item in a collection that has grouped fields. Only the ungrouped fields will show up.

### Errors Shown

None

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

16.13.2

### What database are you using?

MariaDB 10.3.32

### What browser are you using?

Firefox Latest

### What operating system are you using?

Windows 10

### How are you deploying Directus?

Ubuntu Server 20.04, npm installation with a systemd service running it

**Comment by azrikahar** [comment]
Hi! I've just tested this on my end and it works:

### Admin App

https://user-images.githubusercontent.com/42867097/151087866-8a9ec835-0476-4b1d-9b8a-6fe759e49688.mp4

### Share page

![chrome_0oSVWsIEgG](https://user-images.githubusercontent.com/42867097/151087907-e5112504-6c66-4e4d-8aac-b395e546562f.png)

Though this surfaced another bug where fields in groups are editable, but we'll track it on another issue/PR 👍

Just to be sure, could this be the same false positive with adblockers again? would you mind helping to rule that out? 😄

**Comment by HitomiTenshi** [comment]
I tested on Edge where I don't have any addons and I also tested on Firefox with my adblocker disabled, it didn't show.

BUT, I found out why it didn't show up now. You have to specifically also allow the groups in the public role. I previously only allowed to read the fields that were grouped but not their group-field (if that makes sense to you). I just added the group-fields to the public role and it showed up.

Sorry for the false positive again ☹️

**Comment by azrikahar** [comment]
Thanks for the prompt confirmation!

> BUT, I found out why it didn't show up now. You have to specifically also allow the groups in the public role. I previously only allowed to read the fields that were grouped but not their group-field (if that makes sense to you). I just added the group-fields to the public role and it showed up.

Ya that makes sense, and it is working as intended. No worries! 👍
