### ISSUE TITLE
Public vs Private files

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1127]
We'll need a way to set the privacy of files (public or private).

**Comment by benhaynes** [comment]
All files are public now, right @WellingGuzman? What would we need to do to allow for making some files private (only accessible through Directus or authenticated API)?

**Comment by WellingGuzman** [comment]
In order to serve private files we have to serve it through PHP, so only through the API and Web app can be accessible.

**Comment by benhaynes** [comment]
Gotcha. Sounds like a fun and exciting NEW feature...

**[Migrated to FeatHub](http://feathub.com/directus/directus/+51)**

Please use the [Directus FeatHub](http://feathub.com/directus/directus) to vote for features or make new request. Accepted feature requests will be added to GitHub Issues.
