### ISSUE TITLE
Overflowing formatted value display hides content completely

### ISSUE THREAD

**Issue by Fusseldieb** [directus/directus#11270]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

<img src="https://user-images.githubusercontent.com/4715129/151049186-e1513cb7-f7d6-43ec-a9e5-329a489d6e3f.png" width="500px">

Title basically describes the bug. Instead of ellipsing the final part of the name, it just hides it completely.
However, this only happens if the title is **wider** than the card, if it's shorter it displays it no problem.

### To Reproduce

1. Create an item
2. Set a long title
3. Enable "Cards" view on the right side of the Directus panel
4. Set the "Card" title template to be the long title
5. It will hide it completely

### Errors Shown

No errors, purely a CSS issue

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

-

### What database are you using?

-

### What browser are you using?

Chrome 97.0

### What operating system are you using?

Windows 10

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
From @nazariydj in #11293:

> seems to work correctly when changing CSS display param form **inline-block** to **inline** here: 
> https://github.com/directus/directus/blob/e0b2a99b62fbd2e5a716aa34ca2fd685a1eccac5/app/src/displays/formatted-value/formatted-value.vue#L213-L214

**Comment by benhaynes** [comment]
The proper solution here is to switch these card titles/subtitles to use the Display's `plaintext` output... when we have that.
