### ISSUE TITLE
CockroachDB fails on schema changes

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#11280]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Cockroach doesn't support doing schema operations after a regular sql operation in transactions. This is causing issues in data model operations (eg collections/fields/relations).

### To Reproduce

Try any transactions based schema operation in cockroachDB

### Errors Shown

```
unimplemented: the first schema change statement in a transaction must precede any writes
```

### What version of Directus are you using?

9.5.0 – 4e68cd2df429273512b2aa2a3b6ce8b568ff1ee9

### What version of Node.js are you using?

16

### What database are you using?

CockroachDB v21

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

Locally

**Comment by rijkvanzanten** [comment]
@wodka solved this previously by using a nested transaction, that wasn't a branch of the parent transaction in https://github.com/directus/directus/pull/10113. This broke SQLite support however, as that can't do multiple connections simultaneously[^1]. @licitdev "fixed" this in https://github.com/directus/directus/pull/11227 by using the parent transaction as the starting point, however that resurfaces this problem, as Cockroach does not like that.

[^1]: Opening a new transaction during a transaction will cause a secondary connection to be opened to the database

**Comment by rijkvanzanten** [comment]
CockroachDB doesn't support doing schema changes in transactions after a regular write. SQLite doesn't support nested transactions, MySQL simply ignores transactions altogether when doing schema operations.

Long story short, we can't reliably rely on transactions in schema changes (eg /collections, /fields, and /relations). The linked PR is the start of a (bigger) change to effectively remove the usage of transactions in schema operations, in favor of doing proper validation before doing the schema alterations.

**Comment by aidenfoxx** [comment]
TFW it's not Oracle being the problem 🤤

**Comment by wodka** [comment]
mmhm - in typeorm we are solving this problem by having an config setting to define how migrations should handle transactions.

We could do something similar here with setting different defaults per driver?

I would still prefer to have a transaction running for migrations - as it would else become hard to know how to continue on a failed transaction.

**Comment by rijkvanzanten** [comment]
@wodka in that case, we'd have very different behavior depending on what database driver you happen to use. I'd rather find a solution that works the same way regardless of vendor just to make sure we keep the directus codebase itself as agnostic as possible
