### ISSUE TITLE
Ability to change the default status for tables

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1128]
We need to add a dropdown (system) on the "active/status" area of `Settings > Tables & Inputs > Table` so that users can change the default value of this column. It would update the actual DEFAULT variable for the `table.active`. 

It's values would be the available status options (currently global) which should be switched to a per-table basis: #1117 

![screen shot 2016-03-06 at 5 34 13 pm](https://cloud.githubusercontent.com/assets/522079/13557593/c5a8758a-e3c1-11e5-9c06-de2f258f8801.png)

**Comment by WellingGuzman** [comment]
This was implemented in `6.4.x`, you can change the columns default values.
