### ISSUE TITLE
API requests without authentication?

### ISSUE THREAD

**Issue by talbet** [directus/directus#1129]
Is there any way to make a GET request without being logged in? Or alternately, is there any way to generate a persistant API key that can be used for read access to specific tables?

It's not clear from the docs how a front-end would consume the API if you were using Directus as a CMS.

**Comment by WellingGuzman** [comment]
Hey @talbet, we were aware of that recently and what you can do if you are using [6.1.0](https://github.com/directus/directus/releases/tag/6.1.0) or above is after log into directus, go to users and in any users you would like to authenticated as, is to generate or type any string you like to be the your API key. (see image below)

![screen shot 2016-03-09 at 3 00 29 am](https://cloud.githubusercontent.com/assets/1531291/13627779/51b979a6-e5a3-11e5-963b-a8cba7dcc79e.png)

With that token you can authenticate to the API without the need to log into Directus first.

```bash
curl http://website.dom/api/1/tables/projects -u yc7mGPaQu9mchJf1:
```

Notice the `:` at the end.

We are working into update and have a more recent documentations.

let me know if this works for you.

**Comment by talbet** [comment]
@WellingGuzman Thanks for your assistance, that works.

**Comment by che-wf** [comment]
How do you do this in v7? I'm not seeing any token generator.

**Comment by benhaynes** [comment]
You can...

* Use credentials to authenticate and get a token
* Use a static token (doesn't change) from `directus_users.token`
* Make the data public (turn on permissions in the public group)

https://docs.directus.io/api/reference.html#authentication
