### ISSUE TITLE
Field Validation leads to Internal Server Error (again)

### ISSUE THREAD

**Issue by aaron-manning** [directus/directus#11299]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Please see #3375 
This issue has resurfaced in 9.4.3 and 9.5 when trying to add validation to directus_users to stop admins from being able to make more admin users.

### To Reproduce

Add the following validation to directus_users 'create' ability

```
{
	"_and": [
		{
			"role": {
				"admin_access": {
					"_eq": false
				}
			}
		}
	]
}
```

### Errors Shown

Unable to create a user when any validation is present.

```

{
    "errors": [
        {
            "message": "\"role\" must be of type object",
            "extensions": {
                "code": "FAILED_VALIDATION",
                "field": "role"
            }
        }
    ]
}

this also causes a similar error

{
	"_and": [
		{
			"first_name": {
				"_nempty": true
			}
		}
	]
}

"Cannot convert undefined or null to object"

```

### What version of Directus are you using?

9.5

### What version of Node.js are you using?

14.8.1

### What database are you using?

postgres:14.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by jaycammarano** [comment]
```
{
	"_and": [
		{
			"role": {
				"admin_access": {
					"_eq": false
				}
			}
		}
	]
}
```
Why have an "_and" with only one thing in the array?

Also, yes this does happen on 9.5 if you mean what I think you mean.
I put that into the field validation and then went to users. The role didn't show in the sidebar. I made a user in that role by going into the role on roles and permissions. I created a user and it showed up on the user page but only under all. The role still didn't show up.

<img width="632" alt="Screen Shot 2022-01-26 at 4 08 38 PM" src="https://user-images.githubusercontent.com/67079013/151247574-ab811671-167a-4e71-81c8-a67f7557788e.png">


<img width="419" alt="Screen Shot 2022-01-26 at 4 08 52 PM" src="https://user-images.githubusercontent.com/67079013/151247567-5c023bdd-35e3-4f86-8cf8-189e690a4151.png">

**Comment by aaron-manning** [comment]
> ```
> {
> 	"_and": [
> 		{
> 			"role": {
> 				"admin_access": {
> 					"_eq": false
> 				}
> 			}
> 		}
> 	]
> }
> ```
> 
> Why have an "_and" with only one thing in the array?
> 
> Also, yes this does happen on 9.5 if you mean what I think you mean. I put that into the field validation and then went to users. The role didn't show in the sidebar. I made a user in that role by going into the role on roles and permissions. I created a user and it showed up on the user page but only under all. The role still didn't show up.
> 
> <img alt="Screen Shot 2022-01-26 at 4 08 38 PM" width="632" src="https://user-images.githubusercontent.com/67079013/151247574-ab811671-167a-4e71-81c8-a67f7557788e.png">
> 
> <img alt="Screen Shot 2022-01-26 at 4 08 52 PM" width="419" src="https://user-images.githubusercontent.com/67079013/151247567-5c023bdd-35e3-4f86-8cf8-189e690a4151.png">
> 
> Note: the user and role are in the db via the api.

The "and" was added automatically by the UI when adding the field validation

**Comment by aaron-manning** [comment]
Here is the issue

![image](https://user-images.githubusercontent.com/32957675/151258737-f591640f-30ca-421d-9bb8-0f7b93120980.png)

This is with a fresh database and fresh install of directus 9.5 (docker).

Steps:

Add new role.
Add new user to that role.
Configure role to have a field validator for creating/editing users.
Log in as new user.
Try adding a user (as the new user).
See error message.

**Comment by azrikahar** [comment]
> The role didn't show in the sidebar. I made a user in that role by going into the role on roles and permissions. I created a user and it showed up on the user page but only under all. The role still didn't show up.

Technically it's unrelated, but I can confirm I've experienced this in the past & even in the current version. This should be an issue with the users page's navigation not refreshing upon any role added/removed/updated. Let's track it in another issue: #11350

---

As for the current validation error, seems like the form is submitting:

```js
{
    "role": "<uuid>"
}
```

Which is correct. However, when using OP's field validation, it is now expecting:

```js
{
    "role": {
        "admin_access": {
            "_eq": <boolean value here>
        }
    }
}
```

due to the payload validation over here:

https://github.com/directus/directus/blob/81b1ea8fb63f9445e21988bbcc83b9d491d4c4e2/packages/shared/src/utils/validate-payload.ts#L48-L50

which is why the error says `"\"role\" must be of type object"`.

**Comment by rijkvanzanten** [comment]
Thanks for looking into that @azrikahar.

Sounds like it's working as expected. If you configure the validation rules to check for an object with a nested field, that's what needs to be submitted.

In this case, you'd want to configure the permissions as:

```
_or:
  - role
      _in: ['a', 'b', 'c']

  - role
      admin_access:
        _eq: false
```

to allow selecting an existing role that is allow-listed, or allow creating a new one, but only if admin_access is false.

There's a discussion going here on how to streamline this setup a little better, to avoid this confusion: https://github.com/directus/directus/discussions/10771#discussioncomment-1888999
