### ISSUE TITLE
Case-Sensitive Bearer != bearer (Authorization)

### ISSUE THREAD

**Issue by ngjoni** [directus/directus#11300]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

If you use the Authorization Header, bearer and Bearer are not the same.

### To Reproduce

Put 'bearer <token>' in your header.

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

16

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by jaycammarano** [comment]
This is something I've seen in the oauth drivers. It was an issue with facebook returning a bearer token and everyone else returning a Bearer token. The library we were using had a limitation that only accepted Bearer I believe.

#9534 was related

**Comment by rijkvanzanten** [comment]
> If you use the Authorization Header, bearer and Bearer are not the same.

This is currently working as intended. Lets move this to a feature request discussion so we can keep discussing why / why not the header should be case insensitive 👍🏻
