### ISSUE TITLE
Multi-lingual Support: Create language files

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1131]
We need to create a simple system for creating language files to decouple the English in the framework. Once we have the system in place it should be easy to get many translations. @WellingGuzman thoughts?

**Comment by benhaynes** [comment]
https://webtranslateit.com/en/docs/file_formats/json

**Comment by WellingGuzman** [comment]
we should take a look at this: http://symfony.com/doc/current/components/translation/usage.html

**Comment by WellingGuzman** [comment]
oh wait. we need one for the front end :) anyway it's something to look at.

**Comment by christophemarois** [comment]
+1

**Comment by benhaynes** [comment]
@christophemarois working on this update over the next few days. Should have it up soon!
