### ISSUE TITLE
Unsupported Media Type for Patching file 

### ISSUE THREAD

**Issue by kuzmi4** [directus/directus#11335]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

For updating FILE can be used json, and multiform mediatypes (https://docs.directus.io/reference/files/#update-a-file) 

At now you recieve reject when send application/json mediatype data for PATCH /files/:id
![2022-01-29 110108](https://user-images.githubusercontent.com/6544815/151653086-38153c7c-4b59-408b-9966-fc5b0fe84682.png)

### To Reproduce

Send request for update direactus file data (title, tags, etc...) in application/json mediatype

### Errors Shown

{
    "errors": [
        {
            "message": "Unsupported Content-Type header",
            "extensions": {
                "code": "UNSUPPORTED_MEDIA_TYPE"
            }
        }
    ]
}

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

17.4.0

### What database are you using?

Postgres 13

### What browser are you using?

Firefox

### What operating system are you using?

Linux 5.4.0-42-generic

### How are you deploying Directus?

Kubernetes

**Comment by Prochy20** [comment]
I can cofirm I have the same issue in my instance.

**Comment by paescuj** [comment]
Do you want to replace the file itself or just the metadata? How does your request look like?

Fromt the docs:
> You can either submit a JSON object consisting of a partial file object to update the file meta, or send a multipart/form-data request to replace the file contents on disk.

**Comment by kuzmi4** [comment]
I send json via application json for update metadata. 
(For update file data i use multiform)

Olso need change OAS file for add information about multiform type

<img width="733" alt="изображение" src="https://user-images.githubusercontent.com/6544815/151665029-d58cc9dd-d19a-4eb2-89b5-2fc389940c85.png">

**Comment by jeremybradbury** [comment]
I was able to duplicate this issue in a different way. I uploaded an image to attach it to an object in a collection.

Later when I tried to rename the title using file editor in the admin UI, it gave this same error.

9.5.0 as well, but running node v14 & v16
