### ISSUE TITLE
Map field settings missing in 9.5.0?

### ISSUE THREAD

**Issue by aaron-manning** [directus/directus#11332]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Please see the first image here: https://github.com/directus/directus/pull/3183

Are maps supposed to have a few configuration options? If so, those seem to have disappeared between that PR being merged and now.

### To Reproduce

Create a map field and view the configuration.

### Errors Shown

On 9.5 i'm getting the following:

![image](https://user-images.githubusercontent.com/32957675/151636478-eaf737a9-5572-4659-a596-3fca61277433.png)

And under conditions:

![image](https://user-images.githubusercontent.com/32957675/151636505-8484e42c-e594-4350-92cb-934f029baa0f.png)

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

14.8.1

### What database are you using?

postgres:14.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
@aaron-manning Keep in mind that that PR isn't the final implementation. https://github.com/directus/directus/pull/5684 is the follow up that included the actual final interface.
