### ISSUE TITLE
Many-to-one won't add properly

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1134]
When adding a many-to-one column through directus it doesn't add a `relationship_type`. It saves NULL, but it should be `MANYTOONE`. I do mine directly in the database so I didn't notice this. Thanks @webbakery !

**Comment by WellingGuzman** [comment]
This was fixed already in [here](https://github.com/directus/directus/commit/137a3b46f37db6dba4876839433efa3a4ef8b9cb)
