### ISSUE TITLE
MSSQL new project initialisation error 

### ISSUE THREAD

**Issue by arladmin** [directus/directus#11352]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When trying to set up a fresh Directus (docker) project, by connecting to a cloud MSSQL database, the installation process errors with the following log:
```
07:30:14 ✨ Initializing bootstrap...

07:30:14 ✨ Installing Directus system tables...

07:30:16 ✨ Running migrations...

07:30:16 ✨ Applying Remove Collection Foreign Keys...

07:30:16 ✨ Applying Remove System Relations...

07:30:17 ✨ Applying Remove System Collections...

07:30:17 ✨ Applying Remove System Fields...

07:30:17 ✨ Applying Add Cascade System Relations...

07:30:20 ✨ Applying Change Webhook URL Type...

07:30:20 ✨ Applying Add Relations Sort Field...

07:30:20 ✨ Applying Remove Locked Fields...

RequestError: ALTER TABLE [directus_fields] DROP COLUMN [locked] - ALTER TABLE DROP COLUMN locked failed because one or more objects access this column.

    at RequestTokenHandler.onErrorMessage (/directus/node_modules/tedious/lib/token/handler.js:362:21)

    at Readable.<anonymous> (/directus/node_modules/tedious/lib/token/token-stream-parser.js:26:33)

    at Readable.emit (node:events:390:28)

    at addChunk (node:internal/streams/readable:315:12)

    at readableAddChunk (node:internal/streams/readable:289:9)

    at Readable.push (node:internal/streams/readable:228:10)

    at next (node:internal/streams/from:98:31)

    at processTicksAndRejections (node:internal/process/task_queues:96:5) {

  code: 'EREQUEST',

  number: 4922,

  state: 9,

  class: 16,

  serverName: 'WIN-HI1Q00LUV6N\\SQLEXPRESS',

  procName: '',

  lineNumber: 1

}
```

### To Reproduce

Create a new docker-based Directus project and connect it to an existing MSSQL database.

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

14.x

### What database are you using?

MSSQL 10.50.4000

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
@arladmin [Directus only supports MS SQL version 13 and up](https://github.com/directus/directus#-requirements). Please try upgrading your version of MS SQL and try again. (Which might be a good idea regardless, as MSSQL reached EOL in 2014, and stopped receiving extended support from MS in 2019 😬).

**Comment by arladmin** [comment]
@rijkvanzanten Thanks for the info. 

It's a bit out of my scope currently to upgrade the version.

Would there be any possible workaround in such a case?

**Comment by rijkvanzanten** [comment]
I don't think there's a workaround besides using a different database.. 

The installation seems to pass in our tests (and locally) on MS SQL versions 13+, which makes me think this is caused by a change in MSSQL itself. We aim to support LTS versions, and unfortunately can't support older versions indefinitely (especially not if they're EOL and discouraged from being used by the software vendor).

Even if there was a workaround for this one migration, it'd indicate that you might run into other similar issues down the line while using Directus.

**Comment by arladmin** [comment]
Hi @rijkvanzanten , i took your advice and set up a much newer MS SQL SERVER 2016 (mssql version 13.x).

I'm still facing the same issue:

```
07:00:47 ✨ Initializing bootstrap...

07:00:47 ✨ Installing Directus system tables...

07:00:49 ✨ Running migrations...

07:00:49 ✨ Applying Remove Collection Foreign Keys...

07:00:51 ✨ Applying Remove System Relations...

07:00:52 ✨ Applying Remove System Collections...

07:00:52 ✨ Applying Remove System Fields...

07:00:52 ✨ Applying Add Cascade System Relations...

07:00:56 ✨ Applying Change Webhook URL Type...

07:00:57 ✨ Applying Add Relations Sort Field...

07:00:57 ✨ Applying Remove Locked Fields...

RequestError: ALTER TABLE [directus_fields] DROP COLUMN [locked] - ALTER TABLE DROP COLUMN locked failed because one or more objects access this column.

    at RequestTokenHandler.onErrorMessage (/directus/node_modules/tedious/lib/token/handler.js:362:21)

    at Readable.<anonymous> (/directus/node_modules/tedious/lib/token/token-stream-parser.js:26:33)

    at Readable.emit (node:events:390:28)

    at addChunk (node:internal/streams/readable:315:12)

    at readableAddChunk (node:internal/streams/readable:289:9)

    at Readable.push (node:internal/streams/readable:228:10)

    at next (node:internal/streams/from:98:31)

    at processTicksAndRejections (node:internal/process/task_queues:96:5) {

  code: 'EREQUEST',

  number: 4922,

  state: 9,

  class: 16,

  serverName: 'WIN-HI1Q00LUV6N\\MSSQLSERVER2016',

  procName: '',

  lineNumber: 1

}
```

**Comment by arladmin** [comment]
Kindly reopen this issue as it's still valid.

**Comment by arladmin** [comment]
@rijkvanzanten  Kindly reopen this issue as it's still valid.

**Comment by Oreilles** [comment]
In SQL Server, as dumb as it sound, you cannot drop a column that has a default value. First, you need to find, then drop the constraint that defines the default value.
`knex` try to do that with the following query:
```sql
              DECLARE @constraint varchar(100) = (SELECT default_constraints.name
                                                  FROM sys.all_columns
                                                  INNER JOIN sys.tables
                                                    ON all_columns.object_id = tables.object_id
                                                  INNER JOIN sys.schemas
                                                    ON tables.schema_id = schemas.schema_id
                                                  INNER JOIN sys.default_constraints
                                                    ON all_columns.default_object_id = default_constraints.object_id
                                                  WHERE schemas.name = '${schema}'
                                                  AND tables.name = '${this.tableNameRaw}'
                                                  AND all_columns.name = '${column}')
              IF @constraint IS NOT NULL EXEC('ALTER TABLE ${this.tableNameRaw} DROP CONSTRAINT ' + @constraint)`;
```
https://github.com/knex/knex/blob/4494113187cb246d402e1d8747f9bea630d38aa3/lib/dialects/mssql/schema/mssql-tablecompiler.js#L133-L164

For whatever reason, this query does not seem to return anything here, or maybe returns multiple rows, leaving one or more unallowed hanging constraints when trying to delete the column. It is really strange that no one ever faced this issue.

@arladmin, could you run the following query in your cloud database, and tell us what you get ?
```
CREATE TABLE foo(foo BIT NOT NULL DEFAULT 0);

SELECT *
FROM sys.all_columns
INNER JOIN sys.tables
  ON all_columns.object_id = tables.object_id
INNER JOIN sys.schemas
  ON tables.schema_id = schemas.schema_id
INNER JOIN sys.default_constraints
  ON all_columns.default_object_id = default_constraints.object_id
WHERE schemas.name = 'dbo'
AND tables.name = 'foo'
AND all_columns.name = 'foo';
```

**Comment by arladmin** [comment]
@Oreilles Thanks for your inputs!

I executed the script Statement-wise and these are the results-

Statement 1:
![image](https://user-images.githubusercontent.com/64059154/153533238-0cb80347-4d69-40e1-8bd6-7157e1023182.png)

Statement 2:
![image](https://user-images.githubusercontent.com/64059154/153533360-517f552d-88ef-486d-b05f-58c6fb42ea2c.png)
![image](https://user-images.githubusercontent.com/64059154/153533405-9227dc5b-13bc-47a0-9a63-8677df42ac4e.png)
![image](https://user-images.githubusercontent.com/64059154/153533435-5547bb22-2f1e-4b0c-a4a9-04f6a4d7c09b.png)
![image](https://user-images.githubusercontent.com/64059154/153533459-3184b6ca-adcc-420b-80de-38d173ab284c.png)
![image](https://user-images.githubusercontent.com/64059154/153533522-f6c7f5bb-d264-4340-95e2-3c7f3f46bb15.png)

**Comment by Oreilles** [comment]
There are some columns missing in your screenshot, could you copy & paste the results instead ?
Also, can you tell us the cloud provider you're using so we can try and replicate ?

**Comment by Oreilles** [comment]
Can you confirm `arvindprT2` is the name of your database ?

**Comment by arladmin** [comment]
> Can you confirm `arvindprT2` is the name of your database ?

'arvindprT2_' is the database name and 'arvindprT2' is one of the schemas in it.

**Comment by arladmin** [comment]
@Oreilles 

> Can you confirm `arvindprT2` is the name of your database ?

```arvindprT2_``` is the database name and ```arvindprT2``` is one of the schemas in it.

**Comment by arladmin** [comment]
@Oreilles 

> Can you confirm `arvindprT2` is the name of your database ?

```arvindprT2_``` is the database name and ```arvindprT2``` is one of the schemas in it.

**Comment by arladmin** [comment]
Any help on this, anyone?

**Comment by rijkvanzanten** [comment]
> Any help on this, anyone?

We recognize that this may be an important fix for you, but we are a small open-source organization with a lot to triage and complete. If you need immediate help, consider [sponsoring](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍 .

**Comment by jesusaristigueta** [comment]
This issue is still present with the latest Directus version (v9.14.5), I'm using MSSQL 2019 (v15.0.2000.5).

`Something went wrong while seeding the database:

[EREQUEST] ALTER TABLE [directus_fields] DROP COLUMN [locked] - ALTER TABLE DROP COLUMN locked failed because one or more objects access this column.

Please try again`

**Comment by azrikahar** [comment]
> This issue is still present with the latest Directus version (v9.14.5), I'm using MSSQL 2019 (v15.0.2000.5).
> 
> `Something went wrong while seeding the database:
> 
> [EREQUEST] ALTER TABLE [directus_fields] DROP COLUMN [locked] - ALTER TABLE DROP COLUMN locked failed because one or more objects access this column.
> 
> Please try again`

@jesusaristigueta What was the specific migration that causes this? From the terminal, it should be the migration step right before this error that you have shared. For OP's example, it was `Applying Remove Locked Fields...`. Is it the same for you, or perhaps different?

**Comment by jesusaristigueta** [comment]
@azrikahar I was trying a fresh install, blank database, new directus project; NodeJS LTS v16, had the same issue when trying to install on Windows 10 and Debian 11. I switched DB engine to PostgreSQL 13 as I didn't have time to solve the issue with MSSQL, needed a quick project.

**Comment by ixAtomic** [comment]
Hello, I believe I am running into this issue as well on a fresh install of directus to an mssql database. I have tried to migrate on an instance of mssql 15 and mssql 14 and both of them get stuck on this same step as described above.  (dropping the locked column). I am running it on localhost. I can run the same script as above if needed.

**Comment by ixAtomic** [comment]
3 issues (at least for mssql) that I think ive found are: 
1. remove-locked-fields.ts - the constraint (directus_fields_locked_default) needs to be dropped before the column 'locked' can be dropped
2. make-filesize-nullable.ts - the constraint (directus_files_filesize_default) needs to be dropped
3. restructure-relations.ts - the default value for the column 'one_deselect_action' seems to be having its default value set twice causing it to fail.

thats all ive got so far, I am getting another error on the add-shares.ts that I havent looked into yet.

not sure if these would cause issues for other databases as well. im a bit of a noob so I might be off on a tangent in the first place

**Comment by rijkvanzanten** [comment]
@ixAtomic What exact version of ms sql are you seeing the issues in? My primary testing target is "server 2019" that I'm running containerized through https://github.com/directus/directus/blob/c8ae40f82756e6933a6d12869f472e34817b209d/docker-compose.yml#L99-L105, so I'm very curious to hear what the difference is between that version (that seems to work), the current "Azure SQL" (which also seems to work for me), and the exact version you're testing with 🙂

**Comment by ixAtomic** [comment]
I have run it on two different version of mssql. one on mssql 2019 version 15.0.2000.5 and another on mssql 2017 version 14.0.3451.2. I am not using containers for either of these instances. on both, I always run into the same initial error. which is the locked column failing

**Comment by ixAtomic** [comment]
Ok so I found what is causing this issue (for me at least). I was using a schema instead of using just plane dbo to try and generate my schemas. when I switched to using dbo it instantly worked. I was not aware that this was a restriction for mssql databases. I apologize, thanks for the help!

**Comment by rijkvanzanten** [comment]
> Ok so I found what is causing this issue (for me at least). I was using a schema instead of using just plane dbo to try and generate my tables. when I switched to using dbo it instantly worked. I was not aware that this was a restriction for mssql databases. I apologize, thanks for the help!

!! There's the missing piece. Thanks for helping debug that 🙂 @arladmin were you similarly using a non-dbo schema?

**Comment by rijkvanzanten** [comment]
Linear: [ENG-275](https://linear.app/directus/issue/ENG-275/mssql-new-project-initialisation-error)

**Comment by br41nslug** [comment]
I have tested running bootstrap with the latest Directus version against both MSSQL 2016 and MSSQL 2017 and was unable to reproduce this currently.

**Comment by woeterman94** [comment]
> I have tested running bootstrap with the latest Directus version against both MSSQL 2016 and MSSQL 2017 and was unable to reproduce this currently.

Negative. 
Issue still appears fresh install on Azure App Service with an Azure Database. Same error message.

```
2023-03-02T17:37:26.240202044Z               at Readable.<anonymous> (/directus/node_modules/tedious/lib/token/token-stream-parser.js:26:33)
2023-03-02T17:37:26.240206244Z               at Readable.emit (node:events:513:28)
2023-03-02T17:37:26.240209844Z               at addChunk (node:internal/streams/readable:324:12)
2023-03-02T17:37:26.240213344Z               at readableAddChunk (node:internal/streams/readable:297:9)
2023-03-02T17:37:26.240216944Z               at Readable.push (node:internal/streams/readable:234:10)
2023-03-02T17:37:26.240220444Z               at next (node:internal/streams/from:98:31)
2023-03-02T17:37:26.240223744Z               at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-03-02T17:37:26.240227244Z       "code": "ELOGIN"
2023-03-02T17:37:26.240230544Z     }
```

**Comment by rijkvanzanten** [comment]
> > I have tested running bootstrap with the latest Directus version against both MSSQL 2016 and MSSQL 2017 and was unable to reproduce this currently.

> Negative.

I mean.. that's not up for discussion haha. Tim couldn't reproduce it, that hasn't changed 🤷🏻  Can you share exact steps on how to reproduce this on Azure, including order of operations, and exact versions and services used?

**Comment by woeterman94** [comment]
Okay whoops. I thought this issue was about a MSSQL issue when setting up a new instance. I said negative cause I ran into the same issue today. I fixed it by:
- Resetting my database (clearing all tables, resetting indexes...)
- Setting DB_OPTIONS__ENCRYPT to true

Not sure what was the exact issue. I restarted the app multiple times and in the end I got my installation running :)
