### ISSUE TITLE
Unable to register extension hooks after directus upgrade

### ISSUE THREAD

**Issue by pchebro** [directus/directus#11363]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have recently migrated directus version from 9.0.0 to 9.5.0 and getting couldn't register hook warnings. As a result custom validation is not working that we have coded inside hooks. 

### To Reproduce

Create a hook using Directus 9.0.0 version. 
Update your directus version to 9.5.0.
Deploy/run directus app in local.

### Errors Shown

simple	28-Jan-2022 18:37:49	2022-01-28T18:37.48-0500 [APP/PROC/WEB/0]OUT 23:37:48 ⚠️  Couldn't register hook "effective-date"
simple	28-Jan-2022 18:37:49	2022-01-28T18:37.48-0500 [APP/PROC/WEB/0]OUT 23:37:48 ⚠️  Cannot destructure property 'FailedValidationException' of 'exceptions' as it is undefined.
simple	28-Jan-2022 18:37:49	2022-01-28T18:37.48-0500 [APP/PROC/WEB/0]OUT 23:37:48 ⚠️  Couldn't register hook "hyperlink"
simple	28-Jan-2022 18:37:49	2022-01-28T18:37.48-0500 [APP/PROC/WEB/0]OUT 23:37:48 ⚠️  Cannot destructure property 'FailedValidationException' of 'exceptions' as it is undefined.
simple	28-Jan-2022 18:37:49	2022-01-28T18:37.48-0500 [APP/PROC/WEB/0]OUT 23:37:48 ✨ Loaded extensions: effective-date, hyperlink
simple	28-Jan-2022 18:37:49	2022-01-28T18:37.48-0500 [APP/PROC/WEB/0]OUT 23:37:48 ⚠️  Upload directory (/home/vcap/app/uploads) is not read/writeable!

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

16.13.1

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Bamboo and running locally

**Comment by rijkvanzanten** [comment]
@pchebro What does your hook look like? How are you building it for production use?

**Comment by pchebro** [comment]
Two files have been added for each validation as below. 

![image](https://user-images.githubusercontent.com/89423003/151871422-571a97c6-5ffc-4dd9-8650-0adb2eff108a.png)

And then inside index.js this is how I have code: 

![image](https://user-images.githubusercontent.com/89423003/151871680-83f7a53f-f541-4778-aece-0a0ac2367b54.png)

Hope this helps. Please let me know otherwise.

**Comment by rijkvanzanten** [comment]
Ah, I believe you updated from an earlier RC version, not `9.0.0` production, does that sound about right? The structure for hooks was changed before the production 9.0.0 release (in https://github.com/directus/directus/pull/8027 to be exact).

The updated structure would be:

```js
module.exports = function registerHook({ filter }, { exceptions }) {
  const { FailedValidationException, InvalidQueryException } = exceptions;

  action('items.*', async function (input, collection) { ... });
}
```

**Comment by pchebro** [comment]
Yes it is RC83 version. Ah, I see it's a different structure for newer version. Thanks for looking into it.

**Comment by pchebro** [comment]
Updated the structure as directed above and it worked. I really like the transformation of features between rc version and 9.5.0.

I also have another question regarding left side content navigation bar.  Is there a way to customize the below collection view as tree structure? For example, I would like to have Links and Documents appear as child pages inside Universal Navigation with collapse and expand button. Is there any reference documentation that you can point to? Please let me know if I need to open new feature request.

![image](https://user-images.githubusercontent.com/89423003/152153538-6e238ea8-40f3-4fa9-bf66-00f9fe709f9d.png)
