### ISSUE TITLE
S3 Storage Configuration Bug

### ISSUE THREAD

**Issue by rogersanick** [directus/directus#11368]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hi there,

The issue I'm currently facing is as follows. I am unable to upload files via the S3 storage configuration. I have triple checked that the configuration is correct but an error still persists. Additionally, despite a failed upload three `file` records are created in the UI.

### To Reproduce

1. Configure S3 for File Storage
2. Attempt to upload a file

### Errors Shown

```
Error code: InvalidArgument                                                                                        │
│ directus Original stack:                                                                                                    │
│ directus InvalidArgument: null                                                                                              │
│ directus     at Request.extractError (/directus/node_modules/aws-sdk/lib/services/s3.js:710:35)                             │
│ directus     at Request.callListeners (/directus/node_modules/aws-sdk/lib/sequential_executor.js:106:20)                    │
│ directus     at Request.emit (/directus/node_modules/aws-sdk/lib/sequential_executor.js:78:10)                              │
│ directus     at Request.emit (/directus/node_modules/aws-sdk/lib/request.js:686:14)                                         │
│ directus     at Request.transition (/directus/node_modules/aws-sdk/lib/request.js:22:10)                                    │
│ directus     at AcceptorStateMachine.runTo (/directus/node_modules/aws-sdk/lib/state_machine.js:14:12)                      │
│ directus     at /directus/node_modules/aws-sdk/lib/state_machine.js:26:10                                                   │
│ directus     at Request.<anonymous> (/directus/node_modules/aws-sdk/lib/request.js:38:9)                                    │
│ directus     at Request.<anonymous> (/directus/node_modules/aws-sdk/lib/request.js:688:12)                                  │
│ directus     at Request.callListeners (/directus/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```

### Current Configuration

STORAGE_S3_KEY=XXXXXXXX
STORAGE_S3_ROOT=directus
STORAGE_S3_ACL=public
STORAGE_S3_BUCKET=messari-directus-stage-184ed86
STORAGE_S3_REGION=us-west-2
STORAGE_S3_ENDPOINT=https://s3.amazonaws.com
STORAGE_S3_SECRET=XXXXXXXXXXX
STORAGE_LOCATIONS=s3
STORAGE_S3_DRIVER=s3

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

16.13.2

### What database are you using?

Postgres 10

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
I think the cryptic `InvalidArgument: null` is AWS' way of saying that one of the options is wrong. In your example, the value for `ENDPOINT` looks suspect to me. Could you try omitting that env var completely (so it uses AWS' default)?

**Comment by rogersanick** [comment]
@rijkvanzanten - I just removed that block, but am still getting the same message unfortunately. 

STORAGE_S3_KEY=XXXXXXXX
STORAGE_S3_ROOT=directus
STORAGE_S3_ACL=public
STORAGE_S3_BUCKET=messari-directus-stage-184ed86
STORAGE_S3_REGION=us-west-2
STORAGE_S3_SECRET=XXXXXXXXXXX
STORAGE_LOCATIONS=s3,local
STORAGE_S3_DRIVER=s3

We got it working with local file storage by switching to STORAGE_LOCATIONS:local,s3

This is the updated error message:

```20:44:23 🚨 The "path" argument must be of type string. Received null                                                                        │
│ TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null                                                  │
│     at new NodeError (node:internal/errors:371:5)                                                                                            │
│     at validateString (node:internal/validators:119:11)                                                                                      │
│     at Object.join (node:path:1172:7)                                                                                                        │
│     at AmazonWebServicesS3Storage._fullPath (/directus/node_modules/@directus/drive-s3/dist/AmazonWebServicesS3Storage.js:39:61)             │
│     at AmazonWebServicesS3Storage.exists (/directus/node_modules/@directus/drive-s3/dist/AmazonWebServicesS3Storage.js:86:25)                │
│     at AssetsService.getAsset (/directus/node_modules/directus/dist/services/assets.js:69:71)                                                │
│     at runMicrotasks (<anonymous>)                                                                                                           │
│     at processTicksAndRejections (node:internal/process/task_queues:96:5)     ```

**Comment by azrikahar** [comment]
@rogersanick Can you try with the following changes:

- We should remove `STORAGE_S3_ROOT=directus`. `STORAGE_<LOCATIONS>_ROOT` is a local storage specific env variable. Even if you intend to apply it to the local storage strategy, you should use `STORAGE_LOCAL_ROOT` instead, not S3.

- Granted I may not have much hands on experience, but is `public` a valid ACL you have configured? Judging from [the official docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#canned-acl), perhaps you are looking for `public-read` instead since `public` doesn't exist by default? You can also try to remove that variable flat out just as another for of test if `public-read` still isn't working 👍

**Comment by jdoig** [comment]
`In my case what was causing this was a permission issue, the error message gave no clue to this.

**Comment by azrikahar** [comment]
@jdoig would you mind sharing said error message? Just to be sure whether it's coming from the AWS S3 sdk (which we may have less control) or from the Directus API. Definitely would be nice if we are able to make the error more descriptive when possible.

---

That said, I am inclined to believe OP issue is more of a configuration issue rather than an actual bug, so I'll proceed to close this for now. Will reopen if that's not the case 👍

**Comment by jdoig** [comment]
@azrikahar it's exactly as the original reporter put in their ticket (it was searching this error that lead me directly to this ticket).
Sorry I've not got the exact output to hand as it was days ago now.

**Comment by magno32** [comment]
I also had this problem.  I was getting `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null`

Deeper in the stack trace on ECS there was an `access-denied` error.  Fixing write permissions on the bucket that I was using fixed the issue. 

CDK:
```typescript
storageBucket.grantReadWrite(app.taskDefinition.taskRole);
```

Also, since I'm running on ECS, I only had to use the following props to get it working:

```typescript
{
            STORAGE_LOCATIONS: 's3',
            STORAGE_S3_DRIVER: 's3',
            STORAGE_S3_BUCKET: storageBucket.bucketName,
            STORAGE_S3_REGION: props.vpc.stack.region
}
```

**Comment by anselm94** [comment]
> @rogersanick Can you try with the following changes:
> 
> * We should remove `STORAGE_S3_ROOT=directus`. `STORAGE_<LOCATIONS>_ROOT` is a local storage specific env variable. Even if you intend to apply it to the local storage strategy, you should use `STORAGE_LOCAL_ROOT` instead, not S3.
> * Granted I may not have much hands on experience, but is `public` a valid ACL you have configured? Judging from [the official docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#canned-acl), perhaps you are looking for `public-read` instead since `public` doesn't exist by default? You can also try to remove that variable flat out just as another form of test if `public-read` still isn't working 👍

`STORAGE_S3_ROOT` worked in my case, as `root` is one of the options for Directus S3 adapter

https://github.com/directus/directus/blob/dc1a218c58110fc28ec58a43b817069ec72df173/packages/storage-driver-s3/src/index.ts#L24
