### ISSUE TITLE
Registering custom hook extension fails when using plaiceholder package

### ISSUE THREAD

**Issue by Polynook** [directus/directus#11360]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I'm trying to use [plaiceholder](https://github.com/joe-bell/plaiceholder) inside a custom hook but having problems.

The custom hook extension as the following index.ts file:
![Screenshot 2022-01-31 182208](https://user-images.githubusercontent.com/71569839/151831894-b5292cfc-c677-4b7e-af30-b7c82f108ffc.png)

I build the extension, place it inside Directus app and run `npx directus start`. I get the following error:

![Screenshot 2022-01-31 101421](https://user-images.githubusercontent.com/71569839/151826865-e2ea0f1e-74cd-41e3-9cdb-67400c5e33c8.png)

The same code works fine when executed in Next.js app getServerSideProps function.

As the error suggested, I tried configuring @rollup/plugin-commonjs by going by the instructions I found in the docs here https://docs.directus.io/extensions/creating-extensions/#configuring-the-cli :

![Screenshot 2022-01-31 110535](https://user-images.githubusercontent.com/71569839/151835752-9fe55307-2408-4f91-998d-f24746e769d3.png)

With this config, the previous error is gone but I get a different one:
![Screenshot 2022-01-31 110648](https://user-images.githubusercontent.com/71569839/151833432-185b60e2-85f0-43fb-ae2d-3642def2d183.png)

### To Reproduce

1. `npm init directus-extension` -> hook -> typescript -> name: _custom-hook_
2. `npm init directus-project example-project` -> sqlite/postgres
3. Change @directus/extensions-sdk and directus package versions from 9.5.0 to 9.4.3 because of #11275 
4. `cd custom-hook` `npm install plaiceholder`
2. _import getPlaiceholder_ function inside _src/index.ts_ and _console.log_ it inside any of the hooks (as shown in the first image in Describe the Bug section).
3. Build extension with `npm run build`
4. Copy _index.js_ from _dist_ folder into Directus app at _example-project/extensions/hooks/custom-hook/_
5. npx directus start

### Errors Shown

![Screenshot 2022-01-31 101421](https://user-images.githubusercontent.com/71569839/151837436-7bdabbcd-ef02-4690-82ee-129f94730460.png)
![Screenshot 2022-01-31 110648](https://user-images.githubusercontent.com/71569839/151837476-644490fb-00e7-47ee-8f14-dc73d5ec0252.png)

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

v16.13.1

### What database are you using?

Postgres 14.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying Directus?

running locally

**Comment by Lerado** [comment]
Same here

**Comment by rijkvanzanten** [comment]
Linear: [ENG-273](https://linear.app/directus/issue/ENG-273/registering-custom-hook-extension-fails-when-using-plaiceholder)

**Comment by rijkvanzanten** [comment]
I believe this is resolved with the switch to ESM and `plaiceholder` v3. Happy to reopen if not.
