### ISSUE TITLE
Problem with translation display

### ISSUE THREAD

**Issue by danieljwestman** [directus/directus#11385]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I can't figure out how to display a translated field in a M2A relation. It's just output `--`

In this case we have a collection `website_settings` with field(alias) `navigation` which is a M2A relation to the two collections `navigation_dropdown` and `navigation_link`. It's a simple menu builder. We want to see "Dropdown Title" (and corresponding "Link Title") as a display in `navigation`, nothing special with that...

![Skärmavbild 2022-02-02 kl  06 43 50](https://user-images.githubusercontent.com/20950568/152118160-fce7d703-47fa-4d26-8d22-4d7a673f4149.png)

![Skärmavbild 2022-02-02 kl  06 40 13](https://user-images.githubusercontent.com/20950568/152118142-868a1de4-07c4-4612-af84-626fcaadcbf4.png)

Please advise 🙏🏼

### To Reproduce

Follow the images above. 

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

16 / 17

### What database are you using?

PG 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally / NPM

**Comment by licitdev** [comment]
Thank you @danieljwestman for your report. As translations are based on M2M relationships, it is currently not possible to retrieve the translated fields within.

**Comment by danieljwestman** [comment]
Ouch... We have a lot of m2a / m2m with collections including almost every field translatable... There will be a lot of `--`

**Comment by danieljwestman** [comment]
This is the one I talked about @benhaynes 👋🏼

**Comment by danieljwestman** [comment]
I would say this is a bug right? Not a new feature...

Would it be possible to know if this will be fixed in the near future, maybe together with some other work on the translations (@benhaynes have mentioned this)?

**Comment by danieljwestman** [comment]
Yes, I understand. What meant was basically if this issue is being worked on at the moment, maybe in some other type of feature/fix.

But okay, I have a workaround: add a field like `display_me` in the root collection and a build hook that populates this field with the translated value each time you hit save. Far from perfect, but it could work for now.

**Comment by benhaynes** [comment]
Gotcha. We have some big things in the works that are slowing down Core/Bug resolution (as people may have noticed). Once those are released/announced in the next 1-2 weeks, then we'll be really pushing these fixes. Until then, the triage and fixes are up to what the devs think are high priority or within their capabilities.

**Comment by rijkvanzanten** [comment]
@iksent Your example wouldn't work, as Translations > Name is not a single value that can be displayed. `Translations` is a one to many type relationship, which means that the `Name` field is a list of values. There's currently no way to render that as an inline value like you're trying.

In this case, I would highly recommend using the `Translations` field in there instead of `Translations > Name`, and configuring the `Translations` field with the `translations` display, which will render the configured translations template in the user's current language, with a dropdown to see previews of the other values 👍🏻

**Comment by iksent** [comment]
@rijkvanzanten, thanks for your recommendations! Unfortunately, this didn't work for me:

`Article` > `categories` field config:

![image](https://user-images.githubusercontent.com/32956521/154788901-b3873682-cdd0-4f94-8e36-2306be328054.png)

![image](https://user-images.githubusercontent.com/32956521/154788917-7c0dbdf9-1766-43fa-bc26-bf42b373fbd2.png)

`Category` translates config:

![image](https://user-images.githubusercontent.com/32956521/154789158-385279c6-4a45-4e0d-8d7f-c351d6800d73.png)


**Result:**

1) Table:

![image](https://user-images.githubusercontent.com/32956521/154788951-e1021b42-3e0c-427b-b189-6f0e3a8e0e0a.png)

2) Inside Article creation/editing:

![image](https://user-images.githubusercontent.com/32956521/154788971-4fd3f104-da74-4913-9e35-2902e4799aa7.png)

**Comment by LazyBun** [comment]
@rijkvanzanten I've tried this solution and got the same result as @iksent. Directus version: `9.5.2`

**Comment by sepios87** [comment]
Same problem here :/

**Comment by LazyBun** [comment]
@rijkvanzanten  On version `9.7.0` the displaying of translations via the method you've described (`using the Translations field in there instead of Translations > Name, and configuring the Translations field with the translations display`) seems to work :)

There is however another issue I've noticed. I have not seen any other issue that would describe it, so I've created [a new one](https://github.com/directus/directus/issues/12270). Apologies in advance if it's a duplicate.

**Comment by sepios87** [comment]
Hello, I have almost a similar problem with the title of entities : 
https://github.com/directus/directus/issues/12270#issuecomment-1074890890

**Comment by ArtemAstakhov** [comment]
@rijkvanzanten 
Looks like the issue with translations still exists in version 9.17.0

![изображение](https://user-images.githubusercontent.com/18442991/188382215-3ad8c51c-c82c-40a3-9c17-9507c75b6783.png)

**Comment by Nitwel** [comment]
Could you provide more information about your setup as I just tried it again and it's still working?

**Comment by ArtemAstakhov** [comment]
sure

we have builder_info entity with translations
![изображение](https://user-images.githubusercontent.com/18442991/188401038-8865dbf8-5d79-4871-950b-c93b52c5fb02.png)

this translation field has such display
![изображение](https://user-images.githubusercontent.com/18442991/188401400-bf1ea0d8-2a54-4a0a-bb6d-0826787afa30.png)

then we set up translation field as display template for builder_info
![изображение](https://user-images.githubusercontent.com/18442991/188401591-b9c6c499-4990-4a43-b971-d9cf392e8134.png)

then we use this build_info as part of m2a relationship
![изображение](https://user-images.githubusercontent.com/18442991/188401807-5cee8dc2-7aa3-42d9-96e5-3e1f4f16ffd9.png)

**Comment by ArtemAstakhov** [comment]
oh, this way didn't work before :)
seams that now it looks good, I'll test it more

thank you very much
