### ISSUE TITLE
Date picker does not allow to select years earlier than 100

### ISSUE THREAD

**Issue by abdonrd** [directus/directus#11398]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Using the date picker, I try to set the year field to an old year, but it does not allow it.
I have tried with <kbd>Enter</kbd>, <kbd>Tab</kbd>, clicking, ... But it backs to the current year.

Video example:

https://user-images.githubusercontent.com/1007051/152196196-1ccd65df-109e-4583-a084-2507c6c144fb.mov

### To Reproduce

Create a date field and try to set an old year, like `899`.

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

16.13.0

### What database are you using?

SQLite

### What browser are you using?

Chrome

### What operating system are you using?

macOS Monterey (12)

### How are you deploying Directus?

Running locally

**Comment by azrikahar** [comment]
Can you try the following steps? I agree it's not ideal, but it seems to work on my end:

1. Change the year
2. Press "Enter". The day selection should be empty
3. Select a day

May need to investigate this on Flatpickr side since when I tested the [pure Flatpickr examples](https://flatpickr.js.org/examples/), this behavior is the same so it's not technically an issue on our wrapper datepicker.

**Comment by abdonrd** [comment]
> Can you try the following steps? I agree it's not ideal, but it seems to work on my end:
> 
> 1. Change the year
> 2. Press "Enter". The day selection should be empty
> 3. Select a day

It works for me if the number is >=100.
If the number is <100... It appends `19`, so when I set 25, changes to 1925.

**Comment by azrikahar** [comment]
Seems like this "rounding up of years" is happening in Flatpickr as well. If you try this at the Flatpickr examples page linked above, you should see the same interaction.

**Comment by LuizHAP** [comment]
This datepicker is very strange, I need to hit enter for it to work. It should work on mouse out too

**Comment by rijkvanzanten** [comment]
I'll close this in favor of the one tracked on the flatpickr repo: https://github.com/flatpickr/flatpickr/issues/1492
