### ISSUE TITLE
Button within accordion renders as its own accordion

### ISSUE THREAD

**Issue by supermx1** [directus/directus#11408]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

https://user-images.githubusercontent.com/9326922/152308789-92eabfc5-7b2b-4395-8c2d-928b20c1b622.mp4

### To Reproduce

See above

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

16

### What database are you using?

MySQL

### What browser are you using?

Chrome, Brave

### What operating system are you using?

MacOS, Ubuntu 20.08LTS

### How are you deploying Directus?

Locally

**Comment by licitdev** [comment]
@supermx1 An immediate fix is to wrap the two half-width fields within a `Raw Group` interface as shown below.

![Screenshot 2022-02-03 at 6 22 53 PM](https://user-images.githubusercontent.com/26413686/152324772-680fced0-365c-4883-b020-d51e1073ad3e.png)

![Screenshot 2022-02-03 at 6 23 04 PM](https://user-images.githubusercontent.com/26413686/152324758-6470c6ea-3ef9-46b2-a3c8-9c4fef574cfb.png)

However with the above fix, there will be two titles for the "field group" within the accordion.

@benhaynes Any thoughts?

**Comment by benhaynes** [comment]
I believe this is how our Accordions work, each child (field or group) is a section... so you would use Raw Groups to create the expanding items and control their names. @rijkvanzanten right?

**Comment by rijkvanzanten** [comment]
Correct! This is working as expected. Every field in an accordion group becomes a section in the accordion. You can use a raw group field to nest multiple other fields in a single accordion section 👍🏻
