### ISSUE TITLE
Ability to add custom widgets (to listing page header)

### ISSUE THREAD

**Issue by iamamused** [directus/directus#1140]
Is there an easy way in the framework for an extension to add a button to the left tor right navigation on the table pages? For example, I'd like to add an "export" button next to the filter button which would run a script in my extension for that particular table. I see the buttons are based on widgets but there doesn't seem to be a way to include additional widgets from an extension.

**Comment by benhaynes** [comment]
Yes, there are multiple ways to adjust the left nav bar, but it to get total control you can use this:

https://github.com/directus/docs/blob/master/04-developer/03-configuration.md#customizing-the-sidebar-navigation-for-user-groups

*You can also add them individually for users (working on a global option for this):*

**Table:** `directus_bookmarks`
This table stores all of the left-nav bookmarks for Directus. This includes bookmarks that users create as well as the "System" bookmarks at the bottom. Each record is assigned to a specific user.

* `user` - [Directus user id] This assigns the bookmark to a specific user (there's a ticket to allow for "global" bookmarks using `NULL`)
* `title` - The text to display in the navigation menu
* `url` - The path to navigate to when clicked, relative to the Directus root
* `icon_class` - Deprecated
* `section` - ["search" or "other"] Which nav section to show the link within. User generated bookmarks use "search", while all system links go within "other"

**Comment by benhaynes** [comment]
Reading through your comment again, I see you're asking about adding it to the nav on the Item Listing page. I don't know if there's an easy way to do this, but one way to look into would be creating a custom Item Listing view template (using the default as a boilerplate):

https://github.com/directus/docs/blob/master/04-developer/07-folder-and-file-guide.md#listviews

This is overkill, but should get the job done. Otherwise you'd have to fork and tweak the Directus Core code itself – take a look here to see that code:

`/app/core/widgets/` (eg: FilterWidget.js)

**Comment by benhaynes** [comment]
**[Migrated to FeatHub](http://feathub.com/directus/directus/+26)**

Please use the [Directus FeatHub](http://feathub.com/directus/directus) to vote for features or make new request. Accepted feature requests will be added to GitHub Issues.

**Comment by kondzina** [comment]
Any changes here? I want to add language dropdown widget near filter widget on the right top. Is any way to do this using custom/... place? Nothing works for me.

**Comment by rijkvanzanten** [comment]
Hey @kondzina! 

The left sidebar nav is the only user configurable place in directus 6. I am happy to announce that 7.0 _will_ have support for custom listing views _and_ custom markup in the header bar as well. Seeing that the (small) core team is working full time one this next major version (scheduled for RC in 8-10 weeks), this won’t be added in 6.x. Thanks for your understanding and as anytime, feel free to open a PR to 6 if you wanna take a swing at implementing it yourself 😊

**Comment by kondzina** [comment]
@rijkvanzanten - thanks for your replay! Ah, bad news. But maybe I will implement it. I mean the possibility to modify topbar widgets/elements. What is the right branch with current works on version 6?

**Comment by rijkvanzanten** [comment]
The most up to date is the `development` branch. If you're planning on implementing new features to PR, I'd recommend using that branch 👍
