### ISSUE TITLE
Install config.php

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1141]
The text to copy manual config details is empty – and the `Config Writable (../api/config.php)` is showing NO despite being writable (777).

![screen shot 2016-04-06 at 11 59 08 am](https://cloud.githubusercontent.com/assets/522079/14323610/2a6c3264-fbef-11e5-85aa-cf26addd419e.png)

**Comment by benhaynes** [comment]
I finished and it wrote the the file fine, even though it said it didn't have write permission on this page

**Comment by WellingGuzman** [comment]
@benhaynes Which server specifications were you on? and which brand/version did you use?

**Comment by benhaynes** [comment]
To install, I ran: `git clone https://github.com/directus/directus.git directus`

Server:
2 GB Memory / 40 GB Disk / NYC3 - Ubuntu 14.04.4 x64

**Comment by WellingGuzman** [comment]
@benhaynes what user owns `directus` directory? this maybe happening because the owner could be different from the web server user.

can you tell what are the user owner by running this: _Second and third column_

```
$ ls -l directus
# And
$ ls -l directus/api
```

**Comment by benhaynes** [comment]
```
$ ls -l directus
total 1708
drwxr-xr-x 7 root root    4096 Apr  6 11:58 api
drwxr-xr-x 8 root root    4096 Apr  6 10:22 app
drwxr-xr-x 7 root root    4096 Apr  6 10:22 assets
drwxr-xr-x 2 root root    4096 Apr  6 10:22 bin
-rwxr-xr-x 1 root root 1592980 Apr  6 11:31 composer.phar
drwxr-xr-x 3 root root    4096 Apr  6 10:22 extensions
-rw-r--r-- 1 root root   35179 Apr  6 10:22 gpl.md
-rw-r--r-- 1 root root    8367 Apr  6 10:22 gulpfile.js
-rw-r--r-- 1 root root   11767 Apr  6 10:22 index.php
drwxr-xr-x 2 root root    4096 Apr  6 10:22 installation
-rw-r--r-- 1 root root    1748 Apr  6 10:22 karma.conf.js
-rw-r--r-- 1 root root     649 Apr  6 10:22 LICENSE.md
drwxr-xr-x 2 root root    4096 Apr  6 10:22 listviews
-rw-r--r-- 1 root root    7530 Apr  6 10:22 login.php
-rw-r--r-- 1 root root    3926 Apr  6 10:22 main.html
drwxrwxrwx 3 root root    4096 Apr  6 10:22 media
drwxr-xr-x 3 root root    4096 Apr  6 10:22 media_auth_proxy
-rw-r--r-- 1 root root    1168 Apr  6 10:22 package.json
-rw-r--r-- 1 root root     108 Apr  6 10:22 phpunit.php
-rw-r--r-- 1 root root     248 Apr  6 10:22 phpunit.xml
-rw-r--r-- 1 root root    4503 Apr  6 10:22 readme.md
-rwxr-xr-x 1 root root     529 Apr  6 10:22 runtests.sh
-rw-r--r-- 1 root root     846 Apr  6 10:22 test-main.js
drwxr-xr-x 4 root root    4096 Apr  6 10:22 tests
drwxr-xr-x 2 root root    4096 Apr  6 10:22 ui
```

and ...

```
$ ls -l directus/api
total 1708
-rw-r--r--  1 root root   53023 Apr  6 10:22 api.php
-rw-r--r--  1 root root     465 Apr  6 10:22 composer.json
-rw-r--r--  1 root root   29576 Apr  6 11:33 composer.lock
-rwxr-xr-x  1 root root 1592980 Apr  6 11:33 composer.phar
-rwxrwxrwx  1 root root    1779 Apr  6 12:01 config.php
-rw-r--r--  1 root root    1769 Apr  6 10:22 config_sample.php
-rwxrwxrwx  1 root root    2471 Apr  6 12:01 configuration.php
-rw-r--r--  1 root root    2398 Apr  6 10:22 configuration_sample.php
drwxr-xr-x  3 root root    4096 Apr  6 10:22 core
-rw-r--r--  1 root root      44 Apr  6 10:22 globals.php
drwxrwxrwx  3 root root    4096 Apr  6 12:01 logs
drwxr-xr-x  3 root root    4096 Apr  6 10:22 migrations
-rw-r--r--  1 root root    1750 Apr  6 10:22 ruckusing.conf.php
-rw-r--r--  1 root root   17169 Apr  6 10:22 schema.sql
drwxr-xr-x 11 root root    4096 Apr  6 11:33 vendor
drwxr-xr-x  3 root root    4096 Apr  6 10:22 views
```

**Comment by WellingGuzman** [comment]
is there a way that I can replicate this? I'm thinking php is running with `www-data` user which doesn't have permission over `root` files.

**Comment by benhaynes** [comment]
When you install, do you get the `copy config text` text area?

**Comment by WellingGuzman** [comment]
yes, I always get that text, so I'm concern about how didn't you get it.

**Comment by benhaynes** [comment]
Yeah, I NEVER get the config text in that text area. Are you using `build`? I am using the default branch (developer?)

**Comment by incraigulous** [comment]
This exact same thing is happening to me as well. It says config isn't writable and the box is empty.

**Comment by WellingGuzman** [comment]
@incraigulous can you help me replicate the issue, I've tried different things so far without any luck.

What Directus version and OS are you using?

**Comment by WellingGuzman** [comment]
@incraigulous does the web-server user has permissions to read/write the Directus directory?

**Comment by incraigulous** [comment]
Looks like that was the issue. I know not to do this in production, but since I’m just taking it for a test drive on my standing server, I set the whole project to 777. It worked!

Craig

**Comment by WellingGuzman** [comment]
@incraigulous setting to 775 should works too. avoid using 777 on production. 

What OS is your production server? if you are using a linux, you can change permissions using `chmod` command and change owner using `chown` command.

**Comment by incraigulous** [comment]
Great thx. Ill make note of that. It's AWS CentOs.

**Comment by WellingGuzman** [comment]
So I will call it permission issue. solution worked for @incraigulous 

If this still happening to someone let us know and I will open this ticket again.
