### ISSUE TITLE
Wrong storage of UUIDs when creating new M2A items

### ISSUE THREAD

**Issue by cs-jbe** [directus/directus#11417]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

We have a collection that has a child collection as a M2A relationship.
When adding new items to the child collection using the "Create New" button in the parent collection, the UUID of the newly created item is stored as a lowercase UUID in the relationship table. If you add an item with "Add Existing" instead, the UUID will be stored uppercase in the relationship table.
![image (2)](https://user-images.githubusercontent.com/86365077/152395731-fa36df96-a44b-430c-a4df-70fd42e5ab50.png)

All items that are stored with a lowercase UUID in the relationship table cannot be edited via the parent collection. If you open such a new created item for editing, all fields remain empty.
![image](https://user-images.githubusercontent.com/86365077/152396187-11fb0f20-c9c6-4385-9ea9-7a7d7b6908fb.png)
![image](https://user-images.githubusercontent.com/86365077/152401398-77b082a4-e5ae-484d-9796-5c42b37bfe97.png)

This and similar behavior is also described in other issues. As soon as you edit all UUIDs in the relationship table to uppercase they are editable in Directus again.

We suspect that either the "Create New" button stores wrong UUIDs or an internal filter does not filter them correctly. 

### To Reproduce

Create tables "Movies" and "Actors". Add a M2A relationship to the "Movies" table referencing the "Actors" table.
![Animation8](https://user-images.githubusercontent.com/86365077/152401215-79641195-a770-4440-98fa-b27a2588da70.gif)

### Errors Shown

No errors shown.

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

Directus Docker Image

### What database are you using?

Azure SQL (MSSQL latest stable)

### What browser are you using?

Chrome (97), Edge

### What operating system are you using?

Local Windows / Azure Linux

### How are you deploying Directus?

(Azure + Local) Docker

**Comment by rijkvanzanten** [comment]
Linear: [ENG-271](https://linear.app/directus/issue/ENG-271/wrong-storage-of-uuids-when-creating-new-m2a-items)

**Comment by azrikahar** [comment]
I believe this is actually the same issue reported in #16671, especially since both are MS SQL specific and the same "symptom" of lowercased UUID(s) in M2A junction table. Since #16691 has resolved it, marking this as resolved as well 👍
