### ISSUE TITLE
Deleting Sort field from a Collection containing a Tree-View field tries to Drop the collection when it contains data

### ISSUE THREAD

**Issue by Pachat** [directus/directus#11425]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

With Data in a collection with a Tree-View, deleting Sort tries to Drop the collection

### To Reproduce

1. Create a collection `test_collection` with fields `sort`, `name` (Input), `tree_key` (Tree-View) on `test_collection` with `tree_foreign_key` as Foreign Key
2. Add 2 items with the second one in tree with the first one
3. Delete the field `sort`
4. BUG:  DROP TABLE "test_collection" - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed
5. Delete all items
6. Delete the field `sort`: OK.

### Errors Shown

 DROP TABLE "test_collection" - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

14.17.1

### What database are you using?

SQLite version 3.37.0

### What browser are you using?

Firefox

### What operating system are you using?

Windows_NT 10.0.19043

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
Along with #12566, closing this in favor of tracking this SQLite foreign key issue in #10842.
