### ISSUE TITLE
RuntimeException - This query failed: SELECT `directus_tables`.* FROM `directus_tables`

### ISSUE THREAD

**Issue by vhexs** [directus/directus#1143]
## Version Info
  - Directus version: [11889d1](https://github.com/directus/directus/commit/11889d14d3da97d77c4aaaf0366a3769da804c60)
  - PHP version: 5.6.15
  - MySQL version: 5.7.9
  - Web server: Apache 2.4.17
  - OS name and version: Windows 7 32bit

## Expected Behavior
Loading home page after installation

## Actual Behavior
Get the following on my page (not in a log):

```
{
  "code":0,
  "class":"RuntimeException",
  "message":"This query failed: SELECT `directus_tables`.* FROM `directus_tables`",
  "file":"C:\\wamp\\www\\SparkWare-Website-wordpress\\directus\\api\\core\\Directus\\Db\\TableGateway\\AclAwareTableGateway.php",
  "line":486,
  "trace":[
    {
      "file":"C:\\wamp\\www\\SparkWare-Website-wordpress\\directus\\api\\vendor\\zendframework\\zend-db\\src\\TableGateway\\AbstractTableGateway.php",
      "line":208,
      "function":"executeSelect",
      "class":"Directus\\Db\\TableGateway\\AclAwareTableGateway",
      "type":"->",
      "args":[
        {
          
        }
      ]
    },
    {
      "file":"C:\\wamp\\www\\SparkWare-Website-wordpress\\directus\\api\\vendor\\zendframework\\zend-db\\src\\TableGateway\\AbstractTableGateway.php",
      "line":195,
      "function":"selectWith",
      "class":"Zend\\Db\\TableGateway\\AbstractTableGateway",
      "type":"->",
      "args":[
        {
          
        }
      ]
    },
    {
      "file":"C:\\wamp\\www\\SparkWare-Website-wordpress\\directus\\api\\core\\Directus\\Bootstrap.php",
      "line":259,
      "function":"select",
      "class":"Zend\\Db\\TableGateway\\AbstractTableGateway",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"C:\\wamp\\www\\SparkWare-Website-wordpress\\directus\\api\\core\\Directus\\MemcacheProvider.php",
      "line":113,
      "function":"Directus\\{closure}",
      "class":"Directus\\Bootstrap",
      "type":"::",
      "args":[
        
      ]
    },
    {
      "file":"C:\\wamp\\www\\SparkWare-Website-wordpress\\directus\\api\\core\\Directus\\Bootstrap.php",
      "line":262,
      "function":"getOrCache",
      "class":"Directus\\MemcacheProvider",
      "type":"->",
      "args":[
        "directus_tables",
        {
          
        },
        1800
      ]
    },
    {
      "function":"acl",
      "class":"Directus\\Bootstrap",
      "type":"::",
      "args":[
        null
      ]
    },
    {
      "file":"C:\\wamp\\www\\SparkWare-Website-wordpress\\directus\\api\\core\\Directus\\Bootstrap.php",
      "line":40,
      "function":"call_user_func",
      "args":[
        "Directus\\Bootstrap::acl",
        null
      ]
    },
    {
      "file":"C:\\wamp\\www\\SparkWare-Website-wordpress\\directus\\api\\api.php",
      "line":125,
      "function":"get",
      "class":"Directus\\Bootstrap",
      "type":"::",
      "args":[
        "acl"
      ]
    },
    {
      "file":"C:\\wamp\\www\\SparkWare-Website-wordpress\\directus\\index.php",
      "line":13,
      "args":[
        "C:\\wamp\\www\\SparkWare-Website-wordpress\\directus\\api\\api.php"
      ],
      "function":"require"
    }
  ],
  "traceAsString":"#0 C:\\wamp\\www\\SparkWare-Website-wordpress\\directus\\api\\vendor\\zendframework\\zend-db\\src\\TableGateway\\AbstractTableGateway.php(208): Directus\\Db\\TableGateway\\AclAwareTableGateway->executeSelect(Object(Zend\\Db\\Sql\\Select))\n#1 C:\\wamp\\www\\SparkWare-Website-wordpress\\directus\\api\\vendor\\zendframework\\zend-db\\src\\TableGateway\\AbstractTableGateway.php(195): Zend\\Db\\TableGateway\\AbstractTableGateway->selectWith(Object(Zend\\Db\\Sql\\Select))\n#2 C:\\wamp\\www\\SparkWare-Website-wordpress\\directus\\api\\core\\Directus\\Bootstrap.php(259): Zend\\Db\\TableGateway\\AbstractTableGateway->select()\n#3 C:\\wamp\\www\\SparkWare-Website-wordpress\\directus\\api\\core\\Directus\\MemcacheProvider.php(113): Directus\\Bootstrap::Directus\\{closure}()\n#4 C:\\wamp\\www\\SparkWare-Website-wordpress\\directus\\api\\core\\Directus\\Bootstrap.php(262): Directus\\MemcacheProvider->getOrCache('directus_tables', Object(Closure), 1800)\n#5 [internal function]: Directus\\Bootstrap::acl(NULL)\n#6 C:\\wamp\\www\\SparkWare-Website-wordpress\\directus\\api\\core\\Directus\\Bootstrap.php(40): call_user_func('Directus\\\\Bootst...', NULL)\n#7 C:\\wamp\\www\\SparkWare-Website-wordpress\\directus\\api\\api.php(125): Directus\\Bootstrap::get('acl')\n#8 C:\\wamp\\www\\SparkWare-Website-wordpress\\directus\\index.php(13): require('C:\\\\wamp\\\\www\\\\Spa...')\n#9 {main}"
}
```

## Steps to Reproduce
 1. Copy files to server
 2. Run through installation with correct data
 3. Voila

## Logs or Screenshots
See above

The table `directus_tables` doesn't exist and wasn't automatically created.

**Comment by WellingGuzman** [comment]
Hi @vhexs I've tried to reproduce this issue using almost your setup except windows 7 64bit, and I couldn't replicate.

So I have some questions:
- Which tables did Directus created?
- What's your `api/config.php` file like?
- Are you using Directus under a subdirectory in your host/virtual host?

I'd like to help you resolve this.

**Comment by WellingGuzman** [comment]
Another question, is `NO_ZERO_DATE` or `NO_ZERO_IN_DATE` enabled in MySQL modes?

You can check by execute one of these query:
```sql
SELECT @@GLOBAL.sql_mode;
SELECT @@SESSION.sql_mode;
```

Or perhaps in your mysql config file (**my.ini**).

**Comment by vhexs** [comment]
@WellingGuzman Sorry for my late reply, my GitHub notifications are full of things I need to stop watching. 

Directus created the following tables:

- directus_activity
- directus_bookmarks
- directus_columns
- directus_files
- directus_groups
- directus_schema_migrations

I ended up deleting Directus from my project directory, so I'll quickly reinstall it and see if anything's changed (and so I can post the config file if it doesn't).

**Comment by WellingGuzman** [comment]
@vhexs What happened here is that if mysql has `ZERO_IN_DATE` enabled it doesn't allow zeros in dates.

It was fixed by https://github.com/directus/directus/commit/62176ac6a68764153201193f65b8668e6fe09b26 and https://github.com/directus/directus/commit/0b25ca1ef5f0061856aedb9338aa73820e8cedcf

**Comment by vhexs** [comment]
@WellingGuzman Thanks for fixing it! I'll update to the new version now :+1:

**Comment by DaveBlooman** [comment]
@WellingGuzman I just tried a fresh install of Directus from the latest release tag and getting this issue with AWS RDS MySQL.

**Comment by WellingGuzman** [comment]
Hey @DaveBlooman, can please send me any logs, _if any_, on `api/logs`?

Are the rest of the table created? `directus_*` (What are all the tables prefixed with it)

**Comment by DaveBlooman** [comment]
@WellingGuzman I resolved my issue.  For some reason, when supplying a config.php, it creates an error, but if you leave that file out, run the provisioning via the web UI, it works fine, even though the same file is output.  

My use case is that I build Amazon Machine Images with code already in, this was the first time i tried the AMI with a new fresh database.  I guess there is something for the docs, always run through the web UI with a new database, or provision the database first.

**Comment by WellingGuzman** [comment]
Hey @DaveBlooman,

What was the actual problem, I didn't get it. So you meant that you created the `config.php` and `configuration.php` manually and it didn't work until you created Directus using the installer?

How did you create all the core tables, such as `directus_tables`?

I'd love to see what was the actual issue.

**Comment by DaveBlooman** [comment]
I had previous done a setup of Directus in an AWS account by going through the web installer.  Once I knew what files i needed, i automated the process and bake amazon images.  I attempted to use the existing image with a new database.  This didn't work, so i assumed it must be the config.php existence causes Directus to assume a bunch of things, the DB has everything setup for example.  

I guess I should have a step to setup the DB before Direcuts attempts to start, but i don't intend to setup a third CMS right now.
