### ISSUE TITLE
Schema Cache doesn't get flushed after successful schema snapshot apply while Directus is running

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#11436]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When applying a schema snapshot while Directus itself is running on the same database, the schema cache doesn't get flushed properly, causing in unexpected errors / missing fields on the currently running Directus instance.

### To Reproduce

Have a running instance of Directus, apply a schema snapshot from a secondary process.

### Errors Shown

n/a

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16

### What database are you using?

postgres 13

### What browser are you using?

safari

### What operating system are you using?

macos

### How are you deploying Directus?

n/a

**Comment by azrikahar** [comment]
Have indeed came across this in the past after applying a schema via `docker exec <container-name> npx directus schema apply ./path/to/schema.yaml`. Restarting the container does resolve it.
