### ISSUE TITLE
Support Nested Translations

### ISSUE THREAD

**Issue by bitbot-rafa** [directus/directus#11440]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Nested translations interfaces do not load translated values.

Doubly-translated items are created but not loaded upon saving & editing.

### To Reproduce

1. Create two collections to translate with:
    - **languages** with `code` and `name` fields
    - **audiences** with `key` and `name` fields
2. Create **pages** collection
    - Create `audiences` translation field in **pages**: **pages_audiences**
        - Create `languages` translation field in **pages_audiences**: **pages_audiences_translations**
3. Fields within **pages_audiences_translations** are created but not loaded

### Creating a page
![creating-audienced-translated-page](https://user-images.githubusercontent.com/6913610/152605025-870539ef-2a35-4a45-9687-3ae233e46c74.jpg)

### Viewing the created page
![viewing-audienced-translated-page](https://user-images.githubusercontent.com/6913610/152605239-583d9531-d85e-45fe-848a-ff0d598de9a7.jpg)

### Errors Shown

None that I can tell, but this seems to occur because an ID is queried as null for the nested translation items.

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16.13.1

### What database are you using?

MariaDB 10.4.21

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment]
This slightly seem similar to #7613, albeit it doesn't have nesting like in this case. @rijkvanzanten is this something actively supported, or more of a schema modeling situation? 🤔

**Comment by bitbot-rafa** [comment]
For what it's worth, we were successfully utilizing this approach in [V8](https://github.com/directus/v8-archive). 😃

![image](https://user-images.githubusercontent.com/6913610/153263255-7b2580f5-dd99-42f4-ae9c-53c3d6c6f4ec.png)

**Comment by bitbot-jon** [comment]
Is this a supported feature in Directus? Or just a happy accident in V8?

We would like to migrate to V9, but unfortunately this is a critical-path functionality for us. 😞
