### ISSUE TITLE
Proper Error for "File Too Large"

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1144]
Getting an error when uploading a large file to Directus. It SHOULD go through (but take a while) ... but if it is going to fail, the error should not be formatted like this:

![screen shot 2016-04-18 at 4 14 32 pm](https://cloud.githubusercontent.com/assets/522079/14618503/d9f4f744-0580-11e6-91b9-0302072e1202.png)

**Comment by benhaynes** [comment]
Is this the new error message?

![screen shot 2016-08-09 at 8 37 32 pm](https://cloud.githubusercontent.com/assets/522079/17538184/271efdf0-5e71-11e6-9699-12767eedb346.png)

* Can we capitalize "Error"?
* Can we use our filesize convert function to turn these bytes into something more relatable? (KB/MB/GB)
* Are we providing a link or info on how to increase this? Even if it just says "Talk to your administrator about increasing this limit"

**Comment by benhaynes** [comment]
Also, is that the size of the file I'm uploading... or the max allowed? We need to clarify.

**Comment by WellingGuzman** [comment]
Yes, that's the new error message.

I'm aware of that, I skipped the style of it for later discussion.

>  is that the size of the file I'm uploading... or the max allowed?

That's the max allowed.

**Comment by benhaynes** [comment]
If we change the alert to this we can close it:

```
**Error**
This file exceeds the server's max file size of: 6.7MB
```

**Comment by benhaynes** [comment]
Perfect. I made an adjustment to the text so it fits on one line...
