### ISSUE TITLE
Image Field added to translations collection cannot be deleted

### ISSUE THREAD

**Issue by astelmack** [directus/directus#11473]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have created a collection that has a translations field added to it.
In the translations collection, I have added some text fields as well as a couple of image fields as I would like to have distinct images associated with the localized text fields.
However, I wanted to delete one of the image fields as it was not needed.  When I selected "delete item" from the menu and confirming, I received an error popup.

After the error, the image field I tried to delete from the translations collection still remained in the collection.  When I go to edit the content for the "Lessons" collection, the translations section is still showing the image field I tried to delete, however it seems like it is now just a plain text field and is no longer an image picker. 

### To Reproduce

* Add translations field to collection data model
* Edit collection_translations collection data model and add an image field
* Attempt to delete the added image field from the collection_translations collection data model

### Errors Shown

Popup error message:
`
{
  "errors": [
    {
      "message": "alter table \"Lessons_translations\" drop constraint \"lessons_translations_banner_image_foreign\" - constraint \"lessons_translations_banner_image_foreign\" of relation \"Lessons_translations\" does not exist",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
`

I am running this in a docker so I was also able to get the stack trace from the directus app container:

`
directus  | 09:02:42 🚨 error alter table "Lessons_translations" drop constraint "lessons_translations_banner_image_foreign" - constraint "lessons_translations_banner_image_foreign" of relation "Lessons_translations" does not exist 
directus  | error: alter table "Lessons_translations" drop constraint "lessons_translations_banner_image_foreign" - constraint "lessons_translations_banner_image_foreign" of relation "Lessons_translations" does not exist
directus  |     at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:287:98)
directus  |     at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
directus  |     at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
directus  |     at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:11:42)
directus  |     at Socket.emit (node:events:390:28)
directus  |     at addChunk (node:internal/streams/readable:315:12)
directus  |     at readableAddChunk (node:internal/streams/readable:289:9)
directus  |     at Socket.Readable.push (node:internal/streams/readable:228:10)
directus  |     at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
directus  | 09:02:42 ✨ request errored DELETE 500 /fields/Lessons_translations/banner_image 19ms
`

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16.13.2

### What database are you using?

Postgres 14.1

### What browser are you using?

Chrome

### What operating system are you using?

MacOSX Big Sur

### How are you deploying Directus?

Local Docker using the Directus Docker image

**Comment by azrikahar** [comment]
> I can't delete image field both from translations and **from model root:**

Based on this description alone, it should be the same problem. However your error message seems to lead to the `foreign_key_checks` in MySQL (hopefully that's your DB vendor in this case) where it doesn't allow dropping a column with a constraint by default. OP and the other linked issue just so happens to be both using PostgreSQL so this wasn't caught 😬
