### ISSUE TITLE
Markdown UI – JS not loaded on listing page

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1147]
@javiercf @WellingGuzman 

The new Markdown UI works properly on the edit page (where it loads the `marked.js` file), however on the item listing page, that JS file is not loaded but the marked function is still referenced:

https://github.com/directus/directus/blob/development/app/core-ui/markdown.js#L107

This therefore throws the error:

```
Uncaught SyntaxError: Unexpected token <
Uncaught TypeError: marked is not a function
```

We either need to load this marked js file on listing pages (could cause slight load/bloat), or we need to rewrite the `Module.list` code for that UI to not use the library.

**Comment by benhaynes** [comment]
@WellingGuzman you said you fixed this one?

**Comment by WellingGuzman** [comment]
@benhaynes yes, it's fixed.
