### ISSUE TITLE
filter on system date field: ER_WRONG_VALUE: Incorrect TIMESTAMP value: '[object Object]'

### ISSUE THREAD

**Issue by terion-name** [directus/directus#11480]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

date value in filter is not serialising properly (to [object Object])

<img width="1312" alt="Снимок экрана 2022-02-07 в 16 24 51" src="https://user-images.githubusercontent.com/1060205/152806666-8fa5afbd-535f-414d-b021-6442360b8e85.png">

### To Reproduce

Run query over any collection with default date fields (like `date_created`), something like:
```graphql
{
  products(filter: {
    date_created: { 
      _gte: "2022-02-0713:42:00", 
      _lte: "2022-02-07T13:42:59" 
    }
  }) {
    id
    slug
  }
}
```

### Errors Shown

```
select `products`.`id`, `products`.`slug` from `products` where (`products`.`date_created` = {\"_gte\":\"2022-02-0713:42:00\"}, {\"_lte\":\"2022-02-07T13:42:59\"}) order by `products`.`sort` asc limit 100 - ER_WRONG_VALUE: Incorrect TIMESTAMP value: '[object Object]'
```

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

v16.12.0

### What database are you using?

mysql

### What browser are you using?

brave

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by terion-name** [comment]
@azrikahar the error is not about filter combination and this syntax resolves nothing
<img width="1312" alt="Снимок экрана 2022-02-08 в 00 21 02" src="https://user-images.githubusercontent.com/1060205/152882036-69f1e9cb-db93-41d2-9f76-f18066395ac7.png">

**Comment by azrikahar** [comment]
@terion-name thanks for the follow up. It is indeed unfortunate that it's still returning error, but as we can observe from your latest error vs the previous error, the latest is the one with the more accurate query! The previous one was doing `date_created = { <json value here> }` inside SQL queries which is definitely not what we want. 👍 Reopening this for further investigations.

**Comment by azrikahar** [comment]
@terion-name just noticed your `_gte` value is actually missing a `T` in between, which is why it shows incorrect TIMESTAMP value. Can you confirm is that the issue in your case? Here's a test from my end (I'm using PostgreSQL hence the error message is slightly different):

https://user-images.githubusercontent.com/42867097/152921405-8c478c69-d3f9-47ac-840d-68a4936244ec.mp4
