### ISSUE TITLE
Directus User emails should be unique

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1150]
Currently you can add multiple users with the same email address... this should be checked during validation of the User/New form and within the database itself.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/e243db06017a71f8000bfce38724a8b017b4b8e9

**Comment by benhaynes** [comment]
This is a good database change –  but the interface isn't super clear still. When saving an email address with a duplicate value you get:

```Server Error
Statement could not be executed (23000 - 1062 - Duplicate entry 'ben@rngr.org' for key 'directus_users_email_unique')```

Can we add a custom error message for these errors? Token has the same message.

```
*Notice*
The "email" field must be unique – "ben@rngr.org" already exists within this table.
```

**Comment by benhaynes** [comment]
This is working great – and works for `token` too... 

We'll need to come back and replace the key_name with the column_name eventually...
