### ISSUE TITLE
M2O Relations can not be deleted

### ISSUE THREAD

**Issue by ngjoni** [directus/directus#11510]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

You can't delete the M2O relation field of a model anymore.

### To Reproduce

Create a M2O relation field in your model and delete it after creation. 

### Errors Shown

This shows an example from my directus instance. In this case the relation "black_list" can not be deleted from the "players" model.
![image](https://user-images.githubusercontent.com/49320058/152978789-bbfd7db7-63e4-4414-9000-f9d3f63cd095.png)

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

PaaS

**Comment by danieljwestman** [comment]
I can confirm this from my end to. Pretty annoying. A temporary workaround is to create a snapshot, edit it and then apply.

**Comment by azrikahar** [comment]
@ngjoni @danieljwestman May I know if this is only happening to M2O relations specifically, but not any other relations? Just wanted to be sure as I was only able to replicate this issue on M2O relations only.

**Comment by danieljwestman** [comment]
Only M2O for me

**Comment by ngjoni** [comment]
Only M2O.

**Comment by rashidpathiyil** [comment]
https://user-images.githubusercontent.com/15140041/154434968-8d41c4ce-22d8-484a-954d-9f89c653df90.mp4

![image](https://user-images.githubusercontent.com/15140041/154435731-f1af8b7d-8b6e-4a03-b154-a783051092bb.png)


Database: Cockroach DB
Directus: 9.5.1

**Comment by supermx1** [comment]
https://user-images.githubusercontent.com/9326922/156837335-fc43e851-6b76-4650-98b6-b3035aec795d.mp4

Database: MySQL
Directus: 9.5.2
Chrome
Digital Ocean

**Comment by martijn-dev** [comment]
Is there any update on this issue? I am still experiencing the issue on the latest v9.6.
In v9.5.0 there was no issue, so the bug is related to something that got changed from v9.5.0 to v9.5.1.

Database: PostgreSQL
Directus: 9.6.0
Chrome
running locally

**Comment by ngjoni** [comment]
Can anyone describe a "detail" workaround how to delete m2o relation? It's a crucial functionality 😅

**Comment by BartTactick** [comment]
> Can anyone describe a "detail" workaround how to delete m2o relation? It's a crucial functionality sweat_smile

you need to do it in the DB itself sadly.

**Comment by rasco** [comment]
Confirming this with Directus 9.6.0 and Postgres 13

**Comment by riscie** [comment]
I had this on a column with the type `image`. Just deleted it within the db manually now.
