### ISSUE TITLE
All datetime ago values in Firefox say "a few seconds ago"

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1152]
In Firefox *all* timeago values on the platform are printing as `a few seconds ago`

**Comment by WellingGuzman** [comment]
Hey @benhaynes can you describe or show me some screenshots and/or logs? most recent version all timeago are working as expected.

**Comment by benhaynes** [comment]
It's happening locally, and also on Hosted Instances

![screen shot 2016-04-26 at 8 37 19 pm](https://cloud.githubusercontent.com/assets/522079/14838398/ddff67ba-0bee-11e6-9f9b-b2d4f5b9d298.png)

**Comment by WellingGuzman** [comment]
@benhaynes I fixed this issue on firefox. can you confirm?

**Comment by benhaynes** [comment]
Can confirm – this is fixed on `master`

Thanks @WellingGuzman
