### ISSUE TITLE
Share items in sidebar are hidden by adblockers

### ISSUE THREAD

**Issue by azrikahar** [directus/directus#11532]
This is a follow up to #11277.

## Problem

Currently each individual share entries has the CSS class of `.share-item`:

![chrome_alfhqSdNcG](https://user-images.githubusercontent.com/42867097/153114023-22b681dd-5a44-4c99-9a1b-4268f114c8c3.png)
 
However one of a widely used filter (https://secure.fanboy.co.nz/fanboy-annoyance.txt) ended up catching this as a false positive and hides all the share entries, rendering the user unable to interact with them anymore:

![chrome_1Q7kNx6B05](https://user-images.githubusercontent.com/42867097/151077625-f21d9df1-aad0-4a81-97e9-398185762ed2.png)

## Solution

We'll need to change the class to something else since `share` and variations of it are blocked by privacy/adblock filters.

However we may also need to _somehow_ ensure that the new class will not get wrongly flagged by many other filters that exist out there. Just from the same "fanboy-annoyance" list linked above, it also looks for other classes such as:

<details>
<summary>Class List 1</summary>

![image](https://user-images.githubusercontent.com/42867097/153114612-474060e6-fa83-4df1-967e-e496204c4c07.png)

</details>

<details>
<summary>Class List 2</summary>

![image](https://user-images.githubusercontent.com/42867097/153114740-60f789e2-fc47-4c33-b34f-5db91281a403.png)

</details>

and there's more.

**Comment by benhaynes** [comment]
So annoying. I wish we could check if this is being hidden and throw an app notification about disabling the adblocker. I hate that we need to use a less accurate banning system because of this. 😠
