### ISSUE TITLE
Error with document `--yes` option for applying schema snapshots

### ISSUE THREAD

**Issue by iksent** [directus/directus#11537]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I believe there is an error at [documentation](https://docs.directus.io/reference/cli/#migrate-schema-to-a-different-environment) and no `true` required to make a snapshot

Related PR: https://github.com/directus/directus/pull/11356

### To Reproduce

Incorrect command: `npx directus schema snapshot --yes true ./snapshot.yaml`

![image](https://user-images.githubusercontent.com/32956521/153170692-f037e67c-f47c-45a2-ba40-60023279a500.png)

Correct command: `npx directus schema snapshot --yes ./snapshot.yaml` (no **true**)

![image](https://user-images.githubusercontent.com/32956521/153170537-36e32a35-dd22-4f12-855b-11d69faace1e.png)

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

14.17.5

### What database are you using?

MariaDB

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment]
Definitely in favor of using your suggested command, though I am slightly curious on whether it was what worked for @eyecatchup in their CI/CD workflow, or really just a documentation error. That said, @iksent would you like to make a PR for it? 🙂

**Comment by iksent** [comment]
I also think, that we need to get more information from @eyecatchup about this.

**Comment by eyecatchup** [comment]
Hey. Can confirm, this is a documentation error. Sorry for that! Created a PR to fix this. https://github.com/directus/directus/pull/11540

**Comment by azrikahar** [comment]
@eyecatchup thanks for such a quick response, and @iksent thanks for pointing this out 👍
