### ISSUE TITLE
Add custom embedded files links

### ISSUE THREAD

**Issue by WellingGuzman** [directus/directus#1154]
Directus should support customs embedded files links. right now Directus only expects links to be from YouTube or Vimeo.

Ex:
What if I want to embed SoundCloud links? A developer should be able to extend this by adding new supports.

**Comment by benhaynes** [comment]
I'm curious what the best way to implement this would be. Would/could/should this code exist within the file UI, or should we add it into the core so all UIs can use it? Also, we should agree on a good way to handle dependencies – some UIs will require other libraries and we want to make it easy to include those as needed.
