### ISSUE TITLE
An error occurs when deleting the user_created and user_updated fields

### ISSUE THREAD

**Issue by ngjoni** [directus/directus#11542]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

You can't delete the both fields user_created and user_updated anymore.

### To Reproduce

Go to your model with those generated fields and delete them.

### Errors Shown

user_created error:
```
{
  "errors": [
    {
      "message": "alter table \"currencies\" drop constraint \"currencies_user_created_foreign\" - constraint \"currencies_user_created_foreign\" of relation \"currencies\" does not exist",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

user_updated error:
```
{
  "errors": [
    {
      "message": "alter table \"currencies\" drop constraint \"currencies_user_updated_foreign\" - constraint \"currencies_user_updated_foreign\" of relation \"currencies\" does not exist",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16

### What database are you using?

PG 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

PaaS

**Comment by azrikahar** [comment]
Hi, they are actually M2O fields, so this issue is the exact same as the issue you have opened over here: #11510 😄

![chrome_X3IThpTFBV](https://user-images.githubusercontent.com/42867097/153184463-4cc41ad8-e0b9-4a77-8108-4d5f560b75df.png)

**Comment by ngjoni** [comment]
Didn't see that they also are M2O relations. Sorry 😅
