### ISSUE TITLE
Error on first login attempt

### ISSUE THREAD

**Issue by davidbwaters** [directus/directus#1155]
## Version Info
  - Directus version: 6.2.4
  - PHP version: 5.5.34
  - MySQL version: 5.7.12
  - Web server: Apache
  - OS name and version: OS X latest

Error after first login attempt.

Hey, I have an error that seems to be related to the 2 latest critical issues.  Here's my output.  I've tried all fixes from closed issues, triple checked Apache config, and passed all pre-install tests. I get a the 'Server Error' message and access shows error info.  Hope this helps. 

[directus-error.txt](https://github.com/directus/directus/files/253308/directus-error.txt)
![2016-05-07 at 1 34 am](https://cloud.githubusercontent.com/assets/5247627/15090412/3fa61dc0-13f5-11e6-84af-b76aa4f42b0a.png)

**Comment by WellingGuzman** [comment]
hey @davidbwaters thanks for reporting this, according to the error, you have `only_full_group_by` sql mode enabled, and there's a query not obeying this rule.

I will work on it. but if you want to solve this quick for the moment you can turn `only_full_group_by` mode off.

**Comment by WellingGuzman** [comment]
@davidbwaters on development branch right now I pushed what should fix the problem using `only_full_group_by`. this is going to be soon in a release soon.

Let me know if this works for you.

**Comment by WellingGuzman** [comment]
Still no problem after the wrong query group fix.

@davidbwaters if you find yourself having trouble with this let us know
