### ISSUE TITLE
Directus user interface issues

### ISSUE THREAD

**Issue by hektormisplon** [directus/directus#11618]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

There appear to be some issues with the Directus user interface using Brave browser. When using Firefox I don't have any problems. 

![image](https://user-images.githubusercontent.com/36757790/153780281-3f0622da-5520-4130-85ce-e94d75ae2a07.png)
![image](https://user-images.githubusercontent.com/36757790/153780521-fd45d917-c4df-4660-ac3e-9dbf29b4191e.png)

### To Reproduce

1. Run Directus docker image
2. Access the Directus UI from Brave browser

### Errors Shown

No errors.

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16.13.2

### What database are you using?

Default

### What browser are you using?

Brave

### What operating system are you using?

Linux

### How are you deploying Directus?

Docker

**Comment by Oreilles** [comment]
Are you by chance using any content blocker, or styling extension ?
Can you try and see if the issue is present in other chromium based browser such as Chrome or Edge ? If it isn't, and considering that there are no UI glitches on my end using Brave, Chrome and Firefox on macOS or Windows, I will close this issue as it seems very unlikely that this is a bug with Directus itself.

**Comment by jaycammarano** [comment]
> Are you by chance using any content blocker, or styling extension ? Can you try and see if the issue is present in other chromium based browser such as Chrome or Edge ? If it isn't, and considering that there are no UI glitches on my end using Brave, Chrome and Firefox on macOS or Windows, I will close this issue as it seems very unlikely that this is a bug with Directus itself.

Brave automatically blocks a lot of stuff. It's very likely that is the issue.

**Comment by hektormisplon** [comment]
I turned Brave Shields and extensions. My brave version was out of date, after updating the issues were resolved. This is indeed not a directus issue.
