### ISSUE TITLE
Wrong validation failure for required field of INT datatype Select UI

### ISSUE THREAD

**Issue by KailZhang** [directus/directus#1161]
As this is my first day trying directus, I found some problems, below is one

## Version Info
  - Directus version: (Or commit hash)
6.2.5
  - PHP version: 
5.5.21
  - MySQL version: 
5.6.2
  - Web server: (Ex. Apache, nginx or IIS?) 
Apache
  - OS name and version: 
OSX 10.11.2

## Expected Behavior
Pass validation without required message shown

## Actual Behavior
Validation failure message pops up, though the change is persisted

## Steps to Reproduce
 1. Add a new field with Data Type:INT, UI:Select
 2. Properly set options, like {"1":"abc", "2":"def"}
 3. Create or edit related item

It seems to be caused by _.isEmpty of select.js, which complains on numeric value. And I find that the validation is executed twice: first time failed, second time passed.

**Comment by WellingGuzman** [comment]
Hi @KailZhang I couldn't replicate your issue, what errors pops up? "field is required"? your MySQL server has modes enabled?

you can check them by executing one of these:

```sql
select @@global.sql_mode
-- or
select @@session.sql_mode
```

Are you leaving the field empty or pick an option from it? What's the structure of that field?

**Comment by KailZhang** [comment]
Error: "The field is required"
I don't know how mysql's mode is related to this. I set sql_mode to NO_ENGINE_SUBSTITUTION.
But the problem is still there

![2016-06-07 9 37 06](https://cloud.githubusercontent.com/assets/799942/15843331/fb09a36e-2c93-11e6-9b6d-0b828ee5574c.png)
![2015-07-21 11 19 01](https://cloud.githubusercontent.com/assets/799942/15843332/fbd125a6-2c93-11e6-815e-c9f4f0e50338.png)

**Comment by WellingGuzman** [comment]
> I don't know how mysql's mode is related to this.

@KailZhang now I know it doesn't have to do with that, I was asking as you didn't specified the correct error messages I was trying to get this out of the way, as some issues come from mysql modes.

Checking if a number is empty using `_.isEmpty`, it will always going to return false. that was causing the problem.

Thanks for reporting this and let us know if that works for you.
