### ISSUE TITLE
M2M Item has not existing items in the admin panel view

### ISSUE THREAD

**Issue by ngjoni** [directus/directus#11610]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

It shows several items, although they do not exist (anymore).  But if you update the m2m relation in the detail view, it will show the right amount of items.

### To Reproduce

Create a m2m between two collections and add some items in each collection. Go to collection A, select an item and go in detail, then put items from Collection B in Collection A. Go back to the same item and delete few items in the relation now. At the end go to Collection B and select the column with the item amount. Don't forget to set "display" and "interface" with ID or something else as attribute.

### Errors Shown

Here is a short demo:
https://user-images.githubusercontent.com/49320058/153723739-a53a576b-d809-4324-90da-a2e69b60c223.mov

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

v16

### What database are you using?

PG 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

PaaS

**Comment by Nitwel** [comment]
This seems to be all working fine. Make sure you configure your relational triggers properly on the m2m field.
![grafik](https://user-images.githubusercontent.com/22577866/157026296-6255d348-b2d1-4c02-a26c-68d4d73cc745.png)

If I understood the problem wrong feel free to reopen this issue again.
