### ISSUE TITLE
No permission to access admin profile page

### ISSUE THREAD

**Issue by mhdaouas** [directus/directus#11614]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I get the following error when I access the admin profile page:

> you don't have permission to access this.

When I logout/login, the problem is solved.

![Screenshot_2022-02-13_17-57-48](https://user-images.githubusercontent.com/3736107/153762011-83ba15bd-348a-4d7b-b307-6719ed2efc1e.png)
![Screenshot_2022-02-13_17-51-26](https://user-images.githubusercontent.com/3736107/153762012-7994c9af-ab3d-4c9b-9f41-0466fa2b6849.png)
![Screenshot_2022-02-13_18-14-18](https://user-images.githubusercontent.com/3736107/153762101-c38753f2-7364-49ef-a5d1-d57dc65e62f2.png)

### To Reproduce

See above

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

14.17.5

### What database are you using?

PostgreSQL 13.3

### What browser are you using?

Brave 1.31.74

### What operating system are you using?

Linux Manjaro

### How are you deploying Directus?

locally on Visual Code

**Comment by SCaptainCAP** [comment]
@mhdaouas Do you use caching? Had the same issue when running two instances of Directus while connected to one Postgres database. I enabled [caching](https://docs.directus.io/configuration/config-options/#cache) with redis database, and the issue was resolved!

**Comment by jaycammarano** [comment]
Closing. This seems to have been resolved.
