### ISSUE TITLE
Use ISO 8601 on dates

### ISSUE THREAD

**Issue by WellingGuzman** [directus/directus#1162]
We must stop from adding UTC to the dates values, instead we can remove UTC and start using ISO 8601 dates format.

https://en.wikipedia.org/wiki/ISO_8601

Examples
```
2016-06-06T17:18:20+00:00
2016-06-06T17:18:20Z
20160606T171820Z
```

So this is my idea, all dates should be stored as UTC dates (removing the UTC) and can be converted to any timezone we should let the user configure it to. (default to new york timezone).

All API response will include the dates in ISO 8601.

see this bug #1160 – [bug] Save file fails with db error

What do you think @benhaynes?

**Comment by benhaynes** [comment]
This sounds good. But is this for Directus Core data only? Should the date/time UI allow different formats for user content?

Would the user pick a timezone for all of Directus – or per user? If the CMS has users in different timezones, would that still work properly?

**Comment by WellingGuzman** [comment]
> But is this for Directus Core data only? Should the date/time UI allow different formats for user content?

Forgot to mentioned that, yes, Directus core data only, user can format their date as their wish.

> Would the user pick a timezone for all of Directus – or per user? If the CMS has users in different timezones, would that still work properly?

Didn't think through this enough, but good catch, per user will be a even better solution, user can pick their timezone on the editing page. and it will be default to New York Timezone and can be override to whatever the user configure Directus to be.

```
User TimeZone > Directus Project TimeZone > Directus Core TimeZone
```

**Comment by benhaynes** [comment]
OK, great!

Maybe we can request the user's location (in browser) to get/save their timezone for accurate date saving.

**Comment by WellingGuzman** [comment]
We can open a new ticket for user timezone.

Wouldn't be too much asking for location, I always feel too skeptical from site requesting my location, or is it just me? @benhaynes

**Comment by benhaynes** [comment]
We don't need it to use the browser check... just a dropdown on each user detail page instead of the config: https://github.com/directus/directus/issues/1206

Is this one good to close?

**Comment by WellingGuzman** [comment]
yes, and It will auto-close when we merge it into master, thanks to magic ✨ ✨ ✨
