### ISSUE TITLE
Omitting DB_CHARSET is strongly recommended

### ISSUE THREAD

**Issue by 720720** [directus/directus#11628]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a directus CLI installation:

> npm install directus --production --no-optional
> npm install mysql --production
> npx directus bootstrap

My database was created with:

> CREATE DATABASE directus CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

My .env file contains:

> DB_CHARSET="utf8mb4"

<br/>

Directus 9.5.1 update throws the warning message:

> Using custom DB_CHARSET "utf8mb4". Using a charset different from the database's default can cause problems in relationships. Omitting DB_CHARSET is strongly recommended.

<br/>

https://docs.directus.io/configuration/config-options/

> Variable: DB_CHARSET
> Description: Charset/collation to use in the connection to MySQL/MariaDB
> Default Value: UTF8_GENERAL_CI

The directus docs do not mention that you should omit DB_CHARSET and show a collation instead of a charset as default value.

<br/>

https://github.com/directus/directus/commit/148138077552c6fbba6b71df0565da93176eebd2

Adds a warning when DB_CHARSET is not set in env.

<br/>

https://github.com/directus/directus/commit/2d0c23d3c2b9d37737a3fe50bbbe1b3a1a7e5f44

Adds a warning when DB_CHARSET is set in env.
Claims to set charater set to utf8mb4 but I dont see that in the index.ts.

<br/>

https://github.com/directus/directus/pull/11069

Should I just remove DB_CHARSET or is there any other action required.
Any help would be appreciated.

### To Reproduce

npm install -g npm@latest
npm update
npx directus database migrate:latest

### Errors Shown

Using custom DB_CHARSET "utf8mb4". Using a charset different from the database's default can cause problems in relationships. Omitting DB_CHARSET is strongly recommended.

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16.13.2

### What database are you using?

MariaDB 10.5.12

### What browser are you using?

Firefox 97

### What operating system are you using?

Debian 11

### How are you deploying Directus?

Locally

**Comment by Oreilles** [comment]
> Should I just remove DB_CHARSET or is there any other action required.

It is now recommended to remove `DB_CHARSET`, so that the database default value would be used instead when creating collections.

If you're not seeing any other warning after this one:
 
> Using custom DB_CHARSET "utf8mb4". Using a charset different from the database's default can cause problems in relationships. Omitting DB_CHARSET is strongly recommended.

It means that you're lucky and probably won't have anything else to do.
If instead you're being shown messages telling you that some tables and columns in your database have different collations than your database default, you will have to fix them manually.

**Comment by 720720** [comment]
https://github.com/directus/directus/commit/2d0c23d3c2b9d37737a3fe50bbbe1b3a1a7e5f44

<br>

```
my.cnf character_set_server = utf8mb4 collation_server = utf8mb4_general_ci
.env NO DB_CHARSET
```
warning for directus tables utf8mb4_bin

<br>

```
my.cnf character_set_server = utf8mb4 collation_server = utf8mb4_general_ci
.env DB_CHARSET="utf8mb4"
```
warning for directus tables utf8mb4_bin

<br>

```
my.cnf character_set_server = utf8mb4 collation_server = utf8mb4_unicode_ci
.env NO DB_CHARSET
```
warning for directus tables utf8mb4_bin

<br>

```
my.cnf character_set_server = utf8mb4 collation_server = utf8mb4_unicode_ci
.env DB_CHARSET="utf8mb4"
```
warning for directus tables utf8mb4_bin
warning for directus tables utf8mb4_general_ci
warning for collection tables created by directus utf8mb4_general_ci
warning for custom tables != utf8mb4_unicode_ci

<br>

This commit will show warning messages for any directus installation.
Are directus table collation warnings necessary?
Do directus and custom tables need the same collation?
Is there any problem as long as custom tables have the same collation independent of the databases default?
