### ISSUE TITLE
Wrong Time in list

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1164]
## Version Info
  - Directus version: 6.2.8 / ad3636de
  - PHP version: PHP 5.5.10 (built: Mar 14 2014 12:31:02)
  - MySQL version: 5.1.73
  - Web server: Apache
  - OS name and version: Linux 2.6.32

## Expected Behavior

I have created two time fields. I enter an AM time into the one field and a PM time into the other field.

When now looking at the record in the list view:

* am/pm seems to be reversed
* the leading 0 in the minutes in missing

## Actual Behavior

* am/pm should be displayed correctly
* minutes should always be displayed with two digits

## Steps to Reproduce
 1. create a time column
 2. create a row
 3. write something into the time field
 4. look at the time value in the list view

## Logs or Screenshots

form field:
![bildschirmfoto 2016-06-17 um 12 03 01](https://cloud.githubusercontent.com/assets/26493/16147455/7ff59690-3483-11e6-91d5-9af8b2647254.png)

list view:
![bildschirmfoto 2016-06-17 um 12 03 09](https://cloud.githubusercontent.com/assets/26493/16147485/a5870bd2-3483-11e6-96ba-7bec5a438543.png)

## cause

For me it looks like here:
https://github.com/directus/directus/blob/master/app/core-ui/time.js#L103
`time[2]` is always truthy because it's a string so it always adds 12 hours to the time. But I am not sure why that's done anyway.

And this:
https://github.com/directus/directus/blob/master/app/core-ui/time.js#L107
should be replaced with
```
var minutes = (d.getMinutes() < 10 ? '0' : '') + d.getMinutes();
```
in order to prepend a 0 digit whenever the second. (same seconds and hours?)

**Comment by WellingGuzman** [comment]
@laszlokorte You are correct, those are the two exact issue. you are welcome to open PR with fixes like this.

**Comment by benhaynes** [comment]
Good catch @laszlokorte – looks like a lot of little issues have made it through the cracks while we worked through the Hosted platform. Thanks for all these comments/tickets!
