### ISSUE TITLE
Cannot delete folder from Data Model page

### ISSUE THREAD

**Issue by ubikitty** [directus/directus#11643]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

**On the Data Model page create a Folder.**
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/28765701/154052634-3b4d7c7f-4a1b-4d18-a3c4-2cfd51e7a3a8.png">
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/28765701/154052818-04e26049-200a-4d51-8d1c-575396de306b.png">

**Now click on the menu icon of the folder, select delete, confirm deletion.**
<img width="325" alt="image" src="https://user-images.githubusercontent.com/28765701/154052062-00f80524-7653-488b-b2b8-9fc4d14aac1e.png">
<img width="620" alt="image" src="https://user-images.githubusercontent.com/28765701/154052411-28b48409-7e0b-4a4e-9213-c1eab3cd2f14.png">

**An error is shown and the folder is not deleted.**
<img width="620" alt="image" src="https://user-images.githubusercontent.com/28765701/154052488-fae88ba8-89c0-436a-b36b-f16bffacb300.png">

It seems it wants to delete a collection instead of a folder (drop table instead of deleting a row in the directus_collections table).

### To Reproduce

view above

### Errors Shown

view above

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16.13.2

### What database are you using?

Postgresql 14

### What browser are you using?

Firefox

### What operating system are you using?

macos

### How are you deploying Directus?

running locally

**Comment by jaycammarano** [comment]
Yup. Everything you said is correct. Having the API delete the row in directus_collections should solve it. Thank you! 👍

**Comment by azrikahar** [comment]
This should be fixed by #11432. Tested it locally and I can reproduce the issue on a commit before that PR, but also confirmed that it's resolved after that PR 👍
