### ISSUE TITLE
Nested filter do not work in O2M direction

### ISSUE THREAD

**Issue by eXsiLe95** [directus/directus#11655]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When filtering items using nested filters, I can only filter in the direction of a M2O relations. The filter is then being applied to the data across multiple relations (from collection to collection to collection, and on the third collection, a field is checked) and it rightfully sorts out data - it works like a charm! :)

I can not filter "the other way around" (in the direction of O2M relations) with more than one relation. The filter will then not be applied which results in data being received mistakenly.

I already took a look at the code here (at this point, I'd like to mention my deepest respect for you guys!) and tried to wrap my head around what's the issue here, but I couldn't quite figure it out since technically in my eyes, both operation should result in a very similar query and should both work just fine. I _think_ there could be a missing recursion call on the subquery part of `directus/api/src/utils/apply-query.ts#applyFilter()#addWhereClauses()` which only allows one subquery, but no nesting as for the other where clauses.

This might have something to do with #3434, but I'm not quite sure since filtering the other way around works just fine.

### To Reproduce

1. Create three collections `Page`, `Article` and `Author`.
2. Create the following relations (for each M2O, also create the corresponding O2M field):

`Page` <--O2M--> `Article` <--O2M--> `Author`

3. Create a demo set of data which each relates to another:

`GET /items/Page/fields=*.*.*`
```json
{
    "data": [
        {
            "id": 1,
            "pageTitle": "Some title for a page",
            "articles": [
                {
                    "id": 1,
                    "articleName": "Some article",
                    "articlePage": {
                        "id": 1,
                        "pageTitle": "Some title for a page",
                        "articles": [
                            1
                        ]
                    },
                    "authors": [
                        {
                            "id": 1,
                            "name": "Lukas",
                            "article": 1
                        }
                    ]
                }
            ]
        }
    ]
}
```

4. Filter "bottom to top" (in terms of the data model hierarchie), for example:

`GET /items/Author?fields=*.*.*&filter[article][articlePage][pageTitle][_eq]=Some title for a page` (expect to retrieve the user)
```json
{
    "data": [
        {
            "id": 1,
            "name": "Lukas",
            "article": {
                "id": 1,
                "articleName": "Some article",
                "articlePage": {
                    "id": 1,
                    "pageTitle": "Some title for a page",
                    "articles": [
                        1
                    ]
                },
                "authors": [
                    {
                        "id": 1,
                        "name": "Lukas",
                        "article": 1
                    }
                ]
            }
        }
    ]
}
```
and:

`GET /items/Author?fields=*.*.*&filter[article][articlePage][pageTitle][_eq]=x` (expect empty result list)
```json
{
    "data": []
}
```
**It should work perfectly well.**

5. Filter "top to bottom", for example:

`GET /items/Page?fields=*.*.*&filter[articles][authors][name][_eq]=Lukas` (expected to retrieve the page)
```json
{
    "data": [
        {
            "id": 1,
            "pageTitle": "Some title for a page",
            "articles": [
                {
                    "id": 1,
                    "articleName": "Some article",
                    "articlePage": {
                        "id": 1,
                        "pageTitle": "Some title for a page",
                        "articles": [
                            1
                        ]
                    },
                    "authors": [
                        {
                            "id": 1,
                            "name": "Lukas",
                            "article": 1
                        }
                    ]
                }
            ]
        }
    ]
}
```

`GET /items/Page?fields=*.*.*&filter[articles][authors][name][_eq]=x` (expect empty result list)
```json
{
    "data": [
        {
            "id": 1,
            "pageTitle": "Some title for a page",
            "articles": [
                {
                    "id": 1,
                    "articleName": "Some article",
                    "articlePage": {
                        "id": 1,
                        "pageTitle": "Some title for a page",
                        "articles": [
                            1
                        ]
                    },
                    "authors": [
                        {
                            "id": 1,
                            "name": "Lukas",
                            "article": 1
                        }
                    ]
                }
            ]
        }
    ]
}
``` 
**The filter isn't applied**

### Errors Shown

No errors are shown :(

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

v16.13.1

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

locally, Docker, AWS

**Comment by rijkvanzanten** [comment]
Great find! Tricky one to solve, so glad to see you've already put together a PR as well 😄
