### ISSUE TITLE
Insecure passing of access_token in URL parameters

### ISSUE THREAD

**Issue by temptuomas** [directus/directus#11652]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

This is not on the latest version. We currently cannot update to later due to problems related to plugins. 

When you export topics as CSV the following URL is requested

`https://xxxxxxxxxxx.net/items/topics?access_token=CENSORED&export=csv&fields[]=id&fields[]=status&fields[]=topic_page&fields[]=topic_picture&fields[]=date_created`

This url gets passed to Google and this token should be handled securely in the request header instead.

### To Reproduce

When you export topics as CSV the following URL is requested

`https://xxxxxxxxxxx.net/items/topics?access_token=CENSORED&export=csv&fields[]=id&fields[]=status&fields[]=topic_page&fields[]=topic_picture&fields[]=date_created`

### What version of Directus are you using?

9.0-rc.76

### What version of Node.js are you using?

14.0

### What database are you using?

Postgres 11

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Running in Azure

**Comment by jaycammarano** [comment]
I'm tagging this bug and improvement because both seem true in this case. It's more of an improvement but since it's a security improvement that lends itself to be a bug. In my opinion at least.

**Comment by rijkvanzanten** [comment]
I don't know if this is something that we can improve on. You can't add headers when opening a new tab in a browser, so there's only so much we can do. In this particular case, only the temporary token for the user is appended, which isn't permanently valid.

What do you mean by

> This url gets passed to Google

@temptuomas?

**Comment by temptuomas** [comment]
> 
> What do you mean by
> 
> > This url gets passed to Google
> 

Thanks for the swift response! This problem was brought up in a security audit and the worry was that f.ex. Google Chrome sends URL parameters to this safebrowsing service and you could then download the URLs in plaintext from there(?).

I'm not completely clear on the details on how you can download those reports from other machines (or if you can) and don't have further details apart from this image from which I tried to obfuscate the address and the access key. The visible key in POST request seems to be some public Google key used in API requests.

![example-safebrowsing](https://user-images.githubusercontent.com/99743933/154222784-d01ad81b-d708-4342-85d5-79f6ef2b4fb8.png)

**Comment by rijkvanzanten** [comment]
@temptuomas Ah gotcha, thanks! In this case, you have another service in between that keeps track of what URLs are requested.

In general, you're absolutely right. Image thumbnails are currently downloaded with the query parameter authentication method rather than the Authorization header, as browser don't have any native way to attach headers to requests made in <img> or <video> tags. That being said, we're working on a proper solution that uses an alternative media loading strategy here: https://github.com/directus/directus/pull/10592
