### ISSUE TITLE
Cant edit tables content

### ISSUE THREAD

**Issue by nicoonee** [directus/directus#1165]
To help us resolve your issue more quickly, please use the following template:

For feature requests please chat with us through [getdirectus.com](http://getdirectus.com).

## Version Info
Commercial SaaS version tested on Safari and Chrome on OSX

## Expected Behavior
edit table should show me edit page where i can edit table attributes

## Actual Behavior
it redirects me to tables list

## Steps to Reproduce
 1. Create table in admin panel
 2. go to list of tables
 3. click on selected table

## Logs or Screenshots

**Comment by WellingGuzman** [comment]
Hi @nicoonee I'm sorry to hear this but thanks for reporting this.

Does the table has spaces or any special character? I could replicate this issue on a table with spaces and only If I click them on the sidebar, it this also your case?

**Comment by WellingGuzman** [comment]
This was already fixed on hosted.
