### ISSUE TITLE
Error Uploading SVG Files

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1166]
## Version Info
  - Directus version: 6.2.8 / ad3636de
  - PHP version: PHP 5.5.10 (built: Mar 14 2014 12:31:02) 
  - MySQL version: 5.1.73
  - Web server: Apache
  - OS name and version: Linux 2.6.32

## Expected Behavior

SVG files should be uploadable.

## Actual Behavior

uploading svg files causes a server error because `imagecreatefromstring` does not support svg.

## Issue

I guess it is caused by this check which detects svg files as images because the mime type is `image/svg+xml`. 
https://github.com/directus/directus/blob/master/api/core/Directus/Files/Files.php#L362

After adjusting the condition in the php file the upload succeeds but the thumbnail is not displayed correctly. Because is similar condition is encoded in the javascript front end for setting the thumbnail urls:

https://github.com/directus/directus/blob/master/app/core-ui/directus_file.js#L164
https://github.com/directus/directus/blob/master/app/core-ui/single_file.js#L332
https://github.com/directus/directus/blob/master/app/core-ui/single_file.js#L394
https://github.com/directus/directus/blob/master/app/helpers/file.js#L9

IMO for SVG file the original file url should be used for thumbnails without any server side processing.required.

**Comment by WellingGuzman** [comment]
Hi @laszlokorte we were aware we had this issue before, I tried to upload a svg and it works. no error, no nothing. just no thumbnail, but no thumbnail missing, it says, "plain". I wonder what was your error exactly? Just to refresh my mind.

Either way I will take a look at this.

**Comment by WellingGuzman** [comment]
Okay, so I found something related, when the svg has a xml header, it will cause an error, but when it's not presented it will not. (note to self)

**Comment by laszlokorte** [comment]
Yeah that's because 
```
$finfo = new \finfo(FILEINFO_MIME);
$finfo->buffer(...)
```
guesses the mime type by looking at the buffer. If it does not start with the xml header it's not valid xml => not valid svg => finfo can not know that it's svg so it just says `text/plain`.

**Comment by WellingGuzman** [comment]
Would be relying on the file extension to determine their mime type a better option? creating a table of extension and their mime types could be a good reason, although it may not be real.

it will never be perfect, though, as an example we have an svg and by it's content `finfo` doesn't know what it is.

What about using `finfo` and a mime type tables and if they mismatch, use the mime type tables information.

Is it worth it?

@benhaynes what do you think about this?

**Comment by laszlokorte** [comment]
```
it will never be perfect, though, as an example we have an svg and by it's content finfo doesn't know what it is.
```
I think that is not the core problem here. SVG files should always have the correct header to be valid and thus would be detected by finfo correctly.

The problem is that you only check for the media type of the mime type to be image before calling `imagecreatefromstring` but Php does only support JPEG, PNG, GIF, WBMP, and GD2d (http://php.net/manual/de/function.imagecreatefromstring.php) when there are >50 other file formats of type image/* (https://www.sitepoint.com/web-foundations/mime-types-complete-list/).

I would suggest keeping a small list of `imagecreatefromstring`-supported mime types and check against them. Then it might be a good idea to not duplicate that mimetype check on the client side but just save a flag in the database to tell if a thumbnail is available and use this on the client side.
Finally for SVG files the thumbnail should just be a copy of the original file. I guess that check would fit into `Directus\Files\Thumbnail`

**Comment by WellingGuzman** [comment]
Okay so we are having different issues here, I haven't replicate the issue where I get an svg mime type (`image/svg+xml`) correct instead of always text/plain. what I'm saying here is that apparently svg has not default content. as it will dependent from where it was created. some got xml at the headers some don't. As I never got any svg I have upload to get me the correct svg, so this make it possible of the multiple header it can have.

So anyway, I will work on this one, because it's definitely a issue.

If you would like as I said you can always open a PR.

Thanks.

**Comment by laszlokorte** [comment]
I was wrong about SVG files having to start with `<?xml` (https://www.w3.org/TR/xml/#sec-prolog-dtd). It's just a `should`.

So you are right: Additionally checking the file's extension is needed to achieve proper mimetype recognition.

**Comment by benhaynes** [comment]
It's a bummer to rely on extensions, but maybe that's our best fallback. 

I do agree that it might be best to copy the full SVG file as the thumb (instead of trying to generate a bitmap version). @WellingGuzman is that something we can do under this ticket?

Thanks @laszlokorte – really appreciate all these tickets!

**Comment by WellingGuzman** [comment]
We can't crop a svg, can we? we should create an image as svg thumbnail, as it may be used as a preview, and most likely to be supported without much hassle.

Are we really want an svg file to represents itself as thumbnail? we can do that and I see the point, that will add a new level of, this is a svg render itself it's not, look for the thumbnail.

maybe I'm wrong, but let's do testing here.

**Comment by benhaynes** [comment]
Within Directus, we probably want to maintain all thumbnails as bitmap (JPG). Let's try to create a JPG of the SVG in the `thumbs` folder. If we can't do that, we can make a copy of the SVG in the `thumbs` directory.

@WellingGuzman is there a supported way to get a JPG thumb of the SVG with our required libraries?

**Comment by WellingGuzman** [comment]
@benhaynes apparently GD library doesn't support SVG but Imagick does, but all this library requires to be installed.

I will do some research about this, but what can be sure it's that Directus upload the svg with no problem, the thumbnail is what we need to look for a solution.

Copying the same file twice wouldn't be a good idea though. Although we can do it's replace the thumbnail with the same image if the image is an svg, or something similar.

**Comment by benhaynes** [comment]
That works. Not sure if it's better to generate a bitmap thumbnail (when possible) or copy an SVG thumbnail (as a fallback perhaps?)... but either way works for me as long as it represents the uploaded image.

**Comment by benhaynes** [comment]
@WellingGuzman – I know we were trying to find the best way to handle thumbnails... but is the error when uploading SVGs resolved?

**Comment by WellingGuzman** [comment]
it hasn't been resolved yet. Until we figure it out how to do that, let's open a feature ticket for handling SVG thumbnail.

In other hand, I will fix the uploading issue, as this is the main issue.

**Comment by benhaynes** [comment]
Perfect. Let's leave this open to fix the error... the thumbnail is now in FeatHub:

**[Migrated to FeatHub](http://feathub.com/directus/directus/+50) (Thumbnail Creation Only)**

Please use the [Directus FeatHub](http://feathub.com/directus/directus) to vote for features or make new request. Accepted feature requests will be added to GitHub Issues.

**Comment by WellingGuzman** [comment]
I tried to upload svg the one with and witout html header, and no problem uploading, updating the file info method solve this issue along the way.

If someone happen to replicate the issue again, let us know.

**Comment by huyderman** [comment]
Hi
What exactly is the fix? I pulled the latest changes from master, but still get the `imagecreatefromstring` error.

**Comment by WellingGuzman** [comment]
Hi @huyderman, it was fixed on the development branch.

You man want to use the dev branch and try it and let us know if that works for you too.

Thanks,

**Comment by huyderman** [comment]
Finally got `development` up and running. Yeah, seems like uploading SVG works now.

**Comment by WellingGuzman** [comment]
@huyderman thanks for letting us know, this will be in master soon.

**Comment by benhaynes** [comment]
It looks like there is different code for uploading by:

* Drag and drop onto Files page
* Click "New File" on Files page

Same file uploaded both ways, HTML = Drag and Drop:
![screen shot 2016-08-09 at 8 33 17 pm](https://cloud.githubusercontent.com/assets/522079/17538116/88e5a922-5e70-11e6-9fee-2bc8285f59d8.png)

Also, does it need to say `SVG+XML`? Is that important (in terms of meta data) or can it just say `SVG`?

**Comment by benhaynes** [comment]
OK, this is working great now!
