### ISSUE TITLE
Installation form fields color

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1167]
- Directus version: e86379523
  - PHP version: 5.6
  - MySQL version: -
  - Web server: Apache
  - OS name and version: Linux

## Expected Behavior

Some form fields of the installation page have placeholder text set. Usually placeholder text is colored lighter than the actual value of a form field in order to emphasize that it's just a placeholder and not the actual field's value.

## Actual Behavior

The placeholder has the exact same color as the actual field's value. That's extremely confusing. Especially since the "Project Name" field has a placeholder of "My Project Name" which I do not want to change when testing Directus for the first time. 
Not knowing that it's just the placeholder text it took me a few minutes wondering why I was not able to click the button to continue although all fields were filled.

## Logs or Screenshots

![bildschirmfoto 2016-06-18 um 15 13 49](https://cloud.githubusercontent.com/assets/26493/16171209/6cbb7004-3569-11e6-8ca6-10397fbddeda.png)

"admin@example.com" and "My Project Name" are just placeholders but are visually not distinguishable.

## Issue

The reason seems to be the use of the `-webkit-text-fill-color` attribute which sets the color for both the actual field value and the placeholder. I am not sure why such a special vendor prefixed attribute is used for setting the color in the first place.

**Comment by benhaynes** [comment]
@laszlokorte – very true! I removed that vendor-specific property so that the autocomplete text is lighter than the actual input text. I also added "eg:" to the two inputs with placeholder text to avoid mistaking them for actual values.

This is on the `development` branch, which will be merged into master in a few weeks (big update).

Thanks for opening this ticket!!
