### ISSUE TITLE
String primary keys with commas produce unescaped URLs in admin interface

### ISSUE THREAD

**Issue by jakmeier** [directus/directus#11679]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hi,

I'm fairly new to Directus and I love the project so far, thanks for the great work!

I recently ran into a niche bug. When a PK contains a comma, then the URL to edit the element is not escaped.

I admit this is a weird use case, having commas in PKs. But since text PKs are generally allowed, I cannot really stop my users from using them and entering commas...

### To Reproduce

1. Create a new collection and select "manually entered string" as the PK type for a collection. (Produces `character varying(255)` typed PK on my DB) Other fields don't matter. For the simplest case insert no other fields.
2. Create a new entry and give a PK value with a comma.
3. Save the entry.
4. Try to edit the entry

New Collection:
![pk_string](https://user-images.githubusercontent.com/6342444/154364992-2df90354-ea22-4e46-8102-595a69e3b476.png)
Element is shown correctly in the overview page:
![element_shows_correctly_in_list](https://user-images.githubusercontent.com/6342444/154365001-637a0e2a-d0b8-44c9-8643-505fb8fc38c6.png)
The url now contains the comma but is not escaped. (FF displays URLs user readable, so it actually looks like white space isn't escaped, either.. But it is, see screenshot of Chromium URL.)
![Firefox: url_broken](https://user-images.githubusercontent.com/6342444/154365011-a1ee5fee-e615-477a-9017-6d94b2daca49.png)
![Chromium: image broken](https://user-images.githubusercontent.com/6342444/154365166-df1659db-3519-4849-8f8f-5366626291dd.png)

### Errors Shown

Page Not Found

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16.13.2

### What database are you using?

PostgreSQL 11

### What browser are you using?

Firefox, Chromium

### What operating system are you using?

Linux raspberrypi 5.10.90-v8+ (Debian GNU/Linux 10 (buster))

### How are you deploying Directus?

manual `npm init directus-project` on a raspberry pi 4b

**Comment by joselcvarela** [comment]
The problem seems to come from here: https://github.com/directus/directus/blob/main/app/src/composables/use-item/use-item.ts#L52

We might need to handle batches in other manner 🤔

**Comment by azrikahar** [comment]
> The problem seems to come from here: https://github.com/directus/directus/blob/main/app/src/composables/use-item/use-item.ts#L52
> 
> We might need to handle batches in other manner 🤔

I believe the `isBatch` that checks commas in `use-item` is only currently used by Webhooks, where the batch editing happens in a page rather than via the typical batch drawer. 

If this is true (I might've missed other places and lack context on this `isBatch`), it may be better to remove this batch logic from `use-item` when Webhooks is ever completely removed in favor of Data Flows. 🤔

**Comment by rijkvanzanten** [comment]
Good one @azrikahar!

**Comment by daawaan** [comment]
Hey @jakmeier, where you able to make any workarounds? I'm currently facing the same issue where we have an addresses collection wherein the primary key is the address and the items in the addresses collection are in a one-to-many relationship with other collections. This makes it possible to filter directly based on an address in the search query for other collections, but we end up having inaccessible item pages for the addresses instead 🤔

**Comment by rijkvanzanten** [comment]
Linear: [ENG-269](https://linear.app/directus/issue/ENG-269/string-primary-keys-with-commas-produce-unescaped-urls-in-admin)
