### ISSUE TITLE
GraphQL update_fields_item only works with Admin Access enabled

### ISSUE THREAD

**Issue by johannesmutter** [directus/directus#11678]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hello :)

It seems only user roles with "admin access" enabled can [update a field](https://docs.directus.io/reference/system/fields/#update-a-field) for example the choices in a select-dropdown field.
To test I enabled all permissions for a role, still I got the below error. Only after enabling "admin access" I could run a GraphQL mutation to update the choices in a select-dropdown field.

In my scenario App users should be able to add choices to a dropdown, that become available to other users as well. But I don’t want to grant them any further permissions.

### To Reproduce

Add a select-dropdown field called "hobbies" to directus_users and run below mutation (update id of field):

```GraphQL
mutation {
	update_fields_item(
		collection: "directus_users",
		field: "hobbies",
		data: { 
      meta: { 
        id: 102,
        field: "hobbies",
        collection: "directus_users",
        readonly: false,
        hidden: false,
        options: { 
          choices: [
            {
              text: "Running",
              value: "running"
            },
            {
              text: "Hiking",
              value: "hiking"
            },
            {
              text: "Winning Olympia",
              value: "olympia_champion"
            },
        	]
    		} 
    	}
    }
	) {
	    field
	    meta {
	      options
	    }
	}
}
```

### Errors Shown

`          "graphqlErrors": [
            {
              "message": "Cannot query field \"update_fields_item\" on type \"Mutation\". Did you mean \"update_users_item\", \"update_presets_item\", \"update_users_items\", \"update_presets_items\", or \"update_users_me\"?",
`

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

17.4.0

### What database are you using?

Postgres 14.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS Monterey (12)

### How are you deploying Directus?

running locally via NPX (node)

**Comment by rijkvanzanten** [comment]
That's correct. Only admin users can modify the data model at this time 👍🏻
