### ISSUE TITLE
Presentation fields don't work if field permissions are applied

### ISSUE THREAD

**Issue by stx-chris** [directus/directus#11683]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Presentation fields don't work when the user role has restricted view access (at field level). As soon as the role gets view-all access, the presentation fields appear and work as intended.

### To Reproduce

1. Create a notice or button link field
2. Select a user role with view access to the collection
3. Remove individual fields from the view access
4. Note that the newly added presentation fields don't show up in the permission view list
4. Try to use the presentation fields. Button is disabled, Notice is hidden

### What version of Directus are you using?

9.5.1 (upgraded directly from 9.0.0)

### What version of Node.js are you using?

16.13.2

### What database are you using?

Postgres 13

### What browser are you using?

Chrome, Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

locally and Docker

**Comment by stx-chris** [comment]
Note: The issue seems to be connected to the Admin role. Non-admins seem to be affected from this issue.

**Comment by azrikahar** [comment]
@stx-chris thanks for pointing this out, submitted a fix 👍 Just to clarify, when you are selecting individual fields to grant read permission, you _should_ be able to select the Notice, but the bug hid it instead.

In the meantime, if you would like to do the above operation while awaiting the fix to be released in future version, you can downgrade to `9.5.0` as the bug should only happen to `9.5.1`.
