### ISSUE TITLE
Potential security vulnerability in one of your dependencies: nth-check

### ISSUE THREAD

**Issue by abdonrd** [directus/directus#11688]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Potential security vulnerability in one of your dependencies: nth-check

From the GitHub UI:

<img width="934" alt="Screenshot 2022-02-17 at 16 01 56" src="https://user-images.githubusercontent.com/1007051/154578857-1b917b0a-a246-4d47-b471-339bf71c6198.png">

<img width="945" alt="Screenshot 2022-02-17 at 16 17 24" src="https://user-images.githubusercontent.com/1007051/154512044-6bc3020d-a454-4a75-a2d4-64e6d5d8ad27.png">

### To Reproduce

No steps.

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### What operating system are you using?

macOS Monterey (12)

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
Heya, thanks for the update and PR 👍🏻 

For what it's worth, the affected version of `nth-check` is only used in a devDependency, and in a code path out of harm of regular usage of Directus.

The underlying issue (see https://huntr.dev/bounties/8cf8cc06-d2cf-4b4e-b42c-99fafb0b04d0/ for the full report) is a problem that can make the parsing of regexes super slow, and therefore potentially cause a denial of service attack. However, this package is only used as part of the CSS parsing of extensions in its minification, and only during build, so there's really isn't any entrypoint to hit this codepath in usage of Directus.

The downside to automated audit tools like GitHub's dependency search or `npm audit` is that it surfaces a lot of these false-positives that adds a lot of noise. [Dan Abramov](https://mobile.twitter.com/dan_abramov) wrote a great post regarding this: https://overreacted.io/npm-audit-broken-by-design/.

In any case, it's an easy fix, and there's no reason not to update the package of course, just wanted to point this out 😄 

(Oh and please email security@directus.io directly for any potential security problems you might encounter 🙂 )

**Comment by abdonrd** [comment]
Ok! Thanks for all the info!
