### ISSUE TITLE
Table info API endpoint throws confusing exception when fetching a table that doesn't exist

### ISSUE THREAD

**Issue by christophemarois** [directus/directus#1169]
## Version Info
  - Directus version: 6.2.8 installed on official directus Vagrant box

## Behavior

When fetching table info:

```bash
$ curl http://192.168.33.6/api/1/tables/blog \
    -u fkCMPxSyvo7SNX8H:
```

I get an exception:
```
Argument 1 passed to Directus\View\JsonView::render() must be of the type array, boolean given, called in /var/www/html/directus/api/api.php on line 1183 and defined
```

On line 1182 of `api/api.php`, ` $response = TableSchema::getTable($table);` seems to soft-fail and return `false`, so when it is passed as an argument to `JsonView::render`, it throws an exception.

**EDIT:** It seems that I was fetching `api/1/tables/blog` when my table was in fact named `Blog`, so the correct route to call was `api/1/tables/Blog`. I assumed table names were normalized and downcased in order to be URL-safe. Maybe more custom errors would help pinpointing issues like this one?

## Logs or Screenshots

![capture d ecran 2016-06-18 a 12 30 37](https://cloud.githubusercontent.com/assets/811336/16172346/9d3de230-3554-11e6-90b2-e0f8a76b8877.png)

**Comment by WellingGuzman** [comment]
@christophemarois I hope this hot fix works for you, while we work on the API responses we think will be best.

**Comment by benhaynes** [comment]
Thanks @christophemarois – this is super useful! We've actually been talking quite a bit about standardizing table/column names, what's best, and what should be supported. For instance, should spaces be allowed in table/column names (as of now we've decided that creating them _within_ Directus would remove spaces... but that Core would support them when created within the database directly. The same questions arise when looking at case (upper/lower).

We'd love your (or anyone else's) opinion on what is best for the framework – so keep the tickets/comments coming. Also, I've sent you an invite to our Slack team in case you'd like to chat about any of this over there.

Really appreciate the feedback!

**Comment by benhaynes** [comment]
Also, I've updated the docs with notes reminding users of the API that the table/column names are case sensitive. Very important to have in there until we figure out about downcasing, etc.
