### ISSUE TITLE
Time input interface "clunky"

### ISSUE THREAD

**Issue by thepurpleblob** [directus/directus#11700]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The input interface for times seems oddly hard to use. It's quite easy to fail to input part of the time. 

### To Reproduce

- Create a field that requires a time input
- Input the time... I did "hours"... tab... "minutes"... then what?
- clicking tab again does nothing. Clicking enter writes the time into the field but does not close the dialogue. Clicking away closes the dialogue without saving the minutes part of the time. 

I would have thought that anything that moves focus away from the dialogue should write the data to the field. There should be some key (probably enter) that closes it. 

<img width="792" alt="Screenshot 2022-02-18 at 11 01 46" src="https://user-images.githubusercontent.com/664139/154671082-049734ee-0a12-4244-aa8d-41ac1e3f9ff5.png">

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

Latest

### What database are you using?

SQLite

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

Docker

**Comment by VaZark** [comment]
I'd like to add another point to this. Even when the interface option is set to enable 24h format for the time field, it still is displayed in the 12h format with AM/PM
