### ISSUE TITLE
No permission to field function, even with permission granted on field

### ISSUE THREAD

**Issue by johannesmutter** [directus/directus#11713]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Unless I grant "All Access" for "Read" of a collection I cannot query in GraphQL the "date_created_func" (corresponding to a date field called "date_created").

```GraphQL
query {
  Post {
    date_created # works fine
    date_created_func {year} # throws error
  }
}

```

### To Reproduce

1. Create a collection with a date field "date_created"
2. Create a role with custom read permissions, allow reading the date field
3. Create a user and assign it to the role; generate an access token
4. Run  GraphQL query using the property date_created_func

### Errors Shown

```GraphQL
{
  "errors": [
    {
      "message": "You don't have permission to access this.",
...
```

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

17.4.0

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### What operating system are you using?

macOS Monterey (12)

### How are you deploying Directus?

running locally, npx / node

**Comment by joselcvarela** [comment]
Hello,
I can confirm this on my end too.

Also this happens on REST too. Not only with field functions but also with field itself.
