### ISSUE TITLE
Checkbox UI, not null => check required

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1171]
## Version Info
  - Directus version: d2128abec

## Expected Behavior

I have a table with a tinyint(1) column which is not allowed to be NULL but must be 0 or 1. I create a field with the checkbox UI for this column.

I expect the column to be set to 1 if the checkbox is checked and to 0 otherwise.

## Actual Behavior

The validator forces me to check the checkbox because it interprets the NOT NULL constraint as the field being *required*.

## Steps to Reproduce
 1. Create a checkbox/tinyint field
 2. set the corresponding column to NOT NULL (via dbms)
 3. try to create a record without checking the checkbox

The "required" checkbox in the Tables editing view is disabled and cannot be changed.

## Logs or Screenshots

![bildschirmfoto 2016-06-19 um 00 24 07](https://cloud.githubusercontent.com/assets/26493/16174087/e9341690-35b4-11e6-94d4-c98722e35f68.png)

![bildschirmfoto 2016-06-19 um 00 24 52](https://cloud.githubusercontent.com/assets/26493/16174091/f1c99988-35b4-11e6-9802-b3c91ed33638.png)

![bildschirmfoto 2016-06-19 um 00 25 13](https://cloud.githubusercontent.com/assets/26493/16174093/f4a74ae2-35b4-11e6-9cce-af984429c3a6.png)

**Comment by benhaynes** [comment]
Hey @laszlokorte – I remember this came up a while ago (a few years). I forget what the reasoning was for this logic but agree with your recommendation. 

@WellingGuzman do you see any reason why we can't allow unchecking the "required" option (currently disabled) for TINYINT() that do not ALLOW NULL? Having a required checkbox seems a bit weird – and it definitely shouldn't be required...

**Comment by WellingGuzman** [comment]
I bumped into this the other day as well, so wasn't sure what was it, so I let it slide.

checkbox shouldn't be require at all, there's not good reason for that. I mean, if it's checked it will be **1** and if it's not well, it's **0** so it will always have value.

I work around here to keep the "mandatory check", will be to add an option, in case this is something useful in some situation that I can't think of right now.

I'm working on it.

**Comment by WellingGuzman** [comment]
This one https://github.com/directus/directus/commit/bf5235156a3d1918ae8c5f4f7b58120e4a130321 should do the trick.

**Comment by laszlokorte** [comment]
Thank you for your quick responses
