### ISSUE TITLE
File Upload via API returns empty body (204 No Content)

### ISSUE THREAD

**Issue by mopotmo** [directus/directus#11721]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When I upload a file via API (`POST /files`) I get a `204 No Content` as response code as well as an empty response body.

The file is created correctly though.

I would expect to receive a JSON body with the newly created file´s metadata. Especially do I need the id to do something useful with the file.

### To Reproduce

```
curl -v \
  -F "file=@/path/to/local/file" \
  "http://localhost:8055/files/?access_token=..."
```

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

From docker image

### What database are you using?

MariaDB 10.7

### What browser are you using?

Chrome / curl

### What operating system are you using?

macOS

### How are you deploying Directus?

Local docker compose

**Comment by rijkvanzanten** [comment]
Does your user have read access to directus_files?

**Comment by mopotmo** [comment]
Oh, thanks. That was indeed the problem. After granting read access to the user, it worked as expected. Thanks for pointing me in the right direction.
