### ISSUE TITLE
Wrong links in documentations pages

### ISSUE THREAD

**Issue by moalamri** [directus/directus#11736]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When I click on any headline title in documentations pages it should take me to the anchor of the linked element, but instead it takes me out of the app to the login page.

It only happens to hash tagged links where they supposed to scroll down/up to the anchor of the related topic.
The reason for this behavior is due to the current route url not being injected into the link.
The link point to the following:
`http://example.com/admin/#**tag**`

Where it should point to:
`http://example.com/admin/docs/app/**document**#**tag**`

![record-screen](https://i.giphy.com/media/P42ZmvgbKRCGikLYW1/giphy.webp)

### To Reproduce

Click on any documentation tagged link

### What version of Directus are you using?

9.5.0 & 9.5.1

### What version of Node.js are you using?

16.13.1

### What database are you using?

Postgresql

### What browser are you using?

Microsoft Edge | 98.0.1108.50 (Official build) (64-bit) 

### What operating system are you using?

Windows 11

### How are you deploying Directus?

Bare bone

**Comment by licitdev** [comment]
Hi @moalamri, I am unable to reproduce your issue in Microsoft Edge on macOS. 
Please kindly elaborate on your bare bone set up. 
You may also wish to upgrade to test if v9.5.2 resolves the issue. 

https://user-images.githubusercontent.com/26413686/154888585-ace12098-25f3-453e-8cf2-1e2dd26eace6.mov

**Comment by moalamri** [comment]
Hi @licitdev,
Sorry for not being clear about deployment.
I meant that I didn’t use docker or iis or reverse proxy, just Directus on the edge using `directus start`

I deployed a fresh install of v9.5.2 and used different browser (Safari), but it seems like the issue is still there.

I will dig more into this today and let you know.
Otherwise I will upload a copy of the project to see if this just an end user issue.

**Comment by licitdev** [comment]
@moalamri No worries, I thought it could be due to a reverse proxy rewriting urls.
Thank you for your clarification~ 👍🏻

**Comment by moalamri** [comment]
I will close this until later when I have time to debug more or when someone else report the same issue
