### ISSUE TITLE
One to Many, Many to Many sometimes not working

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1173]
## Version Info
  - Directus version: d2128abec

## Expected Behavior

I am not yet able to reproduce this behavior but during the last two days of testing it occurred several times that child records added via a (one|many)-to-many field were not saved correctly.

The first case:

1. click on the "Add ... items" button of a OTM field
2. fill out the child record's form
3. click the child's "save" button
4. I get back to the parent's page but the child has not been created ie it's not in the list of the parent's OTM field. But I get no error at all.

The other case:

1. click on the "Chose existing" button of a MTM field
2. select some records from the list
3. click the save button
4. the selected items are now visible in the list of the parent's MTM field
5. click save (getting back to the parent table's list view - no error message)
6. edit the record again
7. see that the selected items are not longer in the MTM field's list
8. see that the selected items have not been saved in the junction table in the DB

---

As I said I am currently not able to reproduce the problem reliable and I am not able to give you more detailed information. I was just testing directus for the past two days and did about 20 fresh installs. Sometimes the MTM and OTM fields worked, then suddenly they stopped working. Sometimes after deleting and recreating a few fields and tables it was working again. Sometimes I had to wipe the whole DB in order to get it working.

My best guess would be that it happens when some inconsistencies between the real schema and directus' meta schema and permissions occur. But I am not familiar enough with the system to verify this.

Maybe you have some idea what I could try if this happens again.

**Comment by benhaynes** [comment]
Hmm, yeah. The relational UIs are easily the most complex part of Directus Core – and can be very tricky to troubleshoot/fix. Intermittent issues like this are the worst – but we'll also test on our side to try and find a process for reproducing.

 Anyone else experiencing this issue should comment any additional insight here.

Thank you for the heads up @laszlokorte!

**Comment by benhaynes** [comment]
@WellingGuzman do you think the commit you referenced above may have fixed this issue? Unable to duplicate, but it would be nice to know what might have been happening.

I agree that it seems like a difference between how `directus_columns` records are created. Any thoughts on this before I close?

**Comment by WellingGuzman** [comment]
I don't know if that's one of the issues he was experiencing, but that one fixed the only one I could replicate.

What's a concern it's how `directus_columns` records are updated, more than anything, and we had related tickets to this issue: https://github.com/directus/directus/issues/1102 and https://github.com/directus/directus/issues/1091

**Comment by benhaynes** [comment]
I have been testing this one for a week or so, and have not seen either of these two issues happen. I'm going to close it and we can reopen if someone encounters it again or has steps to reproduce.

**Comment by WebMadeGood** [comment]
FWIW this is one of the issues I am seeing here: https://github.com/directus/directus/issues/1955
