### ISSUE TITLE
One to Many, junction column

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1174]
## Version Info
  - Directus version: d2128abec

## Actual Behavior

In the list of the OTM fields the right most column is always the one stating the parent record.

In the screenshot you can see me editing a hotel. A hotel has multiple offers. The last column shows "Dorint Hotel" multiple times. I would argue that this column is unnecessary because it's always the same value as that's the very same hotel I am currently editing.

Furthermore you can see that the last "offer" has just a "1" (the hotel id instead of its name) in the hotel column. That's because that offer was just added and not saved yet. I guess that "1" get's displayed because until it's saved the relationship can not be fully resolved.

Displaying an id instead of a correct label in that column is confusing.

## Expected Behavior

I think the "parent" column should not be visible in the OTM field at all.

![bildschirmfoto 2016-06-19 um 01 11 59](https://cloud.githubusercontent.com/assets/26493/16174271/16816886-35bb-11e6-99ba-55aee292f7a8.png)

**Comment by WellingGuzman** [comment]
hey @laszlokorte this https://github.com/directus/directus/commit/6a584235b22d6c94819dcd2b1f8ab11fd5ef8d7c should fix this issue.
