### ISSUE TITLE
OTM field, edit before save fails

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1176]
## Version Info
  - Directus version: bf52351

## Expected Behavior

When creating a new child record via OTM field and then clicking that new record again for editing it before the parent has been saved) I would expect to be able to edit this child.

## Actual Behavior

When clicking the child I get an error message (see screenshot). 
Interestingly I even get this error after having the parent saved via "Save and Stay" option.

## Steps to Reproduce
 1. edit a record that has a OTM field
 2. create a child record via OTM field
 3. click the "Save" button of the child to get back to the parent
 4. do NOT save the parent yet (or save via "Stay")
 5. click the child to edit it again

## Logs or Screenshots

![bildschirmfoto 2016-06-19 um 12 11 44](https://cloud.githubusercontent.com/assets/26493/16176752/695c5c76-3617-11e6-89b0-08bcd08ed271.png)

**Comment by WellingGuzman** [comment]
Hey @laszlokorte I'm late on replying but now I'm focusing on the UIs.

After I coulnd't replicate this issue, I want to check with you if after all these fixes lately are you still having this issue?

why is the error on `many_to_one` UI? is there a M2M UI in that table?

**Comment by benhaynes** [comment]
Just to add to this – there is a O2M and a different M2O UI... so it's good to clarify which we're talking about.

**Comment by benhaynes** [comment]
Hey @WellingGuzman – did you try to replicate with the `one-to-many` UI (not the `many-to-one`)?

**Comment by WellingGuzman** [comment]
I've not had luck replicating the issue, everything works as expected, BUT, maybe how we have been fixing issues on this UI probably it fixed along the way too. (Now that I tested with M2O instead of O2M)

**Comment by laszlokorte** [comment]
I just tried again with a fresh install from the master branch. Now I get the following behavior:

1. edit a record that has a OTM field
2. create a child record via OTM field
3. click the "Save" button of the child to get back to the parent
Now the child does not appear in the OTM table of the parent at all. (so it can not be clicked for editing again) But if the parent is saved the child is created.
4. -do NOT save the parent yet (or save via "Stay")-
5. -click the child to edit it again-

**Comment by WellingGuzman** [comment]
Hello, @laszlokorte 

Most of this have been fixed on development (here https://github.com/directus/directus/commit/9ef64764a3c7f057984ef168bccc44338d18f71e), it hasn't been merged into master yet.

There has been some different bugs fixed with relational UI.

**Comment by laszlokorte** [comment]
Oh cool. I tried to checkout the development branch but the installation failed due to "schema template '' does not exist".

**Comment by WellingGuzman** [comment]
@laszlokorte oh, that's not good. I'm on it.

**Comment by WellingGuzman** [comment]
@laszlokorte you can now pull the last commit. it should work.

**Comment by benhaynes** [comment]
Both of these issues (`create>save>click` & `create>save`) are working for me... closing this unless someone else is still seeing an issue. Good work @WellingGuzman!
