### ISSUE TITLE
"KEY" Environment Variable is missing.

### ISSUE THREAD

**Issue by Tazooou** [directus/directus#11770]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When I try to start my project with the terminal, i have an error : 
`npx directus start
12:26:58 🚨 "KEY" Environment Variable is missing.`

### To Reproduce

Connect on terminal with SSH and execute this command "npx directus start"

### What version of Directus are you using?

the lastest

### What version of Node.js are you using?

no idea

### What database are you using?

Maria DB

### What browser are you using?

Brave

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by joselcvarela** [comment]
Can you check if you have `KEY` defined in your `.env` file?

**Comment by emrahnazif** [comment]
Probably you installed directus manually?
If yes, you may need to install databases as well. 

Try running:
> npx directus init

in your project directory.

**Comment by rhclayto** [comment]
I just ran into this. Last night `npx directus start` results in

```
16:11:02 🚨 "KEY" Environment Variable is missing.
```

It was working last night, I shut down the Directus server, came back this morning, & get this error. Everything is installed & initialized, database already populated with data, `.env` file already configured, & the KEY environment variable is there. Any clues?

**Comment by rhclayto** [comment]
Just a note that might be of use to others: I had this problem. 100% user error in my case: I was in the wrong directory when I ran `npx directus start`! So it couldn't find the .env file, of course.

**Comment by speirsoj01** [comment]
Me too

**Comment by azrikahar** [comment]
@speirsoj01 would you mind creating a new Q&A discussion detailing what have you tried? It would be easier for us to take it from there. Thanks!
