### ISSUE TITLE
another error about "Invalid Foreign Key"

### ISSUE THREAD

**Issue by qddtdlko** [directus/directus#11794]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

use custom permission then to edit or add new field for system collection "Directus Users" will get error of Invalid foreign key

### To Reproduce

1. Create collection named "new" and click Create On box and Created By box, then click OK.

![image](https://user-images.githubusercontent.com/81072363/155294989-928113e2-1714-447a-ba63-2393a83635a1.png)

2. Create field choose input and named "title" then click Save.

![image](https://user-images.githubusercontent.com/81072363/155295074-f6efbd79-c5aa-4201-b36c-e14bdf832c76.png)

3. Select "Roles & Permissions" menu and click add button to Create Role named "newrole" then click Save.

![image](https://user-images.githubusercontent.com/81072363/155295222-cbcc6bcb-b779-4538-b1dd-f82a3399490c.png)

4. Select "Data Model" menu and open System collections tag and select Directus users to Create Field named "testfield".

![image](https://user-images.githubusercontent.com/81072363/155142821-1d9fcb0e-38c7-4fc9-a31a-cf7c804e1695.png)

![image](https://user-images.githubusercontent.com/81072363/155142863-e46666c7-2ad8-4859-9690-eca091587efd.png)

![image](https://user-images.githubusercontent.com/81072363/155142965-79f55559-65a7-4da7-99d4-ab03920b9100.png)

5. At this time, you can edit "testfield" example edit defult value and click save. it normal.

6. Back to New collection and Create item titled any text example "hello world" then Save it.

![image](https://user-images.githubusercontent.com/81072363/155143047-8979bafb-1e56-4610-8405-269b678bf91b.png)

7. Now you back to step 5 and try to edit again. you can get an error "[INVALID_FOREIGN_KEY] Invalid foreign key."

![image](https://user-images.githubusercontent.com/81072363/155143194-c5ebb5c8-6090-4e74-9360-22abf284af19.png)

### Errors Shown

[INVALID_FOREIGN_KEY] Invalid foreign key.
![image](https://user-images.githubusercontent.com/81072363/155143194-c5ebb5c8-6090-4e74-9360-22abf284af19.png)

and sometimes with this process the system will logout automatic and I dont know how to reproduce it.

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

14.17.5

### What database are you using?

SQLite

### What browser are you using?

Chrome, Edge

### What operating system are you using?

Windows_NT 10.0.22000 (Windows11) and bug will reproduce with Linux again

### How are you deploying Directus?

Running locally

**Comment by qddtdlko** [comment]
Replenish: if delete step 9 posted content, that error will disappear.

100% Reproduce

**Comment by azrikahar** [comment]
Closing this in favor of tracking it over at #10842 as this should also be the same underlying cause.
