### ISSUE TITLE
Map field options stop working after upgrade to version 9.5.1

### ISSUE THREAD

**Issue by cah4a** [directus/directus#11795]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Looks like interface option components stopped receiving `field` and `collection` props.

### To Reproduce

On versions 9.5.1 and 9.5.2 try to add a map field.
Map options are not shown.

### Errors Shown

```
vendor.f59145b7.js:5 TypeError: Cannot read properties of null (reading 'type')
    at I3.fn (index.a253b413.entry.js:347:15912)
    at I3.run (vendor.f59145b7.js:2:11990)
    at lB.get value [as value] (vendor.f59145b7.js:2:20235)
    at setup (index.a253b413.entry.js:347:15944)
    at Nh (vendor.f59145b7.js:5:656)
    at uH (vendor.f59145b7.js:2:66574)
    at RE (vendor.f59145b7.js:2:66359)
    at Xe (vendor.f59145b7.js:2:50140)
    at Ye (vendor.f59145b7.js:2:50006)
    at M (vendor.f59145b7.js:2:46326)
```

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

12.22.7

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Kubernetes

**Comment by cah4a** [comment]
Had some investigation about the issue.

Found that [field-detail-advanced-interface](https://github.com/directus/directus/blob/23f6baa4db019fa4d6093f48b9a251d486257e66/app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-interface.vue) after refactoring stop passing `field` and `collection` to the [extension-options](https://github.com/directus/directus/blob/23f6baa4db019fa4d6093f48b9a251d486257e66/app/src/modules/settings/routes/data-model/field-detail/shared/extension-options.vue) as it requires.

**Comment by azrikahar** [comment]
Thanks for the investigation! Helped a lot to find out what happened & landing on a fix for it 👍
