### ISSUE TITLE
Re-editing OTM entry before saving discards previous edit

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1179]
## Version Info
  - Directus version: bf52351

## Expected Behavior

Temporary changes should not be lost.

## Actual Behavior

Changes are lost.

## Steps to Reproduce
 1. Edit an existing child record via OTM field
 2. change some values
 3. click "Save" for the child to get back to the parent
 4. do not save the parent yet
 5. click on the child in the OTM field again to do some further adjustments
 6. note that the child get's reset to the server's state, all previous changes are lost

**Comment by benhaynes** [comment]
@WellingGuzman It seems that we're loading the child (fresh from db) instead of loading the edited one (cached in app, not db). Again, for the O2M, not the M2O...

**Comment by laszlokorte** [comment]
I just tested this in the dev branch.
It's working now for the simplest case of one OTM field.

But If I have the following:

Sessions -OTM-> Talks -OTM-> Speaker

And I edit a session, then edit a talk through OTM field, then edit a speaker through OTM field, click save twice to get back to the session, then edit the talk again, the talk's speakers are refetched and the changes are lost.

**Comment by WellingGuzman** [comment]
Hey @laszlokorte can you mind in sending me a schema for that, I want to try that. Either way I will try to replicate it on my own.

**Comment by laszlokorte** [comment]
[schema-export.sql.zip](https://github.com/directus/directus/files/399981/schema-export.sql.zip)

**Comment by WellingGuzman** [comment]
Side note @laszlokorte, is it okay to this be public?, if so, this will be an awesome [Schema Template](https://github.com/directus/schemas-boilerplate).

**Comment by laszlokorte** [comment]
Yeah I think I removed all sensitive information 😄

**Comment by WellingGuzman** [comment]
Thanks 👍  Want to open a PR yourself if you feel like it, either way I can create one.

**Comment by benhaynes** [comment]
Awesome schema @laszlokorte – always cool to see how people structure things within Directus.

The nested relational data always get's a bit tricky... @WellingGuzman if it get's too crazy then maybe @jel-massih can help out since he did a lot of Directus relational work.

**Comment by benhaynes** [comment]
@WellingGuzman Added steps to reproduce on the development server to Asana. Removed `testing` until this is fixed.

**Comment by benhaynes** [comment]
Looks great – works great! Thanks @WellingGuzman
