### ISSUE TITLE
GraphQL _aggregated missing for string primary keys

### ISSUE THREAD

**Issue by KevinGregull** [directus/directus#11792]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The GraphQL [collection]_aggregated query is not present on collections not containing an integer.
While this makes sense in theory and if you are using int as auto_increment primary key, that is not an issue,
but when you are using UUID as primary key, it is impossible to get a total count of the collection.
For that reason it is impossible to paginate the results without fetching all of them which is impractical.

### To Reproduce

Create a collection with UUID primary key and some other fields that are only strings.

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

v16.14.

### What database are you using?

mysql 8.0.26

### What browser are you using?

does not apply

### What operating system are you using?

Linux - Debian

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Technically this is "guarded" over here:

https://github.com/directus/directus/blob/main/api/src/services/graphql.ts#L250-L264

Which limited aggregation to `GraphQLInt` and `GraphQLFloat` as it's not possible to do things like min/max on other types like UUID. However we should provide other possible aggregations like `count` in this scenario.
