### ISSUE TITLE
Email template issues

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#11807]
These need to use our new email template styling, but the main issue is that the brand image is not showing up.
![Screen Shot 2022-02-22 at 6 18 21 PM](https://user-images.githubusercontent.com/522079/155236114-bd4943f8-bffa-43c5-bbb0-0ecd6585d66b.png)

**Comment by rijkvanzanten** [comment]
Brand image is based on the public URL of your instance. Make sure `PUBLIC_URL` isn't set to `/` or another non-publicly accessible URL, like `localhost`
