### ISSUE TITLE
UI settings always required?

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1181]
## Version Info
  - Directus version: bf5235156a

## Expected Behavior

When editing the UI settings of a field all options have an asterisk (*) next to them marking them as required. In a way that makes sense because often it is conceptual required to set those values (eg the min and max of a slider). On the other hand it's confusing because it does not get validated. Especially for the "Allow Null" checkbox of a INT field it's confusing.

I think those field's should either be not required at all (as they actually are not from a DB perspective) or each field should be configured in a sensible way to reflect it's corresponding semantics. In the later case the `require`ment should be validated correctly in give an error message.

When going the way of actually requiring and validating the fields there should be a mechanism to initialize the fields with valid values. Eg when switching from Numeric to Slider UI it would be nice to either *force* the user to set the slider config values or use default values.

Another way might be to remove the "required" flag from all ui settings but provide default values for all settings that are displayed as placeholders in the settings panel. This would show the user what happens if he does not enter any settings.

Currently the following is confusing:

1. I create a slider field
2. I look into the field's settings
3. I see that min, max and step are not set
4. I see the fields are required
5. I do not care and save anyway without entering any values
6. No error message

Now what happens? I have to try create a record to see that the slider has a min=0 max=100 step=1 set because those are the html default values for a input type=range

So either:
force me to enter min, max, step values
or:
show me what the defaults are when I enter nothing

## Actual Behavior

Just all fields are marked required but not validated accordingly

## Logs or Screenshots

![bildschirmfoto 2016-06-19 um 13 51 43](https://cloud.githubusercontent.com/assets/26493/16177143/3100e12c-3625-11e6-8eeb-e8d45be84ebf.png)

![bildschirmfoto 2016-06-19 um 13 53 45](https://cloud.githubusercontent.com/assets/26493/16177151/6b17c038-3625-11e6-91b4-7630df9c3923.png)

**Comment by WellingGuzman** [comment]
This was partially solved, as none settings are required. The rest will be addressed in this ticket #1023
