### ISSUE TITLE
The collection display template is not working in the M2O

### ISSUE THREAD

**Issue by abdonrd** [directus/directus#11825]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a `Profiles` collection with this display template:

<img width="849" alt="Screenshot 2022-02-23 at 20 39 49" src="https://user-images.githubusercontent.com/1007051/155395318-b7236a37-9ac7-430d-b655-4bdafbd29426.png">

And it works well in title of the edit detail view:

<img width="849" alt="Screenshot 2022-02-23 at 20 40 20" src="https://user-images.githubusercontent.com/1007051/155395406-775c1c5c-28f8-4716-9c6b-3c6bb9c0a5b2.png">

Also in the relationships leaving the display template empty:

<img width="417" alt="Screenshot 2022-02-23 at 20 42 33" src="https://user-images.githubusercontent.com/1007051/155395768-324c7b91-6b2a-49b5-abe1-534350d32804.png">

<img width="867" alt="Screenshot 2022-02-23 at 20 43 25" src="https://user-images.githubusercontent.com/1007051/155396824-cf94866d-5c01-487a-8d91-57aceac7424c.png">

I also have a `Countries` collection with this display template:

<img width="857" alt="Screenshot 2022-02-23 at 20 52 21" src="https://user-images.githubusercontent.com/1007051/155397253-fd97ed36-ff7b-4c14-8614-33b407b7aafb.png">

And it works well in title of the edit detail view:

<img width="845" alt="Screenshot 2022-02-23 at 20 53 47" src="https://user-images.githubusercontent.com/1007051/155397566-8fa71c28-3574-4d61-9266-43d3847c7ca9.png">

So far everything has gone well. 👏🏻 

🔴 But now, the Country relationship (also leaving the display template empty) looks bad:

<img width="850" alt="Screenshot 2022-02-23 at 20 56 33" src="https://user-images.githubusercontent.com/1007051/155397857-5a64a75a-dbd0-40db-94d5-2c760396d367.png">

<img width="858" alt="Screenshot 2022-02-23 at 20 53 00" src="https://user-images.githubusercontent.com/1007051/155397826-11774818-5625-448a-9fc4-955e2bdbc4d8.png">

In fact it seems as if the Country is trying to use the Profile template... 😕 

### To Reproduce

Described above.

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

16

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### What operating system are you using?

macOS Monterey (12)

### How are you deploying Directus?

Running locally

**Comment by rijkvanzanten** [comment]
Hi @abdonrd! Would you be able to share a schema snapshot with this configuration? 🙂

**Comment by abdonrd** [comment]
Ok! Let me simplify the application!

**Comment by rijkvanzanten** [comment]
Thanks! Saves me a ton of time and helps prevent mistakes when trying to reproduce the exact setup you mentioned 🙂

**Comment by abdonrd** [comment]
Here you have the `schema.yml` and also a `data.db` to easy setup!

[directus-example.zip](https://github.com/directus/directus/files/8127919/directus-example.zip)

**Comment by rijkvanzanten** [comment]
Thanks! ❤️

**Comment by abdonrd** [comment]
Probably a different issue, but...

Also leaving the `Display > Display template` empty:

<img width="857" alt="Screenshot 2022-02-24 at 00 28 41" src="https://user-images.githubusercontent.com/1007051/155427034-28a7cbcc-fab1-4590-8653-248ac2626282.png">
<img width="858" alt="Screenshot 2022-02-24 at 00 28 22" src="https://user-images.githubusercontent.com/1007051/155427037-e236a4e4-373e-4ec6-bd44-160d1cd191c2.png">

I see the IDs, and not the default Display from the field.

<img width="738" alt="Screenshot 2022-02-24 at 00 27 29" src="https://user-images.githubusercontent.com/1007051/155426849-8820201c-5d49-441a-b9c8-73902c57c999.png">

**Comment by rijkvanzanten** [comment]
Very similar if anything. Could be the same bug where it fails to extract the correct display template 🤔

**Comment by abdonrd** [comment]
@rijkvanzanten have you been able to see this? Thanks!

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten have you been able to see this? Thanks!

Yup! Can confirm the broken behavior based on your shared dump 👍🏻

**Comment by abdonrd** [comment]
> > @rijkvanzanten have you been able to see this? Thanks!
> 
> Yup! Can confirm the broken behavior based on your shared dump 👍🏻

Ooh! Thanks for your PR fixing it! 👏

**Comment by rijkvanzanten** [comment]
@abdonrd I was mostly waiting for #12082 before looking into it to make sure we didn't have another merge conflict on our hands in that one 😁
