### ISSUE TITLE
Code block feature is not visible in WYSIWYG toolbar

### ISSUE THREAD

**Issue by Vprasannaakumar** [directus/directus#11823]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When using WYSIWYG , code block feature is not visible. While adding WYSIWYG field to the collection, I selected all available toolbar items(44) in which Code block item is not available.
![image](https://user-images.githubusercontent.com/32242696/155348989-4f891ded-2881-4f15-8c0d-4b5438b0ed32.png)

![image](https://user-images.githubusercontent.com/32242696/155349249-1ac8195a-879e-4ac5-93a8-8defd946b398.png)
### 

### To Reproduce

1.Create a collection ex: post
2.Add WYSIWYG field , select all toolbar items
3. Try to add entry into the collection, when we see WYSIWYG toolbar code block option will be not visible 

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

16.14.0

### What database are you using?

SQLite

### What browser are you using?

Chrome

### What operating system are you using?

Linux 5.10.16.3-microsoft-standard-WSL2

### How are you deploying Directus?

running locally

**Comment by licitdev** [comment]
@Vprasannaakumar Please kindly elaborate on what `code block feature` is.

You are able to edit the HTML's source code via the `Edit Source Code` in the toolbar as shown below.

![image](https://user-images.githubusercontent.com/26413686/155362935-3ea0a22d-1677-425e-afb2-5bae2bebc64f.png) ![image](https://user-images.githubusercontent.com/26413686/155362295-3589f539-ab9e-4ca6-9b23-4dae12c153a2.png)

**Comment by rijkvanzanten** [comment]
I'll close this for now, as it seems to work as expected. (I also see the edit source code option in the original screenshot).

If you're talking about adding an additional feature that you feel is missing, please open [a new feature request](https://github.com/directus/directus/discussions/new) 🙂

**Comment by Vprasannaakumar** [comment]
Hi,
Thank you for your response.
The issue is regarding about **to embed code snippet** like java ,python etc while writing content. I didn't find this option in WYSIWIG editor. In markdown editor, by default it is showing. It would be helpful if it is present in WYSIWIG editor.

**Comment by sarkaramitabh300** [comment]
Is there a way to add code snippets in WYSIWIG editor?
![chrome_skQpqiMPTz](https://github.com/directus/directus/assets/12843606/6d50a51a-ccbf-4eb9-8d78-fcba1c2c8a3c)
something like this?
