### ISSUE TITLE
Creating a single_file field, then changing it back to Numeric

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1182]
## Version Info
  - Directus version: bf5235156

## Expected Behavior

The `relationship_type` and `table_related` columns in `directus_columns` should be reset to null.

## Actual Behavior

The columns stay set to MANYTOONE and directus_files.

This leads to the Relationship settings of the field to be visible even though the field is just a numeric field.

## Steps to Reproduce
 1. create a single_file field
 2. change it to numeric

## Logs or Screenshots
![bildschirmfoto 2016-06-19 um 14 14 25](https://cloud.githubusercontent.com/assets/26493/16177294/5973d1a2-3628-11e6-96d2-c749747a7029.png)

**Comment by benhaynes** [comment]
Looks good!
