### ISSUE TITLE
Showing old version number on snapshot

### ISSUE THREAD

**Issue by rashidpathiyil** [directus/directus#11834]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Created a snapshot from a fresh Directus 9.5.2
Generated snapshot showing 9.5.1
![image](https://user-images.githubusercontent.com/15140041/155478593-b7e5ad84-871c-483d-953e-49c7cf25ffc3.png)

### To Reproduce

Run ``npx directus schema snapshot ./snapshot.yaml``
Open It
Check Directus Version

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

v16.14.0

### What database are you using?

cockroachdb

### What browser are you using?

Edge

### What operating system are you using?

Windows 11

### How are you deploying Directus?

PaaS

**Comment by azrikahar** [comment]
I can't seem to reproduce this on a fresh `v9.5.2` docker image:

![image](https://user-images.githubusercontent.com/42867097/155481251-48655d53-aa22-4377-ba5d-5a68c6ad82da.png)

would you mind checking the version in `package.json` to see whether it's actually `v9.5.2`, or perhaps there is a mix up of different directus instances here?

**Comment by rashidpathiyil** [comment]
I am tying on PaaS, still showing 9.5.1

Package.json
![image](https://user-images.githubusercontent.com/15140041/155483136-096a34a7-7af1-4d8c-a426-920ef52e0032.png)

![image](https://user-images.githubusercontent.com/15140041/155483506-50450724-7e58-43a8-9fbb-a8c7b9a0b10c.png)

**Comment by azrikahar** [comment]
This is rather odd, since the command just grabs the version from the package.json as seen here:

https://github.com/directus/directus/blob/540867b80abc18eae1028cfc59140f1cd02816c6/api/src/utils/get-snapshot.ts#L4

https://github.com/directus/directus/blob/540867b80abc18eae1028cfc59140f1cd02816c6/api/src/utils/get-snapshot.ts#L24-L26

Would you mind running `npx directus -v` and see what version does it display?

**Comment by rashidpathiyil** [comment]
Run ``npx directus -v``
Output: 9.5.1

**Comment by azrikahar** [comment]
Not exactly sure what is happening here, but at least we can confirm your directus is not the latest `9.5.2` version. I noticed line 2 and line 13 of your `package.json` has an edited indicator on the left (I could be wrong), so how did you update it?

Perhaps you can also try `npm upgrade`, then do `npm list directus` (and also `npx directus -v`) to see is it updated correctly or not.

**Comment by rashidpathiyil** [comment]
Now it is showing as expected after following your instructions 
>Perhaps you can also try npm upgrade, then do npm list directus (and also npx directus -v) to see is it updated correctly or not.
