### ISSUE TITLE
checkbox UI for MTM

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1183]
It would be nice to have an additional, simplified UI for handle MTM fields: simple checkboxes.

Let's say I have a `People` table and a `Roles` table which are related MTM.

Now when editing an user instead of having a list of roles of this users to which I can add or remove items it would be nice to have just a few checkboxes like

[x] Administrator  -   [ ] Editor  -   [x] QA

which I can check or uncheck in order to assign roles - without the ability to create new roles and without showing any details on the roles.

In cases like this in which there are only a few possible items on one end of the relationship this would provide a simpler and more compact work flow.

**Comment by laszlokorte** [comment]
Another cool feature would be allowing the Tag UI to be used with MTM relationships and

**Comment by laszlokorte** [comment]
And using the Checkbox UI with the SET column type

**Comment by laszlokorte** [comment]
And using the Radiobuttons UI for MTO relationships

**Comment by benhaynes** [comment]
@laszlokorte Exactly. We actually had this in Directus 5 for relational UIs but they didn't get migrated in. The M2M fields could be displayed as a re-orderable list (how it is now), array of checkboxes, or multi-select list. Then, M2O had display options for dropdown or radio-buttons.

I think we should add these as options in the existing M2M and M2O core UIs – and they template get adjusted. @WellingGuzman just created an example of UI as a directory (`checkbox` is not just a JS file) so maybe that will be easier for managing multiple templates and the extended logic.

Does that sound like what you're thinking?

**Comment by laszlokorte** [comment]
yes

**Comment by WellingGuzman** [comment]
@laszlokorte right! this will be great.

**Comment by benhaynes** [comment]
@laszlokorte – we're still plowing through a huge pile of tickets, are you interested in trying your hand at coding this UI? Not sure how familiar you are with Backbone, but I see this as a display option within the existing M2M and/or O2M UIs.

Any interest?

**Comment by benhaynes** [comment]
**[Migrated to FeatHub](http://feathub.com/directus/directus/+46)**
**[Migrated to FeatHub](http://feathub.com/directus/directus/+47)**
**[Migrated to FeatHub](http://feathub.com/directus/directus/+48)**

Please use the [Directus FeatHub](http://feathub.com/directus/directus) to vote for features or make new request. Accepted feature requests will be added to GitHub Issues.
