### ISSUE TITLE
403 Forbidden modal shows when read-only fields display on Item Detail 

### ISSUE THREAD

**Issue by bcartier** [directus/directus#11830]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The 403 Forbidden modal is being shown when it should not. If you configure a Role to be able to Read, but not Update a given field, and that field appears on the Item detail form, you will see a 403 Forbidden modal, and then get the desired effect (the field appears, and is disabled).  Currently, the only workaround is to configure the field to "Hide Field on Detail" which prevents the Forbidden modal from appearing.  

Here is the error from the logs:

`{
    "level": 20,
    "time": 1645676339036,
    "pid": 42,
    "hostname": "directus-2-c74df48d9-xsmxf",
    "status": 403,
    "code": "FORBIDDEN",
    "extensions": {},
    "stack": "Error: You don't have permission to access this.\n    at RolesService.readOne (/directus/node_modules/directus/dist/services/items.js:246:19)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /directus/node_modules/directus/dist/controllers/roles.js:68:20",
    "type": "Error",
    "msg": "You don't have permission to access this."
}`

### To Reproduce

As described above

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

16.14.0

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Hi, would you mind elaborating more on the necessary steps to reproduce this, or perhaps a screenshot or a short clip? 

I'm seeing that the field is not editable but I could still edit other fields and save. However I think I might be misinterpreting your description here.

## Role permission

![FurjygLFSJ](https://user-images.githubusercontent.com/42867097/155467684-eb953ebf-10fb-4af2-8c1b-7f58ae7671cb.gif)

## Editing/Saving item

https://user-images.githubusercontent.com/42867097/155467551-e3a8e53f-18a4-4baf-9d7c-fc77168734e8.mp4

**Comment by bcartier** [comment]
Sorry for the noise, closing this ticket. 

One of the fields I was configuring as Read-Only was a M2O relationship to Directus Roles. I had missed setting read permissions on Directus Roles fields. I needed to allow read access to  Role Name and ID, which was causing the issue. 

Thanks for looking into it azrikahar!
