### ISSUE TITLE
Migrating UUIDs from Sqlite to Postgres fails

### ISSUE THREAD

**Issue by TnTGamesTV** [directus/directus#11847]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

While applying a schema to an instance of Directus running Postgres the application fails and Postgres does not allow the application of the foreign key constraint.

Important: The schema is exported from a locally running Directus (using SQLite) but this should not have any impact as the schema should be applicable to all database clients.

The relation is the system field "user_created".
As seen under "Errors Shown" Postgres complains about a type mismatch between the two fields.

Such a mismatch can be seen in the [schema](https://pastebin.com/yVrkt5mn) as it uses a "type: string" instead of "type: uuid".
      
After exporting the schema from a Directus instance running Postgres as the database client it is clear that the issue is a result of SQLite not supporting UUID natively. The schema assumes it will be used with SQLite or is not able to provide a SQL command for database clients that support UUID.

### To Reproduce

1. In a fresh instance of Directus using SQLite as a database client create a custom data type with the pre-filled "user_created" option.
2. Export a schema from this instance
3. Apply the schema to a fresh instance of Directus running Postgres as a database

### Errors Shown

ERROR:  foreign key constraint "properties_user_created_foreign" cannot be implemented
DETAIL:  Key columns "user_created" and "id" are of incompatible types: character varying and uuid.
STATEMENT:  alter table "properties" add constraint "properties_user_created_foreign" foreign key ("user_created") references "directus_users" ("id") on delete SET NULL

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

16

### What database are you using?

Postgres 10 (also tested with Postgres 14)

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
This is due to the fact that Sqlite doesn't have native UUIDs, which in turn means that those fields are read / treated as a string of 32 characters. The UUID primary keys in Directus are still created as actual UUIDs in Postgres, meaning that this relationship fails as we're now trying to relate a varchar(32) to a UUID.

**Comment by enzolupia** [comment]
Same issue here, everything run fine with sqlite3 and mysql, while using postegres I get 
> Key columns "user_created" and "id" are of incompatible types: character varying and uuid. 

when adding user_created column foreign key.
