### ISSUE TITLE
"Allow Null" does not alter table

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1184]
## Version Info
  - Directus version: bf5235156

## Expected Behavior

Setting the "Allow Null" setting should alter the table's column. Otherwise what is the difference between the "Allow Null" and "Required" setting of a field?

## Actual Behavior

It's not clear what the "Allow null" does for a numeric field

/edit: same for `select` field

**Comment by WellingGuzman** [comment]
Hi @laszlokorte apparently it does nothing. so, it's going to be removed.

**Comment by WellingGuzman** [comment]
@laszlokorte oh by the way on `select` it basically just let you choose an empty string as value. not modifying your table structure in no way. UI settings isn't not suppose to be to altering the table schema. or maybe not yet.

**Comment by laszlokorte** [comment]
Thanks. Now that you have fixed #1186 I can see how the option works for the select ui.

Maybe it would be more clear to rename the "Allow Null" UI option to "Allow Empty" or "Include Empty Option". Because "allow null" sounds like a technical database related term.
