### ISSUE TITLE
Select UI, INT column

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1185]
## Version Info
  - Directus version: bf52351

## Expected Behavior

When editing a record a select box field should have the currently saved value selected initially.

## Actual Behavior

The selectbox does not have the current value selected

## Steps to Reproduce
 1. Create a select field of type INT
 2. Edit the UI settings and provide `{"10": "X", "20": "Y"}` as json for the selectbox options
 3. select "Allow Null" and provide a placeholder "Nothing"
 4. create a record for that table, select "Y", save
 5. see that `20` is saved to the DB
 6. edit the record
 7. See that the selectbox has "Nothing" selected
 8. Now saving the record without doing anything resets the value in the DB to null (because "nothing" is selected)

Even if "Allow Null" is not selected or no placeholder is given this is the case.

**Comment by WellingGuzman** [comment]
Hi @laszlokorte I couldn't replicate the issue I followed all your step and it did work as expected.

on a side note  `{'10': "X", '20': "Y"}` is a malformed JSON, I used double quote. just letting know. it's has nothing to do though.

**Comment by laszlokorte** [comment]
Right, the single quotes are of course wrong. Anyway the problem for me persists.

The problem seems to be that `selectedValue` here:
https://github.com/directus/directus/blob/master/app/core-ui/select.js#L36

not the selected value but some other object:
![bildschirmfoto 2016-06-20 um 12 56 29](https://cloud.githubusercontent.com/assets/26493/16191847/863803ca-36e6-11e6-82ba-c7428814f1df.png)
so this equality check:
https://github.com/directus/directus/blob/master/app/core-ui/select.js#L47
always fails

Additionally I just noted that the selectbox always allows to select the null/empty option (even if allow_null is not set) because the option here:
https://github.com/directus/directus/blob/master/app/core-ui/select.js#L56
is read as either string `'0'` or string `'1'` which both evaluate to truthy in the the handlebar's `{#if}` statement.

**Comment by WellingGuzman** [comment]
@laszlokorte I've been trying to replicate this again after the recents changes but I can't replicate the selection failing.

Can you check and let me know if still happening?

**Comment by laszlokorte** [comment]
should I try the dev or the master branch?

**Comment by WellingGuzman** [comment]
@laszlokorte master branch, and let us know.

**Comment by benhaynes** [comment]
@laszlokorte any luck replicating?

**Comment by laszlokorte** [comment]
Its working now

**Comment by WellingGuzman** [comment]
Perfect, closing it.
