### ISSUE TITLE
try to delete file get foreign key constaint fails error

### ISSUE THREAD

**Issue by qddtdlko** [directus/directus#11852]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

![image](https://user-images.githubusercontent.com/81072363/155659618-8cbe6120-c525-4905-9b6c-a322ca9cc9de.png)

### To Reproduce

1. open project setting menu and upload a logo type of *.svg
2. go to files menu and find it, then select delete it.
3. get error "a foreign key constraint fails"

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

16.14

### What database are you using?

Mysql 8.0

### What browser are you using?

Chrome

### What operating system are you using?

Debian

### How are you deploying Directus?

Locally

**Comment by qddtdlko** [comment]
After many tests, cancel the setting of the file as logo can be delete it.
I think use a warning tip like "please cancel the logo first to delete it" will better for user

**Comment by azrikahar** [comment]
> After many tests, cancel the setting of the file as logo can be delete it.

That is correct 👍

> I think use a warning tip like "please cancel the logo first to delete it" will better for user

Definitely! We are currently tracking this over at #9507 as there are also other things to consider such as deleting a user that has an uploaded + being used file for example, so let's consolidate this over there.
