### ISSUE TITLE
Select UI, INT column, Required not validated

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1186]
To help us resolve your issue more quickly, please use the following template:

## Version Info
  - Directus version: bf52351

## Expected Behavior

When setting "required" for a select field it should be validated that something from the selectbox is selected.

## Actual Behavior

The selectbox is marked with an asterisk (*) but the even when selecting the empty option no error is reported.

**Comment by laszlokorte** [comment]
This slightly relates to #1184.

Unchecking "Allow Null" for the select ui settings should also alter the table's column and force the "required" checkbox to be checked.

**Comment by WellingGuzman** [comment]
@laszlokorte when you said "required" you mean checking "Allow Null"? if that was I got the issue.

**Comment by laszlokorte** [comment]
@WellingGuzman I think I was actually talking about the "required" checkbox on the field in the field list of the table.

But it's actually working now anyway. Thanks.
