### ISSUE TITLE
Validate JSON

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1187]
## Version Info
  - Directus version: bf52351

## Expected Behavior

When UI settings accept JSON as input, that JSON should be validated while editing the setting.

## Actual Behavior

Currently when inputting invalid json it get's just saved and then causes Directus to crash when editing a record because the UI tries to parse/use the invalid JSON.

## Steps to Reproduce
 1. Create a select UI field
 2. enter invalid json as "Options"
 3. save
 4. try create or edit a record for the corresponding table -> crash (json parse error...)

## Logs or Screenshots

![bildschirmfoto 2016-06-19 um 14 50 02](https://cloud.githubusercontent.com/assets/26493/16177424/2028143a-362d-11e6-9622-9cc9c0ba847b.png)

**Comment by WellingGuzman** [comment]
This is related to this one #1181, that one should be also implemented in order to fix this one.

We are not actually validating the UI settings. on step closer to that.

**Comment by WellingGuzman** [comment]
https://github.com/directus/directus/commit/9868a82646cc33f4927373894a72c07eaa19eae2 is not the solution but it will prevent from crashing the app.

The validation will be taken care of in this ticket. #1023
