### ISSUE TITLE
Visible column strip whitespace

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1188]
## Version Info
  - Directus version: bf52351

## Expected Behavior

The "Visible Column" fields (eg in the MTO ui settings) accepts a CSV of column names. It's convenient to type those name with additional space after the comma. like `title, foo, bar`.

This should work.

## Actual Behavior

It causes an error that the column ` foo` (with leading space) can not be found.

IMO the whitespace should be stripped. Additionally it would be nice to validate the column names while editing the settings to prevent an error later on.

## Logs or Screenshots

![bildschirmfoto 2016-06-19 um 15 14 33](https://cloud.githubusercontent.com/assets/26493/16177534/e6106776-3630-11e6-9a30-df60fb9b1cd3.png)

![bildschirmfoto 2016-06-19 um 15 14 39](https://cloud.githubusercontent.com/assets/26493/16177535/e7a52ffe-3630-11e6-89dc-b8d0c011c222.png)

**Comment by laszlokorte** [comment]
I just tried it again on the master branch. Now I am not getting an error anymore but if I type the column names with spaces ultimatley the MTO field table is not correctly displayed (columns are missing). If I remove the spaces the table is display correctly.

I assume the fix has only been applied to the validation but not to the place where the setting is used.

**Comment by WellingGuzman** [comment]
Hey @laszlokorte,

Good point, I fixed it on one to many before, instead of M2O.

Validating in the setting page will be addressed with this ticket https://github.com/directus/directus/issues/1023

**Comment by benhaynes** [comment]
Hey @WellingGuzman – I'll reopen this until we also have this fixed on M2O...

**Comment by WellingGuzman** [comment]
@benhaynes it was fixed on M2O, and then I fixed it on M2O Typeahead that it was missing. https://github.com/directus/directus/commit/f9a422bed42dc11fbdda75a8dd49cb431e0c78b2
