### ISSUE TITLE
Replace file operation disappears when file is not an image

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#11898]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Right now, the replace-a-file flow is triggered from a button on the image preview component. However, when the file is not an image, this functionality effectively disappears.

### To Reproduce

Upload any non-image file, like a PDF, and try to replace it.

### Errors Shown

n/a

### What version of Directus are you using?

9.6.0

### What version of Node.js are you using?

16.13

### What database are you using?

Postgres 13

### What browser are you using?

Safari 15.3

### What operating system are you using?

macOS Monterrey

### How are you deploying Directus?

Locally

**Comment by rijkvanzanten** [comment]
@benhaynes this is effectively a UX design oversight:

![CleanShot 2022-02-28 at 17 49 36@2x](https://user-images.githubusercontent.com/9141017/156071455-8ff57e97-6cc8-4cbe-aff0-6edd08d6c3ff.png)

The replace-file icon only shows up in the bottom right of the image preview, and only on hover (fairly invisible).

For files that don't have a preview (yet), like PDFs, the functionality simply vanishes:
 
![CleanShot 2022-02-28 at 18 00 20@2x](https://user-images.githubusercontent.com/9141017/156072636-b17ccefd-efe1-4f77-8dc6-a13ac9e5d782.png)

We should figure out where to put that button instead (the header is already getting pretty busy for files 🤔), or have some sort of default no-preview-available-preview box

**Comment by benhaynes** [comment]
I think the "Replace" and "Download" actions should both be moved to a preview box, as both are for the asset... and not the whole record (including metadata, etc). I also agree that these two actions will need to be more obvious... as they are both very important.

I'll work on a formal design for this, but generally, it should include:

* Icon for the file-type (with a catch-all for edge-cases)
* File name, clickable to open/download the file
* Text/button CTA for replacing the asset
* Progress bar (only when actively replacing)?

**Comment by benhaynes** [comment]
Here we go!

* Native previews for images, videos, audio files
* iframe/other for pdfs, or anything else related
* `code` component previews for text, json, csv, etc. files
* The following catch-all design for any other extensions/mime-types

![Screen Shot 2022-03-23 at 9 28 54 AM](https://user-images.githubusercontent.com/522079/159710554-945719c9-debf-4a20-b40f-dd76a7c8f343.png)
