### ISSUE TITLE
CLI Schema update chokes on removing interrelated collections

### ISSUE THREAD

**Issue by TErenberger** [directus/directus#11895]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The CLI schema update tool errors out when removing collections that have relations to each other. Specifically when there is a collection with an associated multilingual collection.  In this case both are to be removed, but one must be removed before the other to satisfy the db engine. 

### To Reproduce

1.  Start with a DB that has existing collections.

One of these collections has a multilingual component which means has an associated hidden collection containing the multilingual values.

2. Copy DB 
3. Remove both the collection and the associated multilingual collection
4. Use CLI tool to export schema.
5. Use CLI tool to import schema on original DB

### Errors Shown

``` 
21:29:10 🚨 error drop table "Customer_Service_Center_Page" - cannot drop table "Customer_Service_Center_Page" because other objects depend on it 
error: drop table "Customer_Service_Center_Page" - cannot drop table "Customer_Service_Center_Page" because other objects depend on it
    at Parser.parseErrorMessage (/powersource/apps/directus-cms/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/powersource/apps/directus-cms/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/powersource/apps/directus-cms/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/powersource/apps/directus-cms/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```
![2022-02-28 15_30_38-Data Model](https://user-images.githubusercontent.com/5725526/156061923-3e7bfc43-2bf5-400d-9c9b-9e5d23bbcdda.png)

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16.14.0

### What database are you using?

POSTGRES 13

### What browser are you using?

Chrome

### What operating system are you using?

Ran on Linux build agent

### How are you deploying Directus?

Docker

**Comment by TErenberger** [comment]
My guess at a solution would be that if this error happens to add that collection to a list to retry after all else have been tried. This could have a cap of 3 retries  before it gives up.

**Comment by rijkvanzanten** [comment]
Agreed. Another approach could be to first drop all relationships to/from the collections we're about to delete, and then delete them after that 🙂

**Comment by benosman** [comment]
I also ran into this issue in #15059, but hadn't seen this issue.

I thought of the two solutions mentioned in this thread: retrying and deleting relations first, and have implemented the first in my dev instance as it seemed easier to implement.

There is however another error that comes up, when the translation collection is deleted first, the schema cache still contains a record of the relationship between the two collections and when you then try to delete the primary collection you get an error about the relation being missing. The workaround is to refresh or mutate the schema for the collectionService instance, but I think that deleting the relevant relations first is probably the best way to go.
