### ISSUE TITLE
Images broken after adding to the WYSIWYG editor

### ISSUE THREAD

**Issue by arladmin** [directus/directus#11899]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I'm also facing the same issue: Image appears broken once added to the WYSIWYG editor.
![image](https://user-images.githubusercontent.com/64059154/156098097-95bfa9f7-983c-4c98-b802-3da63bf5c1de.png)

Also, if i try to access the image by its URL in the browser, i get this error:
```
{"errors":[{"message":"You don't have permission to access this.","extensions":{"code":"FORBIDDEN"}}]}
```

And refreshing the browser doesn't help either.

### To Reproduce

- Upload an image from your computer into a WYSIWYG editor.
- Image does not appear.

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

14.x

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Future reference: Duplicate of #10469, answered by https://github.com/directus/directus/issues/10469#issuecomment-1054992007
