### ISSUE TITLE
I can sort a One to Many field even when it's Readonly

### ISSUE THREAD

**Issue by abdonrd** [directus/directus#11892]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I can sort a `One to Many` field even when it's `Readonly`:

https://user-images.githubusercontent.com/1007051/156033948-c94f870a-441a-4119-b9b6-097e25ad759b.mov

I hope not to allow this to change.

### To Reproduce

See above.

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

16

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### What operating system are you using?

macOS Monterey (12)

### How are you deploying Directus?

Running locally

**Comment by rijkvanzanten** [comment]
Should be as simple as making sure the disabled state of the field is used in these two places:

https://github.com/directus/directus/blob/fc585000a0c603f75f275a5da153781d1b60a1ac/app/src/interfaces/list-o2m/list-o2m.vue#L24

https://github.com/directus/directus/blob/fc585000a0c603f75f275a5da153781d1b60a1ac/app/src/interfaces/list-o2m/list-o2m.vue#L36

probably by wrapping that in a computed value we can reuse for ease of maintenance:

```js
const allowDrag = computed(() => relation.meta.sort_field && !props.disabled)
```
