### ISSUE TITLE
Adding a M2O field to directus_roles blocks the app

### ISSUE THREAD

**Issue by Pachat** [directus/directus#11906]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Just adding a M2O throws you out of the app.
(verified also on a clean installation)

### To Reproduce

1. Create a collection `groups` with one input field `group_name`
2. Add an M2O field `group` in `directus_roles` and save.

### Errors Shown

You get a **No App Access**  `This user isn't allowed to use the admin app. ` on any (refreshed) page.
As you cannot enter the app anymore, you'd better use a previous version of your database.

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

16.14.0

### What database are you using?

SQLite version 3.37.0

### What browser are you using?

Firefox

### What operating system are you using?

Windows_NT 10.0.19043

### How are you deploying Directus?

locally

**Comment by Nitwel** [comment]
This seems to only happen on SQLite.

Request from the app:
![grafik](https://user-images.githubusercontent.com/22577866/157030669-c1ddb795-fe84-492c-b93a-ef292ee5980f.png)

Response from the api:
![grafik](https://user-images.githubusercontent.com/22577866/157030770-cd5ca4bd-f286-4b7d-9f35-39c506e72bfa.png)

**Comment by LevinGermann** [comment]
@Nitwel on the newest version (9.7.1) using **Postgres**, I encounter this issue now as well.
My request / response look exactly the same like in your screenshots.
I didn't create any new field on the directus_roles table. (Maybe relevant: I have a M2M custom field on the directus_users)

**Comment by azrikahar** [comment]
I believe this is related to #10842, where in this case, the role of users was nullified upon "updating" the `directus_roles` table (which is specific to SQLite as mentioned above):

![image](https://user-images.githubusercontent.com/42867097/160753374-f6027e54-e9dc-4c81-9e0e-dd3b7b32fe57.png)

Tested the above interaction again in Postgres just to be sure, and the issue does not exist in that case, so I'll close this issue in favor of tracking it over at #10842.

---

@LevinGermann Unfortunately I'm not sure what would be the issue in your scenario, but it's likely not related to this as it's a SQLite specific bug mentioned here, despite the error shown being the same. 

If you can reproduce the error for Postgres on a fresh installation (it'd be helpful to be as minimal as possible to avoid too many possibilities at play), feel free to open a new issue with said reproduction 👍 Thanks!

**Comment by LevinGermann** [comment]
@azrikahar Thanks for your response, I was able to fix it by following this comment: https://github.com/directus/directus/issues/12397#issuecomment-1081288408
So it appeared to have some permission migration issue that that only got fixed by resetting the permission to the recommended ones.
