### ISSUE TITLE
Collection Field Display Templates do not display singles spaces

### ISSUE THREAD

**Issue by 720720** [directus/directus#11902]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

![display](https://user-images.githubusercontent.com/27628635/156164086-cc0ed903-6c0f-4162-96a3-3e1078f5dd30.png)

Display Templates in Field Interface and Field Display do not display single spaces.

```
directus_fields
options: {"template":"{{id}} ({{name}})"}
display_options: {"template":"{{id}} ({{name}})"}
```

### To Reproduce

Insert a single space between two display template fields

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

16.13.2

### What database are you using?

MariaDB 10.5.12

### What browser are you using?

Firefox 97

### What operating system are you using?

Debian 11

### How are you deploying Directus?

Locally

**Comment by rijkvanzanten** [comment]
@licitdev Any brilliant suggestions on how to tweak this input based on your tremendous amount of research on the contenteditable nightmare in mentions? 😁

**Comment by licitdev** [comment]
@720720 I am unable to reproduce the issue on multiple browsers (Chrome, Safari, Firefox, Edge) and the related values interface for both M2O and M2M.
The spacing is displayed and works as intended. 
Please kindly provide a screen recording for us to investigate further. Thank you.

## Tests

https://user-images.githubusercontent.com/26413686/156208915-4aff76e9-824d-42d9-b239-7819481ea0f7.mov

Another test with bracketed field.

https://user-images.githubusercontent.com/26413686/156209256-935605c9-9022-4796-9da5-09c439e08681.mov

**Comment by licitdev** [comment]
I've just updated to Firefox 97 and I am able to replicate the issue.
Thank you @720720 for the details on the double space.

https://user-images.githubusercontent.com/26413686/156413170-55e1cb8c-abb2-428a-a53c-f883db667681.mov

@rijkvanzanten In this scenario, the text input for Firefox gets inserted outside of the `<span>`. We should look into ensuring text input gets inserted within the `<span>`. There were some discrepancies on how browsers handle "spacings" when typed into `contenteditable`, which might be related.

**Comment by nickrum** [comment]
I have been working on something for a while now that should fix this!

**Comment by rijkvanzanten** [comment]
@nickrum Is that _something_ still a thing? 😁

**Comment by rijkvanzanten** [comment]
Linear: [ENG-267](https://linear.app/directus/issue/ENG-267/collection-field-display-templates-do-not-display-singles-spaces)
