### ISSUE TITLE
Filter Rule "Paste Raw Value" not working

### ISSUE THREAD

**Issue by Pachat** [directus/directus#11907]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Nothing happens

### To Reproduce

1. Show a rule and click on Copy Raw Value
2. Verify in an editor that the raw value is in the clipboard
3. Go to another profile's rule on the same collection and click on Paste Raw Value

### Errors Shown

Nothing copied.
_Albeit click on "Edit Raw Value", Ctrl+V works_

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

16.14.0

### What database are you using?

SQLite version 3.37.0

### What browser are you using?

Firefox

### What operating system are you using?

Windows_NT 10.0.19043

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
This seems to work as expected on my end:

https://user-images.githubusercontent.com/9141017/156399674-d3ffc7b2-9a41-4a18-9cb0-41b8566502e3.mp4

Or am I misunderstanding what "rule" we're talking about? 🤔

**Comment by Pachat** [comment]
Thanks for the example.
Actually, it works on Edge.
But did you try it on Firefox as in the description?

**Comment by rijkvanzanten** [comment]
I did not! I wasn't sure what we were talking about in the first place 😁

**Comment by licitdev** [comment]
@Pachat Thank you for your report. Firefox only supports reading the clipboard in browser extensions. So, we will have to prevent users from "pasting" on unsupported browsers.

<img width="639" alt="Screenshot 2022-03-08 at 10 13 39 PM" src="https://user-images.githubusercontent.com/26413686/157255088-5ba9a7cf-70c5-466f-9eeb-57ddc2abb3f8.png">

Ref: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard#clipboard_availability
