### ISSUE TITLE
WYSIWYG readonly not working

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1190]
## Version Info
  - Directus version:bf52351 

## Expected Behavior

The WYSIWYG UI provides a readonly setting. Setting it to true does not affect the editor. It's still possible to edit the text.

Not sure if "readonly" makes sense for a wysiwyg. Either the option should be removed or it should work.

## Actual Behavior

"Read only" has no effect.

**Comment by WellingGuzman** [comment]
@laszlokorte apparently there's an issue with the wysiwyg library, but the thing the library allowed us to disable the editor, but it doesn't seem to be working.
