### ISSUE TITLE
consistent schema (ids, unsigned)

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1191]
## Version Info
  - Directus version: bf52351

## Suggestion

It's not a real problem but I think it would be nice if the db schema (both the directus tables and the custom ones) would be set up a bit more consistent:

* currently some ìd`columns are `INT(10)` some are `INT(11)`
* some ìd` columns are unsigned, some are not
* the `active` column of a new table allows NULL values. I think `NOT NULL` would be a sensible option.

When setting up a new MTO field it would make sense to restrict the data type and length options to exactly the type of the id column of the related table. (ie not showing those options at all)
There is no point in creating a INT(100) column for referencing an INT(11) column. Then that foreign key column should also be made `unsigned`.

**Comment by WellingGuzman** [comment]
> There is no point in creating a INT(100) column for referencing an INT(11) column. Then that foreign key column should also be made unsigned.

Hi @laszlokorte we are aware of this, so we have no plan to work on this right now, but I will open a new ticket with this information into Directus Wishlist.

Thanks,

**Comment by laszlokorte** [comment]
It just occurred to me that the length  option `x` for mysql integer `INT(x)`, `TINYINT(x)` does not really effect the storage capacity but only the output padding if ZEROFILL is set for the column.

Since ZEROFILL can not be set via directus UI I think the interface could be simplified by not providing the length option for INT/TINYINT/CHAR fields at all.

**Comment by WellingGuzman** [comment]
That's correct, you're right. There's not actual meaning but for padding, but still has meaning.

What I believe this needs to be optional parameter. I'm going to make it optional so the API doesn't required length for numeric types.

Although ZEROFILL can not be set, we plan on doing that, accepting fields options such as ZEROFILL and UNSIGNED.

Thanks @laszlokorte

**Comment by WellingGuzman** [comment]
Okay @laszlokorte I decided to remove it as the other numerics value doesn't require it. Thanks for this one. we will implement fields options in the future versions.
