### ISSUE TITLE
Directus Users does not respect role permissions

### ISSUE THREAD

**Issue by abdonrd** [directus/directus#11916]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Directus Users does not respect role permissions.

I have a `Manager` role with the `App Access` as `Recommended Defaults`.
So I should only be able to see my own user.

<img width="864" alt="Screenshot 2022-03-02 at 19 53 50" src="https://user-images.githubusercontent.com/1007051/156429008-76303c07-fb23-4b0e-91e8-dc91b337d9c4.png">

But check this video where I just refresh the page.
Sometimes it shows all (2) users 😱, and sometimes it shows just my user ✅.

https://user-images.githubusercontent.com/1007051/156428203-4a1846ba-a818-4606-979f-dec42a559bee.mov

### To Reproduce

Check above.

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

16

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### What operating system are you using?

macOS Monterey (12)

### How are you deploying Directus?

Docker

**Comment by abdonrd** [comment]
Another video record:

https://user-images.githubusercontent.com/1007051/156429647-31d0050e-fcc7-457b-9b97-468af8c3e271.mov

**Comment by rijkvanzanten** [comment]
The recommend defaults include read access to directus-users. Did you try setting the permissions to the absolute bare minimum?

**Comment by abdonrd** [comment]
Mmmm I see the same info when changing to `App Access Minimum`:

<img width="863" alt="Screenshot 2022-03-02 at 23 35 43" src="https://user-images.githubusercontent.com/1007051/156461564-18136ad9-b667-432c-908a-f32a87126e6f.png">

**Comment by abdonrd** [comment]
Anyway... Why does the response change randomly in the video?

**Comment by abdonrd** [comment]
But yeah, with the `App Access Minimum` looks like the response is always the same:

https://user-images.githubusercontent.com/1007051/156462215-54e86446-ee99-4e5f-b1b3-ed3c42e2fc72.mov

**Comment by azrikahar** [comment]
> Anyway... Why does the response change randomly in the video?

Just wondering, could it be there's multiple instances (via pm2 for example) without a shared redis/memcached cache here? The alternating behavior reminds me of round robin load balancing to me, meaning it's bouncing between one that has the correct updated permissions, whereas the another one is running stale older permissions.

**Comment by abdonrd** [comment]
@azrikahar we are using a Kubernetes cluster. The deployment has two pods. And the load balancing is done by Ingress.

And we don't have any kind of cache.

**Comment by rijkvanzanten** [comment]
> And we don't have any kind of cache.

There's (memory) cache enabled by default, so in this case Azri is correct: you're seeing one instance respond from a different cache than the other instance 🙂

**Comment by abdonrd** [comment]
Oh! But the documentation says the default value for the cache is `false` 🤔

https://docs.directus.io/configuration/config-options/#cache

**Comment by rijkvanzanten** [comment]
> Oh! But the documentation says the default value for the cache is `false` 🤔
> 
> https://docs.directus.io/configuration/config-options/#cache

For the content-cache, yeah! The schema cache is still enabled by default 🙂

**Comment by rijkvanzanten** [comment]
> > For the content-cache, yeah! The schema cache is still enabled by default 🙂
> 
> Hmmm what do you mean with the schema cache? 🤔

There's some caching Directus does internally to speed up the overall performance (we don't want to introspect the whole database every request for example) which is enabled by default. When running Directus load balanced, either use a shared cache storage (like Redis) or disable all caches 👍🏻

**Comment by abdonrd** [comment]
> There's some caching Directus does internally to speed up the overall performance (we don't want to introspect the whole database every request for example) which is enabled by default.

Ok! And seeing what happens in this issue... Roles are cached in that schema, right?

> When running Directus load balanced, either use a shared cache storage (like Redis) or disable all caches 👍🏻

Ok, thanks!
I'll see if we can add Redis. Anyway, how do I disable all caches?

**Comment by abdonrd** [comment]
> Ok, thanks!
> I'll see if we can add Redis.
> There are documentation about that? And how do I disable all caches?

Oh! I just see the `CACHE_SCHEMA`

**Comment by abdonrd** [comment]
> Ok! And seeing what happens in this issue... Roles are cached in that schema, right?

Oh! And now I just see the `CACHE_PERMISSIONS`!
I assume this causes the issue.

**Comment by rijkvanzanten** [comment]
Yeah! Those are the two you're looking for :) 

If you scroll a little further down on the same page, it goes into how to setup memcached/redis as well 🙌🏻

**Comment by abdonrd** [comment]
Yeah! Maybe my fault, but...

As the Cache section starts with:
> Directus has a built-in **data**-caching option. [...]

And in the table the first option is `CACHE_ENABLED` witht the `false` default...

I assumed all caching would be disabled.

**Comment by rijkvanzanten** [comment]
Fair enough! (cc @erondpowell)

**Comment by rijkvanzanten** [comment]
Closing this as I believe the OP issue was found to be configuration + caching, and we're tracking the docs update elsewhere 🙂
