### ISSUE TITLE
One of these things is not like the other

### ISSUE THREAD

**Issue by paragonie-scott** [directus/directus#1193]
![directus_ad](https://cloud.githubusercontent.com/assets/11591518/16180965/545c2d20-3661-11e6-88a1-0f64c51c62f1.png)

https://github.com/directus/directus/blob/bb359ebfdf68477056ca82972ffa7dbc8bd80025/api/core/Directus/Auth/Provider.php#L212-L215

Not only are you not following best practices for user authentication, that particular arrangement (`sha1(salt || password)`) is a classic setup for a [length-extension attack](https://blog.skullsecurity.org/2012/everything-you-need-to-know-about-hash-length-extension-attacks).

Also, [don't use `uniqid()` as a salt generator](https://github.com/directus/directus/blob/f6020ab1bb8bf0dd7e316c1825ae8dde3ad08517/installation/query.php#L54).

----

Recommendations:

* [Store passwords securely](https://paragonie.com/blog/2016/02/how-safely-store-password-in-2016)
* [Use a CSPRNG](https://github.com/paragonie/random_compat)

**Comment by WellingGuzman** [comment]
Hi @paragonie-scott thanks for the recommendation we help us make Directus more secure.

To be honest we've been aware of the use of `uniqid()` and we happen to address all this soon, we have been working on a lot of stuff and bug fixing right now.

We will take some time to work on security issues, which is also important.

**Comment by paragonie-scott** [comment]
I can sympathize with having all your spare time accounted for with bug fixing, etc.

As a security researcher, however, I do take issue with products claiming to adhere to best practices and then, it turns out, actually don't. Security is hard. Cryptography is one of the more annoying aspects of security, where things like "comparing strings" can lead to [disastrous results](http://blog.ircmaxell.com/2014/11/its-all-about-time.html). Unless you happen to have access to security expertise through the community or on a contract basis, it would be wise to reword that section so you don't give your users a false sense of security.

**Comment by benhaynes** [comment]
@paragonie-scott – Absolutely, we 100% agree. We've been chatting with a few folks adept in security (always looking for more!) and are moving into big security update/push over the next few weeks. Security audits/experts aren't cheap and being open-source we're always looking for community specialists who are interested in assessing/contributing to our framework. 

If you have any interest in providing insight or pull-requests we'd love to chat with you further. Just sent you a Slack invite just in case ;)

In the meantime we'll look into adjusting the copy on our marketing site to better reflect the current state of our auth.
