### ISSUE TITLE
Attributes stripped from HTML editor

### ISSUE THREAD

**Issue by jeremybradbury** [directus/directus#11931]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Using the HTML editor in the WYSIWYG editor strips "invalid" attributes. It looks like some sort of linting is happening without my knowledge or consent. 

Without any warning whole attributes are removed upon saving the field.

In this particular case I am using "experimental" features for the video tag that already supported in major browsers.

The only obvious workaround is to build a custom template and not allow users to add any videos in the content areas.

### To Reproduce

start with this:
```
<video muted autoplay playsinline loop controls disablepictureinpicture disableremoteplayback controlslist="nodownload" preload="auto" src="/file.mp4"></video>
```

or even this

```
<video muted="muted" autoplay="autoplay" playsinline="playsinline" loop="loop" controls="controls" disablepictureinpicture="disablepictureinpicture" disableremoteplayback="disableremoteplayback" controlslist="nodownload" preload="auto" src="/file.mp4"></video>
```

to get this after saving the source code editor and reopening

```
<video src="/file.mp4" preload="auto" autoplay="autoplay" loop="loop" muted="muted" controls="controls"></video>
```

See [here ](https://jsfiddle.net/JeremyBradbury/h4z8sf3c/) for desired results.

### Errors Shown

attributes are stripped from the video tag by the editor: disablepictureinpicture disableremoteplayback controlslist="nodownload" 

FWIW, IMO an html/code editor *should* highlight syntax issues, it *should* ***not*** make "syntax corrections automatically on save". If i break my html it's my fault and we shouldn't ever have an "editor that knows better than the human".

Also note, I had to check "latest version" to submit this issue, but we're 1 patch behind, because 2 has breaking changes and we need to plan for a refactor. 

### What version of Directus are you using?

v9.5.1

### What version of Node.js are you using?

14.17.0

### What database are you using?

Postgres 10

### What browser are you using?

Chrome, Brave & Firefox all yield same results

### What operating system are you using?

Windows & Linux

### How are you deploying Directus?

locally & via systemd service in staging

**Comment by jeremybradbury** [comment]
@rijkvanzanten thanks for the help.

So you're maintaining your own whitelist of attributes, presumably from the tinymce docs in order to "fix code mistakes for users" inside code, but the overrides are stored in the database?

Again, I would say that a code editor, should have no automatic stripping of code, that wasn't placed their by the site owner. If I wan't to stop users from adding images or invalid attributes that should be an option I choose, not a default.

If you think the current default is great and won't be changing it... then at least give us some options like a site setting to override this, rather than having to slap this regex hack into every item's metadata.

**Comment by rijkvanzanten** [comment]
> So you're maintaining your own whitelist of attributes, presumably from the tinymce docs in order to "fix code mistakes for users" inside code, but the overrides are stored in the database?

Nope, we're not maintaining that. This is TinyMCEs default, and we simply don't override it by default.

> Again, I would say that a code editor, should have no automatic stripping of code, that wasn't placed their by the site owner. 

The code editor interface (different from the WYSIWYG) editor doesn't. The "edit source code" operation of the wysiwyg simply edits the raw html in the contenteditable portion of the editor, so will also be affected by the same logic that is applied to regular user content. I disagree that the wysiwyg should allow for anything by default, as that would mean non-technical users could paste in any xss attack under the sun, and hurt your output website.

> then at least give us some options like a site setting to override this

Feel free to [open a feature request](https://github.com/directus/directus/issues/new/choose) 👍🏻

**Comment by jeremybradbury** [comment]
>I disagree that the wysiwyg should allow for anything by default, as that would mean non-technical users could paste in any xss attack under the sun, and hurt your output website.

Well this is why there is a publishing workflow and any untrusted users can only create drafts. Currently any user who is allowed to edit html is a trusted user in our system and we can add zero trust users any time. 

There is no clean way to add to the whitelist, only replace it with some long/complex ruleset and then carefully add a few missing attributes.

To me, it seems like a wildcard whitelist with a much shorter blacklist would suffice for XSS concerns if you really need to allow untrusted users to manage content. this would need far less maintenance by maintainers and users alike.
