### ISSUE TITLE
Incorrect Composer Dependencies Help Link

### ISSUE THREAD

**Issue by timbuckingham** [directus/directus#1194]
## Version Info
  - Directus version: 8638bf1df78eeb9075731005bd562a0b08404513
  - PHP version: 7.0.0
  - MySQL version: 5.5.42
  - Web server: Apache
  - OS name and version: OS X 10.11

## Expected Behavior

Linking to a help page about which composer dependencies need to be installed.

## Actual Behavior

Links to https://github.com/directus/directus/wiki/6.-Development-Build#step-4-install-dependencies

## Steps to Reproduce
 1. Being Directus installation
 2. Get to the review step without installing composer depencies
 3. Click the ? icon below "No"

**Comment by WellingGuzman** [comment]
hey @timbuckingham Thanks for reporting this I will take a look at this later today.

**Comment by WellingGuzman** [comment]
Sorry @timbuckingham I took too long to push this fix.
