### ISSUE TITLE
Discord Oauth 2 - client id required error

### ISSUE THREAD

**Issue by liho00** [directus/directus#11956]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I found a bug AUTH_DISCORD_CLIENT_ID="replace with raw of number" return error, if i insert an alphabet between the number it works...this is due to discord client id is all pure number...

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/77238199/156878140-27912c1e-055a-4b72-9cab-895318ca6a42.png">

We should accept string && number for client_id

Hence can we request the fix for the AUTH_<PROVIDER>_CLIENT_ID to accept pure raw number without alphabet..? Thanks in advance

### To Reproduce

I found a bug AUTH_DISCORD_CLIENT_ID="replace with raw of number" return error, if i insert an alphabet between the number it works...this is due to discord client id is all pure number...

### Errors Shown

<img width="862" alt="image" src="https://user-images.githubusercontent.com/77238199/156875087-d4d5bddb-e359-4a2a-aa57-be9d56c4d6e2.png">

Im not sure whether directus env passing number to openid-client or openid-client reading the env as number..

### What version of Directus are you using?

9.6.0

### What version of Node.js are you using?

16.0.0

### What database are you using?

SQLite v5

### What browser are you using?

chrome

### What operating system are you using?

macos

### How are you deploying Directus?

locally

**Comment by liho00** [comment]
opened a pr at openid-client packages https://github.com/panva/node-openid-client/pull/477

**Comment by liho00** [comment]
I opened a new pr to ensure passing correct client id type to openid-client

**Comment by liho00** [comment]
found the real root cause, its causing from the tryJSON 
<img width="561" alt="image" src="https://user-images.githubusercontent.com/77238199/156877895-b928b204-2dcd-4f99-80cb-7cf74a07914b.png">

**Comment by aidenfoxx** [comment]
I think you can just use `AUTH_DISCORD_CLIENT_ID="string:123"` and it should work.

**Comment by aidenfoxx** [comment]
@liho00 Also, if that's your REAL client id and secret you need to delete that screenshot ASAP.

**Comment by liho00** [comment]
> string:

perfect its working...

**Comment by liho00** [comment]
> @liho00 Also, if that's your REAL client id and secret you need to delete that screenshot ASAP.

yes will delete now, thanks for the advice.

**Comment by azrikahar** [comment]
Thanks for the all the investigation here. This just reminded me that it should be the same "should not cast env to number" issue faced by another user setting it up for Slack over here: #9521, which is still open as of now hence why you're facing it as well.
