### ISSUE TITLE
Bower implementation

### ISSUE THREAD

**Issue by WellingGuzman** [directus/directus#1196]
Quick reminder that we should manage all the front-end libraries using Bower, or similar.

**Comment by benhaynes** [comment]
@jel-massih Have you used Bower? This might be a good (easier) ticket to refamiliarize with.

**Comment by benhaynes** [comment]
**[Migrated to FeatHub](http://feathub.com/directus/directus/+45)**

Please use the [Directus FeatHub](http://feathub.com/directus/directus) to vote for features or make new request. Accepted feature requests will be added to GitHub Issues.
