### ISSUE TITLE
Directory/File Organization

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1197]
- [x] Move composer to root
- [x] `ui`, `listviews` and `extensions` to reside inside `custom`
- [x] `media` becomes `storage` with all subdirectories (including `adapters`)

**Comment by WellingGuzman** [comment]
@benhaynes should we leave this open until we change the `media` directory into `storage`? or wait to a future version?

**Comment by benhaynes** [comment]
We couldn't change the `media` directory because it breaks Hosted? Or backwards compatibility? Or was it just too much work for now?

It'd be good to get that directory renamed/reorganized earlier – so I don't want to push it off too far if we don't have to.
