### ISSUE TITLE
WYSIWYG interface displays nothing sometimes

### ISSUE THREAD

**Issue by d1rOn** [directus/directus#11989]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The contents of WYSIWYG editor don't display sometimes.

### To Reproduce

1. Create a collection "Test".
2. Add field with WYSIWYG interface.
3. Create an item in this collection.
4. Go back to items list and then go to item edit page. The editor content will most likely be empty.

### Errors Shown

No errors are shown.

### What version of Directus are you using?

9.5.2, 9.6.0

### What version of Node.js are you using?

16.13.0

### What database are you using?

MySQL 5.7.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

locally

**Comment by licitdev** [comment]
@d1rOn I am unable to reproduce your issue, but I do see your PR with improvements for the WYSIWYG interface. Do you have an example of what data you're inserting to the wysiwyg resulting in the contents not displaying?

https://user-images.githubusercontent.com/26413686/157179766-d4c01739-3aec-4339-8f39-811f08663c2b.mov

**Comment by licitdev** [comment]
@d1rOn Can you try to undo the changes you've done on `app/src/interfaces/input-rich-text-html/input-rich-text-html.vue`? I faced the issue you've shown in the screen recording only after implementing the below code from your PR.

https://github.com/directus/directus/pull/11990/commits/dab155d816e7423bed9ef1f8ed85835bec96633c

**Comment by d1rOn** [comment]
@licitdev 
After bootstrapping a new DB from scratch I was determined that nothing was changed. The content of editor was still not displayed sometimes.

Then I was tried to work with Directus in Chrome Incognito mode and this partially worked: one part of issue do not reproducing now (italicized below). The second part still reproducing.

Two parts of issue:
1. _Editor not displays its content sometimes._
2. Editor do not observe changes in TinyMCE displayed in drawer (editor in related collection).

First part of issue was that the editor was sometimes received this content early that field value was passed into editor:
```
<p>&nbsp;</p>
<div id="wsc-content-script-id" style="display: none;" data-wsc-content-script-id="1646767395835"></div>
```
This was overwriting the contents of the editor.
It really is related to some Chrome extension. I haven't figured out which one yet.
In PR #11990 I was fixed that by restricting change value of disabled field. (Because of field becomes enabled when its value was passed first time).

The second part of issue is in that the actual code binds MutationObserver to TinyMCE node by querying the DOM by id=<field_name>. And if in the current collection and the related collection **fields has the same name**, binding made incorrect.
This has also been fixed in the PR #11990.

Also I checked above PR on fresh installation of Directus in Chrome Incognito mode. All parts of this issue are not reproducing with it and all seems to work fine.

**Comment by iksent** [comment]
I've experiencing the same issue.
And I noticed, that you should double click to get all translations wysiwygs saved:

Single Click:

https://user-images.githubusercontent.com/32956521/158964141-e0fc7993-98d5-4d12-933b-e6c413c0cd80.mov

Double Click:

https://user-images.githubusercontent.com/32956521/158964174-6224034d-0ca8-4f7a-943f-065b8fa8203d.mov

**Comment by licitdev** [comment]
Hello @iksent, PR #12216 should resolve this double click issue. 
Thank you for your detailed issue reports with screen recording! 👍🏻

https://user-images.githubusercontent.com/26413686/158975914-4ac4d0f7-357d-4bce-8575-9355211a07af.mov
