### ISSUE TITLE
List view column headings do not obey hidden settings by default

### ISSUE THREAD

**Issue by chrisys** [directus/directus#1199]
## Version Info
  - Directus version: cc524c6

## Expected Behavior
When a column within a table is marked as hidden, it should no longer appear in the list views for any user groups.

## Actual Behavior
When a column is marked hidden, it does display in list views for all users until the list view is customised. The hidden column is visible until the columns visible are customised using the cog on the right hand side of table header; as soon as this is saved, even without making any changes, the columns marked hidden disappear.

## Steps to Reproduce
 1. Create table with a few columns
 2. Go to list view and set column B to visible
 3. Go to settings for this table and mark column B as hidden
 4. Return to list view - column B is still visible which is incorrect
 5. Click cog to edit visible columns, click save
 6. Column B now disappears

**Comment by WellingGuzman** [comment]
@chrisys Thanks for reporting this I will take a look at this one.

**Comment by WellingGuzman** [comment]
hey @chrisys on Table Settings now you will see `Hide List` and `Hide Input` which are two separate things, `Hide List` will hide the field from being listed (ex. at the table listing) and `Hide Input` will hide it from being displayed on the editing page.

I hope this helps, and let me know if you have any question.

**Comment by chrisys** [comment]
@WellingGuzman Nice one! Will pull and give it a go shortly.
