### ISSUE TITLE
user insert fails on fresh install

### ISSUE THREAD

**Issue by melfnt** [directus/directus#1200]
## Version Info
  - Directus version: 6.2.8
  - PHP version: PHP 7.0.4-7ubuntu2.1 (cli) ( NTS )
  - MySQL version: mysql  Ver 14.14 Distrib 5.7.12, for Linux (x86_64) using  EditLine wrapper
  - Web server: Apache2
  - OS name and version: Ubuntu 16.04 x86_64

## Expected Behavior
User is correctly inserted after clicking the add button

## Actual Behavior
An error message shows up stating "query failed" (more details follows)

## Steps to Reproduce
 1. Attempt to add a user
 2. Fill the information box with first name, last name et cetera
 3. clic on the green button on the top to confirm adding the user

The failing query is (I changed backtick with quotation mark):
`' INSERT INTO 'directus_users' ('group', 'active', 'salt', 'access_token', 'reset_token', 'reset_expiration', 'last_login', 'last_page', 'ip', 'last_access', 'first_name', 'last_name', 'email', 'email_messages', 'password', 'token', 'position', 'phone', 'location', 'address', 'city', 'state', 'zip', 'avatar') VALUES ('2', '1', '5773e2625c2a3', '', '', '', '', '', '', '', 'Lucio', 'Messina', 'lucio@computerlucio', '0', '$2y$12$xNAg1QwVsUUGsnds3iqsMOiPPujiqyUEpjxUTpZL3Xw/V1/ySnhqe', 'Ws6A97FUtBKrAAIZ', '', '', '', '', '', '', '', '//gravatar.com/avatar/f94d734ce9a190973c10227c6d7c0b81?s=100&d=identicon&r=g'); `
I tried to exec it manually from mysql cli and I got this error:
`ERROR 1292 (22007): Incorrect datetime value: '' for column 'reset_expiration' at row 1`

This was a very very fresh install of directus

**Comment by WellingGuzman** [comment]
Hey @melfnt Is there by any change STRICT mode enabled in your MySQL server? This is an issue we are having, there's nothing we can do right now, but ask you if it's possible to disable strict mode, it has been reported before #395.

We will see what we can do about this as this is an issue that's being reported so many times.

**Comment by melfnt** [comment]
Thank you, @WellingGuzman that solved my problem.
But can you please release a version of directus that can be used without disabling the STRICT mode?

**Comment by WellingGuzman** [comment]
Hi @melfnt we will be work on that, I'll close this ticket so this will be solve in #395
