### ISSUE TITLE
When editing translations, the existing one gets reset

### ISSUE THREAD

**Issue by LevinGermann** [directus/directus#12013]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When I open a translation inside a M2O table and edit a language, the original value disappears.
See example:

https://user-images.githubusercontent.com/9347206/157072405-5fac47b4-a083-4d0f-949d-93d8e7c9abef.mov

This issue is happening as well in v9.4.2
I was hoping first that this was related to https://github.com/directus/directus/issues/11509 which was fixed in 9.6.0 (even though my translations are not singleton), but seems like that's not the case. :(

### To Reproduce

1. Open a translation (from a M2O, not sure if this is needed though) where a translation is already set
2. Edit a value of another language
3. The original translated value becomes empty

### What version of Directus are you using?

9.6.0

### What version of Node.js are you using?

v16.7.0

### What database are you using?

PostgresQL 13.2

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by msn0** [comment]
The same here on 9.6.0

**Comment by olivieralther** [comment]
We have the same problem (also running 9.6.0). Unfortunately this makes the system very unreliable when working with external translators.

**Comment by sepios87** [comment]
Helo, I have almost a similar problem with the title of entities : 
https://github.com/directus/directus/issues/12270#issuecomment-1074890890
