### ISSUE TITLE
Table creation issue

### ISSUE THREAD

**Issue by lukasumlandt** [directus/directus#1201]
## Version Info
  - Directus version: directus-6.2.8
  - PHP version: 7.0.8
  - MySQL version: mysqlnd 5.0.12-dev (10.1.13-MariaDB)
  - Web server: Apache/2.4.18
  - OS: Windows 10 Pro 64bit / Ubuntu Server 32bit (same issue)

## Expected Behavior
Table should show up and be editable (and no backend freeze of course)

## Actual Behavior
Creating table (it shows up in phpmyadmin), freezing and not showing up below "tables"

## Steps to Reproduce
 1. set another backend url than productive-page url 
 2. create a table with some fields
 3. try to look below tables 

## Logs or Screenshots

`Error: Uncaught TypeError: Cannot read property '_listenerId' of undefined
File: http://dev.directus/assets/js/libs/backbone.js?bust=o7nk7lhp95fu4j443fqek8a6c4
Line:219`

**Comment by WellingGuzman** [comment]
Hi @lukasumlandt Thanks for reporting this, but what did you mean by "_set another backend url than productive-page url_"?

I'm sorry I do not understand the step to reproduce the issue.

**Comment by lukasumlandt** [comment]
Hey @WellingGuzman Sorry for the bad description, i meant to set the url of the backend (directus itself) to "http://directus.dev" and the global setting to "http://frontend.dev".

I just tried to manage the page from another domain and not from a "/cms"-subdirectory.

**Comment by WellingGuzman** [comment]
If I understood correctly what you are trying to do is have the Directus admin in one domain and having your frontend site in another domain.

Directus doesn't have any "frontend" part. any frontend solutions should be code by yourself.

The global settings `project name` it's just a quick way to jump into your site whatever that could be, which is it's not attached to Directus in anyway.

Am I missing something?
