### ISSUE TITLE
Language Translations

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1203]
Directus now has multilingual support – and we're looking for anyone interested in helping translate our [English default language file](https://github.com/directus/directus/blob/master/api/locales/en.json) into other languages. It's as easy as copying that `en.json` file and changing the values!

PR any translations into [this Directory](https://github.com/directus/directus/tree/master/api/locales).

🇺🇸  @benhaynes – I can handle this ;) Though I always love help/corrections!
🇫🇷  @christophemarois – you had mentioned helping with French, still interested?
🇪🇸  @WellingGuzman – you've got Spanish covered?
🇩🇪  @katywings – German! Bitte...
🇨🇳  @TigerHix & @Gfast2 – Chinese! 谢谢...
🇧🇷  @michaelnagy – Brazilian/Portuguese! Obrigado... 
🇮🇹  @AeonZh – Italian! Grazie...
🇳🇱  @RijkvanZanten – Dutch! Dank je...

**Comment by katywings** [comment]
I could help with the german translation and am at your disposal :)

**Comment by WellingGuzman** [comment]
Amazing @katywings that would be a huge help.

You can duplicate the [English Translation file](https://github.com/directus/directus/blob/master/app/locales/en.json) into `de.json` and start translating.

_Danke schön_ :)

**Comment by katywings** [comment]
You're welcome. However there is something to talk about before I begin xD, do you prefer formal or personal pronunciation? ([Wiki](https://en.wikipedia.org/wiki/T–V_distinction#German)

"Du oder Sie?"

It will take some time anyway - I will work on it while setting up a new backend ;)

**Comment by WellingGuzman** [comment]
Good question, I believe formal will be best.

Now that you brought this to topic we should be considering this for all translation.

Any thoughts @benhaynes?

**Comment by benhaynes** [comment]
Sorry for the late response – I agree that formal is probably better. It would be nice for Directus to be more approachable and casual, but I think clarity and professionalism is better for corporte end-clients.

Thanks you so much for your help @katywings – we're really excited to get more translations in the platform!

**Comment by benhaynes** [comment]
@katywings – Any luck with the translation? Let us know if you run into any problems so we can help resolve them. Thanks again!

**Comment by katywings** [comment]
@benhaynes I am working on it, but as it isn't my primary task I will need some time - also I had a large project the last few days, therefore I neeed to move this tasks priority a little bit down, but it looks like a can work more on it in the next weeks ;)

**Comment by RabbitMC** [comment]
Is it possible that I help you? Let me :)

**Comment by RabbitMC** [comment]
where can I find the current state? Is there a branch?

**Comment by katywings** [comment]
Hmm not in a public repo, i started working on it in a private environment, but I can copy it into a public directus clone if you need it somehow :)

**Comment by benhaynes** [comment]
Thank you @RabbitMC and @katywings – no rush, I was just curious how things were going. If there's anything I can do to help just let me know!

**Comment by katywings** [comment]
So I wanted to give you a quick update about the translation into german. Please have a look at the following pull request: #1223 

While working on it, i saw some special cases which probably need your attention:

- "Activity": Is this word used for singular or plural cases? In german often times we speak about "Aktivitäten" which is plural - while in english it is used as "Activity" and not "Activities"
- "Visit project": I know its the same in the english file but is it really obvious for the user what is meant by this? Wouldn't it be better to say something like: "Visit project homepage" or "Visit project website" or so?
- "Directus User Guide": We often keep the original label for such things, because it will be easier found with google (especially when the User Guide is not translated into german) - Do you want that this is translated?
- "Personalize this instance of Directus to fit your organization’s needs": 
    - I don't know but this item sounds somehow not perfect in my ears: everywhere is the focus layed towards the word "Project" so it sounds pretty wrong that in this case the word "organization" is used
    - The 1 to 1 german translation from "Directus instance" to "Directus Instanz" isn't really used to often and sounds very technical - therefore I used "Directus Installation", its a pattern which is used quite often, but also keeps its technical background :)

**Comment by benhaynes** [comment]
Hey @katywings – sorry for the late reply...

* **Activity**: It is for all Activity (things that happen) within Directus. So _not_ "Activities"
* **Visit Project**: Directus is written to manage any type of database-driven project, not just sites. That's why we used that word. BUT, since that field only links to a URL, what you said _does_ make more sense. Why don't we use "Visit Project Website"
* **Directus User Guide**: Hmm, good point. But I think that since this is in the Core App and therefore has a `noindex` to not be tracked, it's OK to translate.
* **Personalize...**: I 100% agree, good catch! Let's shift from "organization" to "project"... so: `Personalize this Directus instance to fit your project needs`. As for the translation, I think "Directus Installation" works just as well as Instance – so let's use that!

Thank you so much for your recommendations, they are all spot on. Let me know if you have any other questions or thoughts on this.

**Comment by TigerHix** [comment]
I can help with Chinese translation.

People here need to start using headless CMS like this one. As far as I have seen, they _love_ to reinvent the wheel and always come up with a "CMS" that bugs are everywhere and no one wants / knows how to fix.

**Comment by michaelnagy** [comment]
I can help with Brazilian Portuguese translation.

**Comment by benhaynes** [comment]
Thank you @TigerHix and @michaelnagy – that would be awesome! The first comment of this ticket gives an explanation of how to create the new language files. If you have any questions just let us know!

**Comment by Gfast2** [comment]
I could help to translate into Chinese @benhaynes . But where is file?

**Comment by TigerHix** [comment]
@Gfast2 在 build 分支的 app/locales/ 文件夹里。我这边也在进行中，要不一起翻译？https://github.com/TigerHix/directus/commit/8e86b6ae2ff6e8e2d1bda3e0de0c6e7a1b366715

**Comment by benhaynes** [comment]
Took the words right out of my mouth @TigerHix ;)

**Comment by benhaynes** [comment]
Thanks @Gfast2! I'll let you coordinate with @TigerHix to get the chinese translation wrapped up.

**Comment by TigerHix** [comment]
@benhaynes It seems to me that some strings are not yet configurable in the locale file?

**Comment by WellingGuzman** [comment]
@TigerHix if you spot some string that aren't for the enduser, let us know.

**Comment by katywings** [comment]
Just a little update from my part: i live and didnt forget about the german translation task xD

**Comment by benhaynes** [comment]
Haha, good to know @katywings ;)

@TigerHix Did you find some text in the framework that is not in the locale file?

**Comment by benhaynes** [comment]
@TigerHix and @Gfast2 – any update on the Chinese translation? Once we have a PR for it we'll merge it into `development`. We're planning on merging `development` into `master` in the next few days... so it'd be great to have that included.

Let me know, and thank you very much!

**Comment by TigerHix** [comment]
Yes - Gao Su and I have translated roughly 70% of the text. I will have some free time tomorrow, so hope I will finish them as fast as I could. :)

**Comment by TigerHix** [comment]
Oh, and by the way:


I cant seem to find the string literals of those option titles.

**Comment by TigerHix** [comment]
Oops, looks like Inbox didn't have my image sent.

![img_3179](https://cloud.githubusercontent.com/assets/3406505/17767243/c66e463a-6561-11e6-9e59-be5a0daaeb54.PNG)

**Comment by TigerHix** [comment]
And just a little opinion: would we consider specifying different fonts based on the locale? That's because in my Chrome browser on Windows 10, the font "fallback" to the default font 宋体 which is not really... as elegant as Directus's appearance in English.

**Comment by benhaynes** [comment]
Hey @TigerHix – 70% is great! Looking forward to seeing the final product. And yes, if there's a big difference in Font quality for Chinese we can look into adding conditionals for specific languages. It needs to be open-source, and ideally from the [Google Font library](https://fonts.google.com). Since I can't read Chinese I wouldn't be good at assessing the quality – would you have time to look through those fonts to see if any are styled significantly better?

@WellingGuzman – Can we get those last strings into the translation file in the next few days?

**Comment by Gfast2** [comment]
Yeh, I 've suddenly also so much thing to be done for my jobs.

I'll try my best.

**Comment by pmichaelis** [comment]
I could also help with the german translation. Is there an open repo with language files? @katywings : can I assist?

**Comment by katywings** [comment]
Hey @pmichaelis :D, that would be really cool! From my part the translation in the development branch is sadly my latest version. So you could go from there! @Benhaynes do you have a Discord or Slack group so we could arrange us a little better? (Without always posting into this issue and notify everyone :))
 
@pmichaelis: @RabbitMC is maybe also working on it!

But @RabbitMC how is it going on your side? :D

**Comment by benhaynes** [comment]
Thanks @pmichaelis – we really appreciate the help!

Hey All – @katywings had a good suggestion, adding you all to the Directus Slack channel might be easier for communicating. If you shoot me your email address I can send out invites: ben@rngr.org

See you in Slack!

**Comment by pmichaelis** [comment]
pmichaelis: pm@thedrama.de

Am 20.08.2016 15:34 schrieb Ben <notifications@github.com>:

Thanks @pmichaelis – we really appreciate the help!

Hey All – @katywings had a good suggestion, adding you all to the Directus Slack channel might be easier for communicating. If you shoot me your email address I can send out invites: ben@rngr.org

See you in Slack!

**Comment by benhaynes** [comment]
Thank you all so much for these amazing contributions! We're preparing to merge everything into `master`/`build` for the `6.3` release – so I'm shifting this ticket to `6.4` so it stays alive for new language additions.

☑️ 🇺🇸
☑️ 🇩🇪 
☑️ 🇨🇳 
☑️ 🇫🇷 
☑️ 🇪🇸

**Comment by perazzi** [comment]
I'd be happy to contribute translating to Brazilian portuguese.
I have a question though. Does directus also provide multi-language support for the content?

**Comment by benhaynes** [comment]
@perazzi – What Welling said is exactly right, Directus supports multilingual content that is stored relationally in the database – meaning you can have as many languages as you want for your project.

Also, very excited to add Brazilian Portuguese to the growing list! Thank you!!

**Comment by AeonZh** [comment]
Hello, I just want to let you know that the link to translation folder is broken, I believe the new one is under /api/locales.
And if you are interested I can work on an Italian translation.

**Comment by WellingGuzman** [comment]
Thanks for letting us know. @benhaynes I edited your message to update to paths.

@AeonZh That would be awesome 👍  Go ahead! we would love to see new translations :)

**Comment by benhaynes** [comment]
Thanks @WellingGuzman.

@AeonZh we would absolutely love to add Italian to our locales – thank you so much! If you have any questions just let us know – and I appreciate you alerting us to the outdated directory.
🇮🇹

**Comment by AeonZh** [comment]
Hello again, thank you for the opportunity. I'm working on it during the weekends so the process may be take some time.
I'd like to know if there is a guide to have an instance of the application like TigerHix did on let say Heroku, so I can test it (and to make sure everything makes sense). I went through the documentation but as I'm pretty new I couldn't really catch the requirements on the page.
Besides does the translation need to be as literal as possible? Because sometimes it can actually make sense but would sound somewhat clunky.
For example in: 
` Personalize this instance of Directus to fit your organization’s needs.`
We wouldn't use neither instance or installation (as I read for the German version), just something like "Personalize Directus ..." would sound fine to me. Just a personal opinion.

**Comment by RijkvanZanten** [comment]
Hi all! I started working on the Dutch translations 🇳🇱

**Comment by RijkvanZanten** [comment]
It's quite unusual to use formal language instead of personal language on the web in Dutch. We're quite used to imperative speak and being talked to directly. Would you still like me to use formal speak @benhaynes ?

**Comment by benhaynes** [comment]
@AeonZh – excellent. No need to be overly literal, whatever you think works best. 😊

@RijkvanZanten – that's amazing! Thank you so much! You can be more informal if you think that's appropriate.

**Comment by AeonZh** [comment]
@benhaynes about setting up a personal instance? Where can I find a guide about that?

**Comment by benhaynes** [comment]
@AeonZh – almost forgot about that one! You can use these docs to get up and running:

https://github.com/directus/docs/blob/master/01-getting-started/03-installation.md

If you create a hosted account I can give you a few free months, but you can't really preview your code there so that doesn't help.

**Comment by AeonZh** [comment]
Oh really? It doesn't matter then. Thanks again.

**Comment by lapa182** [comment]
Hey there, I can help with the BR/PT translation. Searched for the json file in the folder, but I didn't see anything.

**Comment by benhaynes** [comment]
That would be great @lapa182 – BR/PT would be a huge addition to the locales!

Thank you!

**Comment by WellingGuzman** [comment]
Hey @lapa182, you can find the json here https://github.com/directus/directus/blob/develop/api/locales/en.json (English)

**Comment by WellingGuzman** [comment]
I think I misinterpreted what you said @lapa182, it's all good! 👍

**Comment by rijkvanzanten** [comment]
Since this "issue" really isn't an issue, we've decided to move the credits of the people mentioned above to the [readme](https://github.com/directus/directus/blob/master/readme.md)

**Comment by kakuevn** [comment]
Hey is it okay if I do Russian translation? :)

Let me know! Cheers!

**Comment by benhaynes** [comment]
Hey @kakuevn – absolutely! We would be thrilled to have a Russian translation!

**Comment by alvsconcelos** [comment]
I can do the Brazilian Portuguese translation!

**Comment by WellingGuzman** [comment]
Great @alvsconcelos! any question let us know!

**Comment by benhaynes** [comment]
Let us know how it goes @alvsconcelos – we would really appreciate you helping us add Portuguese to our supported languages! :)

I'll keep this ticket open for visibility.

**Comment by honzabilek4** [comment]
Hi, I've started to work on Czech translation if this is helpful. I'm going to do it anyway, since we need it for a client.

**Comment by benhaynes** [comment]
Thank you @honzabilek4 ! That would be amazing! Each of these new languages opens up Directus to a whole new demographic of users, so we really appreciate it!

**Comment by anatoliayazilim** [comment]
Hello @honzabilek4 
I started to work for Turkish translation.
See you when I'm done working :)

**Comment by anatoliayazilim** [comment]
I will probably finish my work today and upload it. 
I can re-translate it when the new version is released. 
Yours :)

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/2)

**Comment by rijkvanzanten** [comment]
We handle translations through Crowdin now. See https://locales.directus.io

**Comment by H-Nguyenx** [comment]
> We handle translations through Crowdin now. See https://locales.directus.io

I've finished translating to Vietnamese. How can I apply it?
In Crowdin, it does not let me download the translation file.
Please help!

**Comment by HalwestRasul** [comment]
How can add the Kurdish language?
