### ISSUE TITLE
Automatically navigate to UI Options after creation

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1205]
Directly after creating a new field/column, Directus should navigate the user to the UI Settings to complete the setup. This may only be needed for certain UIs – so we could add a flag (`requires_option_setup`)... relational UIs definitely need this feature.

**Comment by WellingGuzman** [comment]
are we talking about `visible_columns`? :)

This is needed along with #1023 (Validating UI)

**Comment by benhaynes** [comment]
yeah! It would be easy to miss these settings... so we should navigate to them after field creation. Do you agree? We could make that a UI option if not all UI types will have required options.

**Comment by WellingGuzman** [comment]
I will review all the UI to see which one requires to be set before work.
