### ISSUE TITLE
I'm unable to delete image fields

### ISSUE THREAD

**Issue by roceroo** [directus/directus#12054]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Try creating a image field on directus, then try to delete it, it will drop this error message (allways)

```json
{
  "errors": [
    {
      "message": "alter table `products_and_solutions_categories` drop `featured_image` - ER_FK_COLUMN_CANNOT_DROP: Cannot drop column 'featured_image': needed in a foreign key constraint 'products_and_solutions_categories_featured_image_foreign'",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### To Reproduce

Try creating a image field on directus, then try to delete it, it will drop this error message (allways)

### Errors Shown

```json
{
  "errors": [
    {
      "message": "alter table `products_and_solutions_categories` drop `featured_image` - ER_FK_COLUMN_CANNOT_DROP: Cannot drop column 'featured_image': needed in a foreign key constraint 'products_and_solutions_categories_featured_image_foreign'",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16.13.2

### What database are you using?

sql

### What browser are you using?

chrome

### What operating system are you using?

Linux 4.14.252-195.483.amzn2.x86_64

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
What database vendor are you using @roceroo?

**Comment by martijn-dev** [comment]
I think this issue is related to #11510. The issue exist since 9.5.1 and is still there in the newest 9.6 version.
