### ISSUE TITLE
Cannot input tags

### ISSUE THREAD

**Issue by Pachat** [directus/directus#12069]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

After entering tags, as soon as we input another field, the tags are goen

### To Reproduce

![Tags](https://user-images.githubusercontent.com/13746133/157645268-913c0a0c-17ec-4a69-9c01-f311843168fe.gif)

### Errors Shown

The tags disappear

### What version of Directus are you using?

9.6.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

SQLite version 3.37.0

### What browser are you using?

Firefox

### What operating system are you using?

Windows_NT 10.0.19043

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
You should press "Enter" or "comma" keys to actually register each tag, as seen in this example:

![jCj18wS6yq](https://user-images.githubusercontent.com/42867097/157655103-194c13e2-e201-4f54-8e17-1aba762cd81d.gif)

This is by design as to allow inputting tags with spaces in it 👍

**Comment by Pachat** [comment]
Thank you for the demo and the explanation.
May be something to add to the Directus doc?

**Comment by benhaynes** [comment]
The Docs won't help here. We can adjust the _placeholder_ to say "Add a tag then press Enter..."
