### ISSUE TITLE
Cannot read properties of undefined (reading 'slice')

### ISSUE THREAD

**Issue by u12206050** [directus/directus#12061]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have no idea why this issue is popping up.

I am trying to attach a relationship (either new or existing) to an existing item.

Sometimes it works but for a very limited set of items which from what I can tell are not any different than other items when I try to attach the related item it just doesn't throw any error

So hoping someone else might know whats up.

### To Reproduce

Setup two collections with a o2m relationship between them.

Create an action on update of the "many" collection to find an item from the "one" collection and update the "many" item with that relationship.

### Errors Shown

```
Cannot read properties of undefined (reading 'slice')

TypeError: Cannot read properties of undefined (reading 'slice')
    at foreignKeyViolation (/workspace/node_modules/directus/dist/exceptions/database/dialects/mysql.js:132:37)
    at extractError (/workspace/node_modules/directus/dist/exceptions/database/dialects/mysql.js:31:20)
    at translateDatabaseError (/workspace/node_modules/directus/dist/exceptions/database/translate.js:47:53)
    at /workspace/node_modules/directus/dist/services/items.js:325:72
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### What version of Directus are you using?

9.6.0

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

chrome

### What operating system are you using?

osx

### How are you deploying Directus?

GCP

**Comment by rijkvanzanten** [comment]
This reminds me of https://github.com/directus/directus/issues/11374 🤔

**Comment by rijkvanzanten** [comment]
For the record: my PR prevents MySQL error extraction from throwing this exact error (where it tries to use `slice` on `undefined`. It doesn't solve the reason why the error is thrown in the first place. Happy to keep discussing that here @u12206050 👍🏻 


>  it has something to do with the fact that the id field itself is a uuid column, but the id values (due to historic data) could be a number-ish value ie. "751235".

This sounds very likely to me. It could be that MySQL threw an error that the wrong type was used in a foreign key constraint, and that Directus failed to properly extract that error due to it trying to use `slice` on a non-existing string 🤔

**Comment by u12206050** [comment]
The weird thing is this worked for a long time until version 9.5.2. So something must changed then?

**Comment by rijkvanzanten** [comment]
> The weird thing is this worked for a long time until version 9.5.2. So something must changed then?

Not sure!

**Comment by FloStar3000** [comment]
Hi, I got this error when I tried to update an entity and set a field to an empty string. If your field is nullable, you can set the field to `null`, otherwise check that no empty string can call the update endpoint.
