### ISSUE TITLE
incorrect date in api

### ISSUE THREAD

**Issue by terion-name** [directus/directus#12083]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a model with date field (db type `DATE`) and datepicker.

When I save the model with some date — it is stored in DB correctly, e.g. I choose 7th March, db record is saved with `2022-03-07`

But when I get the entry with API (or just go admin edit page) — I get a date one day earlier (e.g. 6th March)

### To Reproduce

Just save an event with some date

[schema.yml.zip](https://github.com/directus/directus/files/8226859/schema.yml.zip)

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

v16.14.0

### What database are you using?

mysql

### What browser are you using?

brave

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by koksikus** [comment]
Hi, you are duplicating issue # 7383. It is almost impossible to overlook (top of page issue).

**Comment by terion-name** [comment]
@benhaynes I've searched issues about date with search and didn't find, but simply didn't pay attention on pinned issues, sorry

**Comment by benhaynes** [comment]
No worries... an honest mistake, It'll be easier to search once we get the total issue count down below 50 (where it belongs). ❤️
