### ISSUE TITLE
Cannot delete last item in M2M relation

### ISSUE THREAD

**Issue by sensedrive** [directus/directus#12099]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The last item of a M2M relation seems not able to be deleted. If there is more than one item referenced, the M2M relation gets updated.

https://user-images.githubusercontent.com/8351587/157907779-770544f6-7eb8-4f78-b553-1aceb0737a49.mov

https://user-images.githubusercontent.com/8351587/157907832-66e36d41-ba9c-4fa4-a68a-6bbfefad6e4d.mov

### To Reproduce

Create a M2M relation. Try to delete the last item.

### Errors Shown

No errors are shown in console output. 

### What version of Directus are you using?

9.6.0

### What version of Node.js are you using?

16.13.1

### What database are you using?

mariadb

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by sensedrive** [comment]
@rijkvanzanten So you think it is an App issue?

I tired to debug and the API seems to get the correct payload (fieldName = images). So this might be related to API maybe. Just try to figure it out ...

<img width="719" alt="grafik" src="https://user-images.githubusercontent.com/8351587/157913395-c98a0156-f867-44b3-8826-cdbabed4aae5.png">

<img width="1040" alt="grafik" src="https://user-images.githubusercontent.com/8351587/157913180-13bfcb99-caff-439d-98c6-c574e6a87f2f.png">

**Comment by rijkvanzanten** [comment]
Not sure! Just recognized that we've seen some similar weird behavior in the same interface on the app side, so figured that'd be the best place to start debugging. Haven't confirmed it yet tho!

> I tired to debug and the API seems to get the correct payload (fieldName = images). So this might be related to API maybe. 

What was the payload that was submitted to the API? It should be `{ "bilder": [] }`

**Comment by sensedrive** [comment]
@rijkvanzanten

The payload was `{"body": "", "images": null }` ... and you are right, if the payload is `{"body": "", "images": [] }` it works. Just tried it manually via Postman.
 
 The "images" field is now empty (Line 15)! So the bug is an App issue.

I can try to figure out, which causes the issue, but I am not yet into Vue.
 
<img width="968" alt="grafik" src="https://user-images.githubusercontent.com/8351587/157930641-fe010a35-7310-47fb-8540-708038719e65.png">

**Comment by sensedrive** [comment]
@rijkvanzanten Everything I could figure out is, that it seems to be these lines. I do not know, what is the purpose of the code, which was written and what it causes, if it would be rewritten. Maybe @azrikahar can help and investigate, because here ends my knowledge.

Thanks anyway for the quick response. I appreciate a lot.

<img width="1680" alt="grafik" src="https://user-images.githubusercontent.com/8351587/157935873-b98ffb4a-0e0a-4680-b4a8-21569a0c108c.png">

**Comment by rijkvanzanten** [comment]
Thanks for helping debugging that! This seems to be a regression introduced in https://github.com/directus/directus/pull/11765. That PR aimed to fix the required state validation by passing `null`, however, `null` and `[]` aren't the same when saving a o2m/m2m field. To fix this, we'll have to revert #11765 and come up with a better solution 🙂  (cc @azrikahar)

**Comment by soch7188** [comment]
I'm experiencing the same issue in v9.6.0 with Postgres. 
I've tried deleting the Collection entry itself (that contains the m2m field), and had no issue in this case.
RIght now, I'm resorting to deleting the rows directly in the DB.

**Comment by sjones6** [comment]
> Thanks for helping debugging that! This seems to be a regression introduced in #11765. That PR aimed to fix the required state validation by passing `null`, however, `null` and `[]` aren't the same when saving a o2m/m2m field. To fix this, we'll have to revert #11765 and come up with a better solution 🙂 (cc @azrikahar)

@rijkvanzanten : raised a PR that modifies the behavior of the API to handle falsey values. Also possible to revert the #11765  and rewire the required field validation, but this seems less intrusive unless it has other problems.

Based on the current code, it looks like it partially was setup to handle falsey values but some stricter checks ended up skipping it in the `for` loop:

```ts
for (let i = 0; i < (payload[relation.meta!.one_field!] || []).length; i++) {
	const relatedRecord = (payload[relation.meta!.one_field!] || [])[i];
```

**Comment by rijkvanzanten** [comment]
Thanks @sjones6!

**Comment by rasco** [comment]
I have the same problem, and it also happens on M2A collections.
Directus 9.7.1, Postgres 13, node 16-alpine
