### ISSUE TITLE
Nothing there after installation

### ISSUE THREAD

**Issue by RabbitMC** [directus/directus#1212]
![screen shot 2016-07-17 at 13 01 50](https://cloud.githubusercontent.com/assets/1866374/16900254/e2c8493a-4c1f-11e6-8a50-b138ad897767.png)
![screen shot 2016-07-17 at 13 02 01](https://cloud.githubusercontent.com/assets/1866374/16900259/fe33e760-4c1f-11e6-8ff3-fa3a1039e10b.png)

![screen shot 2016-07-17 at 13 03 07](https://cloud.githubusercontent.com/assets/1866374/16900255/e2cba756-4c1f-11e6-93fd-aba264fc0178.png)

**Comment by RabbitMC** [comment]
![screen shot 2016-07-17 at 13 02 01](https://cloud.githubusercontent.com/assets/1866374/16900256/f458bd6a-4c1f-11e6-95c9-d92973b15e00.png)

**Comment by WellingGuzman** [comment]
Hello @RabbitMC,

Can you give us more information to replicate the issue? Server OS, Directus version/branch/commit, etc.

You can read our [issue report template](https://github.com/directus/directus/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by RabbitMC** [comment]
I found out, that its working, but on Safari (9.1.1) it not working. Firefox and Chrome for OS X (10.11) works fine.

Version Info:

Directus version: #cbbd2a8  
PHP version: 5.4.0
Web server: Apache 2
OS name and version: Ubuntu 14.04

**Comment by WellingGuzman** [comment]
Thanks @RabbitMC I'm going to work on this one.

**Comment by WellingGuzman** [comment]
@RabbitMC I pushed a fix that will solve this problem.

**Comment by RabbitMC** [comment]
@WellingGuzman tested! works! thanks! 👍
