### ISSUE TITLE
SDK items.readOne(id) behaves like items.readMany() when id is empty string

### ISSUE THREAD

**Issue by ctholho** [directus/directus#12128]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

If you call `directus.items('my_collection').readOne(id)` and `id` happens to be an empty string, the request will return an *array* of objects matching `directus.items('my_collection').readMany()`.

Either the typing of `readOne` is not correct or calling `readOne` with an empty string should fail.
```
interface IItems<T extends Item> {
    ...
    readOne(id: ID, query?: QueryOne<T>): Promise<OneItem<T>>;
    readMany(query?: QueryMany<T>): Promise<ManyItems<T>>;
```

If you ask me, I'd like `readOne` to always behave the same and not fall back to `readMany` behavior. But that's a breaking change and would require a guard in `readOne` which is a high cost just for the sake of consistency. If we were to rely on typescript we could extend `IItems` to have the appropriate return types for `readOne`.

At the very least, I propose to create a PR for the docs at https://docs.directus.io/reference/sdk/#read-single-item. This behavior should be documented somewhere. But I'm waiting for your judgment on how `readOne` should behave.

### To Reproduce

Use the directus sdk and call `directus.items('my_collection').readOne('')`. The http request will go to `<directus-location>/items/rh_members/` and return an array.

### What version of Directus are you using?

9.6.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

Postgres 14

### What browser are you using?

chrome

### What operating system are you using?

macos

### How are you deploying Directus?

docker

**Comment by azrikahar** [comment]
I believe this is due to the way the URL is constructed here:

https://github.com/directus/directus/blob/93122a0131d3e951c6346f8b8de519d1f34207ab/packages/sdk/src/base/items.ts#L16-L19

Since you are passing an empty string, it is indeed doing `/items/my_collection/` + `''`, which became the readMany endpoint `/items/my_collection` in the end. Thanks for bringing this to our intention! Just to answer your question, this is most definitely not an intended behaviour.
