### ISSUE TITLE
typo mistake in a language label

### ISSUE THREAD

**Issue by vahidreza** [directus/directus#12131]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Checking the list of languages [here](https://github.com/directus/directus/blob/main/app/src/lang/available-languages.yaml)
The dictation of Farsi is wrong here and is stated falsely as Farci.
the correct way to put it is as below:
fa-IR: Farsi (Iran)
Also anywhere alongside the app, Farci should be corrected to Farsi accordingly.

### To Reproduce

N/A

### Errors Shown

N/A

### What version of Directus are you using?

9.6.0

### What version of Node.js are you using?

container's node version is v16.13.1

### What database are you using?

MSSQL

### What browser are you using?

chrome Version 94.0.4606.81 (Official Build) (x86_64)

### What operating system are you using?

ubuntu

### How are you deploying Directus?

Docker

**Comment by vahidreza** [comment]
tnx Rjik,
BTW, I asked Ben and he told me to buzz you to be sure that the Persian language will be included in the next release on Thursday as we have already translated almost 57% of it. 
many tnx

**Comment by rijkvanzanten** [comment]
All translations done in locales.directus.io are auto-merged in this repo, so whatever changes have been made will be in the next release 🙂👍🏻

**Comment by vahidreza** [comment]
I thought so, tnx for the clarification.
