### ISSUE TITLE
Missing data from nested fields (v9.6.0)

### ISSUE THREAD

**Issue by arladmin** [directus/directus#12136]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When trying to get all the items (```limit=-1```) from a collection, with ```fields=*.*```, a lot of the records show ```null``` for the nested field (M2O) instead of the data.

I've also tried clearing the cache before making the API call.
### To Reproduce

1. GET all the data from a large collection (~30k records) via the ```/items/:collection``` endpoint
2. Set ```fields = *.* ```
3. Not all the retrieved records contain their nested data. Instead, they say ```null```

### What version of Directus are you using?

9.6.0

### What version of Node.js are you using?

14.x

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by flayks** [comment]
I believe that we have the same issue @arladmin #12134

**Comment by azrikahar** [comment]
Closing in favor of #12134
