### ISSUE TITLE
Drupal  Database

### ISSUE THREAD

**Issue by Rar9** [directus/directus#12143]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Directus is not able to migrate /open drupal datatables

### To Reproduce

Install fresh drupal and add directus.

### Errors Shown

Permission denied

### What version of Directus are you using?

9.6.0

### What version of Node.js are you using?

14.18.0

### What database are you using?

Mariadb 10.6x

### What browser are you using?

firefox

### What operating system are you using?

Linux 5.4.0-100-generic

### How are you deploying Directus?

local

**Comment by rijkvanzanten** [comment]
Directus isn't made to automagically migrate the data model from drupal/wordpress/joomla etc into something cleaner. Seeing that Drupal uses a pretty obfuscated data model, your luck may vary when applying Directus on top of that.

I'll close this for now, as it seems to be a usage error/misunderstanding, but happy to keep discussing down below 👍🏻 

What permission error are you getting?

**Comment by Rar9** [comment]
This should be clearly stated in documentation. That these Cms link their Tabelles in such a way that directus is currently unavailable to use them

And alternative means of migration should be suggested

**Comment by Rar9** [comment]
If directus would display the same as phpmyadmin then we should not be seeing permission denied for most tables

So there is an issue 
-- 
Mit freundlichen Grüßen /with best regards,

Robert Krölls
Am Sonnenhof 16
47800 Krefeld

Am 14. März 2022 20:20:17 MEZ schrieb Ben Haynes ***@***.***>:

**Comment by benhaynes** [comment]
You'll need to be more specific if you're looking for feedback or insight. Is this a permission issue within the App or API? Ar you authenticating? Have you set permissions at all?

As you can imagine, any security-first platform keeps permissions locked by default and allows users to control what gets exposed. So enabling permissions is an important step here... but it's impossible to know what's going on with the info provided.

**Comment by Rar9** [comment]
Is there a way to perhaps migrate the data from drupal jsonapi instead of database?

**Comment by rijkvanzanten** [comment]
> Is there a way to perhaps migrate the data from drupal jsonapi instead of database?

Directus doesn't have a built-in way to inject data coming from Drupal if that's what you're asking. That being said, it should be very doable to write a small handler that will loop over the drupal json api output, and insert it into Directus 👍🏻

**Comment by Rar9** [comment]
Keep me posted when this going into the right direction to do a migration.
