### ISSUE TITLE
GraphQL One to Many is Int type instead of subquery

### ISSUE THREAD

**Issue by wilkomanger** [directus/directus#12152]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hi, great work with Directus!

With a One to Many relationship, in the table where the foreign keys resides, I would expect to be able to query like:
```graphql
query {
    slugs(filter: { value: {_eq: "my-slug" }}) {
        person { id },
        article { id },
    }
}
```
However, I get this error:
```
Field "person" must not have a selection since type "Int" has no subfields.
```

The relationship is visible in Directus in the foreign key fields in `slugs`.

All I can think of is that this is a bug, not implemented yet, or that I should have a Many to One relationship in `slugs` as well. However when I did that last one the database ended in a erroneous state.

### To Reproduce

Have these 3 tables:
```
persons: id, name, birthday, slug
articles: id, title, content, slug
slugs: id, person, article
```
Where the `slug` fields in `persons` and `articles` are set as One to Many in Directus, to `slugs` `person` or `article` respectively.

### Errors Shown

```
Field "person" must not have a selection since type "Int" has no subfields.
```

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

Latest included in Directus docker image

### What database are you using?

Postgres 13

### What browser are you using?

Firefox

### What operating system are you using?

Linux

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
Does the user your using for this query have read access to `persons`?

**Comment by wilkomanger** [comment]
Ah it did have read access to `persons`, however it didn't have read access specifically to `persons.slug` which caused the issue! Letting the user have access to that field, it works as I would expect. Thanks!

**Comment by rijkvanzanten** [comment]
Perfect! Thanks for confirming that 🙂
