### ISSUE TITLE
Error: TypeError: undefined is not a constructor

### ISSUE THREAD

**Issue by RabbitMC** [directus/directus#1216]
## Version Info
  - Directus version: #6e9feb1
  - PHP version: 5.4.0
  - MySQL version: 
  - Web server: Apache 2
  - OS name and version: Ubuntu 14.04 

## Expected Behaviour
Getting image from Directus Files should work

## Actual Behaviour
If I choose
Upload, URL Import it works

If I choose 'Directus Files' as option for an Image of a entry the an error notification occurs

## Steps to Reproduce
 1. Make a table with text and a Single File Field
 2. Create a new Entry
 3. Click on Directus Files as a Single File Option

## Logs

Error: TypeError: undefined is not a constructor (evaluating 'new View(options)') File: https://...../app/core/ListViewManager.js?bust=6e9feb134bb6903f8d5ce26a9cc992841928ca72 Line:47
![screen shot 2016-07-22 at 10 27 24](https://cloud.githubusercontent.com/assets/1866374/17051112/1ae20df8-4ff7-11e6-836a-a57548d3d03a.png)

**Comment by WellingGuzman** [comment]
Hello @RabbitMC,

Thanks for reporting this, I couldn;t replicate this in any other major browser but on Safari, was it same to you?

The commit 6c7fd21 should have fixed this.
