### ISSUE TITLE
Can't select many to one field in system filter UI

### ISSUE THREAD

**Issue by LasseRosenow** [directus/directus#12161]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a recursive collection that has children of itself etc.

I have one special field that I only want to show, when the parent is null meaning on the root element. But its not working. I cannot select the parent field, because it only expands on click and shows its sub fields, but if I use a sub field and check for null of the sub field instead of the parent, it is not working either. Probably because it cannot check the sub field for null because the parent is null.

![image](https://user-images.githubusercontent.com/10547444/158285427-7c1348a4-b328-4fa0-aac8-11fb3b8df976.png)

I want to select the marked field, but its not possible.

### To Reproduce

Create a collection that has a o2m relation on itself and try to create a rule that hides some other field within the collection, if its parent is null.

### What version of Directus are you using?

9.6.0

### What version of Node.js are you using?

16

### What database are you using?

MariaDB

### What browser are you using?

Chrome, Firefox

### What operating system are you using?

Windows

### How are you deploying Directus?

On a remote Debian server

**Comment by abdonrd** [comment]
I think you should select the `Parent > ID`.

**Comment by LasseRosenow** [comment]
> I think you should select the `Parent > ID`.

Yes I tried that but it did not work.

**Comment by abdonrd** [comment]
I have this one working:

<img width="344" alt="Screenshot 2022-03-15 at 10 16 24" src="https://user-images.githubusercontent.com/1007051/158345418-7244a4b2-a2e4-4dab-b5fc-cb6fb6bb8a06.png">

**Comment by abdonrd** [comment]
Oh! Your are doing this in the `Interface` or in the `Conditions`?

In `Interfaces` it works for me, but in `Conditions` it doesn't.

**Comment by LasseRosenow** [comment]
But I can only use `Conditions`, because I want to hide certain fields that have nothing to do with the relation etc. meaning I have a `Checkboxes` field that I only want to show on the root element of my relational tree ;) I think that would only be possible with `Conditions` right?

**Comment by abdonrd** [comment]
Yeah, and it looks like a bug.

**Comment by rijkvanzanten** [comment]
> But its not working. I cannot select the parent field, because it only expands on click and shows its sub fields

This feels like the underlying issue to me. Could you do me a favor, and try to see if it works if you edit the Raw Value (through the field label dropdown menu), and set the rule set in JSON manually?

If I'm understanding the use case correctly, it should be

```json
{
  "parent": {
    "_null": true
  }
}
```

**Comment by rijkvanzanten** [comment]
> Yes this works

Thanks for confirming 👍🏻

**Comment by abdonrd** [comment]
With this:

<img width="319" alt="Screenshot 2022-03-15 at 15 46 14" src="https://user-images.githubusercontent.com/1007051/158404131-2bc6a625-d530-40d2-a8e7-cb52f4c3918f.png">

I have this in the raw value:

```json
{
  "_and": [
    {
      "parent": {
        "id": {
          "_null": true
        }
      }
    }
  ]
}
```

And it works if I change it to:

```json
{
  "parent": {
    "_null": true
  }
}
```

**Comment by rijkvanzanten** [comment]
It should also still work with the wrapped _and group:

```json
{
  "_and": [
    {
      "parent": {
        "_null": true
      }
    }
  }
]
```

The previous example (where you filter against `parent.id`) will validate that `parent` is an object with `{ id: null }`, which (correctly) doesn't trigger in this case.

**Comment by rijkvanzanten** [comment]
> Yeah, looks like a UI/UX bug, right?

Yeah! The "Parent" row in this case should be selectable as well, rather than just toggle its group open/closed.

**Comment by rijkvanzanten** [comment]
> Funnily enough, I remember that I fixed that issue already when I reworked the `useFieldTree` composable but someone must have set groups to be not selectable by mistake.

@Nitwel It only happens in system-filter, as it uses a v-select rather than a v-list with groups like we use in the display-template component 🙂 I created a new field-list component to standardize its use across the platform ([mandatory xkcd](https://xkcd.com/927/)) in https://github.com/directus/directus/pull/12157. Adding that field-list to the system-filter should resolve this issue as well 👍🏻

**Comment by Nitwel** [comment]
Oh I see, awesome!

**Comment by azrikahar** [comment]
Seems like this is the same as #12040, so closing this in favor of tracking it over there 👍
