### ISSUE TITLE
As Admin I can not see entries

### ISSUE THREAD

**Issue by RabbitMC** [directus/directus#1217]
## Version Info
  - Directus version: #6e9feb1 
  - PHP version: 5.4.0
  - Web server: Apache 2
  - OS name and version: Ubuntu 14.04 

## Expected Behaviour
As an Admin with all userrights and permissions I can see all available entries of a table. I can also manipulating them.

## Actual Behavior
As an Admin with all userrights and permissions I can **not** see all available entries of a table. I can **not** also manipulating them, because I can not click in a row.

## Steps to Reproduce
 1. Make two User, one is "super" admin, the other can just see a one table. 
 2. Save some entries in this table a the "other" user
 3. Login with the super admin and click on the table. The admin will see empty row. The "setting" icon on the top right corner also not work - it resets everytime.
![screen shot 2016-07-22 at 10 29 20](https://cloud.githubusercontent.com/assets/1866374/17051301/3933e67c-4ff8-11e6-84c9-5eb5fad30b72.png)
![screen shot 2016-07-22 at 10 29 42](https://cloud.githubusercontent.com/assets/1866374/17051302/3964d840-4ff8-11e6-8383-5ab2610dc006.png)

**Comment by WellingGuzman** [comment]
I've spent some time trying to replicate this issue with no luck, I follow the steps and I get the expected behavior and the icon on the top right corner also works.

Am I missing something? that's not part of the steps described above?

**Comment by RabbitMC** [comment]
I will do a clean install and try it again. Will give feedback after that. :)

**Comment by RabbitMC** [comment]
testet. Can not reproduce.

**Comment by WellingGuzman** [comment]
Thanks @RabbitMC, if you happened to bump into it, or something else let us know.
