### ISSUE TITLE
Replace empty DATETIME values with NULL on update

### ISSUE THREAD

**Issue by niseku** [directus/directus#1218]
## Version Info
  - Directus version: Commit: 6c7fd21815c5e24f798884af006eefcd95104c9e
  - PHP version: 7
  - MySQL version: 5.7
  - Web server: Apache
  - OS name and version: 

## Error
On updating a user the following message is shown:
```
This query failed: UPDATE `directus_users` SET `reset_expiration` = '', `id` = '1', `avatar_file_id` = NULL, `group` = '1' WHERE `id` = '1'
```

it's because `reset_expiration` is an empty string and not `NULL`.
Here is the MySql error message: 
```
#1292 - Incorrect datetime value: '' for column 'reset_expiration' at row 1
```

## Fix
Here is my Hotfix for that:
add the following lines in api/core/Db/TableGateway/RelationalTableGateway.php on line 75
```
        $dateTimeFields = [];
        foreach ($schemaArray as $field){
            if($field['type'] === 'DATETIME'){
                $dateTimeFields[] = $field['id'];
            }
        }

        foreach($dateTimeFields as $fieldName){
            if(array_key_exists($fieldName, $recordData) && empty($recordData[$fieldName])){
                $recordData[$fieldName] = NULL;
            }
        }
```

## Steps to Reproduce
 1. http://getdirectus.com/docs/developer/installation
 2. Login and try to update a User

**Comment by WellingGuzman** [comment]
Thanks @niseku, remember you can always send a Pull Requests with fixes like this.

I will take a look at this, thanks again for reporting this

**Comment by WellingGuzman** [comment]
I fix have been commited here https://github.com/directus/directus/commit/28fc43c321548175de7c56333dee80d3cdeda636 and it's available on the `development` branch.
