### ISSUE TITLE
The hidden Toggle in the Settings > Tables & Inputs seems not working

### ISSUE THREAD

**Issue by niseku** [directus/directus#1219]
## Version Info
  - Directus version: Commit: 6c7fd21815c5e24f798884af006eefcd95104c9e
  - PHP version: 7
  - MySQL version: 5.7
  - Web server: Apache
  - OS name and version: 

## Expected Behavior
Show/Hide a Table in the left Nav after toggling the hidden Toggle in Settings > Tables & Inputs for a Table.

## Actual Behavior
On toggling the hidden Toggle nothing happens (the `nav_listed` field in the `directus_privileges` remains always on `0`)

## Steps to Reproduce
 1. go to Settings > Tables & Inputs
 2. Toggling the hidden Toggle for a table

**Comment by WellingGuzman** [comment]
Hi @niseku, `nav_listed` is not used by the web app right now.

I fixed the toggling issue, it's only on `development` branch.
