### ISSUE TITLE
Hidden inputs are shown when the viewport width is smaller than 800px

### ISSUE THREAD

**Issue by niseku** [directus/directus#1220]
## Version Info
  - Directus version: Commit: 6c7fd21815c5e24f798884af006eefcd95104c9e
  - PHP version: 7
  - MySQL version: 5.7
  - Web server: Apache
  - OS name and version: 

## Actual Behavior
Hidden Inputs are shown when the viewport width is smaller than 800px in the settings for a user

## Steps to Reproduce
 1. go to Users 
 2. Click on New User
 3. Resize the window tho a viewport smaller than 800px

## Logs or Screenshots
![screenshot at juli 23 21-37-14](https://cloud.githubusercontent.com/assets/16119608/17079881/d3c82a6a-511d-11e6-93e1-d1f708a596ef.png)

**Comment by WellingGuzman** [comment]
@niseku Thanks for reporting this, this should fix the problem.  https://github.com/directus/directus/commit/5902327389cf094d00cba2df280347772a10fb99
