### ISSUE TITLE
Authorization service is not exported in services index.ts

### ISSUE THREAD

**Issue by aerdnach** [directus/directus#12207]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I'm not sure if this can be considered a bug, if there is a more appropriate place for this kind of report let me know and I'll move it.

I noticed that in /api/src/services/index.ts  the authorization service (/api/src/services/authorization.ts) is not exported. Is this intentional? I have tried to add it because I need it in my extension and it works correctly. The use case is this one: define a custom endpoint that expose validatePayload method from AuthorizationService class.

### To Reproduce

.

### Errors Shown

.

### What version of Directus are you using?

9.6.0

### What version of Node.js are you using?

16

### What database are you using?

postgres

### What browser are you using?

chrome

### What operating system are you using?

linux

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
> I noticed that in /api/src/services/index.ts the authorization service (/api/src/services/authorization.ts) is not exported. Is this intentional?

Nope! Fixed in #12208 👍🏻
