### ISSUE TITLE
Issues with a Wysiwyg links

### ISSUE THREAD

**Issue by iksent** [directus/directus#12215]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have some issues with links inside Wysiwyg editors which make the experience of using the CMS for the editor to a pain.

## Issue №1

1) Place cursor on a link and click on CTRL/CMD + K

<img src="https://user-images.githubusercontent.com/32956521/158825438-cdfcf3e6-1dbd-4958-bb58-7eb95df89baa.jpg" width="600"/>

2) Click on "Add/Insert Link" button:

<img src="https://user-images.githubusercontent.com/32956521/158825715-a0f6646c-cf3f-4edc-bba3-6815a67eb7f2.jpg" width="600"/>

3) Why these modals aren't the same?

## Issue №2

1) Change link target (for example: _self => _target) with a CTRL/CMD + K
2) Field and item won't be marked as "changed"

https://user-images.githubusercontent.com/32956521/158826604-b39b282c-5ec4-4b18-b2a9-fc1007f7f9f5.mov

3) BUT it works OK with a button:

https://user-images.githubusercontent.com/32956521/158826637-fe545ceb-d6ee-4b33-97d3-8124b00d88dd.mov

## Issue №3

1) Change code to:

```
<p><a href="https://example.com"><span style="color: red;">Test Link</span></a></p>
```

2) You won't be able to edit this link via a button

3) BUT you will be able to edit it via the CTRL/CMD + K

https://user-images.githubusercontent.com/32956521/158826196-74892de6-e66a-42bd-8d4f-0b6cc60c0499.mov

### To Reproduce

All inside description.

### What version of Directus are you using?

9.6.0

### What version of Node.js are you using?

v14.18.1

### What database are you using?

MariaDB

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
> Why these modals aren't the same?

Because we don't rely on tinymce's default modals for the operations. The cmd+k shortcut seems to circumvent that restriction, so that's something we'll have to resolve 👍🏻
