### ISSUE TITLE
Can't upload a file via the `Single File` field

### ISSUE THREAD

**Issue by niseku** [directus/directus#1222]
## Version Info
  - Directus version: 6c7fd21815c5e24f798884af006eefcd95104c9e
  - PHP version: 7
  - MySQL version: 5.7
  - Web server: Apache

## Expected Behavior
Uploading a File via a `Single File` field and save the item

## Actual Behavior
Can't save the item. MySQL throws the following error:
````
#1364 - Field 'user' doesn't have a default value
````
## Steps to Reproduce
 1. create a table and a field of type `Single File` in it
 2. navigate to the table and create a new item
 3. click on upload for the `Single File` field and upload a File
 4. save item ==> error message

## Logs or Screenshots
![screenshot at juli 25 21-47-20](https://cloud.githubusercontent.com/assets/16119608/17114937/65cfc91a-52b1-11e6-98ee-3de7cfa79711.png)

**Comment by WellingGuzman** [comment]
Hi @niseku thanks for reporting this. The issue should've be fixed by 95f0f24
