### ISSUE TITLE
Since 9.7.0: Blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by LasseRosenow** [directus/directus#12237]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Since directus 9.7.0 I get this issue, when trying to fetch from the graphql api:

```

urspruenglich-unverpackt.de/:1 Access to fetch at 'https://admin.urspruenglich-unverpackt.de/graphql' from origin 'https://urspruenglich-unverpackt.de' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

```

### To Reproduce

Update to 9.7.0 and try to do graphql api requests.

### Errors Shown

```

urspruenglich-unverpackt.de/:1 Access to fetch at 'https://admin.urspruenglich-unverpackt.de/graphql' from origin 'https://urspruenglich-unverpackt.de' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

```

### What version of Directus are you using?

9.7.0

### What version of Node.js are you using?

16

### What database are you using?

MariaDB

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

On a remote Debian server

**Comment by abdonrd** [comment]
Check this PR: https://github.com/directus/directus/pull/12022

**Comment by LasseRosenow** [comment]
A thank you very much, would be good to have this in the changelog

**Comment by benhaynes** [comment]
> A thank you very much, would be good to have this in the changelog as it is somewhat breaking

Yes, I agree... I have added this warning to the release notes!
https://github.com/directus/directus/releases/tag/v9.7.0
