### ISSUE TITLE
Title, location, caption are not saved upon file creation

### ISSUE THREAD

**Issue by TigerHix** [directus/directus#1224]
## Version Info
  - Directus version: commit #2b20044
  - PHP version: 5.6.4
  - MySQL version: 5.6.25
  - Web server: Apache 2.4.10
  - OS name and version: Ubuntu 15.04

## Expected Behavior
After uploading the file and filling in title, caption, etc. the file should be saved upon clicking "save item".

## Actual Behavior
Title, location, caption are not saved. Whatever has been filled in, they get cleared when saving the file for the first time. Though, subsequent editing & saving will work normally.

**Comment by benhaynes** [comment]
Thanks @TigerHix – we'll look into this today. Appreciate the bug reporting!
