### ISSUE TITLE
Standard Cloud Account is not allowed to send email

### ISSUE THREAD

**Issue by Thierry0** [directus/directus#12246]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I created a standard cloud recently but I can't invite users within my project. This was working in the community cloud but once I started using the standard cloud, it is not working.
![image](https://user-images.githubusercontent.com/25372642/159132196-899b5b5b-7cd5-4cf2-a7a6-e7c1aa6f126b.png)

### To Reproduce

Create a standard account and try inviting users

### Errors Shown

![image](https://user-images.githubusercontent.com/25372642/159132220-e142b9c5-ecd0-4cc1-85fb-5ad5af32f5c8.png)

### What version of Directus are you using?

9.6.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

Default cloud database

### What browser are you using?

Chrome

### What operating system are you using?

Linux 4.14.262-200.489.amzn2.x86_64

### How are you deploying Directus?

Directus Standard Cloud

**Comment by benhaynes** [comment]
Thank you for reporting this, we're looking into it now.

**Comment by joselcvarela** [comment]
Thanks for reporting this @Thierry0.
We believe this should be fixed now. For further support you can talk to us via chat on https://directus.io 👍
