### ISSUE TITLE
Mass edit doesn't work with grouped fields

### ISSUE THREAD

**Issue by jorauch** [directus/directus#12258]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

It isn't possible to mass edit grouped fields.

### To Reproduce

1) create a new collection
2) create a new toggle field in this collection
3) create a group field in this collection
4) put the new toggle field in the group
5) create two new items in the collection
6) select multiple items
7) multi edit this items e.g to "false"
=> the items wasn't changed with no error

(same procedure works perfect if the field isn´t i a group)

### Errors Shown

no error

### What version of Directus are you using?

9.7.0

### What version of Node.js are you using?

14.19.1

### What database are you using?

mySQL 8.0.24

### What browser are you using?

chrome 99.0.x

### What operating system are you using?

macOS

### How are you deploying Directus?

plesk

**Comment by HitomiTenshi** [comment]
Might be related to some change that also caused #12257
