### ISSUE TITLE
Language table foreign key name does not correspond with language table name

### ISSUE THREAD

**Issue by wilkomanger** [directus/directus#12255]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When adding a Translations field to e.g. table `test`, the language foreign key will always be called `languages_id`, regardless of the actual language table name.

[See also some info here](https://github.com/directus/directus/discussions/3069#discussioncomment-2358144)

### To Reproduce

1. Create table `test`
2. Add Translations field, name the language table `i18n` (it will be created correctly)
4. Notice how in `test_translations`, the foreign key is named `languages_id`, as opposed to the expected `i18n_id`

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

Latest included in Directus docker image

### What database are you using?

Postgres 13

### What browser are you using?

Firefox

### What operating system are you using?

Linux

### How are you deploying Directus?

Docker

**Comment by HitomiTenshi** [comment]
@wilkomanger Directus 9.5.2 and 9.6.0 have some major issues with translation fields, especially when using WYSIWYG fields with the same name on both the main table and translation table.

Does the issue still occur for you when using the latest directus `9.7.0`? My issues went away with that version.

**Comment by rijkvanzanten** [comment]
> @wilkomanger Directus 9.5.2 and 9.6.0 have some major issues with translation fields, especially when using WYSIWYG fields with the same name on both the main table and translation table.
> 
> Does the issue still occur for you when using the latest directus `9.7.0`? My issues went away with that version.

This is unrelated to those issues/fixes 👍🏻 

This is the field configuration flow not defaulting to the correct name in the auto-fill values of the relationship configuration
