### ISSUE TITLE
Couldn't select a grouped field as "Display Template"-Item

### ISSUE THREAD

**Issue by jorauch** [directus/directus#12261]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

It is not possible to add a grouped field as Display-Template with the "+"-Button

### To Reproduce

1. Create a new collection with grouped fields 
![image](https://user-images.githubusercontent.com/6722255/159186182-78c052c1-7c0f-495d-b649-d87a3cb99035.png)

2. Select a grouped field
![CleanShot 2022-03-20 at 22 05 21](https://user-images.githubusercontent.com/6722255/159186454-51d71e05-a838-4b32-8824-7d6e2cdc217b.png)

=> selected field  doesn't add to the template
(it is possible to edit the raw value like {{field-name}} and it works, but the UI of input doesn´t show the grouped field)

### Errors Shown

none

### What version of Directus are you using?

9.7.0

### What version of Node.js are you using?

14.19.1

### What database are you using?

MySql 8.0.24

### What browser are you using?

Chrome 99

### What operating system are you using?

macOS

### How are you deploying Directus?

plesk

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/directus/pull/12260
