### ISSUE TITLE
Why am I getting a Token Expired error?

### ISSUE THREAD

**Issue by dataexcess** [directus/directus#12275]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I am using the following versions of Directus:

client: "@directus/sdk": "^9.5.1",
server: "directus": "^9.6.0"

I have a website that check the JS SDK's /me method on the first page-load. If it returns "invalid user credentials" I don't log in, but I create a public "anonymous" user. There is also a sign-up/login button on my website. When clicked it will go through the login flow UI, and call /users/invite etc. and eventually create a user. When the user logs in with his credentials, the login works. BUT after the expiration time of the access_token, (when closing and reopening the website). The /me method returns a "token expired" error, and consequetly all the public methods of the SDK are not working anymore (as it is trying to refresh the expired token, or something?).

my access_token_TTL is 2 mins and refresh_token_TTL is 7 days in my .env config.

### To Reproduce

- login with JS SDK auth login method. 
- reload page
- /me method called in beginning correctly returns the logged in user object.
- wait till access_token_TTL has expired.
- reload page
- /me method greeted with a 'Token expired' error

expectation: 
- after access_token_TTL reached the refresh_token should refresh the access_token behind the scenes and the /me method should return the logged in user (after refreshing the token behind the scenes)
- when not logging in for a time-period longer than the refresh_token_TTL, the /me method should return a simple "invalid user credentials" and an anonymous user would be created (my personal implementation).

### Errors Shown

a4618ee.js:2 GET https://subneu.live/api/users/me 403 (Forbidden)
bc75317.js:1 Error: Token expired.

### What version of Directus are you using?

client: "@directus/sdk": "^9.5.1", server: "directus": "^9.6.0"

### What version of Node.js are you using?

v15.5.1

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying Directus?

nginx on ubuntu

**Comment by rijkvanzanten** [comment]
I believe the SDK might auto refresh based on the expiration time of the token while using it, but is having some issues when you instantiate the sdk with an already expired token 🤔 We'll have to do some research to confirm that though

**Comment by rijkvanzanten** [comment]
> Ok, this is my website [www.subneu.live](http://www.subneu.live). if it might help..
> I tried to update the client to 9.6.0. but then I had another blocking bug so I could not do that. (will make an issue soon)
> Do you think it's related to the discrepancy between server client versions?

Technically speaking, we do recommend keeping both in sync to make sure they align. In this particular issue, I don't think there have been any changes between 9.5 and 9.6 on the SDK side of things, so it should be OK 👍🏻

**Comment by dataexcess** [comment]
OK! good to know.

**Comment by krazyjakee** [comment]
Also see: https://github.com/directus/directus/issues/10456

**Comment by dataexcess** [comment]
> Also see: #10456

Happy to see I'm not the only one - I was losing my mind over this issue. Added some info on that ticket! 👍

**Comment by dataexcess** [comment]
> 

I believe the issue in this ticket might be solved now, but the other issue I have (as said in the quoted reply) is blocking my website now :)
here's the issue: https://github.com/directus/directus/issues/12536

**Comment by dataexcess** [comment]
> I tried to update the client to 9.6.0. but then I had another blocking bug so I could not do that. (will make an issue soon)

I believe the issue in this ticket might be solved now, but the other issue I have (as said in the quoted reply) is blocking my website now :)
here's the issue: https://github.com/directus/directus/issues/12536

**Comment by krazyjakee** [comment]
@dataexcess it's unrelated to this issue.
If you'd like to call more attention to this issue, your best bet is to find more information to add to your ticket or even fork this repo and dig in on a solution yourself.

**Comment by dataexcess** [comment]
Ok.

**Comment by dataexcess** [comment]
I also fixed the issue. All good! thank you 🙏

**Comment by dataexcess** [comment]
I can confirm this issue is Fixed.
