### ISSUE TITLE
OTM add child before parent is saved

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1227]
I have a parent table(hotels) and a child table(hotel_offers). The parent has an OTM field.
The hotel_id column of the hotel_offers table is mandatory.

Now I create a new parent record but I do not save it yet (so the parent does not have an ID yet).
I then click on the "Add Child" button of the OTM field to add a child record. When clicking the chid form's save button to get back to the (not yet saved) parent I get an error message in a red box:

![bildschirmfoto 2016-08-03 um 04 39 49](https://cloud.githubusercontent.com/assets/26493/17352160/a4d6131a-5934-11e6-9c9c-e79d08e086d4.png)

**Comment by benhaynes** [comment]
Ahh yes, _the cart before the horse_...

I remember we were trying to figure this one out a year or two ago. Not sure how complicated it is, but the related item (`hotel_offer`) should not actually save until the parent is saved... and we would need a way to get the parent ID first... so we can save it into the related item.

@WellingGuzman does that make sense? Do you know why the related item is being saved in the DB before the parent is saved?

**Comment by laszlokorte** [comment]
> Do you know why the related item is being saved in the DB before the parent is saved?

For me it sounds like a client side validation error of the invisible MTO field of the Hotel.

**Comment by benhaynes** [comment]
Ahh, not actually trying to save it, but the FK is validating false? That also makes sense.

Anyon have ideas on how we can resolve this?

**Comment by benhaynes** [comment]
This is working perfectly now – thanks @WellingGuzman
