### ISSUE TITLE
checkbox required asterisk (*)

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1228]
I created a checkbox/TINYINT column and set it to NOT NULL in the database. The column should be 0 if the checkbox is not checked and 1 if it's checked. That is working.

But the NOT NULL constraint get's interpreted as the column being "required" and the checkbox field in the form get's marked with an asterisk (*). That's confusing because checking the checkbox is not actually required.

**Comment by WellingGuzman** [comment]
Commit https://github.com/directus/directus/commit/fd64d1a08b4b45e1f9a53aa31f9dc8f84c54884a didn't work as expected so it was undone by this commit: https://github.com/directus/directus/commit/610790ba9051baa864e4e48c794ee578049596fe

**Comment by benhaynes** [comment]
Basically we need to decide:

Can a checkbox ever be required (must be clicked)? The answer is, only if the field was marked as "required" within Directus. Not because it has "not null".

**Comment by WellingGuzman** [comment]
I did it through the long way, and make the UI decide it. so checkbox are only required if `mandatory` option is set to true.

**Comment by benhaynes** [comment]
Nice, so the only way to make it required is to set the field to "required" within Directus...

I like it. Are you still testing this one or should we close?

**Comment by WellingGuzman** [comment]
I'm testing this out, I've not find any issue so far.

We can close it, and if something rises we can re-open it. @benhaynes what do you think?

**Comment by benhaynes** [comment]
Sounds good... if you see a problem just re-open.

**Comment by laszlokorte** [comment]
If have not tested it yet but did you consider that if NOT NULL is set in the DB the "required" checkbox is checked and disabled? In that case the checkbox should be mandatory right?

**Comment by benhaynes** [comment]
Yes, but I don't think that's how it should be. Do you?

How it _should_ work (open to suggestions) – @WellingGuzman is this what we're doing now?

**EITHER WAY (NULL OR NOT NULL)**: The UI should save with `0` or `1` and is not required (by default) unless the Directus Settings > Required is turned on.

--

As a **new feature**, if ALLOW NULL is on, then we should have a UI Option that says:
* False = NULL
* False = 0

**Comment by WellingGuzman** [comment]
@benhaynes right, checkbox UI should save 0 or 1 and it's not required unless you set the mandatory option on.

> As a new feature, if ALLOW NULL is on, then we should have a UI Option that says:

This sounds good, @laszlokorte what do you think?
