### ISSUE TITLE
Selecting field within group for Related Values display not working

### ISSUE THREAD

**Issue by u12206050** [directus/directus#12283]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

After upgrading to 9.7.0 there were several bugs with fields within groups.

One such bug is not being able to select a field for the display in a relationship.

![Display_Field_in_group](https://user-images.githubusercontent.com/6641242/159338931-467556a9-7a80-43bb-baec-3d9c703c9f4e.gif)

### To Reproduce

Two collections with M2O relationship.

Add fields from the One collection to a group.

In the Many collection update the display field of the relationship to a field within the group.

### Errors Shown

It doesn't show anything within the field-input

### What version of Directus are you using?

9.7.0

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

chrome

### What operating system are you using?

osx

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/directus/pull/12284
