### ISSUE TITLE
Inconsistent "Visible Status IDs"

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1229]
The MTO Field has the "Visible Status IDs" option for filtering the visible records but the MTO Typeahead has a checkbox called "Include Inactive".

I guess the goal of both settings is the same but it's confusing that they work differently.

**Comment by WellingGuzman** [comment]
Hi @laszlokorte,

Thanks for reporting this, but we've already fixed this in the development branch. https://github.com/directus/directus/commit/c9e6fe5edb09850dc9db30b1ee9d1f8d44ddfbe9
