### ISSUE TITLE
CORS configuration

### ISSUE THREAD

**Issue by justrealmilk** [directus/directus#12291]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Can't locate where in the app to configure CORS

### To Reproduce

Attempt to configure CORS

### What version of Directus are you using?

9.7

**Comment by rijkvanzanten** [comment]
It's a set of env vars, see https://docs.directus.io/configuration/config-options/#cors
