### ISSUE TITLE
Update User does not work in GraphQL

### ISSUE THREAD

**Issue by Cammoy** [directus/directus#12295]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

If I want to update a particular user in GraphQL and change the role, it does not work. 
The Rest API works. Additionally in order to update a users role through GraphQL it requires more than just the ID!

### To Reproduce

`mutation {
	update_users_item(id: "72a1ce24-4748-47de-a05f-ce9af3033727", data: { role: "fc68cf04-3aba-4b4b-82b3-44000b4cede0" }) {
		first_name
		last_name
	}
}`

### Errors Shown

`{
  "errors": [
    {
      "message": "select \"admin_access\" from \"directus_roles\" where \"id\" = $1 limit $2 - invalid input syntax for type uuid: \"{\"id\":\"fc68cf04-3aba-4b4b-82b3-44000b4cede0\",\"name\":\"The Professional\",\"icon\":\"supervised_user_circle\",\"enforce_tfa\":false,\"admin_access\":false,\"app_access\":false}\"",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "update_users_item"
      ]
    }
  ],
  "data": {
    "update_users_item": null
  }
}`

### What version of Directus are you using?

Latest Version - Directus Cloud

### What version of Node.js are you using?

Whatever is in cloud

### What database are you using?

Directus Cloud Service

### What browser are you using?

Chrome / Webkit

### What operating system are you using?

macOS

### How are you deploying Directus?

Directus Cloud

**Comment by azrikahar** [comment]
Just to confirm, is the error shown exactly based on the reproduction step you have shared, or a previous request? I assume it's the latter? I am facing an error on my end, but it seems different:

![image](https://user-images.githubusercontent.com/42867097/159478910-7c7b1c43-f9a3-4366-9615-0a46d603960a.png)

**Comment by Cammoy** [comment]
@azrikahar its a previous request.
I experienced the same thing you showed as well. 
The documentation shows that you can just update the role alone but that's not correct as you get the error you have.
You actually have to update the role itself and that like this and that does not work either

`mutation {
update_users_item(
id,
data: {
 role: {
          id: "34f7042b-80c3-5e8a-bda2-cec5be73c1ec"
          name: "User"
          app_access: true
          enforce_tfa: false
          admin_access: false
          icon: "supervised_user_circle"
        }
})
}`

You need to

**Comment by rijkvanzanten** [comment]
The following is a valid request:

```graphql
mutation {
  update_users_item(
    id: "2ebbc642-8008-4a19-8fae-438e9125ef05", 
    data: { role: { id: "2b313657-90da-4e55-afd1-572455a425ab" }}
  ) {
    id
    role {
      id
    }
  }
}
```

that causes the error mentioned in the OP
