### ISSUE TITLE
Batch update of fields in raw group (alias) not working

### ISSUE THREAD

**Issue by u12206050** [directus/directus#12307]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Trying to update fields that are within a raw group doesn't work.

![Raw_group_update_issue](https://user-images.githubusercontent.com/6641242/159565727-b59fbf1f-a729-454c-8ca3-e9f0ef32cfa4.gif)

### To Reproduce

Create fields and group them in a raw group.

### Errors Shown

No error, but can't enter new values.

### What version of Directus are you using?

9.7.0

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

edge

### What operating system are you using?

osx

### How are you deploying Directus?

Locally & GCP

**Comment by jorauch** [comment]
Duplicate #12258
