### ISSUE TITLE
Editing an item field replaces the item with an empty one

### ISSUE THREAD

**Issue by nathan-hubelia** [directus/directus#12301]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

After updating to 9.7, editing an item field and saving it replaces the saved item with a new one which is completely empty. The new item only contains the updated field. This wasn't the case in 9.6. 

https://user-images.githubusercontent.com/98350390/160612340-3212b367-977b-4c81-a876-c7b485360f1c.mov

### To Reproduce
[snapshot.yaml.zip](https://github.com/directus/directus/files/8372999/snapshot.yaml.zip)

OR

1. Create a new collection named "container" that has an input field "name" and another input field "css_classes" which is wrapped into a detail group named "style".
2. Create a new collection named "section container" that has an input field "name" and builder (M2A) field named "components" related to the container collection.
3. Create a new section container and add a container inside its components field. Please also fill the name field for both and the style field of the component. Save everything.
4. Go back to the container nested inside the section container and try to edit the style field. After editing it and saving everything, the bug should occur.

### Errors Shown

Nothing is showed.

### What version of Directus are you using?

9.7

### What version of Node.js are you using?

16.14.2

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

PaaS

**Comment by rijkvanzanten** [comment]
Plain items seem to save just fine on a fresh installation on my end. Could you share a database dump or schema snapshot where this is happening? We'll reopen and keep investigating if there's an issue 👍🏻

**Comment by RegisHubelia** [comment]
Hi, there is something up with O2M relationships - we ended up restoring the backup and rolled back to 9.6 and it's all good now.  We'll investigate further and let you know our findings.

**Comment by RegisHubelia** [comment]
Hey @rijkvanzanten, to keep you posted, I narrowed down the issue and it points to the commit #12216  v-form component.

line 31 @apply (witch is called everytime you type something in a field - and it's quite heavy if you have big objects with multiple relations) calls the function @ Line 317: 

           `function apply(updates: { [field: string]: any }) {
			const updatableKeys = Object.keys(updates).filter((key) => {
				debugger;
				const field = props.fields?.find((field) => field.field === key);
				if (!field) return false;
				return !isDisabled(field);
			});
			emit('update:modelValue', pick(assign({}, props.modelValue, updates), **updatableKeys**));
		}`

Changing the emit to use the previous value like so:
`emit('update:modelValue', pick(assign({}, props.modelValue, updates), **Object.keys(updates)**));`

Fixes our issue.  It then successfully updates the "child" document as expected.

I'll investigate a bit further as it is unclear why it's doing this - but I suspect something in the function isDisabled might be causing the issue with our data structire.  Just wanted to let you know - and maybe you will see something that I haven't yet.

**Comment by rijkvanzanten** [comment]
@d1rOn @licitdev thoughts on the above?

**Comment by RegisHubelia** [comment]
The difference I get when I check both values (updatableKeys and Object.keys(updates)) is that the field 'id' (primary key) exists in the 'updates' array - and it doesn't after the filter function.  Most likely the primary key field needs to be left alone - as by changing the function for:
`			const updatableKeys = Object.keys(updates).filter((key) => {
				const field = props.fields?.find((field) => field.field === key);
				if (!field) return false;
				return field.schema?.is_primary_key || !isDisabled(field);
			});`
does the trick.  Not sure if it's ideal - but it seems to work fine.

**Comment by RegisHubelia** [comment]
@rijkvanzanten, Shall we re-open this issue following the troubleshooting steps above?

Thanks

**Comment by licitdev** [comment]
@RegisHubelia I was unable to reproduce your issue, I believe you are using field groups.

Please kindly assist provide a minimal reproduction steps / schema snapshot on a fresh instance. A screen recording showing the issue or screenshots of your data structure would also be very helpful. Thank you.

**Comment by nathan-hubelia** [comment]
@licitdev I just updated the post with more details.

**Comment by licitdev** [comment]
@nathan-hubelia Thank you for the updated details, I'm able to replicate the issue. The issue was due to the primary key not propagated upstream, which led to the creation of a new relational item. Tested your fix and it worked well. 
Please assist to create a PR, thank you!

**Comment by RegisHubelia** [comment]
PR #12480
