### ISSUE TITLE
MTO typeahead footer

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1230]
development branch (e05c46c93)

The MTO Typehead UI has a "Footer" checkbox in the settings.

1. why? I do not think it makes sense?
2. the footer is displayed even if the checkbox is not checked and shows "NaN" values

**Comment by laszlokorte** [comment]
Well I just noticed that the footer option is added to all UIs. The NaN value seems to be because the `visible column` I have set for the typeahead is not numeric. It would be cool if that case could be caught but I guess it's not that dramatic.

Still there is the the wrong behavior of the footer being displayed regardless if the "footer" checkbox is checked or not.
The reason is this check:
https://github.com/directus/directus/blob/development/app/core/table/table.footerview.js#L64

There `showFooter` is a string `'0'` and not `0`.

If I remember correctly such number<->string mismatch and the truthyness semantics of javascript values have been the reason of many of the issues I have reported until now.

May I suggest two ideas:
1. introduce a type conversion layer that converts all stringy values received from the API into their correct types on a central place. How about adding a `type` property to the `UIComponent`'s `variables` object:
```
this.variables.push({
        id: 'footer',
        type: 'boolean' // <---
        ui: 'checkbox',
        def: 0,
        comment: __t('numeric_footer_comment')
      });
```
and then access the UI options values only through some interface that takes care of the type casting.

2. Do not rely on implicit truthyness of javascript but use strict equals `===` everywhere and check and make boolean conditions explicit `if(showFooter === true)` instead of just `if(showFooter)`

**Comment by WellingGuzman** [comment]
> why? I do not think it makes sense?
Hey @laszlokorte, It's a bug. I'm working on it.

**Comment by WellingGuzman** [comment]
> 1. introduce a type conversion layer that converts all stringy values received from the API into their correct types in a central place. How about adding a type property to the UIComponent's variables object:

@laszlokorte care to open a PR for that?

**Comment by laszlokorte** [comment]
> Still there is the the wrong behavior of the footer being displayed regardless if the "footer" checkbox is checked or not.
The reason is this check:
https://github.com/directus/directus/blob/development/app/core/table/table.footerview.js#L64

For columns that are indeed numeric the problem that the footer is visible even if the checkbox is not checked still persists because '0' is saved to the DB and then by javascript evaluated to true (because non-empty string)

**Comment by WellingGuzman** [comment]
> For columns that are indeed numeric the problem that the footer is visible even if the checkbox is not checked still persists because '0' is saved to the DB and then by javascript evaluated to true (because non-empty string)

I made a hotfix for this solution, as number values are not casting constantly it can be sure when is a number or a string, so we can casting or do your solution. if you mind you could open PR for that.

Thanks,

Let me know if it fixes it for you.

**Comment by laszlokorte** [comment]
I am starting to work on the central typecasting.

**Comment by WellingGuzman** [comment]
Thanks, @laszlokorte.

**Comment by WellingGuzman** [comment]
I will close this as the issue was solved, but you can merge your PR whenever is ready.

Thanks
