### ISSUE TITLE
Invalid status code on INVALID_TOKEN

### ISSUE THREAD

**Issue by stefanovalentegva** [directus/directus#12318]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Even though reading from the docs the Authentication Error Codes when auth token is not valid (ie expired) should be 401 

<img width="664" alt="image" src="https://user-images.githubusercontent.com/92720697/159665447-b2ccc2ae-72be-4cf9-a6c3-03853dc70eb9.png">

I'm getting 403.

<img width="280" alt="image" src="https://user-images.githubusercontent.com/92720697/159663804-bec6bd1e-22ff-47c0-91ca-66e23171bd96.png">

It should probably be 401 Unauthorized.

The error could simply be a mismatch between code and documentation. 

In the  invalid-token.ts file (https://github.com/directus/directus/blob/66d63e7acf89e0a09d5b92bd976f87aaa67c788d/api/src/exceptions/invalid-token.ts) it says 403 while in the documentation 401.

### To Reproduce

1. login
2. let expire the **access_token**
3. make a request to **/items/:collectionName**

### Errors Shown

<img width="664" alt="image" src="https://user-images.githubusercontent.com/92720697/159667040-df8fc534-6b83-49c7-ba2d-6c1d312e7abe.png">

```
{
    "errors": [
        {
            "message": "Token expired.",
            "extensions": {
                "code": "INVALID_TOKEN",
                "stack": "Error: Token expired.\n    at verifyAccessJWT (/path/to/datahub/node_modules/directus/dist/utils/jwt.js:34:19)\n    at handler (/path/to/node_modules/directus/dist/middleware/authenticate.js:43:55)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
            }
        }
    ]
}
```

### What version of Directus are you using?

9.7.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

mysql

### What browser are you using?

API Call

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally, Docker

**Comment by azrikahar** [comment]
Just to clarify, seems like you are viewing the [v8 docs](https://v8.docs.directus.io/api/errors.html#authentication-error-codes) here, which is naturally going to have mismatch here. 😄 However the [latest (v9) docs' error code list](https://docs.directus.io/reference/introduction/#error-codes) does seem to not have `INVALID_TOKEN` documented, so it should definitely be updated.

As for the status code (in v9), it is currently returning 403 for token expiring, but we are looking to change it into 401 👍
