### ISSUE TITLE
MTM choose existing error

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1231]
development branch e05ce6

When clicking the "choose existing" button of a MTM field I get an JS error that 

`view.model` is undefined on this line: https://github.com/directus/directus/blob/development/app/router.js#L194

**Comment by WellingGuzman** [comment]
This commit https://github.com/directus/directus/commit/09238f9a1beebcebf042ad85a91b206e7996950b should do it, let me know.

**Comment by laszlokorte** [comment]
works 👍

**Comment by WellingGuzman** [comment]
Thanks @laszlokorte, closed!

Thanks as always for all this reports, if you happen to find anything else, I know you won't hesitate 👍
