### ISSUE TITLE
MTO create fails

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1232]
And another one 😄  I just update to the latest development branch (09238f9a). I am not sure if the error is new or if I just missed it before.

Creating records for tables with an MTO field does not work anymore.

I have a "people" table and a "members" table. The members table has just two columns:
`id` and `person_id`(uniq, not null) (which is a FK to the people table).

For the `person_id` column I have a MTO field.

A) If I try to create a member I get an error:
"Attempted to load new record post-insert with empty result"

B) If I add another field/column to the members table and try again I get an error:
`INSERT INTO members (other_column) VALUES ('foobar')` failed. (probably because the person_id value is not included)
I guess A) failed because if the person_id column in not included in the inserted tuple the insert statement might have looked like `INSERT INTO members () VALUES ()`.

The POST request that is made to `http://directus.dev/api/1/tables/members/rows`
has the body `person_id:{}`.
So I guess the value of the MTO field is not correctly encoded into the request.

**Comment by WellingGuzman** [comment]
Hey @laszlokorte, I fixed the problem the select tag was missing its name. here's the commit: https://github.com/directus/directus/commit/3cde6832cc67de2350ae11a3117f3dc9c2da612b.

This should've fixed the problem, tested and worked.

**Comment by laszlokorte** [comment]
Works for me 👍

**Comment by WellingGuzman** [comment]
Great to hear @laszlokorte.

**Comment by benhaynes** [comment]
Tested, and working!
