### ISSUE TITLE
MySQL Strict Mode should prevent installation pre-checks from passing

### ISSUE THREAD

**Issue by christophemarois** [directus/directus#1234]
I installed Directus on a fresh Ubuntu 16.04x64 box yesterday, on top of PHP 7 and the latest version of MySQL that has - as I learned after a long time - enabled strict mode by default, breaking most legacy queries.

It took me a long time to take the "**Strict mode enabled**" warning on the installation pre-check seriously, and considering the total failure of the installation because of it, I think it should be a check in itself, required enable the install button and to subsequently finish the installation.

Furthermore, I suggest renaming it to **MySQL strict mode** and providing links to the question. For me, [this solution](https://serverpilot.io/community/articles/how-to-disable-strict-mode-in-mysql-5-7.html) is the one that did the trick.

**Comment by benhaynes** [comment]
We can't test on the pre-check since we don't have DB creds yet. But the test is now blocking on the final install page (Confirm).
