### ISSUE TITLE
Building URLs using PUBLIC_URL is inconsistent in code

### ISSUE THREAD

**Issue by christianrr** [directus/directus#12345]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The usage of PUBLIC_URL is inconsistent in code. If PUBLIC_URL contains a slash (e.g. the default value '/'), some code snippets create URLs in the following way:

```
const acceptURL = url ? `${url}?token=${token}` : `${env.PUBLIC_URL}/admin/reset-password?token=${token}`;
```

This may result in paths like `//admin/reset-password?token=blabla`. While this is not a serious problem for most browsers, it breaks image links for example (like for the project logo on password-reset screen).

This issue was also recently mentioned in #11800.

It would make sense to consistently use the URL Builder for all URLs using env.PUBLIC_URL in order to avoid double slashes.

### To Reproduce

- Create local instance of Directus with PUBLIC_URL = '/'
- Upload a project logo
- Try to reset your password
- Reset URL in e-mail contains `...//admin/...`
- Project logo asset link is broken

### Errors Shown

none

### What version of Directus are you using?

9.7.0

### What version of Node.js are you using?

16

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣

**Comment by benhaynes** [comment]
> 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣

Haha, was meaning to look yesterday for which issue snagged this key...

**Comment by christianrr** [comment]
It's an honor 😁
