### ISSUE TITLE
Use Twig for Installation

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1235]
We should switch the installation file(s) to use Twig templating for better code organization.

**Comment by mercyg** [comment]
@benhaynes I would like to contribute to this issue. Could you please show me on how to get started?

**Comment by WellingGuzman** [comment]
Hello @mercyg,
What we want is to get all this php files into Twig templates (https://github.com/directus/directus/tree/master/installation/views)

Those views are all used here: https://github.com/directus/directus/tree/master/installation/includes/Steps

Thanks for the interest, any help we will be around.

**Comment by benhaynes** [comment]
Thanks @mercyg – that would be amazing! Welling can answer any technical questions you may have... and feel free to join us on Slack for easier communication:

slack.getdirectus.com

**Comment by Alxmerino** [comment]
I will try to take a look at this in the next couple of days as well! would love to contribute :)

**Comment by benhaynes** [comment]
Thank you so much for your contribution @Alxmerino! Another ticket bites the dust...

Always thankful for PRs!
