### ISSUE TITLE
JSON data suddenly returned as string

### ISSUE THREAD

**Issue by t7tran** [directus/directus#12367]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

We have a repeater field (JSON type) which has been working fine until upgrading to v9.7.1. Weird error rendered in the interface due to the fact that data returned by the API as a string (instead of array object). If we clear the value and configure the data again, the interface behaves as unsual until save.

![image](https://user-images.githubusercontent.com/76130324/160021487-f2ea7c7b-48df-4566-a291-cdb4de96da45.png)

If we revert it back to v9.7.0, the problem goes away.

![image](https://user-images.githubusercontent.com/76130324/160012854-2ef5d895-7c4a-4405-a2d5-3792aa2d1997.png)

### To Reproduce

To reproduce, we run it with v9.7.1.

1. Go to the same singleton collection with affected field named `user_navigation`
2. Create two new Repeater fields named `test` and `user_navagation` (note the misspelt). Use any structure.
3. Go to the collection content page and copy and paste the following raw value in both new fields then Save:

```
[
	{
		"icon": "dashboard",
		"name": "Dashboard",
		"target": "/user/dashboard/default"
	},
	{
		"icon": "account_box",
		"name": "My Profile",
		"target": "/user/form1/profile",
		"required_permissions": [
			{
				"actions": [
					"create",
					"read",
					"update"
				],
				"collection": "profile"
			}
		]
	},
	{
		"icon": "local_activity",
		"name": "My Assignments",
		"target": "/user/bookings",
		"required_permissions": [
			{
				"actions": [
					"read"
				],
				"collection": "ep_booking"
			}
		]
	},
	{
		"icon": "feedback",
		"name": "Feedback",
		"target": "/user/form1/feedback",
		"required_permissions": [
			{
				"actions": [
					"create",
					"read",
					"update"
				],
				"collection": "feedback"
			}
		]
	}
]
```

Notice that value in field `test` works fine, while `user_navagation` field is corrupted.

![image](https://user-images.githubusercontent.com/76130324/160021580-22a5eec9-f00d-448f-b09d-96a4be2b5c5b.png)

### Errors Shown

See screenshots above.

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

Docker

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying Directus?

Docker

**Comment by t7tran** [comment]
I tried again with some more field but none of them works apart from the `test` field. Here's the current table schema.

```
mysql> show create table ep_settings;
+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table       | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                               |
+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ep_settings | CREATE TABLE `ep_settings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `paper_preview_notes` text COLLATE utf8_bin,
  `user_navigation` json DEFAULT NULL,
  `test` json DEFAULT NULL,
  `user_navagation` json DEFAULT NULL,
  `usernavigation` json DEFAULT NULL,
  `somenavigation` json DEFAULT NULL,
  `some` json DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_bin
```

**Comment by licitdev** [comment]
@t7tran This should be due to a migration failing. 
Please confirm if there is an error when running `npx directus database migrate:latest`.
Thank you.

**Comment by t7tran** [comment]
Thanks @licitdev. But I'm using Docker which includes migration in its bootstrap command. MySQL v5.7 is used.

**Comment by licitdev** [comment]
@t7tran Please assist to check `directus_migrations` on whether an entry exists for migration `20220322A`.

**Comment by azrikahar** [comment]
@t7tran by the way, would you mind sharing the content of `directus_fields` here? especially interested in the "special" column here for the fields that are erroring out for you.

**Comment by t7tran** [comment]
@licitdev here it is

```
select * from directus_migrations where version = '20220322A';
+-----------+-----------------------------+---------------------+
| version   | name                        | timestamp           |
+-----------+-----------------------------+---------------------+
| 20220322A | Rename Field Typecast Flags | 2022-03-24 00:48:56 |
+-----------+-----------------------------+---------------------+
1 row in set (0.29 sec)
```

**Comment by t7tran** [comment]
@azrikahar here it is

```
mysql> select * from directus_fields where collection = 'ep_settings' and field = 'user_navigation' \G
*************************** 1. row ***************************
             id: 197
     collection: ep_settings
          field: user_navigation
        special: json
      interface: list
        options: {"fields": [{"meta": {"note": "Item name", "type": "string", "field": "name", "width": "half", "options": {"trim": true}, "interface": "input"}, "name": "name", "type": "string", "field": "name"}, {"meta": {"note": "Item Key", "type": "string", "field": "key", "width": "half", "options": {"slug": true, "trim": true}, "interface": "input"}, "name": "key", "type": "string", "field": "key"}, {"meta": {"note": "Target Path", "type": "string", "field": "target", "width": "half", "options": {"trim": true}, "interface": "input"}, "name": "target", "type": "string", "field": "target"}, {"meta": {"note": "Item Icon", "type": "string", "field": "icon", "width": "half", "interface": "select-icon"}, "name": "icon", "type": "string", "field": "icon"}, {"meta": {"type": "json", "field": "required_permissions", "options": {"fields": [{"meta": {"type": "string", "field": "collection", "options": {"trim": true}, "interface": "input"}, "name": "collection", "type": "string", "field": "collection"}, {"meta": {"type": "json", "field": "actions", "options": {"choices": [{"text": "Create", "value": "create"}, {"text": "Read", "value": "read"}, {"text": "Update", "value": "update"}, {"text": "Delete", "value": "delete"}, {"text": "Comment", "value": "comment"}, {"text": "Explain", "value": "explain"}, {"text": "Share", "value": "share"}]}, "interface": "select-multiple-checkbox"}, "name": "actions", "type": "json", "field": "actions"}], "template": "{{collection}}"}, "interface": "list"}, "name": "required_permissions", "type": "json", "field": "required_permissions"}], "template": "{{name}}"}
        display: formatted-json-value
display_options: {"format": "{{name}}"}
       readonly: 0
         hidden: 0
           sort: 3
          width: full
   translations: []
           note: NULL
     conditions: NULL
       required: 0
          group: NULL
1 row in set (0.28 sec)
```

**Comment by licitdev** [comment]
@t7tran Please help to run `npx directus database migrate:down` then `npx directus database migrate:up`, and verify if the `special` column in `directus_fields` is updated from `json` to `cast-json`?

**Comment by t7tran** [comment]
`migrate:down` finished without anything printed in the console, `migrate:up` reported below:

```
10:02:53 🚨 Nothing to upgrade 
Error: Nothing to upgrade
    at up (/directus/node_modules/directus/dist/database/migrations/run.js:56:19)
    at run (/directus/node_modules/directus/dist/database/migrations/run.js:39:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async migrate (/directus/node_modules/directus/dist/cli/commands/database/migrate.js:13:9)
    at async Command.parseAsync (/directus/node_modules/commander/lib/command.js:923:5)
```

**Comment by t7tran** [comment]
Also, all JSON fields have the same `json` in special column. How come the `test` field is rendered correctly.

```
select field,special from directus_fields where collection = 'ep_settings';
+---------------------+---------+
| field               | special |
+---------------------+---------+
| id                  | NULL    |
| paper_preview_notes | NULL    |
| user_navigation     | json    |
| test                | json    |
| user_navagation     | json    |
| usernavigation      | json    |
| somenavigation      | json    |
| some                | json    |
+---------------------+---------+
```

**Comment by licitdev** [comment]
> `migrate:down` finished without anything printed in the console

This is indeed odd as there should be a downgrade log such as:

<img width="329" alt="image" src="https://user-images.githubusercontent.com/26413686/160101628-0d00142d-df16-4730-b955-aa1c9486b131.png">

> Also, all JSON fields have the same json in special column. How come the test field is rendered correctly.

This is something I am confused about. 
json` fields created in `9.7.1` should have the `special` saved as `cast-json`, but as shown above, it's still saved as `json`.
Please confirm if your running directus instance is on `9.7.1`.

Also, are you running multiple instances of Directus? I wonder if it's because you may still be connecting to an older instance.

**Comment by t7tran** [comment]
I ran commands directly in the container with `LOG_LEVEL` set to `warn`. However, as I restarted the container, those columns are now updated to `cast-json`. And those fields now render correctly. Thank you very much.

As I commented in #12141, this should have been flagged in the `v9.7.1` release notes which I always check before upgrading. It would help us updating our schema bootstrap accordingly.
