### ISSUE TITLE
TypeError: env_1.default.STORAGE_LOCATIONS.split is not a function

### ISSUE THREAD

**Issue by kuzmi4** [directus/directus#12365]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

env_1.default.STORAGE_LOCATIONS - is array 

fresh test instalation:

<img width="1036" alt="изображение" src="https://user-images.githubusercontent.com/6544815/160009511-c8ebf32e-eaa5-401f-92ca-a88a40d96372.png">

### To Reproduce

Just run 9.7.1 version with multiple locations like this: `STORAGE_LOCATIONS="local,somesecond"`

### Errors Shown

TypeError: env_1.default.STORAGE_LOCATIONS.split is not a function

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

v16.14.0

### What database are you using?

sqlite

### What browser are you using?

Firefox

### What operating system are you using?

MacOS

### How are you deploying Directus?

running locally

**Comment by u12206050** [comment]
Fixed in this commit #1395e7d10c22377acf9402ba5b4b9b40ddef659c

**Comment by adanielyan** [comment]
I'm having the same issue but with AUTH_PROVIDERS.  Will this fix it too?

> Fixed in this commit [1395e7d](https://github.com/directus/directus/commit/1395e7d10c22377acf9402ba5b4b9b40ddef659c)

I'm having the same issue but with AUTH_PROVIDERS.  Will this commit fix it too?

**Comment by azrikahar** [comment]
> I'm having the same issue but with AUTH_PROVIDERS. Will this commit fix it too? The issue is described here: #12403

That specific commit doesn't, but a follow up PR #12370 yesterday fixed this.
