### ISSUE TITLE
Friendly Errors

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1237]
All error notifications should be friendly and easy to understand, and then give a detailed/technical error message in `console.error`.

_For example, currently we get this:_

```
Server Error

Fatal error: Maximum execution time of 30 seconds exceeded in /var/www/directus/vendor/zendframework/zend-db/src/Sql/Select.php on line 718
```

But that should be the console error (with any other help info) and the following should be the notification error:

```
Error
The server is taking too long with this request. If this persists please contact an administrator.
```

**Comment by benhaynes** [comment]
Just a note reminder that we should try to clean up the "File too large" error at some point

**Comment by WellingGuzman** [comment]
Make sure to add a warning message that alerts the user when an existing email belong to another existing user when they are trying to create a new user. (Ref #1983)

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/3)
