### ISSUE TITLE
Fatal error at installation

### ISSUE THREAD

**Issue by Kakoum** [directus/directus#1238]
Hello guys, i want to try your CMS, but i have a problem :'(

## Version Info
  - Directus version: last github version
  - PHP version: 5.6
  - MySQL version: 5.7
  - Web server: (Ex. Apache, nginx or IIS?): Apache (wamp)
  - OS name and version: Windows 10

## Expected Behavior
Installation :o

## Actual Behavior
Fatal error

## Steps to Reproduce
 1. Simply installation

## Logs or Screenshots
http://image.noelshack.com/fichiers/2016/33/1471520510-directus.png

**Comment by benhaynes** [comment]
Hey @Kakoum – thanks for the ticket! We will get this resolved and pushed this morning...

**Comment by benhaynes** [comment]
Hey @Kakoum – it looks like this was an issue with the database being in STRICT MODE. We have fixed the issue and you should be able to install without a problem now. We're working toward better support of STRICT MODE in the next few weeks...

**Comment by Kakoum** [comment]
Thx boys ! I will try that
