### ISSUE TITLE
I'm getting a login error after installation

### ISSUE THREAD

**Issue by jbcoder** [directus/directus#1239]
## Version Info
  - Directus version and branch: (Or commit hash): Version 6.3.0RC
  - PHP version: 5.5.8
  - MySQL version: 5.6.15
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: Windows 10

## Expected Behavior
Install Directus as a local installation.
Login using email and password.

## Actual Behavior
Install Directus as a local installation.
Getting error when submitting email and password. (I see in the console that there is a 404 error to the api path.)

## Steps to Reproduce
 1. Install a fresh installation
 2. Try to log in

## Logs or Screenshots
![login-error](https://cloud.githubusercontent.com/assets/1719239/17790871/4dc05fca-654d-11e6-8dc6-aa4891b52802.PNG)

**Comment by WellingGuzman** [comment]
Hello there @jbcoder,

Is apache mod_rewrite installed?

**Comment by jbcoder** [comment]
Yes, it is. All Pre-Installation Checks passed.

**Comment by WellingGuzman** [comment]
Is there something in your logs? PHP logs or Directus log (`api/logs`)?

I will try if I can replicate this issue.

**Comment by jbcoder** [comment]
The only thing I'm seeing is `development.log` which contains the following:
```
Aug 18 16:51:23 [info] CREATE TABLE `directus_schema_migrations` (
`version` varchar(255))  ENGINE=InnoDB  DEFAULT CHARSET=utf8;
Aug 18 16:51:23 [info] CREATE UNIQUE INDEX `idx_directus_schema_migrations_version` ON `directus_schema_migrations`(`version`)
Aug 18 16:51:29 [info] SELECT version FROM directus_schema_migrations
Aug 18 16:51:29 [info] SELECT version FROM directus_schema_migrations
Aug 18 16:51:29 [info] SELECT version FROM directus_schema_migrations

```

**Comment by laszlokorte** [comment]
Did you try setting `RewriteBase /` in your .htaccess?

**Comment by jbcoder** [comment]
@laszlokorte I just tried that. No different result.

**Comment by WellingGuzman** [comment]
Maybe it should've been `RewriteBase /api` instead.

@laszlokorte is this something required by windows servers?

**Comment by laszlokorte** [comment]
In the /api/.htaccess as well? (maybe there you need to set `RewriteBase /api`)

**Comment by jbcoder** [comment]
I just changed it in /api/.htaccess. That seemed to do the trick! Thanks!

**Comment by WellingGuzman** [comment]
Thanks @laszlokorte. Great to hear @jbcoder 

I will add this into the `.htaccess` files.

**Comment by laszlokorte** [comment]
I think RewriteBase is not required in all cases and might not work in every case. It depends on how the webserver's DocumentRoot is configured.

For example if you install directus into a sub directory RewriteBase might cause an error.

**Comment by jbcoder** [comment]
If it helps, I have my dev environment set up like this:

```
<Directory "/www">
    Options Indexes MultiViews FollowSymLinks
    AllowOverride All
    Order allow,deny
    Allow from all
</Directory>

<VirtualHost *:80>
    VirtualDocumentRoot "C:\www\%1\www"
    ServerName sites.dev
    ServerAlias *.dev
    UseCanonicalName Off
</VirtualHost>
```

So, right now I'm accessing the site from directus.dev.

**Comment by WellingGuzman** [comment]
Thanks @laszlokorte.
I will add this in the documentation instead.

**Comment by jbcoder** [comment]
I don't know if this is related since this is my first time playing around with Directus, but I keep getting modal popup on the main page (tables) that says "You do not have permission to view that page or it doesn't exist". I've even added tables.

**Comment by laszlokorte** [comment]
The problem is caused by your VirtualDocumentRoot configuration. When using virtual document roots, apache can not determine the rewrite base path on it's own.

http://blog.lavoie.sl/2012/07/document-root-fix-in-htaccess-when.html

**Comment by WellingGuzman** [comment]
Thanks @laszlokorte, for helping out, it seems what you told him lead him to fix the server configuration problem.

@jbcoder I assume you have already fixed your issue, if that's not the case let us know.

**Comment by pdro-enrique** [comment]
> If it helps, I have my dev environment set up like this:
> 
> ```
> <Directory "/www">
>     Options Indexes MultiViews FollowSymLinks
>     AllowOverride All
>     Order allow,deny
>     Allow from all
> </Directory>
> 
> <VirtualHost *:80>
>     VirtualDocumentRoot "C:\www\%1\www"
>     ServerName sites.dev
>     ServerAlias *.dev
>     UseCanonicalName Off
> </VirtualHost>
> ```
> So, right now I'm accessing the site from directus.dev.

Thanks, this works for me.
