### ISSUE TITLE
Table creation issue

### ISSUE THREAD

**Issue by Kakoum** [directus/directus#1240]
I have almost the same mistake than : https://github.com/directus/directus/issues/1201
This issue is close and is not the same file, so i recreate a issue :s

## Version Info
  - Directus version and branch: Last version on github, Master or Build
  - PHP version: 5.5
  - MySQL version: 5.6
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: Windows 10

## Expected Behavior
Table should show up and be editable

## Actual Behavior
Creating table (it shows up in phpmyadmin), not showing up below "tables"

## Steps to Reproduce
 1. Create a table with some fields
 2. Try to look below tables

## Logs or Screenshots
When i click on my "table" after creation :
Error: Uncaught TypeError: Cannot read property '_listenerId' of undefined File: http://localhost/directus/assets/js/directus.min.js?bust=vdmcsv1j5q7jvbfn6q384u0844 Line:8 
And if i refresh my page, my table disappears

**Comment by benhaynes** [comment]
Hey @Kakoum – are you creating the table in Directus or PHPMyAdmin? Do you have any column in it? If you can export the SQL for the table and include it here that might help. Thanks again for reporting this!

**Comment by Kakoum** [comment]
Hello !
I create the table "Articles" in Directus directly. I add two fields (textinput and wyslwyg)
This is my screenshot of phpMyAdmin : http://www.zupimages.net/up/16/33/v7iv.png (4 columns).
After create table "Articles" and add news fields (in Directus), i want click on "Articles" (under "Tables") but i have this error javascript "Cannot read property '_listenerId' of undefined File".
After that i try to refresh my page, and "Articles" disappears.

**Comment by Kakoum** [comment]
Ok i can create table, is nice.
I can  reproduce the bug with these steps : 
- Create new table
- Add field textinput + save item
- Add field wysiwyg + save item
- Save item (save table)

I think is because i create two fields following

**Comment by benhaynes** [comment]
Hey @Kakoum – we're having trouble replicating this issue so we're going to move it to the `6.3.1` patch. We'll fix it as soon as we can find find reliable steps to reproduce. Thanks again for reporting! Let us know if you're still experiencing it after upcoming the `6.3` merge and deploy.

**Comment by WellingGuzman** [comment]
@Kakoum We've found the bug and fixed it.

Tables were being saved as `nav_listed = 0` that prevented the table from being listed in the navigation (sidebar).
