### ISSUE TITLE
auth/refresh 400 error

### ISSUE THREAD

**Issue by j-kia** [directus/directus#12415]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I'm trying to use sameless SSO with google openID provider. I do all configuration guide that provided in directus single sign-on docs. But the problem is when i redirected to page that i specified in auth/login/google url, the cookie is successfully set but when i sending refresh token request without payload (with `withCredentials: true`) to get access_token, always give me 400 error and it seems it can't read `directus_refresh_token` from cookies.

### To Reproduce

Just send a post request without payload to auth/refresh with `withCredentials: true` after redirected to my page. my directus server is on docker and my front running locally (i put it on server but problem was still there).

- when i manually checked the cookies after login, the directus_refresh_token was successfully set
- Sending request
`await fetch('https://api.renotive.demo.greensoft.dev/auth/refresh', {
        method: 'POST',
        withCredentials: true,
      })`

- My .env
```  AUTH_PROVIDERS: "google"
    AUTH_GOOGLE_DRIVER: "openid"
    AUTH_GOOGLE_CLIENT_ID: ******************
    AUTH_GOOGLE_CLIENT_SECRET: ******************
    AUTH_GOOGLE_ISSUER_URL: "https://accounts.google.com"
    AUTH_GOOGLE_IDENTIFIER_KEY: "email"
    AUTH_GOOGLE_ICON: "google"
    AUTH_GOOGLE_ALLOW_PUBLIC_REGISTRATION: "true"
    AUTH_GOOGLE_DEFAULT_ROLE_ID: '3448c9ef-6456-4cad-8015-87a4e8fe1c31'

    REFRESH_TOKEN_COOKIE_DOMAIN: "api.renotive.demo.greensoft.dev"
    REFRESH_TOKEN_COOKIE_SECURE: "true"
    REFRESH_TOKEN_COOKIE_SAME_SITE: "None"
```

### Errors Shown

```
"errors": [
        {
            "message": "\"refresh_token\" is required in either the JSON payload or Cookie",
            "extensions": {
                "code": "INVALID_PAYLOAD"
            }
        }
    ]
```

### What version of Directus are you using?

9.6.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

MySql

### What browser are you using?

chrome

### What operating system are you using?

linux

### How are you deploying Directus?

Docker

**Comment by Silbad** [comment]
Hello, same pb, refresh_token is required for sdk logout with cookie method
https://docs.directus.io/reference/authentication/#logout
"The refresh token to invalidate. **If you have the refresh token in a cookie** through [/auth/login](https://docs.directus.io/reference/authentication/#login), **you don't have to submit it here**."

**Comment by azrikahar** [comment]
I think there's a mix up here as [withCredentials](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials) is not a valid option.

I believe you are looking for `credentials`, reference to MDN docs: https://developer.mozilla.org/en-US/docs/Web/API/fetch

For clarity, here you can see at first I used the same `withCredentials: true` as your example, and it does indeed shows the exact same error. We can see that when we check the Request Header, there is no cookie sent at all.

However, after I changed it to `credentials: 'include'`, we can see that the request completes successfully with a new access token returned. We can also see when we check the Request Header, the `directus_refresh_token` is sent properly.

https://user-images.githubusercontent.com/42867097/161495864-1ceb828e-0494-4838-8993-47d4d417b9e4.mp4

I'll proceed to close this issue first, but if the issue still persists for you after using the correct fetch option, feel free to share more detail for us to replicate it and we'll reopen this issue 👍
