### ISSUE TITLE
New WYSIWYG UI Module

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1242]
_There are several issues/limitations with the current WYSIWYG interface module, below are the requirements for the new UI:_
## Design

The style of the UI **must** conform to that of Directus Core. Intuitive, minimal, and following the same CSS styles/colors/states. Buttons should be flat and free of gradients. Iconography should not have color.
## Options

All buttons and settings within the UI should be adjustable through the UI's options so that the interface can be customized as much as possible. Core options such as `readonly` and `required` should also work as expected.
## Minimum Formatting Buttons

These can contextually appear beside the cursor only when applicable (eg: [Tumblr](https://cdn-images-1.medium.com/max/600/1*bVHdLH8rhNJbTt9pyp0mIg.png)), or be constant.
1. Bold
2. Italic
3. Underline
4. Create Link (new or from selected text)
5. Blockquote
6. Headlines (H1, H2, H3)
## Optional Formatting Buttons
- Toggle HTML
- Strikethrough
- Ordered List
- Unordered List
- Markdown mode
- Horizontal Rule
- Text Justification and Alignment
## Images & Embeds
- Choose from Directus Files
- Insert Image
- Drag and Drop Upload/Placement
- Add Video Embed
## Other Potential Options
- Input height (in pixels or rows)
- Full-screen Mode
- Proper Undo/Redo
- Use `p` or `br` for line breaks
- Image alignment/sizing options
- Table Support
- Emoji support 🔥 
## Libraries & Inspiration

https://imperavi.com/redactor/
https://www.froala.com/wysiwyg-editor
http://getcontenttools.com/
https://www.tumblr.com/ (requires account to try editor)
https://medium.com/ (requires account to try editor)

**Comment by benhaynes** [comment]
Additionally, we have opened up a **[BountySource](https://www.bountysource.com/issues/37216910-new-wysiwyg-ui-module) item for $250** to try and get a quality UI built more expeditiously.

**Comment by laszlokorte** [comment]
What to you think about markdown support? Ie converting the content to markdown before saving it to the database.

Or something like:
https://simplemde.com/

**Comment by benhaynes** [comment]
Exactly @laszlokorte – I had included that under `Optional Formatting Buttons` as I don't think it's required. I think it could be a useful UI Option... or it could be it's own UI module (since it's so useful).

The real question is how how we delineate each module. @WellingGuzman and I just discussed this at length for the `datetime`, `date`, and `time` modules... should they be combined, extended, or remain individual since they deal with different datatypes.

Ultimately we're looking to get a WYSIWYG editor, and any other UIs people can dream/code up. I'd love to hear your thoughts!

**Comment by chrisys** [comment]
What about text alignment tools? This is something that seems to be overlooked in a lot of editors but is frequently asked for by our users.

**Comment by benhaynes** [comment]
Good thinking @chrisys – we can add those as optional buttons as well. Typically we try to keep any formatting that borders on design out of the content – but I too have had clients request this option.

**Comment by lukeed** [comment]
I've encountered this same problem with a few of personal & client projects & eventually decided to roll my own solution. So, may I (shamelessly 😇) suggest [`editor-lite`](https://github.com/lukeed/editor-lite)? 

Although there are a lot of options out there, most of them include clunky UIs, without much room for customization _and_ they're usually massive libraries (60+ kb minified, some are 220!!!). Most devs don't care about byte size, but I do, and so do mobile users.

There's no public demo right now; I've been meaning to get one up. But I've been using it successfully in a few projects, as mentioned.

Here's a screenshot of it in action:

<img width="686" alt="screen shot 2016-11-18 at 11 23 10 am" src="https://cloud.githubusercontent.com/assets/5855893/20443512/f352057a-ad81-11e6-9e60-7117c6a87147.png">

**Comment by benhaynes** [comment]
Thanks @lukeed – any and all input is appreciated, especially on this thread as it's a big topic of contention.

I like your editor: lightweight, simple, and extensible... exactly what we're looking for.

We're working on a design and markup refresh for `v6.6` so we will start experimenting with your library soon. Thanks!

**Comment by lukeed** [comment]
@benhaynes Cool, thanks! I was planning on doing some demos next week, but maybe I'll expedite it for this weekend. 🤔

**Comment by csprance** [comment]
Quill.js is another really nice editor. 
I've been integrating it as a custom ui lately. 

I'll send a pr when I make more progress. Hooking up image upload now.

**Comment by doughnet** [comment]
it would be great if a new wsywig editor could use/understand oEmbed.  I didn't know what this was until I played around with postleaf.

Details: [http://oembed.com/](http://oembed.com/)

**Comment by pittkost** [comment]
One suggestion - Directus is front end agnostic so the WYSIWYG should be. Let's say my CSS describing classes, not HTML tags, so I'd like to set up WYSIWYG to output something like `<h1 class="heading-1">text</h1>`, rather then raw `<h1>text</h1>` for top heading element.

**Comment by benhaynes** [comment]
An excellent point @pittkost! 

I agree that this would be the ideal way to move forward and have run into this situation with my own client work. Most WYSIWYG editors have an "HTML" view toggle to accomplish this, but it's not an ideal UI/UX. We're overhauling the platform design and UIs now and will be creating a new WYSIWYG editor – we'll look into libraries that would support this customization and how we would structure the UI Options for setting this up.

Thanks for the suggestion!

**Comment by csprance** [comment]
## CkEditor WYSIWYG
I'll drop this here with the understanding it's not complete but I don't really have a lot of time to polish it. The only bug I've found is that when you have two of them in one table and you saved it then edit it, the contents of one will be deleted. I am using it in production so the in the interest of open source I want to release it.

It also makes an ajax call for the ckeditor libs so if you have no internet it won't work.

Drop this into `Directus/customs/uis/ckeditor/`


https://gist.github.com/csprance/dc0236d3e66ebcda7362f81fbfe06137

Someones please polish me :)

**Comment by ricricucit** [comment]
Which wysiwyg is being added? Is it sir-trevor mentioned in issued #1297

**Comment by WellingGuzman** [comment]
We added a new WYSIWYG Interface https://github.com/directus/directus/pull/1430, similar to Medium, thanks to @rijkvanzanten

**Comment by WellingGuzman** [comment]
Still missing some features, but are on the way, to a more clean less buggy solution.

**Comment by benhaynes** [comment]
We'll have two: Simple (medium style inline WYSIWYG) and Full-Featured (typical editor, with a million buttons options). Most likely using:

https://www.froala.com/wysiwyg-editor

**Comment by benhaynes** [comment]
One of the major updates in 6.4 is the new WYSIWYG editors. We have an Inline version (based on Medium) and an full-featured version (TinyMCE). We are abandoning the existing custom version in favor of these new options – although it could easily be migrated to 6.4 if you want to continue using it.

We will continue to evolve these editors, but the hard part has been done.

A big thank you to @rijkvanzanten (our Interface Lead) for making these updates – this also closes the number one issue on [FeatHub](http://feathub.com/directus/directus/+30).

**Comment by surfmuggle** [comment]
+1 for TABLE Support in WYSIWYG

**Comment by azrikahar** [comment]
@surfmuggle that sounds like a good idea for a discussion. It's probably better to make this suggestion over there instead of commenting on past closed issue, since it can be hard for the team to keep track of things. Much appreciated 👍

**Comment by benhaynes** [comment]
Also... we already have it. Just needs to be enabled in the Interface Options. @surfmuggle @azrikahar 

![Screen Shot 2021-11-15 at 10 56 38 AM](https://user-images.githubusercontent.com/522079/141813246-39056fb6-13c8-420c-85f9-391cc263d347.png)
