### ISSUE TITLE
Delete files from multiple files interface doesn't delete.

### ISSUE THREAD

**Issue by JonL1** [directus/directus#12424]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Deleting files from a multiple files interface doesn't delete the rows from the database. So when I reload the item they will show up again.

Maybe fixed with the relational interfaces rework (#12082)?

Reporting it because I haven't seen an open issue specifically related to the delete action.

### To Reproduce

Nothing special.

Within a record with a multiple files interface:

1) Delete by clicking X icon
2) Save record
3) Check DB or load record again

### Errors Shown

No errors

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

16.3.1

### What database are you using?

Postgres 12.9

### What browser are you using?

Safari, Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment]
This is actually the same as #12099, since the Files interface uses the same M2M composable under the hood. I've verified that this issue is present in `v9.7.1`, but can also confirm that it has been fixed by #12187 (not released yet) 👍
