### ISSUE TITLE
Error "Image source too large to preview" persists for smaller image files until the page is refreshed

### ISSUE THREAD

**Issue by skaidra-bake** [directus/directus#12431]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Directus displays an error: "Image source too large to preview" instead of a thumbnail (as shown in the first screenshot below) when using image files that have physical dimensions higher than 6000px in height or width.
However, when the big image is replaced with a smaller one (dimensions below 6000px), the error persists (second screenshot) unless the page is refreshed (data model is saved).

<img width="831" alt="Screenshot 2022-03-28 at 16 25 31" src="https://user-images.githubusercontent.com/69679313/160432402-99670c09-552a-43fa-9eca-5a603a776183.png">

<img width="683" alt="Screenshot 2022-03-28 at 16 48 34" src="https://user-images.githubusercontent.com/69679313/160437087-3ee23261-2294-444e-96e6-45437406710f.png">

### To Reproduce

1. Create a data model that has an image file attached.
2. Go to the content, create a new instance of that data model
3.  Set their image to an image that is too big to preview (> 6000px wide/high)
4. Save the instance.
5. Go back to editing the instance, remove the image that's too big to preview and replace it with one that isn't too big to preview.

This should still display the mentioned error until the instance is saved (the thumbnail is showed after save).

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

16.14.2

### What database are you using?

Postgres 12.10

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Heroku

**Comment by domdus** [comment]
Faced the same while dealing with big images (6720 × 4480 px) and thumbs are not generated in file lib.
`errors: [{message: "Image is too large to be transformed, or image size couldn't be determined.",…}]`

Hope this limitation can be eliminated completely?

**Comment by rijkvanzanten** [comment]
>  Hope this limitation can be eliminated completely?

@domdus the limit at which it stops trying to transform images is configurable through `ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION` 👍🏻 It's set to 6000px by default. Just be aware that transforming big images like that will cost more cpu/memory, so make sure your server is up to the task.

**Comment by domdus** [comment]
Ah cool, thx @rijkvanzanten !

**Comment by notflip** [comment]
@rijkvanzanten What happens to images above 6000px?

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten What happens to images above 6000px?

The API will throw a not-allowed error 👍🏻
