### ISSUE TITLE
ENUM/SET

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1243]
## Version Info
  - Directus version and branch: d8264b3da

Creating an ENUM UI with a SET column is currently not possible because the length field is hidden but a SET column requires the options to be specified.

**Comment by benhaynes** [comment]
Good catch! As always, we appreciate the testing/tickets!

**Comment by WellingGuzman** [comment]
This [commit](https://github.com/directus/directus/commit/93be0caeef89e58f77d0c1b3a21b4c8a6c938411) should've fixed this.

The way to set the value list is by typing values separated by comma in the "length" field.
