### ISSUE TITLE
Date UI auto-populate_when_hidden_and_null

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1244]
## Version Info
  - Directus version and branch: d8264b3da

The UI option to autopopulate the a date field when it's hidden and null currently has no effect.

**Comment by benhaynes** [comment]
Thanks @laszlokorte! Must have missed this in our datetime/date/time overhaul a few weeks ago.

**Comment by WellingGuzman** [comment]
https://github.com/directus/directus/commit/030a2ec2f940da8520e249e8dd2206065906e9ea should fix this issue.
