### ISSUE TITLE
LDAP is not working: TypeError: name (string) required

### ISSUE THREAD

**Issue by LasseRosenow** [directus/directus#12442]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I just tried to integrate LDAP into directus, but whenever I try to login, I get an error in the logs.
The issue comes from [ldapjs](https://github.com/ldapjs/node-ldapjs/blob/9143456b4fa2e07127fb1fd37677fdfd4c73a6c5/lib/dn.js#L157) ... it seems like the parse function gets called with some parameter that is no string, even though it should be.

### To Reproduce
```
AUTH_PROVIDERS: ldap

AUTH_LDAP_DRIVER: ldap

AUTH_LDAP_CLIENT_URL: ldap://corp.cedgetec.com

AUTH_LDAP_BIND_DN: CN=DirectusSVCLookupuser,OU=Service,OU=Users,OU=Domain,DC=corp,DC=cedgetec,DC=com

AUTH_LDAP_BIND_PASSWORD: ******

AUTH_LDAP_USER_DN: DC=corp,DC=cedgetec,DC=com

AUTH_LDAP_USER_SCOPE: sub

AUTH_LDAP_GROUP_DN: DC=corp,DC=cedgetec,DC=com

AUTH_LDAP_GROUP_SCOPE: sub
```
### Errors Shown

```
21:53:40 🚨 name (string) required 
TypeError: name (string) required
    at Object.parse (/directus/node_modules/ldapjs/lib/dn.js:158:43)
    at ensureDN (/directus/node_modules/ldapjs/lib/client/client.js:85:15)
    at Client.search (/directus/node_modules/ldapjs/lib/client/client.js:596:18)
    at /directus/node_modules/directus/dist/auth/drivers/ldap.js:66:29
    at new Promise (<anonymous>)
    at LDAPAuthDriver.validateBindClient (/directus/node_modules/directus/dist/auth/drivers/ldap.js:64:16)
    at LDAPAuthDriver.getUserID (/directus/node_modules/directus/dist/auth/drivers/ldap.js:184:20)
    at AuthenticationService.login (/directus/node_modules/directus/dist/services/authentication.js:47:43)
    at /directus/node_modules/directus/dist/auth/drivers/ldap.js:303:84
    at scoped (/directus/node_modules/directus/dist/utils/async-handler.js:5:60)
```

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

16

### What database are you using?

MariaDB

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

On a remote Debian server

**Comment by rijkvanzanten** [comment]
Can you try try prefixing the value for `AUTH_LDAP_BIND_DN` with `string:`? So it becomes:

```
AUTH_PROVIDERS="ldap"
AUTH_LDAP_DRIVER="ldap"
AUTH_LDAP_CLIENT_URL="ldap://corp.cedgetec.com"
AUTH_LDAP_BIND_DN="string:CN=DirectusSVCLookupuser,OU=Service,OU=Users,OU=Domain,DC=corp,DC=cedgetec,DC=com"
AUTH_LDAP_BIND_PASSWORD="******"
AUTH_LDAP_USER_DN="string:DC=corp,DC=cedgetec,DC=com"
AUTH_LDAP_USER_SCOPE="sub"
AUTH_LDAP_GROUP_DN="string:DC=corp,DC=cedgetec,DC=com"
AUTH_LDAP_GROUP_SCOPE="sub"
```

i believe the ldap DN config expects a CSV string, rather than an array of values

**Comment by LasseRosenow** [comment]
Thank you, this seems to be working.

The documentation is wrong then?

![image](https://user-images.githubusercontent.com/10547444/160497255-0b06ae36-df99-466f-9321-de264daedffa.png)

**Comment by azrikahar** [comment]
Thanks for bringing this up! I believe this is an unintended side effect of #12330. Technically the docs were correct up until that point 😄

This may require a joint effort with #9521 (such as _not_ casting certain env vars to array, or perhaps just updating the docs to explicitly note the use of `string:` moving forward?).

**Comment by viharm** [comment]
Prefixing the DNs with `string:` worked for me too. Thanks.

**Comment by viharm** [comment]
@aidenfoxx for LDAP.

**Comment by aidenfoxx** [comment]
This one doesn't really have much to do with me @viharm, but if I were to chime in I'd say it's better to skip or cast known problematic config vars in the config parser to keep the logic in a single location.

**Comment by zicklag** [comment]
Prefixing worked for me, too! The first issue I've had so far with Directus and there's a clear and easy workaround in the GitHub issues. Thanks!

It looks like you guys are doing a great job!

**Comment by rijkvanzanten** [comment]
Closing this in favor of https://github.com/directus/directus/issues/9521
