### ISSUE TITLE
Fix this bug which blocks CORS and any OPTIONS requests

### ISSUE THREAD

**Issue by jeremybradbury** [directus/directus#12447]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

This is a bug not a feature: https://github.com/directus/directus/blob/d64ca14348184e69e4348c8c61bbf88ffcc9937a/api/src/middleware/graphql.ts#L8-L10

### To Reproduce

try to use graphql over https using POST in 9.7.1... for some reason it still works in 9.6 and prior

### Errors Shown

Directus: `GraphQL only supports GET and POST requests.`

Browser: 
```
Request Method: OPTIONS
Status Code: 405 Method Not Allowed
```

### What version of Directus are you using?

v9.7.1

### What version of Node.js are you using?

14.19

### What database are you using?

Postgres 12

### What browser are you using?

Chrome, Brave & Firefox 

### What operating system are you using?

Ubuntu 20.04

### How are you deploying Directus?

systemd service

**Comment by jeremybradbury** [comment]
this is related: https://github.com/directus/directus/issues/12259

**Comment by rijkvanzanten** [comment]
This is most likely caused due to misconfiguration, as per https://github.com/directus/directus/issues/12259
