### ISSUE TITLE
NodeJS Server side + mongoDB support

### ISSUE THREAD

**Issue by kamikazechaser** [directus/directus#1245]
**This is a mongoDB port request and NodeJS server-side port request**

This is in relation to:
https://github.com/directus/directus#new-contributors

Reason:

NodeJS => Very popular server-side language hence easy to find contributors!
mongoDB=> Very popular database usually used together with a NodeJS app! 

P.S I will get intouch to see if I can contribute and also bring others on board!

**Comment by WellingGuzman** [comment]
Hello @kamikazechaser, you must open request to http://feathub.com/directus/directus.
You can open both request for MongoDB and NodeJS server-side.

We have priority on nodeJS, we are polishing our PHP server side first, and making a better API design.

If you are onboard to help please let us know.

Feathub - [MongoDB Support](http://feathub.com/directus/directus/+68)
Feathub - [NodeJS API](http://feathub.com/directus/directus/+69)

**Comment by benhaynes** [comment]
Thanks for the recommendations @kamikazechaser! I agree that supporting both of those would be awesome. We have a small core team right now and are focusing on stability, the API, and Docs... but would 100% support anyone who was interested in creating a pull-request for those ports.

Thanks again!
