### ISSUE TITLE
Image info element obstructs an actions element when image source is too large to preview

### ISSUE THREAD

**Issue by skaidra-bake** [directus/directus#12459]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When choosing a big image file (physical dimensions higher than 6000px in either width or height) for an instance of a model, Directus does not display its thumbnail, instead it renders the text "Image source too large to preview". The image info (title and meta) element is placed very close to and in front of the action elements which can be accessed on hover.

This positioning interferes with clicking on the action icons, e.g. delete the image. The only way to delete the image is to move the cursor to a very specific position (a bit higher) which is not very intuitive.

I have attached a screenshot to show the problem.

<img width="753" alt="Screenshot 2022-03-29 at 12 07 17" src="https://user-images.githubusercontent.com/69679313/160615440-4e80aa1b-25db-436a-b3e1-62dd2bd38d30.png">

### To Reproduce

1. Create a data model that has an image file.
2. Create an instance of the model and choose a big image that would be too big to preview (width or height higher than 6000px)
3. Hover on the image, and try to click on any of the actions for it.

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

16.14.2

### What database are you using?

Postgres 12.10

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Heroku

**Comment by azrikahar** [comment]
Thanks for filing this issue! Although they are reported differently, #11556 and #10475 has the same underlying issue as this. We are currently tracking this over at #10475, so feel free to subscribe to it for future updates. Closing this as duplicate, but once again understandably it's not really flat out a duplicate 👍
