### ISSUE TITLE
Cannot assign LDAP user as admin

### ISSUE THREAD

**Issue by viharm** [directus/directus#12462]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

LDAP users assigned to any Directus role with administrative access revert to a normal group.

### To Reproduce

1. Install _Directus_ with a default admin user.
2. Configure LDAP authentication.
3. Login with a few LDAP users so that they appear in the users list.
4. Login with the default _Directus_ admin user (created during installation).
5. Assign one of the LDAP users to a _Directus_ role with administrative access. (let's call this the target user)
6. Log out.
7. Login with the target LDAP user (recently assigned to the administrative role).
8. Check the role for this target user. This will have moved to a regular role.

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

16.14.2 (from Docker image)

### What database are you using?

MariaDB 15.1 Distrib 10.3.31-MariaDB

### What browser are you using?

Firefox 98.0.2

### What operating system are you using?

Server: Debian 10; Client: Windows 10

### How are you deploying Directus?

Docker

**Comment by viharm** [comment]
OK, so the best practice would be to create _Directus_ roles that match the directory (AD, LDAP, etc.) groups; and then these are auto-assigned by _Directus_? Once matched, I can then manipulate permissions of these roles, right?

Will this match be case-sensitive?

**Comment by aidenfoxx** [comment]
Exactly. You should match the Directus role name to an AD group name. The match is case insensitive and based on the distinguished name of the AD group.

Once matched the user will get the permissions of whatever Directus role they are assigned to.

**Comment by viharm** [comment]
I have tried mapping _Directus_ roles to LDAP groups. However since my users are in multiple groups, it's defaulting to a normal group. Here's what's happening to me.

User 1 (I want this to be admin): `viharm`
User 2 (This should be a normal user): `testuser`

Group 1: `Normal`
memberUid: `viharm`, memberUid: `testuser`

Group 2: `Poweruser`
memberUid: `viharm`

How will _Directus_ map `viharm` user?

When the target user logs in they move to the group `Normal`.

**Comment by aidenfoxx** [comment]
Yes. So Directus only supports 1 role per user, so we kinda just have to pick a role at random. My advice would be to set up Directus specific roles in your AD and assign your users to those.

**Comment by viharm** [comment]
> Yes. So Directus only supports 1 role per user, so we kinda just have to pick a role at random. My advice would be to set up Directus specific roles in your AD and assign your users to those.

Hmm, thanks for your response. However that will only add one more group the users will be members of. Unfortunately I cannot remove them from the existing groups as other applications depend on this grouping :-(

Will there be a future change that allows multiple group memberships for directory users? Or may be allowing the admin to "help" _Directus_ select the appropariate role :-P

**Comment by aidenfoxx** [comment]
Multiple roles is on the roadmap for Directus Q2 2022, so that should solve that problem if they can implement it. https://directus.io/road-map/

But as I suggested, it's generally better to have Directus specific groups in AD so you can manage Directus access without affecting other applications.

**Comment by viharm** [comment]
> Multiple roles is on the roadmap for Directus Q2 2022, so that should solve that problem if they can implement it. https://directus.io/road-map/
> 
Awesome, thanks!

> But as I suggested, it's generally better to have Directus specific groups in AD so you can manage Directus access without affecting other applications.
>
Understood, and that's easy to do. But removing users from existing groups (based on the current state) is not possible for me; and I presume this will be the case for many use cases.

**Comment by viharm** [comment]
I would also like to point out, that I tried many solutions for a no-code app framework. Found _Directus_ and fell in love with. It's truly awesome, with incredible attention to detail. I intend to back this project soon.

**Comment by aidenfoxx** [comment]
You don't have to remove your users from existing groups! Just make sure you don't have group names in Directus that collide with and you should be guccii. 😄 

And I'm glad you appreciate the work. I'm not actually a member of the team, and actually contributed the LDAP integration for my own needs. 👍

**Comment by viharm** [comment]
> Just make sure you don't have group names in Directus that collide with AD
> 

I was thinking about this. Even if I avoid creating _Directus_ roles that match with diretory groups I don't want, there is still the problem of distinguishing users in multiple groups.

In the example above ([link](#issuecomment-1081932841)), I removed the _Directus_ role `Users-Normal`, so that the user `viharm` would be automatically assigned the `Users_PowerUser` role. This means that the user `testuser` is left with no role, so I can't login with that user. Do you think this will be addressed in the upcoming enhancements? Or am I doing this wrong?

**Comment by viharm** [comment]
@aidenfoxx, This is a very good workaround. Reading back through all the message, it is obvious you were trying to say this all along. Sorry it took me a while to get it. Thanks for your patience.

Eagerly awaiting the multi-group enhancements :-)

**Comment by aidenfoxx** [comment]
@rijkvanzanten I believe this can be closed.

**Comment by petrosmm** [comment]
> You are describing LDAP working as intended. The benefit of LDAP is that your roles are provisioned in active directory and synchronized with Directus so you don't have to manage 2 separate systems. If you want your Directus users to be admins you must assign them to a matching group in AD.
> 
> So if you have the role "Directus Admin" in Directus, your user must also be in a group called "Directus Admin" in AD to get the role.
> 
> See group configuration in the docs: https://docs.directus.io/configuration/config-options/#ldap-ldap

I wish I found this well written detail in the docs.

**Comment by rijkvanzanten** [comment]
cc @phazonoverload
