### ISSUE TITLE
Improve nested o2m scan

### ISSUE THREAD

**Issue by jeremybradbury** [directus/directus#12476]
_@rijkvanzanten: nested o2m's are currently scanned in batches as per https://github.com/directus/directus/pull/11246. We can optimize the scan performance by short-circuiting out of the batches when we've reached the required number of nested rows._

---

### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The app will page through users over and over when accessing the permissions menu. 

There is no need to constantly hit the DB for a long list of related userids while editing permissions.

This abusive behavior toward my database server and blocks the UI.

### To Reproduce

Import 2 million-ish users, add them to a role.

Then try to edit permissions for that role.

You'll notice no matter what the browser does after, the app is locked into grabbing every single user no matter how long it takes. 

There is no actual need for this data at the time, (esp without caching it instead of calling out on UI action), however it's being requested on the Roles & Permissions page and the page to edit the Role itself and then again any time you click "use custom" on any item.

### Errors Shown

Directus just keeps asking for ids 25000 at a time. taking about 1 second per page, but cascading the calls so they take more than 3 seconds by the end.

We've had several force disconnects and spikes. 

i have to restart or stop the service any time someone visits the roles so this doesn't lock up our whole data cluster, then we can't get the permission tools to work. simply because we have lots of users....

```
Mar 30 04:11:04 ip-172-31-41-164 DirectusServer[291139]: 04:11:04 🔍 [674.953ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 650000]
Mar 30 04:11:05 ip-172-31-41-164 DirectusServer[291139]: 04:11:05 🔍 [705.361ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 675000]
Mar 30 04:11:07 ip-172-31-41-164 DirectusServer[291139]: 04:11:07 🔍 [713.172ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 700000]
Mar 30 04:11:08 ip-172-31-41-164 DirectusServer[291139]: 04:11:08 🔍 [775.194ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 725000]
Mar 30 04:11:09 ip-172-31-41-164 DirectusServer[291139]: 04:11:09 🔍 [821.747ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 750000]
Mar 30 04:11:10 ip-172-31-41-164 DirectusServer[291139]: 04:11:10 🔍 [774.751ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 775000]
Mar 30 04:11:11 ip-172-31-41-164 DirectusServer[291139]: 04:11:11 🔍 [788.898ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 800000]
Mar 30 04:11:13 ip-172-31-41-164 DirectusServer[291139]: 04:11:13 🔍 [965.275ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 825000]
Mar 30 04:11:14 ip-172-31-41-164 DirectusServer[291139]: 04:11:14 🔍 [973.159ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 850000]
Mar 30 04:11:16 ip-172-31-41-164 DirectusServer[291139]: 04:11:16 🔍 [918.302ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 875000]
Mar 30 04:11:17 ip-172-31-41-164 DirectusServer[291139]: 04:11:17 🔍 [957.776ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 900000]
Mar 30 04:11:19 ip-172-31-41-164 DirectusServer[291139]: 04:11:19 🔍 [917.931ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 925000]
Mar 30 04:11:20 ip-172-31-41-164 DirectusServer[291139]: 04:11:20 🔍 [1198.283ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 950000]
Mar 30 04:11:22 ip-172-31-41-164 DirectusServer[291139]: 04:11:22 🔍 [1023.704ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 975000]
Mar 30 04:11:23 ip-172-31-41-164 DirectusServer[291139]: 04:11:23 🔍 [1103.431ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 1000000]
Mar 30 04:11:25 ip-172-31-41-164 DirectusServer[291139]: 04:11:25 🔍 [1189.824ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 1025000]
Mar 30 04:11:27 ip-172-31-41-164 DirectusServer[291139]: 04:11:27 🔍 [1088.990ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 1050000]
Mar 30 04:11:28 ip-172-31-41-164 DirectusServer[291139]: 04:11:28 🔍 [1043.602ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 1075000]
Mar 30 04:11:30 ip-172-31-41-164 DirectusServer[291139]: 04:11:30 🔍 [1319.685ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 1100000]
Mar 30 04:11:32 ip-172-31-41-164 DirectusServer[291139]: 04:11:32 🔍 [1225.002ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 1125000]
Mar 30 04:11:33 ip-172-31-41-164 DirectusServer[291139]: 04:11:33 🔍 [1340.203ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 1150000]
Mar 30 04:11:35 ip-172-31-41-164 DirectusServer[291139]: 04:11:35 🔍 [1260.870ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 1175000]
Mar 30 04:11:37 ip-172-31-41-164 DirectusServer[291139]: 04:11:37 🔍 [1347.213ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 1200000]
Mar 30 04:11:38 ip-172-31-41-164 DirectusServer[291139]: 04:11:38 🔍 [1320.452ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 1225000]
Mar 30 04:11:40 ip-172-31-41-164 DirectusServer[291139]: 04:11:40 🔍 [1447.335ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 1250000]
Mar 30 04:11:41 ip-172-31-41-164 DirectusServer[291139]: 04:11:41 🔍 [3.240ms] select "ip_access" from "directus_roles" where "id" = $1 limit $2 [1f5dd37a-598b-4706-8880-98c04b2a6743, 1]
Mar 30 04:11:41 ip-172-31-41-164 DirectusServer[291139]: 04:11:41 🔍 [6.094ms] select "ip_access" from "directus_roles" where "id" = $1 limit $2 [1f5dd37a-598b-4706-8880-98c04b2a6743, 1]
Mar 30 04:11:43 ip-172-31-41-164 DirectusServer[291139]: 04:11:43 🔍 [1725.072ms] select "directus_users"."id", "directus_users"."first_name", "directus_users"."last_name", "directus_users"."email", "directus_users"."avatar" from "directus_users" order by "directus_users"."last_access" asc limit $1 [25]
Mar 30 04:11:43 ip-172-31-41-164 DirectusServer[291139]: 04:11:43 🔍 [6.570ms] select "directus_files"."modified_on", "directus_files"."type", "directus_files"."filename_disk", "directus_files"."storage", "directus_files"."id" from "directus_files" where "directus_files"."id" in ($1, $2) limit $3 [some--uuid, some-uuid, 100]
Mar 30 04:11:43 ip-172-31-41-164 DirectusServer[291139]: 04:11:43 🔍 [556.449ms] select count(*) as "count" from "directus_users" []
Mar 30 04:11:43 ip-172-31-41-164 DirectusServer[291139]: 04:11:43 🔍 [537.660ms] select count(*) as "count" from "directus_users" limit $1 [1]
Mar 30 04:11:44 ip-172-31-41-164 DirectusServer[291139]: 04:11:44 🔍 [2174.696ms] select "directus_users"."id", "directus_users"."first_name", "directus_users"."last_name", "directus_users"."email", "directus_users"."avatar" from "directus_users" order by "directus_users"."last_access" asc limit $1 [25]
Mar 30 04:11:44 ip-172-31-41-164 DirectusServer[291139]: 04:11:44 🔍 [3.851ms] select "directus_files"."modified_on", "directus_files"."type", "directus_files"."filename_disk", "directus_files"."storage", "directus_files"."id" from "directus_files" where "directus_files"."id" in ($1, $2) limit $3 [some-uuid, some-uuid, 100]
Mar 30 04:11:44 ip-172-31-41-164 DirectusServer[291139]: 04:11:44 🔍 [524.035ms] select count(*) as "count" from "directus_users" limit $1 [1]
Mar 30 04:11:44 ip-172-31-41-164 DirectusServer[291139]: 04:11:44 🔍 [552.711ms] select count(*) as "count" from "directus_users" []
Mar 30 04:11:44 ip-172-31-41-164 DirectusServer[291139]: 04:11:44 ✨ request completed GET 200 /users?limit=25&fields[]=id&fields[]=avatar.modified_on&fields[]=avatar.type&fields[]=avatar.filename_disk&fields[]=avatar.storage&fields[]=avatar.id&fields[]=first_name&fields[]=last_name&fields[]=email&sort[]=last_access&page=1&filter=%7B%7D&meta[]=filter_count&meta[]=total_count 2.8s
Mar 30 04:11:44 ip-172-31-41-164 DirectusServer[291139]: 04:11:44 🔍 [3163.682ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 1275000]
Mar 30 04:11:46 ip-172-31-41-164 DirectusServer[291139]: 04:11:46 🔍 [1346.805ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 1300000]
Mar 30 04:11:48 ip-172-31-41-164 DirectusServer[291139]: 04:11:48 🔍 [1566.582ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 1325000]
Mar 30 04:11:50 ip-172-31-41-164 DirectusServer[291139]: 04:11:50 🔍 [1690.205ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 1350000]
Mar 30 04:11:52 ip-172-31-41-164 DirectusServer[291139]: 04:11:52 🔍 [1401.189ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 1375000]
Mar 30 04:11:54 ip-172-31-41-164 DirectusServer[291139]: 04:11:54 🔍 [1492.785ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 1400000]
Mar 30 04:11:56 ip-172-31-41-164 DirectusServer[291139]: 04:11:56 🔍 [1470.385ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 142500

....

Mar 30 04:13:59 ip-172-31-41-164 DirectusServer[291139]: 04:13:59 🔍 [2539.321ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 2600000]
Mar 30 04:14:03 ip-172-31-41-164 DirectusServer[291139]: 04:14:03 🔍 [3261.645ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 2625000]
Mar 30 04:14:07 ip-172-31-41-164 DirectusServer[291139]: 04:14:07 🔍 [2831.249ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 2650000]
Mar 30 04:14:10 ip-172-31-41-164 DirectusServer[291139]: 04:14:10 🔍 [2813.961ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 2675000]
Mar 30 04:14:13 ip-172-31-41-164 DirectusServer[291139]: 04:14:13 🔍 [2950.452ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 2700000]
Mar 30 04:14:17 ip-172-31-41-164 DirectusServer[291139]: 04:14:17 🔍 [2809.605ms] select "directus_users"."role", "directus_users"."id" from "directus_users" where "directus_users"."role" in ($1) order by "directus_users"."id" asc limit $2 offset $3 [some-role-uuid, 25000, 2725000]
```

for me this locks the UI and doesn't allow any permissions edits.

Needless to say, our DB service provider is not very happy with this and will likely have a massive bill due to interference/downtime this "feature" caused for other tenants... not to mention our own clients.

what if i actually had throttling on? the app would throttle itself?

when it shows the error in "use custom" tab i used the copy error button:
```
"<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n"
```

FWIW: nice work on creating some db load/pressure testing

### What version of Directus are you using?

v9.6.0

### What version of Node.js are you using?

14.19.0

### What database are you using?

Postgres 10

### What browser are you using?

Chrome, Brave & Firefox 

### What operating system are you using?

Ubuntu 20.04

### How are you deploying Directus?

systemd service

**Comment by jeremybradbury** [comment]
If you need it for reproduction... I restored faker js after the creator forcepushed the repo. 

I don't have the commit history but I have the last working version.

https://www.npmjs.com/package/@jeremybradbury/faker

**Comment by jeremybradbury** [comment]
Just want to bump this one more time.

My only workaround, to be able to edit roles and permissions was to delete most of my users.

this is something i won't be able to do in production as a temporary fix. 

we're stuck using 2 instances with 2 databases one missing users, but everything else synced. then sync back our permissions table.

this is not fun to setup or use.

**Comment by jeremybradbury** [comment]
@rijkvanzanten in this case, there is no need to scan the users table at all.

Why does it need to happen? 

Why does it happen?

Why are we not able to stop this process, even when a user navigates away or the server sends a request timeout?

this is def a bug... not just an "improvement" 

as it entirely prevents use of the roles & permissions and impacts other services using the same database, this would be only with our existing users, and they will continue to grow.

**Comment by benhaynes** [comment]
Hey @jeremybradbury — we don't typically see _thread bumping_ just hours after the initial post... so I just want to quickly set some expectations.

While we recognize that an issue could be a show-stopper for an individual user, as maintainers, we must triage/work through a broader lens. We're also a small OSS team with limited resources to review, respond to, and resolve issues that arrive... and often have to prioritize our paying customer needs, which can delay OSS work.

Also, we have an 80/20 rule that applies to features and fixes. And while I have not gone through all of the above details you provided (I'm not an engineer), I can say that adding "2 million-ish users" to a role (or Directus, in General) is not a use-case we typically test or feel is common. This is likely why this is being considered an `improvement` instead of a bug. 

All that said, we welcome Pull Requests from our community, and I would recommend that, or sponsoring the fix, as the best course of action if you need this resolved quickly. I also want to ensure this dialog stays constructive and inline with our [Code of Conduct](https://github.com/directus/directus/blob/main/code_of_conduct.md). ❤️

**Comment by jeremybradbury** [comment]
> I can say that adding "2 million-ish users" to a role (or Directus, in General) is not a use-case we typically test or feel is common.

@benhaynes so If I am hearing you correctly you're telling the 80% they better not plan to grow their way into the 20% on this?

That by making the limit set to 25000, it shouldn't impact anyone in the 80%?

If that's the approach you want to take, it's discouraging users from using your platform because you won't support it's upper limits.

I am helping Directus OSS spot issues and fix them as much as I possibly can, but Dev Relations tells me that their features aren't intended for many users.

I can't make a PR for every "20%" problem because I'm your largest user (or close to it).

Instead, I would encourage collaboration and feedback from (one of your) your largest user/s.

The pattern being used here is going to break and be malicious to anyone with more than 100k users, sending 5 or more calls to rapidly scan a table that's not used in this context.

But you've already pushed this problem down the road many times, without actually fixing it. You fix it for the 80, but leave the 20 completely blocked acting like malware.

You can throw your hands up and say "that's too many users to matter to my team". 

You can complain that I complain too much.

Or we can try to work together to solve some massive bugs quickly.

Tell me how else I can help other than filing issues and suggestions for broken / missing items.

I honestly can't even get a simple PR accepted or any issue addressed. sometimes they are closed and ignored until others report related issues. 

I am glad to help, but I have limited time. and telling me to go away isn't very helpful for me or the rest of the community.

**Comment by benhaynes** [comment]
> @benhaynes so If I am hearing you correctly you're telling the 80% they better not plan to grow their way into the 20% on this?

No, you are not hearing me correctly. I'm explaining that our 80/20 rule is also used in triaging prioritization. This is not a 20% feature in my eyes (more likely, less than 1%). I've been working on this platform for nearly 20 years and have yet to hear of any use-case even approaching 100K users, let alone millions.

You mentioned being "our largest user" several times. By adding millions of users to the App I understand that's how you view it, however, our Fortune 100 users and paying Enterprise customers are intrinsically "larger" and more strategic to _us_ (to keep payroll running), and therefore demand a higher priority.

> "I can't make a PR for every "20%" problem because I'm your largest user (or close to it)."
> "I am glad to help, but I have limited time."

Exactly, and we the Core Team are far smaller than our community of contributors... and are in the same boat.

This ticket was not closed, meaning, we do intend to resolve it. However, it is low on our _internal_ priority list. I am not an engineer and am not here to assess your recommendations, PRs, or requests. As I said originally, I'm just here to set expectations around internal prioritization so you don't get frustrated by us not responding within hours/days/weeks. We're working within the bounds of our limited resources, and I'm trying to help you understand and respect that.

_When everything is a priority, nothing is a priority._

**Comment by jeremybradbury** [comment]
> When everything is a priority, nothing is a priority.

yes, i guess even malicious behavior reserved for humans who add a lot of users to your platform is not a priority, because it impacts so few.

just know that this app is about to be flagged as malware in many reporting systems because of this willful negligence & deprioritization of malicious issues.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-261](https://linear.app/directus/issue/ENG-261/improve-nested-o2m-scan)

**Comment by rijkvanzanten** [comment]
Closing this in favor of a bigger data querying optimization overhaul
