### ISSUE TITLE
Add query filter validation with permissions not working very well

### ISSUE THREAD

**Issue by zimmersi** [directus/directus#12479]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

https://github.com/directus/directus/blob/6e8ab78c0eed83ba82c294ed0109178b05dadab7/api/src/services/authorization.ts#L167

This validates the filter only based on one permission. Altough I can at least create 5 permissions per collection within directus.
In my case it chooses always the 'create' permission which breaks all readByQuery API calls, because the create permission is more restrictive than the read permission.

What is the exact use case for this? Some kind of data loss?

I guess there are several solutions based on the exact use case. But in my opinion the create and delete permissions are the worst selection to validate filter permissions.

### To Reproduce

It is not that easy to reproduce this issue as the permission is more or less randomly selected.
1. create a collection with fields a, b, c, d, e and configure the permissions as follows
2. set allowed fields on create to a, b
3. set allowed fields on read to a, b, c, d, e
4. try to query the API with a filter on e

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

16.14.2

### What database are you using?

MariaDB 10.8.2

### What browser are you using?

Chromium, Firefox

### What operating system are you using?

Win10

### How are you deploying Directus?

locally

**Comment by zimmersi** [comment]
#12190
@licitdev

**Comment by licitdev** [comment]
@zimmersi Thank you for your report. It should only be reading permissions for `read` as it's validating the filter on `read` permissions. Updating it into https://github.com/directus/directus/pull/12426 now.

**Comment by zimmersi** [comment]
hi @licitdev 
wow, lightning fast reaction ;)
okay, great! this should fix this issue.

**Comment by jeverduzco** [comment]
Following up on what I mentioned in #12497 I realized that I now must give permissions to all collections involved in the query.

With the permissions configured as in the following image, the query using the SDK and the API works.

![image](https://user-images.githubusercontent.com/3856266/161113274-f78ddfe6-64c1-4dd2-8a57-7672ac94474e.png)

In the case of GraphQL, it does not work :( the result is the error shown in: #12497

**Comment by licitdev** [comment]
@jeverduzco The issue that you are facing will be fixed in #12426. You will need to remove permissions for the `languages` table for filter: `languages_id: { _eq: "es-ES" }` to work in GraphQL after the PR is merged. Thank you.
