### ISSUE TITLE
Permissions in deep queries with filters, broken in v9.7.1

### ISSUE THREAD

**Issue by jeverduzco** [directus/directus#12497]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I am developing a platform using Directus as Backend and in version 9.7.0 I could make the following query without any problem:

`http://localhost:8055/graphql`

```graphql
query {
	articles {
        id,
        date_created,
	translations(filter: { languages_id: { _eq: "es-ES" }, status: { _eq: "published" } }) {
	   title,
           cover,
           slug
	}
    }
}
```

The result of this was as expected:

```json
{
    "data": {
        "articles": [
            {
                "id": "f887bf47-19d3-4db0-a05f-bdaa72510853",
                "date_created": "2022-03-30T19:57:08",
                "translations": [
                    {
                        "title": "Este es un artículo de pruebas para el desarrollo",
                        "cover": "e47adca9-ffd0-4a7a-b66a-ebe131387d94",
                        "slug": "este-es-un-articulo-de-pruebas-para-el-desarrollo"
                    }
                ]
            }
        ]
    }
}
```

When upgrading to version 9.7.1 the result of the query is as follows.

```json
{
    "errors": [
        {
            "message": "You don't have permission to access this.",
            "locations": [
                {
                    "line": 2,
                    "column": 2
                }
            ],
            "path": [
                "articles"
            ]
        }
    ],
    "data": {
        "articles": null
    }
}
```

Permissions are the same, with full reading for the public role.

![image](https://user-images.githubusercontent.com/3856266/160948145-20308a48-04a1-4d90-962a-7fcbab6f9688.png)

### To Reproduce

Call translations of a data model using a filter.

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

16.13.2

### What database are you using?

Postgres 13.4

### What browser are you using?

Edge Chromium

### What operating system are you using?

Ubuntu

### How are you deploying Directus?

Docker on Azure

**Comment by jeverduzco** [comment]
Update 2: if I query the SDK with an administrator token in version 9.7.1 the result is as expected:

![image](https://user-images.githubusercontent.com/3856266/160975971-e4498fe2-a9a2-468d-8be2-659aba129f9d.png)

if I query with an administrator token but with GraphQL the result is a different error:

```json
{
    "errors": [
        {
            "message": "GraphQL validation error.",
            "extensions": {
                "code": "GRAPHQL_VALIDATION_EXCEPTION",
                "graphqlErrors": [
                    {
                        "message": "Field \"_eq\" is not defined by type \"languages_filter\". Did you mean \"_or\"?",
                        "locations": [
                            {
                                "line": 5,
                                "column": 42
                            }
                        ]
                    },
                    {
                        "message": "Field \"cover\" of type \"directus_files\" must have a selection of subfields. Did you mean \"cover { ... }\"?",
                        "locations": [
                            {
                                "line": 7,
                                "column": 13
                            }
                        ]
                    }
                ]
            }
        }
    ]
}

```

I can't get it to work as I expect... am I doing something wrong?

**Comment by azrikahar** [comment]
Thanks for the updates! I believe this is related to #12479, as it also started happening in `v9.7.1` where the permissions are not working as expected which should explain why using an admin token worked as expected. I'll close this in favor of tracking this issue over there.
