### ISSUE TITLE
Search "In" Filter with Tags

### ISSUE THREAD

**Issue by st11x** [directus/directus#12496]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I am having trouble with the search "_in" or "_nin" filters. I have tried with the tags field on fields and also created JSON and CSV tags fields on a collection asset.

In this example query , two other images with empty tags came up only because I added some tags to them and then removed them. Those that never had tags would not show up at all. The one that I don't want to show is in the results.

![image](https://user-images.githubusercontent.com/7398499/160945122-396ef935-4bb6-464e-a748-7a981f95cc36.png)

### To Reproduce

Add two tags to an asset and query for it using any one tag or both tags.

I think it will only work as intended if the asset has only 1 tag and that field is a JSON tag field. 

### What version of Directus are you using?

9.7.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

Sqlite 

### What browser are you using?

Edge

### What operating system are you using?

Windows 10

### How are you deploying Directus?

Docker

**Comment by st11x** [comment]
Don't know if it is just Sqlite, but I opened the database and saw that the column is populated like this.

![image](https://user-images.githubusercontent.com/7398499/160948626-486b7c8f-7977-40ec-a53b-fbfa2f651c6b.png)

I intentionally misspelled the field name to see the query generated and that in-clause would never work on that field.

![image](https://user-images.githubusercontent.com/7398499/160948728-a01d4f4c-e8d9-4e96-a2f6-1d1c01a3cb22.png)

The contains operator works as it uses a LIKE SQL query but the order of tags must be the same, and you have to quote the search value exactly like how it appears in the database.

```
                  "tags": {
                      "_contains": "[\"report\",\"bar\"]"
                    } 
```

**Comment by nazariydj** [comment]
my solution is using **JSON** field with **_contains** operator in conjuction with **_and**, **_or** logical operators. 
every sigle tag can be delimited with double quote.
for example: 
`{
  "_and": [
    {"tags": {"_contains": "\"report\""}},
    {"tags": {"_contains": "\"bar\""}}
  ]
}`

**Comment by rijkvanzanten** [comment]
Directus currently isn't capable of searching in the stored value of JSON fields, see https://github.com/directus/directus/discussions/7277 for the open feature request about that 👍🏻
