### ISSUE TITLE
Still can't delete an M2O field when using MariaDB or MySQL

### ISSUE THREAD

**Issue by BenMemescape** [directus/directus#12495]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

M2O field cannot be deleted if using MariaDB/MySQL. 
Apologies if opening a new issue for this is not the right way to go. This issue has been raised previously as #11510 - it was marked as closed and solved in 9.7.0 but as of 9.7.1 it is still happening if you use either MariaDB or MySQL as the backend. It does not happen for Postgres. 

### To Reproduce

1. I am using the latest docker image (9.7.1)
2. Log in to the admin
3. Create a collection.
4. Add an M2O field.
5. Attempt to delete the M2O field.

### Errors Shown

[INTERNAL_SERVER_ERROR] alter table `test` drop `m2o` - ER_DROP_INDEX_FK: Cannot drop index 'test_m2o_foreign': needed in a foreign key constraint

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

16.14.2

### What database are you using?

mariadb:latest, mysql:5

### What browser are you using?

Firefox Developer Edition

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
> Apologies if opening a new issue for this is not the right way to go. 

It is the right way, and thanks for narrowing it down as well! However since there's an existing issue #12478[^1], I'll close this in favor of that. 👍 

[^1]: An image interface is also a m2o field to `directus_files` under the hood. Will update the title accordingly to be more accurate.
