### ISSUE TITLE
AUTH_PROVIDERS config option not working properly

### ISSUE THREAD

**Issue by NickSettler** [directus/directus#12519]
### Preflight Checklist

- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.
- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

I have two auth providers. They are stored in docker-compose.yml file in environment section. It looks like this

```bash
AUTH_PROVIDERS: 'local,google'

AUTH_LOCAL_DRIVER: 'local'

AUTH_GOOGLE_DRIVER: 'openid'
AUTH_GOOGLE_CLIENT_ID: '####'
AUTH_GOOGLE_CLIENT_SECRET: '####'
AUTH_GOOGLE_ISSUER_URL: "https://accounts.google.com"
AUTH_GOOGLE_IDENTIFIER_KEY: "email"
AUTH_GOOGLE_ICON: "google"
```

But when I'm trying to start the container with directus I'm getting error, that the AUTH_PROVIDERS variable cannot be splitted

### To Reproduce

1) Create docker-compose.yml with directus image.
2) Specify multiple auth providers (at least 2)
3) Start the container

### Errors Shown

```bash
directus    | 13:12:21 ? Initializing bootstrap...
directus    | 13:12:21 ? Database already initialized, skipping install
directus    | 13:12:21 ? Running migrations...
directus    | 13:12:21 ? Done
directus    | npm notice 
directus    | npm notice New minor version of npm available! 8.5.0 -> 8.6.0
directus    | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.6.0>
directus    | npm notice Run `npm install -g npm@8.6.0` to update!
directus    | npm notice 
directus    | 13:12:30 ? Server started at http://0.0.0.0:8055
directus    | /directus/node_modules/directus/dist/utils/track.js:63
directus    |             providers: env_1.default.AUTH_PROVIDERS.split(',')
directus    |                                                     ^
directus    | 
directus    | TypeError: env_1.default.AUTH_PROVIDERS.split is not a function
directus    |     at getEnvInfo (/directus/node_modules/directus/dist/utils/track.js:63:53)
directus    |     at async track (/directus/node_modules/directus/dist/utils/track.js:17:22)
```

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

builtin

### What database are you using?

Postgres 12

### What browser are you using?

-

### What operating system are you using?

Ubuntu

### How are you deploying Directus?

docker-compose

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/directus/pull/12370
