### ISSUE TITLE
Login error message : help  Wrong username/password

### ISSUE THREAD

**Issue by YounessTayer** [directus/directus#1251]
Hi;

The installation is well hapened, but the login is impossible( I have one user that I created from the phpmyadmin panel, I encrypted the pasword with SHA1. I still receiving this error message :
_Wrong username/password_.

Any idea to resolve this issue will be very appreciated.

Thanks,

**Comment by WellingGuzman** [comment]
Hello @YounessTayer What exactly are you trying? how are you creating the user?

Have you tried this: https://github.com/directus/docs/blob/master/04-developer/06-schema-guide.md#manually-setting-passwords

Perhaps this:

```bash
$ php bin/directus user:password -e "<your-email>" -p "<new-password>"
```

Let me know if that works for you.

**Comment by benhaynes** [comment]
Hey @YounessTayer – thanks for reporting this! Any update on this user creation issue? It seems like you might have encrypted the user's password incorrectly, but we want to make sure your issue is resolved.

Let us know! :)

**Comment by WellingGuzman** [comment]
Hello @YounessTayer did you manage to solve the issue?

**Comment by WellingGuzman** [comment]
Hey @YounessTayer I assumed you solved the the issue, otherwise we will open the ticket.
