### ISSUE TITLE
Add-, Choose-, Remove Button is not shown when editing a M2M relationship

### ISSUE THREAD

**Issue by niseku** [directus/directus#1252]
## Version Info
  - Directus version and branch: v.6.3.1
  - PHP version: 7
  - MySQL version: 5.6
  - Web server: Apache

## Expected Behavior
There should be a Button for adding, removing or choosing a M2M relation.

## Actual Behavior
Just a Table with selected Items is shown (The Field Images is a M2M Relation):
![unbenannt](https://cloud.githubusercontent.com/assets/16119608/18278418/568fb77c-7452-11e6-91c5-acc6bfb21ef3.PNG)

## Steps to Reproduce
 1. Create a table with a M2M Relation
 2. Create a Entry for this table and try to edit the M2M field

## Logs or Screenshots
The Buttons are selectet in the settings:
![unbenannt](https://cloud.githubusercontent.com/assets/16119608/18278547/d05b1b0a-7452-11e6-8512-b3954215cd89.PNG)

**Comment by benhaynes** [comment]
Thanks @niseku! We're looking into this now. Can you go back into the UI options and confirm those checkboxes are still checked?

**Comment by WellingGuzman** [comment]
Thanks @niseku, I pushed a patch to the master branch that should fix this problem (7f4937b) let us know if that worked for you.
