### ISSUE TITLE
Weird request URL parsing when using SDK's files readMany method

### ISSUE THREAD

**Issue by dataexcess** [directus/directus#12536]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I just updated to the latest version of Directus SDK.

the following code in my client forms a weird formatted URL. This code:

 ```
   static async getSoundURL(soundfile) {
        const sound = await API.files
            .readMany({
                filter: {
                    filename_download: {
                        '_eq': soundfile,
                    }
                }
            })
            .catch((err) => {
                console.error(err);
            });

        let url = ASSETS + sound.data[0].id
        // console.log('loaded soundfile at url: ' + url)
        return url
    }
```
Makes the following network call (which it cannot read due to incorrect formatting?)

` GET https://staging.subneu.live/api/files?filter=%7B%22id%22:%7B%22_in%22:%7B%2…ilename_download%22:%7B%22_eq%22:%22subneu_1.mp3%22%7D%7D%7D%7D%7D&sort=id 500 (Internal Server Error)`

This error did not appear in version 9.0.0.

### To Reproduce

Using the readMany() method like in the description...

### Errors Shown

GET https://staging.subneu.live/api/files?filter=%7B%22id%22:%7B%22_in%22:%7B%22filter%22:%7B%22filename_download%22:%7B%22_eq%22:%22subneu_1.mp3%22%7D%7D%7D%7D%7D&sort=id 500 (Internal Server Error)

Network.js?32ba:56 Error: An unexpected error occurred.
    at Transport.request (sdk.bundler.js?57b0:630:1)
    at async Transport.get (sdk.bundler.js?57b0:644:1)
    at async FilesHandler.readMany (sdk.bundler.js?57b0:26:1)

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

v15.5.1

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying Directus?

nginx on ubuntu

**Comment by dataexcess** [comment]
Fixed by changing the code to 

```
        const sound = await API.files.readByQuery({
            filter: {
                filename_download: {
                    '_eq': soundfile,
                }
            }
        });
```

**Comment by azrikahar** [comment]
This was also noted and highlighted in `v9.5.2`'s release note: https://github.com/directus/directus/releases/tag/v9.5.2 👍

**Comment by dataexcess** [comment]
> This was also noted and highlighted in `v9.5.2`'s release note: https://github.com/directus/directus/releases/tag/v9.5.2 👍

Ooooh I see. Good! The API naming makes more sense now. 👍
