### ISSUE TITLE
Cannot add/modify field on table (PDO errors:42000 - 1064 - You have an error in your SQL syntax;) 

### ISSUE THREAD

**Issue by neosign** [directus/directus#1253]
## Version Info
  - Directus version and branch: 6.3.2 (master)
  - PHP version: 7.0 and 5.6
  - MySQL version:  5.5.42 
  - Web server: (Ex. Apache, nginx or IIS?)  : Apache 2.4 (MAMP)
  - OS name and version:  MacOS10.10.5 (MAMP)

## Expected Behavior
Add field in settings schema

## Actual Behavior
Error msg box shows
Server Error 
Statement could not be executed (42000 - 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1)
## Steps to Reproduce
 1. Go to Settings > Tables & Inputs 
 2. Add table (Passed)
 3. Select table to add field
 4. Click add new fields
     4.1 add Filed Name: first_col
     4.2.select UI : Textinput
     4.3.select data type: varchar
     4.4.input length:100 (default)
5. Click save button 

## Logs or Screenshots
`{
  "code":0,
  "class":"Zend\\Db\\Adapter\\Exception\\InvalidQueryException",
  "message":"Statement could not be executed (42000 - 1064 - You have an error in your SQL syntax; check
 the manual that corresponds to your MySQL server version for the right syntax to use near '' at line
 1)",
  "file":"\/Users\/macos\/Documents\/AppServ\/www\/directus\/vendor\/zendframework\/zend-db\/src\/Adapter
\/Driver\/Pdo\/Statement.php",
  "line":245,
  "trace":[
    {
      "file":"\/Users\/macos\/Documents\/AppServ\/www\/directus\/api\/core\/Directus\/Db\/TableGateway
\/AclAwareTableGateway.php",
      "line":435,
      "function":"execute",
      "class":"Zend\\Db\\Adapter\\Driver\\Pdo\\Statement",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/Users\/macos\/Documents\/AppServ\/www\/directus\/api\/core\/Directus\/Db\/TableGateway
\/AclAwareTableGateway.php",
      "line":399,
      "function":"addTableColumn",
      "class":"Directus\\Db\\TableGateway\\AclAwareTableGateway",
      "type":"->",
      "args":[
        "testsd",
        {
          "data_type":"VARCHAR",
          "ui":"textinput",
          "char_length":100,
          "column_name":"testcol",
          "comment":""
        }
      ]
    },
    {
      "file":"\/Users\/macos\/Documents\/AppServ\/www\/directus\/api\/api.php",
      "line":843,
      "function":"addColumn",
      "class":"Directus\\Db\\TableGateway\\AclAwareTableGateway",
      "type":"->",
      "args":[
        "testsd",
        {
          "data_type":"VARCHAR",
          "ui":"textinput",
          "char_length":100,
          "column_name":"testcol",
          "comment":""
        }
      ]
    },
    {
      "function":"{closure}",
      "args":[
        "testsd"
      ]
    },
    {
      "file":"\/Users\/macos\/Documents\/AppServ\/www\/directus\/vendor\/slim\/slim\/Slim\/Route.php"
,
      "line":436,
      "function":"call_user_func_array",
      "args":[
        {
          
        },
        [
          "testsd"
        ]
      ]
    },
    {
      "file":"\/Users\/macos\/Documents\/AppServ\/www\/directus\/vendor\/slim\/slim\/Slim\/Slim.php"
,
      "line":1305,
      "function":"dispatch",
      "class":"Slim\\Route",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/Users\/macos\/Documents\/AppServ\/www\/directus\/vendor\/slim\/slim\/Slim\/Middleware
\/Flash.php",
      "line":85,
      "function":"call",
      "class":"Slim\\Slim",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/Users\/macos\/Documents\/AppServ\/www\/directus\/vendor\/slim\/slim\/Slim\/Middleware
\/MethodOverride.php",
      "line":92,
      "function":"call",
      "class":"Slim\\Middleware\\Flash",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/Users\/macos\/Documents\/AppServ\/www\/directus\/vendor\/slim\/slim\/Slim\/Slim.php"
,
      "line":1254,
      "function":"call",
      "class":"Slim\\Middleware\\MethodOverride",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/Users\/macos\/Documents\/AppServ\/www\/directus\/api\/api.php",
      "line":1659,
      "function":"run",
      "class":"Slim\\Slim",
      "type":"->",
      "args":[
        
      ]
    }
  ],
  "traceAsString":"#0 \/Users\/macos\/Documents\/AppServ\/www\/directus\/api\/core\/Directus\/Db\/TableGateway
\/AclAwareTableGateway.php(435): Zend\\Db\\Adapter\\Driver\\Pdo\\Statement->execute()\n#1 \/Users\/macos
\/Documents\/AppServ\/www\/directus\/api\/core\/Directus\/Db\/TableGateway\/AclAwareTableGateway.php
(399): Directus\\Db\\TableGateway\\AclAwareTableGateway->addTableColumn('testsd', Array)\n#2 \/Users
\/macos\/Documents\/AppServ\/www\/directus\/api\/api.php(843): Directus\\Db\\TableGateway\\AclAwareTableGateway-
>addColumn('testsd', Array)\n#3 [internal function]: {closure}('testsd')\n#4 \/Users\/macos\/Documents
\/AppServ\/www\/directus\/vendor\/slim\/slim\/Slim\/Route.php(436): call_user_func_array(Object(Closure
), Array)\n#5 \/Users\/macos\/Documents\/AppServ\/www\/directus\/vendor\/slim\/slim\/Slim\/Slim.php
(1305): Slim\\Route->dispatch()\n#6 \/Users\/macos\/Documents\/AppServ\/www\/directus\/vendor\/slim
\/slim\/Slim\/Middleware\/Flash.php(85): Slim\\Slim->call()\n#7 \/Users\/macos\/Documents\/AppServ
\/www\/directus\/vendor\/slim\/slim\/Slim\/Middleware\/MethodOverride.php(92): Slim\\Middleware\\Flash-
>call()\n#8 \/Users\/macos\/Documents\/AppServ\/www\/directus\/vendor\/slim\/slim\/Slim\/Slim.php(1254
): Slim\\Middleware\\MethodOverride->call()\n#9 \/Users\/macos\/Documents\/AppServ\/www\/directus\
/api\/api.php(1659): Slim\\Slim->run()\n#10 {main}"
}`

![screen shot 2559-09-08 at 1 12 56 pm](https://cloud.githubusercontent.com/assets/4457571/18338890/3b6ef730-75c6-11e6-92bd-3b30eef04d34.png)

**Comment by neosign** [comment]
After spent time debugging, I found that problem is on AclAwareTableGateway.php following the picture.
![screen shot 2559-09-08 at 5 31 00 pm](https://cloud.githubusercontent.com/assets/4457571/18346425/3e32e52a-75ea-11e6-9cdb-414efd52e93a.png)

**Comment by benhaynes** [comment]
Good find @neosign! We're looking into this now... though it looks like your proposed fix is the way to go!

Thank you very much for reporting this and identifying a solution – very helpful!
