### ISSUE TITLE
Related Assets Lost When Adding New Relationship

### ISSUE THREAD

**Issue by st11x** [directus/directus#12551]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The issue is similar to https://github.com/directus/directus/issues/9461 that is already marked fixed closed, but I am still getting this problem. I created this very small example to demonstrate this. 

### To Reproduce

Created this simple collection with a relationship to a Block collection

![image](https://user-images.githubusercontent.com/7398499/161448678-615f5c70-ff54-423b-ae95-6a3ccb297ff3.png)

So the content looks just like that.

![image](https://user-images.githubusercontent.com/7398499/161448722-17cbf9d1-0eb0-4601-92f6-de66dea1d2c9.png)

There is a sort field in the junction table to maintain the order. Don't think this is relevant but I thought I should mention.

If I now add a new relationship field to the Page collection, the block relationships become empty. Adding a simple text field is fine. 

### What version of Directus are you using?

9.7.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

Sqllite

### What browser are you using?

Edge

### What operating system are you using?

Windows 10

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Seems like this is the same underlying SQLite issue as #10842, where when we add a new relationship on the Page collection, all references to it gets nulled.

Before adding new relationship:

![DB_Browser_for_SQLite_yiC6G9yobk](https://user-images.githubusercontent.com/42867097/161464364-79cbb165-54ac-4195-aad9-047d91be8cbd.png)

After adding new relationship:

![DB_Browser_for_SQLite_xux6FGEky7](https://user-images.githubusercontent.com/42867097/161464376-04086daf-d513-43ec-93a1-e5f495dfa2e3.png)

We'll close this in favor of tracking it over that same issue 👍
