### ISSUE TITLE
"Create New Item" on table which has relationship field not working 

### ISSUE THREAD

**Issue by neosign** [directus/directus#1256]
## Version Info
 - Directus version and branch: 6.3.2 (master)
 - PHP version: 7.0 and 5.6
 - MySQL version: 5.5.42
 - Web server: (Ex. Apache, nginx or IIS?) : Apache 2.4 (MAMP)
 - OS name and version: MacOS10.10.5 (MAMP)

## Expected Behavior
"Create New Item" table which has relationship  must show input form.

## Actual Behavior
![bug2](https://cloud.githubusercontent.com/assets/4457571/18375507/16e061e0-7681-11e6-8cbf-8c17db7e507a.png)

## Steps to Reproduce
- 1. Go to settings > Tables & Inputs
- 2. Modify table by adding relationship Many to One field and Save.
- 3. Go to the Tables menu > Select the table (from step#2) which has Many To One field > Create New Item

## Logs or Screenshots
`Error
Error: Uncaught Error: You must pass a string or Handlebars AST to Handlebars.compile. You passed undefined File: http://localhost/directus/assets/js/libs/handlebars.js?bust=cc073d4d6d75f8d0849f4f6d28e894b0 Line:2152`

#Error from Firebug Console from "handlebars.js"
  Error: You must pass a string or Handlebars AST to Handlebars.compile. You passed undefined
  var tmp = Error.prototype.constructor.apply(this, arguments);

**Comment by benhaynes** [comment]
Thank you @neosign! Always some sneaky bugs after a big release. We're looking into this now and will push a fix asap.

**Comment by WellingGuzman** [comment]
Thanks again @neosign , I could replicate the issue and push a patch, hoping this would solve your problem as well.
