### ISSUE TITLE
Filter format for REST API possibly not compatible with OpenAPI-Spec, resulting in INTERNAL ERROR

### ISSUE THREAD

**Issue by eidenschink** [directus/directus#12561]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

According to the [Filter documentation API](https://docs.directus.io/reference/query/#filter) a filter is built like

`?filter[first_name][_eq]=Rijk`

When fetching the OAS from the `/server/specs/oas` endpoint and working with it in swagger-ui e.g. the **filter** fields are defined with the _query_ parameter location object:

`query - Parameters that are appended to the URL. For example, in /items?id=###, the query parameter is id.
 `

So it seems with the current PHP-like argument format it is not possible to create the correct API expected argument from the OAS spec.

Currently the final result would become (using the example above):

`?filter=%5Bfirst_name%5D%5B_eq%5D%3DRijk` (wrong) instead of
`?filter%5Bfirst_name%5D%5B_eq%5D=Rijk` (correct - in the sense the endpoint expects it)

When calling the endpoint Directus does not resolve the arguments correctly and the underlying SELECT statement uses `_eq` in this example as a table name and results into a HTTP status code 500 internal error.

### To Reproduce

- Fetch OAS-JSON from `/server/specs/oas` endpoint and use it swagger-ui.
- In any collection edit a LIST ITEMS form and apply a filter statement suitable for your collection.
- Submit

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

v14.19.1

### What database are you using?

postgresql-12

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

DigitalOcean Marketplace

**Comment by rijkvanzanten** [comment]
> So it seems with the current PHP-like argument format it is not possible to create the correct API expected argument from the OAS spec.

Yup! This has been an ongoing discussion on the OpenAPI spec GitHub repo for years, without any resolution unfortunately (https://github.com/OAI/OpenAPI-Specification/issues/1706). 

The Directus API also supports json as the input for the query parameters, so `?filter[abc][_eq]=xyz` can also be written as `?filter={"abc":{"_eq":"xyz"}}`. That should in turn allow for using the filters from Swagger's UI as well. Lemme know if that works as expected for you! If not, we'll reopen and see what we can change to make it work 🙂
