### ISSUE TITLE
Local auth driver login function requires password

### ISSUE THREAD

**Issue by cotyhamilton** [directus/directus#12574]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The login function should issue tokens by providing email only as mentioned below: https://github.com/directus/directus/blob/0930c2df97b480ad0d12dc8f1672360aa9d04e1f/api/src/services/authentication.ts#L37

If not implemented, there are no other exportable functions to help with implementing a custom authentication solution. We'd need to import a package to handle creating jwt and redoing everything else the login function handles for us.

### To Reproduce

1. Set env vars for custom local provider
```
AUTH_PROVIDERS="firebase"
AUTH_FIREBASE_DRIVER="local"
```
2. Create user with `firebase` provider and email "fake3@fake.com"
3. Create custom endpoint `firebase`
```js
"use strict";
var endpoint = (router, { services, exceptions }) => {
    router.get("/connect", async (req, res, next) => {
        const { AuthenticationService } = services;
        const { InvalidCredentialsException } = exceptions;
        const authService = new AuthenticationService({ schema: req.schema });
        try {
            const { accessToken, refreshToken, expires } = await authService.login("firebase", { "email": "fake3@fake.com" });
            res.send({ "data": { accessToken, refreshToken, expires } });
        } catch (error) {
            return next(new InvalidCredentialsException());
        }
    })
};

module.exports = endpoint;
```
4. GET `/firebase/connect`

### Errors Shown

```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at Function.from (node:buffer:322:9)
    at Object.verify (/Users/cotyhamilton/dev/budget.api/node_modules/argon2/argon2.js:95:31)
    at LocalAuthDriver.verify (/Users/cotyhamilton/dev/budget.api/node_modules/directus/dist/auth/drivers/local.js:34:56)
    at LocalAuthDriver.login (/Users/cotyhamilton/dev/budget.api/node_modules/directus/dist/auth/drivers/local.js:39:20)
    at AuthenticationService.login (/Users/cotyhamilton/dev/budget.api/node_modules/directus/dist/services/authentication.js:102:28)
    at async /Users/cotyhamilton/dev/budget.api/extensions/endpoints/firebase/index.js:18:56 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

16.13.2

### What database are you using?

SQLite

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

Local

**Comment by rijkvanzanten** [comment]
The local provider checks against the password as stored in the database, and is used here in the auth service:

https://github.com/directus/directus/blob/0930c2df97b480ad0d12dc8f1672360aa9d04e1f/api/src/services/authentication.ts#L142

The comment you referenced is on the parent authentication service, which in turn calls the auth adapter classes to do the actual login. The used auth adapter may or may not check against the password, hence the comment on it being optional.

Auth adapters are currently not an extension type (yet)

**Comment by cotyhamilton** [comment]
Are there any plans to expose a service for issuing tokens independently of the auth drivers?

And do you have any advice on how to handle this currently?

I abandoned strapi for directus as this project is much better imo, but this was something that was very easy to implement over there and hoping I'm just overlooking something in the directus api.

**Comment by rijkvanzanten** [comment]
> Are there any plans to expose a service for issuing tokens independently of the auth drivers?

The current auth adapters are made in such a way where it should be possible to make them an extension type in the near future. That being said, I'm down to extract the token generation part into a separate util function that can be imported separately by extensions as well 🤔 

> And do you have any advice on how to handle this currently?

So just so I'm on the same page, you're effectively trying to make a custom endpoint to generate the access/refresh tokens from Directus based on any random input, and then continue to use those moving forwards? Another approach could be to use the authenticate hook, that allows you to control the authentication against the incoming request, but that's more to check against a custom token format etc 🤔

**Comment by cotyhamilton** [comment]
Thanks for the response. I went ahead and just did this with an endpoint and copied most of the code from authentication service. Here's a gist for future readers https://gist.github.com/cotyhamilton/14addb2be92fe7829dcdef0bf5eea10d

**Comment by gkielwasser** [comment]
> > Are there any plans to expose a service for issuing tokens independently of the auth drivers?
> 
> The current auth adapters are made in such a way where it should be possible to make them an extension type in the near future. That being said, I'm down to extract the token generation part into a separate util function that can be imported separately by extensions as well 🤔
> 
> > And do you have any advice on how to handle this currently?
> 
> So just so I'm on the same page, you're effectively trying to make a custom endpoint to generate the access/refresh tokens from Directus based on any random input, and then continue to use those moving forwards? Another approach could be to use the authenticate hook, that allows you to control the authentication against the incoming request, but that's more to check against a custom token format etc 🤔

I'm effectively trying to plug into the login function to retrieve tokens ( and reuse all the logic) for a user that have been authenticated elsewhere. Could you please elaborate a bit what you mean using the authenticate hook approach ? I cannot get what would be this workaround ? Thanks

**Comment by rijkvanzanten** [comment]
@gkielwasser My comment is from almost exactly a year ago, I'm afraid I have no clue what I was talking about ^^

**Comment by gkielwasser** [comment]
> @gkielwasser My comment is from almost exactly a year ago, I'm afraid I have no clue what I was talking about ^^

@rijkvanzanten haha no problem, it is true I have started to read and aggregate all have been said since 2021 around those topics
