### ISSUE TITLE
Date field validation on new items

### ISSUE THREAD

**Issue by realpablodias** [directus/directus#1257]
## Version Info
  - Directus version and branch: master (7cc303a9049a5acf725ef9bb73f25ae98c059138)
  - PHP version: 5.5.38
  - MySQL version: 5.6.28
  - Web server: Apache
  - OS name and version: Debian 4.7.2-5

## Expected Behavior
The date and date-time fields should save the selected date when inserting new items.

## Actual Behavior
After inserting a new item, the date field comes as _invalid_. If you make the date field as required, a message shows up saying the field is required but the item is inserted anyway.
The date field just gets fixed if you click to edit the item and save again (even without editing anything).

## Steps to Reproduce
 1. Create a new table with a date (or date-time) field as required;
 2. Insert a new item into the table (an error message will show up);
 3. Back to the items list;
 4. Click on the item with invalid date;
 5. Click to save the item;
 6. The date is ok now.

## Logs or Screenshots

It looks like the _Component.validate_ method is being called twice for the date field, the second one with a _null_ value (app/core/uis/datetime/date.js)

![screen shot 2016-09-11 at 10 12 10 am](https://cloud.githubusercontent.com/assets/4954335/18417503/833bea0c-7808-11e6-94f6-3d0804a4ab6a.png)

![screen shot 2016-09-11 at 10 12 41 am](https://cloud.githubusercontent.com/assets/4954335/18417504/8d33d556-7808-11e6-886e-d25176e695c5.png)

![screen shot 2016-09-11 at 10 12 50 am](https://cloud.githubusercontent.com/assets/4954335/18417505/9215630a-7808-11e6-8b7c-9e29c69f4a25.png)

![screen shot 2016-09-11 at 10 13 06 am](https://cloud.githubusercontent.com/assets/4954335/18417506/97d77da0-7808-11e6-8113-3015031377db.png)

![screen shot 2016-09-11 at 10 13 19 am](https://cloud.githubusercontent.com/assets/4954335/18417509/9ce6f9f6-7808-11e6-9873-39277f897064.png)

**Comment by benhaynes** [comment]
Good find! Thank you for reporting this @realpablodias! We'll get this resolved asap and push a fix.

Appreciate the help!

**Comment by WellingGuzman** [comment]
Hey there @realpablodias, thanks for the report.

I tried your steps and unfortunately I couldn't replicate it, is there something else I need to be aware to replicate it?

**Comment by realpablodias** [comment]
Hi folks. I really appreciate your attention.

I'll try to replicate it in a fresh new install to make sure it isnt a false alarm and let you know soon. Maybe it's  just here?

**Comment by realpablodias** [comment]
Ok, I just got a fresh new install. New project clone, new database, a simple table created from Directus, added a Date field, a Text field, made these fields required and... There's the error.

How can I help you guys with this hunt? Would you like SFTP access to this server? Maybe the database schema?

The only thing I noticed is the missing mod_rewrite during the pre install checks although everything else is fine with the URLs...

Thanks!

**Comment by WellingGuzman** [comment]
Hey @realpablodias, sorry for the delay,

I created a new fresh install as well, and I am now replicating the issue, I will fix this as soon as possible.

Thanks for all the information.

**Comment by WellingGuzman** [comment]
@realpablodias let me know if that fix works for you.

**Comment by realpablodias** [comment]
Works like a charm, @WellingGuzman. Many thanks! ;)

**Comment by WellingGuzman** [comment]
Excellent! Glad to hear. 

@realpablodias anything else let us know :)
