### ISSUE TITLE
CLI Installation: User setup fails (since 6.3)

### ISSUE THREAD

**Issue by beevelop** [directus/directus#1258]
## Version Info
  - Directus version: v6.3.0
  - PHP version: 7.0
  - MySQL version: 5.5
  - Web server: Apache
  - OS name and version: Debian Jessie

## Expected Behavior
Seamless and uncomplicated setup like in the good old times. :shipit: 

## Actual Behavior
```sh
./directus install:config -h 172.17.0.2 -n directus -u directus -p Un1c0rn
./directus install:database
./directus install:install -e directus@example.com -p Un1c0rn -t Directus

Fatal error: Uncaught Directus\Console\Exception\CommandFailedException: [0]: Error changing admin e-mail: Could not change email for ID 1: ID not found or e-mail already changed.
thrown in /var/www/html/api/core/Directus/Console/Modules/InstallModule.php on line 196
```

## Steps to Reproduce
 1. Use [Docker-Directus](https://github.com/beevelop/docker-directus) with Docker-Compose
 2. Create `api/config.php` manually (due to another bug).
 3. Execute the commands from above.

**Comment by WellingGuzman** [comment]
Not good, @beevelop thanks for letting us know. Working on a fix asap.

**Comment by WellingGuzman** [comment]
Hey @beevelop I pushed a fix, let me know if that worked for you. see #1259

**Comment by benhaynes** [comment]
Excellent – thanks again @beevelop... this is a huge help!

**Comment by beevelop** [comment]
@WellingGuzman Wow, thank you for the fast fix. By rebuilding the Docker image from master, I can confirm it to be working. I will incorporate the required changes with your next release into the Dockerfile.
