### ISSUE TITLE
JSON field with wrong (default) value causes error in repeater interface

### ISSUE THREAD

**Issue by HCl-not-HCi** [directus/directus#12584]
### Describe the Bug

If the default value of a JSON field with repeater interface is not null or an array (`[]`), new repeater entries cannot be added. Instead, an error in the browser console is thrown.
The same error occurs if the value of an existing entry is not an array or null, for example, an object (`{}`).

This is caused because directus expects the value of the field to be null or an array.
https://github.com/directus/directus/blob/0930c2df97b480ad0d12dc8f1672360aa9d04e1f/app/src/interfaces/list/list.vue#L263-L267

The question is how to handle this case? Just overwrite the invalid value or show an info that the value is invalid?

Just as a side note how I came accross this error:
I attached directus to an existing database where the default value of a column is `{}`. As a result, directus chose the latter as default value. I did not change it, but configured the repeater interface and tried to add new entries but failed.

### To Reproduce

- Create a collection or use an existing one
- Create a JSON field and set the default value to `{}`
- Set the interface of the JSON field to repeater and configure whatever you like
- Go to the Content module and add a new entry
- See that clicking on "Create New" has no effect but only causes an error

The same happens if an entry already exists but also has an "invalid" value in the JSON field, like `{}`.

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

14.6.0

### What database are you using?

Postgres 12, SQLite

### What browser are you using?

Firefox 98.0.2

### How are you deploying Directus?

Locally, Docker

**Comment by rijkvanzanten** [comment]
> The question is how to handle this case?

I think the least destructive is to ignore the default value, and render a warning in console
