### ISSUE TITLE
CLI Installation requires config.php

### ISSUE THREAD

**Issue by beevelop** [directus/directus#1259]
## Version Info
- Directus version: v6.3.0
- PHP version: 7.0
- MySQL version: 5.5
- Web server: Apache
- OS name and version: Debian Jessie

## Expected Behavior
Installation via CLI should not require `config.php` to exist and just create it.

## Actual Behavior
```bash
./directus install:config -h "$DB_HOST" -n "$DB_NAME" -u "$DB_USER" -p "$DB_PASS"
```

```
Warning: require(/var/www/html/api/config.php): failed to open stream: No such file or directory in /var/www/html/bin/directus on line 7

Fatal error: require(): Failed opening required '/var/www/html/api/config.php' (include_path='.:/usr/local/lib/php') in /var/www/html/bin/directus on line 7
```
## Steps to Reproduce
 1. Launch [Docker-Directus]() with Docker-Compose
 2. Be greeted by the error log from above.

## Workaround
I can successfully skip this exception by `touching` the `api/config.php` first:
```
touch /var/www/html/api/config.php 
```

**Comment by WellingGuzman** [comment]
Thanks @beevelop, I will push a fix as soon as possible.

**Comment by benhaynes** [comment]
Thank you @beevelop! We really appreciate you reporting this issue! 👍
