### ISSUE TITLE
One-To-Many Relationship errors

### ISSUE THREAD

**Issue by luissantos** [directus/directus#1261]
Hi every time i try to select a record from an foreign table a JS error is thrown and the foreign key is not added to the record being inserted. 

`EntriesModel.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:45 Uncaught TypeError: Cannot read property 'get' of undefinedget @ EntriesModel.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:45(anonymous function) @ table.bodyview.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:75_.each._.forEach @ underscore.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:78(anonymous function) @ table.bodyview.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:74_.filter._.select @ underscore.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:172serialize @ table.bodyview.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:69render @ backbone.layoutmanager.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:586manager.callback @ backbone.layoutmanager.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:67_render @ backbone.layoutmanager.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:79actuallyRender @ backbone.layoutmanager.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:427render @ backbone.layoutmanager.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:472(anonymous function) @ backbone.layoutmanager.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:448_.map._.collect @ underscore.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:97(anonymous function) @ backbone.layoutmanager.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:446(anonymous function) @ underscore.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:99_.each._.forEach @ underscore.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:86_.map._.collect @ underscore.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:98(anonymous function) @ backbone.layoutmanager.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:437j @ jquery-1.11.0.js:3099add @ jquery-1.11.0.js:3145actuallyRender @ backbone.layoutmanager.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:427render @ backbone.layoutmanager.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:472(anonymous function) @ one_to_many.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:258triggerEvents @ backbone.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:206trigger @ backbone.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:146_onModelEvent @ backbone.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:933triggerEvents @ backbone.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:207trigger @ backbone.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:147set @ backbone.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:726add @ backbone.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:635(anonymous function) @ one_to_many.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:159_.each._.forEach @ underscore.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:78view.save @ one_to_many.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:142click #addBtn @ ListSelect.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:66dispatch @ jquery-1.11.0.js:4624r.handle @ jquery-1.11.0.js:4292`

## Version Info
  - Directus version and branch: 6.3.3
  - PHP version:  5.5.9-1ubuntu4.9

## Expected Behavior
Save record linked to the another record.

## Actual Behavior
Record is saved without foreign key.

## Steps to Reproduce
 1. Create an One-To-Many field in table X
 2. Create a new record in table X

## Logs or Screenshots
<img width="1920" alt="screen shot 2016-09-17 at 17 06 21" src="https://cloud.githubusercontent.com/assets/1204950/18609399/1def4a7c-7cf9-11e6-814d-dfab9edc5973.png">

**Comment by benhaynes** [comment]
Thanks @luissantos – we're looking into this now! Appreciate you posting this...

**Comment by luissantos** [comment]
I'm trying to understand what the problem is but i'm not familiar with the code base. 
If you need more information please let me know. 
Let me know once you have a patch i would like to help test it.

**Comment by WellingGuzman** [comment]
Hi @luissantos,

Thanks for reporting this, I couldn't replicate the issue can you tell us more about the table schema of both table, `Table X` and the table is the `one to many` related to.

When exactly this happen? after clicking save? or when you choose the item?

**Comment by luissantos** [comment]
@WellingGuzman It happens when i choose the the item.
A Test can be associated with many products.
<img width="1713" alt="screen shot 2016-09-17 at 18 06 41" src="https://cloud.githubusercontent.com/assets/1204950/18609737/8aaf5d8e-7d01-11e6-90d2-0ece0592e469.png">
<img width="1697" alt="screen shot 2016-09-17 at 18 06 22" src="https://cloud.githubusercontent.com/assets/1204950/18609738/8ab34174-7d01-11e6-837c-8300ca116523.png">

**Comment by luissantos** [comment]
Some how my column disappeared and now i can't add it again.
https://github.com/directus/directus/issues/1262

**Comment by luissantos** [comment]
https://github.com/directus/directus/issues/1263
I was trying to start fresh but every time i add an table i got an error.

**Comment by luissantos** [comment]
wget https://github.com/directus/directus/archive/6.3.3.tar.gz

**Comment by WellingGuzman** [comment]
This is not good, I'm is your server like?

I'm working on these issues now, thanks again for reporting all this.

**Comment by luissantos** [comment]
@WellingGuzman I'm using the official vagrant box. 

https://github.com/RNGR/directus-vagrant.git

Linux directusdemo 3.13.0-51-generic #84-Ubuntu SMP Wed Apr 15 12:08:34 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Apache version:  2.4.7-1ubuntu4.4

**Comment by WellingGuzman** [comment]
Hey @luissantos we have been unable to replicate this issue.

Can you please give us the schema you are using with Directus? (You can avoid all the unrelated tables that aren't `directus_`)

Thanks

**Comment by luissantos** [comment]
I'm using the vagrant box and i'm always getting the same error. 

[directus.sql.gz](https://github.com/directus/directus/files/478985/directus.sql.gz)

**Comment by WellingGuzman** [comment]
Thanks for the schema @luissantos , I'm going to try to replicate it using your schema.

**Comment by WellingGuzman** [comment]
Hey @luissantos I finally could replicate the issue, let me know if this [commit](https://github.com/directus/directus/commit/0e444e6a943d7054ab0686cd7390915ea2bbe542) worked for you too.

**Comment by WellingGuzman** [comment]
This should have been fixed by https://github.com/directus/directus/commit/0ba920ebad760dde85225cb2f6a7b1a8a4b6b126 and https://github.com/directus/directus/commit/0e444e6a943d7054ab0686cd7390915ea2bbe542.
