### ISSUE TITLE
Update docs example for uploading file using SDK

### ISSUE THREAD

**Issue by clck-dr** [directus/directus#12628]
### Describe the Bug

If `FormData` for `directus.files.createOne(form)` is generated by package "form-data" there would be a boundary extension in content-type header. The createOne method in files.ts only accepts content-type to be 'multipart/form-data' not 'multipart/form-data; boundary=...'.

### To Reproduce

```javascript
"use strict";

const { Directus } = require("@directus/sdk");
const { FormData } = require("form-data");

(async () => {
  const directus = new Directus("http://example.com/");

  await directus.auth.login({
    email: "some_user",
    password: "some_password",
  });
 
  // https://docs.directus.io/reference/sdk/#files
  // get form as FormData()
  const form = new FormData();
  form.append("file", fs.createReadStream("./to_upload.jpeg"));
  console.log('form :>> ', form.getHeaders());


  const fileId = await directus.files.createOne(form);
})();
```

### Errors Shown

```bash
form :>>  {
  'content-type': 'multipart/form-data; boundary=--------------------------997343116038136974236716'
}
(node:247393) UnhandledPromiseRejectionWarning: Error: Unsupported Content-Type header
    at Transport.request (/home/dr/Schreibtisch/SIAG/hswi-farmer-app/snippets/node_modules/@directus/sdk/dist/sdk.cjs.js:638:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Transport.post (/home/dr/Schreibtisch/SIAG/hswi-farmer-app/snippets/node_modules/@directus/sdk/dist/sdk.cjs.js:667:16)
    at async FilesHandler.createOne (/home/dr/Schreibtisch/SIAG/hswi-farmer-app/snippets/node_modules/@directus/sdk/dist/sdk.cjs.js:61:17)
    at async /home/dr/Schreibtisch/SIAG/hswi-farmer-app/snippets/upload.js:39:18
```

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

14.19.0

### What database are you using?

mysql:5.7

### What browser are you using?

no browser

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
I believe this might be a wrong example in the docs, rather than a bug. https://github.com/directus/directus/pull/12503#issue-1187944570 just implemented support to properly override headers for all the SDK methods, so you should be able to do use:

```js
const { Directus } = require("@directus/sdk");
const { FormData } = require("form-data");

const directus = new Directus("http://example.com/");

await directus.auth.login({
  email: "some_user",
  password: "some_password",
});
 
// https://docs.directus.io/reference/sdk/#files
// get form as FormData()
const form = new FormData();
form.append("file", fs.createReadStream("./to_upload.jpeg"));
console.log('form :>> ', form.getHeaders());

const fileId = await directus.files.createOne(form, {}, {
  headers: {
    ...form.getHeaders()
  }
);
```

**Comment by clck-dr** [comment]
Thank you for your quick response.
I understand your solution but if I apply it to my code, the error still pops up.

![image](https://user-images.githubusercontent.com/74306701/162668959-9416afdf-1f4c-4e54-9415-b4a305900eff.png)

I think the content-type validation in files.ts is to strict. My opinion is that if I have additional boundary behind multipart/form-data the header is still valid (see files.td line 116 post root endpoint).

**Comment by azrikahar** [comment]
@clck-dr the check isn't strict, even though the code seems like it. Reference to the Express docs' `req.is()` here: http://expressjs.com/tr/api.html#req.is

We can also confirm that even when we upload a file via the Admin UI, the content type header sent also contains boundary! Here's a clip:

https://user-images.githubusercontent.com/42867097/162674106-c221d635-eb9a-483e-9900-066ce90ddbc9.mp4

---

I believe the issue in your case (and slight error with the example code shared above) is that the content type header is _NOT_ sent at all. The console log _does not_ confirm that the header is sent in the actual request. Feel free to verify this by outputting the request itself.

As for a fix, you can try this following code that I've tested:

⚠ Make sure that the headers are nested inside `requestOptions`!

```js
const fs = require("fs");
const { Directus } = require("@directus/sdk");
const FormData = require("form-data");

const directus = new Directus("http://localhost:8055");

async function start() {
  await directus.auth.login({
    email: "admin@example.com",
    password: "password",
  });

  // https://docs.directus.io/reference/sdk/#files
  // get form as FormData()
  const form = new FormData();
  form.append("file", fs.createReadStream("./my-example-file.jpeg"));
  console.log("form :>> ", form.getHeaders());

  const fileId = await directus.files.createOne(
    form,
    {},
    {
      requestOptions: {
        headers: {
          ...form.getHeaders(),
        },
      },
    }
  );
}
start();
```

Sample clip of using the above code:

https://user-images.githubusercontent.com/42867097/162674065-6bc5d614-272c-415f-9d9f-7d5137432db2.mp4

**Comment by clck-dr** [comment]
Thank you very much! I missed the nesting inside requestOptions.

**Comment by azrikahar** [comment]
Thanks for confirming! I'll keep this issue open so that we can track this to make sure the docs is updated regarding this `requestOptions` 👍
