### ISSUE TITLE
Duplicated column name error  

### ISSUE THREAD

**Issue by luissantos** [directus/directus#1262]
I'm getting a duplicate column name error but the column isnt visible while editing the table. 

Version: 6.3.3

<img width="1234" alt="screen shot 2016-09-17 at 18 12 42" src="https://cloud.githubusercontent.com/assets/1204950/18609789/851c3594-7d02-11e6-8cc8-d015f794673e.png">
<img width="1230" alt="screen shot 2016-09-17 at 18 12 15" src="https://cloud.githubusercontent.com/assets/1204950/18609790/8535c8a6-7d02-11e6-94cf-6b5dfe66ba79.png">

**Comment by WellingGuzman** [comment]
Can you confirm this still happening to you? I couldn't replicate it. (lil bit late) but which steps did you do to reproduce this?

Thanks, and sorry for the delay with this one.

**Comment by WellingGuzman** [comment]
Hey @luissantos we have solved this issue already it was related to the `data_type` being set to null. (https://github.com/directus/directus/commit/1d3dedef91680c141d995cfa1f8bfe90e2d357f5)

If you still having the issue let us know, and we will open the ticket again.
