### ISSUE TITLE
Error creating table

### ISSUE THREAD

**Issue by luissantos** [directus/directus#1263]
I got an error while creating creating the first table but the table was created successfully. 

`
SchemaManager.js?bust=1aahfii2fk3jtvn6e4sej3o5e7:243 Uncaught TypeError: Cannot read property 'toJSON' of undefined
`

Version: 6.3.3
PHP Version: PHP 5.5.9-1ubuntu4.9

**Comment by luissantos** [comment]
Same thing happened while creating the second table.

**Comment by WellingGuzman** [comment]
@luissantos after days I could replicate the issue: uppercase and linux. Linux is case sensitive, so `Products` and `products` is not the same.

Something to notice is that this can be change, but Directus shouldn't care much about it.

[MySQL identifier case sensitivity](http://dev.mysql.com/doc/refman/5.7/en/identifier-case-sensitivity.html)
