### ISSUE TITLE
Vagrant Box installation fails on OSX

### ISSUE THREAD

**Issue by luissantos** [directus/directus#1264]
Vagrant box installation fails. 

`==> default: /home/vagrant
==> default: PHP Warning:  mysqli::mysqli(): (28000/1045): Access denied for user 'directus'@'localhost' (using password: YES) in /var/
www/html/directus/vendor/directus/migrations/lib/Ruckusing/Adapter/MySQL/MySQLBase.php on line 1294
==> default: PHP Fatal error:  Uncaught
==> default: MySQLBase.php(1296) :
==> default:
==> default: Could not connect to the DB, check host / user / password
==> default:
==> default:
==> default:
==> default:   thrown in /var/www/html/directus/vendor/directus/migrations/lib/Ruckusing/Adapter/MySQL/MySQLBase.php on line 1296
==> default: Database connection failed.`

https://github.com/RNGR/directus-vagrant.git
Box git revision: 77e83ede4d2bd51a1f4e3ca5bbdc7ebd8ab1c2fa

Vagrant: Vagrant 1.8.5
VirtualBox: 5.1.6r110634

<img width="1163" alt="screen shot 2016-09-17 at 18 39 25" src="https://cloud.githubusercontent.com/assets/1204950/18609937/56653954-7d06-11e6-801a-1fb511afa78d.png">
<img width="953" alt="screen shot 2016-09-17 at 18 39 05" src="https://cloud.githubusercontent.com/assets/1204950/18609938/5669d9c8-7d06-11e6-9da3-ba0e9e66bbf9.png">

**Comment by WellingGuzman** [comment]
Thanks for reporting this @luissantos as we have a open similar ticket for vagrant  on his own repo https://github.com/directus/directus-vagrant/issues/16 I will close this and will address the problem over there.

This is a odd issue to me, I can't replicate it, I was thinking it was something to do with Windows or Vagrant version, but apparently is not.

Thanks for the detailed report. I will try to find what is causing this issue.
