### ISSUE TITLE
SQL Server, only tables from DBO - Schema is shown

### ISSUE THREAD

**Issue by StefanPHS** [directus/directus#12647]
### Describe the Bug

I have installed Directus on existing MS SQL  Server Database. I cannot see tables from other schemas than dbo.

### To Reproduce

Create Table in another schema than dbo

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

16

### What database are you using?

MSSQL 2019

### What browser are you using?

Edge

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
This is correct. Directus doesn't currently support using different schemas 👍🏻 See https://github.com/directus/directus/discussions/4908 as well
