### ISSUE TITLE
MTM column not created correctly

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1266]
Current dev branch.

I just tried to create an MTM column but after reloading the page it was gone again. I looked into the DB and saw that the directus_columns table contained the record but it's data_type value was set to null. Setting it manually to `MANYTOMANY` fixed the problem.

A few minutes before I had a problem that while creating a new MTO field getting an mysql syntax error. Only completely reloading the page solved the problem.

Currently I have no time for debugging this any further.

**Comment by WellingGuzman** [comment]
Thanks @laszlokorte again for the report.

We've been having a hard time trying to replicate these issues related to relational UIs, it has been reported similar issues recently.

I will try one more time and see if I can replicate these.

Thanks as always.

**Comment by WellingGuzman** [comment]
@laszlokorte I'm not still able to replicate it. Any help on which steps should I take to replicate it will be helpful.

Thanks.

**Comment by WellingGuzman** [comment]
Another thing @laszlokorte try get the branch updated and let me know if still happen.

**Comment by WellingGuzman** [comment]
hey @laszlokorte we solved this issue with this https://github.com/directus/directus/commit/1d3dedef91680c141d995cfa1f8bfe90e2d357f5 commit

I'm closing the ticket, if you still having issue let me know and I will open the ticket again.

Thanks
