### ISSUE TITLE
Nodemailer not getting text option

### ISSUE THREAD

**Issue by abertay-university** [directus/directus#12677]
### Describe the Bug

I'm trying to email one of our system that only supports plain text emails. I expected the nodemailer to generate a plain text version of the HTML email but this is not the case. After looking into the nodemailer options, it supports a text: option alongside subject. I tried using this option but it's overwritten with:

```
[[https://directus.abertay.ac.uk/admin/img/directus-white.png]](https://directus.abertay.ac.uk/admin/img/directus-white.png)

Sent by the team at Directus — [Manage Emails]()
```

### To Reproduce

<pre>
mailService.send({
    to: 'test@email.com',
    from: 'override.from@email.com',
    subject: 'This is a test email',
    text: 'This is the plain text version',
    template: {
        name: 'custom-template',
    },
});
</pre>

The easiest way to view a plain text email is with the mac mail app. Open the email and click View->Message->RAW Source and look for the section under Content-type: text/plain

It is possible to set Outlook to receive only plain text emails but will impact all incoming messages while switched on.

Here are some other methods for viewing the Raw email source using Gmail, Yahoo and Outlook: https://support.cordial.com/hc/en-us/articles/115002678852

### Errors Shown

No error message thrown as the options are valid.

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

16.13.1

### What database are you using?

MS SQL

### What browser are you using?

Chrome and MS Edge

### How are you deploying Directus?

locally with SMTP server

**Comment by rijkvanzanten** [comment]
I believe the `template` configuration means it's also sending HTML instead of just plain text. With a quick n dirty custom endpoint like:

```js
module.exports = function registerEndpoint(router, { services }) {
	const { MailService } = services;

	router.post('/', async (req, res) => {
		const mailer = new MailService({ schema: req.schema });

		await mailer.send({
			to: 'admin@example.com',
			text: 'Testing',
			subject: 'Plain text test',
		});

		res.send('done');
	});
};
```

the email comes through in the expected plain text:
<img width="1048" alt="CleanShot 2022-04-11 at 12 13 35@2x" src="https://user-images.githubusercontent.com/9141017/162784541-f813c972-5bcd-4317-8050-9e1cd05f87f9.png">

**Comment by abertay-university** [comment]
That's perfect thanks. It would be useful to combine them. Maybe a feature request then?

**Comment by abertay-university** [comment]
Be able to use the text option and the template option in the same email. I made a lot of marketing email in a previous job and I always include a plain text version for those who disable HTML on their client or use an older device that only supports plain text emails. You can see this when you view the Raw code from an email, there will be a plain text version, then a HTML version in the same email. I put it through as a bug because nodemailer had an example using the 2 options:

![image](https://user-images.githubusercontent.com/31690037/162789964-76a6b143-628c-4bb5-a9c8-14684f40dad1.png)

**Comment by rijkvanzanten** [comment]
<img width="752" alt="CleanShot 2022-04-11 at 15 11 31@2x" src="https://user-images.githubusercontent.com/9141017/162812484-88758125-5e95-4edb-b39c-95b446816735.png">

Seems to work as expected!

![CleanShot 2022-04-11 at 15 11 51](https://user-images.githubusercontent.com/9141017/162812573-c4fda62d-128a-45e8-8d1e-0d70f44e5e09.gif)


The template option is just a shorthand to render the HTML inside a `.liquid` file to have a consistent HTML output, which also seems to play nicely with the text on my end:

```js
		await mailer.send({
			from: '"Fred Foo 5" <foodexample.com>', // sender address
			to: 'bar@example.com, baz@example.com', // list of receivers
			subject: 'Hello J', // Subject line
			text: 'Hello world?', // plain text body
			template: {
				name: 'base',
				data: {
					html: '<b>Hello World?</b>',
				},
			},
		});
```

![CleanShot 2022-04-11 at 15 13 46](https://user-images.githubusercontent.com/9141017/162812856-2431103f-9da4-4f0f-88de-8bf9e5f9e94d.gif)


Maybe I'm misunderstanding what you're saying? 😬

**Comment by abertay-university** [comment]
It could be a limitation of the software on the my end. Being a hook, I can easily have just have the text option for this case and another hook for user emails. Such a great platform!
