### ISSUE TITLE
YYYY-MM-DD HH:mm:ss (not shown seconds on datetime ui type). User can insert date and time (HH:mm) but is not possible to set seconds (ss)

### ISSUE THREAD

**Issue by Marco1886** [directus/directus#1267]
Directus 6.3.x

**Comment by WellingGuzman** [comment]
Hey @Marco1886, What do you mean? Not showing on the listing or the input?

**Comment by Marco1886** [comment]
please, find in attach the screenshot. The problem is that i can't set seconds in the ui. The second is setted on db always to 00, but for my project i should set seconds to 59... This is important for example if the cms used to ingest validity period of items. from 00:00:00 to 23:59:59 (24h validity)

![missing possibility to set seconds](https://cloud.githubusercontent.com/assets/22477994/18886248/6462240e-84ef-11e6-9bed-e90af13f429c.png)

**Comment by WellingGuzman** [comment]
@Marco1886 This https://github.com/directus/directus/commit/50692320c2d28425818241c939339160028fe3b1 commit should have fix the issue.

**Comment by benhaynes** [comment]
Thanks for reporting this @Marco1886!!

**Comment by Marco1886** [comment]
you're welcome!! ;-)

**Comment by WellingGuzman** [comment]
Hey @Marco1886 something to know is that, `00` seconds are not shown on Chrome.

And the numbers being disabled is another Chrome thing. BUT I'm glad you find out. I will push a patch for it asap.

Thanks

**Comment by WellingGuzman** [comment]
@Marco1886 This [commit](https://github.com/directus/directus/commit/f6c8247ad364e78ee5aeae3be1d4a40af12c5ae0) should have fix the issue.

**Comment by Marco1886** [comment]
I confirm! fixed! Thanks!

**Comment by WellingGuzman** [comment]
@Marco1886 Great 🎉
