### ISSUE TITLE
Unable to login with new user assigned to new Group

### ISSUE THREAD

**Issue by Marco1886** [directus/directus#1268]
## Steps to Reproduce
 1.  Install directus
 2. Create a new Group Permission
 3. Create new user and set to the user the new Group already create in step 2
 4. Logout
 5. Login with new user.

Actual result:
Unable to login in.
[GroupEditor.txt](https://github.com/directus/directus/files/496040/GroupEditor.txt)

**Comment by WellingGuzman** [comment]
Thanks @Marco1886 for the report, we appreciate it.

I will take a look at the issue.

**Comment by WellingGuzman** [comment]
@Marco1886 did this issue still persist? I wonder if only happened when you first try to log in? then the second time works.

**Comment by Marco1886** [comment]
i'am able to login only with Administrator user. When i try to login with Editor user, the app crash and if i press F5 to refresh crash another time. The only way to do a new login is clear browser cache. Tested on chrome, same version of #1267

**Comment by timonmat** [comment]
I probably the same issue.  Same exact steps anyway. 
http://pastebin.com/iPqYAhMT
Not just once, but every time. clearing the session cookie, is needed to be able to log in again. Admin account continues to work fine, and the new account works via api with the token.

I'm running on docker (rancher) with beevelop/directus image, mysql 5.5 and haproxy in front.

**Comment by WellingGuzman** [comment]
Thanks @timonmat, I'm working on a fix, I could replicate the issue.

**Comment by WellingGuzman** [comment]
@Marco1886 @timonmat something to notice that I haven't told you, is that this is happening because the new group doesn't have permission to read any field from `directus_users` and this will bring a bug that will `select <empty> from any_table`

Giving the current group the right permission will solve the issue.

What I'm working on is making sure the error it's more friendly AND giving the correct default permission to any new users group.

**Comment by Marco1886** [comment]
Yes, it's correct because when i create new group i can't set these perm on this table. We wait the fix. I think that you should publish 6.3.4 build after the fix so other user can't reproduce this bug

**Comment by WellingGuzman** [comment]
@Marco1886 absolutely.

But you can give the group permission using the first user (Admin).

**Comment by WellingGuzman** [comment]
This [commit](https://github.com/directus/directus/commit/263ca372df4723885c9bd45872560ab6c79000e2) and this [one](https://github.com/directus/directus/commit/e1c528358106d78c73dc4a4023d465ef74e03009) should at least avoid showing that exception and it will automatically log out the user.

Make sure that the group has the needed permission.

We still will work on permission in the next releases, any suggestion or issue that may rise let us know.
