### ISSUE TITLE
UI Options should be JSON

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1269]
Instead of saving UI options as rows within `directus_ui`, we should add a new column (`ui_options`) into `directus_columns` for storing the UIs specific settings.

**Comment by WellingGuzman** [comment]
By the way MySQL supports JSON data type as for 5.7.8. https://dev.mysql.com/doc/refman/5.7/en/json.html

> As of MySQL 5.7.8, MySQL supports a native JSON data type that enables efficient access to data in JSON (JavaScript Object Notation) documents. The JSON data type provides these advantages over storing JSON-format strings in a string column.

**Comment by WellingGuzman** [comment]
UI Options are stored as json in `directus_columns` in 6.4.x
