### ISSUE TITLE
List view filters don't work on joined fields

### ISSUE THREAD

**Issue by timonmat** [directus/directus#1270]
I have a table (A) which has a many-to-one relation to another table (B). In the list view of A there is the option filter with dropbox or text values of the joined field. When filter is used it fails with a select error. I tried to modify the filter config in the table settings in many ways, but the error remains the same. 

## Version Info
  - Directus version and branch: (master)
  - PHP version: 7 
  - MySQL version: 5.5 
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: ubuntu 16.04

## Expected Behavior
that filter would work for joined tables.

## Actual Behavior
error

## Steps to Reproduce
 1. create two tables and set up many to one relationship A -> B
 2. view list view of A
 3. use a filter on the join field.

## Logs or Screenshots
![join_table_filter_not_working](https://cloud.githubusercontent.com/assets/15153521/19054490/47ac74d0-89c8-11e6-95fa-a9bd1a3dd18b.PNG)

**Comment by WellingGuzman** [comment]
Thanks for the report I will take a look at this now.

**Comment by benhaynes** [comment]
Thanks @timonmat – we really appreciate you taking the time to report this. We'll follow up here shortly with an update or fix.

**Comment by WellingGuzman** [comment]
Hey @timonmat, I pushed a patch that should fix the issue.

Let us know if it worked for you too.

**Comment by timonmat** [comment]
@WellingGuzman, this is verified ok. cheers!

**Comment by WellingGuzman** [comment]
@timonmat Amazing!
