### ISSUE TITLE
'active' parameter does not work in rest api calls

### ISSUE THREAD

**Issue by timonmat** [directus/directus#1271]
the 'active' parameter does not have an effect on the rest api for 'rows'.

## Version Info
  - Directus version and branch: master
  - PHP version: 7
  - MySQL version: 5.5
  - Web server: apache
  - OS name and version: ubuntu 16.04

## Expected Behavior

the active param is according to docs a global param, and should alwasy work.

## Actual Behavior
for example https://example.com/api/1/tables/table/rows?active=1 results includes all data.

## Steps to Reproduce
 1. create table, add data, delete some data.
 2. query 'rows' rest api with param active=1
 3. 

## Logs or Screenshots
![image](https://cloud.githubusercontent.com/assets/15153521/19088312/44dea32a-8a7e-11e6-8d3d-319b84ac89a7.png)

**Comment by WellingGuzman** [comment]
Hello @timonmat, Thanks for pointing this out.

This docs is outdated, we changed `active` to `status`

it should be like this now: https://example.com/api/1/tables/table/rows?status=1

**Comment by WellingGuzman** [comment]
@timonmat the documentation have been updated.

http://getdirectus.com/api/tables/rows

Closing the ticket, anything else let us know.

**Comment by benhaynes** [comment]
Sorry for the inconvenience, but appreciate you finding and reporting this @timonmat – thanks!

**Comment by timonmat** [comment]
Thanks, and no worries. Found the in[field] param in the updated docs too, which would have been my next question. :)

**Comment by WellingGuzman** [comment]
:) Great, any other question you may have do not hesitate.

PS: We are working on more filters to be implemented soon.

**Comment by podlebar** [comment]
@WellingGuzman it's also wrong written here: https://api.getdirectus.com/1.0/#API_Endpoints in the Global Parameters Sections it still says active instead of status

**Comment by WellingGuzman** [comment]
Hey @podlebar thanks for pointing this out. I'm updating this asap

**Comment by WellingGuzman** [comment]
@podlebar Fixed with https://github.com/directus/api-docs/commit/3f35b746c70dff3acd244251d990ed04aacafa6e and https://github.com/directus/api-docs/commit/5470bda0233ec275b8daad5dad713425f43b7242, Thanks.
