### ISSUE TITLE
Uploaded Files Are Gone After Updating Data Model

### ISSUE THREAD

**Issue by Jason-Hsu** [directus/directus#12718]
### Describe the Bug

The collection has a "Files" field and there are some images uploaded.
![1649837210059](https://user-images.githubusercontent.com/4543938/163130742-a48a10bb-ad9b-4c0e-9b5c-9b637f8b3446.jpg)

After updating the "Data Model" of this collection, then the uploaded images in the "Files" field are gone.
![1649837306865](https://user-images.githubusercontent.com/4543938/163130765-f4cba0be-1065-4b37-bcd7-4603627266ac.jpg)

### To Reproduce

1. Create a new project using the demo project.
2. In "Articles", add a new field of "Files".
3. Select the first row of "Articles", then upload some images in "Files".
4. In "Articles", add a new field of "Image".
5. Go back to see the first row of "Articles", then the uploaded images are gone.

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

16.14.2

### What database are you using?

Directus Cloud's database

### What browser are you using?

Edge

### How are you deploying Directus?

Directus Cloud

**Comment by azrikahar** [comment]
Thanks for filing this issue! I believe this is the same issue as #10842, where other duplicate issues like #10958 and #11296 shares the same characteristics of:

1. data model contains existing O2M/M2M field with linked items (Files interface is a M2M field under the hood as well)
2. Create a new field on the same data model
3. any of the existing O2M/M2M fields loses their linked items

So I'll close this issue in favor of tracking this in #10842. You can subscribe to that issue if you would like to be notified when there's further update 👍
