### ISSUE TITLE
Messaging system annoyances

### ISSUE THREAD

**Issue by Zaelot** [directus/directus#1272]
## Version Info
  - Directus version and branch: master (a2a44d9)
  - PHP version: PHP7
  - MySQL version: MySQL 5.5
  - Web server: Apache 
  - OS: Debian Jessie

## Expected Behavior
One gets to open and see their own messages. Replies in a message-thread are displayed in the order they were sent.

## Actual Behavior
Sending messages gives a Server Error warning, even though messages are actually sent. After that the sent messages are shown unread (white background with blue dot), but when clicked, give a message box with: "You don't have permission to view that page or it doesn't exist" (they also state that "To: A missing or removed user"). Clicking OK transfers one to Tables. If message receives reply, you get a new copy (working).
  
  
Most messages have "Invalid Date" and recent responses can get sandwiched between them (and apparently can also lose their valid date by themselves).

## Steps to Reproduce
 1. Clone master, set up the system with a few admin users
 2. Send a message to another account and reply to it
 3. Check messages with the first user.

## Logs or Screenshots
![image](https://cloud.githubusercontent.com/assets/2608781/19105805/aa60cc82-8aec-11e6-8a67-f9bdc3b3e270.png)
![image](https://cloud.githubusercontent.com/assets/2608781/19105885/21b478d8-8aed-11e6-9fa8-729e61b88cbb.png)

**Comment by Zaelot** [comment]
Apparently messages threads are not marked as read if you're in one while it receives new replies. One has to actually go through Messages navigation to get it correctly marked.

  

Here's a message reply that still has a correct timestamp (that will get corrupted in time). At least when they're all with "Invalid Date" they appear to be in correct order.
![image](https://cloud.githubusercontent.com/assets/2608781/19106129/5c49f5e4-8aee-11e6-8b82-60d60583c813.png)

  

PS. While I'm at it, the Time Zone's were missing some capitals. (Plenty of +2's but no Helsinki. :) )

**Comment by WellingGuzman** [comment]
Hello @Zaelot thanks for reporting this, I'm going to take at look at the issue and fix it as soon as possible.

I will add Helsinki now.

**Comment by WellingGuzman** [comment]
@Zaelot Helsinki is already on the list: https://github.com/directus/directus/blob/master/api/core/functions.php#L576

You are welcome to add more.

**Comment by Zaelot** [comment]
Yes, thank you. That was indeed the issue, though the resulting behaviour was a bit quirky. :)
