### ISSUE TITLE
Field value changes when adding multiple fields from a related collection

### ISSUE THREAD

**Issue by erondpowell** [directus/directus#12734]
### Describe the Bug

In the video, we have an O2M relationship. The  "relational" field `filters_doc` can have multiple `related_values` from the `relational` Collection. Add the IDs from relational and things display fine. Add a second field from the `relational` Collection, and the ID Field values convert to a JSON.

https://user-images.githubusercontent.com/62306630/163212796-8e4db3dd-d924-42a9-b87a-62049d30340d.mov

### To Reproduce

I think I addressed it above. Am I doing this submission process right?

### Errors Shown

No

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

cloud

### What database are you using?

cloud

### What browser are you using?

chrome

### How are you deploying Directus?

Cloud

**Comment by rijkvanzanten** [comment]
This is gonna be a tricky one to fix. The nested relational field signals up to the parent to fetch a different nested data structure, which means that the json structure changes from:

```
{
  "o2m": [1, 2, 3]
}
```

to

```
{
  "o2m": [{ "id": 1 }, { "id": 2 }, { "id": 3 }]
}
```

where each object can have other fields (depending on what's displayed in the tabular layout). 

> Am I doing this submission process right?

Yes!
