### ISSUE TITLE
Shared Table Entry not loading if Role can read m2m Field on related Tables - SQL Error on Backend

### ISSUE THREAD

**Issue by PeterEhses** [directus/directus#12738]
### Describe the Bug

When sharing an item from a given collection that has related (m2m, m2o etc.) collections, the share will not contain any data if the Role selected for the share has read access to the m2m (etc.) key of any related collection. 

The same data gets returned without error when making a simple GET request.

Test link without m2m backlinks: (working except m2m fields with errors)
https://campusdesign.space/admin/shared/0c2d8e4f-88a3-453f-9da5-977a61c8b397
Test link with m2m backlinks: (no fields filled with data)
https://campusdesign.space/admin/shared/9ed14a32-8c3d-4828-bdc5-2208b3ee0218
GET Request URL:
https://campusdesign.space/items/items/de07a0d8-416f-4e67-afe1-0b13b67d9b94

### To Reproduce

Have a collection with a second m2m related collection. 
Create a Role with app access and full read access to the junction table and both collections.
Share one collection using said role. 

### Errors Shown

On the backend, a SQL error is thrown. (Error: ER_TOO_MANY_TABLES: Too many tables; MariaDB can only use 61 tables in a join) On the frontend, the request times out with Status 500.

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

latest

### What database are you using?

MariaDB latest

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker via portainer

**Comment by rijkvanzanten** [comment]
@PeterEhses Would you be able to share a database dump or schema snapshot of this setup either here or through rijk@directus.io? I'm assuming there's some odd recursion going on in the creation of the share permissions between those related m2ms, but it's a little hard to tell without a closer look at the exact setup 🙂

**Comment by PeterEhses** [comment]
> @PeterEhses Would you be able to share a database dump or schema snapshot of this setup either here or through [rijk@directus.io](mailto:rijk@directus.io)? I'm assuming there's some odd recursion going on in the creation of the share permissions between those related m2ms, but it's a little hard to tell without a closer look at the exact setup 🙂

Here's a gist with my current schema:
https://gist.github.com/PeterEhses/1d3034f65616359e7c30718b5a0eca20

If that doesn't help to reproduce the error, I'll send you a database dump via mail. 

The minimum breaking example I tried was sharing an item from "Rooms" and giving the share role read permission for rooms.institutions and institutions.rooms
The same thing happens with any two m2m fields though.

**Comment by azrikahar** [comment]
This could be related or the same as #12336. Also seemingly may only be MySQL/MariaDB specific, and [this SO answer](https://stackoverflow.com/a/5600490) may explain why it's not reported (at least not yet) in Postgres to date.

**Comment by PeterEhses** [comment]
> This could be related or the same as #12336. Also seemingly may only be MySQL/MariaDB specific, and [this SO answer](https://stackoverflow.com/a/5600490) may explain why it's not reported (at least not yet) in Postgres to date.

Looks similar at least. The SQL query logged to console was somewhere around 10k lines wrapped, I can post a dump if needed. 
My instance doesn't crash but does slow down while the query is being computed (presumably). 
I'll see if I can find the time to spin up an instance with postgres to see if the error persists.

**Comment by rijkvanzanten** [comment]
Ahh good find @azrikahar. Lets keep tracking this in https://github.com/directus/directus/issues/12336 👍🏻 Thanks for the help debugging so far @PeterEhses 🙂
