### ISSUE TITLE
Error while adding display columns of raw group

### ISSUE THREAD

**Issue by davidecarlier** [directus/directus#12763]
### Describe the Bug

If I click on the label of "raw group" while adding columns to a collection display table, it adds an empty field that causes erros on refresh.

### To Reproduce

1. create a collection "test" with a raw group "testgroup" and a field "testfield"
2. go the collection page
3. click on the + "add field", and click on testgroup label
4. refresh

### Errors Shown

When I click on the group label the console show a 400 error while attempting this query 
/items/test?limit=25&fields[]=testfield&fields[]=testgroup&fields[]=&fields[]=id&sort[]=id&page=1&meta[]=filter_count&meta[]=total_count

When I refresh the problem shown is this:
```
{
  "errors": [
    {
      "message": "\"fields[2]\" is not allowed to be empty",
      "extensions": {
        "code": "INVALID_QUERY"
      }
    }
  ]
}

```

On a more complex table I got a blank page with this error but I can't reproduce.
![Schermata 2022-04-14 alle 15 48 58](https://user-images.githubusercontent.com/24975420/163407611-46c33c2e-a1c1-4c92-b48e-ac0904d6485e.png)
I had to manually delete the row from directus_preset table to be able to enter the page again

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

14.18.2

### What database are you using?

SQLite 3.31.1

### What browser are you using?

Chrome

### How are you deploying Directus?

DO droplet

**Comment by azrikahar** [comment]
I believe this has been resolved by #12539 (not released yet) which prevents groups from being selectable 👍
