### ISSUE TITLE
Field display template not working on M2M

### ISSUE THREAD

**Issue by lluishi93** [directus/directus#12768]
### Describe the Bug

The display template option does not work, the field container does not show the indicated fields in the configuration. It seems to be showing the ID everytime, no matter what configuration is set.

Configuration:
![image](https://user-images.githubusercontent.com/14786440/163440142-b4e84ed9-ffe2-47ca-b1ac-af516a5dd8d2.png)

![image](https://user-images.githubusercontent.com/14786440/163440039-bc89eb53-3dfb-4c2b-bb53-3ed2100358d7.png)

MySQL row for directus_fields:
![image](https://user-images.githubusercontent.com/14786440/163439918-1f698f6c-50b0-4e1f-8271-aeb4dd9e573e.png)

Result:
![image](https://user-images.githubusercontent.com/14786440/163439687-0ef7846d-0927-4a58-aca1-6514c29938cb.png)

### To Reproduce

1. Create collection A with a string field named "name"
2. Create collection B with a m2m field pointing to collection A. Set the display options to "related values" and set the name in the template
3. Create some items for collection A
4. Create an item for collection B and relate it to some of the previously created collection A items
5. Check that the m2m field does not show the item list with their names

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

16.13.2

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Hi! Would you mind testing this on `v9.9.0` as well? I also believe there is some confusion here. The display template under `Display` tab is for configuring how it is displayed when viewed in a table layout for example, here's a clip:

https://user-images.githubusercontent.com/42867097/163765548-58ceadf5-032e-466f-abc1-bd55006747d1.mp4

Whereas what you are looking for should be the display template under `Interface` instead, as seen here:

https://user-images.githubusercontent.com/42867097/163765600-f229aa8a-7bfd-44ab-aaa6-adcd59d22624.mp4

I believe this is working as intended, but will reopen when you can confirm it is still in fact an issue and there were some misinterpretation in my examples/description given above 👍

**Comment by lluishi93** [comment]
The display template field option was used in Directus 8 to render specific fields **under Interface**, as you can see here:

configuration:

![image](https://user-images.githubusercontent.com/14786440/163790107-70e83f5b-f1d4-42cf-8ea2-81c0a3717a59.png)

result:

![image](https://user-images.githubusercontent.com/14786440/163790154-362356eb-b27a-4efb-a4a2-8eea8e97dc29.png)

The display template in Directus 9 should be the same, and it totally makes sense: when you have a LOT of content, you cannot rely solely on the ID to know which items are related to another.

**Comment by rijkvanzanten** [comment]
@lluishi93 I believe the confusion here is between what the Interface and Display is. The Interface is what you're showing in your screenshot, but you're configuring the Display. Try configuring the Display Template option under Interface 🙂 

> The display template in Directus 9 should be the same

It is 👍🏻

**Comment by lluishi93** [comment]
Ok, that seems to be it. Last thing I miss is that in Directus 8. the display was divided in columns, showing the name of the field on top. But this doesn't seem to be the case for Directus 9. Is there something am I doing wrong?

No hyphen:

![image](https://user-images.githubusercontent.com/14786440/163878250-05dcc107-bfd1-41b5-91ea-11f01b0d148b.png)

With hyphen: 

![image](https://user-images.githubusercontent.com/14786440/163878354-b5c14b67-b2a1-4354-b01f-d5e7198974e7.png)

**Comment by rijkvanzanten** [comment]
That's correct. V8 used to render in inline tables, v9 uses the row style ux 👍🏻  There's actually an in-works PR to allow rendering as either tables or rows, see https://github.com/directus/directus/pull/12820
