### ISSUE TITLE
Cannot Login, Error 404

### ISSUE THREAD

**Issue by RabbitMC** [directus/directus#1276]
## Version Info
  - Directus version and branch: Version 6.3.4
  - PHP version: 7.0.8
  - MySQL version: Ver 14.14 Distrib 5.7.15,
  - Web server: Apache 2
  - OS name and version: Ubuntu Server 16.04.3 

I have installed Let's Encrypt on my server to get a secure connection.
After that I have add a new database and a new db user.

Running 'composer install' was successful. 

I navigated to my webaddress and started with the "installation wizard". 
At the end I have an error on mod_rewrite.

![after_install_1](https://cloud.githubusercontent.com/assets/1866374/19262369/efb4b736-8f96-11e6-8b41-7f4ce536cd4a.png)

I checked all possibilities how to enable mod_rewrite on my server. 
Running `sudo a2enmod rewrite
Module rewrite already enabled`

Then I tried to login. But all the time this error occurs in my debug console.

![after_install_2](https://cloud.githubusercontent.com/assets/1866374/19262418/331fc790-8f97-11e6-831d-a224d4c24eaa.png)

Then I startet a FTP Connection to my server, to change the .htaccess files.

First: /pathToDirectus/directus/.htaccess

```
# Hide directory listings
Options -Indexes

# No font warnings please
AddType font/ttf .ttf
AddType font/eot .eot
AddType font/otf .otf
AddType font/woff .woff


    RewriteEngine On
    RewriteBase /

    RewriteRule ^assets - [L,NC]
    RewriteRule ^extensions/([^/]+) - [L,NC]
    RewriteRule ^extensions/([^/]+)/assets - [L,NC]
    RewriteRule ^extensions/([^/]+)/main.js - [L,NC]

    RewriteRule ^listviews/([^/]+) - [L,NC]
    RewriteRule ^listviews/([^/]+)/assets - [L,NC]
    RewriteRule ^listviews/([^/]+)/ListView.js - [L,NC]

    # Files Proxy
    # - Only define one of the URL segments /.../ here so that the request format
    #   can be more flexibly maintained in the PHP/Slim router
    # @NOTE: media_auth_proxy was removed
    # @TODO: Implement files proxy using the new files object
    # RewriteCond %{REQUEST_URI} media_auth_proxy/([^/]+)/(.+)$
    # RewriteRule ^ /media_auth_proxy/index.php [L]

    # Directus Front Controller
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} !index
    RewriteRule (.*) index.php [L]



<ifModule mod_php5.c>
    # default is 64, so 64 + 72 (post_max_size value)
    php_value memory_limit 136M

    # default is 8, so 8 + 64 (upload_max_filesize value)
    php_value post_max_size 72M

    # default is 2
    php_value upload_max_filesize 64M

    # E_ALL | E_STRICT
    php_value error_reporting 32767
</ifModule>
```

Then /pathToDirectus/directus/api/.htaccess

```
Options +SymLinksIfOwnerMatch


    RewriteEngine On
    RewriteBase /api

    RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Yield static media
    RewriteCond %{REQUEST_FILENAME} !-f

    # Map extension requests to their front controller
    # RewriteRule ^1/extensions/([^/]+) ../extensions/$1/api.php [L]
    RewriteRule ^1/extensions/([^/]+) api.php?run_extension=$1&%{QUERY_STRING} [L]

    # Map all other requests to the main front controller, invoking the API router
    RewriteRule ^ api.php?run_api_router=1&%{QUERY_STRING} [L]
```

Then I go to /etc/apache2/sites-available

I added to all .conf files:

```
<Directory /var/www/html>
			Options Indexes FollowSymLinks MultiViews
        		AllowOverride All
   			Order allow,deny
   			allow from all
		</Directory>
```

Nothing changed :/  Any idea?

**Comment by WellingGuzman** [comment]
Hello @RabbitMC,

Removing the error persists if you removed or add the `RewriteBase`?

Can you try this https://github.com/directus/directus/issues/889#issuecomment-249789534?

**Comment by RabbitMC** [comment]
strange ...

I removed the lines `RewriteBase /` and `RewriteBase /api` from .htaccess files and now its working 👍

**Comment by WellingGuzman** [comment]
Perfect @RabbitMC, anything else let us know.

**Comment by RabbitMC** [comment]
After 3 months, Lets Encrypt need a refresh. The Issue appeared again. Now I know how to fix the issue correctly without having trouble or changing directus files.

In /etc/apache/sites-available/default-ssl.conf check 

```
<Directory /var/www/html>
    Options FollowSymLinks Includes IncludesNOEXEC
    AllowOverride All
    Require all granted
.
.
.
</Directory>
```
**AllowOverride All** must be set!

With this change, I checkout current master, and everything works!
