### ISSUE TITLE
table.insert not firing

### ISSUE THREAD

**Issue by DaveBlooman** [directus/directus#1277]
Further to the issue I raised yesterday, the latest version seems to have broken my hook, it never gets invoked.

Here is the hook code

```php
'hooks' => [
       'table.insert' => function ($tableName, $record) {
          $credentials = array('key'    => 'key',
                               'secret' => 'secret');

          $client = new SnsClient(array(
              'credentials' => $credentials,
              'region'  => 'eu-west-1',
              'version' => "2010-03-31"
          ));


          $keys = array_keys($record);
          $arr = array(
            "postID" => (int)$record[$keys[0]],
            "tableName" => $tableName,
            "status" => (int)$record[$keys[1]]
          );

           $result = $client->publish(array(
              'TopicArn' => 'arn:aws:sns:eu-west-1:0000000000:cms-events',
              'Message' => $record,
              'Subject' => 'CMS Event'
          ));
        }

    ]
```
## Version Info
 - Directus version and branch: 6.3.4
 - PHP version: 5.5
 - Web server: Apache
 - OS name and version: Ubuntu

## Expected Behavior
Hook sends message

## Actual Behavior
Hook doesn't send message

## Steps to Reproduce
 1. Create new post
 2. Hook doesn't trigger

## Logs or Screenshots
No error logs

**Comment by WellingGuzman** [comment]
Thanks for reporting this @DaveBlooman , I'm working on it.

**Comment by WellingGuzman** [comment]
Hello @DaveBlooman, I push a fixes for the issue here: https://github.com/directus/directus/commit/9039d68cbf2474660f88b65615c2449467306164, hope it works for you too.

It's only on development, but it will be soon release.

**Comment by DaveBlooman** [comment]
I haven't tested this, but I assume table.update works too, will report back once i have tried

**Comment by DaveBlooman** [comment]
Fix works great.  Look forward to the next release

**Comment by WellingGuzman** [comment]
Amazing @DaveBlooman, great to hear. As always, anything else, let us know.

Closing it.

**Comment by DaveBlooman** [comment]
So, just noticed that table.update is very different in the data it gives.

```json
{
    "output": {
        "last_page": "{\"path\":\"tables/new_features/24\",\"route\":\"entry\"}",
        "last_access": "2016-11-08 12:15:00",
        "id": 1
    }
}
```

This previously included post ID, status, last access, but now doesn't include post ID. I'm pretty sure that id is actually meant to be status as well.

**Comment by WellingGuzman** [comment]
Hey @DaveBlooman, that's the data the `table.update` is sending?

I'm going to take a look at this and get back to you, asap.

**Comment by WellingGuzman** [comment]
What's inside the `output` it seems to be the `directus_users` update data.
