### ISSUE TITLE
active filter parameter not working for /rows endpoint

### ISSUE THREAD

**Issue by mgkeen** [directus/directus#1278]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests please use the [Directus FeatHub](http://feathub.com/directus/directus) to make a new request or vote for existing ones, or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues.

## Version Info
  - Directus version and branch: 6.3.4
  - PHP version: 5.5
  - Web server: Apache
  - OS name and version: Ubuntu

## Expected Behavior
Calling /api/1/tables/[table]/rows?active=1 should return only active rows.

## Actual Behavior
Currently returning all rows irrespective of active status.

## Steps to Reproduce
 1. Call that endpoint on the API

**Comment by WellingGuzman** [comment]
Hello @mgkeen, Thanks for reaching out, we have changed it to `status`.

Calling /api/1/tables/[table]/rows?status=1 should work, and return only the active rows.

Read here: http://getdirectus.com/api/tables/rows
