### ISSUE TITLE
GeoJSON filtering UI broken

### ISSUE THREAD

**Issue by stockhuman** [directus/directus#12793]
### Describe the Bug

Filter options do not seem to work, the map icons are unclickable and some operations offer no actual input method to complete the filter. Pictured are results that have no data and therefore match a bogus query.

Perhaps related, I cannot seem to get `_intersects_bbox` to work through GraphQL.

```"\"_intersects_bbox\" has to be a valid GeoJSON object"``` is all that is ever returned.

### To Reproduce

1. Create a GeoJSON field and populate it
2. Attempt to filter

### Errors Shown

![Screen Shot 2022-04-14 at 1 58 41 PM](https://user-images.githubusercontent.com/13852458/163654801-56954af4-abf5-48bd-832f-a97361f979ef.png)
![Screen Shot 2022-04-14 at 2 14 39 PM](https://user-images.githubusercontent.com/13852458/163654803-3c1a69cc-b020-4ac9-8e77-92a8f9574109.png)
![Screen Shot 2022-04-14 at 2 15 01 PM](https://user-images.githubusercontent.com/13852458/163654806-36ac6e30-968b-4821-bc2b-86e5bb2c1d5e.png)

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

16.14.2

### What database are you using?

MariaDB

### What browser are you using?

Chrome

### How are you deploying Directus?

Debian VM

**Comment by azrikahar** [comment]
Note: This likely needs to be fixed with #10869 altogether as they should be very related (that issue is the bug on API side).

**Comment by rijkvanzanten** [comment]
Lets consolidate this into #10869 as per the above comment. Both issues are very closely related and should ideally be resolved in the same PR 👍🏻
