### ISSUE TITLE
Total app failure on custom roles with permission based on user column

### ISSUE THREAD

**Issue by u12206050** [directus/directus#12803]
### Describe the Bug

A role with a custom permission on view `directus_users` is causing total app failure.

I have a collection `orgs` with a M2M relationship to `directus_users` through `members` table.
The `members` table has the fields `(id, org, user)`

Seems like the generated query is missing a table name on the first `user` query in `WHERE`

The QUERY, (edited for readability) **Missing table name**
```
SELECT `directus_users`.`*` FROM `directus_users`
WHERE (`directus_users`.`id` = '680828fb-ce31-49bd-b11d-d2c81c9564db'
 AND (
  (`directus_users`.`id` IN (
    SELECT `members`.`user` AS `user` FROM `members`
    LEFT JOIN `orgs` AS `qwe` ON `members`.`org` = `qwe`.`id`
    LEFT JOIN `members` as `asd` ON `qwe`.`id` = `asd`.`org`
    LEFT JOIN `directus_users` as `zxc` ON `asd`.`user` = `zxc`.`id`
    WHERE **`user`** IS NOT NULL AND `asd`.`user` = '680828fb-ce31-49bd-b11d-d2c81c9564db'
  )) OR `directus_users`.`id` = '680828fb-ce31-49bd-b11d-d2c81c9564db')
) order by `directus_users`.`id` asc limit 100
```

### To Reproduce

`(directus_users)<-[user]-(members)-[org]->(orgs)`

The custom permission I have on `directus_users` collection is 
```
{
  orgs: {
    org: {
      members: {
        user: {
          _eq: "$CURRENT_USER"
        }
      }
    }
  }
}
```

### Errors Shown

Query 1 ERROR: Column 'user' in where clause is ambiguous

### What version of Directus are you using?

9.9.0

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

edge

### How are you deploying Directus?

Locally & GCP

**Comment by tspvivek** [comment]
I am getting `column reference "user" is ambiguous ` error. Seems like same issue.

**Comment by rijkvanzanten** [comment]
> I am getting `column reference "user" is ambiguous ` error. Seems like same issue.

Sounds like the same error from a different database vendor 👍🏻
