### ISSUE TITLE
Uploading files to the field results in undefined binding(s) error 

### ISSUE THREAD

**Issue by adrianplavka** [directus/directus#12812]
### Describe the Bug

When creating a new collection with the "Files" input, uploading new files would result in not showing a new item, and trying to create/update the collection item would result in an `undefined binding(s)` error.

![Screenshot 2022-04-17 at 15 54 15](https://user-images.githubusercontent.com/22895555/163717663-2546a784-cebe-45c2-a77b-4a34d434c783.png)

This bug happened to me after updating from version 9.8.0 to 9.9.0. My intention with the upgrade change was to eliminate the duplicate items shown when uploading files to the input. This change would completely disfunction the `Upload file` functionality in the files input.

Adding existing items from the file library to the file input seem to work just fine though.

### To Reproduce

1. Create a new Directus application with SQLite database.
2. Create a new collection.
3. Create a `Files` field under the new collection.
4. Create a new collection item, while trying to upload a new file under this file input.
5. This will not show any thumbnail/item under the input and unable to deselect it. Also, trying to create/update the collection item would result in the error above.

### Errors Shown

```Error: Undefined binding(s) detected when compiling UPDATE. Undefined column(s): [id] query: update `articles_files` set `articles_id` = ?, `directus_files_id` = ? where `id` in (?)
    at QueryCompiler_SQLite3.toSQL (/Users/adrianplavka/Development/goodvision/podhajom/backend/node_modules/knex/lib/query/querycompiler.js:110:13)
    at Builder.toSQL (/Users/adrianplavka/Development/goodvision/podhajom/backend/node_modules/knex/lib/query/querybuilder.js:83:44)
    at ensureConnectionCallback (/Users/adrianplavka/Development/goodvision/podhajom/backend/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:4:30)
    at Runner.ensureConnection (/Users/adrianplavka/Development/goodvision/podhajom/backend/node_modules/knex/lib/execution/runner.js:272:20)
    at async Runner.run (/Users/adrianplavka/Development/goodvision/podhajom/backend/node_modules/knex/lib/execution/runner.js:30:19)
    at async /Users/adrianplavka/Development/goodvision/podhajom/backend/node_modules/directus/dist/services/items.js:322:21```

### What version of Directus are you using?

9.9.0

### What version of Node.js are you using?

16.13.1

### What database are you using?

SQLite 5.0.2

### What browser are you using?

Chrome

### How are you deploying Directus?

local

**Comment by Nitwel** [comment]
Thank's for the issue and sorry for the inconvenience!
A quick workaround would be to upload the file first and then select it until the next release.

**Comment by adrianplavka** [comment]
@Nitwel Thanks for the quick fix! I will eagerly await the next release.
