### ISSUE TITLE
m2m can't select item, shows blank

### ISSUE THREAD

**Issue by cdwmhcc** [directus/directus#12813]
### Describe the Bug

![image](https://user-images.githubusercontent.com/8030134/163749631-0e71cd5e-8f27-4e00-97fe-830b8333a6bf.png)

Many-to-many, can't select item, shows blank

### To Reproduce

Works in version 9.8.0
I don't know what's causing it

### Errors Shown

![image](https://user-images.githubusercontent.com/8030134/163749414-9ca4fac0-8de3-4912-bf8c-d364d9b4f82a.png)

### What version of Directus are you using?

v9.9.0

### What version of Node.js are you using?

v16.14.0

### What database are you using?

mysql 8.0.24

### What browser are you using?

chrome

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment]
Unfortunately I can't seem to reproduce this on my end:

https://user-images.githubusercontent.com/42867097/163761743-ce46f5e8-65fc-4ec2-bad7-3afc2afc8ad8.mp4

it would be much appreciated if you can provide a detailed but minimal reproducible steps, ideally on a fresh instance, in the To Reproduce section 👍 Thanks!

**Comment by cdwmhcc** [comment]
> Unfortunately I can't seem to reproduce this on my end:
> 
>  chrome_1Hv97iNewl.mp4 
> it would be much appreciated if you can provide a detailed but minimal reproducible steps, ideally on a fresh instance, in the To Reproduce section 👍 Thanks!

I don't know how to reproduce, after the upgrade it was like this.

**Comment by rijkvanzanten** [comment]
@cdwmhcc What permissions does your user have to this field? Are they allowed to read the junction/related collections?

**Comment by cdwmhcc** [comment]
> @cdwmhcc What permissions does your user have to this field? Are they allowed to read the junction/related collections?

I removed and re-added the many-to-many field and now it works. This is a very strange thing.I confirm this has nothing to do with permissions.
