### ISSUE TITLE
message multi-select on list does not work

### ISSUE THREAD

**Issue by timonmat** [directus/directus#1281]
In messages list view the multi-select checkboxes don't work, but take you to the message, which means there's no way to delete messages.
## Version Info
- Directus version and branch: 6.3.4
- PHP version: php7
- MySQL version: mariadb 10.1.18
- Web server: (Ex. Apache, nginx or IIS?) apache
- OS name and version: docker /debian jessie
## Expected Behavior

checkboxes to work, and delete option to apper.
## Actual Behavior

goes to the message.
## Steps to Reproduce
1. write message.
2. go to list view, and try to select the checkbox

**Comment by WellingGuzman** [comment]
@timonmat thanks for reporting this, I'm going to work on it soon.

**Comment by WellingGuzman** [comment]
The soon about this was to implement it on `6.4.x` I will close this ticket as we didn't mean to include it in `6.3.x`.

I'm sorry about not adding it in the recent minor version. I've hide the checkbox in 6.3.x to avoid confusion.
