### ISSUE TITLE
Wrong layout

### ISSUE THREAD

**Issue by cdwmhcc** [directus/directus#12815]
### Describe the Bug

wrong layout

![image](https://user-images.githubusercontent.com/8030134/163750396-57d9b9be-5041-4a5c-a4e5-69b2a6924ebf.png)

Why is the red box blank?

![image](https://user-images.githubusercontent.com/8030134/163750360-b0e3423f-b617-4458-a33a-dee36bf95f21.png)

### To Reproduce

as above，I don't remember from which version it was wrong, before several versions it was normal.

### What version of Directus are you using?

v9.9.0

### What version of Node.js are you using?

v16.14.0

### What database are you using?

mysql 8.0.24

### What browser are you using?

chrome

### How are you deploying Directus?

running locally

**Comment by u12206050** [comment]
This is due to the fields that are not visible.
Move none visible fields to the top or to the bottom, this will allow you to easier view how the end layout will be.

**Comment by cdwmhcc** [comment]
> This is due to the fields that are not visible. Move none visible fields to the top or to the bottom, this will allow you to easier view how the end layout will be.

Invisible fields should not affect the layout of visible fields.
