### ISSUE TITLE
M2M field - in deep relationship - dont show list of items

### ISSUE THREAD

**Issue by koksikus** [directus/directus#12836]
### Describe the Bug

I think I found an error you can see it at the end of the video, where inside the record in detail you can not see the items. 
I also have a question why I do not see the details in the junction table - I can not edit details.

https://user-images.githubusercontent.com/90528895/163866223-dd4be52c-8f95-469e-b212-0456cbe35821.mp4

### To Reproduce

I think I showed in the video.

### What version of Directus are you using?

9.9.0

### What version of Node.js are you using?

16.14.1

### What database are you using?

MySQL

### What browser are you using?

Edge

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
@Nitwel I think it's because the primary key of the v-form is set to `+` rather than the ID of the related item
