### ISSUE TITLE
Don't save revision row when delta is empty

### ISSUE THREAD

**Issue by koksikus** [directus/directus#12838]
### Describe the Bug

Without changing anything in the data, you can change the revision:

https://user-images.githubusercontent.com/90528895/163868842-e542f711-9463-402d-8cc5-04cc037a1de3.mp4

### To Reproduce

I showed in the video

### What version of Directus are you using?

9.9.0

### What version of Node.js are you using?

16.14.1

### What database are you using?

MySQL

### What browser are you using?

Edge

### How are you deploying Directus?

locally

**Comment by koksikus** [comment]
This still appears in the latest version. 

https://user-images.githubusercontent.com/90528895/164773019-795493e5-8510-4cd9-804e-ce383f0921a8.mp4

**Comment by rijkvanzanten** [comment]
> This still appears in the latest version.
> 
>  Model-danych.video-converter.com.mp4

In this case, there was an update though, as the "date updated" field was (automatically) modified 👍🏻 This behavior is correct

**Comment by koksikus** [comment]
> 
OK I understand, but why the "date updated" field has changed since nothing has been updated beyond that field. Maybe this field should react to some change ...

**Comment by koksikus** [comment]
I still wonder why opening a record without modifying it saves a new revision. I understand this is due to the field date update and user update but why is this a new revision. Someone without knowing it will write me a lot of revisions. 
If there was a condition that since the change concerns only the date and the user, the revision is not saved until the next field changes, would be great...
