### ISSUE TITLE
Server Error This query failed: INSERT INTO `directus_activity`

### ISSUE THREAD

**Issue by raygers** [directus/directus#1283]
## Version Info
  - Directus version and branch: directus-6.3.4
  - PHP version: 5.6
  - MySQL version: 5.6.15
  - Web server: XAMPP 
  - OS name and version: Windows 10

## Expected Behavior
When adding a new record there should be no server error.

## Actual Behavior
Saving a record produces the following error:
Server Error
This query failed: INSERT INTO `directus_activity` (`type`, `table_name`, `action`, `user`, `datetime`, `parent_id`, `parent_table`, `data`, `delta`, `row_id`, `identifier`, `logged_ip`, `user_agent`) VALUES ('ENTRY', 'lookup', 'UPDATE', '1', '2016-10-18 19:29:42', '16', 'test', '{\"id\":\"6\",\"active\":\"1\",\"category\":\"Cat 2\"}', '{\"id\":6}', '6', 'Cat 2', '::1', 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36')

MYSQL Error: Field 'parent_changed' does not have a default value.

I have 3 tables, test, lookup and a junction table. test has many to many field which is related to the lookup table. The error occurs when saving a record.

![image](https://cloud.githubusercontent.com/assets/22856065/19508879/f577d504-95db-11e6-9115-f7f58e31c967.png)

Thanks
Ray

**Comment by WellingGuzman** [comment]
Thanks @raygers for reporting the issue I will take a look and get back to you as soon as possible.

**Comment by WellingGuzman** [comment]
Hey @raygers I pushed a fix for this issue, let me know if it works for you.

**Comment by raygers** [comment]
Thanks @WellingGuzman. I applied the latest files and the error has been resolved.

Many thanks for the quick response.

Regards
Ray

**Comment by WellingGuzman** [comment]
Glad to heard 👍 , anything else let us know.
