### ISSUE TITLE
How To: One To One Relationship

### ISSUE THREAD

**Issue by RabbitMC** [directus/directus#1285]
Hi,

what is the best practice for my following problem.

I have two tables: `item` and `event`

The user can add one event to one item, when adding a new item. What is the best FIELD for? MANY_TO_MANY, MANY_TO_ONE_TYPEAHEAD, MANY_TO_ONE, ONE_TO_MANY? 

Goal is to get an "event" row in api-call response. Any ideas? Or is my design ugly? 

Trying MANY_TO_MANY with a extra junction table works, but in the response on `.../api/1/tables/item/rows` there is now `event` row. I must go over to the special junction table to look up. This costs time to match all these information on client.

MANY_TO_ONE does not work as I would expect
MANY_TO_ONE_TYPEAHEAD works, but the UI is bad

ONE_TO_MANY looks good in the UI, but do nothing on DB site. So there is also nothing in rest-call response

**Comment by WellingGuzman** [comment]
Hi @RabbitMC,

Using MANY TO ONE, you can quite do a One to One or kind of One to one or none.

Are you having trouble with many to one UI? Because you can add a many to one on `item` to point to `event` and event will always be ONE TO ONE, as the `event` table will always point to only one `item` (_OR None_)

```
Item
--------------
- id
- name
```

```
event
-----------
- id
- name
- item_id
```

in this case an `event` will always a relationship with one item, but the item can be in more event, unless you make the table column unique.

That's the solution that can be done with Directus UI.

Let me know what you think, either way you can help us shape this new UI.

**Comment by RabbitMC** [comment]
Thanks for. 
I will do it with a Many to Many relationship now, because the focus has changed.

**Comment by WellingGuzman** [comment]
Great @RabbitMC, anything else, let us know.

**Comment by zeusstl** [comment]
Wondering if there is a way to limit the number of rows on a one-to-many field, to effectively create a one-to-one. Maybe this means hiding the add buttons after a certain amount of rows.

Part of the issue with using a one-to-many in place of a one-to-one is that the ui still shows the buttons for adding more - so a user will add many (or will be upset with the unique field method that only alerts after the input).

**Comment by benhaynes** [comment]
Hey @zeusstl — I think min/max count options for the M2M and O2M would be a really great enhancement. Not sure if this would be enforced by the API or simply an App (GUI) feature. Either way, if you submit a feature request to the app repository I'll vote for it!

**Comment by stouch** [comment]
Hi, is it possible if I set a Many-To-One to an item, to edit its related content directly in the edit view ? For example , I've got a News item, and a OpenGraph item related, and I want to edit the open graph fields directly in the news edit view ? Is there a way to do this ?
Thx.

**Comment by benhaynes** [comment]
All of the relational interfaces **should** do this. If they don't we can add support in the next v9. It would help to have individual tickets to track these requests though. 😉

**Comment by stouch** [comment]
I mean, in this example : "Page" is a many-to-one item for my "Homepage" -> I'd like to be able to edit directly the related Page inside the Homepage editor .  You confirm it's not possible for now ?
<img width="930" alt="Capture d’écran 2020-03-24 à 15 03 59" src="https://user-images.githubusercontent.com/17531455/77434414-1b38d500-6de1-11ea-9897-6b9d7a58f02d.png">

**Comment by benhaynes** [comment]
Not as of now, but it would make sense to add an Interface Option (on by default) that adds an icon for opening/editing the related item. @rijkvanzanten — let's add this into v9...
