### ISSUE TITLE
Item error after dropping column in database

### ISSUE THREAD

**Issue by claytongulick** [directus/directus#12857]
### Describe the Bug

Directus 404 error when accessing an item in a collection where a configured field was dropped from the database.

### To Reproduce

I have a collection, device_catalog. This collection contained a field "measures".

I configured the "measures" field in the directus UI, however I decided to remove this column.

I dropped the column from the database.

I restarted directus, and I'm able to see the collection, however when I select an item from the collection I get a 404 error.

The logs show a SQL error, attempting to select the column that no longer exists.

Looking in the directus table "directus_fields" I see that the configured column is still in that table.

After manually deleting the row from the "directus_fields" table, everything works properly.

### What version of Directus are you using?

9.9

### What version of Node.js are you using?

16.14.2

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

local

**Comment by rijkvanzanten** [comment]
I think this is caused by the logic that controls what columns are fetched when `fields=*` is used. That should exclude aliases and other columns that don't have a representation in the database (like directus_fields records that no longer exist in the db)
