### ISSUE TITLE
Form items are broken when content is too long

### ISSUE THREAD

**Issue by JackNUMBER** [directus/directus#1286]
## Version Info
  - Directus version and branch: 6c1b811  
  - PHP version: 5.6.25
  - MySQL version: 5.7.14
  - Web server: Apache 2
  - OS name and version: Windows 10 (WAMP)
  - Chrome / Firefox on Windows 10

## Expected Behavior
Form items should fit their content and display nicely.

## Actual Behavior
The item's width is fixed, so some content is hidden or button design broken.

## Steps to Reproduce
You can see it on Login page and User page.

## Logs or Screenshots
Here in french:
![directus_form_items](https://cloud.githubusercontent.com/assets/2306550/19638747/8c6f665a-99d5-11e6-97d3-3498e24d310b.jpg)

**Comment by WellingGuzman** [comment]
Thanks @JackNUMBER for reporting this. We will work on a fix for this soon.

**Comment by benhaynes** [comment]
Thank you @JackNUMBER for reporting this! We'll certainly have to go back and check for any places where longer translations break the initial design. I've resolved these two and checked for others, if any others appear let me know!

We're working on a design refresh for an upcoming version... we'll make sure this is considered for that subversion.
