### ISSUE TITLE
Create model "Image" result in Forbidden error

### ISSUE THREAD

**Issue by BaptisteHouques** [directus/directus#12870]
### Describe the Bug

When I try creating a new model called Image, try adding a new field and register, I got a FORBIDDEN error.
![Image_model-forbidden](https://user-images.githubusercontent.com/65606239/164176544-cc3eaa2c-1058-4cc7-bc09-c1f00cb58166.PNG)

### To Reproduce

Go to Data Model, create a new model named Image (exactly like that), click next and finish setup.
Then click Create Field, choose one (Input in the exemple), enter a Key and Save.
For me it's result in a forbidden error.
![Image_model-forbidden](https://user-images.githubusercontent.com/65606239/164177549-4eaf207a-a173-4171-bcbe-f2c1e7f35003.PNG)

### Errors Shown

{
  "errors": [
    {
      "message": "You don't have permission to access this.",
      "extensions": {
        "code": "FORBIDDEN"
      }
    }
  ]
}

### What version of Directus are you using?

9.9.0

### What version of Node.js are you using?

16.14.2

### What database are you using?

MySQL 5.7.36

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally

**Comment by azrikahar** [comment]
Unfortunately I can't seem to reproduce this issue on my end:

https://user-images.githubusercontent.com/42867097/164202508-71ba62fc-9889-407f-acdc-29c438577009.mp4

With that said, seeing that your Image collection does not show the ID field, I'm suspecting this is related to schema cache. Would you mind trying the following from your end:

1. Start fresh (delete that Image collection and restart Directus)
2. Create the Image collection
3. Use this endpoint to clear the cache: https://docs.directus.io/reference/system/utilities/#clear-the-internal-cache (make sure to use admin credentials)
4. Refresh the browser when viewing data model
5. See whether the ID field appears, as this might be the sign that something is wrong already if it's missing
6. Create a field

**Comment by azrikahar** [comment]
@BaptisteHouques No worries! Actually there are instances where the cache _should_ be cleared by Directus itself, but it doesn't, thus potentially causing the error you had faced. Not sure if that is what's happening here, but do keep us posted if it ever happens again!

**Comment by BaptisteHouques** [comment]
This bug is still annoying :/. I've delete & recreate the project (with mysql in utf8_general_ci) and every time I create a model **with a capital letter as 1st character** this probleme appears. And now the refresh & clear doesn't resolve it :/.
