### ISSUE TITLE
exception 'ErrorException' with message 'Declaration of Directus...

### ISSUE THREAD

**Issue by Rsmith919** [directus/directus#1290]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests please use the [Directus FeatHub](http://feathub.com/directus/directus) to make a new request or vote for existing ones, or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues.

## Version Info
  - Directus version and branch: **6c1b81130b3dcdd42e6d0f9ddf0801a36be1eb50**
  - PHP version: **5.6.27**
  - MySQL version: **5.5.52**
  - Web server: (Ex. Apache, nginx or IIS?)  Apache
  - OS name and version:  Debian Linux Jessie 

## Expected Behavior
Functional Site

## Actual Behavior
mod_rewrite installed = No despite being installed and testing.

Server Error Occurred when logging in.

## Steps to Reproduce
 1. Clean install 
 2. Attempt to log in.
 3. 

## Logs or Screenshots
![capture](https://cloud.githubusercontent.com/assets/7915265/19870876/c200c5e4-9f6f-11e6-8355-774a7f873034.PNG)

Logs error message:

ERROR - 2016-10-31T16:16:51-04:00 - exception 'ErrorException' with message 'Declaration of Directus\Db\TableGateway\AclAwareTableGateway::makeTableGatewayFromTableName() should be compatible with Directus\Db\TableGateway\BaseTableGateway::makeTableGatewayFromTableName($table, $adapter)' in /var/www/html/directus/api/core/Directus/Db/TableGateway/AclAwareTableGateway.php:0
Stack trace:
#0 /var/www/html/directus/vendor/composer/ClassLoader.php(412): Directus\Exception\ExceptionHandler->handleError(2048, 'Declaration of ...', '/var/www/html/d...', 0, Array)
#1 /var/www/html/directus/vendor/composer/ClassLoader.php(412): Composer\Autoload\includeFile()
#2 /var/www/html/directus/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/var/www/html/d...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Directus\\Db\\Tab...')
#4 /var/www/html/directus/api/core/Directus/Db/TableGateway/DirectusTablesTableGateway.php(9): spl_autoload_call('Directus\\Db\\Tab...')
#5 /var/www/html/directus/vendor/composer/ClassLoader.php(412): include('/var/www/html/d...')
#6 /var/www/html/directus/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/var/www/html/d...')
#7 [internal function]: Composer\Autoload\ClassLoader->loadClass('Directus\\Db\\Tab...')
#8 /var/www/html/directus/api/core/Directus/Bootstrap.php(328): spl_autoload_call('Directus\\Db\\Tab...')
#9 [internal function]: Directus\Bootstrap::acl(NULL)
#10 /var/www/html/directus/api/core/Directus/Bootstrap.php(51): call_user_func('Directus\\Bootst...', NULL)
#11 /var/www/html/directus/api/api.php(132): Directus\Bootstrap::get('acl')
#12 /var/www/html/directus/index.php(13): require('/var/www/html/d...')
#13 {main}
ERROR - 2016-10-31T16:16:51-04:00 - exception 'ErrorException' with message 'Declaration of Directus\Db\RowGateway\AclAwareRowGateway::makeRowGatewayFromTableName() should be compatible with Directus\Db\RowGateway\BaseRowGateway::makeRowGatewayFromTableName($table, $adapter, $primaryKeyColumn = 'id')' in /var/www/html/directus/api/core/Directus/Db/RowGateway/AclAwareRowGateway.php:18
Stack trace:
#0 /var/www/html/directus/api/core/Directus/Db/RowGateway/AclAwareRowGateway.php(18): Directus\Exception\ExceptionHandler->handleError(2048, 'Declaration of ...', '/var/www/html/d...', 18, Array)
#1 /var/www/html/directus/vendor/composer/ClassLoader.php(412): include('/var/www/html/d...')
#2 /var/www/html/directus/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/var/www/html/d...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Directus\\Db\\Row...')
#4 /var/www/html/directus/api/core/Directus/Db/TableGateway/AclAwareTableGateway.php(52): spl_autoload_call('Directus\\Db\\Row...')
#5 /var/www/html/directus/api/core/Directus/Db/TableGateway/DirectusTablesTableGateway.php(17): Directus\Db\TableGateway\AclAwareTableGateway->__construct(Object(Directus\Acl\Acl), 'directus_tables', Object(Directus\Db\Connection))
#6 /var/www/html/directus/api/core/Directus/Bootstrap.php(328): Directus\Db\TableGateway\DirectusTablesTableGateway->__construct(Object(Directus\Acl\Acl), Object(Directus\Db\Connection))
#7 [internal function]: Directus\Bootstrap::acl(NULL)
#8 /var/www/html/directus/api/core/Directus/Bootstrap.php(51): call_user_func('Directus\\Bootst...', NULL)
#9 /var/www/html/directus/api/api.php(132): Directus\Bootstrap::get('acl')
#10 /var/www/html/directus/index.php(13): require('/var/www/html/d...')
#11 {main}

**Comment by WellingGuzman** [comment]
Hello @Rsmith919, I see you are using the build version, can you please use the `development` or `master` branch?

We are releasing the a new version patching this issues.

I'm closing it as it's being fixed, but I'm aware of the problem on the build branch, and I'm going to release as soon as possible today.

Thanks for letting us know about this issue.
