### ISSUE TITLE
Enable CORS [setting custom headers]

### ISSUE THREAD

**Issue by michieltjuh11** [directus/directus#1291]
As of now I got a small hack going for me witch is quite nice ^^.
Though I want to make a nice and clean implementation of it.

Things it should do:
- [ ] Enable via settings
- [ ] Configurable via settings (add custom headers and what not)
- [ ]  Handle preflight requests

**Comment by WellingGuzman** [comment]
Thanks @michieltjuh11, I assume this all set. 👍
