### ISSUE TITLE
Creating Table with German Umlaut (UTF-8) results in error

### ISSUE THREAD

**Issue by andreasotto** [directus/directus#1295]
Trying to create a table with a name which contains special chars like ä ö or ü (like Ernährung) results in an erroneous table name with underscore instead of correct letters. 
The underlying database is utf-8. Creating tables manually from shell using mysql cli with utf-8 letters works as expected. Are there any settings in directus which i can check? Creating table names with utf-8 is essentially for me.

**Comment by benhaynes** [comment]
Thanks @andreasotto – a lot of users were adding table/column names that were invalid so we added a auto-formatter that is a bit too strict. We're resolving this in the next release of Directus. In the meantime you can add/rename tables/columns directly in the database.

Appreciate you taking the time to report this!

**Comment by andreasotto** [comment]
Adding such a table directly in the database results in a red warning Alert
"Server Error" without further information while trying to add an item to
the table. Though that is not a solution. Any chances for a quick
workaround?

Am 07.11.2016 3:45 nachm. schrieb "Ben" <notifications@github.com>:

**Comment by WellingGuzman** [comment]
Hello @andreasotto, that's odd, we are curious was causing you the issue, I have tried with german characters before and it works, but again, I'm more interested in your issue to it can be solved.

Is there any log file in `api/logs`? if so, can you share it?

**Comment by andreasotto** [comment]
I just tested again, creating a table name with an umlaut:

```
mysql> create table Täst like Categories;
Query OK, 0 rows affected (0.00 sec)

```

In the api/logs directory error messages begin to scroll:

```
ERROR - 2016-11-07T14:48:58-05:00 - exception 'ErrorException' with message 'Declaration of Directus\Db\TableGateway\AclAwareTableGateway::makeTableGatewayFromTableName() should be compatible with Directus\Db\TableGateway\BaseTableGateway::makeTableGatewayFromTableName($table, $adapter)' in /var/www/bolt/api/core/Directus/Db/TableGateway/AclAwareTableGateway.php:0
Stack trace:
#0 /var/www/bolt/vendor/composer/ClassLoader.php(412): Directus\Exception\ExceptionHandler->handleError(2048, 'Declaration of ...', '/var/www/bolt/a...', 0, Array)
#1 /var/www/bolt/vendor/composer/ClassLoader.php(412): Composer\Autoload\includeFile()
#2 /var/www/bolt/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/var/www/bolt/v...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Directus\\Db\\Tab...')
#4 /var/www/bolt/api/core/Directus/Db/TableGateway/DirectusTablesTableGateway.php(9): spl_autoload_call('Directus\\Db\\Tab...')
#5 /var/www/bolt/vendor/composer/ClassLoader.php(412): include('/var/www/bolt/a...')
#6 /var/www/bolt/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/var/www/bolt/v...')
#7 [internal function]: Composer\Autoload\ClassLoader->loadClass('Directus\\Db\\Tab...')
#8 /var/www/bolt/api/core/Directus/Bootstrap.php(328): spl_autoload_call('Directus\\Db\\Tab...')
#9 [internal function]: Directus\Bootstrap::acl(NULL)
#10 /var/www/bolt/api/core/Directus/Bootstrap.php(51): call_user_func('Directus\\Bootst...', NULL)
#11 /var/www/bolt/api/api.php(132): Directus\Bootstrap::get('acl')
#12 {main}
```

Then i went to the access rights page and enabled access for that table (view, edit, ..). In the log file the following errors occur:

```
[Next exception 'Zend\Db\Adapter\Exception\InvalidQueryException' with message 'Statement could not be executed (HY000 - 1300 - **Invalid utf8 character string**: 'T`\xC3`\xA4`st')' in /var/www/bolt/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:245
Stack trace:
#0 /var/www/bolt/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(233): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#1 /var/www/bolt/api/core/Directus/Db/TableGateway/BaseTableGateway.php(553): Zend\Db\TableGateway\AbstractTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#2 /var/www/bolt/api/core/Directus/Db/TableGateway/AclAwareTableGateway.php(167): Directus\Db\TableGateway\BaseTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#3 /var/www/bolt/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(208): Directus\Db\TableGateway\AclAwareTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#4 /var/www/bolt/api/core/Directus/Db/TableGateway/RelationalTableGateway.php(711): Zend\Db\TableGateway\AbstractTableGateway->selectWith(Object(Zend\Db\Sql\Select))
#5 /var/www/bolt/api/api.php(724): Directus\Db\TableGateway\RelationalTableGateway->getEntries(Array)
#6 [internal function]: {closure}('**T\xC3\xA4st**')
#7 /var/www/bolt/vendor/slim/slim/Slim/Route.php(436): call_user_func_array(Object(Closure), Array)
#8 /var/www/bolt/vendor/slim/slim/Slim/Slim.php(1305): Slim\Route->dispatch()
#9 /var/www/bolt/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#10 /var/www/bolt/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#11 /var/www/bolt/vendor/slim/slim/Slim/Slim.php(1254): Slim\Middleware\MethodOverride->call()
#12 /var/www/bolt/api/api.php(1696): Slim\Slim->run()
#13 {main}](url)
```
and

```
Next exception 'RuntimeException' with message 'This query failed: SELECT `**Täst**`.`id` AS `id`, `Täst`.`active` AS `active`, `Täst`.`title` AS `title` FROM `Täst` WHERE `T``?``?``st`.`active` IN ('1', '2') ORDER BY `id` ASC LIMIT 200 OFFSET 0' in /var/www/bolt/api/core/Directus/Db/TableGateway/AclAwareTableGateway.php:170
Stack trace:
#0 /var/www/bolt/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(208): Directus\Db\TableGateway\AclAwareTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#1 /var/www/bolt/api/core/Directus/Db/TableGateway/RelationalTableGateway.php(711): Zend\Db\TableGateway\AbstractTableGateway->selectWith(Object(Zend\Db\Sql\Select))
#2 /var/www/bolt/api/api.php(724): Directus\Db\TableGateway\RelationalTableGateway->getEntries(Array)
#3 [internal function]: {closure}('T\xC3\xA4st')
#4 /var/www/bolt/vendor/slim/slim/Slim/Route.php(436): call_user_func_array(Object(Closure), Array)
#5 /var/www/bolt/vendor/slim/slim/Slim/Slim.php(1305): Slim\Route->dispatch()
#6 /var/www/bolt/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#7 /var/www/bolt/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#8 /var/www/bolt/vendor/slim/slim/Slim/Slim.php(1254): Slim\Middleware\MethodOverride->call()
#9 /var/www/bolt/api/api.php(1696): Slim\Slim->run()
#10 {main}
```
In the same moment the following message appears in the page:

<img width="400" alt="testprojekt tast" src="https://cloud.githubusercontent.com/assets/2129515/20073406/6f928294-a52c-11e6-9f3f-efa7a1188681.png">

The operating system is a plain vanilla debian, freshly installed

```
# uname -a
Linux webtest 4.2.2-1-pve #1 SMP Mon Oct 5 18:23:31 CEST 2015 x86_64 GNU/Linux
# export
declare -x LANG="de_DE.UTF-8"
...
```

If you need further information i will send them. Thank you very much for having an eye on that.

**Comment by WellingGuzman** [comment]
Thanks for the information.

What I can say for looking at the logs it seems you are using the build branch or the last release. 

So what version/commit/branch are you using? There's s error that was fixed but isn't released yet.

Im looking at the rest.

**Comment by andreasotto** [comment]
I installed 2 days ago as zip download from github.

**Comment by WellingGuzman** [comment]
@andreasotto correct, that's one issue there the build branch has that bug in there, can you please use the development branch? we are trying to make a release as soon as possible, but we keep fixing some minor bugs.

**Comment by WellingGuzman** [comment]
@andreasotto also this is a MySQL issue, or probably a configuration issue with our connection.

```
HY000 - 1300 - Invalid utf8 character string: 'T`\xC3`\xA4`st'
```

Again thanks for all this info, I'm taking care of this right now and see what we can do for this release.

**Comment by andreasotto** [comment]
Great, thank you very much. I'll retry with the dev build right now and let you know.

**Comment by andreasotto** [comment]
unfortunately the development build can't be installed:

On the 4th page (`/installation/index.php?step=4`) if you click the "INSTALL" Button the following occurs in apache's error.log (http 500 error):

```
[Mon Nov 07 21:09:40.340649 2016] [:error] [pid 10203] [client 93.216.52.123:52148] PHP Warning:  array_merge(): Argument #2 is not an array in /var/www/ssl/htdocs/cms/vendor/directus/migrations/lib/Ruckusing/Adapter/MySQL/MySQLTableDefinition.php on line 175, referer: https://ssl...../cms/installation/index.php?step=4
[Mon Nov 07 21:09:40.352321 2016] [:error] [pid 10203] [client 93.216.52.123:52148] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fitapp.directus_settings' doesn't exist' in /var/www/ssl/htdocs/cms/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:240\nStack trace:\n#0 /var/www/ssl/htdocs/cms/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(240): PDOStatement->execute()\n#1 /var/www/ssl/htdocs/cms/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(291): Zend\\Db\\Adapter\\Driver\\Pdo\\Statement->execute()\n#2 /var/www/ssl/htdocs/cms/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(258): Zend\\Db\\TableGateway\\AbstractTableGateway->executeInsert(Object(Zend\\Db\\Sql\\Insert))\n#3 /var/www/ssl/htdocs/cms/api/core/Directus/Util/Installation/InstallerUtils.php(153): Zend\\Db\\TableGateway\\AbstractTableGateway->insert(Array)\n#4 /var/www/ssl/htdocs/cms/installation/includes/Steps/ConfirmStep.php(66): Directus\\Util\\Installation\\InstallerUtils::addDefaultSettings(Array, '/var/www/ss in /var/www/ssl/htdocs/cms/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php on line 245, referer: https://ssl....../cms/installation/index.php?step=4
```

The MySQL database has been created new and has been empty.

Now there is only one table in the database:

```
mysql> show tables;
+----------------------------+
| Tables_in_fitapp           |
+----------------------------+
| directus_schema_migrations |
+----------------------------+
1 row in set (0.00 sec)
```

Any ideas how to workaround that bug? In the build release that was working fine.

**Comment by WellingGuzman** [comment]
That's not good, I'm on it, it should be a fix for this bug soon enough. I will let you know.

**Comment by WellingGuzman** [comment]
Hey @andreasotto I pushed a patch for this bug with this commit https://github.com/directus/directus/commit/78b17a2ab536a3e68901f07d056c9009fb921b62

Let me know if that works for you too. make sure to delete or rename your current `config.php` and `configuration.php` if needed.

**Comment by andreasotto** [comment]
That worked 👍 
(A minor thing: the self check in the last steps says `mod_rewrite No` but thats wrong, it's enabled and working well for other vhosts.)

**Comment by benhaynes** [comment]
Good to hear! The `mod_rewrite` issue has been ongoing... if you know of a better way to test/check that module we'd love to get this resolved! Thanks @andreasotto

**Comment by andreasotto** [comment]
I never wrote a routine to check that, but i could imagine that something like this could work:

in .htaccess set environment var and check later in script

```
<IfModule mod_rewrite.c>
    SetEnv HTTP_REWRITE_ENABLED On
    ...

```

then check with
`array_key_exists('HTTP_REWRITE_ENABLED', $_SERVER);`

**Comment by WellingGuzman** [comment]
The thing is that it won't work with nginx locations, although it says `mod_rewrite` it meant for any rewrite available.

If you can tell me any steps to replicate it, I will love to fix it.

We test by creating a endpoint and if the endpoint return data AND status 200 =, it means it's working, no matter if it's apache mod_rewrite or nginx locations.

We probably can add that into the conditions. but don't know if it will make any difference.

**Comment by WellingGuzman** [comment]
About the `mod_rewrite` check, we need to update that title, because it doesn't actually check for whether the module is enable or not, but rather it checks for whether the routing is working.

In 6.3.x Directus doesn't allow to create table with special characters, by special anything out of alphanumerics, but Directus is going to support it in 6.4.x.

Although you are able to create the table in the database then add permissions accordingly, and it should be set.

**Comment by WellingGuzman** [comment]
We update how we check for "routing" what we are still calling `mod_rewrite` check.

We actually check for the the routing if it's working by trying to ping the API.

About using umlaut (UTF8) now it's possible by changing the `charset` in your `api/config.php` file to `utf8mb4`.
