### ISSUE TITLE
Translations for singleton collection not being retrieved

### ISSUE THREAD

**Issue by lluishi93** [directus/directus#12965]
### Describe the Bug

Once https://github.com/directus/directus/issues/12954 (duplicate of https://github.com/directus/directus/issues/12831) was solved in 9.9.1, now the translations are not being loaded at all when the collection has the singleton flag activated.

### To Reproduce

1. Create a singleton collection
2. Assign a translations field to it
3. Create some translations items
4. Visualize the singleton item and check that no translations are being loaded

### What version of Directus are you using?

9.9.1

### What version of Node.js are you using?

16.14.0

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by Nitwel** [comment]
I tried to reproduce this bug but was not able to. Could you give more information on that one?

**Comment by lluishi93** [comment]
In my case, I think it has to do with the fact that when we get into the singleton item, the URL does not have the ID as the last path param:

/admin/content/conf_shop_the_look

**Comment by Nitwel** [comment]
Thats always the case with singletons. 😄

**Comment by azrikahar** [comment]
I can't seem to reproduce this issue on 9.11.1 as well:

https://user-images.githubusercontent.com/42867097/170462687-5b2f730c-6399-4a37-a909-19a784cbcf8a.mp4

so I'll close this for now 👍
