### ISSUE TITLE
Inserting image in wysiwyg-Editor only works once

### ISSUE THREAD

**Issue by andreasotto** [directus/directus#1297]
Current development build:

Inserting an image into the text within a wysiwyg-Field only works for one time. Afterwards, tapping the insert_image or embed_video link doesn't work again.

Are there other wyswyig-Editors ready to use with directus? (as the current implementation seems to have at least some minor flaws) - or is there an easy to start skeleton for such a contribution?

**Comment by benhaynes** [comment]
Hey @andreasotto – we can look into this. And yes, you can easily create a new UI... or fix this one ;)

Here are the docs for creating or updating UIs:
https://github.com/directus/docs/tree/master/05-custom-uis

**Comment by andreasotto** [comment]
Thank you very much. Just having a look into the existing UIs. I am in need for an input for block content, for example Textlabels, Lists, Images, Blockquotes etc. and i like to approach from the Sir Trevor JS, example here:

![Example](https://github.com/madebymany/sir-trevor-js/blob/master/examples/sir-trevor.gif)

I will try to find out more and see if i'm able to set something up ...

**Comment by WellingGuzman** [comment]
Hey @andreasotto That looks amazing, any help you may need to get this done as UI, let us know to help as much as we can :)

**Comment by WellingGuzman** [comment]
This could also be a good idea for an extension for designing pages :)

**Comment by benhaynes** [comment]
@andreasotto – Yes! That would be amazing, that's exactly the type of editor we're looking to move to (but have no time yet). I imagine the only complex part would be getting it to play nicely with Directus Images (for inserting images/embeds)... but I'm sure we can figure it out.

I'd love to see what you come up with (if you have time) – very exciting!

**Comment by benhaynes** [comment]
Here's the other ticket regarding this – it has a bunch of other options for WYSIWYG libraries:

https://github.com/directus/directus/issues/1242

**Comment by ricricucit** [comment]
Is sir-trevor being integrated?

**Comment by WellingGuzman** [comment]
This interface will replace the current wysiwyg library, which means it's not worth trying to fix it.

I'm sorry I'm closing this, because as soon as we change to the new interface, this may be not an issue, or this still an issue that we are not longer trying to solve as the library itself has some issue that we are not willing to take time to solve it, but to switch to a new library.
