### ISSUE TITLE
Can't enter primary key on singleton collection

### ISSUE THREAD

**Issue by rashidpathiyil** [directus/directus#12985]
### Describe the Bug

Can't enter primary key and can't save without primary key on singleton collection with primary key field type as manually entered string.

### To Reproduce

- Create a singleton collection with primary key field type as manually entered string.
- Add some fields to test
- Try to update the collection

### Errors Shown

![image](https://user-images.githubusercontent.com/15140041/164972646-6a129e70-b9e0-419d-86d7-be1567cae03a.png)

### What version of Directus are you using?

9.9.1

### What version of Node.js are you using?

16.14.0

### What database are you using?

Postgres 13

### What browser are you using?

Edge

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment]
Seems to be due to singletons doesn't have the typical `+` primary key on new records, thus the condition here becomes true and sets the primary key as readonly:

https://github.com/directus/directus/blob/728f9ed3a7f743a8edbf42351aa501eed134c982/app/src/components/v-form/v-form.vue#L258-L270
