### ISSUE TITLE
Homestead vagrant box

### ISSUE THREAD

**Issue by cedricve** [directus/directus#1299]
Hey,

This is really a promising headless CMS. Unfortunately I don't get it working on the widely used vagrant box Homestead. Which is really disappointing as it's popular for developers.

I'm getting blocked with following installation errors:

1. mod_rewrite isn't found (but it's builtin in Nginx).
2. I have to disable strict mode of mysql (but I'm not able to do this).

Would like to see this solved for a lot of my projects, I think the combo of my AngularJS application with directus would be a great match!

Thanks for reading, and maybe solving my issues.

Cédric

**Comment by WellingGuzman** [comment]
Hey @cedricve,

Thanks for your interest in Directus, let's help you out as much as I can.

> 1. mod_rewrite isn't found (but it's builtin in Nginx).
It's built int, but as nginx doesn't support .htaccess, you have to create the locations on your server config file. You can read mroe here: https://github.com/directus/docs/blob/master/04-developer/02-configuration-nginx.md

> 2. I have to disable strict mode of mysql (but I'm not able to do this).

How are you not being able to disable it? a project requirements?

**Comment by cedricve** [comment]
@WellingGuzman  great support, I'm starting to like this.

1. mod_rewrite

I have this solved now by updating the nginx conf.

2. disable strict mysql on Homestead

I followed this tutorial: https://mattstauffer.co/blog/how-to-disable-mysql-strict-mode-on-laravel-forge-ubuntu. Looks like I've ended up with following config file for MySQL (/etc/mysql/my.cnf). I've just appended the sql mode attribute from the tutorial, and restarted the mysqld service. Installation has been completed now.

`#
# The MySQL database server configuration file.
#
# You can copy this to one of:
# - "/etc/mysql/my.cnf" to set global options,
# - "~/.my.cnf" to set user-specific options.
#
# One can use all long options that the program supports.
# Run program with --help to get a list of available options and with
# --print-defaults to see which it would actually understand and use.
#
# For explanations see
# http://dev.mysql.com/doc/mysql/en/server-system-variables.html

#
# * IMPORTANT: Additional settings that can override those from this file!
#   The files must end with '.cnf', otherwise they'll be ignored.
#

!includedir /etc/mysql/conf.d/
!includedir /etc/mysql/mysql.conf.d/

[mysqld]
sql_mode=ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
`

Thank you for your help!

**Comment by WellingGuzman** [comment]
Great @cedricve, that's good news. anything else let us know.
