### ISSUE TITLE
A few questions about directus

### ISSUE THREAD

**Issue by cedricve** [directus/directus#1300]
Hey,

I've evaluated the CMS, and I'm feeling comfortable with it. The design is really great and it contains most of the functionality my project requires. Good job.

I have a few questions though:

* Is there any way to have public API endpoints? I will have pages or items which should be available for every visitor, authenticating those request is overkill.
* Stability: as far I've seen the system is stable, however sometimes I get strange errors (at random times), are you aware of this?
* User groups: this is not very intuitive, I've created a new group called Editor, added some rights, and tried to signin. It seems to work but I receive lots of errors (no permissions). I've solved this by granting most of permissions on the directus internal tables. However this isn't intuitive and requires some debugging to setup.
* Bookmarks: what's the purpose for this? It's not completely clear for me.
* Is this a funded project, how many developers? If I will start using this I want to have some assurance. 
* Do you develop custom features (fixed price, or hour rate)?
* Custom endpoints: I'v seen that there is a possibility to add custom endpoints to the API. However this isn't documented so far. Are you planning to do this?

Thank you for this system, I'm very hopeful!

Cédric

**Comment by WellingGuzman** [comment]
Hey @cedricve, glad that you are enjoy Directus.

> Is there any way to have public API endpoints? I will have pages or items which should be available for every visitor, authenticating those request is overkill.

You have to authenticate any requests, but we can work on something about this.

> Stability: as far I've seen the system is stable, however sometimes I get strange errors (at random times), are you aware of this?

What strange errors? You can open ticket about specifics issue and we can address them, sometimes there can strange errors.

> User groups: this is not very intuitive, I've created a new group called Editor, added some rights, and tried to signin. It seems to work but I receive lots of errors (no permissions). I've solved this by granting most of permissions on the directus internal tables. However this isn't intuitive and requires some debugging to setup.

What errors? we can work on it if you detailed all of them. Yes, if you are logged in, with a new group there's some internal table that need to be set for the user to work with, we have been working to make some pages clear in the new few minor version.

> Bookmarks: what's the purpose for this? It's not completely clear for me.

You can save a state of a listing page, let's say you have a `posts` table, and you want a bookmark all posts that are in `draft` for quick access, you save a bookmark of all the posts with `draft` status.

> Is this a funded project, how many developers? If I will start using this I want to have some assurance.

We are not getting anywhere, We guaranteed an active development for a long time.

> Do you develop custom features (fixed price, or hour rate)?

Yes, we do.

> Custom endpoints: I'v seen that there is a possibility to add custom endpoints to the API. However this isn't documented so far. Are you planning to do this?

Yes, we have planned to update our docs as much as possible in the new few weeks.

**Comment by benhaynes** [comment]
Hey @cedricve – just to follow up on a few of the points @WellingGuzman made:

We're in the process of addressing some UX/UI issues in the next visual overhaul of the platform. The admin side especially should be much more intuitive.

Bookmarks are quite useful for the more complex filters:
`Active Projects from 2015 with author containing %cedric% ordered by views, descending` can be saved as "Cedric's 2015 Projects" for example.

> We are not getting anywhere
Welling means that "we are no going anywhere" ;) ... We have a small but dedicated team working full-time and a growing number of open-source contributors. There are a lot of big releases on the horizon and our roadmap extends to the middle of next year already. Ten years in and we are just getting started.

If you're interested in custom features you can contact RANGER (the managing entity of Directus) at:
info@rngr.org

We'd love *any* input (criticism or praise) from users like yourself – that's how we know what to do next. Also, we can design and develop faster as our team and community grows – helping us gain exposure through social media (`@directus`) is a huge help at this stage.

Thank you very much for taking the time to write this post!

**Comment by WellingGuzman** [comment]
> Welling means that "we are no going anywhere" ;)

Oh boy haha, well yeah, thanks you replied on time..

**Comment by cedricve** [comment]
@WellingGuzman @benhaynes great to know you guys. I'll send some pull request myself, if necessary, so count me in. 👍 

To be honest I'll try to use this for one of my clients, and will combo it with AngularJS. I'll keep you guys posted how it goes. If this is succesfull, and my clients is comfortable with the interface too, this will become my preferred headless CMS.

Thank you guys!

**Comment by WellingGuzman** [comment]
@cedricve I will close this ticket. Any further question please join us on our Slack http://slack.getdirectus.com/
