### ISSUE TITLE
Compact Table Spacing cuts text off

### ISSUE THREAD

**Issue by supermx1** [directus/directus#13010]
### Describe the Bug

![Screenshot 2022-04-26 at 1 45 42 PM](https://user-images.githubusercontent.com/9326922/165302787-54445993-1c6c-46e1-9f6f-05dc2750e36a.jpg)

### To Reproduce

Make sure you have a lot of rows in a table and then change the table spacing to compact. 

### Errors Shown

None

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

16

### What database are you using?

MySQL

### What browser are you using?

Chrome, Brave

### How are you deploying Directus?

Locally

**Comment by azrikahar** [comment]
> Make sure you have a lot of rows in a table and then change the table spacing to compact.

Would you mind sharing what is the type of field and display configured? 

Seems like other columns like the user email isn't being truncated, so I'm inclined to believe this reproduction step is a bit incomplete here as I was not able to reproduce it at the moment.

**Comment by rijkvanzanten** [comment]
@azrikahar It's the related-values display 👍🏻 
<img width="510" alt="CleanShot 2022-04-26 at 10 11 29@2x" src="https://user-images.githubusercontent.com/9141017/165319370-d98dbd00-bf5d-4fee-8a73-9089fcac1187.png">

**Comment by rijkvanzanten** [comment]
It's this height that causes it to overflow on tabular compact:

https://github.com/directus/directus/blob/6828a74d4e0b39807a3b70ac96450e5c9f82db3b/app/src/views/private/components/render-template/render-template.vue#L128

However, removing that causes some styling glitches elsewhere, like in here:

<img width="925" alt="CleanShot 2022-04-26 at 10 15 09@2x" src="https://user-images.githubusercontent.com/9141017/165320202-d7d04ba3-05ed-41d2-a5d8-dc6218e7bed4.png">

We should remove the `height: 100%`, and check the other uses of `render-template` to ensure there's no other styling glitches remaining from that change

**Comment by ykabusalah** [comment]
Hello, could I claim this issue and attempt fixing it?

**Comment by benhaynes** [comment]
Of course! We've assigned you, feel free to reach out over [Discord](https://directus.chat) if you have any questions along the way.

**Comment by sksar** [comment]
```
.render-template {
  line-height: 1;
} 
```
This fixes it. However I am not sure how it effects other things.

**Comment by fa-briz-io** [comment]
I'm using below fix, line-height still clips some character like the letter "g". By adding the class "cell" it does not affect the inputs. I'm sure its not the right fix, but for someone looking for a quick fix like me, it seem to be working without affecting something else. Just add this in the custom css under settings.

`.cell .render-template {
    height: auto!important;
} `
