### ISSUE TITLE
Deleting a huge file twice kills directus

### ISSUE THREAD

**Issue by eXsiLe95** [directus/directus#13029]
### Describe the Bug

When deleting a huge file (>10Mbit) and simultaneously deleting the same file again, Directus will throw an exception and terminate. This issue first occurred because the deletion process was shown as finished, but the files were still shown. When trying to delete the files (again), directus stopped working.

### To Reproduce

Upload multiple files. At least one file needs to be bigger than 10Mbit. Select multiple files for deletion, including the bigger file. Click on delete, and at the same time in another tab, delete the bigger file as well.

### Errors Shown

```
control-expose-headers":"Content-Range","content-type":"image/png","accept-ranges":"bytes","cache-control":"private, max-age=1800","content-length":23718}},"responseTime":2457,"msg":"request completed"}
node:events:368
throw er; // Unhandled 'error' event
^



Error: ENOENT: no such file or directory, open '/directus/uploads/04b6451c-d3df-4369-b71b-e64b47bb6de0.jpg'
Emitted 'error' event on ReadStream instance at:
at emitErrorNT (node:internal/streams/destroy:157:8)
at emitErrorCloseNT (node:internal/streams/destroy:122:3)
at processTicksAndRejections (node:internal/process/task_queues:83:21) {
errno: -2,
code: 'ENOENT',
syscall: 'open',
path: '/directus/uploads/04b6451c-d3df-4369-b71b-e64b47bb6de0.jpg'
}
```

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16.13.1

### What database are you using?

Postgres 10

### What browser are you using?

Chrome (Mac)

### How are you deploying Directus?

Docker (AWS EC2)

**Comment by eXsiLe95** [comment]
I'm going to try and reproduce this issue in a newer directus version as well in the next few days. I'm a little busy atm, so I'm not able to test it right away...

**Comment by br41nslug** [comment]
I was unable to reproduce this specific bug on v9.9.1 or v9.10.0 using the given steps and also tried scripting the delete request to be fired at virtually the same time. Tested with Docker on Linux and Windows using 10 images between 800kb and 50mb.
