### ISSUE TITLE
Trouble with permissions when following QuickStart Guide.

### ISSUE THREAD

**Issue by Nevaero** [directus/directus#13030]
### Describe the Bug

Hey guys, 

I've decided to try out Directus as a backend framework, so I followed the QuickStart guide to the letter.

Then each time I open the url `http://localhost:8055/items/articles`, I get this error:

`{"errors":[{"message":"You don't have permission to access this.","extensions":{"code":"FORBIDDEN"}}]}`

Same thing with Paw. Of course, I've googled it, but few people seem to have trouble with this, and when they do, I try their solution, to no avail. 

Did I do something wrong? I'm using the latest version of Directus, with the latest version of NPM.

### To Reproduce

- run `npm init directus-project ./ `within the target folder
- choose SQLite (had the same issue with PostgreSQL)
- select the default DB path
- set an admin user
- run `npx directus start` and open the corresponding URL in Safari.
- log in with the admin, then create an Articles collection with a title field
- create an item with a title
- set the permissions for the Public role to perform GET requests on this collection.

### Errors Shown

In the browser/response in Paw : 

`{"errors":[{"message":"You don't have permission to access this.","extensions":{"code":"FORBIDDEN"}}]}`

In the console:

`GET 403 /items/articles 7ms`

### What version of Directus are you using?

9.9.1

### What version of Node.js are you using?

16.14

### What database are you using?

Postgres 14.2, SQLite 3.38.2

### What browser are you using?

Safari

### How are you deploying Directus?

running locally with npx

**Comment by jaycammarano** [comment]
Hello!
I was wondering if you added the token to your header? Like in [this](https://docs.directus.io/reference/authentication/#login)

**Comment by azrikahar** [comment]
Out of curiosity, would you mind trying `http://localhost:8055/items/Articles` (capital A)?

**Comment by Nevaero** [comment]
Okay, good to know that REST APIs are case sensitive! (it works, and now I feel dumb). 

Thanks a lot! Closing the issue :)

**Comment by azrikahar** [comment]
@Nevaero No worries! To be fair, it has indeed come up before. Will see if there's a way to prevent this confusion in the first place 👍
