### ISSUE TITLE
Notification service does not send emails

### ISSUE THREAD

**Issue by adrianofoschi** [directus/directus#13050]
### Describe the Bug

I create a notification via "hooks" extension.
It works perfectly inside directus, I see the notification but I don't receive any email.
The smtp seems to work perfectly, I tried with reset password procedure.
Do I need to enable something? Is there a way to debug? I have no errors in console.
It works using REST API.

### To Reproduce
Create a new extension hook that calls notification service.
```
export default async ({ schedule }, { services, database, getSchema, logger, env }) => {

	const schema = await getSchema();

	const ns = new services.ItemsService('directus_notifications',{knext: database, schema});
	ns.createOne({
			status: "inbox",
			recipient: "2f66c79e-f9c6-4829-a7a1-cbe20ccaebfd",
			sender: "f5675c29-e9be-48bd-a4fe-85318ae8f431",
			subject: "Test email",
			message: "This is a test email",
			collection: "mycollection",
			item: "e51d4c01-687a-448f-b894-af8e085aa80b"
	});
};
```

### Errors Shown

No error in console.

### What version of Directus are you using?

9.9.1

### What version of Node.js are you using?

16

### What database are you using?

Posgres 13

### What browser are you using?

Firefox

### How are you deploying Directus?

Digital Ocean Image

**Comment by adrianofoschi** [comment]
I replaced service initialization as follows and it works.

```
const n = new services.NotificationsService({knext: database, schema: schema});
```

**Comment by azrikahar** [comment]
It is best to use the actual service as well, as this "not a simple item" does hold true to other services as well like FieldsService. 👍 

With that said, #12522 may even remove the need of this custom extension! (unless you're doing more things not included in this snippet of course). Everything seems in order so I'll close this issue for now.
