### ISSUE TITLE
Cannot sort Many-To-Many entries

### ISSUE THREAD

**Issue by jhyle** [directus/directus#1305]
When clicking on the sort-enabling button in a many-to-many list I get the following error:

Error: Uncaught TypeError: this.collection.getTotalCount is not a function File: http://cms.remap-berlin.de/app/core/table/table.view.js?bust=kj389sm0675nj89mfkqv0phkm4 Line:177

Directus v6.3.5 (Lapis Lepus)
PHP 5.6.27-0+deb8u1 (cli) (built: Oct 15 2016 15:53:28)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by WellingGuzman** [comment]
Thanks @jhyle, I will take a look at it later today.

**Comment by jhyle** [comment]
Thank you. Do already plan a new release?

**Comment by WellingGuzman** [comment]
Hey @jhyle expect a release soon, probably by tomorrow.
