### ISSUE TITLE
/auth/request-token cannot be found

### ISSUE THREAD

**Issue by tdiddi** [directus/directus#1306]
## Version Info
  - Directus version: 6.3.5
  - PHP version: 5.5
  - Web server: (Ex. Apache, nginx or IIS?) : Apache
  - OS name and version: Centos / VestaCP hosted

## Expected Behavior
Grabbing the API Key with http://pseudo.url/api/1/auth/request-token

## Actual Behavior
Browser Output:

**Sorry, this page isn't available.**
The page you are looking for could not be found.

I re-installed 2 times now and its still not working for me. Request with the API Key from the Backend are working.

**Comment by WellingGuzman** [comment]
Hey @tdiddi,

To request a user token you have to perform a POST request to `http://pseudo.url/api/1/auth/request-token` with your email and password as data. (`email=myemail@mail.com&password=secret`)

Let me know if that works for you.

**Comment by WellingGuzman** [comment]
You can read a similar here using curl: http://getdirectus.com/api/overview/authentication

**Comment by tdiddi** [comment]
I feel so ashamed :D 
I read the 

> Used with all GET Resources

and used GET in my application...

Now its all working with POST.

Thanks for the fast help!

**Comment by WellingGuzman** [comment]
Great, we will update that part of the docs, so it's not confusing anymore.

Thanks!
