### ISSUE TITLE
gatsby plugin extract-files package

### ISSUE THREAD

**Issue by ashkaptsov** [directus/directus#13068]
### Describe the Bug

Hello, 

can't build the project on Gatsby Cloud for. 

error:
`(node:7498) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./public/" in the "exports" field module resolution of the package at /usr/src/app/www/nodemodules/@directus/gatsby-source-directus/nodemodules/extract-files/package.json.

Update this package.json to use a subpath pattern like "./public/*".
(Use node --trace-deprecation ... to show where the warning was created)`

extract-files package in v.9.0, it should be at least v.10.0 to solve the problem. Changing the version in VScode everything works. But Gatsby cloud doesn't let me build the website...

### To Reproduce

 a

### Errors Shown

(node:7498) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./public/" in the "exports" field module resolution of the package at /usr/src/app/www/nodemodules/@directus/gatsby-source-directus/nodemodules/extract-files/package.json.

Update this package.json to use a subpath pattern like "./public/*".
(Use node --trace-deprecation ... to show where the warning was created)

### What version of Directus are you using?

9

### What version of Node.js are you using?

8.5

### What database are you using?

Postgres

### What browser are you using?

Opera

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Would you mind elaborating on what exactly is failing the build? I believe the deprecation warning shouldn't cause it (as it's a warning), but I could be wrong.

> Changing the version in VScode everything works.

Can you share what is the change you did? It is something along the lines of yarn resolutions or npm overrides, or just installing it as a dependency? `extract-files` seems to be a nested dependency of `gatsby-source-directus`:

```
`-- @directus/gatsby-source-directus@9.9.1 -> .\packages\gatsby-source-directus
  +-- gatsby-source-filesystem@4.2.0
  | `-- gatsby@4.12.1
  |   `-- eslint-plugin-graphql@4.0.0
  |     `-- graphql-config@3.4.1
  |       `-- @graphql-tools/url-loader@6.10.1
  |         `-- extract-files@9.0.0 deduped
  `-- gatsby-source-graphql@4.2.0
    `-- @graphql-tools/links@7.1.0
      `-- apollo-upload-client@14.1.3
        `-- extract-files@9.0.0
```

**Comment by yannickkordel** [comment]
Updating gatsby-source-graphql to latest version seems to fix this issue. https://github.com/gatsbyjs/gatsby/issues/34042

**Comment by ashkaptsov** [comment]
Have checked once more, it was not this failing the build, sorry.  Anyway there is always this warning. 
Would be great if you just update **extract-files**. I do it manually, but gatsby cloud or netlify they just download a package for the build with old version.

P.S. Updating gatsby-source-graphql  doesn't change anything because extract-files package is inside @directus/gatsby-source-directus package
