### ISSUE TITLE
IIS version?

### ISSUE THREAD

**Issue by PolywickStudio** [directus/directus#1307]
- Directus version and branch: (Or commit hash) main branch
  - PHP version: 7.1
  - MySQL version:  7.16
  - Web server: (Ex. Apache, nginx or IIS?) IIS
  - OS name and version: Windows Server 2012 standard.

## Expected Behavior
IIS installation.
Login should work, goes to /api/*

## Actual Behavior
Login doesn't work.
It needs htaccess converted to IIS WebConfig.

## Steps to Reproduce
 1. Install DirectUs on IIS.

## Logs or Screenshots
N/A.

**Comment by WellingGuzman** [comment]
We do not support IIS yet, we haven't had the chance to work on a IIS Server.

@PolywickStudio Do you mind giving us a hand there? I could try to convert it to webconfig, but I will need someone to confirm it is working.

**Comment by raygers** [comment]
Hi

You need to install IIS URL Rewrite from https://www.iis.net/downloads/microsoft/url-rewrite
You can try the following url rewrite rules which were imported from the rewrite rules in the .htaccess 
They need to go into the system.webServer section. On a personal note, I had a better experience running it on xampp on a windows box.

      <rewrite>
            <rules>
                <rule name="Imported Rule 1-1" stopProcessing="true">
                    <match url="^assets" />
                    <action type="None" />
                </rule>
                <rule name="Imported Rule 2" stopProcessing="true">
                    <match url="^extensions/([^/]+)" />
                    <action type="None" />
                </rule>
                <rule name="Imported Rule 3" stopProcessing="true">
                    <match url="^extensions/([^/]+)/assets" />
                    <action type="None" />
                </rule>
                <rule name="Imported Rule 4" stopProcessing="true">
                    <match url="^extensions/([^/]+)/main.js" />
                    <action type="None" />
                </rule>
                <rule name="Imported Rule 5" stopProcessing="true">
                    <match url="^listviews/([^/]+)" />
                    <action type="None" />
                </rule>
                <rule name="Imported Rule 6" stopProcessing="true">
                    <match url="^listviews/([^/]+)/assets" />
                    <action type="None" />
                </rule>
                <rule name="Imported Rule 7" stopProcessing="true">
                    <match url="^listviews/([^/]+)/ListView.js" />
                    <action type="None" />
                </rule>
                <rule name="Imported Rule 8" stopProcessing="true">
                    <match url="^" ignoreCase="false" />
                    <conditions logicalGrouping="MatchAll">
                        <add input="{URL}" pattern="media_auth_proxy/([^/]+)/(.+)$" ignoreCase="false" />
                    </conditions>
                    <action type="Rewrite" url="/media_auth_proxy/index.php" />
                </rule>
                <rule name="Imported Rule 9" stopProcessing="true">
                    <match url="(.*)" ignoreCase="false" />
                    <conditions logicalGrouping="MatchAll">
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" negate="true" />
                        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" negate="true" />
                        <add input="{URL}" pattern="index" ignoreCase="false" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="index.php" />
                </rule>
            </rules>
        </rewrite>


Thanks
Ray

**Comment by PolywickStudio** [comment]
It doesn't work... I've used XMPP instead

**Comment by WellingGuzman** [comment]
I will follow what you did in a future release and try to make it work under IIS.

Any other issue you may have let us know. I myself couldn't try it as I'm not on Windows, but I will get my hands in one to try this myself soon.

Thanks.
