### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by Cammoy** [directus/directus#13098]
### Describe the Bug

Search is case sensitive.

### To Reproduce

`query contributed_articles($query: String) {
    articles(
      filter: {
        title: { _contains: $query }
      }
      sort: ["-sort"]
    ) {
      id
      title
      status
    }
  }`

### Errors Shown

If I search for "article" and its Stored as "Article" then the search does not work as expected

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

14

### What database are you using?

Directus Cloud Service

### What browser are you using?

Chrome / Webkit

### How are you deploying Directus?

Directus Cloud

**Comment by rijkvanzanten** [comment]
Duplicate of https://github.com/directus/directus/discussions/2981, https://github.com/directus/directus/discussions/11459
