### ISSUE TITLE
Combined nested filter rule causes duplicate data due to added JOINs

### ISSUE THREAD

**Issue by jdoig** [directus/directus#13107]
### Describe the Bug

With a certain set of **Read** permissions on my `document` collection, an API query to `/items/document` returns multiple duplicates.

```
$ http -v get https://REDACTED/items/document access_token==REDACTED
GET /REDACTED/items/document?access_token=REDACTED HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: REDACTED
User-Agent: HTTPie/2.4.0


HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Encoding: gzip
Content-Length: 209
Content-Security-Policy: script-src 'self' 'unsafe-eval';worker-src 'self' blob:;child-src 'self' blob:;img-src 'self' data: blob: https://cdn.directus.io;media-src 'self' https://cdn.directus.io;connect-src 'self' https://*;default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';object-src 'none';script-src-attr 'none';style-src 'self' https: 'unsafe-inline'
Content-Type: application/json; charset=utf-8
Date: Tue, 03 May 2022 15:36:07 GMT
Etag: W/"6fa-lgNEW+hrvVXdfYsUTScJCWSkHFQ"
Vary: Accept-Encoding
Vary: Origin, Cache-Control
X-Powered-By: Directus

{
    "data": [
        {
            "author": "26a3109a-5279-4dbe-a392-81ce9eadb769",
            "date_created": "2022-04-28T20:40:59.891Z",
            "date_updated": "2022-05-03T14:58:15.885Z",
            "draft": 16,
            "id": 32,
            "published": 25,
            "user_updated": "9967c52c-175d-4631-b390-97dc961a93df"
        },
        {
            "author": "26a3109a-5279-4dbe-a392-81ce9eadb769",
            "date_created": "2022-04-28T20:40:59.891Z",
            "date_updated": "2022-05-03T14:58:15.885Z",
            "draft": 16,
            "id": 32,
            "published": 25,
            "user_updated": "9967c52c-175d-4631-b390-97dc961a93df"
        },
        {
            "author": "26a3109a-5279-4dbe-a392-81ce9eadb769",
            "date_created": "2022-04-28T20:40:59.891Z",
            "date_updated": "2022-05-03T14:58:15.885Z",
            "draft": 16,
            "id": 32,
            "published": 25,
            "user_updated": "9967c52c-175d-4631-b390-97dc961a93df"
        },
        {
            "author": "26a3109a-5279-4dbe-a392-81ce9eadb769",
            "date_created": "2022-04-28T20:40:59.891Z",
            "date_updated": "2022-05-03T14:58:15.885Z",
            "draft": 16,
            "id": 32,
            "published": 25,
            "user_updated": "9967c52c-175d-4631-b390-97dc961a93df"
        },
        {
            "author": "26a3109a-5279-4dbe-a392-81ce9eadb769",
            "date_created": "2022-04-28T20:40:59.891Z",
            "date_updated": "2022-05-03T14:58:15.885Z",
            "draft": 16,
            "id": 32,
            "published": 25,
            "user_updated": "9967c52c-175d-4631-b390-97dc961a93df"
        },
        {
            "author": "26a3109a-5279-4dbe-a392-81ce9eadb769",
            "date_created": "2022-04-28T20:40:59.891Z",
            "date_updated": "2022-05-03T14:58:15.885Z",
            "draft": 16,
            "id": 32,
            "published": 25,
            "user_updated": "9967c52c-175d-4631-b390-97dc961a93df"
        },
        {
            "author": "26a3109a-5279-4dbe-a392-81ce9eadb769",
            "date_created": "2022-04-28T20:40:59.891Z",
            "date_updated": "2022-05-03T14:58:15.885Z",
            "draft": 16,
            "id": 32,
            "published": 25,
            "user_updated": "9967c52c-175d-4631-b390-97dc961a93df"
        },
        {
            "author": "26a3109a-5279-4dbe-a392-81ce9eadb769",
            "date_created": "2022-04-28T20:40:59.891Z",
            "date_updated": "2022-05-03T14:58:15.885Z",
            "draft": 16,
            "id": 32,
            "published": 25,
            "user_updated": "9967c52c-175d-4631-b390-97dc961a93df"
        }
    ]
}
```

### To Reproduce

Data model:
`document`
`document_content`
`document_content_access`

Relations:
`document` has an `author` and `user_updated` that are `directus_user` id's
`document` has a `draft` and `publish` that are `document_content` id's
`document_content` has `user_created` and `user_updated` that are `directus_user` id's
`document_content_access` has a a `document_content_id` which is a `document_content` id
`document_content_access` has a `directus_user_id` that is a `directurs_user` id

Fields (the ones of interest, I have omitted any incidental ones):
`document_content` body - String
`document_content_access` read - Boolean
`document_content_access` write - Boolean
`document_content` has some "virtual" field thats not on the actual table called "access" that directus added as a result of selecting: `Add Field to Related Collection` during relationship configuration.

Read Permissions on `document`:
```
OR: 
    document.author == $CURRENT_USER
    AND:
        document.draft.access.directus_user_id == $CURRENT_USER
        OR:
            document.draft.access.read == true
            document.draft.access.write == true
    AND:
        document.published.access.directus_user_id == $CURRENT_USER
        OR:
            document.published.access.read == true
            document.published.access.write == true
```

Call the API to get a list view of all documents with: GET `/items/document/` with 1 document and you will see it returned 8 times (as seen above)

### Errors Shown

Turning on the DB debugging you can see a SQL statement full of joins that when run directly against the database reproduces this result of seeing the same item 8 times:
(Here I've done the substitution of the variables as shown in the knex debug output to produce runnable SQL)
```
select "document"."id", "document"."date_created", "document"."user_updated", "document"."date_updated", "document"."author", "document"."draft", "document"."published"
from "document"
    left join "directus_users" as "gconp" on "document"."author" = "gconp"."id"
    left join "document_content" as "oqacp" on "document"."published" = "oqacp"."id"
    left join "document_content_access" as "lsfsl" on "oqacp"."id" = "lsfsl"."document_content_id"
    left join "directus_users" as "gvxwd" on "lsfsl"."directus_users_id" = "gvxwd"."id"
    left join "document_content" as "sekef" on "document"."published" = "sekef"."id"
    left join "document_content_access" as "pxbkc" on "sekef"."id" = "pxbkc"."document_content_id"
    left join "document_content" as "fdqyd" on "document"."published" = "fdqyd"."id"
    left join "document_content_access" as "hcgxx" on "fdqyd"."id" = "hcgxx"."document_content_id"
    left join "document_content" as "kcjba" on "document"."draft" = "kcjba"."id"
    left join "document_content_access" as "yssrr" on "kcjba"."id" = "yssrr"."document_content_id"
    left join "directus_users" as "quhag" on "yssrr"."directus_users_id" = "quhag"."id"
    left join "document_content" as "zlmnw" on "document"."draft" = "zlmnw"."id"
    left join "document_content_access" as "svncz" on "zlmnw"."id" = "svncz"."document_content_id"
    left join "document_content" as "vkriu" on "document"."draft" = "vkriu"."id"
    left join "document_content_access" as "vokvp" on "vkriu"."id" = "vokvp"."document_content_id"
where ((("gconp"."id" = '26a3109a-5279-4dbe-a392-81ce9eadb769'  or (
    "gvxwd"."id" = '26a3109a-5279-4dbe-a392-81ce9eadb769' and ("pxbkc"."read" = true or "hcgxx"."write" = true)) or ("quhag"."id" = '26a3109a-5279-4dbe-a392-81ce9eadb769' and ("svncz"."write" = true or "vokvp"."read" = true))))) order by "document"."id" asc limit 100

```

### What version of Directus are you using?

9.9.1

### What version of Node.js are you using?

v16.14.2

### What database are you using?

Postgres 14

### What browser are you using?

HTTPie from the shell

### How are you deploying Directus?

Docker

**Comment by br41nslug** [comment]
I am unable to reproduce this with the given data model description. I have recreated the model and filled it with 6 arbitrary `documents` (12 items in `document_content` and 12 items in `document_content_access`) added the permission rule for a test role/user but am still getting no duplicated results:
```
curl --no-progress-meter --location --request GET 'http://localhost:8055/items/document' --header 'Authorization: Bearer [hidden]'
{
   "data":[
      {
         "id":1,
         "draft":1,
         "publish":2,
         "author":"4d58b08b-7de1-4b7b-a477-4d7fcbfee83b",
         "user_updated":"4d58b08b-7de1-4b7b-a477-4d7fcbfee83b"
      },
      {
         "id":3,
         "draft":9,
         "publish":5,
         "author":"03718caf-f4d4-4136-a8f3-d1f7eaa04d69",
         "user_updated":"03718caf-f4d4-4136-a8f3-d1f7eaa04d69"
      },
      {
         "id":4,
         "draft":10,
         "publish":6,
         "author":"03718caf-f4d4-4136-a8f3-d1f7eaa04d69",
         "user_updated":"03718caf-f4d4-4136-a8f3-d1f7eaa04d69"
      }
   ]
}
```
Would you mind sharing a dump of the database? or deeper insight into what combination of records could be causes this

**Comment by jdoig** [comment]
Thanks, sorry if I've missed something. I'll try recreating these broken permission sets and see if the problem happens again. I may have just got my permissions table in a bad state through another bug. I'll update this ticket as soon as I've done this.

**Comment by jdoig** [comment]
Ok I've stepped through this, it is against the 
It needs 3 users: James, Alice, Bob
* James creates a `document` with related draft and publish `document_content`.
* James grants Bob read access on the published document content by creating an entry in `document_content_access` with that `document_content` id, `read=true` and Bob's user id.
* Bob calls `GET /items/document` **and sees only one document returned** 
* James adds 2 more `document_content_access` items. This time granting Alice read access on the draft and publish `document_content` id's.
* Bob calls `GET /items/document` now **and sees four copies of the same document returned** 

I've some SQL scripts I've generated to create the tables and data that we use as "DB migrations" I could share. Where is the best place to share these to help with this bug?

**Comment by jdoig** [comment]
@rijkvanzanten @br41nslug not sure if I should have @-ed you in the above comment. So here we go, just in case :sweat_smile:

**Comment by br41nslug** [comment]
> rijkvanzanten br41nslug not sure if I should have @-ed you in the above comment. So here we go, just in case 😅

Nice timing, I was just finishing up my reproduction tests :)

**Comment by rijkvanzanten** [comment]
@br41nslug might be related to #11445

**Comment by jdoig** [comment]
The collection that was impacted by this bug how has a new issue in 9.13.
querying `/items/document` returns a 500 and the server logs this:

```
🚨 error select "document"."id", "document"."date_created", "document"."user_updated", "document"."date_updated", "document"."author", "document"."draft", "document"."published", "document"."route", "document"."type", "document"."editable", "document"."archived" from "document" left join "directus_users" as "svcpe" on "document"."author" = "svcpe"."id" left join "document_content" as "tjjlt" on "document"."published" = "tjjlt"."id" left join "document_content_access" as "mussv" on "tjjlt"."id" = "mussv"."document_content_id" left join "document_content" as "nubht" on "document"."published" = "nubht"."id" left join "document_content_access" as "akkce" on "nubht"."id" = "akkce"."document_content_id" left join "directus_users" as "fkepn" on "akkce"."user_id" = "fkepn"."id" where ((("document"."type" in ($1, $2) or "svcpe"."id" = $3 or ("mussv"."read" = $4 and "fkepn"."id" = $5)))) order by "document"."id" asc limit $6 - invalid input syntax for type uuid: "NaN" ```

Turning on logging in the DB suggests that the $5 parameter above is being passed `...`

```
cms_postgres.1.ov2wmev2gtyq@pop-os    | 2022-06-29 15:12:02.955 UTC [35] ERROR:  invalid input syntax for type uuid: "NaN"
cms_postgres.1.ov2wmev2gtyq@pop-os    | 2022-06-29 15:12:02.955 UTC [35] CONTEXT:  unnamed portal parameter $5 = '...'
```

Here are the same logs generated in the DB when running a 9.12 server

```
[35] DETAIL:  parameters: $1 = 'bw_document', $2 = 'template', $3 = '26a3109a-5279-4dbe-a392-81ce9eadb769', $4 = 't', $5 = '26a3109a-5279-4dbe-a392-81ce9eadb769', $6 = '100'```

**Comment by rijkvanzanten** [comment]
Linear: [ENG-258](https://linear.app/directus/issue/ENG-258/combined-nested-filter-rule-causes-duplicate-data-due-to-added-joins)

**Comment by u12206050** [comment]
This issue still seems to be happening as soon as more than on m2m collection is added to a permission check.

eg. View persons

```
{
	"_and": [
		{
			"status": {
				"_eq": 1
			}
		},
		{
			"_or": [
				{
					"registrations": {
						"orgId": {
							"_in": [
								"$CURRENT_USER.organizations.orgId"
							]
						}
					}
				},
				{
					"_and": [
						{
							"organizations": {
								"orgId": {
									"_in": [
										"$CURRENT_USER.organizations.orgId"
									]
								}
							}
						}
					]
				}
			]
		}
	]
}
```

The actual records don't seem to be duplicated, but the `count` is very high, relative to the amount of m2m relationships joined via the sql query.

**Comment by licitdev** [comment]
@u12206050 Are you referring to the item `count` displayed in the data studio? 
I think you might be referring to the same issue as https://github.com/directus/directus/issues/17028
