### ISSUE TITLE
Error when adding One to Many relation

### ISSUE THREAD

**Issue by Ronnyrr** [directus/directus#1310]
## Version Info
  - Directus version and branch: 6.3.5 hash: 899b15f23f6f565e1c54b2b82dff708637dfabcc
  - PHP version: PHP Version 7.0.8-0ubuntu0.16.04.3
  - MySQL version: mysqlnd 5.0.12-dev
  - Web server: Apache
  - OS name and version: macOS Sierra

## Actual Behavior
When saving the post it shows the error as shown below.
You know how to fix this / what is going on? 

## Steps to Reproduce
 1. Create a tables with (lowercase)  
 2. Set column as shown below. Visible Columns* : title
One table is categories with title en color. Other is posts, with several columns
 3. Link category to post with One to Many

## Logs or Screenshots
![Error in Directus](https://s16.postimg.org/wt6cfvil1/Schermafbeelding_2016_12_07_om_16_41_07.png)

![Column](https://s15.postimg.org/rpvkhpnmz/Schermafbeelding_2016_12_07_om_21_32_48.png)

**Comment by WellingGuzman** [comment]
Hey @Ronnyrr can you please show me a screenshot of you `ONETOMANY` column relationship settings. And/Or the record on `directus_columns`.

**Comment by Ronnyrr** [comment]
Welling, the `ONETOMANY` relation is as seen below. Didn't really know what "Only Unassigned" does, but with both checked and unchecked it produces the same error. 
During some permission problems on my server I can't reach my MySQL database via phpMyAdmin or CLI at the moment. I'm sure this isn't the reason it isn't working ;)

![OneToMany relation](https://s28.postimg.org/f9gacp87x/Schermafbeelding_2016_12_08_om_10_12_58.png)

**Comment by WellingGuzman** [comment]
Hi @Ronnyrr, What's on your relationship options (see image below with the arrows)?

![screen shot 2016-12-08 at 11 35 45 am](https://cloud.githubusercontent.com/assets/1531291/21016083/b5b549c0-bd3a-11e6-8f15-a7326b060db1.png)

**Comment by Ronnyrr** [comment]
@WellingGuzman Oh sorry I misunderstood. But my relation is already in the first post (see image below error message).

**Comment by WellingGuzman** [comment]
I think we both are not understanding ourselves haha. I'm sorry I meant clicking on the arrows and whats the relationship values. 😃

**Comment by Ronnyrr** [comment]
Haha here you go! 
![Relation](https://s24.postimg.org/o48g2ie6d/Schermafbeelding_2016_12_08_om_17_14_22.png)

**Comment by WellingGuzman** [comment]
Hey @Ronnyrr, what I thought, the `related column` field is a new column where the current table ID is going to save its ID in the related table. so you have to create a new column in categories to stores it.

Although it seems you want a `many to many` can categories be in more than just one posts? or category unique to one post alone?

**Comment by Ronnyrr** [comment]
@WellingGuzman Adding a many to many solved my issue. Although I do want a `ONETOMANY` but it works this way 👍  Thanks for the help
