### ISSUE TITLE
Check for existing email before user creation

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1311]
When deleting a user (currently) it sets them to inactive (active=0) – however if you go to create a new user with the same unique email address it lets you but then throws a "unique" error.

`(directus_users_email_unique)`

We should check if an email already exists when trying to create a new user – and offer to TURN ON that user instead.

**Comment by benhaynes** [comment]
@WellingGuzman What is the state of this? I know we merged in a PR...

**Comment by WellingGuzman** [comment]
Did we merge the PR? I don't think so, the PR wasn't full solution to this one, as this is heavily on the frontend. the PR solved the problem on the server.

The state of this is IDLE.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/bddf1577aed6036852c64bca8556ca9f4dd4eebf

We omitted the option to let the user to turn ON the account, now it will enable the user and update the new data.
