### ISSUE TITLE
Save options not shown

### ISSUE THREAD

**Issue by igiornotigi** [directus/directus#13119]
### Describe the Bug

Hi, I noticed that on saving an item the save option "save e create new" and "Save as a copy" are no more shown if the user is not an administrator.

### To Reproduce

- Login with non admin user
- Create a new item in a collection 
- Click in the dots save options icon

### What version of Directus are you using?

9.9.1

### What version of Node.js are you using?

12

### What database are you using?

10.5.12 MariaDB

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally on ubuntu 20.04.03 LTS

**Comment by azrikahar** [comment]
They are intentionally hidden to resolve #11723, as those two options shouldn't appear when the user/role does not have create permission. Can you confirm for step 2 in your reproduction steps, you are _creating_ and _not editing_ instead?

here's a clip to illustrate the differences:

https://user-images.githubusercontent.com/42867097/166733359-56abe9f7-3ffe-4572-8b1d-f689e1507eee.mp4

I'll close this issue for now, but if what you are experiencing differs from what is shown in the clip and the issue still persists for you, we will re-open this issue 👍

**Comment by igiornotigi** [comment]
I confirm that it happen only in creating, but I don't understand, if I have create permission, i still can't create multiple items without having to exit from the item every time. So it seems useless to me.

Fortunately I noticed that the shortcut works the same..

**Comment by azrikahar** [comment]
Would you be able to tell are there any discrepancies in the clip shared above? Perhaps the permission configuration is slightly different compared to what you have currently? 

It'd be much appreciated if you can also share a minimal schema snapshot or sqlite file to reproduce this in case I'm missing something here.

**Comment by igiornotigi** [comment]
There is no discrepancy with the video, but this does not highlight the problem of inserting multiple items. In the video, on the second part (with creation privileges) you are editing an item and you see "save and create new", but if you do it, in the new item you just created you can't do it anymore. So you can't insert multiple item.
I wil try to post a video of the issue...
