### ISSUE TITLE
Cant add a field that belongs to a group to display template

### ISSUE THREAD

**Issue by lanvupan** [directus/directus#13111]
### Describe the Bug

Can't add a field that belongs to a group to display template

### To Reproduce

1. Create collection A
2. Create field a1, a2 and put them in a group (eg. detail group)
3. Create collection B
4. Create field b1 that have relationship to collection A (M2O/O2M/...)
5. Edit field b1, in Display section, add field a1, a2 to Display Template and click Save

### Errors Shown

no error shows, but after refreshing a1, a2 are not in Display Template >  it's actually not saved to Display Template

### What version of Directus are you using?

9.9.0

### What version of Node.js are you using?

16.15.0

### What database are you using?

10.4.22-MariaDB-1:10.4.22+maria~focal

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by andreasgan** [comment]
Same here on 9.8.0. Thanks for opening this.
