### ISSUE TITLE
Error when trying to use the Multiple Files column

### ISSUE THREAD

**Issue by cedricve** [directus/directus#1312]
## Version Info
  - Directus version and branch: master
  - PHP version: PHP 5.5.9
  - MySQL version:  5.5.47
  - Web server: nginx 
  - OS name and version: Ubuntu

## Expected Behavior
I want to create a slider for my homepage. Therefore I've added a new field "Multiple Files" to one of my tabels.

## Actual Behavior

I can add the column, however after adding I try to open the Page, but I'm getting an error.

## Logs or Screenshots

![screen shot 2016-12-15 at 19 23 14](https://cloud.githubusercontent.com/assets/1546779/21236684/5cba409c-c2fc-11e6-99a3-ced65298d11a.png)
![screen shot 2016-12-15 at 19 22 33](https://cloud.githubusercontent.com/assets/1546779/21236685/5cbad228-c2fc-11e6-83b1-954025b97195.png)

**Comment by WellingGuzman** [comment]
Hey @cedricve,

Can you share the logs? (`api/logs`), also what's the `junction` table configuration? (it got chopped off in the screenshot)

**Comment by cedricve** [comment]
I just used the default values: I've added a title for the column, selected the UI: Multiple Files, anders pressed save. The default value is directus_activity.

I can't find any log files in the api/logs folder (that's weird?)

**Comment by WellingGuzman** [comment]
There's _possibly_ your problem `The default value is directus_activity.`

You have to create a junction table, let's say `homepage_slideshow` with two column beside `id` to store the homepage table `id` and the file `id`.

You can read a bit more here: https://docs.getdirectus.com/6.3.6/#Multiple_Files_(M2M)

**Comment by cedricve** [comment]
I'll try this, thank you @WellingGuzman

**Comment by cedricve** [comment]
@benhaynes sometimes I'm receiving server errors (e.g. when doing bulk operations). However I don't see any logs written in the api/logs folder (although it's writeable). Do you have any idea?

**Comment by cedricve** [comment]
Nevermind, I've recreated the directory, and it seems to work now.
