### ISSUE TITLE
Feature request: order by drag and drop

### ISSUE THREAD

**Issue by cedricve** [directus/directus#1313]
Hello Directus team,

I've been using directus for a while, and I'm very pleased with your solution. It's so intuitive.
One improvement I see is to be able to change the order of the rows (by using a simple drag and drop). Something like this: http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/simple.

I don't know if this is already on the roadmap?

This is very helpful for sliders, e.g. where I give my clients the possibility to add images and text themself (+ change the order of each row).

![screen shot 2016-12-18 at 10 47 14](https://cloud.githubusercontent.com/assets/1546779/21292757/64fccf58-c50f-11e6-9c9e-7a8ec76b1173.png)

Cédric

**Comment by WellingGuzman** [comment]
Hey @cedricve, If I understand correctly, Directus supports sorting by dragging and dropping, the table needs to have a column named `sort (int)` and you would be able to sort.

**Comment by cedricve** [comment]
Well that's not so intuitive for basic users (the WYSIWYG principle). I understand it's difficult as you also provide filter and sorting.

**Comment by WellingGuzman** [comment]
Yeah, @cedricve, we are trying to address all this in the new redesign in the next couple of versions.

Any suggestion to make this more intuitive?

**Comment by benhaynes** [comment]
Hey @cedricve – glad you're liking Directus so far. The drag and drop reordering seems pretty intuitive to us (once you've read the docs on reordering). What about it seems unclear? 

You need to add a column to store the order value, and as of now need to call that column `sort`. In the next version you can name it anything you want and "tell" Directus which column stores the value. Any other improvements you can think of?

**Comment by cedricve** [comment]
Well from a developer point of views that's indeed intuitive (and logical), however for a user/client this can be cumbersome. Drag and drop functionality, to change the order, would be an intuitive solution for them. As you don't need to learn them to check and edit an integer to simulate the ordening.

**Comment by benhaynes** [comment]
Sorry, this seems to have been a miscommunication. By adding that column it enables drag and drop reordering on the item listing page for that table. Directus saves the appropriate integers into the column, but the user only sees items that can be dragged and dropped. 

Does that make more sense? I'd that what you were looking for?

**Comment by cedricve** [comment]
Wow, sorry my bad I've didn't read the comment properly. It seems to work! Great job.

**Comment by cedricve** [comment]
@benhaynes when I try to sort, I get following exception. Any idea?

     ERROR - 2016-12-20T13:57:10-05:00 - exception 'Exception' with message 'Geen rijen ingevoerd' in /usr/share/nginx/www/production/zwemschooltje/api/api/api.php:741
     Stack trace:
     #0 [internal function]: {closure}('Slider')
     #1 /usr/share/nginx/www/production/zwemschooltje/api/vendor/slim/slim/Slim/Route.php(436): call_user_func_array(Object(Closure), Array)
     #2 /usr/share/nginx/www/production/zwemschooltje/api/vendor/slim/slim/Slim/Slim.php(1305): Slim\Route->dispatch()
     #3 /usr/share/nginx/www/production/zwemschooltje/api/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
     #4 /usr/share/nginx/www/production/zwemschooltje/api/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
     #5 /usr/share/nginx/www/production/zwemschooltje/api/api/core/Directus/Slim/CorsMiddleware.php(22): Slim\Middleware\MethodOverride->call()
     #6 /usr/share/nginx/www/production/zwemschooltje/api/vendor/slim/slim/Slim/Slim.php(1254): Directus\Slim\CorsMiddleware->call()
     #7 /usr/share/nginx/www/production/zwemschooltje/api/api/api.php(1705): Slim\Slim->run()

**Comment by WellingGuzman** [comment]
hmm, the API seems to not be getting any rows parameter. I will take a look and see if can replicate.

Did it work at first, but now it's not working giving you that error?

**Comment by cedricve** [comment]
Well I think it never worked, so properly something went wrong during installation?

**Comment by cedricve** [comment]
FYI @WellingGuzman It looks like the rows parameter is posted correctly.
![screen shot 2016-12-20 at 20 19 18](https://cloud.githubusercontent.com/assets/1546779/21364564/a6a71e0c-c6f1-11e6-8e91-d426cd0946e5.png)

**Comment by WellingGuzman** [comment]
the request data looks correct, thanks, I'm checking the code, there's must the problem. I will get back to you asap.

**Comment by WellingGuzman** [comment]
Hey @cedricve try to pull this https://github.com/directus/directus/commit/2f77f2eb98eb3f1573ce1587ccef927cb0c25590 and let me know if it works.

**Comment by cedricve** [comment]
Unfortunately still the same issue @WellingGuzman..

ERROR - 2016-12-26T14:41:01-05:00 - exception 'Exception' with message 'Geen rijen ingevoerd' in /usr/share/nginx/www/production/zwemschooltje/api/api/api.php:741
Stack trace:
#0 [internal function]: {closure}('Slider')
#1 /usr/share/nginx/www/production/zwemschooltje/api/vendor/slim/slim/Slim/Route.php(436): call_user_func_array(Object(Closure), Array)
#2 /usr/share/nginx/www/production/zwemschooltje/api/vendor/slim/slim/Slim/Slim.php(1305): Slim\Route->dispatch()
#3 /usr/share/nginx/www/production/zwemschooltje/api/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#4 /usr/share/nginx/www/production/zwemschooltje/api/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#5 /usr/share/nginx/www/production/zwemschooltje/api/api/core/Directus/Slim/CorsMiddleware.php(22): Slim\Middleware\MethodOverride->call()
#6 /usr/share/nginx/www/production/zwemschooltje/api/vendor/slim/slim/Slim/Slim.php(1254): Directus\Slim\CorsMiddleware->call()
#7 /usr/share/nginx/www/production/zwemschooltje/api/api/api.php(1705): Slim\Slim->run()
#8 {main}

**Comment by WellingGuzman** [comment]
Hey @cedricve what commit are you on? what's on your `/usr/share/nginx/www/production/zwemschooltje/api/api/api.php:741`?

**Comment by cedricve** [comment]
Latest master.

![screen shot 2016-12-26 at 20 52 22](https://cloud.githubusercontent.com/assets/1546779/21486042/484b1028-cbad-11e6-8389-aa5c63f86b3c.png)

**Comment by WellingGuzman** [comment]
Can you clear your browser cache? Can make sure the commit (https://github.com/directus/directus/commit/2f77f2eb98eb3f1573ce1587ccef927cb0c25590) is applied.

**Comment by cedricve** [comment]
Clearing browser cache did it, indeed was due to caching javascript. Thank you!

Cédric

**Comment by WellingGuzman** [comment]
Glad to hear @cedricve.
