### ISSUE TITLE
Can't edit video properties after adding to WYSIWYG widget.

### ISSUE THREAD

**Issue by cedricve** [directus/directus#1314]
It's not possible to modify the properties of a video file, after you've added it to the WYSIWYG editor. This can be required if you want to resize it.

![screen shot 2016-12-20 at 20 00 13](https://cloud.githubusercontent.com/assets/1546779/21363984/3486c856-c6ef-11e6-857f-91d3d17e2ea6.png)

**Comment by WellingGuzman** [comment]
Hey @cedricve I will see what I can do with this Editor, it has been a fight with the library.

@benhaynes is going to create a new one, using a new library that will be a better fit.

In the meantime I'll see what I can do.

**Comment by WellingGuzman** [comment]
We apologies, but we are removing this library used in the interface. So we are not longer trying to solve any issues this library may have, which can take up much time trying to see why is broken, which wasn't developed by us.

Please go #1242, where are talking about the new interface.
