### ISSUE TITLE
WYSIWYG field is disabled on Create item page when it's in translations

### ISSUE THREAD

**Issue by mr-sanders** [directus/directus#13143]
### Describe the Bug

WYSIWYG editor renders in a disabled state on the "Create item" page when we create a non-singleton model with a translatable field. It happens only for the primary language. After the page reload the field becomes enabled until the next router navigation to that page. Additional locales render the editor properly if they are opened as an additional column.

### To Reproduce

1. Create a non-singleton model with translations (e.g. post)
2. Add a WYSIWYG field (e.g. content) to the corresponding translations collection (e.g. post_translations)
3. Go to Content -> Post
4. Press the "Create item" or "+" button:

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/6909724/166968671-21b3278c-dc92-473f-8b9c-c27c4b590e9c.png">

### Errors Shown

There are no errors

### What version of Directus are you using?

9.10.0

### What version of Node.js are you using?

14.18.2

### What database are you using?

Postgres 14.1

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by arladmin** [comment]
Came across the same issue.

**Comment by SvenBudak** [comment]
I have been watching this issue board of directus for months because we are planning to launch a really really big platform and use directus for it.... i am really afraid of going this step because with every update there are 10 new bugs...
