### ISSUE TITLE
Naming of Precision & Scale can be misleading

### ISSUE THREAD

**Issue by SeanDylanGoff** [directus/directus#13145]
### Describe the Bug

Currently the Schema settings for decimal fields look like this:
![image](https://user-images.githubusercontent.com/6235675/167023415-dacfa50d-1d50-4c9a-881b-ad4675fd86c6.png)

I believe that the label should be "Scale & Precision" instead, so that the ordering is the same as the actual inputs.
Alternatively we could add two separate labels. I'm not sure whether there is enough space in all languages though.

If the maintainers agree that it should be changed i'll make a PR.

**Comment by benhaynes** [comment]
If the order of those labels/inputs is indeed reversed (I always get those two confused), this update has my approval!

**Comment by azrikahar** [comment]
Can you share more detail on the ordering not being the same? I did a brief test and it seems correct on my end:

![chrome_oHGDAukjKt](https://user-images.githubusercontent.com/42867097/167051684-2a5bcff1-0580-40cd-99fe-9f3f2d53769c.png)

![chrome_6rzyQY22Or](https://user-images.githubusercontent.com/42867097/167051690-419eef88-56a8-496d-ad5a-4bbcac163c0e.png)

Could it be a database vendor and/or field type thing and you mean the created column has the precision and scale flipped? 🤔 I am testing this on PostgreSQL.

**Comment by SeanDylanGoff** [comment]
@azrikahar Interesting. I've never worked with PostgreSQL, turns out they label it exactly as Directus does.
I still find the terms a bit confusing though, as I would have guessed that Precision means how many decimal places there are, and Scale how many digits in total (or in the digits before the point).

The naming across supported DBs is as follows:

PostgreSQL, MySQL, Microsoft SQL Server, SQLite, OracleDB, MariaDB

First attribute (total digit count):

precision, precision, precision, N/A, precision, "M is the total number of digits (the precision)"
