### ISSUE TITLE
Contains filter not allowing typing after hitting backspace and trying to continue typing.

### ISSUE THREAD

**Issue by jamescammarano** [directus/directus#13157]
### Describe the Bug

I was trying to filter items on the collection content module by contains. I made a typo and tried to correct it and after that, key strokes were not being recognized. It's possible that they aren't recognized until after the search is completed but its hard to say.

https://user-images.githubusercontent.com/67079013/167177859-435fe0b9-094b-4625-8e2d-3710636c67fa.mov

### To Reproduce

1. On the content collection page start a filter for "status".
2. Use the `contains` filter.
3. type "drag"
4. hit backspace
5. try to correct it to "draft"

### Errors Shown

None. 

### What version of Directus are you using?

main branch

### What version of Node.js are you using?

v16.13.1

### What database are you using?

Postgres

### What browser are you using?

chromium (brave)

### How are you deploying Directus?

running locally

**Comment by ankitchhatbar** [comment]
@azrikahar I could take a look at this. Let me know.

**Comment by rijkvanzanten** [comment]
> @azrikahar I could take a look at this. Let me know.

All yours! ✨ 🚀

**Comment by ankitchhatbar** [comment]
https://user-images.githubusercontent.com/29805075/167500891-caf7b161-63cf-4e6e-ab60-0902bdd635e1.mp4

@jaycammarano I tried to replicate it, I could not get the input to freeze or disallow me to input anything. Although, I noticed very significant lag when typing. As you can see on the video, the characters I type appear very slow after a couple of backspaces. Is this what you meant?

**Comment by jaycammarano** [comment]
No. For me it was consistently removing the characters after the first time I hit backspace. I wasn't hitting backspace in my video after the initial backspace. I'll see if it's still happening on latest.

**Comment by marlenekoh** [comment]
Facing this issue as well

**Comment by Jeyakumarrathnaselvi** [comment]
This issue makes the solution almost unusable to type and search when we are in need and it was a very annoying user experience issue. 

It works fine when we type outside, copy and paste here—managing it like this. last 30+ days

**Comment by ankitchhatbar** [comment]
> No. For me it was consistently removing the characters after the first time I hit backspace. I wasn't hitting backspace in my video after the initial backspace.

@jaycammarano I can't replicate this. Could it be anything to do with the data size?

@rijkvanzanten A potential reason could be that every time a character is typed, we are making an API a request for the search (I am not sure, please correct me). If we could add some sort of a buffer of 500ms or something, we can allow more characters to be typed before doing the API request. So, if no characters are typed in the last 500ms, we can send an API request. This means we won't be sending an API request for every character typed.

Please let me know what you think

**Comment by rijkvanzanten** [comment]
> A potential reason could be that every time a character is typed, we are making an API a request for the search (I am not sure, please correct me). If we could add some sort of a buffer of 500ms or something, we can allow more characters to be typed before doing the API request. So, if no characters are typed in the last 500ms, we can send an API request. This means we won't be sending an API request for every character typed.

Preset updates currently already rely on a 450ms debounce iirc

**Comment by joselcvarela** [comment]
I believe this happens not only with `contains` operator but for the filter generally.
For example `Greater Than` operator

https://user-images.githubusercontent.com/14039341/176694607-398e70ad-16eb-4c2b-b079-8edb4ebfbcbd.mov

**Comment by Nitwel** [comment]
It seems that this is happening because the delayed response from the api is overriding the `b` in the example below.

![grafik](https://user-images.githubusercontent.com/22577866/202190792-7b1edfb7-a481-4825-a3c2-aad877bcf884.png)

**Comment by joselcvarela** [comment]
@Nitwel an interesting thing is that the same does not happen on drawers (at least on my tests).
If you have a relationship and click to choose a related item, it should show records from related collection.
In that table you have the filter, and this behaviour does not seem to happen there. 🤔
