### ISSUE TITLE
Visible column setter overflows in de-DE (CSS problem)

### ISSUE THREAD

**Issue by Radiergummi** [directus/directus#1315]
## Version Info
  - Directus version and branch: 7c9e08a
  - PHP version: 7.0.8
  - MySQL version: 5.5.47
  - Web server: nginx/1.9.12
  - OS name and version: Debian 8.3

## Expected Behavior
The modal for setting the visible columns in the table view expands with the width of the `save` and `cancel` buttons.

## Actual Behavior
The modal stays fixed width, the buttons overlap the modal content area.

## Steps to Reproduce
 1. Change locale to german/de-DE
 2. Try to toggle any columns

## Steps to Resolve
 1. Change the following CSS:

````css
.set-columns {
  /* remove width: 200px; */
}

.set-columns fieldset {
  /* remove margin: 0 0 55px 0; */
}

.set-columns .btn-row {
  /* remove position: absolute; */
  /* remove bottom: 15px; */
  /* remove left: 20px; */
  /* remove right: 20px; */
  /* add */ padding: 20px 20px 15px;
}

.set-columns .btn-row .btn {
  /* remove float: left; */
}
````

## Logs or Screenshots
![image](https://cloud.githubusercontent.com/assets/6115429/21390526/a60d4e80-c787-11e6-99e1-8a58f5bd9ad8.png)

**Comment by benhaynes** [comment]
Thanks @Radiergummi – this is perfect! There are a few issues with multi-lingual text lengths, but we're looking to resolve them in the new design we're implementing now (see below). In the meantime, your CSS seems to work great, so I'm pushing that to the development branch.

Really appreciate the help!

https://preview.getdirectus.com/tables/blog

**Comment by Radiergummi** [comment]
Weee, the new design looks really neat! Looking forward to update 👍
