### ISSUE TITLE
CORS Error on createMany Array with more than 10 objects, works as intended for under 10...

### ISSUE THREAD

**Issue by jabstein** [directus/directus#13161]
### Describe the Bug

When initiating a Post with the Directus SDK (Also tried REST API axios put) that has a paayload array of a certain size or object numbers, causes CORS ERROR:

**No 'Access-Control-Allow-Origin' header is present on the requested resource.**

If i do under ten objects then the post is successfully submitted and no CORS error.

I have tried multiple configurations of the directus env file and it is not changing the outcome.

I have also tried to initiate the post from a https domain name set server and get the same outcome.

### To Reproduce

```
const directus = new Directus('URL')
const PAYLOAD = [ ] //Array of 10 large objects Articles - content-length: 177883

directus.items('posts').createMany(PAYLOAD)
  .then(res => {
      console.log("TRANSFER COMPLETE", {res}, {PAYLOAD})
    })
    .catch(err => {
      console.log("TRANSFER ERROR", {err}, {PAYLOAD})
    })
```

### Errors Shown

Access to XMLHttpRequest at 'URL/items/posts' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

//err log output
```
{
    "parent": {
        "message": "Network Error",
        "name": "Error",
        "stack": "Error: Network Error\n    at createError (webpack-internal:///./node_modules/axios/lib/core/createError.js:16:15)\n    at XMLHttpRequest.handleError (webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:117:14)",
        "config": {
            "transitional": {
                "silentJSONParsing": true,
                "forcedJSONParsing": true,
                "clarifyTimeoutError": false
            },
            "transformRequest": [
                null
            ],
            "transformResponse": [
                null
            ],
            "timeout": 0,
            "xsrfCookieName": "XSRF-TOKEN",
            "xsrfHeaderName": "X-XSRF-TOKEN",
            "maxContentLength": -1,
            "maxBodyLength": -1,
            "headers": {
                "Accept": "application/json, text/plain, */*",
                "Content-Type": "application/json",
                "Authorization": "Bearer AUTH CODE HERE"
            },
            "baseURL": "URL",
            "withCredentials": false,
            "method": "post",
            "url": "/items/posts",
            "data": "[LARGE Object ARRAY HERE]"
        },
        "status": null
    },
    "errors": []
}
```

POST URL net::ERR_FAILED 400      xhr.js?1a5c:210         

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

14 on directus server, 16.13.0 locally

### What database are you using?

postgres

### What browser are you using?

tried chrome, firefox and opera

### How are you deploying Directus?

DO one-click

**Comment by jabstein** [comment]
More Details - Network Request Preflight

`
Request URL: URL
Request Method: OPTIONS
Status Code: 204 
Remote Address: IP
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-credentials: true
access-control-allow-headers: Content-Type,Authorization
access-control-allow-methods: GET,POST,PATCH,DELETE
access-control-allow-origin: http://localhost:3000
access-control-expose-headers: Content-Range
access-control-max-age: 18000
content-length: 0
content-security-policy: script-src 'self' 'unsafe-eval';worker-src 'self' blob:;child-src 'self' blob:;img-src 'self' data: blob: https://cdn.directus.io;media-src 'self' https://cdn.directus.io;connect-src 'self' https://*;default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';object-src 'none';script-src-attr 'none';style-src 'self' https: 'unsafe-inline'
date: Sat, 07 May 2022 01:06:23 GMT
server: Caddy
vary: Origin
x-powered-by: Directus
:authority: API
:method: OPTIONS
:path: /items/posts
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
access-control-request-headers: authorization,content-type
access-control-request-method: POST
origin: http://localhost:3000
referer: http://localhost:3000/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
`

**Comment by jabstein** [comment]
More Details - Network Post

Request URL: URL
Request Method: POST
Status Code: 400 
Referrer Policy: strict-origin-when-cross-origin
content-length: 91
content-security-policy: script-src 'self' 'unsafe-eval';worker-src 'self' blob:;child-src 'self' blob:;img-src 'self' data: blob: https://cdn.directus.io;media-src 'self' https://cdn.directus.io;connect-src 'self' https://*;default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';object-src 'none';script-src-attr 'none';style-src 'self' https: 'unsafe-inline'
content-type: application/json; charset=utf-8
date: Sat, 07 May 2022 01:06:23 GMT
etag: W/"5b-raUMnyiCFHmatG8PbxiVo8tPV1A"
server: Caddy
:authority:  API
:method: POST
:path: /items/posts
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
authorization: Bearer TOKEN
content-length: 177883
content-type: application/json
origin: http://localhost:3000
referer: http://localhost:3000/
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="100", "Google Chrome";v="100"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site

**Comment by azrikahar** [comment]
Hi, would you mind configuring the `MAX_PAYLOAD_SIZE` environment variable and set it to something higher like `10mb`? The default is `100kb` as described in the docs here: https://docs.directus.io/configuration/config-options/#general. 

Apparently exceeding the size limit results in CORS error in Express.js [as mentioned by this SO answer](https://stackoverflow.com/a/66410116). It could be an oddity with the body-parser and cors middleware package, but I'm pretty sure it's not something intentional from our end.

I'll close this for now, but happy to assist further or re-open this issue if this doesn't resolve it for you. 👍

**Comment by jabstein** [comment]
Max payload fixed the issue, thank you.
