### ISSUE TITLE
Filter by field date

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [directus/directus#13192]
### Describe the Bug

Had a field called "date", which i then wanted to filter for using the sdk version.

### To Reproduce

```
dateFilter = {
    date: { _eq: "2022-05-13" }
}		

answer = await directus.items("mealoffers").readByQuery({
    filter: dateFilter,
    fields: ['*,meal.*']
});
```

### Errors Shown

Only an empty error was given back

### What version of Directus are you using?

9.8

### What version of Node.js are you using?

12.0

### What database are you using?

Sqlite 3.31.0

### What browser are you using?

Brave (Chrome)

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
@NilsBaumgartner1994 One thing I noticed is that `fields: ['*,meal.*']` is supposed to be `fields: ['*', 'meal.*']`, but other than that I'm afraid there isn't enough information here for us to be able to reproduce or comment on what might went wrong. 

What does your schema look like? Could you share a database dump with a minimal reproduction? What do you mean by "empty" error? What does the request look like in the network tab of the browser?

I'll close this for now, but we'll reopen when more information becomes available 👍🏻

**Comment by NilsBaumgartner1994** [comment]
it’s okay. Since I retried it with another fieldname it worked, but the name „date“ was not usable for me.

i can add a scheme if wanted, but since it is an „older“ version it may not matter
