### ISSUE TITLE
When 2 columns (single file) are added to a table, only first one gets saved

### ISSUE THREAD

**Issue by cedricve** [directus/directus#1320]
@WellingGuzman sorry man, here I am again.. It looks like something else is broken now, by pulling master yesterday (fix for sorting).

It looks that when I'm trying to save a entry which contains 2 columns (single file), that only the first one is saved to database. After reopening the entry, the second one is empty. I simulated the problem by creating a new table, which contains two (single file) columns. I get following output:

![screen shot 2016-12-27 at 15 21 19](https://cloud.githubusercontent.com/assets/1546779/21501435/3282d690-cc48-11e6-9919-9923d0c8974b.png)

![screen shot 2016-12-27 at 15 17 12](https://cloud.githubusercontent.com/assets/1546779/21501436/346166b6-cc48-11e6-8239-7103a9866ea9.png)

**Comment by WellingGuzman** [comment]
Hey @cedricve, please pull the last commit from master, it should fix the problem, either way let me know.
