### ISSUE TITLE
Repeater with custom interface field not passing required props

### ISSUE THREAD

**Issue by enzolupia** [directus/directus#13212]
### Describe the Bug

Hi, we recently implemented a custom interface that produce a JSON output.
The interface has a custom options component which access the current collection via props (automatically passed from the ExtensionOptionsContext I assume). 
The options component use the collection name to retrieve the collection's fields and allow the user to select one of them.
This works fine.

We tried to include the new interface as a field in the Repeater interface but we discovered that the custom interface cannot access the current collection anymore.
Debbugging the custom interface it turned out that the collection props is null, so the Repeater is not passing the required props to the "child" fields.

### To Reproduce

1. Create a basic custom interface  and  access the **_collection_** property.
2. Verify the interface is working as expected and can access the **_collection_** property.
3. Include the new interface as a field in a Repeater

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

16.13.2

### What database are you using?

SQLite

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally running Docker

**Comment by rijkvanzanten** [comment]
This is technically working as expected. The v-form scope in the repeater isn't based on a given collection, but it's based on it's own custom configured scope from the repeater options. The form in a repeater doesn't come from a 'collection'. Happy to keep discussing potential improvements on this in a new feature request discussion though! 🙂
