### ISSUE TITLE
Invalid user when token is attached for public routes

### ISSUE THREAD

**Issue by wasims1** [directus/directus#13213]
### Describe the Bug

We use directus partially as our blog. So we have our internal authorization system with our tokens. Our blog is public for viewing.

With version 9.0.0: just sending a request to retrieve our blog returns data appropriately

Updating to version 9.10.0: sending a request to retrieve our blog returns error: (message: "Invalid user credentials.")

After some digging, we discovered that if we send the same request to 9.10.0 WITHOUT our own token, it works...

So the issue is that directus is attempting to decode our own tokens as 'directus' user tokens when it's not necessary (as the table/routes are public)

### To Reproduce

Just create any DB and make some table public, try to get some data with random token and you will get an error..

### What version of Directus are you using?

9.10.0

### What version of Node.js are you using?

17.0.0

### What database are you using?

Mysql

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker+K8s

**Comment by rijkvanzanten** [comment]
This is working as intended. If you provide a wrong token, you get an "Invalid user credentials" error. 👍🏻
