### ISSUE TITLE
Maximum of 100 items display on m2m

### ISSUE THREAD

**Issue by joshualyness** [directus/directus#13229]
### Describe the Bug

A m2m field on the directus_users table is only displaying 100 items. If I add any more, it does add them into the junction table, but they disappear from the user field after saving. 

This is a big problem, because the junction table items only store IDs that link to the other collection, which means admin staff have no ability to go in and manage user data. 

Are there any plans to increase this limit, potentially adding pagination or search functionality?

### To Reproduce

1. Create a collection (A) with a m2m field to another collection (B)
2. Add more than 100 items to the m2m field
3. You'll see the list on collection A collapses to a maximum of 100 items, but the correct amount displays in collection B and the junction table

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

16.13.1

### What database are you using?

MySQL 5.7.12

### What browser are you using?

Chrome

### How are you deploying Directus?

Remote server

**Comment by azrikahar** [comment]
This has since be resolved in `9.9.0` thanks to #12082! 🙂 

Mini reminder: Do try to adhere to the second `You're using the latest version of Directus.` point in the top of the form when opening a new issue. Alternatively you can always open a discussion of you can't seem to find relevant issues/discussions on your question. Much appreciated!

**Comment by joshualyness** [comment]
> This has since be resolved in `9.9.0` thanks to #12082! 🙂
> 
> Mini reminder: Do try to adhere to the second `You're using the latest version of Directus.` point in the top of the form when opening a new issue. Alternatively you can always open a discussion of you can't seem to find relevant issues/discussions on your question. Much appreciated!

Ahh apologies, I didn't see that notice. Thanks for your advice, I've updated and I can see pagination now.
