### ISSUE TITLE
Soft Character Limit: Remaining character count not accurate until you type in RTE

### ISSUE THREAD

**Issue by bcartier** [directus/directus#13235]
### Describe the Bug

When you set a soft character limit for a rich text field, and you edit an item that has content in the rich text field, the configured limit is shown at the bottom right. Once you type in the field, the limit changes to show the actual count. 

### To Reproduce

1. Create a collection with a rich text field
2. Set a soft character limit (let's say 500)
3. Create and save an item with some text in the rich text field (let's say 10 characters)
4. edit that item
5. when viewing the field, you will see a "Remaining Character" count of  "500" in the bottom-right for the field, as if the field were empty. It should be showing 490.
6. If you typing a character into the field, the remaining character count starts behaving normally.

### Errors Shown

None

### What version of Directus are you using?

9.10.0

### What version of Node.js are you using?

16.15

### What database are you using?

MySQL

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by bcartier** [comment]
This is still an issue in 9.12.1

**Comment by rijkvanzanten** [comment]
It seems to behave as expected on my end when navigating around in-app, but has the tendency to not set the count properly on a hard-refresh. Could you confirm that behavior on your end @bcartier, or does it act funky in regular app usage as well?

**Comment by bcartier** [comment]
@rijkvanzanten you're right, accessing the item page directly via URL (from a browser bookmark, etc) or using a hard-refresh causes the issue every time. I'm pretty sure I discovered the issue with normal use (linking from a table layout), but I can't reproduce it. I'll investigate further...

**Comment by rijkvanzanten** [comment]
> you're right, accessing the item page directly via URL (from a browser bookmark, etc) or using a hard-refresh causes the issue every time. I'm pretty sure I discovered the issue with normal use (linking from a table layout), but I can't reproduce it. I'll investigate further...

Copy that! I was seeing the same behavior, but haven't been able to reproduce it by "regular" navigation around the app. #13789 includes a fix for the count on fresh reloads. We'll reopen this (again!) if we run into the issue through a third path 🙂
