### ISSUE TITLE
auto_increment not being added to table id columns

### ISSUE THREAD

**Issue by sanpoChew** [directus/directus#1323]
## Version Info
  - Directus version and branch: development
  - PHP version: 7.0.14
  - MySQL version: 5.5.53
  - Web server: nginx
  - OS name and version: Debian 8.4 

## Expected Behavior
I presume that new tables should have their id column set to auto_increment

## Actual Behavior
It's not set, having to set manually with ALTER TABLE or I can't add more than 1 row to a table.

I'm assuming this is an easy fix, It's not the end of the world for me to just use ALTER TABLE manually but would be great if there is a way to fix it.

Great product by the way guys! It's exactly what I've been looking for, glad I found it before I went all-in with Contentful.

**Comment by WellingGuzman** [comment]
Hey @sanpoChew, thanks for reporting this.

It should've created the auto increment id column when you create table from the Directs admin. Is there any warning or error in your logs (`/api/logs`)?

**Comment by sanpoChew** [comment]
Hi,

nothing for when I create a new table or add the first item, trying to add a second item gives me this:

```
ERROR - 2017-01-09T16:08:35+00:00 - Directus\Database\Exception\DuplicateEntryException: Duplicate value: 0<br>(PRIMARY) in /var/www/directus-dev/vendor/directus/database/TableGateway/BaseTableGateway.php:600
Stack trace:
#0 /var/www/directus-dev/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(264): Directus\Database\TableGateway\BaseTableGateway->executeInsert(Object(Zend\Db\Sql\Insert))
#1 /var/www/directus-dev/vendor/directus/database/TableGateway/BaseTableGateway.php(303): Zend\Db\TableGateway\AbstractTableGateway->insert(Array)
#2 /var/www/directus-dev/vendor/directus/database/TableGateway/RelationalTableGateway.php(134): Directus\Database\TableGateway\BaseTableGateway->addOrUpdateRecordByArray(Array)
#3 /var/www/directus-dev/api/core/Directus/Services/EntriesService.php(32): Directus\Database\TableGateway\RelationalTableGateway->manageRecordUpdate('test', Array, 1)
#4 /var/www/directus-dev/api/api.php(904): Directus\Services\EntriesService->createEntry('test', Array, Array)
#5 [internal function]: {closure}('test')
#6 /var/www/directus-dev/vendor/slim/slim/Slim/Route.php(436): call_user_func_array(Object(Closure), Array)
#7 /var/www/directus-dev/vendor/slim/slim/Slim/Slim.php(1305): Slim\Route->dispatch()
#8 /var/www/directus-dev/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#9 /var/www/directus-dev/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#10 /var/www/directus-dev/api/core/Directus/Slim/CorsMiddleware.php(22): Slim\Middleware\MethodOverride->call()
#11 /var/www/directus-dev/vendor/slim/slim/Slim/Slim.php(1254): Directus\Slim\CorsMiddleware->call()
#12 /var/www/directus-dev/api/core/Directus/Application/Application.php(74): Slim\Slim->run()
#13 /var/www/directus-dev/api/api.php(1887): Directus\Application\Application->run()
#14 {main}
```

This is the little error that pops up in the actual CMS:

```
Server Error
Duplicate value: 0
(PRIMARY)
```

**Comment by WellingGuzman** [comment]
Thanks for the info, that's expected if there's not primary key, I will try to dig a bit more into this, but I've not been able to replicate this issue under MacOS, Apache and PHP 5.6.

I will get back to you as soon as I get something.

**Comment by WellingGuzman** [comment]
Hey @sanpoChew I have pushed a fix, try and let me know if that works for you.

**Comment by sanpoChew** [comment]
@WellingGuzman that's fixed now, thanks a lot for the quick response!

**Comment by WellingGuzman** [comment]
@sanpoChew Thanks for the confirmation.
