### ISSUE TITLE
Applying Snapshot on CockroachDB fails

### ISSUE THREAD

**Issue by wodka** [directus/directus#13245]
### Describe the Bug

Trying to apply a snapshot that does create a table will always fail with CRDB.

20:52:42 🚨 error create table "test" ("id" uuid not null default null) - unimplemented: the first schema change statement in a transaction must precede any writes

in theory this should stop being an issue starting with CRDB 22.1 (https://github.com/cockroachdb/cockroach/pull/76279)

I am using a workaround to trigger the first schema change statement also when doing a schema apply with:

```
diff --git a/node_modules/directus/dist/utils/apply-snapshot.js b/node_modules/directus/dist/utils/apply-snapshot.js
index f7acdb8..74aa486 100644
--- a/node_modules/directus/dist/utils/apply-snapshot.js
+++ b/node_modules/directus/dist/utils/apply-snapshot.js
@@ -18,6 +18,7 @@ async function applySnapshot(snapshot, options) {
     const current = (_c = options === null || options === void 0 ? void 0 : options.current) !== null && _c !== void 0 ? _c : (await (0, get_snapshot_1.getSnapshot)({ database, schema }));
     const snapshotDiff = (_d = options === null || options === void 0 ? void 0 : options.diff) !== null && _d !== void 0 ? _d : (0, get_snapshot_diff_1.getSnapshotDiff)(current, snapshot);
     await database.transaction(async (trx) => {
+        await trx.raw('ALTER TABLE "directus_activity" RENAME TO "directus_activity"')
         const collectionsService = new services_1.CollectionsService({ knex: trx, schema });
         for (const { collection, diff } of snapshotDiff.collections) {
             if ((diff === null || diff === void 0 ? void 0 : diff[0].kind) === 'D') {
```

### To Reproduce

1. New Instance
2. Create Table
3. Create Snapshot
4. Delete Table
5. Apply Snapshot

### Errors Shown

20:52:42 🚨 error create table "test" ("id" uuid not null default null) - unimplemented: the first schema change statement in a transaction must precede any writes 

### What version of Directus are you using?

9.10.0

### What version of Node.js are you using?

16

### What database are you using?

CockroachDB

### What browser are you using?

-

### How are you deploying Directus?

Docker / Node

**Comment by rijkvanzanten** [comment]
Closing this in favor of [#13383](https://github.com/directus/directus/issues/13383)
