### ISSUE TITLE
CORS not working for POST requests (create item)

### ISSUE THREAD

**Issue by cedricve** [directus/directus#1324]
I'm trying to create an item through the API, however I get a CORS error message. It looks like for POST requests the allow-cors header is not send; it does work for GET requests.

      No 'Access-Control-Allow-Origin' header is present

![screen shot 2017-01-09 at 11 23 13](https://cloud.githubusercontent.com/assets/1546779/21763445/3fae2fde-d65e-11e6-8a61-bf781ab18da6.png)

**Comment by cedricve** [comment]
Hmm looks like this is something else, I get following error message

    Attempted to load new record post-insert with empty result. Lookup via row id

**Comment by cedricve** [comment]
@WellingGuzman were you able to reproduce?

**Comment by WellingGuzman** [comment]
Hey @cedricve , I've not been able to reproduce it.

What's the http request raw data? it is working for me using Postman.

**Comment by cedricve** [comment]
Hmm, tested it on another machine and it works now.. Sorry for this one. Looks good to me.

**Comment by WellingGuzman** [comment]
Glad to hear, if it pops out again, let us know.

**Comment by lastlink** [comment]
I'm  also getting this error. When I create a new user w/ an invalid email or an email already in use then I get a 404 or 403 error as well as a cors error. My front end is unable to read the response status b/c it's a cors error. It's hard to do validation & show different messages if it's a cors error.
