### ISSUE TITLE
Custom endpoint question

### ISSUE THREAD

**Issue by cedricve** [directus/directus#1325]
I'm trying to acces the custom endpoint at _example.php, but I don't know how I access this through an url. Can you guide me (it's not documented)?

![screen shot 2017-01-09 at 15 57 35](https://cloud.githubusercontent.com/assets/1546779/21770668/86e15c3e-d684-11e6-847d-b97e474faa45.png)

**Comment by WellingGuzman** [comment]
Hey @cedricve, you can get the `/example` endpoint by going to `your-host/api/example`.

I added a ticket to add documentation on how this work. https://github.com/directus/docs/issues/13

**Comment by cedricve** [comment]
Do I need to do something special? Get a page not available.

![screen shot 2017-01-09 at 18 01 30](https://cloud.githubusercontent.com/assets/1546779/21775261/b30c6c02-d695-11e6-8361-d14b49d463db.png)

**Comment by WellingGuzman** [comment]
oh yeah, you have to remove the `_` from `_example` so the file is called `example.php` instead of `_example.php`. all files starting with `_` are ignored.
