### ISSUE TITLE
Update Directus

### ISSUE THREAD

**Issue by ValonK** [directus/directus#1326]
Hello!

I just wanted to know how I can update my Directus without losing my Data?   I couldn't find any Documentation on that topic.

Version Info

Directus: Api Version 1.0
PHP version: PHP 7.0.14-1+deb.sury.org~xenial+1
MySQL version: Ver 14.14 Distrib 5.7.16,
Web server: Apache
OS: Ubuntu 16.04.1

**Comment by WellingGuzman** [comment]
We don't have any solution for update the core files unless you are using git, if so, you can `pull` the latest commit on any branch. You can also download the latest version replacing all the core files keeping in mind that `/customs`, `/storage` `api/config.php` and `api/configuration.php` can be overwritten and those are probably all the files that are not part of the core files in your installation.

**Comment by WellingGuzman** [comment]
You are welcome to join our [slack channel](https://slack.getdirectus.com/) for any help upgrading Directus.
