### ISSUE TITLE
Search typing issue - page get refresh while typing - Test data size is 20000 records in single collection

### ISSUE THREAD

**Issue by Jeyakumarrathnaselvi** [directus/directus#13260]
### Describe the Bug

Facing typing issue in search bar while typing. whenever i type few characters come and go

example if i type abcdefgh. it shows only **abcdfg**. e and h miss while page refresshing

### To Reproduce

It happens only in cloudron deployments
example if i type abcdefgh. it shows only **abcdfg**. e and h miss while page refresshing

### Errors Shown

characters missing

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

16.14.2

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

Cloudron

**Comment by koksikus** [comment]
I have a similar problem when searching when I have a field with relations (e.g. M2O), the last letter or number disappears when automatically refreshed, or when deleting, the last letter or number already appears. Besides, the search result is completely different from the correct results - it shows that he did not find the results when I know that there are over 20 of them, etc ...
Directus 9.10.0 and MS SQL

**Comment by azrikahar** [comment]
I believe this has the same root cause as #13157, so let's consolidate it over there.
