### ISSUE TITLE
Issue with editing/viewing 3rd party relationship

### ISSUE THREAD

**Issue by u12206050** [directus/directus#13262]
### Describe the Bug

When trying to edit/view an item on the "Persons" collection via a relationship, it comes up as wanting to create a new one, instead of editing it. Only the fields, that were apart of the display template are loaded into the form:

![edit_m2o_relation issue](https://user-images.githubusercontent.com/6641242/166633377-c729c7cf-9d4a-4f9f-8dc3-d71bef4c6cd2.gif)

This only seems to be happening on collections where the template contains a field that is within a group/alias.

Can confirm this worked in 9.8.0

### To Reproduce

- Setup three related entities `A<-O2M-B-M2O->C`
- On `C` create a group and place a field in there to use as label
- On `B` select that field as the template
- Create items in all three and select the item in collection `A`
- Then select the field that is related to B which should open it in the sidebar.
- In the side bare select the field that is related to C. Should now show edit item but instead it shows create new item.

### What version of Directus are you using?

9.10.0

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

chrome

### How are you deploying Directus?

Locally & GCP

**Comment by br41nslug** [comment]
This is the same underlying issue as #12881 and is fixed with this PR #13151
