### ISSUE TITLE
DB errors after update to 6.3.6

### ISSUE THREAD

**Issue by jhyle** [directus/directus#1327]
There seems to be a problem with hyphens in column names, e.g.

'Statement could not be executed (42S22 - 1054 - Unknown column 'Footer.E`-`Mail`-`Adresse' in 'field list')' in /home/www/bund/cms.remap-berlin.de/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:244

**Comment by WellingGuzman** [comment]
Hey @jhyle what's the name of your column `E-Mail-Adresse`?

This is an issue with Zend-Db we will try to do our best and find a solution, but feel free to report this on their repository.

**Comment by jhyle** [comment]
Well, it's  `E-Mail-Adresse`.

**Comment by WellingGuzman** [comment]
Thanks, I will have to take a Zend Db to fix this issue. I will get back to you as soon as I have a fix for this.

**Comment by jhyle** [comment]
There is another problem with columns with a hyphen: Saving them does not work. The named parameter gets the column name, unfortunately hyphens are not allowed in parameters.

**Comment by jhyle** [comment]
Is it possible to revert to a more stable version of Zend-Db?

**Comment by WellingGuzman** [comment]
@jhyle This has been an unsolved issue  in ZendDB, so as far as I know there's never been solved. 

I did a hotfix for a older version which probably can work for you: https://github.com/WellingGuzman/zend-db/tree/directus

When I got some time I will sit down and try to create a patch for this issue, for now that's the only thing I can do, I'm sorry.

**Comment by jhyle** [comment]
Thank you. I wonder why this problem shows up now, columns with hyphens did work for some time.

**Comment by WellingGuzman** [comment]
@jhyle we updated to the most recent version of Zend-Db, skipping our hotfix, I will be working on a hotfix soon, so this won't happen in the meantime, until we can try and make an PR to Zend DB.

I will let you know, so you update the zend db package.

**Comment by WellingGuzman** [comment]
Hey @jhyle,

Sorry for the delay, please check this commit https://github.com/directus/directus/commit/d0ba99fe8db5d0ae6914a21c89542ccf17e0febe and update your composer to install `directus-database` with an hotfixed zend-db that will allow you to use columns with dashes and spaces.

Remember to remove the `composer.lock` file to make sure it installs the new version and not the one on `composer.lock`

Let me know how it went.

**Comment by WellingGuzman** [comment]
I will close this, if this still happening I will re-open it.
