### ISSUE TITLE
Incorrect related item permissions validation when updating an item with GraphQL

### ISSUE THREAD

**Issue by adanielyan** [directus/directus#13287]
### Describe the Bug

I have 2 models, ```Profiles``` and ```Gender```. There is a M2O relationship from ```Profile``` to ```Sex```. I have a role "Authenticated". The role has a permission to create and edit Profiles. The Authenticated user cannot edit or create Sex. When I try to update a profile as Authenticated user and select a different gender with GraphQL I get this error:
```
Field "sex" is not defined by type "update_profiles_input".
```
However, if I allow role Authenticated to edit model ```Sex``` everything works.

The problem is that I don't want to allow Authenticated users to modify records in model Sex. I only want them to select Sex from a Profile. How can I do it?

### To Reproduce

1. Create 2 models with M2O relationship from one to another
2. Allow editing 1st model, and reading the second for a specific role
3. While logged in as a user with the role above try updating the related field in an item of the first model through GraphQL

### Errors Shown

Field "sex" is not defined by type "update_profiles_input

### What version of Directus are you using?

9.9.1

### What version of Node.js are you using?

18.0.0

### What database are you using?

Postgres

### What browser are you using?

Edge

### How are you deploying Directus?

AWS

**Comment by azrikahar** [comment]
This has been resolved in `9.10.0` by #13015 👍

## 9.9.1

https://user-images.githubusercontent.com/42867097/168407160-dbb179b9-e017-4e80-ae2c-5debc2ebb1b4.mp4


## 9.10.0

https://user-images.githubusercontent.com/42867097/168407155-5894d9dd-e827-4f7d-8d41-2bede29f0852.mp4

**Comment by adanielyan** [comment]
Thanks a lot for a quick response!

I updated to 9.10.0, but now I get a different error:
```
String cannot represent a non string value: {id: $sex}
```
I should say that all of the ID fields are UUIDs. When I run the same mutation as admin I don't get this error. 

Here is my mutation:

```graphql
mutation UPDATE_PROFILE($id: ID!, $sex: ID!) {
  update_profiles_item(id: $id, data: { sex: {id: $sex } }) {
    id
  }
}
```

**Comment by azrikahar** [comment]
It should be `data: { sex: $sex }` instead of nesting it, similar to the the example I shared earlier, because the user/role don't have permission to the related collection. Nesting as `{ id: $sex }` works on admin is correct as the admin has all permissions (so nesting is required to determine which field is actually being targeted).

**Comment by adanielyan** [comment]
Thank you, that worked! I wish the documentation on this was more clear.

**Comment by azrikahar** [comment]
To be fair, the introspection and autocomplete from a GraphQL explorer does indicate the difference of type. But I can definitely see how it can be helpful to bring it up in the docs just to be more explicit. PRs to improve the docs are always welcome!

## No permission (accepts the ID type)

Mine is showing `Int` here, but yours should be `String`.

![chrome_6JUdZyZoA1](https://user-images.githubusercontent.com/42867097/168408327-bff326b0-7274-4271-ba2b-c30d3d0c428e.png)

## Has permission (accepts an object)

![chrome_Uxtpw7I6gQ](https://user-images.githubusercontent.com/42867097/168408331-58d73b22-d598-42cb-9ba3-309ea4874602.png)
