### ISSUE TITLE
Can't change dashboard panel time series group precision from minute to anything else because changing it resets it back to minute

### ISSUE THREAD

**Issue by sxsws** [directus/directus#13289]
### Describe the Bug

Setting up a simple time series graph and trying to set group precision to hour instead of minute but when I do, it keeps being reset back to minute after save.

### To Reproduce

Set up a time series graph in a dashboard and change the precision from minute to something else.

### Errors Shown

None.

### What version of Directus are you using?

9.10

### What version of Node.js are you using?

12.22.5

### What database are you using?

mariadb

### What browser are you using?

firefox

### How are you deploying Directus?

local

**Comment by azrikahar** [comment]
I can't seem to reproduce this issue locally on v9.10.0:

https://user-images.githubusercontent.com/42867097/168449788-94f76ac1-ef79-42a4-9306-d7a9784fd092.mp4

Are you able to reproduce this on a fresh instance? Or perhaps it's somehow something unique to your current specific setup? Just wondering what are the different variables at play here 🤔 

I'll close this for now, but happy to continue debug/discuss further here, or re-open this issue when more information becomes available to reliably reproduce this.
