### ISSUE TITLE
Can't drag to reorder columns in a table (Chrome)

### ISSUE THREAD

**Issue by sanpoChew** [directus/directus#1328]
## Version Info
  - Directus version and branch: 6.3.6
  - PHP version: 7.0.14-2
  - MySQL version: 5.5.53
  - Web server: nginx
  - OS name and version: Arch Linux
  - Chrome Version 56.0.2924.51 beta (64-bit)

## Expected Behavior
The Ability to drag and drop columns by clicking on the = sign on the left hand side.

## Actual Behavior
When I try to drag a new tab opens and searches google with the following line:

```
drag_handle Sub Pages ⊣ Alias One to Many Translation arrow_drop_down tune swap_horiz close
```
changes slightly depending on the column dragged.

This is only happening on Chrome, I can drag columns in Firefox just fine. This may just be me as I'm running Wayland and Chrome doesn't seem to like it very much but I just thought I'd report it.

**Comment by WellingGuzman** [comment]
Thanks for reporting this, I honestly don't know what to do here, as it's probably Wayland, _even though I have never used it_, but if it's not, and there's a way to reproduce it let me know.

Either way I'm keeping an eye on it.

**Comment by benhaynes** [comment]
Hey @sanpoChew – we have not been able to reproduce this, and the drag-and-drop for Item Listings is refactored in the new version (6.4). Let us know if you're still getting this and we'll get it sorted!
