### ISSUE TITLE
Using Single type table with Single File field type breaks

### ISSUE THREAD

**Issue by HauntedSmores** [directus/directus#1329]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests please use the [Directus FeatHub](http://feathub.com/directus/directus) to make a new request or vote for existing ones, or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues.

## Version Info
  - Directus version and branch: (Or commit hash)
  - PHP version: 7
  - MySQL version: 5.7.16
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: OSX

## Expected Behavior
No errors saving images/tables regardless of type Single or regular

## Actual Behavior
When you create a new table with type Single and try to use the Single File Type it breaks with this error:

Server Error
This query failed: UPDATE `Test` SET `active` = '2', `undefined` = '1', `image` = '9', `id` = '1' WHERE `id` = '1'

## Steps to Reproduce
 1. Create new table
 2. Change type to Single
 3. Go to table and upload a local image file
4. Try to save table

**Comment by WellingGuzman** [comment]
Hey @HauntedSmores, unfourtunatelly I couldn't replicate it. Which version/branch are you on?

You told me this happen after a column was delete? doesn't this was part of the steps to reproduce it?

You create a column with a single file and changed it to single table?

**Comment by HauntedSmores** [comment]
I was on 6.3 I believe (just pulled a new build today). I tried reinstalling directus with a fresh DB and I was still getting that error right away.

**Comment by WellingGuzman** [comment]
@HauntedSmores can you provide me which fields (UI) are on the table?

**Comment by HauntedSmores** [comment]
1 standard text, 1 textarea, 1 single file

**Comment by WellingGuzman** [comment]
Hey @HauntedSmores, can you please pull the last commit from master and let me know if this commit 8d3a562 fixes it for you too.
