### ISSUE TITLE
Can't use sorting

### ISSUE THREAD

**Issue by Froelund** [directus/directus#1330]
Hello,

After altering my table with the sql stmt `ALTER TABLE Subjects ADD sort INT(11);`, a sorting interface appears as documented in [the documentation](https://docs.getdirectus.com/6.3.6/#Tables_&_Columns)

But when I try to use the feature, by dragging to reorder, I get a `Server Error: Rows no specified`

## Version Info
  - Directus version and branch: 6.3.6
  - PHP version: 7.1.0
  - MySQL version: 5.7
  - Web server: Apache
  - OS name and version: docker

I'm running [beevelop/directus](https://hub.docker.com/r/beevelop/directus/)

## Expected Behavior

The new order would be applied.

## Actual Behavior

The new order of items is not applied, and an error appears in the log.

## Logs or Screenshots

```
ERROR - 2017-01-16T12:32:34-05:00 - Exception: Rows no specified in /var/www/html/api/api.php:923
Stack trace:
#0 [internal function]: {closure}('Subjects')
#1 /var/www/html/vendor/slim/slim/Slim/Route.php(436): call_user_func_array(Object(Closure), Array)
#2 /var/www/html/vendor/slim/slim/Slim/Slim.php(1305): Slim\Route->dispatch()
#3 /var/www/html/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#4 /var/www/html/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#5 /var/www/html/api/core/Directus/Slim/CorsMiddleware.php(22): Slim\Middleware\MethodOverride->call()
#6 /var/www/html/vendor/slim/slim/Slim/Slim.php(1254): Directus\Slim\CorsMiddleware->call()
#7 /var/www/html/api/core/Directus/Application/Application.php(74): Slim\Slim->run()
#8 /var/www/html/api/api.php(1887): Directus\Application\Application->run()
#9 {main}
```

**Comment by WellingGuzman** [comment]
Thanks @Froelund for reporting this, I'm taking a look at this, and I will fix it as soon as possible.

**Comment by WellingGuzman** [comment]
Are sure you are on `6.3.6`?, if so, which branch are you using? This should've been fixed. Take a look here: https://github.com/directus/directus/issues/1313 and here https://github.com/directus/directus/commit/2f77f2eb98eb3f1573ce1587ccef927cb0c25590

If you just updated to the current version, please clear your Directus page browser cache.

Let me know how it went.

**Comment by Froelund** [comment]
Thanks for the response @WellingGuzman !

I'm quite sure, I am using [beevelop/docker-directus](https://github.com/beevelop/docker-directus) and in the Dockerfile it's fetching the the 6.3.6 tarball with [this](https://github.com/beevelop/docker-directus/blob/master/Dockerfile#L26) command 
```
curl -sL "https://api.github.com/repos/directus/directus/tarball/${DIRECTUS_VERSION}"
```

**Comment by WellingGuzman** [comment]
Thanks for letting me know I'm going to try myself and see, I will get back to you as soon as possible.

**Comment by Froelund** [comment]
Great

**Comment by WellingGuzman** [comment]
Hello @Froelund, I couldn't run directus using that docker, so I can't tell if it's installing the right version.

Would you mind to use this docker https://github.com/directus/directus-docker and see if you have any luck, as I'm thinking that this issue you are having is because you are using an older version, if it's not, I'm having a hard time replicating.

Please try with this docker and let me know, I'd love to get this solved.

**Comment by Froelund** [comment]
Okay @WellingGuzman . I'll test it.

**Comment by Froelund** [comment]
Thank you for the help @WellingGuzman , it works 👍

**Comment by WellingGuzman** [comment]
Amazing! Anything else let us know :)
