### ISSUE TITLE
Many-To-One field used in table list view causes wrong sql query

### ISSUE THREAD

**Issue by jhyle** [directus/directus#1331]
> Next exception 'Zend\Db\Adapter\Exception\InvalidQueryException' with message 'Statement could not be executed (SELECT `Teaser`.`id` AS `id`, `Teaser`.`active` AS `active`, `Teaser`.`Artikel` AS `Artikel`, `Teaser`.`Titel` AS `Titel`, `Teaser`.`Dachzeile` AS `Dachzeile`, `Teaser`.`Bild` AS `Bild`, `Teaser`.`Linkliste` AS `Linkliste`, `Teaser`.`Video` AS `Video`, `Teaser`.`Veranstaltungsliste` AS `Veranstaltungsliste`, `Teaser`.`Anriss` AS `Anriss` FROM `Teaser` LEFT JOIN `Artikel` ON .`Artikel`=`Artikel`.`id` WHERE `Teaser`.`active` IN (:where1, :where2) ORDER BY `Artikel`.`Titel` DESC LIMIT :limit OFFSET :offset - 42000 - 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '=`Artikel`.`id` WHERE `Teaser`.`active` IN ('1', '2') ORDER BY `Artikel`.`Titel`' at line 1)' in /home/www/bund/cms.remap-berlin.de/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:245

I think the table `Teaser` is missing after ON:  LEFT JOIN `Artikel` ON `Teaser`.`Artikel`=`Artikel`.`id`

**Comment by WellingGuzman** [comment]
Hey @jhyle can you show me how you configure that UI relationship? (Settings > Tables & Inputs > Teaser > Click on the arrow next to the The Many to One column

Or look for the record on the `directus_columns` table.

**Comment by jhyle** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/5750596/22057519/491c5eca-dd65-11e6-986c-c37deeee1e2c.png)

**Comment by WellingGuzman** [comment]
Hey @jhyle, When this error is happening to you?

**Comment by WellingGuzman** [comment]
I'm not being able to reproduce this error.

**Comment by jhyle** [comment]
The error occurs on the Teaser table list page. I have version 6.3.6 with the Zend-Db from https://github.com/WellingGuzman/zend-db/tree/directus installed.

**Comment by WellingGuzman** [comment]
Hey @jhyle if you try to access it from the api `http://your-host/api/1/tables/Teaser/rows` still show you some errors?

I'm trying to replicate this issue without luck.

**Comment by jhyle** [comment]
Hi @WellingGuzman ,

this seems to be a problem with the user preferences for the list view:

`mysql> select * from directus_preferences where directus_preferences.user = 1 and directus_preferences.table_name = 'Teaser';
+----+------+------------+-------+-----------------+---------+------------+--------+---------------+
| id | user | table_name | title | columns_visible | sort    | sort_order | status | search_string |
+----+------+------------+-------+-----------------+---------+------------+--------+---------------+
| 21 |    1 | Teaser     | NULL  | Dachzeile,Titel | Artikel | DESC       | 1,2    |               |
+----+------+------------+-------+-----------------+---------+------------+--------+---------------+
`

If I remove this, everything is fine.

**Comment by benhaynes** [comment]
Can we test this in 6.4 to see if it's still occurring? If not we can close...

**Comment by WellingGuzman** [comment]
@jhyle is this issue still happening to you, we did a clean up and it should working fine in 6.4 and probably on the development version of 6.3, I want to make sure this is fixed to prepare the patch release for 6.3.x.

**Comment by benhaynes** [comment]
It's been months with no follow-up. This should be working fine in `6.4` so we'll close this ticket. If anyone can replicate this issue in the latest version we can re-open – but we can't replicate it as of now.
