### ISSUE TITLE
Adding Collection on Presets & Bookmarks list is not persistent

### ISSUE THREAD

**Issue by Pachat** [directus/directus#13326]
### Describe the Bug

With the right +, it is possible to add the Collection column. But it disappears on refresh.

### To Reproduce

Add the Collection column to Presets & Bookmarks list. 
Refresh.

### Errors Shown

The Collection column disappeared from Presets & Bookmarks list. 

### What version of Directus are you using?

9.10.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

PostgreSQL 14.2

### What browser are you using?

Firefox

### How are you deploying Directus?

locally

**Comment by Jbmanllr** [comment]
I confirm and support this issue.

What version of Directus are you using?
9.11.0

What version of Node.js are you using?
16.14.0

What database are you using?
PostgreSQL 14.2

What browser are you using?
Chrome

How are you deploying Directus?
locally
