### ISSUE TITLE
Image editor size is wrong on subsequent opens

### ISSUE THREAD

**Issue by erondpowell** [directus/directus#13331]
### Describe the Bug

https://user-images.githubusercontent.com/62306630/168635282-c3b78fd2-6c46-4e2c-be16-e80681de373d.mov

### To Reproduce

The vid described the issue. Go into a photo's Item detail page, click "edit", exit, click "edit" again and the sizing is reduced until you leave the Item Page for that image.

### Errors Shown

No errors in console.

### What version of Directus are you using?

Cloud 9.9.1

### What version of Node.js are you using?

cloud

### What database are you using?

cloud

### What browser are you using?

chrome

### How are you deploying Directus?

cloud

**Comment by rijkvanzanten** [comment]
@erondpowell Can you share that particular image that's causing this? I can't seem to reproduce this

**Comment by rijkvanzanten** [comment]
https://user-images.githubusercontent.com/9141017/168642832-0f0fbdc8-b29e-4218-83ce-67e8793e3cc3.mp4

**Comment by erondpowell** [comment]
@rijkvanzanten It happens for ALL images... on my cloud `example` project. Perhaps this should get moved over to Cloud?

**Comment by rijkvanzanten** [comment]
Closing this for now as I believe it has been resolved in 9.10+. We'll keep debugging on your example instance 👍🏻
