### ISSUE TITLE
Redireecting Issue, Version Issue

### ISSUE THREAD

**Issue by globallog** [directus/directus#1335]
Hello, i installed yesterday "directus_build" on my webserver, it started correctly and i have done all the installation steps, including db connection, it was successfull, but then immideately i got the "redirect loop issue" - ive gone through the docs i found here but no cookie deleting nor a missing column in the database was the source of this redirecting loop

could anybody help please?

btw. or do i need to upload the "directus version 6.3.6" i.e. on my webserver? because i have done this today and when i goto the dir over webbroswer absolute nothing appears, but it redirects directly to ../installation/index.php?step=0 but page is absolutely blank (FF)

greetz from cologne

----------------------------------------------------------------------------------------

**Comment by WellingGuzman** [comment]
Hello @globallog,

When this happens is more likely to be a confusion with directus path value. 

What's on your `DIRECTUS_PATH` on `api/config.php`? it should be `/` if you copied your Directus files in your root, otherwise the path of the sub-directory.

**Comment by globallog** [comment]
Hi, there is no config.php in that direcotry, just an config_example.php

and there is

 

define('DIRECTUS_PATH', '/directus/');


 

 

 


Gesendet: Sonntag, 22. Januar 2017 um 23:03 Uhr
Von: "Welling Guzmán" <notifications@github.com>
An: directus/directus <directus@noreply.github.com>
Cc: globallog <gotlife@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [directus/directus] Redireecting Issue, Version Issue (#1335)


Hello @globallog,

When this happens is more likely to be a confusion with directus path value.

What's on your DIRECTUS_PATH on api/config.php? it should be / if you copied your Directus files in your root, otherwise the path of the sub-directory.

**Comment by WellingGuzman** [comment]
Sorry for the late response @globallog.

Is there anything in your logs `api/logs`? on the first step, what do you set `Directus Path` to?

~ Welling

**Comment by benhaynes** [comment]
Hey @globallog – this seems like a `DIRECTUS_PATH` issue with your config. We;ll close this ticket since it's been a few months without a response. Let us know if the issue persists and we'll re-open!
