### ISSUE TITLE
Related item duplication on update

### ISSUE THREAD

**Issue by terion-name** [directus/directus#13369]
### Describe the Bug

Given models `items`, `orders`,`order_slots`

`Order` has many `order_slots`,  `order_slot` has one (`many-to-one` relation) `item`

Adding to `order` an `order_slot` with an `item` is ok. But updating this `order slot` (changing number for example) results in creation of new `item` with name (the field in relation's display) only 

### To Reproduce

Made a screencast to show: 

[![Alt text](https://img.youtube.com/vi/egJCsW_2G6w/0.jpg)](https://www.youtube.com/watch?v=egJCsW_2G6w)

### What version of Directus are you using?

9.10.0

### What version of Node.js are you using?

16.2.0

### What database are you using?

mysql

### What browser are you using?

brave

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
Should be duplicate of #12881, and it was resolved by #13151 (planned for next release after `9.10.0`) 👍

**Comment by terion-name** [comment]
@azrikahar oh. really a dup, didn't find
any ETA on release? it's kinda a critical bug

**Comment by azrikahar** [comment]
No ETA yet, but tentatively should be after Data Flows gets merged.

**Comment by terion-name** [comment]
@azrikahar but this is a critical bug :(( waiting for a such big feature finish to publish a critical patch?

**Comment by benhaynes** [comment]
Data Flows is planned for release this week. Also, prioritization triage is more complicated than it seems, taking into consideration paid sponsor work, which takes priority.
