### ISSUE TITLE
Even with 24 hour time selected, time field shows as 12 hour with a/p suffixed on views

### ISSUE THREAD

**Issue by sxsws** [directus/directus#13373]
### Describe the Bug

Even with 24 hour time selected, it shows as 12 hours with a suffix in a record's detail and index view.

### To Reproduce

create a collection with a time field, enable 24 hours time, create a record with any time, view it in detail or index view

### Errors Shown

--

### What version of Directus are you using?

9.10

### What version of Node.js are you using?

12.22.5

### What database are you using?

mariadb

### What browser are you using?

firefox

### How are you deploying Directus?

local

**Comment by azrikahar** [comment]
The display configuration is actually different from the interface configuration, so we will need to configure the display for places such as the content overview page (or index view presumably that's what you meant). Here's a quick example:

https://user-images.githubusercontent.com/42867097/168975045-5ed83897-a846-496e-b0e1-e5e27daf15c9.mp4

Shoutout to @rijkvanzanten for adding the possibility to enter custom datetime format in display options in #13099 🙌

**Comment by sxsws** [comment]
There's a directus gotcha! Thanks for the video!
