### ISSUE TITLE
Question regarding filters and admins.

### ISSUE THREAD

**Issue by the-pinky-man** [directus/directus#1337]
As per the documentation, if I do the following request:

```
$ curl -g https://instance--key.directus.io/api/1.1/tables/directus_users/rows?filters[email][like]=@rngr.org \
        -u [user-token]:
```

As an administrator, the results are not filtered - I get all users. Is this intended - ie does being an admin trump the use of a filter?

Thanks.

## Version Info
  - Vagrant with 6.3

## Expected Behavior
Unsure

## Steps to Reproduce
 n/a

## Logs or Screenshots
n/a

**Comment by WellingGuzman** [comment]
Hey @the-pinky-man, how and where are you executing this endpoint, it's working on my end.

**Comment by the-pinky-man** [comment]
Heya @WellingGuzman - it's a fresh-ish provision from the vagrant directus repo. All I have done is add a few extra users and groups. here is my endpoint:

`curl -g "http://192.168.33.6/api/1/tables/directus_users/rows?filters[email][like]=@gmail.com -u xFC3uP7M4hSaWXWTt1ooYnFTM0JXtqwL`

Let me know if you see anything wrong with that. Failing that might try a fresh VM.

Thanks
Mat.

**Comment by WellingGuzman** [comment]
@the-pinky-man you are using api version 1, you should be using `1.1`.

`http://your-host/api/1.1/tables/directus_users/rows?filters[email][like]=@gmail.com`

**Comment by the-pinky-man** [comment]
@WellingGuzman that resolved it, my bad. thanks mate.

**Comment by WellingGuzman** [comment]
Glad to hear @the-pinky-man :)
