### ISSUE TITLE
API 1.1 Unable use OR Like for searches

### ISSUE THREAD

**Issue by AwakenTheJaken** [directus/directus#1338]
## Version Info
  - 6.3.6
  - PHP version: 7

First of all thank you so much for this absolutely AWESOME application! I seem to have run into a bit of a gotcha though. Maybe one of you gurus could point me in the right direction!

## Expected Behavior
Unable to search columns with OR LIKE. ie: searching blog title and blog description using a search query.
`WHERE post_title LIKE %whatever% OR description LIKE %whatever% LIMIT 200 OFFSET 0`

## Actual Behavior
When using:
`filters[title][like]=whatever&filters[description][like]=whatever`
The sql results in:
`WHERE post_title LIKE %whatever% AND description LIKE %whatever% LIMIT 200 OFFSET 0`
Which seems like the expected behavior, however what if I wish to compare multiple columns? We would somehow need to add the filter or_like.

Thanks again!

**Comment by WellingGuzman** [comment]
Thanks @AwakenTheJaken, I will be adding this option soon. I will let you know when it's integrate.

**Comment by stevepatter** [comment]
What about something more generic than or_like?

Judging from other frameworks, it'd be good to have some kind of bracketing/subqueries/nested queries so query elements are joined together in the right priority, I'm thinking of query syntax roughly like this:

```
            'filters' => [
                'to' => [
                    'eq' => 1,
		    'before' => '(',
		    'after' => 'OR'
                ],
                'from' => [
                   'eq' => 1,
   		   'after' => ')'
                ]
            ],
```
to make   `WHERE (to = 1 OR from = 1)`

**Comment by benhaynes** [comment]
Just adding these ideas here in case they inspire someone, but the structure is different so this would have to be for v1.2 or be a NEW filter param that sits alongside the current one (so it doesn't break backwards compatibility):

```
'filters' => [
	'or' => [
		'to' => ['eq' => 1],
		'from' => ['eq' => 1]
	],
	'and' => [
		'active' => ['eq' => 1]
	]
],
```

```
'filters' => [
	[
		'to' => [
			'eq' => 1
		],
		'operator' => 'or',
		'from' => [
			'eq' => 1
		]
	]
],
```

**Comment by WellingGuzman** [comment]
Hey @AwakenTheJaken, @stevepatter made a PR that implements logical and/or works (https://github.com/directus/directus/pull/1519)

Maybe there could be a cleaner way, I don't like the `'before' => '(',` and `'after' => ')'` parts.

I can't think of any now, but a way to group the conditions/filters without explicitly saying how to group it should be the best bet.

We can keep the conversation, or open a new ticket to talk about the possible solutions, but I will close the ticket.
