### ISSUE TITLE
Several "single file" columns in same table

### ISSUE THREAD

**Issue by fabhenrich** [directus/directus#1339]
## Version Info
  - Directus version and branch: 6.3.5
  - PHP version: 5.5.38
  - MySQL version: 14.14
  - Web server: Apache
  - OS name and version: Debian 7.11

## Expected Behavior
When having a table with several "single file" columns, they are all managed in the same way (display and API)

## Actual Behavior
The first "single file" column appears as an object in the API, and if it contains an image, it is displayed.
The second and others "single file" columns appear as an objet Id, and the image is not displayed

## Steps to Reproduce
 1. Create a table with 2 single files columns
 2. Add a new element in this table, set 2 images and save
 3. Open the element
 4. Only the first image is displayed
 5. When getting the element with the API, the first coloumn is an object, the second one is just the id of the object

## Logs or Screenshots
![directus_1](https://cloud.githubusercontent.com/assets/25365167/22371762/3d48ef56-e499-11e6-9ba5-497c6ae6c313.jpg)
![directus_2](https://cloud.githubusercontent.com/assets/25365167/22371765/3d4da4e2-e499-11e6-8b66-eb9bb81095b2.jpg)
![directus_3](https://cloud.githubusercontent.com/assets/25365167/22371764/3d4b8c34-e499-11e6-9af7-bfc4a9b1045b.jpg)
![directus_4](https://cloud.githubusercontent.com/assets/25365167/22371763/3d4b70b4-e499-11e6-8e10-d35497da6edb.jpg)

**Comment by WellingGuzman** [comment]
Hey @fabhenrich, this should've been fixed in 6.3.6.

Give it a try and let us know.

**Comment by fabhenrich** [comment]
Fixed approved, thanks for your reply :)
