### ISSUE TITLE
Schema apply --dry-run not working

### ISSUE THREAD

**Issue by pierreavn** [directus/directus#13403]
### Describe the Bug

From the [CLI documentation](https://docs.directus.io/reference/cli/#applying-a-snapshot), when applying a snapshot with the `--dry-run` parameter, an error occurs : 

```
error: unknown option '--dry-run'
```

### To Reproduce

1. Snapshot the data model: `npx directus schema snapshot ./snapshot.yaml`
2. Apply the snapshot with dry run: `npx directus schema apply --dry-run ./snapshot.yaml`

### Errors Shown

```
error: unknown option '--dry-run'
```

### What version of Directus are you using?

CLI v9.4.3

### What version of Node.js are you using?

14.19.0

### What database are you using?

Postgres 14.2

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
The `--dry-run` flag was added in #12006 which was released in `9.7.0`, so do make sure to update to at least that version, or preferably the latest version in case there's any other features that may be missing for you in `9.4.3`. 

I'll close this for now, but do let us know if this issue still persists once you are at least on `9.7.0`.
