### ISSUE TITLE
All Tables/Columns in Settings should show the "raw" name on hover

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1340]
For example:

![screen shot 2017-01-27 at 12 27 24 pm](https://cloud.githubusercontent.com/assets/522079/22380677/3bd961ee-e48c-11e6-933c-59c545d2430b.png)

All tables and columns within Settings should show the raw/actual name in the title attribute on hover (and the datatype if applicable).

**Comment by rijkvanzanten** [comment]
Could you elaborate? As your screenshot implies as well; isn't this already implemented?

**Comment by benhaynes** [comment]
That's the only place it's been done – but it's missing in all the other places within Settings.

**Comment by malindamiller** [comment]
I would be interested in taking this.  Is it done already? If not could I get a hint about which files to start in?

**Comment by benhaynes** [comment]
Hey @malindamiller – it's not done, and we'd love the help!

Most, if not all, of these Settings templates are located here:

https://github.com/directus/directus/tree/master/app/templates/modules/settings

Thanks for the help!

**Comment by benhaynes** [comment]
OK, all of these have been updated (title and datatype)... if we find more we should add them
