### ISSUE TITLE
Bearer / Basic Auth Authentication failing

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1341]
## Version Info
  - Directus version and branch: 6.3.6 development f68c97f 
  - PHP version: 5.6.28
  - MySQL version: 5.6.34
  - Web server: Nginx (MAMP PRO)
  - OS name and version: Mac OS Sierra

## Expected Behavior
`curl -u key123: http://local.directus/api/1.1/tables/test/` or `curl -H "Authorization: Bearer key123" http://local.directus/api/1.1/tables/test/` to return entries

## Actual Behavior
Returns 401 `You must be logged in to access the API`

## Steps to Reproduce
![screen shot 2017-01-28 at 3 10 55 pm](https://cloud.githubusercontent.com/assets/9141017/22397174/00e4bd0a-e56c-11e6-85ff-8767d5dce3e3.png)

**Comment by WellingGuzman** [comment]
Hey @rijkvanzanten I've tried to replicate this issue and I could get the expected results on both Bearer and Basic authentication, I've been checking what could possible go wrong, but it should only fail on failed authentication, but you got a successful authentication with `access_token`

I will see if I can find the problem and I will get back to you as soon as possible.

**Comment by WellingGuzman** [comment]
Hey @rijkvanzanten, could you help me reproduce this issue?

**Comment by rijkvanzanten** [comment]
Sure! What would you like to know? It happened to me on a clean install of Directus 6.3.6. I'll check if the error is still there on the latest master and 6.4. I'll let you know

**Comment by WellingGuzman** [comment]
how I can produce it, I was working as expected to me, so I would like to know how are you trying to use it that it failed.

**Comment by benhaynes** [comment]
Pinging @rijkvanzanten 🔔

**Comment by rijkvanzanten** [comment]
✋ It is still a problem:
```
~/Development/directus-6.3 master
❯ curl -u lDNlwpVk4IBhdPIEdYrzhMMvl1K45Tu8: http://6.3.directus.com/api/1.1/tables/test/
You must be logged in to access the API

~/Development/directus-6.3 master
❯ curl -H "Authorization: Bearer lDNlwpVk4IBhdPIEdYrzhMMvl1K45Tu8" http://6.3.directus.com/api/1.1/tables/test
You must be logged in to access the API

~/Development/directus-6.3 master
❯ curl http://6.3.directus.com/api/1.1/tables/test\?access_token\=lDNlwpVk4IBhdPIEdYrzhMMvl1K45Tu8
{"success":true,"meta":{"type":"entry","table":"directus_tables"},"data":{"id":"test","name":"test","table_name":"test","columns":[{"id":"id","name":"id","column_name":"id","type":"INT","length":null,"precision":10,"scale":0,"sort":1,"default_value":null,"nullable":false,"key":"PRI","extra_options":[],"options":[],
"table_name":"test","required":true,"ui":"numeric","hidden_list":false,"hidden_input":false,"relationship":null,"comment":""},{"id":"active","name":"active","column_name":"active","type":"INT","length":null,"precision":10,"scale":0,"sort":2,"default_value":"2","nullable":false,"key":"","extra_options":[],"options":
[],"table_name":"test","required":false,"ui":"numeric","hidden_list":false,"hidden_input":false,"relationship":null,"comment":""},{"id":"text_test","name":"text_test","column_name":"text_test","type":"VARCHAR","length":null,"precision":0,"scale":0,"sort":9999,"default_value":null,"nullable":true,"key":"","extra_opt
ions":[],"options":[],"table_name":"test","required":false,"ui":"textinput","hidden_list":false,"hidden_input":false,"relationship":null,"comment":""}],"primary_column":"","schema":"directus_6_3","hidden":false,"single":false,"default_status":"0","user_create_column":null,"user_update_column":null,"date_create_colu
mn":null,"date_update_column":null,"created_at":"2017-05-09 18:25:13","date_created":null,"comment":"","row_count":2,"footer":false,"list_view":null,"column_groupings":null,"filter_column_blacklist":null,"preferences":{"id":14,"user":1,"table_name":"test","title":null,"columns_visible":"text_test","sort":"id","sort
_order":"ASC","status":"1,2","search_string":null}}}
```

This is on a clean installation of the [latest `6.3` from the `master` branch](https://github.com/directus/directus/commit/2890e9d473a8cd9bb99a9782265b29f28627718b).

## Steps to reproduce
1. Clone the repo
2. Create MAMP host w/ PHP `5.6.28`
3. Install Composer dependencies
4. Go to the url in the browser (in my case `http://6.3.directus.com`)
5. Go through the installation process
6. Try the three ways of authorizing

**Comment by WellingGuzman** [comment]
This will need some serious debugging, I still not able to reproduce it. I will review all the alternatives why this could happen.
