### ISSUE TITLE
Image is not shown and cannot be updated

### ISSUE THREAD

**Issue by martinptacek** [directus/directus#13425]
### Describe the Bug

I have a collection containing image field. When I create a new article, I can upload or select an existing picture. When I display the detail of collection (the form), image is not visible and cannot be changed.

### To Reproduce

Create a collection containing image
Create a new record and upload a picture
See the detail of uploaded picture
<img width="787" alt="Screenshot 2022-05-20 at 3 19 39" src="https://user-images.githubusercontent.com/5970499/169429574-e4ef72d4-1035-41f8-8471-4a652e6e66ab.png">

### What version of Directus are you using?

9.9.1

### What version of Node.js are you using?

16.14.2

### What database are you using?

cloud standard db

### What browser are you using?

chrome

### How are you deploying Directus?

cloud standard

**Comment by azrikahar** [comment]
I can't seem to reproduce this locally on 9.10.0:

https://user-images.githubusercontent.com/42867097/169530484-bee5fd7e-7f72-44e6-a96f-8b034c9a7c76.mp4

Just curious, although the image seems to be not visible for you, are you able to view the raw value? Here's an example:

https://user-images.githubusercontent.com/42867097/169530633-3025a320-f56c-439e-9ade-9a8ca72a8556.mp4

**Comment by martinptacek** [comment]
Hello Azri,
attaching the screencast where you can see how it behaves.
https://1drv.ms/v/s!AhyzDnhhtOWohsIWQz2JYnjmPTZ4jA?e=FCNaEP

When I change the way how it is displayed, it looks like this:
***@***.***

S pozdravem,
Martin Ptacek


From: Azri Kahar ***@***.***>
Date: Friday, 20 May 2022 15:50
To: directus/directus ***@***.***>
Cc: Martin Ptacek ***@***.***>, Author ***@***.***>
Subject: Re: [directus/directus] Image is not shown and cannot be updated (Issue #13425)

I can't seem to reproduce this locally on 9.10.0:

https://user-images.githubusercontent.com/42867097/169530484-bee5fd7e-7f72-44e6-a96f-8b034c9a7c76.mp4<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F42867097%2F169530484-bee5fd7e-7f72-44e6-a96f-8b034c9a7c76.mp4&data=05%7C01%7C%7Cc7ff8a9194d24dfedb9808da3a67be61%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637886514492680491%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oJWW4z4icDfQnXp5A4dFioVtpgYsSm%2FINEPQxnhpKpM%3D&reserved=0>

Just curious, although the image seems to be not visible for you, are you able to view the raw value? Here's an example:

https://user-images.githubusercontent.com/42867097/169530633-3025a320-f56c-439e-9ade-9a8ca72a8556.mp4<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F42867097%2F169530633-3025a320-f56c-439e-9ade-9a8ca72a8556.mp4&data=05%7C01%7C%7Cc7ff8a9194d24dfedb9808da3a67be61%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637886514492680491%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BEI5uf80DXSCpusKw2dNezfmOTGYmEtDR7dlhUUIAyM%3D&reserved=0>

**Comment by joselcvarela** [comment]
Hey @martinptacek 
For cloud issues or questions, please head to our website and ask for support on chat: https://directus.io

Thank you.
