### ISSUE TITLE
Single-sign-on?

### ISSUE THREAD

**Issue by PolywickStudio** [directus/directus#1342]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests please use the [Directus FeatHub](http://feathub.com/directus/directus) to make a new request or vote for existing ones, or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues.

## Version Info
  - Directus version and branch: (Or commit hash)
  - PHP version: 
  - MySQL version: 
  - Web server: (Ex. Apache, nginx or IIS?) 
  - OS name and version: 
N/A

## Expected Behavior
Is there a way to login via FB or Google? We'd like to use DirectUs admin using SSO.

## Actual Behavior
Right now there is login/password system. Would like to be able to have SSO as well.

## Steps to Reproduce
 1. 
 2. 
 3.

**Comment by benhaynes** [comment]
Hey @PolywickStudio – thank you for submitting this. New features should be submitted and voted on at FeatHub. This has already been requested, so feel free to upvote!

http://feathub.com/directus/directus/+43

Also, I should mention that this feature is being added into the next release of Directus (`6.4`)! So you should be able to review this in a few weeks!
