### ISSUE TITLE
All DB tables in html source

### ISSUE THREAD

**Issue by sanklamm** [directus/directus#1343]
Don't you think it is bad practice to dump all tables from the directus-db into the html source to decide later which of them to display? All users can see all tables **including the users table with email adresses, hashed passwords and salt**!

I really have to say that I am baffled by this.

**Comment by WellingGuzman** [comment]
Really true, we have in mind to solve this in the next version.

In the next minor version we will be hiding hashed passwords and salt, and about tables it should only be seen the table the user has permission to see.

Thanks for letting us know, and we apologies for any inconveniences this may had raise.

**Comment by WellingGuzman** [comment]
Hey @sanklamm I fixed this and only the current user can see they own private user info.

Thanks for pointing this out to us.
