### ISSUE TITLE
Primitive filters (_gte, _neq etc.) should not only accept integers

### ISSUE THREAD

**Issue by jeengbe** [directus/directus#13449]
### Describe the Bug

https://github.com/directus/directus/blob/fa6d9cde22d3a9f2ced42200fd3edb95bbf89846/api/src/utils/validate-query.ts#L110-L112

It makes little sense to limit `value` to integers.

Sure, this may lead to problems with ridiculously precise numbers, but that's an issue that could be dealt with differently than just forbidding all non-integers, as there clearly is no issue on Directus' side of the implementation and the issue would rather lie with the database:
https://github.com/directus/directus/blob/fa6d9cde22d3a9f2ced42200fd3edb95bbf89846/api/src/utils/apply-query/operators/greather-than-equals.operator.ts#L5-L7

### To Reproduce

n/a

### Errors Shown

n/a

### What version of Directus are you using?

fa6d9cd

### What version of Node.js are you using?

n/a

### What database are you using?

n/a

### What browser are you using?

n/a

### How are you deploying Directus?

n/a

**Comment by azrikahar** [comment]
I don't have the full context myself, but it seems to be "moved" to `validate-query` in #10138. However, would you mind providing a quick example on how were you coming across this error? It seems like typically query params are string so they are still not yet cast during `validate-query` (so this Number check wasn't applied), not until later on in `apply-query` after the addition of #12514. Perhaps you were using readByQuery in extensions?

**Comment by jeengbe** [comment]
I was using the JS SDK with TypeScript, which forbid assigning `string` to a `_gte` field.
Plugging in strings despite TS's warning seems to work all fine. Seems like this issue is nested further down in processing of string arguments.

**Comment by rijkvanzanten** [comment]
It's not limiting the compare value to just integers? 

If we look at the whole function:

https://github.com/directus/directus/blob/fa6d9cde22d3a9f2ced42200fd3edb95bbf89846/api/src/utils/validate-query.ts#L100-L121

It checks that the value has to be a string, number, boolean, or date. If the value is passed as a JavaScript integer, we make sure that it's not NaN, and that it's within the range of ints that JavaScript can handle (to prevent other issues). If a number is passed in a string (which would be the default for query parameters anyways) it's not validated against the number check 👍🏻 

As for the SDK typescript improvements, feel free to open a PR or feature request detailing the improvement 🙂
