### ISSUE TITLE
when deleting a file collection field, the relevant data isn't removed from directus tables

### ISSUE THREAD

**Issue by sxsws** [directus/directus#13458]
### Describe the Bug

After removing a file collection field on a table, the following isn't removed:
- the file collection table
- the records from directus_fields
- records from directus_relations
- record from directus_collections

### To Reproduce

as above

### Errors Shown

none

### What version of Directus are you using?

9.10

### What version of Node.js are you using?

12.22.5

### What database are you using?

mariadb

### What browser are you using?

firefox

### How are you deploying Directus?

local

**Comment by azrikahar** [comment]
By "file collection field", I assume you mean the Files field? As I assume "file collection table" is the junction table created. 

> the records from directus_fields

Does this mean the files field itself isn't being deleted?

Aside from that, I think this may somewhat relate to #12395, particularly the reasoning described here: https://github.com/directus/directus/issues/12395#issuecomment-1079380863. 

With that said, attaching screenshot(s) or a short clip(s) in every issue reports would often help to convey things easier! 👍

**Comment by rijkvanzanten** [comment]
I added / removed a file field to/from my collection, and it seems like directus_fields / directus_relations is cleaned up as expected. I'll close this for now 👍🏻
