### ISSUE TITLE
Unable to delete the only remaining field condition

### ISSUE THREAD

**Issue by koksikus** [directus/directus#13451]
### Describe the Bug

After updating to 9.11.0, you cannot delete the conditions for a field. In version 9.10.0 it worked.

![Zrzut ekranu 2022-05-20 183456](https://user-images.githubusercontent.com/90528895/169572921-1485626f-be15-4912-8d78-c83260f9c1d9.jpg)

### To Reproduce

Create a condition for the field and then try to delete it.

### What version of Directus are you using?

9.11.0

### What version of Node.js are you using?

16.15

### What database are you using?

Sql server 2017

### What browser are you using?

Edge

### How are you deploying Directus?

locally

**Comment by koksikus** [comment]
Hey now there is another problem after updating to 9.11.1 - well, I can't save the first condition even cancel it...

https://user-images.githubusercontent.com/90528895/170292587-c022dbce-0660-470d-b66d-f0f39a168c5b.mp4

**Comment by azrikahar** [comment]
@koksikus thanks for pointing that out. #13563 should fix this 👍
