### ISSUE TITLE
404 error on requests

### ISSUE THREAD

**Issue by hpohlmeyer** [directus/directus#1346]
## Version Info
  - Directus version and branch: 2b333d5 (master)
  - PHP version: 7.0.10
  - MySQL version: 5.6.28
  - Web server: Apache
  - OS name and version: MacOS Sierra (10.12.3)

## Expected Behavior
After visiting a URL (e.g. http://my-site.dev/users) the right page should load.

## Actual Behavior
A 404 error gets returned.
It is the same for other pages and for api requests (curl).

## Additional Information
The 404 error even occurs directly after the installation of Directus.
I can go through the admin panel, by following the links, but if I refresh the page I get a 404 error.

I thought this may be a mod_rewrite issue, but mod_rewrite got reported as active during the install.
I noticed, that there is no `.htaccess` file in the Directus root directory. Is that right?

Several reinstalls with different configurations did not help either.

## Steps to Reproduce
 1. Log In to Directus
 2. Visit any page
 3. Refresh the page

## Logs or Screenshots
![directus-error 1](https://cloud.githubusercontent.com/assets/6564077/22627437/7cc0c4ac-ebc3-11e6-95a4-56ec4e00e9d2.gif)

**Comment by WellingGuzman** [comment]
Hey @hpohlmeyer thanks for reporting this.

> I noticed, that there is no .htaccess file in the Directus root directory. Is that right?

No, that's no right. it should have a `.htaccess` file.

**Comment by hpohlmeyer** [comment]
Ok, thanks, I seem to have missed the .htaccess file, while copying the data.
Now everything works fine. :)

**Comment by WellingGuzman** [comment]
Glad to hear 👍

**Comment by hjbarraza** [comment]
I tried 
1. uploading to file library (works)
2. choosing from existing (opens new window)
2.1. it loads the file selection page, but immediately, reloads the previous screen
