### ISSUE TITLE
Inconsistent nested filter results on O2M

### ISSUE THREAD

**Issue by mattbisme** [directus/directus#13469]
### Describe the Bug

Given a scenario where I want to query "customers who have incomplete tickets," here is some GraphQL that worked on a previous version of Directus:

```graphql
query customers_with_working_tickets {
  customers(
    filter: {
      tickets: {
        status: { _eq: "incomplete" }
      }
    }) {
    id
    status
    first_name
    tickets {
      id
      status
    }
  }
}
```
This same GQL now pulls data, even when a customer has no tickets (the response):

```json
{
  "data": {
    "customers": [
      {
        "id": "c3451cd0-6e5c-45e3-a14b-16755e638993",
        "status": "active",
        "first_name": "Matthew",
        "tickets": [
          {
            "id": "0a77b080-9e98-4f78-8d4c-9dc73d8878c0",
            "status": "incomplete"
          },
          {
            "id": "0d67ec9e-d2d8-4d31-86b8-f2124d18cec4",
            "status": "incomplete"
          }
        ]
      },
      {
        "id": "zNUYqxCVF2ADzI5xwjzo",
        "status": "active",
        "first_name": "Kevin",
        "tickets": []
      }
    ]
  }
}
```

Note that the second result ("Kevin") has no tickets. There are, in fact, no tickets assigned to Kevin (I checked), but his result still appears in the list.

However, if I were to change the `status` in the filter to `_eq: "not-a-real-status"` I would, correctly, get zero results. I'm not sure at what point this behavior changed; this actually went unnoticed for a while. But it can be the difference between hundreds vs thousands of results, as you might imagine.

### To Reproduce

Query a collection with an O2M/Alias field using a nested filter that touches the O2M collection.

### Errors Shown

No errors are shown; only incorrect results.

### What version of Directus are you using?

9.11.0

### What version of Node.js are you using?

14.19.1

### What database are you using?

SQLite 3.17.0

### What browser are you using?

Paw (for GraphQL queries)

### How are you deploying Directus?

locally

**Comment by 3615alexis** [comment]
Same issue here : nested filters not working anymore after the upgrade from 9.10.0 to 9.11.0, on relational fields.

In some cases, the filter is just not working anymore => when I use "[_eq]" operator
And in some other cases, it throws an error, see below => when I use "[_neq]" operator

Example : 
If I have the structure below : 
![image](https://user-images.githubusercontent.com/6710698/169689977-7a1702f5-c95d-4979-9715-d8e69cd36d05.png)

And if I add this [_neq] filter : 
&filter[brands_featured][brands_id][slug][_neq]=3615-alexis

I get the following error : 
![image](https://user-images.githubusercontent.com/6710698/169690172-9afa0a13-bb1f-4d2f-8c21-4fd6a74bccc6.png)
Some kind of "mix" is happening between the operator and the field I want to filter.

And if add the [_eq] filter instead : 
&filter[brands_featured][brands_id][slug][_eq]=3615-alexis

I don't have an error but the filter is just not applied. I get all the N-N records.

![image](https://user-images.githubusercontent.com/6710698/169690157-a48e8bb5-aa3b-4afb-a43a-862f5115d9b6.png)

**Comment by CoenWarmer** [comment]
Same here, after upgrading to Directus 9.11.0 our nested filter is broken.  We're using Postgres. 

This used to work:
<img width="410" alt="Screenshot 2022-05-23 at 10 48 47" src="https://user-images.githubusercontent.com/535564/169781218-028d8000-54af-47a9-a512-3f2ec5c580cc.png">


Now only the top level works:
<img width="410" alt="Screenshot 2022-05-23 at 10 45 29" src="https://user-images.githubusercontent.com/535564/169780675-e1a56269-2ef7-401e-8f7b-54b433020d32.png">

Error I get when I attempt a very simple nested filter:
<img width="402" alt="Screenshot 2022-05-23 at 10 45 45" src="https://user-images.githubusercontent.com/535564/169781344-1b921145-b231-414c-9be0-1d754ffc493e.png">

```
  errors: [
    {
      message:
        'select "Question"."id", "Question"."description", "Question"."display", "Question"."type", "Question"."sectionId" from "Question" where exists (select * from "QuestionTranslation" where questionId = QuestionTranslation.questionId and "QuestionTranslation"."text" = $1) order by "Question"."description" asc limit $2 - column "questionid" does not exist',
      extensions: { code: 'INTERNAL_SERVER_ERROR' },
    },
  ],
};

```

**Comment by azrikahar** [comment]
> Some kind of "mix" is happening between the operator and the field I want to filter ("_nlug" is a mix of "_neq" and "slug").

This is very odd. I can only assume this "mix" is somehow caused by the logic here: https://github.com/directus/directus/pull/11737/files#diff-5885d1acf50bd00ba4d0423d591bc471c868e92766b253bfa1e9bd768bf58c26R350, but I could be wrong.

---

>  I'm not sure at what point this behavior changed; 

@mattbisme although it's quite likely to be introduced in 9.11.0 based on others reports, but would you mind confirming whether it works for you in 9.10.0? Just so we can be absolutely sure they all share the same root cause.

**Comment by pgegenfurtner** [comment]
I'm having the same issue in custom filters in user roles

**Comment by kuzmi4** [comment]
Confirm,
On postgres DB with directus 9.11 version on nested selects used query like:
`` where exists (select * from ``
instead 
`` where "parent.key"  in (select "nested.key" ``
