### ISSUE TITLE
The following fields have invalid values:  ID: Value is required

### ISSUE THREAD

**Issue by ahmedmesawer** [directus/directus#13471]
### Describe the Bug

I have created a data model that has id field which is uuid and auto random value and it was working adding new data after upgrading to version 9.10.0 it gives me 

### To Reproduce

try to add new data rows in a data model that has uuid id auto-set column

### Errors Shown

The following fields have invalid values:

ID: Value is required

### What version of Directus are you using?

9.10.0

### What version of Node.js are you using?

17.5.0

### What database are you using?

postgres 14

### What browser are you using?

chrome

### How are you deploying Directus?

k8s

**Comment by ahmedmesawer** [comment]
This On Create was set to Do Nothing, just changed it to Generate and Save UUID and everything is working fine
![image](https://user-images.githubusercontent.com/35766435/169705552-2c9e5287-9e94-4c23-a73a-ab2d66dc13cb.png)

**Comment by s-chillo** [comment]
I' m facing the same issue
Please How to access this field

**Comment by rijkvanzanten** [comment]
@s-chillo This post is 6+ months old. Please create a new issue if you're facing a new or similar issue 👍🏻
