### ISSUE TITLE
M2M Sorting with a display template field (non ID field) from Junction Table fails

### ISSUE THREAD

**Issue by insidesmart** [directus/directus#13476]
### Describe the Bug

**Background**:

We have 2 Collections.

- Sections
- Books

We would like to add multiple books under a section with sorting option.

**Setup**

We have created a M2M relation field in Sections collection pointing to Books collection. There is a junction collection (sections_books) created successfully.

To enable sorting, we have added a separate integer field named Sorter in the Junction Collection. Also selected Sorter in the Sort field under Relationship for the M2M relation field.

We have written a hook extension to handle data after Book Create / Update operations via action (not filter).

**What works:**

If we assign ID from Junction Collection or Books_ID.id as Display Template, then the Sorting of Books is successful (but the Books_ID.id value is not intuitive for end users).

**What is needed**

We would like to assign Book Title as Display Template for the M2M relation field as it will be intuitive & help end users to sort the books as they wanted.

**What doesn't work:**

If we assign Books_ID.title as Display Template, then the Sorting of Books is not successful. When Books_ID.title is used, we can see Items.Update function called for Books Collection (which is not the case if we use Books_ID.id).

### To Reproduce

**Setup**

Create 2 Collections.

- Sections
- Books

Create a M2M relation field in Sections collection pointing to Books collection. There is a junction collection (sections_books) created successfully.

To enable sorting, add a separate integer field named Sorter in the Junction Collection. Also select Sorter in the Sort field under Relationship for the M2M relation field created earlier.

Assign ID from Junction Collection or Books_ID.id as Display Template, then the Sorting of Books is successful

Assign Books_ID.title as Display Template, then the Sorting of Books is not successful (and you can see Books Update function is triggered if you have setup an extension to track books update)

### What version of Directus are you using?

9.11.0

### What version of Node.js are you using?

12

### What database are you using?

Postgresql 13

### What browser are you using?

Safari

### How are you deploying Directus?

Docker

**Comment by insidesmart** [comment]
It would be very helpful if anyone can confirm if this is indeed a bug or I am doing it wrong. Thanks.

**Comment by rijkvanzanten** [comment]
It seems to be working as expected on my end:

`sections` collection with a `books` many to many. `sort` exists on the junction table, `{{ books_id.title }}` used as the display template:

<img width="1707" alt="CleanShot 2022-05-23 at 14 32 07@2x" src="https://user-images.githubusercontent.com/9141017/169884224-d0fd3083-a124-4d0b-8f23-1afd9e8e7405.png">

Drag and drop sorting this list and hitting save does result in the `sort` column in the junction collection being populated correctly:

<img width="595" alt="CleanShot 2022-05-23 at 14 33 11@2x" src="https://user-images.githubusercontent.com/9141017/169884333-cad9306b-00d5-4d72-81d4-15cbfa1e1651.png">

I'll close this for now, as it seems like there's a configuration / misunderstanding, but happy to keep discussing 🙂

**Comment by insidesmart** [comment]
Thanks @rijkvanzanten for taking efforts to reproduce the potential bug.

As highlighted by your steps, I tried it again by setting up new M2M fields. It is indeed working when I disabled the custom extension hook I have built to handle updates.

I will investigate the extension code further. Thanks again for your time.
