### ISSUE TITLE
API 1.1 lacking response

### ISSUE THREAD

**Issue by Zaelot** [directus/directus#1347]
## Version Info
  - Directus version and branch: 6.3.6 ( 7f3d825 )
  - PHP version: PHP7
  - MySQL version: MySQL 5.5
  - Web server: Apache
  - OS: Debian Jessie

_You're probably already aware of most of these, but thought I'd mention._

## Expected Behavior

1. /api/1.1/tables/table_name/
	- `"nullable":true`
2. /api/1.1/tables/table_name/columns/ 
	- List all columns
3. ~/api/1.1/privileges/group_name/~
	- ~`"group_id":3`~
	- ~`"status_id":0`~
4. ~/api/1.1/privileges/group_name/table_name/~
	- ~`"success":true`~

## Actual Behavior
1. `"nullable":null`
2. Only lists the first ("id")
3. ~`"group_id":0` & `"status_id":null` (group_name can also be a non-existing one.)~
4. ~`[{"success":false,"error":{"message":"unable_to_find_privileges_for_x_in_group_x"}}]`~

## Steps to Reproduce
 1. Install the a build supporting 1.1 API
 2. Make some example tables
 3. Perform API requests
 4. (Compare with v1.0 API requests)

**Comment by WellingGuzman** [comment]
Thanks @Zaelot I will give it a look tomorrow

**Comment by Zaelot** [comment]
It seems you can scratch out 3. & 4. as the API was expecting the _group_id_ and not _group_name_ as I had mistaken.

Ran into fresh troubles though, WebGL project is returning a null response with error: **"Unknown error."**
Works fine in IDE. :/ (Tried both: passing the API token in the header, and with `?access_token=`)

**Comment by WellingGuzman** [comment]
Hey @Zaelot both 1 and 2 has been fixed. This will be release soon in 6.3.7

commits:
- https://github.com/directus/directus/commit/622672d70b8dd053cb6d2b5f7533813ed9bc0a09
- https://github.com/directus/directus/commit/c9f346070ca36911f8679e60a3180599517aa594

> Ran into fresh troubles though, WebGL project is returning a null response with error: "Unknown error."
(on api/1.1/tables/{0}/rows/?filters[project][like]={1} )
Works fine in IDE. :/ (Tried both: passing the API token in the header, and with ?access_token=)

What are you referring to here? where are you trying to fetch data from?

**Comment by Zaelot** [comment]
We set up the Directus database that we're trying to utilize for our project. One part of the project is made with Unity 3D and there in the Unity Editor the above (GET) call to `https://ourdirectusaddress.com/api/1.1/tables/table_name/rows/?filters[column_name][like]=item_name`
works just fine without any problems, but in the WebGL build, we get a null response to the request with error message of "Unknown error." (Literally that string.) Content length: 0. Status code: "200 OK"
Tested with API 1.0 as well, same thing. Whether the origin was http or https didn't matter either. 

Request Headers:
`Host: cms.address.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Access-Control-Request-Method: GET
Access-Control-Request-Headers: content-type
origin: http://address.azurewebsites.net
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache`

Response headers:
`Cache-Control: no-store, no-cache, must-revalidate
Content-Length: 0
Content-Type: application/json; charset=utf-8
Date: Wed, 08 Feb 2017 08:33:12 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Server: Apache/2.4.10 (Debian)
Set-Cookie: PHPSESSID=e1371a62c62108ede2437d265d5398e4; path=/
X-Powered-By: PHP/7.1.1`


![image](https://cloud.githubusercontent.com/assets/2608781/22730353/5c7a3c0e-edef-11e6-8bde-0eaeaae2dfed.png)

**Comment by WellingGuzman** [comment]
Hey @Zaelot,

I'm starting to believe this is a request from another host, because it's an OPTION request, probably you should enable `CORS` in your `configuration.php` file [/api/configuration.php](https://github.com/directus/directus/blob/f3124bba281d3f597b9343d8780b307113542020/api/configuration_sample.php#L45-L52)

Try that and let me know if that resolve the problem.

**Comment by WellingGuzman** [comment]
hey @Zaelot If this keep happening, please open a new ticket for this issue.

**Comment by Zaelot** [comment]
Thank you very much @WellingGuzman, that was it!
