### ISSUE TITLE
Time series count is not working as expected

### ISSUE THREAD

**Issue by abdonrd** [directus/directus#13478]
### Describe the Bug

Time series count is not working.

### To Reproduce

We setup a times series insight like this:

<img width="854" alt="Screen Shot 2022-05-23 at 10 57 16" src="https://user-images.githubusercontent.com/1007051/169782828-5ff70966-c0e4-4d43-a1fe-b91598257e03.png">

And then we see the empty insight:

<img width="868" alt="Screen Shot 2022-05-23 at 10 54 56" src="https://user-images.githubusercontent.com/1007051/169782384-cec0490f-a6e7-4e97-8fef-84cc6868be23.png">

We also see in the Dev Tools:

<img width="873" alt="Screen Shot 2022-05-23 at 10 52 32" src="https://user-images.githubusercontent.com/1007051/169782404-e76904fd-abf9-44ae-adb9-116ed30f8200.png">

The `{"count":[null]}` looks wrong.

And all the fields are disabled in the value field:

<img width="423" alt="Screen Shot 2022-05-23 at 10 59 10" src="https://user-images.githubusercontent.com/1007051/169783303-2b90a438-a4a1-4242-943a-203cffcc572d.png">

### What version of Directus are you using?

9.11.0

### What version of Node.js are you using?

16.15.0

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

Running locally

**Comment by azrikahar** [comment]
Additional thought: aside from the current linked PR which allows the use of primary key for count, maybe we can also "enhance" the error handling in general rather than a blank chart akin to #12538. (maybe needs to be in the same or another separate PR)

**Comment by abdonrd** [comment]
By the way, following the PR #13479...

If I manually set (with Edit raw value) the Value Field to "id" it works!

But if I change the Group Aggregation from `Count` to `Sum`... Stop working:
<img width="763" alt="Screen Shot 2022-05-23 at 12 49 55" src="https://user-images.githubusercontent.com/1007051/169803595-f3cb9819-3044-49ca-86cf-0475ce52e2da.png">

**Comment by azrikahar** [comment]
> If I manually set (with Edit raw value) the Value Field to "id" it works!

Thanks for confirming! That's a brilliant way to test it 👍

> But if I change the Group Aggregation from Count to Sum/Maximum... Stop working:

Yeah that is correct, as we can't sum/max primary key such as UUIDs (or lets say if it's manual primary key, we can't sum/max "en-US", "de-DE" etc).

The PR #13479 accounts for this by only allowing the selection of primary key only if it's Count or Count (Distinct).

**Comment by abdonrd** [comment]
> > But if I change the Group Aggregation from Count to Sum/Maximum... Stop working:
> 
> Yeah that is correct, as we can't sum/max primary key such as UUIDs (or lets say if it's manual primary key, we can't sum/max "en-US", "de-DE" etc).

What is the way then to have a graph that accumulates the sum of the entries?
For example when we have 2 users by day:

```
Day 1: 2 users
Day 2: 4 users
Day 3: 6 users
```

**Comment by rijkvanzanten** [comment]
> What is the way then to have a graph that accumulates the sum of the entries?

There's currently no aggregation function that will accumulate values over time like this 👍🏻
