### ISSUE TITLE
Error: exception 'ErrorException' with message 'Call to a member function toArray() on null'

### ISSUE THREAD

**Issue by Zilus** [directus/directus#1348]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests please use the [Directus FeatHub](http://feathub.com/directus/directus) to make a new request or vote for existing ones, or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues.

## Version Info
  - Directus version and branch: 6.3.5
  - PHP version: 5.6.27
  - MySQL version:  5.7.16
  - Web server: Apcahe
  - OS name and version: Ubuntu 14.04.3 LTS

## Expected Behavior

Create fields in table. When I click  save item it should save, but instead fires an alert.
When I click save item a second time, gets saved

## Actual Behavior

ERROR - 2017-02-09T12:57:07-05:00 - exception 'ErrorException' with message 'Call to a member function toArray() on null' in /var/www/html/azpeitia/admin/api/core/Directus/Db/TableGateway/BaseTableGateway.php:217
Stack trace:
#0 [internal function]: Directus\Exception\ExceptionHandler->handleShutdown()
#1 {main}

## Steps to Reproduce
 1. Create table "test"
 2. Add two (or more) fields
 3. Save item
 4. Error alert appears 

## Logs or Screenshots
ERROR - 2017-02-09T12:50:29-06:00 - exception 'ErrorException' with message 'Call to a member function toArray() on null' in /var/www/html/azpeitia/admin/api/core/Directus/Db/TableGateway/BaseTableGateway.php:217
Stack trace:
#0 [internal function]: Directus\Exception\ExceptionHandler->handleShutdown()
#1 {main}

**Comment by WellingGuzman** [comment]
Hey @Zilus, can you update to most recent and try again?

I wasn't able to reproduce with current release, so this was probably fixed along the way. if still happening let me know and I will work on a fix for this.

**Comment by waingro** [comment]
At first I was getting the same error with an identical description with a fresh install. However after a few days I am now getting this for when I create a new Table and Add some new fields. My stacktrace is a bit bigger so hopefully it helps. Looking back this is the same stacktrace with the fresh install error (just with different table names).

**## Version Info**

Directus version and branch: 6.3.7 Master
PHP version: 7.0.8 with Xdebug v2.4.1
MySQL version: MariaDB 10.1.13
Web server: (Ex. Apache, nginx or IIS?) Apache/2.4.18 (Win32)
OS name and version: Windows 10 Pro (64 bit)

**##Steps to Reproduce**
 1. Create a new Table.
 2. Add two TextInput, VARCHAR, limit 100.
 3. Click Save Item and Error Displays.
 4. Click Save and Item successfully saves. 

**## Logs or Screenshot**

ERROR - 2017-02-19T16:02:08-05:00 - Error: Call to a member function toArray() on null in C:\xampp\htdocs\directus\api\core\Directus\Db\TableGateway\BaseTableGateway.php:221
Stack trace:
#0 C:\xampp\htdocs\directus\api\core\Directus\Db\TableGateway\BaseTableGateway.php(183): Directus\Db\TableGateway\BaseTableGateway->findOneBy('table_name', '0')
#1 C:\xampp\htdocs\directus\api\core\Directus\Db\TableGateway\AclAwareTableGateway.php(225): Directus\Db\TableGateway\BaseTableGateway->find('0')
#2 C:\xampp\htdocs\directus\vendor\zendframework\zend-db\src\TableGateway\AbstractTableGateway.php(264): Directus\Db\TableGateway\AclAwareTableGateway->executeInsert(Object(Zend\Db\Sql\Insert))
#3 C:\xampp\htdocs\directus\api\api.php(1473): Zend\Db\TableGateway\AbstractTableGateway->insert(Array)
#4 [internal function]: {closure}('test_table')
#5 C:\xampp\htdocs\directus\vendor\slim\slim\Slim\Route.php(436): call_user_func_array(Object(Closure), Array)
#6 C:\xampp\htdocs\directus\vendor\slim\slim\Slim\Slim.php(1305): Slim\Route->dispatch()
#7 C:\xampp\htdocs\directus\vendor\slim\slim\Slim\Middleware\Flash.php(85): Slim\Slim->call()
#8 C:\xampp\htdocs\directus\vendor\slim\slim\Slim\Middleware\MethodOverride.php(92): Slim\Middleware\Flash->call()
#9 C:\xampp\htdocs\directus\api\core\Directus\Slim\CorsMiddleware.php(22): Slim\Middleware\MethodOverride->call()
#10 C:\xampp\htdocs\directus\vendor\slim\slim\Slim\Slim.php(1254): Directus\Slim\CorsMiddleware->call()
#11 C:\xampp\htdocs\directus\api\core\Directus\Application\Application.php(74): Slim\Slim->run()
#12 C:\xampp\htdocs\directus\api\api.php(1888): Directus\Application\Application->run()
#13 {main}

**Comment by WellingGuzman** [comment]
Hey @Zilus,

I finally understood the issue, and commit a fix to the master branch.

Let me know if that really fixes it.
