### ISSUE TITLE
Mod_Rewrite Enabled: No

### ISSUE THREAD

**Issue by ke207** [directus/directus#1349]
I am using a shared hosting service and trying to install Directus in a sub-folder of a add-on domain root (http://my-add-on-domain.com/cms/). By going through the installation process to step 4, it shows that "Mod_Rewrite Enabled" is "No".

Here's the server info:
  - PHP version: 5.6.29
  - MySQL version: 5.6.32
  - Web server: Apache 2.2.31
  - Directus downloaded from https://github.com/directus/directus/tree/build

I have tried the "/test/non-existing" steps in #889 and the result is positive, I think this means that the mod_rewrite is enabled. I have also checked the database permissions and it looks good.

Also tried adding "RewriteBase /" mentioned in https://docs.getdirectus.com/6.3.5/#FAQ, but I still got a "No".

Can anybody help on the case I met?

**Comment by WellingGuzman** [comment]
Hey @ke207, Thanks for reporting this.

There's a bug verifying the mod_rewrite using Directus in a subdirectory, you can continue and install without a problem.

I will work on a fix.

**Comment by ke207** [comment]
Thanks @WellingGuzman, I think the installation is working great now.

**Comment by WellingGuzman** [comment]
Great to hear @ke207.  I'm closing this ticket.
