### ISSUE TITLE
slug field blocking space, not converting to "-"

### ISSUE THREAD

**Issue by erondpowell** [directus/directus#13496]
### Describe the Bug

I believe the default behavior is to convert a space into a `-` so I'm noting this here.

https://user-images.githubusercontent.com/62306630/169915630-2fd5d354-e775-47a7-ae49-5382e3385678.mov

### To Reproduce

see above.

### What version of Directus are you using?

cloud

### What version of Node.js are you using?

cloud

### What database are you using?

cloud

### What browser are you using?

chrome

### How are you deploying Directus?

Cloud

**Comment by azrikahar** [comment]
I believe this should be resolved by #13112 in 9.11.0 👍 Just to confirm, is your current instance on a prior version? Will reopen and investigate further if it is in fact on 9.11.0 already.
