### ISSUE TITLE
"PostGIS isn't installed. Geometry type support will be limited." despite using postgis/postgis

### ISSUE THREAD

**Issue by sangdth** [directus/directus#13502]
### Describe the Bug

I'm following the tutorial here https://docs.directus.io/getting-started/installation/docker/#docker-compose using Docker compose, it works but with warning at startup:
```
PostGIS isn't installed. Geometry type support will be limited.
```

### To Reproduce

- Follow this guide https://docs.directus.io/getting-started/installation/docker/#docker-compose
- Run `docker-compose up`
- See the warning at startup

### Errors Shown

<img width="822" alt="Screenshot 2022-05-24 at 9 09 40" src="https://user-images.githubusercontent.com/1083478/169961040-f3904665-2db6-40b9-b37c-6b559306b8bd.png">

<img width="809" alt="Screenshot 2022-05-24 at 9 11 11" src="https://user-images.githubusercontent.com/1083478/169961188-6afe9007-b4a1-4edc-8502-8e5292fb0be4.png">

### What version of Directus are you using?

9.11.0

### What version of Node.js are you using?

16.14.2

### What database are you using?

PostgresQL

### What browser are you using?

Firefox

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
I can't seem to reproduce this with the same docker-compose file, so I believe this is (somehow) a localized issue on your end, at least with the current information at hand.

> PostgreSQL Database directory appears to contain a database; Skipping initialization

Curious on why is this appearing in your logs. Were you by any chance wasn't using the docker compose file or postgis/postgis initially? Would you mind making sure to delete the `./data` directory (the volume mounted in database service in compose file), assuming there is no critical data in the existing database of course, and try again?

I'll close this for now, but happy to debug/discuss further on what could be the differentiator in your current setup.

**Comment by sangdth** [comment]
Thank you @azrikahar, I removed the old images, also deleted the `./data` folder, started fresh again and it works fine now.

Sorry for the false alarm.

**Comment by azrikahar** [comment]
Thanks for the prompt update! Cheers
