### ISSUE TITLE
Nav Override "order"

### ISSUE THREAD

**Issue by Zilus** [directus/directus#1350]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests please use the [Directus FeatHub](http://feathub.com/directus/directus) to make a new request or vote for existing ones, or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues.

## Version Info
  - Directus version and branch: 6.3.6
  - PHP version:  5.6
  - MySQL version: 5.7
  - Web server: Apache
  - OS name and version: Ubuntu 14.04

## Expected Behavior

Insert JSON into Database, and show on the nav menu in the JSON order
For this Json:
```
{
  "AAA": {
      "Galeria": {
          "path": "tables/galería"
      },
      "Proyectos": {
          "path": "tables/proyectos"
      },
      "Slider": {
          "path": "tables/slider"
      }
  },
  "BBB": {
      "Acerca de": {
          "path": "tables/acerca"
      },
      "Contacto": {
          "path": "tables/contacto"
      },
      "Meta": {
          "path": "tables/meta"
      },
      "Sociales": {
          "path": "tables/redes_sociales"
      }
  }
}
```

## Actual Behavior

It orders, in a non logical way, one would expect:
AAA --- Galería, Proyectos...
BBB --- Acerca de, Contacto...

But it shows:

BBB
Acerca de
Contacto
Meta
Sociales
AAA
Galeria
Proyectos
Slider

## Steps to Reproduce
 1. Edit group table
 2. user this json:
```
{
  "AAA": {
      "Galeria": {
          "path": "tables/galeria"
      },
      "Proyectos": {
          "path": "tables/proyectos"
      },
      "Slider": {
          "path": "tables/slider"
      }
  },
  "BBB": {
      "Acerca de": {
          "path": "tables/acerca"
      },
      "Contacto": {
          "path": "tables/contacto"
      },
      "Meta": {
          "path": "tables/meta"
      },
      "Sociales": {
          "path": "tables/redes_sociales"
      }
  }
}
```
 3. reload

## Logs or Screenshots
![captura de pantalla 2017-02-14 a las 6 19 18 pm](https://cloud.githubusercontent.com/assets/1158317/22955561/5ee16894-f2e2-11e6-9dbe-32da98dc7cef.png)

**Comment by WellingGuzman** [comment]
Thanks @Zilus, I will take a look at this in a moment.

**Comment by WellingGuzman** [comment]
It was fixed here: https://github.com/directus/directus/commit/37084ca122323323d2ff03152695aae11ec1e92e

Only fixed on `development` branch.
