### ISSUE TITLE
"Slugify" feature not working with cyrillic symbols

### ISSUE THREAD

**Issue by vasiliytsykin** [directus/directus#13530]
### Describe the Bug

Text fields with "slugify" option checked do not accept and transliterate cyrillic symbols. Prior to version 9.9.0 this was working fine.

### To Reproduce

1. Take some text on Ukrainian language for example
2. Put it in text input with "slugify" option checked

### Errors Shown

no

### What version of Directus are you using?

9.11.1

### What version of Node.js are you using?

16.15.0

### What database are you using?

MySql 8.0.28

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Just to confirm, by "put in it text input", you mean pasting the value and not typing it right? (since it should currently prevent typing cyrillic symbols even prior to 9.9.0)

**Comment by vasiliytsykin** [comment]
Yep, i meant pasting

**Comment by azrikahar** [comment]
> Yep, i meant pasting

Thanks! Opened a PR to account for this use case 👍
