### ISSUE TITLE
9.11.1 Update no longer supports mixed UUID format

### ISSUE THREAD

**Issue by mattbisme** [directus/directus#13538]
### Describe the Bug

I have data that was migrated from an old database. That database used an older UID format. So, now I have mixed data:

```json
{
  "customers": [
    {
      "id": "zNUYqxCVF2ADzI5xwjzo",
      "status": "active",
      "date_created": "2021-11-23T14:06:25",
      "date_updated": "2022-05-19T00:45:57",
      "first_name": "Kevin"
    },
    {
      "id": "c3451cd0-6e5c-45e3-a14b-16755e638993",
      "status": "active",
      "date_created": "2022-05-18T20:18:44",
      "date_updated": "2022-05-20T20:51:25",
      "first_name": "Matthew"
    }
  ]
}
```

If I `GET /items/customers`, I can see everything; no problem. If I `GET /items/customers/c3451cd0-6e5c-45e3-a14b-16755e638993`, this also works as expected. However, if I `GET /items/customers/zNUYqxCVF2ADzI5xwjz `, I get a `FORBIDDEN`, "You don't have permission to access this." 

If I edit the records using SQL to swap the IDs, only records with the newer UUIDs will work. If I use SQL to modify the old UUID to a fake one (but using the same format), then it will work properly. I can even generate additional UUIDs using `uuidgen` in macOS terminal and add them via SQL; that also works.

### To Reproduce

Insert an item into a table with a custom ID that does not conform to the UUID (v1-5) standards. Then query the non-confirming ID.

### Errors Shown

```json
{
  "errors": [
    {
      "message": "You don't have permission to access this.",
      "extensions": {
        "code": "FORBIDDEN"
      }
    }
  ]
}
```

### What version of Directus are you using?

9.11.1

### What version of Node.js are you using?

18.0.0

### What database are you using?

SQLite 3.17.0

### What browser are you using?

PAW

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
This is likely linked to #13276, though it should only apply when your primary key field is of type `uuid` (hence `zNUYqxCVF2ADzI5xwjz` fails the uuid check. 

Can you confirm what is the field type of the primary key field? and just to have some additional info, did this migration happen prior to or after upgrading to `9.11.1`? I believe in your case, it should be a manual/string primary key instead, since you have mixed formats here.

**Comment by mattbisme** [comment]
> Can you confirm what is the field type of the primary key field?

The PK is set to UUID. When the DB was setup, it wasn't clear that we were going to be mixing UIDs. Also, everything worked fine up until `9.11.1`. 

> did this migration happen prior to or after upgrading to `9.11.1`?

The original data was migrated back on 9.7, or something close. I have also tested inserting data with the older UIDs on `9.11.1`; the results are the same. 

>I believe in your case, it should be a manual/string primary key instead, since you have mixed formats here.

Manual? So it won't be possible to have Directus generate UUIDs? That would be a tough pill to swallow.

**Comment by azrikahar** [comment]
> Manual? So it won't be possible to have Directus generate UUIDs? That would be a tough pill to swallow.

Agreed that it'd be far from ideal! Also more so an oversight as the previous response was rather reactive based on the current/new validation in place.

> Also, everything worked fine up until `9.11.1`.

Totally understandable, but I think this ended up being an edge case as #13276 was technically intended as a fix, definitely not removing something that was, albeit indirectly, supported! @rijkvanzanten @licitdev thoughts on this?

**Comment by benhaynes** [comment]
> Manual? So it won't be possible to have Directus generate UUIDs? That would be a tough pill to swallow.

Wouldn't this be possible to automate with a simple hook? Could add a Data Flow Operation to generate these UIDs too, so it can be done on cloud with no code.

**Comment by rijkvanzanten** [comment]
This isn't a use case that was ever officially supported, nor a use case that I think we're aiming to support at the moment. Directus is built to work with UUIDv4s across the board, and mixing these different types might result in other unexpected behavior as well. There's a discussion on supporting other flavors of UUIDs here: https://github.com/directus/directus/discussions/13278. As an in between workaround, you could use manual strings as the primary key type in Directus and auto-generate the UUIDs for item creations without primary keys through a hook, or a default value in the database directly 👍🏻

**Comment by u12206050** [comment]
@rijkvanzanten I think if if Directus sales pitch is "You remain in complete control of your new or existing database. No need to migrate to a proprietary data model, so there's no vendor lock-in." then uuids from older databases should be fully supported.

I believe my issue is similar due to my users having numeric values as ids, and since 9.11.1 no one can login. Are we forced to migrate our existing data to use UUID4 due to this now?

**Comment by benhaynes** [comment]
Maybe I'm misunderstanding something here, but the ability to use/generate other UUID formats is supported... but requires the use of hooks. With hundreds/thousands of current and legacy specs for data storage, not everything can be automated out of the box. I personally feel it's reasonable to support those through escape hatches, like hooks.

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten I think if if Directus sales pitch is "You remain in complete control of your new or existing database. No need to migrate to a proprietary data model, so there's no vendor lock-in." then uuids from older databases should be fully supported.

You can use any format primary key when using the "manual string" as the primary key. If you use Directus' UUID primary key, it expects UUIDv4s to be used.

> I believe my issue is similar due to my users having numeric values as ids

`directus_users` was never designed or intended to support anything but Directus' own UUIDs, so this feels like a bigger issue in the imported dataset 🤔 

> Are we forced to migrate our existing data to use UUID4 due to this now?

Depends! In the case of `directus_users` yes absolutely. The system collections rely on UUIDv4 and may have other unexpected side effects by forcing other IDs in there that are in different formats. If it's your own collection, you can keep using custom IDs by using the manual string primary key strategy 👍🏻
