### ISSUE TITLE
Latest version API 1.1 broke Many to One retrieval

### ISSUE THREAD

**Issue by Zaelot** [directus/directus#1353]
## Version Info
  - Directus version and branch: 6.3.7 ( 10a92a0 )
  - PHP version: PHP7
  - MySQL version: MySQL 5.5
  - Web server: Apache
  - OS: Debian Jessie

## Expected Behavior

1. /api/1.1/tables/table_name/rows
	- Embedded data from ManyToOne reference

## Actual Behavior
1. `"manyToOneFieldName": 17,` (so just the index)

## Steps to Reproduce
 1. Install the a build supporting 1.1 API
 2. Make some example tables with a ManyToOne field
 3. Perform API requests
 4. (Compare with v1.0 API requests)

**Comment by WellingGuzman** [comment]
Hey @Zaelot I updated the database component, please make sure to install the `0.1.2` version of the `directus/database` component.
