### ISSUE TITLE
Get last updated (ASC/DESC)

### ISSUE THREAD

**Issue by Faey2222** [directus/directus#1354]
Is there any way to get the latest updated items? Also to get the items which haven't been updated for a long time (pretty much the same filter as described before just sorted different)?

I haven't found any out-of-the-box method or filter for this in the 1.1 API documentation.
If this isn't implemented yet wouldn't that be a nice thing to have in one of the next updates of directus?

**Comment by WellingGuzman** [comment]
Hey @Faey2222,

Directus actually stores those data in `directus_activity` table. You can filter for an specific table.

Ex below:

```sql
SELECT `row_id`, `datetime`
FROM `directus_activity`
WHERE `type` = 'ENTRY' AND `action` = 'UPDATE' AND `table_name` = 'directus_users'
ORDER BY `datetime` DESC
LIMIT 1
```

Using the API 1.0:

```
/api/1/tables/directus_activity/rows?access_token=<api-token>&adv_where[type]=ENTRY&adv_where[action]=UPDATE&adv_where[table_name]=<table-name>&orderBy=datetime&orderDirection=DESC&perPage=1
```

Using the API 1.1:

```
GET /api/1.1/tables/directus_activity/rows?access_token=<api-token>&filters[type]=ENTRY&filters[action]=UPDATE&filters[table_name]=<table-name>&orderBy=datetime&orderDirection=DESC&limit=1
```

Another way using `activity`, same filters, shorter endpoint.
```
GET /api/1.1/activity?access_token=<api-token>&filters[type]=ENTRY&filters[action]=UPDATE&filters[table_name]=<table-name>&orderBy=datetime&orderDirection=DESC&limit=1
```

There's not Interface for this option, but you can add a new record in `directus_tables` and define your desired table if doesn't exists.

In `directus_tables` there's a column named `date_update_column`, you can set this column to whatever column in your table you want to store the last update datetime, and Directus will always store that value every time a record is updated.

I hope it helps, anything else, let us know.
