### ISSUE TITLE
Error: Uncaught TypeError: e.toJSON is not a function

### ISSUE THREAD

**Issue by Zilus** [directus/directus#1355]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests please use the [Directus FeatHub](http://feathub.com/directus/directus) to make a new request or vote for existing ones, or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues.

## Version Info
  - Directus version and branch: 6.3.6
  - PHP version: 5.6
  - MySQL version: 5.7
  - Web server: Apache 
  - OS name and version: Ubuntu 14.04

## Expected Behavior

Select at least 2 rose to delete, and delete them.

## Actual Behavior

Select at least 2 rows in table list view, then click "delete".
Error appears:
Error: Uncaught TypeError: e.toJSON is not a function
File: */assets/js/directus.min.js?bust=alsit5ndiidd0062s8t3jgmem2
 Line:18

## Steps to Reproduce
 1. In any table view select at least 2 rows.
 2. Hit "delete"

## Logs or Screenshots
 
![captura de pantalla 2017-02-22 a las 3 37 22 pm](https://cloud.githubusercontent.com/assets/1158317/23233618/0d3928d6-f915-11e6-9ec6-bbd2a4569d25.png)

**Comment by ricricucit** [comment]
Same error here.

**Comment by WellingGuzman** [comment]
Hey @Zilus + @ricricucit,

I pushed this [commit](https://github.com/directus/directus/commit/ed090e78702d4e0c6e89bc1c0cf96287c212ac29) into `development` branch, it should fix the issue.

Let me know.

**Comment by ricricucit** [comment]
Thanks @WellingGuzman!
Just one question...how can I update with a simple pull?
Documentation says I should `git pull origin build` ...but that generates:

````
Error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
````

**Comment by WellingGuzman** [comment]
Well if you are using build branch, I apologize, but you have to wait when we release the next version, soon today.

What you can do in the mean time is use the development branch (if possible).

**Comment by ricricucit** [comment]
Worked, thanks.
Same applies to your fix! 💯

**Comment by Zilus** [comment]
Works! Thanks!
