### ISSUE TITLE
"Optional System Fields" values are not saved into schema

### ISSUE THREAD

**Issue by joselcvarela** [directus/directus#13562]
### Describe the Bug

When creating a collection you can choose "Optional System Fields", like `user_created` or `date_updated`.
Although, when creating a snapshot, those fields loose user or date track.
This means that after applying this snapshot it will not save user or date for new items.

### To Reproduce

- Create a collection
- Add all "Optional System Fields"
- Make a schema snapshot
- Run Directus from scratch
- Apply the schema
- Create a new item on that collection
- `user_created` or `date_created` are not populated

### What version of Directus are you using?

9.11.1 (main)

### What version of Node.js are you using?

v16.14.2

### What database are you using?

postgis/postgis:13-3.1-alpine

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by br41nslug** [comment]
I've been trying to reproduce this issue but have not been able to in either `v9.11.1`, `v9.12.2` or `v9.13.0`. The optional fields are persisted in the snapshot as expected and applied correctly after the cache has been cleared
![image](https://user-images.githubusercontent.com/9389634/177318354-96acf4b8-3040-475c-a7b7-65662a009cb0.png)
![image](https://user-images.githubusercontent.com/9389634/177318374-4757a15a-f9fc-4c22-9e1c-55f76d4cb263.png)
