### ISSUE TITLE
Self signed certificate error when using SSL for external local auth provider

### ISSUE THREAD

**Issue by BDive** [directus/directus#13589]
### Describe the Bug

When a local instance of an external auth provider running on SSL (https) is utilized, Directus fails to start with the following error. This is when the AUTH KEYCLOAK ISSUER URL is set to https. NB: The self signed certificate is installed locally to local trusted root CA and browsers do not through such error.

![image](https://user-images.githubusercontent.com/28010132/170671777-c6a80e56-3149-4eee-a2fc-d51f7a374f37.png)

### To Reproduce

Use following external auth provider config (tried with local instance of keycloak)

####################################################################################################
## Auth Providers

AUTH_PROVIDERS="KEYCLOAK"

AUTH_KEYCLOAK_DRIVER="openid"
AUTH_KEYCLOAK_CLIENT_ID="direct"
AUTH_KEYCLOAK_CLIENT_SECRET="xxx"
AUTH_KEYCLOAK_ISSUER_URL="https://localhost:8443/check/realms/Test/.well-known/openid-configuration"
AUTH_KEYCLOAK_IDENTIFIER_KEY="email"
AUTH_KEYCLOAK_ALLOW_PUBLIC_REGISTRATION="true"
AUTH_KEYCLOAK_DEFAULT_ROLE_ID="08760b2d-f10d-42dd-a7d1-a6d1298c22ae"

### Errors Shown

![image](https://user-images.githubusercontent.com/28010132/170672057-e4510cac-1fcb-4fd8-8302-0bebcf4d5d5e.png)

### What version of Directus are you using?

9.11.1

### What version of Node.js are you using?

16.15.0

### What database are you using?

Postgres 10

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
@aidenfoxx Am I right in assuming this is the uncaught reject that's causing the startup crash? 

https://github.com/directus/directus/blob/50ba1bfd580e5008ecf1c0936df295f3045c0c83/api/src/auth/drivers/openid.ts#L74

If an OpenID provider can't be registered, I think we should log a warning and still startup as usual. Thoughts?

**Comment by aidenfoxx** [comment]
Yes, that will be the cause of the issue. If the Directus fails to fetch the OpenID metadata from the provider, the process will terminate on rejection. This was intentional since I consider that a critical error, as it would otherwise render the OpenID flow inoperable while the process is active.

I'm a fan of HCF when these kinda things occur, but if we can handle it better I'm all for it. 😄

**Comment by aidenfoxx** [comment]
> Though even nicer would be to (re)try the connection the first time OpenID is used, and throw an error at that stage in usage rather than terminating the whole process 

Feels like overkill to me for something I would consider an edge case. Obviously not fun if your OpenID provider is down when you try and start Directus, but I think it's more likely only people with invalid configs will ever see this.

Think we should add the critical logging first and then improve things if required down the road?

**Comment by rijkvanzanten** [comment]
Sounds like a plan to me!
