### ISSUE TITLE
ManyToOne Typeahead shows deleted entry instead of active

### ISSUE THREAD

**Issue by jhyle** [directus/directus#1359]
I have two relatable items with the same title, one of them is deleted. Unfortunately I see only the deleted one and cannot select the active.

**Comment by WellingGuzman** [comment]
Hey @jhyle, you probably has configured to only fetch `deleted` items on the UI Options.

Change `Visible Status IDs` to a list of statuses you want to use to filter the search

<img width="353" alt="screen shot 2017-02-25 at 10 33 51 pm" src="https://cloud.githubusercontent.com/assets/1531291/23336589/76a9379c-fbaa-11e6-9b79-14d018a314f6.png">

**Comment by jhyle** [comment]
I have a 1 there:

> mysql> select name, value from directus_ui where table_name = "Teaser" and column_name = "Artikel";
> +--------------------+-----------------------+
> | name               | value                 |
> +--------------------+-----------------------+
> | id                 | many_to_one_typeahead |
> | size               | large                 |
> | template           |                       |
> | visible_column     | Titel                 |
> | visible_status_ids | 1                     |
> +--------------------+-----------------------+
>

**Comment by WellingGuzman** [comment]
Hey @jhyle, sorry for the delay, what request is being made to the server? only the deleted records are being shown and nothing else?

**Comment by jhyle** [comment]
I type some keywords of the name and then I get the deleted item as proposal. Please give me more instructions how to give you more useful debugging informations.

**Comment by benhaynes** [comment]
@jhyle – can you add a schema here (on PM us in Slack) so we can reproduce?

@rijkvanzanten – can you see if this is happening for you in the Interface Gallery?

**Comment by WellingGuzman** [comment]
This is working, it should've been fixed in 6.4. I will close this. Unless this is a issue that still exists on 6.3 and there's an schema or a way we can reproduce  it.
