### ISSUE TITLE
Add multiline variant of translation strings input for textarea placeholder field

### ISSUE THREAD

**Issue by azrikahar** [directus/directus#13590]
### Discussed in https://github.com/directus/directus/discussions/12924

<div type='discussions-op-text'>

<sup>Originally posted by **martijn-dev** April 21, 2022</sup>
In the current version the placeholder field for a textarea changed back again to an input field instead of an textarea.

_Originally posted by @martijn-dev in https://github.com/directus/directus/issues/9003#issuecomment-1105010092_</div>

**Comment by rijkvanzanten** [comment]
Linear: [ENG-252](https://linear.app/directus/issue/ENG-252/add-multiline-variant-of-translation-strings-input-for-textarea)

**Comment by rijkvanzanten** [comment]
The new translations editing experience relies on textareas, so considering this done 🚀
