### ISSUE TITLE
Weird compile issue in the docs markdown

### ISSUE THREAD

**Issue by erondpowell** [directus/directus#13606]
### Describe the Bug

Bug is detailed here: https://github.com/directus/directus/pull/13431#discussion_r884205335
I'm assigning myself, but am happy to listen if another teammate has a quick thought on what is causing this.

### To Reproduce

It appears this happens on every commit.

### Errors Shown

na

### What version of Directus are you using?

9.11

### What version of Node.js are you using?

NA

### What database are you using?

NA

### What browser are you using?

chrome

### How are you deploying Directus?

happens on commits, not a deployment issue.

**Comment by rijkvanzanten** [comment]
Looks like a stray character in the markdown file will cause Prettier to go haywire. I'll close this for now as I believe it's a mistake in that one particular doc, rather than a build problem or a bigger bug in the platform / repo 👍🏻
