### ISSUE TITLE
Twig_Extension missing

### ISSUE THREAD

**Issue by DaSchTour** [directus/directus#1361]
## Version Info
  - Directus version and branch: 6.3.7
  - PHP version: 5.6 and 5.5 
  - MySQL version: 5.5
  - Web server: Apache
  - OS name and version: CentOS 7.3

## Expected Behavior

Installation starts

## Actual Behavior

```
Class 'Twig_Extension' not found in /.../installation/includes/Extensions/DirectusTwigHelpers.php on line 13
```

## Steps to Reproduce
 1. Unpack directus to directory
 2. Try to access the root directory for installation
 3. See the Twig_Extension error

## Logs or Screenshots

BTW: The link to the troubleshooting section https://docs.getdirectus.com/6.3.5/#Installation in docs leads to a 404
https://docs.getdirectus.com/05-troubleshooting

**Comment by WellingGuzman** [comment]
Hey @DaSchTour, it seems like you need to install the composer dependencies.

**Comment by DaSchTour** [comment]
How? And why isn't this mentioned in the documentation?

**Comment by WellingGuzman** [comment]
Hey @DaSchTour at the documentation we point to the `build` branch which has the dependencies already installed so we omit that step in the documentation.

You would have to download and install `composer` (https://getcomposer.org/) then cd to your directus path. and run `composer install` you should get all the dependencies installed.

It has nothing to do with your setup. You can download Directus from here which already got all the dependencies included. https://github.com/directus/directus/tree/build

**Comment by WellingGuzman** [comment]
I will close this as this is not an actual issue. I will help you get started, either way.

**Comment by DaSchTour** [comment]
Okay, well. That was not that obvious for me, that I'm directed to a build branch. For me it was more of: "Here is the git repot you can download it". Then I go to releases and download a release and boom I get a not build release for download.

**Comment by WellingGuzman** [comment]
@DaSchTour I apology for the confusion, but only the build branch, linked in the documentation has everything included.

Thanks for pointing this out, we will try to make it more clear.

Did you manage to make it work?

**Comment by DaSchTour** [comment]
@WellingGuzman yes I made it work, but I get MySQL Errors everywhere. After 10 Minutes I have entries that I don't see in any table cause I deleted them but I seem them in selects. And after 1 hour of working with directus I gave up. I'll try something else. Sorry.

**Comment by quadriq** [comment]
@WellingGuzman I think that the docu is very confusing... in the docu you say: "unpack and use" but in reallity its clone, run composer and then use.

I needed to install directos on a webhosting (only ftp).. so I used docker image to run directus there.. setup it and then move the hole direcotry of `/var/lib/www` to the hosting... 

So you need to adjust the docu! or create a release tarball with "ready to use" installation.

**Comment by benhaynes** [comment]
Hello @quadriq – we can update the docs to make all of this more clear. Apologies for any confusion!

**Comment by WellingGuzman** [comment]
Hey @quadriq, the documentation have a link to download release/build zip, which you should unpack and be ready to use (with composer dependencies installed)

**Comment by WellingGuzman** [comment]
Hey @quadriq, I review the documentation and I see the confusion, we do not link to the `zip` file directly but to the `build` branch, we are going to include the zip/tarball in the releases and point directly to those files.

**Comment by WellingGuzman** [comment]
I will close this ticket and we should start tracking this in #1535
