### ISSUE TITLE
Role with custom access and relations 

### ISSUE THREAD

**Issue by artecoop** [directus/directus#13619]
### Describe the Bug

I've first discovered in Directus Cloud, but I can reproduce it on a local installation. 

I'm accessing to all resources via authenticated user via API, but the same problem appears using the Directus dashboard.

I've created a role, which have a smaller set of permissions, and applied as follow
<img width="824" alt="Screenshot 2022-05-30 at 15 08 38" src="https://user-images.githubusercontent.com/52246878/170999397-81a14be6-93fe-496b-b960-8f750adddbc2.png">

To clarify the schema, Contract is the main table, and it can have 0 to N Press items and 0 to N Processing items. 
A Press item must have 1 Paper item, must have 1 Run Type item and can have 0 or 1 Varnish item.
A Processing item must have 1 Process definition item.

I've tried to narrow the number of fields a user in this role can access on the contract field. But in order to actually update the contract, I need to give it full edit access to all the related tables  (as you see in the screenshot above), otherwise Directus returns FORBIDDEN. 

As a test, I've reduced the number of updatable fields on Press for this role. If I directly access a Press Item and I try to edit permitted fields, I incur in no problems.
But if I open a Contract item, here open a related press and modify it (always editing fields the user can access), save the Press item i've just edited and then save the Contract, I got the error. If I save the Press and discard the Contract, the whole edit is discarded.

The user in this role can actually read, as you see, but I can't give him update write access to ALL fields.

### To Reproduce

I've explained in the description. 
The error is a bit scarce

### Errors Shown

This is the result from an API call

{"errors":[{"message":"You don't have permission to access this.","extensions":{"code":"FORBIDDEN"}}]}

### What version of Directus are you using?

9.11.1

### What version of Node.js are you using?

16.15.0 locally

### What database are you using?

Directus Cloud Community

### What browser are you using?

Firefox, Chrome

### How are you deploying Directus?

Directus Cloud, locally

**Comment by azrikahar** [comment]
By "0 to N", did you create an One-to-Many (O2M) field? (assuming it's not M2M since I can't see junction tables from the screenshot). In addition, when you reduce the number of updatable fields for Press, what specific fields did you disable/enable, perhaps a screenshot? If you reproduced this locally on SQLite, it'd also be even more helpful if you can share it 👍

In a local test, I was able to reproduce this issue _if_ the foreign key was not updatable. But after granting permission to that field, it does work:

https://user-images.githubusercontent.com/42867097/171108933-650b2729-3890-40a1-9647-138168c3e9bf.mp4

---

Side note: Initially thought this is somehow related to #13364, but if this issue is with O2M, then it probably isn't related.

**Comment by artecoop** [comment]
@azrikahar THANK YOU, with your help I was able to fix this problem.

First yes, the relation is O2M.

With your suggestion, I've added the permission to the foreign key in Press and Processing table, but to no avail. But watching again (and again 😂)  your video, I saw you give permission on the ID field: that was the final solution.

Why tho? Isn't the read permission sufficient for this purpose?

**Comment by artecoop** [comment]
Well no, that wasn't the final solution. I've still problem with the REST API. Dashboard works like a charm

**Comment by artecoop** [comment]
I had problems updating those fields via the REST API, so I resorted to watch what payload is used to make the same request via my Directus App dashboard. While a user with full write access to update can simply pass the Press array with edited fields and untouched ones, narrowed user must use this JSON to update the folder (extracted from directus request):

```
{
	"press": {
		"create": [],
		"update": [{
			"id": 28,
			"consumed_sheets": 1,
			"working_hours": 1
		}],
		"delete": []
	}
}
```

where consumed_sheets and working_hours are valid and editable fields.

Is this the correct way to do things?

**Comment by artecoop** [comment]
If I use 
`PATCH  https://XXXX.directus.app/items/contracts/9`
with payload
```
{
    "press": 
    [
        {
            "id": 28,
            "working_hours": 1,
            "consumed_sheets": 1
	}
    ]
}
```

the server returns
```
{
	"errors": [{
		"message": "You don't have permission to access this.",
		"extensions": {
			"code": "FORBIDDEN"
		}
	}]
}
```

using the update sintax:
```
{
	"press": {
		"update": [{
			"id": 28,
			"working_hours": 1,
			"consumed_sheets": 1
		}]
	}
}
```

works like a charm

**Comment by artecoop** [comment]
It seems odd to me too, also because I cant reproduce it locally. If you have connection with the directus.cloud team I can give you the project id and see on the actual production installation

**Comment by azrikahar** [comment]
hmm then that may end up being Cloud-specific. That said, feel free to send the details to me at `azri@directus.io` 👍
