### ISSUE TITLE
😢 Emojis are not correctly saved

### ISSUE THREAD

**Issue by ricricucit** [directus/directus#1364]
## Version Info
  - Directus version and branch: 6.3.8
  - PHP version: 7.0.15
  - MySQL version: 5.6.35
  - Web server: Apache
  - OS name and version: 

## Expected Behavior
a. Saving emoji from text inputs and areas should be working.
b. Adding them directly (manually) to the DB works.

## Actual Behavior
a. Saves `????` (4 questionmarks) instead  😢.
b. For those emojis saved manually, any UI displays a `?` (single question mark instead).

## Steps to Reproduce
 1. Save a text with emoji in it
 2. Check the saved result in any of the directus views (lists, UIs, etc.)

## Some ideas
[This](http://stackoverflow.com/questions/39463134/how-to-store-emoji-character-in-my-sql-database?answertab=active#tab-top) is –partially– the reason, as pointed out by @rijkvanzanten ...but possibly also some Zend DB module might be involved.

**Comment by WellingGuzman** [comment]
Thanks @ricricucit for reporting this one, can you share the database, table and field charset and collation?

**Comment by ricricucit** [comment]
Database: **utf8mb4_bin**
Table: **utf8mb4_unicode_ci**
Field: **utf8mb4_bin**

**Comment by WellingGuzman** [comment]
Hey @ricricucit, if you go to your `config.php` file and change `DB_CHARSET` TO `utf8mb4` emojis should work from that point on 💯 

Please confirm.

**Comment by ricricucit** [comment]
Thanks @WellingGuzman.
I've added `define('DB_CHARSET', 'utf8mb4');` to my _config-php_ file, but it still doesn't work.
It either strip the emoji...or save `????`

**Comment by ricricucit** [comment]
😳 whoooops. Forgot to pull.
I've pulled and it's now working. (apart from the WYSIWYG that strips it...but I guess that's fine?)

Thanks @WellingGuzman !

**Comment by WellingGuzman** [comment]
Amazing! @ricricucit, you are welcome to open a new ticket for the WYSIWYG issue, I will have a look at that some time soon either way.

**Comment by ricricucit** [comment]
[done](https://github.com/directus/directus/issues/1370).

**Comment by WellingGuzman** [comment]
Thanks @ricricucit

**Comment by Lokesh1-hub** [comment]
Hi This is lokesh i got a same issue when i insert emoji to database.....
i changed database utf8mb4_bin and also i changed config.php  DB_CHARSET TO utf8mb4 it is not working why????
