### ISSUE TITLE
OAS Spec for readSingle<Item> does not contain global query params such as sort

### ISSUE THREAD

**Issue by CoenWarmer** [directus/directus#13655]
### Describe the Bug

The documentation states that readSingle<Item> [supports all global query parameters](https://docs.directus.io/reference/items/#get-item-by-id).

The OpenAPI Spec that is served by Directus includes `fields` and `meta`, but it does not seem to include `sort` and the others mentioned on https://docs.directus.io/reference/query/:

Swagger docs:
<img width="545" alt="Screenshot 2022-06-01 at 09 09 47" src="https://user-images.githubusercontent.com/535564/171348241-5348efd1-ee6e-426a-af0b-37d1d02e162a.png">

Generated client code:
<img width="855" alt="Screenshot 2022-06-01 at 09 09 58" src="https://user-images.githubusercontent.com/535564/171348896-18162cfd-9d6a-41f1-abfe-e131c64ab69c.png">

Of course, not all global query parameters make sense in this context, but I was looking for a way to sort nested items and so was trying to pass `sort` as the documentation states that that is possible.

### To Reproduce

1. Create a collection
2. Allow read permissions to the created collection
3. Check the OpenAPI Spec

### What version of Directus are you using?

9.11.1

### What version of Node.js are you using?

16

### What database are you using?

Postgres 13

### What browser are you using?

n/a

### How are you deploying Directus?

Docker

**Comment by CoenWarmer** [comment]
Am now noticing https://github.com/directus/directus/issues/11880 and https://github.com/directus/directus/discussions/4502 so perhaps what I am looking for is not possible at all at the moment..?

**Comment by br41nslug** [comment]
As the issues you reference show sorting based on a nested relation is indeed currently not possible. The documentation might need to specify "supports all **applicable** global query parameters` as using params like `sort`, `filter`, ` to sort a single result is not very useful. If you want to sort the results of a relation like m2m you can look into `deep` filters (which seems to be missing from the open api spec as well) https://docs.directus.io/reference/query/#deep

**Comment by CoenWarmer** [comment]
Thank you @br41nslug :) 

Closing this ticket and tracking https://github.com/directus/directus/discussions/4502 with interest.

**Comment by benhaynes** [comment]
@br41nslug let's make sure to update those docs with your recommended text clarification. 👍
