### ISSUE TITLE
Required field prevents deleting item

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1366]
## Version Info
  - Directus version and branch: 6.3.8
  - PHP version: 5.6.28
  - MySQL version: 5.6.34
  - Web server: MAMP
  - OS name and version: Mac OS Sierra 10.12.3

## Expected Behavior
Selecting 'delete' and clicking 'Save item' deletes the item.

## Actual Behavior
An error message pops up reminding me that a required field hasn't been filled yet.

## Steps to Reproduce
 1. Delete an existing user

## Logs or Screenshots
<img width="1139" alt="screen shot 2017-03-12 at 20 29 09" src="https://cloud.githubusercontent.com/assets/9141017/23835149/96b19412-0762-11e7-8e1e-c5144dec9b7d.png">

**Comment by WellingGuzman** [comment]
Hey @rijkvanzanten thanks for posting this, but I'm closing it.

same: https://github.com/directus/directus/issues/1093
