### ISSUE TITLE
Warn users when entering uppercase keys

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#13676]
I'm fine with the decision to allow uppercase keys for collections and fields, but since we do NOT allow renaming, we should clarify with users what they intend. I just created a data model and it wasn't until I saw the uppercase in the app's URL that I knew what I messed up... and then it was too late to change.

We should do one of the following:
* Add an icon toggle on the right of the input to allow unrestricted naming, and have it off by default... so you get auto-forced lowercase/underscored keys
* Add a `warning` icon when uppercase/uncommon characters are added, with a tooltip explaining that these are KEYS for the API, etc
* Use some other ephemeral alert, like a notification to warn users of this

**Comment by rijkvanzanten** [comment]
Would this still be relevant once we have collection/field re-naming?

**Comment by benhaynes** [comment]
I think so, just to avoid the confusion around keys within the API not working as expected.

**Comment by rijkvanzanten** [comment]
Still wondering when we should warn. It's not uncommon to use camelCase for table/field names, and it feels a bit too opinionated to start warning for every uppercase character 🤔

**Comment by rijkvanzanten** [comment]
![Image](https://user-images.githubusercontent.com/9141017/176792689-e5fb4edf-1418-4df1-87db-e108eace4410.png)

Wanna do a note style like that? We could even leave it permanently

**Comment by benhaynes** [comment]
My ideal would be to have a conditional icon show up on the right with a tooltip that reads: `Case-sensitive database and API key`

Otherwise, a _conditional_ note would work.

Last on the list is a normal note, as it's more likely to be ignored and changes the vertical form spacing a bit more.

**Comment by freekrai** [comment]
I’ve done this accidentally with both collection names and field names, I think this is a warning we should put in both cases?

**Comment by rijkvanzanten** [comment]
> I’ve done this accidentally with both collection names and field names, I think this is a warning we should put in both cases?

It should be consistent between the two, but I'm not convinced we should do it for uppercase in general. If you're using camelCase everywhere, it would be very annoying to get constant warnings about the uppercase 🤔

**Comment by freekrai** [comment]
Yeah, my thinking is less camelCase and actually specifically if you start with Uppercase, we could regex and check for camelCase vs PascalCase, etc and only warn on Uppercase but ignore camelCase (if that made sense?)

**Comment by rijkvanzanten** [comment]
> Yeah, my thinking is less camelCase and actually specifically if you start with Uppercase, we could regex and check for camelCase vs PascalCase, etc and only warn on Uppercase but ignore camelCase (if that made sense?)

Trying to figure out what the current "strategy" is and then warning when a new field doesn't adhere to it sounds like quite a bit of added complexity 🤔 Althoughhh I guess there's only 3? strategies: PascalCase, camelCase, and underscores? We might be able to guestimate that based on existing collections and throw warnings when you're deviating.

Although at that point, we might as well refocus that effort in making field names renameable instead 😄

**Comment by rijkvanzanten** [comment]
Linear: [ENG-251](https://linear.app/directus/issue/ENG-251/warn-users-when-entering-uppercase-keys)
