### ISSUE TITLE
Users unable to edit their own details

### ISSUE THREAD

**Issue by sanpoChew** [directus/directus#1367]
## Version Info
  - Directus version and branch: master (098baf15b28c61907363bc6a76caab01960f2bb6)
  - PHP version: 7.0.16-3
  - MySQL version: 5.5.54
  - Web server: nginx 1.10.3
  - OS name and version: Debian 8.7

## Expected Behavior
I'm trying to give users the ability to edit certain sections of their own details, this originally came about with a user trying to add an Avatar.

## Actual Behavior
Any attempts to edit their own details fails with a nondescript 'Server Error' in the bottom right when Save Item is clicked. I, as an Administrator, can edit their details although the password fields are unpopulated which means I'm forced to reset their passwords at the same time. I can also edit my own details without any problems.

I have tried giving their user group similar permissions to mine but it doesn't seem to help.

Is this by design?

**Comment by WellingGuzman** [comment]
Hey @sanpoChew, can you check your logs (`api/logs`) any user should be able to edit their own information, what permissions did you gave the user group those users belongs to?

**Comment by sanpoChew** [comment]
I'm getting the following error: 

`ERROR - 2017-03-14T14:17:19+00:00 - ErrorException: Illegal string offset 'id' in /var/www/directus/api/core/Directus/Db/TableGateway/RelationalTableGateway.php:58
Stack trace:
#0 /var/www/directus/api/core/Directus/Db/TableGateway/RelationalTableGateway.php(58): Slim\Slim::handleErrors(2, 'Illegal string ...', '/var/www/direct...', 58, Array)
#1 /var/www/directus/api/api.php(1040): Directus\Db\TableGateway\RelationalTableGateway->manageRecordUpdate('directus_users', Array, 1)
#2 [internal function]: {closure}('directus_users', '11')
#3 /var/www/directus/vendor/slim/slim/Slim/Route.php(436): call_user_func_array(Object(Closure), Array)
#4 /var/www/directus/vendor/slim/slim/Slim/Slim.php(1305): Slim\Route->dispatch()
#5 /var/www/directus/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#6 /var/www/directus/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#7 /var/www/directus/api/core/Directus/Slim/CorsMiddleware.php(22): Slim\Middleware\MethodOverride->call()
#8 /var/www/directus/vendor/slim/slim/Slim/Slim.php(1254): Directus\Slim\CorsMiddleware->call()
#9 /var/www/directus/api/core/Directus/Application/Application.php(80): Slim\Slim->run()
#10 /var/www/directus/api/api.php(1933): Directus\Application\Application->run()
#11 {main}
`
The current permissions for the group on the directus_users table is they can view and edit any items, but not add or delete.

**Comment by Zilus** [comment]
+1

My log:
ERROR - 2017-03-16T13:39:18-06:00 - exception 'Directus\Acl\Exception\UnauthorizedFieldWriteException' with message '[Group #2 User #3] Acceso de escritura (set) prohibido para la tabla `directus_users` indices: group' in /var/www/html/photograpress/api/core/Directus/Acl/Acl.php:160
Stack trace:
#0 /var/www/html/photograpress/api/core/Directus/Db/TableGateway/AclAwareTableGateway.php(334): Directus\Acl\Acl->enforceBlacklist('directus_users', Array, 'write_field_bla...')
#1 /var/www/html/photograpress/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(361): Directus\Db\TableGateway\AclAwareTableGateway->executeUpdate(Object(Zend\Db\Sql\Update))
#2 /var/www/html/photograpress/api/core/Directus/Db/TableGateway/BaseTableGateway.php(257): Zend\Db\TableGateway\AbstractTableGateway->updateWith(Object(Zend\Db\Sql\Update))
#3 /var/www/html/photograpress/api/core/Directus/Db/TableGateway/RelationalTableGateway.php(92): Directus\Db\TableGateway\BaseTableGateway->addOrUpdateRecordByArray(Array)
#4 /var/www/html/photograpress/api/api.php(1040): Directus\Db\TableGateway\RelationalTableGateway->manageRecordUpdate('directus_users', Array, 1)
#5 [internal function]: {closure}('directus_users', '3')
#6 /var/www/html/photograpress/vendor/slim/slim/Slim/Route.php(436): call_user_func_array(Object(Closure), Array)
#7 /var/www/html/photograpress/vendor/slim/slim/Slim/Slim.php(1305): Slim\Route->dispatch()
#8 /var/www/html/photograpress/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#9 /var/www/html/photograpress/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#10 /var/www/html/photograpress/api/core/Directus/Slim/CorsMiddleware.php(22): Slim\Middleware\MethodOverride->call()
#11 /var/www/html/photograpress/vendor/slim/slim/Slim/Slim.php(1254): Directus\Slim\CorsMiddleware->call()
#12 /var/www/html/photograpress/api/core/Directus/Application/Application.php(80): Slim\Slim->run()
#13 /var/www/html/photograpress/api/api.php(1933): Directus\Application\Application->run()
#14 {main}

**Comment by WellingGuzman** [comment]
This should at least fix the issue @Zilus is having. @sanpoChew let me know if this one fixes it for you too.

**Comment by Zilus** [comment]
It does! Works, But I can't change the user password :(

**Comment by sanpoChew** [comment]
@WellingGuzman unfortunately not, still getting the same error as above:

`ERROR - 2017-03-21T22:54:21+00:00 - ErrorException: Illegal string offset 'id' in /var/www/directus/api/core/Directus/Db/TableGateway/RelationalTableGateway.php:58
Stack trace:
#0 /var/www/directus/api/core/Directus/Db/TableGateway/RelationalTableGateway.php(58): Slim\Slim::handleErrors(2, 'Illegal string ...', '/var/www/direct...', 58, Array)
#1 /var/www/directus/api/api.php(1040): Directus\Db\TableGateway\RelationalTableGateway->manageRecordUpdate('directus_users', Array, 1)
#2 [internal function]: {closure}('directus_users', '13')
#3 /var/www/directus/vendor/slim/slim/Slim/Route.php(436): call_user_func_array(Object(Closure), Array)
#4 /var/www/directus/vendor/slim/slim/Slim/Slim.php(1305): Slim\Route->dispatch()
#5 /var/www/directus/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#6 /var/www/directus/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#7 /var/www/directus/api/core/Directus/Slim/CorsMiddleware.php(22): Slim\Middleware\MethodOverride->call()
#8 /var/www/directus/vendor/slim/slim/Slim/Slim.php(1254): Directus\Slim\CorsMiddleware->call()
#9 /var/www/directus/api/core/Directus/Application/Application.php(80): Slim\Slim->run()
#10 /var/www/directus/api/api.php(1933): Directus\Application\Application->run()
#11 {main}
`

**Comment by WellingGuzman** [comment]
Hey @sanpoChew, this was solved before, I will close this ticket, if you still experiencing this problem, let me know I will reopen and fix it as soon as possible.
