### ISSUE TITLE
Single item table after save (returns to tables list)

### ISSUE THREAD

**Issue by Zilus** [directus/directus#1368]
## Version Info
  - Directus version and branch: 6.3.8
  - PHP version: 5.6
  - MySQL version:  5.7
  - Web server: Apache
  - OS name and version: Ubuntu 14.04

## Expected Behavior
With a single item table, after save I expect to get returned to the item itself.

## Actual Behavior
I goes to "Tables" list

## Steps to Reproduce
 1.  Create a single item table
 2. Edit and save

**Comment by WellingGuzman** [comment]
Hey @Zilus, I've fixed this with https://github.com/directus/directus/commit/3d5d21713264e83602776b4fb0b4142281b201b3

Let me know if that worked for you.

**Comment by Zilus** [comment]
It works perfectly! 
Thanks for the quick answer! I love **Directus** :)
