### ISSUE TITLE
translations m2o interface broken

### ISSUE THREAD

**Issue by wc-matteo** [directus/directus#13683]
### Describe the Bug

if you create a translations field and try to access the relation from the translations collection, you're not allowed

the interface shows:
```
The relationship hasn't been configured correctly
```

the same happens when trying to use the fk fields on the junction table of a m2m relation

### To Reproduce

1. create a translations field
2. go to the translations collection in the data model
3. un-hide the main collection fk field and set its interface to many to one
4. create an item with a translation
5. go to the translation collection in the content view
6. try to access the main collection from the fk field

### Errors Shown

![image](https://user-images.githubusercontent.com/10562635/171640711-ceaceae3-b26c-46bd-8a6b-f3fbe138e9e8.png)

### What version of Directus are you using?

9.11.1 

### What version of Node.js are you using?

n/a

### What database are you using?

postgres 13.3 / mssql 2016

### What browser are you using?

chrome

### How are you deploying Directus?

k8s

**Comment by wc-matteo** [comment]
it's quite a few releases that it's like that. I think it was the relational fields rework

**Comment by kuzemkon** [comment]
I'm experiencing a similar issue:
So in version 9.4.3 I've created an m2m relation between two entities (categories & products). By default I can only manage this relation from the categories entity. But I've also created the o2m relation between products and the junction table of categories-products m2m relation. Thus I was able to manage the m2m relation from both entities - products & categories. But once I've updated to the 9.12.1 - I can't manage m2m relations from products category anymore. I'm getting the following error: 
![image](https://user-images.githubusercontent.com/8713468/172878094-9557ab96-861d-4973-9e39-f2c665b95eed.png)

**Comment by shipsides-sparknel** [comment]
i have a M2A field in the Files collection that links to three other collections. a role that does not have access to all three tables will get "The relationship hasn't been configured correctly" when trying to view this field. when they are given access to all three tables, the M2A interface works. they do not even need access to any of the items inside the table.

is this related to this issue?

with access to all tables (Vendor Registration full, Employees where id = null hence the unresolved ID):
![image](https://user-images.githubusercontent.com/106218118/175527377-acdca3c1-09eb-4389-b9cb-0d46d37c3342.png)
with access to only one table:
![image](https://user-images.githubusercontent.com/106218118/175527592-75722c96-b4ec-4b65-977b-16267b896a5f.png)
