### ISSUE TITLE
Filter O2M first level does not work

### ISSUE THREAD

**Issue by joselcvarela** [directus/directus#13690]
### Describe the Bug

For O2M fields it's only possible filter nested values, not the first level.
For example, this works:
`/items/book?access_token=secret&filter[directus_users][id][_eq]=$CURRENT_USER`

But if we remove `[id]` that does not work:
`/items/book?access_token=secret&filter[directus_users][_eq]=$CURRENT_USER`

Also this can be tested in App

https://user-images.githubusercontent.com/14039341/171736081-6006ed39-d1b9-41dc-8e73-6fda0352dfb1.mov

### To Reproduce

- Create collection "blog"
- Create M2O field "parent"
- Create O2M field "children" pointing to "parent"
- In APP, filter by "children" contains "value" => error happens here
- In APP, filter by "children->id" contains "value" => should work

### Errors Shown

No errors are shown in APP, although a 500 error is sent with the following message:
```
message: "select \"blog\".\"id\", \"blog\".\"title\", \"blog\".\"date\", \"blog\".\"date_updated\", \"blog\".\"parent\" from \"blog\" where (\"blog\".\"id\" in (select \"blog\".\"parent\" as \"parent\" from \"blog\" where \"blog\".\"parent\" is not null and \"blog\".\"_contains\" like $1)) order by \"blog\".\"id\" asc limit $2 - column blog._contains does not exist"
```
(this error is shown on screen recording)

### What version of Directus are you using?

9.11.1 (d17529065)

### What version of Node.js are you using?

v16.14.2

### What database are you using?

SQLite / Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
Linear: [ENG-250](https://linear.app/directus/issue/ENG-250/filter-o2m-first-level-does-not-work)
