### ISSUE TITLE
Select JSON doesn't map on list view

### ISSUE THREAD

**Issue by Zilus** [directus/directus#1369]
I created a select UI, added a JSON ej.
{
    "1":"500px",
    "2":"Behance"
    ...
}
In the new and edit UI it works perfeclty, But when not in the list.
## Version Info
  - Directus version and branch: 6.3.8
  - PHP version: 5.6
  - MySQL version: 5.7
  - Web server: Apache 
  - OS name and version: Ubuntu 

![captura de pantalla 2017-03-13 a las 4 52 10 pm](https://cloud.githubusercontent.com/assets/1158317/23878538/8894d4ce-080d-11e7-9ede-8f91e126f017.png)

![captura de pantalla 2017-03-13 a las 4 52 18 pm](https://cloud.githubusercontent.com/assets/1158317/23878540/8bebf418-080d-11e7-9fdc-b8d5da06c2a8.png)

**Comment by WellingGuzman** [comment]
Hey @Zilus, Now you can select from Select UI options if you wish to use `text` or `value` to be shown in the listing table.

<img width="358" alt="screen shot 2017-03-13 at 7 07 37 pm" src="https://cloud.githubusercontent.com/assets/1531291/23878871/3d88847c-0820-11e7-9ea5-63cd1d882c9c.png">

Let me know if that works for you.

Commit: https://github.com/directus/directus/commit/a00a734bbe7385076cb20a1d225ddaaf53977d43

**Comment by Zilus** [comment]
Awesome!!! 
It works and I love the feature.
