### ISSUE TITLE
WYSIWYG strips emojis 😢 

### ISSUE THREAD

**Issue by ricricucit** [directus/directus#1370]
## Version Info
  - Directus version and branch: latest
  - PHP version: 7
  - MySQL version: 5.6
  - Web server: (Ex. Apache, nginx or IIS?) 
  - OS name and version: 

## Expected Behavior
Saving an emoji in the WYSIWYG should save the emoji!

## Actual Behavior
...it doesn't.

## Steps to Reproduce
 1. add an emoji in a WYSIWYG
 2. save
 3. the emoji will be stripped.

## Logs or Screenshots
![screen shot 2017-03-14 at 13 25 58](https://cloud.githubusercontent.com/assets/1016775/23909964/7714a15e-08d8-11e7-8baa-bc174610da25.png)

**Comment by WellingGuzman** [comment]
To solve this issue make sure your connection, table and column are encoded with `utf8mb4`

Change your connection charset in `api/config.php` `define('DB_CHARSET', 'utf8mb4');`

Otherwise we can do more, as this library are going to be replaced with another one.
