### ISSUE TITLE
Data Flows: cannot edit an operation

### ISSUE THREAD

**Issue by mslonina** [directus/directus#13702]
### Describe the Bug

Hi,

first of all - long awaited feature with DataFlows - awesome!

But, once the flow is created, and an operation is added, it looks like, we cannot edit the operation, but we can replace it entirely i.e. Log in to console cannot be updated, after clicking Edit icon, the dialog with list of operations appears.

### To Reproduce

1. Create a flow
2. Add a operation - `Log in to console` and save it
3. Try to edit `Log in to console` operation - the list of operations appears, not the operation itself

### Errors Shown

None

### What version of Directus are you using?

9.12.0

### What version of Node.js are you using?

Docker

### What database are you using?

Docker

### What browser are you using?

Safari

### How are you deploying Directus?

Docker

**Comment by vanling** [comment]
Workaround would be to refresh when you are in editing screen.
https://user-images.githubusercontent.com/50699657/171913605-b5219ac3-26d6-4409-804c-d067a6993952.mov

**Comment by rijkvanzanten** [comment]
I'm not able to reproduce this locally under the dev build, lemme try a prod instance

**Comment by rijkvanzanten** [comment]
Can confirm. This only happens in the prod build 🤦🏻

**Comment by rijkvanzanten** [comment]
oh. and it only happens in prod Safari 🙈

**Comment by vanling** [comment]
I got in edge :) Versie 101.0.1210.53 (Officiële build) (arm64)

**Comment by rijkvanzanten** [comment]
Ah yeah I edited the trigger, not the operation 👍🏻

**Comment by vanling** [comment]
Maybe timing thing between route and opening the dialog/drawer. Dev build slower?

**Comment by rijkvanzanten** [comment]
I think these refs aren't correctly starting on the values of the prop due to some timing issue. The drawer should only be rendered if the prop exists, but for some reason there's a small discrepancy in timing between prod and dev of when the prop exists (I think)

https://github.com/directus/directus/blob/6e87d8a55b67a2994297014dc9da125e7a4d1bdb/app/src/modules/settings/routes/flows/components/operation-detail.vue#L99-L102

**Comment by mslonina** [comment]
Thanks! I can confirm it works now!
