### ISSUE TITLE
The table `directus_messages_recipients` is missing the `user_create_column` 

### ISSUE THREAD

**Issue by Zilus** [directus/directus#1371]
When a user from a user group created after installation receives a message, gets this error:

The table `directus_messages_recipients` is missing the `user_create_column` 
within `directus_tables` (BigEdit Permission Forbidden)

I fixed by adding manually the directus_messages_recipients row for each group in directus_privileges table. But it should be created when "you creaste a new group".

Maybe there's a quick fix, but I'll leave it here for reference, if someone gets the same error.

## Version Info
  - Directus version and branch: 6.3.8
  - PHP version: 5.6
  - MySQL version: 5.7
  - Web server: Apache
  - OS name and version: Ubuntu 14.04

## Expected Behavior

User group not getting this error message 

## Steps to Reproduce
 1. Log in as main admin
 2. message to a user from another user group
 3.  read the message with the other user account

**Comment by WellingGuzman** [comment]
Hey @Zilus, the table was missing a configuration, when a user only has permission to their own item the table needs to specify which table are used to who's the owner of each record.

This (https://github.com/directus/directus/commit/3038d80208cbfb681dffb4aa63ce7a1643e5c788) should do it, let me know.

**Comment by Zilus** [comment]
Works! Thanks!
