### ISSUE TITLE
Float checkboxes in checkbox lists (Multi Select)

### ISSUE THREAD

**Issue by kaskajp** [directus/directus#1372]
## Version Info
  - Directus version and branch: build branch, commit 52d1c56
  - PHP version: 5.6.27
  - MySQL version: 5.6.27
  - Web server: Apache 2.4.23
  - OS name and version: macOS Sierra 10.12.1

## Expected Behavior
The options should float or something so they don't take up so much space. 

## Actual Behavior
The options stack on top of each other.

## Steps to Reproduce
 1. Just a default Multi Select Checkbox List

## Logs or Screenshots
<img width="655" alt="screen shot 2017-03-15 at 13 42 35" src="https://cloud.githubusercontent.com/assets/1626458/23951553/ab7bda0a-098e-11e7-9f48-4f91301b0cc4.png">

**Comment by WellingGuzman** [comment]
Hey @kaskajp this should do it https://github.com/directus/directus/commit/64929e576e6713c0c889f839ba55b2eeae656b5e as it's a css solution I hope this works across most popular browser.
