### ISSUE TITLE
Flows: results doubled for actions like log to console or email notification

### ISSUE THREAD

**Issue by meditadvisors** [directus/directus#13739]
### Describe the Bug

The results of flows are doubled for actions like Log to console, Send email or notification. 

### To Reproduce

Create a test flow with an event hook on item added to log to console (or send email) 

Note the double action/output... If email is configured you will get 2 emails.

<img width="1399" alt="Screen Shot 2022-06-05 at 17 55 29" src="https://user-images.githubusercontent.com/44246882/172037465-0c754a63-fb22-41df-a6d9-efb09ebcb3f8.png">

### Errors Shown

check the action log and notice same 2 actions/messages

### What version of Directus are you using?

9.12.1

### What version of Node.js are you using?

16.15.0

### What database are you using?

does not matter, tested on both postgres and sqllite

### What browser are you using?

does not matter

### How are you deploying Directus?

Docker

**Comment by jsbrain** [comment]
Same here

**Comment by sfarrowGR** [comment]
Also happening for me.

**Comment by izoukhai** [comment]
Same here too

**Comment by emrahnazif** [comment]
For information:
This can be also related with cache isn't being properly cleared.
My issue is different #13780 but, after I restart the Directus. I feel like this is solved as wel.

**Comment by nickrum** [comment]
@emrahnazif I'm working on a fix that should hopefully fix both issues.

In the meantime, restarting Directus should also work as a workaround for this issue.
