### ISSUE TITLE
New UI for "multi-select"

### ISSUE THREAD

**Issue by the0neyouseek** [directus/directus#1375]
I couldn't help but notice that you use the default html select in the app. It may not be an issue for some cases but, for example, on the user account edit page, the list for choosing the timezone is excessively long and unfriendly. 

To fix this you could use some oss Javascript libs like the ones below :

- [Chosen](/harvesthq/chosen)
- [Select2](/select2/select2)
- [Selectize](/selectize/selectize.js)
- …

All of them can be themed to match the app UI.
If you want me to, I can try to put up a PR for this when I have the time.

(*Looked up the past and present issues for this and couldn't find it, sorry if it's already asked and answered*)

**Comment by benhaynes** [comment]
Hey @the0neyouseek – this would be amazing!

We try to keep a version of the basic Interfaces in the Core, but are _always_ looking for new and innovative ways to interact with data... especially for more common edge-cases like this. We would absolutely love a PR if you want to create this Interface. I would recommend duplicating the current Select as a starting point – that way this is its own module.

You can look at our `6.4` branch to see the new styling too – since the next release will be coming out in a few weeks it would make sense to use those style standards.

Thanks again! Excited to see what you come up with!!

**Comment by the0neyouseek** [comment]
Thanks for the quick reply @benhaynes !

I'll get to it and make a PR as soon as I can then 👍

**Comment by the0neyouseek** [comment]
Here's what I've got so far : 

| ![](https://zippy.gfycat.com/ShorttermLinearAztecant.gif) | ![](https://zippy.gfycat.com/DeadActiveChrysomelid.gif) | 
|---|---|
| Simple | With search and a placeholder <br>(Allow Null) |

If the UI is good for you I will also do the `multiple` select before commiting the changes and making the PR.

**Comment by WellingGuzman** [comment]
Hey @the0neyouseek that look really great! can wait to try it out.

**Comment by the0neyouseek** [comment]
Thanks for the response ! So, before going through with this I have some quick questions guys  😄  

- Which default do you want for the select `search` feature ? enabled or not ?
- Which branch to you want me to commit to ? `version/6.4` / `development` ?
- Do you want me to make a new interface, let's say `select2` (since it's the name of the lib used), or replace the `select`, `many_to_one`, `multi_select` and `enum` ones to use this new UI ?

Also, just to let you know, doing a quick search with Atom I noticed you have a lot of "_loose_" `select` in the code not using the interface (at least 40 ≠ `<select` returned across the whole project and excluding the ones in `jquery` and `core/interfaces`). For now, those will not be affected by the PR I'll make.

**Comment by benhaynes** [comment]
Hey @the0neyouseek – wow!! This is amazing! *Really* great job!

Here are some answers to your questions:
* I think it depends on which interfaces it replaces (see below). If it's part of the main `select` then search should be disabled by default since most people will likely have fewer items. Alternatively, we could have the option be a dropdown with: `Auto (default), On, Off` ... and for auto it automatically enables with over X items (if that's even possible).
* @WellingGuzman would know better than me... but I would say let's merge it to `6.4` so it's in with all our big changes in the next release. Of course if you want to get it out into the world sooner (than 1-2 weeks) then we can merge it to `dev`.
* `select`
    * OK, so my first question is how well does this work on mobile? The ONLY reason the standard dropdown (with overlay styling) was nice is because mobile devices have system interfaces for these. It'd be a bummer to lose that (maybe we can fall back with a mobile conditional?). Either way, we can have it replace `select` but let's add a `display style` option (dropdown) that includes:
        * Styled Dropdown
        * Styled Dropdown with Search
        * System Dropdown
        * Radio Buttons (?)
    * My OTHER question is: Would you have the options handle STATIC (eg: CSV of allowed options) and RELATIONAL data (eg: M2O)? If it can handle both use cases really well... then *maybe* it's better to merge `select` and `many_to_one`. I think another consideration is how much overlap there is for the Options... since we don't want a lot of unused/confusing options depending on the interface style you choose. It's hard to find the right balance between combining Interfaces and splitting them up... so maybe this is worth discussing a bit more.
    * Multi-select saves data differently (and is also visually different) so I don't think that would be merged into this. I could see multi-select being combined with the "array of checkboxes" though... since it saves data the same. HOWEVER, this would save the same as an array of radio buttons... so maybe that's a good interface option!

Hopefully this all makes sense and isn't too crazy! I'd love to hear what you think – and thank you again, I'm really impressed!!

**Comment by the0neyouseek** [comment]
Hi @benhaynes, 

- I've got the `Auto`/`On`/`Off` options done (I've also put the option to change the threshold for the `Auto` mode — default to 10).
- I've made the changes to `6.4`, 1/2 weeks is great 😄 
- `select` 
    - On mobile, with the simple dropdown you get the same thing as above. With search active, the searchbar gets focus and opens the keyboard panel (default html behavior). 
Loosing the mobile system ui is a  _cons_  to using this and the only _pros_ I see is the ability to search for long list of items (not available in the default system ui on iOS/Android). This is not such an important feature on mobile (than desktop) because you can scroll the list of items pretty quickly swipe your finger across the screen.
I think making a conditional for mobile is a good idea, I'll get to it quickly. This way all the default `select` using the interface will benefit from this change without needing modification.
    - `select2` can handle both, you can see a demo of what it can do [here](https://select2.github.io/examples.html#data) but merging `many_to_one` is, as you said, worth another discussion, I'll leave that for another time (and another PR) then 😄 
    - Multi-select would look more like the `tags` interface using `select2`:
![Multi-select example](https://zippy.gfycat.com/ImpressionableDownrightAngelfish.gif) 
For now i'll keep to just changing the `select` & `enum` interfaces to this new UI, keeping the issue/PR light. The multi-select/m2o can be done later if needed 😉

**Comment by WellingGuzman** [comment]
@the0neyouseek Multi-select looks really great, that can be useful!

**Comment by the0neyouseek** [comment]
Do you want me to keep this issue open and switch topic to `multi-select` 😄 or can I close this ?

**Comment by benhaynes** [comment]
Hey @the0neyouseek – we have some good data here, let's keep this ticket and shift it to `multi-select`! Same things apply – we just need an option to allow for a system interface, with an upgrade to yours.

Thank you! Good progress here!

**Comment by the0neyouseek** [comment]
Hi @benhaynes ,
I'll probably work on this next week-end 👍 Keep up the great work guys !

(PS. Totally unrelated, but you should try to post your work on HackerNews/ProductHunt and [the likes…](https://github.com/mmccaff/PlacesToPostYourStartup), probably when `6.4` comes out, the project could gain some attention, and contributors 😉 , from this )

**Comment by benhaynes** [comment]
That's great @the0neyouseek – we really appreciate all the help!

And yes, I've been getting ready to post on Reddit/PH once we're super stable within `6.4`... it will be a big rush, so I want to make sure everyone is done with normal fixes/updates so we have "all hands on deck" available.

Thank you for the PlacesToPost, hadn't seen this! We can ramp up with some of the smaller ones. We were trending yesterday on something called webdesignernews.com and it was a huge bump – so Reddit/PH could be enormous. One chance for first impressions... and all that. ;)

**Comment by the0neyouseek** [comment]
(About that... Full disclosure, it was me :P , I couldn't find you anywhere on websites I go to regularly that I thought would enjoy this projet as much as I, so I posted about you - [Link here](https://www.designernews.co/stories/81737-directus--beautiful-cms-and-api) - Figured later I should probably have waited for `6.4` to come out first, that's why I brought it up now, hope you don't mind..)

**Comment by benhaynes** [comment]
Haha, amazing! I absolutely don't mind – as I said, it's good to ramp up with the marketing so we can anticipate traffic (etc). Also, there are always more bugs after a new release with lots of changes... so I'm sure everyone saw a more stable version. Thank you so much for doing that – we can use all the exposure we can get!

**Comment by benhaynes** [comment]
Hey @the0neyouseek – just found a pretty big issue with the current SELECT interface:

If you open the select dropdown and then scroll, the menu stays fixed on the page (not attached to the interface). Also, once you lose that menu, the whole page stops being clickable (weird). We'll need to get this resolved or roll-back to the system dropdown unfortunately.

Let me know what you think!

**Comment by the0neyouseek** [comment]
Hi @benhaynes , sry I didn't have time to work on this last week-end. I'll get it done tomorrow (hopefully 😉 ).

I think I figured out why the bug is happening and it seems to be because `select2` doesn't like to be positioned in absolute element (why…, that I don't know). In this case, this bit of `.scss` here :

```scss
.page {
	@include transition (all, $timing-short, ease-in-out);
	position: absolute;
	top: 64px;
	left: 200px;
	bottom: 0;
	right: 0;
	overflow: scroll;
	background-color: lighten($gray-1, 3%); // #f5f5f5 // Global!
	z-index: 8;
```

found in `_page.scss` is what causes the issue. 

I'll try to fix this tomorrow too

**Comment by benhaynes** [comment]
Not problem @the0neyouseek – thanks for looking into this! Yeah, it's probably listening to page scroll instead of `.page` scroll... something odd like that would be my guess.

**Comment by benhaynes** [comment]
Hey @the0neyouseek – any updates on this?

**Comment by the0neyouseek** [comment]
Yeah, so sorry Ben ! 🙏 
I've been working a lot this past few weeks and didn't have time to give it a look…
I'll make a pull request Saturday 😉

**Comment by benhaynes** [comment]
No problem – busy times all around! Looking forward to the PR! :)

**Comment by benhaynes** [comment]
Thank you for this contribution @the0neyouseek – the scroll issue is actually part of the external library (because we can't set the offset parent as a parameter). So there's no reason to keep this open – and it's not a huge bug (just weird scrolling if it's open).

I'll close this, and we can revisit if anything else comes up!

We really appreciate the help – these interfaces look great!
