### ISSUE TITLE
Fields shown as editable although permissions disallows editing

### ISSUE THREAD

**Issue by mslonina** [directus/directus#13774]
### Describe the Bug

I have a Demo role, which, for such a simple model `test`:

- name
- description
- access - private/public string

can:

- create item `test`
- read items `test` if `user_created = $CURRENT_USER` or `access = public` + most/all fields are selected
- update/delete `test` if `user_created = $CURRENT_USER` - to do so I also have to expose all the `test` model fields to be updatable by the role (so that the `$CURRENT_USER` can actually update its own content of type `test`).

If User1 within the Demo role create a `test` item with `access` set to `private` - all works as expected (no private content is exposed). If however User1 creates a `test` item with `access` set to `public` (only read access as above), the User2 properly gets the access to the item and can navigate into it. What they see however, is the form, which allows editing of values, and on save - the forbidden message is thrown (it comes from the backend I believe).

On the other hand, if I remove the fields selection from the Update permission, I lose update capability for the item owner - for example, I can easily create content, which is accessible only with the Read to all of the users, and the Admin role can only update it (bypassing all rules). What I expected here - is having fields disabled.

### To Reproduce

As above

### Errors Shown

On saving the public item, Forbidden message is properly shown.

### What version of Directus are you using?

9.12.1

### What version of Node.js are you using?

Docker

### What database are you using?

Docker

### What browser are you using?

Safari

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
> What they see however, is the form, which allows editing of values, and on save - the forbidden message is thrown (it comes from the backend I believe).

This does confirm that it's an issue with the App (as the API correctly disallow the edits), so it should be the same root cause as #11058. Let's track it over there, but do let us know if you feel like it's not the same issue 👍
