### ISSUE TITLE
M2A Builder not updating

### ISSUE THREAD

**Issue by madc** [directus/directus#13779]
### Describe the Bug

We use a M2A Builder inside a translations-field to be able to provide custom page structures. Here is the current setup:

**Page Model**
![image](https://user-images.githubusercontent.com/343392/172600707-7e598413-cf4e-4e1a-927a-cd540295cb50.png)

**Page Translations Model**
![image](https://user-images.githubusercontent.com/343392/172600913-90b4b54f-f402-46af-b0c6-1f0e93ae0676.png)

**Content Field Relationships**
![image](https://user-images.githubusercontent.com/343392/172601509-3c13ceeb-7e7c-4e12-8eeb-d52ef817adaf.png)

Recently an issue was introduced (we noticed it after the current 9.12.1 release), where newly created M2A records do not show up right away. The save-button turns purple, but nothing is added to the M2A list:

https://user-images.githubusercontent.com/343392/172603279-73adce62-01dd-4a73-a4d5-55a3531294c0.mp4

While documenting this issue I noticed, that it only happens it the translation already exists. If I edit a locale for the first time, the M2A builder behaves as expected. Also, If I blindly add two records to the M2A Builder and save, only the second one is persisted. We run two instances of Directus for separate websites that show this behavior.

Please let me know, if I can provide additional information.

### To Reproduce

* Setup a M2A Builder inside a Translations-Field
* Save the locale once and reopen the record.
* Try to add or delete a M2A record

### Errors Shown

There are no errors in the Console.

### What version of Directus are you using?

9.12.1

### What version of Node.js are you using?

12.22.5

### What database are you using?

MySQL

### What browser are you using?

Current Firefox / Chrome

### How are you deploying Directus?

Running locally.

**Comment by azrikahar** [comment]
This should be the same as #13665 and #13551 (particularly any relational or JSON fields within Translations field), and has been resolved in #13574 which will be included in the next release 👍
