### ISSUE TITLE
Deleted flow continue to trigger

### ISSUE THREAD

**Issue by emrahnazif** [directus/directus#13780]
### Describe the Bug

I have created a flow to send an email when a new item created in a collection. After my tests, I deleted the flow. 
But I still receive emails from coming from that flow. 

### To Reproduce

- Create a even flow with send email action when an item is created. 
- Test it, if it is really working (optional)
- Delete the flow
- Create new item in the same collection
- You should receive an email even flow doesn't exist

### What version of Directus are you using?

9.12.1

### What version of Node.js are you using?

n/a

### What database are you using?

mysql

### What browser are you using?

chome

### How are you deploying Directus?

running locally

**Comment by emrahnazif** [comment]
To anyone who faces this problem. After I restart the Directus, It is fixed.

**Comment by benhaynes** [comment]
Sounds like the cache isn't being properly cleared.

**Comment by rijkvanzanten** [comment]
> Sounds like the cache isn't being properly cleared.

Except for the fact that flows aren't stored in cache 😅 

I believe PR https://github.com/directus/directus/pull/13783 might've also resolved this. @nickrum could you confirm as well?
