### ISSUE TITLE
Graphql Schema does not include _between filter

### ISSUE THREAD

**Issue by nico-k3** [directus/directus#13782]
### Describe the Bug

Hi!

If you try to query a collection via graphql and filter it using a _between filter, you will get an error message stating:

`Field "_between" is not defined by type "date_filter_operators"`

On further inspection of the Schema in Apollo Studio, the _between filter was not present in any filter operations.

When trying the same query in REST tho, it worked.

### To Reproduce

1. Create a Directus Community Cloud Instance with demo data
2. Add view permissions for the Articles collection to the public role
3. Try to filter _between on the publish_date field

Used Query:

```
query ExampleQuery($filter: articles_filter) {
  articles(filter: $filter) {
    id
    status
    author
    date_created
    publish_date
    slug
  }
}
```

Headers:

```
{
  "filter": {"publish_date": {"_between": ["2022-06-05T11:14:05", "2022-06-05T11:14:05"]}}
}
```

### Errors Shown

```
{
  "errors": [
    {
      "message": "Variable \"$filter\" got invalid value { _between: [\"2022-06-05T11:14:05\", \"2022-06-05T11:14:05\"] } at \"filter.publish_date\"; Field \"_between\" is not defined by type \"date_filter_operators\".",
      "locations": [
        {
          "line": 1,
          "column": 20
        }
      ]
    }
  ]
}
```

### What version of Directus are you using?

9.11.1

### What version of Node.js are you using?

Whatever Cloud uses

### What database are you using?

Whatever Cloud uses

### What browser are you using?

apollographql

### How are you deploying Directus?

Community Cloud

**Comment by rijkvanzanten** [comment]
> so there may need to be more changes required, depending on should they be in a separate PR or not.

Lets do a single PR to clean that up 👍🏻
