### ISSUE TITLE
After installaion I cannot login

### ISSUE THREAD

**Issue by Mio11** [directus/directus#1378]
I see only this message

warning SERVER ERROR OCCURRED

Webserver
PHP Version 5.6.30
The extension are installered on apache mod_rewirite is loaded when I look in phpinfo. At the Installation directus sait the it is not turned on.

Directus Version 6.3.8

in Google Console it showed a 502 Error by the redircet to this adress /api/1/auth/login

**Comment by eli-oat** [comment]
I'm running into this same issue. @Mio11, did you find a solution?

**Comment by Mio11** [comment]
No I didn't find a solution. I've chosen another CMS.

**Comment by WellingGuzman** [comment]
Hey @Mio11 sorry, I somehow missed this ticket.

@eli-oat is there something in your logs (`/api/logs` directory) ?

**Comment by vasiliysmirnov** [comment]
@eli-oat had the same issue. 
The problem was in nginx server configuration, then i find [this](https://github.com/directus/directus-vagrant/blob/master/config/nginx/default) and add some missing lines.
Then i reinstall directus into root directory of my server and it runs perfect.

But i have a question, @WellingGuzman can i install directus in to some folder, "admin" for example?

**Comment by WellingGuzman** [comment]
@vasiliysmirnov Yes, you can, just make sure to change the `DIRECTUS_PATH` in `api/config.php` to `/admin/`

**Comment by vasiliysmirnov** [comment]
Strange, last time it didn't work. Okay, I'll try again, thanks!

**Comment by WellingGuzman** [comment]
@vasiliysmirnov let us know how it goes!

**Comment by vasiliysmirnov** [comment]
@WellingGuzman well, something is wrong.
I can log in, but then i can't do anything, errors, errors and more errors. None of the buttons works.
Here, a screenshot of errors:
![errors](https://cloud.githubusercontent.com/assets/13482625/24790167/bab177c6-1b7e-11e7-8b1f-75eaf1bd7a03.png)

**Comment by WellingGuzman** [comment]
Hey @vasiliysmirnov,

Are you still having this issue? I'd like to solve this issue, It seems to be a mal-configuration though.

I will close this ticket as this may have been solved, otherwise let me know I will reopen and work on its soon as possible.

**Comment by dalbinaco** [comment]
I managed to solve this issue fixing the path on `api/config.php`, line 32.

The Directus installation set this line mixing slashes and backslashes, like `define('DIRECTUS_PATH', '/labs/directus/');`

So I just changed everything to normal slashes, like `define('DIRECTUS_PATH', '/labs/directus/');` and it worked.

**Comment by WellingGuzman** [comment]
what was the change you made @dalbinaco ? what do you mean by normal slashes?

**Comment by dalbinaco** [comment]
@WellingGuzman Sorry, I previously pasted the same two lines on the above comment, just edited now with the differences.

I meant `/` and `\`.

**Comment by WellingGuzman** [comment]
Hey @dalbinaco, what's your stack? I assume the server was running on Windows?

**Comment by dalbinaco** [comment]
@WellingGuzman That's correct.

Apache 2.4.23
PHP 7.0.10
MySQL 5.7.14

**Comment by benhaynes** [comment]
@WellingGuzman – is there anything else we can update in the Docs or code comments to make sure this is clear (including for windows)?

**Comment by vasiliysmirnov** [comment]
@benhaynes well, if you put some example or default configuration for nginx, that's will be great! :)

**Comment by dalbinaco** [comment]
@vasiliysmirnov https://docs.getdirectus.com/6.3.6/#NGINX_Configuration

**Comment by vasiliysmirnov** [comment]
@dalbinaco I apologize for my inattention, thank you!
