### ISSUE TITLE
App Export Download this Page as CSV M2M Issues

### ISSUE THREAD

**Issue by w0kyj** [directus/directus#13791]
### Describe the Bug

The Download Page as CSV is supposed to export the table exactly as it appears in the table layout view:

For example, on v9.12.1, I have collections for Permits and Organizations. Permits has a many-to-many relationship field called orgs. I choose the following table layout for the Permits collection:

(the last three columns are Orgs: Title - English, Orgs: Subtitle - English, and Directus Roles: Name):
![image](https://user-images.githubusercontent.com/40695629/172697788-4360ab45-a3dc-4fe4-80cc-74a02cc2ce6b.png)

this is the CSV I get from Download this Page as CSV:
![image](https://user-images.githubusercontent.com/40695629/172697876-93bb477f-55ec-4eb2-bb26-1aa4f5dc1f9f.png)

### To Reproduce

- Created a collection: permit
    - Included default fields for status and create/update by/date
    - Create input field: title_english
    - Create dropdown field: language
    - Create m2m field: orgs --> related table organizations
- Collection: organizations
    - Add input fields: title_english, subtitle_english, title_french, subtitle_french

Add the following permit records:

Status | Title English | Language
-- | -- | --
Draft | Import Declaration | bilingual
Published | Federal Incorporation (... | bilingual
Draft | Explosive Importation ... | bilingual

Add the following organizations records:

Subtitle English | Subtitle French | Title English | Title French
-- | -- | -- | --
  |   | Corporations Canada | Fr Corporations Canada
Explosives Regulatory Division | Fr Explosives Regulatory Division | Natural Resources Canada | Fr Natural Resources Canada

- Export using "Download Page as CSV"
    - Tested without any relational fields and works correctly
    - Adding related organizations.title_english makes permits.title_english disappear
    - Relational data to the m2m fields doesn't export
    - Relational data to O2M fields like user_created.first_name exports correctly

## Observations:
- Duplicate field names seem to cause aggregation problems
- M2M relations are not exporting at all -- depth issue maybe?
- Noticed when testing on a dropdown field -- if the Display "Text" entry is blank, then no data will be exported :)
    - Ensure this is noted to the documentation OR put conditional to export the "Value" if the "Text" is empty

### Errors Shown

N/A

### What version of Directus are you using?

9.12.1 & 9.11.1

### What version of Node.js are you using?

Current & Community Cloud

### What database are you using?

SQLite

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally & Community Cloud

**Comment by rijkvanzanten** [comment]
What are the configured displays for those fields @bcartier?

**Comment by bcartier** [comment]
@rijkvanzanten 
Display for Checkbox Tree is configured to mirror the configured Choices 
Display for Wysiwyg is set as "Formatted Value"
