### ISSUE TITLE
Translations State Not Updating Properly

### ISSUE THREAD

**Issue by erondpowell** [directus/directus#13795]
### Describe the Bug

https://user-images.githubusercontent.com/62306630/172733348-b10c7b1f-c119-4270-8b90-1e36d14076dd.mov

### To Reproduce

As shown above, the state does not seem to be updating properly for Collection Name translations.

Settings > Data Model does not update at all.
The Content > Collection Name has issues as shown on screen.

### Errors Shown

None

### What version of Directus are you using?

9.11.1

### What version of Node.js are you using?

cloud

### What database are you using?

cloud

### What browser are you using?

chrome

### How are you deploying Directus?

cloud

**Comment by azrikahar** [comment]
> Settings > Data Model does not update at all.

This is correct, as #13103 updated Data Model view to always show the collection key instead of name (or translated name) now 👍

> The Content > Collection Name has issues as shown on screen.

I can't seem to reproduce the issue shown in 0:17 - 0:22 in Community cloud, nor locally. Does it still happen if you do a hard refresh?

**Comment by erondpowell** [comment]
> > Settings > Data Model does not update at all.
> 
> This is correct, as #13103 updated Data Model view to always show the collection key instead of name (or translated name) now 👍
> 
> > The Content > Collection Name has issues as shown on screen.
> 
> I can't seem to reproduce the issue shown in 0:17 - 0:22 in Community cloud, nor locally. Does it still happen if you do a hard refresh?

Yes it does still happen after hard refresh. I'm going to add you to the specific instance. 
Send me your email in a private chat and I can add you into the project.

**Comment by rijkvanzanten** [comment]
Closing this for now, as we haven't been able to reproduce this. Happy to keep discussing, and we'll reopen once more information becomes available 🙂
