### ISSUE TITLE
Installation failed with larvavel valet (nginx)

### ISSUE THREAD

**Issue by tonimain** [directus/directus#1379]
## Version Info
  - Directus version and branch: cloned repo from actual master
  - PHP version: 7.1 with mcrypt
  - MySQL version: 5.7.17
  - Web server: NGINX
  - OS name and version: osx 10 latest

## Expected Behavior
show me install instrcuctions

## Actual Behavior
Multiple fatal errors:
```
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /Users/tonhaupt/Development/private/directus/api/core/Directus/Auth/Provider.php on line 53

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /Users/tonhaupt/Development/private/directus/vendor/slim/slim/Slim/Slim.php on line 188

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in Unknown on line 0
```

## Steps to Reproduce
 1. cloned repo
 2. composer install
 3.  setup database and imported schema.sql
4. calling http://directus.dev/installation
5. is redirecting to: http://directus.dev/installation/installation/index.php?step=0    ???

**Comment by WellingGuzman** [comment]
hey @tonimain, if you are going to use the installation, you don't need to import the schema.

How your nginx config looks like? it seems that php environment variables are not set correctly, but I may be wrong.

Let me know.

**Comment by tonimain** [comment]
will check things out, thanks for the feedback.

**Comment by lesaff** [comment]
@tonimain, would you mind sharing your valet driver?

**Comment by xorander00** [comment]
I'm seeing the same issue.  I raised the PHP memory limit to 512M.  It looks like a memory leak somewhere.

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /usr/home/directus/app/current/api/core/Directus/Auth/Provider.php on line 53

**Comment by xorander00** [comment]
Looks like api/core/Directus/Auth/Provider.php:prependSessionKey is being called in an unterminated loop somewhere.  I see that it's referenced from setSessionKey as well, but that's only called once?

I've never looked at any source for this project, so I'm unfamiliar with it.  I'm assuming that a caller somewhere for prependSessionKey needs to be fixed?

**Comment by xorander00** [comment]
Fixed it.  configuration.php wasn't created, and so the session prefix wasn't be found.  Bootstrap::get was returning an empty array.

I removed config.php and re-installed.  Looks like it worked ok, so far.

**Comment by tonimain** [comment]
will test this out and feedback if it solves my problem too. thanks for the input

**Comment by tonimain** [comment]
hmmm always getting the same erro :(

**Comment by imknight** [comment]
Hi, @tonimain and @xorander00 can you 2 share the valet driver for directus ? really appreciate it.

**Comment by xorander00** [comment]
No problem.  What exactly do you need?  I'm not familiar with Directus.

**Comment by imknight** [comment]
did you use Laravel valet to run Directus ? if yes can you share valet driver for Directus ?

**Comment by WellingGuzman** [comment]
As far I know this is not a issue directly with Directus, I will close the ticket, but you can still keep the conversation on how to run it under Laravel valet.

**Comment by hybridvision** [comment]
For anyone finding this, I was able to get Directus 6.4.1 working with Laravel Valet by adding a custom Nginx configuration (it was easier than trying to make a driver). More details here: https://github.com/directus/directus/issues/1717#issuecomment-322052712
