### ISSUE TITLE
Can't edit field in the table view

### ISSUE THREAD

**Issue by marc-andrecroteau** [directus/directus#1380]
## Version Info
  - Directus version and branch: (Or commit hash) 49f52f2b1249c99885c1b350fc70472c7b8e19b0 (
     Fix updating relational field when the user has not permission to - #1367
  - PHP version: 5.6.30
  - MySQL version: 5.6.35
  - Web server: (Ex. Apache, nginx or IIS?) Apache 2.4.25
  - OS name and version: Debian 8
   I'm using this kind of architecture (Bitnami LAMP on Google Cloud Platform) :
   https://console.cloud.google.com/launcher/details/bitnami-launchpad/lampstack?q=lamp
   This is a fresh install, I never used directus before.

## Expected Behavior
When I'm click on the field button to edit table's fields, the page loads, and I can easily add/remove fields.

## Actual Behavior
When I'm click on the field button to edit table's fields, the page loads, but give me an JS error.

## Steps to Reproduce
 1. Install directus on the GCP Bitnami Lamp architecture
 2. Create a table
 3. Access table's fields

## Logs or Screenshots
![2017-03-23 18_19_55-abz-app _ settings](https://cloud.githubusercontent.com/assets/5251848/24274114/afe3fb44-0ffc-11e7-9b2d-6b0e87f3f3d8.png)

[104.196.129.85-1490310832677.txt](https://github.com/directus/directus/files/866430/104.196.129.85-1490310832677.txt)

**Comment by WellingGuzman** [comment]
Hey @marc-andrecroteau,

It seems that some template files are or being served corrupted, this has been reported before, and the files some times are different.

I've not being able to reproduce this error myself to know what's the error causing it, although from what I know and saw in the previous cases the files are fine in the server but when access through HTTP are chopped or merged with another file.

If you could help us reproduce this issue will be great.

**Comment by marc-andrecroteau** [comment]
Hey,

thanks a lot for the quick reply! In the next couple of days, I will try to reproduce the problem on another GCP LAMP Bitnami VM and write down all the specific steps I've done.

Have a great day!

**Comment by benhaynes** [comment]
Any updates @marc-andrecroteau?

**Comment by WellingGuzman** [comment]
Now that I read this again and noticed that @marc-andrecroteau mentioned `bitnami` which the server probably has PageSpeed enabled by default, causing this type of error.

This issue was solved by: https://github.com/directus/directus/commit/8cc6961486874cedbfa4169cd27f9835800d23e1 in 6.4 and https://github.com/directus/directus/commit/8cc6961486874cedbfa4169cd27f9835800d23e1 in 6.3
