### ISSUE TITLE
Weekly grouped time series is broken if the week contains 2 months.

### ISSUE THREAD

**Issue by emrahnazif** [directus/directus#13809]
### Describe the Bug

<img width="1190" alt="Screenshot 2022-06-09 at 16 26 14" src="https://user-images.githubusercontent.com/33692017/172871909-ab4d86e8-778b-419b-825f-2f5b0a0b7389.png">

Here is the API data:

`{
	"data": [{
		"date_created_year": 2022,
		"date_created_month": 5,
		"date_created_week": 19,
		"count": {
			"id": 40280
		}
	}, {
		"date_created_year": 2022,
		"date_created_month": 5,
		"date_created_week": 20,
		"count": {
			"id": 44853
		}
	}, {
		"date_created_year": 2022,
		"date_created_month": 5,
		"date_created_week": 21,
		"count": {
			"id": 52191
		}
	}, {
		"date_created_year": 2022,
		"date_created_month": 5,
		"date_created_week": 22,
		"count": {
			"id": 37699
		}
	}, {
		"date_created_year": 2022,
		"date_created_month": 6,
		"date_created_week": 22,
		"count": {
			"id": 63391
		}
	}, {
		"date_created_year": 2022,
		"date_created_month": 6,
		"date_created_week": 23,
		"count": {
			"id": 138148
		}
	}]
}`

If a week contains 2 months, the chart is broken. 
API returns 2 results for that Nth week. See `"date_created_month": 5, "date_created_week": 22,`  and  `"date_created_month": 6, "date_created_week": 22,` Technically, it is correct. I am not sure if fix should be applied to API or APP. It feels like `date_created_month` shouldn't be involved for this return. 

### To Reproduce

Create a chart using the json above

### What version of Directus are you using?

9.12.1

### What version of Node.js are you using?

n/a

### What database are you using?

mysql

### What browser are you using?

chome

### How are you deploying Directus?

local

**Comment by azrikahar** [comment]
I believe this is the same as #8701 (may not be fully resolved)

**Comment by rijkvanzanten** [comment]
I think this might've been resolved in https://github.com/directus/directus/pull/14096. @emrahnazif could you confirm the issue still exists in ^9.13  ?

**Comment by emrahnazif** [comment]
> I think this might've been resolved in #14096. @emrahnazif could you confirm the issue still 

From this (v9.12.2):
<img width="542" alt="Screenshot 2022-06-30 at 19 29 45" src="https://user-images.githubusercontent.com/33692017/176741499-e2d2c809-5e3d-434b-bc82-1cb9a69acd44.png">

To this (v9.13.0):
<img width="542" alt="Screenshot 2022-06-30 at 19 33 19" src="https://user-images.githubusercontent.com/33692017/176741514-d0f3535e-d78c-479a-bf7a-d2672ac4d506.png">

It looks like fixed. Thank you.

**Comment by rijkvanzanten** [comment]
Perfect! Thanks for confirming 🙂
