### ISSUE TITLE
Strange Redirect Issue

### ISSUE THREAD

**Issue by gavinbkr** [directus/directus#1381]
## Expected Behavior
Ability to access the directus system in a sub-directory. Issue with accessing the Directus system. Directus was downloaded and installed with no apparent issues on the 22nd March.

## Actual Behavior
After logging in to Directus, the system tires to load the main root page instead of the directus system but the url is still as per the directus system. It's quite hard to explain sorry.

If I then edit the url to remove the /files extension for example and hit enter it will then let me into Directus and I can navigate around with no issues. As soon as I hit refresh on any page it then tries to load the root again but does not change the url.

Checked the document root in config and all is fine set to /ticketmanager/, removed cookies and still errors, and tried multiple browser types no joy.

## Steps to Reproduce
 1. Access directus login screen and enter details.
 2. Navigate around Directus and hit enter.
 3. 

## Logs or Screenshots
Main url work fine when accessed:
![screen shot 2017-03-24 at 11 25 30](https://cloud.githubusercontent.com/assets/26649777/24292343/dbb7e07c-1084-11e7-8312-ed85b362179d.png)

Initial access to Directus in sub-directory is fine:
![screen shot 2017-03-24 at 11 26 07](https://cloud.githubusercontent.com/assets/26649777/24292366/ee85fa04-1084-11e7-9dac-f200cfe9a429.png)

Once login info entered and I hit enter it does the following, trying to load the main page and not directus:
![screen shot 2017-03-24 at 11 26 20](https://cloud.githubusercontent.com/assets/26649777/24292381/feb23992-1084-11e7-9db7-32b633c53100.png)

If I manually update the url I can get in:
![screen shot 2017-03-24 at 11 26 34](https://cloud.githubusercontent.com/assets/26649777/24292394/10d0de4e-1085-11e7-9ceb-4ae33bcd8e99.png)

But as soon as I hit refresh it tries to load the main page in again:
![screen shot 2017-03-24 at 11 26 43](https://cloud.githubusercontent.com/assets/26649777/24292405/1e619170-1085-11e7-96db-6920a5039c3d.png)

**Comment by WellingGuzman** [comment]
Hey @gavinbkr, that's really strange, are you using nginx or apache? which OS are you on?

**Comment by gavinbkr** [comment]
Tired it on Mac and PC and a few different browsers.

Server is Apache as far as I am aware. Whats the easiest way to find out I have shell access.

It is very strange indeed.

**Comment by WellingGuzman** [comment]
So if you didn't configure anything, so you are on Apache, does you main directory has a `.htaccess` files, it seems like the parent directory or the virtual host configuration has effect in the subdirectory `.htaccess` configuration.

can you share those files, if any?. please make sure to remove any sensitive data.

**Comment by gavinbkr** [comment]
No .htaccess file in parent.

File structure is:
![screen shot 2017-03-24 at 12 23 09](https://cloud.githubusercontent.com/assets/26649777/24294061/b1edeb80-108c-11e7-9c6f-687d498077de.png)

.htaccess file in ticketmanger folder is:
 
[htaccess.txt](https://github.com/directus/directus/files/867790/htaccess.txt)

**Comment by gavinbkr** [comment]
Is you email address still hola at wellingguzman.com?

I can fire over FTP access if you like?

**Comment by gavinbkr** [comment]
Config file (with server bits removed) if that helps/

Been playing with .htaccess and files but nothing seems to have solved it yet :(

[config.php.zip](https://github.com/directus/directus/files/867990/config.php.zip)

**Comment by WellingGuzman** [comment]
Hey @gavinbkr, sorry for the delay, lots going on right now.

If possible, please send me the FTP access to me email hola at wellingguzman(.)com or you can join us in slack and send me a private message there.

I will se what I can do there.

**Comment by gavinbkr** [comment]
Hey, not a problem at all appreciate the help.

I gave up in the end and just stuck Directus on its own sub-domain as it was working fine if I had it in the root folder.

To be honest I think I prefer it that way so will do that from now on.

I will close this and if I have the same issue in future will re-open :)

Cheers.

**Comment by WellingGuzman** [comment]
Thanks @gavinbkr, and if there's anything else we can help you with, please let us know.
