### ISSUE TITLE
ability to set a slug to only populate on initial creation of a record

### ISSUE THREAD

**Issue by chrisdrackett** [directus/directus#1384]
this way even if the user changes the field linked to the slug, links will not break (if a slug is being used in links)

**Comment by benhaynes** [comment]
Better still, when and how this updates should be an Interface option. 

@rijkvanzanten – any thoughts on this?

**Comment by WellingGuzman** [comment]
Hey @benhaynes I got this cover, I will work on this soon. I asked him to report this ticket so I do not forget to add the option later today.

Sorry for the confusion :)

**Comment by WellingGuzman** [comment]
Buuuuuut, if @rijkvanzanten have not problem in work with you, if I haven't by then, I'm good.

**Comment by rijkvanzanten** [comment]
Hi! Great idea! 

What will be the available options?
- always editable (current default)
- read only based on other field?
- on creation editable, read only after that?

Another thing; is the slug already checked for uniqueness in the table? I don't know if this is currently the case but it definitely should (be an option). 

I think @welling gets to it before I do 👍🏻

**Comment by benhaynes** [comment]
Ooh, I like the check for uniqueness @rijkvanzanten! Good thinking! I think @WellingGuzman is just going to get it working... then you can take over.

**Comment by WellingGuzman** [comment]
well, well, well, guess who's here and hasn't done anything yet.

Agreed, I can do what I promised then @rijkvanzanten can jump in.

**Comment by WellingGuzman** [comment]
Would it help to add button to refresh the slug when the slug are only populate on creation, then there's quick option to update the slug. thoughts?

**Comment by WellingGuzman** [comment]
New option added here: https://github.com/directus/directus/commit/2bac1328ced4c243da72c6f2c74d08d2959ee9b8

**Comment by WellingGuzman** [comment]
I'm going to close as it solve the problem in this ticket, we can keep the conversation about the new features suggested by @rijkvanzanten
