### ISSUE TITLE
Flows: Condition Operation returning not allowed error

### ISSUE THREAD

**Issue by cesarsalesgomes** [directus/directus#13855]
### Describe the Bug

Flows created with Condition Operations seems to be returning permission error when performing filters with the available variables ($trigger, $last, ...)

### To Reproduce

1. Create Flow with the setup Event Hook -> Action (Non-Blocking) -> Scope (items.create) -> Select Collection to trigger
2. Create Condition Operation using the variable $trigger on the filter:

![Flow-Bug-1](https://user-images.githubusercontent.com/6998275/173246705-a78a4357-8e33-477d-b58a-5c7498843005.png)

3. Trigger flow by creating item on the previous Collection
4. Check the log created on the Condition Operator step

### Errors Shown

![Flow-Bug-2](https://user-images.githubusercontent.com/6998275/173246854-6f92cb9c-bdf7-466b-b91d-6d0e8986309f.png)

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16.15.1

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

Running locally with Docker

**Comment by jay252** [comment]
I've been struggling with this one also. It seems like the schema generated by generateJoi() may not be reflecting what was intended. When I call describe() on the schema created on line 258 of generate-joi.ts I see the $trigger key repeated twice. I'm having a hard time following this recursive function and I hope I'm not leading anyone down the wrong path. 

The work that has been put into Flows is incredible. Thanks for the effort. I look forward to watching this evolve.

https://github.com/directus/directus/blob/main/packages/shared/src/utils/generate-joi.ts#L258

**Comment by cesarsalesgomes** [comment]
> I've been struggling with this one also. It seems like the schema generated by generateJoi() may not be reflecting what was intended. When I call describe() on the schema created on line 258 of generate-joi.ts I see the $trigger key repeated twice. I'm having a hard time following this recursive function and I hope I'm not leading anyone down the wrong path.
> 
> The work that has been put into Flows is incredible. Thanks for the effort. I look forward to watching this evolve.
> 
> https://github.com/directus/directus/blob/main/packages/shared/src/utils/generate-joi.ts#L258

Totally agree! The simplicity that flows have made event-driven coding is very exciting :D

**Comment by jay252** [comment]
Changing lines 95 - 97 https://github.com/directus/directus/blob/main/packages/shared/src/utils/generate-joi.ts#L95-L97

From:
schema[key] = Joi.object({
	[key]: generateJoi(value as FieldFilter, options),
});

To:
schema[key] = generateJoi(value as FieldFilter, options);

Seems to have removed the duplicate keys from the schema. It appears that the $trigger is evaluating and validating properly now. The Condition is working in my limited testing but I have not done enough testing to know if new problems have been introduced.

**Comment by azrikahar** [comment]
@jay252 thanks for the continuously looking into this! The fix is currently included in #13596, and will try to check more thoroughly whether that affects anything potentially uncaught at the moment 👍

**Comment by makote** [comment]
Flow conditions aren't working for me on 9.12.13

**Comment by imiskolee** [comment]
how about now. we're also blocking this. can not apply a `Condition` operator behind a `Read Data` operator.

**Comment by VISHNU-P-M** [comment]
I created a collection "Test" and it has toggle field `approved`,
I need to check the condition on this toggle field update to true or false.
And my filter condition is
`{
    "$trigger": {
        "payload": {
            "approved": {
                "_eq": true
            }
        }
    }
}`

I got the exception like 
`"message": "\"$trigger.event\" is not allowed",`

how can I rewrite my condition filter for logging while the approved field is updated to true?

**Comment by azrikahar** [comment]
@VISHNU-P-M Are you on Directus 9.14.2 and onwards? The fix should be released in 9.14.2. 

If you have any further questions, do post it in discussions so that we're not sending notifications to everyone in this thread going forward.

**Comment by VISHNU-P-M** [comment]
I upgrade directus version to 9.14.3 and I got the result as I expected at that moment,
Now I updated a another field in the test collection, the condition returning approved toggle true when actually approved is null :( 

Trigger payload::
{ "event": "test.items.update", "payload": { "name": "testName" }, "keys": [ "2" ], "collection": "test" }

condition:
"$trigger": { "payload": { "approved": { "_eq": true } } }

payload actually has no field like approved, but it's returning true for the condition!
@azrikahar Why it is returning true?

**Comment by gkielwasser** [comment]
> I upgrade directus version to 9.14.3 and I got the result as I expected at that moment, Now I updated another field in the test collection, the condition returning approved toggle true when actually approved is null :(
> 
> Trigger payload:: `{ "event": "test.items.update", "payload": { "name": "testName" }, "keys": [ "2" ], "collection": "test" }`
> 
> condition: `"$trigger": { "payload": { "approved": { "_eq": true } } }`
> 
> payload actually has no field like approved, but it's returning true for the condition! @azrikahar Why it is returning true?

I have the same issue in 9.14.3

**Comment by azrikahar** [comment]
@gkielwasser would you mind opening a new issue for it? So that we can track both @VISHNU-P-M and your reports together and investigate further 👍 Thanks!

**Comment by azrikahar** [comment]
> I have fixed it on #14311, but no one cares.

I can see how it can be frustrating, unfortunately it'd take time to triage and review PRs (and issues). It's not that no one cares 👍 Hope that's understandable.

**Comment by gkielwasser** [comment]
> @gkielwasser would you mind opening a new issue for it? So that we can track both @VISHNU-P-M and your reports together and investigate further 👍 Thanks!

This issue can be followed here https://github.com/directus/directus/issues/14571

**Comment by andy1li** [comment]
I'm having the same issue. Wasted hours experimenting and reading docs, and thought it had been something wrong on my part. 😂

And here we are.
