### ISSUE TITLE
Backend documentation jump links not working

### ISSUE THREAD

**Issue by rowild** [directus/directus#13852]
### Describe the Bug

When clicking on a e.g. "Learn more" hash link in the documentation of a local setup, the login page is opened, but not the jump link. A short video is attached.

https://user-images.githubusercontent.com/213803/173226602-1a1e0ac1-517d-463f-baf2-0f64be054c11.mp4

(New to Directus, so I do not know if this is "expected behaviour" or not. If so, please feel free to delete my issue. Thank you!)

### To Reproduce

In a local setup

1. navigate to "Documentation"
2. Go to e.g. "Item Page"
3. Click on one of the jump links at the top of this page (e.g. "Create an Item")

### Errors Shown

No errors shown; instead a complete reload of the page happens that eventually shows the login page instead of jumping to the local anchor.

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16.14.2

### What database are you using?

SQLite 3.28.0

### What browser are you using?

Chrome 102.0.5005.61

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
> (New to Directus, so I do not know if this is "expected behaviour" or not. If so, please feel free to delete my issue. Thank you!)

It is definitely not an expected behaviour, so no worries! However there is an existing issue #12752 to track this particular odd behaviour, so I'll close this in favor of coalescing this issue over there 👍

**Comment by rowild** [comment]
Sorry for the duplication! I looked but didn't find the existing issue...
