### ISSUE TITLE
Address Interface Concepting

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1385]
Currently if you want to have an address in Directus we show several fields sequentially, like this:
```
-----------------
[Address]
-----------------
[Address 2]
-----------------
[City]
-----------------
[State]
-----------------
[zip]
-----------------
[country]
-----------------
```

This is functional, but certainly could be optimized from a UX perspective. It's also a common field-set making this improvement a "big deal". Ideally we would want something like this in a single Interface:

```
-----------------
[Address]
[Address 2]
[City] [State] [zip]
[country]
-----------------
```

But the problem is that Directus has a 1:1 mapping with the database – so the intention of an interface is to save to a (single) column. So while we _could_ save the entire address concat'd into a TEXT column, that seems icky.

If we could we create an `address` interface that "maps" to other columns – we would have a huge improvement! Let's use this ticket to brainstorm how best to handle this (and similar optimizations)... and hopefully get a new Interface out of it!

I'd love to get some input from the following task force... but all opinions are welcome!
@WellingGuzman @rijkvanzanten @the0neyouseek

**Comment by benhaynes** [comment]
Here's my two cents:

`address` Interface is an ALIAS datatype (meaning it's not attached to a specific column) and we have the following options:
* Address Column Mapping (Dropdown of columns in this table)
* Address 2 Column Mapping
* City Column Mapping
* State Column Mapping
* etc...

After that, I feel like there are two possible high-level directions:

## Option 1: Submit Multiple Values from One Interface
I like this one more, it feels cleaner. We change the way Directus works (I think, maybe it will just work!). We HIDE all the proper column interfaces (address, city, etc)... but SHOW the `address` column interface (an ALIAS). This address interface has each input name equal to the column it maps to. When we save the Item, those values all save to their respective columns.

The only think I don't know is if there are any issues submitting values from Interfaces that aren't the true "owner" of that column. OR what would happen if you DIDN'T HIDE the proper interface and TWO values are submitted with the same name. Maybe the address interface could run a check for this `onLoad` and throw a warning?

## Option 2: Copy Values Into Other Interfaces
We have all the fields nicely organized in one Interface template and `onchange` each input saves its value into the "normal" interface for that column. Then we "hide" the normal columns/interfaces so we only see the new address Interface.

----------

Thoughts? Hopes? Wishes? Dreams? Concerns?

**Comment by rijkvanzanten** [comment]
I absolutely love this idea @ricricucit! 😄

The map / address interface could very well be the same thing in my opinion.

**Comment by benhaynes** [comment]
This is great @ricricucit! I agree, we should make the Interface save as standard lat/lon in the managed column. The Interface can *also* have options for mapping the geocoded values to other columns.

If the other column inputs are hidden then we can display it exactly as you have it sketched out here. Otherwise we can simply add values into the other inputs automatically (based on the mapping in the options).

This is exciting! It will be great to have such a thought-through and polished Map/Location interface!

**Comment by rijkvanzanten** [comment]
Lets create a `hidden` interface, which allows people to create columns that have a read-only output in the admin. That way, someone could create optional hidden interfaces for the different parts of an address to save to different columns.

**Comment by rijkvanzanten** [comment]
Options:

`hidden` interface:
- [ ] `show_value`  shows `read_only` textinput with the set value

`map` interface:
- [ ] `save_as_json` save address values as JSON (toggle)
- [ ] `column_mapping` (JSON) map address parts to user columns (optional)
- [ ] `google_maps_api_key` (textinput) (required)

**Comment by benhaynes** [comment]
This is an awesome idea @rijkvanzanten! A great solution.

I question the `show_value` option for a `hidden` interface... but I get why it's useful.

For the `map` interface options, maybe we can have a fallback (or duplicate this interface) so it doesn't *need* an API key? Is there an open-source map that does geocoding for addresses?

**Comment by MartinMekhaiel** [comment]
there is leaflet
https://github.com/Leaflet/Leaflet (MAP)

https://github.com/openstreetmap/Nominatim (Geocoder)
and there is nominatim for geocoding which can be self hosted or there are also paid services, but honestly having set nominatim up on my own thats not really easy (indexing of the whole world takes really long and a big machine).

I'd reccomend to stick with gmaps!

cheers

**Comment by rijkvanzanten** [comment]
This has been moved over to the feature request tool, since there isn't an "issue" with the current implementation and this being a request/proposal for enhancement.

https://request.getdirectus.com/r/133

**Comment by GMZC** [comment]
Hi there, 
first of all congratulations for this great project, i'm new to the world of headless cms and for all i've seen now i really love directus.
I was searching around how to fetch map interface data from the api, right now i just get lat and lng and for a specific project i would be interested getting and setting more info like the address. For example i can set the lat and lng in the map interface by typing an address but i can't get this address neither in the directus UI or the api (only posting the lat and lng). I reopen this thread because the link https://request.getdirectus.com/r/133 doesn't lead to anything related to this particular topic. 
Thank you kindly for your reply

**Comment by benhaynes** [comment]
This ticket is specifically about grouping fields in a more UX-friendly way... which we can partially do now with our new layouts.

What you're looking for sounds more like "geolocation" — which could be added as a custom interface, or a custom API endpoint.

**Comment by GMZC** [comment]
Yes thank you doing some research I came accross custom interfaces and I figured out how to create a custom interface. I started from the Map Interface and got to output address data in the admin, currently I try to figure out how to get address data in the API, so i'm digging in API endpoints. I will create a specific ticket if needed further. Thanks for your reply

**Comment by Gregoor** [comment]
I'm evaluating Directus for a project right now (I'm impressed so far, kudos!) and was wondering if this is still being considered? The request.getdirectus.com portal seems to be down and I found nothing about it on GH discussions. Cheers!

**Comment by Gregoor** [comment]
Thanks for the swift response! I can understand that the address use case is somewhat unique there. It would be great to be able to map the output of a single component to multiple fields in the future but I can certainly appreciate that this is a lot of complexity for a less-common case.
