### ISSUE TITLE
WordPress

### ISSUE THREAD

**Issue by szepeviktor** [directus/directus#1386]
Hello!

Are there presets (settings templates) for existing CMS-s like WordPress?

**Comment by benhaynes** [comment]
No, Directus is a "headless" CMS, which means it only manages content/data and tries to avoid anything presumptuous about how you might use that data (website, native app, kiosk, etc). So there are no templates built-in. However we do have an example of how you could setup a website (with templating): https://github.com/directus/webapp-example

**Comment by szepeviktor** [comment]
Thanks.

I was trying to edit an existing WP database as an experiment.

**Comment by rijkvanzanten** [comment]
@szepeviktor WordPress databases are notoriously hard to convert to a 'clean' database without all the WordPress 'junk' polluting the data. Please let me / us know if you find an easy way :smh
