### ISSUE TITLE
Can't install composer dependencies

### ISSUE THREAD

**Issue by johhansantana** [directus/directus#1387]
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for slim/slim 2.3.2 -> satisfiable by slim/slim[2.3.2].
    - slim/slim 2.3.2 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
  Problem 2
    - slim/slim 2.3.2 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - slim/extras dev-develop requires slim/slim >=2.0.0 -> satisfiable by slim/slim[2.3.2].
    - Installation request for slim/extras dev-develop -> satisfiable by slim/extras[dev-develop].

PHP Version when doing `php -v`

PHP 5.6.28 (cli) (built: Dec  6 2016 12:38:54)

**Comment by rijkvanzanten** [comment]
I believe this is a duplicate of #1352

**Comment by rijkvanzanten** [comment]
Could you try adding the following to your `.bash_profile / .zshrc`?

```bash
# .bash_profile / .zshrc
# make sure the php version is the version selected in MAMP
export MAMP_PHP=/Applications/MAMP/bin/php/php5.6.10/bin
export PATH="$MAMP_PHP:$PATH"
```

Also, make sure that you use PHP >= 5 and not PHP 7+

**Comment by johhansantana** [comment]
Hi @rijkvanzanten I'm using XAMPP

I was able to install mcrypt

After that doing `composer install` gives me new errors of php version

```
Problem 1
    - This package requires php >=5.5.0 but your PHP version (5.4.45) does not satisfy that requirement.
  Problem 2
    - Installation request for directus/database 0.1.3 -> satisfiable by directus/database[0.1.3].
    - directus/database 0.1.3 requires php >=5.5.0 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 3
    - Installation request for league/flysystem 1.1.x-dev -> satisfiable by league/flysystem[1.1.x-dev].
    - league/flysystem 1.1.x-dev requires php >=5.5.9 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 4
    - Installation request for league/flysystem dev-master -> satisfiable by league/flysystem[dev-master].
    - league/flysystem dev-master requires php >=5.5.9 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 5
    - Installation request for zendframework/zend-db dev-directus -> satisfiable by zendframework/zend-db[dev-directus].
    - zendframework/zend-db dev-directus requires php ^5.5 || ^7.0 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 6
    - Installation request for zendframework/zend-stdlib 3.0.1 -> satisfiable by zendframework/zend-stdlib[3.0.1].
    - zendframework/zend-stdlib 3.0.1 requires php ^5.5 || ^7.0 -> your PHP version (5.4.45) does not satisfy that requirement.
```

where my `php -v` outputs different result = `PHP 5.6.28 (cli) (built: Dec  6 2016 12:38:54) `

**Comment by johhansantana** [comment]
After fighting with my mac I had a bunch of conflicts with php versions so I got https://github.com/wilmoore/php-version installed which helps you switch between php versions currently installed then just with Homebrew installed the php version of choice.

**Comment by WellingGuzman** [comment]
Hey @johhansantana glad it solve your problem, and thanks for letting us know about that repo, it can come handy for other users! 👍
