### ISSUE TITLE
Some relationships lost while importing content from CSV with M2M relationships

### ISSUE THREAD

**Issue by martabitbrain** [directus/directus#13881]
### Describe the Bug

Hi!

I'm not sure if I'm doing something wrong, but when I try to import a CSV file with **M2M relationships** to existing items, the relations are only getting saved on the last element that has such relation. 

Please tell me if you need additional tests or examples on my part.

Thanks :)

### To Reproduce

For this example, set up three content types:

Category: 
- id
- name

Subcategory: 
- id
- name

Article: 

- category (M2M)
- subcategory (M2M)
- slug (input, url-safe)
- title (input)
- subtitle (input)

This is the CSV to import:
```
category,subcategory,slug,title,subtitle
"[{""id"":2}]","[{""id"":1}]","slug-0","Title 0","Subtitle 0"
"[{""id"":1}]","[{""id"":3}]","slug-a","Title A","Subtitle A"
"[{""id"":1}]","[{""id"":3}]","slug-b","Title B","Subtitle B"
"[{""id"":2}]","[{""id"":2}]","slug-c","Title C","Subtitle C"
```

And this is the result of an export after the import:
```
"id","title","subtitle","category","subcategory"
75,"Title 0","Subtitle 0","[]","[1]"
76,"Title A","Subtitle A","[]","[]"
77,"Title B","Subtitle B","[1]","[3]"
78,"Title C","Subtitle C","[2]","[2]"
```

If we look closely to the category column:
- id 2 (not saved)
- id 1 (not saved)
- id 1 (the last reference to this id, saved)
- id 2 (the last reference to this id, saved)

If we do the same with the subcategory column:
- id 1 (saved, the only reference to this id)
- id 3 (not saved)
- id 3 (saved, the last with this id)
- id 2 (saved, the only reference to this id)

### Errors Shown

No errors shown.
No erros on JS console either nor in the POST request.

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16.15.1

### What database are you using?

MySQL 8.0.29

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by br41nslug** [comment]
For M2M relations you'll need an extra layer in your relation to bridge the junction table.
For example creating new related items:
```csv
"id","status","relation"
2,"published","[{""test_relation_id"":{""test"":""123""}},{""test_relation_id"":{""test"":""456""}}]"
```
Or for linking existing items:
```csv
"id","status","relation"
2,"published","[{""test_relation_id"":{""id"":1}},{""test_relation_id"":{""id"":2}}]"
```
In the situation you describe you're not linking `categories`/`subcategories` with IDs but you're creating a record in junction table. Using your example I think something like this should work (if i guessed the fields on the junction tables right): ```csv
category,subcategory,slug,title,subtitle
"[{""category_id"":{""id"":2}}]","[{""subcategory_id"":{""id"":1}}]","slug-0","Title 0","Subtitle 0"
"[{""category_id"":{""id"":1}}]","[{""subcategory_id"":{""id"":3}}]","slug-a","Title A","Subtitle A"
"[{""category_id"":{""id"":1}}]","[{""subcategory_id"":{""id"":3}}]","slug-b","Title B","Subtitle B"
"[{""category_id"":{""id"":2}}]","[{""subcategory_id"":{""id"":2}}]","slug-c","Title C","Subtitle C"
```
Closing this for now, if this does not solve it we can re-open the issue 😄

**Comment by martabitbrain** [comment]
You are totally right. I forgot the junction table. Thank you 🤦🏻‍♀️
(And sorry)

**Comment by jotatoledo** [comment]
> For M2M relations you'll need an extra layer in your relation to bridge the junction table. For example creating new related items:
> 
> ```
> "id","status","relation"
> 2,"published","[{""test_relation_id"":{""test"":""123""}},{""test_relation_id"":{""test"":""456""}}]"
> ```
> 
> Or for linking existing items:
> 
> ```
> "id","status","relation"
> 2,"published","[{""test_relation_id"":{""id"":1}},{""test_relation_id"":{""id"":2}}]"
> ```
> 
> In the situation you describe you're not linking `categories`/`subcategories` with IDs but you're creating a record in junction table. Using your example I think something like this should work (if i guessed the fields on the junction tables right):
> 
> ```
> category,subcategory,slug,title,subtitle
> "[{""category_id"":{""id"":2}}]","[{""subcategory_id"":{""id"":1}}]","slug-0","Title 0","Subtitle 0"
> "[{""category_id"":{""id"":1}}]","[{""subcategory_id"":{""id"":3}}]","slug-a","Title A","Subtitle A"
> "[{""category_id"":{""id"":1}}]","[{""subcategory_id"":{""id"":3}}]","slug-b","Title B","Subtitle B"
> "[{""category_id"":{""id"":2}}]","[{""subcategory_id"":{""id"":2}}]","slug-c","Title C","Subtitle C"
> ```
> 
> Closing this for now, if this does not solve it we can re-open the issue 😄

Would be nice to include such a complex example in the [import section of the docs](https://docs.directus.io/app/import-export.html)
