### ISSUE TITLE
Copy of M2M Relation not showing when inside a group field

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/directus#13899]
### Describe the Bug

I try to setup copy fields and want to copy M2M relations, but when the M2M field is inside a group field, there is no option to open the dropdown for the relation -/+ of the M2M field.

Categories outside of group field:
![image](https://user-images.githubusercontent.com/15796397/173770010-901ee6fc-ce48-45ef-874d-28ad4e1ab39e.png)

Categories inside of group field:
![image](https://user-images.githubusercontent.com/15796397/173770124-2f420b31-9ae7-4d1d-a289-9a9f32bbd783.png)

### To Reproduce

Add a M2M field inside a Group Field and try to setup copy settings for this field

### What version of Directus are you using?

9.12.2 (Maintainer update: confirmed to still be an issue on `9.16.1`)

### What version of Node.js are you using?

v14.19.3

### What database are you using?

MySQL 8

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
Linear: [ENG-245](https://linear.app/directus/issue/ENG-245/copy-of-m2m-relation-not-showing-when-inside-a-group-field)
