### ISSUE TITLE
A way to bypass authentication for GET requests?

### ISSUE THREAD

**Issue by johhansantana** [directus/directus#1389]
Is there a way to bypass the authentication for GET requests for certain endpoints? I want to make a web app that just gets the data from the database and show it.

**Comment by benhaynes** [comment]
Hey @johhansantana – we're adding a "public" user group for just this purpose in the next version (`6.4`). It should be available for beta in about a week.

**Comment by johhansantana** [comment]
awesome! how would I be able to get the beta?

**Comment by benhaynes** [comment]
It will be a branch (or maybe a beta release tag) like this:

https://github.com/directus/directus/tree/version/6.4

**Comment by johhansantana** [comment]
Coo!, thank you @benhaynes

**Comment by audacitus** [comment]
Hi @johhansantana. I have the 6.4 version (Ruby Rabbit). Is there a resource/tutorial on how to do this? I've set some tables to the Public group and assigned a preview URL but no luck. I'm sure I'm not doing something right.

Thanks.
