### ISSUE TITLE
User's `ID`, `Last page`, `Last access` although disabled in Fields permissions still show in an M2M relation

### ISSUE THREAD

**Issue by Pachat** [directus/directus#13912]
### Describe the Bug

User's `ID`, `Last page`, `Last access` although disabled in Fields permissions still show in an M2M relation

### To Reproduce

- In a collection, set an M2M field related to Directus_users
- In a role, for Directus_users / Read / Use Custom / Fields Permissions
- Disable `ID`, `Last page`, `Last access`
- Connected under a user of the role, go to the collection's detail and add a user in the M2M field. Save
- Click on the user

### Errors Shown

In the popup form of the user, you still see `ID`, `Last page`, `Last access`

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16.14.0

### What database are you using?

PostgreSQL 14.2

### What browser are you using?

Firefox and Edge

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
> Click on the user

Does the user have edit permissions to those fields?

**Comment by Pachat** [comment]
Yes. The edit permissions have also been deactivated for `ID`, `Last page`, `Last access`

**Comment by rijkvanzanten** [comment]
Does the role have app minimal permissions? I'm fairly sure the app minimum permissions allow the user to update their own profile

**Comment by rijkvanzanten** [comment]
In that case, this is working as expected. The app-access permissions allow the user to update their own profile, so those fields are expected to be visible 👍🏻

**Comment by Pachat** [comment]
Well, the end user will not understand to see `ID`: `49a56dc7-35ff-40d9-8b17-bbe3ef4e8b3c`, 
nor to discover that he is tracked with `Last page`: `/content/project/8b74c032-5550-4fec-a41c-2a29de6e082d` 
all of that will generate useless questions to the support.

**Comment by Pachat** [comment]
And to add what appears strange, that it is possible to hide Token. So why not  `ID`, `Last page`, `Last access`?
All these fields certainly belong to the user's profile from a technical POV, 
but not from the end-user POV. He does not bother about his `uuid`.
