### ISSUE TITLE
Translation strings - Drag n Drop Bug

### ISSUE THREAD

**Issue by erondpowell** [directus/directus#13918]
### Describe the Bug

https://user-images.githubusercontent.com/62306630/173930092-0a9da4f8-e17b-440a-acf5-a0aa184ed61f.mov

### To Reproduce

As seen in the video above.

### Errors Shown

Not certain if these are related.

<img width="688" alt="Screen Shot 2022-06-15 at 4 08 35 PM" src="https://user-images.githubusercontent.com/62306630/173930308-cef78a83-8422-4759-a2cc-5ce7f0cf5f9f.png">

### What version of Directus are you using?

9.12

### What version of Node.js are you using?

cloud

### What database are you using?

cloud

### What browser are you using?

chrome

### How are you deploying Directus?

Cloud

**Comment by azrikahar** [comment]
> Well _that_ shouldn't happen. Though, I'm wondering why these are sortable at all. 🤔

If memory serves, I believe the intention was sort of (pun unintended) allowing the flexibility to users ordering the preferred/frequently-modified language on top. We can definitely tweak that such as making it fixed if that's preferred.

**Comment by benhaynes** [comment]
Ahh, I see. That's interesting, I suppose. I defer to you and @rijkvanzanten on if we want to keep the sorting.

**Comment by rijkvanzanten** [comment]
> Ahh, I see. That's interesting, I suppose. I defer to you and @rijkvanzanten on if we want to keep the sorting.

The sort isn't global, which in turn means that the sort order will be different for each of the translations strings. I think it's actually nicer if we just sort them in a known order (like alphabetical on the language code), so it's consistent between the various translations 👍🏻
