### ISSUE TITLE
API returns null for files

### ISSUE THREAD

**Issue by MarcinKuder** [directus/directus#1392]
I have a simple test table with a 'name' column and 'image' column that is of a single file type.
The record is created using a GUI, name and image are added. The problem is that the API does not return the image/file reference. Query for all files return empty data collection See 'actual behavior' below.
The database contains valid ID of the file.

## Version Info
  - Directus version and branch: 6.3.8
  - PHP version: 7.1
  - MySQL version: MariaDB 10.1
  - Web server: Apache
  - OS name and version: 

## Expected Behavior
API shall return the files

## Actual Behavior
`api/1.1/files`
returns the folowiing:
```
{
  "meta": {
    "table": "directus_files",
    "type": "collection",
    "total": 0,
    "Active": 9,
    "Delete": 0,
    "Draft": 0,
    "total_entries": 9
  },
  "data": []
}
```

`api/1.1/tables/test/rows` returns:

```
{
  "meta": {
    "table": "test",
    "type": "collection",
    "total": 1,
    "Draft": 1,
    "Delete": 0,
    "Active": 0,
    "total_entries": 1
  },
  "data": [
    {
      "id": 2,
      "active": 2,
      "image": null,
      "name": "aaa"
    }
  ]
}
```

**Comment by PaulPoot** [comment]
Any updates on this issue? I've got the same problem with a similar setup to OP's, only difference being the database version.

**Comment by MarcinKuder** [comment]
I've moved to another hosting provider and no issues there. Must have been some configuration problem but I haven't figured out what exactly.

**Comment by PaulPoot** [comment]
Thanks for your reply. I've found out what caused the issue on my side.

I was trying to get the data using the token of a user that belongs to a custom permission group. For files to be returned, you need to check the permissions of the Directus tables. They were all disabled for me, and enabling the files table did the trick.

Perhaps an exception to this rule could be made for files linked to a table that does have the right permissions in a future release? I don't plan on storing any files that I wouldn't want to be public through Directus, but it'd be great to have the option.

**Comment by WellingGuzman** [comment]
Sorry for the late response, after you all solved the problem, but glad that's all resolved.

> Perhaps an exception to this rule could be made for files linked to a table that does have the right permissions in a future release? I don't plan on storing any files that I wouldn't want to be public through Directus, but it'd be great to have the option.

This is something that would need discussion, we would include private files in a future release, but about permission for specific record, that's something that need to be figured it out first, if you have any suggestion how this may work, please let us know.

I'm closing this ticket as it has been resolved, if this issue is experienced again please let us know or open a new ticket.
