### ISSUE TITLE
Webhooks - Duplicate Request

### ISSUE THREAD

**Issue by sebastiansmithomm** [directus/directus#13933]
### Describe the Bug

Webhooks are triggered twice in quick succession. This only applies to 9.12.1 and later.
[Discussion](https://github.com/directus/directus/discussions/13925)

### To Reproduce

1. Spin up a new instance of directus docker with latest build. 
2.  Create a basic collection. 
3. Create a new webhook with 'create' trigger linked the collection (POST)
4. Edit and Save webhook as GET.
5. Webhook is triggered twice for each update. 

Video Recording: 
https://user-images.githubusercontent.com/74179584/174064074-744de78f-d332-4cd3-a8d5-ce18d454ddd3.mp4

Requests in Fiddler: 
![174024390-5b0c408e-fff2-40c4-a58e-74e9086c769c](https://user-images.githubusercontent.com/74179584/174055677-c5795a16-cb6c-48df-953e-aba88de18d12.png)

Webhook Setup:
![174024637-98baf9e5-62a6-44e4-84d3-9f268a71e379](https://user-images.githubusercontent.com/74179584/174055713-7f5f04e9-a4c0-4091-8c4c-ba49aed4beb9.png)

Request Comparison:
![174026406-01669599-00cb-4f27-b519-693e31bae92e](https://user-images.githubusercontent.com/74179584/174055750-d5563a35-de4c-431f-ae18-2f4f27484240.png)

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16.15.0

### What database are you using?

SQlLite

### What browser are you using?

Chroe

### How are you deploying Directus?

Docker

**Comment by Jeyakumarrathnaselvi** [comment]
Facing this today. It created big issue to my system post updating to new version

**Comment by Jeyakumarrathnaselvi** [comment]
Can someone know the issue root cause. it happens from second call of each webhook call after server restart

**Comment by FlatMapIO** [comment]
I have the same problem.

**Comment by martijn-dev** [comment]
I'm experiencing the same behaviour. It only occurs when you modify your webhook configuration. After this it starts sending the webhooks twice. A restart of the directus instance solves the issue.

**Comment by dkamali-mc** [comment]
I have noticed that in Flows/webhooks as well, I thought I was doing something wrong

**Comment by mystix** [comment]
> 

I can confirm the same thing -- Creating a **Flow** which sends `{{$trigger}}` data to a **Webhook / Request URL** works correctly (i.e. fires just once per update):
<img width="673" alt="CleanShot 2022-06-28 at 20 49 12@2x" src="https://user-images.githubusercontent.com/174070/176183546-29ea4b82-3868-41db-bf6f-5c421f841732.png">
<img width="833" alt="CleanShot 2022-06-28 at 20 55 30@2x" src="https://user-images.githubusercontent.com/174070/176183727-d0bb6bf4-c5db-466c-a772-09469415bf01.png">


but a similarly-configured **Webhook** which sends event data to the same URL fires twice per update:

<img width="818" alt="CleanShot 2022-06-28 at 20 53 36@2x" src="https://user-images.githubusercontent.com/174070/176183577-897a795a-f8fc-4c74-b046-214b5a20650e.png">
