### ISSUE TITLE
Geometry datas aren't fetched after Mapbox's search transition

### ISSUE THREAD

**Issue by izoukhai** [directus/directus#13941]
### Describe the Bug

When using Mapbox's search feature, the app doesn't refetch geometry datas inside current view (see video below)
It's not a big deal but maybe worth the investigation
![Enregistrement_de_lecran_2022-06-16_a_16 44 54](https://user-images.githubusercontent.com/44984965/174137476-d111851e-99b4-4e69-b561-56f7d22b96e0.gif)

### To Reproduce

1. Search for a location
2. Wait for the map to center at given location
3. For geometry datas to be shown, you have to manually move the map

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16.13.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by amandesai01** [comment]
I would like to take this up. Will just need a few pointers since I am new.
