### ISSUE TITLE
Slug : Unique ? 

### ISSUE THREAD

**Issue by mpiontek** [directus/directus#1395]
Hey Guys,

i read about directus a few days ago on t3n.de

For a new project i like to give it a try :) seems to be very flexible, but the incomplete docs make it difficult for me to understand everything. So please bear this in mind, if my questions are a little bit foolish :)

The Slug field doesn't seem to check for unique values. I read about this problem and there was a link to a solution (? https://github.com/directus/directus/commit/2bac1328ced4c243da72c6f2c74d08d2959ee9b8)

But i just installed the current version i think and there is nothing to solve my problem.

Do you have any advice?

By the way: Is there more documentation than this: https://docs.getdirectus.com ? Maybe a discussion board or something like that? I do not fully understand every field type and how i use them.

Best regards
Martin

**Comment by benhaynes** [comment]
Hey @mpiontek – our interface lead (@rijkvanzanten) said he likes this idea, and plans to add it into the new Slug interface for version `6.4`. The beta for that is coming tomorrow, but the new interface option may take a little bit longer as we cleanup the new release.

As for Docs, we've been trying to keep adding more and more info, but are a small team and have been busy with this new release the past few months. If you don't see it in our Docs or API Docs then we probably don't have anything yet. If you open tickets for missing info on the Docs repo then we'll get that taken care of!

https://github.com/directus/docs
https://github.com/directus/api-docs

**Comment by mpiontek** [comment]
When it comes to me, the ultimative thing would be, if it checks, that the slug is unique over all the different tables (maybe optional?) and adds something, if not. So i could for example root all my 'blogposts' and 'special offers' to mydomain.com/slug . Thinking of SEO it's a better way than mydomain.com/blog/slug, mydomain.com/specialoffer/slug i think - or isn't it?

**Comment by mpiontek** [comment]
Where do i find the new version? And is there a version number in my backend anywhere?

**Comment by WellingGuzman** [comment]
Hey @mpiontek, that could be beyond what we want to accomplish, and this scenario seems to be more specified to your needs, so in your case, you can add a hook to verify that in the API.

Either way, this should be accomplished with a customized solution.

here are the releases: https://github.com/directus/directus/releases

**Comment by mpiontek** [comment]
Thank you for your advise.

There is a problem in the documentation:
https://docs.getdirectus.com/6.3.6/#Versions_&_Updating

There is said "Run the migration script to update your database/schema" - then there is a link to a instruction how to do this. But this link is not working :(

**Comment by WellingGuzman** [comment]
Hey @mpiontek,

Thanks for pointing it out, in the mean time here the actual link: https://docs.getdirectus.com/6.3.6/#Database_Module


Source here: https://github.com/directus/docs/blob/master/developer-guide/cli.md#database-module

**Comment by mpiontek** [comment]
Ok. I am sorry for my questions, but sometimes i am a little bit insecure.
The documentation also does not say, if i just have to replace the existing folders and files OR if i have to upload all the files (including install directory, test directory, etc.). I swear that this is my last question for today :D

**Comment by WellingGuzman** [comment]
Hey @mpiontek, ask as many as you want, If you want to discuss and ask and talk remember you can join us in our slack (https://slack.getdirectus.com)

Back to your question, if you are upgrading the database, you only have to backup your database. About upgrading the files, we recommend `git` as it do the job for you, but if you are not using `git` you can replace all the files, except this:

- `customs` all the customs API endpoints, extensions and interfaces.
- `storage/uploads` all your uploads files.
- `api/config.php` and `api/configuration.php`
- run composer install, preferably due to cache, remove the `composer.lock` and `/vendor` directory and run `composer install`

It sounds difficult, that's why is better to use `git`.

Remember, try not to remove all the files you created yourself, and you should be in a good place.

**Comment by WellingGuzman** [comment]
We solve the uniqueness that we want to implement, but having a global implementation of slug is not something we want to pursuit now, and the user can implement their own global validation using hooks, not so pretty, but it will do the trick.

If this is something that somehow can be really useful, we will hear what you all have to say.

Closing it!
