### ISSUE TITLE
Auto-Update Date

### ISSUE THREAD

**Issue by mpiontek** [directus/directus#1396]
Hey Guys - it would be great to make a datetime field "read only" plus give it the ability to update on every save of the row. This would be very helpful for example for "last modification".

I think best way for me to do this now would be by creating a hook, am i right?

Best regards
Martin

**Comment by benhaynes** [comment]
Hey @mpiontek – sorry about the late reply! We're actually releasing this feature in the next version of Directus (`6.4`) which will be in beta tomorrow! It is an accountability option under Settings that lets you choose columns for `date_created`, `user_created`, `date_modified`, and `user_modified`. We'll continue to optimize this functionality – but it's a big step forward!

Thank you for posting this request!
