### ISSUE TITLE
An error was thrown while executing action collection.items.create

### ISSUE THREAD

**Issue by vahidreza** [directus/directus#13973]
### Describe the Bug

im using the new flow designer

**this is how my flow looks like:**
<img width="1043" alt="Screen Shot 2022-06-18 at 14 05 22" src="https://user-images.githubusercontent.com/3737551/174431877-bf2f34f4-b88f-4503-bfd6-d6fea8e06575.png">

**the flow setting is as below:**
<img width="846" alt="Screen Shot 2022-06-18 at 14 06 20" src="https://user-images.githubusercontent.com/3737551/174431907-2b81b69d-8fcf-445a-b737-2d7feac3867f.png">

**the condition:**
<img width="842" alt="Screen Shot 2022-06-18 at 14 07 08" src="https://user-images.githubusercontent.com/3737551/174431939-ccc9a863-7914-451a-ab99-fd54324dbb82.png">

**and the final log operation** 
<img width="828" alt="Screen Shot 2022-06-18 at 14 07 50" src="https://user-images.githubusercontent.com/3737551/174431983-afdf883f-dbd1-41f5-a09e-3fcbb395b6df.png">

after saving when i add a record to the collection instead of having the log when the type is not set to 'father' as described in the condition i get below error in the server logs and the expected flow log wont appear in log area of the flow object:

```
09:29:13 ⚠️  Transaction query already complete, run with DEBUG=knex:tx for more info,
09:29:13 ⚠️  An error was thrown while executing action "bhn_crm_contacts_bhn_crm_contacts_3.items.create",
09:29:13 ✨ the relation is not a father type: {"payload":{"related_bhn_crm_contacts_id":{"name":"sister 3","last_name":"patient"},"relationship_class":"family","relationship_type":"sister","bhn_crm_contacts_id":"27f181e1-0d96-41db-821b-fac50dc2831d"},"key":14,"collection":"bhn_crm_contacts_bhn_crm_contacts_3"}
```

### To Reproduce

depicted above

### Errors Shown

```
09:29:13 ⚠️  Transaction query already complete, run with DEBUG=knex:tx for more info,
09:29:13 ⚠️  An error was thrown while executing action "bhn_crm_contacts_bhn_crm_contacts_3.items.create",
09:29:13 ✨ the relation is not a father type: {"payload":{"related_bhn_crm_contacts_id":{"name":"sister 3","last_name":"patient"},"relationship_class":"family","relationship_type":"sister","bhn_crm_contacts_id":"27f181e1-0d96-41db-821b-fac50dc2831d"},"key":14,"collection":"bhn_crm_contacts_bhn_crm_contacts_3"}
```

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16.15.1

### What database are you using?

mysql

### What browser are you using?

chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Closing in favor of tracking this in #13747.
