### ISSUE TITLE
When sending a notification, create record first then email, else no notification record is created if email sending fails

### ISSUE THREAD

**Issue by sxsws** [directus/directus#13974]
### Describe the Bug

Currently, if sending the email notification fails, no notification record is created. The record should be created first in case email sending fails for whatever reason.

Maybe if it does fail, that could be another notification record to the admin with a high alert level?

### To Reproduce

As above.

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

12.22.5

### What database are you using?

mariadb

### What browser are you using?

firefox

### How are you deploying Directus?

local

**Comment by spawnrider** [comment]
Same issue on a notification flow, when you are trying to notify a user without having set the sendmail before.
The flow result payload is empty "{}" and no user notification is sent... 

I think that the internal notification mechanism must work without relaying on the sendmail feature which can be disabled by default.

**Comment by sxsws** [comment]
So I jumped in to make the necessary changes for this thinking it'd only be changing a few lines around... but I was wrong! 

The `createOne` / `createMany` in `api/src/services/notifications.ts` awaits the sending of the email then returns lhe `super.createOne/createMany` which creates the record. So, I suggest that the await is wrapped in a try/catch with the catch writing to the console / log, and then returning as normal. Good plan?

**Comment by sxsws** [comment]
Thanks for not answering my question but taking my solution and code and making a pr from it!
