### ISSUE TITLE
Shared link shows only the relational fields and the dropdowns, not the inputs

### ISSUE THREAD

**Issue by Pachat** [directus/directus#13971]
### Describe the Bug

With a shared link created in a collection (with no pass word), when out of Directus, I only see the relational fields and the dropdowns.
All other inputs, textareas are blank. The role attached to the link has Read set to All access
I thought that the shared link would allow anyone, even not registered.

### To Reproduce

1. Create a shared link on a collection's details (in my case with inputs and dropdowns or M2M. Maybe not necessary to raise the bug) and copy it. The role attached to the link has Read set to All access.
2. Disconnect
3. Fetch the link

### Errors Shown

You only see the relational fields and the dropdowns.
All other inputs, textareas are blank

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

v16.14.0

### What database are you using?

PostgreSQL

### What browser are you using?

Firefox

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
Closing this for now. We'll reopen once more information becomes available 🙂
