### ISSUE TITLE
WYSIWYG field in Directus Cloud does not display, 

### ISSUE THREAD

**Issue by marcpope** [directus/directus#13975]
### Describe the Bug

Images don't display in a WYSIWYG text field.

### To Reproduce

Created a new Community Instance on Directus Cloud, created a simple Post collection with a text field that had WYSIWYG field definition.

Added an image, image does not display. 

### Errors Shown

`{
"errors": [
{
"message": "You don't have permission to access this.",
"extensions": {
"code": "FORBIDDEN"
}
}
]
}`

### What version of Directus are you using?

Community Cloud

### What version of Node.js are you using?

16.15.1

### What database are you using?

Internal to Directus Cloud

### What browser are you using?

Chrome

### How are you deploying Directus?

Cloud

**Comment by azrikahar** [comment]
Presumably the asset URL generating the forbidden error doesn't have a token in it (there should be an `access_token` query parameter), a static token will need to be provided for it to work, as described by this comment to a same question here: https://github.com/directus/directus/issues/10469#issuecomment-1054992007 👍 

The static token configuration for the WYSIWYG field can be found when configuring the field -> Interface tab:

![chrome_UqswQWoOkB](https://user-images.githubusercontent.com/42867097/174527150-33af561c-d29b-4be3-b63a-85b2a6f4f643.png)
