### ISSUE TITLE
M2M Interface settings ignored if the field is hidden by default

### ISSUE THREAD

**Issue by whis** [directus/directus#13986]
### Describe the Bug

The M2M interface options `Enable Create Button` and `Enable Select Button` seem to be ignored if the field is hidden by default and set to visible by a condition.

### To Reproduce

1. Create a new M2M field and configure:
    - Field > Hidden > Check the `Hidden on Detail`
    - Interface > Uncheck `Enable Create Button` and `Enable Select Button`
    - Conditions > Rule > Create a rule `ID Isn't null` (or any other that will be true) and uncheck the `Hidden on Detail`
2. Save the field.
3. Edit an item with the M2M field defined above, you will see both `Create New` and `Add Existing` buttons visible.

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16.15.0

### What database are you using?

Postgres 14

### What browser are you using?

Edge

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
> Conditions > Rule > Create a rule ID `Isn't null` (or any other that will be true) and uncheck the `Hidden on Detail`

I believe during this step, you will need to scroll down (in case it's not visible) and make sure to _uncheck_ `Enable Create Button` and `Enable Select Button` as well 👍 Here's an example from my local test which does work after doing that:

https://user-images.githubusercontent.com/42867097/174542073-642b07e8-fb8c-4e81-ad4d-f812e234d295.mp4

**Comment by whis** [comment]
Ah, that makes sense. I was assuming it will inherit from the default settings and totally overlooked it has its own interface options without the "default" state.
