### ISSUE TITLE
Uncomented text in .env after new installation

### ISSUE THREAD

**Issue by rowild** [directus/directus#14004]
### Describe the Bug

After installation, the .env file has some uncommented text on liner 262:

![Bildschirmfoto 2022-06-20 um 17 41 17](https://user-images.githubusercontent.com/213803/174637511-7442d918-ac05-4f95-8f45-dc4ff62a9601.png)

(This has probably no influence whatsoever, but for the sake of completeness it shall be mentioned here.)

### To Reproduce

- Install directus any way you like
- Inspect the .env file afterwards

### Errors Shown

None

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16.14.2

### What database are you using?

SQLite 3.28.0

### What browser are you using?

Chrome

### How are you deploying Directus?

locally, Docker

**Comment by rijkvanzanten** [comment]
Simple bug, simple fix:

https://github.com/directus/directus/blob/ed64c35af2dbb2638fb82fc708727dcd2537c506/api/src/cli/utils/create-env/env-stub.liquid#L253

**Comment by rowild** [comment]
@rijkvanzanten Thank you!
