### ISSUE TITLE
GraphQL: Non-nullable lists

### ISSUE THREAD

**Issue by reiv** [directus/directus#14007]
### Describe the Bug

It appears that all lists in Directus' GraphQL schema are marked as nullable (both the list as well as the containing entity).

For instance, a collection named "example" exposes the following query:

![image](https://user-images.githubusercontent.com/205631/174652377-fe47fe81-d632-4e49-b44f-e975d61ff7df.png)

Ideally the result would be marked as non-nullable like so: `[example!]!`

Is there actually a scenario where the list might be `null` or might contain `null`s? For context, the absence of non-nullable `!`s makes the output of `graphql-codegen` in a strictly typed TypeScript codebase rather awkward to work with.

### To Reproduce

- Create a collection
- Add read permission for public
- Inspect the resulting GraphQL schema

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16.13.0

### What database are you using?

Postgres 14.3

### What browser are you using?

Firefox

### How are you deploying Directus?

Running locally

**Comment by reiv** [comment]
I think you misunderstand; I am not talking about a field, but the top-level collection.

**Comment by rijkvanzanten** [comment]
Ah gotcha, thought `example` here was a field _in_ a collection. My b
