### ISSUE TITLE
Input placeholder color hard to read / inconsistent across browsers

### ISSUE THREAD

**Issue by laurens94** [directus/directus#14025]
### Describe the Bug

When using the dark theme, the input placeholders are difficult to read in Firefox (on MacOS). On Chrome it's better.

**Firefox:**
![image](https://user-images.githubusercontent.com/5780704/174812331-07cd7e45-aa74-49d2-9b93-e72deeffb84e.png)

**Chrome:**
![image](https://user-images.githubusercontent.com/5780704/174812356-02331e92-4848-428b-a04c-a4557dc769a9.png)

### To Reproduce

1. Use the dark theme
2. Go to Settings
3. Check the empty inputfields with placeholders
4. See the difference between Chrome and Firefox

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16.15.1

### What database are you using?

default sqlite3

### What browser are you using?

Chrome and Firefox

### How are you deploying Directus?

Docker / Kubernetes

**Comment by benhaynes** [comment]
That's odd — I wonder how the contrast could change across browers. If you look in the CSS hex colors, are they the same across browsers? Is it just how they paint/render it?

**Comment by laurens94** [comment]
It seems [Firefox changes the opacity of placeholders by default](https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder#opaque_text). 
Adding the following css fixes this:

```css
::placeholder {
  opacity: 1;
}
```
