### ISSUE TITLE
Missing collections when using an existing database

### ISSUE THREAD

**Issue by leonardodipace** [directus/directus#14032]
### Describe the Bug

When adding Directus to an existing database, no collections are detected.

### To Reproduce

1. Create a new database
2. Import schema and data from https://github.com/datacharmer/test_db/releases/tag/v1.0.7
3. Create a new Directus project and link it to the database you just created
4. Run Directus

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16.14.2

### What database are you using?

MariaDB 10.7.3

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally

**Comment by rijkvanzanten** [comment]
@leonardodipace It seems to work as expected on my end.

Using [the `docker-compose` file](https://github.com/directus/directus/blob/817a6c18911eaac34eb68603028822e65d6c6626/docker-compose.yml) in the root:

```
mysql --host=127.0.0.1  --port=5102 --database=test_db --user=root --password=secret < ./test_db/employees.sql

directus bootstrap
directus start
```

I get a warning about some collections with missing / invalid primary keys:

```
09:41:25 ⚠️  Collection "salaries" doesn't have a primary key column and will be ignored
09:41:25 ⚠️  Collection "titles" doesn't have a primary key column and will be ignored
09:41:25 ⚠️  Collection "dept_emp" doesn't have a primary key column and will be ignored
09:41:25 ⚠️  Collection "dept_manager" doesn't have a primary key column and will be ignored
```

but other than that, collections seem to show up as expected under Data Model:

<img width="955" alt="CleanShot 2022-06-22 at 09 46 08@2x" src="https://user-images.githubusercontent.com/9141017/175044666-87a2a34c-5939-48e0-a96b-450b2d51ca5a.png">

And enabling them there also surfaces them in the app as expected:

![CleanShot 2022-06-22 at 09 46 40@2x](https://user-images.githubusercontent.com/9141017/175044843-8359f76a-9974-464c-b8ac-05d774dd5f07.png)
