### ISSUE TITLE
Hide "Create" in Many to One interface

### ISSUE THREAD

**Issue by Stathis90** [directus/directus#14061]
### Describe the Bug

In M2O interface it should be an option to disable the create button like in the other relationship interfaces.

![image](https://user-images.githubusercontent.com/15157178/175296900-8b6c2c58-1f88-498d-9b52-de9ec14b6796.png)

![image](https://user-images.githubusercontent.com/15157178/175296531-a918b3ed-eb2b-48e0-b467-e2d7b60fd90a.png)

### To Reproduce

1. Create a M2O relation field
2. Go to Interface tab

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

-

### What database are you using?

MSSQL

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Assuming OP meant the "plus" icon as depicted in the comment here: https://github.com/directus/directus/discussions/11903#discussioncomment-2274581, then I believe this is more so a feature request than a bug. Let's consolidate this over in #11903 👍

We'll reopen this is meant as something else and is an actual bug.

**Comment by Stathis90** [comment]
> Assuming OP meant the "plus" icon as depicted in the comment here: [#11903 (comment)](https://github.com/directus/directus/discussions/11903#discussioncomment-2274581), then I believe this is more so a feature request than a bug. Let's consolidate this over in #11903 👍
> 
> We'll reopen if this is meant as something else and is an actual bug.

This is what I meant... My first thought was to open it as a feature request but since all other relation interfaces provide this option I decided to open it as a bug.
