### ISSUE TITLE
Sending Shared link is not working properly under Firefox

### ISSUE THREAD

**Issue by Pachat** [directus/directus#14072]
### Describe the Bug

1.  `Copy link` is not working (the clipboard stays unchanged) <= _This is a bug_
2. The mail sent is strangely composed <= _This needs very necessary improvements_ 
- The subject is 
> user@domain.com has shared an item with you
 => which is very imprecise: how identify that is comes from the App?
- The body is 
> Hello!
[user@mydomain.com](mailto:user@mydomain.com) has invited you to view an item in test.
[/admin/shared/32021047-4228-4034-9130-802955071873]Open
=> Only the mail address is clickable.
=> The app address is incomplete and not clickable
=> Reply to the mail shows the repky address as: `MyDomain <no-reply@directus.io>` 

This is confusing:

1. The no-reply should refer @mydomain.com
2. The mail address should not be clickable as we prefer the recipient to connect to the app
3. The link to the app should be operational

Finally, is it possible to translate the message?

### To Reproduce

1. On a detail, create a shared link
2. Copy the link
3. Send the link

### Errors Shown

2. The clipboard does not contain the link
3. The mail is sent, but with the defaults mentioned above

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

12.22.9

### What database are you using?

PostgreSQL

### What browser are you using?

Firefox

### How are you deploying Directus?

VPS

**Comment by br41nslug** [comment]
Always pains me to answer with a "it's working on my machine" tested with Firefox on Windows on 3 machines.
There are quite a few things/apps that can influence the clipboard functionality from browser plugins (especially password managers) to screenshot helpers like greenshot/loom. 
What OS are you using? (i remember having a terrible time getting the clipboard working for linux os desktops)
Do you have any of the apps/plugins i described that could interfere with the clipboard functionality?

**Comment by Pachat** [comment]
Thank you for your answer.
So, I'll have to do some more tests deactivating maybe some plugins.
This will be done when I go back to my office on Tuesday.
The OS is W10.

**Comment by Pachat** [comment]
I'm sorry to confirm the bug under Firefox. (I adapted the title for it works nice under Edge)

Directus 9.12.2

Firefox configuration: `Firefox	101.0.1 (64-bit)` (All plugins disabled and Firefox restarted)

Windows 10 configuration:
```
Windows 10 Family
Version	21H1
Build 	19043.1766
Windows Feature Experience Pack 120.2212.4180.0
```

**Comment by rijkvanzanten** [comment]
Spoke too soon with that label change. I just tried this under Firefox 103 on macOS Big Sur, and can similarly not reproduce this 🤔 

Clicking "Copy Link" correctly copies `http://localhost:8080/admin/shared/27608088-f6af-4f32-a372-63e2206e92e0` to my clipboard. Do you have any other clipboard managers that might cause issues? Do other "Copy" buttons in the app / on the internet work as expected?

**Comment by rijkvanzanten** [comment]
Closing this for now, as we haven't been able to reproduce this. Happy to keep discussing, and we'll reopen once more information becomes available 🙂

**Comment by Pachat** [comment]
It works fine...when working locally as your test shows.

But it still does not work on a server installation, neither under Edger nor Firefox.

**Comment by rijkvanzanten** [comment]
Might be a difference dev vs prod builds 🤔

**Comment by rijkvanzanten** [comment]
Linear: [ENG-242](https://linear.app/directus/issue/ENG-242/sending-shared-link-is-not-working-properly-under-firefox)

**Comment by rijkvanzanten** [comment]
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻
