### ISSUE TITLE
Many Files

### ISSUE THREAD

**Issue by podlebar** [directus/directus#1410]
Hi..

somehow i'm struggling with adding a Multiple Files field..
i got it that i have to add a junction table.. so i added a table called relationship with id, active, id_a,id_b fields.

than i configured the multiple files field to use this table.
but when i add multiple images to that field i get this error:
`Error: Uncaught SyntaxError: Unexpected end of JSON input
File: https://cms.******.com/tables/test/8
 Line:1`

am i missing a step? do i ned to create that relations table in mysql not directus?

field config:
<img width="561" alt="bildschirmfoto 2017-04-19 um 17 37 18" src="https://cloud.githubusercontent.com/assets/342104/25188747/5eb27aee-2527-11e7-97fc-24f10fc033a0.png">

relations table:
<img width="945" alt="bildschirmfoto 2017-04-19 um 17 38 00" src="https://cloud.githubusercontent.com/assets/342104/25188765/74782f54-2527-11e7-976c-a56872dcd786.png">

**Comment by WellingGuzman** [comment]
Hey @podlebar, can you share the stack trace of that error? or is that the whole error? The relationship seems to be correctly set.

**Comment by podlebar** [comment]
@WellingGuzman 
sorry.. i just found the logs folder..
there was a permission error... sorry for that.

but one question? i need to create a relations table for each multiple files input.. correct? even when i use two multiple files fields in one table.

btw.. here https://docs.getdirectus.com/6.3.6/#Versions_&_Updating the "Read how to" link points to a 404 site.

**Comment by WellingGuzman** [comment]
Glad that you found the solutions,

Yes, each should have their own relations table, as they will be the same entries if you are using the same relations (junction) table.

> btw.. here https://docs.getdirectus.com/6.3.6/#Versions_&_Updating the "Read how to" link points to a 404 site.

Thanks for pointing it out.
