### ISSUE TITLE
can not update field to not null if it's  has fk.

### ISSUE THREAD

**Issue by imiskolee** [directus/directus#14105]
### Describe the Bug

showing error `alter table `relationA` modify `b_id` int not null - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'b_id' and referenced column 'id' in foreign key constraint 'relationa_b_id_foreign' are incompatible.` if update field from null to not null.

directus version: 9.12.1
MySQL version: 8.0.21

## 1. create two temp table
```sql
 CREATE TABLE `relationA` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) DEFAULT NULL,
  `b_id` int unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `relationa_b_id_foreign` (`b_id`),
  CONSTRAINT `relationa_b_id_foreign` FOREIGN KEY (`b_id`) REFERENCES `relationB` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `relationB` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
```

## 2. update relationA.b_id from null to not null.

server error log :

```
alter table `relationA` modify `b_id` int not null - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'b_id' and referenced column 'id' in foreign key constraint 'relationa_b_id_foreign' are incompatible. 
Error: UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'b_id' and referenced column 'id' in foreign key constraint 'relationa_b_id_foreign' are incompatible.
```

the alter table also try to change b_id from `int unsigned` to `int`, it's the major issue. 
When I manually run SQL ``alter table `relationA` modify `b_id` int unsigned not null``, it's  work.

### Errors Shown

alter table `relationA` modify `b_id` int not null - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'b_id' and referenced column 'id' in foreign key constraint 'relationa_b_id_foreign' are incompatible.

### What version of Directus are you using?

9.12.1

### What version of Node.js are you using?

16.14.0

### What database are you using?

MySQL 8.0.21

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally

**Comment by imiskolee** [comment]
# Reproduce Step

1. Create a collection A(auto-increment id)
2. Create a collection B(auto-increment id)
3. Create a many-to-one field called `b_id` on collection A and related to collection B
4. update field `b_id` to allow null or not allow null.

**Comment by azrikahar** [comment]
> # Reproduce Step
> 1. Create a collection A(auto-increment id)
> 2. Create a collection B(auto-increment id)
> 3. Create a many-to-one field called `b_id` on collection A and related to collection B
> 4. update field `b_id` to allow null or not allow null.

Thanks for the updated reproduction steps!

There has been numerous reports on the "incompatible" error, and I was wondering how this steps which seems similar to #7808 is producing a different error. Specifically, after doing these 4 steps, the error shown should be `ER_FK_COLUMN_NOT_NULL`:

![chrome_xIuX7TxtFz](https://user-images.githubusercontent.com/42867097/175851546-9f2e6f13-3196-4d0f-8465-021874342858.png)

However once I restarted the Directus instance and repeat step 4, I'll get the "incompatible" error going forward now:

![chrome_vgwDEBaV2O](https://user-images.githubusercontent.com/42867097/175851734-d8176124-3882-4e2c-a7c5-b6ca988467c3.png)

also very nice catch on the `int unsigned` to `int` point! That seems like a potential huge clue for the issue resolution here.

With that said, this issue should be the same as #7808 so I'll proceed to close this in favor of tracking it over there 👍

**Comment by imiskolee** [comment]
@azrikahar  same issue on uuid many to one, but string field is work, and I researched the SQL,  uuid is varchar(36), string is varchar(255).

Create a collection A(uuid)
Create a collection B(uuid)
Create a many-to-one field called b_id on collection A and related to collection B
update field b_id to allow null or not allow null.

**Comment by azrikahar** [comment]
Thanks again for the additional investigation. I now believe that should be what is actually happening to #10932.
