### ISSUE TITLE
Empty translation fields on main display

### ISSUE THREAD

**Issue by RobinFrcd** [directus/directus#14125]
### Describe the Bug

Translations are not showing any more on the table main display

![image](https://user-images.githubusercontent.com/29704178/175896684-5cb320cc-3493-4507-bdef-7d3a2646f0b6.png)

But if I click on an item, it shows up correctly

![image](https://user-images.githubusercontent.com/29704178/175896805-7e3ddcae-12da-4ed7-869b-7eafdd1813a1.png)

### To Reproduce

Migrate from **9.12.0 to 9.12.2**, try to display already existing tables with translated fields.

### Errors Shown

```
TypeError: e.value.find is not a function
    d /admin/assets/index.133de9ba.entry.js:2814
    run /admin/assets/runtime-core.esm-bundler.b1f35d24.js:1
    get /admin/assets/runtime-core.esm-bundler.b1f35d24.js:1
    Yl /admin/assets/runtime-core.esm-bundler.b1f35d24.js:1
    get /admin/assets/runtime-core.esm-bundler.b1f35d24.js:1
    get /admin/assets/runtime-core.esm-bundler.b1f35d24.js:4
    wze /admin/assets/index.133de9ba.entry.js:2814
    Zt /admin/assets/runtime-core.esm-bundler.b1f35d24.js:4
    T /admin/assets/runtime-core.esm-bundler.b1f35d24.js:4
[runtime-core.esm-bundler.b1f35d24.js:4:1158](/admin/assets/runtime-core.esm-bundler.b1f35d24.js)
```

​

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

The one the the docker image tag 9.12.2

### What database are you using?

Postgres 14.2

### What browser are you using?

Firefox

### How are you deploying Directus?

ECS (Docker)

**Comment by br41nslug** [comment]
Duplicate, the translation interface should also be fixed with the m2m relation fix of #13866 in the next release
