### ISSUE TITLE
Filters (hooks) not working in configuration.php

### ISSUE THREAD

**Issue by justkidding96** [directus/directus#1418]
## Version Info
  - Directus version and branch: 6.3.9
  - PHP version: 7.1.1
  - MySQL version: 5.6.35
  - Web server: Apache
  - OS name and version: Mac OSX El Captian

## Expected Behavior
The before hook/filter is triggered and custom data is added to the data array.

## Actual Behavior
The before hook/filter is not triggered at all. Also the documentation about this is not correct.
**$data['secret_key'] => rand();** is not correct PHP code and throws an 500 error.

## Sample of configuration.php

```php
<?php

/**
 * High priority use case, not super planned out yet.
 * This will be useful in the future as we do a better job organizing our application configuration.
 * We need to distinguish between configuration and application constants.
 */

// Autoload our app
include __DIR__ . '/../../vendor/autoload.php';

return [
    'session' => [
        'prefix' => 'directus6_'
    ],

    'default_language' => 'en',

    'filesystem' => [
        'adapter' => 'local',
        // By default media directory are located at the same level of directus root
        // To make them a level up outsite the root directory
        // use this instead
        // Ex: 'root' => realpath(BASE_PATH.'/../storage/uploads'),
        // Note: BASE_PATH constant doesn't end with trailing slash
        'root' => BASE_PATH . '/storage/uploads',
        // This is the url where all the media will be pointing to
        // here all assets will be (yourdomain)/storage/uploads
        // same with thumbnails (yourdomain)/storage/uploads/thumbs
        'root_url' => '/storage/uploads',
        'root_thumb_url' => '/storage/uploads/thumbs',
        //   'key'    => 's3-key',
        //   'secret' => 's3-key',
        //   'region' => 's3-region',
        //   'version' => 's3-version',
        //   'bucket' => 's3-bucket'
    ],

    'HTTP' => [
        'forceHttps' => false,
        'isHttpsFn' => function () {
            // Override this check for custom arrangements, e.g. SSL-termination @ load balancer
            return isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != 'off';
        }
    ],

    'mail' => [
        'transport' => 'mail',
        'from' => 'rklijnsmit@flaire.nl'
    ],

    'cors' => [
        'enabled' => false,
        'origin' => '*',
        'headers' => [
            ['Access-Control-Allow-Headers', 'Authorization, Content-Type, Access-Control-Allow-Origin'],
            ['Access-Control-Allow-Credentials', 'false']
        ]
    ],

    'hooks' => [
        'postInsert' => function ($TableGateway, $record, $db) {

        },
        'postUpdate' => function ($TableGateway, $record, $db) {
            $tableName = $TableGateway->getTable();
            switch ($tableName) {
                // ...
            }
        },
        'table.insert.orders:after' => '\App\Events\AfterInsert',
    ],
    // Not working
    'filters' => [
        'table.insert.orders:before' => function($data) {
            $data['uid'] = 'test';
            return $data;
        },
    ],

    'feedback' => [
        'token' => '2fa547b51baef1a8254820838ee5cd4b8c63677e',
        'login' => true
    ],

    // These tables will not be loaded in the directus schema
    'tableBlacklist' => [],

    'statusMapping' => [
        0 => [
            'name' => 'Delete',
            'color' => '#C1272D',
            'sort' => 3
        ],
        1 => [
            'name' => 'Active',
            'color' => '#5B5B5B',
            'sort' => 1
        ],
        2 => [
            'name' => 'Draft',
            'color' => '#BBBBBB',
            'sort' => 2
        ]
    ]
];
```

**Comment by WellingGuzman** [comment]
hey @justkidding96,

Are you creating and loading a new class named `\App\Events\AfterInsert`.

I know it's not clear in the documentation, but that means the class you should've created yourself and the namespace should be loaded by yourself.

**Comment by justkidding96** [comment]
@WellingGuzman The AfterInsert trigger is perfectly working!! I am talking about the filters array which is not working as expected. 

According to the docs: if u want to make adjustments **before** saving to the database u need to add this code to configuration.php
```php
[
    'filters' => [
        'table.insert.users:before' => function ($data) {
            $data['secret_key'] => rand(); // This is not correct PHP syntax btw
            return $data;
        }
    ];
];
```
But in my original issue I was mentioning that this is not working. Also the docs uses the wrong PHP syntax which is causing a 500 error, very confusing.

So reveal the code snippet below, I am trying to add an **uid** to the current data set and then save it to the database with this code.
```php
// This is not working
'filters' => [
    'table.insert.orders:before' => function($data) {
        $data['uid'] = 'test';
        return $data;
    },
],
```
I hope u understand now my issue and I am hoping for any solution.

Thanks!!

**Comment by peremp** [comment]
Looks like the problem is located at "api/core/Directus/Db/TableGateway/BaseTableGateway.php" file.

At line 253:
`253: $recordData = $this->applyHook('table.insert:before', [$tableName, $recordData]);`
`254: // @TODO: All hook payload are going to be an object to prevent confusion`
`255: // $recordData = $this->applyHook('table.insert.' . $tableName . '.:before', [$recordData]);`

If you comment the line 253 and uncomment the line 255 the filters will work... But I'm not sure if this will have other implications so lets wait for @WellingGuzman :-)

**Comment by WellingGuzman** [comment]
Hey @justkidding96,

I know what's the issue is, thanks to @peremp. The issue is around there, I was trying hard not to make this change, but it better sooner than later.

In the mean time what you can do is this:

```php
// This is not working
'filters' => [
    'table.insert:before' => function($table, $data) {
        if ($table === 'orders') {
            $data['uid'] = 'test';
        }
        return $data;
    },
],
```


This will be changed to something like this:

```php
'filters' => [
    'table.insert.orders:before' => function ($payload) {
        $payload->data['uid'] = 'test';
        return $payload;
    },
],
```

_Everyone would be warned about those not backward compatibility changes._

**Comment by WellingGuzman** [comment]
Hey, so I update the hooks behavior, instead of passing multiple parameters, it uses a `Payload` object which represents the data and has attributes such as the table name.

It ended up working this way: (_I'm still open to suggestion_)

```php
'filters' => [
    'table.insert.orders:before' => function($payload) {
        $payload['uid'] = 'test';
        return $payload;
    },
    'table.insert:before' => function($payload) {
        if ($payload->attribute('tableName') === 'orders') {
            $payload['uid'] = 'test';
        }
        return $payload;
    },
],
```

An object is pass around to make a little better when multiple filters are going to alter the data.

Let me know how it worked it out.

**Comment by justkidding96** [comment]
@WellingGuzman @benhaynes This issue is still a problem. When I wanted to use a class which implements the HookInterface class instead of your solution the data won't store anymore because it is not returning the correct instance.

**I think the best approach would be:**
The system looks for any active dynamic hooks classes inside the events folder inside the root directory. For example, below a example event class.
```php
<?php

namespace Directus\Events;

use Directus\Hooks\HookInterface

// Before|TableName|Action or After|TableName|Action.
// In this test class we use the before filter and we have a table called 'order'.
class BeforeOrderInsert implements HookInterface
{
    /**
     * Access the data before inserting
     *
     * @param  array $payload
     * @return array $payload
     */
    public function handle($payload = null)
    {
        // Do something with the code and return
        return $payload;
    }
}
```
When the systems detects any active filter/hooks it is executing it automatically.

**Comment by WellingGuzman** [comment]
hey @justkidding96,

Are you talking about the example not working, or when you use HookInterface is not working?

I didn't understood the problem, please can you try to elaborate it a bit more.

**Comment by WellingGuzman** [comment]
I re-read it again, did you mean you want the classes to auto load and enable?

**Comment by justkidding96** [comment]
@WellingGuzman I want to use classes inside the **configuration.php** and not a function kind of way. 

In your the first solution u was saying you are open for any suggestions. The example above is one of my suggestion. To look automatically for any active hooks.

**Comment by WellingGuzman** [comment]
Hey @justkidding96,

I'm so embarrassed, I don't know where was my head at that time while I was reading it, I see what you mean, that's a great idea though.

I will work on it next week, thanks for the suggestion is a really good one, and sorry for my misunderstood.

**Comment by WellingGuzman** [comment]
After long discussion and testing the suggestion of getting the name of a event from the class name is almost impossible, to not say impossible. If someone got an idea, it's welcome.

What we are going to implement now is autoloading classes in `customs/hooks` so it's easy to do this `'event-name' => '\Directus\Customs\Hooks\Class'` without autoloading the class yourselves.

We were also thinking on doing something like this

```php
<?php

namespace Directus\Customs\Hooks;

class NotifyUsers implements \Directus\Hook\HookInterface
{
    public function handle($table, $data)
    {
        // code to notify the user
    }

    public function onHook()
    {
        return 'table.insert.products:after'
    }
}
```

But this need to instantiate the class without knowing if we are actually using it, so Until we find a better way to do that, we still strongly believe in let the user specify the hooks and the class that would work with that.

So we are going to implement multiple classes that listen to one hook/event.

```php
return [
  'hooks' => [
    'table.insert.products:after' => [
      '\Directus\Customs\Hooks\NotifyUsers',
      '\Directus\Customs\Hooks\GeneratingThumbnails'
    ]
  ]
]
```
---

To play safe and avoid confusion, we are not opting for parsing the class name into hook name, as table can have uppercase or lowercase words, dashes, spaces even underscore, we would spend lots of time trying to squeeze a parser for that.
