### ISSUE TITLE
Fetching relational items via graphql is limited to 100 per table without being able to change it on the query

### ISSUE THREAD

**Issue by MiniDigger** [directus/directus#14190]
### Describe the Bug

We have a table that references two other tables (m2a).
When quering elements on that table, we can't get more than 100 elements out of the referenced tables. this limit is counted per table.

example query (table has > 2000 elements):
```graphql
query test{
    absatz_elemente(limit: 2000) {
        item {
            __typename
            ...on bildelement {
                __typename
                id
            }
            ...on textelement {
                __typename
                id
            }
        }
    }
}
```
yields a result like this:
```
{
  "data": {
    "absatz_elemente": [
      {
        "item": null
      },
      {
        "item": {
          "__typename": "textelement",
          "id": "6"
        }
      },
      {
        "item": {
          "__typename": "bildelement",
          "id": "6"
        }
```
where we get 100 items with type textelement, 100 items with type bildelement and 1800 items that are null (altho they have data in the db and that data is visible in directus too)

### To Reproduce

see above

### Errors Shown

none

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

16

### What database are you using?

PostgreSQL 12.11 

### What browser are you using?

-

### How are you deploying Directus?

docker

**Comment by MiniDigger** [comment]
note, this was found in prod which is still running 9.8.0, I incidentally just updated directus in dev so I was able to repro on 9.13.0 (I saw there were graphql changes in .13 and hoped they fixed this)

**Comment by rijkvanzanten** [comment]
Interesting! It's technically working as intended, as you're getting 2k items from the `absatz_elemente` collection of which it's only nesting stuff when the related field matches `bildelement` or `textelement`. You'll probably get the data you're looking for by adding a `filter` to the `absatz_elemente` query that only retrieves `absatz_elemente` with `filter: { collection: { _in: ["bildelement", "textelement"] }`. 

It's probably worth defaulting to that filter if union types are used in GraphQL 🙂

**Comment by rijkvanzanten** [comment]
Ahh gotcha, thanks for confirming that t

**Comment by rijkvanzanten** [comment]
Thanks GitHub https://twitter.com/LeaVerou/status/1542163898018717699

**Comment by naftalivanderloon** [comment]
I have the same issue, the limit param is ignored always uses the default of 100... 
this is a bug not an improvement

tested with v9.18.1
