### ISSUE TITLE
Feature request: Add dot-notation to access 'related' table fields

### ISSUE THREAD

**Issue by studiovlijmscherp** [directus/directus#1419]
As mentioned at the Slack channel:

> Does anybody know if it's possible to filter the dataset on 'related' table fields? In the attached JSON I would like to filter on the 'country' for example using something like: /api/1.1/tables/places/rows?in[country->data->code] = NL

@WellingGuzman [19 hours ago] 
hey @vlijmscherp, right now we do not support nested solution, please open a ticket so I do not forget this, and I will work into a solution for this one, using dots should be a good solution right? `filters[country.code][in]=NL`

**Comment by WellingGuzman** [comment]
We have implemented dot-notation for filtering and columns selection in https://github.com/directus/directus/commit/33986f876b70846fce8ba5a70c79cad2c29e9f45

**Comment by studiovlijmscherp** [comment]
Great! But... how do we use this? Pulled the Develop Branch and tried to filter using:
`/api/1.1/tables/places/rows?filters[city.code][eq]=ams`

`{
    "success": false,
    "error": {
        "message": "This query failed: SELECT `places`.`id` AS `id`, `places`.`active` AS `active`, `places`.`name` AS `name`, `places`.`main_image` AS `main_image`, `places`.`straat_and_number` AS `straat_and_number`, `places`.`zipcode` AS `zipcode`, `places`.`website_url` AS `website_url`, `places`.`e-mail_address` AS `e-mail_address`, `places`.`phone` AS `phone`, `places`.`omschrijving` AS `omschrijving`, `places`.`map` AS `map`, `places`.`slug` AS `slug`, `places`.`prijs` AS `prijs`, `places`.`outbound_link` AS `outbound_link` FROM `places` WHERE `places`.`city` IN (SELECT `cities`.`id` AS `id` FROM `cities` WHERE `cities`.`code` = 'ams') ORDER BY `places`.`id` ASC LIMIT 200 OFFSET 0"
    },
    "code": 0,
    "class": "RuntimeException",
    "file": "/Users/michielzoer/GIT_Projects/triptilt_api/api/core/Directus/Database/TableGateway/BaseTableGateway.php",
    "line": 704
}`

**Comment by WellingGuzman** [comment]
can you provide a schema @studiovlijmscherp? or what the relation of `city` and `code` to `places`? a many to one relationship?

**Comment by studiovlijmscherp** [comment]
**Places -> relate to one or more cities:**
<img width="599" alt="schermafbeelding 2017-10-18 om 09 04 54" src="https://user-images.githubusercontent.com/3353713/31704919-b37aa524-b3e3-11e7-89cd-b06bfc2ad77d.png">

**Each city has a 'code' column**
<img width="791" alt="schermafbeelding 2017-10-18 om 09 06 28" src="https://user-images.githubusercontent.com/3353713/31704920-b394d57a-b3e3-11e7-8fe8-d0d5e766f916.png">

**places_city junction table:**
<img width="492" alt="schermafbeelding 2017-10-18 om 09 07 31" src="https://user-images.githubusercontent.com/3353713/31704950-d012a4fc-b3e3-11e7-88b6-6ae4d3c2ef25.png">

**Comment by WellingGuzman** [comment]
Thanks for the information @studiovlijmscherp

**Comment by WellingGuzman** [comment]
I've fixed the M2M/O2M issue, give a look at the latest from `develop` and let us know if that works for you.

Ref: https://github.com/directus/directus/commit/b8234ee19a47aaa3b4230b2fca91f77511fc6421

**Comment by studiovlijmscherp** [comment]
This commit actually makes things worse. API/Directus not working at all after this latest commit:

`[19-Oct-2017 04:59:47 America/New_York] PHP Fatal error:  Uncaught Error: Class 'Cache\Adapter\Void\VoidCachePool' not found in /Users/michielzoer/GIT_Projects/triptilt_api/api/core/Directus/Bootstrap.php:1189
Stack trace:
#0 [internal function]: Directus\Bootstrap::cache(NULL)
#1 /Users/michielzoer/GIT_Projects/triptilt_api/api/core/Directus/Bootstrap.php(87): call_user_func('Directus\\Bootst...', NULL)
#2 /Users/michielzoer/GIT_Projects/triptilt_api/api/core/Directus/Bootstrap.php(703): Directus\Bootstrap::get('cache')
#3 [internal function]: Directus\Bootstrap::hookEmitter(NULL)
#4 /Users/michielzoer/GIT_Projects/triptilt_api/api/core/Directus/Bootstrap.php(87): call_user_func('Directus\\Bootst...', NULL)
#5 /Users/michielzoer/GIT_Projects/triptilt_api/api/core/Directus/Bootstrap.php(172): Directus\Bootstrap::get('hookemitter')
#6 /Users/michielzoer/GIT_Projects/triptilt_api/vendor/slim/slim/Slim/Helper/Set.php(228): Directus\Bootstrap::Directus\{closure}(Object(Slim\Helper\Set))
#7 /Users/michielzoer/GIT_Projects/triptilt_api/vendor/slim/slim/Slim/Helper/Set.php in /Users/michielzoer/GIT_Projects/triptilt_api/api/core/Directus/Bootstrap.php on line 1189
`

**Comment by WellingGuzman** [comment]
that's the cache we are working on, I'm sorry for any inconvenience this could bring, to solve this you have to update the packages, `composer install` or `composer update` to install the missing `cache/cache` pachage, this is a new required package.

**Comment by WellingGuzman** [comment]
Has been fixed by https://github.com/directus/directus/commit/b8234ee19a47aaa3b4230b2fca91f77511fc6421

Until there's another one reported I will maintain it closed
