### ISSUE TITLE
Bulk update not working as expected with M2M relationship

### ISSUE THREAD

**Issue by bcartier** [directus/directus#14199]
### Describe the Bug

In every other case, using the bulk update replaces all existing values with the newly set values in the bulk-update drawer. With a M2M relationship, any relationships chosen in the bulk-update drawer are added to existing relationships. In our case we have a collection of permits related to one or more items in an Organization collection. Bulk-updating would be used to change several Permits to be related to a new set of Organizations (a fairly common requirement). Currently, this requires editing each Permit Item individually to remove existing Organization relationships before adding new ones in bulk, defeating the purpose of the bulk-update.

### To Reproduce

1. Create two collections with a M2M relationship field between them. 
2. Create some relationships using the Item edit form
3. Bulk edit some Items and choose new relationships
4. observe that old relationships are not replaced by the newly set ones - instead the new relationships are added.

### Errors Shown

None

### What version of Directus are you using?

v9.13.0

### What version of Node.js are you using?

16.15.1

### What database are you using?

MySQL

### What browser are you using?

Chrome

### How are you deploying Directus?

docker

**Comment by azrikahar** [comment]
Although this issue technically precedes #15034, it seems like the bulk of the discussion surrounding this topic is being done over in that issue instead, so opting to close this as "duplicate" to merge both issues 👍 Feel free to subscribe to #15034 for further updates.
