### ISSUE TITLE
Repeater field with two input fields is incorrectly typed in openapi spec

### ISSUE THREAD

**Issue by sandrosc** [directus/directus#14208]
### Describe the Bug

A repeater with two input fields generates an OpenAPI spec that indicates the return value is a list of strings:

    list:
      nullable: true
      type: array
      items:
        type: string

When actually it returns a list of objects:

```js
[
  { title: 'a title', text: 'a text' },
  { title: 'another title', text: 'another text'}
]
```

The repeater: 
![image](https://user-images.githubusercontent.com/12650063/176636910-501fdb90-c061-4090-ae5a-6d62a9cfb28a.png)

### To Reproduce

Create a repeater with two fields and generate the OpenAPI spec.

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

v16.14.2

### What database are you using?

PostgreSQL 13.7

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by pmwheatley** [comment]
Had a go at fixing this one as an exercise in familiarising myself with the Directus codebase. Would appreciate any feedback on the PR #14581. Thanks in advance!
