### ISSUE TITLE
SVG logos not rendering in Gmail

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#14200]
### Describe the Bug

Gmail doesn't support SVGs in emails, so if you use a .svg as the project logo, any email with that logo will show up broken in Gmail 😩

### To Reproduce

Use a .svg logo, have directus send an email

### Errors Shown

n/a

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

n/a

### What database are you using?

n/a

### What browser are you using?

Gmail

### How are you deploying Directus?

n/a

**Comment by br41nslug** [comment]
perhaps we could do svg's inline for mails but i don't think we have an easy way of getting the contents of a svg to embed 🤔

**Comment by benhaynes** [comment]
Might still be blocked, need to test.

**Comment by br41nslug** [comment]
Indeed looks like gmail blocks svg images in all forms

**Comment by benhaynes** [comment]
Sounds about right. We should add a note about this in the Docs (CC @erondpowell ) and maybe even a warning/note in the Project Settings until we can rasterize the SVG for mail.

**Comment by erondpowell** [comment]
> Sounds about right. We should add a note about this in the Docs (CC @erondpowell ) and maybe even a warning/note in the Project Settings until we can rasterize the SVG for mail.

This issue is now noted in the docs under Project Settings.
When it's fixed and closed, please "ping me" and I will remove the warnings.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-239](https://linear.app/directus/issue/ENG-239/svg-logos-not-rendering-in-gmail)

**Comment by rijkvanzanten** [comment]
Closing this as a Wont Fix as it's out of our control.
