### ISSUE TITLE
New Slim environment extend causing `mod_rewrite` looking errors 

### ISSUE THREAD

**Issue by ajshortt** [directus/directus#1420]
## Version Info
  - Directus version and branch: (Or commit hash)
  - PHP version: 5.6.25
  - MySQL version: 14.14
  - Web server: Apache 
  - OS name and version: macOS 10.12.4

## Expected Behaviour
Install and login successfully 

## Actual Behaviour
On install, the `mod_rewrite` status fails.
I still install but the login is unsuccessful. This issue is similar to all the rewrite issues
but the only thing is that it worked on a previous install last week. 

I checked out a commit from last week and it seemed to be fine.
So I dug deeper to find the issue seems to be something to do with the new slim environment usage.

On the latest commit `5f4de4c207706c68160a37b10ea2cf5d4496c699` I commented out `line 44-46` and this seemed to help with a few issues after login. 

Personally, I'm going to dev in the old commit till this is resolved so please give me a bump when it is. 

Ps. Loving the system.

**Comment by WellingGuzman** [comment]
Hey @ajshortt whats the file where you commented out those lines?

**Comment by ajshortt** [comment]
👍 Cheers pal
