### ISSUE TITLE
Directus v 9.13.0 cannot use argon2@0.28.2 anymore

### ISSUE THREAD

**Issue by urbgimtam** [directus/directus#14226]
### Describe the Bug

Updating to version 9.13.0 contains breaking changes. After updating to version 9.13.0, I'm unable to migrate the database.
Downgrading to version 9.12.2 works. 

Please note that I'm aware of issues https://github.com/directus/directus/issues/6071 / https://github.com/directus/directus/issues/3810 / https://github.com/directus/directus/discussions/6222. I'm running node on a CentOS7 Plesk server.

So far, I've been able to mitigate them by installing and rebuilding argon2@0.28.2. (your documentation doesn't state a version, but versions higher than 0.28.2 can't build when presented with a `/lib64/libc.so.6: version 'GLIBC_2.25' not found` error.

By looking at the error log
`/lib64/libc.so.6: version 'GLIBC_2.25' not found (required by /var/www/vhosts/domain/projectname.com/node_modules/directus/node_modules/argon2/lib/binding/napi-v3/argon2.node)`
 it seems that directus now includes a subdependency on argon2, which we cannot access to rebuild.

By manually copying the rebuilt /node_modules/argon2 folder to /node_modules/directus/node_modules/argon2, I've managed to sucessfully migrate the database.

### To Reproduce

`npm update && npm rebuild argon2@0.28.2 --build-from-source`

The dependencies become: 
```
"dependencies": {
    "argon2": "0.28.2",
    "directus": "9.13.0",
    "mysql": "^2.18.1"
}
```

Then run `npm directus database migrate:latest`.

### Errors Shown

```
> @ migrate /var/www/vhosts/domain/projectname.com
> npx directus database migrate:latest

/lib64/libc.so.6: version `GLIBC_2.25' not found (required by /var/www/vhosts/domain/projectname.com/node_modules/directus/node_modules/argon2/lib/binding/napi-v3/argon2.node)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ migrate: `npx directus database migrate:latest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

14.19.3

### What database are you using?

Mysql

### What browser are you using?

Chrome

### How are you deploying Directus?

Plesk (CentOS 7, via Phusion Passenger)

**Comment by rijkvanzanten** [comment]
Instead of downgrading argon2, you should really consider upgrading GLIBC if at all possible. GLIBC 2.25 was released over 5 years ago and is 10 versions behind at this point.

We're not currently planning on downgrading argon2 itself in Directus, as we need to stay up to date with important security releases in that library.

**Comment by urbgimtam** [comment]
I understand and agree. Taking into account that this becomes a breaking change for some users with a very specific setup that they cannot easily control, the main goal for the issue was to alert others, as I couldn't find any information about it.

**Comment by urbgimtam** [comment]
Just for clarification to others users stuck in the same issue, server with CentOS7 or other older Linux distros which are stuck with GLIB version below 2.25, cannot install Directus 9.13.0 at all.

This is NOT a Directus issue, but a argon2 + CentOS7 issue (as GLIB officially package for CentOS7 is 2.17, and messing with it can turn your system very unstable). Other older Linux systems can suffer the same fate also.

(If you are using Plesk with CentOS7, it seems there is no supported way to update/upgrade to a more recent distro, but I may be wrong)

This issue, however, does affects a small percentage of Directus self-hosting users, which should be aware of it.

As a last resort, Directus 9.12.2 can still be installed by downgrading argon2 to 0.28.2.

**Comment by mytchallb** [comment]
> Just for clarification to others users stuck in the same issue, server with CentOS7 or other older Linux distros which are stuck with GLIB version below 2.25, cannot install Directus 9.13.0 at all.
> 
> This is NOT a Directus issue, but a argon2 + CentOS7 issue (as GLIB officially package for CentOS7 is 2.17, and messing with it can turn your system very unstable). Other older Linux systems can suffer the same fate also.
> 
> (If you are using Plesk with CentOS7, it seems there is no supported way to update/upgrade to a more recent distro, but I may be wrong)
> 
> This issue, however, does affects a small percentage of Directus self-hosting users, which should be aware of it.
> 
> As a last resort, Directus 9.12.2 can still be installed by downgrading argon2 to 0.28.2.

I go to the point of updating GCLIB on my CentOS 7 VPS but was told the kernel was too old. Couldn't seem to get past it so switching to Ubuntu 22.04 sever which works with Directus/Plesk/Docker.
