### ISSUE TITLE
UI Filtering on related table returns error: undefined index: table_name

### ISSUE THREAD

**Issue by studiovlijmscherp** [directus/directus#1422]
## Version Info
  - Directus version and branch: 6.3.9
  - PHP version: 7.1.0
  - MySQL version: 5.6.34
  - Web server: Apache
  - OS name and version: macOS Sierra 10.12.4

## Expected Behavior
Filter a list in the UI based on a related table

## Actual Behavior
Filtering returns an error:
undefined index: table_name

## Steps to Reproduce
I have a 'place'. 
This place (Hotel Four Roses, Camping Pinokio, etc.) belongs to a 'Category' (hotel, restaurant, etc.)
place -> category have a 'Many to Many relation' @places table

Each category belongs to a category_group
category -> category_group have a 'Many to One' relation @Categories table

This way I can add categories to places. This is working fine.
Filtering in the UI on the 'Category' returns an error when I select a category: 
Server error:
undefined index: table_name

this is the URL thats being called:
http://triptilt-v2.dev/api/1/tables/places/rows?currentPage=0&perPage=200&sort=name&sort_order=ASC&status=1%2C2&adv_search%5B0%5D%5Bid%5D=category&adv_search%5B0%5D%5Btype%5D=%3D&adv_search%5B0%5D%5Bvalue%5D=3&columns_visible%5B%5D=name&columns_visible%5B%5D=country
with an error (500) and the following results (JSON):
[https://www.dropbox.com/s/lpfiq03xn6e4cap/directus_tablename_error.json?dl=0](url)

## Logs or Screenshots
Places table:
![a1-places_table](https://cloud.githubusercontent.com/assets/3353713/25424850/2c2da7cc-2a6a-11e7-9d12-abbf3e386e0d.png)

Detail of 'Category' Many to Many relation:
![a2-place_table_relation](https://cloud.githubusercontent.com/assets/3353713/25424851/2c31b146-2a6a-11e7-8088-2a645fe4369c.png)

Categories table:
![b1-categories_table](https://cloud.githubusercontent.com/assets/3353713/25424852/2c33240e-2a6a-11e7-8738-a42ac94a1241.png)

Detail of 'Category' Many to One relation:
![b2-categories_table_relation](https://cloud.githubusercontent.com/assets/3353713/25424855/2c38a65e-2a6a-11e7-83c2-d4a253caeb33.png)

Pivot table:
![c1-category_groups_pivot_table](https://cloud.githubusercontent.com/assets/3353713/25424854/2c33e402-2a6a-11e7-94c9-8882b872f57b.png)

UI filter:
<img width="1228" alt="d1-ui-filter" src="https://cloud.githubusercontent.com/assets/3353713/25424853/2c33b054-2a6a-11e7-85d2-1270ae358ff1.png">

UI filter error:
![d2-ui-filter-error](https://cloud.githubusercontent.com/assets/3353713/25424856/2c410420-2a6a-11e7-9aeb-530e6fbb1fd2.png)

**Comment by WellingGuzman** [comment]
Hey @studiovlijmscherp,

I just pushed a [patch](https://github.com/directus/directus/commit/60c7bd70c8040460e4207964afce7f102186e8f7) for this issue, I hope it resolves the issue, let us know if it worked out.

**Comment by studiovlijmscherp** [comment]
@WellingGuzman - filtering works. Great!
