### ISSUE TITLE
Retrieving current userdata without exposing password & salt

### ISSUE THREAD

**Issue by GeeWizWow** [directus/directus#1423]
## Version Info
  - Directus version and branch: Directus-docker 6.3

## Issue

Unless I'm missing anything the only way to retrieve the current user's data is to query `/api/1/tables/directus_users/rows` which exposes password & salt:

`{
      "id": 4,
     ...
      "password": "$2y$12$LCaZfKAp.STXwhfsdfdsWfwxLiiuybN47hnfsdfQWv1M2.DHHOKUf/RNdfDJ.jS",
      "salt": "53219005ddsf5f12305",
      ...
      "group": {
      ...
      },`

Is there anyway to get the users information without exposing these items?

**Comment by WellingGuzman** [comment]
Hey @GeeWizWow,

The authenticated user can always see all their information, you can select the columns you want to see by adding `columns=id,email,etc` into the url.

I don't know if that works for you.

**Comment by GeeWizWow** [comment]
@WellingGuzman 

I'd missed `colums` param, thanks for pointing it out. It'll do. Cheers
