### ISSUE TITLE
Couldn't create a new project

### ISSUE THREAD

**Issue by kadiresen** [directus/directus#14237]
### Describe the Bug

Trying to create a new project with ```yarn create directus-project directus.test``` or ```npx create-directus-project directus.test ``` and retrieving this:
```
Error: npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-sdk/client-sts@3.121.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
Facing with that also when upgrading to v9.13.0.

### To Reproduce

Open a new terminal window and just type ```yarn create directus-project directus.test``` or ```npx create-directus-project directus.test ```

### Errors Shown

```
Error: npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-sdk/client-sts@3.121.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

16.15.0

### What database are you using?

MySQL

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment]
See https://github.com/directus/directus/issues/14235#issuecomment-1172003362 👍
