### ISSUE TITLE
DOCU typo: Sequal-Pro -> should be Sequel-Pro

### ISSUE THREAD

**Issue by studiovlijmscherp** [directus/directus#1424]
https://docs.getdirectus.com/6.3.6/#When_to_Use_Directus

"Experimental Projects"
Sequal-Pro -> should be **Sequel-Pro**

**Comment by benhaynes** [comment]
Thanks @studiovlijmscherp – good catch! I've updated the repo, it will push to the site shortly.

In the future, report these to the issues section of the Docs repo (or better yet, send us a PR 😉 ):

https://github.com/directus/docs
