### ISSUE TITLE
Many-to-one dropdown issue

### ISSUE THREAD

**Issue by ajshortt** [directus/directus#1425]
## Version Info
  - Directus version and branch: `master` `7052909c9`
  - PHP version: 5.6.25
  - MySQL version: 14.14
  - Web server: Apache
  - OS name and version: macOS 10.12.4

## Expected Behavior
I created two tables `client` and `project` where one `client` has many `project`s. 
In the `project` table, I created a many-to-one column that refers to the `client` table.

When I come to add a project, the clients input seems to show `<option>`s for each client but doesn't actually have any text within the element??  

Am I just missing something? 

Cheers

<img width="1254" alt="screen shot 2017-04-26 at 13 03 55" src="https://cloud.githubusercontent.com/assets/6783995/25433649/0955c4de-2a81-11e7-8c26-ee47a368ca1c.png">

**Comment by WellingGuzman** [comment]
Hey @ajshortt,

You can solve this problem by going to the M2O column options `Settings > Tables & Inputs > Project` and type (comma separate) the name of the columns name, by default no columns are selected.

I will work on a quickfix to at least show the first non-system column (if any) as visible on M2O Interface.
