### ISSUE TITLE
Importing @directus/sdk break whole project with react app (redux-toolkit)

### ISSUE THREAD

**Issue by Holovin** [directus/directus#14257]
### Describe the Bug

If you use react with typescprt + router and with any UI libs — you will get build errors.

I think this is because `'@directus/sdk'` has some `vue` peer dependencies (because if you delete all `vue*` directories from node-modules, then everything is build fine)

So `directus@sdk` has dependecy `@directus/shared` and this package has peer dependecies: 
```
"vue": "3",
"vue-i18n": "9",
"vue-router": "4"
```

And I'm not sure that these libraries are needed in sdk project, especially because sdk has examples for many libraries (such as angular, react, svlete, etc)

### To Reproduce

1. Create a project: `npx create-react-app my-app --template redux-typescript` (https://redux-toolkit.js.org/introduction/getting-started)
2. Add dependecy `"@directus/sdk": "^9.13.0"`
3. Ensure that app work
4. Add any import of directus, for example `import { Directus } from '@directus/sdk';` to `App.tsx`
5. Try to build app again

To fix it:
1. Open node_modules folder
2. Remove vue, vue-i18n, vue-router folders
3. Try to build again

### Errors Shown

You will get a lot of error like this (depends on which libs you use):

```
Compiled with problems:X

ERROR in src/index.tsx:13:4

TS2786: 'React.StrictMode' cannot be used as a JSX component.
  Its return type 'ReactElement<any, string | JSXElementConstructor<any>> | null' is not a valid JSX element.
    Type 'ReactElement<any, string | JSXElementConstructor<any>>' is missing the following properties from type 'Element': ref, scopeId, children, component, and 10 more.
```

### What version of Directus are you using?

9.13

### What version of Node.js are you using?

16.15.0

### What database are you using?

Postgress

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker-compose

**Comment by azrikahar** [comment]
This should be the same as #13049, particularly as described by this comment which aligns with your deduction: https://github.com/directus/directus/issues/13049#issuecomment-1135945488
