### ISSUE TITLE
Flows: URL encode url field in Request URL operation.

### ISSUE THREAD

**Issue by makote** [directus/directus#14265]
### Describe the Bug

The the url field in the Webhook / Request URL operation isn't url Encoded / Sanitized before making the request.

When passing payload values as query parameters to the URL field in the Request URL Operation, the url isn't encoded before sending the request.

### To Reproduce

Within a flow create a request operation with a URL field that uses a payload value anywhere.
<img width="1017" alt="Screen Shot 2022-07-03 at 16 44 32" src="https://user-images.githubusercontent.com/1120920/177058233-22fc47f0-6d3c-4936-b984-7dd49055e2d4.png">

After the operation runs without encoding the url field.

### Errors Shown

```{
  "message": "Request failed with status code 404",
  "name": "AxiosError",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": {},
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "User-Agent": "axios/0.27.2"
    },
    "url": "https://https://www.google.com/search?q=**unencoded value ó # **",
    "method": "get"
  },
  "code": "ERR_BAD_REQUEST",
  "status": 404
}```

### What version of Directus are you using?

9.13

### What version of Node.js are you using?

18

### What database are you using?

Postgres 13

### What browser are you using?

Brave

### How are you deploying Directus?

ubuntu/ self-hosted

**Comment by zeel-pathak** [comment]
Hey @rijkvanzanten , New to the community, I think this bug will be good for the warm up with the codebase.

Anything more I need to know?

**Comment by rijkvanzanten** [comment]
@zeel-pathak This is all you'd have to update:

https://github.com/directus/directus/blob/033e12323e001cda3bf36c86e87da15398d72f20/api/src/operations/request/index.ts#L20

**Comment by zeel-pathak** [comment]
@rijkvanzanten , Thanks for the help and for saving my time finding the bug in code, 

I think the issue as described is that the Url is not encoded.

So I am using the ```encodeURIComponent(url)``` instead of URL, so that the respective url got encoded

**Comment by zeel-pathak** [comment]
If it sounds good to you, I will apply a pull request for the same.

**Comment by fitu86** [comment]
there is a way to do it from the app, I use it to synchronize directus with marketplaces, I have a collection where to register the credentials of external applications, this is the form (there are fixed fields and others that are updated as tokens.

![Screenshot_20220714_194944_com android chrome](https://user-images.githubusercontent.com/16139127/179126149-d0851655-8d05-4ae6-a580-9a77ff9431df.jpg)


After we create a flow with a GET method webhook trigger, we copy the url that is generated from the webhook, I use it as Uri-redirect, to generate a code, 

![Screenshot_20220714_193409_com android chrome](https://user-images.githubusercontent.com/16139127/179126187-548bb6e0-63f8-497b-88b5-54d868c4fc6c.jpg)
![Screenshot_20220714_195306_com android chrome](https://user-images.githubusercontent.com/16139127/179126191-5d986220-d603-41be-8876-dca1b9cbd392.jpg)

wich you get it by being redirected, and another thread is created that works with a cron job to refresh the token every 6 hours.

**Comment by fitu86** [comment]
![Uploading SVID_20220714_192623_1.gif…]()
