### ISSUE TITLE
Upload the file and the file name contain the non ascii character

### ISSUE THREAD

**Issue by fastdevops** [directus/directus#14264]
### Describe the Bug

1. Upload the file and the file name contain the non ascii character
2.  The file name is changed to other Æ¦å¿µmarcaã§ã£oå¸æ¿ç½²æ¢å¤3

### To Reproduce

1. Upload the file and the file name contain the non ascii character
2.  The file name is changed to other Æ¦å¿µmarcaã§ã£oå¸æ¿ç½²æ¢å¤3.png

### What version of Directus are you using?

9.13

### What version of Node.js are you using?

8.11.0

### What database are you using?

mysql

### What browser are you using?

chrome

### How are you deploying Directus?

docker

**Comment by rijkvanzanten** [comment]
What's the original file name?

**Comment by fastdevops** [comment]
> What's the original file name?

中文Marcação中文3.png

**Comment by loongmxbt** [comment]
Same issue on v9.13.0, previous version v9.12.x does not have this problem.
![981656902518_ pic](https://user-images.githubusercontent.com/5986600/177078689-14ec0909-5bf3-401b-a801-c80f207a29cd.jpg)
.
