### ISSUE TITLE
GraphQL changing data types

### ISSUE THREAD

**Issue by lluishi93** [directus/directus#14280]
### Describe the Bug

When doing a GraphQL GET operation, some field types (as showed in the screenshots) are being changed, like the ID (primary key).

![image](https://user-images.githubusercontent.com/14786440/177194480-08f3a5f5-ee09-4b97-8710-0186472f842e.png)

### To Reproduce

1. Create a collection
2. Create some item for that collection
3. Do a GET operation with Rest API
4. Do a GET operation with GraphQL
5. Check that the ID type is being changed

### Errors Shown

-

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
In this particular case, the `id` field is typed as a GraphQL `ID!`[^1], which is cast by GraphQL as a string

[^1]: > ID: The ID scalar type represents a unique identifier, often used to refetch an object or as the key for a cache. The ID type is serialized in the same way as a String[...]

**Comment by jotatoledo** [comment]
@rijkvanzanten is there a reason for PK `id` props being serialized as strings? it feels contraproductive specially when using the graphql endpoints through the sdk + types generated using [this extension](https://github.com/maltejur/directus-extension-generate-types)

**Comment by br41nslug** [comment]
I believe the PK is serialized to string to support the UUID and BigInteger types of primary keys.

**Comment by rijkvanzanten** [comment]
> I believe the PK is serialized to string to support the UUID and BigInteger types of primary keys.

It's even simpler than that: GraphQL has a native "ID" type.

> The ID scalar type represents a unique identifier, often used to refetch an object or as the key for a cache. The ID type is serialized in the same way as a String

We're currently using the ID type for IDs, it's a graphql thing that that's casted as a string at all times
