### ISSUE TITLE
Not able to delete filter when there are than preset for each collection for same user

### ISSUE THREAD

**Issue by Jeyakumarrathnaselvi** [directus/directus#14288]
### Describe the Bug

Not able to remove the filter if there are more than one preset per user.

Same filter comes back again after removing the filter

### To Reproduce

Add two presets for the same user for same collection. Let both the preset has some filter configured

this issue comes

### Errors Shown

same filter comes again after deleting the filter

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

16.13.1

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

Cloudron

**Comment by Jeyakumarrathnaselvi** [comment]
Enabled full access to the Presets post your input but user again faced a issue today

![image](https://user-images.githubusercontent.com/36895131/177525829-f4096297-d400-4d9c-bb8e-c15370746c3a.png)

**Comment by rijkvanzanten** [comment]
We haven't been able to reproduce the issue based on the reproduction steps provided, and to be honest, I'm also not entirely sure what you're trying to do, so I'll close this for now.

The app will use whatever the first matching preset is it comes across, so if you edit the second duplicate preset, the first won't be affected.
