### ISSUE TITLE
Conditions not working (partially)

### ISSUE THREAD

**Issue by azrikahar** [directus/directus#14285]
### Describe the Bug

In Directus `9.12.2` (with relevant PR #13799), the conditions added to `valueField` allows us to select primary key _when_ we are using `count` or `countDistinct` for Group Aggregation:

https://github.com/directus/directus/blob/7d451f8df4383373380b7a3eb39d9dfce3488982/app/src/panels/time-series/index.ts#L223-L248

Working in `9.12.2` (`id` is an auto-incremented integer):

https://user-images.githubusercontent.com/42867097/177236556-87868e6e-6226-4963-914c-b83ce65539eb.mp4

However now the same interaction seems to no longer work since `9.13.0`:

https://user-images.githubusercontent.com/42867097/177236215-4235b73f-9637-4fd3-8add-02087dc91aba.mp4

### To Reproduce

1. Create a `test` collection with auto-incremented integer (no optional system fields needed)
2. Add 2 fields to the created collection:

   - `metric` (input field, integer)
   - `timestamp` (datetime field, timestamp)

3. Create a dashboard.
4. Try to add a time-series panel for `test` collection, select "Count" or "Count (Distinct)" for Group Aggregation, and try to select `id` field in Value Field. It used to be selectable in `9.12.2`, but not since `9.13.0`.

### Errors Shown

No errors logged.

### What version of Directus are you using?

9.13.0 (main branch https://github.com/directus/directus/commit/7d451f8df4383373380b7a3eb39d9dfce3488982)

### What version of Node.js are you using?

16.15.1

### What database are you using?

PostgreSQL 13.5

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment]
As brought up in #14295, this seems to be present in v-form in general. Additional new findings are:

- It also doesn't work if we were to set the condition to change the field's placeholder:

  https://user-images.githubusercontent.com/42867097/177491640-ec3d2c84-db2d-4145-9538-279b460c7010.mp4

- But it does work when we change `readonly`:

  https://user-images.githubusercontent.com/42867097/177491703-9faa49c1-520c-405f-9300-02bcc5bbbf6e.mp4

**Comment by w0kyj** [comment]
Conditional rules to hide M2A in a raw group are also not consistently being enforced since 9.13.0 thru 9.14.1

Clean set up seems to be okay, but migrated projects having issues.
