### ISSUE TITLE
Improper links in sharing email

### ISSUE THREAD

**Issue by Pachat** [directus/directus#14297]
### Describe the Bug

When sharing a link by email, the link does not specify the `path`
I use my server with an address like `http://IPv4:port/` and it works OK
But when sending the sharing email,  `IPv4:port` is missing

### To Reproduce

1. Share a link by email
2. Review the mail received

### Errors Shown

Before sending the mail, the `Send link` shown is correct
`http://IPv4:port/admin/shared/32021047-4228-4034-9130-802955071873`

But the email received contains a link that is incorrect:
```
Hello,
user@mydomain.com has invited you to view an item in test.
    [/admin/shared/32021047-4228-4034-9130-802955071873]Open
```
The path is missing

### What version of Directus are you using?

9.13

### What version of Node.js are you using?

v16.14.0

### What database are you using?

PostgreSQL

### What browser are you using?

Firefox

### How are you deploying Directus?

VPS

**Comment by azrikahar** [comment]
Did you configure the `PUBLIC_URL` environment variable? It's necessary for links in emails to work properly 👍

**Comment by Pachat** [comment]
My bad. Setting PUBLIC_URL as `http://IPv4:port` makes it work nice.
