### ISSUE TITLE
Prevent selecting foreign key for sort field in relational configuration

### ISSUE THREAD

**Issue by jtrobinson1993** [directus/directus#14290]
### Describe the Bug

I created a M2A relationship field on a data model, and added a sort field so that I could reorder the selected items. Afterwards, reordering the items wouldn't save regardless of what field I used to sort, and when I sorted by the "item" field, it would cause the names of the fields to disappear after changing their order:

Before reorder:
![image](https://user-images.githubusercontent.com/25162360/177343903-b59c09e1-f3e7-46eb-9f1c-b3ef434a953b.png)

After reorder:
![image](https://user-images.githubusercontent.com/25162360/177343931-8ab73837-e66b-4ca0-a4f9-b380914717bf.png)

The names disappearing stopped happening when I changed the sort field to the articles_id field, but the order of the item would still not be saved:

![image](https://user-images.githubusercontent.com/25162360/177344155-f0cf6be3-7b05-41ae-95c4-024747b3e4f3.png)

### To Reproduce

Create M2A field with sort field selected on a data model.

Select 2 other collections to add items from.

Create one of each type of item.

Attempt to reorder them.

The order won't be saved, and depending which field you selected to sort by, you may encounter the visual bug described above.

### What version of Directus are you using?

9.12.2 (cloud hosted)

### What version of Node.js are you using?

unknown

### What database are you using?

unknown

### What browser are you using?

chrome

### How are you deploying Directus?

Cloud service

**Comment by br41nslug** [comment]
> I sorted by the "item" field
I think there might be some confusion about what the `sort` field does here. When selecting a "sort field" that field will be used to both `sort by` and to `save the sort order` as it needs to save the sort order somewhere when updated.
> and added a sort field so that I could reorder the selected items
Generally you'd create a new integer field (i personally always call it `sort`) on the junction table to use for sort order. Setting this to any field that already contains other content will indeed override that fields value to try and save the updated sort order.
