### ISSUE TITLE
Relation deleted after delete a field of a collection

### ISSUE THREAD

**Issue by jessybreyne** [directus/directus#14298]
### Describe the Bug

When I delete a field, all the joins (relations, links) of my collection translations are deleted

### To Reproduce

npm init directus-project directus-test
Use SQLITE

Create a posts collection
Add a translations relation
Add an input field (A) to posts

Add an input field (B) to post_translations

Create a post with 2 translations

Delete the input field (A) of post collection

All the relations translations of input (B) are deleted.

### What version of Directus are you using?

directus": "^9.13.0"

### What version of Node.js are you using?

v16.15.1

### What database are you using?

"sqlite3": "^5.0.8"

### What browser are you using?

Brave (Chrome)

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
This should be the same as #13936 👍
