### ISSUE TITLE
Too Many Bugs On Flow

### ISSUE THREAD

**Issue by imiskolee** [directus/directus#14307]
### Describe the Bug

I am working on flows now, and trying to fix a lots flows bug, just make this issue as tracker:

### To Reproduce

* [] can not read keyedData on `Condition` operator:(created a read data operator `read_object` as `object_key` and connect to a `Condition` operator, then can not use the object key `object_key` on condition rule.

### What version of Directus are you using?

00

### What version of Node.js are you using?

00

### What database are you using?

00

### What browser are you using?

00

### How are you deploying Directus?

00

**Comment by rijkvanzanten** [comment]
Please just create individual issues, as that's way easier to triage, track, and solve 🙂 Also please make sure to include the correct reproduction steps and version information, as that's mission critical in reproducing / resolving potential issues 👍🏻

**Comment by imiskolee** [comment]
I tried write a new unit test case 

```node
	it('nested filter', () => {
		const mockFilter = { payload: { id: { _null: false } } };
		const mockPayload = { payload: { id: 'abcd' } };
		console.log(validatePayload(mockFilter, mockPayload));
		expect(validatePayload(mockFilter, mockPayload)).toHaveLength(0);
	});
```

showing a exception 

```
[[ValidationError: "payload.id" is not allowed]]
```

**Comment by rijkvanzanten** [comment]
What is `validatePayload` in this example? Where does it come from?

**Comment by imiskolee** [comment]
I trying to fix the validatePayload can not working on nested object now.
