### ISSUE TITLE
SSO login button doesn't work after upgrading from 9.13 to 9.14

### ISSUE THREAD

**Issue by younky-yang** [directus/directus#14325]
### Describe the Bug

After upgrading from 9.13.0 to 9.14.0 without any configuration change, I found the login with Microsoft button disappeared, so I can't SSO to the application. 

### To Reproduce

If you have SSO worked before 9.14, just upgrade it to 9.14, and the login with SSO provider button will disappear. or you configure the SSO for 9.14 but you can't login with SSO as there is no login with SSO button.

### Errors Shown

no logs found from the console as this is a code issue. 

### What version of Directus are you using?

9.14.0

### What version of Node.js are you using?

16.15.1

### What database are you using?

postgres 13, Aurora RDS 11.7

### What browser are you using?

chrome

### How are you deploying Directus?

local, AWS Fargate

**Comment by younky-yang** [comment]
The issue can be fixed by setting {immediate: true} for sso-links.vue. 
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/10388011/177929168-d19ccf06-6a0f-420f-8af6-41866a25b901.png">

**Comment by azrikahar** [comment]
@younky-yang nice catch! Want to make a PR for it? I reckon we can use a computed instead and remove the watch and ref to simplify it.

**Comment by younky-yang** [comment]
> @younky-yang nice catch! Want to make a PR for it? I reckon we can use a computed instead and remove the watch and ref to simplify it.

Working on the PR now.
