### ISSUE TITLE
The Markdown field interface it's editable when readonly

### ISSUE THREAD

**Issue by abdonrd** [directus/directus#14329]
### Describe the Bug

The Markdown field interface it's editable when readonly
(you can see that it's readonly in the raw value)

https://user-images.githubusercontent.com/1007051/177955838-d978c4ea-2f61-4a58-b7aa-4eb43cc7336b.mov

It works well with the Textarea interface:
<img width="833" alt="Screen Shot 2022-07-08 at 10 52 21" src="https://user-images.githubusercontent.com/1007051/177955970-29384d69-1cb7-4b7e-b75c-38b167c7868d.png">

### To Reproduce

Use a Markdown field interface with readonly field.

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

16.14.2

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
I can't seem to reproduce this on my end (Windows, Chrome, PostgreSQL):

https://user-images.githubusercontent.com/42867097/178185980-8c111bf7-265f-4236-a7b2-ca371fc7835d.mp4

Can you share how are you making it readonly? Are you by any chance using conditions to make it readonly?

With that said, it seems to also work fine with conditions:

https://user-images.githubusercontent.com/42867097/178186415-94be9a7c-9fba-4cd7-9d10-218c0e8f386a.mp4

**Comment by abdonrd** [comment]
@azrikahar but you test the wysiwyg, not the markdown. Try with the markdown. 😊

**Comment by azrikahar** [comment]
> @azrikahar but you test the wysiwyg, not the markdown. Try with the markdown. 😊

Somehow I was fixated with WYSIWYG doesn't works, Textarea works but not markdown. Thanks for correcting! 😄 Can confirm markdown fields are not disabling/readonly.

**Comment by abdonrd** [comment]
Yeah, we are not using conditions.
Just the readonly checkbox enabled.
