### ISSUE TITLE
API thrown 500 error when posting to API with custom user permissions

### ISSUE THREAD

**Issue by justkidding96** [directus/directus#1432]
## Version Info
  - Directus version and branch: master
  - PHP version: 7.1.1
  - MySQL version: 5,6
  - Web server: Apache
  - OS name and version: Mac OSX El Capitan

## Expected Behavior
Give user (group) different read/write access to fields inside table.

## Actual Behavior
When I give the user (group) different read write permission I can't store through the API.

#### Screenshot which is causing the error
![screen shot 2017-05-01 at 11 32 25](https://cloud.githubusercontent.com/assets/1297850/25576818/026b8822-2e62-11e7-94a0-b6158eb67998.png)
#### Screenshot of the error
![screen-shot-2017-05-01-at-11 34 55](https://cloud.githubusercontent.com/assets/1297850/25577165/8742e098-2e64-11e7-8d7a-23d8aca8fa4c.png)

**Comment by WellingGuzman** [comment]
Hey @justkidding96,

Thanks for reporting this error, late-night mistake here from my part. I'm going to work on a fix later today. 🔨

**Comment by WellingGuzman** [comment]
Hey @justkidding96,

Please, update the database package in composer to `0.1.5` to fix this issue.
