### ISSUE TITLE
Issue with filtering using recursive O2M count

### ISSUE THREAD

**Issue by goggi** [directus/directus#14338]
### Describe the Bug

I'm trying to filter a **recursive** o2m field based on the count option that is available.  But the filter is not filtering away records that I expect to be removed. 

[recording_20220708-231701.webm](https://user-images.githubusercontent.com/1946339/178071883-f7a8a125-c84f-42a8-b59e-128104d78d05.webm)

The o2m relation is to itself
![image](https://user-images.githubusercontent.com/1946339/178072987-252ca935-57c2-48b9-9494-36f4ce3617e3.png)

### To Reproduce

See video

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

16.15.0

### What database are you using?

Postgres 13,

### What browser are you using?

Firefox

### How are you deploying Directus?

Docker

**Comment by eikaramba** [comment]
i can also confirm this on sqlite with latest directus (9.14.1)

**Comment by rijkvanzanten** [comment]
Linear: [ENG-233](https://linear.app/directus/issue/ENG-233/issue-with-filtering-using-recursive-o2m-count)
