### ISSUE TITLE
GraphQL error on deep queries - "Max relational depth exceeded"

### ISSUE THREAD

**Issue by mpkliewer** [directus/directus#14337]
### Describe the Bug

When POSTing a GraphQL query to the /graphql endpoint that is ~12+ levels deep, an error is returned: "Max relational depth exceeded." 

This query worked fine in Directus <= 9.12.2, but fails in 9.13.0 and 9.14.0.

My data is a mix of M2M, M2A and others. Database dump available if needed.

### To Reproduce

This is an example query that fails with the error - if the `languages_code` portion is removed, the query succeeds.

```
query PublishQuery($courseId: ID!) {
  courses: courses_by_id(id: $courseId) {
    modules {
      modules_id {
        module_components {
          module_components_id {
            blocks {
              item {
                ... on block_quiz {
                  questions {
                    block_quiz_questions_id {
                      translations {
                        id
                        languages_code {
                          code
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

### Errors Shown

POST 200 response:

```
{
  "errors": [
    {
      "message": "Max relational depth exceeded.",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "courses"
      ]
    }
  ],
  "data": {
    "courses": null
  }
}
```

### What version of Directus are you using?

9.14.0

### What version of Node.js are you using?

16.16.0

### What database are you using?

Postgres 14.4

### What browser are you using?

Microsoft Edge

### How are you deploying Directus?

Running locally

**Comment by rijkvanzanten** [comment]
Set the `MAX_RELATIONAL_DEPTH` env var 👍🏻

https://docs.directus.io/self-hosted/config-options/#general

**Comment by mpkliewer** [comment]
Wow, totally missed that - thanks so much!
