### ISSUE TITLE
CSV export of presentation values don't work since v9.12.0 - n:1 relation

### ISSUE THREAD

**Issue by Lukas-Sachse** [directus/directus#14344]
### Describe the Bug

I am using the CSV export for presentation values...
![bug_csv_0](https://user-images.githubusercontent.com/62059415/178097323-e939c7a1-6f2d-4187-bcd2-3cfb8234f433.png)

with these relational values ( "veranstaltung" and "veranstaltung.titel") from a n:1 relation:
![bug_csv_1](https://user-images.githubusercontent.com/62059415/178097325-45b8d138-3b85-46ce-9ee8-a8d97b8406cf.png)

### Version 9.14.1:
![bug_csv_2_9 14 1](https://user-images.githubusercontent.com/62059415/178097324-f9d87c80-041b-428c-b063-d80152e2f47d.png)

### Version 9.13.0:
![bug_csv_3_9 13 0](https://user-images.githubusercontent.com/62059415/178098007-ad4f0913-2733-443f-a560-ada45c3da588.png)

### Version 9.12.2:
![bug_csv_3_9 12 2](https://user-images.githubusercontent.com/62059415/178097322-e9ea9c6b-c6b2-4418-8236-8b9e8d7143a5.png)

 ### Version 9.11.1:
![bug_csv_4_9 11 1](https://user-images.githubusercontent.com/62059415/178097319-e42dc941-df75-4721-ab2b-d7d682dca512.png)

### To Reproduce

1. Create a n:1 relation with display of relational values
2. Use the "quick CSV export for presentation values"
3. take a look at the exported values and compare with the presentation values
4. try different versions of directus and repeat  step 2 and 3

In v9.11.1 it should work as expected. In all versions since 9.12.0 it doesn't work anymore.

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

Postgres 13

### What browser are you using?

Vivaldi (Chromium)

### How are you deploying Directus?

Local, PaaS (Render - Web Service)

**Comment by abernh** [comment]
This problem still exists in 9.18.1 running on Standard Cloud.

In my case I am missing the values 2 fields with relative display values
 - `n:n` relation field - `collection_b.name`
 - `file` field - `{{filename_download}}  (  {{filesize}}  )`

This is also not a permission issue as this is happening for `admin` roles as well.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-232](https://linear.app/directus/issue/ENG-232/csv-export-of-presentation-values-dont-work-since-v9120-n1-relation)

**Comment by hanneskuettner** [comment]
This seems to have been fixed in the mean-time. Following the reproduction of setting up one collection with a M2O relation, selecting the related column and a field of the related value they all show up in the exported CSV exported through the quick export button.
