### ISSUE TITLE
WYSIWYG context menu does not trigger edited state

### ISSUE THREAD

**Issue by martinptacek** [directus/directus#14372]
### Describe the Bug

WYSIWYG currently saves its content only if there is a direct change. When editing something in the HTML source or with the context menu, it will not be saved.

### To Reproduce

1. Create a text containing url link and save it.
2. Open the editor again and right click on the link and change the target to be opened in a new window.
3. Save it.

If you did not do anything else, the change is not going to be saved. To force it, you need to e.g. add and delete a space. Then changes are reflected and content of editor is saved.

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

16.15.1

### What database are you using?

Cloud

### What browser are you using?

Chrome

### How are you deploying Directus?

Directus cloud

**Comment by martinptacek** [comment]
It is not only a context menu. It is also anything you do straight in the source code. When you switch to the HTML format and make a change, this change will not be reflected too. Try to edit some class or style.

**Comment by br41nslug** [comment]
Doing changes directly in the source modal works as expected for m. If you mean directly in the DOM via the dev panel that is not supported, i believe the virtual dom is the blocking factor for such things.

**Comment by martinptacek** [comment]
OK. You are right. It works now. 
Thanks.

**Comment by rijkvanzanten** [comment]
My bad! I thought you were talking about the field context menu (like #14212), but you mean the right-click context menu :

**Comment by martinptacek** [comment]
OK :-)
