### ISSUE TITLE
Error on creating tree view field

### ISSUE THREAD

**Issue by mccombs** [directus/directus#14378]
### Describe the Bug

Upon creating a Tree view field under a collection. it returns the following error:

```
[INTERNAL_SERVER_ERROR] INSERT INTO "_knex_temp_alter101" SELECT * FROM "pages"; - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed
```

### To Reproduce

- Create collection
- Create Tree view field
- Add a Key. _I used Nav_
- Select a Collection
- Select a foreign key
- Save

### What version of Directus are you using?

9.14.0

### What version of Node.js are you using?

18.4.0

### What database are you using?

SQLite

### What browser are you using?

Brave

### How are you deploying Directus?

running locally

**Comment by mccombs** [comment]
This also happens on **one to many** field

`[INTERNAL_SERVER_ERROR] INSERT INTO "_knex_temp_alter808" SELECT * FROM "offers"; - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed`

**Comment by mccombs** [comment]
Thought there might be an error on duplicate similarly named Foreign Keys so I deleted any other fields marked as title. Same error upon save/creation.

**Comment by mccombs** [comment]
Similar error with two new collections and a new field:
`[INTERNAL_SERVER_ERROR] insert into `new_source` (`name_field`) values ('test') returning `id` - SQLITE_ERROR: FOREIGN KEY constraint failed`

Surely this is related?

**Comment by azrikahar** [comment]
> Upon creating a Tree view field under a collection. it returns the following error:

Can you share what was the collection and foreign key you selected? For Tree View field, the collection should be the collection itself, and the foreign key should be newly created by typing in a new field name. Here's what I did locally without any error on SQLite:

https://user-images.githubusercontent.com/42867097/178432496-6171d0ae-dd30-441d-b5a0-333d340916f1.mp4

Would you mind trying this as well? 

> This also happens on one to many field

I assume you mean when selecting the "one to many" field as the foreign key for a Tree View field?

> Similar error with two new collections and a new field

Is this in the same context for tree view field? Can't say I fully understand what is meant here, but feel free to elaborate further if the initial recommendation shared above doesn't work 👍

**Comment by mccombs** [comment]
I'm going to close this. I believe it's due to a node version mismatch.

**Comment by Rar9** [comment]
Is this tree view working with translations?

**Comment by azrikahar** [comment]
> Is this tree view working with translations?

@Rar9 There is an open issue #15408 related to tree view and translations display, in case that's the same error you're facing 👍 

That being said, please do opt to create a new discussion if you have any general questions, or a new issue if there isn't a matching issue yet, similar to https://github.com/directus/directus/issues/11029#issuecomment-1250576578. That would be much appreciated, thanks!

**Comment by Rar9** [comment]
![Screenshot-04-10-22-16-15-56-1.png](https://user-images.githubusercontent.com/2239608/193993388-4fce49f5-acb6-45bc-862f-e1f4c51f3470.png)

I'm facing that the Child Terms don't get the same id on translation, as the nav item just increments.

And moving /re-ording is buggy as stuff disappears.

**Comment by azrikahar** [comment]
> ![Screenshot-04-10-22-16-15-56-1.png](https://user-images.githubusercontent.com/2239608/193993388-4fce49f5-acb6-45bc-862f-e1f4c51f3470.png)
> 
> I'm facing that the Child Terms don't get the same id on translation, as the nav item just increments.
> 
> And moving /re-ording is buggy as stuff disappears.

Would you mind creating a new issue with minimal reproducible steps in a fresh Directus instance on the latest version (`9.18.1` as of now)? Thanks!

**Comment by Rar9** [comment]
I used your gui,  only the name and nav are under translation

https://github.com/directus/directus/issues/14378

**Comment by azrikahar** [comment]
> I used your gui, only the name and nav are under translation
> 
> #14378

I can see that you do have name and nav under translation, but I'm not sure I understand what do you mean in response to my request for a new issue with reproduction steps. Do you mean you were not able to reproduce it?

**Comment by rijkvanzanten** [comment]
> Why was this closed?

https://github.com/directus/directus/issues/14378#issuecomment-1181831617

The OP couldn't be reproduced and was deemed a node version mismatch.

> Child terms id don't match for translations
> Gui breaks on moving terms?

No idea what you mean, but please open a new issue detailing your setup and the problem you're running into 👍🏻

**Comment by Rar9** [comment]
Check out the screenshot I attached? 

Parent term has the same id 
Child term ids are only in the order the terms are created

Also Moving terms in one language will not sync the other language. 
![Screenshot-04-10-22-16-15-56-1](https://user-images.githubusercontent.com/2239608/195448688-4765dfe9-2a2b-4523-9d4d-c78c731c77a0.png)

**Comment by rijkvanzanten** [comment]
Please [open a new issue](https://github.com/directus/directus/issues/new?assignees=&labels=&template=bug_report.yml) detailing your setup and the problem you're running into 👍🏻
     ☝🏻 ☝🏻 ☝🏻
