### ISSUE TITLE
The dialog with folders, when moving file, does not scroll - not possible to move file

### ISSUE THREAD

**Issue by martinptacek** [directus/directus#14399]
### Describe the Bug

We have a large number of sub-folders in the file library. By default, any uploaded image is placed into the root. Then we move it to the right customer's subfolder. We have almost 100 subfolders and the dialog for selecting the folders does not seem to be able to handle that.

<img width="958" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/5970499/178483974-bea1f317-6a82-4b69-9ac7-f67728d5a1b9.png">
 

### To Reproduce

1. Create 50 subfolders in some folder in the file library section.
2. Upload a picture to the root folder.
3. Select this picture and click on the icon "Move"

You will see a dialog with long list of subfolders with no possibility to scroll.

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

16.15.1

### What database are you using?

Directus cloud

### What browser are you using?

Chrome

### How are you deploying Directus?

Directus cloud

**Comment by domdus** [comment]
Not ideal, but as temporary workaround you can add the following custom CSS in project settings:

`.folder-picker .v-list-group .items {
    overflow-y: overlay;
    height: 50vh;
}`

**Comment by martinptacek** [comment]
It works. Thanks!


S pozdravem,
Martin Ptacek


From: dw-minick ***@***.***>
Date: Saturday, 16 July 2022 21:05
To: directus/directus ***@***.***>
Cc: Martin Ptacek ***@***.***>, Author ***@***.***>
Subject: Re: [directus/directus] The dialog with folders, when moving file, does not scroll - not possible to move file (Issue #14399)

Not ideal, but as temporary workaround you can add the following custom CSS in project settings:

.folder-picker .v-list-group .items { overflow-y: overlay; height: 50vh; }
