### ISSUE TITLE
Conditional field stops working on CSV field

### ISSUE THREAD

**Issue by minyan-gu** [directus/directus#14392]
### Describe the Bug

On prior versions upto `9.12.2`, we can filter and display custom choices based on conditional rules set on the field (at least CSV typed field). 

However, it seems broken from `9.13.0` onwards and conditions are not applied anymore.

### To Reproduce

On `9.12.2`, we can
1. Create a test collection with any name.
2. Crate a string field called type, with 2 limited choices: `vegetable` and `fruit`.
![image](https://user-images.githubusercontent.com/49973259/178455953-f4ccd849-f460-4dba-bf9d-249994b55eae.png)
3. Create a CSV field, with empty choices by default []
![image](https://user-images.githubusercontent.com/49973259/178456223-ef5ce8cc-e34c-471f-b0b3-f8756e2c04b5.png)
4. and on `Conditions` tab, create a new rule as below
![image](https://user-images.githubusercontent.com/49973259/178456538-859e3b26-7a58-4509-89f9-4d2286f1d1d7.png)

Now goto create a new item, by default we should not see any choices:
![image](https://user-images.githubusercontent.com/49973259/178456762-b1836496-e02a-4e71-b73e-991955eef7f5.png)

and when change the dropdown `Type` to  `fruit`, we can see the underlying choices from step 4
![image](https://user-images.githubusercontent.com/49973259/178456900-895abc5b-9b3c-43a6-9848-52497dcd4011.png)

However, updating to `9.13.0`, we can only see the default error message `Choices configured incorrectly` and when we select the `fruit` on type field, we can no longer see the underlying choices
![image](https://user-images.githubusercontent.com/49973259/178457500-54e52bfa-85ad-4c71-8524-5a247491d71c.png)

### Errors Shown

No.

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

v16.15.1

### What database are you using?

Postgres 13.4

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by br41nslug** [comment]
related to #14285
