### ISSUE TITLE
Spell Check isn't working for markdown text field

### ISSUE THREAD

**Issue by bensonshaji** [directus/directus#14409]
### Describe the Bug

I was trying to create markdown note with some snippets but syntax highlight doesn't seem to be working in edit/preview mode.

<img width="1058" alt="Screenshot 2022-07-13 at 2 59 15 AM" src="https://user-images.githubusercontent.com/1668381/178599652-18da9d5f-03df-43c9-b912-cbf6d713eacf.png">

Default OS spell check isn't working when the field interface is set to markdown. Above screenshot is a reference. 
After a bit of digging found out CodeMirror uses spellcheck="false" by default. This may be causing the spell checks not to trigger.

https://github.com/codemirror/dev/issues/63#issuecomment-468644628 

I believe this option isn't set in directus either

### To Reproduce

1. Create a new Data 
2. Create a field
3. Select markdown in Text & Numbers
4. Enter a random keyname
5. Create Item with spelling errors and insert code snippet with standard markdown fenced code as per the screenshot

### Errors Shown

``` html
<textarea autocorrect="off" autocapitalize="off" spellcheck="false" tabindex="0" style="position: absolute; bottom: -1em; padding: 0px; width: 1000px; height: 1em; min-height: 1em; outline: none;"></textarea>
```

Spell check is false by default in DOM

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

v16.15.1

### What database are you using?

SQLite

### What browser are you using?

3.37.0

### How are you deploying Directus?

locally

**Comment by licitdev** [comment]
@bensonshaji The syntax highlighting within the markdown interface is unsupported as the languages used in code blocks needs to be parsed and imported dynamically. You may wish to submit the idea under discussions. Thank you.

**Comment by bensonshaji** [comment]
@licitdev That makes sense. Since it is not crucial to have syntax highlight while writing, it would be great to have highlights removed completely.  
In my opinion devs who configure markdown field type likes to offer their writers a clean and simple interface for best writing experience. Especially if that writing involves multiple line of code and showing it all in a shade of yellow/orange is not pleasing to the eye, either in dark/light mode. 
Disabling syntax highlight all together may be a cleaner experience if syntax highlight isn't present.

**Comment by licitdev** [comment]
@bensonshaji Agreed. Disabled the highlighting of fenced code block in the markdown interface. Thanks!

You are able to override the font colour via `Project Settings -> Custom CSS`.

### Example

```css
.cm-s-default .cm-comment {
	color: var(--foreground) !important;
}
```

**Comment by bensonshaji** [comment]
@licitdev Thanks for tip on override! I will change it right away :)
