### ISSUE TITLE
Cannot sort translated field even with default language set

### ISSUE THREAD

**Issue by miagg** [directus/directus#14419]
### Describe the Bug

On a collection with translations alias field, I cannot sort by translated field even with default language set.
If I add the same column using relationship ordering does appear, but throws an error if you sort in any direction.

https://user-images.githubusercontent.com/6439071/178770215-5d9a09f2-c495-44f4-aaa0-91ddc695e512.mp4

### To Reproduce

1. Add a translations alias field to a collection and set default language id
2. Add an entry to the collection
3. Try to sort translations in index page (disabled)
4. Try to add the sortable field through relation and sort (throws error)

### Errors Shown

```
code: "INTERNAL_SERVER_ERROR"
message: "select \"glossaries\".\"id\" from \"glossaries\" order by \"efatt\".\"term\" desc limit $1 - missing FROM-clause entry for table \"efatt\""
```

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

16.5.1 (LTS)

### What database are you using?

Postgres

### What browser are you using?

Google Chrome

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
This makes sense, as `translations` (and thus any nested value from `translations`) is an array of values, not a single value. This makes it impossible to sort on, as there isn't a single value to compare against (also see https://github.com/directus/directus/issues/12271). That being said, that error shouldn't be thrown, as the API shouldn't try that query 👍🏻

**Comment by miagg** [comment]
Am I missing an alternative way to do it? How would one sort a translated field by a specific language? I thought that's why default language exists on the alias field.

**Comment by miagg** [comment]
> So just for my own understanding, are you trying to sort glossary items by the translated value in a given language?

Yes exactly that. Content editors need a way to sort. It just came to me that I can use the helper table glossary_translations which is hidden by default, but I wish there was a better way.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-228](https://linear.app/directus/issue/ENG-228/cannot-sort-translated-field-even-with-default-language-set)
