### ISSUE TITLE
generateJoi error when creating a new role

### ISSUE THREAD

**Issue by azrikahar** [directus/directus#14413]
### Describe the Bug

When creating a new role, the subsequent `/permissions` POST request will return error with the message `[generateJoi] Filter doesn't contain field key. Passed filter: {}`. (More detailed error in **Errors Shown** section below). However the role seems to be created fine after doing a browser refresh:

https://user-images.githubusercontent.com/42867097/178679910-426d0495-1f7c-4ab3-90fa-4f81a3e6da61.mp4

### To Reproduce

1. Create a new role
2. Observe the `/permissions` POST request returning error 500 and the error dialog appeared

### Errors Shown

Error shown in terminal for the failed `/permissions` POST request:

```
15:37:31 🚨 [generateJoi] Filter doesn't contain field key. Passed filter: {}
Error: [generateJoi] Filter doesn't contain field key. Passed filter: {}
    at generateJoi (C:\Users\Azri\Documents\Projects\directus\packages\shared\dist\cjs\utils\generate-joi.js:74:15)
    at passesFilter (C:\Users\Azri\Documents\Projects\directus\api\src\utils\filter-items.ts:33:30)
    at C:\Users\Azri\Documents\Projects\directus\api\src\utils\filter-items.ts:22:12
    at Array.every (<anonymous>)
    at passesFilter (C:\Users\Azri\Documents\Projects\directus\api\src\utils\filter-items.ts:21:21)
    at C:\Users\Azri\Documents\Projects\directus\api\src\utils\filter-items.ts:12:10
    at Array.filter (<anonymous>)
    at filterItems (C:\Users\Azri\Documents\Projects\directus\api\src\utils\filter-items.ts:11:15)
    at PermissionsService.readByQuery (C:\Users\Azri\Documents\Projects\directus\api\src\services\permissions.ts:50:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
15:37:31 ✨ request errored POST 500 /permissions 9.2s
```

### What version of Directus are you using?

9.14.1 (Main branch https://github.com/directus/directus/commit/b1585e0556dfc6596105a9ef5336c6880dc15e65)

### What version of Node.js are you using?

16.15.1

### What database are you using?

PostgreSQL 13.4, SQLite 3.38

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally in dev

**Comment by azrikahar** [comment]
It should be because of when the permissions is read during the POST request (after create):

https://github.com/directus/directus/blob/b1585e0556dfc6596105a9ef5336c6880dc15e65/api/src/controllers/permissions.ts#L34

It then uses the `filterItem` util:

https://github.com/directus/directus/blob/b1585e0556dfc6596105a9ef5336c6880dc15e65/api/src/services/permissions.ts#L68-L74

Which calls `generateJoi` here:

https://github.com/directus/directus/blob/b1585e0556dfc6596105a9ef5336c6880dc15e65/api/src/utils/filter-items.ts#L32

Since the permissions passed are an empty object `{}`, the "doesn't contain field key" error is thrown.

---

In the recent `isAllowed` util added in #13596, there is a check with `Object.keys().length === 0` to return early when it is an empty object:

https://github.com/directus/directus/blob/b1585e0556dfc6596105a9ef5336c6880dc15e65/app/src/utils/is-allowed.ts#L32-L34

So possibly this is the fix? I tried adding a similar logic, `if (Object.keys(filter).length === 0) return true;` right before the generateJoi in filterItems:

https://github.com/directus/directus/blob/b1585e0556dfc6596105a9ef5336c6880dc15e65/api/src/utils/filter-items.ts#L32

And it seems to resolve the issue:

https://user-images.githubusercontent.com/42867097/178680242-268d2d79-6c34-4565-ae98-9e12097c3293.mp4

**Comment by licitdev** [comment]
>  I tried adding a similar logic, `if (Object.keys(filter).length === 0) return true;` right before the generateJoi in filterItems

@azrikahar Yes that should be the solution. generateJoi should be skipped when the filter is `{}` as there is nothing to filter on. 👍🏼
