### ISSUE TITLE
Flows: Operation "request" does not pass error information/data 

### ISSUE THREAD

**Issue by phihu** [directus/directus#14415]
### Describe the Bug

I stumbled across this behavior trying to pass additional information along with an error and could not retrieve it. 

In case of an error the flow's logs show an (axios) error but the payload (incl. headers, message etc.) consists of the original request's data, not the error's response.

File: `directus/api/src/operations/request/index.ts` :

Perhaps - unfortunately I can't test it myself right now :/ - this is (simply) due to a missing try/catch block.

A request is made without catching possible errors, thus loosing all additional error information/data from the server the request went to:

```typescript
...
  handler: async ({ url, method, body, headers }) => {
    const customHeaders = headers?.reduce((acc, { header, value }) => {
      acc[header] = value;
      return acc;
    }, {} as Record<string, string>);

    const result = await axios({ url, method, data: body, headers: customHeaders });

    return { status: result.status, statusText: result.statusText, headers: result.headers, data: result.data };
  },
...
```

If so, it could be solved by adding the try/catch block and passing the error's information/data: 

```typescript
...
  handler: async ({ url, method, body, headers }) => {
    const customHeaders = headers?.reduce((acc, { header, value }) => {
      acc[header] = value;
      return acc;
    }, {} as Record<string, string>);

    try{
      const result = await axios({ url, method, data: body, headers: customHeaders });
      return { status: result.status, statusText: result.statusText, headers: result.headers, data: result.data };
    } catch(error) {
      return { status: error.response.status, statusText: error.result.statusText, headers: error.response.headers, data: error.response.data };
    }
  },
...
``` 

This would be analog to the [Axios Docs (Error Handling)](https://axios-http.com/docs/handling_errors)

And last but not least: Thank you so much for your great work, Directus really is an amazing project! 

### To Reproduce

Add a 'request' operation to a flow, that makes a request to a script and within that script (in my case a custom endpoint extension) return an error with additional data.

For example (within a custom endpoint extension), something like the following (js):

```js
  export default (router, context) => {
    return router.get('/', (req, res) => {
      return res.status(400).send('A custom error message');
    }
  }
```

Even if you add additional custom headers, json etc. to the response, the problem remains the same: The flow's logs will only show the original requests data in the payload. The additional data (in this case the message 'A custom error message') is nowhere to be found. 

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

v17.8.0

### What database are you using?

SQLite

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by nickrum** [comment]
There is no try-catch-block because the flows manager will call the operation connected to the `reject` anchor of the current operation whenever an error is thrown. In that case it will use the thrown error as the data returned by the operation. So I think this is actually working as intended.

**Comment by zeel-pathak** [comment]
Ohh! I see, I was so excited and curious for contributing that I didn't thought about it.

Thanks @nickrum

**Comment by phihu** [comment]
I might be completely wrong, of course, but I doubt that the operation works as supposed, unfortunately I doubt my suggestion works, neither - and I can't properly debug/test it right now :(

Within the operation there is the `result` object (incl. `result.status` etc) and in case of an error, the `error` object that has itself a `response` property `error.response` (incl. `error.response.status` etc).

I set up a minimal endpoint extension:

```javascript

export default (router, context) => {
   return router.get('/', (req, res) => {
        return res.status(403).send({error: 'CUSTOM ERROR'});
   })
}

```
(BTW, alternatively, I also tried `return res.status(403).send('CUSTOM ERROR');`,  `return res.status(403).send(new Error('CUSTOM ERROR'));` - same result.)

I set up a simple flow:

![flow](https://user-images.githubusercontent.com/1455315/178832716-e7a6e267-a6b3-48f4-a5ff-be2bd048752d.png)

Triggering the flow, the request failed (as expected) calling the logger operation.
The logs then only show the axios error including the _original request_ but without the server's (error) response (incl. the 'CUSTOM ERROR' or any other data):

```json
{
  "message": "Request failed with status code 403",
  "name": "AxiosError",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": {},
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/json",
      "User-Agent": "axios/0.27.2",
      "Content-Length": 1123
    },
    "url": "http://0.0.0.0:8055/kfrm",
    "data": "{\"path\":\"/trigger/c3b52322-9933-4fd1-b918-8ea472dff0e0\",\"query\":{},\"body\":{\"collection\":\"test\",\"keys\":[1]},\"method\":\"POST\",\"headers\":{\"host\":\"0.0.0.0:8055\",\"connection\":\"keep-alive\",\"content-length\":\"32\",\"accept\":\"application/json, text/plain, */*\",\"cache-control\":\"no-store\",\"authorization\":\"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhjZTMwNzhlLTI0MTYtNDJhMC1hNGQ1LTRjNzlkYzFiMTAwYyIsInJvbGUiOiI2YWU2ZjNhOS1kZDYxLTQ2ZDAtOTBkZS03ZmU1Mzk0M2ZjNzgiLCJhcHBfYWNjZXNzIjoxLCJhZG1pbl9hY2Nlc3MiOjEsImlhdCI6MTY1Nzc0NTU4NywiZXhwIjoxNjU3NzQ2NDg3LCJpc3MiOiJkaXJlY3R1cyJ9.4IgoB7RDFN3JmZZsSBpiKVytrrewxiamnvhli5eSp-I\",\"user-agent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36\",\"content-type\":\"application/json\",\"origin\":\"http://0.0.0.0:8055\",\"referer\":\"http://0.0.0.0:8055/admin/content/test\",\"accept-encoding\":\"gzip, deflate\",\"accept-language\":\"de,en-US;q=0.9,en;q=0.8,ko;q=0.7,nl;q=0.6,fr-CH;q=0.5,fr;q=0.4,zh;q=0.3,zh-HK;q=0.2,ja;q=0.1,de-DE;q=0.1\",\"cookie\":\"directus_refresh_token=bXKo9Ct9GLTcAjMNCT6_q7tV9RoMf8P6NcAbcTkmbLsv4E8VWaT_6figASisK44I\"}}",
    "method": "get"
  },
  "code": "ERR_BAD_REQUEST",
  "status": 403
}
```
I would expect the actual server error response data to be found somewhere or am I wrong...?

And again: Thank you so much for all your work!!!

**Comment by piotr-cz** [comment]
You may try with Hook extension, as here: https://github.com/directus/directus/discussions/9930#discussioncomment-4303384

**Comment by rijkvanzanten** [comment]
Linear: [ENG-229](https://linear.app/directus/issue/ENG-229/flows-operation-request-does-not-pass-error-informationdata)
