### ISSUE TITLE
Insights 2: Metric Panel - aggregate Count (Distinct) improperly disabled

### ISSUE THREAD

**Issue by claytongulick** [directus/directus#14420]
### Describe the Bug

Line 115 of panels/metric/index.ts is:

```
{
	text: 'Count (Distinct)',
	value: 'countDistinct',
	disabled: !fieldIsNumber.value,
},
```

This improperly causes the count distinct aggregation to be greyed out for non-numeric values, there's no need for the value to be numeric to do a distinct count.

Logging this here, I'll do a PR when I get a second.

There's currently a workaround, where the aggregate function can be selected before the field is selected - which is another problem - but allows it to work for now.

### To Reproduce

Add a metric panel to an insights dashboard
Select a non-numeric field
Count (Distinct) is incorrectly disabled

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16.14.2

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

local

**Comment by azrikahar** [comment]
Good catch. A similar fix was added to time-series via field conditions in #13479, but the approach can probably be different since there's a computed fieldIsNumber here already.
