### ISSUE TITLE
LDAP Login isn't shown when default provider is disabled

### ISSUE THREAD

**Issue by MiniDigger** [directus/directus#14428]
### Describe the Bug

if you set `AUTH_DISABLE_DEFAULT` to `true` and define an LDAP `AUTH_PROVIDER`, the login form will be empty.

this is caused by `driver` never being assigned to the ldap value: https://github.com/directus/directus/blob/64acd2fdb32103761b7f8ed1a195ef4412db00cc/app/src/routes/login/login.vue#L52

before, on setup, `providerOptions` would always be set, calling the computed which sets the `driver` var, in this refactor, `providerOptions` is just fetched from store and the `providerSelect`, which now sets the `driver` var, is never called now, leaving it to `local`, which is disabled, leaving me with no login form at all :/

https://github.com/directus/directus/commit/1a1c784ebd5e2883c4b781c6e8b483bd038b3ede#diff-58ad84885be031697a2831aca0d9c9b89cf346514329fad9b6540bc24e02e017L86

(I wanted to PR this fix, cause its so simple, but I can't get my dev env to work right now, so its easier to just file an issue...)

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

16

### What database are you using?

postgres

### What browser are you using?

edge

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
An easier way to reproduce it is to setup a non-default `default`-based auth:

```
AUTH_DISABLE_DEFAULT="true"
AUTH_PROVIDER="example"
AUTH_EXAMPLE_DRIVER="default"
```

(saved myself an hour finicking with local LDAP servers)
