### ISSUE TITLE
Dirty translations interface after emptying edits

### ISSUE THREAD

**Issue by licitdev** [directus/directus#14427]
### Describe the Bug

The translations interface remains dirty after the edit is cleared

### To Reproduce

https://user-images.githubusercontent.com/26413686/178969237-6fbec586-00ad-4a54-a889-2db7d985ef85.mov

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

v16

### What database are you using?

SQLite

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
Linked fix #15111 caused other issues and was reverted in https://github.com/directus/directus/pull/15337
