### ISSUE TITLE
M2A showing not requested fields

### ISSUE THREAD

**Issue by joselcvarela** [directus/directus#14434]
### Describe the Bug

When requesting a specific field within M2A collection, it properly returns that field for that collection but also return all fields for other collections, although they were not asked.

### To Reproduce

Make the following request on the attached SQLite database:
http://localhost:8055/items/article_content?access_token=lwXx2LL7uZp03MwvA4QsmhnqmnWFTm64&fields[]=content.item:articles.content

You should see something like this:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/14039341/179036483-7cd1d282-e6a7-4633-8b27-c6af7aad94b5.png">

Database:
[m2a-issue.sqlite.zip](https://github.com/directus/directus/files/9113743/m2a-issue.sqlite.zip)

### What version of Directus are you using?

directus/directus:9.14.1

### What version of Node.js are you using?

directus/directus:9.14.1

### What database are you using?

SQLite

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker => directus/directus:9.14.1

**Comment by rijkvanzanten** [comment]
This is because the `item:<collection>` call for the other collections still defaults to `*`

**Comment by rijkvanzanten** [comment]
Linear: [ENG-227](https://linear.app/directus/issue/ENG-227/m2a-showing-not-requested-fields)

**Comment by Nitwel** [comment]
What would the expected return value be, only showing the id of the item like so?
```json
{
  "data": [
    {
      "content": [
        {"item": {"content": "Article 1"}},
        {"item": {"content": "Article 2"}},
        {"item": 1},
        {"item": 2},
      ]
    }
  ]
}
```

**Comment by joselcvarela** [comment]
That could be a way, but as user I would expect only `article` items to be retrieved since I only asked for `:article.content`.
So the answer I expected would be:
```json
{
  "data": [
    {
      "content": [
        {"item": {"content": "Article 1"}},
        {"item": {"content": "Article 2"}},
      ]
    }
  ]
}
```

This is what I expected the response to be, but since M2A is a complex field it may also work different

PS: I don't remember correctly but I think this was also reported by a Cloud user at that time.

**Comment by Nitwel** [comment]
I'm not sure if we would want to add filter logic to the fields param. This would leave you thinking that there are only 2 items in content even though there are 4. And if you want to restrict from certain collections from not showing up, you can easily do that with a deep filter.

I think the best way is to do the same behaviour when we don't specify any collection at all:
`http://localhost:8055/items/m2a/1?fields=m2a.item.name_b` returns
```json
{
    "data": {
        "m2a": [
            {
                "item": {}
            },
            {
                "item": {
                    "name_b": "aaww"
                }
            },
            {
                "item": {}
            }
        ]
    }
}
```
where `http://localhost:8055/items/m2a/1?fields=m2a.item:b.name_b` returns
```
{
    "data": {
        "m2a": [
            {
                "item": {
                    "id": 2,
                    "name_a": "aa",
                    "tags_a": null
                }
            },
            {
                "item": {
                    "name_b": "aaww"
                }
            },
            {
                "item": {
                    "id": 1,
                    "name_c": "ggg",
                    "toggle_c": true
                }
            }
        ]
    }
}
```
