### ISSUE TITLE
One-To-Many with multiples "Ones" not working

### ISSUE THREAD

**Issue by abenz1267** [directus/directus#14449]
### Describe the Bug

Let's say i have the following relations:

- A
- B
- C

Now B has a One-To-Many to A and C has a One-To-Many to A.

I think this should be possible when using UUIDs as keys, as there can't be a conflict.

Directus says the relationship for C to A has been misconfigured.

Regards

### To Reproduce

See bug description

### Errors Shown

See bug description

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

14.19.3

### What database are you using?

sqlite

### What browser are you using?

chrome

### How are you deploying Directus?

local

**Comment by azrikahar** [comment]
Would you mind sharing more detail on where exactly did the `the relationship for C to A has been misconfigured` appear? I assume in collection C's page when creating/viewing an item? I can't seem to replicate this issue on my end:

https://user-images.githubusercontent.com/42867097/179195173-6f7c4118-77fb-41aa-867f-cbc40b2fecaa.mp4

**Comment by abenz1267** [comment]
Yeah, the error appears when trying to add A to C. Also when i open the field settings where you can also set "sorting field" etc. via the "relationship" tab, the "relationship" tab straight away doesn't exist.

**Comment by azrikahar** [comment]
> Yeah, the error appears when trying to add A to C.

Can you share what are the differences in my steps when adding the `o2m_a` field (A) to C, compared to what you tried?

It'd also be helpful if you can share the sqlite file here as well (may need to zip it as GitHub don't allow uploading `.db` or `.sqlite` files)

**Comment by abenz1267** [comment]
[data.db.zip](https://github.com/directus/directus/files/9120114/data.db.zip)

This is the complete database. I've created a user for you: directus@github.com, password is "12345678"

The affected collection is "PriceContainer" and the field is "actions".

**Comment by azrikahar** [comment]
Thanks for sharing. I can confirm what you described and it seems like there isn't a relevant relation in `directus_relations`, hence the field indeed has no relationship configured.

> Can you share what are the differences in my steps when adding the o2m_a field (A) to C, compared to what you tried?

In the case of my example but with your context in mind, were you doing anything different? Could it be the foreign key setup?

> The affected collection is "PriceContainer" and the field is "actions".

What were the related collection and foreign key you had selected when creating the "actions" field? For foreign key, did you manually type in a new key or selected an existing field?

**Comment by abenz1267** [comment]
I've setup the foreign key when creating the field for B. So i manually typed in the field and called it "parent". And when setting the relation for C i simply selected "parent". As i assume this shouldn't really be a problem using UUIDs.

**Comment by azrikahar** [comment]
Thanks for clarifying 👍 I do believe the main thing is when we have the following scenario:

- Collection `A`
- Collection `B` with O2M field using a new foreign key called `parent` to collection `A`
- Collection `C` with O2M field using the **same** foreign key above, `parent`, to collection `A`

The O2M field in collection `C` will display this odd behavior. I do wonder is there a better way to approach such use case though, if it's applicable. @rijkvanzanten thoughts on this scenario here?

**Comment by rijkvanzanten** [comment]
> - Collection B with O2M field using a new foreign key called parent to collection A
> - Collection C with O2M field using the same foreign key above, parent, to collection A

This isn't currently supported, as you're trying to mix different types in the same one to many. What you're describing here is effectively the "reverse" of a many-to-any field, where the foreign key is the composite of both the `collection` and `item` field (or in this case `parent` combined with a missing "source collection" field).

This is an open feature request tracked in https://github.com/directus/directus/discussions/4749, so please give that an upvote 🙂
