### ISSUE TITLE
Can create users without email when there is field validation for email

### ISSUE THREAD

**Issue by martinomg** [directus/directus#14441]
### Describe the Bug

Directus is allowing me to create user without an email, also is not considering filters. 

### To Reproduce

Here's the screenshot of the accepted request. It also doesn't show me any of the fields i added in the params.

![accepted_request](https://user-images.githubusercontent.com/5248081/179117857-1caf9e28-d3ac-4701-ad83-8dbe4b5c7054.jpg)

Here's the list of users without email
![duplicated_users](https://user-images.githubusercontent.com/5248081/179117939-5e7175b2-1024-46ec-ad05-5edca77f78d0.jpg)

The rule to avoid duplicated emails is working fine
![avoid_duplication_working](https://user-images.githubusercontent.com/5248081/179118024-8f51f3ab-475b-4439-965f-0dcf88a934ee.jpg)

### Errors Shown

I tried to add custom field validation and is also not working
![field_validation](https://user-images.githubusercontent.com/5248081/179117988-d357ee4b-b98e-422a-95f8-8f98426f099d.jpg)

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

14.16.0

### What database are you using?

MySQL / MariaDB / Percona 10.3.34

### What browser are you using?

Chrome

### How are you deploying Directus?

Self Hosted, Ubuntu + plesk

**Comment by aidenfoxx** [comment]
Context for why email requirement isn't the default:

>The general users API doesn't require email. This is to support providers that may not provide an email (LDAP, OAuth etc.). At one point it was even possible to log in without an email for the default login by specifying an alternative identifier, but this was removed.
>
>Adding an email requirement in code would require hardcoded logic specific to "local" provider types, which may or may not be worth it.

I can't speak for why "Field Validation" wouldn't work to solve this, however.

**Comment by martinomg** [comment]
@aidenfoxx thank you for your answer. It certainly wasn't something i was too worried because form validation solves most of the cases, but it caught my attention the problem with the field validation, that's mainly why i reported this as a bug. Also there is no user object returned unless i activate all the read permission for the public role. 

![image](https://user-images.githubusercontent.com/5248081/179241816-7a1f0d91-b413-4ac4-b26c-d64bcc7299ba.png)

I was expecting to get something like this from the response 
![image](https://user-images.githubusercontent.com/5248081/179242565-d5ccb609-3f28-402c-b923-5b48c242ff6b.png)

The interface is a bit confusing because in all the other collections, the filter tab is clean, and the directus_users one shows this message

![image](https://user-images.githubusercontent.com/5248081/179245979-77f4eeec-11a1-481e-9e81-6ed96cd70f7b.png)

I tried the dynamic variable $CURRENT_USER but it doesn't make sense for it to work, because as there is no token involved there is no current user. Is not a big deal because if the register request is ok i just chain it to the /auth/login endpoint and get all the right data. If there would be a dynamic variable to solve this i think it could be something like $ON_CREATE to only be readable if it's in a create/insert context, something as a one time condition filter. 
When i switch the Read permissions to **'All Access'** i can see all the data i requested in the query params, but as a public visitor i don't want all the users to be able to request the user list.

**Comment by azrikahar** [comment]
> If there would be a dynamic variable to solve this i think it could be something like $ON_CREATE to only be readable if it's in a create/insert context, something as a one time condition filter.

I believe #14887 should somewhat be related to this use case!

That being said, turns out this "field validation not working for user creations" issue is the same as #14296, so let's track this over there 👍
