### ISSUE TITLE
Insight - Adding list panels with date filters containing dynamic variables will crash the API

### ISSUE THREAD

**Issue by mmmaxxxe** [directus/directus#14480]
### Describe the Bug

Adding two list panels of the same collection an the app, with date filters crashes directus (504 or 503 errors)

### To Reproduce

Add a couple of panels in a dashboard
add TWO LIST panels of the very same collection and withs different date filter (to me, first with date >= $NOW and second with date > $NOW)
Save the dashboard
New panels are not saved and/or directus crashes returning 503 or 504

  

### Errors Shown

503/504

### What version of Directus are you using?

9.13 - cloud

### What version of Node.js are you using?

directus cloud

### What database are you using?

directus cloud (postgres?)

### What browser are you using?

Chrome, brave, firefox

### How are you deploying Directus?

cloud

**Comment by azrikahar** [comment]
@mmmaxxxe just to confirm, do you mean Standard/Enterprise or Community cloud?

Granted the 503/504 errors are cloud specific (in which case we do highly recommend reaching out via the live chat as the main channel of communication), I do believe this error in this case does pertain to Directus.

---

Alternative steps to reproduce:

- Create a collection called `metrics`
  - Add an integer field called `value`
  - Add a timestamp field called `timestamp`
- Add some dummy data to said collection spread across few days ago from now
- Create a dashboard, create a list panel in it
   - collection: `metrics`
   - display template: `{{id}}`
   - filter: `timestamp` greater than a specific value/timestamp
- Observe that it works. Now add a change the `timestamp` filter to use dynamic variable, such as `$NOW(-2 day)`
- The graphql request returns error in terms of HTTP 200 (which is expected), but it seems to cause some underlying issues. In PostgreSQL, it seems to make the API unresponsive, hence the subsequent `/page` PATCH request (after we close the panel drawer) fails. As for SQLite, it does also error but the API doesn't crash or get unresponsive.

**Comment by mmmaxxxe** [comment]
My Directus Cloud is standard.
And that's correct, filters with dates and dynamic variables seems not working, even on app filters.
