### ISSUE TITLE
Database with dates "0000-00-00 00:00:00" throws "Invalid time value"

### ISSUE THREAD

**Issue by RihanArfan** [directus/directus#14497]
### Describe the Bug

I'm using Directus to add a REST API to an existing database, which another software uses. This 3rd party closed source software sets certain MySQL timestamp fields to `0000-00-00 00:00:00` instead of null, like updated_at, which is causing errors with Directus.

### To Reproduce

Set MySQL timestamp field to `0000-00-00 00:00:00` and try and view via Directus UI or REST API (`/items/:collection`).

### Errors Shown

When trying to view from Directus UI or via REST, I get the error "Invalid time value".
```json
{
	"errors": [
		{
			"message": "Invalid time value",
			"extensions": {
				"code": "INTERNAL_SERVER_ERROR"
			}
		}
	]
}
```
```
21:21:09 🚨 Invalid time value 
RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at PayloadService.processDates (/directus/node_modules/directus/dist/services/payload.js:237:86)
    at PayloadService.processValues (/directus/node_modules/directus/dist/services/payload.js:142:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (/directus/node_modules/directus/dist/database/run-ast.js:42:21)
    at async runAST (/directus/node_modules/directus/dist/database/run-ast.js:30:16)
    at async ItemsService.readByQuery (/directus/node_modules/directus/dist/services/items.js:216:25)
    at async /directus/node_modules/directus/dist/controllers/items.js:70:18
```

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

16

### What database are you using?

MariaDB 10.7.3

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker - directus/directus:latest@sha256:24873256aab33da71340c02b3c00b1ae4cbb8563dfeabd89458461e576b1357c

**Comment by azrikahar** [comment]
I think this is a slightly odd case, as MySQL itself does not allow such value by default (Ref: https://github.com/directus/directus/issues/11676#issuecomment-1050654538), so I'm not sure about this presumption of inserting `0000-00-00 00:00:00` as timestamp values. Unless of course that check is intentionally disabled.

This is further confirmed when trying to run the same statement ``INSERT INTO `test` (`timestamp`)
VALUES ('0000-00-00 00:00:00');`` in both databases, where it fails in MySQL yet succeeds in MariaDB, at least from their respective out-of-the-box docker images.

|MySQL 8.0.29|MariaDB 10.8.3|
|---|---|
|![chrome_Ly5XCmE7l6](https://user-images.githubusercontent.com/42867097/179670111-122d7ddc-e318-453e-add3-fd654b1c4a05.png)|![chrome_HlG1or2BNF](https://user-images.githubusercontent.com/42867097/179670137-79f1c770-afcc-4377-9b76-39a6cc465546.png)|


---

With that said, technically the logic here should probably be tweaked:

https://github.com/directus/directus/blob/3770661bde1dffe02b503f3be488fcf43272fb02/api/src/services/payload.ts#L288-L295

as when line 289 tries to do `new Date("0000-00-00 00:00:00")`, `value` will become an invalid date, hence the attempt to do `.toISOString()` in line 293 throws the "Invalid time value" error.

**Comment by jirisykora83** [comment]
Seems like same apply for postgress
