### ISSUE TITLE
Nested forms get out of sync on unset

### ISSUE THREAD

**Issue by jacobrienstra** [directus/directus#14495]
### Describe the Bug

I think this is a separate problem that was revealed #13574, though it fixed one problem, I'm afraid it's created another.

I edit a field on a related item and then edit it back to its original value, the form will `unset` that field, because the field now matches the `initialValue`.

After saving, those changes bubble all the way up and then come back down, but since we're using the `use-relation-multiple _value` as the single source of truth, that field is no longer there and therefore is missing in the rendered template display, even though it remains set on the actual item.

### To Reproduce

Create a Collection 1. Add some input fields.
Create a related Collection 2. Add some input fields.
Attach C2 as an M2M field on C1. In the interface options, make the render template use the C2 input fields.

Create an item on C1, and attach/create a few connected C2 items. Save. 
Now open C1 item. Click on existing C2 item in M2M interface. Click on an input field, then tab out. Click save. 

The affected input field should disappear from the render template in the list of C2 items.

https://user-images.githubusercontent.com/10411238/179609777-f58613fb-3c9f-4b07-a246-22fae26339c6.mov

I've thought a lot about this and think the problem is 2-fold:

1. The `render-template` depends on the `DisplayItem`, which is also being used as `editsAtStart/modelValue` of the edit related item form. But I think those ideally should be separated, so the `render-template` can use a merged object of initialValues and `DisplayItem` values. Otherwise the form starts with any fields required for the `render-template` marked as edited because they're present in the `modelValue`. That's why the value disappears on the template—it doesn't have any fallback values like the form does.

2. `unset` in nested forms. So I _think_ what's happening here is that in a single-level form, the data really only has to go up to the base form and then get posted. So unsetting a field is just fine—the form won't post any updates to that field, and the field itself is the source of truth, so there's nothing else to keep in sync. 
But in a nested form, the data has to bubble up and then come all the way back down. If a field emits and is then unset by its parent `form-field`, the value emitted on the way up has cleared that field key, which means on the way down nothing actually changes, and the data gets out of sync. 

Does that seem right?

I think the solution could be using the `nested` prop on forms and passing it to the `form-field`s, and checking that before unsetting fields, ensuring anything emitted is passed all the way up. I think the main reason to use the `unset` feature is to disable saving when there are no new changes, but that isn't being done on relational forms anyway. We could do that as well, but we'd still need to always emit values, even if they're redundant to the initial values, because they need to be passed back down to render elements.

### Errors Shown

Nope

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

16.14.2

### What database are you using?

postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
I think this ties back to a bigger conversation around the structuring, organization, performance, and ideal setup of the whole (nested) v-form system. @AustinPhillipTaylor did a great write-up on everything that's going on currently in https://github.com/directus/directus/discussions/13627 with some recommendations on how to improve it. I'd love to hear your thoughts on that as well

**Comment by jacobrienstra** [comment]
Oh yes that would absolutely solve this problem. 100% behind a store-based approach
