### ISSUE TITLE
Editing a hyperlink in WYSIWYG doesn't enable Save button

### ISSUE THREAD

**Issue by bcartier** [directus/directus#14535]
### Describe the Bug

Adding or removing a link triggers marks the WYSIWYG field as modified, but editing the URL if the linked text using the Link feature does not. You have to make another change in the text to be able to save.

### To Reproduce

1. Create a collection with a WYSIWYG field
2. Create an example item and populate the WYSIWIG field with text
3. Select some of the WYSIWYG text and use the Link button create a link (let's say to https://www.google.com/search?q=directus)
4. Save the Item
5. Edit that same item and change the URL to https://www.google.com/search?q=directus+cloud)
6. Notice that even though the WYSIWYG markup has changes, you can't save the Item, and the WYSIWYG field is not marked as  "modified" (the small dot next to the field label doesn't appear)

### Errors Shown

None

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

16.16.0

### What database are you using?

MySQL

### What browser are you using?

Chrome

### How are you deploying Directus?

docker

**Comment by rijkvanzanten** [comment]
Closing this for now, as I believe it's resolved. We'll reopen if the problem persists in the next release
