### ISSUE TITLE
Bad Gateway 502 and 503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by sebastiansmithomm** [directus/directus#14548]
### Describe the Bug

Hello - we are getting sporadic errors when trying to update content.
![image](https://user-images.githubusercontent.com/74179584/180181054-f2ac975d-64e3-4895-b332-e68aa1952042.png)

### To Reproduce

Update any content.

### Errors Shown

![image](https://user-images.githubusercontent.com/74179584/180181111-de9d14b0-d15f-44b0-a969-ec6c4f6e0a9e.png)

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

16.15.1

### What database are you using?

Not sure - using Directus Cloud

### What browser are you using?

chrome

### How are you deploying Directus?

PaaS

**Comment by br41nslug** [comment]
This does not seem related to the Directus core platform but rather a cloud hosting issue. For cloud support you can reach out using the chat panel on the cloud dashboard [directus.cloud](https://directus.cloud/)
