### ISSUE TITLE
Wrong query when using nested filter in M2A context

### ISSUE THREAD

**Issue by checco700** [directus/directus#14564]
### Describe the Bug

There is user_details which has an M2A relationship with people (junction user_details_user_details_people).
people has an M2M relationship with job (junction table people_job).
people has an job_name.
people_job has job_id.

### To Reproduce
```
/items/user_details_user_details_people?filter={
   "_and":[
      {
         "item:people":{
            "job_name":{
               "job_id":{
                  "_eq":"uuid"
               }
            }
         }
      }
   ]
}
```
### Errors Shown
```
{
    "errors": [
        {
            "message": "select \"user_details_user_details_people\".\"id\", \"user_details_user_details_people\".\"user_details_id\", \"user_details_user_details_people\".\"collection\", \"user_details_user_details_people\".\"item\" from \"user_details_user_details_people\" left join \"people\" as \"mblae\" on \"collection\" = $1 and \"user_details_user_details_people\".\"item\" = CAST(\"mblae\".\"id\" AS CHAR(255)) where (\"people_job\".\"job_id\" = $2) order by \"user_details_user_details_people\".\"id\" asc limit $3 - missing FROM-clause entry for table \"people_job\"",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}
```
### What version of Directus are you using?

9.10.0

### What version of Node.js are you using?

16.14.2

### What database are you using?

Postgres 13.3

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by licitdev** [comment]
Hi @checco700, please assist to test whether this issue persists on the latest version of Directus. I will be closing this issue for now. 
Thank you.

**Comment by checco700** [comment]
Hi, I just tested with 9.14.3 and got the same error. Could you reopen the bug? 
Thank you

**Comment by lubrst** [comment]
Got the same error with 9.16.1

**Comment by azrikahar** [comment]
Ref https://github.com/directus/directus/pull/15162#pullrequestreview-1097623601 for another example of reproducing this error.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-223](https://linear.app/directus/issue/ENG-223/wrong-query-when-using-nested-filter-in-m2a-context)
