### ISSUE TITLE
9.14.3 breaks assets paths when serving Directus from a subfolder (Apache)

### ISSUE THREAD

**Issue by christianrr** [directus/directus#14565]
### Describe the Bug

Up to version 9.14.1 serving Directus from a subfolder on Apache was working fine with the config from below.
On 9.14.3 the assets paths seems to be broken as the subfolder is now attached twice in the assets URL:
```
https://my.domain.com/cms/cms/assets/49857276-fb24-4db3-a808-6954becbb936
```

### To Reproduce

1. Create Directus instance and serve from subfolder in Apache

```
ProxyPreserveHost On
ProxyPass /cms http://127.0.0.1:8055
ProxyPassReverse /cms http://127.0.0.1:8055
```
.env
```
PORT=8055
HOST=localhost
PUBLIC_URL="https://my.domain.com/cms/"
```

2. Upload image and check path in network console 

### What version of Directus are you using?

9.14.3

### What version of Node.js are you using?

16

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
Directus' url construction relies on the `/admin` part in the path to know what the root URL is in the app, so did this configuration ever work before? 🤔

**Comment by rijkvanzanten** [comment]
Also, where are you seeing the wrong URL being used?

**Comment by br41nslug** [comment]
I was able to reproduce this on a running Apache server using the provided vhost and environment settings.
This seems to be happening globally across the app for images, i've seen it at: 
- files overview
- files detail
- user avatars
- image m2m
The urls being generated look like `http://[redacted]/cms/cms/assets/bea39707-b876-463a-8dfd-7aed80ab8611?key=system-medium-cover&modified=2022-07-22T11:27:00.188Z&download=true`
While all other requests like js/css files and API calls are working without problems.

**Comment by christianrr** [comment]
> Directus' url construction relies on the `/admin` part in the path to know what the root URL is in the app, so did this configuration ever work before? 🤔

Yes, worked fine until 9.14.1. We use this configuration since release candidate phase.

> Also, where are you seeing the wrong URL being used?

In the network console of Chrome Developer Tools...

**Comment by Serhii-the-Dev** [comment]
Same here, I have this issue after a migration from `9.14.1` to `9.14.3`. Docker config:
```yaml
environment:
  - "PUBLIC_URL=/directus/"
  - "ROOT_REDIRECT=./directus/admin/"
```
I'm using Caddy for a reverse proxy:
```
handle_path /directus* {
  reverse_proxy directus:8055
}
```

**Comment by rijkvanzanten** [comment]
@br41nslug Figured it out: The `v-image` component uses the `api` instance to download the files. The `api` instance itself uses `getRootPath()` as the baseURL config, which in turn means that you end up fetching `getRootPath() + props.src`, where `props.src` is often `getRootPath() + /assets/:uuid`. The double `getRootPath()` is causing the issue 👍🏻
