### ISSUE TITLE
Flows Conditions operation is considered valid if the property is not defined in the input data

### ISSUE THREAD

**Issue by gkielwasser** [directus/directus#14571]
### Describe the Bug

When a property is not defined in the input data passed to the condition rule, the condition is considered as valid whatever the filter is.

### To Reproduce

Configure the flow:
1. Create a Trigger operation on collection A (type:action, scope:items.update)
2. On Success, create a Condition configured as follow

Condition Rules
```
 "$trigger": {
      "payload": {
        "informations_status": {
          "_eq": "request_additional_data"
        }
      }
    }
  }
```

Use cases while updating a collection A item with those payloads:

1- Payload is defining the value

```
     { "informations_status": "request_additional_data" }
```
```
     { "informations_status": "draft" }
```
Observed: The condition returns correctly true/false according to the given "informations_status" value

2- Payload is not defining the tested value
```
     { "any_another_field": "foo" }
```
Observed: The condition returns incorrectly true.

### Errors Shown

None

### What version of Directus are you using?

9.14.3

### What version of Node.js are you using?

14

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
Ref https://github.com/directus/directus/pull/14311

**Comment by andy1li** [comment]
Ref: https://github.com/directus/directus/pull/14311#issuecomment-1198601837

> @andy1li You're correct. That being said, I believe the change in this PR might be a solution for (unconfirmed) bug #14571, so I don't wanna close it yet 👍🏻

---

@rijkvanzanten. Yes, I was also encountering the "undefined leads to true" problem during my ignorant journey of trying to figure out how to use Flows.

I used something like this as filter:

```
{
  "$trigger.payload.status": {
    "_eq": "aaa"
  }
}
```

Then the condition would pass, no matter what.

And {{`condition_foo_key`}} in a subsequent "Log to Console" would print `null`.

Directus Version: 9.14.5

**Comment by u12206050** [comment]
Just saw I have the same issue:

```
{
    "$trigger": {
        "activeStatusCode": {
            "_eq": 0
        }
    }
}```

This is always truthy even though the payload data on the trigger is :

```
{
  "name": "RedQ",
  "type": "club",
  "orgID": 2314,
  "activeStatusCode": 2
}```

**Comment by izoukhai** [comment]
If you're experiencing this issue, you can create a "Run Script" operation and check the field this way:

`module.exports = async function({$trigger}) {
    if (!$trigger.payload.status) 
        throw new Error("Status is not changed")
    else 
        return {};
}`

**Comment by u12206050** [comment]
@izoukhai Thanks for the tip, but seems like I run into another issue then #15653 

Which is that within a sub flow data isn't available where it should be.

**Comment by izoukhai** [comment]
@u12206050 Ah shit, let's see what the Directus team think about it.

**Comment by azrikahar** [comment]
Ref https://github.com/directus/directus/issues/15899#issuecomment-1274236961 for similar issue in field validations

**Comment by JonathanSchndr** [comment]
Workaround for all with the same error to check a Value with Run Script in flow.

Example: Status must be invited and not undefined
```
module.exports = async function(data) {
    if(typeof data.$trigger.payload.status !== 'undefined' && data.$trigger.payload.status === 'invited') {
        return {...data}
    }
    
	throw new Error('Status is not invited.');
}
```

**Comment by dataheadless** [comment]
@JonathanSchndr Excellent answer, if there was documentation for using flows then it would have been great, you never know what is passed in data object.
