### ISSUE TITLE
Primary Key property is always equal to "+" in custom interface extensions

### ISSUE THREAD

**Issue by Serhii-the-Dev** [directus/directus#14574]
### Describe the Bug

After an update to the v9.14.3 (and `"@directus/extensions-sdk": "9.14.2"`) the `primaryKey` prop in both of my interface extensions is constantly filled with a `+` value. The extensions are made to match `uuid` and `boolean` field types, the entity they are used with has a `uuid` primary key (one of the extensions is used to render a PK interface).

### To Reproduce

1. Create a fresh Directus project (I used Docker image with a tag `9.14.3`)
2. Create an interface extension, add the next prop:
```
    primaryKey: {
      // I checked both String and Object, the result is the same
      type: String, 
    }
```
3. In the `setup` hook, check the `props.primaryKey` value.

### What version of Directus are you using?

9.14.3

### What version of Node.js are you using?

16+

### What database are you using?

PostgreSQL

### What browser are you using?

Chrome.Safari

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
> In the setup hook, check the props.primaryKey value.

Is this in a singleton? Does the value update once the item is loaded? During the loading state of the item, the primary key might be reported as `+` if it's not known yet

**Comment by Serhii-the-Dev** [comment]
Hi @rijkvanzanten 
It’s a regular existing item, and I’ve just checked, indeed the value is set to the “+” at the loading of the page. Is this a new behaviour in the 9.14.2? I don’t have this in 9.14.1.

**Comment by azrikahar** [comment]
I believe this is related to #14608. Closing in favor consolidating this over there.
