### ISSUE TITLE
Insight Dashboard doesn't work for V9.14.3 (work fine with V9.14.1)

### ISSUE THREAD

**Issue by khunsatant** [directus/directus#14573]
### Describe the Bug

after upgrade to 9.14.3, my dashboard doesn't work anymore for all panels.
I found that there are error return in graphql response.
and I also tested it by create new dashboard and panel as image, result is the same.
![image](https://user-images.githubusercontent.com/18061895/180425335-5bdfc5e1-d7c0-40d6-aab1-8210c7e32f80.jpeg)

### To Reproduce

1. create Metric panel by use Average. my case use "value" field(type: float) on "metric" table.
2. after save, data not show

### Errors Shown

`{
    "errors": [
        {
            "message": "Cannot read properties of undefined (reading 'length')",
            "locations": [
                {
                    "line": 2,
                    "column": 5
                }
            ],
            "path": [
                "metric_aggregated"
            ]
        }
    ],
    "data": null
}`

### What version of Directus are you using?

9.14.3

### What version of Node.js are you using?

v16.15.1

### What database are you using?

Mysql 8.0.29

### What browser are you using?

Brave

### How are you deploying Directus?

running Locally

**Comment by azrikahar** [comment]
I believe this is the same issue as #14557, which stems from the GraphQL aggregate count bug. 

Just to confirm, you are using Count or Count (Distinct) as the aggregate function in the metric panel right? We'll re-open if you're not using them 👍

**Comment by khunsatant** [comment]
@azrikahar Both Average and Count show the same error.

**Comment by azrikahar** [comment]
@khunsatant ah.. very sorry about the confusion. It's actually aggregate functions as whole, not just limited to Count. Thanks for clarifying!

**Comment by khunsatant** [comment]
Yeah, don’t worry. Thank you.
