### ISSUE TITLE
Not returning file object if FormData appended data.

### ISSUE THREAD

**Issue by quomark** [directus/directus#14579]
### Describe the Bug

I have an custom field named 'file_purpose'. 
if I Post a file with this formdata, there will be return 204 (with no data).
No file object is returned. (See image)

[https://i.ibb.co/r3LgVfw/Whats-App-Image-2022-07-15-at-5-57-30-PM.jpg](url)

### To Reproduce

just Post a file with POSTMAN, and add formdata before the file data.

### Errors Shown

return 204 No Content

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

14.19.0

### What database are you using?

MYSQL

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally

**Comment by rijkvanzanten** [comment]
Image link is broken

**Comment by rijkvanzanten** [comment]
This seems to work as expected on my end. 

```
POST /files HTTP/1.1
Authorization: Bearer admin
Content-Type: multipart/form-data; charset=utf-8; boundary=__X_PAW_BOUNDARY__
Host: localhost:8055
Connection: close
User-Agent: Paw/3.3.6 (Macintosh; OS X/12.4.0) GCDHTTPRequest
Content-Length: 1784730

--__X_PAW_BOUNDARY__
Content-Disposition: form-data; name="file_purpose"

example
--__X_PAW_BOUNDARY__
Content-Disposition: form-data; name="file"; filename="colton-duke-UExx0KnnkjY-unsplash.jpg"
Content-Type: image/jpeg

ÿØÿàJFIFHHÿâICC_PROFILElcmsmntrRGB XYZ Ü)9acspAPPLöÖÓ-lcms [truncated]
```

returns 

```json
{
  "data": {
    "id": "fad753e6-86c0-49a3-b127-3a38e7568e43",
    "storage": "local",
    "filename_disk": "fad753e6-86c0-49a3-b127-3a38e7568e43.jpg",
    "filename_download": "colton-duke-UExx0KnnkjY-unsplash.jpg",
    "title": "Colton Duke U Exx0 Knnkj Y Unsplash",
    "type": "image/jpeg",
    "folder": null,
    "uploaded_by": "7f7fd5e4-d596-4dcd-9d89-879365f798b8",
    "uploaded_on": "2022-07-22T15:02:39.747Z",
    "modified_by": null,
    "modified_on": "2022-07-22T15:02:39.813Z",
    "charset": null,
    "filesize": "1784474",
    "width": 4096,
    "height": 2384,
    "duration": null,
    "embed": null,
    "description": null,
    "location": null,
    "tags": null,
    "metadata": {},
    "file_purpose": "example"
  }
}
```

The 204 response is probably because your current user doesn't have read-access to the file. If you use an access token that has read access to files, it'll be returned on create 👍🏻 If the custom field isn't set properly, please double check the order of the fields in the multipart body in Postman

**Comment by quomark** [comment]
> https://i.ibb.co/r3LgVfw/Whats-App-Image-2022-07-15-at-5-57-30-PM.jpg

the image is not broken. you just need to copy and paste the link

**Comment by rijkvanzanten** [comment]
> > https://i.ibb.co/r3LgVfw/Whats-App-Image-2022-07-15-at-5-57-30-PM.jpg
> 
> the image is not broken. you just need to copy and paste the link

so the link is broken then 😉 

As for what's going wrong, your file doesn't have a "key" (should be `file`), so I don't think postman is correctly sending the body.

**Comment by quomark** [comment]
> > > https://i.ibb.co/r3LgVfw/Whats-App-Image-2022-07-15-at-5-57-30-PM.jpg
> > 
> > 
> > the image is not broken. you just need to copy and paste the link
> 
> so the link is broken then 😉
> 
> As for what's going wrong, your file doesn't have a "key" (should be `file`), so I don't think postman is correctly sending the body.

I tried add the file as key, same result. see picture.

[https://imgur.com/a/pvMj09L](url)

**Comment by quomark** [comment]
> This seems to work as expected on my end.
> 
> ```
> POST /files HTTP/1.1
> Authorization: Bearer admin
> Content-Type: multipart/form-data; charset=utf-8; boundary=__X_PAW_BOUNDARY__
> Host: localhost:8055
> Connection: close
> User-Agent: Paw/3.3.6 (Macintosh; OS X/12.4.0) GCDHTTPRequest
> Content-Length: 1784730
> 
> --__X_PAW_BOUNDARY__
> Content-Disposition: form-data; name="file_purpose"
> 
> example
> --__X_PAW_BOUNDARY__
> Content-Disposition: form-data; name="file"; filename="colton-duke-UExx0KnnkjY-unsplash.jpg"
> Content-Type: image/jpeg
> 
> ÿØÿà��JFIF�����H�H��ÿâ��ICC_PROFILE������lcms����mntrRGB XYZ �Ü�������)�9acspAPPL��������������������������öÖ������Ó-lcms����������������������������������������� [truncated]
> ```
> 
> returns
> 
> ```json
> {
>   "data": {
>     "id": "fad753e6-86c0-49a3-b127-3a38e7568e43",
>     "storage": "local",
>     "filename_disk": "fad753e6-86c0-49a3-b127-3a38e7568e43.jpg",
>     "filename_download": "colton-duke-UExx0KnnkjY-unsplash.jpg",
>     "title": "Colton Duke U Exx0 Knnkj Y Unsplash",
>     "type": "image/jpeg",
>     "folder": null,
>     "uploaded_by": "7f7fd5e4-d596-4dcd-9d89-879365f798b8",
>     "uploaded_on": "2022-07-22T15:02:39.747Z",
>     "modified_by": null,
>     "modified_on": "2022-07-22T15:02:39.813Z",
>     "charset": null,
>     "filesize": "1784474",
>     "width": 4096,
>     "height": 2384,
>     "duration": null,
>     "embed": null,
>     "description": null,
>     "location": null,
>     "tags": null,
>     "metadata": {},
>     "file_purpose": "example"
>   }
> }
> ```
> 
> The 204 response is probably because your current user doesn't have read-access to the file. If you use an access token that has read access to files, it'll be returned on create 👍🏻 If the custom field isn't set properly, please double check the order of the fields in the multipart body in Postman

Yes you are right. It is the read-access issue. Sorry for bothering.
