### ISSUE TITLE
Environment configurations superseded by .env, container configurations not overriding .env

### ISSUE THREAD

**Issue by isawk** [directus/directus#14587]
### Describe the Bug

All environment configurations are overridden by .env

### To Reproduce

Upgrade Directus to v9.14.5 from version 9.8.0

v9.8.0 (working version, container, PaaS environment configurations are taking into consideration)
![image](https://user-images.githubusercontent.com/21027753/180590969-e26fbd34-2e0d-44a7-a137-0d9a16c98273.png)

v9.14.0 (appears env are overridden by what is in .env)
![image](https://user-images.githubusercontent.com/21027753/180590986-4321c5b2-e7e2-4437-acf4-ae6abdcc3f15.png)

### Errors Shown

No errors, just expected environment configurations are not picked up/used

### What version of Directus are you using?

v9.14.5

### What version of Node.js are you using?

16

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

PaaS

**Comment by azrikahar** [comment]
This was a change in #12900 which is included in Directus 9.9.1 onwards. That said, let's keep this as a specific issue this concern: https://github.com/directus/directus/pull/12900#issuecomment-1137037830, as an issue for it was requested but not yet opened to date.

**Comment by isawk** [comment]
I see, perhaps once can dynamically use javascript to retrieve configurations from a secured key store. This also will prevent having to commit .env file for local development. 

> This was a change in #12900 which is included in Directus 9.9.1 onwards. That said, let's keep this as a specific issue this concern: [#12900 (comment)](https://github.com/directus/directus/pull/12900#issuecomment-1137037830), as an issue for it was requested but not yet opened to date.

Thanks for the insight reasons for change makes sense. Perhaps one can dynamically use javascript to retrieve configurations from a secured key store. This also will prevent having to commit .env file for local development.

**Comment by rijkvanzanten** [comment]
> Thanks for the insight reasons for change makes sense. Perhaps one can dynamically use javascript to retrieve configurations from a secured key store. This also will prevent having to commit .env file for local development.

You should be able to do that already: https://docs.directus.io/self-hosted/config-options/#config-js
