### ISSUE TITLE
Prompt to "Update Bookmark"

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1459]
Bookmarks need to *prompt* before saving changes: `Would you like to update your bookmark with this change?` 

Yes = save, and stay in bookmark (keeps nav on bookmark)
No = apply changes, move to normal page (nav switches to table)

**Comment by WellingGuzman** [comment]
> Yes = save, and stay in bookmark (keeps nav on bookmark)

Closed by: https://github.com/directus/directus/commit/3623b135476bda0ec8dc5018b64cc21c18dfc2ae

**Comment by WellingGuzman** [comment]
> No = apply changes, move to normal page (nav switches to table)

Closed by https://github.com/directus/directus/commit/23894c92dc7f4abf1973778406f61518959a6cf2

**Comment by benhaynes** [comment]
When you choose "No" on the update modal, it does not take you to the same exact page you requested.

If you're on a bookmark and change the status to also show DRAFT, then it asks you if you want to update your bookmark (you say "no"), then it should show you the normal Listing page and SHOW DRAFT (like you requested).

**Comment by WellingGuzman** [comment]
I thought we agreed that's how it should work.

If the user didn't want to apply the changes in the modal, that changes will replace the original table preferences and redirect to the actual table.

**Comment by benhaynes** [comment]
Exactly. But right now the NEW change (that caused the modal) is not moving over. Example:

Normal: `published`
Bookmark: `draft`

User is viewing bookmark, and ADDS `published` but does NOT save/update the bookmark. It should navigate to Normal:

Normal: `published`, `draft`
Bookmark: `draft`

but instead it just goes to:

Normal: `draft`
Bookmark: `draft`

**Comment by benhaynes** [comment]
OK, this looks good now
