### ISSUE TITLE
REST API request fails with error 500 - "fields is not iterable"

### ISSUE THREAD

**Issue by petervukovic** [directus/directus#14607]
### Describe the Bug

Using a specific REST query with field parameters on a many-to-many relationship results in error 500.

### To Reproduce

1. Create an `artists` collection with a `name` text field
2. Create a `song` collection with a `title` text field and `performed_by` relationship field
3. Configure `performed_by` relationship so it is a `many-to-many` relationship with `artists`
4. Run the following REST query `GET /items/songs?fields=title, performed_by:artists.name`

Expected Response:
Status 400 / INVALID_QUERY, or an empty data set for `performed_by` section of the query

Actual:
Status 500 / INTERNAL_SERVER_ERROR - message: "fields is not iterable"

### Errors Shown

Console output shows this stack trace:

```
fields is not iterable 
TypeError: fields is not iterable
    at parseFields (/Users/petervukovic/Repositories/sparwk/directus/node_modules/directus/dist/utils/get-ast-from-query.js:77:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async parseFields (/Users/petervukovic/Repositories/sparwk/directus/node_modules/directus/dist/utils/get-ast-from-query.js:197:31)
    at async getASTFromQuery (/Users/petervukovic/Repositories/sparwk/directus/node_modules/directus/dist/utils/get-ast-from-query.js:66:20)
    at async ItemsService.readByQuery (/Users/petervukovic/Repositories/sparwk/directus/node_modules/directus/dist/services/items.js:200:19)
    at async /Users/petervukovic/Repositories/sparwk/directus/node_modules/directus/dist/controllers/items.js:70:18
```

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

17.0.1

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by NigmaX** [comment]
I think that on "many to many" relations you can't target a specific column. 
you can do that only on M2A (many to any) as specified on the documentation.
you can target the relation column and get the related fields as an object by using the ".*" mark 
`/items/songs?fields=title,performed_by.*`

for the documentation section: https://docs.directus.io/reference/query/

**Comment by petervukovic** [comment]
@NigmaX That is correct, but the API should respond with an invalid query error instead of crashing.
