### ISSUE TITLE
Reset header after filter (inaccessible checkbox)

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1460]
We need to reset the header and item checkboxes after changing status (item listing). Right now if you have View == Published Only and you check an item and make it Draft... it disappears but is still checked (hidden) so you can't change the header filter

**Comment by WellingGuzman** [comment]
Closed by: https://github.com/directus/directus/commit/c62abf614710515ab67bf99937c97339eee2e535 and https://github.com/directus/directus/commit/7a6f2a52d0527c8f8a989529961f0141a8059025
