### ISSUE TITLE
Image preview not updated after editing in the file library

### ISSUE THREAD

**Issue by licitdev** [directus/directus#14619]
### Describe the Bug

PR https://github.com/directus/directus/pull/14511 resolved the issue for the collections module but the same issue exists in the file library.

### To Reproduce

https://user-images.githubusercontent.com/26413686/180731717-56d3a904-fcd8-4f5e-94ab-364acd3321b7.mov

### What version of Directus are you using?

v9.14.5

### What version of Node.js are you using?

v16

### What database are you using?

SQLite

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
The file preview is correctly updated with the new src, but the `v-image` component doesn't re-fetch / redisplay the image when the `src` changes (it's only loading on the observer now). Should be a relatively easy fix
