### ISSUE TITLE
Reload the item when a flow is executed on the item detail page

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#14630]
An additional important point is that we should trigger a warning when you have unsaved changes when executing the flow (eg "this might change the item, are you sure you want to execute" something).

### Discussed in https://github.com/directus/directus/discussions/14585

<div type='discussions-op-text'>

<sup>Originally posted by **farmisen** July 22, 2022</sup>
My (reduced) use case is the following:

I have setup a manually triggered flow to `Publish` an item of a given collection from the item page. The flow itself works perfectly and consist on a trigger block followed by an update block that change the `status` field content to "published" (but eventually will alter more fields).

![image](https://user-images.githubusercontent.com/229946/180577602-b98de299-5c44-4bdb-b307-c13885738843.png)

My issue is that when I trigger the flow from the item page, the item values do not update like they do after a ⌘+S and after the flow has completed, I have to manually reload the page to see the correctly updated value.

Is there any official way to achieve that? Any work around you can think of? This is a relatively critical issue for the thingie I am working on and I will gratefully welcome any suggestion pointing me toward the correct direction. Thanks!</div>

**Comment by rspauwen** [comment]
@rijkvanzanten this only appears to work for a manual flow. How can I force a reload after a flow that is triggerd by `item.update` ?

**Comment by rijkvanzanten** [comment]
If you use a `filter` hook, that should handle itself, as the app will wait for the mutation to be completed before reloading the page. If you're using an action hook, the app doesn't know there's a change to refresh for
