### ISSUE TITLE
WYSIWYG Image options no longer available

### ISSUE THREAD

**Issue by barrylow** [directus/directus#14643]
### Describe the Bug

From v9.14.3 to latest v9.14.5, when right-clicking on an image in the WYSIWYG, the "Image..." options no longer opens the modal presenting general and advanced image options such as Show Caption. Reverting to 9.14.1 restores expected function.

Expect to see Image options modal:
<img width="360" alt="Screen Shot 2022-07-25 at 1 16 11 PM" src="https://user-images.githubusercontent.com/77066045/180868470-4c9136da-b563-4432-adf0-08dc3b997eec.png">

Instead see, side panel opens and see:
<img width="480" alt="Screen Shot 2022-07-25 at 1 16 44 PM" src="https://user-images.githubusercontent.com/77066045/180868584-e9bb8f53-ea61-4ffd-ad6c-844c9f1bdc83.png">

### To Reproduce

In latest Directus, in WYSIWYG field, insert an image. Right-click on inserted image and click on "Image...":
<img width="480" alt="Screen Shot 2022-07-25 at 1 28 49 PM" src="https://user-images.githubusercontent.com/77066045/180868863-3a383e67-56c2-458e-b12c-1321ef26343c.png">

### Errors Shown

No errors are show in Directus server logs or browser console.

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

16.15.1

### What database are you using?

Postgres 12

### What browser are you using?

Chrome Version 103.0.5060.114

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
This is actually on purpose in https://github.com/directus/directus/pull/14404. The context menu in tinymce was using the wrong modal instances before. Feel free to open a new feature request discussion for any enhancements in the media modal 👍🏻
