### ISSUE TITLE
Not getting warning about missing PK Interface

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1464]
I changed the PK interface to Numeric and I am not getting the warning about "No PK Interface". I assume this is because it is there's still a PK in the database, but we need the warning even if you don't have the interface set.

Also, the PK Interface is NOT visible in the dropdown, so there's no way to set one. PK, Sort, and Status Interfaces should be visible in the dropdown IF ONE DOESN'T EXIST IN THE TABLE ALREADY. That will make sure there's only one per table... but you can still add it if there isn't one.

**Comment by WellingGuzman** [comment]
Also closed by this https://github.com/directus/directus/commit/3dbe01a8c0d33003b02c76e61111da4b5706f900
