### ISSUE TITLE
Filter operator mishandles regular expressions

### ISSUE THREAD

**Issue by tb-lbi** [directus/directus#14641]
### Describe the Bug

The "Matches RegExp" filter operator returns true if the regular expression matches any substring of the field. This makes it impossible to, for instance, add a validation constraint on an input field that only accepts strings consisting of alphanumeric characters. The "Matches RegExp" operator should only return true if the field's entire string value matches the regular expression.

### To Reproduce

Create a collection with an input field, e.g. "example_field". Go to validation tab for the input field and add the filter "Example Field Matches RegExp abc". Create an item in the collection and enter "##%^qq@!&^$$abc!!#!@#" under Example Field. The validation filter will not prevent you from creating this item.

### Errors Shown

No

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

16.16.0

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### How are you deploying Directus?

Cloud instance

**Comment by rijkvanzanten** [comment]
`##%^qq@!&^$$abc!!#!@#` is a valid value for RegExp `/abc/` though, as the regex doesn't introduce any string size or positioning requirements. This can be verified in plain javascript as well:

```js
const regex = /abc/;
regex.test('##%^qq@!&^$$abc!!#!@#');
// => true
```

What you're looking for is regex `/^abc$/`, which would result in the "strict" check 👍🏻 

```js
const regex = /^abc$/;
regex.test('##%^qq@!&^$$abc!!#!@#');
// => false
```
