### ISSUE TITLE
Unable to set integer ID field of new item

### ISSUE THREAD

**Issue by u12206050** [directus/directus#14652]
### Describe the Bug

Have a collection with and ID field of type `integer` even though the following options are set, the field is always disabled.

![Screenshot 2022-07-26 at 12 15 03](https://user-images.githubusercontent.com/6641242/180982580-d06ef9eb-ac65-4552-99d6-26b17c8156b8.png)

![Screenshot 2022-07-26 at 12 15 22](https://user-images.githubusercontent.com/6641242/180982632-2684755b-078e-4257-943e-2ba2eca5fbed.png)

### To Reproduce

Create a collection with an auto-incremented integer id field.

Try to create an item with a predefined id. No matter which options are set, the field is simply always disabled.

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

chromium

### How are you deploying Directus?

Locally & GCP

**Comment by rijkvanzanten** [comment]
This is by design. When you have auto-increment enabled, the primary key is disabled. If you enter a primary key manually in an auto-incremented field, there's a chance you corrupt the sequence used in the database, which can cause various other errors in usage
