### ISSUE TITLE
Too many redirects in Safari (before installation)

### ISSUE THREAD

**Issue by raymonschouwenaar** [directus/directus#1469]
I've uploaded the all the files for Directus (v6.3.9) to my webhosting. 

When I tried to visit the url, the is an error in Safari with Too many redirects occurred trying to open url: "http://rexmagazine.magr.digital/directus/login.php?redirect=login.php?redirect=login.php?redirect=login.php?redirect=login.php?redirect=login.php?redirect=login.php?redirect=login.php?redirect=login.php?redirect=login.php?redirect=login.php?redirect=login.php?redirect=login.php?redirect=login.php?redirect=login.php?redirect=login.php".

## Step to reproduce:
1. Open Safari browser with "http://rexmagazine.magr.digital".
2. Then you will get this result!

Webfaction is my hosting, I used a static application. (Documentation https://docs.webfaction.com/software/static.html)  It is a NGINX server, but the documentation tells me that it will use the .htaccess.

I hope someone can tell me what I'm doing wrong.

**Comment by raymonschouwenaar** [comment]
I found the solution for me!

I uploaded the application in the main directory, but my DIRECTUS_PATH was: `define('DIRECTUS_PATH', '/directus/');` , but had to be `define('DIRECTUS_PATH', '/');`

Hopefully this will help others :-)

**Comment by WellingGuzman** [comment]
Hey @raymonschouwenaar, I assume you copied an paste the config examples? Just curious.

I'm going to change the default `DIRECTUS_PATH` value to `/`

Thanks for the info.
