### ISSUE TITLE
Switch to pnpm causes runtime dependency error: Cannot find module '@directus/app/package.json'

### ISSUE THREAD

**Issue by claytongulick** [directus/directus#14706]
### Describe the Bug

The switch to pnpm seems to have changed the way that workspace dependencies are resolved.

When starting directus by running api/cli.js start, the error: Cannot find module '@directus/app/package.json' is shown and causes a crash.

It looks like workspace:* dependencies are not being resolved correctly in resolve-packages.ts - the call to require.resolve is using the node module resolution algorithm relative to /shared/util rather than relative to the main module or peer dependencies.

Current temporary workaround is to add @directus/app as a dependency to the shared package, this will allow directus to start, but isn't going to work for package extension resolution.

### To Reproduce

Do a fresh git clone of main branch, pnpm install, pnpm -r build, and try to run via api/cli.js start

### Errors Shown

Cannot find module '@directus/app/package.json'

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

16

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

local

**Comment by rijkvanzanten** [comment]
You can use `pnpm -r directus cli <command>` instead of `node ./api/cli.js <command>` to run the CLI in the dev bundle 🙂

**Comment by claytongulick** [comment]
Hi @rijkvanzanten and thanks, but I think I must have missed a bit in the description, I created the issue based on the discord discussion with @br41nslug - the problem is running the code base in production mode directly from the cloned repo, not as a package dependency (i.e., running a forked version - we have that custom external extension code in production).

When you set SERVE_APP=true and run it, it causes the above error - it's not able to locate the @directus/app dependency because of the call to require.resolve in shared/utils/node/resolve-package.ts

I haven't found any way to launch the compiled, build, production mode app without running into that dependency issue.

@br41nslug mentioned that at least one other person had run into this as well.

**Comment by rijkvanzanten** [comment]
Oh that's a good question, that's not really something we've ever really officially supported. The "official" way to run the production Directus is through the npm or docker distributions. I think @br41nslug ran into it as the core team used to use that command to quickly run some local CLI commands like `./api/cli.js bootstrap`, but that use case is replaced by the `pnpm -r directus cli <command>` approach. 

That all being said, I think this might be an easy fix to add in to support that use case for real. I believe we can fix this by adding the correct `root` values to the places we try to load in the app. This should make sure that `pnpm` will read it from the correct source when running locally.

```diff
/api/src/app.ts
@@ -179,7 +179,7 @@ export default async function createApp(): Promise<express.Application> {
        });

        if (env.SERVE_APP) {
-               const adminPath = require.resolve('@directus/app');
+               const adminPath = require.resolve('@directus/app', { paths: [require.main!.filename] });
                const adminUrl = new Url(env.PUBLIC_URL).addPath('admin');

                // Set the App's base path according to the APIs public URL
```

```diff
/api/src/extensions.ts
@@ -310,7 +310,9 @@ class ExtensionManager {
        }

        private async getSharedDepsMapping(deps: string[]) {
-               const appDir = await fse.readdir(path.join(resolvePackage('@directus/app'), 'dist', 'assets'));
+               const appDir = await fse.readdir(
+                       path.join(resolvePackage('@directus/app', require.main!.filename), 'dist', 'assets'
)
+               );

                const depsMapping: Record<string, string> = {};
                for (const dep of deps) {
```

@claytongulick can you confirm that the above two changes fix things on your end? If so, I can prepare a PR to get this through 👍🏻

**Comment by claytongulick** [comment]
@rijkvanzanten thanks, that worked great!

**Comment by rijkvanzanten** [comment]
Oh my bad, you're right. It's `pnpm -F directus cli <command>` instead of `pnpm -r directus cli <command>` 👍🏻
