### ISSUE TITLE
Values not remembered after switching tabs in modal 

### ISSUE THREAD

**Issue by Ronnyrr** [directus/directus#1470]
## Version Info
  - 6.4 (beta)

## Expected Behavior
You want the interface tab to save the values after you switch between tabs. This happens with all modals. 

## Actual Behavior
When switching to “Column setup” without saving, returned to “Interface options” and all fields where empty / resetted. Small overlay usability tweak. 

## Logs or Screenshots
<img width="619" alt="schermafbeelding 2017-05-12 om 15 32 15" src="https://cloud.githubusercontent.com/assets/4519142/26019574/973e5642-3776-11e7-8f24-ab4716b84222.png">

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/66fc638b3bf6dcb182960297a0f7747bd509d0db

**Comment by benhaynes** [comment]
Not working for interface options – but we'll get to this after release

**Comment by WellingGuzman** [comment]
Correction: Not working for some interfaces, mainly non-native inputs.

**Comment by WellingGuzman** [comment]
Values are being remembered now. another issue that seems to be similar to this one but it actually isn't is https://github.com/directus/directus/issues/1637, which looks like it's one form and saving one will save both, but those are two independent form.

The fix will be make it work like one, no matter which tap are enable/open when you click save.

Closing this as the values are remember when you switch tabs. if one or more interfaces are not working (not remember their value) we can reopen.
