### ISSUE TITLE
Update all emails to use new template

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1471]
Use general template style from Hosted

**Comment by WellingGuzman** [comment]
@benhaynes I've added the logo from `directus.io` url, and the design of the footer has too much spacing, take a look and see what you think it's best.

About the logo, should we use the svg from `assets` directory and fallback to any logo the user use? This follow another question should the logo background be customizable in case the logo and the background don't play well?

**Comment by benhaynes** [comment]
Getting close!

Can we update that "Change your preferences" link to point to THEIR user detail page? Directus will redirect them there after login.

For emails sent from Directus Messages... can we include the name of the sender below?

And can these email subject lines have ` [Directus: Project Name]` at the end?

It doesn't like that logo for some reason:
![screen shot 2017-05-17 at 7 07 59 pm](https://cloud.githubusercontent.com/assets/522079/26179971/86a8b6a8-3b34-11e7-9b4b-a9c139a5186b.png)

Here's an article about why an image might not display:
https://support.google.com/mail/answer/145919?hl=en

Also, the Email sender is getting a notice, is there anything we can do about this? Maybe send from a generic address?
![screen shot 2017-05-17 at 7 08 34 pm](https://cloud.githubusercontent.com/assets/522079/26179953/5b584bd0-3b34-11e7-8122-37facbba8d30.png)

**Comment by benhaynes** [comment]
Also, we should use the Project Logo (image) in the header – if it doesn't exist then we use the Directus logo (from their instance, not directus.io)

**Comment by WellingGuzman** [comment]
The `directus.io` was just for placeholder, the one in directus is a svg, so I need your help on make it work using the svg, in the other hand I will make it work using the project logo (image).

**Comment by benhaynes** [comment]
OK, SVG Directus logo is not good for email, I just pushed a PNG into the repo... let's use that as a fallback to the Project Image.

**Comment by benhaynes** [comment]
```
$adapter = \Directus\Bootstrap::get('zendDb');
$acl = \Directus\Bootstrap::get('acl');
$table = new \Directus\Database\TableGateway\DirectusUsersTableGateway($adapter, $acl);
$user = $table->find(1);
```

**Comment by benhaynes** [comment]
@WellingGuzman – I am receiving multiple (3-4) copies of emails (notifications of new Directus Messages) from the SENDER. Maybe it is sending one for each reply? Either way, it should only send ONE.

**Comment by benhaynes** [comment]
We need a route to open messages. Same page, but should open the message in the right pane:

`http://local.directus.com/messages/new`
`http://local.directus.com/messages/12` (opens message id:`12`)

**Comment by benhaynes** [comment]
@WellingGuzman The only problem with using the project log (and project directus logo) is that it won't work on local (not a HUGE deal, but too bad). If we can TEST for local somehow, we can serve the directus.io logo in those cases.

**Comment by benhaynes** [comment]
OK, moved "link to messages" to FeatHub... the rest looks good!
