### ISSUE TITLE
Cannot access Directus Cloud app with Admin account

### ISSUE THREAD

**Issue by willemmulder** [directus/directus#14721]
### Describe the Bug

In the app (being logged in as the admin user and not having done anything odd) I suddenly got this error message for all pages

![image](https://user-images.githubusercontent.com/70933/181510711-889ef6c5-d2ec-4553-bee4-fe741e170e8a.png)

Logging out and in again does not help. Now the app does not show at all. I'm effectively locked out... 
App: https://b3339lek.directus.app/admin/content

### To Reproduce

I don't know :-)

### What version of Directus are you using?

latest

### What version of Node.js are you using?

?

### What database are you using?

SQLite (Directus Cloud with free project... that's SQLite right?)

### What browser are you using?

Chrome

### How are you deploying Directus?

Directus Cloud

**Comment by rijkvanzanten** [comment]
Hi @willemmulder! Sounds like there's a specific configuration problem with your user (sounds like the role got disconnected for some reason). I'll pass this on to the Cloud team 👍🏻 

For future cloud related problems, it's faster to reach out through the chat on the Cloud Dashboard. That puts you in touch with the team that can resolve problems like these immediately 🙂

**Comment by willemmulder** [comment]
Thanks, will do, and thanks for forwarding this time!

But I'll wait until my other issues are resolved; they currently prevent me from doing what I want.
Will pick this up in the future :-)
