### ISSUE TITLE
Welcome Modal Issues

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1472]
* Inputs should only have checks when the value is valid/matching 
* Password isn't editable (only admins?)
* Edit Avatar button doesn't do anything
    * Should open up "global" file uploader/chooser
    * Or, open system upload dialog
    * Or, hide pencil icon for now

**Comment by WellingGuzman** [comment]
- [x] Inputs should only have checks when the value is valid/matching
Issue on password; check overlaps due to being wrapped into the same element
- [x] Password isn't editable (only admins?)
Only when it's empty
- [x] Edit Avatar button doesn't do anything
It opens system upload dialog

**Comment by benhaynes** [comment]
I'm testing the Welcome Message modal. I created a new user in the DB and logged in... some things seem to be working but I got this error:

 ```Error
Error: Uncaught TypeError: (intermediate value)(intermediate value).callback.call is not a function
File: http://local.directus.com/assets/js/libs/backbone.js?bust=8e89cfdcf6d936fb831e7b1a6dade6db7953025e
Line:205```

And then when I finish, I get this error:


 ```Server Error
Argument 1 passed to Directus\Database\TableGateway\DirectusUsersTableGateway::__construct() must implement interface Zend\Db\Adapter\AdapterInterface, string given, called in /Users/Ben/Sites/directus/api/core/Directus/Database/TableGateway/BaseTableGateway.php on line 152 and defined```


Also, the password fields were still _disabled_ so I couldn't update my password:

![screen shot 2017-05-17 at 9 34 27 am](https://cloud.githubusercontent.com/assets/522079/26156838/931bc744-3ae5-11e7-98f1-6f853a084b07.png)

**Comment by WellingGuzman** [comment]
> I created a new user in the DB and logged in

what values had the user when you created in the DB?

> The password fields were still disabled so I couldn't update my password

I going to update this, it only worked when the user didn't have any password, now will work like this:

1. User has password and Input is not empty: Change password
2. User has not password set and Input is empty: Validation Warning
3. User has password set and Input is empty: Pass, keep current password

**Comment by benhaynes** [comment]
Still getting this error when submitting:

```
Error
Error: Uncaught TypeError: this.get(...).has is not a function
File: http://local.directus.com/app/modules/users/UsersModel.js?bust=976b1cad4e2ffd44a495dc2cd98008ca967f8756
Line:14
```

This is what the user looks like before:
```INSERT INTO `directus_users` (`id`, `active`, `first_name`, `last_name`, `email`, `password`, `salt`, `token`, `access_token`, `reset_token`, `reset_expiration`, `position`, `email_messages`, `last_login`, `last_access`, `last_page`, `ip`, `group`, `avatar`, `avatar_file_id`, `location`, `phone`, `address`, `city`, `state`, `country`, `zip`, `language`, `timezone`, `invite_token`, `invite_date`, `invite_sender`, `invite_accepted`)
VALUES
	(2, 1, 'Test', 'Bogus', 'info@rngr.org', '$2y$12$sY0dHz/UJ4Nbz9FvCncCQ.AFUkECTKFJg6wbKRBYjVa9Md3YH0U2y', '6ei6yUYDLioF0Dq4', 'QMe3PU1YBX70y4WJdw0m6DmQjXYwcFal', '5ae0f91ab7e94cdf67b99990e0c296afa3accd07', '', NULL, '', 1, '2017-05-17 22:47:50', '2017-05-17 22:57:05', '{\"path\":\"users\",\"route\":\"users\"}', '', 1, '//www.gravatar.com/avatar/98e33820f7d391d4295aceb4abb727e4?s=200&d=identicon&r=g', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'en', 'America/New_York', NULL, NULL, NULL, NULL);
```

**Comment by WellingGuzman** [comment]
can you share how you create Mr. Bogus user in the first place?

**Comment by benhaynes** [comment]
The SQL in the last comment... (added directly into database)

**Comment by WellingGuzman** [comment]
With an existing password? I thought it was the result. testing now.

**Comment by benhaynes** [comment]
The second password check should only be blue if the passwords *match*.

Don't allow the modal to be closed (and no close button in top-right).

I added a "Go Back" button to the bottom of the last pane, let's get that working.

**Comment by benhaynes** [comment]
Whew – finally done! Awesome job Welling...
