### ISSUE TITLE
Conditions broken in Flows

### ISSUE THREAD

**Issue by andy1li** [directus/directus#14729]
### Describe the Bug

It's same bug in https://github.com/directus/directus/issues/13855.

Sorry to open the same issue again, but #13855 was closed incorrectly because the issue persists.

### To Reproduce

Check #13855.

### Errors Shown

```
[
  {
    "details": [
      {
        "path": [
          "$trigger",
          "payload",
          "status"
        ],
        "type": "any.only",
        "context": {
          "key": "status",
          "label": "$trigger.payload.status",
          "value": "bbb",
          "valids": [
            "aaa"
          ]
        },
        "message": "\"$trigger.payload.status\" must be [aaa]"
      }
    ],
    "_original": {
      "$last": {
        "keys": [
          "0ce1bf8b-9357-492c-b488-d737e0cfc994"
        ],
        "event": "Foo.items.update",
        "payload": {
          "status": "bbb"
        },
        "collection": "Foo"
      },
      "$trigger": {
        "keys": [
          "0ce1bf8b-9357-492c-b488-d737e0cfc994"
        ],
        "event": "Foo.items.update",
        "payload": {
          "status": "bbb"
        },
        "collection": "Foo"
      },
      "$accountability": {
        "ip": "127.0.0.1",
        "app": true,
        "role": "d6c8d1b5-6c80-4a9e-87ca-9a591568c370",
        "user": "bb2efb5c-8a00-402e-9fd1-d708fd1d5479",
        "admin": true,
        "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
        "permissions": []
      }
    }
  }
]
```

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

16.16

### What database are you using?

mysql  ver 8.0.28

### What browser are you using?

chrome

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
This looks like a different issue to me. The OP you're referring to had the problem that it wouldn't accept `$trigger` to be read in the first place, which is not what you're seeing.

From the JSON you've shared, I'm seeing `\"$trigger.payload.status\" must be [aaa]` with a context of 

```json
{
  "context": {
    "key": "status",
    "label": "$trigger.payload.status",
    "value": "bbb",
    "valids": [
      "aaa"
    ]
  }
}
```

which to me looks like the validation is configured to check that `$trigger.payload.status _eq 'aaa'`, but you've submitted `status = bbb`?

What rules configuration did you use for the operation?

**Comment by andy1li** [comment]
Turns out the issue was fixed.

It's just that I was actually on 9.14.2 because of #14678.

**Comment by andy1li** [comment]
Thank you, @rijkvanzanten, for the super quick reply! 

Sorry for incorrectly reported issue. 

Yes, I was having the `"message": "\"$trigger.payload\" is not allowed"` error on my server (which was running 9.14.1 because of https://github.com/directus/directus/issues/14678). 

The error `$trigger.payload.status\" must be [aaa]` came from my local 9.14.5. Pasted it without looking closely enough. Sorry again.
