### ISSUE TITLE
Comments not being displayed all the time in the APP

### ISSUE THREAD

**Issue by goggi** [directus/directus#14755]
### Describe the Bug

If a item has comments the comments are not always displayed when looking at the item. If I clear the catch the comments become visible, but then if I reload the page again the comments are not displayed. It seems a bit random when it works and does not.

I have tested this on
1. Arch - Firefox
2. Arch - Chromium
3. Arch - Edge
4. OSX - Safari
5. OSX - Vivaldi

With the same issue. 

### To Reproduce

[recording_20220730-125120.webm](https://user-images.githubusercontent.com/1946339/181907777-acfad714-e494-422d-9bf0-f3be726cbfa0.webm)

### Errors Shown

What I have noticed is that the APP is missing the item id when doing the activity call to the api. 
ex:
When the comments are available it looks like this:
activity?filter[collection][_eq]=import_catalog_sections&filter[item][_eq]=00080908-f890-4004-9f82-20c782945839&filter[action][_eq]=comment&sort=-id&fields[]=id&fields[]=action&fields[]=timestamp&fields[]=user.id&fields[]=user.email&fields[]=user.first_name&fields[]=user.last_name&fields[]=user.avatar.id&fields[]=revisions.id&fields[]=commen
When the comments are missing it looks like this:
activity?filter[collection][_eq]=import_catalog_sections&filter[item][_eq]=%2B&filter[action][_eq]=comment&sort=-id&fields[]=id&fields[]=action&fields[]=timestamp&fields[]=user.id&fields[]=user.email&fields[]=user.first_name&fields[]=user.last_name&fields[]=user.avatar.id&fields[]=revisions.id&fields[]=comment

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

16.15.0

### What database are you using?

Postgres 13

### What browser are you using?

See description

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Thanks for the extensive testing! I believe this is what's reported in #14608 👍 

The gist of it is there's a split second where the ID is `+` at the start, instead of the current item's ID due to a recent change, hence the odd "intermittent" nature of loading of sidebar widgets like revisions/comments (you should also see revisions are getting fetch twice, with the first one being the wrong ID).

**Comment by goggi** [comment]
Great!! I'll keep track of it in the other issue then. Thanks!
