### ISSUE TITLE
Empty page when all fields are hidden

### ISSUE THREAD

**Issue by joselcvarela** [directus/directus#14768]
### Describe the Bug

If we create a collection and all fields are hidden, by setting them explicitly or hidden by permissions, then if we go to a content item of that collection a blank page is shown without any information:
![image](https://user-images.githubusercontent.com/14039341/182077122-f449dc3d-ac59-49ad-9965-1cae7549cb7e.png)

We should add some sort of notice just to let know that this is expected and not a bug.

We may need Ben's abilities 😄 

### To Reproduce

For example, create a collection with only system fields, then go to the content section of that collection.

### Errors Shown

None, only an empty interface which may seems like a bug.

### What version of Directus are you using?

9.14.5 (main)

### What version of Node.js are you using?

v16.14.2

### What database are you using?

postgis/postgis:13-3.1-alpine

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by NigmaX** [comment]
@joselcvarela @azrikahar we need to make sure that when you open a relational form (m2m, m2a) in which all fields there are hidden by default, you will NOT see any message as it will look weird to see a message at the bottom. :)

**Comment by rijkvanzanten** [comment]
> @joselcvarela @azrikahar we need to make sure that when you open a relational form (m2m, m2a) in which all fields there are hidden by default, you will NOT see any message as it will look weird to see a message at the bottom. :)

In the case of the relational forms, the notice should only show up when both form fields are "empty" (fully hidden)
