### ISSUE TITLE
Cannot create/edit fields in collections that is just created. Data is not visible for those collections.

### ISSUE THREAD

**Issue by tasozgurcem11** [directus/directus#14775]
### Describe the Bug

<img width="883" alt="image" src="https://user-images.githubusercontent.com/71333156/182124006-9de664a3-5fd3-4eca-bc37-af7cee900c6c.png">

So I have 11 different collections that are working perfectly. But for the collections that I am creating after those, for example, **country** as it's seen in the image above, it doesn't let me add fields and I can't even see the data.

Edit: This problem occurred for no reason and somehow I can't add new collections properly. As mentioned, other collections that were created previously are working well.

### To Reproduce

Cannot give reproduce steps, because the problem occurred all of a sudden. 

### Errors Shown

```
{
  "errors": [
    {
      "message": "You don't have permission to access this.",
      "extensions": {
        "code": "FORBIDDEN"
      }
    }
  ]
}
```

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

12.0.0

### What database are you using?

PostgreSQL 13.5

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
Mind sharing a database dump of where this is happening? Do you have any other services attached (like Redis etc)? Does the problem persist after restarting Directus? Did you configure the collections any different from the ones that do work? Based on the information currently presented, there isn't really anything we can debug against, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Comment by tasozgurcem11** [comment]
**Do you have any other services attached (like Redis etc)?**
Yes, Redis is also attached.

**Does the problem persist after restarting Directus?**
The problem occurs even restarting Directus.

**Did you configure the collections any different from the ones that do work?**
No that's the problem. Somehow Directus is not working properly. Working ones are the ones that are created previously. Now, it doesn't matter how/where you create it, it doesn't let me add any field to the collection AND it doesn't show the primary key field after creation. So I believe it's something related to field access. But it does let me create fields for an older collection. So everything works perfectly for previous collections but not ones that are new.

**Comment by rijkvanzanten** [comment]
Mind sharing a database dump of a minimal reproduction where this is happening consistently?
