### ISSUE TITLE
Hide Options Tab when changing Interface

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1477]
When changing an interface, it should HIDE the Interface options (not show the options for the current/previous interface).

**Comment by benhaynes** [comment]
This change ALWAYS hides the tab... it should only be hidden when the user CHANGES the Interface dropdown.

**Comment by WellingGuzman** [comment]
It's working as expected to me, can you show me the steps you are doing?

Mine:
1. Click any column (Options Visible)
2. Change Interface (Options hidden)
3. Change back to the original Interface (Options Visible)

**Comment by WellingGuzman** [comment]
Never mind, one file wasn't committed. (Closed by https://github.com/directus/directus/commit/694c4bc97a1074f859d670f69a8eb31501762443)
