### ISSUE TITLE
Duplicated items in different level filters

### ISSUE THREAD

**Issue by martinomg** [directus/directus#14779]
### Describe the Bug

I'm trying to filter a collection by 2 different levels (to get project_updates relevant to an specific user, on projects where it could be the leader or could be a member), and the response show duplicated items which i would say is expected because i'm iterating over another child-collection (is it expected this behaviour?), but it has more than 1 duplicated item in some cases. Does it makes sense to behave like this? is there any way to ensure only unique items will be returned in the response? 

### To Reproduce

Here's the detail of 2 requests for different users.

Case #1, Filter #1 (filter_count: 7)
![image](https://user-images.githubusercontent.com/5248081/182180863-d7d4f8b7-790d-4ee7-80f2-e070fae22002.png)

Case #1, Filter #2 (filter_count: 4)
![image](https://user-images.githubusercontent.com/5248081/182180957-ca2ba1e5-80a2-4e29-aba5-c0cd25e491e1.png)

Case #1, Combined filters (filter_count: 17) 7 + **(8 x 3)** = 17
![image](https://user-images.githubusercontent.com/5248081/182180677-19b5d15b-b8dd-4c16-bdd8-54a9e6f4791c.png)

Case #2, filter #1 (filter_count: 13)
![image](https://user-images.githubusercontent.com/5248081/182181238-3df354b3-7f3e-4c28-bd3b-18e9573395cf.png)

Case #2, filter #2 (filter_count: 7)
![image](https://user-images.githubusercontent.com/5248081/182181309-2a417d74-de2c-4186-b4eb-c77ee666a0a4.png)

Case #2, Combined filters (filter_count: 27) 13 + **(7 x 2)** = 27
![image](https://user-images.githubusercontent.com/5248081/182181395-d2deff7a-48f6-4e51-bfef-15fbb62592e2.png)

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

14.16.0

### What database are you using?

MySQL / MariaDB / Percona 10.3.34

### What browser are you using?

chrome

### How are you deploying Directus?

Self Hosted, Ubuntu + plesk

**Comment by licitdev** [comment]
Related to #11445 and #13107 on duplicated results

**Comment by rijkvanzanten** [comment]
@licitdev Lets combine these issues onto #13107 so we have a single place to track the progress of the underlying JOIN bug 👍🏻

**Comment by rijkvanzanten** [comment]
Closed in favor of https://github.com/directus/directus/issues/13107 (same underlying problem, aggregating the issues there)
