### ISSUE TITLE
Running `npm run build` on an extension of type `operation` fails

### ISSUE THREAD

**Issue by genu** [directus/directus#14797]
### Describe the Bug

I believe it may be because the `@directus/extensions-sdk` is still published as `9.14.4` on NPM, so it doesn't know how to build an `operation` type extension?

![CleanShot 2022-08-02 at 10 21 02](https://user-images.githubusercontent.com/928780/182397980-153bc5db-df54-47d0-9eb6-1328f943dbea.png)

### To Reproduce

Create an extension using `npm init directus-extension`

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

16.16.0

### What database are you using?

Postgres 13

### What browser are you using?

N/A

### How are you deploying Directus?

N/A

**Comment by azrikahar** [comment]
I have just tested this on the latest version 9.16.1 and it works. Closing this as it should be resolved by #14410 back in 9.15.0.

---

Brief explanation of the timeline: OP opened this issue on August 2nd, but version 9.15.0 with #14410 (official support for operations extension) was only released on August 4th.
