### ISSUE TITLE
Stuck value with Offset/Page

### ISSUE THREAD

**Issue by kuzmi4** [directus/directus#14804]
### Describe the Bug

https://user-images.githubusercontent.com/6544815/182544405-f3ca8805-a17b-4bf3-b977-723a8541cf9c.mov

Problem in stuck value in query with offset

Directus cache mode - disabled
DB: Postgres 13
ID: Uniq

Table DDL

```
CREATE TABLE public.author (
	id uuid NOT NULL,
	sort int4 NULL,
	date_created timestamptz NULL,
	date_updated timestamptz NULL,
	first_name text NULL,
	last_name text NULL,
	middle_name text NULL,
	full_name text NULL,
	CONSTRAINT author_full_name_unique UNIQUE (full_name),
	CONSTRAINT author_pkey PRIMARY KEY (id)
);
```

 

### To Reproduce

Don't, know how exactly it can be reproduced, I have simple  data collections.

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

16.16.0

### What database are you using?

Postgres 13

### What browser are you using?

Safari

### How are you deploying Directus?

Docker

**Comment by kuzmi4** [comment]
@br41nslug any idea which information can help?

**Comment by br41nslug** [comment]
Thats a strange situation 🤔 Could you try adding an explicitly sorting to the query to see if it persists?

**Comment by kuzmi4** [comment]
Maybe I find reason

U Idea with sorting - working:

https://user-images.githubusercontent.com/6544815/182556298-2f5d97a9-041f-4d61-b40b-4562653f8037.mov



So I checked data in table and found that i have sort column with all Null data, and collection setting in directus has setting "sort" with this column.

<img width="477" alt="screen 2022-08-03 в 11 00 52" src="https://user-images.githubusercontent.com/6544815/182556528-46b40d2a-0b1e-4204-a332-7a2b30bc65b9.png">

I deleted this column, and now its, work find 🤔

https://user-images.githubusercontent.com/6544815/182557296-c85fa37f-b291-4794-ba33-1470e6691684.mov

### BUT 🤔 🤔 another collections doesn't have sort columns and have the same bug.

So at one moment I have 1 working collection and 4 with problem. 🤔 🤔 🤔

So, i restarted the directus container and got the same problem with **ALL** collections ;)

It look like problem with default sort strategy in directus, and solution at this moment is manual sorting by ID.

**Comment by br41nslug** [comment]
Interesting having a sort column with all `null`s could be causing "random access" or randomized sorting for each query. Do you have a sort field selected for all your collections? could you double check and "deselect" sort fields for collections where you're not doing manual sorting (otherwise the column will never be filled). Setting this sort column is in my eyes not the "default sort strategy" as you have to explicitly add the sort column and then never sort to get this behavior.

**Comment by br41nslug** [comment]
As i don't think this is a core bug i'll be closing this issue for now. There may be room for improvement here on how to handle such sorting but thats better done in a discussion 😄

**Comment by kuzmi4** [comment]
U a re right, I found a reason on my side, refuting the problem in the sorting strategy. 😄

I check that all collection have deselect sort field, and at now all work find 

![image](https://user-images.githubusercontent.com/6544815/182565755-bb9e03d5-e908-45f7-9f57-85f5a1707569.png)
