### ISSUE TITLE
transform can not work on json object

### ISSUE THREAD

**Issue by imiskolee** [directus/directus#14814]
### Describe the Bug

transform operator can not work if the input is a JSON object

### To Reproduce

1.  create a transform operator
2. set content to `{"id":"1"}`,
3. transform operator showing red point on flows log.

### Errors Shown

When I add a debug on api/src/flows.ts#L395, it's showing

`
Exception flow SyntaxError: Unexpected token o in JSON at position 1
`

because of the content removed quote, it's `{id:'1'}`

![Uploading image.png…]()

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

16.5.4

### What database are you using?

Postgres 12

### What browser are you using?

Chrome 

### How are you deploying Directus?

Locally

**Comment by rijkvanzanten** [comment]
@nickrum any immediate thoughts?

**Comment by nickrum** [comment]
Coincidentally, I just ran into the exact same issue while testing something else. I'll push a fix 👍
