### ISSUE TITLE
Minimum and maximum integer value not enforced on item create

### ISSUE THREAD

**Issue by JohnHillegass** [directus/directus#14823]
### Describe the Bug

When creating an item in a collection with an input field that has a minimum and maximum integer value set, I am finding that I can still input values outside of that range. For example if its 0-100, when creating I can set the value to -100 or 1000. I cannot do this on item updates, just on creation. My expectation is that the input validation would also be done before submitting the create. Currently this issue can be worked around by adding a validation rule.

### To Reproduce

Create a collection called Thing with a field called Percentage
Set the Percentage field Minimum value to 0 and Maximum value to 100
Create a Thing and set the Percentage to -100 then save

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

16.16.0

### What database are you using?

Postgres 11

### What browser are you using?

Edge

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
This is correct. The interface options only control the UI input in use, it doesn't control any validation on the API side or limit the submitted value in any way. That's what validation/permissions are for 🙂

**Comment by JohnHillegass** [comment]
This makes sense to me. Hadn't considered the complexity of sending via an API call. These steps were all performed in the UI though. @rijkvanzanten do you agree it should have enforced it at the input field level when creating via UI?

**Comment by rijkvanzanten** [comment]
I believe the `input` interface min / max operate identically to a regular html `<input type="number" />` `min` and `max` attribute, in that they only really control how the up/down arrows function 🤔
