### ISSUE TITLE
Automatic refresh after form validation

### ISSUE THREAD

**Issue by mhdaouas** [directus/directus#14822]
### Describe the Bug

I added a hiding condition to a form field and when I change a value on which depends that condition (another field) and validate by clicking the green checkmark button, the field is still displayed. It seems like an automatic refresh of the form is needed after any validation.

### To Reproduce

See above

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

14

### What database are you using?

PostgreSQL

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally with Visual Code

**Comment by azrikahar** [comment]
I believe this is the same as #14285 which is a bug on 9.13.0.

It was then resolved by #14488 in 9.14.2. Can you try with that version or later? We'll reopen if it turns out to be something different.
