### ISSUE TITLE
Breaking change from v9.9.1 , APP assets path ignore PUBLIC_URL 

### ISSUE THREAD

**Issue by enzolupia** [directus/directus#14821]
### Describe the Bug

Hi, we used Directus v.9.8 for some time in a multi-project environment.
Basically we have multiple Directus instances hosted on the same domain but on different context-root.
Something like:

- mydomain.com/project1
- mydomain.com/project2
- mydomain.com/project3

Each project has the PUBLIC_URL configured to mydomain.com/{{projectID}}

Everything is working fine with v.9.8.0

We tried to upgrade to a newer version but we noticed that starting from v9.9.1 Directus APP stopped working, apparently because some assets loaded by the APP are not loaded properly. 

In particular, this is one of the resources that is currently loaded by the APP with version 9.8.0
![image](https://user-images.githubusercontent.com/32568361/182621680-9d7f05b7-76e0-48b0-ae7f-73d66efeb1cb.png)

While, this is the same resource, loaded by the APP with version 9.9.1
![image](https://user-images.githubusercontent.com/32568361/182621965-ef0a1cd9-d6fc-4b5b-8fbb-1022e2eaf924.png)

Please notice that in the second case, the asset path does not contain the project context-root, thus resulting in a 404 error.
 

### To Reproduce

- Install a new instance with version 9.9.1
- Configure a PUBLIC_URL so that the instance is reachable on a non-root path, i.e. /project1
- Verify if the APP is correctly loading

### Errors Shown

Login page is blank.

![image](https://user-images.githubusercontent.com/32568361/182622853-be1f70a5-fdbe-429f-b3ab-f68e48c37098.png)

### What version of Directus are you using?

9.9.1

### What version of Node.js are you using?

16.14.2

### What database are you using?

Postgres 10.19

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by br41nslug** [comment]
Can you test if the problem persists with the latest version 9.14.5? there have been a few fixes around that subject since 9.8

**Comment by enzolupia** [comment]
@br41nslug already tried with the latest version and I got the same result, I tried different versions and It turned out that the problem was introduced in version 9.9.1.

**Comment by br41nslug** [comment]
I've pulled in the 9.9.1 version to be sure and tested with the latest and am unfortunately not able to reproduce it so far. Both versions look to be generating the correct paths:
![image](https://user-images.githubusercontent.com/9389634/182632571-f9778c54-b13a-463e-96c9-b07fb79ef0a8.png)
(tested with images `directus/directus:9.9.1` and `directus/directus:9.14.5`)

My test setup is very basic with minimal configuration, are there other factors we need to consider like a reverse proxy rewriting  paths or anything like that?

**Comment by rijkvanzanten** [comment]
This seems to work on my end as well. Simply setting the `PUBLIC_URL` to `https://rijks.website/testing` will correctly use `/testing` as the root relative, and set the `<base>` tag in HTML accordingly: `<base href="/testing/admin/" />`. Setting `PUBLIC_URL` to `/testing` also results in the same behavior.

We haven't been able to reproduce this based on the given information, so I'll this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Comment by enzolupia** [comment]
Thanks, I'll try to investigate more and figure out what configuration may cause such error.

I'll keep this thread updated if I discover something new.
