### ISSUE TITLE
Missing relationship field in side drawer.

### ISSUE THREAD

**Issue by u12206050** [directus/directus#14832]
### Describe the Bug

I'll explain as an example:

Two collections: Orders and OrderLines.
And order has one2many order lines.

When viewing a specific order line and clicking on its' order, the drawer opens up to display all the fields. However I am unable to view what other order lines are on that order.

### To Reproduce

As mentioned above.

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

chromium

### How are you deploying Directus?

Locally & GCP

**Comment by rijkvanzanten** [comment]
Recursive relational fields show included "readonly" rather than removed completely 👍🏻
