### ISSUE TITLE
Long text labels causing CSV Checkboxes field to overflow

### ISSUE THREAD

**Issue by koksikus** [directus/directus#14835]
### Describe the Bug

When creating a field with checkboxes and setting it to half the width, if the description is longer than the intended one, the field becomes longer and does not keep the given width. The text should wrap or end ... so that the field width matches that given

### To Reproduce

Create a field with checkboxes and setting it to half the width. In the interface, add another field and extend the description so that it goes beyond the width of half the width of the field. Having 2 columns and this field when will be on the right will be wider than the other fields...

### What version of Directus are you using?

9.12.1

### What version of Node.js are you using?

16.15

### What database are you using?

Sql server 2017

### What browser are you using?

Edge

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
Mind sharing a screenshot of what you mean? I'm a little confused as to what the problem is 🙂

**Comment by koksikus** [comment]
I checked in the latest version of directus - the error still exists. The position of the field does not matter, it does not have to be on the right side. If it is on the left, it enters the space on the right side field.

![Zrzut ekranu 2022-08-03 214249](https://user-images.githubusercontent.com/90528895/182695791-66308ce2-dff3-4208-bb26-17d4827cc864.jpg)

**Comment by davydhyk** [comment]
![image](https://user-images.githubusercontent.com/22622242/182728149-3e89cb89-6131-4cc3-94be-84fed94d1f67.png)
```
directus: {
  version: '9.14.5'
}
```
```
node: {
  version: '16.10.0'
}
```

**Comment by koksikus** [comment]
in my case, type field is csv ... 
do you remember about #14033 :)

**Comment by koksikus** [comment]
My thoughts, if the text is hiding now, how do I see the rest of the text? Will a window pop up with the entire description after hovering the cursor over it? 
However, is it best to shorten the text so that it is fully readable...

**Comment by azrikahar** [comment]
> My thoughts, if the text is hiding now, how do I see the rest of the text? Will a window pop up with the entire description after hovering the cursor over it? However, is it best to shorten the text so that it is fully readable...

That is being discussed in #13964! A tooltip would be a good improvement indeed.

**Comment by koksikus** [comment]
Thanks, I just wrote there, that the best solution is a popup window that would show all the content. This could be applied to every field and view - possibly an option to turn it off in the settings. When viewing the table, it would solve the problem that you have to click on each record to view the content or to make the photo larger...
