### ISSUE TITLE
Import a file from the web - URL with special characters didn´t work

### ISSUE THREAD

**Issue by hermesalvesbr** [directus/directus#14848]
### Describe the Bug

I'm trying to import a url from a website in Brazil, the language is Brazilian Portuguese. This language has special characters, like á é í ó ú. 

`BUGOU _> https://www.araripina.pe.gov.br/wp-content/uploads/2017/02/Saúde.png - [object Object] - Error: Couldn't fetch file from url "https://www.araripina.pe.gov.br/wp-content/uploads/2017/02/Saúde.png"`

**Error: Couldn't fetch file from url**

### To Reproduce

```
{
	"url": "https://www.araripina.pe.gov.br/wp-content/uploads/2017/02/Saúde.png",
	"data": {
		"title": "Saúde"
	}
}
```

### Errors Shown

`https://www.araripina.pe.gov.br/wp-content/uploads/2020/07/Decreto-nº-055-2020-Define-novas-medidas-de-prevenção-e-controle-para-enfrentamento-da-COVID-19-no-âmbito-do-município-de-Araripina-PE-2.pdf - [object Object] - Error: Couldn't fetch file from url "https://www.araripina.pe.gov.br/wp-content/uploads/2020/07/Decreto-nº-055-2020-Define-novas-medidas-de-prevenção-e-controle-para-enfrentamento-da-COVID-19-no-âmbito-do-município-de-Araripina-PE-2.pdf"`

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

14

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by licitdev** [comment]
| File Name  | Can Import  |
|---|---|
| [red.png](https://licit.dev/files/red.png)  | ⭕  |
| [réd.png](https://licit.dev/files/réd.png)  | ❌  |
| [紅色.png](https://licit.dev/files/紅色.png)  | ❌  |
| [紅色réd.png](https://licit.dev/files/紅色réd.png)  | ❌  |

**Comment by hermesalvesbr** [comment]
This works for me now:  `url =  encodeURI(url)`
