### ISSUE TITLE
Medium Editors are not being destroyed

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1485]
When the framework creates the `medium-editor` (WYSIWYG Interface) they are not destroyed when not in use and they build up in the DOM... causing layout/scroll issues:

![screen shot 2017-05-14 at 11 23 33 pm](https://cloud.githubusercontent.com/assets/522079/26041671/ae4c03e8-38fc-11e7-8f14-1e006e433ec1.png)

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/af80926635c05ba42535329b4cdf0b3c41f09633
