### ISSUE TITLE
invalid input syntax for type uuid: "$CURRENT_USER"

### ISSUE THREAD

**Issue by fbernalm93** [directus/directus#14857]
### Describe the Bug

I can't use the dynamic variable $CURRENT_USER in filters when I use a function readByQuery(), for a query for a current user as a parameter.

The permissions in the section, Role and Permission, in the Public Section, allow view collections directus/users and directus/roles.

### To Reproduce

```js
const orderService = new ItemsService("orders", {
  schema: context.schema,
  accountability: context.accountability,
});
const usagePerUser = await orderService.readByQuery({
  filter: {
    connected_user: {
      _eq: "$CURRENT_USER",
    },
  },
});
```

### Errors Shown

```
error select "orders"."id", ..... fields of the table..... where "orders"."connected_user" = $1 order by "orders"."sort" asc limit $2 - invalid input syntax for type uuid: "$CURRENT_USER" 
```

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

18.2.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome and Safari for test

### How are you deploying Directus?

AWS

**Comment by br41nslug** [comment]
Is the `accountability` object filled? there is no current user context if thats undefined.

**Comment by rijkvanzanten** [comment]
It's unclear in the code example what `context` is, so I'm not sure if this is a bug in the service, or a typo/mistake in the extension itself.

I haven't been able to reproduce this based on the given information, so I'll this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻
