### ISSUE TITLE
Cannot delete a field in data model

### ISSUE THREAD

**Issue by nordcart** [directus/directus#14865]
### Describe the Bug

Cannot delete fields

### To Reproduce

Delete a field of a collection in data model

### Errors Shown

![image](https://user-images.githubusercontent.com/12813484/183023222-13299258-a0a8-45b2-ba4f-93f9d823aa10.png)

### What version of Directus are you using?

9.15.0

### What version of Node.js are you using?

dont know

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Seems very much like #9896 #9092 #8675. Do try out the breaking change upgrade instructions quite a while ago, as mentioned over here: https://github.com/directus/directus/issues/8675#issuecomment-940629829 and here: https://github.com/directus/directus/issues/8675#issuecomment-940940506 (I assume it was never done in this particular Directus instance) 👍
