### ISSUE TITLE
Duplicate constraint name error

### ISSUE THREAD

**Issue by falmanna** [directus/directus#14873]
### Describe the Bug

I am getting the error `duplicate constraint name` whenever I try to:

1. Create a O2M field on an existing M2O relation
2. Alter existing O2M field

### To Reproduce

Directus `v9.14.5`
CockroachDB serverless on version `v22.1.4` (latest)

Case 1:
Create M2O on a table without creating O2M alias.
Try to create an alias on the parent table.

Case 2:
Create M2O relations with O2M alias
Try to change the relational trigger

Tried the same changes on localhost with SQLite and all worked without a problem. 
If there is a limitation I think it should be handled without throwing 5xx error.

### Errors Shown

```
{
  "errors": [
    {
      "message": "alter table "table_name" add constraint "constraint_name" foreign key ("key") references "key" ("id") on delete CASCADE - duplicate constraint name: "constraint_name" ",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### What version of Directus are you using?

v9.14.5

### What version of Node.js are you using?

16-alpine

### What database are you using?

CockroachDB serverless v22.1.4

### What browser are you using?

Chrome

### How are you deploying Directus?

Google Cloud Run

**Comment by florianbepunkt** [comment]
This prevents not only altering existing O2M relationships, but also creating new ones.

**Comment by falmanna** [comment]
@florianbepunkt I can create, but can't edit any relation field. Looks like @br41nslug figured it our in the referenced PR, hopefully, a patch is coming :)

**Comment by kevincam3** [comment]
I don't know if my problem is related but I'm getting this error when I try to add the "Created By" annd/or "Updated By" fields.

See attached video

https://user-images.githubusercontent.com/870934/201475484-12ad0de7-80e2-4f98-9172-a9cd55ec1052.mp4

**Comment by florianbepunkt** [comment]
@br41nslug Thank you. Is there an ETA for when this is released?

**Comment by br41nslug** [comment]
Don't have an actual ETA of the next release but it will be in the next 😄
