### ISSUE TITLE
Strict Naming JS is breaking cursor/arrows

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1491]
There's no way to go back with arrows to make corrections in these inputs because the text cursor/caret is ALWAYS at the end of the text.

**Possible solution:**
http://stackoverflow.com/questions/14508707/updating-an-inputs-value-without-losing-cursor-position

**Comment by WellingGuzman** [comment]
The link did the job, please confirm in your end to close it.

**Comment by benhaynes** [comment]
Perfect!
