### ISSUE TITLE
SVG Image preview in table is too big

### ISSUE THREAD

**Issue by flayks** [directus/directus#14926]
### Describe the Bug

I suppose it is sort of linked to [this issue](https://github.com/directus/directus/issues/14592), SVG image previews on a table mode are quite large/high as well, taking more height than available.

As of reference, the flags here are square.

<img width="315" alt="image" src="https://user-images.githubusercontent.com/273716/183307194-8b4f0e25-0bfe-45b8-8232-e4a385366c04.png">

### To Reproduce

Use an SVG image as a file and use it as a thumbnail in a table mode

### What version of Directus are you using?

Directus 9.15.1

### What version of Node.js are you using?

16

### What database are you using?

MariaDB

### What browser are you using?

Brvae

### How are you deploying Directus?

locally

**Comment by br41nslug** [comment]
Can you elaborate on the configuration you've used to get these images to fill out the entire row? I am unable to reproduce this so far in either Firefox or Chrome using flag svg test images.
![image](https://user-images.githubusercontent.com/9389634/183607503-8ab7971b-14ea-48a4-beed-7c220e00f93a.png)

**Comment by flayks** [comment]
> Can you elaborate on the configuration you've used to get these images to fill out the entire row? I am unable to reproduce this so far in either Firefox or Chrome using flag svg test images.
> 
> ![image](https://user-images.githubusercontent.com/9389634/183607503-8ab7971b-14ea-48a4-beed-7c220e00f93a.png)
> 
> 

Hm that is strange. My SVGs are 64x64px maybe that's why? Have you  tried with larger images?

**Comment by azrikahar** [comment]
@flayks just to confirm, are you using Related Values display template? as I believe Image or File display template behaves differently. It'd also be helpful if you can share the exact SVG you're using as well, if it's that okay.

**Comment by flayks** [comment]
@azrikahar oh nice, I believe that they are indeed related values!

Here is one of my flag images:
![flag-australia](https://user-images.githubusercontent.com/273716/183633758-e9fc9545-3056-4efa-95f1-d1c250f6929b.svg)

**Comment by azrikahar** [comment]
@flayks would you mind sharing the exact interface + display configuration? Unfortunately I'm having trouble replicating this setup like your original screenshot on my end.

**Comment by rijkvanzanten** [comment]
> @azrikahar oh nice, I believe that they are indeed related values!
> 
> Here is one of my flag images: ![flag-australia](https://user-images.githubusercontent.com/273716/183633758-e9fc9545-3056-4efa-95f1-d1c250f6929b.svg)

Is the Aboriginal flag used as the national flag for Australia nowadays, or is that just in your project? First time seeing it in use like this!

**Comment by flayks** [comment]
@azrikahar Not sure what you mean but here is what I have: Location is a collection including a Country relation field (which is another collection then)
<img width="431" alt="image" src="https://user-images.githubusercontent.com/273716/183688023-c3c7d54a-ec3e-4a1a-aa51-3fb70b71f12d.png">
<img width="846" alt="image" src="https://user-images.githubusercontent.com/273716/183687444-3a146161-8fad-4bef-8fbf-9e2c4b3c45d6.png">
<img width="949" alt="image" src="https://user-images.githubusercontent.com/273716/183687499-feef2c88-0cf0-4757-873b-98fbaa800ded.png">

@rijkvanzanten It is the official aboriginal flag used in Australia but often used with the "british" Australian flag. For some of us we prefer to acknowledge it alone as the true flag, but it's an intentional choice, as for the square size it's a design decision 😄

**Comment by azrikahar** [comment]
@flayks thanks for sharing! I'm now able to reproduce this with the shared SVG and the M2O configuration 👍

**Comment by flayks** [comment]
@azrikahar great! Glad I could help 🙌
