### ISSUE TITLE
Some JS events stop working randomly

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1493]
**STILL NEED STEPS TO REPRODUCE**

After navigating the user system, sometimes when going to Admin settings I can no longer click on Add New Column or the Interface option modals... it seems like all JS stops, but there are no console errors.

I will try to find a way to reproduce.

**Comment by rijkvanzanten** [comment]
I have noticed this myself as well. I'll post it here if I'm able to reproduce it

**Comment by WellingGuzman** [comment]
I found out that this seems to only happening when trying to open a modal window.
Somehow the container of the modal gets removed from the DOM which prevent modals from being opened.

How this container gets removed, that's what we need to find out.

**Comment by WellingGuzman** [comment]
When we open a overlay page we insert another view into the main content section, which put the parent view on insert mode, which deletes every child that has been rendered and does not has the `keep` flag set to `true` every time its parent render.
