### ISSUE TITLE
Unknown column 'NaN' in 'where clause when "Save as Copy" including Translation

### ISSUE THREAD

**Issue by joelamltc** [directus/directus#14944]
### Describe the Bug

I was trying to duplicate an item from a collection. Below are my model settings with translation.

![model1](https://user-images.githubusercontent.com/13143636/183406483-6fa32a63-5ce6-4118-870c-ae22ea4ca676.png)

<img width="1680" alt="Screenshot 2022-08-08 at 19 28 37" src="https://user-images.githubusercontent.com/13143636/183408231-16b3fea6-e302-4c99-b310-1d924ec24778.png">

![model2](https://user-images.githubusercontent.com/13143636/183406509-e9a2fc19-8a2c-4801-a183-4cd545eef95f.png)

![model3](https://user-images.githubusercontent.com/13143636/183406521-28dcfa57-85b4-442d-a4f9-2edfa3d8e4e5.png)
  
There was an error shown after the "Save as Copy" action. Though the model is duplicated with the correct translation.
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/13143636/183406811-bf318b59-b140-4690-8486-fb879b789b95.png">
Error detail:
```
{
  "errors": [
    {
      "message": "select `locations_translations`.`id`, `locations_translations`.`locations_id`, `locations_translations`.`name`, `locations_translations`.`languages_code` from `locations_translations` where `locations_translations`.`locations_id` = NaN order by `locations_translations`.`id` asc - ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### To Reproduce

I have attached a video to demo the error case

https://user-images.githubusercontent.com/13143636/183407600-20ec92b5-e9c7-40e7-8496-86ca76f033fe.mp4

### Errors Shown

<img width="1680" alt="Screenshot 2022-08-08 at 19 20 53" src="https://user-images.githubusercontent.com/13143636/183407274-6f12808c-329e-402f-bbd6-a207450d2126.png">

### What version of Directus are you using?

v9.15.1

### What version of Node.js are you using?

v14.18.3

### What database are you using?

mysql  Ver 15.1 Distrib 10.5.5-MariaDB, for osx10.15 (x86_64) using readline 5.1

### What browser are you using?

Version 103.0.5060.134 (Official Build) (x86_64)

### How are you deploying Directus?

Running locally

**Comment by rijkvanzanten** [comment]
@licitdev this smells very similar to https://github.com/directus/directus/issues/14209, could be related?

**Comment by licitdev** [comment]
Yes it's somewhat related as the typecasting of filter value was fixed for aliased fields.

For this issue, the app sends a request with an invalid ID in the following filter `{"locations_id":"+"}`, resulting in the `NaN`.

```
23:09:51 🔍 [21.758ms] select `locations_translations`.`id`, `locations_translations`.`locations_id`, `locations_translations`.`name`, `locations_translations`.`languages_code` from `locations_translations` where `locations_translations`.`locations_id` = ? order by `locations_translations`.`id` asc [NaN]
23:09:51 ✨ request completed GET 304 /items/locations_translations?fields[]=*&fields[]=id&fields[]=languages_code.code&filter=%7B%22locations_id%22:%22%2B%22%7D&page=1&limit=-1 35ms
```

**Comment by rijkvanzanten** [comment]
That should actually be a fairly easy fix then, as the interfaces should never fetch data for primary keys `+` from the app 🙂
