### ISSUE TITLE
Modal buttons (a11y)

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1495]
[BETA] The cancel / save buttons as well as the tabs have no visual indication of the focus state. Navigating the modal with the keyboard results in unexpected behavior

**Comment by benhaynes** [comment]
Yes, this is important to have. We _could_ use the outline property – or  look into a more styled approach. Do you have a preference Rijk?

**Comment by rijkvanzanten** [comment]
Ben, an outline is the most recognizable focus style, but also quite an "ugly" one style wise. I recommend a double box-shadow (one bg color, one primary blue) which creates the ring effect but in style

**Comment by benhaynes** [comment]
Ahh, I like that! I haven't used double-box-shadows but will give that a try!

**Comment by benhaynes** [comment]
Added! I also updated some of the interfaces to use `<buttons>` instead of divs with a `.button` class... we'll want to update all of them in the interfaces though (and give tab-indexes to important non-buttons)

**Comment by rijkvanzanten** [comment]
(For later reference) It was fixed in this commit: 72391d470f19e00969e49b951d4e95d5cd3adab6
