### ISSUE TITLE
"Copy Link" from "Shares" does not work

### ISSUE THREAD

**Issue by hugopvl** [directus/directus#14955]
### Describe the Bug

when we try to use the "copy link", from "shares", the information is not copied to the transfer area, so when you paste, nothing is returned.

### To Reproduce

Create a new share and use the copy link option.

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

MSSQL

### What browser are you using?

chrome

### How are you deploying Directus?

locally. on debian server

**Comment by br41nslug** [comment]
I am unable to reproduce this using Chrome or Firefox on the latest version

https://user-images.githubusercontent.com/9389634/183595338-9aa97e62-7b69-4198-a02f-7506deead0cc.mp4

**Comment by hugopvl** [comment]
Good afternoon,
I already found out where the problem was, I don't know if it's intentional or not, if I enter directus through the address that is in the project url. ex: www.pocdesign.pt the copy link option works perfectly, but if I enter directus through the ip/port, ex: 198.168.100.100:8055 the copy link option does not work.

**Comment by br41nslug** [comment]
Interesting with your `PUBLIC_URL` set to the domain presumably 🤔 that sounds to me like it could possibly be a browser security measure

**Comment by rijkvanzanten** [comment]
> Interesting with your `PUBLIC_URL` set to the domain presumably 🤔 that sounds to me like it could possibly be a browser security measure

I think Chrome requires HTTPS for the copy to clipboard to function. It has an exception for `localhost`, but that doesn't help in this case.
