### ISSUE TITLE
LOCK_WAIT_TIMEOUT error when using hook to update a specific row

### ISSUE THREAD

**Issue by MajedMuhammad** [directus/directus#14961]
### Describe the Bug

Custom hooks can be fired at the same time. Especially when we use it with createMany (Item service). Whether actions or filters are used, the same issue will happen. 

Let me drop a scenario to explain the issue here: 
I've a buildings table, and a row with id: 1. 
Now I am going to update that row (id: 1) with a calculated value whenever I have new floor added. 
User has added new floors (1, 2) to the building (id: 1). We will be using createMany to create those floors. 
If we have counter hook to update the building whenever we have new floors being added, the hook will be fired two times:
1. with floor (1)
2. with floor (2)
Now inside the hook, we are going to update the building row (id: 1) to calculate the num_floors (number of floors).
building (id: 1) is being accessed two times in the same time. Which causes a  LOCK_WAIT_TIMEOUT error. 

### To Reproduce

Try to update a specific row using hooks.

### Errors Shown

LOCK_WAIT_TIMEOUT error

### What version of Directus are you using?

9.14.2

### What version of Node.js are you using?

16.3.0

### What database are you using?

MySQL

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by licitdev** [comment]
@rijkvanzanten This looks to be an improvement for endpoints with `createMany()`. 

Can we add a `emitActionSync()` which emit the action events sequentially when a query parameter (`emitActionSync` perhaps) is provided?

The implementation should be possible after #14981 is merged as that enables the extraction of action events.

**Comment by rijkvanzanten** [comment]
@licitdev Just so I understand correctly, the problem here is that the custom action triggers in parallel instead of sequentially? If that's the case, they might want to use a `filter` instead of an `action`, as that's `await`ed on purpose. I don't think we'd want to tweak actions necessarily, as they're meant to be "async"

**Comment by licitdev** [comment]
> Whether actions or filters are used, the same issue will happen.

@MajedMuhammad You've mentioned that the same issue occurs when `filter` hook is used. 
Please provide a sample extension that triggers the `LOCK_WAIT_TIMEOUT` error. Thanks!

**Comment by MajedMuhammad** [comment]
>  If that's the case, they might want to use a filter instead of an action, as that's awaited on purpose. 
I want to update a specified row after the event occurrence not before so I have to use "action".

**Comment by MajedMuhammad** [comment]
> > Whether actions or filters are used, the same issue will happen.
> 
> @MajedMuhammad You've mentioned that the same issue occurs when `filter` hook is used. Please provide a sample extension that triggers the `LOCK_WAIT_TIMEOUT` error. Thanks!

@licitdev I modified the logic and it is not happening anymore with `filter`

**Comment by licitdev** [comment]
> I modified the logic and it is not happening anymore with `filter`

@MajedMuhammad Thanks for confirming. Closing as there's no longer an issue.
