### ISSUE TITLE
Column in where clause is ambiguous

### ISSUE THREAD

**Issue by lehha** [directus/directus#1496]
Broken SQL query on filter if it have a Multi-to-One link: column name same in both tables.

Message was:
```
Server Error
This query failed: 
SELECT 
`calls_clients`.`id` AS `id`,
`calls_clients`.`active` AS `active`,
`calls_clients`.`status` AS `status`
FROM `calls_clients` 
LEFT JOIN `class_call_status` ON `class_call_status`.`id`=`calls_clients`.`status` 
WHERE `calls_clients`.`active` IN ('1') AND status = '6' 
ORDER BY `id` ASC 
LIMIT 100 OFFSET 0
```

Table class_call_status have that:
id, active, status (varchar)

  - Directus version and branch: 6.3.9
  - PHP version: 5.6
  - MySQL version: 5.1.73
  - Web server: Apache
  - OS name and version: CentOS 6.9

## Expected Behavior
in Where statement must be fully qualify: ... AND `calls_clients`.`status` = '6' 

## Actual Behavior
Where have a short statement: ... AND status = '6' 

## Steps to Reproduce
 1. Add field in table with Many-to-One link, name same in both tables
 2. Try to view items by filter.

In field setting value of "Filter Column" fully qualify = calls_clients.status, but filter request anyway came short and wrong.

**Comment by benhaynes** [comment]
This is a great find @lehha! We will make sure that all columns are fully qualified in `v6.4` and make sure this isn't happening any more.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/cb63e4ba212d8f5adec05306fb2252c63a614c8a
