### ISSUE TITLE
Flow - axios is double encoding parts of webhook urls

### ISSUE THREAD

**Issue by shipsides-sparknel** [directus/directus#14971]
### Describe the Bug

At some point between 4:48pm AEST 03/08 and 7:30am 04/08 (was this when 9.15.0 went live?), my flows that send payloads via webhook to Power Automate stopped working. The flows continue to fire on events and send data to the webhook, but the webhook is rejecting the request. Prior to this, they were working fine and no other changes were made.

To test what may have been causing this, I have created a webhook that returns "Congratulations" on a GET request with no headers required:
https://prod-79.westeurope.logic.azure.com:443/workflows/ec0dded7191f4205ba5135af43875b5e/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=EMi5HhfcjUngo4WqkSPoBewGjzzOXuVbcnPkND56mJ0

I then create a flow with item.create and trigger a webhook to this URL. No content type is required working around https://github.com/directus/directus/issues/14547, and no body is required working around https://github.com/directus/directus/issues/14069.

The options section of the run shows:

> {
  "url": "https://prod-79.westeurope.logic.azure.com:443/workflows/ec0dded7191f4205ba5135af43875b5e/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=EMi5HhfcjUngo4WqkSPoBewGjzzOXuVbcnPkND56mJ0",
  "body": null,
  "headers": null
}

Note the %2F in the URL. This is correctly encoded and how PA gives you the webhook URL

The response shows:

> {
  "message": "Request failed with status code 401",
  "name": "AxiosError",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": {},
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "User-Agent": "axios/0.27.2"
    },
    "url": "https://prod-79.westeurope.logic.azure.com:443/workflows/ec0dded7191f4205ba5135af43875b5e/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%252Ftriggers%252Fmanual%252Frun&sv=1.0&sig=EMi5HhfcjUngo4WqkSPoBewGjzzOXuVbcnPkND56mJ0",
    "data": null,
    "method": "get"
  },
  "code": "ERR_BAD_REQUEST",
  "status": 401
}

Notice the %2F's are now %252F which is the literal of %2F. The webhook considers this incorrect as it's not / and refuses the request.

When I change the URL to be /triggers/manual/run, the response of Congratulations is received in the flow.

### To Reproduce

1. create a flow
2. webhook trigger
3. observe payload and failed response with a 401
4. manually decode to observe success

### Errors Shown

See above

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.16.0

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

cloud

**Comment by br41nslug** [comment]
Quite possibly caused by https://github.com/directus/directus/pull/14418

**Comment by shipsides-sparknel** [comment]
worth mentioning this **can't** be worked around for some URL's - eg:

https://api.powerbi.com/beta/redacted/datasets/redacted/rows?key=zx9L%2BUjM92RFtvWYeZvJjI94ANz8v2V907QdPIH93UOhqdEMIFGBj8KvF3fdhi3DyKIkxZHospsh9lAc%2B7BtXw%3D%3D

must be used instead of

https://api.powerbi.com/beta/redacted/datasets/redacted/rows?key=zx9L+UjM92RFtvWYeZvJjI94ANz8v2V907QdPIH93UOhqdEMIFGBj8KvF3fdhi3DyKIkxZHospsh9lAc+7BtXw==

so this is definitely a problem as opposed to something trivial

**Comment by emilyf** [comment]
Apologies if I'm commenting in the right place but my debugging has led me here at this point. Using Flows as described to run a POST call on external webhook I'm finding no matter how I clean the data I end up with this same axios error as reported above. In the screenshots below you can see my output is formatted cleanly all the way up until the final webhook payload when it starts escaping characters in the fields. I was searching around for this starting on https://github.com/directus/directus/issues/14265 and ended up here. Below are screenshots; I'm on enterprise cloud so I don't think I have ability to directly configure axios (assuming that's where my issue is). 

Note: I have triggered the same response body through postman with same headers, same auth, same json etc and it comes back successful.

My flow is triggered by another flow, here's the payload I have coming out of that which is looking how I want.

<img width="503" alt="trigger_payload" src="https://user-images.githubusercontent.com/1789807/196298717-6fa08973-6295-4e9f-aa1f-c00e1f0c2343.png">

From there i'm just triggering a webhook and my output here is still holding on....

<img width="625" alt="webhook request options" src="https://user-images.githubusercontent.com/1789807/196299089-a2d1c547-b3cd-4d12-8666-02fbf47dfa45.png">

Then it hits the payload for the webhook and I get the 400 Axios error. 

<img width="647" alt="payload_error" src="https://user-images.githubusercontent.com/1789807/196299211-0fbd080e-3553-4ec6-a6bb-634d1d0e4782.png">

**Comment by shipsides-sparknel** [comment]
@emilyf assuming the URL part that you have blocked out doesn't have any characters that needed escaping, it seems outside the scope of this issue because i specifically removed any body to bypass [#14069](https://github.com/directus/directus/issues/14069), which could be your issue
