### ISSUE TITLE
Translation missing : error You don't have permission to access this.

### ISSUE THREAD

**Issue by nervusdm** [directus/directus#14972]
### Describe the Bug

It's not a huge bug, but...

Update a field, in other language than english, without access.

There is a mix beetween "current language", and internal message error.

![Capture d’écran 2022-08-09 à 11 01 14](https://user-images.githubusercontent.com/4217180/183609263-c0cd27e2-ccf2-4c35-a1f2-ee9d4d180bb2.png)

### To Reproduce

Modify roles of someone.
(in relation files for example)

### Errors Shown

[FORBIDDEN] You don't have permission to access this.

### What version of Directus are you using?

9.5

### What version of Node.js are you using?

6

### What database are you using?

mysql

### What browser are you using?

edge

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
The part in red is the raw error returned from the API, so that won't be translated (on purpose). The description in the dialog should be translated though

**Comment by nervusdm** [comment]
The red error, not translated is not something any client wants. I know, I can easily quick & replace this. But It's not "on purpose".

**Comment by rijkvanzanten** [comment]
> The red error, not translated is not something any customer / user wants. I know, I can easily quick & replace this. But It's not "on purpose".

Agree to disagree. The raw error is critical for administrators to be able to help debug a user's problem. A generic translated "Oops sorry went wrong" makes figuring out the problem nearly impossible

**Comment by nervusdm** [comment]
I did not say "oopps sorry...". is a good thing?

But everything should / may be translated.

I mean, it not about a basic missing thing, the role permissions in a collection is commun, error will be too.

Btw, debug user  is not something acceptable in a production mode. If you disagree, why dont we give them read of sql password of example ?

**Comment by rijkvanzanten** [comment]
> Btw, debug user is not something acceptable in a production mode. If you disagree, why dont we give them read of sql password of example ?

We're not printing the full unauthorized stack trace of course, that'd be a huge security problem. I'm saying that—even in production—admins need to be able to help debug problems that the user might run into. This dialog is an "unexpected" exception, so any error codes and hints we can provide the user to pass on to their sysadmin helps resolve the issue quicker 👍🏻

**Comment by rijkvanzanten** [comment]
The API returns the error code, the app then uses that to render the title/description. We already have a most of the errors in place here: 

https://github.com/directus/directus/blob/de7ac8ff1444f48a030cdc52796fcc75f878b748/app/src/lang/translations/en-US.yaml#L582-L585
