### ISSUE TITLE
Unnecessary field permissions for uploading files

### ISSUE THREAD

**Issue by andy1li** [directus/directus#14982]
### Describe the Bug

Uploading files won't work (403) unless field permissions are granted for `storage`, `mime_type` and `filename_download`.

Even if I don't need (or want) to set them in API calls, it's still required to grant (unnecessary) permissions on those fields for file uploading to work .

<img width="584" alt="image" src="https://user-images.githubusercontent.com/1450947/183662425-f9003e58-4a8e-4539-a9ed-7a5c0f8efa74.png">

### To Reproduce

1. Not granting permission on any of `storage`, `mime_type` or `filename_download` for file creation.

2. Uploading files by calling `/files`.

3. Error 403.

### Errors Shown

```json
{
  "errors":[{
      "message": "You don't have permission to access this.",
      "extensions": {"code": "FORBIDDEN"}
  }]
}
```

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.16

### What database are you using?

mysql 8.0.28

### What browser are you using?

chrome

### How are you deploying Directus?

self-hosted

**Comment by azrikahar** [comment]
Granted I understand how they can be perceived as unnecessary, but I believe we can't exactly deem them as such without further research (maybe aside from Mime Type for certain use cases). 

Storage will likely play a big part in #14742 for example, and `filename_download` is used in download links as the [`download` attribute for `<a>` tags](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download) throughout the App. 

Let's continue this discussion in #14979 just so we can keep everything in one place.
