### ISSUE TITLE
Foreign key field does not autopopulate when creating a new related record

### ISSUE THREAD

**Issue by Thierry0** [directus/directus#14992]
### Describe the Bug

When creating a new child record from a parent record is supposed to fill the parent record's primary key in the foreign key of the child record. This is how it was working until today. I reached out through the chat functionality on the main website so you can refer there for videos of what is happening in my standard projects. Nevertheless, below you will find how to reproduce the error.

### To Reproduce

Create 2 tables, ex: students and grades tables. create a relationship where each student can have many grades and each grade belong to only one student (1:m). The grades table should have a foreign key field (call it studentId) which holds the Id of the student.

Next, Create a student record and from there create a grade for that student. The studentId foreign key field should automatically autopopulate with the student's Id (primary key in the student table)

### Errors Shown

"Foreign key cannot be empty"

### What version of Directus are you using?

Standard Cloud

### What version of Node.js are you using?

Standard Cloud

### What database are you using?

Standard Cloud

### What browser are you using?

Chrome

### How are you deploying Directus?

Standard Cloud

**Comment by joselcvarela** [comment]
This seems to be caused in https://github.com/directus/directus/pull/14834
Basically we were filtering validation to not include the `circularField`. But in that PR all fields are validated including the circular one. Since this field is not populated and is readonly, it's not possible to create the relationship.
I am already doing a fix

**Comment by mmmaxxxe** [comment]
same here on a standard cloud
