### ISSUE TITLE
Guide on how to add CORS headers to Directus API response  

### ISSUE THREAD

**Issue by jroxendal** [directus/directus#1501]
From what I can see the feature is there, but I can't find documentation on how to use it, any pointers?

**Comment by WellingGuzman** [comment]
Hey @jroxendal, you can read the configuration.php and see the options https://github.com/directus/directus/blob/master/api/configuration_sample.php#L45-L52

Change the `enabled` option to `true`.

We are going to improve the documentation after we release Directus 6.4
