### ISSUE TITLE
Unable to use toggle for conditional on input inside a details group

### ISSUE THREAD

**Issue by kallezz** [directus/directus#15021]
### Describe the Bug

Toggle field is not selectable as a condition in input field. When I try to set a condition to the input, the toggle field cannot be found in the add rule section. Both fields are contained in an details group.

Toggle field along with an input field:
![image](https://user-images.githubusercontent.com/32303354/184113345-8ea86b19-0725-492c-a5ea-eb8b819087f5.png)

Configuring the conditional for input field:
![image](https://user-images.githubusercontent.com/32303354/184113499-c783a6fe-112d-435e-a397-366d454b230f.png)

If I take the fields outside of the details group everything works as expected:
![image](https://user-images.githubusercontent.com/32303354/184113894-1f509d96-6a54-4bb2-bc53-96d00e081b1d.png)

### To Reproduce

Create a toggle and an input field inside a details group, try to assign toggle as the conditional for input field and it cannot be found.

### Errors Shown

None.

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.13.1

### What database are you using?

SQLite 3

### What browser are you using?

Chrome

### How are you deploying Directus?

local

**Comment by licitdev** [comment]
Relational fields were hidden from validation filters in #14818, however this change affected nested fields in groups.
