### ISSUE TITLE
New item with manually entered string primary key does not show "Field has to be unique" error message

### ISSUE THREAD

**Issue by koksikus** [directus/directus#15033]
### Describe the Bug

When I create a new collection with the primary key field and select "manually entered string", it does not show a duplication message when I enter the same number - it does not allow only to save. I can not select the uniqueness field because a database error pops up.

### To Reproduce

https://user-images.githubusercontent.com/90528895/184174320-b57d7e11-4eec-4201-ae64-a8cfdd257b43.mp4

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.14.1

### What database are you using?

MySQL

### What browser are you using?

Edge

### How are you deploying Directus?

locally

**Comment by licitdev** [comment]
This issue applies when a conflicting manual primary key is sent.

The `RecordNotUniqueException` for fields contain the `field` when the unique constraint is triggered.
 
![image](https://user-images.githubusercontent.com/26413686/184334911-4953ff2c-cc50-4741-a0a7-2ee4ce4b99b5.png)

However when it's for the primary key, the field is `null`.

![image](https://user-images.githubusercontent.com/26413686/184335480-9194500a-6b50-42f2-8bc6-23208ca870c0.png)

https://github.com/directus/directus/blob/55ec5f87d0fce5aef5dd4d2f534990cf6b79b4d9/api/src/exceptions/database/record-not-unique.ts#L11-L15

**Comment by rijkvanzanten** [comment]
Some database errors don't always return the field that was the one conflicting (very annoying). The app should show some sort of fallback warning for those (even though it's not as helpful).

**Comment by azrikahar** [comment]
Ref https://github.com/directus/directus/issues/15063#issuecomment-1214477142 for additional context on a similar situation but with composite unique constraint.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-211](https://linear.app/directus/issue/ENG-211/new-item-with-manually-entered-string-primary-key-does-not-show-field)
