### ISSUE TITLE
Chrome translates page when not needed

### ISSUE THREAD

**Issue by piotr-cz** [directus/directus#15035]
### Describe the Bug

When user has *Google Translate* enabled in her/ his browser, page is being translated even that Project Settings/ User Preferences are set to same language as browser's language.

This results in incorrect (or double) translations - particularly on Calendar Layout where days are in short format.

In my opinion the html lang attribute is [set](https://github.com/directus/directus/blob/v9.15.1/app/src/lang/set-language.ts#L43) too late in app lifecycle and Google Translate triggers before it is set.

One workaround could be to add [`translate="no"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/translate) to the html attribute but this disables translations altogether - even when content doesn't have translations.

### To Reproduce

1. Create collection *News* with Datetime field
1. Set Settings > Project Settings > Default Language: Polish
1. Set Chrome's language to Polish
1. Reload app
1. Go to collection *News*
1. See *wt.* (short label for Tuesday in Polish) translated to *Wtwt.*
1. Reload page
3. See *wt.* (short label for Tuesday in Polish) translated to *wag.*

### Errors Shown

No errors show

### What version of Directus are you using?

v9.15.1

### What version of Node.js are you using?

16.16.0

### What database are you using?

MySQL 5.7.32

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
I don't think there's much (if anything at all) we can do about that 🤔 We're setting the lang attribute the moment the language is known and set. If the translate widget doesn't register changes to lang after the fact, we end up with this problem. Happy to keep discussing potential improvements, but I can't really think of a way around this (that doesn't involve updating the translate widget itself)

**Comment by piotr-cz** [comment]
I understand.

I think Google Translate triggers before any scripts are parsed (or within very short time frame after that) and removing the `lang="en"` tag doesn't help here.

This leaves me with the `translate="no"` workaround which might not be optimal for every project out there.

**Comment by piotr-cz** [comment]
Just to document the behavior:

- User opens the page with Google Translate enabled
- The [index.html](https://github.com/directus/directus/blob/v9.15.1/app/index.html) is loaded with `lang="en"`
- Chrome evaluates that page content language is in english language
- Directus app starts, setting lang tag to default language code, page content loads in default language
- Chrome translates content from english to browser language which results in quirks
