### ISSUE TITLE
Schema apply attempts deleting relationship that doesn't exist

### ISSUE THREAD

**Issue by u12206050** [directus/directus#15038]
### Describe the Bug

After making several changes to via Directus and then trying to apply them to other environments we get an issue where the schema contains deleted fields.

### To Reproduce

In environment A create a relationship between two collections. Take a snapshot and apply to environment B. In env B remove the relationship, leaving the two collections as is. Take a snapshot of env B and apply it to env C

### Errors Shown

![Uploading Screenshot 2022-08-12 at 09.27.01.png…]()

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

chromium

### How are you deploying Directus?

Locally & GCP

**Comment by azrikahar** [comment]
This does seem odd. Can you share the schema snapshot? What was the relationship? How was it removed?

**Comment by u12206050** [comment]
I'll dm you the snapshot.

It was either removed manually by the developer before he applied the snapshot.

**Comment by azrikahar** [comment]
Thanks! Feel free to send it it to `azri@directus.io` 👍

**Comment by u12206050** [comment]
@rijkvanzanten Found the issue and fixed it here: https://github.com/knex/knex-schema-inspector/pull/123
