### ISSUE TITLE
Filter by folder doesn`t work on file and files interface

### ISSUE THREAD

**Issue by davydhyk** [directus/directus#15058]
### Describe the Bug

Just see the title.

### To Reproduce

1. Create input with file interface.
2. Set specific folder in the interface settings.
3. Then go to create an entity and try to choose the file, you will see entire library, but not one filtered folder.

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.16.0

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by licitdev** [comment]
The issue exists on `file` & `files` interfaces.
Folder option works in `image`, `wysiwyg` and `markdown` interfaces.
