### ISSUE TITLE
Optionally disable file listing to make Directus more secure

### ISSUE THREAD

**Issue by xamiam** [directus/directus#15057]
### Describe the Bug

Currently there is no differentiation between reading a single file (info, original file or transformed version) and showing the index of all files using the API.

In our case we really need to turn off the file listing for the API, but cannot do this without disabling read access to single files. 
We are using a special directus user with a token to access the files. The token is visible in the source code which makes listing ALL files a potential security risk. 

If there is a workaround, please let us know.

### To Reproduce

See directus doc:

https://docs.directus.io/reference/files/#list-files

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

16.16

### What database are you using?

MySQL

### What browser are you using?

Any Browser

### How are you deploying Directus?

heroku

**Comment by azrikahar** [comment]
Let's consolidate this in #11464 which delves into a potential list permission 👍
