### ISSUE TITLE
Clicking Settings>Group>Permissions>Status

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1506]
Settings>Group>Permissions>Status

@WellingGuzman – Clicking on Status cells (even for disabled rows) changes the status to "deleted". Clicking that should not do anything.

**Comment by benhaynes** [comment]
Clicking on status should NEVER do anything.

**Comment by WellingGuzman** [comment]
Closed by: https://github.com/directus/directus/commit/d85ff38ebbef00754e6a4e2c197c59c90a7b5d58

**Comment by benhaynes** [comment]
Done
