### ISSUE TITLE
Unable to fully delete manually typed O2M sort field

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#15061]
### Describe the Bug

When deleting the `sort` field on a relation via backspace one character after another the app correctly notices that the field does not exists and needs to be deleted. 

After deleting the last character the app still holds the last character and creates a column named by it.
When selecting the whole text and deleting it that, it won't happen.

_NOTE: It's not only a display error - the column get's created_

https://user-images.githubusercontent.com/46492597/184542785-75c825b3-6dbd-484b-885a-d746f982404b.mov

### To Reproduce

Create a many to one relation, select a sort field and start deleting the sort field value character by character.

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

N/A

### What database are you using?

N/A

### What browser are you using?

Chrome

### How are you deploying Directus?

N/A

**Comment by azrikahar** [comment]
> Create a many to one relation, select a sort field and start deleting the sort field value character by character.

Just to confirm, this is meant as One-To-Many right? as Many-To-One doesn't have a sort field (since we can't really sort 1 item)
