### ISSUE TITLE
File library images disappear on sorting

### ISSUE THREAD

**Issue by AVROTROS-developers** [directus/directus#15078]
### Describe the Bug

When you initially the File Library in Directus shows all our images from a Google Cloud bucket correctly. However, when you click the sort button the images randomly disappear. If you keep clicking for about 4-5 times suddenly everything is complete again.  

![image](https://user-images.githubusercontent.com/108686553/184689613-ba7a8ffb-e438-4b32-b806-dd2e5f1a985b.png)

I tested this with images in the local storage and that seemed to work fine, I didn't have any issues. I also tested it with Firefox, no issues there at all, both cloud based images and local images are working fine. So it seems to be mainly a Chrome issue. 
Rijk suggested it might be the intersection observer, so I checked what happened if you resize the screen so the images go out of view and back in and this also makes the images reappear. 

This issue is also present in the Users section, when sorting users the avatars disappear / reappear in the same way.

### To Reproduce

Upload 10 images in a GCS bucket
View them from Directus in the File Library
Press the sort button a couple of times

https://user-images.githubusercontent.com/108686553/184691536-4253e8c9-5eb7-4125-a354-387ea681b605.mp4

### Errors Shown

No errors in the console, the network inspector also shows all the images in the API calls. 

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.15

### What database are you using?

MySQL

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
@azrikahar I think it's because the `v-image` is loaded before (in view), then moved out of view with sort (so it unloads the image from the component), then when it's in view again, the `!loaded` prevents it from rendering again:

https://github.com/directus/directus/blob/14f0acbcc605cb403b7cd5aebd480953d68c5631/app/src/components/v-image.vue#L32
