### ISSUE TITLE
Nav Blacklist

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1509]
Should not be case-dependent: `Faq`, `FAQ`, `faq`... should all work

Should trim spaces from split values: `this, that, those` should work (right now only this work: `this,that,those`)

Settings interface should have this comment/note:
`A CSV of table names that should be hidden from the default navigation list`

---------

**OR, if this is cleaner:**
We already have `directus_privileges.nav_listed` under the group's table permissions but I don't know if we're using it. We *could* remove the `nav_blacklisted` interface and just add `nav_listed` checkboxes to the permissions interface.

**Comment by WellingGuzman** [comment]
> OR, if this is cleaner:
We already have `directus_privileges.nav_listed` under the group's table permissions but I don't know if we're using it. We could remove the `nav_blacklisted` interface and just add `nav_listed` checkboxes to the permissions interface.

This is a good solution, I will implement this in the second batch for the next minor version. what do you think @benhaynes ?

**Comment by benhaynes** [comment]
Perfect! We can update the ticket to reflect that

**Comment by benhaynes** [comment]
OK – @WellingGuzman and I decided to NOT remove the `nav_blacklist` because of a complexity in the upcoming "workflow permissions" and because we need to control more than just Tables (also: extensions, User Directory, File Library, Activity Dashboard, etc).

So we need to do make sure the current `nav_blacklist` can allow for toggling the following:

* Tables: eg `any_table_name` (*Working*)
* Extensions: eg `any_extension_id` (*Not Working*)
* User Directory: `directus_users` (*Not Working*)
* File Library: `directus_files` (*Not Working*)
* Messages: `directus_messages` (*Not Working*)

**Comment by WellingGuzman** [comment]
@benhaynes the new `nav_blacklist` was implement by https://github.com/directus/directus/commit/5423c8b8269a07eb9d32a0a8863d6627df834c10
