### ISSUE TITLE
Settings>Groups>Show Files

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1510]
Settings>Groups>Show Files is not working

If unchecked it should hide the "File Library" from the user navigation and not allow users to go to the "Files" page.

**Comment by WellingGuzman** [comment]
@benhaynes Would this reflect into permissions as well?

**Comment by benhaynes** [comment]
It's currently called `show files`, but it SHOULD be `allows_uploads`.
Since that's not controlled by permissions...
