### ISSUE TITLE
Reopening a `delete` Activity is buggy

### ISSUE THREAD

**Issue by erondpowell** [directus/directus#15127]
### Describe the Bug

Uploading Screen Recording 2022-08-17 at 1.27.41 PM.mov…

### To Reproduce

Try to open a deleted item in a collection within the activity log.

### What version of Directus are you using?

Cloud

### What version of Node.js are you using?

Cloud

### What database are you using?

Cloud

### What browser are you using?

.... Chrome

### How are you deploying Directus?

Cloud

**Comment by licitdev** [comment]
![image](https://user-images.githubusercontent.com/26413686/185223667-964ad032-d127-42d7-831a-dbc12f2b243a.png)

The open button shows up for `delete` activity item, which leads to the following page as the item no longer exists.

![image](https://user-images.githubusercontent.com/26413686/185224063-cc37cfd7-5943-4bbe-ba82-bb34d6fb6c7d.png)

@rijkvanzanten Should we hide the button or should we display the last values similar to the revisions drawer? The latter option will require the a `delete` entry in `directus_revisions`.

**Comment by erondpowell** [comment]
Oh dang! I didn't even realize the video never fully uploaded

**Comment by rijkvanzanten** [comment]
@licitdev lets just hide the open button for deletes 👍🏻
