### ISSUE TITLE
Settings>Groups>Allow Profile Editing

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1513]
Settings>Groups>Allow Profile Editing is not working.

This should disable the ability for these users to edit their user page. We can remove the save button from that user edit/detail page. Ideally all interfaces on their user detail page should be disabled too.

**Comment by benhaynes** [comment]
If "Allow Profile Editing" is off, does it still update the info at login? Eg: `last_access`, `last_page`, `last_page`, `ip`

**Comment by WellingGuzman** [comment]
it wasn't possible, but now it's bypassed. done here: https://github.com/directus/directus/commit/75771bde1e43956942f1502eef76b98f104547ef
