### ISSUE TITLE
aggregated function generate wrong Join sql

### ISSUE THREAD

**Issue by mojerro** [directus/directus#15136]
### Describe the Bug

I'm not sure if this is a bug or a new feature. I try to use the aggregated function with the groupBy filter in the join table, and I found that the groupBy filter doesn't support joined table fields like `join_table.field`.

### To Reproduce

Here is my graphql code.
```graphql
query MyQuery {
  consultations_aggregated(groupBy: "period_id.duration") {
    group
    count {
      id
    }
  }
  periods {
    id
    duration
  }
}
```
And below shows the generated SQL by directus which has wrong in `group by` statement.
```SQL
select "consultations"."period_id",
    count("consultations"."id") as "count->id"
from "consultations"
    left join "periods" as "periods1" on "consultations"."period_id" = "periods1"."id"
group by "consultations"."period_id"."duration"
order by "periods1"."duration" asc
limit $1 - missing
FROM - clause entry for table "period_id"
```

### Errors Shown

```
select "consultations"."period_id", count("consultations"."id") as "count->id" from "consultations" left join "periods" as "rcyhi" on "consultations"."period_id" = "rcyhi"."id" group by "consultations"."period_id"."duration" order by "rcyhi"."duration" asc limit $1 
- missing FROM-clause entry for table "period_id"
```

### What version of Directus are you using?

9.15.1 in docker

### What version of Node.js are you using?

--

### What database are you using?

postgres 10

### What browser are you using?

Chrome

### How are you deploying Directus?

docker

**Comment by rijkvanzanten** [comment]
Grouping doesn't support nested fields currently. Feel free to open a new feature request to get that discussion started 🙂
