### ISSUE TITLE
Cannot remove a `Name` from a Presets and Bookmarks item

### ISSUE THREAD

**Issue by erondpowell** [directus/directus#15135]
### Describe the Bug

Uploading Screen Recording 2022-08-17 at 10.48.37 PM.mov…

### To Reproduce

Create a bookmark, then try to remove the name, to make it into a default.

### What version of Directus are you using?

cloud

### What version of Node.js are you using?

cloud

### What database are you using?

cloud

### What browser are you using?

chrome

### How are you deploying Directus?

cloud

**Comment by azrikahar** [comment]
Linked a PR to resolve this, but wanted to note that it seems like the video wasn't uploaded successfully 😄 just for future reference 👍

**Comment by erondpowell** [comment]
> Linked a PR to resolve this, but wanted to note that it seems like the video wasn't uploaded successfully 😄 just for future reference 👍

Interesting.
This happened previously yesterday. I took special care to "view the preview vid" for this PR....
Seems that it loaded, then *unloaded*....
