### ISSUE TITLE
v-select search not working with custom item text and item value

### ISSUE THREAD

**Issue by u12206050** [directus/directus#15147]
### Describe the Bug

Using the v-select in custom extensions with a `item-text="name"` and `item-value="id"` doesn't work when searching a value.

### To Reproduce

Don't worry PR coming.

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

chrome

### How are you deploying Directus?

Locally & GCP

**Comment by br41nslug** [comment]
While it's very much appreciated to get a PR for it, we still need the reproduction steps to verify that it fixes this issue properly 😬

**Comment by u12206050** [comment]
No problem:

In either a new extension, or just any where you want :) Use the <v-select> similar to the following:

 ```
 <v-select
      :model-value="state.selectedOrg ? state.selectedOrg.id : null"
      :items="orgs"
      placeholder="Select a Org"
      item-text="name"
      item-value="id"
      @update:model-value="selectOrg($event)"
  />
  ```
  
  Here orgs looks like this:
`  [{ id: 1, name: "one" }, { id: 2, name: "two" }] ` etc.

Have enough items ( more than 20) and try to search.
