### ISSUE TITLE
Can't sort by single value (Array conversion)

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#15150]
### Describe the Bug

According to the [docs](https://docs.directus.io/reference/query.html#deep) we should be able to sort by a single value.
This fails with the error  `rootSort.map is not a function`. If we pass the filter-value as an array everything works as expected.

Note: tried it only inside the deep-parameter.

Is there an array parsing / type-check in the api missing or is it wrong in the docs?

### To Reproduce

Create a sort based on a single string: 
"_sort": "version",

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.5.1

### What database are you using?

N/A

### What browser are you using?

N/A

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
> Note: tried it only inside the deep-parameter.

Where are you trying it? Is this through the REST API?

**Comment by Dominic-Marcelino** [comment]
> Where are you trying it? Is this through the REST API?
Run into it in a custom endpoint (ItemsService)

**Comment by rijkvanzanten** [comment]
Ah that makes more sense then. The ItemsService requires the correct types to be used. The REST API / GraphQL APIs are a little more forgiving. When using the services directly, `sort` (and deep `_sort`) is required to be an array of strings 👍🏻

**Comment by Dominic-Marcelino** [comment]
You're absolutely right. Have been checking it though the API and everything works. Will close this issue.

Thanks ❤️
