### ISSUE TITLE
Blank page when creating new items

### ISSUE THREAD

**Issue by lluishi93** [directus/directus#15165]
### Describe the Bug

We get a blank page once we try to create new items.

### To Reproduce

1. Create collection A
2. Add some fields (simple string, translations, and maybe a m2m)
3. Go to collection A items and try to create a new item

### Errors Shown

Console error:
![image](https://user-images.githubusercontent.com/14786440/185613773-adacd1b4-019f-4eae-9b87-c876b1d5a1fe.png)

Blank page:
![image](https://user-images.githubusercontent.com/14786440/185613843-2750b286-076a-49c9-807c-aff492d80aef.png)

### What version of Directus are you using?

9.16.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
This should be the same as #15157 👍
