### ISSUE TITLE
Operation fields not shown when creating / editing flows

### ISSUE THREAD

**Issue by david-zacharias** [directus/directus#15168]
### Describe the Bug

When creating or editing flow operations no fields for configuring the selected operation are shown

<img width="855" alt="Bildschirmfoto 2022-08-19 um 14 39 30" src="https://user-images.githubusercontent.com/1903179/185621132-07a6f35f-b55f-4660-aca0-7f32dc9fc30a.png">

### To Reproduce

Create or edit an operation of a flow in Directus

### Errors Shown

Browser console shows `TypeError: e.fieldsMap[l] is undefined`

<img width="658" alt="Bildschirmfoto 2022-08-19 um 14 38 47" src="https://user-images.githubusercontent.com/1903179/185621175-7fb3ea12-83ff-48fc-8304-8d7353c759ff.png">

### What version of Directus are you using?

9.16.0

### What version of Node.js are you using?

16.15.0

### What database are you using?

PostgreSQL 13

### What browser are you using?

Chrome, Firefox

### How are you deploying Directus?

Docker (directus/directus:9 image)

**Comment by br41nslug** [comment]
This should be the same as https://github.com/directus/directus/issues/15157 👍
