### ISSUE TITLE
Consolidate environment variables for Redis use

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#15176]
In order to allow for horizontal scaling, Directus relies on a shared store for caches, rate limit, and cross-instance messaging. This is currently done through either Redis or memcached. 

If you rely on the same storage server for all three of these functionalities, you have to reconfigure the same config thrice. Similarly, if you don't realize that rate limit uses a different storage from the caches, you can easily end up in a confusing mess.

We should upgrade the environment variables to have a single "REDIS_*" configuration set, which can then automatically be reused for all Redis uses.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-208](https://linear.app/directus/issue/ENG-208/consolidate-environment-variables-for-redis-use)

**Comment by hillsporter** [comment]
Great job~~Thanks!!
