### ISSUE TITLE
Breaking Bug: 9.16 does not allow to add items for the add form does not show any field

### ISSUE THREAD

**Issue by Pachat** [directus/directus#15170]
### Describe the Bug

On a clean install of Directus 9.16, a new collection with one input field shows an empty add form 

### To Reproduce

1. New Directus install: create a collection with an input field
2. Click to add an item

### Errors Shown

No input field in the add form.

Same empty form if you try to add a user or a webhook.
Roles, Presets and Flows work though. 

### What version of Directus are you using?

9.16.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

PostgreSQL

### What browser are you using?

Firefox

### How are you deploying Directus?

locally

**Comment by br41nslug** [comment]
This should be the same as https://github.com/directus/directus/issues/15157 👍

**Comment by Pachat** [comment]
Downgrading the new 9.16.0 install to v9.15.1 and applying `npx directus database migrate:down`  made the forms working again.
I'll do an upgrade now and tell you.

**Comment by Pachat** [comment]
Same. Definitely v9.16.0 does not work.

**Comment by br41nslug** [comment]
A hotfix is on its way for this problem 😄
