### ISSUE TITLE
Item Revision History does not display

### ISSUE THREAD

**Issue by award96** [directus/directus#15173]
### Describe the Bug

In the main view of a record, I see that there were 12 fields updated by me at 9:58 am. When I click on "updated 12 fields" it takes me to the detailed view, but no changes are displayed. It should be displaying the 12 differences in the record. 

The same was true for a record with only 3 revisions, so it is not the number of revisions that is the issue.

In the "activity feed" view, the changes are correctly visible under the "Delta" column. So this error is only present in the

 "Editing Item in [collection]" view.

![revisions](https://user-images.githubusercontent.com/59756310/185680408-4b810b8e-7c27-4cda-a772-d7950bbc676a.jpg)
![broken_revision_history](https://user-images.githubusercontent.com/59756310/185680364-69288d2a-32e6-4384-aea3-e7f3b22800e0.jpg)

### To Reproduce

1. Make a change to a record.
2. View that record 
3. Click "revisions"
4. Click "updated [n] fields"

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.16.0

### What database are you using?

Postgres 14.2

### What browser are you using?

Chrome Version 104.0.5112.101

### How are you deploying Directus?

deploying the directus docker image to a kubernetes cluster

**Comment by azrikahar** [comment]
I can't seem to reproduce this on my end when running locally:

https://user-images.githubusercontent.com/42867097/185904859-429c5aea-2c9c-46bc-8f23-f4a398fbbe0f.mp4

Can you share what was fetched via the revisions API when loading said item? Example:

https://user-images.githubusercontent.com/42867097/185905381-b39a4d3b-caea-4785-a765-8719d7f456bb.mp4

How many instances of Directus are you running in the Kubernetes cluster? If you can also test this again with a fresh Directus instance locally, it would be very helpful.

**Comment by rijkvanzanten** [comment]
I haven't been able to reproduce this based on the given information, so I'll this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻
