### ISSUE TITLE
SSL routines:ssl3_get_record:wrong version number in mail feature

### ISSUE THREAD

**Issue by rhclayto** [directus/directus#15183]
### Describe the Bug

There are couple of closed issues on here with a similar symptom, but my scenario is a bit different. I cannot get e-mail notification/invitations to work on my server.

I have Postfix running locally, which also handles all my e-mail, from e-mail clients, webmail, & other apps which use it to send their e-mails (Nextcloud, Bookstack, etc.). These all work. Postfix is running locally on port 25, without any TLS/STARTTLS, just SMTP. I also have Postfix running on public port 465 (& 25 for server to server), which does use TLS (actually TLS termination on a HAProxy instance, which proxies connections to Postfix, so Postfix is configured without any encryption at all), but attempting to connect to the public port just times out. I can connect to port 25 locally with Telnet just fine, as well.

These are my settings, although I have tried every combination of settings:

```
### Email
EMAIL_VERIFY_SETUP=true # true, false, & commented out.
EMAIL_FROM="noreply@example.com" # Tried different values.
EMAIL_TRANSPORT="smtp"
EMAIL_SMTP_HOST="127.0.0.1" #also 'localhost'
EMAIL_SMTP_POOL=false # Also true.
EMAIL_SMTP_PORT=25
EMAIL_SMTP_SECURE=false # Also true.
EMAIL_SMTP_IGNORE_TLS=true # Also false.
EMAIL_SMTP_USER="x"
EMAIL_SMTP_PASSWORD="somethingsecret"
EMAIL_SMTP_TLS_CIPHERS="ALL" # Also other values, & commented out.
```

I have tried with all combinations of `EMAIL_SMTP_SECURE`, `EMAIL_SMTP_IGNORE_TLS`, `EMAIL_SMTP_TLS_CIPHERS` (including without this setting set, & with various values). 

I don't understand why Directus (Nodemailer) is trying to connect with encryption when I am not using encryption on my server (for local submission).

### To Reproduce

Hmm. I have described the configuration & server environment above, so I guess to reproduce, approximate that.

### Errors Shown

Aug 19 23:30:38 skeletor bauernhof[17413]: {"level":40,"time":1660951838399,"pid":17413,"hostname":"skeletor","library":"SSL routines","function":"ssl3_get_record","reason":"wrong version number","code":"ESOCKET","command":"CONN","stack":"Error: 140062517999552:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n","type":"Error","msg":"140062517999552:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n"}

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.17.0

### What database are you using?

PostgreSQL 12

### What browser are you using?

Firefox, Chrome

### How are you deploying Directus?

locally Ubuntu 20.04 server

**Comment by rhclayto** [comment]
I couldn't figure out how to solve the connection to localhost, but I did manage to get it to work with my SMTP server over it's public IP:port. The timeout issue was because I was applying some restrictions with systemd (which I use to launch Directus), restricting it to localhost only). Adding my public IP solved that. Still frustrating about the failure to work on localhost, though. (Even tried using the sendmail transport (Postfix provides a sendmail compatibility executable), & that gave EPIPE errors.)

**Comment by azrikahar** [comment]
Granted I'm not quite sure how does the implemented restrictions interfere with localhost connection as I'm not experienced with it, but maybe an alternative to potentially debug this (only if you have the time/interest of course) may be to setup a a simple Nodemailer script such as the one shown here: https://nodemailer.com/about/#example, but without the test account and replace it with your own.

This way it might be easier to find out what specific config worked for NodeMailer with localhost connection, then transfer/translate those configs into the environment variables that Directus accepts and passes to the internal Nodemailer.

**Comment by rhclayto** [comment]
Hi, thanks for the response. I was able to send a mail using the following script:

```js
"use strict";
const nodemailer = require("nodemailer");

// async..await is not allowed in global scope, must use a wrapper
async function main() {

  // create reusable transporter object using the default SMTP transport
  let transporter = nodemailer.createTransport({
    host: "localhost",
    port: 25,
    secure: false, // true for 465, false for other ports
    ignoreTLS: true,
    auth: {
      user: 'me',
      pass: 'crazy hard password',
    },
  });

  // send mail with defined transport object
  let info = await transporter.sendMail({
    from: '"Fred Foo 👻" <me@example.com>', // sender address
    to: "me@example.org", // list of receivers
    subject: "Hello ✔", // Subject line
    text: "Hello world?", // plain text body
    html: "<b>Hello world?</b>", // html body
  });

  console.log("Message sent: %s", info.messageId);
}

main().catch(console.error);
```

**Comment by rhclayto** [comment]
I'll reopen in case you want to investigate further.

**Comment by rijkvanzanten** [comment]
@rhclayto Your example configuration:

```js
  let transporter = nodemailer.createTransport({
    host: "localhost",
    port: 25,
    secure: false, // true for 465, false for other ports
    ignoreTLS: true,
    auth: {
      user: 'me',
      pass: 'crazy hard password',
    },
  });
```

should be the same as:

```
EMAIL_SMTP_HOST="localhost"
EMAIL_SMTP_PORT="25"
EMAIL_SMTP_SECURE="false"
EMAIL_SMTP_IGNORE_TLS="true"
EMAIL_SMTP_USER="me"
EMAIL_SMTP_PASSWORD="crazy hard password"
```

as it's constructed to the same transporter object config as far as I can tell:

https://github.com/directus/directus/blob/05d05f2cb83db24d2f21192b6e9bdb1b5664e2c0/api/src/mailer.ts#L30-L49

**Comment by rijkvanzanten** [comment]
I'll close this for now, as feels like more of a (server) configuration problem than a bug in Directus, but happy to keep discussing 🙂

**Comment by rhclayto** [comment]
I'm satisfied with my currently working configuration. It is odd, however, that the nodemailer script I used works, while the Directus configuration which should be equivalent (& indeed is the first config I tried), doesn't.  Cheers, thanks for the dialogue.

**Comment by rijkvanzanten** [comment]
Those exact env vars I shared above result in 

```
{
  pool: undefined,
  host: 'localhost',
  port: 25,
  secure: false,
  ignoreTLS: true,
  auth: { user: 'me', pass: 'crazy hard password' },
  tls: {}
}
```

for the configuration, which looks correct to me. Is that empty object under the `tls` config nodemailer to behave weirdly even with ignoreTLS set to true? Might trying adding that `tls: {}` in your example

**Comment by rhclayto** [comment]
Well holy mackerel. It works (`tls{}` or no `tls{}`). I am so sure I used that config, more than once. Well, many thanks, I am mystified but happy.

**Comment by mmospanenko** [comment]
having the same issue with Docker ARM64 using Gmail SMTP (relay, tls, 587)
