### ISSUE TITLE
Field Validation / Filtering by MIME Type doesn't work

### ISSUE THREAD

**Issue by lack-of-gravitas** [directus/directus#15184]
### Describe the Bug

Trying to figure out why filters don't work for me  -- I've got a collection ('seenOn') allowing users to ONLY pick in image/png files. I've placed this in as a validation rule against the 'images' field however it does not seem to work. What am I doing wrong??

What I expect - files to be pre-filtered by MIME type ('image/png') in this case.
What happens - all files are shown. I can pick in a JPG and collection is saved (no validation error / message). 

### To Reproduce

1 - Create a collection with a Files field.
2 - Add validation rule where _Directus File > MIME Type equals images/png_
3 - Create a new record in the collection
4 - Add existing item, file picker appears showing unfiltered view of all file types
5 - Select any invalid file type (e.g. JPG file) and save
6 - no validation message appears. record is created / saved.
![Screenshot_20220820_144045](https://user-images.githubusercontent.com/10094964/185729448-1597f295-1992-415d-b3e0-19b5bf860752.png)
![Screenshot_20220820_144059](https://user-images.githubusercontent.com/10094964/185729450-fb7cc0ef-1fdf-4c42-967f-17a56372381d.png)
![Screenshot_20220820_144114](https://user-images.githubusercontent.com/10094964/185729451-2882ded0-3f1c-44cf-a3cd-3fd5cd0e7039.png)
![Screenshot_20220820_144153](https://user-images.githubusercontent.com/10094964/185729454-343ce741-1eb8-4cfe-96e5-a434a9cf2d11.png)

### Errors Shown

No errors in console or on UI

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

Node LTS 16.15.0

### What database are you using?

PostgreSQL 14.1 on Supabase

### What browser are you using?

Firefox Developer Edition 102.0b3 (64-bit)

### How are you deploying Directus?

Docker on fly.io

**Comment by azrikahar** [comment]
> I've got a collection ('seenOn') allowing users to ONLY pick in image/png files. I've placed this in as a validation rule against the 'images' field however it does not seem to work. What am I doing wrong?

You're not doing anything wrong. 👍 This should be the same as #14655, where currently adding existing file will not get "expanded" and only contains the UUID, hence validation rules aren't able to perform the checks. Closing in favor of tracking it in #14414.

> What I expect - files to be pre-filtered by MIME type ('image/png') in this case.

This is interesting! I believe this is not possible (and may not be a part of #14414), but I can see how that can be another potential enhancement to validations, particularly when selecting existing items (not limited to files). DO feel free to add in a discussion for this.
