### ISSUE TITLE
Build API to ESM instead of CJS

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#15190]
The API is currently building to CJS, which has a couple of downsides:

1. More and more packages are becoming ESM only, which in turn means we either have to start replacing them with internal code (like https://github.com/directus/directus/pull/14840), or have to stick behind on a previous version that's CJS compatible (with all security implications that comes with that). 
2. The app (through vite) is already building to ESM, which means we're in a split-codebase (App in ESM, API in CJS), which in turn means that the tooling is also split (vitest app, jest api for example). This is starting to become more of a maintenance problem, as it also means we have to keep the CJS vs ESM discussion in mind in things like the shared libraries.

Before, we weren't able to move to ESM as TypeScript's support wasn't quite there yet. However, since TS 4.7, it _should_ now have decent support to transpile to ESM instead of CJS, which in theory should mean we should be able to flip the switch.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-204](https://linear.app/directus/issue/ENG-204/build-api-to-esm-instead-of-cjs)

**Comment by abdonrd** [comment]
@rijkvanzanten after this, there is an option to build the extensions as ESM instead of CJS?

**Comment by rijkvanzanten** [comment]
The API uses an `await import(x)` to pull in the extensions, so that should work yeah

**Comment by abdonrd** [comment]
But when you run `npm run build`, the output is CJS and not ESM.

i just saw this now:
https://github.com/directus/directus/blob/f850bcbacdb6597a6110f06816c15f2a25b0a0f8/packages/extensions-sdk/src/cli/commands/build.ts#L619

**Comment by rijkvanzanten** [comment]
@abdonrd Oh you're talking about the extensions-sdk build now specifically. CJS is still importable in an await import 👍🏻 I interpreted your question as "Do extensions bundled to ESM work"

**Comment by abdonrd** [comment]
Right! Excuse me if I didn't explain myself well!

I was expecting that now that the API is build as ESM, the extensions-sdk also build as ESM.

**Comment by rijkvanzanten** [comment]
> I was expecting that now that the API is built as ESM, the extensions-sdk also build as ESM. Or at least an option to allow build as ESM.

Fair! The plan right now was to prevent too many breaking changes by keeping that part as-is. If you bundle to ESM, you also have to make sure that the dependencies of your extensions are ESM compatible as well, so changing that default might cause more breaking changes. Now.. it's obvious that a lot of people having issues regardless (being due to cjs/esm, or importing from `directus` private internals that are now esm or unavailable, or whatever else), so I'm almost wondering if makes sense to just "rip the bandaid" and switch that over as well 😬

**Comment by abdonrd** [comment]
Fair point!

Rip it! 🩹😬

And you can always release a major version. The versions at the end are free numbers ...
