### ISSUE TITLE
Directus authentication create user with POST /users doesent return anything, when not read all

### ISSUE THREAD

**Issue by MrBond2104** [directus/directus#15196]
### Describe the Bug

POST returns 204 "No Content" if not all users are public.

### To Reproduce

I want to register users in Directus per POST. Therefore I have a "User" role and the "Public" role.

For the "Public" role, I just want to set "Directus Users" CREATE to true and limit this so that only users can be created with the ID of the "User" role. 

Then I sent a POST to /users with the following content:
```
{
    "email": "test@example.com",
    "password": "d!r3ctu5",
    "role": "9175cc78-b41f-4f6d-9c92-fb296af8b49d",
    "provider": "default"
}
```

Apparently the documentation isn't up to date here either, I have to specify a "provider" here... Even with Graphql I have to specify between last_access and provider as well as status? Not really according to the docs.

If the users are not all publicly accessible under GET /users, I will not receive a response here, i.e. "204 No Content".
When I set "Directus Users" to READ ALL it works. It can't be intentional that a list of users is publicly accessible?

I also tried to limit it so that only the CURRENT user can be queried. But that doesn't work because there is no current user. I just want to create the user.

Is there a special procedure here? It would be nice there is at least a response that the user was created successfully.
I think there was one in previous Directus versions: data: { create_users_item: true }

### Errors Shown

REST: 204 No Content

```
GRAPHQL: {
    "errors": [
        {
            "message": "GraphQL validation error.",
            "extensions": {
                "code": "GRAPHQL_VALIDATION_EXCEPTION",
                "graphqlErrors": [
                    {
                        "message": "Field \"create_users_item\" must not have a selection since type \"Boolean\" has no subfields.",
                        "locations": [
                            {
                                "line": 2,
                                "column": 143
                            }
                        ]
                    }
                ]
            }
        }
    ]
}
```

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

18.6.0

### What database are you using?

MariaDB 10.5.15

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
> Is there a special procedure here? It would be nice there is at least a response that the user was created successfully.


The 204 status _is_ the response that the user was created successfully 🙂 If the user wasn't created, that wouldn't be a 204. As for what's returned, it's based on the read access for the current user. If you're creating accounts from the public role, I'd recommend just looking for the 2xx status, as you're correct in saying that you'll probably don't want to list all your users publicly

**Comment by MrBond2104** [comment]
Ah okay, I didn't know that, thanks.
But I still ask myself the question, is it intentional that if you don't POST any body to /user, the account is still created but without any information. Email and password should be required according to the docs?

For the GraphQL API, however, the docs are really not up to date, are they? Since last_access is required? According to the docs only email and password.

**Comment by rijkvanzanten** [comment]
> But I still ask myself the question, is it intentional that if you don't POST any body to /user, the account is still created but without any information. Email and password should be required according to the docs?

Email and password is only required when using the `local` auth adapter. SSO based authentication strategies most likely don't have passwords, and may or may not have an associated email address. 

> Email and password should be required according to the docs?

That's wrong! Cc @erondpowell

> For the GraphQL API, however, the docs are really not up to date, are they? Since last_access is required? According to the docs only email and password.

The GQL required state is based on the nullification rule of the column. Sounds like it might wrongly ignore default / generated values? @licitdev mind taking a look to confirm that?

**Comment by licitdev** [comment]
I was unable to replicate the need for `last_access` to be required in GraphQL.

## Public Role Permission
https://user-images.githubusercontent.com/26413686/186584128-2b6c23d2-0f47-46eb-a688-fc05c791e8f4.mov

## Public Role Mutation
https://user-images.githubusercontent.com/26413686/186584151-c66680ee-291b-40b0-a056-5a00dbd9a17d.mov

## Required Fields
Upon testing, only `status` and `provider` are required fields, if all fields are allowed for the `Create`. The user is created with default values of `active` and `default` respectively.

### Allow All Fields
![image](https://user-images.githubusercontent.com/26413686/186585058-437b38cc-632f-4d48-9bbc-51b4ba9bd461.png)

### Only Allow `email` & `password` Fields
![image](https://user-images.githubusercontent.com/26413686/186585522-08ab44ef-89cf-482b-807c-e8646f0c44b3.png)

**Comment by erondpowell** [comment]
> Email and password should be required according to the docs?

@MrBond2104  Can you send a link to where you found this in the docs?

**Comment by MrBond2104** [comment]
@erondpowell In fact, it is probably correctly documented... Because it says in the docs that only the default provider requires a password and mail (https://docs.directus.io/reference/system/users.html#create-a-user).

So it's correct so far. The Docs are probably just a bit vague in my opinion, because if I don't give anything, the provider is not automatically set to "default".

**Comment by erondpowell** [comment]
@MrBond2104 Okay sounds good. We'll be completely redoing the API docs fairly soon, so we can take a look at this too!
