### ISSUE TITLE
Can't see relations inside item form

### ISSUE THREAD

**Issue by lluishi93** [directus/directus#15208]
### Describe the Bug

Since 9.16.0 (also 9.16.1) we're unable to see relations inside item side details form (in the screenshot, inside the "Edit hero slider" form the "Slides" field should be displaying some rows, but it is empty)

![image](https://user-images.githubusercontent.com/14786440/185947696-b977196d-5c40-4e93-b46f-84afc478183f.png)

### To Reproduce

1. Create collection A
2. Create collection B with a "name" field
3. Create collection C with a "name" field
4. Add a m2m field inside collection A pointing to collection B and make the display template show both ID and NAME
5. Add a m2m field inside collection B pointing to collection C and make the display template show both ID and NAME
6. Create some items for collection C
7. Create some items for collection B and add the previously created C items to the m2m relationship
8. Create an item for collection A and add the previously created B items to the m2m relationship
9. Save all
10. Go to item A and click one of the B items linked to it
11. Check that inside the B item detail form you can't see the C items related to it

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

16.14.0

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by Nitwel** [comment]
![grafik](https://user-images.githubusercontent.com/22577866/186153266-66eb8ed4-2262-451d-9b78-f04db1f01306.png)

There we have our culprate, seem that changing something from `junctionField` to `junctionPkField` does cause some problems down the road. 😄 Ref: #12820
