### ISSUE TITLE
ServiceUnavailableException title translation missing

### ISSUE THREAD

**Issue by alexleboucher** [directus/directus#15207]
### Describe the Bug

When we throw a ServiceUnavailableException like this : `throw new ServiceUnavailableException('I love Directus')`, the title of the modal is `errors.SERVICE_UNAVAILABLE`.

<img width="544" alt="Capture d’écran 2022-08-22 à 16 04 55" src="https://user-images.githubusercontent.com/91946849/185940931-6d2d670b-320e-475e-9f48-060b32748b5d.png">

### To Reproduce

In a filter hook, throw a  `ServiceUnavailableException`

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

16.12

### What database are you using?

Postgres 11

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
Has to be added in here:

https://github.com/directus/directus/blob/add851ac16ac0e24363a2f4041b4eb08584b59d5/app/src/lang/translations/en-US.yaml#L585-L609

@alexleboucher Wanna open a PR? 🙂
