### ISSUE TITLE
GraphQL query fails when using query parameters on a singleton data model

### ISSUE THREAD

**Issue by madc** [directus/directus#15212]
### Describe the Bug

It is currently not possible to use data from a singleton data model as source for an insights dashboard (tested with the metric type).

![image](https://user-images.githubusercontent.com/343392/186002624-dd0a079b-b59b-474c-9013-9ce22916f223.png)

### To Reproduce

- Create a new data model and mark it as singleton
- Create a new dashboard and use any value from this data model

### Errors Shown

```
{"errors":[{"message":"GraphQL validation error.","extensions":{"code":"GRAPHQL_VALIDATION_EXCEPTION","graphqlErrors":[{"message":"Unknown argument \"limit\" on field \"Query.build_status\".","locations":[{"line":1,"column":39}],"path":["query_6df036f1"]}]}}]}
```

Additionally, if a sort-column is set, it will complain about that as well.

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

16

### What database are you using?

MySQL

### What browser are you using?

Firefox

### How are you deploying Directus?

Docker

**Comment by freekrai** [comment]
So it's not just insights this happens with FYI, if you do a GraphQL query on any singleton with limit, filter or sort it will error out since by default singletons don't have or need any arguments. I'm testing a fix I'll push shortly in a PR.
