### ISSUE TITLE
Column titles behave differently when you setting them.

### ISSUE THREAD

**Issue by koksikus** [directus/directus#15230]
### Describe the Bug

By setting the width of the columns, their titles behave differently when setting them, i.e. the whole word disappears immediately, but the text with dots should appear, and sometimes there is more space behind the sort indicator, this makes the column not necessarily that wide (this is manifested by the word hiding too quickly and creating a space between the column line and sort indicator) . I can see longer words get reduced to 3 letters and dots which is a good solution, but not always the case. It would be good to be able, for example, to reduce the font because as you can see in the status by the title, the column is wider than it would have to be ... And what if the text could be rotated by 90 degrees.

In addition, a very good solution is to leave the title tag always visible, because when you go down the collection and move to the next columns, you simply do not know what this data is about (unless you know the arrangement of the columns by heart)

### To Reproduce

You can see it in the video:

https://user-images.githubusercontent.com/90528895/186244287-b017d168-18d1-4cc3-80bd-5dcff035e85d.mp4

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

16.15

### What database are you using?

Sql server 2017

### What browser are you using?

Edge

### How are you deploying Directus?

locally

**Comment by Nitwel** [comment]
The hiding of a table name seems to be intentional. I would love to hear you opinion @rijkvanzanten if this should be changed or if it is fine as is.

**Comment by rijkvanzanten** [comment]
This is currently working as intended / expected. Once the name gets too small to be reasonable legible, we hide it completely in favor of relying on the tooltip to show the full name. 

It's to allow for setups where you have tiny columns with single char sized previews, like a status color dot:

<img width="616" alt="CleanShot 2022-08-24 at 16 45 10@2x" src="https://user-images.githubusercontent.com/9141017/186520008-9dbf014b-9a50-4837-8096-d48811443f72.png">

**Comment by koksikus** [comment]
I would like to return to the discussion in this regard. I have the latest version of Directus 9.18.0 and it still has an error. Look at how much space is behind a 3 letter word and how much space is left for a long word. Again at the end of the video, I managed to trigger an error. Just move the column to decrease and increase for a while.

https://user-images.githubusercontent.com/90528895/191999113-fad81065-2844-43bc-94f8-ce5f0126cf9f.mp4
