### ISSUE TITLE
SEARCH method does not work on singletons via REST API

### ISSUE THREAD

**Issue by StephenGunn** [directus/directus#15244]
### Describe the Bug

I use the SEARCH method for almost all of my queries and found that singleton collections don't respond to the body object. They do respond to the classic GET method with the fields specified as query params. 

The result is that you cannot retrieve relational data via the SEARCH method. It will retrieve the foreign keys, so only the first-level data.

### To Reproduce

- Create a singleton with a O2M relationship.
- Add items to that relationship.

Query the singleton collection with a GET request:
`[GET] /items/:collection?fields=*.*`

Query the singleton collection with a SEARCH request:
```
[SEARCH] /items/:collection
body: {
	"query": {
		"fields": [
			"*.*"
		]
	}
}
```

This will give you two different results. 

I do not know if this is a "bug" or not, but I couldn't find anything in the docs that described this behavior. 

### Errors Shown

No errors on either end. 

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

16.17.0

### What database are you using?

Postgres 12

### What browser are you using?

no browser, Insomnia and straight from node

### How are you deploying Directus?

Self install on Digital Ocean droplet with a managed DB instance. Ubuntu server on the droplet.

**Comment by rijkvanzanten** [comment]
Singletons are short-circuited here:

https://github.com/directus/directus/blob/d7b8ef297e1389d648cd7b7ed7d9db3b8eca57b0/api/src/middleware/validate-batch.ts#L17
