### ISSUE TITLE
m2a crashing tabular layout in header

### ISSUE THREAD

**Issue by Nitwel** [directus/directus#15263]
### Describe the Bug

When selecting a m2a field as a new column in the table layout, the whole app crashes.

### To Reproduce

See bug description...

### Errors Shown

App crashes

### What version of Directus are you using?

latest

### What version of Node.js are you using?

latest

### What database are you using?

mariadb

### What browser are you using?

firefox

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
Linear: [ENG-202](https://linear.app/directus/issue/ENG-202/m2a-crashing-tabular-layout-in-header)
