### ISSUE TITLE
Insights - Global variable input disabled since 9.16.0

### ISSUE THREAD

**Issue by dewita97** [directus/directus#15270]
### Describe the Bug

On the insights, after upgrading to Directus 9.16.0 (also tested for 9.16.1), global variable inputs are disabled by default.

I need to inspect the element in order to remove the "disabled" attribute on the input tag. It's the only way to make it work again. When I revert to a previous version than 9.16.0, everything works as expected. 

### To Reproduce

1. Go to the insights panel
2. Create an insight 
3. Create a global variable with an input (string)
4. Save
5. The input is disabled

NB: I've experienced this issue as an administrator

### Errors Shown

None

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

v14.15.1

### What database are you using?

MySQL 8

### What browser are you using?

Chrome, Safari

### How are you deploying Directus?

Locally and AWS ec2

**Comment by joselcvarela** [comment]
Already fixed on https://github.com/directus/directus/pull/15211
Should be available on next release.
