### ISSUE TITLE
Disabling o2m field using the table interface turns off pagination

### ISSUE THREAD

**Issue by colemahatmccreary** [directus/directus#15287]
### Describe the Bug

Adding the disabled flag to a o2m field/relationship (via condition or field config) removes the page buttons so only the first N are visible (15 by default).

### To Reproduce

Create o2m relationship between two tables with multiple entries. Set the o2m table interface page length to 1. Only the first in the related list will be visible, with no option to continue to the next page

### What version of Directus are you using?

9.16.1 (Standard Cloud)

### What version of Node.js are you using?

Standard Cloud

### What database are you using?

Standard Cloud

### What browser are you using?

Chrome

### How are you deploying Directus?

Standard Cloud

**Comment by leosin** [comment]
![image](https://user-images.githubusercontent.com/3676670/187090048-258d6702-cec3-4df6-8c9a-af4e39cbf018.png)

Maybe I have the same problem，how to display pagination?
