### ISSUE TITLE
Add file-too-large-to-upload error message

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1528]
## Version info
  - Directus version and branch: BETA 6.4-rc https://github.com/directus/directus/commit/5558cd2ab3acf14abe0ab2f0420a97353bde0b12

## Expected Behavior
Saving item with semi-large (5+ MB) image throws "image too big" error.

## Actual Behavior
Admin throws Error `Unexpected token < in JSON` error

## Steps to Reproduce
 1. Create an item with a single-file interface
 2. Select a large image (5+ MB)
 3. Hit save

## Logs or Screenshots
Current error:
```
Error
Error: Uncaught SyntaxError: Unexpected token < in JSON at position 0
File: http://www.kunstenkindkampen.nl/admin/tables/aanbod/new
Line:1
```

The ajax request returns:
```
<br />
<b>Fatal error</b>:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 14592 bytes) in <b>/home/kunstenkindkampen.nl/public_html/admin/api/core/Directus/Filesystem/Thumbnail.php</b> on line <b>49</b><br />
```

**Comment by WellingGuzman** [comment]
After trying different things, it seems be difficult to add a proper message when the error is about memory limit exhausted, which means you almost can't use any more memory to change the message, or are not able to strictly remove memory to use in other way.

**Comment by benhaynes** [comment]
@WellingGuzman – Can't we compare the server max upload size with the upload size for the current file? Then we could check if a file is too big BEFORE uploading and still have memory to show a proper error notification.

@rijkvanzanten – any other ideas?

**Comment by WellingGuzman** [comment]
We do compare it, but the end result can becomes "too big" and hit memory limit.

I can look for an alternative solution though.

**Comment by rijkvanzanten** [comment]
Maybe we could look for alternative solutions to uploading files altogether? I've uploaded way larger images and files on this exact server using two other CMSs in the past.

**Comment by WellingGuzman** [comment]
This information could help, let's talk over slack. Last night I did some test and manage to saved 60mb of memory, while uploading a 23mb image that was giving me the memory exhausted error.

**Comment by benhaynes** [comment]
This is done except for the friendly error, so we're closing this ticket – follow up can be tracked here: https://github.com/directus/directus/issues/1237

**Comment by WellingGuzman** [comment]
We now return a more proper way, it's a technical error, but at least it's error that will give an idea what's going on.

We have another ticket dedicated to work on more friendly errors messages here #1237

**Comment by WellingGuzman** [comment]
It seems @benhaynes closed at the same time I was trying to :)
