### ISSUE TITLE
Selected option is not automatically cleared when the meeting condition is changed

### ISSUE THREAD

**Issue by apsonandtesla** [directus/directus#15281]
### Describe the Bug

If you create 2 dropdown fields (_category_1_ and _category_2_) in a data collection, and write conditions for _category_2_ based on _category_1_, for example, 

* if _category_1_ equals to "A", then the options for _category_2_ would be "1", "2", and "3";
* if _category_1_ equals to "B", then the options for _category_2_ would be "4" and "5".

Now let's select "A" for _category_1_, and then select "2" for _category_2_. We then select "B" for _category_1_, you can see that the chosen value for _category_2_ is still "2", which would not match the rules we set above.

I have tried to add validations in the _category_2_ and while it worked for the first time you create a record, it would appears that as long as you don't change the value for _category_2_, the validation will not work even if you change the value for _category_1_, and you may have a "wrong" record for your data collection.

### To Reproduce

1. Create 2 dropdown fields (_category_1_ and _category_2_) in a data collection, and write conditions for _category_2_ based on _category_1_, and set the conditions on _category_2_ as: 
* if _category_1_ equals to "A", then the options for _category_2_ would be "1", "2", and "3";
* if _category_2_ equals to "B", then the options for _category_2_ would be "4" and "5".

Now let's select "A" for _category_1_, and then select "2" for _category_2_. We then select "B" for _category_1_, you can see that the chosen value for _category_2_ is still "2" (which I think should be reset to null), which would not match the rules we set above.

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

not sure

### What database are you using?

Postgres

### What browser are you using?

Firefox

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
> if category_2 equals to "B", then the options for category_2 would be "4" and "5".

Just to be sure, It should be `if category_1 equals to "B"` right? 😄

That said, I believe this should be the same as #10199. Keeping this up for now as there wasn't a PR made for #10199 yet.

**Comment by apsonandtesla** [comment]
> Just to be sure, It should be `if category_1 equals to "B"` right? 😄
Yep you are right.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-201](https://linear.app/directus/issue/ENG-201/selected-option-is-not-automatically-cleared-when-the-meeting)

**Comment by drupalshift** [comment]
@rijkvanzanten I know this is a low priority in the backlog, but is there any way this could get attention
Or give me some hint as to where should I look to patch things up 
This is a serious problem In conditional selects since it can save incorrect inputs
