### ISSUE TITLE
Allow setting `name` in mail configuration 

### ISSUE THREAD

**Issue by onurbamaro** [directus/directus#15294]
### Describe the Bug

Emails like invite user or reset password are not getting over to gmail/microsoft(outlook, live) inboxes using SMTP. The email gets delivered correctly to some personal e-mails I have on hostgator, but never gmail/microsoft. 

After a little research I was able to found an issue reported on nodemailer's github. After testing what was suggested by some users it worked and e-mails were successfully delivered. 

Nodemailer's issue: https://github.com/nodemailer/nodemailer/issues/677#issuecomment-283037667

I've added 'name:  env_1.default.EMAIL_SMTP_HOST' on createTransport as some users reported that it worked that way. After that emails got to the inbox. 

```js
    else if (transportName === 'smtp') {
        let auth = false;
        if (env_1.default.EMAIL_SMTP_USER || env_1.default.EMAIL_SMTP_PASSWORD) {
            auth = {
                user: env_1.default.EMAIL_SMTP_USER,
                pass: env_1.default.EMAIL_SMTP_PASSWORD,
            };
        }

        const tls = (0, get_config_from_env_1.getConfigFromEnv)('EMAIL_SMTP_TLS_');
        transporter = nodemailer_1.default.createTransport({
            name: env_1.default.EMAIL_SMTP_HOST,
            host: env_1.default.EMAIL_SMTP_HOST,
            port: env_1.default.EMAIL_SMTP_PORT,
            secure: env_1.default.EMAIL_SMTP_SECURE,
            ignoreTLS: env_1.default.EMAIL_SMTP_IGNORE_TLS,
            auth,
            tls,
        });

    }
```

### To Reproduce

Spin up a project with the following env variables: 

In my case I am using smtp over hostgator. 

```
EMAIL_FROM="email@yourdomain.com.br"
EMAIL_TRANSPORT="smtp"
EMAIL_SMTP_HOST="mail.yourdomain.com.br"
EMAIL_SMTP_POOL=true
EMAIL_SMTP_PORT=465
EMAIL_SMTP_SECURE=true  # Use TLS
EMAIL_SMTP_IGNORE_TLS=false
EMAIL_SMTP_USER="email@yourdomain.com.br"
EMAIL_SMTP_PASSWORD="yourpassword"
```

Invite some users with @gmail.com/@outlook.com/@live.com emails and other domains too. 

See that the e-mail gets to the inbox when its not one of those three (that I tested). 

After add 'name' in the createTransport and  send those invitations over again and see that the e-mails will get there. 

### Errors Shown

There is no error shown. 

Nodemailer doesn't not return any errors and that the weird part of it. Apparently it sends the e-mail, but those email providers doesn't get them because the lack of the 'name' property. 

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

16.17.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally with supabase and over a VPS with docker

**Comment by rijkvanzanten** [comment]
Considering this more of an improvement rather than a bug, as that seems to be vendor specific (f.e. AWS SES nor Sendgrid seem to have the same requirements on the `name` field being said)
