### ISSUE TITLE
Run Script return value with circular reference throws error

### ISSUE THREAD

**Issue by licitdev** [directus/directus#15291]
### Describe the Bug

Error is thrown while saving revision if Run Script returns value with circular reference.

https://github.com/directus/directus/blob/a98a83b5da0677c45cce0e9dc23204438ee32cc8/api/src/flows.ts#L343-L351

Leading to an error being thrown in the payload service.

https://github.com/directus/directus/blob/a98a83b5da0677c45cce0e9dc23204438ee32cc8/api/src/services/payload.ts#L179-L180

### To Reproduce

Create a new flow with `Activity & Logs Tracking` set as `Track Activity & Logs`.
Create a Run Script operation in Flows with the following example.

```js
module.exports = async function(data) {
	const obj = {a: 1};
	obj.b = obj;
	return obj;
}
```

### Errors Shown

```
00:28:25 🚨 Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'b' closes the circle
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'b' closes the circle
    at JSON.stringify (<anonymous>)
    at /Users/ian/Projects/directus/api/src/services/payload.ts:179:27
    at Array.forEach (<anonymous>)
    at PayloadService.processValues (/Users/ian/Projects/directus/api/src/services/payload.ts:175:21)
    at /Users/ian/Projects/directus/api/src/services/items.ts:135:35
```

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

v16

### What database are you using?

SQLite

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
Linear: [ENG-200](https://linear.app/directus/issue/ENG-200/run-script-return-value-with-circular-reference-throws-error)
