### ISSUE TITLE
The width of the video file preview is not the full width and the video background color is adjusted

### ISSUE THREAD

**Issue by MunMunMiao** [directus/directus#15296]
### Describe the Bug

When the video width is less than the container width, the surrounding will be left blank. For the video, the style is not beautiful.

It should be like this:
![WX20220828-145420@2x](https://user-images.githubusercontent.com/18216142/187061808-b900b431-9a42-4c6d-8590-7240787d8e34.png)

not like this:

![WX20220828-145344@2x](https://user-images.githubusercontent.com/18216142/187061744-434cf961-4525-4bdd-8266-2eafc6ffc71b.png)

### To Reproduce

open video file preview

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

18.7.0

### What database are you using?

mysql8.0

### What browser are you using?

Chrome

### How are you deploying Directus?

docker

**Comment by rijkvanzanten** [comment]
This is currently working as intended / expected. The media source file is rendered at its original aspect ratio, with the letterboxing provided by the app. Down to discuss improvements in a new discussion, but as it stands, this is not a bug to resolve 🤔
