### ISSUE TITLE
Swiftmailer validation refuses RFC 2822 compliant e-mails

### ISSUE THREAD

**Issue by GeeWizWow** [directus/directus#1530]
## Version Info
  - Directus docker 6.3
  - PHP version: 7.1.2

## Steps to Reproduce
 1.  Run a directus docker instance
 2.  (Optional: Create a new user)
 3.  Log out
 4. Press the reset password button
 5. Observe the network call to /forgot-password fail with an error 500 

## Logs or Screenshots

`{
  "code": 0,
  "class": "Swift_RfcComplianceException",
  "message": "Address in mailbox given [{{directus_email}}] does not comply with RFC 2822, 3.6.2.",
  "file": "/var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php",
  "line": 345, [...]`

E-mail was checked and was rfc 2822 compliant. It raises another issue, if swiftmailer is going to reject non rfc compliant e-mails they should prob not be allowed at signup

**Comment by WellingGuzman** [comment]
Hey @GeeWizWow, apparently there's an issue with the docker image no providing a default email on installation. note the `{{directus_email}}` that's a placeholder that needs to be replaced.

**Comment by WellingGuzman** [comment]
This is indeed a directus docker image issue rather than a directus issue.

**Comment by WellingGuzman** [comment]
Moved to docker repository https://github.com/directus/directus-docker/issues/15
