### ISSUE TITLE
`*_REDIS_PASSWORD` Fields Become an Array

### ISSUE THREAD

**Issue by wrynegade** [directus/directus#15311]
### Describe the Bug

If a `*_REDIS_PASSWORD` environment variable contains a `,`, the environment variable parser will convert the value to an array.

### To Reproduce

Set `CACHE_REDIS_PASSWORD` to anything containing a `,` (e.g. `abc,def`)

### Errors Shown

```console
[ioredis] Unhandled error event: ReplyError: ERR syntax error
    at parseError (/directus/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/directus/node_modules/redis-parser/lib/parser.js:302:14)
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

ReplyError: ERR syntax error
    at parseError (/directus/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/directus/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'auth',
    args: [
      'abc',
      'def'
    ]
  }
}
```

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

16.16.0

### What database are you using?

pg13

### What browser are you using?

chrome

### How are you deploying Directus?

docker

**Comment by rijkvanzanten** [comment]
This is technically by design. We're gonna stop doing this magic parsing per v10 in https://github.com/directus/directus/issues/9521 👍🏻

**Comment by rijkvanzanten** [comment]
You can prevent this currently by prefixing the env var with `string:`

**Comment by wrynegade** [comment]
Interesting! I'll see if I can work around this for now then.
