### ISSUE TITLE
M2M field: items disappear when Add Existing item

### ISSUE THREAD

**Issue by meerzulee** [directus/directus#15324]
### Describe the Bug

 I added all items from the existing table. When I click add existing item wherein the table of existing items, the table of added items disappears. 
Here's video https://www.dropbox.com/s/qnastcbcixvjgm4/2022-08-30%2021-16-33.mkv?dl=0the 

### To Reproduce

It shouldn't change added items

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

16.16.0

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by br41nslug** [comment]
For future reference this is not enough information for reproduction @meerzulee 
> To Reproduce
> - It shouldn't change added items

The video is a nice addition but should not replace the description here. These steps should contain everything to re-create the data-model and all of the actions needed to get to the error state.
