### ISSUE TITLE
Time series panel error when it is linked to a collection that not longer exists

### ISSUE THREAD

**Issue by azrikahar** [directus/directus#15334]
### Describe the Bug

When viewing a time series panel that is getting data from a collection, and we intentionally delete said collection, the panel will show the spinner indefinitely since there's an error.

https://user-images.githubusercontent.com/42867097/187624993-880f32f3-7641-4722-bc8c-da2a393b151c.mp4

The error seems to stem from here:

https://github.com/directus/directus/blob/d7b8ef297e1389d648cd7b7ed7d9db3b8eca57b0/app/src/utils/query-to-gql-string.ts#L33

Where the non-null assertion causes the accessing of `.field` to error out.

Perhaps the fix would be to prevent fetching of data when the panel is relying on a collection/field  that does not exist anymore.

### To Reproduce

1. Create a new collection for time series panel later on
   - ensure to create a numeric field as the time series value
   - ensure to create a datetime/timestamp field as the time series date
2. Create dashboard, then create a time series panel with above collection
3. View the panel, everything should work fine
4. Go to data model and delete the new collection
5. Go back to view the panel, it will throw gql validation error (because the API side couldn't find the collection and field anymore)
6. Refresh browser so that the collections and fields store can rehydrate
7. Notice that the panel is infinitely spinning, and refer to "Errors Shown" section below for the error appeared in browser console

### Errors Shown

Browser console error:

```
query-to-gql-string.ts:33 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'field')
    at formatQuery (query-to-gql-string.ts:33:93)
    at queryToGqlString (query-to-gql-string.ts:17:32)
    at loadPanelData (insights.ts:205:21)
    at Proxy.refresh (insights.ts:170:9)
    at Proxy.<anonymous> (pinia.esm-browser.js:1305:30)
    at beforeEnter (index.ts:25:11)
    at vue-router.esm-bundler.js:1934:35
    at new Promise (<anonymous>)
    at vue-router.esm-bundler.js:1908:18
    at vue-router.esm-bundler.js:3423:65
```

### What version of Directus are you using?

latest main branch

### What version of Node.js are you using?

16.16.0

### What database are you using?

PostgreSQL 13.5

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally in dev build

**Comment by freekrai** [comment]
Would this return null or an error? Technically it _could_ / _should_ be a validation rule in GraphQL to check for non-existent collections same as it checks for non-existent arguments.

**Comment by rijkvanzanten** [comment]
@freekrai I think this is a very similar situation as https://github.com/directus/directus/pull/15326 where the response from GraphQL is technically correct. GraphQL correctly throws the validation error when a wrong query is made. The solution here is to prevent the app from making the invalid request in the first place. I think we can handle this on the dashboard level during the graphql query creation. Whenever it runs into a collection that no longer exists, it should skip it in the graphql request, and instead put an (app-generated) Error object in the panels data, so the panel can render the error individually (while the rest of the dashboard remains in operation)

**Comment by freekrai** [comment]
yeah, that makes sense.
