### ISSUE TITLE
Flow Operation disappears after select it

### ISSUE THREAD

**Issue by amo42** [directus/directus#15341]
### Describe the Bug

Once any Flow is opened, and an Operation is selected by a single click, the Operation and/or other elements vanished. Refreshing the page/discard the changed is a workaround. Clicking the edit icon of the flow instead works as expected.

I've showed it to @erondpowell in our today's chat, and he recommends raising a bug ticket. Find attached a short screen recording.

### To Reproduce

1. Open existing flow
2. Click on the blank space within an Operation

See screen recording attached

https://user-images.githubusercontent.com/12328155/187732305-278a592f-5574-4276-9e04-7e06e7e9bc09.mov

### Errors Shown

```
[Error] Error: Invalid value for <svg> attribute width="NaN"
[Error] Error: Invalid value for <svg> attribute height="NaN"
[Error] Error: Problem parsing d="M 370 540 L 390 540 Q 400 540 NaN NaN L NaN NaN Q 400 NaN NaN NaN L NaN NaN Q NaN NaN NaN NaN L NaN NaN Q NaN NaN NaN NaN L NaN NaN M NaN NaN L NaN NaN M NaN NaN L NaN NaN"
[Error] Error: Problem parsing d="M NaN NaN L NaN NaN Q NaN NaN NaN NaN L NaN NaN Q NaN NaN NaN NaN L NaN NaN Q 760 NaN NaN NaN L NaN NaN Q 760 60 770 60 L 787 60 M 787 60 L 779 52 M 787 60 L 779 68"
[Error] Error: Problem parsing d="M NaN NaN L NaN NaN Q NaN NaN NaN NaN L NaN NaN Q NaN NaN NaN NaN L NaN NaN Q 740 NaN NaN NaN L NaN NaN Q 740 400 750 400 L 767 400 M 767 400 L 759 392 M 767 400 L 759 408"
[Error] Error: Problem parsing d="M 370 540 L 390 540 Q 400 540 NaN NaN L NaN NaN Q 400 NaN NaN NaN L NaN NaN Q NaN NaN NaN NaN L NaN NaN Q NaN NaN NaN NaN L NaN NaN M NaN NaN L NaN NaN M NaN NaN L NaN NaN"
```

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

16.17.0

### What database are you using?

PostgreSQL

### What browser are you using?

Safari, Firefox

### How are you deploying Directus?

Docker

**Comment by licitdev** [comment]
Fixed in https://github.com/directus/directus/pull/15164, it'll be included in the next release.
Thank you! @amo42

**Comment by amo42** [comment]
Thanks @licitde. Seams I’ve missed the closed issue. Good to know that it was already on your list.
