### ISSUE TITLE
Ensure `perPage` param is working on API

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1534]
We've had a few reported cases of the `perPage` parameter not working on API requests. This is an alias for `limit` but we should still make sure it's functioning properly.

**Comment by WellingGuzman** [comment]
Hey @benhaynes,

`perPage` works, the situation is that `limit` works alone while `perPage` always worked along side `currentPage`

What we should do is make it act as a limit? with `currentPage` default to 1?

**Comment by benhaynes** [comment]
Yeah, exactly. Let's have the `currentPage` default to one to avoid these issues. We can ALSO have perPage default to the instance default `200` I think. That way *either* param can be used alone.

**Comment by WellingGuzman** [comment]
`perPage` are not being set as `limit` takes priority and `perPage` is deprecated

So `currentPage` is definitely is going to be set to 1 by default when `perPage` is set.
