### ISSUE TITLE
Flows: No revisions tracked when doing CRUD operations with full permission

### ISSUE THREAD

**Issue by ddiu8081** [directus/directus#15346]
### Describe the Bug

I created some flow to update items, but when the item is updated by the flow, I can't find the change log in Revisions panel:

![image](https://user-images.githubusercontent.com/1998168/187753958-38c920db-4cbe-4b86-ad5e-5b9bf38589af.png)

(Only records modified directly by the user can be found, not those modified by the system.)

### To Reproduce

- Create a flow that updates any value of a item (Both the event-hook jobs and CRON tasks seem to have problems).
- Trigger the flow.
- Open the changed item's revisions.

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

16.14.2

### What database are you using?

MySQL 8.0

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker Compose

**Comment by rijkvanzanten** [comment]
@ddiu8081 Could you do me a favor, and check if the revisions exist under `directus_revisions` directly in the database? Wondering if this is a presentation issue in the app, or if the API is failing to track the changes 🙂 

Also, are there any errors/warnings in the dev tools in the browser when you open that sidebar?

**Comment by ddiu8081** [comment]
@rijkvanzanten Thanks for the quick reply! 

I try to find a minimal reproduction: create an item that `value=0`, and "change value to 1 when value equals 0" in flow.

Here's my `directus_revisions` (id-1816: I create an item; id-1817: trigger flows)

<img width="1321" alt="ScreenShot 2022-09-01 at 03 09 35@2x" src="https://user-images.githubusercontent.com/1998168/187763098-37480773-349a-4994-ba4d-615559d8daef.png">

And there's no error or warnings in devtools:

![ScreenShot 2022-09-01 at 03 16 04@2x](https://user-images.githubusercontent.com/1998168/187763734-775f94b8-6150-41ae-a62c-2474257fb7fe.png)

**Comment by rijkvanzanten** [comment]
Hmm ok! Looks like the revision isn't tracked at all. Thanks for confirming 🙂

**Comment by ddiu8081** [comment]
Add more info:

Here's the screen recording, if needed 😄: https://share.cleanshot.com/S2QQmO

My flow operation settings:

<img width="840" alt="ScreenShot 2022-09-01 at 03 25 16@2x" src="https://user-images.githubusercontent.com/1998168/187765327-34b51303-e378-4b9b-a9c4-3a4df602f27c.png">

**Comment by freekrai** [comment]
I can take this one on.

**Comment by freekrai** [comment]
<img width="877" alt="Screen Shot 2022-09-05 at 4 17 01 PM" src="https://user-images.githubusercontent.com/21484/188519848-8a589281-01a3-4c0b-ab4f-54be5cb49dc5.png">
<img width="709" alt="Screen Shot 2022-09-05 at 4 17 18 PM" src="https://user-images.githubusercontent.com/21484/188519849-c6a066eb-e2c1-40a6-96a0-53522cd50fe1.png">

So I just tested this with 9.17.1, I created a `posts` collection with two fields, `title` and `test` then I set the flow to update `test` with `Does this work?` whenever I save a new record or update it.

And I see it show in the revisions, you can see in the table where it does the initial insert with just title, and then because I'm doing a non-blocking flow, the update shows up between that first save and the record for the flow which says what it did.

<img width="969" alt="Screen Shot 2022-09-05 at 4 12 19 PM" src="https://user-images.githubusercontent.com/21484/188519634-cc069c4f-e98b-4ac7-a6ad-b32adeddc004.png">
<img width="856" alt="Screen Shot 2022-09-05 at 4 18 20 PM" src="https://user-images.githubusercontent.com/21484/188519893-19efe6e4-27eb-4bf5-a853-1e91d925efb2.png">

I can try some other combinations to see if I can reproduce not seeing revisions.

**Comment by ddiu8081** [comment]
> I can try some other combinations to see if I can reproduce not seeing revisions.

@freekrai Could you try changing the operation premission from `$trigger` to `$full`? I noticed in the screenshot that the operator who modified the record is admin user.

**Comment by freekrai** [comment]
> > I can try some other combinations to see if I can reproduce not seeing revisions.
> 
> 
> 
> @freekrai Could you try changing the operation premission from `$trigger` to `$full`? I noticed in the screenshot that the operator who modified the record is admin user.

yeah, can try in a bit... Actually that brings up a point: does the user /operator who the action is run by have permission to add or edit revisions on your site?

**Comment by ddiu8081** [comment]
> yeah, can try in a bit... Actually that brings up a point: does the user /operator who the action is run by have permission to add or edit revisions on your site?

Yes, because it is a scheduled task on my site, I always set `$full` trigger premission to run flows, the item was also successfully edited but no revision.

**Comment by freekrai** [comment]
> @freekrai  Yes, because it is a scheduled task on my site, I always set `$full` trigger premission to run flows, the item was also successfully edited but no revision.

Yeah had to ask as I know revisions are separate permissions from editing or adding docs in the permissions settings (under system     tables) as I've run into that with other roles before, will test mine with $full shortly

**Comment by azrikahar** [comment]
It should be very likely to be a full permissions specific scenario, as CRUD operations aren't tracked for system operations i.e. null accountability (at least off the top of my head).

Relevant code references:

- `$full` sets accountability to `null` (which means system)

  https://github.com/directus/directus/blob/fd9c75b27cf795c4864fb61d5d5b5ecd3a65942e/api/src/operations/item-update/index.ts#L30-L31
  
- only track revisions when there's accountability (not null)

    https://github.com/directus/directus/blob/fd9c75b27cf795c4864fb61d5d5b5ecd3a65942e/api/src/services/items.ts#L555-L556
    
- as they are "needed" to populate `user`, `ip`. `userAgent` and `origin` (maybe there needs to be particular values to indicate system "user", as there's no such "user" in place yet. Ref https://github.com/directus/directus/discussions/15345#discussioncomment-3520549)

    https://github.com/directus/directus/blob/fd9c75b27cf795c4864fb61d5d5b5ecd3a65942e/api/src/services/items.ts#L562-L572

**Comment by freekrai** [comment]
> It should be very likely to be a full permissions specific scenario, as CRUD operations aren't tracked for system operations i.e. null accountability (at least off the top of my head).
> 
> Relevant code references:
> 
> - `$full` sets accountability to `null` (which means system)
> 
>   https://github.com/directus/directus/blob/fd9c75b27cf795c4864fb61d5d5b5ecd3a65942e/api/src/operations/item-update/index.ts#L30-L31
>   
> - only track revisions when there's accountability (not null)
> 
>     https://github.com/directus/directus/blob/fd9c75b27cf795c4864fb61d5d5b5ecd3a65942e/api/src/services/items.ts#L555-L556
>     
> - as they are "needed" to populate `user`, `ip`. `userAgent` and `origin` (maybe there needs to be particular values to indicate system "user", as there's no such "user" in place yet. Ref https://github.com/directus/directus/discussions/15345#discussioncomment-3520549)
> 
>     https://github.com/directus/directus/blob/fd9c75b27cf795c4864fb61d5d5b5ecd3a65942e/api/src/services/items.ts#L562-L572

Sounds like that then, will follow the $full line and see where it leads, just had to ask the questions first

**Comment by freekrai** [comment]
Just to update the fix that's in the PR, setting `customAccountability` to the following:

```
customAccountability = {
  user: null,
  role: null,
  admin: true,
  app: true,
  ip: '',
  userAgent: '',
  origin: '',
  share: undefined,
  share_scope: undefined,
  permissions: [],
};
```

rather than the previous `customAccountability = null;` creates the revision tracking without linking it to a user and treating it as a system revision basically (though it's not called that).
