### ISSUE TITLE
Include a zip/tarball to each release

### ISSUE THREAD

**Issue by WellingGuzman** [directus/directus#1535]
We should start including a zip/tarball in each new release.

- ~zip/tarball with the same files as cloning the repo~
- zip/tarball compressed with composer dependencies included

Should we include any zip/tarball?

**Comment by benhaynes** [comment]
Doesn't GitHub do this automatically?

https://github.com/directus/directus/releases

https://github.com/directus/directus/archive/6.4.0-beta.3.zip
https://github.com/directus/directus/archive/6.4.0-beta.3.tar.gz
etc...

Do we have this for the `build` branch?

**Comment by WellingGuzman** [comment]
oh right, they include the source by default, then we only have to include the `build` version in the release.

We don't do releases on `build` branch.

**Comment by benhaynes** [comment]
OK, let's add that to our release workflow!
