### ISSUE TITLE
JSON default values are returned stringified by the API

### ISSUE THREAD

**Issue by wc-davide** [directus/directus#15351]
### Describe the Bug

I created a Repeater field in directus with a default value (JSON Array) but once I save the field it converts the default value into a string.
When I try to create a new item in my collection it will then display a warning, which was added in this PR https://github.com/directus/directus/pull/12592
I'll also attach a screenshot of the database design of the field(MSSQL)

Creating the field with default value:
![image](https://user-images.githubusercontent.com/46521712/187895239-2bc358e4-d907-4692-8880-49de8fc6566e.png)

After saving this is how it looks:
![image](https://user-images.githubusercontent.com/46521712/187895283-a398a2dd-da56-487c-9167-889b0990cb48.png)

MSSQL table design of the field:
![image](https://user-images.githubusercontent.com/46521712/187895557-34c92e7f-ceba-47a7-862b-3d7a45eb7e6e.png)

### To Reproduce

1. Create a repeater field with a default value of (example):
```json
[{"width":0,"size":25},{"width":600,"size":15},{"width":1200,"size":10}]
```
2. Save
3. Open the field again and see it has stored the default value as string
4. Try to create a new item in the collection, it will display the warning/error

### Errors Shown

When creating a new item in the collection:
![image](https://user-images.githubusercontent.com/46521712/187895329-beb57a5c-f646-4965-9108-733b91603542.png)

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

n/a

### What database are you using?

MSSQL 2016

### What browser are you using?

Brave

### How are you deploying Directus?

k8s

**Comment by rijkvanzanten** [comment]
@wc-davide Does this happen exclusively on `repeater` fields, or on any JSON type field with a default value?

**Comment by wc-davide** [comment]
> @wc-davide Does this happen exclusively on `repeater` fields, or on any JSON type field with a default value?

I tried creating a `tags` field:
![image](https://user-images.githubusercontent.com/46521712/188081302-bcbd4e5e-b859-4072-942a-75a0919d338c.png)

Saving and reopening the field shows the default value as string on this one too:
![image](https://user-images.githubusercontent.com/46521712/188081391-1ffaa657-901d-418a-8934-2e4763ac8fb2.png)

But this time there's no error/warning when creating a new item, it just doesn't seems to work (no default values):
![image](https://user-images.githubusercontent.com/46521712/188081515-b18698a6-2e35-458b-9f1d-91663b6e13a8.png)

But it has data in "Edit Raw Value" (which I guess it doesn't show in the field because it can't parse it?):
![image](https://user-images.githubusercontent.com/46521712/188081643-1156419d-2629-4778-9f79-06ddaf4a71ee.png)

**Comment by rijkvanzanten** [comment]
> But it has data in "Edit Raw Value" (which I guess it doesn't show in the field because it can't parse it?):

Yup! Same bug. In both cases, the default value isn't correctly cast back to JSON from the API 👍🏻

**Comment by rijkvanzanten** [comment]
Linear: [ENG-197](https://linear.app/directus/issue/ENG-197/json-default-values-are-returned-stringified-by-the-api)
