### ISSUE TITLE
Singletons cant be saved

### ISSUE THREAD

**Issue by Nitwel** [directus/directus#15364]
### Describe the Bug

After saving on a singleton collection, no values get saved.

### To Reproduce

1. Create a new Singleton collection
2. Add a field to it
3. Open said collection
4. Write something
5. Press save

The written text should now disappear.
The item does get created in the api but just contains an id equal to `1` and that's it.

The Request to the API:

```
PATCH | http://localhost:8080/items/single

{"my_field":"wwww"}
```

Response:
```
{"data":{"id":1,"my_field":null}}
```

The body look and response look fine to me so it must be a bug in the api. 🤔 

### Errors Shown

None

### What version of Directus are you using?

latest

### What version of Node.js are you using?

latest

### What database are you using?

mariadb

### What browser are you using?

firefox

### How are you deploying Directus?

locally

**Comment by Nitwel** [comment]
Might be caused by #15339 as it is the only issue that made changes to singletons.

**Comment by azrikahar** [comment]
Seems like it is, as the `req.body = {}` here is currently removing the body sent when saving a singleton:

https://github.com/directus/directus/blob/d29c2dfc3f3e0cfb21177194710a9fe37eaae944/api/src/middleware/validate-batch.ts#L14-L17
