### ISSUE TITLE
Unable to change field interface from Code back to Map

### ISSUE THREAD

**Issue by rc1** [directus/directus#15368]
### Describe the Bug

I have a field of type "Polygon".

On an entry page, the field will display a map interface with a handy tool to create polygon on the page.

I have to enter in some raw geojson, so I change the fields "interface" to code from map.

Now I cannot change the field back to map. There is no option to remove the "Code" interface and change it back to a "Map" interface.

![image](https://user-images.githubusercontent.com/166915/188168670-38cbf21d-a859-4203-8e32-b548420afa8f.png)

### To Reproduce

Create a field on a collection with type Polygon.

Add an entry to the collection and draw a polygon on the map.

Edit the field's interface properties to be "Code".

Save the edit to the field.

Try and change the field back to a map. This is not possible. 

### Errors Shown

None. 

### What version of Directus are you using?

9.41.1

### What version of Node.js are you using?

n/a

### What database are you using?

Postgres with PostGis extensions

### What browser are you using?

Chrome

### How are you deploying Directus?

docker

**Comment by licitdev** [comment]
@rc1 I am unable to replicate the issue on `9.17.0`. 

Please kindly provide a screenshot / recording of this field, showing the schema and interface tabs. There's no `code` interface available in my testing.

![image](https://user-images.githubusercontent.com/26413686/188278167-ff1e2624-688f-4c69-af0e-5067c68d270c.png)

Also, what is the data type of the said field in the database? Mine's `geometry(polygon, 4326)`.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/26413686/188278113-8c5e213e-8ba2-4853-811e-c16d5ab4c26f.png">

The updating of raw geojson can be done by editing the raw value. 
Here's a recording of my testing. 

https://user-images.githubusercontent.com/26413686/188278217-23c90f43-f9fb-4518-bf68-69f11f9957d7.mov

**Comment by azrikahar** [comment]
I can't seem to reproduce this after creating a Map field of type `polygon` as well. 

`code` interface itself is (and has been) only available to `geometry` type field, which means `Geometry (All)` when creating a Map field:

https://github.com/directus/directus/blob/fd9c75b27cf795c4864fb61d5d5b5ecd3a65942e/app/src/interfaces/input-code/index.ts#L38

`geometry` type not to be confused with geometry polygons, as the latter will be typed as `geometry.Polygon` instead, similar to how Map interface specifically supports `geomtry.Polygon`:

https://github.com/directus/directus/blob/fd9c75b27cf795c4864fb61d5d5b5ecd3a65942e/app/src/interfaces/map/index.ts#L12-L24

which why it is rather odd how it would be selectable for polygon fields. I've also attached my attempt at the end of this comment, where I intentionally swapped back and forth between `code` and `map` interface for "Geometry (All)` field, but it seems to work on my end.

With that said, I'll close this for now, but happy to debug further when more info arises (particularly curious how `code` interface was selectable for `polygon` field in your setup).

---

Attempt:

https://user-images.githubusercontent.com/42867097/188548588-8f8072ff-8a35-4990-a45e-5307b95b23cc.mp4
