### ISSUE TITLE
Add default CSS outline to all buttons/interfaces for accessibility

### ISSUE THREAD

**Issue by colemahatmccreary** [directus/directus#15373]
### Describe the Bug

Using 'tab' to traverse the app UI does not display any button/link outlines. 

Only left most navigation bar will highlight the active icon (content, insights, etc), but beyond those there's no indication of where you are on the page if using tab/arrows.

Like this:
<img width="872" alt="Screen Shot 2022-09-02 at 9 16 35 AM" src="https://user-images.githubusercontent.com/40645344/188196098-990e76a2-ab75-472b-a60c-536188f327f2.png">

### To Reproduce

Tab around any page in the app

### Errors Shown

N/A

### What version of Directus are you using?

Standard Cloud 9.16.1

### What version of Node.js are you using?

Standard Cloud

### What database are you using?

Standard Cloud

### What browser are you using?

Chrome

### How are you deploying Directus?

Standard Cloud

**Comment by rijkvanzanten** [comment]
Treating this as a bigger enhancement discussed/tracked in https://github.com/directus/directus/discussions/4825 🙂
