### ISSUE TITLE
Editing Relational Item (M2M) in Drawer required new input for all mandatory fields

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/directus#15379]
### Describe the Bug

I have a M2M Relation field in Collection A, if I want to edit the relational Item in Collection B, the Drawer opens and if I want to save it, I got an error, that I have to fill all fields which are defined as Mandatory/Required. (All of this fields are already filled, but I have to change the value to be able to save it)

Here Type is required, even it is set already previously
![image](https://user-images.githubusercontent.com/15796397/188259531-fd76e886-bce9-4222-ae80-dd9e8fe3df66.png)

### To Reproduce

1. M2M Relation between 2 Collections (not sure if other relations have the same behaviour).
2. Try to Edit an Item of Collection A via Drawer from Collection B

### What version of Directus are you using?

9.17.0

### What version of Node.js are you using?

14.20.0

### What database are you using?

MySQL 8

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by koksikus** [comment]
The problem still occurs in the latest version of Directus 9.17.2 In deeper relation but clickable. Don't look at the data because this is my version for testing.

https://user-images.githubusercontent.com/90528895/188687807-97cdefee-ca47-4ec4-b430-34664291f910.mp4

**Comment by licitdev** [comment]
@koksikus Thank you for pointing out the issue. 👍
Pushed a fix in https://github.com/directus/directus/pull/15433.

**Comment by koksikus** [comment]
I confirm, in 9.17.3 it works
