### ISSUE TITLE
impossible to invite Team members with existing accounts

### ISSUE THREAD

**Issue by cnschu** [directus/directus#15388]
### Describe the Bug

if you invite a new team member to your team, directus generates an invitation e-mail, that allows only for the creation of a new account. It's not possible to invite an existing account.

### To Reproduce

1) create a new Team
2) go to "members" tab
3) enter e-mail to invite
4) click on "send invites"
5) open invite E-Mail
6) click on "join directus"
7) On the opened webpage, it is impossible to login. You have to create a new account.

### Errors Shown

Invalid Payload

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

it's not displayed on the webpage on https://directus.cloud/

### What database are you using?

it's not displayed on the webpage on https://directus.cloud/

### What browser are you using?

Crome

### How are you deploying Directus?

https://directus.cloud/

**Comment by azrikahar** [comment]
Hi! That does seem odd. Will pass this along to our cloud team so that they may follow up on this issue better 👍

In general, or issues specific to Directus Cloud projects, please do reach out via the Live Chat in our Cloud Dashboard as that's the best way to get help with your Cloud projects 🙂

**Comment by cnschu** [comment]
Ok.
Can you please elaborate on the matter (why is it an installation specific problem?)
I trust your judgment on that, but a little more information would be nice. So i can understand what is the error made by the cloud team that resulted in this error. So that i can avoid making the same mistake with my own installation of the software.

**Comment by azrikahar** [comment]
Linking this comment here which was in response to your other comment for future reference: https://github.com/directus/directus/issues/15389#issuecomment-1237629290 

---

In this case, Team members and invites are specific to Directus Cloud's Dasboard, not Directus itself (Directus itself is referring to your Directus projects, not Dashboard). When specifying that this is not related to Directus itself, this holds true for self-hosted installations as well, so we technically can't "avoid making the same mistake with own installation" as you inquired 🙂

For aforementioned reasons, it is why we'll need assistance from the Cloud team to look into this. This is also why it's highly recommended to reach out via the Live Chat in your Cloud Dashboard so it will reach the appropriate point of contacts directly 👍
