### ISSUE TITLE
[9.17.0] can't add new translation string in fields

### ISSUE THREAD

**Issue by leosin** [directus/directus#15383]
### Describe the Bug

can't add new translation string in fields

eg: field > note
or
validation > Custom Validation Message

https://user-images.githubusercontent.com/3676670/188269948-f90d7c8d-97f7-45db-b3f3-46207a1c6c81.mp4

### To Reproduce

update to 9.17.0

### What version of Directus are you using?

9.17.0

### What version of Node.js are you using?

14.0

### What database are you using?

mysql 8

### What browser are you using?

edge

### How are you deploying Directus?

locally

**Comment by licitdev** [comment]
@leosin Thank you for your report. 👍 
Fixed in https://github.com/directus/directus/pull/15376
