### ISSUE TITLE
Adding a relationship clears existing related values with SQLite

### ISSUE THREAD

**Issue by Juanjo-GEx** [directus/directus#15398]
### Describe the Bug

Having two collections joined by a many-to-one relationship, if we add an image-type field to the data model of the destination collection, the previously established relationship disappears in the source collection.

### To Reproduce

**Data model**
1-We create the destination collection (Ex.: _Templates_)
2-We create the source collection (Ex.: _Pages_)
3-In the source collection we add a many-to-one relationship type field to the destination collection.

**Content**
1-We add records to the destination collection (_Templates_)
2-We add records to the source collection (_Page_) including the field that relates them.

**Data model**
4-We add an image type field to the destination collection

**Content**
3-In the source collection, **the data** of the field that relates both tables disappears.

### Errors Shown

The error is not included as a log in the terminal.

### What version of Directus are you using?

9.17.0

### What version of Node.js are you using?

16.16.0

### What database are you using?

SQLite 5.0.11

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by br41nslug** [comment]
Following the provided steps i was not able to reproduce this unfortunately.

**Comment by Juanjo-GEx** [comment]
I share a video so you can reproduce the bug:
[https://www.loom.com/share/3513b7589dc94c97a9b03267f1f5fdc2]Error's video

**Comment by br41nslug** [comment]
I have updated my test as you mentioned M2M in this issue but judging from the video you have a M2O relation from `pages.template_builder` to `template.key` (and the reverse O2M).
Can you clarify exactly how you've set up this relation? by the look of the names the `template_builder` should be a o2m/m2m/m2a but it is m2o in the video.

**Comment by Juanjo-GEx** [comment]
You are right and it does not explain well the relation between both collections. The relationship is **many to one** and not many to many as I mentioned at the beginning. In other words, only one _template_ can be applied to each _page_. But that _template_ can be used on multiple _pages_.

The only thing I have done is configure the many-to-one relationship in the **pages collection** as I show in the video and define which **templates is the destination collection**. In the templates collection I have not defined any relationship. That relationship was created automatically.

[Vídeo](https://www.loom.com/share/68469738dabe4a36a199c3bd3278f401)

**Comment by br41nslug** [comment]
Alright so with a m2o relationship that means the foreignKey is stored on the `pages` collection so im not directly sure how that would be affected by a field change to `templates` 🤔 Is the relation actually cleared if you refresh the page after adding the image field or is it visually losing its display data?

**Comment by Juanjo-GEx** [comment]
You don't have to refresh the page to get the error. As shown in the first video, automatically adding an image field to the **templates collection** breaks all the relationships of the rows in the **pages collection**. That is, the field that links them (many to one) in the pages table is still there, but all the relationships of its items (rows) disappear and that field of the row, which was currently linked with a template, when making that change, appears then empty.

**Comment by br41nslug** [comment]
The reproduction steps used to reproduce this in the end are the following (only works in SQLite as far as i can tell):
- create `table_a` and `table_b`
- add a m2o relation from `table_a` to `table_b` (the reverse o2m is not needed)
- add a couple of records with related (1 or 2 in each was enough in my test)
- check the items in `table_a`
- add an image field to `table_b`
- check `table_a` again and the foreign_key for each record is `NULL`
