### ISSUE TITLE
Ability to delete ALIAS/RELATIONAL fields in settings

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#154]
Currently there is no way to delete ALIAS or RELATIONAL fields within the settings page

**Comment by WellingGuzman** [comment]
@benhaynes this got me thinking, not all columns/fields are actual columns, so right now you can drop a column but what if the column is not real? we should delete the references, even though the column doesn't exists.

**Comment by benhaynes** [comment]
Exactly. Now that we have column delete this should be easier, right @WellingGuzman ?
