### ISSUE TITLE
Don't display dropdown if no folders exist in File Library

### ISSUE THREAD

**Issue by YannickMol** [directus/directus#15405]
### Describe the Bug

In the File Library, the dropdown is visible even when there are no folders. 
![image](https://user-images.githubusercontent.com/13256289/188500792-c662549e-18d5-4cba-a253-47c8dcd91ad1.png)

### To Reproduce

1. Go to File Library
2. View the folders in the File Library by clicking the dropdown. This is possible even if there are no folders.

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

14.15.4

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

DigitalOcean

**Comment by chaiwattsw** [comment]
I will take this

**Comment by azrikahar** [comment]
@chaiwattsw thanks!
