### ISSUE TITLE
Can't delete file in multiple_files

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1541]
## Version Info
  - Directus version and branch: Directus version and branch: v6.4.0-rc1

## Expected Behavior
Clicking the ❌  in the bottom right of a photo/file removes the file from the item

## Actual Behavior
Clicking the button doesn't do anything

## Steps to Reproduce
 1. Create table w/ multiple_files interface
 2. Add multiple files to an item
 3. Save
 4. Edit item
 5. Remove one of the files with the ❌  button

**Comment by WellingGuzman** [comment]
@rijkvanzanten Does the junction table has status column? can you share schema of the junction table? I couldn't reproduce this issue

**Comment by WellingGuzman** [comment]
I've reproduced this issue on `multiple_files_csv` interface
