### ISSUE TITLE
Related images not rendering in table layout

### ISSUE THREAD

**Issue by flayks** [directus/directus#15417]
### Describe the Bug

Since 9.17, related images (here `country` M2O in a `location` collection) don't show up in the table layout anymore.

Now:
<img width="608" alt="image" src="https://user-images.githubusercontent.com/273716/188579160-dcaa683e-024f-4bc2-89ba-918b7bf8a21b.png">

Before (still with a [visual bug](https://github.com/directus/directus/issues/14926) however it is showing):
<img width="537" alt="image" src="https://user-images.githubusercontent.com/273716/188579491-eee978e7-7e2d-462d-92b1-1b232d7a83bc.png">

This might be linked to that PR? https://github.com/directus/directus/pull/15155

### To Reproduce

Add a related field and change the display rendering to Thumbnail of an image file and a text

<img width="622" alt="image" src="https://user-images.githubusercontent.com/273716/188580054-f7ed6166-9a5e-4a98-b19c-92e59bb38593.png">

### Errors Shown

Thumbnail field returns a null class and -- as the content even though there is an image

```html
<div class="render-template" interface="select-dropdown-m2o" interface-options="[object Object]" type="integer" data-v-3c17af7e="" data-v-972ab270="" data-v-72e35180="" data-v-7b6d5623="">
  <span class="vertical-aligner" data-v-3c17af7e=""></span>
  <!-- this next line especially -->
  <span class="null" data-v-17820dde="" data-v-3c17af7e="">--</span>
  <span data-v-3c17af7e="">&nbsp;&nbsp;</span>
  <span data-v-3c17af7e="">France</span>
</div>
```

### What version of Directus are you using?

9.17.1

### What version of Node.js are you using?

16.17.0

### What database are you using?

MariaDB

### What browser are you using?

Brave/Chrome

### How are you deploying Directus?

locally

**Comment by izoukhai** [comment]
Can confirm, also happens in item view

**Comment by baranelitez** [comment]
I think this is also related: Files added with the `Files` relation (multiple images for a single object) have their thumbnails not rendered.

**Comment by alejandrorbraun** [comment]
Hi @baranelitez , I have Files fields added with the `Files` relation and the thumbnails are no longer being rendered. I recently upgraded from 9.13 to 9.17.4.

**Comment by Nitwel** [comment]
This seems to be working for me in 9.18, feel free to reopen it when it persists.
Make sure you have the `image` display selected and configured the display-template like in the video below:

https://user-images.githubusercontent.com/22577866/191078752-60ce87c5-a21d-40ae-b3b7-d65c7c53d2f8.mp4

**Comment by flayks** [comment]
Looks good to me as well! I had to reconfigure the Display settings but it shows up. Thanks ✌️

**Comment by alejandrorbraun** [comment]
Hi @Nitwel , I just updated from 9.17 to 9.18 and the bug still exists when using the Files field as well as M2A field. I've attached a video clip using the Files field. I can add images just fine, but the Thumbnails do not show any information and show `--` instead. This occurs both with the table view and item view. I've looked through the code base and can't seem to find any `v-image` fields when using `Files`, but I'm not very familiar with directus' backend and didn't have a chance to see if this would be implemented through one of the template functions used. Please let me know if there's anything I can do to help.

[Screencast from 09-19-2022 06:41:00 PM.webm](https://user-images.githubusercontent.com/31396210/191137871-a7ce3abc-ebc2-477e-a758-1eb0cf1e2a09.webm)

**Comment by alejandrorbraun** [comment]
Good morning @kamil-malinski , there is no file object to select for either display or interface when using the `Files` type.

**Comment by brandnewx** [comment]
Directus is still plagued with bug regression like this, again and again. Any bug fix should have an accompany unit test that makes sure the bug is fixed and will never return.
