### ISSUE TITLE
Allow modification of the default `robots.txt` content

### ISSUE THREAD

**Issue by melrefaie** [directus/directus#15421]
### Describe the Bug

robots.txt file prevent Twitterbot from getting image when share any thing.
is there is any way we can fix this or edit robots.txt.

```
WARN:  The image URL https://board.ecommaraby.com/assets/5170c498-a2ad-4dd1-a3cf-af55c4dca5b5?fit=cover&width=1200&height=800&quality=80 specified by the 'twitter:image' metatag may be restricted by the site's robots.txt file, which will prevent Twitter from fetching it.
```

### To Reproduce

share any asset to twitter 

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

v16.16.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

server

**Comment by azrikahar** [comment]
Currently the `robots.txt` served by the API has the following value:

```robots
User-agent: *
Disallow: /
```

However as described in [Twitter's Developer Platform docs](https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started#crawling), it respects the `robots.txt` specification and gets blocked in the process. The suggested value is the following instead, to specifically allow Twitterbot:

```robots
User-agent: Twitterbot
Disallow:

User-agent: *
Disallow: /
```

PR #13754 did made it into a constant value, so perhaps making it as a configurable env variable would be a potential solution, but not sure how newlines would interact in such cases.

**Comment by azrikahar** [comment]
**Full disclaimer: the following snippet should not be treated as an official solution, but more so to offer a rather hacky workaround in the mean time.**

@melrefaie seems like the following hooks extension can be a workable temporary solution, would you mind trying it on your side?

```js
const customRobotsTxt = `
User-agent: Twitterbot
Disallow:

User-agent: *
Disallow: /
`.trim();

module.exports = ({ init }) => {
	init('app.before', ({ app }) => {
		app.get('/robots.txt', (_, res) => {
			res.set('Content-Type', 'text/plain');
			res.status(200);
			res.send(customRobotsTxt);
		});
	});
};
```

**Comment by melrefaie** [comment]
@azrikahar  Thanks for your reply .

i added extension with your code. still twitter bot can't get image.

robots.txt  file changed 
https://board.ecommaraby.com/robots.txt

**Comment by melrefaie** [comment]
Thanks i fixed it with this code.

```
const customRobotsTxt = `
User-agent: Twitterbot
Allow: /

User-agent: *
Disallow: /
`.trim();

module.exports = ({ init }) => {
  init("app.before", ({ app }) => {
    app.get("/robots.txt", (_, res) => {
      res.set("Content-Type", "text/plain");
      res.status(200);
      res.send(customRobotsTxt);
    });
  });
};

```

**Comment by rijkvanzanten** [comment]
Ohh this is very interesting 🤔 robots.txt is there as a "feature" to make sure Google (et al.) don't scrape any files from the /assets endpoint that you didn't intend to make public. That being said, it does indeed also mean that open graph use is disabled. We should make this an env var 👍🏻

**Comment by alexreid** [comment]
I've also just run into this problem with Directus Cloud, so it'd be great to have a solution that works there as well.

**Comment by flayks** [comment]
Running into the same issue as well, which is a bit constraining as I'm using assets for my share images 🙈

**Comment by andrii-bodnar** [comment]
Faced the same issue. As a result, can't update Directus and I have to use the 9.12.1 version where this issue is not present.

**Comment by azrikahar** [comment]
@flayks @andrii-bodnar were you guys able to try the custom hook extension in https://github.com/directus/directus/issues/15421#issuecomment-1243752763? It should help as a workaround in the meantime 👍

**Comment by andrii-bodnar** [comment]
@azrikahar I am using the Docker image of Directus, so I can't change the code without some hacky solutions

**Comment by azrikahar** [comment]
@andrii-bodnar just to clarify, it is a custom hook extension ([docs reference](https://docs.directus.io/extensions/hooks.html)), not a change in the codebase itself! 🙂

It would require the same steps that you will need to take for [building an extension](https://docs.directus.io/extensions/creating-extensions.html#building-your-extension) and [installing it](https://docs.directus.io/extensions/creating-extensions.html#installing-an-extension), though for the case of Docker, you would mount it to [/directus/extensions](https://docs.directus.io/self-hosted/installation/docker.html#persistence), more specifically `/directus/extensions/hooks/robots/index.js` in this case.

**Comment by andrii-bodnar** [comment]
@azrikahar, very interesting, thanks a lot for the explanation! 🙂 

I will definitely try this.

**Comment by andrii-bodnar** [comment]
@azrikahar this approach works like a charm, thanks a lot!

**Comment by flayks** [comment]
> @flayks @andrii-bodnar were you guys able to try the custom hook extension in [#15421 (comment)](https://github.com/directus/directus/issues/15421#issuecomment-1243752763)? It should help as a workaround in the meantime 👍

Sorry for the late answer. This fixes the issue indeed, works well in an online Docker environment. I still think it could be added as a default in the core since it's very specific to Twitter. Having to build an extension is a little bit much imo 😅 good workaround though.

**Comment by kristjanmar** [comment]
I'm also running into this issue with my paid Directus Cloud install. The preview images are not accessible when sharing on Twitter.

**Comment by oberbayer** [comment]
> @andrii-bodnar just to clarify, it is a custom hook extension ([docs reference](https://docs.directus.io/extensions/hooks.html)), not a change in the codebase itself! 🙂
> 
> It would require the same steps that you will need to take for [building an extension](https://docs.directus.io/extensions/creating-extensions.html#building-your-extension) and [installing it](https://docs.directus.io/extensions/creating-extensions.html#installing-an-extension), though for the case of Docker, you would mount it to [/directus/extensions](https://docs.directus.io/self-hosted/installation/docker.html#persistence), more specifically `/directus/extensions/hooks/robots/index.js` in this case.

Guys, that is probably a noob question as I've never build a directus extension myself: I've tried to follow the steps for building and installing an extension, but the template for hook extensions looks totally different:
```
export default ({ filter, action }) => {
	filter('items.create', () => {
		console.log('Creating Item!');
	});

	action('items.create', () => {
		console.log('Item created!');
	});
};
```

I've tried:

- Doing scaffolding, building with the above code by @azrikahar . The result: 
`"use strict";const t="\nUser-agent: Twitterbot\nAllow: /\n\nUser-agent: *\nDisallow: /\n".trim();module.exports=({init:e})=>{e("app.before",(({app:e})=>{e.get("/robots.txt",((e,n)=>{n.set("Content-Type","text/plain"),n.status(200),n.send(t)}))}))};
`
- Trying, basically by guessing, to merge the template and above code. The result:
```
export default ({ init }) => {
  const customRobotsTxt = `
	User-agent: Twitterbot
  Allow: /

  User-agent: *
  Disallow: /
  `.trim();

	init("app.before", ({ app }) => {
    app.get("/robots.txt", (_, res) => {
      res.set("Content-Type", "text/plain");
      res.status(200);
      res.send(customRobotsTxt);
    });
  });
};
```

- Just using the above code by @azrikahar as the extension index.js, without scaffolding, building, installing

But nothing worked, robots.txt is unchanged. Any idea what am I doing wrong?! Thank you very much for any hint!

**Comment by oberbayer** [comment]
When directly looking at the docker volume on the filesystem, I can find the folder and the index.js, yet directus is ignoring it somehow... Hmm.

**Comment by paescuj** [comment]
> I also load the package extension "directus-extension-wpslug-interface" as a dependency. But mixing package and local extensions in one installation should not be a problem, right?

Yes, this shouldn't be a problem 👍 

> When directly looking at the docker volume on the filesystem, I can find the folder and the index.js, yet directus is ignoring it somehow... Hmm.

Please confirm that the volume is mounted at the correct path (with the default docker image it's `/directus/extensions`, see also https://docs.directus.io/self-hosted/config-options.html#extensions).

Also look out for errors in the logs of the container. Due to #16284 you might need to define the environment variable `LOG_STYLE=raw` to see all log entries until the next release.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-196](https://linear.app/directus/issue/ENG-196/allow-modification-of-the-default-robotstxt-content)
