### ISSUE TITLE
Workflow: Not Saving Per Status

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1542]
### Saving Normally:
Working. This saves a table's permissions with `NULL` under `status_id` and is the ONLY value for the table/group.

### Saving a Workflow:
Not working. Should save table/group values for EACH status option in the statusMapping and the `NULL` record (for normal/global, see above) should be removed. When viewing the Settings>Groups>Permissions it should have the workflow open by default (pageLoad) so you can see all the privileges.

**Comment by benhaynes** [comment]
A new issue that has come to my attention: when we expand the rows (one for each status) then there are two columns that don't apply:

`add` (soon to be create) and `nav_listed`... because they don't depend on `status`. So we'll need a new interface.

**Comment by rijkvanzanten** [comment]
What is the status of this issue? What is the problem in the first place? What is this `add` column you're referring to? What new interface do we need?

**Comment by benhaynes** [comment]
The status is: incomplete.

The problem is the workflow (saving permissions by status) is not working. 

The `edit` column: eg, an item in draft status can not be edited. (makes sense)
The `add` column: eg, an item doesn't have a status if it hasn't been added yet. (so this needs to be removed)

The interface: when you go to permissions on the preview site, and click the "workflow" button... Notice the expanded rows. This is the interface referred to.

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/5)
