### ISSUE TITLE
Users created in admin have no access to API

### ISSUE THREAD

**Issue by istvano** [directus/directus#1543]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests please use the [Directus FeatHub](http://feathub.com/directus/directus) to make a new request or vote for existing ones, or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues.

## Version Info
  - Directus version and branch: 6.3.9
  - PHP version:  7.0
  - MySQL version:  5.6
  - Web server: Apache 2.4
  - OS name and version:  Centos Linux 

## Expected Behavior
A user created in the admin should can send API requests to the API endpoint

## Actual Behavior
Only the admin user's token is accepted when making API request

## Steps to Reproduce
 1. create a user in the backend using admin privileges
 2. curl -H "Authorization: Bearer Py8RumuLD7HE5juFrOR5" https://mysite.com/api/1.1/tables
 3. 

## Logs or Screenshots
An interesting thing is that the admin user's token is LONGER 
my admin user token that was generated by the platform is: 32 chars long
my other users which I add using the GUI has a token of 16 chars

If I manually insert a 32 chars long token it also works for the users I created via the admin.

thanks

**Comment by WellingGuzman** [comment]
Hey @istvano,

If you go to the editing page of the user you changed the token manually, does the token still the same?

Where are you getting the token that's not working from? directly from the database or the cms?

**Comment by istvano** [comment]
Hi,

- in the CMS gui the admin user has a token that is 32 chars long
- in the CMS gui when a token is generated for any users I add via the GUI they all have a token of 16 chars long. 
- if I click generate token on the CMS page by clicking on generate new. The token will be 16 chars long
- If I manually in the CMS add a token that is 32 chars long I can log in using curl.

I hope I did answer all the questions.

ps; I have not had a look at in the db

**Comment by istvano** [comment]
Having had a look at the db it seems that it also stores the token as 16 long string. I am guessnig the bug is somewhere in the token generation code on the frontend.

ps: I have also cleaned the whole db and reinstalled the app. it is still the same.

**Comment by WellingGuzman** [comment]
Hey @istvano, thanks for the information.

I had an idea what this was, just wanted to make sure we were in the same page.

So what happens here, is that the non admin users are forbidden to see their own token, so this make the interface to generate one every time you visit that user editing page, which give the idea of that that's the actual token.

So the bugs goes beyond to everybody hiding the token except for the same user if it's an admin.

We've pushed a patch, hopefully we make things work again as expected.

Although this going to be tagged in the next release 6.3.10, in the meantime you could `cherry-pick` the commit or if understand that the master branch may or may not be broken, use the master branch :)

**Comment by lastlink** [comment]
Any updates on this? It would be very useful for normal users to use the api as well.

**Comment by rijkvanzanten** [comment]
@lastlink Normal users can use the api! You can request a user's token by sending his/her credentials in a `POST` request to `/api/1.1/auth/request-token`: https://api.getdirectus.com/1.1/#Authentication. Once you have the user's token, you can use it to authenticate any request just like you would with an admins token 👍

**Comment by lastlink** [comment]
I got this to work only after logging in as admin and generating an api token for the user then saving. Is there a way to have this token auto generate or do admins always have to go in and generate them for them? @WellingGuzman mentioned some 6.3 patch?
