### ISSUE TITLE
Error installing on M1 Mac

### ISSUE THREAD

**Issue by 3zzy** [directus/directus#15466]
### Describe the Bug

Unable to install Directus locally on M1 Mac

### To Reproduce

Run `npm init directus-project aes-backend` on M1 Macbook

### Errors Shown

Error: Cannot find module '@napi-rs/snappy-darwin-x64'
Node.js v18.8.0
✖ Installing Directus
Error: undefined
npm ERR! command failed
npm ERR! command sh -c -- create-directus-project aes-backend

### What version of Directus are you using?

9.17

### What version of Node.js are you using?

18.8.0

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

Local

**Comment by rijkvanzanten** [comment]
Try running `npm init -y && npm install directus && npx directus init` instead 🙂
