### ISSUE TITLE
Problems when creating an element with the side-by-side translations view

### ISSUE THREAD

**Issue by MeYan-08** [directus/directus#15460]
### Describe the Bug

Creating an item with the side-by-side translation view creates 3 translation items instead of two (or forbid you to create the element under certain circomstances like the presence of non-nullable fields or unique fields)

### 1. Create a collection with a translation field

| collection_1  | 
| ------------- |
| id | 
| translations |   

| collection_1_translations  | 
| ------------- |
| id | 
| collection_1_id | 
| languages_id | 
| name | 

### 2. Go to the creation page for "collection_1" and use the side-by-side translation view

![image](https://user-images.githubusercontent.com/18357403/188926097-2e5ac5ab-ab86-44a9-a2dd-31186a9a89bf.png)

### 3. Fill in the form

(First problem : When you start editing the second field, the value of the first one is copied in the field and the first one is now blank)

### 5. Three translation items have been created (two for the first language and one for the second)

payload of the POST request :
```
{
  "translations": {
    "create": [
      {
        "languages_id": { "code": "fr-FR" },
        "collection_1_id": "+",
        "name": "FrenchName"
      },
      {
        "name": "EnglishName",
        "languages_id": { "code": "en-US" },
        "collection_1_id": "+"
      },
      { "name": "E", "languages_id": { "code": "en-US" } }
    ],
    "update": [],
    "delete": []
  }
}
```

![image](https://user-images.githubusercontent.com/18357403/188928035-d78a64df-73f8-47d9-be1e-4b7c65b0bacd.png)

### Errors Shown

You can get an error (400) if you have not-nullable fields in your translation collection and one of these is null in the "Invisible third element".

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

16.17.0

### What database are you using?

MySQL 8.0.21

### What browser are you using?

Chrome

### How are you deploying Directus?

Self-hosted Openshift cluster (kubernetes)

**Comment by azrikahar** [comment]
This might be a potential regression in `9.17.0`, as it seems to work back in `9.16.1`. 

### 9.17.0 (has this problem)

https://user-images.githubusercontent.com/42867097/189303726-dd8c932c-2293-4cb8-a792-39c63de06d74.mp4

### 9.16.1 (no problem)

https://user-images.githubusercontent.com/42867097/189303649-453f60ca-f115-48ed-b536-1e0ee4791c58.mp4

**Comment by Nitwel** [comment]
Not a regression but a bug that got revealed though another fix I did.

**Comment by fblackburn** [comment]
Any idea when this fix will be released?

**Comment by rijkvanzanten** [comment]
> Any idea when this fix will be released?

We release on a roughly two-week cadence, so within the next couple days 👍🏻
