### ISSUE TITLE
Deselecting related entity doesn't delete it

### ISSUE THREAD

**Issue by adanielyan** [directus/directus#15462]
### Describe the Bug

I have a M2A relationship in one of my collections. In the M2A field Relationship settings I selected ```Delete ***/*** item (cascade)``` option under ```On Deselect of field_name```. However, when I deselect the related item the record is deleted only from the Junction Collection, but not from the related collection. So the related item itself is not deleted.

### To Reproduce

Create 3 collections. 
From the first create a M2A relationship with the other 2
Create an item of a first collection, then from it create 1 or more items of collections 2 and/or 3.
Save the item.
Edit newly created item of collection 1 and deselect the related items of collection 2 and 3.

### Errors Shown

No errors are shown

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

16.16

### What database are you using?

Postgres 14

### What browser are you using?

Edge

### How are you deploying Directus?

AWS EC2 + RDS

**Comment by yacir** [comment]
I'm facing the same issue

**Comment by rijkvanzanten** [comment]
> However, when I deselect the related item the record is deleted only from the Junction Collection, but not from the related collection. So the related item itself is not deleted.

This is expected behavior currently. The relational constraints work just like database CASCADE (and most often use that under the hood), which means that the record holding the foreign key gets cascaded when the linked primary key gets deleted. In m2m / m2a or other deeply nested relational data, that means that only the first junction level gets cascaded to. 

Happy to discuss ideas for improvements in a new feature request 🙂

**Comment by rijkvanzanten** [comment]
> Currently all of the fields in junction collection are locked and cannot be edited. Thoughts?

Junction collections are just regular collections with some auto-generated fields for convenience's sake. They're auto-hidden by default, as they're often times used as an "internal" junction table, but you can just make them visible like you can with any other collection/field 🙂

**Comment by rijkvanzanten** [comment]
> Thank you for clarifying, rijk. Could you please convert this issue to a discussion?

Lets actually just open a new discussion. The title, original post, and the rest of the thread are all discussing the current behavior rather than discussing how it could be improved 🙂

**Comment by adanielyan** [comment]
Unfortunately I cannot save any edits to system generated fields.

https://user-images.githubusercontent.com/861777/189789375-837cb6a7-cd9f-4927-9872-73995c15e3ad.mov

**Comment by adanielyan** [comment]
I created a new discussion here: #15545

**Comment by rijkvanzanten** [comment]
> Unfortunately I cannot save any edits to system generated fields.
> 
>  Screen.Recording.2022-09-12.at.21.45.51.mov

That's odd! Does that happen for every system generated relational field? Is this a many to any `item` field?

**Comment by adanielyan** [comment]
> That's odd! Does that happen for every system generated relational field? Is this a many to any `item` field?

Yes, it is an item field from M2A junction collection. Didn't notice this issue on M2M relations.

**Comment by rijkvanzanten** [comment]
Ahhh that's definitely a bug! It sounds like the editing state of the field drawer there gets "confused" when you're editing the "any to one" field from the m2a junction table. That save shouldn't be blocked (also note how that related collection is blank; that should have the collections in it).

I see that you opened the ability to save those changes as the new feature, so I'll treat that as a new bug report. Lets not stop discussing the "deep relational cascading on delete" though 🙂

**Comment by adanielyan** [comment]
OK, great! Once we have this bug fixed we can try configuring the `Delete ***/*** item (cascade)` in the junction table that should enable the desired behavior.
