### ISSUE TITLE
CORS not longer working

### ISSUE THREAD

**Issue by jroxendal** [directus/directus#1549]
## Version Info

  - Directus version and branch: (Or commit hash)
a47f66d (version/6.4 branch)
  - PHP version: 
  - MySQL version: 
  - Web server: (Ex. Apache, nginx or IIS?) 
  - OS name and version: 
MacOS ElCap

## Expected Behavior
Get CORS headers from the API.

## Actual Behavior
No header: ```Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.```

## Steps to Reproduce
 1. `git checkout a47f66d`
 2. query the 1.1 API and check for Access-Control-Allow-Origin headers

## To get CORS working again:
1. `git checkout 0c988bc` (Fri Jun 2 12:24:23 2017)
2. Headers now present.

**Comment by WellingGuzman** [comment]
Thanks for reporting this, I'm going to take a look and send a patch as soon as possible.

**Comment by WellingGuzman** [comment]
Hey @jroxendal, that patch should fix the issue, you should be able to use CORS now.
