### ISSUE TITLE
`nanoid` breaks hook extension, because it's a pure ES module

### ISSUE THREAD

**Issue by flevi29** [directus/directus#15528]
### Describe the Bug

After upgrading from 9.16.1 to 9.17.4 I am getting an ES module require error.

My extension is transpiled by typescript directly to CJS, maybe the transpiler provided by the SDK would handle this error? Don't really have time to test this right now.

The problem really seems to be that `nanoid` is required somewhere by `extensions-sdk`, whereas it can only be imported. 9.16.1 did not have this `nanoid` module.

### To Reproduce

Create a new CJS project with Directus, add a CJS hook extension to it.

### Errors Shown

```
10:11:45 ⚠️  Couldn't register hook "directus-nestjs-hook"
10:11:45 ⚠️  require() of ES Module C:\Users\user\some_proj\node_modules\@directus\shared\node_modules\nanoid\index.js from C:\Users\user\some_proj\node_modules\@directus\shared\dist\cjs\composables\use-custom-selection.js not supported.
Instead change the require of index.js in C:\Users\user\some_proj\node_modules\@directus\shared\dist\cjs\composables\use-custom-selection.js to a dynamic import() which is available in all CommonJS modules.
```

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

18.9.0

### What database are you using?

Postgres 14.5

### What browser are you using?

Firefox

### How are you deploying Directus?

running locally

**Comment by flevi29** [comment]
As I thought my issue is that I've been using the extension directly, instead of transpiling it and all of it's imports into one file. So I am requiring within my transpiled extension `@directus/extensions-sdk`. So far it worked, but it is not meant to be used that way I guess, so I need to make some changes. I'll adjust my code later and if it works, which it most likely will, I'm closing this issue.

**Comment by rijkvanzanten** [comment]
I haven't been able to reproduce this based on the given information, so I'll this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Comment by flevi29** [comment]
I am building my hook extension with esbuild now, and it works.
I am building a tightly coupled project, NestJS being the main thread, running Directus on a `worker_thread`, communicating with it through `MessagePort`s, which is my main use for the hook extension. I guess I could still use for building the provided `directus-extension build`, but since I am customizing so much, I decided to go all out.

**Comment by flevi29** [comment]
@MichaelFBA I use `esbuild` directly, without invoking anything from `@directus/extensions-sdk` CLI. I'm assuming the extension CLI itself doesn't do very much other than invoking `rollup` with different configurations, at least for hooks. I run a build script like so:
```javascript
import { build } from "esbuild";
import { execaCommand } from "execa";

// this only type checks, because esbuild doesn't
await execaCommand("tsc -p src/extensions/tsconfig.json", { stdio: "inherit" });

await build({
  entryPoints: ["./src/extensions/hooks/directus_nestjs_hook/index.ts"],
  bundle: true,
  outdir: "./dist",
  outbase: "./src",
  platform: "node",
  format: "cjs",
  // Specify imports which should not be bundled into output
  // https://esbuild.github.io/api/#external
  external: [
    "threads/worker",
    "../../../app/modules/prisma/prisma.model",
    "../../../app/util/get_libs",
  ],
  sourcemap: true,
});
```
