### ISSUE TITLE
Translations fields are cloning, deleting and creating wrong translations in Directus 9.17.4

### ISSUE THREAD

**Issue by guillecro** [directus/directus#15538]
### Describe the Bug

There is a weird interaction when creating translations in Directus 9.17.4

I can confirm this doesn't happen in previous Directus version (at least I can confirm in Directus 9.14.1)

So, when you type something in a translation field, say for example inside the translation model of another model (say a field `name` inside the `ingredients_translations` model) it clones the input from one language to another, leaving one input with nothing in it). It also creates a new entry in the translations model.

I made a video that shows the bug in action. This happened while creating a new instance of a model with translations.

https://user-images.githubusercontent.com/8771166/189709783-be582250-3c9a-492b-8849-05b827687e97.mp4

### To Reproduce

Say for example, we have 2 entities, "**Ingredients**" and "**Recipe**"

* Create a `ingredients` model
* In the **Ingredients** model, aside from the default `id`, create a `translations` field.
* Inside `ingredients_translations` model, aside from the default fields (`id`, `ingredients_id`, `language_code`),  create a field `name`

* Now create a new instance of "Ingredients"
* Select to see two languages at the same time. (English in the left, Spanish in the right)
* Enter the name in the english field `name`
* Now enter the name in the spanish field `name`

You'll see the bug in action, copying the field from the english input to the spanish input. The english input will dissapear. Naturally, you delete the whole input in the spanish, and you input the spanish name, then the english name.. the bug won't happen now.. but after you create the translation, check the `ingredients_translations` and you will see 3 rows: 2 are correct (for english and spanish) but there will be a 3rd one with only one letter.

### Errors Shown

I made a video showing the browser console. There is nothing in the docker-compose log.

https://user-images.githubusercontent.com/8771166/189708181-c0729776-770b-4af7-b63a-5ab804fa034e.mp4

**Note in 0:48 that I type another letter (W) and it puts (A) (First letter from the Spanish translation I believe)**

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

Directus Docker Image

### What database are you using?

MySQL 5.7 (Docker image)

### What browser are you using?

Firefox and Chrome

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
@Nitwel mind taking a look?

**Comment by azrikahar** [comment]
@guillecro thanks for the write up, always happy to see detailed & clear bug reports! That said, I believe this is actually the same as #15460 so I'll close this as duplicate. As the linked issue was resolved, this bug will be fixed in the next release 👍
