### ISSUE TITLE
Save & stay and M2O/M2M/O2M relationships

### ISSUE THREAD

**Issue by peremp** [directus/directus#1553]
## Scenario ##
Imagine that you have two tables: _cart_ and _food_.
_cart_ table has an **O2M** relationship with food table.

## Steps to Reproduce
 1. Edit an item from _cart_ (/tables/cart/ID).
 2. Add a _food_ item to the _cart_ using the O2M UI.
 3. Click "Save & stay"
 4. Add another _food_ item to the _cart_.
 5. Click "Save".
 6. Open again the _cart_ item where we added the food.

## Expected behavior
The cart has the items added on step 2 and 4.

## Current behavior
The cart only has the item added on step 2. Item added after "Save & Stay" (step 4) is missing.

This happens with any field that is M2O, M2M, O2M or "Multiple files".
And it always happens after the use of "save and stay".

**Comment by benhaynes** [comment]
Hello @peremp – which version of Directus are you using when you get this bug?

**Comment by peremp** [comment]
6.3.9
