### ISSUE TITLE
Filter search "Is one of" does not separate values on paste

### ISSUE THREAD

**Issue by RemiMatrod** [directus/directus#15532]
### Describe the Bug

When searching items with filters in the content page, pasting a search in an "Is one of" filter does not separate the values between commas.
However, switching to the "Contains" filter then going back to "Is one of" does the separation properly.

Having the value be separated on paste would be very useful when searching for multiple lines at once.

### To Reproduce

1. Open a table in the contents page
![image](https://user-images.githubusercontent.com/85554828/189647182-718e24ae-21a6-48be-b05f-7ee19519abe4.png)
2. Open the filters, add a "Name Is one of" filter, and paste the value `ONE,TWO,"THREE, OK"`
3. No results are sent
![image](https://user-images.githubusercontent.com/85554828/189647890-8182519b-420c-4f01-958b-5621e3c6a3eb.png)
4. Switch from "Is one of" to "Contains", nothing has changed
![image](https://user-images.githubusercontent.com/85554828/189647578-e95a7634-209c-4ae3-948a-7c36645dbb52.png)
5. Switch from "Contains" to "Is one of". Then the separation looks like this:
![image](https://user-images.githubusercontent.com/85554828/189647804-ad5a4880-af33-4f01-bc73-84d22774d50d.png)

As an additional note, the current separation system can also cause problems with strings containing commas, as shown above.

### Errors Shown

There are no errors for text searches. However, this paste issue may cause problems when searching for numbers, like IDs:
![image](https://user-images.githubusercontent.com/85554828/189648455-6dda7b50-8d14-4d72-b482-07cd5d11e61f.png)
This causes a few 500s to show up in the web console and Directus terminal.

Then, after switching filters and going back to "Is one of", the values are separated properly and the search completes, not causing more errors:
![image](https://user-images.githubusercontent.com/85554828/189648789-495f86e0-5173-48c5-ab3b-3bb90aa77e2c.png)

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

16.13.0

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome 105

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
Not really a bug as it's not intended to do that by itself, but certainly a nice enhancement and something we should keep consistent 👍🏻
