### ISSUE TITLE
Translations issue when no other field

### ISSUE THREAD

**Issue by alrick** [directus/directus#15530]
### Describe the Bug

I have some collections that have only one field : translations.
When I create a new entry in that collection, there is an issue happening consistently, the value from some translations is automatically moved to the next language I add, leaving the previous empty, sometimes it's between the first language and the second, sometimes between the second and the third.

[Kazam_screencast_00000.webm](https://user-images.githubusercontent.com/1086355/189621497-97d86374-6dc3-4e37-9845-959b1ea069cd.webm)

### To Reproduce

1. Click the + sign to create a new entry
2. The translations switcher is showed, with the default language selected
3. Enter the translation for the first language
4. Switch to the next language
5. The text entered on the default language is moved to the next language as soon as I start typing in the field
6. If I switch back to the first language, it's empty, sometimes the second language is empty and not the first..

### What version of Directus are you using?

9.17.1

### What version of Node.js are you using?

16.16.0

### What database are you using?

SQLite 3.37.2

### What browser are you using?

Firefox / Brave

### How are you deploying Directus?

CLI installation

**Comment by azrikahar** [comment]
This should be the same as #15460 and there's an open PR #15500 to fix it 👍 Closing this as duplicate, but feel free to subscribe to that issue for further updates.
