### ISSUE TITLE
Warn user if someone else on same page

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1554]
This used to work – not sure when it stopped.

1. User-A goes to Page-1 (Edit Item Detail)
2. User-B goes to Page-1 (same page)
3. Checks to see if any other users are:
    * ONLINE (last_access>NOW-3 minutes)
    * On same page (last_page=this page)
4. If `true`, we show a notification saying: 

`Warning: {{FIRST_NAME}} {{LAST_NAME}} is also editing this page, please coordinate with them to ensure there are no save conflicts.`

**Comment by WellingGuzman** [comment]
This used to work on Directus 5, never on 6.

**Comment by benhaynes** [comment]
Ahh, you're right. We'll it should be an easy one for a new dev to implement :)

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/90089656915e4db5d8ed5cdf7fd008658a5e0191
