### ISSUE TITLE
Unable to add child item with default values from drawer

### ISSUE THREAD

**Issue by licitdev** [directus/directus#15569]
### Describe the Bug

Unable to add child item without saving a different value, and updating it back to the original value.

https://user-images.githubusercontent.com/26413686/190131798-87a7d939-5afd-4d2e-a52b-d6cc85122088.mov

### To Reproduce

Create an O2M relationship, with the child collection having a boolean field defaulting as `false`.

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

v16

### What database are you using?

PG

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
Linear: [ENG-189](https://linear.app/directus/issue/ENG-189/unable-to-add-child-item-with-default-values-from-drawer)
