### ISSUE TITLE
Should be able to search for flow, instead of needing to find uuid

### ISSUE THREAD

**Issue by u12206050** [directus/directus#15584]
### Describe the Bug

Instead of copy and pasting flow id, use the autocomplete interface to search for a flow and insert uuid automatically

### To Reproduce

Create a flow triggering another flow

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

chromium

### How are you deploying Directus?

Locally & GCP

**Comment by izoukhai** [comment]
We could implement this in Notification operations too, instead of pasting users' uuid

**Comment by u12206050** [comment]
Fully agree :)
