### ISSUE TITLE
Re-arranging interfaces throws error

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1559]
## Version Info
  - Directus version and branch: beta @ version/6.4 latest
  - PHP version: 7.10.0

## Expected Behavior
Dragging an interface to change the order in `settings/tables/{tablename}` changes order of interfaces

## Actual Behavior
Directus throws `Server Error Undefined index: column`

## Steps to Reproduce
 1. Head to the settings page of a table
 2. Rearrange the interfaces by dragging with the little drag handle icon

**Comment by rijkvanzanten** [comment]
Not sure if this is related, but the sort column in `directus_columns` has a value of `9999` for all interfaces

**Comment by benhaynes** [comment]
I think that is so any new columns go to the end of the list by default. They should be given an incrementing value from 1 when reordered

**Comment by WellingGuzman** [comment]
Fixed by https://github.com/directus/directus/commit/5cdaf9e93ae8a5e807451a0cc596ee81fd21552b
