### ISSUE TITLE
Insights graphql failing with filter

### ISSUE THREAD

**Issue by u12206050** [directus/directus#15602]
### Describe the Bug

There are a number of things that don't work just right.

1. Assigning value (static or variable) directly to relationship in filter doesn't work
```
{
    "_and": [
        {
            "event": {
                "_eq": "{{event}}"
            }
        }
    ]
}
```
![insights-id](https://user-images.githubusercontent.com/6641242/190496033-80093c73-0f19-4fc7-8da6-cf3c14fcbb19.gif)

2. When using a global variable the id just gets set to blank and just never seems to work
![insights-variable](https://user-images.githubusercontent.com/6641242/190496824-9e0bdfff-e142-44b7-8976-644f3c6bb96f.gif)

3. When using aggregate functions such as count within the filter even though it works via api, over graphql it just fails
```
{
    "_and": [
        {
            "event": {
                "id": {
                    "_eq": "{{event}}"
                }
            }
        },
        {
            "count(activities)": {
                "_eq": "0"
            }
        }
    ]
}
```
![insights-aggregate](https://user-images.githubusercontent.com/6641242/190497358-ded600ac-ce94-45b0-83a1-25e9349bd947.gif)

### To Reproduce

Follow steps as shown in gifs above

### Errors Shown

This is the graphql error being thrown for al three
```
{"errors":[{"message":"GraphQL schema validation error.","extensions":{"code":"INVALID_PAYLOAD","graphqlErrors":[{"message":"Syntax Error: Expected \":\", found \"(\".","locations":[{"line":1,"column":139}]}]}}]}
```

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

chromium

### How are you deploying Directus?

Locally & GCP

**Comment by licitdev** [comment]
### Notes

> When using aggregate functions such as count within the filter even though it works via api, over graphql it just fails

For the 3rd point, the filter should be reformatted to the "GraphQL" format.

```
{count(activities): {_eq: 2}}

👇 

{activities_func: {count: {_eq: 2}}}
```

**Comment by daawaan** [comment]
@licitdev for unknown reasons, it still won't work despite being valid with the SDL. Note that the filter is perfectly valid but this issue only occurs with the `<collection>_aggregated` type in the SDL. The server returns a status code of 200 OK but returns a response similar to the following instead:

```
{
  "errors": [
    {
      "message": "\"<collection>.<relation>_func\" is not a relational field",
      "locations": [
        {
          "line": 2,
          "column": 5
        }
      ],
      "path": [
        "<collection>_aggregated"
      ]
    }
  ],
  "data": null
}
```

**Comment by licitdev** [comment]
@daawaan Kindly provide a minimum reproduction example of the the query / steps leading to the error. It would be great if you can provide screenshots / screen recording. 
Thank you.

**Comment by u12206050** [comment]
Here you go, I tried now with the activities_func but got the same error as @daawaan has above.

![issue_repro](https://user-images.githubusercontent.com/6641242/190623338-e476c15a-59ce-4c2c-992e-55af7f393df2.gif)

**Comment by licitdev** [comment]
@u12206050 Thank you! Your screen recording is crystal clear! 👍 

`"\"<collection>.<relation>_func\" is not a relational field"`
The error is related to https://github.com/directus/directus/issues/12725. In addition, the filter within aggregated GraphQL queries isn't correctly parsed.

Just added a patch to https://github.com/directus/directus/pull/14798 which addresses the API issues. Do give it a try if it's possible. 🙂

**Comment by u12206050** [comment]
After updating to `9.18.1` I get the following error even when just filtering on event, not even aggregating.

```
errors
: 
[{message: "GraphQL validation error.", extensions: {code: "GRAPHQL_VALIDATION_EXCEPTION",…}}]
0
: 
{message: "GraphQL validation error.", extensions: {code: "GRAPHQL_VALIDATION_EXCEPTION",…}}
extensions
: 
{code: "GRAPHQL_VALIDATION_EXCEPTION",…}
code
: 
"GRAPHQL_VALIDATION_EXCEPTION"
graphqlErrors
: 
[{message: "Field "_eq" is not defined by type "events_filter". Did you mean "_or"?",…}]
0
: 
{message: "Field "_eq" is not defined by type "events_filter". Did you mean "_or"?",…}
locations
: 
[{line: 1, column: 97}]
message
: 
"Field \"_eq\" is not defined by type \"events_filter\". Did you mean \"_or\"?"
message
: 
"GraphQL validation error."
```

The query payload was
```
{"query":"query { query_2e50774: registrations_aggregated (limit: 1, sort: \"id\", filter: {_and: [{event: {_eq: \"6ebd2f42-e027-4526-8dc6-961743d358ef\"}}, {status: {_eq: \"new\"}}]}) { count { id } } }"}
```

**Comment by mmmaxxxe** [comment]
same problem here (standard cloud) with global and relational variables with "metrics".

**Comment by mmmaxxxe** [comment]
Any updates on the issue? My insight module is largerly unusable at the moment (filters not working and errors on access)

**Comment by Maloc** [comment]
Any updates on this issue? Hard to work with insight without filters...

**Comment by licitdev** [comment]
A fix is in the works, pending https://github.com/directus/directus/pull/14798, which should be merged soon.

**Comment by viters** [comment]
Workaround is to edit RAW value directly. You can use variables then. Filters will be correctly applied but filters component view will get broken.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-187](https://linear.app/directus/issue/ENG-187/insights-graphql-failing-with-filter)

**Comment by pbischoffcg** [comment]
I'm not understanding the mentioned issues in depth, but I have a very similar problem.

I create a metric with count aggregation. As filter I want only a foreign key to equal a given integer value.
I'm getting the error:
```
{
  "errors": [
    {
      "message": "GraphQL validation error.",
      "extensions": {
        "code": "GRAPHQL_VALIDATION_EXCEPTION",
        "graphqlErrors": [
          {
            "message": "Field \"_eq\" is not defined by type \"activities_filter\". Did you mean \"_or\"?",
            "locations": [
              {
                "line": 1,
                "column": 91
              }
            ]
          }
        ]
      }
    }
  ]
}
```

When I want the primary key "id" to equal a given integer value for filtering, then there is no error.

https://user-images.githubusercontent.com/96301128/213894966-86323078-9553-46e8-ae68-0aa513d4a356.mp4

Thanks for any help.

**Comment by licitdev** [comment]
@pbischoffcg The PR that fixes this issue was merged recently and it will be in the next release. Kindly ensure that you're on the latest release, and open a new issue if the issue persists. Thank you.

**Comment by pbischoffcg** [comment]
> @pbischoffcg The PR that fixes this issue was merged recently and it will be in the next release. Kindly ensure that you're on the latest release, and open a new issue if the issue persists. Thank you.

@licitdev ohh okay so the PR was merged, but is not part of release 9.22.4, but will be in a later release, right?
I tested it on self hosted version 9.22.4 (although my directus ui shows 9.22.3, but I selected latest as docker tag, which should have been 9.22.4)

**Comment by licitdev** [comment]
@pbischoffcg Yes, it'll be in the next release.
For the version display issue, kindly refer to https://github.com/directus/directus/issues/17306#issuecomment-1404711182

**Comment by Maloc** [comment]
Hello, I have just updated to the last version v9.25.1 and I still have this issue when filtering...
