### ISSUE TITLE
Alias interface not working

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1562]
## Version Info
  - Directus version and branch: beta @ version/6.4 latest

## Expected Behavior
Adding an ALIAS interface to a table does.. something

## Actual Behavior
Directus throws an SQL syntax error

## Steps to Reproduce
 1. Change the settings of a table
 2. Add ALIAS interface

## Logs or Screenshots
```
Server Error
Statement could not be executed (42000 - 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALIAS COMMENT "''"' at line 1)
```

_Note: I have absolutely no clue what this interface is even supposed to do. I'm checking all interfaces, so please let me know if it isn't even intended for use in this way_

**Comment by benhaynes** [comment]
We should have an alias DATATYPE... but I don't think we need an alias INTERFACE. Let's remove it and see if any havoc is caused! 🔥

**Comment by WellingGuzman** [comment]
Removed by https://github.com/directus/directus/commit/bfffd64f328b345fb79b381ef1899e232a96efb3
