### ISSUE TITLE
Buttons links won't show inside a group inside an accordion

### ISSUE THREAD

**Issue by Pachat** [directus/directus#15638]
### Describe the Bug

Buttons links won't show inside a group inside an accordion

### To Reproduce

Create a button links : it shows
Now, drag it inside a group that's inside an accordion

### Errors Shown

The button links will not show

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

16.14.0

### What database are you using?

SQLite version 3.37.0

### What browser are you using?

Firefox and Edge

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
Unfortunately I can't seem to reproduce this on my end:

https://user-images.githubusercontent.com/42867097/190970663-69f36845-88f8-45aa-bc4f-151cc138b746.mp4

Can you try whether this is reproducible in a fresh Directus instance?

**Comment by Pachat** [comment]
I confirm it works on a clean installation.
