### ISSUE TITLE
Remove Field in Collection

### ISSUE THREAD

**Issue by Thomas-Blakeney** [directus/directus#15635]
### Describe the Bug

I Can't remove Fields from Collections because there is no Button.

### To Reproduce

Add a Field in a Collection and try to remove it.

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

12.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome, Firefox and Safari

### How are you deploying Directus?

Docker

**Comment by licitdev** [comment]
@Thomas-Blakeney Please update your node to be on the latest LTS version and verify if the issue persists. 
Ref: https://docs.directus.io/self-hosted/quickstart.html#_1-installation
Thank you.
