### ISSUE TITLE
M2M and "Multiple files" fields on item creation

### ISSUE THREAD

**Issue by peremp** [directus/directus#1563]
## Version Info
  - Directus version and branch: 6.3.9

## Steps to Reproduce
 1. Go to any table that has an M2M or Multiple Files field.
 2. Add one or more items to the M2M/MultFiles field using the UI.
 3. Click "Save Item"

## Expected Behavior
The item is created with the items added on step 2.

## Actual Behavior
- A notification with an SQL error appears.
- You are kept in the "Creating new item" form.
- If you go back to the table, you can see that the item is created with its basic information (any field that is not a relationship), but the items added on step 2 does not appear.

This only happens on creation.

## An example:
Table: problems
Table: related_problems

Problems has a M2M field using _related_problems_ as a junction table. When reproducing steps 1, 2, 3 the generated SQL throws the following error:

_UPDATE `problems` SET `id` = '15508', `active` = '1', `slug` = 'live-broadcasting-apps', `title` = 'live broadcasting apps', `description` = '', `created` = '2017-04-26 10:10:20', `updated` = '2017-05-23 07:33:43', `related_problems` = '15508' WHERE `id` = '15508'_

**#1054 - Unknown column 'related_problems' in 'field list'**

Looks like Directus is adding the field used to do the M2M relationship into the query.

**Comment by peremp** [comment]
Looks like it is solved in directus 6.4.0. But still, this is a big issue for the 6.3.9.
If you know the reason or in what commit you solved this for 6.4.0, I could do the fix for the 6.3.9.

**Comment by benhaynes** [comment]
So much changed in 6.4 (code-wise) it may be difficult to find this difference. @peremp – have you been able to find any differences?

**Comment by peremp** [comment]
No sorry :-(!
And tbh my focus is the migration from 6.3.9 to 6.4.0

**Comment by benhaynes** [comment]
That's OK, we appreciate the testing either way! We'll get everything fixed, just might take a little time. Thanks and let us know if you run into any migration issues...

**Comment by benhaynes** [comment]
Can someone test to see if this is still happening on `6.4`?

**Comment by peremp** [comment]
It's not

**Comment by benhaynes** [comment]
Ahh, I should have read your comment above. OK, well we could/should get this fixed for legacy versions, but due to our core team being SO small I think we're going to have to close this since the new release fixes it.

If anyone wants to find the offending code and submit a PR to 6.3.x we will gladly merge it! Otherwise, the official "fix" for this is to upgrade to the latest release (6.4).
