### ISSUE TITLE
Write a comment inside a table (6.4.0)

### ISSUE THREAD

**Issue by peremp** [directus/directus#1564]
## Version Info
  - Directus version and branch: 6.4

## Steps to Reproduce
 1. Go to any table
 2. Click to edit some item.
 3. Try to leave a comment.

## Expected Behavior
 - The comment is added to the item.

## Actual Behavior
 - The error "There seems to be a problem... Messages (New)  Recipients: The field cannot be empty" appears.

The option to specify "recipients" does not exist on that page... and I guess that the comment should be linked to the item you're editing, not to any recipient/user.

**Comment by WellingGuzman** [comment]
Hey @peremp this [patch](https://github.com/directus/directus/commit/5f8ca101e38e2eb81479ad5eb01c6c71d81fbeeb) should fix this issue
