### ISSUE TITLE
Flows: Run script doesn't have access to last node's data

### ISSUE THREAD

**Issue by u12206050** [directus/directus#15653]
### Describe the Bug

I have a "Read Data" operation before a "Run Script" operation, however looking at options and payload, the only data available in the data argument sent to "Run Script" is the `$trigger, $last and $accountability`. The `$last` property seems to be an exact copy of the $trigger.

### To Reproduce

Create a flow that fetches some data after the initial trigger, using "Read Data".
After that add a "Run Script" operation and just return the data argument as is.

Trigger the flow, and view the logs afterward.
Notice the payload on the "Run Script" operation doesn't contain the data form the "Read Data" operation.

### What version of Directus are you using?

9.18.0

### What version of Node.js are you using?

16.4.0

### What database are you using?

sqlite

### What browser are you using?

chromium

### How are you deploying Directus?

locally

**Comment by br41nslug** [comment]
I am unable to reproduce this with a basic flow unfortunately. This is the flow i've used for testing:
![image](https://user-images.githubusercontent.com/9389634/191288260-d64783ee-1dc9-4c57-ab40-7789da3fc6e1.png)
With the following script:
```js
module.exports = async function(data) {
	console.log(data);
	return {};
}
```
This logs me all the operator payloads i'd expect.
```json
{
   "$trigger":{
      "path":"/trigger/c3f0213b-ad01-4eac-89c5-27531f374f89",
      "query":{
         
      },
      "body":{
         "collection":"any",
         "keys":[
            "Array"
         ]
      },
      "method":"POST",
      "headers":{
         "host":"localhost:8055",
         "user-agent":"----",
         "accept":"application/json, text/plain, */*",
         "accept-language":"en-US,en;q=0.5",
         "accept-encoding":"gzip, deflate, br",
         "authorization":"Bearer token",
         "content-type":"application/json",
         "cache-control":"no-store",
         "content-length":"31",
         "origin":"http://localhost:8055",
         "dnt":"1",
         "connection":"keep-alive",
         "referer":"http://localhost:8055/admin/content/any",
         "cookie":"------",
         "sec-fetch-dest":"empty",
         "sec-fetch-mode":"cors",
         "sec-fetch-site":"same-origin"
      }
   },
   "$last":[
      {
         "id":1,
         "toggle":true,
         "files":[
            "Array"
         ]
      },
      {
         "id":2,
         "toggle":false,
         "files":[
            "Array"
         ]
      }
   ],
   "$accountability":{
      "user":"uuid",
      "role":"uuid",
      "admin":true,
      "app":true,
      "ip":"127.0.0.1",
      "userAgent":"----",
      "origin":"http://localhost:8055",
      "share":"undefined",
      "share_scope":"undefined",
      "permissions":[
         
      ]
   },
   "item_read_mbr1i":[
      {
         "id":1,
         "toggle":true,
         "files":[
            "Array"
         ]
      },
      {
         "id":2,
         "toggle":false,
         "files":[
            "Array"
         ]
      }
   ]
}
```

**Comment by br41nslug** [comment]
The operation is receiving the right data but i think you might be running into this situation (but maybe failing silently 🤔 ) https://github.com/directus/directus/issues/15291

**Comment by u12206050** [comment]
@br41nslug not it doesn't seem to be a circular reference issue. 
I can confirm the $trigger property is that of the "main" flow that was first triggered.
I then pass a payload of an array of ids which then call the "child" flow one by one for each id. The value of $trigger is then an ID, which I use in the "Read Data" operation, although the next operation "Run Script" has the data argument it seems of the main flow instead.

**Comment by dimbslmh** [comment]
@br41nslug I am experiencing the same issue as the `OP`. We are using 2 flows, one that ends with `Trigger Flow` and one that starts with `Another Flow`. What you will find in the data prop in `Run Script` is: 

- $trigger: payload of the `Manual` trigger.
- $last: payload of the `Read Data` operation.
- test_a: same as $last.

> ![image](https://user-images.githubusercontent.com/9389634/191288260-d64783ee-1dc9-4c57-ab40-7789da3fc6e1.png)

You can adjust your reproduction to this:
- Create a new flow that is triggered by `Another Flow` and add the `Run Script` there.
- Replace the `Run Script` from your data flow, with `Trigger Flow`.

**Comment by dimbslmh** [comment]
Uhmm.., found out that you can use `{{ $trigger }}` and {{ $last }} in the `Run Script`. You can just add it to a variable.. and skip using data attribute in this case.

**Comment by martinptacek** [comment]
Same issue here. "Run script" step in the flow-triggered flow receives data from the previous flow trigger. There are no previous steps in the "data"
**Trigger flow producing array as an output**
<img width="616" alt="image" src="https://user-images.githubusercontent.com/5970499/194690109-a4bf9580-9d64-47e8-ba82-daaf947ff49f.png">

**Execution flow, executed several times**
<img width="939" alt="image" src="https://user-images.githubusercontent.com/5970499/194690182-466c8cb2-cfcc-4d3f-a2d8-763b99af31b7.png">

**Read data in the second flow**
<img width="654" alt="image" src="https://user-images.githubusercontent.com/5970499/194690305-0453d9ec-f9f2-41f2-9e6f-ea0870bddaa8.png">

**Run script step detail, returning the input**
<img width="728" alt="image" src="https://user-images.githubusercontent.com/5970499/194690193-fea7c9c7-403a-4195-bc86-0280f5d6deaf.png">

**Comment by abernh** [comment]
> Uhmm.., found out that you can use `{{ $trigger }}` and `{{ $last }}` in the `Run Script`. You can just add it to a variable.. and skip using data parameter in this case.

Not only `{{$trigger}}` etc but also all the other operations keys that are currently in the flow object, can be used via the template variables approach, e.g. I had a "read users from db into key `users`" operation and was currently not able to access it via `data.users`. But using the template variable gave me all the values I needed

```js
module.exports = function(data){
  const users = {{users}}
  ....
}
```

**Comment by martinptacek** [comment]
Thanks @abernh . This is the solution!

**Comment by kamalseisy** [comment]
Same behavior in `Condition` operation in a child flow `$trigger` value will be from the parent flow
