### ISSUE TITLE
Dynamic params (id, etc ...) in button links are not working

### ISSUE THREAD

**Issue by sensedrive** [directus/directus#15651]
### Describe the Bug

Dynamic parameters in button links are not working. Weather solo (id) or combined with text (/content/ce_downloads/{id}).

### To Reproduce

1. Create a Button Link
2. Use dynamic params in the URL

<img width="944" alt="grafik" src="https://user-images.githubusercontent.com/8351587/191091158-89f2196b-4070-49f4-9fd5-931680f21c2f.png">

<img width="941" alt="grafik" src="https://user-images.githubusercontent.com/8351587/191091270-9471a638-08b9-406b-a755-79269b30fa93.png">

### Errors Shown

No error shown.

### What version of Directus are you using?

9.18.0

### What version of Node.js are you using?

16.17.0

### What database are you using?

mariadb

### What browser are you using?

Firefox

### How are you deploying Directus?

locally

**Comment by br41nslug** [comment]
I am unable to reproduce this so far with the provided information using either an auto increment or uuid primary key on the latest version.
Except when creating a new item but that's logical as there is no ID for a not yet created item.

**Comment by sensedrive** [comment]
I will try to debug it later, if I get my dev running locally. Currently I have an issue here https://discord.com/channels/725371605378924594/1019994077766357044

The param I try to connect here is a value from a m2m relation.

<img width="1674" alt="grafik" src="https://user-images.githubusercontent.com/8351587/191213915-738ff5a4-7884-40e7-9715-f7ec48e9e3e4.png">

**Comment by br41nslug** [comment]
> combined with text (/content/ce_downloads/{id}).
Based on this part i had just tested with the current items ID not following relations.

Currently the buttons don't support following nested relations unfortunately.
This is tracked here https://github.com/directus/directus/discussions/14886 and https://github.com/directus/directus/issues/8228 .
