### ISSUE TITLE
O2M - Not able to select more than one related item

### ISSUE THREAD

**Issue by krishnam09** [directus/directus#1565]
## Version Info
  - Directus version and branch: 6.3.9
  - PHP version: php 7 (As per getdirectus/directus-base-layer:0.0.8)
  - MySQL version: 5.6.19-67.0
  - Web server: Apache
  - OS name and version: Debian - Jessie  (As per getdirectus/directus-base-layer:0.0.8)

## Expected Behavior
Should be able to add multiple items to a parent table

## Actual Behaviour
Part 1 - https://youtu.be/_apJZ7uH_yI
Part 2 - https://youtu.be/cvpGUrG27yo

*Above youtube links are unlisted.

**Comment by benhaynes** [comment]
Hey @krishnam09 – could you comment on the reason this was closed?

**Comment by krishnam09** [comment]
Was using M2M instead of O2M. My bad! Created junction table, it started working now.
