### ISSUE TITLE
"Created By" and "Last Modified By" on click error (6.4.0)

### ISSUE THREAD

**Issue by peremp** [directus/directus#1566]
## Version Info
  - Directus version and branch: 6.4.0 latest

## Steps to Reproduce
 1. Create an item
 2. Edit the item
 3. Click on "Unknown User" in the "options" menu (the one on the right)

## Expected Behavior
I don't really know.

## Actual Behavior
- Error: Uncaught TypeError: Cannot read property 'table' of undefined
- File: File: http://localhost/directus/app/core/entries/EntriesModel.js?bust=863537bed58a0f7604ca3e2736f9c58757bbb4b3

**Comment by WellingGuzman** [comment]
Hey @peremp, this commit https://github.com/directus/directus/commit/9c24a129216231c79283ce48f7a6a645e805aab5 should've fix this issue.

Let us know.
