### ISSUE TITLE
"offset" doesn't work if "sort" is also specified

### ISSUE THREAD

**Issue by V1210N** [directus/directus#15667]
### Describe the Bug

Querying a collection via GraphQL while specifying both a [sort](https://docs.directus.io/reference/query.html#sort) and an [offset](https://docs.directus.io/reference/query.html#offset) causes the `offset` to be ignored.

### To Reproduce

1. Create a collection with a `date_created` field and fill it with 4 items.
2. Query the collection using the following parameters:
  - `page: 1`
  - `limit: 3`
  - `sort: ["-date_created"]`
3. Now add the offset and verify that it doesn't change the results you're getting:
  - `page: 1`
  - `limit: 3`
  - `sort: ["-date_created"]`
  - `offset: 1`
4. Finally, remove the `sort` argument and verify that it now applies the offset:
  - `page: 1`
  - `limit: 3`
  - `offset: 1`

For what it's worth, this is a close replica of the query I'm running in my application:

```
query {
  posts (limit: 10, offset: 1, page: 1, sort: ["-date_created"], filter: {status:{_eq:"published"}}) {
    id
    title

    categories {
      categories_id {
        id
        name
      }
    }

    featured_image {
      id
    }

    date_created
    date_updated

    user_created {
      first_name
      last_name
    }
  }  
}
```

### What version of Directus are you using?

9.17.4 (Directus Cloud)

### What version of Node.js are you using?

Whichever version Directus Cloud is running now

### What database are you using?

Whichever database Directus Cloud is running now

### What browser are you using?

.

### How are you deploying Directus?

Directus Cloud

**Comment by licitdev** [comment]
@V1210N You should only be using `page` or `offset` and not within the same request, as `page` is an alternative to `offset`. Ref: https://docs.directus.io/reference/query.html#page

`page` could override `offset`.
https://github.com/directus/directus/blob/42fdf00554abcd19dc1d01a5bc289cfbcb758835/api/src/utils/apply-query.ts#L44-L50
