### ISSUE TITLE
Delete on items linked via M2M fails in GraphQL and app

### ISSUE THREAD

**Issue by verystack** [directus/directus#15664]
### Describe the Bug

Our previously working Delete One GraphQL mutation is failing on all roles that should be able to delete it. 
We have a type called 'Post' (with the uppercase 'P').
Roles have been double-checked to make sure they can delete any 'Post' item.

```graphql
mutation DeletePost {
  delete_Post_item(id: 6) {
    id
  }
}
```

It produces this cryptic error:
```js
{
  "errors": [
      {
        "message": "Cannot set properties of undefined (setting 'code')",
        "locations": [
          {
            "line": 7,
            "column": 3
          }
        ],
      }
   ]
}
```

I have the feeling this is a very edge-y case as delete seems to work fine for our other types.

### To Reproduce

Run a delete_one mutation for a singular item.

### Errors Shown

```js
{
  "errors": [
      {
        "message": "Cannot set properties of undefined (setting 'code')",
        "locations": [
          {
            "line": 7,
            "column": 3
          }
        ],
      }
   ]
}
```

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

Cloud

### What database are you using?

Cloud

### What browser are you using?

Chrome

### How are you deploying Directus?

Cloud

**Comment by verystack** [comment]
Bump on this: Found this error in Directus app itself:
```
{
  "errors": [
    {
      "message": "delete from \"Post\" where \"id\" in ($1) - update or delete on table \"Post\" violates foreign key constraint \"Post_Post_related_Post_id_Post_id\" on table \"Post_Post\"",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

**Comment by rijkvanzanten** [comment]
@verystack Why was this closed as completed? Was it misreported?

**Comment by riaddaima** [comment]
@verystack Same thought as @rijkvanzanten please 🙏🏻.
