### ISSUE TITLE
Unable to aggregate bigInteger fields in GraphQL as they are typed as string

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#15663]
### Describe the Bug

I have a dashboard displaying some file-meta data. Therefore I use the "metric" widget with `directus_files` as a collection, `filesize` as field and `sum` as aggregation method. 

It stopped working at an unknown point. I think it's probably related to the refactoring of the Dashboard requests a few versions ago.

Based on Chrome inspector it creates the following query:
`{"query":"query { query_6bbb97b6: files_aggregated (limit: 1, sort: \"id\") { sum { filesize } } }"}`

### To Reproduce

see above

### Errors Shown

```json
{
  "message": "GraphQL validation error.",
  "extensions": {
    "code": "GRAPHQL_VALIDATION_EXCEPTION",
    "graphqlErrors": [
      {
        "message": "Cannot query field \"filesize\" on type \"directus_files_aggregated_fields\".",
        "locations": [
          {
            "line": 1,
            "column": 73
          }
        ],
        "path": [
          "query_6bbb97b6"
        ]
      }
    ]
  }
}
```

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

16.04

### What database are you using?

MySql

### What browser are you using?

16.15.1

### How are you deploying Directus?

-

**Comment by azrikahar** [comment]
Tested on Postgres (but should be true for MySQL as well), seems like `filesize` being a bigInteger field is interpreted as a string in GraphQL. This was intentionally done to fix #12051. However this in turn prevented this use case as GraphQL (correctly) prevents aggregation on string values. 🤔

**Comment by w0kyj** [comment]
Confirming this issue in 9.18.1 and affects insights panels:

<img width="821" alt="Screen Shot 2022-10-06 at 7 09 30 AM" src="https://user-images.githubusercontent.com/40695629/194321256-27fc4c56-2019-41dc-bb3b-8d42108c7330.png">

```json
{"errors":[{"message":"GraphQL validation error.","extensions":{"code":"GRAPHQL_VALIDATION_EXCEPTION","graphqlErrors":[{"message":"Cannot query field \"filesize\" on type \"directus_files_aggregated_fields\".","locations":[{"line":1,"column":73}],"path":["query_5a9da5a5"]}]}}]}
```

**Comment by br41nslug** [comment]
For this to work we might need to look into a solution like this https://github.com/slightlytyler/graphql-type-bigint
As BigInts have a precision of 63bits while graphql limits Int to 32bits

**Comment by iamdagy** [comment]
Im just starting with directus and came into this issue on my very first panel 😅. it would be nice to make a note of this in the insights documentation, or maybe have the big int fields be grayed out in the insight fields selection. at least until a solution is found. Thanks
