### ISSUE TITLE
Standard Cloud instance not supporting SEARCH HTTP method

### ISSUE THREAD

**Issue by colemahatmccreary** [directus/directus#15671]
### Describe the Bug

Search HTTP method doesnt seem to be configured for Cloud.

I have a request that requires a ton of nested/relational data, causing it to exceed the maximum allowed query string length.

To compensate, I'm moving this request away from the SDK and to a plain fetch request, using the SEARCH method as [outlined here](https://docs.directus.io/reference/introduction.html#search-http-method).

Sending the request this way results in a CloudFront error.

### To Reproduce

Query our Standard Cloud instance using the SEARCH method. Parse the incoming response to find the CloudFront error below:

### Errors Shown

The CloudFront error returned by fetch:

> This distribution is not configured to allow the HTTP request method that was used for this request. The distribution supports only cachable requests.
> We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
> <BR clear="all">
> If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
> <BR clear="all">
> <HR noshade size="1px">
> <PRE>
> Generated by cloudfront (CloudFront)
> Request ID: ktNqYxjkYyY68bWalw_fEFpJ8fIiijJL65vQ5MGPuUA5GKjvygFQEA==
> ...

### What version of Directus are you using?

9.17.4 (Standard Cloud)

### What version of Node.js are you using?

Standard Cloud

### What database are you using?

Postgres (Standard Cloud)

### What browser are you using?

Chrome

### How are you deploying Directus?

Standard Cloud

**Comment by azrikahar** [comment]
Seems like this was answered in our Discord server so adding a quote from the response 👍

> SEARCH is currently not support by our provider so it's not possible to use it in our Cloud.
>
> As alternative, you can use Graphql to make great requests. It should only be necessary if you have a URL greater than X characters, where X is the maximum supported characters of your client (for example, for Internet Explorer it is 2048)

Discord message link for above quote: https://discord.com/channels/725371605378924594/932742844806991962/1021845456080355328

---

That said, would also like to add that for inquiries/issues regarding Directus Cloud projects, do kindly reach out through the Live Chat in our Cloud Dashboard as that's the best channel to get assistance with your Cloud projects 😊
