### ISSUE TITLE
Visual inconsistency for tree-view

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#15676]
### Describe the Bug

The tree-view interface has some visual quirks as compared to the other relational interfaces, mainly:

- It uses shadows instead of the bordered row style
- Open/close arrows point the wrong way (closed should be 👉🏻, open should be 👇🏻)
- There's no notice when there aren't any items yet

### To Reproduce

Add a tree-view interface with some content,  note the visual inconsistencies:

<img width="903" alt="CleanShot 2022-09-20 at 16 32 03@2x" src="https://user-images.githubusercontent.com/9141017/191359651-9e7a38cd-0632-4aee-adfd-ce798228a8ef.png">

### Errors Shown

n/a

### What version of Directus are you using?

v9.17.4

### What version of Node.js are you using?

18

### What database are you using?

PG13

### What browser are you using?

Safari

### How are you deploying Directus?

Locally

**Comment by AlexGaillard** [comment]
Hey Rijk, I'd like to go ahead and try this one.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-184](https://linear.app/directus/issue/ENG-184/visual-inconsistency-for-tree-view)
