### ISSUE TITLE
WYSIWYG Full not working on relational edits

### ISSUE THREAD

**Issue by peremp** [directus/directus#1567]
## Version Info
  - Directus version and branch: 6.3.9 and 6.4.0

Imagine that we have a table _solutions_, a table _problems_, and a table _use_cases_ as junction table.
The table _solutions_ has a M2M field called "related problems".

## Steps to Reproduce
 1. Create some random problems.
 1. Create a _solution_, and in the "related problems" field choose some of the existing problems created on step 1.
 2. Save.
 3. Edit the solution and click on any of the related problems added on step 2.
 4. Edit something on the problem
 5. Click "Save".

## Expected Behavior
The problem changes are saved.

## Actual Behavior
The changes are not saved.

## Also
If the _problem_ table have a "WYSIWYG" editor, it is not loaded when accessing to the problem through the solution edition.

**Comment by WellingGuzman** [comment]
Hey @peremp, this was working for me at 6.3.9, can you try to reproduce this issue again?

**Comment by peremp** [comment]
![Image of Yaktocat](http://i.imgur.com/bLQcSnm.jpg)

As you can see in the image, I'm editing an item from a table "solutions". The solution has a M2M field called "Problems".

When I click to a problem from the M2M list, an overlay is opened to edit the problem:

![Image of Yaktocat](http://i.imgur.com/l2grXNe.jpg)

Now, take a look at the field "Description". It should be a WYSIWYG, but it isn't.
Also, as I commented previously, if I make some change to the problem description and then click "save", the description is not saved.

**Comment by rijkvanzanten** [comment]
@WellingGuzman Is that a `wysiwyg_full` interface or a regular `wysiwyg`? The regular one is a Medium-style editor which only shows options on text-select

**Comment by benhaynes** [comment]
@rijkvanzanten Those screenshots are 6.3.x, so this is the legacy WYSIWYG...

**Comment by rijkvanzanten** [comment]
@benhaynes I believe @WellingGuzman's screenshot is from 6.4 (notice the grey background) ☺️

**Comment by peremp** [comment]
Screenshots are from 6.3.9.
But it also happens on 6.4.0 with a regular wysiwyg (Does not shows options on text-select)

**Comment by WellingGuzman** [comment]
@peremp is there any logs in dev tools console?

**Comment by benhaynes** [comment]
@peremp – or you can send us a SQL dump with any private info removed. This is the best way to help us replicate it. Thank you!

**Comment by peremp** [comment]
I'll try to recreate the scenario and send you the SQL.

**Comment by peremp** [comment]
Install directus, then load this SQL: https://drive.google.com/open?id=0B0sF62qJHeE5YWEzWUJSMjJNUmc

Then, do exactly this:
1. Go to problems.
2. Edit "problem 1"
3. Click on the related solution "Solution 2" to edit it through the overlay.
4. select some text on the "Solution > description" textarea to see that the WYSIWYG is not loaded.
5. Change the title to "Solution 2 mod".
6. Save (the solution in the overlay) and save (the problem that we were editing)

The "Solution 2" title is not saved. A warning "Nothing changed, nothing saved" appears.

If you repeat all the steps, then the changes on "Solution 2" are saved. I have seen other casuistic where the item in the overlay is not saved, but I can't reproduce the exact steps.

**Comment by WellingGuzman** [comment]
Where are we on this? I never could reproduce this issue. what browser were you using @peremp? stills happening now on the latest commit from `develop`?

**Comment by benhaynes** [comment]
Hey @peremp – if you have time, could you please check to see if this is still happening for you? We've been updating a lot over the past month so I want to either get this fixed or close it if it's no longer an issue.

Thank you!

**Comment by peremp** [comment]
I had no luck reproducing it. But an editor told me just yesterday that this still happens.
I've been thinking, and maybe is related to the "cache" problem I reported here https://github.com/directus/directus/issues/1708

What I mean is, maybe the changes are saved, but they are not able to see them. But again, not 100% sure. I'll try to find the exact way to reproduce it.

**Comment by WellingGuzman** [comment]
This has been fixed by severals commit.

Reference:
- https://github.com/directus/directus/commit/47275a00b62265774243b38a7b2b3f1977c1badc
- https://github.com/directus/directus/commit/063a55579d96087f5b04d26636c245d317cf1902
- https://github.com/directus/directus/commit/30c06c3ca0b60b779f962d21d3c5e4916e0cb0bb

If someone still experiencing this on `develop` branch please let us know and some steps to reproduce this issue and we will re-open it.

People not using `develop` by the end of the week we are going to release version 6.4.1, with all these fixes.

**Comment by jakub-czyz** [comment]
I am using the latest version 6.4.5 and have the exact problem as described above.
I have a table with items and elements. In the item is a WYSIWYG Full editor and junction to table with elements. If i create or edit a junction element and go back to my item, then is my WYSIWYG editor destroyed.
But that only happens if there is a field with "WYSIWYG Full" in my element.
I have already tried different browsers, but everywhere the same problem.

**Comment by rijkvanzanten** [comment]
At the moment, all core developers are working fulltime on the next major version of the platform, so I'll have to leave this open as a help-wanted. If anyone is inclined to take a swing at fixing this, a PR is very welcome 😄

**Comment by horngperng-pxs** [comment]
i believe what ur editor do it, he/she edit the interface of m2o relation's WYSIWYG FULL and press save directly. i think the correct step is, edit the interface of m2o relation's WYSIWYG FULL and blur out from the interface first before u press save (click any whitespace beside the interface/field to be precise), then u can save/submit. Please let me know if its work

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/6)
