### ISSUE TITLE
Allow removing a link in WYSIWYG when clearing the URL input

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/directus#15670]
### Describe the Bug

1. Set a Link in TinyMCE Interface and click save
2. Open the dialog of the link again and clear the URL input
3. The save button is then disabled

I checked the TinyMCE Full example on their website, there you can clear the URL input and save, and the link is gone from the editor.

### To Reproduce

1. Set a Link in TinyMCE Interface and click save
2. Open the dialog of the link again and clear the URL input
3. The save button is then disabled

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

v14.19.3

### What database are you using?

MySQL 8

### What browser are you using?

Chrome

### How are you deploying Directus?

Linux VPS

**Comment by azrikahar** [comment]
I think it's very important to note that although the WYSIWYG interface does indeed use TinyMCE under the hood, there are quite a number of customized implementations so we can't exactly impose expectations from TinyMCE usages to transfer 1:1 in the current interface. A slightly recent example would be #14643.

With that said, I don't see any harm in supporting this interaction, so keeping this to track it as an improvement 👍
