### ISSUE TITLE
Cannot filter when adding items through M2M/O2M UI (6.4.0)

### ISSUE THREAD

**Issue by peremp** [directus/directus#1568]
## Version Info
  - Directus version and branch: 6.4.0

## Steps to Reproduce
 1. Edit an item that has a M2M/O2M field.
 2. Click on "choose existing"

## Expected Behavior
A list of items appear with the filter form in the header.

## Actual Behavior
A list of items appears without the filter form. 
Also if you had an active filter for that table, the list is filtered by that and you cannot remove the filter.

**Comment by WellingGuzman** [comment]
Hey @peremp, can you explain a little bit more the sentence below?
> Also if you had an active filter for that table, the list is filtered by that and you cannot remove the filter.

**Comment by WellingGuzman** [comment]
I figured it out what you meant by the filters.
By default the listing will have the table filtering, but changing this won't reflect the table filters.

**Comment by peremp** [comment]
perfect :+1:
