### ISSUE TITLE
FIlter `_icontains` is missing in GraphQL

### ISSUE THREAD

**Issue by danielband** [directus/directus#15699]
### Describe the Bug

I would like to filter fields in relation by using a case insensitive filter. Doing so results in a error message.

**icontains is not included in string_filter_operators**

The SDL shows:
```
input string_filter_operators {
  _eq: String
  _neq: String
  _contains: String
  _ncontains: String
  _starts_with: String
  _nstarts_with: String
  _ends_with: String
  _nends_with: String
  _in: [String]
  _nin: [String]
  _null: Boolean
  _nnull: Boolean
  _empty: Boolean
  _nempty: Boolean
}
```

### To Reproduce

1. Setup a Collection with a String or Text field
2. Try to filter by using _icontains 

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

16.5

### What database are you using?

Postgres 13

### What browser are you using?

Firefox Developer

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
Ref https://github.com/directus/directus/issues/13782#issuecomment-1149916025 (these may or may not be up-to-date now, but the first item here is the same as OP's report)

> There seems to be additional discrepancies such as:
>
> - GraphQL `StringFilterOperators` is missing `icontains`
> - GraphQL `DateFilterOperators` is missing `in`, `nin`
> - GraphQL `GeometryFilterOperators` has `_eq` and `_neq`, but `getFilterOperatorsForType` does not have them. `getFilterOperatorsForType` have `null` and `nnull` instead.
> - `getFilterOperatorsForType`'s date/time/dateTime seems to have additional duplicated `null` and `nnull`

**Comment by freekrai** [comment]
I'm already in this thought space so can take this, seems mostly a matter of being consistent.
