### ISSUE TITLE
You don't have permission to access this

### ISSUE THREAD

**Issue by devTheodul** [directus/directus#15698]
### Describe the Bug

# Access to Rest endpoint forbidden

I am trying to setup a new Directus deployment for development and testing. I was following the [guide here](https://docs.directus.io/self-hosted/quickstart.html).

However when I get to [Step 7 - Connect to the API](https://docs.directus.io/self-hosted/quickstart.html#_7-connect-to-the-api), all requests are declined.

I thought maybe it's a local environment and spun up a  [dev server on Directus Cloud](https://z66ogfjz.directus.app/) with the demo data option but I'm still getting the same error.

### To Reproduce

# Steps to reproduce

1. Follow the steps in the setup guide - https://docs.directus.io/self-hosted/quickstart.html
2. Attempt to access an item via the API through the browser or via Postman.
3. All requests return 403.

### Errors Shown

The Browser Console shows the 403 Error.

The related terminal log entry is

```
00:00:00 1 Ô£¿ request completed GET 403 /items/articles 13ms
```

The response generated in the browser and response body is:

```
{
    "errors": [
        {
            "message": "You don't have permission to access this.",
            "extensions": {
                "code": "FORBIDDEN"
            }
        }
    ]
}
```

### What version of Directus are you using?

9.18.0

### What version of Node.js are you using?

16.16.0

### What database are you using?

SQLite that came with Install

### What browser are you using?

Chrome

### How are you deploying Directus?

Running locally

**Comment by azrikahar** [comment]
When you were following [step 3](https://docs.directus.io/self-hosted/quickstart.html#_3-create-a-collection) to create the `articles` collection, did you perhaps type `Articles` (capital letter)? Can you try `/items/Articles` as an additional confirmation?

And just to be certain, you have granted Read permission for the articles/Articles collection you have created to the Public Role in [step 6](https://docs.directus.io/self-hosted/quickstart.html#_6-set-role-public-permissions) right?

**Comment by devTheodul** [comment]
Hi @azrikahar.

In step 3, I can confirm it's Articles. Upon further investigation, I realized that an antivirus extension on my Machine (HP Wolf Security) was rewriting the URLs and changing it back to `articles` hence the error. 

If I disable the security service, I am able to access the API and the requests are fulfilled.

Since this is not related to Directus, but rather a third party, I'll close this issue.

P. S, Yes, I had granted `read` permissions for the collection. Everything seems to work now. 

Switching over development to Mac

**Comment by azrikahar** [comment]
> In step 3, I can confirm it's Articles. Upon further investigation, I realized that an antivirus extension on my Machine (HP Wolf Security) was rewriting the URLs and changing it back to `articles` hence the error. 

Wow that's an interesting scenario! if anything, that's another thing to keep in mind whenever there's similar reports, so thanks for sharing 😄 Glad everything's resolved.
