### ISSUE TITLE
Getting 403 while accessing the image 

### ISSUE THREAD

**Issue by Zuhal-Ayob** [directus/directus#15696]
### Describe the Bug

403 

{"errors":[{"message":"You don't have permission to access this.","extensions":{"code":"FORBIDDEN"}}]}

### To Reproduce

getting 403 while accessing the image , it happened after updating directus to the most recent version

### Errors Shown

{"errors":[{"message":"You don't have permission to access this.","extensions":{"code":"FORBIDDEN"}}]}

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

16.17.0

### What database are you using?

Postgres 10

### What browser are you using?

Chrome

### How are you deploying Directus?

PaaS

**Comment by azrikahar** [comment]
There doesn't seem to be much info we can work with here, would you mind answering the following questions?

- What version were you updating _from_?
- By `PaaS` deployment, how are the assets stored? What is the storage location currently in use?
- Have you grant the necessary permissions to `directus_files`? What role are you accessing this image with?
- Can you share assets endpoint you have tried (eg. `/assets/c2e81a3f-4005-4ce3-8671-154d40ff197a`) or just the UUID of the image?

**Comment by br41nslug** [comment]
Closing this issue for now until more information is available

**Comment by Zuhal-Ayob** [comment]
> There doesn't seem to be much info we can work with here, would you mind answering the following questions?
> 
> * What version were you updating _from_?
> * By `PaaS` deployment, how are the assets stored? What is the storage location currently in use?
> * Have you grant the necessary permissions to `directus_files`? What role are you accessing this image with?
> * Can you share assets endpoint you have tried (eg. `/assets/c2e81a3f-4005-4ce3-8671-154d40ff197a`) or just the UUID of the image?

>* I updated from `9.0.0-rc.101` , it was working with that version, after that, I haver tried several newer version which is not working.
>*  Directus is hosted on Gov PaaS,  backed by Postgres, Redis, and S3. we are storing the videos on Vimeo (videos are accessible ) and the images in the Directus.
>* yeah, it was working fine, it happened after updating the version of the Directus, I am accessing the images with the administrator user .
>* This is the endpoint `https://sfccmstest.cloudapps.digital/assets/8cc4f9b1-9867-498f-875c-8a0e5f55f401`
