### ISSUE TITLE
Initial /fields call way too slow

### ISSUE THREAD

**Issue by lluishi93** [directus/directus#15702]
### Describe the Bug

The initial /fields call that Directus app makes is way too slow in our system. It is probably due to having a lot of fields, I can understand that. But this should not be the cause for poor performance. IMHO, there should be a better way to load this information after the login.

### To Reproduce

The only way I can think of reproducing this is loading a lot of collections with a lot of fields in the database. I can provide you the database backup as well.

### Errors Shown

![image](https://user-images.githubusercontent.com/14786440/191725815-b0704303-de56-4a1f-96f6-7b4c07d06936.png)

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

16.14.0

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by br41nslug** [comment]
Perhaps we can limit this to only the core table fields on initial load and hydrate the user-defined fields on-demand

**Comment by lluishi93** [comment]
> Perhaps we can limit this to only the core table fields on initial load and hydrate the user-defined fields on-demand

that would be ideal IMHO

**Comment by rijkvanzanten** [comment]
I'll close this for now, as a "improve overall performance of endpoint X" is not really an actionable item beyond an ongoing effort to improve the overall performance. If there's any specific bottlenecks that are identified, we can resolve those as individual issues 🙂

**Comment by lluishi93** [comment]
> I'll close this for now, as a "improve overall performance of endpoint X" is not really an actionable item beyond an ongoing effort to improve the overall performance. If there's any specific bottlenecks that are identified, we can resolve those as individual issues 🙂

I think I don't understand your point. The bottleneck is that when there's a lot of fields because the project has been ongoing for several years now, Directus gets stuck because it has to wait for all the fields to load previously. This causes poor user experience and sometimes (depending on infra configuration) timeouts. IMHO, this is a quite important issue to address, I think there should be a better way to retrieve that information (on demand, for instance). But that's just my opinion.

**Comment by br41nslug** [comment]
> I'll close this for now, as a "improve overall performance of endpoint X" is not really an actionable item
IMO this issue is not about the performance of `/fields?limit=-1` itself that will always be slow with enough fields.
> If there's any specific bottlenecks that are identified
The specific bottleneck here is that the app waits for this `/fields?limit=-1` call delaying the initial load by seconds for data models with large tables

**Comment by lluishi93** [comment]
> > I'll close this for now, as a "improve overall performance of endpoint X" is not really an actionable item
> 
> IMO this issue is not about the performance of `/fields?limit=-1` itself that will always be slow with enough fields.
> 
> > If there's any specific bottlenecks that are identified
> 
> The specific bottleneck here is that the app waits for this `/fields?limit=-1` call delaying the initial load by seconds for data models with large tables

That's it. I don't think this issue should be close, as having to wait like 10 seconds for the APP to load is an expected behaviour, independently of the amount of fields that Directus can have.
