### ISSUE TITLE
How to create custom extension

### ISSUE THREAD

**Issue by hiranya-sarma** [directus/directus#1571]
**Version Info**

Directus version and branch: 6.3.9
PHP version: 5.5.9
MySQL version: 5.5.53
Web server: Apache
OS name and version: Ubuntu 14.10 LTS

**Problem:**
Can you provide step by step guide how to create custom extension,looks like documentation is incomplete.

Also not able to find any core extensions.

**Comment by rijkvanzanten** [comment]
Hi all! I wrote a little article on how to get started with custom extensions! Let me know if this helps you out 😊

https://medium.com/directus/how-to-setup-a-custom-extension-770d6ea48551

**Comment by benhaynes** [comment]
Having read this awesome article, I'm confident it answers all/most questions on setting up Custom Extensions. I'll close this unless there are other, more specific, questions.

Thanks @rijkvanzanten!!
