### ISSUE TITLE
M2M field: Cannot save when using "Add new item" button (6.4.0)

### ISSUE THREAD

**Issue by peremp** [directus/directus#1573]
Directus version: 6.4.0 commit d4014f0
This can't be reproduced on last commit e98001a because of this: https://github.com/directus/directus/issues/1572

## Steps to Reproduce
 1. Edit some item that has an M2M field.
 2. Click on "Add new item".
 3. (overlay) Create the item and click "save"
 4. The new item appears on the M2M list.
 5. Click "save"

**Expected:**
The item is saved correctly.
The item created on step 3 is created.

**Current:**
Server Error: Undefined index data. Nothing is saved or created.

**Comment by WellingGuzman** [comment]
Fixed by 281c763ade97153796512b1ab3f02013761e8154
