### ISSUE TITLE
Files thumbnails are not showing in files interface

### ISSUE THREAD

**Issue by d1rOn** [directus/directus#15735]
### Describe the Bug

Files thumbnails are not showing in files interface.

![image](https://user-images.githubusercontent.com/26179694/192111973-7ba9953c-f988-43f7-b1dd-8557facb2dce.png)

### To Reproduce

1. Create a collection A.
2. Create field B that is Multiple Files (m2m).
3. Select the Files interface.
4. Go to Content module and try to add some files into B field. Click Save.
5. You can see that thumbnails are not rendering.

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

v17.9.0

### What database are you using?

SQLite 3

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally

**Comment by brandnewx** [comment]
It's broken since 9.17.0

**Comment by Rar9** [comment]
+ 1 Let's hope the fix is applied with next update.

**Comment by RaphaelBP** [comment]
this bug is really blocking :(

**Comment by brandnewx** [comment]
@azrikahar, could you review the pull request? This is really a big issue for everyone with the Files.
