### ISSUE TITLE
Sort on translations not work properly

### ISSUE THREAD

**Issue by fprencipe3** [directus/directus#15759]
### Describe the Bug

Considering a collection linked to another collection with one field as translation.
Each collection contains two elements.
Each element in collection with translations contains two translations.

Filtering items in first collection by translations, Directus returns 4 elements instead of two.

### To Reproduce

- create a collection  test_type with schema schema_test_type.json in zip attachments
- create a collection test_sort with schema schema_test_sort.json in zip attachments
- create a translation collection with schema schema_test_type_translation in zip attchaments

[schemas.zip](https://github.com/directus/directus/files/9647312/schemas.zip)

with the following curl Directus returns 4 elements instead of 2

`curl --location --request GET 'http://localhost:8055/items/test_sort?fields=type.translations.name&sort=type.translations.name' \
--header 'Accept: application/json, text/plain, */*' \
--header 'Accept-Language: it-IT,it;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkZTg5NzkyLTUyZDItNGNiOS05OThjLWNmMDM5Y2U2MzVhYSIsInJvbGUiOiI5N2IxNzQyNy1kZTU0LTRjMWYtYjQyNS03MmY1MjhhYWQwYjAiLCJhcHBfYWNjZXNzIjp0cnVlLCJhZG1pbl9hY2Nlc3MiOnRydWUsImlhdCI6MTY2NDE4MTA3OSwiZXhwIjoxNjY0Nzg1ODc5LCJpc3MiOiJkaXJlY3R1cyJ9.Q4V_6rGfbwSWl4xDbgmk-jZVeTH6gS-CxYl08kYJfIY' \
--header 'Cache-Control: no-store' \
--header 'Connection: keep-alive' \
--header 'Cookie: directus_refresh_token=H5Yd9W43djKEQ2r4K-FKkiKCq_afs2if1TiV2h7rFxsTCsfrjFN4Prl4ot9IOgxS' \
--header 'If-None-Match: W/"b-EFAlOux7Kcr/ZEgGkn2r+oFAbu4"' \
--header 'Referer: http://localhost:8055/admin/content/test_type/e0fe6fd4-7170-4518-bcbd-d7aa6fd2199d' \
--header 'Sec-Fetch-Dest: empty' \
--header 'Sec-Fetch-Mode: cors' \
--header 'Sec-Fetch-Site: same-origin' \
--header 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.50' \
--header 'sec-ch-ua: "Microsoft Edge";v="105", " Not;A Brand";v="99", "Chromium";v="105"' \
--header 'sec-ch-ua-mobile: ?0' \
--header 'sec-ch-ua-platform: "macOS"'`

### Errors Shown

In the following screen is possible to see the four elements

<img width="1214" alt="Schermata 2022-09-26 alle 16 57 58" src="https://user-images.githubusercontent.com/19491420/192310865-fa872fe3-56f2-43a2-b3e4-d3953961c9fd.png">

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.14.2

### What database are you using?

Postgres 13

### What browser are you using?

Edge

### How are you deploying Directus?

Docker

**Comment by br41nslug** [comment]
In the request you're doing here you are requesting `fields=type.translations.name&sort=type.translations.name` where the specified fields mean you're querying the nested names of translations so i believe the resulting data you're getting back here are the 4 translation names you've created in 2 collections with 2 translations:
> Each collection contains two elements.
> Each element in collection with translations contains two translations.

Closing this issue for now until more information is available

**Comment by fprencipe3** [comment]
Hi @br41nslug,
Even removing the fields parameter, Directus returns 4 elements:

<img width="1256" alt="Schermata 2022-09-27 alle 08 54 39" src="https://user-images.githubusercontent.com/19491420/192454655-0e7212e3-91b8-406e-bc68-8ec6f034d8a4.png">

Removing the sort parameters, the elements returned are two.
<img width="1256" alt="Schermata 2022-09-27 alle 08 54 50" src="https://user-images.githubusercontent.com/19491420/192454909-de3c0ca5-0249-4f19-a595-9c482b4168e5.png">

**Comment by azrikahar** [comment]
@fprencipe3 I believe this was noticed and being accounted for in #14798. Although the PR initially focused on filters hence the title, we can see the latest commit https://github.com/directus/directus/pull/14798/commits/416b7ed9541673563aa301faf9010031225cf9be is meant to fix duplicate results in relational sort. cc @licitdev just in case 👍
