### ISSUE TITLE
A user should not be allowed to deselect its role

### ISSUE THREAD

**Issue by Pachat** [directus/directus#15761]
### Describe the Bug

Users can deselect their role.

As we cannot act on this Directus field,, by default, the `Deselect X` should not show on the role field of the user's form.

### To Reproduce

1. On the current user form, deselect the role
2. Save

### Errors Shown

You are not allowed to access this App (of course, no more role to allow access).

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.14.0

### What database are you using?

PostgreSQL 14.2

### What browser are you using?

Firefox and Edge

### How are you deploying Directus?

locally

**Comment by Pachat** [comment]
A side effect is related here  #15767

**Comment by freekrai** [comment]
Can confirm this can happen, even the admin user can deselect their role.

**Comment by Pachat** [comment]
That's exactly what happens (as a try) and i had then to tinker directly the DB to set the role again and recover access.

**Comment by u12206050** [comment]
This is the edit validation rule I have on `directus_users` 
```
{
	"_and": [
		{
			"role": {
				"_in": [
					"$CURRENT_USER.roles.role"
				]
			}
		}
	]
}
```

I added an additional field called roles, which is a many to many between the users and `directus_roles` which only I as the Administrator can set.

This allows users to select any of the other roles that I have added to their user profile.
To limit exposer, I have also added that they can only view roles which they have in `roles` or as set in `role` field.

**Comment by Pachat** [comment]
Until this is resolved, I hide the `X` Deselect by CSS in the Project Settings:
```
#main-content.content main div.user-item div.v-form.grid div.field.half-right div.interface div.many-to-one div.v-input.full-width.has-click div.input div.append span.v-icon.deselect  {
    display: none;
}    
```
hoping it will not have unwanted side effects.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-180](https://linear.app/directus/issue/ENG-180/a-user-should-not-be-allowed-to-deselect-its-role)
