### ISSUE TITLE
Relational item can't be created if the fields are all intact

### ISSUE THREAD

**Issue by d1rOn** [directus/directus#15765]
### Describe the Bug

Assume we have collection with fields that are all not required and has the default values.

In this case we can't create an item with no any edits (Save button is not active).
In case of our collection is used in relation, we can press Save button, but it's not take effect — the item will not created.

https://user-images.githubusercontent.com/26179694/192361321-af4cef7c-3b30-4958-8ca0-0a42f3052b5c.mp4

### To Reproduce

1. Create collection `B` with field `toggle` (Toggle interface, default to false; Boolean display).
2. Create collection `A` with field `relation` (O2M to `B`; Display template `{{ toggle }}`)).
3. Try to create a new `A` item.
4. Press **Create New** button, leave form untouched, press **Save**.
5. You can see that item display template is not rendered.

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

v17.9.0

### What database are you using?

SQLite 3

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally

**Comment by br41nslug** [comment]
This should be the same problem as https://github.com/directus/directus/issues/15569
