### ISSUE TITLE
Huge files upload fails during/after completion

### ISSUE THREAD

**Issue by domdus** [directus/directus#15769]
### Describe the Bug

I can not tell if this is directly related to directus or node or env maybe. Feel free to sort out things here.

When uploading huge files (< 10G) the upload completes at 100% (UI) and it seems the client completes the transmission successfully. (watching network load)

There is no timeout or any limit on our env (NGINX set client_max_body_size = 0). File uploads would run forever till completed.
This is about after the upload completed - something keeps the node process very busy for some time. (file moved? / copied?  / any IO?)
![image1](https://user-images.githubusercontent.com/67951828/192506241-472fa749-ccdc-4b58-86e9-398de3b0707e.png)

After exactly 2 (!) minutes the process stops/fails resulting in a HTTP 504 response to the client (app):
`"<html><body><h1>504 Gateway Time-out</h1>\nThe server didn't respond in time.\n</body></html>\n\n"`

At this point you don't see anything of this in the directus logs, nor on NGINX side.
POST request:
![image2](https://user-images.githubusercontent.com/67951828/192507923-5f134e9b-ec2b-4b77-8167-a24d83debcb0.png)

Directus creates the empty meta file still:
<img width="111" alt="image" src="https://user-images.githubusercontent.com/67951828/192515247-d712219f-1845-4149-9c90-23036c534143.png">
<img width="427" alt="image" src="https://user-images.githubusercontent.com/67951828/192515294-51621032-18c1-4c85-b1b1-e60fc172ab6d.png">

I found info about a default timeout of `120000ms` for node http, but it was removed in node v13.0.0:
https://stackoverflow.com/questions/23874954/is-there-a-default-timeout-in-node-js-for-http-request
https://nodejs.org/api/http.html#servertimeout
It would have perfectly matched the issue.

In the end I also tried to play with directus server config options (https://docs.directus.io/self-hosted/config-options.html#server), but no success.

SERVER_REQUEST_TIMEOUT=0
SERVER_TIMEOUT=0
SERVER_KEEP_ALIVE_TIMEOUT=10000

-----------------------------------------------------------------

Attempt to use the api with same result:
<img width="779" alt="image" src="https://user-images.githubusercontent.com/67951828/192514994-85123bbf-3997-448d-b9e4-09737a1fbd25.png">

------------------------------------------------------------------

Host Specs:
AMD EPYC™ 7702
64 GB DDR4 RAM (ECC)
14 Cores
2 TB SSD

-------------------------------------------------------------------

### To Reproduce

- Make sure your env is capable of accepting huge file uploads, no timeouts, client_max_body_size=0 (NGINX)
- Grab 10G file or create (dd if=/dev/zero of=10g.img bs=1 count=0 seek=10G) to upload to directus file lib
- Wait until upload completes at 100% (client traffic lowers/stops)
- Watch directus host processes (top) => node being busy for exactly 2 minutes before stop
- Directus app responds error `"<html><body><h1>504 Gateway Time-out</h1>\nThe server didn't respond in time.\n</body></html>\n\n"`
Client POST "wait" -> time-to-first-byte (TTFB) is exactly the 2 minutes (screenshot above)

### Errors Shown

`"<html><body><h1>504 Gateway Time-out</h1>\nThe server didn't respond in time.\n</body></html>\n\n"`

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

16.14.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

PaaS

**Comment by emrahnazif** [comment]
I tested this with v9.13.0, everything (upload&download) worked smooth for me. 
1 test with 10gb file. 
1 test with 48gb file. 

In your case, did you verify if the file is actually uploaded in to the storage location?

**Comment by domdus** [comment]
Hi @emrahnazif,

thx for testing it. I've just figured it out. 
The primary cause is our env setup with NGINX, so I will close the issue now.

**For the record**
We have a central `NGINX` host (proxy vhosts) --`VLAN`--> `directus` hosts.
NGINX is not running on same host as directus.

By default NGINX buffers upload requests and the whole file - it does not instantly write it to destination storage.
First after the upload is completed (100%), NGINX offloads the buffered file and starts writing to the storage location on directus host.
In our case, transfer & write of< 10G files via VLAN takes longer than the 2 minutes (unknown threshold mentioned on top) and the transfer gets cut off.
Reason unclear, but something does not like this taking longer.

To fix it, the NGINX buffering behavior needs to be changed - one of the following settings is relevant:

proxy_buffering off;
proxy_no_cache 1;
proxy_request_buffering off;

With that - file uploads are immediately written to disk on directus host - no "post upload" IO is happening and big file uploads work fine.

I will give an update on which of the 3 settings exactly does the trick.
