### ISSUE TITLE
Editing a file throws an error

### ISSUE THREAD

**Issue by wittwerch** [directus/directus#1577]
## Version Info
  - Directus version and branch: 0aefd193d0316eca87412dd3c15ec113e9c1b281
  - PHP version: 7.1
  - MySQL version: 5.7
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: Docker

## Actual Behavior
Browsing an image throws an error.

Clicking on "Delete": nothing happens, no error
Clicking on "Save": error message => "Data: The field cannot be empty"

## Steps to Reproduce
 1. Upload an image
 2. Navigate to it

## Logs or Screenshots
![screen shot 2017-06-15 at 09 29 40](https://user-images.githubusercontent.com/1575445/27170194-59639ae8-51ad-11e7-8dd5-0a27bea78704.png)

**Comment by WellingGuzman** [comment]
Hey @wittwerch, also I'm curious about that error below in the screenshot? what did you click that it throws that error?

**Comment by wittwerch** [comment]
The error appeared once I navigate to the detail view: http://127.0.0.1:8020/files/1
Now upgraded to b38906b9de9b6916888938e262acf12ee7649888 and error doesn't appear anymore.

However clicking on "Save" still throws an error: "Data: The field cannot be empty".
