### ISSUE TITLE
Unable to add M2O relation to unsigned bigint PK

### ISSUE THREAD

**Issue by gisostallenberg** [directus/directus#15785]
### Describe the Bug
```
{
  "errors": [
    {
      "message": "alter table `my_table` add constraint `my_table_test_id_foreign` foreign key (`test_id`) references `my_other_table` (`id`) on delete SET NULL - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'test_id' and referenced column 'id' in foreign key constraint 'my_table_test_id_foreign' are incompatible.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### To Reproduce

Create a table with a unsigned bigint PK (as Laravel creates it PK's by default) and another table.
Use Create Field in Advanced Mode on the other table and choose M2O relationship.
After selecting the table with the unsigned bigint as PK in 'Related Collection' save the field.
You'll get the above error, even though the dialog states "Determined by Relationship" under Schema -> Field type.

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

N/A

### What database are you using?

MySQL 8

### What browser are you using?

N/A

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Should be the same root cause as #7808, which seems to match the finding here: https://github.com/directus/directus/issues/7808#issuecomment-1166785934. Let's track this in the same issue 👍

**Comment by gisostallenberg** [comment]
Thanks @azrikahar for your quick response. Any clue on why https://github.com/directus/directus/pull/14128 is marked as Draft?

**Comment by azrikahar** [comment]
> Thanks @azrikahar for your quick response. Any clue on why #14128 is marked as Draft?

Welcome! It's because it doesn't 100% resolves it (at least with the current findings), though subsequent changes works. More info in the two comments here: https://github.com/directus/directus/pull/14128#issuecomment-1167341090
