### ISSUE TITLE
Presets do not apply on junction collections

### ISSUE THREAD

**Issue by Pachat** [directus/directus#15781]
### Describe the Bug

On selection of an M2O, the list just shows the bullets and not the expected columns of the Preset
(It is possible to add fields with + to see the values, but this presentation is not kept after saving the item)

### To Reproduce

1. Set an M2M relation between two collections.
2. Set an M2O relation between the same parent collection and the junction collection created in 1. 
3. Set a preset on the junction collection.
4. Create items in the collections
5. Update an item on the parent collection to open the lookup

_If anything particular to Directus collections, 
my M2M is  `directus_users <=> directus_roles` and M2O `directus_users <- junction_directus_users_directus_roles`_

### Errors Shown

The lookup of the junction collection shows only the bullets.

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.14.0

### What database are you using?

PostgreSQL 14.2

### What browser are you using?

Firefox and Edge

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻
