### ISSUE TITLE
We should be able to set the 'loading' field in images with WYSIWYG editor

### ISSUE THREAD

**Issue by izoukhai** [directus/directus#15790]
### Describe the Bug

Not really a bug but a missing feature / improvement. 

`<img>` tags support a 'loading' field which defines if it should be lazy loaded or not. It's quite useful for performance in blog websites with long articles with multiple images.

### To Reproduce

Add an image with the wysiwyg editor, you can't set the loading field

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

LTS

### What database are you using?

Postgres 13

### What browser are you using?

irrelevant

### How are you deploying Directus?

irrelevant

**Comment by rijkvanzanten** [comment]
Linear: [ENG-176](https://linear.app/directus/issue/ENG-176/we-should-be-able-to-set-the-loading-field-in-images-with-wysiwyg)
