### ISSUE TITLE
Disabled "Clear value" option in M2M

### ISSUE THREAD

**Issue by lluishi93** [directus/directus#15804]
### Describe the Bug

The clear value option is not enabled for M2M fields.

### To Reproduce

- Create collection A
- Create collection B
- Add a m2m field to collection A pointing to collection B
- Add some items to the relation and save
- Enter the item and try to clear value

### Errors Shown

![image](https://user-images.githubusercontent.com/14786440/193013118-f244a6c3-708e-410e-a393-82a96515d280.png)

### What version of Directus are you using?

9.18.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by Nitwel** [comment]
This is not a bug but intentional as we currently don't support clearing relational data.

**Comment by lluishi93** [comment]
> This is not a bug but intentional as we currently don't support clearing relational data.

How so? What does not allowing this bring to the table?

**Comment by Nitwel** [comment]
Relational interfaces only model the changes you do to the data so clearing in that case would only mean undoing all changes made that aren't saved. We will look into adding this in later on but for now disabling it was the solution that made most sense.

**Comment by lluishi93** [comment]
> Relational interfaces only model the changes you do to the data so clearing in that case would only mean undoing all changes made that aren't saved. We will look into adding this in later on but for now disabling it was the solution that made most sense.

Ok. I though it just simply deleted all the records related to the item that we were editing. We look forward to have this added back again. Thanks.
