### ISSUE TITLE
Page not found when collection and item is null

### ISSUE THREAD

**Issue by u12206050** [directus/directus#15805]
### Describe the Bug

When sending a notification to a user via flows or custom extension, with not collection and item the user is still able to click on the notification but is redirected to `/admin/content/null/null` which is "Not Found"

### To Reproduce

Send a notification to a user using flows.

### Errors Shown

"Page not found"

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

chromium

### How are you deploying Directus?

Locally & GCP

**Comment by azrikahar** [comment]
Should be the same as #13727 👍
