### ISSUE TITLE
Cannot reorder fields or change "required/visible" columns on settings/tables

### ISSUE THREAD

**Issue by peremp** [directus/directus#1581]
## Version Info
  - Directus version and branch: 6.4.0

## Steps to Reproduce (reorder)
 1. Go to 'settings/tables' and edit some table.
 2. Drag and drop a field to reorder

**Expected**
The field is reordered.

**Current**
An error appears: This query failed: INSERT INTO `directus_columns` (`id`, `column_name`, `sort`, `table_name`, `required`, `ui`, `hidden_list`, `hidden_input`, `comment`, `relationship_type`, `related_table`, `junction_table`, `junction_key_right`, `junction_key_left`) VALUES ('id', 'id', '1', 'directus_columns', '', 'numeric', '', '', '', NULL, NULL, NULL, NULL, NULL)

## Steps to reproduce (required/visible)
 1. Go to 'settings/tables' and edit some table.
 2. Click on the "eye" of any field to change its visibility

**Expected**
Visibility of the field is changed.

**Current**
Error: There seems to be a problem... Columns (use_case_id)
Data Type: The field cannot be empty

Same for the "required" column:
Error: There seems to be a problem... Columns (active)
Data Type: The field cannot be empty

**Comment by benhaynes** [comment]
I am still getting this error when re-ordering columns within Settings:

```Server Error
This query failed: INSERT INTO `directus_columns` (`id`, `column_name`, `sort`, `table_name`, `required`, `ui`, `hidden_list`, `hidden_input`, `comment`, `relationship_type`, `related_table`, `junction_table`, `junction_key_right`, `junction_key_left`) VALUES ('activity', 'activity', '12', 'activities', '', 'textarea', '', '', '', NULL, NULL, NULL, NULL, NULL)```

It's trying to enter the ID as the column name

**Comment by benhaynes** [comment]
👻  this phantom bug has somehow fixed itself. I will re-open if it's reproducible
