### ISSUE TITLE
Flow: Add Mail Templates

### ISSUE THREAD

**Issue by JonathanSchndr** [directus/directus#15826]
### Discussed in https://github.com/directus/directus/discussions/15706

<div type='discussions-op-text'>

<sup>Originally posted by **JonathanSchndr** September 22, 2022</sup>
It would be great if you could also select a custom mail template in Flows > Send Mail and there is a mapping for Data. Currently the workaround is to copy your base template and the content as code again.

![Bildschirmfoto 2022-09-22 um 15 54 17](https://user-images.githubusercontent.com/922406/191766093-070e8156-9971-4bf3-a5a2-c5c7fa371784.png)
</div>

**Comment by rijkvanzanten** [comment]
Linear: [ENG-173](https://linear.app/directus/issue/ENG-173/flow-add-mail-templates)
