### ISSUE TITLE
Cannot delete items after latest upgrade for users role

### ISSUE THREAD

**Issue by mmmaxxxe** [directus/directus#15828]
### Describe the Bug

The "delete" button is greyed after upgrade for users that has a filter like this:

![image](https://user-images.githubusercontent.com/102175921/193271821-b52e9f19-90eb-4a28-a864-a89f3fdc6189.png)

![image](https://user-images.githubusercontent.com/102175921/193271980-6c057313-987d-4ab1-b67e-89f7a317a987.png)

![image](https://user-images.githubusercontent.com/102175921/193272562-0d3fa308-0b62-4aea-aa45-f3c04289bb7a.png)

This happens at the very same time for every item of every collection, without any modification.

### To Reproduce

Upgrade to 9.18.1

### Errors Shown

Grayed Delete button

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

cloud

### What database are you using?

cloud

### What browser are you using?

chrome and firefox

### How are you deploying Directus?

directus cloud

**Comment by azrikahar** [comment]
I believe this is the same underlying issue as #11059, particularly this comment here: https://github.com/directus/directus/issues/11059#issuecomment-1024104669 which notes the delete permission in particular is still disabling the button. 

I do acknowledge that you have noted it as "after latest upgrade" which implied it used to work, but the linked issue is present in an older version, and I've also tried this in `9.17.4` and `9.16.1` to be sure (and they didn't work). So I believe it didn't used to work, but if you can share a specific version that worked (likely via local installs, not cloud), it'd be much appreciated as well!

Closing this in favor of tracking it in #11059.
