### ISSUE TITLE
A bug when relinking flow operations

### ISSUE THREAD

**Issue by erondpowell** [directus/directus#15831]
### Describe the Bug

 The following error is triggered when I try to reassign Flow operations using the method shown in the video:

```
{
  "errors": [
    {
      "message": "Field \"resolve\" has to be unique.",
      "extensions": {
        "code": "RECORD_NOT_UNIQUE",
        "collection": "directus_operations",
        "field": "resolve",
        "invalid": "e5528245-c76c-4889-930f-37fce63b660a"
      }
    }
  ]
}
```

https://user-images.githubusercontent.com/62306630/193347467-406f8226-8454-4e2c-b484-24a9e49c23f6.mov

### To Reproduce

See above

### Errors Shown

See above

### What version of Directus are you using?

Cloud

### What version of Node.js are you using?

n/a

### What database are you using?

n/a

### What browser are you using?

Chrome

### How are you deploying Directus?

Cloud

**Comment by erondpowell** [comment]
> At first, webhooks were working just fine. Then I tried to put a log that referenced the webhook operation with {{$last}}.
After that, the console log operation stopped showing up any time I triggered the flow:

This was a silly error on my part.... The previous operation was failing... and the log was on the "success" route.

Still not sure why reconfiguration was breaking though 🤔

**Comment by azrikahar** [comment]
This should be the same as #14185, let's track this over there 👍
