### ISSUE TITLE
Suggestion: UI Improvement w/User Image

### ISSUE THREAD

**Issue by JREAM** [directus/directus#1583]
## Version Info
  - Directus 6.4
  - PHP version: 7.0
  - MySQL version: Percona 5.7.18
  - Web server: Apache 2.4
  - OS name and version: Ubuntu 16.10 x64 w/Gnome

## Steps to Reproduce
 1. Add your photo (Do not Save)
 2. Click Upload (Doesn't do anything), perhaps it should be disabled until the photo is removed? 
Also, Click "From Directus" with your image there, it leaves the page without warning.

## Logs or Screenshots
![osse](https://user-images.githubusercontent.com/145959/27206777-971d99ce-5207-11e7-9a86-548d94e92d91.jpg)

**Comment by benhaynes** [comment]
Different version (luckily!)
We can re-open if this is a problem on 6.4 too...
