### ISSUE TITLE
Calendar View not respecting nested display template

### ISSUE THREAD

**Issue by eikaramba** [directus/directus#15832]
### Describe the Bug

I want to show in the calendar view a field from my collection lendings. The structure is:
`lendings->(M2M) positions ->(M2O) article -> field: title`

However if i select this nothing changes the default ID is still shown. Other fields on the lendings collection work, but nested fields not.

### To Reproduce

Use calendar view for collection. Collection should have relation as described above.

### Errors Shown

![grafik](https://user-images.githubusercontent.com/1320525/193315844-675d88d5-0b01-43df-98e5-649415e07434.png)

see also the following video:
https://user-images.githubusercontent.com/1320525/193316602-a433096b-9fec-415c-9bb4-c6704fc017f0.mp4

No console error shown

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16

### What database are you using?

sqlite

### What browser are you using?

FF

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
This might be related to #12957 as the `isValid` check is not actually accounting for "valid" date-only strings, thus the "increment end date by 1" logic for FullCalendar within the IF statement isn't being applied in this scenario:

https://github.com/directus/directus/blob/cbe1e7fbc69c8e9bd02254e9ed6efc35ba6468ef/app/src/layouts/calendar/index.ts#L298-L306

**Comment by br41nslug** [comment]
The display is falling back to the default behavior here because of the M2M relation in there. The methods used for extracting the display value do not account for the array of data returned here. Unfortunately you can't put in a manual template in this specific situation either.

**Comment by eikaramba** [comment]
is there anything i can do? if somehow pins me to the right location of the code i can try to fix it maybe :)

**Comment by eikaramba** [comment]
i tried to work on this. First one has to decide what to do with M2M relations here. either pick the first entry or pick all and combine them with `", "`.

For the first approach i was able to modify the code to actually look at the proxy targets type and if it is an array modify the current dot path and append `[0]` to it. then the `renderDisplayStringTemplate` will get the correct value. however also the template string for micromustache has to be adapted as well.

I'm not happy with the code but here it is for now. It feels like there are lot of moving parts here, so fixing this will not be as easy as i thought unfortunately.
```js
export function renderDisplayStringTemplate(
	collection: string,
	template: string,
	item: Record<string, any>
): string | null {
	const fieldsStore = useFieldsStore();

	const fields = getFieldsFromTemplate(template);

	const fieldsUsed: Record<string, Field | null> = {};

	for (const key of fields) {
		set(fieldsUsed, key, fieldsStore.getField(collection, key));
	}

	const { aliasFields } = useAliasFields(ref(fields));

	const parsedItem: Record<string, any> = {};

	for (const key of fields) {
		const parts = key.split('.');
		let partsNew=[];
		let finalKey ="";
		for (var i = 0; i < parts.length; i++) {
			partsNew.push(parts[i]);
			finalKey = partsNew.join(".");
			if(Object.getPrototypeOf(get(item,finalKey)).constructor.name=="Array"){
				partsNew[i] = partsNew[i] + "[0]";
			}
		};
		template = template.replace(key,finalKey); //make micromustache happy
		



		const value =
			!aliasFields.value?.[finalKey] || get(item, finalKey) !== undefined
				? get(item, finalKey)
				: get(item, aliasFields.value[finalKey].fullAlias);

		
		let display: DisplayConfig | undefined;

		if (fieldsUsed[finalKey]?.meta?.display) {
			display = getDisplay(fieldsUsed[finalKey]!.meta!.display);
		}

		if (value !== undefined && value !== null) {
			set(
				parsedItem,
				finalKey,
				display?.handler
					? display.handler(value, fieldsUsed[finalKey]?.meta?.display_options ?? {}, {
							interfaceOptions: fieldsUsed[finalKey]?.meta?.options ?? {},
							field: fieldsUsed[finalKey] ?? undefined,
							collection: collection,
					  })
					: value
			);
		} else {
			set(parsedItem, finalKey, value);
		}
	}

	return renderPlainStringTemplate(template, parsedItem);
}
```

**Comment by rijkvanzanten** [comment]
Linear: [ENG-172](https://linear.app/directus/issue/ENG-172/calendar-view-not-respecting-nested-display-template)
