### ISSUE TITLE
Calendar view EndDate always -1 before actual EndDate

### ISSUE THREAD

**Issue by eikaramba** [directus/directus#15844]
### Describe the Bug

Currently if the endDate of an item is 10.10.22 the calendar view displays the bar until 09.10.22 -  i'm sure this can make sense, however for our case it would make more sense that the bar is stretching until 10.10.22 (endDate included).

Ideally this is configurable, as both cases can make sense i think. In our case the user is actually renting an item and selecting an item like this
![grafik](https://user-images.githubusercontent.com/1320525/193416436-ef768bf3-975e-4180-a566-166bc7fcd2de.png)

### To Reproduce

1. Use calendar
2. Set Enddate to n
3. Bar displayed until n-1

### Errors Shown

![grafik](https://user-images.githubusercontent.com/1320525/193416443-54fa65ab-7263-41eb-9122-0ae8c5ddd5d5.png)

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16

### What database are you using?

SQLITE

### What browser are you using?

FF

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
This might be related to #12957 as the `isValid` check is not actually accounting for "valid" date-only strings, thus the "increment end date by 1" logic for FullCalendar within the IF statement isn't being applied in this scenario:

https://github.com/directus/directus/blob/cbe1e7fbc69c8e9bd02254e9ed6efc35ba6468ef/app/src/layouts/calendar/index.ts#L298-L306

**Comment by eikaramba** [comment]
date-fns unfortunately is not suited for this, but we can work around this by first parsing the date and then using the isValid method on that. i am currently preparing a PR for this.

**Comment by azrikahar** [comment]
> first parsing the date and then using the isValid

@eikaramba thanks for preparing the PR! I believe that's the initial thought I've had after realizing the assumption that `isValid` would try to parse it first before checking is actually incorrect. Will gladly review your PR when you submit it 👍

**Comment by eikaramba** [comment]
done! never worked locally on the directus core. glad that i was able to setup everything and can contribute now :) the only thing i haven't yet figured out how to run the tests locally.

btw: is it normal that i have to run `pnpm -r dev` AND `pnpm --filter @directus/app dev` AND `pnpm --filter directus dev` each in separate terminals for everything to work? i thought the first command would invoke everything. but as long as it works, it works.

**Comment by azrikahar** [comment]
> done! never worked locally on the directus core. glad that i was able to setup everything and can contribute now :) the only thing i haven't yet figured out how to run the tests locally.

Thank you! You should be able to run `pnpm -F directus test` or `pnpm -F @directus/app test` to test the API or the App respectively. (`-F` is short for `--filter`)

As for E2E test, you can refer to here: https://docs.directus.io/contributing/running-locally.html#_9-running-tests 👍

> btw: is it normal that i have to run `pnpm -r dev` AND `pnpm --filter @directus/app dev` AND `pnpm --filter directus dev` each in separate terminals for everything to work? i thought the first command would invoke everything. but as long as it works, it works.

It's normal for either `pnpm -r dev` or `pnpm --filter @directus/app dev` AND `pnpm --filter directus dev`, but definitely not all 3 together 🤔 I believe the first command is prone to race conditions which might explain why it didn't work out-of-the-box for you. 

I think using `pnpm --filter @directus/app dev` and `pnpm --filter directus dev` (also you might want to add in `pnpm --filter @directus/shared dev` when tinkering code over there, which can happen fairly commonly!) are generally good enough.
