### ISSUE TITLE
Interface options for for WYSIWYG Full can't be saved

### ISSUE THREAD

**Issue by wittwerch** [directus/directus#1584]
## Version Info
  - Directus version and branch: ba808c0af54f3be33db01d0ed5534e36441c580b
  - PHP version: 7.1
  - MySQL version: 5.7
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: Docker

## Steps to Reproduce
1. Add a "WYSIWYG Full" field to a table
2. Go the the Interface Options
3. Unselect "Tables", "Image", "Insert Media"
4. Click on Save

## Logs or Screenshots
![screen shot 2017-06-16 at 08 22 02](https://user-images.githubusercontent.com/1575445/27214526-511e5970-526d-11e7-84d1-46ed0f5bf511.png)

**Comment by benhaynes** [comment]
I've experienced this too – @rijkvanzanten, I know we spoke about this... what were your thoughts?

**Comment by rijkvanzanten** [comment]
It's a 🐛 which is going to 💥!

**Comment by benhaynes** [comment]
Is it for you or @WellingGuzman?

**Comment by rijkvanzanten** [comment]
I'll handle it tonight / tomorrow morning (CEST) 👍

**Comment by WellingGuzman** [comment]
I can take care of @rijkvanzanten, it seems you shouldn't validate fields with `default_value`

**Comment by WellingGuzman** [comment]
Hey @wittwerch, let us know if this [commit](https://github.com/directus/directus/commit/807d469c0fc1ed6ad5b27143a5ff68f1ec9cd35c) solves the problem for you too.

**Comment by rijkvanzanten** [comment]
Ah, great!

**Comment by benhaynes** [comment]
I'm getting this error after saving:

```
Error
Error: Uncaught TypeError: value.split is not a function
File: http://local.directus.com/app/core/interfaces/select/interface.js?bust=807d469c0fc1ed6ad5b27143a5ff68f1ec9cd35c
Line:70
```

**Comment by rijkvanzanten** [comment]
@benhaynes I'm not able to reproduce this issue.. What steps did you take to get this?

The value of the select gets split on the set delimiter. If the value isn't set it defaults to an empty string (which can be split) so not sure why you are getting this.

**Comment by WellingGuzman** [comment]
I think @benhaynes may be getting a value that's not a string.

**Comment by rijkvanzanten** [comment]
@WellingGuzman How could that be possible from an `input[type="text"]`? I could implement a check nonetheless, but this issue can than also arise in other interfaces..

**Comment by WellingGuzman** [comment]
@rijkvanzanten I'm guessing, that's seem to be the only reason that it doesn't have split, and remember that `this.options.value` doesn't not come directly from `input` but rather from the model.

I know you will get it I just wanted to give some ideas :)

**Comment by benhaynes** [comment]
Haha, I have no idea how I got it... but it's gone now. I think I have a magical cache that refuses to be completely cleared despite my best efforts. Working perfectly now!
