### ISSUE TITLE
Filter and Groupby Date not working Properly

### ISSUE THREAD

**Issue by anupsunni** [directus/directus#15843]
### Describe the Bug

Querying a Collection to get Sum of Prices
In the image I am trying to group by day - month and year because the field is a datetime field. 
at the same time I want it only between 2 dates.
The filter isnt working.

I am also trying the aggregate sum of prices weekly, but I want it only between 2 dates, how to make filter work in that case. 
it seems like group by and filter are for dates are not working properly. 

Using SDK as shown below:
`
ordersResponse = await ordersService.readByQuery({
				fields: [ "*.*" ],
				limit: -1,
				group: [ "day(purchase_date)", "month(purchase_date)", "year(purchase_date)" ],
				aggregate: { sum: [ "price" ] },
				sort: [ "day(purchase_date)", "month(purchase_date)", "year(purchase_date)" ],
				filter: {}
			});
`

Filtering as shown below:
`
filter: {
					"_and":
						[
							{ purchase_date: { "_lte": dateToDDMMYY(to_date) } }, { purchase_date: { "_gte": dateToDDMMYY(from_date) } }
						]
				}
`

### To Reproduce

Mentioned In the description.

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

16.16.0

### What database are you using?

14

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally

**Comment by licitdev** [comment]
@anupsunni I've just tested your filter and query to be working fine on the API.
What is your output of `dateToDDMMYY(to_date)`?

You've mentioned that the field is of `datetime` type. Therefore, the filter value should have be in the `datetime` format of `YYYY-MM-DDTHH:mm:ss` such as `2022-09-31T12:00:00`.

Additionally, kindly update your Directus instance to the latest version.

**Comment by rijkvanzanten** [comment]
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻
