### ISSUE TITLE
Sorting nested translation field not working if display template is not defined

### ISSUE THREAD

**Issue by Rar9** [directus/directus#15849]
### Describe the Bug

Changing the nested `translations.name` sort order will break/reset to some strange values
![image](https://user-images.githubusercontent.com/2239608/193455796-3851f84b-ede2-4a70-bf7f-4c85da0b1b01.png)

If I define a default Display Template this will not happen

### To Reproduce

![image](https://user-images.githubusercontent.com/2239608/193455962-cc7a030b-5ea0-4314-b25d-565c48b2a8e5.png)

### Errors Shown

```json
{
  "errors": [
    {
      "message": "select `XX`.`id` from `XX` order by `skkvx`.`Name` asc limit 25 - ER_BAD_FIELD_ERROR: Unknown column 'skkvx.Name' in 'order clause'",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```
  
Pressing Reset button i then end up with
  
![image](https://user-images.githubusercontent.com/2239608/193456032-f1d4d7cf-66e8-4320-a090-03ea833d5f8c.png)

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.7

### What database are you using?

Maridb 10.6x

### What browser are you using?

Firefox

### How are you deploying Directus?

Plesk

**Comment by Rar9** [comment]
When Default Display Template is used to define ID + Name I can switch to Name sorting with out a crash

**Comment by Rar9** [comment]
Is there a change to Output of the TRANSLATED NAME to only display the USER specific language instead of all values?

**Comment by azrikahar** [comment]
> Is there a change to Output of the TRANSLATED NAME to only display the USER specific language instead of all values?

You should be able achieve this by enabling the "Use Current User Language" option in the Translations display (and also configuring the Display Template in the same display's options) 🙂 To clarify, note that this is on the `translations` field itself, rather than on `translations.name`.

https://user-images.githubusercontent.com/42867097/193520308-404ac275-8d31-4813-adb8-a500f5b02702.mp4

**Comment by Rar9** [comment]
I already set both English and current user. Language like in your clip 

Would this also in theory resolve the name that shows both eng/de?



I also hope that the know thumbnail issue will be implemented in next update.

**Comment by azrikahar** [comment]
> Would this also in theory resolve the name that shows both eng/de under layouts ?

Yes, but do make sure you are selecting `translations` (with Translations display mentioned above), and not the `translations -> name` in the table layout.

**Comment by Rar9** [comment]
![image](https://user-images.githubusercontent.com/2239608/193999884-9656c8aa-1ab7-44d3-9346-a47ac11b6499.png)

Yes I have this

In the XX/translation/Name  there is no Setting for language

**Comment by azrikahar** [comment]
Make sure not to use `translations -> name` (the screenshot in the top right corner). You can also refer to the video in my other reply over here: https://github.com/directus/directus/discussions/15661#discussioncomment-3801794 to see the differences between `translations` and `translations -> title`.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-171](https://linear.app/directus/issue/ENG-171/sorting-nested-translation-field-not-working-if-display-template-is)

**Comment by azrikahar** [comment]
Seems like this bug exists up until `9.21.1`, but not `9.22.1`. Confirmed that #14798 was the PR fixing this issue. Marking this resolved.
