### ISSUE TITLE
GraphQL endpoint gives INTERNAL_SERVER_ERROR with 'Union type must define one or more member types.'

### ISSUE THREAD

**Issue by marianhlavac** [directus/directus#15856]
### Describe the Bug

Acessing the GraphQL endpoint gives HTTP 500 with **'Union type must define one or more member types.'**

The problematic data model looks like this, I'm not sure how to give more information on the schema of the data model.

<img width="1071" alt="Screenshot 2022-10-02 at 21 51 10" src="https://user-images.githubusercontent.com/3010503/193473451-4efa74e5-d21b-4ea0-b0d2-2728d2d482ac.png">

The DDL of the table in the database is following

```sql
CREATE TABLE product_feature_block_translations_product_features (
    id SERIAL PRIMARY KEY,
    product_feature_block_translations_id integer REFERENCES product_feature_block_translations(id) ON DELETE SET NULL,
    item character varying(255),
    collection character varying(255)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX product_feature_block_translations_product_features_pkey ON product_feature_block_translations_product_features(id int4_ops);
```

### To Reproduce

Accessing the GraphQL endpoint with any query triggers this error.

### Errors Shown

```json
{
    "errors": [
        {
            "message": "Union type product_feature_block_translations_product_features_item_union must define one or more member types.",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}
```

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

Node from Docker image directus/directus:9.18.1

### What database are you using?

Postgres 13.4

### What browser are you using?

-

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
> I'm not sure how to give more information on the schema of the data model.

Would you mind creating a minimal setup which includes this data model (I assume it is/was originally an m2a junction table based on the `item` and `collection` field?), and [create a schema snapshot](https://docs.directus.io/reference/cli.html#snapshot-the-data-model) to share it here? That would definitely help a lot to make it easier to reproduce the same data model 👍

**Comment by rijkvanzanten** [comment]
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻
