### ISSUE TITLE
Openid is not working

### ISSUE THREAD

**Issue by terion-name** [directus/directus#15857]
### Describe the Bug

First I've tried with my Authentik server — no luck
But maybe it was an authentik problem? Tested on a generic auth0 app:

```
AUTH_AUTH0_DRIVER="openid"
AUTH_AUTH0_CLIENT_ID="string:clientid"
AUTH_AUTH0_CLIENT_SECRET="string:clientsecret"
AUTH_AUTH0_ISSUER_URL="string:https://dev-5ibjswzg.us.auth0.com/.well-known/openid-configuration"
AUTH_AUTH0_IDENTIFIER_KEY="email"
```

Pressing button on login screen, getting after auth :
<img width="447" alt="Снимок экрана 2022-10-03 в 00 32 46" src="https://user-images.githubusercontent.com/1060205/193477214-bda7119a-97c1-482d-973f-e5b36fe5f423.png">

In log:
```
00:30:59 ✨ request completed GET 302 /auth/login/auth0?redirect=http://localhost:8055/admin/login?continue 35ms
00:31:45 ⚠️  Invalid user credentials.
00:31:45 ✨ request completed GET 302 /auth/login/auth0/callback?code=GPi4L0mKAmeXaGrbp9dUwB35EGS9rl6ME-0SkrTPKkgKG&state=YzM4li9L8ca-uNLgJ_frT7PqxMVoJ4V0n-jCPAL_-FA 1s
00:31:45 ✨ request completed GET 200 /admin/login?reason=INVALID_CREDENTIALS 4ms
```

### To Reproduce

Create a generic Auth0 app, configure directus for it, try to login

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

18

### What database are you using?

mysql

### What browser are you using?

brave

### How are you deploying Directus?

locally

**Comment by terion-name** [comment]
sorry, forgot ALLOW_PUBLIC_REGISTRATION

**Comment by Dan6erbond** [comment]
Did you configure anything specific in Authentik to get this working? I'm getting the same issue with this config:

```env
AUTH_PROVIDERS="authentik"

AUTH_AUTHENTIK_DRIVER="openid"
AUTH_AUTHENTIK_CLIENT_ID=""
AUTH_AUTHENTIK_CLIENT_SECRET=""
AUTH_AUTHENTIK_SCOPE="openid profile email"
AUTH_AUTHENTIK_ISSUER_URL=""
AUTH_AUTHENTIK_IDENTIFIER_KEY="email"
AUTH_AUTHENTIK_ALLOW_PUBLIC_REGISTRATION=true
AUTH_AUTHENTIK_REQUIRE_VERIFIED_EMAIL=true
AUTH_AUTHENTIK_DEFAULT_ROLE_ID="18d94ae3-533a-4de3-b2a8-b11070824ba1"
AUTH_AUTHENTIK_ICON="user-lock"
```

**Comment by xgenvn** [comment]
@terion-name same question with @Dan6erbond, do we need to configure anything special in Authentik?
In my setup, using AUTH_AUTHENTIK_ISSUER_URL=<path to .well-known> is helpful and the user is created successfully. But still showing INVALID_CREDENTIALS on the logs.

I guess maybe something with the cookie so need to try with real domain.
