### ISSUE TITLE
The char @ in a translation string breaks the app

### ISSUE THREAD

**Issue by icomad** [directus/directus#15867]
### Describe the Bug

This issue I think it is strictly related to [this closed issue](https://github.com/directus/directus/issues/11056).
If the character `@` appears in a translation string  then the collection using that translation string is no longer accessible, only a blank screen is showing.

### To Reproduce

Create a collection with an input field and use as a placeholder a translation string having `@` as a character like `test@example.com`. That collection will no longer be accessible by users using the locale in which the `@` is being used in the translation string.

### Errors Shown

The browser just display a blank page, in the console there is a `SyntaxError: 9` referencing a `vue-i18n.[#####].entry.js` file

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

18.9.0

### What database are you using?

Postgres 14.5

### What browser are you using?

Firefox

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
Nice catch! This is definitely the same root cause as the closed issue you have linked. Should be due to Translation Strings didn't exist yet when the fix was applied, so the same fix was missed when it was first implemented.
