### ISSUE TITLE
Select fetching the field that does not exist in the table

### ISSUE THREAD

**Issue by leomangueira** [directus/directus#15866]
### Describe the Bug

I have an Oracle database already ready, I chose the PCPEDCFV table which is my order table, in this table there is no "id" field. My primary key is the "CGCCLI" field.
How do I tell directus that the filter must be done using the fields that exist in the table and not filter the field "id" when this field does not exist in my table?

![image](https://user-images.githubusercontent.com/23041699/193604243-b395c216-ce9a-4b98-a889-145bb71482fa.png)
![image](https://user-images.githubusercontent.com/23041699/193604315-0c6406ff-bcaa-495e-a7f5-81f72bce9404.png)

`Error: select * from (select "PCPEDCFV"."CGCCLI", "PCPEDCFV"."CODUSUR", "PCPEDCFV"."DTABERTURAPEDPALM", "PCPEDCFV"."NUMPEDRCA", "PCPEDCFV"."id" from "PCPEDCFV" order by "PCPEDCFV"."NUMPEDRCA" asc) where rownum <= :1 - ORA-00904: "PCPEDCFV"."id": identificador inv├ílido`

### To Reproduce

Click collection 

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.16.0

### What database are you using?

Oracle 19c

### What browser are you using?

Edge

### How are you deploying Directus?

running locally

**Comment by leomangueira** [comment]
this is a detail that I realized that Directus does not recognize the field as a primary key, I tried to mark the primary key option in directus in order to try to solve the problem, but directus tries to change the field in the database and gives an error because the field is already a primary key, it informs that it is not possible to make the change because the field is already a primary key. I would like to know how to make directus recognize the fields that are primary key in oracle

**Comment by br41nslug** [comment]
After some testing primary keys seems to be picked up correctly based on the primary key constraint with already existing tables. Composite keys don't work which to be expected as that's not supported by Directus. Can you elaborate on how your primary key are configured for this table? 
![image](https://user-images.githubusercontent.com/9389634/195548906-6c904597-fd1e-4ee2-9ea5-fb4310d4b407.png)
Closing this ticket for now until more information is available.

**Comment by leomangueira** [comment]
is your database oracle? my primary key is a normal PK field like in any bank

**Comment by leomangueira** [comment]
I created a new project and connected my oracle database and it still doesn't recognize the fields that are primary key.
![image](https://user-images.githubusercontent.com/23041699/196062569-046f6732-af5b-4534-ba45-77397f8cbb4a.png)
![image](https://user-images.githubusercontent.com/23041699/196062634-15269db0-14d9-4dc2-b1d6-06fe03ec1da2.png)

**Comment by br41nslug** [comment]
My database for testing was indeed Oracle but from your screenshots it looks like you're using composite primary keys which are not supported at this time.
![image](https://user-images.githubusercontent.com/9389634/196130392-3d7b609b-fae3-44b9-845c-6028275ed9f8.png)

https://github.com/directus/directus/discussions/12137
https://github.com/directus/directus/discussions/14158

**Comment by leomangueira** [comment]
is there a deadline for directus to support composite primary keys?

**Comment by br41nslug** [comment]
[Unfortunately, we can not provide estimates on features or fixes](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete.
