### ISSUE TITLE
Storage system requires remote files also be stored locally

### ISSUE THREAD

**Issue by aaron-manning** [directus/directus#15882]
### Describe the Bug

Scenario:

Directus is configured to use a S3 bucket that holds numerous large files.
Some of the files were uploaded using Directus, some of them were uploaded by another system and entries were added to directus_files programmatically (via sql). directus_files has an entry for every file, but the remote files have a null filename_disk.

Issue:
Currently there seems to be no way to serve files from S3 that aren't ALSO stored in the local filesystem (./uploads for example).
The following limitations seem to apply:

1. All files have to be uploaded using directus (via UI or API call) so that the files are copied to the local file system.
2. Files that were uploaded via the directus UI or API get sent to S3 and also stored locally. Migrating the Directus instance to another host will cause files to fail to load unless the uploaded files are also backed up and transfered.
3. Directus seems to be unable to serve any remote files that aren't also stored on the local file system. This negates many of the benefits of using a cloud storage provider, and causes issues with storage requirements and the ability to recreate instances and load balance.
4. Directus throws an error when attempting to download any file with a null filename_disk field (which is a nullable field in the database). I have been unable to find any way to serve the files (by clicking download in the UI for example) without both setting filename_disk AND ensuring the file is on the local filesystem.

Suggested behaviour:
1. If the storage adaptor isn't 'local', attempt to read the file from disk (if filename_disk not null), if that fails, request the file from the storage provider (eg S3). Once downloaded from the storage provider, if filename_disk not null, store the file to disk using the filename_disk id for later re-use.

Thanks

### To Reproduce

see above

### Errors Shown

When trying to serve a remotely stored file with a null filename_disk
```
{"errors":[{"message":"E_UNKNOWN: An unknown error happened with the file null.\n\nError code: ERR_INVALID_ARG_TYPE\nOriginal stack:\nTypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string. Received null\n    at new NodeError (node:internal/errors:372:5)\n    at validateString (node:internal/validators:120:11)\n    at join (node:path:1172:7)\n    at LocalFileSystemStorage._fullPath (/directus/node_modules/@directus/drive/dist/LocalFileSystemStorage.js:51:61)\n    at LocalFileSystemStorage.exists (/directus/node_modules/@directus/drive/dist/LocalFileSystemStorage.js:104:54)\n    at AssetsService.getAsset (/directus/node_modules/directus/dist/services/assets.js:73:71)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /directus/node_modules/directus/dist/controllers/assets.js:122:36","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}
```

When trying to serve a remotely stored file with a valid filename_disk, which was once stored locally but now longer exists in the local filesystem (eg due to moving instance to a new host)

```
{"errors":[{"message":"You don't have permission to access this.","extensions":{"code":"FORBIDDEN"}}]}
```

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

14.18.1

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
I don't really understand the bug here. `filename_disk` is what tells Directus where to read the file from. If that value is corrupted (for whatever reason), then Directus won't be able to load the file. This seems to be expected behavior to me, but happy to reopen/discuss if I'm misunderstanding 🙂

**Comment by rijkvanzanten** [comment]
Also to clarify: no, files don't have to be stored locally when you're using S3. If you've called your storage location `s3` in the environment variables, make sure that the `storage` in `directus_files` also uses the name `s3` 👍🏻

**Comment by aaron-manning** [comment]
> Also to clarify: no, files don't have to be stored locally when you're using S3. If you've called your storage location `s3` in the environment variables, make sure that the `storage` in `directus_files` also uses the name `s3` 👍🏻

I'm still experiencing this issue.

Simple test:

docker config
```
      STORAGE_LOCATIONS: "S3"
      STORAGE_S3_DRIVER: "s3"
      STORAGE_S3_KEY: ${STORAGE_S3_KEY}
      STORAGE_S3_SECRET: ${STORAGE_S3_SECRET}
      STORAGE_S3_BUCKET: ${STORAGE_S3_BUCKET}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION}
      STORAGE_S3_ENDPOINT: "s3.amazonaws.com"
      STORAGE_S3_ACL: "private"
```

1. upload a file to S3 using Directus UI = works OK. confirmed uploaded to S3.
2. note that the download button in the file manager successfully downloads the file (probably from local storage rather than S3)
3. set the 'filename_disk' in the 'directus_files' table for this upload to null, as we should not need a local file and I want to ensure we are serving the file from S3, not the local filesystem.
4. press the download button in the file manager in Directus and note the following error

```
{"errors":[{"message":"The \"path\" argument must be of type string. Received null","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}
```

table definition says this field is nullable. 
If the value is set to an empty string instead of null I get the following error:

```
{"errors":[{"message":"You don't have permission to access this.","extensions":{"code":"FORBIDDEN"}}]}
```

There is nothing obviously wrong with the s3 API keys I have provided Directus. It uploads the file fine, and I am able to download the file from S3 using an external application with the same keys.

Please can you describe how this is supposed to function without also having the file saved on disk

Thanks
