### ISSUE TITLE
Empty/Null string field validation does not stop record creation

### ISSUE THREAD

**Issue by abbcdfi** [directus/directus#15899]
### Describe the Bug

Setting ~role-level~ validation rules to stop users creating records with NULL or empty values in a field does not stop the record from being created.

Edit: Tested this with global validation rules, and the same problem occurs.

Edit2: Tested the same validation rules on an update, changing the field value from populated to empty, and the validation rules worked. Seems likely related to this discussion: https://github.com/directus/directus/discussions/12282

I've tested other validation rules e.g. `greater than` and `contains` and they work.

The `Matches RegExp` rule in the reproduction steps below fails to stop an empty value. But, other `Matches RegExp` rules work. I'm wondering if this is an issue where validation rules are not checked unless a value is entered?

### To Reproduce

- Create a role with read access to a table containing a text field
- Configure the role with custom field validation on the text field, and add one of the following validation rules:
<tab><img width="273" alt="image" src="https://user-images.githubusercontent.com/106962299/194307177-54ede98b-1634-47a7-b2e9-737a38eadd44.png">

- Login as a user with the role, then attempt to create a record in the table, leaving the text field of the record empty.
- Observe that the record with an empty text field has been created in the DB. 
Directus (I think?) should block the user from creating a record where the text field is empty

### Errors Shown

The error is that a record that does not pass the validation rules can be written to the DB.

I'd expect the UI to display something like the following.
![image](https://user-images.githubusercontent.com/106962299/194308872-6250bf49-52a5-4d88-9596-63acb500b45d.png)

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

18.9.0

### What database are you using?

Postgres 13.7

### What browser are you using?

Safari

### How are you deploying Directus?

AWS EC2 self hosted

**Comment by br41nslug** [comment]
Thought there was already a ticket for this but indeed validation fails (or is skipped rather) for fields that are not submitted and fall back to defaults on the database level.

**Comment by azrikahar** [comment]
> I'm wondering if this is an issue where validation rules are not checked unless a value is entered?

I believe this should technically be the same as #14571, especially since both essentially uses `validatePayload` which might be the root cause here:

### Field Validation

https://github.com/directus/directus/blob/4904c3bba1e360476e316a7d2fc06a5dc10a5409/api/src/services/authorization.ts#L550-L566

### Flows Conditions Operation

https://github.com/directus/directus/blob/4904c3bba1e360476e316a7d2fc06a5dc10a5409/api/src/operations/condition/index.ts#L12

Let's track this in the same issue 👍
