### ISSUE TITLE
Argon2 fails to run on Apple M1

### ISSUE THREAD

**Issue by adamdobkin-mc** [directus/directus#15900]
### Describe the Bug

The `directus bootstrap` command fails when running on Apple M1 CPUs using Node version 16 and above. The Argon2 hashing library used by Directus did not support Apple M1 CPUs until version 0.29 ([see this issue in the Argon2 repo](https://github.com/ranisalt/node-argon2/issues/305)) which was released in late August. [Directus is still on version 0.28.X](https://github.com/directus/directus/blob/v9.18.1/api/package.json#L93) so fixing this issue should be as simple as upgrading the library. Thank you!

### To Reproduce

Attempt to run `directus bootstrap` using Node version 16 or above. Prior versions of Node did not support Apple M1 CPUs so Node would run using [Rosetta 2 which translated the CPU instructions](https://support.apple.com/en-us/HT211861) and circumvented the problem.

### Errors Shown

<img width="958" alt="argon2" src="https://user-images.githubusercontent.com/110941247/194307713-4ec97963-a7e9-4f12-9b17-0f2471c79f57.png">

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.17.1

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by luojiegithuber** [comment]
but now the `npx directus start` command fails when running on Apple M1 CPUs using Node version 16 . 

![image](https://user-images.githubusercontent.com/52662201/205918681-3190df17-5f91-479d-976d-8b67a22e1c58.png)

**Comment by rijkvanzanten** [comment]
@luojiegithuber I'd highly recommend using Docker to run Directus. If that's not possible, make sure to reinstall the node modules when you switch node versions with `nvm`, as the specific native extensions for the dependencies might not exist if you installed the dependencies in a different node environment

**Comment by rowild** [comment]
When running the Docker directus then postgis will not be compatible...
