### ISSUE TITLE
Insights dashboard - List panels no longer link to listed collection items.

### ISSUE THREAD

**Issue by DhiaPhntm** [directus/directus#15915]
### Describe the Bug

This was originally reported to Cloud support who suggested submitting this as a bug.

Noticed recently that List panels created in an Insights dashboard no longer link to the displayed collection item where they used to link to the items a few weeks ago when we first looked at them. 

The relationship/filter is still valid as the collection item matches are displayed as expected. the List panel also no longer displays the 'add new' collection buttons.

(example of text only item display)
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/89022460/194566528-c74e956f-0fb0-443b-8fb3-7b4e9c12e887.png">

Have tried creating a new insight dashboard with no change. 

Issue is present on our Standard Cloud project (v9.18.1), the Insights feature update in 19.8.0 could be related.

### To Reproduce

- Create a new Insights dashboard
- Create a new `List` panel, add a related collection that contains items
- the listed items should be links to open the edit interface of the selected item.

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

N/A

### What database are you using?

N/A

### What browser are you using?

Chrome

### How are you deploying Directus?

Standard Cloud

**Comment by w0kyj** [comment]
Can confirm this issue in my cloud demo instances also. Insights List Panel items are not linked to the source items in 9.18.1

**Comment by br41nslug** [comment]
This was changed in 9.13 with the release of insights 2.0 https://github.com/directus/directus/pull/14096 although i couldn't trace back in what version the "add new" button was. I've re-implemented the click through optionally which you can enable in the panel settings.
![image](https://user-images.githubusercontent.com/9389634/194872632-b2915b63-5645-4ac6-8807-dc923f6385ad.png)
