### ISSUE TITLE
App: Sorting current collection by using a nested field throws an error

### ISSUE THREAD

**Issue by ALAiello** [directus/directus#15914]
### Describe the Bug

**Expected**
When using a nested field in a collection to sort it, it should sort the collection correctly by nested field.

**Actual**
When using a nested field in a collection to sort it you get an error message

### To Reproduce

Add translation to a collection
Add field to translation
Create element of collection
Create multiple translations for field
Go to App and add nested field of translation to table
Sort by nested field => probably nothing happens
Reload page => see error

### Errors Shown

`[INTERNAL_SERVER_ERROR] select "article"."isFaq", "article"."status", "article"."id" from "article" where not "article"."status" = $1 order by "izrgb"."title" asc limit $2 - missing FROM-clause entry for table "izrgb"
`

### What version of Directus are you using?
- 9.18.1 (Cloud)

### What version of Node.js are you using?
- Cloud

### What database are you using?
- Cloud

### What browser are you using?
- Chrome

### How are you deploying Directus?
- Cloud

**Comment by licitdev** [comment]
Sorting of nested multi relational values in O2M fields such as translations is currently unsupported. Ref: https://github.com/directus/directus/discussions/13239
PR https://github.com/directus/directus/pull/14798 attempts to add support for the sorting of such multi relational values.
