### ISSUE TITLE
Cannot add new items with related files or images via APP (FORBIDDEN ERROR, it worked before yesterday)

### ISSUE THREAD

**Issue by mmmaxxxe** [directus/directus#15929]
### Describe the Bug

A user for a specific role, adds a new item with an O2M field to file uploads
1) when files are bigger than 1 MB the user receive a 413 error
2) if files are smaller, the upload works, but when saving the item the user receive a FORBIDDEN error.

Please note that the configuration worked flawlessly before saturday for sure.

### To Reproduce

too difficult, cannot export database because i'm in cloud

### Errors Shown

FORBIDDEN when saving a new item

### What version of Directus are you using?

9.8.1

### What version of Node.js are you using?

Cloud

### What database are you using?

Cloud

### What browser are you using?

Brave

### How are you deploying Directus?

Standard Cloud

**Comment by br41nslug** [comment]
Should be the same issue as https://github.com/directus/directus/issues/15927 it is being worked on.
