### ISSUE TITLE
Flows - if a condition is on a property that doesn't exist, it's regarded as success

### ISSUE THREAD

**Issue by LevinGermann** [directus/directus#15937]
### Describe the Bug

We have a flow which should insert new entries in a table if an image got uploaded in the "review" folder.

![image](https://user-images.githubusercontent.com/9347206/195071622-00452acb-9696-4d3e-a688-4f066e262f6f.png)

The filter happens on the $trigger payload object:
```
{
    "$trigger": {
        "folder": {
            "_eq": "16df09d7-ff87-447b-8ee6-b6c7638ea72a"
        }
    }
}
```

This works fine when files get uploaded manually in the media library, but it seems to fail when the images are uploaded as part of other items in the DB. (e.g. via file-upload as an attachment on a "city"-table)
In this case, the files land in the root folder, and the flow gets triggered without a "folder" property:

![image](https://user-images.githubusercontent.com/9347206/195072108-36dca619-6d33-4f9d-83da-1152dd6bf6e6.png)

For some reason, the flow allows this and thinks this is okay and therefore continues with the flow...

![image](https://user-images.githubusercontent.com/9347206/195073017-833653c4-9936-482c-8b02-3a631393966e.png)

In my opinion, there are two bugs:
1. The payload of the trigger in an upload-case should always contain the folder property, since this is also the case when manually uploading files into the root folder.
2. A condition shouldn't continue if the property-check is done on a property that doesn't exist. Note that even with a not null check (_nnull) I wasn't able to catch this. 

### To Reproduce

1. Create a flow with the above condition (modify the folder UUID obviously)
2. Upload a file via another collection "embedded"
3. The flow triggers without a folder property, and the flow ignores that the condition doesn't even match.

### Errors Shown

No errors

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

v16.7.0

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Should be the same issue as #14571 👍
