### ISSUE TITLE
A regular user should not be allowed to edit an M2M item when the collection has no editing access for his role

### ISSUE THREAD

**Issue by Pachat** [directus/directus#15962]
### Describe the Bug

When clicking on the name of any of the M2M field, the related collection is opened despite the related collection has no editing access.
The opening throws the error "You don't have permission to access this."
But editing and saving the related item is still possible.
After coming back to the main item, it throws "You don't have permission to access this." and cannot be saved.

So saving is prevented, but not editing as it should be.
**I would like even then M2M collection item not to be shown.**

_May I add that unckecking the fields the user can read has no effect: he still sees the all, including `users in role` and even the custom fields_

### To Reproduce

1. Create an M2M field (in my case, it was `roles `in `directus_users `M2M to `directus_roles`)
2. For the role of this regular user disable editing on `directus_roles`
3. Allow editing on the M2M field in `directus_users `(to be able to add a `role `to `roles`) and check the field `roles `in editing permissions of the role.
4. In the form (in my case, the user form), add some `roles`.
5. After saving, back in the form, click on any of the `roles`.
=> `You don't have permission to access this.`
6. Edit the role, click on Save
7. Click on Save of the user
=>`You don't have permission to access this.`

### Errors Shown

Being able to edit a not allowed to edit collection
Then getting `You don't have permission to access this.`

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.14.0

### What database are you using?

Postgresql 14

### What browser are you using?

Firefox and Edge

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
Linear: [ENG-166](https://linear.app/directus/issue/ENG-166/a-regular-user-should-not-be-allowed-to-edit-an-m2m-item-when-the)
