### ISSUE TITLE
"Nothing changed, nothing saved" Multiple Files Re-order

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1599]
Going to a edit page and and changing the order in a Multiple Files interface (and then saving) is showing:

`Warning: Nothing changed, nothing saved`

Obviously we need to track these re-orders as a change. Even if you change something else so that is doesn't give the warning... the new order is NOT saved.

**Comment by WellingGuzman** [comment]
True, I will remove that flag now, we do not have the relational changes that sophisticated, to know when the order changes, don't know if you want to close it or let it open until we manage to get this to the proper solution, or move it to unsaved changes ticket (#1476).

**Comment by benhaynes** [comment]
OK, let me know when I can test re-order/save for those...

**Comment by WellingGuzman** [comment]
It should be working now!

**Comment by benhaynes** [comment]
THIS works (though there are other issues with this interface still, in other tickets)
