### ISSUE TITLE
M2M "Choose" Overlay

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1600]
When clicking "Choose" on Multiple Files interface:

* We need the info button (disabled) for spacing
* We need to remove that right-sidebar space if the sidebar is not used/open
* Clicking the column headers to sort isn't working

<img width="1055" alt="screen shot 2017-06-19 at 7 45 59 pm" src="https://user-images.githubusercontent.com/522079/27310548-02fde382-5529-11e7-9397-adedcac42737.png">

**Comment by benhaynes** [comment]
This Right Sidebar spacing issue is also happening on Settings>Groups too... again, it's based on previous page settings. **This class (`body.right-sidebar-open-wide`) needs to be reset on EVERY page load to avoid this – the class should be added if the sidebar is open, and removed if it is closed.**

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/3987e81e55a7655fb62205f58439962eea306044
