### ISSUE TITLE
After running a blocking flow: Timeout acquiring a connection. The pool is probably full.

### ISSUE THREAD

**Issue by m1212e** [directus/directus#16009]
### Describe the Bug

After creating a blocking flow which sends a webhook request, and the triggering it, directus stops responding.
The console:
```
14:51:18 ✨ request errored GET 500 /extensions/interfaces/index.js 1m
14:51:18 🚨 KnexTimeoutError Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? 
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/directus/node_modules/knex/lib/client.js:307:26)
    at async Runner.ensureConnection (/directus/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/directus/node_modules/knex/lib/execution/runner.js:30:19)
    at async /directus/node_modules/directus/dist/middleware/check-ip.js:19:18
```

### To Reproduce

Not sure, but my installation is now broken so I can't really test it.

### What version of Directus are you using?

9.18.1 

### What version of Node.js are you using?

The one of the official docker image

### What database are you using?

sqlite

### What browser are you using?

firefox

### How are you deploying Directus?

Docker

**Comment by nickrum** [comment]
It would be very helpful if you could elaborate on why you closed the issue, so anyone else running into exactly the same issue knows how to solve it 🙂

**Comment by rijkvanzanten** [comment]
My best guess is something around `sqlite` + doing a database query outside of the transaction somehow

**Comment by m1212e** [comment]
Originally I thought this was caused by Directus. As it turned out, I enabled a flow and accidentially triggered a webhook request to build my app when a system collection got modified. This triggered loads and loads of builds which spammed by directus instance, which then stopped responding.

**Comment by mangeshchavan** [comment]
![Screenshot from 2022-10-19 13-26-15](https://user-images.githubusercontent.com/31240755/196631086-7514e8df-6d2f-46c8-8774-6f42e0c093da.png)




directus    | 07:31:32 ? KnexTimeoutError Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? 
directus    | KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
directus    |     at Client_PG.acquireConnection (/directus/node_modules/knex/lib/client.js:307:26)
directus    |     at async Runner.ensureConnection (/directus/node_modules/knex/lib/execution/runner.js:287:28)
directus    |     at async Runner.run (/directus/node_modules/knex/lib/execution/runner.js:30:19)
directus    |     at async validateDatabaseConnection (/directus/node_modules/directus/dist/database/index.js:151:13)
directus    |     at async waitForDatabase (/directus/node_modules/directus/dist/cli/commands/bootstrap/index.js:78:5)
directus    |     at async Command.bootstrap (/directus/node_modules/directus/dist/cli/commands/bootstrap/index.js:41:5)
directus    |     at async Command.parseAsync (/directus/node_modules/commander/lib/command.js:923:5)

**Comment by azrikahar** [comment]
@mangeshchavan would you mind sharing more context on this error? It'd also be better if you can create a new Q&A discussion describing what were the steps/actions you were performing prior to getting such error as it can be difficult to understand what's happening here without more info.

**Comment by supermx1** [comment]
Same issue here... Just started showing up in my pm2 logs

**Comment by azrikahar** [comment]
> Same issue here... Just started showing up in my pm2 logs

@supermx1 there can be a variety of potential causes which would depend on further info such as are you using SQLite or other db vendor, or could it be Flows or custom extensions that contains unnoticed /malformed logic which clogged the connection pool, as mentioned in the comment above: https://github.com/directus/directus/issues/16009#issuecomment-1279223116

It would be very difficult to follow up without any detail, so I'd highly recommend creating a separate thread in discussion detailing what does your current setup entails. It would also be very helpful if you can try to reproduce this on a fresh and minimal Directus instance so that we can possibly narrow things down! 👍
