### ISSUE TITLE
Import existing tables with Foreign Keys

### ISSUE THREAD

**Issue by mycaravam** [directus/directus#1601]
**Problem**: I have two tables i imported into directus DB - `clientes` and `images`. There is a Constraint like `ALTER TABLE images
ADD CONSTRAINT images_ibfk_1 FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE ON UPDATE CASCADE`

**Question**: Is there a way to display this relation with dropdowns like phpmyadmin?

![bildschirmfoto vom 2017-06-20 09 16 55](https://user-images.githubusercontent.com/4922951/27321194-8d301d02-5599-11e7-82fc-06308bf9c72b.png)

Labels: Question, Help wanted

**Comment by benhaynes** [comment]
Thanks @mycaravam – we're super busy (internally) with the 6.4 release right now but will get to this as soon as we have time!

**Comment by benhaynes** [comment]
This is a new feature/interface – so we'll follow our usual workflow process of submitting it for community review before integration. Therefore I've moved this over to FeatHub:

http://feathub.com/directus/directus/+113
