### ISSUE TITLE
Use UUIDs for all system data + default to UUIDs for new tables

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#16013]
UUIDs are better for export/import (because of upsert capability without auto_increment sequence conflicts).

This is definitely a breaking change, and a bit of a nasty migration.

**Comment by emrahnazif** [comment]
Also, it increases the security slightly as it is not possible to guess.

**Comment by LasseRosenow** [comment]
> Also, it increases the security slightly as it is not possible to guess. This should apply to conjunction tables as well.

This is not true. Guessing UUIDs is much mor possible than one would think.

See: https://medium.com/@crussell52/thank-you-for-taking-the-time-to-share-your-experiences-this-is-a-valuable-topic-f097fb7b91a1


If you want to have security, I think the best way to have UUID as primary key and then a second key for external use that would be a `hash` on top of the primary key.

The real primary key should `ALWAYS` stay private. Never expose primary keys.

**Comment by LasseRosenow** [comment]
Also please consider to store the UUID as primary key as for example `BINARY(16)` and not as string :) You probably know that already, but just want to make sure :)

**Comment by rijkvanzanten** [comment]
> This is not true. Guessing UUIDs is much mor possible than one would think.

I think they were mostly thinking about the fact that it's easier to guess id `6` if you know that the current ID is `5`, than to guess `616e1eac-244f-4cd9-a2d5-b58d9b2f3e5c` when you're on `68607fa3-547d-4637-b705-d827e3e1d806`, but yeah, definitely not a security device that should be relied on.

**Comment by emrahnazif** [comment]
> This is not true. Guessing UUIDs is much mor possible than one would think.
> 
> See: https://medium.com/@crussell52/thank-you-for-taking-the-time-to-share-your-experiences-this-is-a-valuable-topic-f097fb7b91a1

I agree with your comments. Thank you. 
But when I consider security, imagine you are running an e-commerce, and order ID's are auto_increment. This can make for competitors to "guess" the volume of your sales or number of customers etc. 

> If you want to have security, I think the best way to have UUID as primary key and then a second key for external use that would be a `hash` on top of the primary key.
> 
> The real primary key should `ALWAYS` stay private. Never expose primary keys.

the best way

**Comment by sksar** [comment]
this is the way. UUIDs are the way.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-164](https://linear.app/directus/issue/ENG-164/use-uuids-for-all-system-data-default-to-uuids-for-new-tables)

**Comment by kulogix** [comment]
At minimum, you could provide a config option to set the default data type for Primary Keys -- and also honor that choice for Junction tables.

Currently, even though I choose UUID-based IDs for all my own tables, when I create a relationship the auto-generated junction tables have id columns with integer -- and (at least in Postgres and CockroachDB) an integer or bigint sequence is added.  

This could be combined with another item raised in the issues (not sure if a feature has been logged yet) to support compound keys -- allowing junction tables (maybe based on unique relationship / single-entry option) to skip the ID and sequence entirely, and just use the 2 foreign keys as a compound key.

In the interim, I'm testing to see if I can manually edit the junction tables / sequences, and still have Directus function normally -- including cascading deletes, etc. Any guidance / prior research results would be much appreciated.

**Comment by kulogix** [comment]
Additionally, there are many other int/bigint-based sequences that are created by default -- which can possibly be changed to timestamp-based ordering or other non-colliding sequence types.  

This is important for distributed database environments, like CockroachDB.  For display / usability purposes , a numeric sequencing could still be calculated from the timestamps.  

Some edge case handling may be needed for scenarios where prior sequenced rows "all of a sudden" appear in the collection (either due to manipulation, or out-of-band activity being sync'd-in) -- especially when rules exist to enforce certain values/conditions on most recent vs prior records (e..g, revisions).

- directus_activity_id_seq
- directus_fields_id_seq
- directus_notifications_id_seq
- directus_permissions_id_seq
- directus_presets_id_seq
- directus_relations_id_seq
- directus_revisions_id_seq
- directus_settings_id_seq
- directus_webhooks_id_seq
- personas_files_id_seq

**Comment by flipswitchingmonkey** [comment]
Also, if possible we should be using uuid v7, since it is timestamped by and makes them sortable by default.

**Comment by rijkvanzanten** [comment]
@flipswitchingmonkey yeah! I've also been eyeing Snowflake IDs as an alternative, but it looks like UUIDv7 has the same benefits 🙂

**Comment by seanmangar** [comment]
I'd prefer the flexibility to specify the primary key if this does go ahead. Currently use bigint unsigned for an existing database we're using with Directus, which causes issues whenever Directus tries to create junction tables (perhaps this was fixed on newer Directus versions, we're on 10.12). 

From what I understand UUIDs on MYSQL can have non-negligible performance downsides though for writes. See more here: [UUID primary key in MySQL](https://planetscale.com/blog/the-problem-with-using-a-uuid-primary-key-in-mysql)

**Comment by rijkvanzanten** [comment]
@seanmangar This would only be for the internal system tables 👍🏻 You'd still be able to choose whichever you prefer for your own data 🙂

**Comment by rijkvanzanten** [comment]
While this is still on my want-to-have list, the large cost of implementation + risky migrations outweigh the small benefit of standardizing the system tables to UUIDs. If and when we'll rearchitect the system tables it'll be UUID first 🙂

**Comment by pageagency** [comment]
Has anyone had issues with high availability or clustered DB's because of these autoincrement id's?

**Comment by pageagency** [comment]
Has anyone run into any issues with clustering or HA because of the autoincrement tables?

**Comment by rijkvanzanten** [comment]
@pageagency Try asking on https://directus.chat instead. A two year old closed issue is probably not the place people are actively looking to answer questions 👍🏻
