### ISSUE TITLE
Project background image is not loading if served from subpath

### ISSUE THREAD

**Issue by NDev8** [directus/directus#16032]
### Describe the Bug

If serving Directus form a subpath (e.g. `https://example.com/cms/`), the assets get loaded without the subpath prefix.

The following examples show the actual and expected path when serving from `https://example.com/cms/`:
Expected: `https://example.com/cms/assets/ASSET_UUID`,
Actual: `https://example.com/assets/ASSET_UUID`

See also this comment in the pull request with might have broken this: https://github.com/directus/directus/pull/14650#issuecomment-1277393074

<hr>

If used with Nginx as a revese proxy, there is a quick workaround by serving only the assets also from the root path:
```nginx
# Pass only directus assets requested from root path also to directus
location ~* "^/assets/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}" {
	# Your proxy headers
	proxy_pass http://directus-upstream;
}
```

### To Reproduce

- Install a fresh Directus instance
- Configure `PUBLIC_URL` in `.env` to your domain (e.g. `PUBLIC_URL=https://example.com/cms/`)
- Serve it from a subpath with a reverse proxy (Nginx)
- Set a custom public background image
- Goto login page (image is not loading)

### Errors Shown

- Assets are not found in the browser

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.17.1

### What database are you using?

Any

### What browser are you using?

Any

### How are you deploying Directus?

running locally

**Comment by spawnrider** [comment]
Same issue for me

**Comment by licitdev** [comment]
This issue should only apply to `public_background`.

https://github.com/directus/directus/blob/3d6fcf360cd0f17e0f128357c241a7b41e9a66e2/app/src/views/public/public-view.vue#L130-L140

`public_foreground` and `project_logo` display fine when served from a subfolder as they utilises `v-image`.
