### ISSUE TITLE
New Item Info Button

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1604]
We should disable the info button (in header) when creating NEW items. But we need to then show the Status column (if it exists) in the main content area (first).

**Comment by benhaynes** [comment]
We can wait until after release for this – it is NOT super important.

**Comment by WellingGuzman** [comment]
If we disable the button and the user has a small resolution (<1200) it would hide the right pane, and unable to change the status value.

**Comment by benhaynes** [comment]
> But we need to then show the Status column (if it exists) in the main content area (first).

We would ONLY hide this button for NEW items. And we would force the status interface in the main content area (the sidebar would never be shown on NEW items because there is no useful info there except Status).

**Comment by WellingGuzman** [comment]
Oh sorry I completely misunderstood this, I thought you meant show it on the right pane.

All good!
