### ISSUE TITLE
Images on App front are not shown

### ISSUE THREAD

**Issue by Piteraguayo** [directus/directus#16040]
### Describe the Bug

After upgrading to 9.18.1, images and files are not shown on the App. If I inspect, I notice that a base64 is the value for the SRC images. On the previous version, it was an to the assets folder. The result of the bug is that not any image is shown at any place (collections edition, files menu, etc).

It is maybe related with this issue: https://github.com/directus/directus/issues/16032
But I'm not setting the PUBLIC_URL to a subfolder. My value for PUBLIC_URL is "/".

![Directus_files_error](https://user-images.githubusercontent.com/5360439/196398710-2d2c73c1-ff02-4ffd-a6e4-1524a9e2b4a9.png)

### To Reproduce

Install or upgrade to 9.18.1. Go to App -> File Library -> add an image.
After adding the image, in the file menu, the image appear as not existing. The SRC is a base64 value.
Editing whatever item on a collection with image, you can select the images (not shown on the display) and save without problem. But are not showing on the interface.

### Errors Shown

Refused to load the image 'data:image/png;base64,iVBORw0KGgoA..............

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

17.3.0

### What database are you using?

MYSQL

### What browser are you using?

Chrome, Firefox

### How are you deploying Directus?

locally

**Comment by br41nslug** [comment]
Do you mind sharing the complete error? `Refused to load the image ..... because.....` (assuming it is blocked by CSP maybe). And can you double check that the image files actually exist in the uploads folder?

**Comment by Piteraguayo** [comment]
Hi @azrikahar,
Here a screenshot of the complete console error:

![console_error](https://user-images.githubusercontent.com/5360439/196406928-e1d88ee1-aca3-4cec-bdea-bf8f89eadc35.png)

The CSP problem wa solved on previous versions adding the following on .env file: 
`CONTENT_SECURITY_POLICY_DIRECTIVES__IMG_SRC="array:'self',other_domains........."`

I have checked the image is inside assets folder and when browsing "https://domain/assets/image_id" the image is shown.

Thank you

**Comment by Piteraguayo** [comment]
Hi all, 
As @azrikahar gave the clue, it was a problem of CORS and I checked my CONTENT_SECURITY_POLICY_DIRECTIVES__IMG_SRC and added " data:" after the 'self' and now it's working.

So, my value on .env:

`CONTENT_SECURITY_POLICY_DIRECTIVES__IMG_SRC="array:'self' data:,other_domains........."`

On my side, this is resolved.

Thank you

**Comment by azrikahar** [comment]
Was just about to ask you to try adding it 😄 glad it's working! Marking this as resolved.

Additional note just for future readers stumbling upon this: 

Directus by defaults adds `data:` for imgSrc CSP over here:

https://github.com/directus/directus/blob/3d6fcf360cd0f17e0f128357c241a7b41e9a66e2/api/src/app.ts#L120

so it should be included when overriding it.
