### ISSUE TITLE
Image thumbnails do not appear when files uploaded manually

### ISSUE THREAD

**Issue by HemboPagi** [directus/directus#16046]
Hi, this is the issue I started to dicusss in #8950 .

So  maybe I have done something in wrong way but no thumbnails are created when browsing the Files Library -  full size images are loaded :
<img width="1073" alt="Screenshot 2022-10-18 at 09 13 16" src="https://user-images.githubusercontent.com/95413906/196349833-dacdaecf-cb77-4b61-94f1-96b6539517b4.png">
<img width="796" alt="Screenshot 2022-10-18 at 09 13 48" src="https://user-images.githubusercontent.com/95413906/196349940-df157640-b852-40d3-af57-99ef7c52fdb0.png">

I copied all the files manually to server with UUID based filenames and created also entries to Directus files table.

**Comment by br41nslug** [comment]
What type of images are the ones that are not loading thumbnails? Judging by the requests some do seem to work so i suspect it may have something to do with not being able to transform/render them.

**Comment by HemboPagi** [comment]
I have jpeg-s and tiff-s. Seems to behave the same way - loading full size images. So to display 25 thumbnails in File Manager it takes quite a long time as some images are over 10MB. An other screenshot where i waited 285 MB to dowload but only 3 images were rendered. When I clicked to the unrendered image, detail page opens also without the image. BUT, when I then click Edit-button, image appears right away.

<img width="2503" alt="Screenshot 2022-10-19 at 13 24 20" src="https://user-images.githubusercontent.com/95413906/196665796-cf1dc479-a685-4e8d-9a40-c679244a6f27.png">

**Comment by br41nslug** [comment]
Can you verify that the `key` parameter is added to the request? Can't see in the screenshot but it should look like this:
![image](https://user-images.githubusercontent.com/9389634/196676514-02010dbe-f59f-4ee8-950e-4f0bd41e233a.png)
Can you try an URL like that manually to see if it is the image processing library failing to scale them? `http://YOUR-DIRECTUS/assets/UUID?key=system-medium-cover` (you may need to add an `access_token` too)

There is hard check that prevents the fetched images from being rendered if they're over 5mb that explains why some smaller ones do get rendered.

**Comment by HemboPagi** [comment]
Hi, here is the test url: http://db.dl.tlu.ee/assets/003c65a6-4da9-4691-b37b-1e5a53bd877b?key=system-medium-cover  
And some more UUIDs for testing:
0026ee10-a922-4103-bdfb-0fb41892141c
ff7cbd20-7b5f-48bc-ab4e-c006d02d8b9f
00b0d8e8-a676-445a-a450-14510e405e6f

It is still downloading the full size image. All the requests seem to have a key included:
https://db.dl.tlu.ee/assets/00ab98b4-5f2b-4a13-b658-3595f3f8a5a4?key=system-medium-cover&modified=2022-09-23T11:38:48.000Z&download=true

**Comment by HemboPagi** [comment]
thanks! it was the mime-type as well as the image dimensions (some images over 10000px - archive stuff)
ps. i use iip image server (https://iipimage.sourceforge.io/) for image manipulation, super fast.
