### ISSUE TITLE
Replace `aws-sdk` with `@aws-sdk/client-s3` in `@directus/drive`

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#16059]
`@directus/drive` currently uses AWS SDK v2, which includes way more code than we need. For AWS SDK v3, AWS opted to ship individual client packages for the various services, meaning that we can vastly reduce the overall footprint of `@directus/drive` by switching to v3. That being said, every API call is done differently, so it's not just a drop-in replacement.

**Comment by davidecarlier** [comment]
Hi! Can I give this a shot?

**Comment by rijkvanzanten** [comment]
Sure thing @davidecarlier!

**Comment by rijkvanzanten** [comment]
Linear: [ENG-162](https://linear.app/directus/issue/ENG-162/replace-aws-sdk-with-aws-sdkclient-s3-in-directusdrive)
