### ISSUE TITLE
Possible to delete directus_presets directus_preset (meta)

### ISSUE THREAD

**Issue by autr** [directus/directus#16051]
### Describe the Bug

Hello! On 2 of 4 of my Directus instances I've been able to accidentally delete the global directus_presets, preset, for directus_presets.

This seems to have happened by clicking the checkbox in the table header - which seems to also delete this hidden preset (my guess: using '*' in the req, or maybe the preset is present in the table, but hidden).

Afterwards the directus_presets list page becomes not so useable, and difficult to rectify, because directus data and directus_presets is not selectable from the Collection field.

So a temporary fix is to tweak the presets view GUI to create a directus_presets entry linked to the user account as Scope - then change the Scope back to Global. 

### To Reproduce

Select all checkbox in list of presets and Delete

### Errors Shown

None

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

v12

### What database are you using?

PG

### What browser are you using?

WebKit

### How are you deploying Directus?

Ubuntu, Digital Ocean

**Comment by rijkvanzanten** [comment]
Correct me if I'm wrong, but this sounds like things are technically working as expected. You select the preset, delete the preset, and then the preset is gone 🤔 Are you asking to add some additional validation to prevent the deletion of a specific preset? If that's the case, lets open a new feature request discussion instead 🙂 

I'll reopen  this if i'm misunderstanding and this is a bug 👍🏻

**Comment by autr** [comment]
It's working how it should - _except_ - that Directus Collections and certain Fields are hidden away from the GUI, so it's not possible to recreate the original Preset. 😅
