### ISSUE TITLE
Error While Installing Directus on The Same Server (another user or schema)

### ISSUE THREAD

**Issue by lovatti** [directus/directus#16058]
### Describe the Bug

Hi!

I'm trying a new installation of Directus on an oracle server that already contains another Directus installation.

The error is because the select returns more than one line.

SELECT cols.column_name INTO PK_NAME  FROM all_constraints cons, all_cons_columns cols  WHERE cons.constraint_type = 'P'  AND cons.constraint_name = cols.constraint_name  AND cons.owner = cols.owner  AND cols.table_name = 'directus_fields';

This select should do another filter in the where clause
AND cons.owner = "the user or schema" equal the parameter DB_USER in the .env file

As I don't know the impact of this change...

I think the parameter DB_PREFIX removed in https://github.com/directus/directus/pull/688 should correct the problem if used for all the tables and objects created by Directus installation, including the default sequences, triggers and tables directus_users, directus_fields, directus_files and so on.

Is there another solution to run multiple Directus installations on the same server (different users or schemas)?

Thank you!

Bruno

npx directus bootstrap
15:41:15 ✨ Initializing bootstrap...
15:41:15 ✨ Installing Directus system tables...
15:41:17 ⚠️  Automatically generated name "directus_fields_collection_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
[Error: DECLARE PK_NAME VARCHAR(200); BEGIN  EXECUTE IMMEDIATE ('CREATE SEQUENCE "directus_fields_seq"');  SELECT cols.column_name INTO PK_NAME  FROM all_constraints cons, all_cons_columns cols  WHERE cons.constraint_type = 'P'  AND cons.constraint_name = cols.constraint_name  AND cons.owner = cols.owner  AND cols.table_name = 'directus_fields';  execute immediate ('create or replace trigger "directus_fields_autoinc_trg"  BEFORE INSERT on "directus_fields"  for each row  declare  checking number := 1;  begin    if (:new."' || PK_NAME || '" is null) then      while checking >= 1 loop        select "directus_fields_seq".nextval into :new."' || PK_NAME || '" from dual;        select count("' || PK_NAME || '") into checking from "directus_fields"        where "' || PK_NAME || '" = :new."' || PK_NAME || '";      end loop;    end if;  end;'); END; - ORA-01422: exact fetch returns more than requested number of rows
ORA-06512: at line 1] {
  errorNum: 1422,
  offset: 0
}

### To Reproduce

Try a new Directus installation on a server that already contains another installation of Directus.

### Errors Shown

[Error: DECLARE PK_NAME VARCHAR(200); BEGIN  EXECUTE IMMEDIATE ('CREATE SEQUENCE "directus_fields_seq"');  SELECT cols.column_name INTO PK_NAME  FROM all_constraints cons, all_cons_columns cols  WHERE cons.constraint_type = 'P'  AND cons.constraint_name = cols.constraint_name  AND cons.owner = cols.owner  AND cols.table_name = 'directus_fields';  execute immediate ('create or replace trigger "directus_fields_autoinc_trg"  BEFORE INSERT on "directus_fields"  for each row  declare  checking number := 1;  begin    if (:new."' || PK_NAME || '" is null) then      while checking >= 1 loop        select "directus_fields_seq".nextval into :new."' || PK_NAME || '" from dual;        select count("' || PK_NAME || '") into checking from "directus_fields"        where "' || PK_NAME || '" = :new."' || PK_NAME || '";      end loop;    end if;  end;'); END; - ORA-01422: exact fetch returns more than requested number of rows
ORA-06512: at line 1] {
  errorNum: 1422,
  offset: 0
}

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16

### What database are you using?

Oracle

### What browser are you using?

Firefox

### How are you deploying Directus?

locally

**Comment by ConnorSimply** [comment]
Are you trying to run 2 instances of Directus with different schemas using the same database or 2 different databases?

**Comment by rijkvanzanten** [comment]
> I think the parameter DB_PREFIX removed in https://github.com/directus/directus/pull/688 should correct the problem if used for all the tables and objects created by Directus installation

Just FYI, the linked pull request is 7+ years old, and was targeting a couple major versions before. Directus didn't support Oracle at all back then 🙂

**Comment by lovatti** [comment]
Yes. That one is very old but can be an option to allow multiple installations in the same server.

We can find other issues regarding DB_SEARCH_PATH too without a solution.

https://github.com/directus/directus/discussions/5395

Thank you!

**Comment by lovatti** [comment]
> Are you trying to run 2 instances of Directus with different schemas using the same database or 2 different databases?

Hello @ConnorSimply!

Yes. I'm trying to run 2 instances of Directus, each with a different schema (user) in Oracle, but in the same server.

I found discussions about DB_PREFIX and DB_SEARCH_PATH, but DB_PREFIX is old and DB_SEARCH_PATH did not work.

Any suggestion?

Thank you!

**Comment by rijkvanzanten** [comment]
Linear: [ENG-163](https://linear.app/directus/issue/ENG-163/error-while-installing-directus-on-the-same-server-another-user-or)

**Comment by paescuj** [comment]
This is not something which is currently supported, although it might be at some point in the future.
Therefore I'm closing this issue for now, thank you for the understanding!

**Comment by lovatti** [comment]
For anyone needing this..

Directus shows conflict errors of objects names only in the installation proccess. Because of knex.

I successfully use some different directus instances in the same database server by..

Installing a new directus instance in another database instance (not the main database instance). 

After that, I export the db objects script and recreate the clean database structure in the main database instance.

That works!

Bruno
