### ISSUE TITLE
tif image conversion

### ISSUE THREAD

**Issue by HemboPagi** [directus/directus#16068]
### Describe the Bug

TIF images are rendered as black in Directus App File Browser.

<img width="1193" alt="Screenshot 2022-10-20 at 07 24 37" src="https://user-images.githubusercontent.com/95413906/196856193-796f655d-948b-4f3b-a9ba-a531d0dddbc1.png">

Here are the request made by Directus:
https://db.dl.tlu.ee/assets/a0928c43-315e-4631-be4c-f61ffa0f0c1d?key=system-medium-cover&modified=2022-10-20T04:21:12.000Z&download=true
https://db.dl.tlu.ee/assets/c0d2ac87-e167-45e0-a682-e69cb318a9d0?key=system-medium-cover&modified=2022-10-20T04:21:14.000Z&download=true

Same image can be dispayed using the trasformation setup i have created for thumnails:
https://db.dl.tlu.ee/assets/a0928c43-315e-4631-be4c-f61ffa0f0c1d?key=thumbnail
https://db.dl.tlu.ee/assets/c0d2ac87-e167-45e0-a682-e69cb318a9d0?key=thumbnail

I have followed instructios (#16046) and set the ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION to 11000. Also checked the mime types. 

### To Reproduce

Upload TIF image via Directus App File Browser.
You will see black thumbnail instead of the image.
Test images i used:
Medium size - https://www.icloud.com/iclouddrive/0de-79pzgV2rPBQm3rk1BcRAQ#medium_10084x8146
Small size - https://www.icloud.com/iclouddrive/061osRRDOYaI4vyfDrMKB11Tw#small_4000x3231

### Errors Shown

Tested with the lates Brave browser (Version 1.44.112 Chromium: 106.0.5249.119 (x86_64)), and Safari (Version 16.0 (16614.1.25.9.10, 16614)). No other errors except in Safari  "Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy." 

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

14.18.2

### What database are you using?

Maria DB

### What browser are you using?

Brave browser (Version 1.44.112 Chromium: 106.0.5249.119 (x86_64)), and Safari (Version 16.0 (16614.1.25.9.10, 16614))

### How are you deploying Directus?

Directus runs at Uni server, set up manually

**Comment by br41nslug** [comment]
Important to note here is that neither Chrome or Firefox support TIFF format images (one would assume neither does Brave as it is a chrome based browser). Testing here should be limited to Safari.

**Comment by br41nslug** [comment]
It can do that using the `format` option but this is not done by default for the previews in the app.

**Comment by rijkvanzanten** [comment]
> It can do that using the `format` option but this is not done by default for the previews in the app.

Would be kinda nice to implement https://github.com/directus/directus/discussions/15918 and set format=auto by default on the system presets. That way, the browser is in charge of choosing the most optimized version of the preview image 🙂

**Comment by HemboPagi** [comment]
hello, any progress with that?

**Comment by rijkvanzanten** [comment]
Linear: [ENG-157](https://linear.app/directus/issue/ENG-157/tif-image-conversion)
