### ISSUE TITLE
Replace Jest with Vitest

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#16063]
We've been using `vitest` for new projects and it's been an absolute joy. It's more or less a drop-in replacement for `jest` and natively supports ESM. We should replace our current uses of Jest in the sub-packages and API for `vitest`

**Comment by DorianCBrwn** [comment]
I'd be willing to give it a shot. I'm still trying to wrap my head around the code base but this is basically updating the jest config files to vite.config, and updating the package.json files for the API and packages right?

**Comment by DorianCBrwn** [comment]
So I've gotten 13 tests to pass and 14 are still failing. The remaining 14 I'm having a lot of difficulty trying to resolve. I was wondering if anyone would like to pair with me and help out. I'm still writing out a full break down of what I've worked on and what errors I'm running into if that will help.

**Comment by rijkvanzanten** [comment]
Sure thing! Mind opening the changes so far as a Draft PR so others can take a look as well?
