### ISSUE TITLE
Filtering Users

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1606]
When filtering users, the global search input loses focus after processing. We fixed this on the normal Item Listing page... but we need to fix it on Users/Files too.

This is NOT a priority.

**Comment by WellingGuzman** [comment]
This issue should've been fixed by https://github.com/directus/directus/commit/7b3f5470eed1418b4883ad6defacfd14a00f27af

**Comment by benhaynes** [comment]
Works!

But the status checkboxes in the dropdown are NOT working still. No matter what you choose, all users are visible.

Also, we should update this table (`directus_users`) and the other system tables to use `status` instead of `active`.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/6a73fc7204b820436fc43033c781c0a9f5e9f93d
