### ISSUE TITLE
Unable to save m-2-m relationship when set manually

### ISSUE THREAD

**Issue by wasims1** [directus/directus#16089]
### Describe the Bug

We have a database with already-built m2m relationship between two tables. Because we want to inherit the relationship and not create new fields (one of the biggest weaknesses of directus currently in my opinion), we manually enetered the relationship between the two tables as follows:

- directus_relations (col1 represents collection1, and col2 collection2)
<img width="791" alt="CleanShot 2022-10-20 at 17 40 44@2x" src="https://user-images.githubusercontent.com/28712798/197064330-a157f0a2-b10a-4823-ac17-6174d918ec71.png">

- directus_fields:
<img width="1195" alt="CleanShot 2022-10-20 at 17 39 51@2x" src="https://user-images.githubusercontent.com/28712798/197064126-f26dfb64-9393-4739-b456-40beef638218.png">

- also made sure the m2m intermediary table is managed by directus as seen above

This results in the field showing appropriately in the model. However when i try to create new col1--col2 associations, it's NOT saving to the database...

I tried to create the relationship through directus interface on a dev environment, and it did work appropriately... I confirmed that the directus_relations, and directus_fields entries were identical to the manual entries...

### To Reproduce

create two related tables m2m, and try to connect them manually by editing directus_relations and directus_fields

### What version of Directus are you using?

9.3.0

### What version of Node.js are you using?

16.13.1

### What database are you using?

mysql

### What browser are you using?

chrome

### How are you deploying Directus?

docker

**Comment by rijkvanzanten** [comment]
Please upgrade to the latest version before opening a bug report 👍🏻 

>  Because we want to inherit the relationship and not create new fields (one of the biggest weaknesses of directus currently in my opinion)

Directus mirrors the foreign keys in the database, and doesn't require the creation of new fields if you don't want to. Do your table's columns that you're using as foreign key fields have foreign key constraints enabled?
