### ISSUE TITLE
Can't remove M2M related items if "status" column does not exist on the junction table

### ISSUE THREAD

**Issue by peremp** [directus/directus#1608]
## Version Info
  - Directus version and branch: 6.4.0 latest

## Steps to Reproduce
 1. Create a table "solutions", "problems" and "use_cases"
 2. Add numeric fields "solution_id" and "problem_id" to "use_cases"
 3. Add a M2M field into solutions, using "use_cases" as junction, and "problems" as right table.
 4. Create some random problems.
 5. Create a solution and SAVE.
 6. Edit the solution and try to remove some problem from the M2M list.

## Expected Behavior
The problem is removed from the list.

## Actual Behavior
Nothing happens.

Looks like the problem is here:

app/core/interfaces/relational/m2m/interface.js line 49.
```
        if (!statusColumnName) {
          statusColumnName = app.statusMapping.get('status_name');
          statusValue = app.statusMapping.get('delete_value');
        }

        attributes[statusColumnName] = statusValue;
        model.set(attributes);
```
app.statusMapping.get('status_name') returns undefined.
app.statusMapping.get('delete_value') returns undefined.

**Comment by benhaynes** [comment]
We should not require the `status` column on junction tables – in fact, we should not even use them on junction tables... we should ALWAYS plan on hard-deleting junctions to avoid confusion.

**Comment by peremp** [comment]
Not agree at all... sometimes the status column is useful on junction tables

**Comment by benhaynes** [comment]
You don't think that could get extremely confusing?

**This Item**: Published
**Junction Table**: Draft
**Related Item**: Under-Review

How do we represent this in the M2M Interface? Is it `draft` or `under-review`?

**Comment by peremp** [comment]
Imagine something like this:

**Problem** (this item): How to learn french (published)
**Solution** (related item): Duolingo (published)
**Use case** (junction table): How to learn french - Duolingo (draft)

The problem, how to learn french, can have X solutions.
The solution, Duolingo, can solve X problems.

If a web visitor suggest a new solution for the problem (a new use case), the draft status is useful to validate the use case before publishing it.

**Comment by benhaynes** [comment]
That use case makes sense... but the interface in Directus needs a way to show the status of TWO things then: the related item and the junction relationship. So for now this needs to be figured out at the design-level.

**Comment by WellingGuzman** [comment]
Can keep the conversation going 👍
