### ISSUE TITLE
The problem of Directus interaction with Redis

### ISSUE THREAD

**Issue by DKarulin** [directus/directus#16084]
### Describe the Bug

Hello guys,
I am using Directus(9.18.1) with Redis(6.2.6). 
The problem is that the SET that is defined through the `CACHE_NAMESPACE` variable is not cleared when the cache is cleared through the utility. And over time, directus does not delete the keys stored in `namespace: directus-cache`
And when the value in the SET becomes more than 1048576 elements and when redeploying or reloading the container, directus tries to delete the values in `namespace: directus-cache` but it fails and it crashes with an error.

![image](https://user-images.githubusercontent.com/60217384/197000730-7ebd9571-5a37-4b3f-8921-27e492d66e06.png)
![image](https://user-images.githubusercontent.com/60217384/197000842-1c889506-5bcb-4c69-be15-0d4cb520692f.png)

Is there any way to avoid this problem?

### To Reproduce

cache large amount of data more than 1048576 items in `namespace: directus-cache`. rebuild the project so that the command to delete values is executed in the namespace

### Errors Shown

![image](https://user-images.githubusercontent.com/60217384/197000730-7ebd9571-5a37-4b3f-8921-27e492d66e06.png)
![image](https://user-images.githubusercontent.com/60217384/197000842-1c889506-5bcb-4c69-be15-0d4cb520692f.png)

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

14.17.3

### What database are you using?

Postgres 13

### What browser are you using?

Chrome, Safari

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
This is a known issue in the package we rely on to do the cache manipulation: https://github.com/jaredwray/keyv/issues/455. 
There's actually an active engineering effort underway to move away from that package, which in turn should also resolve this problem 👍🏻

**Comment by DKarulin** [comment]
got it thanks.

**Comment by jaredwray** [comment]
Hi @DKarulin - we are also working on a rewrite of the redis storage adapter in Keyv. We are hoping to get this out in November 20223 which will solve this issue. 

Again, sorry for the hassle on this as this is a legacy problem with how we are handling name spacing.

**Comment by DKarulin** [comment]
@jaredwray thanks, I'll wait

**Comment by azrikahar** [comment]
@jaredwray I believe there's a typo with the year 😁 Appreciate the update!

**Comment by azrikahar** [comment]
Closing this in favor of #15178 👍
