### ISSUE TITLE
Validation errors do not show in O2M drawer

### ISSUE THREAD

**Issue by tenebrius** [directus/directus#16091]
### Describe the Bug

Validation errors no longer appear in the drawer. 
For example when creating an item in a O2M list. If a required field is not filled, the validation error does not appear. This is occuring on the main branch and not on 9.18.1

### To Reproduce

1. Use latest code from main branch
2. Create a collection team 
3. Create a collection players. Add a required field 'Name..  Add a M2O field for team. 
4. Add an O2M field for players in the team collection
5. Add a new team
6. In the O2M list of the team creation page, click 'Create New' so that the drawer opens to create a new player
7. Leave the required 'name' field blank and click save

Result : No errors are shown and drawer does not close

### Errors Shown

An validation error should show, but it does not

### What version of Directus are you using?

latest main branch

### What version of Node.js are you using?

18

### What database are you using?

SQLite 5.12.0

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
Linear: [ENG-156](https://linear.app/directus/issue/ENG-156/validation-errors-do-not-show-in-o2m-drawer)

**Comment by tenebrius** [comment]
> Linear: [ENG-156](https://linear.app/directus/issue/ENG-156/validation-errors-do-not-show-in-o2m-drawer)

This says I don't have permissions to access

**Comment by rijkvanzanten** [comment]
> This says I don't have permissions to access

It's a private issue tracker for the maintainer team 🙂 Allows us to keep track of long term planning and release strategy etc 👍🏻
