### ISSUE TITLE
directus_tables_delete_value_comment not localized

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1611]
## Version Info
  - Directus version and branch: 6.4.0

## Expected Behavior
Status interface settings modal shows instructions on the `Delete Value` option

## Actual Behavior
Status interface settings modal shows `directus_tables_delete_value_comment`

## Steps to Reproduce
 1. Alter the settings of the status interface in table settings

<img width="460" alt="screen shot 2017-06-21 at 10 05 01" src="https://user-images.githubusercontent.com/9141017/27373671-816b2388-5669-11e7-99aa-be1aa7b36d85.png">

**Comment by WellingGuzman** [comment]
This was solved before by setting the comment directly, I just localize the text with the fixed text.
