### ISSUE TITLE
latest docker version not match to the actual latest version 

### ISSUE THREAD

**Issue by NigmaX** [directus/directus#16121]
### Describe the Bug

trying to pull the image: "directus/directus:9.19.1" gives an error,
"manifest for directus/directus:9.19.1 not found"

### To Reproduce

try to manually pull the directus 9.19.1 with docker

### Errors Shown

manifest for directus/directus:9.19.1 not found

### What version of Directus are you using?

-

### What version of Node.js are you using?

-

### What database are you using?

-

### What browser are you using?

-

### How are you deploying Directus?

Docker

**Comment by NigmaX** [comment]
answered on Discord
"There are some fixes being worked on related to the docker workflow so might not get released until Monday"

https://discord.com/channels/725371605378924594/1019641731332976722/threads/1033438949454131200

**Comment by rijkvanzanten** [comment]
I also called that out in the release notes:

https://github.com/directus/directus/releases/tag/v9.19.1
