### ISSUE TITLE
Add a "blocker" during processing times

### ISSUE THREAD

**Issue by peremp** [directus/directus#1612]
## Version Info
  - Directus version and branch: 6.4.0 latest

Would be nice to have a "blocker" during processing times like we have in Directus 6.3.9.

The blocker gives feedback to the users and it also prevents them from unintended actions that could cause unexpected errors (like duplicated items).

**Comment by benhaynes** [comment]
I agree with this. Event over is important so we should make sure we finish processing before additional interaction. I'll plan on adding a blocker layer back into 6.4

**Comment by peremp** [comment]
I will do this. I was thinking on keeping the "loading" overlay (class="loading blocking") but with some transparency on the background.

Is it ok for you?

**Comment by benhaynes** [comment]
That sounds perfect! Re-using that loading pane seems like the best option.

Thanks @peremp!

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/0e9d14ee91cdb324a05fea5bd13f61180ca1c02b (PR #1675)
