### ISSUE TITLE
Translating the field not reverting without refreshing the app

### ISSUE THREAD

**Issue by koksikus** [directus/directus#16128]
### Describe the Bug

If you translate the field name, after removing the translation, it is not possible to return to the original name, the translation remains.

### To Reproduce

In the video below:

https://user-images.githubusercontent.com/90528895/197409274-27024a07-84ed-495b-ba78-b6ff3868b841.mp4

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.17

### What database are you using?

MS SQL

### What browser are you using?

Edge

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
It should still revert once you refresh the browser 👍 but can confirm it doesn't revert _without_ refreshing.
