### ISSUE TITLE
Not able to upload image - Issue with thumbnail generation

### ISSUE THREAD

**Issue by krishnam09** [directus/directus#1613]
Version Info:
Directus version and branch: 6.3.9
PHP version: php 7 (As per getdirectus/directus-base-layer:0.0.8)
MySQL version: 5.6.19-67.0
Web server: Apache
OS name and version: Debian - Jessie (As per getdirectus/directus-base-layer:0.0.8)

**Error Log below:**
[Thu Jun 22 11:34:00.718717 2017] [php7:error] [pid 2812] [client 10.14.113.40:65056] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 24576 bytes) in /var/www/html/api/core/Directus/Files/Thumbnail.php on line 49, referer: http://host_name/files/new **All the images are 800KB to 1.5MB.**

## Expected Behavior
Should be able to upload any image lessthan 2 MB

## Actual Behavior
Behaving as shown in the screenshot.

## Logs or Screenshots
<img width="1235" alt="screen shot 2017-06-22 at 11 37 14 am" src="https://user-images.githubusercontent.com/592451/27419550-2f51a226-573f-11e7-9dc3-f56782fc4c3c.png">

**Comment by WellingGuzman** [comment]
Hey @krishnam09, can you share your php memory limit and php max upload values.

**Comment by nithinga** [comment]
@krishnam09 Did you give correct permission for folders such as storage/uploads etc ?

**Comment by WellingGuzman** [comment]
@krishnam09 are you still experiencing this error, did you increase your php memory and upload limits?

I will close this ticket as highly due to php configuration, otherwise I will re-open the ticket.
