### ISSUE TITLE
Redesign password lost functionality

### ISSUE THREAD

**Issue by wittwerch** [directus/directus#1614]
## Version Info
  - Directus version and branch: 1283092fde80bf9238244aa98109f63e86155804
  - PHP version: 7.1
  - MySQL version: 5.7
  - Web server: Apache
  - OS name and version: Docker 

## Expected Behavior
As a user I expect a "password lost" link under the login button. Placing it under the login button is kind of a standard.

## Actual Behavior
The "password lost" link is placed inside the password input. I see two problems with that:
1. The user doesn't expect it there
2. It gets covered/overlayed by password managers (like LastPass)

<img width="324" alt="screen shot 2017-06-22 at 10 57 53" src="https://user-images.githubusercontent.com/1575445/27425900-3dda9f78-573a-11e7-82e7-5effb1f5d103.png">

**Comment by benhaynes** [comment]
This has been updated in 6.4 – 6.3.9 will be fixed by the PR above
