### ISSUE TITLE
Permission Error for select-dropdown

### ISSUE THREAD

**Issue by shi-rudo** [directus/directus#16153]
### Describe the Bug

Hello, 

after upgrading from 9.14.5 to 9.19.2 (at the same time also from postgres 14 to 15) im experience one error in one collection.
When I try to change the value of a `select-dropdown` field, the message `[FORBIDDEN] You don't have permission to access this` is shown to me. The user **is an admin user.** So far, I have only encountered this error in one collection, although we have many collections, so I cannot rule out the possibility that this also happens elsewhere.

- The failing collection is an translation collection of its parent collection
- The message is only shown once. 
- The second attempt is successful without showing an error message.
- The selected value is set even when the error message is shown.

the failing field from `directus_fields`
```
[
  {
    "id": 370,
    "collection": "entities_translations",
    "field": "status",
    "special": null,
    "interface": "select-dropdown",
    "options": {"choices":[{"text":"draft","value":"draft"},{"text":"published","value":"published"},{"text":"archived","value":"archived"}]},
    "display": null,
    "display_options": null,
    "readonly": false,
    "hidden": false,
    "sort": 4,
    "width": "full",
    "translations": null,
    "note": null
  }
]
```

collection `directus_permissions` is empty

from console on load
```
Failed: http://127.0.0.1:8883/items/entities/%2B?fields[]=title&fields[]=id
Failed to load resource: the server responded with a status of 403 (Forbidden)
```

from console on action 
```
index.dfa694ae.entry.js:22
GET http://127.0.0.1:8883/items/entities/%2B?fields[]=title&fields[]=id 403 (Forbidden)
```

Where should I look to rebuild the permission or where in the db can I fix this?

### To Reproduce

no possible

### Errors Shown

`[FORBIDDEN] You don't have permission to access this`

### What version of Directus are you using?

9.19.2

### What version of Node.js are you using?

16.13.1

### What database are you using?

Postgres 15

### What browser are you using?

chrome

### How are you deploying Directus?

docker

**Comment by br41nslug** [comment]
> http://127.0.0.1:8883/items/entities/%2B?fields[]=title&fields[]=id
If that is a GET request you are requesting a record from `entities` with the primary key `+` (`%2B`) which will throw a Forbidden error if that does not exist.

Can you check if `GET http://127.0.0.1:8883/items/entities?fields[]=title&fields[]=id` gives the same result?

**Comment by br41nslug** [comment]
Permission errors are often used as fallback in the codebase so it is most likely not an actual Permission problem but something like a missing or invalid record.

**Comment by shi-rudo** [comment]
`http://127.0.0.1:8883/items/entities?fields[]=title&fields[]=id `gives
```
{"errors":[{"message":"You don't have permission to access this.","extensions":{"code":"FORBIDDEN"}}]}
```

> Permission errors are often used as fallback in the codebase so it is most likely not an actual Permission problem but something like a missing or invalid record.

any idea where to look for? this happens when I create a new entry, not updating an existing one.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-152](https://linear.app/directus/issue/ENG-152/permission-error-for-select-dropdown)

**Comment by br41nslug** [comment]
Sorry for the long delay, is this still occurring for you @shi-rudo ?
If so do you happen to have any extensions/validation-rules/custom-permissions associated with that collection

**Comment by shi-rudo** [comment]
> Sorry for the long delay, is this still occurring for you @shi-rudo ?
> 
> If so do you happen to have any extensions/validation-rules/custom-permissions associated with that collection

Will check within the next days

**Comment by br41nslug** [comment]
This issue has been stale for a while, closing it for the moment until more information becomes available.
