### ISSUE TITLE
Placeholders/interpolations with curly braces in translations stopped working

### ISSUE THREAD

**Issue by u12206050** [directus/directus#16164]
### Describe the Bug

I believe due to this PR #15872 any placeholders I have in translated strings used in custom modules and interfaces aren't being replaced anymore.

eg. `Happy New Year {year}`
v9.18.1 = `Happy New Year 2023`
v9.19.2 = `Happy New Year {year}`

I believe it is due to special characters being html encoded.

### To Reproduce

Create a translation string with a placeholder for a variable you can specify later. eg. `new_year: "Happy new year {year}"
In a custom ui extension use the translation string eg. `t('new_year', { year: 2023 })`

Notice that the string doesn't translate properly.

### Errors Shown

Variables aren't injected.

### What version of Directus are you using?

9.19.2

### What version of Node.js are you using?

16.4.0

### What database are you using?

sqlite, mysql

### What browser are you using?

chromium

### How are you deploying Directus?

Locally GCP

**Comment by azrikahar** [comment]
> I believe due to this PR #15872 any placeholders I have in translated strings used in custom modules and interfaces aren't being replaced anymore.

Makes sense! #15782 took a naive approach to include all the characters listed in https://vue-i18n.intlify.dev/guide/essentials/syntax.html#special-characters, but definitely an oversight in terms of curly braces as they are commonly used for interpolations such as `t('my_translation', { my_key: 'my_value' })` as mentioned.
