### ISSUE TITLE
[BUG] "Save as Copy" Button No Longer Works After Update

### ISSUE THREAD

**Issue by AaronBeaudoin** [directus/directus#16186]
### Describe the Bug

I recently bumped our company Directus installation from v9.17.4 to v9.19.2. After updating, it seems that the "Save as Copy" button always fails.

<img width="302" alt="image" src="https://user-images.githubusercontent.com/26592486/198117418-e3c503b1-c859-4f03-bb7a-e757b08d0221.png">

It appears that the reason for this is that Directus no longer correctly gives the new item a new primary key.

<img width="415" alt="image" src="https://user-images.githubusercontent.com/26592486/198117603-9d5fd4d9-a219-4a2f-a8e4-6801ac30dea7.png">

The **ID** field is a UUID primary key and it isn't shown on the detail, per the default configuration.

The "Save as Copy" button is important for us because it allows us to update the status to "Draft" and, save a copy to work on, then eventually _promote_ the copy to "Published" copy, removing the original item.

### To Reproduce

1. Make a minimal collection with the default configuration.
2. Add a basic input field with the default configuration.
3. Create a new item in the collection and save it.
4. Modify the input field value and press "Save as Copy".

The button doesn't work. As far as I can tell, it no longer ever does under any circumstance.

### Errors Shown

See description above.

### What version of Directus are you using?

9.19.2

### What version of Node.js are you using?

From Directus 9.19.2 Docker Image

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Should be the same underlying cause in #15771 👍 Let's track it in the same issue.
