### ISSUE TITLE
Problems when adding a new column "Misc > User" or "System > User created"

### ISSUE THREAD

**Issue by peremp** [directus/directus#1618]
## Version Info
  - Directus version and branch: 6.4.0 latest

## Steps to Reproduce
 1. Go to /settings/tables/_tableName_
 2. Click on "Add a new column"
 
## Problems
- The "User interface" dropdown has a duplicated "Misc > User":
-- The first option has set the value to "directus_user" and it throws an SQL error when trying to "save".
-- The second one has set the value to "user". It can be saved, but if you create a new item, the field shows an "Unknown User" and you cannot interact with it. Same on item edition.

- When you have a "System > User created" column and you create/edit an item, the field is empty (only the label appears, but not the name/image of the editor). Since Directus has the _Created By_ and _Modified By_ on the right panel, maybe the label could be hide.

Also related to "System > User created": On directus 6.3.9 you can set the user as a visible column on the table view to see the thumbnail+username. On directus 6.4.0 you can't, the column does not appear on "Right panel > Columns"

**Comment by WellingGuzman** [comment]
I removed on interface and leave one, but that one it's used in users interface as internal interface to show the names of each user.

These interfaces were meant to assigned the current authenticated user to the interface. This is the same behavior as created user interface, so this is not needed anymore.

---
What we could do is create another interface specific to user: `single_user` and `multiple_users`, what do you think @benhaynes @rijkvanzanten?

The user interface needs a little make up.

**Comment by rijkvanzanten** [comment]
That sounds like a logical step forward. This would essentially just be a o2m and a m2m for user specifically right?

**Comment by benhaynes** [comment]
Yeah, I agree!

**Comment by WellingGuzman** [comment]
Exactly! (change `o2m` to `m2o`) pick one user or pick multiple users.
