### ISSUE TITLE
After last update (9.19.2), Directus logs out users after about 15 min. repeatedly.

### ISSUE THREAD

**Issue by bamboowonder** [directus/directus#16188]
### Describe the Bug

We changed nothing else in our configuration.   We use google apps only for logins.   The log shows an error about unauthorized user.  It's like suddenly the login cookies are only good for a short duration.   Our refresh token is set at the default 7days.
Any pointers or insight would be greatly appreciated!
thank you

### To Reproduce

google apps only for directus login
nothing changed in configuration except to update to 9.19.2

### Errors Shown

page reloads with prompt to login with google apps as though no user was logged in at all.   however if i F5 reload page again, it says a user by my name is already logged in, would i like to continue as that user.

### What version of Directus are you using?

9.19.2

### What version of Node.js are you using?

16.14.2

### What database are you using?

postgres 14

### What browser are you using?

chrome

### How are you deploying Directus?

CLI/npx

**Comment by silasabbott** [comment]
I'm also experiencing this with two new v9.19.2 installs through Cloudron using *at least* the default Administrator account in Safari

**Comment by sekhuat** [comment]
I'm also facing the same issue after upgrade to 9.19.2. I am using Chrome login with the default administrator. The system keep saying Session Expired after a short while.

**Comment by azrikahar** [comment]
Can you guys share what was the version you were on before the upgrade? Wondering if this could be related to the recent dependency updates in 9.19.0 and above, such as Axios 🤔

@silasabbott @sekhuat just to confirm, do you have any SSO setup in your case?

**Comment by dokime7** [comment]
> @silasabbott @sekhuat just to confirm, do you have any SSO setup in your case?

I have 2 instances of Directus, one with SSO enabled and one without, both are this problem.

**Comment by dokime7** [comment]
> Can you guys share what was the version you were on before the upgrade? Wondering if this could be related to the recent dependency updates in 9.19.0 and above, such as Axios thinking

For sure there is no issue before v9.19.0

**Comment by sekhuat** [comment]
> 

Mine is 9.18.1 before upgrade to 9.19.2. No SSO setup.

**Comment by shi-rudo** [comment]
same problem here on 9.19.2, NO SSO

**Comment by sekhuat** [comment]
Seem like this issue happened again when update from 9.23.1 to 9.23.3 without SSO.

**Comment by azrikahar** [comment]
> Seem like this issue happened again when update from 9.23.1 to 9.23.3 without SSO.

@sekhuat should be related to #17901, so feel free to add any `9.23.3` related findings in that issue 👍
