### ISSUE TITLE
Make token field optional for new users

### ISSUE THREAD

**Issue by wittwerch** [directus/directus#1619]
## Version Info
  - Directus version and branch: 61e0e0268f646e5879c48296b80625cc7fe3a10b
  - PHP version: 7.1
  - MySQL version: 5.7
  - Web server: Apache
  - OS name and version: Docker 

## Expected Behavior
Create a user and set the firstname, lastname, email and a password

## Actual Behavior
The dialog requires you to set a token. We have a lot of users that will never use that token, si I think it should be optional.

**Comment by WellingGuzman** [comment]
Hey @wittwerch, the column is unique, what we can do is auto-generate the token value, so you don't to worried about it, does that works?

Otherwise we have to discuss what's best to do.

**Comment by benhaynes** [comment]
@WellingGuzman – We can auto-generate through Directus. Does the token _need_ to be required or could it be optional?

**Comment by WellingGuzman** [comment]
If we auto-generate the token in interface or better yet we can also auto-generate on API, which doesn't require you to do it, but if the user forgot to do it, it generates a new one for you.

@wittwerch @benhaynes do you see this as something? good solution or?

I think this would be the way to go, as that column has to be unique, thinking about whether or not the user is going or allow to use it, that another subject we are open to discuss.

**Comment by wittwerch** [comment]
Does unique mean it can't be null? Speaking from a user perspective I think auto-generating the value would be fine.

**Comment by WellingGuzman** [comment]
Yes, it can be null, that could work, MySQL allows unique that allows null to have multiple records with `null`.

What do you think @benhaynes ?

**Comment by benhaynes** [comment]
`NULL`/Optional or Auto-generated/Required.. either way works for me!

**Comment by wittwerch** [comment]
I think Null would be the safer choice. No need to expose random generated tokens.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/4070f35b991cba41a0163a3469b03c3e1bea7939.

must upgrade the users table schema by running `bin/directus db:upgrade`
