### ISSUE TITLE
items.create action hooks triggered by `createMany` cannot query inserted items

### ISSUE THREAD

**Issue by appy-one** [directus/directus#16198]
### Describe the Bug

Action hook handlers on `some_collection.items.create` cannot query newly created records when they are inserted through `createMany`, because the hooks are triggered by `createOne` that runs in a nested, [unfinished transaction](https://github.com/directus/directus/blob/d6fce8d92a48a5983293ca0c04f9de84201ec405/api/src/services/items.ts#L263). Trying to query the inserted record using `readOne` will yield an "You don't have permission to access this." error because the transaction has not been committed yet. The only exception being the last record in the `createMany` batch.

I am aware that querying the created record is not needed in `items.create` hooks because they get the data in `metadata.payload`, but sometimes it is feasible to use the same handler for both `items.update` and `items.create` hooks. Also, the handler might need more data not available in the payload, such as db defaults for unset fields or related data from foreign key tables.

Note that this is not an issue when records are inserted using `createOne` because there is no nested transaction.

### To Reproduce

* add an action hook `action('my_collection.items.create', handler)`
* insert multiple records into my_collection using `createMany`
* Let `handler` query the record with the inserted primary key given in `metadata.key`
  * using `readOne`: `const row = await itemService.readOne(metadata.key)` --> throws "You don't have permission to access this."
  * using `readMany`: `const rows = await itemService.readMany([metadata.key]);` --> `rows.length === 0`

### Errors Shown

"You don't have permission to access this." when using `readOne`

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

docker

**Comment by azrikahar** [comment]
Just a note: this seems oddly similar to #11172 which was fixed on `9.16.0`.

**Comment by appy-one** [comment]
@azrikahar similar, but reproducibly present in current version. The solution would be to queue action hook callbacks in `createOne` if it is called from `createMany`, then execute them in `createMany` once its transaction finishes. If you want me to submit a PR for this, let me know.

**Comment by licitdev** [comment]
Yes, I could reproduce this issue in `createMany`.

I think the `bypassEmitAction` option could be added to `createMany`. However, an existing `bypassEmitAction` should passed along as one might be provided.

https://github.com/directus/directus/blob/2adbb3bfd27639b3af4453d4ffcdd3be59736dea/api/src/services/payload.ts#L705-L709
 
@appy-one Thank you for reporting and it'll be great if you could submit a PR. 👍 May I assign this issue to you?

**Comment by rijkvanzanten** [comment]
Linear: [ENG-150](https://linear.app/directus/issue/ENG-150/itemscreate-action-hooks-triggered-by-createmany-cannot-query-inserted)
