### ISSUE TITLE
User Roles not loading

### ISSUE THREAD

**Issue by wfriedman89** [directus/directus#16207]
### Describe the Bug

We have 1m+ users in Directus, they load ok (a bit slow but they load), however the roles aren't loading, it keeps "loading" with the skeleton effect (see screenshot) but they don't load. 

### To Reproduce

By simply navigating to the Users page, the roles fail to load every 

![User_Roles_Not_Loading_1](https://user-images.githubusercontent.com/109602228/198324264-80cf2fcd-56e3-4a68-97c4-7fa8204c3bd4.png)

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.17.0

### What database are you using?

13.4

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker - Directus Cloud

**Comment by br41nslug** [comment]
You mention "We have 1m+ users in Directus" but for reproduction im curious over how many roles these are spread out?

**Comment by wfriedman89** [comment]
4 or 5 but not many.

This is an error that can be seen in the browser dev tools.

![image](https://user-images.githubusercontent.com/109602228/199135337-306d23e2-34a4-4ba1-ab10-a0c3f7c536b8.png)

**Comment by br41nslug** [comment]
managed to create about half a million users without running into the issue so far :( Will push it further tomorrow.
![image](https://user-images.githubusercontent.com/9389634/199231514-bd199b2b-3b6c-4997-b3c7-335786a7fd67.png)

**Comment by licitdev** [comment]
> ![image](https://user-images.githubusercontent.com/109602228/199135337-306d23e2-34a4-4ba1-ab10-a0c3f7c536b8.png)

From this error screenshot, I think the issue here is due to a non-selection of fields, resulting in the `users` field being selected. Hence with a longer run time required, the proxy throws 502 after a set timeout.

I think we could fix this by selecting necessary fields instead of leaving it empty which has a default value of `*`.

**Comment by rijkvanzanten** [comment]
> I think we could fix this by selecting necessary fields instead of leaving it empty which has a default value of *.

We have a winner. It should only read the `id` and `name` fields for the role 👍🏻

**Comment by rijkvanzanten** [comment]
Also ref #12476
