### ISSUE TITLE
When using `npm init directus-extension` and selecting TypeScript, `npm run dev` doesn't update `dist/index.js`

### ISSUE THREAD

**Issue by AaronBeaudoin** [directus/directus#16209]
### Describe the Bug

When scaffolding a new Directus extension with `npm init directus-extension` and selection TypeScript as the language to use, `npm run dev` is essentially useless.

1. `dist/index.js` is generated initially, but if I make a change to `src/index.ts`, then `dist/index.js` remains unchanged. I need to restart the process to actually see any changes. This entirely defeats the whole purpose of `npm run dev`.
2. To make things even worse, if `npm run dev` is running and I _do_ update `src/index.ts`, then ~the process locks up such that it doesn't respond to <kbd>Ctrl</kbd>+<kbd>C</kbd>, so I have to completely close the terminal to end the process!~ Actually, it looks like it does eventually exit on its own but it take a _long_ time.
3. When initially running the command, I get this output, which may or may not be related:

```
❯ npm run dev

> directus-extension-test-4@1.0.0 dev
> directus-extension build -w --no-minify

⠇ Building Directus extension...preferring built-in module 'events' over local alternative at '/Users/aryse/Projects/directus/extensions/test-4/node_modules/events/events.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
⠋ Building Directus extension...Circular dependency: node_modules/joi/lib/index.js -> node_modules/joi/lib/cache.js -> node_modules/joi/lib/common.js -> node_modules/joi/lib/schemas.js -> node_modules/joi/lib/index.js
Circular dependency: node_modules/joi/lib/common.js -> node_modules/joi/lib/messages.js -> node_modules/joi/lib/template.js -> node_modules/joi/lib/common.js
Circular dependency: node_modules/joi/lib/common.js -> node_modules/joi/lib/messages.js -> node_modules/joi/lib/template.js -> node_modules/joi/lib/errors.js -> node_modules/joi/lib/annotate.js -> node_modules/joi/lib/common.js
Circular dependency: node_modules/joi/lib/common.js -> node_modules/joi/lib/messages.js -> node_modules/joi/lib/template.js -> node_modules/joi/lib/errors.js -> node_modules/joi/lib/common.js
Circular dependency: node_modules/joi/lib/template.js -> node_modules/joi/lib/errors.js -> node_modules/joi/lib/template.js
Circular dependency: node_modules/joi/lib/common.js -> node_modules/joi/lib/messages.js -> node_modules/joi/lib/template.js -> node_modules/joi/lib/ref.js -> node_modules/joi/lib/common.js
Circular dependency: node_modules/joi/lib/template.js -> node_modules/joi/lib/ref.js -> node_modules/joi/lib/template.js
✔ Done
Watching files for changes...
```

This issue does not seem to occur when scaffolding the extension with plain JavaScript instead, but I _really_ don't want to do that because for me the type safety of TypeScript is very important.

### To Reproduce

1. Run `npm init directus-extension`.
2. Select `typescript` as the language.
3. Run `cd <whatever-you-named-the-extension>`.
4. Run `npm run dev`.
5. Note that `dist/index.js` is created.
6. Note the warnings in the console.
7. Make a change to `src/index.ts`.
8. Note that `dist/index.js` is the same.
9. Hit <kbd>Ctrl</kbd>+<kbd>C</kbd> to try and end the process.
11. Wait 5 minutes or close the terminal.
12. Give up and use plain JavaScript.
13. Weep silently.

### Errors Shown

See output in description above.

### What version of Directus are you using?

9.19.2

### What version of Node.js are you using?

Docker Version

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by nickrum** [comment]
> 1. `dist/index.js` is generated initially, but if I make a change to `src/index.ts`, then `dist/index.js` remains unchanged. I need to restart the process to actually see any changes. This entirely defeats the whole purpose of `npm run dev`.

Looks to me like a regression that was introduced when updating some of our dependencies in `v9.19.2`. It's working fine in `@directus/extensions-sdk@9.18.1`. You might want to downgrad until the issue is fixed.

> 2\. To make things even worse, if `npm run dev` is running and I _do_ update `src/index.ts`, then ~the process locks up such that it doesn't respond to Ctrl+C, so I have to completely close the terminal to end the process!~ Actually, it looks like it does eventually exit on its own but it take a _long_ time.

I can't reproduce this on my end. For me, it's exiting immediately. Which OS are you running on?

> 3\. When initially running the command, I get this output, which may or may not be related:

Those are just warnings that can be savely ignored.

**Comment by AaronBeaudoin** [comment]
I'm on macOS.

I've downgrades until this issue is fixed.
