### ISSUE TITLE
"Manage Emails" in notification emails is not clickable 

### ISSUE THREAD

**Issue by paulleduc** [directus/directus#16211]
### Describe the Bug

The following text appears in the footer of all notification emails:

"Sent by the team at [app name]— Manage Emails"

But the "Manage Emails" part does not seem to be a link or clickable in any way

### To Reproduce

Create a Directus Notification via API with the recipient being a user that has email notifications enabled. 

Check out the email in Gmail in your browser or the Gmail app on your phone.

### Errors Shown

None

### What version of Directus are you using?

Directus Cloud (9.18.1)

### What version of Node.js are you using?

Directus Cloud

### What database are you using?

Directus Cloud

### What browser are you using?

Chrome, iOS Gmail app

### How are you deploying Directus?

Directus Cloud

**Comment by azrikahar** [comment]
Seems like notifications emails are using the base email template, which in turn uses the `url` variable to determine "Manage Emails" href value:

https://github.com/directus/directus/blob/72b5e5cbbb1df014a21c12b7005b3db974c3ee4d/api/src/services/mail/templates/base.liquid#L145

However in notifications service, there is no `template.data.url` being passed:

https://github.com/directus/directus/blob/72b5e5cbbb1df014a21c12b7005b3db974c3ee4d/api/src/services/notifications.ts#L43-L52

Whereas password reset emails and user invitation emails does include `template.data.url` respectively:

- Invite User

    https://github.com/directus/directus/blob/72b5e5cbbb1df014a21c12b7005b3db974c3ee4d/api/src/services/users.ts#L315-L325
    
- Password Reset

    https://github.com/directus/directus/blob/72b5e5cbbb1df014a21c12b7005b3db974c3ee4d/api/src/services/users.ts#L384-L394

---

@benhaynes Seems like "Manage Emails" was added during the email updates via #9921. Is there a particular context in relation to the app where "Manage Emails" should link to? Or could it be meant as "Manage Notifications", or maybe something along the lines of "Go to app"/"Go to dashboard"? Or perhaps the intention was "Manage My Email Preferences" (to allow said user to opt out for example)?  🤔

Sample email sent via Flows' Send Notification operation (which uses base template):

![image](https://user-images.githubusercontent.com/42867097/198503915-220a0cf6-1adb-4342-bd9d-e2e06348b757.png)

**Comment by benhaynes** [comment]
Yeah, since we don't have an "opt-out of emails" toggle for users yet, we should probably change it to say `Manage Your Account` and then link to their user details page. Eventually, we should add some options for which emails a user gets (comment mentions, platform updates, etc).

CC @rijkvanzanten @jabooth3  ... an interesting idea for allowing users to add themselves to our newsletter within the app (get platform updates).

**Comment by benhaynes** [comment]
Also, can we update that email HTML to ensure the logo box is always a square? It looks like it's collapsing shorter because of the bunny aspect ratio. @azrikahar

**Comment by paulleduc** [comment]
It probably makes sense to hide the Manage Email text all together for users who are not app-enabled (such as in my case), or perhaps at least making the URL configurable via the dashboard for the sake of Directus Cloud users.

**Comment by azrikahar** [comment]
> It probably makes sense to hide the Manage Email text all together for users who are not app-enabled (such as in my case)

Had the same thought in #16233 and the current PR does hide it when it is not possible to link to a user detail page (more so for #15829 which will make it possible to use templates when sending email, but the email can be generic and not an actual user), but you mentioned a great point with not app-enabled even if it's a legitimate user! Will add in that additional logic 👍 

> or perhaps at least making the URL configurable via the dashboard for the sake of Directus Cloud users.

That's an interesting idea!
