### ISSUE TITLE
Missing access to adjustFieldsForDisplays

### ISSUE THREAD

**Issue by u12206050** [directus/directus#16224]
### Describe the Bug

I've create a number of interfaces, layouts and custom modules. In most of them I allow using the template on a collection or a field to display values, however I don't have access to the `adjustFieldsForDisplays` function only the `getFieldsFromTemplate` which gets me 50% there.

I tried copying the `adjustFieldsForDisplays` function, but it requires the `displays` array which contains the list of registered displays, without which translations and other relational fields don't load correctly.

Currently I can load `getFieldsFromTemplate` from `@directus/shared/utils`. Could `adjustFieldsForDisplays` also be added?

### To Reproduce

Try to create a custom module or layout and try loading values from a template string :P

### What version of Directus are you using?

9.19.2

### What version of Node.js are you using?

16.4.0

### What database are you using?

sqlite, mysql

### What browser are you using?

chromium

### How are you deploying Directus?

Locally GCP

**Comment by u12206050** [comment]
Actually tried to create a PR for this and realised I could inject all extensions and get displays via that, so here it is for anyone else. Until `adjustFieldsForDisplays` is exposed by directus, you'll have to recreate it.

```
// adjustFieldsForDisplays.ts
import { inject, Ref } from 'vue';
import { DisplayConfig, Field } from '@directus/shared/types';
import { EXTENSIONS_INJECT } from '@directus/shared/constants';

export function getDisplay(name?: string | null): DisplayConfig | undefined {
	const { displays } = inject(EXTENSIONS_INJECT) as {
		displays: Ref<DisplayConfig[]>;
	};
	return !name ? undefined : displays.value.find(({ id }) => id === name);
}

export function adjustFieldsForDisplays(fieldsStore: any, fields: readonly string[], parentCollection: string): string[] {
	const adjustedFields: string[] = fields
		.map((fieldKey) => {
			const field: Field | null = fieldsStore.getField(parentCollection, fieldKey);

			if (!field) return fieldKey;
			if (field.meta?.display === null) return fieldKey;

			const display = getDisplay(field.meta?.display);

			if (!display) return fieldKey;
			if (!display?.fields) return fieldKey;

			let fieldKeys: string[] | null = null;

			if (Array.isArray(display.fields)) {
				fieldKeys = display.fields.map((relatedFieldKey: string) => `${fieldKey}.${relatedFieldKey}`);
			}

			if (typeof display.fields === 'function') {
				fieldKeys = display
					.fields(field.meta?.display_options, {
						collection: field.collection,
						field: field.field,
						type: field.type,
					})
					.map((relatedFieldKey: string) => `${fieldKey}.${relatedFieldKey}`);
			}

			if (fieldKeys) {
				return fieldKeys.map((fieldKey) => {
					/**
					 * This is for the special case where you want to show a thumbnail in a relation to
					 * directus_files. The thumbnail itself isn't a real field, but shows the thumbnail based
					 * on the other available fields (like ID, title, and type).
					 */
					if (fieldKey.includes('$thumbnail') && field.collection === 'directus_files') {
						return fieldKey
							.split('.')
							.filter((part) => part !== '$thumbnail')
							.join('.');
					}

					return fieldKey;
				});
			}

			return fieldKey;
		})
		.flat();

	return adjustedFields;
}
```

**Comment by Nitwel** [comment]
I agree, we should move that function to shared as it is very helpful in nearly any app extension. 👍

**Comment by rijkvanzanten** [comment]
Linear: [ENG-149](https://linear.app/directus/issue/ENG-149/missing-access-to-adjustfieldsfordisplays)

**Comment by Nitwel** [comment]
I tried it in the branch `fix-16224` but was not able to get it fully working. It was failing to inject the stores when changing the collection view from one to the other.

Because of that I'm gonna leave the `adjustFieldsForDisplays` in the app for now but if you have time for that you could look try to make it work and then create a PR for it. But for now I'd say this won't be moved to shared and keept in the app.
