### ISSUE TITLE
When having 2 flows with one being Filter, all of them are considered a filter

### ISSUE THREAD

**Issue by LevinGermann** [directus/directus#16249]
### Describe the Bug

I have 2 flows, one of them is an Action for the scope `items.create`, the other is a Filter for `items.update` and `items.delete`.
When I now create an object of a collection for which we have this flow, the `id` in the flow is undefined and the item is clearly in a "Blocking"-flow, even though the action for a "create" is set to Action (Non-Blocking).

### To Reproduce

Create two flows:
- Action for `items.create`
- Filter for `items.update, items.delete`

Now the flow will be awaited if you create a new item (and therefore have `undefined` as id of the new item).

### Errors Shown

No error

### What version of Directus are you using?

9.19.2

### What version of Node.js are you using?

v16.7.0

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by br41nslug** [comment]
Can you elaborate on the situation you are seeing? i have created 2 flows based on the description but am not seeing any blocking behavior on item creates. Could there be a relational update in the create action? Have you selected any core tables in the event scope?
![image](https://user-images.githubusercontent.com/9389634/199208430-cd762fdd-338a-45f4-baef-6b8f654ecce8.png)
![image](https://user-images.githubusercontent.com/9389634/199208447-1ad30846-d7a9-4897-a729-01ceb1304955.png)

**Comment by LevinGermann** [comment]
Hello @br41nslug , thanks for taking time to re-check this.
It seems I messed up somewhere and mistook a configuration - on re-testing everything seems to work fine...

Sorry for the trouble! This issue can be closed.
