### ISSUE TITLE
Datetime picker Turkish localization bug

### ISSUE THREAD

**Issue by usamecavga** [directus/directus#16247]
### Describe the Bug

When language set to Turkish; Datetime picker's time not working properly. Always hour is 00: and minute is day number. 

I attached screenshot below.

![image](https://user-images.githubusercontent.com/755857/199128437-50447fb4-ee06-43eb-acb8-ee35f0317300.png)

![image](https://user-images.githubusercontent.com/755857/199128940-0747fae2-a21c-4c58-bb3f-351d6da6401c.png)

In English it's working properly.

![image](https://user-images.githubusercontent.com/755857/199129190-983fe7e8-1a7b-4a2f-8837-aa4c697938ac.png)

### To Reproduce

Select user's language to Turkish and add Datetime picker with time enabled 24 hours.

### What version of Directus are you using?

9.19.2

### What version of Node.js are you using?

14.18.0

### What database are you using?

Postgres v14

### What browser are you using?

Chrome Version 106.0.5249.119

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment]
Looks like currently it's using an odd `SS:dd:ss` format (which mean `Fraction of seconds : day of month : second`):

https://github.com/directus/directus/blob/2adbb3bfd27639b3af4453d4ffcdd3be59736dea/app/src/lang/translations/tr-TR.yaml#L402-L409

but I believe it should be kept as `HH:mm:ss` as the App does use date-fns to format it based on locale. For an example such as:

![chrome_I24Ags035S](https://user-images.githubusercontent.com/42867097/199156648-6531dd0e-45ae-4766-9ec5-1c1ad6a28a64.png)

Here are the comparison:

| `SS:dd:ss` | `HH:mm:ss` |
|---|---|
|![](https://user-images.githubusercontent.com/42867097/199156675-6bf359fc-0885-4d88-b333-769f165dac3d.png)|![](https://user-images.githubusercontent.com/42867097/199156697-b87ad288-dde7-43b4-99f4-eefa4e0c61c9.png)|

@usamecavga would you like to correct this via [the Crowdin page for Directus](https://locales.directus.io/)?

**Comment by usamecavga** [comment]
Yes, you are right.

<img width="959" alt="image" src="https://user-images.githubusercontent.com/755857/199193798-d54428c1-73d2-4e45-a14a-e3bc5c0abfb6.png">

I am updating it.

Thank you for your help.

**Comment by usamecavga** [comment]
Can you attach Crowdin updates to next release? Some date-fn strings was missing, I updated them.

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten Can you attach Crowdin updates to next release? Some date-fn strings was missing, I updated them.

We merge those in every release 👍🏻
