### ISSUE TITLE
File is not removed from S3 on delete if filename_disk !~ id

### ISSUE THREAD

**Issue by bfour** [directus/directus#16241]
### Describe the Bug

- upload a file in directus (S3 as storage)
- manually change ID of directus_file entry
- when deleting file item in directus, physical files do not get removed from S3
---
- in same setup, file removal works just fine if the directus_file ID matches the S3 file name (omitting extension) (which probably rules out a permission etc. issue)
- images load just fine from S3, even when directus_file ID and filename_disk (without .extension) mismatch
- I'm assuming viewing and deleting should have the same logic in that regard. Generally I would assume the filename_disk field to determine the physical (S3) file we want to deal with, but it seems that on delete, directus looks for phsical files named <directus_file.ID<suffix>> instead of <filename_disk*<suffix>> (for images there can be thumbnails it seems, so there can be multiple physical files for one directus_file)?

### To Reproduce

- have S3 configured
- upload file or manually create directus_file entry
- change ID of directus_file entry
- delete file entry in directus

### Errors Shown

can't see any, checked deployment log

### What version of Directus are you using?

9.19.2

### What version of Node.js are you using?

unknown

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

railway.app

**Comment by rijkvanzanten** [comment]
Assets are generated based on the filename_disk, but the deletion approach for assets is (still) based on the primary key. This is a leftover from the fact that we only ever officially supported saving the files under their UUID. Seeing that there's bigger discussions ongoing on allowing the filename to stay as-uploaded, we should start moving in the right direction and start optimizing some of these pieces.

To be updated code for reference:

https://github.com/directus/directus/blob/5780bb174f114f66fbb68e53f71128607f073be0/api/src/services/files.ts#L56

**Comment by rijkvanzanten** [comment]
Linear: [ENG-147](https://linear.app/directus/issue/ENG-147/file-is-not-removed-from-s3-on-delete-if-filename-disk-id)
