### ISSUE TITLE
6.4.0 Interface Gallery

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1626]
@rijkvanzanten has the SQL generated for this, but we need to implement it in a way so that it works on install. This version will be more complex as it will showcase relational interfaces, including Translation.

**Comment by benhaynes** [comment]
* Junction tables should be hidden by default
* `children` table should be fake person names, or be called `countries`

What is the difference between `items` and `children`? Curious why we need both.

Could we add field comments describing each interface?

It takes a LONG time to load the Interface Listing view even though almost all the visible columns are non-relational. Shouldn't it only fetch the visible columns it needs to it's faster? (we can open a separate ticket for this)

This can wait, but when we have time I'd like to re-open this and add in dummy activity/comments for each item.

LOTS of Interface ToDos... I'll keep those individual/separate

**Comment by benhaynes** [comment]
Also, the `slug` should be directly under the text-input so it's clear how that pulls from the other column.

**Comment by benhaynes** [comment]
All section break interfaces should have the same text: "Section Break"

**Comment by benhaynes** [comment]
We can remove `single_image` since it's the same as `single_file`

We can remove `multiple_image` since it's the same as `multiple_file`

**Comment by benhaynes** [comment]
Fields should be named after their interfaces (eg: Many to One):

`Items`
`Item`
`Item Typeahead`

**Comment by WellingGuzman** [comment]
> `children` table should be fake person names, or be called `countries`
>
> What is the difference between items and children? Curious why we need both.

I just called it children because I didn't know what else should have been called, these are interfaces record "children", if you got better naming and example for O2M records, please shoot! I'm all ears.

`children` are O2M entries and `items` are for M2O and M2M entries, as I said couldn't figure it out a good example, so I just created random names, then we can rename it to whatever it's best next.

> It takes a LONG time to load the Interface Listing view even though almost all the visible columns are non-relational. Shouldn't it only fetch the visible columns it needs to it's faster? (we can open a separate ticket for this)

Yeah it should only fetch select the visible column, checking it out now.

**Comment by benhaynes** [comment]
Let's just call the tables: `countries` and `items`.

Once this and the other changes are made we can close this one.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/schemas-boilerplate/commit/ba5404a06f871af53d2d63ba8c812771c91f0e2b
