### ISSUE TITLE
Missing logs with Pino asynchronous logging

### ISSUE THREAD

**Issue by abdonrd** [directus/directus#16284]
### Describe the Bug

After update to `^9.19` (same with latest `v9.20.3`), `npx directus bootstrap` has no logs:

<img width="371" alt="Screenshot 2022-11-02 at 1 07 04 PM" src="https://user-images.githubusercontent.com/1007051/199555162-b681663b-0c2e-49fb-9b55-3944befc5c67.png">

Logs with `v9.18.1`:

<img width="513" alt="Screenshot 2022-11-02 at 1 09 14 PM" src="https://user-images.githubusercontent.com/1007051/199555788-ad57a049-ec69-4d7b-8286-d07b8d301e40.png">

### To Reproduce

Update to `^9.19` and run `npx directus bootstrap`.

### What version of Directus are you using?

9.19.2

### What version of Node.js are you using?

16

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

Running locally

**Comment by abdonrd** [comment]
Looks like something related with:

https://github.com/directus/directus/blob/e7ada1f173dc6756cce40743023a8873ed2623e2/api/src/cli/commands/bootstrap/index.ts#L14-L49

**Comment by abdonrd** [comment]
This is random. I share a video repeating the bootstrap step several times with different results:

https://user-images.githubusercontent.com/1007051/199585495-3b153af2-dbdb-4ab5-b82e-7d855fb7cf67.mov

Maybe related with the bootstrap CLI command?

https://github.com/directus/directus/blob/e7ada1f173dc6756cce40743023a8873ed2623e2/api/src/cli/commands/bootstrap/index.ts#L14-L49

**Comment by nicksergeant** [comment]
Also ran into this. I have no idea why it's failing, because there are no logs.

**Comment by azrikahar** [comment]
> Also ran into this. I have no idea why it's failing, because there are no logs.

@nicksergeant in the meantime, setting `LOG_STYLE=raw` should help surface any error logs that weren't rendered when using the default pretty log style 👍

**Comment by arpadgabor** [comment]
Can confirm this issue as well. In my case applying the database schema errored with exit code 1 and no logs, seems like `LOG_STYLE=raw` works in showing logs, will keep an eye out for any other issues.

**Comment by jarekcieslak** [comment]
We're seeing the same issue. Applying `LOG_STYLE=raw` helps to some extent
