### ISSUE TITLE
Cannot group fields into accordion - cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by jakobpevec** [directus/directus#16286]
### Describe the Bug

Hello!

I have multiple fields which i'd like to tidy up into accordions. When I drag and drop the raw group or a single field into accordion I get the following error:

[20:04:55] PATCH /fields/product_variation 500 255ms
0|directus  | [20:04:55] ERROR (20247 on 602453.cloudwaysapps.com): Cannot read properties of undefined (reading 'type')
0|directus  |     err: {
0|directus  |       "type": "TypeError",
0|directus  |       "message": "Cannot read properties of undefined (reading 'type')",
0|directus  |       "stack":
0|directus  |           TypeError: Cannot read properties of undefined (reading 'type')
0|directus  |               at FieldsService.updateField (/home/..../public_html/node_modules/directus/dist/services/fields.js:307:73)
0|directus  |               at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|directus  |               at async /home/...../public_html/node_modules/directus/dist/controllers/fields.js:93:9
0|directus  |     }

Until I re-open the data model editor, the fields are grouped in an accordion. When I open the data model editor it will reset it and place fields outside the accordion. Same happens with detail group.

Update: I've noticed that as soon as I add a raw group/accordion/detail group it becomes impossible to rearrange any fields.

Any ideas what's the issue?

Node version: 16.18.0
Directus version: 9.20.1
MariaDB version: 10.4.20-MariaDB-1:10.4.20+maria~buster-log

### To Reproduce

1. create a collection
2. create an accordion
3. create a raw group
4. create an input field inside a raw group
5. move raw group into an accordion -> error happens here
6. it seems normal after this point, but if you refresh the page or leave and come back to the collection editor it will remove the fields/group from the accordion

### Errors Shown

[20:12:48] PATCH /fields/product_variation 400 129ms
[20:12:55] ERROR (20247 on 602453.cloudwaysapps.com): Cannot read properties of undefined (reading 'type')
0|directus  |     err: {
0|directus  |       "type": "TypeError",
0|directus  |       "message": "Cannot read properties of undefined (reading 'type')",
0|directus  |       "stack":
0|directus  |           TypeError: Cannot read properties of undefined (reading 'type')
0|directus  |               at FieldsService.updateField (/home/602453.cloudwaysapps.com/wuuxpgavqw/public_html/node_modules/directus/dist/services/fields.js:307:73)
0|directus  |               at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|directus  |               at async /home/602453.cloudwaysapps.com/wuuxpgavqw/public_html/node_modules/directus/dist/controllers/fields.js:93:9
0|directus  |     }

### What version of Directus are you using?

9.20.1

### What version of Node.js are you using?

16.18.0

### What database are you using?

10.4.20-MariaDB-1:10.4.20+maria~buster-log

### What browser are you using?

Edge, Firefox, Chrome

### How are you deploying Directus?

Cloudways server, CLI installation, PM2

**Comment by azrikahar** [comment]
This should be the same issue as #16273 #16269, and should be fixed by #16270 in the latest patch version `9.20.3` 👍
