### ISSUE TITLE
UseItems composable loading ref 

### ISSUE THREAD

**Issue by MichaelFBA** [directus/directus#16285]
### Describe the Bug

When using the `useItems` composable in the directus extensions SDK the `loading` reference is set to false. This causes issues since the `items` is undefined when it is instantiated and we cannot rely on `loading` to conditionally render a component without adding some nasty watcher on `items`

### To Reproduce

In the example below `<SomeComponent>` will render and items will be initially empty until it eventually returns data, causing issues further down component tree
```
<template>
   <div v-if="loading">Loading</div>
   <SomeComponent v-else :items="items"/> 
</template>

const { items, loading } = useItems(ref('collection_name'), {
    fields: ref(['*']),
    limit: ref(-1),
    sort: ref(null),
    search: ref(''),
    filter: ref(null),
    page: ref(1)
});
```

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

18

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
This is working as intended. The items aren't being loaded immediately, once the actual loading starts, the `loading` ref is set to true 👍🏻
