### ISSUE TITLE
Secure "Remember Me" implementation

### ISSUE THREAD

**Issue by freen** [directus/directus#163]
Research indicates:
 * Making a session indefinite isn't a fantastic way to go, owing to the resulting:
   * paralysis of server-side session data garbage collection
   * increased exposure to session hijacking (they should expire on a regular basis, between 10 and 60 minutes)

These posts indicate that the best route is to have a OneToMany "remember_me" table, mapping user ids to random tokens. Allows for global session invalidation by user. Etc etc.

http://fishbowl.pastiche.org/2004/01/19/persistent_login_cookie_best_practice/
http://stackoverflow.com/a/11541271/739373

**Comment by benhaynes** [comment]
**[Migrated to FeatHub](http://feathub.com/directus/directus/+3)**

Please use the [Directus FeatHub](http://feathub.com/directus/directus) to vote for features or make new request. Accepted feature requests will be added to GitHub Issues.
