### ISSUE TITLE
Field Validation not working for nested values

### ISSUE THREAD

**Issue by arladmin** [directus/directus#16307]
### Describe the Bug

I have 2 collections:
A [fields: 'b'(M2O-B)]
B [fields: 'valid'(boolean)]

For field 'b' in A, i have set Field Validation as shown:
![image](https://user-images.githubusercontent.com/64059154/199777287-0f6b9bd0-a511-46bb-b8db-c07b7a2e05c9.png)

But, when i try to create an item in A, it fails:
![image](https://user-images.githubusercontent.com/64059154/199777617-9c7ff7ea-8b60-43c6-8dd9-0e42b1478cb3.png)

This error is generated regardless of the value set in 'valid' in B.

### To Reproduce

Stated above.

### What version of Directus are you using?

9.19.2

### What version of Node.js are you using?

-

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by br41nslug** [comment]
I cannot seem to reproduce this specific issue in v9.19.2. Could there be more steps involved? or was the related "valid" toggle not sent with the request?
![image](https://user-images.githubusercontent.com/9389634/200276254-2d25479e-5a1b-48c3-a6a1-7a42f480a304.png)
![image](https://user-images.githubusercontent.com/9389634/200276368-464e0f45-2eea-44a0-823c-dbec11b1fa27.png)

**Comment by arladmin** [comment]
> I cannot seem to reproduce this specific issue in v9.19.2. Could there be more steps involved? or was the related "valid" toggle not sent with the request? ![image](https://user-images.githubusercontent.com/9389634/200276254-2d25479e-5a1b-48c3-a6a1-7a42f480a304.png) ![image](https://user-images.githubusercontent.com/9389634/200276368-464e0f45-2eea-44a0-823c-dbec11b1fa27.png)

Could you also test it by trying to selecting a valid entry?

**Comment by br41nslug** [comment]
Ah i see it specifically throws this error  **only** when selecting an **existing** item. Which makes sense because the value is not sent with the request in that case thus cannot be validated against.

**Comment by br41nslug** [comment]
Im sure there are other discussions on this topic you could upvote/follow too https://github.com/directus/directus/issues/11775 but the long and short of it is, the field validation only validates incoming data and does not fetch extra data from the database. Because of this your validation is failing when selecting an existing item as only it's ID is passed in that case.
