### ISSUE TITLE
"[INVALID_PAYLOAD] Alias type cannot be changed" when adding conditions to a divider

### ISSUE THREAD

**Issue by tonyellow** [directus/directus#16315]
### Describe the Bug

Add a divider to one of your content models. Edit the field and go to conditions. Create any new condition and click save. You will get error: [INVALID_PAYLOAD] Alias type cannot be changed.

![Screenshot 2022-11-04 at 08 37 13](https://user-images.githubusercontent.com/8984917/199919089-7d80b408-3378-4017-8b3b-00e74fc7e2ed.png)
![Screenshot 2022-11-04 at 08 39 51](https://user-images.githubusercontent.com/8984917/199919117-20560a6f-583f-4eb0-95d5-89dde2e906f7.png)

### To Reproduce

see bug

### Errors Shown

[INVALID_PAYLOAD] Alias type cannot be changed

### What version of Directus are you using?

9.20.4

### What version of Node.js are you using?

v16.18.0

### What database are you using?

Postgres 15

### What browser are you using?

Chrome mac os x

### How are you deploying Directus?

locally npx

**Comment by joaopaulomoraes** [comment]
The same here!
