### ISSUE TITLE
Unable to change the uploaded image in "Single File" upload field

### ISSUE THREAD

**Issue by nithinga** [directus/directus#1632]
## Version Info
  - Directus version and branch: version/6.4 80b1acf048b930a63d5503eb415d98a2e61471fc
  - PHP version: 7.1
  - MySQL version: 5.7
  - Web server: Apache 
  - OS name and version: Docker ( Ubuntu )

## Expected Behavior
When editing the files in record, either by deleting and uploading the file or changing it by choosing "Choose existing", it should update the image without error.

## Actual Behavior
It is giving query errors or nothing to update error

## Steps to Reproduce
 1. Create a new table in Directus and add a "single file" upload field.
 2. Add a record with file to it.
 3. Try to change the image for already existing record.

## Logs or Screenshots
![screenshot from 2017-06-28 18 31 12](https://user-images.githubusercontent.com/18306604/27638413-cd9837ce-5c30-11e7-83ce-74be8210aaea.png)

**Comment by benhaynes** [comment]
Thank you for reporting this @nithinga – which version/branch of Directus is this happening in? The screenshot looks like 6.4 – are you on the latest?

**Comment by nithinga** [comment]
@benhaynes latest 6.4 branch

**Comment by WellingGuzman** [comment]
Hey @nithinga, this should've been fixed by https://github.com/directus/directus/commit/2f16e32ee1ebf7724ab56c8c1c608a98bce082dd

Try pulling the latest from 6.4 branch, otherwise we can re-open the ticket.
