### ISSUE TITLE
Save as copy not working

### ISSUE THREAD

**Issue by mmmaxxxe** [directus/directus#16326]
### Describe the Bug

Saving a copy of a record makes the button rotating and Directus just sits there doing noyhing
The autoincrement primary key is UUID

### To Reproduce

edit a record with a user that is not an admin
save as copy

### Errors Shown

No errors, the save button start rotating and directus sits there doing nothing.

### What version of Directus are you using?

9.20.3

### What version of Node.js are you using?

Directus Cloud

### What database are you using?

Directus Cloud

### What browser are you using?

Chrome

### How are you deploying Directus?

Directus Cloud

**Comment by azrikahar** [comment]
Should be the same issue as #15771 (#16186 also reported it for UUID) 👍
