### ISSUE TITLE
Getting error changing permissions

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1633]
Changing a table's permission is throwing an error:

![screen shot 2017-06-28 at 10 06 51 am](https://user-images.githubusercontent.com/522079/27641336-8e09e1bc-5be9-11e7-982f-43cfd9824cd2.png)

**Comment by benhaynes** [comment]
Also, if you refresh the page it doesn't save this change (the red delete permission)

**Comment by nithinga** [comment]
1. After creating a new group, try to add permission by click.
2. In the first click nothing happends, no error or log error.

**Comment by rijkvanzanten** [comment]
Hi guys! I pushed a commit which should fix it. Could you please pull the latest and check it out @nithinga @benhaynes? 🙂

**Comment by benhaynes** [comment]
This is solved – if there are other issues we can re-open.
