### ISSUE TITLE
Development logs are swallowed

### ISSUE THREAD

**Issue by jonlambert** [directus/directus#16331]
### Describe the Bug

It seems that errors / logs are completely swallowed when cloning and running Directus locally. 

Could be related to #16284.

### To Reproduce

1. Run the following command:

```bash
git clone https://github.com/directus/directus directus-error && cd directus-error && pnpm i && pnpm -r build && pnpm --filter directus dev
```

This will clone the repo, install modules, build the whole project and run the API dev server; deliberately skipping the creation of a `.env` file. `KEY` should be missing from the environment (verify this with `$ echo $KEY`).

This will fail to boot when it fails to pass environment validation, but will emit no error 😞 

### Errors Shown

😄

### What version of Directus are you using?

9.19.2

### What version of Node.js are you using?

v19.0.1

### What database are you using?

n/a

### What browser are you using?

n/a

### How are you deploying Directus?

n/a

**Comment by jonlambert** [comment]
For those looking for a temporary local fix, replace [this line](https://github.com/directus/directus/blob/2d104e933b5e582caa5b72371231bab3e1d05357/api/src/logger.ts#L52) with: 

```ts
const logger = pino();
```

**Comment by jonlambert** [comment]
Related: #16299

**Comment by azrikahar** [comment]
> This will fail to boot when it fails to pass environment validation, but will emit no error 

It is definitely the same root cause, as mentioned here: https://github.com/directus/directus/pull/16299#issuecomment-1302807216. Let's keep track of this in the same issue #16284 (which should be updated to specify pino logging as a whole, rather than CLI specific).
