### ISSUE TITLE
nanoid security issue

### ISSUE THREAD

**Issue by tinchoz49** [directus/directus#16346]
### Describe the Bug

npm is reporting a moderate security issue

### To Reproduce

1. Install directus locally in your project.
2. run: npm install

### Errors Shown

```
nanoid  3.0.0 - 3.1.30
Severity: moderate
Exposure of Sensitive Information to an Unauthorized Actor in nanoid - https://github.com/advisories/GHSA-qrpm-p2h7-hrv2
fix available via `npm audit fix --force`
Will install directus@9.18.1, which is a breaking change
node_modules/nanoid
  directus  >=9.19.0
  Depends on vulnerable versions of nanoid
  node_modules/directus
```

### What version of Directus are you using?

9.20.4

### What version of Node.js are you using?

16.15.1

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by tinchoz49** [comment]
for now, using the version 9.18.1 solves the problem.

**Comment by rijkvanzanten** [comment]
nanoid output isn't used for any security related operations, so being able to reproduce the previously generated ID isn't a security vulnerability in our platform 👍🏻 

(also https://overreacted.io/npm-audit-broken-by-design/ 🙂 )
