### ISSUE TITLE
API post request using 'multipart/form-data' not working

### ISSUE THREAD

**Issue by whis** [directus/directus#16340]
### Describe the Bug

Directus API does not process multipart form data properly and fails to assign fields value. It works for uploading files but not for custom data models. When the form is converted to JSON and sent as a body, it works without issues.

### To Reproduce

1. Create a custom data model `car`.
2. Add a new string field `color`, and set it as **required** and **non-nullable**.
3. Make a **POST** request to create a new car using the `multipart/form-data` content type.
```shell
curl -H "Authorization: Bearer <bearer_token>" -X POST -F 'color=red' <app_url>/items/cars
```

Alternatively, you can use PowerShell and validate there is a problem processing multipart form data by converting it to JSON.
```shell
$uri = "<app_url>/items/cars"
$headers = @{ Authorization = "Bearer <bearer_token>" }
$form = @{ color = 'red' }

# Throws the error
Invoke-WebRequest -Method POST -Headers $headers -ContentType multipart/form-data -Form $form -Uri $uri

# Convert the form to JSON and send the request again with the OK result
$body = $form | ConvertTo-Json
Invoke-WebRequest -Method POST -Headers $headers -ContentType application/json -Body $body -Uri $uri
```

### Errors Shown

```json
{
  "errors":
  [
    {
      "message":"\"color\" is required",
      "extensions":
      {
        "code":"FAILED_VALIDATION",
        "field":"color",
        "type":"required"
      }
    }
  ]
}
```

### What version of Directus are you using?

9.20.4

### What version of Node.js are you using?

16.0.0

### What database are you using?

Postgres 13

### What browser are you using?

Firefox

### How are you deploying Directus?

Docker

**Comment by br41nslug** [comment]
While file uploads are done using `mulitpart/form-data` this method is not currently supported on the API beyond that. The API is JSON based and thus expects incoming data to be `application/json`.

> Directus offers both a RESTful and GraphQL API to manage the data in the database. The API has predictable resource-oriented URLs, relies on standard HTTP status codes, **and uses JSON for input and output.**

Reference: https://docs.directus.io/reference/introduction.html#api-reference

**Comment by whis** [comment]
Thanks for the prompt reply @br41nslug and the clarification! I can live without the support for `multipart/form-data` for now so I won't open a feature request for it. I thought it might have been a bug.
