### ISSUE TITLE
Custom edit permission are not replicated in Translations Interface

### ISSUE THREAD

**Issue by gerolds** [directus/directus#16344]
### Describe the Bug

Using the app,
given custom edit permissions on a translation collection,
when viewing the translation fields through the Translations Interface,
then the custom permissions are not replicated (all fields appear editable), which consequently also prevents saving (FORBIDDEN)

Similar issues come up when disabling create/delete on a pivot/junction table or the target table of a relation, which does _not_ cause the add/delete buttons in the app to disappear in interfaces that use this pivot/junction or target table, thus a user can create items which they then cannot save.

### To Reproduce

- Make a collection `foo`
- Add a translations field to the collection `foo`
- Add an input field `bar` and `baz` to the translations collection `foo_translations`
- Create a role which has custom/partial edit permissions on `foo_translations` (can only edit `foo_translations.bar`, and the relevant relation fields id, fk, lang)
- Using the role with custom permissions, edit field `foo_translations.baz` through the Translations Interface on `foo` --> permission denied

### Errors Shown

{
  "message": "You don't have permission to access this.",
  "extensions": {
    "code": "FORBIDDEN"
  }
}

### What version of Directus are you using?

9.20.4

### What version of Node.js are you using?

16.18.0

### What database are you using?

postgres 12

### What browser are you using?

Chrome

### How are you deploying Directus?

docker

**Comment by rijkvanzanten** [comment]
Linear: [ENG-142](https://linear.app/directus/issue/ENG-142/custom-edit-permission-are-not-replicated-in-translations-interface)
