### ISSUE TITLE
Unsaved Changes are ignored when the changes are in a sub-collection

### ISSUE THREAD

**Issue by LevinGermann** [directus/directus#16351]
### Describe the Bug

The unsaved changes are ignored when the changes are done in a sub-collection, and not on the collection item itself.
I added an example data-dump which contains the reproduction steps:

[data.db.zip](https://github.com/directus/directus/files/9960190/data.db.zip)
username: admin@example.com
password: password

https://user-images.githubusercontent.com/9347206/200541695-04a6e135-b04e-47c7-a514-8095b7d67a88.mov

### To Reproduce

1. Create a collection "order"
2. Create a O2M colleciton "order" -> "item"
3. Create translations on "item"
4. When creating a new order and adding an item, you can close the window while having unsaved changes

### Errors Shown

No errors

### What version of Directus are you using?

9.20.4

### What version of Node.js are you using?

v16.7.0

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by br41nslug** [comment]
Just to double check, the issue you're bringing up here is that you can quit a relational popup with changes without getting the "you have unsaved changes, confirm" popup?

**Comment by LevinGermann** [comment]
> Just to double check, the issue you're bringing up here is that you can quit a relational popup with changes without getting the "you have unsaved changes, confirm" popup?

Correct, yes! Sorry if I wasn't precise enough. :)
