### ISSUE TITLE
Unable to do multiple delete

### ISSUE THREAD

**Issue by nithinga** [directus/directus#1635]
## Version Info
  - Directus version and branch: version/6.4 - 80b1acf048b930a63d5503eb415d98a2e61471fc
  - PHP version: 7.1
 - MySQL version: 5.7
 - Web server: Apache
 - OS name and version: Docker ( Ubuntu )

## Expected Behavior
When trying to delete multiple records through directus, it should delete records.

## Actual Behavior
When trying to delete multiple records through directus, nothing happends. No error or error in log.

## Steps to Reproduce
 1. Try to delete multiple records

**Comment by WellingGuzman** [comment]
Hey @nithinga, this issue was fixed by https://github.com/directus/directus/commit/8730016146d3ebdde322c05cf55d97f72437b2e5
