### ISSUE TITLE
Table name not shown in delete info message

### ISSUE THREAD

**Issue by wittwerch** [directus/directus#1636]
## Version Info
  - Directus version and branch: 80b1acf048b930a63d5503eb415d98a2e61471fc

## Actual Behavior
![screen shot 2017-06-29 at 14 16 19](https://user-images.githubusercontent.com/1575445/27687071-aec8799e-5cd5-11e7-9732-171bc6b9e98d.png)

**Comment by WellingGuzman** [comment]
I see you are using the german translation, it seems the translation is a bit outdated, I will fix it in english but this should solve the problem and it will better be solved when one of the people that has help us with the german translation step in.

**Comment by wittwerch** [comment]
My native language is german, so I will try to translate the remaining strings.. :)

**Comment by WellingGuzman** [comment]
There we go :) thanks @wittwerch!
