### ISSUE TITLE
o2m interface sort field bug

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/directus#16376]
### Describe the Bug

We have the case where we have 2 collections (companies & contacts). The o2m interface on companies has set lastname as sort field. 

First of all the sort field is ignored, I think it is due to the fact, that it is clearly no integer field, despite I am able toselect it in the app. So the sort field is ignored in the interface. (the sort parameter is missing in the api call)

The second issue is, that when I use the possibility to sort the contacts in the o2m interface, it sets integer values for lastname of all items present. (seems like a visual bug in this case)

My understanding/expectation would be, that if I use a non integer field for sorting in the interface, manual sorting shouldn't be possible and the query should have `sort=lastname` included.

There is also an additional bug we encountered here: 

All contacts had `sort=NULL`, if the interface had a pagination, we had duplicate entries present, this was resolved by setting actual integer values in the sort field by manually sort the items via layout one time. This could maybe be prevented by adding something like this to the SQL Query:

```
order by IFNULL(sort, 1000000000), id;
```

### To Reproduce

Add 2 Collections, connect them via O2M and set a string field as sort field in the O2M interface.

### What version of Directus are you using?

9.20.4

### What version of Node.js are you using?

16.17.1

### What database are you using?

MySQL 8

### What browser are you using?

Chrome

### How are you deploying Directus?

linux vps

**Comment by MichaelNussbaumerGOWEST** [comment]
*edit: 

If I configure lastname as sort field in the contact collection itself, (by manually set the field) the layout has the same problem. It allows me to sort the items manually and it produces a 500 error.

![image](https://user-images.githubusercontent.com/15796397/200822475-84c8432b-6daf-40b7-bcb0-14663d4cc4b2.png)

**Comment by Nitwel** [comment]
We currently don't support non integer fields for sorting as it won't work with drag&drop. Thus I'm updating the field select to only allow for selecting integer type fields.

A thing you can do is to change the interface options of the o2m to the table layout, this gives you the possibility to sort for fields.
![grafik](https://user-images.githubusercontent.com/22577866/200855167-0a1ce7e1-35dd-472f-96f6-654acaa5357f.png)
