### ISSUE TITLE
'Interface option' for status field getting reset.

### ISSUE THREAD

**Issue by nithinga** [directus/directus#1637]
## Version Info
  - Directus version and branch: version/6.4 - 80b1acf048b930a63d5503eb415d98a2e61471fc
  - PHP version: 7.1
 - MySQL version: 5.7
 - Web server: Apache
 - OS name and version: Docker ( Ubuntu )

## Expected Behavior
After saving our custom status json in "Interface option", if we switch to 'Column setup' and save , both tab values should be saved.

## Actual Behavior
After saving our custom status json in "Interface option", if we switch to 'Column setup' and save , "Interface option" tab values gets reset or deleted.

**Comment by WellingGuzman** [comment]
This is a good request, it actually looks like one form with two tabs, but actually this is two form in one single view.

Thanks for the suggestion or pointing out my mistake whatever this is, I will be working on it soon.

**Comment by WellingGuzman** [comment]
Hey @nithinga,

This commit should fix this issue, or better word: implement a improved saving, avoiding the confusion (https://github.com/directus/directus/commit/70af164c9505284c2bc7df99906c8efd469d345b)
