### ISSUE TITLE
o2m interface (table) bugs (sorting, pagination)

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/directus#16389]
### Describe the Bug

1. If I have a o2m interface (table) and want to sort by a field in the interface (example sort by lastname), it only sorts the currently visible items on the page. I would expect to fetch the data with `sort=lastname` in that case.
2. In the same interface, (if you have 35 related items for example) navigate to the last page and change the page size to 100. Then you can't see any items.

### To Reproduce

O2M interface between two collections and add a some items and add a relation. Then try to sort by a field in the table, the order is only correct of the items already visible on the page. 

### What version of Directus are you using?

9.20.4

### What version of Node.js are you using?

16.17.1

### What database are you using?

MySQL 8

### What browser are you using?

Chrome

### How are you deploying Directus?

linux vps

**Comment by Nitwel** [comment]
The second one is for sure a bug but the first problem is not really a bug but a limitation we where willing to take for relational interfaces. The reason why we don't support sorting is because it would cause too many headaches as we would have to somehow inject local entries that where just created into the api response and still work in pagination and so on. We agreed on not supporting a global sort in favor of better maintainability and simplicity.

**Comment by MichaelNussbaumerGOWEST** [comment]
So it is because from interface created items would be "lost" kind of, ok.

@Nitwel: One question out of curiosity, why are created relational items not already created when u "save" the item in the drawer? If I understand that correct, this would make the global sorting possible as the item would exist in the api already. I ask as we were asked this questions already from a few of our customers, in some cases there are 2-3 drawers to open because of the complexity of the datastructure. Then you have to basically save 3-4 times until you really create items or apply a change.

**Comment by Nitwel** [comment]
We could go that route and it would simplify things a lot but it might be very unintuitive as you might not expect those changes to go live the instant you press save on a relational item. And there are probably some more reasons why we went with the current approach that I can't tink of right now.
