### ISSUE TITLE
Collection M2M alias not returning via REST API

### ISSUE THREAD

**Issue by paulleduc** [directus/directus#16403]
### Describe the Bug

I have a M2M relationship table between a custom collection called `events` and `directus_users`. The `events` table has an alias field for the relationship called `users`.

Authenticated with an admin user, I should be able to see the `users` alias field when fetching data for the `events` collection via the REST API. Any existing permission settings should be ignored because an admin user is being used. Regardless, I have tried providing full access temporarily to no avail.

No matter what I try with the API `fields[]` param, I am unable to see the `users` field within the `event` object returned. Specifying no filters or fields as API params at all should still display the existence of he `users` alias field, but no such field is returned. It's as if the field is simply not defined in the system. All other fields and relationships across my Directus instance work as expected, including similar M2M aliases.

The `events` collection with the `users` alias:
<img width="704" alt="Screen Shot 2022-11-10 at 2 18 16 PM" src="https://user-images.githubusercontent.com/1308031/201219815-2bf22f78-0dcf-4e69-8181-a42b76d39315.png">

The setup of the M2M relationship:
<img width="869" alt="Screen Shot 2022-11-10 at 2 16 32 PM" src="https://user-images.githubusercontent.com/1308031/201219821-3cccf0d6-133a-4999-968d-9e4be304a84c.png">

The results I get when fetching a single `event` with no `fields[]` defined:
<img width="485" alt="Screen Shot 2022-11-10 at 2 18 00 PM" src="https://user-images.githubusercontent.com/1308031/201219826-dc5e75e8-37b0-40ab-b0c1-7c99b30ae045.png">

### To Reproduce

You can try creating a similar collection->directus_users M2M relationship with an alias and testing the REST API as described, but this may be difficult to reproduce.

### Errors Shown

No field returned when expected

### What version of Directus are you using?

Directus Cloud (9.20.4)

### What version of Node.js are you using?

Directus Cloud

### What database are you using?

Directus Cloud

### What browser are you using?

Chrome

### How are you deploying Directus?

Directus Cloud

**Comment by br41nslug** [comment]
I have not been able to reproduce this using a `m2m` to `directus_users`.
Does the issue persist after clearing cache? or even after recreating the relation?

**Comment by rijkvanzanten** [comment]
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

---

I'd recommend reaching out to cloud support, as they'll be able to take a look at your actual project and troubleshoot from there :)
