### ISSUE TITLE
Dynamic variables don't get parsed inside _some and _none

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#16400]
### Describe the Bug

When using the variable `$NOW` inside `_none` it won't get parsed.

From the MySQL request: 
```
[....].`date_created` > '$NOW(-48 hours)')
```

I think the problem is inside the `parseFilterEntry` function that would need to know about the `_none` and `_some` operations:
https://github.com/directus/directus/blob/cc55d5608e9a39b0a8e876aecfb6c4331bae15e0/packages/shared/src/utils/parse-filter.ts#L49

### To Reproduce

Here's my complete filter as an example. I need to filter items that have no relations created within the last 48h. Once we replace the $NOW() variable with a static date everything works as expected.

Filter:
```
{
  "_and": [
    {
      "status": {
        "_eq": "published"
      }
    },
    {
      "_or": [
        {
          "count(<collection_name>)": {
            "_eq":"0"
          }
        },
        {
          "<collection_name>": {
            "_none": {
              "date_created": {
                "_gt" : "$NOW(-48 hours)"
              }
            }
          }
        }
      ]
    }
  ]
}
```

### Errors Shown

ER_WRONG_VALUE: Incorrect TIMESTAMP value: '$NOW(-48 hours)'

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

v16.15.1

### What database are you using?

MySql 8

### What browser are you using?

N/A

### How are you deploying Directus?

N/A

**Comment by licitdev** [comment]
Can confirm this issue on the current `main` branch. 
Issue is fixed within the query rework in https://github.com/directus/directus/pull/14798.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-141](https://linear.app/directus/issue/ENG-141/dynamic-variables-dont-get-parsed-inside-some-and-none)
