### ISSUE TITLE
"Required" columns not working

### ISSUE THREAD

**Issue by peremp** [directus/directus#1642]
## Version Info
  - Directus version and branch: 6.4.0 latest

## Expected Behavior
When a column is marked as required, the user shouldn't be able to create a new item if the required field is empty.

## Actual Behavior
The user can create items without filling the required fields.

**Comment by rijkvanzanten** [comment]
Hi @peremp! Is this an issue with certain interfaces or does it happen with every?

**Comment by WellingGuzman** [comment]
Yes, please, provide which interfaces this behavior happens, this probably is related to some specific interfaces, if it's @rijkvanzanten would take care of it.

**Comment by peremp** [comment]
Text input, slug, textarea, numeric... Haven't tried all.

**Comment by WellingGuzman** [comment]
Thanks @peremp, issue reproduced, I'm working on a fix.

**Comment by WellingGuzman** [comment]
Fixed by https://github.com/directus/directus/commit/cbc839435cec3c7f97ade674504ee79309e29b86
