### ISSUE TITLE
O2M unable to select existing M2O field

### ISSUE THREAD

**Issue by br41nslug** [directus/directus#16437]
### Describe the Bug

Using cockroachDB it is not possible to create the reverse relation to a M2O after the fact.

https://user-images.githubusercontent.com/26413686/200910989-2b02f801-5eaf-408e-b206-866659a56bed.mov

As it's not a problem when selecting the reverse relation on creation this must be on the frontend "disable field" side.

### To Reproduce

- Create 2 collections (collection A, collection B)
- Create a M2O relation from collection A to collection B
- Try to create the reverse O2M relation

### Errors Shown

Existing field is not selectable.

### What version of Directus are you using?

9.20.4

### What version of Node.js are you using?

16.x

### What database are you using?

CockroachDB

### What browser are you using?

firefox/chrome

### How are you deploying Directus?

docker

**Comment by kueronya** [comment]
It seems that the O2M foreign key dropdown selection is bugged.
I ran into the same issue running MySQL 8.0.29 and Directus 9.21.0, no matter if i created a M2O on the related table before.
All columns were greyed out, no matter if they were valid or not. 
I was able to work around, by typing the foreign key column name directly into the textbox.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-140](https://linear.app/directus/issue/ENG-140/o2m-unable-to-select-existing-m2o-field)
