### ISSUE TITLE
No visual feedback if thumbnail cannot be generated (e.g. image file too big)

### ISSUE THREAD

**Issue by fabianbeier** [directus/directus#16440]
### Describe the Bug

If an image is uploaded that is larger than the ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION no thumbnail is generated in the app. If you access the file via api you do get an error message: 

![SCR-20221114-oj7](https://user-images.githubusercontent.com/38300500/201717086-4a8962f8-226a-4ad3-9bc9-7912aa260743.png)

But in the app you only see a blank thumbnail and no image on the detail-page of the file:

![SCR-20221114-ojr](https://user-images.githubusercontent.com/38300500/201717296-63237737-928d-44e8-96a7-56583825c38e.png)
![SCR-20221114-ojz](https://user-images.githubusercontent.com/38300500/201717312-86822aca-0bbe-4e5d-a856-138d78be1625.png)

It would be great if there was an error-icon as a thumbnail and a message on the detail-page (e.g. "Thumbnail cannot be shown because the image is larger than 6000px" – if that info is available to the app). In the current version Clients/Users are confused why their images are not showing up. 

### To Reproduce

Upload an image file that exceeds ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION (default 6000px)

### What version of Directus are you using?

9.20.4

### What version of Node.js are you using?

v18.12.1

### What database are you using?

SQLite

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
Linear: [ENG-139](https://linear.app/directus/issue/ENG-139/no-visual-feedback-if-thumbnail-cannot-be-generated-eg-image-file-too)

**Comment by jay-p-b-7span** [comment]
@rijkvanzanten  I have successfully solved this issue and screenshots have been attached. Please have a look.

Screnshots
![image](https://user-images.githubusercontent.com/93135924/208240964-b5f91558-34cb-4f4a-85b6-b45b5f16a6ff.png)
![image](https://user-images.githubusercontent.com/93135924/208240974-e5ff174f-6742-48b4-bdcd-005eb99814c3.png)

PR #16843  Closes this issue.

**Comment by rijkvanzanten** [comment]
Awesome!
