### ISSUE TITLE
scrollbar bug

### ISSUE THREAD

**Issue by BrianRonin** [directus/directus#16451]
### Describe the Bug

error in the direct interface with the scroll bar every time there is an image

I didn't get to test better where this bug is coming from, but I know it's from the image because when I put display none in it, it solved it
![image](https://user-images.githubusercontent.com/55673280/201843340-4418b1bb-7248-4cd9-adf6-48f50c3621a0.png)

the image is svg
![saas-paas-iaas-diagram](https://user-images.githubusercontent.com/55673280/201847006-56e35042-7123-4bf4-957f-32c1952aa140.svg)

I have two monitors

I can give more information if necessary, I'm trying to explain the basics because I don't even know if you guys will care about this error

### To Reproduce

I had to crop the gif so maybe you can't understand. but the sidebar keeps crashing not letting it go up

![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/55673280/201845202-0f6cc5ba-955f-4655-af82-31ff31ed6ede.gif)

now that i noticed, it keeps varying rapidly between png and svg, but that only happens when i start to move up
![bug_directus_sd](https://user-images.githubusercontent.com/55673280/201849133-50f9b2c8-2909-4d80-827f-13e03885f90f.gif)

![image](https://user-images.githubusercontent.com/55673280/201849535-d900706c-327b-4295-9580-3d404e8b1a45.png)

### Errors Shown

none

### What version of Directus are you using?

9.20.4

### What version of Node.js are you using?

16.18.0

### What database are you using?

SQLite

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker local

**Comment by rijkvanzanten** [comment]
Do you see similar behavior for other file types? Does this happen on every browser? What version of Chrome are you using?

**Comment by BrianRonin** [comment]
my chrome version: ![image](https://user-images.githubusercontent.com/55673280/202866450-46cbced5-235f-4b98-ae1f-62379ddd779e.png)
Do you see similar behavior for other file types?:
I didn't get to do a deeper test, but I believe it's just with svg

**Comment by BrianRonin** [comment]
> Do you see similar behavior for other file types? Does this happen on every browser? What version of Chrome are you using?
![image](https://user-images.githubusercontent.com/55673280/202866543-76bbc231-d3b4-405c-be0e-4cebebb32ed8.png)
I didn't get to do a deeper test, but I believe it's just with svg, and this happens only when this modal on the right side is opened, I solved the problem here with the scroll bar just by removing the height of the svg image, but internally it is still changing quickly that element that I showed before
