### ISSUE TITLE
It doesn´t show any error message in the login when the email is correct and the password is wrong

### ISSUE THREAD

**Issue by jorgeflores** [directus/directus#1646]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests please use the [Directus FeatHub](http://feathub.com/directus/directus) to make a new request or vote for existing ones, or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues.

## Version Info
  - Directus version and branch: 6.3.9
  - PHP version: 5.6.30
  - MySQL version: MariaDB 10.1.21
  - Web server: 2.4.25
  - OS name and version: windows 10

## Expected Behavior

 In the log in, when I put a correct user email and wrong password, it should show a error message like "incorrect password or email".

## Actual Behavior

It doesn´t show any error message in the login when the email is correct and the password is wrong

## Steps to Reproduce
 1. Go to the the Log in Form
 2. Put a correct user email
 3. Put a wrong password
 4. Submit the form

**Comment by WellingGuzman** [comment]
Hey @jorgeflores thanks for the report, I believe this commit (https://github.com/directus/directus/commit/73af8df5e77ed9a298a11a3ea4dc36133bf863e9) should have fixed it.

Let us know.

**Comment by WellingGuzman** [comment]
Also fixed a bug created by the previous fix by this commit https://github.com/directus/directus/commit/39b701fdec4c34cfc1a272b5b1d50348ec68f53b
