### ISSUE TITLE
How to Creating new Tables with UTF8 charset?

### ISSUE THREAD

**Issue by canyousayyes** [directus/directus#1647]
## Version Info
  - Directus version and branch: 6.3.9
  - PHP version: 7.1.6
  - MySQL version: 5.7
  - Web server: (Ex. Apache, nginx or IIS?) Apache 2.4.10

## Expected Behavior
I have created some new tables using the interface. It does not give the options to choose / update the charset.

When I check the charset settings in DB, it shows `latin1`.

Example query executed to create table
```
CREATE TABLE `pc_artwork_tags` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `active` int(11) NOT NULL DEFAULT '2',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

Furthermore, my `/api/config.php` has the constant `define('DB_CHARSET', 'utf8');`

## Actual Behavior
I would like to create custom tables that follows the `DB_CHARSET` constant.
Or, having an option in UI to change table charset.

If this is not possible in the near future, please advise on how to create a custom DB migration.
(Or should I just run `ALTER TABLE` query by manual?)

## Steps to Reproduce
 1. Go to the Directus UI
 2. Create a new table under `/settings/tables`
 3. Check the DB schema charset (e.g. using SequelPro to connect to DB)

**Comment by canyousayyes** [comment]
Hmmm, it seems Directus has default charset = latin1 when settings up the database.
After I run `ALTER DATABASE directus DEFAULT CHARACTER SET utf8;`, all tables created afterwards are now utf8.

I wonder if it's possible to set database default charset when setup?

**Comment by WellingGuzman** [comment]
What table name are you trying to create and what's the end result?

The charset should be working, give me specific example to try to replicate this issue.

It seems you are talking about running the migration, but I'm not sure, let me know.

I noticed that we still clean the names in 6.4 whether or not the "strict naming" is disabled, that's a good catch, but still we have been discussing this for long time about wether or not directly support this.

@benhaynes I wonder if we should allow any table name using the API.

**Comment by directus-git** [comment]
Yeah, I am fine with no limitations on the API. It think it's only the
interfaces that might have users enter "friendly" names by accident.


Benjamin Haynes
*Founding Partner, Director of Technology*

RANGER Studio LLC
149 Cleveland Rd
New Haven, CT 06515

Mobile 1-224-444-9666
http://RangerStudio.com

**Comment by benhaynes** [comment]
Hey @canyousayyes – we've closed the issue with forced strict naming through the API. We can't replicate the database defaulting to `latin1`... if you can help us reproduce this we'll re-open and resolve!
