### ISSUE TITLE
Can't re-order M2A items

### ISSUE THREAD

**Issue by ImaCrea** [directus/directus#16470]
### Describe the Bug

I have set a M2A field related to 3 collections. It all seems to work except that I can't re-order them. I see on other screenshot that it should be possible. I wonder if it's due to a bug or something I'm missing in my configuration.

### To Reproduce

Create an M2A field linked to 3 collections.

### Errors Shown

I don't see any errors. But I don't see any handle on the interface which could let me re-order items:
![Capture d’écran 2022-11-16 à 10 49 40](https://user-images.githubusercontent.com/764332/202150501-4a0152f3-5734-4588-af81-85fbe25eb20e.png)

### What version of Directus are you using?

9.20.4 (cloud)

### What version of Node.js are you using?

dunno

### What database are you using?

dunno

### What browser are you using?

Firefox 106

### How are you deploying Directus?

Cloud

**Comment by Nitwel** [comment]
Goto `Data Model -> Your Collection -> Click your M2A Field`. Then you have to set the sort field in order to have drag and drop like on the image below.

![grafik](https://user-images.githubusercontent.com/22577866/202154694-16125e05-5d8c-40a0-97e9-d51695c9519a.png)

**Comment by ImaCrea** [comment]
Thanks!
