### ISSUE TITLE
Deleting the file in 'File library' removes the file but not DB entry.

### ISSUE THREAD

**Issue by nithinga** [directus/directus#1648]
## Version Info
  - Directus version and branch: version/6.4 - 0f0bd5f758b60ad3b640d8634dd8c3496ddb4566
 - PHP version: 7.1
 - MySQL version: 5.7
 - Web server: Apache
 - OS name and version: Docker ( Ubuntu )

## Expected Behavior
When deleting the file it should delete the file as well as DB entry.

## Actual Behavior
When deleting the file it delete the file but not the DB Entry.

**Comment by WellingGuzman** [comment]
We are not forcing hard delete on files until we implement a new option to decide whether to soft or hard delete a file.
- Hard-Delete: Deletes file and DB record.
- Soft-Delete: Keeps the file, sets the file status to `Inactive`

**Comment by benhaynes** [comment]
So how does it work now, @WellingGuzman?

**Comment by WellingGuzman** [comment]
Whoops! I meant to say **We are now forcing hard delete on files...**
