### ISSUE TITLE
'X' Close button in file preview popup is not working

### ISSUE THREAD

**Issue by nithinga** [directus/directus#1649]
## Version Info
  - Directus version and branch: version/6.4 - 0f0bd5f758b60ad3b640d8634dd8c3496ddb4566
 - PHP version: 7.1
 - MySQL version: 5.7
 - Web server: Apache
 - OS name and version: Docker ( Ubuntu )

## Expected Behavior
Clicking the 'X' Close button in file preview, should close the preview.

## Actual Behavior
Clicking the 'X' Close button in file preview, it will not close the preview. But clicking outside (overlay) the file preview closes it.

## Steps to Reproduce
 1. Add a file field in table.
 2. Add the new record with file.
 3. Click the uploaded file thumbnail, it will open the popup. Click the 'X' Close button in file preview, it will not close the preview. But clicking outside (overlay) the file preview closes it.

**Comment by WellingGuzman** [comment]
Fixed by https://github.com/directus/directus/commit/95bc9e8789502a5ef3adf815c03150b97ae16a13
