### ISSUE TITLE
Failed to create relation because collection doesn't exist

### ISSUE THREAD

**Issue by arpadgabor** [directus/directus#16503]
### Describe the Bug

Maybe I'm having a really bad day but... while trying to debug #16493 I started attempting to recreate the whole database see if it works. But now I can't get an empty database to initialize with the database schema.

Unfortuately for me, the `attachments` collection does exist, as it is the first one in the whole snapshot. I tried this same thing with another snapshot and got the same error with another collection.

Not sure why it started happening, but it happens on both my local and on my VPS. I have a feeling Directus skips creating some collection? But why...

Initial tables in `bootstrap` were created successfully.

### To Reproduce

I created [a gist](https://gist.github.com/arpadgabor/d945f0121edf73976d32778d703d3311) with the two snapshots that are experiencing these issues.

### Errors Shown

```
{"level":50,"time":1668764884784,"pid":28534,"hostname":"flow","msg":"Failed to create relation \"attachments.file\""}
{"level":50,"time":1668764884789,"pid":28534,"hostname":"flow","err":{"type":"InvalidPayloadException","message":"Collection \"attachments\" doesn't exist","stack":"Error: Collection \"attachments\" doesn't exist\n    at RelationsService.createOne (/home/arpad/projects/ccoc/node_modules/.pnpm/directus@9.21.0/node_modules/directus/dist/services/relations.js:141:19)\n    at /home/arpad/projects/ccoc/node_modules/.pnpm/directus@9.21.0/node_modules/directus/dist/utils/apply-snapshot.js:190:44","status":400,"code":"INVALID_PAYLOAD","extensions":{}},"msg":"Collection \"attachments\" doesn't exist"}
```

### What version of Directus are you using?

9.21.0, 9.20.4, 9.19.2

### What version of Node.js are you using?

16.18.1

### What database are you using?

Postgres 13 (postgis/postgis:13-3.3-alpine)

### What browser are you using?

n/a

### How are you deploying Directus?

Docker

**Comment by arpadgabor** [comment]
I found this issue that is related #16165 but, at least in my case, I had a successful deployment before on the exact same postgres image. Will continue to investigate.

**Comment by arpadgabor** [comment]
So I tracked down the issue adding console logs in the snapshot code. Seems like all collections are added in the correct order, but it looks like they are not commited in the transaction (I noticed there are some nested transactions around here), so when doing `getSchema` for the `RelationsService`, the schema is the initial one created by `bootstrap` and the collections required for the relations do not exist in the response to that query.

**Comment by arpadgabor** [comment]
Managed to create all collections by separating the relations step into a separate transaction, and now I discovered that the whole ordeal was caused by the cached schema. I now used `CACHE_SCHEMA=false` but now I'm getting back to the issue I reported in #16493, it hangs when getting the database overview.

**Comment by paescuj** [comment]
> @arpadgabor This is still happening for me. One field that we deleted still shows up in the snapshot as a relation and messes up the import. Deleting the filed manually and its relations makes it work, but then this happens: [#17117 (comment)](https://github.com/directus/directus/issues/17117#issuecomment-1548715601)
> 
> My version:
> 
> ```yaml
> directus: 9.26.0
> vendor: postgres
> ```
> 
> I wonder if this part is not working as intended: https://github.com/directus/directus/blob/main/api/src/utils/get-snapshot.ts#L16

Please open a new issue with a precise description of the problem. This issue here was already concluded some time ago.

**Comment by HaraldNordgren** [comment]
New issue: https://github.com/directus/directus/issues/18619
