### ISSUE TITLE
9.21.0 App broken on Firefox "forbidden MIME type"

### ISSUE THREAD

**Issue by neo7-studio-web** [directus/directus#16506]
### Describe the Bug

After an update to version 9.21.0, blank page was shown, with error "forbidden MIME type (« application/json »)"
Works OK on Chrome.

### To Reproduce

Update to 9.21.0 go to App home page

### Errors Shown

![Capture d’écran 2022-11-18 134743](https://user-images.githubusercontent.com/18073828/202708544-b671f8c8-a8cd-46b1-b92a-2ea7eb2a3901.png)

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

18.12.1

### What database are you using?

MariaDB 10.6.7

### What browser are you using?

Firefox 107

### How are you deploying Directus?

locally on a VPS

**Comment by neo7-studio-web** [comment]
Same problem on Chrome & Firefox with Docker image freshly installed :
![Capture d’écran 2022-11-18 142046](https://user-images.githubusercontent.com/18073828/202714819-d758141e-ec71-4175-ad8f-426a5e0bf7ce.png)

**Comment by rijkvanzanten** [comment]
Can you try clearing the browser caches, or doing this in an incognito tab?

**Comment by neo7-studio-web** [comment]
> Can you try clearing the browser caches, or doing this in an incognito tab?

That was it, thanks.
