### ISSUE TITLE
Input restrictions not working on certain browsers

### ISSUE THREAD

**Issue by wfriedman89** [directus/directus#16515]
### Describe the Bug

Seeing some issues and inconsistencies with min/max restrictions and data type values that are allowed across browsers.  See 'To reproduce' below for additional details.

### To Reproduce

1.       Min and max input restrictions for integer and decimal fields do not restrict (all browsers). All values can be saved.
Example:
Configuration:

![image](https://user-images.githubusercontent.com/109602228/202787040-7c7b11d9-fc00-46ca-b85f-574af328223a.png)

![image](https://user-images.githubusercontent.com/109602228/202787073-38183e2b-547d-4e7e-b6dc-9593d69a7332.png)

Input and saved value example:

![image](https://user-images.githubusercontent.com/109602228/202787127-821e661e-1bec-4e7f-b4ee-3423360715e3.png)

![image](https://user-images.githubusercontent.com/109602228/202787165-19d271ee-e6ec-48b4-96eb-fccb619185c1.png)

2.       In Firefox integer and decimal fields allow input of strings:
Example:

Configuration:
<same as above>

![image](https://user-images.githubusercontent.com/109602228/202787335-e07f29ea-094b-4a2b-bced-c7cbc63dfbf2.png)

Input:

![image](https://user-images.githubusercontent.com/109602228/202787366-7c5df8be-5bb4-462d-a9ac-15f95335f48e.png)

or

![image](https://user-images.githubusercontent.com/109602228/202787386-c9309488-5f53-4c10-98f4-c0ec0f35fc32.png)

These values will not be saved, but the user is not getting any error or info message and might miss the missing value.

In Edge and Chrome the field is restricted to integers/decimals and such inputs are not possible.

3.       Integer fields allow input of decimals and cause internal server error when saving:
Example:

Configuration:
<same as above>

Input and error messages:

![image](https://user-images.githubusercontent.com/109602228/202787491-51ded408-70f4-4cd3-ba99-0b6c19062e96.png)

![image](https://user-images.githubusercontent.com/109602228/202787502-dbee4801-9d3b-4ac2-82ba-3a606a4bed3a.png)

or

![image](https://user-images.githubusercontent.com/109602228/202787521-029d3acb-1748-4d79-a65f-0e98c451d940.png)

### What version of Directus are you using?

9.20.4

### What version of Node.js are you using?

16.17.0

### What database are you using?

Postgres 13.4

### What browser are you using?

See ticket details

### How are you deploying Directus?

Docker - Directus Cloud Enterprise

**Comment by rijkvanzanten** [comment]
Linear: [ENG-135](https://linear.app/directus/issue/ENG-135/input-restrictions-not-working-on-certain-browsers)

**Comment by rijkvanzanten** [comment]
This is currently working as expected. The min / max options control the input's `min` and `max` attributes respectively, but aren't controlling validation. That's controlled through Permissions 👍🏻
