### ISSUE TITLE
Mentioned user not rendered in preview

### ISSUE THREAD

**Issue by wittwerch** [directus/directus#1652]
## Version Info
  - Directus version and branch: 1ae426fdcfa3fb8ecad94d6f23d74936e117d473
  - PHP version: 7.1
  - MySQL version: 5.7
  - Web server: Apache
  - OS name and version: Docker 

## Expected Behavior
The mentioned username should be rendered in the preview column on the left.
![screen shot 2017-07-04 at 09 26 58](https://user-images.githubusercontent.com/1575445/27819580-3a6e9550-609b-11e7-96c0-2c7bd31ada3c.png)

That screenshot is from a comment on an entry. It would be cool to have a backlink to that entry, so you can jump right to it with one single click.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/12c6955fb296caaab80f86e0b89dd92aa1b02dd4
