### ISSUE TITLE
Incorrect ellipsis rendering in render-template

### ISSUE THREAD

**Issue by d1rOn** [directus/directus#16521]
### Describe the Bug

In Chrome it is look like that:
![image](https://user-images.githubusercontent.com/26179694/202798158-8a82a22b-6320-47a0-b703-1fbf7ca2a7cb.png)

I figured out that it is related with parent element, which is inline. Seems like ellipsis can't work correctly with inline parent or when it inline itself.

### To Reproduce

It can be reproduced in several ways. One of these: setup relational interface and set template value to field that has a long text value.

### What version of Directus are you using?

9.20.4

### What version of Node.js are you using?

v17.9.0

### What database are you using?

MySQL

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by vedant-z** [comment]
Can I take this @d1rOn

**Comment by paescuj** [comment]
> Can I take this @d1rOn

It seems like @d1rOn already came up with a fix, see #16525.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-133](https://linear.app/directus/issue/ENG-133/incorrect-ellipsis-rendering-in-render-template)
