### ISSUE TITLE
Non-admin user can't read messages

### ISSUE THREAD

**Issue by wittwerch** [directus/directus#1654]
## Version Info
  - Directus version and branch: 1ae426fdcfa3fb8ecad94d6f23d74936e117d473
  - PHP version: 7.1
  - MySQL version: 5.7
  - Web server: Apache
  - OS name and version: Docker 

## Expected Behavior
As a non-admin user I can read messages that are sent to me

## Actual Behavior
The messages are not shown in the backend

## Steps to Reproduce
 1. Create a group with no table permissions but make sure that "messaging" is allowed.
![group](https://user-images.githubusercontent.com/1575445/27822326-92ce7cba-60a5-11e7-9cfb-dcd522c53d04.png)

 2. Send him a message
![screen shot 2017-07-04 at 10 43 48](https://user-images.githubusercontent.com/1575445/27822352-b0b78244-60a5-11e7-978b-82a8b3ed3a5e.png)

3. John receives the email and clicks on the link

Error
![screen shot 2017-07-04 at 10 44 59](https://user-images.githubusercontent.com/1575445/27822433-df6b5a34-60a5-11e7-9d76-12700c69e35a.png)

Inbox is empty
![screen shot 2017-07-04 at 10 45 36](https://user-images.githubusercontent.com/1575445/27822466-f789ab8e-60a5-11e7-8373-b364bc83069b.png)

**Comment by WellingGuzman** [comment]
Hey @wittwerch, even though they are allow to send message they should also has permission to `directus_messages` and `directus_messages_recipients` tables.

I think if this happen we should force basic permission to messages.

What do you think @benhaynes? we have to give the user 3 permission (toggle, and two tables) in order to read/sent messages

**Comment by benhaynes** [comment]
I think we should add a comment to the `Allow Messaging` switch that says:

```
Messaging also requires that this group has full permissions for `directus _messages` and `directus_recipients`
```

**Comment by benhaynes** [comment]
Though this is a fix, not a solution (thanks @rijkvanzanten). We should edit all of these features in ONE place (not two), so I recommend having the permissions determine if Messages will exist/function for a user group.

For example: if you have VIEW for `directus_messages` then you can see messages. If you have CREATE then you can send messages. The only concern here is that you would ALSO need access to `directus_message_recipients`.

Any other thoughts on this?

**Comment by benhaynes** [comment]
OK, so I still think this needs to be based on the permissions. Let's REMOVE `allow_messages` and change to:

If you have VIEW for both:`directus_messages` && `directus_message_recipients` then you have access to Messages. But you need CREATE to send new messages, and EDIT to archive them. Let's spend the time to make this use the Permissions system properly.

**Comment by WellingGuzman** [comment]
We removed the `show_messages` column labeled as `Allow Messaging` and you group must have permission to add `directus_messages` and `directus_message_recipients` to allow them to messaging.

Closed by https://github.com/directus/directus/commit/fda63e4e93f6152fe943fe66505fc28b0ab6beea
