### ISSUE TITLE
Can't Query In Flow Run Scripts

### ISSUE THREAD

**Issue by robertclaus** [directus/directus#16544]
### Describe the Bug

I'm trying to query information from a public API using a Flow and update information in my database based on it.

I can get everything to work if I have a single record. In this situation I can run a query using the "Webhook / Request URL" operation. However, if I'm updating multiple records there's no way to make a query for each record.

I've tried to do this using a custom script, but none of the standard libraries for http requests is available.

### To Reproduce

Try to make an http request in a Custom Script operation within a flow.

### Errors Shown

Module doesn't exist.

### What version of Directus are you using?

9.20.4

### What version of Node.js are you using?

Unsure

### What database are you using?

Unsure

### What browser are you using?

Chrome

### How are you deploying Directus?

Directus Cloud

**Comment by azrikahar** [comment]
> However, if I'm updating multiple records there's no way to make a query for each record.

It should be possible if you pass it to another flow via the [Trigger Flow operation](https://docs.directus.io/configuration/flows/operations.html#trigger-flow) 👍 Specifically noted in the notice block at the end of that section: `"If you pass an array to the other flow, the other flow will run once for each item in the array."`

---

> I've tried to do this using a custom script, but none of the standard libraries for http requests is available.

Currently modules/packages need to be explicitly allowed via the `FLOWS_EXEC_ALLOWED_MODULES` environment variable for security reasons, which should be why you are getting "module doesn't exist" error. 

However I do notice that you mentioned you are on Directus Cloud, in which case editing of environment variables is currently available for Enterprise plan only at the moment. For future inquiries or issues pertaining to Directus Cloud projects, do kindly reach out through the Live Chat in the Cloud Dashboard as that's the best channel to get assistance from the Cloud team with your Cloud projects 🙂
