### ISSUE TITLE
Non-admin user can't view his own profile

### ISSUE THREAD

**Issue by wittwerch** [directus/directus#1655]
## Version Info
  - Directus version and branch: 1ae426fdcfa3fb8ecad94d6f23d74936e117d473
  - PHP version: 7.1
  - MySQL version: 5.7
  - Web server: Apache
  - OS name and version: Docker 

## Expected Behavior
I can view my profile and update settings

## Actual Behavior
View is broken

## Steps to Reproduce
 1. Create a group with no table permissions
![group](https://user-images.githubusercontent.com/1575445/27822326-92ce7cba-60a5-11e7-9cfb-dcd522c53d04.png)

 2. Go to "Your Profile".
![screen shot 2017-07-04 at 10 48 32](https://user-images.githubusercontent.com/1575445/27822611-81909414-60a6-11e7-92a9-45fdc2b21517.png)

**Comment by WellingGuzman** [comment]
That's an expected behavior if the user doesn't have any permission to `directus_users` table.

**Comment by wittwerch** [comment]
Ok, once we add permissions the view loads.

![screen shot 2017-07-05 at 10 45 14](https://user-images.githubusercontent.com/1575445/27856681-19fb8e16-616f-11e7-9057-6ccf6abf8bd2.png)

As a non-admin user I can try to give myself admin permissions. That ends in an error:

![screen shot 2017-07-05 at 10 46 07](https://user-images.githubusercontent.com/1575445/27856725-39fe59a0-616f-11e7-8b28-df3302d02d5c.png)

**Comment by nithinga** [comment]
@WellingGuzman is it necessary to set permission so to block their own profile ?

**Comment by WellingGuzman** [comment]
@nithinga we don't want to assume anything, by default if you create a group from Directus it gives the basic permission so all the users can read their own information.

**Comment by WellingGuzman** [comment]
Hey @wittwerch, what do you mean by:

> As a non-admin user I can try to give myself admin permissions. That ends in an error:

**Comment by wittwerch** [comment]
@WellingGuzman: Let's say I'm in the group "Editor" which has some basic permissions. If I go to my profile the group dropdown appears and I can "try" to assigne the "Admin" group to myself. That ends in the error you see in the screenshot above.

**Comment by WellingGuzman** [comment]
Thanks @wittwerch, the issue here is that the `dropdown` should be disabled too.

We are working on it.

**Comment by WellingGuzman** [comment]
@wittwerch I disable the select input not to be changeable.

Would this solve the issues with this ticket?

**Comment by wittwerch** [comment]
Yes that would be good!

**Comment by WellingGuzman** [comment]
Awesome @wittwerch.
