### ISSUE TITLE
Can't update M2A after sorting

### ISSUE THREAD

**Issue by ptitb** [directus/directus#16567]
### Describe the Bug

When editing a sort in a M2A field the collection item can't be saved because it's missing the M2A collection field.
It's true that there's no collection field in the PATCH request.

The PATCH request object:
`{
    "create": [],
    "update": [
        {
            "sort_id": 1,
            "id": 5,
            "item": {
                "id": 4
            }
        },
        {
            "sort_id": 2,
            "id": 6,
            "item": {
                "id": 5
            }
        },
        {
            "sort_id": 3,
            "id": 8,
            "item": {
                "id": 7
            }
        },
        {
            "sort_id": 4,
            "id": 7,
            "item": {
                "id": 6
            }
        }
    ],
    "delete": []
}`

### To Reproduce

Add a M2A (Builder) field to a collection. Set a custom sort field in the creation of the field. Add M2A items -> save -> edit order of M2A items -> save collection item.

### Errors Shown

[INVALID_PAYLOAD] Can't update nested record "work_media.item" without field "work_media.collection" being set

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

18.12.1

### What database are you using?

MySQL

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
Can confirm this on `9.21.0`:

https://user-images.githubusercontent.com/42867097/203225992-42002e64-7ba4-4634-984f-17cc5c4bf674.mp4

I believe this is related to #16283, so it should work back in `9.20.4`.
