### ISSUE TITLE
Add tajk language for localization

### ISSUE THREAD

**Issue by Ilkhom-S** [directus/directus#16571]
Kindly add Tajik (Tajikistan) Cyrillic language to site for able to localize

**Comment by azrikahar** [comment]
There is the concern of languages that were added but didn't get translated as mentioned here: https://github.com/directus/directus/pull/14858#issuecomment-1206791665, but I've added an `external` label to this issue for now as I believe it will need to be enabled in Crowdin first by @rijkvanzanten, if this is approved.

That being said, in case this helps facilitate any next steps, can you confirm whether `tg-TJ` is the correct language code here? We're generally adhering to [BCP-47 language tags](https://github.com/directus/directus/blob/main/app/src/lang/available-languages.yaml) (from what I understand) and I was able to locate `tg-TJ` listed in https://partnerhub.warnermediagroup.com/metadata/languages#:~:text=tg%2DTJ,tg%2DTJ but not sure if that's the best source here, so just wanted to double check with you.

**Comment by Ilkhom-S** [comment]
Correct, Tajik language code is tg-TJ. I can help you with formatting and translations if needed.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-131](https://linear.app/directus/issue/ENG-131/add-tajk-language-for-localization)
