### ISSUE TITLE
Admin can't edit collection after created and don't show on Collection page

### ISSUE THREAD

**Issue by thongle-dn** [directus/directus#16577]
### Describe the Bug

I logged in with the admin role and created a new collection. After creation, the collection was saved in the database but didn't show on the Collection page, just accessed through the URL and couldn't edit or delete it. 

### To Reproduce

![Uploading Screen Shot 2022-11-23 at 11.52.35 AM.png…]()

### Errors Shown

In the logs, just show PATCH 200 and 304 HTTP code. 

### What version of Directus are you using?

900-rc.87

### What version of Node.js are you using?

12.22.6

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by licitdev** [comment]
Kindly ensure that you are on the latest version of Directus. Thank you.
