### ISSUE TITLE
"Is one of" filter is duplicating comma separated input

### ISSUE THREAD

**Issue by koksikus** [directus/directus#16594]
### Describe the Bug

When I select the contains command, the correct record appears, but when I change to "is one of" no record appears. This is important when you want to search a database with many values. This can be created by Or and then select field and "contains", only that subsequent records have to be created in the same way, and that takes a long time. Maybe a good solution would be to be able to copy lines in the search. Where X appears, let there also be the possibility of a copy.

The second problem is when you use a comma it suddenly shows up a lot of values also trying to remove it

### To Reproduce

https://user-images.githubusercontent.com/90528895/203600258-8e400fc8-b179-4fbf-991a-cefba67a7180.mp4

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

16.18

### What database are you using?

MS SQL

### What browser are you using?

Edge

### How are you deploying Directus?

locally

**Comment by br41nslug** [comment]
"Is one of" cannot be used to search as it requires a complete match like `_eq` so unless one of the "tekst" fields only contains "test1" then this is working as expected. 
The second issue you mention seems like a bug probably to do with the pasting comma separated lists logic 🤔

**Comment by koksikus** [comment]
In that case, my question is how to search for multiple values from a given field. Suppose I have a list and I want to search the database. As I wrote, the next filters are time-consuming, a nice copy option would be...
![Zrzut ekranu 2022-11-25 113528](https://user-images.githubusercontent.com/90528895/203965246-8b5dc299-f7d5-48d9-92a0-90396eb83878.jpg)

**Comment by paescuj** [comment]
@br41nslug Do you know by any chance in which cases this "popup" with the bigger text field appears? I tried to reproduce this on Firefox but this popup doesn't show up.

**Comment by br41nslug** [comment]
@paescuj I think it's specific on the `is one of` (or its reverse) on a non-relational field. It worked for me on firefox with a `is one of` filter against a string field.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-130](https://linear.app/directus/issue/ENG-130/is-one-of-filter-is-duplicating-comma-separated-input)
