### ISSUE TITLE
Encryption Interface

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1661]
The interface needs a way to encrypt strings based on different hash options. So the backend needs a endpoint to encrypt strings for the frontend.

Maybe this `encrypted` interface should be separate from the Password interface... it might be used for many different purposes

**Comment by rijkvanzanten** [comment]
Do you want the interface to encrypt on change or encrypt on save?

**Comment by benhaynes** [comment]
Hmm... Good question. I think on change, that way if they don't have the string masked (eg password) then they can see the hash

**Comment by WellingGuzman** [comment]
I think they hash has to be on server side (on save) otherwise we have to create the algorithm function on both client and server side, UNLESS we request a encrypted value on every change.

**Comment by benhaynes** [comment]
I think it would be better to have access to this on the client-side... other Interfaces might use it differently and need to encrypt before save.

As for this interface, I think we can either encrypt on keypress/blur and have it display below the input. Then when you save it saves the hashed value... so if you go back to edit the item later the plaintext value is gone.

**Comment by rijkvanzanten** [comment]
@WellingGuzman I meant send of the request to hash on change of the interface. We won't hash client-side

**Comment by WellingGuzman** [comment]
@benhaynes Having and endpoint means all interfaces can use it.

**Comment by benhaynes** [comment]
I get it.

1. User adds plaintext string to input
2. On keypress, gets encrypted hash from backend
3. Interface displays hash below input
4. User saves item/page
5. Hash is saved in column value
6. User views page – sees hash in the input

**Comment by rijkvanzanten** [comment]
Does the `encryption` endpoint also support checking a hashed value @WellingGuzman? Or is there going to be a separate `check-hashed`-style endpoint?

**Comment by WellingGuzman** [comment]
I don't see point on hashing on keypress, unless there's a good reason for it.

We keep calling the server on each keypress, which I think is unnecessary.

2. On keypress, gets encrypted hash from backend
2.1. On second keypress what value do we send to the server we already have the plaintext hashed?
2.2. Then we need to keep keep a plain value stored, then we should send those instead
2.3. If that's the case, why don't do that instead, hash only when the user press "hash" button, typing will be faster than getting the data back from the server.

Which mean why the reason to have a client side example, but everything should be best to pass through the server instead.

**Comment by WellingGuzman** [comment]
@rijkvanzanten I was thinking on having a the plain text stored for those case, and calling the server endpoint every x ms after stop typing? @benhaynes

**Comment by rijkvanzanten** [comment]
We will add in a debounce on the input of course, so it will only hash after `400ms` or so inactivity. We keep the plaintext version client-side as long as the user is editing the item. When the user saves the item, we only save the hashed value.

**Comment by benhaynes** [comment]
Exactly. Not on keypress, 500ms after keypress will avoid most calls.

**Comment by WellingGuzman** [comment]
Awesome! no more question your honor!

**Comment by benhaynes** [comment]
This interface has been added into `6.4`. You can choose your hashing algorithm and if you want the value masked.

**Comment by marwie** [comment]
Hello, somehow I get an error when I try use the encrypted interface on my server: the error says: "Not found: unknown".

**Comment by rijkvanzanten** [comment]
Hey @marwie! Could you please open a new issue detailing your exact problem and server setup so we can reproduce and debug it? Thanks!
