### ISSUE TITLE
Insights charts time offset

### ISSUE THREAD

**Issue by martinomg** [directus/directus#16619]
### Describe the Bug

Hello, I'm using directus to store data from a bunch of crawlers and on the insights panel i'm getting differences related to the timezone. Normally i start running my app at 9am and on the first hour running it gets around 5-6k new records, so it should be reflecting that on the chart.

When i apply filters to the different components, they have an offset that doesn't consider my timezone in relation to the database timezone. This only happens inside the insights panel.

### To Reproduce

My machine is setup to work for Chilean time.
<img width="478" alt="Screenshot 2022-11-25 at 09 21 13" src="https://user-images.githubusercontent.com/5248081/203987824-5e458f9b-d385-4ea4-9ffc-c8727743b321.png">

As you can see the maximum time is around my local time which is fine, but the last value is not even close to the last hour.
<img width="918" alt="Screenshot 2022-11-25 at 09 40 40" src="https://user-images.githubusercontent.com/5248081/203988024-d4f60392-1de4-4c54-99eb-ecb6da98f8a2.png">

This is filtering the last hour but technically i started running the crawler at 09:10, so it's ok to be couting 2692.
![Screenshot 2022-11-25 at 09 39 20](https://user-images.githubusercontent.com/5248081/203989128-9c24e847-2e14-4f12-bbe5-6b8380b6b91d.png)

Checking the query i think it might be related to the filter, i don't know if this considers the UTC time or my local time.
<img width="1440" alt="Screenshot 2022-11-25 at 09 47 25" src="https://user-images.githubusercontent.com/5248081/203989461-538f9150-004e-4e4c-acc7-416bf79c8820.png">
 
![Screenshot 2022-11-25 at 09 53 42](https://user-images.githubusercontent.com/5248081/203990153-cf16f4ca-5b7e-4423-8142-7e84a1032328.png)

Also there is the same empty offset at the beginning of the charts
<img width="893" alt="Screenshot 2022-11-25 at 09 43 05" src="https://user-images.githubusercontent.com/5248081/203990422-15134f38-3c75-4d1c-96d1-5d5a05666aa4.png">

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

16.17.0

### What database are you using?

Mysql

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally MacOS

**Comment by rijkvanzanten** [comment]
Linear: [ENG-129](https://linear.app/directus/issue/ENG-129/insights-charts-time-offset)
