### ISSUE TITLE
Relationship's fields on sub-collection showing as readonly or editable (it should be hidden)

### ISSUE THREAD

**Issue by mmmaxxxe** [directus/directus#16635]
### Describe the Bug

If i'm adding an item into a main collection and then i add a sub item on a related collection (O2M, M2M,M2O) the field that links the two collections on the related table should be not visible as it is supposed that the two records are linked toghether.
Instead, the linking fields are visible but readonly or visible and editable.

This is a minor issue on O2M or M2O (visible but readonly), but it is a problem with M2M because the user can actually add an item on the main collection from the sub-collection pane.

### To Reproduce

1) Create two collections (example)

a) main_collection with some fields
b) sub_collection with some fields and relationship O2M with a) (add the M2O to the a) actually...)

Add an item on a) and add a related item , you should see the a) field as readonly

2) Create two collections (example)

a) main_collection_1 with some fields
b) sub_collection_1 with some fields and relationship M2M with a) (and back in a) create the corresponding M2M)

Add an item on a) and add a related item , the relationship field is visible and editable (so you can add a new item in a) and so on in a infinite loop) 

### Errors Shown

none

### What version of Directus are you using?

9.20.4

### What version of Node.js are you using?

directus cloud standard

### What database are you using?

directus cloud standard

### What browser are you using?

brave, chrome

### How are you deploying Directus?

directus cloud standard

**Comment by mmmaxxxe** [comment]
Edit: the readonly relationship's fields on subcollection are empty so they give no information to the user (they can be invisible then)

**Comment by rijkvanzanten** [comment]
Linear: [ENG-128](https://linear.app/directus/issue/ENG-128/relationships-fields-on-sub-collection-showing-as-readonly-or-editable)

**Comment by paescuj** [comment]
Thank you very much for this report!

I think that's more of a question of the configuration. In the settings of a field you can make it read-only:
<img width="350" src="https://user-images.githubusercontent.com/5363448/216067173-0677e582-c720-4ae2-ac3d-fca579cab646.png">
In your case you should be able to make the O2M / M2M fields in the "sub" collections read-only.
Directus itself cannot really know which field you ultimately want to use to edit the values, so I think it's something you have to configure yourself.
For this reason I'm closing this issue for now.
Feel free to open a new issue if this is somehow still a problem for you.
