### ISSUE TITLE
Date validation always invalidates input

### ISSUE THREAD

**Issue by laurens94** [directus/directus#16649]
### Describe the Bug

I created a datetime (type: Date) field called `date` with the following validation:

---

<img width="624" alt="image" src="https://user-images.githubusercontent.com/5780704/204299756-c86874f0-29b0-4b99-a0fd-0523ec9b8810.png">

---

**Having an invalid date shows the error as expected:**

<img width="843" alt="image" src="https://user-images.githubusercontent.com/5780704/204300019-b1506022-ed15-4783-bc49-ddc3abdf98eb.png">

---

**But having a valid date (year 2023), also shows the error:**

<img width="822" alt="image" src="https://user-images.githubusercontent.com/5780704/204300121-8ce1f5a5-8c72-4416-91ab-4ee97612785b.png">

### To Reproduce

1. Create a DateTime field with the type 'Date'
2. Field > Validation > Add Filter > Click on the name of the field > Click the arrow > Click Year (Fieldname)
<img width="362" alt="image" src="https://user-images.githubusercontent.com/5780704/204301127-72d67ab5-8489-4ef9-ae76-59957a583329.png">
3. Type 2023, save
4. Add a new item to the collection you created the field in
5. Select a date within 2023, save
6. See the error

### Errors Shown

Nope

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

16.18.1

### What database are you using?

Postgres 13

### What browser are you using?

Firefox

### How are you deploying Directus?

Using directus/directus:9 docker image

**Comment by rijkvanzanten** [comment]
Linear: [ENG-126](https://linear.app/directus/issue/ENG-126/date-validation-always-invalidates-input)
