### ISSUE TITLE
Bookmarks don't work

### ISSUE THREAD

**Issue by martinfojtik** [directus/directus#1664]
## Version Info
  - Directus version and branch: version/6.4 (e1f5002)
  - PHP version: 7.1.5
  - MySQL version: 5.7.18
  - Web server: Apache
  - OS name and version: Windows 10

## Actual Behavior
This error `You don't have permission to view that page or it doesn't exist` is displayed after clicking on bookmark 

## Steps to Reproduce
 1. create bookmark
 2. click on bookmark in left side menu

**Comment by WellingGuzman** [comment]
Fixed by https://github.com/directus/directus/commit/551e92fc910b42173e52ade9208f7e052e1deb99
