### ISSUE TITLE
HookExtensionContext export missing

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#16658]
### Describe the Bug

Based on the definition of `defineHook` the second parameter of the register function is typed as `HookExtensionContext`. This is just adding the emitter to the `ApiExtensionContext` but for full TS-support it should be exported as ApiExtensionContext: 
https://github.com/directus/directus/blob/main/packages/shared/src/utils/define-extension.ts#L35-L37

https://github.com/directus/directus/blob/main/packages/shared/src/types/hooks.ts#L4-L17

### To Reproduce

N/A

### What version of Directus are you using?

Github main-branch

### What version of Node.js are you using?

N/A

### What database are you using?

N/A

### What browser are you using?

N/A

### How are you deploying Directus?

N/A

**Comment by rijkvanzanten** [comment]
Linear: [ENG-125](https://linear.app/directus/issue/ENG-125/hookextensioncontext-export-missing)
