### ISSUE TITLE
Conditions in a field that is in a group

### ISSUE THREAD

**Issue by koksikus** [directus/directus#16663]
### Describe the Bug

The full description is in the discussion. First I wanted to make sure it wasn't a setting error.
https://github.com/directus/directus/discussions/16158

### To Reproduce

https://github.com/directus/directus/discussions/16158

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

16.18.1

### What database are you using?

MS SQL

### What browser are you using?

Edge

### How are you deploying Directus?

locally

**Comment by br41nslug** [comment]
Mind adding reproduction steps and a description next time, using the discussion as reference is perfectly fine but it does not replace a concise description and clear reproduction steps.

**Comment by br41nslug** [comment]
I am unable to reproduce this with the given information. I've rebuilt the test case displayed in the video and tested across firefox, chrome and edge.

https://user-images.githubusercontent.com/9389634/204557710-0f6a45a7-8240-4584-ac18-12002ae220b4.mp4

Happy to reopen the ticket when more info is available 😄

**Comment by koksikus** [comment]
But in your video you can see this error. In 1:08 
![Zrzut ekranu 2022-11-29 163342](https://user-images.githubusercontent.com/90528895/204573716-2697dc98-849b-4ecd-9458-3e99dcbb4fed.jpg)

You can trigger this error in the group or by pulling the field out of the group with the same settings and vice versa.

**Comment by koksikus** [comment]
Sorry, now i see it and confirm at least one choice must be entered. Allow for other values doesn't help. I didn't think of it because I don't want any choice. Well, what if you don't want any choice... Sometimes when conditions aren't met, you don't want there to be a choice, but certainly not a message that "Choises configured incorrectly". It wouldn't be better if the information from placeholder was displayed. 
Thank you.

**Comment by br41nslug** [comment]
Ah sorry i thought simply allowing for other options would have worked too. Having a proper/editable "no items available" message instead of the "configured incorrectly" could be a good feature suggestion 😄

**Comment by koksikus** [comment]
I found the difference between our settings, well my toggle is in default value false i am not using null. 
I can't disable editing field like in the video, when the field is out of the group.

https://user-images.githubusercontent.com/90528895/213220475-c31956ac-c373-45a1-8f09-2dbbc775a4be.mp4

**Comment by koksikus** [comment]
Make the field uneditable when creating the card, without clicking on the value. So that it results from the values that are already in the card, i.e. toggle is false. If you start clicking, the conditions will work.

**Comment by koksikus** [comment]
To reproduce:
the toggle field must have a default value "false" and be in a different group than the field in which we set the conditions
we create in other field a condition if the toggle field is "false" then the field is not editable.
we create a new record - the condition does not work
we open the previously saved record - the condition works
