### ISSUE TITLE
Unable to filter search based on Many to one field dropdown

### ISSUE THREAD

**Issue by nithinga** [directus/directus#1667]
## Version Info
 - Directus version and branch: version/6.4 - 7654959ddc6193aebac11750b0e50e3f60e2662e
 -  PHP version: 7.1
 - MySQL version: 5.7
 - Web server: Apache
 - OS name and version: Docker ( Ubuntu )

## Expected Behavior
When searching based on many to one field it should return results.

## Actual Behavior
When searching based on many to one field it returns an error.

## Steps to Reproduce
 1. Make a table with many to one relations.
 2. Try to filter based on that field in search
 3. You will get errors.

## Logs or Screenshots
![screenshot from 2017-07-07 12 56 45](https://user-images.githubusercontent.com/18306604/27947687-90a1091e-6314-11e7-9780-c7f5b3deda34.png)

**Comment by WellingGuzman** [comment]
Hey @nithinga,

I tried and I couldn't replicated, can you try to update to the latest commit, and see if still happens?

**Comment by WellingGuzman** [comment]
I managed to replicate the issue. It's not working when it sets to `dropdown`.

We are working on this ticket right now.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/4360025796ef0e2ebe38010a47ef5267ba47f744
