### ISSUE TITLE
M2A inside M2M not saving correctly

### ISSUE THREAD

**Issue by abertay-university** [directus/directus#16671]
### Describe the Bug

When creating a new M2A record inside a M2M record, then saving the record, the M2A record is not linking correctly. It appears as an empty record. However, the M2A record has saved in the table. To resolve, I need to remove the record from the M2M field, save, then add the content back from the existing record.

https://user-images.githubusercontent.com/31690037/204590156-718485dc-321e-45f4-a5b8-01fe686f06fd.mov

### To Reproduce

Create a collection (uuid) with a M2A field that link to 2 different collections (regular ID).
Create a collection (uuid) with a M2M field that links to the collection with the M2A field.
Create a new M2M record, then a new M2A record.
Save.
Open the M2M record and view the M2A record.

### Errors Shown

No errors shown.
The M2A record appears empty. The API called returns a record with the it's ID but the record is empty.

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

16.17.1

### What database are you using?

MS SQL MI

### What browser are you using?

Chrome & Edge on Windows and Safari on Mac

### How are you deploying Directus?

locally

**Comment by br41nslug** [comment]
Have not been able to repro this on a postgres database so might be MS SQL depend 🤔

**Comment by abertay-university** [comment]
I had a look at the database. I can see where the issue is. When the UUID is saved into the joiner table, it's using lowercase, but the UUID on the record is uppercase.

![image](https://user-images.githubusercontent.com/31690037/204852008-5e9a3bd3-5db1-4076-9cb8-46e85fc436e6.png)

**Comment by br41nslug** [comment]
Thanks for the extra info that does indeed look like this is specifically a MS SQL issue. Will setup a proper test environment for this issue tomorrow 😄

**Comment by abertay-university** [comment]
When I compare to M2M joiner table, they use 2 columns with Foreign Key, Unique Identifier.

![image](https://user-images.githubusercontent.com/31690037/204855130-72b0bacc-b73e-4953-b432-1803fa2cc2dc.png)

Whereas M2A uses the item column (nvarchar(255)) because the ID doesn't come from a single table.

![image](https://user-images.githubusercontent.com/31690037/204855207-daf421b4-0473-49ce-84a4-2532417c6a01.png)
