### ISSUE TITLE
Error when inviting user - "not authorized to perform `ses:SendRawEmail' on resource"

### ISSUE THREAD

**Issue by shipsides-sparknel** [directus/directus#16676]
### Describe the Bug

Receive error when inviting a user. The user still creates, but no email gets sent.

This is Directus Cloud and might be specific to ap-southeast instances based on the error message. I tested on a community cloud project and it is still working fine.

Feature was working yesterday on 9.20.4 and no longer works on 9.21.2, doesn't seem like a coincidence.

### To Reproduce

Invite user using the API or the app on a APAC instance

### Errors Shown

{
  "message": "User `arn:aws:sts::176291536184:assumed-role/eks-standard-1-nodegroup-spot-NodeInstanceRole-15UERT5Z9WWS4/i-08f54280a27ccb9b5' is not authorized to perform `ses:SendRawEmail' on resource `arn:aws:ses:ap-southeast-1:176291536184:identity/directus.io'",
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR"
  }
}

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

16.18.1

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

Standard Cloud

**Comment by br41nslug** [comment]
I've checked with the cloud team and this issue should be resolved now 😄
