### ISSUE TITLE
When creating O2M the foreign key selector field options are greyed out

### ISSUE THREAD

**Issue by tbeni02** [directus/directus#16692]
### Describe the Bug

Today I created some other fields to my database through the cloud UI. I created a singleton collection (call it collection ,,A") with a few String type fields. 

After this I created another (not singleton) collection (call it collection ,,B" )with some fields and a field for the foreign key, as I did before. (I always created a plus field in the collection for the O2M model I choosed integer field type, entered a starting value (always 1 ) and clicked to the hidden on details button)

When I did this I wanted to add an O2M field to collection A but when I selected collection B in the related collection field option, I cannot choose any foreign key from collection B, all of the options greyed out.

I attached a Picture:

![image](https://user-images.githubusercontent.com/63247066/205116383-735e4f25-3919-4695-9e41-87009c7a5dc5.png)

Interesting thing is that the same issue appear when I delete and recreate a some data structure, Same issue happening when I downloaded the latest update I tryed to create what I mentioned above, result: not working.

I don't know what is the solution. I kindly ask you for your help!

Thank you! 

### To Reproduce

Please follow the Describe the bug session!

### Errors Shown

No error just greyed out foreign key selector field. 

### What version of Directus are you using?

9.21.2.

### What version of Node.js are you using?

8.15.0.

### What database are you using?

MySQL

### What browser are you using?

Chrome

### How are you deploying Directus?

Running locally, trying from the cloud version

**Comment by br41nslug** [comment]
Existing foreignkeys are indeed not selectable when creating an O2M on a singleton. As a workaround letting the app create the relationship still works. You can do this by typing a non-existing name in the foreign key field instead of selecting one from the dropdown.

**Comment by tbeni02** [comment]
#16437 issue solved me the problem. Turned out this is a bug. you can type the foreign key manually from the list. If its exactly matching it will be signed with blue text colour.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-122](https://linear.app/directus/issue/ENG-122/when-creating-o2m-the-foreign-key-selector-field-options-are-greyed)
