### ISSUE TITLE
Directus folder permission handling not working

### ISSUE THREAD

**Issue by tbeni02** [directus/directus#16695]
### Describe the Bug

I created a role let's call it test role.

After I created multiple folders with my administrator role:
![image](https://user-images.githubusercontent.com/63247066/205180174-d25b2a18-3d95-4103-b74d-9c52c81c123a.png)

In the permissions tab I deleted all type of access to the test role to view, create, delete, update folders:

![image](https://user-images.githubusercontent.com/63247066/205180753-77436e65-5450-46c7-abb6-41b8763c97ee.png)

Finally I switched from the administrator role to the test role and the folder options are still there. 
Is it a bug? Or I am doing something wrong?

### To Reproduce

Please read the describe the bug section.

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

8.15.0

### What database are you using?

MySQL

### What browser are you using?

Chrome

### How are you deploying Directus?

Running locally, also cloud version

**Comment by br41nslug** [comment]
This can be browser cache if you switch accounts without refreshing the page.
