### ISSUE TITLE
ERROR: (O2M) One-to-many with unique 

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#16708]
### Describe the Bug

When creating a many-to-one and a related one-to-many alias and set the FK to unique, the one-to-many interface doesn't work anymore. Also it can't be edited anymore.

In 9.18.1 this worked as a solution for a o2o relation.

### To Reproduce

1. Create a o2m and m2o, 
2. Set the FK to unique (must be done directly on the DB, as the API can't alter the existing contstraint but also won't allow us to make it unique on creation)
3. Check the m2o view (--> everything is fine)
4. Check the 02m view (--> Shows error: "The relationship hasn't been configured correctly")

### Errors Shown
Interface: `The relationship hasn't been configured correctly`
Data-Model Settings: Nothing
### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

N/A

### What database are you using?

MySQL

### What browser are you using?

Chrome

### How are you deploying Directus?

N/A

**Comment by br41nslug** [comment]
> must be done directly on the DB, as the API can't alter the existing contstraint but also won't allow us to make it unique on creation

You shouldnt have to go edit it directly in the database. I was unable to reproduce this problem by creating an unique constraint.
https://user-images.githubusercontent.com/9389634/205866975-0ae30a40-e05f-4079-88e4-9993dc7106eb.mp4

Happy to re-open when more info becomes available

**Comment by Dominic-Marcelino** [comment]
@br41nslug Thanks for checking!
Turns out that somehow there was an error inside the relations-table. 

Fixed it and haven't been able to recreate the issue.

**Comment by Dominic-Marcelino** [comment]
In case anybody else runs into this (as it happened again to me):

The issue was, that the fk index initially created as `<collection>_<field>_foreign`. 
When you manually set this to a unique constraint, the interface displays the error above. You need to change the index name name to  `<collection>_<field>_unique`
