### ISSUE TITLE
Can't install Directus, error on final step

### ISSUE THREAD

**Issue by lunacye** [directus/directus#1671]
## Version Info
  - Directus version and branch: (Or commit hash) directus-build-6.4.0-20170709143459
  - PHP version: 5.6.30
  - MySQL version: 5.5.55-cll
  - Web server: (Ex. Apache, nginx or IIS?)  Apache 2.2.32 on MediaTemple VPN
  - OS name and version: linux or unix, not sure exact version

## Expected Behavior

Followed installation guide at https://docs.getdirectus.com/6.4.0/#Simple_Installation. 

## Actual Behavior

Successfully installed Directus on website. Realized I was using old version with less fancy UI. Deleted Installation. Re-installed with latest version. No longer can install Directus.
Error message "Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]])" after clicking Install on step 4 of installation.

## Steps to Reproduce

All requirements were met for the server (file info, mysql db created, etc)

1. Uploaded directus build to root folder of api.domain.com
2. Worked great, realized I had older version with less fancy UI updates, and deleted installation + composer folder + tables from DB

Here's where the problem starts:
1. Uploaded latest directus build to root folder of api.domain.com
2. Installed/added composer to same folder (root of api subdomain)
3. Ran composer via SSH (php composer.phar install) and installer runs successfully adding all modules to Vendor directory
4. Navigated to api.domain.com and get redirected to installation directory
5. Filled out installation form and get to step where requirements are listed before install, with big install button on bottom
6. Step 4 - Click install and get another directus screen on same step URL (see attach - same styling as others, blue bg with box) -- error msg: "Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]])". Also mentioned to install composer. 
7. After installing composer again via SSH, composer does nothing as modules don't need installing/updating.
8. Go back to api.domain.com. Page is blank, no redirect to installation.
9. Go directly to installation folder. Form is autofilled with data I entered previously, including passwords.
10. At step 3, I get an error saying Database already exists "Directus Core tables already exist in this database. It seems Directus is already installed here."
11. Check mySQL and confirm, DB has one table, directus_schema_migrations.
12. Delete table, redo installation steps (with all forms auto-filled), and get same error at the end. 
13. rinse repeat

I've tried installing 6.3, 6.4, and the master. I tried installing each from the ZIP, uploaded via FTP to the server. And I even tried a git clone of the repo directly to the server via SSH (actually worst case, all file permissions were broken for some reason and gave 500 internal server errors). None worked, all return same error.

I'm sure this is probably a problem on my end, or a server config issue, but I thought it'd be worth reporting because no matter how I slice it - I can't install it on my production server. Works fine on my local LAMP.

## Logs or Screenshots
![screen shot 2017-07-09 at 3 39 55 pm](https://user-images.githubusercontent.com/27020773/27998203-23c3aaee-64be-11e7-9d37-ed9fcfe08741.png)
![screen shot 2017-07-09 at 3 49 29 pm](https://user-images.githubusercontent.com/27020773/27998209-3bd6b392-64be-11e7-8b9f-64733e0504e6.png)

**Comment by benhaynes** [comment]
If it's a new install, I would just delete the existing tables in the database. Directus won't install over an existing version to avoid overwriting any of your previous system.

It looks like you did delete the tables, but you probably need to delete the generated config and configuration files within `/api`.

Either way we're looking into this now! Thank you so much for reporting the problem!

**Comment by lunacye** [comment]
Hi Ben, thanks for getting back to me!

Yep, I tried deleting tables and reinstalling, no avail, same results. 

I also did a clean install each time, deleting all files and uploading fresh ones, so no configs should have been artifacts.

**Comment by lunacye** [comment]
It works like a charm! Thank you for the help @WellingGuzman and @benhaynes!

You guys are making kickass software here, excited to have it in our stack now 👍

**Comment by WellingGuzman** [comment]
Awesome!  glad it worked it out.

Thanks for the kind words. please let us know how it went! :)
