### ISSUE TITLE
Unable to filter items in M2A collections

### ISSUE THREAD

**Issue by juggler39** [directus/directus#16715]
### Describe the Bug

I have a collection `pages` with a field `content` made with the relationship `Builder (M2A)`.
Inside that field are collections with a translated field.
It is unable to filter the items with the specified language. I use this query: 
`deep[content][item][translations][_filter][languages_code]=en-US`,
but returned are all languages:
![image](https://user-images.githubusercontent.com/61351959/205597827-36474d28-e78e-48c0-97c7-77d5a267325c.png)

### To Reproduce

Create a collection, add a field with `Builder(M2A)` relationship to a collection with translations.
Try to get just one language.

### Errors Shown

no

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

v16.15.1

### What database are you using?

Sqlite3 5.1.2

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
Linear: [ENG-119](https://linear.app/directus/issue/ENG-119/unable-to-filter-items-in-m2a-collections)

**Comment by br41nslug** [comment]
The `deep` query is not complete. To query/filter m2a fields you'll need to provide a collection scope https://docs.directus.io/reference/query.html#many-to-any-union-types
If you update the filter to include the collection you're querying it should work as expected.
```
&deep[content][item:COLLECTION][translations][_filter][languages_code]=en-US
```

Filtering m2a fields with deep queries are working in my tests.
