### ISSUE TITLE
Missing file : /assets/img/directus-logo-flat.svg

### ISSUE THREAD

**Issue by trk** [directus/directus#1672]
This file : **``/assets/img/directus-logo-flat.svg``** in use on **``api\api.php``** file line [527](https://github.com/directus/directus/blob/master/api/api.php#L527) and on **``api\core\functions.php``** file line [1309](https://github.com/directus/directus/blob/master/api/core/functions.php#L1309).

**Comment by WellingGuzman** [comment]
Thanks @trk, we will fix this asap.
