### ISSUE TITLE
Cannot login into Directus (unexpected mistake)

### ISSUE THREAD

**Issue by tbeni02** [directus/directus#16729]
### Describe the Bug

I dont really have information, None of my colleauges in the company could log into our Directus instance.
![image](https://user-images.githubusercontent.com/63247066/205892717-f0a1d9a1-fe24-4aa7-8f0b-f77c46d0df42.png)

The problem appeared today morning.

### To Reproduce

No idea how to even reproduce it. 

### What version of Directus are you using?

9.21.2.

### What version of Node.js are you using?

8.15.0.

### What database are you using?

MySQL

### What browser are you using?

Chrome

### How are you deploying Directus?

cloud version

**Comment by br41nslug** [comment]
For cloud support please use the chat widget in http://directus.cloud

**Comment by tbeni02** [comment]
In the Chrome console the system drops me Invalid Filesystem Path status code 500

**Comment by wfriedman89** [comment]
Hi @tbeni02 ,

You have a Support Ticket opened for this request and will be providing updates there.

Closing out this Directus Core ticket.
