### ISSUE TITLE
INTERNAL_SERVER_ERROR when delete a user linked to files

### ISSUE THREAD

**Issue by juherr** [directus/directus#16733]
### Describe the Bug

When trying to delete a user, I receive an unknown issue:

```json
{
  "errors": [
    {
      "message": "delete from `directus_users` where `id` in ('<ID>') - ER_ROW_IS_REFERENCED_2: Cannot delete or update a parent row: a foreign key constraint fails (`directus_operations`.`directus_files`, CONSTRAINT `directus_files_modified_by_foreign` FOREIGN KEY (`modified_by`) REFERENCES `directus_users` (`id`))",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### To Reproduce

1. Create a new instance with the default admin user
2. Configure a logo by uploading a new file
3. Create another admin
4. Remove the first admin user

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

18.12.1

### What database are you using?

MySQL 5.7.40

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by juherr** [comment]
Once I've updated the `uploaded_by` and `modified_by`columns from `directus_files`, the deletion worked as expected.

**Comment by azrikahar** [comment]
Should be the same issue (and potential solution) as described in #9507 👍
