### ISSUE TITLE
Forbidden fields in update of a readonly M2M should not show when the M2M is clicked

### ISSUE THREAD

**Issue by Pachat** [directus/directus#16732]
### Describe the Bug

- A **collection** (`Directus_Roles` with an added field `network`) is set for the Regular role with  `network` excluded from Read and  Update permissions.
- On another collection (`Directus_Users`), an <= M2M => `Directus_Roles` the M2M **field** is set for the Regular role with Read, not Update permissions.
- The Regular User sees his `M2M` as readonly: _correct_
- But when he clicks on it, he sees the whole related field (the role) including  `network`.

### To Reproduce

1. In `Directus_Roles` add the field `network`
2. For the `Regular role`, set on `Directus_Roles`, no Read permission on the field `network`, and `No Access` for Update permission.
3. In `Directus_Users` add an  `Directus_Users <= M2M => Directus_Roles`
4. For the `Regular role`, for `Directus_Users`, in Read permissions include the M2M field, but not in Update permissions.
5. Connect as Regular and show the user profile.
6. Click on the M2M field: the related M2M `Directus_Roles` shows

### Errors Shown

- You see the field `Directus_Roles.network` that has no Read permission.

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

19.0.1

### What database are you using?

PostgreSQL 15

### What browser are you using?

Edge and Firefox

### How are you deploying Directus?

locally and on VPS

**Comment by Pachat** [comment]
Same bug for O2M : when an O2M field is not allowed to Update (and furthermore with Select is deactivated) a click on the O2M item in the parent collection should be inactive (it shows the list of the items of the O2M collection to make a choice and modify it. The consequence is 
```
{
  "message": "You don't have permission to access this.",
  "extensions": {
    "code": "FORBIDDEN"
  }
}
```
That's correct but not friendly: better to deactivate the click action than allow an action that is forbidden at last.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-116](https://linear.app/directus/issue/ENG-116/forbidden-fields-in-update-of-a-readonly-m2m-should-not-show-when-the)
