### ISSUE TITLE
Auto-generate token for new users

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1674]
When creating a new user, it should auto-generate a new token for them. Right now I have to click "generate" to get one each time.

**Comment by WellingGuzman** [comment]
I thought we decided it should be optional and generated only if the admin decided to.

**Comment by benhaynes** [comment]
Maybe I'm just OCD and want each user to have one. OK, that works. We'll keep it how it is. It's another security feature since not everyone gets a token by default.

We should also add a check sometime to make sure users can't accidentally add "a" to the field (or something equally simple) since then the API auth would be too easy to hack.
