### ISSUE TITLE
File download 403 with custom role using JWT

### ISSUE THREAD

**Issue by NecoHorne** [directus/directus#16759]
### Describe the Bug

I have a custom role that should only be able to access files linked to that role. 

in the `directus_users` table I have added a many to one relationship with the customer table, then in the `directus_files` I have created the same relationship. 
![image](https://user-images.githubusercontent.com/30078491/206478539-1d82499c-90f1-4d98-86fd-5f864ef91f3d.png)

in my custom role I have created access rules so the user can only see customers and statements that belong to the same customer. 

For the customer object read permissions:
```json
{
	"_and": [
		{
			"id": {
				"_eq": "$CURRENT_USER.customer.id"
			}
		}
	]
}
```

for the directus_files read permissions: 
```json
{
	"_and": [
		{
			"customer": {
				"id": {
					"_eq": "$CURRENT_USER.customer.id"
				}
			}
		}
	]
}
```

Everything in the app is working as expected, I can see only the customer assigned to the user, and the user can only see the files assigned to the same customer as the user. 

![image](https://user-images.githubusercontent.com/30078491/206479417-8c865a55-0fcc-4bf4-aea8-08ade715c52f.png)

The issue comes in when I try and download the file using the user JWT token. The system responds with a 403 not authorized. This happens when clicking on the download button in the app or trying to access it directly using the API like so 

`http://localhost:8056/assets/<FILE-ID>?download=&access_token=<JWT-TOKEN>`

or when trying to download it using the Directus api in a custom module `this.api.get`.

![image](https://user-images.githubusercontent.com/30078491/206479684-d5886f93-783a-4bb2-ab2f-1992ff5d7bf9.png)

I think it has something to do with the `?download` param.

I have tried the url param `access_token=` and the header param `Authorization: Bearer <token>` with the same result.

### To Reproduce

Use a custom role with custom permissions on the asset download query referenced here https://docs.directus.io/reference/files.html#downloading-a-file using a JWT token to auth the request.

### Errors Shown

[17:02:03] GET /assets/5dfe08f9-b8ff-4e8b-a8b4-a265593240b0?download=&access_token=--redacted-- 403 163ms

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

16.16.0

### What database are you using?

MySQL

### What browser are you using?

Chrome

### How are you deploying Directus?

EC2 Ubuntu VM and locally.

**Comment by paescuj** [comment]
I have a similar permissions on files and the download works in my case.
Are you maybe missing some field permissions?
Also do you see any relevant errors / warnings in the logs?

**Comment by br41nslug** [comment]
I've recreated the permissions as described on a clean installation however i am able to download the image as expected (in the App and manually using the API) with a valid access token.

Could either the UUID or Token be invalid somehow?

**Comment by NecoHorne** [comment]
@br41nslug Thanks for pointing out the UUID, this was an ID10T issue and this time I was the idiot🤦‍♂️.

The uploads folder for this project is not committed to the repo, the file was uploaded on the prod version and my dev version did not have the file in question, I downloaded the prod uploads folder and all working as expected. 

Sorry for wasting your time, you can close this issue.
