### ISSUE TITLE
Uncaught TypeError: t is not a constructor

### ISSUE THREAD

**Issue by peXed** [directus/directus#1676]
## Version Info
  - Directus version and branch: (Or commit hash)
  - PHP version: 7.1.6
  - MySQL version: MariaDB 10.1.24
  - Web server: XAMPP v3.2.2 (Apache)
  - OS name and version: Windows 10

## Expected Behavior
WYSIWYG Editor is working

## Actual Behavior
Error message is showing (javascript errror):

Error: Uncaught TypeError: t is not a constructor
File: http://localhost/directus/assets/js/directus.min.js?bust=1pasfno6iak7uootd0re7akllp
Line:38

## Steps to Reproduce
 1. Create new Table
 2. Add (Full) WYSIWYG Field
 3. Try to add new item to table

**Comment by rijkvanzanten** [comment]
I'm not able to reproduce this on `master`. @WellingGuzman I think the build bundle is missing (or breaking) TinyMCE somehow?

**Comment by WellingGuzman** [comment]
@rijkvanzanten It's highly what's happening, I will review this on the build branch and include TinyMCE or whatever is missing here.

Thanks for reporting this @peXed

**Comment by WellingGuzman** [comment]
The error still happen on the build branch, I'm going to update it soon.

What was fixed was the script that was causing the missing files.

**Comment by daddykom** [comment]
When this problem will be solved in the build?
