### ISSUE TITLE
Docker directus - extension changes not reflecting after npm run build

### ISSUE THREAD

**Issue by nehadnb** [directus/directus#16760]
### Describe the Bug

I have installed docker for directus following this documentation - https://docs.directus.io/self-hosted/installation/docker.html
Creating layout extension using this command `npm init directus-extension` in extensions/layouts folder
try to change layout.vue and run npm run build or npm run dev
index.js is updating after build
but it is not reflecting on browser

my docker-compose.yml file

    version: '3'
    services:
      database:
        platform: linux/x86_64
        container_name: database
        image: postgis/postgis:13-master
        volumes:
          - ./data/database:/var/lib/postgresql/data
        networks:
          - directus
        environment:
          POSTGRES_USER: 'directus'
          POSTGRES_PASSWORD: 'directus'
          POSTGRES_DB: 'directus'
    
    cache:
      container_name: cache
      image: redis:6
      networks:
        - directus
  
    directus:
      container_name: directus
      image: directus/directus:latest
      ports:
        - 8055:8055
      volumes:
        # By default, uploads are stored in /directus/uploads
        # Always make sure your volumes matches the storage root when using
        # local driver
        - ./uploads:/directus/uploads
        # Make sure to also mount the volume when using SQLite
        # - ./database:/directus/database
        # If you want to load extensions from the host
        - ./extensions:/directus/extensions
      networks:
        - directus
      depends_on:
        - cache
        - database
      environment:
        KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
        SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

        EXTENSIONS_AUTO_RELOAD: "true"
  
        DB_CLIENT: 'pg'
        DB_HOST: 'database'
        DB_PORT: '5432'
        DB_DATABASE: 'directus'
        DB_USER: 'directus'
        DB_PASSWORD: 'directus'
  
        CACHE_ENABLED: 'false'
        CACHE_STORE: 'redis'
        CACHE_REDIS: 'redis://cache:6379'
  
        ADMIN_EMAIL: 'admin@example.com'
        ADMIN_PASSWORD: 'd1r3ctu5'
  
        # Make sure to set this in production
        # (see https://docs.directus.io/self-hosted/config-options#general)
        # PUBLIC_URL: 'https://directus.example.com'
  
    networks:
      directus:

everytime i have restart docker to reflect my changes, How can i solve this? 

### To Reproduce

- Install directus using docker
- create new layout using `npm init directus-extension` in extensions/layouts folder and select javascript
- change layout.vue file and run npm run build or npm run dev
- make sure index.js updated in right folder 
- refresh browser

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

16.18.1

### What database are you using?

 Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by br41nslug** [comment]
What operating system are you using to host dockers? Not all OS's allow for watching file changes in mounted volumes.

**Comment by nehadnb** [comment]
MacOs M1 chip

**Comment by paescuj** [comment]
Can you please check if the `arm64` version of the image is loaded?

```bash
docker-compose exec directus arch
```

**Comment by nehadnb** [comment]
it is `aarch64`

**Comment by paescuj** [comment]
Just found this: https://github.com/directus/directus/issues/13675#issuecomment-1144580939

**Comment by nehadnb** [comment]
I am missing `PUBLIC_URL` in environment, after adding it changes are showing after npm run dev or build

Thanks

**Comment by claudiotassis** [comment]
> adding it changes are show

How did you do it? What changes did you make?

**Comment by paescuj** [comment]
@claudiotassis I'm not sure if that is already enough but according to @nehadnb it started working once the `PUBLIC_URL` environment variable has been defined:
```yaml
  # [...]
  directus:
    # [...]
    environment:
      # [...]
      EXTENSIONS_AUTO_RELOAD: "true"
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # for example:
      PUBLIC_URL: 'http://localhost:8055'
```
