### ISSUE TITLE
Infinite scroll not working (post 6.4.0 release)

### ISSUE THREAD

**Issue by peremp** [directus/directus#1677]
## Version Info
  - version: Master latest. This is **not** happening on the release version.

Looks like the table model no longer has the following attributes:
- Deleted
- Draft
- Published

So the method "getTotalCount" (collection.js) returns 0 for each visible state, and therefore no more items are loaded.

**Comment by benhaynes** [comment]
Thanks for reporting this one @peremp – we'll get this one fixed asap!

**Comment by peremp** [comment]
I found the bug on: a55b114

**Comment by WellingGuzman** [comment]
Thanks @peremp, We will work on it as soon as possible
