### ISSUE TITLE
"Save and stay" throwing error

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1678]
When choosing "save and stay" I am getting the following error. I can provide a schema to replicate.

```
Server Error
Undefined index: name
```

**Comment by WellingGuzman** [comment]
Please send me those through slack.

**Comment by benhaynes** [comment]
The first issue if fixed, but the relational fields are not showing data after saving:

![screen shot 2017-07-12 at 9 32 28 am](https://user-images.githubusercontent.com/522079/28120091-0ace15d2-66e5-11e7-881e-6b02a5d374dc.png)

**Comment by WellingGuzman** [comment]
This commit (https://github.com/directus/directus/commit/8fc347d9639218efaf1e04f77598f6dc7ee2a57f) should've fix this issue.

**Comment by benhaynes** [comment]
Yeehaw!
