### ISSUE TITLE
Sharp causing trouble with JPGs created on certain mobile devices

### ISSUE THREAD

**Issue by StephenGunn** [directus/directus#16794]
### Describe the Bug

Hi, I hate to trouble you with this but I've been trying to find the source of this bug for a while and I think I have it nailed down. I just don't know what to do about it.

I have a project that people upload photos of a weekly art challenge, and the users are very non-technical people. Some don't even have computers, just phones. I have been fighting about 1-2% of my users not getting past my upload form's error checking process. For the longest time I thought it was me or my users, but it looks like it's Sharp and Samsung's JPG creation not getting a long.

I know this is is Directus' issue board, but that's where I am having the problem and I don't know if there is anything I can do to help.

I found this bug report: https://github.com/lovell/sharp/issues/1578 talking about the issue.

The real issue comes when I try to convert the image to webp. The API errors and sends back a blank image.

### To Reproduce

This is a bit tricky, but you need to upload a JPG created on a samsung phone, here is one that caused the error: 
![amy](https://user-images.githubusercontent.com/7240548/207131343-ef0e2b0a-3c0d-4cfe-965e-8fb24afcd4e2.jpg)

I have confirmed that the above image was generated with Samsung Galaxy S21 Ultra.

Then you need to try and convert the image to webp via the API's image transformations.

This will cause an error in the API and deliver a blank image to the user.

### Errors Shown

![image](https://user-images.githubusercontent.com/7240548/207132438-d922a645-a62f-4ca7-a696-eb8ee8df30dd.png)

![image](https://user-images.githubusercontent.com/7240548/207132506-44eaf336-d657-4b4a-9e38-bfc92b0c952b.png)

```
Error: VipsJpeg: Invalid SOS parameters for sequential JPEG  

"message": "E_UNKNOWN: An unknown error happened with the file f6fdcdce-b7bc-48f8-a3d5-9cced867da75__165facd2baf7377772b0045e3f5b9a6644f04806.webp.\n\nError code: Error\nOriginal stack:
```

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

16.17.0

### What database are you using?

postgres 12

### What browser are you using?

chrome, firefox

### How are you deploying Directus?

self install, Ubuntu 22.04.1 LTS, manged by pm2

**Comment by StephenGunn** [comment]
Seems like the official fix for this is setting `failOnError: false` on the sharp constructor as a second argument. Seems like a  weak fix but if it works.. What would be the chances of getting something like this into the codebase? Should I fork my own and set it myself?

I've been looking for a way to correct these errors on upload but haven't found anything. Seems like Samsung just sucks.

**Comment by StephenGunn** [comment]
So, forked the latest release, built it locally, created a postgres db / DO space for files to mirror my main application.

Uploaded the image I posted above and got the same error when trying to load it in the media library:
![image](https://user-images.githubusercontent.com/7240548/207183798-7893ead3-bfde-4a5c-b70d-14b2411aef6d.png)

![image](https://user-images.githubusercontent.com/7240548/207183849-eaf205fc-1532-450e-ae64-a7bbdb62d306.png)


After adding the `failOnError:false` to the Directus codebase, evil Samsung JPGs starting loading with no error: 
![image](https://user-images.githubusercontent.com/7240548/207184345-ad05ad82-bba1-4e5c-969c-2562dea2b411.png)

Thoughts on making a pull request for this fix? Doesn't seem like samsung is going to fix their JPG encoding any time soon and I could really use this.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-110](https://linear.app/directus/issue/ENG-110/sharp-causing-trouble-with-jpgs-created-on-certain-mobile-devices)

**Comment by rijkvanzanten** [comment]
Ha what an absolutely fascinating situation. I would've never thought that Samsung would produce invalid JPEG formats for those inputs 😅 I'd normally be low-key inclined to go "not my problem", but it's a little hard for Directus to tell Samsung to go fix something on their end haha...

Tim's PR seems like the cleanest in-between solution! We'll keep the defaults safe as-is, but allow you to optionally reduce Sharp's strictness which in turn allows for this situation to be avoided 🙂
