### ISSUE TITLE
no logger messages in terminal for schema apply

### ISSUE THREAD

**Issue by leonroman** [directus/directus#16806]
### Describe the Bug

Starting with Directus v9.19.0, logger messages, stopped to appear in terminal for schema apply. 
This issue is valid starting with Directus v9.19.0

**Example for Directus 9.18.1:**
ubuntu@ip:\~/testproject$ npx directus --version
9.18.1
ubuntu@ip:\~/testproject$ npx directus schema apply snapshot.yaml
**15:00:31 ✨ No changes to apply.**

**Example for Directus 9.19.0:**
ubuntu@ip:\~/testproject$ npx directus --version
9.19.0
ubuntu@ip:\~/testproject$ npx directus schema apply snapshot.yaml
**<here must be the massage "No changes to apply.">**

### To Reproduce

Install Directus v9.19.0 till latest.
Create a snapshot:
npx directus schema snapshot ./snapshot.yaml
Use the same snapshot:
npx directus schema apply ./snapshot.yaml

Error expected: no feedback message displayed

### Errors Shown

No error - No log massages displayed in terminal for schema apply

### What version of Directus are you using?

9.19.0

### What version of Node.js are you using?

16.17.0

### What database are you using?

Aurora PostgreSQL 10.18.5

### What browser are you using?

Firefox 107.0.1

### How are you deploying Directus?

running locally

**Comment by br41nslug** [comment]
This was solved in https://github.com/directus/directus/issues/16284 and will be fixed in the next release.
The current workaround for this problem is temporarily setting your `LOG_STYLE` to `RAW` in the environment variables

**Comment by leonroman** [comment]
I am using config.json instead of .env

 "LOG_STYLE": "RAW" - RAW in UPPERCASE no working 

 with "LOG_STYLE": "raw"
 ubuntu@ip:~/testproject$ npx directus schema apply snapshot.yaml
{"level":30,"time":1670942274640,"pid":137851,"hostname":"ip","msg":"No changes to apply."}

Thank you!
