### ISSUE TITLE
A user who has readonly rights on a collection should not be allowed to activate the manual sort

### ISSUE THREAD

**Issue by Pachat** [directus/directus#16807]
### Describe the Bug

On a collection that has a Sort field and on which a role is Read only
the user can still activate the manual sort

### To Reproduce

- Set a collection with a Sort field 
- Set a Regular role with Read only permissions on that collection
- Show the collection

### Errors Shown

- The user can still activate the manual sort

_it has no update effect, but still this gives the false impression to the user that he can reorder the collection_

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

19.0.1

### What database are you using?

Postgresql 15

### What browser are you using?

Firefox & Edge

### How are you deploying Directus?

VPS

**Comment by rijkvanzanten** [comment]
Linear: [ENG-109](https://linear.app/directus/issue/ENG-109/a-user-who-has-readonly-rights-on-a-collection-should-not-be-allowed)
