### ISSUE TITLE
No UTF-8 (special characters) on CSV export

### ISSUE THREAD

**Issue by cs1m0n** [directus/directus#16818]
### Describe the Bug

When exporting items from a collection (to a CSV file), special characters are replaced with weird characters - in my use case there are Norwegian specific characters.

I know CSV does not support UTF-8 characters by default but there is also a similar filetype called CSV UTF-8 (Comma delimited) which should support "special characters".

### To Reproduce

Export an item from a collection which contains special characters in the field value.

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

Postgres 14.4.1

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by paescuj** [comment]
Quick note: That would be the `withBOM` option from [json2csv](https://juanjodiaz.github.io/json2csv/#/parsers/parser?id=options). See also https://juanjodiaz.github.io/json2csv/#/others/known-gotchas?id=unicode-support.

> [...] there is also a similar file type called CSV UTF-8 [...]

What do you mean by that? I'm not aware of such a file type.

By the way: I'm able to open a CSV file containing UTF-8 characters with LibreOffice out of the box. So this primarily seems to be a thing in Excel.

**Comment by cs1m0n** [comment]
From Microsoft Excel you can Save as CSV with 4 different filetypes:
1. CSV UTF-8 (Comma delimited)
2. CSV (Comma delimited)
3. CSV (Macintosh)
4. CSV (MS-DOS)

Where 1 & 2 seem to support special characters, while 3 & 4 don't.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-108](https://linear.app/directus/issue/ENG-108/no-utf-8-special-characters-on-csv-export)

**Comment by cs1m0n** [comment]
This is actually a very easy fix. Check this: https://github.com/eligrey/FileSaver.js/issues/28

**Comment by rijkvanzanten** [comment]
> This is actually a very easy fix. Check this: [eligrey/FileSaver.js#28](https://github.com/eligrey/FileSaver.js/issues/28)

Wanna open a PR?? 🙂  @cs1m0n

**Comment by cs1m0n** [comment]
#16835 actually addresses this (as well as adding delimiter support) better than the fix I've suggested above since [json2csv](https://juanjodiaz.github.io/json2csv/#/parsers/parser?id=options) already has a `withBOM` option.
Thank you for taking the time to look at this!

**Comment by LevelUpGit** [comment]
@cs1m0n We agree, it's a real issue both no UTF-8 support and fixed delimiter to comma.

**Comment by vwasteels** [comment]
I am still experiencing this issue, is there any plan on fixing it ?

thanks

![Capture d’écran 2024-10-14 à 14 09 01](https://github.com/user-attachments/assets/bec24983-42e6-4d9b-ad67-a73dee1024d0)

**Comment by rijkvanzanten** [comment]
@vwasteels What database are you using? How are you exporting currently? What type of field is that? I haven't been able to reproduce the original issue (and can't yet now either..)
