### ISSUE TITLE
Messaging w/Groups Possible Bug

### ISSUE THREAD

**Issue by JREAM** [directus/directus#1682]
## Version Info
  - Directus version and branch: master (6.4)
  - PHP version: 7.0
  - MySQL version:  Percona 5.7 (strict mode disabled)
  - Web server: (Ex. Apache, nginx or IIS?)  Apache
  - OS name and version: Ubuntu 16.04 x64

## Expected Behavior
- Message to Send to all users in a Group (If this was intended)
- Message to archive (works) but not have additional errors.

## Actual Behavior
Red-box Popup Error Messages, and at one point the left column had a table disappear as if the JS was not updated.

## Steps to Reproduce
1: Create New Group, I called mine "Developers"
2: Go to Messages
3: Try to message Group (Nobody is in there), and try when someone is in there. `The reason I tried this is because it auto-suggested it, USER TO USER WORKS`
4: Message I get is:
```Server Error
This query failed: SELECT `directus_users`.`id` AS `id`, `directus_users`.`group` AS `group` FROM `directus_users` WHERE `group` IN ('3') AND = '1'"```

Also, when you click "Archive" with nothing selected, you get:
```Server Error
Invalid argument supplied for foreach()
```
It should just say "Select message(s) to archive" / When selected it works fine.

However, as soon as you archive it, I get this message:
```Error
Error: Uncaught TypeError: Cannot read property 'id' of undefined
File: http://projects/directus/app/app.js?bust=91ef1a82193af5ada272115a30c82cc8b22bea3c
Line:121
```

It seems to think the ID for the message is still there, or supposed to be in the JS.

## Logs or Screenshots
![image](https://user-images.githubusercontent.com/145959/28071841-320c9e32-661f-11e7-870b-3d094ba702e2.png)

**Comment by WellingGuzman** [comment]
Hey @JREAM, I've fixed some issues with messages including:

- Sending messages to an empty group
- Removing a message that was already empty and sent to no one
- Archive threads now archive ALL responses too

Please confirm this patch fixes all the issues mentioned above to you too.

**Comment by JREAM** [comment]
Will check soon!

**Comment by benhaynes** [comment]
Thanks @JREAM – we'd love to close this if it's resolved, so let us know!

**Comment by benhaynes** [comment]
Any update @JREAM?

**Comment by benhaynes** [comment]
Since @WellingGuzman has fixed several issues and @JREAM hasn't responded in over a month I'll close this one. Please re-open if this is still an issue.
