### ISSUE TITLE
REST user creation return no user object on success

### ISSUE THREAD

**Issue by conorhub** [directus/directus#16837]
### Describe the Bug

Creating new users via POST in REST API returns nothing after a successful user creation.
I expected a user object to be returned.
Errors return error objects fine, it's only on succesful creation do I receive no response.

### To Reproduce

Using postman (or equivalent) do the following:

**POST** to server at:
`https://yourserveraddress/users`

**Headers**
`Content-Type: application/json`

**Body
RAW JSON**

```
{
    "first_name": "testuser",
    "email": "anemail@email.com",
    "password": "123456789",
}
```

No auth or tokens as I've set the public role for directus_users to all_access for create

Response is blank, unless there has been an error, but Directus model shows a new user was succesfully created with all values, upon inspection.

### Errors Shown

In postman, no.

In my javascript frontend, an await function trying to return the response throws an error:

`Uncaught (in promise) SyntaxError: Unexpected end of JSON input`

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

The version provided in Docker 9.21.2 image

### What database are you using?

MySQL 8

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
> Creating new users via POST in REST API returns nothing after a successful user creation.
I expected a user object to be returned.

> No auth or tokens as I've set the public role for directus_users to all_access for create

This should be because you have allowed access for create, but not _read_, hence the empty response (but it does create it successfully). Make sure to grant read access as well. 👍

**Comment by rijkvanzanten** [comment]
You could configure the read permissions to only allow read access to items where id equals $CURRENT_USER

**Comment by conorhub** [comment]
@rijkvanzanten Unless I'm misunderstanding, this won't work for the situation I mentioned, where the public role can create new users.

If it's a public role creating a new user, there's no $CURRENT_USER to equate against.

I'm trying to find a way to for the public role to be able to create new users but to not let the public role be able to pull a list of every user.

As a background, I just need users of my web app to be able to register themselves, so I'm doing it via a form on the frontend and using REST api. I don't believe that there's currently a method to register new users in the backend UI without being created by an existing user.

**Comment by azrikahar** [comment]
> As a background, I just need users of my web app to be able to register themselves, so I'm doing it via a form on the frontend and using REST api. I don't believe that there's currently a method to register new users in the backend UI without being created by an existing user.

An alternative would be to disable any permissions for the public role to `directus_user`, and create a [custom endpoint extension](https://docs.directus.io/extensions/endpoints.html) or a [Flows webhook trigger](https://docs.directus.io/configuration/flows/triggers.html#webhook) to act as the API for public registration 👍

> I'm trying to find a way to for the public role to be able to create new users but to not let the public role be able to pull a list of every user.

This is currently discussed in #11464, but in the mean time you may also try this extension shared in that discussion: https://github.com/directus/directus/discussions/11464#discussioncomment-4227415
