### ISSUE TITLE
Flow: Mail not sent when the body contains only {{$trigger.payload}}

### ISSUE THREAD

**Issue by Pachat** [directus/directus#16842]
### Describe the Bug

When the body is only `{{$trigger.payload}}` the mail is not sent.

### To Reproduce

Send a mail from a flow only `Details: {{$trigger.payload}}` in the body. The mail is sent.
Modify the body of the mail to only `{{$trigger.payload}}` in the body. 

_Not very important, but may hide some other potential bug_

### Errors Shown

The mail is not sent when reduced to `{{$trigger.payload}}`

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

19.0.1

### What database are you using?

Postgresql 15

### What browser are you using?

Firefox & Edge

### How are you deploying Directus?

VPS

**Comment by rijkvanzanten** [comment]
Linear: [ENG-306](https://linear.app/directus/issue/ENG-306/flow-mail-not-sent-when-the-body-contains-only-dollartriggerpayload)

**Comment by rijkvanzanten** [comment]
Are there any errors thrown? What trigger are you using? What is the payload of the trigger that you're trying to use?

**Comment by Pachat** [comment]
![Flow](https://user-images.githubusercontent.com/13746133/208399171-81c801bb-266d-4161-bcdb-8d262834f4cf.png)
![Payload](https://user-images.githubusercontent.com/13746133/208399796-9399bee6-2fde-423f-9fad-ff5462dbc7f9.png)
No email sent. No error.



---

Now after adding some text:

![Flow 2](https://user-images.githubusercontent.com/13746133/208399274-0a0cb6b5-2e67-4510-92fb-0e37fb275e17.png)
![Payload-2](https://user-images.githubusercontent.com/13746133/208399909-06856963-2eba-4263-a116-82a968183ef4.png)
Email sent.
