### ISSUE TITLE
Unable to get to installation page

### ISSUE THREAD

**Issue by jdblack** [directus/directus#1685]
## Version Info
  - Directus version and branch: Github tag 6.4.0
  - PHP version:  libapache2-mod-php7.0             7.0.18-0ubuntu0.16.04.1
  - Web server: apache2           2.4.18-2ubuntu3.3 
  - OS name and version:  Ubuntu 16.04

## Expected Behavior
I expect  to be able to get to the login page

## Actual Behavior
I get a 404 that redirects me to   /s/hashyuuid/  
==> DirectUS-error.log <==

curl http://localhost:8080 -L

[Wed Jul 12 23:27:29.899789 2017] [rewrite:trace1] [pid 31212] mod_rewrite.c(476): [client 127.0.0.1:39202] 127.0.0.1 - - [localhost/sid#7efcca69ca70][rid#7efcca6720a0/initial] pass through /
[Wed Jul 12 23:27:29.900117 2017] [rewrite:trace1] [pid 31212] mod_rewrite.c(476): [client 127.0.0.1:39202] 127.0.0.1 - - [localhost/sid#7efcca69ca70][rid#7efcca6720a0/initial] [perdir /mnt/directus/current/] pass through /mnt/directus/current/
[Wed Jul 12 23:27:29.900143 2017] [rewrite:trace1] [pid 31212] mod_rewrite.c(476): [client 127.0.0.1:39202] 127.0.0.1 - - [localhost/sid#7efcca69ca70][rid#7efcca6740a0/subreq] pass through /index.html
[Wed Jul 12 23:27:29.900256 2017] [rewrite:trace1] [pid 31212] mod_rewrite.c(476): [client 127.0.0.1:39202] 127.0.0.1 - - [localhost/sid#7efcca69ca70][rid#7efcca6740a0/subreq] [perdir /mnt/directus/current/] pass through /mnt/directus/current/index.html
[Wed Jul 12 23:27:29.900275 2017] [rewrite:trace1] [pid 31212] mod_rewrite.c(476): [client 127.0.0.1:39202] 127.0.0.1 - - [localhost/sid#7efcca69ca70][rid#7efcca6740a0/subreq] pass through /index.cgi
[Wed Jul 12 23:27:29.900337 2017] [rewrite:trace1] [pid 31212] mod_rewrite.c(476): [client 127.0.0.1:39202] 127.0.0.1 - - [localhost/sid#7efcca69ca70][rid#7efcca6740a0/subreq] [perdir /mnt/directus/current/] pass through /mnt/directus/current/index.cgi
[Wed Jul 12 23:27:29.900354 2017] [rewrite:trace1] [pid 31212] mod_rewrite.c(476): [client 127.0.0.1:39202] 127.0.0.1 - - [localhost/sid#7efcca69ca70][rid#7efcca6740a0/subreq] pass through /index.pl
[Wed Jul 12 23:27:29.900416 2017] [rewrite:trace1] [pid 31212] mod_rewrite.c(476): [client 127.0.0.1:39202] 127.0.0.1 - - [localhost/sid#7efcca69ca70][rid#7efcca6740a0/subreq] [perdir /mnt/directus/current/] pass through /mnt/directus/current/index.pl
[Wed Jul 12 23:27:29.900432 2017] [rewrite:trace1] [pid 31212] mod_rewrite.c(476): [client 127.0.0.1:39202] 127.0.0.1 - - [localhost/sid#7efcca69ca70][rid#7efcca6740a0/subreq] pass through /index.php
[Wed Jul 12 23:27:29.900485 2017] [rewrite:trace1] [pid 31212] mod_rewrite.c(476): [client 127.0.0.1:39202] 127.0.0.1 - - [localhost/sid#7efcca69ca70][rid#7efcca6740a0/subreq] [perdir /mnt/directus/current/] pass through /mnt/directus/current/index.php

==> DirectUS-access.log <==
127.0.0.1 - - [12/Jul/2017:23:27:29 +0000] "GET / HTTP/1.1" 302 - "-" "curl/7.47.0"

==> DirectUS-error.log <==
[Wed Jul 12 23:27:29.900831 2017] [rewrite:trace1] [pid 31212] mod_rewrite.c(476): [client 127.0.0.1:39202] 127.0.0.1 - - [localhost/sid#7efcca69ca70][rid#7efcca66e0a0/initial] pass through /installation/index.php
[Wed Jul 12 23:27:29.900988 2017] [rewrite:trace1] [pid 31212] mod_rewrite.c(476): [client 127.0.0.1:39202] 127.0.0.1 - - [localhost/sid#7efcca69ca70][rid#7efcca66e0a0/initial] [perdir /mnt/directus/current/] pass through /mnt/directus/current/installation/index.php

==> DirectUS-access.log <==
127.0.0.1 - - [12/Jul/2017:23:27:29 +0000] "GET /installation/index.php HTTP/1.1" 302 - "-" "curl/7.47.0"

==> DirectUS-error.log <==
[Wed Jul 12 23:27:29.902278 2017] [rewrite:trace1] [pid 31212] mod_rewrite.c(476): [client 127.0.0.1:39202] 127.0.0.1 - - [localhost/sid#7efcca69ca70][rid#7efcca6720a0/initial] pass through /s/40737d0b1640aeb6b32026e13747f4fa731d385d/installation/index.php
[Wed Jul 12 23:27:29.902417 2017] [rewrite:trace1] [pid 31212] mod_rewrite.c(476): [client 127.0.0.1:39202] 127.0.0.1 - - [localhost/sid#7efcca69ca70][rid#7efcca6720a0/initial] [perdir /mnt/directus/current/] pass through /mnt/directus/current/s
[Wed Jul 12 23:27:29.902440 2017] [core:info] [pid 31212] [client 127.0.0.1:39202] AH00128: File does not exist: /mnt/directus/current/s/40737d0b1640aeb6b32026e13747f4fa731d385d/installation/index.php

==> DirectUS-access.log <==
127.0.0.1 - - [12/Jul/2017:23:27:29 +0000] "GET /s/40737d0b1640aeb6b32026e13747f4fa731d385d/installation/index.php?step=0 HTTP/1.1" 404 324 "-" "curl/7.47.0"

# /etc/apache2/sites-enabled/DirectUS.conf
```
# Managed by chef
<VirtualHost *:8080>
  ServerName localhost
  DocumentRoot /mnt/directus/current

#  <Directory /mnt/directus/current>
<Directory /mnt>
    AddType application/x-httpd-php .php
    Options FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>


  <Location /server-status>
    SetHandler server-status

    Require local

  </Location>

  RewriteEngine On
  LogLevel info rewrite:trace1
  ErrorLog /mnt/directus/current/log/DirectUS-error.log
  CustomLog /mnt/directus/current/log/DirectUS-access.log combined


  # Canonical host, localhost
#  RewriteCond %{HTTP_HOST}   !^localhost [NC]
#  RewriteCond %{HTTP_HOST}   !^$
#  RewriteRule ^/(.*)$        http://localhost/$1 [L,R=301]
#
#  RewriteCond %{DOCUMENT_ROOT}/system/maintenance.html -f
#  RewriteCond %{SCRIPT_FILENAME} !maintenance.html
#  RewriteRule ^.*$ /system/maintenance.html [L,R=503]
</VirtualHost>
```

## /mnt/directus/current (a symlink to /mnt/directus/releases/alonghash)
```

# Hide directory listings
Options -Indexes

# No font warnings please
AddType font/ttf .ttf
AddType font/eot .eot
AddType font/otf .otf
AddType font/woff .woff

<ifModule mod_rewrite.c>
    RewriteEngine On
    # Uncomment this if you are getting routing errors:
    #RewriteBase /

    RewriteRule ^assets - [L,NC]
    RewriteRule ^extensions/([^/]+) - [L,NC]
    RewriteRule ^extensions/([^/]+)/assets - [L,NC]
    RewriteRule ^extensions/([^/]+)/main.js - [L,NC]

    RewriteRule ^listviews/([^/]+) - [L,NC]
    RewriteRule ^listviews/([^/]+)/assets - [L,NC]
    RewriteRule ^listviews/([^/]+)/ListView.js - [L,NC]

    # Files Proxy
    # - Only define one of the URL segments /.../ here so that the request format
    #   can be more flexibly maintained in the PHP/Slim router
    # @NOTE: media_auth_proxy was removed
    # @TODO: Implement files proxy using the new files object
    # RewriteCond %{REQUEST_URI} media_auth_proxy/([^/]+)/(.+)$
    # RewriteRule ^ /media_auth_proxy/index.php [L]

    # Directus Front Controller
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} !index
    RewriteRule (.*) index.php [L]

</ifModule>

<ifModule mod_php5.c>
    # Fix $HTTP_RAW_POST_DATA deprecated warning
    php_value always_populate_raw_post_data -1
</ifModule>

# Prevent PageSpeed module from rewriting the templates files
# Avoiding it from breaking the template
<IfModule pagespeed_module>
    ModPagespeedDisallow "*/app/**/*.html"
</IfModule>
```

**Comment by WellingGuzman** [comment]
Hey @jdblack, I have fix how we get the real Directus root path. please get the latest code from the `master` branch, and let us know if that patch fixes the problem you were having.

**Comment by cesasol** [comment]
@WellingGuzman I have the same issue under shared hosting. In my case redirects to a truncated parent directory `http://api.dinamo.mx/amo.mx/html/installation/index.php?step=0`
the filesystem path is `/home/XXX/domains/api.dinamo.mx` and the symlink is `/home/XXXX/users/.home/domains/api.dinamo.mx`.

PHP version:  
PHP 5.6.21 (cli) (built: May 23 2016 18:42:48)

I already tried with the master branch having the same error

**Comment by benhaynes** [comment]
Hey @jdblack – if you have time, could you post a quick comment about this ticket's resolution? Especially given that @cesasol seems to be having a similar issue still.

**Comment by cesasol** [comment]
Strange that the issue went away from last night attemp. Maybe my host was keeping some sort of cache

**Comment by jdblack** [comment]
This issue went away from me when I switched from the 4.6.0 branch to  the master branch as per wellingguzman's  comment.

**Comment by Faey2222** [comment]
Unfortunately I have the same issue with the current version "6.4.5-20171218214440".

PHP 5.6.32 (cli)

Linux lupus.uberspace.de 2.6.32-696.18.7.el6.x86_64 #1 SMP Thu Jan 4 17:31:22 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by WellingGuzman** [comment]
What issue exactly are you having @jknigga? Directus or configuration issues?

**Comment by jknigga** [comment]
I cannot get to the installation page. I get a 404 error.

The system path is /web/groups/jakob/public_html/directus/. My web root is public_html, so my site sits at www.website.com/jakob/directus/. When I go to this page, it redirects to www.website.com/jakob/public_html/directus/installation/index.php?step=0, which doesn't exist. I have tried to manually set the path in multiple places, including "get_directus_path()", but to no avail.

**Comment by WellingGuzman** [comment]
how you `config.php` looks like? it seems you have the `DIRECTUS_PATH`, sets wrong, which means it has to be `/directus/`.

**Comment by jknigga** [comment]
@WellingGuzman - Doesn't the config file get generated during the install? I can't get to the install page.

**Comment by WellingGuzman** [comment]
@jknigga yes, the config file gets generated on installation (last step). do you have the `config.php` file?

**Comment by WellingGuzman** [comment]
Due to inactivity I'm going to close this ticket until we hear back about the new issue on installation page.
