### ISSUE TITLE
Fix URL for subfolders for export files

### ISSUE THREAD

**Issue by christianrr** [directus/directus#16865]
### Describe the Bug

When Directus is served from a subfolder, the export file paths are broken (subfolder appears twice). The reason is that `exportDataLocal()` uses both `getBasePath` and `api.get()`. However, `api.get()` uses `getRootPath()` internally, which leads to an invalid URL.

Similar issue:
https://github.com/directus/directus/pull/15126

### To Reproduce

- Serve Directus from subfolder
```
PUBLIC_URL="https://example.domain.com/cms/"
ROOT_REDIRECT="./cms/admin"
```
- Export files

### Errors Shown

Route does not exist

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

16

### What database are you using?

MySQL

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
I believe this is the same issue as #16718, which was fixed by #16724 in `9.22.0` onwards. Let us know whether upgrading fixes it for you 👍

>  However, `api.get()` uses `getRootPath()` internally, which leads to an invalid URL.

Nice catch! Seems to be exactly the solution used in #16724 by changing it from `getRootPath()` to `getPublicURL()` instead.
