### ISSUE TITLE
Assets 500 / 403 after updating to 9.22.0 using Digital Ocean Spaces S3 for storage (App / API)

### ISSUE THREAD

**Issue by StephenGunn** [directus/directus#16876]
### Describe the Bug

9.22.0 fixes a problem for me so I was eager to upgrade.

After upgrading, all of my assets either 500 or 403 in the admin app and when requested through the API. It's mostly 403 errors but I have also seen some 500s mixed in.

I ran the usual upgrade process specified in: https://docs.directus.io/self-hosted/upgrades-migrations.html#upgrading-updating-a-project

I am not sure if I missed something on the upgrade. I know the file system got a lot of changes. I tried to read through them to see if I need to reconfigure something in my .env but I couldn't find anything.

### To Reproduce

Upgrade from 9.21.2 -> 9.22.0 and check the File Library.

### Errors Shown

The errors aren't very verbose:

![image](https://user-images.githubusercontent.com/7240548/208995605-3b9b3091-717d-4ea9-a596-fd4aefb0ec7e.png)

![image](https://user-images.githubusercontent.com/7240548/208995643-4cf747fa-4a1b-4704-b48f-775c0ee51b74.png)

### What version of Directus are you using?

9.22.0

### What version of Node.js are you using?

v18.12.1

### What database are you using?

postgres 12

### What browser are you using?

chrome / firefox

### How are you deploying Directus?

self install, Ubuntu 22.04.1 LTS, manged by pm2

**Comment by rijkvanzanten** [comment]
What env vars are you using with spaces? (make sure to redact key/secret)? 🙂 The file storage updates abstraction upgraded AWS's S3 SDK from v2 to v3, so maybe something went sideways in the compatibility with DigitalOcean spaces.

**Comment by StephenGunn** [comment]
Here is the .env with data removed, is this enough info?

![image](https://user-images.githubusercontent.com/7240548/208996590-f7e5b829-75e9-4b88-b808-94523a7de8af.png)

**Comment by rijkvanzanten** [comment]
@StephenGunn ty! Yes I'm gonna go give it a shot. I tested against s3 and minio, so curious to see what about DO Spaces changes things.

**Comment by rijkvanzanten** [comment]
<img width="581" alt="CleanShot 2022-12-21 at 15 51 45@2x" src="https://user-images.githubusercontent.com/9141017/209000602-cd97e5cc-0bfa-4861-8c9f-824e7eb1ab08.png">

hmm i'm not currently able to spin up a new Spaces bucket on DO, so I'll have to figure out how to debug this efficiently

**Comment by bryantgillespie** [comment]
I'm using DO Spaces for my Better Sign Shop app. And it broke the assets as soon as I updated Directus to 9.22.1.

Found this article after @rijkvanzanten mention the updated version of the AWS SDK.
https://docs.digitalocean.com/products/spaces/reference/s3-sdk-examples/#configure-a-client

Here's the bit from the article
> Due to an AWS-specific behavior in all versions of the SDK except Python 3, to successfully create a new bucket, you must specify an AWS region, such as us-east-1, in your configuration. This is because, when creating a bucket, the SDK sends an entirely different payload if a custom region is specified, which results in an error. Region does not affect any other examples listed in this page.

> Note, specifying us-east-1 does not result in slower performance, regardless of your bucket’s location. The SDK checks the region for verification purposes but never sends the payload there. Instead, it sends the payload to the specified custom endpoint.

Here's what I had and the changes I made. Working for now 🤞 .
<img width="653" alt="ScreenShot 2022-12-21 at 19 59 01@2x" src="https://user-images.githubusercontent.com/23302570/209031990-61b4effe-55e6-40ec-80d5-2767b039d4ba.png">

**Comment by StephenGunn** [comment]
From working with Rijk earlier, adding the https:// to the endpoint was part of the fix. I still have nyc3 as my region and it works.

**Comment by kroawen** [comment]
same problem for me,
I use Alibaba oss storage, .env config similar with S3 , 9.21.2 it worked, but 9.22.1 not.
![image](https://user-images.githubusercontent.com/6927999/209038009-6e74cd87-5152-4cd4-a157-edb29f8676d1.png)

**Comment by preetamslot** [comment]
@bryantgillespie 
I also use Spaces, after adding https:// to the endpoint I can upload new files, but older files still don't have permission to be shown in the CMS :(

How do I get the permissions back?

![image](https://user-images.githubusercontent.com/5420582/209949261-b25a1fa5-b7b3-4903-9988-30c2eac09587.png)

**Comment by hamza-zafar-319** [comment]
I have a similar issue with Google Cloud Storage. I can upload new files but trying to view/download existing files gives a  403  error.

**Comment by preetamslot** [comment]
@rijkvanzanten Do you have any pointers on how to restore the permissions of files uploaded by a previous version of Directus?

**Comment by gecode-es** [comment]
I had also been successfully using Cloudflare R2 storage which was compatible with the S3 driver. I now receive "missing region" errors. This is even the case with Directus version 9.22.1

**Comment by StephenGunn** [comment]
Yes, and I have updated more projects by adding https:// to the endpoint.

**Comment by phihu** [comment]
> @StephenGunn Does it work on your DO spaces? I still have 403 on previously uploaded files.
> 
> ```
> STORAGE_DIGITALOCEAN_DRIVER="s3"
> STORAGE_DIGITALOCEAN_KEY="********"
> STORAGE_DIGITALOCEAN_SECRET="**********"
> STORAGE_DIGITALOCEAN_ENDPOINT="https://fra1.digitaloceanspaces.com"
> STORAGE_DIGITALOCEAN_BUCKET="********"
> STORAGE_DIGITALOCEAN_REGION="fra1"
> STORAGE_DIGITALOCEAN_ROOT="/"
> STORAGE_DIGITALOCEAN_PUBLIC_URL="********"
> STORAGE_DIGITALOCEAN_ACL="public-read"
> ```
> 
> ```
> "errors": [
>    {
>       "message": "You don't have permission to access this.",
>       "extensions": {
>       "code": "FORBIDDEN"
>    }
> ]
> ```

Just in case you're still having trouble, we were able to fix it (using DO in Germany, too). 

You have to add the 'https://' to the endpoint AND you have change the region key to a 'valid' S3 region code. We are using the Frankfurt data center, too. We used 'eu-central-1' instead of 'fra1'.
I actually don't think the region code itself even matters as long as it passes validation, but haven't had the time to check that last bit...

```
STORAGE_DIGITALOCEAN_ENDPOINT="https://fra1.digitaloceanspaces.com"
STORAGE_DIGITALOCEAN_REGION="eu-central-1"

``` 
Hope that helps!

**Comment by botzill** [comment]
We are using DO as well and I set for region `eu-central-1`, but after some time I see the same error, 403

**Comment by phihu** [comment]
Sorry for asking, but did you check you've changed both:
`STORAGE_DIGITALOCEAN_REGION="eu-central-1"` 
and
`STORAGE_DIGITALOCEAN_ENDPOINT="https://fra1.digitaloceanspaces.com"`?
It only worked after both keys had been changed accordingly.

**Comment by botzill** [comment]
Yes, for me this values are:

`https://ams3.digitaloceanspaces.com`
`eu-central-1`

**Comment by phihu** [comment]
Sorry it didn't work for you! 
For the lack of any better idea, I would try changing the region code and contact DO support, maybe this problem (at least from this point) is (also) DO related...

**Comment by preetamslot** [comment]
> Sorry it didn't work for you! For the lack of any better idea, I would try changing the region code and contact DO support, maybe this problem (at least from this point) is (also) DO related...

@phihu Can you let me know what the question to DO should be?
If I tell them that:

> After upgrading to the latest version **of directus**, **in directus CMS** we lost permissions to view media uploaded in the older version **of directus**. but media uploaded in the newer version **of Directus** works fine.


I think they they redirecting me to this place :P

**Comment by phihu** [comment]
@preetamslot Yeah, that would not be how I would phrase it...
I would tell them about the problem, confirm the values of all the keys/configs you used and check if they have additional information regarding the error (logs, any details). Perhaps there is a problem related to you specific configuration rather then the storage api/directus.

**Comment by preetamslot** [comment]
@phihu I found the critter, it was:
```
STORAGE_DIGITALOCEAN_ROOT="/"
```
After removing that line all works again.
