### ISSUE TITLE
Previous comments not showing to non admin users

### ISSUE THREAD

**Issue by renjith341** [directus/directus#1687]
## Version Info
  - Directus version and branch: 6.4
  - PHP version: 7.0.10 
  - MySQL version: 5.7.14
  - Web server: Apache
  - OS name and version: Windows 7

## Expected Behavior
Users who has got permission to view messages and 'can comment' has to view previous comments on table content edit page.

## Actual Behavior
On table content edit page no previous comments are shown. When user adds a new comment, all the comments are shown including previous comments.

## Steps to Reproduce
 1. Create a table name it 'books'
 2. create a group book owners and give full permission to books & directus_messages then
assign one user to this group
 3. Add some content to books by administrator and add some comments
 4. Login as book user edit book and user wont see any comments, add one comment then user can see all comments.

**Comment by WellingGuzman** [comment]
Hey @renjith341,

This commit (https://github.com/directus/directus/commit/fd508cd8d11c7bb0169ed446862b5ff447d6f506) should've fixed the issue. please confirm either way.

**Comment by nithinga** [comment]
@WellingGuzman Solved

**Comment by WellingGuzman** [comment]
Thanks for the confirmation!
