### ISSUE TITLE
After upgrade to 9.22.1 app content shows empty table occasionally

### ISSUE THREAD

**Issue by aclisp** [directus/directus#16883]
### Describe the Bug

https://user-images.githubusercontent.com/5406765/209098901-d9b02887-7c57-4111-a57e-955f98280ed9.mov

### To Reproduce

1. Upgrade to 9.22.1
2. Start Directus locally
3. Login as admin, go to `/admin/content/`
4. Switch between different collections, the problem occurs.

### Errors Shown

No

### What version of Directus are you using?

v9.22.1

### What version of Node.js are you using?

v18.12.1

### What database are you using?

SQLite

### What browser are you using?

Google Chrome

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment]
Hi! Would you mind checking the browser devtools network tab to see whether there's request(s) being canceled when you're switching between them? For example, when you switch from "Product" to "Product Order", there should likely be a canceled request to `/items/product`. If it is, this should be resolved by #16881.

**Comment by KayhanB** [comment]
I'm faced too with this issue and request is not canceling when switching between collections. Maybe this is another issue

**Comment by jotatoledo** [comment]
Came to report the same, see the attached files

[bug_collections.webm](https://user-images.githubusercontent.com/20740204/209168972-9a253079-f185-441d-af6e-a6e85bedb716.webm)

**Comment by azrikahar** [comment]
Thanks for the reports! Slight correction to my previous comment, this issue actually isn't exclusively happening when there are canceled requests 👍 The linked PR does still resolve this issue (especially the newer commits in that PR).

**Comment by u12206050** [comment]
@rijkvanzanten Please hot fix this :)

**Comment by eikaramba** [comment]
please do a new release, this is a blocker for us to update to the latest version and given the amount of new tickets and people with the same problem i am curious why a hotfix release was not considered. Maybe it is too late now and a new release is imminent, but if not then my suggestion stands.
