### ISSUE TITLE
Latest docker tag won't start

### ISSUE THREAD

**Issue by donaldrich80** [directus/directus#16888]
### Describe the Bug

It appears the latest docker tag is a defective build.

After being updated by watchtower, directus became unresponsive.  A cold restart didn't fix the issue.

Rolling back to 9.21 restored functionality.

Happy Holidays!

### To Reproduce

Launch an instance using recent latest docker image

### Errors Shown

Log:
```
Node.js v18.12.1
[12:16:11.792] INFO: Server started at http://0.0.0.0:8055/
node:events:491
      throw er; // Unhandled 'error' event
      ^
Error: ENOENT: no such file or directory, open '/directus/uploads/health-VZWFY'
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {

  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/directus/uploads/health-VZWFY'
}
```

### What version of Directus are you using?

directus/directus:latest

### What version of Node.js are you using?

directus/directus:latest

### What database are you using?

Postgres  13 alpine

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by br41nslug** [comment]
I cannot reproduce this by booting a fresh instance using either `directus/directus:9.22.1` or `directus/directus:latest` tags. 
Do you have any extensions loaded that could be causing this?

**Comment by donaldrich80** [comment]
Yes, I do. Forgot about those.

I will move them to an external folder and retry.

**Comment by donaldrich80** [comment]
Without the extensions, the latest image worked fine. Thanks.

For the record, I had the editorjs and image scout extensions loaded.

**Comment by br41nslug** [comment]
Awesome :D thanks for checking. rebuilding the extension with the updated SDK should fix it 🤞
