### ISSUE TITLE
Greek letters are converted to HTML special characters in the WYSIWYG interface

### ISSUE THREAD

**Issue by Lord-KalEl** [directus/directus#16892]
### Describe the Bug

In a Greek translation, the letters are all translated as HTML special characters in the database. This not only consumes memory, but is simply not readable. Actually everything should be stored in UTF-8 ... then nobody has a problem with it.

### To Reproduce

We did a Greek translation and then used GraphQL to display the data. In the translation, the Greek letters were not readable.

### Errors Shown

None …

### What version of Directus are you using?

v9.20.4

### What version of Node.js are you using?

?

### What database are you using?

Postgres (from Docker)

### What browser are you using?

Firefox

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
Are you talking about the wysiwyg interface of data in general?

**Comment by Lord-KalEl** [comment]
Data in general (It is stored like that)

**Comment by br41nslug** [comment]
This seems to be isolated to the wysiwyg interface the other text interfaces save their data properly in UTF-8.
![image](https://user-images.githubusercontent.com/9389634/209331000-96cfc73b-327c-46be-858a-68317299d9d5.png)

**Comment by paescuj** [comment]
Might be fixed by #16062, I'll test it out when I have time 👍

**Comment by rijkvanzanten** [comment]
This is controlled through [TinyMCE's `entity_encoding` setting](https://www.tiny.cloud/docs-3x/reference/Configuration3x/Configuration3x@entity_encoding/). You can control this by adding the following to the "Options Override" option in the wysiwyg interface options:

```json
{
    "entity_encoding": "raw"
}
```

**Comment by Lord-KalEl** [comment]
Thanks …

**Comment by rijkvanzanten** [comment]
You're welcome…
