### ISSUE TITLE
Add native Supabase Storage abstraction

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#16903]
Supabase Storage is S3 'compatible', but has it's own methods and SDKs to manipulate files. Now that #16825 is merged and released, it should be trivial to create a new `@directus/storage-driver-supabase` abstraction.

**Comment by rijkvanzanten** [comment]
#15631 and #16830 contain some initial attempts to achieve this in the previous drive abstraction. We should be able to combine the efforts there to get this spun up 🙂

**Comment by SharadKumar** [comment]
[Supabase Storage v3 released](https://supabase.com/blog/storage-v3-resumable-uploads)

**Comment by MentalGear** [comment]
> [Supabase Storage v3 released](https://supabase.com/blog/storage-v3-resumable-uploads)

Yes, they are using TUS.
> "TUS is an open protocol for resumable file uploads. By leveraging an open protocol, developers can use existing libraries with Supabase Storage."
