### ISSUE TITLE
Application stops when `/server/health`

### ISSUE THREAD

**Issue by abdonrd** [directus/directus#16904]
### Describe the Bug

When we call the `/server/health` endpoint, the application stops.

With this log:

```
[18:31:36] GET /server/health 304 408ms
[18:31:36] GET /server/health 304 356ms
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'project-path/uploads/health-6IG4X'
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'project-path/uploads/health-6IG4X'
}
```

As you see, it happens after a couple of calls.

I think it's related with the `testStorage`:

https://github.com/directus/directus/blob/dc1a218c58110fc28ec58a43b817069ec72df173/api/src/services/server.ts#L289-L331

Probably related:
- https://github.com/directus/directus/pull/16825

### To Reproduce

Run a Directus application an call the `/server/health` endpoint several times.

### Errors Shown

```
[18:31:36] GET /server/health 304 408ms
[18:31:36] GET /server/health 304 356ms
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'project-path/uploads/health-6IG4X'
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'project-path/uploads/health-6IG4X'
}
```

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

Running locally

**Comment by rijkvanzanten** [comment]
@abdonrd Just to confirm, you're using the `local` storage driver?

**Comment by abdonrd** [comment]
@rijkvanzanten I imagine so. Since we don't use files in this project, we don't set any variables about it.

**Comment by freekrai** [comment]
@abdonrd @rijkvanzanten I tested with local, S3, azure, cloudinary and GCS and yeah, this is only with local, fix is being worked on.

**Comment by abdonrd** [comment]
Thanks @freekrai!

**Comment by abdonrd** [comment]
Thanks @freekrai!

I imagine that it affects us because, since we don't use storage...
By default it is configured as `local`.
