### ISSUE TITLE
UI: In tiles view, clicking a tile does not navigate to the row / record

### ISSUE THREAD

**Issue by mkleywegt** [directus/directus#1690]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests please use the [Directus FeatHub](http://feathub.com/directus/directus) to make a new request or vote for existing ones, or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues.

## Version Info
  - Directus version and branch: 6.4 @ develop
  - PHP version: 5.6
  - MySQL version: 5.7.12
  - Web server: (Ex. Apache, nginx or IIS?) nginx
  - OS name and version: Ubuntu 16.04.2

## Expected Behavior
When the view is set to tiles, clicking anywhere on a single tile should initiate navigating to the page for that single row / record.

## Actual Behavior
{void}

## Steps to Reproduce
 1. Create table with at least one field with a single file UI
 2. Create some rows
 3. Set the view options to display tiles
 4. Try clicking a tile
 2. 
 3.

**Comment by WellingGuzman** [comment]
Hey @mkleywegt, this issue was fixed by https://github.com/directus/directus/commit/74f4a13445676e0b61dea3e5a2d7201e51386fdd
