### ISSUE TITLE
Avatar / logo flashes on page changes

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#16917]
I believe it might have something to do with the fact that it tries to load from the API and inject as a data string, and the navigation causes an `update` cycle in Vue, which causes it to reinstantiate the image. 

### Discussed in https://github.com/directus/directus/discussions/16908

<div type='discussions-op-text'>

<sup>Originally posted by **ernst86913** December 24, 2022</sup>
Hi - 
currently the logo and the avatar are reloaded on every route change... which creates a bit of a "messy" experience for the user as those components are "flickering". Would it be possible to keep those 2 components stay on the screen like all other navigation bar components (e.g. the Directus Standard logo works nicely).

Thanks,
Roman </div>

**Comment by KlausMikhaelson** [comment]
Hey @rijkvanzanten , can I work on this issue ?

**Comment by br41nslug** [comment]
For sure @KlausMikhaelson very much appreciated 😄 I'll assign you the issue for now, be sure to reference this issue in your pull request

**Comment by licitdev** [comment]
Hey @KlausMikhaelson, how's the fix going? 😄

**Comment by KlausMikhaelson** [comment]
Hey @licitdev I literally forgot about it really sorry for that, will try to fix it tonight and create a pr!

**Comment by licitdev** [comment]
@KlausMikhaelson No worries! Thank you for taking up the issue. 👍

**Comment by licitdev** [comment]
@KlausMikhaelson I've unassigned you as I've just pushed #17236 which should resolve this issue. Look forward to seeing your contributions in the future~ 👍
