### ISSUE TITLE
Importing file via URL from the same server not working

### ISSUE THREAD

**Issue by peXed** [directus/directus#16915]
### Describe the Bug

I tried to migrade a V8 project to V9 and the file transfer ist not working. I always get "SERVICE_UNAVAILABLE".
The file is accessible from the internet.

I tried to import the image via the file library (add file from url), but still get the same error. I tried it with different images and completly different projects that are on the same server. It seems that images, that are hostet under the same IP can't get imported.

### To Reproduce

- Try to add a new image, hosted on the same server in the file library via URL

### Errors Shown

```
{
  "errors": [
    {
      "message": "Couldn't fetch file from url \"https://DIFFERENT-URL-BUT-SAME-SERVER/originals/8e8c345d-4c73-586c-957e-54bf1d689c61.jpg\"",
      "extensions": {
        "code": "SERVICE_UNAVAILABLE",
        "service": "external-file"
      }
    }
  ]
}
```

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18.3.0

### What database are you using?

MySQL 8.0.30

### What browser are you using?

Chrome

### How are you deploying Directus?

Node via PLESK (Managed Server)

**Comment by rijkvanzanten** [comment]
This is by design. The default value for `IMPORT_IP_DENY_LIST` is `0.0.0.0`, which blocks imports from locations that resolve to localhost. You can reconfigure that env var to explicitly allow localhost resolution for files 👍🏻
