### ISSUE TITLE
Searching items using national chars

### ISSUE THREAD

**Issue by dsivokhin** [directus/directus#1691]
## Version Info
  - Directus version and branch: 6.4 master
  - PHP version: 7.0
  - MySQL version: 5.7
  - Web server: nginx
  - OS name and version: Ubuntu 16.04 LTS

## Expected Behavior
Filtering for tables rows work with cyrrilic or another national chars

## Actual Behavior
If table have fields type 'DATE' or 'DATETIME', searhing rows using cyrrilic chars has error `Error Code: 1271. Illegal mix of collations for operation 'like'`. 

## Steps to Reproduce
 1. create table with field type DATE or DATETIME
 2. Insert some rows in table
 3. Do a search on the table using cyrillic chars or another national chars

## Info
define('DB_CHARSET', 'utf8');
collation_connection - utf8_general_ci
collation_database - utf8_unicode_ci
collation_server - utf8_general_ci

**Comment by WellingGuzman** [comment]
Hey @dsivokhin,

We are now only searching on numeric and string columns which will prevent the issue with date types.

If there's a reason to include blob or date time, we are open to discuss.

Fixed by https://github.com/directus/directus/commit/80c64fa6613f6b4f561f1b31376798577b9aeb87

**Comment by dsivokhin** [comment]
Hello @WellingGuzman,
It's work by many tables, but if table have M2O (Single file), I have this error

``Server Error
This query failed: SELECT `packages`.`id` AS `id`, `packages`.`active` AS `active`, `packages`.`name` AS `name`, `packages`.`photo` AS `photo` FROM `packages` WHERE (`packages`.`id` LIKE '%Сете%' OR `packages`.`active` LIKE '%Сете%' OR `packages`.`name` LIKE '%Сете%' OR `photo` IN (SELECT `directus_files`.`id` AS `id` FROM `directus_files` WHERE (`directus_files`.`id` LIKE '%Сете%' OR `directus_files`.`status` LIKE '%Сете%' OR `directus_files`.`name` LIKE '%Сете%' OR `directus_files`.`title` LIKE '%Сете%' OR `directus_files`.`location` LIKE '%Сете%' OR `directus_files`.`caption` LIKE '%Сете%' OR `directus_files`.`type` LIKE '%Сете%' OR `directus_files`.`charset` LIKE '%Сете%' OR `directus_files`.`tags` LIKE '%Сете%' OR `directus_files`.`width` LIKE '%Сете%' OR `directus_files`.`height` LIKE '%Сете%' OR `directus_files`.`size` LIKE '%Сете%' OR `directus_files`.`embed_id` LIKE '%Сете%' OR `directus_files`.`user` LIKE '%Сете%' OR `directus_files`.`date_uploaded` LIKE '%Сете%' OR `directus_files`.`storage_adapter` LIKE '%Сете%'))) AND `packages`.`active` IN ('1', '2') ORDER BY `id` ASC LIMIT 50 OFFSET 0`` 

because 'LIKE' search in DATETIME column `directus_files`.`date_uploaded`

**Comment by WellingGuzman** [comment]
Hey @dsivokhin,

This patch (https://github.com/directus/directus/commit/9e1d4572613f618373298121da7582cf5edf4d1c) should have fix this issue. please let us know if it worked for you too.

**Comment by dsivokhin** [comment]
Hi @WellingGuzman, thank you it works.
