### ISSUE TITLE
Data stops showing on page swap

### ISSUE THREAD

**Issue by onurbamaro** [directus/directus#16918]
### Describe the Bug

The data doesn't show on the APP after changing to another data table. 

![Animação](https://user-images.githubusercontent.com/41651403/209451433-c175a420-c3ca-4557-9544-422a76e13690.gif)

### To Reproduce

Change from a table to another inside directus app. If you change to another module (like users) and go back to data it will show at first, but after changing to another table the problem happens once again. 

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18.12.1

### What database are you using?

postgres 14

### What browser are you using?

chrome

### How are you deploying Directus?

locally without docker

**Comment by freekrai** [comment]
This is being covered in https://github.com/directus/directus/issues/16883 and a fix is in progress already
