### ISSUE TITLE
Folders in File module and disabled modules

### ISSUE THREAD

**Issue by walkwizus** [directus/directus#1692]
Hi,

I've seen this issue : #682 and I would like know if this feature are implemented because I see it on your demo but not in 6.4.4 version. There are a mention in documentation too : [https://docs.getdirectus.com/6.4.0/#File_Library](https://docs.getdirectus.com/6.4.0/#File_Library)

Other question, the three modules (Activity Log, Server Details and Version & Updates) are disabled, is it normal ?

Thanks for you reply and for your great work !

**Comment by WellingGuzman** [comment]
Hello @walkwizus,

Folders in Files was moved to http://feathub.com/directus/directus/+12 as Feature requests (wishlist), we haven't implement it yet, and we did have it on the demo, as the demo was our wishlist of 6.4, some feature like folders were opt out of the way for 6.4.0, but it will be include in a future version for 6.4.

> Other question, the three modules (Activity Log, Server Details and Version & Updates) are disabled, is it normal ?

Once again these are feature we will implement soon, we just leave it there as a sneak peek, it has been getting some confusion, maybe we should add a banner or label that says coming soon. what do you think @benhaynes?

---

As this is not an issue I will close it right away. You are always welcome to join us at our [slack channel](https://slack.getdirectus.com)

**Comment by benhaynes** [comment]
We could comment those panels out for now... but I'd rather leave them in as a reminder of what's coming soon (eg: marketplace). Once we have critical bugs resolved we can slowly start turning these features on.

**Comment by WellingGuzman** [comment]
I believe if we have a badge that says "soon" will make easier to think is not "disable" but under development.

**Comment by jleider** [comment]
I came here to say the same thing as @WellingGuzman. I was confused until I found this issue stating they were "coming soon"
