### ISSUE TITLE
Getting many errors when applying schema snapshot from CDB to Postgres

### ISSUE THREAD

**Issue by falmanna** [directus/directus#16928]
### Describe the Bug

I generated a schema from a directus instance running on CDB using the CLI, and I am trying to apply it on a postgres directus instance. So I am facing multiple errors and so far haven't got it working yet. Errors I got so far:
```
invalid input syntax for type numeric: "NULL"
invalid input syntax for type integer: "nextval('public."CompanySize_id_seq"'::REGCLASS)"
```
First one was easy to fix ad I provided a default `0` instead of the empty null value, although Null is what I need. The second error is harder to resolve as it involves id change, and I don't want to play with that.

Though I would share here before changing my schema anymore.

### To Reproduce

Create some collections and items on CDB and use decimal types with null default and auto increment ids. 
Generate a schema and try to apply it to a Postrgres instance.

### Errors Shown

Multiple:
```
invalid input syntax for type numeric: "NULL"
invalid input syntax for type integer: "nextval('public."CompanySize_id_seq"'::REGCLASS)"
```

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18.2.0

### What database are you using?

CDB v22.1.12, PG15

### What browser are you using?

Chrome

### How are you deploying Directus?

Directus locally, CDB serverless, PG neon

**Comment by falmanna** [comment]
The field in the schema
```
- collection: CompanySize
    field: id
    meta:
      collection: CompanySize
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: integer
      default_value: nextval('public."CompanySize_id_seq"'::REGCLASS)
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: true
      max_length: null
      name: id
      numeric_precision: 32
      numeric_scale: 0
      schema: public
      table: CompanySize
    type: integer
```

**Comment by azrikahar** [comment]
> invalid input syntax for type numeric: "NULL"

Can you share the schema for this decimal field like you did for the auto increment field?

> invalid input syntax for type integer: "nextval('public."CompanySize_id_seq"'::REGCLASS)"

I believe this is actually caught and fixed in the middle of #14713 (but it is not merged yet, so you will indeed still face this error), specifically this commit: https://github.com/directus/directus/pull/14713/commits/816c998291ecb1fceb7b7f867f94290896a3435f

As the commit above entails, can you try modifying CompanySize id field in the schema, and change `meta.has_auto_increment` from `false` to `true`?

**Comment by falmanna** [comment]
Schema for the other numeric field
```
- collection: Budget
    field: max
    meta:
      collection: Budget
      conditions: null
      display: raw
      display_options: null
      field: max
      group: null
      hidden: false
      interface: input
      note: null
      options:
        max: 10000000
        min: 0
      readonly: false
      required: false
      sort: null
      special: null
      translations: null
      validation:
        _and:
          - _or:
              - max:
                  _null: true
              - max:
                  _between:
                    - '0'
                    - '10000000'
      validation_message: Max rate is out of range!
      width: full
    schema:
      comment: null
      data_type: numeric
      default_value: 'NULL'
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: max
      numeric_precision: 10
      numeric_scale: 1
      schema: public
      table: Budget
    type: decimal
```

Will check the fix and report

**Comment by azrikahar** [comment]
> Schema for the other numeric field

It's really odd how it's `'NULL'` instead of the typical `null` as the default value. Did you explicitly typed `'NULL'` in the default value of that field via the Directus App (Data Studio), or is it the way it is when you didn't modify default value at all?

Another tangent thought, I'm wondering could this somehow be something to do with `knex-schema-inspector`'s cockroachdb `parseDefaultValue` instead: https://github.com/knex/knex-schema-inspector/blob/master/lib/dialects/cockroachdb.ts#L39-L50

That being said, can you try changing `'NULL'` to `null` (lowercase without quotes)?

> Will check the fix and report

Thanks! I've also just realized I typed `schema.has_auto_increment` instead of `schema.has_auto_increment` in my previous comment 🤦‍♂️ hope that wasn't too confusing.

**Comment by falmanna** [comment]
I didn't modify at all.

![Screenshot 2022-12-27 120436](https://user-images.githubusercontent.com/3227740/209641913-075d2c99-dc6d-4f8c-bcfc-dbbbf457c8fe.png)

> Another tangent thought, I'm wondering could this somehow be something to do with `knex-schema-inspector`'s cockroachdb `parseDefaultValue` instead: https://github.com/knex/knex-schema-inspector/blob/master/lib/dialects/cockroachdb.ts#L39-L50

Compared to postgres's `parseDefaultValue ` method, the CDB one is not handling the letteral `'NULL'` case while postgres is.
https://github.com/knex/knex-schema-inspector/blob/ced5a9b02d3682fee5d8d45920b425b371345740/lib/dialects/postgres.ts#L42

And yes both fixes work. 
I Still have many other occasions of these errors, so will hold this migration for now.

**Comment by azrikahar** [comment]
> Compared to postgres's parseDefaultValue  method, the CDB one is not handling the letteral 'NULL' case while postgres is.
https://github.com/knex/knex-schema-inspector/blob/ced5a9b02d3682fee5d8d45920b425b371345740/lib/dialects/postgres.ts#L42

Nice catch! Totally forgot to compare it with postgres' dialect over there. 

Looking at knex/knex-schema-inspector#117, seems like handing of string 'NULL' was added to all dialect _except_ cockroachdb, so it might be unintentional, and will need to be fixed over there.

**Comment by falmanna** [comment]
I think this part would benefit from some shared abstraction

**Comment by azrikahar** [comment]
> Looking at [knex/knex-schema-inspector#117](https://github.com/knex/knex-schema-inspector/pull/117), seems like handing of string 'NULL' was added to all dialect _except_ cockroachdb, so it might be unintentional, and will need to be fixed over there.

Since we have integrated the mentioned logic into `directus/schema` after #18014, opting to resolve this in #18048 via commit https://github.com/directus/directus/pull/18048/commits/3c9a63647c3e6aa628305c32b5ede81c454bda2e.
