### ISSUE TITLE
Issue when having a UUID as a primary key of a collection

### ISSUE THREAD

**Issue by peauc** [directus/directus#16938]
### Describe the Bug

When I have an UUID as a primary key for a collection I can enter the edit view for this item. But when I click on the second entry on the list, I get a item not found error.

### To Reproduce

https://user-images.githubusercontent.com/15132860/209726859-c79a74cf-d03d-4c84-81df-e60228425332.mp4

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

18.0

### What database are you using?

Postgres 13

### What browser are you using?

Brave

### How are you deploying Directus?

Local + Docker

**Comment by br41nslug** [comment]
I am unable to reproduce this given a table using UUID as primary key. Any console errors or failed requests you can share when this happens or what UUID specifically is causing this.

https://user-images.githubusercontent.com/9389634/209797761-8d88e2bd-1bb6-4cf6-9e10-9da5b3180672.mp4

Happy to re-open the ticket when more detailed information is available.

**Comment by peauc** [comment]
@br41nslug Hello, thank you for taking the time to reply.

[I have encountered a thread where you discussed a specific format of uuid being supported.](https://github.com/directus/directus/discussions/15535) We have an enormous dataset and changing the UUIDs is not something that is possible. 
However we found a workaround by setting the collection's ID as an `int` and autogenerating the values. Is this bugfix tracked somewhere, I can and want to contribute :).

**Comment by br41nslug** [comment]
> https://github.com/directus/directus/discussions/15535 We have an enormous dataset and changing the UUIDs is not something that is possible.

As mentioned in the discussion Directus only officially supports UUIDv4 (but v1/v5 should work too) other formats of UUIDs will fail the validation.

> However we found a workaround by setting the collection's ID as an int and autogenerating the values.

Wouldn't using "manually entered" primary key be more appropriate if you already have UUIDs that do not fit the v1/v4/v5 spec.

> Is this bugfix tracked somewhere?

Im not completely sure what bugfix you're referring to? The current one?

**Comment by peauc** [comment]
@br41nslug We have a few different UUID formats as we are depending on third parties for data.

Thank you for the workaround, it works well, I had to change the column type from `uuid` to `varchar(255)` directly in the database, I couldn't manage with Directus' UI.

I was referring to your comment, could I help ? 
<img width="998" alt="CleanShot 2023-01-03 at 16 29 46@2x" src="https://user-images.githubusercontent.com/15132860/210388573-1204434e-e80f-41d2-a46f-6e81523fb72d.png">

**Comment by br41nslug** [comment]
Aah that is current not considered a bug, well upvoting that discussion/feature request would be the way to go. It currently has one upvote and i think thats default so that does not give us the impression there is much interest for this feature in the community 😬

**Comment by peauc** [comment]
@br41nslug, do you have a link to this feature request I cannot seem to find it 😵‍💫.

**Comment by br41nslug** [comment]
https://github.com/directus/directus/discussions/15535

**Comment by peauc** [comment]
I feel stupid 😅. Alright thanks for your precious time, I'll try to contribute :)
