### ISSUE TITLE
Changing the status on an overlayed item modifies the main item status

### ISSUE THREAD

**Issue by peremp** [directus/directus#1693]
## Version Info
  - Directus version and branch: Directus Develop latest

## Steps to Reproduce
 1. Edit or create an item with some M2M column
 2. Click on "Add new item" on the M2M field.
 3. Create the item and click on "published"

## Expected Behavior
The item that I'm creating through the overlay should change its status to "published".

## Actual Behavior
The status of the item that I'm creating through the overlay is **NOT** changed.
The status of the main item that I'm creating/editing (step 1) **IS** changed (should not).

**Comment by WellingGuzman** [comment]
Hey @peremp, I was just working with this one, I just noticed couple of hours ago.

Thanks for the report!

**Comment by WellingGuzman** [comment]
This should've fixed the issue (https://github.com/directus/directus/commit/62ceaf4cff174368fc41b49bc25a57e1231d87ac) please confirm.

**Comment by peremp** [comment]
Fixed. Thx!
