### ISSUE TITLE
Not able to push multiple keys on a single Flow

### ISSUE THREAD

**Issue by GioKaaja** [directus/directus#16957]
### Describe the Bug

We developed a Flow that uses a Webhook to invoke an external API. The flow is triggered by an Event Hook based on the item. Update on a specific Collection (Action). After the Event Hook, a Condition Step will filter the events I'm interested in, which are the updates on a specific field set as TRUE (boolean). After this, a Read Data step will retrieve the data necessary for the webhook to be invoked, for the specific item updated.
The Flow works perfectly for a single update on an item inside the collection; however, when using the Batch Editing feature inside the Collection mentioned, the Event Hook recognized multiple event Keys (i.e., multiple Items) but the Read Data step stops the flow with the following error message: "sqlMessage": "Operand should contain 1 column(s)"

### To Reproduce

1. Create a Flow that is triggered by an item. Update Action and has a ReadData step 
2. Use the BatchEditing feature to modify more than 1 item at the same time
3. Analyze the Read Data if it s able to work with more than 1 item at the same time

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

18.0.0

### What database are you using?

mySQL

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by br41nslug** [comment]
The read operation is perfectly capable of dealing with multiple keys. How have you configured your operations?
A quick test gives me the expected items for both single and multiple item updates:
![image](https://user-images.githubusercontent.com/9389634/209952013-b05b9efb-c532-46d4-aa03-cb49fe8101fe.png)
![image](https://user-images.githubusercontent.com/9389634/209952060-31cf6977-9a11-401c-b99d-e31600a298e4.png)

**Comment by GioKaaja** [comment]
hi @br41nslug so it s a matter of configuration from my side - could you copy and paste how you configure the query inside the Read Data step? it will be super helpful!!! thanks

**Comment by br41nslug** [comment]
All configuration i've done is visible in the previous screenshots i think. But for completeness 
![image](https://user-images.githubusercontent.com/9389634/209953349-7a934a84-98dd-4d0c-bb34-bb701c471ded.png)
