### ISSUE TITLE
No matching version found for @directus/app@9.22.1.

### ISSUE THREAD

**Issue by sekhuat** [directus/directus#16950]
### Describe the Bug

I am trying to upgrade my DirectUs from 9.21.2 to 9.22.1 but got the "No matching version found for @directus/app@9.22.1." error when issue the `npm update` command after changing the package.json as shown below.

```
{
  "name": "api",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "directus": "9.22.1",
    "mysql": "^2.18.1",
    "web-push": "^3.5.0"
  }
}
```

### To Reproduce

With a working version of DirectUs 9.21.2 installed, edit the package.json file by changing the directus dependencies from 9.21.2 to  9.22.1.

Issue the `npm update` command.

### Errors Shown

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @directus/app@9.22.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxxxx/.npm/_logs/2022-12-29T06_35_57_113Z-debug-0.log

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

18.12.1

### What database are you using?

MySQL 8.0.30 (MySQL Community Server - GPL)

### What browser are you using?

Chrome & Safari

### How are you deploying Directus?

locally

**Comment by br41nslug** [comment]
I cannot reproduce this on my end, could this be npm cache?
![image](https://user-images.githubusercontent.com/9389634/209946199-8dd6ef81-1abb-4c84-b9c1-f89a2734c110.png)

**Comment by sekhuat** [comment]
I had tried the `npm cache clean --force` command to clear the npm cache but still not working. I even remove the package-lock.json and the node_modules folder to perform reinstallation via `npm install` but still the same error.

**Comment by sekhuat** [comment]
I just tried to perform a new installation of DirectUs using the `npm init directus-project my-project` command but still get the same error as shown below:

✖ Installing Directus
Error: npm WARN config production Use `--omit=dev` instead.
npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
npm WARN config `--include=optional` to include them.
npm WARN config
npm WARN config     Default value does install optional deps unless otherwise omitted.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @directus/app@9.22.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

My node version is v18.12.1 and npm is 8.19.2. Please help.

**Comment by sekhuat** [comment]
Finally managed to solve the issue by running the `npm doctor` command. After running the `npm doctor` command, it will show a list of suggested fixes for my npm. 

I upgraded my npm from 8.19.2 to 9.2.0 and reset the registry to the default registry https://registry.npmjs.org/ and I managed to perform the Directus update.
