### ISSUE TITLE
GraphQl sorting by nested field doesn't work

### ISSUE THREAD

**Issue by TyrionFront** [directus/directus#16951]
### Describe the Bug

During performing an attempt to fetch data sorted by a nested field using GrqphQL I just get the "INTERNAL_SERVER_ERROR" with no data in response
<img width="1129" alt="Screenshot 2022-12-29 at 11 33 29" src="https://user-images.githubusercontent.com/18406903/209932416-155490da-8aa5-4cb7-b65f-ad9194042457.png">

And what is curious that for some reason Directus randomly creates a name of inexisting table (highlighted on the screenshot):

<img width="1436" alt="Screenshot 2022-12-29 at 11 28 33" src="https://user-images.githubusercontent.com/18406903/209933255-ecc89b50-e42d-4cae-a7b1-cdc24913102b.png">

### To Reproduce

The data that is being processed has the next structure with the appropriately configured "sort" field:

<img width="868" alt="Screenshot 2022-12-29 at 11 26 12" src="https://user-images.githubusercontent.com/18406903/209932681-99b25339-1ad7-473d-a84a-9d3152889f64.png">
<img width="943" alt="Screenshot 2022-12-29 at 11 26 38" src="https://user-images.githubusercontent.com/18406903/209932683-a975dd34-a5b3-418f-93c9-4dedf55919d5.png">
<img width="960" alt="Screenshot 2022-12-29 at 11 27 32" src="https://user-images.githubusercontent.com/18406903/209932684-da80a4e8-81ef-416e-9629-216ba28ebf4b.png">

The GraphQL query is next:

`query {
  specialists (limit: -1, sort: ["-insurers_general_info.total_claims_12months"]) {
    main_category {
      category_name
    }
    full_name,
    insurers_general_info {
      total_claims_12months,
      avg_claims_pm
    }
  }
}`

### Errors Shown

<img width="1436" alt="Screenshot 2022-12-29 at 11 28 33" src="https://user-images.githubusercontent.com/18406903/209933402-10d5b6e4-d116-40d4-a45e-4ce696b329e2.png">
<img width="1129" alt="Screenshot 2022-12-29 at 11 33 29" src="https://user-images.githubusercontent.com/18406903/209933404-1cc13502-d2a5-4564-8fef-fd98ca0386f8.png">

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

v16.15.0

### What database are you using?

PostgreSQL 14.5 on aarch64-apple-darwin20.6.0

### What browser are you using?

Brave

### How are you deploying Directus?

Docker

**Comment by licitdev** [comment]
Support for nested O2M sorting is added via https://github.com/directus/directus/pull/14798 in `9.22.0`. Kindly update to the latest version.

**Comment by TyrionFront** [comment]
> Support for nested O2M sorting is added via #14798 in `9.22.0`. Kindly update to the latest version.

Kindly appreciated and sorry 4 irrelevant additional disturbance.
