### ISSUE TITLE
Select element issues on Firefox

### ISSUE THREAD

**Issue by joshas** [directus/directus#1695]
## Version Info
  - Directus version and branch: master fd508cd8d11c7bb0169ed446862b5ff447d6f506
  - PHP version: 5.6.18
  - MySQL version: 5.7.11
  - Web server: Apache
  - OS name and version: Windows 7

## Expected Behavior
Chromium 59
![select-chromium-59](https://user-images.githubusercontent.com/79141/28332664-465c0280-6bfe-11e7-81f0-9f65d48e98be.png)

## Actual Behavior
Firefox 54
Note that select is much higher and text inside has uppercase styling (inherited from label).
![select-firefox-54](https://user-images.githubusercontent.com/79141/28332678-4e7c35d4-6bfe-11e7-8ef4-e5e015f73d6d.png)

## Steps to Reproduce
 1. Start Directus installer on Firefox

**Comment by rijkvanzanten** [comment]
Good catch!

**Comment by rijkvanzanten** [comment]
This has been fixed in https://github.com/directus/directus/commit/55cce00ec101d1cbabb38149401ac77998ad2f37 and https://github.com/directus/directus/commit/9d4ed0bedb9aed7d72845a944b29698863646101 and will be added in master soon.
