### ISSUE TITLE
Intallation check - mod_rewrite detect fail

### ISSUE THREAD

**Issue by joshas** [directus/directus#1696]
## Version Info
  - Directus version and branch: master fd508cd8d11c7bb0169ed446862b5ff447d6f506
  - PHP version: 5.6.18
  - MySQL version: 5.7.11
  - Web server: Apache
  - OS name and version: Windows 7

## Expected Behavior
Pre-installation check displays "Mod_Rewrite Enabled: Yes"

## Actual Behavior
Pre-installation check displays "Mod_Rewrite Enabled: No"

## Steps to Reproduce
Start Directus installation and reach final step. Directus is installed in subdirectory.
Issue was fixed(?) in 6.3 #1349 , but some code probably was rewritten and now installation check is failing again.
Installation actually works and /api/1/ping route is accessible after installation. During installation that route returns 404 error.

**Comment by WellingGuzman** [comment]
Fixed by https://github.com/directus/directus/commit/2a8381ac674a29456fc579e038d722c72f1e59aa. (`develop` branch)

It will be merge at most at the end of the week to master.
