### ISSUE TITLE
Collection records not displaying

### ISSUE THREAD

**Issue by supermx1** [directus/directus#16976]
### Describe the Bug

https://user-images.githubusercontent.com/9326922/210152805-2ee289d2-4668-487b-8cda-733089225b90.mp4

This is a weird bug that occurs on one of my Directus instances. It started acting like that after I updated from v9.21.1 to v9.22.1. To load records I will have to refresh my browser. The API works as expected, but the admin panel is acting weird.

### To Reproduce

Can't say honestly. It is weird.

### Errors Shown

None

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

Node v19.3.0

### What database are you using?

10.3.37-MariaDB

### What browser are you using?

Brave, Chrome, Safari

### How are you deploying Directus?

Azure, Locally

**Comment by jotatoledo** [comment]
Dup of https://github.com/directus/directus/issues/16883

**Comment by lpadula** [comment]
Same ploblem here on fresh install via docker-compose.

**Comment by freekrai** [comment]
Closing this as it’s a duplicate issue that has been merged and just waiting for next release.
