### ISSUE TITLE
WYSIWYG formatting controls cover editable text

### ISSUE THREAD

**Issue by joshas** [directus/directus#1697]
## Version Info
  - Directus version and branch: master fd508cd8d11c7bb0169ed446862b5ff447d6f506
  - PHP version: 5.6.18
  - MySQL version: 5.7.11
  - Web server: Apache
  - OS name and version: Windows 7

## Expected Behavior
WYSIWYG formatting controls hover above text.

## Actual Behavior
WYSIWYG formatting controls cover editable text, if that text is on first line of textarea.

## Steps to Reproduce
 1. Create WYSIWYG (not full) input.
 2. Write/paste some text.
 3. Try formatting ant text that is on first line.

## Logs or Screenshots
![wysiwyg](https://user-images.githubusercontent.com/79141/28336113-74480468-6c09-11e7-8755-0cf9a17c61ea.png)

**Comment by rijkvanzanten** [comment]
Hi @joshas! This has been fixed in commit https://github.com/directus/directus/commit/c3e74f4d7ef1d5c537f27badd495b390f6212a71 which will be merged into master soon 👍
