### ISSUE TITLE
Settings Singleton Upsert - ID NULL ERROR

### ISSUE THREAD

**Issue by ernst86913** [directus/directus#16972]
### Describe the Bug

When Directus bootstraps a clean DB installation, die ID of the settings service is not set. This leads to issues when one tries to do a settings singleton upsert change to the settings.

Workaround:  go into Admin Frontend and edit the project settings record... save it... afterwards the ID is set.

### To Reproduce

Clean Directus Installation - and then do upsert on Settings Singleton record.

### Errors Shown

[11:24:15.938] INFO:
    id: null
    project_name: "Directus"
    auth_login_attempts: 25
    storage_asset_transform: "all"
    default_language: "en-US"
[11:24:15.971] ERROR: Value for field "id" can't be null.
    err: {
      "type": "NotNullViolationException",
      "message": "Value for field \"id\" can't be null.",
      "stack":
          Error: Value for field "id" can't be null.
              at notNullViolation (/directus/node_modules/directus/dist/exceptions/database/dialects/postgres.js:87:12)
              at extractError (/directus/node_modules/directus/dist/exceptions/database/dialects/postgres.js:27:20)
              at translateDatabaseError (/directus/node_modules/directus/dist/exceptions/database/translate.js:55:56)
              at /directus/node_modules/directus/dist/services/items.js:110:68
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      "status": 400,
      "code": "NOT_NULL_VIOLATION",
      "extensions": {
        "collection": "directus_settings",
        "field": "id"
      }
    }

### What version of Directus are you using?

latest Docker image 9.22.1

### What version of Node.js are you using?

?

### What database are you using?

Postgres 15

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by br41nslug** [comment]
I've tried using the `PATCH /settings` endpoint (which uses the upsert) and using a custom extension, for both the upsert worked without error.
EDIT: I was able to reproduce it when adding the `id: null` to the payload which is not a valid value. Removing the ID from your payload should fix the problem.

**Comment by ernst86913** [comment]
Thanks - removing the ID did the job :)On 02.01.2023, at 10:28, Brainslug ***@***.***> wrote:﻿
I've tried using the PATCH /settings endpoint (which uses the upsert) and using a custom extension, for both the upsert worked without error.
EDIT: I was able to reproduce it when adding the id: null to the payload which is not a valid value. Removing the ID from your payload should fix the problem.
