### ISSUE TITLE
GraphQL - Server Info Endpoint Doesn't Work, Instead Server_Health Query returns Server Info

### ISSUE THREAD

**Issue by balabellam** [directus/directus#16975]
### Describe the Bug

**Below Returns Null:**

```
curl --location --request POST 'http://localhost/graphql/system' --header 'Content-Type: application/json' --data-raw '{"query":"query {\n\t**server_info** {\n\t\t**project_name**\n\t}\n}\n","variables":{}}'
```

**Below Returns Server Info Instead of Server Health:**
`curl --location --request POST 'http://localhost/graphql/system' --header 'Content-Type: application/json' --data-raw '{"query":"query {\n\t**server_health**\n}","variables":{}}'`

```json
{
    "data": {
        "**server_health**": {
            "**project**": {
                "project_name": "",
                "project_descriptor": "",
                "project_logo": "",
                "project_color": "",
                "default_language": "",
                "public_foreground": null,
                "public_background": null,
                "public_note": "",
                "custom_css": ""
            }
        }
    }
}
```

### To Reproduce

Run GraphQL request using below cURL,
`curl --location --request POST 'http://localhost/graphql/system' --header 'Content-Type: application/json' --data-raw '{"query":"query {\n\t**server_info** {\n\t\t**project_name**\n\t}\n}\n","variables":{}}'`

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

16.16.0

### What database are you using?

Postgres 13

### What browser are you using?

Safari

### How are you deploying Directus?

Running Locally

**Comment by br41nslug** [comment]
I suspect this may be related to https://github.com/directus/directus/issues/16904 in some fashion.
