### ISSUE TITLE
Directus 9.22.1 Amazon S3 403 assets

### ISSUE THREAD

**Issue by florianbepunkt** [directus/directus#16985]
### Describe the Bug

After upgrading from 9.21 assets are showing a 403 error. I can successfully add new images and view them, but all images that have been uploaded before the update, are not shown. Accessing them gives the following error (from the browser's network inspection tab):

```json
[
    {
        "message": "You don't have permission to access this.",
        "extensions": {
            "code": "FORBIDDEN"
        }
    }
]
```

I believe this is similar to https://github.com/directus/directus/issues/16876 however I am on 9.22.1 and the issue persists.

Storage config

```
STORAGE_LOCATIONS=s3
STORAGE_S3_BUCKET=OMITTED
STORAGE_S3_DRIVER=s3
STORAGE_S3_KEY=OMITTED
STORAGE_S3_REGION=eu-central-1
STORAGE_S3_ROOT=/
STORAGE_S3_SECRET=OMITTED
```

### To Reproduce

Not sure.

1. You would need to use an old version of the Directus docker image with the above s3 configuration (with your own set of credentials). I am using Elastic Beanstalk
2. Then upload some files
3. Upgrade docker image to current version

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18

### What database are you using?

Cockroach DB Serverless

### What browser are you using?

Chrome

### How are you deploying Directus?

Elastic Beanstalk (Docker Image)

**Comment by crebuh** [comment]
I've a similar issue after upgrading to 9.22.1 first I also got the 403. Then I restarted the docker container and now I even get this error message. Which is even more weird, because I did not touch the storage configuration.

`[07:55:02.980] ERROR: Location "amazon" doesn't exist.
    err: {
      "type": "Error",
      "message": "Location \"amazon\" doesn't exist.",
      "stack":
          Error: Location "amazon" doesn't exist.
              at StorageManager.location (file:///directus/node_modules/@directus/storage/dist/index.js:18:19)
              at AssetsService.getAsset (/directus/node_modules/directus/dist/services/assets.js:75:38)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async /directus/node_modules/directus/dist/controllers/assets.js:125:36
    }`

**Comment by hamza-zafar-319** [comment]
I have the same issue with 9.22.0 and 9.22.1. I get 403s on already existing assets, but post-update uploaded assets can be accessed just fine. Everything goes back to normal when I roll back the update; then, I can access everything. 

### To Reproduce
- Update Directus 9.21.2 to 9.22.1.
- Try to access any pre-update asset

Even the 'Project Logo' uploaded for the App does not load.

### Errors Shown
HTTP 403 error. 

### What version of Directus are you using?
9.22.1

### What version of Node.js are you using?
18

### What database are you using?
MySQL 8.0.31

### What browser are you using?
Chrome / Firefox

### How are you deploying Directus?
On Ubuntu 22 LTS with PM2 (Production) and Windows 11 (Dev Env)

### Temp Fix
Rollback the update by using `npm install directus@9.21.2`

**Comment by cs1m0n** [comment]
I have the same problem after updating to Directus 9.22.1 using Amazon S3.

**Comment by crebuh** [comment]
Downgrading to 9.21.2 is the current workaround for me.

**Comment by cs1m0n** [comment]
Sure it is!
Another finding is that the files which were uploaded while on Directus 9.22.1 are still not accessible even after downgrading to 9.21.2, returning the same 403 error code.

**Comment by rijkvanzanten** [comment]
@crebuh / @hamza-zafar-319 / @cs1m0n was that using a similar / the same environment variable set as the original post? I noticed that's missing "endpoint", so trying to figure out if that's the offender

**Comment by hamza-zafar-319** [comment]
@rijkvanzanten I'm not sure how I could match my environment variables with the ones in the [original post](https://github.com/directus/directus/issues/16876) because GCS uses a JSON file for its setup. 

My Env file has the following:
```
STORAGE_LOCATIONS="gcs"
STORAGE_GCS_DRIVER="gcs"
STORAGE_GCS_ROOT="/beta"
STORAGE_GCS_KEY_FILENAME="./key_file.json"
STORAGE_GCS_BUCKET=xyz_storage
```
This is what the key_file.json looks like; it was pulled directly from GCP. I redacted all the sensitive stuff
```
{
  "type": "service_account",
  "project_id": "redacted_project_id",
  "private_key_id": "redacted_private_key_id,
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQI....redacted..nZXqk=\n-----END PRIVATE KEY-----\n",
  "client_email": "redacted@redacted.iam.gserviceaccount.com",
  "client_id": "redacted_client_id",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/redacted%40redacted.iam.gserviceaccount.com"
}
```



Ref:
[Directus Docs on setting up GCS ](https://docs.directus.io/self-hosted/config-options.html#google-cloud-storage-gcs)

**Comment by rijkvanzanten** [comment]
Ah @hamza-zafar-319 mind opening a new issue then? This one is about S3 specifically, which will have a different root cause (even though the symptoms are similar) 🙂

**Comment by florianbepunkt** [comment]
@rijkvanzanten Endpoint has a default value, so it does not need to be specified, or has that changed? https://docs.directus.io/self-hosted/config-options.html#s3-s3

**Comment by rijkvanzanten** [comment]
@florianbepunkt That should still be the case, just trying to see if that's a common cause of this problem across everybody who ran into this issue 🙂

**Comment by hamza-zafar-319** [comment]
> Ah @hamza-zafar-319 mind opening a new issue then? This one is about S3 specifically, which will have a different root cause (even though the symptoms are similar) 🙂

Opened a new issue: https://github.com/directus/directus/issues/17022

**Comment by joselcvarela** [comment]
I have experienced this myself and I believe this is because the S3 driver is requiring `secret` and `key` as environment variable.
Although, previous versions didn't require it.

Can you all tell if are you passing secret and key as environment variable?

I have opened this PR that should solve this:
https://github.com/directus/directus/pull/16942

**Comment by florianbepunkt** [comment]
@joselcvarela I posted my config above where key and secret are defined - still the problem exists.

**Comment by cs1m0n** [comment]
Lol, I'm very sorry, I'm actually using GCS.

**Comment by MichaelFBA** [comment]
Our STORAGE env variables if it helps
```
STORAGE_LOCATIONS=s3
STORAGE_S3_BUCKET=OMITTED
STORAGE_S3_DRIVER=s3
STORAGE_S3_REGION=eu-central-1
STORAGE_S3_ROOT=OMITTED

```

**Comment by florianbepunkt** [comment]
@rijkvanzanten This issue still exists with Directus 9.22.3

**Comment by florianbepunkt** [comment]
I believe this is due to the storage root is set to default to "/"... in my s3 bucket, before updating to `9.22.1 ` all files were uploaded to the bucket root, e. g. `s3://my-nice-bucket/file1.jpg`. After the update all new files are uploaded to `s3://my-nice-bucket//file1.jpg`. Please note the extra trailing slash.

Since s3 doesn't really know the concept of folders, it creates this:
![Bildschirmfoto 2023-01-12 um 11 16 01](https://user-images.githubusercontent.com/8314202/212040322-71cdd495-39e5-40af-a329-0c3dbe06c51e.png)

All newly uploaded files land in this "/" folder, while my old files are outside of it. Directus is looking for my old files in the wrong directory. So the 403 in reality is a 404 (but S3 gives 403 for non-existing files).

**Comment by u12206050** [comment]
I've just updated to 9.22.4 and this is still an issue. I am only able to view one set of files under a folder called public, but not of the other files. I simply get Permission Denied.

**Comment by bennyzen** [comment]
Just tried to update to the latest 9.23.1 (docker) and the issue is still present. All files from S3 still yield a 403. I don't think this is fixed.

**Comment by syahzuan** [comment]
Following. Having the same issue.

**Comment by bennyzen** [comment]
Just tried to update to v10.1.1 and this issue still seems to persist. Downgrading again. I'm stuck on v9.21.2.

Am I the only one still experiencing this?

**Comment by florianbepunkt** [comment]
Does this help?

> I believe this is due to the storage root is set to default to "/"... in my s3 bucket, before updating to `9.22.1 ` all files were uploaded to the bucket root, e. g. `s3://my-nice-bucket/file1.jpg`. After the update all new files are uploaded to `s3://my-nice-bucket//file1.jpg`. Please note the extra trailing slash.
> 
> 
> 
> Since s3 doesn't really know the concept of folders, it creates this:
> 
> ![Bildschirmfoto 2023-01-12 um 11 16 01](https://user-images.githubusercontent.com/8314202/212040322-71cdd495-39e5-40af-a329-0c3dbe06c51e.png)
> 
> 
> 
> All newly uploaded files land in this "/" folder, while my old files are outside of it. Directus is looking for my old files in the wrong directory. So the 403 in reality is a 404 (but S3 gives 403 for non-existing files). 
> 
> 
> 
> 
> 
> **UPDATE**
> 
> If anyone else encounters this bug:
> 
> 
> 
> 1. In your directus config, specifiy a value for `STORAGE_S3_ROOT` so it does not default to `/`, e. g. `/data`.
> 
> 2. In your S3 bucket: Move all files from the root level to the prefix specified in step 1.

**Comment by bennyzen** [comment]
@florianbepunkt I just followed your instructions to the point and I still get 403s for all files stored in S3.

**Comment by bennyzen** [comment]
Update: No need to prepend some kind of path or move all objects into a virtual subfolder. 

This is my new configuration and it solved the issue with newer Directus versions:
```yml
      STORAGE_LOCATIONS: S3
      STORAGE_S3_DRIVER: s3
      STORAGE_S3_ROOT: "/"
      STORAGE_S3_KEY: "V470......81E"
      STORAGE_S3_SECRET: "Nu......ccUkJ"
      STORAGE_S3_BUCKET: "somebucket"
      STORAGE_S3_REGION: "someregion-unused"
      STORAGE_S3_ENDPOINT: "https://s3.example.org"
      STORAGE_S3_FORCE_PATH_STYLE: "true"
```

Maybe this helps someone.
