### ISSUE TITLE
GraphQL requests

### ISSUE THREAD

**Issue by TyrionFront** [directus/directus#16996]
### Describe the Bug

By the server logs it looks like a lot of more or less big GraphQl queries make server to fall due to "heap out of memory"(c)

<img width="1436" alt="Screenshot 2023-01-03 at 10 56 41" src="https://user-images.githubusercontent.com/18406903/210327245-28890b87-1c11-48a2-9087-5afa0df25ec0.png">
<img width="1135" alt="Screenshot 2023-01-03 at 10 57 21" src="https://user-images.githubusercontent.com/18406903/210327248-e354af0e-7eec-4cb2-813e-498f12a01b9b.png">
<img width="1073" alt="Screenshot 2023-01-03 at 10 57 36" src="https://user-images.githubusercontent.com/18406903/210327253-3a7215e9-705d-4da6-ad97-05f27c9cc547.png">
<img width="1440" alt="Screenshot 2023-01-03 at 10 58 12" src="https://user-images.githubusercontent.com/18406903/210327254-06313e1f-f184-4b7d-a42e-1b4490a6ed4c.png">
<img width="1440" alt="Screenshot 2023-01-03 at 10 48 48" src="https://user-images.githubusercontent.com/18406903/210327243-4a252a36-e5df-4491-8dea-93360ba03e74.png">

### To Reproduce

Just usual request to Directus GraphQL. The only thing I must say is that there's no rate limit yet for such requests. Could it be the potential reason of the issue ?

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

v16.15.0

### What database are you using?

PostgreSQL 14.5 on aarch64-apple-darwin20.6.0

### What browser are you using?

Brave

### How are you deploying Directus?

Docker

**Comment by br41nslug** [comment]
> The only thing I must say is that there's no rate limit yet for such requests. Could it be the potential reason of the issue ?

Judging from the logs i'd say yes, it looks like you're firing off a (possibly infinite) loop of requests within milliseconds effectively DDoSing your directus instance.

**Comment by br41nslug** [comment]
Is it one specific request that is crashing the instance or is it just stacking up long requests till it hits the resources limit? Happy to re-open the issue with more information available

**Comment by TyrionFront** [comment]
> Is it one specific request that is crashing the instance or is it just stacking up long requests till it hits the resources limit? Happy to re-open the issue with more information available

With a big delay but I reply anyway: it was all about previously mentioned improvised DDoS and lack of RAM on the server. TXS again for helping to clarify the issue.
