### ISSUE TITLE
Many to Many Input not sorting properly

### ISSUE THREAD

**Issue by aaronaustin** [directus/directus#1700]
## Version Info
  - Directus 6.4.0
  - PHP version: 7.0.15
  - MySQL version: 5.6.35
  - Web server: Apache
  - OS name and version: Running via MAMP 4.1.1 on OSX

## Expected Behavior
When sorting items in Many to Many input, items should reorder and save.  I would expect only the chosen items in the M2M field to update sort values in the table. 

## Actual Behavior
Sorting items in Many to Many input results in both items disappearing from page.  It looks as if both sort values in the junction table are set to 0. On save, the following error is produced: 

> This query failed: UPDATE `mailings_junc` SET `mailing_id` = '5', `post_id` = '2', `id` = '17', `sort` = '0', `null` = '1' WHERE `id` = '17'

## Steps to Reproduce
 1. Create M2M input, junction table, etc.
 2. Make sure to enable sorting on junction table.
 3. Add more than one item to M2M input and sort.

## Logs or Screenshots
<img width="1331" alt="screen shot 2017-07-19 at 10 37 19 am" src="https://user-images.githubusercontent.com/9779077/28373348-18f4e8e4-6c70-11e7-9694-cdd0fa4a6a81.png">

**Comment by WellingGuzman** [comment]
Hey @aaronaustin, I haven't any luck reproducing this issue, would you care to provide a schema that I can use to reproduce this issue?

**Comment by aaronaustin** [comment]
Thanks for looking at this.  Maybe I'm just overlooking something important.  Here's the sql for these three tables: Posts, Mailings, and Mailings_junc.  The Mailings table has the M2M field where you can choose from the Posts table.

[many_to_many.sql.zip](https://github.com/directus/directus/files/1163186/many_to_many.sql.zip)

**Comment by WellingGuzman** [comment]
Thanks for the schemas. Can you please share these tables and tables' columns information in `directus_tables` (if any) and `directus_columns`?

**Comment by aaronaustin** [comment]
Sorry about that.  Here you go...
[many_to_many_v2.sql.zip](https://github.com/directus/directus/files/1163198/many_to_many_v2.sql.zip)

**Comment by WellingGuzman** [comment]
Thanks @aaronaustin, testing now!

**Comment by WellingGuzman** [comment]
Hey @aaronaustin, this commit (https://github.com/directus/directus/commit/645ed69dd61f4401fc503defb42a1430085c4062) should've fixed the issue, please confirm this is working as expected to you too. 

Also nice looking form you got on those tables :)

**Comment by aaronaustin** [comment]
@WellingGuzman , thanks! That was fast.  It's working great now.

**Comment by WellingGuzman** [comment]
Awesome, glad to hear!

**Comment by treechime** [comment]
Hey @WellingGuzman I'm getting this same error now on v6.4.6 where it's trying to UPDATE on column null and therefore breaking

```
Next exception 'RuntimeException' with message 'This query failed: UPDATE `playlist_slides` SET `playlist` = '1', `slide` = '1', `id` = '1', `sort` = '0', `null` = '1' WHERE `id` = '1'' in /directus_directory/api/core/Directus/Database/TableGateway/BaseTableGateway.php:837
Stack trace:
#0 /directus_directory/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(361): Directus\Database\TableGateway\BaseTableGateway->executeUpdate(Object(Zend\Db\Sql\Update))
#1 /directus_directory/api/core/Directus/Database/TableGateway/BaseTableGateway.php(388): Zend\Db\TableGateway\AbstractTableGateway->updateWith(Object(Zend\Db\Sql\Update))
#2 /directus_directory/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(615): Directus\Database\TableGateway\BaseTableGateway->addOrUpdateRecordByArray(Array, 'playlist_slides')
#3 /directus_directory/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(190): Directus\Database\TableGateway\RelationalTableGateway->addOrUpdateToManyRelationships(Object(Directus\Database\Object\Table), Array, Array, false, Array)
#4 /directus_directory/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(77): Directus\Database\TableGateway\RelationalTableGateway->manageRecordUpdate('playlists', Array, 1)
#5 /directus_directory/api/routes/A1/Entries.php(202): Directus\Database\TableGateway\RelationalTableGateway->updateRecord(Array, 1)
#6 [internal function]: Directus\API\Routes\A1\Entries->row('playlists', '1')
#7 /directus_directory/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Array, Array)
#8 /directus_directory/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#9 /directus_directory/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#10 /directus_directory/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#11 /directus_directory/api/core/Directus/Slim/CorsMiddleware.php(19): Slim\Middleware\MethodOverride->call()
#12 /directus_directory/api/core/Directus/Slim/HttpCacheMiddleware.php(18): Directus\Slim\CorsMiddleware->call()
#13 /directus_directory/api/core/Directus/Slim/ResponseCacheMiddleware.php(37): Directus\Slim\HttpCacheMiddleware->call()
#14 /directus_directory/vendor/slim/slim/Slim/Slim.php(1302): Directus\Slim\ResponseCacheMiddleware->call()
#15 /directus_directory/api/core/Directus/Application/Application.php(103): Slim\Slim->run()
#16 /directus_directory/api/api.php(533): Directus\Application\Application->run()
#17 {main}
```

[Dump20180221.zip](https://github.com/directus/directus/files/1742763/Dump20180221.zip)

Any ideas?
