### ISSUE TITLE
GraphQL schema and actual payload required mismatch for many-to-many relationships

### ISSUE THREAD

**Issue by LeBenLeBen** [directus/directus#17006]
### Describe the Bug

Considering the following collections relation:

![image](https://user-images.githubusercontent.com/793344/210398987-49434dd5-bf61-4a4d-8aa0-276d7752912d.png)

It generates the following GraphQL schema (simplified):

```gql
type Mutation {
  create_recipes_item(data: create_recipes_input!): recipes
}

input create_recipes_input {
  id: ID
  tags: [create_recipes_tags_input]
}

input create_recipes_tags_input {
  id: ID
  recipes_id: create_recipes_input
  tags_id: create_tags_input
}

input create_tags_input {
  id: ID
  title: String
  slug: String
  recipes: [create_recipes_tags_input]
}
```

Which implies that to assign tags to a recipe when creating it, a mutation of the following should be used:

```gql
mutation createRecipe($data: create_recipes_input!) {
  create_recipes_item(data: $data) {
    id
  }
}
```

Where the payload is:

```json
{
  "data": {
    "tags": [{
      "tags_id": {
        "id": "1"
      }
    }]
  }
}
```

Notice how `tags_id` is an Object and its `id` is a String.

This payload triggers the following error:

> Variable "$data" got invalid value "1" at "data.tags[0].tags_id"; Int cannot represent non-integer value: "1"

Changing `"1"` for `1` isn’t enough here, the payload that is expected for the request to succeed is the following:

```json
{
  "data": {
    "tags": [{
      "tags_id": 1
    }]
  }
}
```

But this does not comply with the GraphQL schema 😅

I’m guessing `create_recipes_tags_input` should be adapted to something like this:

```gql
input create_recipes_tags_input {
  id: ID
  recipes_id: Int
  tags_id: Int
}
```

But if you allow me to add my personal opinion here, I find it weird that Integers are required here, whereas everywhere else IDs are strings. As a user, I would appreciate it to be consistent.

### To Reproduce

1. Import the following snapshot in a blank Directus project using the CLI:

[snapshot.yaml.zip](https://github.com/directus/directus/files/10338309/snapshot.yaml.zip)

2. Create a tag in the panel, with id `1` (or replace the ID in the request below).

3. Ensure you have the right to create recipes/recipes_tags/tags with your user

4. Replace `TOKEN` with a valid access token (and eventually the target url `http://localhost:8055`) in the request below

```bash
curl 'http://localhost:8055/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'Origin: altair://-' -H 'Authorization: Bearer TOKEN' --data-binary '{"query":"mutation createRecipe($data: create_recipes_input!) {\n  create_recipes_item(data: $data) {\n    id\n  }\n}","variables":{"data":{"tags":[{"tags_id":{"id":"1"}}]}}}' --compressed
```

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18.12.1

### What database are you using?

Postgres 13

### What browser are you using?

Firefox 108

### How are you deploying Directus?

Local Docker using official Directus image

**Comment by rijkvanzanten** [comment]
Seeing that GraphQL doesn't support union input types, we have to choose between requiring the primary key (as `ID`), or require a partial nested object of the item to be provided (as `create_tags_input` in this case). Seeing that Directus supports nested creates/updates, the latter was chosen as the way forwards, as that allows the full feature set to be used. That does mean that you are required to pass an object that matches the type of the related item, like:

```json
{
  "tags": [
    {
      "tags_id": {
        "id": 1
      }
    }
  ]
}
```

That in turn also allows new tags to be created dynamically by omitting the ID:

```json
{
  "tags": [
    {
      "tags_id": {
        "name": "My New Tag",
        "color": "#6644ff"
      }
    }
  ]
}
```

**Comment by LeBenLeBen** [comment]
@rijkvanzanten I was confused by your answer at first because this is exactly the problem I have, it didn’t accept an object, only an Integer. However earlier today I got similar weird errors and finally tracked them down to permissions.

So I decided to allow "create" permissions on the Tags collection and now it works like expected. This is confusing to me, no tags is created here so I don’t understand why these permissions are necessary. I actually don’t want to give users the ability to create new tags. The error message is also confusing to me and the fact it changes the expected schema is even weirder.

I will probably open a separate issue with illustrated examples of missing permissions throwing unrelated errors to see how this can be improved.

Thank you for your help!

**Comment by MarkusElmer** [comment]
Any news on this?
@LeBenLeBen Have you created a new Issue?

I ran into the same problem.
The GraphQL-Endpoint reacts different depending on the Permission set.

We have an Object called Entry and apply different Categories to it over a many-to-many relationship.

If the User has Create Permissions on the Related Item (Category in this case) the following GraphQL will work:
`"categories":[
	{
		"category_id": {"id": "1"}, 
		"entry_id": {"id": "+"}
	}
]
`
If the User has no Create Permissions on the Related Item (Category) the following GraphQL will work:
`"categories":[
	{
		"category_id": 1, 
		"entry_id": {"id": "+"}
	}
]
`
But if we change to the second Implementation the GraphQL will fail for Users with create Permission:
`Variable \"$categories\" of type \"[Int]\" used in position expecting type \"[create_entry_category_input]`
So we don't have a solution that works with both non-create and create permission Users.

**Comment by LeBenLeBen** [comment]
@MarkusElmer No I didn’t create another issue. You might find interesting information in #7237 though.
