### ISSUE TITLE
Delete record bug

### ISSUE THREAD

**Issue by jimhuds** [directus/directus#17004]
### Describe the Bug

No records are displayed after a field is deleted (see below for more info).

### To Reproduce

If I create a field and then sort by it in the content tab, and then delete that field, Directus will return no records, and in the logs there will be the error "Error: ER_BAD_FIELD_ERROR: Unknown column".

It looks like the sorting entry doesn't delete when a field is deleted, so the SQL query still tries to sort by the deleted field and then returns the error.

Using latest version of Directus and MariaDB.

Thanks

### Errors Shown

"Error: ER_BAD_FIELD_ERROR: Unknown column"

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18

### What database are you using?

MariaDB 10.9.4

### What browser are you using?

Chrome

### How are you deploying Directus?

NPM/PM2

**Comment by rijkvanzanten** [comment]
This should throw an error message allowing the user to reset the preset 🤔
