### ISSUE TITLE
Javascript error in Firefox

### ISSUE THREAD

**Issue by lehha** [directus/directus#1701]
## Version Info
  - Directus version and branch: 6.4.0
  - PHP version: 5.6.25
  - MySQL version: 5.1.73
  - Web server: Apache + nginx
  - OS name and version: centos 6.9

## Expected Behavior
Normal work ))

## Actual Behavior
After installing and login into admin, got JavaScript Error in Browser:

Error: TypeError: depth0 is undefined
File: http://hostname/assets/js/directus.min.js?bust=tks4t49e1l3io3hofkl2v3gbs3 line 1 > Function
Line:26

## Steps to Reproduce
 1. Install from directus-build-6.4.0-20170710010648.tar.gz
 2. Login
 3. Got this error

## Logs or Screenshots
<img width="606" alt="screenshot" src="https://user-images.githubusercontent.com/4051362/28378319-6f0aa8e8-6cb8-11e7-8ad1-e03471b9cb4a.PNG">

**Comment by WellingGuzman** [comment]
Hey @lehha, I've not being able to reproduce this issue, can you share more output from the server on dev tools mainly the `.html` files, it seems one probably be corrupted.

What hosting service are you using? What's the server stack + extension or module installed. any security or cache installed?

**Comment by WellingGuzman** [comment]
Hey @lehha, which version of Firefox are you using on what OS?

**Comment by benhaynes** [comment]
It's been a few weeks and we are still unable to reproduce this issue. If anyone encounters it, please send us your server details, commit hash, and exact steps to reproduce.

**Comment by diegogurpegui** [comment]
Hey @benhaynes ,
I just found the exact same problem in my environment. Same steps for reproducing and same javascript stack (based on the screenshot provided by @lehha ).

I have the latest version so far:
Revision: 42ce2f23863da0073a59b0e6878d8cf65472e773
Author: Welling Guzman
Date: 2017-08-23 04:03:43

Server:
64bit Amazon Linux 2016.09 v2.3.3 running PHP 7.0

Browser:
55.0.2 (32-bit)

This error does **not** happen in Chrome.

**Comment by benhaynes** [comment]
Very interesting @diegogurpegui – is your full schema private or would you be able to share it with our developers via Slack? We haven't been able to replicate this issue as of yet so anything would help.

Also, was this a fresh install, or have you upgraded/migrated from an existing version?

**Comment by diegogurpegui** [comment]
I can't share data but I would be able to share schema (structure) if you want.

It was a fresh install. Actually, it happened first when we upgraded from a 6.3.* version. Then we did a fresh install just in case (because we had several other problems) but this specific error continued.

**Comment by rijkvanzanten** [comment]
It seems like this particular error (`depth0 is undefined`) is a Handlebars error which is thrown when it is passed invalid JSON (https://stackoverflow.com/questions/12704697/handlebars-what-is-depth0-is-undefined#comment25584307_12704697).

As it uses the same data across browsers, this doesn't really explain why this happens only in Firefox.

**Comment by benhaynes** [comment]
Thanks @diegogurpegui – a schema structure would be great! @rijkvanzanten – any ideas on how we can replicate/solve this?

**Comment by WellingGuzman** [comment]
@diegogurpegui, does your server has cache/minifier/security layer modifying the html served by directus?

I will actually going to change `.html` to `.hbs`, what do you all think? this will prevent all these _possible_ issues.

**Comment by benhaynes** [comment]
Is that the proper extension? Or is it `.handlebars`?

**Comment by WellingGuzman** [comment]
I don't think there's an official extension, but I've seen using `.hbs` and `.handlebars` but as `.hbs` is shorter and I'm used to that, I was going to do it, but it's open for voting.

**Comment by diegogurpegui** [comment]
>  does your server has cache/minifier/security layer modifying the html served by directus?

Not really, just a standard installation. Also, keep in mind that this works well on Chrome (same server, same installation).

**Comment by WellingGuzman** [comment]
Hey @diegogurpegui, I was just testing this again without any luck.

Is there a way that you can share an url (demo server) where we can see the error live? or probably screenshots/screencast showing the requests and the network tabs errors/message?

**Comment by rijkvanzanten** [comment]
We have been testing this extensively, but hadn't any luck at all replicating this issue. Could you please check if you maybe have any extensions active which could interface with the code execution? I'll close this for now as this issue has been open for a little while without any real progress.

If anyone has any specific additional information or a schema we can use to replicate this, we'd be more than happy to re-open and re-investigate this issue.

**Comment by diegogurpegui** [comment]
Hi everyone. Sorry for not participating that much on this lately.
I just wanted to let you know that this issue seems to no longer be present in the brand new version of Firefox.
Thanks!
