### ISSUE TITLE
Directus 9.22.1 Google Cloud Store (GCS) 403 error on assets

### ISSUE THREAD

**Issue by hamza-zafar-319** [directus/directus#17022]
### Describe the Bug

After upgrading from 9.21.2, pre-existing assets are getting a 403 HTTP error. This error occurs when externally using  /assets API and inside the App. I can successfully upload and view files, but all files uploaded before the update cannot be accessed. For example, pre-existing assets like a custom application logo do not load post-update. 

My Env file has the following:
```
STORAGE_LOCATIONS="gcs"
STORAGE_GCS_DRIVER="gcs"
STORAGE_GCS_ROOT="/beta"
STORAGE_GCS_KEY_FILENAME="./key_file.json"
STORAGE_GCS_BUCKET=xyz_storage
```
This is what the key_file.json looks like; it was pulled directly from GCP. I redacted all the sensitive stuff.
```
{
  "type": "service_account",
  "project_id": "redacted_project_id",
  "private_key_id": "redacted_private_key_id,
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQI....redacted..nZXqk=\n-----END PRIVATE KEY-----\n",
  "client_email": "redacted@redacted.iam.gserviceaccount.com",
  "client_id": "redacted_client_id",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/redacted%40redacted.iam.gserviceaccount.com"
}
```

Ref:
[Directus Docs on setting up GCS ](https://docs.directus.io/self-hosted/config-options.html#google-cloud-storage-gcs)

### To Reproduce

1. Update Directus 9.21.2 to 9.22.1.
2. Try to access any pre-update asset.

### Errors Shown

403 errors in the console when viewing the File Library in the App

![image](https://user-images.githubusercontent.com/98976335/210649431-862fc258-b090-45a8-852b-96cafc3abc33.png)

Chrome stacktrace with the "network" tab:
```
(anonymous) @ http://127.0.0.1:8055/admin/assets/use-sync.bc96de7c.js:28
of @ http://127.0.0.1:8055/admin/assets/use-sync.bc96de7c.js:28
af @ http://127.0.0.1:8055/admin/assets/use-sync.bc96de7c.js:28
request @ http://127.0.0.1:8055/admin/assets/use-sync.bc96de7c.js:28
Ke.<computed> @ http://127.0.0.1:8055/admin/assets/use-sync.bc96de7c.js:28
(anonymous) @ http://127.0.0.1:8055/admin/assets/use-sync.bc96de7c.js:27
l @ http://127.0.0.1:8055/admin/assets/index.0fe04da9.entry.js:2623
(anonymous) @ http://127.0.0.1:8055/admin/assets/index.0fe04da9.entry.js:2623
```

Chrome response in the network tab:
`{"errors":[{"message":"You don't have permission to access this.","extensions":{"code":"FORBIDDEN"}}]}`

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

v18.12.1

### What database are you using?

MySQL 8.0.31

### What browser are you using?

Chrome / Firefox

### How are you deploying Directus?

Running locally on Ubuntu 22 LTS with PM2 (Production ENV) and Locally on Windows 11 (Dev Env)

**Comment by Logrythmik** [comment]
I am having the same issue and I think I know what is going on. Our config:

```
STORAGE_LOCATIONS: gcp,local
STORAGE_GCP_DRIVER: gcs
STORAGE_GCP_KEY_FILENAME: /google/service-key.json
STORAGE_GCP_BUCKET: dxp-archer
STORAGE_GCP_ROOT: cms
```
New files are getting written to:
`cms/cms/<file>`
while old files still live at:
`cms/<file>`

This update changed the meaning of the 'STORAGE_X_ROOT' path.

**Comment by u12206050** [comment]
Can we assume the meaning of `STORAGE_X_ROOT` will be reverted. Such that we don't need to start updating file paths in database? @rijkvanzanten

**Comment by u12206050** [comment]
Hmm, after updating to 9.22.4 I am still getting 403 for the majority of files. Any new files uploaded seem to be fine, but all previous files are giving 403 in response (even as admin).
I've tried spotting any differences in file names but can't seem to find any. 

Anyone have a similar problem with solution?

**Comment by u12206050** [comment]
Ha! Right after writing above, I checked in the actual cloud bucket, and it seems that previous files actually have never been written to the path as specified in env which is `/` and now I see the new folders are stored in a file called `/` :D So guess I can just remove the root.
