### ISSUE TITLE
Unable to make M2O field required in UI

### ISSUE THREAD

**Issue by nithinga** [directus/directus#1702]
## Version Info
 - Directus version and branch: version/6.4 - da6d751afa1d454b8efefa6ec1b06647eecaefdd
 - PHP version: 7.1
 - MySQL version: 5.7
 - Web server: Apache
 - OS name and version: Docker ( Ubuntu )

## Expected Behavior
Provision for validating the dropdown field in UI. Eg: I need to make a dropdown mandatory.

## Actual Behavior
There is no UI for validation for relational dropdown field.

**Comment by WellingGuzman** [comment]
Validation or required? You can make the column required, and it should make the dropdown mandatory if that's what you are looking for.

**Comment by nithinga** [comment]
@WellingGuzman How can we make the given coloum required ?
![screenshot from 2017-07-21 11 09 40](https://user-images.githubusercontent.com/18306604/28450916-f660cbc4-6e07-11e7-867d-b817344bb2d7.png)

![screenshot from 2017-07-21 11 09 53](https://user-images.githubusercontent.com/18306604/28450924-fc916a80-6e07-11e7-8edb-d1975e568d90.png)

**Comment by WellingGuzman** [comment]
The stars in the columns list

<img width="383" alt="screen shot 2017-07-21 at 2 05 01 am" src="https://user-images.githubusercontent.com/1531291/28451043-0de2bbda-6db9-11e7-904d-e2f74a22f141.png">

**Comment by nithinga** [comment]
@WellingGuzman It is not working for dropdown.

**Comment by WellingGuzman** [comment]
@nithinga it must be an interface issue, Which dropdown interface are you using and what's the information on that column, allow null? has default value?

**Comment by WellingGuzman** [comment]
I see you that you have `allow_null` to false, which mean you have a value selected by default. which won't bring the required value warning as you already _probably_ have a value selected which will pass the validation.

Can you please elaborate more about this issue?

**Comment by nithinga** [comment]
@WellingGuzman yes..... M2O interface It is allow null = true ( allow null then only the option "select from below" comes ) Sorry for the wrong screenshot... messed it when playing around with it.

**Comment by WellingGuzman** [comment]
It's all good, I will give it a look now and fix it asap

**Comment by WellingGuzman** [comment]
Hey @nithinga, this commit (https://github.com/directus/directus/commit/3fefadd83d79e033ae1e93752e4d6c2ab8dafa9c) should fix the missing validation.

Please confirm.

**Comment by nithinga** [comment]
@WellingGuzman Thank you... This solves the issue in M2O field.

**Comment by WellingGuzman** [comment]
Awesome, @nithinga is this happening to you in other fields? or should I close it?

**Comment by WellingGuzman** [comment]
@nithinga I assumed there's nothing else. please let us know if there's interface not validating.
