### ISSUE TITLE
Slider's indicator of a "slider" field overlaps the field's note tooltip/hint

### ISSUE THREAD

**Issue by jotatoledo** [directus/directus#17021]
### Describe the Bug

Seems like the margin/paddings arent enough to prevent this situation, see attached pictures (particularly the `Level` field at the bottom of the 1st picture):

![image](https://user-images.githubusercontent.com/20740204/210648557-f4f59976-f4da-4c49-8206-985f721ef3fe.png)
![image](https://user-images.githubusercontent.com/20740204/210648863-b0d35eb4-f698-42b4-8224-25071a787689.png)

### To Reproduce

Setup a field as slider with a note

### Errors Shown

Overlapping

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18.12.1

### What database are you using?

Postgres 14.5

### What browser are you using?

MS Edge

### How are you deploying Directus?

docker in azure app service

**Comment by rijkvanzanten** [comment]
The added margin should be added when the "Always show value" option is set 👍🏻
