### ISSUE TITLE
Mutations have disappeared from the graphql scheme

### ISSUE THREAD

**Issue by Corentin7301** [directus/directus#17036]
### Describe the Bug

Hello,
As the title says, the mutations have disappeared from my graphql scheme.
Either on the url: /graphql or /graphql/system.
On /graphql, all mutations have disappeared.
![image](https://user-images.githubusercontent.com/63867332/211023849-23d211eb-843e-41f1-ada9-2da94a1c1a94.png)
On /graphql/system, there are 14 mutations but many are missing!
![image](https://user-images.githubusercontent.com/63867332/211023893-0fd7036d-ea29-470e-952d-5714c80e70ea.png)

I use `9.22.1` Directus version

Thank you for your help!

### To Reproduce

I don't know...
Just have PostgresQL database and Directus GraphQL API.
The problem is the same in local or on server.

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18.12.1 in local

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally and on Coolify (Docker)

**Comment by br41nslug** [comment]
Did you authenticate your graphql request? By default the Public role will be used for unauthenticated request which generally does not have create/update/delete permissions to collections.
When adding an `access_token` i get all the mutations i am expecting based on permissions (on both endpoints):
![image](https://user-images.githubusercontent.com/9389634/211037249-8a0ba5cb-3a72-4ef7-8701-f17e3d8cfd92.png)

**Comment by br41nslug** [comment]
@Corentin7301 In this test i used an online version of graphiql https://lucasconstantino.github.io/graphiql-online/
Adding the token in the connection url explicitly
![image](https://user-images.githubusercontent.com/9389634/211043120-17e724b9-2e68-4d82-8350-8678ef02f0f9.png)

**Comment by Corentin7301** [comment]
Okay, I feel like it's okay, it must be Insomnia that has a problem...
Thanks a lot!
