### ISSUE TITLE
Date field not getting read only

### ISSUE THREAD

**Issue by nithinga** [directus/directus#1705]
## Version Info
 - Directus version and branch: version/6.4 - da6d751afa1d454b8efefa6ec1b06647eecaefdd
 - PHP version: 7.1
 - MySQL version: 5.7
 - Web server: Apache
 - OS name and version: Docker ( Ubuntu )

## Expected Behavior
When setting the date type field to readonly, it should be readonly

## Actual Behavior
When setting the date type field to readonly, it is not readonly, we can edit it

**Comment by WellingGuzman** [comment]
Would be nice that you mention that you are going to open a PR, so we don't have too start fixing the issue just to find minutes later a PR.

We do love PRs though, just a reminder.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/ba31626721d1cdc494b4ce29f594e9e4f0f290ab
