### ISSUE TITLE
File permissions are always forbidden and uploading an error returns "S3ServiceException"

### ISSUE THREAD

**Issue by pzehle** [directus/directus#17065]
### Describe the Bug

After upgrading the version of Directus to the latest one (which proves that it has nothing to do with this error because I downgraded later on and same result) and (the error I think is here) started to sort my files into folders, now using the API, admin and SDK, returns an 403 forbidden error for trying to view the files. Yes, permissions for public are directus_files, directus_folders, even directus_relations. Even in the app, as an admin, I am not able to view the files. Also, which I think is connected, uploading a file returns:

```json
{
	"type": "S3ServiceException",
	"message": "UnknownError",
	"stack": 302: UnknownError
              at throwDefaultError (node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js: 8: 22)
              at deserializeAws_restXmlPutObjectCommandError (node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js: 5782: 43)
              at runMicrotasks (<anonymous>)
              at processTicksAndRejections (node:internal/process/task_queues: 96: 5)
              at async node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js: 7: 24
              at async node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js: 14: 20
              at async StandardRetryStrategy.retry (node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js: 51: 46)
              at async node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js: 56: 20
              at async node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js: 5: 22
              at async Promise.all (index 0)
      "name": "302",
	"$fault": "client",
	"$metadata": {
		"httpStatusCode": 302,
		"attempts": 1,
		"totalRetryDelay": 0
	}
}
```

### To Reproduce

I have no clue to be honest, but I just started creating folders and moving the files into them, then I don't have permissions to the files anymore, and I can't upload new files.

Important thing to notice is that I am using digitalocean spaces as a CDN. It is correctly configured with Directus, as for week I was able to view, upload and manage files. In the CDN they are visible. This doesn't work in either localhost or the production server.

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18.13.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally and on an Ubuntu 20.04 server

**Comment by azrikahar** [comment]
Thanks for the report. Let's close this in favor of #16882 since there are other users reporting similar experience with DigitalOcean Spaces in that issue. It would also be helpful if you can share your current storage related environment variables over there which may help the debugging process 👍

**Comment by pzehle** [comment]
Thanks, I see the related issue, however, I don't see that those guys are having also the "forbidden" error. Do you think is related? Otherwise I would open the issue again...

**Comment by preetamslot** [comment]
I have the same issue with DigitalOcean spaces:
Files uploaded in an older version of direct return 403. But files uploaded in the newest version are working


```
STORAGE_DIGITALOCEAN_DRIVER="s3"
STORAGE_DIGITALOCEAN_KEY="********"
STORAGE_DIGITALOCEAN_SECRET="**********"
STORAGE_DIGITALOCEAN_ENDPOINT="https://fra1.digitaloceanspaces.com"
STORAGE_DIGITALOCEAN_BUCKET="********"
STORAGE_DIGITALOCEAN_REGION="fra1"
STORAGE_DIGITALOCEAN_ROOT="/"
STORAGE_DIGITALOCEAN_PUBLIC_URL="********"
STORAGE_DIGITALOCEAN_ACL="public-read"

```

```
"errors": [
   {
      "message": "You don't have permission to access this.",
      "extensions": {
      "code": "FORBIDDEN"
   }
]
```

![image](https://user-images.githubusercontent.com/5420582/211544874-a09364df-2ab9-4fde-9473-65a170129c25.png)

**Comment by pzehle** [comment]
@preetamslot 

Was this happening before the 9.22 upgrade? I am seriously thinking on downgrading fully to the older version, which gave less problems...

**Comment by preetamslot** [comment]
@pzehle This bug is since 9.22, on 9.21.2 I have no problems.

What's strange is that I can upload files, and view them. it only affects my previously uploaded files.
What is your STORAGE_DIGITALOCEAN_ENDPOINT  & STORAGE_DIGITALOCEAN_REGION ?

p.s on my spaces settings I have enabled CDN.
![image](https://user-images.githubusercontent.com/5420582/211565463-933ba474-d397-4a31-81c7-200d6698d0db.png)

**Comment by pzehle** [comment]
The weird thing is that, I downgraded and I was still having the issue, but to be honest maybe I did it wrong. I will try again and let you know.

On the other hand, my settings look like this:

```
STORAGE_DIGITALOCEAN_REGION="nyc3"
STORAGE_DIGITALOCEAN_ENDPOINT="nyc3.digitaloceanspaces.com"
```

Could it be that my backend is under nyc1? Anyway I don't think so, because it also does not work on localhost, and it used to work just fine anyway.

> What's strange is that I can upload files, and view them.

I can't upload files, and I can't view them. No matter permissions, admin, API, app, nothing. I just can't view older files. I can't upload new ones.

**Comment by pzehle** [comment]
Ok @preetamslot downgrading correctly makes everything work again. So yeah, we can pinpoint the problem to the newest version...

**Comment by preetamslot** [comment]
@pzehle 

I found my critter, it was 
```
STORAGE_DIGITALOCEAN_ROOT="/"
```
By removing that line all was working again

**Comment by pzehle** [comment]
Hi @preetamslot thanks. Unfortunately, I don't even have that directive in my .env.

**Comment by preetamslot** [comment]
@pzehle try setting the region to "us-east-1"
STORAGE_DIGITALOCEAN_REGION="us-east-1"

**Comment by pzehle** [comment]
@preetamslot I don't think that would solve it, since my region in in "ams". I will try some other things then. Thanks!
