### ISSUE TITLE
Enable `avif` image format

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#17076]
`sharp` supports `avif` natively nowadays, which means that our `format` query parameter and subsequent options in the app support it as well. We should go over all image transformation format uses and make sure `avif` is added to checks and lists.

**Comment by rijkvanzanten** [comment]
It feels safer to keep it static so we have a chance to test and confirm support before we enable/document certain file types. For example, in your list above, there's support for `application/gzip` but I have no clue what sharp will do when you try to rotate a gzip 👀

**Comment by paescuj** [comment]
> It feels safer to keep it static so we have a chance to test and confirm support before we enable/document certain file types. 

Very good point, you confirm my thoughts and I absolutely agree! 👍 
(The `application/gzip` is coming from `.svg.gz`... But I'd like to see the rotated gzip too 👀😄)

What do you think about the additional support of other formats? I don't think that anything speaks against `gif`, `heif`, `heic`, but `svg` would probably be a different story (I don't know what `sharp` is able to do with SVGs...).

**Comment by rijkvanzanten** [comment]
> What do you think about the additional support of other formats? I don't think that anything speaks against gif, heif, heic, but svg would probably be a different story (I don't know what sharp is able to do with SVGs...).

`heif` and `heic` are effectively new alternatives to `jpeg`, so we can "just" open those up. Gif is interesting though, as we need to support animated gifs. SVG needs a lot of testing before we open that up :)

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten is this something that can be supported on by a code contribution?

Yes! Open [Issues](https://github.com/directus/directus/issues) are actionable items that are awaiting implementation. That implementation can either come from a maintainer or a contributor. PRs are very welcome :)

**Comment by paescuj** [comment]
> @rijkvanzanten is this something that can be supported on by a code contribution?

I'd also be happy to see your code contribution on this! 😃 
Let's focus on adding support for `avif`, `heic` and `heif` for now and do `gif` in a separate step.

Here's what needs to be done:
* Update the list of supported formats in services (possibly consolidated in one place - [constants.ts](https://github.com/directus/directus/blob/main/api/src/constants.ts))
  * https://github.com/directus/directus/blob/dc135f776d3ba453e7764fc5471585bcba0ddc18/api/src/services/assets.ts#L116
  * https://github.com/directus/directus/blob/dc135f776d3ba453e7764fc5471585bcba0ddc18/api/src/services/files.ts#L90
* Add formats as possible options in transformation presets:
  https://github.com/directus/directus/blob/dc135f776d3ba453e7764fc5471585bcba0ddc18/api/src/database/system-data/fields/settings.yaml#L253
* Update translations:
  https://github.com/directus/directus/blob/dc135f776d3ba453e7764fc5471585bcba0ddc18/app/src/lang/translations/en-US.yaml#L1150
* Test it by uploading said formats, looking at metadata and requesting as transformed assets

**Comment by knulpi** [comment]
> Let's focus on adding support for `avif`, `heic` and `heif` for now and do `gif` in a separate step.

According to [sharps API doc](https://sharp.pixelplumbing.com/api-output#heif), the only direct usable option is `heif`, the `heic`-compression would need to be specified when calling sharp with the `heif` format. So this is a more complex option to add than just providing the format I guess.

Another thing, in the article about `heic` there is mentioned:
> Support for patent-encumbered HEIC images using hevc compression requires the use of a globally-installed libvips compiled with support for libheif, libde265 and x265.

I am not really sure if this is a commonly fulfilled requirement? 

Since this issue is about `AVIF` and I see less traps with adding support for it (also successfully tested it in my dev instance) I would suggest going with that in this scope first, would that also be okay, @paescuj ?

**Comment by knulpi** [comment]
One thing I just recognized is the missing AVIF-Support on Microsoft Edge and older Safari browsers...[caniuse](https://caniuse.com/avif) suggested this, and I tested it on Edge, with the following behavior:
![image](https://user-images.githubusercontent.com/24552458/214443106-04c30740-a168-48c1-9e11-6f48dea72825.png)

Is this something that should be taken care off in the scope of this issue? Like providing fallbacks or else?

**Comment by rijkvanzanten** [comment]
@knulpi Lets start with just `avif` as that's the scope of the OP 🙂  

> Is this something that should be taken care off in the scope of this issue? Like providing fallbacks or else?

I don't think so. We can add an improved error handler in a separate sprint 👍🏻

**Comment by paescuj** [comment]
> According to [sharps API doc](https://sharp.pixelplumbing.com/api-output#heif), the only direct usable option is heif, the heic-compression would need to be specified when calling sharp with the heif format. So this is a more complex option to add than just providing the format I guess.

Good point!

> @knulpi Lets start with just avif as that's the scope of the OP 🙂

Since it's really the exact same steps to enable `heif` as it is for `avif`, however, I'd say that we should take this opportunity and include `heif` in this scope. Do you agree @rijkvanzanten?

> Another thing, in the article about `heic` there is mentioned:
> 
> > Support for patent-encumbered HEIC images using hevc compression requires the use of a globally-installed libvips compiled with support for libheif, libde265 and x265.

In any way, we can't count on `libvips` being compiled with the necessary flags / libs (see also https://github.com/directus/directus/issues/17076#issuecomment-1380256547). In case the requested format is not supported, `sharp` will probably/hopefully just throw an error and we catch those already.

**Comment by knulpi** [comment]
@paescuj can you tell me your expected use case with `heif` or `heic`? According to [caniuse](https://caniuse.com/heif) no web browser at all currently supports that format. What's your motivation for adding it?

**Comment by paescuj** [comment]
Please keep in mind that the `assets` endpoint is not limited to browsers use but can theoretically accessed by anything (mobile app, ...).
As we're already going to touch these lines, I don't see any harm in enabling `heif` as well.
However, I fully agree with you that `heic` is out of this scope!

**Comment by rijkvanzanten** [comment]
@paescuj as long as we're certain it's the same scope :) the heic discussion made me a little worried ^^

**Comment by paescuj** [comment]
You know what? Let's skip `heif` for now and look at it again when there's an actual demand for it. This could save us from some questions in this regard... I'm really sorry for the noise! 🙈 So, that's a "go" from my side 🚀😃
