### ISSUE TITLE
Wrong validation message when putting a character other than a number in a number-field

### ISSUE THREAD

**Issue by JonathanDoelan** [directus/directus#17074]
### Describe the Bug

Wrong validation message `Value can't be null` when putting a character other than a number in a number-field. Validation message should be something like `Only numbers allowed`.

### To Reproduce

Create a collection with a number field, create a new entry and put a character into the field, that is not a number.

### Errors Shown

`Value can't be null`

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

Latest

### What database are you using?

MySQL

### What browser are you using?

Firefox

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
Even though it's a little unexpected for non-technical users, it is in fact working as expected. Numeric inputs (eg `<input type="number">` allow typing characters for things like `2e6` which is then saved as a number. A regular single character doesn't stage anything in the input, which means you're not actually saving anything. Happy to discuss potential improvements in a new feature request 👍🏻
