### ISSUE TITLE
Cache problems

### ISSUE THREAD

**Issue by peremp** [directus/directus#1708]
## Version Info
  - Directus version and branch: 6.4.0

There are various problems related with the cache.

**schema**:
tables: `problems`, `solutions`, `use_cases` tables.
columns: `problems` and `solutions` have a M2M relation using `use_cases` as junction table.

## Example 1:
Imagine that we have a `problem` with some related `solutions`. The `use_cases` are in DRAFT, so when I am editing the problem, in the list where the solutions are shown (M2M interface), the status is DRAFT (expected, since the `use_cases` are in DRAFT).
But if I change the `use_cases` status to publish, and go back to the problem, the items in the M2M list still appearing as DRAFT.

If I check "disable cache" on developer tools and refresh, then the status is displayed correctly.

## Example 2:
This example does not happens always, but the root problem is the same:

If you create a `problem` with a related `solutions` using the M2M interface, and then you go to the `solution` you added to the `problem`, the `problem` does not appear in his M2M list.

If you do an F5 with "disable cache" enabled on developer tools, then the problem appear.

**Comment by peremp** [comment]
Seems that this is happening more often than expected.

Another easy example that is happening to us:
- Open any item from any table.
- Edit any text/varchar field (or any WYSIWYG).
- Save (Directus send you back to table list)
- Enter the item you edited

**Expected:**
The item is modified.

**Current:**
The item is modified BUT you still see the old information until you `disable` the cache using the developers tools.

This is a big problem in the sense that, if you save again, you overwrite the changes that you have done before.

Also, the editors can't be 100% sure that their changes are applied or not.

**Comment by WellingGuzman** [comment]
Hey @peremp, now I'm realizing this probably is one issue that has been reported before.

If you go to your `GET` requests of the data, does it says "from cache" in the dev tools network tab?

Do you have an specific configuration to cache http requests?

We are thinking on forcing getting new entries by appending some param on the url, so we get a new data no matter the cache the server/browser has configured.

**Comment by benhaynes** [comment]
Hey @peremp – do you have time to give this a quick test?

**Comment by hybridvision** [comment]
I'm not sure if this is directly related but when I re-order the fields and then go to edit or add a record in that table, the old field order is used until I do a full refresh.

I have also seen some odd behaviour while testing where it looks like data I enter into the admin settings for field interface options (eg. placeholder text and options JSON) is not recorded. It appears to save normally but then I get a little warning icon in the User Interface column and it has the tooltip `Requires additional setup`. When I click to edit that field immediately, everything is blank in the Interface Options popup (ie. no placeholder text and no options JSON). At this point, if I refresh the whole page, the warning icon is no longer present and if I open the Interface Options popup, I see the data I entered previously.

I'm on the latest commit from the `develop` branch but I think I was seeing it in `master` too.

**Comment by peremp** [comment]
Hello!

I was on vacation :)! I'll test this as soon as possible @benhaynes @WellingGuzman

**Comment by peremp** [comment]
```
Request Method:GET
Status Code:200 OK (from disk cache)
```

**Comment by WellingGuzman** [comment]
Hey @peremp, are you using apache? I would love to know if you have some sort of cache configuration in your server, I will try to add a new param on each requests so we make sure the cache is not being made.

**Comment by WellingGuzman** [comment]
Hey @peremp, I've added a new query param with different value for each `GET` request this will potentially prevent the browser from catching the results.

Let us know if this fixes the problem. We will implement a proper cache solution server and client side.

This probably also fix the issue #1710.

**Comment by peremp** [comment]
Looks like it's working on the edit page. Still happens on the table list:

```
Request URL:http://localhost:8282/api/1.1/tables/solutions/rows?currentPage=0&perPage=30&sort=id&sort_order=ASC&status=1%2C2&columns_visible=slug%2Ctitle%2Cdescription%2Cauthor_full_name%2Cauthor_email%2Cauthor_avatar%2Cmain_tag_id%2Cid%2Cstatus
Request Method:GET
Status Code:200 OK (from disk cache)
```

Also, not sure if this is related to this changes, but the list of related items (M2M interface) is always empty, even if you relate some items.

**Comment by WellingGuzman** [comment]
Hey @peremp, did you clear you cache, or what branch are you using? Almost request now (including listing table and editing entry) now has a new query string param to prevent caching and the URL you used as example doesn't have that param included.

Same with the M2M being empty was fixed on develop branch. Let us know if it doesn't work in develop branch and we can take care of it.

**Comment by peremp** [comment]
Version: develop bed51a7
Tested on incognito window and on a normal window clearing and disabling the cache.

Same result: The M2M list is empty, and the param is not included when loading a table list.

**Comment by hybridvision** [comment]
@WellingGuzman / @peremp: I'm on the same latest version and I see the `reqid` parameter but only for viewing specific records. For example:

![image](https://user-images.githubusercontent.com/11492432/29567912-ecadfbaa-874e-11e7-985c-3c40c3dcda7b.png)

None of the other API requests seem to include this parameter...

Also, I noticed that there's a constant polling of the messages table. I guess this is needed for the messaging functionality but is there a way to disable it if we don't use it? (Sorry, a bit off topic)

**Comment by Zaelot** [comment]
Encountered another cache related problem when we upgraded to the latest version: Got stuck in a loading screen for /tables after logging in, on Chrome. Solution was to clear the cache (also deleted Directus cookie.)

  

Console log from the situation:
![image](https://user-images.githubusercontent.com/2608781/29614815-58e46a0a-8814-11e7-8346-aa0fb3472ee2.png)

**Comment by WellingGuzman** [comment]
@Zaelot the browser was caching the old files, this has been an continuous issue that I'd have to find a "force" solution when upgrading.

@hybridvision can you tell us what request doesn't get included?

@peremp I've added a `no-cache,no-store` header on all `GET` request, give it a try and let me know if that works, this is a hotfix, until we find a proper way to manage all these browser caching issue we are having.

**Comment by benhaynes** [comment]
What is the status of this? Could we check to see if these caching issues are persisting? @Zaelot @hybridvision @peremp 

@WellingGuzman – are there any other files we should stop from caching? We should make sure that this still allows for IMAGES to cache... so that the File Library doesn't load too slowly.

**Comment by WellingGuzman** [comment]
I only stopped from caching all `GET` request from the API, again this is temporary, until we implement the cache solution.

**Comment by benhaynes** [comment]
These caching issues should all be resolved based on the updates from Welling. Caches can be pretty sticky – so please remember to try other browsers and incognito to debug these issues.

I'll close this as "complete" for now. Let us know if there are additional cache related issues that arise.

**Comment by peremp** [comment]
Still having cache problems on table lists.

```
Request URL:http://localhost:8282/api/1.1/tables/solutions/rows?currentPage=0&perPage=30&sort=id&sort_order=ASC&status=1%2C2&columns_visible=slug%2Ctitle%2Cdescription%2Cauthor_full_name%2Cauthor_email%2Cauthor_avatar%2Cmain_tag_id%2Cid%2Cstatus
Request Method:GET
Status Code:200 OK **(from disk cache)**
```

Maybe is something related to Nginx, but I can't see the headers that you mention @WellingGuzman

**Comment by WellingGuzman** [comment]
@peremp you may still be using old code, there's not `reqid` param anywhere, in what commit are you working on?

I still want to know if you have any browser plugin install or any server caching solution or configuration.

**Comment by peremp** [comment]
Are you sure about the reqid? https://github.com/directus/directus/blob/b0677b8512527bec04a1eec3ac4d4208dbfa7d1f/app/core/entries/EntriesModel.js#L343

I'm always using the latest version of develop (right now: commit b0677b8), and I still see the reqid on calls like:

```
http://localhost:8282/api/1.1/tables/problems/rows/481?preview=true&reqid=1504686607400
```

To test I use Chrome (incognito window), so the extensions are not loaded. Anyway I have Adblocks, Postman and JSON View extensions.

We have cache for statics, not for GET/POST requests.

**Comment by WellingGuzman** [comment]
After re-reading all this once again and test it more carefully, I see where the problem relies, when we update the related status, we actually update the related data status, not the JUNCTION data status.

We've had discussed this internally, how should we handle the junction table? should we have a new button that will jump to the junction table record instead of the related data record?

So @peremp if you can go to the junction table and update the status on the junction table does that change get reflected?

**Comment by WellingGuzman** [comment]
Another option would be, having both related and junction table in the same item view, with a separator in between.

**Comment by WellingGuzman** [comment]
As the report of this was a confusion I may call this a missing feature, so I will add it as feature request. https://request.getdirectus.com/r/121

As the problem was setting the junction status value, in the meantime any user experiencing this problem can go directly to the table, I'm sorry this doesn't seems to intuitive, but we want to get all the feature to separate from the issues. Although it seems like one.

**Comment by WellingGuzman** [comment]
Anyone can go to https://request.getdirectus.com/r/121 and we can discuss how would be a best way to handle this.

**Comment by william-roy** [comment]
I've tried following the issues referenced here, but can't seem to find whether this was ever resolved or accurately diagnosed, apologies if I'm missing something. I'm experiencing the exact same behavior @peremp first described on a fresh install of the latest release. Running Apache 2.2.31, PHP 7.3, MySQL 5.6.
