### ISSUE TITLE
Token expire when using "Auto Refresh"-Feature in a background tab [ /auth/refresh is missing]

### ISSUE THREAD

**Issue by Lukas-Sachse** [directus/directus#17083]
### Describe the Bug

I updated directus from v9.11.1 to v9.22.1. Then I noticed a bunch of "Token Expired" sometimes in my console. 

After reading https://github.com/directus/directus/issues/16188 and some testing I realized it only happens when an "Auto Refresh" from the sidebar is running in a background tab. In that case there won't be triggered an "/auth/refresh".

When the browser tab with directus is open/active it works as expected.

### To Reproduce

1. Set your ACCESS_TOKEN_TTL to "1m" (for faster reproduction)
2. Set your LOG_LEVEL to "debug"
3. Choose a Collection
4. Set up "Auto Refresh" in the sidebar for 30sec
5. Switch to a new Browser Tab (directus in background tab)

The first refresh after 30sec should work. All other refreshes after 1m should fail and show a "Token expired.".

6. Switch to the directus browser tab again

An /auth/refresh will be triggered and all "Auto Refreshes" will work again

### Errors Shown

_Disclaimer: I cleaned the file paths to only show the part after node_modules folder._

**DEBUG: Token expired.**
```
    err: {
      "type": "TokenExpiredException",
      "message": "Token expired.",
      "stack":
          Error: Token expired.
              at verifyAccessJWT (CLEANED\directus\dist\utils\jwt.js:38:19)
              at handler CLEANED\directus\dist\middleware\authenticate.js:44:55)
              at runMicrotasks (<anonymous>)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
      "status": 401,
      "code": "TOKEN_EXPIRED",
      "extensions": {}
    }
```

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18.12.1

### What database are you using?

Postgres 13

### What browser are you using?

Vivaldi (Chromium)

### How are you deploying Directus?

locally, render.com

**Comment by paescuj** [comment]
We should probably apply the idle tracker currently used in the "Auth Refresh" to the "Auto Refresh" as well:
https://github.com/directus/directus/blob/cb275308eb7f2a7490ad8b06e1c2775c94edfcef/app/src/auth.ts#L62-L63

Based on this report, I've the impression that this is not currently the case...

**Comment by jay-p-b-7span** [comment]
> We should probably apply the idle tracker currently used in the "Auth Refresh" to the "Auto Refresh" as well:
> 
> https://github.com/directus/directus/blob/cb275308eb7f2a7490ad8b06e1c2775c94edfcef/app/src/auth.ts#L62-L63
> 
> Based on this report, I've the impression that this is not currently the case...

Let me know whether to provide support for this issue ?

**Comment by jay-p-b-7span** [comment]
## Problem
When app tab is inactive, `auto refresh` logic is running and `hide` event is triggered to clear `refresh timer` due to which we are getting token expired error. 

## Discussion
Based on the investigation, we have two scenarios
1. We stop the `auto-refresh` logic request when tab is inactive. 
2. We disable clearing timer logic in `app/auth.ts` file when either `hide` or `idle` event is triggered. 
![image](https://user-images.githubusercontent.com/93135924/214573327-8bec6c2d-5ef0-4f89-9d5d-2a4abb51a9e1.png)

Let me know your feedback @rijkvanzanten.

**Comment by paescuj** [comment]
> 1. We stop the auto-refresh logic request when tab is inactive.

Let's do this one!

There's a reason for disabling auth refresh when tab is inactive (see https://github.com/directus/directus/pull/7177), so we should keep this part as it is.

**Comment by bamboowonder** [comment]
It looks like this is just waiting to be merged?   Just here to give this a little love nudge.  :)

**Comment by paescuj** [comment]
> It looks like this is just waiting to be merged? Just here to give this a little love nudge. :)

Still requires a proper review...  :-)
