### ISSUE TITLE
403 error when editing m2a item inside drawer

### ISSUE THREAD

**Issue by d1rOn** [directus/directus#17108]
### Describe the Bug

When I click on item in m2a interface, the drawer is opening. In the same time the 403 error popup appears.

In DevTools I see that **app is trying to fetch the junction collection with and id of m2a item** (that is related to another collection).
This API call is performed by:
https://github.com/directus/directus/blob/abde5adacdfa8a377d941923059c97c72ef6e15a/app/src/views/private/components/drawer-item.vue#L319

The 403 error appears every time when junction collection item with an id of item collection is not exists (very often).

### To Reproduce

1. Create collection A with m2a relation.
2. Create an item of A, add at least one "any" item.
3. Open editing page of created A item.
4. Try to edit one of "any" item. The 403 error will appear.

I suggest to use PK type = UUID for all collections, because of auto-incremented ids can be the same in junction and "any" collections.

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

v17.9.0

### What database are you using?

MySQL 8

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally

**Comment by vanling** [comment]
I think I just ran into the same issue, directus_users with a m2a to favorites_coll_a, favorites_coll_b. Opening the drawer in a user results in a 403 and an `[object Object]` on item. _(in api via frontend everything works fine)_


![Schermafbeelding 2023-01-12 om 09 55 18](https://user-images.githubusercontent.com/50699657/212022076-c60bd178-d45d-4ad7-9c77-d22dc3dd16fc.jpg)


```
[08:47:30.166] TRACE: [15.686ms] select `junction_directus_users_favourites`.`collection`, `junction_directus_users_favourites`.`directus_users_id`, `junction_directus_users_favourites`.`id`, `junction_directus_users_favourites`.`item` from `junction_directus_users_favourites` where `junction_directus_users_favourites`.`id` = ? order by `junction_directus_users_favourites`.`id` asc limit ? [56, 100]
    }
      "extensions": {}
      "code": "FORBIDDEN",
      "status": 403,
             .....
          Error: You don't have permission to access this.
      "stack":
      "message": "You don't have permission to access this.",
      "type": "ForbiddenException",
```

**Comment by JonathanDoelan** [comment]
Same here, when opening an existing item of an M2A field in the drawer, an error occurs:

```json
{
  "errors": [
    {
      "message": "You don't have permission to access this.",
      "extensions": {
        "code": "FORBIDDEN"
      }
    }
  ]
}
```

It also happens in a O2M field, but not in all O2M fields …

**Comment by licitdev** [comment]
The primary key of the related item is incorrectly fetched from the junction table when the drawer is opened.

a <= junction => b

the drawer fetches from `/items/junction/{b.id}` instead of `/items/junction/{junction.id}`, leading to the 403.

**Comment by licitdev** [comment]
Refer to #17167 for another way to reproduce this issue / to test the fix.
