### ISSUE TITLE
composer.lock removed from repository

### ISSUE THREAD

**Issue by wittwerch** [directus/directus#1711]
I noticed that the composer.lock was removed from the repository (e732c931f6a7dadc1713e215786f0bbac263ff42, 1634a22aa3384d7d15028cb43f1e7dc528c7ef13). Can you please explain why?

> Committing this file to VC is important because it will cause anyone who sets up the project to use the exact same versions of the dependencies that you are using. Your CI server, production machines, other developers in your team, everything and everyone runs on the same dependencies, which mitigates the potential for bugs affecting only some parts of the deployments. Even if you develop alone, in six months when reinstalling the project you can feel confident the dependencies installed are still working even if your dependencies released many new versions since then. (See note below about using the update command.)

https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control

**Comment by WellingGuzman** [comment]
Some developers were having some issue where they have to regenerated the `composer.lock` to their php version, mainly from php 5 (Generated by us) to php 7 (generated by them).

it was difficult to find out the issue or why some package were missing or an error was showing up to some but not to others. This way people will have a fresh vendor from their php version, which we (Contributors and Developers using Directus) are now going to get a more sense or what going on.

This was a long discussing subject that we end it up just doing it, and see what happens after it stopped happening to us.

**Comment by wittwerch** [comment]
Ok, I was not aware of these problems. I think removing `composer.lock` will introduce a whole bunch of potential new problems. You loose track of what exact versions were used to develop a feature. Also during the deployment you potentially end up with different versions on test and production environments.

However I'm going to add a `composer.lock` to our forked Directus project. Thanks for the open communication, you can close the issue.

**Comment by WellingGuzman** [comment]
Thanks @wittwerch, we were aware of the benefits you mentioned, but we are going to let users do it by themselves and see how it goes, depends on it we can bring it back or find better way to handle these issues. we are always welcome to discuss anything that bring improvements to Directus.

Thanks for pointing this out
