### ISSUE TITLE
Bad URL in reset password email

### ISSUE THREAD

**Issue by martinfojtik** [directus/directus#1712]
## Version Info
  - Directus version and branch: develop
  - PHP version: 7
  - MySQL version: 
  - Web server: (Ex. Apache, nginx or IIS?) 
  - OS name and version: 

## Expected Behavior

After I click on the link in reset password email, I am redirected to error 404 page. URL in email is `http://example.com/api/1/auth/reset-password/XXXreset_tokenXXX`

## Actual Behavior

I think URL should be `http://example.com/api/1.1/auth/reset-password/XXXreset_tokenXXX`

## Steps to Reproduce
 1. 
 2. 
 3.

**Comment by WellingGuzman** [comment]
Thanks for reporting this @martinfojtik. It has been fixed by https://github.com/directus/directus/commit/adc5685383d1819435e05b368ca50b8679b0002b
