### ISSUE TITLE
Sometimes clicking on a M2A item does not work

### ISSUE THREAD

**Issue by JonathanDoelan** [directus/directus#17127]
### Describe the Bug

Sometimes when clicking on a M2A item nothing happens. After a few more tries it then works. It seems like it didn't load right away. Indeed it takes longer for relations that have lots of fields in it. 

### To Reproduce

Create a collection (let’s say projects) with a M2A field (slides). For the junction table create a collection called `projects_slides` and for the relation a collection called `projects_slides_items`. For the `projects_slides_items` collection add lots of fields (at least to file or image fields). Create a new item in the projects collection and add multiple new items to the slides. Save the project and reload the page. Then click on one of the M2A items.

### Errors Shown

nope

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

Latest

### What database are you using?

MySQL

### What browser are you using?

Firefox

### How are you deploying Directus?

Docker

**Comment by Nitwel** [comment]
I was not able to reproduce this, even with a somewhat large amount of fields.
It does take a bit to fully load but that is to be expected. 

![GIF 03 02 2023 15-50-45](https://user-images.githubusercontent.com/22577866/216633862-0c708c6e-a349-4da0-a611-8c442319ae72.gif)

Please feel free to reopen this if there is a consistent way to reproduce this. 😄
