### ISSUE TITLE
User group can't edit own profile

### ISSUE THREAD

**Issue by Zilus** [directus/directus#1713]
## Version Info
  - Directus version and branch: 6.4
  - PHP version: 7.1
  - MySQL version: 5.6
  - Web server: apache
  - OS name and version: Ubuntu 14.04

## Expected Behavior
I created a user group, with the ability to edit their own profiles.

## Actual Behavior
I Cant edit my own profile (as a user from that group)

## Steps to Reproduce
 1. Log as admin
 2. Create user group
 3. Leave "Allow Profile Editing" checked
 4. Log in as a user from the new group
 5. Go to profile and try to edit something

## Schema Dump, Logs, or Screenshots
<img width="1072" alt="captura de pantalla 2017-07-26 a la s 6 12 29 pm" src="https://user-images.githubusercontent.com/1158317/28647693-49b66872-722e-11e7-9b7d-262cc738657b.png">

[dump.txt](https://github.com/directus/directus/files/1178284/dump.txt)

**Comment by dsivokhin** [comment]
Hello, I have the same problem, I will add to this issue error message
`Error
Error: Uncaught TypeError: this.get(...).get is not a function
File: https://directus.qnap.ru/app/modules/users/UsersModel.js?bust=798e08c391723309a7c18943477c056b388f393a
Line:72`

**Comment by WellingGuzman** [comment]
Hey @Zilus are you experiencing the same error @dsivokhin is having?

**Comment by WellingGuzman** [comment]
Hey @Zilus + @dsivokhin, does this commit (https://github.com/directus/directus/commit/26968b0c121cf6ab77fa85512e0aed38610538e5) fixes the issue you've experiencing?

**Comment by dsivokhin** [comment]
Hi @WellingGuzman, thanks, it works, users can edit own profiles now. But I see another issue, I can't change group for any users. I am admin, go to edit user page, changing group and save, but new value not save in database and no error on screen. This problem was before this commit.

**Comment by WellingGuzman** [comment]
This may be related to https://github.com/directus/directus/issues/1719.

I will give it a spin.

**Comment by WellingGuzman** [comment]
Hey @dsivokhin, check this patch (https://github.com/directus/directus/commit/443e4449d7fe9a4991257f5f9deb8c92ee915286) and let me know if it fixes the other issue.

**Comment by dsivokhin** [comment]
Hi @WellingGuzman , yes, it works.

**Comment by WellingGuzman** [comment]
Great @dsivokhin, thanks for letting us know.

Any feedback @Zilus?

We are decided to remove `Allow Profile Editing` and only let the user edit their profile based on their group's permission. (Small edit = can only edit their profile, Big edit = can edit any user profile)

**Comment by WellingGuzman** [comment]
We removed `show_users` column from `directus_groups` (labeled as `Allow Profile Editing` on groups editing page) to allow any group to edit their own profile must have Small edit and to edit any profile must have big edit permission.

Closed by https://github.com/directus/directus/commit/fda63e4e93f6152fe943fe66505fc28b0ab6beea
