### ISSUE TITLE
Extension - subpage is possible ?

### ISSUE THREAD

**Issue by Yanlaz** [directus/directus#1714]
I try to create a extension. It's work fine but i need a lot a page for this extension and i don't want to create one extension per page.  It's possible to create some subpage for extension ? I don't find the way.

I manage to create 2 pages for one extension but not to add this in sidebar. I try to include a partial template menu in my template but it doesn't work too. 

I don't find docs for extension, only https://medium.com/directus/how-to-setup-a-custom-extension-770d6ea48551 but it don't really help me.

**Comment by WellingGuzman** [comment]
Yes, it is possible. we are going to update our example extensions to support multiple view and a internal extension menu.

**Comment by WellingGuzman** [comment]
Also to give you a hint or the way to do it, you can add more routes in the Router object (https://github.com/directus/directus/blob/master/customs/extensions/_example/main.js#L55)

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/68c907264ee9035dc7d3c6e1689ea8e208e1fdfd
