### ISSUE TITLE
M2A fields are not copied on `Save as Copy` 

### ISSUE THREAD

**Issue by JonathanDoelan** [directus/directus#17150]
### Describe the Bug

When hitting `Save as Copy` M2A fields are not copied. An `Invalid Item` message appears in the M2A field.

### To Reproduce

Create a `projects` collection with a M2A field called `slides`, that creates the `projects_slides` junction collection. The junction collection connects the `projects_slides_images` and the `projects_slides_videos` collection. To keep it simple create only a title field (input field) for every collection. Now create a project item with some items in the M2A field, then open it again, change something and hit `Save as Copy`. Then the related items of the M2A have a `Invalid Item` message.

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

Latest

### What database are you using?

MySql

### What browser are you using?

Firefox

### How are you deploying Directus?

Docker

**Comment by br41nslug** [comment]
Have you selected the required "Item Duplication Fields" for the collection with the m2a you want to save as copy? Looks to be working in a quick test on v9.22.4
![firefox_dHQOSKKX6y](https://user-images.githubusercontent.com/9389634/212872937-0fb0e070-99c6-4023-98f6-9df42b486c1b.gif)

**Comment by JonathanDoelan** [comment]
@br41nslug Thanks. I got it working now, but it is really complicated, because we need to think through the whole structure. I think there could be an easier solution for this. I will write a feature request the next days … ;)
