### ISSUE TITLE
directus_files table incomplete after installation

### ISSUE THREAD

**Issue by LiamMartens** [directus/directus#1715]
## Version Info
  - Directus version and branch: 6.40
  - PHP version: 7.0
  - MySQL version: MariaDB 15.1
  - Web server: Caddy 0.10.6
  - OS name and version: Alpine3.5.0 in Docker

## Expected Behavior
Should create the columns `url`, `thumbnail_url`, `old_thumbnail_url` and `html`

## Actual Behavior
They aren't being created causing the Many-To-Many file relation to fail.

## Steps to Reproduce
 1. Go through installation
 2. Create a table with a Multiple Files field
 3. Add a file

## Schema Dump, Logs, or Screenshots
![deepin-screen-recorder_google-chrome_20170731170627](https://user-images.githubusercontent.com/5265324/28784087-a52716c4-7612-11e7-8c5c-9b05cc275c38.gif)

![deepinscreenshot_select-area_20170731170659](https://user-images.githubusercontent.com/5265324/28784100-acb7f9a8-7612-11e7-8231-a2834a7c3d0e.png)

**Comment by WellingGuzman** [comment]
Hey @LiamMartens can you test this on `develop` branch?, I believe this was reported before and fixed, not yet released, it will be on 6.4.1.

**Comment by WellingGuzman** [comment]
Also the columns `url`, `thumbnail_url`, `old_thumbnail_url` and `html` are just helpers, never meant to be actual columns (created).

**Comment by benhaynes** [comment]
Hey @LiamMartens – if you have a chance, we'd love for you to test/confirm this fix on the `develop` branch. We believe this has already been fixed and would love to get the issue closed if that's the case.

Either way, thanks for reporting this!

**Comment by LiamMartens** [comment]
@benhaynes Sorry for the delay, tested on `develop` branch and seems the Many To Many files relationship appears to be fixed indeed.
