### ISSUE TITLE
[GraphQL] Useful errors shouldn’t be redacted for non-admin users

### ISSUE THREAD

**Issue by LeBenLeBen** [directus/directus#17168]
Currently all error messages returned by the GraphQL API are redacted when you’re not an admin. While I understand the security reasons behind this choice, this has an important impact on the user experience when errors relates to validation & permissions.

For example using the `auth_login` mutation, entering a wrong email/password pair, the following payload is returned (HTTP code 200):

```json
{
	"errors": [
		{
			"message": "An unexpected error occurred.",
			"extensions": {
				"code": "INTERNAL_SERVER_ERROR"
			}
		}
	],
	"data": {
		"auth_login": null
	}
}
```

This is caused by this code: https://github.com/directus/directus/blob/0ac08da7ed9d5e4cef52d055be5259fc87ff23ae/api/src/services/graphql/utils/process-error.ts

1. As a developer, I have no way to identify this error as related to the user input and therefor cannot act accordingly
2. As a user, I think that the server has issues instead of knowing that my credentials are wrong

_Originally posted by @LeBenLeBen in https://github.com/directus/directus/discussions/17035_

**Comment by ryntab** [comment]
Agreed, I've been forced to handle auth notices in ambiguous ways which is not super helpful to the user.

**Comment by rijkvanzanten** [comment]
This should rely on the same error handling logic as https://github.com/directus/directus/blob/0ac08da7ed9d5e4cef52d055be5259fc87ff23ae/api/src/middleware/error-handler.ts does
