### ISSUE TITLE
core/extensions missing in build version

### ISSUE THREAD

**Issue by Yanlaz** [directus/directus#1716]
## Version Info
- Directus build

It miss core/extensions in app.min.js

**Comment by WellingGuzman** [comment]
What do you mean @Yanlaz? can you please elaborate what warning/error messages you were receiving and when?

**Comment by Yanlaz** [comment]
I have this javascript error :
`
directus.min.js?bust=gmn53c4jnc72d5j27sn89hvui1:2 Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror
    at makeError (directus.min.js?bust=gmn53c4jnc72d5j27sn89hvui1:2)
    at HTMLScriptElement.onScriptError (directus.min.js?bust=gmn53c4jnc72d5j27sn89hvui1:2)`


I resolve it to add core/extensions from master (based on app/core/extensions.js) in app.min.js before execute task gulp for generate directus.min.js

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/a33017485c135b1290f12fb176e33618750a6dad.

Next build release will include this missing file.
