### ISSUE TITLE
forbidden permission when add multiple file fields in 9.22.x

### ISSUE THREAD

**Issue by leosin** [directus/directus#17167]
### Describe the Bug

I'm not sure if this is a bug, or if I'm not doing it right.

After adding multiple file fields, when entering the edit, it prompts that there is no permission (but it can actually be accessed and edited)

https://user-images.githubusercontent.com/3676670/212529011-b5b57535-a2c1-447d-82fc-9ec90ff53ba5.mp4

And in fact both the endpoint and the image file are accessible。

BTW: I'm currently using 9.22.4

this problem doesn't exist in version 9.20

### To Reproduce

1. Fresh installation
2. Create a new collection
3. Add multi-file fields

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

18.3.0

### What database are you using?

mysql 8.0

### What browser are you using?

chrome/edge

### How are you deploying Directus?

pnpm create directus-project

**Comment by leosin** [comment]
![image](https://user-images.githubusercontent.com/3676670/212529492-c5ce375f-5916-4f21-b3b2-29be9b2c2e28.png)
![image](https://user-images.githubusercontent.com/3676670/212529504-c337d4f0-4f85-4fc9-b24d-e46c3d3e3789.png)

**Comment by licitdev** [comment]
Duplicate of #17108
