### ISSUE TITLE
STORAGE_XXXX_S3_FORCE_PATH_STYLE not working since v9.22.0 ?

### ISSUE THREAD

**Issue by loulou2852** [directus/directus#17170]
### Describe the Bug

With a S3 compatible drive, before 9.22.0 the connection is working, since v9.22.0 and above, it's not connected anymore.

When I reverted to v9.21.2 it's working good.

To confirm that, I checked the log, and it's showing the bucket as a subdomain instead of a path.

### To Reproduce

connect a S3 API adapter working with STORAGE_XXXX_S3_FORCE_PATH_STYLE (for me, it's Contabo Object storage)

Install a fresh instance with the v9.21.2 or bellow.
Try to upload a file -> it's working and you see a preview image

Update to v9.22.0 and superior.
Try to go to media file library.
No preview and error info on upload.

### Errors Shown

[11:10:20.391] ERROR: getaddrinfo ENOTFOUND test-external-bucket2.eu2.contabostorage.com
err: {
"type": "Error",
"message": "getaddrinfo ENOTFOUND test-external-bucket2.eu2.contabostorage.com",
"stack":
   Error: getaddrinfo ENOTFOUND test-external-bucket2.eu2.contabostorage.com
         at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
         "errno": -3008,
       "code": "ENOTFOUND",
       "syscall": "getaddrinfo",
       "hostname": "test-external-bucket2.eu2.contabostorage.com",
       "$metadata": {
         "attempts": 1,
         "totalRetryDelay": 0
 npm ERR! path /directus
 npm ERR! command failed
       }
 npm ERR! signal SIGTERM
 npm ERR! command sh -c -- directus start
 
     }
 npm ERR! A complete log of this run can be found in:
 npm ERR!     /home/node/.npm/_logs/2023-01-15T11_01_17_158Z-debug-0.log

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

Node 18 (Docker)

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Can you try replacing `_S3_FORCE_PATH_STYLE` with `_FORCE_PATH_STYLE` to see whether that works? 

Additional note: This config should work on `9.22.4` only (not 9.22.1 to 9.22.3) as it was recently patched by #17081.

**Comment by loulou2852** [comment]
Yes it's working Thanks
