### ISSUE TITLE
'Save as Copy' broken?

### ISSUE THREAD

**Issue by conorhub** [directus/directus#17189]
### Describe the Bug

I want to make several items that are similar, with small differences.
Ideally, I would love a more prominent 'duplicate item' option for all users in the UI but I've found a slightly hidden 'save as copy' item that's revealed when editing an existing items fields.
It doesn't appear to actually duplicate for me and, on clicking it, clears the UI form of all field elements, leaving me with a confirm/tick button and nothing to modify.
No duplicate item / copy is created.

### To Reproduce

Choose an existing item in the Directus app UI.
Modify one of the fields and choose 'save as copy' from the context meny beside the tick.
All field elements disappear.
Confirm changes on blank form.
Return to Items list and see that the original item has been modified instead of creating a duplicate

### Errors Shown

Console produces:

`400 XHR Bad Request`
`TypeError: Ot.field is null`
`Error: Promised response from onMessage listener went out of scope`

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

16.18.1

### What database are you using?

MySQL 8

### What browser are you using?

Firefox

### How are you deploying Directus?

Docker on remote server

**Comment by azrikahar** [comment]
Would you mind trying this on the latest version `9.22.4`? This sounds similar to #16326, and there was a fix #16966 that was included in `9.22.2`. Will re-open if it turns out to still be an existing bug on `9.22.4` 👍

**Comment by conorhub** [comment]
Updated to `9.22.4` (pulling the latest image and confirming this version is running after starting container) and unfortunately the bug is still present. I replicated it as outlined in the original post.

**Comment by conorhub** [comment]
> Updated to `9.22.4` (pulling the latest image and confirming this version is running after starting container) and unfortunately the bug is still present. I replicated it as outlined in the original post.

Just bumping this again, I don't think it was noticed.

**Comment by paescuj** [comment]
@conorhub I cannot reproduce this on 9.22.4. Can you please share more information about your collection / field setup?

**Comment by ncarkaci** [comment]
The codes in Docker Hub are legacy codes from 9.22.3. The problem may be due to this. If it is updated to version 9.22.4 in Dockerhub, the problem will be solved.

**Comment by paescuj** [comment]
> @paescuj The codes in Docker Hub are legacy codes from 9.22.3. The problem may be due to this. If it is updated to version 9.22.4 in Dockerhub, the problem will be solved.

You're probably referring to this https://github.com/directus/directus/issues/17115 (latest version is on DockerHub, but it still shows 9.22.3 under settings)

**Comment by conorhub** [comment]
> @conorhub I cannot reproduce this on 9.22.4. Can you please share more information about your collection / field setup?

Sure. I don't believe I've anything noteworthy in any of the field configurations, other than one field, **collection_editor** a m2m with the **directus_users** collection.

There's also required string fields, such as **collection_title**, and a few standards like, status, sort, user_created, user_updated, date_updated, date_created.

I can't think of anything unusual or of relevance in the collection configuration itself.

> The codes in Docker Hub are legacy codes from 9.22.3. The problem may be due to this. If it is updated to version 9.22.4 in Dockerhub, the problem will be solved.

I'm not sure if this contradicts, but if I check my project settings info I get:

Directus Version: 9.22.4
Node Version: 18.13.0

When pulling from latest docker image 3 weeks ago.

**Comment by conorhub** [comment]
This issue is fixed for me in the version I pulled today (pulling @latest docker version, which I believe is 9.23). Thanks for the updates.

Relations are not being transferred to the copy, but a copy basic string and integer fields are being cloned into a new item.

**Comment by paescuj** [comment]
> This issue is fixed for me in the version I pulled today (pulling @latest docker version, which I believe is 9.23). Thanks for the updates.
> 
> Relations are not being transferred to the copy, but a copy basic string and integer fields are being cloned into a new item.

Thanks for the update! I'm glad it's working for you now 👍
