### ISSUE TITLE
Composite Primary Keys Cannot Be Detected

### ISSUE THREAD

**Issue by ozum** [directus/directus#17185]
### Describe the Bug

Composite primary keys contain more than one column. If a table has a composite primary key, directus cannot detect the primary key.

### To Reproduce

* For PostgreSQL, create a table with a primary key consisting of more than one column as shown below.

```sql
CREATE TABLE "TabProfile"
(
  "profileId" UUID NOT NULL,
  "tabId" UUID NOT NULL
);

ALTER TABLE "TabProfile" ADD CONSTRAINT "TabProfileId" PRIMARY KEY ("tabId","profileId");
```
* `npm init directus-project directus`
* `cd directus`
* `npx directus start`

### Errors Shown

On console:

`WARN: Collection "TabProfile" doesn't have a primary key column and will be ignored`

### What version of Directus are you using?

9.22.3

### What version of Node.js are you using?

19.4.0

### What database are you using?

PostgreSQL 15.1

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally with npm using `npm init directus-project directus`

**Comment by br41nslug** [comment]
Composite primary keys are not currently supported. Please refer to and upvote the feature request https://github.com/directus/directus/discussions/12137 😄

**Comment by ozum** [comment]
Hi, @br41nslug. I voted as suggested.

I kindly suggest this issue stays open as a bug because composite keys are a natural part of SQL standard. In its current state, a database with a composite key cannot be used with directus and it's a blocking issue for those databases.

**Comment by cube-dan** [comment]
@u12206050 has a [elegant solution mapped out over here](https://github.com/directus/directus/discussions/12137#discussioncomment-3042244 ) and I've solved this issue using a [custom hook implementation](https://github.com/directus/directus/discussions/12137#discussioncomment-4806346).
