### ISSUE TITLE
Empty table listing when adding from existing database

### ISSUE THREAD

**Issue by rgvy** [directus/directus#1718]
## Version Info
  - Directus version and branch: 6.4.0
  - PHP version: 7.1.1
  - MySQL version: 5.6.35
  - Web server: Apache (MAMP)
  - OS name and version: macOS 10.12.6 

## Expected Behavior
A listing showing all my rows including ones added via Directus UI

## Actual Behavior
"Nothing to see here..."

## Steps to Reproduce
 1. Create database with table below and seed with data
 2. Install directus
 3. Enable management of test tables
 4. View test tables
 5. Observe empty
 6. Add an item
 7. Observe empty

## Schema Dump, Logs, or Screenshots
```
CREATE TABLE `users2` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(249) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `username` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` tinyint(2) unsigned NOT NULL DEFAULT '0',
  `verified` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `registered` int(10) unsigned NOT NULL,
  `last_login` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `users2` (`id`, `email`, `password`, `username`, `status`, `verified`, `registered`, `last_login`)
VALUES
	(1, 'test@example.com', '123', 'user', 0, 0, 0, NULL);
```

**Comment by rgvy** [comment]
I'll note that I was able to use Directus UI to add a table and rows to that table without any problem.

**Comment by rgvy** [comment]
Furthermore, the only log entries are:
```
ERROR - 2017-08-01T15:49:49-04:00 - ErrorException: Undefined index: id in /Users/asher/Documents/Repo-SOCMS/directus-6.4.0/index.php:603
Stack trace:
#0 /directus-6.4.0/index.php(603): Directus\Exception\ExceptionHandler->handleError(8, 'Undefined index...', '...', 603, Array)
#1 {main}
ERROR - 2017-08-01T15:49:49-04:00 - ErrorException: Undefined index: directus_activity in /directus-6.4.0/api/core/Directus/Database/TableSchema.php:783
Stack trace:
#0 /directus-6.4.0/api/core/Directus/Database/TableSchema.php(783): Directus\Exception\ExceptionHandler->handleError(8, 'Undefined index...', '...', 783, Array)
#1 /directus-6.4.0/index.php(603): Directus\Database\TableSchema::getAllSchemas(NULL, '551b56ad6fa8e29...')
#2 {main}
```
And they only occur when launching Directus UI initially

**Comment by WellingGuzman** [comment]
Hey @rgvy Did you gave the user group permission to read data from that table?

**Comment by rgvy** [comment]
Thanks for the suggestion. I was the administrator, so I assumed it was unnecessary. I'll try that tomorrow and report back.

**Comment by WellingGuzman** [comment]
Great @rgvy, please let us know.

Note: By default only the tables you create from Directus are automatically managed by directus (admin has permission to it), if you create a table via other way, it won't be visible unless you go to `Settings > Tables` and click "manage" which give the admin group permission to manage and view the table data

**Comment by rgvy** [comment]
Hmmm, I tried that actually. What I have yet to try is tinkering with ``` settings > group permissions```

At first I thought that my issue was caused by foreign keys to/from tables I hadn't chosen to manage. But then I was able to create the bug by duplicating my users table...

**Comment by WellingGuzman** [comment]
I didn't quite get what you were saying... did you perform what I recommend and it didn't work? As Admin you can see any table that you want to manage within directus.

Anyway I will try to reproduce this myself with your steps, because I'm thinking this could be something else.

**Comment by WellingGuzman** [comment]
hey @rgvy I see you that mentioned it about managing the table, I'm sorry I just didn't notice what it meant.

**Comment by rgvy** [comment]
Sorry if I wasn't clear. I have more information.

Yes, I have already tried it as you recommend: by clicking "manage" in ```settings > tables```. The table appears in the left sidebar, but there is no data shown while my database has hundreds of rows. However, I CAN add new rows to the managed table, and they do show up in the database. But the table list view shows none.

Furthermore, I tried adding a different table. That table had no primary key. After using Directus to add a primary key, the table data showed as expected. Perhaps this is related? I should note that the non-functioning tables already have primary keys in columns named 'id'

**Comment by WellingGuzman** [comment]
Hey @rgvy, Thanks for all the information, I finally found what was causing the trouble, Directus is treating the `status` column as if it were a Status Interface column, and because the value is 0, and the default value for deleted is 0, the records are hidden.

We are discussing this behavior, and will come up with a solution soon.

**Comment by rgvy** [comment]
I see. Funny, it was only the tables with a ```status``` column that I tried using while evaluating Directus.

May I ask, if I simply change the name of this column, will that fix everything? Besides ```id``` are there any other "magic names" to be aware of?

Thanks!

**Comment by benhaynes** [comment]
Today USED to be magic, along with `sort` for drag and drop, and `id` for the primary key. NOW (in 6.4) all these columns are dictated by their chosen interface. One of the hardcoded values must have been overlooked. 

We're on it! 😉

**Comment by WellingGuzman** [comment]
Hey @rgvy this commit (https://github.com/directus/directus/commit/c166d3592b2d1694f00c16f7f3c856c86224bde8) should fix the issue not showing up any data into the `users2` table.

Please let us know if it did the job.

**Comment by rgvy** [comment]
I can't confirm if that commit fixed, since I don't know how to use the dev branch. I'm just using the 6.4.0 distro

I can, however, confirm that avoiding or renaming ```status``` columns totally fixes my issues.

Thanks for the response to this bug! I'm very much looking forward to using Directus!

**Comment by WellingGuzman** [comment]
@rgvy awesome, I can confirm with works on my end. I will re-open if this still happen in some other way.
