### ISSUE TITLE
Change language name for Traditional Chinese from "Taiwanese Mandarin (Taiwan)" to "Chinese (Traditional)"

### ISSUE THREAD

**Issue by sekhuat** [directus/directus#17198]
### Describe the Bug

I would like to propose changing the Traditional Chinese language name from "Taiwanese Mandarin (Taiwan)" to "Chinese (Traditional)". The reason is "Chinese (Simplify)" and "Chinese (Traditional)" is a de facto standards for naming the Chinese language. Because of the language name Directus currently used, I thought that Directus doesn't support Traditional Chinese. After scrolling the entire language list one by one then I saw "Taiwanese Mandarin (Taiwan)".

I am a Singaporean, so China & Taiwan issue is not a matter to me and I also hope that Directus also be neutral on the naming. Please follow the de facto standard for naming the Chinese language so that it is easier for all users. Thank you.

### To Reproduce

NA

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

18.12.1

### What database are you using?

MySQL

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
I believe this is a very outdated locale naming that was migrated way back in #3352. Seeing that Crowdin itself maps `zh-TW` to `Chinese Traditional` in their site: https://developer.crowdin.com/language-codes/, it'll only make sense to use the same naming 👍
