### ISSUE TITLE
Flows are not sortable

### ISSUE THREAD

**Issue by LevinGermann** [directus/directus#17195]
### Describe the Bug

This was working for sure in 9.20.4.

When looking at the flows, they have a seemingly random order now.
it's not possible to sort them, clicking on the sort icon next to the `name` or `status` doesn't do anything.

https://user-images.githubusercontent.com/9347206/212712140-f276e717-c5fb-40eb-add3-0c25b41ab6f5.mov

### To Reproduce

1. Create some flows with different names.
2. They are unsorted by default and can't be sorted

### Errors Shown

None

### What version of Directus are you using?

9.22.3

### What version of Node.js are you using?

18

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Can confirm this, seems to be a side effect of #16897 (included in `9.22.2`).

**Comment by azrikahar** [comment]
Linear: [ENG-510](https://linear.app/directus/issue/ENG-510/flows-are-not-sortable)
