### ISSUE TITLE
Sort columns in tables

### ISSUE THREAD

**Issue by dsivokhin** [directus/directus#1721]
## Version Info
  - Directus version and branch: 6.4 develop
  - PHP version: 7.0
  - MySQL version: 5.7
  - Web server: nginx
  - OS name and version: Ubuntu 16.04

## Actual Behavior

Error when sort columns

`Server Error
This query failed: UPDATE `directus_columns` SET `null` = '0' WHERE `table_name` = 'products' AND `column_name` = 'id'`

## Schema Dump, Logs, or Screenshots
![3](https://user-images.githubusercontent.com/4669992/28958783-5f078e62-7900-11e7-9750-126dca6933fc.PNG)

**Comment by benhaynes** [comment]
Thank you @dsivokhin for reporting this! We've resolved this issue in the commit above. We'll be pushing a patch release this evening to `build`... in the meantime you can pull that commit to fix the problem.
