### ISSUE TITLE
Settings > Users Interface

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1722]
**1. REMOVE "X"** – We should remove this "X" because you can't remove a user from a group (then can only be shifted to a NEW group) otherwise they would not have a group assigned.

**2. Add these columns:**

* Avatar
* Name
* Last Login
* Last IP

**3. Make each clickable to open the User Modal**

**Comment by benhaynes** [comment]
Just for reference – the new one is not 100% (shouldn't have "X", but I thought this would help):

![screen shot 2017-08-05 at 12 44 10 pm](https://user-images.githubusercontent.com/522079/28997200-d6d0e510-79dc-11e7-97d6-31e42bdc02a5.png)

![screen shot 2017-08-05 at 12 44 19 pm](https://user-images.githubusercontent.com/522079/28997199-d0e8f94e-79dc-11e7-9e25-16098255e7cd.png)

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/7d9f19fece4bcb3165a9a90035ae6a7d603877c1
