### ISSUE TITLE
directus 6.4.0 migration from older version. Problem on eye button

### ISSUE THREAD

**Issue by NextrekNet** [directus/directus#1724]
## Expected Behavior
able to edit field after reactivate it.

## Actual Behavior
unable to edit field after clicking two times (not visible / visible) on eye button. if we perform and reload of main page it works well

## Step to reproduce
1. edit table and edit column clicking on eye button to not visible colum
2. edit again column clicking on eye button to show visible column
3. click on field name to edit it.

**Comment by WellingGuzman** [comment]
Hey @NextrekNet, are you trying to say that clicking the icon couple of times stop working?

**Comment by benhaynes** [comment]
He means: click the visibility "eye" icon two times, then try to edit the interface (open the modal) and he gets an error. He has a video on Slack that he can share.

**Comment by WellingGuzman** [comment]
I understand clearly, thanks @benhaynes. it helps to show errors screenshot.

Working on it.

**Comment by WellingGuzman** [comment]
Hey @NextrekNet, I have fixed this issue on https://github.com/directus/directus/commit/afe76be8ccfac0f10759a0da2ceba7cefea24922

Please confirm, otherwise I will re-open.
