### ISSUE TITLE
M2M relation - Error message [FORBIDDEN] You don't have permission to access this.

### ISSUE THREAD

**Issue by frejandreassen** [directus/directus#17251]
### Describe the Bug

As admin user.

- Set up two collections with Generated UUID as id. 
- Set up M2M relation between collections using Template Wizard from first collection.  
- Create item in junction collection.

Click newly created item.
Receive Error message: [FORBIDDEN] You don't have permission to access this.
But, not access restrictions.

## Expected behaivour
No error message.

### To Reproduce

To reproduce I followed the following steps

`npx directus init`
I chose postgres as db, and started 
`npx directus start`

Navigate to localhost:8055 and log in as first admin user
- Create collection Recipies, with id Generated UUID. 
- Create field name on collection Recipies

- Create collection Ingredients, with id Generated UUID
- Create filed name on collection Ingredients

- Create field on collection Recipies using Template Wizard, M2M. field name ingredients and 

- Create item with name "Carrot" in collection Ingredients
- Create item with name "Carrot soup" in collection Recipies, and select Carrot in field Ingredients

- Click field Ingredients (Carrot) on item detail for Carrot soup
![Skärmbild 2023-01-20 100531](https://user-images.githubusercontent.com/58067540/213657302-e7dbdb13-920f-4524-b07a-651d36390793.png)

Receive error
![Skärmbild 2023-01-20 100605](https://user-images.githubusercontent.com/58067540/213657317-8e970461-e589-43c9-b663-43abe18045f3.png)

Looking at the request made by the browser. 

> 
> Request URL: http://localhost:8055/items/recipies_ingredients/72a5683c-d531-476d-a249-659361798c39
> Request Method: GET
> Status Code: 403 Forbidden
> Remote Address: 127.0.0.1:8055
> Referrer Policy: strict-origin-when-cross-origin

There is no recipies_ingredients with UUID as id. The collection id is auto incremented integer.

[snapshot.yaml.txt](https://github.com/directus/directus/files/10464714/snapshot.yaml.txt)

### Errors Shown

{
  "errors": [
    {
      "message": "You don't have permission to access this.",
      "extensions": {
        "code": "FORBIDDEN"
      }
    }
  ]
}

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

16.15.1

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
Should be the same issue as #17211 #17108 👍
