### ISSUE TITLE
Crytical error in 6.4.1

### ISSUE THREAD

**Issue by riartem** [directus/directus#1726]
## Version Info
  - Directus version and branch: 6.4.1
  - PHP version: 5.6.28
  - MySQL version: 5.6.34
  - Web server: Apache

After updating from 6.4.0 I have infinite loading and console errors:
![image](https://user-images.githubusercontent.com/987517/29113538-f0e2f23e-7cf9-11e7-98bd-8d7bb72c75a3.png)

![image](https://user-images.githubusercontent.com/987517/29113513-e34a62b0-7cf9-11e7-9c45-1d903d958088.png)

Update: 
On fresh install it's not working too if directus installed in sub directory, like: /htdocs/directus/
It's a serious bug. Looks like /customs/interfaces/rating/component.js is hard-coded.

**Comment by riartem** [comment]
Update: 
Not working if directus installed in sub directory, like: /htdocs/directus/
It's a serious bug. Looks like /customs/interfaces/rating/component.js is hard-coded.

**Comment by WellingGuzman** [comment]
Hey @riartem, thanks for reporting this, meanwhile you can rename `customs/interfaces/rating` to `customs/interfaces/_rating` to stop the interface from loading.

I will take a look asap

**Comment by WellingGuzman** [comment]
Can you also try to clear the cache from the browser just in case is a browser cache issue?

**Comment by riartem** [comment]
@WellingGuzman of course, I am cleaned browser cache.
Case description:
File exists here: /**directus**/customs/interfaces/rating/component.js
But system is ignoring that it is in a subdirectory and looking for that file in path /customs/interfaces/rating/component.js

**Comment by WellingGuzman** [comment]
Thanks @riartem! I will be working on it asap, one more question, where did you download the directus files from? zip, tar, git, GitHub zip?

**Comment by vkrementzoff** [comment]
I wanted to try 6.4.1 with a clean install ; I cloned the repo, made a composer install and created a clean database, I have an error that stops installation.

Here is the detail of the errors:

Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'directus.directus_tables' doesn't exist in /home/directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:239 Stack trace: #0 /home/directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute() #1 /home/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(239): Zend\Db\Adapter\Driver\Pdo\Statement->execute() #2 /home/directus/api/core/Directus/Database/TableGateway/BaseTableGateway.php(708): Zend\Db\TableGateway\AbstractTableGateway->executeSelect(Object(Zend\Db\Sql\Select)) #3 /home/directus/api/core/Directus/Database/TableGateway/BaseTableGateway.php(689): Directus\Database\TableGateway\BaseTableGateway->executeSelect(Object(Zend\Db\Sql\Select), Array) #4 /home/directus/api/core/Directus/Database/TableGateway/BaseTableGateway.php(673): Directus\Database\TableGateway\BaseTableGateway->selectWith(Object(Zend\Db\Sql\Select), Array) #5 /home/di in /home/directus/api/core/Directus/Database/TableGateway/BaseTableGateway.php on line 730

![composerinstall](https://user-images.githubusercontent.com/26149225/29176738-b8cc270a-7dba-11e7-95f6-e3afdb6c66cd.png)
![directus-error](https://user-images.githubusercontent.com/26149225/29176739-b8cc6922-7dba-11e7-81e3-17bc98c5f957.png)

**Comment by WellingGuzman** [comment]
@vkrementzoff what MySQL version are you using? and what sql mode do you have enabled?

Did composer install nothing?

**Comment by WellingGuzman** [comment]
Also @riartem, I reproduced this issue and I've been working on it. we have an alias that map "customs/interfaces" to "interfaces" which don't place nice on subdirectories. I'm hopping to get this done soon. Thanks for the report!

**Comment by vkrementzoff** [comment]
@WellingGuzman 
Hello Welling. Thank you for replying so quickly, as usual :)

I use 10.1.25-MariaDB. Works fine with Directus 6.3.8. Composer seems to have installed everything from the beginning.

What do you mean by sql mode ?

**Comment by WellingGuzman** [comment]
@vkrementzoff the mode your database is running on.

One way you can get the sql mode is by running the query below:

```sql
SELECT @@GLOBAL.sql_mode;
SELECT @@SESSION.sql_mode;
```

Or you can check your database config file. Probably it can be found in `/etc/mysql/my.cnf`.

**Comment by vkrementzoff** [comment]
@WellingGuzman 

I found the problem : for some reasons, ownership of mysql (mariaDb) files was broken, so mariaDb couldn't write in its own files. Now it works.

Have a nice day!

**Comment by WellingGuzman** [comment]
Hey @vkrementzoff, can you please explain this a bit more so someone else having this issue could know how to fix it?

**Comment by vkrementzoff** [comment]
Sure @WellingGuzman ;

MariaDb or MySQL (they work the same way) is made of files containing data (the actual database) ; usually it's located in the /var/lib/mysql directory, sometimes (like in our case) it can be located elsewhere . 

To find where it's located, you can have a look at the /etc/mysql/my.cnf file, the _datadir_ variable.

For some reason, the owner of the /var/lib/mysql directory wasn't mysql, so mysql couldn't write any data. That's why new tables couldn't be created. I tested just with phpMyAdmin, table creations were refused as well.

Then, making a chown -r mysql:mysql /var/lib/mysql (or any other directory where data is actually located) solved the problem.

Directus wasn't the source of the problem in my case.

**Comment by WellingGuzman** [comment]
Hey @riartem, the missing interface component was fixed by https://github.com/directus/directus/commit/b9aabbf807fdc547070ae6ada3efc5bb21831e7b

I've rebuilt the build zip/tar. Please confirm if this has been fixed or not.
