### ISSUE TITLE
"Count" field in the UI doesn't work

### ISSUE THREAD

**Issue by TyrionFront** [directus/directus#17273]
### Describe the Bug

For some reason the "Count" field - really useful one - is not available any more in Directus UI after the latest update.

<img width="849" alt="Screenshot 2023-01-23 at 09 51 39" src="https://user-images.githubusercontent.com/18406903/213989919-c240edf4-75a0-4125-8624-a2b7097105a6.png">
<img width="855" alt="Screenshot 2023-01-23 at 09 52 15" src="https://user-images.githubusercontent.com/18406903/213989929-f8fe7f1e-a9aa-4c69-b98e-2c962af1c256.png">

### To Reproduce

Just try to work with any one-to-many or many-to-many relation

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

v18.13.0

### What database are you using?

PostgreSQL 14.5 on aarch64-apple-darwin20.6.0

### What browser are you using?

Brave

### How are you deploying Directus?

Docker

**Comment by paescuj** [comment]
Thanks for reporting this issue!
This has already been fixed via #17182 which will be available in the next release.

**Comment by TyrionFront** [comment]
> Thanks for reporting this issue! This has already been fixed via #17182 which will be available in the next release.

Ok, txs.
And when exactly will it happen?

**Comment by paescuj** [comment]
We cannot give an exact date, but I expect this to happen soon!
