### ISSUE TITLE
Errors on createFile 

### ISSUE THREAD

**Issue by dieguezz** [directus/directus#1727]
## Version Info
  - Directus version and branch: build
  - PHP version: 5.6
  - MySQL version: 5.7.18
  - Web server: (Ex. Apache, nginx or IIS?) Apache 2.4.27
  - OS name and version: CentOs 2.62.32

## Expected Behavior
When uploading a file should not return 500 error

## Actual Behavior
Returns 500

## Steps to Reproduce
This his happening using the js-sdk and using just axios.
Request:
![captura de pantalla 2017-08-10 a las 15 55 16](https://user-images.githubusercontent.com/1161455/29179285-4ae1dee4-7df4-11e7-99ca-231d6beb508c.png)
Request without file type
![captura de pantalla 2017-08-10 a las 15 54 26](https://user-images.githubusercontent.com/1161455/29179306-5fdf67d0-7df4-11e7-8665-4c5f5f9ff96c.png)
Error in browser:
![captura de pantalla 2017-08-10 a las 15 54 44](https://user-images.githubusercontent.com/1161455/29179333-6d740ffe-7df4-11e7-9f7d-2fa120e40e4e.png)

// api/logs..
<img width="881" alt="captura de pantalla 2017-08-10 a las 16 24 29" src="https://user-images.githubusercontent.com/1161455/29179264-382a2e46-7df4-11e7-9f4c-d6c9ab367775.png">

**Comment by WellingGuzman** [comment]
Hello @dieguezz,

This is a both API and Docs issue related, you must provide the `name` and the `type` (mime type) of the upload.

for example `name=image.jpg` and `type=image/jpeg` (mime type).

The upload should work with those two required information. I will make sure this is clear in the documentation.

Thanks for reporting this.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/6cfabd4c0810163df8b8da022222089347d7c1f2
