### ISSUE TITLE
Directus Cloud Assets returns an error 403

### ISSUE THREAD

**Issue by jhouedanou** [directus/directus#17281]
### Describe the Bug

Hi, i have the endpoint below 
https://scu698sm.directus.app/items/Clients

when i try to access the image field from a browser

https://scu698sm.directus.app/items/Clients/assets/f11ab8cc-aa3e-4d06-a48a-962aad7f0ad8

i get an 403 error.
Files permissions have been set correctly 
 
![Capture d’écran 2023-01-24 120023](https://user-images.githubusercontent.com/1837389/214286298-e9c8ece4-11da-422b-bec7-1d75d82cffab.jpg)

### To Reproduce

1. Go to 
https://scu698sm.directus.app/items/Clients/assets/f11ab8cc-aa3e-4d06-a48a-962aad7f0ad8

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

16.18.1

### What database are you using?

the one with directus cloud

### What browser are you using?

Chrome

### How are you deploying Directus?

Directus cloud

**Comment by br41nslug** [comment]
The url for assets is `https://scu698sm.directus.app/assets/f11ab8cc-aa3e-4d06-a48a-962aad7f0ad8`.
Are you authenticating the request or are those the Public permissions?

Closing this issue for now as i don't think this is an issue with the core codebase. Happy to keep discussing tho and re-open if i turn out to be wrong 😄
