### ISSUE TITLE
Error creating new table

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1728]
Creating a new table within Directus:

```
Error: Uncaught TypeError: model.setActive is not a function
File: http://local.directus.com/app/core/bookmarks.js?bust=2070d78c10d2fabc852bbb99aac683046adadf1a
Line:79
```

It DOES create the table – but throws the error.

**Comment by WellingGuzman** [comment]
Did you clear the cache? this should have been fixed by https://github.com/directus/directus/commit/88adb7abfbc7fe2a7e6e491869f27ff6b809c097

**Comment by benhaynes** [comment]
Weird – I had cleared my cache many times, but now it's gone. Must have been _sneaky_ cache!

**Comment by rijkvanzanten** [comment]
Gotta love those sneaky caches

![sneaky](https://media.giphy.com/media/V1NxC1YoNEHBe/giphy.gif)
