### ISSUE TITLE
Navigate back after "no changes"

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1729]
When saving an item, sometimes it says there were "no changes" (see below) – but then it keeps you on the same page. Within `Settings>Tables&Inputs>Table` when you change interface options and then save the page it tells you this because interface options are saved immediately... but it's annoying because it doesn't take you back to the parent page.

*When you get this message we should still navigate the user back to the intended listing page*

```
Warning
Nothing changed, nothing saved
```

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/effdb8666e1cc3fdee74e20acd7bb0de5424fb04

**Comment by WellingGuzman** [comment]
Notice: these three view will be merge/shared code soon.
