### ISSUE TITLE
Directus not Updating to latest version

### ISSUE THREAD

**Issue by orlsanchez** [directus/directus#17306]
### Describe the Bug

I followed the update steps for Directus, to update from version 9.22.3 to 9.22.4.
I'm running Directus locally.

Steps to update:
(in Directus project folder)
npm update
npx directus database migrate:latest

Get the following:
up to date, audited 959 packages in 13s

104 packages are looking for funding
  run `npm fund` for details

11 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

When I start Directus and go to the project URL, it still shows version 9.22.3

### To Reproduce

Steps to update

### What version of Directus are you using?

9.22.3

### What version of Node.js are you using?

16.14.2

### What database are you using?

Postgres 

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment]
Provided the version isn't pinned to `9.22.3` in your `package.json` file, I believe this is the same issue as #17115, where the Settings module page shows it is `9.22.3` but it is actually the `9.22.4` build.

You should be able to run `npm list directus` in your Directus project folder as a confirmation whether you are currently already on `9.22.4` (even if the Settings page is showing `9.22.3`). Proceeding to close this for now 👍
