### ISSUE TITLE
Interface Options opening wrong modal

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1730]
After creating several new columns/interfaces – clicking on the most recent column's interface options opens a modal with the incorrect options.

Clicking on the URL options (Notice the interfaces used by URL and Publish Date below):
![screen shot 2017-08-10 at 12 58 25 pm](https://user-images.githubusercontent.com/522079/29182298-5716f65e-7dcc-11e7-9bbb-4b40f1a56957.png)

Opens this modal:
![screen shot 2017-08-10 at 12 58 16 pm](https://user-images.githubusercontent.com/522079/29182308-5e40adee-7dcc-11e7-8e64-ddaf29154e12.png)

This is showing the column title "URL" but the options for Publish Date. This happens every time you click on the options – but once you refresh the page it stops happening.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/ab4c9551e665e7700c10fca14bb4c187efa9c4a5
