### ISSUE TITLE
Don't show right sidebar for New Items

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1731]
The INFO icon in the header is disabled, but the empty sidebar still shows up when creating new items. It should *not* be visible at any screen width.

![screen shot 2017-08-10 at 2 22 38 pm](https://user-images.githubusercontent.com/522079/29185507-65f51d6c-7dd7-11e7-813e-d8348470150c.png)

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/9041a44f1d810be2cfc5c35f04f969896b2fc628

**Comment by benhaynes** [comment]
Is it possible to not include the sidebar HTML for new items? Or to find a way to avoid the flicker?

Flicker: When you load the page you see the sidebar on the right for a moment as it slides off the page. This is distracting and makes it seem like there's something over there you should be able to use/see.

**Comment by WellingGuzman** [comment]
Right pane flickering stopped by https://github.com/directus/directus/commit/dbc1d8c42b6a561cbf3c6c46396586e2d975eda4
