### ISSUE TITLE
Confusing how to delete project with project name

### ISSUE THREAD

**Issue by mcqua007** [directus/directus#17315]
### Describe the Bug

This might not be a bug really, but I wanted to point out it took a minute to find the actual name of the project in  order to delete it. When trying to delete the project from Directus cloud  Directus says to input the project name in the text box below to delete said project. Looking right above it shows a text field labeled project name (i.e. Project Name: Test Project).

One would think we need to put this project name into the text input in order to delete rather than putting the project ID into the text input. Even though it has the placeholder of the project name/id. I think it would be helpful to have this name/id somewhere else on the page possibly labeled as project id. Then change the text to something like: "enter the project id in the text field below to delete the project". Sorry I know this is a small thing, but I thought it was good feedback in making it easier for a user to delete project.

<img width="1097" alt="Screenshot 2023-01-26 at 12 18 41 PM" src="https://user-images.githubusercontent.com/17321059/214943098-1b978cef-9d48-4a02-badf-14abf0815ee9.png">

### To Reproduce

Go to Directus cloud and edit a project. Then try to delete said project.

### Errors Shown

Hard to find the correct project name to delete the project. I kept putting in the project name above but Directus wanted the project Id which I found in the URL.

### What version of Directus are you using?

n/a

### What version of Node.js are you using?

n/a

### What database are you using?

n/a

### What browser are you using?

Chrome

### How are you deploying Directus?

Cloud

**Comment by rijkvanzanten** [comment]
Heya! Thanks for the heads up. This seems like a cloud specific issue so I'll pass this along to our cloud team as they will be more suited to look into this matter 👍🏻

For future inquiries or issues specific to Directus Cloud projects, please reach out through [the Live Chat in our Cloud Dashboard](https://directus.cloud/) as that's the best channel to get help with your Cloud projects 🙂
