### ISSUE TITLE
Order for new columns

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1732]
When creating new columns within a table, they seem to order properly at first – but the column order is saved in `directus_columns.sort` as `9999`. This means that the order is different when you come back because they are all set to `9999`.

What we should do: as you add a column, it should save `directus_columns.sort` as the column count... so that it is ordered at the end.

Example:
Save first column: sort = 1
Save second column: sort = 2
Save third column: sort = 3
etc...

Or we could save it as MAX + 1:
So if the highest sort is `42` then we save as `43`

**Comment by WellingGuzman** [comment]
Hey @benhaynes, I implement in this commit https://github.com/directus/directus/commit/f55d50d22efe3cbd1bc0166bf315074fec58fcbd incrementing by one the last column sort value to the new one.

**Comment by benhaynes** [comment]
Almost! Right now it increments from the max value in the whole `directus_columns` table... but it should _only_ find the max from THIS table.

Example:
**Projects**
id = `0`
title = `1`
image = `2`
date = `3`

**Articles**
id = `0`
title = `9999`
url = `9999`

If I add a new column to Projects then it gets the sort order: `10000`, but it _should_ be `4`

**Comment by WellingGuzman** [comment]
That's because the table last column already have `9999`, that values will reset after you reset by sorting the columns.

Or Am I missing the problem?

**Comment by benhaynes** [comment]
Hmm – I guess it will always "work" hahah. No one looks at the sort values so I guess this is fine.

**Comment by WellingGuzman** [comment]
I set the new columns value set to `0, 1, 2` (https://github.com/directus/directus/commit/8f549e4c563b457fae17e2fc858646f27635ab70)
