### ISSUE TITLE
The following fields have invalid values: ID: Value is required 

### ISSUE THREAD

**Issue by s-chillo** [directus/directus#17329]
### Describe the Bug

I have a data model that has id field which is bigint it was working adding new data 
On one data model when i save data il always have this error

`The following fields have invalid values: ID: Value is required`

### To Reproduce

Install directus 9.21.0 with docker
Use postgis/postgis:13-master

### Errors Shown

The following fields have invalid values: ID: Value is required 

### What version of Directus are you using?

Docker 9.21.0

### What version of Node.js are you using?

16

### What database are you using?

postgis:13-master

### What browser are you using?

chrome

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
There's currently not enough information present to be able to reproduce this. Can you elaborate on your reproduction steps? We'll reopen once more information becomes available.
