### ISSUE TITLE
"contains" does not work on custom permisson

### ISSUE THREAD

**Issue by xdoo** [directus/directus#17338]
### Describe the Bug

I want to create a directus application where users should only see the entities of their own organisation. For that I wanted to create under Roles & Permissions a custom permission like "Users Contains $CURRENT_USER". This doesn't work and I'm not able to create a raw filter rule at all. 

Is this a bug, or a limitation of the on premise version?

### To Reproduce

- start the docker compose file (see https://docs.directus.io/self-hosted/docker-guide.html)
- log into directus
- switch to the settings panel / Data Model and create a collection "Foos"
- create inside "Foos" a O2M relationship to "directus_users", name the property "Users"
- switch to Roles & Permissions
- you can use the public role or create a new one
- click on the red sign of Foos - update (or any other CRUD action) and select "use custom"
- be sure that you're on "Item Permission"
- click on "add filter" and try to select "Users". 
- I would assume, that a click on Users (not the little arrow on the right) would create something like "Users Contains --", but the click opens the attributes of "directus_users"

### Errors Shown

no errors

### What version of Directus are you using?

9.22.3

### What version of Node.js are you using?

see directus/directus:latest

### What database are you using?

postgis/postgis:13-master

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by br41nslug** [comment]
`contains` is a string comparison and will not work in this case. The filter i think you are looking for is `Users -> ID equals $CURRENT_USER` to only see the "Foos" which are related to the current user ID.
