### ISSUE TITLE
Single File Relationship

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1733]
When you setup a new Single File interface it auto-generates the relationship. However it doesn't include the `directus_files.id` column in the relationship setup – and it's there is no option to select it. Maybe this is because `directus_files.id` isn't set up as a PK interface in the static schema?

![screen shot 2017-08-10 at 3 55 13 pm](https://user-images.githubusercontent.com/522079/29189448-907fae82-7de4-11e7-8479-440ab83cebd6.png)

**Comment by WellingGuzman** [comment]
This is not happening in my end, also we change the fixed information? I hate to keep asking this, but I know it always our issue, cache. did you clear the cache?

**Comment by WellingGuzman** [comment]
Primary column information was set to the fixed schema objects.

Closed by https://github.com/directus/directus/commit/bd41318182f33977a2980d866f6aa878cc9da22a
