### ISSUE TITLE
WYSIWYG Full not saving changes

### ISSUE THREAD

**Issue by textoo** [directus/directus#1734]
## Version Info
  - Directus version and branch: 6.4.1 master
  - PHP version: 7.1.7
  - MySQL version: percona 5.7.18
  - Web server: Apache
  - OS name and version:  Debian Jessie (x86_64)

## Expected Behavior

In Chrome 60.0.3112.90 

Hitting save in an entry form with a WYSIWYG Full textarea with new content in it  should save new content in database

## Actual Behavior

In Chrome 60.0.3112.90 

Hitting save in an entry form with a WYSIWYG Full textarea with new content in it will fire a warning notification "nothing changed, nothing saved" , and new content is not actualy saved (with no errors in javascript console)

## Steps to Reproduce
 1. open an entry with a WYSIWYG Full textarea
 2. change content in the WYSIWYG Full textarea 
 3. hit save

**Comment by rijkvanzanten** [comment]
Hi @textoo, thanks for the report. I have just installed a fresh copy of Directus from the master branch and can't seem to reproduce this issue (also on Chrome 60)...

Does this issue also happen on other interfaces or just `wysiwyg_full`? Lets try to specify the issue some more :)

**Comment by WellingGuzman** [comment]
The issue was happening when you edit an existing record, no on new records.

Closed by https://github.com/directus/directus/commit/32f14a4809e200be044e75ccb4ca06e97715a6b4

**Comment by akubheka** [comment]
Hi Guys, 

Has this been resolved?

**Comment by rijkvanzanten** [comment]
Hey @akubheka! It should be solved, seeing it’s closed. Are you having this issue (or a similar problem)?
