### ISSUE TITLE
Unmanaged Tables Should Not be Present

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1735]
A table that is *not* managed by Directus should not appear anywhere within Directus and should not be accessible by the API/SDK.

A table that is not managed:
![screen shot 2017-08-11 at 9 16 59 am](https://user-images.githubusercontent.com/522079/29214616-0b19388e-7e76-11e7-9e83-644679151d40.png)

Should not be in permissions options:
![screen shot 2017-08-11 at 9 17 16 am](https://user-images.githubusercontent.com/522079/29214620-0df79924-7e76-11e7-8055-f20aafc3b459.png)

**Comment by WellingGuzman** [comment]
Admin can see any table from the API, but on permissions, table not managed can't be listed on the permission table.

Closed by https://github.com/directus/directus/commit/0ba22ba67d69a7eb990714a3194c406401acff5f
