### ISSUE TITLE
Minor Bug - Flicker of "SELECT ALL CHECKBOX" in content modules

### ISSUE THREAD

**Issue by ernst86913** [directus/directus#17358]
### Describe the Bug

... nothing urgently - but still suggest to fix it... currently the SELECT ALL CHECKBOX is enabled as default in the content module... and with every load its then deselected - which results in an ugly screen flickering... suggest to have the checkbox initially deselected and load the screen that way

### To Reproduce

Just open one of the collections in your content modules and you will see it

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

18.13.0

### What database are you using?

Postgres 15

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
I believe this is caused by the checkbox checking if the number of selected items is equal to the number of loaded items. While it's loading, that number is 0 which is the same as the number of selected items, hence "all selected".
