### ISSUE TITLE
[status-page] Add empty input checks to project status I/P

### ISSUE THREAD

**Issue by Siddhant-K-code** [directus/directus#17351]
### Describe the Bug

On [Directus Status](https://status.directus.cloud/) page. There is no empty check for the `Check Project Status` input. Which returns the Internal Server Error page. 

### To Reproduce

See this 👀 

https://user-images.githubusercontent.com/55068936/215685228-7a019f6b-d35d-4cdd-a937-50b7179e0183.mov

### Errors Shown

Internal Server Error

### What version of Directus are you using?

n/a

### What version of Node.js are you using?

n/a

### What database are you using?

n/a

### What browser are you using?

Chrome

### How are you deploying Directus?

n/a

**Comment by azrikahar** [comment]
Heya! Thanks for the heads up. This seems like a Directus Cloud Status page specific issue so I'll pass this along to our cloud team as they will be more suited to look into this matter 👍🏻

For future issues specific to Directus Cloud projects or including the Directus Cloud Status page, please reach out through [the Live Chat in our Cloud Dashboard](https://directus.cloud/) as that's the best channel to notify the cloud team directly 🙂
