### ISSUE TITLE
Exporting all fields to File Library fails

### ISSUE THREAD

**Issue by hissingpanda** [directus/directus#17360]
### Describe the Bug

When trying to export items to the file library with all fields (no fields selected) from the browser directus is unable to generate the export and responds with an error message.

This is mainly a problem when trying to export more than 2500 items as the browser forces you to use the file library so it can be generated in batches.

Exporting to the file library with specific fields selected works and exporting all fields (>100) when the export location is set to Download File also works.

### To Reproduce

1. open collection
2. select export items from right sidebar
3. select file library for export location
4. remove all fields selected and start export

### Errors Shown

"Your export of [db_name] failed" appears in user notifications. No messages appear in the browser console. Selecting the failed notification takes you to a page not found: https://admin.debtcollective.org/items/null/null

### What version of Directus are you using?

9.22.3

### What version of Node.js are you using?

18.13.0

### What database are you using?

Postgres 11.16

### What browser are you using?

Firefox

### How are you deploying Directus?

Docker on an AWS EC2 instance

**Comment by rijkvanzanten** [comment]
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻
