### ISSUE TITLE
Cloud CMS does not save changes

### ISSUE THREAD

**Issue by yondr-luka** [directus/directus#17366]
### Describe the Bug

I am trying to create new record and updating existing.
When saving the changes it still show the old data or there has not been created a new record

Deleting records does work

### To Reproduce

Using Cloud CMS content

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

directus cloud

### What database are you using?

directus cloud

### What browser are you using?

Chrome

### How are you deploying Directus?

directus cloud

**Comment by br41nslug** [comment]
Sounds like it could perhaps be caching related 🤔 Did you create a cloud support ticket for this? You can do this via the chatbot in the cloud dashboard (or directly using this form https://share.hsforms.com/1Kuu-0jHIRYGd2cYSbofC_Ac8497)

**Comment by yondr-luka** [comment]
I found it was a flow action that overwrite the new data with the old data. The documentation about the payload isn't very clear, probably did something wrong here.
