### ISSUE TITLE
Many to One: Selection/Placeholder

### ISSUE THREAD

**Issue by rtm516** [directus/directus#1737]
## Version Info
  - Directus version and branch: master (fabd5479836c0b06a0ef20f5916b92e5a06e8987)
  - PHP version: 5.6.14
  - MySQL version: 5.6.21
  - Web server: (Ex. Apache, nginx or IIS?) Apache 2.4.17
  - OS name and version: Windows Server 2012 R2

## Expected Behavior
The form adds the item with no errors.

## Actual Behavior
The form thinks you haven't selected a value for the dropdown even though there is only one option. The placeholder attribute is also ignored.

## Steps to Reproduce
 1. Create a many to one dropdown with only one row in the other table.
 2. Try and create a new item where it is auto selected.

## Schema Dump, Logs, or Screenshots
![The error](https://share.rtm516.co.uk/2017-08-14_15-42-18.png)
![Placeholder set](https://share.rtm516.co.uk/2017-08-14_15-46-56.png)

**Comment by WellingGuzman** [comment]
Hey @rtm516, this has been fixed in the latest commit from `develop` branch.

Closed by https://github.com/directus/directus/commit/2748f5b825be9bb008a1fe4d012329868d19145f
