### ISSUE TITLE
Corresponding Field is not working for system collections "directus_files"

### ISSUE THREAD

**Issue by ncxx23** [directus/directus#17376]
### Describe the Bug

I try to create "Multiple Files" relation field and set up corresponding field (m2m) in directus_files collection
![Screenshot 2023-02-02 at 14 56 17](https://user-images.githubusercontent.com/124268186/216333121-c93d94ea-93c0-44ab-bfbc-bccf0eef5b1d.png)
----
![Screenshot 2023-02-02 at 14 56 33](https://user-images.githubusercontent.com/124268186/216333186-d1dab63b-fdc3-4be3-91a6-59d20111287b.png)
----
This field is created but if you open that corresponding field you see it is don't have any relations and look corrupted.
![Screenshot 2023-02-02 at 14 56 57](https://user-images.githubusercontent.com/124268186/216334558-a28781fb-c880-4fef-8a0b-1f5b19efa705.png) and after this moment any action with directus_files  causes an error, and the current files are no longer available (they visible but show error when you click on it)

### To Reproduce

Create "Multiple files" field with corresponding m2m field.

### Errors Shown

```
{
  "errors": [
    {
      "message": "select \"directus_files\".\"id\", \"directus_files\".\"storage\", \"directus_files\".\"filename_disk\", \"directus_files\".\"filename_download\", \"directus_files\".\"title\", \"directus_files\".\"type\", \"directus_files\".\"folder\", \"directus_files\".\"uploaded_by\", \"directus_files\".\"uploaded_on\", \"directus_files\".\"modified_by\", \"directus_files\".\"modified_on\", \"directus_files\".\"charset\", \"directus_files\".\"filesize\", \"directus_files\".\"width\", \"directus_files\".\"height\", \"directus_files\".\"duration\", \"directus_files\".\"embed\", \"directus_files\".\"description\", \"directus_files\".\"location\", \"directus_files\".\"tags\", \"directus_files\".\"metadata\", \"directus_files\".\"candidates_test\" from \"directus_files\" where \"directus_files\".\"id\" = $1 order by \"directus_files\".\"id\" asc limit $2 - column directus_files.candidates_test does not exist",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

![Screenshot 2023-02-02 at 14 57 15](https://user-images.githubusercontent.com/124268186/216335366-79e597c5-a647-4363-9681-8216ac5378ef.png)

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

18.13.0

### What database are you using?

Postgres: 15.1

### What browser are you using?

Crome

### How are you deploying Directus?

Docker

**Comment by Nitwel** [comment]
Do you have permissions configured so that you can't edit the `directus_files` collection or something similar?

**Comment by ponanin** [comment]
I can confirm, reproduced, version 9.22.3 in Docker

**Comment by ncxx23** [comment]
> Do you have permissions configured so that you can't edit the `directus_files` collection or something similar?

Yeah, I have full permissions (admin role), I can create fields in system collections.
Creating the "Multiple Files" field does not even offer a choice of collection, it automatically creates a link to that system collection "directus_files"
I tried to reproduce this bug on 3 different directus instances - it reproduces everywhere.

https://user-images.githubusercontent.com/124268186/216601476-aeca0802-df44-4352-a651-c45ff423440b.mov

**Comment by Nitwel** [comment]
Yea, I overlooked that you wrote that the error occurs when interacting with it. I read it as it would error on creating. 👍
