### ISSUE TITLE
WYSIWYG: Image is automatically placed inside <p>

### ISSUE THREAD

**Issue by TheOneAndOnlyGarcia** [directus/directus#17380]
### Describe the Bug

Hello, 

when I add an image inside the WYSIWYG editor it is automatically placed inside `<p>`. Is there any way to disable this behavior? Is this intended?

Even when using edit source code of WYSIWYG:
```html
<p>bar</p>
<img src="http://xyz" alt= />
```

becomes after save
```html
<p>bar</p>
<p><img src="http://xyz" alt= /></p>
```

Basically `<img>` tags are within `<p>` valid html. However, we run a parser over our content that replaces all images outside of `<p>` with more complex divs. `<div>` inside `<p>` would be invalid html. So it would be great if the WYSIWYG editor would not put the `<img>` inside a `<p>` when adding an image. It's a bit tedious to manually move each image outside the `<p>` and add a `<div>` to it.

thanks a lot!

### To Reproduce

* open WYSIWYG editor
* place image
* edit source code
* move `<img>` out of `<p>` 
* save
* edit source code 
* ---> `<img>` is inside `<p>`

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

14.18.1

### What database are you using?

postgres 14

### What browser are you using?

chrome

### How are you deploying Directus?

docker

**Comment by rijkvanzanten** [comment]
Directus relies on TinyMCE, which does this by default (so it's intended). You should be able to disable that by setting "Options Overrides" to `{ "force_p_newlines": false }`
