### ISSUE TITLE
Extension's dependency treated as external

### ISSUE THREAD

**Issue by florian-lefebvre** [directus/directus#17398]
### Describe the Bug

When creating an interface extension, node imports are generated. When starting directus, it shows a warning and the extension doesn't appear in the app.

Context: https://discord.com/channels/725371605378924594/1071098328529506385

### To Reproduce

https://github.com/florian-lefebvre/directus-extension-repro

### Errors Shown

```sh
"node:url" is imported by "extensions/interfaces/osm-autocomplete/index.js", but could not be resolved – treating it as an external dependency.
"node:http" is imported by "extensions/interfaces/osm-autocomplete/index.js", but could not be resolved – treating it as an external dependency.
"node:https" is imported by "extensions/interfaces/osm-autocomplete/index.js", but could not be resolved – treating it as an external dependency.
"node:util" is imported by "extensions/interfaces/osm-autocomplete/index.js", but could not be resolved – treating it as an external dependency.
"node:stream" is imported by "extensions/interfaces/osm-autocomplete/index.js", but could not be resolved – treating it as an external dependency.
"node:assert" is imported by "extensions/interfaces/osm-autocomplete/index.js", but could not be resolved – treating it as an external dependency.
"node:zlib" is imported by "extensions/interfaces/osm-autocomplete/index.js", but could not be resolved – treating it as an external dependency.
"node:events" is imported by "extensions/interfaces/osm-a
``` 

### What version of Directus are you using?

^9.22.4

### What version of Node.js are you using?

16.15.0

### What database are you using?

Postgres 15 (postgis/postgis:15-3.3-alpine)

### What browser are you using?

Brave v1.47.186

### How are you deploying Directus?

Running locally

**Comment by Nitwel** [comment]
This doesn't look like a bug on our side. I just tested again with the default template generated by `pnpm create directus-extension` to import that extension and everything is fine. Maybe it's caused by `"@rollup/plugin-commonjs": "^24.0.1",` on your side but I'm just guessing here.

Try creating a new empty template with the latest extension cli like I did and then adding your changes onto that.

**Comment by florian-lefebvre** [comment]
Alright thx! I'll try and send updates there if I find anything
