### ISSUE TITLE
Problem while trying to refresh any page

### ISSUE THREAD

**Issue by ngirardhg** [directus/directus#1740]
## Version Info
  - Directus version and branch: 6.4.1 (Ruby rabbit)
  - PHP version: 5.6.30
  - MySQL version: 5.0.11
  - Web server: Apache (XAMPP)
  - OS name and version: Windows 7 pro service pack 1

## Expected Behavior
Refreshing any pages should refresh the page and display it again 
(exemple, refreshing : http://localhost:8888/_clients/cch/directus/ecole-de-pilotage/tables)

## Actual Behavior
Refreshing any page display a 404, object not found.

## Steps to Reproduce
 1. Go to any page,
 2. Refresh it

## Schema Dump, Logs, or Screenshots
![404](https://user-images.githubusercontent.com/31041083/29322426-70742a44-81ab-11e7-8446-172ba2b3ff9e.png)

Directus config (api/config.php)
![configs](https://user-images.githubusercontent.com/31041083/29322543-da7389f8-81ab-11e7-92a6-3ec0e3514be0.png)

Php info screenshot (showing mod_rewrite as part of the loaded modules)
![rewrite](https://user-images.githubusercontent.com/31041083/29323343-993806d2-81ae-11e7-9e9e-51222054ba27.png)

**Comment by benhaynes** [comment]
Hey @ngirardhg – I know you mentioned that the install went smoothly, but our devs seem to think this is a mod_rewrite issue. Could you confirm that this is working?

**Comment by ngirardhg** [comment]
I just uploaded a new screenshot showing my phpinfo(). I can see mod_rewrite as a loaded module so it seems to be activated.

**Comment by WellingGuzman** [comment]
Hey @ngirardhg if you go to `http://localhost:8888/_clients/cch/directus/ecole-de-pilotage/tables` directly doesn't work, or is it only on refresh?

Also can you please share your apache virtual host?

**Comment by ngirardhg** [comment]
It's not only on refresh, if I go directly to [http://localhost:8888/_clients/cch/directus/ecole-de-pilotage/tables](url) I still get a 404. The only way I can access the app normaly is by going to [http://localhost:8888/_clients/cch/directus/ecole-de-pilotage/](url)

As for the virtual host, I haven't changed the default value. The (httpd-vhosts.conf) file of apache is commented, which is the default values.

**Comment by ngirardhg** [comment]
Here is my detailed configuration : 

λ httpd.exe -S

VirtualHost configuration:
*:443                  www.example.com (C:/xampp/apache/conf/extra/httpd-ssl.conf:121)
ServerRoot: "C:/xampp/apache"
Main DocumentRoot: "C:/xampp/htdocs"
Main ErrorLog: "C:/xampp/apache/logs/error.log"
Mutex ssl-stapling-refresh: using_defaults
Mutex rewrite-map: using_defaults
Mutex ssl-stapling: using_defaults
Mutex proxy: using_defaults
Mutex ssl-cache: using_defaults
Mutex default: dir="C:/xampp/apache/logs/" mechanism=default
PidFile: "C:/xampp/apache/logs/httpd.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG

**Comment by WellingGuzman** [comment]
I would like to see how you set up the virtualhost that point to `localhost:8888`

**Comment by ngirardhg** [comment]
Here is the only line of setup I have changed to point to localhost:8888, which is located in httpd.conf file.
![httpdconfserverhost](https://user-images.githubusercontent.com/31041083/29328624-2f4a10b8-81c1-11e7-87fb-d49af17839d7.png)

Here is the httpd-vhosts.conf file that would be set up if I made any changes in the vhosts settings. 
![virtualhosts](https://user-images.githubusercontent.com/31041083/29328765-a450971a-81c1-11e7-971c-f6b04d963b64.png)

**Comment by WellingGuzman** [comment]
Hey @ngirardhg, sorry for the delay, does this still happening to you?

**Comment by WellingGuzman** [comment]
You are missing the `.htaccess` file on the root directus directory, that's why you are getting 404 when you go to `http://localhost:8888/_clients/cch/directus/ecole-de-pilotage/tables` and not when you go to `http://localhost:8888/_clients/cch/directus/ecole-de-pilotage`

Please make sure the `.htaccess` (hidden files) exists.

**Comment by benhaynes** [comment]
We should add this to our "Installation FAQs"!

**Comment by ngirardhg** [comment]
@WellingGuzman @benhaynes Thanks for your support, problem solved !

**Comment by WellingGuzman** [comment]
I added some information about 404 page into the FAQ doc page. https://github.com/directus/docs/commit/be52bb96ad3e08ff178ee8f9deff35679bf3ecb4
