### ISSUE TITLE
can't access payload in other flow

### ISSUE THREAD

**Issue by sharkfin009** [directus/directus#17404]
### Describe the Bug

I am triggering another flow and can see a valid payload on the first trigger operation in the flow. However I cannot get hold of this data. In the simplest test I have a script operation returning the data argument... surely that should give me something ? But it's returning an empty object

### To Reproduce

FIre a second flow with the 'trigger flow' operation, passing in a payload like this :
{
    "enquiryType": "{{$trigger.collection}}",
    "enquiryData": "{{$trigger.payload}}",
    "customer": "{{get_customer_object[0]}}",
    "consultant": "{{get_customer_consultant[0]}}"
}

I am not assigning a response body as that has brought less success, ie no payload showing at all .

### What version of Directus are you using?

9.22.3

### What version of Node.js are you using?

16

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

Railway.app

**Comment by sharkfin009** [comment]
![Uploading Screen Shot 2023-02-05 at 17.19.44.png…]()

**Comment by sharkfin009** [comment]
Here you can see the 'run script' operation outputting {} in the log, with the data sitting pretty in the trigger payload above.

**Comment by sharkfin009** [comment]
![Screen Shot 2023-02-05 at 17 19 44](https://user-images.githubusercontent.com/30635121/216854433-2d2bc44e-b0f4-4a1d-979f-027c8b785cb1.png)

**Comment by paescuj** [comment]
Thanks for opening this issue! This has been fixed by #17181 in the meantime. This fix will be included in the next release, so I'll proceed to close this issue but if you think it is actually a different issue, then please do not hesitate to comment.

**Comment by sharkfin009** [comment]
Thanks very much @paescuj ! I made a monster spaghetti flow to get things working for now. Look forward to the next release and thanks for the absolutely awesome work you guys are doing. Am really loving Directus

**Comment by paescuj** [comment]
Thank you very much for your positive feedback! ❤️ I'm glad to hear that you've been able to find a workaround for now.
