### ISSUE TITLE
When I add new list of relations, empty fields appear

### ISSUE THREAD

**Issue by koksikus** [directus/directus#17413]
### Describe the Bug

When I add more than 15 items to the M2M field with an empty value, additional empty values are displayed.
I conducted a short investigation and this is due to the value set in the Interface in the Per Page field, here I have set 15 and when I add more, 15 is displayed correctly, the rest is empty and when I choose the next tab, the first 15 are empty and the next ones are saved correctly. After saving, everything is ok and only those with values are saved, empty ones disappear. If I modify the value then various strange things happen.
The problem occurs in the latest version as well as in the previous 9.18.1

![Zrzut ekranu 2023-02-06 141120](https://user-images.githubusercontent.com/90528895/216980074-6cb305ff-1d67-4809-85ff-7686ea069102.jpg)

### To Reproduce

In the M2M field where you have the layout set: List and Per Page: 15 then add more relations than this number.

### Errors Shown

aggregate[count]=* 500 (Internal Server Error)
 Uncaught (in promise) X {message: 'Request failed with status code 500', name: 'AxiosError', code: 'ERR_BAD_RESPONSE', config: {…}, request: XMLHttpRequest, …}

### What version of Directus are you using?

9.22.3

### What version of Node.js are you using?

16.18.1

### What database are you using?

MS SQL

### What browser are you using?

Edge

### How are you deploying Directus?

locally

**Comment by paescuj** [comment]
I haven't been able to reproduce this so far. 

> When I add more than 15 items to the M2M field with an empty value [...]

What do you mean by an empty value? Would you mind to explain the steps in more detail or perhaps show it with a short video?

**Comment by rijkvanzanten** [comment]
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Comment by koksikus** [comment]
Here is the video with the problem. Latest version of directus

https://user-images.githubusercontent.com/90528895/217331765-1ae342e8-aca7-4ab4-89d2-0cbf63dd1244.mp4

**Comment by koksikus** [comment]
The attempt without the filter also ends the same. It is enough that there will be more than a number in Per Page

**Comment by koksikus** [comment]
[paescuj](https://github.com/paescuj) I don't know how to report it when the ticket is closed. How is it done? It is enough to add a comment, or is it better to mention in the comment the person who closed or dealt with it?

**Comment by paescuj** [comment]
Yes, it's enough to add a comment! 👍 Thanks, we'll look into it.

**Comment by paescuj** [comment]
Thanks for the video! I've now been able to reproduce it on my end.

- Create first collection (e.g. `test1`) with some fields (e.g. `status` field and a string field)
- Create second collection (e.g. `test2`) with a M2M field pointing to `test1` and a configured "Display Template":
  <img width="350px" src="https://user-images.githubusercontent.com/5363448/217484894-052ec3d3-af0f-42c9-a8c8-60a193b508c5.png">
- Create > 15 items in `test1`, create a new item in `test2` and add all items from `test1` at once.

**Result:**
<table><tr><th>Page 1</th><th>Page 2</th></tr><tr><td>
<img src="https://user-images.githubusercontent.com/5363448/217484983-43416404-8550-43de-936f-3c7c89f39d91.png">
</td><td>
<img src="https://user-images.githubusercontent.com/5363448/217485381-3ea16675-c242-4b12-89a2-52178201e0d3.png">
</td></tr></table>

**Result when "Display Template" for M2M field is left unconfigured:**
<table><tr><th>Page 1</th><th>Page 2</th></tr><tr><td>
<img src="https://user-images.githubusercontent.com/5363448/217486317-69cafd98-c0f8-4927-9a51-9f64b64976ff.png">
</td><td>
<img src="https://user-images.githubusercontent.com/5363448/217486343-63c750b8-58f6-41a9-9a68-5800ca95c319.png">
</td></tr></table>
