### ISSUE TITLE
Bug: `directus link` command links incorrect directory

### ISSUE THREAD

**Issue by ched-dev** [directus/directus#17421]
### Describe the Bug

Running a `directus link ../directus-demo/extensions/modules/` generates a symlink pointing to root of extension folder instead of `extension-workspace/dist/` folder.

This breaks loading of the app that uses this extension:

> WARN: Couldn't bundle App extensions
> WARN: Could not resolve "./extensions/modules/directus-extension-medialab/index.js" from "virtual:entry"

Note, running command from `./dist/` folder produces same result.

### To Reproduce

After creating a Directus Extension with the [Scaffolding your Directus Extension documentation](https://docs.directus.io/extensions/creating-extensions.html#scaffolding-your-directus-extension), I see I have a script in my `package.json` for `directus link`.

When I run `npm run link ../directus-demo/extensions/modules/` to install in my directus demo application, it creates the symlink at `../directus-demo/extensions/modules/directus-extension-medialab` and points to the root of my extension directory instead of the `./dist/` folder (based on [local extension install docs](https://docs.directus.io/extensions/creating-extensions.html#local-extension)).

This causes an error when I start my directus demo app:

> WARN: Couldn't bundle App extensions
> WARN: Could not resolve "./extensions/modules/directus-extension-medialab/index.js" from "virtual:entry"

### What version of Directus are you using?

9.4.2 - 9.22.3

### What version of Node.js are you using?

v16.13.2

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What OS are you using?

Mac OS 12 Monterey

**Comment by Nitwel** [comment]
Heya, the right command would be to run `npm run link ../directus-demo/extensions/`. The reason being we want to move away from having to worry about putting extensions in the right subfolder. That's why we introduced top level extensions which means every folder on the top level of your extensions folder that starts with `directus-extension-` will be loaded. 

The link command should symlink you whole project structure to the extensions folder and the api should be able to then load that.

**Comment by FenkoAlex** [comment]
@ched-dev  i have same problem, in my case i install necessary dependencies for module, which solve 
> WARN: Couldn't bundle App extensions
> WARN: Could not resolve "./extensions/modules/directus-extension-medialab/index.js" from "virtual:entry"

**Comment by julpod** [comment]
I've found my way by
```json
...
	"scripts": {
		"build": "directus-extension build && npm run sync",
		"dev": "directus-extension build -w --no-minify",
		"sync": "mkdir -p ../<project-name>/extensions/themes/<extension-name> && cp ./package.json ./dist/* ../<project-name>/extensions/themes/<extension-name>/",
		"link": "directus-extension link"
	},
...
```
