### ISSUE TITLE
Route `/schema/snapshot` doesn't exist

### ISSUE THREAD

**Issue by leonardodipace** [directus/directus#17422]
### Describe the Bug

The [schema endpoints](https://docs.directus.io/reference/system/schema.html) are not working in the latest [Docker Image](https://hub.docker.com/r/directus/directus).
When I try to send a GET request to the `/schema/snapshot` endpoint I get the `ROUTE_NOT_FOUND` error.

### To Reproduce

1. Pull the latest Docker Image from Docker Hub
2. Start a new container
3. Reach the `/schema/snapshot` endpoint

### Errors Shown

```
{
  "errors": [
    {
      "message": "Route /schema/snapshot doesn't exist.",
      "extensions": {
        "code": "ROUTE_NOT_FOUND"
      }
    }
  ]
}
```

### What version of Directus are you using?

9.22.3

### What version of Node.js are you using?

18.13.0

### What database are you using?

MySQL

### What browser are you using?

Microsoft Edge

### How are you deploying Directus?

Docker

**Comment by licitdev** [comment]
https://github.com/directus/directus/pull/14713 was recently merged and it will be in the next release.
