### ISSUE TITLE
Table with a wysiwyg full gives error message

### ISSUE THREAD

**Issue by ngirardhg** [directus/directus#1742]
## Version Info
  - Directus version and branch: 6.4.1 (Ruby rabbit)
  - PHP version: 5.6.30
  - MySQL version: 5.0.11
  - Web server: Apache (XAMPP)
  - OS name and version: Windows 7 pro service pack 1

## Expected Behavior
Adding a wysiwyng full to a table and trying to display the page of the table should display the page and the wysiwyg full

## Actual Behavior
Displaying the page with a wysiwyg full in it gives an error

## Steps to Reproduce
 1. Create a table
 2. Add a wysiwyg full
 3. Try to add a new entry into that table

## Schema Dump, Logs, or Screenshots
![errormsg](https://user-images.githubusercontent.com/31041083/29328056-269c45f0-81bf-11e7-84bb-445f37b05759.png)

**Comment by rijkvanzanten** [comment]
@WellingGuzman Could you verify if the TinyMCE is correctly bundled in the minified app bundle?

**Comment by michlschmitt** [comment]
Same issue here. 

`Error
Error: TypeError: t is not a constructor
File: http://localhost:8888.com/assets/js/directus.min.js?bust=2c40adb22af1449ffe6acc6150422a71
Line:38`

**Comment by textoo** [comment]
similar issue here, 

Error: Uncaught SyntaxError: Unexpected token <
File: http://mywebsite.com/app/plugins/hr/plugin.min.js
Line:1

as this file is not existing, a html file is returned so a javascript error apply

it appears that this error is fired multiple times, with a different missing file:

/app/plugins/table/plugin.min.js
/app/plugins/hr/plugin.min.js
/app/plugins/image/plugin.min.js
/app/plugins/link/plugin.min.js
....

**Comment by rijkvanzanten** [comment]
@michlschmitt @textoo are these happening on the bundled download?

**Comment by michlschmitt** [comment]
@rijkvanzanten yes, I use the bundled version.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/743590035352c0094f6d03815af1ed5b81c0f703

If it doesn't work let us know and we are going to re-open the ticket.

Make sure to update the branch (build)

**Comment by textoo** [comment]
@WellingGuzman works like a charm now, thanks, second time i post an issue, second time it's fixed in less than 24h. you rocks.
