### ISSUE TITLE
Error using Directus in live server but works smoothly on local server

### ISSUE THREAD

**Issue by Sirjoseph94** [directus/directus#1743]
## Version Info
  - Directus version and branch:  6.4.1 (Ruby rabbit)
  - PHP version: 7.1
  - MySQL version: 10.1.24-MariaDB-cll-lve
  - Web server:  Apache, 2.2.31
  - OS name and version: linux

## Expected Behavior
After login in, I should be able to create new tables and records as well as modify settings

## Actual Behavior
Nothing works. almost any action i try to carry out is followed by an error message. but on my local server (xampp) it works smoothly. As soon as i upload the project that is working locally to my live server, i keep getting errors

## Steps to Reproduce
 1. Install version 6.4.1 (Ruby rabbit)
 2. login
 3. try to create a new table

## Schema Dump, Logs, or Screenshots
![screencapture-glimng-org-admin-settings-global-1502839045649 1](https://user-images.githubusercontent.com/21038634/29341766-7d7350d0-821e-11e7-82ec-21f45acbf5af.png)

**Comment by benhaynes** [comment]
Hey @Sirjoseph94 – this is definitely just a configuration issue. How did you install? The `build` branch?

**Comment by Sirjoseph94** [comment]
i downloaded it from the release

**Comment by benhaynes** [comment]
Are you using a caching service, such as CloudFlare? This would minify the templates, thereby breaking them.

**Comment by benhaynes** [comment]
I'm not sure what the specific issue/difference is with your setup, but if you disable the caching it should work. 

If you're using CloudFlare try this:

> Ok for anyone that is having issues with CloudFlare, if you create a rule disabling cache and performance, for the url it should fix your issues.

**Comment by Sirjoseph94** [comment]
I have created the pagerule but still get same errors
`Error
Error: Uncaught Error: Parse error on line 1:
...l">{{/if}}
-----------------------^
Expecting 'OPEN_ENDBLOCK', got 'EOF'
File: https://www.glimng.org/admin/app/directus.min.js?bust=hgqqronnfcl68qv312ouv8su26
Line:1`

**Comment by Sirjoseph94** [comment]
I even turned off rocket loader

**Comment by benhaynes** [comment]
We'll keep this open for a bit (for exposure) but unless we can duplicate it we'll close it. Since it's (most likely) not a Directus issue, I would recommend submitting something on StackOverflow for config/server help:

https://stackoverflow.com/search?q=directus

**Comment by WellingGuzman** [comment]
@Sirjoseph94 do you have anything that could be removing spaces from the `.html` files? maybe we should remove the `.html` extension and use `.hbs` instead so we avoid this issue in the future, as most service/extension/etc just look for `.html`.

What do you all think about this?

**Comment by Sirjoseph94** [comment]
![screencapture-server189-web-hosting-2083-cpsess9300672089-frontend-paper_lantern-home-status-html-1502942773546](https://user-images.githubusercontent.com/21038634/29395602-db77e97a-8309-11e7-936b-47772cb3a687.png)

My cloudflare auto minifies html. but i have removed it from the directus folder

**Comment by Sirjoseph94** [comment]
i also noticed when ever i first attempt to login, it first shows `server error` then it login successfully when i try it again

**Comment by Sirjoseph94** [comment]
i changed my browser and its working. i think it was a cache issue(though i cleared my cache on google chrome.

but now am getting 500 error code when i try to access the main code

<?php
define("BASE_URL", "/");
define("ROOT_PATH", $_SERVER{"DOCUMENT_ROOT"}. "/");

include __DIR__ . '/../vendor/autoload.php';

$client = \Directus\SDK\ClientFactory::create('pjcfACZwOf38e5PDuz3bepdkIrFjE2y9', [
    // Directus API Path without its version
    'base_url' => 'https://www.glimng.org/',
    'version' => '1.1' // Optional - default 1
]);

**Comment by WellingGuzman** [comment]
Hey @Sirjoseph94, what's your current issue? getting 500 internal issue every time you access the site?

Is there any errors log (api/logs):

**Comment by Sirjoseph94** [comment]
yes i keep getting 500 internal Server Error each time i access the site

**Comment by Sirjoseph94** [comment]
Thanks for the hint. I checked the error log and i have been able resolve it. Everything is working now. Thanks for the surport

**Comment by WellingGuzman** [comment]
@Sirjoseph94 What was the issue? does that close the ticket?

**Comment by Sirjoseph94** [comment]
After checking the error log, I discovered the vendor folder was not properly uploaded. After uploading it again the autoload.php was able to run successfully. 

Yes it can be closed now. Thanks
