### ISSUE TITLE
Cache is not refreshed, when schema is updated in production.

### ISSUE THREAD

**Issue by vitali-droujko** [directus/directus#17437]
### Describe the Bug

I run Directus in GKE. (Node v18, Directus v9.22.4)
When I open a shell inside the pod, and I execute a command to update the schema:
```
     npx directus schema apply ./data/snapshots/v1.yaml
```

Then I open the directus UI, I can show my new collection successfully created. But if I click on it, to add one item, I can't with  a 403 forbidden the form is empty.

Maybe the title of the issue is wrong.
Locally, it's ok, the solution is to restart directus.
In production it's okay too, the solution is to restart the pod.
It's temporary solution until a future release of directus with this bug fixed.

### To Reproduce

You can reproduce the bug locally:

-> launch directus (don't kill the process)
```
npx directus start
```
-> open another shell then update the schema (add a new collection or a new field in a collection)
```
npx directus schema apply ./data/snapshots/v1.yaml
```
-> go to your browser and refresh the page

### Errors Shown

There is different bugs, I don't identify them all but I think it's related to the fact that the schema is not updated in the same time as the database.
List of identified bugs:
 -> if in your new schema you have a new collection, you can't create a new item in this collection. (403 forbidden)
 -> if you have a new field in a collection, you can't create a new item in this collection. (page not found)

### What version of Directus are you using?

v9.22.4

### What version of Node.js are you using?

v18

### What database are you using?

PostgreSQL

### What browser are you using?

chrome | safari

### How are you deploying Directus?

Google kubernetes engine | locally

**Comment by br41nslug** [comment]
You can disable the schema cache (`CACHE_SCHEMA`) or lower its TTL (`CACHE_SYSTEM_TTL`) to prevent this. https://docs.directus.io/self-hosted/config-options.html#cache
