### ISSUE TITLE
Can't deactivate manual sorting

### ISSUE THREAD

**Issue by Nitwel** [directus/directus#17445]
### Describe the Bug

After clicking on the manual sort button in v-table the second time, the app errors.

### To Reproduce

See above.

### Errors Shown

--

### What version of Directus are you using?

latest

### What version of Node.js are you using?

latest

### What database are you using?

latest

### What browser are you using?

latest

### How are you deploying Directus?

latest

**Comment by djmtype** [comment]
Has this issue been merged? I can't deactivate the manual sort either, running Directus 9.22.4

**Comment by paescuj** [comment]
> Has this issue been solved? I can't deactivate the manual sort either, running Directus 9.22.4

This has been solved by #17446 which will be available with the next release.
