### ISSUE TITLE
TinyMCE and other JS not working after upgrade from v6.3.9 to v6.4.1

### ISSUE THREAD

**Issue by prudolph81** [directus/directus#1744]
## Version Info
  - Directus version and branch: v6.4.1
  - PHP version: 5.6
  - MySQL version: 5.6
  - Web server: Apache
  - OS name and version:  Linux

## Error Description
After upgrade to v6.4.1 TinyMce (an other JS) is not working anymore. Tries to load e.g. example.org/app/themes/modern/theme.min.js instead of example.org/assets/js/themes/modern/theme.min.js (where the file is located)

**Comment by WellingGuzman** [comment]
Thanks @prudolph81, I will close this as this issue is duplicated.

Follow up here: https://github.com/directus/directus/issues/1742
