### ISSUE TITLE
Directus CLI error when upgrading

### ISSUE THREAD

**Issue by aaronaustin** [directus/directus#1745]
## Version Info
  - Directus version and branch: 4886be3
  - PHP version: 7.0.15
  - MySQL version: 5.6.35
  - Web server: Apache
  - OS name and version: OSX 10.12.5 

I'm trying to upgrade the db after downloading the newest build.  I checked the api/config.php file and the db is configured,  but I'm getting this error:

`Warning: mysqli::mysqli(): (HY000/2002): No such file or directory in /Applications/MAMP/htdocs/lexcentraladmin/vendor/directus/migrations/lib/Ruckusing/Adapter/MySQL/MySQLBase.php on line 1294

Fatal error: Uncaught
MySQLBase.php(1296) :

Could not connect to the DB, check host / user / password

  thrown in /Applications/MAMP/htdocs/lexcentraladmin/vendor/directus/migrations/lib/Ruckusing/Adapter/MySQL/MySQLBase.php on line 129 6`

## Steps to Reproduce
Ran `php bin/directus db:upgrade` from the root directus project folder.

Things are running fairly normally except for a few issues that I think are caused by a custom interface I made, but I want to make sure that a change in schema isn't causing problems.

**Comment by WellingGuzman** [comment]
Hey @aaronaustin thanks for reporting this, do you have `mysqli` installed?

**Comment by aaronaustin** [comment]
Yep.  Here's my phpinfo from the mysqli section:

<img width="643" alt="screen shot 2017-08-17 at 10 52 32 am" src="https://user-images.githubusercontent.com/9779077/29418457-5337123a-833a-11e7-8112-997361b31025.png">

**Comment by WellingGuzman** [comment]
Thanks for the information. so you are actually able to log in, but can't upgrade?

**Comment by aaronaustin** [comment]
Yes.  I can login, though there is usually an error on the first attempt now.  But after that things work mostly fine.  When I attempt to upgrade the db via the cli, that's when I get the error.  I'm wondering if the few errors I'm getting in the cms are due to not upgrading the db or other changes that are making my custom interfaces fail.

**Comment by WellingGuzman** [comment]
wait. I think what could it be, what's the configuration of your php cli? version and see if it has `mysqli` installed.

Also about the first attempt error, probably is because you have an old database schema. do the `directus_users` table has a column named `active` instead of `status`?

**Comment by aaronaustin** [comment]
When I check the PHP version in the terminal it's 5.6.30, so I must be using the local version rather than the MAMP version.  I didn't even think about that.  I checked the modules loaded in the terminal and it says mysqli is loaded.  In the users table, there's an active column.

**Comment by WellingGuzman** [comment]
so using the `mamp` php cli does work? Actually the error seems to the connection not missing the `mysqli`, sorry for the confusion, what's your php cli version?

> In the users table, there's an active column.

That's the issue with the first time login error, as soon as you can run the directus cli (load mysql)

**Comment by aaronaustin** [comment]
I added the path for MAMP's PHP and things are working now.  Everything updated just fine. Login went smooth and it looks like the other errors are gone too. Sorry to bother you with this issue. Thanks so much for your help!

**Comment by WellingGuzman** [comment]
All good @aaronaustin, we appreciate these type of reports (issues) because we get to know how directus behave with different environments.

Thanks, anything else please let us know!
