### ISSUE TITLE
Display problems with table containing a translation

### ISSUE THREAD

**Issue by ngirardhg** [directus/directus#1746]
## Version Info
  - Directus version and branch: 6.4.1 (Ruby rabbit)
  - PHP version: 5.6.30
  - MySQL version: 5.0.11
  - Web server: Apache (XAMPP)
  - OS name and version: Windows 7 pro service pack 1

## Expected Behavior
A table contains a translation. The translation table contains a field which has a many-to-many relationship. If I go into the table containing the translation (the uppermost table), the items inside the field which has a many-to-many relationship should be displayed. In order to display these items, I have to go into the translation table. 

## Actual Behavior
Here is a visual example of the behaviour : 

Page is the parent table, containing the translation table. Here we can see that there are no items displayed for the field "Instructeurs".
![parent-page](https://user-images.githubusercontent.com/31041083/29425226-82623b50-8350-11e7-91eb-3533a28f6b14.png)

On the other hand, if I go to "Page Translations" table, which is the translation table, the items now display into the "Instructeurs" field.
![translation-page](https://user-images.githubusercontent.com/31041083/29425413-2b9090be-8351-11e7-8b3c-31fbc7cc7d3c.png)

## Steps to Reproduce
 1. Create a table and a translation table
 2. Link the table with the translation table
 3. Add a many to many relationship field to the translation table and add elements in it
 4. Try looking at these elements from the parent table

**Comment by WellingGuzman** [comment]
Hey @ngirardhg, sorry for the delay, can you provide the schema so it's easier for us to reproduce the issue and fix it? Thanks!

Also are you using 6.4.1 from the release version or a branch?

**Comment by ngirardhg** [comment]
@WellingGuzman Here is the schema for the database. 
[schema.zip](https://github.com/directus/directus/files/1235532/schema.zip)

I am using 6.4.1 from the release versions.

**Comment by WellingGuzman** [comment]
Thanks for the schema this would be really helpful!

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/1338670bfde673a0bc5a4a0d0c3497a84dd28d2f

This will be included in the next Directus version 6.4.2

@ngirardhg you can always cherry pick this commit

**Comment by ngirardhg** [comment]
@WellingGuzman Good job, Thanks !
