### ISSUE TITLE
Sorting a column in a Many to Many table returns error

### ISSUE THREAD

**Issue by laurens94** [directus/directus#17474]
### Describe the Bug

Hi, I hope I can describe this issue clear enough.

In my data model, I have a collection `project`. 
Within this collection there is a Many to Many field called `poster_layers`.

<details>
<summary>Show Data Model</summary>

![image](https://user-images.githubusercontent.com/5780704/217871331-ee1dc675-0669-4f7a-bb95-2e9b602dd0ed.png)

</details>

<details>
<summary>Show Many to Many field config</summary>

![image](https://user-images.githubusercontent.com/5780704/217870434-545242ae-eac6-4d59-b421-b0c48dcde66b.png)
![image](https://user-images.githubusercontent.com/5780704/217870488-da59d0eb-0205-41b2-b417-b7404d3658b0.png)
![image](https://user-images.githubusercontent.com/5780704/217870550-09b15e3e-2a84-47fe-864d-5830e18342f5.png)
![image](https://user-images.githubusercontent.com/5780704/217870569-baa4be50-a8ab-4922-a849-5c6f5c4d6e56.png)
![image](https://user-images.githubusercontent.com/5780704/217870608-a64aa9fa-faf8-4936-97a2-269492b256dc.png)

</details>

![image](https://user-images.githubusercontent.com/5780704/217868276-76970306-19cb-4315-a66b-a65e251789f2.png)

When I click on a column header to sort, e.g. `Z Index` in the screenshot above, I get the following error:

![image](https://user-images.githubusercontent.com/5780704/217868527-90523719-22bc-402d-b8fd-2850a84147ac.png)

---

Also, what is very weird (but maybe unrelated), is that sometimes when I click on an item in this table I get the following error:

![image](https://user-images.githubusercontent.com/5780704/217869176-da12ab42-0e52-4ae3-acc9-23ce47ea4c05.png)

Clicking on Dismiss just closes the popup and everything works as you'd expect: it opens the item and I can edit it. 

### To Reproduce

I'm not sure how to reproduce this, but the Poster Layers collection looks like this:

<details>
<summary>Show Poster Layers collection fields</summary>

![image](https://user-images.githubusercontent.com/5780704/217877062-d40ea9f1-cc37-4e99-9f06-3483032e2378.png)

</details>

<details>
<summary>Show Project Poster Layers junction table</summary>

![image](https://user-images.githubusercontent.com/5780704/217876979-ce145beb-7c66-425c-b0a8-86ad31694e94.png)
![image](https://user-images.githubusercontent.com/5780704/217877335-ec97231a-410f-4635-81cc-d50ffb8d9d0d.png)

</details>

### Errors Shown

I see a 400 Bad Request network error in the console:

`/items/project_poster_layers?fields[]=poster_layers_id.image.id&fields[]=poster_layers_id.image.type&fields[]=poster_layers_id.image.title&fields[]=poster_layers_id.zIndex&fields[]=poster_layers_id.id&fields[]=poster_layers_id.scale&fields[]=poster_layers_id.blendMode&fields[]=id&filter[_and][0][project_slug]=gnomes&page=1&limit=15&sort[]=poster_layers_id.poster_layers_id.zIndex`

I think the error is in the last `sort[]` parameter. If I replace that value with `poster_layers_id.zIndex` the request returns with 200 OK and the table sorts properly.

### What version of Directus are you using?

9.22.3

### What version of Node.js are you using?

-

### What database are you using?

Postgres

### What browser are you using?

Firefox

### How are you deploying Directus?

Docker image 9

**Comment by rijkvanzanten** [comment]
Odd! It feels like it might be setting something wrong in `deep`, which would error out if it's not a relational field.
