### ISSUE TITLE
Bookmarks API issue

### ISSUE THREAD

**Issue by miked63017** [directus/directus#1747]
## Version Info
  - directus.io
  - reference docs https://directus.io/api/overview/endpoints

## Expected Behavior
  - Querying ```/bookmarks``` should show your bookmarks
  - Querying ```/bookmarks/1``` should return user 1's bookmarks as per docs

## Actual Behavior
  - Best guess is that querying ```/bookmarks``` should only return the current user's bookmarks, either way it returns null
  - querying ```/bookmarks/1``` returns id 1 from directus_bookmarks table, or null if id belongs to a different user

## Steps to Reproduce
 1.  Create a bookmark
 2.  query the api to try to find it

## Schema Dump, Logs, or Screenshots
![screen shot 2017-08-17 at 3 44 19 pm](https://user-images.githubusercontent.com/5140447/29433877-8761d726-8366-11e7-98ae-62bb81111a42.png)

```
lstl8e22g8wm-m:directus s0043826$ curl -s https://miked63017--sdk-test-validation.directus.io/api/1/bookmarks?access_token=*********** | jq
null
```
```
lstl8e22g8wm-m:directus s0043826$ curl -s https://miked63017--sdk-test-validation.directus.io/api/1/bookmarks/1?access_token=*********** | jq
{
  "id": 1,
  "user": 1,
  "title": "Activity",
  "url": "activity",
  "icon_class": "icon-bell",
  "active": null,
  "section": "other"
}
lstl8e22g8wm-m:directus s0043826$ curl -s https://miked63017--sdk-test-validation.directus.io/api/1/bookmarks/2?access_token=*********** | jq
{
  "id": 2,
  "user": 1,
  "title": "Files",
  "url": "files",
  "icon_class": "icon-attach",
  "active": null,
  "section": "other"
}
lstl8e22g8wm-m:directus s0043826$ curl -s https://miked63017--sdk-test-validation.directus.io/api/1/bookmarks/3?access_token=*********** | jq
{
  "id": 3,
  "user": 1,
  "title": "Messages",
  "url": "messages",
  "icon_class": "icon-chat",
  "active": null,
  "section": "other"
}
lstl8e22g8wm-m:directus s0043826$ curl -s https://miked63017--sdk-test-validation.directus.io/api/1/bookmarks/4?access_token=*********** | jq
{
  "id": 4,
  "user": 1,
  "title": "Users",
  "url": "users",
  "icon_class": "icon-users",
  "active": null,
  "section": "other"
}
lstl8e22g8wm-m:directus s0043826$ curl -s https://miked63017--sdk-test-validation.directus.io/api/1/bookmarks/5?access_token=*********** | jq
null
```
Most of these seem to be internally created bookmarks, possibly configurable to change the way the UI looks. Thats fine, but I think maybe the /bookmarks endpoint should only return user created bookmarks?

Also, the docs say /bookmarks/[id] returns bookmarks for a specific user, but really it seems to be returning the specific bookmark with id = [id], not sure which is the intended behaviour. Either the docs are wrong or the api is not working as intended. I think returning the bookmark by id is probably better than the described behaviour in the api doc, because users won't really have access to other users' bookarks using their own access key. But I do believe that bookmark id 1 should return the first user created bookmark, and not the first internal book mark.

**Comment by WellingGuzman** [comment]
Hey @miked63017,

I've updated the docs for the confusion about `bookmarks/<id>` the `id` is the bookmarks `id`, if that bookmarks belong to the authenticated user it will be displayed. (Ref https://github.com/directus/api-docs/commit/cfeefeb0eeefb857831558441877f7d286d63ebb)

The bookmarks endpoint (`/bookmarks`) was fixed and it returns all the bookmarks for the current authenticated user. (Ref https://github.com/directus/directus/commit/451c104dfa0b87c5377288d6360c5f896f0f60c5)

We are going to keep inserting the "default" bookmarks as still has some reference in the app, but we would need to go over all these to get it right.

Thanks for the report!
