### ISSUE TITLE
Can't create a new user

### ISSUE THREAD

**Issue by ngirardhg** [directus/directus#1748]
## Version Info
  - Directus version and branch: 6.4.1 (Ruby rabbit)
  - PHP version: 5.6.30
  - MySQL version: 5.0.11
  - Web server: Apache (XAMPP)
  - OS name and version: Windows 7 pro service pack 1

## Expected Behavior
Trying to create a new user should create a new user

## Actual Behavior
Try to create a new user gives an error which says : "Group : this field is required". This error comes up even though the group is properly set. 

Here is a screenshot showing the error and the group set to "Administrator"
![new user](https://user-images.githubusercontent.com/31041083/29466599-74a9a71c-840b-11e7-8199-493be5ae604d.png)

## Steps to Reproduce
 1. Try creating a new user setting the last name, first name, email, password and group.

**Comment by rijkvanzanten** [comment]
Hi @ngirardhg. Thanks for the info! 

We believe this is related to https://github.com/directus/directus/issues/1737 which will hopefully be fixed in https://github.com/directus/directus/pull/1738. We'll keep you up to date on the progress here!

**Comment by WellingGuzman** [comment]
Hey @ngirardhg, I've made a fix for this specific issue while other issue related to this one will be resolved by #1738.

Closed by https://github.com/directus/directus/commit/d6e22883c1ad61ff04c125b0d06d75d224327592
