### ISSUE TITLE
Can not delete a column of type many-to-many

### ISSUE THREAD

**Issue by ngirardhg** [directus/directus#1749]
## Version Info
  - Directus version and branch: 6.4.1 (Ruby rabbit)
  - PHP version: 5.6.30
  - MySQL version: 5.0.11
  - Web server: Apache (XAMPP)
  - OS name and version: Windows 7 pro service pack 1

## Expected Behavior
Trying to delete a column of type many-to-many should delete the column

## Actual Behavior
Trying to delete a column of type many-to-many does not delete the column. Instead, an error message is displayed "column not removed"

Here is a screenshot of the behaviour : 
![column](https://user-images.githubusercontent.com/31041083/29476279-45f62c58-8431-11e7-9310-753ea4caa053.png)

## Steps to Reproduce
 1. Create a table 
 2. Put a many to many relationship field in it and set it up correctly
 3. Try to delete the column

**Comment by WellingGuzman** [comment]
Thanks @ngirardhg, I'm working on it

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/7001c121f811c147aecefd3ccb15330a34322353

This will be included in Directus next version (6.4.2)

**Comment by lastlink** [comment]
I just barely cloned the latest and launched it. I tried to create a many to many and it had the same yellow triangle and was unable to delete it

**Comment by rijkvanzanten** [comment]
(Just speculating here), but could it be possible that it blocks every interaction as long as the column isn’t set up properly? That’s unexpected and unwanted behavior of course, but could be what is going on here.

**Comment by lastlink** [comment]
Well I managed to save this column w/out a name & had to access the database directly to give the column a name. Then I was able to make some changes.
