### ISSUE TITLE
OAuth login is ignoring redirect URL

### ISSUE THREAD

**Issue by danielbuechele** [directus/directus#17493]
### Describe the Bug

When navigating to a particular URL of the app, while being logged out, the app should redirect to this URL after a successful login. This is usually done via the `redirect` query string. However, when using an OAuth provider, this is not happening and instead the user is redirected to the last page stored for their account.

The problem are these lines, where the searchParams are cleared: https://github.com/directus/directus/blob/main/app/src/routes/login/components/sso-links.vue#L55-L58

While I understand, the `?continue` param needs to be added to the URL, is there a reason the `redirect` param is removed?

### To Reproduce

1. Set up Directus to use an OAuth provider.
2. Head to `http://localhost:8055/admin/settings/data-model`, while not being logged in
3. See you are correctly redirected to `http://localhost:8055/admin/login?redirect=/settings/data-model`
4. Click the login button for your OAuth provider
5. Browser navigates to `http://localhost:8055/auth/login/<provider_name>?redirect=http://localhost:8055/admin/login?continue`
6. At this point the information where to redirect after the successful login is lost

### What version of Directus are you using?

9.22.3

### What version of Node.js are you using?

18.7.0

### What database are you using?

Postgres 13.9

### What browser are you using?

Chrome 109.0.5414.119 

### How are you deploying Directus?

locally

**Comment by u12206050** [comment]
Would probably need an additional cookie to track this, as the redirect url in the oauth flow is typically a particular value that has been added to the oauth provider as an "approved redirect" value.

**Comment by danielbuechele** [comment]
The `?continue` query param is for the redirect URL is added by directus and is not specific to the oauth flow, is it? This makes me think we should be able to add another query param with the redirect URL: `?redirect=/something&continue` or am I missing something here?

**Comment by Paiman-Rasoli** [comment]
Hi @danielbuechele , I have read the entire issue and recently fixed this bug, can I have a PR for this issue?

**Comment by rijkvanzanten** [comment]
This was fixed in https://github.com/directus/directus/pull/17939
