### ISSUE TITLE
Tabular layouts freeze when adding a datetime column

### ISSUE THREAD

**Issue by jacobrienstra** [directus/directus#17506]
### Describe the Bug

Whenever I try to add a `datetime` column to the tabular layout, it freezes things up such that I eventually have to reload the app.

I don't know why it freezes up exactly, because on 22.4 it doesn't even load the column values and just totally freezes up, while on 22.0 it does add the column, but there are errors in the console and eventually when trying to navigate back to the page in question, it hangs forever.....

BUT I do know the the cause: the `datetime` display is getting an empty array as a value, which it doesn't know how to handle. It's expecting null or a string. 

The culprit is this line: https://github.com/directus/directus/blob/1e824f7f2184b9c1c95bf8cee1f2b8a67111171e/app/src/layouts/tabular/tabular.vue#L296
For some godforsaken reason that returns `true` for an empty array, meaning when values aren't yet retrieved from the backend but the fields have changed and the table is eagerly trying to load them, this will return an empty array to the `render-display` element which causes this small bit of havoc. I added an empty array check on `matchingValues` and everything works smoothly now. 

### To Reproduce

I don't think you need anything fancy here: just use a tabular layout and use the + button to add a datetime column to it. 

### Errors Shown

```
RangeError: Invalid time value
    at format (chunk-SVH7MBRM.js?v=95da87c8:1040:11)
    at localizedFormat (localized-format.ts?t=1676332598802:4:10)
    at watch.immediate (datetime.vue?t=1676332598802:76:32)
```

```
Cannot read properties of null (reading 'emitsOptions')
...then a bunch of chunk files
```

### What version of Directus are you using?

22.4

### What version of Node.js are you using?

16.14.2

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

locally, Docker

**Comment by paescuj** [comment]
Is it a simple collection with a `datetime` field? What value is stored in this field (you can inspect it with the raw editor)?

**Comment by paescuj** [comment]
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Comment by jacobrienstra** [comment]
> Is it a simple collection with a `datetime` field? What values are stored in the items for this field (you can inspect it with the raw editor)?

Correct, just a simple collection with `datetime` fields. Specifically in my case it's the `date_created` and `date_updated` fields. The values returned are normal ISO strings that are parsed into Date objects by the display. 

There may be a race condition happening here that's harder to reproduce; when the list of fields to fetch is changed, it triggers a refetch of the items in `use-items.ts`, but while that's being fetched, the `fields` being changed ALSO triggers a re-render in the `tabular.vue` even if the new items haven't been fetched yet. So right here: https://github.com/directus/directus/blob/1e824f7f2184b9c1c95bf8cee1f2b8a67111171e/app/src/layouts/tabular/tabular.vue#L26-L32 
Tries to fetch values for the newly added column, but since that value isn't yet present in the `items` object, it returns `null`. Or at least, it should—because of the line I pointed out, it actually returns an empty array, which is incorrectly typed. Typescript can't catch it because of the dynamic nature of items here. 

Though whether you can reproduce it or not, the code I cited in the issue description is still faulty and should be fixed. It `matchingValues` (an array) is empty, the `getAliasedValue` function should return null, not an empty array.
