### ISSUE TITLE
Error creating M2O

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1750]
Creating a new M2O column/interface (in this case called `assign_to`) to the `directus_users` table (related with `directus_users.id`).  When clicking save you get the following error:

```
Error: Uncaught TypeError: Cannot read property 'options' of undefined
File: http://local.directus.com/app/core/UIView.js?bust=2745c2e4d303d2c5ccad30ee1885e5747a805f8d
Line:70
```

It does not open up the interface options (it looks like it tries to though).

**Comment by benhaynes** [comment]
When I manually try to save the M2O options, I get this:

```
Error: Uncaught RangeError: Maximum call stack size exceeded
File: http://local.directus.com/assets/js/libs/underscore.js?bust=2745c2e4d303d2c5ccad30ee1885e5747a805f8d
Line:811
```

**Comment by benhaynes** [comment]
OK, it seems to create columns with the newest changes pulled – but saving options shows "incomplete" icon even when complete:

![screen shot 2017-08-19 at 10 34 19 am](https://user-images.githubusercontent.com/522079/29487617-538eef1e-84ca-11e7-909a-00a332ce0a39.png)

But it is gone when you refresh the page (until you edit again)

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/536fc997368d81f9e6472f22fea642a72b4e1b18
