### ISSUE TITLE
Different data in the side panel than it actually is

### ISSUE THREAD

**Issue by koksikus** [directus/directus#17512]
### Describe the Bug

I noticed a very strange thing. Different data appears in the side panel than is actually in the record. Here in the example is the status.

https://user-images.githubusercontent.com/90528895/218816269-efb7110d-f771-4891-9740-c37618b401c9.mp4

### To Reproduce

create two collections and connect them with the M2M field. Enter in the settings in the interface and display to display the status and other fields.
Go to the first collection and select another record then click on one of the records of that field and a side panel will open as you can see in the video it shows a different status than it actually is. I had cases with other fields that, for example, did not display data even though they were entered.

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

16.18.1

### What database are you using?

MS SQL or MySQL

### What browser are you using?

Edge

### How are you deploying Directus?

locally

**Comment by koksikus** [comment]
sometimes it shows fine but next time it shows wrong again. This is only in the latest version of Directus, in the previous one it is displayed correctly.

**Comment by paescuj** [comment]
Did you also configure a display template for the collection itself?
<img width="550" src="https://user-images.githubusercontent.com/5363448/218997923-2805c649-31dc-48fc-986d-102beef0a32d.png">

> This is only in the latest version of Directus, in the previous one it is displayed correctly.

Do you remember which version you've used before? Nothing has changed in this regard from 9.22.3 to 9.22.4.

**Comment by koksikus** [comment]
It wasn't set, but when I changed it didn't change much. I installed 9.22.0 and as you can see on the same data works properly. 

https://user-images.githubusercontent.com/90528895/219069766-2ac7fcee-ec47-4ba6-8aa1-845b6124c788.mp4

When I restored the latest version, the error returned. At the end of the video, you can see how the right data is displayed - and that's because I jumped between browser tabs.


https://user-images.githubusercontent.com/90528895/219070436-bcf8d302-8e08-4a35-b209-a3043b5459ef.mp4

**Comment by paescuj** [comment]
Would you be able to provide a schema / database snapshot?

**Comment by koksikus** [comment]
Here is the data from the database. This is a local version that is used for testing, so the data is fictitious.
On the production version, I have a different symptom - it first displays what is shown in the video, but in about a second it changes to the correct data.
[directus-sql.zip](https://github.com/directus/directus/files/10794614/directus-sql.zip)

**Comment by paescuj** [comment]
Thank you!

> On the production version (MS SQL), I have a different symptom - it first displays what is shown in the video, but in about a second it changes to the correct data.

Are there any relevant differences between the local and the productive environment?

**Comment by koksikus** [comment]
In the test version there are more different fields and collections to check the behavior  in case if you need to add other fields.

**Comment by koksikus** [comment]
Hi, were you able to replicate this situation?

**Comment by paescuj** [comment]
Not yet and [unfortunately, we can not provide any estimates on this](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍

**Comment by koksikus** [comment]
In the latest version it still occurs

**Comment by koksikus** [comment]
I tested it in the latest version 9.23.1 and it works fine. Maybe it was due to some bug like administrator permissions...
