### ISSUE TITLE
Upload to File Library when default directory is set

### ISSUE THREAD

**Issue by dr-wahrheit** [directus/directus#17518]
### Describe the Bug

I noticed that with the default directory set if I upload directly from the root of the "File Library" (/admin/files) the default directory for the file just uploaded is not set.

Maybe that's the desired behavior, but I have some concerns...

### To Reproduce

1. Create a folders A
2. In "Project Settings", under "Files & Storage", set default folder to A.
3. Upload a file to File Library
4. File is now on File Library but not in Folder A

### What version of Directus are you using?

on branch main

### What version of Node.js are you using?

v18.13.0

### What database are you using?

SQLite 3.39.4

### What browser are you using?

*

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
Great question. I'm not sure if this is something that we should "Fix". The current behavior of the drag and drop upload in the file library is that it uploads to the folder you're currently in. Therefore, dropping a file to the root of the file library should still upload to the root folder of the file libary.

That being said, I do think that a "correct" fix here would be to open the configured default folder whenever you navigate to the file library 🙂

**Comment by dr-wahrheit** [comment]
It's an intriguing problem...

The way I see it, I would have expected since it's called "default folder" that:

1) uploading a file to a specific folder sets that folder as the file's folder
2) uploading a file to the root sets the default folder as the file's folder

Unless, as you say, the default folder is just a matter of display; but in this case the check done on the API side doesn't make much sense.

https://github.com/directus/directus/blob/main/api/src/services/files.ts
<img width="971" alt="immagine" src="https://user-images.githubusercontent.com/1035931/219053321-d696256b-0ff2-4503-bc59-f4426fbd339f.png">



Also because, but maybe I'm wrong, from what I've seen the check above will never be true for uploads made via admin. The folder property is always present.

**Comment by rijkvanzanten** [comment]
I disagree on the second point:

> uploading a file to the root sets the default folder as the file's folder

The root itself is also a presented / treated as a folder, so uploading a file to the root folder should still be possible IMO

> Also because, but maybe I'm wrong, from what I've seen the check above will never be true for uploads made via admin. The folder property is always present.

Not through the admin, correct. The admin app isn't the only usage of the API though 🙂

**Comment by paescuj** [comment]
I see two possibilities:
- Open the configured default folder whenever you navigate to the file library, as suggested by @rijkvanzanten 
- Change the description of the option so that it is clear that only the API is affected by it
