### ISSUE TITLE
Self-Hosted Docker instance crashing on webp file upload

### ISSUE THREAD

**Issue by FlorianB-DE** [directus/directus#17513]
### Describe the Bug

Directus container crashes on webp upload.

### To Reproduce

- `docker run -p "8055:8055" -e KEY=your-key -e SECRET=your-secret directus/directus:9`;
- open localhost:8055 in browser and login;
- go to file library and add file;
- i tested multiple webp files but [this](https://media.gettyimages.com/id/1263307689/de/foto/junge-frau-mode-stil-junge-ziemlich-modische-m%C3%A4dchen.webp?s=2048x2048&w=gi&k=20&c=ZCsh0Nl1SPQRWxHPhyR4Nn2bPoCeaKgiXrVy_KcxZe4=) should do the trick: https://media.gettyimages.com/id/1263307689/de/foto/junge-frau-mode-stil-junge-ziemlich-modische-m%C3%A4dchen.webp?s=2048x2048&w=gi&k=20&c=ZCsh0Nl1SPQRWxHPhyR4Nn2bPoCeaKgiXrVy_KcxZe4=
- directus container crashes

### Errors Shown

```
/directus/node_modules/exif-reader/index.js:8
      throw new Error('Invalid EXIF data: buffer should start with "Exif", "MM" or "II".');
            ^

Error: Invalid EXIF data: buffer should start with "Exif", "MM" or "II".
    at module.exports (/directus/node_modules/exif-reader/index.js:8:13)
    at Object.<anonymous> (/directus/node_modules/directus/dist/services/files.js:152:103)
```

Node.js v18.13.0

### What version of Directus are you using?

9.22.3

### What version of Node.js are you using?

Default in container (v18.13.0)

### What database are you using?

Postgres 15, SQLite (container default)

### What browser are you using?

Firefox 109.0.1 (64-Bit)

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
Can you share the `webp` file that causes this?

**Comment by FlorianB-DE** [comment]
@rijkvanzanten i shared a link in step 4 of "To Reproduce". In fact any of the images I downloaded there didn't work. I do not own the Image so I'd rather not upload it anywhere.
In the UI it only says:
```
{
  "stack": "X@http://localhost:8055/admin/assets/use-sync-7318fa3d.js:27:18531\nH0</</R.onerror@http://localhost:8055/admin/assets/use-sync-7318fa3d.js:29:4378\n",
  "message": "Network Error",
  "name": "AxiosError",
  "code": "ERR_NETWORK",
  "config": {}
}
```

**Comment by rijkvanzanten** [comment]
Ah my bad, didn't notice the small `this` link 🙂
