### ISSUE TITLE
Add package extensions path to env variables

### ISSUE THREAD

**Issue by nfjodor** [directus/directus#17524]
### Describe the Bug

Currently, I'm working on a project that uses Directus as a thin client with Electron.
The idea comes from my company and my private project.
We host a database somewhere (it is very easy and cheap). Then the Directus clients (executable application) can connect to this database.
I'm almost done but I have a problem. When I'm compiling the application with Electron, Directus wants to load package.json from the wrong place. As I saw I can manage a lot of things from `.env` but the allowed packages for Directus Flows isn't working because the path of package.json is hardcoded in `api/src/extensions.ts` file.

### To Reproduce

Clone this repository: https://github.com/nfjodor/directus-electron
Then checkout to initial commit: `git checkout 55d88536a3983134ad6ef7d6c69165c19b736e70`
Then run `npm i && npm run package`
Then run the electron app from `out` folder.
Then see the console, an error happens and Directus Flows couldn't load the packages (in this case the fs-extra package).
If you wan't to test it, the example admin user is norbi.boci@gmail.com and the password is 123456
After that, you need to edit the created Flow to trigger collections Release and Version.

### Errors Shown

Error: Current folder does not contain a package.json file
![image](https://user-images.githubusercontent.com/6689221/220381117-5b67c282-4b7d-4fc7-aaa2-0bbf95162902.png)

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

not relevant

### What database are you using?

not relevant

### What browser are you using?

not relevant

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
> Directus wants to load package.json from the wrong place

Where? Directus relies on Node's regular resolution if I'm not mistaken, so it expects `node_modules` to live next to the `package.json` file of the project 🤔

**Comment by nfjodor** [comment]
After the electron build you can run the application from anywhere, for example by a shortcut on the desktop. In this case, the `path.resolve('.')` returns the actual folder you are in which isn't contain the `package.json` file and `node_modules` folder.
You're right in the PR, Directus electron support is out of scope, I just created the pull request because I saw the hardcoded value and I gave it a chance, maybe it can be removed/modified in the future because this issue can cause problems in the future in other Directus related projects too.

If you think that this is not an issue (which I totally understand) you can close this bug and the connected pull request. My project can be done without this modification because I can use a patch file after `npm install` and the electron app can work too. Then in the future, if electron support can be an option, this issue will be fixed if it still exists.

**Comment by rijkvanzanten** [comment]
@nfjodor Are you aware of any other major blockers for Electron? If this is the only real blocker preventing people from going forwards, I'm willing to go with your proposed fix, just wanna make sure it's not a "pointless" addition if then 10 other things are still blocking you (in which case I'd rather put it together as a bigger _lets support electron_ sprint)

**Comment by nfjodor** [comment]
Thank you for your response. Tomorrow I will check all Directus features. As I saw this was the only thing that isn't working. So, I'll be back tomorrow.
I will try it with different databases and mail providers too.

**Comment by nfjodor** [comment]
Sorry for the late, the test took longer than I thought. The final result is no other modification is needed to work every feature with electron.
The only thing is I need to modify the mail templates to put a custom URL scheme but the Directus gives me the ability to change mail templates, so it will be my task not relevant to you!

_Off: As I saw the Directus codebase I love this project more than before 💜. Modular, and easy to customize, I love it!_

**Comment by rijkvanzanten** [comment]
Thanks for checking @nfjodor! Glad to hear that's the only blocker. In that case, lets go ahead and get that PR merged 🙂 

> Off: As I saw the Directus codebase I love this project more than before 💜. Modular, and easy to customize, I love it!

Thanks! ❤️ Lot of hard work to keep it maintainable over time 🙂

**Comment by nfjodor** [comment]
I close this issue because it is fixed in this PR: https://github.com/directus/directus/pull/17525
