### ISSUE TITLE
Custom interfaces not found on page refresh

### ISSUE THREAD

**Issue by aaronaustin** [directus/directus#1753]
## Version Info
  - Directus version and branch: 4886be3
  - PHP version: 7.0.22-0ubuntu0.16.04.1
  - MySQL version: 5.7.19-0ubuntu0.16.04.1
  - Web server: Apache
  - OS name and version: Ubuntu 16.04

## Expected Behavior
Custom interfaces should load and be available even after refresh.

## Actual Behavior
Custom interfaces load after cache is cleared.  Upon refreshing the page, the following error is produced in forms: `You are missing the interface: ******` .  My custom interfaces were working fine in 6.4.0.  Only after updating to 6.4.1 did this begin. This behavior is consistent on my web server as well as my local MAMP server.

## Steps to Reproduce
 1. Add custom interface to table.
 2. Refresh app.
 3. Navigate to edit and item.
 4. Error should trigger.
 5. Clear browser cache.
 6. Custom interfaces available again.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/743590035352c0094f6d03815af1ed5b81c0f703

Please confirm this worked for you too.

We've also updated the build branch.

**Comment by aaronaustin** [comment]
Works great!  Thanks!
