### ISSUE TITLE
Temporary revocation of admin rights

### ISSUE THREAD

**Issue by Zaelot** [directus/directus#1754]
## Version Info
  - Directus version and branch: 6.4.1
  - PHP version: PHP 7.1.8
  - MySQL version: MariaDB 10.1
  - Web server: Apache
  - OS: Debian Jessie

## Expected Behavior
Changing Group permission description and saving the settings returns to the **Admin Settings** screen.

## Actual Behavior
Gives error message "You don't have permission to view that page or it doesn't exist." and throws back to /tables. Admin Settings option also disappears from the user menu. (Returns after visiting user profile page.)

## Steps to Reproduce
 1. (The Directus was just updated from 6.3.6, so the Users and Group permissions already existed.) Log in with a secondary admin account.
 2. Go to **Admin Settings** > **Group Permissions** > pre-existing group
 3. Write something in the previously empty "Description" field. Save from the right upper corner. 

## Schema Dump, Logs, or Screenshots
![image](https://user-images.githubusercontent.com/2608781/29615360-5472f174-8816-11e7-964e-76d8ad73728b.png)

**Comment by WellingGuzman** [comment]
Hey @Zaelot, this issue has been closed by https://github.com/directus/directus/commit/0bcc86bdd85c846ab60b4a12bc8a8e5a84e1446f

Please confirm us it does works for you.
