### ISSUE TITLE
Question - How to show notifications on hook error

### ISSUE THREAD

**Issue by Radiergummi** [directus/directus#1755]
## Version Info
  - Directus version and branch: 6.3.9
  - PHP version: 7.0.8
  - MySQL version: 5.5.55
  - Web server: nginx
  - OS name and version: Debian 8

I'm using Directus as a CMS for a static site. As soon as a table is changed, my hook starts gulp in a shell_exec that rebuilds the site and pushes the files to the webserver.  
That is all well, but of course, there could be situations where the build fails because of some reason - say, because the handlebars templates (which are kept in a Directus table) contain an error or have been deleted, or a file is missing, etc.  
This is usually very well covered by gulp, which writes a meaningful message to the command output about what went wrong, but that's pretty useless unless the user learns of it.  

So, I'm almost sure there is a way to hook into Directus' notifications, and I apologize if I have overlooked it in the docs, and I would be glad if you could point me in the correct direction here.

**Comment by WellingGuzman** [comment]
Do you want to throw errors on Directus? you can throw exception using php and the webapp will catch it.

for example:

```php
$somethingWentWrong = true;
if ($somethingWentWrong) {
    throw new \Exception('something went wrong');
}
```

Let me know if this is something it works for you, and we will document it for future usage.

**Comment by WellingGuzman** [comment]
this wasn't an issue I'm going to close it! but we can still discuss how to implement this, if the above didn't work.

**Comment by Radiergummi** [comment]
Hey @WellingGuzman I'm sorry I didn't respond yet, there was just too much stuff going on. Thank you for the explanation, throwing exceptions sounds good.
