### ISSUE TITLE
Filter option not available for the field which has O2M relation with another table

### ISSUE THREAD

**Issue by ntsh999** [directus/directus#17551]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

I have 2 collections. Events and Event_Bookings. An event can have multiple bookings hence a O2M relationship between Events.bookings and Event_Bookings.event. I want to apply a filter on Events.booking so that only the booking matching the criteria in the filter are shown. However, I do not get an option to apply filter on the field. The filter option is usually available in the interface menu which appears in the edit field option. How can I get the filter option in this case? I am using directus v9.21.2

![filter-1](https://user-images.githubusercontent.com/29781097/219347152-bf604069-63f3-409d-944b-6ef91dacdd01.PNG)
![filter-2](https://user-images.githubusercontent.com/29781097/219347613-fcf3d296-93e8-4762-8c51-0d860bf8174b.PNG)

The filter, I am expecting.

![filter-3](https://user-images.githubusercontent.com/29781097/219347653-721eac6c-485b-438c-8f2f-aadf1594c887.PNG)

### To Reproduce

Create 2 collections. Events (fields: id(PK), name, bookings etc) and Event_Bookings (fields: id (PK), event, status etc). An event can have multiple bookings hence create a O2M relationship between Events.bookings and Event_Bookings.event. I want to apply a filter on Events.booking so that only the booking matching the criteria in the filter are shown. 

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
It seems like this has been fixed in the meantime, so I'll close this for now. Please upgrade and try with a newer version (latest is currently v9.22.4).
If you think this is actually still an issue, then please do not hesitate to comment.
