### ISSUE TITLE
Displaying relations M2M was lost

### ISSUE THREAD

**Issue by dsivokhin** [directus/directus#1756]
## Version Info
  - Directus version and branch: 6.4.2 master
  - PHP version: 7.0
  - MySQL version: 5.7
  - Web server: nginx
  - OS name and version: ubuntu 16.04

## Actual Behavior
after update to 6.4.2 version, displaying relations M2M was lost. I'm clear cache, but nothing displaying.

## Schema Dump, Logs, or Screenshots

![1](https://user-images.githubusercontent.com/4669992/29625284-f1567e58-8833-11e7-97f6-726bd3f3a12f.PNG)
![3](https://user-images.githubusercontent.com/4669992/29625283-f152e2d4-8833-11e7-87fa-600120e9fc72.PNG)
![4](https://user-images.githubusercontent.com/4669992/29625459-68bcac1a-8834-11e7-8eaa-8a587e302ae8.png)

[Dump20170823.zip](https://github.com/directus/directus/files/1246071/Dump20170823.zip)

**Comment by benhaynes** [comment]
Thanks Dmitry – @WellingGuzman is aware of this and in the process of releasing a hotfix.

**Comment by WellingGuzman** [comment]
Hey @dsivokhin,

can you give it another try on `develop` branch?

This was closed by https://github.com/directus/directus/commit/3d7225c1ff05dd3ff1d0acd83515a0f71ccf2841

**Comment by dsivokhin** [comment]
Hello @WellingGuzman, thank you, it's works for M2M. But the same problem with M2O Dropdown. Value isset in DB, but not checked in selector, displaying 'Please select an option'

**Comment by WellingGuzman** [comment]
Hey @dsivokhin can you provide a schema so we can test this with? I tried with the latest code (6.4.2) and it seems to be working.

Thanks!

**Comment by dsivokhin** [comment]
@WellingGuzman, sorry, it's not error, i understood. In M2O Dropdown only 50 `option` load by api limit, in my DB table 150 items, not all `option` load. It's bug or feature ?
