### ISSUE TITLE
Set Mapbox Access token as env

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#17567]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

Right directus allows to set a Mapbox API token in the settings. I think security wise it should also be possible to set the token as an env variable instead. In this case the input field in the app should be disabled.

### To Reproduce

n.A

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
Thanks for opening this issue! However, this should be a new feature request.
Please create one over here: https://github.com/directus/directus/discussions/new?category=feature-requests
Thanks again!
