### ISSUE TITLE
Any edit to an insights board results in error

### ISSUE THREAD

**Issue by davidnixon** [directus/directus#17571]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

1. Self hosted Directus on IBM Cloud (but it looks like this can be reproduced on Google cloud as well)
2. Edit an insight board and save
<img width="541" alt="image" src="https://user-images.githubusercontent.com/7536103/219878550-849ebb3a-cc77-43a4-89df-1ce19a3d35ef.png">

I think there are at least 2 bugs here depending on how you count.
1. `app/src/stores/insights.ts` does this check before issuing create/update/delete `if (edits.create)` or `if (edits.update)` or `if (edits.delete)` these checks always return true because and empty array is truthy.
2. `api/src/controllers/panels.ts` has this code for delete:
```ts
if (Array.isArray(req.body)) {
await service.deleteMany(req.body);
} else if (req.body.keys) {
await service.deleteMany(req.body.keys);
} else {
await service.deleteByQuery(req.body.query);
}
``` 
Unfortunately the body received by the server is empty so its not an array, it does not have a "keys" value, and it does not have a "query" value but `deleteByQuery` is called anyway and the error above is shown.

Why is there no body to the DELETE request? There is an interesting [stack exchange](https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request) on this topic but the short answer is that the body is removed by the routing before it gets to the server. So the browser is definitely sending a body but the server is definitely NOT getting it.

So the issue is with delete but because of (1) above the error always happens because delete is always called even if there is nothing to delete. 

Working on a PR ...

### To Reproduce

Edit any Insight on a self-host cloud instance.

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
How can this be reproduced?

**Comment by paescuj** [comment]
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Comment by davidnixon** [comment]
You have to deploy on a cloud that does not allow a body in a DELETE. Looks like that IBM & Google at least. Have not checked Amazon.

**Comment by davidnixon** [comment]
I cannot reproduce now either :-( . I missed something.  digging into it some more.

**Comment by davidnixon** [comment]
I'm trying to confirm with the net work team but it looks like it might be an cdn setting that is stripping the delete body before it reaches the server.
