### ISSUE TITLE
Get row with "Single File" field by API only returns the file id instead of file data

### ISSUE THREAD

**Issue by diegogurpegui** [directus/directus#1757]
Not sure if this should be considered as a new feature, or an issue (since it worked in API v1.1).

## Version Info
  - Directus version and branch: 42ce2f23863da0073a59b0e6878d8cf65472e773
  - PHP version: 7.1
  - MySQL version: 5.6+
  - Web server: Apache
  - OS name and version: 64bit Amazon Linux 2016.09 v2.3.3 running PHP 7.0

## Expected Behavior
When a row data is returned from the API, the Single File field should return the entire File data.

## Actual Behavior
When a row data is returned from the API, the Single File field returns only the file id.

## Steps to Reproduce
 1. Define a table that has a "Single File" field
 2. Pull a row (or rows) from the API
 3. See that the field for the "Single File" returns only the file ID.

## Schema Dump, Logs, or Screenshots
(not applicable)

**Comment by WellingGuzman** [comment]
Hey @diegogurpegui, by default you are getting the first "level" of nested data.

How Directus work now, is that you can say how many levels of related data you want to fetch, by default the `depth=1` which means any related data on the requested table (first level) will be included.

So updating `depth` to match the how many levels you want to include, if that's what wrong, this is a documentation issue, we need to make this clear.

Otherwise, if that doesn't work, please share a schema that we can use to reproduce.

Thanks for reporting this issue.

**Comment by diegogurpegui** [comment]
Thanks @WellingGuzman !
We didn't know about the "depth" query parameter, I personally didn't see it documented anywhere.

We just tried it and seems to be working as expected. It's exactly how I would expect this to be solved, in a very flexible way.
We'll start using it more and get back here if we find anything.

Thanks

**Comment by WellingGuzman** [comment]
Awesome @diegogurpegui, we are going to implement in a dot notation feature so you can pick what columns you want to pick, more in #1419.

**Comment by diegogurpegui** [comment]
That sounds awesome @WellingGuzman

**Comment by CodexAnima** [comment]
Hey awesome directus team!
I need this one reopened.

More than a year later, I have the same problem in just getting the image id from a "file" field but need the url instead.

I tried the `?fields=*,header_image=*` where "header_image" is my named "file" field. The output is only nesting the id like `header_image":{"id":4}}`. I tried with another field called tag, a relational field to another list collection and the nesting data is correct.

The whole is requesting from a public state, no access token.

`https://domain.tld/subfolder/apifolder/public/_/files/4` in browser get `{"error":{"code":203,"message":"Item not found"}}`,
`https://domain.tld/subfolder/apifolder/public/_/files` responses with `{"error":{"code":300,"message":"Reading items from \"directus_files\" collection was denied"}}`.

That is ok, no public should enter my files.

But I need the url from the related image in the collection like `https://domain.tld/subfolder/apifolder/public/uploads/_/originals/related_image.jpg`.

That source is accessible from public browser.


Keep on rocking,
Matthias
