### ISSUE TITLE
wysiwyg editor nested list (ul/ol) doesn't work

### ISSUE THREAD

**Issue by gauravkrp** [directus/directus#17579]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

For some of my content, I would want to nest a list inside another. For example, let's say an unordered list inside two of the items in an ordered list. After starting my parent list, when I switch to nesting for child content, everything messes up.

### To Reproduce

Try creating a list inside the another in the WYSIWYG rich content editor field 

<img width="855" alt="Screenshot 2023-02-21 at 3 55 58 AM" src="https://user-images.githubusercontent.com/12250556/220207148-7e30cde7-78e4-4a0f-81a7-30f89b2f6cc2.png">

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

https://user-images.githubusercontent.com/5363448/220307189-5d8918c9-d2b5-4571-9805-97b5703b361c.mp4
