### ISSUE TITLE
Toggles not displaying in list views

### ISSUE THREAD

**Issue by awbranch** [directus/directus#1758]
## Version Info
  - Directus version and branch: 6.4.2 - 3d7225c
  - PHP version: 5.6.30-12
  - MySQL version: 5.7.19 
  - Web server: Apache 2.4.18
  - OS name and version: Ubuntu 16.04.2

## Expected Behavior
When I add a column of type toggle to the table list view I would expect to see some representation of its value.

## Actual Behavior
There is no indication of the checkbox. It looks like a styling issue. I can see in the DOM that there is an input and its checked attribute is true, but the class "custom-checkbox" has the CSS style "display: none". Looking in main.css:627 has the following style which is hiding the checkbox:

```
input[type="checkbox"].custom-checkbox,
input[type="radio"].custom-checkbox {
display: none; }
```

## Steps to Reproduce
 1. Add a table with a toggle field.
 2. Add a record with the toggle checked to true.
 3. View the record in the list view

## Schema Dump, Logs, or Screenshots
![screen shot 2017-08-23 at 5 38 16 pm](https://user-images.githubusercontent.com/108669/29639845-3415c604-882a-11e7-9818-8a3d266ef705.png)

**Comment by rijkvanzanten** [comment]
Hey @awbranch, thanks for the heads up. I have fixed the issue in https://github.com/directus/directus/commit/9f19567dade2bc8f25eca79caa5ad1e745e0237e on the ![develop](https://github.com/directus/directus/tree/develop) branch. It will be merged into master soon.

**Comment by awbranch** [comment]
Tested and working on the develop branch.
