### ISSUE TITLE
advanced search on a collection overview is not working anymore

### ISSUE THREAD

**Issue by pitstampfli** [directus/directus#17591]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

With upgrade to cloud hosted version 9.22.4 the advanced filtering does not work any more.
First it takes 5+ seconds to appear

![image](https://user-images.githubusercontent.com/106923100/220530751-15420a03-977d-45bc-a949-aedc2768d9b7.png)

During this time the whole application freezes.

Than the searchable field do not show.

### To Reproduce

is happening always

### Hosting Strategy

Directus Cloud

**Comment by br41nslug** [comment]
I am unable to reproduce this on a Cloud Demo instance with the given steps. Could you provide extra context on the collection that is creating this situation? Like does it have a huge amount of fields, or translations etc.

If you think this could be specific to your cloud instance you can get cloud support by filling out this form https://share.hsforms.com/1Kuu-0jHIRYGd2cYSbofC_Ac8497

**Comment by pitstampfli** [comment]
Hi

I requested a access a cloud support using the link.

We have two Problems:

   1. Advanced Filtering does not work
   2. Cannot change the columns in table view.

If I try to do the one above - the system freezes for 5+ seconds.

*Both is a very critical production issue for our business!*

Here an example with collection ProjectAssignement:

   - The collection has fairly lot of fields: with lots of relations (O2M,
   M2O --> no M2M or M2A) see screen shot
   - The number of actual records ist very low (<100)
   - No translsations

With the old Version, there never was a problem with this Filtering and
Adding of Fields.

*What I just found out is that with a smaller Collection - there is no
Problem (see Collection Config)*


[image: image.png]
[image: image.png]

*What I just found out is that with a smaller Collection - there is no
Problem:*
[image: image.png]

**Comment by pitstampfli** [comment]
Here the exception out of the browser!

runtime-core.esm-bundler-ba53435f.js:1 RangeError: Maximum call stack size exceeded
    at Object.get (runtime-core.esm-bundler-ba53435f.js:1:7091)
    at Proxy.filter (<anonymous>)
    at Proxy.getRelationsForCollection (index.dcecc29f.entry.js:22:6727)
    at Proxy.<anonymous> (pinia.7a285ab5.entry.js:5:2318)
    at Proxy.getRelationsForField (index.dcecc29f.entry.js:22:7200)
    at Proxy.<anonymous> (pinia.7a285ab5.entry.js:5:2318)
    at m (index.dcecc29f.entry.js:27:46577)
    at p (index.dcecc29f.entry.js:27:46102)
    at f (index.dcecc29f.entry.js:27:45355)
    at index.dcecc29f.entry.js:27:45255

**Comment by pitstampfli** [comment]
If you cant solve it quickly - please roll back to old version

**Comment by br41nslug** [comment]
After a ton of testing I was able to reproduce this by creating a self-referencing m2o relation in a group.

**Comment by pitstampfli** [comment]
Thanks awesome! When will be the delivery to my cloud instance?

**Comment by pitstampfli** [comment]
thank you all for your extra efford to solve this issue. It all looks good now from our side!

**Comment by paescuj** [comment]
> thank you all for your extra efford to solve this issue. It all looks good now from our side!

Great, thanks for your positive feedback!
