### ISSUE TITLE
Permission Error when opening an item from a Files item

### ISSUE THREAD

**Issue by LevinGermann** [directus/directus#17597]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

I basically want to re-open the issue mentioned here (https://github.com/directus/directus/issues/17514) which got converted into a discussion.

It's possible to view the item without any problems, there's just a misleading popup saying that there was a permission issue.

`GET /items/trail_files/87ca8207-4cd2-4282-a0cf-26fa2ed891c6 403 31ms`

The issue here is that it tries to access an item from trail_files, but the collection has a regular int as a primary key, not a UUID (which is probably the directus_files uuid)

I attached a db dump here: 
[data.db.zip](https://github.com/directus/directus/files/10807028/data.db.zip)

admin@example.com / password

### To Reproduce

1. Create a new collection
2. Create a new field as a files type.
3. Create a new record of created collection
4. Add a new file, save the item. Reopen it and try to click on the item
5. Permission error

https://user-images.githubusercontent.com/9347206/220721349-dfc76843-e006-4643-b97d-b51b8d654ebe.mov

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by azrikahar** [comment]
> The issue here is that it tries to access an item from trail_files, but the collection has a regular int as a primary key, not a UUID (which is probably the directus_files uuid)

Can confirm this is the underlying bug discovered in #17108 👍 I'll proceed to close this as a duplicate.
