### ISSUE TITLE
Text input size widths are ignored

### ISSUE THREAD

**Issue by awbranch** [directus/directus#1760]
## Version Info
  - Directus version and branch: 6.4.2 - 3d7225c
  - PHP version: 5.6.30-12
  - MySQL version: 5.7.19
  - Web server: Apache 2.4.18
  - OS name and version: Ubuntu 16.04.2
  - Browser: Chrome  60.0.3112.90

## Expected Behavior
  When setting a Text Input columns interface options "Size": field you can select "Small", "Medium" or "Large". I expect that when the field is displayed in the edit view that they be different sizes based on this setting.

## Actual Behavior
They are always the same size regardless of the setting. 

## Steps to Reproduce
 1. Create 3 text columns in a table.
 2. Set their respective sizes in the interface options to Small, Medium and Large
 3. Add a new record for this table. Notice that all the text fields are the same size.

This appears to be a styling issue. 

## Schema Dump, Logs, or Screenshots

![screen shot 2017-08-23 at 6 21 32 pm](https://user-images.githubusercontent.com/108669/29641198-70d0460e-8830-11e7-83fd-6ddb68752a83.png)

![screen shot 2017-08-23 at 6 26 20 pm](https://user-images.githubusercontent.com/108669/29641309-fb8fa06e-8830-11e7-9b81-c16e2aaa25d9.png)

**Comment by benhaynes** [comment]
Good catch! We've been overhauling the interfaces and this must have been missed.

@rijkvanzanten these sizes should be standardized across all interfaces so that small/medium/large represents the same max-width values and interfaces still align vertically. Some CSS edge-cases may be required for "visual alignment" if there is a more complex interface.

**Comment by rijkvanzanten** [comment]
Ah yes! Missed this.. This might also a great moment to add in the `auto` option which used the value of `length` to set the width @benhaynes

**Comment by rijkvanzanten** [comment]
This has been fixed/implemented in #1762 on the [develop](https://github.com/directus/directus/tree/develop) branch and will hit master/release soon.
