### ISSUE TITLE
Column order not maintained after editing 2nd column

### ISSUE THREAD

**Issue by awbranch** [directus/directus#1761]
## Version Info
- Directus version and branch: 6.4.2 - 3d7225c
- PHP version: 5.6.30-12
- MySQL version: 5.7.19
- Web server: Apache 2.4.18
- OS name and version: Ubuntu 16.04.2
- Browser: Chrome 60.0.3112.90

## Expected Behavior
When editing column attributes I would expect the ordering of the columns to be maintained.

## Actual Behavior
If I edit just one column the order doesn't change, but if I edit a 2nd column things start to shift around. 

## Steps to Reproduce
 1. Add a new table
 2. Add 4 Text Input fields named "Foo", "Bar", "Bizz", "Buzz"
 3. Click on "Foo" and Click the "Interface Options" tab and set the size to "Medium"
 4. Click on "Bizz" and Click the "Interface Options" tab and set the size to "Medium"
 5. Notice that the order of the columns is now: "Bar",  "Bizz", "Buzz", "Foo"

## Schema Dump, Logs, or Screenshots
![screen shot 2017-08-23 at 6 56 45 pm](https://user-images.githubusercontent.com/108669/29642126-08766af2-8835-11e7-9dd7-062678fbfbd7.png)

**Comment by benhaynes** [comment]
Thank you for these steps @awbranch – we were experiencing this before and @WellingGuzman had submitted a fix that resolved it... but it seems you've found a new way to find this issue.

We're on it!

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/11d35eb78bc2244aa7e75f09819f480bb1bab49a

**Comment by WellingGuzman** [comment]
Hey @awbranch thanks for reporting this bug, please let us know if that commit fixes the issues for you too.
