### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by mutweb** [directus/directus#17614]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

[INTERNAL_SERVER_ERROR] alter table "contactus" drop column "options" - relation "contactus" does not exist

### To Reproduce

create field relationship and delete hidden table

### Hosting Strategy

Directus Cloud

**Comment by paescuj** [comment]
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻
