### ISSUE TITLE
Password issue on Directus Cloud for a single user

### ISSUE THREAD

**Issue by artecoop** [directus/directus#17628]
### Checklist

- [ ] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [ ] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

Hello all!
I have a project on the free tier in the directus cloud service that have a problem with it's password. Since some days, after a number of hours between 12 and 24 the password seems to expire for a single user. It happened to the main admin account also, but just for a few times. Changing the password solves the problem for the current window of hours.
I've already opened a pair of tickets with the directus cloud support, but for both of them William Friedman, the good man who investigated my issues, verified that they cannot reproduce the problem, nor seeing any strange issue in the logs. So, he suggested me to open this ticket.

For some reason, the project is not updated to the latest version (currently 9.21.2), and seems to not be paused anymore, since the dashboard says: "This project will be paused on Feb 14, 2023 at 8:41 AM" but we're way past that date.

### To Reproduce

Me too cannot reproduce this problem on a local installations. Seems related to this project alone, at least for the ones I manage.
Being in the Directus Cloud infrastructure, I have no access

### Hosting Strategy

Directus Cloud

**Comment by paescuj** [comment]
Heya! Thanks for the heads up. This seems like a cloud specific issue so I'll pass this along to our cloud team as they will be more suited to look into this matter 👍🏻

For future inquiries or issues specific to Directus Cloud projects, please reach out through [the Live Chat in our Cloud Dashboard](https://directus.cloud/) as that's the best channel to get help with your Cloud projects 🙂 (That's what the support team meant)
