### ISSUE TITLE
Unnecessary "This field is required" warnings on required Date, Dropdown and Toggles columns

### ISSUE THREAD

**Issue by awbranch** [directus/directus#1763]
## Version Info
  - Directus version and branch: 6.4.2 - 3d7225c
  - PHP version: 5.6.30-12
  - MySQL version: 5.7.19
  - Web server: Apache 2.4.18
  - OS name and version: Ubuntu 16.04.2
  - Browser: Chrome 60.0.3112.90

## Expected Behavior
When creating a new record with columns such as Dates, Dropdowns or Toggles the fields are populated with default values such as the current date, the first item in the drop down or a false value respectively. If these fields are required I would expect that I would not have to edit them if the default was what I wanted.

## Actual Behavior
If you don't edit these fields, Directus seems to think that they are empty and since they are required it will display a required field warning. This is confusing. You have to make an edit from the default to clear the error.

This could be a problem with more field types, I haven't tested them all.

## Steps to Reproduce
 1. Create a table with 3 columns, date, dropdown & toggle.
 2. Set them all to required.
 3. Create a new record and accept the default values.
 4. You will see an error when trying to save.

## Schema Dump, Logs, or Screenshots

![image](https://user-images.githubusercontent.com/108669/29678889-43901f7c-88ce-11e7-811e-b2ef08e52eff.png)

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/1d6fb81e13483ae7ae031487edc585476ccd8c5b

Please @awbranch confirm this patch, otherwise I will re-open the ticket.
