### ISSUE TITLE
Filtering by `_empty` in the "Read data" operation errors with `INVALID_QUERY`

### ISSUE THREAD

**Issue by ferretwithaberet** [directus/directus#17635]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

When using the `_empty` filter in the "Read data" operation the response is:
```json
{
  "status": 400,
  "code": "INVALID_QUERY",
  "extensions": {}
}
```

The exact filter I am trying to use is:
```json
{
    "filter": {
        "country": {
            "_eq": "{{validate_query.validatedCountry}}"
        },
        "region": {
            "_empty": true
        }
    }
}
```

### To Reproduce

1. Create a table with at least 1 field that is not required.
2. Create a flow.
3. In the flow try to filter the table using `_empty` on the field that is not required.

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
You're missing a [logical operator](https://docs.directus.io/reference/filter-rules.html#logical-operators). You're probably looking for something like this:
```json
{
  "_and": [
    {
      "region": {
        "_eq": "{{validate_query.validatedCountry}}"
      }
    },
    {
      "country": {
        "_empty": true
      }
    }
  ]
}
```
