### ISSUE TITLE
[UNKNOWN] Network Error

### ISSUE THREAD

**Issue by bashulsbosch** [directus/directus#17645]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

{   "stack": "AxiosError: Network Error\n    at R.onerror (<PRIVATEURL>/admin/assets/use-sync-7318fa3d.js:29:4378)",   "message": "Network Error",   "name": "AxiosError",   "code": "ERR_NETWORK",   "config": {} }

Uploading large files results in a network error. Creating 2 uncompleted files in the file library.

### To Reproduce

Upload a large file

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
A couple of limits spring to mind, but hard to say without more detailed information. Like what do you consider a "large file".
You may be running into the default `MAX_PAYLOAD` https://docs.directus.io/self-hosted/config-options.html#general or proxy configuration, nginx has a couple of ways where request sizes are limited for instance.
