### ISSUE TITLE
Standard docker-with-postgis installation not working because postgis is not M1/M2 compatible

### ISSUE THREAD

**Issue by rowild** [directus/directus#17640]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

Trying to install what the docu provides here:
https://docs.directus.io/self-hosted/docker-guide.html#docker-compose

The error thrown:
`database The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

Several thread on the www mention that problem, the community provides custom-builds (e.g. https://github.com/postgis/docker-postgis/issues/216).

I would recommend to at least mention in the docu that currently there is no supported way to work with postgis on Mac M1/M2.

### To Reproduce

Simply run the the docker-compose-yaml provided in the installation guide:
https://docs.directus.io/self-hosted/docker-guide.html#docker-compose

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
See https://github.com/directus/directus/pull/16812#issuecomment-1349150838.

If you need more help, please follow these instructions: https://docs.directus.io/getting-started/support.html#support-tiers

**Comment by rowild** [comment]
Ok, but don't you think that this should be mentioned in the docu?

**Comment by rowild** [comment]
Follow-up error:

```sh
➜  directus9 npx directus start
internal/modules/cjs/loader.js:753
      throw new ERR_UNKNOWN_BUILTIN_MODULE(filename);
      ^

Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:stream/promises
    at new NodeError (internal/errors.js:322:7)
    at Function.Module._load (internal/modules/cjs/loader.js:753:13)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/robertwildling/.npm/_npx/ebcc468e2b0f2b61/node_modules/directus/dist/services/files.js:38:20)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'ERR_UNKNOWN_BUILTIN_MODULE'
}
```

**Comment by paescuj** [comment]
> Ok, but don't you think that this should be mentioned in the docu?

Created a pull request for this, see https://github.com/directus/docs/pull/313 👍

**Comment by paescuj** [comment]
> Follow-up error:
> [...]

The `directus` image works on M1:
<img width="400" src="https://user-images.githubusercontent.com/5363448/221813848-0b29eb0a-582e-4f4c-b1ce-f47267c8a759.jpeg">

Please open a separate issue with all required information, if you are sure that this is indeed a bug.

**Comment by rowild** [comment]
Thank you vey much! – As for the "folow-up" error: Stupid me! There is no need to run "npx directus start"! Opening localhiost:8055 works just fine!
