### ISSUE TITLE
Primary Key doesn't support text-based datatypes

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1764]
## Version Info
  - Directus version and branch: develop 9f19567dade2bc8f25eca79caa5ad1e745e0237e
  - PHP version: 7.1.6
  - MySQL version: 5.6.35
  - Web server: MAMP Pro
  - OS name and version: MacOS Sierra

## Expected Behavior
Supporting text-based values for the Primary Key of a table can be achieved by changing the datatype of the Primary Key interface to a text-one like `VARCHAR` or `CHAR`.

## Actual Behavior
The options are missing from the dropdown. 
Next to that, adding them in by modifying the allowed datatypes in [`component.js`](https://github.com/directus/directus/blob/develop/app/core/interfaces/_system/primary_key/component.js#L6) results in all kinds of unexpected behavior, f.e.:

1.  changing the datatype of an existing table with content results in every key being removed and the system throwing an error about duplicate keys (all `NULL`).

2.  the admin doesn't register the Primary Key being available and thus keeps throwing errors when trying to open the list view of the table and;

3.  the auto-increment breaks as it is now a text-based value.

**Comment by benhaynes** [comment]
@WellingGuzman Didn't you say you were working on this one? What is the status?

**Comment by WellingGuzman** [comment]
Please confirm, otherwise I will re-open.

Closed by https://github.com/directus/directus/commit/6529c4d5114b922153aedb9f5eb06c1bf6ad38fd

**Comment by xstable** [comment]
I have installed 6.5.0 and the Bug still exist.

**Comment by WellingGuzman** [comment]
Hey @xstable Which version exactly did you installed?

**Comment by xstable** [comment]
Where can I find out? Is there no version-info in the gui?
I found only this in sourcecode (browser-view) : 
/assets/imgs/icons/browserconfig.xml?v=6.5.0

**Comment by WellingGuzman** [comment]
@xstable on `/package.json` or hover over "Directus" at the bottom of the login page.

**Comment by xstable** [comment]
Installed Version: 6.4.3

**Comment by alanford123** [comment]
has this bug been fixed? i can't seem to be able to use uuid as the primary key
