### ISSUE TITLE
Cannot retrieve users location, title, description and tags through user_created nested relation

### ISSUE THREAD

**Issue by agodard** [directus/directus#17643]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

Regarding [the documentation](https://docs.directus.io/reference/introduction.html#system-data-in-graphql), **nested relations should work as expected regardless if they "cross over" between user and system data**. 

Nevertheless, I can retrieve users _location, title, description and tags_ when querying `/grapgql/system` endpoint but all tese fields are null when querying `/graphql` endpoint through nested relation (user_created field). 

There is no problem with i_d, email, first_name, last_name and avatar_ fields though. Did I miss something or is there a real bug here ?

For your information I'm using the latest Directus v9.22.4 community Cloud version.

### To Reproduce

Querying `{{directus-host}}/graphql` url with followin payload : 

```graphql
query {
    articles(filter: { status: { _eq: "published" } }, limit: 1) {
        slug
        cover_image {
            id
            filename_download
            title
        }
        date_published
        author: user_created {
            id
            email
            fisrtname: first_name
            lastname: last_name
            avatar {
                id
                filename_download
                title
            }
            location
            title
            description
            tags
        }
        title
        content
    }
}
```

results in : 

```json
{
    "data": {
        "articles": [
            {
                "slug": "some-title",
                "cover_image": {
                    "id": "5d4e9ff0-aa38-57ba-b686-c2c49f466d3a",
                    "filename_download": "some-title.png",
                    "title": "Some Title"
                },
                "date_published": "2023-02-24T19:27:00",
                "author": {
                    "id": "574a198a-7973-4e1f-a17d-81fc5a0e1aac",
                    "email": "paul_eluard@example.com",
                    "fisrtname": "Paul",
                    "lastname": "Eluard",
                    "avatar": {
                        "id": "66c232bf-a3de-462f-a558-2b23a73c348f",
                        "filename_download": "Paul_Eluard.jpeg",
                        "title": "Paul Eluard"
                    },
                    "location": null,
                    "title": null,
                    "description": null,
                    "tags": null
                },
                "title": "Some title",
                "content": "<p>content here ...</p>"
            }
        ]
    }
}
```

### Hosting Strategy

Directus Cloud

**Comment by br41nslug** [comment]
It looks like you're retrieving the location/title/etc just fine in the result, are you sure they're filled for this response?

In a quick test im getting the fields as expected via an `user_created` relations.
![image](https://user-images.githubusercontent.com/9389634/221826873-8f6dbb36-208c-4425-b1bd-1e2f15cf92f5.png)

Happy to re-open the ticket when more info is available 😄
