### ISSUE TITLE
After the update, the description of the version does not agree

### ISSUE THREAD

**Issue by koksikus** [directus/directus#17653]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

After the update, the description of the version does not agree. There is still 9.22.3 despite the fact that I updated to 9.23

### To Reproduce

Update to the latest version and look at the displayed version

### Hosting Strategy

Self-Hosted (Custom)

**Comment by koksikus** [comment]
Or the command does not work "npm update". Showed me the latest version 9.22.3

**Comment by paescuj** [comment]
Due to an issue in the release pipeline, the new version hasn't been pushed to the NPM registry. This has been fixed in #17656. A new release in order to make the packages available will be made soon.
