### ISSUE TITLE
Translations not persisting in Database (when using the Translation (O2M))

### ISSUE THREAD

**Issue by magbeat** [directus/directus#1766]
Hi there,

## Version Info
  - Directus version and branch: 6.4.2 (current master as the time of writing (3d7225c)
  - PHP version: 5.6.31
  - MySQL version: 10.1-MariaDB
  - Web server: Apache
  - OS name and version: unknown (Hoster) 

## Expected Behavior

Store translated field when saving.

## Actual Behavior

Not storing translated field when saving

## Steps to Reproduce
 1. Setup translation as described in Medium Tutorial (https://medium.com/directus/multilingual-content-setup-in-directus-i18n-4f243f72e554)
 2. Edit an entry
 3. Enter something in the translated field
 4. Save the entry
 5. Open it again

The translated field is however saved when I switch to another language after I entered the input. That's why I assume that the tables are set up correctly.

## Schema Dump, Logs, or Screenshots

![01_edit](https://user-images.githubusercontent.com/1089410/29717847-f5b437d2-89b0-11e7-8da3-c23751b8c7a1.png)

![02_save](https://user-images.githubusercontent.com/1089410/29717850-f8e89452-89b0-11e7-826c-f6dcaee987db.png)

![03_not_saved](https://user-images.githubusercontent.com/1089410/29717855-fce8dfee-89b0-11e7-9b79-44bce21fd09a.png)

**Comment by WellingGuzman** [comment]
Thanks @magbeat, I will be working on it as soon as possible!

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/3c4fbd6dc8df6af8ec6f56dd18d9b626b0d59997

Please @magbeat confirm, and i will re-open otherwise.

**Comment by magbeat** [comment]
@WellingGuzman I can confirm that it works. Thanks a lot!
