### ISSUE TITLE
Input type="email" interface

### ISSUE THREAD

**Issue by dteskera** [directus/directus#17676]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

when creating directus users the email field isn't of type="email" so you can create users with invalid emails. but when you try to login the email input field is of type="email" which prevents you from entering such invalid emails.

### To Reproduce

1. open users collection. 
2. create new user. for email put something like a.a.
3. log out as current user.
4. try to log in with email a.a (directus rightfully prevents you with html5 validation - since its an invalid email)

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by azrikahar** [comment]
Thanks for reporting this. I believe this goes hand-in-hand with #11399 as a whole, so I'll proceed to close this in favor of that issue. 👍
