### ISSUE TITLE
Directus | Flows are not updating the Revision while creating a collection

### ISSUE THREAD

**Issue by ananth3087** [directus/directus#17677]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

I'm using Directus lastest version

 1. I have created a Data Model "Article" with title and Random_order field. 
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/38585821/222400018-1fccd3ee-89cd-4112-a4a1-bf36a275737b.png">

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/38585821/222400232-69c47f3a-98ab-49e2-8d85-752b88f96d41.png">

 2. I have created an flow which will update a random number into the field "Random_order".
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/38585821/222400430-08e34613-672a-4251-986e-57175902deeb.png">

<img width="870" alt="image" src="https://user-images.githubusercontent.com/38585821/222400823-0e54c83a-6456-4755-af22-e1e1ba3f9426.png">

<img width="919" alt="image" src="https://user-images.githubusercontent.com/38585821/222401000-a2997595-7b6c-4574-a2e6-5d01b86c4798.png">

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/38585821/222401341-46a57dfc-c9ed-4fe1-b554-de330cbe389c.png">

 3. The feature is working fine but when i saw the revision history, that revision history is not showing any details about "Random_order" value. It should show the random number 535.
 
<img width="856" alt="image" src="https://user-images.githubusercontent.com/38585821/222401921-4b3f331c-e4fc-49bf-b6a8-97e84df6f2e6.png">

So the problem is, when we use Directus flow to alter the field value of any Data model, then its not getting recorded in Revision history. 

Currently i'm using the "Filter" type of Directus Flow

### To Reproduce

I'm using Directus lastest version, 9.22. 

 1. I have created a Data Model "Article" with title and Random_order field. 
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/38585821/222400018-1fccd3ee-89cd-4112-a4a1-bf36a275737b.png">

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/38585821/222400232-69c47f3a-98ab-49e2-8d85-752b88f96d41.png">

 2. I have created an flow which will update a random number into the field "Random_order".
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/38585821/222400430-08e34613-672a-4251-986e-57175902deeb.png">

<img width="870" alt="image" src="https://user-images.githubusercontent.com/38585821/222400823-0e54c83a-6456-4755-af22-e1e1ba3f9426.png">

<img width="919" alt="image" src="https://user-images.githubusercontent.com/38585821/222401000-a2997595-7b6c-4574-a2e6-5d01b86c4798.png">

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/38585821/222401341-46a57dfc-c9ed-4fe1-b554-de330cbe389c.png">

 3. The feature is working fine but when i saw the revision history, that revision history is not showing any details about "Random_order" value. It should show the random number 535.
 
<img width="856" alt="image" src="https://user-images.githubusercontent.com/38585821/222401921-4b3f331c-e4fc-49bf-b6a8-97e84df6f2e6.png">

So the problem is, when we use Directus flow to alter the field value of any Data model, then its not getting recorded in Revision history. 

Currently i'm using the "Filter" type of Directus Flow

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Nitwel** [comment]
Created a PR to fix this bug and just wanted to let you know that you probably want to use `return {... 
data.$trigger.payload, "order": randomInt}` instead of using double curly brackets as that's the intended way to access data inside the function and your way can lead to unknown side effects. @ananth3087

**Comment by ananth3087** [comment]
Great, Thank you @Nitwel
