### ISSUE TITLE
Validation errors do not show in inline editor

### ISSUE THREAD

**Issue by shipsides-sparknel** [directus/directus#17673]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

When a validation error is present, the **inline editor** does not display errors of any types (required value, regex, etc).

Instead, it just refuses to submit and provides no feedback as to what fields stopped it and why.

Also tested in Chrome and Edge to the same effect.

### To Reproduce

In this example I used Insights to access the inline editor
![inline editor no invalid](https://user-images.githubusercontent.com/106218118/222292441-f58414f5-2f90-4887-b2d1-5e3bab1c6d34.gif)

The behavior is the same when using the inline editor from an item.

### Hosting Strategy

Directus Cloud

**Comment by azrikahar** [comment]
Seems like this is the same issue as #16091 (as Insights List panel's inline editing opens up the same underlying `<drawer-item>` component), so I'll proceed close this as a duplicate 👍
