### ISSUE TITLE
9.23 - O2M sub-columns not displaying in table layout

### ISSUE THREAD

**Issue by JoshTheDerf** [directus/directus#17670]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

Reproduction SQLite3 Database:
[test.db.zip](https://github.com/directus/directus/files/10864556/test.db.zip)
Username: `test@test.com`
Password: `test`

Tested With:
- Integer primary keys
- UUID primary keys
- Custom primary keys
- SQLite3

Not Tested:
- Other databases
- Other relationship types
- Other layout & preset scenarios

Likely introduced in: https://github.com/directus/directus/pull/15269

In the table layout, columns selected from the child table of an O2M relationship do not display at all and seem to conflict with O2M field on the parent table.

Sub-columns `Title` and `Path` invisible without the parent O2M column selected:
![image](https://user-images.githubusercontent.com/5861371/222241888-309307c3-fe07-432c-9aaf-8e1c6fbeb083.png)

Sub-columns `Title` and `Path` display the primary key of the child table when the parent O2M column is selected:
![image](https://user-images.githubusercontent.com/5861371/222242134-82331a9f-ce7e-40d8-8d90-40a0f558d9e8.png)

There are a slew of other interaction/UI bugs relating to this, but they're a bit hard to describe. 

### To Reproduce

1. Create a table to be on the "Many" end of an O2M relationship. Add a couple input columns to it.
![image](https://user-images.githubusercontent.com/5861371/222242921-a66705a8-d146-48b7-b62f-63119a801219.png)

2. Create another table to be on the "One" end of the O2M relationship. Add an input column to it (just for demonstration), and an O2M relation to the "Many" table.
![image](https://user-images.githubusercontent.com/5861371/222239833-0e1dab7d-7a40-4647-a890-f0eb9f9c67a8.png)

3. Create several rows in the "One" table, each relating to a unique row in the "Many" table.
![image](https://user-images.githubusercontent.com/5861371/222240349-3b9c7f05-77ff-4bbb-9606-2269c9b0d4e3.png)

4. In the table view for the "One" table, add the input columns from the "Many" table to the table headers:
![image](https://user-images.githubusercontent.com/5861371/222240524-f729caf4-f2a2-4c8d-8809-b95c46cc869d.png)

5. Note that the related fields do not display. Clicking on the "jump to item" links will navigate to an `content/TABLE/undefined` route.

6. Adding the O2M column directly to the headers results in all sub-columns displaying the primary key for the O2M field, and rearranging them causes the names all to review to the field name for the O2M field.
![image](https://user-images.githubusercontent.com/5861371/222241191-8eaa6ea0-9bd8-44b3-93ba-5c6880720d7d.png)

### Hosting Strategy

Self-Hosted (Custom)

**Comment by koksikus** [comment]
Same thing happens to me

**Comment by jarekcieslak** [comment]
Same here, issue with table layout
