### ISSUE TITLE
Sharp: Input buffer contains unsupported image format causing directus to shutdown.

### ISSUE THREAD

**Issue by cory-glooh** [directus/directus#17683]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

Using Digital Oceans app platform to deploy directus. when attempting to replace an existing file, if the payload is invalid, it causes directus to shutdown. 
![msedge_B8lDTFbc9r](https://user-images.githubusercontent.com/85269391/222455387-da46e98d-4672-431b-9463-27129d3adda8.png)

### To Reproduce

Call PATCH on a file, with invalid image data. 

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
Please make sure to use the latest version!
This has been fixed in https://github.com/directus/directus/pull/17335 and released with 9.23.0.
I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment.
