### ISSUE TITLE
Error staging a schema: adding icon and color

### ISSUE THREAD

**Issue by MaLub** [directus/directus#17698]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

I want to transfer the schema of a Directus instance to another Directus instance.
For this I use the steps as described here: https://docs.directus.io/reference/system/schema.html

We're using Postgres 15.1 and Directus 9.23.1

----

I've changed color and icon of one collection in the source instance. Destination instance doesn't have any color or icon defined for this collection.

Here is the payload after generating the diff (`/schema/diff`) for `/schema/apply`

```
{
    "hash": "06f905c54e2700d9e2167275cf5ce62f3d90566a",
    "diff": {
        "collections": [
            {
                "collection": "test2",
                "diff": [
                    {
                        "kind": "E",
                        "path": [
                            "meta",
                            "color"
                        ],
                        "lhs": null,
                        "rhs": "#FB0404"
                    },
                    {
                        "kind": "E",
                        "path": [
                            "meta",
                            "icon"
                        ],
                        "lhs": null,
                        "rhs": "event"
                    }
                ]
            }
        ],
        "fields": [],
        "relations": []
    }
}
```

Error-Response
```
{
    "errors": [
        {
            "message": "\"diff.collections[0].diff[0].lhs\" must be of type object",
            "extensions": {
                "code": "INVALID_PAYLOAD"
            }
        }
    ]
}
```

In my point of view it shouldn't raise an 'INVALID_PAYLOAD' because there is no color or icon defined in the destination and therefore `lhs` should be null.

### To Reproduce

- Start two instance of directus
- Change color in one of them
- Transfer schema from that instance to the other  as described her https://docs.directus.io/reference/system/schema.html

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by mcqua007** [comment]
Im getting this same issue:

```
 "hash": "9974fb03ed472dca130bf994589f4d47754149a5",
    "diff": {
        "collections": [
            {
                "collection": "pages",
                "diff": [
                    {
                        "kind": "E",
                        "path": [
                            "meta",
                            "color"
                        ],
                        "lhs": null,
                        "rhs": "#3399FF"
                    },
```

Getting this error:
```
{
    "errors": [
        {
            "message": "\"diff.collections[0].diff[0].lhs\" must be of type object",
            "extensions": {
                "code": "INVALID_PAYLOAD"
            }
        }
    ]
}
```

**Comment by stylefieber** [comment]
It seems to be a general issue. When I try to import a diff via "schema/apply" I get this error for several objects.
