### ISSUE TITLE
Unexpected behaviour when getting a user's password

### ISSUE THREAD

**Issue by pzehle** [directus/directus#17691]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

I've recently opened an issue which got converted into a discussion which of course nobody is commenting:

[Is there a way to avoid 'conceal' when using ItemsService within nodejs?](https://github.com/directus/directus/discussions/17632)

After some days I realized I should open another issue, since I believe the one I opened before got converted by mistake. Let me explain:

I think it should be possible to get a user's password from within Directus, and we shouldn't have to use any workaround to get the user's password so we can actually deliver a password recovery process with another email provider. I believe that this is in fact an unexpected behaviour (forcefully getting '**********' instead of the hash) as one should be able to decide if such information comes concealed or not, and NOT be forced to have some * because there is no option to do otherwise.

With that being said, I am getting an unexpected behaviour, or a bug, in which I can't retrieve a user password's hash using the Items Service, which of course I should be able to.

Is there any other way I can achieve this?

Thank you.

### To Reproduce

Get a user password's hash using the Items Service

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
> I believe that this is in fact an unexpected behaviour (forcefully getting '**********' instead of the hash)

This is very much intentional out of security concerns. You will not be able to use the services to get this data but as mentioned in my other response it is possible at your own risk https://github.com/directus/directus/discussions/17632#discussioncomment-5218294
