### ISSUE TITLE
Call to a member function getOptions() on null

### ISSUE THREAD

**Issue by jvmejias** [directus/directus#1770]
## Version Info
  - Directus version and branch: Build 6.4.2
  - PHP version: PHP 5.6.30
  - MySQL version: 
  - Web server: Apache
  - OS name and version: Windows 7

## Expected Behavior
I'm trying to upload an image to a Multiple Files M2M column. The expected behavior is to save the image id and the article id in my junction table.
It was working fine for me in the previous version, but not after I updated to Build 6.4.2

## Actual Behavior
The image is uploaded and the thumb is created (I can see them via FTP), but the changes won't save to database. I get the following error:

> Server Error
> Call to a member function getOptions() on null

I get the same error when trying to upload from the File Library.
I can however edit and save an item if I don't add any images.

Probably it is due to some misconfiguration of mine, but I'm clueless.

**Comment by WellingGuzman** [comment]
Hey @jvmejias, Is this a fresh install? did you update the database schema by using `bin/directus db:upgrade`?

**Comment by jvmejias** [comment]
Thank you very much Welling, that was it. I had in fact run that CLI command, but I didn't figured out I had to delete the directus_schema_migrations table before for the update to take effect.
Congrats to all the team for your hard work with this wonderful CMS!

**Comment by WellingGuzman** [comment]
Thanks!

You didn't have to, or you shouldn't had to delete the `directus_schema_migrations` table in order to proper update.

**Comment by jvmejias** [comment]
Hi @WellingGuzman
I've just updated from 6.4.3 to 6.4.4 (Build branch) and I can confirm you that I had to delete directus_schema_migrations from my current db for the migration to succeed.

Here is the Git Bash output:

```
$ bin/directus db:upgrade
db:setup - table 'directus_schema_migrations' already exists. Nothing to do.
db:migrate - Not executed
```

And after directus_schema_migrations deletion:

```
$ bin/directus db:upgrade
db:setup - directus_schema_migrations table created
db:migrate - Migration successful
```

**Comment by WellingGuzman** [comment]
Hey @jvmejias, that's okay, there's not always migration file to execute.
