### ISSUE TITLE
9.23 - Displaying of relational fields of Translations relation is broken in Tabular layout

### ISSUE THREAD

**Issue by d1rOn** [directus/directus#17716]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

9.23 - Displaying of relational fields of Translations relation is broken in Tabular layout.

https://user-images.githubusercontent.com/26179694/223399302-b656f256-de13-41ff-813c-8b627733c992.mp4

This only started happening since version 9.23.
I suggest looking in the direction of Discussion #16508 and PR #16507. I think this display algorithm will be the most acceptable.

### To Reproduce

1. Create collection A with Translations relation (to collection A_translations).
2. Add some items.
3. Go to Content module.
4. Try to add `Translations -> Languages Code` column. It will show the empty values.
5. Then try to add `Translations` column. It will show the data within Translations display in this column correctly. The `Translations -> Languages Code` will show the same Translations display with the same data (not a Languages Code field only).
6. The try to move one of these columns (d'n'd) to another place. After this action, all both `Translations` and `Translations -> Languages Code` columns will have the same name — `Translations`.
7. Then try to delete one of these columns. Both columns will be removed.

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by gloribus** [comment]
Faced the same problem

**Comment by MaximSavin** [comment]
Confirm, same problem. Both field displays Title value, which is Display template for Translations. On drag any of translation column both reset to Translation column. After delete any one of this column — deleted both. And then when add it back Title, then Body in console log have TypeError in runtime-core.

<img width="370" alt="Screenshot 2023-03-14 at 14 56 04" src="https://user-images.githubusercontent.com/125530/224933524-f618039d-cccb-4eca-b5de-36fefa189318.png">
<img width="366" alt="Screenshot 2023-03-14 at 14 56 11" src="https://user-images.githubusercontent.com/125530/224933555-475e2e12-fbb0-474b-bd6f-146f9f8d02d8.png">
<img width="356" alt="Screenshot 2023-03-14 at 15 00 39" src="https://user-images.githubusercontent.com/125530/224934536-92b6b056-1ceb-4f7d-8acc-2f7ad2cfc650.png">
<img width="581" alt="Screenshot 2023-03-14 at 14 56 44" src="https://user-images.githubusercontent.com/125530/224933585-4d0aae8c-4770-477b-964b-e4b8ae0f27c0.png">


DB Snapshot: [snapshot.yaml.txt](https://github.com/directus/directus/files/10965642/snapshot.yaml.txt)
