### ISSUE TITLE
Unable to send webhook events to localhost

### ISSUE THREAD

**Issue by diastremskii** [directus/directus#17735]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

It seems that the fix for [this](https://github.com/advisories/GHSA-j3rg-3rgm-537h) vulnerability has broke sending webhook events for localhost. The requests fail with "Requested URL "\*url\*" resolves to a denied IP address".

### To Reproduce

1. Set up Directus to send events to localhost, i.e. http://localhost:80.
2. Perform an action that triggers sending a webhook event.

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
As Azri mentioned requesting `localhost` is blocked by default. You can allow these requests by setting an empty value for `IMPORT_IP_DENY_LIST=""`
