### ISSUE TITLE
WYSIWYG Full editor modifying html

### ISSUE THREAD

**Issue by jvmejias** [directus/directus#1773]
## Version Info
  - Directus version and branch: Build 6.4.2
  - PHP version: PHP 5.6.30
  - MySQL version: MariaDB 10.1
  - Web server: Apache
  - OS name and version: Windows 7

I'm using the new WYSIWYG FULL editor and I have noticed that it automatically modifies my html before saving (adding paragraphs, changing paths, decoding html entities, etc).  I would like to preserve the html intact as it was in the previous editor (version 6.3.9. I think)
For the moment I have swaped to Textarea because these automatic corrections break my content.
Is there an easy way to deactivate this behavior?
Or should I duplicate the UI and customize it?

**Comment by benhaynes** [comment]
Hello @jvmejias – I defer to @rijkvanzanten on these interface issues, but my understanding is this:

The new WYSIWYG Full interface parses the data it's given to meet the requirements of its output. This most likely differs from the way that rich content was managed in the previous (6.3.x) WYSIWYG editor. There are a few options:

1. Update your content, refactoring as needed within your applications
2. Duplicate and update the new WYSIWYG editor to fit your needs (Custom Interface)
3. Copy the old WYSIWYG editor interface from 6.3.x into your new Directus instance

Let me know your thoughts on all this! I understand that changes like this can be annoying, but our goal is to keep the framework moving forward while still supporting as many previous versions as possible.

**Comment by benhaynes** [comment]
Hey @jvmejias – Rijk agrees with my assessment. Since this can be solved to support your legacy content format I'm going to say this isn't a bug and won't be fixed. If others disagree we can certainly re-open!

**Comment by jvmejias** [comment]
Hi Ben. Sorry for the delay, option 3 could be fine but I didn't look into it yet.

I understand your point. However I'll elaborate a little bit my consultation.
Please enter the following html in a WYSIWYG Full editor field

```
<div class="row">
    <div class="col-md-6">
        <div class="my-gallery" itemscope="" itemtype="http://schema.org/ImageGallery" data-pswp-uid="1">
        <figure class="max600 btnlupa" itemprop="associatedMedia" itemscope="" itemtype="http://schema.org/ImageObject"><a href="http://www.example.com/version2/media/image-big1.jpg" itemprop="contentUrl" data-size="2000x1415">
        <div class="iconopeq iconolupa"></div>
        <img src="http://www.example.com/version2/media/image1.jpg" class="img-responsive" alt="Daños de guerra en Pompeya"></a></figure>
        </div>
    </div>
    <div class="col-md-6">
        <div class="my-gallery" itemscope="" itemtype="http://schema.org/ImageGallery" data-pswp-uid="2">
        <figure class="max600 btnlupa" itemprop="associatedMedia" itemscope="" itemtype="http://schema.org/ImageObject"><a href="http://www.example.com/version2/media/image-big2.jpg" itemprop="contentUrl" data-size="2000x1415">
        <div class="iconopeq iconolupa"></div>
        <img src="http://www.example.com/version2/media/image2.jpg" class="img-responsive" alt="Daños de guerra en Pompeya"></a></figure>
        </div>
    </div>
</div>

<div id="mapabombardeo" class="iconopeq iconomapainfo metido"><h3><span>Plano de Amadeo Maiuri, localización de las bombas</span></h3></div>
<div id="mapabombardeo2" class="iconogrande iconoexcava metido2 borderclass" data-toggle="tooltip" data-placement="right" title="" data-original-title="Mostrar imagen aérea"></div>

<div class="contenedorimagen ampliado" style="padding-bottom:73%;">
    <a id="hotspot1" class="hotspot extenso miniiconovideo" data-toggle="popover" style="position: absolute; top: 64%; left: 36%;" data-placement="top" data-content="<div style='position:relative;height:0;padding-bottom:75.0%;min-width:550px;'><iframe src='https://www.youtube.com/embed/W1uxHzp-iQw?ecver=2&amp;showinfo=0&amp;rel=0' width='480' height='360' frameborder='0' style='position:absolute;width:100%;height:100%;left:0' allowfullscreen></iframe></div>" data-html="true" data-original-title="" title=""></a>
    <div class="fullbg mapabombardeo2"></div> 
    <div class="fullbg mapabombardeo1"></div> 
</div>
```
...and it becomes:

```
<div class="row">
<div class="col-md-6">
<div class="my-gallery" data-pswp-uid="1">
<figure class="max600 btnlupa">
<div class="iconopeq iconolupa">&nbsp;</div>
<a href="../../../../media/image-big1.jpg" data-size="2000x1415"><img class="img-responsive" src="../../../../media/image1.jpg" alt="Da&ntilde;os de guerra en Pompeya" /></a></figure>
</div>
</div>
<div class="col-md-6">
<div class="my-gallery" data-pswp-uid="2">
<figure class="max600 btnlupa">
<div class="iconopeq iconolupa">&nbsp;</div>
<a href="../../../../media/image-big2.jpg" data-size="2000x1415"><img class="img-responsive" src="../../../../media/image2.jpg" alt="Da&ntilde;os de guerra en Pompeya" /></a></figure>
</div>
</div>
</div>
<div id="mapabombardeo" class="iconopeq iconomapainfo metido">
<h3>Plano de Amadeo Maiuri, localizaci&oacute;n de las bombas</h3>
</div>
<div id="mapabombardeo2" class="iconogrande iconoexcava metido2 borderclass" title="" data-toggle="tooltip" data-placement="right" data-original-title="Mostrar imagen a&eacute;rea">&nbsp;</div>
<div class="contenedorimagen ampliado" style="padding-bottom: 73%;">&nbsp;</div>
```

1 - In the first part, some atributes have dissappeared (itemscope, itemtype) and that makes my javascript gallery not to work.

2 - In the last part, all contents inside the div with class '.contenedorimagen'(two divs and a link) are completely gone...

3 - My absolute paths are converted to relative (only if the domain name is the same where Directus is). This results in the two images of the example not showing.
My storage folder is called media and it is a level up the Directus root directory.

4 - Spanish accents in the view source button are now showing the decoded entities, so it becomes more difficult to read.

5 - Indentation is lost

I can live without 4 and 5, but if my html content is manipulated too much, to the extent of some content dissapearing I cannot use the editor, at least in this project!

**Comment by benhaynes** [comment]
@rijkvanzanten – can you respond with your thoughts on these points?

**Comment by rijkvanzanten** [comment]
Hi @jvmejias!

There's an option which allows you to see and modify the actual output HTML. That allows you to paste in your existing markup without having the editor change the values you described above. To add the view source button to the toolbar, you have to activate the `View Source` option in the interface's toolbar options setting.

<img width="630" alt="screen shot 2017-09-05 at 12 56 08 pm" src="https://user-images.githubusercontent.com/9141017/30073157-d02295da-923a-11e7-92b1-06fc4ae8e98a.png">

<img width="1435" alt="screen shot 2017-09-05 at 12 59 27 pm" src="https://user-images.githubusercontent.com/9141017/30073160-d6e5fbc8-923a-11e7-97a2-5c2caea4436d.png">


The editor is configured by default to remove potentially unsafe HTML tags which can be used for XSS attacks in some specific cases. That means that as of now, it still removes the `<iframe>` in your markup. I'll create an option in the same interface settings to overrule this, as this is a critical option to have as end user!

Please let us know if this works out for you!

**Comment by rijkvanzanten** [comment]
The option mentioned above is added in in https://github.com/directus/directus/commit/5464f0e59a8c1c53bdd0efe2680db662c9b6957a on the [develop](https://github.com/directus/directus/tree/develop) branch and will hit master soon.

**Comment by jvmejias** [comment]
Hi @rijkvanzanten!
Thanks for your time! I know the 'view source' button, there is where I paste my html content. I create my markup outside Directus and later paste it on there. I'm just using the following editor options: 'bold', 'cursive', 'link' and 'view source'.

In your last image, if you click ok and then hit again 'view source' the content has already transformed as described in my example.

The main problem I have is with custom attributes being deleted by default. In my example, the editor trims "itemscope", "itemtype" and "itemprop".

I'd love to have an option to completely deactivate the filtering and leave my input html untouched (at my own risk of course). Will https://github.com/directus/directus/commit/5464f0e59a8c1c53bdd0efe2680db662c9b6957a do that or still apply some filtering?

**Comment by rijkvanzanten** [comment]
The option I created sets the editor to allow all HTML tags and attributes as valid children, which theoretically means it should leave your markup untouched. Other then the white space issue I couldn’t spot any other differences at first glance, but it does need some extra testing still. If you’re able to test out the develop branch (which has this option), I’d love to  get your feedback 😊 I’ll see what I can do about the indentation getting messed up 👍🏻

**Comment by jvmejias** [comment]
Sounds great @rijkvanzanten!
I'll get back to you as soon as I try it. Thanks a lot

**Comment by jvmejias** [comment]
Hi @rijkvanzanten
I've just updated to the latest build and I've tried the option you added upon my request.
It's pretty cool but there is still a little problem that results in unwanted modifications to the html input.
It happens when there is a div inside an a tag, which as far as I know it is valid html5

To reproduce, enter the following markup:

```
<a href="/about-page.php">
	<div class="article">
	<h1>Hi there</h1>
	<p>The whole div is a link</p>
	</div>
</a>
```

And you get:

```
<div class="article">
<h1>Hi there</h1>
<p>The whole div is a link</p>
</div>
```

The link is gone.

Another part, from my original html example:

```
<div class="col-md-6">
    <div class="my-gallery" itemscope="" itemtype="http://schema.org/ImageGallery" data-pswp-uid="1">
        <figure class="max600 btnlupa" itemprop="associatedMedia" itemscope="" itemtype="http://schema.org/ImageObject">
        <a href="http://www.example.com/version2/media/image-big1.jpg" itemprop="contentUrl" data-size="2000x1415">
        <div class="iconopeq iconolupa"></div>
        <img src="http://www.example.com/version2/media/image1.jpg" class="img-responsive" alt="Daños de guerra en Pompeya">
         </a></figure>
    </div>
</div>
```
It is changed to:

```
<div class="col-md-6">
<div class="my-gallery" itemscope="" itemtype="http://schema.org/ImageGallery" data-pswp-uid="1">
<figure class="max600 btnlupa" itemprop="associatedMedia" itemscope="" itemtype="http://schema.org/ImageObject">
<div class="iconopeq iconolupa"></div>
<a href="http://www.example.com/version2/media/image-big1.jpg" itemprop="contentUrl" data-size="2000x1415"><img src="http://www.example.com/version2/media/image1.jpg" class="img-responsive" alt="Da&ntilde;os de guerra en Pompeya" /></a></figure>
</div>
</div>
```

Here the div with class "iconopeq iconolupa" has been moved subtly outside the a tag, and that provokes the javascript gallery won't open.

**Comment by rijkvanzanten** [comment]
Hey @jvmejias, I've been looking into this and trying a number of options. It seems like this isn't something we can fix on our side.... 

I came across an open issue over on the repo of TinyMCE itself where the following answer is given:
> This the the only thing about the HTML5 spec we don't allow since block based anchors are problematic in a rich text editor since how do you handle nested links and how do one make a UI to edit these block based links. You need some form of block link editor that can wrap things in blocks.

https://github.com/tinymce/tinymce/issues/3142

So, for now. I'm afraid that the only option for now is either changing the original markup of your example, or not using the WYSIWYG editor for this purpose.

**Comment by flo-f** [comment]
By the way: I came across a related problem today. TinyMCE was replacing my URLs: I inserted absolute URLs to my Directus storage folder and TinyMCE rewrote these to relative URLs.

I entered _https://www.mydomain.com/directus/storage/..._ which was replaced by _../../storage/..._

As I needed the URLs to remain absolute, I modified the file [`/app/core/interfaces/wysiwyg_full/interface.js`](https://github.com/directus/directus/blob/598fa1a06ebcc5ecbb5c94ef9ac85e03f550e140/app/core/interfaces/wysiwyg_full/interface.js) by adding a fixed option `convert_urls` right above TinyMCE initialization (currently close to line 210 of `interface.js`):

```javascript
options.convert_urls = false;
tinyMCE.init(options);
```

I'm aware this is only a workaround and would only survive Directus updates when using the Git based approach. 
Maybe the option could become selectable in Directus config somewhen in future? I'd be happy to help with this if you would be interested in such a feature?

**Comment by rijkvanzanten** [comment]
Hey @flo-f! Thanks for notifying us about this problem! I've moved it over to [a new issue](https://github.com/directus/directus/issues/1896) ( #1896 ) as it's unrelated, though similar, to this one.

I'm not sure if an option would be necessary, as I actually can't think of a situation where this behavior is wanted, but I'd love to hear what you think. Lets discuss this further over at the other issue!

**Comment by benhaynes** [comment]
I'd say, the less automatic manipulation the better. Let's keep what the user entered and completely disable the conversion. No need to busy up the options with unnecessary edge cases.
