### ISSUE TITLE
Flows are not reloaded in the App before opening the Flow

### ISSUE THREAD

**Issue by ernst86913** [directus/directus#17747]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

If multiple admin are working on flows definition or if one admin works on flows definition using multiple windows the CACHING of flows can lead to inconsistent results... 

### To Reproduce

Use multiple Browser tabs to change DIFFERENT flows... then within one of the tabs navigate to a flow that was changed in a different tab... in this case it will still show the "OLD" flow definition... if you now start changing that flow it will overwrite the flow that was previously already changed....

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
This is a consequence of 2 clients saving their conflicting local states. I don't think this is a bug as such or an actionable item 😬 However this could be a good feature request

**Comment by ernst86913** [comment]
Couldn’t disagree more… it’s not about standard tables…. it’s about directus base tables / configuration… directus also does not cache collections / fields / …

LG,
Roman

Von meinem iPhone gesendet

On 09.03.2023, at 14:35, Brainslug ***@***.***> wrote:

﻿

Closed #17747<https://github.com/directus/directus/issues/17747> as not planned.

**Comment by br41nslug** [comment]
With some testing this data is cache to aggressively. We should definitely refresh this data when opening a Flow. I had lumped this in with other inconveniences/impatibilities when running multiple tabs.

**Comment by ernst86913** [comment]
Great - thanks for reconsidering

LG,
Roman

Von meinem iPhone gesendet

On 10.03.2023, at 12:53, Brainslug ***@***.***> wrote:

﻿

With some testing this data is cache to aggressively. We should definitely refresh this data when opening a Flow. I had lumped this in with other inconveniences/impatibilities when running multiple tabs.
