### ISSUE TITLE
Infinite scroll bugs

### ISSUE THREAD

**Issue by peremp** [directus/directus#1774]
## Version Info
  - Directus version and branch: 6.4.2, develop latest

## Steps to Reproduce
 1. Go to any table list 
 2. Add some search query (the number of items once the search query is applied should be more than the number of items shown per listing page (Rows Per Page)).
 2. Scroll down to load more items until you get all the items.
 3. Keep scrolling down.

## Expected Behavior
- The loader does not appear anymore since all the items are loaded.

## Actual Behavior
- The loader appears.

## More info
1- I've seen that `getTotalCount` from `collection.js` always returns the total count without taking into account the search filter (q=whatever). That's why Directus tries to load more items non-stop.
2- Because of the previous bug, and the '- 500' in `table.js` > `hitBottom` method, the `onScroll` method is called multiple times when there are no more items to load and you keep scrolling down. I proposed this some time ago, and still thinking that the `- 500` should be removed, so the items are loaded when you reach the "real" bottom.
3- If you use the horizontal scroll, it triggers the onScroll. If you scroll up, it triggers the onScroll (when you are at the end). You could add a simple check on the `onScroll` method to avoid unnecessary calls (F.e: `currentScrollPosition > lastScrollPosition`).

Doing the point 2 and point 3, the bug is fixed (already tested). But the real bug here is the point 1, and since it's related to backbone I'm not able to fix it.

**Comment by WellingGuzman** [comment]
> 1- I've seen that getTotalCount from collection.js always returns the total count without taking into account the search filter (q=whatever). That's why Directus tries to load more items non-stop.

I can't reproduce because the `getTotalCount` actually get the total items (after filters)

Can you provide an schema that we can use to test this? I test it using latest `develop` (2bddb07)

**Comment by benhaynes** [comment]
Hey @peremp – any help replicating this would be appreciated! :)

**Comment by rijkvanzanten** [comment]
Hey @peremp! We all haven't been able to reproduce this.. As @WellingGuzman mentions, the `getTotalCount` has the right count and I'm not facing any loaders popping up either. JS execution keeps a scroll handler, as that's used for more than just the infinite scrolling. If you have any additional info or a specific schema we can use to reproduce this, we'll re-open this issue and get to the bottom of it!

![can t reproduce](https://user-images.githubusercontent.com/9141017/30402190-ea5f122c-98aa-11e7-8709-f6174e85b92e.gif)
_Total items: 102, Rows per page: 40, Search query result count: 65_

**Comment by WellingGuzman** [comment]
After being reported by someone else, we noticed that this issue was only happening to tables without status column.
