### ISSUE TITLE
directus not reconnect to memcached

### ISSUE THREAD

**Issue by sbanditster** [directus/directus#17745]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

Hello,

I have the following direcus installation in azure kubernetes:
Directus using azure postgresql as database and azure storage account for files.
Everything works fine.

If I setup memcache  as external cache, it works also very nicely, except when the memcache pod restarted.
When memcached pod restarted directus loose connection to it and not reconnecting. It only reconnects if I restart the directus pod.
The memcache pod runs also in the same kubernetes cluster and in the same nemaspace as directus.

I have not found any relevant log entries why is this happening.
This issue is happening with the latest version and with older version(e.g: 9.7.0) too

Logs when directus not connecting to cache(log level: trace):

8:23:13 ✨ request completed GET 302 / 1ms
08:23:13 ✨ request completed GET 200 /admin 1ms
08:23:13 ✨ request completed GET 200 /admin
08:23:17 🔍 [6.129ms] select "ip_access" from "directus_roles" where "id" is null limit $1 [1]
08:23:23 ✨ request completed GET 302 /
08:23:23 ✨ request completed GET 302 / 1ms
08:23:23 ✨ request completed GET 200 /admin 1ms
08:23:23 ✨ request completed GET 200 /admin 1ms
08:23:33 ✨ request completed GET 302 / 1ms
08:23:33 ✨ request completed GET 302 / 1ms
08:23:33 ✨ request completed GET 200 /admin
08:23:33 ✨ request completed GET 200 /admin
08:23:38 🔍 [1.875ms] select "ip_access" from "directus_roles" where "id" is null limit $1 [1]
08:23:43 ✨ request completed GET 302 /
08:23:43 ✨ request completed GET 302 / 1ms
08:23:43 ✨ request completed GET 200 /admin
08:23:43 ✨ request completed GET 200 /admin
08:23:53 ✨ request completed GET 302 / 1ms
08:23:53 ✨ request completed GET 302 /
08:23:53 ✨ request completed GET 200 /admin 1ms

Thanks!

### To Reproduce

        - name: LOG_LEVEL
          value: trace
        - name: CACHE_ENABLED
          value: "true"
        - name: CACHE_STORE
          value: memcache
        - name: CACHE_MEMCACHE
          value: <memcache endpoint> 
        - name: CACHE_AUTO_PURGE
          value: "true"

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Nitwel** [comment]
I'm not sure if it's worth fixing this as we're planning to get rid of memcached entirely: #17500
@rijkvanzanten thoughts?

**Comment by rijkvanzanten** [comment]
We'll close this in favor of https://github.com/directus/directus/issues/15177. Not a "fix", but we're intending to drop support for memcached in the near future

**Comment by sbanditster** [comment]
Thanks for the info @rijkvanzanten. Do you have any information about if you are planning to support connection to redis cluster in the near future?
Like here: https://github.com/directus/directus/pull/6131
Thx

**Comment by rijkvanzanten** [comment]
It's looking like we'll have to start requiring Redis in the near future (for https://github.com/directus/directus/pull/14737 to reliably work), at which point we'll also greatly improve the connection and usage of Redis 👍🏻
