### ISSUE TITLE
Migrating from 6.3.8 to 6.4.2 causes problems with certain translation tables

### ISSUE THREAD

**Issue by ngirardhg** [directus/directus#1776]
## Version Info
  - Directus version and branch: From 6.3.8 to 6.4.2 (release version)
  - PHP version: 5.6.30
  - MySQL version: 5.0.11
  - Web server: Apache (XAMPP) 
  - OS name and version: Windows 7 pro service pack 1

## Expected Behavior
Adding a new entry in a table containing a translation should correctly add the entry and it's translations.

## Actual Behavior
Adding a new entry in a table containing a translation only add the parent data, and sends a server error.

## Steps to Reproduce
 1. Go to the "categories" table
 2. Fill out all the fields including the translation table one's (in french, and english)
 3. Press the save button

## Schema Dump, Logs, or Screenshots
SQL schemas, request payload and error stack trace in the following zip.
[schema_and_dumps.zip](https://github.com/directus/directus/files/1263689/schema_and_dumps.zip)
*It is possible to log in using the following credentials : user : webmaster@directus.com, password : directus

Screenshot of the error
![error_server](https://user-images.githubusercontent.com/31041083/29874302-520cb778-8d64-11e7-8eb4-431fa3306c23.png)

**Comment by WellingGuzman** [comment]
Hey @ngirardhg, I've fixed this in develop branch, please let us know it works in your end too.

You can cherry-pick the commit `e36f94e`.

Closed by https://github.com/directus/directus/commit/e36f94efb71244f95c51f3221ce676f70123f76a

**Comment by ngirardhg** [comment]
@WellingGuzman I've just tried it on my end. I replaced the code from "TranslationView.js" by the code mentionned in commit e36f94e. This unfortunately does not work for me.

**Comment by WellingGuzman** [comment]
@ngirardhg same issue? did you try to clear the browser cache?

**Comment by ngirardhg** [comment]
@WellingGuzman Indeed I cleared the browser cache before trying it. I also tried with another browser to be certain of it.

**Comment by WellingGuzman** [comment]
@ngirardhg I find it odd that you still getting the same issue, this may be fixed altogether with other translations fixes. I will make `develop` branch functional again. I will ask you if you could reproduce it on `develop` branch.

**Comment by WellingGuzman** [comment]
@ngirardhg can you do another test and see if it works on `develop` branch?

**Comment by ngirardhg** [comment]
@WellingGuzman I will test the problem on the develop branch to see if it works. I keep you up once it's done.

**Comment by ngirardhg** [comment]
@WellingGuzman It indeed solves the problem ! Do you guys know when you're going to include it in a release ?

**Comment by miguelalvagarcia** [comment]
@WellingGuzman
Hello, I have the same problem I downloaded the develop branch, it seems to have worked when I have saved the fields in one language but when I try to save the second language it does not work and it gives the same error.
[Sql-and-files-json-save-send.zip](https://github.com/directus/directus/files/1285301/Sql-and-files-json-save-send.zip)

ERROR - 2017-09-07T11:09:38-04:00 - exception 'Directus\Database\Exception\SuppliedArrayAsColumnValue' with message 'Attempting to write an array as the value for column `projects_translations`.`0.' in /git/cms_dev/api/core/Directus/Database/TableGateway/BaseTableGateway.php:339

The json to send to save when it works is different when it fails.

When fails adds the projects already created in the same array that should not be, and the composition of json think it is not correct.

This only happens to me when I use the one2many field to relate to another table. I have not tested with another related field but if you remove it works correctly.

[Sql-and-files-json-save-send.zip](https://github.com/directus/directus/files/1285303/Sql-and-files-json-save-send.zip)


Thanks

**Comment by WellingGuzman** [comment]
Hey @miguelalvagarcia what commit are you on from `develop` branch? it's working as expected with the schema you sent.

Can you provide a step by step?

**Comment by WellingGuzman** [comment]
Still working, does clearing the browser cache fix the issue?

**Comment by miguelalvagarcia** [comment]
I don't think so, you have to create a new project only in Spanish by entering a challenge save the project and when you are in the list of all projects edit the same project again and change the selector to English and fill all fields including challenge field and save the project at that time gives error.

**Comment by WellingGuzman** [comment]
Oh when you said "re-enter" you meant editing a entry, gotcha, I was able to reproduce the issue.

**Comment by miguelalvagarcia** [comment]
I'm sorry, I've done so many tests with several branches that I did not know how to explain.

**Comment by WellingGuzman** [comment]
Hey @miguelalvagarcia, this issued was fixed by https://github.com/directus/directus/commit/f5d8788744c3d7b80198e285f6a90b248b6d6291

Please let us know otherwise.

**Comment by miguelalvagarcia** [comment]
Thanks, thats working!
