### ISSUE TITLE
"new Date()" returns empty object in flow

### ISSUE THREAD

**Issue by fusscreme** [directus/directus#17764]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

I am using the "run script" action in a directus flow to get the current datetime and put it into the payload for further use.
It used to work but fails in the newest directus version (9.23.1). See attached screenshots.

**Screenshot 1**
![image](https://user-images.githubusercontent.com/74452802/224357703-d9780aa7-6ff0-4e37-b01f-c661f38a81a6.png)

**Screenshot 2**
![image](https://user-images.githubusercontent.com/74452802/224357763-d99824b3-b76f-4eea-b07b-29529f5d5eb5.png)

I tried to use "new Date().toString()" but then I'll get an sql error when inserting the value.

### To Reproduce

- Create flow
- Action: run script
- Use this code:
```
module.exports = async function(data) {
    let keys = {{$trigger}}.keys || [{{$trigger}}.key];
	return {keys,now:new Date()};
}
```
- trigger the flow and check the payload in the logs

### Hosting Strategy

Self-Hosted (Custom)

**Comment by ncarkaci** [comment]
You should pass a timestamp like `Date.now()` or date string like `new Date().toISOString()` Duplicate with [10140](https://github.com/directus/directus/discussions/10140)

**Comment by fusscreme** [comment]
`new Date().toISOString()` works!
(`Date.now()` does not)

Thank you :)
