### ISSUE TITLE
Directus cloud: Unable to access projects

### ISSUE THREAD

**Issue by yondr-luka** [directus/directus#17775]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

Unable to access my project after activation. It keeps showing the Directus screen even after 4hours waiting.
![image](https://user-images.githubusercontent.com/93581121/224747621-59f8f374-311e-4861-b55b-06cec86a6fda.png)

### To Reproduce

1. Reactivate a hibernated project on directus cloud
2. Open your project

### Hosting Strategy

Directus Cloud

**Comment by paescuj** [comment]
For inquiries or issues specific to Directus Cloud projects, please reach out through [the Live Chat in our Cloud Dashboard](https://directus.cloud/) as that's the best channel to get help with your Cloud projects 🙂

**Comment by br41nslug** [comment]
Have you contacted the cloud support about this? either via `support@directus.io` or using the chat widget on `directus.cloud`

**Comment by yondr-luka** [comment]
Thanks, I will address the issue here.
