### ISSUE TITLE
Unable to run Directus locally

### ISSUE THREAD

**Issue by AxeemHaider** [directus/directus#17786]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

I'm trying to run directus locally using this guide [https://docs.directus.io/contributing/running-locally.html](https://docs.directus.io/contributing/running-locally.html) But my frontend application does not load it continuously stay in loading state.

Here are my `.env` files
under API folder -> `.env`

```
HOST="localhost"
PORT=8055

DB_CLIENT="mysql"
DB_HOST="127.0.0.1"
DB_PORT="3306"
DB_DATABASE="fsp_dashboard"
DB_USER="admin"
DB_PASSWORD="password"


KEY="d1b865f6-05cb-4752-ba37-bcbd6c0904c0"
SECRET="rfYPSkb2p1WMWTFDm0Fa94cHHIbwuSb5"
```
I run services like this
![image](https://user-images.githubusercontent.com/27768863/224981132-9701b584-1f72-49a2-9c9e-6fbb7371d44e.png)

And this is how my application is shown
![image](https://user-images.githubusercontent.com/27768863/224981303-3c76a1cd-e3b9-4504-929c-1d35049e443c.png)

I see there are some pending requests which are never resolve, there is no error in console but here is my networking tab
![image](https://user-images.githubusercontent.com/27768863/224981551-3cec9bd8-7314-4258-87fa-215b1dff126e.png)

### To Reproduce

Try to run Directus locally using this Guide [https://docs.directus.io/contributing/running-locally.html](https://docs.directus.io/contributing/running-locally.html)

### Hosting Strategy

Self-Hosted (Custom)

**Comment by Nitwel** [comment]
You have to set `SERVE_APP=true` in your `.env` file in order to run the api in dev mode with the build app. You then also have to build the app first by navigating to the root directory and running `pnpm -r build` there.

**Comment by AxeemHaider** [comment]
Thanks now it's working. I just run it `pnpm --filter directus dev` and it also show the frontend application everything is working.
But should I have to build it on everytime ? If I change anything in frontend application I have to build it again to reflect changes. So how can I get ride from this build everytime. 

If I change anything in API it works fine automatically reflect changes but problem is with frontend app.
 
I try to run `pnpm --filter @directus/app dev` but still same problem with this stuck in loading state.

Can you please let me know how can I made changes in frontend app and changes automatically reflect without build setp.
