### ISSUE TITLE
JPEGs imported from URLs show charset

### ISSUE THREAD

**Issue by computerwizjared** [directus/directus#1778]
## Version Info
  - Directus version and branch: 6.4.0
  - PHP version: 7.1.6
  - MySQL version: AWS Aurora (MySQL) 5.6.10a
  - Web server: Apache 2.4.10
  - OS name and version: Debian 8

## Expected Behavior
Importing a JPEG from a URL into the file library should be detected simply as a JPEG.

## Actual Behavior
JPEGs imported from URLs are detected as "JPEG;charset=UTF-8", and glitch up the underlying HTML.

## Steps to Reproduce
 1. Head to create a new item
 2. Import a JPEG with a URL.

## Schema Dump, Logs, or Screenshots
![image](https://user-images.githubusercontent.com/2905521/29889142-c2a3beb8-8d88-11e7-8b4b-52ec284db0d7.png)

**Comment by WellingGuzman** [comment]
Hey @computerwizjared, thanks for reporting this, would you care to share an url of an jpg image that we can use to reproduce this issue?

**Comment by computerwizjared** [comment]
@WellingGuzman Thanks for the quick response! Here's the specific JPG that I imported: https://cms.sight-sound.com/binaries/content/gallery/SSWebsite/events/moses/moses-show-shots/moses-plagues-pharoah.jpg.

Please let me know if you need any other information :)

**Comment by WellingGuzman** [comment]
Thanks for the url @computerwizjared, I managed to reproduce the issue, I will fix it soon.

**Comment by computerwizjared** [comment]
@WellingGuzman No rush on this, it obviously isn't a showstopper. Thank you!

**Comment by WellingGuzman** [comment]
Too late 😄, I rushed and hopefully fixed. 

Please confirm, otherwise I will re-open.

Closed by https://github.com/directus/directus/commit/cb791e891246fba526895c04ec83440beadce806

**Comment by computerwizjared** [comment]
I don't have a quick way of testing at the moment, but will follow up after the next release if that's alright. Thank you 🥇

**Comment by WellingGuzman** [comment]
No problem @computerwizjared, thanks for the report! 👍

**Comment by computerwizjared** [comment]
Hey @WellingGuzman, it looks like this came back up in v7. Shall I make a new issue, or can we re-open this one? Thank you!

**Comment by WellingGuzman** [comment]
Hey @computerwizjared, Please open a new ticket in [`directus/api`](https://github.com/directus/api/issues/new?template=Bug_report.md), I would appreciate it.

**Comment by computerwizjared** [comment]
Sorry to bother @WellingGuzman, I did some more digging and it only involves the files we had already uploaded in the past. I believe I can change the "type" field in the database to fix it. Have a happy holidays!

**Comment by WellingGuzman** [comment]
Great to hear @computerwizjared, Happy holidays!

Do not hesitate if this happens again.
