### ISSUE TITLE
Uploads from Pexels or Unsplash cause Directus container to crash

### ISSUE THREAD

**Issue by EvelynKin** [directus/directus#17793]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

![image](https://user-images.githubusercontent.com/39491000/225022741-afb24c4f-a49b-438c-9d17-14274374ac4c.png)
While uploading images from URLs from websites like Unsplash and Pexels via the file import URL(/files/import), Directus container stops with an error message attached. When I try viewing the uploaded file, the app container stops.

### To Reproduce

**Post to /files/import on a locally running Directus container and use this as the payload**

URL: **/files/import**
Method: POST
{
   "url": "https://images.unsplash.com/photo-1552642762-f55d06580015?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1332&q=80", 
   "data": {"title": "67"}
}

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
I am unable to reproduce this locally with the given steps. The provided image imports and displays without problems for me. Are there perhaps any asset settings like that are required to reproduce? https://docs.directus.io/self-hosted/config-options.html#assets

![image](https://user-images.githubusercontent.com/9389634/225309634-4aebdfb8-a68f-4bd3-ad14-cd50aa5422de.png)
![image](https://user-images.githubusercontent.com/9389634/225310667-4da0f031-eaf7-49c5-8627-03a581b4f516.png)

Happy to re-open the issue once more information becomes available 😄
