### ISSUE TITLE
Creating a "Many-to-One" relationship and filling out the correct "Visible Column Template, Twig Template String" results in EMPTY DROP DOWN

### ISSUE THREAD

**Issue by redandblackstar** [directus/directus#1779]
## Version Info
  - Directus version and branch: (Or commit hash): LATEST MASTER (master Commit: 3d7225c1ff05dd3ff1d0acd83515a0f71ccf2841 [3d7225c])
  - PHP version: 7.0.8
  - MySQL version: 5.5.42
  - Web server: (Ex. Apache, nginx or IIS?) MAMP
  - OS name and version: MAC OS X SIERRA 10.12.6

## Expected Behavior
The drop down should display the {{title}} field for the "Many-to-One" relationship

## Actual Behavior
The drop-down list seems to populate but comes out with BLANK OPTIONS 

## Steps to Reproduce
 1. Create a "Many-to-One" relationship between two tables
 2. Edit the table with the "Many-to-One" relationship and when adding items, the drop down is blank (see mp4 files attached that shows the setup and error)
<img width="640" alt="screen shot 2017-08-31 at 11 38 32 am" src="https://user-images.githubusercontent.com/11436060/29939519-f1f41e84-8e40-11e7-8738-b4c4d6c4ae93.png">
[the-error-many-to-one-relationship.zip](https://github.com/directus/directus/files/1268141/the-error-many-to-one-relationship.zip)

**Comment by WellingGuzman** [comment]
Hey @redandblackstar,

On `chapter.course` the `visible_columns` should be `title` as the `title` column from the Course table instead of `Course` the current column's name.

**Comment by redandblackstar** [comment]
I will try this right now!! Thank you for your feedback!!

**Comment by WellingGuzman** [comment]
no a problem, @redandblackstar Let us know if that fixes the issue.

**Comment by redandblackstar** [comment]
Looks like I had misunderstood the visible_columns input field—once I tried your suggestion the drop-down is no longer blank! THANK YOU VERY MUCH!! I will now close this ticket as this is not an issue!

:)
