### ISSUE TITLE
Dropdown menu selection ignored (not saved)

### ISSUE THREAD

**Issue by joelkennedy** [directus/directus#1780]
## Version Info
  - Directus version and branch: develop 3ae077c
  - PHP version: 7.1.6
  - MySQL version: 5.6.35
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: MacOS 10.13 with Safari 11 (sanity checked in Google Chrome 60.0.3112.113)

## Expected Behavior
The selected item of the dropdown menu should be saved

## Actual Behavior
The selected item is being ignored, and NULL is being saved in the database

## Steps to Reproduce
 1. Create a new table with a Dropdown interface as one of the columns
 2. Create a new item on the table, and select an item in the dropdown
 3. The item selected won't be saved

## Schema Dump, Logs, or Screenshots
Creating dropdown column
![screen shot 2017-09-02 at 12 46 19](https://user-images.githubusercontent.com/19573914/29995300-3122085c-8fde-11e7-8161-2d2aab169825.png)
Adding the options
![screen shot 2017-09-02 at 12 46 22](https://user-images.githubusercontent.com/19573914/29995302-36335102-8fde-11e7-9d58-2aae496209dc.png)
Create a new item and selecting Value 1
![screen shot 2017-09-02 at 12 46 28](https://user-images.githubusercontent.com/19573914/29995304-3a8a1f38-8fde-11e7-9c83-f7196ca3185c.png)
When editing, you can see the value was not saved
![screen shot 2017-09-02 at 12 48 13](https://user-images.githubusercontent.com/19573914/29995306-416c0870-8fde-11e7-9171-65c6ccf2c50e.png)
The row in the database reflects that
<img width="169" alt="screen shot 2017-09-02 at 12 48 02" src="https://user-images.githubusercontent.com/19573914/29995311-492d24f4-8fde-11e7-9f4d-92ad4617e653.png">

The issue occurs on both native and custom dropdown types.

**Comment by WellingGuzman** [comment]
Thanks for reporting this @joelkennedy, I've fixed this issue in the latest commit on `develop` give it a try and let me know if it didn't work for you.

Closed by https://github.com/directus/directus/commit/5c73f8335b2a2ed8728bc9511fb8dd87dd066e4e
