### ISSUE TITLE
Extension watcher doesn't respect directus:extension paths

### ISSUE THREAD

**Issue by JoshTheDerf** [directus/directus#17805]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

[`initializeWatcher()` (lines 274-276)](https://github.com/directus/directus/blob/main/api/src/extensions.ts#L274-L276) watches `EXTENSION_DIR/app.js`, `EXTENSION_DIR/api.js`, and/or `EXTENSION_DIR/index.js` regardless of the values configured in `package.json` under `directus:extension.path`. Fairly self-evident in the code.

This results in extensions not auto-reloading if those files are not present. (For example, stored in a `dist/` directory as is the default with `directus-extension build`.)

Likely related to #17694 

### To Reproduce

1. Create an operation-type extension in `extensions/operations` using `npm init directus-extension`.
   - This outputs to `dist/app.js` and `dist/api.js` by default.
3. Set the `EXTENSIONS_AUTO_RELOAD` environment variable to `true`.
4. Start directus. It will either display a warning and stack trace indicating a failure to load the extension files at `EXTENSION_DIR/app.js|api.js`, or load the extension but fail to auto-reload it. (I suspect the former might be a separate bug.)

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
We never supported custom dist paths for extensions installed via local "typed" extension folders (`extensions/{operations,...}`).

Besides that, this installation type is going to be deprecated soon. Instead, for local installation of extensions, the recommended way is to put extension packages into the root of the `extensions/` folder: https://docs.directus.io/extensions/installing-extensions.html#installing-through-the-extensions-folder

With local extension packages, custom paths via `directus:extension` are supported and watched as expected. See also https://docs.directus.io/extensions/creating-extensions.html#extension-folder-structure.

Furthermore, the extensions watcher has received quite some improvements in the meantime.
