### ISSUE TITLE
Docker cannot run clean installation.

### ISSUE THREAD

**Issue by co2nunes** [directus/directus#17806]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

I cannot execute a clean Docker install of Directus 9.
```
#!/bin/sh

rm -r uploads
rm -r extensions
rm -r postgresql-container
docker compose down
mkdir postgresql-container
cd postgresql-container
mkdir database
cd ..
docker compose up
```

then It returns 

postgresql-container             | You are now connected to database "directus" as user "directus".
postgresql-container             | CREATE EXTENSION
directuslocal-postgresql-bind-data-directus-container     | [14:42:06.352] ERROR: Can't connect to the database.
directuslocal-postgresql-bind-data-directus-container     | [14:42:06.352] ERROR: connect ECONNREFUSED 172.24.0.3:5432
directuslocal-postgresql-bind-data-directus-container     |     err: {
directuslocal-postgresql-bind-data-directus-container     |       "type": "Error",
directuslocal-postgresql-bind-data-directus-container     |       "message": "connect ECONNREFUSED 172.24.0.3:5432",
directuslocal-postgresql-bind-data-directus-container     |       "stack":
directuslocal-postgresql-bind-data-directus-container     |           Error: connect ECONNREFUSED 172.24.0.3:5432
directuslocal-postgresql-bind-data-directus-container     |               at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
directuslocal-postgresql-bind-data-directus-container     |       "errno": -111,
directuslocal-postgresql-bind-data-directus-container     |       "code": "ECONNREFUSED",
directuslocal-postgresql-bind-data-directus-container     |       "syscall": "connect",
directuslocal-postgresql-bind-data-directus-container     |       "address": "172.24.0.3",
directuslocal-postgresql-bind-data-directus-container     |       "port": 5432
directuslocal-postgresql-bind-data-directus-container     |     }

### To Reproduce

$ docker compose down
 ⠿ Container directuslocal-postgresql-bind-data-directus-container     Removed                                                                                                                                                                                         0.0s
 ⠿ Container postgresql-container             Removed                                                                                                                                                                                         0.3s
 ⠿ Container redis-cache-directuslocal-postgresql-bind-data-container  Removed                                                                                                                                                                                         0.3s
 ⠿ Network directuslocal-postgresql-bind-data_directus-co2             Removed                                                                                                                                                                                         0.1s
[+] Running 4/5
 ⠿ Network directuslocal-postgresql-bind-data_directus-co2                                                                                                                          Created                                                                            0.1s
 ⠿ Container redis-cache-directuslocal-postgresql-bind-data-container                                                                                                               Started                                                                            0.6s
 ⠿ Container postgresql-container                                                                                                                          Started                                                                            0.6s
 ⠇ database The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                                                                    0.0s
 ⠿ Container directuslocal-postgresql-bind-data-directus-container                                                                                                                  Started                                                                            0.7s
[+] Running 3/0
 ⠿ Container redis-cache-directuslocal-postgresql-bind-data-container  Running                                                                                                                                                                                         0.0s
 ⠿ Container postgresql-container             Running                                                                                                                                                                                         0.0s
 ⠿ Container directuslocal-postgresql-bind-data-directus-container     Running                                                                                                                                                                                         0.0s
Attaching to directuslocal-postgresql-bind-data-directus-container, postgresql-container, redis-cache-directuslocal-postgresql-bind-data-container
postgresql-container             | The files belonging to this database system will be owned by user "postgres".
postgresql-container             | This user must also own the server process.
postgresql-container             |
postgresql-container             | The database cluster will be initialized with locale "en_US.utf8".
postgresql-container             | The default database encoding has accordingly been set to "UTF8".
postgresql-container             | The default text search configuration will be set to "english".
postgresql-container             |
postgresql-container             | Data page checksums are disabled.
postgresql-container             |
postgresql-container             | fixing permissions on existing directory /var/lib/postgresql/directuslocal-postgresql-bind-data ... ok
postgresql-container             | creating subdirectories ... ok
postgresql-container             | selecting dynamic shared memory implementation ... posix
postgresql-container             | selecting default max_connections ... 100
postgresql-container             | selecting default shared_buffers ... 128MB
postgresql-container             | selecting default time zone ... Etc/UTC
postgresql-container             | creating configuration files ... ok
directuslocal-postgresql-bind-data-directus-container     | [14:41:41.312] INFO: Initializing bootstrap...
postgresql-container             | running bootstrap script ... ok
postgresql-container             | performing post-bootstrap initialization ... ok
postgresql-container             | syncing data to disk ... ok
postgresql-container             |
postgresql-container             | initdb: warning: enabling "trust" authentication for local connections
postgresql-container             | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
postgresql-container             |
postgresql-container             | Success. You can now start the database server using:
postgresql-container             |
postgresql-container             |     pg_ctl -D /var/lib/postgresql/directuslocal-postgresql-bind-data/ -l logfile start
postgresql-container             |
postgresql-container             | waiting for server to start....2023-03-15 14:41:50.028 UTC [127] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
postgresql-container             | 2023-03-15 14:41:50.032 UTC [127] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgresql-container             | 2023-03-15 14:41:50.055 UTC [135] LOG:  database system was shut down at 2023-03-15 14:41:48 UTC
postgresql-container             | 2023-03-15 14:41:50.092 UTC [127] LOG:  database system is ready to accept connections
postgresql-container             |  done
postgresql-container             | server started
postgresql-container             | CREATE DATABASE
postgresql-container             |
postgresql-container             |
postgresql-container             | /usr/local/bin/docker-entrypoint.sh: sourcing /docker-entrypoint-initdb.d/10_postgis.sh
postgresql-container             | CREATE DATABASE
postgresql-container             | Loading PostGIS extensions into template_postgis
postgresql-container             | CREATE EXTENSION
postgresql-container             | CREATE EXTENSION
postgresql-container             | You are now connected to database "template_postgis" as user "directus".
postgresql-container             | CREATE EXTENSION
postgresql-container             | CREATE EXTENSION
postgresql-container             | Loading PostGIS extensions into directus
postgresql-container             | CREATE EXTENSION
postgresql-container             | CREATE EXTENSION
postgresql-container             | You are now connected to database "directus" as user "directus".
postgresql-container             | CREATE EXTENSION
directuslocal-postgresql-bind-data-directus-container     | [14:42:06.352] ERROR: Can't connect to the database.
directuslocal-postgresql-bind-data-directus-container     | [14:42:06.352] ERROR: connect ECONNREFUSED 172.24.0.3:5432
directuslocal-postgresql-bind-data-directus-container     |     err: {
directuslocal-postgresql-bind-data-directus-container     |       "type": "Error",
directuslocal-postgresql-bind-data-directus-container     |       "message": "connect ECONNREFUSED 172.24.0.3:5432",
directuslocal-postgresql-bind-data-directus-container     |       "stack":
directuslocal-postgresql-bind-data-directus-container     |           Error: connect ECONNREFUSED 172.24.0.3:5432
directuslocal-postgresql-bind-data-directus-container     |               at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
directuslocal-postgresql-bind-data-directus-container     |       "errno": -111,
directuslocal-postgresql-bind-data-directus-container     |       "code": "ECONNREFUSED",
directuslocal-postgresql-bind-data-directus-container     |       "syscall": "connect",
directuslocal-postgresql-bind-data-directus-container     |       "address": "172.24.0.3",
directuslocal-postgresql-bind-data-directus-container     |       "port": 5432
directuslocal-postgresql-bind-data-directus-container     |     }
postgresql-container             | CREATE EXTENSION
postgresql-container             |
postgresql-container             | 2023-03-15 14:42:07.234 UTC [127] LOG:  received fast shutdown request
postgresql-container             | 2023-03-15 14:42:07.235 UTC [127] LOG:  aborting any active transactions
postgresql-container             | waiting for server to shut down....2023-03-15 14:42:07.253 UTC [127] LOG:  background worker "logical replication launcher" (PID 141) exited with exit code 1
postgresql-container             | 2023-03-15 14:42:07.254 UTC [131] LOG:  shutting down
postgresql-container             | 2023-03-15 14:42:07.256 UTC [131] LOG:  checkpoint starting: shutdown immediate
directuslocal-postgresql-bind-data-directus-container     | npm notice
directuslocal-postgresql-bind-data-directus-container     | npm notice New minor version of npm available! 9.5.0 -> 9.6.1
directuslocal-postgresql-bind-data-directus-container     | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.1>
directuslocal-postgresql-bind-data-directus-container     | npm notice Run `npm install -g npm@9.6.1` to update!
directuslocal-postgresql-bind-data-directus-container     | npm notice
directuslocal-postgresql-bind-data-directus-container exited with code 1
postgresql-container             | ..2023-03-15 14:42:09.354 UTC [131] LOG:  checkpoint complete: wrote 4469 buffers (27.3%); 0 WAL file(s) added, 0 removed, 2 recycled; write=2.062 s, sync=0.006 s, total=2.098 s; sync files=613, longest=0.001 s, average=0.001 s; distance=34811 kB, estimate=34811 kB
postgresql-container             | 2023-03-15 14:42:09.413 UTC [127] LOG:  database system is shut down
postgresql-container             |  done
postgresql-container             | server stopped
postgresql-container             |
postgresql-container             | PostgreSQL init process complete; ready for start up.
postgresql-container             |
postgresql-container             | 2023-03-15 14:42:09.607 UTC [1] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
postgresql-container             | 2023-03-15 14:42:09.611 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgresql-container             | 2023-03-15 14:42:09.611 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgresql-container             | 2023-03-15 14:42:09.615 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgresql-container             | 2023-03-15 14:42:09.655 UTC [190] LOG:  database system was shut down at 2023-03-15 14:42:09 UTC
postgresql-container             | 2023-03-15 14:42:09.692 UTC [1] LOG:  database system is ready to accept connections

CTRL+C ( break)

$ docker compose up

then it works, but in two steps.

Here is my YML file: 

```
version: '3.1'
services:
  database:
    container_name: postgresql-container
    image: postgis/postgis:latest
    env_file:
    - .env
    networks:
      - directus-co2
    volumes:
    - type: bind
      source: './postgresql-container/database'
      target: /var/lib/postgresql/directus
  cache:
    container_name: redis-cache-directus-container
    image: redis:6
    networks:
      - directus-co2

  directus:
    container_name: directus-directus-container
    image: directus/directus:latest
    ports:
      - 8053:8053
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    networks:
      - directus-co2
    depends_on:
      - cache
      - database
    env_file:
      - .env
networks:
  directus-co2:
    driver: bridge

volumes:
  postgresql-container:
```

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Please follow the official guide: https://docs.directus.io/self-hosted/docker-guide.html

**Comment by co2nunes** [comment]
The example does not survive a docker compose down.
It should contain bind or volume mounting and that is my why all data gets lost and overwritten when docker-compose up.
