### ISSUE TITLE
Period in search bar throws error

### ISSUE THREAD

**Issue by vonadz** [directus/directus#17807]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

Typing a period (.) into the search bar for the File Library throws an error. See screenshot below.

![period-error](https://user-images.githubusercontent.com/16930123/225445745-d42afe78-1522-4b7d-ad7f-9a21162945e3.png)

If you escape it using a backslash, you don't get the error. See screenshot below.

![period-bug-fixed](https://user-images.githubusercontent.com/16930123/225446224-cbe6dcf6-b5c9-467e-9cc4-c14a06d2b1e0.png)

### To Reproduce

Spin up a fresh instance of directus.
Type a period into the search bar for the File Library.

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Comment by vonadz** [comment]
> We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

@paescuj I've updated the steps to reproduce and information on the error. Posted this last night when it was late and rushed it, my bad. It looks like the error is to do with the PostgreSQL driver. Probably related to `("directus_files"."filesize" = $7)` in the SQL query, since that's the only bigint on files that I could find.
