### ISSUE TITLE
GraphQL error: Cannot set properties of undefined (setting 'code')

### ISSUE THREAD

**Issue by nodeworks** [directus/directus#17817]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

There is an issue with the GraphQL service that when there's an error, and Directus tries to format that error, it fails because a property on the error doesn't exist. It's trying to set "code" on the "extensions" property of the error but "extensions" doesn't exist which gives the error below.

![Screenshot 2023-03-16 at 10 54 44 AM](https://user-images.githubusercontent.com/5272855/225657144-311c23fd-1374-498a-b76a-7ce3872bbf31.png)
![Screenshot 2023-03-16 at 10 54 54 AM](https://user-images.githubusercontent.com/5272855/225657149-9d559acc-9031-4241-81bb-42e7ecc025ca.png)

### To Reproduce

I'm using SQL Server, try making a graphql request that errors out.

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Would you be able to provide an exact reproduction?

**Comment by nodeworks** [comment]
I can’t as the data is sensitive. I can do a private screenshare though if that would help.

**Comment by paescuj** [comment]
> I can’t as the data is sensitive. I can do a private screenshare though if that would help.

if possible, simply some steps like the following example would be enough:
1. Create collection "A"
2. Create input field "B"
3. ...
4. Perform GraphQL mutation:
    ```graphql
    mutation {
      update_a_item(id: 15, data: { b: "Example" }) {
        id
        b
      }
    }
    ```

**Comment by nodeworks** [comment]
I think it might be specific to MS SQL. Anything from the graphql side that triggers an error (could be any error) that hits the formatError function causes the problem.

File: /api/src/services/graphql/index.ts
Function: formatError()

**Comment by nodeworks** [comment]
It seems as though the "extensions" property on the error is set on the BaseException class:

```packages/shared/src/exceptions/base.ts```

However, when it's trying to extract the error and it can't find the error code it just straight up returns the error object:

![Screenshot 2023-03-20 at 3 11 06 PM](https://user-images.githubusercontent.com/5272855/226442278-fba1bf80-2bd6-49d2-a68e-b96ba6585fe0.png)

Whereas it should be wrapping it in a new exception that extends the BaseException.

**Comment by nodeworks** [comment]
These are currently the error codes for MSSQL for the Directus dialects:

```
enum MSSQLErrorCodes {
	FOREIGN_KEY_VIOLATION = 547,
	NOT_NULL_VIOLATION = 515,
	NUMERIC_VALUE_OUT_OF_RANGE = 220,
	UNIQUE_VIOLATION = 2601, // or 2627
	VALUE_LIMIT_VIOLATION = 2628,
}
```

The error I hit had a code of 544. So we can either:
1. Wrap the generic error in a new exception that extends the BaseException when the error code isn't found / used.
2. Populate the MSSQLErrorCodes enum with more available codes.
3. Utilize the PR I made where we just check for the "extensions" property first before trying to access it.
