### ISSUE TITLE
connecting multiple collections to the same M2A junction table is not working as expected

### ISSUE THREAD

**Issue by NigmaX** [directus/directus#17844]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

Creating a M2A relation on multiple collections with the **same junction table** messes up the data and the M2A interface data that is being displayed/loaded.

Question:
Are we supposed to have the ability to connect multiple collections to the same junction table?
If we do, then it's not working correctly.

### To Reproduce

create collection resource_1
create collection resource_2
create collection resource_3

create collection test_1
create collection test_2

create a M2A field on test_1 call the junction table any_any (choose resource_1 and resource_2) (use M2A interface)
create a M2A field on test_2 use the junction table any_any (choose resource_1, *_2 and *_3) (use M2A interface)

Open test_1 collection and click on the create 

**expected**
you will see only resource_1 and resource_2 as option
you will be able to save
it will be loaded correctly whenever you edit any collection that is using the any_any table

**actual**
you will see only resource_1 and resource_2 and resource_3 (although it was not selected)
saving might give you errors (on one machine, it worked. On another, it didn't)
if you try to edit the field (on either collection), it will affect all the collections that are using it (and will mess data that was already saved).

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Thanks for opening this issue!

> Question:
> Are we supposed to have the ability to connect multiple collections to the same junction table?

No, I don't think this is an intended use case.
if there is a need for this, please fill out a [feature request](https://github.com/directus/directus/discussions/new?category=feature-requests) for it. This would also help us understand why this is needed.
