### ISSUE TITLE
Error message `collection xxx doesn't exist` displayed when creating a new collection

### ISSUE THREAD

**Issue by Eshaftri** [directus/directus#17845]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

When attempting to create a new collection, an error message stating `collection xxx doesn't exist` is displayed, even though the collection is intended to be newly created.

<img width="852" alt="Screenshot 2023-03-19 at 10 01 48 PM" src="https://user-images.githubusercontent.com/21362631/226208773-051f8572-1d68-44ab-bf13-7b7e45c6ee13.png">

However, after a few seconds, the newly created collection does appear. Nonetheless, when trying to create a Many-to-Many (M2M) field, an error message stating `you don't have permission to access this` is displayed, preventing the creation of the M2M field.

<img width="683" alt="Screenshot 2023-03-19 at 9 59 51 PM" src="https://user-images.githubusercontent.com/21362631/226208644-e3e0ee19-fcd0-4404-adb5-b7cc9303450e.png">

### What version of Directus are you using?
v9.23.1

### What database are you using?
Postgres

### What browser are you using?
chrome, firefox

### How are you deploying Directus?
Self Hosted in IBM cloudis 

### To Reproduce

1- Navigate to the Directus admin interface.
2- Attempt to create a new collection by clicking on "New Collection" or the appropriate button.
3- Observe the error message collection xxx doesn't exist displayed on the screen.
4- Wait for a few seconds and notice that the newly created collection does appear.
5- Try to create a Many-to-Many (M2M) field within the new collection.
6- Observe the error message stating "you don't have permission to access this", preventing the creation of the M2M field.

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

Is this happening every time? Could it somehow be related to IBM cloud?
