### ISSUE TITLE
M2O dropdowns don't show all entries in old tables from 6.3.6 in 6.4.1

### ISSUE THREAD

**Issue by Zaelot** [directus/directus#1784]
## Version Info
  - Directus version and branch: 6.4.1
  - PHP version: PHP 7.1.8
  - MySQL version: MariaDB 10.1
  - Web server: Apache
  - OS: Debian Jessie

## Expected Behavior
Able to filter the old *Many to One* Dropdowns for the desired entry.

## Actual Behavior
Only shows the first 30 entries, and doesn't let you filter them at all. Also changing the filter type to text input also doesn't do anything.

## Steps to Reproduce
 1. Have an old 6.3.6 version, and create two tables, fill them with some entries (over 30), and make a Many to One entry in one of them referencing the other.
 2. Update to 6.4.1, create some new entries in the linked table.
 3. Try to select the newly created entries in the Many to One dropdown interface.

**Comment by Zaelot** [comment]
Oh, and can't browse the entries in the tables themselves. the small handy `< and >` arrows have disappeared.

**Comment by Zaelot** [comment]
Workaround is to change the type to _Many to One Typehead_.

**Comment by benhaynes** [comment]
Ahh, pagination is missing on the overlay listings (eg Choose Item)? @WellingGuzman, are these lazy-loading too?

**Comment by dsivokhin** [comment]
Hello, I'am have same issue. If M2O Dropdown have more than `global api limit` not all `option` loads. I see settings `Results limit` for O2M, 
![default](https://user-images.githubusercontent.com/4669992/30275025-7e225c7a-9708-11e7-9aa9-82a127c87824.png)
maybe add this settings to M2O Dropdown ?

**Comment by WellingGuzman** [comment]
Thanks @dsivokhin, I see what's the problem.

**Comment by WellingGuzman** [comment]
We have added a `result_limit` option (default to `100`) to the many to one interface.

Closed by https://github.com/directus/directus/commit/1f969c5f7606fa8502344e66cfeb6607b52a8f0c
