### ISSUE TITLE
Flows --> Send-notification user = null after closing edit-drawer

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#17849]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

When adding a "set notification" step to a flow, edit the user and close the steps side-drawer the user get's reset to null. There's no error in the console.

When editing the raw-value directly it is kept

### To Reproduce

https://user-images.githubusercontent.com/46492597/226331106-de82386b-3f22-49f9-9af2-9b172c8cc594.mov

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Nitwel** [comment]
You have to press enter to add the user UUID as the placeholder text sais. But I agree that this is a very confusing on first look and also that the placeholder disappears when you type something into it.
