### ISSUE TITLE
`FLOWS_EXEC_ALLOWED_MODULES` does not work with node builtins like node:crypto

### ISSUE THREAD

**Issue by work-reimarrosas** [directus/directus#17855]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

I'm trying to process data sent via POST to a Flow but in order to accomplish this, I need to use a Run Script operation and import the node:crypto module.

Problem:
When I use the code: `const crypto = require('crypto')` in a Run Script within the Flow, it results with the error: "VMError - cannot find module 'crypto'". Even when I add the env variable `FLOWS_EXEC_ALLOWED_MODULES=crypto`, it still results with the same error.

Based on current implementation: https://github.com/directus/directus/blob/main/api/src/operations/exec/index.ts, it seems like the environment variable I used only works with external (npm) modules and not node builtins.

### To Reproduce

1. Create a Run Script operation inside a Flow.
2. Require the node:crypto module with `const crypto = require('crypto')`

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Built-ins are blocked by default and needs to be explicitly allowed via `require.builtin` (see https://github.com/patriksimek/vm2#nodevm). So the solution would probably be something like proposed in #17821.
