### ISSUE TITLE
Strict-Transport-Security middleware should use `includeSubDomains` instead of `includeSubdomains`.

### ISSUE THREAD

**Issue by danestves** [directus/directus#17857]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

Every time I start my Directus application, I receive this warning:

```bash
Strict-Transport-Security middleware should use `includeSubDomains` instead of `includeSubdomains`. (The correct one has an uppercase "D".)
```

### To Reproduce

Set these two environment variables

```env
HSTS_ENABLED=true
HSTS_INCLUDE_SUBDOMAINS=true
```

And run the application

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
You should be able to get the correct property name by separating `SUB` and `DOMAINS` with an underscore:
```
HSTS_INCLUDE_SUB_DOMAINS=true
```

See https://docs.directus.io/self-hosted/config-options.html#type-casting-and-nesting

**Comment by danestves** [comment]
Thank you! Was my fault
