### ISSUE TITLE
Global Settings, Row per Page affecting API's

### ISSUE THREAD

**Issue by Zaelot** [directus/directus#1786]
## Version Info
  - Directus version and branch: 6.4.1
  - PHP version: PHP 7.1.8
  - MySQL version: MariaDB 10.1
  - Web server: Apache
  - OS: Debian Jessie

## Expected Behavior
`/api/1.1/tables/my_table/rows/` returns all of the entries.

## Actual Behavior
Instead it limits it to the **Settings** > **Global** > _Rows per Page_ (30).
(More specific API queries encounter the same problem.) Adding `?limit=200` works as a workaround.

## Steps to Reproduce
 1. Create more than 30 entries.
 2. Query table.
 3. Only see the first 30 entries.

## Notes
Possibly related to #1720

**Comment by WellingGuzman** [comment]
Hey @Zaelot, can you provide us a schema example? I can't reproduce this issue, it's working as expected.

Can you upgrade to 6.4.2 and see if it still happening?

**Comment by WellingGuzman** [comment]
Re reading this again, isn't this the expected behavior? if you set the query limit to `30` the API will get 30 items in all fetch unless `limit` or `perPage` are set.

This is a global setting, if this is related to an specific interface then we can get options to the table. (related #1784)
