### ISSUE TITLE
While using stores in extension store can able to get

### ISSUE THREAD

**Issue by aravindkmr007** [directus/directus#17863]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

<script lang="ts" setup>
import { useStores } from '@directus/extensions-sdk';
import { computed } from 'vue';
import { inject } from 'vue';
import { ref } from 'vue';
const { useCollectionsStore, useFieldsStore } = useStores();

interface FieldOnChange {
	(e: 'input', value: string): void;
}
function useCollection(collectionKey: string) {
	const collectionsStore = useCollectionsStore();
	const fieldsStore = useFieldsStore();

	const collection = ref(collectionKey);
	const info = computed(() => {
		return collectionsStore.collections.find(({ collection: key }) => key === collection.value) || null;
	});

	const fields = computed(() => {
		if (!collection.value) return [];
		return fieldsStore.getFieldsForCollectionSorted(collection.value);
	});

	const defaults = computed(() => {
		if (!fields.value) return {};

		const defaults: Record<string, any> = {};

		for (const field of fields.value) {
			if (field.schema?.default_value) {
				defaults[field.field] = field.schema.default_value;
			}
		}

		return defaults;
	});

	const primaryKeyField = computed(() => {
		return (
			fields.value.find((field) => field.collection === collection.value && field.schema?.is_primary_key === true) ||
			null
		);
	});

	const userCreatedField = computed(() => {
		return fields.value?.find((field) => (field.meta?.special || []).includes('user_created')) || null;
	});

	const sortField = computed(() => {
		return info.value?.meta?.sort_field || null;
	});

	const isSingleton = computed(() => {
		return info.value?.meta?.singleton === true;
	});

	const accountabilityScope = computed(() => {
		if (!info.value) return null;
		if (!info.value.meta) return null;
		return info.value.meta.accountability;
	});

	return { info, fields, defaults, primaryKeyField, userCreatedField, sortField, isSingleton, accountabilityScope };
}

const value = ref('');
const api = inject('api');

api.get('/app/src/stores').then((res) => {
	console.log(res, 'aa');

	// this.collections = res.data.data;
});

const props = defineProps({
	value: {
		type: String,
		default: null,
	},
	fields: {
		type: Array,
		default: undefined,
	},
});

const emit = defineEmits<FieldOnChange>();
function handleChange(value: string) {
	console.log(useCollection('orders'), 'arafindddd');
	// const { info: collectionInfo, primaryKeyField } = useCollectionsStore('orders');
	// console.log(collectionInfo, primaryKeyField);
	emit('input', value);
}
</script>

### To Reproduce

<script lang="ts" setup>
import { useStores } from '@directus/extensions-sdk';
import { computed } from 'vue';
import { inject } from 'vue';
import { ref } from 'vue';
const { useCollectionsStore, useFieldsStore } = useStores();

interface FieldOnChange {
	(e: 'input', value: string): void;
}
function useCollection(collectionKey: string) {
	const collectionsStore = useCollectionsStore();
	const fieldsStore = useFieldsStore();

	const collection = ref(collectionKey);
	const info = computed(() => {
		return collectionsStore.collections.find(({ collection: key }) => key === collection.value) || null;
	});

	const fields = computed(() => {
		if (!collection.value) return [];
		return fieldsStore.getFieldsForCollectionSorted(collection.value);
	});

	const defaults = computed(() => {
		if (!fields.value) return {};

		const defaults: Record<string, any> = {};

		for (const field of fields.value) {
			if (field.schema?.default_value) {
				defaults[field.field] = field.schema.default_value;
			}
		}

		return defaults;
	});

	const primaryKeyField = computed(() => {
		return (
			fields.value.find((field) => field.collection === collection.value && field.schema?.is_primary_key === true) ||
			null
		);
	});

	const userCreatedField = computed(() => {
		return fields.value?.find((field) => (field.meta?.special || []).includes('user_created')) || null;
	});

	const sortField = computed(() => {
		return info.value?.meta?.sort_field || null;
	});

	const isSingleton = computed(() => {
		return info.value?.meta?.singleton === true;
	});

	const accountabilityScope = computed(() => {
		if (!info.value) return null;
		if (!info.value.meta) return null;
		return info.value.meta.accountability;
	});

	return { info, fields, defaults, primaryKeyField, userCreatedField, sortField, isSingleton, accountabilityScope };
}

const value = ref('');
const api = inject('api');

api.get('/app/src/stores').then((res) => {
	console.log(res, 'aa');

	// this.collections = res.data.data;
});

const props = defineProps({
	value: {
		type: String,
		default: null,
	},
	fields: {
		type: Array,
		default: undefined,
	},
});

const emit = defineEmits<FieldOnChange>();
function handleChange(value: string) {
	console.log(useCollection('orders'), 'arafindddd');
	// const { info: collectionInfo, primaryKeyField } = useCollectionsStore('orders');
	// console.log(collectionInfo, primaryKeyField);
	emit('input', value);
}
</script>

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Could you format that a bit more readable? But judging from the comment you left here https://github.com/directus/directus/issues/9802#issuecomment-1477700630
You are doing `const { useCollectionsStore, useFieldsStore } = useStores();` in the root of you're file but you should be using this inside the context of your component like so
```js
<script lang="ts">
import { defineComponent, PropType, computed } from 'vue';

// Here won't work
// const { useCollectionsStore, useFieldsStore } = useStores();

export default defineComponent({
    props: {
    },
    emits: ['input'],
    setup(props, { emit }) {
        // here you can use stores
        const { useCollectionsStore, useFieldsStore } = useStores();
        //... other code
    }
});
</script>
```
Happy to re-open if that doesnt solve your problem 😄

**Comment by AxeemHaider** [comment]
How you can use the `useCollectionsStore` inside `definePanel` custom extension ?
