### ISSUE TITLE
Unable to pass filter type to filter hook register function

### ISSUE THREAD

**Issue by 4erem6a** [directus/directus#17870]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

Typed filter handler is not assignable to the parameter of `register.filter`.

### To Reproduce

```typescript
import { defineHook } from "@directus/extensions-sdk"
import { FilterHandler } from "@directus/shared/types"

type MyType = {}

declare const filterHandler: FilterHandler<MyType>

const hook = defineHook((register, context) => {
	register.filter("event", filterHandler) // Error: FilterHandler<MyType> is not assignable to FilterHandler
})
```

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Thanks for opening the issue! However I think this concern should be better submitted as a feature request, so we understand the idea and motivation behind it. If you're still interested in this, do kindly open a [new feature request](https://github.com/directus/directus/discussions/new?category=feature-requests) instead. I'll proceed to close this issue, thanks again!

**Comment by sequencerr** [comment]
@4erem6a Evgeny? Hello friend?
