### ISSUE TITLE
directus.auth.password.request with custom address errors

### ISSUE THREAD

**Issue by norricorp** [directus/directus#17878]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

The following works
await directus.auth.password.request($emailName);
The user receives an email.

But using
await directus.auth.password.request($emailName, import.meta.env.VITE_SVELTE_URL + "/resetpw");
does not work. In console get
Uncaught (in promise) Error: Url "http://localhost:3000/resetpw" can't be used to reset passwords.

I have searched through the sdk and directus github repos for that term with no hits. Have I misunderstood what custom address means? Am I using it incorrectly? If I replace with actual string rather than variable then same result.

### To Reproduce

Use the password.request api

### Hosting Strategy

Self-Hosted (Custom)

**Comment by azrikahar** [comment]
Make sure to configure the [`PASSWORD_RESET_URL_ALLOW_LIST` env variable](https://docs.directus.io/self-hosted/config-options.html#security) as noted in the docs 👍 it should be under the custom address code sample:

![image](https://user-images.githubusercontent.com/42867097/226849959-3f54f0d0-3e07-444f-8b55-e6ba164609dc.png)

**Comment by norricorp** [comment]
Hi @azrikahar,
thanks for this. Really should read all of the manual!
Anyway, add to .env
PASSWORD_RESET_URL_ALLOW_LIST="http://localhost:3000/resetpw"
(and could add other addresses as well as comma seperated list?)
restarted directus

Result in console.log is 
Uncaught (in promise) Error: Url "http://localhost:3000/resetpw" can't be used to reset passwords.

And in directus log
[09:08:35.738] WARN: Invalid URL used "http://localhost:3000/resetpw"
[09:08:35.738] WARN: Invalid URL used "http://localhost:3000/resetpw"
[09:08:35] POST /auth/password/request 400 12ms

So I am still not undertanding something

**Comment by azrikahar** [comment]
@norricorp I've added a screen capture here, and we can see I first tried commenting out `PASSWORD_RESET_URL_ALLOW_LIST` to trigger the same "can't be used to reset passwords" error. However after I uncomment it and restart Directus, it works as expected:

https://user-images.githubusercontent.com/42867097/226872661-571a9986-43ca-4e72-87a9-4226ffc91d59.mp4

so I can only assume your env change(s) aren't properly applied. Do also make sure you are on the latest version, as my test above is on `9.23.1`.

**Comment by norricorp** [comment]
Stop the presses!
OK, it does work if there is a single entry for PASSWORD_RESET_URL_ALLOW_LIST. But if there are multiple entries then it doesn't work
So I have now PASSWORD_RESET_URL_ALLOW_LIST="http://localhost:3000/resetpw", "http://localhost:3000/resetpwx"
and that fails.

**Comment by rijkvanzanten** [comment]
@norricorp Take a peak at https://docs.directus.io/self-hosted/config-options.html#type-casting-and-nesting, that goes over how to provide a list of values to an env var 👍🏻  🙂

**Comment by norricorp** [comment]
So PASSWORD_RESET_URL_ALLOW_LIST is a string of comma separated entries but CORS_ORIGIN is a list of comma separated strings. As I had already used the latter, I used the same format for the former.
Perhaps the docs should mention this.
But most importantly, thank you for the patience and work you have put into this.
I will implement it in the morning (updating this on phone)

**Comment by rijkvanzanten** [comment]
No, they're both the same 👍🏻

**Comment by azrikahar** [comment]
> So I have now PASSWORD_RESET_URL_ALLOW_LIST="http://localhost:3000/resetpw", "http://localhost:3000/resetpwx"

It's important to note that env variables are ultimately strings when they are being read. It's just that Directus (or any other frameworks/applications) will try to process said strings to what they expect.

So based on your current config of:

```env
PASSWORD_RESET_URL_ALLOW_LIST="http://localhost:3000/resetpw", "http://localhost:3000/resetpwx"
```

assuming all the quotes and spaces are exactly what you posted, you are actually creating a string of `http://localhost:3000/resetpw", "http://localhost:3000/resetpwx` (note the quotation marks, or lack thereof).

That string will then be parsed into the following when we split based on comma:

```js
[
  'http://localhost:3000/resetpw"',
  ' "http://localhost:3000/resetpwx'
]
```

which is very likely why your reset url is not matching because they are malformed.

The following value should be correct:

```env
PASSWORD_RESET_URL_ALLOW_LIST="http://localhost:3000/resetpw,http://localhost:3000/resetpwx"
```

**Comment by norricorp** [comment]
Thank you to both @azrikahar and @rijkvanzanten. 
In reply to @rijkvanzanten last comment, they are not the same in my code. I have CORS_ORIGIN as a list of strings and that works. But PASSWORD_RESET_URL_ALLOW_LIST is now a string of values and that now works.
And the docs do describe the two differently. But examples would be useful.
