### ISSUE TITLE
Can't press enter in tags on settings modal

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1788]
## Version Info
  - Directus version and branch: Latest develop

## Expected Behavior
Pressing enter inside a tags interface should add the tag

## Actual Behavior
Pressing enter saves and closes the modal

## Steps to Reproduce
 1. Add a color interface (or any which uses a tags interface for a setting)
 2. Try adding a tag by typing something and pressing enter

**Comment by benhaynes** [comment]
👍
