### ISSUE TITLE
Invite user error response

### ISSUE THREAD

**Issue by ericlemans** [directus/directus#17884]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

1) A user is invited (https://docs.directus.io/reference/system/users.html#invite-a-new-user)
2) User creates password and backend changes status from "Invited" to "Active"
3) User forgets that he/she has already set a password and tries to activate the account again by creating a password with the provided link in the invite email
4) Error response is: "Email address email@example.com hasn't been invited."

Expected outcome: The error message should read "User has already activated the account"

Context: The email has a custom URL that sends them to a custom landing page.

### To Reproduce

1) Send an invitation to a user
2) Create password
3) After activating account, go back to invitation email and click again on activate account
4) Try creating password again

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
This is currently a security choice to prevent account enumeration not a bug. However this could be a good feature request! 😄
