### ISSUE TITLE
Can't find filters on O2M and other relational field when updating them

### ISSUE THREAD

**Issue by ImaCrea** [directus/directus#17885]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

Hi there,

I just noticed I can't the filter module that should appear on relational field in the interface section when updating a field.

According to https://github.com/directus/directus/pull/9135 this should appear :
![138983684-027706f9-a55d-4268-aee2-9b16ecc11632](https://user-images.githubusercontent.com/764332/226948688-1d46a175-16c4-4e0d-a7fb-2e2c617eda33.png)

And it's available in deed when creating a new field. But, when I want to update an already in place relational field, it doesn't seem to appear. Here's an example:
<img width="839" alt="Capture d’écran 2023-03-22 à 16 06 44" src="https://user-images.githubusercontent.com/764332/226949116-6d44dd7d-7c12-4b28-be64-2f9c0909d8ee.png">

### To Reproduce

- Open a relational field in place to edit its setting
- Go into the "interface" section
- See there's no filter settings available

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by ImaCrea** [comment]
Ok, sorry. I just understood something which wasn't clear to me in this feature :

![bugDirectusFilter](https://user-images.githubusercontent.com/764332/227520050-4a3cdd89-85eb-49e2-99f5-458411ada9e9.gif)

From what happens in this capture, when trying to edit an O2M relation field the filter is linked to the possibility to select or not related items.

But what I thought is that I could have a filter for related items diplayed in my table so I could, for example, exclude archived items. I understand this filter applies to the items available in the selection filter but not to the displayed items in the table.

Is that correct?

**Comment by rijkvanzanten** [comment]
Ahh yeah that's correct. The filter controls what items you can _select_, not what items are previewed. That'd be a new feature! (For which a [feature request](https://github.com/directus/directus/discussions/new?category=feature-requests) is very welcome 🙂

**Comment by ImaCrea** [comment]
> Ahh yeah that's correct. The filter controls what items you can _select_, not what items are previewed. That'd be a new feature! (For which a [feature request](https://github.com/directus/directus/discussions/new?category=feature-requests) is very welcome 🙂

And here you go -> https://github.com/directus/directus/discussions/17952
