### ISSUE TITLE
Sorting records won't work if user role has ALL permissions on that collection

### ISSUE THREAD

**Issue by kolosseo** [directus/directus#17883]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

Roled users (which are not administrator) have no sorting option (drag'n drop) in all collections in which they have ALL permissions enbled.
The sorting features, anyway, appears as soon as there is some limited permission from that role to that collection.
This is pretty a non-sense, but that is.

### To Reproduce

- Create a new role and assign it to a user
- Give all permissions of a populated collection to that user.
- The user won't have the sorting-record feature (missing drag'n drop column).

To make it appear the drag'n drop column (and relative feature):
- Give a random custom restriction to that user for that same collection (i.e. "can't update ID").
- The user now will have the possibility to sort items.

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by egidiusmengelberg** [comment]
Having the same issue. I just asked for it in the Dutch Discord channel.

**Comment by domdus** [comment]
I can reproduce this issue in version 9.23.1 and 9.23.4 fixes it.

**Comment by egidiusmengelberg** [comment]
Thanks, just upgraded. It worked.
