### ISSUE TITLE
Starting Directus without being connected to the internet hangs for about two minutes

### ISSUE THREAD

**Issue by sebescudie** [directus/directus#17882]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [x] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

I'm using latest Directus (9.23.1) on a Windows 11 machine. I'm starting my instance using a .bat file that simply contains `npx directus start`. My instance uses an SQLite database located inside the project directory.

When my computer has access to the internet, double-clicking the `.bat` file starts Directus almost instantly (normal behavior). But when the machine does not have access to the internet, the prompt will hang for about two minutes, and then the usual startup messages will be printed to the console.

It looks like it begins correctly (the title of the window changes to `npm exec directus start`), but then it stays like that for two minutes.

Could it be that it's trying to look online for a newer release? If so, is there a way to disable this behavior?

I tried setting the log level to trace, but it does not print anything other than the classic messages. It just prints them two minutes later. 

Observed a similar behavior on two Windows machine (Windows 10 and Windows 11).

Thanks in advance!

### To Reproduce

- Create a Directus instance on a Windows machine
- Start it with a bat file that contains `npx directus start`
- All good
- Disconnect the internet
- Launch the bat file again
- The prompt will hang for two minutes and then connect

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
I was unable to reproduce this on windows 10 or 11. Directus does check for the latest version but thats a non-blocking operation. I did not see a measurable difference between starting with internet and without.

https://user-images.githubusercontent.com/9389634/227218129-47230ce1-a418-4f5d-b3cb-415289839d70.mp4

**Comment by DanielBiegler** [comment]
@coderyqy 

> '. bat' under window, I don't know how to close it!

Depending on the application you might simply need: `CTRL+C` to stop the script.

For closing other programs that expect the "end" of the input (for example python prompt) you will need `CTRL+Z <enter>`. 

`<enter>` means you press the ENTER-key

**Comment by coderyqy** [comment]
> 
Thank you very much for your reply, but after running my ". bat", I shut down the terminal and ran it in the background, so there is no place to "ctrl+c"

**Comment by coderyqy** [comment]
> 
Hello, I mainly use this'. bat 'in the window system to solve the problem of how' npx directors start 'runs in the background

**Comment by coderyqy** [comment]
> > 非常感谢您的回复，但是运行我的“.bat”后，我关闭了终端并在后台运行它，所以没有地方“ctrl+c”
> 
> 请不要在不相关的问题上提问。[请随时在Discord 服务器](https://discord.com/invite/directus)中提问[](https://discord.com/invite/directus)

ok

**Comment by coderyqy** [comment]
> > Thank you very much for your reply, but after running my ". bat", I shut down the terminal and ran it in the background, so there is no place to "ctrl+c"
> 
> Please dont ask questions in unrelated issues. Feel free to ask in the [Discord Server](https://discord.com/invite/directus)

Hello! I joined the chat channel, but I don't have permission to comment.

![image](https://github.com/directus/directus/assets/63534197/16437605-56c9-4f2f-850c-1edeeb1d611d)
