### ISSUE TITLE
Many to many field is  required not honoured when saving

### ISSUE THREAD

**Issue by chetank628** [directus/directus#17897]
### Describe the Bug

suppose I have  a many-to-many field in my collection in that I have set the value of is required to true and then I delete all the values of the m2m field and try to save it  get saved without giving any error 
and then i open the same item in the collection and try to add the value in the m2m field and try to save it always give the error the following xx m2m field cannot be nullI

### To Reproduce

1)create any collection
2)add m2m value with the required set to true
3)add the item to the collection and save it
4)open the same item delete all the values from m2m field and save it get saved ideally it should throw an error
5)open the same item again and try to repopulate the m2m value now it is throwing error xx m2m filed can't be null and it is stuck there
 version : latest

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Nitwel** [comment]
This will very likely not be fixed in the near future as it is a limitation of the way we handle relational data.

At the moment, relational data is send to the api by noting down the changes and not the absolute value that way it is not easily possible to check if a relation has items or not.
