### ISSUE TITLE
INVALID_PAYLOAD for collection

### ISSUE THREAD

**Issue by boo-code** [directus/directus#17895]
### Describe the Bug

When trying to create a collection with "default" system fields like "status", "created on" etc., I get an error:
Collection "dddddd" doesn't exist, INVALID_PAYLOAD.

As a result a collection is created, but trying to add any fields results in another error:
"[FORBIDDEN] You don't have permission to access this."

![image](https://user-images.githubusercontent.com/65190196/227243030-59364c10-448e-4cff-9e42-0efd47f1df2a.png)

### To Reproduce

DB: Postgress 13.2 on external server, encoding UTF8.
Docker image with Directus v9.23.1 is used.

The system as a whole is used for a year. Problem occurred with some latest Directus Docker image update. I'm not sure which one exactly.

What was done before is working perfectly. But now it's not possible to add any new collection.

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
I am unable to reproduce this on a new Directus instance. Since the fields list in empty in your screenshot i suspect something could have errored or become corrupted on the database side 😬 

https://user-images.githubusercontent.com/9389634/227277830-9baab997-0e32-4cd5-9474-a325169eb2e8.mp4

**Comment by boo-code** [comment]
Are there any logs to check more detailed errors?

If I create a table on DB side and I add the fields there, then they are not reflected on Directus side. Trying to add a field from Directus provides the same Permission error.

The same problem with Postgress is described here: https://github.com/directus/directus/discussions/17478
