### ISSUE TITLE
[Flows] Webhook operations: can't make request to itself?

### ISSUE THREAD

**Issue by rootforbid** [directus/directus#17906]
### Describe the Bug

Directus v9.23.3 (Docker)

I'm not sure if it's intended or a bug.

In a "Webhook / Request URL" flow operation, if you use the Directus instance itself in the request URL (get or post), you just get a:
```
{
  "message": "Cannot read properties of undefined (reading 'status')"
}
```

I've tried with:
http://localhost:8055
http://127.0.0.1:8055
http://172.30.30.3:8055 (the IP of the container)

You might ask why I'm trying to query Directus from within in a flow.
I'm actually trying to create flows dynamically; when an item is created, create a new Webhook trigger flow.
Since you can't create flows from flows, I'm trying to use the Webhook operation to create a new flow via the API.

### To Reproduce

1. Create any kind of flow that you can trigger
2. Attach a "Webhook / Request URL" flow operation to it
3. with a method of "GET" and a URL of "http://127.0.0.1:8055/server/health"
4. Trigger the flow
5. In the logs, check the Payload of the webhook and you'll get the "message: Cannot read properties of undefined (reading 'status')"

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Any IP/Domain that resolves to localhost is blocked out of the box. You can manage this with the `IMPORT_IP_DENY_LIST` https://docs.directus.io/self-hosted/config-options.html#security

**Comment by rootforbid** [comment]
> Any IP/Domain that resolves to localhost is blocked out of the box. You can manage this with the `IMPORT_IP_DENY_LIST` https://docs.directus.io/self-hosted/config-options.html#security

Can't believe I never saw that extensive list of config options beside just the database configs.
You the man :)

**Comment by Militao36** [comment]
@rootforbid @XanManZA The server is always available. When running the flow the server is always available but it fails.

Server framework description: I am using expressjs, along with nginx as reverse proxy. My application is always online I tested several endpoints and none worked
