### ISSUE TITLE
Directus user is logged out after app reload

### ISSUE THREAD

**Issue by JonathanDoelan** [directus/directus#17901]
### Describe the Bug

Everytime I reload the Directus app, the login screen appears.

### To Reproduce

Download Directus version `9.23.3`, open the admin panel, login and then refresh the page (or copy the url and open in a new tab)

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by gramakri** [comment]
This applies to any URL , for example, `/admin/settings/data-model/+` .

To reproduce:
1. Login to directus
2. In another tab, go to `https://directus.example.com/admin/settings/data-model/+`
3. You are logged out

**Comment by freekrai** [comment]
hi @gramakri I just tested with a fresh install of 9.23.3 and tested both refresh and cycling between tabs and wasn't able to replicate this behaviour, Do you have cookies enabled, and can you test in incognito mode please?

**Comment by freekrai** [comment]
One more question: what auth strategy is this using? Regular email / password or using an SSO option?

**Comment by nebulade** [comment]
I can also reproduce this here. It seems after login, the app stores a cookie with `directus_refresh_token` and and some token. This is all it stores here, is this correct for a start?

Then on page reload, after loading the app assets, it calls POST https://direct.nebulon.space/auth/refresh which gets a `401 Unauthorized` response. Then redirecting to the login page.

**Comment by Ben-Ryder** [comment]
Hello, I have just ran into this issue too on a fresh install of 9.23.3, reproducible for me in Firefox and Chromium incognito and not.

Inspecting the browser when I first login, I can see the `directus_refresh_token` cookie being saved. When I refresh the page straight after, I can see the request `/auth/refresh [POST]` failing with a `401 Unathorized` response:
```
{"errors":[{"message":"Invalid user credentials.","extensions":{"code":"INVALID_CREDENTIALS"}}]}
```

I assume this failed auth refresh then means the application redirects to get me to log in again.

**Comment by nebulade** [comment]
> One more question: what auth strategy is this using? Regular email / password or using an SSO option?

@gramakri and me are both on Cloudron, where LDAP is configured

**Comment by freekrai** [comment]
@Ben-Ryder same question, as above. Is this email / password or a different auth strategy? I haven’t repeated this on email / password on a fresh install of 9.23.3, but if this is related to a different password strategy then it could be connected to https://github.com/directus/directus/issues/17905

**Comment by nebulade** [comment]
Just tried both the local and the ldap strategy and the behavior is the same.
Putting the app in debug log level, server side looks like:
```
23:35:27 - [22:35:26.738] DEBUG: Invalid user credentials.
23:35:27 - err: {
23:35:27 - "type": "InvalidCredentialsException",
23:35:27 - "message": "Invalid user credentials.",
23:35:27 - "stack":
23:35:27 - Error: Invalid user credentials.
23:35:27 - at AuthenticationService.refresh (/app/code/node_modules/directus/dist/services/authentication.js:237:19)
23:35:27 - at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
23:35:27 - at async /app/code/node_modules/directus/dist/controllers/auth.js:67:52
23:35:27 - "status": 401,
23:35:27 - "code": "INVALID_CREDENTIALS",
23:35:27 - "extensions": {}
23:35:27 - }
```

Is there anything I could otherwise set to get more info?

**Comment by Ben-Ryder** [comment]
> @Ben-Ryder same question, as above. Is this email / password or a different auth strategy? I haven’t repeated this on email / password on a fresh install of 9.23.3, but if this is related to a different password strategy then it could be connected to #17905

I am using the email / password auth strategy.

I've just been having a debug and I think the changes introduced in https://github.com/directus/directus/commit/349536303983ccba68ecb3e4fb35315424011afc to redact the auth cookie values may be fully overriding the value everywhere. When I breakpoint the refresh logic, the refresh token value appears as `--redacted--` for me.

**Comment by freekrai** [comment]
yes, a fix is being worked on as it is related to that commit

**Comment by sekhuat** [comment]
I facing the same issue after update the app from 9.23.1 to 9.23.3. The Directus app will either auto logout with Session Expired around 15min time or when browser refresh. I am using Chrome browser and without SSO.

**Comment by Zack-Heisnberg** [comment]
a super quick fix if you are not using the docker version


open this file inside the node_modules folder in your project

 node_modules/directus/dist/logger.js

change
` const output =pino_http_1.stdSerializers.req(request));`
to
` const output = JSON.parse(JSON.stringify(pino_http_1.stdSerializers.req(request)));`

i will make a merge request soon

**Comment by JonathanDoelan** [comment]
A few other issues which maybe relate to the same problem:
- extensions don't load
- not able to run `docker compose exec directus npx directus ...`
- if I list the directory structure `docker compose exec directus ls` it is quite different from previous versions.

**Comment by nebulade** [comment]
Thanks everyone for the quick fix!

**Comment by rijkvanzanten** [comment]
> Thanks everyone for the quick fix! I can confirm it works now.

Thanks for confirming  🙂

**Comment by JonathanDoelan** [comment]
> A few other issues which maybe relate to the same problem:
> 
>     * extensions don't load
> 
>     * not able to run `docker compose exec directus npx directus ...`
> 
>     * if I list the directory structure `docker compose exec directus ls` it is quite different from previous versions.

I can also confirm that it works as expected and the above side effects are gone as well. Thx!

**Comment by donavan-tangible** [comment]
I tried to upgrade directus packages and still have this issue... 

"@directus/extensions-sdk": "^10.1.1",
"directus": "^10.1.1",

**Comment by JonathanDoelan** [comment]
@donavan-tangible yes, it happens again. This time not every page reload logs out the user — but it happens very often …

**Comment by donavan-tangible** [comment]
Can you reopen this ticket?

**Comment by Sandros94** [comment]
Even in v10.2.x and v10.3?

**Comment by donavan-tangible** [comment]
@Sandros94  yes, I just need to refresh the page to get logged out... 
![Capture d’écran, le 2023-06-18 à 07 55 52](https://github.com/directus/directus/assets/109524661/bfbe3cc1-e160-4512-8df6-f4cdd1e68652)

**Comment by Sandros94** [comment]
> Do I'm suppose to have the cookie access Token once logged in?

Well, yes, you are suppose to have a cookie `directus_refresh_token` (default name):
![image](https://github.com/directus/directus/assets/13056429/91053c37-30c8-4257-afc9-9b152f069abd)

My gut feeling is that something else is preventing your refresh token cookie to be saved, and it shouldn't be directly related to this issue.

**Comment by donavan-tangible** [comment]
With Chrome I got the cookie but I don't get with Safari.

**Comment by Sandros94** [comment]
> With Chrome I got the cookie but I don't get with Safari.

I'm not from directus team, nor I have that much experience with session cookies (yet). At this point, to me, this looks more like a safari security/privacy thing to set (I don't have a macos machine to test it quickly).

Maybe some else could help you better than me tho.

**Comment by donavan-tangible** [comment]
Well, I just opened a new issue for this:
https://github.com/directus/directus/issues/18932
