### ISSUE TITLE
Google Login is not working with next-auth.

### ISSUE THREAD

**Issue by amankch** [directus/directus#17918]
### Describe the Bug

Google Login of Directus is not working with nextjs, next-auth. 

### To Reproduce

Create a Next APP
Integrate Next-auth and implement Google Sign In
Now try to login/sign in with Directus provided URL with next-auth google login access_token.

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Likely a duplicate of either https://github.com/directus/directus/issues/17901 or https://github.com/directus/directus/issues/17905
