### ISSUE TITLE
Creating Items via API using the Public Group results in Error

### ISSUE THREAD

**Issue by magbeat** [directus/directus#1791]
## Version Info
  - Directus version and branch: 6.4.2 (current master as the time of writing (3d7225c)
  - PHP version: 5.6.31
  - MySQL version: 10.1-MariaDB
  - Web server: Apache
  - OS name and version: unknown (Hoster) 

## Expected Behavior

Let the public API group to create items via API (https://api.getdirectus.com/1.1/#Create_Item) 

## Actual Behavior

I assume because there is no "Public User" but only a "Public Group" the behavior is as follows:
The item is created, but the response is an error message: "Statement could not be executed (23000 - 1048 - Column 'user' cannot be null)"

## Steps to Reproduce
 1. Create a table
 2. Add permissions to Add (and View, otherwise there will be an 'Permission Denied' error)
 3. Create a new item via API (Post request to .../tables/<tableName>/rows with paylod)

## Schema Dump, Logs, or Screenshots

Response:
`{
	"success": false,
	"error": {
		"message": "Statement could not be executed (23000 - 1048 - Column 'user' cannot be null)"
	},
	"code": 0,
	"class": "Zend\\Db\\Adapter\\Exception\\InvalidQueryException",
	"file": "\/home\/ecologic\/www\/coppolini-api.ecologic-services.ch\/vendor\/zendframework\/zend-db\/src\/Adapter\/Driver\/Pdo\/Statement.php",
	"line": 244,
	"public": true
}`

Logs:
`
Next exception 'Zend\Db\Adapter\Exception\InvalidQueryException' with message 'Statement could not be executed (23000 - 1048 - Column 'user' cannot be null)' in /home/ecologic/www/coppolini-api.ecologic-services.ch/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:244
Stack trace:
#0 /home/ecologic/www/coppolini-api.ecologic-services.ch/vendor/zendframework/zend-db/src/RowGateway/AbstractRowGateway.php(165): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#1 /home/ecologic/www/coppolini-api.ecologic-services.ch/api/core/Directus/Database/RowGateway/BaseRowGateway.php(223): Zend\Db\RowGateway\AbstractRowGateway->save()
#2 /home/ecologic/www/coppolini-api.ecologic-services.ch/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(270): Directus\Database\RowGateway\BaseRowGateway->save()
#3 /home/ecologic/www/coppolini-api.ecologic-services.ch/api/core/Directus/Services/EntriesService.php(32): Directus\Database\TableGateway\RelationalTableGateway->manageRecordUpdate('benutzer', Array, 1)
#4 /home/ecologic/www/coppolini-api.ecologic-services.ch/api/routes/A1/Entries.php(27): Directus\Services\EntriesService->createEntry('benutzer', Array, Array)
#5 [internal function]: Directus\API\Routes\A1\Entries->rows('benutzer')
#6 /home/ecologic/www/coppolini-api.ecologic-services.ch/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Array, Array)
#7 /home/ecologic/www/coppolini-api.ecologic-services.ch/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#8 /home/ecologic/www/coppolini-api.ecologic-services.ch/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#9 /home/ecologic/www/coppolini-api.ecologic-services.ch/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#10 /home/ecologic/www/coppolini-api.ecologic-services.ch/api/core/Directus/Slim/CorsMiddleware.php(24): Slim\Middleware\MethodOverride->call()
#11 /home/ecologic/www/coppolini-api.ecologic-services.ch/vendor/slim/slim/Slim/Slim.php(1302): Directus\Slim\CorsMiddleware->call()
#12 /home/ecologic/www/coppolini-api.ecologic-services.ch/api/core/Directus/Application/Application.php(103): Slim\Slim->run()
#13 /home/ecologic/www/coppolini-api.ecologic-services.ch/api/api.php(533): Directus\Application\Application->run()
#14 {main}`

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/3bcf9a134c29150800cad059792900227d7c1651

**Comment by WellingGuzman** [comment]
Hey @magbeat, I've fixed this by giving the public "user" and id = 0, which prevent the issue that the activity user column doesn't allow null as user.

**Comment by magbeat** [comment]
Hey @WellingGuzman. Great! I'll have a go with it tomorrow. Thanks a lot!

**Comment by magbeat** [comment]
@WellingGuzman  I have now manually added the user with Id 0 to our database. The workaround does work well for us. Thanks!
