### ISSUE TITLE
errors with M2M/M2O

### ISSUE THREAD

**Issue by peremp** [directus/directus#1792]
## Version Info
  - Directus version and branch: Develop latest (f420579)

## Preparation for both errors:
 - Do a clean installation of Directus
 - Import the SQL that I sent you (Slack)

## Steps to reproduce error 1
 - Go to problems table (/tables/problems)
 - Click on 'Problem 1' (/tables/problems/1)
 - On the "Editing item" page, scroll down to find the `Solutions` M2M interface and click on 'Solution 1'

## Expected behavior for error 1
 - Solution 1 is opened in an overlay

## Current behavior
```
Error: Uncaught TypeError: value.startTracking is not a function.

File: http://localhost:8282/app/core/interfaces/many_to_one/interface.js?bust=27d013994fef7aeee549f85d5f3a6a14
```

## Steps to reproduce error 2
 - Go to solutions table (/tables/solutions)
 - Click on 'Solution 1' (/tables/solutions/1)
 - On the "Editing item" page, scroll down to find the `Problems` M2M interface and click on 'Problem 1'

## Expected behavior for error 2
 - Problem 1 is opened in an overlay

## Current behavior 2
```
Error: Uncaught TypeError: Cannot read property 'junctionStructure' of undefined

File: http://localhost:8282/app/core/interfaces/relational/m2m/interface.js?bust=27d013994fef7aeee549f85d5f3a6a14
```

**Comment by WellingGuzman** [comment]
Hey @peremp, I've pushed a fix, let me know if that patch also fixed it for you.

Closed by https://github.com/directus/directus/commit/a29f4fc7f595e747e791efe62d26aac4b04157a7
