### ISSUE TITLE
Tables with names containing dashes produce errors when trying to display their contents

### ISSUE THREAD

**Issue by StefanOrzu** [directus/directus#1793]
## Version Info
  - Directus version and branch: 6.4
  - PHP version: 7
  - MySQL version: 5.5
  - Web server: apache
  - OS name and version: Boot2Docker 17.06.2-ce

## Expected Behavior
The UI should display the list of rows in the table

## Actual Behavior
Rows don't appear and the UI shows an error message.

## Steps to Reproduce
 1. Go to **Admin Settings** -> **Tables and Inputs**
 2. Click the **+** icon
 3. In the **Create Table** modal type "table-with-dashes" in the Table Name input
 4. Click **OK**
 5. Click on "Table-with-dashes" in the left-hand panel
 6. An error pop-up message appears saying ```This query failed: SELECT `table-with-dashes`.`id` AS `id`, `table-with-dashes`.`status` AS `status`, `table-with-dashes`.`sort` AS `sort` FROM `table-with-dashes` WHERE `table``-``with``-``dashes`.`status` IN ('1', '2') ORDER BY `table``-``with``-``dashes`.`sort` ASC LIMIT 200 OFFSET 0```

I've copy-pasted the SQL query into a MySQL console and got the same error. After a few corrections it worked: ```SELECT
  `table-with-dashes`.`id`     AS `id`,
  `table-with-dashes`.`status` AS `status`,
  `table-with-dashes`.`sort`   AS `sort`
FROM `table-with-dashes`
WHERE `table-with-dashes`.`status` IN ('1', '2')
ORDER BY `table-with-dashes`.`sort` ASC
LIMIT 200 OFFSET 0```

## Schema Dump, Logs, or Screenshots
<img width="788" alt="screen shot 2017-09-07 at 17 42 00" src="https://user-images.githubusercontent.com/4761763/30174713-e9c0e450-93f3-11e7-86de-3cb7aaa8c796.png">

**Comment by WellingGuzman** [comment]
Hey @StefanOrzu this issue has been closed by https://github.com/WellingGuzman/zend-db/commit/6bedd69fb149d9ec001816320fce5527adeb9725

Please run `composer install` to install the latest commit of our custom zend db repo.

**Comment by StefanOrzu** [comment]
Hi, thanks for getting that fixed so quickly, that's really great. ATM I'm using the directus-docker repository, could you please tell me how I can update that to incorporate the latest changes?

**Comment by WellingGuzman** [comment]
Hey @StefanOrzu you can attach a shell to the container by running this:

```
$ docker container exec -it <container-id-or-name> /bin/bash
```

`/bin/bash` being the shell path
