### ISSUE TITLE
Search don't work for capital cyrillic letters

### ISSUE THREAD

**Issue by lericol** [directus/directus#17941]
### Describe the Bug

if you need to find item with capital cyrillic letters in value - search return null value or only values with lower case

### To Reproduce

Example:
Collection with cyrillic values
![image](https://user-images.githubusercontent.com/64581792/227779537-a124e78e-9c09-4003-8fd7-6681e9139182.png)

Try to find values with capital latin letters - Success
![image](https://user-images.githubusercontent.com/64581792/227781350-3536e611-ac53-423e-b5c1-17d81cfdbfc5.png)

Try to find values with capital cyrillic letters - Fail
![image](https://user-images.githubusercontent.com/64581792/227781396-0b9a6e75-fe75-41be-ab8d-78d5086c9fb3.png)
![image](https://user-images.githubusercontent.com/64581792/227781416-b52a7d6c-56a4-4130-a8f9-a38d28df24df.png)

### Hosting Strategy

Self-Hosted (Custom)

**Comment by azrikahar** [comment]
Are you using SQLite by any chance?

I was not able to reproduce this on PostgreSQL:

https://user-images.githubusercontent.com/42867097/227810314-383b48b7-f3b4-4a6c-9cb0-d6c2a66f1290.mp4

---

But as #16747 brought up this same scenario, it is confirmed to be a _default_ limitation of SQLite, as seen in my second screen capture below. You can refer to https://github.com/directus/directus/issues/16747#issuecomment-1342403354 for more info on how to enable this for SQLite.

https://user-images.githubusercontent.com/42867097/227810372-97747942-add8-4ea2-91de-00a675fd8eec.mp4

**Comment by lericol** [comment]
use Postgres
thanks!

**Comment by lericol** [comment]
problem was with LC_COLLATE LC_CTYPE in postgre
