### ISSUE TITLE
A one2many field inside a translations, is not returned in the request in the api

### ISSUE THREAD

**Issue by miguelalvagarcia** [directus/directus#1795]
In the api when you have a field one2many inside a translations, when the api returns the project the field one2many does not return it.
/api/1.1/tables/projects/rows/1

## Version Info
  - Directus version and branch: Last develop 
  - PHP version: 5.5.26
  - MySQL version: 5.5.42
  - Web server: Apache 
  - OS name and version:  osX  10.12.6

## Expected Behavior
See all the fields of a project and the translation of the project including a related field

## Actual Behavior
I see all project information except related fields. (I've only tried the one2many field)

## Steps to Reproduce
 1. Go to the projects table enter the project "Title project 1" and check that all fields are filled, or create a new project and fill in all the fields including the one2many field. 
 2. Make a request to the api that project id "/api/1.1/tables/projects/rows/1"
 3. Check that the json

## Schema Dump, Logs, or Screenshots
[schema_and_dumps.zip](https://github.com/directus/directus/files/1288444/schema_and_dumps.zip)

**Comment by WellingGuzman** [comment]
Hey @miguelalvagarcia this bug has been fixed on `develop` branch, soon to be added into release 6.4.3.

Closed by https://github.com/directus/directus/commit/2709959f241e92006690c9e2f16fac478b69bfa3

**Comment by miguelalvagarcia** [comment]
Hi @WellingGuzman, I've tried this commit but I do not see the field in the api. I should see the challenges field and I still can not see it.

Thank you

**Comment by WellingGuzman** [comment]
Hey @miguelalvagarcia, by default you get 1 level depth of relational data. you can change that by using the `depth` param to one level deep.

Ex: `/api/1.1/tables/projects/rows/1?access_token=token&depth=2` you would get the challenges field.
