### ISSUE TITLE
Unable to reorder M2A relation with more than 15 items 

### ISSUE THREAD

**Issue by schroeder-g** [directus/directus#17962]
### Describe the Bug

Our team is using Directus as our CMS. We have a `Page` collection that serves `Content` blocks to our app. Creating a page with more than 15 content items, the items list becomes paginated, and the drag-and-drop functionality is removed.

![image](https://user-images.githubusercontent.com/66321261/227993025-2bce960b-abab-4113-a821-bcbb7b1e2253.png)
_with fewer than 15 items, you can drag and drop the items to reorder them_

![image](https://user-images.githubusercontent.com/66321261/227992729-f29cd454-aa8c-4f3f-a5a8-d5c1a7ea599b.png)
_with greater than 15 items, the 'drag and drop' icon disappears, and you can no longer rearrange them_

How can I circumvent this bug within the Directus UI? Thank you for any pointers or insight as to how to work around this issue. 

### To Reproduce

1. Create a collection
2. Give it a Many-to-Any field
3. Enable sorting on the field
![image](https://user-images.githubusercontent.com/66321261/227993546-dc5ec6e3-9f1b-460a-a67f-2fa9e1b6bd32.png)
4. Create 16 or more instances of the field on a given item of the parent collection
5. Attempt to reorder the field instances in content

### Hosting Strategy

Directus Cloud

**Comment by Nitwel** [comment]
Have a look at #12818 for detailed information why we do this.
This will be closed as it is based on a feature request.

**Comment by schroeder-g** [comment]
> Have a look at #12818 for detailed information why we do this. This will be closed as it is based on a feature request.

@Nitwel awesome, thank you for pointing me in the right direction. 🙏
