### ISSUE TITLE
Edit Raw Values not working

### ISSUE THREAD

**Issue by rowild** [directus/directus#17978]
### Describe the Bug

When choosing "Edit Raw Value", the change is not saved.

Example:

The JSON of a list of audio files looks like this:

```json
{
  172,
  173,
  174,
  177
}
```

I want to move 177 to the top of the list:

```json
{
  177,
  172,
  173,
  174
}
```

After saving and re-opening the data item, the change is not reflected.

What I expect:
The change is persisted.

What happens:
The initial status is reflected even after saving.

Of course this issue is superfluous, if my expectation is wrong! In that case sorry for the waste of time!

### To Reproduce

- Upload some files (I have audio files in a sub folder "Audio Files")
- Create a collection (e.g. for an audio player) and create a relational field to those (audio) files (in that specific folder)
- After saving choose "Edit Raw Value" (next to the header of the relational field)
- Change the sequence of the ids
- Save
- Re-open the data item

A video reflecting the problem:
https://user-images.githubusercontent.com/213803/228303818-4fe825e4-0221-4ba8-858d-acac5823729f.mp4

Directus 9.23.4
Hosted on Digital Ocean via Docker (based on the instruction in the docu)

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
If this is a relational field then you'll have to the "detailed format" to update the relational items this way https://docs.directus.io/reference/introduction.html#one-to-many-many-to-many

However for re-ordering the items dragging/dropping in the interface is a lot easier! If thats not available you're probably missing a `sort` field on your relation/related collection.

**Comment by rowild** [comment]
@br41nslug Thank you! I lacked the knowledge that sorting can be added via a sort field! AWESOME!
