### ISSUE TITLE
Template hook is not working inside directus extensions

### ISSUE THREAD

**Issue by NigmaX** [directus/directus#17971]
### Describe the Bug

Hi, im trying to create a custom interface that get an html string and renders it.

Im trying to use the template hook in vue, but it doesn’t seem to work.

```
export default{
Template: “<div>example template</div>”
}
```

also trying to use the render function but it also doesn’t seem to work properly 

```
render:()=>{
 let comp = {
  template: “<div>example template</div>”
 }
 return h(comp)
}
```

Both of the examples above does work on a scaffolded vue application.

any thoughts?
Thanks in advance.

### To Reproduce

try to use template in a custom interface
```

export default{
Template: “<div>example template</div>”
}
```

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Nitwel** [comment]
The easiest way to get started with an extension is using the extensions-sdk. https://docs.directus.io/extensions/creating-extensions.html

You can access the render function in there like so: https://vuejs.org/api/composition-api-setup.html#usage-with-render-functions

**Comment by NigmaX** [comment]
@Nitwel There needs to be more to solve the problem, though.
To be able to render template strings I need to run vue with the esm-bundler.js engine.

The idea is to take the WYSIWYG's interface output and change some placeholders to support custom components.

```
render:()=>{
 let comp = {
  template: “<div>example template <custom-interface></custom-interface> other text</div>”
 }
 return h(comp)
}
```

Trying to put the code above in a custom interface will NOT work.

**Comment by Nitwel** [comment]
Please use the extension SDK for your extension development, we can't provide help outside of that.

**Comment by NigmaX** [comment]
@Nitwel, but I am using the extension SDK.
I can't use the render function with a template string inside the custom interface.

try to Create a new interface using the extension SDK and just try to render a template string.
It won't work.
