### ISSUE TITLE
Broken uploading image with some additional file fields

### ISSUE THREAD

**Issue by kuzmi4** [directus/directus#17970]
### Describe the Bug

When uploading image file, additional data like: "description", "tags" not accepting.

Example upload png file (folder data accepted, description and tags - not):

![image](https://user-images.githubusercontent.com/6544815/228190698-84c72f77-0ecf-4027-82d3-0f0187eac967.png)

Example upload fb2 file:

![image](https://user-images.githubusercontent.com/6544815/228190915-75a63d7b-60b9-415e-9686-0c1e9b182c55.png)

### To Reproduce

Just upload image with description or tags info

Example with curl:
`curl --location 'DIRECRUS_URL/files' \
--header 'Authorization: Bearer token' \
--form 'description="{\"sss\":1111111231}"' \
--form 'tags="[1,2,3,4]"' \
--form 'file=@"path to file"'`

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Nitwel** [comment]
That is because the api doesn't take form-data into account. The right way to set the description is by setting it in the json structure of the request body.

**Comment by Nitwel** [comment]
I was wrong, this looks like a bug!
