### ISSUE TITLE
Many 2 Many relationship permission config

### ISSUE THREAD

**Issue by duylddev** [directus/directus#17986]
### Describe the Bug

I have m2m relationship between `company` and `partner` like this 

![image](https://user-images.githubusercontent.com/9783862/228491326-6c3bf64c-531d-497f-8d2c-4ea66e555e32.png)

Permission should be `company.user_created` equal `$CURRENT_USER` can CRUD `company` and `company_partner`.

Here is problem, user can use POST request to `company_partner` to link any `company` to any `partner`

This is permission setting for creating `company_partner`
![image](https://user-images.githubusercontent.com/9783862/228493264-742e0ea8-b766-49b8-b1f6-a17906ee135a.png)

### To Reproduce

Create m2m relationship between `company` and `partner`
Setting permission `company.user_created` equal `$CURRENT_USER` can CRUD `company` and `company_partner`

send `POST` request to `/items/company_partner` with any existing company_id and partner_id

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Nitwel** [comment]
I don't think you can prevent this with the standard permission system, but you can create a flow which is configured to a filter hook, so you can validate yourself if an item gets created. @directus/review  please correct me if I'm wrong!

**Comment by duylddev** [comment]
could I disable junction table rest API?
