### ISSUE TITLE
The "?" character in default field value was replaced with "$1" when using Postgresql database

### ISSUE THREAD

**Issue by gigigimay** [directus/directus#17989]
### Describe the Bug

Directus version: 9.23.4

The `"?"` character in the default field values are replaced with `"$1"`

This issue appears to be happening when using Postgresql DB and won't happen on SQLite

### To Reproduce

1. In the data model setting, create a field within any collection with a default value that contains a question mark (`?`). For example, `"bello?"`
2. After creating, click to open the field detail and check its default value

**Actual result:**
The default value is `"bello$1"`

**Expected result:**
The default value should be `"bello?"`

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
This is a bug in `knex`. I've opened https://github.com/knex/knex/issues/5626 and we'll track/resolve this over there 👍🏻
