### ISSUE TITLE
Can't delete columns

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1798]
## Version Info
  - Directus version and branch: develop latest

## Expected Behavior
Clicking the red `x` and `Yes` shows the "confirm deletion by typing the column name" modal

## Actual Behavior
Clicking yes closes the modal and doesn't seem to do anything else

## Steps to Reproduce
 1. Try to remove a column in table settings

## Schema Dump, Logs, or Screenshots
![2017-09-08 16_26_20](https://user-images.githubusercontent.com/9141017/30230044-79599382-94b2-11e7-8a5c-37ce564debcb.gif)

No errors in console or anything

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/59b5924b0942d14e2c143e1a2ca3816806fcd706
