### ISSUE TITLE
endpoint /schema/diff generates a diff that isnt consumable by endpoint /schema/apply

### ISSUE THREAD

**Issue by jbsiddall** [directus/directus#17987]
### Describe the Bug

Directus version: 9.23.4

when I hit the `/schema/diff` endpoint but with a schema file that is the same as the schema in directus, then the endpoint returns a response body of null instead of normal json diff schema.

We currently store the response body of hitting `/schema/diff` in a json file that is then sent to the `/schema/apply` endpoint.
we're hitting that endpoint using curl (with -vvv) and this is the response:
```
*   Trying 192.168.32.4:8055...
* Connected to directus (192.168.32.4) port 8055 (#0)
> POST /schema/apply HTTP/1.1
> Host: directus:8055
> User-Agent: curl/7.74.0
> Accept: */*
> Authorization: Bearer <PRIVATE_API_TOKEN>
> Content-Type: application/json
> Content-Length: 4
> 
* upload completely sent off: 4 out of 4 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Content-Security-Policy: script-src 'self' 'unsafe-eval';worker-src 'self' blob:;child-src 'self' blob:;img-src 'self' data: blob: https://cdn.directus.io;media-src 'self' https://cdn.directus.io;connect-src 'self' https://*;default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';object-src 'none';script-src-attr 'none';style-src 'self' https: 'unsafe-inline'
< X-Powered-By: Directus
< Content-Type: application/json; charset=utf-8
< Content-Length: 877
< ETag: W/"36d-oiuYM7HNQFlWY9ej8uJQM3E0eUk"
< Date: Wed, 29 Mar 2023 11:02:00 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
* Connection #0 to host directus left intact
{"errors":[{"message":"Unexpected token n in JSON at position 0","extensions":{"code":"INVALID_PAYLOAD","stack":"Error: Unexpected token n in JSON at position 0\n    at /directus/dist/app.js:151:29\n    at /directus/node_modules/.pnpm/body-parser@1.20.1/node_modules/body-parser/lib/read.js:130:7\n    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)\n    at invokeCallback (/directus/node_modules/.pnpm/raw-body@2.5.1/node_modules/raw-body/index.js:231:16)\n    at done (/directus/node_modules/.pnpm/raw-body@2.5.1/node_modules/raw-body/index.js:220:7)\n    at IncomingMessage.onEnd (/directus/node_modules/.pnpm/raw-body@2.5.1/node_modules/raw-body/index.js:280:7)\n    at IncomingMessage.emit (node:events:513:28)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"}}]}
```

The desired behaviour in the scenario when the local schema snapshot is the same as the schema in teh directus server is that the diff is in a format that can still be sent to `/schema/apply` but results in zero changes.

### To Reproduce

* hit /schema/snapshot?export=json endpoint and save the response body to a schema.json file
* then hit the /schema/diff?export=json passing in the schema.json as request body and save the response body as diff.json
* finally hit the /schema/apply endpoint passing in the diff.json as the request body.

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
The diff from `/schema/diff` is returned under the `data` property. Please make sure to only post these data to `/schema/apply` and not the whole response.
As I assume this to be the problem here, I'm going to close the issue. Happy to keep discussing in this thread, and we'll reopen if it turns out that it's actually a different issue 👍🏻
