### ISSUE TITLE
In dev mode, extensions are apparently loaded, but they don't show up in admin panel / settings / modules

### ISSUE THREAD

**Issue by mpenna** [directus/directus#17995]
### Describe the Bug

I'm setting up my environment in order to work on some custom extensions, and to be able to use Vue's dev tools during the development phase, I got Directus running locally, albeit dockerized. Given this particular strategy, and to make the dev experience hopefully less confusing, I have configured Directus' Docker container with a (bind mount) volume which points to the folder (on the host) where I'll be working on the custom extensions. Once I run everything, Directus apparently detects and loads a couple of test extensions that I have already scaffolded. At least, that's what is eventually written to the console when I run `pnpm --filter directus dev`:

![Screenshot from 2023-03-29 18-52-11-highlighted](https://user-images.githubusercontent.com/6953141/228678271-c09ba3ba-5b89-43cf-a4b6-06df7ba831bf.png)

But, upon visiting the admin panel, under settings / modules, the extensions are not listed.

![Screenshot from 2023-03-29 18-53-43](https://user-images.githubusercontent.com/6953141/228678456-8a05a186-3b93-48b6-9317-065aa1e0882e.png)

Funny thing, though, is that I have a second instance of Directus up and running, this one however using the actual Docker image, and with the exact same "shared extensions" folder configuration also applied to this second instance. Upon visiting the admin panel / settings / modules page of this second instance, the modules are in fact listed.

![Screenshot from 2023-03-29 18-53-34-highlighted](https://user-images.githubusercontent.com/6953141/228679012-b29f9cc2-227e-42d9-beb9-341cad65d822.png)

One other info: at this point in time, both instances are sharing the same postgresql database instance.

### To Reproduce

Run two Directus instances:

- a local one, running from source in dev mode
- a Docker-based one

Configure volumes on both instances so they share a common folder on the host that will hold the extensions.

Both instances point to the same postgresql database.

Run both instances. 

The Docker-based instance should list the custom extensions in the admin panel, while the one running from source doesn't list the extensions.

### Hosting Strategy

Self-Hosted (Custom)

**Comment by mpenna** [comment]
Noticed that an XHR request `/settings` endpoint is triggered by the admin app and that the test modules that have been configured and available at the database are indeed present in the response, but they're not being listed.

```json
{
    "data": {
        "id": 1,
        "project_name": "Intranet - Admin",
        "project_url": null,
        "project_color": null,
        "project_logo": "c7bbe70d-ccb8-4160-97af-573a7a00c482",
        "public_foreground": null,
        "public_background": null,
        "public_note": null,
        "auth_login_attempts": 25,
        "auth_password_policy": null,
        "storage_asset_transform": "all",
        "storage_asset_presets": null,
        "custom_css": null,
        "storage_default_folder": null,
        "basemaps": null,
        "mapbox_key": null,
        "module_bar": [
            {
                "type": "module",
                "id": "content",
                "enabled": true
            },
            {
                "type": "module",
                "id": "users",
                "enabled": true
            },
            {
                "type": "module",
                "id": "files",
                "enabled": true
            },
            {
                "type": "module",
                "id": "insights",
                "enabled": true
            },
            {
                "type": "module",
                "id": "settings",
                "enabled": true,
                "locked": true
            },
            {
                "type": "module",
                "id": "other",
                "enabled": true
            },
            {
                "type": "module",
                "id": "some",
                "enabled": false
            },
            {
                "type": "module",
                "id": "test",
                "enabled": false
            },
            {
                "type": "module",
                "id": "whatever",
                "enabled": false
            },
            {
                "type": "module",
                "id": "personal",
                "enabled": false
            },
            {
                "type": "module",
                "id": "random",
                "enabled": false
            }
        ],
        "project_descriptor": null,
        "translation_strings": null,
        "default_language": "pt-BR",
        "custom_aspect_ratios": null
    }
}
```

**Comment by mpenna** [comment]
Perhaps this has something to do with the fact that they're not being displayed...

![image](https://user-images.githubusercontent.com/6953141/229846292-d92f5bf2-cdc2-430b-82e0-372c80928f8c.png)

**Comment by mpenna** [comment]
I went again through the steps on the Running Locally documentation and the custom modules are now being listed:

pnpm install
pnpm -r build
pnpm --dir api cli bootstrap
pnpm --filter directus dev

**Comment by rijkvanzanten** [comment]
@mpenna Thanks for confirming that @mpenna! I'll close this for now then 🙂

**Comment by mpenna** [comment]
Today I debugged this a bit more thoroughly and was able to pinpoint where and what is causing this behavior: 

// app/src/extensions.ts
![image](https://user-images.githubusercontent.com/6953141/231203564-fd57f05d-0013-4b48-959f-36ff88400a03.png)

If we put a `NODE_ENV=development` setting in the `app/.env` file, and then build and run the project, the result is that Vue.js' Dev Tools are then enabled, but the custom extensions are not loaded and not listed. 

If we comment out the aforementioned NODE_ENV  setting, then the opposite happens: Vue.js' Dev Tools are disabled and the custom extensions are loaded and listed.
