### ISSUE TITLE
ESM Package

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [directus/directus#17997]
### Describe the Bug

First of all, I love directus. When trying to import the "antlr4" package a problem occurs, its an ESM package. Maybe i have little knowledge in this area but when trying to use them in a directus hook it encounter the problem:

When trying to use require
```
const antlr4 = require("antl4");
require() of ES Module /directus/node_modules/antl4/index.js from /directus/extensions/hooks/custom_hook/index.js not supported.
```

When trying to use import
´´´
import antlr4 from "antl4";
> SyntaxError: Cannot use import statement outside a module
´´´

Since antlr4 does not support commonJS (https://github.com/antlr/antlr4/pull/4199) this brings me to a point where i am struggeling how to proceed. I dont want to install antlr4 since i want to use the npm package, which brings me the joy of updates.

### To Reproduce

1. Create a custom hook for directus
2. Import/Require antlr4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
ESM only dependencies are currently not compatible with Directus extensions because the Directus API is not fully ESM yet.

**Comment by NilsBaumgartner1994** [comment]
Ok thanks, any perspective, when we can assume this will be compatible?

**Comment by br41nslug** [comment]
It is being worked on but it's a huge refactor across the codebase so no idea when that will land
