### ISSUE TITLE
App doesn't properly refresh the session once the tab gets focus again

### ISSUE THREAD

**Issue by koksikus** [directus/directus#18016]
### Describe the Bug

With an expired Token, this error message appears and first of all, it should not be an unexpected Error because we know what it is, but this time it is about the Reset Page Preferences button, by clicking on it, it will change the appearance of the data. I think there should be a refresh button.
![Zrzut ekranu 2023-03-31 142246](https://user-images.githubusercontent.com/90528895/229286619-6c068267-2eb7-47ad-8971-53abe6e9e144.png)

### To Reproduce

Wait until the timer expires, go to the Directus tab and see the message. Click on it and the page preferences will be changed. But it's just the token getting expired. 
If someone clicks on it (thinking it will solve problem) they will have even more trouble with resetting the data.

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by koksikus** [comment]
I just did a test. I opened Directus in the refreshed tab. I opened another one and worked on it after about 20 minutes or a little more I switched to the Directus tab and a list of errors appeared in the console.
GET (...) 401 (Unauthorized)
Uncaught (in promise) X {message: 'Request failed with status code 401', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}
GET (...) 401 (Unauthorized)
Uncaught (in promise) X {message: 'Request failed with status code 401', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}
GET (...) 401 (Unauthorized)
Uncaught (in promise) X {message: 'Request failed with status code 401', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}

**Comment by koksikus** [comment]
The same errors keep popping up in the background.  The longer it takes, the more the console fills up with errors.

**Comment by koksikus** [comment]
I noticed one more thing - if everything is on one computer and database and directus and I log in to the project using this computer, no error appears.

**Comment by koksikus** [comment]
It's terribly annoying. Does anyone else have this issue?  Is it just me because I set something wrong?

**Comment by azrikahar** [comment]
> I'm using the latest version of Directus in the Edge browser.

This might be Edge's Sleeping Tabs feature: https://www.microsoft.com/en-us/edge/features/sleeping-tabs-at-work

@koksikus Can you share what is the amount of time configured for your Edge browser within `Settings` -> `System and performance` -> `Optimize performance` -> `Put inactive tabs to sleep after the specified amount of time`? Here's an example screenshot to find it in your browser:

![](https://github.com/directus/directus/assets/42867097/dad0dfa1-43ee-467a-9d42-e7a65ed6e065)

> I noticed one more thing - if everything is on one computer and database and directus and I log in to the project using this computer, no error appears.

By "everything is on one computer" and "this computer", are you accessing Directus via `localhost` instead of an actual domain?

It seems like `localhost` for example cannot enter such "sleep" state as Edge prevents it:

![](https://github.com/directus/directus/assets/42867097/e3d4690f-252f-48a4-9c6b-7c8a6197ff02)

so I'm wondering if it's the reason why it worked for you when you said "one computer".

**Comment by koksikus** [comment]
Hi azrikahar, I checked, I changed the settings to 12 hours or clicked the option to completely disable this function and it didn't change anything, this message still appears.
When writing about one computer, as you write, the database and directus are on one computer and I log in via localhost.
I changed ACCESS_TOKEN_TTL to 120 min and REFRESH_TOKEN_TTL to 1 day. Previously, I had higher values and it didn't change anything in terms of the message that appeared, only that I force them to log in again and this way they won't click on this message, which will cause the view to fall apart.
Should I do any other tests?

**Comment by koksikus** [comment]
This only happens on the databases tab. If I'm on Directus settings tab, nothing like this happens.

**Comment by azrikahar** [comment]
@koksikus thanks for doing the additional checks on your end!

> Should I do any other tests?

Would it be possible for you to help test out #20383 in your setup? That would extremely helpful to confirm whether it resolves your exact situation, just in case the way the error happens to you is still different than what I assumed.
