### ISSUE TITLE
Dropdown multiselect not save all values

### ISSUE THREAD

**Issue by dsivokhin** [directus/directus#1801]
## Version Info
  - Directus version and branch: devel and master
  - PHP version: 7.0
  - MySQL version: 5.7
  - Web server: nginx
  - OS name and version: Ubuntu 16.04

## Actual Behavior
Dropdown multiselect not save all values, only first chose value.

## Steps
1. Create field type Dropdown multiselect
2. Settings field, click `Fill with Example` and have error
![default](https://user-images.githubusercontent.com/4669992/30276123-776331f8-970c-11e7-8803-2c6f9960ce14.png)

3. if manual write json no have error
4. Go to item page choose 2-3 value and save
5. See that save only first value.

## Schema Dump, Logs, or Screenshots
[test.zip](https://github.com/directus/directus/files/1292651/test.zip)

**Comment by rijkvanzanten** [comment]
Hey @dsivokhin! Good catch.. The JSON not setting the value on entering just the example has just been fixed on the develop branch in https://github.com/directus/directus/commit/4aa561f5243d78086d4f9f516592974eaeb7a481.

For the more pressing multiselect issue.. I'm going to check it out right away!

**Comment by chrisbenjamin** [comment]
Same here.

**Comment by rijkvanzanten** [comment]
This was fixed on the [develop](https://github.com/directus/directus/tree/develop) branch in https://github.com/directus/directus/commit/cf887e848f5cec795d0a720227b0e279d683d56d and will hit master soon.

Please let me know if you're able to test this on [develop](https://github.com/directus/directus/tree/develop) and if it works for you 🙂

**Comment by dsivokhin** [comment]
Hello @rijkvanzanten, now an error occurred while creating a new item
![default](https://user-images.githubusercontent.com/4669992/30318364-97cbbcfe-97b5-11e7-99de-7fc418e02b72.png)

![default](https://user-images.githubusercontent.com/4669992/30318400-ad6646ba-97b5-11e7-893d-36d9305d3804.png)

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/79d297fe2d551fc94f5abfc918e6d4fc7f3548fa
