### ISSUE TITLE
Route /schema/snapshot doesn't exist.

### ISSUE THREAD

**Issue by davidmach14** [directus/directus#18020]
### Describe the Bug

I am trying to export the schema as described in [the documentation](https://docs.directus.io/reference/system/schema.html). After sending the request I get an error message:
```json
{
  "errors": [
    {
      "message": "Route /schema/snapshot doesn't exist.",
      "extensions": {
        "code": "ROUTE_NOT_FOUND"
      }
    }
  ]
}
```

Same behavior on cloud (version 9.21.2) and self-hosted instance (version 9.23.4 Docker image). 

### To Reproduce

curl https://{directus_url}/schema/snapshot -H "Authorization: Bearer {token}"

### Hosting Strategy

Directus Cloud

**Comment by LilaRest** [comment]
@davidmach14 The schema endpoint has been introduced in the [v9.23.0](https://github.com/directus/directus/releases/tag/v9.23.0), which explains why you get this error in your v9.21.2 environment.

**Comment by davidmach14** [comment]
Thanks for the explanation! But this only answers half of my question...

**Comment by paescuj** [comment]
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

```console
❯ curl localhost:8055/schema/snapshot -H "Authorization: Bearer <TOKEN>"
{"data":{"version":1,"directus":"9.23.4","vendor":"sqlite","collections":[],"fields":[],"relations":[]}}
```
