### ISSUE TITLE
Type field 'Tags' in national languages keyboard

### ISSUE THREAD

**Issue by dsivokhin** [directus/directus#1802]
## Version Info
  - Directus version and branch: master
  - PHP version: 7.0
  - MySQL version: 5.7
  - Web server: nginx
  - OS name and version: Ubuntu 16.04

## Expected Behavior
When enter keycode `188` - no insert tag, because in national keyboard it is not comma, it is a letter

## Actual Behavior
When enter key with code 188, event stoped writing word and insert tag.

**Comment by WellingGuzman** [comment]
Thanks @dsivokhin, what's your keyboard standard/format (the one the triggers the issue)?

**Comment by dsivokhin** [comment]
Cyrillic keyboard. I find event keydown in directus\app\core\interfaces\tags\interface.js line 22
```
events: {
      'keydown #tag-input': function (event) {
        // 188 = comma, 13 = enter
        if (_.contains([188, 13], event.keyCode)) {
          event.stopPropagation();
          event.preventDefault();

          this.insertTag();
        }
      }, 
```

**Comment by rijkvanzanten** [comment]
I've changed to interface to match on `event.key === 'Enter'` and `event.key === ','` instead of the keyCodes `188` and `33`. I guess that should do it. Could you test out the [develop](https://github.com/directus/directus/tree/develop) branch and confirm @dsivokhin?

**Comment by dsivokhin** [comment]
@rijkvanzanten, @WellingGuzman. Thank you. It's works.
