### ISSUE TITLE
API returns deleted items

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1805]
## Version Info
  - Directus version: Hosted (6.3.8) using API 1.1

## Expected Behavior
Deleting an item in the admin interface prevents it from showing up in the API response as well.

## Actual Behavior
The item can't be found anywhere in the admin panel (makes sense, as it's deleted), but still shows up in the API response in nested relational interfaces.

Here's the kicker: this also happens when using the `status=1` param or even `in[active]=1`

## Steps to Reproduce
 1. Delete an item
 2. Get items from that table
 3. Profit

**Comment by WellingGuzman** [comment]
Returning `deleted` items it's a expected behavior on 6.3.x, although this was changed on 6.4, to only return "published" (defined by the user) items.
