### ISSUE TITLE
M2O Relation not visible in table view

### ISSUE THREAD

**Issue by nskartoredjo** [directus/directus#18065]
### Describe the Bug

At the table view, if a field is added such that it has a relation with the collection of another collection, i.e. A -> B -> C, than the field is considered empty even if the values are non-empty.

Additionally, this field will break if you try to resize it.

https://user-images.githubusercontent.com/5946359/230114709-be027149-1133-4726-b774-d9287f512e5f.mp4

### To Reproduce

To reproduce the bug, start of by creating an instance using version 9.22.3. Create three collections and a relationship as described above. Visualise the relationship by adding the field to the table view. This should still work. Update to version 9.23.4. Now that field will give you either an empty bracket or the `0 items` values. Updating to version 9.24.0 doesn't resolve the issue either.

This bug could not be replicated on a clean instance of version 9.23.4 or 9.24.0, hosted by Directus Cloud.

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
We haven't been able to reproduce this based on the given information with the latest version (9.25.1), so I'll close this for now. Chances are high that the issue you were experiencing has been fixed in the meantime. Happy to keep discussing in this thread, if you think this is actually still an issue!

**Comment by nskartoredjo** [comment]
I've updated the instance to the latest version (9.25.2) and it indeed seems to be resolved!
