### ISSUE TITLE
API calls very slow

### ISSUE THREAD

**Issue by MartinMekhaiel** [directus/directus#1807]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests please use the [Directus FeatHub](http://feathub.com/directus/directus) to make a new request or vote for existing ones, or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues.

## Version Info
  - Directus version and branch: (Or commit hash)
  3d7225c1ff05dd3ff1d0acd83515a0f71ccf2841
  - PHP version: 
7.0.8
  - MySQL version: 
5.5.42
  - Web server: (Ex. Apache, nginx or IIS?) 
apache
  - OS name and version: 
macosx sierra

## Expected Behavior
Fast api calls

## Actual Behavior
a normal api call on a table takes 1,3 seconds without any filtering and 2 items in the table.
`<?php 

require 'vendor/autoload.php';

$client = \Directus\SDK\ClientFactory::create('<secret>', [
    'base_url' => 'http://<my-server>/cms/directus/',
    'version' => '1.1'
]);

$params = [];

$results = $client->getItems('products', $params);
exit;
`
![bildschirmfoto 2017-09-12 um 18 06 41](https://user-images.githubusercontent.com/7896311/30336357-372d9d2e-97e5-11e7-9533-274f8750d258.png)

what can i do?

**Comment by MartinMekhaiel** [comment]
if i do some more selects and filtering it can go up to 5 seconds,

I have the same script with a native PDO select executing in 50ms

**Comment by rijkvanzanten** [comment]
Thanks for reporting this as well. As it's a duplicate, lets move all further discussion to the original issue #1575
