### ISSUE TITLE
Allow configuring non-manual sort order for the o2m style interfaces

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#18076]
### Discussed in https://github.com/directus/directus/discussions/12771

<div type='discussions-op-text'>

<sup>Originally posted by **paulboudewijn** November 19, 2021</sup>
When no sort field is configured for a relation, the PK is used as the default sort field instead of using the field(s) used in the display template. This results in a seemingly random list of items in the m2m interface.

I have a PR ready.

### To Reproduce

1. Create a 'book' collection with the 'title' and 'subtitle' fields
2. Create an 'author' collection
3. Create a m2m relation between 'author' and 'book', without sortfield and interface displaytemplate
4. Note that the m2m interface list 'books' on the 'author' collection is sorted by the PK field
5. Add displaytemplate `{{book_id.title}} - {{book_id.subtitle}}` to the interface
6. Note that the m2m interface list is still sorted in the PK field, although title and subtitle alphabetically could suggest otherwise
7. Add a sort field  `sort` to the relation
8. Note that the interface list is sorted on this column (as expected)</div>

**Comment by LevelUpGit** [comment]
+1

**Comment by carlo-salinari** [comment]
Is there any plan to include this fix in version 11?

**Comment by rijkvanzanten** [comment]
@carlo-salinari See https://github.com/directus/directus/pull/23019 👍🏻
