### ISSUE TITLE
Docker Image / NPM fails + Dependency Errors

### ISSUE THREAD

**Issue by ernst86913** [directus/directus#18081]
### Describe the Bug

**ERROR - "NPM INSTALL XXXXXXXXXXX" INSIDE DOCKER TERMINAL**

npm ERR! Cannot read properties of null (reading 'matches')

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2023-04-06T09_18_16_982Z-debug-0.log

**ERROR - "NPM INSTALL" INSIDE DOCKER TERMINAL:**

npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: rollup-plugin-styles@4.0.0
npm WARN Found: rollup@3.19.1
npm WARN node_modules/rollup
npm WARN   rollup@"3.19.1" from the root project
npm WARN   10 more (rollup-plugin-esbuild, @directus/extensions-sdk, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer rollup@"^2.63.0" from rollup-plugin-styles@4.0.0
npm WARN node_modules/rollup-plugin-styles
npm WARN   rollup-plugin-styles@"4.0.0" from @directus/extensions-sdk@9.24.0
npm WARN   node_modules/@directus/extensions-sdk
npm WARN 
npm WARN Conflicting peer dependency: rollup@2.79.1
npm WARN node_modules/rollup
npm WARN   peer rollup@"^2.63.0" from rollup-plugin-styles@4.0.0
npm WARN   node_modules/rollup-plugin-styles
npm WARN     rollup-plugin-styles@"4.0.0" from @directus/extensions-sdk@9.24.0
npm WARN     node_modules/@directus/extensions-sdk
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /directus/package-lock.json
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, open '/directus/package-lock.json'
npm ERR!  [Error: EACCES: permission denied, open '/directus/package-lock.json'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/directus/package-lock.json'
npm ERR! }

### To Reproduce

Run latest version of Directus in Docker Image and open Docker Terminal and run the two commands describe above.

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
> Run latest version of Directus in Docker Image and open Docker Terminal and run the two commands describe above.

When installing additional packages, you should create a new Docker Image rather than installing into a live ephemeral container 👍🏻 

For example:

```dockerfile
FROM directus/directus:9.24.0

RUN corepack enable \
  && corepack prepare \
  && pnpm install xxxxxxxxx \
  && pnpx directus bootstrap \
  && pnpx directus start
```

**Comment by ernst86913** [comment]
Till now it worked that way..: but thanks a lot for pointing out that there is a different / better way to do it - will give it a try :)

LG,
Roman

Von meinem iPhone gesendet

On 06.04.2023, at 23:28, Rijk van Zanten ***@***.***> wrote:

﻿

Run latest version of Directus in Docker Image and open Docker Terminal and run the two commands describe above.

When installing additional packages, you should create a new Docker Image rather than installing into a live ephemeral container 👍🏻

For example:

FROM directus/directus:9.24.0

RUN corepack enable \
  && corepack prepare \
  && pnpm install xxxxxxxxx \
  && pnpx directus bootstrap \
  && pnpx directus start

**Comment by ernst86913** [comment]
@rijkvanzanten  ... unfortunately not working - any idea?

 => CACHED [1/2] FROM docker.io/directus/directus:latest                                                                                                                                                         0.0s 
 => ERROR [2/2] RUN corepack enable     && corepack prepare     && pnpm install mangopay2-nodejs-sdk     && pnpx directus bootstrap     && pnpx directus start                                                   0.4s 
------
 > [2/2] RUN corepack enable     && corepack prepare     && pnpm install mangopay2-nodejs-sdk     && pnpx directus bootstrap     && pnpx directus start:
#0 0.396 Internal Error: EACCES: permission denied, symlink '../lib/node_modules/corepack/dist/pnpm.js' -> '/usr/local/bin/pnpm'
#0 0.396 Error: EACCES: permission denied, symlink '../lib/node_modules/corepack/dist/pnpm.js' -> '/usr/local/bin/pnpm'
------
failed to solve: executor failed running [/bin/sh -c corepack enable     && corepack prepare     && pnpm install mangopay2-nodejs-sdk     && pnpx directus bootstrap     && pnpx directus start]: exit code: 1

**Comment by paescuj** [comment]
The correct Dockerfile should look like this:
```Dockerfile
FROM directus/directus:9.24.0

USER root
RUN corepack enable \
  && corepack prepare pnpm@8.1.1 --activate \
  # Currently required, we'll probably address this in the base image in future release
  && chown node:node /directus

USER node
RUN pnpm install xxxxxxxxx
```

I'll see that the corresponding documentation is updated 👍

**Comment by ernst86913** [comment]
Just perfect - that’s working - thanks a lot!

LG,
Roman

**Comment by Alex-NHS** [comment]
Hi everyone, with this approach, the image size is doubled. 
Can we make a more memory-efficient tweak to reduce the image size?
