### ISSUE TITLE
Unexpected Error with refreshing presets

### ISSUE THREAD

**Issue by bamboowonder** [directus/directus#18089]
### Describe the Bug

Our users are getting "Unexpected Error" with an option to "Reset Page Preferences"
It occurs on saved views/presets that have a 5min refresh interval.
User goes away from computer, or spends time on a another tab while the page auto-refresh occurs.
It seems to be only on the front-end, browser console log is below.  However server logs show no error.

As an administrator, if I click the "Reset Page Preferences" button in the error, it silently duplicates the saved preset with the refresh disabled.  (note this preset has a Global Scope, so any changes I make outside of the admin UI are save-as anyway).

We do use cloudflare, though because of many other issues with directus/CF, and the CF minifying and WAF rules, we have disabled all it's features so that it's just a dumb proxy at this point.

I'm going to test if disabling the refresh solves the error.

Browser console error below:

`Uncaught (in promise) X {message: 'Request failed with status code 401', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}code: "ERR_BAD_REQUEST"config: adapter: (2) ['xhr', 'http']baseURL: "/"data: undefinedenv: {FormData: ƒ, Blob: ƒ}headers: $r {Accept: 'application/json, text/plain, */*', Authorization: 'Bearer xxxxxxxxxxxxxx.eyJpZC…1cyJ9.xxxxxxxxxxxxxx', Content-Type: null}id: "_gyEzvuebfdT9pqwn1iJT"maxBodyLength: -1maxContentLength: -1method: "get"params: {aggregate: {…}}signal: AbortSignal {aborted: false, reason: undefined, onabort: null}timeout: 0transformRequest: [ƒ]transformResponse: [ƒ]transitional: {silentJSONParsing: true, forcedJSONParsing: true, clarifyTimeoutError: false}url: "/items/x_5344_y79ad2de1-86e2-44dd-a714-xxxxxxxxxxxxxx"validateStatus: ƒ (s)withCredentials: truexsrfCookieName: "XSRF-TOKEN"xsrfHeaderName: "X-XSRF-TOKEN"[[Prototype]]: Objectmessage: "Request failed with status code 401"name: "AxiosError"request: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: true, upload: XMLHttpRequestUpload, …}response: {data: {…}, status: 401, statusText: '', headers: $r, config: {…}, …}stack: "AxiosError: Request failed with status code 401\n    at D_ (https://xxxxxxxxxxxxxx.xxxxxxxxxxxxxx.com/admin/assets/use-sync-5cbb6423.js:29:949)\n    at XMLHttpRequest.P (https://xxxxxxxxxxxxxx.xxxxxxxxxxxxxx.com/admin/assets/use-sync-5cbb6423.js:29:4045)"[[Prototype]]: Error
xe @ use-sync-5cbb6423.js:29
await in xe (async)
Tt @ index.bdce314d.entry.js:1858
Qt @ index.bdce314d.entry.js:1858
$e @ runtime-core.esm-bundler-becf0084.js:1
Ae @ runtime-core.esm-bundler-becf0084.js:1
oi @ runtime-core.esm-bundler-becf0084.js:1
(anonymous) @ index.bdce314d.entry.js:1858
use-sync-5cbb6423.js:29          GET https://xxxxxxxxxxxxxx.xxxxxxxxxxxxxx.com/items/x_5344_y79ad2de1-86e2-44dd-a714-xxxxxxxxxxxxxx?limit=25&fields[]=52101767.first_name&fields[]=6a13b5fa.id&fields[]=call_result&fields[]=screening_status&fields[]=status_notes&fields[]=first_name&fields[]=last_name&fields[]=mobile_phone&fields[]=email_primary&fields[]=gender&fields[]=age_group&fields[]=z_ethnicity&fields[]=city&fields[]=province&fields[]=q01_industries&fields[]=q05_hours_listen&fields[]=q06_stations_listen_to&fields[]=q07_favourite_station&fields[]=q08b_station_choice&fields[]=q08_montage_rating&fields[]=q09_past_participation&fields[]=q10_last_time_participating&fields[]=z_incentive_method&fields[]=created&fields[]=updated&fields[]=id&alias[52101767]=recruiter_id&alias[6a13b5fa]=recruiter_id&sort[]=id&page=1&filter[_and][0][_or][0][screening_status][_starts_with]=Ready&filter[_and][0][_or][1][screening_status][_starts_with]=Screen&filter[_and][0][_or][2][screening_status][_null]=true&filter[_and][1][q06_stations_listen_to][_contains]=Move 401
(anonymous) @ use-sync-5cbb6423.js:29
xhr @ use-sync-5cbb6423.js:29
gf @ use-sync-5cbb6423.js:29
Promise.then (async)
request @ use-sync-5cbb6423.js:29
Mr.<computed> @ use-sync-5cbb6423.js:29
(anonymous) @ use-sync-5cbb6423.js:27
Cn @ use-sync-5cbb6423.js:29
Tt @ index.bdce314d.entry.js:1858
Qt @ index.bdce314d.entry.js:1858
$e @ runtime-core.esm-bundler-becf0084.js:1
Ae @ runtime-core.esm-bundler-becf0084.js:1
oi @ runtime-core.esm-bundler-becf0084.js:1
(anonymous) @ index.bdce314d.entry.js:1858
setInterval (async)
Wn.immediate @ index.bdce314d.entry.js:1858
$e @ runtime-core.esm-bundler-becf0084.js:1
Ae @ runtime-core.esm-bundler-becf0084.js:1
R @ runtime-core.esm-bundler-becf0084.js:1
Rs @ runtime-core.esm-bundler-becf0084.js:1
te @ runtime-core.esm-bundler-becf0084.js:1
T @ runtime-core.esm-bundler-becf0084.js:1
run @ runtime-core.esm-bundler-becf0084.js:1
G.c.update @ runtime-core.esm-bundler-becf0084.js:1
Oe @ runtime-core.esm-bundler-becf0084.js:1
Z @ runtime-core.esm-bundler-becf0084.js:1
R @ runtime-core.esm-bundler-becf0084.js:1
Ht @ runtime-core.esm-bundler-becf0084.js:1
Q @ runtime-core.esm-bundler-becf0084.js:1
ie @ runtime-core.esm-bundler-becf0084.js:1
R @ runtime-core.esm-bundler-becf0084.js:1
Ht @ runtime-core.esm-bundler-becf0084.js:1
Q @ runtime-core.esm-bundler-becf0084.js:1
ie @ runtime-core.esm-bundler-becf0084.js:1
R @ runtime-core.esm-bundler-becf0084.js:1
Ht @ runtime-core.esm-bundler-becf0084.js:1
Q @ runtime-core.esm-bundler-becf0084.js:1
ie @ runtime-core.esm-bundler-becf0084.js:1
R @ runtime-core.esm-bundler-becf0084.js:1
H @ runtime-core.esm-bundler-becf0084.js:1
U @ runtime-core.esm-bundler-becf0084.js:1
M @ runtime-core.esm-bundler-becf0084.js:1
R @ runtime-core.esm-bundler-becf0084.js:1
T @ runtime-core.esm-bundler-becf0084.js:1
run @ runtime-core.esm-bundler-becf0084.js:1
G.c.update @ runtime-core.esm-bundler-becf0084.js:1
Oe @ runtime-core.esm-bundler-becf0084.js:1
Z @ runtime-core.esm-bundler-becf0084.js:1
R @ runtime-core.esm-bundler-becf0084.js:1
T @ runtime-core.esm-bundler-becf0084.js:1
run @ runtime-core.esm-bundler-becf0084.js:1
G.c.update @ runtime-core.esm-bundler-becf0084.js:1
Oe @ runtime-core.esm-bundler-becf0084.js:1
Z @ runtime-core.esm-bundler-becf0084.js:1
R @ runtime-core.esm-bundler-becf0084.js:1
H @ runtime-core.esm-bundler-becf0084.js:1
U @ runtime-core.esm-bundler-becf0084.js:1
M @ runtime-core.esm-bundler-becf0084.js:1
R @ runtime-core.esm-bundler-becf0084.js:1
T @ runtime-core.esm-bundler-becf0084.js:1
run @ runtime-core.esm-bundler-becf0084.js:1
G.c.update @ runtime-core.esm-bundler-becf0084.js:1
Oe @ runtime-core.esm-bundler-becf0084.js:1
Z @ runtime-core.esm-bundler-becf0084.js:1
R @ runtime-core.esm-bundler-becf0084.js:1
T @ runtime-core.esm-bundler-becf0084.js:1
run @ runtime-core.esm-bundler-becf0084.js:1
G.c.update @ runtime-core.esm-bundler-becf0084.js:1
Oe @ runtime-core.esm-bundler-becf0084.js:1
Z @ runtime-core.esm-bundler-becf0084.js:1
R @ runtime-core.esm-bundler-becf0084.js:1
Ht @ runtime-core.esm-bundler-becf0084.js:1
Q @ runtime-core.esm-bundler-becf0084.js:1
ie @ runtime-core.esm-bundler-becf0084.js:1
R @ runtime-core.esm-bundler-becf0084.js:1
T @ runtime-core.esm-bundler-becf0084.js:1
run @ runtime-core.esm-bundler-becf0084.js:1
G.c.update @ runtime-core.esm-bundler-becf0084.js:1
$e @ runtime-core.esm-bundler-becf0084.js:1
mr @ runtime-core.esm-bundler-becf0084.js:1
Promise.then (async)
gr @ runtime-core.esm-bundler-becf0084.js:1
bn @ runtime-core.esm-bundler-becf0084.js:1
(anonymous) @ runtime-core.esm-bundler-becf0084.js:1
Ts @ runtime-core.esm-bundler-becf0084.js:1
Nn @ runtime-core.esm-bundler-becf0084.js:1
yn @ runtime-core.esm-bundler-becf0084.js:1
(anonymous) @ runtime-core.esm-bundler-becf0084.js:1
Ts @ runtime-core.esm-bundler-becf0084.js:1
Nn @ runtime-core.esm-bundler-becf0084.js:1
yn @ runtime-core.esm-bundler-becf0084.js:1
(anonymous) @ runtime-core.esm-bundler-becf0084.js:1
Ts @ runtime-core.esm-bundler-becf0084.js:1
Nn @ runtime-core.esm-bundler-becf0084.js:1
yn @ runtime-core.esm-bundler-becf0084.js:1
set value @ runtime-core.esm-bundler-becf0084.js:1
y @ index.bdce314d.entry.js:79
set @ index.bdce314d.entry.js:79
set value @ runtime-core.esm-bundler-becf0084.js:1
set @ runtime-core.esm-bundler-becf0084.js:1
set @ runtime-core.esm-bundler-becf0084.js:1
P.onUpdate:modelValue.t.<computed>.t.<computed> @ index.bdce314d.entry.js:1858
$e @ runtime-core.esm-bundler-becf0084.js:1
Ae @ runtime-core.esm-bundler-becf0084.js:1
oi @ runtime-core.esm-bundler-becf0084.js:1
set @ index.bdce314d.entry.js:1858
set value @ runtime-core.esm-bundler-becf0084.js:1
set @ runtime-core.esm-bundler-becf0084.js:1
set @ runtime-core.esm-bundler-becf0084.js:1
P.onUpdate:modelValue.t.<computed>.t.<computed> @ index.bdce314d.entry.js:1858
$e @ runtime-core.esm-bundler-becf0084.js:1
Ae @ runtime-core.esm-bundler-becf0084.js:1
oi @ runtime-core.esm-bundler-becf0084.js:1
_e.children.ge.onUpdate:modelValue.C.<computed>.C.<computed> @ index.bdce314d.entry.js:2603
$e @ runtime-core.esm-bundler-becf0084.js:1
Ae @ runtime-core.esm-bundler-becf0084.js:1
oi @ runtime-core.esm-bundler-becf0084.js:1
e.item.divider.ge.onClick.a.<computed>.a.<computed> @ index.bdce314d.entry.js:2603
$e @ runtime-core.esm-bundler-becf0084.js:1
Ae @ runtime-core.esm-bundler-becf0084.js:1
oi @ runtime-core.esm-bundler-becf0084.js:1
m @ index.bdce314d.entry.js:2603
$e @ runtime-core.esm-bundler-becf0084.js:1
Ae @ runtime-core.esm-bundler-becf0084.js:1
s @ vue.runtime.esm-bundler-dbfb2032.js:1`

### To Reproduce

I don't know that this can be easily reproduced outside of our system, other than providing more logs or details?

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Similar to and should be fixed along with #17083
