### ISSUE TITLE
Imageuploader Broken in develop branch

### ISSUE THREAD

**Issue by MartinMekhaiel** [directus/directus#1808]
## Version Info
  - Directus version and branch: (Or commit hash)
26d4ab5733b9a50349ef67f36193f86125f8e239
  - PHP version: 
7.0.8
  - MySQL version: 
5.5.42
  - Web server: (Ex. Apache, nginx or IIS?) 
apache
  - OS name and version: 
macosx sierra

## Actual Behavior
when i do a git pull origin develop 
and then try to upload images via drag&drop or via select, they get uploaded and resized but the
preview is not working its showing some fallback image

## Steps to Reproduce
 1. clone the repo
 2. git checkout origin devleop
 3. add a singlefile interface
 4. drag & drop a image
5. save

**Comment by rijkvanzanten** [comment]
Thanks for reporting this as well. As it's a duplicate, lets move all further discussion to the original issue  #1804.
