### ISSUE TITLE
Aren't snapshots supposed to carry over every configuration between Directus instances?

### ISSUE THREAD

**Issue by mpenna** [directus/directus#18090]
### Describe the Bug

As an attempt to mock and test out a Dev/Prod deployment workflow, I have two instances of Directus running locally: one from source and a second one from the Docker image. After doing some work on the first (Dev) instance, creating and configuring some collections and their fields, along with some environment settings, I have generated a snapshot in order to migrate all this over to the second instance (Prod). Not sure what exactly is going on here, but it seems that not everything is being ported over. I took a screen capture of a specific collection on both instances to point out a couple differences between the two instances:

Dev Instance

![Screenshot from 2023-04-06 17-13-44](https://user-images.githubusercontent.com/6953141/230489544-9ea5ca51-a5f3-46b2-8fe9-98b19f5ff25d.png)

- all collection names are being displayed in Portuguese
- the one collection visible on the image has its alias field "cities" hidden

Prod Instance

![Screenshot from 2023-04-06 17-13-51](https://user-images.githubusercontent.com/6953141/230489576-5a96129c-67db-4bcc-a926-850b7d63cca9.png)

- all collection names are being displayed in English
- the one collection visible on the image has its alias field "cities" being displayed

These and other discrepancies are occurring with other collections also.

BTW, the data itself I have migrated over via custom migrations.

### To Reproduce

Set two Directus instances up. Create some collections on one instance and configure their fields accordingly. Also configure other various environment/project settings (e.g.: project name, default language, etc.). Generate a snapshot at the instance that has been configured and then apply that snapshot at the second instance. 

One expects to see the second instance in sync with the first one. As described above, this does not seem to be happening.

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by LilaRest** [comment]
Hi @mpenna ! Since few days I'm also trying to achieve local->dev->prod sync of schema and data (permissions, roles, dashboard, flows, etc.).

About your issue, have you migrated also data between your two instances ? Or just schema ?

I think that translations and project settings are data. Which means that you are not migrating those one when performing a snapshot of **the schema** and then applying it on the other instance.

**Comment by rijkvanzanten** [comment]
The schema snapshot only contains the _schema_ information (collections/fields/relations). It does not contain any user preferences (like layout configuration or language etc)

**Comment by mpenna** [comment]
Hi @LilaRest I'm performing basically two tasks: one that relies on schema snapshots and another one that is mainly a seeding operation. For the seeding operation, I created some custom migrations that actually just seed some tables with initial data. This will probably come to be a one-off operation, whenever it's time to actually deploy the app on the target environment. Now, the schema migrations, these are being done regularly. Whenever I change something schema-related on my local environment, I generate a new snapshot and subsequently apply that on a secondary environment I have set up locally (to simulate an actual dev > prod CD workflow). 

@rijkvanzanten Thanks for clearing that out. What would you say is the best way to get all this "extra" data also migrated over to a secondary environment?

**Comment by mpenna** [comment]
Not sure if I got you there. Do you mean the import/export (csv/json) options available on the sidebar of the data models, user directory and file library pages (https://docs.directus.io/app/import-export.html#import-export)? OK, but will this take care of migrating the actual information regarding layout configuration, tanslations, etc., as you pointed out in your previous comment? Where is all this info actually stored?

**Comment by rijkvanzanten** [comment]
@mpenna yeah! and/or through the API `?export` query param and import endpoints. To where the actual information is stored, it depends on what you're looking to migrate; for Presets (eg layout configuration etc), it's in Presets `/presets`: https://docs.directus.io/reference/system/presets.html or `directus_presets` in the database :slig

**Comment by mpenna** [comment]
Thanks. I will check that out and see if I can get the missing info migrated over.

**Comment by mpenna** [comment]
Oh boy. Every corner I turn, I end up hittin' some wall. Although I'm using a valid static token for the Admin user issued at the secondary environment, I'm getting a 403 `FORBIDDEN` error when trying to import *.csv files correctly generated at the primary environment. Can't figure out why this is happening.

![Screenshot from 2023-04-11 14-58-22](https://user-images.githubusercontent.com/6953141/231248978-2e830aa0-0f97-476f-8024-d35593d55d92.png)

**Comment by hinsxd** [comment]
> Oh boy. Every corner I turn, I end up hittin' some wall. Although I'm using a valid static token for the Admin user issued at the secondary environment, I'm getting a 403 `FORBIDDEN` error when trying to import *.csv files correctly generated at the primary environment. Can't figure out why this is happening.
> 
> ![Screenshot from 2023-04-11 14-58-22](https://user-images.githubusercontent.com/6953141/231248978-2e830aa0-0f97-476f-8024-d35593d55d92.png)

This happens when I try to import using the UI too. Super annoying and I still cannot find a way to migrate Flows operations between environments. I am starting to wonder if I chose the wrong framework and whether I should give it up before it is too late.
