### ISSUE TITLE
Sorting M2A items does not work anymore in Directus 9.24.0

### ISSUE THREAD

**Issue by martijnboland** [directus/directus#18096]
### Describe the Bug

Just updated Directus from 9.23.1 to 9.24.0 and I noticed that I can not re-order M2A items anymore. They are still draggable, but jump back to their previous positions after dropping. When saving, the sort order isn't changed in the database as well. 
This happens with both existing collections and new collections. 

Reverted back to 9.23.1 and sorting works again.

### To Reproduce

Create a collection with a M2A field that contains a couple of different items and a sort field. Then try to re-order the items.

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
Also seems to be an issue for the other multiple relational interfaces o2m/m2m/m2a

**Comment by abdelmomen1985** [comment]
I've face same issue with M2A  items, that's what i did to resolve it 
- Add sort filed to the hidden M2A builder collection 
- For the collection with builder itself i've edited the relation field by adding a sort 

![image](https://user-images.githubusercontent.com/701675/231351323-1cdc3f01-50d9-45b9-90a0-00ede1fff3ea.png)

And it's working properly , my directus version is 9.24

**Comment by vv1n3k** [comment]
I'm here to just confirm. Reverting to 9.23 fix the issue.

**Comment by Ashcon** [comment]
This has become a critical issue for us on Cloud as well. We of course don't have a way to revert versions so we're kind of stuck across our multiple deployments right now.
