### ISSUE TITLE
how to restore revision via gui?

### ISSUE THREAD

**Issue by MartinMekhaiel** [directus/directus#1809]
i see all the revisons made but how can i restore them via the gui?

**Comment by benhaynes** [comment]
Hey @MartinMekhaiel – the revisions are stored in the `directus_activity` table for all changes, but we don't have a GUI for restoring previous deltas yet. You can request it over on FeatHub (as a new feature) and we'll definitely vote it up (we're excited to get this one too). Small team, so we have to prioritize these new features.

https://feathub.com/directus/directus

**Comment by MartinMekhaiel** [comment]
thanks i did that!

https://feathub.com/directus/directus/+121

**Comment by benhaynes** [comment]
I upvoted it! Let's get this to the top...
