### ISSUE TITLE
avg field doesn't work (but count does)

### ISSUE THREAD

**Issue by andreirt** [directus/directus#18098]
### Describe the Bug

I have three Collections, Post, Rating and Like. I am able to list all the posts including the number of likes each post has, but not the average value of post ratings. For testing purposes, I added the 'count(ratings)' field, and it works:

```
postsService.readByQuery(
  {
    limit: -1,
    fields: ['thumbnail', 'count(likes)', 'avg(ratings.rating)', 'count(ratings)'],
  },
)
```

For context, I am wrinting an endpoint extension.

### To Reproduce

- create three collections, Post, Like and Rating. Post should include two relational fields, likes and ratings, and Rating should have a rating field (numeric). 
- query all posts, including these fields, 'count(likes)' and 'avg(ratings.rating)'. The likes_count field is found on results, but not the average field.

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
`avg` is not a function available to use in fields https://docs.directus.io/reference/query.html#functions
to get averages you'll want to look into aggregation https://docs.directus.io/reference/query.html#aggregation-grouping
