### ISSUE TITLE
None of the Codesandbox examples work

### ISSUE THREAD

**Issue by JonasGruenwald** [directus/directus#18103]
### Page

https://github.com/keystonejs/keystone/tree/main/examples/usecase-blog

### Describe the Inaccuracy

This applies to all of the examples, when clicking the Codesandbox link it fails to build with an error.
Error from this example is the following:

```
yarn run v1.22.19
$ keystone dev
✨ Starting Keystone
✘ [ERROR] Could not resolve "../example-utils"

    keystone.ts:2:30:
      2 │ import { fixPrismaPath } from '../example-utils';
        ╵                               ~~~~~~~~~~~~~~~~~~

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentationabout this command.
```

Codesandbox link:
https://githubbox.com/keystonejs/keystone/tree/main/examples/usecase-blog

**Comment by rijkvanzanten** [comment]
I think you're in the wrong repo friend 😄 This ain't keystone

**Comment by JonasGruenwald** [comment]
Embarassing, I just noticed it before you replied, so quick!
My bad 😬
