### ISSUE TITLE
MANY2MANY filter doesn't work

### ISSUE THREAD

**Issue by MartinMekhaiel** [directus/directus#1810]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests please use the [Directus Request Tool](https://request.getdirectus.com/) to make a new request or vote for existing ones, or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues.

## Version Info
  - Directus version and branch: (Or commit hash)
4dd466d69374627ee1782892c65010f385f4038d
  - PHP version: 
7.0.8
  - MySQL version: 
5
  - Web server: (Ex. Apache, nginx or IIS?) 
apache
  - OS name and version: 
macosx sierra
## Expected Behavior
filtering based on many2many field 

## Actual Behavior
im trying to filter on a many2many realationship field, directus is trying to filter on that column, but for m2m relationships there are no columns inside a table

## Steps to Reproduce
 1. create a many2many field with a junction table
 2. try to filter based on that in die main table
 3. See the SELECT error

**Comment by WellingGuzman** [comment]
Hey @MartinMekhaiel can you please share logs and screenshots, and if possible an schema?

**Comment by MartinMekhaiel** [comment]
Ill Share the screenshots first, let me know if that makes it clear, bcause the schema dumps and so on take some time for me as a i cant share all our data

So first we add a new Many 2 Many Relation ship

"products.included_services" 
i have a table "included_services"
and a junction table "product_included_services" (where i store product_id and service_id)

![bildschirmfoto 2017-09-14 um 02 10 44](https://user-images.githubusercontent.com/7896311/30406504-6cc01b02-98f2-11e7-9d91-c59aaad855ad.png)

next i set the filtercolumn to "description" which is a valid column in the included_services table,
and filter_type to "text input"
![bildschirmfoto 2017-09-14 um 02 10 53](https://user-images.githubusercontent.com/7896311/30406528-9b6e7462-98f2-11e7-8942-c623965414d5.png)

in my product entry then i have a list like that 
![bildschirmfoto 2017-09-14 um 02 12 07](https://user-images.githubusercontent.com/7896311/30406551-c2edc920-98f2-11e7-9535-4746ed691d03.png)

Now lets make a text search for the first entry "2 x .."
![bildschirmfoto 2017-09-14 um 02 17 51](https://user-images.githubusercontent.com/7896311/30406575-f398cdb8-98f2-11e7-88c0-a58192b0bf7d.png)

In the error message it says: 
"WHERE products.included_services LIKE %2 x% ..."
but the column "included_services" doesnt exist on the proucts_table i checked in the database it seems that directus isnt creating columns for m2m relationships

so if i do the same query in mysql obviosly the same error occurs. 

Hope that makes it clear

Thanks for the help

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/4a680ec26eaf92a073c7a9b5efb1bd747dfa47ce
