### ISSUE TITLE
Empty response when creating item with no view permissions

### ISSUE THREAD

**Issue by unleashit** [directus/directus#18108]
### Describe the Bug

When creating a new item through the API with create permissions only (no view perms), the server responds with a 204 but no response body. This causes an error if the client was expecting JSON. If the client requests JSON, I think a valid JSON response is expected.

The problem goes away as soon as at least one field is given read permission (Directus sends that in the response). This isn't ideal since then the collection can then be enumerated based on the field(s).

### To Reproduce

1. Add a collection and grant the public create permissions (and no other).
2. In a web application, make a POST request (using fetch, etc.) with the appropriate body and a `Content-Type: application/json` header.
3. Content successfully is added, but if you try to parse the response as JSON (like response.json() in fetch), you get an error:

`Uncaught (in promise) SyntaxError: Unexpected end of JSON input`

While it's possible to manually process in a catch block, it shouldn't be needed.

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
This is working as expected and intended. If you're not allowed to read anything, the response will be empty. An empty http body should have status 204 no content. When it comes to `fetch` in client side JS, you can check the status code for a 204 before using the json helper 👍🏻

**Comment by unleashit** [comment]
Not a big deal, but I've never heard of this being a standard (blank response in this particular case), and I have seen the opposite opinion. You're right it's easy to handle, I guess since the fetcher I use has abstracted the double promise (and so I do need to use catch), it made me think it was worth posting. After thinking about it it seems like it's probably more of an API designer's choice then right or wrong.

**Comment by rijkvanzanten** [comment]
> I've never heard of this being a standard (blank response in this particular case), and I have seen the opposite opinion. 

Mind sharing where? Always interested in hearing the counter arguments :)

**Comment by rijkvanzanten** [comment]
Also curious to hear what you think it should return instead; would it be an empty object? The word "null" (which is technically valid JSON), or..?

**Comment by unleashit** [comment]
> Mind sharing where? Always interested in hearing the counter arguments :)

I did recently see a SO post where a lot of people agreed the a server should respond in this situation, and I tried to find it when I made the initial post... but now I can't. Not that something on SO is a final word.

It's not the most common situation, but In my anecdotal experience, APIs I've worked with when for example posting a contact form return something. I'm not sure if Directus has the ability to create an "own" permission for just the submission, but for my own API's I'd usually return a copy of of the item, maybe with ID. Alternatively, an empty object doesn't seem bad. A lot of APIs do something like:

```javascript
{ "success": true }
```
I'm not really a fan of that because the status code tell you that already.

Not trying to disagree. I'm a front end dev before all else 😉 I highly respect your opinion brother...  this was just the first time I've run into the issue. And even if it "can" happen, it means its a bug in my fetcher and I've decided to handle the 204 (and other non-200 2xx) cases even though I wasn't expecting them.

**Comment by unleashit** [comment]
In the spirit of nerdery (and since I didn't want to be empty handed 🤷 ) I just had a sec and found that MDN seems to favor a 201 with the newly created item in the response body:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201

This guy](https://blog.ploeh.dk/2013/04/30/rest-lesson-learned-avoid-204-responses/) seems to agree, although he's mainly speaking in the context of HATEOAS I think.

The quote at the top of https://apihandyman.io/empty-lists-http-status-code-200-vs-204-vs-404/ made me laugh a bit.

I guess the beauty of the state of REST is the "right" way to do certain things can depend on who you ask. At least before AI takes over...

**Comment by rijkvanzanten** [comment]
> I did recently see a SO post where a lot of people agreed the a server should respond in this situation, and I tried to find it when I made the initial post... but now I can't. Not that something on SO is a final word.

All good! I’m just immediately morbidly curious :) Always trying to improve, so if there’s any better standard/fit for doing things, i’m all ears

> It's not the most common situation, but In my anecdotal experience, APIs I've worked with when for example posting a contact form return something. I'm not sure if Directus has the ability to create an "own" permission for just the submission, but for my own API's I'd usually return a copy of of the item, maybe with ID

This can be configured! The response will have to be based on the read permissions though, as the input data isn’t necessarily the same data that’s saved for the database. For example, IDs, dates, user-created fields etc might be auto-generated, you might have extensions or flows that modify the data, or you might even have private fields associated to the item that the (public) poster isn’t allowed to see. You can currently configure this by adding a “user created” field to the collection, and then setting the read permissions to “allow where user created = $CURRENT_USER”. That’ll then also allow them to see the submissions they posted themselves 🙂 

> I'm not really a fan of that because the status code tell you that already.

Agreed!

> Not trying to disagree. I'm a front end dev before all else 😉 I highly respect your opinion brother... this was just the first time I've run into the issue. And even if it "can" happen, it means its a bug in my fetcher and I've decided to handle the 204 (and other non-200 2xx) cases even though I wasn't expecting them.

Not a problem! Same here :) Just trying to extract as much information as I can from these types of questions/suggestions to improve the overall platform. For example, if this fetcher library that you’re relying on is a standard, or a very popular default solution for a large portion of the user base, it makes a lot of sense to consider some tweaks on the directus side of the equation to smoothen out that interaction. 

One thing I am gathering from this is that we should probably look into using the 201 status code rather than the 204. It doesn’t necessarily fix your issue in that the body is potentially empty, but it is the better status to use for a successful creation :) Great example of how a friendly discussion like this helps improve the details of the platform :D 

> The quote at the top of https://apihandyman.io/empty-lists-http-status-code-200-vs-204-vs-404/ made me laugh a bit.

This is a great other conversation though! If you search for an item, but the search comes up empty, is that 200, 204, or 404? I’d argue that the “search” API endpoint is to get a list of results, and if that list is empty, it’s still a successful search result. It’s also not-empty in the http body, as you’d get an empty JSON array, so 200 is what we’re currently using ourselves 😄 

For creating a new item where you don’t have any permission to then see the item, there’s no real data we have that we can send back, which made me go with the 204 status initially :)

**Comment by unleashit** [comment]
I agree about the little things being important, but still definitely impressed with all that's going on you'd still find the time to care about this! By the way, the timing of me posting this and the license thread was pure coincidence that I happened to be working on my Directus project again. I've found a couple other (at least what I feel are) bugs, but I need to comb through the reports a bit better before I post (one is custom validation messages show up in the admin as you'd expect but aren't being sent when called externally through the API).

> This can be configured! The response will have to be based on the read permissions though, as the input data isn’t necessarily the same data that’s saved for the database. For example, IDs, dates, user-created fields etc might be auto-generated, you might have extensions or flows that modify the data, or you might even have private fields associated to the item that the (public) poster isn’t allowed to see. You can currently configure this by adding a “user created” field to the collection, and then setting the read permissions to “allow where user created = $CURRENT_USER”. That’ll then also allow them to see the submissions they posted themselves 🙂

Yeah I know all of this, and I also understand some of the extra challenges of trying to make an interface that has to suit a lot of needs.  But in this case (a public contact form) there is no user. I could create a public user... but then that'd be...  public (and I assume you could get a nice list at /items/collection... and I don't see why anyone needs to even know the COUNT(*) of how many contacts I get (not as many as I'd like Lol)). The only elegant way to solve it in the context of Directus (that I can think of), would be to add a new permission type that would allow reading of selected fields for the duration of a request/transaction. That would be the equivalent of simply hacking it into an ad hoc API response (temporarily bypassing any RBAC). Or a simpler idea could be adding a text area in the backend for a custom response (maybe with access to field vars that can bypass ACL) when otherwise null.

Not saying I love these ideas or if the problem is bad enough to justify the work. I personally like control over everything, but hey I realize there are bigger fish to fry then supporting some code hipster's idea of perfect semantics!

> For example, if this fetcher library that you’re relying on is a standard, or a very popular default solution for a large portion of the user base, it makes a lot of sense to consider some tweaks on the directus side of the equation to smoothen out that interaction.

Ha, no not exactly. It just a little something I cooked up to make NextJS 13 data fetching (with React Server Components) a little nicer: https://github.com/unleashit/next-promise-cache. For now, it's mostly a toy project but one of the side features is to try to handle the double promise. Just now took a look at axios (which I think uses XMLHttpRequest under the hood), since it also handles both the req and processing the resp. It goes to pretty great lengths to handle everything, so I would be surprised if a 204 caused it to choke. Anyhoo, I've tentatively updated mine to at least handle invalid JSON better: https://github.com/unleashit/next-promise-cache/blob/master/src/index.ts#L207-L235. Problem gone for now.

> One thing I am gathering from this is that we should probably look into using the 201 status code rather than the 204. 

Yeah, my take as well. I personally still feel like a response body should additionally be returned if the client is expecting JSON, but it seems like that's just an opinion. 

> Great example of how a friendly discussion like this helps improve the details of the platform :D

I enjoyed as well, and thank you... my code is better for it.

> If you search for an item, but the search comes up empty, is that 200, 204, or 404? If you search for an item, but the search comes up empty, is that 200, 204, or 404? I’d argue that the “search” API endpoint is to get a list of results, and if that list is empty, it’s still a successful search result. It’s also not-empty in the http body, as you’d get an empty JSON array, so 200 is what we’re currently using ourselves 😄

Totally agree it should be a 200 with an empty array. Better DX in case you just want to map over the result (and don't need to do anything special if empty). I mainly sent that because the D&D joke was semi related and pretty funny.
