### ISSUE TITLE
S3 file upload succeeds, but then read requests from that bucket all fail

### ISSUE THREAD

**Issue by JordanPQuinn** [directus/directus#18104]
### Describe the Bug

Hi folks! 

We have a directus instance self-hosted behind the VPN at my enterprise company. We're attempting to connect this directus deployment to an S3 bucket in our infrastructure to handle uploads.

The bucket is public, with all permissions granted for all object interactions to any principal.

It is able to successfully upload health check files to the bucket while bootstrapping, but then all requests to read out of the bucket fail with 403 access denied.

I'm curious what could be causing this ability to connect for uploads/put requests, but inability to read out of the bucket. Unfortunately I can't share much about our specific implementation due to the enterprise nature. We aren't setting a specific ACL on file uploads, which could be it.

### To Reproduce

- Point a self hosted docker image at an s3 bucket with all permissions for all object operations enabled
- S3 configurations used are: region, bucket, driver, and location. Nothing else. 
- file uploads should succeed, but then be unable to read back out of that bucket

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
@JordanPQuinn What was the cause?

**Comment by JordanPQuinn** [comment]
It ended up being not forcing https:// to be part of the endpoint for s3.amazonaws.com. So, for some reason, it could upload to just the plain url, but not retrieve
