### ISSUE TITLE
Cannot load directus script with proxy

### ISSUE THREAD

**Issue by romanlex** [directus/directus#18113]
### Describe the Bug

I can't use directus with proxy
For example I want all request to `http://my-domain.com/admin` send to directus
I can't made it because core js files loaded correctly but js files loaded via runtime cannot be loaded, for example
`/extensions/sources/index.js` 

![image](https://user-images.githubusercontent.com/3369304/230739584-e44e0e42-5210-4ec8-9945-b3e2ea2f7081.png)

Why this code https://github.com/directus/directus/blob/main/app/src/utils/get-root-path.ts#L4-L6 doesn't use env PUBLIC_URL for generate url in runtime? I think this resolve my issue

### To Reproduce

For example your can use nextjs app
```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  publicRuntimeConfig: {
    url: process.env.DIRECTUS_URL,
  },
  serverRuntimeConfig: {
    email: process.env.DIRECTUS_EMAIL,
    password: process.env.DIRECTUS_PASSWORD,
    // token: process.env.DIRECTUS_STATIC_TOKEN,
  },
  async rewrites() {
    return [
      {
        source: '/api/:path*',
        destination: `${process.env.DIRECTUS_URL}} ?? ''}/:path*`, // Proxy to Backend
      },
      {
        source: '/admin/:path*',
        basePath: false,
        locale: false,
        destination: `${process.env.DIRECTUS_URL ?? ''}/admin/:path*`, // Proxy to Backend
      },
    ]
  },
}

module.exports = nextConfig
```

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
The app is built to and expects to run in a path of the API 👍🏻 Feel free to open a new feature request on how you think this should work ideally 🙂
