### ISSUE TITLE
Can't select file in layout if it is nested in relation

### ISSUE THREAD

**Issue by lluishi93** [directus/directus#18139]
### Describe the Bug

Having a collection `small_banner` with these fields:

- background_video (`File`)
- background_image (`m2o` to collection `Image`)

And collection `Image` with these:
- src (`File`)
- translations -> alt

We're not able to use the background_image -> src field in the cards layout (or even in the Table layout)

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/14786440/231297999-c51db068-4ff8-4a14-97c7-df5d6ffdb93b.png">

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/14786440/231298143-5619233f-9fbb-46a2-b8fb-3fce8de36304.png">

### To Reproduce

- Create collection A with a `File` field
- Create collection B with a `m2o` pointing to collection A
- Create some items for both collections
- When listing items in collection B, try to use the `File` field inside collection A to add a column to the Table layout, or use it to render the image in the cards layout

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
That is correct, the cards layout does not support relational fields for image source. Feel free to create a feature request instead 😄
