### ISSUE TITLE
No documentation about preview=true

### ISSUE THREAD

**Issue by wittwerch** [directus/directus#1813]
I'm trying out to read the details of an item on the API. It looks like you need to append "preview=true" to items that are in the state of a draft. There is no documentation about that, I just found it out by inspecting the requests on the Directus frontend.

``
/api/1.1/tables/ideas/rows/4?preview=true
``

## Version Info
  - Directus version and branch: 75ec6debf62831d1397f9275056d5831272874a7

## Expected Behavior
The item should show up with all fields and data

## Actual Behavior
I get an empty response

```
{
    "meta": {
        "table": "ideas",
        "type": "item"
    },
    "data": []
}
```

**Comment by benhaynes** [comment]
Technically this should be an issue on the Docs repo. Either way, we'll get some docs up for this soon.

**Comment by WellingGuzman** [comment]
I added (moved) this ticket to `api-docs` repo.

Ref: https://github.com/directus/api-docs/issues/10
