### ISSUE TITLE
There's no "select all non directus-core collection permissions"

### ISSUE THREAD

**Issue by lluishi93** [directus/directus#18141]
### Describe the Bug

When creating a new role when Directus already has hundreds of collection, setting all permissions on existing non-core collections takes too much (or has to be done via script). 

<img width="264" alt="image" src="https://user-images.githubusercontent.com/14786440/231302670-0c90514d-b922-47d1-90ce-1b36e8a4d795.png">

### To Reproduce

- Create a lot of collections
- Check that there's no option for setting all permissions in non-core directus collections for fast role creation.

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
Heya! Mind opening this as [a Feature Request](https://github.com/directus/directus/discussions/new?category=feature-requests) instead? Thanks!

**Comment by lluishi93** [comment]
> Heya! Mind opening this as [a Feature Request](https://github.com/directus/directus/discussions/new?category=feature-requests) instead? Thanks!

done!
