### ISSUE TITLE
Cloudinary driver root not working

### ISSUE THREAD

**Issue by hamishjohnson** [directus/directus#18146]
### Describe the Bug

When using the 'root' with cloudinary to put files into a specific folder, I get errors:

[INTERNAL_SERVER_ERROR] No stream returned for file "18ab05e9-efd8-4cfc-9e99-6d154236a79e.png"

![](https://user-images.githubusercontent.com/9589803/231056569-ff20abe4-f82e-472b-9fc7-199396d30d8f.png)

### To Reproduce

Use cloudinary storage settings like so

STORAGE_LOCATIONS=cloudinary
STORAGE_CLOUDINARY_DRIVER=cloudinary
STORAGE_CLOUDINARY_ROOT=directus
STORAGE_CLOUDINARY_CLOUD_NAME=*
STORAGE_CLOUDINARY_API_KEY=*
STORAGE_CLOUDINARY_API_SECRET=*
STORAGE_CLOUDINARY_ACCESS_MODE=public

Create a folder in cloudinary called 'directus'

Try to upload an image to a collection.

### Hosting Strategy

Self-Hosted (Custom)

**Comment by aurelienbobenrieth** [comment]
Hey @kolvin it still is not working for me.

I updated to v10.0.0, and it will fail if I put everything but an empty stirng to `STORAGE_CLOUDINARY_ROOT`.

**Comment by jbool24** [comment]
This error is still an issue in v10.1.0.

The upload goes into the root of Cloudinary and not into the cloudinary "folder" listed under STORAGE_CLOUDINARY_ROOT variable. Currently testing on local as described by OP @hamishjohnson 

Also files are not able to be returned to the Admin Data Studio. All files get inside the studio (auth'd as Admin User)...
```{"errors":[{"message":"You don't have permission to access this.","extensions":{"code":"FORBIDDEN"}}]}```
