### ISSUE TITLE
`useRelationMultiple` loses updates if two happen in the same event loop cycle

### ISSUE THREAD

**Issue by hanneskuettner** [directus/directus#18150]
### Describe the Bug

The bug surfaced while trying to edit a YAML code fragment within a translations form.

When using a CodeMirror editor (either for code or Markdown text) updates disappear under certain conditions. I've attached videos of 3 instances where I could reliably reproduce the issue. It seems to be caused by an interaction of the editor update event and the `update` action of `useRelationMultiple`.

It seems like the CodeMirror editor triggers two consecutive updates within the same Vue event loop cycle when applying a format rule (or something along those lines). This causes two calls to the `update` action. Both times without `$index` and `$type` set, because the reactive `displayItems` hasn't been updated since it all happens in the same cycle.

This also happens with the markdown editor in a related collection if the first thing one does is insert a new line after a word. It causes all subsequent edits to the text to be lost.

### To Reproduce

1. Create a collection with a translations relation and a code YAML field (needs to be something that applies some reformatting or insertion rules in the editor)
2. Create a new item, and insert some valid, nested yaml, eg
```yaml
parent:
    child1: foo
    child2: bar
```
3. Save the item
4. Now edit the item, insert a new line between child1 and child2, and write some text in the new line
5. Save the item
6. See that only the new line is persisted and in the network tab you can see two entries in the update array for that entry, one containing the newline, the other one containing the newline and the new text

## Example in a code editor in translations

https://user-images.githubusercontent.com/4376726/231427595-e045af71-7dfb-4368-b7e5-66a54da991b8.mov

## Example in a markdown editor in translations (the line break is inserted right after a word)

https://user-images.githubusercontent.com/4376726/231427704-bb5d96a7-417a-4986-8b9a-cb1d6ead434c.mov

## Example of a markdown editor in a related collection drawer

https://user-images.githubusercontent.com/4376726/231427641-711f376f-5a52-4eb3-9935-defb7d6391cb.mov

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
When adding debug output to 

https://github.com/directus/directus/blob/6225523c61d5c4f41f28d5e9d2e3688955137fd7/app/src/interfaces/translations/translations.vue#L185

https://github.com/directus/directus/blob/6225523c61d5c4f41f28d5e9d2e3688955137fd7/app/src/composables/use-relation-multiple.ts#L60

and 

https://github.com/directus/directus/blob/6225523c61d5c4f41f28d5e9d2e3688955137fd7/app/src/composables/use-relation-multiple.ts#L185

I can see the following output 

<img width="1195" alt="Screenshot 2023-04-12 at 11 48 14" src="https://user-images.githubusercontent.com/4376726/231431895-ab97f062-1f25-43bf-89f8-b2600958624f.png">

Which does confirm displayItems is only recomputed after both events have been processed, causing the missing `$index` in the updated item and the duplication of update items.

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/directus/pull/18194
