### ISSUE TITLE
Cloudinary driver not working with project logo

### ISSUE THREAD

**Issue by hamishjohnson** [directus/directus#18157]
### Describe the Bug

When I try to upload a project logo in the settings, I get error

```
{
  "errors": [
    {
      "message": "Readable.fromWeb is not a function",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### To Reproduce

Using env, setup with CLI

STORAGE_LOCATIONS=cloudinary
STORAGE_CLOUDINARY_DRIVER=cloudinary
STORAGE_CLOUDINARY_ROOT=
STORAGE_CLOUDINARY_CLOUD_NAME=*
STORAGE_CLOUDINARY_API_KEY=*
STORAGE_CLOUDINARY_API_SECRET=*
STORAGE_CLOUDINARY_ACCESS_MODE=public

### Hosting Strategy

Self-Hosted (Custom)

**Comment by hamishjohnson** [comment]
This also happens when I try to use directus with other file formats like video

**Comment by rijkvanzanten** [comment]
Are you using Node 18?

**Comment by hamishjohnson** [comment]
Hi - yes that was the issue actually, I saw that in this thread https://github.com/directus/directus/discussions/14649 not an hour ago.

I will close this issue, however I now have a new issue that just seems to affect video uploads. I'll close this and open a new one
