### ISSUE TITLE
STORAGE_<LOCATION>_BUCKET is being ignored (S3 Minio)

### ISSUE THREAD

**Issue by carlos-duran** [directus/directus#18151]
### Describe the Bug

I deployed a fresh instance of Directus (Docker) + Minio (S3), everything was working fine untiI tried to upload a picture, this failed:
![image](https://user-images.githubusercontent.com/15650777/231434183-d754f167-f8d2-44aa-9a48-7f1f288b98e9.png)
The file was stored in the database but not in Minio s3.

Caprover logs:
![image](https://user-images.githubusercontent.com/15650777/231435052-becae96e-797a-418b-9429-119709cea5a2.png)

It looks like it didn't take the bucket name correctly. So I tried to append the bucket name in my STORAGE_MINIO_ENDPOINT env variable, and it worked!

### To Reproduce

These are my env variables:

```
STORAGE_LOCATIONS=minio
STORAGE_MINIO_DRIVER=s3
STORAGE_MINIO_KEY=my-key
STORAGE_MINIO_SECRET=my-secret
STORAGE_MINIO_REGION=us-east-1 # this is the minio default
STORAGE_MINIO_BUCKET=my-images
STORAGE_MINIO_ENDPOINT=http://minio.example.com:9000
```

The solution was:
```
STORAGE_MINIO_ENDPOINT=http://minio.example.com:9000/my-images
```

With this solution, Minio's side looks good. Creation and deletion are working fine.

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
I believe that's because minio relies on the "path-style" S3 requests, whereas AWS currently defaults to virtual host style. I believe setting `STORAGE_MINIO_FORCE_PATH_STYLE=true` might get you the same result 👍🏻

**Comment by carlos-duran** [comment]
> I believe that's because minio relies on the "path-style" S3 requests, whereas AWS currently defaults to virtual host style. I believe setting `STORAGE_MINIO_FORCE_PATH_STYLE=true` might get you the same result 👍🏻

OMG, it worked with that env. I didn't know about that behavior.

Thank you so much
