### ISSUE TITLE
Adding relational data over 2 many-to-many tables does not work

### ISSUE THREAD

**Issue by m-pire** [directus/directus#1815]
## Version Info
  - Directus version and branch: 6.4.2 and 6.3
  - PHP version:  7.0.19
  - MySQL version: MariaDB 10
  - Web server: Apache 2.4
  - OS name and version: Debian 9 stretch

## Expected Behavior
While creating a new row entry (e.g. "Article") it is possible to add relational data from a many-to-many defined table. **Within this adding NEW ITEM** it should be possible to add again a **NEW ITEM**.

## Actual Behavior
It is not possible to add data over **2** relational tables. 

## Steps to Reproduce
 1. Create a Table (A) and define it as relational to (B)
 2. Create a Table (C) and define it as relational to (B)
 3. Try to add a new row to (A), within this action you can add **NEW** data to (B), within this, try to add **NEW** data to (C)

## What works
Adding new data to (C) and choose it as **CHOOSE EXISTING** 

## Schema Dump, Logs, or Screenshots
1. Adding Data to "Articles" and clicking **ADD NEW ITEM** to "Reactions"
![1](https://user-images.githubusercontent.com/16267962/30427262-6ddf62ec-994f-11e7-931c-be8aeef2ce1b.png)

2. Adding **NEW** data to relational "Sources" does not work, there is **no** "NEW ITEM" button:
![2](https://user-images.githubusercontent.com/16267962/30427285-83c40e46-994f-11e7-8dd4-f86378859048.png)

3. Whilst adding directly "NEW ITEM" to Sources does work when selecting "Sources" from the tables list directly:
![3](https://user-images.githubusercontent.com/16267962/30427389-eb175aee-994f-11e7-96ba-a1102730987c.png)

What I am wrong? I checked the relations more times I can count already. Thank you Guys again.

**Comment by WellingGuzman** [comment]
Hey @m-pire can you share you the m2m column relationship? also if possible a schema we can use to replicate this issue?

**Comment by m-pire** [comment]
Hey, 
I have this screenshot for you:

![a](https://user-images.githubusercontent.com/16267962/30492430-b6060a5c-9a40-11e7-8ac8-c8c92a7fadb5.png)

And this SQL Dump: 
[directus_6_4_2.sql.zip](https://github.com/directus/directus/files/1306928/directus_6_4_2.sql.zip)

Thank you very much - this is why I want to update to 6.4.2 - problem exists in 6.3.x too.

**Comment by WellingGuzman** [comment]
The sql dump you share are missing lot of tables. got bunch of warning of missing tables, I'll try to reproduce it based on your screenshots.

**Comment by WellingGuzman** [comment]
This was already fixed by https://github.com/directus/directus/commit/57cac36106844df5264619779aa8bc5227dce21d

Soon to be included on 6.4.3

**Comment by m-pire** [comment]
Thank you very much, this is fixed!
