### ISSUE TITLE
'Hide Table' option doesn't save

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1816]
## Version Info
  - Directus version and branch: develop 4dd466d69374627ee1782892c65010f385f4038d

## Expected Behavior
Toggling the Hide Table to the on position hides the table

## Actual Behavior
The value of the option isn't saved, which means that the table isn't hidden

## Steps to Reproduce
 1. Create a new table
 2. Set the 'Hide Table' option to true

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/7031b329c8133d116385c2ef181bd3e981c508e5
