### ISSUE TITLE
Table layout with translation fields issues

### ISSUE THREAD

**Issue by alexvdvalk** [directus/directus#18163]
### Describe the Bug

When adding fields from the related translation collection into a Table layout, weird behaviour occurs with column layout.

I've tested this against 9.23.4 and 9.24

Recording below:

### To Reproduce

Create a translations field in a collection
Add a text field (eg. Title) to the translations collection
Create some demo data against 2 translations
Open the collection in the table layout
Add the Translations > Title field to the table layout
Try resize the column or add another translations field to the table layout.

https://user-images.githubusercontent.com/21194068/231735651-de544d66-e1d0-4a3e-b542-517641feb2e1.mov

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Nitwel** [comment]
This should be fixed by #17799 and will be part of the next release.
Please reopen this if this is not the case.
