### ISSUE TITLE
Two chained Many2Many Relations with strange behaviour / Bug

### ISSUE THREAD

**Issue by chrisbenjamin** [directus/directus#1817]
I have three main tables and two junction tables, that are connected with each other through Many to Many relations.

Word: M2M -> Translation
Translation: M2M -> Regions

When I'm adding a new "Word", I have the possibility to add also a "Translation", as it's related as M2M relation. Within the "Translation", I have the option to select many "Regions", as these are related as M2M relation.
When I leave the regions blank (it's the "nested" relation), directus adds one entry to "Translations" in the "Regions" table, but without any data. I can't find an entry within the database or in directus. I only can delete this empty entry from the "Translations" overview.
With this empty entry you can't use your dataset, because you receive errors (see below).

**Update**
After testing around, for me it's obviously a bug. It seems to me that in this constellation the nested relation can't be empty. Even when I go into the entry and delete the "empty" entry, I can only save, when I have chosen another "region".
This happens as well, when I post an entry via POST request and not via directus UI.

## Version Info
- Directus version and branch: build-6.4.2.20170823180744
- PHP version: 5.6.30-0+deb8u1
- MySQL version: 5.0.11-dev
- Web server: nginx/1.6.2
- OS name and version: Debian GNU/Linux 8 (jessie)

## Expected Behavior
There should not be added anything.

## Actual Behavior
An empty entry is added, which follows error messages.

## Steps to Reproduce
 1. Create three tables and add many to many junctions from table A to B and B to C
 2. Add Entry to Table A and add related item, but leave relation within this entry blank
 3. Check your data

## Schema Dump, Logs, or Screenshots

These Screenshots show the structure of my tables
<img width="1700" alt="bildschirmfoto 2017-09-15 um 08 17 10" src="https://user-images.githubusercontent.com/569479/30469154-70026b14-99ef-11e7-8a3b-337216fadace.png">
<img width="1712" alt="bildschirmfoto 2017-09-15 um 08 17 23" src="https://user-images.githubusercontent.com/569479/30469155-7006e694-99ef-11e7-8ed7-afd8e5db0306.png">
<img width="1719" alt="bildschirmfoto 2017-09-15 um 08 17 34" src="https://user-images.githubusercontent.com/569479/30469157-7008629e-99ef-11e7-9a09-6f6433b13916.png">
<img width="1716" alt="bildschirmfoto 2017-09-15 um 08 17 44" src="https://user-images.githubusercontent.com/569479/30469159-7008e084-99ef-11e7-97d0-a56709875a55.png">
<img width="1718" alt="bildschirmfoto 2017-09-15 um 08 17 54" src="https://user-images.githubusercontent.com/569479/30469156-70084c14-99ef-11e7-8699-dd37e29f55d2.png">
<img width="668" alt="bildschirmfoto 2017-09-15 um 08 18 08" src="https://user-images.githubusercontent.com/569479/30469158-7008a466-99ef-11e7-86c1-c6312a663899.png">
<img width="661" alt="bildschirmfoto 2017-09-15 um 08 18 19" src="https://user-images.githubusercontent.com/569479/30469160-701b15b0-99ef-11e7-94f6-94fc8653e871.png">

Steps how to add data for reproduce error

Add new entry to "words"
<img width="1709" alt="bildschirmfoto 2017-09-15 um 08 18 40" src="https://user-images.githubusercontent.com/569479/30469212-9530d2c2-99ef-11e7-9417-603ccff41c41.png">

Add new item "translation" within words (as it's relational)
Leave the nested relational data blank (region)
<img width="1711" alt="bildschirmfoto 2017-09-15 um 08 19 00" src="https://user-images.githubusercontent.com/569479/30469266-ac710d8a-99ef-11e7-81f6-6b7eaa3a7f4a.png">

Check entry.. you see there is a "1" in region column
<img width="1713" alt="bildschirmfoto 2017-09-15 um 08 19 39" src="https://user-images.githubusercontent.com/569479/30469292-c9865c5e-99ef-11e7-8ae7-aa50c26d5788.png">
Click on item for seeing details...
<img width="1353" alt="bildschirmfoto 2017-09-15 um 08 19 48" src="https://user-images.githubusercontent.com/569479/30469307-d7bbef14-99ef-11e7-8f53-e62b122ee5c1.png">
 
When you click on that "zombie" entry..
<img width="1713" alt="bildschirmfoto 2017-09-15 um 08 22 00" src="https://user-images.githubusercontent.com/569479/30469316-e4609904-99ef-11e7-9c6f-34f4e84658ea.png">

Now, I want to add a new region to my translation..
<img width="1712" alt="bildschirmfoto 2017-09-15 um 08 22 58" src="https://user-images.githubusercontent.com/569479/30469337-f60a2440-99ef-11e7-8c99-62fd4e08f535.png">

But I can't save (see message in corner)
<img width="1712" alt="bildschirmfoto 2017-09-15 um 08 23 11" src="https://user-images.githubusercontent.com/569479/30469341-02683358-99f0-11e7-90ab-9934412a2586.png">

**Comment by WellingGuzman** [comment]
@chrisbenjamin can you please provide an schema we can use to reproduce this issue?

Also can you give it a try to the `develop` branch, we have fixed some bugs to the translations interface.

**Comment by WellingGuzman** [comment]
This is similar to https://github.com/directus/directus/issues/1752

**Comment by chrisbenjamin** [comment]
@WellingGuzman I have updated my post and added your requested information. Please check section "Steps to reproduce" / "Update 2 (16.09.2017)".

This is really an annoying bug, because you are not able to create complex data structures. Could you please provide me your thoughts with which priority you will handle this? If you need more information, please let me know. -- Also I'll try to use the develop branch to reproduce this issue.

**Comment by WellingGuzman** [comment]
Hey @chrisbenjamin, please let us know why the develop is too buggy, what parts of the UI is not working properly, that would help us a lot.

Thanks for the updated steps, but the schema are missing the table and columns information (missing `directus_columns`)

**Comment by chrisbenjamin** [comment]
@WellingGuzman please check my updated post (Update 3). I have uploaded a new database dump - it's a complete database. just focus on the five tables X Region, X Trans Regioin, X Translation, X Word, X Word Trans.

Regarding the develop-release: You can't see any items. The complete UI, where you expect your tabled data, is empty. But there are also a lot other bugs, like the get_directus_path() function, I will report separately when this bug is fixed. Sadly I am not able to finish my project because of this problem. Thanks for your help.

**Comment by WellingGuzman** [comment]
Hey did you test it on `develop` branch, because this bug was already fixed. I'm only experiencing this before the bug as it should have.

Can you on the other hand tell us what's the issue you are experiencing on 6.4.x develop branch?

**Comment by chrisbenjamin** [comment]
Where/How can I get the fix for that, @WellingGuzman ? 

No I didn't test this on the develop branch. It's tested on an installation, based on the latest prebuild version of directus ([this file](https://github.com/directus/directus/releases/download/6.4.2/directus-build-6.4.2.20170823180744.tar.gz)) 

I will open a separate ticket for development branch bugs.

**Comment by WellingGuzman** [comment]
As I mentioned before this was fixed on `develop` branch. This and more bug-fixes will be included in 6.4.3 version release.

Please open ticket related to bugs on the develop branch.

**Comment by chrisbenjamin** [comment]
@WellingGuzman I can confirm that this bug is fixed in develop branch. Can you tell me when the version 6.4.3 will be released?
