### ISSUE TITLE
Delay in directus Tool

### ISSUE THREAD

**Issue by karthikgou** [directus/directus#18172]
### Describe the Bug

When I create a new collection in directus, it internally creates a table connected to the MYSQL database, but it is not showing up in the directus UI immediately. After a few minutes, upon page refresh, I can see my newly created collection.

I have created a docker image for directus and used a custom MYSQL database to connect to directus. MYSQL database is also hosted on another docker container.

### To Reproduce

I have created a docker image for directus and used a custom MYSQL database to connect to directus. MYSQL database is also hosted on another docker container.

Create a collection and you can see it is not reflected in the UI though the collection is created in the background

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
This is not enough information to reproduce the issue im afraid. Can you provide more information about your setup?
- are you using caching? or other configuration options that may affect performance?
- what do you mean by "I have created a docker image for directus"?
- are there enough resources for directus and the database?

Happy to re-open when more information becomes available 😄
