### ISSUE TITLE
Users with edit and view permissions in a table can make changes but can't save

### ISSUE THREAD

**Issue by idelb** [directus/directus#1818]
# Version Info
  - Directus version and branch: dev-master
  - PHP version: 7.1.9
  - MySQL version: 5.5.57
  - Web server: Apache

## Expected Behavior
Users with edit and view permissions in a table can make changes and save.

## Actual Behavior
Users with edit and view permissions in a table can make changes but can't save because the save button is disabled.

## Steps to Reproduce
 1. Create a group with read and write permissions in certain table
 2. Open a table entry and make some changes
 3. The save button il disabled

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/fa30b5ac1e5d4f28f483ec4570fcecd085929452
