### ISSUE TITLE
Display template doesn't work in calendar layout

### ISSUE THREAD

**Issue by grefrit** [directus/directus#18206]
### Describe the Bug

If you leave display template empty or add some template values you will get an error. Setting just simple string value works fine, setting string + template value doesn't work too

![image](https://user-images.githubusercontent.com/45934058/232326549-b19271e1-443b-48de-86d8-8acb6d1e1dc1.png)

### To Reproduce

Spin up Directus locally (tested with SQLite locally, but doesn't work on Postgres in production too). Add table, optionally add `start_at` and `end_at` timestamps, choose calendar layout on collection page and you will see error in console immediately

### Directus Version

9.25.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
As far as I can tell this is caused by #17799
