### ISSUE TITLE
/schema/snapshot 404

### ISSUE THREAD

**Issue by sharkfin009** [directus/directus#18205]
### Describe the Bug

This route is returning a 404

### To Reproduce

Set up admin auth and do a request to /schema/snapshot

Other routes are working for me as admin.

Am trying various other versions to try and get this working

### Directus Version

v9.24.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by xlanex6** [comment]
So I am but is from Directus Cloud instance

**Comment by sharkfin009** [comment]
yes I have seen people stuck with this in the discord server also - using Directus Cloud

**Comment by sharkfin009** [comment]
working on 25.1.0 !
