### ISSUE TITLE
Unable to insert relational data without access to 'Edit ID permission'

### ISSUE THREAD

**Issue by arladmin** [directus/directus#18214]
### Describe the Bug

Collection A - 
- id
- field1 (M2O to collection B)

Collection B -
- id
- field2 (O2M to collection A)

User's Permission:
- Full add/view/edit rights to collection B
- View & edit rights to field1 in collection A

---------------------

User makes POST request to collection B with data for field2.
Error:
```
DEBUG: You don't have permission to access this.
    err: {
      "type": "ForbiddenException",
      "message": "You don't have permission to access this.",
      "stack":
          Error: You don't have permission to access this.
              at checkFieldPermissions (/directus/node_modules/directus/dist/services/authorization.js:280:31)
              at validateFilterPermissions (/directus/node_modules/directus/dist/services/authorization.js:154:17)
              at AuthorizationService.processAST (/directus/node_modules/directus/dist/services/authorization.js:40:9)
              at FilesService.readByQuery (/directus/node_modules/directus/dist/services/items.js:272:46)
              at async /directus/node_modules/directus/dist/controllers/files.js:182:18
      "status": 403,
      "code": "FORBIDDEN",
      "extensions": {}
    }
```

---------------------

Change the user's permission for collection A to also have Edit rights to `id`.
Try the request again.
Success.

---------------------

This seems to be a severe bug in the permissions system:
A `less permission` user needs to be provided edit access to the primary field, `id`, of a collection just to create/edit an item in a connected collection!

### To Reproduce

.

### Directus Version

v9.23.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
Closed in favor of https://github.com/directus/directus/issues/21906 as there's a bit more info in that duplicate issue 🙂
