### ISSUE TITLE
Locally installed bundle isnt loaded

### ISSUE THREAD

**Issue by FirstSanny** [directus/directus#18225]
### Describe the Bug

When installing a bundle extension locally (copying the two compiled files into the `app\extensions\bundles\extension-name`, the extensions aren't getting loaded.

I have the following extensions (in ts) in my bundle: 
- 1x hook
- 1x display
- 1x endpoint

### To Reproduce

- Create a local directus env 
- create externally a bundle extension with the mentioned extension types in ts
- run the build command and copy the api.js and app.js into the extension path

### Directus Version

v9.25.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
For bundle extensions you need to deploy your extensions `package.json` too as this contains the definitions for the different extensions and the paths to the `app.js` and `api.js`. Easiest approach is to deploy the entire bundle extension to `./extensions/directus-extension-your-bundle`.

**Comment by FirstSanny** [comment]
Okay. Will give it a try. Can we then update this part, because here is where my misunderstanding is coming from:
https://docs.directus.io/extensions/creating-extensions.html#local-extension

**Comment by FirstSanny** [comment]
Btw. Thanks for the fast reply. 👍

**Comment by br41nslug** [comment]
> Okay. Will give it a try. Can we then update this part, because here is where my misunderstanding is coming from:
> https://docs.directus.io/extensions/creating-extensions.html#local-extension

Yeah have created a ticket to update the incomplete docs 👌
