### ISSUE TITLE
Broken map after latest update

### ISSUE THREAD

**Issue by com-pote** [directus/directus#18239]
### Describe the Bug

As the WYSIWYG, the map have also broken icons. Thank you for the quick fix :)

### To Reproduce

Just select the map layout on a table.

### Directus Version

V9.25.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by hanneskuettner** [comment]
This was also fixed as part of https://github.com/directus/directus/pull/18185 and is available in the next version
