### ISSUE TITLE
Bookmark_outline Default Icon missing in new Material Library

### ISSUE THREAD

**Issue by w0kyj** [directus/directus#18234]
### Describe the Bug

Presets & Bookmarks default icon "Bookmark Outline" is now just "Bookmark" and any thing using these gets a giant _OUTLINE next to the icon in Content view
![image](https://user-images.githubusercontent.com/40695629/232902811-634f3119-9d94-4e10-a94c-9835f336ee70.png)

### To Reproduce

Upgrade to 9.25.1 with any default bookmark presets

### Directus Version

v9.25.1

### Hosting Strategy

Directus Cloud

**Comment by rijkvanzanten** [comment]
This is due to a failure to run migrations. The migrations for 9.25 include the change from `bookmark_outline` to `bookmark_border` 👍🏻

**Comment by 4rt10m** [comment]
@w0kyj did you manage to fix this? Having the same issue and am unsure if there's anything on my end that needs doing. Thanks.

**Comment by w0kyj** [comment]
This is resolved by running migrations or manually updating the icons in the app or api
