### ISSUE TITLE
Cannot install via: npx directus init

### ISSUE THREAD

**Issue by donavan-tangible** [directus/directus#18237]
### Describe the Bug

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated json2csv@5.0.7: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
file:///Users/<user>/.npm/_npx/ebcc468e2b0f2b61/node_modules/@directus/api/dist/services/files.js:76
            payload.height ??= height ?? null;
                           ^^^

SyntaxError: Unexpected token '??='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:149:18)

### To Reproduce

npx directus init

### Directus Version

v9.25.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
Node 18 is required 👍🏻
