### ISSUE TITLE
Can't edit properties of M2O fields after creation

### ISSUE THREAD

**Issue by aliemba** [directus/directus#18247]
### Describe the Bug

In an created M2O field; when editing the field properties again it fails with 

`[INTERNAL_SERVER_ERROR] alter table `assembly` modify `installation` varchar(36) not null - ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'installation': used in a foreign key constraint 'assembly_installation_foreign'`

In my case I have an "assembly" collection with a M2O field with a relation the "installation" collection.

The ID is a UUID 

### To Reproduce

add a M2O field relation.
try to edit anything (ex. null behaviour ) on the properties (after creation)

10.6.12-MariaDB MariaDB Server

### Directus Version

v9.25.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by jaybharadia** [comment]
I am also facing this issue in version `9.26`

**Comment by M-GRV** [comment]
I might have the same/similiar issue:

`[INTERNAL_SERVER_ERROR] alter table `brand` modify `manufacturer` int - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'manufacturer' and referenced column 'id' in foreign key constraint 'brand_manufacturer_foreign' are i...
`
```
{
  "errors": [
    {
      "message": "alter table `brand` modify `manufacturer` int - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'manufacturer' and referenced column 'id' in foreign key constraint 'brand_manufacturer_foreign' are incompatible.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

But this happens when trying to even create a O2M from scratch for myself. v10 now.

**Comment by alexvdvalk** [comment]
I only see this occurring on mysql

**Comment by aliemba** [comment]
Agree. Moved to a postgresql and with the same schema = no error

**Comment by M-GRV** [comment]
> Agree. Moved to a postgresql and with the same schema = no error

I'm making this switch now. Just glad I caught it early. But still something that should be investigated further for our mysql family

**Comment by ra-hoch3** [comment]
Same issue with translating n:1 fields like user_created or user_updated. Tested in 9.25 with MariaDB and 10 with MySQL. 

```
{
  "errors": [
    {
      "message": "alter table `Contact` modify `user_created` varchar(36) - ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'user_created': used in a foreign key constraint 'contact_user_created_foreign'",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

**Comment by NecoHorne** [comment]
Issue is still present on V10.0.0 MySQL

```
  {
    "errors": [
      {
        "message": "alter table `comm_bulk_upload` modify `creditor` int - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'creditor' and referenced column 'id' in foreign key constraint 'comm_bulk_upload_creditor_foreign' are incompatible.",
        "extensions": {
          "code": "INTERNAL_SERVER_ERROR"
        }
      }
    ]
  }
```
