### ISSUE TITLE
Assign edit to same user created not working

### ISSUE THREAD

**Issue by afonsolopez** [directus/directus#18243]
Any way to filter just the same user that created something to let him edit it is not working.

Not working for me on 9.25.1 :(

_Originally posted by @afonsolopez in https://github.com/directus/directus/discussions/3519#discussioncomment-5655913_

**Comment by paescuj** [comment]
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻
