### ISSUE TITLE
toggle interface doesnt work

### ISSUE THREAD

**Issue by MartinMekhaiel** [directus/directus#1824]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests please use the [Directus FeatHub](http://feathub.com/directus/directus) to make a new request or vote for existing ones, or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues.

## Version Info
  - Directus version and branch: (Or commit hash)
4dd466d69374627ee1782892c65010f385f4038d
  - PHP version: 
7.0.8
  - MySQL version: 
5.5.2
  - Web server: (Ex. Apache, nginx or IIS?) 
apache
  - OS name and version: 
mac osx sierra

## Expected Behavior
state of the toggle (checkbox or switch) will be saved on change

## Actual Behavior
the state isnt saved, it always falls back to null

## Steps to Reproduce
 1. add a table with a column that has a toggle interface
 2. add an item to the table and set the toggle to checked
 3. save it and open the item again

**Comment by WellingGuzman** [comment]
Hey @MartinMekhaiel, this was fixed last night with this patch https://github.com/directus/directus/commit/7031b329c8133d116385c2ef181bd3e981c508e5
