### ISSUE TITLE
Tree Interface not correctly updating when adding Item in child

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/directus#18250]
### Describe the Bug

If I have a Tree Interface for a self referencing collection, if I add an child element and save, then it doesn't show up on the parent item until I reopen or close and open the tree where the new item should appear.

### To Reproduce

 
Item A
 - Item B
 - Item C

Item X
 - Item Y
 - Item Z

1. Open "Item A"
2. Now open "Item B" in the tree interface
3. Add a child Item ("Item D" for example)
4. Click Save  on "Item B"
5. Click Save and Stay on "Item A"

Now I would expect the tree interface to display "Item D" as child of "Item B", but this just shows up after I reopen "Item A"

### Directus Version

v9.23.4

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
Just for my understanding: The new item is already there, but hidden and the parent item currently needs to be expanded for the sub item to appear. So as I understand it, the idea is that the corresponding parent item will be expanded automatically, correct?
