### ISSUE TITLE
rating interface doesnt work

### ISSUE THREAD

**Issue by MartinMekhaiel** [directus/directus#1825]
## Version Info
  - Directus version and branch: (Or commit hash)
4dd466d69374627ee1782892c65010f385f4038d
  - PHP version: 
7.0.8
  - MySQL version: 
5.5.2
  - Web server: (Ex. Apache, nginx or IIS?) 
apache
  - OS name and version: 
macosx sierra

## Expected Behavior
saving a rating (selecting the stars) and save

## Actual Behavior
i can add the interface but the values arent stored it always falls back to 0 stars after saving

## Steps to Reproduce
 1. add a table with a column on the rating interface
 2. add a new entry and select a rating 
 3. save the entry

**Comment by WellingGuzman** [comment]
Thanks for reporting this.

Closed by https://github.com/directus/directus/commit/2d66b1f743077ae5bab0b36eb0525856631ad4d2

**Comment by MartinMekhaiel** [comment]
there still is an issue with the rating when loaded in a m2m relational (modal) window, its not possible to set the rating.

**Comment by WellingGuzman** [comment]
Thanks @MartinMekhaiel, let me try that out, I will get back to you asap

**Comment by designerzen** [comment]
This is still a problem in 2020 - directus 8 - even on the live demo page it doesn't work.

Setting rating to 10 should show an interface of 10 stars but it only ever shows 2 stars and the UI seems to be operating in reverse where clicking one star selects both.
