### ISSUE TITLE
Can not use deep in extensions with useItems

### ISSUE THREAD

**Issue by u12206050** [directus/directus#18251]
### Describe the Bug

Using `import { useItems } from '@directus/extensions-sdk';` it isn't possible to use `deep` within the query.

### To Reproduce

Use the `useItems` to fetch some data that has relationships, and add the `deep` property to the query to filter those relationships.
Notice that it has no affect.

### Directus Version

9.25.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by u12206050** [comment]
Could I create a PR for this? @rijkvanzanten

**Comment by paescuj** [comment]
> Could I create a PR for this? @rijkvanzanten

Yes! ❤️ 

(Also please do not ping team members unless there is a good reason to do so. Thanks!)
