### ISSUE TITLE
Cockroachdb -  ALTER COLUMN TYPE for a column that has a constraint is currently not supported

### ISSUE THREAD

**Issue by zs-ko** [directus/directus#18252]
### Describe the Bug

when altering an image field when using cockroachdb gives the following error

`unimplemented: ALTER COLUMN TYPE for a column that has a constraint is currently not supported`
` error: alter table "test" alter column "testimg" type uuid using ("testimg"::uuid) - unimplemented: ALTER COLUMN TYPE for a column that has a constraint is currently not supported`

### To Reproduce

1. create an image field with cockroachdb as client against a cockroach database. 

2. make a change on that field, either base folder or field conditions

### Directus Version

v9.25.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
This is a limitation of CockroachDB itself, see for example https://www.cockroachlabs.com/blog/alter-column-type/.
