### ISSUE TITLE
Column Names in Many2Many Rel picker

### ISSUE THREAD

**Issue by MartinMekhaiel** [directus/directus#1826]
## Version Info
  - Directus version and branch: (Or commit hash)
2d66b1f743077ae5bab0b36eb0525856631ad4d2
  - PHP version: 
7.0.8
  - MySQL version: 
5.5.2
  - Web server: (Ex. Apache, nginx or IIS?) 
apache
  - OS name and version: 
macosx sierra

## Expected Behavior
multiple colum names are shown in many2many table

## Actual Behavior
but only  the first one is shown

here i am adding two visible columns
![bildschirmfoto 2017-09-17 um 05 01 20](https://user-images.githubusercontent.com/7896311/30517611-8e3de6cc-9b65-11e7-83f1-bb80ab6e8b27.png)

but they dont show up:
![bildschirmfoto 2017-09-17 um 05 03 21](https://user-images.githubusercontent.com/7896311/30517614-9c7d8ca6-9b65-11e7-8969-ddd5894e1773.png)

**Comment by WellingGuzman** [comment]
@MartinMekhaiel Can you share a schema?

**Comment by MartinMekhaiel** [comment]
@WellingGuzman sent to you via slack channel

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/e71cacf76919eb9e480c13bf44ee0c41df4a0919
