### ISSUE TITLE
Add dot notation for Visible Columns in M2M / M2O relations

### ISSUE THREAD

**Issue by MartinMekhaiel** [directus/directus#1827]
## Version Info
  - Directus version and branch: (Or commit hash)
2d66b1f743077ae5bab0b36eb0525856631ad4d2
  - PHP version: 
7.0.8
  - MySQL version: 
5.5.2
  - Web server: (Ex. Apache, nginx or IIS?) 
apache
  - OS name and version: 
macosx Sierra

## Expected Behavior
Showing specific properties of a related table with dot notation eg.
airport_departure.name

## Actual Behavior
when adding the visible columns in a m2m relationship there is no way to access the properties within the related column, to show them in the m2m table, always the id gets shown

## Steps to Reproduce
 1. add a m2m relationship
 2. set the visible column to a specific property of the related table
 3. see the error, as we can only access properties within the main table right now.

![bildschirmfoto 2017-09-17 um 22 27 23](https://user-images.githubusercontent.com/7896311/30524668-6e12c3ac-9bf8-11e7-9a36-69acf37236ab.png)

**Comment by benhaynes** [comment]
I believe @WellingGuzman is working on this now (unless it's dot.notation for a different component). We'll update here soon...

**Comment by rijkvanzanten** [comment]
For reference: the columns `airline`, `airport_departure`, `airport_arrival`, `stopovers` are relational themselves as well

**Comment by rijkvanzanten** [comment]
We've moved this over to the [Directus feature request tool](https://request.getdirectus.com) as this is a feature request and not an actual issue with the current implementation.

https://request.getdirectus.com/r/134
