### ISSUE TITLE
Fix the icon failure for wswiswyg

### ISSUE THREAD

**Issue by yottoo** [directus/directus#18280]
### Describe the Bug

![image](https://user-images.githubusercontent.com/36605252/233526495-db19de26-ae6d-401f-9cf2-e398691e90e5.png)

### To Reproduce

just select all the function items for the wysiswyg control.

### Directus Version

9.25.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
Inter -apple etc is the name of the font that's in use, so that's correct. The "Visual aid" is to toggle visual aid, im not sure that's supposed to be an icon 🤔
