### ISSUE TITLE
Can't read message, click event not recognized

### ISSUE THREAD

**Issue by idelb** [directus/directus#1829]
## Version Info
  - Directus version and branch: master
  - PHP version: 7.1.9
  - MySQL version: 5.5.57
  - Web server: Apache

## Expected Behavior
Click on message preview, show the message detail.

## Actual Behavior
Click on message preview, nothing happens.

## Steps to Reproduce
 1. Create a message and send it
 2. Go to the messages list
 3. Try to click in one of the messages preview

**Comment by rijkvanzanten** [comment]
Closed by #1831
