### ISSUE TITLE
Can't open message clicking on the preview modal

### ISSUE THREAD

**Issue by idelb** [directus/directus#1830]
## Version Info
  - Directus version and branch: master
  - PHP version: 7.1.9
  - MySQL version: 5.5.57
  - Web server: Apache

## Expected Behavior
Click on them message preview modal, go to message detail

## Actual Behavior
Click on them message preview modal, error message

## Steps to Reproduce
 1. Receive a message
 2. Wait for the preview modal
 3. Click on it

**Comment by rijkvanzanten** [comment]
Closed by #1831
