### ISSUE TITLE
Generate thumbnail files repeatedly when using MinIO

### ISSUE THREAD

**Issue by kuerme** [directus/directus#18301]
### Describe the Bug

Using MinIO as the file store, and jpg or png images as the `Project Logo` or `Public Background`, the thumbnail is generated repeatedly each time the `Project Settings` or `File Library` page is refreshed

![screenshot-20230423-171410](https://user-images.githubusercontent.com/2811986/233830814-a25f31c1-4162-466b-9b76-ddff3c071622.png)

### To Reproduce

1. upload a png or jpg image to `Project Logo` or `Public Backgounrd`;
2. refesh `Project Settings` or `File Library` page;
3. go to MinIO Console, and you will see the image generated repeatedly;

### Directus Version

v9.25.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by aclisp** [comment]
I have the same problem, while I am using the `local` storage.

**Comment by leosin** [comment]
still happend in version 10.1.0
When refreshing the file library page, A large number of local pictures are copied
