### ISSUE TITLE
npx directus init fails on IPv6 only

### ISSUE THREAD

**Issue by lahdekorpi** [directus/directus#18313]
### Describe the Bug

Init fails silently if you are on a IPv6 only network.

Maybe it should warn in that case or maybe the documentation should have a mention of this.

### To Reproduce

```bash
npx directus init
```

### Directus Version

9.26.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
Does it time out? I'm wondering if it's `npm` that isn't able to download the dependencies, as Directus itself doesn't really connect to the network for anything during init

**Comment by paescuj** [comment]
I'm going to close this issue for now but happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻
