### ISSUE TITLE
Flow display bug for raw editor

### ISSUE THREAD

**Issue by avimar** [directus/directus#18315]
### Describe the Bug

When I open a flow with a field that was filled in with the raw editor, it shows it empty.

So far I've noticed this for the flow for notifications and email.

![image](https://user-images.githubusercontent.com/314077/234286813-b9b9104b-dfd7-42b9-ac1b-b1434c6f905f.png)

If I click the {} to see the raw editor then it shows up:
![image](https://user-images.githubusercontent.com/314077/234286880-f89b1769-0857-4e72-a3e0-a16842c06904.png)

I had thought this bug affected what's being saved, but I haven't seen that when testing. So it may just be an aesthetic issue, which surprises you.

### To Reproduce

Create a new flow
click edit
add a new type: notification
click {} on user, type in {{$trigger.user_created}}, and then click save and save.

Upon editing and editing the notification page, it will be empty & clicking the {} will show null.

Maybe I should be hitting "enter" -- in which case you have to put in {{$trigger.user_created}} without quotes and press enter.
Then switching to raw {} shows it as an array entry.

### Directus Version

v9.25.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by kropsi** [comment]
The same bug with Edit and Create Data operations. This means that it is not possible to choose which fields to create/update dynamically. You have to update all the fields each time, even though you don't wish to overwrite already field information. This is very limiting as you have to create cases for all update scenarios instead of having one flow and passing a data object to it with selected fields.

**Comment by kropsi** [comment]
Yes it also influences "Triggers -> Another Flow" as it is not possible to pass an array into the flow as described here

<img width="734" alt="image" src="https://github.com/directus/directus/assets/946662/f83e6df2-d4f1-43e5-bbbd-a1ec5e120279">

The information can be entered but it is removed on save

<img width="837" alt="image" src="https://github.com/directus/directus/assets/946662/0144d03b-8888-4897-b931-171cca8c0e5c">

**Comment by kropsi** [comment]
@rijkvanzanten just to tell that this one has quite some impact on Flows, as you can't pass any objects or arrays into any of the operations that use code (json) interface. It also means that it is not possible to iterate though the arrays using Trigger flow.

**Comment by rijkvanzanten** [comment]
I believe this is resolved as part of https://github.com/directus/directus/pull/19126

**Comment by Pachat** [comment]
@rijkvanzanten  It remains is IDs  #19474
