### ISSUE TITLE
Sort function in n:n relations is broken

### ISSUE THREAD

**Issue by skuhnow** [directus/directus#18311]
### Describe the Bug

I have 2 collections, one called 'slides' and one called 'blocks', they are connected with an n:n relation so that I can use every block in one or more slides. I have only one slide with 10+ blocks, status of the blocks is published, some drafts and one deleted. I can sort them (I have the handle) but every time when I try to move them, they "jump back" to the previous order after I release the handle

### To Reproduce

* Create two collections (i.E. post and comment)
* Connect them with n:n named "comments"
* Add a numeric field "sort" to the n:n table
* Set the sort field in the "comments" field of the "post" collection
* create a post and 2-3 comments
* add the comments to the post
* try to change the order of the post

**You can move the item to another position, but as soon as you release the mouse, the items jumps back to the initial position**

### Directus Version

v9.24.0 (it worked in v9.23.1)

### Hosting Strategy

Self-Hosted (Custom)

**Comment by hanneskuettner** [comment]
This is a bug affecting versions v9.24.0 - v9.25.1. It has been fixed in the newest release. #18096
