### ISSUE TITLE
password reset url 

### ISSUE THREAD

**Issue by in2uitions** [directus/directus#18314]
### Describe the Bug

I am trying to reset password, and Im always getting the error that the "Url \" can't be used to reset passwords." Although, I configured the reset allow link in the .env file in the backend. I have this working on another project and its not working here, so maybe its something with directus version to note that I have 9.21.0 

### To Reproduce

Nothing special

### Directus Version

9.21.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
"Nothing special" is not enough information to reproduce the issue. Please provide the required information to reproduce the issue on a new instance.
