### ISSUE TITLE
Bookmarks are randomly duplicated

### ISSUE THREAD

**Issue by grefrit** [directus/directus#18318]
### Describe the Bug

https://user-images.githubusercontent.com/45934058/234304458-0d3a5ba1-7f4f-45e3-b45c-d866257a6f8b.mov

My customers bookmark is duplicated (original bookmark is global, duplicated is personal). Tested on Admin account, but similar situation can happen even on App access minimum permissions

### To Reproduce

Try to create (tested on Global bookmark) and switch between collections multiple times. It can be tricky, but eventually Directus will duplicate it (it isn't a visual bug, it will be duplicated in database)

### Directus Version

v9.25.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
\linear

**Comment by paescuj** [comment]
I haven't been able to reproduce this whatsoever on the latest version ([v10.1.1](https://github.com/directus/directus/releases/tag/v10.1.1)), so I'll close this for now. Could you try to reproduce it again on this version and provide as much information as possible, if that should be the case?
Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻
Thanks!

**Comment by aaronransley** [comment]
Can confirm, I can recreate this on 10.3.0.

**Comment by rijkvanzanten** [comment]
> Can confirm, I can recreate this on 10.3.0.

What steps did you take to run into the issue?

**Comment by br41nslug** [comment]
I have been able to reproduce this using the provided steps since it was triaged.

https://github.com/directus/directus/assets/9389634/63746779-84c3-4725-b827-bc51082ad5dc

**Comment by bryantgillespie** [comment]
I've seen this behavior recently on 10.6.1

https://www.loom.com/share/e802c637424f4752baaeff7ccabe0cd4?sid=06896534-1978-408e-a860-cc231a683bb5

**Comment by abaturovskyi** [comment]
Same here, I reproduced it with @bryantgillespie steps
