### ISSUE TITLE
Error Microsoft Azure log in

### ISSUE THREAD

**Issue by DavidBlanchGit** [directus/directus#18324]
### Describe the Bug

When I log in in directus it give me this error: AADSTS90102: 'redirect_uri' value must be a valid absolute URI.

### To Reproduce

I have created two applications registered in Azure following the tutorial of the url https://intility.github.io/fastapi-azure-auth/single-tenant/azure_setup/ in order to use the login in fast api and directus, I have the following environment variables http://localhost:8055/auth/login/microsoft/callback

```env
AUTH_PROVIDERS="microsoft"
AUTH_MICROSOFT_DRIVER="openid"
AUTH_MICROSOFT_ICON="business"
AUTH_MICROSOFT_CLIENT_ID="XXXX"
AUTH_MICROSOFT_CLIENT_SECRET="XXXX"
AUTH_MICROSOFT_ISSUER_URL="https://login.microsoftonline.com/XXXX/v2.0/.well-known/openid-configuration"
AUTH_MICROSOFT_SCOPE="openid user.read mail.read"
AUTH_MICROSOFT_IDENTIFIER_KEY="email"
AUTH_MICROSOFT_REQUIRE_VERIFIED_EMAIL="false"
AUTH_MICROSOFT_ALLOW_PUBLIC_REGISTRATION="true"
AUTH_MICROSOFT_DEFAULT_ROLE_ID="XXXX"
```

As redirection url I have added http://localhost:8055/auth/login/microsoft/callback

### Directus Version

v9.23.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by azrikahar** [comment]
Have you configured the `PUBLIC_URL` env variable? Judging from your redirection URL, it will likely need to be `PUBLIC_URL="http://localhost:8055"`.

**Comment by DavidBlanchGit** [comment]
Thank you very much, it seems that this was the error that was giving me so many problems.
