### ISSUE TITLE
Database conection errors in Docker Container on Plesk server.

### ISSUE THREAD

**Issue by cesarkmelo** [directus/directus#18323]
### Describe the Bug

Hi, I have installed a new docker container with the latest version of directus on my plesk server, everything works perfectly with sqlite but when I want to move to MariaDB for data persistence I get the following response:

`node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: getaddrinfo EAI_AGAIN database
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
    --------------------
    at Protocol._enqueue (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:116:18)
    at /directus/node_modules/.pnpm/knex@2.4.2_gtxrszusl6tkjfynyc22baqi3i/node_modules/knex/lib/dialects/mysql/index.js:66:18
    at new Promise (<anonymous>)
    at Client_MySQL.acquireRawConnection (/directus/node_modules/.pnpm/knex@2.4.2_gtxrszusl6tkjfynyc22baqi3i/node_modules/knex/lib/dialects/mysql/index.js:61:12)
    at create (/directus/node_modules/.pnpm/knex@2.4.2_gtxrszusl6tkjfynyc22baqi3i/node_modules/knex/lib/client.js:254:39) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'database',
  fatal: true
}

Node.js v18.15.0`

This is the env configuration for my container.

![Firefox_Screenshot_2023-04-25T21-53-26 518Z](https://user-images.githubusercontent.com/6840815/234412742-78014af3-dd91-49ff-94bb-c768ed99579c.png)

I haven't found any MySql or MariaDB valid example for the setup in the official documentation of directus, and I dont know what to do next.

Is there any way to tell the container to use my local MariaDB for the DB?

Could you help me?

### To Reproduce

**Plesk:** 
Plesk Obsidian
Version 18.0.51 Update #1, last updated on April 6, 2023 06:28 AM

**Server:**
Ubuntu 22.04.2 LTS

**DB:**
MariaDB 10.6.12

**Directus Docker Image:**
directus/directus:latest    Created on April 25, 2023.

Steps:

- Dowload Docker Image.
- Create container with the below env variables.
- Start container
- getting error.

DB_CLIENT=mysql
DB_HOST=database
DB_PORT=3306
DB_DATABASE=directus
DB_USER=directus
DB_PASSWORD=directus
CACHE_ENABLED=true
CACHE_STORE=redis
CACHE_REDIS=redis://cache:6379
ADMIN_EMAIL=test@alfamediaweb.com
ADMIN_PASSWORD=d1r3ctu5
PUBLIC_URL=https://testurl.com

I have also tried with a different database already created and tested on my local server with this env variables

DB_CLIENT=mysql
DB_HOST=database
DB_PORT=3306
DB_DATABASE=directus_db
DB_USER=directus_user
DB_PASSWORD=directus_password
CACHE_ENABLED=true
CACHE_STORE=redis
CACHE_REDIS=redis://cache:6379
ADMIN_EMAIL=test@alfamediaweb.com
ADMIN_PASSWORD=d1r3ctu5
PUBLIC_URL=https://testurl.com

Gettin exactly the same error.

### Directus Version

v9.x.x

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
You might want to double-check the `DB_` variables as it seems like the database instance cannot be reached.
For further assistance on self-hosted setups, please follow the guidelines under [Community Support](https://docs.directus.io/getting-started/support.html#community-support).

**Comment by cesarkmelo** [comment]
Hi, DB_ variables are triple-checked and the error persist, any other idea?

**Comment by rijkvanzanten** [comment]
EAI_AGAIN is a DNS lookup timeout. This means there's most likely a network connectivity problem in how these containers network. Hard to say exactly, as this is a environment / plesk / server specific issue..
