### ISSUE TITLE
Malformed POST / PATCH request when saving an item causes "[FORBIDDEN] You don't have permission to access this."

### ISSUE THREAD

**Issue by heyarne** [directus/directus#18337]
### Describe the Bug

When manipulating related items in the overlay interface it's possible that Directus treats items as updated which have not yet been created. Saving the parent item then sends a `PATCH` request, which fails with `[FORBIDDEN] You don't have permission to access this."`.

### To Reproduce

1. Create a collection (collection a) with  a one-to-many relationship; the nested collection (the to-many-side, collection b) needs to have some field that you can change
2. Open the "Content" tab in the directus admin interface and create a new parent collection
3. From within the parent collection, select "Create New" and create a child item. Change the attribute somehow in the overlay that appears and close it by clicking the checkmark button in the top right
4. Open the overlay again, change the value, close it by clicking the checkmark button in the top right
5. Save collection a
6. A popup with the error should appear.

The `POST` (or `PATCH` body, if the parent collection already existed) looks like this:

``` json{
{
  "collection_b": {
    "create": [
      {
        "attribute": "Whatever you entered in the first overlay"
      }
    ],
    "update": [
      {
        "attribute": "Whatever you entered in the second overlay"
      }
    ],
    "delete": []
  }
}
```

The `update` should have been merged locally before sending it to the server.

### Directus Version

v9.20.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
I have not been able to reproduce this issue on v10 please update and verify this is still happening for you 😄
