### ISSUE TITLE
Ui error

### ISSUE THREAD

**Issue by MartinMekhaiel** [directus/directus#1833]
## Version Info
  - Directus version and branch: (Or commit hash)
3f4e7898e90d9eabf5c0c664ae516324e5c4b7ac
  - PHP version: 
7.0.8
  - MySQL version: 
5.5.2
  - Web server: (Ex. Apache, nginx or IIS?) 
apache
  - OS name and version: 
macosx sierra

## Expected Behavior
loading a table list view 

## Actual Behavior
an error gets shown (seems to be related with related columns in list view, but not sure)

![bildschirmfoto 2017-09-20 um 14 01 51](https://user-images.githubusercontent.com/7896311/30642823-a965231c-9e0c-11e7-951d-564786a730c3.png)

![bildschirmfoto 2017-09-20 um 14 01 56](https://user-images.githubusercontent.com/7896311/30642828-abcaa88e-9e0c-11e7-9432-4099faf6065f.png)

**Comment by dsivokhin** [comment]
Hello, this error after commit 1e9c4ac0a1dc9f60bda3f9e5e92e1e2c8690ef7e for #1828. 
In comments I writed same problem. You can rollback temporarily.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/66c40c6cb61337383c6f1ac5e21b6df85148f2ff
