### ISSUE TITLE
Ploblem with single_file component in related field M2M

### ISSUE THREAD

**Issue by dsivokhin** [directus/directus#1834]
## Version Info
  - Directus version and branch: develop
  - PHP version: 7.0
  - MySQL version: 5.7
  - Web server: nginx
  - OS name and version: Ubuntu 16.04

## Actual Behavior
When open item with related M2M(with single_file column) 
![default](https://user-images.githubusercontent.com/4669992/30686831-180951b6-9ec2-11e7-9a73-917d701ccf86.png)

error 
![default](https://user-images.githubusercontent.com/4669992/30686631-893cd462-9ec1-11e7-8f59-dd650b09fe5c.png)
![default](https://user-images.githubusercontent.com/4669992/30686669-a3098264-9ec1-11e7-9f23-226c7eaa50b6.png)

because `var model` is not object - is numeric `file id`

## Schema Dump, Logs, or Screenshots

![default](https://user-images.githubusercontent.com/4669992/30686937-67df58c0-9ec2-11e7-8316-684b8eb47376.png)
![default](https://user-images.githubusercontent.com/4669992/30686951-7410938e-9ec2-11e7-9009-9fbc6f7362b1.png)

[test.zip](https://github.com/directus/directus/files/1320514/test.zip)

**Comment by WellingGuzman** [comment]
The issue reported here was actually fixed by 67c9ea2.

It was left open due to the same issue reported here: https://github.com/directus/directus/issues/2080

I will close this ticket and continue the conversation over the same issue in a more detailed specific issue report.
