### ISSUE TITLE
DefineHook of extensions is called twice during server startup

### ISSUE THREAD

**Issue by ernst86913** [directus/directus#18348]
### Describe the Bug

I am using a definehook / server.start action hook for initialization scripts / config handling and just figured out in my logs that it seems that those definehooks are called twice during server startup

My hook definition:

export default defineHook(async ({ action }, { database, services, emitter, logger, env, getSchema }) => {..................

1. It seems that definehooks are called directly at the beginning... 

2. It seems that definehooks are called again after  the following:

2023-04-27 21:29:20 [19:29:20.465] INFO: Database already initialized, skipping install
2023-04-27 21:29:20 [19:29:20.465] INFO: Running migrations...
2023-04-27 21:29:20 [19:29:20.477] INFO: Done

... I would understand if there were any migrations that are running... but I am definitely at the latest status with all migrations... 

While this is not really a "blocking issue" fixing this might improve server startup time and potentially resource utilization.

PS - I am pretty sure that this behaviour already exists for quite a long time.

### To Reproduce

Write an extension using 

export default defineHook(async ({ action }, { database, services, emitter, logger, env, getSchema }) => {..................

and put a logger statement directly afterwards (not into the action hook itself).

### Directus Version

v10

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
I am unfortunately not able to reproduce this. I've created the following hook:
```js
import { defineHook } from '@directus/extensions-sdk';

export default defineHook(async ({ action }, { database, services, emitter, logger, env, getSchema }) => {
    console.log('test123');
    action('server.start', () => console.log('server.start'));
});
```
And this only logs once as expected:
![image](https://user-images.githubusercontent.com/9389634/236438098-17faa01e-0643-44c6-b50b-7bbf76496f85.png)

**Comment by br41nslug** [comment]
Aaaah but  it does happen in the docker image because both the `node /directus/cli.js bootstrap` and `node /directus/cli.js start` commands load the extensions 🤔

**Comment by ernst86913** [comment]
Great that you were able to reproduce.

LG,
Roman

Von meinem iPhone gesendet

On 05.05.2023, at 12:50, Brainslug ***@***.***> wrote:

﻿

Aaaah but it does happen in the docker image because both the node /directus/cli.js bootstrap and node /directus/cli.js start commands load the extensions 🤔

**Comment by ernst86913** [comment]
@ classification - fine for me - but shouldn’t the issue stay open instead of being closed?
