### ISSUE TITLE
Search input is reset to earlier queries when response arrives

### ISSUE THREAD

**Issue by heyarne** [directus/directus#18340]
### Describe the Bug

When using the search input field in the admin collection interface, the search query is reset as soon as a response comes in. When typing fast, this leads to very confusing behavior, where parts of a word can end up missing.

I could imagine two ways to improve this:

1) Debounce search requests, so that they start only after a small pause interval
2) Do not reset the search input when a response arrives, and somehow find a different way to keep the displayed search result in sync with what the user most recently typed in

### To Reproduce

1. Pick a collection with many entries (search queries should take some hundreds of milliseconds for easy reproduction)
2. Start typing a very long word

You should notice that some letters will get lost as responses arrive, and continued typing will add letters to those cut off words.

### Directus Version

v9.20.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by azrikahar** [comment]
Can you try `v9.21.0` (ideally the latest version `v10` of course)? #13157 was fixed by #16473 in `9.20.4`, which is later than your current reported version. We do also recommend verifying any bug using the latest version just so we can be sure it isn't resolved yet 👍

**Comment by heyarne** [comment]
Thanks for pointing out that a current version may have fixed that. Updates aren't trivial for us, but I'll gladly give it a shot and provide feedback!

**Comment by rijkvanzanten** [comment]
I'll close this for now as we believe this has already been fixed in a more recent version 🙂  We can reopen if that's not the case. Ty!
