### ISSUE TITLE
mongodb support

### ISSUE THREAD

**Issue by Reedyuk** [directus/directus#1835]
Hi,
I heard mongodb support is currently in development, is there a branch that i could pull to get access to this?

Thanks

**Comment by benhaynes** [comment]
It is in the very early R&D stages still, but we're hoping to have proper support in 4-6 months. Closing this as it's not an issue – if you'd like to expedite, you can submit PRs or garner support on our FeatHub:

https://feathub.com/directus/directus/+68

**Comment by danielalmeidagoncalves** [comment]
Sorry for reviving this topic, but do we have news on this? Is there planes to support mongo or was dropped by some reason?

**Comment by benhaynes** [comment]
We never supported Mongo, so it wasn't "dropped".

https://docs.directus.io/getting-started/support/#does-directus-support-mongo-nosql

[**Unfortunately, we can not provide estimates on features or fixes**](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍 . Or contribute a pull-request... after all, this is OSS!
