### ISSUE TITLE
npm install directus --save does not install v10

### ISSUE THREAD

**Issue by Pachat** [directus/directus#18354]
### Describe the Bug

`npx directus start` says `Update available: 9.26.0 -> 10.0.0`
but `npm install directus --save` does not install v10 and keeps on 9.26

### To Reproduce

Run
`npm install directus --save`

### Directus Version

v9.26 => v10

### Hosting Strategy

Self-Hosted (Custom)

**Comment by DavidBlanchGit** [comment]
Try with `pnpm install directus --save`

**Comment by paescuj** [comment]
If you want to update, you have to specify the version explicitly:
`npm install directus@10.0.0`
