### ISSUE TITLE
in slug inputs, hyphen gets removed if case of `-s` and `-t`

### ISSUE THREAD

**Issue by sharkfin009** [directus/directus#18352]
### Describe the Bug

While creating transformation presets, form validation is not allowing names like "project-thumbnail". Super minor obviously , but leaving it here for the record

### To Reproduce

In the admin UI under settings, create a naming as above

### Directus Version

9.25.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by azrikahar** [comment]
This should be affecting slug inputs in general, and it is a "side effect" of the latest release of the slugify package (https://github.com/sindresorhus/slugify/releases) where `-s` and `-t` (the intended fix was for `'s` and `'t` that are slugified) are sort of a false positive for our slugify use case. Transformation presets key just so happens to be one of input with slug enabled:

https://github.com/directus/directus/blob/3ff71cc34aafadd78028a1440c22a9fc89ec8332/api/src/database/system-data/fields/settings.yaml#L183

**Comment by leosin** [comment]
![image](https://github.com/directus/directus/assets/3676670/4e5b1b3b-c6d6-4ce0-a707-47fc34e227cd)

did you mean this Raw Value ?
I don't quite understand

**Comment by br41nslug** [comment]
@leosin 
This "raw value" when entering your value in the interface.
![image](https://github.com/directus/directus/assets/9389634/79476b80-46ee-4449-a448-24e26a9be1de)

**Comment by leosin** [comment]
> @leosin This "raw value" when entering your value in the interface. !

Thanks a lot, I've got the hang of it!
