### ISSUE TITLE
Unmasked password is sent in payload of Event Hook, in Flow

### ISSUE THREAD

**Issue by arladmin** [directus/directus#18353]
### Describe the Bug

I have a Flow set up triggered by an `Event Hook` : `items.create` (`action`), on `directus_users`.

Surprisingly, the payload of this flow contains the unmasked password of the user!
That shouldn't have been possible, right?

### To Reproduce

^

### Directus Version

v10.0.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Initially I was going to go with this is intentional as there may be use-cases for having access to this data in Custom Extensions. But you're very right this plain text password should never be stored in the Flow Logs.

**Comment by arladmin** [comment]
This issue is still existent.

In Directus v10.8.3, in Flow logs as well as actual execution data, only the log for the 'Trigger' step shows the password as `--redacted--`. Other than that, 
- the password is still visible everywhere in the logs
- it is passed on to all the subsequent steps within the flow!
