### ISSUE TITLE
The interface "Collection Item Dropdown" does't have correct display features

### ISSUE THREAD

**Issue by aliemba** [directus/directus#18369]
### Describe the Bug

The interface "Collection Item Dropdown" is missing the ability to select fields in the "Display" section. You can select "Formatted JSON value" that will not give related field values

But it should give the ability to select fields from the "related" collection.

![billede](https://user-images.githubusercontent.com/44196248/235340299-d256cb46-c141-4bc1-9cff-515b223dbba5.png)

### To Reproduce

Add a "Collection Item Dropdown" to a collection.
Edit the field
See the "Display" section for missing options

### Directus Version

v10.0.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
The "Collection Item Dropdown" is not a database relation at this time so these display's are correct.

**Comment by aliemba** [comment]
But i looks up in another collection? 

Then remove the word "relation" in my post.

It still needs to show something else than the JSON raw value when displayed.

**Comment by laportem** [comment]
So how do we display a field from the selected dropdown collection? The json has only a key and the collection name

**Comment by aliemba** [comment]
My point exactly.

You can't show this field in a view or alike. It will show the json and not give the option in a treeview.
