### ISSUE TITLE
Can't edit/hide Relational Fields in Table layout

### ISSUE THREAD

**Issue by arladmin** [directus/directus#18364]
### Describe the Bug

Once a relational field has been added to the Table layout, it can't be edited or hidden.
The options to edit/hide are visible, but acting on them makes no change.

### To Reproduce

.

### Directus Version

v9.23.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
I believe this was fixed as part of https://github.com/directus/directus/pull/18267. I can't reproduce this anymore on the latest state of `main`. We'll reopen if the problem persists after the next release 👍🏻
