### ISSUE TITLE
docs: Broken Links

### ISSUE THREAD

**Issue by mundry** [directus/directus#18375]
### Page

https://docs.directus.io/app/settings.html

### Describe the Inaccuracy

Hi,

currently there are 104 unique broken internal links to 35 unique pages in the docs. 
When opening those links directly in the browser they get redirected correctly, However, when opening the link within the docs a 404 page is shown (like with "Project Settings" on the Settings page, for example). Upon reloading that page, the redirect takes effect and results in the correct page.

![Screenshot from 2023-05-01 12-39-31](https://user-images.githubusercontent.com/1453314/235442995-829d7f8b-c2bd-4258-8dbf-59e951fa9c13.png)

If you'd like, I'd be happy to submit a PR to fix those links.

**Comment by rijkvanzanten** [comment]
> If you'd like, I'd be happy to submit a PR to fix those links.

Yes please! ❤️

**Comment by that1matt** [comment]
I actually just found this issue as well, and created a PR, and saw this issue.
