### ISSUE TITLE
ID gets overwritten using Create New on Builder field

### ISSUE THREAD

**Issue by adamkhan** [directus/directus#18371]
### Describe the Bug

I have a Builder (M2A) field with the option to Create New. When doing so, the ID field is editable, which lets me overwrite/destroy existing entries in my related collection.

### To Reproduce

Set up an instance with a collection, a builder field and another collection that it relates to.

### Directus Version

v9.26.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
Unless you have the ID set to "manually entered string" this is intentional and gets overwritten by the auto-generation of the ID when creating an item.
