### ISSUE TITLE
Incorrect schema difference being detected

### ISSUE THREAD

**Issue by claytongulick** [directus/directus#18379]
### Describe the Bug

In 9.26, when modifying metadata on a field Directus is detecting a schema change when none has occurred - for example, adding a value to a dropdown list.

The issue is caused by line 402 in fields.ts: 

    if (!isEqual(sanitizeColumn(existingColumn), hookAdjustedField.schema)) {

sanitizeColumn has a picklist that excludes these fields:
 - comment
 - foreign_key_schema
 - schema

hookAdjustedField.schema contains these fields, while sanitizeColumn(existingColumn) does not, which causes Directus to erroneously detect a schema change when none has happened.

To fix the issue, either both fields need to be wrapped by sanitizeColumn() or neither:

    if (!isEqual(sanitizeColumn(existingColumn), sanitizeColumn(hookAdjustedField.schema as Column)))

Unfortunately not able to create a PR for the fix for this due to BSL, but wanted to share the issue and fix to (hopefully) save the Directus team some time. 

### To Reproduce

Modify any field in Directus, metadata only. Directus will issue an ALTER TABLE command even though nothing has changed.

This impacts any customer that may have a view bound to the database table, the ALTER TABLE command will fail due to the bound view.

### Directus Version

v9.26

### Hosting Strategy

Self-Hosted (Custom)

**Comment by miagg** [comment]
I have the same problem on v9.26 (didn't try 10.0).
1. I cannot change anything on a primary key field (readonly, description, etc.)
2. It somehow messes with postgres sequences by deleting the default value on primary keys.
