### ISSUE TITLE
flow design ui doesn't update after editing the flow

### ISSUE THREAD

**Issue by kamalseisy** [directus/directus#18381]
### Describe the Bug

after editing flow design by add/edit/delete  operations and save the changes the view mode will show the flow without the edits however the changes are saved to the db. by refreshing the page you can see the changes 

### To Reproduce

1. open any flow
2. click edit flow
3. add new operation (the new operation will show in edit mode)
4. click save (this will switch to view mode and the new operation is not show, after refreshing the page you can see the new operation)

### Directus Version

9.24.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
I think this was fixed in 9.25 by https://github.com/directus/directus/pull/17819 can you verify this issue is resolved after updating?
