### ISSUE TITLE
Filter on Many to Many and Many to One Tables throws SQL Error

### ISSUE THREAD

**Issue by meezaan** [directus/directus#1838]
## Version Info
  - Directus version and branch: 8dae0a3  (master on September 26, 2017)
  - PHP version: 5.6.31
  - MySQL version: Percona 5.6.23
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: CentOS release 6.7 (Final)

## Expected Behavior
I've got a table with several many to many and many to one connections. When I try and filter on a many to many field, I get a SQL error. Rather than looking in the join table, it is looks in the table for . a field that doesn't exist in it. Even on a many to one field, it tries to do a subquery but SQL is not correct - it tries to look for a field called 0 - so table_name.0. 

## Actual Behavior
It should filter on the selected field

## Steps to Reproduce
 1. Use attached schema - it has the directus_tables, directus_columns and all the actual created tables in it.

## Schema Dump, Logs, or Screenshots

[books.sql.zip](https://github.com/directus/directus/files/1333803/books.sql.zip)

**Comment by WellingGuzman** [comment]
Hey @meezaan,

Thanks for reporting this, the M2M issue has been reported (#1810) and the M2O issue has been fixed already.

If you provide a proper steps by steps to reproduce one of these if it hasn't been fixed for you in master branch (6.4.3) I will re-open.

**Comment by meezaan** [comment]
@WellingGuzman Excellent stuff - thank you. I can confirm that M2O now works like a charm. I'd be happy to help, time permitting. I haven't really dug deep, but is the SQL generated by https://github.com/directus/directus-database?

Thank you.

**Comment by WellingGuzman** [comment]
Glad to hear.

If you are interested in helping Filters are created here: https://github.com/directus/directus/blob/master/api/core/Directus/Database/TableGateway/RelationalTableGateway.php#L949

https://github.com/directus/directus-database is a read only repo created from https://github.com/directus/directus/blob/master/api/core/Directus/Database

**Comment by adamjgrant** [comment]
@WellingGuzman Is M2M filtering documented anywhere? I only see this line in the API docs:

"[API Reference | Directus Docs](https://docs.directus.io/api/reference.html#filtering)"

> There's two filter has and all that only works on O2M-type fields, any other type of fields used will throw an error saying the field cannot be found.

So what do you use for M2M?

**Comment by benhaynes** [comment]
@adamjgrant — is this what you're looking for?

https://docs.directus.io/api/reference.html#filter-relational

**Comment by adamjgrant** [comment]
I don’t think so, should this syntax support m2m?

**Comment by benhaynes** [comment]
Maybe related to this ticket?
https://github.com/directus/api/issues/784
