### ISSUE TITLE
Restricted Access if fields checked in 'Column Read Blacklist'

### ISSUE THREAD

**Issue by dsivokhin** [directus/directus#1839]
## Version Info
  - Directus version and branch: master
  - PHP version: 7.0
  - MySQL version: 5.7
  - Web server: nginx
  - OS name and version: Ubuntu 16.04

## Expected Behavior
User not see fields, if their checked in `Column Read Blacklist`
User can edit self profile

## Actual Behavior
After update to 6.4.23, users in group with not empty `Column Read Blacklist` see error
![1](https://user-images.githubusercontent.com/4669992/30910744-b2b22654-a38e-11e7-802c-b746ae463d01.PNG)

And User can't edit self profile 
![default](https://user-images.githubusercontent.com/4669992/30911135-159edd92-a390-11e7-9af3-e3ad2b94e657.png)

![2](https://user-images.githubusercontent.com/4669992/30910764-c3024408-a38e-11e7-86c4-adb57de31bb3.PNG)

Before update, was no error

## Steps to Reproduce
 1. Get my sql dump
 2. login: test@test.com pass: test
 3. open table 'Products'

## Schema Dump, Logs, or Screenshots
[test.zip](https://github.com/directus/directus/files/1336873/test.zip)

**Comment by WellingGuzman** [comment]
Thanks @dsivokhin for reporting.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/d3fff534f2716d211ff2e4c06df0c52de9ff1e20
