### ISSUE TITLE
Not work 'Save as copy'

### ISSUE THREAD

**Issue by dsivokhin** [directus/directus#1840]
## Version Info
  - Directus version and branch: master
  - PHP version: 7.0
  - MySQL version: 5.7
  - Web server: nginx
  - OS name and version: Ubuntu16.04

## Actual Behavior
When I try push 'Save as copy' nothing happens
![default](https://user-images.githubusercontent.com/4669992/30911553-c44f907e-a391-11e7-9c50-41e9097e3e45.png)

## Schema Dump, Logs, or Screenshots
[test.zip](https://github.com/directus/directus/files/1336921/test.zip)

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/9a863f9035739770912bf5eb4a5804711ceacb24

**Comment by dsivokhin** [comment]
Hello @WellingGuzman , is it possible to copy M2M and other relations  ?
