### ISSUE TITLE
"Nothing to see here..." message missing from empty table list

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1841]
## Version Info
  - Directus version and branch: develop latest

## Expected Behavior
New installations should show some sort of hint on what to do next.

## Actual Behavior
It shows an empty list interface.

## Steps to Reproduce
1. Create a new Directus instance

## Schema Dump, Logs, or Screenshots

<img width="1359" alt="screen shot 2017-09-27 at 11 43 40 am" src="https://user-images.githubusercontent.com/9141017/30923308-85cbfed6-a379-11e7-9c3b-ddb3b82cef6b.png">

**Comment by WellingGuzman** [comment]
@rijkvanzanten Ben was talking to me that about adding a tour, this would solve that problem.

To me this is a feature request.

**Comment by benhaynes** [comment]
The tour is a Feature Request... but this page should show the "Nothing to see here" message because it's empty (just like all other pages). So I'd call this a bug.

**Comment by WellingGuzman** [comment]
That's true. but the report is about this:

> New installations should show some sort of hint on what to do next.

I was based on that.

Showing nothing on tables that's a missing option, and adding a "NEW" table button at the top. what do you all think?

**Comment by benhaynes** [comment]
True!

I agree, we should add the "Nothing to see here" on this page... we can add the "New" button too, but only for admins.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/60c0210e68d3a81c9f19178e4862d603e33f39bd
