### ISSUE TITLE
Style system-user interface

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1842]
## Version Info
  - Directus version and branch: Develop latest

## Expected Behavior
Including a user interface shows the user

## Actual Behavior
It does show the user, but in a rather ugly fashion

## Steps to Reproduce
 1. Add a user interface

## Schema Dump, Logs, or Screenshots
<img width="325" alt="screen shot 2017-09-28 at 11 25 20 am" src="https://user-images.githubusercontent.com/9141017/30975225-ba5ef1d2-a43f-11e7-82ce-9de5d27b06c3.png">

**Comment by WellingGuzman** [comment]
Here is the template for this view:

https://github.com/directus/directus/blob/d3df3475c76b3eadc78c0956b8765d40b27a0dd3/app/core/interfaces/user/interface.handlebars#L1-L8

A easy way to style this is adding the style in the same `.handlebars` file, and updating the markup as much as it needed to display the user information and avatar.

The most important information that can be found in a user object may be the one below:

```
└─ user
   ├─ id
   ├─ status
   ├─ first_name
   ├─ last_name
   ├─ email
   └─ group
````

You can take a look at the [user migration file](https://github.com/directus/directus/blob/d3df3475c76b3eadc78c0956b8765d40b27a0dd3/api/migrations/schema/20150204042725_CreateDirectusUsersTable.php) to see what are other columns.
