### ISSUE TITLE
Installation troubles on Flynn(heroku)

### ISSUE THREAD

**Issue by martinrisseeuw** [directus/directus#1844]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests please use the [Directus Request Tool](https://request.getdirectus.com/) to make a new request or vote for existing ones, or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues.

## Version Info
  - Directus version and branch: (Or commit hash) Master
  - PHP version: php (7.1.9)
  - MySQL version: 10.1.22-MariaDB
  - Web server: (Ex. Apache, nginx or IIS?) apache (2.4.20)
  - OS name and version: N/A

## Expected Behavior
I'm trying to deploy Directus with flynn (similar to heroku) the deploy and seems to work well as it opens up the installation menu after:
![image](https://user-images.githubusercontent.com/8780559/30985717-c17b430a-a456-11e7-8e5d-ddc4977c1b05.png)

In the dropdown for the DB I only have one option but it seems to work:
![image](https://user-images.githubusercontent.com/8780559/30985765-e9560d74-a456-11e7-8c03-ec45a0ed5f1a.png)

During the confirm step, I get two issues: 
- mod_rewrite is not enabled 
- Media directory is not writeable

I tried to add the Rewritebase to the api htaccess and the root htaccess but this doesn't change anything. I tried to run the install anyway and get this error:

```
Uncaught TypeError: Argument 1 passed to {closure}() must be an instance of Exception, instance of Error given in /app/installation/bootstrap.php:17 Stack trace: #0 [internal function]: {closure}(Object(Error)) #1 /app/api/core/Directus/Hook/Emitter.php(266): call_user_func_array(Object(Closure), Array) #2 /app/api/core/Directus/Hook/Emitter.php(107): Directus\Hook\Emitter->executeListeners(Array, Array, 0) #3 /app/api/core/Directus/Exception/ExceptionHandler.php(73): Directus\Hook\Emitter->run('application.err...', Object(Error)) #4 [internal function]: Directus\Exception\ExceptionHandler->handleException(Object(Error)) #5 {main} thrown
```

**Comment by WellingGuzman** [comment]
Hey @martinrisseeuw, I've added a fix for that error, but that error was trying to throw another error, and because php 7 sends internal error as `\Error` instead of PHP 5`\Exception`.

Please try to install again, and share the actual error it was getting.

**Comment by WellingGuzman** [comment]
I'm closing this 16 days without any replying. Assuming the issue was identified and solved, otherwise it will re-open.
