### ISSUE TITLE
value.isnew() is not a function

### ISSUE THREAD

**Issue by MartinMekhaiel** [directus/directus#1845]
## Version Info
  - Directus version and branch: (Or commit hash)
43a33c87b8dda009dc932f825abab934219fdb44
  - PHP version: 
7.0.8
  - MySQL version: 
5.5.2
  - Web server: (Ex. Apache, nginx or IIS?) 
apache
  - OS name and version: 
macosxsierra

## Actual Behavior
the following error gets shown when loading an item page, i dont really know why exactly. it seems to be an issue with the column name setting 

## Schema Dump, Logs, or Screenshots
![bildschirmfoto 2017-09-28 um 22 53 40](https://user-images.githubusercontent.com/7896311/30990219-bac5c900-a4a0-11e7-88ea-e09df579ac13.png)

**Comment by rijkvanzanten** [comment]
For reference, this issue is on 
`app/core/interfaces/many_to_one_typeahead/component.js` line 78

https://github.com/directus/directus/blob/598fa1a06ebcc5ecbb5c94ef9ac85e03f550e140/app/core/interfaces/many_to_one_typeahead/component.js#L78-L80

**Comment by WellingGuzman** [comment]
Hey @MartinMekhaiel can you please provide any database dump?

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/0826c4970d22d1c4e2a84e4ba5816b384c10b630
