### ISSUE TITLE
Batch Edit – Cancel Button Spacing

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1846]
Add space to the left, or wrap to a new line.

**Comment by WellingGuzman** [comment]
To clarify what needs to be done here:

Steps:

1. Go to any table listing page
2. Select multiple entries
3. Click Batch Edit on header
4. Click on any interface input to start editing a value

This will enable the input for editing, but next to the field name there's a "Cancel" button, that's too close (See Screenshot below).

<img width="463" alt="screen shot 2017-10-02 at 12 36 34 am" src="https://user-images.githubusercontent.com/1531291/31064420-fc2d655e-a709-11e7-9210-7bf1d4f17081.png">

We want to create a spacing between the field label and the button.

The template that contain this piece is located in `app/templates/interface-container.handlebars`. 

https://github.com/directus/directus/blob/d3df3475c76b3eadc78c0956b8765d40b27a0dd3/app/templates/interface-container.handlebars#L9-L11

**Comment by lex111** [comment]
Created PR #1850.

**Comment by rijkvanzanten** [comment]
Closed by #1850. Thanks @lex111!
