### ISSUE TITLE
Directus_files item permissions Rule - Filter not working as expect w/  folder name does not contain,

### ISSUE THREAD

**Issue by mcqua007** [directus/directus#18475]
### Describe the Bug

I am trying to create a private folder for contact form attachments. Obviously I don't want them accessible to the public, but since my site is a CMS/page builder, I  also want all other images/files not in a private folder to be readable by the public role as they are used on the public facing site.

So I went into public permission and to `directus_files` read permissions and changed to custom. I added a filter to only give read access to files not in a Private folder. For example,  I want to make all files that don't  have a folder that contains the substring 'Private'.  That way I can add Private to any folder name and it will not be readable by the public role.

First I tried this:
<img width="857" alt="Screenshot 2023-05-03 at 4 11 40 PM" src="https://user-images.githubusercontent.com/17321059/236119943-7e3e923c-b963-4bb4-a58e-aae246af18b5.png">
 I saved it and book all the images (not in a private folder) lost read access, breaking the front end of the website.
 
 Then I tried using the folder id like so (hg) is just a placeholder for a UUID:
 
<img width="800" alt="Screenshot 2023-05-01 at 5 56 58 PM" src="https://user-images.githubusercontent.com/17321059/236120167-78110bee-c104-4287-bbe1-13c5a66e8614.png">

Same results no files were readable in the public role.

I posted a convoluted issue before and got some feedback and tried that as shown below, with same results:
<img width="854" alt="Screenshot 2023-05-01 at 5 52 40 PM" src="https://user-images.githubusercontent.com/17321059/236120401-30629e0e-b8d4-430a-a22c-b980fc21f27b.png">
<img width="855" alt="Screenshot 2023-05-01 at 5 53 35 PM" src="https://user-images.githubusercontent.com/17321059/236120412-f257aee3-6584-4962-904c-e0b72f778136.png">

If I make a folder called public and then do the following, only the files in that folder are readable by the public role. How come the opposite (doesn't contain Private) does not work. All of they above should evaluate to true.

<img width="859" alt="Screenshot 2023-05-03 at 10 42 11 PM" src="https://user-images.githubusercontent.com/17321059/236120766-90bd13be-d9a1-4863-bdc9-cca45a6dfe5f.png">

Either there is a bug or  I  missing  something because it's not intuitive.

All your help is greatly appreciate, I ned to secure these files haha.

### To Reproduce

Add some images to all files in your file manager. Create a folder called `Private` and put a few different files in there.
Go to roles & permissions and edit _public roles_, go down to **diectus_files** and create a item filter as shown above and below.
<img width="857" alt="Screenshot 2023-05-03 at 4 11 40 PM" src="https://user-images.githubusercontent.com/17321059/236121447-760940b8-3fe0-45f4-97d6-533d3da6a1d9.png">

Now in a public env try fetch a list of files. You should get an empty array.

Expected to get a return list of all files not in the Private folder.

### Directus Version

v9.25.3

### Hosting Strategy

Directus Cloud

**Comment by mcqua007** [comment]
But this case does't catch folders that are also public

**Comment by br41nslug** [comment]
> But this case does't catch folders that are also public

how do you mean folders that are public? If you mark folders public with permissions that has no impact on accessing files

**Comment by mcqua007** [comment]
See above:
<img width="626" alt="Screenshot 2023-05-04 at 10 04 57 AM" src="https://user-images.githubusercontent.com/17321059/236275509-614948d0-395f-4a59-b57e-8953faf8065c.png">

**Comment by mcqua007** [comment]
To get around this I found this late last night after the issue was posted:
<img width="790" alt="Screenshot 2023-05-04 at 10 11 23 AM" src="https://user-images.githubusercontent.com/17321059/236276965-d6f71645-0a97-4cd7-a19d-a08c631f8242.png">
This feels kind of icky and not intuitive.

**Comment by br41nslug** [comment]
> See above, say I want the private & contact form attachment folders files to no be readable by the public role. But all other folder and files should be readable by public role. The Icons, Blog Images Folders files will not have folder: null

Unless im not understanding you this is what my permissions does:
Files are publicly accessible if they're **not** in the private folder (which has ID `16edb60a-979d-4b30-88a0-93986d7d3c27` in my example) or if they are not in a folder (aka `folder: null`)

**Comment by mcqua007** [comment]
> > See above, say I want the private & contact form attachment folders files to no be readable by the public role. But all other folder and files should be readable by public role. The Icons, Blog Images Folders files will not have folder: null
> 
> Unless im not understanding you this is what my permissions does: Files are publicly accessible if they're **not** in the private folder (which has ID `16edb60a-979d-4b30-88a0-93986d7d3c27` in my example) or if they are not in a folder (aka `folder: null`)

Yep, I understand that. The goal is I have clients using this stuff. I don't want them to create a folder or something and block files meant to be public.

**Comment by mcqua007** [comment]
I feel your original single line rule, should work instead of the complex one I posted above. One would think the UUID !== null & !== SOME_OTHER_UUID_UNSPECIFIED_IN_THE_RULE
<img width="574" alt="Screenshot 2023-05-04 at 10 16 47 AM" src="https://user-images.githubusercontent.com/17321059/236278457-62736079-d112-4d43-bdfe-eaa88188c7df.png">

**Comment by mcqua007** [comment]
For example with the Folder isn't null I get this response from the public read role. All folder:null, and the ones with folder uuid are the public folder in the screen shot below.
``` json
         {
            "title": "CTA Bg Mobile",
            "folder": null
        },
        {
            "title": "Careers Banner Mobile",
            "folder": null
        },
        {
            "title": "Random Public Icon ",
            "folder": "242b2636-9ca0-4f40-9766-d8e806529e6b"
        },
          {
            "title": "Public Blog Hero Image ",
            "folder": "54c9ba0d-1e4c-41bc-ab55-d478e51608d8"
        },
```
<img width="626" alt="Screenshot 2023-05-04 at 10 04 57 AM" src="https://user-images.githubusercontent.com/17321059/236275509-614948d0-395f-4a59-b57e-8953faf8065c.png">
