### ISSUE TITLE
Filter operator _icontains is missing

### ISSUE THREAD

**Issue by DanielBiegler** [directus/directus#18471]
### Page

https://docs.directus.io/reference/filter-rules.html#filter-operators

### Describe the Inaccuracy

I remembered that there was a case insensitive operator but couldnt remember if it was `_ieq` or or something like that, so looked up the docs but theres no mention of this. Then tried `_icontains` out because I found #15760 - which works exactly like expected.

Tested on `Directus v10.0.0`

Thought I'd let you know :v:

**Comment by paescuj** [comment]
Thank you very much for opening this issue! I'm going to close this in favor of #18496 where additionally `_ieq` and `_nieq` will be tracked.
