### ISSUE TITLE
Batch Edit - Stepping out of the page error

### ISSUE THREAD

**Issue by WellingGuzman** [directus/directus#1848]
## Version Info
  - Directus version and branch: 6.4.3
  - PHP version: 5.6.30
  - MySQL version: 5.6.35
  - Web server: Apache
  - OS name and version: MacOS 10.12.5

## Expected Behavior

No error, step out of the page easily

## Actual Behavior

When trying to step of the page an error message: `topViewInfo` is undefined appears.

## Steps to Reproduce
 1. Go to any table with M2M
 2. Select two or more items
 3. Click Batch Edit on top of the page
 4. Add couple of M2M items, then step out

## Schema Dump, Logs, or Screenshots

_Note_: I will be adding more info later.

**Comment by rijkvanzanten** [comment]
At the moment, all core developers are working fulltime on the next major version of the platform, so I'll have to leave this open as a help-wanted. If anyone is inclined to take a swing at fixing this, a PR is very welcome 😄

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/8)
