### ISSUE TITLE
Azure Open ID Invalid Token

### ISSUE THREAD

**Issue by DavidBlanchGit** [directus/directus#18495]
### Describe the Bug

Microsoft provider authentication still does not work after pull request https://github.com/directus/directus/pull/18310

I have compiled the source code since version 10.0.0.0 does not include the pull request and it does not work either.

### To Reproduce

```env
AUTH_PROVIDERS="microsoft"
AUTH_MICROSOFT_DRIVER="openid"
AUTH_MICROSOFT_ICON="business"
AUTH_MICROSOFT_CLIENT_ID="XXXX"
AUTH_MICROSOFT_CLIENT_SECRET="XXXX"
AUTH_MICROSOFT_ISSUER_URL="https://login.microsoftonline.com/XXXX/v2.0/.well-known/openid-configuration"
AUTH_MICROSOFT_SCOPE="openid user.read mail.read"
AUTH_MICROSOFT_IDENTIFIER_KEY="email"
AUTH_MICROSOFT_REQUIRE_VERIFIED_EMAIL="false"
AUTH_MICROSOFT_ALLOW_PUBLIC_REGISTRATION="true"
AUTH_MICROSOFT_DEFAULT_ROLE_ID="XXXX"
```

```python
import requests
import json

url = "https://login.microsoftonline.com/xxxx/oauth2/token"

client_id = "xxxx"
client_secret = "xxxx"

data = {
    "grant_type": "client_credentials",
    "client_id": client_id,
    "client_secret": client_secret,
    "resource": "https://graph.microsoft.com"
}

response = requests.post(url, data=data)

access_token = response.json()["access_token"]
print(access_token)

api_url = "http://localhost:8055/items/example"

headers = {
    "Authorization": f"Bearer {access_token}",
    "Content-Type": "application/json"
}

response = requests.get(api_url, headers=headers)

print(response.json())
```

`{'errors': [{'message': 'Invalid user credentials.', 'extensions': {'code': 'INVALID_CREDENTIALS'}}]}`

### Directus Version

v10.0.0 & current commit

### Hosting Strategy

Self-Hosted (Custom)

**Comment by aidenfoxx** [comment]
Are you trying to use the access token provided by Azure to fetch content from Directus? Unfortunately, that is not a supported workflow. You need a Directus access token to query Directus endpoints.

**Comment by DavidBlanchGit** [comment]
And how can i get a directus token when my provider is Microsoft?

**Comment by aidenfoxx** [comment]
You need to authenticate using OpenID via Directus. There is some information on this here: https://docs.directus.io/self-hosted/sso.html#seamless-sso

This cannot be done programmatically. If you want to call Directus from a backend service, you could create a service user in Directus, and authenticate using that, via the default login endpoint.

**Comment by DavidBlanchGit** [comment]
okey, thank you very much for the info and docs
