### ISSUE TITLE
Some fields show '--' in bookmarked list

### ISSUE THREAD

**Issue by BArtistically** [directus/directus#18499]
### Describe the Bug

When you add a filter on a collection and create a bookmark from it. You then go to Bookmarks and change the reach to all users. If you go back to the bookmark, the values of some fields show '--' instead of the value in the list.
I don't know why some are shown and some not. It's in the same column that some show '--' and others show the value.

### To Reproduce

Go to a collection. 
Add a filter.
Create a bookmark.
Got to bookmarks and select the bookmark you just created.
Change the reach to all users.
Go back to bookmark and some fields show  '--' instead of the value in the list.

### Directus Version

v9.25.2

### Hosting Strategy

Directus Cloud

**Comment by paescuj** [comment]
Hey, thanks for opening the issue! Could you share what type of fields and / or displays are affected?

**Comment by rijkvanzanten** [comment]
Heya! There isn't enough information available to keep investigating this issue at present time, so it'll be closed until more information becomes available. Thanks!
