### ISSUE TITLE
A fatal CASCADE

### ISSUE THREAD

**Issue by Pachat** [directus/directus#18508]
### Describe the Bug

If you want to truncate the directus_files table, for example when going from dev to prod, be aware that this will truncate all your development: you will end up with no directus_fields and even more, no directus_users (even yourself gone).

I don't know how this can be solved because deleting a user's files when deleting the user makes sense.
But should users be deleted when their files are deleted?

Not sure if this happens because of related fields added to some directus collections or simply in the original database design.

### To Reproduce

Run TRUNCATE TABLE public."directus_files" CASCADE; on the database.

Consequences: it will
TRUNCATE cascade on the table « directus_settings »
TRUNCATE cascade on the table « **directus_fields** »
TRUNCATE cascade on the table « directus_folders »
TRUNCATE cascade on the table « directus_permissions »
TRUNCATE cascade on the table « directus_presets »
TRUNCATE cascade on the table « **directus_roles** »
TRUNCATE cascade on the table « directus_shares »
TRUNCATE cascade on the table « **directus_users** »
TRUNCATE cascade on the table « directus_dashboards »
TRUNCATE cascade on the table « directus_flows »
TRUNCATE cascade on the table « directus_notifications »
TRUNCATE cascade on the table « directus_operations »
TRUNCATE cascade on the table « directus_panels »
TRUNCATE cascade on the table « directus_sessions »

### Directus Version

v10.0.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
This is not something that is currently envisaged, so I'll proceed to close this issue.
I rather think this will be something that will be automatically solved by an implementation of a feature like https://github.com/directus/directus/discussions/5107.

**Comment by rijkvanzanten** [comment]
This makes sense, as there's foreign key constraints between those tables. Using a CASCADE on truncate in a raw SQL query therefore makes every connected table truncate as well 👍🏻

**Comment by merlindru** [comment]
IMO users should be soft-deleted by default, with a "permanently delete" button warning about this exact thing

**Comment by rijkvanzanten** [comment]
> IMO users should be soft-deleted by default, with a "permanently delete" button warning about this exact thing

I don't think that's related to the original post. That describes what happens when you run a manual SQL query with an explicit CASCADE. Has nothing to do with deleting a user from Directus itself 👍🏻

**Comment by merlindru** [comment]
Oh, sorry. Got it! Thanks
