### ISSUE TITLE
2FA not enforced in Directus API

### ISSUE THREAD

**Issue by mosabalrsaheed** [directus/directus#18506]
### Describe the Bug

Identified a potential security issue related to 2-factor authentication (2FA) in the Directus API. Currently, 2FA is not enforced in the Directus API, which means that users are not required to use 2FA when accessing the API. This could potentially allow unauthorized access to sensitive data if a user's credentials are compromised.

### To Reproduce

Steps to produce:

1- Log in to Directus.
2-Enable 2FA in a role or user.
3-Don't login through directus admin, use API.
4- If the call to tfa/generate is not made, attempt to access the API login without using an otp.
5- try to call all available api end points and it should work.

Expected behaviour
All api endpoints (a middleware ?) should check if the user have successfully used and otp in his login. potentially checking the tf_secret field if it's null or not.

Note that the API can be accessed without 2FA, potentially allowing unauthorized access to sensitive data.

### Directus Version

v10.0.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
> 2-Enable 2FA in a role or user.

Which of the 2 do you mean here? When enabling 2fa for a specific user then an OTP will be needed to get your access token.
However if you set the "Require 2FA" then each user in that role will need to enable/configure 2fa on the first next login. So until 2fa is actually activated for that user it will not be required.

I followed the reproduction steps and unfortunately cannot reproduce this for users where 2fa is enabled. Happy to re-open the ticket if more information becomes available.
