### ISSUE TITLE
Change three-way toggle to dropdown in data model settings

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#18518]
### Discussed in https://github.com/directus/directus/discussions/17682

<div type='discussions-op-text'>

<sup>Originally posted by **Dominic-Marcelino** March  2, 2023</sup>
### Summary

By default all folders and collections are opened in the sidebar.
For folders we can set that they should start either:
- Start open
- Start collapsed
- Always stay open

This setting can be changed by clicking on the folder-Icon what I think is not really intuitive (just discovered it right now after two years with directus - not sure if this always existed 😅)
![Bildschirm­foto 2023-03-02 um 14 55 58](https://user-images.githubusercontent.com/46492597/222449164-f7569221-e7e4-4335-8428-8a642733abc5.png)

I'd suggest the following changes:
- Using a dropdown to select the behaviour
- More distinct icons (as you can see in the screenshot above the icons are nearly identical)
- Add the setting to the edit-folder modal (as it's called "Edit folder" I'd expect that it shows me all options)

And as a new feature:
Right now this behaviour can't be set for bookmarks. Would be great if they could be collapsed by default, too

### Motivation

Increase the UI / UX for the App, make the settings more intuitive.

### Detailed Design

see above

### Must Have:
- More distinctive icons
- Dropdown to select the behavious

### Should Have:
- Move it into the settings modal

### Could Have:
- Setting for Bookmarks to start collapsed too

### Drawbacks

/

### Alternatives

/

### Adoption Strategy

/

### Unresolved Questions

_No response_</div>

**Comment by hanneskuettner** [comment]
Looks like this has been addressed by #18547
