### ISSUE TITLE
File library aligns center

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1851]
## Version Info
  - Directus version and branch: develop latest (https://github.com/directus/directus/commit/a5bcc69c9343413c7f6c0c4cd028c08d8938b1d2)

The file library centers the items horizontally, whereas the user library (which uses the same visual style) aligns the items to the left (see screenshots below). For visual consistency, these should behave the same.

 
_User directory_
![screen shot 2017-10-02 at 12 16 10 pm](https://user-images.githubusercontent.com/9141017/31087739-2cc51c86-a76c-11e7-9e52-780c31c91e69.png)

_File directory_
![screen shot 2017-10-02 at 12 16 07 pm](https://user-images.githubusercontent.com/9141017/31087740-2ccce5ba-a76c-11e7-8876-e54a99466e2f.png)

**Comment by W01fw00d** [comment]
Hi! I would like to help with this :)

**Comment by rijkvanzanten** [comment]
Awesome @W01fw00d! Highly appreciated 😄 

To get you started:
- The user listing styles are in [assets/sass/_users.scss](https://github.com/directus/directus/blob/master/assets/sass/_users.scss)
- the file listing styles in [assets/sass/_files.scss](https://github.com/directus/directus/blob/master/assets/sass/_files.scss).

Ideally, these share the same styles for the general layout of the page

The markup is a little more spread out.., and is possibly harder to alter:
- The cards themselves of files/users are in [app/templates/modules/files/card-view.handlebars](https://github.com/directus/directus/tree/master/app/templates/modules/files/card-view.handlebars) and [app/templates/modules/users/card-view.handlebars](https://github.com/directus/directus/tree/master/app/templates/modules/users/card-view.handlebars) respectively
- The files-cards Backbone model / collection and main view is in: [app/modules/files/](https://github.com/directus/directus/tree/master/app/modules/files/), users' one is [app/modules/users/](https://github.com/directus/directus/tree/master/app/modules/users/)

Please let us know if you need any info or help! For quicker messaging, you are very welcome to join us over on Slack: https://slack.getdirectus.com

**Comment by W01fw00d** [comment]
Just to make sure; we want both galleries to center elements to the left right? Just like the user gallery behaves currently.

**Comment by rijkvanzanten** [comment]
The `Tiles` items view uses the same off wrapping as files used to..
![screen shot 2017-10-11 at 1 49 38 pm](https://user-images.githubusercontent.com/9141017/31457573-256d223c-ae8b-11e7-98f7-5ee77a39b6ec.png)

We should give all these views the same styling

**Comment by W01fw00d** [comment]
Oh, I didn't know those ones were off too, I can fix it. Tiles is a common view for all Tables right?

**Comment by WellingGuzman** [comment]
@W01fw00d it's not a common view, but it does shares the same CSS.

**Comment by W01fw00d** [comment]
PR opened, this issue shall be fixed just removing flex.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/78ddba78bc5d1928973a3dde1cd30724bf00bca9
