### ISSUE TITLE
Custom Formats won't display in WYSIWYG editor

### ISSUE THREAD

**Issue by Arecsu** [directus/directus#18519]
### Describe the Bug

Hello! I'm trying to apply the template custom format to a WYSIWYG field: 

```json
[
    {
        "title": "My Custom Format",
        "inline": "span",
        "classes": "custom-wrapper",
        "styles": {
            "color": "#00ff00",
            "font-size": "20px"
        },
        "attributes": {
            "title": "My Custom Wrapper"
        }
    }
]
```
But the toolbar item to select a custom format – which as far as I know, appears as a button showing "Paragraph" as the default option – doesn't appear. Also I can't find the item in the toolbar options to enable it.

![image](https://user-images.githubusercontent.com/12679098/236881624-3676fd7e-1958-4903-bd62-7477097e3693.png)

Here is the raw value of the toolbar

```
[
	"undo",
	"redo",
	"bold",
	"italic",
	"underline",
	"strikethrough",
	"h1",
	"h2",
	"h3",
	"h4",
	"outdent",
	"numlist",
	"bullist",
	"blockquote",
	"customLink",
	"customImage",
	"customMedia",
	"hr",
	"code",
	"fullscreen"
]
```

I added `formatselect` to the previous list manually, which seems to be the one I need according to TinyMCE docs. Still won't show up.

I tried to make a new WYSIWYG field with the default options, only applying the template custom format and the issue persist. What may be causing it?

### To Reproduce

1. Create a WYSIWYG field
2. Go to its options, Interface, fill Custom Formats with the code above or with the Fill with Template Value that appears on hover
3. Save it
4. Go to the WYSIWYG editor in your content data
5. `Paragraph` button should be visible in the toolbar. It's not.

By reference, I watched this official Directus video that does this, but I don't get the button to appear. https://www.youtube.com/watch?v=1eErahCf6WQ

### Directus Version

v9.25.2

### Hosting Strategy

Directus Cloud

**Comment by br41nslug** [comment]
I am unable to reproduce this on v10.1 by adding custom formats to wysiwyg interface (using the default settings).
![image](https://github.com/directus/directus/assets/9389634/1b648682-c921-4ea5-a914-7c5896ad847a)
![image](https://github.com/directus/directus/assets/9389634/b8ddae8f-3a37-4cd3-87d1-3b34dece5758)

Can it be a specific selection of toolbar items or other settings creating this situation?

**Comment by Arecsu** [comment]
Probably it was fixed along the latest versions of Directus. I'm running v9.25.2 because is the one Directus Cloud uses. I'll contact support to see if they can update to the latest version and will report back. 

Also tried to disable almost everything on the toolbar or inspect the elements (maybe it was hidden), but is not even in the DOM.

**Comment by damienmontastier** [comment]
Anyone have a solution ? It's a bit problematic not to be able to change the content of WYWIWYG on the Cloud versions of Directus.
