### ISSUE TITLE
Add way to collapse collection folders in data-model view

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#18517]
When you have a large amount of collections in your schema, the data model view can become very unwieldy. By adding a way to collapse those folders in the view, this can be alleviated a bit. See https://github.com/directus/directus/discussions/9939#discussioncomment-5833036 for a proposed solution.

## Must Haves

- Allow folders to be collapsed with a toggle button

## Should Have

- Sync collapsed state in localStorage 

## Could Have

n/a

## Won't Have

- Collapsing for folders on the folder view

**Comment by that1matt** [comment]
@rijkvanzanten I am happy to continue to improve my mvp code on this as stated in #9939. I can try and find a way to add some sort of visibility indicator on collapsable items, unless your UX team might have a suggestion I can work on implementing.

**Comment by rijkvanzanten** [comment]
@that1matt On second thought, no other collapsable _thing_ right now has an indicator of the amount of nested items, so I think that for a first MVP having the ability to collapse them is sufficient 🙂

**Comment by that1matt** [comment]
@rijkvanzanten do you want me to disconnect the collapse from the folder settings, and move it to localStorage?
