### ISSUE TITLE
List Relations (in Collection/by Name) only returns a "O2M" relationship.

### ISSUE THREAD

**Issue by that1matt** [directus/directus#18510]
### Page

https://docs.directus.io/reference/system/relations.html#list-relations-in-collection

### Describe the Inaccuracy

Currently if you create a collection that contains all types of collections using the Field Interface builder, you only get the physical relationship for a O2M. There should be a note in the documentation about using the `/relations` API to get a list of all relationships.

The assumption being that I would get all relationships regardless of alias type when using Relations in Collection, or Relations by Name.

**Comment by jaads** [comment]
Thanks for the feedback! 🙌 

> ..., you only get the physical relationship for a O2M

by this you mean when fetching items via e.g. the `/items/<collection>` endpoint of the API, right?

There was a small tip already on the `item` object [here](https://docs.directus.io/reference/items.html#the-item-object) but I added one more sentence, see https://github.com/directus/directus/pull/19381.

I hope that makes it clearer from the beginning.
