### ISSUE TITLE
Hook extensions fails if it depends on sharp

### ISSUE THREAD

**Issue by WoLfulus** [directus/directus#18548]
### Describe the Bug

I'm having some issues with hook extension that uses sharp as a dependency. If I add sharp as a dependency, rollup tries to install it and it fails for whatever reason. If I leave it out, probably because pnpm isn't hoisting the dependency, I end up with MODULE_NOT_FOUND even though Directus already depends on it.

I'm not sure why this happens, and my initial thoughts were wrong - I think it's something to do with how rollup is trying to process that module.

```

Something went wrong installing the "sharp" module

The specified procedure could not be found.
\\?\E:\directus\node_modules\.pnpm\sharp@0.32.1\node_modules\sharp\build\Release\sharp-win32-x64.node

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current win32-x64 runtime: "npm install --platform=win32 --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
- Ensure the version of sharp aligns with the .pnpm package: "npm ls sharp"
    err: {
      "type": "Error",
      "message": "\nSomething went wrong installing the \"sharp\" module\n\nThe specified procedure could not be found.\r\n\\\\?\\E:\\\directus\\node_modules\\.pnpm\\sharp@0.32.1\\node_modules\\sharp\\build\\Release\\sharp-win32-x64.node\n\nPossible solutions:\n- Install with verbose logging and look for errors: \"npm install --ignore-scripts=false --foreground-scripts --verbose sharp\"\n- Install for the current win32-x64 runtime: \"npm install --platform=win32 --arch=x64 sharp\"\n- Consult the installation documentation: https://sharp.pixelplumbing.com/install\n- Ensure the version of sharp aligns with the .pnpm package: \"npm ls sharp\"",
      "stack":
          Error:
          Something went wrong installing the "sharp" module

          The specified procedure could not be found.
          \\?\E:\directus\node_modules\.pnpm\sharp@0.32.1\node_modules\sharp\build\Release\sharp-win32-x64.node   

          Possible solutions:
          - Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
          - Install for the current win32-x64 runtime: "npm install --platform=win32 --arch=x64 sharp"
          - Consult the installation documentation: https://sharp.pixelplumbing.com/install
          - Ensure the version of sharp aligns with the .pnpm package: "npm ls sharp"
              at Object.<anonymous> (E:\directus\node_modules\.pnpm\sharp@0.32.1\node_modules\sharp\lib\sharp.js:37:9)
              at Module._compile (node:internal/modules/cjs/loader:1112:14)
              at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
              at Module.load (node:internal/modules/cjs/loader:988:32)
              at Module._load (node:internal/modules/cjs/loader:834:12)
              at Module.require (node:internal/modules/cjs/loader:1012:19)
              at require (node:internal/modules/cjs/helpers:102:18)
              at Object.<anonymous> (E:\directus\node_modules\.pnpm\sharp@0.32.1\node_modules\sharp\lib\constructor.js:11:1)
              at Module._compile (node:internal/modules/cjs/loader:1112:14)
              at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    }
```

### To Reproduce

- Create a bundle extension
- Create a hook inside the bundle
- Install sharp as a dependency
- Import sharp
- Build the extension
- Try to use it

### Directus Version

9.24+

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
Sharp is a library that depends on installing a system binary which is not supported by rollup bundling. I think the way to use this used to be to `require` it from the Directus context and not bundle it with the extension but i'm not sure if that still works after the ESM move 🤔

**Comment by WoLfulus** [comment]
That's what I was expecting: require it since it's already on node_modules. Even with a dynamic import it fails to load, but from a deeper look I think there might be some OS related issues in this one. I'll try to isolate this and get a more detailed reason on why this happens.

**Comment by br41nslug** [comment]
It is definitely in the directus node_modules however `sharp` is not explicitly in the list of shared dependencies known to Rollup

**Comment by WoLfulus** [comment]
Turns out it's something really weird with pnpm, I changed a hell lot of stuff, and tbh I'm not even sure what got it to work. I think it's probably a combination of being in a monorepo, having multiple versions of the package in the repo and/or using linked local packages.
