### ISSUE TITLE
filterHook doesn't allow to specify a payload type

### ISSUE THREAD

**Issue by nicolaracco** [directus/directus#18557]
### Describe the Bug

The filterHook function doesn't let specify a generic type for the payload object even if FilterHandler already uses generics. https://github.com/directus/directus/blob/d16c3896987af769ca73502a06ae400383dcaebd/api/src/extensions.ts#L542

It's a trivial issue, that could be easily solved changing it to:
```ts
    filter: <T = unknown>(event: string, handler: FilterHandler<T>) => void;
```

If it's ok I would send a PR for this.

### To Reproduce

The following snippet doesn't work in typescript by default.
```
filter('items.create', (payload, _meta, { accountability }) => {
    // Change the payload if request comes from app/admin
    if (accountability && !(accountability.admin || accountability.app)) {
      delete payload.project; // => Error: 'payload' is of type 'unknown'
    }
    return payload;
});
```

And payload type cannot be specified. The only way to make it work is by doing:
```
filter('items.create', (payload, _meta, { accountability }) => {
    const input = payload as MyPayload;
    // Change the payload if request comes from app/admin
    if (accountability && !(accountability.admin || accountability.app)) {
      delete input.project; // => Error: 'payload' is of type 'unknown'
    }
    return input;
});
```

### Directus Version

v10.0.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Can you specify this a bit or put it in context? How exactly is the first snippet supposed to work, where do you specify the payload type?

**Comment by nicolaracco** [comment]
Sorry, my fault. I don't know why the other day I was hitting an error on this, but I couldn't find a way to properly cast the input argument. Anyway, this is properly working now. This is the code I was working on:

```ts
interface User {
  [key: string]: unknown
  input: {
    status: unknown;
    role: unknown;
  };
}

export default async function registerHook({ filter, action }, { services, exceptions, env }) {
    const { AuthenticationService, MailService } = services
    const { InvalidCredentialsException } = exceptions

    filter(
        'users.create',
        async (input: User, { collection }, { database, schema, accountability }) => {
            // Do not change the payload if request comes from app / admin
            if (!accountability || (accountability.admin && accountability.app))
                return
            delete input.status
            delete input.role
            return input
        }
    )

   ...
}
```
