### ISSUE TITLE
Default language in translate relation field allows only number

### ISSUE THREAD

**Issue by swttt** [directus/directus#1855]
## Version Info
  - Directus version and branch: Master branch
  - PHP version: 7.0
  - MySQL version: Ver 14.14 Distrib 5.7.19
  - Web server: Nginx
  - OS name and version: Ubuntu 16.04

## Expected Behavior
Select a default language based on char/varchar

## Actual Behavior
It only allows input as a number now.

## Steps to Reproduce
 1. Follow your tutorial on how to setup multi language content

**Comment by rijkvanzanten** [comment]
This has been closed by https://github.com/directus/directus/commit/395c1774e570b7c20ae9075a91ccf93b3ecbc239 on the [`develop`](https://github.com/directus/directus/tree/develop) branch and will release with master soon.
