### ISSUE TITLE
[SSO] Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by RobinFrcd** [directus/directus#18558]
### Describe the Bug

Hi,
I've configured an [OAuth 2.0](https://docs.directus.io/self-hosted/config-options.html#sso-oauth2-and-openid) provider with my own [authentik](https://goauthentik.io/) server.

When I try to log in, the connection through authentic goes fine but I'm getting `Wrong username or password` on directus. When I look at the logs I see a lot of connections being blocked because of CORS.

I've tried to set my `CORS_ORIGIN` env var to `"array:https://authentik.example.com,https://directus.example.com"` but it didn't help.

Is there something else I can do ?

Thanks,

### To Reproduce

Configure SSO and set `CORS_ORIGIN`

### Directus Version

v10.0.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻
