### ISSUE TITLE
Unable to view file information in file library, causing frontend to hang

### ISSUE THREAD

**Issue by deounix** [directus/directus#18569]
### Describe the Bug

When attempting to view file information in the Directus file library, the frontend becomes unresponsive and hangs. This occurs when clicking on certain files or images to retrieve their details.

Inside the developer console am getting this error:

`TypeError: Cannot read properties of null (reading 'insertBefore')`

### To Reproduce

Steps to Reproduce:

1. Navigate to the file library in Directus
2. Click on a file or image to view its details

### Directus Version

v10.1.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by drennvinn** [comment]
I just updated to 10.1.0 and I'm experiencing the same error. It's a big problem I think it will have to be solved quickly

**Comment by deounix** [comment]
> Which browser are you using?

Google chrome v111.0.5563.111

**Comment by drennvinn** [comment]
I use chrome too but I tried on firefox, edge, safari and it's the same for all browsers

**Comment by paescuj** [comment]
Okay, thanks & may I ask you about the OS as well?

**Comment by drennvinn** [comment]
MacOS 13.3.1

**Comment by deounix** [comment]
> Okay, thanks & may I ask you about the OS as well?

Tested locally: Windows 11

**Comment by paescuj** [comment]
> > Okay, thanks & may I ask you about the OS as well?
> 
> Tested locally: Windows 11

Using the Docker image?

**Comment by Arood** [comment]
I'm experiencing this on a docker image as well, same error
