### ISSUE TITLE
Directus error on tables with a composite primary key (junction tables)

### ISSUE THREAD

**Issue by nangelov77** [directus/directus#18580]
### Describe the Bug

Looks like junction tables are completely ignored and inaccessible through Directus UI/API due to having composite keys. During the initialization of Directus, the following warning message is shown in the log. `Collection "<table_name>" doesn't have a primary key column and will be ignored`.

Any attempt at interacting with or modifying this table results in a 403 Forbidden. 
![Screenshot (309)](https://github.com/directus/directus/assets/99470328/a7d4c9e7-70df-47d9-8d64-efaca273c124)

Getting `[FORBIDDEN] You don't have permission to access this.` from the UI.
![Screenshot (314)](https://github.com/directus/directus/assets/99470328/9b8f92fb-0a92-4fe4-835d-b8aa086e124c)

Getting `403 Forbidden` for any API operation related to a junction table.
![Screenshot (328)](https://github.com/directus/directus/assets/99470328/7df11f25-0869-4ab8-a94e-97873adbcf3c)

### To Reproduce

1. To reproduce, use the following docker-compose.yml file.

```
version: '3'
services:
  database:
    container_name: database
    image: mariadb
    networks:
      - directus
    environment:
      MARIADB_ROOT_PASSWORD: 'directus'
      MARIADB_USER: 'directus'
      MARIADB_PASSWORD: 'directus'
      MARIADB_DATABASE: 'directus'
    ports:
      - 3306:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    networks:
      - directus
    depends_on:
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      DEBUG: 'knex:query,knex:bindings'
      DB_CLIENT: 'mysql'
      DB_HOST: 'database'
      DB_PORT: '3306'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'false'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'

networks:
  directus:
``` 

2. Create a folder called sql
3. Inside the folder, create an SQL file called data.sql and add the contents below. 

```
CREATE TABLE notecodes (
  notecode_nbr int NOT NULL AUTO_INCREMENT,
  note_code nchar(12) NOT NULL,
  note_desc nchar(30) NULL,
  text nchar(250) NULL,
  editable int NULL,
  PRIMARY KEY (notecode_nbr)
);

CREATE TABLE notetriggers 
  notetrig_nbr int NOT NULL AUTO_INCREMENT,
  notetrig_desc nchar(30) NULL,
  notetrig_appl int NULL,
  notetrig_mode int NULL,
  PRIMARY KEY (notetrig_nbr)
);

CREATE TABLE notecode_trig (
  notecode_nbr int NOT NULL,
  notetrig_nbr int NOT NULL,
  PRIMARY KEY (notecode_nbr, notetrig_nbr),
  FOREIGN KEY (notecode_nbr) REFERENCES notecodes(notecode_nbr),
  FOREIGN KEY (notetrig_nbr) REFERENCES notetriggers(notetrig_nbr)
);

INSERT INTO notecodes (note_code, note_desc, editable) VALUES ('DEFAULT', 'Default Note Code', 1);

INSERT INTO notetriggers (notetrig_desc, notetrig_appl, notetrig_mode) VALUES ('Manual Subscriber Note Entry', 7, 1);

INSERT INTO notecode_trig (notecode_nbr, notetrig_nbr) VALUES (1, 1);
``` 

### Directus Version

v9.22.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Directus currently does not support composite primary keys. Feel free to create a feature request instead 😄 

![image](https://github.com/directus/directus/assets/9389634/40bfd0ff-d80b-4e86-a39f-e55b34bb0800)
https://docs.directus.io/app/data-model/collections.html#create-a-collection
