### ISSUE TITLE
Directus bundles extensions are not working as expected

### ISSUE THREAD

**Issue by navanshu** [directus/directus#18593]
### Describe the Bug

Directus doesn't load the bundle extensions, I am copying the dist and package.json on extensions folder under /testing

### To Reproduce

Make a directus extension of type bundle
Add a few extensions to it using the give commands in package.json
Build the extension 

Copy package.json and dist folder to ./extensions/testing/ (path as per docker config)

### Directus Version

v10.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by chrisgoddard** [comment]
Hey team, this part here:
> When using bundles as local extensions make sure your extension folder is prefixed with `directus-extension-` so it should work if you update your deploy path to `./extensions/directus-extension-testing/`

**Comment by romanlex** [comment]
what about restriction? 
I dont see this information on https://docs.directus.io/extensions/bundles.html
And what about format of package.json inside bundle extension?
`entries` section need for src code
`path` for output code
Which values needed inside dist bundle extension?
