### ISSUE TITLE
Empty update in auth drivers thows an error, preventing login

### ISSUE THREAD

**Issue by aidenfoxx** [directus/directus#18595]
### Describe the Bug

Reported by a user in Discord. I was unable to get additional information such as DB vendor, and exact Directus version. 

The issue relates to the recently added  `auth.update` hook, which now always triggers an SQL user update on authentication with an existing account: https://github.com/directus/directus/blob/main/api/src/auth/drivers/oauth2.ts#L162

When an empty update is triggered, Knex throws the error `Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query.`. This prevents the user from authenticating.

I am unsure if this only affects certain vendors, or if it is limited to the OpenID and OAuth flows. I would reason that LDAP and SAML flows would also be affected.

### To Reproduce

Authentication as an existing user on an auth driver that supports updating user information on login (OpenID, OAuth, LDAP, SAML).

### Directus Version

v10.1.0+

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by aidenfoxx** [comment]
> The issue did not happen when this line was {}

Are you certain it works with an empty object? I would hope Knex evaluates `{ auth_data: undefined }` the same as `{}`, but maybe not.

The underlying change that causes the user update to be triggered with an empty object was added here. I think that was released just before v10.0.0: https://github.com/directus/directus/pull/18131/files#diff-249d6560e108f61fab7c1b235ece9adcf3880369803d990f7771a680888fb408L145

> With this new scope the refresh token is sent and the user can log in (so maybe updating the example could be enough)

This wouldn't work consistently for all auth providers, unfortunately.

**Comment by Myddna** [comment]
> Are you certain it works with an empty object? I would hope Knex evaluates `{ auth_data: undefined }` the same as `{}`, but maybe not.

Yep, I changed the line locally and it worked (several times, to be sure). Someone had a similar issue while working with knex and having objects with elements set to undefined: https://github.com/knex/knex/issues/3591#issuecomment-628753558 

I've tried to find where on knex code this happens but no luck for now.

**Comment by aidenfoxx** [comment]
> Yep, I changed the line locally and it worked (several times, to be sure). Someone had a similar issue while working with knex and having objects with elements set to undefined: https://github.com/knex/knex/issues/3591#issuecomment-628753558

Okay. that's weird behavior from Knex IMO, but at least it's an easy fix. We can just set auth data to `null` if it's undefined.

**Comment by echocrow** [comment]
`userPayload.auth_data ?? null` confirmed working too on our end

**Comment by aidenfoxx** [comment]
PR is up: https://github.com/directus/directus/pull/18607

**Comment by rijkvanzanten** [comment]
PR is merged 🚀
