### ISSUE TITLE
ID: Value is required

### ISSUE THREAD

**Issue by ztob** [directus/directus#18609]
### Describe the Bug

Does anyone know with what it can be related this as it worked before v10.1.0
It fails even if I try to enable ID editing 

```
The following fields have invalid values:
    ID: Value is required
```

<img width="1270" alt="image" src="https://github.com/directus/directus/assets/88615762/fc8c48e2-bf9f-4eec-948c-ad2443a015a1">
<img width="733" alt="image" src="https://github.com/directus/directus/assets/88615762/2aaf4917-7e9d-49b2-ae55-ab9b55df338b">

<img width="900" alt="image" src="https://github.com/directus/directus/assets/88615762/c6077bde-9dd5-4750-9abc-c5c4b2cbb82e">
<img width="947" alt="image" src="https://github.com/directus/directus/assets/88615762/d6fb7c07-4f60-4dec-8457-3d7350460b50">

### To Reproduce

I don't know how to reproduce as it works on different collections, on this failing collection ot worked before I did update from 10.0.0 to 10.1.0

### Directus Version

v10.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by daltonsutton** [comment]
I'm having this issue as well with a fresh install. Using the default ID field when setting up a new collection. Haven't dived into it yet, but super odd.

**Comment by paescuj** [comment]
Which type is used for the ID field? Could you maybe share a screenshot of the ID field settings?

**Comment by mundry** [comment]
I can't reproduce it anymore with 10.1.1, like before with 10.1.0. I'm not really able to tell from the changelog what the brought the fix about.

**Comment by Fusseldieb** [comment]
Same error here. Our database pkey has become out-of-sync, according to some StackOverflowers.
I was able to "fix" it by using following approach: https://stackoverflow.com/a/71904859/3525780

Transcribed link:

> (Replace the table_name to your actual name of the table.)
> 
> 1. Gives the current last id for the table. Note it that for next step.
> SELECT MAX(id) FROM table_name;  
> 
> 2. Get the next id sequence according to postgresql. Make sure this id is higher than the current max id we get from step 1
> SELECT nextVal('"table_name_id_seq"');
> 
> 3. If it's not higher than then use this step 3 to update the next sequence.
> SELECT setval('"table_name_id_seq"', (SELECT MAX(id) FROM table_name)+1);
