### ISSUE TITLE
Can't add logo within global settings (error)

### ISSUE THREAD

**Issue by swttt** [directus/directus#1860]
## Version Info
  - Directus version and branch: Master branch
  - PHP version: 7.0
  - MySQL version: 
  - Web server:  nginx
  - OS name and version: Ubuntu 16.04

## Expected Behavior
Trying to add an image/logo for the global settings so it shows in the top-left.

## Actual Behavior
Error when saving the image:
```array_key_exists() expects parameter 2 to be array, string given```

## Steps to Reproduce
 1. Go to global settings
 2. Chose a local image
 3. Press save

**Comment by rijkvanzanten** [comment]
Interesting
I'm able to upload a photo but am not able to select an existing one / import an url on develop latest..

**Comment by WellingGuzman** [comment]
Hey @swttt, this has been fixed by https://github.com/directus/directus/commit/f2bf1c1eb9b2817f6578f4ea82e61c48bcc85e9d, it will be included in 6.4.4.

I'm having some issue as @rijkvanzanten mentioned selecting existing one or importing from an url.

I'm working on getting that fixed now.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/745a8b46ede5df6be000b7c05d58644dd337db99

**Comment by swttt** [comment]
Aah... so the actual issue was fixed already. Couldn’t find an issue for it on here sorry 😀

**Comment by hjbarraza** [comment]
I still haven't been able to make it work, even from a fresh branch.

I tried:
1. uploading to file library (works)
2. choosing from existing (opens new window)
2.1. it loads the file selection page, but immediately, reloads the previous screen

**Comment by rijkvanzanten** [comment]
@hjbarraza Do you have some more specific details about the env? What directus version? What PHP version/server etc etc. Anything we can use to reproduce the issue basically :)

**Comment by WellingGuzman** [comment]
@hjbarraza also when you say fresh branch, which branch are we talking about?

**Comment by WellingGuzman** [comment]
This issue has been fixed in the `develop` branch.

**Comment by hjbarraza** [comment]
Thanks 
I git cloned from https://github.com/directus/directus.git

### INFO:
* PHP Version 7.0.22-0ubuntu0.16.04.1
* Apache/2.4.18 (Ubuntu)

https://api.impactosocial.co/info.php

**Comment by WellingGuzman** [comment]
Hey @hjbarraza make sure to checkout your branch (default to master) to `develop` using `git checkout develop`
