### ISSUE TITLE
repeater interface not working

### ISSUE THREAD

**Issue by MCl57** [directus/directus#18614]
### Describe the Bug

Create field with type repeater. No templates are displayed.
Version 9.26.0 is working.

### To Reproduce

Create field with type repeater. 

### Directus Version

v10.0.0 and v10.1.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
Thanks for opening this issue! However this is a duplicate of an existing issue #18599, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #18599 for future updates.
