### ISSUE TITLE
npx directus init/bootstrap did nothing, help

### ISSUE THREAD

**Issue by Nomia** [directus/directus#18613]
### Describe the Bug

i want to get started with directus, and i followed this article in official documentation
https://docs.directus.io/self-hosted/cli.html#server

i tried `npx directus init`, but there is nothing generated

then, I tried `npx directus bootstrap`, it did nothing neither
![image](https://github.com/directus/directus/assets/1707818/bac19e37-d628-47b5-bd8e-9cf048d723d7)

please let me know if there was anything that I'm missing

### To Reproduce

1.create an empty folder

2.try `npx directus init`

3.try `npx directus bootstrap`

### Directus Version

10.1.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by Nomia** [comment]
and when i try to create project with yarn `yarn create directus-project directus-demo`

![image](https://github.com/directus/directus/assets/1707818/2d91dfef-5fb9-4442-868e-feb238d490c0)

it says package cannot be found

**Comment by paescuj** [comment]
We haven't been able to reproduce this based on the given information, so I'll close this for now.
Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

It seems like you're currently having some issues connecting to the NPM registry as those packages are indeed available in the registry.

<img width="762" alt="Screenshot 2023-05-16 at 09 53 44" src="https://github.com/directus/directus/assets/5363448/27b526fd-1eec-4ee3-8b1c-f860f530dcf5">

<img width="774" alt="Screenshot 2023-05-16 at 09 37 43" src="https://github.com/directus/directus/assets/5363448/0fafe090-e6f3-48f9-8e2c-c065e9554846">

**Comment by Nomia** [comment]
hi @paescuj 
could u tell me what is your registry?
mine is 
`registry=https://registry.npmjs.org`

**Comment by paescuj** [comment]
Yeah, Directus packages are on https://registry.npmjs.org.
This should be the default setting, should not need to be explicitly defined.
