### ISSUE TITLE
Http code for exceptions

### ISSUE THREAD

**Issue by cgarnier** [directus/directus#1862]
## Version Info
  - Directus version and branch: build
  - PHP version: 5.6
  - MySQL version: 5
  - Web server: apache (directus-docker) 
  - OS name and version: ubuntu 14

## Expected Behavior
An exception or a fatal erreur should respond with a http 500. 
Idealy, it should be globaly catched and wrapped into an http error

## Actual Behavior
It reponds with a 200

## Steps to Reproduce
exemple with log rights
 1. `chmod -xr *.log`
 2. 200 `Fatal error: Uncaught ErrorException: fopen(/var/www/html/api/logs/2017-10-05.log): failed to open stream...`

**Comment by WellingGuzman** [comment]
Hey @cgarnier, what error are you getting? not having permission to write to the logs directory getting you a 200 status code?

**Comment by cgarnier** [comment]
Yes it does

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/03975374781c488a8ea8813f4310267ae1a6d772
