### ISSUE TITLE
Incorrect version update shown

### ISSUE THREAD

**Issue by u12206050** [directus/directus#18632]
### Describe the Bug

<img width="358" alt="Screenshot 2023-05-16 at 20 27 37" src="https://github.com/directus/directus/assets/6641242/2ecd6677-f825-468e-a7bc-bdcb6cd6d537">

Released is version `10.1.1`

### To Reproduce

Run directus

### Directus Version

v10.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by licitdev** [comment]
The incorrect version can also be found in the server info. 

<img width="204" alt="image" src="https://github.com/directus/directus/assets/26413686/e7ed4891-7bc1-4d90-8934-9629fcc0b242">
