### ISSUE TITLE
[Feature request] Choose the auth method

### ISSUE THREAD

**Issue by cgarnier** [directus/directus#1864]
Hello,
Is it possible to choose only one auth method? 
I think mixing tokens and php session is a mess.

I encountered some login issue on directus. Sometime i can no more connect to directus. It responds with a 403 but it doesnt show any login form. I have to clear cookie and retry.

**Comment by WellingGuzman** [comment]
Feature request should be added here: http://request.getdirectus.com

We are planning on doing this soon.

Thanks for the recommendation.
