### ISSUE TITLE
[Feature request] Logout method

### ISSUE THREAD

**Issue by cgarnier** [directus/directus#1865]
## Version Info
  - Directus version and branch: build
  - PHP version: 5
  - MySQL version: 5 
  - Web server: apache
  - OS name and version: ubuntu 

Need a endpoint to logout and invalidate the token.

**Comment by WellingGuzman** [comment]
You can use `GET /api/1.1/auth/logout`.

Also feature request should be added into http://request.getdirectus.com.
Also we are probably going to deprecate this functionality (persistent authentication)

**Comment by cgarnier** [comment]
This endpoint make a redirection to /login. Nothing to do in /api.

It should just return 200 some message to say it s ok.

It doesnt invalidate the token. When i relog i get exactly the same. That make no sense.

**Comment by WellingGuzman** [comment]
Which token do you want to invalidate @cgarnier?

**Comment by rijkvanzanten** [comment]
I think he's referring to the `access_token` @WellingGuzman

**Comment by cgarnier** [comment]
It s for a security reason. The token must not remains valid for eternity. If, for some reason, some one get it, he can login on your account and you cant revoke his access.

**Comment by WellingGuzman** [comment]
Thanks @rijkvanzanten, it makes sense.

**Comment by WellingGuzman** [comment]
We set the access_token to `NULL`, but the redirection still there, it will be removed in the next API version.

Ref: https://github.com/directus/directus/commit/fa16a6431eff11b7f25e2296bb8538abfb3b514f
