### ISSUE TITLE
Missing Permissions since 10.1.1

### ISSUE THREAD

**Issue by rasco** [directus/directus#18654]
### Describe the Bug

I have a mysterious bug since 10.1.1 where some user roles lost some of their permissions – but the permissions are set correctly.
I rolled back to 10.1.0 and everything is working again.

I think I found the bug: 
The permissions list is too long, and I guess due to this commit https://github.com/directus/directus/pull/17309 it is not being transferred entirely.
(Yes I have many collections)

- I used network inspector to see which permissions are being transferred, and turned out many of them were left out
- Then I used the API manually to get the permissions and same thing
- But as soon as I set limit:-1 to the request, all permissions get returned correctly.

### To Reproduce

Have many collections (I don't know how many, but the permissions API response was about 120 entries, around 4 per collection).

Create roles with varying CRUD-access to those collections

Log in as one of the roles and check if you can create/update items.

### Directus Version

v10.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rasco** [comment]
On 10.1.0 the permissions JSON that get transferred to the browser has 520 entries
This is the URL that gets requested: `/permissions?limit=-1&filter[role][_eq]=xxxxx`

On 10.1.1 it only has 116 entries, and this is the URL: 
`/permissions?filter[role][_eq]=xxxxxx`

**Comment by domdus** [comment]
Great analysis @rasco !
Same issue here. Though I messed up something with the data. 😀

**Comment by u12206050** [comment]
Please fix asap, as we can't even rollback to 10.1.0 due to the oauth issue, and so basically have to rollback to version 9.25
@rijkvanzanten

**Comment by paescuj** [comment]
> Please fix asap, as we can't even rollback to 10.1.0 due to the oauth issue, and so basically have to rollback to version 9.25 @rijkvanzanten

Working on it 👍

**Comment by deounix** [comment]
> Quickfix that seems to work for us: In the dockerfile we use to build our directus instance, add:
> 
> ```dockerfile
> ENV QUERY_LIMIT_DEFAULT=1000
> ```

You're a life saver! :))
