### ISSUE TITLE
Error "ID: Value has to be unique" when migrating schema and data

### ISSUE THREAD

**Issue by hasnainsaad93** [directus/directus#18662]
### Describe the Bug

This issue is a duplicate of this closed ticket, where the error still persist in v10.1.1

https://github.com/directus/directus/issues/18609

Where "ID: Value has to be unique" error appears when creating new entry after migrating and afterward importing dataset from source to target.

### To Reproduce

Detail steps to reproduce is mentioned in the following ticket, 

https://github.com/directus/directus/issues/18609

### Directus Version

v10.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
I think you need to update the ID field, for example by toggling the "Hidden on Detail" option, so the options are properly set again.

**Comment by hasnainsaad93** [comment]
> I think you need to update the ID field, for example by toggling the "Hidden on Detail" option, so all options are properly set again.

I recreated a new collection just in case to check if the issue persist. After migration and importing data, I did toggling of hide/unhide ID field. But issue still persist.

**Comment by paescuj** [comment]
If you migrate the collection, the wrong default value for the primary key is also taken over.

I think there are two ways to solve the issue:
- Recreate the collection in Directus and then import the data
- Manually correct the primary key in the database for the existing collection
  ```sql
  # Example for PostgreSQL (with auto-incremented integer for primary key)

  ALTER TABLE <collection> ALTER COLUMN <primary_field> SET DEFAULT nextval('<collection>_<primary_field>_seq');
  # Example:
  # ALTER TABLE example ALTER COLUMN id SET DEFAULT nextval('example_id_seq');

  # Verify whether the nextval for the sequence is appropriate
  SELECT nextval('example_id_seq');
  # If not, set the correct nextval -> https://www.postgresql.org/docs/current/functions-sequence.html
  ```

In both cases, you may want to make a backup before.

**Comment by hasnainsaad93** [comment]
Can we make this the part of import utility as a fix ? Instead this work around might create redundancy in our deployment process.

**Comment by paescuj** [comment]
> Can we make this the part of import utility as a fix ? Instead this work around might create redundancy in our deployment process.

This is just a one-time fix that needs to be applied if you've been affected by that particular issue ( #18609) by actually updating the primary field. It has been fixed in #18579 and is therefore no longer an issue.

**Comment by hasnainsaad93** [comment]
I am getting this issue every time I create new collections and migrating them onto production server. This script execution/recreating collection that you suggested above have to be done every time we are deploying new stuff.

**Comment by paescuj** [comment]
In that case you need to apply the fix in your staging environment. Afterwards the snapshot will be fine as well so no further steps are required in production.

**Comment by antonio-silencio** [comment]
same problem here. in a directus cloud environment. how to solve this issue if we don't have access to db?

**Comment by jaads** [comment]
this will potentially get fixed by https://github.com/directus/directus/pull/19328
