### ISSUE TITLE
Password interface doesn't work outside `directus_users` table

### ISSUE THREAD

**Issue by airbenich** [directus/directus#1866]
## Version Info
  - Directus version and branch: 6.4.3 release
  - PHP version: 7.1
  - MySQL version: N/A
  - Web server: PLESK with Apache & nginx for static data
  - OS name and version: CentOS

## Expected Behavior
Passwords using password ui will be encrypted after saving it via directus webinterface to the database

## Actual Behavior
Passwords using password ui will not be encrypted

## Steps to Reproduce
 1. Install directus 6.4.3
 2. Build a new table and add password ui
 3. create a new entry on this table with a password
 4. take a look into the database and see that the password is not encrypted

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/0d7bfe280dee1b73838ff379f6597a3818f950da
