### ISSUE TITLE
Disappearing / reappearing properties

### ISSUE THREAD

**Issue by braco** [directus/directus#18675]
### Describe the Bug

Created a data model.

Created one record.

Added a new field to the model, simple text field called title.

Tried to update the record, it looked like it wasn't working. As in the form would submit and the record wasn't changed.

I reloaded a couple times and noticed that the value would sometimes appear.

This is difficult to demonstrate, so I setup a node API client that would retrieve and print the record., and it happens through the API as well.

These are seconds apart:

```
❯ node newscripts/test.mjs
{
  id: 1,
  status: 'draft',
  date_created: '2023-05-21T02:48:03.008Z',
  date_updated: '2023-05-21T02:53:09.294Z'
}

❯ node newscripts/test.mjs
{
  id: 1,
  status: 'draft',
  date_created: '2023-05-21T02:48:03.008Z',
  date_updated: '2023-05-21T02:53:09.294Z',
  title: 'Test Title?'
}
```

This is running in directus/directus docker. Couldn't find a duplicate issue, please let me know what other info I can provide.

### To Reproduce

Created a data model.

Created one record.

Added a new field to the model, simple text field called title.

Go back to record, try to edit title

### Directus Version

v10.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by braco** [comment]
I added another field to test. Now the title field seems stable, but the new field appears/disappears in the same manner.

```
❯ node newscripts/test.mjs
{
  id: 1,
  status: 'published',
  date_created: '2023-05-21T02:48:03.008Z',
  date_updated: '2023-05-21T03:23:05.692Z',
  title: 'Test Title?',
  another_test: null
}
❯ node newscripts/test.mjs
{
  id: 1,
  status: 'published',
  date_created: '2023-05-21T02:48:03.008Z',
  date_updated: '2023-05-21T03:23:05.692Z',
  title: 'Test Title?'
}
```

**Comment by braco** [comment]
I added CACHE_ENABLED=false to the docker ENV and it seems to be acting normal now. This would have rebuilt / restarted everything as well, I assume there's a chance that alone did something

**Comment by braco** [comment]
Still weirdness happening, viewing a collection randomly throws this error:

UNEXPECTED ERROR
[FORBIDDEN] You don't have permission to access this.

if I reload the page, sometimes it goes away.

I also tried to create a file field and it failed with something like "there's no such collection as X", but the field was created

**Comment by braco** [comment]
Trying to create a record in this collection randomly shows this:

<img width="249" alt="Screenshot 2023-05-23 at 4 41 56 PM" src="https://github.com/directus/directus/assets/2449172/0f7d13c9-468e-416b-85cc-1ef46fd6809b">

**Comment by rijkvanzanten** [comment]
How many containers are you running? If more than one, are you using Redis for the cache?

**Comment by braco** [comment]
@rijkvanzanten you probably just identified part of the problem: I launched this on DigitalOcean and it defaulted me to 2 containers. I just scaled down to 1. 

However, some of this behavior was happening locally as well.

The only major deviation from the standard provided docker is that I'm using supabase for postgres, which I defined in the ENV.  It's difficult to understand what's happening under the hood otherwise.

How else can I help debug?

**Comment by rijkvanzanten** [comment]
When you have 2+ containers, you have to make sure they're connected to the same store for caches (eg Redis) to make sure that cache invalidation happens across the project. By default, the container caches things in memory, which in turn means that in a load-balanced environment (like digitalocean) you sometimes hit container 1 and sometimes container 2. If they have a different state cached, you start to get this type of unexpected behavior.

> However, some of this behavior was happening locally as well.

Is this something you can accurately reproduce in a "fresh" environment? As of right now, it's a bit chasing a ghost of course 🙂
