### ISSUE TITLE
The Directus self-hosted update is stuck at version 9.26.0

### ISSUE THREAD

**Issue by Silbad** [directus/directus#18674]
### Describe the Bug

I update with your documentation ; `npm update`
But the version is stuck at 9.26.0.
Perhaps this is due to the change of licence?

### To Reproduce

- a version 9.26.0
- `npm update` (on Ubuntu)

### Directus Version

v9.26.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by deounix** [comment]
There's two ways to update Directus

1. Update it globally (it's not a good if you've a separate projects on the same machine and every one of them depends on specific Directus version)

`
npm i -g directus@latest
`
Then navigate to your project directory & run the migration command

`
cd /home/blah blah & npx directus database migrate:latest
`

2. Update it locally (inside the project)

Navigate to you project directory and update Directus version to the latest & run the migration command

`
cd /home/blah blah; npm i --save directus@latest; npx directus database migrate:latest
`

**Comment by Silbad** [comment]
Ok this documentation is no longer relevant then? https://docs.directus.io/self-hosted/upgrades-migrations.html

**Comment by deounix** [comment]
> Ok this documentation is no longer relevant then? https://docs.directus.io/self-hosted/upgrades-migrations.html

This docs assumed that you've installed Directus locally (inside the project)

e.g.

`
npm init
npm i --save pg
npm i --save directus@latest
`

**Comment by Silbad** [comment]
Yes, this is my case, on an Ubuntu server.
I'll try with `npm i --save directus@latest`

**Comment by Silbad** [comment]
Ok it's work with install, no more update, tks
