### ISSUE TITLE
Slug field not save after update

### ISSUE THREAD

**Issue by dsivokhin** [directus/directus#1867]
## Version Info
  - Directus version and branch: develop
  - PHP version: 7.0
  - MySQL version: 5.7
  - Web server: nginx
  - OS name and version: Ubuntu

## Actual Behavior
When created new item, `slug` field will pull value from `title` and saved in DB. 
When update item and change field `title`, `slug` field changed in interface, but not saved in DB.

## Steps to Reproduce
 1.  Create two fields `title` - text input and `slug` - type slug 
 2. Create new item, write `title`, `slug` will pull it's value from `title` 
 3. Update item change `title` and save, `slug` field new value not save in DB

## Schema Dump, Logs, or Screenshots

![default](https://user-images.githubusercontent.com/4669992/31275906-db8c1dd6-aaa1-11e7-8dee-bed7c70e86d1.png)

![default](https://user-images.githubusercontent.com/4669992/31276061-a280b488-aaa2-11e7-9e1d-3fe1321fed2e.png)

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/fe251aa510c9f979ea0e10749e1b9246c6044fee
