### ISSUE TITLE
Checkbox UI – wrong delimiter

### ISSUE THREAD

**Issue by airbenich** [directus/directus#1868]
## Version Info
  - Directus version and branch: 6.4.3 develop
  - PHP version: 7.1
  - MySQL version: N/A
  - Web server: PLESK with Apache & nginx for static data
  - OS name and version: CentOS

## Expected Behavior
The Checkbox UI has a custom delimiter option. Selecting a + as the delimiter should store the data like this in the database:
`+firstElement+secondElement+thirdElement+`

## Actual Behavior
The database has the following value:
`+firstElement,secondElement,thirdElement+`

## Steps to Reproduce
 1. Set up new directs UI checkbox
 2. create a new entry on this table with a checkbox ui
 3. select some elements and store the entry
 4. take a look into the database and see that the wrong checkbox field

**Comment by rijkvanzanten** [comment]
Hey @airbenich! This is fixed in https://github.com/directus/directus/commit/9d3263c89cabc7bbba64433ccdd195725ae81c2c. Please let me know if the problem persists after upgrading to this commit.

**Comment by airbenich** [comment]
Thank you! Delimiter is now correct!
