### ISSUE TITLE
defineDisplay fields configuration does not work

### ISSUE THREAD

**Issue by Helongzhou** [directus/directus#18681]
### Describe the Bug

I'm trying to customize a display to implement row manipulation, and I'm trying to get the current item's field values via fields in index.ts like directus/display/user
![image](https://github.com/directus/directus/assets/20851197/23d24127-374e-45ae-85b9-28b312f7235e)

But just not work  as expected.

### To Reproduce

```js
import { defineDisplay } from '@directus/extensions-sdk'
import DisplayComponent from './display.vue'

export default defineDisplay({
  id: 'action-display',
  name: 'action-display',
  icon: 'box',
  description: 'Display a button for action!',
  component: DisplayComponent,
  types: ['string', 'uuid'],
  options: [
    ...
  ],
   fields: ['id', 'description', 'status', 'currency', 'amount']
});
```

### Directus Version

v10.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
The fields list there is an option list and is used to fetch these fields by the display. The value of the field your display belongs to gets passed to your extension as `value` property https://docs.directus.io/extensions/displays.html#available-props

**Comment by Helongzhou** [comment]
> The fields list there is an option list and is used to fetch these fields by the display. The value of the field your display belongs to gets passed to your extension as `value` property https://docs.directus.io/extensions/displays.html#available-props

I followed the documentation to configure the fields option, but the custom display doesn't show up, I think it might be reporting an error but not throwing it. At the moment I can only get the current primaryKey when the user clicks the button via route interception, but this is not a conventional method.
![image](https://github.com/directus/directus/assets/20851197/c6571d2c-4ce3-4181-824b-57ba2d6912a7)
![image](https://github.com/directus/directus/assets/20851197/a19acdba-e9d8-46cc-9f0a-13811af46ed3)

**Comment by br41nslug** [comment]
Sorry my bad apparently someone added this and i was not aware 😬 
> fields — If this option is set, the display will fetch relational fields. Can either be an array of fields or a function that returns an array of fields.

**Comment by rijkvanzanten** [comment]
> and I'm trying to get the current item's field values via fields in index.ts like directus/display/user

The `fields` option in the extension manifest aren't the fields of the _current_ item, they're the fields of the _related_ item when used with a relational field. In the `user` example, that is a display that shows the values of the related user record in the display. The fields in that screenshot (eg `id`, `avatar.id` etc) are the fields that exist on `directus_users`
