### ISSUE TITLE
M2M reference the same id's on my collection Item's, but on API they're not

### ISSUE THREAD

**Issue by staminna** [directus/directus#18680]
### Describe the Bug

 Create a M2M reference another Collection and add the **same item's** _id's_ a Collection for example 1 and 5; 2 and 6; and 3 and 4:

```
 {
	"Common_name": "Name 1",
	"id": 1,
	"Picture_Eco": "90651a12-085b-4721-ac1a-8418eec321d8",
	"sort": null,
	"user_created": "z0bca66b-0b1c-4ad8-abf5-d974a4fa19a0",
	"user_updated": "z0bca66b-0b1c-4ad8-abf5-d974a4fa19a0",
	"m2m_Eco_details": [
		1,
		5
	]
},
{
	"Common_name": "Name 2",
	"id": 2,
	"Picture_Eco": "042ecc5a-f3eb-429f-82a6-0b590342dfdd",
	"sort": null,
	"user_created": "z0bca66b-0b1c-4ad8-abf5-d974a4fa19a0",
	"user_updated": "z0bca66b-0b1c-4ad8-abf5-d974a4fa19a0",
	"m2m_Eco_details": [
		2,
		6
	]
},
{
	"Common_name": "Name 3",
	"id": 8,
	"Picture_Eco": "b1ff5612-5ba5-44dd-ae19-15cb6c4aae15",
	"sort": null,
	"user_created": "25848c6e-e69d-4b59-b0d5-899dd471db4e",
	"user_updated": "z0bca66b-0b1c-4ad8-abf5-d974a4fa19a0",
	"m2m_Eco_details": [
		3,
		4
	]
}

```

### To Reproduce

And in fact, they are exactly the very same items. I can see the mapping from the hidden junction table but instead of

1 and 2, 1 and 2, and 1 and 2 (because they are exactly the same in Directus UI) I get m2m_Eco_details when I check the endpoint in the API they are not. 

Can this be fixed within Directus or needs to be fixed with multiple calls to the API on the frontend side?
We do not want to expose the API details in our front-end calls.

Please let me know your thoughts and thanks for input.

### Directus Version

V10.10.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Because this is a M2M you're seeing the junction table IDs. Try fetching the relational data instead https://docs.directus.io/reference/introduction.html#relational-data
