### ISSUE TITLE
directus_files have status DRAFT when uploaded after Upgrade from 6.3.9

### ISSUE THREAD

**Issue by airbenich** [directus/directus#1869]
## Version Info
  - Directus version and branch: upgraded from 6.3.9 to 6.4.3 develop
  - PHP version: 7.1
  - MySQL version: N/A
  - Web server: PLESK with Apache & nginx for static data
  - OS name and version: CentOS

## Expected Behavior
When a files is uploaded through Single File UI or the File Backend Module, the files should have the state PUBLISHED (when selected).

## Actual Behavior
The files has the status DRAFT.

## Steps to Reproduce
 1. Upload new file through file backend module
 2. select published as status
 3. save file entry
 4. see details of this file or database entry -> DRAFT

**Comment by WellingGuzman** [comment]
Hey @airbenich, can you please share a schema? (if possible)

When you say backend module, do you mean from the files page? or using a `single_file` interface?

**Comment by airbenich** [comment]
Its the same: Uploading from Files Page or using the single_file interface results in a new entry wich has the status: DRAFT.

I send you the schema via Slack.

**Comment by WellingGuzman** [comment]
Not being able to reproduce this issue, that's why I was wondering if you could provide an schema that trigger this bug.

Does your `directus_files.status` has `2` as default value?

**Comment by airbenich** [comment]
In MySQL? Yup, the default value is in MySQL: on directus_files.status = 2

**Comment by WellingGuzman** [comment]
Hey @airbenich, I have tried couple of times no luck reproducing this. If there's a schema you can provide to make this debugging faster that would be great. in the meantime I do not have any information on this bug.

**Comment by airbenich** [comment]
I#ve send you a schema via slack. Changing manually the default value on the database to 1 helped solving the issue.

**Comment by WellingGuzman** [comment]
Hey @airbenich, I didn't receive any schema. I couldn't reproduce this issue using default to `2`, in my end is working as expected. Anyway if you . find a way to reproduce it, it would be great.

Either way, I'm glad you figured it a way out.
