### ISSUE TITLE
Custom Migration Extensions do not have any validation on file name.

### ISSUE THREAD

**Issue by that1matt** [directus/directus#18694]
### Describe the Bug

When creating a custom migration, if there are multiple file names in the `extensions/migrations/*.js`, the migration run command will attempt to process them.

The [documentation](https://docs.directus.io/extensions/migrations.html) states that it should match an `[identifier]-[name].js` file name structure.

The [customMigrations](https://github.com/directus/directus/blob/6141092f298c87e54efcaf4e7f1dddf092868100/api/src/database/migrations/run.ts#L26) filter doesn't limit by the `[identifier]-[name].js` pattern. Where as the [line above](https://github.com/directus/directus/blob/6141092f298c87e54efcaf4e7f1dddf092868100/api/src/database/migrations/run.ts#L24) does have a filter.

When Directus tries to run a non-migration file, it will run into a `TypeError: up is not a function` or a `TypeError: up2 is not a function`.

When running this on a fresh install, it will actually cause the `cli bootstrap` command to fail, and not create the first admin user.

### Workaround
A workaround for this, is to make sure that only the migration file is added to the root `/extensions/migrations` folder, with any helpers either being adding inline, or in a nested folder in `/extensions/migrations/<folder-name>`.

### Potential Fixes
1. Add same logic to customMigrations filtering.
2. Update documentation to state that if you require dependency/helper files, that should not live at the root of `/extensions/migrations`

### To Reproduce

1. Create simple migration extension with another file being using in the `[identifier]-[name].js` file.
2. Add both files to `/extensions/migrations`
3. Either run the bootstrap cli for initial database, this will cause the first admin user to not get created and error out, or run `database migrate:up`  to get the error message.

### Directus Version

v10.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
The documented filename restriction is very open-ended (it only really requires the presence of a single `-` to separate between identifier and migration name). #18971 makes sure that `-` is validated against, updates the docs to warn about the presence of non-migration files in the root, and warns and ignores files if they don't export an `up` or `down` function on upgrade / downgrade respectively 🙂
