### ISSUE TITLE
Deleting every column in table throws error

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1870]
## Version Info
  - Directus version and branch: [develop latest](https://github.com/directus/directus/commit/9d3263c89cabc7bbba64433ccdd195725ae81c2c)
  - PHP version: 7.1.6
  - MySQL version: 5.6.35
  - Web server: Apache (MAMP Pro)
  - OS name and version: macOS High Sierra v10.13.1 Beta (17B25c)

## Expected Behavior
Clicking the delete button and submitting the confirmation deletes the column

## Actual Behavior
Directus throws a server error:
```
Statement could not be executed (42000 - 1090 - You can't delete all columns with ALTER TABLE; use DROP TABLE instead)
```

## Steps to Reproduce
1. Create a new blank table
2. Delete every default column

## Additional info
Since we don't actually want to drop the whole table, this issue might be 'unsolveable'. Maybe we should close it as part of [#1237 - Friendly Errors](https://github.com/directus/directus/issues/1237), but it might be nicer if we disabled the delete button with a message telling you can't delete the last item?

**Comment by WellingGuzman** [comment]
The user are now warned about deleting the last column. Also the "X" will be hidden if theres only one column.

Closed by https://github.com/directus/directus/commit/f7d403a07242a2bc528d7698ecf1aba4f7fecbab
