### ISSUE TITLE
Cannot use _istarts_with and _iends_with filters

### ISSUE THREAD

**Issue by nicolaracco** [directus/directus#18702]
### Describe the Bug

I've just discovered directus has support for some case insensitive filters, added with https://github.com/directus/directus/pull/11737 but I cannot find a way to use _istarts_with and _iends_with operators.

### To Reproduce

- Create a collection with a string field.
- Call the items API with `filter={"myField":{"_istarts_with":"foo"}}`

The API returns the following error:
```
{
	"errors": [
		{
			"message": "\"string\" field type does not contain the \"_istarts_with\" filter operator",
			"extensions": {
				"code": "INVALID_QUERY"
			}
		}
	]
}
```

### Directus Version

v10.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by gitstart** [comment]
We'd love to work on this
