### ISSUE TITLE
System fields are editable using the API

### ISSUE THREAD

**Issue by alexey-yarmosh** [directus/directus#18727]
### Describe the Bug

Optional system fields of the collection items are not editable using UI, but nothing prevents user to update them using API requests request.

### To Reproduce

Create a collection with the system fields included: `status`, `sort`, `date_created`, `user_created`, `date_updated`, `user_updated`.
While logged in as `user1` create a new item in the collection.
Then send a PATCH request with body like
```
{
        "user_created": "id_of_user2",
        "date_created": "2024-05-25T12:42:35.000Z"
}
```
That way I (as a plain user) can reassign an item to another user and move the creation date to future.

I'd rather expect `date_created`, `user_created` to be non-editable, and `date_updated` and `user_updated` to be generated automatically on the BE side.

### Directus Version

v10.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
The fields you mention `status, sort, date_created, user_created, date_updated, user_updated` are not system field rather pre-defined fields. They are editable using the UI but are hidden by default. This is working as intended.

**Comment by alexey-yarmosh** [comment]
Configuring permissions fixes that, thank you
