### ISSUE TITLE
Add missing filter operators for case sensitivity

### ISSUE THREAD

**Issue by NEO97online** [directus/directus#18739]
### Page

https://docs.directus.io/reference/filter-rules.html#filter-operators

### Describe the Inaccuracy

The case-insensitive filter operators (`_icontains`) are not documented at all. I almost thought Directus didnt have this functionality until finding this issue: https://github.com/directus/directus/discussions/2981

Maybe more are also undocumented?

**Comment by RubensRafael** [comment]
Hello @rijkvanzanten. Are there any other filters that need to be documented?

**Comment by RubensRafael** [comment]
Hey @rijkvanzanten,
I would love to take on this task.
I’ve noticed that there’s two other filters other than `_icontains` that fall into this category: _istarts_with and _iends_with but these are not working as expected considering https://github.com/directus/directus/issues/18702.
Are there any other filters that need to be documented?
