### ISSUE TITLE
Use `yy` instead of `YY` (in `d. M. YY`)

### ISSUE THREAD

**Issue by AndyTempel** [directus/directus#18744]
### Describe the Bug

{
  "fileName": "https://[TLD]/admin/assets/index.2920f9c2.entry.js",
  "lineNumber": 47,
  "columnNumber": 20968,
  "message": "Use `yy` instead of `YY` (in `d. M. YY`) for formatting years to the input `Fri May 26 2023 13:06:50 GMT+0200 (Central European Summer Time)`; see: https://github.com/date-fns/date-fns/blob/master/docs/unicodeTokens.md"
}

### To Reproduce

Change default language to Slovenian and explore admin dashboard.

### Directus Version

v10.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Translate string:
https://locales.directus.io/translate/directus/70/en-sl#7470

**Comment by br41nslug** [comment]
I was able to reproduce this eventually. For next time it would be much appreciated if the reproductions steps are more specific than "explore admin dashboard" like "open the users detail page" or "any collection with a date field".

**Comment by rijkvanzanten** [comment]
This was resolved through https://locales.directus.io and will be fixed with the upcoming release 👍🏻
