### ISSUE TITLE
extension-sdk: SCSS line comments break the build process

### ISSUE THREAD

**Issue by julianko** [directus/directus#18745]
### Describe the Bug

Having SCSS line comments in a vue file doesn't work with the current `@directus/extensions-sdk` version (10.1.1).

### To Reproduce

- Create a new directus (module) extension: `npm init directus-extension@latest`
- in `src/module.vue`, add an scss style tag with a line comment:
```
<style lang="scss">
// some stuff
</style>
```
- run `npm run build`

### Directus Version

10.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
The extension SDK does not come with CSS preprocessors out of the box. You'll need to add the appropriate rollup extension to the configuration 
https://docs.directus.io/extensions/creating-extensions.html#configuring-the-cli
https://www.npmjs.com/package/rollup-plugin-scss

**Comment by julianko** [comment]
I tried creating a `extension.config.js`:
```
import scss from 'rollup-plugin-scss';

export default {
	plugins: [scss()],
};
```

still getting the same error.

**Comment by nickrum** [comment]
The Extensions SDK uses `rollup-plugin-styles` so in theory you should be able to use scss, provided you have installed sass.

It would be very helpful if you could mention the exact error message you are getting.
