### ISSUE TITLE
Can't set date_created with initial payload

### ISSUE THREAD

**Issue by braco** [directus/directus#18754]
### Describe the Bug

When creating a new record via the API, { date_created } seems to be ignored, but it can be changed on a subsequent request

### To Reproduce

// Doesn't work:
await directus.items('...').createOne({ date_created });

// Works:
const { id } = await directus.items('...').createOne({ });
await directus.items('...').updateOne(id, { date_created });

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
If date created has the "on create - set current date" option set then that will always get priority. If you intend to manually set the date_created instead of generating this you can disable this option in the field settings.
