### ISSUE TITLE
Uploading files fails on Nginx

### ISSUE THREAD

**Issue by nilsborg** [directus/directus#1875]
Hola!

just installed Directus and create a first table with a single file input field, which gives me an error when I upload a file.

## Version Info
  - v6.4.3
  - PHP version: PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
  - MySQL version: mysqld  Ver 5.7.19-0ubuntu0.16.04.1 for Linux on x86_64 ((Ubuntu))
  - Web server: nginx version: nginx/1.10.3 (Ubuntu)
  - OS name and version: Ubuntu 16.04 (the one you get from digital ocean currently)

## Expected Behavior

I guess it saves the file :)

## Actual Behavior

Tried uploading a tiny jpeg with results in this error message:

```
Error
Error: Uncaught SyntaxError: Unexpected end of JSON input
File: https://cms.strandrover.com/tables/media/new
Line:1
```

The js console says:

<img width="930" alt="screen shot 2017-10-10 at 16 01 58" src="https://user-images.githubusercontent.com/1119139/31390495-5d377378-add4-11e7-8112-57c4960c680a.png">

## Steps to Reproduce
 1. Create a table with a single file input
 2. Grab this JPG: ![all-the-things](https://user-images.githubusercontent.com/1119139/31390661-c6eb05c8-add4-11e7-9e20-db3cbe8c92d4.jpg)
 3. Drag into the input thing
 4. Be delighted to see a preview of the file
 5. Hit Save and see the error message 

## Schema Dump, Logs, or Screenshots

![2017-10-10 16 12 17](https://user-images.githubusercontent.com/1119139/31391119-ef78518e-add5-11e7-9021-ac3ce606c9e0.gif)

[directus_2017-10-10.sql.gz](https://github.com/directus/directus/files/1372220/directus_2017-10-10.sql.gz)

This is all the info I can think of … @rijkvanzanten I this what you had in mind? 
THANK YOU GUYS!

**Comment by rijkvanzanten** [comment]
This is perfect @nilsborg, thanks!

**Comment by WellingGuzman** [comment]
Hey @nilsborg, can you check if there's a log in your `api/logs` directory? also can you show us your nginx server configuration?

**Comment by nilsborg** [comment]
Sure thing!

nginx "vhost" (or whatever thats called with the fancy folks of nginx ;)

```
server {
	root /var/www/cms.strandrover.com;

	index index.php index.html index.htm index.nginx-debian.html;

	server_name cms.strandrover.com;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		# BACKUP try_files $uri $uri/ =404;
		try_files $uri $uri/ /index.php$args;
	}

	# pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
	#
	location ~ \.php$ {
		include snippets/fastcgi-php.conf;
	#
	#	# With php7.0-cgi alone:
	#	fastcgi_pass 127.0.0.1:9000;
	#	# With php7.0-fpm:
		fastcgi_pass unix:/run/php/php7.0-fpm.sock;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
        	fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        	include fastcgi_params;
	}

	# deny access to .htaccess files, if Apache's document root
	# concurs with nginx's one
	#
	location ~ /\.ht {
		deny all;
	}

	location /api {
    		if (!-e $request_filename) {
        		rewrite ^/1/extensions/([^/]+) /api/api.php?run_extension=$1 last;
    		}
    		rewrite ^ /api/api.php?run_api_router=1 last;
	}

	location ~ ^/(media|storage)/.*\.(php|phps|php5|htm|shtml|xhtml|cgi.+)?$ {
    		add_header Content-Type text/plain;
	}

	location ~* /customs/endpoints/ {
    		deny all;
	}



    	listen 443 ssl http2; # managed by Certbot
	ssl_certificate /etc/letsencrypt/live/cms.strandrover.com/fullchain.pem; # managed by Certbot
	ssl_certificate_key /etc/letsencrypt/live/cms.strandrover.com/privkey.pem; # managed by Certbot
    	include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
}
```

nginx conf:

```
user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
	worker_connections 768;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	# server_tokens off;

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;
	gzip_disable "msie6";

	# gzip_vary on;
	# gzip_proxied any;
	# gzip_comp_level 6;
	# gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}
```

Logs attached (everything I could find in that dir)

[2017-09-15.log](https://github.com/directus/directus/files/1373646/2017-09-15.log)
[development.log](https://github.com/directus/directus/files/1373647/development.log)

**Comment by nilsborg** [comment]
Guys … thanks for the rubber ducking. Literally the readme file in the api/logs dir tipped me off, that I had a permissions problem. It was not writeable for the www-data user ...

**Comment by nilsborg** [comment]
Now I just get the same funky error message with files that are too big (how @rijkvanzanten led me to believe) Any idea what to do about that?

**Comment by rijkvanzanten** [comment]
Could you check the `max_upload_size` setting in your `php.ini`?

**Comment by nilsborg** [comment]
Ah ok so I didnt find that exact option but this one:
```
; Maximum allowed size for uploaded files.
; http://php.net/upload-max-filesize
upload_max_filesize = 20M
```

but now I get this:

![screen shot 2017-10-11 at 15 10 24](https://user-images.githubusercontent.com/1119139/31442327-558e2c08-ae96-11e7-8ea2-c0209b7d51e4.png)

**Comment by rijkvanzanten** [comment]
There might be a similar option for the whole maximum post request size. I think it's something like `post_max_size`?
