### ISSUE TITLE
Sort order doesn't work for O2M

### ISSUE THREAD

**Issue by hamishjohnson** [directus/directus#18750]
### Describe the Bug

When using the relationship sort field when createing a O2M relationship (advanced > relationship> sort field), the interface seems to ignore that actual ordering when the relationships are dragged in the list view.

When you drag the items, it does actually update the sort order in the DB, but it doesn't update in the UI, so it's impossible to actually get any meaningful sort out of it, since it always just gets overwritten.

I found this issue which seems to describe exactly what happens, just with M2A https://github.com/directus/directus/issues/3750

I'm using directus 9.24.0

### To Reproduce

Create master collection
Create subcollection
Add O2M relationship with a sort field in the advanced section
Once created, add some dummy data and drag the subcollection items in the master collection item

### Directus Version

v9.24.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
This seems to work as expected in the latest release (10.2.1) 👍🏻
