### ISSUE TITLE
useItems() Composable does not work with custom Modules

### ISSUE THREAD

**Issue by NecoHorne** [directus/directus#18767]
### Describe the Bug

The useItems composable from the Directus extensions does not work in custom modules, always returns null or empty array. 

### To Reproduce

My custom module is in JS if that makes a difference. 

I import it in my component file
```js
<script>
...
import { useItems  } from '@directus/extensions-sdk';
...
```

in the setup method I tried testing it with my own collections and directus collections, went to the source code of the composable and its test file to see if I was maybe using it wrong and copied a test from there, still returning null. 

```js
  setup(){
    // const { items, itemCount } = useItems(ref('commission_line_items'), {limit: 50});
    // console.log(unref(items));
    // console.log(unref(itemCount));

    const { totalCount, itemCount } = useItems(ref('directus_files'), {
      fields: ref(['*']),
      limit: ref(1),
      sort: ref(null),
      search: ref(null),
      filter: ref(null),
      page: ref(1),
    });

    console.log(unref(totalCount));
    console.log(unref(itemCount));
  },
```

I have tested it from Directus v10.0.0 through to latest version v10.2.1 all same result. 

in all instances I have matched the module @directus/extensions-sdk version with the main project Directus version.

### Directus Version

10.2.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
This snippet you have shared will always return `null` for both as it logs the initial default value of `null` and never updates when the store is hydrated.

does it update if you watch the values?
```
  setup(){
    // const { items, itemCount } = useItems(ref('commission_line_items'), {limit: 50});
    // console.log(unref(items));
    // console.log(unref(itemCount));

    const { totalCount, itemCount, loading, error } = useItems(ref('directus_files'), {
      fields: ref(['*']),
      limit: ref(1),
      sort: ref(null),
      search: ref(null),
      filter: ref(null),
      page: ref(1),
    });

    watch(totalCount, (val) =>console.log(val));
    watch(itemCount, (val) =>console.log(val));
    watch(loading, (val) =>console.log(val ? 'LOADING...' : 'LOADED!'));
    watch(error , (val) =>console.error(val));
  },
  ```
  
  Happy to re-open when more information becomes available 😄
