### ISSUE TITLE
Exception throw when using filter hook with varchar primary key

### ISSUE THREAD

**Issue by dlaprade** [directus/directus#1876]
## Version Info
  - Directus version and branch: 6.4.3
  - PHP version: 7
  - MySQL version: 
  - Web server:  Apache
  - OS name and version: Linux

## Expected Behavior
If I have a table with primary key as varchar and a filter hook to set the ID, I expect to have successful save for a record if the filter is setting the ID.

## Actual Behavior
I am receiving an error in the Directus UI. Below is the error listed in the api logs.

## Steps to Reproduce
 1. Create new table
 2. Add some columns
 3. Update ID column to use varchar with length 36
 4. Save
 5. Click table to enter new data
 6. Enter values in columns ( Do not enter data in ID )
 7. Save.

## Schema Dump, Logs, or Screenshots

![screen shot 2017-10-10 at 8 49 34 am](https://user-images.githubusercontent.com/7399336/31396327-fe382534-ad97-11e7-934e-9adc77ac3e9b.png)
[Directus_GUID_error-on-save.txt](https://github.com/directus/directus/files/1372555/Directus_GUID_error-on-save.txt)
[Direcuts_GUID-filter-hook.txt](https://github.com/directus/directus/files/1372556/Direcuts_GUID-filter-hook.txt)

**Comment by WellingGuzman** [comment]
Hey @dlaprade, the issue is actually how you are using the UUID library, you have to convert it to string instead of passing the object.

```php
$uuid = Uuid::uuid4()->toString();
```
