### ISSUE TITLE
Image overflows container single_file interface

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1877]
## Version Info
  - Directus version and branch: develop 50bb84a76fafa1eb9eaf6084a4dd7cd3b377e44b
  - Browser: Safari 11.0.1, macOS High Sierra 10.13.1 Beta (17B25c)

## Expected Behavior
Image fits nicely in box

## Actual Behavior
Image refuses to stay in its box, and is quite rude about it.

## Steps to Reproduce
 1. Create a table with a single_file interface
 2. Select an existing file from the file library

## Schema Dump, Logs, or Screenshots
<img width="557" alt="screen shot 2017-10-10 at 4 09 00 pm" src="https://user-images.githubusercontent.com/9141017/31408300-092350f2-add6-11e7-8ff1-952d89649826.png">

**Comment by rijkvanzanten** [comment]
_Bonus fix_: there is some margin to the left of the image box which seems a bit.. off

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/0f64a592d55b824bf9232625f5fe436b02aa9764

That margin on the left I think is the shadow that makes it look a bit off

**Comment by rijkvanzanten** [comment]
@WellingGuzman I was referring to this space 😉 
<img width="557" alt="31408300-092350f2-add6-11e7-8ff1-952d89649826" src="https://user-images.githubusercontent.com/9141017/31826480-2f5c88ce-b583-11e7-9b2c-4ebc00b10873.png">

@benhaynes What do you think about this design wise, should it align with the button and the title, or is this the way it was intended to be?

**Comment by WellingGuzman** [comment]
@rijkvanzanten Upsilon! I see it now 😬

**Comment by benhaynes** [comment]
Ahh, this was probably from when we were centering things. If everything will be left-aligned then we should be able to get rid of this! Rijk – would you do the honor?

**Comment by rijkvanzanten** [comment]
I'll 🔥 this 🐛 with ❤️
