### ISSUE TITLE
docker pull error

### ISSUE THREAD

**Issue by raelcv** [directus/directus#18776]
### Describe the Bug

I'm getting an error on docker pull:
 sudo docker pull directus/directus:latest
Trying to pull repository docker.io/directus/directus ...
manifest for docker.io/directus/directus:latest not found

### To Reproduce

 sudo docker pull directus/directus:latest

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
It is available on the docker hub (https://hub.docker.com/r/directus/directus/tags) and i am able to pull it in locally 
![WindowsTerminal_SR2qmd01jk](https://github.com/directus/directus/assets/9389634/b674e8c3-4357-4bfe-ad79-381829d783c2)

I suspect this may be due to network configuration but happy to re-open this when more information becomes available.

**Comment by raelcv** [comment]
Same error

**Comment by raelcv** [comment]
[root@vps ~]# docker pull directus/directus:10.1
Trying to pull repository docker.io/directus/directus ...
10.1: Pulling from docker.io/directus/directus
Digest: sha256:b31711d247951ee26c2c512410b35163b9f6ac3b16d7599d852d08b75f772d54
Status: Downloaded newer image for docker.io/directus/directus:10.1
[root@vps ~]# docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
docker.io/directus/directus   10.1                3015352a9756        13 days ago         405 MB
docker.io/directus/directus   latest              3015352a9756        13 days ago         405 MB
[root@vps ~]# docker pull directus/directus:latest
Trying to pull repository docker.io/directus/directus ...
manifest for docker.io/directus/directus:latest not found

*I didn't try to remove the one already downloaded, I need the service working for now.

**Comment by br41nslug** [comment]
seems `directus:latest` was cached locally to the 10.1 version. you should be able to safely remove the latest tag if there arent any active dockers using that tag. I do recommend running on specific version tags over using the `latest` tag.
