### ISSUE TITLE
Saving color as RGB throws error

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1878]
## Version Info
  - Directus version and branch: develop 50bb84a76fafa1eb9eaf6084a4dd7cd3b377e44b
  - Browser: Safari 11.0.1, macOS High Sierra 10.13.1 Beta (17B25c)

## Expected Behavior
Saving an item with a color interface.. saves the item.

## Actual Behavior
Directus throws an error:

```
Server Error
Attempting to write an array as the value for column `site_settings`.`accent_color.
```

## Steps to Reproduce
 1. Add a color interface
 2. Set the input to `hex`, the output to `rgb`
 3. Add some value and save the item

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/7ef3206141a778cc44be87d1904ee8903077f4c6
