### ISSUE TITLE
Very slow loading the app, particularly "/fields" and "/relations" endpoints

### ISSUE THREAD

**Issue by mrchristophy** [directus/directus#18789]
### Describe the Bug

I've made a fresh install of Directus on a VPS using the NPM package (no Docker), connecting to a MariaDB database. This works fine locally, but on the VPS it's very slow to do anything. You can see in the screenshot it's particularly taking a long time to fetch /fields and /relations. I'm not sure if this is an issue with Directus or the database, although it's the same database setup I have used on countless other non-directus, intensive websites so I can't see how that could be a problem.

If anyone could give me an idea of how to debug this further I will gladly give more information, or if you have any idea what's causing it, it would be much appreciated!

![Monosnap Article 2023-06-01 17-02-32](https://github.com/directus/directus/assets/6993675/c00019eb-24b3-48f2-b0d2-fe7a4a4c8269)

### To Reproduce

Install Directus using npm package, connect to MariaDB database

### Directus Version

10.2.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
Unfortunately we cannot provide support for arbitrary hosting outside our cloud. Please use the Discord server for questions about hosting vendors or non-docker installations.

Having said that my first suspect is not enough resources available, low memory or slow disks is often a footgun for databases.
