### ISSUE TITLE
Versions mix

### ISSUE THREAD

**Issue by Pachat** [directus/directus#18795]
Not quite fixed. 

On a clean install of `10.2.1`  
- correctly no request for update after `npx directus start`

but
- `10.2.0` is incorrectly shown in the UI
- `npx directus -v` still gives `11.0.1` _(at least on my development computer and on the server)_.

despite `node_modules/directus/package.json` contains
```
{
  "name": "directus",
  "version": "10.2.1",
  ...
  "dependencies": {
    "@directus/api": "11.0.1",
    "@directus/update-check": "11.0.0"
  },
  ...

```
This makes it difficult to automate updates on purpose.

BTW, why `npx directus -v` takes so much time ~10s.?
Wouldn't be much faster (and more accurate) to read the version from `node_modules/directus/package.json`?

_Originally posted by @Pachat in https://github.com/directus/directus/issues/18782#issuecomment-1571599180_

**Comment by johnny9144** [comment]
I face the same issue, I just add `force` param to ignore version check for a workaround, however, it's quite insecure...

**Comment by Pachat** [comment]
At least, until this bug is fixed, instead of
`# npx directus -v > version.txt`
I use
`grep -o '"version": *"[^"]*"' "$script_dir/../../node_modules/directus/package.json" | sed 's/"version": *"\([^"]*\)"/\1/' > version.txt`
which, BTW, is about a hundred time faster.

**Comment by Pachat** [comment]
Still there with `10.4.0` out there a few days ago.
The message at Directus Start is still
```
 Update available!                 
                                                   
                     10.2.1 → 10.3.1
```

**Comment by Pachat** [comment]
To day, as published version is v10.4.2, when starting Directus, I get
`Update available: 10.2.0 -> 12.0.2`

**Comment by Pachat** [comment]
After updating to 10.4.2 locally, I get
![versions 10 4 2](https://github.com/directus/directus/assets/13746133/236f061a-a2d7-49aa-b122-7f1fc8b3e7e0)
which shows on the same installation, depending on how the version is requested:

- 10.2.0
- 10.4.2
- 10.2.0 => 12.0.2
- 10.1.1

**Comment by Pachat** [comment]
From today, 05/07/23 I reinstalled from scratch the v10.4.2
Only one bug remains:
`npx directus -v` gives '12.0.2' instead of '10.4.2' given by all other means.
