### ISSUE TITLE
Server error when running flow: message": "Cannot destructure property 'result' of '(intermediate value)' as it is undefined

### ISSUE THREAD

**Issue by Eggwise** [directus/directus#18794]
### Describe the Bug

I created a flow to bulk update statusses in a "match" table.
When i select matches and press update the flow runs and it works. But it is displaying an error anyway..

![image](https://github.com/directus/directus/assets/20506046/d912aee1-911b-4623-b753-659165895127)

![image](https://github.com/directus/directus/assets/20506046/a96becfe-516f-4479-ba18-57f8d16ad11a)

### To Reproduce

- create new flow. manual trigger
- second step update records based on ids selected before triggering flow

### Directus Version

v10.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

Server logs:

```
[14:26:14] POST /flows/trigger/97f32616-28df-4cd9-bb9b-6a1f81c14dd9 500 35ms
[14:26:14.922] ERROR: Cannot destructure property 'result' of '(intermediate value)' as it is undefined.
    err: {
      "type": "TypeError",
      "message": "Cannot destructure property 'result' of '(intermediate value)' as it is undefined.",
      "stack":
          TypeError: Cannot destructure property 'result' of '(intermediate value)' as it is undefined.
              at file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/controllers/flows.js:16:13
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    }
```

**Comment by licitdev** [comment]
Fixed in `v10.2.0` via #18741.
