### ISSUE TITLE
Text input throws regex error (without regex being used)

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1879]
## Version Info
  - Directus version and branch: develop 50bb84a76fafa1eb9eaf6084a4dd7cd3b377e44b
  - Browser: Safari 11.0.1, macOS High Sierra 10.13.1 Beta (17B25c)

## Behavior
Saving an item which contains a `text_input` interface with a character whitelist throws an error on save:

```
Error
Error: SyntaxError: Invalid regular expression: range out of order in character class
File: http://directus.dev/app/core/interfaces/text_input/component.js?bust=50bb84a76fafa1eb9eaf6084a4dd7cd3b377e44b
Line:103
```

## Steps to Reproduce
 1. Add `text_input` interface to table
 2. Set the validation to `character_whitelist` `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~:/?#[]@!$&'()*+,;=`.`
 3. Add some valid characters
 4. Save the item

**Comment by WellingGuzman** [comment]
I didn't know what approach you wanted to take, but in the meantime I fixed it by fixing the regex (escaping the characters).

Ref: https://github.com/directus/directus/commit/76f554732d5448ec8f4531ca18c92a4275a4d0e8
