### ISSUE TITLE
Column deleted notification wrong name

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1880]
## Version Info
  - Directus version and branch: develop 17aad8fa5637b14c572c3f31a2d4a5ca59aa11f0
  - Browser: Safari 11.0.1, macOS High Sierra 10.13.1 Beta (17B25c)

## Behavior
Deleting a column shows `Column "%{column_name}" was removed`

## Steps to Reproduce
 1. Create and delete a column in table settings

<img width="354" alt="screen shot 2017-10-10 at 5 46 09 pm" src="https://user-images.githubusercontent.com/9141017/31412470-38fa477e-ade3-11e7-838b-b0ab95486200.png">

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/5ce02d371465e8ce07e634453f7319ef6cd4c066
