### ISSUE TITLE
Flows - Read Data and filter: invalid input syntax for type timestamp with time zone

### ISSUE THREAD

**Issue by LevinGermann** [directus/directus#18806]
### Describe the Bug

Time variable $NOW(+/- adjustment) fails for "Read data" Flow operation

Apparently this has been fixed for this issue: https://github.com/directus/directus/issues/13745
But it has reappeared. I know we're not using the latest version but I don't see any release-notes for the one newer version related to this.

<img width="1052" alt="image" src="https://github.com/directus/directus/assets/9347206/223e85b7-bc5c-472d-b51e-808322e2482a">

<img width="835" alt="image" src="https://github.com/directus/directus/assets/9347206/8d43d347-db94-4435-a553-2ea569247f38">

This leads to:

```
{
  "length": 174,
  "name": "error",
  "severity": "ERROR",
  "code": "22007",
  "where": "unnamed portal parameter $1 = '...'",
  "file": "datetime.c",
  "line": "3803",
  "routine": "DateTimeParseError"
}
```

and the log on the Postgres Server:

[1-1] db=directus,user=directus ERROR: invalid input syntax for type timestamp with time zone: "$now(-1 days)"

### To Reproduce

Create a flow to read data from a table and filter it based on a time variable like $NOW()

### Directus Version

10.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
The `$NOW(...)` function is case sensitive, it looks like you are using lower case.
