### ISSUE TITLE
Cannot POST /collections

### ISSUE THREAD

**Issue by SalveEdoki** [directus/directus#18817]
### Describe the Bug

Wether I use an account with a role that has all collections permissions or an admin with his token, I can't create collection throught REST API

```json
{
    "errors": [
        {
            "message": "You don't have permission to access this.",
            "extensions": {
                "code": "FORBIDDEN",
                "stack": "Error: You don't have permission to access this.\n    at CollectionsService.readOne (file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/services/collections.js:258:19)\n    at async file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/controllers/collections.js:21:24"
            }
        }
    ]
}
```

### To Reproduce

1. Create a user
2. Generate token for the user
3. Create a role
4. Allow all direct us system collection permissions
5. Send request (error)
6. 

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
The /collections endpoint is only accessible to Admin users 👍🏻
