### ISSUE TITLE
Return HTTP 500 when logfile can't be written

### ISSUE THREAD

**Issue by wittwerch** [directus/directus#1881]
## Version Info
  - Directus version and branch: 75ec6debf62831d1397f9275056d5831272874a7
  - PHP version: 7.1

## Expected Behavior
- Directus should answer with a HTTP 500 and a error message.

## Actual Behavior
- Directus returns a HTTP 200 with a stack trace.

## Steps to Reproduce
1.  Make the logfile read-only (chmod 400 api/logs/2017-10-11.log)
2. Force a log entry to be written (call /api/1.1/tables/user/rows for example)

## Schema Dump, Logs, or Screenshots
<img width="1268" alt="screen shot 2017-10-11 at 11 54 56" src="https://user-images.githubusercontent.com/1575445/31434073-a145344a-ae7b-11e7-8569-88a48385d37c.png">

**Comment by cgarnier** [comment]
200 means everything is ok.
500 with a json error containing a stacktrace sounds better.

**Comment by WellingGuzman** [comment]
Hey @wittwerch, everything under "Expected Behavior" is a mixed of the steps and the expected behavior?

Thanks for reporting this.

**Comment by wittwerch** [comment]
@WellingGuzman Updated the issue, was a bit in a rush when reporting it :)

**Comment by WellingGuzman** [comment]
I assumed @wittwerch, thanks!

**Comment by WellingGuzman** [comment]
On `develop` branch it was actually throwing 404 error, now it throws an 500 Internal Server error.

Closed by https://github.com/directus/directus/commit/4d7573b78864be0307c8c515aeaf1c046f88b28f
