### ISSUE TITLE
languages table in /admin/settings/data-model

### ISSUE THREAD

**Issue by anime777** [directus/directus#18816]
### Describe the Bug

1. add a  new fied to  languages table ,  this field can be edited in admin dashboard , but it not show up in API respone 's translations object

`?fields=blog_id,title,translations.*`
2.   it seems not support custom language code,   when  edit code field  value in  languages collection , my custom code can not be saved ,    en-US => en ,   ja-JP => ja

### To Reproduce

http://127.0.0.1/admin/settings/data-model

### Directus Version

image: directus/directus:10.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
I'm assuming that you're using the auto-generated translations setup, in which case the languages table is one more level deep from the translations. Try `translations.*.*`.
