### ISSUE TITLE
Flow hooks collection list includes folders

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#18823]
### Describe the Bug

When creating a hook-flow the collections list contains the folders from the collections.

### To Reproduce

- Create a folder for collections
- create a flow
  - select "hooks"
  --> the folder will be listed in the collections  

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by Boegie19** [comment]
this one should be closed since 19007 was merged

**Comment by br41nslug** [comment]
Well spotted 🚀
