### ISSUE TITLE
Table sort default value should be 0 not null

### ISSUE THREAD

**Issue by cgarnier** [directus/directus#1882]
## Version Info
  - Directus version and branch: build
  - PHP version: 7
  - MySQL version: 5 
  - Web server: docker-directus 
  - OS name and version: ubuntu

## Expected Behavior
in the response of  /api/1.1/tables/<table>, the value of default_value in the sort column description should be 0, not null

## Actual Behavior
Actualy it s null. In the database table, sort cant be null. The default value must be a valid value

## Steps to Reproduce
 1. Create a table 
 2. POST /api/1.1/tables/<table>/rows an entity with the default values
 3.

**Comment by WellingGuzman** [comment]
Hey @cgarnier what do you mean? the `/api/1.1/tables` endpoint list tables name only.

The default value of the sort column is `0`.
