### ISSUE TITLE
Field "x" already exists in collection "directus_users"

### ISSUE THREAD

**Issue by delivey** [directus/directus#18838]
### Describe the Bug

When adding a new field (in the directus_users table, not sure if same issue for others), I get an error saying it already exists. It doesn't exist, and hasn't ever existed.

I think the issue might be that I sent payloads to create a field with the same field name, but all of them failed.

### To Reproduce

1. Add a field using a POST request, but make sure the type and data_type values are null.
2. Try to create a field using the web interface.

It will show that the field already exists, probably because it has a type of null, even though it didn't get created.

### Directus Version

v9.22.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
I haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻
