### ISSUE TITLE
Flows stopped to work

### ISSUE THREAD

**Issue by octavioamu** [directus/directus#18836]
### Describe the Bug

Im not sure if something to my side or general but after updating from 9.X to 10.2 all my flows using hooks (is the only ones Im using) stopped to work, On the server console I have this.

```
[15:24:16.716] WARN: An error was thrown while executing action "posts.items.delete"
﻿[15:24:16.716] WARN: structuredClone is not defined
﻿err: {
﻿"type": "ReferenceError",
﻿"message": "structuredClone is not defined",
﻿"stack":
﻿ReferenceError: structuredClone is not defined
﻿at redact (file:///app/node_modules/@directus/api/dist/utils/redact.js:11:19)
﻿at FlowManager.executeFlow (file:///app/node_modules/@directus/api/dist/flows.js:281:31)
﻿at runMicrotasks (<anonymous>)
﻿at processTicksAndRejections (node:internal/process/task_queues:96:5)
﻿at async Promise.all (index 0)
﻿}
```

### To Reproduce

Create a flow using hooks add a console log, trigger by interacting with the collection
> No trigger logs

### Directus Version

v10.2.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Directus is targeting the active LTS version of Node.js which currently is v18 (see https://github.com/nodejs/release#release-schedule). Please update to this version.
