### ISSUE TITLE
Insights: Plot labels do not respect interface display templates

### ISSUE THREAD

**Issue by DustinBracy** [directus/directus#18830]
### Describe the Bug

First I want to say that I _love_ the new insight modules!  

However, creating a new plot only shows the ID for relationship fields in a collection.  This is a problem for fairly normalized databases, where many tables have foreign key relationships.  The labels end up being all UUIDs, which are not very user friendly.  

The ability to select related column names, or even respect the default display template configured on the collection relationship field would go a very long ways into making plots more usable  (e.g. user created should map to first name last name, as it does everywhere else). 

![directus plot](https://github.com/directus/directus/assets/34081222/a7f5a2b6-1907-4957-a027-ac9dcf9b67f4)

### To Reproduce

1. Create an insights dashboard
2. Add a bar chart
3. Select a collection, add user_created to X axis, and count of ID of some field for Y axis.
4. Configure display template as first_name last_name for user_created
5. See IDs as labels

![Screenshot 2023-06-06 183043](https://github.com/directus/directus/assets/34081222/ca8d9db9-8692-4efe-a504-3d351f699bde)

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
As this is technically "working as intended" would you mind creating a [Feature Request](https://github.com/directus/directus/discussions/categories/feature-requests) for this?
