### ISSUE TITLE
Delete files from storage from directus flow.

### ISSUE THREAD

**Issue by AxeemHaider** [directus/directus#18835]
### Describe the Bug

I have a collection in which I can upload many files. When I unlink files from there it does not remove from storage. I try to remove them by creating flow but I can only remove them from `directus_files` not from local storage. Is there any way I can remove them from local storage as well. 

While on the other hand if you remove any files from `library` module it also remove them from local storage. I want to achieve same result with other data models. 

### To Reproduce

1. Create data model with filed `files` which will accept multiple files
2. upload some files
3. remove one of them
4. removed file still be available in `library` module. 

### Directus Version

v10.2.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by ConnorSimply** [comment]
@AxeemHaider When you delete the file item from `directus_files` in the AdminApp/DataStudio does it delete the file from the storage adapter? (Local, S3, etc)

**Comment by AxeemHaider** [comment]
> Removing items from `directus_files` **does not delete** from storage adapter (Local, S3 etc)

I'm using **flow operation** to delete items from `directus_files`. But if you use API or AdminApp/DataStudio Gallery to delete files it will remove them from `directus_files` as well as from storage. 

I have checked code and under the hood gallery delete button directus is using api to delete files `api.delete('/files')` which delete the files from storage and from `directus_files` collection. But on the other hand in flow operations there is **Delete Operation** which delete only entries from collections. For example you can use **Delete Data operation** to delete items from `directus_files` which delete entries from collection only. Because it does not know `directus_files` collection is special collection which is link to storage as well. For `directus_files` it should delete entry as well as item from storage. 

Only possible solution right now is to delete it using API `api.delete('/files')` but problem with this is there is no access to **api** in flow operations. At least I'm not able to find and flow operation in which I can access `api` object.

**Comment by ConnorSimply** [comment]
@AxeemHaider Ah I see, yes that is something we should fix. In the meantime as a work around you can use the REST API with the Request Operation to delete files. https://docs.directus.io/app/flows/operations.html#webhook-request-url

**Comment by AxeemHaider** [comment]
@ConnorSimply need more info, as I know **Webhook/Request URL** operation is for external URLs. How can I call internal directus url. I tried it like this.

1. In Method field select `DELETE`
2. In URL field add `/files/file-uuid`

This is not working, operation fail, I tried it with even full URL `http://localhost:8055/files/file-uuid` this one is also not working. 
I tried it with `GET` method `/item/collection_name` which is also not working. 

I think operation fails because these are protected routes. And we are not passing any access token in this example. Directus does not know these are **internal API URLs** and does not pass automatically access token into it. 

Solution: There should be separate operation to call internal APIs or **Webhook/Request URL** operation should know if URL 
is start from `/` (_same we are using with link buttons_) then this is internal API call and pass access token as well.

**Comment by AxeemHaider** [comment]
Weird error: I tried **Webhook/Reuest URL** with static access token. But it also not working it seems directus not able to reach to end point I tried it `/items/collection_name`, `http://0.0.0.0:8055/items/collection_name` and `http://localhost:8055/items/collection_name` none of them is working. I think it's not able to reach at **localhost** because it works on other live URLs. I have checked code it's very simple just getting `axios` instance and send request to url. Not able to find what is problem. Maybe directus running it in **sandbox** that's why its not able to reach at **localhost**

**Comment by br41nslug** [comment]
@AxeemHaider IPs that resolve to localhost are blocked by default for security. Did you update the `IMPORT_IP_DENY_LIST` environment variable?

**Comment by AxeemHaider** [comment]
@br41nslug  No, I didn't update any `IMPORT_IP_DENY_LIST`.  So, if localhost is blocked then how can I allow for development ?

**Comment by rijkvanzanten** [comment]
There are currently no built-in operations for file library modifications. Feel free to open a new feature request to have that added in the future! 🚀
