### ISSUE TITLE
Calendar Layout not displaying items

### ISSUE THREAD

**Issue by w0kyj** [directus/directus#18848]
### Describe the Bug

Calendar layout not showing days, items, etc. Bottom half of the layout is blank instead of showing month/week/day/list view

### To Reproduce

Open any collection with date field(s)
If needed, set the Calendar Layout
    - Only the headings will show
    - Bottom section displays blank

<img width="1110" alt="Screenshot 2023-06-08 at 7 43 02 AM" src="https://github.com/directus/directus/assets/40695629/b91a5aac-18a6-441a-8a9d-987ad4fb67e8">

### Directus Version

v10.2.1

### Hosting Strategy

Directus Cloud

**Comment by com-pote** [comment]
I run the same issue, and the map layout just display a blank page

**Comment by com-pote** [comment]
I saw this thanks to @br41nslug :

Edit custom css on your project settings and add :

```css
.private-view .content-wrapper{
   height:100%!important;
}
```
