### ISSUE TITLE
Can't press enter in radio buttons settings modal

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1884]
## Version Info
  - Directus version and branch: develop 5ce02d371465e8ce07e634453f7319ef6cd4c066
  - Browser: Safari 11.0.1, macOS High Sierra 10.13.1 Beta (17B25c)

## Expected Behavior
Pressing enter in the JSON settings field enters a new line

## Actual Behavior
`Rijk used Enter, it wasn't very effective...`

## Steps to Reproduce
 1. Add a `radio_buttons` interface to a table
 2. Try adding a new line to the JSON options
 3. Lay down, try not to cry, cry a lot

**Comment by WellingGuzman** [comment]
I'm not able to reproduce this issue @rijkvanzanten. Using Safari Version 10.1.1 (12603.2.4)

**Comment by rijkvanzanten** [comment]
Hmm, seems to work correctly now. Let's blame the #cache.
