### ISSUE TITLE
Export hangs UI

### ISSUE THREAD

**Issue by u12206050** [directus/directus#18842]
### Describe the Bug

When entering 6000 items into the items to export, the notice changes icon, but still states that the export will be downloaded to my device once completed.

However, once I start the export I soon get an email (with nothing in it, another issue) but then also nothing happens on the admin ui side of things, not file gets downloaded or anything. It just hangs and I can't even close the modal. Only way to escape is by refreshing.

### To Reproduce

Start and export of 6000 items, wait a bit at first, ideally until after you get notified by email that export is finished.

Try and navigate / close / or view any files being downloaded.

### Directus Version

10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by ConnorSimply** [comment]
@u12206050 Is the file being exported into your directus files collection?

> **Exporting to File Library**
> 
> When downloading 2,500 or more Items, you will be required to download into the Directus Project's File Library. After exporting, go to the File Library to download your file locally.

**Comment by u12206050** [comment]
Yes it is

**Comment by u12206050** [comment]
Related #18957

**Comment by u12206050** [comment]
I can confirm that this was not an issue on 10.0.0. But I consistently get this issue on 10.2 and 10.3

**Comment by u12206050** [comment]
I am aware that on the latest main Directus branch I am unable to reproduce this issue. Although I can't find anything that I would think has altered export in anyway.
I have also tested now on some other less complex Directus projects and even removed all custom extensions, yet still get the same issue from 10.2 and 10.3

![Screenshot 2023-06-27 at 08 54 51](https://github.com/directus/directus/assets/6641242/c4402df0-0e0e-4ca2-8e2e-2adec31486d5)

**Comment by rijkvanzanten** [comment]
> I am aware that on the latest main Directus branch I am unable to reproduce this issue. Although I can't find anything that I would think has altered export in anyway.

When running it from the `main` branch, are you using `pnpm run dev`, or making a production build first and running that? Sounds like this might be a dev vs prod bug in Vue itself 🤔
