### ISSUE TITLE
Kanban Doesn't Respect Read only Status

### ISSUE THREAD

**Issue by drupalshift** [directus/directus#18858]
### Describe the Bug

When you have a model that has a condition to disable the editing of status field 
You can change the status by dragging the entry in the Kanban layout 

Is this expected? 
Shouldn't Kanban respect the "Group By" field conditions?

### To Reproduce

Create a Model 
Create a Dropdown named Status with a few options like Step 1, Step 2, Step 3 
Disable Edition Value in the dropdown

Switch to Kanban layout and Group by Status

Now you can drag and drop the entries while you have disabled the editing of status field

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Field conditions set frontend form interface options they are not doing actual API validation. The Kanban layout doesnt render an interface for the groupBy field so there is no `input` to apply settings like "readonly" or "hidden".

Try using validation instead 😄

**Comment by d3v1an7** [comment]
Just ran into this myself. For anyone else looking for a potential workaround, I modified the user role to disallow editing of `Status` (the readonly field I was using for groupBy).

Users can still drag/drop, but the status will not change on drop, and the board resets to current state on a page refresh.

**Comment by d3v1an7** [comment]
@br41nslug I had a poke around validation settings for the field, but I couldn't figure out how that would help in this situation -- that only seems to fire a specific message for a specific state, and I did't see a way to identify/catch/validate a _change_ in status (i.e. going from Draft to Publish)

I'm probably missing something though, so if you have a moment to expand on your comment, that'd be ace!

**Comment by br41nslug** [comment]
@d3v1an7 The OP was using conditions to toggle the "readonly" option for field which is a frontend feature only applicable to the edit form on the detail page of an item and thus has no effect on layouts like Kanban or Cards. If you want to prevent status from being updated in any situation you need validation.
