### ISSUE TITLE
Columns of a table with complex primary key not recognised

### ISSUE THREAD

**Issue by rowild** [directus/directus#18852]
### Describe the Bug

Wile porting over an existing database into Directus 10, the columns of a table with complex primary keys – like PRIMARY KEY (uid_local,uid_foreign), – are not recognised. Opening the collection shows an empty interface, even though the DB tool (e.g. Sequel Ace) does show that coloums have been created with the respective keys.

Tables like these are important, though, for creating mm relationships.

### To Reproduce

install a local (docker) Directus 10.2.1 configuring it to use MySQL 5.7
via some mysql tool (I use VS Code's MySQL management tool by Dan Hun) import the 3 DB shown below
check the collection rwfm_mm_award_awardcategory
It would be expected that this table has at least 4 columns.

This SQL is used for the example:

```sql
CREATE TABLE `rwfm_award` (
  `uid` int(11) NOT NULL AUTO_INCREMENT,
  `pid` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `title` varchar(255) NOT NULL DEFAULT '',
  `path_segment` varchar(2048) DEFAULT NULL,
  `subtitle` mediumtext DEFAULT NULL,
  `date_received` varchar(10) NOT NULL DEFAULT '',
  `information` text DEFAULT NULL,
  `categories` int(11) NOT NULL,
  `rwfm_award_person` int(11) NOT NULL DEFAULT 0,
  `sorting` int(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`uid`),
  KEY `parent` (`pid`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `rwfm_awardcategory` (
  `uid` int(11) NOT NULL AUTO_INCREMENT,
  `pid` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `title` varchar(255) NOT NULL DEFAULT '',
  `title_without_spaces` varchar(255) NOT NULL DEFAULT '',
  `information` mediumtext DEFAULT NULL,
  `awards` int(10) UNSIGNED DEFAULT 0,
  `sorting` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `path_segment` varchar(2048) DEFAULT NULL,
  PRIMARY KEY (`uid`),
  KEY `parent` (`pid`),
  KEY `path_segment` (`path_segment`(185),`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `rwfm_mm_award_awardcategory` (
  `uid_local` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `uid_foreign` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `sorting` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `sorting_foreign` int(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`uid_local`,`uid_foreign`),
  KEY `uid_local` (`uid_local`),
  KEY `uid_foreign` (`uid_foreign`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
``` 

Here is a video showcasing the problem:
https://dl.rowild.at/directus_10_does_not_recognise_table_with_complex_primary_key.mp4

Further observation:
- Public permissions are set to true
- When creating a new coloum called, e.g., id and this field is defined as PRIMARY KEY (while the combined key is deleted), then the columns are recognised correctly.

### Directus Version
v10.2.1

### Hosting Strategy
Self-Hosted (Docker Image)

**Comment by rowild** [comment]
@rijkvanzanten I am very confused today, very sorry for that. Fact is this is indeed an issue, so I re-open it. Again: apologies for the back-and-forth!

**Comment by rowild** [comment]
Follow-up tests:

When removing the complex key and adding a new column with a unique PRIMARY KEY, using this table for an mm relation still does not work. This error is thrown:

```json
{
  "errors": [
    {
      "message": "alter table `rwfm_mm_award_awardcategory` add constraint `rwfm_mm_award_awardcategory_uid_foreign_foreign` foreign key (`uid_foreign`) references `rwfm_awardcategory` (`uid`) on delete SET NULL - ER_CANNOT_ADD_FOREIGN: Cannot add foreign key constraint",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

I am confused about the naming of the constraint, but I assume this is some internal logic by Directus creating that name.

Here is a video of the process what happens when only one column is used as PRIMARY KEY in a table that should be used as an mm table:
https://dl.rowild.at/directus_mm_table_with_unique_primkey_still_causes_problems.mp4

**Comment by br41nslug** [comment]
Composite primary keys are not currently supported by Directus.

**Comment by rowild** [comment]
@br41nslug That's a short message for a long time being confronted with that problem. Any chance this could be mentioned anywhere in the docu? Would save us all time!

**Comment by rowild** [comment]
Ok, I see that I oversaw. But my workflow comes from **integrating** Directus with an **existing DB**. In that scenario I do not look at the docu for creating a collection, since I am already of the opinion that I have them already. After all that's what Directus claims to excell at, right?
I believe this is not the only culprit one could encounter, relational tables in general might not be recognised at all – or are they? So I would suggest to provide a page with all those culprits one could encounter when trying to integrate an existing project. What do you think? (Or am I overseeing another page that already covers those limits?)

**Comment by br41nslug** [comment]
> I would suggest to provide a page with all those culprits one could encounter when trying to integrate an existing project.

I believe the "collections" page currently fills this space. Whether the table is pre-existent or not you still need to set it up within Directus.

**Comment by rowild** [comment]
But "set up" and "creating" are still 2 different things. I would vote for a dedicated page that informs about what to watch out for, when trying to "super impose" Directus on an existing project.

**Comment by br41nslug** [comment]
Sounds like it could be a good addition, feel free to make an issue for that with your docs improvements 😄 tagging in @phazonoverload as docs owner

**Comment by br41nslug** [comment]
Haha the "tagging thing" was just to make sure Kevin gets this issue in his notifications for visibility 😄

**Comment by phazonoverload** [comment]
I have been summoned - and I think the idea of creating a 'Using Directus With An Existing Database' document somewhere is a solid one to encapsulate all folks need to know. Not quite sure where it would go - but I'd be open to working on it with you!

**Comment by rowild** [comment]
@br41nslug Just to make sure my infos I collect are not wrong, would you mind to give me a quick feedback on this issue here, please (currently only referring to MxSQL): 

When a field is set to "unique" than Directus does not need a primary key anymore, right? While transfering a project, I came across a table which had an "id" field set to "PRIMARY KEY" and an "emailaddress" field set to "unique". When I do that in Directus, an error is thrown saying sth along the lines of "PRIMARY KEY already defined" (or "Only one primary key is allowed").

Thank you!

**Comment by rowild** [comment]
@br41nslug Thank you for clarifying!
