### ISSUE TITLE
Wrong default value for toggle interface

### ISSUE THREAD

**Issue by cgarnier** [directus/directus#1885]
## Version Info
  - Directus version and branch: (Or commit hash)
  - PHP version: 
  - MySQL version: 
  - Web server: (Ex. Apache, nginx or IIS?) 
  - OS name and version: 

## Expected Behavior
Toggle type should be a TINYINT(2)

## Actual Behavior
Default value on the new field creation is TINYINT(11)

**Comment by rijkvanzanten** [comment]
Hey @cgarnier! Thanks for the input. Could you in future issues please state why this change is wanted or required? Thanks!

**Comment by cgarnier** [comment]
It s tinyint(1) sorry.

Because to do that you need 2 value, a 0 or a 1 so only 1 bit is required.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/f55490063dfba5473b7b9a1573a6171c7ddb77d7
