### ISSUE TITLE
ItemsService is throwing a permissions error inside of a custom operation

### ISSUE THREAD

**Issue by mannyyang** [directus/directus#18850]
### Describe the Bug

When I try to use the provided ItemsService from the context parameter in a custom operation, it throws an error saying I don't have permissions to access it. I'm logged in as an admin user so I should have access to it.

### To Reproduce

```
export default defineOperationApi<Options>({
  id: "headlines-operation",
  handler: async (
    { adId },
    { env, logger, accountability, services, getSchema }
  ) => {
    const { ItemsService } = services;
    const schema = await getSchema();

    const adService = new ItemsService(COLLECTION.AD, {
      schema: schema,
      accountability: accountability,
    });

    try {
      const ad = await adService.readOne(adId);
      logger.info(`Ad ${ad}`);

      return { ad };
    } catch (error) {
      logger.error(`Error getting ad ${adId}: ${error}`);
    }
  },
});
```

### Directus Version

v10.1.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
You should double check 2 things:
- Does `adId` have a valid existing ID in it
- Does the flow have the required permissions, since you're using the `accountability` from the context that will use the permissions available to the trigger.

**Comment by mannyyang** [comment]
> You should double check 2 things:
> 
> * Does `adId` have a valid existing ID in it
> * Does the flow have the required permissions, since you're using the `accountability` from the context that will use the permissions available to the trigger.

![image](https://github.com/directus/directus/assets/3444220/e5f0a039-8271-4146-a84b-caf36cce964f)
I'm passing a valid existing ID and using a flow I created from an admin account.

Error response message
![image](https://github.com/directus/directus/assets/3444220/e3414cf4-0fbf-4d2a-8727-4e794feddc80)

Is there a way to set specific permissions on a flow?

**Comment by mannyyang** [comment]
@br41nslug a heads up on the comment above

**Comment by br41nslug** [comment]
It really depends on the flow you've build. Depending on what trigger is used either `null` (public permissions) or the authentication in the request (for webhooks/manual) will be the default accountability. If your operation needs to be elevated beyond the permissions the flow is runnig at you can add `admin: true` to your `accountability` object but do be aware of security considerations.
