### ISSUE TITLE
Flow "slugify" not working

### ISSUE THREAD

**Issue by rowild** [directus/directus#18861]
### Describe the Bug

The flow "slugify" - as shown in the Youtube video https://www.youtube.com/watch?v=Z4ua6CH45L4 and as partially provided in the Code Recipies section of the Directus website - does not work. The `{{$trigger.collection}}` and `{{$trigger.key}}` fields are not saved.

This already happened in Directus 9.23... and is still not fixed in Directus 10.

Here is a video showcasing the problem:
https://dl.rowild.at/directus-flow-slugify-not-working.mp4

### To Reproduce

Follow this tutorial:
https://www.youtube.com/watch?v=Z4ua6CH45L4

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
> This already happened in Directus 9.23...

What's the existing GH issue? Let's consolidate there

**Comment by rowild** [comment]
@rijkvanzanten Didn't post that as an issue, but mentioned it either under the youtube video or on Discord...

**Comment by rijkvanzanten** [comment]
Ah ok. GitHub Issues is where we track issues so if it's not on here, it's not a known issue 👍🏻

**Comment by rowild** [comment]
Well, I initially wanted feedback on that problem, but unfortunately you – that is: the Directus team – does not seem to be present at all on those channels (Youtube, Discord). Which is a bit sad, because you also say things like "Leave a comment below", but you never ever get back or react in any way to those comments... IMO this must be improved, other OSS are way better here. I also recommended that in your recent survey on how to improve Directus 10 (or whatever the topic was called). I believe that many issues could most likely be solved before opening a issue and therefore reduce work for you guys...

**Comment by Sandros94** [comment]
> Could have sworn this is a duplicate but as rowild said it was probably just mentioned on discord and never reported.

Same, I noticed this bug two weeks ago and I though that I had already opened an issue. Now I've got to this one only because I was looking on the state of this bug (I wanted to test some things about the slugify) but couldn't find in my opened issues. Then looked at the Directus YT channel and I couldn't find the the video either, so I knew the two things were related.

Anyway the bug I've noticed last time I tried this was that if you edit the raw value for the collection `{{$trigger.collection}}` it does work, but if I try to do the same for raw value of the ID we get:
![image](https://github.com/directus/directus/assets/13056429/16583e4e-ecf0-45da-b533-0aec05ff0e1d)

Not to mention that the IDs field doesn't save any string either.

**Comment by Sandros94** [comment]
hold on a second...
![image](https://github.com/directus/directus/assets/13056429/9a7b9774-b892-4ec4-b58c-fcb81225ff81)
why is this legal?
![image](https://github.com/directus/directus/assets/13056429/04a50c50-0317-4a8c-9a97-e337692ac12f)

**Comment by rijkvanzanten** [comment]
> hold on a second... why is this legal?

Any operation option can use the `{{}}` syntax, no matter how/where it's used 🙂

**Comment by Sandros94** [comment]
> Any operation option can use the `{{}}` syntax, no matter how/where it's used 🙂

Yes, I'm noticing now that I should watch the payload and not the options. So no, the filtering for the ID that triggered the payload isn't working.

**Comment by Sandros94** [comment]
I'm noticing that not even the query filter is able to look for the current `{{$trigger.keys}}`:
![image](https://github.com/directus/directus/assets/13056429/99a244e1-bb8c-47e0-9b5d-0612ecfd02a2)

But it does work correctly if I try to filter something else:
![image](https://github.com/directus/directus/assets/13056429/da861a52-d4d1-4cee-a386-0aa014164a4a)

**Comment by Sandros94** [comment]
I just noticed that if I input `{{$trigger.keys}}` it retrieves the actual ID, but if I input if I input `{{$trigger.key}}` it doesn't. Could it be just a misspell?

**Comment by rijkvanzanten** [comment]
> I just noticed that if I input {{$trigger.keys}} it retrieves the actual ID, but if I input if I input {{$trigger.key}} it doesn't. Could it be just a misspell?

This seems to be the case. `items.create` has a value `key`, whereas `items.update` uses `keys`.
