### ISSUE TITLE
Map interface not filling other columns

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1886]
## Version Info
  - Directus version and branch: develop 5ce02d371465e8ce07e634453f7319ef6cd4c066
  - PHP version: 7.1.6
  - MySQL version: 5.6.35
  - Web server: Apache on MAMP Pro
  - OS name and version: macOS High Sierra 10.13.1 Beta (17B25c)
  - Browser: Safari 11.0.1

## Expected Behavior
The map sets the value of another interface on select / change of the location on the map

## Actual Behavior
It doesn't

## Steps to Reproduce
 1. Add a map interface to a table
 2. Set up the map interface to fill a column with the respective item

## Schema Dump, Logs, or Screenshots
No console errors or anything

**Comment by WellingGuzman** [comment]
Can you explain this again, I do not understand what do you meant when you said `to fill a column with the respective item`

**Comment by mikeful** [comment]
This might be same bug: setting up fields and selecting location from map in edit interface fill fields correctly via Javascript but seems like they are not marked as changed and because of it are not sent to backend for saving. I'll create proper issue if this is different than what rijkvanzanten meant.

**Comment by rijkvanzanten** [comment]
Hi @mikeful! I'm pretty sure that's the cause of this problem.

Note to self: check if `this.model.set(<column_name>, <set_value>);` gets called in the referenced other columns on change in the map. (probably not, which would explain this error)

**Comment by mikeful** [comment]
Slug field might have similar bug in some situations. Maybe check it too?

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/pull/2014/commits/e55a1ccbf6ca806da57485b763ecc0c21bbd48fb
