### ISSUE TITLE
Sending a float on a int field should throw an error

### ISSUE THREAD

**Issue by cgarnier** [directus/directus#1887]
## Version Info
  - Directus version and branch: (Or commit hash)
  - PHP version: 
  - MySQL version: 
  - Web server: (Ex. Apache, nginx or IIS?) 
  - OS name and version: 

## Expected Behavior
400 bad request

## Actual Behavior
200, the float is converted to an integer (45.3 => 45)

## Steps to Reproduce
 1. 
 2. 
 3.

**Comment by WellingGuzman** [comment]
I'm closing this ticket, as we are going to implement all this into API 2.0, to avoid confusion we probably going to keep it close and report back when it's implemented.

This ticket has been added to [API 2.0 backlog](https://github.com/directus/directus/projects/7#card-5146966).
