### ISSUE TITLE
Directus Many to One relation after deleting old field 

### ISSUE THREAD

**Issue by vitalijalbu** [directus/directus#18878]
### Describe the Bug

Many to One relation after deleting old field called `members` and create another one called same name, it gives error when trying to create items.
![Screenshot 2023-06-13 alle 16 40 28](https://github.com/directus/directus/assets/40239902/f6d7b606-d3e4-4993-9f0f-6261ee58fcc9)
---------

![Screenshot 2023-06-13 alle 16 36 37](https://github.com/directus/directus/assets/40239902/26fa39d3-3e48-47f1-bdda-fe49e405742e)

### To Reproduce

Create a realtionship, delete it and create new relationship with the same name.

### Directus Version

latest

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by joselcvarela** [comment]
I also suspect that when creating one relationship with similar name of an existent one, it may corrupt the latter when deleting the former.

**Comment by vitalijalbu** [comment]
@benhaynes could you help?

**Comment by rijkvanzanten** [comment]
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻
