### ISSUE TITLE
OAuth2 issue with FusionAuth - "INVALID_CREDENTIALS" error

### ISSUE THREAD

**Issue by frellan** [directus/directus#18872]
### Describe the Bug

Hello,

I am having trouble integrating FusionAuth as an authentication provider for Directus. Despite properly configuring the authentication, I keep encountering an "INVALID_CREDENTIALS" error.

Here's the summary of the issue:

- FusionAuth is correctly authorizing the user and sending them back to Directus.
- However, after redirection, Directus throws an "INVALID_CREDENTIALS" error page.

I have verified the details and credentials multiple times, so it's less likely a typo or incorrect credential issue. Below are the environment variables I have set up for the FusionAuth integration.

Please let me know if there's anything else you need to help resolve this issue. I appreciate your help.

Thanks,
Fredrik

### To Reproduce

This is the environment variables config. I do not think FusionAuth is the problem. it can act as any black box OAuth2 spec enabled auth service essentially in this case.

```
AUTH_PROVIDERS=fusionauth
AUTH_FUSIONAUTH_DRIVER=oauth2
AUTH_FUSIONAUTH_CLIENT_ID=********************
AUTH_FUSIONAUTH_CLIENT_SECRET=********************
AUTH_FUSIONAUTH_AUTHORIZE_URL=https://fusionauth.example/oauth2/authorize
AUTH_FUSIONAUTH_ACCESS_URL=https://fusionauth.example/oauth2/token
AUTH_FUSIONAUTH_PROFILE_URL=https://fusionauth.example/oauth2/userinfo
```

**Note:** I have replaced the actual FusionAuth URL and client credentials with placeholders for security reasons.

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by frellan** [comment]
Fixed it by tweaking the config a bit more

**Comment by BlackDahlia313** [comment]
> Fixed it by tweaking the config a bit more

I'm running into this now trying to twitch or github. What did you see that made a difference?
