### ISSUE TITLE
No validation rules on numbers

### ISSUE THREAD

**Issue by cgarnier** [directus/directus#1888]
Could be nice to have a way to set some contraints on number or other fields.

Min, max, step, decimal number ... for instance

**Comment by rijkvanzanten** [comment]
Hey @cgarnier! Thanks for the input.

Nearly every interface has a number of options to pick from. The `slider` interface for example has these exact options.

I'm going to move over the request for extra validation options in the `numeric` interface to our [feature request tool](https://request.getdirectus.com/r/129) and close this issue, as it's not really an issue.

Have a nice day! 😄
