### ISSUE TITLE
WebSockets Rest subscription with 'strict/handshake' mode returns an empty data array with $CURRENT_USER filter.

### ISSUE THREAD

**Issue by cliqer** [directus/directus#18891]
### Describe the Bug

WebSockets Rest subscription with `strict` or `handshake` mode returns an empty data array `{"type":"subscription","event":"init","data":[]}`. Neither the public nor the authenticated fields are returned.
When the mode is `public`, it works as expected and returns the query fields' public data.
### To Reproduce

```js
wss://example.com/ws?access_token=wZsiQowp4fIGyzfUMKPh6ptiDBVIcuz7
```
```json
{
   "type":"subscribe",
   "collection":"test",
   "query":{
      "fields":["*"]
   }
}
```
```env
WEBSOCKETS_ENABLED=true
WEBSOCKETS_REST_ENABLED=true
WEBSOCKETS_REST_PATH="/ws"
WEBSOCKETS_REST_AUTH="strict"
WEBSOCKETS_GRAPHQL_ENABLED=false
WEBSOCKETS_GRAPHQL_AUTH="strict"

MESSENGER_STORE="redis"
MESSENGER_REDIS_HOST="127.0.0.1"
MESSENGER_REDIS_PORT=6379
MESSENGER_REDIS_DB=2
```

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
I am not able  to reproduce this using the given steps unfortunately

![image](https://github.com/directus/directus/assets/9389634/6cf0c089-5731-4ee6-995e-aa3b1f49c4d8)
