### ISSUE TITLE
Map view defaults to wrong location

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1889]
## Version Info
  - Directus version and branch: develop 5ce02d371465e8ce07e634453f7319ef6cd4c066

## Expected Behavior
Selecting the map view (instead of the list view) shows a map with all my items visible

## Actual Behavior
It defaults to Brooklyn, New York with quite a high zoomlevel which causes my items to be outside of the viewport

## Steps to Reproduce
 1. Add a map interface to a table and add some items
 2. Switch to the map view

## Schema Dump, Logs, or Screenshots

_Expected:_
<img width="1478" alt="screen shot 2017-10-11 at 1 08 26 pm" src="https://user-images.githubusercontent.com/9141017/31455276-66716276-ae85-11e7-9f86-e7c9dbfb430b.png">

_Actual:_
<img width="1478" alt="screen shot 2017-10-11 at 1 08 35 pm" src="https://user-images.githubusercontent.com/9141017/31455366-701bf7be-ae85-11e7-89b8-b544910cf79e.png">

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/248d516c73767758335f70ffc91c122eef88b132

**Comment by rijkvanzanten** [comment]
The Brooklyn problem is solved, but now it shows the most bottom-right position of the map zoomed in fully.....
<img width="1440" alt="screen shot 2017-11-09 at 4 52 51 pm" src="https://user-images.githubusercontent.com/9141017/32631521-882a96bc-c56e-11e7-97f2-6d3bb0c6ea9a.png">

**Comment by rijkvanzanten** [comment]
Probably because there aren't any visible items in the table

**Comment by rijkvanzanten** [comment]
This was fixed in 983c91efe57ff91f9777ad6890c64f95f9514311 on the develop branch and will release in master soon
