### ISSUE TITLE
Kanban layout regrouping fails when sort field is not set

### ISSUE THREAD

**Issue by grefrit** [directus/directus#18899]
### Describe the Bug

Try to regroup multiple items in Kanban layout, eventually it will make request to `/utils/sort/<collection>` and return error `Collection doesn't have a sort field.`. I didn't see this behaviour on previous version, spotted on 10.3.0

Relates to #18790, but I didn't understand why it was closed, it is a major bug that prevents from using Kanban layout, maybe it is not clear, but when this error occurs item is not updated in database, it just updates visually

### To Reproduce

Create collection with status field, create Kanban layout, choose grouping by status, try to regroup multiple items in one group. 

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
The linked issue was closed for lack of reproducing, and the OP never responded after to dispute it.
However it does seem i didnt have enough items in my tests there to easily recreate it.
