### ISSUE TITLE
KnexTimeoutError SQL, SQLite, Flows

### ISSUE THREAD

**Issue by sshvaiko** [directus/directus#18896]
### Describe the Bug

Hello! I'm getting KnexTimeoutError with a simple flow from this example:
https://docs.directus.io/guides/flows/slugify-text-with-run-script.html

![image](https://github.com/directus/directus/assets/25116698/5eef0883-b62d-48c2-b5fd-deac160576d8)

### To Reproduce

1) Create a flow using this tutorial: https://docs.directus.io/guides/flows/slugify-text-with-run-script.html
2) Run it 5-10 times
3) Directus is not working anymore, KnexTimeoutError is in console

### Directus Version

9.23.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Is the "Emit Events" option disabled for the "update data" operation? this will prevent an infinite loop of the flow triggering itself.
