### ISSUE TITLE
User avatars are not loading in Kanban layout

### ISSUE THREAD

**Issue by grefrit** [directus/directus#18900]
### Describe the Bug

<img width="288" alt="image" src="https://github.com/directus/directus/assets/45934058/c13eab10-f10c-4116-ade2-4a78e4c2bc9b">
<img width="342" alt="image" src="https://github.com/directus/directus/assets/45934058/cf79bd3b-0fde-4aaa-a92c-8be3ec410abc">

It is not loading, because there is no src in image tag, not sure why

### To Reproduce

Create Kanban layout, create user, add avatar (in my case I using Azure storage), avatar will not load in Kanban layout, even on admin account with all privileges

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by ConnorSimply** [comment]
@grefrit I am unable to reproduce this. Can you please confirm that the file type is a `image` or `svg`?

**Comment by grefrit** [comment]
@ConnorSimply MIME type is image/svg+xml

**Comment by ConnorSimply** [comment]
@grefrit Fix Underway :) #18904
