### ISSUE TITLE
Flow for Files `item.create` not being triggered

### ISSUE THREAD

**Issue by ched-dev** [directus/directus#18905]
### Describe the Bug

When I have a Flow that should trigger on `items.create` of Directus Files, it does not get triggered.

### To Reproduce

In this example I have set up a flow with the following settings:
- Run a filter on `items.create` and `items.update` of Directus Files
- Log out the results
<img width="721" alt="Screen Shot 2023-06-14 at 1 57 42 PM" src="https://github.com/directus/directus/assets/73146636/d55c8af5-bc5b-4a90-a0ee-c120ac81a66d">

Following the normal flow of creating a file through Directus admin, I see no trigger for the `items.create`, but successful trigger for `items.update`.

https://github.com/directus/directus/assets/73146636/b8d0a149-fa96-4c64-8530-705b6bfa325a

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
That is expected and documented behavior https://docs.directus.io/extensions/hooks.html#filter-events
![image](https://github.com/directus/directus/assets/9389634/95e4f7fb-f50d-40a4-a517-a380ccba8f90)
