### ISSUE TITLE
Searching for location on map view throws error

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1890]
## Version Info
  - Directus version and branch: develop 5ce02d371465e8ce07e634453f7319ef6cd4c066
  - Browser: Safari 11.0.1, macOS High Sierra 10.13.1 Beta (17B25c)

## Behavior
Using the search field in the top left of the map view throws error.

## Steps to Reproduce
 1. Search for a location on the map view

## Schema Dump, Logs, or Screenshots

```
Error
Error: TypeError: undefined is not an object (evaluating 'place.geometry.location')
File: http://directus.dev/app/core/listings/map.js?bust=5ce02d371465e8ce07e634453f7319ef6cd4c066
Line:368
```

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/9e6a3f9e4e7276e852f51115d37374ef075001a6

---

The autocomplete only allow places from the autocomplete list, other values should be ignore.
