### ISSUE TITLE
Can not open permission page "

### ISSUE THREAD

**Issue by u12206050** [directus/directus#18917]
### Describe the Bug

Error message:
```{
  "stack": "TypeError: Cannot read properties of undefined (reading 'id')\n    at http://localhost:8080/admin/assets/index.aa47f040.entry.js:2949:339979\n    at Array.map (<anonymous>)\n    at l (http://localhost:8080/admin/assets/index.aa47f040.entry.js:2949:339906)",
  "message": "Cannot read properties of undefined (reading 'id')"
}```

### To Reproduce

After updating to 10.3.0 I am unable to open permission page.

In developer tools I notice that during the map function f.users is just an array of user ids instead of objects, so that when 1 item exists, then p.count (which doesn't exist on user object) but specifically `p.count.id` causes the error.
```
i.value = [{
                    public: !0,
                    name: e("public_label"),
                    icon: "public",
                    description: e("public_description"),
                    id: "public"
                }, ...d.map(f=>{
                    var p;
                    return {
                        ...Tu(f),
                        count: ((p = f.users[0]) == null ? void 0 : p.count.id) || 0
                    }
                }
                )]
```

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Is this dependent on specific filters you've set? I am unable to reproduce this on a clean `10.3` instance.

**Comment by ps73** [comment]
It seems that my pr #18937 is adressing this issue.
