### ISSUE TITLE
Columns sorting drag and drop problems

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1891]
## Version Info
  - Directus version and branch: develop 5ce02d371465e8ce07e634453f7319ef6cd4c066
  - Browser: Safari 11.0.1, macOS High Sierra 10.13.1 Beta (17B25c)

## Expected Behavior
Dragging the column name changes the order

## Actual Behavior
It only orders.. when it wants to? It seems to help if you move the cursor fast.

## Schema Dump, Logs, or Screenshots
![2017-10-11 13_45_35](https://user-images.githubusercontent.com/9141017/31457337-785fc428-ae8a-11e7-9b85-5344e9492e24.gif)

**Comment by WellingGuzman** [comment]
It happened to me once, but I've never been able to reproduce it ever since.

**Comment by rijkvanzanten** [comment]
It seems like it works fine on first load, but after navigating back and forth between tables the problem starts

**Comment by bratsun** [comment]
Cannot drag'n'drop rows while editing M2M content and tables settings at /admin/settings/tables/*. Latest Chrome. Works in Safari though.

**Comment by rijkvanzanten** [comment]
Could that specific one have been caused by https://github.com/directus/directus/issues/1941 @bratsun?

**Comment by bratsun** [comment]
@rijkvanzanten I think yes. was #1941 pushed to master or not yet?

**Comment by rijkvanzanten** [comment]
I believe it is yes @bratsun

**Comment by rijkvanzanten** [comment]
At the moment, all core developers are working fulltime on the next major version of the platform, so I'll have to leave this open as a help-wanted. If anyone is inclined to take a swing at fixing this, a PR is very welcome 😄

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/9)
