### ISSUE TITLE
Deleted field, still referenced in other collection and breaking the view

### ISSUE THREAD

**Issue by dewey** [directus/directus#18912]
### Describe the Bug

I have a data model set up for "linked_object" which had a column called entity_id and entity_type. As entity_type wasn't used anymore I deleted the column in the linked_object table in my Directus database by dropping the column directly via SQL.

After that, opening my "article" data model which uses the "linked_object" in a field started erroring as it still referenced the entity_type somewhere:

<img width="694" alt="image" src="https://github.com/directus/directus/assets/790262/c57ffa3e-950c-4ef9-b109-e245e2dd554d">

I figured that I shouldn't have deleted the column I re-created it via SQL, doing that via Directus first gave me the following error:

<img width="694" alt="image" src="https://github.com/directus/directus/assets/790262/80b55b54-0af1-4e64-b736-af1f0585f542">

I figured that if I deleted it again through Directus now it would clean up after itself and the articles would load again in Directus. I did that and it now showed up as "database only, click to configure" in Directus.

Everything worked again after that but even if it's not used any more in the linked_object data model it starts erroring again when I drop the column again.

Any advice on how to cleanly remove this column / field? It looks like it's still referenced in the directus_fields table, why is this not cleaned up after clicking delete on a field?

<img width="1083" alt="image" src="https://github.com/directus/directus/assets/790262/3078df9b-b2d3-4a27-abcc-be53e920820e">

Thanks!

### To Reproduce

- Delete column in a custom data model via SQL which is referenced in another data model
- Open item based on data model in Directus -> Error
- Create column again via SQL, configure field
- Delete field again
- Open item based on data model in Directus -> Works
- Drop column again via SQL
- Open item based on data model in Directus -> Error

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
In this particular case, you're right! Because you're actively using that column in the options of a display, the display is trying to load those values in the layout, which in turn causes the error. I'll leave this issue open as a small improvement to make sure that display will silently ignore fields that no longer exist 👍🏻
