### ISSUE TITLE
Deeply nested field does not properly filter 

### ISSUE THREAD

**Issue by yoshiemuranaka** [directus/directus#18915]
### Describe the Bug

We have courses, lessons, and progressions collections.

courses o2m lessons
progressions m2o lessons

We expect a query with filters below to only return courses that have lessons with progressions `is_complete` value true, but we get inconsistent results. It seems like some courses are filtered but not by the `is_complete` value

```
query MyQuery {
  courses(filter: {lessons: {progressions: {is_complete: {_eq: true}}}}) {
    id
    lessons {
      id
      progressions {
        is_complete
      }
    }
  }
}

```

returns something like:

```
{
  "data": {
    "courses": [
      {
        "id": "2700d177-1687-4b7d-a27e-c8941f8440ca",
        "lessons": [
          {
            "id": "11845b3b-1acc-4173-b93b-9f7cbcbb552a",
            "progressions": [
              {
                "is_complete": true
              }
            ]
          },
          {
            "id": "a0c9e6e1-85f6-48da-8d38-edd7eb1722cc",
            "progressions": [
              {
                "is_complete": true
              }
            ]
          }
        ]
      },
      {
        "id": "3c57c117-12e8-4ddc-8a8f-7087844a4a73",
        "lessons": [
          {
            "id": "a8bfccc9-1b24-415e-8948-a715eda65f9a",
            "progressions": [
              {
                "is_complete": false
              }
            ]
          },
          {
            "id": "140d22c3-7a10-4c24-8437-fc0ad4a58d9b",
            "progressions": [
              {
                "is_complete": true
              }
            ]
          },
          {
            "id": "9bacb498-a25a-4f50-938c-a54e0fa47a79",
            "progressions": [
              {
                "is_complete": true
              }
            ]
          },
          {
            "id": "ef614b4d-f6f7-4d6f-ba19-dad95e52d8d2",
            "progressions": [
              {
                "is_complete": false
              }
            ]
          },
          {
            "id": "7f322bcd-363e-4c87-84a7-7fef1f58eaf0",
            "progressions": []
          },
          {
            "id": "9abba483-960b-4621-a951-7d71125447e8",
            "progressions": []
          },
          {
            "id": "2bdd03f5-be9b-4374-bd61-e79b8a1f1453",
            "progressions": [
              {
                "is_complete": false
              }
            ]
          },
          {
            "id": "2ad1b8ca-ed57-4b9c-b35f-91608487f110",
            "progressions": []
          }
        ]
      }
    ]
  }
}
```

### To Reproduce

Create courses collection
Create lessons collection
Create progressions collection
Create course o2m lessons relationship
Create progression m2o lesson relationship
Create progression is_complete boolean field
Try filtering with `courses(filter: {lessons: {progressions: {is_complete: {_eq: true}}}})`

### Directus Version

9.26

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
The returned result there looks correct for your filter 🤔 when nesting like this the filter functions as: You're filtering courses where any lesson has any progression with `is_complete: true`. And by the looks of it all returned courses have at least one completed lesson in the response.

**Comment by yoshiemuranaka** [comment]
@br41nslug with the query in the description, we're also seeing some courses returned with no progressions. is this expected?

```
{
  "data": {
    "courses": [
      ...
      {
        "id": "eca8c894-8797-4747-be91-bf06555561bf",
        "lessons": [
          {
            "id": "2c802cfd-4aeb-49d6-a617-4d676e84a634",
            "progressions": []
          },
          {
            "id": "dc9fb453-84cb-46fa-96dd-dd5425327a2c",
            "progressions": []
          }
        ]
      },
      {
        "id": "97d461ee-4cbd-4f37-a01e-2629e37ec929",
        "lessons": [
          {
            "id": "8bb67169-44a2-4d03-a9ab-ee59e1a6f73a",
            "progressions": []
          },
          {
            "id": "dce96f57-1530-4921-86f5-810a5617ecf0",
            "progressions": []
          },
          {
            "id": "27a30eb4-e5c6-4afb-9675-b746a0005eaf",
            "progressions": []
          },
          {
            "id": "bbe21a23-a7ee-4ac3-87de-e0830520ceb4",
            "progressions": []
          },
          {
            "id": "c7c4821c-9e00-4e1d-8902-6e8c87eb25ee",
            "progressions": []
          }
        ]
      }
    ]
  }
}
```

And we are also seeing unexpected results when querying the lessons directly

```
query MyQuery {
  lessons(filter: {progressions: {is_complete: {_eq: true}}}) {
    id
    progressions {
      is_complete
    }
  }
}
```

Returns

```
{
  "data": {
    "lessons": [
      {
        "id": "2c802cfd-4aeb-49d6-a617-4d676e84a634",
        "progressions": []
      },
      {
        "id": "11845b3b-1acc-4173-b93b-9f7cbcbb552a",
        "progressions": [
          {
            "is_complete": true
          }
        ]
      },
      {
        "id": "a0c9e6e1-85f6-48da-8d38-edd7eb1722cc",
        "progressions": [
          {
            "is_complete": true
          }
        ]
      },
      {
        "id": "a8bfccc9-1b24-415e-8948-a715eda65f9a",
        "progressions": [
          {
            "is_complete": false
          }
        ]
      },
      {
        "id": "dc9fb453-84cb-46fa-96dd-dd5425327a2c",
        "progressions": []
      }
    ]
  }
}
```

**Comment by br41nslug** [comment]
> we're also seeing some courses returned with no progressions. is this expected?

I am presuming one of the elipsed `...` lessons in that course does have a progression. Remember you're filtering `courses` any nested level beyond that you're getting `all` related items. You may want to look into the `deep` filter (https://docs.directus.io/reference/query.html#deep) option for more fine grained filtering.

Not completely sure whats happening in the second example (is the same happening with REST?).

**Comment by yoshiemuranaka** [comment]
I may have pasted the returned data incorrectly, here's screenshot from a playground that shows the empty progressions better

<img width="1363" alt="Screenshot 2023-06-19 at 9 41 41 AM" src="https://github.com/directus/directus/assets/8097306/316dc921-6be2-4124-a1ef-42b49d70b286">



For the second example, I am seeing similar results using REST

Appreciate your help with this @br41nslug !

**Comment by yoshiemuranaka** [comment]
Another thought, our progressions table also has a user field (lesson progress is tied to a specific user) and we have permissions set up so a user can only see progression items associated with their user id. 
I'm wondering if maybe the filter function is returning any lesson with a progression `is_true` that may be associated with other users?
