### ISSUE TITLE
Problem while trying to use decimal datatype

### ISSUE THREAD

**Issue by ngirardhg** [directus/directus#1892]
Version Info
  - Directus version and branch: 6.4.3, release version
  - PHP version: 5.6.30
  - MySQL version: 5.0.11
  - Web server: Apache XAMPP
  - OS name and version: Windows 10 pro

## Expected Behavior
Trying to add and save a decimal value in a field of datatype decimal should add and save the value.

## Actual Behavior
Trying to add and save a decimal value in a field of datatype decimal throws and error "Invalid value"

## Steps to Reproduce
 1. Create a table
 2. Add a new field of interface "Numeric" and dataype "Decimal",  set the precision to let's say : 10,5
 3. Try to add and save the following value : 123,321 or 123.321

## Schema Dump, Logs, or Screenshots
![directus_issue_screenshot](https://user-images.githubusercontent.com/31041083/31457553-19efc45a-ae8b-11e7-9ec9-07d751811c5b.png)

**Comment by rijkvanzanten** [comment]
For future reference:
Directus uses native browser validation on the `input[type=number]`, but didn't set the `step` attribute which causes the browser to return `false` on the validation method for floats.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/ad4d3e07b1d33594d20a4d2ebe0a6ef916b8215e and https://github.com/directus/directus/commit/2c17729de7757fff00a99279c920109d4e152c49

**Comment by ngirardhg** [comment]
@WellingGuzman @rijkvanzanten  I pulled the develop branch and ran the gulp file to be sure everything was properly compiled. I then tried using a field of type "decimal", which still gives me the same error.
