### ISSUE TITLE
Websocket not sending update 

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/directus#18925]
### Describe the Bug

I have a collection with a sort field, if I change the sorting in directus by drag and drop, I don't get an event via websocket.

### To Reproduce

1. Create Collection with a sort field
2. Connect and Subscribe via Websocket (REST)
3. Change sorting in Directus via Drag and Drop
4. No event is retrieved in the message callback

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
Sorting items is indeed throwing the uncaught `items.sort` event instead of the `items.update`
