### ISSUE TITLE
Live preview does not worklng with Nuxt 3.5.2

### ISSUE THREAD

**Issue by JESSYV96** [directus/directus#18926]
### Describe the Bug

i tried to set up live preview with documentation but  i've blank page in directus dashboard

### To Reproduce

you have set up a nuxt 3.5 project and follow documentation

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
Make sure you have added the domain you're trying to preview to the CSP `CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: 'http://example.com/'` (and it doesnt hurt to check if the preview site has no anti-framing settings set)
