### ISSUE TITLE
Unable to retrieve information about currently connected WebSocket clients

### ISSUE THREAD

**Issue by seymoe** [directus/directus#18924]
### Describe the Bug

I am using Directus version 10.3.0, and overall, everything is working well. However, I am facing an issue where I am unable to retrieve information about the clients currently connected to the WebSocket. After inspecting the code, I noticed that the WebSocketService provides a "clients" method for this purpose.

However, when I attempted to construct an endpoint and looked for the WebSocketService in the services, I couldn't find it. I am using create-directus-extension with a version of 10.0.5.

Could you please assist me in resolving this issue and guide me on how to retrieve the information about connected WebSocket clients in Directus version 10.3.0?

Thank you.

### To Reproduce

export default (router, { services }) => {
  console.log(services.WebSocketService); // undefined ??
	router.get('/', (req, res) => res.send('Hello, World!'));
};

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by seymoe** [comment]
I understand that the development team is currently not planning to do this feature. I will close this issue.

**Comment by br41nslug** [comment]
@cliqer If websockets was 50% connection events then it would not have much functionality 😉 
Extending the core behavior for your bussiness logic should be very doable with hook extensions:
```js
export default function registerHook({ action }) {
    action('websocket.connect', ({ client }) => console.log('connected', client));
    action('websocket.error', ({ client }) => console.log('error', client));
    action('websocket.close', ({ client }) => console.log('close', client));
}
```
However the WebSocketsService should have been exposed to extension to make it easier so re-opening this anyway🤔
