### ISSUE TITLE
Github SSO not logging in. (registers user though)

### ISSUE THREAD

**Issue by M-GRV** [directus/directus#18922]
### Describe the Bug

When trying to login the github user is not being logged in. It DOES create the user and properly set their external identifier. I have tried using the email (with the user having it public) or just using the username.

Both create the user, and input the external identifier. But the user remains at the login screen. No errors. 

Twitch works as expected for example. 

### To Reproduce

install via docker
configure github
user remains at login screen
check via admin account and see the github user was created

### Directus Version

v10.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by M-GRV** [comment]
https://github.com/directus/directus/issues/18921 has been fixed by moving to docker. This is an entirely different issue.

**Comment by BlackDahlia313** [comment]
Installing from a forked repo instead of hub has resolved the sso issues for me and most of the collection issues. I just cannot build relations.

**Comment by M-GRV** [comment]
Installing from a forked repo instead of hub has resolved the sso issues for me and most of the collection issues. I just cannot build relations atm.
