### ISSUE TITLE
Email: Link color is hard-coded to #6644ff

### ISSUE THREAD

**Issue by dnndev** [directus/directus#18927]
### Describe the Bug

The `base.liquid` email template hard-codes `body a` to be #6644ff. This should be set to take the primary Project color from Project Settings.

Ref: https://github.com/directus/directus/blame/main/api/src/services/mail/templates/base.liquid

### To Reproduce

Change the Project Settings / Project color to something other than the default. Send a password reset email. The "Reset Your Password" link color is still the indigo/purple color #6644ff.  

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by ArchitGajjar** [comment]
@dnndev can you please assign this to me. Thank you!
