### ISSUE TITLE
Directus user is logged out after app reload

### ISSUE THREAD

**Issue by donavan-tangible** [directus/directus#18932]
### Describe the Bug

Describe the Bug

Everytime I reload the Directus app, the login screen appears.

### To Reproduce

Download Directus version 10.3.0, open the admin panel, login and then refresh the page (or copy the url and open in a new tab)

It works with Google Chrome.

It's not working with Safari

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
Gut feeling says this is configuration / hosting related. How are you running Directus? What is the configuration for the REFRESH_TOKEN [environment variables](https://docs.directus.io/self-hosted/config-options.html#security)? Are you using HTTPS?

**Comment by donavan-tangible** [comment]
@rijkvanzanten  Please add this information in the documentation.

**Comment by br41nslug** [comment]
@donavan-tangible https://docs.directus.io/self-hosted/config-options.html#security

**Comment by rijkvanzanten** [comment]
There's tons of great resources available from the likes of MDN and web.dev on how cookies (should) behave, like https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies and https://web.dev/understanding-cookies/ 🙂 

👍🏻

**Comment by donavan-tangible** [comment]
Directus's documentation is simply not clear about this the effect of REFRESH_TOKEN_COOKIE_SECURE .
"Whether or not to use a secure cookie for the refresh token in cookie mode."
