### ISSUE TITLE
redis cache password and port settings are ignored

### ISSUE THREAD

**Issue by BlackDahlia313** [directus/directus#18933]
### Describe the Bug

Was able to solve everything by adding a redis server. The issue is that I need a password to protect this redis server. But if one is enabeled and the password is entered as a env variable, I get: NOAUTH Authentication required

I also tested by changing the default port and it kept trying to connect to the default. 

### To Reproduce

try pointing to external redis server

### Directus Version

v.10.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by BlackDahlia313** [comment]
> I am unable to reproduce this and have redis authentication working on a different port with both a single connection string `CACHE_REDIS: 'redis://:test123@<IP>:1234/1'` and as individual settings
> 
> ```
> CACHE_REDIS_HOST: '<IP>'
> CACHE_REDIS_PORT: '1234'
> CACHE_REDIS_USERNAME: 'default'
> CACHE_REDIS_PASSWORD: 'test123'
> CACHE_REDIS_DB: '1'
> ```
> 
> Make sure you have added authentication to all redis uses like rate limiter, cache and messenger.

trying this again with adding the auth to the other layers like rate limiting and messenger. as it was just cache that had it
before

**Comment by BlackDahlia313** [comment]
again its being ignored for me:

![image](https://github.com/directus/directus/assets/44903742/9324114f-dba8-4c25-a678-fc27f4e2ea8c)
![image](https://github.com/directus/directus/assets/44903742/9d25d67c-5b6f-4c82-a1f4-54c27a244af2)

@br41nslug its still doing the same thing. Either doing each as invdidual or not.

**Comment by br41nslug** [comment]
Are you sure you're environment setting are applied correctly? You mention you use the Docker Image in the description but this last screenshot does not look compatible with that. Are you building a custom image or using docker-compose?

**Comment by BlackDahlia313** [comment]
> Are you sure you're environment setting are applied correctly? You mention you use the Docker Image in the description but this last screenshot does not look compatible with that. Are you building a custom image or using docker-compose?

This is digital ocean. 

![image](https://github.com/directus/directus/assets/44903742/0335befa-5856-4964-9bc7-98fe7c165213)

These live in here.

Every other ENV is read fine. I have a lot of custom variables here for sso, s3 storage etc. Those work fine.

But no matter what I put for redis it doesnt change anything. It just sees the redis flag for enabled and attempts to connect locally.

If I break it out individually, it can see the IP address, but ignores port and password variables.

**Comment by BlackDahlia313** [comment]
> Then i'd check 2 things:
> 
> * If you have special chars in your password you may want to add quotes to the value and see if that helps
> * And double check if you dont have a double environment variables for `CACHE_REDIS` or a lingering `REDIS_*`

it looks like for some reason DO cares about where the ENV variable sit. 

I moved all of those redis variables to the bottom and broke them up again. It seems to be connecting to everything now. Cache, rate limiting, messenger and sync. 

So for anyone reading this for digital ocean deploys, 

make sure to keep these variables at the bottom (use build edit if needed to make change) 


Weird but seems to be resolved now. Ty  for your help @br41nslug . Sorry for any noise
