### ISSUE TITLE
Tiles list view uses raw value

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1893]
## Version Info
  - Directus version and branch: develop 5ce02d371465e8ce07e634453f7319ef6cd4c066

## Expected Behavior
The values in the cards on a Tiles view use the output of the `list` method of the interface. 

## Actual Behavior
It shows the raw value

## Steps to Reproduce
 1. Switch to Tiles view

## Schema Dump, Logs, or Screenshots
This matters because the raw output of some columns can be useless or less pleasing to use and look at. For example, I'd like the card to display the display value of my selected radio button instead of the raw value

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/df4c59a96641bd97234e0e8a86815540a17815a6
