### ISSUE TITLE
Unexpected behaviour with v-table and show-select='one'

### ISSUE THREAD

**Issue by Philippe-cheype** [directus/directus#18930]
### Describe the Bug

I was trying to make a `v-table` with selection enabled, more specifically with the ability to select a single value.

[Looking at the wiki I found `show-select`](https://github.com/directus/directus/wiki/v-table#:~:text=Boolean-,show%2Dselect,-Hide%20checkboxes%3A), here was my setup:

```ts
<v-table
    :headers="tableHeaders"
    :items="tableItems"

    v-model="selectedTableItems"
    show-select="one"
    item-key="uid"
></v-table>
```

But there a was a clear issue with the way the radio buttons (a.k.a. `'one'`) worked. After some looking around in the source code I realises that indeed it was not being handled as expected.

I had to make hacky event handler on my end to fix it.

### show-select='multiple'

![Show Select multiple](https://github.com/directus/directus/assets/72014356/bdd5837b-ab21-49d2-8ad6-4bf9640893da)

### show-select='one'

![Show Select one](https://github.com/directus/directus/assets/72014356/626847f4-5a84-4a4c-9efc-12a1c11517e9)

### The issue

Taking a look at the source code (link to [v-table.vue:272](https://github.com/directus/directus/blob/10215abdd0575bc92019381170e362b98388d6cd/app/src/components/v-table/v-table.vue#L272))

```
@directus/directus/app/src/components/v-table/v-table.vue:272

 272 | function onItemSelected(event: ItemSelectEvent) {
```

This function doesn't take into account the different between `show-select='one'` or `'multiple'`.

But the feature is right there, it doesn't feel right to have to hack it on my end.

### To Reproduce

- **Version**: Latest version.
- **Setup directus**: Create a directus project, link it to a database, setup a new extension of type: `module`
- **Setup the `v-table`**: create a `v-table` (as given above), fill with data
- **Start directus**: build the extension, start directus, enable new module in settings, go to new module page,
- **The issue**: Select multiple items im the table and you will find that 1+ radio buttons can be selected even though we specified `'one'`

### Directus Version

v10.x.x

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
This was fixed in https://github.com/directus/directus/pull/18931 🚀
