### ISSUE TITLE
Datetime field uses default 12:00 time instead of 00:00

### ISSUE THREAD

**Issue by bartvdbqld** [directus/directus#18948]
### Describe the Bug

When using a datetime field (24h notation), the default time seems to be 12:00. In older versions of directus this was 00:00.

When a user selects a date (without clicking "Set to Now") the datetime selected is always the selected date at 12:00 instead of selected date at 00:00 (start of day). Which is most of the time the wrong value since most of the time we want 00:00 and there seems to be no way to change te default time?

### To Reproduce

Add a datetime field. Create new content and select a date.

### Directus Version

v10.0.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by arladmin** [comment]
Came across the same thing. Indeed, 12:00 default would be considered a "bug" in pretty much all use-cases.
