### ISSUE TITLE
Problem while trying to use a "many to one" relationship

### ISSUE THREAD

**Issue by ngirardhg** [directus/directus#1895]
Version Info
  - Directus version and branch: 6.4.3, release version
  - PHP version: 5.6.30
  - MySQL version: 5.0.11
  - Web server: Apache XAMPP
  - OS name and version: Windows 10 pro

## Expected Behavior
Creating a new column of interface many to one in a table and then clicking on the "+" button to add a new item to the table should lead to the new item creation form.

## Actual Behavior
Creating a new column of interface many to one in a table and then clicking on the "+" button to add a new item throws an error : "Error: Uncaught TypeError: Cannot read property 'map' of null"

## Steps to Reproduce
 1. Create a table, and then a second table
 2. Try adding a new column of type "Many to one" relating to the second table
 3. Try adding a new item to the table containing the "Many to one" relationship

## Schema Dump, Logs, or Screenshots
Screenshot of the error
![relation_error](https://user-images.githubusercontent.com/31041083/31463835-71cd45a0-ae9d-11e7-8b0a-2322ba013da9.png)

Screenshot of the column setup
![relation_column_setup](https://user-images.githubusercontent.com/31041083/31463851-7d703b1a-ae9d-11e7-8ef5-f4a0239b9ef5.png)

Screnshot of the interface options 
![relation_interface_option](https://user-images.githubusercontent.com/31041083/31463869-8a673de6-ae9d-11e7-9e66-05942d2a3747.png)

**Comment by WellingGuzman** [comment]
I can't tell what's going on. Is `map` a field? can you please share with us a schema that we can use to reproduce this issue? I'm not being able to reproduce this.

**Comment by argmhz** [comment]
Got the same error. I was also trying to make a "Many to one" relation between to tables. No map field involved.

**Comment by WellingGuzman** [comment]
@argmhz can you please share a schema that we can use to reproduce this issue?

**Comment by rijkvanzanten** [comment]
@WellingGuzman I'm thinking `map` is the array method. `Can't find property 'map' of null` sounds to me like we try to map over an array, but that array is now `null` for some reason

**Comment by ngirardhg** [comment]
@WellingGuzman I would gladly send you a database schema but I lost the files due to a broken hard drive, as soon as I am able to retrieve them I will provide them.

**Comment by WellingGuzman** [comment]
@rijkvanzanten oh yeah, it makes sense now.

@ngirardhg if you can recover that data please send it over.

**Comment by ngirardhg** [comment]
@WellingGuzman Here is the database schema to illustrate the problem. I was not able to recover my old database, so I created a new one. In the "bureau_de_location" table I have a many to one relationship linked to the table "ville". If you try cliking on the table, you'll get the error. If you remove the field "ville" in the "bureau_de_location" table (which contains the many to one relationship), the error won't be there anymore. 

[directus_immobilier.zip](https://github.com/directus/directus/files/1391222/directus_immobilier.zip)

The credentials to log in : directus@directus.com, password : directus

**Comment by ngirardhg** [comment]
@WellingGuzman @rijkvanzanten This issue seems to be resolved in the "develop" branch. The tables containing fields of type "many to one" are now working. The only problem left remains in the display part of the dropdown : the text does not appear (although properly configured in the interface option)

![dropdown unfilled](https://user-images.githubusercontent.com/31041083/31684200-fbd48520-b34c-11e7-9fb2-496788305841.png)

**Comment by WellingGuzman** [comment]
Glad this issue was already resolved.

can you show us how you configured the visible columns in many to one relationship?

**Comment by ngirardhg** [comment]
It was a configuration mistake, thanks for you help ! This is also solved.

**Comment by WellingGuzman** [comment]
Glad to hear @ngirardhg!
