### ISSUE TITLE
A role that does not have the right to modify directus_dashboards should not be able to modify

### ISSUE THREAD

**Issue by Pachat** [directus/directus#18959]
### Describe the Bug

A role that does not have the right to modify `directus_dashboards` can modify a dashboard

### To Reproduce

Create a dashboard
Give `All Read Access` and `No Edit Access` to a role on `directus_dashboards`
Connect with that role
Show the dashboard
Click on the pencil and edit the dashboard
Save

=> You have edited the dashboard despite `No Edit Access`

### Directus Version

v10.2.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by Pachat** [comment]
- Responsiveness would be NTH.

- Also, Decimal 0 should show 0 decimal, not 3.

**Comment by br41nslug** [comment]
Make sure you also adjust the permissions to `directus_panels` else you may not be able to edit the dashboard name etc but will be able to edit the panels in it.
