### ISSUE TITLE
Visual glitch when adding fields to the table layout

### ISSUE THREAD

**Issue by nskartoredjo** [directus/directus#18964]
### Describe the Bug

Adding a field to the table layout will cause the + symbol to shift from the right corner to the left, just below the first field header.

(A picture is worth a thousand words)

![image](https://github.com/directus/directus/assets/5946359/a69e0048-8a79-4603-afbe-aec2417e31ab)

### To Reproduce

- Open a collection view
- Select the table layout
- create a setup with $`n-1`$ columns, with $`n`$ being all fields provided by the collection
- refresh page
- add the last missing field to the layout

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
I haven't been able to reproduce this based on the given steps. What browser are you using @nskartoredjo?
