### ISSUE TITLE
Archived items are still shown on M2M

### ISSUE THREAD

**Issue by LevinGermann** [directus/directus#18965]
### Describe the Bug

When having a M2M relationship and archive an item, the items are still shown on the parent item.

Isn't the archiving functionality supposed to work like this?

https://github.com/directus/directus/assets/9347206/65ad7bc1-d857-4c00-9b9a-200f96d72927

I tried to setup archiving on the item and on the junction item itself, both don't have any effect.

### To Reproduce

1. Create a Parent collection
2. Create a child collection, archiveable
3. Parent M2M child relationship
4. Archive a child item
5. The item still shows up on the parent.

### Directus Version

10.3.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
This is working as intended! The archive status just sets the configured field to a configured value, but there's no assumptions made on how they should behave elsewhere. You can configure a filter on the m2m interface to prevent archived items from being selected 👍🏻

**Comment by LevinGermann** [comment]
@rijkvanzanten Oh, alright. My goal is that I have "child" items which have a date on them, and I don't want to show "expired" ones on the parent item.
My initial thought was to archive expired items with a CRON flow, but since archiving doesn't seem to achieve this I need to somehow hide these on the parent.

<img width="847" alt="image" src="https://github.com/directus/directus/assets/9347206/c78c6cb2-608f-496b-a395-660dce4f9283">


Having the "Enable searching & filtering" enabled (and setting some default for all users?) doesn't seem to achieve the goal, the search/filter option doesn't appear. Seems to be working for O2M though... :

<img width="817" alt="image" src="https://github.com/directus/directus/assets/9347206/fd35f4b4-d5cc-4cda-8927-9bd76e6337fe">

**Comment by rijkvanzanten** [comment]
I see! I think that's a new feature. Filtering currently filters what people are allowed to select, but not what's displayed 🤔
