### ISSUE TITLE
Permissions Fetch Loop

### ISSUE THREAD

**Issue by ps73** [directus/directus#18961]
### Describe the Bug

When opening a role there is an infinite loop of requests to fetch permissions:
![Screenshot 2023-06-21 at 15 34 51](https://github.com/directus/directus/assets/17291660/685918f8-cab9-4a4c-8890-213739c71e50)

### To Reproduce

- fresh installation
- open admin role detail page

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by ps73** [comment]
This seams to be the same issue described here: #18654

The PR #18655 seems not to fix this issue at all.

**Comment by rijkvanzanten** [comment]
This was fixed in #18962! 🚀
