### ISSUE TITLE
Map listing view throws error after navigating away

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1897]
## Version Info
  - Directus version and branch: develop 56301d4e8c42a44576ae21fa02bd0c8af1c92cc9

## Behavior
After selecting an item from the map view to edit it, Directus throws an error:
```
Error
Error: TypeError: null is not an object (evaluating 'this.map.getBounds')
File: http://directus.dev/app/core/listings/map.js?bust=56301d4e8c42a44576ae21fa02bd0c8af1c92cc9
Line:373
```

## Steps to Reproduce
 1. Switch to mapview
 2. Navigate to edit item view

**Comment by WellingGuzman** [comment]
Hey @rijkvanzanten can you share a schema? I'm not being able to reproduce this issue.

**Comment by rijkvanzanten** [comment]
Here you go!

[schema_copy.sql.zip](https://github.com/directus/directus/files/1387720/schema_copy.sql.zip)

**Comment by WellingGuzman** [comment]
Still all good, what commit are you on? when you say navigate to edit item view, you mean clicking on the blue pins on the map?

**Comment by rijkvanzanten** [comment]
This was on 56301d4e8c42a44576ae21fa02bd0c8af1c92cc9, but it seems to have fixed itself over the weekend... Lets blame the cache. I'll close this for now and reference this one if it were to happen again
