### ISSUE TITLE
Unable to save 'id' tags in Flows

### ISSUE THREAD

**Issue by EnzoBitMatrix** [directus/directus#18975]
### Describe the Bug

When creating a flow, I am unable to save the ID tag ie; {{$trigger.body.keys}} on update and read flows.

I have tried toggling the field and also entering raw values.  When trying to enter a raw value, the 'Done' button does nothing and the screen just remains as it is.

### To Reproduce

1. Login to Directus
2. Navigate to Flows and create a new flow
3. Select any type of flow, I am using 'Webhooks' > Method is 'POST > Response Body: All Data
4. Create a 'Read' Operation
5. Permissions: Full Access
6. Choose a collection
7. Enter ID of: {{$trigger.body.keys}}
8. Save the operation

Further testing:
Change the toggle of the ID field and enter the ID: Fail
Select Edit RAW value and enter ID > Unable to click 'Done' > Fails

I have tried using varied combinations of keys, and none of them save into the flow.

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Make sure to actually add the tag before saving 😬 
![image](https://github.com/directus/directus/assets/9389634/6da8c912-940d-484a-9d1d-90bfab3cf810)

https://github.com/directus/directus/assets/9389634/567a426b-bed5-4de8-bd93-39d750e15c6b
