### ISSUE TITLE
Flow Operations Docs Confusion

### ISSUE THREAD

**Issue by ched-dev** [directus/directus#18972]
### Page

https://docs.directus.io/app/flows/operations.html

### Describe the Inaccuracy

Content mentions "Action (Blocking)" but it should probably be "Filter (Blocking)" or "Action (Non-Blocking)"

<img width="682" alt="Screen Shot 2023-06-22 at 4 56 09 PM" src="https://github.com/directus/directus/assets/73146636/6a0d6466-94c0-45f3-91ba-e526cdfc09a1">

**Comment by rijkvanzanten** [comment]
Great catch!
