### ISSUE TITLE
Flows: Error when removing operation then adding with same name

### ISSUE THREAD

**Issue by ched-dev** [directus/directus#18973]
### Describe the Bug

If I remove an operation in a flow with a custom name (Ex: `read_users`) and I try to add a new operation with the same name, I see an error:
> Operation keys must be unique in a Flow

It incorrectly thinks the operation still exists since we have not saved the entire flow.

Expected behavior: it should not show an error since it no longer exists in the flow.

### To Reproduce

Within a flow:
- Delete an operation with a custom name (Ex: `read_users`)
- Add a new operation with the same name
- Error shown inline

Screen Recording:

https://github.com/directus/directus/assets/73146636/ecac3586-19e8-4202-9413-67eb45663bfd

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
This is most likely a chaching issue. How have you configured caching?

**Comment by ched-dev** [comment]
I have not clicked the save button between edits. I know this is a work around, but I believe most people will not save and edit again. I don't think you should **need** to save and edit again to prevent the error. In my opinion, the error is confusing since it says there are duplicate keys, but no other operations exist.

**Comment by ched-dev** [comment]
If anyone else runs into this issue, a quick fix is to remove the connections between the operations (steps) and save, then come back and reconnect them. I can usually get past this error when doing so.

**Comment by rijkvanzanten** [comment]
This is most likely because the name-exists-check is performed against the last saved value, instead of against the currently "staged" value
