### ISSUE TITLE
Get current user info

### ISSUE THREAD

**Issue by BennerGe** [directus/directus#1898]
Is a API endpoint existing, where information about the currently logged-in user can be fetched? 
Maybe via _/api/1.1/users/me_ or something like this. 

## Version Info
  - Directus version: 6.4.3

**Comment by WellingGuzman** [comment]
This is a good thing you asked this, we planned on adding this for some reason I can't find it.

This was meant to be an alias to `/api/1.1/users/<current-authenticated>`

Well I guess I'll add it.

![ba5 copy](https://user-images.githubusercontent.com/1531291/31581696-1dbbef08-b13f-11e7-8fee-df6d08e26fb0.jpg)

**Comment by WellingGuzman** [comment]
New endpoints:

```
GET /users/me
DELETE /users/me
PATCH /users/me
PUT /users/me
```

These are alias to (respectively):

```
GET /users/<authenticated-user>
DELETE /users/<authenticated-user>
PATCH /users/<authenticated-user>
PUT /users/<authenticated-user>
```

Closed by https://github.com/directus/directus/commit/9b589399c15e21ff7e22fe49b41c82f11aa25558

**Comment by cgarnier** [comment]
Please ... document new features... it s not yet in the API doc like lot of other things

**Comment by WellingGuzman** [comment]
Thanks @cgarnier I have added users endpoint to the docs. we will continue keep the docs up to date bit by bit.

Anything missing let us know and we will get it done.

Ref: https://github.com/directus/api-docs/commit/bc97d9122a893faa8cb192e1a6d5c77e2df3cda9
