### ISSUE TITLE
Filtering m2a (multiple relations to multiple collections)

### ISSUE THREAD

**Issue by fabFrankDouwes** [directus/directus#18999]
### Describe the Bug

We're experiencing issues when having multiple and/or m2a filters (both in the CMS filter field and when writing them as queries to use with collectionService.readByQuery().

**The situation is as follows:**
we have an article_page collection. an article_page can be related to multiple pages (of various page types) using a m2a field. For this example we're using 'overview_page' and 'person_page' specified in the articles_collections belongs_to field.

![Screenshot 2023-06-26 at 09 24 35](https://github.com/directus/directus/assets/58548091/3f6378e5-d4bf-4d86-8bce-baa0686f908b)

**this issue**
writing a filter (or composing one in the Directus CMS page filter) works as expected when using a single m2a, so 'get all article_pages that belongs_to overview_page with an id of 1' works fine.

![Screenshot 2023-06-26 at 09 20 22](https://github.com/directus/directus/assets/58548091/a79346d4-4dc2-41eb-87cd-48d4b45e1de9)

however, adding a second filter (with an _and) doesn't work.

![Screenshot 2023-06-26 at 09 14 24](https://github.com/directus/directus/assets/58548091/e7c43f3c-ebee-455b-b0f1-de6496a42957)

The same issue occurs when reversing the logic (using 'doesn't equal') or using an array (contains/doesn't contain).

 

### To Reproduce

1. create 3 collections, collection_a, collection_b, collection_c
2. create a m2a field on collection_a, select collection_b and collection_c as the options
3. create an instance of collection_b and collection_c
4. create an instance of collection_a, and select the instances of collection_b and collection_c in the m2a field.
5. filter the CMS (described above)

### Directus Version

v10.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
Hi @fabFrankDouwes! I think it's because you're filtering with an `_and`. You're effectively saying "Show all items where the related `item` is _both_ `overview_page:1` _and_ `person_page:1`. It can only be one! I think you're looking for an `_or` in this case 👍🏻
