### ISSUE TITLE
an issue with graphql

### ISSUE THREAD

**Issue by sanba-anass** [directus/directus#18993]
### Describe the Bug

so yesterday iwas using postman and https://hoppscotch.io/graphql , testing directus graphql all seems to work perfectly , today i have encountered this problem :
using postman :
![using postman](https://github.com/directus/directus/assets/83970851/733b98b7-104a-4e07-86d8-3b6e5f1562f8)
using hoppscotch:
![using hoppscotch](https://github.com/directus/directus/assets/83970851/6e5b7341-397b-451c-9531-f47352a8451d)

### To Reproduce

error message : 
"TypeError[count_functions.count]: Cannot convert to OutputType the following value: Object({ type: GraphQLScalarType({ name: \"Int\", description: \"The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1.\", specifiedByURL: undefined, serialize: [function serialize], parseValue: [function parseValue], parseLiteral: [function parseLiteral], extensions: {  }, astNode: undefined, extensionASTNodes: [] }) })"

### Directus Version

10.3.0

### Hosting Strategy

Self-Hosted (Custom)
```[tasklist]
### Tasks
```

**Comment by sanba-anass** [comment]
idid deleted my project and recreate another one with  my local postgres database , it works fine like for 2h then , the same issue occurs again and again

**Comment by sanba-anass** [comment]
[14:47:38] POST /graphql 500 47ms
[14:48:38] POST /graphql 500 21ms
i"don't know but the problem seems to be in the server side always when i restart the server this happens

**Comment by rijkvanzanten** [comment]
What does the data model for the `dragons` collection look like?

**Comment by sanba-anass** [comment]
![image](https://github.com/directus/directus/assets/83970851/9c8d42b0-58b4-4b47-a758-67dacc455f89)

![image](https://github.com/directus/directus/assets/83970851/51b81bb1-4bc1-4527-ac03-d3a0bd6cf321)
it's a simple collection nothing fancy . idon't know but i think the issue was with  [apollo graphql Extension](https://www.apollographql.com/docs/devtools/editor-plugins/) everytime i use it and restart the server this error keeps showing

**Comment by sanba-anass** [comment]
if u can investigate the problem that would be cool :)

**Comment by sanba-anass** [comment]
the issue still presist is it because i'm fetching data at the same directory as the project ? 
![image](https://github.com/directus/directus/assets/83970851/375c0a4d-e079-441c-9e22-a0851facc843)

**Comment by rijkvanzanten** [comment]
Just to be clear, this problem only happens when using the Apollo GraphQL VS Code extension? How many records exist in the `dragons` table?

**Comment by hotspot-app** [comment]
I get the same errors when querying the graphql endpoint. This should not be related to the VS Code extension as I am not using this it.

This also happens for the graphql/system endpoint. For example:

![image](https://github.com/directus/directus/assets/97624653/0765e10d-4a66-469f-8736-502562ab950a)

**Comment by hotspot-app** [comment]
I saw that i was on graphql version 16.7.1 (Possibly by running `npm update`). Downgrading to version 16.6.0 fixed it for me.

**Comment by sanba-anass** [comment]
> I saw that i was on graphql version 16.7.1 (Possibly by running `npm update`). Downgrading to version 16.6.0 fixed it for me.

![image](https://github.com/directus/directus/assets/83970851/6d0351dc-590d-40b5-9a57-b5580ed89f61)
did u edit the package-lock.json ?

**Comment by br41nslug** [comment]
I am able to reproduce this exact error by forcing an update of graphql to `16.7.1`. The API has graphql pinned to `16.6.0` https://github.com/directus/directus/blob/main/api/package.json#L114 make sure to install the correct version of dependencies.
