### ISSUE TITLE
Differences in result between api calls and web socket

### ISSUE THREAD

**Issue by jmjoary** [directus/directus#19002]
### Describe the Bug

When I make an api call on the files collection with a filter, the result provide me 4 items. If I do the same query using a web socket, I don't have any items.

### To Reproduce

1. Create a folder
2. Give authorization to read the file in this folder
3. Add some pictures
4. Compare api and subscription results

This api call provide me 4 results :
`https://directusURL//files/?filter={"folder": {"_eq": "FOLDER_ID"}}`

This web socket subscriptions provide me nothing
`_channel.sink.add(jsonEncode({
        "type": "subscribe",
        "collection": "directus_files",
        "query": {
          "filter": {
            "folder": {"_eq": "FOLDER_ID"}
          }
        }
      }));`

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
How are you listening for websocket responses? The subscribe request you have there works as expected here:
subscribe: 
```json
{
  "type": "subscribe",
  "collection": "directus_files",
  "query": {
    "filter": {
      "folder": {
        "_eq": "f5109dfb-f807-46a1-a434-7303b4cfebb3"
      }
    }
  },
  "uid": "5017e75b-61a7-47d4-a2b6-c7062aa259b2"
}
```
`init` response:
```json
{
  "type": "subscription",
  "event": "init",
  "data": [
    {
      "id": "0b9edc3c-8175-4fbf-81e3-e43b72f17c38",
      ...truncated...
      "folder": "f5109dfb-f807-46a1-a434-7303b4cfebb3",
      ...truncated...
    },
    {
      "id": "696eacaf-dc22-4cd3-ad3f-2bb9dfac0ab9",
      ...truncated...
      "folder": "f5109dfb-f807-46a1-a434-7303b4cfebb3",
      ...truncated...
    },
    {
      "id": "fc9f1455-a654-4299-9830-4352eba944b4",
      ...truncated...
      "folder": "f5109dfb-f807-46a1-a434-7303b4cfebb3",
      ...truncated...
    }
  ],
  "uid": "5017e75b-61a7-47d4-a2b6-c7062aa259b2"
}
```

Happy to keep discussion and re-open the issue if appropriate.
