### ISSUE TITLE
Sort items when many rows

### ISSUE THREAD

**Issue by dsivokhin** [directus/directus#1900]
## Version Info
  - Directus version and branch: develop
  - PHP version: 7.0
  - MySQL version: 5.7
  - Web server: nginx
  - OS name and version: Ubuntu

## Expected Behavior
Sort items when their more "Rows Per Page"

## Actual Behavior
I have 189 items in my table. Global setting "Rows Per Page" = 100
I try scrolling to end, and load all items and click on the button
![default](https://user-images.githubusercontent.com/4669992/31549396-b43c8370-b036-11e7-9ee2-f42c4b6d26ee.png)

but I see this error

![default](https://user-images.githubusercontent.com/4669992/31548862-01ef55cc-b035-11e7-8ceb-3094599a4b6a.png)

## Steps to Reproduce
 1.  Create table with sort column
 2.  Create many items > "Rows Per Page" in global settings
 3.  Try scroll and load all item on the page, click button to sort

**Comment by benhaynes** [comment]
The issue before was that items were on multiple pages, but now we use lazy-load/infinite-scroll. This script updates ALL items with a new incremental sort value, so it's pretty intensive for large quantities of records. So there are two options:

1. Update the notification to say: `There are too many items in this table to support reordering`

2. Check if all items are loaded on the page and allow reordering.

@WellingGuzman @parnas @rijkvanzanten – do you (or anyone else) have thoughts on this?

**Comment by rijkvanzanten** [comment]
Can we think of a way to know the new order value based on the records above and below the current one? Do we really need the whole list before you can reorder?

**Comment by benhaynes** [comment]
I mean, if we can think of a better way... great!

The key is, this needs to work with a basic SQL `SORT`. We could get into decimals, but that seems more convoluted and not good long term.

**Comment by dsivokhin** [comment]
Hello, It would be nice to make it possible to sort the filtered values too.

**Comment by benhaynes** [comment]
Presumably this would ONLY update the values that are currently filtered? Since the `sort` column is global, that could give unexpected results, but I see what you're saying.

**Comment by dsivokhin** [comment]
Yes, when sorting filtered items change only their `sort` value. 
Example 
![default](https://user-images.githubusercontent.com/4669992/31839821-6799e2a0-b5eb-11e7-970f-2f3cd80e9608.PNG)

**Comment by benhaynes** [comment]
This definitely works, the only issue is that it relies on the existing `sort` values being accurate and complete. So for instance, if something was added directly in the database, or a sort value was "off" for some reason, then issues could arise because at no point is everything "reset" (globally updated).

Still, this direction is worth considering! What does everyone think?

**Comment by rijkvanzanten** [comment]
@benhaynes This idea swaps the sort value of two items, so it doesn't really matter what the actual sort value was right? For all we know, you swap `sort=125` with `sort=A5Tx`

**Comment by benhaynes** [comment]
True – but if there are a lot of NULLs or values that are the same for some reason, this won't do anything.

**Comment by rijkvanzanten** [comment]
We're redesigning how sorting works in the next major version (7.0). We have taken this into consideration.
