### ISSUE TITLE
Group Disable not working

### ISSUE THREAD

**Issue by dflexRD** [directus/directus#19014]
### Describe the Bug

I would like disable whole group of field, but it didnt work.
I think it is good to let the group to disable its children fields.
thank you

![image](https://github.com/directus/directus/assets/65934642/2d0d49df-9f1f-4fcc-b065-aea4c819f59d)

### To Reproduce

Disable the group, and its children still working

### Directus Version

v9.24.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
This is technically working as intended but do feel free to make a [feature request](https://github.com/directus/directus/discussions/categories/feature-requests) instead.
