### ISSUE TITLE
Updating date time field through REST api doesn't match with original value

### ISSUE THREAD

**Issue by Tinloy-WCC** [directus/directus#19013]
### Describe the Bug

When updating a date time field through REST API, the date time value in Directus is always in UTC time, but not the value that the users' countries.

### To Reproduce

Update the date time field through Directus API

### Directus Version

v10.3.0

### Hosting Strategy

Directus Cloud

**Comment by br41nslug** [comment]
Can you elaborate on the problem you're seeing and the requests you're doing? The API doesn't do any time manipulation when saving unless there is explicit timezone data in the format like `2023-06-05T11:42:32+06:00` which will be resolved to UTC removing the 6hrs.
