### ISSUE TITLE
Wrong docker-compose example url in root docker-compose.yml

### ISSUE THREAD

**Issue by ceptonit** [directus/directus#19015]
### Describe the Bug

Looks like the docker-compose example url was not updated to the new url after the 10.4.0 changes to the docs.
https://github.com/directus/directus/blob/main/docker-compose.yml

### To Reproduce

Url on line 3 of https://github.com/directus/directus/blob/main/docker-compose.yml will get you a 404 error.

### Directus Version

v10.4.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
This is not an example intended for use and has a disclaimer at the top. 

> # This compose file is meant to spin up a copy of all supported database vendors + Redis and S3 (Minio).
> # For production use see the docker compose file example in the docs:
> #     https://docs.directus.io/self-hosted/installation/docker/#docker-compose
> #
> # ONLY FOR DEBUGGING. THIS IS NOT INTENDED FOR PRODUCTION USE.

**Comment by paescuj** [comment]
I think this was a small misunderstanding. It's important to understand that the example is not intended for production use, but the issue about the wrong link is valid 👍

**Comment by br41nslug** [comment]
It was 🙈
