### ISSUE TITLE
Get Started Postgre SQL Docker Script is Broken.  Cannot connect to Redis

### ISSUE THREAD

**Issue by ramseur** [directus/directus#19029]
### Describe the Bug

The get started instructions are broken : https://docs.directus.io/self-hosted/docker-guide.html

 They do not have a definition for 

- Network - without this no network will be created
- Volumes - without this you will get an error with postgreSQL

### To Reproduce

Simply try running the docker compose yml on the get started page.  You will get errors.

You can run my attached script.  If you see I have disabled all the redis information as the script will not work with redis.  You will get a connection error.  I have tried to bind to 0.0.0.0 or 127.0.0.1 and none of them work.

      
      

  
`
[docker-compose.yml.txt](https://github.com/directus/directus/files/11906971/docker-compose.yml.txt)

### Directus Version

v10.0.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
You're very right somehow `container_name` and `network` erroneously got added without the extra required fields breaking the getting started example. And the Redis environment configuration was updated without updating the directus version to the minimum required version for these new env variables.

Having said that:

> Network - without this no network will be created

Network is not a requirement for docker-compose and will create a default network for the docker-compose project. (given the services don't explicitly require it)

> Volumes - without this you will get an error with postgreSQL

Is defined so should not be throwing errors.

**Comment by ramseur** [comment]
This is still broken. I just tried it.  If you do not define the networks and the volumes postgreSQL will not work in all versions of docker. It wont even start.  Can you please re-open this?

![image](https://github.com/directus/directus/assets/5710902/0255f92e-7add-4070-90bd-2b8e2404aa74)

**Comment by br41nslug** [comment]
@ramseur this is the updated compose file :) https://github.com/directus/directus/blob/9dd79fca8ac6a29445936cccb30c7808e3b46227/docs/self-hosted/docker-guide.md#example-docker-compose
But removing the network section from your database (and any other services) should do the trick aswel

**Comment by ramseur** [comment]
@br41nslug Once you define the network, the network issue is resolved.  Many users who use your software do so in a real scenario therefore they define the network.  They do not leave docker to do it.  I have moved passed that issue.

Your new script still has the issue of the new Redis container and will NEVER work unless you change the port.

**Comment by ramseur** [comment]
The redis issue is discussed here and I have commented how to fix it : 

https://github.com/directus/directus/issues/19036

**Comment by br41nslug** [comment]
> Your new script still has the issue of the new Redis container and will NEVER work unless you change the port.

This is not true and tested :) The issue you were seeing was a mismatch in configuration values after the last update. Either using the new >10.4 config settings on an older version or vice-versa. The port will only be an issue once you both expose it (which is not necessary but you can if you want) and already have something running under that same port on your host machine.

**Comment by vamostamos** [comment]
@ramseur Great job to you and others
