### ISSUE TITLE
Date `second` function throws error as it includes milliseconds 

### ISSUE THREAD

**Issue by sanba-anass** [directus/directus#19023]
### Describe the Bug

graphql throws an error when fetching second  from  date_created_func or date_updated_func and return null  :
![image](https://github.com/directus/directus/assets/83970851/d4717816-3614-4f8c-a64b-f23ce0bc2701)
![image](https://github.com/directus/directus/assets/83970851/928f3f08-f19d-40ba-83cd-f3639aeb8339)

### To Reproduce

full error :

```
ERROR: Int cannot represent non-integer value: "30.318000"
"errors": [
    {
      "message": "An unexpected error occurred.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
```

### Directus Version

10.3.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
Looks like the second function here tries to include the milliseconds. What database are you using @sanba-anass?
