### ISSUE TITLE
Directus Docs 404 

### ISSUE THREAD

**Issue by BlackDahlia313** [directus/directus#19024]
### Describe the Bug

Go to Docs and search for something.

Any link that points to

https://docs.directus.io/app is now 404 (any pointing to reference is fine)

Example:

https://docs.directus.io/app/import-export.html

![image](https://github.com/directus/directus/assets/44903742/48ce8b49-bff7-4596-a3be-4c3a60236327)

### To Reproduce

^

### Directus Version

v10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by BlackDahlia313** [comment]
Looks when hitting the page from search the redirect thats assigned isnt working:

https://docs.directus.io/user-guide/content-module/import-export.html

is the new:
https://docs.directus.io/app/import-export.html

**Comment by BlackDahlia313** [comment]
Some links within the docs still link to old url too:

![image](https://github.com/directus/directus/assets/44903742/e83dd0e8-fc9e-45cc-8846-43eebd13e850)

**Comment by phazonoverload** [comment]
On it 🫡 We set up redirects, but as Vitepress does client-side nav, the Netlify redirects aren't kicking in.

**Comment by phazonoverload** [comment]
^ actually, this PR will not fix this. This is a broken search index, which also needs solving but is not the same issue. Still, these are related.

**Comment by maisur** [comment]
i got this error when try to access the docs.

![image](https://github.com/directus/directus/assets/47018830/58f8c050-1612-440d-aecf-4c22f079552a)

**Comment by rijkvanzanten** [comment]
This was fixed in https://github.com/directus/directus/pull/19026 👍
