### ISSUE TITLE
directus-extension link links the wrong directory

### ISSUE THREAD

**Issue by AndreKR** [directus/directus#19025]
### Describe the Bug

When running `npm run link` in an extension directory, it links the current directory instead of the `dist` directory.

### To Reproduce

* Create a new extension in some arbitrary folder outside your Directus installation using `npm init directus-extension@latest`. Make it for example an `operation` extension.
* Build the extension with `npm run build`.
* Set up a Directus installation in `/path/to/directus` and start it with `npx directus start`.
* Back in the extension directory run `npm run link /path/to/directus/extensions/operations`.

A symlink `/path/to/directus/extensions/operations/directus-extension-my-extension` is created but the symlink points to `extension-dir` instead of `extension-dir/dist`. The extension doesn't work if the built files are in the `dist` directory.

### Directus Version

v9.26.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
Please update to the latest version of Directus before opening an issue 👍🏻 Happy to reopen this if this is still an issue on the latest version.
