### ISSUE TITLE
Calling the DELETE method for items is always limited to 100 items

### ISSUE THREAD

**Issue by TLMondo** [directus/directus#19022]
### Describe the Bug

So I updated the `docker-compose.yml` file to include: `QUERY_LIMIT_MAX: -1`, and the did a pull and rebuild (because I know I was a micro version behind). Still only showing `100` deletes at a time. More interesting, the UI shows: `35,551` items the DB shows: `68,654` (much closer to the starting 70,000 I then tried to change the query parameter to `limit=10000` and `limit=1000`, but both work the same... capped at `100`

### Dockerfile
```
FROM directus/directus:10.4.0
WORKDIR /directus

USER root
RUN npm i -g pnpm
RUN pnpm i @directus/sdk@beta
RUN pnpm i directus-extension-field-actions
RUN pnpm i directus-extension-group-modal-interface
RUN pnpm i directus-extension-sanitize-html
RUN pnpm i directus-extension-sparkline-display
```

### docker-compose.yml
```
    environment:
...
      QUERY_LIMIT_MAX: -1
...
```

Make REST endpoint call for DELETE
```
DELETE {{baseURL}}/items/{collection}}
```

body: 
```
{ “filter”: {“id”: { “_gt”: “0" }} }
```

### Directus Version

10.4.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
In addition to `QUERY_LIMIT_MAX`, there's the `QUERY_LIMIT_DEFAULT` config which takes effect here and defaults to 100 if you don't specific a limit in the request itself. See
- https://docs.directus.io/self-hosted/config-options.html#general
- https://docs.directus.io/reference/query.html#limit

**Comment by TLMondo** [comment]
> In addition to `QUERY_LIMIT_MAX`, there's the `QUERY_LIMIT_DEFAULT` config which takes effect here and defaults to 100 if you don't specific a limit in the request itself. See
> 
> * https://docs.directus.io/self-hosted/config-options.html#general
> * https://docs.directus.io/reference/query.html#limit

Perhaps I'm reading this wrong, but I AM specifying a limit in the request. See the last sentence of the description:
```
I then tried to change the query parameter to limit=10000 and limit=1000, but both work the same... capped at 100
```

**Comment by TLMondo** [comment]
Solved. So instead of the query parameters like the document references, I put it in the JSON body, and now it works.

<img width="664" alt="image" src="https://github.com/directus/directus/assets/7502754/dd80a7c2-4ec8-4f9d-b8b4-dbf069b6c3cb">
