### ISSUE TITLE
Slug: Change ß to ss 

### ISSUE THREAD

**Issue by BennerGe** [directus/directus#1902]
In Germany some words contain the letter **ß**, this should be display as **ss** in the slug field. 

## Version Info
  - Directus version: 6.4.3

## Expected Behavior
Change **ß** in title to **ss** in slug

## Actual Behavior
_ß_ leads to nothing

## Steps to Reproduce
 1. Create title called 'Fußball'
 2. Computed slug is 'fuball'

**Comment by rijkvanzanten** [comment]
Hey @BennerGe! Thanks for the heads up. Are there more characters we can think of that might cause similar problems @benhaynes @WellingGuzman?

**Comment by BennerGe** [comment]
Yes, we have some more weird chars in Germany :-D

ä --> ae
ö --> oe
ü --> ue

**Comment by rijkvanzanten** [comment]
This is probably going to be a way bigger overall thing to fix, since those conversions will probably be different for most languages 😳

**Comment by WellingGuzman** [comment]
I do not have experiencing with these chars, but as far as my knowledge goes, this are how in German are represented, and may be different in other language as @rijkvanzanten says.

Would it be weird changing it from `ä --> a`, etc. I know it may look like another word.

@BennerGe how do other websites/apps/etc handle this in the german language? translating to its actual sound/value?

Maybe we can use this against the current localization?

**Comment by BennerGe** [comment]
Wordpress handles this different, depending on the configured language. 
If German is configured, `ß --> ss and ä --> ae`, in English `ß --> s and ä --> a`.

I think a good way would be to convert `ä, ö, ü --> a, o, u` and `ß --> ss`.
ß exists only in German, so this conversion should be okay.

**Comment by WellingGuzman** [comment]
I think we can do the conversion based on the user localization, but this may not work, if there's different people using different localization.

I think we should at least go for Eszett and other possible german-only characters, and keep improving this as we learn more about all this.

**Comment by wittwerch** [comment]
Have you thought about using an existing library for that? 

https://github.com/cocur/slugify

**Comment by WellingGuzman** [comment]
It's a good idea to use something like that. I was thinking on when on how to use the locale, should it be based on the user locale and set default to English?

For example, if it's a German project, but my users locale are English, then the umlaut won't be translate to the actual meaning: `ä --> ae` but rather `ä --> a`.

Should it be based on configuration (global) or slug interface settings?

**Comment by BennerGe** [comment]
I think it should be based on the global configuration and not on the configured language of the current user. 
Would be quite confusing if the conversion acts different for different users. Additionally the slug would change, when a user with another language updates the entry.

**Comment by benhaynes** [comment]
I'm not sure that we have a global locale/language right now – but if we don't we should add one into the Config or Global Settings. Then the default user locale and all character conversion (eg: slugs) should match the project default.

I like having things like this in the config because changing them is a big deal with big consequences. BUT, for our Hosted platform that means that this is not editable (no server access). Thoughts?

**Comment by rijkvanzanten** [comment]
Why does this have to be in the config file? Couldn't it be a setting in the global settings pane in the Directus admin itself?

**Comment by benhaynes** [comment]
It doesn't need to be in the config, my only concern is that if it's in the Global Settings that it's easier to change... but if it's changed then slugs may update and links could break. I'm fine with Global Settings though... we can add a warning note to the column.

**Comment by WellingGuzman** [comment]
> Additionally the slug would change, when a user with another language updates the entry.

Exactly that's a huge problem.

> I'm not sure that we have a global locale/language right now

We can use the `directus_users.language` default value as the global one, our it will be too odd to find. or should we add another one app level in the configuration?

> for our Hosted platform that means that this is not editable (no server access)

For hosted platform I always think that we should implement way (same as CORS) to update their their config that will be generated to the current user instance configuration, so I think this could be easily implemented.

**Comment by WellingGuzman** [comment]
> I'm fine with Global Settings though... we can add a warning note to the column.

Now reading that again global settings, on the admin. that's a good option too. I always can't tell the line between when it should be on global settings or in the configuration files

**Comment by benhaynes** [comment]
Yeah – I think we should use Global Settings with a warning... MOST things should go into Settings (instead of the config) so that app users can manage things without server access.

**Comment by WellingGuzman** [comment]
Agree @benhaynes. Also I'm thinking on implementing a smaller version of the slugify @wittwerch recommended, just to keep it things smaller and use only the translation we support, and we use their data.

**Comment by rijkvanzanten** [comment]
@WellingGuzman Are we going to implement the slug logic server side or client side?

**Comment by WellingGuzman** [comment]
That's a concern we need to figure it out somehow for the new API, because the server should be self sufficient. (See https://github.com/directus/directus/issues/1911)

This functionality are done using the interfaces and all API user don't have.

I don't know if this would be a overkill, but it would be good to have the client as "example" but the real result would be the API? this can bring confusion if there's a bug in one of them.

**Comment by rijkvanzanten** [comment]
Yeah.. The alternative is shooting a "slug"-request to the API on input of the slug interface (debounced ofc), but that also feels a bit overkill as the client-side implementation works just as fine (and is probably faster)

**Comment by WellingGuzman** [comment]
too bad we are not using the same code for the server and the client. *wink* *wink*

**Comment by rijkvanzanten** [comment]
This has been fixed in ac4ea4db97e5138aa72afaec176be9357c07e0e6 on the develop branch and will be released soon!

![2017-11-09 14_41_37](https://user-images.githubusercontent.com/9141017/32626040-21114f78-c55c-11e7-8c9f-c4e7ef3059fa.gif)
