### ISSUE TITLE
Fatal error: Allowed memory size  exhausted

### ISSUE THREAD

**Issue by BennerGe** [directus/directus#1904]
I've got an fatal error with the current development branch, after logging in. It seems that commit ef3c4b6d6d39a13281b94c57164e437c1386f9e3 causes this error.

The complete error message is 
`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/directus/api/core/Directus/Permissions/Acl.php on line 458` 

If I remove either the second condition of the if-clause or the exception throw, the error doesn't occur anymore. 

https://github.com/directus/directus/blob/f55490063dfba5473b7b9a1573a6171c7ddb77d7/api/core/Directus/Permissions/Acl.php#L454-L459

## Version Info
  - Directus version and branch: 6.4.3 – f55490063dfba5473b7b9a1573a6171c7ddb77d7
  - PHP version: 7.0
  - OS name and version: Ubuntu 16.04

Edit: memory_limit is 128M, but even 512M is not working.

**Comment by WellingGuzman** [comment]
Can you share your logs? (api/logs)?

**Comment by BennerGe** [comment]
No, unfortunately not. There's no file existing (directory is writeable). 
But I will try it tomorrow on another system.

**Comment by benhaynes** [comment]
Hey @BennerGe – any luck? We'd love to replicate this so we can fix/close. :)

**Comment by BennerGe** [comment]
Sorry for the long delay. I've tried it now on my other system which has basically the same software running (same OS, same PHP version), but I cannot reproduce it here. 
Maybe I'll find something in the php error logs. Do you have any idea what could raise this error?

**Comment by rijkvanzanten** [comment]
Hey @BennerGe! Thanks for the information. Maybe the PHP config was cached or something had to be restarted in order for the settings to take effect?

**Comment by BennerGe** [comment]
I think there's a little missunderstanding. The problem still exists on my desktop pc, I haven't solved it there. Only on my laptop it's running fine. 

I have put now a error_log right above the if-clause for debugging. Tthis leads to 139 entries to php's error log file from only one request (directus/login.php). I don't think that this should be called that often. Maybe a clean installation of directus will solve this problem.
