### ISSUE TITLE
Show a link to the item opens /items/directus_users instead of User Directory

### ISSUE THREAD

**Issue by grefrit** [directus/directus#19052]
### Describe the Bug

Show a link to the item in One to Many relation ship, forwards user to /items/directus_users/:id, instead of /users/:id. Because of that, user can see unnecessary fields, like Last Page and Last Access 

### To Reproduce

Create one to many relationship to directus_users model with Show a link to the item setting enabled. Click on that link

### Directus Version

v10.4.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
> Didn't this used to be an option? I don't see anywhere that we can even disable the link anymore in 10.4.2 or 10.4.3.

Nothing changed with respect to the item link toggle itself. It is disabled by default so you need to enable it first.
![image](https://github.com/directus/directus/assets/9389634/c9c01613-3334-4508-b627-bdc6afa766c8)

**Comment by rijkvanzanten** [comment]
This is caused by the fact that the link links to the "same" route (item detail), which therefore skips the route navigation guards that normally rewrites the link to /users.

**Comment by DustinBracy** [comment]
Ah thanks @br41nslug, I was looking at a M2O field and not seeing the Item Link setting.  I see it now that I'm looking at a O2M field.  I guess it's always enabled on many to one fields?
