### ISSUE TITLE
Links don't use anchor tag

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1905]
## Version Info
  - Directus version: 6.4.x

## Problem
All links on the page (navigation, table rows etc) are regular text elements with an onclick handler instead of an anchor element `<a>`. This problem has been mentioned on the [feature request tool](https://request.getdirectus.com/r/52) as well.

I raise it as an issue here since I don't feel like this is a feature, but a major design flaw in terms of accessibility and usability. No navigational items can be focussed by keyboard users, screenreaders don't know they're actual links and thus read them as regular text, and other keyboard based navigational tools and extensions like [Vimmy](https://github.com/gggritso/Vimmy.safariextension) are rendered useless.

**Comment by benhaynes** [comment]
Fair enough. We can start to swap these out, but need to be careful not to break anything along the way. Many of the JS selectors use the element type to monitor events, so this could have adverse effects.

**Comment by rijkvanzanten** [comment]
At the moment, all core developers are working fulltime on the next major version of the platform, so I'll have to leave this open as a help-wanted. If anyone is inclined to take a swing at fixing this, a PR is very welcome 😄

Ps: This already has been implemented in the alpha version of 7.0

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/10)
