### ISSUE TITLE
filter in flows not working as expected

### ISSUE THREAD

**Issue by Zack-Heisnberg** [directus/directus#19054]
### Describe the Bug

i am not sure here what i am doing wrong so i tried

              {
                  "filter": {
                      "$and": [
                          {
                              "email": {
                                  "_eq": "{{$trigger.body.email}}"
                              }
                          },
                          {
                              "phone": {
                                  "_eq": "{{$trigger.body.phone}}"
                              }
                          }
                      ]
                  },
                  "fields": [
                      "email",
                      "phone",
                      "tfa_secret"
                  ]
        }

with both $or and $and

the results always return all the users as there is no filter at all

### To Reproduce

make a flow , read data with a filter that have $and or $or

### Directus Version

v9

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
Logical operators start with an underline, so `_and` instead of `$and`, see also https://docs.directus.io/reference/filter-rules.html#logical-operators.
