### ISSUE TITLE
collection got corrupted causing internal server error in related places

### ISSUE THREAD

**Issue by tzoor-eanygo** [directus/directus#19063]
### Describe the Bug

after changing a collection and going to add an item of it i encountered the following error:

![Screenshot 2023-07-05 at 10 52 31](https://github.com/directus/directus/assets/134547377/bd2723bb-753e-4262-ba64-8f7486758964)

im not sure what exactly caused this.

the affected collection is rather simple, nothing fancy in it at all.

i am evaluating directus for my use case and am using the package directly without docker as i prefer so.

help me clarify further if need be.

### To Reproduce

[data.db.zip](https://github.com/directus/directus/files/11955452/data.db.zip)

if it is acceptable, use the dump above to recreate, i cant assure the safety of the file, but i promise its not malicious for what its worth, i just dont currently have a better idea of how to recreate this issue.

this happens when either:
1. going to `content -> form_components`
1. going to `content -> form_components -> create item -> fill required field and submit` (the item is added to the database)
1. or going to `content -> forms -> an item that is related to form_components items (there is only one in the data.db file)`

### Directus Version

v10.4.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
What database vendor is that dump for?

**Comment by tzual** [comment]
> What database vendor is that dump for?

SQLite

**Comment by rijkvanzanten** [comment]
@tzual  / @tzoor-eanygo 

> after changing a collection [...]

What did you change on the collection? I'm also seeing a `form_components_1` that exists next to `form_components`, is that intentional?

**Comment by rijkvanzanten** [comment]
Not entirely what caused it, but one of the relationships is misconfigured, which causes this symptom to show up. Directus Relations item `27` has a `one_field` configured to `id`, which is the primary key of the related collection. The related primary key isn't a valid alias field for the o2m pointing back 🤔 

<img width="725" alt="CleanShot 2023-07-09 at 16 55 18@2x" src="https://github.com/directus/directus/assets/9141017/34f10f10-b494-4cc2-bde7-2470a545e9c2">

I'll have to close this for now as there's no way to for me to reproduce that setup without clearer reproduction steps, but setting that `id` to `null` should at least resolve the error you're facing 👍🏻

**Comment by tzual** [comment]
> @tzual  / @tzoor-eanygo 
> 
> > after changing a collection [...]
> 
> What did you change on the collection? I'm also seeing a `form_components_1` that exists next to `form_components`, is that intentional?

Unfortunately, i dont remember what i changed before this happened.

the `form_components_1` collection was **not** intentional.

this is a good lead as i was messing with the relation of `form` and `form_components`.

**Comment by rijkvanzanten** [comment]
@tzual Please do let me know here if/when you run into the same issue again! It's hard to tell now if that wrong `id` value came from a bug, or from some experimentation that went wrong. Happy to reopen if the same problem occurs again and we have a solid idea of what caused it 🙂

**Comment by tzual** [comment]
> @tzual Please do let me know here if/when you run into the same issue again! It's hard to tell now if that wrong `id` value came from a bug, or from some experimentation that went wrong. Happy to reopen if the same problem occurs again and we have a solid idea of what caused it 🙂 

will do that. Thanks for your time
