### ISSUE TITLE
Login url redirection does not word as documented

### ISSUE THREAD

**Issue by aliemba** [directus/directus#19069]
### Describe the Bug

https://directus.myserver.com/auth/login/google?redirect=https://client.myserver.com/login

Doing this will not redirect to "https://client.myserver.com/login"

But something like this;
https://directus.myserver.com/admin/https://client.myserver.com/login

The documentation states that it should. 

### To Reproduce

Link to the login via https://directus.myserver.com/auth/login/google?redirect=https://client.myserver.com/login

### Directus Version

v10.4.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
> The documentation states that it should.

Mind sharing what docs page you're referring to?

**Comment by rijkvanzanten** [comment]
Might be related to change https://github.com/directus/directus/pull/17939

**Comment by aliemba** [comment]
Sorry about that; here it comes
 
https://docs.directus.io/self-hosted/sso.html#seamless-sso

**Comment by BlackDahlia313** [comment]
hmm... I had just set this up and the redirect was working in my instance. I'm still on 10.3. I can upgrade to confirm.

**Comment by BlackDahlia313** [comment]
> hmm... I had just set this up and the redirect was working in my instance. I'm still on 10.3. I can upgrade to confirm.

I am seeing the expected functionality. I see you arent using docker. I'm wondering if a proxy is messing up the redirect somehow.

**Comment by aliemba** [comment]
I have done son tests on this; it seems to work via the SSO as expected. I assumed that the redirect would be the same with the "non SSO redirects".

Something like this:
https://directus.myserver.com/auth/login?redirect=https://client.myserver.com/login

**Comment by rijkvanzanten** [comment]
As far as I can tell, things seem to be working as documented 👍🏻
