### ISSUE TITLE
The getExtensionsRealPaths() function is unable to correctly recognize Symbol Link directories created by "directus-extension link."

### ISSUE THREAD

**Issue by luochuanyuewu** [directus/directus#19064]
### Describe the Bug

As described in the title, this issue results in Vite being unable to detect changes in my app extension code and thus fails to trigger hot reloading.

To make hot reload works, i havo to change some code in getExtensionsRealPaths() of vite.config.js

Change
`if (!fs.lstatSync(extensionTypeDir).isDirectory()) return;`
to
`if (!fs.statSync(extensionTypeDir).isDirectory()) return;`

[Reference:](https://nodejs.org/api/fs.html#statsisdirectory)
words in node docs:
"If the [<fs.Stats>](https://nodejs.org/api/fs.html#class-fsstats) object was obtained from [fs.lstat()](https://nodejs.org/api/fs.html#fslstatpath-options-callback), this method will always return false. This is because [fs.lstat()](https://nodejs.org/api/fs.html#fslstatpath-options-callback) returns information about a symbolic link itself and not the path it resolves to."

### To Reproduce

1.A local development environment for Directus has been set up in the directory d:/directus.

2.A new Directus bundle extension has been created locally using "npm init directus-extension@latest" in the directory d:/mybundle. It includes an app extension called "testmodule".

3.In the mybundle directory, run "npm run link ../directus/api/extensions" (requires administrator privileges) and then run "npm run dev".

4.In the directus directory, run "pnpm --filter api dev" and "pnpm --filter app dev".

5.Currently, making changes to the code of testmodule does not trigger hot reloading in the Directus app.

### Directus Version

v10.4.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
Wanna open a PR for that @luochuanyuewu ? 🙂

**Comment by luochuanyuewu** [comment]
> Wanna open a PR for that @luochuanyuewu ? 🙂

Sure, [here ](https://github.com/directus/directus/pull/19074)is the PR.
