### ISSUE TITLE
I'm getting a 502 error after moving the directus app to a different server.

### ISSUE THREAD

**Issue by Mich5** [directus/directus#19061]
### Describe the Bug

 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received.

![image](https://github.com/directus/directus/assets/16474937/c150aa0e-f9a2-48e2-8279-d09842f425ae)

Any ideas on how I can resolve this? 

### To Reproduce

1. Copy directus files from a working installation to a different server or directory
2. Make sure directus is connecting to the same database by checking the .env file
3. Run directus

### Directus Version

V10.4.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
This seems to be more of a question than an actual problem with Directus itself. Please take a look at https://docs.directus.io/getting-started/support.html to see how you can get help.
I'll proceed to close this but if you think this is actually an issue with Directus itself, then please do not hesitate to comment. Thanks!
