### ISSUE TITLE
Kanban layout cards only show raw values in the 'Card Text' field

### ISSUE THREAD

**Issue by magnus-bb** [directus/directus#19065]
### Describe the Bug

When using a WYSIWYG text field for the Kanban layout's 'Card Text', the card previews do not use the Display Formatted Value that is normally used in e.g. the Table layout. This results in the card text including HTML tags. If the field is a Markdown field instead, the text will include MD syntax etc. I have tried all kinds of different options for formatting the display value.

In a perfect world the value would be rendered as text with the applied formatting, but just making it readable (as the current Table view does) would be a fix to this problem.

An example of how the card text is displayed with a WYSIWYG field in the Kanban layout:
![image](https://github.com/directus/directus/assets/51884390/785fd945-ff12-41bc-9da9-7be060479d5d)

An example of how the same text is displayed in the Table layout:
![image](https://github.com/directus/directus/assets/51884390/bfb0ba38-a0c5-41df-b5cd-7b7fd48c7c71)

The Display settings for the field:
![image](https://github.com/directus/directus/assets/51884390/e1ae3414-18a9-4b3b-bb65-ef974c3b93ab)

You're doing a great job with Directus!

### To Reproduce

1. Create an empty Directus project
2. Create a collection (e.g. Tasks)
3. Set a WYSIWYG text field for the collection with a Display option of 'Formatted Value'
4. Go to the Tasks content page of directus, create an entry with some formatting in the WYSIWYG field
5. See the column in the Table layout and then switch to the Kanban layout and set the WYSIWYG field as the 'Card Text' to see the HTML tags in the card preview.

### Directus Version

v10.4.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by magnus-bb** [comment]
I am new to open source contributing, but I'll give it a shot :+1:

**Comment by zozito** [comment]
Another issue you have on Kanban is, when you have a Repeater entry the values will show in the Kanban card.

![image](https://github.com/directus/directus/assets/4005288/7feb61f5-4943-4900-b76f-76f4dc776da9)

![image](https://github.com/directus/directus/assets/4005288/d2fe5841-b762-47c1-af73-7eff6b47a4d9)

**Comment by magnus-bb** [comment]
> Another issue you have on Kanban is, when you have a Repeater entry the values will show in the Kanban card.
> 
> ![image](https://user-images.githubusercontent.com/4005288/252308224-7feb61f5-4943-4900-b76f-76f4dc776da9.png)
> 
> ![image](https://user-images.githubusercontent.com/4005288/252308390-d2fe5841-b762-47c1-af73-7eff6b47a4d9.png)

Generally the display values on Kanban cards are not used or not functioning correctly. The problem @zozito mentions seems to be related to how the component `<display-labels>` is implemented:
https://github.com/directus/directus/blob/816f7dc00a4b94250f11086b71440fd83c9fcb38/app/src/layouts/kanban/kanban.vue#L57C9-L61C11.

Additionally I noticed that the `<render-display>` component cannot handle markdown even when using the `<render-display>` component that works for WYSIWYG and the field is set to Display a formatted value:
![image](https://github.com/directus/directus/assets/51884390/15768d43-7bf6-4041-97b0-6006840095bb).

I will shortly create a PR that fixes the WYSIWYG display by using the `<render-display>` component , but I am pretty sure that these other issues will require a deeper dive into the relevant components by someone other than me.
