### ISSUE TITLE
Single-File errors

### ISSUE THREAD

**Issue by oOAeroOo** [directus/directus#1907]
## Version Info
  - 6.4.0
  - PHP version: 7.x
  - MySQL version: 5
  - Web server: Apache2
  - OS name and version: 

Import image url not working for several image files.

## Steps to Reproduce
 1. Create a table with a "Single-File"-Relation.
 2. Upload some images
 3. try https://i.pinimg.com/originals/63/dd/d7/63ddd7f601b6c9961e83fc5f45bd67f5.gif
and 
https://cdn.boldomatic.com/content/post/9QANZw/I-love-you-as-much-as-Kanye-West-loves-Kanye-West?size=800
and
https://31.media.tumblr.com/tumblr_lfl0nuPiYO1qdzjnp.gif

You get two different error messages "
"undefined index: extension"
and 
Attempting to write an array as the value for column `directus_files`.`size.
the third image will not be saved correctly and is not shown after saving (initially it was shown)

**Comment by WellingGuzman** [comment]
I can't reproduce the `directus_files.size` issue.

The missing extension has been reported here: https://github.com/directus/directus/issues/1852

**Comment by oOAeroOo** [comment]
And what about the "undefined index: extension" error?

**Comment by rijkvanzanten** [comment]
Some weeks have passed since this issue was reported and we haven't been able to reproduce it since. We'll reopen if this issue comes up again or is reproduces.

**Comment by sayak-brm** [comment]
I get this issue... 
![image](https://user-images.githubusercontent.com/5992716/46320708-403df480-c5fd-11e8-88c1-dfd54b74c40c.png)

**Comment by sayak-brm** [comment]
The image I imported was from a URL, and the URL did not contain the extension of the image.
Image URL: https://lh3.googleusercontent.com/cZvPf2sQKT_f_7dI1ydDRaKyeOzILiVopwwl7tcgTbxv1WcAFxbma7RikZdmAeocE2U8O4FTzNmM=w500-h750-rw
I can't even upload the file from the file-library.
![image](https://user-images.githubusercontent.com/5992716/46320928-34066700-c5fe-11e8-88d0-f6b26e4ff2bc.png)
