### ISSUE TITLE
Block editor inline styling quirky on Firefox

### ISSUE THREAD

**Issue by simonflick** [directus/directus#19071]
### Describe the Bug

I have noticed 2 bugs:

1. normal text is always seen as bold by the editor. Removing bold on normal text makes it use a light font weight
2. underline cannot be removed if you select the whole underlined text

### To Reproduce

I'm using Firefox 115.0 on Windows 11 and was unable to reproduce these bugs on Microsoft Edge.

Bug 1:

1. open block editor with all elements enabled
2. write "Lorem ipsum dolor sit amet.", save the item and open it again
3. Select the word "ipsum". The toolbar will show the text as bold
4. Click on "bold". The text will get lighter and you cannot save
5. Select the whole line and make it light by clicking on "bold"
6. Now select a word and make it bold. It will now work

https://github.com/directus/directus/assets/19348971/ecf3a688-dd84-4e95-a9fe-b693c38f67c5

Bug 2:

1. open block editor with all elements enabled
2. write "Lorem ipsum dolor sit amet."
3. select the whole line and click "underline"
4. deselect the text to make the toolbar disappear
5. select the whole line again and click "underline". It will not remove the underline
6. select a single word and click "underline". It will expand the selection and start working again

https://github.com/directus/directus/assets/19348971/f48dc3cf-7aeb-4250-88bb-a6589aa6f97a

### Directus Version

v10.4.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Krishna2323** [comment]
@rijkvanzanten, I'm interested in taking this up.
