### ISSUE TITLE
Editing "Timestamp"-Field

### ISSUE THREAD

**Issue by oOAeroOo** [directus/directus#1908]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus version and branch: 6.4.0
  - PHP version: 7
  - MySQL version: 5
  - Web server: (Ex. Apache, nginx or IIS?) Apache2
  - OS name and version: Ubuntu TLS 16.04

Editing a field comment for an "Timestamp" DateTime-Field throws MySQL-Errors.
You only can change values for new columns but not for existing ones

## Steps to Reproduce
 1. Create a new table
 2. Add a DateTime Filed with "TimeStamp"
 3. Save
 4. "Add Comment"
 5. save -> error

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/6a5a1ac91d13a4a03876599a369454f9c3c5f0bb
