### ISSUE TITLE
"Page not found" upon collections creation - Database permissions

### ISSUE THREAD

**Issue by AristideBH** [directus/directus#19088]
### Describe the Bug

Deploying Directus on my VPN running Debian 11 and Docker 24.0.3, I get a weird error when I try to create a collection.

When I fill the minimal config to create a collection (name field), I get the little toast notifying me that the collection has been created, but instead of redirecting me to the correct page, it just shows "Page not found".

Then, navigating to the collection itself, I get the same error.

Upon collection creation, the directus log show this, so its seems that it does its job.
```
directus  | [10:42:50] POST /collections 200 219ms
directus  | [10:42:50] GET /collections 200 14ms
directus  | [10:42:51] PATCH /users/me/track/page 204 43ms
```
Restarting the server with 'docker compose up' seems to restablished the saved data. 
I also noticed that every so often, the directus log states 
```
cache     | 1:M 07 Jul 2023 10:35:23.036 * 100 changes in 300 seconds. Saving...
cache     | 1:M 07 Jul 2023 10:35:23.053 * Background saving started by pid 19
cache     | 19:C 07 Jul 2023 10:35:23.065 * DB saved on disk
cache     | 19:C 07 Jul 2023 10:35:23.066 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
cache     | 1:M 07 Jul 2023 10:35:23.154 * Background saving terminated with success
```
This does correct the problem without restarting the server, and my collections are accessibles.

I also noticed that the 'database' volume folder get its permissions reajusted everytime the container is spinned. 
I manually set them to 777 to test, but it reverts back to 'drwx------------' automatically.

When the collections are finally editable, the same "Page not found" behaviour appears when creating new items.
Untill I restart container or wait for the cache to trigger '100 changes in 300 seconds. Saving...'

I actually have a friend who's had the exact same problem runing similar config...
Any help's appreciated, thanks in advance.

### To Reproduce

Here's my `docker-compose-yml` file : 
```compose
version: '3'
services:
  database:
    container_name: database
    image: postgis/postgis:15-master
    volumes:
      - ./$DIRECTUS_DATA_FOLDER/database:/var/lib/postgresql/data
    networks:
      - directus
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'directus'
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD

  cache:
    container_name: cache
    image: redis:7
    command: --port 6380
    networks:
      - directus

  directus:
    container_name: directus
    build:
      context: './'
      dockerfile: Dockerfile
    ports:
      - 8055:8055
    volumes:
      - ./$DIRECTUS_DATA_FOLDER/uploads:/directus/uploads
      - ./$DIRECTUS_DATA_FOLDER/extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6380'

      KEY: $DIRECTUS_KEY
      SECRET: $DIRECTUS_SECRET
      ADMIN_EMAIL: $DIRECTUS_EMAIL_ADMIN  
      ADMIN_PASSWORD: $DIRECTUS_PASSWORD_ADMIN

      PUBLIC_URL: $DIRECTUS_PUBLIC_URL
      WEBSOCKETS_ENABLED: true
      FLOWS_EXEC_ALLOWED_MODULES: directus-extension-editorjs

networks:
  directus:
```
The `Dockerfile` :
```
FROM directus/directus:10.4.2

USER root
RUN corepack enable \
  && corepack prepare pnpm@8.3.1 --activate

USER node
RUN pnpm install directus-extension-editorjs
```

And here is the `.env` example :
```
DB_USER=directus
DB_PASSWORD=directus
DB_DATABASE_NAME=database

# RUN `openssl rand -base64 24` twice to output keys
DIRECTUS_KEY=some_random_key
DIRECTUS_SECRET=some_random_key

DIRECTUS_PUBLIC_URL=https://example.com
DIRECTUS_EMAIL_ADMIN=admin@example.com
DIRECTUS_PASSWORD_ADMIN=D1r3ctu$

DIRECTUS_DATA_FOLDER=app_data
```

**Edit :** 

- Creating a new Insights gives no problem and appeared instanlty upon creation. 
- Adding a photo inside the library failed at first, but setting the 'uploads' folder's permissions with `chmod 777 uploads` fixed that, and I successfully uploaded the photo.
- Trying to give 777 permissions to 'database' folder while the server is running, doesn't change anything to the issue.

### Directus Version

V10.4.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by AristideBH** [comment]
Here's a public repo as a boilerplate to speed things up if tests are needed :
[DirectusVPN](https://github.com/AristideBH/directusVPN)

Made a little script to scaffold the upload and extensions folders, bug is present wheter I execute it or not.
`sudo ./scripts/scaffold_dirs.sh`.

**Comment by rijkvanzanten** [comment]
You could try disabling the schema cache to debug if it's Redis or the database that's causing the issue, but I'm afraid we won't be able to help you further with this, as it's seemingly an issue in Docker volumes on that specific environment and folder structure, rather than a bug in Directus itself.

**Comment by AristideBH** [comment]
Hello and thanks for your answer.
After further inspections and many tests, I may finally have found what seems to be the problem, 
and while I've got not explanations for it, it seems more simple than a cache problem.

Commenting the "extensions" line volume from the Directus container did the trick,
even thought I had none loaded or even installed.
` # - ./$DIRECTUS_DATA_FOLDER/extensions:/directus/extensions`
 
My `app_data/extensions` folder, as well as any of its folder children, have full 777 permissions.
They were made with a  script I made (`./scripts/scaffold_dirs.sh`), and if they were inexistents upon instanciation, 
Directus would throw some errors about them not being accessible.

One other change I copied somewhere on Github (sorry, can't remember who), 
was to prefix containers' name. But I doubt that has any effect.

I updated my [repo](https://github.com/AristideBH/directusVPN) to reflects theses changes if further tests are needed.

Anyone able to test or confirm please?
I'll eventually need to install some extensions and this seems to be the culprit.

**Comment by rijkvanzanten** [comment]
I personally don't have a Debian 11 environment available, so I won't be able to help confirm/deny/debug this..

**Comment by AristideBH** [comment]
Well, my previous findings are not a solution :'(
Disabling the extensions volume did a trick for about a day, but the bug came back as it.

I've look at many things, sourcing details from other posts and issues, but I couldn't find anything working.

Decided to look at my server Ram usage adn its seems its rapidly topping up to 100%,
as I've only got a limited plan with only 1Go ram on Hostinger.

I followed that finding by running 'htop' and tracked services that could be a issue, but I'm really not an expert.
Don't know if that is a normal behaviour, or a duplicate glitch, but both `node /directus/cllis.js start` and `usr/bin/dockerd -h fd://...` are running multiple times (with different PID)
![image](https://github.com/directus/directus/assets/11951633/3d64b0d1-8d96-4a29-863f-90d32385cd79)

Could that be the culprit ? 
Is there any hardware requirements for a smooth self-hosted Directus ?

**Comment by rijkvanzanten** [comment]
> Could that be the culprit ?

Maybe! I have no idea how you're running Directus on your server, or really anything about that environment, so it's very hard to tell.

> Is there any hardware requirements for a smooth self-hosted Directus ?

512MB of RAM with 0.25vCPU should be plenty for a single running instance, a load balanced setup of 2x 1 vCPU / 2GB is recommended. That being said, I think the problem you should resolve first is why it's spawning so many different instances, as that's definitely wasting resources

**Comment by AristideBH** [comment]
Thanks for taking time to answer me.
> why it's spawning so many different instance

Well, looking into it a bit more, seems it is only a display setting : 
"it's just that htop by default shows each thread as a separate process." 

Added `hide_userland_threads=1` to `~/.config/htop/htoprc` file to show only one line
![image](https://github.com/directus/directus/assets/11951633/57b1e74f-8219-40e5-96cb-ea589fed2897)

I'll try to install a lighter Debian 9 minimal distro to see if that affects the performance and bug.

**Comment by rijkvanzanten** [comment]
> and if not working, I'll maybe try switching to a better plan on my host.

I'd really recommend not dealing with VPSes yourself if you don't have to. There's tons of hosts nowadays that'll happily take a Docker image and handle all the server and keep-alive stuff on your behalf 🙂

**Comment by AristideBH** [comment]
Well, Debian 9 Minimal is not supported anymore by Docker, so I wasn't able to get it working there.
Testing on Centos 7 gave me the same result... I now higly suspect that this is a problem on my VPS side.

To further that thought,  could it be linked to the type of VPS ? 
I've tried running [Caprover](https://github.com/caprover) to deploy the dedicated app (Directus + MySQL + Redis). 
But I couldn't get it to [install](https://github.com/caprover/caprover/issues/1796). It seems that it need a [KVM VPS and not a LXD-based VP](https://github.com/caprover/caprover/issues/1759#issuecomment-1584388618)

Could that be a similar problem ?
Anyway, thanks a lot for your assistance, I'll update here if I find a solution !

**Comment by rijkvanzanten** [comment]
> To further that thought, could it be linked to the type of VPS ?
> I've tried running [Caprover](https://github.com/caprover) to deploy the dedicated app (Directus + MySQL + Redis).
> But I couldn't get it to https://github.com/caprover/caprover/issues/1796. It seems that it need a https://github.com/caprover/caprover/issues/1759#issuecomment-1584388618

This is what I meant by _not dealing with VPSes yourself if you don't have to_ 😅 Just use something like Directus Cloud, Railway or DigitalOcean App Platform so you don't have to deal with any of this!
