### ISSUE TITLE
Home and End keys do not work in some (dbSafe?) inputs

### ISSUE THREAD

**Issue by anantakrishna** [directus/directus#19097]
### Describe the Bug

Pressing “Home” or “End” keys in the some inputs such as a “field key” or “related collection” does not work. Cursor is not moving to the start or the end of the text.

### To Reproduce

- Press “Create Field” in a collection.
- Choose any type.
- In the “Key” field type something.
- Press “Home” key.
- Cursor does not move to the beginning of the text.
- Feel irritation.
- Move the cursor to the beginning of the text with the mouse of cursor keys.
- Press ”End” key.
- Cursor does not move to the end of the text.
- Feel irritation.

### Directus Version

v10.4.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by anantakrishna** [comment]
Perhaps, a continuation of #16646.

**Comment by shivm29** [comment]
HEY @rijkvanzanten ! I wanna help. Please assign me this.
