### ISSUE TITLE
Flow filter item.delete not passing keys

### ISSUE THREAD

**Issue by u12206050** [directus/directus#19106]
### Describe the Bug

On a flow that triggers before items are being deleted the keys to those items are null, and for some reason there are two null values even if just one item is being deleted.

This potentially means that no flows using filter item.delete are working!

![flow issue](https://github.com/directus/directus/assets/6641242/ed5d4a31-66c7-4966-976d-dffe9a6e1597)

### To Reproduce

Setup a flow that triggers before an item is deleted.

Delete the item and check the flow log. 

Expected: The `$trigger.keys` should have the ids of the items being deleted

### Directus Version

10.4.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
Can you share the schema / primary key type used in this delete? What database are you using? Do you have any other flows or extensions that might affect this?

I'm seeing the correct keys being passed to the payload on delete:

```json
{"payload":["d20c4409-8c39-44c1-a508-06a1ad4ba409"],"event":"block_hero.items.delete","collection":"block_hero"}
```

**Comment by u12206050** [comment]
Using MySQL
Primary key is `id`
Flow trigger options are:
```
{
  "type": "filter",
  "scope": [
    "items.update",
    "items.delete"
  ],
  "return": "{{$trigger.payload}}",
  "collections": [
    "registrations"
  ]
}
```

Not sure if the addition of `items.update` changes it?

**Comment by rijkvanzanten** [comment]
Not seeing the behavior on Postgres on UUID with items.update and items.delete. Trying on MySQL next..

**Comment by rijkvanzanten** [comment]
@u12206050 On a fresh installation against MySQL 8.0.33 with flow trigger

```json
{"type": "filter", "scope": ["items.update", "items.delete"], "collections": ["flow_test"]}
```

against a `flow_test` collection that's effectively empty:

<img width="961" alt="CleanShot 2023-07-10 at 10 36 41@2x" src="https://github.com/directus/directus/assets/9141017/d26a33d9-56bf-4878-ae4f-7dae49a79400">

it seems to behave as intended:

```json
{"payload":[2],"event":"flow_test.items.delete","collection":"flow_test"}
```

**Comment by u12206050** [comment]
I have checked a custom logging extension and noticed that the filter for `delete` did not return anything.
After updating it to return `keys` it does seem flows it working as intended again.
Question though: If these extensions are suppose to work as a middleware it makes sense, but not really in the context of delete though or?

Anyways thanks for the effort, and sorry I didn't notice it before was actually unsure at first if beforeDelete should return anything.

**Comment by rijkvanzanten** [comment]
> Question though: If these extensions are suppose to work as a middleware it makes sense, but not really in the context of delete though or?

Same middleware rules apply! You could prevent the deletion altogether, or delete less/more items as part of the middleware call depending on your data needs.
