### ISSUE TITLE
Better out-of-the-box filtering of tables (e.g. in "Related Collection")

### ISSUE THREAD

**Issue by rowild** [directus/directus#19101]
### Describe the Bug

When creating an e.g. m2m relation, a "Relational Collection" has to be defined. This list should only show tables that are actually "valid" tables. Meaning: Tables that Directus has not yet recognised should not be shown.

The attached screenshot shows an example where tables that phpmyadmin creates show up in the selection list.

![Screenshot 2023-07-09 at 14 41 15](https://github.com/directus/directus/assets/213803/043a3a36-2006-421d-b1db-f79dcd5b8afe)

NOTE:
This is probably less of a bug, but instead more of a feature request. Since I am unsure, I chose this form … I hope I have your blessing!

### To Reproduce

1. In a SQL tool (but NOT via Directus) add a new table, e.g. "Test" with a id, title and an info column
2. Back in Directus do NOT set that new table to "Make visible"
3. Create some relation of some sort
4. in the "Related Collection" you'll see that new table from step 1

### Directus Version

v10.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
> This is probably less of a bug, but instead more of a feature request. Since I am unsure, I chose this form … I hope I have your blessing!

Yeahhhhh this one is an edge case 😄 Seeing it's such a(n accepted) tiny tweak we'll triage it as a small improvement here 👍🏻

**Comment by khako** [comment]
Hey, I can work on this one if still needed :)

**Comment by paescuj** [comment]
Thank you @khako for taking this on!

However, after checking out the pull request (#20756) I've realized it might be sub-optimal to completely hide unconfigured collections. Relations actually seem to work with unconfigured collections, and out in the wild there might be such configurations. This would be a breaking change as such collections wouldn't be displayed and also couldn't be deselected (M2A) anymore.

For this reason, I think the appropriate solution would be to still list these collections, but like the system collections under a separate collapsible section:
<img width="166" src="https://github.com/directus/directus/assets/5363448/30784eb8-e9f7-421f-bebc-614805f1ab04">

**Comment by khako** [comment]
Maybe something like that ?

<img width="777" alt="image" src="https://github.com/directus/directus/assets/23417448/7451c2c1-cd2d-40f3-b167-0512728bb73f">

**Comment by rijkvanzanten** [comment]
@paescuj I think we should hide the non-directus managed collections from these dropdowns. We're hiding them on purpose elsewhere in the system, so it feels inconsistent to still be able to select them here

**Comment by paescuj** [comment]
> @paescuj I think we should hide the non-directus managed collections from these dropdowns. We're hiding them on purpose elsewhere in the system, so it feels inconsistent to still be able to select them here

Thanks for the feedback! Okay, let's go with that 👍 We could always circle back if necessary as it's only a visual change.

Thanks for 🐻-ing with me, @khako!
