### ISSUE TITLE
Empty filter not working

### ISSUE THREAD

**Issue by Alekshar** [directus/directus#1910]
## Version Info
  - Directus version and branch: current master branch 

## Actual Behavior
I tried to understand what was the difference between the 'null' filter and the 'empty' filter. 
I tried this key on  both text fields and numeric and got no results, neither null nor empty

Trying the filter over a 'multiple files' field, I got the following sql error and its content suprised me.

This query failed: SELECT `test`.`id` AS `id`, `test`.`status` AS `status`, `test`.`sort` AS `sort`, `test`.`title` AS `title`, `test`.`content` AS `content`, `test`.`count` AS `count` FROM `test` WHERE (`test`.`files` IS NULL AND `test`.`files` = '') AND `test`.`status` IN ('1') ORDER BY `test`.`sort` ASC LIMIT 200 OFFSET 0

notice this part :  WHERE (`test`.`files` IS NULL **AND** `test`.`files` = '')
Isn't this a mistake in the query to check the field is null AND empty ?

Other questions : 
Shouldn't the filter be able to tell when there is no file listed ? 

As texts and numerics cannot be empty (they are set to null when nothing is written in them) is the empty filter usefull for any find of field type ?

EDIT : here is the full stacktrace I received
`
{
    "success": false,
    "error": {
        "message": "This query failed: SELECT `test`.`id` AS `id`, `test`.`status` AS `status`, `test`.`sort` AS `sort`, `test`.`title` AS `title`, `test`.`content` AS `content`, `test`.`count` AS `count` FROM `test` WHERE (`test`.`files` IS NULL AND `test`.`files` = '') AND `test`.`status` IN ('1') ORDER BY `test`.`sort` ASC LIMIT 200 OFFSET 0"
    },
    "code": 0,
    "class": "RuntimeException",
    "file": "C:\\xampp\\htdocs\\directus\\api\\core\\Directus\\Database\\TableGateway\\BaseTableGateway.php",
    "line": 704
}
`

**Comment by WellingGuzman** [comment]
Hey @Alekshar thanks for the report, can you provide a schema that we can use to test this?

Null check for `null` values only but empty check for both `null` and empty string.

**Comment by Alekshar** [comment]
Here is the database I used for the test.
[directus.sql.txt](https://github.com/directus/directus/files/1393653/directus.sql.txt)

The request ouputing the error is : 
localhost/directus/api/1.1/tables/test/rows?access_token=pk8H56szTMLX3gxvteUTOrbUSgVvTg9X&filters[files][empty]

I correctly understood what 'empty' means but I do not understand how a field can be null and empty at the same time which is what the SQL request checks.

**Comment by WellingGuzman** [comment]
oh I see what you mean, it should've been `OR` not `AND`. Thanks for pointing it out.

**Comment by WellingGuzman** [comment]
@Alekshar we should fallback to a friendly error message OR a better yet, implement this as an alias to (NOT) `has` for X2M items, which needs to be implemented too.

Thanks, and sorry to my confusion on your concern at first.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/c624bb4be4e68dfedf2286b7ba595f408dbc0992

**Comment by Alekshar** [comment]
It works but more on the design topic, I do not see which field type can be empty, numbers and texts are automatically set to 'null' when they are empty.

That being said, thanks for your help :+1:

**Comment by WellingGuzman** [comment]
> numbers and texts are automatically set to 'null' when they are empty

What do you mean? from the Directus app when you empty the input, it will be saved as null? it should, if allow null.

You can always [join us on slack](https://slack.getdirectus.com), and we can talk about design topic.

**Comment by Alekshar** [comment]
In deed, it seems you cannot have an empty value in any field type, maybe I did not see how to set the default value to 'empty' or the config button to switch between 'null' and 'empty'.
Thus the empty check seems currently useless.

(As my company proxy disallows slack, I wanted to underline this point here)

**Comment by WellingGuzman** [comment]
On the Input if you remove all the information (say Text Input) it should save a empty value, by empty, I mean a empty string.

**Comment by Alekshar** [comment]
I tried on the develop branch with the Text Imput : 
1. created with some contents in the field in my browser
2. get table with the API : my value is here
3. removes the field's content using my browser
4. get table with the API : field is null again

It really seems empty content are replaced by a null value
