### ISSUE TITLE
Can't use arrays in flow trigger payload

### ISSUE THREAD

**Issue by u12206050** [directus/directus#19105]
### Describe the Bug

Trying to add `{{ $trigger.body.keys }}` to the payload of a **trigger flow** action just converts it to
```
{
  "data": "{{ $trigger.body.keys }}"
}
```

Which results in it not being executed as an array.

### To Reproduce

Add a manual trigger action flow and another flow that you can trigger.
Add the keys from the trigger to the payload eg. `{{ $trigger.body.keys }}`

Notice when you save and go back that it has been transformed to 
```
{
  "data": "{{ $trigger.body.keys }}"
}
```

Even if you do encapsulate it with `"` the array doesn't get parse correctly and ends up being a stringified array.

### Directus Version

10.4.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
I've setup two flows: one manual trigger, and the other the "triggered by other flow" (operation) trigger. In the operation trigger, I'm just logging what the trigger data is using the log operation. For the manual trigger, I'm calling the other flow with the configured payload:

```json
{
  "data": "{{ $trigger.body.keys }}"
}
```

When checking the server logs on triggering the manual flow, I'm (correctly) seeing 

```
[14:06:00.635] INFO: {"data":[1]}
```

<details><summary>Configured flows</summary>

```json
[
  {
    "id": "3df5ff38-73ad-4b63-8c43-bcca5055f3ad",
    "name": "Test",
    "trigger": "manual",
    "operations": [
      {
        "id": "7695f171-9ba3-49f1-bff9-b145610dfd9d",
        "name": "Trigger Flow",
        "options": {
          "payload": {
            "data": "{{ $trigger.body.keys }}"
          },
          "flow": "391f933c-bbe9-46dd-b6c7-12aa40b5ee13"
        }
      }
    ]
  },
  {
    "id": "391f933c-bbe9-46dd-b6c7-12aa40b5ee13",
    "name": "Triggered",
    "trigger": "operation",
    "operations": [
      {
        "id": "7e08b6c8-bbef-469b-b784-681817cbd2c4",
        "name": "Log to Console",
        "options": {
          "message": "{{$trigger}}"
        }
      }
    ]
  }
]
```

</details>

I haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available.
