### ISSUE TITLE
Directus Doesn't use BaseDN in LDAP Search Requests

### ISSUE THREAD

**Issue by Dan6erbond** [directus/directus#19102]
### Describe the Bug

I have Directus configured to use LDAP for authentication with Authentik, as I tried OIDC and had issues with that as well. Unfortunately, the search request Directus sends to the LDAP outpost doesn't include the BindDN, which is set in the environment variables, resulting in the request being rejected:

```json
{
  "baseDN": "cn=directus-ldap,ou=users,dc=directus,dc=myorg,dc=ch",
  "bindDN": "",
  "client": "10.244.0.156",
  "event": "Search request",
  "filter": "(objectclass=*)",
  "level": "info",
  "requestId": "82b682f9-9176-4d6e-998a-2828acd64219",
  "scope": "Base Object",
  "timestamp": "2023-07-09T13:40:39Z",
  "took-ms": 0
}
```

### To Reproduce

I guess setup your own instance of Authentik, and then set the environment variables according to something like this:

```tf
    AUTH_PROVIDERS                      = "authentik"
    AUTH_AUTHENTIK_DRIVER               = "ldap"
    AUTH_AUTHENTIK_CLIENT_URL           = "ldap://ak-outpost-ldap.auth"
    AUTH_AUTHENTIK_BIND_DN              = "string:cn=directus-ldap,ou=users,dc=directus,dc=myorg,dc=ch"
    AUTH_AUTHENTIK_BIND_PASSWORD        = var.authentik_ldap_password
    AUTH_AUTHENTIK_USER_DN              = "string:ou=users,dc=directus,dc=myorg,dc=ch"
    AUTH_AUTHENTIK_USER_ATTRIBUTE       = "cn"
    AUTH_AUTHENTIK_MAIL_ATTRIBUTE       = "mail"
    AUTH_AUTHENTIK_FIRST_NAME_ATTRIBUTE = "firstName"
    AUTH_AUTHENTIK_LAST_NAME_ATTRIBUTE  = "lastName"
    AUTH_AUTHENTIK_GROUP_DN             = "string:ou=groups,dc=directus,dc=myorg,dc=ch"
    AUTH_AUTHENTIK_GROUP_ATTRIBUTE      = "cn"
    AUTH_AUTHENTIK_DEFAULT_ROLE_ID      = var.ldap_default_role_id
```

### Directus Version

10.4.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
Directus currently passes the configured `BIND_DN` into the `base` parameter of the [`search` method of `ldapjs`](http://ldapjs.org/client.html#search), which I believe is reflected under the `baseDN` in the object you shared.

What's the error you're getting, and what's the object you expected to get from Directus?

**Comment by Dan6erbond** [comment]
@rijkvanzanten Authentik expects the bindDN to be used to authenticate to its LDAP endpoint, while baseDN should tell it where to search for the object class AFAIK.

**Comment by rijkvanzanten** [comment]
From what I can tell, the LDAP auth implementation tries to search first, but does rebind on search error: 

https://github.com/directus/directus/blame/4834dfcda5da3628a0fe529481ef3292c660566a/api/src/auth/drivers/ldap.ts#L95

When you said _resulting in the request being rejected_, did you mean you saw the failed request in the logs from Authentik, or did the request from Directus fail too?

**Comment by rijkvanzanten** [comment]
(@aidenfoxx any further insights we're missing here? 🙂 )

**Comment by aidenfoxx** [comment]
`BIND_DN` is used for authentication of the LDAP management user. As has been described, that user then fetches various information from the `USER_DN` and `GROUP_DN` (which are the `baseDn` of the search request).

The way the LDAP system in Directus works is, it tries to maintain an open session for the management user, and re-authenticates only when required. This is done with the `validateBindClient` function, which is always called at the top of the authentication or token refresh functions.

Are there any logs on your side? It's hard to know what the issue might be flying blind.

**Comment by aidenfoxx** [comment]
Also, just to clarify what you're seeing @rijkvanzanten, when we trigger a `validateBindClient` we do so by querying the `bindDn` to see if we get an error back. So in this instance, the `bindDn` is the `baseDn`. We do this because it's a known variable we should be able to query against to see if we're still authenticated.
