### ISSUE TITLE
Slug is not generated on item creation via api

### ISSUE THREAD

**Issue by BennerGe** [directus/directus#1911]
## Version Info
  - Directus version and branch: 6.4.3 – 9bdadd639322fbc61d0e0f56fcb61647ded75d5d

## Actual Behavior
When I create a new item via the api, the 'slug' isn't set. The slug is only generated when an item is added with the directus backend.  

## Expected Behavior
Generate slug for new items when created via backend as well as via api. 

## Steps to Reproduce
 1. Create table with column ' title' and 'slug'
 2. Create item via API
 3. Slug is not set

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/0ca88ba7ca527aed964dacf85db91b9a280cf39f
