### ISSUE TITLE
Impossible to create validation rules for a field based on other fields after creation.

### ISSUE THREAD

**Issue by hawaiiH** [directus/directus#19120]
### Describe the Bug

During the creation of a field, it is possible to add validation rules based on other fields present in the collection. However, after the field is saved, when attempting to edit it and add additional validation rules, only the current field is available as an option. The other fields disappear from the list of options.

### To Reproduce

1. Open Settings -> Data Model -> select collection -> press button 'Create Field' -> select Input interface (or any other) -> press 'Continue in Advanced Field Creation Mode'
2. In the **Validation** tab, click on the 'Add filter' button. You should be able to choose fields by which to validate.
3. Save the field.
4. Open the field for editing by clicking on the three dots and selecting 'Edit Field'.
5. Go to the **Validation** tab.
6. At this point, you can only add filters based on the current field, and there is no possibility to add a filter based on other fields in the collection.

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
> In the Validation tab, click on the 'Add filter' button. You should be able to choose fields by which to validate.

Funnily enough, I believe this is the bug. The validation rules on the Field should be for the field you're configuring, not any of the other fields (as their validation rules should be on those fields)

**Comment by hawaiiH** [comment]
> I believe this is the bug. 

@rijkvanzanten I found it quite useful for certain cases. For example, it can be used to make certain input fields mandatory when a specific dropdown option is selected. In my situation, I have a field called "slug" that must be filled if you wish to change the status to "publish." Otherwise, it will prevent you from publishing.
