### ISSUE TITLE
User field: Replace id by related data

### ISSUE THREAD

**Issue by BennerGe** [directus/directus#1912]
## Version Info
  - Directus version and branch: 6.4.3 – 9bdadd639322fbc61d0e0f56fcb61647ded75d5d

## Actual Behavior
An api request of a table with field 'user' responses only the user id for this field, regardless of the passed 'depth' parameter.

## Expected Behavior
I would expect, that the related data for this user is responded. 

## Steps to Reproduce
 1. Create table with field of type 'user'
 2. Call /directus/api/1.1/[table]/rows
 3. The user field contains only the user id, not the related data

**Comment by WellingGuzman** [comment]
This not an relational interface, because of this we have `single_user` interface planned. The `user` interface was initially created to hold an integer.

I will take this as a feature request. Let's see what other thinks ( @benhaynes @rijkvanzanten )

**Comment by WellingGuzman** [comment]
I'm closing this one, as it's a feature request.

Moved to [request#132](https://request.getdirectus.com/r/132)
