### ISSUE TITLE
"add to home screen" not white labeled

### ISSUE THREAD

**Issue by BlackDahlia313** [directus/directus#19132]
### Describe the Bug

When viewing the data studio on a mobile device (tested on ios). When adding the data studio to the home screen, it displays the Directus title automatically and generates it's own D icon from it. 

It should default to the logo icon we already have placed and the title of the backend we have set.

This is important for any clients that need to lock down the backend on mobile devices for public use/events etc. 

![InkedInked1](https://github.com/directus/directus/assets/44903742/9f17c913-234b-4e4e-adf7-56e83e9e04a1)
![Inked2](https://github.com/directus/directus/assets/44903742/0f961e74-4052-45f9-9796-66f8686810d1)
![Inked3](https://github.com/directus/directus/assets/44903742/a03ab6ba-17d2-447c-8de2-73dc81e70ce2)

### To Reproduce

Head to your backend on your mobile device. 

Add the backend to your "home screen"

See that it defaults to the Directus title

### Directus Version

10.4.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
> It should default to the logo icon we already have placed

This is tricky, as apple requires very specific sizes and formats of the logo that is likely to not match the logo that was uploaded 🤔 The title should indeed be the configured project name rather than the "Directus" default 👍🏻

**Comment by rijkvanzanten** [comment]
Hmm odd. The title is correctly set to the configured project name, but Apple's save to homescreen still pulls the name from elsewhere 🤔 

<img width="242" alt="CleanShot 2023-07-12 at 09 58 17@2x" src="https://github.com/directus/directus/assets/9141017/bca357d8-8703-432e-8080-3438db6c5703">

**Comment by rijkvanzanten** [comment]
Ah found the problem. There was an old outdated manifest file that was still shipped.. Removing that resolves this 🙂
