### ISSUE TITLE
Update/archive functionality is broken in test environment 

### ISSUE THREAD

**Issue by sagguptachegg** [directus/directus#19142]
### Describe the Bug

Update/archive functionality is broken in test environment. We are using 10.4.2 version in test environment. 

### To Reproduce

Update or archive command is not working. The same is getting reflecting in Directus UI but is not updating the Taxonomy DB.

### Directus Version

v10.4.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
There isn't enough reproduction information available for me to be able to reproduce and help fix the problem. What does your test environment look like? Do you use Redis or memory for caching? What environment variables do you have configured? What do you mean by "Update or archive command"?
