### ISSUE TITLE
Conditions for the field with relations - show the wrong message

### ISSUE THREAD

**Issue by koksikus** [directus/directus#19145]
### Describe the Bug

At least since version 9.26 there is a bug. In the case of a relational field (M2M; M2O etc) in the conditions tab, it is not possible to set a new view because an incorrect message appears. 
The field is properly configured and it is possible to display data, but not when you want to set it for a specific condition.
![conditions](https://github.com/directus/directus/assets/90528895/a5ac8e37-a5f0-4207-8f11-03b3fcc9cec0)

### To Reproduce

In an existing relational field, try to set a condition.

### Directus Version

v10.4.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
> At the moment it is not possible to open condition or create a new one. Clicking on this field causes the entire tab to freeze and nothing can be done. (10.5.0)

Tracked in https://github.com/directus/directus/issues/19259.
