### ISSUE TITLE
RangeError when exporting Datetime fields

### ISSUE THREAD

**Issue by Kazzim** [directus/directus#19152]
### Describe the Bug

When exporting tables using the "Download page as CSV" feature below the Export button and the table contains a Datetime field with the Display setting put to Long and error is thrown in the console and no export is performed.

By setting the format to Short this error is avoided.

` Uncaught (in promise) RangeError: Format string contains an unescaped latin alphabet character "n"
index.b83eab94.entry.js:47 `
![errorsetting](https://github.com/directus/directus/assets/9380978/d6492e7f-814f-44af-8682-f6af5a98ba7d)

### To Reproduce

To reproduce.
Create a table with a Datetime field.
Set the type to Date (have not tested other formats)
Set Display setting to Long format
Create a new value in the table.
Export using the "Download page as CSV" button.

![long](https://github.com/directus/directus/assets/9380978/dcb1739c-be5e-44f7-82c5-5d4b58f7f494)

### Directus Version

10.4.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
I was only able to reproduce this specifically on the Date type using the direct "Download as CSV" link (for some reason the export modal is not affected)

**Comment by rijkvanzanten** [comment]
> I was only able to reproduce this specifically on the Date type using the direct "Download as CSV" link (for some reason the export modal is not affected)

The _Download as CSV_ link saves currently visible page values using the Display's toString methods, whereas the export modal version uses the APIs raw output 🙂  Looks like the datetime display toString method is failing on the configured format

**Comment by rijkvanzanten** [comment]
``RangeError: Format string contains an unescaped latin alphabet character `n```

is because it's trying to use `undefined` as the string
