### ISSUE TITLE
Calendar performance

### ISSUE THREAD

**Issue by DMachad0** [directus/directus#19151]
### Describe the Bug

I have a bookmark for layout calendar option, and I have +/- 1300 records, on a week range I have like 50 records.
The calendar loading it's extremely slow.
I can use month, week or day the speed it's the same.

### To Reproduce

Have an collection with a large number of records and use calendar layout.

### Directus Version

v10.4.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
There isn't enough information available for me to be able to reproduce this issue.
