### ISSUE TITLE
Running locally docs are not accurate

### ISSUE THREAD

**Issue by KKKaisar** [directus/directus#19150]
### Page

https://docs.directus.io/contributing/running-locally.html

### Describe the Inaccuracy

node -v
v18.16.0
pnpm -v
8.6.7
pnpm build doesn't work, tried pnpm -r build and still doesn't work. Don't know what to do. Pls fix it
...│ ✓ 5652 modules transformed.
│ rendering chunks...
│ <--- Last few GCs --->
│ [11396:0000025496F74F90]    54155 ms: Scavenge 1999.5 (2076.9) -> 1998.7 (2084.9) MB, 5.5 / 0.0 ms  (average mu = 0.295, current mu = 0…  
│ [11396:0000025496F74F90]    54175 ms: Scavenge 2007.3 (2085.5) -> 2005.9 (2085.3) MB, 8.0 / 0.0 ms  (average mu = 0.295, current mu = 0…  
│ [11396:0000025496F74F90]    54249 ms: Scavenge 2013.7 (2086.2) -> 2012.3 (2101.7) MB, 69.4 / 0.0 ms  (average mu = 0.295, current mu = …  
│ <--- JS stacktrace --->
│ FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
│  1: 00007FF79844D51F node_api_throw_syntax_error+175743
│  2: 00007FF7983D2E66 v8::internal::wasm::WasmCode::safepoint_table_offset+59654
│  3: 00007FF7983D4B72 v8::internal::wasm::WasmCode::safepoint_table_offset+67090
│  4: 00007FF798E7AAB4 v8::Isolate::ReportExternalAllocationLimitReached+116
│  5: 00007FF798E65E12 v8::Isolate::Exit+674
│  6: 00007FF798CE7C6C v8::internal::EmbedderStackStateScope::ExplicitScopeForTesting+124
│  7: 00007FF798CE4E8B v8::internal::Heap::CollectGarbage+3963
│  8: 00007FF798CFB0C3 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath+2099
│  9: 00007FF798CFB96D v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath+93
│ 10: 00007FF798D0B1A3 v8::internal::Factory::NewFillerObject+851
│ 11: 00007FF7989FC285 v8::internal::DateCache::Weekday+1349
│ 12: 00007FF798F18051 v8::internal::SetupIsolateDelegate::SetupHeap+558193
│ 13: 00007FF798E9DB62 v8::internal::SetupIsolateDelegate::SetupHeap+57218
│ 14: 00007FF7199A3ABF 
└─ Failed in 55s at C:\Users\Данияр\Desktop\directus\app
C:\Users\Данияр\Desktop\directus\app:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @directus/app@10.5.0 build: `vite build`
Exit status 134

**Comment by br41nslug** [comment]
As the error says your node process ran out of memory. The instructions are still correct and working. Google is your friend in regards to allowing nodejs more memory.
