### ISSUE TITLE
Conditionals doesn't work as expected.

### ISSUE THREAD

**Issue by zozito** [directus/directus#19153]
### Describe the Bug

I have a field with a conditional raw value.

```json
{
	"_and": [
		{
			"equipamento": {
				"fabricante": {
					"nome": {
						"_eq": "DELL"
					}
				}
			}
		}
	]
}
```

This will show one hide field when it is true
![image](https://github.com/directus/directus/assets/4005288/36c40d67-4b80-41f2-a5d9-1406e3cdb366)

But, when I select the "fabricante" with the name "DELL" the hidden field doesn't appear as expected.

This only work if I create raw value with the "equipamento" ID, but that is not the conditional I want.

### To Reproduce

Use conditional with one2many field to show/hide other fields

![image](https://github.com/directus/directus/assets/4005288/dd0b18a1-0e25-465f-a04f-570b8c25c44f)

![image](https://github.com/directus/directus/assets/4005288/ce4918cd-a766-4b39-a43a-dc5b9e129cc3)

![image](https://github.com/directus/directus/assets/4005288/1c44eda1-53b0-43b8-9ab1-d1c9b0284f0a)

Let me know if you need something else.

Thank you

### Directus Version

v10.4.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
Could you share a database dump with a minimal reproduction of this issue?

**Comment by zozito** [comment]
Will try to explain the best I can.

Create 3 tables, one called "Equipment" with the fields, ID, name, family (related One2Many with family), incidents (related One2Many with incidents), and description.

Another table with the name "Family" with the fields, ID, name, equipment (Many2One), and description.

Create the last table "Incidents" ID, Name, Equipment (Many2One), workorder, and description.

The condition is created in the "incidents" table in the "workorder" field as follows:

If equipment.family.name = DELL, the "workorder" field appears to be filled in. If it is not valid, it remains hidden by default.

[directus_dump.zip](https://github.com/directus/directus/files/12073803/directus_dump.zip)

**Comment by zozito** [comment]
Hello,

Do you have any updates on this?

I don't know if it's I'm doing something wrong or if is a Directus bug.

Thank you

**Comment by rijkvanzanten** [comment]
Thanks for the dump! That really helped understanding what you were talking about.

Conditional fields don't currently support nested relational fields. There's an open issue here tracking that feature: https://github.com/directus/directus/issues/8228
