### ISSUE TITLE
Flows: Update operation is ignoring "IDs"

### ISSUE THREAD

**Issue by nicolaracco** [directus/directus#19154]
### Describe the Bug

I've created a Manual Flow, with an Update Data operation
![image](https://github.com/directus/directus/assets/203857/c4b0cbf2-99c6-4685-8af0-83b9ccc297ae)

On submit, the IDs field is left blank both in the diagram and in the detail
![image](https://github.com/directus/directus/assets/203857/10fb9f05-1512-408a-84ae-f9776eb61d17)
![image](https://github.com/directus/directus/assets/203857/638234c9-77ac-4d24-8a0d-b0ae2c366209)

Looking at the network, this is the creation payload sent to directus
```
{
  "operation": {
    "flow": "0f74d286-4bc8-4434-8978-fc52ac2df168",
    "position_x": 19,
    "position_y": 1,
    "name": "Update Data",
    "key": "item_update_v356q",
    "type": "item-update",
    "options": {
      "collection": "{{$trigger.body.collection}}",
      "payload": {
        "status": "accepted"
      },
      "emitEvents": true
    }
  },
  "operations": {
    "create": [],
    "update": [],
    "delete": []
  }
}
```

Looking at the source code, I assume the property should be named "key", so I tried updating the operation by calling PATCH /operations/:id and sending
```
{
	"options": {
				"collection": "{{trigger.body.collection}}",
				"key": "{{trigger.body.keys}}",
				"emitEvents": true,
				"payload": {
					"status": "accepted"
				},
				"query": {
					"filter": {
						"status": {
							"_neq": "accepted"
						}
					}
				}
			}
}
```

The payload has been updated, but the frontend doesn't show the value.

### To Reproduce

- Create a collection
- Create a Manual Flow for that collection
- Add a "Update Data" step
- Set IDs to the raw value {{$trigger.body.keys}}
- Submit the operation and save the flow

### Directus Version

v10.4.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Looks like you forgot to press enter in the `IDs` field 😬 
![image](https://github.com/directus/directus/assets/9389634/f1756fd8-1c77-4f07-bf28-9821399c5cd7)

**Comment by br41nslug** [comment]
When directly adding values using the Raw Mode you'll have to make sure it is in the correct/expected format. In this case as a JSON array: 
![image](https://github.com/directus/directus/assets/9389634/36757474-adb9-4a4b-87c8-e80604128f90)

**Comment by nicolaracco** [comment]
Sorry but I'm not getting how it should work. In a manual trigger `$trigger.body.keys` is the Array of IDs the user selected. But I can't set it in the keys because it's requiring me to set `["{{$trigger.body.keys}}"]` which will result in an array of array.

How can I do a Manual trigger which makes an update over all the selected items then?
