### ISSUE TITLE
The validation rules "bug" is still present.

### ISSUE THREAD

**Issue by hawaiiH** [directus/directus#19165]
### Describe the Bug

Previously, created bug report [#19120](https://github.com/directus/directus/issues/19120). However, it is still can be recreated.

Also, I have probably found some misunderstanding with @rijkvanzanten . I believe that validation by other fields is a really useful feature, as it provides an opportunity to create custom rules for different states of an item in a collection based on its data.

### To Reproduce

1. Open Settings -> Data Model -> select collection -> press button 'Create Field' -> select Input interface (or any other) -> press 'Continue in Advanced Field Creation Mode'
2. Don't input any Key for the Field
3. In the Validation tab, options to validate by other fields are available.

If you add Key, the options disappear.

### Directus Version

v10.4.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
> However, it is still can be recreated.

Same bug, different steps to reproduce tho! 😄 

> Also, I have probably found some misunderstanding with @rijkvanzanten . I believe that validation by other fields is a really useful feature, as it provides an opportunity to create custom rules for different states of an item in a collection based on its data.

It won't provide the opportunity to create custom rules _for different states_ though, it would just merge all those rules into single validation step. What you're thinking about is conditional validation, which is more like "If current value for field `x` is `1`, validate against the following rules: abc". Small yet crucial difference! 🙂
