### ISSUE TITLE
Any action on `directus_presets` does not reflect immediately when cache is active

### ISSUE THREAD

**Issue by joselcvarela** [directus/directus#19166]
### Describe the Bug

When doing any action on `directus_presets`, the change takes some time until it is retrieved, despite the`CACHE_AUTO_PURGE` being enabled.

After some investigation I found this is happening because `directus_presets` is on `CACHE_AUTO_PURGE_IGNORE_LIST` by default.
Then the condition to check if the cache should be purged fails, because `directus_presets` collection is being ignored:
https://github.com/directus/directus/blob/d4e8286ebca95e884e25f52b7b4f8c094b70adc1/api/src/utils/should-clear-cache.ts#L20-L22

I think the solutions are:
- The most obvious one is just to remove `directus_presets` from `CACHE_AUTO_PURGE_IGNORE_LIST` but this will wipe cache very frequently. 
~~- App-wise, is to use cache busting. For example, add `?timestamp=${Date.now()}`, but this will always request fresh data and would only work on App, not via API.~~
~~- Also App-wise is to call clear cache endpoint within Presets view, but same issue regarding API as previous one~~
___
###  ℹ️ This actually seems to be working on App for some platforms but not in others. This is because cache is skipped should be skipped if the request comes from App but is relying on "Referer" header which seems to be removed by some middleware services not reaching Directus projects.
https://github.com/directus/directus/blob/91c4863f22c8236abba69cf1a00248d6272aa990/api/src/utils/should-skip-cache.ts#L17
___

For reference, this was inserted on https://github.com/directus/directus/pull/18484

### To Reproduce

- Setup Directus to run with Redis Cache and set `CACHE_TTL` to '30m'.
- Open App and go to Presets. No other requests should be made to API, otherwise any other request could trigger cache clear
- Create/Edit/Delete any item and refresh page. Data is not updated

### Directus Version

v10.4.3(main)

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
Ohh this is a tricky one.. We don't want to purge the cache every time somebody changes like the width of a tabular column, but we _do_ want to purge the cache when you "explicitly" change presets through settings 🤔 

Any thoughts on how to make this happen @joselcvarela / @licitdev / @paescuj?

**Comment by joselcvarela** [comment]
Maybe we can add a query or a specific request header that controls if the current request clears the cache or not, despite other configurations.
If that parameter was set to `true`, then cache is cleared no matter what just before the response is sent.
If that parameter was set to `false`, then cache is **not** cleared no matter what.

**Comment by licitdev** [comment]
> Maybe we can add a query or a specific request header that controls if the current request clears the cache or not, despite other configurations. If that parameter was set to `true`, then cache is cleared no matter what just before the response is sent. If that parameter was set to `false`, then cache is **not** cleared no matter what.

Good idea, this is a possible solution. 👍 

End users could "bypass" the cache clearing by tampering the header / query param, resulting in data inconsistencies where admins might not be expecting or unaware of. 🤔 

How about if this cache clearing control functionality is limited to the forcing of cache clearing only for collections in the `CACHE_AUTO_PURGE_IGNORE_LIST`?

**Comment by paescuj** [comment]
Yeah, something like this crossed my mind too 👍 

> How about if this cache clearing control functionality is limited to the forcing of cache clearing only for collections in the CACHE_AUTO_PURGE_IGNORE_LIST?

Or exposing this param for the `presets` endpoint only? 🤔

Note: In the future, after having completed the new data abstraction layer we should be able to overcome such issues by implementing a more granular cache service 😃

**Comment by rijkvanzanten** [comment]
An alternative solution is to have a dedicated endpoint to set user changes to presets, kinda like how we have that `/me/track/page` endpoint on `/users` 🤔 That way we can ignore the cache clear for just that endpoint, but leave it on for regular `/presets` operations

**Comment by paescuj** [comment]
> An alternative solution is to have a dedicated endpoint to set user changes to presets, kinda like how we have that `/me/track/page` endpoint on `/users` 🤔 That way we can ignore the cache clear for just that endpoint, but leave it on for regular `/presets` operations

I like this 😃👍

**Comment by joselcvarela** [comment]
@licitdev found that App should always ask fresh content but it's relying on `Referer` header:
https://github.com/directus/directus/blob/91c4863f22c8236abba69cf1a00248d6272aa990/api/src/utils/should-skip-cache.ts#L17

I've just included this information to original post:
> ###  ℹ️ This actually seems to be working on App for some platforms but not in others. This is because cache is skipped should be skipped if the request comes from App but is relying on "Referer" header which seems to be removed by some middleware services not reaching Directus projects.
https://github.com/directus/directus/blob/91c4863f22c8236abba69cf1a00248d6272aa990/api/src/utils/should-skip-cache.ts#L17

**Comment by joselcvarela** [comment]
This is not an issue anymore for my use case.
The issue was with the provider I was using, but I was able to pass the `Referer` header now.
