### ISSUE TITLE
Read Data operation in Flows in unable to save the ID information

### ISSUE THREAD

**Issue by ravi-2912** [directus/directus#19175]
### Describe the Bug

The read data operation in Flow do not save the ID provided.

![ReadDataOpsIDBlankIssue](https://github.com/directus/directus/assets/25941167/9e31345a-18c7-4db3-a096-c69c54abbb69)

### To Reproduce

Create a flow
Create a read operation on trigger like `item.update`
Create a read data operation and provide ID as {{$trigger.keys[0]}}
Save it completely.
Start editing this flow again.
ID is vanished and not seem.

### Directus Version

v10.4.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by SeanDylanGoff** [comment]
I also fell for that. You have to press enter in the ID input (it's a "tags" input)

**Comment by br41nslug** [comment]
SeanDylanGoff is right 😄 and i think we've all fallen for that at some point 😅 This is a "tags" interface which handles a list of items an requires you to press enter to "add the item".

**Comment by ravi-2912** [comment]
Thanks 😆

**Comment by rijkvanzanten** [comment]
> SeanDylanGoff is right 😄 and i think we've all fallen for that at some point 😅 This is a "tags" interface which handles a list of items an requires you to press enter to "add the item".

We should add a blur handler to stage the value as well to prevent this confusion in the future

**Comment by BlackDahlia313** [comment]
> > SeanDylanGoff is right 😄 and i think we've all fallen for that at some point 😅 This is a "tags" interface which handles a list of items an requires you to press enter to "add the item".
> 
> We should add a blur handler to stage the value as well to prevent this confusion in the future

it got me today. I agree haha
