### ISSUE TITLE
File Upload ignores File Object parts

### ISSUE THREAD

**Issue by adamkhan** [directus/directus#19174]
### Describe the Bug

When uploading a file following the method described in the docs at https://docs.directus.io/reference/files.html#upload-a-file, I want to include `folder` and `uploaded_by`. The docs say:

> The file contents has to be provided in a part called file. All other properties of [the file object](https://docs.directus.io/reference/files.html#the-file-object) can be provided as parts as well, except filename_disk and filename_download.

When I add them though they are ignored.

I'm using Nuxt 3's $fetch rather than $axios.

### To Reproduce

Upload a file following the docs and set up formData, eg:

```
let formData = new FormData();
formData.append('name', uploadName);
formData.append('file', fileDetails);
formData.append('folder', folderID);
formData.append('uploaded_by', userID);
```

And submit it following the method in the docs.

### Directus Version

10.4.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
The order of the properties matters, add your non-file properties before adding the file 😄 
![image](https://github.com/directus/directus/assets/9389634/cab357b2-0cbf-4095-bd75-94d7d52a71c3)
https://docs.directus.io/reference/files.html#upload-a-file

**Comment by adamkhan** [comment]
Oops, thank you [br41nslug](https://github.com/br41nslug) for taking the time to help me RTFM!
