### ISSUE TITLE
Password reset request

### ISSUE THREAD

**Issue by idmansourali** [directus/directus#19182]
### Describe the Bug

We have an issue with the password reset feature, frontend users receive the email but they can no longer reset their password.
The environment variable " PASSWORD_RESET_URL_ALLOW_LIST" is well configured.
Our users are getting the forbidden error message when they send the reset request with a new password:

`
payload: { password: "1234567", token: "eyJhbGc......" }
`

`
{
    "errors": [
        {
            "message": "You don't have permission to access this.",
            "extensions": {
                "code": "FORBIDDEN"
            }
        }
    ]
}`

Any help's appreciated, thanks in advance.

### To Reproduce

Use the password request api

### Directus Version

v10.0.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
I am unable to reproduce this by using the password request and reset endpoints with Postman.

Presuming this is correct:
> The environment variable " PASSWORD_RESET_URL_ALLOW_LIST" is well configured.

Then the reset token is probably expired.

**Comment by idmansourali** [comment]
What's strange to me is that the process was working before, could this issue be caused by a firewall we put in place recently?

> Then the reset token is probably expired.

The reset link is used right after receiving the email!

**Comment by idmansourali** [comment]
Is this value correct for the PASSWORD_RESET_URL_ALLOW_LIST variable ?:

`PASSWORD_RESET_URL_ALLOW_LIST=http://localhost:3000/password/reset, http://localhost:3002/password/reset
`

Double quotes are required?

**Comment by rijkvanzanten** [comment]
> What's strange to me is that the process was working before, could this issue be caused by a firewall we put in place recently?

If nothing else changed in the meantime, it very well could!

> Double quotes are required?

It depends on the environment, but it doesn't hurt to try! Try setting it to 

`PASSWORD_RESET_URL_ALLOW_LIST="http://localhost:3000/password/reset,http://localhost:3002/password/reset"`

**Comment by idmansourali** [comment]
It also doesn't work with double quotes :(

**Comment by idmansourali** [comment]
I managed to identify the problem, it works in the local machine but not from outside the local network
I think this is related to the recent change in windows hosts and firewall configuration.

Thanks for your help
