### ISSUE TITLE
Google Cloud SQL connection described with DSN

### ISSUE THREAD

**Issue by zbrox** [directus/directus#1918]
I'm trying to run the latest stable release of Directus on GAE. In order to connect to the Google Cloud SQL instance I need to use a DSN to describe the connection. The documentation gives an example (https://cloud.google.com/appengine/docs/standard/php/cloud-sql/#setting-up) like `mysql:unix_socket=/cloudsql/INSTANCE_CONNECTION_NAME;dbname=DATABASE`

The documentation was pretty brief on configuring the DB connection and I only saw a host/db/user/pass described and no possibility to just directly pass the DSN. Is this possible or planned for the future?

**Comment by WellingGuzman** [comment]
Hey @zbrox, I've no experiencing working on Google Cloud SQL, but is this a MySQL or similar server? Also don't they provide directly information such as the server host? Finally can you just try using `localhost` or `127.0.0.1` as the database host?

We do not support socket connection but rather tcp connection, give it a shot and let me know.


I'm going to close this as this is not directly a Directus issue, even if you want to support sockets connection you must create a new feature request here: https://request.getdirectus.com

We can continue the conversation on how to set this up with Google Cloud SQL
