### ISSUE TITLE
typo in permission object attributes

### ISSUE THREAD

**Issue by juliuste** [directus/directus#19196]
### Page

https://docs.directus.io/reference/system/permissions.html

### Describe the Inaccuracy

Hey everyone! While reading your docs on `permissions`, I noticed that the object [attribute list at the top of the page](https://docs.directus.io/reference/system/permissions.html#the-permission-object) lists an attribute **`preset`**, while the examples below contain the term **`presets`**. I assume one of these is wrong? If you'd let me know which one, I'd open a PR 🙂

Besides all that, thank you very much for your great work, it is deeply appreciated! ❤️

**Comment by rijkvanzanten** [comment]
Heya! Great catch! `presets` is the correct one 👍🏻
