### ISSUE TITLE
SQL error due to non-existing database entry

### ISSUE THREAD

**Issue by studiovlijmscherp** [directus/directus#1919]
**Version info**
Directus version 6.4.3
PHP 7.1.0
MySQL 5.6.35
OS: MAcOS High Sierra

I have three **empty** database tables:
- place_attributes
- place_attribute_groups
- place_attribute_groups_attributes (junction)

I have setup an M2M relation in Directus. Many place_attributes belong to many place_attribute_groups.

When I browse to the 'place_attributes'  in the directus backend I receive the following error:

Server Error
`
This query failed: SELECT `place_attributes`.`id` AS `id`, `place_attributes`.`label` AS `label` FROM `place_attributes` WHERE `place_attributes`.`attribute_group` = '5' ORDER BY `place_attributes`.`id` ASC LIMIT 200 OFFSET 0`

All three tables are empty... so why is the query looking for  `place_attributes`.`attribute_group` = '5'?

![schermafbeelding-2017-10-20-om-11 45 02](https://user-images.githubusercontent.com/3353713/31815521-38404c8c-b58d-11e7-9286-61ea5d654ddf.jpg)

**Comment by WellingGuzman** [comment]
Hey @studiovlijmscherp, I'm not able to reproduce this, can you share a schema that we can use to reproduce this?

**Comment by rijkvanzanten** [comment]
It has almost been three weeks since this was reported and we've not been able to reproduce it so far.. We'll re-open this and continue investigating once there is more information available
