### ISSUE TITLE
Bug in `utils/url.js` removing trailing slashes

### ISSUE THREAD

**Issue by amerkay** [directus/directus#19207]
### Describe the Bug

The [utility `/api/src/utils/url.ts`](https://github.com/directus/directus/blob/c2c04734f0c5e1fa72090c5ca624fcb32d4cf3c9/api/src/utils/url.ts#L3) removes trailing slashes.

### Why is it a problem?

Because static deployments on S3 redirect folders and forces a trailing slash. But when it does so, it removes the query line. Dumb, I know! This issue is well documented, see [here](https://github.com/gatsby-uc/gatsby-plugin-s3/issues/51), [here](https://repost.aws/knowledge-center/s3-static-website-url-trailing-slash) and [here](https://stackoverflow.com/questions/30090254/aws-s3-forces-302-redirects-when-url-has-no-trailing-slash-need-301s).

From [S3 docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/IndexDocumentSupport.html#IndexDocumentsandFolders):
> However, if you exclude the trailing slash from the preceding URL, Amazon S3 first looks for an object `photos` in the bucket. If the `photos` object is not found, it searches for an index document, `photos/index.html`. If that document is found, Amazon S3 returns a `302 Found` message and points to the `photos/` key. For subsequent requests to `photos/`, Amazon S3 returns `photos/index.html`. If the index document is not found, Amazon S3 returns an error.

For more context, I use Nuxt 3 in my project, and it creates paths like `dist/verify/index.html` when using static site generation mode.

### To Reproduce

I give it the URL `https://example.com/verify/` and it returns `https://example.com/verify?token=...`.  
**Notice that the utility removes the trailing slash.**

You can test using this snippet:
```js
import { Url } from "@directus/api/utils/url";

const inviteURL = new Url("http://localhost/auth/verify/");
inviteURL.setQuery("token", "123123");
console.log("inviteURL", inviteURL.toString()); 
```

This will return `http://localhost/auth/verify?token=123123` instead of `http://localhost/auth/verify/?token=123123`, which is missing the trailing slash `/`.

### Directus Version

v10.4.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by amerkay** [comment]
I fixed the issue in a fork, and added tests. 

Problem: I noticed that an existing test fails: https://github.com/directus/directus/blob/c2c04734f0c5e1fa72090c5ca624fcb32d4cf3c9/api/src/utils/url.test.ts#L17

I'll wait for feedback before submitting a Pull Request.

Love Directus! Thanks for all your hard work. Cheers :)

**Comment by rijkvanzanten** [comment]
Good find! https://github.com/directus/directus/pull/17120 added in that additional test, but I think it's in error. If you pass a trailing slash, it should be returned with a trailing slash 🙂 Wanna open a PR??
