### ISSUE TITLE
Hidden confirmation window in certain situation

### ISSUE THREAD

**Issue by koksikus** [directus/directus#19206]
### Describe the Bug

Perhaps it will never occur to the user, it will not perform such an operation. but with my set of data for testing, I am able to trigger a situation where the confirmation window is hidden. The data and arrangement do not represent anything, this is just a test version.

### To Reproduce

Visible in the video. The situation is that by opening the side panel and changing the data, and then opening the next field without saving, the field confirming the previous change is hidden.

https://github.com/directus/directus/assets/90528895/0e9dd999-38d6-41a9-86d4-d6c858fd13a5

### Directus Version

v10.4.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
Woa good find! Tricky to reproduce indeed. Would you be able to share a database dump of this setup so it's easier for others to reproduce? 🙂

**Comment by koksikus** [comment]
I hope I did it right:
[directus.zip](https://github.com/directus/directus/files/12164713/directus.zip)

**Comment by rijkvanzanten** [comment]
That looks perfect, thanks! (For those reading along; it's from MariaDB 10.4.27)
