### ISSUE TITLE
Create user with custom ID woes

### ISSUE THREAD

**Issue by mrbarletta** [directus/directus#19213]
### Describe the Bug

When creating a user with REST having a custom ID it works

```json
{
	"email": "another@example.com",
	"password": "d1r3ctu5",
	"id": "22"
}
```

But when browsing the USER through the interface, an errror shows up :

`[FORBIDDEN] You don't have permission to access this.`

Furthermore, creating a user with the GraphQL api works, but fails to return back the data

```json
{
	"data": {
		"create_users_item": null
	},
	"errors": [
		{
			"message": "You don't have permission to access this.",
			"extensions": {
				"code": "INTERNAL_SERVER_ERROR"
			},
			"locations": [
				{
					"line": 2,
					"column": 2
				}
			],
			"path": [
				"create_users_item"
			]
		}
	]
}
```

### To Reproduce

Use the API to create a user adding the ID field
```json
{
	"email": "another@example.com",
	"password": "d1r3ctu5",
	"id": "22"
}
```

Access the interface `/admin/users/22` and check the interface

### Directus Version

v10.4.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
Users rely on UUIDs instead of integers, so make sure to pass a valid UUID as the primary key 👍🏻
