### ISSUE TITLE
401 Unauthorized Creating Report (/admin/insights)

### ISSUE THREAD

**Issue by Apkahym** [directus/directus#19218]
### Describe the Bug

When i can try to create a report from view in /admin/insights, after complete de modal form and click on save, appear this error and the panel is not created "401 Unauthorized"

### To Reproduce

- Login
- Go to */admin/insights*
- Try to create the panel
- Complete the form
- Save it

See error

### Directus Version

v10.2.1/v10.4.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
There isn't enough information available here for me to be able to reproduce the issue. Making new dashboards and panels seems to work on my end.
