### ISSUE TITLE
File disappear

### ISSUE THREAD

**Issue by tjsheppard** [directus/directus#19211]
### Describe the Bug

Strange behaviour with a docx file; when I add it to a file record and save, when I refresh or navigate back to it, it has disappeared!

### To Reproduce

- I add a file field to a table
- Upload a docx file to a record and save
- Go back to that record and the file field will be empty - no docx

### Directus Version

v10.4.3

### Hosting Strategy

Directus Cloud

**Comment by rijkvanzanten** [comment]
I haven't been able to reproduce this on my local machine nor on my cloud environment using the following dummy docx file:

[file-sample_100kB.docx](https://github.com/directus/directus/files/12148176/file-sample_100kB.docx)

Mind reaching out to support@directus.io to have the right folk take a look at your actual instance? I can't rule out something funky happening there, but based on the reproduction steps and testing on my end, I'll have to close this for now as not-reproducible 👍🏻
