### ISSUE TITLE
Permission denied for valid user

### ISSUE THREAD

**Issue by Alekshar** [directus/directus#1921]
## Version Info
  - Directus version and branch: master branch (october 9th version)
  - PHP version: 7.1.9
  - MySQL version: 10.1.26-MariaDB
  - Web server: Apache 2.4.27
  - OS name and version: Windows 7

## Expected Behavior
I try to login into the directus interface with a non-admin user.
However, I am able to get the authentication token in the API for this user. 

## Actual Behavior
Receive following exception in the browser (current chrome)
```json
{
  "success":false,
  "error":{
    "message":"Permission denied"
  },
  "code":0,
  "class":"Directus\\Exception\\Http\\ForbiddenException",
  "file":"C:\\xampp\\htdocs\\directus\\api\\core\\Directus\\Database\\TableSchema.php",
  "line":182
}
```

After that I cannot even access the login page without cleaning my browser's cookies first

## Steps to Reproduce
 1. Create at least two tables
 2. Create a new group for editors having all rights on only 1 table
 3. Create a user in this group
 4. Try to log in with this user

**Comment by Alekshar** [comment]
I got the same result with the latest build : 6.4.3

**Comment by WellingGuzman** [comment]
This issue has been solved in `develop` branch (https://github.com/directus/directus/commit/dfc5346b6fcd45d59fa03b6623a27d8a68774c53), reported in https://github.com/directus/directus/issues/1863

Please try using that branch or cherry pick the change (if possible), Otherwise I will reopen and ind what the problem is in your case then.

**Comment by Alekshar** [comment]
@WellingGuzman I got the same error on the current dev branch and to be honest I do not see any relation between this issue and the one you referenced.

1. I created a user group only allowed to edit some tables
![editors](https://user-images.githubusercontent.com/6387602/31929267-a83aec02-b89b-11e7-9366-5cde9ccc1bfb.PNG)

2. I try to log in with the user
![editor login](https://user-images.githubusercontent.com/6387602/31929290-c2172dfc-b89b-11e7-9eba-a1eaf6ea9192.PNG)

3. I only get the following error on every page afterwards (until I manually remove the cookies)
![editors denied](https://user-images.githubusercontent.com/6387602/31929331-eba74012-b89b-11e7-8191-d8f1f9471223.PNG)

I would say the user successfully logged in but is denied the web application as, when the credentials are incorrect, we have a message on the login page

**Comment by WellingGuzman** [comment]
Hey @Alekshar, can you share a simple schema that we can use to reproduce this one?
I will be trying to reproduce this one.

**Comment by Alekshar** [comment]
Sure, here it is : [directus-dev.sql.txt](https://github.com/directus/directus/files/1413602/directus-dev.sql.txt)

**Comment by WellingGuzman** [comment]
Hey @Alekshar, I've fixed the problem you were facing here https://github.com/directus/directus/commit/8075e93b769e0d556c306982dc28f67e20bce435

Let me know if that also works for you.

**Comment by Alekshar** [comment]
It works
Thanks for the quick fix :+1:
