### ISSUE TITLE
Cloudinary storage driver failing to write on delete operation

### ISSUE THREAD

**Issue by sethkaufee** [directus/directus#19219]
### Describe the Bug

With the Cloudinary storage driver configured, the API successfully uploads and writes files to Cloudinary, but a subsequent delete operation fails to remove the asset downstream. The DB record of the file is removed without an error or log.

### To Reproduce

1. Configure the environment

```env
STORAGE_LOCATIONS=cloudinary
STORAGE_CLOUDINARY_DRIVER=cloudinary
STORAGE_CLOUDINARY_CLOUD_NAME=*
STORAGE_CLOUDINARY_API_KEY=<SOME-KEY>
STORAGE_CLOUDINARY_API_SECRET=<SOME-SECRET>
STORAGE_CLOUDINARY_ACCESS_MODE=public
```
2. Successfully upload a file on the Directus instance (take note of the ID).
3. Delete the file
4. See the associated file and its generated assets still exist on Cloudinary. 

### Directus Version

v10.4.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by sethkaufee** [comment]
Also, there seems to be multiple open issues for this backend, including https://github.com/directus/directus/issues/18146.

I currently have a temporary fix addressing both of these issues for our use case, but happy to open a PR to move this forward!

**Comment by BlackDahlia313** [comment]
Looks like this getting fixed in the next release cycle.

It is currently assigned as well. If you want to open a PR, it could help rijkvanzanten expedite the fix. :)

**Comment by rijkvanzanten** [comment]
Yes I have a fix in the works for #18146! I believe it might also fix this issue actually, but I'll have to do some more testing.

This is my in-works attempt: https://github.com/directus/directus/compare/main...issue/18146

**Comment by sethkaufee** [comment]
Awesome, I didn't see that branch! This is my first project using Cloudinary, and I quickly came to the same conclusion about their API being inconsistent, which doesn't help my existing anxiety 🤣.

I made similar changes and seems to be working for us, where I am overriding the `storage-driver-cloudinary` package with my patched package in our docker build. I found their V2 API accepts the `asset_folder` and `use_asset_folder_as_public_id_prefix` parameters, replacing the previous `folder` parameter in uploads. However, it's also not available in all methods/api calls (like "resource" and "explicit").

Have you looked at leveraging their Node SDK? It doesn't seem to be more than another auto-generated SDK, but does handle automatic signing and chunked/large uploads. Just curious!

**Comment by rijkvanzanten** [comment]
> I found their V2 API accepts the asset_folder and use_asset_folder_as_public_id_prefix parameters, replacing the previous folder parameter in uploads. However, it's also not available in all methods/api calls (like "resource" and "explicit").

Hours spent yelling at docs spent on this 😅 

> Have you looked at leveraging their Node SDK? It doesn't seem to be more than another auto-generated SDK, but does handle automatic signing and chunked/large uploads. Just curious!

I have! I don't know about the most up to date version, but when building the current implementation, the Cloudinary Node SDK didn't have any way to stream files in/out, which is a requirement to make the file rendering/thumbnail generation somewhat performant.

**Comment by sethkaufee** [comment]
I tested your branch, https://github.com/directus/directus/compare/main...issue/18146, on our deployment and have some comments/modifications. Would you like me to create a branch/PR as well to compare? I can also just leave comments on your changes as well!
