### ISSUE TITLE
Global Relational Variable multiple select shows no items

### ISSUE THREAD

**Issue by Stathis90** [directus/directus#19227]
### Describe the Bug

In Insights, if I create a Global Relational Variable with multiple select and select more than 21 items it shows no items even though the selection still persists
![grv](https://github.com/directus/directus/assets/15157178/1b1b98a7-e1ee-4098-9f85-a78a5716074a)

### To Reproduce

Create a dashboard 
Create a Global Relational Variable with multiple select
Select more than 21 items

### Directus Version

v10.4.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
Heya! What configuration are you using for this panel? Most importantly the `limit` option of the panel

**Comment by Stathis90** [comment]
Hey,

It's a simple table with just a manual string primary key. The limit is 50 I have try changing the limit but it's the same behavior.
![Screenshot_2023-07-24-16-50-52-52_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/directus/directus/assets/15157178/6551b538-0370-4667-afdf-1fc66134e2a0)

**Comment by rijkvanzanten** [comment]
This is actually another symptom of https://github.com/directus/directus/issues/16745 ! The panel uses an `in` statement, so once you hit 20 primary keys, the linked QS bug will cause some havoc. I'll bump the priority on that one to indicate it's causing multiple issues 👍🏻
