### ISSUE TITLE
discord auth

### ISSUE THREAD

**Issue by BlackDahlia313** [directus/directus#19224]
### Describe the Bug

When trying to add discord as a SSO provider, deployment fails and asks for the client id, even tho one is specified. 

Has anyone else seen this?

### To Reproduce

Add discord as a sso provider and try to deploy

### Directus Version

v10.4.3

### Hosting Strategy

Self-Hosted (Docker Image)

```
AUTH_DISCORD_DRIVER=oauth2

AUTH_DISCORD_CLIENT_ID=****

AUTH_DISCORD_CLIENT_SECRET=****

AUTH_DISCORD_AUTHORIZE_URL=https://discord.com/oauth2/authorize

AUTH_DISCORD_ACCESS_URL=https://discord.com/api/oauth2/token

AUTH_DISCORD_PROFILE_URL=https://discord.com/api/users/@me

AUTH_DISCORD_ALLOW_PUBLIC_REGISTRATION=true

AUTH_DISCORD_DEFAULT_ROLE_ID=*****

AUTH_DISCORD_ICON=discord

AUTH_DISCORD_LABEL=Discord

AUTH_DISCORD_EMAIL_KEY=email

AUTH_DISCORD_IDENTIFIER_KEY=email
```

**Comment by rijkvanzanten** [comment]
When I copy paste those exact environment variables (even with `***` instead of values) Directus seems to deploy on my end. How are you setting those environment variables? Could it be that some of the secrets aren't making it to the Directus environment properly? 

This is most likely a deployment related issue rather than a bug in Directus 🤔

**Comment by BlackDahlia313** [comment]
It’s really weird @rijkvanzanten 

I add that above like any other ENV and during finally deployment checks it fails and asks for client id. 

Been doing this for me since I started with directus. 

Only when I add discord. 

If I change it to openid I get an error. 

But if I change it back to oauth than it fails again asking for a client id that is def supplied. 

I’m wondering if it doesn’t like the client id for some reason?

Every other provider I throw doesn’t do this haha. 

Let me try creating a new app and getting fresh client id. 

Idk lol

**Comment by rijkvanzanten** [comment]
@BlackDahlia313 Can you try it with just `discord` and nothing else? 🤔

**Comment by BlackDahlia313** [comment]
> @BlackDahlia313 Can you try it with just `discord` and nothing else? 🤔

@rijkvanzanten 

just having discord there throws same thing. It just does not like discord it seems lol. I could try a fresh demo on railway instead of DO and test to see if it does the same thing. 

![image](https://github.com/directus/directus/assets/44903742/944ed1a6-bcaa-4698-a177-12ecfc356ebb)
![image](https://github.com/directus/directus/assets/44903742/9fc27b19-eb13-4b4f-8a43-c347e9ec72ba)

**Comment by BlackDahlia313** [comment]
@rijkvanzanten 

![image](https://github.com/directus/directus/assets/44903742/9353f099-4358-475c-986b-af73ba7cf172)

Confirmed it on a fresh demo railway deployment too. 

![image](https://github.com/directus/directus/assets/44903742/591f31f4-1c01-40b3-80d3-f542dcda7294)

**Comment by rijkvanzanten** [comment]
Very odd. Is there a chance that you have the same environment variable twice? Does it work when you rename it to something else (eg `dahlia` instead of `discord`). That is a generic error that'd be the same regardless of provider, so if it works for twitch, it should work for Discord 🤔 

(In any case, I'll close this for now as it's most likely a configuration issue rather than a bug in Directus. Happy to reopen if it turns out to be otherwise)

**Comment by BlackDahlia313** [comment]
> Very odd. Is there a chance that you have the same environment variable twice? Does it work when you rename it to something else (eg `dahlia` instead of `discord`). That is a generic error that'd be the same regardless of provider, so if it works for twitch, it should work for Discord 🤔
> 
> (In any case, I'll close this for now as it's most likely a configuration issue rather than a bug in Directus. Happy to reopen if it turns out to be otherwise)

discord is not duplicated anywhere. The second test was a fresh deployment and anything discord related was posted in the screenshot. 

When you add discord as a enabled auth provider you are not seeing this? if you just leave the variables in there without trying to enable it the error doesnt happen. its only when you try to enable it auth_providers.

In any case I just renamed everything to dahlia for example and followed the same method as twitch and its the same issue. 

I than tried adding a different sso like google and had no issue. So I need someone else to confirm this by adding it and trying to enable it with auth_providers. 

I did delete the profile url from the env and it threw the proper error:

![image](https://github.com/directus/directus/assets/44903742/22d0e109-5e3a-46f2-aa8b-0084e28f6006)


So my assumption is that there is something happening with this:

`AUTH_DISCORD_PROFILE_URL=https://discord.com/api/users/@me`

throwing the client id error

**Comment by BlackDahlia313** [comment]
@rijkvanzanten 

I didnt see this originally when searching. We should maybe put a small callout in the docs that specifically calls out discord.

https://github.com/directus/directus/issues/11956#issuecomment-1059733148

https://github.com/directus/directus/issues/11956

All is good now. But it is discord itself. so strange. 

Now the question is. should I leave it as dahlia or flip it back to discord lol xD

![image](https://github.com/directus/directus/assets/44903742/3905fe3b-2c4f-45df-ac4d-47aeb33c02b0)

**Comment by rijkvanzanten** [comment]
Ahhhhhhh yes I now see it too! In my testing before, I had non alpha characters in the client_id to test if it was the variable not making it to the setting. That makes a ton of sense, as discord only uses numbers. Another point to implement #9521 sometime soon..

**Comment by BlackDahlia313** [comment]
> Ahhhhhhh yes I now see it too! In my testing before, I had regular characters in the client_id to test if it was the variable not making it to the setting. That makes a ton of sense, as discord only uses numbers. Another point to implement #9521 sometime soon..

I knew I wasn't crazy! hahaha
