### ISSUE TITLE
Create Data Operation is ignoring auto increment Ids

### ISSUE THREAD

**Issue by danielband** [directus/directus#19222]
### Describe the Bug

I am seeding a database with either knex (straight to the db) or axios client (via directus api). Thus, I pass data with preset primary key Ids. The Ids column of the collection is an auto increment integer. In both cases the data is visible in directus admin. 

If I seed without specifying primary keys, the problem does not appear.

When executing a flow with a create operation the new data is rejected with the exception "RECORD NOT_UNIQUE". I would expect the operation to create a new row with an auto incremented id. It seems there is some kind of caching involved. That said, the caching option is not active in my scenario.

Executing the request over the directus endpoint '/items/collection' without specifying any id in the body works just fine.

One thing. I am starting Directus before seeding the DB. I tried restarting directus after seeding, but with the same result.

I attached the workflow and the postman requests beneath.

### To Reproduce

![1](https://github.com/directus/directus/assets/72872468/d46a05c0-998f-4a5e-944e-b7ca9e1a9b01)
![2](https://github.com/directus/directus/assets/72872468/81afd8c9-1694-4b20-869c-b3920eaf063d)
![3](https://github.com/directus/directus/assets/72872468/8339ecb4-f11f-4dbb-87d0-196b7140d347)
![4](https://github.com/directus/directus/assets/72872468/ac802fc9-68ec-4f31-9457-a0d84a3d041f)

### Directus Version

v10.4.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
This is a side-effect of how Postgres tracks auto increment primary keys. If you manually provide an ID (either in SQL or through Directus), Postgres won't update the `nextval` values. Once you create a new item, Postgres will use the wrong `nextval` value, which causes the duplicate error. 

I personally use the following snippet to generate the SQL required to force reset the sequence value to whatever the latest ID is.

<details><summary>Reset sequence snippet</summary>

```sql
SELECT 'SELECT SETVAL(' ||
       quote_literal(quote_ident(PGT.schemaname) || '.' || quote_ident(S.relname)) ||
       ', COALESCE(MAX(' ||quote_ident(C.attname)|| '), 1) ) FROM ' ||
       quote_ident(PGT.schemaname)|| '.'||quote_ident(T.relname)|| ';'
FROM pg_class AS S,
     pg_depend AS D,
     pg_class AS T,
     pg_attribute AS C,
     pg_tables AS PGT
WHERE S.relkind = 'S'
    AND S.oid = D.objid
    AND D.refobjid = T.oid
    AND D.refobjid = C.attrelid
    AND D.refobjsubid = C.attnum
    AND T.relname = PGT.tablename
ORDER BY S.relname;
```

</details>

There's discussions on how to improve this from Directus' side, by auto-resetting sequences (https://github.com/directus/directus/issues/6321), or potentially not relying on the database sequence at all (https://github.com/directus/directus/pull/19194)
