### ISSUE TITLE
WARN: storage:s3:responseTime in WARN state

### ISSUE THREAD

**Issue by samehhady** [directus/directus#19225]
### Describe the Bug

I am using S3 Storage to host all my images, my app loads around 500 image on page load by CDN till they are cached and from time to time I find this warning in logs and when it happens all further Directus calls slow down. instead of finishing the request in 10ms it finish in 1s! and some calls even takes more. 
Also at this time calling /server/health actually fails and either return in 0 seconds or null which leads to failed health check and my ECS service restart.

```
[06:56:16] GET /server/health null 0ms
[06:56:56] GET /server/health null 14.5s
[06:57:00.876] WARN: storage:s3:responseTime in WARN state, the observed value 18506.051 is above the threshold of 750ms
```

I don't think I am doing more than 1000 call to S3 which seems from docs way much less than the S3 limits so I am not really sure what is the problem.

 

### To Reproduce

Do 1000 call to S3 and then call the health check or any other endpoint.

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
I recall seeing some issues around s3 concurrency in older versions. Mind upgrading to the latest version? I believe this might already been resolved 👍🏻

**Comment by arladmin** [comment]
@rijkvanzanten 

In v10.8.2, getting a lot of 
```
GET /server/health null
```
sometimes followed by log messages like:
```
WARN: storage:DIGITALOCEAN:responseTime in WARN state, the observed value 1269.818 is above the threshold of 750ms
```
which is resulting in monitoring services marking the Directus instance as being **down**.

<hr>

Another example:
```
[04:51:56] GET /server/health null 47.8s
[04:52:04] GET /server/health null 4m 59.9s
[04:52:19.249] WARN: storage:DIGITALOCEAN:responseTime in WARN state, the observed value 241557.97 is above the threshold of 750ms
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TimeoutError: Socket timed out without establishing a connection within 5000 ms
    at Timeout._onTimeout (/directus/node_modules/.pnpm/@aws-sdk+node-http-handler@3.344.0/node_modules/@aws-sdk/node-http-handler/dist-cjs/set-connection-timeout.js:12:38)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[04:52:41.546] ERROR: storage:DIGITALOCEAN:responseTime in ERROR state
    err: {
      "type": "Error",
      "message": "Socket timed out without establishing a connection within 5000 ms",
      "stack":
          TimeoutError: Socket timed out without establishing a connection within 5000 ms
              at Timeout._onTimeout (/directus/node_modules/.pnpm/@aws-sdk+node-http-handler@3.344.0/node_modules/@aws-sdk/node-http-handler/dist-cjs/set-connection-timeout.js:12:38)
              at listOnTimeout (node:internal/timers:569:17)
              at process.processTimers (node:internal/timers:512:7)
      "name": "TimeoutError",
      "$metadata": {
        "attempts": 4,
        "totalRetryDelay": 448
      }
    }
```

**Comment by rijkvanzanten** [comment]
> Also, does this represent issue(s) within Directus (the S3 package), or with the S3 provider, DigitalOcean in this case?

No clue! It looks like it's having trouble connecting to digitalocean spaces. Do file uploads etc work as expected in this instance? 🤔 The health check endpoint just writes and deletes a temporary file to check if files work, so that should be the same

**Comment by arladmin** [comment]
> No clue! It looks like it's having trouble connecting to digitalocean spaces. Do file uploads etc work as expected in this instance? 🤔 The health check endpoint just writes and deletes a temporary file to check if files work, so that should be the same

DigitalOcean Spaces, in my concerned region, was suffering from a major incident yesterday, which led to all of my Directus instances suffer from this for several hours (for several hours i kept getting alerts regarding instances bein down, as the healthcheck endpoint couldn't be reached).

So, my question is, just because the S3 provider is having issues, should that make the Directus healtcheck endpoint unresponsive and useless?
