### ISSUE TITLE
Date columns not nullable from UI

### ISSUE THREAD

**Issue by ngirardhg** [directus/directus#1923]
Version Info
  - Directus version and branch: 6.4.3, release version
  - PHP version: 5.6.30
  - MySQL version: 5.0.11
  - Web server: Apache XAMPP
  - OS name and version: Windows 10 pro

## Expected Behavior
A field of type date already filled with a date (e.g. 2012-12-12) should be nullable from the UI.

## Actual Behavior
Trying to set a date field to NULL leaves it as it is, and does not save.

## Steps to Reproduce
 1. Create a table with a column of type date
 2. Set a random date
 3. Try setting it to NULL afterward (e.g. by clicking on the "x" button near the date picker)

**Comment by rijkvanzanten** [comment]
This was fixed in ba07c00435424254c3e07d6c18e80417472e14d9 on the develop branch and will be released in master soon
