### ISSUE TITLE
Block Editor - Alignment Tune change not causing save trigger

### ISSUE THREAD

**Issue by a-fazal** [directus/directus#19240]
### Describe the Bug

Changing the alignment tune in the block editor doesnt cause the save button to trigger. Even though the data in the blocks are technically changed. I have to change some other text to make it trigger.

https://github.com/directus/directus/assets/19141713/f0d13d7b-0f7f-47ed-bb2d-dadaa8c45e28

### To Reproduce

1. Create a block editor field.
2. Go to interfaces -> toolbar -> check off alignment.
3. Add some text.
4. Save.
5. Change the alignment of the text by clicking on the dots for the tune config to center or right.
6. Notice how the save button doesnt enable. 

### Directus Version

v10.4.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by DanielBiegler** [comment]
I could reproduce this in v10.4.3 and in latest v10.5.0 - checking out the raw value it does seem to not update.

After adding one character and re-checking the raw value it is correctly updated. Thank you for this report!

**Comment by paescuj** [comment]
Issue within the `editorjs-alignment-blocktune` plugin itself: https://github.com/kaaaaaaaaaaai/editorjs-alignment-blocktune/issues/12
We should try to move away from this plugin, as it seems to be unmaintained.

**Comment by rijkvanzanten** [comment]
@a-fazal wanna try your hand at a PR to resolve this issue? 🙂

**Comment by a-fazal** [comment]
Thanks for the fix @Nitwel !! @rijkvanzanten I've been quite busy with my projects but I'd love to help out Directus in the future when I find opportunity too
