### ISSUE TITLE
MSSQL - Cannot create two image fields on one collection

### ISSUE THREAD

**Issue by josip8** [directus/directus#19248]
### Describe the Bug

Cannot add two image fields to same collection
![image](https://github.com/directus/directus/assets/26368640/fa72eaba-725e-43c6-b2db-bfa0bd6308e6)

### To Reproduce

- Create new collection
- Add 1st image
- Add 2nd image -> BUG

### Directus Version

v10.5.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by josip8** [comment]
Hi, this is how image field looks like, I only added "key", all other properties are not changed from default:

![image](https://github.com/directus/directus/assets/26368640/8120a257-3c2b-420e-878d-c73b82bdcbd2)

In console output I these errors:

```AggregateError: ALTER TABLE [test] ADD CONSTRAINT [test_test2_foreign] FOREIGN KEY ([test2]) REFERENCES [directus_files] ([id]) ON DELETE SET NULL -```

```Error: Introducing FOREIGN KEY constraint 'test_test2_foreign' on table 'test' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.```

```Error: Could not create constraint or index. See previous errors.```

**Comment by BozeTadic** [comment]
Hello, same issue here. What I found out is that adding the field works if "Prevent deletion" is selected, but not any other relational triggers, e.g. "Set to default value".

**Comment by rijkvanzanten** [comment]
@BozeTadic @josip8 are both of you using MS SQL / Azure SQL by chance? That database can only have a single foreign key constraint to the same related table (very annoying.. but unfortunately not something we can do anything about)

**Comment by josip8** [comment]
@rijkvanzanten yes

Are there any other limitations with Directus + MS SQL? Do you recommend switching to PostgreSQL or some other database system?

**Comment by rijkvanzanten** [comment]
> Are there any other limitations with Directus + MS SQL?

For what it's worth, this is just a limitation of MS SQL as a database, not really on how we use it 😬 

> Do you recommend switching to PostgreSQL or some other database system?

This is a personal choice! I personally gravitate towards postgres as it has the least amount of quirks in my opinion, but others swear by mysql/mariadb.

**Comment by josip8** [comment]
@rijkvanzanten Got it! Thank you for quick responses 🙂
