### ISSUE TITLE
Issues with SDK v11 - not production-ready

### ISSUE THREAD

**Issue by stx-chris** [directus/directus#19245]
### Page

https://docs.directus.io/guides/sdk/getting-started.html

### Describe the Inaccuracy

Congrats on the new SDK! But after spending a day trying to rewrite code, we have reached a dead end. Unfortunately, the docs and Discord threads are insufficient to convert existing code to the new SDK. We are especially stuck keeping all the typings in line.

e.g. What is the correct typing for a Directus client that uses both `rest()` and `staticToken()` so that `client.request` is not rejected by the linter? What happened to the `ManyItems` and `QueryMany` types so the linter doesn't complain?

If such a drastic change is released, may I ask the team to provide a clear migration guide as well as a ton of example code before actually releasing such a breaking change? Unfortunately, a lot of the docs are still pointing to some non-existing `..../sdk%20(beta)/...` path as of yet.

Looking forward to upcoming improvements but for now we will be downgrading again to v10.

**Comment by paescuj** [comment]
it is not necessary to switch to the new SDK immediately, the old version will continue to work, but will no longer be supported or maintained.
The documentation of the new SDK will be continuously improved and supplemented.
However since the new version is a complete overhaul, I don't think a migration guide will be really feasible and helpful, since there will be no 1-to-1 migration steps.

> e.g. What is the correct typing for a Directus client that uses both `rest()` and `staticToken()` so that `client.request` is not rejected by the linter? What happened to the `ManyItems` and `QueryMany` types so the linter doesn't complain?

What's the error message here?

> Unfortunately, a lot of the docs are still pointing to some non-existing `..../sdk%20(beta)/...` path as of yet.

Could you provide the corresponding locations? As far as I know we have removed all beta references.

**Comment by stx-chris** [comment]
Hi @paescuj thx for your quick reply! I understand.

I spotted the outdated links mainly through the search bar, maybe due to an outdated search index.
e.g. for an outdated link: Go to Search bar and enter "staticToken"; Click on the first result, which will lead to `https://docs.directus.io/packages/@directus/sdk%20(beta)/module.auth-1/interfaces/interface.statictokenclient.html#interface-statictokenclient-schema`

Regarding the exact error messages I will create a separate post, thx.

**Comment by paescuj** [comment]
> Hi @paescuj thx for your quick reply! I understand.

You're welcome!

> I spotted the outdated links mainly through the search bar, maybe due to an outdated search index. e.g. for an outdated link: Go to Search bar and enter "staticToken"; Click on the first result, which will lead to `https://docs.directus.io/packages/@directus/sdk%20(beta)/module.auth-1/interfaces/interface.statictokenclient.html#interface-statictokenclient-schema`

I see, thank you! We're looking to refresh the search index!

> Regarding the exact error messages I will create a separate post, thx.

Great!
