### ISSUE TITLE
Screen freezing when clicking "Create New" button in any field "condition" in version 10.5.1

### ISSUE THREAD

**Issue by jagyas** [directus/directus#19259]
### Describe the Bug

I am not able to click "Create New" button inside **condition** tab of any field.

![image](https://github.com/directus/directus/assets/6293136/260eb38a-8e07-4464-a83d-50bdedbc4e0c)

### To Reproduce

Go to a colllection add any field (I am adding O2M). Click advanced mode and go to **condition** tab. Try to click "Create New" and screen will freeze.

### Directus Version

v10.5.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by DanielBiegler** [comment]
Hi there! Just tried it out on v10.5.1 both for a simple string field and a one-to-many relation, both work for me?
[Screencast from 27.07.2023 14:37:40.webm](https://github.com/directus/directus/assets/14810858/2a99c6ae-799f-49f6-b69f-77a298f40b24)

Is there maybe an error in the console that you could share? Can't reproduce this.

**Comment by Triggsy22** [comment]
Have the exact same problem, in directus version 10.5.0 and 10.5.1
The whole browsertab is freezing.
From the Moment you click on 'Create New' nothing will appear in the console again, i cant even write anything in the console, cause its also frozen.
Also my processor goes up to 20%, so it could be some kind of an endless loop.
Tried it in chrome, opera, edge and firefox, all with the same problem

**Comment by mladimatija** [comment]
> Have the exact same problem, in directus version 10.5.0 and 10.5.1 The whole browsertab is freezing. From the Moment you click on 'Create New' nothing will appear in the console again, i cant even write anything in the console, cause its also frozen. Also my processor goes up to 20%, so it could be some kind of an endless loop. Tried it in chrome, opera, edge and firefox, all with the same problem The type of the field doesnt matter, problem occours in all kind of fields i tried.

I can confirm the the issue as well. I installed a fresh copy of Directus 10.5.0 and 10.5.1 and can reproduce this issue as soon as creating a first field (simple text field).

**Comment by paescuj** [comment]
The issue has been confirmed and is being investigated right now 👍

**Comment by 3615alexis** [comment]
Same problem here in 10.5.1.
The problem seems to occur with any type of field. I just tried with a brand new "test" collection with 2 test fields, same issue.
I can't find any trace in the console. No logs on server side either, even when I put "LOG_LEVEL" to "trace".
On postgreSQL side, I can't find any long running query : 

![image](https://github.com/directus/directus/assets/6710698/01e09845-b49e-4f85-8ad1-26c365164597)

Any idea ?
