### ISSUE TITLE
Unable to authenticate to websocket

### ISSUE THREAD

**Issue by Zyles** [directus/directus#19258]
### Describe the Bug

I am unable to authenticate to the websocket.

### To Reproduce

```
$ npm i ws

import * as WebSocket from 'ws'

const websocketUrl = 'wss://your-directus-url/websocket'
const accessToken = 'xxxxx'
const ws = new WebSocket(websocketUrl)

    ws.on('error', console.error);

    ws.on('open', async function open() {
      console.log('ws open')
      ws.send(JSON.stringify({
        type: 'auth',
        accessToken,
      }))
    });

    ws.on('message', async function message(data) {
      console.log('received: %s', data);
    });

```

Error:
```
ws open
received: {"type":"auth","status":"error","error":{"code":"AUTH_FAILED","message":"Authentication handshake failed
."}}
```

I am using a created user with a static token, not the primary admin user if that makes a difference.

And yeah I don't want to use the SDK because I want to be able to connect to other websockets too.

### Directus Version

latest

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Zyles** [comment]
The docs are incorrect: https://docs.directus.io/guides/real-time/getting-started/websockets.html

Needs to be:
```
ws.send(JSON.stringify({
        type: 'auth',
        access_token: accessToken,
      }))
```

**Comment by cdwmhcc** [comment]
same
