### ISSUE TITLE
Dropdown Enum: Server error

### ISSUE THREAD

**Issue by BennerGe** [directus/directus#1925]
## Version Info
  - Directus version and branch: Current develop branch
 - MySQL version: 14.14 Distrib 5.7.20

## Actual Behavior
Adding a column of type 'dropdown enum' leads to the following error:

`Statement could not be executed (42000 - 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') COMMENT "''"' at line 1)`

**Comment by rijkvanzanten** [comment]
Hi @BennerGe!

ENUM values are stored in the `length` field in SQL, and an empty value isn't valid. That means that this setup works:

<img width="662" alt="screen shot 2017-10-26 at 1 21 15 pm" src="https://user-images.githubusercontent.com/9141017/32067749-4433ff42-ba52-11e7-8aa9-6f842307f3d2.png">

That being said, we should definitely implement some sort of warning or a better error.

**Comment by BennerGe** [comment]
Okay thanks, I didn't get that the values must be entered in the length field.

**Comment by rijkvanzanten** [comment]
That's understandable, `dropdown_enum` is the only dropdown interface for which this is the case.

**Comment by rijkvanzanten** [comment]
@WellingGuzman Should we add a way to add instructions to this view?
We could introduce a `instructions` field to `UIComponent` which gets shown in this whitespace:

<img width="662" alt="screen shot 2017-10-26 at 1 21 15 pm" src="https://user-images.githubusercontent.com/9141017/32110736-4ac9224c-bb06-11e7-9fc7-205d111f1829.png">

We can add important notes on interfaces a general description. What do you think?

**Comment by WellingGuzman** [comment]
> We could introduce a `instructions` or `description` field to `UIComponent` which gets shown in this whitespace:

@rijkvanzanten I like that, let's make that happen.

**Comment by benhaynes** [comment]
Good solution! It shouldn't be an issue, but remember that we're using that space for an "important announcement" for ALIAS interfaces/columns.
