### ISSUE TITLE
Custom modules disappeared in v10.5.0

### ISSUE THREAD

**Issue by NecoHorne** [directus/directus#19250]
### Describe the Bug

After update to v10.5.0 custom modules disappeared. 

I can see it registered on Directus startup in the logs but its no longer available in the side panel or the project settings.
![image](https://github.com/directus/directus/assets/30078491/43de9694-0bc2-49c0-883f-f9ba1fee121f)

![image](https://github.com/directus/directus/assets/30078491/b3584dd6-d618-46a2-a74f-3e2e7ce1572a)

I checked the release notes and docs and I don't see any breaking changes listed for custom modules. 

### To Reproduce

Update to v10.5.0

### Directus Version

v10.5.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
Which version did you upgrade from?
Please make sure to upgrade properly according to this guide: https://docs.directus.io/self-hosted/upgrades-migrations.html

**Comment by NecoHorne** [comment]
> Which version did you upgrade from? Please make sure to upgrade properly according to this guide: https://docs.directus.io/self-hosted/upgrades-migrations.html

v10.4.3,

just ran migrations, still the same issue

**Comment by NecoHorne** [comment]
Some more info:

Weird thing is I upgraded another project, also from v10.4.3 to v10.5.0 and the custom modules loaded fine in that project. 

I have deleted `package-lock.json` and node modules from both the project and custom module and re-run npm install, and rebuild the module still same issue. I just ran log level trace and can't see anything specific that might lead to this issue. 

Nothing very different in the package.json files of the 2 projects, also upgraded `@directus/extensions-sdk` to `^10.1.7` from 10.1.5, still same issue. Will comment here if I find anything else more helpfull

**Comment by paescuj** [comment]
Thanks for opening this issue and posting additional information!
I've already identified the problem. A fix is on the way!

**Comment by NecoHorne** [comment]
@paescuj Awesome thanks. 

Just checked the web console too and saw this. Maybe a bit more extra info. 

![image](https://github.com/directus/directus/assets/30078491/2a1ca6d9-df98-4232-9d74-c89cbe564816)

Thanks for jumping on it!

**Comment by Dominic-Marcelino** [comment]
This doesn't only happens to module (in my case bundled interfaces + displays). I assume it's related to the extension loading?
