### ISSUE TITLE
UPdate from 10.3 to 10.5 of self-hosted DOcker version not working due to Redis

### ISSUE THREAD

**Issue by rowild** [directus/directus#19251]
### Describe the Bug

I want to update my self-hosted Docker Directus v10.3 instance to 10.5 by applying the `directus > image: directus/directus:10.5.0` and `docker compose up -d`.

When the instance is started, I cannot open the standard URL `http://127.0.0.1:8055/`. Upon inspecting Docker Desktop, I find these log messages listed in the attached text file (time code removed).

[dennis-dk_cache-1.txt](https://github.com/directus/directus/files/12171429/dennis-dk_cache-1.txt)

This is my docker-compose.yml file:
[docker-compose.yml.zip](https://github.com/directus/directus/files/12171439/docker-compose.yml.zip)

### To Reproduce

- Use the included docker-compose-yml – BUT change the directusimage version to 10.3 first
- Run `docker compose up -d`
- Check if it is working by opening the URL `http://127.0.0.1:8055`
- Run `docker compose down`
- Change the version of the Docker Directus image to 10.5
- Run `docker compose up -d`
- Try opening the URL `http://127.0.0.1:8055`

### Directus Version

10.3, 10.5

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Please update the environment variables for Redis according to the notes from https://github.com/directus/directus/releases/tag/v10.4.0 under "Consolidated environment variables for Redis use".

**Comment by rowild** [comment]
@paescuj Wow! closing right away! Not even awaiting and answer... did you even try??? Just because I forget to mention a step it doesn't mean that the issue is not justified. Really... that behaviour does not really enforce ones motivation to help...

**Comment by paescuj** [comment]
The problem is quite apparent to me because as mentioned above the environment variables for Redis need to be updated for 10.4.0+, which is why I've closed the issue.
Regardless of closing the issue, I'm happy to keep discussing in this thread, and if it turns out that it is indeed a bug, we can  reopen the issue.
