### ISSUE TITLE
Admin editing warning on single-item table

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1926]
## Version Info
  - Directus version and branch: develop 8075e93b769e0d556c306982dc28f67e20bce435
  - PHP version: `7.0.2`
  - Web server: Caddy `0.10.10`
  - OS name and version: macOS High Sierra 10.13.1 Beta (17B25c)

## Behavior
Editing a single-item table shows the following error:
```
Warning
Admin User is also editing this page, please coordinate with them to ensure there are no save conflicts.
```
while I'm the admin user (and the only user in Directus)

## Steps to Reproduce
 1. Use the provided sql
 2. Edit the single-item table `site_settings`

## Schema Dump, Logs, or Screenshots
[db_reset.sql.zip](https://github.com/directus/directus/files/1418959/db_reset.sql.zip)

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/1d06470fccdf4d9115215732585adde50b195faa (wrong reference)
