### ISSUE TITLE
@directus/sdk: TS2451: Cannot redeclare block-scoped variable 'Query'.

### ISSUE THREAD

**Issue by AndreasGBS** [directus/directus#19261]
### Describe the Bug

HI, I get an error when using the new SDK 
node_modules/@directus/sdk/dist/index-c4b8121c.d.ts:2:127 - error TS2451: Cannot redeclare block-scoped variable 'Query'.

2 import { ad as MergeCoreCollection, ab as RelationalFields, af as AllCollections, aj as UnpackList, ag as GetCollection, X as Query, a6 as ItemType, D as DirectusActivity, O as ApplyQueryFields, am as IfAny, ak as Merge, N as PickFlatFields, K as FieldsWildcard, ai as Mutable, P as PickRelationalFields, ao as IsNullable, I as HasManyToAnyRelation, U as ApplyNestedQueryFields, T as ApplyManyToAnyFields, i as DirectusCollection, k as DirectusDashboard, l as DirectusField, ap as NestedPartial, o as DirectusFile, p as DirectusFlow, q as DirectusFolder, a7 as CollectionType, r as DirectusNotification, s as DirectusOperation, t as DirectusPanel, u as DirectusPermission, v as DirectusPreset, w as DirectusRelation, ac as RemoveRelationships, y as DirectusRole, A as DirectusShare, B as DirectusUser, E as DirectusWebhook, a9 as RegularCollections, x as DirectusRevision, z as DirectusSettings, a8 as SingletonCollections, W as WebSocketAuthModes } from './output-476d05a4.js';

### To Reproduce

Here my setup: 
   Ionic CLI                     : 7.1.1 (/Users/aj/.nvm/versions/node/v18.13.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.1.4
   @angular-devkit/build-angular : 15.2.1
   @angular-devkit/schematics    : 15.2.1
   @angular/cli                  : 15.2.1
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.6.2
   @capacitor/android : 4.6.2
   @capacitor/core    : 4.8.0
   @capacitor/ios     : 4.8.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.13.0 (/Users/aj/.nvm/versions/node/v18.13.0/bin/node)
   npm    : 8.19.3
   OS     : macOS Unknown

### Directus Version

v10.5.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
I installed the mentioned dependencies and was unable to reproduce this issue. Please provide complete steps how to reproduce this issue :) Happy to re-open the issue when more info becomes available
