### ISSUE TITLE
Econnrefused redis?

### ISSUE THREAD

**Issue by nordcart** [directus/directus#19275]
### Describe the Bug

I upgraded from 10.1.1 to 10.5.1. The directus app is not working at all after the upgrade.

[05:55:56.375] WARN: [cache] Error: connect ECONNREFUSED 127.0.0.1:6379
directus    |     err: {
directus    |       "type": "Error",
directus    |       "message": "connect ECONNREFUSED 127.0.0.1:6379",
directus    |       "stack":
directus    |           Error: connect ECONNREFUSED 127.0.0.1:6379
directus    |               at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
directus    |       "errno": -111,
directus    |       "code": "ECONNREFUSED",
directus    |       "syscall": "connect",
directus    |       "address": "127.0.0.1",
directus    |       "port": 6379
directus    |     }

### To Reproduce

Upgrade

### Directus Version

10.5.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by licitdev** [comment]
We had consolidated `REDIS` environment variables in `10.4.0`.
Kindly refer to the [release notes](https://github.com/directus/directus/releases/tag/v10.4.0). Thank you.
