### ISSUE TITLE
Fields Not Saving

### ISSUE THREAD

**Issue by VladDigitalOriginal** [directus/directus#19279]
### Describe the Bug

I have deleted and created the collection several times (my mistake, I know). After doing this and maybe something more, I noticed that fields do not save data, except for related fields.
<img width="420" alt="Screenshot 2023-07-28 at 13 06 33" src="https://github.com/directus/directus/assets/122997283/6dcaf829-7914-4cd2-a468-f432c3bf7c27">
<img width="464" alt="Screenshot 2023-07-28 at 13 06 46" src="https://github.com/directus/directus/assets/122997283/8c75985e-795a-462f-b500-646857692c54">
<img width="509" alt="Screenshot 2023-07-28 at 13 06 53" src="https://github.com/directus/directus/assets/122997283/d6510bcb-2c5f-40bf-929a-4c52401f2351">

### To Reproduce

Unfortunately, I am unable to recreate the issue at the moment. However, prior to this happening, I performed the following actions: created and deleted the collection multiple times, and established m2m relations with other fields.

### Directus Version

v10.5.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
It's going to be near impossible for us to reproduce this 🤔 Would you be able to share a database dump where this is happening?

**Comment by VladDigitalOriginal** [comment]
Yeah, here it is:
[fields-not-saving.zip](https://github.com/directus/directus/files/12216515/fields-not-saving.zip)

**Comment by VladDigitalOriginal** [comment]
@rijkvanzanten 
Collections which I had corrupted:
- techniques
- fields
- tags
