### ISSUE TITLE
Setup encoding problem 

### ISSUE THREAD

**Issue by Jan10** [directus/directus#1927]
## Version Info
  - Directus version and branch: 6.4.3
  - PHP version: 7.0.13
  - MySQL version:  10.1.19-MariaDB 
  - Web server: Apache/2.4.23 (Win32) 
  - OS name and version: Windows 7

## Steps to Reproduce
 1.  In the setup process enter "Müller" as project name.
 2.  On step 4 in the setup process the project name is not displayed correctly.

## Schema Dump, Logs, or Screenshots
![2017-10-27-000015](https://user-images.githubusercontent.com/192557/32095274-e6ebae1e-bb02-11e7-8863-863e77b46741.png)

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/cbcc5ec3e52a5ff77bbc13cb7c1a03e8218c02f8
