### ISSUE TITLE
WYSIWYG editor becomes incorrectly disabled

### ISSUE THREAD

**Issue by BenoitAverty** [directus/directus#19278]
### Describe the Bug

A field using the WYSIWYG interface becomes disabled when the interface has been used in another page.

I have a collection with a WYSIWYG field.

When I interact with an item in this collection for the first time after a full page refresh, the field works fine and I can edit my content and save the item.

However, when I try again with another item or the same, the field is disabled and the value can't be edited (except with the "dit raw value" button)

### To Reproduce

1. Create a collection
2. Add a field in standard mode, chosing the "WYSIWIG" option with default settings
3. Create an item of this collection : the wysiwyg field works fine
4. Edit the created item : the field is disabled
5. refresh the page : the field is enabled.
6. Modify the field and save the item
7. Edit the same item : the field is disabled

### Directus Version

v10.5.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by nfabacus** [comment]
I am still getting the same issue with the latest 10.5.2, and it is getting unusable as I have to refresh the page every time to enable the editor... Not sure if anyone else is having the same issue?  I am downgrading it to 10.4.3 to see if I still encounter the issue...previously I had no issue with 10.4.3.

**Comment by nfabacus** [comment]
ok, thank you @paescuj 
For now, I reverted the version back to 10.4.3 until the next release, and all working fine.
