### ISSUE TITLE
[SDK, TypeScript] Filter type does not accept logical operators

### ISSUE THREAD

**Issue by martijn-dev** [directus/directus#19285]
### Describe the Bug

The [Filter type](https://docs.directus.io/reference/filter-rules.html) accepts only attributes of the entity it is filtering on, while it should also allow for [logical operators](https://docs.directus.io/reference/filter-rules.html#logical-operators).

This was reported first in an old issue https://github.com/directus/directus/issues/7475#issuecomment-1655762961.

### To Reproduce

```ts
 directus.request(
        readItems('users', {
          filter: {
            _or: [ //<- Type '{ _or: { name: string; }[]; }' is not assignable
              {
                name: 'martijn',
              },
              {
                name: 'directus',
              },
            ],
          },
        }),
      )
```

### Directus SDK Version

v11.0.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Pachat** [comment]
Just to mention that the OP refers to version 11.0. But Directus today is at v10.5.2
Version error is probably due to #18795

**Comment by br41nslug** [comment]
@Pachat the OP is referring to the specific `Directus SDK` version not the global Directus version :)
