### ISSUE TITLE
Cannot find module '@directus/schema' or its corresponding type declarations - Angular 16 - Ionic 7

### ISSUE THREAD

**Issue by kulkarni005** [directus/directus#19292]
### Describe the Bug

as Reported earlier in #19260 
This issue is not resolved. - Checked on @directus/sdk 11.0.1.
I am working on Angular project frontend only - Should I need to install knex, vue in it ?
can we decouple frontend type defs - Core SDK type defs?
am i doing something wrong ? Please suggest appropriate NPM package to use.
Let me know how can i contribute in resolving this.

![256956839-565e0b00-d1f3-4e69-ab9b-1fb9ba473398](https://github.com/directus/directus/assets/10194474/1cee2c70-ec26-4109-9f1c-13c9ddb43cbe)

### To Reproduce

Fresh ionic app creation :
Ionic start --type=angular tabs

Install Directus sdk :
npm install @directus/sdk

Start the app - after importing sdk in appropriate service / component
ionic start

### Directus Version

10.5.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
Similar issue exists in a nuxt context:

```
The inferred type of 'default' cannot be named without a reference to '.pnpm/@directus+types@10.1.3/node_modules/@directus/types'. This is likely not portable. A type annotation is necessary.
```

**Comment by rijkvanzanten** [comment]
@br41nslug in case it helps: my particular error seems to be a regression between 11.0.0 and 11.0.1 👍🏻

**Comment by br41nslug** [comment]
is our types package not compatible in these runtimes? 🤔 only change in sdk that this could be is the moving of `@directus/types` to dependencies as fix for https://github.com/directus/directus/issues/19260

I could of course remove the one reference to the `@directus/types` package (and probably will as short term solution) however i would like to be able to rely in our shared packages over maintaining types in 2 places.

**Comment by kulkarni005** [comment]
In @directus/sdk 11.0.0 - this single change of line fixed the issue for me.
path : /node_modules/@directus/sdk/dist/index-xxxx.js and output-xxxx.ts.

//import { PrimaryKey } from '@directus/types';
export type PrimaryKey = string | number;

Only def of PrimaryKey was required.

but after update to @directus/sdk 11.0.1  above trick no longer works as @directus/types added in dependencies in PR #19296

**Comment by SvenBudak** [comment]
> but after update to @directus/sdk 11.0.1 above trick no longer works

Unfortunately, your fix (at least for me) also doesn't work with `11.0.0`.
