### ISSUE TITLE
[SDK] Can't read items with meta

### ISSUE THREAD

**Issue by pierre-H** [directus/directus#19298]
### Describe the Bug

With the JS SDK (`v11.0.1`), we can't readItems with meta

### To Reproduce

```ts
 apiClient.request(readItems('posts', {
		filter: {
			categorie: {
				slug: {
					_eq: params.slug
				}
			}
		},
		page,
		sort: ['sort', 'name'],
		meta: '*'
	}));
```

### Directus Version

v10.5.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
Correct, please refer to aggregation for your meta information needs :) https://docs.directus.io/reference/query.html#aggregation-grouping

**Comment by eytanProxi** [comment]
So we need two queries now instead of one 😢  ...

**Comment by hambanet** [comment]
@br41nslug For REST queries, the docs say `?meta=*` is valid.

The new SDK doesn't appear to permit the meta parameter in REST queries. It should be permitted, no?

<img width="287" alt="image" src="https://github.com/directus/directus/assets/54257468/6f307cb5-d33a-4ccf-9a4b-2c7200749f51">

**Comment by hambanet** [comment]
Issue #15665 seems to clear this up.
