### ISSUE TITLE
`count` function in SDK missing from types

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#19294]
### Describe the Bug

When trying to use `count()` on a relational field, TypeScript throws an error:

<img width="1338" alt="CleanShot 2023-07-29 at 12 19 13@2x" src="https://github.com/directus/directus/assets/9141017/afc47ea8-ca26-4ff8-b721-770c85452304">

### To Reproduce

```ts
import { createDirectus, rest, readItems } from '@directus/sdk'

interface Example {
  id: string;
  related: number[] | Relational[];
}

interface Relational {
  id: number;
}

interface Schema {
  example: Example[];
  relational: Relational[];
}

const directus = createDirectus<Schema>('https://example.com').with(rest());

directus.request(readItems('example', {
  fields: ['count(related)']
});
```

```
Type '"count(related)"' is not assignable to type '"*" | keyof Example | QueryFieldsRelational<Schema, Example>'.ts(2322)

```

### Directus Version

v10.5.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Same goes for any other function in the `fields` list
