### ISSUE TITLE
readItems type error on sdk 11

### ISSUE THREAD

**Issue by 50l3r** [directus/directus#19309]
### Describe the Bug

SDK Version: 11.0.1

I have a TS (2345) problem when i try to execute a rest function:

`Argument of type "string" is not assignable to parameter "never"`

Thats a minimal reproduction for the issue:

```
import { createDirectus, graphql, readItems, rest, staticToken } from '@directus/sdk'

interface Plattform {
    id: number
    sort: number
    name: string
    logo: string
}

interface Schema {
    plattform: Plattform
}

async function init() {
    const client = createDirectus<Schema>('https://example.com')
        .with(rest())
        .with(staticToken('XXXXXXXXXXXXXXXXXXX'))
        .with(graphql())

    const plattforms = await client.request(readItems('plattform'))

    return plattforms
}
```

Maybe i am doing something wrong?

### To Reproduce

1. Try to create directus instance with predefined schema
2. Execute `readItems` method
3. Linter says `argument of type "string" is not assignable to parameter "never"`

### Directus Version

10.4.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Looks like you have `Plattform` marked as singleton in the Schema :) either use the `readSingleton()` function or update the schema to the following if that was unintentional :)
```ts
interface Schema {
    plattform: Plattform[];
}
```

**Comment by 50l3r** [comment]
> Parece que ha `Plattform`marcado como singleton en el esquema :) use la `readSingleton()`función o actualice el esquema a lo siguiente si eso no fue intencional :)
> 
> ```ts
> interface Schema {
>     plattform: Plattform[];
> }
> ```

Much thanks :D It works

**Comment by Sandros94** [comment]
@br41nslug but what if, in my Schema, I have multiple collections and I need to retrive everything in one function? Do I must add a `createDirectus` for each collection (or type of)?

Shouldn't this just work?
```ts
import { createDirectus, readItems, rest } from '@directus/sdk'

interface Globals {
  title: string
  description: string
  cover_image: string
}

interface Plattforms {
  id: number
  sort: number
  name: string
  logo: string
}

interface Schema {
  plattforms: Plattforms[]
  globals: Globals
}

async function init() {
  const client = createDirectus<Schema>('https://example.com').with(rest())

  const plattforms = await client.request(readItems('plattforms'))
  const globals = await client.request(readItems('globals'))

  return plattforms, globals
}
```

**Comment by br41nslug** [comment]
@Sandros94
> Shouldn't this just work?

Since the API output is different between regular and singleton collections you'll need to use the appropriate `readSingleton` function for the types to match the returned data. Having said that your code should "just work" if you're willing to ignore the incorrect types as the API call is almost identical the main difference is in the functions input/output TS typing.

Side note: There is a syntax error in your `return` statement

> Do I must add a createDirectus for each collection (or type of)?

You can if you want or re-use your client, whatever works best in your situation. I would recommend re-using your client in most cases.

**Comment by Sandros94** [comment]
> Since the API output is different between regular and singleton collections you'll need to use the appropriate `readSingleton` function for the types to match the returned data. Having said that your code should "just work" if you're willing to ignore the incorrect types as the API call is almost identical the main difference is in the functions input/output TS typing.

Oh right, I forgot about that, my bad.

> Side note: There is a syntax error in your `return` statement

I knew something was off with the return while writing it on mobile, once I got back to the desk my finger autopilots made me realize it.

> You can if you want or re-use your client, whatever works best in your situation. I would recommend re-using your client in most cases.

Yes, that was my goal and reason why I kept on testing this.
