### ISSUE TITLE
SDK should report `response.status` on fetch failure

### ISSUE THREAD

**Issue by aclisp** [directus/directus#19304]
### Describe the Bug

Hi, I want to implement a login page redirection when an unauthenticated user tries to access some collection. I'm using `@directus/sdk` like this:
```
try {
        const result = await client.request(
	    readItems('collection_name', {
		query,
	    })
        );
} catch (error: any) {
     // if it is 403 Forbidden, then redirect to the login page.
}
```
However, there is no way to get `response.status` from `error`.

I looked through the source code, when fetch failed, the throwing error is just the body content.
https://github.com/directus/directus/blob/318c77270fc62976e934e1eb42f905acf8192585/sdk/src/utils/request.ts#L36C1-L36C36

When fetch failed, there should be a reliable way to get the exact HTTP status code. 

### To Reproduce

As above.

### Directus Version

v10.5.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by kueronya** [comment]
I agree not being able to handle status codes is pretty frustrating. 

I would also like to extend that issue to the onResponse() callback which seems to map the response to the data array and strips off the response object completely which makes it impossible to write some kind of interceptor. It also just get called on successful requests making it impossible to do some global error intercepting/handling.

```typescript
const directus = createDirectus<DirectusSchema>(process.env.API!)
.with(rest({
      onResponse: (res) => {  
      // onResponse() isn't called on error responses
      // onResponse() isn't called for successful login() either (!) 
      // res is just mapped data without response object
        return res
      }
    }))
``` 

It would be awesome to have at least somehow access to the original response for plain requests as well as the onResponse() callback to handle errors or do some global intercepting.
