### ISSUE TITLE
Creating many to one relationship FK fails (data type mismatch)

### ISSUE THREAD

**Issue by seanmangar** [directus/directus#19315]
### Describe the Bug

Foreign key data type (created by Directus) is not aligned with the primary key data type so creating the foreign key constraint fails.

Observed this in several places where Directus automatically creates tables behind the scenes 
1. Setting up translations.
2. Setting up a many to one field.

### To Reproduce

1. Create a table with a primary key of **bigint** in MySQL 5.7 (this was an already existing table created outside of Directus)
2. Go to data model and create a many to one relationship to relate to this primary key
3. Foreign key constraint creation fails as Directus creates a FK field with data type **int** instead of **bigint**

<img width="719" alt="Screenshot 2023-08-01 at 08 47 20" src="https://github.com/directus/directus/assets/6080053/b47cf17c-3be0-4f52-8f63-0e549ff04f15">

### Directus Version

v10.5.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
I wasn't able to reproduce this on MySQL 8.0.34. Could you try updating the database? MySQL 5.7 is no longer supported[^1] and is end-of-life in 2 months.

[^1]: only "extended support" for enterprise customers of Oracle

**Comment by seanmangar** [comment]
Thanks @rijkvanzanten - will make a note to upgrade and try again. I was able to get it to work by creating database records manually - maybe not the best approach but it works for now.
