### ISSUE TITLE
WYSIWYG is not allowing edit once created.

### ISSUE THREAD

**Issue by jagyas** [directus/directus#19314]
### Describe the Bug

Once collection record is created, I am not able to edit WYSIWYG input box.

![image](https://github.com/directus/directus/assets/6293136/ca177726-fe91-4cd7-bed4-f65cf158e74d)

### To Reproduce

Create a collection and add WYSIWYG input field. Create a collection record and add text in WYSIWYG field and save record. Try to edit the record, you can not. It becomes readonly.

### Directus Version

v10.5.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Couldn't reproduce this so far on my end. Do you have a special setup for the field?
Also please make sure to clear the browser cache and then try again.

**Comment by jagyas** [comment]
No, I do not have any special setup. When I tried to open saved record in incognito mode then it allows edit but after making any change when I am saving again it becomes readonly.

**Comment by paescuj** [comment]
Thanks for the info! I'm able to reproduce it on Chrome, while there's no issue in Firefox.

**Comment by KonstantinSolv** [comment]
We have issue, happens 99% on Chrome, sometimes its slips through and works. On Firefox other way around, works most of the time, an occasionally field is blocked.
