### ISSUE TITLE
Editing wysiwyg interface options results in error

### ISSUE THREAD

**Issue by mmeester** [directus/directus#1931]
## Version Info
  - Directus (master branch)
  - PHP version: 7.0
  - MySQL version:  5.7
  - Web server: Apache

## Expected Behavior
Editing interface options in small wysiwyg should be applied and result in exteded options.

## Actual Behavior
Editing row impossible and crashes with following javascript error: `Error
Error: Uncaught TypeError: Cannot read property 'name' of undefined
File: /app/core/interfaces/wysiwyg/vendor/medium-editor.min.js?bust=tr1n62e6717fblqcqnho5c00a0
Line:3`

## Steps to Reproduce
 1. Edit table
 2. Edit wysiwyg interface options 
 3. Go to row in table

Can be solved by editing `directus_columns` and removing comma's in front and end of buttons json created: ```{"id":"wysiwyg","buttons":",bold,italic,underline,anchor,quote,orderedlist,h2,h3,","buttons_orderedlist":"orderedlist"}```

Should be:
```{"id":"wysiwyg","buttons":"bold,italic,underline,anchor,quote,orderedlist,h2,h3","buttons_orderedlist":"orderedlist"}```

**Comment by rijkvanzanten** [comment]
Hi @mmeester!

Thanks for the heads up, and thanks for your PR!

Wrapping the values of the checkboxes in another set of delimiters is in fact a feature (not a bug) of the checkboxes interface, however, the option should've been turned off for the `wysiwyg_full` buttons.

I have just pushed a commit to turn this option off for the wysiwyg_full buttons. I'll still merge your fix, as it introduces a safety net for people who already have `wysiwyg_full` setup with the delimiter option still on.

Groetjes!
