### ISSUE TITLE
Minor issue with fields parameter in items requests

### ISSUE THREAD

**Issue by sharkfin009** [directus/directus#19324]
### Describe the Bug

When specifying relational field data (many to many), eg "images.*.description" I am getting back what I asked for , plus any field with the same name on the primary record. 

### To Reproduce

Do a GET request ( /items/<collection>) on any collection with a many to many related collection . Add a fields parameter that specifies a relational field , the name of which is also found on the collection you are querying. 

### Directus Version

v10.0.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by sharkfin009** [comment]
``` "images": [
            {
               "id": 6,
               "packages_id": {
                  "description": "<p><strong>Looking for a festive romantic break in early 2023? Well here's your opportunity to score big time on this great deal with&nbsp;35% discount included - book and pay by 30 November 2022.</strong></p><p>The 3 star Plus Adaaran Club Rannalhi's unique location offers access to pristine beaches, excellent scuba diving opportunities and a relaxed environment with easy access to the capital city of Male.</p><p>The Adaaran Club Rannalhi is featured among the best hotels in Maldives and sits exclusively at the tip of the South Male atoll within the exotic collection of islands known as the Maldives.&nbsp;Bask in the golden sun and frolic on the soft sands as you experience friendly Maldivian hospitality and explore the rich tropical wonders of a vibrant island nation during your stay at our inviting Maldives hotel.<strong>&nbsp;</strong></p><p><strong>UNIQUE OFFERING:</strong><br>Access to pristine beaches<br>Excellent scuba diving opportunities<br>Exciting watersports<br>Fun excursions to choose from<br>Doctor on call<br><br><strong>RESORT FACILITIES:</strong><br>Spa<br>1 Restaurant, 2 bars and a coffee shop<br>Water sports: Wind surfing, Snorkelling, Scuba diving, Water skiing, Surf jets, Diving<br>Activities: Table tennis, Beach volleyball, Beach football</p>"
               },
               "directus_files_id": {
                  "description": "Preskil Island Resort (2) in Mauritius",
                  "filename_disk": "1628162d-b043-455f-b76b-4a856a3b06e3.jpg",
                  "filename_download": "5ca338686e06e646353931-lg.jpg"
               }
            }
         ]``

This show part of the response. 'images' is the relational field. I am getting 'description' under the packages_id key, which is not in my 'fields' parameter. Packages is the name of the collection I am querying.

**Comment by rijkvanzanten** [comment]
> This shows part of the response. 'images' is the relational field. I am getting 'description' under the packages_id key, which is not in my 'fields' parameter. Packages is the name of the collection I am querying.

Is it not though? With `images.*.description`, you're effectively asking for "description in everything that's nested in images", so what you're getting back looks correct to me! What you're looking for might be `fields=images.*,images.directus_files_id.description` (which is "everything on the first level of `images`, and the nested description for `directus_files_id`

**Comment by sharkfin009** [comment]
Thanks Rijk! 
Makes sense now, for some reason I thought that the fact that images was an array meant an asterisk was neccesary. I get it now , the array level effectively dissapears. Thats great.
Btw am going to start a big project at work using Directus soon, looking forward.

**Comment by sharkfin009** [comment]
closing
