### ISSUE TITLE
Non deterministic behavior editing and running flows/operations when using multiple directus instances

### ISSUE THREAD

**Issue by MaLub** [directus/directus#19320]
### Describe the Bug

We deploy Directus in a Kubernetes cluster and use multiple pods.
If you define flows and operations only the pod that is randomly called by the load balancer saves the changed operation in the DB (`directus_operations`).

The `FlowManager` then updates itself and reads in the changed operation. (This happens here: 
https://github.com/directus/directus/blob/dd00703c83fb622b711946886b83a5f39174fbfd/api/src/flows.ts#L92-L95)

The state variable is then updated with the new operations (https://github.com/directus/directus/blob/dd00703c83fb622b711946886b83a5f39174fbfd/api/src/flows.ts#L59).

However, all other pods do not get this `event` and thus do not update their operations.

If the flow is now executed, it results into a non-deterministic behavior (depending on which pod the load balancer sends the request to).

As a workaround, we start the Directtus instances after making changes to the flows.

Maybe it's a solution, to put the operations in the cache, then you could perhaps define a corresponding TTL or something similar here.

### To Reproduce

- run two directus instances in a kubernetes cluster
- define a simple Workflow with a simple operation (f.ex. log)
- run it a few times to make sure the workflow is executed on both pods

Then
-> change the Workflow and it's operation (f.ex. change log-message)
- save
- and run it a few times .
- you should see different log messages depending on which pods is called by the kubernetes load balancer

### Directus Version

v10.x

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
Make sure to use and configure Redis when running Directus in multiple containers. That's how it keeps things in sync
