### ISSUE TITLE
M2A is referenced as "Many-to-Any (O2M)"

### ISSUE THREAD

**Issue by cyberyanka** [directus/directus#19339]
### Page

https://docs.directus.io/app/data-model/fields/relational.html#tree-view

### Describe the inaccuracy

Many-to-Any relationships are referenced in a confusing way, direct quote:

> The Tree View interface is only available on self-referencing (recursive) relationships. See [Many-to-Any (**_O2M_**) Relationships](https://docs.directus.io/app/data-model/relationships.html#many-to-any-m2a).

Spelt "Many-to-Any"
BUT
Abbriviated to "O2M" ("One-to-Many")
AND
Linking to M2A

I believe it should rather be:

> The Tree View interface is only available on self-referencing (recursive) relationships. See Many-to-Any (**_M2A_**) Relationships

**Comment by rijkvanzanten** [comment]
Good catch! Thanks for the heads up ~
