### ISSUE TITLE
No automatic reconnection after connection error

### ISSUE THREAD

**Issue by stx-chris** [directus/directus#19336]
### Describe the Bug

For quite some time we've been observing the problem that our web apps won't reconnect to Directus after a connection issue. If this happens, we have to open Directus in the browser and hit refresh in our apps to make them work again.

### To Reproduce

It can be simulated by switching WiFi locally, for instance. It occurs in managed Kubernetes pods or Cloud Run as well, but it's harder to provoke.

1. Start Directus instance locally on port 8055
2. Run node.js app locally that connects to Directus via 127.0.0.1:8055
3. Switch to another WiFi so that the local IP changes
4. Refresh the app, now the connection to Directus will be dropped. Multiple refreshes won't change that. But Directus will output a `Connection terminated unexpectedly` error.
5. Open Directus on http://127.0.0.1:8055 in a browser tab. Don't login, just load the landing page.
6. Switch to the app again and hit refresh, it will magically connect to Directus again.

It is clear that connections drop if network conditions change. But I don't understand why the app cannot connect the instance again on refresh and that this behaviour changes if I open the landing page of Directus. **Is something reset or re-initialized on open?**

Many thanks for any suggestions.

P.S. We are using Javascript SDK v10.3.5. But this issue has been observed for at least a year now.

The error shown in the console is:
```
[08:05:58.755] ERROR: select "ip_access" from "directus_roles" where "id" is null limit $1 - Connection terminated unexpectedly
    err: {
      "type": "Error",
      "message": "select \"ip_access\" from \"directus_roles\" where \"id\" is null limit $1 - Connection terminated unexpectedly",
      "stack":
          Error: select "ip_access" from "directus_roles" where "id" is null limit $1 - Connection terminated unexpectedly
              at Connection.<anonymous> (/Users/.../client.js:132:73)
              at Object.onceWrapper (node:events:627:28)
              at Connection.emit (node:events:513:28)
              at Socket.<anonymous> (/Users/...pg/lib/connection.js:63:12)
              at Socket.emit (node:events:513:28)
              at TCP.<anonymous> (node:net:313:12)
    }
```

see also the full screenshot
![image](https://github.com/directus/directus/assets/62717406/2d5d9925-2480-4887-b934-f76425a4f77c)

### Directus Version

v10.5.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
I am unable to reproduce this when switching from networks. And it really shouldnt considering you are accessing directus locally on `127.0.0.1` (or `localhost`) which both should be unaffected by almost any network change.

The connection terminated error looks like directus has issues connecting to your database after the network change. Is the database also on 127.0.0.1 and does it stay reachable during the network switch?
