### ISSUE TITLE
dynamic thumbnails 404 error

### ISSUE THREAD

**Issue by moritzw1** [directus/directus#1933]
## Version Info
  - Directus version and branch: 6.4.3
  - PHP version: 7.0
  - MySQL version: 5.5
  - Web server: Apache 
  - OS name and version: CentOS 7

## Expected Behavior
Thumbnail should be created in the specified resolution

## Actual Behavior
There is an error message saying:
**Not Found**
The requested URL /subpath/thumbnail/300/200/00000000006.jpg was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

## Steps to Reproduce
 1. Place directus installation inside a subfolder/subpath (http://domain.com/subpath/)
 2. Try to create a thumbnail from this subpath

Moving the directus installation to the main folder of the domain fixes this issue

**Comment by rijkvanzanten** [comment]
Hey @moritzw1! Thanks for addressing this. Could you please check (and confirm) if the keys `root_url` and `root_thumb_url` are pointing to the right paths in `/api/configuration.php`?

```php
// This is the url where all the media will be pointing to
// here all assets will be (yourdomain)/storage/uploads
// same with thumbnails (yourdomain)/storage/uploads/thumbs
'root_url' => '/<subpath>/storage/uploads',
'root_thumb_url' => '/<subpath>/storage/uploads/thumbs',
```
_`<subpath>` should be your actual subpath_

**Comment by moritzw1** [comment]
Hi @rijkvanzanten 

yes, I can confirm this. The subpath is correct.

**Comment by rijkvanzanten** [comment]
Hmm... Have you any other information we could use to reproduce this error? I haven't been able to reproduce this error on my own install. The only issue I came across was the paths in `configuration` and `config` not matching. 

Just to make sure, did you update the `DIRECTUS_PATH` key in `api/config.php` as well?

**Comment by moritzw1** [comment]
Yes, I can confirm the path in the config.php aswell. I can recreate the issue with a local MAMP installation putting the Directus files in htdocs -> subfolder breaks the thumbnail functionality

**Comment by moritzw1** [comment]
Hi @rijkvanzanten 
with the latest update 6.4.4 this error is gone and the thumbnails working flawlessly.

Thanks for your help anyway 👍
