### ISSUE TITLE
M2A Manual Sort Broken in 10.5.2

### ISSUE THREAD

**Issue by dnndev** [directus/directus#19334]
### Describe the Bug

I'm using Directus.cloud. It just switched from 10.4.3 to 10.5.2. Unfortunately, the M2A Builder control no longer shows the grab handle in each item allowing for manual sorting as shown here:
<img width="421" alt="image" src="https://github.com/directus/directus/assets/1757808/0a3920ec-34c4-4a83-be06-0c1c121b8a32">

### To Reproduce

Follow the Directus Guide on Creating Reusable Components -- specifically the section: https://docs.directus.io/guides/headless-cms/reusable-components.html#configure-a-many-to-any-m2a-relationship-inside-the-pages-collection

This is the guide I was working through on 10.4.3 where the drag handles appear and function. Now on 10.5.2 I see this (with sample text):

<img width="784" alt="image" src="https://github.com/directus/directus/assets/1757808/3873141f-27f2-4e7b-ad38-0c3486f8fe58">

### Directus Version

v10.5.2

### Hosting Strategy

Directus Cloud

**Comment by paescuj** [comment]
You need to define a `Sort` field when creating the Builder (M2A) field, available when clicking on "Continue in Advanced Field Creation Mode":
<img width="500" src="https://github.com/directus/directus/assets/5363448/47116ad6-8f2f-41cb-80b1-07593f8956ef">

I think we should mention this in the guide.
