### ISSUE TITLE
Cannot give default value in Many to One relationship field except word "e"

### ISSUE THREAD

**Issue by jagyas** [directus/directus#19345]
### Describe the Bug

I cannot give default value in a many to one relationship except word "e". Please find below screenshot:

![image](https://github.com/directus/directus/assets/6293136/3ebef8d8-c457-4cbf-9e96-1361bdd0b304)

### To Reproduce

Create a many to one field. Go to advanced mode and try to give default value.

### Directus Version

v10.5.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
I am unable to reproduce this 🤔 There must be more to it, please provide more information to make it reproducable on a fresh instance.

Happy to reopen the issue once more details are available.
