### ISSUE TITLE
Subscribe with realtime and query results in unhandled exception on server

### ISSUE THREAD

**Issue by clck-dr** [directus/directus#19342]
### Describe the Bug

I want to use Real-Time Directus. I want to specify query to only get fields of interest.
I used createDirectus with schema and query as described in documentation. 

If I add `{actualContent: ["asset"]}` or `{actualContent: ["*"]}` to fields I get an error on server an no websocket events anymore. If I use `actualContent.*` no error occurs.

The filter has also no effect. I double-checked CLIENT_NAME to has a valid string.

### To Reproduce

```
export interface Schema {
  devices: Device[];
  content: Content[];
}

export interface Device {
  id: number;
  hostname: string;
  actualContent: number | Content;
}

export interface Content {
  id: number;
  asset: string;
}
...
socket.current = createDirectus<Schema>(DIRECTUS_SOCKET_URL)
  .with(
    realtime({
      authMode: "handshake",
      heartbeat: true,
      reconnect: { retries: 10, delay: 1000 },
    })
  )
  .with(staticToken(DIRECTUS_TOKEN));

await socket.current.connect();

const { subscription, unsubscribe } = await socket.current.subscribe(
  "devices",
  {
    query: { fields: ["hostname", {actualContent: ["asset"]}] },
    filter: { hostname: { _eq: CLIENT_NAME } },
  }
);

  for await (const item of subscription) {
    const { type, event, data } = item;
    console.log(`${type}, ${event}`, data);
  }
```
results in:
`
ERROR: WebSocket unhandled exception {"type":"subscribe","error":{}}
`

### Directus Version

v10.5.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
> If I add {actualContent: ["asset"]} or {actualContent: ["*"]} to fields I get an error on server an no websocket events anymore. If I use actualContent.* no error occurs.

That is correct the API/WS is erroring on the incorrect use of fields there.

**Comment by clck-dr** [comment]
> > If I add {actualContent: ["asset"]} or {actualContent: ["_"]} to fields I get an error on server an no websocket events anymore. If I use actualContent._ no error occurs.
> 
> That is correct the API/WS is erroring on the incorrect use of fields there.

Can you explain to me how to implement the query correctly? I followed the documentation:
https://docs.directus.io/guides/sdk/getting-started.html#read-nested-fields

Why isn't the filter being taken into account?

**Comment by br41nslug** [comment]
The nested object `fields` structure is only applicable to REST endpoints using the SDK. The websocket format is unchanged https://docs.directus.io/guides/real-time/getting-started/websockets.html

**Comment by arladmin** [comment]
@br41nslug The `filter` is not working for me either, in the sense that the subscription is receiving events for items out of the scope defined by the filter.

My code:
```
    connection.send(
        JSON.stringify({
            type: 'subscribe',
            collection,
            query: {         
                filter: {
                    id: {
                        _eq: "680aed0b-457d-47b1-b6ed-dcbc63aebd1e"
                    }
                },            
                fields: ['*'] 
            },
            uid: collection
        })
    );
```

Init response:
```
{
    "event": "onmessage",
    "data": {
        "type": "subscription",
        "event": "init",
        "data": [
            {
                "id": "680aed0b-457d-47b1-b6ed-dcbc63aebd1e",
                "user": "4d43e55e-8e62-4959-a953-b1e178952b25",
                "status": "active",
                "date_closed": null,
                "date_created": "2023-09-15T15:47:44.693Z",
                "date_updated": null
            }
        ],
        "uid": "sessions"
    }
}
```

Subsequent message upon activity:
```
{
    "event": "onmessage",
    "data": {
        "type": "subscription",
        "event": "delete",
        "data": [
            "fd92b2ad-9112-4d69-b84f-52717b810643"
        ],
        "uid": "sessions"
    }
}
```

As seen in the above example, the subscription has received an event for an item, for which it's not subscribed!
