### ISSUE TITLE
Permissions not working properly after updating to 10.1.1

### ISSUE THREAD

**Issue by idmansourali** [directus/directus#19340]
### Describe the Bug

After updating from 10.0.0 to 10.1.1, I noticed that permissions are not working properly for some collections.

I didn't want to update to the latest version because I had a bad experience updating to 10.3 due to the permissions issue with the CURRENT_USER variable.

I don't know if this issue is related to the upgrades and downgrades I've done.

### To Reproduce

1. Create a new collection
2. Grant full permission to a role
3. Log in using a user in this role
4. Try to modify or add an element of the created collection
5. Note that the form is disabled and the Add button is disabled too

-----------

![permissions1](https://github.com/directus/directus/assets/53354635/d46f104a-0482-40b7-b3c9-5d7191302e23)

-----------

![permissions2](https://github.com/directus/directus/assets/53354635/33e96627-d35f-47e2-a901-9db456311ee9)

-----------

![permissions3](https://github.com/directus/directus/assets/53354635/c9597e21-7dd7-46e3-a87e-bc37b408b0af)

### Directus Version

v10.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Pachat** [comment]
There are many issues related: #19327 #18898 #19043 #19249
For my part, I'm stuck on v10.2.1 which runs correctly for all my fairly complex permissions.

**Comment by falmanna** [comment]
> There are many issues related: #19327 #18898 #19043 #19249 For my part, I'm stuck on v10.2.1 which runs correctly for all my fairly complex permissions.

I t think my issue falls under the same category as well https://github.com/directus/directus/issues/19337
