### ISSUE TITLE
Installation Issues on Nginx

### ISSUE THREAD

**Issue by derekshull** [directus/directus#1934]
## Version Info
  - Directus version and branch: 6.4.3
  - PHP version: 7
  - MySQL version: 5.7
  - Web server: nginx
  - OS name and version: Ubuntu 14.04

## Expected Behavior
Expected MySQL strict mode to show as disabled, mod_rewrite enabled to show as Yes, Logs Directory Writable to show as Yes, Media Directory Writable to show as Yes, Config File Writable to show as Yes.

## Actual Behavior
I noticed that mysql strict mode was enabled, so I went into `/etc/mysql/mysql.conf.d/mysqld.cnf` and entered the line `sql_mod=""`.  It still shows that mysql strict mode is enabled.

I noticed that mod_rewrite was disabled.  I'm using nginx so I made the server block file have the following:
```
location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ /index.php?$args;
}
```
I changed `try_files $uri $uri/ =404;` to `try_files $uri $uri/ /index.php?$args;` after seeing somewhere online that it should work.  It still shows that mod_rewrite is not enabled.

For Logs Directory Writable, Media Directory Writable, and Config File Writable I used `chmod 775` on the file and directories.  It's still showing though that it's not writable.

## Steps to Reproduce
1. download the zip file and unzip
2. create the server block for nginx
```

server {
        listen 80;
        listen [::]:80;

        root /var/www/directus;
        index index.html index.php;

        server_name subdomain.topdomain.com;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
               include snippets/fastcgi-php.conf;

               # With php7.0-cgi alone:
               #fastcgi_pass 127.0.0.1:9000;
               # With php7.0-fpm:
               fastcgi_pass unix:/run/php/php7.0-fpm.sock;
        }
}
```
3. Set the settings in digital ocean to create a cname for the subdomain
4. Go to the domain and go through the installation

**Comment by WellingGuzman** [comment]
This is a expected result.

You would have to use our nginx or follow our nginx configuration example here: [directus nginx config](https://github.com/directus/directus-vagrant/blob/master/config/nginx/default)

**Comment by tiptap** [comment]
I'm still experiencing this problem even after using the directus nginx config.

I get a 404 on the /api/1.1/auth/login

I was wondering if its because directus was installed in /directus/ ?
