### ISSUE TITLE
SDK 11: It's impossible to include credentials with AuthenticationClient methods

### ISSUE THREAD

**Issue by Jon1VK** [directus/directus#19344]
### Describe the Bug

When calling for example `refresh()`-method of `AuthenticationClient` module, the request does not include cookies in the headers and there is no way to configure AuthenticationClient methods to include cookies in the headers of the requests.

### To Reproduce

Try calling refresh() method with JS SDK 11 and check out the sent headers. There is no cookies sent with the request.

### Directus Version

v10.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by layanto** [comment]
Please release this fix to npm @directus/sdk
