### ISSUE TITLE
Permissions error : Mutation create_<collection>_input not exist for non-admin

### ISSUE THREAD

**Issue by CMonjo** [directus/directus#19348]
### Describe the Bug

Hi!

I have a permission problem for non-admin users and mutations.

I'm trying to run this mutation
> /!\ Program is a collection that contains relations

```
mutation CreateProgram(
  $data: create_Program_input!
) {
    create_Program_item(data: $data) {
        id
    }
}
```

This is the error I get when the user is not an administrator: 
```
{
    "errors": [
        {
            "message": "GraphQL validation error.",
            "extensions": {
                "code": "GRAPHQL_VALIDATION_EXCEPTION",
                "graphqlErrors": [
                    {
                        "message": "Unknown type \"create_Program_input\".",
                        "locations": [
                            {
                                "line": 2,
                                "column": 10
                            }
                        ]
                    },
                ]
            }
        }
    ]
}
```
And this mutation will work if the user is admin.

Even having read the documentation, I don't understand what permissions would allow me to correct this problem.

I think the problem is with the Program collection relationships, since I'm able to execute other create_<collection>_input mutations. The problem being, I've enabled all permissions for related collections.

I've also read the only issue I managed to find that refers to my problem https://github.com/directus/directus/issues/5624 (but the version of directus is old).

Many thanks for your help!

### To Reproduce

To reproduce the problem, just copy my mutation. But I doubt that this problem is easily reproducible. It's all the collections in my environment that make the problem happen.

### Directus Version

v10.1.1

### Hosting Strategy

Self-Hosted (Docker Image)
```[tasklist]
### Tasks
```

**Comment by rijkvanzanten** [comment]
Please upgrade to the latest version, there's a chance this issue has already been resolved since! If this problem can be reproduced in the latest version, we'll reopen and keep investigating 👍🏻
