### ISSUE TITLE
Rating stars not displayed on cards view (content)

### ISSUE THREAD

**Issue by patric-eberle** [directus/directus#19359]
### Describe the Bug

I have collection items that have a rating field. If I try to display this in the `cards` view in the `Content` section, the rating is not visible, because it is visually pushed out of view by the `.vertical-aligner` element.

To fix this for the moment, I used the following CSS overwrite:
```
.render-template .vertical-aligner:not(:last-child) { /* Fixes a line break bug when using ratings on cards. */
    display: none !important;
}
```

<img width="461" alt="grafik" src="https://github.com/directus/directus/assets/10571945/5f67bd08-792c-40b5-a8ba-a7a6c6106d88">

### To Reproduce

- Create a collection, that uses a field of type `Slider`.
- Set the fields `Display` type to `Rating`.
- Move to `Content` view, and display the items of the collection as `Cards`.
- Select a text field for the `Title` in `Layout Options` for the `Cards` view.
- Select the `Slider` field for the `Subtitle`.
- Result: The rating is not visible.

### Directus Version

v10.5.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by DanielBiegler** [comment]
Good find, thank you for filing this issue! :)

While fixing this, I found theres also a small cutoff issue when you use the "simple" rating variant see here:

![image](https://github.com/directus/directus/assets/14810858/8ed019e3-76d9-4db3-85c9-fab3b732be38)

Let's fix this in one swoop! :+1:
