### ISSUE TITLE
Unable to view Files as thumbnails when creating item within Directus

### ISSUE THREAD

**Issue by philleepflorence** [directus/directus#1935]
## Version Info
  - Directus version and branch: 6.4.3
  - PHP version: 7
  - MySQL version: 5.7
  - Web server: Apache
  - OS name and version: CentOS 7

## Expected Behavior
When selecting Choose Existing in Single or Multiple Files Interface, one would see thumbnails of files to select.

![screen shot 2017-11-01 at 5 40 59 pm](https://user-images.githubusercontent.com/2633551/32299503-3f631d02-bf2c-11e7-9381-20c9ec53c664.png)

## Actual Behavior
When selecting Choose Existing in Single or Multiple Files Interface, one sees rows of files, with no image preview.

![screen shot 2017-11-01 at 5 41 12 pm](https://user-images.githubusercontent.com/2633551/32299522-5146299c-bf2c-11e7-8e4e-9c8f90896b57.png)

## Steps to Reproduce
 1. Add a single or multiple file input to any table.
 2. Create a new item and try to add image

## Schema Dump, Logs, or Screenshots
`Table: directus_tables`
![screen shot 2017-11-01 at 5 46 41 pm](https://user-images.githubusercontent.com/2633551/32299654-ba9661fa-bf2c-11e7-9424-737035712388.png)

`Table: directus_preferences`
![screen shot 2017-11-01 at 5 48 18 pm](https://user-images.githubusercontent.com/2633551/32299688-e17a7784-bf2c-11e7-8c27-e5775d2c051e.png)

`Table: directus_columns`
![screen shot 2017-11-01 at 5 50 18 pm](https://user-images.githubusercontent.com/2633551/32299771-2d1bdfd4-bf2d-11e7-83ee-eb44cfd5e884.png)

**Comment by WellingGuzman** [comment]
Hey @philleepflorence, thanks for reporting this. We will get it done, as soon as possible.

note: This has been reported before, I just can't find the other ticket.

**Comment by philleepflorence** [comment]
Thank you! Will await updates...

**Comment by supercranky** [comment]
Any update on this? I'm also in need of image thumbnails in the "Choose Existing" view!

**Comment by WellingGuzman** [comment]
No update @supercranky, any time this week we will bring back the missing thumbnail to the listing table.

**Comment by supercranky** [comment]
Fastastic! Awesome work btw!!

**Comment by rijkvanzanten** [comment]
With the core developer team working full time on the next major version (7.0), non-system critical issues like this one unfortunately get put on the back burner.. 

If anyone feels inclined to take a swing at this issue before we get to it: as always, a PR is very welcome 😄 

The overlay gets openend here: https://github.com/directus/directus/blob/master/app/core/interfaces/single_file/interface.js#L67-L110

The overlay itself is managed by:
https://github.com/directus/directus/blob/master/app/modules/tables/views/OverlayEditView.js

**Comment by philleepflorence** [comment]
I was trying to tackle this, but I cannot find `/app/core/single_file/interface.js`, I can only see `/app/core/single_file/input.handlebars` in that folder. 
I am using Build 6.4.8.
Please advise.

**Comment by rijkvanzanten** [comment]
@philleepflorence The build branch has all those `.js` files bundled into 1 main `directus.min.js`. You have to use the un-bundled version straight from the `master` / `develop` branch (which uses `require-js` to debug this

**Comment by philleepflorence** [comment]
Ah okay, thanks!
I will pull the develop branch later and go through.

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/12)
