### ISSUE TITLE
File preview is missing on edit clickout for file, image, m2o and o2m interfaces

### ISSUE THREAD

**Issue by martijn-dev** [directus/directus#19366]
### Describe the Bug

Whenever I click the edit button on a `file` or `image` field it will open an edit side overlay wherein I cannot see the actual file.
The edit button:
<img width="613" alt="image" src="https://github.com/directus/directus/assets/73393707/c67d45bd-faaf-464d-93f2-78682eb36561">
<img width="620" alt="image" src="https://github.com/directus/directus/assets/73393707/fe3956ea-252f-4af7-9f96-3137aa82b2f5">

The overlay that is shown:
<img width="766" alt="image" src="https://github.com/directus/directus/assets/73393707/52029e25-3df4-45fa-829f-58d630d7f955">

This issue also occuces for a regular `m2o` or `o2m` relation on the `directus_files` collection.

This do works for the `files` interface (m2m):
<img width="636" alt="image" src="https://github.com/directus/directus/assets/73393707/6b168d81-d10e-4b66-8819-7a242c1147af">

### To Reproduce

1. Create a test collection
2. Add a file field (or an image field) (or a regular m2o or o2m on `directus_files`)
3. Create an item in the test collection and add a file to the field
4. Save
5.  Click on the edit button
6. An overlay without preview is shown

### Directus Version

v10.5.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by martijn-dev** [comment]
Could this be related to this old bug? https://github.com/directus/directus/issues/19080

**Comment by DanielBiegler** [comment]
So I identified the responsible code, it's in the `drawer-item` when deciding whether to render the `file-preview` or not, see here:

https://github.com/directus/directus/blob/5114169b3873b7a354a137fd777952c5807d0bcb/app/src/views/private/components/drawer-item.vue#L23-L31

Both `file` and `junctionField` are `null` which prevents rendering `file-preview` mh.

**Comment by DanielBiegler** [comment]
```vue
		<drawer-item
			v-model:active="editModalActive"
			:collection="relationInfo.relatedCollection.collection"
			:primary-key="currentPrimaryKey"
			:edits="edits"
			:circular-field="relationInfo.relation.meta?.one_field ?? undefined"
			:disabled="!updateAllowed || disabled"
			@input="onDrawerItemInput"
		/>
```

`junctionField` prop isnt set in `select-dropdown-m2o`, since there is no junction here.

This leads to: 

```ts
	const relatedCollection = computed<string | null>(() => {
		if (!props.junctionField) return null;
```


```ts
function useFile() {
	const isDirectusFiles = computed(() => {
		console.log("isDirectusFiles => relatedCollection ==", relatedCollection.value);
		return relatedCollection.value === 'directus_files';
	});
```

this leads to:

```ts
	const isDirectusFiles = computed(() => {
		console.log("isDirectusFiles => relatedCollection ==", relatedCollection.value);
		return relatedCollection.value === 'directus_files';
	});```

`isDirectusFiles` becomes false

This leads to:

```ts
	const file = computed(() => {
		if (isDirectusFiles.value === false || !initialValues.value || !props.junctionField) return null;
```

so that `file` becomes `null`

Now both `junctionField` and `file` are `null` and we cant render the `file-preview`
