### ISSUE TITLE
Slug not saved correctly on creation

### ISSUE THREAD

**Issue by BennerGe** [directus/directus#1936]
## Version Info
  - Directus version and branch: Develop branch

## Actual Behavior
If the slug is changed manually on creation of a table entry, it will remain on the sluggified title, not the string, which was entered. The slug must be updated again, to save it correctly. 

## Steps to Reproduce
 1. Create `title` and `slug` field, set mirrored field to `title`
 2. Create new table entry, set `title` to "Title" and `slug` to "Title test"
 3. Save
 4. `slug` remains "title"

**Comment by rijkvanzanten** [comment]
This has been fixed in ac4ea4db97e5138aa72afaec176be9357c07e0e6 on the develop branch and will be released soon!
