### ISSUE TITLE
Request failed when change field sorting

### ISSUE THREAD

**Issue by dergachevm-evr** [directus/directus#19368]
### Describe the Bug

When changing sorting of fields in page model, after 44s got error

"<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.23.2</center>\r\n</body>\r\n</html>\r\n"

Also! Cloud version works extremely slow!

### To Reproduce

Change sorting of fields in model
https://\*\*\*.directus.app/fields/\*\*\*
Request error
![chrome_bPhDS8uoqR](https://github.com/directus/directus/assets/126075884/293d0c7f-0678-4430-b95c-ff5458c9be35)

Payload
![chrome_D9gWNs5M6i](https://github.com/directus/directus/assets/126075884/c67e014d-4554-445a-8e66-c3fb9663652b)

### Directus Version

v10.5.2

### Hosting Strategy

Directus Cloud

**Comment by rijkvanzanten** [comment]
Hi! Could you please reach out to support@directus.io? This seems to be a specific issue with your cloud instance rather than a bug in Directus itself we can solve here in the core codebase. Thanks!
