### ISSUE TITLE
Typing error with `readItems`

### ISSUE THREAD

**Issue by ganlhi** [directus/directus#19375]
### Describe the Bug

Using `readItems`, I get a TypeScript error saying it expects 0 argument. 

### To Reproduce

When I'm writing the following code:
```
  const client = createDirectus<{
    context: ContextResponse[];
  }>('https://example.com')
    .with(rest())
    .with(staticToken('XXXXXXXXXXXXXXXXXXX'));
  
  const contexts = await client.request(readItems('context'));
```

I have a TypeScript error on the argument of `readItems`: 
> TS2554: Expected 0 arguments, but got 1.

### Directus Version

v10.5.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Make sure to set [`moduleResolution`](https://www.typescriptlang.org/tsconfig#moduleResolution) in your tsconfig file to `node16` or `nodenext`.

**Comment by ganlhi** [comment]
I tried, but it doesn't work. I also tried to update TypeScript to the latest version. 
Here is my tsconfig:
``` 
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node16",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "baseUrl": ".",
    "paths": {
      "@/*": [
        "src/*"
      ],
      "@styles/*": [
        "styles/*"
      ],
      "@testdata/*": [
        "testdata/*"
      ]
    }
  },
  "include": [
    "next-env.d.ts",
    "./jest-setup.ts",
    "**/*.ts",
    "**/*.tsx"
  ],
  "exclude": [
    "node_modules",
  ]
}
```

**Comment by paescuj** [comment]
> I tried, but it doesn't work. I also tried to update TypeScript to the latest version. Here is my tsconfig:
> 
> ```
> {
>   "compilerOptions": {
>     "target": "es5",
>     "lib": [
>       "dom",
>       "dom.iterable",
>       "esnext"
>     ],
>     "allowJs": true,
>     "skipLibCheck": true,
>     "strict": true,
>     "forceConsistentCasingInFileNames": true,
>     "noEmit": true,
>     "esModuleInterop": true,
>     "module": "esnext",
>     "moduleResolution": "node16",
>     "resolveJsonModule": true,
>     "isolatedModules": true,
>     "jsx": "preserve",
>     "incremental": true,
>     "baseUrl": ".",
>     "paths": {
>       "@/*": [
>         "src/*"
>       ],
>       "@styles/*": [
>         "styles/*"
>       ],
>       "@testdata/*": [
>         "testdata/*"
>       ]
>     }
>   },
>   "include": [
>     "next-env.d.ts",
>     "./jest-setup.ts",
>     "**/*.ts",
>     "**/*.tsx"
>   ],
>   "exclude": [
>     "node_modules",
>   ]
> }
> ```

Cannot reproduce on my end. Please ensure you're importing `readItems` from the correct source, that is:
```ts
import { readItems, <other imports> } from "@directus/sdk";
// or 
import { readItems, <other imports> } from "@directus/sdk/rest";
```

Probably unrelated but you might want to adjust your tsconfig to get rid of the following warning:
```
Top-level 'await' expressions are only allowed when the 'module' option is set to 'es2022', 'esnext', 'system', 'node16', or 'nodenext', and the 'target' option is set to 'es2017' or higher.ts(1378)
```

**Comment by mikkeschiren** [comment]
Getting the same issue.

Here is my tsconfig:
```

{
  "compilerOptions": {
    "target": "es2017",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "baseUrl": ".",
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "incremental": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "nodenext",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "typeRoots": [
      "./lib"
    ],
    "plugins": [
      {
        "name": "next"
      }
    ]
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    "next.config.js",
    ".next/types/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}

```

And my imports:

```
import { readItems } from "@directus/sdk/rest";
...
```

And my lib for createDirectus:

```
import { createDirectus } from "@directus/sdk";
import { rest } from "@directus/sdk/rest";

import type { MyCollection } from "./my-collection";

const directus = createDirectus<MyCollection>(
  process.env.DIRECTUS_URL,
).with(rest());

export default directus;
```

**Comment by mikkeschiren** [comment]
Ok - it seems that for me it was related to a vsconfig - deleted that, and warning went away...

**Comment by mattbisme** [comment]
> Ok - it seems that for me it was related to a vsconfig - deleted that, and warning went away...

What fixed this for you? I'm having the same issue.

**Comment by mikkeschiren** [comment]
My warning was inside vscode - not in the terminal, so I deleted the .vscode folder. After that, all green (well, not all things, but this :D )

**Comment by mattbisme** [comment]
@mikkeschiren I was hoping that your fix might have been a vscode config change that I could replicate in Nova. Alas, I can't figure it out. However, my compiler is working, making the error mostly cosmetic.

**Comment by mtrnik** [comment]
I'm late to the party, but just for future reference, I had exactly this issue in the JetBrains Webstorm and fixed it by switching Typescript to version 5.

**Comment by br41nslug** [comment]
Correct TypeScript 5.0+ is required for the SDK 😄
