### ISSUE TITLE
Privileges API only available for admin user group

### ISSUE THREAD

**Issue by BennerGe** [directus/directus#1937]
## Version Info
  - Directus version and branch: Develop branch

## Actual Behavior
The privileges endpoint can only be accessed as admin, even when the privileges are set to `read_all` for the table `direcuts_privileges`.
This is due to the following code:
https://github.com/directus/directus/blob/1db9ed459b693632ea0f8012750c498c98d5c556/api/routes/A1/Privileges.php#L26-L28

Is this behaviour desired? If yes, how can an application check, if an user is allowed to execute an action? This would be nice, e.g. to hide an button if the user is not allowed to add an entry to a table.

**Comment by rijkvanzanten** [comment]
@WellingGuzman Is this behavior intentional?

**Comment by WellingGuzman** [comment]
This is a intentional behavior, to avoid users to see other users privileges.

Authenticated user can see their own privileges here: `/auth/permissions`.

**Comment by rijkvanzanten** [comment]
@WellingGuzman Is this documented somewhere?

**Comment by WellingGuzman** [comment]
No that I'm aware of.

**Comment by benhaynes** [comment]
Needs documentation. @WellingGuzman

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/api-docs/commit/015da7b3bebae89c387d3a3d3bc4a748092d147a
