### ISSUE TITLE
Not showing error message when tried remove item on collection page

### ISSUE THREAD

**Issue by vadikk006** [directus/directus#19376]
### Describe the Bug

Error message not showing on collection page if delete any item and was error.

### To Reproduce

add custom hook with filter by any collection and generate error if was called delete event
```
export default defineHook(({filter}, context: HookExtensionContext) => {
    filter('project.items.delete', () => {
        const DeleteError = createError('DELETE_PROJECT_ERROR', 'fail delete', 400);
        throw new DeleteError();
    });
});
```
go collection page, and tried remove collection item on collection page(not page edit item).

![image](https://github.com/directus/directus/assets/9569061/ea649a9e-16e1-461a-aebf-d0530e855246)
after click delete
![image](https://github.com/directus/directus/assets/9569061/e73ffde3-74f0-4745-9944-24dd2ed9714a)
after click cancel 
![image](https://github.com/directus/directus/assets/9569061/981d1241-bf29-42c6-8207-c66e4764157a)

how to fix that: 
file: app/src/modules/content/routes/collection.vue
function batchDelete add in finally : confirmDelete.value = false;

result:
```
try {
	await api.delete(`/items/${props.collection}`, {
		data: batchPrimaryKeys,
	});

	selection.value = [];
	await refresh();
} catch (err: any) {
	error.value = err;
} finally {
	 confirmDelete.value = false;
	deleting.value = false;
}
```

### Directus Version

v12.1.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by DanielBiegler** [comment]
Reproduced it! Can confirm this occurs exactly as described. I'm on it. :rocket:
