### ISSUE TITLE
Schema CLI displays colors which may not be viewable

### ISSUE THREAD

**Issue by jaads** [directus/directus#19386]
### Describe the Bug

When applying a snapshot via the schema cli, some phrases are in the same color as my terminals background color and hence not viewable:

<img width="358" alt="Screenshot 2023-08-10 at 11 08 37" src="https://github.com/directus/directus/assets/34009329/8b8cc170-0722-4746-bc7f-4b0d78e8b9c1">

by selecting the messages, I can see that the text is there, it's just the same color as my terminal. It would be nice to be able to see the content, regardless of the terminal theme.
### To Reproduce

apply a schema using the CLI by having a terminal with dark background 

### Directus Version

10.5.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rockingrohit9639** [comment]
@rijkvanzanten Is this issue still open ?

**Comment by rijkvanzanten** [comment]
![CleanShot 2023-10-04 at 15 16 58@2x](https://github.com/directus/directus/assets/9141017/3f291c5c-44e2-4208-be6d-6a70d0197384)

Yes!

**Comment by rockingrohit9639** [comment]
> ![CleanShot 2023-10-04 at 15 16 58@2x](https://user-images.githubusercontent.com/9141017/272686128-3f291c5c-44e2-4208-be6d-6a70d0197384.png)
> 
> Yes!

OMG!
Can you assign me? I want to work on this.

**Comment by DanielBiegler** [comment]
> I want to work on this.

@rockingrohit9639  Feel free to make a fork, implement your changes and open a pull request. You can find step by step instructions on how to get up and running in our docs: https://docs.directus.io/contributing/running-locally.html

Good luck & have fun! :smile:

**Comment by nassan** [comment]
@rijkvanzanten Could I be made the assignee on this. I have a quick PR hopefully.

**Comment by paescuj** [comment]
> @rijkvanzanten Could I be made the assignee on this. I have a quick PR hopefully.

PR's are welcome, feel free to take this up 👍
