### ISSUE TITLE
Colllection not removed if has group, when apply schema

### ISSUE THREAD

**Issue by vadikk006** [directus/directus#19385]
### Describe the Bug

if collection was removed localy and when  generate schema. Collection not removed on server

### To Reproduce

1. Create folder in Directus Data model
2. Create collection in this folder.
3. generate schema
4. apply schema on server or another pc 
5. remove collection 
6. generate schema again
7. apply new schema on server or another pc 

### **result**: 
collection not removed 
### **reason**:  
api/src/utils/apply-diff.ts ->  deleteCollections has condition `return collectionDiff.kind === DiffKind.DELETE && collectionDiff.lhs?.meta?.group === null;`

### **solution**
remove collectionDiff.lhs?.meta?.group === null in condition

### Directus Version

v12.1.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by DanielBiegler** [comment]
Hi there! :) So I applied a schema, which worked.

```[14:38:40.859] INFO: Snapshot applied successfully```

![image](https://github.com/directus/directus/assets/14810858/f8521b09-01ce-4709-8398-9e307dad2f4c)

Now check the diff for removing the collection in the folder, like you mentioned:

```The following changes will be applied:

Collections:
  - Delete temp_todo_delete

Would you like to continue? Yes
[14:43:50.683] INFO: Snapshot applied successfully
```

Looks correct but now like you mention, it is indeed not deleted!

![image](https://github.com/directus/directus/assets/14810858/5ddf3142-3f51-4547-a62d-a3c4c6534912)

Very nice find, thank you for the concise writeup! <3 :rocket:
