### ISSUE TITLE
M2O Dropdown not working 'Visible status IDs'

### ISSUE THREAD

**Issue by dsivokhin** [directus/directus#1938]
## Version Info
  - Directus version and branch: develop

## Expected Behavior
Load items with status set in `Visible status IDs`
![default](https://user-images.githubusercontent.com/4669992/32368869-3ef97d76-c098-11e7-8429-a5884bb86865.png)

## Actual Behavior
When load items for `Dropdown` ajax path `/api/1.1/tables/[table-name]/rows?active=1,2,3&columns_visible=name%2Cid&limit=100`

 `GET` param `active` not filtering items.

If I try set `GET` param `status`  items is filtered e.g. `/api/1.1/tables/[table-name]/rows?status=1,2,3&columns_visible=name%2Cid&limit=100`

## Schema Dump, Logs, or Screenshots
![default](https://user-images.githubusercontent.com/4669992/32369289-b97ce2e4-c099-11e7-9485-63d860889f36.png)

**Comment by rijkvanzanten** [comment]
This has been fixed in a0cff5c58243ff4515cd59a97346731979cf5ed6 on the develop branch and will be released into master soon
