### ISSUE TITLE
Collection item dropdown text overflow

### ISSUE THREAD

**Issue by JHulsmanGit** [directus/directus#19393]
### Describe the Bug

Text overflow when its too long instead of expanding or truncating to look neat.

### To Reproduce

Create a Collection Item dropdown that is linked to a collection where you can write a lot of words and have it display that.

### Directus Version

v10.5.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by JHulsmanGit** [comment]
![image](https://github.com/directus/directus/assets/92354504/09e41378-b516-4113-8d70-3dcc00cea5f1)

**Comment by Nitwel** [comment]
What type of interface are you using. If you don't know where to find that information, just hover over the field in data model like shown on the image below: 
![grafik](https://github.com/directus/directus/assets/22577866/363e9ba6-cb42-4648-8cbe-d5f3ff64270a)
