### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by jvmejias** [directus/directus#1939]
This probably is an error on my end but I need help to debug it.
I have Directus (6.4.2) running fine in a site on server A, and we moved all to server B.
Now on server B, when I try to upload or choose an existent image I get the annoying 'Uncaught SyntaxError: Unexpected end of JSON input' error.
I can save changes in texts though.

I've seen #1410 where @podlebar had the same issue and it was a permissions error, but I have doublechecked this and I don't find any difference with server A where it was working.

If I upload an image, it uploads but just won't save to the table (I have a junction table for images).
Nothing writes in api/logs (it is 755)

I'm quite stucked

**Comment by benhaynes** [comment]
Hey @jvmejias – unfortunately we can't debug config issues here on GitHub. I'd say your best bet is to head over to our Slack and see if the community/developers can help: https://slack.getdirectus.com/
