### ISSUE TITLE
Add a search bar to the data model page

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#19396]
### Describe the Improvement

If you have a large data model, it would be very helpful to have a search bar like we do for interfaces so you can find the collection you're aiming to edit faster:

<img width="987" alt="CleanShot 2023-08-10 at 11 03 45@2x" src="https://github.com/directus/directus/assets/9141017/86190ec5-acb6-4b48-9f22-32404ccd3878">

![CleanShot 2023-08-10 at 11 02 25@2x](https://github.com/directus/directus/assets/9141017/02d43656-22b9-417b-adf9-b80302ac6173)

**Comment by Nitwel** [comment]
How would that work with fields that are nested? 🤔 
I would guess that we continue showing it's parents but let me know what you think.

**Comment by rijkvanzanten** [comment]
The way you have it in the PR is exactly what I'd expect it to do 👍🏻
