### ISSUE TITLE
Changes to data in left childpane for one-to-many lost + error when saving for fields rawgroup

### ISSUE THREAD

**Issue by bartvdbqld** [directus/directus#19401]
### Describe the Bug

When editing/creating a new data item that contains a One To Many relationship, data in the side pane of the child items is in certain cases lost when editing. As far as I can tell, the problem only occurs when editing fields that are in a RawGroup.  When editing field values for fields not in a group, there seems to be no problem. Editing field inside and outside of a rawgroup also triggers the problem. 

Additionally an error is thrown when saving the parent item (only in case when editing fields valies in rawgroup)

### To Reproduce

**Start from following setup:**

![image](https://github.com/directus/directus/assets/131148828/4944a61a-bc58-4841-bc54-25e9f9e8078c)

![image](https://github.com/directus/directus/assets/131148828/8f1e7ecd-5a1b-4375-b2d1-a9be7eb41971)

Where the Children field in the Parent data model is a One To Many to the Child data model

**Triggering the issues:**

1. Create new Parent item
2. Create new child item
3. Enter a value for field "Field Outside of Raw Group"
4. Close the side pane
5. Open the child item again to see the details and observe the prevously entered value is still there
6. Enter a value in the field "Field in Raw Group"
7. Close the side pane
8. Open the child item again to see the details and observe that the last entered value is **not there**
9. Clode the side pane
10. Save the parent item
11. **An error is thrown "[Forbidden] You don't have permission to access this."**

### Directus Version

v10.5.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by Nitwel** [comment]
Weirldy enough, this does not happen when you enter both values at the same time. 🤔
We will look into it as I was able to reproduce it.
![GIF 11 08 2023 10-46-03](https://github.com/directus/directus/assets/22577866/ca836a48-a7cf-4144-9fc9-32a09e87279c)
