### ISSUE TITLE
Translation alias not behaving properly

### ISSUE THREAD

**Issue by Vlasterx** [directus/directus#1940]
## Version Info
  - Directus version and branch: master branch (6.11.2017.)
  - PHP version: PHP 7.1.11-1+ubuntu16.04.1+deb.sury.org+1 (cli)
  - MySQL version: 5.7.20-0ubuntu0.16.04.1 - (Ubuntu)
  - Web server: (Ex. Apache, nginx or IIS?)  Apache/2.4.29 (Ubuntu)
  - OS name and version: Ubuntu server 16.04.3 LTS

## Expected Behavior
Based on [this tutorial](https://medium.com/directus/multilingual-content-setup-in-directus-i18n-4f243f72e554).

I have 3 tables in this setup:

| languages                   | articles_translation    | articles                 |
|-----------------------------|-------------------------|--------------------------|
| code [primary key, varchar] | id [primary key, int]   | id [primary key, int]    |
| code_short [varchar]        | language_code [varchar] | translation_id [translation alias]     |
| name [varchar]              | article_id [int]        | reference_name [varchar] |
| sort                        | title [varchar]         | date_created [datetime]  |
| status                      | content [wysiwyg full]  | sort                     |
|                             | status                  | status                   |

Languages table is filled with 2 different language data.
`translation_id` from table **articles** is set as translation alias, as in provided tutorial.
When new article is created, I expect 2 rows to be filled in **articles_translation** for each language where `language_code` is filled with `code` values from **languages** table.

## Actual Behavior
**Three** rows are created in **articles_translation** table. First insert has `language_code` in numerical value 0. If system `status` is set, it also unexpectedly influence how rows are created.   

## Steps to Reproduce
 1. Create tables from Directus as described in Expected Behavior
 2. In table **articles** create new record
 3. Check **articles_translation** for results

## Schema Dump, Logs, or Screenshots
Provided in Expected Behavior

**Comment by rijkvanzanten** [comment]
At the moment, all core developers are working fulltime on the next major version of the platform, so I'll have to leave this open as a help-wanted. If anyone is inclined to take a swing at fixing this, a PR is very welcome 😄

**Comment by uhop** [comment]
I have a similar problem with translations. The tutorial on Medium doesn't work failing with various SQL errors. Non-integer PK doesn't work. A language code field initially (the default) is correct, but any switch to a different language creates a record with a numeric value instead of a language code. Switching back to the default language creates yet another record with a numeric language code. For some reason working with translations using the API is not documented, and it appears that all translations are retrieved with the main object. There is no obvious way to retrieve only a required translation.

**Comment by Kinzi** [comment]
Any progress here?

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/13)
