### ISSUE TITLE
Flow that fails throws error which crashes entire process

### ISSUE THREAD

**Issue by u12206050** [directus/directus#19400]
### Describe the Bug

After creating a flow that tries to delete an item that may or may not have attachments to dependent items, if the item does have dependents then the database throws and error about constraints, but the issue is that this error isn't caught in the flow and eventually becomes an uncaught error which crashes Directus.

### To Reproduce

Create a synchronous manual execute flow that attempts to delete something that has constraints, or insert something that might already exists, then manually execute the flow. The server should crash as a result.

### Directus Version

10.5.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by DanielBiegler** [comment]
Hi there! Cannot reproduce both on the current dev build and the docker 10.5.2 build. Can you maybe provide a little more detail regarding your specific case? Thanks!

Tried

- Deleting something that doesnt exist
- Reading something that doesnt exist
- Deleting something that gets denied by a hook-extension
- Filtering for a field that doesnt exist
- Manually throwing an exception in a run script

Everything works as expected. For example see the response for trying to create an entry with a primary key that already exists:

![image](https://github.com/directus/directus/assets/14810858/db12b869-3490-43c0-a743-7e9d1f94e357)

**Comment by u12206050** [comment]
Hmm, for me it was specific on database errors such as constraints. But will investigate if it is more specific. THanks for the effort.
