### ISSUE TITLE
WebSocket updates not sent for specific collection in production environment

### ISSUE THREAD

**Issue by onurbamaro** [directus/directus#19418]
### Describe the Bug

I'm facing an issue with Directus where WebSocket updates for a particular collection are not being sent to subscribed clients in the production environment, while it works perfectly in the local environment.

Example:
Colletion Couriers: Dev/OK - Prod/OK
Colletion Itineraries: Dev/OK - Prod/OK
Collection Orders: Dev/OK - Prod/No updates (just this particular collection)

Also, using bra1nslug's websocket extension I have no problem. In others words, it fires the updates of the collection "Orders" normally, which makes me think that the directus hook is working. 

**Additional Information:**

Both local and production environments use identical Directus versions and the same environment variables.
I've restored the production database to the dev environment, and the issue does not reproduce locally; everything works as expected.
Using Chrome developer tools, I verified the WebSocket connection is active. Regular ping messages and updates from other collections are received without any issue.
The problem is isolated to just one collection. Other collections send updates as expected in the production environment.

**Troubleshooting Steps Already Taken:**

Verified environment variables and Directus configurations - they are consistent between dev and production.
Restored the production database in the dev environment to ensure collection configurations are identical.
Checked WebSocket connection status and confirmed it's active with regular ping messages.

Any insights or guidance on how to resolve this would be greatly appreciated. Thank you!

### To Reproduce

Establish WebSocket connection in the production environment.
Authenticate and receive acknowledgment.
Subscribe to updates for the problematic collection.
Make changes to the said collection.

Deployment: caprover on Vultr server.
Database: PostgreSQL 15
Browser: Chrome
OS: Ubuntu 22.04

### Directus Version

10.5.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
I know you said it's a copy of the database, but could you confirm the Permissions are the exact same for both users? Also could you try purging your caches by flushing everything in Redis or restarting the Directus process if you're not using Redis?

**Comment by onurbamaro** [comment]
I've confirmed, same permissions for both users. I don't use cache and I've restarted directus a lot while troubleshooting, but without success.

**Comment by onurbamaro** [comment]
"I've set up a staging deployment on my VPS. I used the commands npx directus bootstrap followed by npx directus schema apply to import the schema from my current database. Afterward, I established identical roles and permissions for the specific collection. I then added some dummy data for testing purposes, and it worked. lol

**Comment by onurbamaro** [comment]
OK, I've finally identified the issue. It was actually some clients with outdated code that attempted to connect and subscribe to this collection using Tim's websocket extensions. Somehow, if a client tries to connect and subscribe, it disrupts the native implementation of Directus.
