### ISSUE TITLE
 Sortable doesn't work with Chrome 62 latest

### ISSUE THREAD

**Issue by dsivokhin** [directus/directus#1941]
## Version Info
  - Directus version and branch: master

## Actual Behavior
After update Chrome, sort items not working, I find this issue in https://github.com/RubaXa/Sortable/issues/1182 

Can you update js plugin for master branch too?

**Comment by rijkvanzanten** [comment]
This has been fixed in 80d68cda9fe79ff2b573034e91b1a6dcc0e68dbd on the develop branch and will be released into master soon
