### ISSUE TITLE
Conditions applied to fields across different grouping does not work.

### ISSUE THREAD

**Issue by laportem** [directus/directus#19416]
### Describe the Bug

A field in a group with a condition based on another field outside the group does not work.
I have field B in Group 2 with a hidden condition based on Field A not being null. Field A is not grouped.
If (Field A equal null), then hide Field B else show Field B
If I move Field B outside of the grouping IT WORKS. The moment I move Field B to a grouping it does not work.

### To Reproduce

- Create 2 fields (say, Field A and Field B)
- Create a Detail Group called Group 1
- Move Field B to Group 1
- Create condition on Field B as follows: 
   Rules: Field A Is NULL
   Action: Check the "Disable editing value"
Test and you will see that Field B is still editable whether Field A is Null or Not Null 

Now move Field B outside of  Group 1 and you will see that all works as expected.

### Directus Version

v10.5.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by DanielBiegler** [comment]
Hi! Thanks for opening the issue, we'll investigate and keep track over on #19571
