### ISSUE TITLE
Translations not displaying in the user language in collections

### ISSUE THREAD

**Issue by DamienMrtl** [directus/directus#19424]
### Describe the Bug

The translation should be displayed in french only, and not a list of translations comma separated. 

The workaround is to display the language column but then the column name doesn't make sense to the user.

<img width="1010" alt="image" src="https://github.com/directus/directus/assets/7550391/08ad8055-c89e-4450-a4b6-68e2c69b569d">

### To Reproduce

Create translatable field in collection.
Create content and translate it.
Add the field in the collection display.

### Directus Version

v10.5.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
What display do you have configured for this `nom` field?

**Comment by DamienMrtl** [comment]
@rijkvanzanten I tried both of these:
![image](https://github.com/directus/directus/assets/7550391/1d1c8b0c-311b-483f-bdf0-9c306fb44bf4)

**Comment by rijkvanzanten** [comment]
Oh is that `nom` field on the `produits` table a relational nested field? Try using the translations field itself in that table instead. That has a display that allows you to configure what fields to render and in what language 👍🏻

**Comment by DamienMrtl** [comment]
This "Translation" display mode should be available on the translated field 
![image](https://github.com/directus/directus/assets/7550391/1dc8ad39-50a5-4537-a92b-4a741a826bd0)
Because the column header should be the correct field name representing the value. Isn't that possible ?

**Comment by rijkvanzanten** [comment]
Ah OK, so your "Translations" field is called "Languages". In that case, configure the "Display" (you're currently screenshotting the Interface) for the Languages field to show "Name" 👍🏻

**Comment by DamienMrtl** [comment]
@rijkvanzanten can you please reopen this issue as this is still not working.

**Comment by rijkvanzanten** [comment]
This conversation is continued in the duplicate copy #19626
