### ISSUE TITLE
Preflight Authorization

### ISSUE THREAD

**Issue by ruthgeridema** [directus/directus#19431]
### Describe the Bug

When using Directus JS, it's using an empty Authorization header when . Traefik won't accept that header.
I guess there is no need for the JS-client to use this header. 

A workaround for Traefik is also welcome if this is wanted behaviour:

**Error in Traefik:**
Access to XMLHttpRequest at 'https://xxx/items/settings?0=*' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.

### To Reproduce

 curl -D - '{{URL}}' \
  -X 'OPTIONS' \                                                                     
  -H 'authority: xx' \   
  -H 'accept: */*' \                    
  -H 'accept-language: nl-NL,nl;q=0.9,en-US;q=0.8,en;q=0.7' \
  -H 'access-control-request-headers: authorization' \
  -H 'access-control-request-method: GET' \                                                                                               
  -H 'origin: http://localhost:3000' \
  -H 'referer: http://localhost:3000/' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36' \
  --compressed

### Directus Version

latest

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Please do elaborate on your reproduction steps as just running that request against directus works without issues. So at the very least i expect that a treafik setup with specific settings is required to reproduce 😄 

Did you configure CORS settings for your setup like:
```
CORS_ALLOWED_HEADERS: 'Content-Type,Authorization'
```

Closing this issue for now, happy to re-open when more information becomes available.
