### ISSUE TITLE
Can't update columns in table view in presets and bookmarks

### ISSUE THREAD

**Issue by hripunov** [directus/directus#19432]
### Describe the Bug

From now on, I can't update my presets and bookmarks, in particular, add new columns to the table view or delete existing ones. The "save" button does not become active.

So far, everything has worked. The problem is observed on three projects on different servers.
Directus is installed on Ubuntu+mysql, starts with the ‘npx directus start’ command.

To reproduce the error, I started a clean server with a clean Directus installation. I tried to reproduce both with SQLite and MySQL.

### 1. Creating a new default preset

![Снимок экрана (20)](https://github.com/directus/directus/assets/125863745/1cdfac39-3750-4aa1-bd72-5ef446fe3af6)

### 2. Choose a collection

![Снимок экрана (21)](https://github.com/directus/directus/assets/125863745/5637e899-ba1b-4c04-b8ec-31fa04eb633e)

### 3. Arrange the columns as needed

![Снимок экрана (22)](https://github.com/directus/directus/assets/125863745/f6ef53d7-d586-4c39-b75a-f4128fa90023)

### 4. Save the preset

![Снимок экрана (23)](https://github.com/directus/directus/assets/125863745/d427d432-596b-46d7-8200-8df8bde7e894)

### 5. Go to the collection items page, make sure that everything is fine

![Снимок экрана (24)](https://github.com/directus/directus/assets/125863745/dc420a00-909d-4317-b078-ec3a264c5564)

### 6. Go to the preset list page and delete the preset created automatically for the current user

![Снимок экрана (25)](https://github.com/directus/directus/assets/125863745/62a90a4b-effc-4182-9dbd-97566d33a314)

### 7. Go to the default preset editor and add a new column to the table (for example, ID)

![Снимок экрана (26)](https://github.com/directus/directus/assets/125863745/25211fa1-7781-49f5-920e-3dc5a961ff28)
![Снимок экрана (27)](https://github.com/directus/directus/assets/125863745/42da4a9b-1e23-46de-8bbd-b12e3fd1c6ae)

### 8. (ERROR) We are trying to save the preset, but the "save" button is inactive

![Снимок экрана (28)](https://github.com/directus/directus/assets/125863745/b7e75645-eae2-4f8e-b73c-06235efc2d58)

### 9. Trying to activate the "save" button by changing the main preset fields (for example, color)

![Снимок экрана (29)](https://github.com/directus/directus/assets/125863745/3562153a-27f2-4fdc-a8b1-b1a5898441b8)

### 10. Click the "save" button

![Снимок экрана (30)](https://github.com/directus/directus/assets/125863745/17c6f217-536d-4aa8-b492-7c0207bdb1de)

### 11. (ERROR) We go to the collection items page, make sure that the column we added did not appear.

![Снимок экрана (31)](https://github.com/directus/directus/assets/125863745/147c5537-280a-422a-ae22-aa780607e7ed)

### Directus Version

v10.5.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by pjhartin** [comment]
We are also experiencing this same bug on **v10.5.3**.

**Comment by rijkvanzanten** [comment]
@ConnorSimply just tagging you in on this for oversight on the bigger upgrades around preset configuration 🙂
