### ISSUE TITLE
Groups not printed in REST API

### ISSUE THREAD

**Issue by aoor9** [directus/directus#19447]
### Describe the Improvement

I created a detail group (let's call it 'foo') with some fields inside (bar1, bar2 ...) and I wanted to fetch it through REST API.
However when I call the endpoint, the payload result is not what I expected.

```
// what I wanted to retrieve
{
    "data": {
        "foo": {
            "bar1": "",
            "bar2": "",
            ...
        }
    }
}

// what I actually get is all of the group's fields but not the group itself
{
    "data": {    
        "bar1": "",
        "bar2": "",
         ...    
    }
}
```

When I add this to the endpoint URL
`?fields=foo.*`

it only returns the item ID. Still not what I'm looking for.  

Aren't groups supposed to be nested objects? Isn't there a way to fix this? Or (if groups are meant for some different goals) even override the endpoint to map the requested result?

**Comment by rijkvanzanten** [comment]
> Aren't groups supposed to be nested objects?

Nope! Groups are just for presentation in the app.

> Or (if groups are meant for some different goals) even override the endpoint to map the requested result?

You could use hooks to override the output, but I wouldn't recommend doing that. Changing the output of the items endpoint will brick the admin app. You could make a custom endpoint or use flows to generate an endpoint that returns data in a custom format though!
