### ISSUE TITLE
Extra comma in front of column write blacklist

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1944]
## Version Info
  - Directus version and branch: develop 06f0accf43aaf37ad5091f75bfb577bfda9167ab

## Behavior
The permissions settings render an extra comma in front of the CSV of "Column Write Blacklist":

<img width="1123" alt="screen shot 2017-11-08 at 10 15 49 am" src="https://user-images.githubusercontent.com/9141017/32556682-0c96f6d6-c46e-11e7-8268-8d9457304569.png">

**Comment by WellingGuzman** [comment]
Interesting, it should have trip those trailing and forward.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/f70af8d12f94ddcad52b0ce9f8eac472aa5a5576
