### ISSUE TITLE
Feature Request: Filter Field for One-to-Many Relations Creation

### ISSUE THREAD

**Issue by bogdan-nita** [directus/directus#19449]
### Describe the Improvement

I am currently working on a CMS setup using Directus where I have a collection called blocks_group. This collection is designed to have a many-to-any relationship with other collections such as FAQ, Quotes, Workshops, etc. The goal is to have a generic group component in which I can reference items from other collections.

However, I've encountered an issue: when content editors are populating these groups, there's a risk they might mistakenly mix item types within the same group (e.g., combining FAQ and Quotes in a single group). This poses a challenge for maintaining consistent content structures and can result in unpredictable content presentations on the frontend.

Describe the solution you'd like
I propose the introduction of a filter field during the creation of one-to-many relations. This filter would allow administrators to set constraints on what types of items can be added to a specific group. For instance, if I'm creating a group meant for FAQ items, I could set a filter that only allows items of the type FAQ to be added.

One workaround is to create separate collections for each type of group (like blocks_faq, blocks_testimonials, etc.), each having a many-to-many relationship with its respective item collection. However, this approach leads to redundancy and can make the CMS setup overly complex.

Having the ability to set constraints on one-to-many relations would provide a robust solution for maintaining content consistency. It would ensure that content editors are guided correctly when populating groups, preventing potential content mix-ups.

**Comment by br41nslug** [comment]
That seems like a quite useful addition for content moderating 😄 however "issues" is not the right place for feature requests, please do make a [Feature Request](https://github.com/directus/directus/discussions/categories/feature-requests) for this and drop it in the discord for some upvotes as im sure others are interested in similar solutions 😄
