### ISSUE TITLE
Choosing existing user on permissions settings page doesn't seem to do anything

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1945]
## Version Info
  - Directus version and branch: develop 06f0accf43aaf37ad5091f75bfb577bfda9167ab
  - PHP version: 7.1.8
  - MySQL version: 5.6.35
  - Web server: Apache on MAMP Pro
  - OS name and version: macOS High Sierra 10.13.1 Beta (17B25c)

## Behavior
Clicking on "Select Existing" and selecting an existing user doesn't seem to do anything..

![broken](https://user-images.githubusercontent.com/9141017/32558522-f1d66912-c472-11e7-9234-766ab138737b.gif)

## Steps to Reproduce
 1. Try to add an existing user to a permissions group

**Comment by WellingGuzman** [comment]
It seems to work, but not visually. I will fix this as soon as possible.

**Comment by WellingGuzman** [comment]
Note: If you go ahead and save it works.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/5b1f72ba4674871df90f3628fb9dafbb83e7de28
