### ISSUE TITLE
Allow ignoring paths from logger

### ISSUE THREAD

**Issue by duel-adn** [directus/directus#19464]
### Describe the Improvement

In a kubernetes environment is common to use `/server/ping` for liveness and/or readiness checking, however, this causes a lot of log messages that have no practical use and pollute the important output of the application.

In the previous versions of Directus, it was possible to add something like this in the `.env`:

`LOGGER_HTTP_AUTO_LOGGING__IGNORE_PATHS=["/server/ping"]`

but due to [changes](https://github.com/pinojs/pino-http/blob/d1f226c706db04910afdc44f46686b75fc2b39eb/deprecations.js) in pino logger this does not work anymore.

The solution suggested by pino is to add `opts.autoLogging.ignore`, but this variable must point to a function that obviously cannot be put in a .env file.

Writing a config.js just for solving this problem would be an overkill, hence my suggestion of adding an environment variable to disable the logging of the `/server/ping` route.

**Comment by rijkvanzanten** [comment]
Gonna increase the scope of this a hair to just make it configurable what paths to ignore, so it's not something that's specific to /server/ping 🙂
