### ISSUE TITLE
Flows - "Trigger Flow" auto escapes payload

### ISSUE THREAD

**Issue by alexvdvalk** [directus/directus#19469]
### Describe the Bug

When passing in a variable into the payload field on the "trigger flow" operation, the quotation marks are automatically escaped which causes the variable to be interpreted as a string. This makes the flow crash because it's expecting JSON but receives a string.

### To Reproduce

Add in the payload variable
save the operation
re open the operation
notice that the string has some additional included escape characters.

https://github.com/directus/directus/assets/21194068/7593673b-2f56-4af3-ac4f-aab4af7ceed6

### Directus Version

10.5.3

### Hosting Strategy

Directus Cloud

**Comment by danielband** [comment]
Hi, for now you can edit the raw payload. There are a few issues with operation inputs right now. #19244
