### ISSUE TITLE
FB/Google/Twitter Login

### ISSUE THREAD

**Issue by razuro** [directus/directus#1947]
Great work guys! I"ve seen in the demo there are FB/Google/Twitter integration. But it seems like being disabled. I'm currently using 6.4.1 and from the change log, I know that this is possible. Mind showing me the docs how to go about?

Thanks!

**Comment by rijkvanzanten** [comment]
Hey @razuro! I actually just wrote an article on this subject yesterday! It's over on [our Medium publication](https://medium.com/directus):

https://medium.com/directus/3rd-party-authentication-2da642576dcd?source=linkShare-d577fb4926a5-1510195202
