### ISSUE TITLE
Checkboxes (JSON)

### ISSUE THREAD

**Issue by TyrionFront** [directus/directus#19488]
### Describe the Bug

For JSON-field interface type defined as "Checkboxes (Tree)" whenever you select 1 nested item - if it's the same one in any other upper branch, it will be selected as well

https://github.com/directus/directus/assets/18406903/4307653a-33b3-49a6-8b11-891a53065e42

<img width="856" alt="Screenshot 2023-08-22 at 17 11 26" src="https://github.com/directus/directus/assets/18406903/8d1cbe6d-de18-446a-8ba3-4b5485f27ed9">

### To Reproduce

Just add any tree-like JSON-field and try to work with it.

### Directus Version

v10.5.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by DanielBiegler** [comment]
Hi there! This is not a bug, values are supposed to be unique. Changing your values to be unique fixes this.

**Comment by rijkvanzanten** [comment]
> With all the respect - it can barely be named a "feature": what about the use case when there are no unique values required within every branch ?

@TyrionFront It sounds to me like you're coming from the assumption that the parent-level makes the children not-unique. The value that's saved is a flat array of selections, not a nested list. That in turn means that values from leafs should be unique within branches, for example:

```
- [ ] branch-a
  - [ ] leaf-1
  - [x] leaf-2
- [ ] branch-b
  - [ ] leaf-1
  - [x] leaf-2
```

will save `["leaf-2", "leaf-2"]` 👍🏻

**Comment by TyrionFront** [comment]
@DanielBiegler , @rijkvanzanten - thank you both for the informative and detailed explanations.
My bad - didn't get to the docs good enough)
