### ISSUE TITLE
Case sensitive email address 

### ISSUE THREAD

**Issue by craigharman** [directus/directus#19497]
### Describe the Bug

You can create a user with a case sensitive email address "Test@test.com".
Then trying to login with "test@test.com" fails.

Suggest forcing emails to lowercase on creation/update or during login comparison.

### To Reproduce

Use the API to create a new user with email address "Test@test.com"

### Directus Version

10.5.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
Uniqueness is checked as lowercase on login and on creation. I am unable to create 2 emails with varying cases and i am able to login independent of capitalization 🤔 

Can this be related to a specific database vendor? Tested with postgres and sqlite.

**Comment by craigharman** [comment]
I'll get some more details on platform and recreation steps from my team.
