### ISSUE TITLE
File-picker doesn't show folders when "Root" folder is set

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#19493]
### Describe the Bug

When there's no root folder, the file picker drawer has the file library navigation included:

<img width="955" alt="CleanShot 2023-08-22 at 17 40 18@2x" src="https://github.com/directus/directus/assets/9141017/341508d5-ef07-4026-a544-5ddb3aa9907f">

This is missing when you're using a root folder:

<img width="994" alt="CleanShot 2023-08-22 at 17 41 30@2x" src="https://github.com/directus/directus/assets/9141017/2ef8d998-5a7f-480e-bc6b-d47a53055e02">

Even when you have a root folder, you should be able to use the file sidebar navigation

### To Reproduce

Use the file interface with the root folder option configured, select an existing file from the system

### Directus Version

10.5.3

### Hosting Strategy

Directus Cloud

**Comment by rijkvanzanten** [comment]
@paescuj Lets change that "design" than 😄 The setting is called _Root_ Folder, which to me means it's the top-level folder you can access, but it doesn't mean that you're not allowed to use any of the folders that are within that root folder. Your "Limited navigation (only show sub folders)" suggestion should be the default here 👍🏻

**Comment by paescuj** [comment]
> Your "Limited navigation (only show sub folders)" suggestion should be the default here 👍🏻

Absolutely agree 😃👍
Just wanted to ensure we don't introduce the breaking change mentioned in the comment.

**Comment by rijkvanzanten** [comment]
I don't think that's a breaking change 👍🏻

**Comment by paescuj** [comment]
> I don't think that's a breaking change 👍🏻

Hmm I know that some admin's are/were using the "Root Folder" option as a way to limit the file selection for users, so what I meant is that showing all folders would be a breaking change since the users would suddenly be able to see all files.
But yeah, the "only show sub folders" option by default should be fine and expected 👍

**Comment by rijkvanzanten** [comment]
> Hmm I know that some admin's are/were using the "Root Folder" option as a way to limit the file selection for users, so what I meant is that showing all folders would be a breaking change since the users would suddenly be able to see all files.

If that's the case, something was going wrong. That's permissions, not interface options!
