### ISSUE TITLE
Import .svg image from a url gives error

### ISSUE THREAD

**Issue by Datacenturies** [directus/directus#19492]
### Describe the Bug

Import .svg image from a URL gives this error

### To Reproduce

upload any media file, choose from URL, insert this URL https://www.uspolo.org/uspolo/safari-pinned-tab.svg

### Directus Version

v10.5.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by Nitwel** [comment]
I was not able to reproduce this and using the link you provided added the svg just fine. 

Please provide more information like the error message that you got or how you configured your file system.

**Comment by br41nslug** [comment]
I did reproduce it yesterday.
