### ISSUE TITLE
Adding status column to existing table removes all items from view

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1949]
## Version Info
  - Directus version and branch: develop ba07c00435424254c3e07d6c18e80417472e14d9

## Expected Behavior
Creating a new column with the status interface sets all columns to a default

## Actual Behavior
The column is `NULL` in the DB (since it's a new column) which makes Directus hide the items completely

## Steps to Reproduce
 1. Create a table _without a status column_
 2. Add some records
 3. Add a status column

**Comment by benhaynes** [comment]
The issue here seems to be that you should be able to choose a default value when adding the column (just like in the actual database). Did you try adding a default when creating the new status column?

**Comment by WellingGuzman** [comment]
Exactly, what is the default value of that column?

**Comment by rijkvanzanten** [comment]
That's the difficult question. It can't be `NULL` or it they'll be invisible, but we can't just set it to a value as well, since it's user configurable....

**Comment by rijkvanzanten** [comment]
@benhaynes We should discuss this a little more seeing that this isn't an implementation bug, but rather a design-problem. Can we / do we want to automatically default to the first status as defined in `configuration.php` (`directus_settings` in 7.0)?

**Comment by rijkvanzanten** [comment]
Right!

**Comment by rijkvanzanten** [comment]
At the moment, all core developers are working fulltime on the next major version of the platform, so I'll have to leave this open as a help-wanted. If anyone is inclined to take a swing at fixing this, a PR is very welcome 😄

We'll make sure this isn't a problem in 7.0, but nonetheless: if anyone wants to fix this in 6.x, a PR is welcome!

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/14)
