### ISSUE TITLE
Insights: TypeError[count_functions.count]: Cannot convert to OutputType

### ISSUE THREAD

**Issue by Pachat** [directus/directus#19509]
### Describe the Bug

Count/distinct on UUID/string fields produces the following error
```
    {
      "message": "TypeError[count_functions.count]: Cannot convert to OutputType the following value: Object({ type: GraphQLScalarType({ name: \"Int\", description: \"The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1.\", specifiedByURL: undefined, serialize: [function serialize], parseValue: [function parseValue], parseLiteral: [function parseLiteral], extensions: {  }, astNode: undefined, extensionASTNodes: [] }) })",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
```

### To Reproduce

1. Create a dashboard
2. Add a Metric: Count on the uuid ID of a collection

The error will appear at saving the Metric, at saving the dashboard and at showing the dashboard.

PostgreSQL 15

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
I have been unable to reproduce this on either postgres 14 or 15. Testing with a dashboard using the count distinct metric on both a custom collection uuid and the directus_users collection.

Happy to re-open the issue if more information becomes available 😄

**Comment by Pachat** [comment]
@br41nslug Thanks for investigating.
I hope the issue #19327 which is preventing me from upgrading from 10.2.1 will be part of the next release.
I'll wait to see if I can redo dashboards.

**Comment by Pachat** [comment]
@br41nslug Just tried on 10.6.2 fresh install for another app.
- Collection with an int column and trying to get Σ on it for all rows.
- It gives
```
TypeError[count_functions.count]: Cannot convert to OutputType the following value: Object({ type: GraphQLScalarType({ name: \"Int\", description: \"The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1.\", specifiedByURL: undefined, serialize: [function serialize], parseValue: [function parseValue], parseLiteral: [function parseLiteral], extensions: {  }, astNode: undefined, extensionASTNodes: [] }) })",
      "stack":
```
Is it still a bug or am'i not doing things right?

**Comment by Pachat** [comment]
@br41nslug Thank you so much for the time you took to try once again.
If it is not a Directus bug, it may depend on the environment.
Here, I test locally under W10 on a PostgreSQL as already stated.
Here are the insights:

1° the collection

![1](https://github.com/directus/directus/assets/13746133/1344a1e4-74bd-4f2b-a258-491f5dc14c43)

2° the insght

![2](https://github.com/directus/directus/assets/13746133/34294b9f-28e4-4f47-8b34-0a8d2a11f74f)

3° What happens on saving the previous screen

![3](https://github.com/directus/directus/assets/13746133/f75971b4-d8bf-4d7c-8ba1-9ac05929e190)

The same happens using Count instead of Sum.
And then when I just try to open the insight, the same error raises.

May be it has to do with GraphQLScalarType .
I did an npm install. But still got the same errors.

**Comment by Pachat** [comment]
Finally, it happens that this error is produced on a local installation only (under Windows 10).
No bugs on the server.

**Comment by br41nslug** [comment]
> Finally, it happens that this error is produced on a local installation only (under Windows 10).

any new steps to reproduce? because so far i have been reproducing on win10 locally
