### ISSUE TITLE
Create collections endpoint returns 403

### ISSUE THREAD

**Issue by JoelForamitti** [directus/directus#19501]
### Describe the Bug

Using the javascript SDK, createCollection returns 403 with the following error:

```
ERROR  [unhandledRejection] { errors: [ { message: "You don't have permission to access this.", extensions: [Object] } ] }
```

### To Reproduce

I am using the Javascript SDK with Nuxt and a fresh Docker instance of Directus.

I can successfully create fields and read and write data. 

The following produces the error:

```ts
const adminClient = createDirectus(<env_var>)
  .with(authentication())
  .with(rest());

await adminClient.login(<env_var>, <env_var>, { mode: "json" });

await adminClient.request(
  createCollection({
    collection: "myCollection",
  })
);
```

### Directus Version

v10.5.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
This is unrelated to the SDK but rather an issue with the collections endpoint.
The docs say the following but yet creating a collection with only a collection name does fail for me
> The collection property is required, all other properties of the [collection object](https://docs.directus.io/reference/system/collections.html#the-collection-object) are optional.
```
curl --location 'http://localhost:8055/collections' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer adminToken' \
--data '{"collection":"test_collection" }'
```
![image](https://github.com/directus/directus/assets/9389634/eb609131-1c77-48f9-98cb-d59f501c9904)

**Comment by JoelForamitti** [comment]
Thank you for the quick response. So there are two issues, right? One is that the endpoint requires optional parameters, and the other is that the response for an invalid payload is wrong (should be 400, not 403).

Unfortunately, the workaround is not possile with the SDK since `"schema":{}` is not allowed. With `"schema":null` or the following I still get the same response:

```ts
{
      collection: "myCollection",
      schema: {
        schema: "test-schema",
        name: "test-schema",
        comment: null,
      },
      meta: {},
}
```

**Comment by JoelForamitti** [comment]
Thank you for explaining @rijkvanzanten.

But should this issue not remain open as it is nonetheless not possible to use the createCollection function of the SDK? Or is there an example of an implementation of createCollection that works?

**Comment by rijkvanzanten** [comment]
> But should this issue not remain open as it is not possible to use the createCollection function of the SDK

Is it not? From what I can tell the SDK behaves as it should 🤔 I've updated the docs in the linked PR to mention that schema is required to prevent this confusion moving forwards 🙂

**Comment by JoelForamitti** [comment]
Thanks! Maybe I am just missing a working example of how a correct createCollection call looks like, since the docs say the following:

```
const result = await client.request(
	createCollection({
		collection: 'collection_name',
		field: {
			sub_field: 'value',
		},
	})
);
```

**Comment by alexvdvalk** [comment]
The default payload automatically creates an Integer for the primary key. This payload creates the table with a UUID primary key:

```
const result = await client.request(
    createCollection({
      collection: "myCollection",
      //@ts-ignore
      fields: [
        {
          field: "id",
          type: "uuid",
          meta: {
            hidden: true,
            readonly: true,
            interface: "input",
            special: ["uuid"],
          },
          schema: {
            is_primary_key: true,
            length: 36,
            has_auto_increment: false,
          },
        },
      ],
      schema: {
        schema: "test-schema",
        name: "test-schema",
        comment: null,
      },
      meta: {},
    })
  );
  ```
