### ISSUE TITLE
Pre-existing Postgres array-of-strings filtering

### ISSUE THREAD

**Issue by sibowyer** [directus/directus#19505]
### Describe the Bug

I have Directus (10.5.3) running on top of a pre-existing Postgres DB (13.7).
In the UI, filtering on character varying[] (i.e array of strings) field types doesn't seem to work. And in the schema configuration modal the field type is shown as `unknown`, which may have something to do with the problem. I was previously hoping that this https://github.com/directus/directus/pull/19005 would have been the resolution.

Attempting to filter an array column (in my example a table named area having a column named alternative names) using the 'Contains' operator, and typing a value, throws an Internal Server Error:
```
"message": "select \"area\".\"country_alpha_3\", \"area\".\"google_location_key\", \"area\".\"google_place_id\", \"area\".\"id\", \"area\".\"alternative_names\" from \"area\" where (\"area\".\"alternative_names\" like $1) order by \"area\".\"id\" asc limit $2 - operator does not exist: character varying[] ~~ unknown"
```

When then switching to the 'Is one of' operator, there is no ability in the UI to enter a value. However, if I use the 'Contains' operator first to enter a value and then change the operator type to 'Is one of', the following Internal Server Error is thrown:
```
"message": "select \"area\".\"country_alpha_3\", \"area\".\"google_location_key\", \"area\".\"google_place_id\", \"area\".\"id\", \"area\".\"alternative_names\" from \"area\" where (\"area\".\"alternative_names\" in ($1)) order by \"area\".\"id\" asc limit $2 - malformed array literal: \"Ir\""
```

### To Reproduce

- Manually, create a postgres database having a table with an array-of-strings column:
```sql
CREATE TABLE area (
    id SERIAL PRIMARY KEY,
    alternative_names character varying[] NOT NULL DEFAULT '{}'::character varying[]
```
- Add a couple of rows manually.

- Install the latest version of Directus onto this DB.
- In the Directus UI, unhide the collection, then attempt to apply filtering to the array column.

### Directus Version

v10.5.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
Directus currently doesn't natively support Postgres arrays or other non-sql types (like custom types). Please do open a [new feature request](https://github.com/directus/directus/discussions/new?category=feature-requests) though if this is something you'd like to see supported in the platform in the future!

**Comment by sibowyer** [comment]
Thanks for the prompt response @rijkvanzanten, much appreciated. I shall instead wait for the [JSON filtering PR](https://github.com/directus/directus/pull/15889) and we'll use JSONB arrays.
