### ISSUE TITLE
Error with Many-to-Many when primary keys are VARCHAR

### ISSUE THREAD

**Issue by dlaprade** [directus/directus#1951]
## Version Info
  - Directus version and branch: 6.4.3
  - PHP version: 7.1.11
  - MySQL version: MariaDB 10.1
  - Web server: Apache
  - OS name and version: Debian Jessie Linux

## Expected Behavior
I created a many-to-many relationship between two tables with a join table that have primary keys of type VARCHAR. The data_type of the many-to-many shows up as "ALIAS". When I am creating a new many-to-many, I expect that when I choose from a list of items, I can select a few of them, then confirm successful save. 

## Actual Behavior
When I am creating a new many-to-many, when I click choose existing, it comes up with a list of items, I can select a few of them, but when confirming (blue checkbox) it fails with the error show below. 

## Steps to Reproduce
 1. Create TABLE_A with VARCHAR primary key
 2. Create TABLE_B with VARCHAR primary key
 3. Create JOIN_TABLE_A_B with VARCHAR primary key
 4. In TABLE_A, create a many-to-many relationship, by choosing the junction table JOIN_TABLE_A_B and related table TABLE_B
 5. Save
 6. Select TABLE_A
 7. Click CHOOSE EXISTING buttom in GUI
 8. Select items from TABLE_B
 9. Click choose to save

## Schema Dump, Logs, or Screenshots
![screen shot 2017-11-10 at 4 14 00 pm](https://user-images.githubusercontent.com/7399336/32744029-1953466a-c863-11e7-82e1-7a9f5f58f0cf.png)

**Comment by WellingGuzman** [comment]
Hey @dlaprade thanks for reporting this, we are going to take a look at this bug some time this week.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/2488d23e95e3015ad2fbc267ee1beda64c8962f9
