### ISSUE TITLE
How to get user data after successful login

### ISSUE THREAD

**Issue by abelbayon02** [directus/directus#19519]
### Describe the Bug

I have a react project for frontend and im using the directus as my backend and CMS as welll , Is there any way to fetch the user data after a successful login? because as my current situation, after i login the response is only access_token. or is the access_token can be use to get the user data?

auth/login this is the endpoint i'm using

### To Reproduce

create a login form , then use the auth/login endpoint . check the response and you'll only see access_token and refresh_token

### Directus Version

9

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
You can use the `/users/me` endpoint to get the user that's associated with the current login session.

Also make sure to update your Directus project, v9 is EOL
