### ISSUE TITLE
Float Rounding Sometime

### ISSUE THREAD

**Issue by pdesuze** [directus/directus#19515]
### Describe the Bug

I have one field IPC Amount of Data Type Float with Value 1218913.73 rounding up to 1218913.8 and another field of the same Data type float with value 32456.73 and it display as 32456.73. Is this a bug or because of the precision value.  

### To Reproduce

Two Fields of Data Type Float

### Directus Version

10.5.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
There's no way for me to answer that without a little more info on the setup of those fields 👀 

> [...] or because of the precision value.

Could be! What is the configured precision value for those two fields?

**Comment by pdesuze** [comment]
The Precision is 24 for float (Default)
