### ISSUE TITLE
Audio pronunciation link invalid

### ISSUE THREAD

**Issue by ched-dev** [directus/directus#19535]
### Page

https://docs.directus.io/getting-started/introduction.html

### Describe the Inaccuracy

When I click the "([duh REKT iss](http://audio.pronouncekiwi.com/Salli/Directus))" pronunciation link I get an error page.

<img width="683" alt="Screen Shot 2023-08-26 at 1 46 44 PM" src="https://github.com/directus/directus/assets/73146636/95728375-7662-4b84-b6a0-dd96b7ab874c">

<img width="765" alt="Screen Shot 2023-08-26 at 1 43 40 PM" src="https://github.com/directus/directus/assets/73146636/a1c02495-45da-4d8b-8526-4f520b2ce742">

**Comment by paescuj** [comment]
Thanks for your report!

Seems like the page has been replaced for some time.
The original audio is still available on the Wayback Machine: http://web.archive.org/web/20220525065924/https://audio.pronouncekiwi.com/Salli/Directus

Wondering if we should upload our own version to the docs so we are independent of external sources 🤔

**Comment by rijkvanzanten** [comment]
> Wondering if we should upload our own version to the docs so we are independent of external sources 🤔

You wanna record it? 😄
