### ISSUE TITLE
Default rule for system table Directus Users is not being applied per the notice

### ISSUE THREAD

**Issue by kevincam3** [directus/directus#19536]
### Describe the Bug

I'm testing Directus so I only have the Admin user. I created a new Role but did not modify the system table permissions. When I create a new user, login and go to the the users module, the new user I created can see the admin user. When I go the the Read permissions of the  directus_users table it appears that by default the user should only be able to see their account

![image](https://github.com/directus/directus/assets/870934/1a8843ee-6951-4760-98f8-e5b84f25bb25)

If I add that rule manually it works as I expected.

![image](https://github.com/directus/directus/assets/870934/599da1aa-9076-473d-98a1-542d0ee46948)

### To Reproduce

1. Create a new collection
2. Create a new role and give access to the new collection
3. Create a new user and assign to that role
4. Login as new user and go to User Directory > All Users

You will see the Admin user

### Directus Version

v10.7.0-beta.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
> [...] I created a new Role but did not modify the system table permissions [...] 

It seems like you modified the `Field Permissions` for `directus_users`, though. Without that the default rule works fine, but I guess it should also be enforced even with modified `Field Permissions` 👍
