### ISSUE TITLE
Can't saved "Color" field withs RGB

### ISSUE THREAD

**Issue by dsivokhin** [directus/directus#1953]
## Version Info
  - Directus version and branch: master
  - PHP version: 7.0

## Actual Behavior

Can't saved "Color" field withs RGB 

![default](https://user-images.githubusercontent.com/4669992/32772203-37318d80-c936-11e7-8ac3-f3c9f020753f.png)

![default](https://user-images.githubusercontent.com/4669992/32772222-42453096-c936-11e7-9a33-a4c6002d2744.png)

![default](https://user-images.githubusercontent.com/4669992/32772247-55f8406a-c936-11e7-99ae-12267fbc1f82.png)

**Comment by WellingGuzman** [comment]
This was fixed by https://github.com/directus/directus/commit/4f58b39e8fc15f9bbb95db7f4f438dbf8e1d2f25
