### ISSUE TITLE
npx create-directus-project not working anymore?

### ISSUE THREAD

**Issue by vtisnado** [directus/directus#19534]
### Describe the Bug

`npx create-directus-project` command keeps in the "Installing Directus" message, spikes de server RAM memory but never completes.

After months without creating a new project, yesterday I tried to find the steps in the documentation, however, now I only see the method with Docker, so I'm wondering if the NPX method is not working anymore.

### To Reproduce

Run `npx create-directus-project PROJECT_NAME` command on a Linux server.

### Directus Version

v9.0.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by ched-dev** [comment]
@vtisnado What node version are you using? Latest directus requires v18+.

**Comment by vtisnado** [comment]
That's weird. I just checked and my server have Node +18:
```
node  v18.16.0
npm  9.6.5
```
I had no issues in that server working with **Directus 9**, but now I can't find the documentation to start the project with **Directus 9** and I only got the `npx create-directus-project` command from old notes.

**Comment by paescuj** [comment]
Can you try with `npm init directus-project my-project`? See https://github.com/directus/create-directus-project#installation

**Comment by vtisnado** [comment]
I just uploaded to:
```
node  v20.5.1
npm  9.8.0
```
before tried `npm init directus-project my-project` without luck.

**Comment by paescuj** [comment]
Just tested and it works fine on my system (macOS). What OS are you on? Are outgoing connections (to NPM) enabled and allowed?
Also can you retry with `@latest` to ensure the latest version of `create-directus-project` is used:
```shell
npm init directus-project@latest my-project
```

**Comment by vtisnado** [comment]
Hi @paescuj I just tried the `npm init directus-project@latest my-project ` command and I have more than 50 minutes waiting to complete.

I didn't mention that I'm trying to run the installation on an Ubuntu server where I have other Directus v9 instances.

After run the command this is what I see:
```
Need to install the following packages:
create-directus-project@9.14.2
Ok to proceed? (y) y
⠼ Installing Directus
```
And it keeps in that screen, sometimes the green animations stops, others the "Installing Directus" disappear and appears again, but the installation never completes.

My only guess is that the support of this installation method has been stopped and now the only way is using Docker.

**Comment by rijkvanzanten** [comment]
> My only guess is that the support of this installation method has been stopped and now the only way is using Docker.

Nope! We push Docker as it's way simpler to get running and less risky to run into environment specific issues, like missing binaries etc. Doesn't mean that NPM based installations aren't possible though 🙂 The `npm init` command is just a mini shorthand for:

1. `npm init -y`
2. `npm install directus` 
3. Creating the `.env` file with the required [env variables](https://docs.directus.io/self-hosted/config-options.html) 
4. Running `npx directus bootstrap`

Do those individual steps take that long as well?

**Comment by vtisnado** [comment]
Hey @rijkvanzanten

I just noticed that the process get stuck on step 2: `npm install directus`. The last message I got was: `(##################) ⠴ reify:date-fns: timing reifyNode:node_modules/rxjs Completed in 24912ms`

Nothing else moves forward after that message and the RAM memory keeps at +90% until I kill the process. I have more than 20 mins waiting and nothing...

Here is the complete message in the terminal:

```
npm install directus
npm WARN deprecated @types/cssnano@5.1.0: This is a stub types definition. cssnano provides its own type definitions, so you do not need this installed.
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated consolidate@0.15.1: Please upgrade to consolidate v1.0.0+ as it has been modernized with several long-awaited fixes implemented. Maintenance is supported by Forward Email at https://forwardemail.net ; follow/watch https://github.com/ladjs/consolidate for updates and release changelog
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated json2csv@5.0.7: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
(##################) ⠴ reify:date-fns: timing reifyNode:node_modules/rxjs Completed in 24912ms
```

I updated the server yesterday to:

```
node  v20.5.1
npm  9.8.0
```

Linux versión:
`Ubuntu 20.04.6 LTS`

**Comment by paescuj** [comment]
This seems to be an issue with `npm` and not Directus itself. See https://github.com/date-fns/date-fns/issues/2479#issuecomment-851763334 for a similar case and how it could possibly be solved.
I'll close this issue for now.

**Comment by vtisnado** [comment]
Hey, in case anyone got also stuck in the manually installation, I finally discovered what was the cause.

After updating Node, NPM and Ubuntu, I tried a fresh installation and I got this error message:

`Error: Cannot find module '@napi-rs/snappy-linux-x64-gnu'`

So I ran the Directus installation again and it worked! Here are the steps:

1. Start the installation with `$npx create-directus-project PROJECT_NAME`
2. If the installation never stops or get the **napi** error, install the library inside **PROJECT_NAME** directory:  `npm i @napi-rs/snappy-linux-x64-gnu` (napi version should match your system)
3. After napi installation completes, run `npx directus init` inside **PROJECT_NAME** directory

You should see the Directus bootstrap steps now.  

I took the steps from: https://github.com/directus/directus/discussions/16257#discussioncomment-4214605
