### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by eiacopini** [directus/directus#19540]
### Describe the Bug

Running Directus through a Nginx proxy with sub folder 
https://domain.cloud/db
https://domain.cloud/db/admin/login
if i try to insert the docker-compose data ADMIN_USER and ADMIN_PASSWORD
I get the following error.
![Screenshot 2023-08-28 164303](https://github.com/directus/directus/assets/107869133/710c74cd-8fb8-4001-bf92-1bfc1c9b0b90)

Post auth/login 401

### To Reproduce

```
directus:
    container_name: directus
    image: directus/directus:latest
    ports: 
    - "8055:8055"
    volumes: 
    - ./directus/uploads:/directus/uploads 
    depends_on:
     - geonode
     - db
    environment:
       KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
       SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
       DB_CLIENT: 'pg'
       DB_HOST: 'db'
       DB_PORT:  5432
       DB_DATABASE: 'test'
       DB_USER: postgres
       DB_PASSWORD: postgres
       ADMIN_EMAIL: 'admin@admin.com'
       ADMIN_PASSWORD: 'd1r3ctu5'
       PUBLIC_URL: 'https://domain.cloud/db/'
       ROOT_REDIRECT: ./admin

location ~ ^/db/ {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_pass http://directus:8055;   
}
```

### Directus Version

latest

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Make sure to rewrite the subfolder so Directus can keep routing as usual. It is probably failing because `/db/auth/login` is not an endpoint known to Directus.

try adding this rewrite to ur nginx location
```
rewrite ^/db/(.*)$ /$1 break;
```

**Comment by eiacopini** [comment]
@br41nslug I tried but still giving the same error.
I reload nginx docker exec -it nginx4geonode nginx -s reload
and docker compose up

**Comment by br41nslug** [comment]
Can you check the directus console output for the error on the backend?

**Comment by eiacopini** [comment]
![Screenshot 2023-08-28 172916](https://github.com/directus/directus/assets/107869133/2f33dc6d-9d21-4db6-85b3-944f4c4ac285)
![Screenshot 2023-08-28 173028](https://github.com/directus/directus/assets/107869133/a69ac0b3-7114-43b3-8e37-1005d7d07812)

**Comment by br41nslug** [comment]
Looks like most requests are succeeding. perhaps not all headers get passed by the proxy 🤔 
If for instance the `Content-Type: application/json` doesn't get passed the body with your credentials won't get parsed properly.

Can you try adding:
```
proxy_pass_request_headers      on;
```

**Comment by eiacopini** [comment]
Same error auth/login 401 :(

**Comment by eiacopini** [comment]
https://github.com/directus/directus/discussions/4480#discussioncomment-3578333

in latest version where is node_modules/@directus/sdk/dist/sdk.bundler.js?

**Comment by paescuj** [comment]
> [#4480 (comment)](https://github.com/directus/directus/discussions/4480#discussioncomment-3578333)
> 
> @br41nslug in latest version where is node_modules/@directus/sdk/dist/sdk.bundler.js?

As already indicated in https://github.com/directus/directus/issues/19533#issuecomment-1694525022, please use the help channels mentioned in https://docs.directus.io/getting-started/support.html#support-tiers for questions like this.
Thanks!

**Comment by br41nslug** [comment]
> [#4480 (comment)](https://github.com/directus/directus/discussions/4480#discussioncomment-3578333)
> 
> @br41nslug in latest version where is node_modules/@directus/sdk/dist/sdk.bundler.js?

That is someone using the (old) SDK in their own frontend site i don't think that is applicable to ur situation.
