### ISSUE TITLE
Image/File processing service is unavailable

### ISSUE THREAD

**Issue by johannes-richter** [directus/directus#19543]
### Describe the Bug

When trying to add media content with the file service in any section (e.g. creating an item with an image or just a logo change in the project settings), it will not happen and following error will be displayed:
[SERVICE_UNAVAILABLE] Service "external-file" is unavailable. Couldn't fetch file from url
or
[SERVICE_UNAVAILABLE] Service "files" is unavailable. Couldn't save file 57A8500F-A847-47E7-9AD5-C839A56A5CD9.svg.

### To Reproduce

Sign in to your directus project. Navigate to project settings and change the background
or
Navigate to files and try uploading an image

### Directus Version

v10.3.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
What kind of storage adapter have you configured?

**Comment by johannes-richter** [comment]
Sorry, no idea. I thought storage adapter was a piece of hardware.

**Comment by br41nslug** [comment]
Then i'll assume you havent configured a cloud storage adapter like Amazon S3 or similar. Have you configured your uploads folder then? with the right permissions
https://docs.directus.io/self-hosted/docker-guide.html#persistence

**Comment by johannes-richter** [comment]
Hey @br41nslug 
Thanks, that's a good hint. I requested access to these configuration files and then I'll check the upload permissions. I think as of now, this might not be a bug, but a configuration issue. I will come back here and report, once I have been granted access and corrected the yaml. Thanks :-)

**Comment by rijkvanzanten** [comment]
I'll close this for now as it seems to be a configuration issue rather than a Directus issue. Happy to keep discussing here or reopen if it turns out to be a bug 🙂

**Comment by shealavington** [comment]
Hiya 👋 I'm updating my Image Scout extension, and I've just had the same issue as you @johannes-richter. 

I've attached screenshots (From the UI, and Docker Logs) of the issue I was getting while trying to upload files. 

I've found that when I remove the uploads mount (`- ./uploads:/directus/uploads`) from my `docker-compose.yml` volumes, the permissions issue goes away. Given this information, I don't think it's a driver issue, by default a local driver is used, instead it is likely a permissions issue between the host machine with a mounted volume and the permissions of the container.

Hopefully this helps somewhat ✨

![image](https://github.com/directus/directus/assets/16869302/a884389a-0dc5-4054-b377-96e0736d6d08)
![image](https://github.com/directus/directus/assets/16869302/b74c4822-4339-44c4-94a0-3f561dd2b402)

**Comment by notflip** [comment]
@shealavington Did you find a solution to this? Also running into this issue using the local driver

**Comment by shealavington** [comment]
> @shealavington Did you find a solution to this? Also running into this issue using the local driver

I just proceeded with the directory unmounted as for what I was doing, it didn't matter for me. Unfortunately I'm not sure about an actual solution to it.

**Comment by metaaifactory** [comment]
Same problem for me :(
