### ISSUE TITLE
I am trying to delete some bookmarks and they will not delete

### ISSUE THREAD

**Issue by divinepersuasionstudio** [directus/directus#19549]
### Describe the Bug

I am trying to delete duplicate bookmarks and even though it let's me delete them, they do not actually delete.

### To Reproduce

go to the bookmarks and presets module
click on the bookmark you want to delete.
click delete
the page will refresh and it will still be there
tried bulk delete and going into each bookmark to delete
neither works

### Directus Version

10.5.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Couldn't reproduce this on the quick.
Are you logged in as an Admin user? What database are you using?
