### ISSUE TITLE
Login through external provider not working with new SDK

### ISSUE THREAD

**Issue by stx-chris** [directus/directus#19544]
### Describe the Bug

When using the `login` method of the client in the new SDK `11.X.X` with an external provider, eg. `google`, the login fails with a `404 not found` error. Reason seems to be that the request is sent as `POST` whereas provider redirection is `GET` only. 

### To Reproduce

1. Set up an external OpenId/OAuth2 Provider in Directus
2. use the Javascript SDK
3. Call the `login` function on the client like this: `await client.login("", "", { provider: "google" })`
4. See the `404` error

![image](https://github.com/directus/directus/assets/62717406/6a65fc78-15f8-43ab-873e-f7c8bf59274d)

### Directus Version

v10.6.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by stx-chris** [comment]
was anybody able to reproduce this issue or have a workaround?

We tried to switch to email/pwd temporarily but then Directus would complain that for the given email a different provider must be used.

Grateful for any ideas. thx!

**Comment by br41nslug** [comment]
Sorry the bug here is me copying the SSO settings for the login function blindly 😬 Currently the SDK does not support SSO login flows (even tho the settings are technically there). Please do upvote the feature request i put up for it https://github.com/directus/directus/discussions/19723
