### ISSUE TITLE
Can't update DB schema through CLI

### ISSUE THREAD

**Issue by flrrrhoffpauir** [directus/directus#1954]
I am able to login to Directus locally and add/modify content, but when I try to upgrade the database schema I get an error.

## Version Info
  - Directus version and branch: 6.4.3 master
  - PHP version: 5.6.30
  - MySQL version: 5.6.35
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: macOS Sierra

## Expected Behavior
Upgrade the database scheme using the CLI:
`php bin/directus db:upgrade`

## Actual Behavior
Error:
```
Warning: mysqli::mysqli(): (HY000/2002): No such file or directory in /Applications/MAMP/htdocs/directus/vendor/directus/migrations/lib/Ruckusing/Adapter/MySQL/MySQLBase.php on line 1296

Fatal error: Uncaught
MySQLBase.php(1298) :

Could not connect to the DB, check host / user / password



  thrown in /Applications/MAMP/htdocs/directus/vendor/directus/migrations/lib/Ruckusing/Adapter/MySQL/MySQLBase.php on line 1298
```

## Steps to Reproduce
 1. CD to Directus directory in terminal
 2. run `php bin/directus db:upgrade`
 3. receive error

**Comment by WellingGuzman** [comment]
Hey @flrrrhoffpauir this issue has to do with the `mysqli` not being loaded in your php cli version.

This may help a bit: https://github.com/directus/directus/issues/1745

**Comment by flrrrhoffpauir** [comment]
thanks so much @WellingGuzman that did the trick. I added the MAMP version of php to my path, ran the command again and it worked

```
# Use MAMP version of PHP
PHP_VERSION=`ls /Applications/MAMP/bin/php/ | sort -n | tail -1`
export PATH=/Applications/MAMP/bin/php/${PHP_VERSION}/bin:$PATH
```

**Comment by WellingGuzman** [comment]
Glad it worked out.
