### ISSUE TITLE
ESM error when using a config.js file

### ISSUE THREAD

**Issue by ericandrewscott** [directus/directus#19555]
### Describe the Bug

If you have a `config.js` file and are on the latest version of 9.x, you'll be unable to deploy a Docker image.
This may be fixed in 10, but many of use are stuck on 9 without an enterprise license.

It seems like it's trying to `require` when it imports the config here: https://github.com/directus/directus/blob/0deadb9062cd4d360cb61d1a4a09de6c0988267f/api/src/env.ts#L15

And then it blows up here: https://github.com/directus/directus/blob/0deadb9062cd4d360cb61d1a4a09de6c0988267f/api/src/env.ts#L403

![Screenshot 2023-08-29 at 1 34 35 PM](https://github.com/directus/directus/assets/1651613/e66ada2a-8fb8-456b-bbb7-3631a39dfb7c)

### To Reproduce

1. Docker file using latest 9.x: `FROM directus/directus:9.26.0`.
2. Docker file referencing a config file with `COPY ./config.js .`
3. Have a fairly simple ESM `config.json`:
```
import fs from 'fs';
import path from 'path';

export default function (env) {
    // Get the JSON file name from the environment
    const jsonFileName = '/vault/secrets/secrets.json';

    // Read the JSON file and parse its contents
    const jsonData = fs.readFileSync(path.resolve(jsonFileName));
    const json = JSON.parse(jsonData);

    for (let prop in json) {
        env[prop] = json[prop];
    }

    // Log the environment variables that were set
    return env;
};
```

### Directus Version

v9.26.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
The `config.js` file needs to be in CJS format, ESM is not supported, see https://docs.directus.io/self-hosted/config-options.html#config-js.

Also it might be worthwhile to contact our team at https://directus.io/contact to find an appropriate solution for you to upgrade to v10 so you don't miss out new features, security patches, etc.

**Comment by ericandrewscott** [comment]
@paescuj if you need a config file in 9.25 or 9.26, you can't because it's not set up to use CJS when it's explitly type module in the API project. Is that by design?

**Comment by br41nslug** [comment]
I can confirm that independently of the content of the `config.js` file (tested both esm and cjs) it will error in production mode (`pnpm dev` works somehow). Tested this on 9.26 and 10.6 and the same issue is present in both.

Because our API is set to `type: module` any `*.js` file will be assumed to be ESM and we're using `require` to include this which fails on loading ESM files. And for config files we're not loading `*.cjs` or `*.mjs` extensions.

![image](https://github.com/directus/directus/assets/9389634/3b7d3094-a6a0-44b3-8d52-cdce97204487)
![image](https://github.com/directus/directus/assets/9389634/3e5a13d7-c15a-4328-bce9-9fa1602519db)

**Comment by ericandrewscott** [comment]
Thanks @br41nslug for confirming this is a bug!

**Comment by peti446** [comment]
I can confirm that I also have the issue on 10.6.1 (docker image), to circumvent it for the time being you can create a folder where the config.js is present and alongside a package.json, the package.json needs to have at least the following type:
{
  "type": "commonjs"
}
You then set the config path to the .js and as the closest package.json will be the one created with the type commonjs it will not complain about the .js extensions allowing directus to load it correctly.

This is what I am doing inside my docker images for the time being
