### ISSUE TITLE
Changes being lost / stuff not getting saved

### ISSUE THREAD

**Issue by tom-wmg** [directus/directus#1955]
## Version Info
  - Directus version and branch: 6.4.3
  - PHP version: 5.6.30
  - MySQL version: 5.6.36
  - Web server: Apache
  - OS name and version: OS X 

## Expected Behavior

Clicking save when editing content of nested X2M relationships (at least 3 levels deep) should save content.

## Actual Behavior

Content not saved - no errors appear. But content "lost"

Welling says problem with X2M. 

## Steps to Reproduce
 1. Video shows what goes wrong

## Schema Dump, Logs, or Screenshots

https://www.dropbox.com/s/fqsgqnz14x9q2n8/Directus%201.mov?dl=0

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/6af1ad6833a39c526b9021b67cec0f5e6db6bdba
