### ISSUE TITLE
upload embed youtube

### ISSUE THREAD

**Issue by phongXEM** [directus/directus#19554]
### Describe the Bug

i embed youtube vào wyswyg. then save. but 504 Gateway Time-out

### To Reproduce

504 Gateway Time-out

### Directus Version

v10.5.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
You need to configure CSP to allow embedding of Youtube videos.
For example with the following configuration:
```ini
CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC="www.youtube.com"
```
See also:
- https://docs.directus.io/self-hosted/config-options.html#security
- https://github.com/directus/directus/discussions/17393
- https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

**Comment by phongXEM** [comment]
I'm done configuring `CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC="www.youtube.com"`
But when save items. Directus show error [UNKNOWN] Request failed with status code 504
a padding to disable MSIE and Chrome friendly error page

**Comment by paescuj** [comment]
Okay, so it seems like there's an issue with your setup. I assume you've a proxy in place which is responsible for the [504 Gateway Timeout](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504) error, so I recommend making sure that the proxy is configured correctly.
