### ISSUE TITLE
Schema migration out of the box

### ISSUE THREAD

**Issue by TyrionFront** [directus/directus#19553]
### Describe the Bug

An attempt of saving snapshot file in JSON format creates file with .json ext but still in .yaml-based format.

<img width="952" alt="Screenshot 2023-08-30 at 00 26 02" src="https://github.com/directus/directus/assets/18406903/f793bf67-22ca-4c60-9db5-3b530feafe52">

### To Reproduce

Apply relevant command from the [migration flow section](https://docs.directus.io/self-hosted/cli.html#migrate-schema-to-a-different-environment)

### Directus Version

10.5.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
The command is:
```shell
npx directus schema snapshot --format json ./snapshot.yaml
```

See also:
```shell
npx directus schema snapshot --help
```
