### ISSUE TITLE
Drag and drop reordering doesn't work

### ISSUE THREAD

**Issue by tom-wmg** [directus/directus#1956]
## Version Info
  - Directus version and branch: 6.4.3
  - PHP version: 
  - MySQL version: 
  - Web server: (Ex. Apache, nginx or IIS?) 
  - OS name and version: Chrome, latest, OS X

## Expected Behavior

Drag and drop to reorder field list

## Actual Behavior

Field list doesn't change order

## Steps to Reproduce
 1. Video shows what goes wrong

## Schema Dump, Logs, or Screenshots

https://www.dropbox.com/s/mh31zsyxe9slu3g/Directus%202.mov?dl=0

**Comment by rijkvanzanten** [comment]
This might be a duplicate of https://github.com/directus/directus/issues/1941

**Comment by tom-wmg** [comment]
I confirm this works on Safari, so could well be a browser bug, sorry

**Comment by rijkvanzanten** [comment]
No that's okay! Rather have multiple duplicates than no report at all 😄 

I'll close this as we release 6.4.4 tomorrow including this fix 👍
