### ISSUE TITLE
Condition does not update start open and start closed on detail group

### ISSUE THREAD

**Issue by hotspot-app** [directus/directus#19571]
### Describe the Bug

I have a collection address with a field group `different_contact` which has the fields `different_first_name`, `different_last_name` and `different_company` which are all strings.
![image](https://github.com/directus/directus/assets/97624653/0bc0b416-787b-44ec-a8c8-3582b9b32772)

 In the detail group interface i set this:
![image](https://github.com/directus/directus/assets/97624653/793c086f-9e37-486f-8ea8-c641e7ed76f0)

With this condition:
![image](https://github.com/directus/directus/assets/97624653/eea53443-dc80-4c2f-b1e0-a0f4858c7f45)

The icon gets updated correctly. The problem is that no matter if the values are null or not, when i open an address item the detail group always starts closed.

### To Reproduce

Create a field group with nullable values in a collection.
In the interface options set `Start Open`
Add a condition: If all values are null `Start Closed`

### Directus Version

v10.6.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by DanielBiegler** [comment]
Can confirm, this is reproducible but not only on groups, also on other fields like a simple string-field. The following condition should disable the nullable string-field, as it's default value is null, but it **does not:**

![image](https://github.com/directus/directus/assets/14810858/61e57edd-c845-46cf-b249-a768f5eee9f5)

Also tried other conditions, of which **none** worked.

**Comment by rijkvanzanten** [comment]
I believe this is because the interface is rendered before the item's data is loaded, meaning that the conditional fields will executed _after_ the interface is already rendered and therefore the "start" point in time is already in the past
