### ISSUE TITLE
Core O2M GUI functionality broken

### ISSUE THREAD

**Issue by tom-wmg** [directus/directus#1957]
## Version Info
  - Directus version and branch: 6.4.3
  - PHP version: 
  - MySQL version: 
  - Web server: (Ex. Apache, nginx or IIS?) 
  - OS name and version: Chrome, latest, OS X

## Expected Behavior

Parent/child content should be retained upon creation and save

## Actual Behavior

Content gets deleted most of the time. This is not fit for purpose.

## Steps to Reproduce
Video shows what goes wrong

## Schema Dump, Logs, or Screenshots

https://www.dropbox.com/s/htswwl8ysphqzxn/Directus%203.mov?dl=0

**Comment by tom-wmg** [comment]
ps, am I the only one? Seems hard to believe... Or do people just not use the GUI?

**Comment by rijkvanzanten** [comment]
Hi @tom-wmg 

This issue hasn't been reported before and I haven't been able to reproduce this myself on a clean local install so far.

With Directus being able to be hosted and used virtually anywhere, it's very hard for maintainers and contributors to figure out what is going on without having the necessary information. Could you please update your original post with more information so we can reproduce your env and figure out what is going on? You have left us hardly any info to work with..

**Comment by WellingGuzman** [comment]
hey @rijkvanzanten I talked to @tom-wmg, and this issue has been resolved by https://github.com/directus/directus/commit/6af1ad6833a39c526b9021b67cec0f5e6db6bdba

Related to https://github.com/directus/directus/issues/1955
