### ISSUE TITLE
Can’t scroll the page after disabling Preview Mode

### ISSUE THREAD

**Issue by JonathanDoelan** [directus/directus#19579]
### Describe the Bug

The page does not scroll after disabling the preview mode.

### To Reproduce

Open an existing item, where preview mode is available. Click the `Enable Preview` button and try to scroll. If scrolling works, toggle the Preview Button again until it does not work (sometimes the bug occurs after the second time).

Browser: Firefox 117.0

### Directus Version

v10.5.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
https://github.com/directus/directus/assets/9389634/0f8149ac-d1a9-4a59-8fab-add78bdf4acc
