### ISSUE TITLE
docker readonlyfilesystem could not be enable after upgrading directus 10

### ISSUE THREAD

**Issue by taco-chen** [directus/directus#19578]
### Describe the Bug

I am currently using a self-hosted Directus instance deployed as a Docker container on AWS ECS. Directus is an awesome project. However, I encountered an issue after upgrading from Directus 9.18.1 to 10.6.1. I am unable to enable the `ReadonlyRootFilesystem` feature of the Docker container because the new version of Directus requires the creation of a `.cache` folder during initialization.

Our company policy, along with AWS Security Hub's recommendations, mandates that the `ReadonlyRootFilesystem` feature of Docker containers must always be enabled to maintain security standards. Failure to do so is considered a critical security issue.

I'm wondering if there are any options to disable this caching feature in Directus 10, similar to how it was possible in Directus 9. Any guidance on this matter would be greatly appreciated.

Error message:
```
node:internal/process/promises:288
triggerUncaughtException(err, true /* fromPromise */);
[Error: EROFS: read-only file system, mkdir '/cms/.cache'] {
  errno: -30,
  code: 'EROFS', 
  syscall: 'mkdir', 
  path: '/cms/.cache' 
}
Node.js v18.14.2
```

Thank you!

### To Reproduce

1. set `read_only: true` to dockerfile
2. docker compose up with directus
3. the system prompts `[Error: EROFS: read-only file system, mkdir '/cms/.cache']`

### Directus Version

v10.6.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
This is a consequence of the `update-notifier` added in https://github.com/directus/directus/pull/18738
