### ISSUE TITLE
@directus/sdk - Realtime auth token sent to server many times per second

### ISSUE THREAD

**Issue by matt-rolley** [directus/directus#19583]
### Describe the Improvement

When inspecting an open socket, it seems to send the access token many times per second, and I think this might be the issue:

```js

if (message['type'] === 'auth' && hasAuth(currentClient)) {
  const access_token = await currentClient.getToken();
  
  if (access_token) {
	  ws.send(auth({ access_token }));
	  continue;
  }
}

```

When the server sends back an auth ok, it triggers the socket to send the access token - is this required?

Would this work instead?

```js

if (message['type'] === 'auth' && message['status'] !== 'ok' && hasAuth(currentClient)) {
  const access_token = await currentClient.getToken();
  
  if (access_token) {
	  ws.send(auth({ access_token }));
	  continue;
  }
}

```

It just makes it hard to debug in the network tab

**Comment by br41nslug** [comment]
Happened to run into this bug too today :) thanks for reporting it
