### ISSUE TITLE
Not able to download directus vagrant box

### ISSUE THREAD

**Issue by vasselva** [directus/directus#1958]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus version and branch: (Or commit hash)
  - PHP version: 
  - MySQL version: 
  - Web server: (Ex. Apache, nginx or IIS?) 
  - OS name and version: 

## Steps to Reproduce
 1. 
 2. 
 3.

**Comment by vasselva** [comment]
> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'directus' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'directus' (v0) for provider: virtualbox
    default: Downloading: https://demo.getdirectus.com/vagrant/directus
    default: Progress: 100% (Rate: 6779/s, Estimated time remaining: --:--:--)
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and that enough disk space
is available and then try again.
The output from attempting to unpackage (if any):

bsdtar.EXE: Error opening archive: Unrecognized archive format

**Comment by WellingGuzman** [comment]
Hey @vasselva thanks for reporting this, this has been reported in the `directus-vagrant` repo. (Ref: https://github.com/directus/directus-vagrant/issues/25)

I will try to upload the box once again today, having some issue uploading it.
