### ISSUE TITLE
Directus Unauthenticated Modules and user/invite/accept override

### ISSUE THREAD

**Issue by Be-P** [directus/directus#19580]
### Describe the Bug

I'm trying to override the "user invite accept" flow. I've correctly used the `USER_INVITE_URL_ALLOW_LIST` to override the `invite_url` used in the email invite flow. Differently from what the Documentation reports about the [invite callback](https://docs.directus.io/reference/system/users.html#request-11) I'm not receiving back the password, I'm only receiving the token back from the client. 

Reading the directus source code that's how it is supposed to work: the `accept-invite.vue` page was the actually overridden destination of the email link. Then the vue component does the following:
```javascript
await api.post(`/users/invite/accept`, {
	password: password.value,
	token: acceptToken.value,
}); 
```
This is what allows the `users/invite/accept` endpoint to get back both pwd and token.

I'm trying to reproduce the same behavior with small changes, I was reading how such public routes are defined and it should be something like that:
```javascript
export default defineModule({
 id: 'custom',
 name: 'Custom',
 icon: 'box',
 routes: [{ path: 'test', component: ModuleComponent, meta: { public: true }}],
});
```

Unfortunatly the public modifier doesn't work, and now I'm stuck: It seems there is no possibility to  correctly expose, without authentication a `<public-view>`

I think at least 3 things can be fixed here:
- allow to override the invite callback post-password configuration
- allow to publish unauthorized modules
- fix the documentation

### To Reproduce

Create a custom module and define it as follows 
```javascript
export default defineModule({
 id: 'custom',
 name: 'Custom',
 icon: 'box',
 routes: [{ path: 'test', component: ModuleComponent, meta: { public: true }}],
});
```
Try to access it without being authenticated, you'll get redirected to the login page

### Directus Version

v10.6.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Be-P** [comment]
If I can provide some help I'll be glad to help and open a PR, but I need some pointers

**Comment by michaeltoohig** [comment]
Now I may not be giving the best help or the correct help you need but I did something with a public registration before which may be relevant here. 

You could create a public role and user for public access. In directus you can create a auth token for the public user then embed the token in your application so whoever visits this page is authenticated automatically as this public user. You have to restrict the role associated with this user to prevent anyone from doing anything other than what you intend them to do until they register and login as their own user.

I did this with a separate vue app and used directus as a backend only so this may not work in your custom module.

**Comment by br41nslug** [comment]
The built-in "user invite accept flow" cannot be overridden afaik and the Directus App currently does not support publicly accessible routes.

Please do make a [feature request](https://github.com/directus/directus/discussions/categories/feature-requests) for suggesting new features or improvements to existing features.
