### ISSUE TITLE
Many-To-One changes with VARCHAR Primary Key not Saved

### ISSUE THREAD

**Issue by magbeat** [directus/directus#1959]
## Version Info
  - Directus version and branch: current develop branch as of 20-11-2017
  - PHP version: 5.6.32
  - MySQL version: 10.1-MariaDB
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: FreeBSD

## Expected Behavior

Many-to-One connection with VARCHAR Primary Keys should be saved when editing an item.

## Actual Behavior

Many-to-One connection with VARCHAR Primary Keys are not saved when editing an item.

## Steps to Reproduce
 1. Create table with VARCHAR Primary Key
 2. Create another table which references first table via VARCHAR foreign key
 3. Add and edit an item

## Schema Dump, Logs, or Screenshots

Table with VARCHAR Primary Key:

![01_language_table](https://user-images.githubusercontent.com/1089410/33022156-7d453182-ce04-11e7-9f33-41c19b818101.PNG)

Table with Many-To-One Relation:

![02_uploads_table_part1](https://user-images.githubusercontent.com/1089410/33022158-816f3dca-ce04-11e7-90ae-9020ed5a4948.PNG)

![02_uploads_table_part2](https://user-images.githubusercontent.com/1089410/33022162-849a98b4-ce04-11e7-81b0-c6f7078b0fab.PNG)

Add and edit an item:

![03_edit_item](https://user-images.githubusercontent.com/1089410/33022165-876dab1c-ce04-11e7-9c1b-cf89693193ff.PNG)

Choose a language from the dropdown:

![04_select_language](https://user-images.githubusercontent.com/1089410/33022178-8c4054c8-ce04-11e7-881c-6c22f826428d.PNG)

Save and open again (changes lost):
![05_edit_item_again](https://user-images.githubusercontent.com/1089410/33022181-8ece0ece-ce04-11e7-8d79-f67ce98d68b4.PNG)

**Comment by WellingGuzman** [comment]
Fixed by https://github.com/directus/directus/commit/a54043c955f0292bb1e3895ca5d9c043b2f45a96

**Comment by magbeat** [comment]
@WellingGuzman Thanks for the fix! I can now change the value in the database and it's shown in the list and when editing the item it is correctly marked as selected in the dropdown. However I cannot save the item and when changing the relation. 

There is an error toast saying: "Server Error
Statement could not be executed (42S22 - 1054 - Unknown column 'id' in 'where clause')"

The logs in full:

`ERROR - 2017-11-20T16:31:47-05:00 - exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause'' in /home/exampleadmin/www/api.example.ch/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:239
Stack trace:
#0 /home/exampleadmin/www/api.example.ch/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute()
#1 /home/exampleadmin/www/api.example.ch/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(239): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#2 /home/exampleadmin/www/api.example.ch/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(209): Zend\Db\TableGateway\AbstractTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#3 /home/exampleadmin/www/api.example.ch/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(196): Zend\Db\TableGateway\AbstractTableGateway->selectWith(Object(Zend\Db\Sql\Select))#4 /home/exampleadmin/www/api.example.ch/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(198): Zend\Db\TableGateway\AbstractTableGateway->select(Object(Closure))
#5 /home/exampleadmin/www/api.example.ch/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(453): Directus\Database\TableGateway\RelationalTableGateway->manageRecordUpdate('language', Array)
#6 /home/exampleadmin/www/api.example.ch/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(131): Directus\Database\TableGateway\RelationalTableGateway->addOrUpdateManyToOneRelationships(Object(Directus\Database\Object\Table), Array, Array, false)
#7 /home/exampleadmin/www/api.example.ch/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(77): Directus\Database\TableGateway\RelationalTableGateway->manageRecordUpdate('uploads', Array, 1)
#8 /home/exampleadmin/www/api.example.ch/api/routes/A1/Entries.php(202): Directus\Database\TableGateway\RelationalTableGateway->updateRecord(Array, 1)
#9 [internal function]: Directus\API\Routes\A1\Entries->row('uploads', '1')
#10 /home/exampleadmin/www/api.example.ch/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Array, Array)
#11 /home/exampleadmin/www/api.example.ch/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#12 /home/exampleadmin/www/api.example.ch/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#13 /home/exampleadmin/www/api.example.ch/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#14 /home/exampleadmin/www/api.example.ch/api/core/Directus/Slim/CorsMiddleware.php(19): Slim\Middleware\MethodOverride->call()
#15 /home/exampleadmin/www/api.example.ch/api/core/Directus/Slim/HttpCacheMiddleware.php(18): Directus\Slim\CorsMiddleware->call()
#16 /home/exampleadmin/www/api.example.ch/api/core/Directus/Slim/ResponseCacheMiddleware.php(37): Directus\Slim\HttpCacheMiddleware->call()
#17 /home/exampleadmin/www/api.example.ch/vendor/slim/slim/Slim/Slim.php(1302): Directus\Slim\ResponseCacheMiddleware->call()
#18 /home/exampleadmin/www/api.example.ch/api/core/Directus/Application/Application.php(103): Slim\Slim->run()
#19 /home/exampleadmin/www/api.example.ch/api/api.php(534): Directus\Application\Application->run()
#20 {main}

Next exception 'Zend\Db\Adapter\Exception\InvalidQueryException' with message 'Statement could not be executed (42S22 - 1054 - Unknown column 'id' in 'where clause')' in /home/exampleadmin/www/api.example.ch/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:244
Stack trace:
#0 /home/exampleadmin/www/api.example.ch/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(239): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#1 /home/exampleadmin/www/api.example.ch/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(209): Zend\Db\TableGateway\AbstractTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#2 /home/exampleadmin/www/api.example.ch/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(196): Zend\Db\TableGateway\AbstractTableGateway->selectWith(Object(Zend\Db\Sql\Select))#3 /home/exampleadmin/www/api.example.ch/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(198): Zend\Db\TableGateway\AbstractTableGateway->select(Object(Closure))
#4 /home/exampleadmin/www/api.example.ch/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(453): Directus\Database\TableGateway\RelationalTableGateway->manageRecordUpdate('language', Array)
#5 /home/exampleadmin/www/api.example.ch/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(131): Directus\Database\TableGateway\RelationalTableGateway->addOrUpdateManyToOneRelationships(Object(Directus\Database\Object\Table), Array, Array, false)
#6 /home/exampleadmin/www/api.example.ch/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(77): Directus\Database\TableGateway\RelationalTableGateway->manageRecordUpdate('uploads', Array, 1)
#7 /home/exampleadmin/www/api.example.ch/api/routes/A1/Entries.php(202): Directus\Database\TableGateway\RelationalTableGateway->updateRecord(Array, 1)
#8 [internal function]: Directus\API\Routes\A1\Entries->row('uploads', '1')
#9 /home/exampleadmin/www/api.example.ch/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Array, Array)
#10 /home/exampleadmin/www/api.example.ch/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#11 /home/exampleadmin/www/api.example.ch/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#12 /home/exampleadmin/www/api.example.ch/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#13 /home/exampleadmin/www/api.example.ch/api/core/Directus/Slim/CorsMiddleware.php(19): Slim\Middleware\MethodOverride->call()
#14 /home/exampleadmin/www/api.example.ch/api/core/Directus/Slim/HttpCacheMiddleware.php(18): Directus\Slim\CorsMiddleware->call()
#15 /home/exampleadmin/www/api.example.ch/api/core/Directus/Slim/ResponseCacheMiddleware.php(37): Directus\Slim\HttpCacheMiddleware->call()
#16 /home/exampleadmin/www/api.example.ch/vendor/slim/slim/Slim/Slim.php(1302): Directus\Slim\ResponseCacheMiddleware->call()
#17 /home/exampleadmin/www/api.example.ch/api/core/Directus/Application/Application.php(103): Slim\Slim->run()
#18 /home/exampleadmin/www/api.example.ch/api/api.php(534): Directus\Application\Application->run()
#19 {main}`
