### ISSUE TITLE
directus snapshot 10.6.1

### ISSUE THREAD

**Issue by co2nunes** [directus/directus#19590]
### Describe the Bug

When saving a snapshop.yaml file into the HD, it keeps asking to reinstall directus@10.6.1 in a loop and doesn't create any snapshot file.

### To Reproduce

Now using node v18.17.1 (npm v9.6.7)
[ec2-user@ip-172-31-34-173 api]$ npm install -g directus@10.6.1
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated @types/cssnano@5.1.0: This is a stub types definition. cssnano provides its own type definitions, so you do not need this installed.
npm WARN deprecated consolidate@0.15.1: Please upgrade to consolidate v1.0.0+ as it has been modernized with several long-awaited fixes implemented. Maintenance is supported by Forward Email at https://forwardemail.net ; follow/watch https://github.com/ladjs/consolidate for updates and release changelog
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated json2csv@5.0.7: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm ERR! code 1
npm ERR! path /home/ec2-user/.nvm/versions/node/v18.17.1/lib/node_modules/directus/node_modules/isolated-vm
npm ERR! command failed
npm ERR! command sh -c prebuild-install || (node-gyp rebuild --release -j 4 && node-gyp clean)
npm ERR! prebuild-install warn install No prebuilt binaries found (target=18.17.1 runtime=node arch=arm64 libc= platform=linux)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@18.17.1 | linux | arm64
npm ERR! gyp info find Python using Python version 3.9.16 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/ec2-user/.nvm/versions/node/v18.17.1/lib/node_modules/directus/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ec2-user/.nvm/versions/node/v18.17.1/lib/node_modules/directus/node_modules/isolated-vm/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ec2-user/.nvm/versions/node/v18.17.1/lib/node_modules/directus/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ec2-user/.cache/node-gyp/18.17.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/ec2-user/.cache/node-gyp/18.17.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/ec2-user/.nvm/versions/node/v18.17.1/lib/node_modules/directus/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/ec2-user/.cache/node-gyp/18.17.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/ec2-user/.nvm/versions/node/v18.17.1/lib/node_modules/directus/node_modules/isolated-vm',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/home/ec2-user/.nvm/versions/node/v18.17.1/lib/node_modules/directus/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /home/ec2-user/.nvm/versions/node/v18.17.1/lib/node_modules/directus/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/home/ec2-user/.nvm/versions/node/v18.17.1/lib/node_modules/directus/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /home/ec2-user/.nvm/versions/node/v18.17.1/lib/node_modules/directus/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/home/ec2-user/.nvm/versions/node/v18.17.1/lib/node_modules/directus/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /home/ec2-user/.nvm/versions/node/v18.17.1/lib/node_modules/directus/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /home/ec2-user/.nvm/versions/node/v18.17.1/lib/node_modules/directus/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /home/ec2-user/.nvm/versions/node/v18.17.1/lib/node_modules/directus/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:210:21)
npm ERR! gyp ERR! System Linux 6.1.41-63.114.amzn2023.aarch64
npm ERR! gyp ERR! command "/home/ec2-user/.nvm/versions/node/v18.17.1/bin/node" "/home/ec2-user/.nvm/versions/node/v18.17.1/lib/node_modules/directus/node_modules/.bin/node-gyp" "rebuild" "--release" "-j" "4"
npm ERR! gyp ERR! cwd /home/ec2-user/.nvm/versions/node/v18.17.1/lib/node_modules/directus/node_modules/isolated-vm
npm ERR! gyp ERR! node -v v18.17.1
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

### Directus Version

v10.6.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Looks like you're missing the required build deps when installing directus not sure where the snapshot figures in as you should already have directus installed to make a snapshot of.

Make sure you have all the pre-requisites for isolated-vm or use the pre-built docker.
https://github.com/directus/directus/releases/tag/v10.6.0
https://github.com/laverdet/isolated-vm#requirements

Closing this for now
