### ISSUE TITLE
Flows. ReferenceError: require is not defined

### ISSUE THREAD

**Issue by VladDigitalOriginal** [directus/directus#19602]
### Describe the Bug

I keep my project on version 10.3.0 for some time and importing module in flows was just fine.
`FLOWS_EXEC_ALLOWED_MODULES: 'crypto'` is set and all worked.

After updating to 10.6.1 it show no allowed modules and throw error:
`{
  "name": "ReferenceError",
  "message": "require is not defined"
}`

### To Reproduce

1. Set `FLOWS_EXEC_ALLOWED_MODULES: 'crypto'` in docer-compose / Dockerfile
2. Create new flow
3. Add operation 'Run Script'
4. `const crypto = require('crypto');`
5. Run flow.

### Directus Version

v10.6.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Support for Custom NPM Modules in the Run Script operation in Flows has been removed in 10.6.0, see https://docs.directus.io/releases/breaking-changes.html#dropped-support-for-custom-npm-modules-in-the-run-script-operation-in-flows and https://github.com/directus/directus/releases/tag/v10.6.0.
