### ISSUE TITLE
How dynamic button or live preview 

### ISSUE THREAD

**Issue by haidv1992** [directus/directus#19600]
### Describe the Bug

![Screenshot_20230906-061603_Chrome](https://github.com/directus/directus/assets/86423592/f03706bd-bdc7-46c5-9107-c420d08d5caa)

How dynamic url like this  use variables  in environment. It is good for devlopment when deploy or migration  to staging or production

### To Reproduce

In live preview or button 

### Directus Version

V10.x x

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Thanks for opening the issue! However this concern should be submitted as a feature request, so do kindly open a [new feature request](https://github.com/directus/directus/discussions/new?category=feature-requests) instead. I'll proceed to close this issue, thanks again!
