### ISSUE TITLE
rest api with translations

### ISSUE THREAD

**Issue by haidv1992** [directus/directus#19611]
### Describe the Bug

from issue #19610 
then call api
![image](https://github.com/directus/directus/assets/86423592/033fd00a-0356-4514-ab5b-524a818e6654)

### To Reproduce

rest api with translations working not clear

### Directus Version

V10.6.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by ConnorSimply** [comment]
The `meta` parameter has been [depreciated](https://docs.directus.io/reference/query.html#metadata). Additionally, the meta parameter returns the TOP level number of items in the array. There are 11 "translations" items in that top level array in your screenshot. This is working as expected. You are deeply filtering the translations on each post, so your query currently gets all posts then in the translations field and filters one by one the translations returned for each post.
