### ISSUE TITLE
rest api not return files filed

### ISSUE THREAD

**Issue by haidv1992** [directus/directus#19614]
### Describe the Bug

in my record have field by field files but not return in rest api

![image](https://github.com/directus/directus/assets/86423592/47ef24e9-a32b-4f39-ac9d-4c2cb6240203)

### To Reproduce

rest api not return files filed

### Directus Version

V10.6.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Can you please share the whole query and corresponding data model?

**Comment by DanielBiegler** [comment]
Judging by visuals alone, you seem to be confusing the collection name with the accordion-group name. Take a look at your data model to find the real name, see:

![image](https://github.com/directus/directus/assets/14810858/bc7b3765-6732-4ab5-a882-4b226a5cef3b)

**Comment by paescuj** [comment]
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻
