### ISSUE TITLE
Continuous error accessing global settings after updating CMS logo

### ISSUE THREAD

**Issue by justindesjardins-thinkingbox** [directus/directus#1961]
After updating to Directus 6.4.4 I tried changing the CMS logo on the Global Settings screen. The logo has successfully changed, but an error popped up on the screen, and now persists every time I try to access the global settings.

The error is the following:

Uncaught TypeError: Cannot read property 'get' of undefined

## Version Info
  - Directus version and branch: 6.4.4
  - PHP version: 7.0.21
  - MySQL version: Ver 14.14 Distrib 5.6.37
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: Amazon Linux AMI 2017.09.0.20170930 x86_64 HVM GP2

## Expected Behavior
I should be able to access the global settings screen.

## Actual Behavior
Error shown in screenshot below pops up. And no settings are shown on the screen.

## Steps to Reproduce
 1. Run through update instructions in the docs to version 6.4.4
 2. Login to Directus, and change the CMS logo by uploading a local file
 3. Observe error pop  up and then persist on subsequent attempts to access settings.

## Schema Dump, Logs, or Screenshots

<img width="315" alt="screen shot 2017-11-21 at 9 28 21 am" src="https://user-images.githubusercontent.com/16246530/33089003-357d8174-cea4-11e7-8460-b28a5a19cce3.png">

**Comment by WellingGuzman** [comment]
Hey @justindesjardins-thinkingbox, make sure this has been fixed in `develop`.

Closed by https://github.com/directus/directus/commit/2c1135cbb44f4157d5e919527ec7baa8b06876ee

**Comment by justindesjardins-thinkingbox** [comment]
I can confirm this has fixed the issue. Thanks @WellingGuzman
