### ISSUE TITLE
Can't create new item with Slug field

### ISSUE THREAD

**Issue by dsivokhin** [directus/directus#1962]
## Version Info
  - Directus version and branch: master

## Actual Behavior

Create new item with slug field, have error, without slug field (if change to text_input) no error.

![default](https://user-images.githubusercontent.com/4669992/33124156-435b9d6e-cf8d-11e7-8e27-bab47ead8591.png)

![default](https://user-images.githubusercontent.com/4669992/33124138-31fae782-cf8d-11e7-8a6f-a53b4a8f7337.png)

**Comment by WellingGuzman** [comment]
Can you give us more information about this? I don't understand the issue.

**Comment by dsivokhin** [comment]
Hi @WellingGuzman, steps:
1)Create table with Text input and Slug field
2)Try create new item.
3)Fill "text input" field, "Slug" fied auto input from first field
4)Try save, see error

**Comment by WellingGuzman** [comment]
What version are you on? I'm not experiencing this in the latest version. can you try the last version `6.4.4`, If possible share a schema if still getting this issue on the latest version.

**Comment by dsivokhin** [comment]
@WellingGuzman, This issue played after update 6.4.24 on master. And 6.4.4 on develop too.
my dump - [test.zip](https://github.com/directus/directus/files/1505015/test.zip)

![default](https://user-images.githubusercontent.com/4669992/33255738-0291a798-d360-11e7-8169-a36b8438ad7b.png)

![default](https://user-images.githubusercontent.com/4669992/33255787-326c4fea-d360-11e7-9810-3509ad5cee17.png)

**Comment by WellingGuzman** [comment]
Please send a schema that we can use, I've not had luck trying to reproduce this, it's working as expected in my end.

**Comment by rijkvanzanten** [comment]
@WellingGuzman There is a zip in the previous comment, isn't that what you are looking for?

**Comment by WellingGuzman** [comment]
Oh true, somehow I missed that message when I read it.

Thanks @rijkvanzanten

**Comment by WellingGuzman** [comment]
This issue was fixed by https://github.com/directus/directus/commit/17467fd5a375c0914e80689c98d2789fe7c8e602

The user needs to install the `mbstring` php extension.
(Ref: http://php.net/manual/en/book.mbstring.php)

**Comment by rijkvanzanten** [comment]
Is that requirement documented somewhere @wellingguzman?

**Comment by WellingGuzman** [comment]
Yes, added by https://github.com/directus/docs/commit/39a1c8831e9a50405b7b7f6b8ca49a77ba5bbf7a
