### ISSUE TITLE
SDK - readItem not returning null/error when ID is empty

### ISSUE THREAD

**Issue by Sandros94** [directus/directus#19621]
### Describe the Bug

As discussed with @br41nslug on [Discord](https://discord.com/channels/725371605378924594/1121094628037361768/1149337923183972383), when you provide an empty `ID` to `readItem` it will fetch all the elements in the specified collection instead of returning null or error, wasting resources from the backend.

Ideally, since there is a clear difference between `readItem` and `readItems` it should check for the presence of `ID` before making the call. This would make conditional rendering of the response much simpler too.

### To Reproduce

Basic Nuxt repro:
```vue
<template>
  <div>
    Single Post by ID:
    <span>
      <input type="text" v-model="postId">
      <button @click="refreshPost()">
        Find Post
      </button>
    </span>
    <div v-if="singlePost">
      <h2>{{ singlePost.title }}</h2>
      <sub>{{ singlePost.id }}</sub>
      <p>{{ singlePost.content }}</p>
    </div>
    <pre v-else-if="error">{{ error }}</pre>
    <span v-else>No posts available</span>
  </div>
</template>

<script setup>
const client = createDirectus('http://directus.example.com').with(rest())

const postId = ref('')
const { data: singlePost, error, refresh: refreshPost } = await useAsyncData(
  async () => await client.request(readItem('posts', postId))
)
</script>
```

### Directus Version

sdk v11.0.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Sandros94** [comment]
I was about to open up a PR and add the following to `read/items.ts>readItem()`
```ts
if (!key) {
  throw new Error('Missing ID for readItem');
}
```

But then not only I realized this could be an issue on other read-related composables but on update/delete related ones too.

So instead of hardcoding that `if` into each one, wouldn't it be simpler to specify a list of composables that should require it?

Imagine someone forgetting to pass the id to one of them in a `for` loop...
API calls go **brrrrr**

**Comment by Sandros94** [comment]
Ok, looks like that `useAsyncData` brakes once it starts to fetch with a wrong/missing id, in particular its `refresh` function. This could be useful for some sort of search field.

**Comment by rijkvanzanten** [comment]
> So instead of hardcoding that if into each one, wouldn't it be simpler to specify a list of composables that should require it?

I'd prefer per-composable actually. Ideally those functions stay self-contained. As of right now, the client doesn't know / care about the individual functions, which also allows people to create their own if they wanted to. By hardcoding in lists of composables in the client itself we lose some of those benefits 👍🏻

**Comment by Sandros94** [comment]
> I'd prefer per-composable actually. Ideally those functions stay self-contained. As of right now, the client doesn't know / care about the individual functions, which also allows people to create their own if they wanted to. By hardcoding in lists of composables in the client itself we lose some of those benefits 👍🏻

So if I got you right: this would mean that making this logic pre-composable it could potentially apply to any custom composables made by people?
