### ISSUE TITLE
Segmentation fault - Custom Extension crashes Directus instance

### ISSUE THREAD

**Issue by Akanixon** [directus/directus#19620]
### Describe the Bug

Directus crashes the moment .upsertOne is being executed from within a Custom Extension

### To Reproduce

```js
const { ItemsService } = services;
const appointments = new ItemsService("appointments", { schema, knex: database });
await appointments.upsertOne(event.data);
```

Directus fully crashes the moment it reaches line 3 with a "Segmentation Fault" message

### Directus Version

v10.6.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
What does `event.data` contain in your example?

**Comment by Akanixon** [comment]
```json
[
	{
		"id": "1000053232",
		"status": "Completed",
		"type": "41358651",
		"date_created": "2023-03-09T16:55:34.000Z",
		"start": "2023-03-23T10:45:00.000Z",
		"date_updated": "2023-09-04T11:50:10.391Z",
		"user_created": null,
		"user_updated": null,
		"archived": null,
		"timezone": "Europe/London",
		"end": "2023-03-23T11:35:00.000Z",
		"duration": 50,
		"councellor": 825
	}
]
```

**Comment by br41nslug** [comment]
It definitely shouldnt crash but you can't pass an array of items to an upsert**One** function ;)

**Comment by Akanixon** [comment]
Sorry that array is coming from the export. The data supplied is just a singular item

**Comment by br41nslug** [comment]
Any more details you can provide for reproduction because just doing an `upsertOne` on a quickly constructed table based on the payload does not error for me.

Does adding a `.catch()` to ur upsertOne help or at least give a more info about error?

**Comment by Akanixon** [comment]
Sadly thats all: It doesn't even get to the point of being able to report:
![image](https://github.com/directus/directus/assets/22319382/ab963abd-949d-4465-8df6-9c597489446f)

**Comment by Akanixon** [comment]
I can now confirm this is happening without using custom extensions.
Just replicated that using Read Data and Run Script

**Comment by br41nslug** [comment]
Oh hmm thats interesting, and progress. Can you share the flow you've build to reproduce this? 😂

**Comment by Akanixon** [comment]
![image](https://github.com/directus/directus/assets/22319382/9560c370-39fd-42ec-96ec-30b76537b82d)
I don't mind sharing access to it

**Comment by DanielBiegler** [comment]
We'd need to see what the run scripts are doing so that we can hopefully replicate this locally for us. Could you please share a minimum working example? Much thanks! <3 :pray: 

Further question: Does the first one crash or the second one or both?

**Comment by Akanixon** [comment]
Scirpt 1:```js
module.exports = async function(data) {
	// Do something...
    let types = [];
    for (let type of data["$last"]){
    	types.push(type.appointmentTypes_id);
    }
	return types;
}
```

Script 2:```js
module.exports = async function (data) {
    let categories = data["types"]
        .map(t => t.category)
        .filter((item, index, arr) => {
            if (item != "" && item != "undefined") {
                return arr.indexOf(item) === index;
            }
        });

    let name = categories;
    let years = function (startYear = 2020) {
        var currentYear = new Date().getFullYear(), years = [];
        startYear = startYear || 1980;
        while (startYear <= currentYear) {
            years.push(`${startYear++}`);
        }
        return years;
    }

    let type = function () {
        let types = {};
        categories.forEach(element => {
            types[`${element}`] = data["types"].filter((t) => t.category == element).map((t) => { return { type_id: t.id, typeName: t.name } })
        });
        return types
    };

    return {ids: data["exec_9n9op"], name: name, year: years(), type: type() }
}
```

**Comment by Akanixon** [comment]
Additional info:
The error happens when a flow gets triggered with a parameter set => NOT if no parameter is set
The error happens in combination with read operations
Disconnecting and reconnecting sometimes fixes the problem

**Comment by DjLawRee** [comment]
Having same issue, while using custom extensions (hooks). Problem appeared after updating to 10.7.2

**Comment by Zerotredici** [comment]
Same issue on v.10.8.2 using a flow with the "Run script" operation.

**Comment by yassilah** [comment]
I can confirm I had the same issue with Directus 10.8.3 whenever a Flow included a "Run Script" operation. Switched from Node 20.x > 18.x and the issue seems to have disappeared.

**Comment by DanielBiegler** [comment]
It'd be much appreciated when someone that runs into this could write down a minimally reproducible example. Thanks! :smile:

**Comment by xyzones** [comment]
### Env
```fish
node -v
v20.11.0
PostgreSQL 15.4 
npx directus -v
10.9.0
```
### Steps

```fish
npm init directus-project@latest my-directus                                                                                                                                                                                            
cd my-directus
npx directus database migrate:latest
npx directus start
```

* Create a new tests model with a name field.
* Create a flow triggered by incoming hook POST all data
 *  add a read data node on test collection with 
```json
{
    "filter": {
        "name": {
            "_eq": "{{$trigger.body.data.name}}"
        }
    }
}
```
* add a run script 
```js
module.exports = function(data) {
  return {
    timesTwo: 2
  }
}
```
* hit endpoint

### result 

Server crashes, no response

```
{"level":10,"time":1707426096045,"pid":65576,"hostname":"my-mini.local","msg":"[4.394ms] select \"ip_access\" from \"directus_roles\" where \"id\" is null limit $1 [1]"}
{"level":10,"time":1707426096052,"pid":65576,"hostname":"my-mini.local","msg":"[2.724ms] select * from \"directus_permissions\" where \"role\" is null []"}
{"level":10,"time":1707426096062,"pid":65576,"hostname":"my-mini.local","msg":"[3.054ms] select \"id\" from \"directus_users\" where LOWER(\"email\") = $1 limit $2 [me@email.com, 1]"}
{"level":10,"time":1707426096066,"pid":65576,"hostname":"my-mini.local","msg":"[2.976ms] select \"u\".\"id\", \"u\".\"first_name\", \"u\".\"last_name\", \"u\".\"email\", \"u\".\"password\", \"u\".\"status\", \"u\".\"role\", \"r\".\"admin_access\", \"r\".\"app_access\", \"u\".\"tfa_secret\", \"u\".\"provider\", \"u\".\"external_identifier\", \"u\".\"auth_data\" from \"directus_users\" as \"u\" left join \"directus_roles\" as \"r\" on \"u\".\"role\" = \"r\".\"id\" where \"u\".\"id\" = $1 limit $2 [e677619d-92cd-4fc7-a0ce-a81530fefd9c, 1]"}
{"level":10,"time":1707426096070,"pid":65576,"hostname":"my-mini.local","msg":"[2.589ms] select \"directus_settings\".\"auth_login_attempts\", \"directus_settings\".\"id\" from \"directus_settings\" order by \"directus_settings\".\"id\" asc limit $1 [1]"}
{"level":10,"time":1707426096223,"pid":65576,"hostname":"my-mini.local","msg":"[19.002ms] insert into \"directus_sessions\" (\"expires\", \"ip\", \"origin\", \"token\", \"user\", \"user_agent\") values ($1, $2, DEFAULT, $3, $4, $5) [Thu Feb 15 2024 22:01:36 GMT+0100 (Central European Standard Time), 127.0.0.1, 9IkaJr-X_Tz0tQcWpZcHPMxXsLoro80sZtgNPRHQLkQu5V4zQtLkxeTQdBlUs6TB, e677619d-92cd-4fc7-a0ce-a81530fefd9c, insomnia/8.6.1]"}
{"level":10,"time":1707426096226,"pid":65576,"hostname":"my-mini.local","msg":"[2.977ms] delete from \"directus_sessions\" where \"expires\" < $1 [Thu Feb 08 2024 22:01:36 GMT+0100 (Central European Standard Time)]"}
{"level":10,"time":1707426096241,"pid":65576,"hostname":"my-mini.local","msg":"[3.912ms] insert into \"directus_activity\" (\"action\", \"collection\", \"ip\", \"item\", \"origin\", \"timestamp\", \"user\", \"user_agent\") values ($1, $2, $3, $4, DEFAULT, $5, $6, $7) returning \"id\" [login, directus_users, 127.0.0.1, e677619d-92cd-4fc7-a0ce-a81530fefd9c, Thu Feb 08 2024 22:01:36 GMT+0100 (Central European Standard Time), e677619d-92cd-4fc7-a0ce-a81530fefd9c, insomnia/8.6.1]"}
{"level":10,"time":1707426096264,"pid":65576,"hostname":"my-mini.local","msg":"[11.736ms] update \"directus_users\" set \"last_access\" = $1 where \"id\" = $2 [Thu Feb 08 2024 22:01:36 GMT+0100 (Central European Standard Time), e677619d-92cd-4fc7-a0ce-a81530fefd9c]"}
{"level":30,"time":1707426096564,"pid":65576,"hostname":"my-mini.local","req":{"id":1,"method":"POST","url":"/auth/login","query":{},"params":{},"headers":{"host":"localhost:8055","cookie":"--redacted--","content-type":"application/json","user-agent":"insomnia/8.6.1","accept":"*/*","content-length":"59"}},"res":{"statusCode":200,"headers":{"content-security-policy":"script-src 'self' 'unsafe-eval';worker-src 'self' blob:;child-src 'self' blob:;img-src 'self' data: blob:;media-src 'self';connect-src 'self' https://*;default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';object-src 'none';script-src-attr 'none';style-src 'self' https: 'unsafe-inline'","x-powered-by":"Directus","vary":"Origin, Cache-Control","access-control-allow-credentials":"true","access-control-expose-headers":"Content-Range","cache-control":"no-cache","content-type":"application/json; charset=utf-8","content-length":"449","etag":"W/\"1c1-1A6Pg6J0NP3JK2U0/3kGzZJXXq4\""}},"responseTime":547,"msg":"request completed"}
{"level":10,"time":1707426102199,"pid":65576,"hostname":"my-mini.local","msg":"[2.452ms] select \"ip_access\" from \"directus_roles\" where \"id\" = $1 limit $2 [c5563d29-8bfc-44a0-b597-422ebb8c8df4, 1]"}
{"level":10,"time":1707426102222,"pid":65576,"hostname":"my-mini.local","msg":"[3.493ms] select \"test\".\"id\", \"test\".\"status\", \"test\".\"sort\", \"test\".\"user_created\", \"test\".\"date_created\", \"test\".\"user_updated\", \"test\".\"date_updated\", \"test\".\"name\" from \"test\" where \"test\".\"name\" = $1 order by \"test\".\"sort\" asc limit $2 [undefined, 100]"}
fish: Job 1, 'npx directus start' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by paescuj** [comment]
@xyzones Could you try with Node.js 18 as this is the version we officially support at the moment: https://docs.directus.io/self-hosted/cli.html#requirements

**Comment by DanielBiegler** [comment]
Tried the mentioned steps

- Directus 10.9.0 fresh install prod, Sqlite, Node 20.10.0, Linux
  - Cant reproduce
- Directus 10.9.0 fresh install prod, Sqlite, Node 20.11.0, Linux
  - Cant reproduce
- Directus 10.8.3 Local Dev Mode, Sqlite, Node 18, Linux
  - Cant reproduce
- Directus 10.8.3 Locally built prod, Sqlite, Node 20.10.0, Linux
  - Cant reproduce

Tried both supplying data inside the POST and no data.

So the only difference I have should be the DB but that sounds highly unlikely?!

**Comment by rijkvanzanten** [comment]
@xyzones what operating system are you running on

**Comment by xyzones** [comment]
I am on mac.

v18 sqlite works ...
v20 sqlite fails ...

**Comment by rijkvanzanten** [comment]
@xyzones Didn't you say before you were testing on Postgres 15.4? Is this happening with Postgres, SQlite, or both?

**Comment by xyzones** [comment]
on v20 it is happening on sqlite and postgres

**Comment by xyzones** [comment]
@rijkvanzanten 

it crashes with api/src/operations/exec/index.ts:L26
```typescript 
const isolate = new ivm.Isolate({ memoryLimit: isolateSizeMb });
```

**Comment by sensedrive** [comment]
Got the same issue.

Starting directus with `npx --node-options='--no-node-snapshot' directus start` works for me. It is also mentioned here https://github.com/laverdet/isolated-vm/issues/424#issuecomment-1864629126.

**Comment by br41nslug** [comment]
> on v20 it is happening on sqlite and postgres

This is why Directus currently still requires `>18.17 <20`, but the mentioned isolated vm workaround can work in certain setups 😄

**Comment by sensedrive** [comment]
Good to know, but where is this documented?

https://docs.directus.io/self-hosted/cli.html#requirements not finding this information.
https://github.com/directus/directus/blob/b87530cc945142cd46e0c612b351c33efff7a088/package.json#L24 also not finding this informaton

**Comment by br41nslug** [comment]
It's a bit tricky in the wording but this is it: Node major version 18 specifically 18.17 or higher
![image](https://github.com/directus/directus/assets/9389634/0f289c64-cfca-4928-b2ec-ab839fada57b)
