### ISSUE TITLE
[SDK 11] RequestQuery Typescript fields '*.*'

### ISSUE THREAD

**Issue by marquetd** [directus/directus#19622]
### Describe the Bug

With previous sdk version , i use *.* in order to request all children of a object : 

```
{
    id,
    query: {
      fields: ['*.*'],
    }
}
```

With version 11, i have  a typescript error. 

I can use '\*' but not '\*.\*'

### To Reproduce

Make a request with field: ['*.*']

### Directus Version

v11.x

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
We very consciously made the decision not to support nesting wildcards in the SDK as it is an anti-pattern which causes a lot of performance issues for people going to production without refactoring out the wildcards.

Also the fields format for relational fields has changed slightly in the SDK to accommodate proper TypeScript types (the old version was breaking the TS engine trying to brute-force all possible field options recursively).

```
readItems('articles', {
  fields: ['title', 'date_created', { authors: ['*'] }],
})
```
