### ISSUE TITLE
Hebrew issues on API

### ISSUE THREAD

**Issue by neran** [directus/directus#1963]
Hebrew values are messed up on API calls due to json_encode function.
Fix: 
/api/core/Directus/Application/Application.php, line 140
Change
$response->setBody(json_encode($data));
To
$response->setBody(json_encode($data,JSON_UNESCAPED_UNICODE));

**Comment by WellingGuzman** [comment]
Hey @neran can you please show us some example that we can use to reproduce this?

**Comment by WellingGuzman** [comment]
Or better yet, if you have a way to fix it, we would love that fix in a PR.

**Comment by neran** [comment]
Sure, when I write Hebrew in a table and try to get the items by API, this is what I get:
![screenshot at nov 22 19-30-25](https://user-images.githubusercontent.com/576945/33141477-f3daa8a0-cfbb-11e7-8eef-f5d1e6405e8b.png)

After applying the fix, here's how it looks:
![screenshot at nov 22 19-31-26](https://user-images.githubusercontent.com/576945/33141502-048bf4e2-cfbc-11e7-91c9-5dc783b853eb.png)

Awesome software btw, really enjoy it.
Will try a PR.

**Comment by WellingGuzman** [comment]
Thanks @neran!

**Comment by WellingGuzman** [comment]
Hey @neran, I have took you fix and push it myself.

Thanks for the report and the fix.

Closed by https://github.com/directus/directus/commit/3efe10dd8ec7ac569f97bdff8d591562db5da232
