### ISSUE TITLE
directus.transport.post with composable SKD

### ISSUE THREAD

**Issue by dimitarkolev** [directus/directus#19631]
### Describe the Bug

How can we use the equivalent of directus.transport.post when using the new composabel SDK?

### To Reproduce

Missing anything about it in the documentation

### Directus Version

11.0.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
Like this, by putting custom request options inside `client.request`

```js
import { createDirectus, rest } from '@directus/sdk';

const client = createDirectus('http://directus.example.com').with(rest());

const result = await client.request(() => ({
    path: '/my-path',
    method: 'POST',
}));

console.log(result);
```

See https://docs.directus.io/packages/@directus/sdk/types-1/interfaces/interface.RequestOptions.html#interface-requestoptions for all request options.
