### ISSUE TITLE
Live Preview with translations not working

### ISSUE THREAD

**Issue by pacoccino** [directus/directus#19637]
### Describe the Bug

The live preview feature does not work when we use the translation feature. 
The preview window should propose a dropdown for selecting the language to see. 

As I want use slugs for article routing, and these slugs get translated and different for each languages, in the Preview URL I choose `BLOG_URL/(Translation->Slug)` but this got converted to the list of translated slugs instead of one (like `["slug-in-english", "slug-in-french"]`), so the page does not exist. 

### To Reproduce

Follow this translation guide
https://docs.directus.io/guides/headless-cms/content-translations.html

Then follow the Live preview guide
https://docs.directus.io/guides/headless-cms/live-preview/nextjs.html

Setup the preview URL to `BLOG_URL/(Translation->Slug)`

Open the preview, see that `Slug` is a string of an array of all the translated slugs.
The URL tried is `BLOG_URL/["slug-in-english", "slug-in-french"]`

### Directus Version

v10.6.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
I think we should add a new "placeholder" to the Preview URL which represents the current selected language.

**Comment by rijkvanzanten** [comment]
Heya! Thanks for opening this bug report. Seeing this is a new feature, rather than a bug in the currently intended behavior, I'd love it if you could open this as [a new feature request instead](https://github.com/directus/directus/discussions/new?category=feature-requests). Thanks!
