### ISSUE TITLE
Directus flow: require

### ISSUE THREAD

**Issue by deounix** [directus/directus#19646]
### Describe the Bug

Directus flow script `require` isn't defined.

### To Reproduce

In the Directus flow script and after adding the package to white_list I can't use require to import it I even tried the

`import {} from ''`

The require was working just fine in previous version v10.5.3

e.g.

`const { readFile } = require('fs')`

### Directus Version

10.6.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
Support for using node modules was dropped from the run script operation in [10.6](https://github.com/directus/directus/releases/tag/v10.6.0); see https://docs.directus.io/releases/breaking-changes.html#version-10-6
