### ISSUE TITLE
O2M creation error with Generated UUID type of primary field

### ISSUE THREAD

**Issue by resultatum** [directus/directus#19648]
### Describe the Bug

Hello, dear friends. Its a last stable directus in docker. And have this error when I try to create O2M relation. Help me out pls

```json
{
  "errors": [
    {
      "message": "alter table \"languages\" add constraint \"languages_language_foreign\" foreign key (\"language\") references \"language_codes\" (\"id\") on delete SET NULL - foreign key constraint \"languages_language_foreign\" cannot be implemented",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### To Reproduce

Create some collections in one folder with one field (string) + ordinary fields (sort, created by etc.) and try to add O2M relation.

### Directus Version

10.6.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by resultatum** [comment]
I restore back-up with 10.5.3 version but still have this error
{
  "errors": [
    {
      "message": "alter table \"languages\" add constraint \"languages_language_value_foreign\" foreign key (\"language_value\") references \"alphabets\" (\"id\") on delete SET NULL - foreign key constraint \"languages_language_value_foreign\" cannot be implemented",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

Im use postgres db

**Comment by resultatum** [comment]
I re-create collections, post data in it, and had same error
{
  "errors": [
    {
      "message": "alter table \"languages\" add constraint \"languages_language_title_foreign\" foreign key (\"language_title\") references \"iso_codes\" (\"id\") on delete SET NULL - foreign key constraint \"languages_language_title_foreign\" cannot be implemented",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

So, I can create O2M relations in collections created yesterday, but not  in a new collection

**Comment by resultatum** [comment]
If I change labels error still there
{
  "errors": [
    {
      "message": "alter table \"languages\" add constraint \"languages_title_foreign\" foreign key (\"title\") references \"iso_codes\" (\"id\") on delete SET NULL - foreign key constraint \"languages_title_foreign\" cannot be implemented",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

**Comment by resultatum** [comment]
So now I reinstall my db soft from postgis/postgis:13master to postgis/postgis:13-3.1-alpine. But still there


{
  "errors": [
    {
      "message": "alter table \"languages\" add constraint \"languages_code_foreign\" foreign key (\"code\") references \"iso_codes\" (\"id\") on delete SET NULL - foreign key constraint \"languages_code_foreign\" cannot be implemented",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

**Comment by resultatum** [comment]
So I try all I can. I try to reinstall image, restore a backup, change labels and names. But still have this error

**Comment by resultatum** [comment]
2023-09-11 07:18:54.225 UTC [106] ERROR:  foreign key constraint "languges_title_foreign" cannot be implemented
2023-09-11 07:18:54.225 UTC [106] DETAIL:  Key columns "title" and "id" are of incompatible types: character varying and uuid.
2023-09-11 07:18:54.225 UTC [106] STATEMENT:  alter table "languges" add constraint "languges_title_foreign" foreign key ("title") references "language_codes" ("id") on delete SET NULL

logs in database container

**Comment by resultatum** [comment]
So, one more think. I just make sure to keep consistent types for identifiers.
![image](https://github.com/directus/directus/assets/142282971/4776ba30-fbff-4980-85a4-e1a4ddf6d296)
![image](https://github.com/directus/directus/assets/142282971/09c5a044-87c3-4be6-b27e-8a5a2cffc8b3)

AND I STILL HAVE ERROR

But when I change type on manually entered string 
![image](https://github.com/directus/directus/assets/142282971/50a67048-4ccb-4137-ae32-9b2e73ce1b39)

its gone.

The question is why Directus dont let me create O2M with Generated UUID??

**Comment by DanielBiegler** [comment]
Hi there! Seems like you're trying to point from a uuid to something else (string) which doesnt work because theyre two different types. Creating a o2m means want to put the language.id into iso_codes.language_id so that multiple iso_codes point to the same language.

Is this really what you want? Or do you only want one language to have one iso_code?

If you want this, then simply do:

![image](https://github.com/directus/directus/assets/14810858/fd3b0acb-c762-48d1-af07-2b2c6ac4eefe)

typing the name in makes Directus create the column for you.

The docs have a page for understanding [relations](https://docs.directus.io/app/data-model/relationships.html) that might be helpful :)

Closing for now since this isnt a problem with Directus but happy to reopen if we uncover something different.

**Comment by resultatum** [comment]
Hi, Daniel!
Not in a first I try to create relations. And it was done successful when parent collection have manually entered string type of Primary Key Field.

In this case one language code can contain many languages. So I create collections languages and iso_codes. I dont have source of UUID for it, so I use generated UUID in BOTH collections.

1) I try to create O2M in collection  iso_codes. 
2) You think that Im trying to point from a uuid to something else (string), but Im not. 
![image](https://github.com/directus/directus/assets/142282971/5bf44733-45f1-4d4f-ab04-f847557c28d8)

![image](https://github.com/directus/directus/assets/142282971/59143837-7521-4524-867c-8dd4915ac80f)



In othe case I create O2M already. 
![image](https://github.com/directus/directus/assets/142282971/8a0e77a9-2561-40c6-baef-04a0d8042d63)

I do the same thing, and its work
![image](https://github.com/directus/directus/assets/142282971/53d15a47-869a-45bb-bb71-27f6c8d55970)

But in case of Telegram chats I will use Telegram chatID from Api, so I choose string
![image](https://github.com/directus/directus/assets/142282971/4407827b-3a38-4486-8a3a-021d5ac5bff6)


So, in case of language codes (and others) then I need Generated UUID Directus cant create relation
![image](https://github.com/directus/directus/assets/142282971/942fc5f5-ac4b-4cc4-ba6a-b3935954f752)

So, I already have the column that I need for relation. But with UUID it cant be created for some reason.

I will be grateful for your help

**Comment by DanielBiegler** [comment]
Foreign keys link to primary keys on the other table and vice versa in Directus relations to ensure uniqueness and reliability.

If for example you have the following items:

- iso_codes
  - id: 123
  - value: "en"
  - language_id: null

- languages
  - id: xyz
  - iso_codes: null

And now you want to link them, you will end up with the following:

- languages
  - id: **xyz**
  - iso_codes: [123]

- iso_codes
  - id: 123
  - value: "en"
  - language_id: **xyz**

This way the database can then guarantee via foreign-key constraint that **xyz** exists and warn/cascade for you.

You seem to want to relate to the value field which is something different.

Please see the [relation docs](https://docs.directus.io/app/data-model/relationships.html#one-to-many-o2m), they have a picture and description for this.
