### ISSUE TITLE
Can't upload a file

### ISSUE THREAD

**Issue by TyrionFront** [directus/directus#19650]
### Describe the Bug

Cannot upload a file using the [current directus-sdk functionality](https://docs.directus.io/packages/@directus/sdk/rest/functions/function.uploadFiles.html#type-parameters):

<img width="871" alt="Screenshot 2023-09-10 at 16 14 57" src="https://github.com/directus/directus/assets/18406903/fb1d7fbc-f21f-4fec-9007-20a4c274cb78">

"@directus/extensions-sdk": "^10.1.9",
"@directus/sdk": "^11.0.3",

### To Reproduce

``` 
import { stringify } from 'csv-stringify/sync';
import { toFormData } from 'axios';
...
private readonly directusClient = createDirectus(OPERATIONAL_BASE_URL)
		.with(rest())
		.with(staticToken(process.env.FILES_PROCESSOR_AUTH_TOKEN!));
...

prepareAndUploadCsvFile = async (fileName: string, data?: any[]) => {
		if (!data) {
			return;
		}
		const newCsv = stringify(data, { header: true });

		const filePath = getStoragePath(`${fileName}.csv`);
		await writeFile(filePath, newCsv, { encoding: 'utf-8' });

		const form = toFormData({});
		const folderId = await this.getCsvResultsFolderId();
		form.append('folder', folderId);
		form.append('file', createReadStream(filePath));

		try {
			const relevantDbRecord = await this.directusClient.request(uploadFiles(form));
			await unlink(filePath);

			return relevantDbRecord;
		} catch (error) {
			console.log('File uploading has failed:\n');
			console.error(error);
			throw error;
		}
	};
```

### Directus Version

10.6.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
`file` in `FormData` needs to be a `Blob`. See the following example:
```ts
import { createDirectus, rest, staticToken, uploadFiles } from '@directus/sdk';
import { readFileSync } from 'node:fs';

const client = createDirectus('https://directus.example.com')
  .with(rest())
  .with(staticToken('xyz'));

const title = 'test';
const file = new Blob([readFileSync('test.txt')]);

const formData = new FormData();
formData.append('title', title);
formData.append('file', file);

const result = await client.request(uploadFiles(formData));

console.log(result);
```

We'll add the example to the docs 👍

**Comment by TyrionFront** [comment]
> `file` in `FormData` needs to be a `Blob`. See the following example:
> 
> ```ts
> import { createDirectus, rest, staticToken, uploadFiles } from '@directus/sdk';
> import { readFileSync } from 'node:fs';
> 
> const client = createDirectus('https://directus.example.com')
>   .with(rest())
>   .with(staticToken('xyz'));
> 
> const title = 'test';
> const file = new Blob([readFileSync('test.txt')]);
> 
> const formData = new FormData();
> formData.append('title', title);
> formData.append('file', file);
> 
> const result = await client.request(uploadFiles(formData));
> 
> console.log(result);
> ```
> 
> We'll add the example to the docs 👍

TXS a lot 4 the response !
Honestly speaking, submitting the issue was the last planned way of solving the problem after spending some time in shaman dances around current docs part that is related to the desired result. And after making sure that there's nothing similar or close to it in your DIscord or here, in the issues list, I've left this problem here )

**Comment by TyrionFront** [comment]
@paescuj UPD:

With all the respect - it didn't work

<img width="869" alt="Screenshot 2023-09-11 at 01 42 15" src="https://github.com/directus/directus/assets/18406903/8baddf8f-b466-4704-91ed-5b562ee62397">

it's seems like there's still required a readable stream. But in that case we come back to what we've started from:
<img width="864" alt="Screenshot 2023-09-11 at 01 47 29" src="https://github.com/directus/directus/assets/18406903/bd37b7e1-dd45-49bb-9d49-ee61aa54a5d8">

**Comment by paescuj** [comment]
> TXS a lot 4 the response !
Honestly speaking, submitting the issue was the last planned way of solving the problem after spending some time in shaman dances around current docs part that is related to the desired result. And after making sure that there's nothing similar or close to it in your DIscord or here, in the issues list, I've left this problem here )

You're welcome and this is much appreciated! ❤️ The documentation was indeed missing a working example for the upload, so I've added it now in #19651 👍 

> With all the respect - it didn't work

I've tested my example code - it works 😃 

For you're code, you need ensure the variable you're passing in to `new Blob()` is compatible, see https://nodejs.org/api/buffer.html#new-bufferblobsources-options.

**Comment by TyrionFront** [comment]
> > TXS a lot 4 the response !
> > Honestly speaking, submitting the issue was the last planned way of solving the problem after spending some time in shaman dances around current docs part that is related to the desired result. And after making sure that there's nothing similar or close to it in your DIscord or here, in the issues list, I've left this problem here )
> 
> You're welcome and this is much appreciated! ❤️ The documentation was indeed missing a working example for the upload, so I've added it now in #19651 👍
> 
> > With all the respect - it didn't work
> 
> I've tested my example code - it works 😃
> 
> For you're code, you need ensure the variable you're passing in to `new Blob()` is compatible, see https://nodejs.org/api/buffer.html#new-bufferblobsources-options.

It's nice )
<img width="761" alt="Screenshot 2023-09-11 at 11 03 05" src="https://github.com/directus/directus/assets/18406903/9f379db8-06f3-4b20-92eb-0b2edc3ff7e3">
<img width="902" alt="Screenshot 2023-09-11 at 11 03 46" src="https://github.com/directus/directus/assets/18406903/67d185db-127b-4e26-89a6-2e8af9b00842">

But I'm still facing the same issue related to the ReadStream. I don't understand why in previous version of this API (screen) it worked just eazy-breezy

**Comment by paescuj** [comment]
Hard to tell without knowing the full code... I recommend you to get help from the community, e.g. on Discord. See also https://docs.directus.io/getting-started/support.html#community-support.

**Comment by muhsim** [comment]
When trying the above, I see the following error in the browser: `Error: Module "node:fs" has been externalized for browser compatibility. Cannot access "node:fs.readFileSync" in client code.`

I am running the code in an SPA (SvelteKit).

**Comment by paescuj** [comment]
`node:fs` is a Node.js built-in module [^1] which you cannot use outside of Node.js. You need to rely on client side APIs to get the file resp. build the form data.

[^1]: https://nodejs.org/api/fs.html
