### ISSUE TITLE
"require is not defined" in "Run Script" flow's operation

### ISSUE THREAD

**Issue by alexey-yarmosh** [directus/directus#19661]
### Describe the Bug

I am trying to configure directus flow to handle github events using webhooks from gh. For that I need to validate the webhook using the token from gh and node's 'crypto' module.

<img width="676" alt="image" src="https://github.com/directus/directus/assets/16905445/2dd8ffbb-4922-4847-aa75-30db474431b5">

But that is not working, I am getting 'require is not defined' error.

<img width="680" alt="image" src="https://github.com/directus/directus/assets/16905445/a4984b9e-1ee8-49ed-ba95-49543d0fda07">

import statement doesn't work too.

### To Reproduce

Add a code with a require statement as an "operation" of the "flow".

### Directus Version

v10.6.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
The Run Script operation doesn't support importing modules for security reasons. Use a custom operation instead if you need access to node modules 👍🏻

**Comment by alexey-yarmosh** [comment]
Thanks
