### ISSUE TITLE
Foreign key relation M2O - wrong colomn

### ISSUE THREAD

**Issue by blackmotion55** [directus/directus#19663]
### Describe the Bug

Hello 🙂
i'm struggling with something i thought would be simple
My Directus is connected to a MySQL DB
i have a table prono_tip linked to a table match_db 
prono_tip.match_api_id (varchar) = match_db.api_id (varchar)
the FK in prono_tip is well configured.
But Directus links automatically to the match_db.id (primary) (int)

![CleanShot 2023-09-11 at 16 19 18@2x](https://github.com/directus/directus/assets/109959443/f0b5074a-beb1-4d48-994e-32e362aa1366)
![CleanShot 2023-09-11 at 16 20 45@2x](https://github.com/directus/directus/assets/109959443/315faa9b-0f19-4ffe-a010-46985a165109)

### To Reproduce

have a database with 2 tables linked via a FK string, 
with the table ONE having a int ID primary

[database.sql.zip](https://github.com/directus/directus/files/12578622/database.sql.zip)

### Directus Version

v10.6.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
Foreign keys link to primary keys on the other table and vice versa in Directus relations to ensure uniqueness and reliability. Feel free to open a [feature request](https://github.com/directus/directus/discussions/categories/feature-requests) for adding non-primarykey relations.
