### ISSUE TITLE
Payload is empty when using Flow with Action and items.create

### ISSUE THREAD

**Issue by ravi-2912** [directus/directus#19672]
### Describe the Bug

When running a Flow with Trigger Event Hook, Action (Non-Blocking) and scope as `items.create`, the `$trigger`  contains empty payload.

### To Reproduce

1. Create a collection name `Test`
2. Add two fields `name` and `channel` with default values TEST_NAME and TEST_CHANNEL
3. Create a Flow named `test`
4. In the Flow's Trigger Setup select `Event Hook` 
5. Select `Action (Non-Blocking)`
6. In Scope select `items.create`
7. In Collections select `Test`
8. Press tick mark on top right
9. Then add an operation Log to Console with Message as `{{$trigger}}`
10. Save the flow

Then create an item in `Test` collection and look at logs. The `$trigger` will be printed with actual value with `payload:{}` i.e. empty payload.

Actual Output
```
INFO: {"event":"test.items.create","payload":{},"key":1,"collection":"test"}
```

Expected Output
```
INFO: {"event":"test.items.create","payload":{"name":"TEST_NAME","channel":"TEST_CHANNEL"},"key":1,"collection":"test"}
```

![image](https://github.com/directus/directus/assets/25941167/af3361e8-d1c7-49ec-8249-574e5e791ec1)
![image](https://github.com/directus/directus/assets/25941167/fbdffb49-cc6c-4710-84f5-b9630cdc5bc0)

### Directus Version

v10.6.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by ravi-2912** [comment]
On Discord Tim (Brainslug) advised that default values do not hit the API hence, payload is empty. Don't you think this should not be the case. 
I tried another test, and noted the if I enter some text (other than default in field `name` whereas leave `channel` field, then I only get `name` field in the payload.

This seems inconsistent to me.

**Comment by ravi-2912** [comment]
Right I get it after little thinking over. Please ignore my comment.

**Comment by br41nslug** [comment]
If you rely on the default values you'll want to read the complete object with the `Read Data` operation instead of relying on the partial event payload.

**Comment by paescuj** [comment]
For reference, recently submitted identical issue: #19360
