### ISSUE TITLE
`npx directus init` doesn't install Directus as a dependency

### ISSUE THREAD

**Issue by Natetronn** [directus/directus#19674]
### Describe the Bug

_Note: I'm not sure if this is a bug, by design or should be a feature request._

When installing Directus (non-docker) via `npx directus init`, it doesn't install Directus as a dependency in package.json, only the database driver is present. You have to then run `npm install directus` for it to also be added.

https://docs.directus.io/self-hosted/cli.html#initialize-a-new-project

Aside: it also requires the creation of a package.json using `npm init`, and half way errors out if not done first, and although I see the note in the docs about that, perhaps it could offer to create it for us, if one isn't present. 

### To Reproduce

```
mkdir directus-test
cd directus-test
npm init
npx directus init
nano package.json
```
Then notice there is no `"directus": "^10.6.1",` in the dependencies object.
### Directus Version

v10.6.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by Natetronn** [comment]
As a quick "fix", perhaps the docs could be adjust to include:

```
npm init
npx directus init
npm install directus
```

(yarn, pnpm, bun etc.)

**Comment by br41nslug** [comment]
`npm init directus-project [Folder Name]` is the way to go for starting a new project

**Comment by Natetronn** [comment]
@br41nslug is there a reason `npx directus init` is listed in the docs instead of the `npm init directus-project [Folder Name]`?

https://docs.directus.io/self-hosted/cli.html#initialize-a-new-project

Happy to PR the docs, but don't know if there is something I'm missing here.

**Comment by rijkvanzanten** [comment]
Good point @Natetronn. `create-directus-project` is a mini-library that will create a new folder, install `directus` and run `npx directus init` on your behalf. Running `npx directus init` directly requires `directus` to already exist in the folder's `node_modules` somewhere. Both need some tender love and care!

**Comment by rijkvanzanten** [comment]
The goal was to funnel people to the docker container where possible, as that's so much more fool-proof (as you have none of the environment specific issues), but increasingly people are looking for the "raw" option of just running it in straight node, so I think it's time to revisit those helper installers and make that a little easier again too

**Comment by Natetronn** [comment]
I think it's wise to funnel to Docker when possible; I use the Docker version myself. For updates, avoiding differences between machines and all around portability etc. it seems like the better choice. 

I was going over the "raw" option to better help someone in the Discord, who struggling to to use that option to install. That's when I tested it and realized there was this anomaly.
