### ISSUE TITLE
Typing errors with readItems, createItems, and maybe all rest commands... in SDK

### ISSUE THREAD

**Issue by johnny9144** [directus/directus#19676]
### Describe the Bug

I'm using `webpack` + `ts-loader` with Directus SDK in our project when I tried to migrate SDK to the latest version. Both `ts-loader` and `ts-language-server` cannot load the correct type definitions.

### Issue Screenshot
![image](https://github.com/directus/directus/assets/11556489/e056ed2c-b3ca-4919-b436-d095139809e1)
![image](https://github.com/directus/directus/assets/11556489/5c5fcaf8-880b-4e2d-9a04-60b255cb1e68)

### The way I import the SDK
`import { createDirectus, authentication, rest, readItem } from "@directus/sdk";`

I also tried to import sdk like below as you officially recommended at the beginning. but it didn't work as well.

```
import { createDirectus, authentication } from "@directus/sdk";
import { rest, readItem } from "@directus/sdk/rest";
```

### To Reproduce

Here is the [project](https://github.com/johnny9144/directus-sdk-bug-with-webpack-and-tsloader) that reproduces the issue. 

```
import { createDirectus, authentication, rest, readItem } from "@directus/sdk";

async function getCmsClient({ url, email, password }) {
  const client = createDirectus(url).with(authentication()).with(rest());

  await client.login(email, password, {});

  return client;
}

async function run() {
  const client = await getCmsClient({
    url: "http://localhost:8055",
    email: "random",
    password: "random",
  });

  const result = await client.request(
    readItem("random", "2072d782-9ed5-4f65-9a87-36a233ae8333")
  );

  console.log(result);
}

run();
```

### Directus Version

v10.6.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by johnny9144** [comment]
BTW, you might not be able to get the error on vscode.

**Comment by alexvdvalk** [comment]
I can reproduce. Upgrading to typescript 5 solves the issue. Is this a viable solution for you?

**Comment by br41nslug** [comment]
Typescript 5.0 or higher is required for the SDK

**Comment by johnny9144** [comment]
Upgrading to Typescript 5 does fix the bugs, Thanks for your prompt assistance.
