### ISSUE TITLE
No visual feedback when deleting M2M elements

### ISSUE THREAD

**Issue by newah** [directus/directus#1968]
## Version Info
  - Directus version and branch: 6.4.2 release
  - PHP version: 7.1.6-1
  - MySQL version: 14.14
  - Web server: Apache
  - OS name and version: Ubuntu 16.04

## Expected Behavior
Visually remove elements from M2M list (i.e. have 4 speakers. Press X on one, should see effect). No errors in the console.

## Actual Behavior
Visually removed element is still there. After saving, removed element disappears.

## Steps to Reproduce
 1. Add elements to M2M list.
 2. Choose "Save and stay".
 3. Try to remove newly added element.

**Comment by WellingGuzman** [comment]
Hey @newah, can you try using the most recent releases? or can you share a example schema that we can use to reproduce this issue?

**Comment by newah** [comment]
@WellingGuzman wasn't able to exclude sensitive company information from the schema... But got to the bottom of this - junction tables were missing Status field ;)
