### ISSUE TITLE
Extending select-dropdown-m2o error: `TypeError: Cannot read properties of undefined (reading 'includes')`

### ISSUE THREAD

**Issue by Crunchyman-ralph** [directus/directus#19689]
### Describe the Bug

Hey Guys!

I am trying to create an extension where I want to use the interface `select-dropdown-m2o` but everytime I try to load it I get an error like this:
`TypeError: Cannot read properties of undefined (reading 'includes')`

here is my code:
```tsx
<template>
  <component :is="SelectDropdownM2o" v-bind="componentAttrs.value" />
</template>

<script setup lang="ts">
import { useExtensions } from "@directus/extensions-sdk";
import { computed } from "vue";
import { Filter } from "@directus/types";

const props = withDefaults(
  defineProps<{
    value?: number | string | Record<string, any> | null;
    collection: string;
    field: string;
    template?: string | null;
    selectMode?: "auto" | "dropdown" | "modal";
    disabled?: boolean;
    filter?: Filter | null;
    enableCreate?: boolean;
    enableSelect?: boolean;
  }>(),
  {
    value: null,
    selectMode: "auto",
    disabled: false,
    template: null,
    filter: null,
    enableCreate: true,
    enableSelect: true,
  }
);

const { interfaces } = useExtensions();

console.log({ interfaces });

const selectedInterface = interfaces.value.find(
  (i) => i.id === "select-dropdown-m2o"
);

if (!selectedInterface) {
  throw new Error("Interface select-dropdown-m2o not found.");
}

const SelectDropdownM2o = selectedInterface.component;

const componentAttrs = computed(() => {
  return {
    ...props,
  };
});
</script>
```

I wasn't having this issue literally 2 minutes ago, and all of the sudden without changing anything I was having issues, and the code is minified for some reason, so I am not even able to follow the stack trace.

If anyone knows a potential solution, please let me know!

### To Reproduce

Take my code and try to use it inside an extension

### Directus Version

v10.6.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
I doubt this is an issue with the Directus core 😬 closing this issue for now as this was also asked in discord
