### ISSUE TITLE
TransportError: Invalid payload. File is missing filename.

### ISSUE THREAD

**Issue by braco** [directus/directus#19683]
### Describe the Bug

Getting this error when trying to programmatically upload through js sdk: `TransportError: Invalid payload. File is missing filename.`

Coming from here?: https://github.com/directus/directus/blob/ac43a4322319dd0c2eda13076e28a2efa8d18093/api/src/controllers/files.ts#L78C8-L80

Documentation doesn't say anything about supplying a filename except that the [two filename fields will be ignored](https://docs.directus.io/reference/files.html#upload-a-file), so I'm confused by this error message. It seemed to start after upgrading to 10.6.0.

It would be nice if the sdk handled file uploads and downloads, it's currently a chore to find the right order/balance of everything to get that working.

### To Reproduce

```
  const form = new FormData();
  form.append('folder', folder);
  // Does this need to exist? Seems to be ignored.
  form.append('filename', fileName);
  form.append('title', title);
  form.append('file', fileData);

   directus.files.createOne(
    form,
    { },
    {
      requestOptions: {
        headers: {
          ...form.getHeaders(),
        },
      },
    },
  );
```

### Directus Version

10.6.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by braco** [comment]
I guess this is the fix:

```
  form.append('file', fileData, fileName);
```

I'm going to leave this open as a request for documentation – this is frustratingly esoteric, and I found the solution on a random page:

https://forums.appgyver.com/t/uploading-file-to-directus-multipart-form-data/11271/2

**Comment by br41nslug** [comment]
Closing this issue as this is well documented behavior of `FormData` https://developer.mozilla.org/en-US/docs/Web/API/FormData/append
