### ISSUE TITLE
When generating tables with the primary key of type `uuid` directus should set `default gen_random_uuid()` on the primary key

### ISSUE THREAD

**Issue by hrastnik** [directus/directus#19682]
### Describe the Improvement

Currently, when we create a new data model we can select the primary key type. One of these options is `Generated UUID`.

When we select this option, the resulting table doesn't have a default constraint.

This proves a problem when we're accessing the database through other tools. In my case, I'm trying to insert some values into the database using [Drizzle ORM](https://github.com/drizzle-team/drizzle-orm) but am unable to do so.

One solution would be to set the default constraint on the primary key when creating a new data model.

Another solution would be to explicitly enable setting functions as default values through the directus UI. Currently values like `now()` and `CURRENT_TIMESTAMP` are custom handled in the code. This could be expanded to handle more values, or alternatively - a dropdown could be implemented when creating a new data model that would have different functions the user could chose from.

**Comment by br41nslug** [comment]
Im closing this issue because I believe this is more than a tiny tweak and deserves to be a [Feature Request](https://github.com/directus/directus/discussions/new?category=feature-requests) instead to discuss through the implementation details across the supported database vendors.
