### ISSUE TITLE
ManyToOne Relationship on existing database

### ISSUE THREAD

**Issue by pravk** [directus/directus#1969]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus version and branch: 6.4.4
  - PHP version: 7.1
  - MySQL version: 5.6
  - Web server: nginx
  - OS name and version: OSX/Ubuntu 16

## Expected Behavior
Many to one relationship should work on existing database tables

## Actual Behavior
Listing page fails with "Undefined Index index_name"

## Steps to Reproduce
 1. Create a database with 2 tables ps_entity_attribute_meta and ps_entity_attribute_value  (schema attached).
 2. Install Directus and configure it to use the database
 3. Manage the tables 
 4. Modify ps_entity_attribute_value.id_entity_attribute_meta column to Many-to-one relationship with ps_entity_attribute_meta.id_entity_attribute_meta
 5. Try to navigate to ps_entity_attribute_value table entries.

## Schema Dump, Logs, or Screenshots

```sql
-- Create syntax for TABLE 'ps_entity_attribute_meta'
CREATE TABLE `ps_entity_attribute_meta` (
  `id_entity_attribute_meta` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `entity_name` varchar(100) NOT NULL DEFAULT '',
  `attribute_name` varchar(200) NOT NULL DEFAULT '',
  `attribute_type` int(11) NOT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `date_add` datetime NOT NULL,
  `date_upd` datetime NOT NULL,
  `attribute_group` varchar(100) DEFAULT 'Default',
  PRIMARY KEY (`id_entity_attribute_meta`),
  KEY `entity_name` (`entity_name`),
  KEY `entity_name_2` (`entity_name`,`attribute_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'ps_entity_attribute_value'
CREATE TABLE `ps_entity_attribute_value` (
  `id_entity_attribute_value` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `id_entity` int(11) NOT NULL,
  `id_entity_attribute_meta` int(11) NOT NULL DEFAULT '0',
  `attribute_value` longtext,
  `date_add` datetime NOT NULL,
  `date_upd` datetime NOT NULL,
  PRIMARY KEY (`id_entity_attribute_value`),
  KEY `id_entity` (`id_entity`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
<img width="1580" alt="screen shot 2017-11-25 at 7 44 19 am" src="https://user-images.githubusercontent.com/926011/33226472-83ea4a32-d1b4-11e7-8e41-22a22db2ec44.png">

**Comment by WellingGuzman** [comment]
Hey @pravk would help a lot if you share the schema that we can use to reproduce this issue.

**Comment by pravk** [comment]
Please check the schema dump in the issue. I have attached schema of the two tables.

**Comment by WellingGuzman** [comment]
thanks @pravk, but I'd need to have the `directus_columns`  records for those specific tables and if any, the records on `directus_tables`, otherwise I won't get the relationship some of those columns have.

**Comment by pravk** [comment]
Please find the records in directus columns below:

`INSERT INTO `directus_columns` (`id`, `table_name`, `column_name`, `data_type`, `ui`, `relationship_type`, `related_table`, `junction_table`, `junction_key_left`, `junction_key_right`, `hidden_input`, `required`, `sort`, `comment`, `options`)
VALUES
	(42, 'ps_entity_attribute_meta', 'id_entity_attribute_meta', NULL, 'primary_key', NULL, NULL, NULL, NULL, NULL, 0, 1, 1, '', '[]'),
	(43, 'ps_entity_attribute_value', 'id_entity_attribute_value', NULL, 'primary_key', NULL, NULL, NULL, NULL, NULL, 0, 1, 1, '', '[]'),
	(44, 'ps_entity_attribute_value', 'id_entity_attribute_meta', 'INT', 'many_to_one', 'MANYTOONE', 'ps_entity_attribute_meta', NULL, NULL, 'id_entity_attribute_meta', 0, 0, 3, '', '{\"id\":\"many_to_one\",\"visible_column\":\"attribute_name\",\"visible_column_template\":\"{{attribute_name}}\",\"result_limit\":\"81\",\"allow_null\":0,\"filter_column\":\"attribute_name\"}');
`

directus_tables don't have have records specific to my tables.

**Comment by WellingGuzman** [comment]
Thanks I will give it a shot now.

**Comment by WellingGuzman** [comment]
Hey @pravk, this issue has been fixed by https://github.com/directus/directus/commit/cea3f7563443135e93546afecdd9e966d49d4f13

Otherwise please confirm.

**Comment by pravk** [comment]
@WellingGuzman thanks a lot for fixing. Confirmed working.
