### ISSUE TITLE
Cannot retrieve data from a many to many field

### ISSUE THREAD

**Issue by DavidGrd69** [directus/directus#19697]
### Describe the Bug

I tried to request some fields from a model. Simple fields work fine, but for a many to many field, I cannot access to targeted m2m model fields.

### To Reproduce

One model A
One model B
A has a many to many field => stock a list of ids of B
B has field called name

Request by API A with fields: '*, B.name'
I tried many ways to write this request,  even with <m2a-field>:<collection-scope>.<field> from your doc
I get all fields from A but none from B.
I tried with one to many field too

Either I have a config problem, or the doc is not complete

### Directus Version

10.6.1

### Hosting Strategy

Directus Cloud

**Comment by DanielBiegler** [comment]
Hey there! First, make sure you have configured your permissions correctly to have read access to all relevant collections. Second, a many-to-many field uses a junction table where you can get your items like so:

```?fields=m2m.b_id.name```

that should result in you seeing all the B names.

**Comment by DavidGrd69** [comment]
Thanks, it worked. the junction table was not permit
