### ISSUE TITLE
Search is not normalized

### ISSUE THREAD

**Issue by ruihildt** [directus/directus#19698]
### Describe the Bug

Using the graphql API (or directly in the Directus dashboard), if I search for "Lowenthal" or "lowenthal", it won't find "Löwenthal" of the term if my text fields.

### To Reproduce

- Create an item containing the text "Löwenthal"
- Search for "lowenthal" in the collection corresponding to the created item
- Nothing is found

### Directus Version

v10.6.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by DanielBiegler** [comment]
This could be an enhancement to the search filters but comes with a performance cost and has to be investigated further in terms of support of database vendors, what kind of diacritics you'd like to support and more questions. If you really would like to see this feature implemented please open a [Feature Request](https://github.com/directus/directus/discussions/new?category=feature-requests).

**Comment by ruihildt** [comment]
> This could be an enhancement to the search filters but comes with a performance cost and has to be investigated further in terms of support of database vendors, what kind of diacritics you'd like to support and more questions. If you really would like to see this feature implemented please open a [Feature Request](https://github.com/directus/directus/discussions/new?category=feature-requests).

As long as you're an English speaking country, then you mostly don't care about it. But as soon as you have to support latin-based language (most of Europe to start with), then it is necessary.

In terms of diacritics, I am interested in French specifically, but the problem is present for all latin-based languages.that's obviously not a language specific issue.

**Comment by ruihildt** [comment]
See: https://github.com/directus/directus/discussions/19699

**Comment by DanielBiegler** [comment]
It's not a complete fix but for the meantime maybe using the wildcard character is enough for your specific usecase, see:

![image](https://github.com/directus/directus/assets/14810858/538f5a3f-5a68-436c-851b-906aae739c83)

Careful with matching too much though, it depends on the usecase. Cheers.

**Comment by ruihildt** [comment]
@DanielBiegler Thanks that seems helpful. Is it possible to match only a single character?

**Comment by ruihildt** [comment]
(answering myself: use the `_` char instead)
