### ISSUE TITLE
jquery-1.11.0.js:9666 GET .... 404()

### ISSUE THREAD

**Issue by RudolfFussek** [directus/directus#1970]
Hey,

when I go in the table site, then I have an error:

https://imgur.com/a/lz2Xc

**Comment by WellingGuzman** [comment]
Hey @RudolfFussek, what version are you using? and can you share a schema that we can use to reproduce this issue?

Can you also verify what's the output of that request?

**Comment by RudolfFussek** [comment]
Hey @WellingGuzman, version 6.4.0

Hier a GIF:

http://www.giphy.com/gifs/l2RnyEwbWspXmAlva

**Comment by WellingGuzman** [comment]
can you try to upgrade to `6.4.4` and see if it still happens?

**Comment by RudolfFussek** [comment]
How can I do that? x.x

**Comment by RudolfFussek** [comment]
I have do it. Same error 😢

**Comment by RudolfFussek** [comment]
I have found the error. It was the wrong url in the settings o.O.... Sorry and thanks for your help!

#1503

**Comment by RudolfFussek** [comment]
I have another error when I will make a Dropdown ENUM.

https://imgur.com/a/hSjft

**Comment by BennerGe** [comment]
I think this issue should help you: 
https://github.com/directus/directus/issues/1925

**Comment by RudolfFussek** [comment]
Thanks!
