### ISSUE TITLE
Cannot change timezone of user to Europe/Bern

### ISSUE THREAD

**Issue by magbeat** [directus/directus#1971]
## Version Info
  - Directus version and branch: develop branch (a54043c955f0292bb1e3895ca5d9c043b2f45a96)
  - PHP version: 5.6.31
  - MySQL version: 10.1-MariaDB
  - Web server: Apache
  - OS name and version: unknown (Hoster) 

## Expected Behavior

Change the Timezone of a User. Everything works.

## Actual Behavior

If we change the timezone of a user to Bern the following error is shown in the browser.

## Steps to Reproduce
 1. Create a user
 2. Set the timezone of the user to Bern
 3. Log in with the newly created user

## Schema Dump, Logs, or Screenshots

`Fatal error: Uncaught exception 'Exception' with message 'DateTimeZone::__construct() [<a href='http://php.net/manual/en/datetimezone.construct.php'>datetimezone.construct.php</a>]: Unknown or bad timezone (Europe/Bern)' in /home/bwmadmin/www/api.bwm.ch/api/core/Directus/Util/DateUtils.php:135 Stack trace: #0 /home/bwmadmin/www/api.bwm.ch/api/core/Directus/Util/DateUtils.php(135): DateTimeZone->__construct('Europe/Bern') #1 /home/bwmadmin/www/api.bwm.ch/api/core/Directus/Database/TableGateway/BaseTableGateway.php(997): Directus\Util\DateUtils::convertToISOFormat('2017-11-28 09:1...', 'UTC', 'Europe/Bern') #2 /home/bwmadmin/www/api.bwm.ch/api/core/Directus/Database/TableGateway/BaseTableGateway.php(1038): Directus\Database\TableGateway\BaseTableGateway->convertDates(Array, Object(Directus\Database\Object\Table), 'directus_users') #3 /home/bwmadmin/www/api.bwm.ch/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(904): Directus\Database\TableGateway\BaseTableGateway->parseRecord(Array) #4 /home/bwmadmin/www/ in /home/bwmadmin/www/api.bwm.ch/api/core/Directus/Util/DateUtils.php on line 135`

**Comment by WellingGuzman** [comment]
I'm checking, and there's not `Europe\Bern` timezone in php. Ref: http://php.net/manual/en/timezones.europe.php

The array timezone should be flipped, so the value is the timezone. Europe\Bern used to use `Europe\Berlin` timezone

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/039128683e4144460b1c109acb2256bd7dd62a74
