### ISSUE TITLE
Add more clarity to ROOT_REDIRECT and SERVE_APP settings in the config

### ISSUE THREAD

**Issue by jeremyzilar** [directus/directus#19724]
### Page

https://docs.directus.io/self-hosted/config-options.html

### Describe the Inaccuracy

As a new Directus user, I was trying to figure out if Directus could be hosted at a route other than `./admin`. The configuration currently docs seem to imply that it is possible through `ROOT_REDIRECT` and `SERVE_APP`, or that is how I read it. https://docs.directus.io/self-hosted/config-options.html

> `ROOT_REDIRECT` — Where to redirect to when navigating to /. Accepts a relative path, absolute URL, or false to disable.
> `SERVE_APP` — Whether or not to serve the Admin App under /admin.

The descriptions on those settings read as though they might be relevant to hosting the app at a different URL, when in fact they do not do this.

Thanks to Dominic in the Discord channel for explaining those two features to me. https://discord.com/channels/725371605378924594/1153023317691879535/1153206349342187520

**Comment by br41nslug** [comment]
The serve_app description could indeed be more clear but i dont see the issue with ROOT_REDIRECT.

Changing the SERVE_APP description to something like 
> Enables or disables serving the Admin App.
