### ISSUE TITLE
"Save and add" shows unsaved changes message

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1973]
## Version Info
  - Directus version and branch: 6.4.4

## Expected Behavior
Clicking save and add instead of the regular save saves the current and opens a new edit view

## Actual Behavior
Admin shows the unsaved changes warning, but saves regardless and continues execution as expected

## Steps to Reproduce
 1. Add a new row to a table
 2. Select save and stay in the top right

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/fc127c54e56cce5950318d977c8416c2b9f097d1
