### ISSUE TITLE
"Breaks" shouldn't show up in column list

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1974]
I'm not sure how we would flag these, but section breaks should not be included in the sidebar on the Item Listing page. They are not data, just presentation items for the detail page. 

Any thoughts @rijkvanzanten @WellingGuzman ?

![screen shot 2017-11-29 at 4 58 18 pm](https://user-images.githubusercontent.com/522079/33401267-b52aa87e-d526-11e7-9da7-0b0ca49d8ae2.png)

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/pull/2016/commits/51eba4edad70ffa4fc8e4aa7e9ef78feba1ab35c
