### ISSUE TITLE
Service unavailable when uploading file or image

### ISSUE THREAD

**Issue by robamon** [directus/directus#19742]
### Describe the Bug

![error uploading image](https://github.com/directus/directus/assets/136369652/cc80d9b1-479b-4d67-911c-e26cea7bff69)

### To Reproduce

File -> Add file

### Directus Version

v10.6.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
There's not nearly enough information presented here for us to reproduce or help debug. Please include the full error that was thrown in both app and api logs as well. Thanks!

**Comment by robamon** [comment]
Good day,

The error occurs when I try to upload a file/ image under the *File Library*.
From the attached activity log screenshot, the file is uploaded and deleted
instantaneously. Thereafter a *Service Unavailable* error is presented as
attached.

I hope this helps.

Regards

**Comment by robamon** [comment]
![activity log error](https://github.com/directus/directus/assets/136369652/d56fe1ea-7ab6-4099-a501-a3a301dd36a5)

**Comment by DanielBiegler** [comment]
@robamon please provide error logs from your terminal that runs Directus as that may help us actually see where the problem occurs.

- Have you checked that Directus has read+write permissions for the upload folder?
- What storage adapter are you using?
- Any other customizations you supplied via env-variables?

It's very hard to help you if you don't provide any information.

**Comment by robamon** [comment]
As you had suspected, it was a permission issue...
`[11:07:37.180] WARN: Couldn't save file e8d57029-814b-4256-929e-caa492f64b1c.png
[11:07:37.180] WARN: EACCES: permission denied, open '/directus/uploads/e8d57029-814b-4256-929e-caa492f64b1c.png'
    err: {
      "type": "Error",
      "message": "EACCES: permission denied, open '/directus/uploads/e8d57029-814b-4256-929e-caa492f64b1c.png'",
      "stack":
          Error: EACCES: permission denied, open '/directus/uploads/e8d57029-814b-4256-929e-caa492f64b1c.png'
      "errno": -13,
      "code": "EACCES",
      "syscall": "open",
      "path": "/directus/uploads/e8d57029-814b-4256-929e-caa492f64b1c.png"
    }
`
I've sorted it. Thanks

**Comment by robamon** [comment]
Ticket closed
