### ISSUE TITLE
getting type errors when trying to use `ofetch`/`$fetch` with the SDK@12.0.0

### ISSUE THREAD

**Issue by Sandros94** [directus/directus#19747]
### Describe the Bug

I'm having trouble getting `ofetch`/`$fetch` to work with the new SDK in a Nuxt project.

I already described some of this in the discord channel, but basically I'm getting 1/2 type errors related to the `extract-data` util (depending on the browser is either `TypeError: e.headers is undefined` or `TypeError: Cannot read properties of undefined (reading 'get')`. But printing the response logs I see that the correct data is returned.

![Screenshot 2023-09-20 003920](https://github.com/directus/directus/assets/13056429/1477dd8d-b2ed-46ee-8b9c-7d3c444bc317)

One thing I've noticed is that the `ofetch`/`$fetch` types don't exactly match with the directus `fetch` type, but then looking at the first two I also see `type FetchRequest = RequestInfo;`, so I imagine that this should just work.

### To Reproduce

```vue
<template>
  <div>
    <div>
      <button @click="signIn('admin@example.com', 'Passw0rd!')">
        Sign in
      </button>
      <button @click="signOut">
        Sign out
      </button>
      <button @click="refreshTokens">
        Refresh Tokens
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { createDirectus, authentication } from '@directus/sdk'

const client = createDirectus(
  'http://localhost:8055', {
    globals: {
      // @ts-expect-error
      fetch: $fetch.create({
        onResponse({ request, options, response }) {
          console.log('Request:', request)
          console.log('Options:',options)
          console.log('Response:',response)
        }
      }),
    }
  }).with(authentication({ autoRefresh: true, credetials: 'include'}))

async function signIn(email: string, password: string) {
  const loginData = await client.login(email, password).catch(console.error)
  console.log(loginData)
} 
async function signOut() {
  const loginData = await client.logout().catch(console.error)
  console.log(loginData)
} 
async function refreshTokens() {
  const loginData = await client.refresh().catch(console.error)
  console.log(loginData)
} 
</script>
```

### Directus Version

sdk v12.0.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Sandros94** [comment]
> 1. `autoRefresh` enables or disabled the automatic refreshing of credentials

But is this done during requests? Or is it the SDK that checks for the expiry and calls a refresh only in need?
Looking at the SDK code I'm not fully sure how it works, but I would like to understand it so that I could just stop having a full nuxt-plugin just for the autoRefresh as I did until now.

> 2. https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#sending_a_request_with_credentials_included

Ah nice, idk why I didn't expect it. Thanks

**Comment by br41nslug** [comment]
> > 1. `autoRefresh` enables or disabled the automatic refreshing of credentials
> 
> But is this done during requests? Or is it the SDK that checks for the expiry and calls a refresh only in need? Looking at the SDK code I'm not fully sure how it works, but I would like to understand it so that I could just stop having a full nuxt-plugin just for the autoRefresh as I did until now.

The authentication composable checks for expiry and refreshes before that so the SDK should always a have a valid token available for requests.
https://github.com/directus/directus/blob/main/sdk/src/auth/composable.ts#L63-L72

**Comment by Sandros94** [comment]
> The authentication composable checks for expiry and refreshes before that so the SDK should always a have a valid token available for requests. https://github.com/directus/directus/blob/main/sdk/src/auth/composable.ts#L63-L72

Yes, I was checking those lines earlier.
But in the even if the `access_token` gets corrupted or lost, while `refresh_token` is still valid, couldn't this cause soft-locks?

Or should this be implemented by the people using the sdk?

**Comment by br41nslug** [comment]
Losing or corrupting the access_token is an interesting situation, the SDK can't really tell you whether that token is valid or intentionally cleared so I guess the api calls would error with invalid credentials on its requests until the `refresh` is triggered or manually run. 

As it stands the SDK does not check the response for invalid credentials so you'd need to implement that with you're projects needs (like a queue to re-send the failed requests, maximum retries, etc)

**Comment by Sandros94** [comment]
I'm testing stuff about the corruption or loss of the `accessToken`, but sometimes I find myself in a situation where after a successful refresh of the tokens the `refreshToken` gets `httpOnly: true` even if it was declared as `false`. And if a second corruption/loss this would cause the impossibility of `accessToken` refreshes and inability to invalidate the session:
![image](https://github.com/directus/directus/assets/13056429/ec2884cf-6a34-45b5-824c-7908c80899ed)

Should I wait till `ofetch` gets fixed or could I investigate it elsewhere?

Mainly for context, but on Nuxt side of things I feel like I'm doing everything alright:
```ts
import type { DirectusUser } from '../types'
import { readMe } from '#imports'

export function useDirectusAuth () {
  const autoRefresh = useRuntimeConfig().public.directus.autoRefresh
  const { accessToken, refreshToken } = useDirectusCookie()
  const user = useDirectusUser()
  const directus = useDirectus().with(authentication('json', { autoRefresh, credentials: 'include' }))
  const directusRest = useDirectusRest({ staticToken: false })

  const setUser = <T extends object>(value: DirectusUser<T>) => {
    user.value = value
  }

  // [...]

  const refreshTokens = async () => {
    try {
      const authResponse = await directus.refresh()
      // check previous note in `signIn` about type error
      if (authResponse.expires !== null) {
        refreshToken(authResponse.expires).value = authResponse.refresh_token
        accessToken(authResponse.expires).value = authResponse.access_token
      }
      const res = await directusRest.request(withToken(authResponse.access_token!, readMe()))
      setUser(res)

      return {
        accessToken: authResponse.access_token,
        refreshToken: authResponse.refresh_token,
        expiresAt: authResponse.expires_at,
        expires: authResponse.expires
      }
    } catch (error: any) {
      if (error && error.message) {
        // eslint-disable-next-line no-console
        console.error("Couldn't refresh tokens", error.errors)
        throw error.errors
      } else {
        // eslint-disable-next-line no-console
        console.error(error)
        throw error
      }
    }
  }

  return {
    // [...]
    refreshTokens
  }
}
```

And here is the composable that handles the cookies:
```ts
import type { ModuleOptions } from '../types'
import type { CookieRef } from '#app'
import { useCookie } from '#imports'

export function useDirectusCookie () {
  const {
    tokenCookieName,
    refreshTokenCookieName,
    cookieHttpOnly: httpOnly,
    cookieSameSite: sameSite,
    cookieSecure: secure
  } = useRuntimeConfig().public.directus as ModuleOptions

  const accessToken = (maxAge?: number | undefined): CookieRef<string | null> => {
    const cookie = useCookie<string | null>(tokenCookieName, { maxAge, httpOnly, sameSite, secure })
    return cookie
  }

  const refreshToken = (maxAge?: number | undefined): CookieRef<string | null> => {
    const cookie = useCookie<string | null>(refreshTokenCookieName, { maxAge, httpOnly, sameSite, secure })
    return cookie
  }

  return {
    accessToken,
    refreshToken
  }
}
```
