### ISSUE TITLE
`withOptions` does not working in `createItem` in @directus/sdk@12.0.0

### ISSUE THREAD

**Issue by Dominic-Preap** [directus/directus#19758]
### Describe the Bug

With the introduction of `withOptions` we can easy add custom option through fetch like header etc. But when using it with createItem for create record it doesn't work.

### To Reproduce

This will create a new record with empty value on every fields (name and price is empty).
```js

const client = createDirectus<Schema>('my-url')
  .with(staticToken(env.NEXT_DIRECTUS_TOKEN))
  .with(rest());


const data = return await client.request(
    withOptions(
      createItem('products', {
        name: 'product name',
        price: 10
      }),
      { headers: { Authorization: `Bearer my-token` }
    )
  );
```

When console log `withOptions` function, I see the body is JSON string? is it intentional? 

```js
 console.log(
    withOptions(
      createItem('products', { name: 'product name', price: 10 }),
      { headers: { Authorization: `Bearer my-token` }
    )()
  );

  // --- Output Result ---
  // {
  //   path: '/items/products',
  //   params: {},
  //   body: '{"products":"product name","price":10}', <--- string here
  //   method: 'POST',
  //   onRequest: [Function (anonymous)]
  // }

```

### Directus Version

v10.6.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
This is working as intended, a couple things to note here:
1. `withOptions` allows you to override anything so you probably want to use `withToken` instead if the goal is to add/override a token.
2. The Directus API requires the `Content-Type: application/json` header to parse the incoming body but all `headers` are being overwritten by `withOptions` in the snippet
3. using both the `staticToken` and `withOptions` methods of adding tokens is somewhat redundant

**Comment by Dominic-Preap** [comment]
> 2. The Directus API requires the Content-Type: application/json header to parse the incoming body but all headers are being overwritten by withOptions in the snippet

Can confirm by add `Content-Type: application/json`, it works. Thanks.


```js
const data = await client.request(
  withOptions(
    createItem("products", {
      name: "product name",
      price: 10,
    }),
    {
      headers: {
        Authorization: `Bearer my-token`,
        "Content-Type": "application/json",
      },
    }
  )
);
```

>3. using both the staticToken and withOptions methods of adding tokens is somewhat redundant

The reason is some of my endpoint required, access token (auth token) from outside instead of using static token. I want to create a client with default static token and some functions with override token with the same client.
