### ISSUE TITLE
Can't batch update: choose existing file

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1975]
When batch updating items, if you edit a Multiple Files interface and select an existing file it SHOULD save that relational ID to all batch items. However right now you are not given the option to save (action button stays disabled)

**Comment by rijkvanzanten** [comment]
At the moment, all core developers are working fulltime on the next major version of the platform, so I'll have to leave this open as a help-wanted. If anyone is inclined to take a swing at fixing this, a PR is very welcome 😄

Ps. this has been fixed in 7.0

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/15)
