### ISSUE TITLE
In custom extensions/interfaces PrimaryKey is '+'

### ISSUE THREAD

**Issue by Pachat** [directus/directus#19754]
### Describe the Bug

In custom extensions interfaces, in Setup still in onMounted, the PrimaryKey values '+' event if the item is not in creation

Looks like #14574 is again here, or for some other reason.

This is a blocking bug, preventing from using this version.
It was my first try to get out of v10.2.1, so I cannot say precisely when it appeared, but sure after v10.2.1 where the PrimaryKey is correct.

### To Reproduce

On an input extension, in a form of let say `/admin/content/util/70d9ca25-67d2-485f-8a7a-5c01b7000cf3`

Put debugger stops and look at `props.primaryKey` value

```
export default {
	props: {
		primaryKey: {
			type: String | Number,
			default: null,
		},
		value: {
			type: String,
			default: null,
		},
	},
	setup(props, { emit }) {
		if (props.primaryKey == '+')
			debugger  // <= should not stop here

		onMounted(async () => {
			if (props.primaryKey == '+')
				debugger  // <= should not stop here

```	

### Directus Version

v10.6.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
The fields/interfaces might be loaded before the item is done loading from the server

**Comment by Pachat** [comment]
@rijkvanzanten Yes thats exactly what happens now (not before) maybe for performance reasons.

Therefore how, in setup or onMounted, is it possible

- to know if we are creating or updating an item?
- in case of updating have the item's key and make some api calls necessary for some particular actions?

**Comment by Pachat** [comment]
To confirm that, with `setTimeout` inside the setup things get OK.

@rijkvanzanten Thank you for telling me that it is an expected behaviour.
