### ISSUE TITLE
Snapshot field ordering is wrong

### ISSUE THREAD

**Issue by cliqer** [directus/directus#19756]
### Describe the Bug

While trying to apply an SQLite snapshot to Postgres found out that columns are being created in a random order, making it impossible to use 'INSERT INTO' as the values are incorrect

### To Reproduce

on a sqlite backed directus
`npx directus schema snapshot ./snapshot.yaml`

on a new bootstrapped Postgres backed directus
`npx directus schema apply ./snapshot.yaml`

Export data and import through pgql
`sqlite3 data.db .dump | grep '^INSERT INTO' > dump.sql`

Also, tried to convert data by adding the table order on the statements though, this is still a work in progress:
```python
# python
import sqlite3

def escape_quotes(value):
    """Escape single and double quotes for SQL insertion."""
    if isinstance(value, str):
        return value.replace("'", "''").replace('"', '""')
    return value

db_file = 'data.db'
conn = sqlite3.connect(db_file)
cursor = conn.cursor()

tables = [row[0] for row in cursor.execute("SELECT name FROM sqlite_master WHERE type='table';").fetchall()]

with open("dump.sql", "w") as out_file:
    for table in tables:
        # Get column names for the table
        columns = [row[1] for row in cursor.execute(f"PRAGMA table_info({table})").fetchall()]

        # Fetch data from the table
        data_rows = cursor.execute(f"SELECT * FROM {table}").fetchall()

        # Write data to the file
        for row in data_rows:
            values = ', '.join([f"'{escape_quotes(value)}'" if isinstance(value, str) else str(value) for value in row])
            out_file.write(f"INSERT INTO {table} ({', '.join(columns)}) VALUES ({values});\n")

cursor.close()
conn.close()
```

### Directus Version

v10.6.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
I'm not entirely sure if this is something we can properly resolve across the board, as not every database provider supports configurable / adjustable ordinal positioning. For example, you can't change the order of columns in Postgres, so if your snapshot would add a column that should be "in the middle", there's no way to do so without recreating the whole table, which feels excessive.

> making it impossible to use 'INSERT INTO' as the values are incorrect

IIRC the order of columns in named inserts doesn't matter, for example: `INSERT INTO my_table (title, id) VALUES ('hi', 5)` shouldn't fail if the table ordinal order is `id`, `title` 🤔

**Comment by rijkvanzanten** [comment]
> it makes it impossible to transfer on a different db in one go using the schema

This is the part I'm not quite fully understanding. How is the difference in ordinal positioning between two databases preventing you from transferring data? When using named inserts, the ordinal positioning should be irrelevant 🤔

**Comment by rijkvanzanten** [comment]
Ahh gotcha 👍🏻 

While we wouldn't be able to fully guarantee the order (esp. on _update_ rather than create), we should take a look at what's causing that order difference in the first place and see if that's something possible to address 🙂

**Comment by ConnorSimply** [comment]
The Schema Service currently organizes the collections alphabetically by collection name. For fields, the service sorts them first by collection name and then by field name. For relations, the service sorts them first by collection name and then by field name. If we change them to sort by their **original ID**, it should in theory be a little closer to the original schema when it gets applied. @rijkvanzanten Do you think that would adequately address the issue since we can't guarantee the order?

**Comment by makote** [comment]
I'm not sure this is within this scope, but the it also changes the order of the fields on a table interface for O2M relationships to alphabetical,  we currently review them individually every time we want to apply changes to production.

**Comment by rijkvanzanten** [comment]
>  If we change them to sort by their original ID, it should in theory be a little closer to the original schema when it gets applied.

@ConnorSimply By _original ID_, do you mean the database's ordinal ID? For what it's worth, the reason we went with alphabetical order was because the ID reported by some databases was non-deterministic which cause the output to be random, which was not good 👀

**Comment by ConnorSimply** [comment]
@rijkvanzanten No, I mean the ID in the ID column...PK of the row. That ID would in theory be the order they were created, right?

**Comment by rijkvanzanten** [comment]
Ahh the ID in `directus_fields`! Yeah that'd work 🙂
