### ISSUE TITLE
Single File change not counted as edit

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1976]
When I update an item (parent) with a new Single File (relational) it does not update the "Last Update" field on the Item Listing. The ID in the column changed, so this should have been updated.

![screen shot 2017-11-30 at 12 03 59 pm](https://user-images.githubusercontent.com/522079/33443853-a2028690-d5c6-11e7-8f17-08510cf9d865.png)

**Comment by WellingGuzman** [comment]
This has been already fixed on `develop` AKA `6.4.5-dev`, probably in this commit: https://github.com/directus/directus/commit/1199bcd2367b03a79d12a369f39d52990a08972c
