### ISSUE TITLE
Privilege Option not working as intended

### ISSUE THREAD

**Issue by neocafe** [directus/directus#1977]
## Version Info
  - Directus version and branch: Latest Version
  - PHP version: 7.2
  - MySQL version: 5.10
  - Web server: Apache
  - OS name and version: Ubuntu 16.04

## Expected Behavior
When setting the privilege to view only, can view the entries but cannot modify any data which includes files also.

## Actual Behavior
Not seeing the already uploaded file but can see only an upload option.

## Steps to Reproduce
 1. Add a new user group that can only view data
 2. Assign user to a table that has some file(s) in it
 3. try to login as the user and navigate to it.

## Schema Dump, Logs, or Screenshots
![access](https://user-images.githubusercontent.com/13376344/33466863-b1b088fc-d676-11e7-816a-5bb71d6268b0.PNG)
![after_login](https://user-images.githubusercontent.com/13376344/33466864-b1f4184c-d676-11e7-80c2-b15395222c4f.PNG)

***UPDATE***

So, After running some tests I was able to have the files listed instead of getting a file upload button, but still I can remove the image ( won't get updated but still a non-privileged user can see a form ) 

The problem is that I will have to grant permission to the directus_files table to the user, now the user can view all the files I've uploaded on to the server.

**Comment by WellingGuzman** [comment]
Exactly, this is not an bug, but an actual a confusion with how to use the privileges.

Closing this, otherwise you are experiencing an issue, please be clear and we can take care of it.

Thanks for reporting this issue.

**Comment by neocafe** [comment]
@WellingGuzman, I'm not sure if I could agree with.

The problem I'm facing with is that for a set of user's I gave View / Read Permission for a table which had File as one of the columns, now if a user login he / she must be able to view the file. But instead of showing the uploaded file, the user is being shown with an upload button although the upload won't work, it's not possible for the user to view the already uploaded file.

**Comment by WellingGuzman** [comment]
This has been a discussion we have been doing for long time, but it make sense to not display related data if the user has not permission to view the related table content.

**Comment by neocafe** [comment]
Hi @WellingGuzman Yes it makes sense to not display the related data if the user has not the permission to view related data.

But, I have a table that provides user with the read permission. Now if I provide access to the related table: directus_files I will be indirectly providing access to all files that is uploaded ( by accessing the File Library ). Or else is there any way to provide access to those entries in the directus_files table for which the user already has the read permission to.

**Comment by neocafe** [comment]
At the very least, I believe it would be better to not display the upload button where the uploaded file would have been. Wouldn't that confuse a user more?

**Comment by benhaynes** [comment]
OK, I think there is some confusion going on here, let me clear things up:

**Single File Interface:**
Read Blacklist= true (the user should see the image in the interface if `directus_files` are read=true)
Write Blacklist = false (the upload/choose/url/remove buttons should be hidden/disabled)

**Directus Files Table:**
Read/View = true (the user can see all files)
Create/Add = true (can upload images)

@neocafe could you describe your situation in these terms so I can explain how it should be.

**Comment by WellingGuzman** [comment]
I agree on the button, but with the rest and more confusing because @benhaynes understood something else.

Let's clear things up.

---
also ben I think it better to point out that if a user can see/read/view only their upload files as well.

> Read Blacklist= true (the user should see the image in the interface if directus_files are read=true)

Shouldn't be the other way around, if the read is not black listed?

**Comment by benhaynes** [comment]
I updated my comment, I had the blacklist values backwards

**Comment by rijkvanzanten** [comment]
At the moment, all core developers are working fulltime on the next major version of the platform, so I'll have to leave this open as a help-wanted. If anyone is inclined to take a swing at fixing this, a PR is very welcome 😄

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/16)
