### ISSUE TITLE
Avatar displays ID if not set

### ISSUE THREAD

**Issue by emahuni** [directus/directus#19773]
### Describe the Bug

Compare the following items for item associated with a user with an avatar and another without when hovered over:

![image](https://github.com/directus/directus/assets/7290508/ccde9f60-1ff9-40fa-979f-38c6ca50b2b8)

The one at the bottom has no avatar image and when hovered over it shows that id instead of the same popup with a placeholder image.

### To Reproduce

1. Create an articles collection and associate it with the user collection as follows:

articles.user -> directus_users.articles

2. Ensure the user field's display uses the avatar display
3. Create 2 users
4. Upload avatar image for one of the users and leave the other one as is.
5. Create an article for each user
6. Go to the articles layout 
7. Add the user column to the tabular layout 
  - the row for the artible with the user that has an avatar should show the uploaded image and the other should show the placeholder avatar image in the column
8. hover over each of the articles
 - the article for the user that has an avatar will show popup as shown above
 - the article without an uploaded image will show an ID instead, as shown above

### Directus Version

v10.6.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by 0x2aff** [comment]
This issue has nothing To-Do with missing avatar on Directus user. 

The user-popover component is missing a null-check for the Directus user role. Hovering over the display of a user without a role will lead to this issue.

PR incoming.
