### ISSUE TITLE
sdk unable to customize how the auth cookie is stored

### ISSUE THREAD

**Issue by Sandros94** [directus/directus#19780]
### Describe the Bug

If we use the `authentication` composable with `mode: cookie` all the cookie configs are inherited from the Directus env variables.

In some cases it could be beneficial to edit some or all those cookie configs, while still taking advantage of the `mode: cookie`. 

Wouldn't be easier to provide somesort of customization like the `storage` for `authentication` composable? This way if people wants to customize the cookie name they can do it without the need to override other configs like `sameSite`, `httpOnly` and `secure` that could be inherited from the Directus instance.

### To Reproduce

Potential example:

```diff
const client = createDirectus<T>('https://example.com').with(authentication(
  'json', {
    autoRefresh,
    credentials: 'include',
    storage: useDirectusAuthStorage(),
++  cookie: {
++    name: 'myCustomName', // optional
++    httpOnly: true, // optional
++    sameSite: 'none', // optional
++    // [...]
++  }
  })).with(rest(options))
```

### Directus Version

sdk v12.0.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
The SDK does not set cookies and when `httpOnly` is enabled the SDK should not have access to them at all so i am not sure what these options would do and don't think this can be classified as a bug. 
If you do decided to manage cookies you are absolutely able customize the storage with any options you require.

If you do want the SDK to have a feature for setting cookies feel free to open a [Feature Request](https://github.com/directus/directus/discussions/categories/feature-requests) 😄

**Comment by Sandros94** [comment]
> when httpOnly is enabled the SDK should not have access to them at all
I guess I didn't fully realized that one.

Indeed setting up a custom storage is the better choice for those who need this. An since the cookie is managed by Directus itself, not the sdk, it is not even possible to inherit some of those cookie configs to a custom storage right?

**Comment by br41nslug** [comment]
> it is not even possible to inherit some of those cookie configs to a custom storage right?

Not directly no, the API would have to expose the settings somewhere to fetch 🤔
