### ISSUE TITLE
Using @directus/sdk in a Cloudflare Worker

### ISSUE THREAD

**Issue by martinsotirov** [directus/directus#19784]
### Describe the Bug

The @directus/sdk seems to rely on the credentials field when sending requests via the Fetch API which causes the request to error out in a Cloudflare Worker context (See https://github.com/cloudflare/workers-sdk/issues/2514).

### To Reproduce

Try to use the `@directus/sdk` in a Cloudflare Worker

### Directus Version

10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
This has been addressed in https://github.com/directus/directus/pull/19749

**Comment by martinsotirov** [comment]
@br41nslug thanks for the info. Maybe this should be mentioned somewhere in the docs for the sdk. 👀

**Comment by br41nslug** [comment]
> Maybe this should be mentioned somewhere in the docs for the sdk. 👀

What specifically would you want to see in the docs?

**Comment by martinsotirov** [comment]
@br41nslug I don't know, probably a short page dedicated to Edge deployments would be helpful. It could sum up all the different gotchas, like loading the SDK via esm.sh on Supabase Deno functions or this weird case with the credentials on Cloudflare Workers. I could make a docs PR if you point me in the right direction.

**Comment by br41nslug** [comment]
> It could sum up all the different gotchas

I cannot document what im not aware of "like loading the SDK via esm.sh on Supabase Deno functions" is news to me 🤔 and this cloudflare issue was a bug that has been resolved in the latest version.
