### ISSUE TITLE
Sort field not set for O2M relation field by default

### ISSUE THREAD

**Issue by errnesto** [directus/directus#19795]
### Describe the Bug

On a One to Many relation field by default the sort field is left empty when adding an item to the relation.

Only after I rearrange the items the values in the sort field will be set.

### To Reproduce

- Add a One to Many relation field and specify a sort field.
- (display the sort field in the item table - just easier to debug)
- Add a item (new or exisiting) to the relation

No numbers are added to the sort field.

(Once you rearrange items the sort field value is set)

### Directus Version

v10.5.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by mutil** [comment]
Hi, is there anything we can do to help with this issue?

**Comment by yipivan** [comment]
Faced the same issue, hope it got fixed soon. Is there anything blocking the pr?
