### ISSUE TITLE
Item Listing: item highlighting not working

### ISSUE THREAD

**Issue by WellingGuzman** [directus/directus#1979]
## Version Info
  - Directus version and branch: 6.4.4

## Expected Behavior
When you save a item and should take you back to the listing table and highlight the item row that was recently saved for couple of seconds. (aka flash the row)

## Actual Behavior

Doing nothing.

## Steps to Reproduce
 1. Go to any table listing
 2. Click on a item
 3. Save that item
 4. Nothing happens

**Comment by rijkvanzanten** [comment]
At the moment, all core developers are working fulltime on the next major version of the platform, so I'll have to leave this open as a help-wanted. If anyone is inclined to take a swing at fixing this, a PR is very welcome 😄

**Comment by benhaynes** [comment]
Kamino cloned this issue to [directus/app](https://github.com/directus/app/issues/1035)

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/17)
