### ISSUE TITLE
Save and X button not reachable on Firefox

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1980]
## Version Info
  - Directus version and branch: 6.4.4 Develop latest
  - OS name and version: Firefox Quantum 57.0.1

## Expected Behavior
Clicking the 3 dots on the save button shows the dropdown options for "save and stay" etc

## Actual Behavior
Clicking the 3 dots saves the item and navigates away (ignores dots)

## Steps to Reproduce
 1. Try save and stay on the newest Firefox

## Schema Dump, Logs, or Screenshots
<img width="213" alt="screen shot 2017-12-01 at 4 42 09 pm" src="https://user-images.githubusercontent.com/9141017/33504777-d54eea34-d6b6-11e7-96d8-6d7ca8e45da3.png">

**Comment by danhipke** [comment]
@benhaynes Can I give this one a shot?

**Comment by WellingGuzman** [comment]
@danhipke go ahead!

**Comment by benhaynes** [comment]
Absolutely! It must be some sort of bubble / propagation issue... but our devs are completely occupied with v7 dev and don't have time to look into it. Let us know what you come up with @danhipke!

**Comment by danhipke** [comment]
@benhaynes @WellingGuzman I added a fix for this and another similar bug I found. Details in the pull request.

**Comment by danhipke** [comment]
Created a new pull request since my old one was from the master branch and not the develop one.

**Comment by rijkvanzanten** [comment]
Awesome! Thanks @danhipke 😄

**Comment by rijkvanzanten** [comment]
Ref #2076
