### ISSUE TITLE
SDK relies on global `WebSocket` for state checks

### ISSUE THREAD

**Issue by AndriyAntonenko** [directus/directus#19801]
### Describe the Bug

I am trying to create subscription to my custom collection in the directus database:

```ts
   import * as WebSocket from 'isomorphic-ws';
   Object.assign(global, { WebSocket });

   const client = createDirectus(configService.get<string>('directus.url'), {
          globals: { WebSocket: WebSocket as any },
        })
          .with(rest())
          .with(staticToken(configService.get<string>('directus.token')))
          .with(
            realtime({
              authMode: 'handshake',
            }),
          );

   await client.connect();
   client.onWebSocket('message', console.info);
   const { subscription } = await this.client.subscribe('art_assets' as never, {
      event: 'update',
    });

    for await (const data of subscription) {
        console.info('data', data);
    }
```

I've received only one message from directus: `{ type: 'auth', status: 'ok' }`

After this, subscription iterator is not producing any events. I am sure that collection name is correct.

Also, I don't like that I have to add WebSocket to global to make it work. It seems that typings should be changed for to support node.js server env.

### To Reproduce

To reproduce you can try my code from the bug description. Don't forget to do `npm i ws isomorphic-ws`.

### Directus Version

v10.6.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
> Also, I don't like that I have to add WebSocket to global to make it work. It seems that typings should be changed for to support node.js server env.

Node.js doesn't have native WebSockets, so there's no workaround we can apply to the SDK to make that just work.

`Object.assign(global, { WebSocket });` This isn't required though if you use the `globals: {}` option 👍🏻

**Comment by AndriyAntonenko** [comment]
And my main problem is that I can't create subscription through SDK

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten without `Object.assign(global, { WebSocket });` I have an error ![Знімок екрана 2023-09-25 о 18 57 38](https://user-images.githubusercontent.com/31802208/270401548-90ee63cd-e802-4061-8bfa-610a8e10fbbc.png)

Ah that's a separate bug then 🙂  (cc @br41nslug)

**Comment by AndriyAntonenko** [comment]
Ok) Can you suggest something about my issue with subscription?

**Comment by rijkvanzanten** [comment]
Nope! I have no clue (hence tagging/assigning somebody else 🙂  )

**Comment by br41nslug** [comment]
The "main issue" is that way that `isomorphic-ws` is being imported if you update that to it will work:
```ts
import ws from 'isomorphic-ws';

// still required and will fix for this issue
Object.assign(global, { WebSocket: ws });

const client = createDirectus/*<MySchema>*/('http://localhost:8056/', {
	globals: { WebSocket: ws as any }
})
    .with(authentication('json', {autoRefresh:false})) //staticToken('admin'))
    .with(realtime())
    .with(rest());
```
I would however recommend using `ws` directly instead of `isomorphic-ws` as it seems to be fairly unmaintained.

The global set is still required because there are some occurences of comparing against `WebSocket` constants like 
```ts
ws.readyState === WebSocket.OPEN
```

**Comment by rijkvanzanten** [comment]
Thanks @br41nslug! I'll update this issue to focus on the global WebSocket reliance then 👍🏻
