### ISSUE TITLE
Project Forum: Extensions Marketplace

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#19800]
Parent-issue to keep track of timelines and any additional subtasks for the marketplace 🚀 

```[tasklist]
### Must Have
- [ ] https://github.com/directus/directus/issues/19803
- [ ] https://github.com/directus/directus/issues/20625
- [ ] https://github.com/directus/directus/issues/20540
- [ ] https://github.com/directus/directus/issues/20559
- [ ] https://github.com/directus/directus/issues/20981
- [ ] https://github.com/directus/directus/issues/20539
- [ ] https://github.com/directus/directus/issues/20978
- [ ] https://github.com/directus/directus/issues/20560
- [ ] https://github.com/directus/directus/issues/20980
- [ ] https://github.com/directus/directus/issues/21005
- [ ] https://github.com/directus/directus/issues/21314
```
```[tasklist]
### Should Have
```

```[tasklist]
### Could Have
- [ ] Allow extensions to register their own global options
- [ ] Allow extensions to have an install/uninstall step (for database migrations / other prep)
- [ ] Env var / config to only allow packages from allowlisted / verified authors
- [ ] Upgrade / Downgrade Extensions
```

### Won't Have

- x

**Comment by BlackDahlia313** [comment]
Question for anyone.

 Was just talking about this while writing my guest blog and wondering how this is persisted to new containers? Is the extension installed during bootstrap?

**Comment by br41nslug** [comment]
QQ: because i dont see a ticket related to it how would you migrate installed marketplace extensions from one instance to another? Does it automatically install if you migrate the content of `directus_extensions`? Having to manually re-install required extensions for each instance would not be great DX

**Comment by rijkvanzanten** [comment]
@br41nslug It's the same as file uploads. You're expected to copy over the extensions folder

**Comment by br41nslug** [comment]
> You're expected to copy over the extensions folder

Does it then correctly distinguish between locally installed extensions and extensions in the marketplace that may accidentally share the same name.
