### ISSUE TITLE
Undefined is not an object (evaluating 'this.structure.get')

### ISSUE THREAD

**Issue by joelkennedy** [directus/directus#1981]
## Version Info
  - Directus version and branch: v6.4.4
  - PHP version: 7.0.13
  - MySQL version: 5.5.50-MariaDB
  - Web server: Apache
  - OS name and version: CentOS 7.2

## Expected Behavior
To be able to save a CMS logo image for Directus

## Actual Behavior
Error "Undefined is not an object (evaluating 'this.structure.get')" when saving the Global Settings page of Directus after inserting an image for the logo.

## Steps to Reproduce
 1. Go to Global Settings
 2. Select an image for CMS Thumbnail URL (can upload there and then, or select existing 
 3. Press Save

## Schema Dump, Logs, or Screenshots

The code seems to fail inside the 'isNew()' function of Directus.

I can see that the object being passed in is correct:

<img width="687" alt="screen shot 2017-12-03 at 11 15 19" src="https://user-images.githubusercontent.com/19573914/33524903-d9975d12-d81c-11e7-981b-45e455a46391.png">

But the 'structure' part of that is undefined:

<img width="415" alt="screen shot 2017-12-03 at 11 15 08" src="https://user-images.githubusercontent.com/19573914/33524907-eea055d8-d81c-11e7-9f29-238ef3405368.png">

**Comment by WellingGuzman** [comment]
Thanks for reporting this, I can't find the commit but I'm almost sure this issue has been fixed in `develop, I'm not near a computer now to confirm it, if you can give it a shot before I do that would be great.

I will come back to either way

**Comment by WellingGuzman** [comment]
This issue was fixed by https://github.com/directus/directus/commit/2c1135cbb44f4157d5e919527ec7baa8b06876ee

**Comment by WellingGuzman** [comment]
@joelkennedy this will be included in the next version `6.4.5`, in the meantime you can cherry-pick this change or fix it in your local install if you will guiding by this commit.
