### ISSUE TITLE
"run script" operations crashes directus

### ISSUE THREAD

**Issue by fusscreme** [directus/directus#19818]
### Describe the Bug

I recently updated my directus version. Now my flows terminate directus whenever I use a 'run script' operation.

Please see this simple example:

<img width="763" alt="flow overview" src="https://github.com/directus/directus/assets/74452802/c2b11114-440c-4b63-b569-f9df1bfeef20">

<img width="705" alt="run script" src="https://github.com/directus/directus/assets/74452802/800c8fe3-38e6-42bb-8bdd-28942a962a79">

Now with the above flow active, whenever I update something in the collection, a 502 http status error gets displayed:

<img width="1283" alt="error 502" src="https://github.com/directus/directus/assets/74452802/400ef99d-e510-4790-84ce-3a27ecd00fc7">

The server crashes without logging anything, just terminates immediately: 
<img width="679" alt="crash" src="https://github.com/directus/directus/assets/74452802/4bd69f74-ecab-486d-9b34-1068e2e22b7d">

When I check the flow logs (after restarting directus) they contain nothing:
<img width="1399" alt="no_logs" src="https://github.com/directus/directus/assets/74452802/a52b9389-b3c9-47cf-99c2-60dbe668cd80">

I have the same error in production (both development and production are windows server 2016).
I first noted the error in v10.6.2 but the error persists in v10.6.3 (latest version as of now).

Windows Server 2016, self-hosted

### To Reproduce

1. create flow - trigger: items.update
2. create 'run script' operation in that flow - fill it out with whatever
3. update item in collection
4. node.js crashes

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
Can you share same more details about how you're running Directus? Which version of Node.js do you use?

**Comment by fusscreme** [comment]
sure :) 
in development i am using node v19.3.0, in production it is v19.1.0. both are windows server 2016 vms and directus runs behind a IIS reverse proxy.

when accessing directly (no reverse proxy) there is no '502 error' but a 'network error' displayed. please see the screenshot below.

<img width="643" alt="network error" src="https://github.com/directus/directus/assets/74452802/c6e3ff4a-024a-4822-94c0-b014d18c1bef">

**Comment by rijkvanzanten** [comment]
@fusscreme Can you try it in Node's LTS (18 at time of writing)? Uneven Node numbers are known to be more experimental. Directus targets LTS

**Comment by fusscreme** [comment]
I used node v18.18.0 and it the error is gone!
sorry for bothering you guys and thank you very much for the prompt support ❤️❤️❤️
