### ISSUE TITLE
OpenID User Payload

### ISSUE THREAD

**Issue by xxsuperdreamxx** [directus/directus#19827]
### Describe the Bug

Can we switch the openid user payload to allow the use of FIRST_NAME_KEY environment, since for example the identity server I am using is not using given_name but name, and I have to modify that in the @directus package, if we could possibly make it conditional, by default to use given_name but if the user specifies something else, to use the other variable

### To Reproduce

Setting up openID and try to use custom FIRST_NAME_KEY, since it is hardcoded it does not work

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
Yes! We should make this configurable through env vars 👍🏻

**Comment by xxsuperdreamxx** [comment]
I wouldn't mind that @rijkvanzanten. I would be happy to also cheers from Eindhoven

**Comment by rijkvanzanten** [comment]
Groetjes terug uit NYC! 👋🏻

**Comment by xxsuperdreamxx** [comment]
Aww man, je hebt onze Frikadel verlaten voor de gefruit eeten! Honestly I am eating only Asian cuisine and Eastern European you are not missing on anything haha

**Comment by xxsuperdreamxx** [comment]
@rijkvanzanten another point while updating this, might as well add the option for users to manually enter the endpoints as well, since I noticed GitLab allows you to disable the .well-known configuration

**Comment by rijkvanzanten** [comment]
@xxsuperdreamxx Lets double-check if that's in the OpenID spec. From what I remember, the `.well-known` approach is as per the spec. For the manual setup of endpoints you'd basically fallback to OAuth2

**Comment by xxsuperdreamxx** [comment]
I notice that the oauth2 configuration does not like Gitlab, I am not sure for the others, I am not sure how Panva handles that, since I only use his openId server

**Comment by xxsuperdreamxx** [comment]
@rijkvanzanten, using the `new Issuer` instead of `discover` is possible since Auth0's client also allows manual configuration. Sometimes companies do have a good reason to hide that
https://github.com/panva/node-openid-client/blob/main/docs/README.md#new-issuermetadata

**Comment by xxsuperdreamxx** [comment]
For the sake of simplicity we can only allow it if the discovery URL is missing in the env config

**Comment by rijkvanzanten** [comment]
@xxsuperdreamxx Lets split that off into another issue/pr combo 👍🏻 I'm a little hesitant we'll block / delay the release of the OP while researching/discussing the implementation details of the alternative setup for well-known :)

**Comment by xxsuperdreamxx** [comment]
Alright, I will link a new issue request, I will send the PR with the firstname and lastname at least

**Comment by xxsuperdreamxx** [comment]
#19907

**Comment by xxsuperdreamxx** [comment]
shall I mark the conversation as closed @rijkvanzanten

**Comment by aidenfoxx** [comment]
So we have hooks specifically for this kind of behavior in the "auth.create" and "auth.update" hooks, which receive the user payload from the server, and allows augmenting the stored user information. The remapping could be done there for these kinds of special cases?

**Comment by paescuj** [comment]
> So we have hooks specifically for this kind of behavior in the "auth.create" and "auth.update" hooks, which receive the user payload from the server, and allows augmenting the stored user information. The remapping could be done there for these kinds of special cases?

Seeing that we also allow customizing the name keys via env var for OAuth 2.0 and LDAP, I think it makes sense to do the same for OpenID.
For other kind of customization, I totally agree with you that hooks should used instead.

**Comment by aidenfoxx** [comment]
LDAP and OAuth don't provide consistent specs for their profile response, so it becomes a necessity there. I would say almost all OpenID providers correctly map the user profile.

Not saying I'm against the change. Just that there is a reason that the option wasn't provided.

**Comment by paescuj** [comment]
> LDAP and OAuth don't provide consistent specs for their profile response, so it becomes a necessity there. I would say almost all OpenID providers correctly map the user profile.

Hmm, that's indeed a good point! 🤔 

@xxsuperdreamxx why is this required in your case?

**Comment by xxsuperdreamxx** [comment]
Oh, I forgot to mention it here form the other issue thread, it is due to services liek Gitlab where they allow you to hide the discovery document. And recently many of my project with directus sadly use gitlab as authentication method. This is why I suggested it, I know Okta allows the discovery hiding as well! So allowing custom entry can allow mroe people to easily use it

**Comment by xxsuperdreamxx** [comment]
For this case this one is due to gitlab using `name`, ianidead of first name at least on our configuration and the Identity Server 4 for my university is using `first_name` instead of `given_name`. Altough they should follow the RFC paper, some never do. Also there ar places that jsut merge both names under the `name`

**Comment by aidenfoxx** [comment]
I feel like we're crossing our threads here @xxsuperdreamxx . 😄

But on point 1, the idea of the discovery document is that it's makes things easy to use and more secure (due to providing optional parameters that can be used for more secure operation). Opening up manual configuration I feel exposes the likelihood of more mistakes being made.

With discovery hiding being an option to enable rather than a hard requirement, I don't feel like we're doing a disservice to our users by not allowing manual configuration.

On point 2, it's a little frustrating but understandable that this happens if the only themselves store the full name in a single field. But I think a more elegant fallback would just be to default to "name" if "first_name" isn't defined, rather than setting up config options.

**Comment by xxsuperdreamxx** [comment]
I understand, currently the suggested PR, make sir optional to be set and uses the default values. It is the minor inconvenience that we might forget to change on directus update. In the NL, things sometimes go weird I have seen oauth using voornaam & achternaam for First and last name

**Comment by aidenfoxx** [comment]
Yeah, but OAuth is the wild west. OpenID at least has a `UserInfo` spec that providers (should) follow. 😬

**Comment by xxsuperdreamxx** [comment]
Sadly for example if I set the gitlab to be used as oauth2, it won't work because of the way the refresh token is returned

**Comment by aidenfoxx** [comment]
Obviously I would then recommend OpenID in that case (with `.well-known). But do you know what is wrong with the refresh token? We don't do anything special other than store the token and use it to verify the grant is still valid, and that shouldn't differ between OAuth and OpenID?

**Comment by paescuj** [comment]
@aidenfoxx I really appreciate your input here. I didn't account for OpenID's specs, but considering this I have to say I agree with you that it feels more like a disservice if we start making these fields configurable via environment variable. So for special cases I think using the hooks as you suggested in https://github.com/directus/directus/issues/19827#issuecomment-1748412469 is the way to go.

@rijkvanzanten Your thoughts on this?

**Comment by aidenfoxx** [comment]
I'm honestly for making one minor change to, just as some kind of fallback for services that only provide the full name field:
```
  first_name: userInfo['given_name'] ?? userInfo['name'],
```

**Comment by xxsuperdreamxx** [comment]
That also works, i added both as  an option since why not. I rarely

**Comment by xxsuperdreamxx** [comment]
Tha also works, I did both of them as conditional for the sake of simplicity. (sorry the internet is  unstable, KPN is my next enemy haha)

**Comment by paescuj** [comment]
> I'm honestly for making one minor change, just as some kind of fallback for services that only provide the full name field:
> 
> ```
>   first_name: userInfo['given_name'] ?? userInfo['name'],
> ```
> 
> Also, great to raise this @xxsuperdreamxx, since with Gitlab we do have a concrete case where this is a problem.

Hmm, couldn't this lead to an unintentional mix up? We don't know what's stored in `name` - could also be the last name...
That's what the spec is for, to get predictable values, right? 😄

For this reason, I tend to leave it as is and recommend the use of auth hooks for such special cases instead.
We could, however, add an example for such a case to the docs.

**Comment by aidenfoxx** [comment]
So the spec says `End-User's full name in displayable form including all name parts, possibly including titles and suffixes, ordered according to the End-User's locale and preferences`.

Really is a question of "Is something better than nothing?" I would say.

**Comment by xxsuperdreamxx** [comment]
The current conditional rendering I suggested they can even leave it custom for last name not to show it it on purpose if needed

**Comment by paescuj** [comment]
Closing this with the background that such customization can be applied in a more targeted way using the `auth.create` / `auth.update` hooks (https://docs.directus.io/extensions/hooks.html#available-events). For example, a specific logic can be implemented where first/last name can be derived from the `name` property.
However, I'm looking into adding an example for the `auth.create` / `auth.update` hooks to the documentation as an aid.

**Comment by yakubovmax213** [comment]
@xxsuperdreamxx Maybe this will help you: I tried to fill in the first and last name of the user from the data from Okta via saml. And in the code for saml this is already supported through the environment variables AUTH_OKTA_GIVEN_NAME_KEY and AUTH_OKTA_FAMILY_NAME_KEY (or related vars to your provider). Here is this code:

https://github.com/directus/directus/blob/b99eeb90e2d76145df7bb89a9fc5fa36617714c7/api/src/auth/drivers/saml.ts#L50C3-L50C3

Perhaps the same principle could be implemented for openId?

**Comment by almereyda** [comment]
> an example for the auth.create / auth.update hooks to the documentation as a starting aid.

Did this example ever emerge?

**Comment by xxsuperdreamxx** [comment]
> > an example for the auth.create / auth.update hooks to the documentation as a starting aid.
> 
> Did this example ever emerge?

We didn't publish it, it got reverted look at the main discussion

**Comment by almereyda** [comment]
That's why I was asking, thank you. It wasn't perfectly evident from the argumentation.
