### ISSUE TITLE
The shutdown hook is not complete when WEBSOCKETS_ENABLED is false

### ISSUE THREAD

**Issue by aclisp** [directus/directus#19822]
### Describe the Bug

https://github.com/directus/directus/blob/9e1ae56b651a4fb7412c7e0ec935feb7eca136b5/api/src/server.ts#L122-L126

`getWebSocketController()` will throw an Error if WEBSOCKETS_ENABLED is false, which is the default setting. So `onSignal` will abort and prevent the Action Event `server.stop` from executing.

### To Reproduce

Start the directus server, then kill the process. 

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
Thanks for the report! ❤️
