### ISSUE TITLE
Collection Filter in Field Copy Modal Not Functional

### ISSUE THREAD

**Issue by RaiBinPar** [directus/directus#19828]
### Describe the Bug

I encountered an issue when attempting to copy a field. A modal appears with an option labeled "collection", upon trying to utilize the filter, I observed that it does not appear to have any functional impact. In other words, the filter does not assist in narrowing down the search, nor does it seem to provide any discernible action or effect. 

The "collection" filter should help users narrow down their search by filtering out unrelated collections based on the input.

![image](https://github.com/directus/directus/assets/109278454/e63588c6-6a8d-46ea-be62-4ddfd5f3ec03)

Thanks! 
Rai, from BinPar Team 🚀

### To Reproduce

1. Navigate to the section where fields can be copied.
2. Initiate the process to copy a field.
3. In the resulting modal, try to use the "collection" filter to narrow down the list.
4. Observe that the filter does not produce any changes or assist in the search process.

### Directus Version

v10.5.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
This has been fixed in #19732 which has been released in [v10.6.2](https://github.com/directus/directus/releases/tag/v10.6.2).
