### ISSUE TITLE
Bar Chart panel unable to count M2M relationship on users

### ISSUE THREAD

**Issue by geoffoliver** [directus/directus#19835]
### Describe the Bug

The "Bar Chart" dashboard panel is unable to count M2M related data.

I can add a panel using the UI - no "raw" field editing or code views - and the panel will be created, but it doesn't display anything. It renders, but it just displays an empty box. Setting the `LOG_LEVEL` .env variable to `TRACE` reveals an error in the console when the panel tries to render, and the error is related to how a column - `directus_users.consulting_customers` - does not exist.

### To Reproduce

1. Set the `LOG_LEVEL` in your .env to `TRACE` and start Directus.
2. Create a `customers` data model with the basic fields (status, created, etc) and a "name" field.
3. Edit the `directus_users` data model and create a relationship called "Consulting Customers" (`consulting_customers`) with the following configuration:
    - M2M to `customers`
    - Click the "Continue in Advanced Field Creation Mode" link
    - Check the "Add M2M to "customers"" option in the "Corresponding Field" section under the "Relationship" section
4. Create at least one "Customer" record, and associate at least one user with the customer record under the "Consultants" field.
5. Create a dashboard and name it whatever you want.
6. Add a "Bar Chart" panel with the following configuration:
    - Collection: Directus Users
    - X-Axis: First Name
    - Y-Axis Function: Count
    - Y-Axis: Consulting Customers
    - All other fields left as default value

**Expected Result**
Bar chart displays a chart with user first names on x-axis and bars displaying the total number of "Consulting Customers" each user has.

**Actual Result**
An error is thrown in the console:

```
err: {
  "type": "GraphQLError",
  "message": "select \"directus_users\".\"first_name\", count(\"directus_users\".\"consulting_customers\") as \"count->consulting_customers\" from \"directus_users\" group by \"directus_users\".\"first_name\" order by \"directus_users\".\"first_name\" asc - column directus_users.consulting_customers does not exist",
  "stack":
      error: select "directus_users"."first_name", count("directus_users"."consulting_customers") as "count->consulting_customers" from "directus_users" group by "directus_users"."first_name" order by "directus_users"."first_name" asc - column directus_users.consulting_customers does not exist
          at Parser.parseErrorMessage (/home/geoff/project/node_modules/pg-protocol/dist/parser.js:287:98)
          at Parser.handlePacket (/home/geoff/project/node_modules/pg-protocol/dist/parser.js:126:29)
          at Parser.parse (/home/geoff/project/node_modules/pg-protocol/dist/parser.js:39:38)
          at Socket.<anonymous> (/home/geoff/project/node_modules/pg-protocol/dist/index.js:11:42)
          at Socket.emit (node:events:513:28)
          at addChunk (node:internal/streams/readable:324:12)
          at readableAddChunk (node:internal/streams/readable:297:9)
          at Readable.push (node:internal/streams/readable:234:10)
          at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
  "path": [
    "query_4891e1c5"
  ],
  "locations": [
    {
      "line": 1,
      "column": 9
    }
  ],
  "extensions": {}
}
```

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by ConnorSimply** [comment]
All of the panels expect the aggregation to happen on the _selected_ collection. If you are trying to get that bar chart, you would set the config to...

- Collection = `consulting_customers`
- X-Axis = `user`
- Y-Axis = `id`
- Y-Axis Function = `count`

This will count the `consulting_customers` m2m junction items, grouped by the user.

Please note that your X-Axis will display the user ID numbers if that is how you have your junction collection configured. It is currently not possible to group based on related fields with insights right now. Adding the ability to group on related fields would be a new feature and should follow the feature request process 😀!
