### ISSUE TITLE
Directus crashes on PHP 7.2 because Object is a reserved keyword

### ISSUE THREAD

**Issue by MeLlamoPablo** [directus/directus#1984]
Hi! I'm getting an error 500 after doing the installation process and logging in for the first time.

## Version Info
  - Directus version and branch: [e54b1ead5c71121dc855668a36bfb20c6e1101c2](https://github.com/directus/directus/commit/e54b1ead5c71121dc855668a36bfb20c6e1101c2)
  - PHP version: `PHP 7.2.0-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Nov 30 2017 13:58:33) ( TS )`
  - MySQL version: MariaDB 10.1.26 
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: Ubuntu Server 16.04

## Expected Behavior

No errors

## Actual Behavior

The following warnings and errors are produced in `http://<ip>/users`

```
Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/vendor/zendframework/zend-db/src/Sql/AbstractSql.php on line 244

Fatal error: Cannot use Zend\Db\Metadata\Object as Object because 'Object' is a special class name in /var/www/html/vendor/zendframework/zend-db/src/Metadata/Source/AbstractSource.php on line 14
```

## Steps to Reproduce
 1. Create an VM with Ubuntu Server 16.04
 2. Run the following commands (these are from my `histroy`, with irrelevant stuff removed. Ignore the numbers, as they are from different shells combined):
```
    1  apt-get install -y python-software-properties
    1  add-apt-repository ppa:ondrej/php
    2  add-apt-repository ppa:ondrej/apache2
    3  apt update -y
    4  apt upgrade -y
    5  clear
    6  sudo apt install -y apache2 php7.2 libapache2-mod-php7.2 php7.2-mbstring zip unzip php7.2-zip
    7  php --version
    8  wget https://raw.githubusercontent.com/composer/getcomposer.org/eb2dd7a54a41891e27ab30e59b79782648380e89/web/installer -O - -q | php -- --quiet
    9  mv composer.phar /usr/local/bin/composer
   10  clear
   11  sed -i -e 's/DirectoryIndex index.html index.cgi index.pl index.php index.xhtml index.htm/DirectoryIndex index.php index.html index.cgi index.pl index.php index.xhtml index.htm/g' /etc/apache2/mods-enabled/dir.conf
   12  a2enmod rewrite
   13  echo "<Directory "/var/www/html">" >> /etc/apache2/sites-available/000-default.conf
   14  echo "    AllowOverride All" >> /etc/apache2/sites-available/000-default.conf
   15  echo "</Directory>" >> /etc/apache2/sites-available/000-default.conf
   16  sed -i -e 's/;extension=mbstring/extension=mbstring/g' /etc/php/7.2/cli/php.ini
   17  sed -i -e 's/;extension=mbstring/extension=mbstring/g' /etc/php/7.2/apache2/php.ini
   18  systemctl restart apache2
   19  apt install -y php7.2-mysql
   20  systemctl restart apache2
   22  cd /var/www
   24  rm -rf html
   25  git clone https://github.com/directus/directus.git html
   28  cd html
   28  sudo chmod -R 777 .
   38  apt install php7.2-xml
   39  composer install
   40  apt install php7.2-gd -y
   41  apt install curl -y
   43  apt install php7.2-curl -y
   46  systemctl restart apache2
```
 3. Go to the directus site and follow the installation process
 4. Log in with the admin account

## Schema Dump, Logs, or Screenshots

Here's a zip of the `api/logs` folder: [logs.zip](https://github.com/directus/directus/files/1527854/logs.zip)

Thanks for your attention

**Comment by WellingGuzman** [comment]
Thanks @mellamopablo, I will give this a shot as soon as I get my hand into a ubuntu machine

**Comment by MeLlamoPablo** [comment]
@WellingGuzman hi, thanks for your answer.

I tried again and this time I thought that I'd provide a more deterministic installation script, since I can't 100% assure that the previous commands would produce the same result. Here it is:

```sh
#!/bin/bash

add-apt-repository -y ppa:ondrej/php
add-apt-repository -y ppa:ondrej/apache2
apt-get update -y
apt-get upgrade -y
sudo apt-get install -y apache2 php7.2 libapache2-mod-php7.2 php7.2-mbstring zip unzip php7.2-zip php7.2-xml php7.2-gd curl php7.2-curl php7.2-mysql
wget https://raw.githubusercontent.com/composer/getcomposer.org/eb2dd7a54a41891e27ab30e59b79782648380e89/web/installer -O - -q | php -- --quiet
mv composer.phar /usr/local/bin/composer
sed -i -e 's/DirectoryIndex index.html index.cgi index.pl index.php index.xhtml index.htm/DirectoryIndex index.php index.html index.cgi index.pl index.php index.xhtml index.htm/g' /etc/apache2/mods-enabled/dir.conf
a2enmod rewrite
a2enmod headers
echo "<Directory "/var/www/html">" >> /etc/apache2/sites-available/000-default.conf
echo "    AllowOverride All" >> /etc/apache2/sites-available/000-default.conf
echo "</Directory>" >> /etc/apache2/sites-available/000-default.conf
sed -i -e 's/;extension=mbstring/extension=mbstring/g' /etc/php/7.2/cli/php.ini
sed -i -e 's/;extension=mbstring/extension=mbstring/g' /etc/php/7.2/apache2/php.ini
sed -i -e 's/;extension=curl/extension=curl/g' /etc/php/7.2/cli/php.ini
sed -i -e 's/;extension=curl/extension=curl/g' /etc/php/7.2/apache2/php.ini
cd /var/www
rm -rf html
git clone https://github.com/directus/directus.git html
cd html
sudo chmod -R 777 .
composer install
systemctl restart apache2
```

I deployed it on an AWS EC2 instance with `ami-bf8ecbd3`, which is Ubuntu Server 16.04 LTS. I believe there should be no difference at all with a regular VM, but just in case.

Going to `http://<ip>`, and procceeding with the configuration page, these are my settings:

![screenshot-2017-12-5 install directus](https://user-images.githubusercontent.com/11708035/33620940-975df45a-d9e9-11e7-8cbf-daca140c777d.png)

After the settings page, the login page appears. After logging in, the 500 happens. Note that the PHP errors are not enabled in the script abobe. In order to do so:

```sh
sed -i -e 's/display_errors = Off/display_errors = On/g' /etc/php/7.2/apache2/php.ini
systemctl restart apache2
```

Thanks for your help.

**Comment by WellingGuzman** [comment]
Hey @MeLlamoPablo, this may be too much to ask, but would it be possible that you can send me the urls so I can try to log in and see the issue by myself? do you get any error dump into the response body? the logs you sent me are not directly from directus?

**Comment by WellingGuzman** [comment]
Do you `mod_security` installed?

**Comment by MeLlamoPablo** [comment]
@WellingGuzman sure thing, go here: http://52.67.108.238/login.php

and login with

```
user = pabloviolin8@gmail.com
pass = [¾0òwC±ªl\_5O¯}5Whz1Õª<`}Cuí]E]#,b<A%=lA[plv82l-E'5G08BIJ>60ðch3
```

You should get:

```
Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/vendor/zendframework/zend-db/src/Sql/AbstractSql.php on line 244

Fatal error: Cannot use Zend\Db\Metadata\Object as Object because 'Object' is a special class name in /var/www/html/vendor/zendframework/zend-db/src/Metadata/Source/AbstractSource.php on line 14
```

`mod_security` is not installed. I created a phpinfo file so you can get more details: http://52.67.108.238/phpinfo.php

To random internet strangers logging in, don't troll this please. You're not gonna find anything valuable.

**Comment by neocafe** [comment]
@MeLlamoPablo as of PHP 7.2 Object is a reserved keyword and this is causing the problem.

Ref: http://php.net/manual/en/reserved.other-reserved-words.php

**Comment by MeLlamoPablo** [comment]
Does Directus not support PHP 7.2? Because I couldn't find that anywhere in the docs

**Comment by WellingGuzman** [comment]
I'm currently installing php because of @neocafe said. We haven't tested it yet, but I would assume they would be trying fatal error from 7.1 to 7.2

**Comment by MeLlamoPablo** [comment]
I just tried with PHP 7.1, and can confirm that it's working fine. I'll stay in 7.1 until this is fixed then.

**Comment by neocafe** [comment]
@MeLlamoPablo Maybe this will be the most laziest !dea ever :P

I was able to make it work after renaming the folder "Object" @ /var/www/html/vendor/zendframework/zend-db/src/Metadata  to "ZObject"

and then on the file at /var/www/html/vendor/zendframework/zend-db/src/Metadata/Source to 
"use Zend\Db\Metadata\Object" to  "use Zend\Db\Metadata\ZObject"

Also run command "composer dump-autoload"

Then I was able to login without any problem

**Comment by neocafe** [comment]
But still is getting the error
Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/vendor/zendframework/zend-db/src/Sql/AbstractSql.php on line 244

**Comment by MeLlamoPablo** [comment]
As for the error, seems easy enoguh to fix. I believe [this](https://github.com/wellingguzman/zend-db) is the repo in question.
As for the warning, indeed that should be adressed as well.

**Comment by WellingGuzman** [comment]
Exactly, I can update in our fork version and that would do the trick.

**Comment by tom-wmg** [comment]
Running into the same bug on PHP 7.2 FTW ;)

**Comment by 1zaak** [comment]
Yup same issue here as well.

**Comment by WellingGuzman** [comment]
Hey, I just want to apologies, I didn't have the chance to use php 7.2 to get the issue replicate, I checked the issue and it was a problem with `zend-db`, that was already fixed (Ref: https://github.com/zendframework/zend-db/pull/287) in version 2.9.0. But was we are using a clone until they implement flexible names for column and table, we are using our fork.

To solve this issue, remove `composer.lock` and try to install dependencies again `composer install` and make sure `zendframework/zend-db dev-directus` is on commit `ffccc5c`.

Let me know who it went.
