### ISSUE TITLE
Flow Operation runs partially in case of error, when it shouldn't at all 

### ISSUE THREAD

**Issue by arladmin** [directus/directus#19851]
### Describe the Bug

In one of my (Action) flows, there's an Update Data operation that is running in an incorrect manner (as per my interpretation).

Among the properties passed via the payload, one of them errors out. But, instead of the entire operation erroring out, the remaining properties get updated and then an error is generated by the Update data operation.

Here's the (masked) payload:
```
{
  "collection": "content",
  "key": 9929,
  "payload": {
    "final_code": "XXXX",
    "raw_final_code": "YYYY",
    "final_url": "ABC",
    "html_type": "DEF",
    "status": "GHI"
  },
  "permissions": "$full"
}
```

Here's the output of the node:
```
{
  "name": "DirectusError",
  "message": "Value for field \"final_code\" in collection \"content\" has to be unique."
}
```

![image](https://github.com/directus/directus/assets/64059154/0c0b2ee6-3619-4e37-b26b-6758489d369f)

The issue is, i would expect this to be a 'transaction' sort of operation, where, if an error exists in any stage of the operation, the entire things gets rolled back and cancelled out.

But that doesn't seem to be the case here. Either by design or because it's a bug?

Either way, is it possible to run the Update Data operation as a transaction?

### To Reproduce

.

### Directus Version

v10.6.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Can you elaborate on when this situation happens or what flow is creating this issue?
Updates are already done in a transaction and will not be applied when the specific operation fails.

Before: 
![image](https://github.com/directus/directus/assets/9389634/95d98620-3d2b-4320-9326-252890b0c719)

Flow:
![image](https://github.com/directus/directus/assets/9389634/6914df4a-1b96-4d8f-8058-217d24161375)
![image](https://github.com/directus/directus/assets/9389634/cc7ed360-2843-4615-bf66-2a98db418837)

After:
![image](https://github.com/directus/directus/assets/9389634/f059240b-9c2c-41e7-85d8-5905b47a63d7)

Closing this for now, happy to re-open when more information becomes available.
