### ISSUE TITLE
Documentation extension endpoint check for authenticated user

### ISSUE THREAD

**Issue by Zehir** [directus/directus#19858]
### Page

https://docs.directus.io/guides/extensions/endpoints-api-proxy-twilio.html#ensure-user-is-authenticated

### Describe the Inaccuracy

Hello Kevin ;)

I think there is an issue in the example:

```typescript
router.get('/*', async (req, res) => {
	if (req.accountability == null) { 
		throw new ForbiddenError(); 
	} 
```
According my test an unauthenticated used return this value :
```javascript
{
   accountability: {
     user: null,
     role: null,
     admin: false,
     app: false,
     ip: '127.0.0.1',
     userAgent: 'fooo',
     permissions: [ [Object], [Object], [Object], [Object] ]
   }
 }
```

But I see somewhere that `accountability` could be `null` but I don't know when. This may need double check with code

Thanks

**Comment by paescuj** [comment]
Thank you @Zehir! ❤️ Great catch!

The check should look as follows:
```js
if (req.accountability?.user == null) {
    res.status(403);
    return res.send(`You don't have permission to access this.`);
} 
```

Will be fixed in #19859.
