### ISSUE TITLE
No logs while running locally

### ISSUE THREAD

**Issue by alexey-yarmosh** [directus/directus#19852]
### Describe the Bug

I have a set up described in https://docs.directus.io/contributing/running-locally.html . Also I have `LOG_LEVEL=trace
`. But still the only logs I can see are:
- from debugger
<img width="1034" alt="image" src="https://github.com/directus/directus/assets/16905445/dbbf6499-c7b9-475c-b41e-c4a913d06d30">

- and from `pnpm --filter app dev`
<img width="1044" alt="image" src="https://github.com/directus/directus/assets/16905445/7830758b-e8db-438f-bd45-bb79fb149fd2">

How can I access all backend logs? Like while using docker container.

### To Reproduce

https://docs.directus.io/contributing/running-locally.html

### Directus Version

v10.6

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
The logs should be there in terminal same as running in production. Are you running both the app and api?

**Comment by alexey-yarmosh** [comment]
Second screen is logs from `app`. And first screen is what vscode gives with [configuration from the docs](https://docs.directus.io/contributing/running-locally.html#debugging-the-api-in-vs-code), I assume that is an `api`.

**Comment by br41nslug** [comment]
The app isnt super helpful until the api has been started. Not sure what that debug console shows but all data you need is in the terminal tabs. 
I'd recommend doing it 1 step at a time and not starting out with a full fledged debugger, just try to start the api and app first
start the api
```bash
$ cd api
$ pnpm dev
```
then once thats started (This may take a while) start the app.
Once you have both running successfully only then i'd recommend looking into starting/hooking in debuggers
![image](https://github.com/directus/directus/assets/9389634/ab6da9a3-2612-4d78-a182-6663eb4a972c)
