### ISSUE TITLE
Api Error 404 from AngularJS

### ISSUE THREAD

**Issue by alangv** [directus/directus#1986]
## Version Info
  - Directus 6.4
  - PHP version: PHP/7.1.5
  - MySQL version: 5.7.18
  - Web server: Apache/2.4.25
  - OS name and version:  (Win64) 

## Expected Behavior
I Expect that a response from http request from Angularjs to Directus Api 1.1

## Actual Behavior
I received "Error 404 Not Found" 

## Steps to Reproduce
 return $http({
                method: 'POST',
                url: apiv1 + 'auth/request-token',
                //params: {email: email, password: pw}, //not works
                data: {email: email, password: pw}, //not works
                headers: {
                    'Content-Type': 'application/json' 
                }
            })

**Comment by rijkvanzanten** [comment]
Hey @alangv! Could you log the value of `apiv1 + 'auth/request-token'`?

**Comment by alangv** [comment]
Yes sure...
apiv1 = "https://www.third.mysite.it/folder/directus/api/1.1/";

**Comment by WellingGuzman** [comment]
The url seems okay. Would it be possible to see the raw http request? All the response you get is "Error 404 Not Found"?

**Comment by alangv** [comment]
Ok, here you can find more info about the request and the response

![raw2](https://user-images.githubusercontent.com/34287914/33636940-b3e2dade-da1e-11e7-85e8-09436c25036b.PNG)
![raw](https://user-images.githubusercontent.com/34287914/33636941-b4040b1e-da1e-11e7-9ded-ae7e3fa56ba5.PNG)

**Comment by rijkvanzanten** [comment]
Could you make sure directus is installed at that location?

**Comment by WellingGuzman** [comment]
this could likely be one of two things, is running a non-POST request, or the url is incorrectly as @rijkvanzanten says.

**Comment by alangv** [comment]
Like you can see, the request is a post request. Then if I remove "api/1.1/auth/request-token" I can see the login page. 
![raw3](https://user-images.githubusercontent.com/34287914/33637167-b71213a4-da1f-11e7-90b4-5c86965c5472.PNG)

**Comment by WellingGuzman** [comment]
if you request `GET <your-host>/directus/api/1.1/ping` do you get `pong` back?

**Comment by alangv** [comment]
Oh...Finally I have found the solution! 
The name of the folder contained lowercase and uppercase characters.
this problem was not noticed using the browser because is not case sensitive. 

Thank you very much for the support! 
Directus rocks!

**Comment by WellingGuzman** [comment]
Thanks @alangv, glad it was figured it out
