### ISSUE TITLE
Issue with <v-checkbox-tree/> Component: Parent Item Always Selected

### ISSUE THREAD

**Issue by RaiBinPar** [directus/directus#19863]
### Describe the Bug

I've recently created a new interface using the <v-checkbox-tree/> component inside. I have passed specific parameters to it as shown in the attached image
![image](https://github.com/directus/directus/assets/109278454/4f4f9152-3c5e-4934-8a1a-8c1e4c856eb5)
Notably, the component is set to leaf mode and the localValue field is empty.

However, I'm encountering an issue where, despite localValue being empty (which should determine which checkboxes are selected), the parent item is always selected by default. Please refer to the attached image for a clear representation of the issue ![image](https://github.com/directus/directus/assets/109278454/e756d25b-bfd6-410e-842f-f1143c6029a8)

### To Reproduce

1. Setup a New Interface
2. Add `<v-checkbox-tree/>` Component.
3. Configure parameters. 
_(I'm not sure if anything else in my code really has anything to do with it, I don't think so. If we see that this way it is impossible to reproduce the error, I will try to be a bit more specific)_ 
4. Save and preview
5. Check Parent item behaviour

### Directus Version

v10.5.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by RaiBinPar** [comment]
Ok, I just realized that it is not necessary to create an interface, in fact any field in "checkbox(tree)" mode that has leaf mode will do the same.

**Comment by rijkvanzanten** [comment]
It seems to behave as expected in the Directus app itself in leaf mode, leading me to believe it might be a mismatch in props that's causing the behavior.

The app currently sets the following:

![CleanShot 2023-10-04 at 15 27 46@2x](https://github.com/directus/directus/assets/9141017/3c390e11-1e92-4b36-ad3e-49f45d54acc8)

Could you share a minimal reproduction of an extension that's misbehaving? I'm not able to reproduce this so far based on the existing info. Thanks!
