### ISSUE TITLE
Error thrown on successful LDAP authentication

### ISSUE THREAD

**Issue by fusscreme** [directus/directus#19878]
### Describe the Bug

Currently, in `...\@directus\api\dist\auth\drivers\ldap.js` an error is thrown on "end" event if the status code is "0".

<img width="636" alt="image" src="https://github.com/directus/directus/assets/74452802/d70131d4-b443-41d1-9b5d-78b0d24513ec">

Pretty sure this should be other way around, e.g. if status code is **not** "0". Please see the ldap.js documentation [http://ldapjs.org/client.html](http://ldapjs.org/client.html) (highlight by me):

> Note that the error event will only be for client/TCP errors, not LDAP error codes like the other APIs. You'll want to check the LDAP status code (likely for 0) on the end event to assert **success**.

Also, the warning is kind of misleading (at least for me) because I thought that the "bind user" is the one used for querying the directory.

Proposal:

```
res.on("end", (result) => {
          // Handle case where authenticated user is not found in directory
          if (result?.status !== 0) {
            logger.warn("[LDAP] Failed to find user record");
            reject(new UnexpectedResponseError());
          }
        });
```

### To Reproduce

1. connect directus with ldap, i.e. configure the .env file accordingly
2. in the admin app, authenticate with ldap
3. check the server log: a warning is logged everytime someone authenticates with ldap

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
> Pretty sure this should be other way around, e.g. if status code is not "0".

Feels like an obvious fix, but I'm not really familiar enough with LDAP to make that call. @aidenfoxx does that sound correct?

**Comment by aidenfoxx** [comment]
Yeah, looks like a silly oversight in the original PR; the issue for which this was added is here: https://github.com/directus/directus/issues/9516

It only exists for logging purposes, so we could just remove the whole "end" block.

**Comment by rijkvanzanten** [comment]
I think the logging purpose is still valid for some of those edge cases, so let's just flip the `===` to a `!==` and resolve this problem 🙂
