### ISSUE TITLE
"Is One Of" filter not working in dashboard beyond 21 items

### ISSUE THREAD

**Issue by vonadz** [directus/directus#19870]
### Describe the Bug

When filtering items in the dashboard, the "Is One Of" filter doesn't work when you use a list with more than 21 items. See example below.

https://github.com/directus/directus/assets/16930123/4ad0d3dd-0a8f-4a08-bf35-a7fb576804e8

### To Reproduce

Create a new instance of Directus following these instructions: https://docs.directus.io/self-hosted/quickstart.html

Create a new collection with an input field called "name".

Create 4 items in this collection with the name 1, 2, 3, 4.

Try to filter items using "Is One Of" filter, but add 22 items to the right-side list (see recording in section above).

### Directus Version

10.6.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
You're running into the following limit of query parameter parsing https://github.com/directus/directus/issues/16745

Closing this as duplicate 😄
