### ISSUE TITLE
Calendar view removes entries with Created Date = NULL from results even after changing to another view

### ISSUE THREAD

**Issue by treechime** [directus/directus#1987]
## Version Info
  - Directus version and branch: (Or commit hash) 6.4.4
  - PHP version: 7.1.1
  - MySQL version: 5.5.56-MariaDB
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: 

## Expected Behavior
Changing View Status to Calendar and then back to Table should return all entries

## Actual Behavior
Only entries with a date associated are returned after returning to Table view - all of those with null dates aren't available until refreshing the page

## Steps to Reproduce
1. Have table with Date Created column, data entered prior to Directus has Date Created value of NULL
1. View table
1. Switch to Calendar view
1. Switch back to Table view

**Comment by WellingGuzman** [comment]
Thanks @treechime for reporting this issue, I'm taking a look at it right now.

**Comment by WellingGuzman** [comment]
Fixed by https://github.com/directus/directus/commit/89f0fb1c6adace1880196b2af5a9eef61c121434
