### ISSUE TITLE
Creating a flow to read data from directus users collection throwing permissions error, even if full access is configured for the flow action

### ISSUE THREAD

**Issue by urg2014** [directus/directus#19874]
### Describe the Bug

If creating a flow which read the directus_user table, the system respond a permissions error, even if full access is configured for the flow action.

{
  "name": "DirectusError",
  "message": "You don't have permission to access this."
}

### To Reproduce

Create a flow to be triggered in UI from existing collection, configure read data from directus_users collection. 

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Does the user ID you're trying to read exist?

![image](https://github.com/directus/directus/assets/9389634/c7bcc637-49b3-4d42-9aff-b23f30035054)
![image](https://github.com/directus/directus/assets/9389634/b4ea2035-266e-493c-a5b9-55e1939e9fe8)
