### ISSUE TITLE
Add redacted Display for the Hash interface

### ISSUE THREAD

**Issue by br41nslug** [directus/directus#19889]
### Describe the Improvement

The Hash field currently comes with an interface but is missing the matching display resulting in the raw hashed value being rendered in overview pages. For the end user this should behave like the directus_user password field avoiding to directly render this value in the web app.

<img width="832" alt="271256912-6d23976d-6284-4fb0-9434-35bfeb69a538" src="https://github.com/directus/directus/assets/9389634/1b364e1c-f924-411a-b6bc-57eaf2bad88a">
<img width="832" alt="271257254-c0e79cd0-634b-408f-b59c-97beda2e4bdf" src="https://github.com/directus/directus/assets/9389634/dba6d1bc-dabb-450d-bd7b-3e836ce93626">

**Comment by gyanendrasng** [comment]
Assign it to me, I will work on it

**Comment by rijkvanzanten** [comment]
@gyanendrasng Any updates? Need any help? 🙂
