### ISSUE TITLE
Dropdown Values Empty

### ISSUE THREAD

**Issue by frappierer** [directus/directus#1988]
## Version Info
I used the docker under: https://github.com/directus/directus-docker

## Expected Behavior
I tried the example https://www.youtube.com/watch?v=rLodHE3e7Os&list=PLD--x9rY3ZL31stRPkA4FdGC4idIM-8-d&index=2 
When you come to the point to relate the photo to a user the user dropdown where you choose the "Uploader" should display all user names which were created within the user table.

## Actual Behavior
Currently there are no dropdown values. They are empty.

## Steps to Reproduce
See https://www.youtube.com/watch?v=rLodHE3e7Os&list=PLD--x9rY3ZL31stRPkA4FdGC4idIM-8-d&index=2 

## Schema Dump, Logs, or Screenshots
Screen Recording: http://jmp.sh/wlXolbY

**Comment by WellingGuzman** [comment]
Hey @frappierer you have to set the visible columns.

See here: https://youtu.be/rLodHE3e7Os?t=3m7s
