### ISSUE TITLE
directus schema snapshot currently doesn't export soft limit

### ISSUE THREAD

**Issue by MidasVE** [directus/directus#19893]
### Describe the Improvement

Currently the `directus schema snapshot` doesn't export the Soft Limit field in Directus. This is an issue when you try importing the schema and the soft limit gets removed everytime you do.

Is there a way to add this manually to the schema, or to implement this into the existing export?

**Comment by rijkvanzanten** [comment]
Mind reopening this as a Bug Report rather than a tiny tweak so it has all the information that's needed to reproduce the issue? Thanks! 🙂
