### ISSUE TITLE
SDK DirectusCollection.meta.sort requires String (should be Number)

### ISSUE THREAD

**Issue by jofmi** [directus/directus#19899]
### Describe the Bug

Using the SDK (v12.0.0)

The type `DirectusCollection.meta.sort` requires a string. 

This is inconsistent with `DirectusField.meta.sort`, which requires a number.

### To Reproduce

Here is a code example that creates a typescript warning:
```
createCollection({
  meta: {
    sort: 1,
  }
})
```

`Type 'number' is not assignable to type 'string'.ts(2322)`

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
This was addressed by https://github.com/directus/directus/pull/19881
