### ISSUE TITLE
Thumbnailer doesn't accept uppercase file extensions

### ISSUE THREAD

**Issue by airbenich** [directus/directus#1989]
## Version Info
  - Directus version and branch: 6.4.4 develop
  - PHP version: 7.1
  - MySQL version: n/a
  - Web server: PLESK with Apache & nginx for static data
  - OS name and version: CentOS

## Expected Behavior
Calling an image file via the thumbnailer with an uppercase file extension (.JPG) should return the processed file.

## Actual Behavior
Calling an image file via the thumbnailer with an uppercase file extension (.JPG) returns "Image not available".

## Steps to Reproduce
 1. Upload image with uppercase file extension like IMG_1234.JPG via directus
 2. Call it via the thumbnailer: https://directus.domain.de/thumbnail/800/450/crop/better/IMG_0362-test.JPG
 3. See the not available screen.

@jasekz @rijkvanzanten 
https://github.com/directus/directus/commit/71b01c9d5369ed67215d7b8b1e82075c86474cd6#diff-826cf7323c9db3aaac7d76b506f70104R227

Take a look at file api/core/Directus/Filesystem/Thumbnailer.php Line 227 see commit #1928
The strtolower() function in line 227 is part of this behavior. Removing the function will fix this behavior.

**Comment by WellingGuzman** [comment]
Thanks for reporting this @airbenich 

Fixed by https://github.com/directus/directus/commit/6465f5c22911d114d84eb6196b7ae4baa0a65adb#diff-826cf7323c9db3aaac7d76b506f70104R227
