### ISSUE TITLE
Uploading Image from URL inside a folder doesn't save the folder path location

### ISSUE THREAD

**Issue by vitalijalbu** [directus/directus#19891]
### Describe the Bug

Uploading Image from URL inside a folder doesn't save the folder path location, but directly uploading works correctly; see video example:

https://github.com/directus/directus/assets/9141017/f0db98b0-e9ae-4f88-9aaa-a5ad5bcdedee

I host it without directus, but with simply package.json

### To Reproduce

1. create a folder
2. upload image via URL inside the created folder

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by DanielBiegler** [comment]
Thank you for your report, I appreciate you adding the video! :)

Can confirm this is happening exactly like described. Upload works correctly, import doesnt.
