### ISSUE TITLE
Cant set custom permissions on folder Public in media

### ISSUE THREAD

**Issue by angh0r** [directus/directus#19894]
### Describe the Bug

I'm unsure if I'm doing it correctly, but docs are terribly ambiguous about setting folder permissions (apart from the statement that it should be done). No matter what I set up, my images are not accessible (forbidden).

I'm trying to do it like this:
1) choose "Use custom" for reading in "directus_files" 
2) In the rules window I'm adding the filter "Folder Equals" and then the text: Public
3) I'm saving permissions

Unfortunately, my Images added to the Public folder are still inaccessible.

When I'm trying to revise the folder filter the content I entered (the word "Public") is empty.
Not sure why and if this is a reason for my images being inaccessible.

### To Reproduce

- create "Public" folder in media assets
- add image to this folder
- set-up the permissions as mentioned in description above

### Directus Version

10.6.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by angh0r** [comment]
OK. I've found a similar issue on other forums. It looks like I'm clicking the "folder" label rather than the arrow to expand it and choose "Name". Then all works correctly.

It is terrible UX if clicking on a label creates a filter that can't work. If the element is expandable label should expand the option to let the user know that he needs to choose a more specific element.

**Comment by br41nslug** [comment]
> It is terrible UX if clicking on a label creates a filter that can't work. If the element is expandable label should expand the option to let the user know that he needs to choose a more specific element.

The filter does work however since it is a relation to folders when using the toplevel filter you'll need to use the folder ID not its name.

**Comment by gloribus** [comment]
> > It is terrible UX if clicking on a label creates a filter that can't work. If the element is expandable label should expand the option to let the user know that he needs to choose a more specific element.
> 
> The filter does work however since it is a relation to folders when using the toplevel filter you'll need to use the folder ID not its name.

I think its better to use the ID field and open the filter right away
