### ISSUE TITLE
Refactor API errors to live in `@directus/errors`

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#19906]
### Describe the Improvement

Allows them to be re-used in packages like `@directus/data` and user extensions. Currently you have to recreate errors with the same code, which can easily cause inconsistencies. 

Discussion that sparked this issue: https://github.com/directus/directus/discussions/19872

**Comment by Boegie19** [comment]
Mind Assigning me to this issue. also I assume we want the @directus/api to re export them from @directus/errors. so we don't break any existing projects?

**Comment by paescuj** [comment]
> also I assume we want the @directus/api to re export them from @directus/errors. so we don't break any existing projects?

Nope, this isn't necessary!

**Comment by Boegie19** [comment]
> > also I assume we want the @directus/api to re export them from @directus/errors. so we don't break any existing projects?
> 
> Nope, this isn't necessary!

Can I ask why. reason why I was thinking this was needed is some extensions could be importing the errors from @directus/api (This is just an assumption since I am new to directus)

**Comment by paescuj** [comment]
> Can I ask why. reason why I was thinking this was needed is some extensions could be importing the errors from @directus/api (This is just an assumption since I am new to directus)

Sure! Importing from `@directus/api` is nothing we have ever supported.

**Comment by Boegie19** [comment]
Thank. now everything is clear mind assigning me.
