### ISSUE TITLE
Browser freezes and stop working when save item with M2M

### ISSUE THREAD

**Issue by dsivokhin** [directus/directus#1990]
## Version Info
  - Directus version and branch: develop
  - PHP version: 7.0
  - MySQL version: 5.7
  - Web server: nginx
  - OS name and version: Ubuntu16.04

## Actual Behavior

When many many item  in relation field M2M, when I try save, browser freezes, long time and stop working. ( Windows10, Chrome and Firefox latest version) 
Can you optimization this ?

## Steps to Reproduce
 1. import my sql dump
 2. open table Catalog and open first item
 3. add new item in M2M field 'Product'
 4. try save 

## Schema Dump, Logs, or Screenshots

[test.zip](https://github.com/directus/directus/files/1538448/test.zip)

![default](https://user-images.githubusercontent.com/4669992/33707890-fc886840-db49-11e7-8010-5da6437adf4b.png)

**Comment by benhaynes** [comment]
Could this be that your server is timing out? It seems that this is a schema/architectural issue... though I agree it should still work with 100+ relational items.

Any ideas for how to optimize this save process to accommodate so many items being saved at once?

**Comment by rijkvanzanten** [comment]
We've reworked the nested item saving in 7.0 👍 

I'll close this issue due to inactivity. It's most likely that the server timed out during save.
