### ISSUE TITLE
OpenID manual discovery settings

### ISSUE THREAD

**Issue by xxsuperdreamxx** [directus/directus#19907]
### Describe the Improvement

Adding the feature for manually setting up the OpenID, configuration due to services like GitLab, of which allow the hiding of `.well-known` 

Potential solution
[new Issuer panva/node-openid-client](https://github.com/panva/node-openid-client/blob/main/docs/README.md#new-issuermetadata

#19827

**Comment by rijkvanzanten** [comment]
@aidenfoxx twice in one week! Oh wise wizard of auth, any concerns around adding support for custom issuers for cases where `.well-known` isn't exposed?

**Comment by aidenfoxx** [comment]
So we have hooks specifically for this kind of behavior in the "auth.create" and "auth.update" hooks, which receive the user payload from the server, and allows augmenting the stored user information. The remapping could be done there for these kinds of special cases?

**Comment by xxsuperdreamxx** [comment]
Without the `.well-known` discovery document, openid client will just ignore it or will crash directus on startup. I have tried manipulating it few times. As for using oauth2 instead of openid, the way the refresh token is returned is not liekd by the client itself

**Comment by aidenfoxx** [comment]
Sorry, I was replying to the wrong issue. Why would you not want to use the `.well-known` discovery? You mention that you can hide the endpoint in gitlab, but if you need it, why hide it?
