### ISSUE TITLE
Dropdown having NULL value prevents revision history to be updated

### ISSUE THREAD

**Issue by DarwinsBuddy** [directus/directus#19900]
### Describe the Bug

It seems that although there is this resolved [issue](https://github.com/directus/directus/pull/17732) 

If you have still some null values stored for dropdowns in a table and you edit another field, the change will not appear in revisions.

### To Reproduce

- Create a collection with multiple fields, one of them being a dropdown with some options
- create an entry and set everthing to some value, but the one dropdown (which stays NULL) and save
- edit some values there once again (but let the dropdown be still NULL) and save
- you should be able to observe that the revision has not been extended by the last change
- now change this dropdown to some value and save
- observe that revision history is updated

### Directus Version

v9.26.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
I am unable to reproduce this issue on the latest version. 

https://github.com/directus/directus/assets/9389634/d7b960d9-7a35-4388-a1f6-59262a69fbf3
