### ISSUE TITLE
CSV field falls back to 255 characters in length

### ISSUE THREAD

**Issue by Sandros94** [directus/directus#19903]
### Describe the Bug

Follow-up to a short Discord discussion, any input field with type `CSV` wont let you edit the length (much like `JSON` as expected), but once created they have their length locked to 255 characters.

The workaround is to create it as a `JSON` type, but then we'll go against other issues like #7277 till #15889 is implemented.

Database is Postgis13 and Redis6

### To Reproduce

1. In the advanced page for Tags Field or Standard Field change to type CSV
  ![image](https://github.com/directus/directus/assets/13056429/7ba295d4-41bd-46b4-9a03-4b262174450a)
2. Create the field and go back to its settings and as you can see it reports a 255 limit
  ![image](https://github.com/directus/directus/assets/13056429/4af8c426-cdb8-4cc3-91ef-dc97cf73190e)
3. When testing if that limit is respected or not we do see it active
  ![image](https://github.com/directus/directus/assets/13056429/10dfd8a8-5884-480d-995a-165e0f01ac25)

### Directus Version

v10.6.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
I think the solution here is to have the API use `text` instead of `string` for CSV values by default. That'll remove the length limitation and generally feels like a safer choice for CSV values.
