### ISSUE TITLE
Script Operation in v10.6 does not work on shared host

### ISSUE THREAD

**Issue by Tummerhore** [directus/directus#19914]
### Describe the Bug

I've just updated to the latest Directus version (10.2.1 -> 10.6.3) and noticed that using the script operation in a flow (which worked before) now causes it to produce an error on my shared host. Even the simplest flow (manual trigger -> script operation which does nothing) breaks. Using the same flow on my local Directus Instance (with or without Docker image works.)

The error you get looks like this:
`[UNKNOWN] Request failed with status code 502` with the following details:
`"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000�\b\u0000�X\u0000\u0000\", \"message\": \"Incomplete response received from application\"}"`
Also, if you open the flow afterwards, the logs do not show that the flow ran.

I guess it has something to do with the change to `isolated-vm` and I know that you guys are not too execited about running Directus in such restricted environments. But maybe you know an easy fix for it? In any case, this issue report may be helpful for other users with similar environments since it took me quite some time to realize that a flow (triggered by events) with a script operation) is causing this problem.

The good news: As a **workaround** for the problem you can register a custom operation extension with your script content instead of using the script operation.

### To Reproduce

On shared host: Trigger any flow with a script operation.

Known environment on shared host:
Node.js v19.9.0 via Phusion Passenger

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by Tummerhore** [comment]
No, using only normal JS. It happens also with this minimal script content:
```js
module.exports = async function(data) {
    return {};
}
```

**Comment by br41nslug** [comment]
Oh i see you're running an experimental version of nodejs v19 🤔 That could very well have breaking changes or incompatibilities. It is recommended to stick to the even LTS "stable" versions

**Comment by rijkvanzanten** [comment]
Closing this for now as neither Directus nor `isolated-vm` officially supports experimental versions of NodeJS. Directus aims to support the LTS version of Node, which is version 18 at the time of writing.

**Comment by Tummerhore** [comment]
Changed node.js version to 20.8.0 and now it works again. :) Thanks for the hint @br41nslug
