### ISSUE TITLE
Getting Error During Installation

### ISSUE THREAD

**Issue by GaneshKandu** [directus/directus#1992]
## Version Info
  - Directus version and branch: 6.4.4 master
  - PHP version: 5.5
  - MySQL version: 5.5
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: Centos 2.2.31

## Actual Behavior

**Fatal error**: Arrays are not allowed in class constants in **api/core/Directus/Permissions/Acl.php** on line **38**

## Steps to Reproduce
 1. install Directus 6.4.4 on php 5.5

## Schema Dump, Logs, or Screenshots

![screenshot-webuzo web-2017-12-08-13-51-05](https://user-images.githubusercontent.com/12833130/33757146-df805250-dc1e-11e7-9e80-b5fbda0d27a5.png)

![screenshot-webuzo web-2017-12-08-13-52-48](https://user-images.githubusercontent.com/12833130/33757189-1d2e5b6a-dc1f-11e7-8a0b-9cdfaf7da043.png)

I think you can not define array in constant in php 5.5,
i am installing it on php 5.5 same version  you mentioned for Directus installation 
you should change required minimum php version or change a code for php 5.5

**Comment by GaneshKandu** [comment]
i have installed Directus with Recursive 777 file permission
what file and folder should be writable for Directus in not checked in requirement part of installer

**Comment by WellingGuzman** [comment]
Hey @GaneshKandu, thanks for letting us know, we have changed the message. it will be reflected on 6.4.5. (Ref: https://github.com/directus/directus/commit/358f8653712154376ce4fb24144c603664080147)

After changing this can you install correctly or still having issue?

**Comment by GaneshKandu** [comment]
Hi @WellingGuzman  Thanks
What files and folders should be writable to run Directus?

i will let you know tomarrow

**Comment by GaneshKandu** [comment]
Thanks ! Working on PHP 5.6

**Comment by GaneshKandu** [comment]
Hi What are File permissions 
![screenshot-webuzo web-2017-12-09-15-43-10](https://user-images.githubusercontent.com/12833130/33794742-d16c582e-dcf7-11e7-8174-2a56a7fcacf1.png)

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'directus644.directus_tables' doesn't exist' in vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:239 Stack trace: # 0 vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute() # 1 api/core/Directus/Database/Schemas/Sources/MySQLSchema.php(87): Zend\Db\Adapter\Driver\Pdo\Statement->execute() # 2 api/core/Directus/Database/SchemaManager.php(330): Directus\Database\Schemas\Sources\MySQLSchema->getTables(Array) # 3 api/core/Directus/Database/TableSchema.php(869): Directus\Database\SchemaManager->getTables() # 4 api/core/Directus/Bootstrap.php(472): Directus\Database\TableSchema::getTablesSchema(Array, true) # a5 [i in vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php on line 244

**Comment by GaneshKandu** [comment]
Hi

this following permissions are checked by Directus installer

Logs Directory Writable (../api/logs/) 	Yes
Media Directory Writable (/storage/uploads) 	Yes
Config File Writable (../api/config.php) 	Yes

i think it permissions should be 


Logs Directory Writable (../api/logs/) 	Yes
Media Directory Writable (/storage/uploads) 	Yes
Config File Writable (../api/config.php) 	Yes
Config File Writable (../api/) 	**creates configuration.php file in api folder**
Config File Writable (../customs/) 	**creates migrations folder and some sub folders in customs folder**
Config File Writable (../storage/) 	**to upload files**

Directus 6.4.4 is Working with this permission

**Comment by neosin** [comment]
@GaneshKandu thanks for this post, setting permissions on "/customs/" let me finish installation

**Comment by rijkvanzanten** [comment]
Thanks for the detailed list!
