### ISSUE TITLE
Login not possible when redis is not enabled but set as store

### ISSUE THREAD

**Issue by eXsiLe95** [directus/directus#19928]
### Describe the Bug

When `RATE_LIMITER_STORE` is set to `redis`, but `RATE_LIMITER_ENABLED` is set to true, a `RateLimiterRedis` will be created when trying to log in. However, if the configuration is invalid or redis is currently unavailable, the rate limiter request will timeout and therefore will block the login attempt, resulting in the user being suspended.

From a user's view, I would expect the `createRateLimiter` function (from `rate-limiter.ts`) respects the `RATE_LIMITER_ENABLED` setting and will choose `memory` instead.

### To Reproduce

- Configure `RATE_LIMITER_REDIS_*` to a non-functional redis instance.
- Configure `RATE_LIMITER_STORE` to `redis`
- Configure `RATE_LIMITER_ENABLED` to `false`

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by eXsiLe95** [comment]
I'm willing to contribute to this when there's nothing against my proposed change.

**Comment by br41nslug** [comment]
the variables `RATE_LIMITER_REDIS_*` are not used but rather `REDIS_*` is shared for all features using redis.

Considering the `createRateLimiter` is used for more than one ratelimiter so we cannot do the enabled check in that function but rather should rewrite how this ratelimiter is instantiated (https://github.com/directus/directus/blob/main/api/src/services/authentication.ts#L21-L23) that does not check the enabled setting

**Comment by newathnow** [comment]
any updates on this i got same issue ?
