### ISSUE TITLE
Server error trying to manage Address in MySQL Sakila test DB

### ISSUE THREAD

**Issue by ttm-github** [directus/directus#1993]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus version and branch:  e54b1ea  
  - PHP version: 7.0.23
  - MySQL version: 5.7
  - Web server: (Ex. Apache, nginx or IIS?) Apache2
  - OS name and version: Ubuntu 16.04 LTS x64

## Expected Behavior

- Sakila Address table should be managed correctly from Directus.

- Mod rewrite should be reported as "yes"

## Actual Behavior
- When choosing to manage the Sakila "Address" table, accessing the table results in a RED "Server error" on the web-page. Nothing in the logs.

- Directus reports mod rewrite to "no" even though it works fine - global .htaccess works fine, htaccess_tester.php works fine and a top-level .htaccess with the following content:
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteRule ^.*$ htaccess_tester.php
</IfModule>

## Steps to Reproduce
 1. Install LAMP + Directus under www/html/directus
 2. Install sakila database
 3. Choose to manage the Sakila "Address" in Directus

**Comment by WellingGuzman** [comment]
I'm not being able to reproduce this, can you look into your http request that returns "Server Error", and share the response body?

**Comment by WellingGuzman** [comment]
Closed due to inactivity.

We will re-open as soon as we get more info to reproduce this.
