### ISSUE TITLE
The data queried through gql converted from int to string?

### ISSUE THREAD

**Issue by cdwmhcc** [directus/directus#19947]
### Describe the Bug

The data queried through gql converted from int to string, why?

### To Reproduce

![image](https://github.com/directus/directus/assets/8030134/af4f5cd6-05bf-4c5b-bcd9-eedb42292185)

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
There's not enough information available for me to really answer that. I'm assuming it's because the field is of type BigInt, which GraphQL represents as a string.

**Comment by cdwmhcc** [comment]
> There's not enough information available for me to really answer that. I'm assuming it's because the field is of type BigInt, which GraphQL represents as a string.

This is indeed caused by bigint, thank you for helping me with your extensive experience.
