### ISSUE TITLE
Unable to configure Supabase oAuth as auth provider for Directus

### ISSUE THREAD

**Issue by intrinsic-blockchain** [directus/directus#19944]
### Describe the Bug

I am unable to correctly configure Supabase auth as a oAuth provider in Directus. I created a new app inside Supabase and got the credentials. Using those credentials I configured the .env file in Directus but I keep getting errors from Supabase such as {"message":"property access_type should not exist"}

### To Reproduce

1. I created a new app in Supabase with a client ID and client secret for Directus integration.
2. Then added the following configuration to the .env file
 AUTH_PROVIDERS="supabase"
AUTH_SUPABASE_DRIVER="oauth2"
AUTH_SUPABASE_CLIENT_ID="f3e4aec4-****-****-****-4d5ac6ac6fb7"
AUTH_SUPABASE_CLIENT_SECRET="sba_65043ff**********a488693d7aff49fc599ace2"
AUTH_SUPABASE_AUTHORIZE_URL="https://api.supabase.com/v1/oauth/authorize"
AUTH_SUPABASE_ACCESS_URL="https://api.supabase.com/v1/oauth/token"
AUTH_SUPABASE_PROFILE_URL="https://api.supabase.com/v1/userinfo"

But I keep getting different errors such as this: 
{"message":"property access_type should not exist"} 
or when I remove the query param for access)type I see this error:
{"message":"redirect_uri not allowed"}

Not sure what is going wrong. Any help will be appreciated.

### Directus Version

^10.6.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by DanielBiegler** [comment]
Hi there! We use Github Issues to keep track of problems with Directus itself i.e. bugs or features, not usage questions. This sounds like a setup problem with Supabase and theres not enough info for me to help so I gotta close it for now. For usage questions and support we got a wonderful community over at Discord, see https://directus.chat that might be able to help you.
