### ISSUE TITLE
Lightbox

### ISSUE THREAD

**Issue by RudolfFussek** [directus/directus#1995]
Is there a Lightbox option in the editor?

**Comment by rijkvanzanten** [comment]
What editor? What are you talking about?

**Comment by RudolfFussek** [comment]
In WYSIWYG Full!

<img width="972" alt="bildschirmfoto 2017-12-11 um 01 34 45" src="https://user-images.githubusercontent.com/13014306/33811429-96119d1c-de13-11e7-90e8-6f187d62bd6b.png">

**Comment by RudolfFussek** [comment]
And a button for a text color would be great!

**Comment by benhaynes** [comment]
Hey @RudolfFussek – all feature requests should happen here: https://request.getdirectus.com

If you'd like to discuss other points with the community that can happen in our slack: https://slack.getdirectus.com
