### ISSUE TITLE
LDAP seems to stop working after a while

### ISSUE THREAD

**Issue by fusscreme** [directus/directus#19954]
### Describe the Bug

I am using directus with ldap authentication. This works just fine for the first couple of hours, maybe days.
But after a while a refresh request takes 120 seconds or more and fails.
Meanwhile the app stays blank.

![directus_ldap](https://github.com/directus/directus/assets/74452802/fd4967c2-95fc-475c-be3a-072490d38387)

If I wait the 120 seconds and then try to log in to the app with new credentials, the request also fails after about 2 minutes.
Requesting the login endpoint directly (auth/login/ldap/) also fails after around 2 minutes.

Eventually, when I wait long enough or try long enough, directus seems to resolve the issue on its own and I can log in normally.
Restarting directus also works.

I am pretty sure it has something to do with the ldap connection. I found this discussion that was closed a year ago: https://github.com/directus/directus/discussions/9336
Is the issue/discussion still open?

 I am happy to provide additonal information. Thank you guys for your work.

### To Reproduce

1. configure directus to use ldap for authentication (change .env file accordingly)
2. start directus
3. log in to directus, then close the app
4. wait an unspecified amount of time (1 or 2 days)
5. log in to directus and open the console
6. refresh fails after about 120 seconds
7. login fails after about 120 seconds

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by fusscreme** [comment]
Hi Daniel,
Thank you for the prompt reply. I'll get back to you as soon as possible with further information.

**Comment by fusscreme** [comment]
Thanks for your patience. Unfortunately, no error is logged. 
Please see this screenshot:
![image](https://github.com/directus/directus/assets/74452802/27d75ed3-7844-448f-9e4f-8470c6b279fc)

**Comment by fusscreme** [comment]
I did some investigating although I have to admit that the directus source code is a little too sophisticated for me.
Anyway, here are my thoughts:

1. `api\dist\auth\drivers\ldap.js`: in case ldap is reconnected, there is no rebind ("no rebind after reconnect"). please see this comment to see an example how this could look like: [https://github.com/ldapjs/node-ldapjs/issues/392#issuecomment-308924100](https://github.com/ldapjs/node-ldapjs/issues/392#issuecomment-308924100)
2. also there is never an `unbind` - not sure if this needed
3. in the same file, there is a `async verify(user, password)` function (not sure what this function is used for) that has the `reconnect` option set to false
4. `reconnect` option accepts further properties that are currently not used. see this documentation: [http://ldapjs.org/client.html#reconnect](http://ldapjs.org/client.html#reconnect)

**Comment by petrosmm** [comment]
can confirm, seeing this, as well

**Comment by fusscreme** [comment]
In this file [https://github.com/directus/directus/blob/main/api/src/auth/drivers/ldap.ts](https://github.com/directus/directus/blob/main/api/src/auth/drivers/ldap.ts) on line 90, is the `return` supposed to be there after? The `.on('error')`-handler will never be executed.

**Comment by fusscreme** [comment]
Because this issue kept coming up I had a thorough look at the source code and it seems that the ldap implementation in directus is very well done. After confirming this, I double checked my server configuration and - as one of your engineers correctly pointed out - this was a misconfiguration issue on my end all along (the ldap connection was successfully established but could not be reconnected). Sorry for wasting your time and thank you for your efforts.

This is how my .env file looks now, for people having a similar problem in ldap/active directory:

```
AUTH_LDAP_DRIVER="ldap"
AUTH_LDAP_CLIENT_URL="array:LDAP://192.168.4.180:389,LDAP://192.168.4.181:389" # two domain controllers - don't forget the port!
AUTH_LDAP_BIND_DN="string:CN=directus,OU=TEST,DC=DDC,DC=LOCAL"
AUTH_LDAP_BIND_PASSWORD="MYSAFEPASSWORD"
AUTH_LDAP_USER_DN="string:DC=DDC,DC=LOCAL"
AUTH_LDAP_USER_ATTRIBUTE="sAMAccountName"
AUTH_LDAP_USER_SCOPE="sub"
AUTH_LDAP_MAIL_ATTRIBUTE="mail"
AUTH_LDAP_FIRST_NAME_ATTRIBUTE="givenName"
AUTH_LDAP_LAST_NAME_ATTRIBUTE="sn"
AUTH_LDAP_GROUP_DN="string:DC=DDC,DC=LOCAL"
AUTH_LDAP_GROUP_ATTRIBUTE="member"
AUTH_LDAP_GROUP_SCOPE="sub"
AUTH_LDAP_DEFAULT_ROLE_ID="f8ba4321-19c3-4e67-bb22-0aef5d78d9af"
```

**Comment by paescuj** [comment]
Thank you very much for the feedback, @fusscreme! This is much appreciated and I'm glad to hear that is is working for you now!
