### ISSUE TITLE
missing auto populate button for ui time

### ISSUE THREAD

**Issue by airbenich** [directus/directus#1997]
## Version Info
  - Directus version and branch: 6.4.4 develop
  - PHP version: 7.1
  - MySQL version: n/a
  - Web server: PLESK with Apache & nginx for static data
  - OS name and version: CentOS

## Expected Behavior
The Time UI in directus should have an option to switch on and off the auto population.

## Actual Behavior
Auto-Populate is default when field ist empty / null.

**Comment by benhaynes** [comment]
Thanks @airbenich – all feature requests should be submitted over here so things start organized and can be voted on by the community: https://request.getdirectus.com

Or send over a PR! 😉
