### ISSUE TITLE
login stuck forever on data loading - javascript error in console

### ISSUE THREAD

**Issue by kjj77** [directus/directus#1998]
## Version Info
  - Directus version and branch: (Or commit hash) 6.4.4
  - PHP version:  5.6.28
  - MySQL version: mysqlnd 5.0.11-dev - 20120503
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: Windows 10

## Expected Behavior
After using it for a day to create my tables, relationships etc., when I now try to login it's stuck forever on loading data. Tested on Chrome, Chrome incognito, Firefox, Edge (it seems like a sort of Directus cache preventing the access). It manifests as javascript errors in the log. It's a local install so I cannot give you a link to test it online.

## Actual Behavior
stuck forever loading data

## Steps to Reproduce
 1. login
 2. 
 3. 

## Schema Dump, Logs, or Screenshots
![image](https://user-images.githubusercontent.com/34485550/33897934-260d93ea-df67-11e7-8fd5-d0783fbe4a59.png)

**Comment by kjj77** [comment]
Here it is, thanks !
[directus (3).zip](https://github.com/directus/directus/files/1552920/directus.3.zip)

**Comment by kjj77** [comment]
Hi guys, just to test I completely wiped my database and directus folder, and did a clean reinstall with git + composer, and a clean db install. And I had the same problem at the login again, without ever entering Directus myself ! The only way to make it work on my machine is to actually download it from the build version (on the getdirectus.com site). That works flawlessly (until, I guess, the problem will appear again, because first time I installed it from the build too). So to me this is NOT an issue with my schema anymore, but more with my configuration; yet it's a major issue for those wanting to test Directus locally.

**Comment by jedimonkey** [comment]
We had a similar sort  of issue earlier this week. I've set up a running docker instance and we have been happily using it for a couple of weeks.  But then one morning, both me and another developer were unable to log in.  Similar problem to you - just sat there loading data.  The api kept working and the db was accessible (I had a phpmyadmin talking to it fine).  I had to leave it to work on something else and by the afternoon it appeared to resolve itself for both myself/other dev.  Really really odd.  :-/

**Comment by WellingGuzman** [comment]
Maybe this is an issue with your "directus_path" in your `config.php`? I wonder why do you the browser is looking for a `main.js` which should be bundled into the `directus.min.js` file.

When you git clone, which branch do you use?

I'd call cache, but as you mentioned that you tested in different browser, that idea fall behind.

**Comment by rijkvanzanten** [comment]
This issue has been closed due to inactivity. If this error pops up again we'll re-open it.
