### ISSUE TITLE
Calendar view one day added (end date) when an event is moved

### ISSUE THREAD

**Issue by baudryj** [directus/directus#19995]
### Describe the Bug

When you move an event with a start and end date in the calendar layer, the end date add each time 1 day more.

Ex : I you create an event  2 days long and you move it, it becomes 3 days long

My simple data model :
![Capture du 2023-10-11 09-18-21](https://github.com/directus/directus/assets/259649/05f0548c-faad-4e02-bc06-b868ac88157a)

Create an event
![Capture du 2023-10-11 09-24-28](https://github.com/directus/directus/assets/259649/ec0a1b50-cb96-4dda-a48d-0bbea4c87657)

Move the event below and refresh
![Capture du 2023-10-11 09-25-02](https://github.com/directus/directus/assets/259649/a279c978-798c-4ebc-9835-ebfba46ffba8)

### To Reproduce

1/ Create a calendar view
2/ Add an event with start and end date (day format / no time) - 2 days between start and end
3/ Move this event in the calendar view
4/ Refresh the page
5/ The end date has moved +1 day - now 3 days between start and end

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by DanielBiegler** [comment]
Hi there! Cant reproduce both in dev and prod, see:

[Screencast from 11.10.2023 13:15:23.webm](https://github.com/directus/directus/assets/14810858/04dc574f-9758-407f-ba04-a6a438969e06)

Is it possible that you have set your `On Update` to save the current time?

**Comment by baudryj** [comment]
Yes exact only the **date** type format is affected.
The date type allow to extend the period directly in the calendar layout (not date time format)

https://www.loom.com/share/4ba20c83cee04172a73ab0c9a65a4dd9
