### ISSUE TITLE
M2M relationships with no duplicates buggy - multiple records still created

### ISSUE THREAD

**Issue by jedimonkey** [directus/directus#1999]
## Version Info
  - Directus version and branch: (Or commit hash) 6.4.4
  - PHP version: 7.1.9
  - MySQL version: 5.5
  - Web server: (Ex. Apache, nginx or IIS?) Nginx (running from docker)
  - OS name and version: Docker container

## Expected Behavior
When creating a M2M relationship, you create a junction table which tracks the relationships.  Enabling 'no duplicates' should mean that no duplicate records are ever created and sorting work.

## Actual Behavior
You are still able to add duplicates via the interface, which then in turn saves to the database.  However upon editing the record, it only shows you unique junctions.  Upon investigating the database, I found multiple joins.  This affects sorting as sort values are assigned, but due to the duplicates you may get inconsistent order.  And once you have duplicates you also get odd behaviour when removing junction records as you may remove a junction, save and then reedit the page shows the junction like it was never removed (as only a duplicate was removed).  If you clear out all duplicates, functionality works as intended.

## Steps to Reproduce
 1. Create 2 tables, A, B and Joiner (no status required for Joiner)
 2. Add a column to B, 'title' (text)
 3. Add a 2 columns to Joiner, 'a_ref' (numeric) and 'b_ref' (numeric)
 4. Add a column to A, 'Bs' (many to many, a.id => joiner.a_ref & joiner.b_ref => b.id) See:
![image](https://user-images.githubusercontent.com/5734286/33943781-009ed10c-e055-11e7-837f-89ee7ff8f5f9.png)  Ensure that No Duplicates are set. and put 'title' in for the visible/filtering columns and remove ability to add records.
 5. Create 3 test B records (B1, B2, B3)
 6. Create record under A, click 'choose' and add in B1 & B2 & B3.  Order to B1, B2, B3 (save)
 7. Re-edit, change order and save (ensure it's working)
 8. Re-edit and ensure order is B1, B2, B3 (click save).
 9. Re-edit and click 'choose' and add in B2, B3.  Take note of order but don't change - (mine is B1, B2, B3, B2, B3) - click save
 10. Re-edit and you should see the order of B1, B3, B2.  Removing either B2 or B3 (or both) changes order, but still shows that it referenced in the junction.

**Comment by WellingGuzman** [comment]
Hey @jedimonkey, are the columns the exact data type? probably there's a bug in the API returning the actual type, can you confirm the API is returning the actual data type?

**Comment by rijkvanzanten** [comment]
Closed due to inactivity

**Comment by jedimonkey** [comment]
Wait! this is still an issue - I've got a PR with a potential fix, but seems to not have resolution on the best solution.  I can understand that this may be a low priority bug, but I'd still like to fix it.  There is a bunch of comments on this in #2001, however no decision on if my PR can be merged.  Can someone throw some ideas at the PR?

**Comment by rijkvanzanten** [comment]
Ahh! Gotcha. I'll go through it right away!

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/20)
