### ISSUE TITLE
Ws doesn't send event if multiple subscriptions and one doesn't match filters

### ISSUE THREAD

**Issue by Nihcep** [directus/directus#20003]
### Describe the Bug

When connecting multiple subscriptions to a same event with custom query, Directus stop trying to dispatch to subscription if one is not concerned. 
Eg : 
1 subscription is listening on task.create with filter on type === GOOGLE
1 subscription is listening on task.create with filter on type === MICROSOFT

An event with type === MICROSOFT is sent, Directus find both subscriptions, try to dispatch to the first one but as type === MICROSOFT, final payload to dispatch is empty. Directus don't look to the next subscriptions and therefore never send the event to the second one.

**I managed to fix this issue, I'm creating this issue to complain with the Pull Request Process.**

### To Reproduce

Create DataModel Task with a field type.

Create 1 subscription listening on task.create with filter on type === GOOGLE
Create 1 subscription listening on task.create with filter on type === MICROSOFT

(type === GOOGLE subscription must be registered BEFORE the MICROSOFT one).

Try to create a new task with type === MICROSOFT. Nothing will be send to the MICROSOFT subscription. 

### Directus Version

v13.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Are you using the `uid` field to distinguish between the 2 subscriptions? And how are you listening for the incoming messages? Some code examples would be helpful.

> I managed to fix this issue, I'm creating this issue to complain with the Pull Request Process.

Please do elaborate :)

**Comment by br41nslug** [comment]
Oh wow yeah you're absolutely right! That should not be a `return` statement there 🤔 Feel like creating a PR for that?
