### ISSUE TITLE
Unable to upload a CMS Thumbnail URL

### ISSUE THREAD

**Issue by shevaroller** [directus/directus#2000]
## Version Info
  - Directus version: v6.4.4
  - PHP version: 7.1.7
  - MySQL version: 5.7
  - Web server: Apache2
  - OS name and version: Docker 17.12.0-ce-rc2
  - File system: AWS S3

## Expected Behavior
 - Choosing an existing image for the admin panel logo should work.
 - Importing an image from the url  for the admin panel logo should work.

## Actual Behavior
 - Choosing an existing image for the admin panel logo throws an error.
 - Importing an image from the url  for the admin panel logo throws another error.

## Steps to Reproduce
 1. Go to Admin Settings -> Global
 2. Try choosing an existing image or importing from a url.

## Schema Dump, Logs, or Screenshots
When choosing an existing image:
`Uncaught TypeError: Cannot read property 'get' of undefined`
When importing from a url:
`Uncaught TypeError: Cannot read property 'getStatusColumnName' of undefined`

**Comment by WellingGuzman** [comment]
Hello @shevaroller this issue has been fixed by https://github.com/directus/directus/commit/2c1135cbb44f4157d5e919527ec7baa8b06876ee. (maybe duplicated https://github.com/directus/directus/issues/1961?)

We will be releasing 6.4.5 tomorrow.
