### ISSUE TITLE
Detail groups are not hidden on Condition false, only its childs

### ISSUE THREAD

**Issue by Pachat** [directus/directus#20021]
### Describe the Bug

When a Detail group has Condition false, its label is still visible

### To Reproduce

In a collection, create an Accordion with a Detail Group and put a condition for Hidden on Detail.
You may also create a field inside the Detail Group.

When the condition for Hidden on Detail is met, the field inside the Detail Group is hidden
but the Detail Group itself is not hidden.

### Directus Version

v10.2.6

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
Could you try with the latest version (currently 10.6.3)? IIRC some fixes landed in the past releases in this regard.

**Comment by Pachat** [comment]
Sure, I'd very much like to. 
But because of https://github.com/directus/directus/issues/19327#issuecomment-1694219563 I'm still stuck to v10.2.6

And patiently* waiting for a full resolution to update the version
* as it appear "not a top priority at the moment." https://github.com/directus/directus/issues/19327#issuecomment-1759234874

**Comment by paescuj** [comment]
> Sure, I'd very much like to. But because of [#19327 (comment)](https://github.com/directus/directus/issues/19327#issuecomment-1694219563) I'm still stuck to v10.2.6
> 
> And patiently* waiting for a full resolution to update the version
> 
>     * as it appear "not a top priority at the moment." [Update permissions still incorrect in 10.5.2 #19327 (comment)](https://github.com/directus/directus/issues/19327#issuecomment-1759234874)

See https://github.com/directus/directus/issues/20023#issuecomment-1761800806.

**Comment by rijkvanzanten** [comment]
I'm fairly sure this is the same underlying bug as #20023, but happy to reopen if this is confirmed to be an existing issue under 10.6.3 or later
