### ISSUE TITLE
select-radio for flow type is inconsistent for different language

### ISSUE THREAD

**Issue by aclisp** [directus/directus#20034]
### Describe the Bug

<img width="583" alt="image" src="https://github.com/directus/directus/assets/5406765/a0a0e20c-091d-4898-9082-a3f8b091b0f9">
<img width="591" alt="image" src="https://github.com/directus/directus/assets/5406765/4c74f4ed-3005-4d4d-8649-f80ad093e537">

The problem might be related to the grid class calculation. If English language is used, it is `grid-2`, however for Chinese it is `grid-4`.

https://github.com/directus/directus/blob/eb6c965c7218c1a668f19f46f1d55ca849f6eba8/app/src/interfaces/select-radio/select-radio.vue#L37-L54

### To Reproduce

Change the language of the user and re-login, go to Settings -> Flows -> Trigger Setup.

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by DanielBiegler** [comment]
Good find! Yes we change the width of depending on the amount of characters. Will need to see if we have a way to override that specifically.

**Comment by DanielBiegler** [comment]
By providing the props.width as `"half"` we would fix this but this has the side effect of longer languages spanning the entire row which wouldnt be a dealbreaker for me personally but we'd have to see what others think.

```ts
	if (props.width?.startsWith('half')) {
		if (widestOptionLength <= 10) return 'grid-2';
		return 'grid-1';
	}
```

| Header | Header |
|--------|--------|
| ![image](https://github.com/directus/directus/assets/14810858/40a43928-7a1b-4f65-ac0b-976ebbfcf150) | ![image](https://github.com/directus/directus/assets/14810858/b4a5eb1e-d3fb-49bf-9129-26a7a3a06c91) |
