### ISSUE TITLE
User can see item, although permission is set to 'only see own'

### ISSUE THREAD

**Issue by BennerGe** [directus/directus#2004]
## Version Info
  - Directus version and branch: 6.4.4

## Expected Behavior
User should only see his own table items, when permissions are set to 'only see own items'. 

## Actual Behavior
User can see table items of admin (probably also from other users, not tested).

## Schema Dump, Logs, or Screenshots
These are the group permissions, seen from admin account:
![group_permission](https://user-images.githubusercontent.com/26544180/34125318-2b997ee0-e436-11e7-9b38-fb794c3f212a.png)

These are the table entries, seen by 'Testnutzer'. The first entry is created by the admin account.
![user_test_table](https://user-images.githubusercontent.com/26544180/34125319-2dff5de4-e436-11e7-857c-167672ab91b9.png)

Do I miss something here? How does Directus check the owner of the entry?  Must there be a column of type 'user' in the table?

**Comment by BennerGe** [comment]
And the other way around, users cannot edit their own items, even when permissions for ```edit``` are set to ```allow edit own items```

**Comment by WellingGuzman** [comment]
Hey @BennerGe, How the table looks like? the table must have a  `user_created` interface to make sure who's the owner of the record.

**Comment by BennerGe** [comment]
That was the missing point, thank you. :+1: 
Maybe a little hint above the permission table in the app would be helpful.

**Comment by rijkvanzanten** [comment]
I don't know if a permanent note is the best option, since it's not applicable to all permissions, but it should at least be documented somewhere. I should add it as a note to the medium article about permissions. @wellingguzman, could you check if it's in the regular docs?

**Comment by u12206050** [comment]
This should definitely be more clear, as I also have been sitting with this issue for a day now.

**Comment by hamzamu** [comment]
That's cool, however, needs more explanation and examples in the docs for the JS SDK and the custom API endpoints. :)
