### ISSUE TITLE
Graph in insight stay purple and sometime disappear

### ISSUE THREAD

**Issue by triplecasquette** [directus/directus#20042]
### Describe the Bug

I use the self-hosted version (with cli and NGinx on my own VPS). Latest version. With a mysql database. Nothing more specific comes to mind here.

When I want to create a graph using the following parameters
<img width="839" alt="Capture_decran_2023-10-16_a_10 12 01" src="https://github.com/directus/directus/assets/81014220/99881430-a41a-413e-9798-70439affc2f7">

I am confronted with an unexpected behaviour:
<img width="1049" alt="Capture_decran_2023-10-16_a_10 12 16" src="https://github.com/directus/directus/assets/81014220/9660bf56-f524-409a-abde-4291feb5b6b1">

The graph remains purple (because that's probably the default colour, even if the project colour is changed and styles are added with the excellent theme builder :D

What's even crazier is that after changing some settings, the graphic disappears and never appears again. Until I create it again
<img width="1079" alt="Capture_decran_2023-10-16_a_10 14 16" src="https://github.com/directus/directus/assets/81014220/efa47ea0-d268-485e-ad1d-15ab572a1c88">

### To Reproduce

Simply create a pie chart in an Insight panel, changing the colour.

### Directus Version

V10.6.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by ConnorSimply** [comment]
@adacadabrafr Few questions...

- Are there any errors showing in the browser console logs?
- Do you have any extensions installed?

**Comment by adacadabrafr** [comment]
I will check tommorrow but I can say that I create a new Directus instance (for another project) and this time it works.
I don't know what was the difference, because it's also a VPS maybe the node version on some package on the VPS my colleague have or not on both. I'll Let you know if I noticed something.

**Comment by adacadabrafr** [comment]
_By the way if you know how to display the text of a select instead of it's value on this graph I will appreciate :)_

**Comment by adacadabrafr** [comment]
Hi @ConnorSimply,
I have no extension but noticed the behavior about the **color** is working when using colors of Directus (when click on the picker I have a **selection of colors** I talk about these one) But when I use a **custom color** for example : _#049DBF_ The color get back to default Directus Purple.

sorry I don't have much time at the moment
