### ISSUE TITLE
[Feature Request] possibility to hide junction table 

### ISSUE THREAD

**Issue by rmNyro** [directus/directus#2005]
Hi everyone,

I want to start by saying I like your product very much (altho I'm sad you use relational database, I think it'd be better with some noSQL or something more "fluid", but that's another topic).

I recently have seen a behavior that is to me not user friendly.
I wanted to have a many-to-many relation so I created a basic junction table like so :

| TABLE                      |
|----------------------------|
| list_id          INT(11) |
| element_id  INT(11) |

Nothing fancy but I thought I could make it invisible to users so they are not tempted to edit the table directly. BUT I cannot as it triggers a "permission denied" error which is fine because it's intended.

So maybe you already had plan for the future regarding a distinct separation between "dev admin" (database designer/maintainer) and "end user admin" (the people to use and fill the db) but if not I think that would be an awesome feature.
In the meantime, adding the option to "prevent" some user to directly modify but allow them to indirectly modify some tables, like junction tables. :)

Anyway, I hope I've been precise enough and I wish you the best.
Cheers.

**Comment by rijkvanzanten** [comment]
Hey @rmNyro!

Have you tried the _Hide Table_ option in the junction table's settings view? That sounds like exactly what you are looking for :) This option hides the table for every user, but still allows Directus to manage it.

![image](https://user-images.githubusercontent.com/9141017/34222234-d94dee4c-e588-11e7-945b-4b6fe14c26d0.png)

If that's too "global" for you, you could also blacklist the table from showing up in the system for this specific user's usergroup or override the nav completely for finegrain control. Our Medium article on permissions goes a little further in depth on setting up user groups: [Medium — Working with Permissions](https://medium.com/directus/working-with-permissions-7c6aa33bde1d).

Let me know if that does the trick for you 😄

**Comment by rmNyro** [comment]
Well, I completely missed the feature. I think it'll work perfectly in my case.
But I think it's is indeed too "global".
Anyway, thanks for the tip. :)
