### ISSUE TITLE
Allow to define `from` from `MailService.send`

### ISSUE THREAD

**Issue by stafyniaksacha** [directus/directus#20053]
### Describe the Improvement

Today, it's not possible to override sender name when sending emails, we can only change sender email

https://github.com/directus/directus/blob/fb65446f1d4196a446d474d73b7f4315be3fe715/api/src/services/mail/index.ts#L58

A better option would be something like:
```ts
const from = options.from || `${defaultTemplateData.projectName} <${(env['EMAIL_FROM'] as string)}>`; 
```

With this, we would have total control over the from field.

If you agree, I can make a PR

**Comment by paescuj** [comment]
I don't see an issue with this but I'd like to have this confirmed. What do you think @br41nslug?

Out of curiosity: What's the use case for this @stafyniaksacha?

**Comment by JonathanSchndr** [comment]
Note: Should this be extended, I would also ask that in the PR the flow of "Send Mail" also receives a From directly. :)

**Comment by JonathanSchndr** [comment]
Goes with it: https://github.com/directus/directus/discussions/11042

**Comment by paescuj** [comment]
I overlooked that you suggested the whole FROM to be customizable. However, that should not be allowed! Only the display name should be. (Thanks for pointing out @br41nslug)

```js
const from = `${options.from ?? defaultTemplateData.projectName} <${(env['EMAIL_FROM'] as string)}>`; 
// instead of
const from = options.from || `${defaultTemplateData.projectName} <${(env['EMAIL_FROM'] as string)}>`; 
```

**Comment by br41nslug** [comment]
> I overlooked that you suggested the whole FROM to be customizable. However, that should not be allowed! Only the display name should be. (Thanks for pointing out @br41nslug)
> 
> ```js
> const from = `${options.from ?? defaultTemplateData.projectName} <${(env['EMAIL_FROM'] as string)}>`; 
> // instead of
> const from = options.from || `${defaultTemplateData.projectName} <${(env['EMAIL_FROM'] as string)}>`; 
> ```

This suggestion would however be a breaking change 😬 for people currently using `options.from` to override the email address instead of the name

**Comment by paescuj** [comment]
Yeah, we should introduce a new option for this like `options.displayName`

**Comment by rijkvanzanten** [comment]
I'm also not convinced that's something that should necessarily be overridden on a per-email basis. This is one of those subjects that can very easily become a security issue if individual emails can be sent with different names and email FROMs. I'd be down to make this another environment variable, but have some worries about letting the FROM field be changed per request 👍🏻

**Comment by rijkvanzanten** [comment]
Seeing this is quickly turning into a bigger discussion on how this should work as a new feature rather than a tiny tweak, lets move it to [a new Feature Request](https://github.com/directus/directus/discussions/new?category=feature-requests) 👍🏻
