### ISSUE TITLE
Incorrect M2O relationship foreign key

### ISSUE THREAD

**Issue by WayneEld** [directus/directus#20067]
### Describe the Bug

Hi There.

I have a postgres DB that has been configured with the DB schema and relationships. I have a table with a many-to-one relationship: 
`table: record_list` - `field: data_source_code ` -> 
`table: data_source` - `field: code`. 

However when installing Directus over the schema I can see that the M2O relationship points to the `id` field of `data_source` and not `code` as the schema attached would suggest. (Please see attached for Directus relationship screen shot)

Even if attempt to configure this relationship within the `directus_relations` table it always seems to point to the `id` field.

Is this a Directus issue that infers that the foreign key will be `id`.

<img width="496" alt="Screenshot 2023-10-18 at 15 23 42" src="https://github.com/directus/directus/assets/12561623/36c6ab04-db14-40c0-a75d-103470c37bfa">
<img width="846" alt="Screenshot 2023-10-18 at 15 25 36" src="https://github.com/directus/directus/assets/12561623/abcf61e2-57b4-4bad-84fb-9b428e62ca54">

### To Reproduce

Difficult to reproduce with the DB schema.

### Directus Version

v10.6.3

### Postgres Version
v14.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
> Difficult to reproduce with the DB schema.

Does that mean it's only reproducible in some specific cases?
Would you be able to share the corresponding schema?

**Comment by br41nslug** [comment]
The op means that you cannot use any other field than the PrimaryKey form many-to-one relations (or any for that matter). This is true but not sure whether that can be considered a bug or a design choice.
![image](https://github.com/directus/directus/assets/9389634/1e12002f-9177-4ee4-9465-b1a275e16f4c)

**Comment by WayneEld** [comment]
> > Difficult to reproduce with the DB schema.
> 
> Does that mean it's only reproducible in some specific cases? Would you be able to share the corresponding schema?

@paescuj here is the DB schema and sample data on top of Directus as a zip. Some data is scrambled but the relationship and example is there.  https://www.dropbox.com/scl/fi/4a81rz7b7dawct5masmf9/tester.zip?rlkey=m3ltmopv7tu02mj7zfi6emb1r&dl=0

**Comment by WayneEld** [comment]
> The op means that you cannot use any other field than the PrimaryKey for many-to-one relations (or any relation for that matter). This is true but not sure whether that can be considered a bug or a design choice. It can surely feel like a bug if you're bringing your own database.
> ![image](https://user-images.githubusercontent.com/9389634/276551406-1e12002f-9177-4ee4-9465-b1a275e16f4c.png)

@br41nslug thanks for the insight. I am hoping that this a small bug and not a design choice. Directus seems to infer this id primary key relationship, and as you mentioned, with bringing your own database to the table, this may cause an issue.

**Comment by rijkvanzanten** [comment]
@WayneEld Directus is currently built/designed to rely on the relationship using a foreign key to the related table's primary key. This is currently working as expected (tho we're overhauling our data abstraction to support non-PK foreign keys in a next version 🙂)
