### ISSUE TITLE
O2M Fails silently when wrong datatype is used for related table

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#2006]
## Version Info
  - Directus version and branch: 6.4.5 release

## Behavior
When the "wrong" datatype is used for the related primary key field, the O2M doesn't display the selected values. They are saved however.

For example in this table structure:

**Table A**

| column | interface | datatype |
|-------|-----|-------|
| id | primary_key    | INT |
| relation | one-to-many | ALIAS |

**Table B**

| column | interface | datatype |
|-----|-----|-------|
| title | text_input | VARCHAR |
| table_a_id | text_input | VARCHAR |

The selected items won't be displayed in the interface. For some reason, this is caused by the fact that `table_a_id` is set to a `VARCHAR` type, instead of matching the `INT` of the `id` it is going to store.

## Schema Dump, Logs, or Screenshots

[one-to-many-dump.sql.txt](https://github.com/directus/directus/files/1577317/one-to-many-dump.sql.txt)

**Comment by rijkvanzanten** [comment]
At the moment, all core developers are working fulltime on the next major version of the platform, so I'll have to leave this open as a help-wanted. If anyone is inclined to take a swing at fixing this, a PR is very welcome 😄

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/21)
