### ISSUE TITLE
Theming error in production

### ISSUE THREAD

**Issue by br41nslug** [directus/directus#20064]
### Describe the Bug

When setting up Directus with the `next` branch for the first time (aka new database, no extensions and running in production mode). We are getting errors in Theming, what looks like an incorrect font and the same Dark mode issues mentioned in https://github.com/directus/directus/issues/20044

This seems to only happen in production so getting to the source of those console errors will take some debugging.

Darkmode Firefox:
![firefox_m94vIGAIEd](https://github.com/directus/directus/assets/9389634/c25310b9-98e2-4217-9cf2-93ad76f85d92)
![image](https://github.com/directus/directus/assets/9389634/8d7fae10-7a20-4d8b-b59a-cb1b649f0cd9)

Lightmode Chrome:
![image](https://github.com/directus/directus/assets/9389634/45aacca2-942d-4361-a9cf-9079a8c8aca5)
![image](https://github.com/directus/directus/assets/9389634/6ec2687d-2eaa-4990-aa66-1defe06b22eb)

In development mode everything looks fine (using the same API/DB):
![image](https://github.com/directus/directus/assets/9389634/301b93c5-4888-4289-a82a-974f3c7b9f46)
![image](https://github.com/directus/directus/assets/9389634/b1f5d8f3-655f-44ec-9073-90754715e4ec)

### To Reproduce

1. Create a new instance with a new database
2. Run the instance in production mode
3. Navigate to the login screen in Firefox or Chrome
4. [optional] Login

### Directus Version

next

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
Seems to be related to this issue, working with pinia stores in separate packages https://github.com/vuejs/pinia/discussions/1073#discussioncomment-6297570

**Comment by br41nslug** [comment]
The `externals` solution suggested in the issue doesnt work in my tests. The `window.pinia` workaround does but i'd rather not use that in any production capacity 😬 
![image](https://github.com/directus/directus/assets/9389634/e86b30ca-8766-42b4-b9f6-3593014dc548)
![image](https://github.com/directus/directus/assets/9389634/82d7ecc6-3356-4f2b-9e4b-db717bfd59df)

Which leads me to the conclusion that the only "nice solution" would be to migrate at least the store from `@directus/themes` back into the app 😬 @rijkvanzanten

**Comment by paescuj** [comment]
> Which leads me to the conclusion that the only "nice solution" would be to migrate at least the store from @directus/themes back into the app 😬 @rijkvanzanten

The problem is the store is also used in `use-theme.ts` so I guess we would have to migrate the whole package... 🙈 

Another thing we could do though is to move the store to `@directus/store` and then import it from there in `@directus/app` as well as in `@directus/theme`.
Would probably not even be that bad, assuming that's what the `@directus/store` package is for.

**Comment by rijkvanzanten** [comment]
This is wild! I'm sure there must be an in-between solution.. right? What's the root cause of this? Is it because we're bundling / minifying?

**Comment by paescuj** [comment]
Got it running 🥳 Tried out different things, now need to figure what actually fixed it. PR coming afterwards 👍

**Comment by br41nslug** [comment]
![image](https://github.com/directus/directus/assets/9389634/e67dcd91-a156-4d52-b8a8-238f1dba7a7d)
