### ISSUE TITLE
Flows Drag & drop looks broken on edition

### ISSUE THREAD

**Issue by arhubi** [directus/directus#20074]
### Describe the Bug

Edition of an existing flow looks to be broken. 
When I try to drag a flow operation, it's moved to a random place.

Console shows issues with SVGs:
<img width="642" alt="Screenshot 2023-10-19 at 07 37 26" src="https://github.com/directus/directus/assets/54635794/a82806f9-7cdb-4b4c-ad54-008e1388ea6e">

### To Reproduce

Issue met with Chrome (latest) and Safari (latest), even on private navigation (no enabled plugin)

1. Create a flow with a few operations
2. Save the flow
3. Go back on the flow and try to move an operation using drag and drop. Item will be pushed very far to the right, or randomly (NaN position).

![CleanShot 2023-10-19 at 07 34 55](https://github.com/directus/directus/assets/54635794/e5a9b750-34ca-429d-b51e-6ad5acf3650c)

### Directus Version

10.6.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
I have not been able to reproduce this on the latest version with the latest chrome. Could this perhaps be OS related?


https://github.com/directus/directus/assets/9389634/63eb557b-a8c9-4e36-90f1-50d68e418bd0



Happy to reopen the issue when more information becomes available

**Comment by arhubi** [comment]
Hello @br41nslug, thanks for your quick answer!

After a long analysis, I noticed that my DB had serious issues (e.g.: no way to add M2M or O2M relations) due to migration from Directus 8 / SQLite, + other bad moves I made at the beginning of my projecy.

I managed to take a fresh start, and it works like a charm now. ✨
