### ISSUE TITLE
Content version key/name length

### ISSUE THREAD

**Issue by br41nslug** [directus/directus#20081]
### Describe the Bug

Currently the frontend form for adding a new version does not have any limits set at all, while this fails gracefully on save it is not great UX having to go back and count the characters manually.

At the least we should set a limit on the inputs to match the database, which is currently 255. But since our UI elements don't seem designed to deal with such long names i'd recommend lowering the database limit to for instance 50 or 80 characters.

### To Reproduce

1. enable content versioning on a table
2. create a new version with a very long key/name

https://github.com/directus/directus/assets/9389634/38292850-0201-4cd7-996e-2c8d8817d6f7

![firefox_t0Jlzb6sHh](https://github.com/directus/directus/assets/9389634/6e68b42d-dde2-464f-a00e-482b59a673a4)
![firefox_a436TTxeAv](https://github.com/directus/directus/assets/9389634/ff6f177e-4159-46fe-a902-7b5a470dca28)

### Directus Version

next

### Hosting Strategy

Self-Hosted (Custom)

**Comment by azrikahar** [comment]
Resolved by #20097
