### ISSUE TITLE
Content version save and stay

### ISSUE THREAD

**Issue by br41nslug** [directus/directus#20086]
### Describe the Bug

Currently when editing a Content Version your only option is to "Save and Quit" which returns you back to the collection overview. This is very unintuitive and requires multiple clicks to get back to the specific content version you were editing.

The same dropdown from the main branch is there but only contains a revert option. The behavior i would expect here is that it would take me back to the "main branch" of the item. 

And i think having the choice of some of these options would be nice:
- Save and Stay
- Save and go to Main
- Save and Quit (go to Collection)

### To Reproduce

1. enable content versioning on a collection
2. create an item on that collection
3. create a content version for that item
4. make some changes and save

https://github.com/directus/directus/assets/9389634/855c8ab3-7e61-429a-bc2a-93e8b7a03c91

### Directus Version

next

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
I agree that the other options should be available as well.
On a side note: Right now, it is possible to "Save and Stay" by using the keyboard shortcut

**Comment by br41nslug** [comment]
Wait the shortcut does work? 😂 didnt even test
