### ISSUE TITLE
CMD in Dockerfile breaks `podman ps`

### ISSUE THREAD

**Issue by felixfischer** [directus/directus#20080]
### Describe the Improvement

Directus' CMD directive in the Dockerfile contains tabs (`\t`) which break the table view of `podman ps` (I assume `docker ps` works the same). See how some data is in the wrong column in the last line of this example:

```
IMAGE          COMMAND          CREATED      STATUS            PORTS             NAMES
mariadb        mariadbd         1 day ago    Up 2 hours ago    3306->3306/tcp    mariadb-10
vaultwarden    /start.sh        1 day ago    Up 2 hours ago    50020->80/tcp     vaultwarden
directus       /bin/sh -c :     && ...       2 hours ago       Up 2 hours ago    50955->8055/tcp  directus
```

This is due to the CMD written like this:

```
CMD : \
	&& node /directus/cli.js bootstrap \
	&& node /directus/cli.js start \
	;
```

Ideas how to fix this:

* Modify the Dockerfile so CMD does not include tabs, e.g.: `CMD node cli.js bootstrap && node cli.js start`
* Introduce a new CLI command that combines `start` and `bootstrap` into one, e.g.: `start --bootstrap`

I can create a PR if it helps.

**Comment by felixfischer** [comment]
@paescuj Could you be using a different Dockerfile? Because there is no `docker-entrypoint.sh` mentioned in the [Dockerfile](https://github.com/directus/directus/blob/main/Dockerfile).

**Comment by paescuj** [comment]
No, this is inherited from the base image (`node:alpine`)
