### ISSUE TITLE
PM2 ecosystem.config.js not working with Directus 9.25.0 and above

### ISSUE THREAD

**Issue by mirino83** [directus/directus#20091]
### Describe the Bug

Versions:
Node 18.18.2
Directus 10.6.2
PM2 5.2.2

PM2 ecosystem.config.js is not working with Directus 9.25.0 and above.

### To Reproduce

ecosystem.config.js file:
```
module.exports = {
    apps: [
        {
            name: 'app',
            exec_mode: 'cluster',
            instances: '2',
            script: './node_modules/.bin/directus',
            args: 'start'
        }
    ]
}
```

When using clean install of Directus 9.24.0 and running:
`pm2 start ecosystem.config.js`
Everything works as expected.

When updating Directus to whatever version above 9.25.0 included and running:
`pm2 start ecosystem.config.js`

I get this error:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/xxxxxxx/code/directus/node_modules/directus/cli.js not supported.
Instead change the require of cli.js in null to a dynamic import() which is available in all CommonJS modules.
    at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:303:25
    at wrapper (/usr/local/lib/node_modules/pm2/node_modules/async/internal/once.js:12:16)
    at next (/usr/local/lib/node_modules/pm2/node_modules/async/waterfall.js:96:20)
    at /usr/local/lib/node_modules/pm2/node_modules/async/internal/onlyOnce.js:12:16
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/pm2/lib/Utility.js:186:13)
    at WriteStream.emit (node:events:517:28)
    at FSReqCallback.oncomplete (node:fs:200:23)
| App name:xxxxxxx id:1 disconnected
| App [xxxxx:1] exited with code [0] via signal [SIGINT]
```

Renaming ecosystem.config.js to ecosystem.config.cjs did not help.

### Directus Version

10.6.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
This sounds like a PM2 configuration issue, have a look at this PR for examples on how to configure Directus with PM2 https://github.com/directus/directus/pull/18998

**Comment by rijkvanzanten** [comment]
> @br41nslug nope. it's from Directus side I faced this problem before. I think u should set the type to module inside the package.json file

it is 

https://github.com/directus/directus/blob/e987c1990e720592750a53eb19f6c3252d98238f/api/package.json#L49

The problem is that the PM2 config file itself should be renamed to the `.cjs` extension, as the type: module sets node's default to ESM which PM2 doesn't support

**Comment by rijkvanzanten** [comment]
Also we'll be shipping an "official" PM2 file soon 🙂 

https://github.com/directus/directus/pull/18998

**Comment by mirino83** [comment]
Setting the `type: "module"` in package.json and renaming ecosystem.config.js to ecosystem.config.cjs resolved the issue, thank you

**Comment by deounix** [comment]
@rijkvanzanten, thank you. PM2 is essential for handling high loads.

I have another idea that's a bit different. What if you consider switching to React for Directus? I've noticed that some other CMS projects, which may not be as powerful as Directus, are using React. React is very popular and could be a big improvement for the Directus community. It's even more popular than Vue.

Just like when you moved Directus from PHP to Node.js, which had a significant impact, I believe adopting React could be similarly game-changing.

Once again, thanks for the good work 🫡🫡

**Comment by rijkvanzanten** [comment]
> What if you consider switching to React for Directus?

This is very off-topic in this thread, and I'm happy to elaborate on Discord or in a discussion, but the short answer is _no_. Without any context, I disagree it would be an improvement for the core codebase, nor am I convinced it'd be an upgrade for the community.
