### ISSUE TITLE
Msgpack support?

### ISSUE THREAD

**Issue by 1zaak** [directus/directus#2010]
Just a suggestion for Directus API. Any plans to support msgpack as an alternative to JSON?

**Comment by benhaynes** [comment]
It's not on or roadmap as of now, but it could be if added and upvoted enough on https://request.getdirectus.com

Thanks for the suggestion!

**Comment by WellingGuzman** [comment]
@1zaak Also you can use the `response` filter to change the output value. But probably have to change the response content type. 

Ref: https://github.com/directus/docs/blob/master/developer-guide/hooks.md
