### ISSUE TITLE
Preset preview

### ISSUE THREAD

**Issue by HemboPagi** [directus/directus#20119]
### Describe the Bug

I have collection with multiple columns, one of them called _reference_.

I have created preset to show content basesd on _reference_.

If only one row is returned nothing is displayed.
If two rows are returned one is displayed.
And if three is returned two is displayed.

<img width="754" alt="Screenshot 2023-10-23 at 12 42 40" src="https://github.com/directus/directus/assets/95413906/339ded27-d594-47b8-a01e-54a92fe99923">

All presets are dispalyed correctly in collection managemnt.

<img width="1135" alt="Screenshot 2023-10-23 at 12 43 44" src="https://github.com/directus/directus/assets/95413906/9a0364f1-6708-4338-82ca-bde38af92a65">

### To Reproduce

- Create collection with multiple fileds
- Add data so you coud apply filters based on one column
- Create preset and add filter where the result returns only one field
- No results is dispayed in preset preview

### Directus Version

10.3.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
Could you try updating to the latest version? We'll reopen if the issue persists in the 10.7 and up 👍🏻

**Comment by HemboPagi** [comment]
Tested it in 10.6.4 and it seems working
