### ISSUE TITLE
Public group has options for nav override

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#2012]
## Version Info
  - Directus version and branch: Directus 6 latest

The public group has options for nav override and nav blacklist in the permissions group view, but you can't login as a "public" user to begin with, so these are never being used.

**Comment by WellingGuzman** [comment]
Hey @rijkvanzanten, would you care to explain this to me, I didn't understand the issue.

**Comment by rijkvanzanten** [comment]
@wellingguzman The field for the nav override section is available to enter for the public group. This setting has no effect whatsoever since people can’t login to directus from the public group to begin with.

**Comment by WellingGuzman** [comment]
Still don't get it, from where you can enter this information using public group credentials? as Admin in the web app? and since it has no effect where is the issue? You are talking about removing this information from the web app?

**Comment by rijkvanzanten** [comment]
In the directus admin application when you’re editing user groups you can also edit the public group. The settings you can alter here are useless, since they’re not used at all. To avoid confusion, these should be removed. Therefore, it’s a trivial optimization.

You can treat this issue as a reminder for 7.0 that we don’t make the same mistake

**Comment by rijkvanzanten** [comment]
At the moment, all core developers are working fulltime on the next major version of the platform, so I'll have to leave this open as a help-wanted. If anyone is inclined to take a swing at fixing this, a PR is very welcome 😄

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/22)
