### ISSUE TITLE
SDK: Add query parameter to readCollections and readFields

### ISSUE THREAD

**Issue by jofmi** [directus/directus#20134]
### Describe the Improvement

Most read functions of the SDK like `readItems` or `readRoles` have a parameter query that can be used to filter the results. See https://docs.directus.io/packages/@directus/sdk/rest/functions/function.readItems.html

This would also be useful for `readCollections` and `readFields`.

**Comment by rijkvanzanten** [comment]
The SDK follows the APIs, which currently don't support query params on some of the system endpoints, like collections and fields https://docs.directus.io/reference/system/collections.html#query-parameters

**Comment by jofmi** [comment]
Thanks! Would it make sense to convert this issue into a feature request to support query parameters on these endpoints?

**Comment by rijkvanzanten** [comment]
@jofmi That'd make a lot of sense 🙂 https://github.com/directus/directus/discussions/new?category=feature-requests
