### ISSUE TITLE
No task queue available and all Workers are busy

### ISSUE THREAD

**Issue by paulvonber** [directus/directus#20149]
### Describe the Bug

<img width="591" alt="image" src="https://github.com/directus/directus/assets/37245111/78b85fdf-cae6-480b-a687-aecfddc42cad">

<img width="1369" alt="image" src="https://github.com/directus/directus/assets/37245111/72dabd33-f8af-4582-9434-6348722f912b">

after upgrade to v10.7.0 constantly receiving this error while uploading CSV file to collection.
Tried to drop containers start again etc... nothing helps and not really sure where to look at.

### To Reproduce

Try to upload CSV file to any collection

### Directus Version

10.7.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Did you limit the resources for this Docker container? Is this error occurring right from the beginning (first CSV import after start of instance)? Is it a large CSV file?

**Comment by paulvonber** [comment]
No not limiting anything, docker has plenty of resources
Yes first start then upload
No it's super small 497 bytes just few entries

**Comment by paescuj** [comment]
Thanks!

Could you run the following two commands inside your Docker container and post the output here?
```bash
cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l
     
cat /proc/cpuinfo | grep "core id" | sort | uniq | wc -l
```

You can run it like this, for example:
```bash
# To get the container ID
docker ps

docker exec <ID> <COMMAND>
```

**Comment by paulvonber** [comment]
<img width="631" alt="image" src="https://github.com/directus/directus/assets/37245111/de292e2d-5027-483c-8f6e-b18f06ad1706">

**Comment by paescuj** [comment]
Thanks again! That's interesting, I would have expected the numbers to be > 0. Would you mind posting the whole output from `cat /proc/cpuinfo`?

**Comment by paulvonber** [comment]
yeah 0 doesn't tell a lot :) 
sure, here you go:
<img width="1667" alt="image" src="https://github.com/directus/directus/assets/37245111/cb1585f7-a50c-4501-9e13-4c49a437a38b">

**Comment by paescuj** [comment]
Do you use the `arm64` version of the Docker image, i.e. running on a Apple M1/M2?

**Comment by paulvonber** [comment]
> Do you use the `arm64` version of the Docker image, i.e. running on a Apple M1/M2?

Yes I do, running on M1

**Comment by paescuj** [comment]
As outlined in #20199, this is an issue with Tinypool (used in Directus as worker pool for CSV imports) where the CPU count doesn't work on _ARM machines_, which means the creation of a thread is disallowed and the CSV import would fail.
