### ISSUE TITLE
Add a general Migration Guide

### ISSUE THREAD

**Issue by emahuni** [directus/directus#20148]
### Page

https://docs.directus.io/releases/breaking-changes.html

### Describe the Inaccuracy

I suggest that there should be a general migration guide that one can follow when upgrading self-hosted installations. Then specific versions upgrade on ones that have breaking changes.

Things have not gone well from time to time when upgrading to newer versions using just semver info (had to fix and jump hoops). When upgrading I just change the version in the package.json file, and `pnpm i`, that's after reading and checking for any possible breaking changes in release notes for the newer version.

**Comment by paescuj** [comment]
By a "general migration guide", do you mean something like this → https://docs.directus.io/self-hosted/upgrades-migrations.html?

**Comment by paescuj** [comment]
Sounds like a good idea 😄 👍

**Comment by rijkvanzanten** [comment]
The linked PR is just a link to satisfy the OP. Happy to keep discussing more specific tweaks / improvements in individual issues 🙂
