### ISSUE TITLE
Detail Group crashing pages

### ISSUE THREAD

**Issue by paulvonber** [directus/directus#20145]
### Describe the Bug

After upgrading to 10.7.0 some of my collections getting frozen in studio app, I discovered that If you have detail group inside detail group it's a problem, before it was all good, also no outside/console errors are visible, page simply freezing and then in few second browser tab crashes.

### To Reproduce

Create detail group and then create another detail group and drop inside the previous one.

### Directus Version

v10.7.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paulvonber** [comment]
> Error stated on version 10.6.4 and I believe it's not only detail group, just anything that groups fields and is nested inside another causes this error. Had to rollback to 10.6.3. It'd be great if there is a migration guide on every release to enable seamless upgrade.

I've jumped from 10.6.1 so not sure about versions in between, but for me it's the only case when it crashes all other nesting seems to be fine.

**Comment by paescuj** [comment]
@paulvonber Would it be possible for you to share your data model? While I think I'm able to reproduce it in another way, it doesn't seem to trigger a freeze on my side when simply having a detail group inside another.

**Comment by paulvonber** [comment]
> @paulvonber Would it be possible for you to share your data model? While I think I'm able to reproduce it in another way, it doesn't seem to trigger a freeze on my side when simply having a detail group inside another.

so here is what I have:
<img width="871" alt="image" src="https://github.com/directus/directus/assets/37245111/cd743c0b-9216-4443-b176-15a2e1271449">

All of the detail groups by default are "closed", so when I go to collection entry and try to open the very top parent one it crashes, if I take out those four details group out of the parent then all works as expected.
If I set parent group by default to "opened" then I can't even enter item page it crashes in the collection list view (table page)

**Comment by stx-chris** [comment]
can confirm; same behaviour with nested groups. Works fine until `10.6.3` and suddenly freezes on open or on creation since `10.6.4`, including `10.7.0`

**Comment by alexvdvalk** [comment]
2 detail groups inside a detail group triggers the crash.

Uploading Screen Recording 2023-10-24 at 13.03.19.mov…

**Comment by paescuj** [comment]
Thanks @all, the bug has been confirmed and a fix is on the way 👍

**Comment by rijkvanzanten** [comment]
Haven't confirmed this, but gut feeling says it's related to either https://github.com/directus/directus/pull/19959 or https://github.com/directus/directus/pull/19962. @Nitwel any thoughts?

**Comment by paescuj** [comment]
It is related to #19962 and a fix is on the way 👍
