### ISSUE TITLE
custome access control - fields disbaled

### ISSUE THREAD

**Issue by akamalmra** [directus/directus#20144]
### Describe the Bug

i have custom access control for edit permission, 
the allowed fields are disabled in the form view.

### To Reproduce

custom access for edit

### Directus Version

v10.7.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by DanielBiegler** [comment]
Hey there, could you please provide more information? We use Github issues to keep track of bugs in Directus and since I cant know it from your description I'll close this for now. Happy to reopen if theres new info! Cheers.
