### ISSUE TITLE
Fix support for Windows support

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#20159]

**Comment by br41nslug** [comment]
related to https://github.com/directus/directus/issues/20146

**Comment by br41nslug** [comment]
So far all i know is that the `npx directus init` command ran by `create-directus-project` silently fails for windows users. Must be something with the stdout and stdin with either `execa` or `inquirer` but havent managed to pinpoint it beyond that without any errors.

**Comment by Pachat** [comment]
Works OK with 10.7.1
Thanks

**Comment by br41nslug** [comment]
Looks like this was indeed resolved with the latest release.

https://github.com/directus/directus/assets/9389634/4d3a0d0f-cc0d-4b3d-8f07-e3518b0f4082
