### ISSUE TITLE
`Read Data` operation in flow returns list of `null` values

### ISSUE THREAD

**Issue by g-pichler** [directus/directus#20155]
### Describe the Bug

When a flow contains a `Read Data` operation, reading data from a different collection, this operation returns a list of `null` values instead of the expected collection entries.

In the Log of the flow I see a list `[ null, null, ... ]` (with the correct length) instead of the expected collection entries

As far as I could tell, this applies to blocking, as well as non-blocking flows. The `filter` is used as the length of the returned list (all entries are `null`) is correct.

**Versions affected:** The Bug is present in versions 10.6.4 and 10.7. It is *not* present in 10.6.1. It seems to affect only newly created flows, as flows present in the database, which were created before the update still work as intended.

### To Reproduce

In a fresh Directus 10.7 or 10.6.4 perform the following steps:
1. Create Collections `a` and `b` with only a default `id` field.
2. Create one item in `a` with `id = 1`.
3. Create a blocking (or non-blocking) flow, triggering on `items.create` of collection `b`
4. Add a `Read Data` element to the flow, reading the contents of collection `a` (`Query` is empty)
5. Create an item in collection `b`
6. Inspect the logs of the flow and observe that the payload of the `Read Data` operation is `[ null ]`.

Here are screenshots, illustrating the problem on v10.6.4. The same steps lead to the itended behavior on v10.6.1.
![1_collections](https://github.com/directus/directus/assets/1562581/5bf9ad73-918c-488b-a48f-673a5ed0aafa)
![2_contents_a](https://github.com/directus/directus/assets/1562581/ada44840-b10f-4643-8437-f099ad815c0e)
![3_flow](https://github.com/directus/directus/assets/1562581/d2c43eca-66d5-4c0b-9f05-a28b61d526c0)
![4_payload](https://github.com/directus/directus/assets/1562581/6b829dd3-fa14-465c-be9e-3eb0f3030d1d)

### Directus Version

v10.7

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by DanielBiegler** [comment]
OK I reproduced this. Yes, it does show you `null` values if you inspect the read operation but **only** if you do **not** have a following operation. See:

![image](https://github.com/directus/directus/assets/14810858/2103b05e-955e-4cd8-975b-0d0584a13460)

But now when we reconnect the logging operation:

![image](https://github.com/directus/directus/assets/14810858/4ed1994c-1ce4-445d-88cd-9f3f714f21a5)

We do actually see the result.

**Comment by DanielBiegler** [comment]
OK so I debugged this a little bit. First sigh of relief: It seems to be just a visual bug. We do actually

- run the reads
- get the expected output on api side
- actually send over the data too

One problem is then in `<logs-sidebar-detail>` rendering

Inspecting the revisions inside `revisionsByDate` you can even find the actual returned read data. If you check out where the data for the Payload dropdown comes from you see it has the data that we need as `$last`

Going then back one revision shows you even the correct key with its correct data - but we dont render it

**Comment by DanielBiegler** [comment]
Update: Traced it down and it is definitely the newly introduced `redactObject` function!

If you inspect the flow on the api side you get the correct object before we persist it via the `revisionsService`:

```
...
  '$env': {},
  item_read_g0oyt: [ { id: 1, name: 'First A' }, { id: 2, name: 'XXXXX' } ]
}
```
which then becomes the following after redaction:

```
...
  },
  '$env': {},
  item_read_g0oyt: [ null, null ]
}
```

Only question left is how to not trigger redaction for this key

**Comment by rijkvanzanten** [comment]
Sounds like it's redacting a little too well!

**Comment by DanielBiegler** [comment]
Lmao yea. We just solved it btw. Fix is on the way.
