### ISSUE TITLE
Add proper documentation for `create-directus-project`

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#20160]
This is a little wrapper which allows boilerplating a Directus project via npm using `npm init directus-project`. While npm installation is not an advised path, we should still surface this as part of our new getting started learning path, perhaps as part of the first step - Installation.

**Comment by rijkvanzanten** [comment]
@phazonoverload / @estheragbaje Pascal & I will prepare a draft of ideas for us to discuss / iterate on, so no action needed from your end just yet 😄

**Comment by phazonoverload** [comment]
@rijkvanzanten a month on do you still want to proceed with preparing a draft? Or do you wanna have an hour session where we can learn what we need to, and then draft it ourselves?

**Comment by rijkvanzanten** [comment]
hehe yeahhh it's been on the up-next todo, but the low-prio keeps moving it back. Happy to hand it over to you and get this show on the road 👉🏻👈🏻
