### ISSUE TITLE
Moving to directus 10.7 data lost (theming, media)

### ISSUE THREAD

**Issue by vitalijalbu** [directus/directus#20178]
### Describe the Bug

I just moved to directus 10.7, I lost:
- light theme (the light theme on admin panel is a varchar input, no more a selection), so all users lost light theme
- images arre not showed up...
- how to enable light theme now??

I should re-create the project from scratch??

### To Reproduce

I upgraded package.json and runned `npx directus database migrate:latest ` and `npx directus bootstrap` but nothing...
There also was an error of tabe **directus_revisions**
I host it simply with package.json and pm2... no docker or anything custom....

![Screenshot 2023-10-25 alle 09 59 50](https://github.com/directus/directus/assets/40239902/9a7d0ac3-5af2-42ab-9416-41a93ea87551)

### Directus Version

10.7.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by vitalijalbu** [comment]
![Uploading Screenshot 2023-10-25 alle 10.46.03.png…]()

**Comment by vitalijalbu** [comment]
![Screenshot 2023-10-25 alle 10 46 03](https://github.com/directus/directus/assets/40239902/bc8d2e0d-8674-4524-91c3-08f6d6258914)

**Comment by br41nslug** [comment]
Looks like your migration failed for some reason and this is the second time running it (seeing that the new `directus_extensions` table already exists). Please try migrating back down and up to properly update to the latest version. It might help as well to disable extensions while doing the database upgrade.

https://docs.directus.io/self-hosted/upgrades-migrations.html#downgrading-a-project

Make sure to always make backups of your database before doing updates against any data loss.
Closing this issue for now as it seems to be the result of a failed migration.

**Comment by vitalijalbu** [comment]
> Looks like your migration failed for some reason and this is the second time running it (seeing that the new `directus_extensions` table already exists). Please try migrating back down and up to properly update to the latest version. It might help as well to disable extensions while doing the database upgrade.
> 
> https://docs.directus.io/self-hosted/upgrades-migrations.html#downgrading-a-project
> 
> Make sure to always make backups of your database before doing updates against any data loss. Closing this issue for now as it seems to be the result of a failed migration.

Does the database latest upgrade db depends on package.json version ? i mean, i should update gradually directus or can pass directly from v9 to 10.7 without problems?

![Screenshot 2023-10-25 alle 15 47 42](https://github.com/directus/directus/assets/40239902/797e9fd2-fc5c-4b9b-aa27-de5c5b782f99)

**Comment by br41nslug** [comment]
> Does the database latest upgrade db depends on package.json version ?

No it just depends on the directus version as that holds the to be done migrations

> i should update gradually directus or can pass directly from v9 to 10.7 without problems?

Shouldnt really matter as migrations are run one by one anyway however no promises on the "without problems" because there have been quite a few breaking changes between 9.X and 10.7 you may run into 

https://docs.directus.io/releases/breaking-changes.html

**Comment by vitalijalbu** [comment]
> > Does the database latest upgrade db depends on package.json version ?
> 
> No it just depends on the directus version as that holds the to be done migrations
> 
> > i should update gradually directus or can pass directly from v9 to 10.7 without problems?
> 
> Shouldnt really matter as migrations are run one by one anyway however no promises on the "without problems" because there have been quite a few breaking changes between 9.X and 10.7 you may run into
> 
> https://docs.directus.io/releases/breaking-changes.html
> 
> Did you downgrade and re-apply the latest migrations?

Just tried, going down to 10.6.3 (all works ok), but when trying to migrate:latest (10.7) i have problems withassets not showing up :

```
{
  "errors": [
    {
      "message": "Invalid query. Invalid filter key \"version\" on \"directus_revisions\".",
      "extensions": {
        "code": "INVALID_QUERY",
        "reason": "Invalid filter key \"version\" on \"directus_revisions\""
      }
    }
  ]
}
```

**Comment by br41nslug** [comment]
> Just tried, going down to 10.6.3 (all works ok)

Did you downgrade only the the database migrations? or downgraded the entire instance (downgrading must be done on the latest version as 10.6.3 does not include the migrations for 10.7)

**Comment by vitalijalbu** [comment]
> > Just tried, going down to 10.6.3 (all works ok)
> 
> Did you downgrade only the the database migrations? or downgraded the entire instance (downgrading must be done on the latest version as 10.6.3 does not include the migrations for 10.7)
> 
> Images not showing up could be unrelated to the database, let's focus on 1 thing at the time, and get the database in a proper state first.

Uplaoding images also not working, i cannot see thumbnail:

Please see video:
https://drive.google.com/file/d/1WIauyJu1Qyf4HETEPcaTh1POdaJVVgH9/view?usp=sharing


My package.json:

```
{
  "name": "resthotels-cms",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@directus/extensions-sdk": "^10.1.13",
    "axios": "^1.5.1",
    "directus": "^10.7.0",
    "mysql": "^2.18.1"
  }
}

```
