### ISSUE TITLE
IPv6 addresses incompatible with directus_activity.logged_ip

### ISSUE THREAD

**Issue by NTmatter** [directus/directus#2017]
## Version Info
  - Directus version and branch: 6.4.5+20171218214440 e330fa8dfaed4e9549b549cab250abde9738bf1b
  - PHP version: PHP 7.0.22-0ubuntu0.16.04.1
  - MySQL version: mysql  Ver 14.14 Distrib 5.7.20
  - Web server: Apache/2.4.18 (Ubuntu)
  - OS name and version: OSX 10.11.6

## Expected Behavior
IP address logged.

## Actual Behavior
Activity is not logged, error is displayed.

## Steps to Reproduce
 1. Connect over IPv6 (eg, using mDNS address directus.local)
 2. As admin, manage or modify a table
 3. Commit changes

## Workaround
Increase length of logged_ip to hold an IPv6 address with possibility of embedded IPv4 address ([reference](https://stackoverflow.com/a/1076755)):
`ALTER TABLE directus_activity MODIFY logged_ip VARCHAR(45);`

## Schema Dump, Logs, or Screenshots
[2018-01-02.log](https://github.com/directus/directus/files/1598928/2018-01-02.log)

**Comment by WellingGuzman** [comment]
Thanks @NTmatter.

Closed by https://github.com/directus/directus/commit/c268ec48e90eab44f2784af3fae748ad5cbced10
