### ISSUE TITLE
many-to-any-union-types

### ISSUE THREAD

**Issue by adacadabrafr** [directus/directus#20173]
### Page

 https://docs.directus.io/reference/query.html#many-to-any-union-types

### Describe the Inaccuracy

I needed to Type a function that use a m2A collection for a page builder like (using a collection page that have a builder that contains : hero blocks, richtext block, etc..)
But seems that something went wrong in my code and it miss some example or explanation here.

Here's what I got:

```ts
export const findHome = async () => {
  return await directus.request(
    readItem("page", "f8468980-0d61-4d96-9cc2-dff2dd8a372e", {
      fields: ["*", { content: ["*", { item: ["*", { fimg: ["*"] }] }] }],
    })
  );
};
};
```

Then Tim brings me here with this example:

```ts
export const findHome = async () => {
  return await directus.request(
    readItem("page", "f8468980-0d61-4d96-9cc2-dff2dd8a372e", {
      fields: [
        "*",
        {
          content: [
            "*",
            {
              item: {
                hero: ["*", { fimg: ["*"] }],
                richtext: ["*"],
                list: ["*"],
                figcaption: ["*"],
                quote: ["*"],
                chapter: ["*"],
              },
            },
          ],
        },
      ],
    })
  );
};
```

Because you have to declare all of the collection in the item fields.

Thank you Tim again :)

**Comment by rijkvanzanten** [comment]
@adacadabrafr #20174 should help a lot with that 🙂  Lemme know if you have any other suggestions for improving those docs
