### ISSUE TITLE
Can't log-in in new deployment

### ISSUE THREAD

**Issue by kerbersystems** [directus/directus#20177]
### Describe the Bug

When deploying with docker compose on Ubuntu 20.04, entering an ADMIN_EMAIL and ADMIN_PASSWORD to not apply to the deployment. It seems to work when tying to a local SQLlite instance, but I have tied to a MSSQL sentence. The Directus table are made in MSSQL and I notice the only account in the users table is a user with the email "admin@example.com". No clue what the password is.

### To Reproduce

Deploy a fresh instance to MSSQL.

### Directus Version

V10.7

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by azrikahar** [comment]
Based on your description, I believe the MSSQL database has already been bootstrapped/initialized _without_ `ADMIN_EMAIL` and ` ADMIN_PASSWORD` (maybe in a previous run when the Directus container was ran without those environment variables, you may have a bind volume for the assumed database container, thus it is now technically not 100% fresh).

In that case, Directus will automatically create an admin user with the email `admin@example.com` & a randomly generated password that are both shown in the logs, as described in the docs:

> If omitted, the published Docker image will automatically populate the database and create an admin user, and these will only be shown in the Docker bootstrap logs when starting Directus for the first time. 
> Link: [Configure Admin User](https://docs.directus.io/self-hosted/docker-guide.html#configure-admin-user)

and here's an additional example screenshot:
![](https://github.com/directus/directus/assets/42867097/a8701a71-740e-4dc8-ba0c-e283f38ba69f)

You can either make sure the MSSQL container's bind volume is completed wiped before you restart the MSSQL & Directus containers, or you can look up the randomly generated password in your logs to gain access to said account and change the password if you wish to. 👍
