### ISSUE TITLE
mod_rewrite was no even enabled it.

### ISSUE THREAD

**Issue by ericsonluciano** [directus/directus#2018]
## Version Info
  - Directus version and branch: (Or commit hash) v6.4.5
  - PHP version: 7.0
  - MySQL version: 5.7.0
  - Web server: (Ex. Apache, nginx or IIS?)  Apache and Nginx (Yes i try both)
  - OS name and version:  Ubuntu 16.04

## Expected Behavior
from installation of directus pre-installation setup the mod_rewrite was **Yes** but the permission of config.php is not writable. then after i  fix with chown then mod_rewrite become **No**. Also the return of `domain.com/api/1.1/ping` was pong

i try both platform Apache and NGINX

## Actual Behavior
should be mod_rewrite **Yes**

## Steps to Reproduce
 1. i follow the installation from [medium post](https://medium.com/directus/installing-directus-on-lamp-758e8d52daf4)

## Schema Dump, Logs, or Screenshots
Can't screenshots sorry i already proceed to install

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/77ebc0069dd67bfa4da8879b99fc4a78fa01aac4
