### ISSUE TITLE
Extension - schedule hook not starting after upgrade to 10.7

### ISSUE THREAD

**Issue by timgit** [directus/directus#20184]
### Describe the Bug

After upgrading to 10.7 and running the db migration, schedule hooks are not starting.  I read in the release notes that extensions can be enabled/disabled now, which I also verified in the admin console that all extensions were listed as enabled.

Downgrading back to 10.6 will produce a log each minute.  

### To Reproduce

The following is a simple logging demo.

```js
export default ({ schedule }, { logger }) => {
    schedule('*/1 * * * *', () => {
        logger.info(`scheduled`)
    })
}
```

### Directus Version

v10.7.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by nodeworks** [comment]
@rijkvanzanten  can this be released as a patch today? this is critical for us as no schedules are running.

**Comment by rijkvanzanten** [comment]
Yup! Already preparing it 👍🏻
