### ISSUE TITLE
Directus SDK Authentication

### ISSUE THREAD

**Issue by WolfgangWenzel** [directus/directus#20186]
### Describe the Bug

I am using directus sdk 12.0.1. with the latest diretus release (which is not the issue). 

Authentication works but no authentication tokens are added to subsequent requests so read protected items on the server. Accessing the same items using axios with the same token works. 

Request Header generated by SDK call (code below):

GET /items/lecture_unit HTTP/1.1
Host: h2950924.stratoserver.net:8055
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0
Accept: */*
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://localhost:3000/
Content-Type: application/json
Origin: http://localhost:3000
Connection: keep-alive

Request header generated by Axios REST call:

GET /items/lecture_unit HTTP/1.1
Host: h2950924.stratoserver.net:8055
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0
Accept: application/json, text/plain, */*
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYzc5OWE4LTlmNTktNGUzNy05MTk0LThlYzRmNzcwM2NiOSIsInJvbGUiOiIyODA2ZmJkOS00MjNhLTQyZTctYmYwMi1lZGZkMDZhNDI2ODkiLCJhcHBfYWNjZXNzIjpmYWxzZSwiYWRtaW5fYWNjZXNzIjpmYWxzZSwiaWF0IjoxNjk4MjQ5MDYyLCJleHAiOjE2OTgyNDk5NjIsImlzcyI6ImRpcmVjdHVzIn0.AuTE-Q3a1zRWNDDBH1etbqIww0nyo3Iqh1Q1Hu4_u3k
Origin: http://localhost:3000
Connection: keep-alive
Referer: http://localhost:3000/

It is clear that the authorization token is missing in the SDK call

In the code below you have to replace url, user_id & pwd.

### To Reproduce

`
const SimpleTest = () => {
    const [directus ] = useState('URL');
    const [isLoggedIn, setIsLoggedIn] = useState(false);
    const [authKey, setAuthKey] = useState(null);

    const directusServer = createDirectus(directus)
        .with(authentication('json', { autoRefresh: false, credentials: 'include' }))
        .with(rest({ credentials: 'include' }));

    const mylogin = async (email, password) => {
        const response = await directusServer.request(login(email, password));
        console.log('test1 login result:', response);
        setIsLoggedIn(true);
        setAuthKey( response.access_token);
    }

    mylogin('user_id', 'pwd');

    const getUnits = async () => {
        if (isLoggedIn) {
            console.log('about.js getUnits ok ?:', isLoggedIn);

            try {
                const result = await directusServer.request(
                    withOptions(
                        readItems('lecture_unit'),
                        {credentials: 'include'}
                    ));
                console.log('about.js sdk getUnits:', result);
            } catch (e) {
                console.log('about.js getUnits error:', e.errors[0]);
            }

            const response = axios.get(directus + '/items/lecture_unit', {
                headers: {
                    Authorization: `Bearer ${authKey}`,
                }
            }).then(response => {
                    console.log('about.js axios items:', response.data.data);
                    return response.data.data;
                }
            ).catch(error => {
                    console.log('about.js axios error', error);
                }
            )
        }
    }

    getUnits();

    return (
        <div>
            <h1>Simple Test</h1>
        </div>
    )
}`

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
You have opted to do a manual rest-only login request `client.request(login(email, password))` which indeed simply returns the data like any other request without persisting the data.
To make use of the `authentication` composable and storage you'll want to use the `client.login()` function instead.

https://docs.directus.io/guides/sdk/authentication.html

**Comment by br41nslug** [comment]
I've tested the following code and seems to be working as expected:
```ts
const client = createDirectus<MySchema>('http://localhost:8055/')
    .with(authentication('cookie', {autoRefresh:false}))
    .with(rest({ credentials: 'include' }));

await client.login(email, pass);
console.log(await client.getToken());

console.log(await client.request( readMe({ fields: ['*'] }) ));

await client.refresh();
console.log(await client.getToken());
```

Depending on the framework you're using you may have to check for SSR logic as the `client` stores it's access token in memory, so this cannot be automatically shared between browser and server.

**Comment by WolfgangWenzel** [comment]
thanks it works, when i implement proper logic to request the items only after the await for the login has finished.
