### ISSUE TITLE
Unicode Characters Displaying Issue

### ISSUE THREAD

**Issue by mbaljeetsingh** [directus/directus#2019]
I'm trying to add translations for the body in the posts table. I'm trying to add the translations for 3 languages English, Punjabi and Hindi for the body field. During Create the characters show, but when I try to edit the post, then the body for the translation field shows ???? for both Punjabi and Hindi.

## Version Info
  - Directus version and branch: (Or commit hash) 6.4.0
  - PHP version: 7.1.7
  - MySQL version: libmysql - mysqlnd 5.0.12-dev - 20150407
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: Windows 10

## Expected Behavior
Should show Unicode characters

## Actual Behavior
If I add the Unicode characters in any field and save it and then edit the item, characters don't show. It shows ?????

## Schema Dump, Logs, or Screenshots
#During Create
![chrome_2018-01-07_20-08-02](https://user-images.githubusercontent.com/872762/34650439-5a9a0096-f3e7-11e7-8831-adcce1584878.png)
#During Edit
![chrome_2018-01-07_20-08-27](https://user-images.githubusercontent.com/872762/34650433-569f0ac2-f3e7-11e7-92b7-40cd2536c166.png)

**Comment by WellingGuzman** [comment]
Hey @mbaljeetsingh, what's that field charset? when you go the database the value is saved correctly? make sure you set the charset to `utf8mb4` in Directus configuration (`api/config.php`) and your fields/table/database.

**Comment by mbaljeetsingh** [comment]
Hi @WellingGuzman, charset is set to `utfmb4` in the Directus configuration `api/config.php`. But, field charset was different, If changed it to `utf8mb4_unicode_ci` from the PHPMyAdmin interface, now it seems to be working fine. 

But now the problem is, do I have to change it for every field. Can we make it default for every field from the interface?

.......................................
**Directus** has all the features I need for my next project. But there's one more issue related to speed, I have created the same API with **directus**, **cockpit** and **strapi**. Also, added the same data. But, Directus is taking longer than the others to return almost the same amount of data. In that case half the data.

**Directus (via Postman)**
![directus](https://user-images.githubusercontent.com/872762/34658942-6e8c3fd4-f459-11e7-89f1-d625a04e2b1c.png)

**Strapi (via Postman)**
![strapi](https://user-images.githubusercontent.com/872762/34658962-a08f3158-f459-11e7-80b7-d239c3566e11.png)

**Cockpit (via Postman)**
![cockpit](https://user-images.githubusercontent.com/872762/34658981-cb0a8720-f459-11e7-84fe-d5d93737f59e.png)

Thanks.

**Comment by WellingGuzman** [comment]
If you change your database default charset, every new table/column will get the database charset by default.

Try doing that, changing the table or the database charset to `utf8mb4`.

**Comment by WellingGuzman** [comment]
Thanks for the information on Strapi vs Cockpit vs Directus.

Which databases does this product uses? either way I will take a look at it.

Keep in mind we are working on optimizing the API response time, any help, suggestion is really welcome. Plus enabling cache should improve the response time.

Also, adding `?meta=0` to the url should make a bit more of difference in time response. This will remove the request for items count in the table.

**Comment by mbaljeetsingh** [comment]
**Directus** is using **MySQL**.
**Strapi** is using **MongoDB**.
**Cockpit** is using **Sqlite**.

Tried adding `?meta=0`, there's slight increase like `5ms`

**Comment by WellingGuzman** [comment]
> Directus is using MySQL.
> Strapi is using MongoDB.
> Cockpit is using Sqlite.

Thanks for the info, it makes sense the speed difference though, but we can still make it go down a little bit more too when using MySQL.

> Tried adding ?meta=0, there's slight increase like 5ms

Increase? well, that should not have happened. If this is a constant issue. (trying multiple times keep getting up rather than down, please open a new ticket so we can follow up separately)

---

Closing this as the main issue has been resolved, we can still discuss Directus speed here or any other new threads.

Thanks @mbaljeetsingh
