### ISSUE TITLE
Sporadically getting ECONNRESET error from SDK calls in Directus Cloud

### ISSUE THREAD

**Issue by jakecollins1** [directus/directus#20201]
### Describe the Bug

We are seeing a sporadic `ECONNRESET` error being thrown from various directus sdk calls.  When it happens, it drops the connection of our API endpoints.  I am wondering if the connection pool configuration can be configured for directus cloud.  I see that it can be for self-hosted directus projects.  If it can't be configured by us, I think maybe it could be tuned to solve this problem.

I also don't see any Live Chat entry point in the cloud dashboard, otherwise I would be sending this there.

### To Reproduce

Calling directus sdk functions.  The error is sporadic but does occur.

### Directus Version

v10.6.3

### Hosting Strategy

Directus Cloud

**Comment by rijkvanzanten** [comment]
Heya! It should be in the bottom right of the dashboard, though an adblocker might mess that up. As an alternative, you can reach out to support@directus.io directly 👍🏻 

This repo isn't monitored by or used for cloud support tickets, so I'll close this for now. Thanks!
