### ISSUE TITLE
Slow API response time

### ISSUE THREAD

**Issue by mbaljeetsingh** [directus/directus#2020]
Hey @WellingGuzman 
**Directus** has all the features I need for my next project. But there's one more issue related to speed, I have created the same API with **directus**, **cockpit** and **strapi**. Also, added the same data. But, Directus is taking longer than the others to return almost the same amount of data. In that case half the data.

**Directus (via Postman)**
![directus](https://user-images.githubusercontent.com/872762/34658942-6e8c3fd4-f459-11e7-89f1-d625a04e2b1c.png)

**Strapi (via Postman)**
![strapi](https://user-images.githubusercontent.com/872762/34658962-a08f3158-f459-11e7-80b7-d239c3566e11.png)

**Cockpit (via Postman)**
![cockpit](https://user-images.githubusercontent.com/872762/34658981-cb0a8720-f459-11e7-84fe-d5d93737f59e.png)

**Comment by WellingGuzman** [comment]
This ticket has been copied from https://github.com/directus/directus/issues/2019#issuecomment-355882447

**Comment by Anthonyzou** [comment]
I setup a little profiling with xdebug and using qcachegrind.

It seems the `trait ArraySetter` is calling the `underscoreToCamelCase` function thousands of times per request.

<img width="628" alt="screen shot 2018-02-01 at 11 20 19 pm" src="https://user-images.githubusercontent.com/1567160/35719382-80888688-07a6-11e8-837b-1090db4e719a.png">

[cachegrind.out.1095.zip](https://github.com/directus/directus/files/1688261/cachegrind.out.1095.zip)

**Comment by rijkvanzanten** [comment]
Update: I can confirm that the next version of the API (under development: [directus/api](https://github.com/directus/api)) is significantly faster. This new version of the API will be the default for Directus v7 and onwards

**Comment by daniel-upzzle** [comment]
I've made this pull request. Hope it helps.

https://github.com/directus/directus/pull/2125

**Comment by benhaynes** [comment]
Kamino cloned this issue to [directus/api](https://github.com/directus/api/issues/512)

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/23)
