### ISSUE TITLE
Copy to action in flows gives error

### ISSUE THREAD

**Issue by craigharman** [directus/directus#20215]
### Describe the Bug

Anytime I try and use the "copy to" action to copy a flow operation from one flow to another I get the error:

[RECORD_NOT_UNIQUE] Value for field "resolve" in collection "directus_operations" has to be unique.

### To Reproduce

Create 2 flows.
In one create a new operation (it doesn't seem to matter what it is).
Save the operation and the flow.
Edit the flow and select "copy to" on operation and attempt to copy it to the other flow.
Error appears.

I'm using docker-compose set up with Postgis 13.

### Directus Version

v10.7.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Important to note that this only happens with operations that are linked to a subsequent one.

I think we shouldn't copy the `resolve` field (and maybe others) along.
