### ISSUE TITLE
WYSIWYG editor not appearing in translations interface

### ISSUE THREAD

**Issue by simonking76** [directus/directus#2021]
## Version Info
  - Directus version and branch: 6.4.5 – 93ceb86f3171e7369d6bd376d2cd8c13024edd28
  - PHP version: 7.0.25
  - MySQL version: 5.5.58
  - Web server: Apache 2.4
  - OS name and version:  ubuntu 14.04

## Expected Behavior
Following the [Multilingual Content Setup](https://medium.com/directus/multilingual-content-setup-in-directus-i18n-4f243f72e554) the fields were created as described; a WYSIWYG FULL editor was selected for the body content field in the article_translations table. When entering translations, it was expected to see the WYSIWYG FULL editor interface to format text as required.

## Actual Behavior
The body content field appears as a (small) text area field, with no WYSIWYG editor interface, editor controls do not appear to format text. 

HTML markup is rendered in the text area field as raw html tags if pasted from a pre-populated WYSIWYG editor (from another table) which did contain html markup.

Changing the body field to use WYSIWYG as per the tutorial (rather than WYSIWYG full) improves the size of the body field but there are still no WYSIWYG editor controls to format text (add tables, titles etc).

## Steps to Reproduce
 1. create the tables for translatable content as per the tutorial
 2. create a new article and then go to enter text in the body field of the translatable fields.
 
## Schema Dump, Logs, or Screenshots

![dir-01](https://user-images.githubusercontent.com/2388352/34743916-5d2f5d68-f583-11e7-8836-8da7c6d4a0ba.png)

**Comment by rijkvanzanten** [comment]
Hey @simonking76!

Thanks for the heads up. I wasn't able to reproduce this issue.. Do you have some more specific info we can use to reproduce this issue? (What browser / how did you install Directus / etc)

About the other WYSIWYG editor, it's a Medium style editor, so the 'toolbar' will only show up when you select a piece of content to edit.

**Comment by rijkvanzanten** [comment]
This issue has been closed due to inactivity

**Comment by RadioSchattenwelt** [comment]
Hey,
I just experienced the same issue.
I had a WYSIWYG FULL editor in my table and added one in the related translations table, too.
In the translations table I could see the WYSIWYG editor but in the actual table it appeared as simple text area.
When I removed the editor from my table the translations editor showed up right again.
