### ISSUE TITLE
Duplicate extensions name collision

### ISSUE THREAD

**Issue by u12206050** [directus/directus#20213]
### Describe the Bug

We have a lot of extensions, divided into the different folders `hooks`, `endpoints` etc.

Many of them do have the same name, which is now causing an issue in Directus 10.7.0

```
"Duplicate entry 'activities' for key 'directus_extensions.PRIMARY'",
```

Worst though is this is just shrugged off with a warning: ` Couldn't load extensions`
But the app still goes online, even though half of the hooks might not be active.

### To Reproduce

Add a folder called `activities` to both `extensions/hooks` and `extensions/endpoints` 

Add a simple index.js for each with some boiler code.

Notice when you try starting the server that it will though these warnings about unable to insert into the `directus_extensions` directory.

### Directus Version

10.7.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by XanManZA** [comment]
Still receiving this error on a bundle type extension using 10.7.2. The changes in the PR don't cover bundle types.
