### ISSUE TITLE
Italian language Capitalize settings menu link

### ISSUE THREAD

**Issue by vitalijalbu** [directus/directus#20212]
### Describe the Improvement

**impostazioni** must be capitalized -> **Impostazioni**

![Screenshot 2023-10-27 alle 08 35 46](https://github.com/directus/directus/assets/40239902/97192dd0-7c7e-40ba-97cb-cfd77e8ba5f6)

**Comment by paescuj** [comment]
Thank you for the issue!
Our translations are managed via Crowdin [^1], which means everyone can contribute.
I fixed the translation now, but next time you are welcome to correct it yourself ❤️ 

[^1]: https://docs.directus.io/contributing/introduction.html#translate-the-app
