### ISSUE TITLE
M2O Field Creation Type Discrepancy, different between Create Field and Create Field in Advanced Mode

### ISSUE THREAD

**Issue by Natetronn** [directus/directus#20225]
### Describe the Bug

_Note: I'm referring to the M2O field, although it's possibly this happens on other fields as well._ 

When first creating a new M2O field, using the _Create Field_ button, then selecting the picture of the Many to One field, the Type input is grayed and says "UUID". If you "Continue in Advanced Field Creation Mode" it's the same.

![basic-m2o](https://github.com/directus/directus/assets/582149/0f984cb6-0af9-4c3b-8cc5-6116d1cd55e6)

However, when creating a new field via the _Create Field using Advanced Mode_ (link under the Create Field button) and selecting the Many to One Relationship from the dropdown, the Type is grayed out and says "Determined by Relationship"

![advanded-m2o](https://github.com/directus/directus/assets/582149/4349dd3f-19ca-4e18-965b-7782e76e0075)

Brand new fields, both the same field type (M2O), two different values for the grayed out Type input.

Tested on two instances of Directus, including a local copy of AgencyOS.

### To Reproduce

In a Collection, create a new Many to One Relationship field using the _Create Field_ button, select Many To One and you'll see Type is grayed out and says "UUID". If you then select "Continue in Advanced Field Creation Mode" you'll see it again as "UUID". Close that field and start over at the collection.

This time, click the _Create Field using Advanced Mode_ link (below the Create Field button), Select Many to One Relationship and you'll see Type is grayed out and says "Determined by Relationship".

### Directus Version

v10.7.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
In both cases it is "determined by the relation" as the type will match the primary key type of the related table.

https://github.com/directus/directus/assets/9389634/723e82f9-8088-4103-bc31-8270398265eb
