### ISSUE TITLE
The `QUERY_LIMIT_MAX` setting is not honored by `SEARCH` requests

### ISSUE THREAD

**Issue by g-pichler** [directus/directus#20228]
### Describe the Bug

When performing a HTTP `SEARCH` request, the `QUERY_LIMIT_MAX` setting is not applied.

Performing the same request using `GET` or a `GraphQL` query results in the error `[INVALID_QUERY] "limit" must be less than or equal to 5`.

### To Reproduce

Steps to reproduce on a fresh Directus 10.7.1:
1. Set `QUERY_LIMIT_MAX = 5` 
2. Create a collection with 6 items.
3. Query the collection using a `SEARCH` request with `limit = 10` and all 6 items are returned.

### Directus Version

v10.7.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by g-pichler** [comment]
The problem seems to occur only when `limit` is passed within the body of the search request. Could you try the following script in your setup:

```
const url = 'http://localhost:8056/items/a';

const data = await fetch(url, { method: 'SEARCH',
                                headers: {
                                   'Accept': 'application/json',
				   'Content-Type': 'application/json'
				},
                                body: JSON.stringify({query: {limit: 10 }}),
				})
	.then((response) => response.json());

console.dir(data);
```

On my system (Directus 10.7.1 on docker) this yields more than `QUERY_LIMIT_MAX` entries.

**Comment by br41nslug** [comment]
I can reproduce that `QUERY_LIMIT_MAX` is not properly working on limits set directly in the body of a `SEARCH` request.
