### ISSUE TITLE
Unexpected behavior with `QUERY_LIMIT_MAX > 0` and `limit = -1`

### ISSUE THREAD

**Issue by g-pichler** [directus/directus#20229]
### Describe the Bug

I'm not sure if this qualifies as a bug, but in my opinion this is not wanted behavior:

If `QUERY_LIMIT_MAX > 0` is set and data is requested with `limit=-1` instead of the obvious error `[INVALID_QUERY] "limit" must be less than or equal to <limit>`, Directus returns `<limit>` entries of the collection. The caller must be aware of the Directus configuration to be able to tell that the response does *not* include the complete dataset.

From the users perspective this is troublesome, as Directus is explicitly asked for the entire dataset with `limit=-1`, responds with response code `200`, but does *not* provide what is asked. Is there a way for a client to tell that this is happening other then querying with `limit != -1`?

### To Reproduce

Steps to reproduce on a fresh Directus 10.7.1:

1. Set `QUERY_LIMIT_MAX = 5`
2. Create a collection with 6 items.
3. Query the collection with `limit = -1` and all 5 of the 6 total items are returned.

### Directus Version

v10.7.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
> From the users perspective this is troublesome, as Directus is explicitly asked for the entire dataset with limit=-1, responds with response code 200, but does not provide what is asked.

This feels like a misunderstanding about the meaning of `limit=-1`, which means "return the maximum amount records allowed" which means all of them if no limit is set and the `QUERY_LIMIT_MAX` if that's configured to limit the maximum allowed records. 

> Is there a way for a client to tell that this is happening other then querying with limit != -1?

The `/server/info` endpoint exposes the maximum limit configured for a server (for authenticated users)
https://docs.directus.io/reference/system/server.html#info

**Comment by g-pichler** [comment]
I see. That explains the behavior.

However, then the wording of the [documentation](https://docs.directus.io/reference/query.html#limit) should be improved, imo. It seems to support my understanding of `limit=-1`:

```
Limit

Set the maximum number of items that will be returned.
[...]
Get all items: -1
```

The meaning `Get all items` for the value `limit=-1` is unambiguously stated in the *Examples* section. The fact that not all items might be returned as well as the `QUERY_LIMIT_MAX` setting are not mentioned at this point.
