### ISSUE TITLE
Primary color is missing in the login form

### ISSUE THREAD

**Issue by JonathanDoelan** [directus/directus#20232]
### Describe the Improvement

Don't think this is intended …

`>=10.7.0`
![screenshot](https://github.com/directus/directus/assets/2291224/efb24139-72c3-47b2-b96d-d5df96686ceb)

`<10.7.0`
![old](https://github.com/directus/directus/assets/2291224/251ee974-b97b-4cb3-a1c0-cc937e04a7fe)

**Comment by rijkvanzanten** [comment]
Funnily enough, it's kinda working as expected. Before, if you'd configure a custom brand color in settings, we'd make the login form grayscale not to conflict between the primary purple and the brand color. Starting in 10.7, primary _is_ the configured project color, which in turn means the login form now thinks there's a custom color all the time! 

This is 'fixed' by removing the grayscale magic in #20226 🚀
