### ISSUE TITLE
Manual sort doesn't work, due to null in new items

### ISSUE THREAD

**Issue by Neschastje** [directus/directus#20230]
### Describe the Bug

New items have null in sort field in Safari.

### To Reproduce

1) Open admin panel with Safari
2) Settings > Data Model > Create new 
3) Create any model with sort field. 
4) Content > <Collection> > Add new Item(x2)
5) Enable showing sort. There will be '--' value in sort and dnd is not working after manual sort is enabled.

Same is working in Chrome.

### Directus Version

v10.7.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by azrikahar** [comment]
> Same is working in Chrome.

> Directus Version
> v10.7.1

Based on these descriptions, I believe this is the same issue as #20349. I'll proceed to close this one in favor of that issue.
