### ISSUE TITLE
the order field on a collection table view or on the Data Model / Fields & Layout, doesn't work

### ISSUE THREAD

**Issue by paulosilva** [directus/directus#20235]
### Describe the Bug

We can't order the information on a collection table view or on the Data Model / Fields & Layout, the drag and drop action doesn't work.

### To Reproduce

On the Content View:
1. Open a Collection
2. Try to drag and drop the header fields

On the Data Model
1. Open a Collection
2. Try to drag and drop a field in the Fields & Layout

### Directus Version

v10.7.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
https://github.com/directus/directus/assets/9389634/69b4044f-af20-4e0b-adbe-4500be5287bf


I have not been able to reproduce this based on the given information, sort seems to work in both Chrome and Firefox.

Happy to re-open if more details become available.

**Comment by bstrr** [comment]
> chrome_S6QsprCJzJ.mp4 
> 
> I have not been able to reproduce this based on the given information, sort seems to work in both Chrome and Firefox.
> 
> Happy to re-open if more details become available.

Sorting the collections works fine, but if you try and sort the **fields** in a collection, it is no longer possible to drag them up and down. Mac/Safari, Directus 10.7.2 here.

**Comment by bstrr** [comment]
It works in Mac/Chrome, so probably only an issue in Safari. Inspecting the element shows that clicking it does set the element draggable=true, so something is fishy.
