### ISSUE TITLE
PDF Thumbnail not shown in EditMask

### ISSUE THREAD

**Issue by dfranklinAxon** [directus/directus#2024]
When you want to edit a row with a single file which has a PDF it does not show a thumbnail of the PDF.
![bildschirmfoto 2018-01-11 um 13 57 45](https://user-images.githubusercontent.com/35228436/34826615-913774ba-f6d7-11e7-8924-f2c5373d20a5.png)

Also if you want to edit the file you will also not see a picture of the PDF.

## Version Info
  - Directus version and branch: 6.4.5
  - Web server: Apache

## Expected Behavior
Thumbnail or Screenshot from the first PDF Page

## Actual Behavior
White Screen

**Comment by WellingGuzman** [comment]
Hey @dfranklinAxon do you have `Imagick` installed in your server? that php extension is needed in order to create PDF thumbnails.

**Comment by dfranklinAxon** [comment]
Yes  I have Imagick already installed on the server.

**Comment by WellingGuzman** [comment]
is `Imagick` Installed and enabled in the php version you are using? if you go to your `storage/uploads/thumbs` is the pdf thumb image exists? have you tried with other PDFs?

**Comment by dfranklinAxon** [comment]
![bildschirmfoto_2018-01-15_um_11 32 25](https://user-images.githubusercontent.com/35228436/34947751-62dba6b8-fa0b-11e7-9f5f-b7cf44f49280.png)
![bildschirmfoto_2018-01-15_um_11 33 42](https://user-images.githubusercontent.com/35228436/34947753-63580ff0-fa0b-11e7-848f-1db81d0992de.png)

Here are the infos you want and I checked another PDF but it doesn't show a picture

**Comment by WellingGuzman** [comment]
Are there any generated thumbnails in `storage/uploads/thumbs` for that specific image, I want to tell if this a loading, a missing data (url) or a generating issue.

**Comment by dfranklinAxon** [comment]
Yes the thumbnails are there

**Comment by dfranklinAxon** [comment]
There are generated thumbnails in storage/uploads/thumbs but they are not show in the backend only like the example.

**Comment by dfranklinAxon** [comment]
![bildschirmfoto 2018-01-23 um 11 19 19](https://user-images.githubusercontent.com/35228436/35270608-ffd4270e-002f-11e8-92fc-c81fa9a8589b.png)


When I add an exel document it shows the thumbnail as buggy as when I add a pdf.

**Comment by WellingGuzman** [comment]
Hey @dfranklinAxon, I have not been able to reproduce this issue yet. How your `filesystem` configuration looks like? (in api/configuration.php)? does the thumbnail path is correct?

**Comment by dfranklinAxon** [comment]
'filesystem' => [
'adapter' => 'local',
// By default media directory are located at the same level of directus root
// To make them a level up outsite the root directory
// use this instead
// Ex: 'root' => realpath(BASE_PATH.'/../storage/uploads'),
// Note: BASE_PATH constant doesn't end with trailing slash
'root' => BASE_PATH . '/storage/uploads',
// This is the url where all the media will be pointing to
// here all assets will be (yourdomain)/storage/uploads
// same with thumbnails (yourdomain)/storage/uploads/thumbs
'root_url' => '/storage/uploads',
'root_thumb_url' => '/storage/uploads/thumbs',
// 'key' => 's3-key',
// 'secret' => 's3-key',
// 'region' => 's3-region',
// 'version' => 's3-version',
// 'bucket' => 's3-bucket',
// Digital Ocean endpoint
// 'endpoint' => '
],

I think thats look right and the thumbnail path is correct too.

**Comment by WellingGuzman** [comment]
> I think thats look right and the thumbnail path is correct too.

When you fetch files using the API, does all the thumbnails links works if you click on them?

**Comment by dfranklinAxon** [comment]
![bildschirmfoto 2018-01-25 um 10 51 41](https://user-images.githubusercontent.com/35228436/35381815-c535ad0e-01bd-11e8-848a-ce2134ebe896.png)


When I clicked on it in storage/uploads/thumbs all links work and download the image and i can open the right image in the downloadfolder

**Comment by WellingGuzman** [comment]
Wait, when you click the image url, it downloads the image? This seems to be a configuration issue somehow, the image exists but the doesn't show up at the web app.

**Comment by rijkvanzanten** [comment]
This issue has been closed due to inactivity.

If anyone runs into the same issue, please let us know and we'll re-open the issue!
