### ISSUE TITLE
Dropdown value displayed instead of text

### ISSUE THREAD

**Issue by aderugy** [directus/directus#20264]
### Describe the Bug

Hello,

I believe that dropdowns are wrongly displayed when viewing items from a collection (Directus v10.7.1).
The value is displayed and not the text, as it can be seen on the screenshots below.

![image](https://github.com/directus/directus/assets/117949192/0c5956dd-48fb-4425-836b-59a7b7f0ddbc)

![image](https://github.com/directus/directus/assets/117949192/5fa294a9-ba9a-4686-b835-88151b420d36)
It can be seen that the purpose field has it's value displayed and not it's text.

I have not found any parameter that could change this.

### To Reproduce

Create a collection with a dropdown field, and an integer value. Create an item from this collection, and watch the result in the content view page.

### Directus Version

v10.7.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by aderugy** [comment]
Made a quick additional test by creating a new field to my collection:
![image](https://github.com/directus/directus/assets/117949192/0b3151c8-9fc9-4823-b223-31d5e97a46a0)
Displayed like this:
![image](https://github.com/directus/directus/assets/117949192/522c5e5d-a4be-4d08-aae8-709cae2d6dd5)

**Comment by br41nslug** [comment]
The first screenshot is showing the `display`s while the second configuration screenshot shows the `interface`. Make sure to also configure your displays for the overview pages (the tab under the interface configuration).

**Comment by aderugy** [comment]
I agree, the purpose of the screen was to show that the text wasn't displayed.
The point is, in the display settings, I have no options to show the text instead of the value.

![image](https://github.com/directus/directus/assets/117949192/be6a2124-796a-4238-bec5-d8888b318a07)
![image](https://github.com/directus/directus/assets/117949192/36d71883-17fa-4320-a519-e40db56a0e92)

**Comment by br41nslug** [comment]
The display and interface settings are separate so you may need to configure the display labels in both.

**Comment by aderugy** [comment]
After testing, it seems to be specific to integer dropdowns. Works just like you have shown with String dropdown.

Here is my field representation.
```
{
			"collection": "FormSubmission",
			"field": "purpose",
			"type": "integer",
			"schema": {
				"name": "purpose",
				"table": "FormSubmission",
				"data_type": "int",
				"default_value": null,
				"generation_expression": null,
				"max_length": null,
				"numeric_precision": 10,
				"numeric_scale": 0,
				"is_generated": false,
				"is_nullable": false,
				"is_unique": false,
				"is_primary_key": false,
				"has_auto_increment": false,
				"foreign_key_column": null,
				"foreign_key_table": null,
				"comment": ""
			},
			"meta": {
				"id": 21,
				"collection": "FormSubmission",
				"field": "purpose",
				"special": null,
				"interface": "select-dropdown",
				"options": {
					"choices": [
						{
							"text": "PRODUCT DEVELOPMENT",
							"value": 1
						},
						{
							"text": "LITIGATION",
							"value": 2
						}
					]
				},
				"display": null,
				"display_options": null,
				"readonly": false,
				"hidden": false,
				"sort": 6,
				"width": "full",
				"translations": null,
				"note": null,
				"conditions": null,
				"required": true,
				"group": null,
				"validation": null,
				"validation_message": null
			}
		}
```

**Comment by br41nslug** [comment]
Oh my bad you're not using a `string` field 🤔 perhaps the labels display should be available for `integers` and `floats` but it currently is not.
