### ISSUE TITLE
Many to One relation issue DB mysql

### ISSUE THREAD

**Issue by vitalijalbu** [directus/directus#20266]
### Describe the Bug

![Screenshot 2023-10-31 alle 14 15 10](https://github.com/directus/directus/assets/40239902/275844cf-3531-4215-b891-b601850b4b16)

FULL ISSUE:
```
{
  "errors": [
    {
      "message": "alter table `listings` add constraint `listings_user_foreign` foreign key (`user`) references `directus_users` (`id`) on delete SET NULL - ER_CANT_CREATE_TABLE: Can't create table `resthotels_stagging`.`listings` (errno: 150 \"Foreign key constraint is incorrectly formed\")",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### To Reproduce

I tried just to create a relationship **Many to One** between **listings** table and **users directus**.

It never happened unitl **10.7**, using phpmyadmin and mysql

### Directus Version

10.7.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by azrikahar** [comment]
This looks like it might share the same root cause as what was described in #20316. Can you try out what was shared in this comment: https://github.com/directus/directus/issues/20316#issuecomment-1793503393, or perhaps check are there any differing collations within your setup?
