### ISSUE TITLE
Vagrant user not found

### ISSUE THREAD

**Issue by jongirard** [directus/directus#2026]
Installed using the vagrant installation option listed in the Directus docs. Installation successful but login with the provided credentials of ```admin@admin.com``` and password of ```admin``` fails with ```email not found```.

## Version Info
  - Directus version and branch: Directus Demo 0.1.1

## Steps to Reproduce
 1. Install via Vagrant
 2. Attempt to login with provided credentials in docs

**Comment by WellingGuzman** [comment]
Moved to https://github.com/directus/directus-vagrant/issues/26
