### ISSUE TITLE
Roles permissions should be based on public role

### ISSUE THREAD

**Issue by cdwmhcc** [directus/directus#20272]
### Describe the Bug

Every time you create a rule, you need to configure new permissions. Shouldn't permissions be based on Public rules under normal circumstances? Public role is the minimum permissions.

### To Reproduce

same

### Directus Version

10.7.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
This is not a bug, roles do not inherit from each other. Feel free to create a feature request or upvote any of the existing one like https://github.com/directus/directus/discussions/4959
