### ISSUE TITLE
Unable to sync user password

### ISSUE THREAD

**Issue by u12206050** [directus/directus#20278]
### Describe the Bug

We are trying to export and import users from one source system into multiple other systems, without requiring them to create a new account, however when we try to export the user item, the password value is just `**********`.

There doesn't seem to be any flag or setting we can set to bypass this.

### To Reproduce

Read a user item using the ItemsService. Check the password field.

Expected that at least within the backend that password field will be value stored in db

### Directus Version

10.7.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
Correct they are being redacted at the UsersService level to prevent user passwords/tokens from being accidentally exposed over the API or other methods.

To get at the raw password hash you'll need to read it directly from the database like:
https://github.com/directus/directus/blob/main/api/src/utils/get-accountability-for-token.ts#L36

Perhaps such a flag could be a feature request 🤔 although it does feel risky from a security point of view.
