### ISSUE TITLE
Primary key value shown when not visiable

### ISSUE THREAD

**Issue by dlaprade** [directus/directus#2028]
## Version Info
  - Directus version and branch: 6.4.3
  - PHP version: 7.1.11
  - MySQL version: MariaDB 10.1
  - Web server: Nginx
  - OS name and version: Debian Jessie Linux

## Expected Behavior
I have a table defined with an INT primary key ( not visible ) with a couple of MANYTOONE relationships and when a new row is added the primary key 'id' is not shown in admin UI.

## Actual Behavior
I am seeing the primary key 'id' in the UI and when a value is not entered into the field an error is being presented to user: Server Error: Duplicate value: 0 (PRIMARY)

## Further information

- I am noticing that the primary key values for 'id' are jumping and are not sequential.
- I am connecting to S3 for image storage and this table references an image.
- No extra filters or hooks are being used in the configuration.php file.

**Comment by WellingGuzman** [comment]
@dlaprade can you provide a mysql dump that we can use to reproduce this issue?

**Comment by rijkvanzanten** [comment]
This issue has been closed due to inactivity
