### ISSUE TITLE
How to get Metadata description from Image?

### ISSUE THREAD

**Issue by PhilipZi** [directus/directus#20289]
### Describe the Bug

when i upload images to my file directory in directus i get a "title" generated from the filename, but i dont get the metadata from the image such as description or tags, the fields of the file in directus "description" are existing and i can manually fill them but is there a way i can use the already existing metadata to fill these inputs automatically? 
I am a bit lost, appreciate your help! 

Best regards 

### To Reproduce

 upload images to the file folder and open the image in there. there you can see the image and the fields for it you can work on. The title get filled but the rest wont. Why? 

### Directus Version

10.3.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
> When uploading an image, Directus persists the description, title, and tags from available EXIF metadata. For security purposes, collection of additional metadata must be configured:

It should work if the file has properly set exif data if not try setting `FILE_METADATA_ALLOW_LIST` to `*`.

https://docs.directus.io/self-hosted/config-options.html#metadata

**Comment by PhilipZi** [comment]
thank you that helped!
