### ISSUE TITLE
Directus changes table schema of DB

### ISSUE THREAD

**Issue by u12206050** [directus/directus#20285]
### Describe the Bug

After installing the latest Directus version 10.7, and running migrations, expecting only for it to update directus tables, we noticed that allocated storage size increased in the database. Upon further inspection we realised that a lot of our original varchar(255) columns were changed to text(65535)!!!

The only common thing I found between the fields were that they were using the Directus csv type, which in our case is what we want, but we are very specific with the sizes of the columns, since they most of them won't ever contain so much data.

Directus is supposed to just be the api on **our** database, not take it over.

I understand that certain csv fields could be longer, but that should then be apart of the configuration when fields are created, eg. look at the max length.

### To Reproduce

Migration pre 10.7 directus project with csv fields to 10.7 and notice the column schema has changed.

### Directus Version

10.7

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
This was an explicit bugfix of CSV fields incorrectly getting a `string` type instead of `text` https://github.com/directus/directus/pull/19953

**Comment by u12206050** [comment]
I understand it could be seen as a bug fix, but then it could also only apply to new fields, and rather allow developers to apply migration manually if they want on the columns they want.

If this is a case of 80/20 then it is fine, we already added another migration to migrate our csv fields back to varchar.
