### ISSUE TITLE
Make extension version visible in new extension panel

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#20282]
### Discussed in https://github.com/directus/directus/discussions/20281

<div type='discussions-op-text'>

<sup>Originally posted by **that1matt** October 31, 2023</sup>
### Summary

Currently when making a change to an extension, and pushing to Directus Self-Hosted/Directus Enterprise, we have no way of knowing if our change has made it to production.

With Directus 10.7.1, and the new extensions panel in settings, it should show the version that is installed.

### Basic Example

![Screenshot 2023-10-31 at 1 48 42 PM](https://github.com/directus/directus/assets/9679004/6ff87a2f-cfe2-479a-9eac-3f02a5442340)

### Motivation

When making changes to extensions, and when deploying the new changes there is no easy way to validate if the new version has been installed. This is especially true for Directus Enterprise.

### Detailed Design

Would need to add a new field to the `directus_extensions` collection for `version`. 
Then along with getting the `name` from the `package.json`, getting the current `version`, and updating the `version` field in `directus_extensions`

### Must Have:
- Visible output of currently "successfully" installed extension visible in Extensions panel in settings.

### Should Have:
- In the more menu (triple dots), could have a link to render any issues with installation.

### Drawbacks

Would possibly need to find a way to surface any installation issues if latest version couldn't be installed.

### Alternatives

Currently, you could have a custom endpoint with an unauthenticated endpoint return the version.

### Adoption Strategy

A simple migration would solve this issue, but extending the current `directus_extensions` collection to allow for a version field.

### Unresolved Questions

_No response_</div>

**Comment by that1matt** [comment]
This might be out of scope for this feature request, but I wonder if there is a way to indicate whether the extension was successfully installed or not. Either by capturing any errors and adding them to a new field in the `directus_extensions` collection. Might even be able to be a boolean field to just indicate success/failure.

**Comment by br41nslug** [comment]
Might be a little bit of scope creep but i think it would be valuable to also have a badge showing whether an extension is "secure" or not on this page. Happy to make this a separate improvement if need be 😄 
![image](https://github.com/directus/directus/assets/9389634/5b5639c3-fdd3-460b-a22e-4a869ace7b7a)
