### ISSUE TITLE
GraphqQL BigInt handling

### ISSUE THREAD

**Issue by br41nslug** [directus/directus#20291]
### Describe the Bug

After further looking into Azri's comment here https://github.com/directus/directus/pull/20263#issuecomment-1787147823 there seem to be a variety of issues when working with BigInt types over GraphQL.

1. filtering bigInt values results in 500 internal server error
```gql
query Test3 {
    test3(filter: { big_int: { _lt: "-9223372036854775800" } }) {
        id
        name
        big_int
    }
}
```

2. filtering NaN values doesnt get caught until the SQL query actually has NaN in it. This happens  for any non-numeric value including an empty string. Same behavior occurs for creating items and likely updating too then.
```gql
query Test3 {
    test3(filter: { big_int: { _lt: "test+123" } }) {
        id
        name
        big_int
    }
}
```

3. creating items with valid BigInt numbers fails with a validation error
```gql
mutation Create_test3_item {
    create_test3_item(data: { big_int: "-9223372036854775800", name: "test" }) {
        name
        big_int
    }
}
```

All these likely have the same root cause, which i suspect is the BigInt implementation here https://github.com/directus/directus/blob/main/api/src/services/graphql/types/bigint.ts which attempts to cast BigInt values to a Number defeating the purpose of using the BigInt type.

### To Reproduce

1. create a collection and add a BigInt field
2a. try to create new item using GraphQL (with a big int value outside the range of a regular Number)
2b. try to filter against a BigInt value (with the value outside the range of a regular Number)
2c. try filtering or creating an item using a string that is not a number

### Directus Version

10.7.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by mahendraHegde** [comment]
@br41nslug  @alexchopin  can you assign this to me, i'm checking this.
