### ISSUE TITLE
Duplicate system table directus_users in Directus Cloud

### ISSUE THREAD

**Issue by JitYc** [directus/directus#20292]
### Describe the Bug

In Directus Cloud (version 10.7.1, but has shown up since pre-10 from what I can remember) the directus_users table shows up twice in UI. It is unclear if it's an actual duplicate table issue, or a cosmetic / UI issue.  See below images; two images to show hover where one shows "system users for the platform" and the other does not. When clicked, both go to directus.app/admin/settings/data-model/directus_users

![image](https://github.com/directus/directus/assets/129078770/86d32fe6-dd58-45cc-ae98-315bddd6b61d)
![image](https://github.com/directus/directus/assets/129078770/96caba49-e2a5-40db-9f49-8717524c39f6)

### To Reproduce

Go to _yourdomain_.directus.app/admin/settings/data-model and click on system collections at the bottom and view the system collections.

### Directus Version

v10.7.1

### Hosting Strategy

Directus Cloud

**Comment by br41nslug** [comment]
Please contact cloud support via the live chat or email to look into this. GitHub issues are not actively monitored for cloud issues.

**Comment by JitYc** [comment]
@br41nslug There is no chat support option (on cloud standard) and the report a bug  feature brings me to Github; thoughts?

**Comment by br41nslug** [comment]
![image](https://github.com/directus/directus/assets/9389634/42015272-47dd-426b-bffc-566b4ae19ceb)

Or you can skip the bot and [fill out the form here](https://share.hsforms.com/1Kuu-0jHIRYGd2cYSbofC_Ac8497)
