### ISSUE TITLE
Error [500] in AbstractSql.php

### ISSUE THREAD

**Issue by kkar** [directus/directus#2030]
## Version Info
  - Directus version and branch: Latest from git
  - PHP version: 7.2.1 (the one included in the latest XAMPP for windows)
  - MySQL version: (the one included in the latest XAMPP for windows)
  - Web server: Apache (the one included in the latest XAMPP for windows)
  - OS name and version: MS Windows 10 with XAMPP

## Expected Behavior
Allowing administrators view and/or add new tables.

## Actual Behavior
When the admin user browses http://127.0.0.1/projectname/settings/tables for viewing or to add a new table, a "500 internal server error" is produced, which is coming from line 244 of AbstractSql.php.

## Steps to Reproduce
 1. Install XAMPP on Windows OS
 2. Create a new database with phpMyAdmin
 3. Install Directus by following the "easy installation" section of the manual
 4. Log in to Directus and go to "Admin Settings -> Tables & Inputs"
 5. An error is spawned in the lower-right corner, and it can be examined in console too

**Comment by WellingGuzman** [comment]
Hey @kkar Providing a database dump and an specific version for MySQL, rather than "_the one included in the latest XAMPP for windows_" helps a lot. If you have a chance please do it, so we can reproduce this issue quickly.

**Comment by kkar** [comment]
> C:\xampp\mysql\bin>mysql -h localhost -V
> mysql  Ver 15.1 Distrib 10.1.30-MariaDB, for Win32 (AMD64)

@WellingGuzman you will need a dump too? It really doesn't have anything else except the fresh-install content. I am unable to add anything cause of the same error.

**Comment by WellingGuzman** [comment]
@kkar Thanks. When this error is thrown? is there something in your logs. Can be found in `api/logs` directory?

**Comment by kkar** [comment]
@WellingGuzman a lot of errors, but not different. All of them refer to the same line.

> ERROR - 2018-01-22T17:37:43-05:00 - ErrorException: count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\testProject\vendor\zendframework\zend-db\src\Sql\AbstractSql.php:244

**Comment by WellingGuzman** [comment]
Gotcha just what I thought, Read this comment: https://github.com/directus/directus/issues/1984#issuecomment-357484829

zend-db had some bugs with 7.2, has been resolved, and you need to remove the `composer.lock` and reinstall again.

**Comment by kkar** [comment]
@WellingGuzman sorry for keeping you busy, but, is the solution applies with the "simple installation" too? Thanks again!

**Comment by WellingGuzman** [comment]
@kkar Either way, the problem is with zend-db and php 7.2.x. if you switch to php 7.1 it will works, without any problem.

**Comment by kkar** [comment]
@WellingGuzman it worked as promised!!! Thank you so much, you are the most instant and helpful contributor ever! Thanks again!
