### ISSUE TITLE
Support enabling/disabling bundle extensions

### ISSUE THREAD

**Issue by br41nslug** [directus/directus#20304]
### Describe the Improvement

Because a bundle may contain any number of child extensions i think it would be good to be able to enable or disable an entire bundle instead of having to go enable/disable each bundled child extension separately.

![image](https://github.com/directus/directus/assets/9389634/7665e304-1023-4406-bec7-81e442ed7db9)

**Comment by rijkvanzanten** [comment]
It should be a "enable all" / "disable all" type of helper 🙂

**Comment by br41nslug** [comment]
As an extra to this i would like to be able to define in the Bundle config whether it is possible to enable/disable individual sub extensions as quite often the various extensions are dependent on eachother and cannot function by themselves.

For example: an interface extension can rely on the custom endpoint in the bundle to function.
