### ISSUE TITLE
WYSIWYG Full does not load on IE11

### ISSUE THREAD

**Issue by michlschmitt** [directus/directus#2031]
## Version Info
  - Directus version and branch: 6.4.5. bundled version
  - PHP version: PHP 7.0.25
  - MySQL version: 5.5.58
  - Web server: nginx
  - OS name and version: Windows

## Expected Behavior

Write an article via WYSIWYG Full Interface.

## Actual Behavior

The WYSIWYG Full Editor does not show up on Windows and Internet Explorer 11. 

![ie-wysiwyg](https://user-images.githubusercontent.com/22587130/35286373-260f98b0-0060-11e8-9862-d7cd69ab6fed.PNG)

## Steps to Reproduce
 1. Create a table with WYSIWYG Full field
 2. Open the table and insert content if you can see the editor

**Comment by rijkvanzanten** [comment]
Hey @michlschmitt!

Thanks for the head up! Could you maybe provide the output in the developer console? I'm wondering if it might be related to #1906..

Thanks in advance!

**Comment by michlschmitt** [comment]
@rijkvanzanten I will provide you the console output. However, it'll take some time, because I have no IE 11 near to me...

**Comment by rijkvanzanten** [comment]
At the moment, all core developers are working fulltime on the next major version of the platform, so I'll have to leave this open as a help-wanted. If anyone is inclined to take a swing at fixing this, a PR is very welcome 😄

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/26)
