### ISSUE TITLE
Field conditions with "Required value to be set on creation" not working for the API

### ISSUE THREAD

**Issue by dp1194** [directus/directus#20320]
### Describe the Bug

When defining a condition on a field with "Required value to be set on creation", the admin app respects this but the API does not.

This seems like a pretty severe bug if you are depending on these conditions to be met on when creating items through the API.

### To Reproduce

Create a new Model with the following fields,

condition_toggle: Toggle - boolean
test_1: Input - string - non nullable - required
test_2: input - string - nullable - not required

<img width="838" alt="image" src="https://github.com/directus/directus/assets/144729109/704cc48d-643c-4071-82fe-bc1b71e6ce90">

Add a condition to `test_2` which is based on `condition_toggle` being true and is required.

<img width="825" alt="image" src="https://github.com/directus/directus/assets/144729109/b8f4d93f-2544-4430-93b1-f014f05ddf86">

Create a new Test item with `condition_toggle: false` and hit save. As expected, only test_1 is required.

<img width="862" alt="image" src="https://github.com/directus/directus/assets/144729109/51f9fd0c-879f-47b9-8f9a-990ed0e02dcf">

Set condition_toggle to true and hit save. As expected, test_1 and test_2 are required.

<img width="898" alt="image" src="https://github.com/directus/directus/assets/144729109/344ce294-8428-4744-8bb9-30ad488476f2">

Now do the same through the GraphQL API.

```
mutation {
    create_Test_item(data: { condition_toggle: true, test_1: "foo" }) {
        id
    }
}
```

When condition_toggle is true and test_2 is not provided, the item is created successfully.

<img width="591" alt="image" src="https://github.com/directus/directus/assets/144729109/d9e1170e-1e1a-4231-b005-a7049006b40f">

**Snapshot**

```
version: 1
directus: 14.0.2
vendor: postgres
collections:
  - collection: Test
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: Test
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      preview_url: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: null
      versioning: false
    schema:
      name: Test
fields:
  - collection: Test
    field: condition_toggle
    type: boolean
    meta:
      collection: Test
      conditions: null
      display: null
      display_options: null
      field: condition_toggle
      group: null
      hidden: false
      interface: boolean
      note: Make test_2 required.
      options: null
      readonly: false
      required: true
      sort: 2
      special:
        - cast-boolean
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: condition_toggle
      table: Test
      data_type: boolean
      default_value: false
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: Test
    field: id
    type: integer
    meta:
      collection: Test
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: 1
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: id
      table: Test
      data_type: integer
      default_value: nextval('"Test_id_seq"'::regclass)
      max_length: null
      numeric_precision: 32
      numeric_scale: 0
      is_nullable: false
      is_unique: true
      is_primary_key: true
      is_generated: false
      generation_expression: null
      has_auto_increment: true
      foreign_key_table: null
      foreign_key_column: null
  - collection: Test
    field: test_1
    type: string
    meta:
      collection: Test
      conditions: null
      display: null
      display_options: null
      field: test_1
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: true
      sort: 3
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: test_1
      table: Test
      data_type: character varying
      default_value: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: Test
    field: test_2
    type: string
    meta:
      collection: Test
      conditions:
        - name: Required when toggle enabled
          rule:
            _and:
              - condition_toggle:
                  _eq: true
          required: true
          options:
            font: sans-serif
            trim: false
            masked: false
            clear: false
            slug: false
      display: null
      display_options: null
      field: test_2
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      sort: 4
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: test_2
      table: Test
      data_type: character varying
      default_value: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
relations:
  - collection: directus_settings
    field: public_favicon
    related_collection: directus_files
    meta: null
    schema:
      table: directus_settings
      column: public_favicon
      foreign_key_table: directus_files
      foreign_key_column: id
      constraint_name: directus_settings_public_favicon_foreign
      on_update: NO ACTION
      on_delete: NO ACTION
```

### Directus Version

v10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Conditions only change visual/frontend/app settings. If you want to enforce validation rules on the API you'll want to use "validation" instead.

**Comment by dp1194** [comment]
Ah, right! That makes sense. Thanks for pointing out!

**Comment by br41nslug** [comment]
Usually i would point you to the docs explaining this too but with the search broken i cannot find it myself either 🙈

**Comment by dp1194** [comment]
That's ok. I know exactly what you mean. I guess it's just a bit confusing which ones to use for when. The validation rules will work nicely and the only thing that's different really is that I have to provide my own message. I guess I will try match it to the response you get when a field is required in the usual way.

**Comment by dp1194** [comment]
Maybe I wasn't confused. Just attempting to setup validation rules but you can only do validation on the field itself and it con't be based on a different field.

<img width="423" alt="image" src="https://github.com/directus/directus/assets/144729109/5a1c8d6a-c119-4463-9107-fbba557cbab3">

If you could point me to the docs on this then that would be great as I can't seem to find anything on this.

Surely the conditions should be enforced by the API as well, otherwise what's the point? If I could do a condition as you say using the validation rules then that's a perfectly acceptable workaround, but as I cannot, I need to implement the validation logic in a custom hook or endpoint, which seems such a waste as you are already doing it for the UI.

Anyway, maybe not a bug but this is definitely a useful feature at least.

**Comment by dp1194** [comment]
I do still think this is a big, for 2 reasons,

- Nowhere is it clear that conditions won't be enforced by the API. Which means you could have many users that are expecting the conditions are met when in fact they aren't.
- Directus is a headless CMS. Any field validation should carry through to the API.

**Comment by br41nslug** [comment]
> If you could point me to the docs on this then that would be great as I can't seem to find anything on this.

Will do, if/once i find it

> Surely the conditions should be enforced by the API as well, otherwise what's the point?

Conditions just toggle frontend interface options, particularly useful to make "conditional fields" where for example selecting a value from a dropdown will hide and/or show other form fields, or changes another dropdowns options, etc. (only the somewhat confusing "required" input option could actually have any API side effect)

> Directus is a headless CMS. Any field validation should carry through to the API.

This is exactly what "validation" does and also why "conditions" aren't called "validation".

> Anyway, maybe not a bug but this is definitely a useful feature at least.

You're very welcome to create a [Feature Request](https://github.com/directus/directus/discussions/categories/feature-requests) or improvement to the docs of course 😄

**Comment by dp1194** [comment]
> (only the somewhat confusing "required" input option could actually have any API side effect)

But it it doesn't have any API side effects. Should it? If it should then can we re-open this issue? If it shouldn't then I guess I'll open a feature request for more complex field validation rules as below.

> This is exactly what "validation" does and also why "conditions" aren't called "validation".

Validation doesn't currently allow a more complex rule. E.g. If `condition_toggle` is true and `test_2` is null then "This field is required".

**Comment by br41nslug** [comment]
> But it it doesn't have any API side effects. Should it? If it should then can we re-open this issue? If it shouldn't then I guess I'll open a feature request for more complex field validation rules as below.

We're still talking about "Conditions" so *it shouldn't*, as mentioned before conditions are App-only and have no impact on how the API functions

> I guess I'll open a feature request for more complex field validation rules

Perfect, that's exactly what feature requests are for

**Comment by dp1194** [comment]
Great, will do. Thanks for clarifying!
