### ISSUE TITLE
Endpoint is being reg. but route is unavailalbe

### ISSUE THREAD

**Issue by aliemba** [directus/directus#20336]
### Describe the Bug

For existing endpoint prior to 10.7 **and** when creating new endpoints; it shows under "INFO: Loaded extensions:" and shows no errors elsewhere.

But when hitting the endpoint it gives "DEBUG: Route /test doesn't exist."

Either the documentation is unclear or the endpoint is broken.

Also tried via the extension builder

### To Reproduce

in the endpoints directory create a folder called "test" add index.mjs (or js) with 

`export default (router) => {
	router.get('/', (req, res) => res.send('Hello, World!'));
};`

When trying '/test'

0|directus  | [11:03:00.367] DEBUG: Route /test doesn't exist.
0|directus  |     err: {
0|directus  |       "type": "",
0|directus  |       "message": "Route /test doesn't exist.",
0|directus  |       "stack":
0|directus  |           DirectusError: Route /test doesn't exist.
0|directus  |               at notFound (file:///var/node/admin/node_modules/@directus/api/dist/controllers/not-found.js:25:14)
0|directus  |               at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|directus  |       "name": "DirectusError",
0|directus  |       "extensions": {
0|directus  |         "path": "/test"
0|directus  |       },
0|directus  |       "code": "ROUTE_NOT_FOUND",
0|directus  |       "status": 404
0|directus  |     }

### Directus Version

v10.7.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
This has been resolved in the latest release by https://github.com/directus/directus/pull/20259
