### ISSUE TITLE
`Replace File` wipes fields

### ISSUE THREAD

**Issue by luigigorlero** [directus/directus#20331]
### Describe the Bug

https://github.com/directus/directus/assets/22613842/b754b64d-7db8-45fb-81c2-97fcc64a28e1

Inside the App’s File Library, using the `Replace File` button under the thumbnail wipes Title, Description and Tags data. Most of the time, we are using `Replace File` to upload an updated version of a certain file/image, this forces us to fish the old information from the Revisions panel.

Is this expected behaviour? In that case I would suggest to add an `Update File` button to retain those infos.

### To Reproduce

Add Title, Description and Tags information to a file/image and use the `Replace File` function

### Directus Version

v10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Edit 1:** Title was originally set automatically by Directus (based on filename), I manually wrote Description and added Tags. In the video I’m re-uploading the same file, however Directus isn’t picking up the Title on FileReplace.

**Comment by br41nslug** [comment]
Looks like it is overwriting those fields based on the metadata extracted from the new image. However it should probably only do this when these fields actually hold data and not if the "new metadata" is empty.
