### ISSUE TITLE
Video display as a image preview downloads the whole video in content list

### ISSUE THREAD

**Issue by MarvinXu** [directus/directus#20333]
### Describe the Bug

I have a file field that display as a image preview in the content table view.
![image](https://github.com/directus/directus/assets/7382357/a672aed0-58ea-4358-89c2-d8bc100ad506)
When I open the content table view, there is a request trying to download **the whole video** instead of a "preview"(or nothing). This holds all my following requests causing really slow page response. And it won't stop downloading even I navigate to other pages!

![image](https://github.com/directus/directus/assets/7382357/604cb1ae-c416-4173-8a1d-0c61c4ca7104)

![image](https://github.com/directus/directus/assets/7382357/0faed5a0-7472-4703-9764-cfdc6ddadf2e)

### To Reproduce

- Add a file field to a collection
- set display as image
- open collection content page

### Directus Version

v10.7.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
This is a consequence of the `image` display trying to load your video as an image. If you want to avoid this in a situation where you're dealing with non-images you'll want to use the "file" display instead

![image](https://github.com/directus/directus/assets/9389634/a4ed4632-f313-4d5b-9fee-466517fd648b)

![image](https://github.com/directus/directus/assets/9389634/5fa1d8af-62e7-4b93-b730-1d4b503b5661)
