### ISSUE TITLE
Saving a Content Version with relational fields does not work more than once

### ISSUE THREAD

**Issue by bk-azi** [directus/directus#20337]
### Describe the Bug

The feature of content versioning does not seem to work correctly with N:N and M2A relational types.
This bug occurs if you try to save a version with changes in a relational field more than once.

### To Reproduce

1. Create a collection with a N:N or M2A field.
2. Create an item A in the collection. Add a reference to another item B in the relation field.
3. Create a new version "draft" of item A.
4. Change item B in the "draft" version and save the "draft".
5. Change item B again in the "draft" version.

**Result:** The button for saving the version is disabled. Changing other non-relational fields of item A, enables it again. However, if you save the version with this workaround, the changes in the relational field are not applied.

### Directus Version

v10.7.1

### Hosting Strategy

Directus Cloud

**Comment by azrikahar** [comment]
> N:N and M2A relational types.

This description seems to be the key, as I believe this may be related to `useRelationMultiple` composable used in both `list-m2m` and `list-m2a` interface, particularly with how it internally fetches the relation items so the data isn't including the relational content version from the original content item.

**Comment by theTestTube** [comment]
This is particularly easy to reproduce with translations.

**Comment by esonesson** [comment]
For me the save button is only enabled when I create a new version. After saving the first time it's never enabled again, even if I create, delete or update relational fields (translations etc.). Using 10.8.2 as well.
