### ISSUE TITLE
Drag-and-drop field sorting broken in Safari

### ISSUE THREAD

**Issue by programmarchy** [directus/directus#20349]
### Describe the Bug

The drag-and-drop sorting in a collection appears to have broken in Safari (still works in Chrome, though).

Instead of popping out and dragging with the mouse down, the text gets highlighted instead.

Currently broken in 10.7.2. Confirmed working in 10.6.3 and seems like the break occurred in 10.6.4.

Works in 10.6.3
<img width="1552" alt="dnd-10 6 3-working" src="https://github.com/directus/directus/assets/622192/59e1c199-d429-4135-b2fc-2b06088b06a7">

Not in >=10.6.4
<img width="1552" alt="dnd-10 6 4-broken" src="https://github.com/directus/directus/assets/622192/f262a6cb-083d-473d-9613-46574773609f">

### To Reproduce

Click and drag a collection field using Safari (v17). This causes text to be highlighted instead of the field to be moved.

### Directus Version

v10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by bstrr** [comment]
This is also an issue in Safari when editing the order of columns in a table view.

**Comment by mattbisme** [comment]
I'm running into this same issue. Doesn't work in Safari (I'm running macOS Sonoma), but it does work in Firefox Developer.

**Comment by Hinkolas** [comment]
I have the same issue on macOS, but for some reason it works fine on iOS 17.0 as seen in the image below:


![Simulator Screenshot - iPhone 15 Pro - 2023-12-15 at 09 39 38](https://github.com/directus/directus/assets/90035653/86f779f2-0775-4db5-a2fe-22bca1e8e6db)

**Comment by azrikahar** [comment]
> Currently broken in 10.7.2. Confirmed working in 10.6.3 and seems like the break occurred in 10.6.4.

@programmarchy thank you for this important information! It definitely made it a lot easier to narrow down what could be the potential commits within the `10.6.4` release that causes this bug to start happening 👍
