### ISSUE TITLE
Mandatory Field allowing null values

### ISSUE THREAD

**Issue by danieljones97** [directus/directus#2034]
When setting up a new table, I specified that the first field was mandatory, however when adding my first row to the table using Postman and the API, I could leave the first field blank and the table was still updating with the new row.
 
## Version Info
  - Directus version and branch: 6.4.3
  - PHP version: 5.6.0
  - MySQL version: 5.5.55
  - Web server: Apache 5.5.1
  - OS name and version: macOS Sierra Version 10.12

## Expected Behavior
I should receive an error stating that the first field is mandatory

## Actual Behavior
The table is updated with the new row and the first field is null.

## Steps to Reproduce
1) Create a new table in directus.
2) Add a new field and click the star next to the column to state it is required.
3) Using Postman, hit the API endpoint without passing any data to that first field.

**Comment by WellingGuzman** [comment]
it will be done on 7.0 (API 2.0)
Ref: https://github.com/directus/directus/issues/2035#issuecomment-361042954

**Comment by rijkvanzanten** [comment]
This is being implemented in the next major version of the API. Unfortunately, (due to the small core team size) we won't have the resources to implement this in the current version as well. 

If anyone wants to take a swing at this (in 6.x) a PR is very welcome 😄

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/28)
