### ISSUE TITLE
Directus does not upload files.

### ISSUE THREAD

**Issue by soucannabisdev** [directus/directus#20342]
### Describe the Bug

When installing Directus Docker, as per the docker-compose.yml example in the documentation, but when trying to upload any file, I get the following error.

![image](https://github.com/directus/directus/assets/118570727/36671c0d-9f7e-4bc8-8753-cc8d1ec3deeb)

![image](https://github.com/directus/directus/assets/118570727/e757398d-5fc4-42ca-b854-f210cf1cdad4)

### To Reproduce

Ubuntu Server

### Directus Version

v10.7.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
What configuration options have you used for storage?

**Comment by soucannabisdev** [comment]
I just executed - docker-compose.yml

version: '3'
services:
  database:
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    image: redis:6

  directus:
    image: directus/directus:10.7.1
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    depends_on:
      - cache
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: 'https://directus.example.com'

**Comment by br41nslug** [comment]
Double check the permissions on your local uploads folder
> - ./uploads:/directus/uploads

**Comment by soucannabisdev** [comment]
It worked out!!
Access the /uploads folder inside the container and set the permission from 755 to 777
