### ISSUE TITLE
`process.env.NODE_ENV` is left as is when the extension manager bundle app extensions

### ISSUE THREAD

**Issue by gbicou** [directus/directus#20351]
### Describe the Bug

Directus fails to load extensions when some of them depends on external libraries that relies on `process.env.NODE_ENV` (tippy.js for example).

### To Reproduce

- create an extension
- depend on tippy.js (for example)

### Directus Version

v10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Please provide more detail in your reproduction steps. `process.env.NODE_ENV` should not be an issue for backend extension running on nodejs.

**Comment by paescuj** [comment]
This should already be replaced when bundling via Extension SDK, see https://github.com/directus/directus/pull/7627.
The plan was to adjust this to only replace it for App extensions though, see https://github.com/directus/directus/issues/17556.

**Comment by gbicou** [comment]
OK, for example in the `directus-extension-tiptap` there is an indirect dependency on tippy.js through @tiptap/vue-3 package.
Tippy.js relies on the bundler to specify the NODE_ENV (https://atomiks.github.io/tippyjs/v6/faq/#i-m-getting-uncaught-referenceerror-process-is-not-defined).

If I build the extension without externals this is OK.
But if I build the extensions with externals deps, the directus extensions manager miss it, and the `process.env` goes to the browser, and the extensions are not loading...

**Comment by paescuj** [comment]
@nickrum Thoughts on doing that on the API side instead of Extension SDK?

**Comment by gbicou** [comment]
The reason is that some tiptap extensions are in a private npm registry : the extension builder can't include them, but the extensions manager yes !

**Comment by paescuj** [comment]
Yeah, makes sense 👍 Waiting for @nickrum's input 😃

**Comment by nickrum** [comment]
This is the exact reason why I didn't like the idea of introducing node resolution to the App extension entrypoint bundler. App extensions should be single js files which can be loaded by the browser. The bundling on server startup was meant to be an optimization which is an implementation detail that the extension shouldn't be concerned about.

**Comment by paescuj** [comment]
> This is the exact reason why I didn't like the idea of introducing node resolution to the App extension entrypoint bundler. App extensions should be single js files which can be loaded by the browser. The bundling on server startup was meant to be an optimization which is an implementation detail that the extension shouldn't be concerned about.

I see 🤔 What would be your preferred solution in this case?

**Comment by paescuj** [comment]
@nickrum I'm not quite sure how to proceed here... Kinda seems like a fair use case to have private packages as external deps for an app extension, right? 🤔

**Comment by gbicou** [comment]
As a workaround, I use async `import()` wrapped in vue `Suspense` for those external dependencies...

**Comment by rijkvanzanten** [comment]
Closing this as a wontfix. I don't think our in-api bundling should do any transformations to the included code itself, as that can easily cause hard to debug bugs. If an app extension wants to include code that contains a `process.env` value, it's up to the build step of the extension itself to resolve that before shipping it to production. Ty!
