### ISSUE TITLE
Validation Fields not enforcing rules

### ISSUE THREAD

**Issue by danieljones97** [directus/directus#2035]
On text fields you can specify validation in the form of a Regular Expression. When I tried to use this feature, the regex I used was not enforced. I set it up to only allow letters a to z, in lower case and exactly two characters. The regex I used for this was `[a-z][a-z]`
When I used Postman to hit the API endpoint for this table, I passed "abc" to test and no error was returned and the table was updated. 
 
## Version Info
  - Directus version and branch: 6.4.3
  - PHP version: 5.6.0
  - MySQL version: 5.5.55
  - Web server: Apache 5.5.1
  - OS name and version: macOS Sierra Version 10.12

## Expected Behavior
I should receive an error stating that the data is invalid and my custom Validation Message should be displayed.

## Actual Behavior
No error is returned and the table is updated with the new row

## Steps to Reproduce
1) Create a new table in directus.
2) Add a new field and go to the interface options
3) Select the "Regex" Validation Type and under Validation String, enter `[a-z][a-z]`
4) Using Postman, hit the API endpoint for this new table and pass the first field as "abc"
5) Notice that there is no error returned and the table is updated with the new row in directus.

**Comment by WellingGuzman** [comment]
We actually are working to make this works as described on API 2.0. We don't know if it will be worth the time to make it work for API 1.x.

I will add this to the Directus 7.0 list.

**Comment by danieljones97** [comment]
@WellingGuzman Do you have a timeframe for when this will be implemented and usable?

**Comment by WellingGuzman** [comment]
@danieljones97 Not soon, we are still developing the API and application.

A "quick" and good solution to implement this into 1.x is using hooks, and throw exception if the data being inserted/update doesn't match a validation set.

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/29)
