### ISSUE TITLE
Permissions are not merged with minimal app permissions when they are fetched

### ISSUE THREAD

**Issue by azrikahar** [directus/directus#20358]
### Describe the Bug

After creating a new role and user, modifying the `directus_user` read permission to include an additional field over the minimal app permission field will cause the fetching of permissions to have 2 permissions instead of 1.

This however is not an issue on the API side because when the API retrieves the permissions in the middleware:

https://github.com/directus/directus/blob/9a1ba0982ce0e8d0bf93b8367d82e69a1b458aeb/api/src/middleware/get-permissions.ts#L10

the `getPermissions` used will then merge both permissions together over here:

https://github.com/directus/directus/blob/9a1ba0982ce0e8d0bf93b8367d82e69a1b458aeb/api/src/utils/get-permissions.ts#L86-L92

leading to a singular permission:

```js
[
  {
    role: '434419af-b63e-4073-8190-22943c868cc4',
    collection: 'directus_users',
    action: 'read',
    permissions: {
      _or: [
        { id: { _eq: 'a5ee8d0c-87e3-4167-8b45-3cb60c081819' } }
      ]
    },
    validation: {},
    presets: {},
    fields: [
      'last_access',
      'id',
      'first_name',
      'last_name',
      'last_page',
      'email',
      'password',
      'location',
      'title',
      'description',
      'tags',
      'preferences_divider',
      'avatar',
      'language',
      'appearance',
      'theme_light',
      'theme_dark',
      'theme_light_overrides',
      'theme_dark_overrides',
      'tfa_secret',
      'status',
      'role',
      'theme'
    ]
  }
]
```

However when permissions are fetched via the permissions services:

https://github.com/directus/directus/blob/9a1ba0982ce0e8d0bf93b8367d82e69a1b458aeb/api/src/services/permissions.ts#L46-L62

The minimal app permissions are only appended rather than merged with any applicable permissions. Thus when the API returns permissions, it has 2 entries instead of 1:

```js
[
  {
    "id": 50,
    "role": "434419af-b63e-4073-8190-22943c868cc4",
    "collection": "directus_users",
    "action": "read",
    "permissions": null,
    "validation": null,
    "presets": null,
    "fields": ["last_access"]
  },
  {
    "system": true,
    "role": "434419af-b63e-4073-8190-22943c868cc4",
    "collection": "directus_users",
    "action": "read",
    "permissions": {
      "id": {
        "_eq": "$CURRENT_USER"
      }
    },
    "validation": null,
    "presets": null,
    "fields": [
      "id",
      "first_name",
      "last_name",
      "last_page",
      "email",
      "password",
      "location",
      "title",
      "description",
      "tags",
      "preferences_divider",
      "avatar",
      "language",
      "appearance",
      "theme_light",
      "theme_dark",
      "theme_light_overrides",
      "theme_dark_overrides",
      "tfa_secret",
      "status",
      "role",
      "theme"
    ]
  }
]
```

This will then cause a similar issue with #19369 where the App will only use the first permission that it can find rather than the "merged" permission like what the API does.

---

A potential solution seems to be using `mergePermissions` within the permissions service instead of `result.push`, which seemed to work from a quick test, but I'm not sure are there any unforeseen problems that can potentially be caused by this solution.

### To Reproduce

1. Create a new role
2. Reset the system permissions for that role to `App Access Minimum`
3. Create a new custom `read` permission on `directus_users`
4. Check the `last_access` field

   ![](https://github.com/directus/directus/assets/42867097/15260837-278b-4614-b7fb-686ed331a8a9)

5. Create a new user with that role
6. Login as the new user
7. Look at the `/permissions` API call (which is when the permissions store is hydrated), and there will be 2 entries instead of 1 for `directus_user` `read` permission.

### Directus Version

v10.7.2 (Main branch https://github.com/directus/directus/tree/9a1ba0982ce0e8d0bf93b8367d82e69a1b458aeb)

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
Fixed in #21542
