### ISSUE TITLE
Counting M2M relations fails

### ISSUE THREAD

**Issue by maettyhawk** [directus/directus#2036]
In the table view there's this handy field showing how many M2M relations for a M2M field exist (f.e. files). This field is always showing zero, eventhough there a exisiting relations.

## Version Info
  - Directus version and branch: lastest (6.4.5)
  - PHP version: 7.1.8
  - MySQL version: 5.0.12
  - Web server: Apache (within MAMP env)
  - OS name and version: MacOS Sierra

## Expected Behavior
The right amount of relations is displayed.

## Actual Behavior
Zero relations are displayed.

## Steps to Reproduce
 1. Add table with M2M relation (f.e. table "downloads" with m2m field "files")
 2. Add an alias table (f.e. downloads_id and file_id)
 3. Configure M2M field using the alias table in order to relate to directus_files table
 4. Add rows to table, choose files
 5. List view shows "0 files" eventhough there are files selected

## Schema Dump, Logs, or Screenshots
![directus test verzeichnis](https://user-images.githubusercontent.com/1299262/35442520-d99ea9e0-02a7-11e8-9ccd-b2fc304676d3.png)

**Comment by WellingGuzman** [comment]
@maettyhawk thanks for reporting this issue.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/d88c2ffcb12797367186d7efda9c8cb427d82b83
