### ISSUE TITLE
SSO login should update name and email on subsequent logins

### ISSUE THREAD

**Issue by dasantonym** [directus/directus#20362]
### Describe the Improvement

We are using Keycloak as an OpenID provider and noticed that when changing a user's name or email in Keycloak, this change does not get reflected in Directus. Our users are managed via Keycloak so this should be the single source of truth regarding this information.

I have made some tweaks to `ldap.ts`, `oauth2.ts` and `openid.ts` which you can see in the attached merge request.

This is a change in behaviour that might be undesired for you, but I thought I'd raise this issue just in case someone is interested.

However, if you'd like this to be included, there are questions relating to the changes that need to be sorted out first:

- The `auth_data` prop that is currently being updated is being set with the non-falsy value or `null` which I understand to be used to delete an existing value, correct? I have not used this for the names, but rather pass the value as is (`undefined` if not existing on the user info) so that the existing name remains if it is not supplied. Please correct me, if that is not the case.
- I have only made the changes for the above-mentioned files because I did not understand how this is handled in SAML. This might need to be added as well and maybe you can point me to where this is done there.
- This behaviour might be undesired for some, but not for all use cases. Would you rather have this update functionality be opt-in with an env var?

Let me know what you think of this. We are maintaining our own fork of Directus anyway, so we don't push for this to be included, but I'd be happy to make changes to suit your requirements.

**Comment by rijkvanzanten** [comment]
This does make sense to me to have included out of the box. I can't really think of a reason why you would want to explicitly disable the syncing, but I do think we should include that as an env var just to allow people to keep the current default behavior if they have a reason to do so.

**Comment by rijkvanzanten** [comment]
Any thoughts/feelings/concerns on this @aidenfoxx? 🙂

**Comment by aidenfoxx** [comment]
It depends on your system I suppose. If it's an organizational system where you want to keep your users synchronized with some authoritative system, it certainly makes sense. I would say for more general systems deferring control to the user post-authentication makes more sense, in that I would find it strange if my details kept getting reset.

Maybe that's a UX issue, and in systems that support syncing credentials, users should be prevented from updating certain details. 🤔 

But overall I think it's a good option to have. We already do it for roles in LDAP.

**Comment by aidenfoxx** [comment]
And good thing to point out on the `auth_data`. That null set was put in place to workaround a bug where sending an empty payload would cause an error, but that will unset any previous `auth_data`, which isn't ideal. I'll get a PR up on the weekend to check if the `userPayload` is empty, and skip doing a user update all together instead.

**Comment by dasantonym** [comment]
Hey @aidenfoxx and @rijkvanzanten, thanks for your thoughts on this. I will rework the pull request to make this an option to be set via env vars. This will be the least disruptive option.

I agree that it might be confusing being able to edit your name and then seeing it reset on the next login. In our case, we are using Directus merely as an API for an SPA, so this isn't an issue. But I think if the feature is opt-in, the UX issue could be dealt with separately later on. Maybe one could disable user editing in the UI with a setting?

@aidenfoxx: I'll make these changes and then wait to merge in your PR about the auth_data.

**Comment by dasantonym** [comment]
So, I made the changes but ran into some issues, maybe someone can help me out.

In `ldap.ts`, this reassignment works:

```javascript
                        // Run hook so the end user has the chance to augment the
                        // user that is about to be updated
                        let emitPayload = {};


                        // Only sync roles if the AD groups are configured
                        if (groupDn) {
                                emitPayload = {
                                        role: userRole?.id ?? defaultRoleId ?? null,
                                };
                        }


                        if (env['AUTH_SYNC_USER_INFO']) {
                                emitPayload = {
                                        ...emitPayload,
                                        first_name: userInfo.firstName,
                                        last_name: userInfo.lastName,
                                        email: userInfo.email,
                                };
                        }
```

But now the same thing in `openid.ts` and `oauth2.ts` gives me a Typescript error when building (`first_name` is not accepted as a prop).

Now, I must admit that I am a late bloomer when it comes to Typescript so I am not sure what to do here. I now did it like this, which feels a bit clumsy/verbose:

```javascript
                        // Run hook so the end user has the chance to augment the
                        // user that is about to be updated
                        let emitPayload = {};


                        // Only sync roles if the AD groups are configured
                        if (groupDn) {
                                emitPayload = {
                                        role: userRole?.id ?? defaultRoleId ?? null,
                                };
                        }


                        if (env['AUTH_SYNC_USER_INFO']) {
                                emitPayload = {
                                        ...emitPayload,
                                        first_name: userInfo.firstName,
                                        last_name: userInfo.lastName,
                                        email: userInfo.email,
                                };
                        }
```

Maybe you have a better solution?

The other thing is that I get a linter error for line 3 in the docs ('Assign to rvalue'), but I did not change anything there, just added the new env var.

**Comment by kulogix** [comment]
For anyone looking to implement this functionality sooner, you can add the following hook (e.g., /extensions/hooks/auth-update-userinfo/index.js):

```javascript
export default async ({ filter }, { logger, database, services, getSchema }) => {
	const { UsersService } = services;
	const users = new UsersService({ schema: await getSchema(), knex: database });
	
	filter('auth.update', async (input, { identifier, provider, providerPayload }) => {
		if (providerPayload.userInfo && providerPayload.userInfo.sub) {
			logger.info(`Login for user with external identifier: ${identifier}`);
			// logger.info(`userPayload.auth_data: ${JSON.stringify(input)}`);
			// logger.info(`providerPayload: ${JSON.stringify(providerPayload)}`);
			const user = await database
				.select('id', 'first_name', 'last_name', 'email')
				.from('directus_users')
				.whereRaw('LOWER(??) = ?', ['external_identifier', identifier.toLowerCase()])
				.first();
			// logger.info(`Existing User: ${JSON.stringify(user)}`);
			
			if (
				user
				&& (providerPayload.userInfo.email && providerPayload.userInfo.given_name && providerPayload.userInfo.family_name)
				&& (
					providerPayload.userInfo.email != user.email
					|| providerPayload.userInfo.given_name != user.first_name
					|| providerPayload.userInfo.family_name != user.last_name
				)
			) {
				const userIds = await users.updateByQuery(
					{ filter: { id: user.id } }, 
					{ 
						email: providerPayload.userInfo.email,
						first_name: providerPayload.userInfo.given_name, 
						last_name: providerPayload.userInfo.family_name
					}
				);
				logger.info(`During login for user with external identifier ${identifier}, updated user ${user.id}: email from '${user.email}' to '${providerPayload.userInfo.email}', first name from '${user.first_name}' to '${providerPayload.userInfo.given_name}', last name from '${user.last_name}' to '${providerPayload.userInfo.family_name}'.`);
			} else if (
				user
				&& providerPayload.userInfo.email
				&& providerPayload.userInfo.email != user.email
			) {
				const userIds = await users.updateByQuery(
					{ filter: { id: user.id } },
					{
						email: providerPayload.userInfo.email
					}
				);
				logger.info(`During login for user with external identifier ${identifier}, updated user ${user.id}: email from '${user.email}' to '${providerPayload.userInfo.email}'.`);
			}
		}
		
		// Return the payload unchanged
		return input;
	});
};
```
