### ISSUE TITLE
Export doesn't to file work for limit = -1

### ISSUE THREAD

**Issue by Voldemorten** [directus/directus#20370]
### Describe the Improvement

When query limit is set to -1, which is supposed to select all items, it remains as -1 which results in a exported file with zero data exported.

Proposed change:
`const count = query.limit ? Math.min(totalCount, query.limit) : totalCount;` → `const count = query.limit > 0 ? Math.min(totalCount, query.limit) : totalCount;`

**Comment by azrikahar** [comment]
Seems like this exact line of code was actually fixed by #19820 in version `10.6.4`, so perhaps you are on an older version before that?

Closing this for now unless it is still reproducible on the latest version (`10.7.2` as of the writing of this comment) 👍
