### ISSUE TITLE
Directus extension build in dist folder.

### ISSUE THREAD

**Issue by Rafache** [directus/directus#20399]
### Describe the Bug

Hello, there is a problem with custom extensions. By default, extensions created with `npx create-directus-extension@latest` are built in the `dist` folder as marked in the package.json file.

```
"directus:extension": {
  "type": "endpoint",
  "path": "dist/index.js",
  "source": "src/index.js",
  "host": "^10.1.14"
},
```

Directus seems to look for compiled files at the root of the extension :

```
[19:18:23.833] WARN: Couldn't bundle App extensions
[19:18:23.833] WARN: Could not resolve "./extensions/panels/hello/index.js" from "virtual:entry"
    err: {
      "type": "Error",
      "message": "Could not resolve \"./extensions/panels/hello/index.js\" from \"\u0000virtual:entry\"",
      "stack":
          RollupError: Could not resolve "./extensions/panels/hello/index.js" from "virtual:entry"
              at error (file:///directus/node_modules/.pnpm/rollup@3.22.0/node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
              at ModuleLoader.handleInvalidResolvedId (file:///directus/node_modules/.pnpm/rollup@3.22.0/node_modules/rollup/dist/es/shared/node-entry.js:23979:24)
              at file:///directus/node_modules/.pnpm/rollup@3.22.0/node_modules/rollup/dist/es/shared/node-entry.js:23941:26
      "code": "UNRESOLVED_IMPORT",
      "exporter": "./extensions/panels/hello/index.js",
      "id": "\u0000virtual:entry",
```

**To get around the problem, simply remove `/dist` from the path in the package.json file.**

It would be great to correct this directly in Directus or in the `create-directus-extension` module which automatically generates this file.

thanks 

### To Reproduce

```
npx create-directus-extension@latest
...
cd "extension name"
npm run dev
```

### Directus Version

10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
If you create an extension with the `create-directus-extension` tool you should place the resulting extension folder in the
root of the extensions path (`./extensions`) and not inside one of the extensions type folders (e.g. `./extensions/panels`). Using these subfolders is no longer recommended and those will be deprecated in the near future.
The structure should look like this (note that the folder of your extension needs to be prefixed with `directus-extension-` until the deprecation of extension type folders):
```
extensions/
  directus-extension-my-custom-panel/
    dist/
      index.js
    package.json
  ...
```

You can find more information under https://docs.directus.io/extensions/installing-extensions.html#installing-through-the-extensions-folder.

**Comment by Rafache** [comment]
THANK YOU ! 
Indeed, if I put the extensions directly at the root of the extensions folder and adding a prefix "directus-extension-" it works as it should and will read the files in the dist folder.
However, when I delete the "display, endpoints, hooks, etc." folders, they end up "reappearing" when I restart the docker container.

**Comment by paescuj** [comment]
You're very welcome!

> However, when I delete the "display, endpoints, hooks, etc." folders, they end up "reappearing" when I restart the docker container.

That's right. Currently, those are auto-created if missing. We'll remove this as well in the near future 👍

**Comment by Rafache** [comment]
Thank you for your help. Directus is so amazing...
