### ISSUE TITLE
`directus-extension add` rewrites package.json

### ISSUE THREAD

**Issue by ameotoko** [directus/directus#20394]
### Describe the Bug

If custom `devDependencies` have been added during a development of a bundle-type extension, running `directus-extension add` deletes them.

Additional, lesser parts of the problem also are:

- other entries in the `package.json`, albeit preserved, are moved around and changed places, which introduces unnecessary VCS changes
- CLI has no option to skip actual invocation of `npm install`, like Composer does e.g. with `composer update --no-install`, to only update the `.json` file and be able to review changes before time-consuming installation process is initiated

### To Reproduce

1. Generate an initial extension structure with `npx create-directus-extension`, provide extension type "bundle"
2. Run `directus-extension add` to add e.g. a hook
3. Add some dev dependencies by running `npm install <SOME_DEP> --save-dev`
4. Run `directus-extension add` to scaffold another part of your bundle, e.g. an interface
5. Your `devDependencies` are now reverted to initial state, your custom ones are uninstalled, those that Directus itself adds are reverted to earlier versions

### Directus Version

10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by nickrum** [comment]
Should be easy to fix by first defining the dependencies that are needed by the extensions in the bundle and then overwriting them by what's already in the `package.json` dependencies list.

> other entries in the `package.json`, albeit preserved, are moved around and changed places, which introduces unnecessary VCS changes

I stumbled upon this as well. It might be related to the way how `zod` messes with the package manifest.

> CLI has no option to skip actual invocation of `npm install`, like Composer does e.g. with `composer update --no-install`, to only update the `.json` file and be able to review changes before time-consuming installation process is initiated

I'd be down to add that. Seems like a no-brainer 👍

Could you create separate issues for the other two improvements so we can track them individually? That'd be great!

**Comment by ameotoko** [comment]
> Could you create separate issues for the other two improvements so we can track them individually? That'd be great!

Done, see #20401, #20402
