### ISSUE TITLE
Extension folder name requirement not clear enough

### ISSUE THREAD

**Issue by tomgreener** [directus/directus#20405]
### Page

https://docs.directus.io/extensions/installing-extensions.html

### Describe the Inaccuracy

When [installing extensions locally via the extensions folder](https://docs.directus.io/extensions/installing-extensions.html#installing-through-the-extensions-folder), extensions are only recognised and loaded when placed in a folder named `directus-extension-{name}`. This is not made clear enough in the areas I would expect in the Extensions documentation. It is mentioned in the section on [installing through NPM](https://docs.directus.io/extensions/installing-extensions.html#installing-through-npm) and also in a [separate API proxy guide](https://docs.directus.io/guides/extensions/endpoints-api-proxy.html) but it is not mentioned in the section on installing locally or the page on creating extensions where it would be most useful.

**Comment by phazonoverload** [comment]
Yup, agree, and @estheragbaje is on it. Thanks for raising it!

**Comment by tomgreener** [comment]
Thanks for addressing ⭐
