### ISSUE TITLE
Content versions do not seem to work with relationships

### ISSUE THREAD

**Issue by davecalleja-casumo** [directus/directus#20429]
### Describe the Bug

When trying out content versioning on basic fields (text for example), it works great and is an awesome feature, yet when trying it out on relationships, the behaviour is very strange.

I have a model called a **page** which is basically a wrapper for references to other pieces of content. Initially I was hoping content versions of those pieces of content would propagate when querying the **page**. It seems this does not work. The content version is only applied to the item you are querying and not any related content.

I decided to work around this by creating a content version of the **page** and changing one of the references to something new. Although this works, the functionality is limited. Querying via _graphql_ throws an error when trying to get the `id` of the related item. And querying via REST will only ever respond with the `id` of the related item (no matter how many levels of `fields=*.*.*` you add).

This highly limits this awesome feature and how it is just me doing something wrong :) 

### To Reproduce

- Create a collection called **pages**
- Create a collection called **blocks**
- For **pages**, add a many-to-one relationship with **blocks**
- For **blocks** add a text field called `name`
- Populate some content in each collection
- Create a content version of one of the referenced blocks called `experiment-ref`

#### Graphql
- Query pages via Graphql with `?version=experiment-ref`
- Add `id` to block fields in query results in `Cannot return null for non-nullable field`
- Any other field is the original value (not the content version)

##### REST
- Query pages via REST with `?version=experiment-ref`
- Reference value is always the id even when adding `fields=*.*.*`

---

- Create a content version of one of the pages called `experiment-page`

#### Graphql
- Query page via Graphql with `?version=experiment-page`
- Reference fields are `null`

#### REST
- Query page via Graphql with `?version=experiment-page`
- Reference value is always the id even when adding `fields=*.*.*`

### Directus Version

v10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by azrikahar** [comment]
> Create a content version of one of the referenced blocks called `experiment-ref`

Just to be sure I understand this correctly, do you mean you are creating the content version `experiment-ref` to an item in `blocks` collection, then trying to get it via `pages` collection item such as `/items/pages/1?version=experiment-ref`? If that is the case, that would unfortunately not work as the content version should be done in `pages` collection item, not the related collection item.

> - Create a content version of one of the pages called `experiment-page`
>
> #### Graphql
> - Query page via Graphql with `?version=experiment-page`
> - Reference fields are `null`
> 
> #### REST
> - Query page via Graphql with `?version=experiment-page`
> - Reference value is always the id even when adding `fields=*.*.*`

Can you share the exact GraphQL and REST query you are using? I believe the second `via Graphql` is intended to be `via REST`, but wanted to be sure we'll be able to reproduce the exact same described issue with the exact query used 👍

**Comment by davecalleja-casumo** [comment]
Thanks for the reply @azrikahar .

So let's take this as an example:
- Create block collection with "name" text input
- Create page model with "blocks" many-to-many input

Graphql request

```
query versioning_test {
  test_page_by_id(id: 1) {
    blocks {
      test_blk_id {
        name
      }
    }
  }
}
```

Graphql Result

```
{
  "data": {
    "test_page_by_id": {
      "blocks": [
        {
          "test_blk_id": {
            "name": "First Block"
          }
        }
      ]
    }
  }
}
```

After creating an `experiment-page` content version on the page item...

Graphql request

```
query versioning_test {
  test_page_by_id(id: 1, version: "experiment-page") {
    blocks {
      test_blk_id {
        name
      }
    }
  }
}
```

Graphql Result

```
{
  "data": {
    "test_page_by_id": {
      "blocks": null
    }
  },
  "errors": [
    {
      "message": "Expected Iterable, but did not find one for field \"test_page.blocks\".",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      },
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "test_page_by_id",
        "blocks"
      ]
    }
  ]
}
```

Using the REST API gives other errors but lets focus on just graphql for now :)
