### ISSUE TITLE
Date not conform to the required format each time a key is pressed in an interface

### ISSUE THREAD

**Issue by Pachat** [directus/directus#20424]
### Describe the Bug

Each time a key is pressed, in an input or textarea for instance, a warning it raised like this one:
`The specified value "2023-11-14T08:36:04" does not conform to the required format, "yyyy-MM-dd"`

### To Reproduce

Open the debugger and type anything in a input field

The code line that generates the error is inside this function:
```
function Dn(e, t, s, n, o, r, i) {
    if (t === "innerHTML" || t === "textContent") {
        n && i(n, o, r),
        e[t] = s ?? "";
        return
    }
    const a = e.tagName;
    if (t === "value" && a !== "PROGRESS" && !a.includes("-")) {
        e._value = s;
        const c = a === "OPTION" ? e.getAttribute("value") : e.value
          , u = s ?? "";
        c !== u && (e.value = u), //<=  The specified value "2023-11-14T08:36:04" does not conform to the required format, "yyyy-MM-dd"
        s == null && e.removeAttribute(t);
        return
    }
    let f = !1;
    if (s === "" || s == null) {
        const c = typeof e[t];
        c === "boolean" ? s = qe(s) : s == null && c === "string" ? (s = "",
        f = !0) : c === "number" && (s = 0,
        f = !0)
    }
    try {
        e[t] = s
    } catch {}
    f && e.removeAttribute(t)
}

```
This happens with every keystroke.

### Directus Version

v10.7.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
This is not something i can reproduce by blindly typing anything in any `input`. Please do elaborate on the situation:
- what browser are you using?
- is there anything to do with dates somewhere in the collection? inputs dont have date validation by default
- any extensions and/or flows?

**Comment by Pachat** [comment]
@br41nslug Edge. Right. When I remove all my interfaces extensions it is OK. So, I'll put them back one by one to find out which one produces the bug. 
Thank you for trying to reproduce.
For now, I close this.
