### ISSUE TITLE
problem with cors

### ISSUE THREAD

**Issue by artur-grzeda** [directus/directus#2043]
Hi, 

i need help with cors I think, i have error 

`GET http://##########/directus/api/1.1/tables/tasks/rows 403 (Forbidden)
directus:1 Failed to load http://###########/directus/api/1.1/tables/tasks/rows: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 403.
`

In my configuration.php i have: 

` 'cors' => [
        'enabled' => true,
        'origin' => '*',
        'headers' => [
            ['Access-Control-Allow-Headers', 'Authorization, Content-Type, Access-Control-Allow-Origin'],
            ['Access-Control-Allow-Credentials', 'false']
        ]
    ],`

I use a nuxt.js, my code to get:

`async asyncData ({ params }) {
      let { data } = await HTTP.get(`http://dev.creacode.pl/directus/api/1.1/tables/tasks/rows`)
      return { data }
    }`

Can you help me ?

**Comment by WellingGuzman** [comment]
Hey @artur-grzeda, You need to authenticate. Ex: `http://dev.creacode.pl/directus/api/1.1/tables/tasks/rows?access_token=<MY-USER-TOKEN>`

**Comment by simofacc** [comment]
@WellingGuzman I am also having the same issue. I am using the javascript SDK and I am specifying the accessToken in the client initialisation and the pre-flight check returns 200 but the GET request returns 403 even though the Authorization: Bearer is set correctly in the request headers.

Cors is enabled in the API configuration file too.

Any idea?

**Comment by simofacc** [comment]
@WellingGuzman found a similar issue in the javascript sdk repo and I managed to fix it by enabling the apache headers module and add the cors origin header in the site config file.

`Header set Access-Control-Allow-Origin "*"`

**Comment by georgecm** [comment]
This is still an issue with Directus. I'm using nuxt-directus and all requests return CORS. The server works fine. Any help please?

**Comment by rijkvanzanten** [comment]
> This is still an issue with Directus. I'm using nuxt-directus and all requests return CORS. The server works fine. Any help please?

This is a closed issue from over 5 years old. Please open a new issue 👍🏻
