### ISSUE TITLE
Trigger Flow action escapes quotation marks

### ISSUE THREAD

**Issue by mtllr** [directus/directus#20443]
### Describe the Bug

I setup a flow to dynamically dispatch a payload to another flow.

The issue as I understand is that the *Flow* input box requires me to quote the input value otherwise it raises an error because it does not support template tags. However the value that I am templating is already of type string in the form of a UUID. So when this gets passed down the line, the quotes around the UUID string get escaped and my flow id is not recognised anymore.

(Side note) I have noticed that the above quoting/escaping strategy works in a *Read Data* action when the ID field is in integer type. Maybe the use case for dynamic data does not include UUIDs?

The action flow is defined as so:

<img width="826" alt="Screenshot 2023-11-16 at 12 43 04" src="https://github.com/directus/directus/assets/10560462/40ed4522-a179-4573-bd30-0070c8a04feb">

And get the following log:

<img width="677" alt="Screenshot 2023-11-16 at 12 41 47" src="https://github.com/directus/directus/assets/10560462/afff8904-cb7c-4e61-a41e-77ddf2cbe533">

I have checked issues #14971  and #14069 before creating this issue. 

### To Reproduce

1. Make flow 1 with trigger flow to flow 2
2. Get the UUID of flow 2 and inject manually into data of flow 1
3. Update flow 1 trigger flow action *Flow* input to a template tag with the value of flow 2 UUID

### Directus Version

v10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
> The issue as I understand is that the Flow input box requires me to quote the input value otherwise it raises an error because it does not support template tags.

You can use templates there without quoting but you may have to make sure to enable template mode.
![image](https://github.com/directus/directus/assets/9389634/76f1af38-ba1e-4b5f-8706-0a53e8cb4c04)

**Comment by mtllr** [comment]
Thank you Br41nslugSent from my iPhoneOn 16 Nov 2023, at 13:44, Brainslug ***@***.***> wrote:﻿

The issue as I understand is that the Flow input box requires me to quote the input value otherwise it raises an error because it does not support template tags.

You can use templates there without quotes but you may have to make sure to enable template mode.
