### ISSUE TITLE
Multiple "Reloading extensions" get executed in sequence

### ISSUE THREAD

**Issue by u12206050** [directus/directus#20440]
### Describe the Bug

While directus server is running, whenever we do a batch `pnpm -r build` of our extensions, we notice in the console that Directus is "Reloading extensions" again and again and again * 22, which is one per extension is seems.

It does this in sequence and the server doesn't work correctly until it is finished.

Looking at the code in `api/src/extensions.ts` I notice in the `reload()` function that it is simply being enqueued onto a job stack.

## Solution

Debounce the reloading of extensions. The `chokidar.watch` being used seems to trigger the reload function multiple times per second as the files in `extensions` folder is being updated. So debounce and only execute a reload once every 1s, once in the start of the second and once in the end (if another reload has been called)

### To Reproduce

Build a lot of custom extensions in parallel whilst auto reload extensions is true.

### Directus Version

10.6

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by u12206050** [comment]
Let me know if I should submit the PR

**Comment by nickrum** [comment]
Do you think we need an "actual" debounce that only triggering a single reload when there hasn't been any reload requests for a certain amount of time or could we instead only enqueue a new reload job if there is none in the job queue?

Once we've figured that out, a PR would be highly appreciated.

**Comment by u12206050** [comment]
Well og the developer has made changes then he would anyways want to have the changes loaded before he tests it, so waiting for 500ms for additional changes I think is worth it.

**Comment by nickrum** [comment]
Makes sense to me! It might be tricky to find a "time to wait" that works for everyone, but something like 500ms would be better than nothing, so I'd be down to merge a PR 👍
