### ISSUE TITLE
Large image uploading consume over 100% of CPU in container

### ISSUE THREAD

**Issue by AndriyAntonenko** [directus/directus#20448]
### Describe the Bug

I am using self-hosted directus. Sometimes I have to download large files to my library (over 0.5GB). And during the uploading process CPU usage of the docker container is over 100%. Can you help me to understand how I can fix and optimize this upload? Here is my configuration:
```
      KEY: ...
      SECRET: ...

      PUBLIC_URL: ...

      DB_CLIENT: 'pg'
      DB_HOST: ...
      DB_PORT: ...
      DB_DATABASE: ...
      DB_USER: ...
      DB_PASSWORD: ...
      DB_SSL__REQUIRE: 'true'
      DB_SSL__REJECT_UNAUTHORIZED: 'false'
      DB_SSL__CA: '/root/ca/ca-certificate.crt'

      # Directus extension resize_images
      THRESHOLD_IMAGE_RESIZE: '50'
      FORMAT_EXTENSION: 'png'
      DEEP_DEBUG: 'false'

      LOG_LEVEL: "debug"
      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      REDIS: ...

      CACHE_TTL: '1m'
      CACHE_AUTO_PURGE: 'false'
      CACHE_SYSTEM_TTL: '1m'
      CACHE_SCHEMA: 'true'
      CACHE_NAMESPACE: 'docache'
      CACHE_STATUS_HEADER: 'true'
      ASSETS_CACHE_TTL: '30m'

      MAX_PAYLOAD_SIZE: '2048mb'

      ADMIN_EMAIL: ...
      ADMIN_PASSWORD: ...

      ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION: '16000'
      ASSETS_TRANSFORM_MAX_OPERATIONS: '50'
      ASSETS_TRANSFORM_MAX_CONCURRENT: '50'

      STORAGE_LOCATIONS: 'local'
      STORAGE_LOCAL_DRIVER: 's3'
      STORAGE_LOCAL_ROOT: '/uploads'
      STORAGE_LOCAL_BUCKET: ...
      STORAGE_LOCAL_ACL: 'public-read'
      STORAGE_LOCAL_REGION: ...
      STORAGE_LOCAL_ENDPOINT: ...
      STORAGE_LOCAL_KEY: ...
      STORAGE_LOCAL_SECRET: ....
```

### To Reproduce

To reproduce this bug, just run the docker compose with latest directus version. After this run `docker stats <container>` and try to upload large file to the file library. In this moment pay attention to the CPU usage percent.

### Directus Version

10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Some key pieces of info are missing to properly triage this:
- Are these files images that get transformed? or just any file
- Are you using local or remote file storage?
- How much CPU does this container have access to?
- Have you tried lowering the transformation size? `ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION: '16000'` because the docs explicitly mention transformations being resource intensive

**Comment by AndriyAntonenko** [comment]
Hello @br41nslug ! Thanks for your response

1. These are images (png). Does the Directus do transformation during image uploading?
2. We are using remote digital ocean space (s3).
3. My VM has 2 vCPU on digital ocean (intel)
4. No. I didn't try. I am trying to just upload an image. I thought that transformation could happen only when fetching images using assets API. Am I mistaken?

**Comment by AndriyAntonenko** [comment]
It seems it happens not on uploading but on asset thumbnail fetching. But it looks like default behavior of Directus (fetching thumbnails on library page loading). Is there are some way to optimize it?

**Comment by br41nslug** [comment]
The app does indeed load thumbnails and does this so browsers doesnt have to load all full size images for each item on the page. The server transforms these on the first request and caches it after however this initial transformation is not avoidable to my knowledge.
> Is there are some way to optimize it?

Directus has a few image transformation settings but there is not much to optimize, you could change the file library layout settings to not load images but i doubt thats the kind of optimization you're looking for. Unfortunately image transformation can be a very resource intensive process (in memory, cpu or both depending on the formats/sizes involved)
so the best i can do is suggest either:
- scale the resources horizontally or vertically to match the transformation load
- limit the size of images uploaded for the project as to not overload the server

**Comment by AndriyAntonenko** [comment]
Is it cache have some TTL? Or is it permanent?

**Comment by br41nslug** [comment]
There is a TTL for how long the browser should cache it but the transformation only happens once and gets written to disk on the server side. So thats "permanent" unless you update the image file.

**Comment by AndriyAntonenko** [comment]
Cool, thanks for your help! Have a nice day
