### ISSUE TITLE
Multiple files column throws error

### ISSUE THREAD

**Issue by studioscholz** [directus/directus#2045]
## Version Info
  - Directus version and branch: 6.4.5
  - PHP version: 7.1
  - MySQL version: 5.7
  - Web server: Apache
  - OS name and version: Ubuntu 16.04.3 x64

## Expected Behavior

Uploaded images can be connected to entries in different table.

## Actual Behavior

`This query failed: INSERT INTO `system_relationships` (`item_id`, `image_id`) VALUES ('2', '3')`

## Steps to Reproduce
 1. Setup table `inventory`
 2. Setup table `system_relationships`
 3. Create columns `item_id` and` image_id` within `system_relationships`
 4. Setup column "images" according to screenshot in `inventory`
 5. Add an entry including an image to `inventory`

## Schema Dump, Logs, or Screenshots

<img width="642" alt="screen shot 2018-02-05 at 16 56 15" src="https://user-images.githubusercontent.com/8195463/35817548-007d02b6-0a9e-11e8-9e7f-b90ad869093a.png">

<img width="625" alt="screen shot 2018-02-05 at 17 17 13" src="https://user-images.githubusercontent.com/8195463/35817554-079cf75e-0a9e-11e8-868c-1945ee076310.png">

`Next RuntimeException: This query failed: INSERT INTO `system_relationships` (`item_id`, `image_id`) VALUES ('2', '3') in /srv/users/serverpilot/apps/rebr-bookshop/public/cms/api/core/Directus/Database/TableGateway/BaseTableGateway.php:783
Stack trace:
#0 /srv/users/serverpilot/apps/rebr-bookshop/public/cms/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(264): Directus\Database\TableGateway\BaseTableGateway->executeInsert(Object(Zend\Db\Sql\Insert))
#1 /srv/users/serverpilot/apps/rebr-bookshop/public/cms/api/core/Directus/Database/TableGateway/BaseTableGateway.php(396): Zend\Db\TableGateway\AbstractTableGateway->insert(Array)
#2 /srv/users/serverpilot/apps/rebr-bookshop/public/cms/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(615): Directus\Database\TableGateway\BaseTableGateway->addOrUpdateRecordByArray(Array, 'system_relation...')
#3 /srv/users/serverpilot/apps/rebr-bookshop/public/cms/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(190): Directus\Database\TableGateway\RelationalTableGateway->addOrUpdateToManyRelationships(Object(Directus\Database\Object\Table), Array, Array, false, Array)
#4 /srv/users/serverpilot/apps/rebr-bookshop/public/cms/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(77): Directus\Database\TableGateway\RelationalTableGateway->manageRecordUpdate('inventory', Array, 1)
#5 /srv/users/serverpilot/apps/rebr-bookshop/public/cms/api/routes/A1/Entries.php(202): Directus\Database\TableGateway\RelationalTableGateway->updateRecord(Array, 1)
#6 [internal function]: Directus\API\Routes\A1\Entries->row('inventory', '2')
#7 /srv/users/serverpilot/apps/rebr-bookshop/public/cms/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Array, Array)
#8 /srv/users/serverpilot/apps/rebr-bookshop/public/cms/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#9 /srv/users/serverpilot/apps/rebr-bookshop/public/cms/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#10 /srv/users/serverpilot/apps/rebr-bookshop/public/cms/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#11 /srv/users/serverpilot/apps/rebr-bookshop/public/cms/api/core/Directus/Slim/CorsMiddleware.php(19): Slim\Middleware\MethodOverride->call()
#12 /srv/users/serverpilot/apps/rebr-bookshop/public/cms/api/core/Directus/Slim/HttpCacheMiddleware.php(18): Directus\Slim\CorsMiddleware->call()
#13 /srv/users/serverpilot/apps/rebr-bookshop/public/cms/api/core/Directus/Slim/ResponseCacheMiddleware.php(37): Directus\Slim\HttpCacheMiddleware->call()
#14 /srv/users/serverpilot/apps/rebr-bookshop/public/cms/vendor/slim/slim/Slim/Slim.php(1302): Directus\Slim\ResponseCacheMiddleware->call()
#15 /srv/users/serverpilot/apps/rebr-bookshop/public/cms/api/core/Directus/Application/Application.php(103): Slim\Slim->run()
#16 /srv/users/serverpilot/apps/rebr-bookshop/public/cms/api/api.php(534): Directus\Application\Application->run()
#17 {main}`

**Comment by WellingGuzman** [comment]
Hey @studioscholz, This bug has been fixed by https://github.com/directus/directus/commit/d758bc5082429154eeb8ef08f48503c77b2db2ad

It's going to be part of the next version (6.4.6) today, to fix this issue add a default value to your `sort` column, right now the bug is that doesn't allow null and not value is being set.
