### ISSUE TITLE
directus.request(deleteTranslations()) does not work with keys, but only with uuid

### ISSUE THREAD

**Issue by geor0014** [directus/directus#20458]
### Describe the Bug

When trying to pass an array of keys to the deleteTranslations function it will not work. You need to pass the UUID, which is auto-generated and always different. So, for example, if I want my migrate up function to create translations and my migrate down to delete them it will never work, because the UUIDs will always be different.

### To Reproduce

- Install Directus SDK
- crate a migration
- create an up function, which creates translations
- create a down function, which takes an array of translation keys and deletes them

### Directus Version

v10.8.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
This is indeed how the API functions https://docs.directus.io/reference/system/translations.html

Feel free to create a [feature request](https://github.com/directus/directus/discussions/categories/feature-requests) if you wish this to behave differently.
