### ISSUE TITLE
Padding/Theming issues after updating to 10.8.0

### ISSUE THREAD

**Issue by Natetronn** [directus/directus#20456]
### Describe the Bug

After updating to 10.8.0, myself and others are seeing some funkiness with padding and the new theming/styling.

![directus](https://github.com/directus/directus/assets/582149/a79d9001-ccf1-4e90-856e-207db00477d4)
![directus-2](https://github.com/directus/directus/assets/582149/b95871b2-bcd6-4a6c-9607-6888a6d041a8)
![directus-3](https://github.com/directus/directus/assets/582149/d0d1908f-2ccd-4682-8be6-316f6612bbad)

### To Reproduce

Update from a previous Directus (10.7.x in my case) to see the issue.

### Directus Version

v10.8.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Will be fixed by https://github.com/directus/directus/pull/20455
