### ISSUE TITLE
Small design issues since the last update

### ISSUE THREAD

**Issue by JonathanDoelan** [directus/directus#20467]
1. favicon is missing
2. unintended dark color at the data model settings ![theme-bug-1](https://github.com/directus/directus/assets/2291224/db634ffd-624d-47c5-a37b-ee8a365005bb)
3. not sure if this is intended or not, but this is a huge visual difference and relates to all fields that had this muted colors and now appear very strong ![theme-bug-2](https://github.com/directus/directus/assets/2291224/cb87e799-b546-4429-b1df-3d073f1dc16d)
4. unintended colors at modules settings ![Bildschirmfoto 2023-11-17 um 20 29 19](https://github.com/directus/directus/assets/2291224/c7555860-47ff-45c8-b4f3-830766f00078)

i’m not sure if some of the changes are intended or not.

Anyway, I love the new theming system!

**Comment by rijkvanzanten** [comment]
Thanks for the heads up! (1) I believe has since been resolved, (2) is a little visual bug that was fixed in #20842, and (3) and (4) are intentional!
