### ISSUE TITLE
Not able to install directus

### ISSUE THREAD

**Issue by udayn4** [directus/directus#2046]
Hi All,
I am new to ubuntu platform and trying to install directus on apache2. 

System info:
Ubuntu : Ubuntu 16.04.3 LTS
Apache: 2
PHP: 7.0.27-1
mySQL: 5.7.21

I am getting the following error when I try to goto install page:

Uncaught Exception: Directus\Bootstrap#appdepends on undefined constant DIRECTUS_ENV in /var/www/html/directus/api/core/Directus/Bootstrap.php:132 Stack trace: #0 /var/www/html/directus/api/core/Directus/Bootstrap.php(147): Directus\Bootstrap::requireConstants(Array, 'app') #1 [internal function]: Directus\Bootstrap::app(NULL) #2 /var/www/html/directus/api/core/Directus/Bootstrap.php(84): call_user_func('Directus\\Bootst...', NULL) #3 /var/www/html/directus/api/core/Directus/Exception/ExceptionHandler.php(74): Directus\Bootstrap::get('app') #4 [internal function]: Directus\Exception\ExceptionHandler->handleException(Object(TypeError)) #5 {main} thrown

As I am not a PHP developer, I am not able to figure this out. I have already cleared the browser cache and all the dependencies are installed. Can you please help me out?

**Comment by WellingGuzman** [comment]
Hey @udayn4,
- What directus version are you using?
- Can you check your apache/PHP logs?

This is an error that php couldn't catch because it got another error (not fund DIRECTUS_ENV)

**Comment by rijkvanzanten** [comment]
Closed due to inactivity. If anyone else experiences the same issue, please let us know and we'll reopen the issue.
