### ISSUE TITLE
Disabled extensions stays active

### ISSUE THREAD

**Issue by Seinnd** [directus/directus#20478]
### Describe the Bug

As the title already describes - even after restarting Directus, a disabled extension (doesn't matter of type) stays active:
![image](https://github.com/directus/directus/assets/22862290/33fad428-ef7b-41dd-9d1b-a37f3508fb56)
![image](https://github.com/directus/directus/assets/22862290/3db004ce-96e9-41da-803e-db4402e2041c)

### To Reproduce

just do it :-)

https://discord.com/channels/725371605378924594/741317677397704757/1176144948752551956

### Directus Version

v10.8.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Seinnd** [comment]
As further testing on my part has shown, this applies to all extensions and not just bundles.

**Comment by br41nslug** [comment]
In my tests i can reproduce this with, bundle extension and npm style extensions. Old style endpoints seem to enable/disable as expected.
