### ISSUE TITLE
Optionally Return refresh_token for SSO auth

### ISSUE THREAD

**Issue by peter-olom** [directus/directus#20476]
### The Improvement

I'm able to authenticate users using Google sign in on React Native.

For react native web everything works perfectly since I'm able to push httpOnly cookies and have my tokens refreshed.

Where I have challenges is on native. I am able to intercept the access_token but not the refresh_token. What this means essentially is that on my native apps, users are only authenticated for 15mins.

A simple fix would be to increase my access_token validity period, but I don't want to do that.

On that note, can I suggest there is an option to return **refresh_token** for sso login?

**Comment by paescuj** [comment]
Could you add some more information around your current solution?
- How does the authentication flow looks like? Specifically, this interception you mentioned
- Is this a limitation of React native?
- ...

**Comment by esonesson** [comment]
I'm also trying to make this work, but using Keycloak for SSO. 

I can use [Expo AuthSession](https://docs.expo.dev/versions/latest/sdk/auth-session/) to login with Keycloak. But then I would need to exchange the Keycloak code for an access/refresh token with Directus. Is there an endpoint I can use to do this?

Using the seamless SSO like I do on web would open the browser (external app or in app browser), and redirect to the app (deeplink). But since Directus sets a cookie in the browser I can't access that in react-native (as far as I know).

Like @peter-olom I think the best and most simple solution would be to optionally ask for the refresh token in the redirect URL. Then I can pick up that parameter, do a refresh and save in secure storage.

**Comment by peter-olom** [comment]
@esonesson You get the gist 👍🏾. I use Expo Webbrowser.openAuthSessionAsync to authenticate.

While it'll be good to have Directus optionally return the token during sso auth, I have been able to solve my problem using Directus Extensions anyway. Here is my flow:

- Implement an endpoint extension, call it anything e.g token-minter. In that token, you could do something like this: 
```typescript
import { defineEndpoint } from '@directus/extensions-sdk';

interface AuthResponse {
	access_token: string;
	refresh_token: string;
	expires: number;
}

export default defineEndpoint((router) => {
	router.get('/', async (req, res) => {
		// get the refresh token from the cookie
		const refresh_token = req.cookies["directus_refresh_token"];
		// read callback/redirect url from query (this should be to your app[native or mobile])
		const cb = req.query.cb;

		try {
			// refresh the token
			const refreshProxy = await fetch(`${process.env.PUBLIC_URL}/auth/refresh`, {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
				},
				body: JSON.stringify({ refresh_token, mode: 'json' }),
			}).then((res) => res.json());

			const { data } = refreshProxy as { data: AuthResponse };
			if (cb) {
				const redirectUrl = `${cb}?token=${data.access_token}&refreshToken=${data.refresh_token}&expiresIn=${data.expires}`;
				// redirect to the callback url
				res.redirect(redirectUrl);
			} else {
				res.json(refreshProxy);
			}
		} catch (error) {
			res.status(500).json({ error });
		}
	});
});
```
- Open sso login specifying your `token-minter` url as redirect
```typescript
// the cb query is how the token minter knows where to redirect to after successfully refreshing and grabbing and refresh token
const tokenExtractLink = `https://localhost:8055/token-minter?cb=myapp://signin`
const authLink = `https://localhost:8055/auth/login/google?redirect=${tokenExtractLink}`;

// on mobile, you can do something like this now to extract the token and save to secure storage
const handleMobileAuth = async () => {
      try {
        const res = await WebBrowser.openAuthSessionAsync(authLink);
        if (res.type === "success") {
          // extract the token from res.url
        }
      } catch (error) {
        console.log("@@@", { error });
      }
}

```
I hope this is helpful @esonesson.

If Directus won't implement this in the near future, then maybe I'll extract my exact extension and publish on github in case there are others like me who faced this challenge.

**Comment by esonesson** [comment]
@peter-olom That worked perfectly, thanks for the write up! 

Hopefully this can be integrated into Directus in the future. But until then, this works like I want it to.

**Comment by paescuj** [comment]
Hey there, thanks for your comments! You might want to submit this as a [feature request](https://github.com/directus/directus/discussions/new?category=feature-requests) if you're still interested in having this integrated in Directus.
