### ISSUE TITLE
Cannot use bullmq library for extension. __dirname is not defined

### ISSUE THREAD

**Issue by AndriyAntonenko** [directus/directus#20488]
### Describe the Bug

Hello everyone! I am trying to create a queue for my backend tasks using directus hook extension. I am trying to use bullmq for it. But when I am building the extension, it contains __dirname references. By default extension bundle is esm module. I am trying to find a workaround. I am trying to use `extension.config.js`:

```js
import nodeResolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';

export default {
  plugins: [
    nodeResolve({ exportConditions: ['node'], preferBuiltins: true }),
    commonjs({
      include: ['node_modules/bullmq/*.js', 'node_modules/bullmq/**/*.js'],
    }),
  ],
};
```

But the build still contains `__dirname` references. Can you suggest how to deal with such cases?

### To Reproduce

Create extension bundle for directus (typescript) and try to write hook with bullmq worker. It will cause this error.

```bash
__dirname is not defined in ES module scope\nThis file is being treated as an ES module because it has a '.js' file extension and '/directus/extensions/directus-extension-do/package.json' contains \"type\": \"module\". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
```

### Directus Version

10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Are you sure `@rollup/plugin-commonjs` injects `__dirname`? I think https://github.com/rollup/plugins/tree/main/packages/esm-shim is what you're looking for.

**Comment by paescuj** [comment]
I'm closing this for now, but feel free to comment if it still doesn't work. Also you might be interested in [community help](https://docs.directus.io/getting-started/support.html#community-support) in that case.

**Comment by AndriyAntonenko** [comment]
Hello! Yes, esm-shim helpend me. I have also one question, may I add something to globalThis using output.globals in `extension.config.mjs`?

**Comment by paescuj** [comment]
As of now, only `plugins` is supported in `extension.config.js`, but you should be able to modify `globalThis` via a plugin. I think https://github.com/JRJurman/rollup-plugin-polyfill looks promising.
