### ISSUE TITLE
Improve documentation for File uploads via SDK

### ISSUE THREAD

**Issue by manuinsfx** [directus/directus#20497]
### Page

https://docs.directus.io/reference/files.html#upload-a-file

### Describe the Inaccuracy

The documentation for uploading files via SDK is missing how to specify the original filename.

```js
// Would expect
formData.append('file', raw_file, 'example.txt');
// instead of
formData.append('file', raw_file);
```

Also it would be nice to include an example on how to create the raw file object from a local file, e.g.
```js
const file = new Blob([readFileSync('/path/to/example.txt')], { type: 'text/plain' });
```

**Comment by paescuj** [comment]
> The documentation for uploading files via SDK is missing how to specify the original filename.

Totally agreed 👍 

> Also it would be nice to include an example on how to create the raw file object from a local file, e.g.

The [example](https://docs.directus.io/reference/files.html#example-3) already includes that, but I also agree that we need to add the `type` property.

**Comment by br41nslug** [comment]
We probably should include a link to the FormData documentation https://developer.mozilla.org/en-US/docs/Web/API/FormData
