### ISSUE TITLE
User roles permissions ignored

### ISSUE THREAD

**Issue by anneQui** [directus/directus#20492]
### Describe the Bug

Using the /graphql/system endpoint with the query Users, a user which is not Admin cannot retrieve details about other users's role, unless the role is the same as theirs.

Role will appear as null, despite directus_roles table being set as fully readable for all user types and directus_users being similarly accessible.

### To Reproduce

**Example:**
I have created a directus 10.8.1 projet from scratch using a new PostGre database.
I have created two roles, User and Manager, and one user for each role.
For the purpose of the test, I filtered the directus_users for both roles as fully readable, with a filter on users with status "active". directus_roles are fully readable without restrictions.

Using a manager role token, querying Users return:
![image](https://github.com/directus/directus/assets/140420708/404bb470-9947-4fc4-849e-005d01dbc3a4)

### Directus Version

v10.8.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
- What are the exact users and roles permissions you have set for both roles (or just the one used for querying)?
- What is the exact request you're doing?

**Comment by anneQui** [comment]
Here are screenshots:

For the purpose of the test I set it as "open" as possible:
![image](https://github.com/directus/directus/assets/140420708/79cd4346-b84a-4491-90fb-5c8dc1b94109)
![image](https://github.com/directus/directus/assets/140420708/2db747ed-78c4-4f3c-937b-caa75668059b)
![image](https://github.com/directus/directus/assets/140420708/8e57f8a8-860f-4493-b7fe-a24afebf8f3c)
![image](https://github.com/directus/directus/assets/140420708/6c2f01ad-a0d9-458a-a9b8-a534da38aa35)
Field permissions are all checked.

I generated a manager role token and I'm using the following query:
**Endpoint:** localhost:8055/graphql/system
**Query:**
query Users {
    users {
        id
        first_name
        last_name
        role {
            id
            name
        }
    }
}

Here if more is needed :)

**Comment by br41nslug** [comment]
Did you overwrite the default roles permissions same as for the users?
![image](https://github.com/directus/directus/assets/9389634/3f9355b3-0b3a-4626-a5ea-25142a89ebce)

After defining something else than the default you should see the roles returned else it will default to only showing the current users role.

**Comment by anneQui** [comment]
@br41nslug Solved the issue, thanks

**Comment by br41nslug** [comment]
@anneQui There was also an underlying issue which has been hotfixed for 10.8.2

**Comment by anneQui** [comment]
@br41nslug noted, thanks for the tip :) I'll upgrade to 10.8.2
