### ISSUE TITLE
Upgrading from 10.6 -> 10.8 breaks

### ISSUE THREAD

**Issue by u12206050** [directus/directus#20493]
### Describe the Bug

It seems there is some missing migrations.

We are trying to run migrations but it is failing with:

```
"update `directus_users` set `appearance` = 'dark' where `theme` = 'dark' - Unknown column 'theme' in 'where clause'",
```

### To Reproduce

Update directus from 10.6.3 to 10.8.1 and run migrations.

### Directus Version

10.8.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Does the setup matter on 10.6.3? If so please elaborate on the reproduction steps required. 
I am not able to reproduce this given the reproduction instructions, i've tried creating a clean 10.6.3 instance, setting the admins preference to dark mod and updated that to 10.8.1 without errors.

**Comment by u12206050** [comment]
It seems the theme column didn't exist for some reason. SO I added it manually and it worked. Not sure when or how the theme column removed.
