### ISSUE TITLE
Setting up Directus with MySQL is not working

### ISSUE THREAD

**Issue by mhannan** [directus/directus#20538]
### Describe the Bug

Environment: `Ubuntu 22.04`
Docker Version: `24.0.7`

I am trying to install `directus` using docker but it shows MySQL related errors when I run `docker compose up`. I followed the guidelines for `.env` and `dockercompose.yml` as given here (pertaining to MySQL 8): https://github.com/directus/directus/discussions/17005

![img_v3_025j_e4bf04fb-dbcb-4d42-91ed-5e861d52ebah](https://github.com/directus/directus/assets/3625083/3d0f6b4c-306d-4e0c-b2a7-7a0841985b4c)

### To Reproduce

I run `docker compose up` with following configuration files:

### .env
    # .env
    # Docker Compose
    STACK_PRFX=directus-app

    # Directus
    KEY=secret
    SECRET=secret

    PUBLIC_URL="http://localhost:8055"

    DB_CLIENT=mysql
    DB_HOST=database
    DB_PORT=3306
    DB_DATABASE=directus_db
    DB_USER=testu
    DB_PASSWORD=1234

    CACHE_ENABLED=true
    CACHE_STORE=redis
    CACHE_REDIS=redis://cache:6379

    ADMIN_EMAIL=demo@demo.com
    ADMIN_PASSWORD=demo

    # MySQL
    MYSQL_ROOT_PASSWORD=r00tpa$$
    MYSQL_USER=${DB_USER}
    MYSQL_PASSWORD=${DB_PASSWORD}
    MYSQL_DATABASE=${DB_DATABASE}

    # MySQL image by bitnami
    MYSQL_AUTHENTICATION_PLUGIN="mysql_native_password"

### dockercompose.yml

	# docker-compose.yaml

	version: "3"

	networks:
		default:
			name: ${STACK_PRFX}

	services:
		# Database, Option 1: MySQL Version 5
		database:
			container_name: ${STACK_PRFX}-database
			image: mysql:8.0
			# Uncomment for local macOS development
			# platform: linux/amd64
			volumes:
				- ./mysql-data:/var/lib/mysql
			command:
				[
					"--character-set-server=utf8mb4",
					"--collation-server=utf8mb4_unicode_ci",
					"--default-authentication-plugin=mysql_native_password",
				]
			env_file:
				- .env

		# Cache
		cache:
			container_name: ${STACK_PRFX}-cache
			image: redis:7.0-alpine

		# Directus
		directus:
			container_name: ${STACK_PRFX}-directus
			image: directus/directus:9.22.1
			restart: unless-stopped
			ports:
				- 8055:8055
			volumes:
				- ./uploads:/directus/uploads
			depends_on:
				- cache
				- database
			env_file:
				- .env

### Directus Version

9.22.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by mhannan** [comment]
If you recommend any other way to install the `directus` do let me know please.

**Comment by br41nslug** [comment]
As the log shows the database is not done starting up when directus throws that error. Did you add a `restart: unless-stopped` as suggested in the issue you've linked?

**Comment by br41nslug** [comment]
I thought there was already an open issue for the underlying cause of the container not waiting for the database to be completely started but could not find it so i've created it now https://github.com/directus/directus/issues/20542

Considering the error shows this to be the same underlying cause im closing this issue for now in favor of #20542
