### ISSUE TITLE
User with custom permissions can't add new item to table with relation field

### ISSUE THREAD

**Issue by u12206050** [directus/directus#2054]
## Version Info
  - Directus version and branch: 1.1
  - PHP version: 7.0.27
  - MySQL version: 10.1.30-MariaDB
  - Web server: apache
  - OS name and version: CENTOS 7

## Expected Behavior
Be able to add a new item if user has correct permissions to do so even though relationship field has permission for view-only

## Actual Behavior

Error message: [Submanager] permissions only allow you to [edit] your own items.

## Steps to Reproduce
 1. Create two tables eg. A & B
 2. Create a Many-one relationship field in table A that selects an entry from table B
 3. Set group permissions for a user other than Admin, to allow viewing, adding and editing on table A, but only allow viewing table B
  4. Login as limited user, and try to create new item in table A

**Comment by rijkvanzanten** [comment]
Hey @u12206050! We're adding an additional option to the permissions in version 7.0 that makes this possible.
