### ISSUE TITLE
Deprecate extensions folder structure

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#20540]
In order to make programmatic management of extensions more stable, we gotta:

- Drop the individual type packages in extensions (eg interfaces/displays/etc)
- Require `package.json` to exist for every extension
- Drop the requirement for root extensions to start with `directus-extension-*`

```[tasklist]
### Documentation
- [ ] https://github.com/directus/directus/issues/20622
- [ ] https://github.com/directus/directus/issues/20623
```

**Comment by phazonoverload** [comment]
Yea that’s what I thought. I just want the other change made in the meantime.

**Comment by rijkvanzanten** [comment]
> Won't this fail for any pre-existing installation that has the old extension folders already on disk

It does, hence this being a breaking change! 

> How will this work for custom migrations? they are not currently an official extension type available in the new structure but they are housed in ./extensions/migrations/* 😬

Ah good one! That should definitely be supported just like the other extension types 🤔 Weird that it was excluded before..

**Comment by rijkvanzanten** [comment]
@br41nslug Ref #20625 for that second point 🙂

**Comment by nickrum** [comment]
Do we actually want to _deprecate_ the old extension folder structure first? Because this sounds and looks more like a hard removal 🧐
