### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ksraghavendra** [directus/directus#2055]
## Version Info
  - Directus version and branch: (Or commit hash) Latest
  - PHP version: 7.1.13
  - MySQL version:  4.7.7
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: Debian

Getting the following errors on the final step of installer. Using google cloud lamp stack.

## Actual Behavior

mkdir(): Permission denied

Argument 3 passed to Ruckusing\RuckusingException::__construct() must be an instance of Ruckusing\Exception or null, integer given, called in /opt/bitnami/apache2/htdocs/directus/directus/vendor/directus/migrations/lib/Ruckusing/Util/Migrator.php on line 236

Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'directus.directus_tables' doesn't exist in /opt/bitnami/apache2/htdocs/directus/directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:239 Stack trace: #0 /opt/bitnami/apache2/htdocs/directus/directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute() #1 /opt/bitnami/apache2/htdocs/directus/directus/api/core/Directus/Database/Schemas/Sources/MySQLSchema.php(87): Zend\Db\Adapter\Driver\Pdo\Statement->execute() #2 /opt/bitnami/apache2/htdocs/directus/directus/api/core/Directus/Database/SchemaManager.php(332): Directus\Database\Schemas\Sources\MySQLSchema->getTables(Array) #3 /opt/bitnami/apache2/htdocs/directus/directus/api/core/Directus/Database/TableSchema.php(869): Directus\Database\SchemaManager->getTables() #4 /opt/bitnami/apache2/htdocs/directus/directus/api/core/Directus/Bootstrap.php(472): Directus\Database\TableSchema::getTablesSchema(Array, true) #5 [intern

## Schema Dump, Logs, or Screenshots
Screenshots -
https://pasteboard.co/H7kpv4r.png
https://pasteboard.co/H7kpIFP.png
https://pasteboard.co/H7kpODe.png

Thanks in advance.

**Comment by rijkvanzanten** [comment]
Hey @ksraghavendra! Could you make sure the PHP user has the right permissions in the Directus folders? Directus is trying to create the `storage` folder, but seemingly doesn't have the right permissions to do so on the server.

**Comment by ksraghavendra** [comment]
Hey @rijkvanzanten the third screenshot shows the checklist where php has necessary permissions for 'storage/uploads' folder. The installation went through successfully after granting permission to 'storage' folder instead of 'storage/uploads'. It would help if this is indicated correctly in the pre-installation checklist. Thanks.

**Comment by rijkvanzanten** [comment]
>  It would help if this is indicated correctly in the pre-installation checklist.

You're right! The core team is currently reworking the docs for the next major version (7.0) and I'll make sure it gets added in there 👍 

Glad you figured it out!

**Comment by marcomontalbano** [comment]
Hi @rijkvanzanten I had the same issue, but in my case granting permission to `storage` folder didn't solve the issue. I had to grant `755` permission also to `customs/migrations` folder.
