### ISSUE TITLE
Editing config.php & configuration.php directly from the interface?

### ISSUE THREAD

**Issue by TechnicallyJoe** [directus/directus#2056]
## Version Info
Using 6.4 from https://hub.docker.com/r/getdirectus/directus/

Hi,

We're deploying a Directus server and have hit bit of a snafoo. I can't seem to find any way to edit the config.php & configuration.php settings from within the interface, and so deploying hooks and editing the files are.. troublesome.. to say the least in a docker/Rancher infrastructure.

What we need is simple webhooks to be fired, when a specific table has been saved/updated.

The current plan is to build a directus image, based of the one you have on docker hub, and replace the files with our own.
Is there a better way to do this? and are there plans to provide some sort of interface for editing these in the future?

Edit: updated text to be more specific

**Comment by rijkvanzanten** [comment]
Hey @TechnicallyJoe!  

We're moving most of the configuration in those two files to `directus_settings`, which makes them editable from the admin UI 🙂 

We're keeping certain API internals in those files though (like the PHP hooks). Would having http webhooks solve your issue? https://request.getdirectus.com/r/9

**Comment by TechnicallyJoe** [comment]
Hi

That woukd fix some of it, yeah.
Http webhooks with a custom header option, would satisfy our needs exactly

**Comment by TechnicallyJoe** [comment]
Any indication on, when any of the two features/changes you mentioned, will be added?

**Comment by rijkvanzanten** [comment]
We're working full time trying to get the next major version of the platform out ASAP. We're targetting for an beta release at the end of april!
