### ISSUE TITLE
CORS issues due to missing headers in preflight response

### ISSUE THREAD

**Issue by jbool24** [directus/directus#20577]
### Describe the Bug

I discovered this while vetting the Directus Community example of the Agency-OS stack for production. The preflight requests to Directus do not return the proper header `Access-Control-Allow-Origin`, which is required by most secure browsers to evaluate 
CORS policy from the server side. We currently get CORS errors if a browser client talks directly to Directus.

Example Error Response from browser:
```bash
Access to fetch at 'https://cms.{{REDACTED}}.com/auth/login' from origin 'http://{{REDACTED}}.test:3000' has been blocked by
CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present
on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with
CORS disabled.
```

***What is expected to happen?***
With CORS_ENABLED set to `true`, if CORS_ORIGIN is also set, the server should respond to requests with a header named `Access-Control-Allow-Origin` and its value should be as it was configured on the instance by the user in CORS_ORIGIN env var (or other equivalent config methods) or if CORS_ORIGIN is simply `true` it should return the exact origin as the initiating request. It's equivalent as saying `Access-Control-Allow-Origin: '*'` The latter being less secure but still valid CORS policy.

### To Reproduce

Start a fresh instance of Directus. Using any browser-based client and the Directus sdk, attempt to login with a valid user and see that the browser will complain about CORS on that request. You can also inspect the headers (or lack of) using cURL or Postman.

### Directus Version

v10.7.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by jbool24** [comment]
As a follow-up, I upgraded to v10.8.2 and re-tested some values for the `CORS_ORIGIN` policy. The only way I got this to work is by setting CORS_ORIGIN to `true`; however if the end-user wants more granular control over which client origins can talk to Directus they should be able to set the value from ENV with a list of values.

According to the [docs](https://docs.directus.io/self-hosted/config-options.html#environment-syntax-prefix) there are prefix modifiers that can be used to cast the values. So I modified the `CORS_ORIGIN` value examples listed in the OP to include these modifiers but none of those rules seem to be honored because no origin headers are matched and subsequently returned in the OPTIONS payload as expected.

**Comment by mahendraHegde** [comment]
@jbool24  i cant reproduce it in my local, may be your gateway or proxies are overriding the response headers?

#### with custom value
<img width="940" alt="Screenshot 2023-12-17 at 9 59 32 PM" src="https://github.com/directus/directus/assets/22556323/b563b760-c750-44c9-ac13-b4b74d631855">

#### with *
<img width="1009" alt="Screenshot 2023-12-17 at 9 58 36 PM" src="https://github.com/directus/directus/assets/22556323/86710aaf-3870-42fc-88be-356af4a159cf">

**Comment by jbool24** [comment]
@mahendraHegde you are using Postman which will not enforce cors in OPTIONS. But you can see the result of the missing headers at least with that. In order to experience the "issue" you must use dev tools in a browser environment to see how it will react with the pre-flight request and subsequent payload request.

**Comment by mahendraHegde** [comment]
@jbool24  i posted the screenshot for POST, but i tried OPTIONS as well,  i'm getting back the access control header in response.

**Comment by jbool24** [comment]
> @jbool24 i posted the screenshot for POST, but i tried OPTIONS as well, i'm getting back the access control header in response.

Using the same version Directus? And what browser -- are you using a Chrome or Chromium based browser to view the request in dev tools?

**Comment by mahendraHegde** [comment]
i used 10.7.0 and latest both
here's my .env for cors(for testing)
```
CORS_ENABLED=true
CORS_ORIGIN=test.com
```
and yes only browsers enforce the strictness, i was trying inspect the response header in postman.
setting `CORS_ORIGIN=true` gives back the origin and setting anything else returns the same value. 

>What is configured on a CORS activated server (Directus in this case) with Allow Origin rules should filter only the origin requests that match that hostname (or hostnames or regex patterns that are configured on the server). So this shows a bug is present even if you do see the Header.

if you mean server should validate the origin, cors is only validated by clients.

**Comment by AntonioLeutsch** [comment]
I have the same bug, calling the api with postman or server side js works like a charm, but in my case i want to implement a api call on a static site, so the request will be made by the client using the website.

I've tried multiple CORS Settings and it blocks the request 

`Access to fetch at 'https://DIRECTUS_URL/items/food?limit=15&search=ijio' from origin 'WEBSITE' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.`

**Comment by jbool24** [comment]
> i used 10.7.0 and latest both here's my .env for cors(for testing)
> ...
> and yes only browsers enforce the strictness, i was trying inspect the response header in postman. setting `CORS_ORIGIN=true` gives back the origin and setting anything else returns the same value.
> 
@mahendraHegde 
What I am describing is specific to **browser routed use-cases** and the browser client environment. I have not been seeing the origin header returned correctly in the latter. Also to note, I have set up CORS_ORIGIN with a regex array of origin URLS permitted to access. The formatting options available on Directus for CORS_ORIGIN described are [here](https://docs.directus.io/self-hosted/config-options.html#cors) with that functionality delegated to [CORS pacakge](https://www.npmjs.com/package/cors#configuration-options). With regex or regex array set, we should see the matched origin URL in the server response. I'm not seeing that. That specifically is what I mean in this ticket.


> if you mean server should validate the origin, cors is only validated by clients.

Yes. but the library will validate if the origin is in the whitelist on the sever and selectivly add it or not. That is what I'm pointing out in this issue.

**Comment by mahendraHegde** [comment]
@jbool24  can you share your env, let me reproduce

**Comment by jbool24** [comment]
@mahendraHegde What exactly are you asking to share? 

Right now, I'm working with [Directus Agency-OS](https://github.com/directus-community/agency-os) repository as a test ground for using Directus with the client SDK in the browser. This is where I surfaced the errors about CORS origin when hitting my Directus instance with CORS_ORIGIN and an Array<Regex> as its value. The reasoning for this config is Directus might provide auth and or data to multiple FE sites/apps and so many URLs should be allowed cross-origin but blacklist all other requests. Make sense?

**Comment by Drunkenpilot** [comment]
> @mahendraHegde What exactly are you asking to share?
> 
> Right now, I'm working with [Directus Agency-OS](https://github.com/directus-community/agency-os) repository as a test ground for using Directus with the client SDK in the browser. This is where I surfaced the errors about CORS origin when hitting my Directus instance with CORS_ORIGIN and an Array of Regex as its value. The reasoning for this config is Directus might provide auth and or data to multiple FE sites/apps and so many URLs should be allowed cross-origin but blacklist all other requests. Make sense?

We had the same issue when the request has been called in browser.  
After several hours search, we found an unexpected header has been sent to directus server, which is disallowed. 

I suggestion that you could check with chrome dev tool just to be sure you are not in the same situation (See the screenshot) 
![1441705589967_ pic](https://github.com/directus/directus/assets/2257567/b7bca194-4218-4a43-968f-d979aef34b94)

**Comment by jbool24** [comment]
@mahendraHegde I have a feeling there are a few issues server-side with the CORS integration. Anything outside of the example config in the docs for CORS and CORS_ORIGIN will cause issues in the browser client (meaning only `CORS_ORIGIN=true` or `CORS_ORIGIN=someStaticString`).

This could be a big security issue with modern browsers.

Hopefully one of the dev team can comment here and let us know if they can reproduce the same for this particular config use-case and also verify that the integration with CORS library is complete. Maybe offer a workaround or even tell me that I was ignorant in my understanding of this config option and what to do to fix that :wink:
