### ISSUE TITLE
Sort fields not respected in Data Studio self-hosted

### ISSUE THREAD

**Issue by krysialynne** [directus/directus#20573]
### Describe the Bug

Data Studio isn't respecting the specified sort fields on a collection.
I have several collections with an ID, name, and weight field. The weight field is an integer used for custom sorting. Here's one such collection:
![image](https://github.com/directus/directus/assets/43474151/71f5cedb-b33b-4fb5-8190-6b6e5e201635)

Although the sort field is set on the collection settings, the Data Studio app is not sorting by that field by default. Instead, it's sorting by ID:
![image](https://github.com/directus/directus/assets/43474151/6ceb820f-4b83-47e4-9740-5999ab0d5fa9)

This behavior also persists when using the collection in a Many-to-One field and selecting an option:
![image](https://github.com/directus/directus/assets/43474151/bc7c3111-82b2-4556-a93f-cf05388fd423)

Note that I had the "ID" field hidden on detail and unhid it for these screenshots to show the sort behavior - I didn't manually sort by the ID column at any point. This behavior occurs regardless of whether the custom sort field is pre-existing on the database, or if the custom sort field is created on the collection within Data Studio.

### To Reproduce

1. Create a new [self-hosted Directus instance on Docker](https://docs.directus.io/self-hosted/quickstart.html).
2. Add a collection to the data model with the following fields: ID, name (string), weight (integer).
3. Set the sort field for the collection to "weight"
4. Add some items to the collection and set the weight field so that the desired sort order for the items would not be the same as sorting them by ID.
5. View the collection data in Data Studio.

### Directus Version

v10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
You have the list explicitly sorted by ID there in the screenshots, the sort value is only used as default when no other sorting is defined.
![image](https://github.com/directus/directus/assets/9389634/fb57fd43-a868-434a-a6ab-d9d3c6bc6513)

**Comment by krysialynne** [comment]
> You have the list explicitly sorted by ID there in the screenshots, the sort value is only used as default when no other sorting is defined. Setting a default sort field does not prevent you from sorting on different fields. ![image](https://private-user-images.githubusercontent.com/9389634/286672103-fb57fd43-a868-434a-a6ab-d9d3c6bc6513.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzU2ODksIm5iZiI6MTcwMTI3NTM4OSwicGF0aCI6Ii85Mzg5NjM0LzI4NjY3MjEwMy1mYjU3ZmQ0My1hODY4LTQzNGEtYTZhYi1kOWQzYzZiYzY1MTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjlUMTYyOTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjE5NjA2NzcyZTllNDIzNTY1OTMyYjAyZTYyNDM2ZDRkMTA1NjczYmYzZWZiYzY1MTEyMWEyY2FkY2ZhNDE0ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.K0n8dW9PK5hZ4YXpgiHggXHZxEoQVT8QBnf-g318q0o)

This screenshot was taken after making the ID column visible. I did not explicitly select to sort by it.

**Comment by br41nslug** [comment]
The sorting icon there indicates the current list is sorted by ID and Ascending.

**Comment by krysialynne** [comment]
> The sorting icon there indicates the current list is sorted by ID and Ascending.

Here's another example of a collection with the same configuration. With the ID field hidden:
![image](https://github.com/directus/directus/assets/43474151/edcdc0fe-fbe0-4f49-840c-bdfd6d436cb1)

Here is the same collection after going to the collection in the data model and switching the ID field to be visible on detail:
![image](https://github.com/directus/directus/assets/43474151/0e357d0e-7526-4e31-9493-025a5a40ce09)

The sort indicator is showing on the ID column *even though I did not manually select that column to sort*. I would call that unexpected behavior, hence the bug,

**Comment by krysialynne** [comment]
Here is another example of this behavior on a newly-created collection with no items in it.
I created this collection:
![image](https://github.com/directus/directus/assets/43474151/39215069-7b8f-4d2e-8f44-d33dc684fbef)
I used the default settings for the ID field, and it defaults to be hidden on detail.

![image](https://github.com/directus/directus/assets/43474151/dad38fa2-92db-4893-b6f8-9314c7fe0e6d)
I set the sort field to "weight".

Starting from an empty collection -- so there is no possibility to manually sort the items yet -- and adding some items yields the same behavior:
![0E7C84CC-C4E4-4658-90CD-06B5E8EDA84A](https://github.com/directus/directus/assets/43474151/52ba7c11-7e5b-475f-ae96-dd5b0d0f7eda)

You can see that manual sort is toggled off once I start adding items, but they are being sorted by ID and not by the specified sort field.

**Comment by br41nslug** [comment]
> The sort indicator is showing on the ID column even though I did not manually select that column to sort.

This can be a consequence of manually adding the ID column to the preset when no explicit sort has been saved yet.

> If I use the Toggle Manual Sort button to toggle manual sort on and then back off, the correct sorting is applied.

That would indeed reset the sorting back to defined the sort field, even if that field is not part of the columns. The "correct" sorting however is the sorting field and direction indicated by the table header icons as pointed out in my first message.

> If that's not intended behavior, then manual sort shouldn't be enabled by default when a sort field is set on a collection.

Be aware that your sort field may be empty (aka all NULL's) until you actually manually sort them once or fill in the values per record.

**Comment by krysialynne** [comment]
> Be aware that your sort field may be empty (aka all NULL's) until you actually manually sort them once or fill in the values per record.

You can see in the screen recording above that this behavior occurs even when items are created in a collection with sort values specified in the sort field on creation.

**Comment by br41nslug** [comment]
Created a new concise issue for the improvement you've described (without the wall of screenshots 😬) #20574

**Comment by krysialynne** [comment]
> Created a new concise issue for the improvement you've described (without the wall of screenshots 😬) #20574

Thank you!!
