### ISSUE TITLE
Default sorting in App Layout

### ISSUE THREAD

**Issue by br41nslug** [directus/directus#20574]
### Describe the Improvement

Currently when a new layout preset is created the App will always sort this by ID. When an API sort field has been defined we should default to that with potentially the ID as second sort field.

Initial ordering:
![image](https://github.com/directus/directus/assets/9389634/06ef03e1-6504-477b-8b58-8fb56f0304be)

Expected ordering:
![image](https://github.com/directus/directus/assets/9389634/559cf1e4-29cd-4bf3-a992-8ee5af9cfc99)

**Comment by wasimTQ** [comment]
@br41nslug Can you explain how can I replicate it? I'm still pretty new to directus

**Comment by br41nslug** [comment]
> @br41nslug Can you explain how can I replicate it? I'm still pretty new to directus

Open the collection table for a collection that has the sort field configured (dont forget to delete any pre-existing presets you may have for that collection).
