### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Bamschool** [directus/directus#20582]
### Describe the Bug

I wrote `http://0.0.0.0:8055/items/korean_sentence_listview?filter[date][_gte]=2023-10-30T00:00:00&filter[date][_lt]=2023-11-29T00:00:00`
 it says
```
{
    "errors": [
        {
            "message": "Maximum call stack size exceeded",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}
```

of course, it works if I wrote `http://0.0.0.0:8055/items/korean_sentence_listview?filter[date][_gte]=2023-10-30T00:00:00` 

### To Reproduce

--

### Directus Version

10.8.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
Thanks for opening this issue! Some more information would be appreciated, for example:
- What database are you using?
- Are there a lot of items in the corresponding collection?
- What does the data model of this collection look like?

**Comment by Bamschool** [comment]
@paescuj 
thank you for answering!
i am using postgress (supabase)

Nope! it's not a lot. only 3 
if I wrote http://0.0.0.0:8055/items/korean_sentence_listview/
{
    "data": [
        {
            "id": "s1",
            "status": "published",
            "title": "오랜만이에요!",
            "englishSentence": "Long time no see!",
            "date": "2023-11-29T00:00:00",
            "topic": "Greeting"
        },
        {
            "id": "s2",
            "status": "published",
            "title": "저는 바빠요",
            "englishSentence": "I am busy",
            "date": "2023-11-28T00:00:00",
            "topic": "Greeting"
        },
        {
            "id": "s3",
            "status": "published",
            "title": "오늘 날씨가 어때요?",
            "englishSentence": "How's the weather today?",
            "date": "2023-11-30T00:00:00",
            "topic": null
        }
    ]
datamodel is  
<img width="1130" alt="스크린샷 2023-11-30 오전 9 38 50" src="https://github.com/directus/directus/assets/87596687/c84f5f8e-ef3d-4511-821e-47ea2118c536">

}

**Comment by Bamschool** [comment]
@rijkvanzanten Thank you so much. it works!
