### ISSUE TITLE
Half-width conditional fields not displayed properly

### ISSUE THREAD

**Issue by MarvinXu** [directus/directus#20583]
### Describe the Bug

Default view:
![image](https://github.com/directus/directus/assets/7382357/68be9ef1-deae-45fe-96c5-49a3dd07e977)

After toggle:
![image](https://github.com/directus/directus/assets/7382357/ce3d6857-4e3c-4fdb-bc87-65b0d5ced0fd)

### To Reproduce

1. create two half-width fields, and place them in the same line
2. set conditions to hide the first field
3. when you toggle to hide the first field, the second field doesn't fill the blank space
![image](https://github.com/directus/directus/assets/7382357/f75f0294-a68f-4b4a-a854-cce38bd3d3e1)

### Directus Version

v10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
This issue was resolved by https://github.com/directus/directus/pull/20563

**Comment by paescuj** [comment]
Unfortunately, it's not covered by #20563 as the alignment of fields has never been recalculated after condition changes.
Fix incoming!

**Comment by paescuj** [comment]
Hmm, it is on my end with the following setup:

<table><tr><td>
<img width="700" src="https://github.com/directus/directus/assets/5363448/7ea33544-4d7c-413b-85b7-e30853139d9b">
</td></tr>
<tr><td>
<img width="700" src="https://github.com/directus/directus/assets/5363448/833e8478-c0c3-4954-a21c-bfefdb4886e5">
</td></tr>
<tr><td>
<img width="700" src="https://github.com/directus/directus/assets/5363448/971f2d6a-2b8b-4c5f-8dbd-87bb88f72a67">
</td></tr></table>
