### ISSUE TITLE
"Nothing saved, nothing changed" occurs after inputting data for all required fields

### ISSUE THREAD

**Issue by mjcella** [directus/directus#2058]
## Version Info
  - Directus version and branch: 6.4.4
  - PHP version: PHP 5.6.29
  - MySQL version: 5.6.27
  - Web server: Apache
  - OS name and version: OS X El Capitan

## Expected Behavior
- It should be possible to save an item into a table after inputting data for all required fields, even if the user does not touch or modify any other fields.

## Actual Behavior
- The "Nothing saved, nothing changed" response occurs and the record does not save.

## Steps to Reproduce
1. Create a table with the following visible columns / UI elements in this order:
 - Many-to-one to external table A (required)
 - Many-to-one to external table B (required)
 - Text input (Varchar 256), not required, null default
 - Integer input (default 1), not required, null default
2. Go to the create new item page (v3/tables/table_name_here/new)
3. Connect both many-to-one UI elements to a record in their respective external tables
4. Without modifying either of the other two UI elements, click save

I'm guessing this is caused by JS validation because I see the HTTP POST is not occurring despite both required fields being filled out. If I try the same above steps but modify either of the two other non-required text inputs, the POST occurs and the item saves as expected.

**Comment by WellingGuzman** [comment]
Hey @mjcella would it be possible to share a schema that we can use to reproduce this issue?

**Comment by mjcella** [comment]
[Here's](https://drive.google.com/file/d/1-jvpq58esyiGGiUbBWZcFpWX4Um9ZBvC/view?usp=sharing) the SQL commands that I think would be necessary to create the schema that's producing this issue.

After the tables are created, add some records in the offices and elections tables. Then go to /settings/tables/races_test3, create the required assocations with an office and an election, and click save. This is returning "Nothing saved; nothing changed" for me, despite both required fields being filled out.

I can work around this issue by typing into the optional races3.description field, or changing the status from draft to published, after filling out the required fields. I'm guessing this retriggers a JS validation routine and then the save works?

**Comment by WellingGuzman** [comment]
I see what you mean @mjcella while this seems confusing, it was actually as expected. any change you make to the columns are saved immediately and doesn't require to click the save button unless you want to make a change to the other fields.

See the warning above the table:

<img width="395" alt="screen shot 2018-03-18 at 5 32 26 pm" src="https://user-images.githubusercontent.com/1531291/37571401-75918db6-2ad2-11e8-9583-f2b2a93e56a5.png">

As this won't be change in 6.x and will be implemented in 7.x, I will close this ticket.
