### ISSUE TITLE
Password Field Salt not generating

### ISSUE THREAD

**Issue by brianhyper** [directus/directus#2059]
## Version Info
  - Directus version and branch: 6.4.5
  - PHP version: 7.0
  - MySQL version: 5.7
  - Web server: Apache
  - OS name and version: Linux

## Expected Behavior

Password field should generate a salt into the salt field or use the one we wrote into the salt field to hash with the password.  We should have data into the salt field and if you wrote manually a string into the salt field and we compare the saved hash with the salt+clear_password it's not working because it didn't use any salt be we want one.

Or maybe I have miss something and the doc isn't clear at all...

## Actual Behavior

No salt generated or if we enter one in the salt field it didn't use it to hash the password.  So if you compare the hashed password with the clear_password it will work without any salt be we want one.

## Steps to Reproduce
 1. create a table or use one already existing
 2. add a password field
 3. add a salt field (of type VARCHAR, or TEXT or what ever could hold a salt string because we tried every type and nothing work...)
 4. configure the password field to use the salt field we just created
 5. create a new entry into the new table or use an existing one
 6. try to generate a password and save
 7. go see if the salt field was populated or try to hash the password with the string you wrote into the field it will not work, but if you hash with the password you just generated it will work without salt.

**Comment by WellingGuzman** [comment]
Thanks for this report. We will check the use of salt outside users, when we do a round of tickets or someone else got his hands into this.

We recently moved this interface to be used anywhere.

**Comment by rijkvanzanten** [comment]
We've reworked the complete auth flow in the next major version of the platform (7.0), so this won't be a problem anymore.

Seeing the core team is working fulltime on this next major version, we unfortunately don't have the resources to implement this for 6.x as well. If anyone wants to take a swing at it; a PR is more than welcome 😄

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/30)
