### ISSUE TITLE
Integrate the SDK into the App

### ISSUE THREAD

**Issue by br41nslug** [directus/directus#20598]
### Describe the Task

We want to support real time interactions in the app, for which we need the SDK.

**Comment by phazonoverload** [comment]
When getting this ready, please create a docs issue to document `useSDK()`.

**Comment by rijkvanzanten** [comment]
This was implemented in https://github.com/directus/directus/commit/988bc8762e1ce0848c218bcb63eb1afa10db072a 🙂
