### ISSUE TITLE
Call to a member function getCmsOwnerColumnByTable() - empty $this->acl

### ISSUE THREAD

**Issue by philleepflorence** [directus/directus#2060]
## Version Info
  - Directus version and branch: build 6.4.6
  - PHP version: 7.1
  - MySQL version: 5.6
  - Web server: Apache
  - OS name and version: macOS High Sierra 10.13.3

## Expected Behavior
When using `$tableGateway->updateRecord($recordData)`, expected result is table rows get inserted or updated.

## Actual Behavior
I am getting: 
`Call to a member function getCmsOwnerColumnByTable() on null`. 
The problem seems to be from caused by 
`$cmsOwnerColumnName = $this->acl->getCmsOwnerColumnByTable($tableName)` 
on `/api/core/Directus/Database/TableGateway/RelationalTableGateway.php:line 97`. 
`$this->acl` seems to be null!

## Steps to Reproduce
 1. Create custom api endpoint and create connection. 
 2. `$dbConnection = Bootstrap::get('zendDb');`
 3. `$tableGateway = new RelationalTableGateway($table, $dbConnection);`
 4. `$tableGateway->updateRecord($row);`

## Schema Dump, Logs, or Screenshots
```
ERROR - 2018-02-13T19:30:12-05:00 - Error: Call to a member function getCmsOwnerColumnByTable() on null in [...]/api/core/Directus/Database/TableGateway/RelationalTableGateway.php:99
Stack trace:
#0 [...]/api/core/Directus/Database/TableGateway/RelationalTableGateway.php(72): Directus\Database\TableGateway\RelationalTableGateway->manageRecordUpdate('app_icons', Array, 1)
#1 [...]/customs/endpoints/rows.php(92): Directus\Database\TableGateway\RelationalTableGateway->updateRecord(Array)
#2 [internal function]: {closure}()
#3 [...]/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#4 [...]/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#5 [...]/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#6 [...]/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#7 [...]/api/core/Directus/Slim/CorsMiddleware.php(24): Slim\Middleware\MethodOverride->call()
#8 [...]/api/core/Directus/Slim/CacheMiddleware.php(18): Directus\Slim\CorsMiddleware->call()
#9 [...]/vendor/slim/slim/Slim/Slim.php(1302): Directus\Slim\CacheMiddleware->call()
#10 [...]/api/core/Directus/Application/Application.php(103): Slim\Slim->run()
#11 [...]/api/api.php(527): Directus\Application\Application->run()
#12 {main}
```

**Comment by philleepflorence** [comment]
Seems this works:

```
$acl = Bootstrap::get('acl');
$dbConnection = Bootstrap::get('zendDb');
$tableGateway = new RelationalTableGateway($tableName, $dbConnection, $acl);
$tableGateway->updateRecord($row);
```

Seems if you are going to insert records you must include the $acl when instantiating the RelationalTableGateway since the activity table is involved as well?

**Comment by rijkvanzanten** [comment]
> Seems if you are going to insert records you must include the $acl when instantiating the RelationalTableGateway since the activity table is involved as well?

@WellingGuzman?

I'll close this for now, as (with my limited understanding of the backend stuff) I feel like you found the solution.

Excusi for the long wait 😬

**Comment by philleepflorence** [comment]
Oh sorry, yes this was resolved!
