### ISSUE TITLE
Kanban can't show value from other collection (one to many) field

### ISSUE THREAD

**Issue by nickian** [directus/directus#20617]
### Describe the Bug

I have a collection with a one-to-many field from another collection. In this case, these are many "jobs" related to a single item in the "companies" collection.

When I set the view to Kanban for the jobs, I noticed the linked Company value won't display in the "Card Content" and will only display the UUID in the title. It does not seem to respect the display template to show the company name.

Showing as "--" in card content:
<img width="320" alt="Screenshot 2023-12-02 at 9 27 41 PM" src="https://github.com/directus/directus/assets/590678/a6d1c184-8f6d-4c8e-a30e-de3f85192ad6">

Showing UUID in the title:
<img width="314" alt="Screenshot 2023-12-02 at 9 28 06 PM" src="https://github.com/directus/directus/assets/590678/ac911f4c-da3f-41f9-b799-8082c6be4618">

Shouldn't it be displaying the name value since I have this set? Or am I missing something?

<img width="850" alt="Screenshot 2023-12-02 at 9 29 13 PM" src="https://github.com/directus/directus/assets/590678/c099cbfe-a3e8-4a61-9839-23e9b7b03352">

<img width="855" alt="Screenshot 2023-12-02 at 9 29 25 PM" src="https://github.com/directus/directus/assets/590678/ed76d7d3-9a89-45a4-b9fc-5124be4f6417">

### To Reproduce

- Create a collection
- Create another collection with a one-to-many relationship to the first collection
- Set the layout to kanban and try to display the linked field in the title or card content

### Directus Version

10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by AlexGaillard** [comment]
Fixed by [https://github.com/directus/directus/pull/23538](https://github.com/directus/directus/pull/23538)
