### ISSUE TITLE
bug: `count(field)` returns string instead of number

### ISSUE THREAD

**Issue by Sandros94** [directus/directus#20615]
### Describe the Bug

Via REST API the `count(field)` returns a string.

In the following screenshot I was requesting for:
- `id`
- `name`
- `table`
- `count(answers)`
- `active`

![Screenshot 2023-11-29 162835](https://github.com/directus/directus/assets/13056429/2fa4e15b-b3f7-4801-b203-d2d6411d3102)

### To Reproduce

use `count(field)` via postman/hoppscotch/httpie

### Directus Version

v10.6.2 & v10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
I'm 85% sure that's on purpose as it's a bigInt

**Comment by br41nslug** [comment]
Aggregation functions like `count()` indeed return bigInt types hence the string response. https://www.postgresql.org/docs/15/functions-aggregate.html
