### ISSUE TITLE
Move `migrations` out of extensions

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#20626]
They aren't really an extension type, and shouldn't be documented as such. There's a new `MIGRATIONS_PATH` env var that allows them to live anywhere on the local filesystem.

**Comment by paescuj** [comment]
Related pull request for reference: #20627

**Comment by br41nslug** [comment]
Does the same apply to "Email Templates"? Which i think are not generally considered an extension type similar to Migrations. https://docs.directus.io/extensions/email-templates.html

**Comment by paescuj** [comment]
> Does the same apply to "Email Templates"? Which i think are not generally considered an extension type similar to Migrations. https://docs.directus.io/extensions/email-templates.html

Good catch! I think so!
I'm wondering if we can expect them together with migrations in the same local directory, something like:
```
ASSETS_PATH
├── email-templates
└── migrations
```

So we don't need to introduce two new config options (`MIGRATIONS_PATH`, `EMAIL_TEMPLATES_PATH`).

**Comment by br41nslug** [comment]
> I'm wondering if we can expect them together with migrations at the same local directory

I like that idea 🤔 However instead of creating 2 new edge-case/exceptions it could also be worth it to just actually make them extensions types? 🤔 Then they could be included in bundles and eventually perhaps even supported in the marketplace.

**Comment by paescuj** [comment]
>However instead of creating 2 new edge-case/exceptions it could also be worth it to just actually make them extensions types? 🤔 Then they could be included in bundles and eventually perhaps even supported in the marketplace.

Yeah, I agree that we should find a way to make them easier distributable & loadable, like extensions 👍

**Comment by rijkvanzanten** [comment]
The current migration type shouldn't be an extension type. They don't work cross database vendor, and there's no way to do any permissions or checks on them (as it's straight to knex). It's not something you should install from a third party vendor. The final package type of project ama would be an extension type though, which would solve the same use case.

Email templates are an interesting edge case. It's almost more of a theming thing rather than an extension thing 🤔

**Comment by br41nslug** [comment]
> They don't work cross database vendor, and there's no way to do any permissions or checks on them (as it's straight to knex). It's not something you should install from a third party vendor.

Not necessarily in their current state but i'd love to have an official way of adding migrations to extension bundles that require schema changes/custom tables instead of hacking around that by Hooks to do that.

**Comment by Dominic-Marcelino** [comment]
> Not necessarily in their current state but i'd love to have an official way of adding migrations to extension bundles that require schema changes/custom tables instead of hacking around that by Hooks to do that.

That‘s some of the biggest things I’m missing for more complex extensions. 
For the current state I build an dev-toolkit that allows to sync some extension-based migrations to the migration folder but that’s not a really great solution. 
An alternative to migrations could be some kind of “installed” and “updated” hooks (passing the previous and current version as parameter to check for required changes)

**Comment by rijkvanzanten** [comment]
Yeah! The tricky bit right now is that migrations rely on direct knex usage, which means they're not that transportable across instances that use different database types. It also means that there's no real way for the Directus process to check what a migration is planning on doing before executing. What we need first is a migrations format that's database agnostic and in a declarative format that'll allow Directus to run permissions checks and validation against it before executing 🙂

**Comment by Dominic-Marcelino** [comment]
>  they're not that transportable across instances that use different database types

Regarding the database agnostic part I assume that's something Durus will solve? 🤔


>  process to check what a migration is planning on doing before executing ....  to run permissions checks and validation against it

As a migration is only run by an admin (either manually or in that case via extension): What's the reason directus needs to check it / what kind of permission should it validate?
I think if somebody installs an mailicious extension it doesn't matters if the migration is mailicious too or not, as the extension itself can do the whole damage (exception of secured extensions, but this probably has to be treaten separated)

**Comment by binaryben** [comment]
> However instead of creating 2 new edge-case/exceptions it could also be worth it to just actually make them extensions types like we did for "themes"? 🤔 Then they could be included in bundles and eventually perhaps even supported in the marketplace.

Regarding emails as an edge case, I also agree they could be an extension type. I can envision extension bundles adding their own emails to send to users.

Eg: Install an eCommerce bundle from future marketplace > extension includes receipt emails

> What we need first is a migrations format that's database agnostic and in a declarative format that'll allow Directus to run permissions checks and validation against it before executing 🙂

Should we create a new extension type called something akin to 'models', 'data' or 'schema' then? An extension developer can declare what the collections should look like and let Directus figure out the migrations needed.

It would be great if an extension developer could also include Directus options like labels and icons. I have been writing two migration files for private extensions. One if platform agnostic (just the data) and the other to manually add the Directus icons and labels et al.

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/directus/pull/21718
