### ISSUE TITLE
Issues with svg preview

### ISSUE THREAD

**Issue by Tscheffrey** [directus/directus#2062]
Directus seems to try to load a JPEG preview image from the SVG.
In the focused view, the image displays correctly but it is not centered.
![image](https://user-images.githubusercontent.com/35004675/36266708-6d916136-1272-11e8-98c2-7fd24d0a5077.png)
![image](https://user-images.githubusercontent.com/35004675/36266724-76854370-1272-11e8-9e94-bb403e294e3f.png)
![image](https://user-images.githubusercontent.com/35004675/36266777-9bd32976-1272-11e8-8802-1a8789850050.png)

**Comment by DanielRuf** [comment]
relevant code: https://github.com/directus/directus/blob/de567596e4fdde0ec48ef498516ddb2455dc5e0e/api/core/Directus/Filesystem/Files.php#L468-L471

**Comment by DanielRuf** [comment]
https://github.com/directus/directus/blob/5f3acb95f4cd5b8cc15de4c1afb6aa0a0f41df31/api/core/Directus/Filesystem/Thumbnail.php#L127

**Comment by DanielRuf** [comment]
We have two options:

* Directly use the original SVG but show it smaller / rescale it using CSS.
* Or generate a png file from it
```
<?php

$usmap = 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/410.svg';
$svg = file_get_contents($usmap);

/////////////////// MODIFY THE MALFORMED SVG ///////////////////////

$dom = new DomDocument();
$dom->loadXML($svg);
foreach($dom->getElementsByTagName('image') as $image) {
    $encoded = $image->attributes->getNamedItem('href')->value;
    if(!empty($encoded)) {
        $binary = base64_decode(substr($encoded,strpos($encoded,'base64,') + 7));
        $info = getimagesizefromstring ($binary);

        $image->setAttributeNS('http://www.w3.org/1999/xlink','xlink:href','data:'.$info['mime'].';base64,' . base64_encode($binary));
    }
}

$svg = $dom->saveXML();

/////////////////// MODIFY THE MALFORMED SVG ///////////////////////

$im = new Imagick();
//$im->setBackgroundColor(new ImagickPixel('transparent'));
$im->readImageBlob($svg);
$im->setImageFormat("png32");
$im->setImageCompressionQuality(100);
$base64=base64_encode($im);
file_put_contents('image.txt', $base64);
$im->clear();
$im->destroy();
```

Code is taken from https://stackoverflow.com/a/34001825/753676

**Comment by rijkvanzanten** [comment]
Hey @DanielRuf! Thanks for the heads up 🙂 

At the moment, all core developers are working fulltime on the next major version of the platform, so I'll have to leave this open as a help-wanted. If anyone is inclined to take a swing at fixing this, a PR is very welcome 😄

**Comment by DanielRuf** [comment]
I could provide a PR.

**Comment by DanielRuf** [comment]
What approach should we choose?

> Directly use the original SVG but show it smaller / rescale it using CSS. (recommended)
> * resize svg
> * or generate a div wrapper with the needed size

> Show a fallback / default / placeholder image

> Or generate a png file from it

**Comment by WellingGuzman** [comment]
Hey @DanielRuf I believe the ideal approach will be using the thumbnail otherwise use the placeholder text. (current logic)

Using the SVG sounds like a good option, but here lies the problem that the original file (the svg) needs to be loaded and the size varies and can take longer to load, plus may not be a squared dimension.

What do you think?

**Comment by DanielRuf** [comment]
> can take longer to load

Ehm, SVG is very small in practice. Also bitmap images with many different colors are also quite big due to the compression algorithms.

> I believe the ideal approach will be using the thumbnail

There is currently no thumbnail. Generating a bitmap image from a SVG comes with several issues and drawbacks.

> plus may not be a squared dimension.

An image can be easily centered and used with object-fit. Generating a squared bitmap image from a SVG might be a bit tricky.

**Comment by benhaynes** [comment]
My opinion is that we should use the raw SVG _as_ the thumbnail (not generating a bitmap version). The SVG "thumbnail" would need to be contained/centered within the thumb dimensions (eg: 200x200) and should not exceed a max filesize (to avoid overloading the page with some crazy blueprint or something).

The only issue I can think of is: do we _copy_ the original file to the thumbs folder, or write SVG specific conditional to use the original for this mime type?

**Comment by WellingGuzman** [comment]
You are thinking about the web app only, having multiple files (listing page) can take up to loading all files slower, it can be small, but it can be huge, while is likely no matter how many colors or algorithm it uses the thumbnail (say jpg) are like to have a range or size.

Okay now to the point of using the svg directly, remember this is a xml file, we can't tell what's inside of it. can this be used as attack or break the design? can you just write script inside a svg? My suggestion is: no svg, but an actual file if it's possible.

**Comment by DanielRuf** [comment]
> My opinion is that we should use the raw SVG as the thumbnail (not generating a bitmap version). The SVG "thumbnail" would need to be contained/centered within the thumb dimensions (eg: 200x200) and should not exceed a max filesize (to avoid overloading the page with some crazy blueprint or something).

Right.

> The only issue I can think of is: do we copy the original file to the thumbs folder, or write SVG specific conditional to use the original for this mime type?

This is my current question boiled down.

**Comment by DanielRuf** [comment]
> You are thinking about the web app only, having multiple files (listing page) can take up to loading all files slower, it can be small, but it can be huge, while is likely no matter how many colors or algorithm it uses the thumbnail (say jpg) are like to have a range or size.
> 
> Okay now to the point of using the svg directly, remember this is a xml file, we can't tell what's inside of it. can this be used as attack or break the design? can you just write script inside a svg? My suggestion is: no svg, but an actual file if it's possible.

Never saw big SVG files in the wild. Illustrator, Sketch and so on are good at compressing them when they export them for web.

SVG can contain text and other things that can not be converted to bitmap images.

**Comment by benhaynes** [comment]
We store the filesize of all files in the DB, so if it's too big we can simply not return the SVG file and it would default to the type (`SVG`) instead of a thumbnail.

I'm not too worried about someone hacking code into an SVG... we have accountability, so if someone did this it could easily be tracked back to them. Remember, this is a closed-system CMS that is intended for invite-only access. Not random/public people uploading things. If it's setup to allow external uploads, then the user's project application should do sanitization and file checking.

In my experience, almost all SVGs are very small in filesize (usually smaller than a bitmap equivalent). I still vote for returning the original SVG if the filesize is less than "x".

**Comment by rijkvanzanten** [comment]
At the moment, all core developers are working fulltime on the next major version of the platform, so I'll have to leave this open as a help-wanted. If anyone is inclined to take a swing at fixing this, a PR is very welcome 😄

**Comment by DanielRuf** [comment]
I might provide a PR when I find the time but it's good to add the `help wanted` badge in general as I am focusing on Foundation Sites at the moment =)

**Comment by rijkvanzanten** [comment]
Awesome @DanielRuf!

**Comment by benhaynes** [comment]
Kamino cloned this issue to [directus/api](https://github.com/directus/api/issues/513)

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/32)
