### ISSUE TITLE
Add translations for theming strings

### ISSUE THREAD

**Issue by DanielBiegler** [directus/directus#20637]
I noticed while looking into integrating theming into the onboarding that there are some untranslated strings related to theming for example:

- "Default Appearance"
- "Default Theme Light"
- "Default Theme Dark"
- "Directus Default"
- "Directus Minimal"
- "Directus Color Match"

Edit: Dont forget the User settings too, in my naive first try they dont wanna work for some reason at the moment.(?)

**Comment by rijkvanzanten** [comment]
Keep in mind that the theme names themselves aren't translated, as they're the unique theme names 👍🏻
