### ISSUE TITLE
[SDK] Unable to resolve inferred partial field types, when using _and/_or filters in queries

### ISSUE THREAD

**Issue by sensedrive** [directus/directus#20633]
### Describe the Bug

I am using the SDK (13.0.2) with Types.

With the SDK it is possible to retrieve the types of the partial object, when explitely queriing single fields like in the example below.

```ts
const response = await this.directus.request(
      readItems('products', {
        fields: [
          'id',
          'title'
        ],
      }),
    );
```

I get

<img width="798" alt="grafik" src="https://github.com/directus/directus/assets/8351587/3b84f98a-0133-409d-a17a-a0c32e5b7bf9">

`const response: Merge<MapFlatFields<object & Product, "id" | "title", MappedFunctionFields<Collections, object & Product>>, {}>[]`

### To Reproduce

But when I additionally filter with _and/_or I get the type for the whole object back.

<img width="928" alt="grafik" src="https://github.com/directus/directus/assets/8351587/f2408656-9a60-41a2-b854-8ea92be99cb1">

`const response: Merge<MapFlatFields<object & Product, keyof Product | FunctionFields<Collections, Product>, MappedFunctionFields<Collections, object & Product>>, {}>[]`

Maybe this ticket is connected with the following issue? https://github.com/directus/directus/issues/19285

Thank you in advance

### Directus Version

v10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by sensedrive** [comment]
> What is the actual issue you're seeing? I dont directly see anything wrong with that generated type but is always hard to tell without the appropriate context.

The TypeScript issue I'm facing involves incorrect type resolution for queries. Ideally, only the queried fields should be resolved, but instead, it resolves the entire object type from the collection.

**Comment by br41nslug** [comment]
Mind sharing the important parts of the schema for reproduction too? the root and product types should do.

> Maybe this ticket is connected with the following issue? #19285

If not related to the issue it will be related to the PR as thats where these conditionals were implemented

**Comment by sensedrive** [comment]
I uploaded a test repo here https://github.com/sensedrive/directus-types-test

Filtering with or without _and makes a significant difference in the response types.

You should see an ts errror in line 16. Or I am doing something wrong ...

**Comment by adacadabrafr** [comment]
I face a similar problem.
I'm using nextjs. I see using chatGPT the problem could be in ts config : ```"moduleResolution": "bundler",```
But this is the next config and don't want to change it.

Actually what i run into is when i want to filter a readItems the filter couldn't be partial.
I mean i just want to filter by Slug like this:

```tsx
export const findServiceBySlug = async (slug: string) => {
  const service = await directus.request(
    readItems("service", {
      fields: ["*", { fimg: ["*"] }, { block_image: ["*"] }],
      filter: { slug: { _eq: slug } },
      limit: 1,
    })
  );```
  
  And ts throw this error underlining the world filter:
  ```Type '{ slug: { _eq: string; }; }' doesn't have properties of type 'QueryFilter<ISchema, IService>': id, name, subtitle, price and 8 more.ts(2740)
(property) Query<ISchema, IService>.filter?: QueryFilter<ISchema, IService> | undefined```
