### ISSUE TITLE
Realtionship field to user shows all fields

### ISSUE THREAD

**Issue by vitalijalbu** [directus/directus#20639]
### Describe the Bug

I have a collection called listings, and a field host which relates to 1 user only.
Problem is that I see all user object inside (Public access) event if i only enabled few fields from directs_users permissions:

![Screenshot 2023-12-04 alle 16 54 04](https://github.com/directus/directus/assets/40239902/44958bab-f90c-41c2-86ea-797c0f7356b9)
 
 
![Screenshot 2023-12-05 alle 11 11 08](https://github.com/directus/directus/assets/40239902/296d1484-bec0-450e-bb14-8c74e98e5a4b)

### To Reproduce

- relate a user with a field
- change directus_users fields to be showed
- see in public that nothing changes, all full user object displayed

### Directus Version

10.8.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
I have not been able to reproduce this given the provided information. Limiting the directus_user fields seems to work as expected (even though i'd recommend not exposing users to the public role).

![image](https://github.com/directus/directus/assets/9389634/60344715-e7b3-44cc-8718-c8eeaf173c12)
![image](https://github.com/directus/directus/assets/9389634/8522c17b-285b-4d71-808f-5721d5009cb8)

Closing this for now but happy to re-open if more information becomes available to reproduce this.
