### ISSUE TITLE
Frontend Syntax Error when querying unconventional named table-field

### ISSUE THREAD

**Issue by tiptronic** [directus/directus#2064]
In one of my databases there's a table-field called 'Golf & Camping' (I know - not good, but anyway...)
When I try to restrict access to such a field, I'm getting the error below:

Error
Error: Error: Syntax error, unrecognized expression: #check_Golf & Camping
File: http://directus.test/app/directus.min.js?bust=tesr2rtaufp42qidlfjghtoukj
Line:5

**Comment by rijkvanzanten** [comment]
Hey @tiptronic! Thanks for the heads up 🙂 

At the moment, all core developers are working fulltime on the next major version of the platform, so I'll have to leave this open as a help-wanted. If anyone is inclined to take a swing at fixing this, a PR is very welcome 😄

**Comment by tiptronic** [comment]
No problems... I am anyway much more curious about the Vue integration! 😊

**Comment by WellingGuzman** [comment]
Closed by 8541c39
