### ISSUE TITLE
Directus flows doesn't allow to update items witch each items having its own values

### ISSUE THREAD

**Issue by gremo** [directus/directus#20650]
### Describe the Bug

Directus flows doens't allo to update items witch each items having its own values.

### To Reproduce

1. Create a flow of type "manual trigger from a collection", in my case `bank` collection. Doesn't require a selection.
2. Create an operation of type "update collection" and use as payload:

```json
[
	{"id": 1, "name": "foo"  },
	{"id": 2, "name": "bar"  }
]
```

3. Click the flow button, items doesn't get updated

On the contrary, make the operation a "webhook" of type `POST` to `https://directus.example.com/items/bank` with the same payload. Update works!

This basically makes any trigger based on the collection update event not usable. Imagine an invoice table, with a total amount computed at the sum of every item inside the invoice. How one can update each invoice with it's unique value?

### Directus Version

v10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
The 2 calls you're comparing do not match in functionality. To update items you use `PATCH` on the API, doing `POST` creates items for you so the equivalent to that is the `Create Data` operation.

> This basically makes any trigger based on the collection update event not usable.

Bit to broad of a statement but it could make your specific usecase a little bit more difficult to implement sure.

> How one can update each invoice with it's unique value?

The updateBatch function you're referring to is not implemented in the "Update Data" operation, so you're left with three options: do the update in a loop, create a custom operation to handle it or update using the API.


Feel free to create a feature request for implementing batch update features in Flows 😄

**Comment by gremo** [comment]
@br41nslug thanks, my fault about the POST, but you are confirming that a trigger on "updates on collection" won't let us modifying multiple items each with its own unique data, at least using the flow interface, right?
