### ISSUE TITLE
Trigger on directus_files does not trigger when dropping a file.

### ISSUE THREAD

**Issue by Pachat** [directus/directus#20653]
### Describe the Bug

Trigger on `directus_files` does not trigger when dropping a file.

### To Reproduce

1. Create a flow with a trigger on item.create in directus_files
![Trigger](https://github.com/directus/directus/assets/13746133/d122a16e-2c9b-43d9-9c55-0a7495e6f20f)

3. Open library
4. Drag and drop a file (verify that directus_files has a new row)
5. Refresh the flow page => `No Logs Yet`

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
That is correct. I think you are looking for the `files.upload` event instead.
https://docs.directus.io/extensions/hooks.html#action-events
![image](https://github.com/directus/directus/assets/9389634/85dd1a4c-eb07-4e16-a1bd-8017b9d9acc5)
