### ISSUE TITLE
Add Color and Icon options to Choices for the Dropdown Interface

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#20658]
### Describe the Improvement

Our current Dropdown interface supports choices with a `Text` and `Value`. I would like to add options to _each choice_ for `Icon` and `Color` (using the existing icon interface, and color interface, respectively). The end result would be an interface that allows for this:

![CleanShot 2023-12-06 at 12 27 33](https://github.com/directus/directus/assets/522079/04cacea1-7dec-4c53-8c47-3e6c47678d96)

_Note: The interface currently supports a global icon (doesn't change), but this needs to be a per-choice icon/color._

---

## **Current Dropdown Interface**
![CleanShot 2023-12-06 at 12 15 43](https://github.com/directus/directus/assets/522079/f27169c1-8f97-4e9e-8174-7c72cedef93f)

## **Interface Choice Setup**
![CleanShot 2023-12-06 at 12 17 32](https://github.com/directus/directus/assets/522079/a5142c46-6876-45d1-9e04-609143d758c1)

## **Choices Options**
![CleanShot 2023-12-06 at 12 17 42](https://github.com/directus/directus/assets/522079/f9116b4e-a65e-4419-b4ce-9ff83f8bc178)

## **Existing Icon Interface**
![CleanShot 2023-12-06 at 12 20 02](https://github.com/directus/directus/assets/522079/d8d1866e-486b-4c10-98af-d8339b9d2014)

## **Existing COlor Interface**
![CleanShot 2023-12-06 at 12 19 55](https://github.com/directus/directus/assets/522079/014e615a-db8b-4629-809c-65df5b903f7f)

**Comment by ComfortablyCoding** [comment]
@benhaynes 

#### Questions
- Is display in scope for this change?
- Should the same changes apply to the multi select?

#### Assumptions
- The global icon should show by default (if set), any choices selected that have an icon will override it and show that icon instead.

**Comment by benhaynes** [comment]
> Is display in scope for this change?

I would _really_ like it to be, but it's not required. But unless it's a big lift, let's include it. We should discuss the difference between the `Labels` and `Formatted Value` displays, as they have quite a bit of overlap. However we plan to do this, we should clean up one or both of these displays.

> Should the same changes apply to the multi select?

Assuming you mean the `Dropdown (Multiple)` interface. Not sure, since we'd need to be careful since this one shows a checkbox to the left of each item choice. It might get complicated quickly. We can say this one's not MVP.

> The global icon should show by default (if set), any choices selected that have an icon will override it and show that icon instead.

By default, I think dropdowns **do not** use icons. They should only be added if the user configures it. The global icon was shown on the dropdown, but not in the choices, so I feel like it should be removed... but if you (and @rijkvanzanten) think it should stay and be used as a fallback for when some but not all choices have icons, then that works. But we still need a fallback for if the choice AND global are not set. In that case, let's use `check` (in our subdued gray color).

Also, we should update the `status` dropdown field (one of our default fields when creating a Collection) to use proper icons+colors.

**Comment by ComfortablyCoding** [comment]
> I would really like it to be, but it's not required. But unless it's a big lift, let's include it. We should discuss the difference between the Labels and Formatted Value displays, as they have quite a bit of overlap. However we plan to do this, we should clean up one or both of these displays.

Formatted value seems to already support this, I will add it to Label as well for consistency. Refactor/Cleanup might be best left to a separate PR.

> Assuming you mean the Dropdown (Multiple) interface. Not sure, since we'd need to be careful since this one shows a checkbox to the left of each item choice. It might get complicated quickly. We can say this one's not MVP.

Yes, I was referring to the Dropdown (Multiple). Alright, will leave that as is for now.

> By default, I think dropdowns do not use icons. They should only be added if the user configures it. The global icon was shown on the dropdown, but not in the choices, so I feel like it should be removed... but if you (and rijkvanzanten) think it should stay and be used as a fallback for when some but not all choices have icons, then that works. But we still need a fallback for if the choice AND global are not set. In that case, let's use check (in our subdued gray color).

I spoke with @rijkvanzanten and we came up with the following functionality:
- No global icon set
   - Any option without an icon (and **at least one** option has an icon set) will have left padding so it is inline with the other option text
   - An option with an icon is selected will result in the text + icon showing in the selection
- Global icon set
   - The global icon will show beside the placeholder as it does now
   - Any option without an icon (and **at least one** option has an icon set) will have the global icon beside it
   - An option with an icon is selected will result in the global icon being replaced with the option icon
 
 Misc
   - If only the color is set then a colored dot icon will show for that option (display & interface)

**Comment by benhaynes** [comment]
> Formatted value seems to already support this, I will add it to Label as well for consistency. Refactor/Cleanup might be best left to a separate PR.

Sounds good, but let's spend 15-30m together polishing up the CSS styling for everything once it's in. (vertical alignment, icon spacing, etc).

> An option with an icon is selected will result in the text + icon showing in the selection

Just to be clear, icons should be shown on the left... before the text.

The rest all looks great!!
