### ISSUE TITLE
FR: Add a button 'Deselect All/Select All' to white-/blacklisting colums

### ISSUE THREAD

**Issue by tiptronic** [directus/directus#2065]
I have a couple of tables containing 50+ columns.
To restrict access to some users (e.g. restful consumers), it would be very convenient to have an option to 'deselect all' (or 'select all') fields in the group's rights settings page. - For both: whitelisting and blacklisting.

**Comment by rijkvanzanten** [comment]
Good idea! I've moved this feature request over to our feature request tool:

https://request.getdirectus.com/r/156
