### ISSUE TITLE
Error when adding a user with duplicate email-address in the group-permission pane

### ISSUE THREAD

**Issue by tiptronic** [directus/directus#2066]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus version and branch: (Or commit hash)  6.4.6
  - PHP version:   7.2.1
  - MySQL version: 5.6.38
  - Web server: (Ex. Apache, nginx or IIS?) Apache 2.2
  - OS name and version:  MacOS X

## Actual Behavior

When adding a new user in the (group-permissions) backend manually and adding an already used email-address, I can save this user, but when I try to save the group-permissions-pane, I'm getting an type-error and it shows an <anonymous or deleted user>

Error
Error: TypeError: undefined is not an object (evaluating 'n.isParentRightPaneOpen')
File: http://directus.test/app/directus.min.js?bust=tesr2rtaufp42qidlfjghtoukj
Line:58

## Steps to Reproduce
 1. Go to global settings > group permissions
 2. Add new user and enter an already used email-address
 3. Save user (no error) and then save the group-pane -> error above

## Schema Dump, Logs, or Screenshots
Error
Error: TypeError: undefined is not an object (evaluating 'n.isParentRightPaneOpen')
File: http://directus.test/app/directus.min.js?bust=tesr2rtaufp42qidlfjghtoukj
Line:58

**Comment by rijkvanzanten** [comment]
Hey @tiptronic! Thanks for the heads up 🙂 

At the moment, all core developers are working fulltime on the next major version of the platform, so I'll have to leave this open as a help-wanted. If anyone is inclined to take a swing at fixing this, a PR is very welcome 😄

**Comment by WellingGuzman** [comment]
Hey @tiptronic I couldn't reproduce this issue.

**Comment by tiptronic** [comment]
Hi @WellingGuzman 
let me see, if I can reliably reproduce the problem. If yes, I'll let you know and provide a short video or more steps to reproduce.

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/33)
