### ISSUE TITLE
Time zone bug

### ISSUE THREAD

**Issue by abelbayon02** [directus/directus#20661]
### Describe the Bug

The value in the database is this 2023-12-06 09:59:57.659 but when i try to fetch the data using API , the result is this 2023-12-06T01:59:57.659Z

### To Reproduce

Add new collection and use the date_created field. then add data then try to fetch the data using API.

### Directus Version

10.4.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by abelbayon02** [comment]
configured in UTC , this only happens in one of my collections , only in date_created default field. other collections that handles date and time fields are all working as expected

**Comment by rijkvanzanten** [comment]
> As for only date_created resulting this format I think you need to confirm your other date/time fields, are they datetime or timestamp?

This is my suggestion as well. Sounds like you might be mixing timestamp and datetime type fields

**Comment by hanneskuettner** [comment]
Closing this as it does seem to either be resolved or not relevant any more and likely a configuration / setup related issue.
