### ISSUE TITLE
Request password API should respond with an error when something is wrong with a request

### ISSUE THREAD

**Issue by 0xJamin** [directus/directus#20674]
### Describe the Improvement

It would be great if the request reset password API could respond with an error whenever something goes wrong with the request.
At the moment, whenever a request is made to the request reset password API and an error occurs, the API responds to the request with a status code of `204` yet it throws an error at the directus backend without returning the error to the request.

### Current directus responds to a request from a frontend application that failed (request password reset):
<img width="1109" alt="Screenshot 2023-12-07 at 5 11 13 pm" src="https://github.com/directus/directus/assets/34829458/0a99f7aa-0514-4611-98f2-d6636d6aa718">

### Error thrown at the backend(directus):

```
[17:14:39] POST /auth/password/request 204 582ms
[17:14:39.249] WARN: [email] DirectusError [FORBIDDEN]: You don't have permission to access this.
    err: {
      "type": "",
      "message": "You don't have permission to access this.",
      "stack":
          DirectusError: You don't have permission to access this.
              at UsersService.requestPasswordReset (file:///directus/node_modules/.pnpm/file+api_vue@3.3.4/node_modules/@directus/api/dist/services/users.js:362:19)
              at async file:///directus/node_modules/.pnpm/file+api_vue@3.3.4/node_modules/@directus/api/dist/controllers/auth.js:123:9
      "name": "DirectusError",
      "code": "FORBIDDEN",
      "status": 403
    }

```

**Comment by paescuj** [comment]
We cannot do that for security reasons, as we would disclose information about the existence of a user.
This is a common practice. If the user is present, they receive an email, otherwise no action will be taken.

The error you're seeing on server side means the user for the given email address either does not exist or is not in active state.
