### ISSUE TITLE
Status and other translated values are not translated in csv export

### ISSUE THREAD

**Issue by ImaCrea** [directus/directus#20682]
### Describe the Bug

When exporting a set of data from a collection, values that appear translated in table view are not translated in exported csv file.

Here you can see :
![Capture d’écran 2023-12-08 à 16 40 22](https://github.com/directus/directus/assets/764332/cbccf43a-1294-41a0-a4e4-7e33a49bbdb0)

We should have them displayed in their translated version (french in our situation). Ours users can't use properly export feature because of this issue.

### To Reproduce

For example you could translated the different status possible for status field and then export and see you can't have anything but the english version.

### Directus Version

10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
The export feature purely exports the data you've stored in the database. What form of translation did you rely on? Translation fields should have their data in the database without issue.

Closing this for now as this is not an issue with the export. Happy to re-open it if more info becomes available

**Comment by ImaCrea** [comment]
Hi there @br41nslug thanks for your quick reply.

I understand your point but let me clarify our situation because we're not talking here exactly about things stored in the db but also declared in the schema. 

We have a collection with a status field, based on the dropdown component. This status has various values available, about 15 in our case. Each of them has a translation attached as Directus offer that possibility :

![status](https://github.com/directus/directus/assets/764332/d3ab2106-58bd-45d5-99e9-0e20d1536a4a)

As you can imagine, we couldn't use the translated version in our code and have set them in english with code style syntax.

But all our users are used to see theses values in their translated version in Directus and they believe this is how it's stored and frankly we can't really expect them to learn which are their english coded equivalent.

So when they export, it's normal they're expecting to see the same things they see in Directus tables. And at the moment, having the english codish style version is the source of many confusions and mistakes when working on exported data.

I believed first it's a bug because the product influence the user in that way, and asking for translations opens the expectations to have them consistent when exporting.

I hope these explanations helps clarify this ticket and eventually let you reconsider its importance.
