### ISSUE TITLE
An unexpected error occurred. Internal Server Error

### ISSUE THREAD

**Issue by bastianhilton** [directus/directus#20687]
### Describe the Bug

I'm having an issue with my graphql response. For some reason out of nowhere, Directus is giving me a 500 error when attempting to access my Directus graphql endpoint. 

{
  "errors": [
    {
      "message": "An unexpected error occurred.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

any idea on why this is happening now?

### To Reproduce

Not quite sure why this is happening so not sure how to reproduce

### Directus Version

v10.8.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
I'm afraid there's too little information to proceed with this issue, so I'll close this for now.
It would help if you'd inspect the server log around the time the error occurred.
Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻
