### ISSUE TITLE
Document ItemsService File Upload

### ISSUE THREAD

**Issue by sharkfin009** [directus/directus#20686]
### Describe the Request

This appears to be missing in the docs? all other file functionality is described. 

### Maintainence Strategy

Only when necessary

**Comment by paescuj** [comment]
Could you add a link to the corresponding page in the docs?

**Comment by br41nslug** [comment]
https://docs.directus.io/extensions/services/accessing-files.html I presume

**Comment by phazonoverload** [comment]
@estheragbaje this was omitted from the original PR because it was a bit more complex, but it is important to have. Please can we get this work lined up?
