### ISSUE TITLE
HTTPS for directus in VPS

### ISSUE THREAD

**Issue by JeremyMAQUAIRE** [directus/directus#20692]
### Describe the Bug

Hi, I have installed directus via docker and can be accessed at http://mysite.com:8055. I also install SSL and https://mysite.com also works but I can’t get it to work directus on https://mysite.com:8055. I am on VPS server with ubuntu 22, SSL works via nginx. How can I solve my problem. thank you for your help

### To Reproduce

Hi, I have installed directus via docker and can be accessed at http://mysite.com:8055. I also install SSL and https://mysite.com also works but I can’t get it to work directus on https://mysite.com:8055. I am on VPS server with ubuntu 22, SSL works via nginx. How can I solve my problem. thank you for your help

### Directus Version

v10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Discussing on Discord 👍
