### ISSUE TITLE
Security Issue - User token always valid even if the user was disable or deleted

### ISSUE THREAD

**Issue by spawnrider** [directus/directus#2070]
## Version Info
- Directus version and branch: Using Directus Docker last 6.4 version
- PHP version: 7.1.2
- MySQL version: 5.5
- Web server: Apache
- OS name and version: Windows 10

## Expected Behavior
When an user is disable / deleted,  his API access is revoked.

## Actual Behavior
For now, when an user is disable / deleted,  his API access is not revoked. His access token is alaways validated.

## Steps to Reproduce
1. Access to an API endpoint with the user token.
2. Delete an user.
1. Access to an API endpoint with the same user token.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/e76968e58305927fbd6f388a297ea80ecb0c68aa

**Comment by benhaynes** [comment]
Found, fixed, and merged in only a few hours... thank you for this one @spawnrider!
