### ISSUE TITLE
Different structure of payload in filter hook when an item is created using GraphQL.

### ISSUE THREAD

**Issue by sarthakgaur** [directus/directus#20716]
### Describe the Bug

Different structure of `payload` in `filter` hook when an item is created using GraphQL. For example, let's say there is a collection called `notes` that has 4 fields: `id`, `title`, `body` and `directus_users_id`. If we create a note through REST, we can get the `directus_users_id` like `payload.directus_users_id`. But, if we create a note through GraphQL, we have to do `payload.directus_users_id.id`. How to write `filter` hooks so they work for both REST and GraphQL? We have already written a lot of `filter` hooks that fetch data like `payload.directus_users_id`, we don't want to rewrite all of our hooks.

### To Reproduce

Refer to the "Describe the Bug" section.

### Directus Version

v10.8.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
> How to write filter hooks so they work for both REST and GraphQL?

GraphQL always enforces the extra nesting but its also possible over REST or websockets so you'll always have to double check whether `directus_users_id` is an ID or a nested object.

> We have already written a lot of filter hooks that fetch data like payload.directus_users_id, we don't want to rewrite all of our hooks.

With conventions validating/parsing the object should be a single shared function making it just a single change but you could opt to not use graphql or rest for instance
