### ISSUE TITLE
Always sort nulls last

### ISSUE THREAD

**Issue by NickCrews** [directus/directus#20723]
### Describe the Improvement

Currently, we use the default sort order: [NULLS FIRST is the default for DESC order, and NULLS LAST otherwise](https://www.postgresql.org/docs/current/queries-order.html)

Can we make it so NULLS are always last? I'm not sure the backward compatibility story here. Maybe just for in the UI, not for API requests? But that's not great for consistency? Add a config flag for this, with the default being the old behavior?

ascending:
<img width="117" alt="image" src="https://github.com/directus/directus/assets/10820686/9369eb86-0d66-4181-879c-1db63ceeaff2">

descending:
<img width="123" alt="image" src="https://github.com/directus/directus/assets/10820686/2a530392-95bb-4781-8f30-88afe66ba479">

**Comment by paescuj** [comment]
What's your motiviation for this?
I'm afraid it might be a bit unexpected if NULL values are always at the end, because you don't spot them without navigating to the last page when switching to DESC.

**Comment by NickCrews** [comment]
See https://github.com/duckdb/duckdb/pull/7174 for some context/other smart people thinking of implications

> What's your motivation for this?

- In my example I screenshotted, I want to see "zzzzz"s
- If sorting by date I want to see the latest or the earliest, not nulls
- if sorting by dollar amount I want to see largest and smallest, not nulls
- many many others

> because you don't spot them without navigating to the last page when switching to DESC

Good thought, this isn't ideal. I think it might just be the cost we have to pay though, I can't think of a way around it. Could display in the column header the number of nulls? That sounds expensive. Maybe only when you open the "sort" modal?

Maybe have 4 options in the sort modal?
- asc, nulls last
- asc, nulls first
- desc, nulls last
- desc, nulls first

**Comment by paescuj** [comment]
Thanks @NickCrews!
I think it's worth considering, e.g. adding this as an additional option. That's counts as a feature request rather than a small improvement, though.
May I ask you to fill out the [feature request form](https://github.com/directus/directus/discussions/new?category=feature-requests) so we're able to further discuss it?
Thanks again!
