### ISSUE TITLE
Cant query field compare field 

### ISSUE THREAD

**Issue by violetcrazy** [directus/directus#20729]
### Describe the Bug

Hi everyone, 
i want query product with logic : price < regular_price, how can do it
This is my data:

<img width="570" alt="image" src="https://github.com/directus/directus/assets/20683808/2696fdf2-4e5c-4a7b-ad75-783417c23fe3">

### To Reproduce

Thanks

### Directus Version

v10.7.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
This is tracked as a feature request: https://github.com/directus/directus/discussions/2993
