### ISSUE TITLE
Many to One field type with translation

### ISSUE THREAD

**Issue by tchai81** [directus/directus#2073]
Hello,

Thanks for the great software.

I have a question with regards to translation.

I have the following tables:-

| locations                       | districts    | districts_translations | languages     |
|---------------------------------|--------------|------------------------|---------------|
| id                              | id           | id                     | id            |
| district_id (Type: Many to One) | translations | name                   | language_code |
|                                 |              | district_id            |               |
|                                 |              | language_id            |               |

**Current Issue:**

On locations input UI, district field dropdown shows empty string.

**Question:**
Is it possible to setup district field on locations table in such a way that the text is retrieved from the translation table?

Thanks!

**Comment by WellingGuzman** [comment]
Hey @tchai81, I don't know what you are looking for exactly, but translations is a one to many relationships and it won't have a direct/one value relationship. Also the interface actually only fetch the first relation value, which make the value inaccesible. There's a open ticket for that. currently.

I will close it unless this result to be a bug not opened before.

We can still having this conversation or you are welcome to join us at [Slack](https://slack.getdirectus.com)

**Comment by zerbfra** [comment]
Hi @Wedjaa I have the same issue - it will be nice to provide a "default" language so in the dropdown of the related items we will see the default translation.
Otherwise it will be impossible to have dropdowns with translated entities!

**Comment by rijkvanzanten** [comment]
@zerbfra I think you tagged someone unrelated to Directus haha..

Anyway, do you mind opening a new feature request detailing exactly what you're looking for? This issue is almost 2 years old at this point and related to a way older version of Directus 🙂
