### ISSUE TITLE
Error uploading multiple files using Data Studio App: Location "local" doesn't exists

### ISSUE THREAD

**Issue by luistar15** [directus/directus#20769]
### Describe the Bug

Uploading more than one file at the same time gives an error for some files:

`[INTERNAL_SERVER_ERROR] Location "local" doesn't exists.`

https://github.com/directus/directus/assets/1296095/c80ad622-f946-47c5-9d05-7efc84cb7878

### To Reproduce

1. Clone https://github.com/luistar15/directus-test
2. docker-compose up -d
3. Drag and drop multiple files to `File library`

### Directus Version

v10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Is this repeatedly reproducible for you? I couldn't reproduce on my end.

**Comment by luistar15** [comment]
> Is this repeatedly reproducible for you? I couldn't reproduce on my end.

At least 8/9 times. I think only happens when uploading to a empty library.
I have notice the problem using S3 storage (minio), so I tried using a new installation, same problem.

I'm using Win11 Docker WSL

**Comment by br41nslug** [comment]
I was able to reproduce this once but only on the very first run for some reason 🤔 clearing the library and/or database did not get me back to that initial error to debug it

**Comment by VincentKempers** [comment]
I have experienced this myself. 

To reproduce this issue:
- You need to restart your local instance Api and APP
- Then immediately upload a bunch of files.
- Then this error will pop up immediately.

Then you will get this error here.
```
[18:48:55.209] ERROR: Location "local" doesn't exist.
    err: {
      "type": "Error",
      "message": "Location \"local\" doesn't exist.",
      "stack":
          Error: Location "local" doesn't exist.
              at StorageManager.location (file:///Users/~/projects/directus/packages/storage/dist/index.js:19:13)
              at FilesService.uploadOne (/Users/~/projects/directus/api/src/services/files.ts:66:24)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at Multipart.<anonymous> (/Users/~/projects/directus/api/src/controllers/files.ts:112:23)
      "extensions": {
        "stack":
            Error: Location "local" doesn't exist.
                at StorageManager.location (file:///Users/~/projects/directus/packages/storage/dist/index.js:19:13)
                at FilesService.uploadOne (/Users/~/projects/directus/api/src/services/files.ts:66:24)
                at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                at Multipart.<anonymous> (/Users/~/projects/directus/api/src/controllers/files.ts:112:23)
      }
    }
```

I believe it's an concurrency problem here in [`api/src/storage/index.ts`](https://github.com/directus/directus/blob/main/api/src/storage/index.ts).
When uploading a bunch of files in a fresh start, there isn't a `_cache.storage`. When going to the code it will set an empty `storageManager` and await for the driver and location. But the `uploadOne` is already triggering the getStorage for the next files and will trigger the error.

**Comment by VincentKempers** [comment]
Just to add more information here about debugging this:

So I noticed this happens when this is happening every time the project is initialised. This also happened when getting an assets. 
```
{"type":"Error","message":"Location \"storage\" doesn't exist.","stack":"Error: Location \"storage\" doesn't exist.\n    at StorageManager.location (file:///directus/node_modules/.pnpm/file+packages+storage/node_modules/@directus/storage/dist/index.js:19:13)\n    at AssetsService.getAsset (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.9_pinia@2.1.7_typescript@5.3.3_vue@3.3.13/node_modules/@directus/api/dist/services/assets.js:46:38)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.9_pinia@2.1.7_typescript@5.3.3_vue@3.3.13/node_modules/@directus/api/dist/controllers/assets.js:152:36"},"msg":"Location \"storage\" doesn't exist."}
```
