### ISSUE TITLE
Help needed: Load external javascript libraries for a custom interface

### ISSUE THREAD

**Issue by ca057** [directus/directus#2077]
Hello!
I need some short help: My goal is to create a custom interface, where I need to load an external javascript library. Writing the actual interface is pretty straight forward, but I'm currently lacking on the best way to load and integrate my external library.

My current thoughts include: 
* Is there a place in the build process where I can place my compiled (& minified for production) file
* Does it make more sense to add it as a fixed dependency to the package.json?

In the best case I would like to leave a minimal footprint, so keeping my setup up to date isn't too hard.

Thanks in advance!

**Comment by rijkvanzanten** [comment]
Hey @ca057! It regrets me to say that there isn't a "good" way to actually do this as far as I'm concerned in 6.x. We've redesigned the way extensions / interfaces work for the upcoming 7.0 to use a `package.json` / `npm`.

The "best" way for now would be to include the dependency as a file in a `vendor` folder and adding it in your interface by importing it with `requirejs`

**Comment by ca057** [comment]
Thanks for the help - till 7.0 is out I can do it the not so good way ;-)
