### ISSUE TITLE
Next.js guides need updating for v14

### ISSUE THREAD

**Issue by phazonoverload** [directus/directus#20778]
### Page

/guides/headless-cms/build-static-website/next-13

### Describe the Inaccuracy

Been a report that, while this page specifies Next 13, it no longer works correctly with the latest stable Next 14. 

> Creating pages section does not work on app router

Can we please audit and update these docs pages?

**Comment by phazonoverload** [comment]
Ok I opened this based on feedback - willing to accept it was some other issue. Let's just rename the titles to show Next 14 and close it out with minimal effort.

**Comment by estheragbaje** [comment]
Alright, will do
