### ISSUE TITLE
Creating a new folder yields `Validation failed for field "name". Value is required` error

### ISSUE THREAD

**Issue by marcules** [directus/directus#20781]
### Describe the Bug

When I try to create a folder through either UI or API I get the following error:

```json
{
  "errors": [
    {
      "message": "Validation failed for field \"name\". Value is required.",
      "extensions": {
        "code": "FAILED_VALIDATION",
        "field": "name",
        "type": "required"
      }
    }
  ]
}
```

In the UI it just displays the error:
![MicrosoftTeams-image](https://github.com/directus/directus/assets/2453108/f1f32088-7073-4804-9bdf-ccc01b17ad66)
(clicking the copy-error button the message is like the one pasted above)

With the API the same error is returned as well:
```sh
cat <<EOF | curl -sS -XPOST -H "Authorization: Bearer $BEARER" -H 'Content-Type: application/json' --data-binary @- https://myapp.directus.app/folders | jq '.'
{"name":"t1"}
EOF
```

![MicrosoftTeams-image (1)](https://github.com/directus/directus/assets/2453108/d9c85e33-3a98-40bb-969c-93d25c7040cd)

---

I'm using the directus cloud offering and we also already have some folders created although they are older. I'm using an admin account, so I suppose this should not be a permissions issue.

According to the documentation the POST payload should be correct: https://docs.directus.io/reference/system/folders.html#example-2

I have also tried wrapping it in `{"data": {"name": "t1"}}` and with the 'multi folder creation' like `[{"name": "t1"}]` on the same endpoint `/folders` with the same error response.

If you need more info please feel free to reach out.
Kind Regards,
Marc

### To Reproduce

1. Login to the Directus Cloud Management UI
2. Navigate to the `File Library`
3. In the main File Library folder hierarchy click on the `Create Folder` button on the top right side
4. Type in any name
5. Click on `Save`

![MicrosoftTeams-image (2)](https://github.com/directus/directus/assets/2453108/043beb68-c958-49a4-bfda-96edabc3545e)

### Directus Version

v10.8.2

### Hosting Strategy

Directus Cloud

**Comment by br41nslug** [comment]
I was unable to reproduce this with the given instructions.

Do you have any extensions/flows that could be interfering here?

**Comment by marcules** [comment]
Hi @br41nslug - there are no extensions installed (I was unaware that this is possible for cloud-hosted) but you are right, there is a flow, that is configured for the `items.create` scope with `Data of Last Operation` for the `directus_folders` collection.

When I disable that flow, I can create new folders just fine.

Sorry for the trouble there seems to be some kind of issue with the flow itself.
