### ISSUE TITLE
SAML does not work when identifier attribute appears multiple times

### ISSUE THREAD

**Issue by joselcvarela** [directus/directus#20804]
### Describe the Bug

Not sure if this is specific to Shibboleth SAML or not, but we are experiencing the following issue:
We are not being able to login via SAML because the identifier key appears twice in response. For example:
```xml
<saml2:AttributeStatement>
  <saml2:Attribute
    FriendlyName="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
    Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
    NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
  >
    <saml2:AttributeValue>hello@example.com</saml2:AttributeValue>
  </saml2:Attribute>
  <saml2:Attribute
    FriendlyName="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
    Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
    NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
  >
    <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:type="xsd:string"
    >hello@example.com</saml2:AttributeValue>
  </saml2:Attribute>
</saml2:AttributeStatement>
```

The error on logs is:
```
...
{"type":"TypeError","message":"identifier.toLowerCase is not a function","stack":"TypeError: identifier.toLowerCase is not a function\n
  at SAMLAuthDriver.fetchUserID
  at SAMLAuthDriver.getUserID
  at AuthenticationService.login
...
```

This means that `samlify` package will return this attribute as an array with both values instead of a string. This value is put into `identifier`:
https://github.com/directus/directus/blob/dd3de6bda6b5c310bc9127c6faa0ab2373b11e69/api/src/auth/drivers/saml.ts#L53

Then Directus is trying to call `identifier.toLowerCase()` multiple times, but value is an array.

I am not aware of the SAML specification, but here's what I think the solutions could be:
- always use index 0
- check if all values in array are the same and throw error if not
- add configuration to decide what index should be used

### To Reproduce

Login with SAML which defines same attribute twice

### Directus Version

main

### Hosting Strategy

Directus Cloud

**Comment by paescuj** [comment]
In the case above, the fact that two different `NameFormat`'s are given for the same resource seems to indicate to me that there is actually a misconfiguration on the part of the IdP. This can apparently happen after an update of Shibboleth. See https://www.unicon.net/insights/articles/shibboleth-idp-understanding-the-attribute-registry, under "My SAML responses suddenly have duplicate attributes in them, why is that?".

I don't know myself whether duplicate attributes are actually allowed resp. intended.
But it certainly seems to occur in the wild: https://www.google.com/search?q=saml+duplicate+attributes
And the fact that it passes the schema validator indicates that it is possible:
https://github.com/directus/directus/blob/dd3de6bda6b5c310bc9127c6faa0ab2373b11e69/api/src/auth/drivers/saml.ts#L21
On that note, it would be interesting to run the complete SAML response from above through a validator like https://www.samltool.com/validate_xml.php.

---

Should we decide to handle duplicate attributes on our side, I think we should consider these decisions from two other SAML libraries:

https://github.com/SAML-Toolkits/python3-saml/issues/39#issuecomment-262013022:
> On [v1.2.0](https://github.com/onelogin/python3-saml/releases/tag/v1.2.0) we avoid the use of multiple saml:Attribute values with the same name,
that was a recommendation from an external security audit.

Therefore, it's probably a good idea to make it opt-in like in
https://github.com/SAML-Toolkits/php-saml/commit/370a5d9c8432ede5776f278edcdcf3b8e8212cc6.

**Comment by joselcvarela** [comment]
Thank you @paescuj 
That's right. It looks like we should not have duplicated attributes anyway.
I just thought it was a standard since `samlify` can handle that gracefully.
We were able to remove the duplicated attribute so going to close it.
