### ISSUE TITLE
When selecting an item for M2M type that has reference to another table, I would expect to see the related table field in Twig format as defined in column settings, instead it shows just an ID.

### ISSUE THREAD

**Issue by lokers** [directus/directus#2080]
## Version Info
  - Directus version and branch: 6.4.4
  - PHP version: 7.2.2
  - MySQL version: Ver 14.14 Distrib 5.7.21, for osx10.13 (x86_64)
  - Web server: Apache
  - OS name and version: macOS High Sierra 10.13.2

## Expected Behavior
When selecting an item for M2M type that has reference to another table, I would expect to see the related table field in Twig format as defined in column settings, instead it shows just an ID.

## Actual Behavior
When I view existing row, I only see `{{id}}`, then when I click to add new, I see correct format I defined in Twig format, or when I click on existing it swaps again from `{{id}}` to current defined format. It looks like when the initial pull for fields is made, it doesn't extend the info the same way when new row is added, because then the id becomes extended with Twig format. (Look at the last screenshot)

## Steps to Reproduce
 1. Create a table with fields: `id`, `title`, `subcategory_id`
 2. `subcategory_id`, will be `many-to-one` type field with interface options as:
- visible columns: `id,title`
- twig column template: `{{id}}: {{title}}`
 3. Create another table with fields: `id`, `title`, `profiles`
 4. `profiles` will be `many-to-many` type field with interface options as:
- visible columns: `id,title,subcategory_id`
- twig column template: `{{id}}: {{title}}`
 5. Go and try to add new row and watch the m2m field, specifically the `subcategory_id` column. 

## Schema Dump, Logs, or Screenshots
<img width="625" alt="screen shot 2018-02-26 at 09 16 03" src="https://user-images.githubusercontent.com/1701781/36660427-6492a91e-1ad8-11e8-8724-4ae6673780c6.png">
<img width="625" alt="screen shot 2018-02-26 at 09 16 12" src="https://user-images.githubusercontent.com/1701781/36660426-64710372-1ad8-11e8-9295-6616e49b5319.png">
<img width="626" alt="screen shot 2018-02-26 at 09 18 16" src="https://user-images.githubusercontent.com/1701781/36660425-644e002a-1ad8-11e8-8fde-40f42f869c44.png">
<img width="622" alt="screen shot 2018-02-26 at 09 18 35" src="https://user-images.githubusercontent.com/1701781/36660424-641fbac6-1ad8-11e8-9040-52bda3a32163.png">
<img width="853" alt="screen shot 2018-02-26 at 09 21 30" src="https://user-images.githubusercontent.com/1701781/36660423-6402f56c-1ad8-11e8-94c6-2cd0c670e24f.png">

**Comment by treechime** [comment]
It displays correctly when you edit an existing row and save as well (with or without making a change), not just adding a new row. It's happening to me with a single file interface.

**Comment by lokers** [comment]
guys, any hint how to fix this? I can give it a go, but would be nice if someone can point me into the right direction to speed things up...

**Comment by rijkvanzanten** [comment]
@WellingGuzman any pointers for @lokers?

**Comment by treechime** [comment]
I've really hackily patched this for an image field by adding `if(data.file) data.file = '<div class="media-thumb"><img src="'+ directusPath +'/storage/uploads/thumbs/'+ data.file +'.jpg" class="img landscape"></div>'; //where file is column name` to line 30 of `EntriesJunctionCollection.js`

You could do something similar for a different field by doing an ajax api call, but I'm not sure how you'd handle it with async and returning the values.

Hopefully won't be an issue in the upcoming release :)

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/34)

**Comment by chrisphua-pxs** [comment]
> @wellingguzman any pointers for @lokers?

Hi i know its old issue. Is there any workable fix for this? I really appreciate someone could point me to the right direction.

Tks & best regards.

**Comment by benhaynes** [comment]
@bjgajjar — any thoughts?

**Comment by rijkvanzanten** [comment]
There's no known workaround. I suggest upgrading to Directus 8. V6 is no longer supporter nor maintained.

**Comment by chrisphua-pxs** [comment]
Alright, thanks all! Really appreciate the replies!
