### ISSUE TITLE
Add deprecation notice in docs for useApi

### ISSUE THREAD

**Issue by br41nslug** [directus/directus#20808]
While the transition from `axios` to `SDK` is in progress we want to mark the existing `useApi` composable as deprecated in the documentation. This composable will not actually be removed until after the transition has been completed.

**Comment by paescuj** [comment]
Actually, we can incorporate this into #20684 right away 👍

**Comment by phazonoverload** [comment]
We can, but we won't 😅 We'll document deprecation when it happens (or when there's a viable alternative - whichever happens first)

**Comment by phazonoverload** [comment]
Added this as a note on #20813 and will close this as a dupe
