### ISSUE TITLE
Page blocks go out of order when a second tab is created. 

### ISSUE THREAD

**Issue by MattatDirectus** [directus/directus#20815]
### Describe the Bug

When enough blocks are created to create a tab for a second page, it knocks the blocks out of order. But the live preview looks correct despite the blocks being out-of-order until a block is moved. 

![image](https://github.com/directus/directus/assets/118303535/668bab2e-361a-44e6-9052-5d83c4651b3b)

![CleanShot 2023-12-20 at 08 42 46](https://github.com/directus/directus/assets/118303535/b9b038c7-481b-40f4-9a53-0283829757c6)

### To Reproduce

Create enough page blocks to create a second tab within the page editor.

### Directus Version

v10.8.2

### Hosting Strategy

Directus Cloud

**Comment by DanielBiegler** [comment]
Mhh I seem to be unable to reproduce this on the currrent main-branch. I made some blocks from 1-9, reduced the pagination to 3 items per page and added the blocks to the M2A relation in the following order:

```
1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3
```

Everything seems to stay in order correctly both with the live preview and without the live preview.

[Screencast from 27.12.2023 12:49:38.webm](https://github.com/directus/directus/assets/14810858/ee8877b1-c7b9-4aa4-909d-6a588d0f02dd)

Mhhh are there more steps needed to reproduce this or does this happen all the time for you? :frowning:
