### ISSUE TITLE
Add documentation for useSdk and deprecate useApi

### ISSUE THREAD

**Issue by br41nslug** [directus/directus#20813]
With the addition of the `useSdk` composable (in #20811) we'll need to document it just like the `useApi` (like the related https://github.com/directus/directus/issues/20606)

While the transition from axios to SDK is in progress we want to mark the existing useApi composable as deprecated in the documentation. This composable will not actually be removed until after the transition has been completed.

**Comment by phazonoverload** [comment]
When is this expected to be available? If you could also provide some rough snippets we can take them away and document off them

**Comment by br41nslug** [comment]
When the first two PR's of this migration are merged (adding useSDK and authentication) this will be usable. Dont have any usage examples as of yet.

**Comment by kevincam3** [comment]
I think the "Add documentation for useSdk" part of this is covered by this PR. https://github.com/directus/directus/pull/20684

**Comment by phazonoverload** [comment]
It is not - that docs page uses useApi

**Comment by kevincam3** [comment]
Got it. So is the idea just to add a useSdk() section for the new useSdk() composables that was added to the @directus/composables package along with an example of how to use it like the other composables on this page have?

https://docs.directus.io/extensions/app-composables.html

**Comment by phazonoverload** [comment]
Yeah you got it - it's a docs thing encouraging use of useSdk

**Comment by br41nslug** [comment]
To be reconsidered later
