### ISSUE TITLE
6.4.7 installation issue

### ISSUE THREAD

**Issue by pawlisiak** [directus/directus#2081]
## Version Info
  - Directus version and branch: 6.4.7 / master
  - PHP version: 7.0
  - MySQL version: 5.6.35
  - Web server: Apache

## Actual Behavior
After installation there is some kind of warning on step 4 (//host/installation/index.php?step=4).

## Steps to Reproduce
 1. Clone the repo
 2. Install composer dependecies
 3. Run installation
 4. Fill all forms with valid database data

## Schema Dump, Logs, or Screenshots

{
  "success":false,
  "error":{
    "message":"Unexpected character \"#\"."
  },
  "code":0,
  "class":"Twig_Error_Syntax",
  "file":"\/Users\/pawlisiak\/Localhost\/~fp\/partners\/public_html\/directus2\/api\/views\/mail\/base.twig",
  "line":31
}

**Comment by spee** [comment]
I just had this same issue. The unexpected character seems to be introduced here: https://github.com/directus/directus/commit/a86e78eaadd7c06c13d849979035f119f1ed7a45#diff-36b0ca5a7194f4fb4cfc3cbeb6647452R31

**Comment by rijkvanzanten** [comment]
Looks like Twig is trying to parse the Handlebars template..? @WellingGuzman

**Comment by WellingGuzman** [comment]
Thanks @pawlisiak for the report and @spee for pointing it out.

It was actually a handlebars `condition` instead of a twig's.

Closed by e4b4da6
