### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by staminna** [directus/directus#20819]
### Describe the Bug

I have two collection and a O2M relationship.

### To Reproduce

Create 2 collections, make a O2M with a foreign integer auto increment field on collection 2, make it a child of collection 1.
Create a new item on collection 1, add a new item on collection 2 and save. 
error message:Cannot convert undefined or null to object

### Directus Version

v10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
> make a O2M with a foreign integer auto increment field on collection 2

How exactly do you mean "auto increment"? the foreign key needs to be writable and thus cannot be a primaryKey so auto increment does not apply/work here.

The current reproduction steps are unfortunately not enough for me to recreate the error situation. Happy to re-open the issue when more information becomes available 😄
