### ISSUE TITLE
6.4.7 Add user issue

### ISSUE THREAD

**Issue by pawlisiak** [directus/directus#2082]
## Version Info
  - Directus version and branch (Or commit hash): 6.4.7
  - PHP version: 7.0
  - MySQL version: 5.6
  - Web server: Apache

## Expected Behavior
Clear instalation (with issue from #2081) - click on "add user" button should open the window to fill user data.

## Actual Behavior
There is red notification.

## Schema Dump, Logs, or Screenshots
Error
Error: Uncaught TypeError: Cannot read property 'data' of undefined
File: https://partners.loc/directus2/app/router.js?bust=7d6d883986704dd116e9aae94b15c47a53a4d9dd
Line:647

**Comment by WellingGuzman** [comment]
Thanks @pawlisiak for reporting this, it was been fixed by 51f8cbc. It will be release later today on `6.4.8`
