### ISSUE TITLE
Group is not set when you disable a user

### ISSUE THREAD

**Issue by spawnrider** [directus/directus#2083]
## Version Info
- Directus version and branch: Using Directus Docker 6.4 version
- PHP version: 7.1.2
- MySQL version: 5.5
- Web server: Apache
- OS name and version: Windows 10

## Expected Behavior
Disable an specific user by : 
- Select "Inactive" value
- Click "Save" button
- Return to the previous screen (user list or group screen) without any issue

## Actual Behavior
When you click on the save button, an error occures : 
> There seems to be a problem...
Users (XX)
Group: This field is required

## Steps to Reproduce
 Disable an specific user by : 
 1. Select "Inactive" value
 2. Click "Save" button

See issue in live: 
![issue_directus](https://user-images.githubusercontent.com/107427/36725941-3e9695b4-1bb8-11e8-913e-e8bf05f4a58b.png)

**Comment by rijkvanzanten** [comment]
This error comes from the API directly, meaning that we can fix it by either sending over the `group` on this save as well from the app, or using a `PATCH` request to save just the `status` change. The second is cleaner (and what we'll be doing in 7.0), but is probably way harder to implement in 6.x..

**Comment by spawnrider** [comment]
This is actually the case, a PATCH request is fired with `{status: 2}`
IMHO, it's not an API issue but an local validation issue because the Group is not correctly set....

**Comment by rijkvanzanten** [comment]
Oh! That opens up perspectives.. The user edit view uses a regular edit view, so either the interface that is used doesn't call the 'value changed' code or the value is set to nothing

**Comment by rijkvanzanten** [comment]
At the moment, all core developers are working fulltime on the next major version of the platform, so I'll have to leave this open as a help-wanted. If anyone is inclined to take a swing at fixing this, a PR is very welcome 😄

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/35)
