### ISSUE TITLE
Unable to select 'User' in User Interface type after an table import

### ISSUE THREAD

**Issue by spawnrider** [directus/directus#2084]
## Version Info
- Directus version and branch: Using Directus Docker 6.4 version
- PHP version: 7.1.2
- MySQL version: 5.5
- Web server: Apache
- OS name and version: Windows 10

## Expected Behavior
I imported an table from another environment. 
I want to manage it on Directus. 
This table contains a column of type INT(11). 
This column was of "User" User interface type on the source environment.
It would be also of "User" type on this environment. 

## Actual Behavior
On this environment, the type is NUMERIC and cannot be switch back to "User".

## Steps to Reproduce
 1. Create a table with "User" field of type "User" on an environment
 2. Copy this table using SQL / PhpMyAdmin to another environment
 3. Manage this table on this new environment.
 4. The "User" field is now of type "NUMERIC" and not "User". 

## Schema Dump, Logs, or Screenshots
![directus_user_issue](https://user-images.githubusercontent.com/107427/36726454-1ed3baf2-1bba-11e8-9a34-d4155e10070b.png)

**Comment by rijkvanzanten** [comment]
Good catch!

**Comment by rijkvanzanten** [comment]
The interface should ideally be a relational one. The user interface as is uses `INT` as datatype, so there must be some other magic going on why it's not showing up..

**Comment by spawnrider** [comment]
**A temporary workaround  :** 
I am using a many to one association with the **directus_user** table and set this for the **Visible Column Template** : 
`<a href="/users/{{id}}">{{first_name}} {{last_name}} {{id}}</a>` 

By doing this, you can click the item field to be redirected to the linked user but you cannot see his picture.

**Comment by rijkvanzanten** [comment]
At the moment, all core developers are working fulltime on the next major version of the platform, so I'll have to leave this open as a help-wanted. If anyone is inclined to take a swing at fixing this, a PR is very welcome 😄

In 7.0, the user interface is being rebuild from the ground up. We'll make sure this issue doesn't happen in the new version 👍

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/36)
