### ISSUE TITLE
not Permittion using Using fields/{collection} 

### ISSUE THREAD

**Issue by NewIdeaSrls** [directus/directus#20855]
### Describe the Bug

I am trying, using your internal API to create with nodejs (axios), new collections e also define the fields of collection trought api call {{urlDirectus}}/fields/{{collection}} , the collection that i have create work perfectly, but during the creation of fields , i have back an error , that i havent the permission to do it,  i am the administrator, i give back token correctly but , the creation of fileds give me this error, can you help me ? with example if its possible.

const fieldData = {
      field: "id",
      type: "integer",
    };

    // Imposta l'header Authorization con il token Bearer
    const config = {
      headers: { Authorization: `Bearer ${token}` },
    };

    let collection = "Users"
    const response = await axios.post(
      `${DIRECTUS_API_URL}/fields/${collection}`,
      fieldData,
      config
    );

In advance , best regards.

### To Reproduce

const fieldData = {
      field: "id",
      type: "integer",
    };

    // Imposta l'header Authorization con il token Bearer
    const config = {
      headers: { Authorization: `Bearer ${token}` },
    };

    let collection = "Users"
    const response = await axios.post(
      `${DIRECTUS_API_URL}/fields/${collection}`,
      fieldData,
      config
    );

### Directus Version

v10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
I am not able to reproduce it using the given instructions, the field gets created without issue.
Make sure the fields data is correct and no typo's in the collection. Forbidden does not only cover permission errors.
