### ISSUE TITLE
Error invite user

### ISSUE THREAD

**Issue by ducdao-cdh** [directus/directus#20878]
### Describe the Bug

I'm inviting a user by email and this error occurs. This error may be in the edited inviteUser function. I don't have this problem with version 10.8.2

```
TypeError: Cannot read properties of undefined (reading 'email')
      at UsersService.inviteUser (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.9_pinia@2.1.7_typescript@5.3.3_vue@3.3.13/node_modules/@directus/api/dist/services/users.js:328:30)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
<img width="1009" alt="image" src="https://github.com/directus/directus/assets/145431773/61169b76-8beb-4b5d-9c77-0a326e8c87a9">
The error occurred at line 399

### To Reproduce

Use the inviteUser function of UsersService

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by joselcvarela** [comment]
@paescuj should this be in "Next Release" milestone?

**Comment by paescuj** [comment]
> @paescuj should this be in "Next Release" milestone?

Yeah, the associated pull request (#20878) is in the "Next Release" milestone 👍
