### ISSUE TITLE
Collections sort field disappears after save

### ISSUE THREAD

**Issue by aclisp** [directus/directus#20871]
### Describe the Bug

See below reproduce steps.

### To Reproduce

1. Create a new collection
2. Select `Sort` as an Optional Field
3. Save

The `Sort` field is not automatically selected for Sort Field, but in previous releases it is.

4. Enter the collection's data model setting page, select `Sort` as Sort Field
5. Save
6. Enter the collection's data model setting page again!

The Sort Field is empty. It can not remember what is selected before.

### Directus Version

v10.8.3 

### Hosting Strategy

Self-Hosted (Custom)

**Comment by aclisp** [comment]
Just find the Archive Field has the same problem.

**Comment by aclisp** [comment]
Hi, I setup the project in dev mode, did some digging and finally have some findings.

I believe it is caused by this code in interface `system-field`

https://github.com/directus/directus/blob/54d8152c7259f36a8188c7d9999293f9512e77ab/app/src/interfaces/_system/system-field/system-field.vue#L42-L47

Enter the collection's data model page, the debugger stops here, which shows `oldCol = undefined`. But it still emits the `input` event, changing the field‘s value to null.

Note: `expenses` is a collection whose archive_field="status" and sort_field="sort" 

![image](https://github.com/directus/directus/assets/5406765/eb567480-1c02-4de5-9938-8b7031a290e5)

So why we need to reset value whenever the chosen collection changes? It reminds me the issue #19417 that is still not resolved reasonably by #20562.

Actually when you follow o2m/m2m alias field to another model, the vue component `./routes/data-model/fields/fields.vue` is   rendered with a new collection. Here `child` has a m2o field to `parent`, and we are just entering `parent`'s model from `child`'s.

![image](https://github.com/directus/directus/assets/5406765/834bc199-8cb8-4f96-b1b4-260ce2cbdee9)

So `parent`'s Archive Field and Sort Field is reset, and boolean `hasEdits` becomes true, turning the page to modified state.

I think we should remove the watch in `system-field.vue`. Both this issue and #19417 could be fixed.

**Comment by br41nslug** [comment]
This looks to be very much related to the https://github.com/directus/directus/issues/19417 issue where traversing a relation in the data-model page will clear the sort/archive fields for a collection 🤔 not yet marking it as duplicate but may have the same underlying cause
