### ISSUE TITLE
How to implement storage adapters other than S3

### ISSUE THREAD

**Issue by michchan** [directus/directus#2087]
The documentation (6.4.0) just mentioned how to implement S3
but is there any guide to implement others, say dropbox, one drive etc.?

**Comment by rijkvanzanten** [comment]
@WellingGuzman 🔔

**Comment by benhaynes** [comment]
Kamino cloned this issue to [directus/docs-v7](https://github.com/directus/docs-v7/issues/36)

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/38)
