### ISSUE TITLE
App: Calls to `undefined` from presentation links within translations interface

### ISSUE THREAD

**Issue by joselcvarela** [directus/directus#20880]
### Describe the Improvement

Will start with reproduction so it's easier to explain:
- Create collection `example`
- Create translations field
- Edit newly translations junction table
- Add a button based on `languages_id.code`
- Go to Content and create a new item in collection A
- Open Devtools and see calls to `/items/example_translations/undefined`. This is called whenever a change is made within the translations interface

This happens while the record on `example_translations` is not created so `undefined` is passed to here:
https://github.com/directus/directus/blob/6fb9288773a7e5683bfc6d565aad91445138c2fa/app/src/interfaces/presentation-links/presentation-links.vue#L44

**Comment by DanielBiegler** [comment]
@joselcvarela I fixed this locally for me with a very naive approach and it works but I wanted to ask if there is an actual bug that I could test against? Or is this just a behind the scene improvement? Did this wrong behaviour cause a bug somewhere? Cheers.

**Comment by joselcvarela** [comment]
This is just an improvement behind the scenes.
I think we can improve this by doing two things:
1. Don't make api call if `primaryKey` of junction table is `undefined`
2. If button is based on another field, only update when that field is updated. For example, if button depends on `languages_id.code` only refresh when `languages_id.code` changes. Currently, it's being refreshed when any other field is updated.
