### ISSUE TITLE
Options Override won't display in WYSIWYG editor

### ISSUE THREAD

**Issue by Ponyleung8812** [directus/directus#20882]
### Describe the Bug

I'm trying to apply the Options Override to a WYSIWYG field:
`{
    "fontsize_formats": "12px 14px 16px 18px 24px 36px 48px 56px 72px"
}`
but the toolbar item select font size has not changed as a result
![error](https://github.com/directus/directus/assets/154901583/29477607-104a-49c5-9d88-4acc4f72e90a)

### To Reproduce

1. Create a WYSIWYG field
2. Go to its options, Interface, fill Options Override with the code 
3. Save it
4. Go to the WYSIWYG editor in your content data
5. The toolbar has not changed with the custom code

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by DanielBiegler** [comment]
Well, by taking a look at the [documentation](https://www.tiny.cloud/docs/tinymce/latest/user-formatting-options/#font_size_formats) I found out that you have a typo. There has to be an underscore between `font` and `size`.

```diff
- { "fontsize_formats": "12px 14px 16px 18px 24px 36px 48px 56px 72px" }
+ { "font_size_formats": "69px 420px 1337mm" }
```

Which when fixed works:

![image](https://github.com/directus/directus/assets/14810858/2193d8e9-4caa-4d18-966c-5359ac77468f)

So this is not a bug in Directus but I do think it'd probably be a nice improvement if we mentioned or linked to the documentation of the editor library similar to how we link to sharps documentation in the custom transformations.
