### ISSUE TITLE
Redirect for SSO with Github does not seem to work on localhost

### ISSUE THREAD

**Issue by podlomar** [directus/directus#20892]
### Describe the Bug

When I setup a basic Directus SSO development environment with GitHub SSO according to [the docs](https://docs.directus.io/self-hosted/sso.html#testing-seamless-sso-locally) I always get `redirect_uri_mismatch` from GitHub even though in my GitHub OAuth app I make sure to set the `Authorization callback URL` to the exact string that Directus is redirecting to.

### To Reproduce

1. Clone [this repository](https://github.com/podlomar/directus-github-sso) with basic Directus setup
2. Setup a basic GitHub OAuth app. Tutorial [here](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app)
3. In the created OAuth app settings, set the `Authorization callback URL` to `http://localhost:8055/admin/login/continue`,
4. Make a copy of `.env.sample` file and fill in the client ID and client secret of the created app. Also fill in other required directus secrets.
5. Create a `data` folder with empty folders: `backup`, `database` and `uploads`.
6. Run `docker-compose up`. 
7. Try to sign in with GitHub. You should be redirected back to `localhost` with an error `redirect_uri_mismatch`.

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by DanielBiegler** [comment]
According to [GitHub Docs](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps#loopback-redirect-urls) and [OAuth RFC](https://datatracker.ietf.org/doc/html/rfc8252#section-7.3) the use of localhost is discouraged. They shall be replaced by using loopback URLs like `http://127.0.0.1:1234/path`

I do remember GitHub actively blocking `localhost` back in the past when I tried setting it up myself but thats quite a while ago.

Since this seems to be a problem with GitHub and not Directus itself I'll close this issue for now but we can of course reopen if something changes! 😄

**Comment by podlomar** [comment]
The localhost address does not seem to be the problem here. If I set the GitHub app Authorization callback to `http://127.0.0.1:8055/admin/login` which definitelly should be the correct address as the link from directus SSO button looks like this:

`http://127.0.0.1:8055/auth/login/github?redirect=http://127.0.0.1:8055/admin/login?continue=`

I still get the `redirect_uri_mismatch` as before. The GitHub docs even say thet when redirecting to 127.0.0.1, it is allowed by default and does not need to match the specified Authorizec callback URL at all. My guess was that Directus maybe ignores what is in the `redirect` param and tells GitHub tu redirect to some other address maybe constructed from the PUBLIC_URL environment variable or something. 

I will investigate furthur but I do not recall having any problems with setting up GitHub OAuth in the past without using Directus.

**Comment by podlomar** [comment]
@DanielBiegler As I supected, when I create a simple webpage with just a link to GitHub OAuth endpoint like this:

```
<a href="https://github.com/login/oauth/authorize?client_id=xxx&redirect_uri=http://127.0.0.1:8055/admin/login">Login with GitHub</a>
```
and run it on port 8055, the redirect works perfectly. So the problem does not seem to be with GitHub but with Directus not sending the proper redirect_uri parameter to GitHub.

**Comment by podlomar** [comment]
Ok, NOW it makes sense. After further investigation, I figured out that the redirect parametr is not there to point GitHub to a correct URL, but for Directus to know ehere to redirect AFTER all the OAuth negotiations are settled and the user is succesfully logged in. [This article](https://learndirectus.com/how-to-add-sso-to-directus/) helped mi to understand this. The docs alone are a bit misleading on this and they never mention the correct redirect URL which you need to set in your OAuth app.

**Comment by DanielBiegler** [comment]
Thats awesome to hear, thanks for the update!

> The docs alone are a bit misleading on this and they never mention the correct redirect URL

The SSO Quickstart guide in our docs over [here](https://docs.directus.io/self-hosted/sso.html#openid) seems to mention the settings you'll need with a Google SSO example

> On **Authorized redirect URIs** put your Directus instance address plus /auth/login/google/callback. For example, you should put https://directus.myserver.com/auth/login/google/callback where https://directus.myserver.com should be the address of your Directus instance.

We'd be very grateful for [pull requests](https://docs.directus.io/contributing/introduction.html) if you think you can improve the docs for other people, thanks! :heart:
