### ISSUE TITLE
image upload

### ISSUE THREAD

**Issue by semorur** [directus/directus#20898]
### Describe the Bug

on the newest version 10.8.3 (on v10.8.2 - everything works fine)
there are problems with image uploads

it looks like the problem is with generated smaller versions of images (it is empty or with changed colors)

### To Reproduce

just upload any image jpg or png to files

### Directus Version

v.10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Can you elaborate on the specific situation to reproduce this?

> just upload any image jpg or png to files

Is not enough to recreate the situation you are seeing with the docker image.

https://github.com/directus/directus/assets/9389634/1a816e25-5d9d-41ff-ac15-e074d59668ee

Happy to re-open issue when it becomes reproduceable 😄
