### ISSUE TITLE
AWS, installed fine but admin login = Server error occurred

### ISSUE THREAD

**Issue by neosin** [directus/directus#2089]
## Version Info
  - Directus version and branch:  6.4.8 3d9f609
  - PHP version: 7.2.2
  - MySQL version: 5.7.12
  - Web server: Apache 2.0
  - OS name and version: ubuntu16.04.1

## Expected Behavior
user login form should validate user/pass and enter cms

## Actual Behavior
"Server error occurred" when pressing login button
No log files generated

## Steps to Reproduce
 1.  upload unpacked files from repo zip to AWS/Cloud9 environment
 2.  run installation in browser
 3.  try to login
 4.  install via git/compser to AWS/Cloud9 environment
 5.  run installation in browser
 6.  try to login

This error occurs on AWS/Cloud9 environment.
Additionally (and unrelated?) the installation script cannot detect mod rewrite on AWS for some reason.
phpinfo does indeed show it is available and I have tested it works with other scripts.

Locally, I am able to install from zip and use without any problems on windows8 with latest xampp.
Locally, I am able to install from git/composer and use without any problems on windows8 with latest xampp.

**Comment by neosin** [comment]
ok resolved it

During installation a Ubuntu command overwrote some of the apache conf files and since apache2.conf has higher hierarchy it wasn’t applying the mod_rewrite

**aen2mod in 16.04 LTS does this**

**Comment by neosin** [comment]
this ticket can be closed

**Comment by WellingGuzman** [comment]
Glad you resolved the issue. thanks for the clarification.

**Comment by ManjunathL** [comment]
Hi 

I am Facing "Server error occurred" how to resolve this issue in ubuntu 14.04 LTS version please give some advice

**Comment by rijkvanzanten** [comment]
@ManjunathL can you be more specific? As you can tell from the original issue, these kind of problems are caused by small issues in the server configuration.

**Comment by ManjunathL** [comment]
Hi All,

Finally I got a solution for this in Directus "Server Execution Error"

Directus “Server Execution Error “ Solution


**apache2/site-availabel/000-default.config**
<Directory /var/www/html>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Require all granted
    </Directory>

Thank you

**Comment by benhaynes** [comment]
Hey @ManjunathL — if you're still experiencing this issue could you open a new ticket for this with as much info as possible?

Thanks!

**Comment by benhaynes** [comment]
https://media.giphy.com/media/l0MYCWfIFOMJGjM7C/giphy.gif
