### ISSUE TITLE
Content not saved if date field is empty, even if it's not required. Error received: 'Not a valid date'

### ISSUE THREAD

**Issue by ninjabachelor** [directus/directus#2090]
## Version Info
- Directus version and branch: 6.4.5
- PHP version: 7.1.13
- MySQL version: latest
- Web server: nginx
- OS name and version: Ubuntu 16

## Expected Behavior
Save content with empty date if it's not a required field.

## Actual Behavior
If the content has a not-required date field, the content is not saved. The error shown is: 'Not a valid date'.

## Steps to Reproduce
1. Create a table with a not-required date field.
2. Create a new content leaving the date field empty.
3. Save the content.
4. You should receive an error: 'Not a valid date'

Note: debugging app/core/interfaces/datetime/date.js, the validate function receives a value which is: 'Invalid date', even if the field is empty.

## Schema Dump, Logs, or Screenshots
![validation](https://user-images.githubusercontent.com/3736582/36913475-62705ce2-1e4a-11e8-8a6b-c2b83120ee0c.png)

**Comment by rijkvanzanten** [comment]
Hey @ninjabachelor! In what browser does this happen?

**Comment by ninjabachelor** [comment]
Hi @rijkvanzanten ,
I'm using Chrome and Firefox on Mac

**Comment by rijkvanzanten** [comment]
At the moment, all core developers are working fulltime on the next major version of the platform, so I'll have to leave this open as a help-wanted. If anyone is inclined to take a swing at fixing this, a PR is very welcome 😄

This sounds like a somewhat easy fix. Accepting an empty string as a valid value (when the field isn't required) should do it.

**Comment by WellingGuzman** [comment]
Fixed by https://github.com/directus/directus/commit/78ce1bd7042d3016578cccc9dca4b1e510cb892b
