### ISSUE TITLE
importing from @directus/api lost typescript declaration

### ISSUE THREAD

**Issue by romanlex** [directus/directus#20902]
### Describe the Bug

If you import for example
`import { useLogger } from '@directus/api/logger'`

You get error `Cannot find module '@directus/api/logger' or its corresponding type declarations`

![image](https://github.com/directus/directus/assets/3369304/db003938-de22-4c81-b3ff-b9c2a111e1b4)

This happens because the exports section clearly indicates where to get the file from, but typescript does not understand this.

You need remove dist folder and change section `exports` to
```
  "exports": {
    ".": "./index.js",
    "./*": "./*.js",
    "./cli/run.js": "./dist/cli/run.js",
    "./package.json": "./package.json"
  },
  ```
  
  Or add `typesVersions` section to package.json with content
  
  ```
  "typesVersions": {
    "*": {
      "logger": ["dist/logger.d.ts"],
      ...
    }
  },
  ```
  
  Now its work perfectly
  
![image](https://github.com/directus/directus/assets/3369304/cfa9ac3d-53a9-46e5-9de6-15d21670caf9)

  

### To Reproduce

Install @directus/api: v15.0.0
create any hook with typescript syntax
use `import { useLogger } from '@directus/api/logger'` for check

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Importing internals directly from `@directus/api` is not supported the `logger` is provided to hooks in the context object.
https://docs.directus.io/extensions/hooks.html#register-function
