### ISSUE TITLE
mysql error trying to reset the password using cli

### ISSUE THREAD

**Issue by rajiteh** [directus/directus#2091]
## Version Info
  - Directus version and branch (Or commit hash): getdirectus/directus:6.4.8 (image id: sha256:d7f0765cf2260116d373ff5410a93d3b3c2ae9bb95ec6757ae262f35b450a225)
  - PHP version: `PHP 7.1.14 (cli)`
  - MySQL version: 5.7.21

## Expected Behavior

User's password is changed to the supplied argument of the cli command.

## Actual Behavior

Command fails with a PDOException due to `salt` string being invalid for the field. 

## Steps to Reproduce
 1. `docker exec` in to the directus container.
 2. type `php bin/directus user:password -u admin@admin.com -p pass
 3. the command will fail with an exception.

## Schema Dump, Logs, or Screenshots

```
root@13a72bf8de2e:/var/www/html# php bin/directus user:password -e r@r.r -p pass
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xA9\x8B\x15Z`\x9A...' for column 'salt' at row 1 in /var/www/html/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:239
Stack trace:
#0 /var/www/html/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute()
#1 /var/www/html/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(391): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#2 /var/www/html/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(349): Zend\Db\TableGateway\AbstractTableGateway->executeUpdate(Object(Zend\Db\Sql\Update))
#3 /var/www/html/api/core/Directus/Console/Common/User.php(102): Zend\Db\TableGateway\AbstractTableGateway->update(Array, Array)
#4 /var/www/html/api/core/Directus/Console/Modules/UserModule.php(98): Directus\Console\Common\User->changePassword('r@r.r', 'pass')
#5 /var/www/html/api/core/Directus/Console/Modules/ModuleBase.
php(75): Directus\Console\Modul in /var/www/html/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php on line 244
root@13a72bf8de2e:/var/www/html#
```
![image](https://user-images.githubusercontent.com/905419/36956317-bc374cba-1ffb-11e8-9264-b3c6b011a4d1.png)

## more info

as a temporary work around i've removed this part from the code StringUtils.php https://github.com/directus/directus/blob/master/api/core/Directus/Util/StringUtils.php#L97-L102

**Comment by WellingGuzman** [comment]
Thanks @rajiteh for the report.

This has been fixed by https://github.com/directus/directus/commit/74d79e609450734f116517412f2419ceae5e795c
