### ISSUE TITLE
Tabelview not saved when collection key is of type "manually entered string"

### ISSUE THREAD

**Issue by beo3000** [directus/directus#20924]
### Describe the Bug

The visible columns cannot be change for collections with key of type "manually entered string". Console logs error 

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')
    at index.6UgrYuTr.entry.js:99:12652
    at Proxy.map (<anonymous>)
    at Proxy.update (index.6UgrYuTr.entry.js:99:12608)
    at async Proxy.savePreset (index.6UgrYuTr.entry.js:99:13641)
    at async f (index.6UgrYuTr.entry.js:99:14134)

at

        async update(n, e) {
            const t = Q2();
            $E[n] = t;
            const i = await Jn.patch(`/presets/${n}`, e);
            return $E[n] === t && (this.collectionPresets = this.collectionPresets.map(o=>{
                const r = i.data.data;
                return o.id === r.id ? r : o
            }
            )),
            i.data.data
        },
 

### To Reproduce

- Create a collection with a primary key "id" of type "manually entered string"
- Create an item
- Open Tableview
- Try to add any column to view
- leave view -> return to view -> added column ist not visible

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by DanielBiegler** [comment]
Tested on the current main branch and its not reproducible for me:

![image](https://github.com/directus/directus/assets/14810858/242d5060-55fc-44cb-9a07-04623e7c04bd)

-- I'll update this comment once I've tested the official 10.8.3 image --
