### ISSUE TITLE
"Recommended Defaults" permissions for non admins breaks access to the revisions.

### ISSUE THREAD

**Issue by alexvdvalk** [directus/directus#20938]
### Describe the Improvement

directus_revisions collection is not granted
directus_activity read access is limited to $current_user

I'm not sure if this is bug status or even needs to be changed, but UX is a bit weird if non admin users don't see the Revision section when looking at a record.
<img width="311" alt="Screenshot 2024-01-02 at 12 10 30" src="https://github.com/directus/directus/assets/21194068/03a2100f-49f4-46d2-acde-9864c96c259e">

**Comment by br41nslug** [comment]
> directus_revisions collection is not granted
> directus_activity read access is limited to $current_user

These are the defaults for non-admin users but it should hide the revisions tool in the sidebar 🤔 

How can i reproduce this? 

Permissions:
![image](https://github.com/directus/directus/assets/9389634/85f307dd-a4db-4c44-974f-072cd08c7f53)

Collection:
![image](https://github.com/directus/directus/assets/9389634/fbf05b35-5f6f-4526-ac29-c977c41089c7)

Item Detail:
![image](https://github.com/directus/directus/assets/9389634/89d3cfb3-e889-42fa-a4b8-da1d01912e46)

**Comment by alexvdvalk** [comment]
It feels like the "recommended defaults" permissions for non admins should allow read access to directus_revisions and directus_activity, but after further research, this would lead to non-users being able to query all edit histories for all collections, and would expose data in a bad way.
