### ISSUE TITLE
Encoding Issue with Greek Characters in WYSIWYG or Markdown Editor 

### ISSUE THREAD

**Issue by jsalichos** [directus/directus#20947]
### Describe the Bug

The bug is a character encoding issue in the WYSIWYG editor. It seems that when you write Greek or other national characters, the database field gets updated with encoded characters instead of displaying them correctly.

For example, the word "Καλημέρα" should be stored as it is, but it is being converted to "&Kappa;&alpha;&lambda;&eta;&mu;έ&rho;&alpha;" which represents the HTML entities for each individual character.

### To Reproduce

To reproduce the bug where Greek or other national characters are encoded in a WYSIWYG editor, follow these steps:

1. Open any record of a collection that has a WYSIWYG editor.
2. Navigate to the field where you can input text.
3. Start typing or copy-paste Greek or other national characters into the editor.
4. Ensure that you observe how the characters appear in real-time as you type them.
5. After entering the desired text, save or submit it to update the database field.

To verify if encoding occurs and see how it affects output in markdown:

1. Retrieve and view the data from the updated database field.
2. Check if any of the entered Greek or national characters have been converted into their encoded representations (e.g., Κ instead of &Kappa;).

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
The WYSIWYG is intended to write HTML content. The entity encoding is enabled by default for the best compatibility with the web and underlying databases.

To disable entity encoding you can set the "entity_encoding" option of TinyMCE https://www.tiny.cloud/docs-3x/reference/Configuration3x/Configuration3x@entity_encoding/

![image](https://github.com/directus/directus/assets/9389634/2d083397-dc26-47d6-b9d3-aba68cfb5af3)

**Comment by jsalichos** [comment]
Thank you, 

I just came to the same conclusion by reading carefully the docs. In fact I came back to update the issue
I use:
{
    "selector": "textarea",
    "entity_encoding": "raw"
}

Maybe the selector is not needed.

It would be nice though to have this functionality as a general setting for projects for countries that do not use latin characters,

**Comment by br41nslug** [comment]
> It would be nice though to have this functionality as a general setting for projects for countries that do not use latin characters,

It really depends on whether your database is configured to support non-latin chars and how you're using the content. If you're rendering it in a webpage then having the non-latin characters encoded will ensure it is rendered correctly on any browser (else you could theoretically end up with those beautiful question mark characters ���).

**Comment by jsalichos** [comment]
It's not about displaying the text. It is about being able to search text content either by using db queries or gull text search.
