### ISSUE TITLE
403 status disappear when we restart GCloud Run

### ISSUE THREAD

**Issue by weburnit** [directus/directus#20956]
### Describe the Bug

Suddenly, all Flow APIs have 403 status
We restart the Google Cloud Run, then 200 nicely come

### To Reproduce

No idea how to reproduce this

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Unfortunately without reproduction steps there is not a lot we can do here 😬 Closing this issue for now as not reproducable but happy re-open the issue when more information becomes available to debug this
