### ISSUE TITLE
Can't access files in root folder when folder access is restricted

### ISSUE THREAD

**Issue by DrDreave** [directus/directus#20960]
### Describe the Bug

**Target state**: Block public access to the files in a specific folder and allow access to all other files. 
**Problem:** If a policy that allows access to all files (with the exception of one folder) is set up, access to files that are not in any folder is also incorrectly blocked.

## Example

- **Root**
  - _Asset A_
  - **Folder B**
    - _Asset B_
  - **Folder C**
    - _Asset C_

**Rule:** Allow access if folder.id is not one of **Folder B**
_Same applies to using the doesn't equal operator._

### Expected result
- _Asset A_: allowed
- _Asset B_: blocked
- _Asset C_: allowed

### Actual result
- _Asset A_: blocked ❗ 
- _Asset B_: blocked
- _Asset C_: allowed

### To Reproduce

- Create a new directory _A_
- Upload a file to directory _A_
- Upload a file to the _root_ directory
- Enter the permission settings
- Setup a custom read access rule for the _Public_ role for the _directus_files_ collection
- Create a new rule in the _Item Permissions_ tab: `folder -> id is not one of <id of directory A>`
- Make a call to `<host-url>/files` as an unauthenticated user (public role)

The file in the root directory will not show up even though it shouldn't be covered by the set up access rule.

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by DrDreave** [comment]
Many thanks for the quick reply. Unfortunately, the problem still occurs when I run the check on folder instead of folder.id.

**Comment by eXsiLe95** [comment]
As I understand the issue, it should also run into problems when filtering for other attributes of an folder, e.g. folder name.

**Comment by br41nslug** [comment]
My bad forgot to include the `null` check in the screenshot.
![image](https://github.com/directus/directus/assets/9389634/33753422-7114-4bd0-84f5-ad87cb41de92)

Currently `null`s are not matched by other operators as described in this issue https://github.com/directus/directus/issues/13778

**Comment by br41nslug** [comment]
> For a non-technical user that doesn't understand how Directus resolves those rules, it's simply false to not grant access to a file as described in the bug report.

I understand that its inconvenient which is why the original issue (linked) for this is still active which would cover your A scenario.
