### ISSUE TITLE
Detail groups collapse on save-and-stay

### ISSUE THREAD

**Issue by AndreKR** [directus/directus#20968]
### Describe the Bug

When saving an item with <kbd>Ctrl</kbd>+<kbd>S</kbd> or by choosing "Save and Stay", detail groups that have been expanded are collapsed.

This did not happen in v9.26.0.

### To Reproduce

1. In the data model of any collection create a detail group with "Start" set to "Start Closed".
2. Go to edit an item of that collection.
3. Expand the detail group.
4. Change any field so that the save button becomes available.
5. Either press <kbd>Ctrl</kbd>+<kbd>S</kbd> or from the menu of the save button choose "Save and Stay".

The previously expanded group collapses.

### Directus Version

v10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Pachat** [comment]
I use groups details inside Accordions and they do not collapse with Ctrl+S at least in v10.8.3
