### ISSUE TITLE
Studio: Access to the Marketplace from Settings

### ISSUE THREAD

**Issue by alexchopin** [directus/directus#20978]
Extensions Links in Studio Settings for:
- Browse installed extensions (Action: enable/disable + uninstall)
- Browse new extensions (Action: Install)
Design:
- Table/List Layout with Search Input
- Categories (Type, Popular: default)
- Verified Authors

**Comment by rijkvanzanten** [comment]
Closing this in favor of smaller issues for individual parts 🙂
