### ISSUE TITLE
Directus Version shows undefined

### ISSUE THREAD

**Issue by 0xJamin** [directus/directus#20979]
### Describe the Improvement

The recent Directus `10.8.3` version shows `undefined` when self-hosted.
The version seems to be missing

I am running DIrectus  both locally and on a self-hosted ec2 instance on AWS and the error is the same

See screenshot below

<img width="223" alt="Screenshot 2024-01-05 at 6 01 26 pm" src="https://github.com/directus/directus/assets/34829458/ac75a5dc-2694-4cd6-89ec-192432bca709">

**Comment by br41nslug** [comment]
This was resolved in https://github.com/directus/directus/issues/20857 and will be fixed in the next release 😄
