### ISSUE TITLE
Flow JSON interpreted as string for no reason

### ISSUE THREAD

**Issue by malipetek** [directus/directus#20976]
### Describe the Bug

Hello, I have a clients directus and a staging directus instance. I have constructed a flow in the staging one and copied over to the clients. Flows are identical except some details like collection names and fields names.

So subject flow:
  1 - receives an id of an article. 
  2 - it reads translations with "read data"
  3 - it runs this simple script and returns an array
```js
module.exports = async function({ $last }) {
	return $last.map(translation => {
    	translation.article_content = translation.article_content
            .replace(/lang\="([^"]+)"/gi, (a, langCode) => {
        		return `lang="${translation.languages_id}"`
        	});
        return translation;
    });
}
``` 
4- And then it is supposed to trigger another flow with array entries
<img width="726" alt="image" src="https://github.com/directus/directus/assets/13527277/8f1f046e-b122-4aa8-b818-ef95b4b5c1e1">

At trigger flow step it behaves different, in the staging instance it is fine, payload of 3rd operation is an array:
<img width="835" alt="image" src="https://github.com/directus/directus/assets/13527277/ad5233a5-6aa4-421d-afc1-a9167f37f973">

And it triggers another flow with all entries with this settings:
<img width="832" alt="image" src="https://github.com/directus/directus/assets/13527277/ea3000d7-b175-4dc6-aa1d-2c84bbaa3538">

## Issue and TLDR
However when I run almost exactly same in the production this is the case:
 Everything fine until "trigger flow operation", for some reason payload passed to it in options becomes a string instead of an array. Please see below:
<img width="840" alt="image" src="https://github.com/directus/directus/assets/13527277/cb81ff83-831a-4b84-ae97-38485277d47a">

I suspected maybe it is because of payload, but it doesn't make sense because payload of 3rd operation shows as parsed.
I don't know how to proceed.

### To Reproduce

I can give access to self hosted staging instance and can check any logs/data from production one. 
These are the operations of problematic one and third one I mentioned is `send_data_to_save_flow`:

C005C... | Read Translations | item_read_fskq6 | item-read | 19 | 1 | {"collection":"Blog_translations","query":{"filter":{"Blog_id":{"_eq":"{{ $trigger.data.key }}"}}}} | 0B0D9FA... |   | AE465... | 2024-01-05 09:09:04 | BD135CD4-68...
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0B0D9F... | Fix language inlines | fix_language_inlines | exec | 37 | 1 | {"code":"module.exports = async function({ $last }) {\n\treturn JSON.parse(JSON.stringify($last.map(translation => {\n    \ttranslation.Description = translation.Description\n            .replace(/lang\\=\"([^\"]+)\"/gi, (a, langCode) => {\n        \t\treturn `lang=\"${translation.languages_code}\"`\n        \t});\n        return translation;\n    })))\n}"} | 9ADAB94... |   | AE465A95-5A... | 2024-01-05 09:09:04 | BD135CD4-68...
9A... | Send Data to Save Flow | send_data_to_save_flow | trigger | 55 | 1 | {"payload":"\"{{ $last }}\"","flow":"85CBDBB3-02..."} |   |   | AE465A95-5A... | 2024-01-05 09:09:04 | BD135CD4-68...

### Directus Version

10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
You're interpolating it into a string here if im not mistaken, enable the template mode (red arrow) and remove the quotes:
![image](https://github.com/directus/directus/assets/9389634/fc8fa73b-331a-4263-80ad-e18c9afd12fe)

**Comment by domdus** [comment]
As @br41nslug said... I run into this regularily 😄

<img width="529" alt="image" src="https://github.com/directus/directus/assets/67951828/769b5792-903f-40a5-89c0-b937942fa8cb">

**Comment by malipetek** [comment]
You are correct guys, it was exactly that. I realized when I was reading db entry for this issue and realized there is `\"` around `{{ $last }}`

Thanks <3
