### ISSUE TITLE
Production mode for error suppression?

### ISSUE THREAD

**Issue by recumbentbirder** [directus/directus#2097]
## Version Info
  - Directus version and branch (Or commit hash): 6.4.3
  - PHP version: 7.0.22
  - MySQL version: 
  - Web server: (Ex. Apache, nginx or IIS?) Apache/2.4.18 (Ubuntu)
  - OS name and version: Linux Ubuntu Xenial

## Expected Behavior
On setting `DIRECTUS_ENV`, I' d expect to suppress red popups in the user backend, according to docs and comments in api/config.php:

``
/**
 * DIRECTUS_ENV - Possible values:
 *
 *   'production' => error suppression
 *   'development' => no error suppression
 *   'staging' => no error suppression
 */
define('DIRECTUS_ENV', 'production');
``
 
## Actual Behavior

No change in popups.

**Comment by rijkvanzanten** [comment]
Hey @recumbentbirder, thanks for the heads up! 

In the next major version, we’re not displaying the JS errors in notifications at all, but will limit it to something more generic and user friendly. The full error with debug info will be in the dev console.

**Comment by WellingGuzman** [comment]
Hey @recumbentbirder, if you are not seeing php error on the API this is working as expected.

On the web app we do not have options to suppress these notification errors yet.

I will close this unless it's a bug related directly with php displaying errors.
