### ISSUE TITLE
Error in storage registration for Azure Container

### ISSUE THREAD

**Issue by HelioDigital** [directus/directus#20989]
### Describe the Bug

Azure Storage does not currently work due to an incorrect variable being used in the DriverAzure class. This causes an undefined container name to be passed to the constructor, which causes Azure storage to fail. 

### To Reproduce

The constructor for the DriverAzure class (storage-azure-driver/dist/index.js) on line 16 is expecting a variable called containerName, however, _container_ is given and available within the config object instead:

`var DriverAzure = class {
  containerClient
  signedCredentials
  root
  constructor(config) {
    this.signedCredentials = new StorageSharedKeyCredential(config.accountName, config.accountKey)
    const client = new BlobServiceClient(
      config.endpoint ?? `https://${config.accountName}.blob.core.windows.net`,
      this.signedCredentials
    )
    console.log(config)
    this.containerClient = client.getContainerClient(config.containerName)
    this.root = config.root ? normalizePath(config.root, { removeLeading: true }) : ''
  }`

When using a console.log here for the config object I get the below:
`{
  accountName: 'REDACTED',
  accountKey: 'xxxxx REDACTED',      
  container: 'REDACTED'
}`

As seen containerName does not exist.

### Directus Version

10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
How does your configuration look like?

**Comment by HelioDigital** [comment]
> How does your configuration look like?

`STORAGE_LOCATIONS="azure"
STORAGE_AZURE_DRIVER="azure"
STORAGE_AZURE_ACCOUNT_NAME="xxx"
STORAGE_AZURE_ACCOUNT_KEY="xxxxxx"
STORAGE_AZURE_CONTAINER="xxx"`

I figured it out now. It seems that the Restack documentation is out of date. After digging through the code a bit more I see it just uses the env variable name to construct that config option, so changing it to STORAGE_AZURE_CONTAINER_NAME worked. 

I'm going to leave this here for anyone else facing this issue. Here's the [link ](https://www.restack.io/docs/directus-knowledge-directus-azure-storage-integration)to the incorrect documentation.

**Comment by paescuj** [comment]
I see, thanks!
Also note that it is correctly documented in our side: https://docs.directus.io/self-hosted/config-options.html#azure-azure
