### ISSUE TITLE
How to create a custom plugin that extends the base core plugin from tinymce?

### ISSUE THREAD

**Issue by tumraja** [directus/directus#2098]
I have been searching and reading on the documentation for the directus. The Custom Interfaces section doesn't explain how to implement custom plugin from tinymce library.

I want to add custom plugin in the WYSIWYG_FULL by extending the core plugin base WYSIWYG_FULL.

I want all my custom plugins should be located in the custom directory but still using the core infrastructure. 

Would you please give the solution on this.

**Comment by rijkvanzanten** [comment]
Hey @tumraja! What are you thinking of adding? If it's useful for everyone, we could also merge it in the main repo!

> I want to add custom plugin in the WYSIWYG_FULL by extending the core plugin base WYSIWYG_FULL.

You should be able to copy the wysiwyg_full interface to the customs folder and customize it however you want.

> I want all my custom plugins should be located in the custom directory but still using the core infrastructure.

This is what the customs folder does. The app itself doesn't differentiate between interfaces in the core folder vs the customs folder. The split is just there to make sure people don't accidentally delete core interfaces that are needed for the system to work properly.

Let me know if that answers your question :)

**Comment by tumraja** [comment]
This is very usefull and it would be nice to be merge to the repo and have a documentation that explains how to develop a custom working plugin either as a standalone or part of the toolbar-options of wysiwyg_full.
> Hey @tumraja! What are you thinking of adding? If it's useful for everyone, we could also merge it in the main repo!

As a developer, we are using quite alot Directus, We have to create plugin for different control, we need to have a clear path to do this.

How the custom plugin can be linked or hooked to  wysiwyg_fullinterface to the customs folder?
Would you be able to provide the example for this? Thank you.
> You should be able to copy the wysiwyg_full interface to the customs folder and customize it however you want.

**Comment by rijkvanzanten** [comment]
You’ll be pleased to hear that we’ve redesigned how extensions are built and distributed in the next major version (7.0)! We’re even working on a marketplace to allow developers to host and distribute these extensions in a centralized way 😄

> How the custom plugin can be linked or hooked to wysiwyg_fullinterface to the customs folder?
Would you be able to provide the example for this? Thank you.

(I might understand your question wrong, but) you don’t. You copy it to the customs folder, so you’re making a direct copy that does the same things. There is no way to extend an existing one from the customs folder. It’s only possible to create new ones there
