### ISSUE TITLE
DirectusError You don't have permission to access this - readOne

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [directus/directus#20990]
### Describe the Bug

I am using in a custom hook the itemService with admin auth (accountability null).
Everything works except using readOne on a collection where String is the primary key.

### To Reproduce

Created a simple database
Create a collection with String as primary key.
Just search for a key:

```
let obj = this.cashregisters_transactions_service.readOne(obj_json.id);

```

Error on console:

```
Transaction parsing progress: 0/3
         getCashregisterExternalIdentifierFromTransaction: 0.177ms
         findOrCreateCashregister: 13.429ms
         [CashregisterParseSchedule] Failed
         Error [DirectusError]: You don't have permission to access this.
             at ItemsService.readOne (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.9_pinia@2.1.7_typescript@5.3.3_vue@3.3.13/node_modules/@directus/api/dist/services/items.js:367:19)
             at async ParseSchedule.parse (file:///directus/extensions/hooks/cashregisterSchedule/ParseSchedule.js:165:25)
             at async EventEmitter.<anonymous> (file:///directus/extensions/hooks/cashregisterSchedule/index.js?t=1704650646922:73:17)
             at async Promise.all (index 0) {
           extensions: undefined,
           code: 'FORBIDDEN',
           status: 403
         }
```

### Directus Version

10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
I couldn't reproduce this on the quick. Could you share a bit more information about your hook extension, specifically how you're creating/using the `ItemsService`? Does your collection primary key looks like this?
<img width="606" src="https://github.com/directus/directus/assets/5363448/c15efa2d-b23a-4807-b832-7460bdcd0b69">

**Comment by NilsBaumgartner1994** [comment]
<img width="2032" alt="Bildschirmfoto 2024-01-08 um 00 56 59" src="https://github.com/directus/directus/assets/33295329/c27c31ef-1373-43a0-87f9-eae76bbd31fd">


```
export class ItemsServiceCreator {

    constructor(services, database, schema) {
        this.services = services;
        this.database = database;
        this.schema = schema;
    }

    getItemsService(tablename) {
        const {ItemsService} = this.services;
        return new ItemsService(tablename, {
            accountability: null, //this makes us admin
            knex: this.database,
            schema: this.schema,
        });
    }

}
```



```
init(getSchema, services, database, logger) {
    this.schema = await getSchema();
    this.database = database;
    this.logger = logger;
    this.services = services;
    this.itemsServiceCreator = new ItemsServiceCreator(services, database, this.schema);
    this.cashregisters_transactions_service = this.itemsServiceCreator.getItemsService(TABLENAME_CASHREGISTERS_TRANSACTIONS);
}

...
// obj_json.id is a string like: "158-226-17-1"
let obj = this.cashregisters_transactions_service.readOne(obj_json.id);


```

**Comment by Mathijs003** [comment]
i got the same issue, trying to access a collection with the Itemservice in a hook extension. Logged in as admin in directus

**Comment by br41nslug** [comment]
> i got the same issue, trying to access a collection with the Itemservice in a hook extension. 

Are you sure the item/collection exist, no typos/uppercase? How are you creating the items service?

**Comment by Mathijs003** [comment]
My code : 
```
export default defineHook(({ action }, { env, services, getSchema }) => {
  const { ItemsService } = services;

  action("poi.items.create", async (meta, context) => {
 
    const poiTranslationService = new ItemsService("poiTranslation", {
      schema: await getSchema(),
      accountability: context.accountability,
    });

    const result = await poiTranslationService.readOne(
      meta.payload.originalLanguage
    );
    
    console.log(result);
  });
});
```

Accountability object: 


```
accountability: {
  user: "cf5abf22-e87e-43fe-827f-918dfd0d01c8";
  role: "eb96156b-14da-4568-b808-14b0c6232663";
  admin: true;
  app: true;
  ip: "192.168.65.1";
  userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36";
  origin: "http://0.0.0.0:8055";
  permissions: [];
}
```

Error: 

DirectusError: You don't have permission to access this.
at ItemsService.readOne (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.21/node_modules/@directus/api/dist/services/items.js:372:19)

**Comment by br41nslug** [comment]
Ah you may want to remove the `accountability` from the constructor as i suspect that `context.accountability` will be `null` which translate to "public permissions".

**Comment by Mathijs003** [comment]
Nevermind, I found the issue. I was requesting an item that is not existing. Thanks for the quick response

**Comment by NilsBaumgartner1994** [comment]
I would wish to get a 404 exception for requesting an item which does not exist instead of no permission.Beste Grüße,Nils BaumgartnerAm 03.04.2024 um 22:11 schrieb Mathijs003 ***@***.***>:﻿
Nevermind, I found the issue. I was requesting an item that is not existing. Thanks for the quick response
