### ISSUE TITLE
It seems that ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION doesn't change limitInputPixels

### ISSUE THREAD

**Issue by AndriyAntonenko** [directus/directus#20995]
### Describe the Bug

When I am trying to download large image to the directus, I am receiving an error:
```json
{
  "errors": [
    {
      "message": "Input image exceeds pixel limit",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

It seems this error came from sharp library. I've tried to set this env value large enough, but it doesn't work
```bash
ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION=number:100000000000
```

My image has the next sizes: 16226 × 20665
So, pixels amount: 335310290
From Directus docs I know that `limitInputPixels=Math.pow(env['ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION'], 2)`. So my `limitInputPixels=1e+22` and this value much bigger than amount of pixels from my image.

Can you check it, pls?

### To Reproduce

Try to download a large image: here is my https://drive.google.com/file/d/1eqKWnfz2emyw0e-m26oh8BjUAdetvLzB/view?usp=sharing

### Directus Version

10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
We can definitely implement this `Sharp` setting for maximum pixels, be aware that working with images of this size can have noticable performance implications.

**Comment by AndriyAntonenko** [comment]
So, it could be a performance issue? My server machine is not big, but I can also reproduce this issue locally on my Mac OS with M2 CPU. I think it should be enough

**Comment by AndriyAntonenko** [comment]
So, @br41nslug can you suggest something, or are you gonna make some fix and I should wait for it?

**Comment by br41nslug** [comment]
> So, it could be a performance issue?

Correct, as you may expect the bigger images get the more CPU/memory the process takes to make thumbnails.

> So, @br41nslug can you suggest something

Sure, upload smaller images for the time being 😂 

> or are you gonna make some fix and I should wait for it?

That is what open issues are for, people with large enough servers should not be limited by this setting, and whether you wait is up to you 😄

**Comment by br41nslug** [comment]
> It is not related to server size.

I know, i mean for those that have a large enough server to handle the transformations of that size without freezing up the server while processing, not directly related to this issue just my performance warning.

> Do you have some estimates for this task to be done?

[Unfortunately, we can not provide estimates on features or fixes](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍

**Comment by AndriyAntonenko** [comment]
I understand. Thanks for the help and explanation. Have a nice day

**Comment by rijkvanzanten** [comment]
Took another look at this, and the reason behind the error is that the output `limitInputPixels` is above JavaScript's safe integer number (`1+e22 > Number.MAX_SAFE_INTEGER`) which in turn causes Sharp's option validation to fail. 

While we could theoretically disable input pixels limit when it exceeds that, I would strongly urge against doing so. Directus is not built to handle transforming images that are counted in gigs, and will most likely cause major memory issues on production servers if attempted. 

I'm considering this a wontfix, and will put a note in the docs that the max number for `ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION` is the square root of `Number.MAX_SAFE_INTEGER`, aka 94906265. Thanks!

**Comment by AndriyAntonenko** [comment]
@rijkvanzanten in my case problem occurs on the file upload step and the problem not just with value of the `ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION`, but with `getMetadata` method in `FilesService`

```ts
async getMetadata(stream: Readable, allowList = env['FILE_METADATA_ALLOW_LIST']): Promise<Metadata> {
		return new Promise((resolve, reject) => {
			pipeline(
				stream,
				sharp().metadata(async (err, sharpMetadata) => {
					if (err) {
						reject(err);
						return;
					}

					const metadata: Metadata = {};

					if (sharpMetadata.orientation && sharpMetadata.orientation >= 5) {
						metadata.height = sharpMetadata.width ?? null;
						metadata.width = sharpMetadata.height ?? null;
					} else {
						metadata.width = sharpMetadata.width ?? null;
						metadata.height = sharpMetadata.height ?? null;
					}

					// Backward-compatible layout as it used to be with 'exifr'
					const fullMetadata: {
						ifd0?: Record<string, unknown>;
						ifd1?: Record<string, unknown>;
						exif?: Record<string, unknown>;
						gps?: Record<string, unknown>;
						interop?: Record<string, unknown>;
						icc?: IccProfile;
						iptc?: Record<string, unknown>;
						xmp?: Record<string, unknown>;
					} = {};

					if (sharpMetadata.exif) {
						try {
							const { image, thumbnail, interoperability, ...rest } = exif(sharpMetadata.exif);

							if (image) {
								fullMetadata.ifd0 = image;
							}

							if (thumbnail) {
								fullMetadata.ifd1 = thumbnail;
							}

							if (interoperability) {
								fullMetadata.interop = interoperability;
							}

							Object.assign(fullMetadata, rest);
						} catch (err) {
							logger.warn(`Couldn't extract EXIF metadata from file`);
							logger.warn(err);
						}
					}

					if (sharpMetadata.icc) {
						try {
							fullMetadata.icc = parseIcc(sharpMetadata.icc);
						} catch (err) {
							logger.warn(`Couldn't extract ICC profile data from file`);
							logger.warn(err);
						}
					}

					if (sharpMetadata.iptc) {
						try {
							fullMetadata.iptc = parseIptc(sharpMetadata.iptc);
						} catch (err) {
							logger.warn(`Couldn't extract IPTC Photo Metadata from file`);
							logger.warn(err);
						}
					}

					if (sharpMetadata.xmp) {
						try {
							fullMetadata.xmp = parseXmp(sharpMetadata.xmp);
						} catch (err) {
							logger.warn(`Couldn't extract XMP data from file`);
							logger.warn(err);
						}
					}

					if (fullMetadata?.iptc?.['Caption'] && typeof fullMetadata.iptc['Caption'] === 'string') {
						metadata.description = fullMetadata.iptc?.['Caption'];
					}

					if (fullMetadata?.iptc?.['Headline'] && typeof fullMetadata.iptc['Headline'] === 'string') {
						metadata.title = fullMetadata.iptc['Headline'];
					}

					if (fullMetadata?.iptc?.['Keywords']) {
						metadata.tags = fullMetadata.iptc['Keywords'] as string;
					}

					if (allowList === '*' || allowList?.[0] === '*') {
						metadata.metadata = fullMetadata;
					} else {
						metadata.metadata = pick(fullMetadata, allowList);
					}

					// Fix (incorrectly parsed?) values starting / ending with spaces,
					// limited to one level and string values only
					for (const section of Object.keys(metadata.metadata)) {
						for (const [key, value] of Object.entries(metadata.metadata[section])) {
							if (typeof value === 'string') {
								metadata.metadata[section][key] = value.trim();
							}
						}
					}

					resolve(metadata);
				})
			);
		});
	}
```

In this method `ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION` is not used at all. Here is the main problem in my case. Can you initialize sharp here as you did it in `AssetsService`:

```ts
sharp({
  limitInputPixels: Math.pow(env['ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION'], 2),
   sequentialRead: true,
  failOn: env['ASSETS_INVALID_IMAGE_SENSITIVITY_LEVEL'],
})
```

**Comment by rijkvanzanten** [comment]
Oh! Good find @AndriyAntonenko! Wanna open a PR to resolve that? Should be an easy fix 🙂

**Comment by AndriyAntonenko** [comment]
@rijkvanzanten sure, I would like to contribute. Can I add you ass a reviewer when PR is ready?

**Comment by AndriyAntonenko** [comment]
@rijkvanzanten I've added the [PR](https://github.com/directus/directus/pull/23064), could you review it pls when you have time?
