### ISSUE TITLE
Images served from the /assets endpoint lose their color when parameters such as `?width=200` are used

### ISSUE THREAD

**Issue by LasseRosenow** [directus/directus#21008]
### Describe the Bug

I just updated to the newest directus version and suddenly newly uploaded images become black and white and lose all their colors.

### To Reproduce

1. Upload a new image ... In my case it is a large image with around 4000*2000px. (Old images are usually not affected as their optimizations are cached)
2. Open the image in the browser and apply a parameter such as `?width=200` 
3. You will get an image that has no colors.

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
What's the affected image type? Would you be able to share such an image?

**Comment by LasseRosenow** [comment]
Of course.

The normal image:
https://admin.cpe-bach-chor.de/assets/94611410-9a05-461c-a6d6-773a99e039e9

The image after having a `width` parameter applied:
https://admin.cpe-bach-chor.de/assets/94611410-9a05-461c-a6d6-773a99e039e9?width=2000

**Comment by paescuj** [comment]
Thanks!

Hmm, looks similar to https://github.com/lovell/sharp/issues/3929 although the original seems to be an JPEG, right?

**Comment by rijkvanzanten** [comment]
This seems to have been resolved in the meantime. Pulling up the example images seems to look good now 🙂
