### ISSUE TITLE
Custom Delete Permissions work on Bulk but not Single Item

### ISSUE THREAD

**Issue by w0kyj** [directus/directus#21009]
### Describe the Bug

Setting a collection custom delete permission enables the delete operation on Bulk actions, but "Not Allowed" delete button on item edit page.

### To Reproduce

- New or existing collection
- New or existing role
    - add a custom delete permission on a collection
        - eg status equals inactive
- Login with User (role above)
- Navigate to collection and check one or more items
    - note Delete button active and user can delete allowed records (NOTE error will occur on action if one or more records not allowed by custom rule)
- Open one of the items that user should be allowed to delete
    - The Delete button shows gray and "Not Allowed" on hover

https://www.loom.com/share/59f7dda1c0484fe98f1131c347f8878c?sid=3af263b0-1419-4c65-9a6b-60d2158c9701

### Directus Version

v10.8.2

### Hosting Strategy

Directus Cloud

**Comment by br41nslug** [comment]
After some testing on the `main` branch this issue was solved by #21152 (great job @paescuj 🎉)
