### ISSUE TITLE
Unexpected early exit (code 13) when trying to run npx directus <command>

### ISSUE THREAD

**Issue by miagg** [directus/directus#21029]
### Describe the Bug

Sometimes when running `npx directus ...` to trigger a cli command the script exits without any error message.
This causes CI/CD pipelines to fail because of the exit code.
It seems to happen randomly (~1/10 chances) or more frequently if I run immediately after `npm install`.

I tried switching to `./node_modules/.bin/directus command` to check for npx issues but it does not solve the issue.

This has never occurred before. I'm pretty sure it has something to do with version checking since it started happening when 10.8.3 was released.

Any clues?

### To Reproduce

On a Ubuntu LTS 22.04 machine, cd into a self-hosted directus folder and run:
`npm install` followed by `npx directus help`.

It should fail with exit code 13. If not give it some more tries as shown on this video.

https://github.com/directus/directus/assets/6439071/e686c018-b3ae-470e-9728-8ee4e6da99b0

### Directus Version

10.6.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
Fixed via #20693, released in [v10.8.3](https://github.com/directus/directus/releases/tag/v10.8.3).
