### ISSUE TITLE
Having two different Directus instances open in the same browser causes authentication issues

### ISSUE THREAD

**Issue by Andersang** [directus/directus#21027]
### Describe the Bug

I have two Directus containers running at the same time for different projects, on different ports, directories, using different KEY and SECRET variables, using entirely different databases. The only similarity to both projects is that they share the same administration email. I have tried shifting one of the instances to a different server, and found no difference in the result.

If I am logged in to either Directus instance, I would be unable to login to the other if I use the same browser for both. Running each instance in different incognito browser windows allows me to login to both at the same time. 

### To Reproduce

Run two completely different directus instances sharing the same admin email and try to login to both of them with the same non-incognito browser window. 

### Directus Version

10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Make sure one instance is not overwriting the others refresh token cookie if they're running them from the same domain `REFRESH_TOKEN_COOKIE_NAME`.

https://docs.directus.io/self-hosted/config-options.html#security
