### ISSUE TITLE
Block editor doesn't detect cutting of existing paragraph and doesn't save it either.

### ISSUE THREAD

**Issue by RonaldKools** [directus/directus#21031]
### Describe the Bug

See the attached video. If you select and cut a paragraph in the blockeditor, the editor doesn't detect the change so the save button stays disabled. See: 
https://github.com/directus/directus/assets/15251435/acc951a2-f7f6-4d5a-807f-ffd5f9349ef5

Additional info: 
- When you cut 2 or more paragraphs it does detect a change and saving is enabled.
- When you manually add and remove a character you can continue to save, but if you don't touch this block editor field at all, your changes are also not saved to the database.

### To Reproduce

- Create a simple collection with 1 input field called Tilte and 1 field called Bodytext that uses the block editor interface.
- Fill in some text in the Title field
- Fill in some text in 1 paragraph in the Bodytext field (block editor)
- Save.
- Reopen.
- Click in the Bodytext field and do CTRL A (select all text) followed by CTRL C (cut all text)

> Save is still disabled, focussing on other fields does not help either. 

- Click in the Title field and add some text.

> Save is now enabled.

- Save.
- Reopen.

> Title is save, but the paragraph you cut away is still there.

### Directus Version

v10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by RonaldKools** [comment]
Video showing the save issue:

https://github.com/directus/directus/assets/15251435/19a4729f-831a-4b29-9b61-639d44c0745d

**Comment by paescuj** [comment]
This is fixed in [v10.8.3](https://github.com/directus/directus/releases/tag/v10.8.3) 👍 
In fact this release contains several improvements to the block editor interface:

- #20733
- #19634
- #20524

**Comment by RonaldKools** [comment]
Aaaah I checked the changelog but missed that. Perfect, we plan to update next week. ;-)

Thanx @paescuj !

**Comment by paescuj** [comment]
> Aaaah I checked the changelog but missed that. Perfect, we plan to update next week. ;-)
> 
> Thanx @paescuj !

Awesome! You're welcome!
