### ISSUE TITLE
Many-to-one not showing anything

### ISSUE THREAD

**Issue by horngperng-pxs** [directus/directus#2103]
## Version Info
  - Directus version and branch (Or commit hash): #2094 
  - PHP version: 7.2.3
  - MySQL version: 5.7.21
  - Web server: Apache
  - OS name and version: ubuntu0.16.04.1

I created two tables pages and subpages where one page has many subpages.
In the subpages table, I created a many-to-one column that refers to the pages table.

When I come to add a subpage, the clients input seems to show <option>s for each parent(linked to page) but doesn't actually have any text within the element??

i saw this solution online https://github.com/directus/directus/commit/b3441fafb964371599eb0e4f5ca9d20ca7dfb689 , but the folder structure seems to be different...

<img width="798" alt="screen shot 2018-03-20 at 10 04 32 pm" src="https://user-images.githubusercontent.com/32503897/37661257-5a98ef5e-2c8f-11e8-8602-9e01a764cb79.png">

**Comment by rijkvanzanten** [comment]
Hey @horngperng-pxs! Have you entered the correct values in the `visible columns` and `visible columns template` interface options?

**Comment by rijkvanzanten** [comment]
Just to make sure, could you checkout [the article I wrote on setting up relationships](https://medium.com/directus/understanding-relationships-it-isnt-complicated-35e0dcf78450) to check if it matches 🙂?

> my pages table got a title

So your visible columns would be set to something like `title,id` with your visible columns template `{{ title }} ({{id}})` or something similar to render the data

**Comment by horngperng-pxs** [comment]
Thank rijk! its my own mistake, the visible columns should be title instead of Title... my bad..

**Comment by rijkvanzanten** [comment]
Glad you figured it out 😄!
