### ISSUE TITLE
encountering a problem while using M2M (Many-to-Many) relationships.

### ISSUE THREAD

**Issue by Bamschool** [directus/directus#21037]
### Describe the Bug

Hello! I'm encountering a problem while using M2M (Many-to-Many) relationships. My filtering URL is: http://localhost:8055/items/user/(uid)?fields=name,email,point_sentence,solved_problem.korean_sentence_listview_exerciseId.date. I have a table named user and a field called korean_sentence_listview. Since these have a Many-to-Many relationship, they are connected through user_korean_sentence_listview. 

What I'm trying to do is when I access the URL http://localhost:8055/items/user/(uid)?fields=name,email,point_sentence,solved_problem.korean_sentence_listview_exerciseId.date, I get an output like this:

{
    "data": {
        "name": "jjjjj",
        "email": "email@gmail.com",
        "point_sentence": 140,
        "solved_problem": [
            {
                "korean_sentence_listview_exerciseId": {
                    "date": "2024-01-07"
                }
            },
            ... [other date entries] ...
            {
                "korean_sentence_listview_exerciseId": {
                    "date": "2024-01-11"
                }
            }
        ]
    }
}

<img width="867" alt="스크린샷 2024-01-11 오전 9 50 09" src="https://github.com/directus/directus/assets/87596687/fedcaa10-c809-4ca0-9fde-090e05ab5a37">

<img width="1092" alt="스크린샷 2024-01-11 오전 9 49 31" src="https://github.com/directus/directus/assets/87596687/66c935f0-01c7-45d7-bf87-12b88e30669a">

What I want is to filter these results to show only the dates within January. I tried using the between method and spent hours looking through documentation, but I couldn't succeed. Could you please guide me on how to achieve this? Thank you!

### To Reproduce

m2m relationship query working 

### Directus Version

10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
https://docs.directus.io/reference/query.html#functions

For community questions or support feel free to join our discord server https://discord.com/channels/725371605378924594/1019641731332976722
