### ISSUE TITLE
Selecting archive field not persisting

### ISSUE THREAD

**Issue by u12206050** [directus/directus#21041]
### Describe the Bug

![archive-field](https://github.com/directus/directus/assets/6641242/32f8f1e4-faa2-473a-8ff8-8453378148c4)

When creating the collection we didn't have a status field at first, but then added it later and then want to enable archive functionality.
We are able to select a field to use for archive, but after saving, it seems to just be removed and doesn't take affect.

### To Reproduce

Create a new collection without status field.
Then create new status field
Add some items with various status including "archive" on some (not sure if this has an impact)
Then edit the collection and select the status field as the archive field and save.
Edit the collection to notice the archive field is empty again

### Directus Version

10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
This was resolved in #20949 and will be fixed in the next release
