### ISSUE TITLE
Unable to delete users

### ISSUE THREAD

**Issue by ksraghavendra** [directus/directus#2104]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus version and branch (Or commit hash): latest
  - PHP version: 7.1.13
  - MySQL version: 
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: Debian 4.9.65

## Expected Behavior
Upon deleting users, the user should be removed.

## Actual Behavior
Deleting users, removes the user but on refreshing the users page, they appear again.

**Comment by rijkvanzanten** [comment]
Hey @ksraghavendra!

I can't seem to reproduce this issue on my latest install.. 

Do you have some more specific information we can use to reproduce this issue? What browser / how did you install / any errors in api/logs / any errors in the devtools etc

**Comment by WellingGuzman** [comment]
@ksraghavendra how are you trying to delete users? using the API or the web app?

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/40)
