### ISSUE TITLE
Error displayed on user page

### ISSUE THREAD

**Issue by phongXEM** [directus/directus#21040]
### Describe the Bug

Columns are displayed in incorrect order
<img width="858" alt="Screenshot at Jan 11 16-39-46" src="https://github.com/directus/directus/assets/141018948/94d623f1-5e88-472c-a7a6-4f7b3d75149c">
<img width="853" alt="Screenshot at Jan 11 16-40-13" src="https://github.com/directus/directus/assets/141018948/b9b86aaa-a69f-45bf-8acb-2310be2c6434">

### To Reproduce

collection directus_user cant edit. How to display it in the correct order in page detail user.

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
This was addressed in https://github.com/directus/directus/pull/20910 and will be available on the next release :)
