### ISSUE TITLE
Toggle nav on click

### ISSUE THREAD

**Issue by cosmincelea** [directus/directus#21045]
### Describe the Improvement

I think it would be nice to be able to toggle the sidebar nav of modules.

Hei,

Sorry for being unclear, so when i click on the content module for the navigation then to the right, a submenu with the content collections opens, and there is not way to close that sub menu.
For me it was for example annoying when opening a collection with the map layout. I would like to only see the map and the module nav not also all the collection from the submenu.
PS. I have also made a PR.
I have also attached a print screen.

![Screenshot 2024-01-11 at 15 04 24](https://github.com/directus/directus/assets/15088090/64da0d97-2387-4c74-86af-e874c3fa013c)

**Comment by br41nslug** [comment]
How do you mean "toggle the sidebar"? What would you toggle 🤔 there is not much to collapse in the module sidebar.

Please elaborate on the description or create a [Feature Request](https://github.com/directus/directus/discussions/new?category=feature-requests)

**Comment by paescuj** [comment]
As outlined in https://github.com/directus/directus/pull/21050#issuecomment-1889647266 this should be filed as a  [Feature Request](https://github.com/directus/directus/discussions/new?category=feature-requests). Thank you!
