### ISSUE TITLE
extension [RollupError]

### ISSUE THREAD

**Issue by Bamschool** [directus/directus#21054]
### Describe the Bug

Hi! I got the error when I excute npm run build in extension. I don't know why.. it worked before well.

choejonghwan@choejonghwan-ui-MacBookPro directus-extension-saved_problem % 
<img width="389" alt="스크린샷 2024-01-12 오전 9 03 40" src="https://github.com/directus/directus/assets/87596687/1e924c4f-563b-4e38-9c53-c11d8964f5e9">

 *  복원된 기록 

choejonghwan@choejonghwan-ui-MacBookPro directus-extension-saved_problem % npm run build

> directus-extension-saved_problem@1.0.0 build
> directus-extension build

✖ Failed
[RollupError] Could not resolve "./src/saved_problem/index.js" from "virtual:entry"

virtual:entry
RollupError: Could not resolve "./src/saved_problem/index.js" from "virtual:entry"
    at error (file:///Users/choejonghwan/Downloads/directus_admin-main/node_modules/@directus/extensions-sdk/node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/choejonghwan/Downloads/directus_admin-main/node_modules/@directus/extensions-sdk/node_modules/rollup/dist/es/shared/node-entry.js:23979:24)
    at file:///Users/choejonghwan/Downloads/directus_admin-main/node_modules/@directus/extensions-sdk/node_modules/rollup/dist/es/shared/node-entry.js:23941:26
choejonghwan
<img width="457" alt="스크린샷 2024-01-12 오전 9 36 09" src="https://github.com/directus/directus/assets/87596687/58ebd4a3-5e44-4ea0-8647-abc2371739ee">

<img width="371" alt="스크린샷 2024-01-12 오전 9 34 40" src="https://github.com/directus/directus/assets/87596687/6d03f17e-b0bf-432b-9a7d-178d5a97766d">
@choejonghwan-ui-MacBookP
folder 
### To Reproduce

it should work well in extension

### Directus Version

10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Do you have the latest version of the `@directus/extensions-sdk` dependency installed?
You can check that by running `npm outdated`.
Would you mind sharing your `package.json` file?

**Comment by Bamschool** [comment]
Hi thank you so much for replying!  
I just updated from 10.2.0 to 10.3.0. but it still doesn't work :)  pacakage.json: {
  "name": "admin",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "directus-extension build"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "directus": "^10.8.2",
    "pg": "^8.11.3"
  }
}
 in extension package.json {
	"name": "directus-extension-saved_problem",
	"version": "1.0.0",
	"type": "module",
	"description": "Please enter a description for your extension",
	"icon": "extension",
	"directus:extension": {
		"host": "^10.2.0",
		"type": "bundle",
		"path": {
			"app": "dist/app.js",
			"api": "dist/api.js"
		},
		"entries": [
			{
				"type": "endpoint",
				"name": "saved_problem",
				"source": "src/saved_problem/index.js"
			}
		]
	},
	"keywords": [
		"directus",
		"directus-extension",
		"directus-custom-bundle"
	],
	"scripts": {
		"build": "directus-extension build",
		"dev": "directus-extension build -w --no-minify",
		"link": "directus-extension link",
		"add": "directus-extension add"
	},
	"devDependencies": {
		"@directus/extensions-sdk": "^10.3.0"
	}
}

**Comment by paescuj** [comment]
Thanks @Bamschool!

Can you check whether the file at `src/saved_problem/index.js` actually exists inside your extension?
I tried to reproduce it and I get the same error when I delete the file:
```console
❯ npm run build

> directus-extension-my-bundle@1.0.0 build
> directus-extension build

✔ Done
❯ rm src/saved_problem/index.js 
❯ npm run build

> directus-extension-my-bundle@1.0.0 build
> directus-extension build

✖ Failed
[RollupError] Could not resolve "./src/saved_problem/index.js" from "virtual:entry"
```

**Comment by Bamschool** [comment]
@paescuj 
wow... I just feel like I am so fool. 

thank you so much! it's working well!! 

have a good day!!

**Comment by paescuj** [comment]
No worries, happens to the best 😄 

Thank you, likewise!
