### ISSUE TITLE
Nestable Folder not supported 

### ISSUE THREAD

**Issue by MengdanCode** [directus/directus#2105]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus version and branch (Or commit hash): 6.4.8
  - PHP version: 7.2.1
  - MySQL version: 5.6.38
  - Web server: Apache
  - OS name and version: MacOS 10.13.3

## Expected Behavior
From the documentation( https://docs.getdirectus.com/6.4.0/#File_Library) there is a nestable folder feature supported in Directus. 

## Actual Behavior
No Nestable folder button found 

## Steps to Reproduce
 1. 
 2. 
 3.

**Comment by WellingGuzman** [comment]
Hey @MengdanCode, this was planned for 6.4 but it ended up being under development for 7.x.

As this is being under development I will close this ticket.
