### ISSUE TITLE
Data Model: Archive Field and Sort Field not selected when edit collections

### ISSUE THREAD

**Issue by tinhXEM** [directus/directus#21059]
### Describe the Bug

Data Model: Archive Field and Sort Field not selected when edit collections

If a collection has Status Field or Sort Field, every time click detail to edit model. The Archive Field and Sort Field not keep lastest value (they always return null value).

### To Reproduce

1. Go to [Settings -> Data Model](https://soc.socjsc.com/admin/settings/data-model)
2. Click a collection which has Status Field or Sort Field
3. Scroll down and check Archive Field and Sort Field (not selected latest value)

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
This was resolved in https://github.com/directus/directus/pull/20949 and will be fixed in the next release
