### ISSUE TITLE
Rollback Button not found in UI

### ISSUE THREAD

**Issue by MengdanCode** [directus/directus#2106]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus version and branch (Or commit hash): 6.4.8
  - PHP version: 7.2.1
  - MySQL version: 5.6.38
  - Web server: Apache
  - OS name and version: MacOS 10.13.3

## Expected Behavior
From the documentation( https://docs.getdirectus.com/6.4.0/#Item_Detail), Rollback feature is supported in Directus. 

## Actual Behavior
No Rollback button found 

## Steps to Reproduce
 1. 
 2. 
 3. 

## Schema Dump, Logs, or Screenshots

**Comment by WellingGuzman** [comment]
Hey @MengdanCode, this was initially planned for 6.4 but it didn't made the cut. This is being under development for Directus 7.0
