### ISSUE TITLE
Sdk schema type inference not working for `readItem` or `readItems`

### ISSUE THREAD

**Issue by mattiaz9** [directus/directus#21063]
### Describe the Bug

Sdk type inference does not work for `readItem` or `readItems`, but only for `readSingleton`.

For instance this gives the error: `Argument of type 'string' is not assignable to parameter of type 'never'`:
```ts
interface DirectusSchema {
  example: {
    id: string;
  };
}

const directusClient = createDirectus<DirectusSchema>(
  "http://localhost:8055",
).with(rest());

const result = await directusClient.request(readItems("example"))
```

but this does not:
```ts
const result = await directusClient.request(readSingleton("example"))
```

### To Reproduce

I made a small sandbox:
https://codesandbox.io/p/devbox/lldd35

### Directus Version

v14.0.0 (sdk)

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
Hey, thanks for opening the issue!

Your current schema describes a singleton collection. To describe a collection with multiple items, the corresponding type needs to be an array:
```ts
interface DirectusSchema {
  // singleton
  example: {
    id: string;
  };

  // normal collection
  example: {
    id: string;
  }[];
}
 ```

On a little side note, the SDK requires TypeScript v5 [^1] - I've noticed you're using TypeScript v4 in the provided CodeSandbox.

[^1]: https://docs.directus.io/guides/sdk/getting-started.html#basic-usage

**Comment by mattiaz9** [comment]
thank you @paescuj!
I fixed the schema as you said and that works, but I'm having some other issues now.

I updated the sandbox: https://codesandbox.io/p/devbox/lldd35.
Basically I can't select fields for the `photo` column, but when I remove the field `translations` from `TeamMeber` then it works.

Am I missing something else?

**Comment by paescuj** [comment]
You're welcome @mattiaz9! I'm glad it works so far.

> I updated the sandbox: https://codesandbox.io/p/devbox/lldd35.
> Basically I can't select fields for the photo column, but when I remove the field translations from TeamMeber then it works.
>
> Am I missing something else?

This looks like a bug to me. Could you open a new issue for this? https://github.com/directus/directus/issues/new?assignees=&labels=&projects=&template=bug_report.yml
