### ISSUE TITLE
Cannot run using podman

### ISSUE THREAD

**Issue by jazoom** [directus/directus#21064]
### Describe the Bug

This is the error message:

Error: Cannot find module '/directus/cli.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

### To Reproduce

podman run --rm \
--name directus \
-p 8055:8055 \
-v $HOME/directus:/directus \
-e KEY="sdafs" \
-e SECRET="asdf" \
-e ADMIN_EMAIL="a@example.org" \
-e ADMIN_PASSWORD="adsf" \
-e DB_CLIENT="pg" \
-e DB_HOST="a.supabase.co" \
-e DB_DATABASE="postgres" \
-e DB_PORT="5432" \
-e DB_USER="postgres" \
-e DB_PASSWORD="sdfafd" \
-e WEBSOCKETS_ENABLED=true \
directus/directus:10.8.3

### Directus Version

10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Hey @jazoom!
The issue lies within the following line:
```
 -v $HOME/directus:/directus 
```

With that, you're effectively overriding the whole `/directus` directory inside the container in which the application lives.
Please follow our Docker Guide [^1] to see how to correctly configure the volumes.

[^1]: https://docs.directus.io/self-hosted/docker-guide.html

**Comment by jazoom** [comment]
Ah right. I'm used to other containers not putting application files in the same directory as data. My mistake. Thanks for taking the time to set me straight.

**Comment by jazoom** [comment]
@paescuj 

FYI it still doesn't work in podman.

If I use:
```
-v $HOME/directus/database:/directus/database \
-v $HOME/directus/uploads:/directus/uploads \
-v $HOME/directus/extensions:/directus/extensions \
```

This is the error message:

```
ERROR: Extension folder "/directus/extensions/interfaces" couldn't be opened
    err: {
      "type": "Error",
      "message": "Extension folder \"/directus/extensions/interfaces\" couldn't be opened",
      "stack":
          Error: Extension folder "/directus/extensions/interfaces" couldn't be opened
              at ensureExtensionDirs (file:///directus/node_modules/.pnpm/file+packages+extensions_@unhead+vue@1.8.9_knex@3.1.0_mysql@2.18.1_pg@8.11.3_pinia@2.1.7_pino_rwyql3f2zfhcsyunnc4cwmipb4/node_modules/@directus/extensions/dist/node.js:11:13)
              at async ExtensionManager.load (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.9_pinia@2.1.7_typescript@5.3.3_vue@3.3.13/node_modules/@directus/api/dist/extensions/manager.js:138:13)
              at async ExtensionManager.initialize (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.9_pinia@2.1.7_typescript@5.3.3_vue@3.3.13/node_modules/@directus/api/dist/extensions/manager.js:124:13)
              at async loadExtensions (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.9_pinia@2.1.7_typescript@5.3.3_vue@3.3.13/node_modules/@directus/api/dist/cli/load-extensions.js:17:5)
              at async createCli (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.9_pinia@2.1.7_typescript@5.3.3_vue@3.3.13/node_modules/@directus/api/dist/cli/index.js:20:5)
    }
```

It works if I remove the extensions volume and just use:
```
-v $HOME/directus/database:/directus/database \
-v $HOME/directus/uploads:/directus/uploads \
```

**Comment by paescuj** [comment]
> @paescuj
> 
> FYI it still doesn't work in podman.
> 
> If I use:
> 
> ```
> -v $HOME/directus/database:/directus/database \
> -v $HOME/directus/uploads:/directus/uploads \
> -v $HOME/directus/extensions:/directus/extensions \
> ```
> 
> This is the error message:
> 
> ```
> ERROR: Extension folder "/directus/extensions/interfaces" couldn't be opened
>     err: {
>       "type": "Error",
>       "message": "Extension folder \"/directus/extensions/interfaces\" couldn't be opened",
>       "stack":
>           Error: Extension folder "/directus/extensions/interfaces" couldn't be opened
>               at ensureExtensionDirs (file:///directus/node_modules/.pnpm/file+packages+extensions_@unhead+vue@1.8.9_knex@3.1.0_mysql@2.18.1_pg@8.11.3_pinia@2.1.7_pino_rwyql3f2zfhcsyunnc4cwmipb4/node_modules/@directus/extensions/dist/node.js:11:13)
>               at async ExtensionManager.load (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.9_pinia@2.1.7_typescript@5.3.3_vue@3.3.13/node_modules/@directus/api/dist/extensions/manager.js:138:13)
>               at async ExtensionManager.initialize (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.9_pinia@2.1.7_typescript@5.3.3_vue@3.3.13/node_modules/@directus/api/dist/extensions/manager.js:124:13)
>               at async loadExtensions (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.9_pinia@2.1.7_typescript@5.3.3_vue@3.3.13/node_modules/@directus/api/dist/cli/load-extensions.js:17:5)
>               at async createCli (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.9_pinia@2.1.7_typescript@5.3.3_vue@3.3.13/node_modules/@directus/api/dist/cli/index.js:20:5)
>     }
> ```
> 
> It works if I remove the extensions volume and just use:
> 
> ```
> -v $HOME/directus/database:/directus/database \
> -v $HOME/directus/uploads:/directus/uploads \
> ```

You need to ensure the container has write access to the `extensions` volume.

**Comment by paescuj** [comment]
Our Docker image runs as user `node` for security reasons.
You need to ensure that user has write access to your directories, either via ownership (UID 1000, GID 1000) or via permissions for "others".
If you run Podman in rootless mode, you may need to configure the correct user mapping: https://www.redhat.com/sysadmin/rootless-podman-user-namespace-modes

**Comment by jazoom** [comment]
Okay. Perhaps you need to document that you're forcing the user to be `node` rather than simply using the one which ran the container?
