### ISSUE TITLE
Added items not showing in the table list screen

### ISSUE THREAD

**Issue by biznlinks** [directus/directus#2107]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus version and branch (Or commit hash): latest
  - PHP version: 7.1.13
  - MySQL version: 
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: Linux

## Expected Behavior
Upon adding items, items are then shown in the list, when click on table.

## Actual Behavior
Shows "Nothing to see here", even though it says 2 loaded items in the search/filter menu 

## Steps to Reproduce
 1. Add item via form
 2. Click on tables, "Tasks" to review list
 3. Checked the Network tab in Chrome, data is actually retrieved but page is not updated.

## Schema Dump, Logs, or Screenshots

<img width="1460" alt="screen shot 2018-03-21 at 4 18 45 pm" src="https://user-images.githubusercontent.com/22963787/37738050-bfd393e4-2d23-11e8-8072-04ae2dfc1323.png">

**Comment by WellingGuzman** [comment]
Hey @biznlinks does this table has status interface? can you share the schema you are using?

**Comment by biznlinks** [comment]
@WellingGuzman  please see the attached schema.

Regards,

<img width="1458" alt="screen shot 2018-03-25 at 4 01 54 pm" src="https://user-images.githubusercontent.com/22963787/37879918-e94c6c9e-3045-11e8-8011-7e344bda0db6.png">

**Comment by WellingGuzman** [comment]
@biznlinks, is the primary key string or numeric? can you share a mysql dump that we can use to reproduce this issue?

**Comment by WellingGuzman** [comment]
@biznlinks I am unable to reproduce this issue, using the database dump you shared. Can you try clearing your browser cache? sometimes that helps dealing with client side issues like this.

**Comment by americanblond** [comment]
The same issue. When you setup some schema for table and then (for example) you wanna to add some column, you wouldn't see any updates on table list bookmark. I have already tried on all browsers - reproduces well.

**Comment by americanblond** [comment]
Ok. I have found it :) After adding a new column you should activate it like on image. Not very user friendly.
![solution](https://user-images.githubusercontent.com/3984116/40975444-ac7b6a88-68d3-11e8-8710-ee5618c0b264.png)

**Comment by rijkvanzanten** [comment]
Hey @americanblond!

What would you suggest is the best user flow in this case? I'm working on the next major version of the platform and like to get this right in there 🙂 

We save the view options to the DB, so the screen looks the same the way you left it last. However, if you view the page and add a new column, it still retrieves the old saved settings, which don't include the new column...... I'm not sure if it makes sense to force add the new column to everyones view preferences whenever a new column is created seeing not every user might want that... 🤔 🤔 🤔 

What are your thoughts on this? 🙂

**Comment by rijkvanzanten** [comment]
I'll close this as it's not so much a technical error, but a poorly designed user interaction

**Comment by americanblond** [comment]
Hey,

I think that the best way will be if you change icon "i". This icon, as for
me, more looks like a "help" icon :)

Br

вт, 5 июня 2018 г., 20:56 Rijk van Zanten <notifications@github.com>:

**Comment by benhaynes** [comment]
To me, `?` is for help and `i` is for information. The right sidebar gives more context/info on the current page so it makes sense. We're using the Material Design icon set in v7, so if anyone has a better icon choice we'd love to hear!

https://www.google.com/design/icons/

**Comment by americanblond** [comment]
In previous version you have something like gear icon. As for me it was
more better. Thanks)

чт, 7 июня 2018 г., 0:36 Ben <notifications@github.com>:
