### ISSUE TITLE
Breaking changes in new `@directus/env` package

### ISSUE THREAD

**Issue by paescuj** [directus/directus#21086]
The new `@directus/env` package (unreleased) comes with a few backwards-incompatible changes which we need to sort out before the next release.

### Variables Loading

Previously, all variables were passed-through to the final `env` result. The list of allowed keys was only used for `_FILE` variables: https://github.com/directus/directus/blob/0b0db0f4499b5337528e1c7088e34afb03add14f/api/src/env.ts#L502
In the new package, the allow list is used against all variables:
https://github.com/directus/directus/blob/ef0940c9409675abe9e948e5b1c75f8596beacda/packages/env/src/lib/create-env.ts#L21

This is an issue for "external" env variables which have been referenced in hooks / flows. Not sure if other places are affected as well.

We can see this issue in the following blackbox test: https://github.com/directus/directus/actions/runs/7523242983/job/20476365354#step:5:54

Possibilities I see:
- Revert back to previous behavior (#21084)
- Treat variables which are not in allow list separately and pass them to hooks / flows only (uncasted?)

### `_FILE` variables casting

Previously, `_FILE` envs used to be casted as well.
This is no longer the case in `@directus/env`.

Possibilities I see:
- Revert back to previous behavior (#21084)
- Keep new behavior but announce it as a breaking change

### ESM JS Config Files

In https://github.com/directus/directus/pull/19654 we added support for ESM (async) JS config files.
This won't work anymore in the new package:
https://github.com/directus/directus/blob/ef0940c9409675abe9e948e5b1c75f8596beacda/packages/env/src/utils/read-configuration-from-javascript.ts#L7

**Comment by br41nslug** [comment]
> Previously, all variables were passed-through to the final env result. The list of allowed keys was only used for _FILE variables

My 10 cents is that we should keep this logic same as it was. There are various usecases in flows and extensions where arbitrary ENV vars should be able to be loaded. This check was added to explicitly prevent Directus from trying to load arbitrary `*_FILE` variables on the system as files:
- for example `CA_CERT_FILE` from Apache which would be sensitive data
- this can also lead to high memory usage if these are big files that are unused by directus
- and to prevent errors for arbitrary environment variable that end in `_FILE` but do not actually point to a path to load the file from

**Comment by rijkvanzanten** [comment]
1 & 2 resolved! 3 is on purpose in prep for the env/config split, so we'll mark that in the breaking change announcements
