### ISSUE TITLE
VARCHAR default "0" resets to null

### ISSUE THREAD

**Issue by mdbarr73** [directus/directus#2108]
When saving a dropdown varchar column with default value of "0", the default value resets to null. Confirmed in dev tools, PUT request sends "0", response has null as default value.

## Version Info
  - Directus version and branch (Or commit hash): 6.4.7
  - PHP version: 7.1
  - MySQL version: Aurora MySQL 5.6.10a
  - Web server: Apache
  - OS name and version: Docker Directus

## Expected Behavior
With a "dropdown" varchar column, setting the default value to "0" (zero) should cause the column to always have a default value of 0.

## Actual Behavior
Setting the default value to "0", then reverts to null on refresh/save.

## Steps to Reproduce
 1. Create a dropdown column with type varchar
 2. Change default value to 0
 3. Save, check default value is null.

## Schema Dump, Logs, or Screenshots
![image](https://user-images.githubusercontent.com/30296775/37779229-48da51ac-2dc2-11e8-807d-2c235a078aa5.png)
![image](https://user-images.githubusercontent.com/30296775/37779240-5402c14a-2dc2-11e8-91af-ad13eb9be29e.png)

**Comment by WellingGuzman** [comment]
Hey @mdbarr73 does the column has `null` or `0` in the database? or is it only on displaying `NULL` on Directus?

**Comment by WellingGuzman** [comment]
Fixed by https://github.com/directus/directus/commit/e421072bbf9c48b91af56e22f97376ba32e7586b
