### ISSUE TITLE
Directus App filters for system collections based on name 'directus_*' instead of the 'system' property

### ISSUE THREAD

**Issue by wfriedman89** [directus/directus#21090]
### Describe the Bug

Tables can be added via Direct DB, custom extension etc. that are named 'directus_*' and those tables are recognized in the Directus app as system collections.

### To Reproduce

1. Add a table to the DB directly named 'directus_*'
2. You will see this table recognized as a system collection in the app

### Directus Version

v10.8.3

### Hosting Strategy

Directus Cloud

**Comment by rijkvanzanten** [comment]
I wouldn't be surprised if the `directus_` prefix is used for the same check API-side as well, so we should consider this a bug across the whole platform.

**Comment by br41nslug** [comment]
Correct this check is also done in the ItemsService (and thus it's inherited classes) which should also be replaced with the check against the `system` property instead.
