### ISSUE TITLE
Fix typo in Flows field reference

### ISSUE THREAD

**Issue by BI-MarcB** [directus/directus#21097]
### Describe the Request

On https://docs.directus.io/reference/system/flows.html there are references to a field "note". There is no such field in the API. This field is called "description". 
Also see https://github.com/directus/directus/blob/main/api/src/database/system-data/fields/flows.yaml 

### Maintainence Strategy

This is a change that updates out-of-date docs.

**Comment by phazonoverload** [comment]
Thanks for the report!
