### ISSUE TITLE
Import URL - not sanitised file names.

### ISSUE THREAD

**Issue by konradwww** [directus/directus#2110]
## Version Info
  - Directus version and branch (Or commit hash): 6.4.8
  - PHP version: 7.1.14
  - MySQL version: 5.7
  - Web server: Apache
  - OS name and version: Docker alpine:3.7

## Expected Behavior
If file imported from URL, the filename should not contain GET parameters.

## Actual Behavior
File imported from URL is saved with not sanitised filename.
`/9932b84ada4ac41fb8bf6734cd5dd33f.jpg?k=6&e=wwlxZTGtMyUVXbyf2t7pHThk3gGwtg4xcvl_u_egZoEVW63OutGElGnzP8_-LQet-aFBS09KODgT1fqb8X23e62g8qpvykVkKsB6gL-Ui1KamJM1ngLs_Arsx5mTtWSB
`

## Steps to Reproduce
 1. Use single_file interface
 2. Paste into import url for example: 
[https://media.gettyimages.com/photos/beautiful-architecture-and-interior-of-art-in-siena-duomo-one-of-the-picture-id934855464.jpg?qwertyqwerty]
 3.  Save it

**Comment by rijkvanzanten** [comment]
Thanks for the heads up @konradwww!

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/54a185535e92c3d8e32306311cc9dfa4171c3dc4
