### ISSUE TITLE
Accept invite need to return the user id.

### ISSUE THREAD

**Issue by Asteb612** [directus/directus#21106]
### Describe the Improvement

Currently a user invited via the directus app interface sends an email with a url in the format `/admin/accept-invite` and a token.
My current problem is that I can't fill in any other information such as first and last name when accepting the invitation.
So after entering a password, the user has to authenticate himself before I can change his details.
Because the only way to modify a user is with their username.

A modification that would avoid this would be to have the user ID as the return value of the `/users/invisponse/accept` endpoint. This modification can improve the user flow.

If you're ok with this modification i propose to do it.

**Comment by rijkvanzanten** [comment]
I'm not entirely sure what this would look like or how this tweak would solve for that. Mind opening [a new feature request](https://github.com/directus/directus/discussions/new?category=draft-feature-requests) instead? Thanks!
