### ISSUE TITLE
Delete many by query applies query limit

### ISSUE THREAD

**Issue by samlof** [directus/directus#21104]
### Describe the Bug

Deleting items with query doesn't delete everything because it applies the instances default limits and max query limits. Same problem from way before https://github.com/directus/directus/issues/6560 but with query and not keys.

### To Reproduce

- Have more than default limit items in collection
- Try to delete them using a query
- SanitizeQuery applies default limit, thus deletes only up to that many

### Directus Version

v10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Correct and these system wide default limits are very much by design, try adding `limit: -1` if you're trying to delete/fetch an unbounded amount of items. Or update the default limit to something more appropriate for the project. https://docs.directus.io/reference/query.html#limit

**Comment by samlof** [comment]
@br41nslug  could we get the query to return something useful then? If it returned the amount of items deleted could use it to loop until nothing deleted anymore. With get queries we can do pages and loop until get empty return. With delete cannot.
With as it is, first have to do GET or SEARCH queries to get all primary keys with the filter, then call delete with primary keys. Because the limit doesn't apply if deleting by keys, it only applies if deleting with filter.

`limit: -1` means can never use `QUERY_LIMIT_MAX` limit. Default limit just means it won't work when amounts grow bigger again.

**Comment by samlof** [comment]
I went for other way of limit: 200 and batch my calls into targeting 200 per call.
