### ISSUE TITLE
Unnecessary fetches using Base64

### ISSUE THREAD

**Issue by Fusseldieb** [directus/directus#21118]
### Describe the Bug

<img src="https://github.com/directus/directus/assets/4715129/78b23a21-1a02-40cf-b213-eac288d88559" height="400px">

As seen in the image above, when listing a table with a user shown, it loads the image one after another, pretty slowly, and this is exacerbated when the ping is high (>=250ms).

After a quick look into the code it looks like it is loaded using Base64, over and over. Wouldn't it be considerably faster if fetched directly using the image endpoint? That way, the browser would understand that the same image is being fetched again and would display them all at once.

Cheers!

### To Reproduce

1. Use a high latency connection
2. View a table with "User Created" or similar

### Directus Version

10.8.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
This was originally implemented as base64 to avoid CORS issues and having to have the access_token directly in the asset URL. This will be resolved in the future with an authentication update.
