### ISSUE TITLE
I don't know how to run Directus in the background of a Windows computer without installing Docker.

### ISSUE THREAD

**Issue by coderyqy** [directus/directus#21125]
### Page

https://docs.directus.io/getting-started/quickstart.html

### Describe the Inaccuracy

I don't know how to run Directus in the background of a Windows computer without installing Docker.
I am currently using the npx directus start command to run it. When I close the terminal, the directory project also stops.
 I want to know how to run it in the background without using Docker.
```js
npx directus start
```

**Comment by Pachat** [comment]
Use pm2

**Comment by phazonoverload** [comment]
Running background processes with Node.js is not a Directus-specific piece of knowledge, and given that we highly encourage the use of Docker, I don't see us embellishing the Node.js path with much more information at this time.
