### ISSUE TITLE
Field conditions do not allow to write a string like $CURRENT_ROLE.name

### ISSUE THREAD

**Issue by jcostasilva** [directus/directus#21135]
### Describe the Bug

When we use the raw editor for writing a condition, it parses and changes the input. One consequence is that a string like $CURRENT_ROLE.name is not possible to use as the name of a property. The editor automatically creates an inner object $CURRENT_ROLE: { "name": etc }. Because of this, $CURRENT_ROLE and $CURRENT_USER are not replaced by the true values and the condition does not work.

### To Reproduce

Try to set a condition like: 
{
	"_and": [
		{
			"$CURRENT_ROLE": {
				"_eq": "e0a89954-59e1-4e05-8413-30eb4626868c"
			}
		}
	]
}

It doesn't work.

But go to the database and replace by:

{
	"_and": [
		{
			"$CURRENT_ROLE.id": {
				"_eq": "e0a89954-59e1-4e05-8413-30eb4626868c"
			}
		}
	]
}

Now it works.

### Directus Version

v10.8.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by jcostasilva** [comment]
BTW, I guess this is because:

  149  		const extractPermissionData = (val: any) => {
  150: 			if (typeof val === 'string' && val.startsWith('$CURRENT_USER.')) {
  151: 				requiredPermissionData.$CURRENT_USER.push(val.replace('$CURRENT_USER.', ''));
  152  				containDynamicData = true;

The string must end with a '.' -> 'CURRENT_USER.'

**Comment by HKMANOJ** [comment]
Can i work on this issue

**Comment by connorwinston** [comment]
Heyo! This wasn't working for you because that is not how you use the dynamic variables when filtering. The dynamic variables are meant to be used after the operand. See the example below, please let me know if you have any questions. I am going to close this issue out for now.

```json
{
    "user_created": {
        "_eq": "$CURRENT_USER"
    }
}
```

```json
{
    "user_created": {
        "role": {
            "name": {
                "_eq": "$CURRENT_USER.role.name"
            }
        }
    }
}
```
