### ISSUE TITLE
Bad redirection during install

### ISSUE THREAD

**Issue by Namide** [directus/directus#2113]
## Version Info
  - Directus version and branch : master, build and develop
  - PHP version: 7.0.10
  - MySQL version: ---
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: Windows 10 (WAMPSERVER 3.0.6)

## Expected Behavior

Installation of Directus

## Actual Behavior

Bad redirection from http://localhost/inspire/back/ to http://localhost/pire/back/installation/index.php?step=0 (Not Found)

## Steps to Reproduce

 1. Use an alias with WAMP (Alias /inspire "[...]/inspire")
 2. Add a subdirectory /inspire/back with the files of Directus and run `composer install` in this subdirectory
 3. Go to the subdirectory with the URL http://localhost/inspire/back/, a redirection will change the URL on the bad request http://localhost/pire/back/installation/index.php?step=0
> **inspire** changed to  **pire**

## Finally

The alias http://localhost/pire don't exist so an error page will display :
```
Not Found
The requested URL /pire/back/installation/index.php was not found on this server.

Apache/2.4.23 (Win64) PHP/7.0.10 Server at localhost Port 80
```
And I can't install Directus.

Anyone has an idea about this strange redirection?

**Comment by WellingGuzman** [comment]
Hey @Namide, can you please show us the complete apache virtualhost?

**Comment by Namide** [comment]
Hi @WellingGuzman, I've used an alias with this config:

```
Alias /inspire "D:/NAMIDE/www/inspire"

<Directory "D:/NAMIDE/www/inspire">
	Options Indexes FollowSymLinks MultiViews
 	AllowOverride all
  	<ifDefine APACHE24>
		Require local
	</ifDefine>
	<ifDefine !APACHE24>
		Order Deny,Allow
    		Deny from all
    		Allow from localhost ::1 127.0.0.1
	</ifDefine>
	php_admin_value upload_max_filesize 128M
	php_admin_value post_max_size 128M
	php_admin_value max_execution_time 360
	 php_admin_value max_input_time 360
</Directory>
```

But because you told me about virtual host I've just change my config for a virtual host and now it's success! It's working!

My new config is:
```
NameVirtualHost inspire.local

<VirtualHost inspire.local>
	ServerName inspire.local
	ServerAlias inspire.local
	DocumentRoot "D:/NAMIDE/www/inspire/"

	<Directory "D:/NAMIDE/www/inspire/">
		Options Indexes FollowSymLinks MultiViews
		AllowOverride all
		<ifDefine APACHE24>
			Require local
		</ifDefine>
	</Directory>

</VirtualHost>
```
 
Thank's for your help
