### ISSUE TITLE
Pasting into JSON fields make Directus believe nothing was changed.

### ISSUE THREAD

**Issue by ninemind** [directus/directus#2114]
## Version Info
  - Directus version: 6.4.8
  - PHP version: 7.1
  - MySQL version: 10.2.13-MariaDB-10.2.13+maria~jessie
  - Web server: nginx 1.10.3
  - OS name and version: Ubuntu 16.04.4 LTS

## Expected Behavior
Upon pasting valid JSON in a JSON field type and saving, data should be exactly how it was entered.

## Actual Behavior
After pasting valid JSON into JSON field, a warning is produced that "Nothing changed, nothing saved".

## Steps to Reproduce
 1. Create table with JSON field
 2. Paste valid JSON into field
 3. Save

**Comment by WellingGuzman** [comment]
Closes by https://github.com/directus/directus/commit/4c71967b983b6088d50bfe38adac73ecb03bbe10

Going to be release on 6.4.9
