### ISSUE TITLE
Sort field will be reset everytime you open the data model

### ISSUE THREAD

**Issue by VincentKempers** [directus/directus#21147]
### Describe the Bug

When selecting a custom sort in the sort field of a collection it will set perfectly fine. But returning to the same collection, the sort field will be empty. Directus will see that as a change every time. So when you save you will clear your sort field.

### To Reproduce

- Have a data model and create a manual sort field. 
- Then select your manual sort on the sort field.
- Save
- Then return to that data model
- You will notice that you have a change
- Then you go to the sort field and see that there is nothing selected.

https://github.com/directus/directus/assets/14160793/df8192fa-ba00-46e8-bee0-5abc62b34e01

### Directus Version

v10.8.3

### Hosting Strategy

Directus Cloud

**Comment by paescuj** [comment]
Fixed in #20949 👍
