### ISSUE TITLE
How to modify the parameters passed by the front-end in the flow?

### ISSUE THREAD

**Issue by coderyqy** [directus/directus#21154]
### Page

https://docs.directus.io/app/flows.html

### Describe the Inaccuracy

The main problem is that I don't know how to modify the data in the payload in the flow, and the modified data is the final data stored in the database.

![image](https://github.com/directus/directus/assets/63534197/f72de14a-f476-4a4a-9ba3-d5362f06b2e9)

I have searched for a lot of information on Github and Discord, but none of it has been resolved. Can you provide an example and corresponding code?

Expected approach：
```js
// Front end API call, passing parameters
{
  ip: "127.0.0.1";
  userAgent: "aaa"
}
```
In the flow：
```js
module.exports = async function(data) {
	// Do something...
	return {
    userAgent: "{{$accountability.userAgent}}"
    };
}
```
I'm not sure if it's feasible?

Or is there a ready-made solution that I haven't found?

**Comment by phazonoverload** [comment]
This is covered in a few places - we explicitly have a transform payload operation which shows and example in the docs. We also mention in the run script operation docs: 

> The operation provides a default function template. The optional `data` parameter lets you pass in the data chain as an argument.

You'll want to use a combination of setting descriptive keys for each operation and the logs in the sidebar to troubleshoot this. However, I don't see us updating the docs in response to this issue.

Much of this can be solved not just in docs, but also by improving the logs experience for flows, which we're discussing at this live event on Feb 8: https://discord.gg/SuxhGBeQ?event=1196772963857473617

Hope this has helped point you in the right direction.

**Comment by coderyqy** [comment]
The invitation link is invalid

**Comment by phazonoverload** [comment]
Thanks @coderyqy they seem to time out aggressively. Updated the link - check the events tab
