### ISSUE TITLE
Add security note for access_token in the query

### ISSUE THREAD

**Issue by ricsirigu** [directus/directus#21159]
### Describe the Request

The authentication section in the Directus documentation (https://docs.directus.io/reference/authentication.html) mentions two methods for passing the access token: through a query parameter or an authorization header. It is generally recommended to use the authorization header approach. This helps in minimizing the risk of the access token being inadvertently exposed in logs or accessed by third-party systems. Using headers for token transmission is a best practice for enhancing security.

![CleanShot 2024-01-22 at 15 16 01@2x](https://github.com/directus/directus/assets/5004093/9bd1b469-995d-43ca-9825-8efadc7e96f1)

References:
https://cwe.mitre.org/data/definitions/598.html
https://cwe.mitre.org/data/definitions/200.html
https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#used-vs-accepted-session-id-exchange-mechanisms

### Maintainence Strategy

No maintenance, it's a design best practice, not technology dependent

**Comment by br41nslug** [comment]
We're not encouraging one over the other here but rather documenting the 2 possible options. But you're not wrong the query parameter option could use a small not about the recommended approach from a security view.

**Comment by phazonoverload** [comment]
I'll make this note in #21006 and link to that page here. I'll capture this in that issue and close this one to keep it tidy. Thank youuuuu
