### ISSUE TITLE
Fix layout issues when extending Directus models.

### ISSUE THREAD

**Issue by jbeckton** [directus/directus#21153]
### Describe the Improvement

The Admin UI allows us to add fields to the built in Directus models like Users. I noticed that after adding a new field to my Users model, when I use the create user form the fields are all out of order.

![image](https://github.com/directus/directus/assets/2669585/34bed864-adda-4df1-9dfd-2e519653f71a)

![image](https://github.com/directus/directus/assets/2669585/1f610aab-220a-4737-b1ba-19c996833abb)

**Comment by paescuj** [comment]
Thanks for opening this issue! However, this is a duplicate of #20894, which has been fixed in #20910. The fix will be available in the next release.
