### ISSUE TITLE
Make step size for range fields change database type, or allow it to be set upon creation and not changed

### ISSUE THREAD

**Issue by ninemind** [directus/directus#2115]
## Version Info
  - Directus version: 6.4.8
  - PHP version: 7.1
  - MySQL version: 10.2.13-MariaDB-10.2.13+maria~jessie
  - Web server: nginx 1.10.3
  - OS name and version: Ubuntu 16.04.4 LTS

## Expected Behavior
When setting step size for range fields, make database field proper type. Example: A range slider with .5 steps should be a DECIMAL(2,1)

## Actual Behavior
When creating a numeric range field, the database creates the field as an INT regardless of step size.

## Steps to Reproduce
 1. Create table with numeric range field
 2. Change step size to .5
 3. Create item in table and set range to 3.5, upon saving it will become 4

**Comment by WellingGuzman** [comment]
Hey @ninemind The range interface only allow integer data type? did you create the column manually and want the interface to work with floating point data type?

**Comment by ninemind** [comment]
@WellingGuzman The range interface already supports floating point data types, it's the column creation in the database that does not.

![image](https://user-images.githubusercontent.com/4838451/38170815-52bee0da-354b-11e8-89cc-0f8bcd63979c.png)

![image](https://user-images.githubusercontent.com/4838451/38170825-6d29bc2e-354b-11e8-8826-3df26484c7c6.png)

This is how the interface looks, but once you save the item the precision is removed (3.5 becomes 4).  If you manually change the column type to DECIMAL(2,1) in the database, then things work fine, though they may reset if other changes to the table are made.  I'm not sure.

**Comment by WellingGuzman** [comment]
I see what you mean, what I was talking about is that the interface doesn't list non-integer type when you create it.

What you are requesting is to support DECIMAL on the `slider` interface. I will take a look at this request.

**Comment by WellingGuzman** [comment]
Hey @ninemind I added support for decimal type on the `slider` interface, and it will be released on the next version `6.4.9`

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/87bb231e8c2b9d405d221056f5849aa1721e610a
