### ISSUE TITLE
Global Settings: Project URL feature appears not to work

### ISSUE THREAD

**Issue by andrewliles** [directus/directus#2116]
## Version Info
  - Directus version : 6.4
  - PHP version: as per your Docker image: getdirectus/directus:6.4
  - MySQL version: 5.5
  - Web server: none
  - OS name and version: as per your Docker image: getdirectus/directus:6.4

## Expected Behavior
Having set a project URL, when I click on the logo top left of UI, would expect to be taken to that location.

## Actual Behavior
UI refreshes to /tables 

## Steps to Reproduce
 1. Admin Settings
 2. Global Settings
 3. Set field "Project URL" to something like http://www.google.com
 4. Save
 5. Click on logo in top left corner of UI (directus logo, if you have not changed that)
 6. End up on Tables view, rather than http://www.google.com

## Schema Dump, Logs, or Screenshots
I can see this JavaScript object in the raw page source:
```
<script>
  window.directusPath = '/';
  window.directusData = {"cacheBuster":"d0e 
--snip--{"id":3,"collection":"global","name":"project_url","value":"http:\/\/www.google.com"}
```
By inspecting the built DOM, the customized URL is not showing in what I think would the correct <a>:
```
<a href="/" class="open-modal" data-modal="welcome-1"><div class="logo help static has-project-logo" data-help="Your Logo --snip--
```

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/41)
