### ISSUE TITLE
ON_UPDATE constraint not added when new relation is created from schema

### ISSUE THREAD

**Issue by u12206050** [directus/directus#21189]
### Describe the Bug

When importing a schema generated from another environment the `on_update` isn't added to the database.

After digging through the Directus code I found out why and am attaching a PR to this issue

### To Reproduce

Create a relationship with on_update set to CASCADE, then export the schema and import on another db.

When you export schema from the new db, you will notice the on_update being `NO ACTION`
![Screenshot 2024-01-25 at 09 51 50](https://github.com/directus/directus/assets/6641242/055f1744-7a96-4c1f-bedb-cac15b1b16b7)

### Directus Version

10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
@rijkvanzanten Does anything speak against passing through the `ON UPDATE` trigger? Was it simply omitted because it's not relevant in Directus itself (yet, see #2711)?

**Comment by rijkvanzanten** [comment]
I think that's an oversight. I would expect that information to be in here, as the Directus GUI allows you to modify it
