### ISSUE TITLE
Directus SDK does not return refresh token upon Login as specified

### ISSUE THREAD

**Issue by Andersang** [directus/directus#21188]
### Page

https://docs.directus.io/reference/authentication.html

### Describe the Inaccuracy

The directus SDK is mentioned to return a `refesh_token` in its reponse upon a successful login despite the response mode set to the default of `json`. However, the response data I have received so far only contain `access_token` and `expires`. 

`refresh_token` does appear when logging in via REST API. 

This is the code I used, which is copied from the documentation page:

``` js
import { createDirectus, authentication, rest, login } from '@directus/sdk';

const client = createDirectus('https://directus.example.com').with(authentication()).with(rest());

// login using the authentication composable
const result = await client.login('admin@example.com', 'd1r3ctu5');

console.log(result);

```

**Comment by br41nslug** [comment]
As described in the response description:
> Note: if you used cookie as the mode in the request, the refresh token won't be returned in the JSON.

The SDK defaults to `cookie` mode so the `refresh_token` is stored in a cookie instead of returned in the API response in this example.

**Comment by Andersang** [comment]
It seems like it was not stated in the docs that the Directus SDK defaults to 'cookie' mode. I had assumed that 'json' mode was the default considering the API documentation mentioning so:

'mode'
Whether to retrieve the refresh token in the JSON response, or in a 'httpOnly' 'secure' cookie. One of 'json', 'cookie'. Defaults to 'json'.

**Comment by br41nslug** [comment]
This is currently only explicitly mentioned in the SDK reference https://docs.directus.io/packages/@directus/sdk/auth/functions/authentication.html#parameters, the referred link is the http api reference which does contain sdk usage examples for the corresponding not http api call but is not a reference for the SDK itself.
