### ISSUE TITLE
"Unknown column 'status' in 'where clause'" when making curl requests to Directus API 1.1

### ISSUE THREAD

**Issue by acwhite** [directus/directus#2120]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus version and branch (Or commit hash): **6.4.9**
  - PHP version: **7.2.4**
  - MySQL version: **MariaDB 10.0.34**
  - Web server: (Ex. Apache, nginx or IIS?) **Apache**
  - OS name and version: **Ubuntu 16.04**

## Expected Behavior
API should be accessible via curl requests once a user token is generated

## Actual Behavior
User token can be retrieved as per the instructions found [here](https://api.getdirectus.com/1.1/), but subsequent curl requests using that token fail with an SQL error.

## Steps to Reproduce
 1. **Generate a user token as follows:** curl -d "email=email@domain.com&password=pwd" http://server.ip.address.here/api/1.1/auth/request-token
 2. **Attempt to use the user token to authenticate a request to the Directus API:** curl -u **tokengoeshere**: http://server.ip.address.here/api/1.1/tables
 3. Receive the error message below in response.

## Schema Dump, Logs, or Screenshots
{
  "success":false,
  "error":{
    "message":"Statement could not be executed (42S22 - 1054 - Unknown column 'status' in 'where clause')"
  },
  "code":0,
  "class":"Zend\\Db\\Adapter\\Exception\\InvalidQueryException",
  "file":"\/var\/www\/html\/vendor\/zendframework\/zend-db\/src\/Adapter\/Driver\/Pdo\/Statement.php",
  "line":244
}

**Comment by WellingGuzman** [comment]
Hey @acwhite,

It seems you didn't upgrade your database schema, in recent versions `directus_users.active` was changed to `directus_users.status`, please upgrade your schema with `bin/directus db:upgrade`.
