### ISSUE TITLE
Create/Updating an item in a flow fails when using timestamp with timezone.

### ISSUE THREAD

**Issue by jonathan-james-dev** [directus/directus#21210]
### Describe the Bug

I am using Supabase for my database and have a table that has several columns with the datatype "TIMESTAMP WITH TIME ZONE" to store date and times in UTC format.

I have created a flow that when triggered, creates a new item, passing the payload with the field name and string representation of the date with time zone. 

When the create executes I the following error message from the flow, stating that my ISO 8601 date is not valid:

**Reponse:**
```
{
  "name": "Error",
  "message": "date must have a valid date format or reference"
}
```

**Payload:**
```
{
  "collection": "schedules",
  "permissions": "$full",
  "emitEvents": true,
  "payload": {
    "end_date": "2024-01-26T00:00:00.000Z"
  },
  "query": {
    "filter": {
      "id": {
        "_eq": "28149"
      }
    }
  }
}
```

### To Reproduce

1. Create a flow to create an item with a field with "TIMESTAMP WITH TIME ZONE" data type
2. Create a datetime string with a timezone like so: "2024-01-25T00:00:00.000Z" or "2024-01-25T00:00:00Z" or "2024-01-25T00:00:00"

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
I can not reproduce this issue in the current version of Directus (v10.10.7) with neither Postgres nor SQLite drivers and can create the items with the datetime field as expected. 

I'll proceed to close this issue, if this still is a issue for you on the most recent version of Directus, I'll happily reopen this.
