### ISSUE TITLE
Color interface default not working

### ISSUE THREAD

**Issue by treechime** [directus/directus#2121]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus version and branch (Or commit hash): 6.4.9
  - PHP version: 5.6.33
  - MySQL version: 5.5.56-MariaDB
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: 

## Expected Behavior
Color interface with default value will display default value when creating a new entry.

## Actual Behavior
Color interface doesn't display default value. Default value is entered into the database upon entry being saved unless user has accidentally "cleared" the field (from empty to empty?), in which case the value is empty in the database.

## Steps to Reproduce
1. Create color column using color interface
1. Add default value to color interface
1. Create new entry with color column - field is blank

## Schema Dump, Logs, or Screenshots
Settings:
![image](https://user-images.githubusercontent.com/8661599/38791158-6e13bdb6-4189-11e8-8457-9e60d2b6520d.png)

New entry:
![image](https://user-images.githubusercontent.com/8661599/38791177-925024b2-4189-11e8-98df-d7815a80ff0f.png)

New entry when empty field is "cleared" by clicking the x on the color preview:
![image](https://user-images.githubusercontent.com/8661599/38791204-be697c9c-4189-11e8-8cf3-b01a8fc7ba8c.png)

Entry in database when one field has been cleared and the other untouched:
![image](https://user-images.githubusercontent.com/8661599/38791289-249132da-418a-11e8-9bca-d31143ba4226.png)

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/42)
