### ISSUE TITLE
Cannot configure authentication custom storage with SDK

### ISSUE THREAD

**Issue by valensto** [directus/directus#21219]
### Describe the Bug

In the documentation, we can implement a custom storage to stores and retrieves data: [https://docs.directus.io/guides/sdk/authentication.html#configure-custom-storage](https://docs.directus.io/guides/sdk/authentication.html#configure-custom-storage)

```js
import { createDirectus, authentication } from '@directus/sdk';

class LocalStorage {
  get() {
    return JSON.parse(localStorage.getItem("directus-data"));
  }
  set(data) {
    localStorage.setItem("directus-data", JSON.stringify(data));
  }
}

const client = createDirectus('http://directus.example.com')
  .with(authentication('json', { storage: new LocalStorage() }));

client.setToken('TOKEN');
```

The fact is the setToken method only accepts string as `access_token` and populate the type AuthenticationData with only field

```ts
setToken(access_token: string | null) {
    storage.set({
	    access_token,
	    refresh_token: null,
	    expires: null,
	    expires_at: null,
    });
},
```

Like the get token does the same thing and get only the access_token instead of the full object

```ts
async getToken() {
    await refreshIfExpired();
    
    const data = await storage.get();
    return data?.access_token ?? null;
},
```

src: [https://github.com/directus/directus/blob/main/sdk/src/auth/composable.ts](https://github.com/directus/directus/blob/main/sdk/src/auth/composable.ts)

So we cannot use the config parameter because it's not used inside the core function 

If someone can fix that and change both interfaces 

```ts
export interface AuthenticationClient<_Schema extends object> {
	login(email: string, password: string, options?: LoginOptions): Promise<AuthenticationData>;
	refresh(): Promise<AuthenticationData>;
	logout(): Promise<void>;

	getToken(): Promise<string | null>;
	setToken(access_token: string | null): void;
}

export interface StaticTokenClient<_Schema extends object> {
	getToken(): Promise<string | null>;
	setToken(access_token: string | null): void;
}
```

Thank :)

### To Reproduce

Just follow the documentation :

[https://docs.directus.io/guides/sdk/authentication.html#configure-custom-storage](https://docs.directus.io/guides/sdk/authentication.html#configure-custom-storage)

And try to store tokens from login method 

```ts
import { createDirectus, authentication } from '@directus/sdk';

class LocalStorage {
  get() {
    return JSON.parse(localStorage.getItem("directus-data"));
  }
  set(data) {
    localStorage.setItem("directus-data", JSON.stringify(data));
  }
}

const client = createDirectus('http://directus.example.com')
  .with(authentication('json', { storage: new LocalStorage() }));

const login = async (email: string, password: string) => {
  const tokens = await client.login(email, password);
  client.setToken(tokens); // this store object.Object because waiting string instead of AuthenticationData
};
```

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Can you explain in more detail what you want to achieve?

> So we cannot use the config parameter because it's not used inside the core function

Which config parameter do you mean, for example?

**Comment by br41nslug** [comment]
what you're trying to achieve is:
```
import { createDirectus, authentication } from '@directus/sdk';

class LocalStorage {
  get() {
    return JSON.parse(localStorage.getItem("directus-data"));
  }
  set(data) {
    localStorage.setItem("directus-data", JSON.stringify(data));
  }
}

const storage = new LocalStorage();
const client = createDirectus('http://directus.example.com')
  .with(authentication('json', { storage }));

const login = async (email: string, password: string) => {
  const tokens = await client.request(login(email, password));
  storage.set(tokens);
};
```
or just:
```
import { createDirectus, authentication } from '@directus/sdk';

class LocalStorage {
  get() {
    return JSON.parse(localStorage.getItem("directus-data"));
  }
  set(data) {
    localStorage.setItem("directus-data", JSON.stringify(data));
  }
}

const storage = new LocalStorage();
const client = createDirectus('http://directus.example.com')
  .with(authentication('json', { storage }));

await client.login(email, password);
// because you dont really need to manually store the tokens in the provided example
```

**Comment by valensto** [comment]
@br41nslug I want to store my tokens in my local storage with the custom config 

```ts
import { createDirectus, authentication } from '@directus/sdk';

class LocalStorage {
  get() {
    return JSON.parse(localStorage.getItem("directus-data"));
  }
  set(data) {
    localStorage.setItem("directus-data", JSON.stringify(data));
  }
}

const storage = new LocalStorage();
const client = createDirectus('http://directus.example.com')
  .with(authentication('json', { storage }));

const tokens = await client.request(login(email, password));
client.setToken(tokens) // store object.object because it want a string instead of authenticationData type
```
so we need to passe tokens.access_token to store the access token but the other fields are set to null

`client.setToken(tokens.access_token)` 
but don't want that and pass as expected my tokens object with 

```ts
export interface AuthenticationData {
	access_token: string | null;
	refresh_token: string | null;
	expires: number | null;
	expires_at: number | null;
}
```

**Comment by valensto** [comment]
@br41nslug I don't think it's close, the documentation, the interface, the parameters and how the code is used is not consistent. 

The override configuration is just fully ignored and use only the access_token instead of the full object. 
In your exemple you are using the storage but not with the client instance, so it's not the same

**Comment by paescuj** [comment]
Admittedly, it also confused me a bit.
Looking at #21232, it seems like the solution here would be to directly use `storage.set`, is that correct @br41nslug?

**Comment by br41nslug** [comment]
Correct `storage.set` is the way to write data to your storage if your usecase requires that (you'll see storage setting on storage init too sometimes for SSR). `setToken` is more of a remnant from the `staticToken` composable to overwrite the currently managed token with a manually managed (or static) token.
