### ISSUE TITLE
Support for IDN emails?

### ISSUE THREAD

**Issue by maxia** [directus/directus#2122]
I noticed that when a user has an email with a IDN domain (e.g. info@dömäin.com -> info@xn--dmin-moa0i.com) the login will not work.

I'm currently using a workaround that converts the email to punycode on login and entered the punycode email for the user.

## Version Info
  - Directus version and branch (Or commit hash):
  - PHP version: PHP 7.0.28-0ubuntu0.16.04.1
  - MySQL version: 5.7.21-0ubuntu0.16.04.1 
  - Web server: nginx/1.12.1
  - OS name and version:  Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-116-generic x86_64)

## Steps to Reproduce
 1. Enter a email like info@dömäin.com for a user
 2. Try to login

**Comment by benhaynes** [comment]
Kamino cloned this issue to [directus/app](https://github.com/directus/app/issues/1037)

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/43)
