### ISSUE TITLE
Wrong create project documentation

### ISSUE THREAD

**Issue by ganjarsetia** [directus/directus#21227]
### Page

https://docs.directus.io/getting-started/quickstart.html

### Describe the Inaccuracy

I tried following create project from this doc by running `npm init directus-project@latest`

![image](https://github.com/directus/directus/assets/3258090/dd107615-bb7e-4a40-94eb-b7d0162fc41d)

When I tried I got error:

![image](https://github.com/directus/directus/assets/3258090/39d6b4fd-e8d2-4942-b207-c385909b9d1a)

I think the documentation is wrong. Or perhaps maybe this one is right answer `npm init directus-project@latest .` ?

My setup info:

```
node v20.11.0
npm 10.4.0
create-directus-project 10.0.1
```

**Comment by phazonoverload** [comment]
This should have been caught in #20836
