### ISSUE TITLE
Extension loading but not working

### ISSUE THREAD

**Issue by Lucas-Gruber** [directus/directus#21220]
### Describe the Bug

I have Directus running in a Docker Container. When i now add a Interface-Extension in the folder and restart the container is following in console:
![CleanShot 2024-01-28 at 8  36 16@2x](https://github.com/directus/directus/assets/72545889/50c3eae4-b3ea-40a6-a2ed-af2a6f9100f4)

And in the Admin app (/admin/settings/extensions):
![CleanShot 2024-01-28 at 8  37 22@2x](https://github.com/directus/directus/assets/72545889/9dfb1a77-7bd4-4ad4-8990-247f391a0184)

But when i creating a field none of the interface are shown. But when i first added the extensions it worked without problems.

So only after a time or restarts (i restarted the instance in the time several times) it doesnt work anymore.

### To Reproduce

- Install a interface extension such as: https://github.com/resauce-dev/directus-image-scout/tree/main
- restart the instance several times or wait a time
- Try if it works

ps: i also have used the interface in the data model and now it is a raw field because it doesnt work anymore

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
I have not been able to reproduce this issue following the reproduction steps. Please provide more detailed information about your setup where you are seeing this issue. This is likely an issue with the storage used for extensions.

**Comment by Lucas-Gruber** [comment]
Sorry i found the issue more or less. I've used docker compose and i removed the volume, restarted the stack and added it again and now it works. I don't know whats the problem is but it works now.
Sorry for the dumb bug report!
