### ISSUE TITLE
Bug in Bulk Edit: Unselected Fields Getting Modified in ListView

### ISSUE THREAD

**Issue by bajzikgyuri** [directus/directus#21251]
### Describe the Bug

When utilizing ListView in Directus for bulk record modifications, a sporadic problem arises where non-selected fields undergo alterations as well. This issue poses a serious risk to data integrity, primarily because users remain unaware of these accidental changes. The critical nature of this problem cannot be overstated, as it harbors the potential for considerable disruptions and unintended data inconsistencies, undermining the system's dependability and the user's trust.

### To Reproduce

1. Go to 'ListView' in Directus.
2. Select multiple items for bulk editing (e.g., 1000 items).
3. Click on 'Bulk Edit'.
4. Choose the specific field you want to modify.
5. Enter the new value for the field.
6. Confirm the bulk modification by clicking the confirmation button (tick mark).
7. Occasionally, a field that was not selected for editing gets its value copied across all selected items.

### Directus Version

v10.6.7

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Could you expand on the actual issue in the description? like examples, types of fields you're bulk updating, types of fields that may change unintentionally, what does the collection look like, how many items is needed, etcetera.

Are these production steps reliable? You mention "Occasionally" in the last step which doesn't sound like following the steps will get reliable reproduction on every try 🤔
