### ISSUE TITLE
[SDK] Unexpected eslint "any" error

### ISSUE THREAD

**Issue by MarcosGin** [directus/directus#21262]
### Describe the Bug

I am using the trpc boirlerplate configuration in next.js, I am having problems with eslint when creating the client, what I was wondering is the any that is defined in the types

//from sdk
<img width="1100" alt="image" src="https://github.com/directus/directus/assets/26859121/18ffdf91-fb91-4a36-9964-fe6de05ed06c">

<img width="1401" alt="image" src="https://github.com/directus/directus/assets/26859121/c9d6eeb7-c0a7-4091-9465-659a7967ba4b">

### To Reproduce

api.ts
```ts
import { createDirectus, graphql, readItems, rest } from "@directus/sdk";
import type { DirectusClient, GraphqlClient, RestClient } from "@directus/sdk";
import { env } from "@/env";
import type { Collections } from "./types";

// const globalForDirectus = globalThis as unknown as {
//   directus: Directus<Collections> | undefined;
// };

// export const directusClient =
//   globalForDirectus.directus ?? new Directus(env.DIRECTUS_SDK_URL);

// if (env.NODE_ENV !== "production") globalForDirectus.directus = directusClient;

const globalForDirectus = globalThis as unknown as {
  directus: DirectusClient<Collections> &
    RestClient<Collections> &
    GraphqlClient<Collections>;
};

export const directusClient =
  globalForDirectus.directus ??
  createDirectus<Collections>(env.DIRECTUS_SDK_URL)
    .with(rest())
    .with(graphql());


if (env.NODE_ENV !== "production") globalForDirectus.directus = directusClient;

```

eslintrc
```cjs
/** @type {import("eslint").Linter.Config} */
const config = {
  parser: "@typescript-eslint/parser",
  parserOptions: {
    project: true,
  },
  plugins: ["@typescript-eslint", "tailwindcss"],
  extends: [
    "next/core-web-vitals",
    "plugin:@typescript-eslint/recommended-type-checked",
    "plugin:@typescript-eslint/stylistic-type-checked",
    "plugin:tailwindcss/recommended",
  ],
  rules: {
    // These opinionated rules are enabled in stylistic-type-checked above.
    // Feel free to reconfigure them to your own preference.
    "@typescript-eslint/array-type": "off",
    "@typescript-eslint/consistent-type-definitions": "off",

    "@typescript-eslint/consistent-type-imports": [
      "warn",
      {
        prefer: "type-imports",
        fixStyle: "inline-type-imports",
      },
    ],
    "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
    "@typescript-eslint/require-await": "off",
    "@typescript-eslint/no-misused-promises": [
      "error",
      {
        checksVoidReturn: { attributes: false },
      },
    ],
  },
};

module.exports = config;

```

### Directus Version

v14.0.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
`any` is the default/fallback schema so the SDK can keep functioning even if no Schema is provided however you're explicitly overwriting with `Collections` so there should be no reason for TS to complain here 🤔

**Comment by rijkvanzanten** [comment]
@MarcosGin Can you provide a repo with a minimal reproduction? I wanna make sure we rule out any environment based shenanigans. Is this something you can reproduce with just the SDK and eslint?

**Comment by MarcosGin** [comment]
Of course, you can get the base structure using this boirleplate: https://create.t3.gg/
It already comes with eslint and typescript configurations.

I tried changing the type from any to an object and now eslint shows no errors.
declare const createDirectus: <Schema extends object = object>(url: string, options?: ClientOptions) => DirectusClient<Schema>;

**Comment by br41nslug** [comment]
setting it to `object` may satisfy the eslint rule on your end but is not a valid default for the SDK.

**Comment by rijkvanzanten** [comment]
I'm conflicted here, our defaulting to `any` when you're not providing the type in the SDK feels like a perfectly fine use of `any` in the SDK itself 🤔

**Comment by br41nslug** [comment]
While we rely on `any` the following rule will never be compatible with the SDK `@typescript-eslint/no-redundant-type-constituents`

This rule checks for `Type & any` which we do in [one place](https://github.com/directus/directus/blob/main/sdk/src/types/utils.ts#L36), here we are actually checking if a type is `any` for conditional logic, which i suppose we may still need even if `any` as not the default.

**Comment by MarcosGin** [comment]
Sorry guys, were you able to replicate the error?
After manually modifying the typing in the node_modules, I had to delete everything and restart eslint/typescript in vscode, now I am unable to replicate the error.

Could it be a temporary error in vscode?

**Comment by br41nslug** [comment]
I wasnt able to configure eslint in my SDK test project within a reasonable amount of time so have not reproduced the issue.

**Comment by paescuj** [comment]
I haven't been able to reproduce it, so I think that was indeed a temporary issue from VS Code. Sometimes a manual reload/restart of VS Code is required for the ESLint plugin to catch up with the latest changes (code changes, eslint config, tsconfig, packages, ...). This is especially the case if the plugin should have crashed for some reason, which can also happen in rare cases.
I'm closing this issue for now, but do let us know if you feel like this is still an issue originating from `@directus/sdk`.
