### ISSUE TITLE
Extensions - Proper way to use router?

### ISSUE THREAD

**Issue by cj3g10** [directus/directus#2126]
## Version Info
  - Directus version and branch (Or commit hash): v6.4.9 (Ruby Rabbit)
  - PHP version: 7.2.1
  - MySQL version: 5.6.38
  - Web server: Apache
  - OS name and version: Windows 10

I am creating an extension where there is a button that links to a subpage. I have looked at the example extension, read [this tutorial](https://medium.com/directus/how-to-setup-a-custom-extension-770d6ea48551) and searched around but I don't really understand what is the proper way to link the next page.

Current my route looks like this (following the example extension as a guide):
```php
routes: {
    "(/)": "home",
    "/export": "exportPage"
}
```

Using the example extension as a template, in my "home" view, I have a button with link like this:
```html
location.href="#ext/test/export"
```
which links me to http://127.0.0.1:8888/directus/ext/test#ext/test/export and I also get an error
```
Uncaught TypeError: Cannot read property 'subroutes' of undefined
    at B.n.checkUrlForSubroute (directus.min.js?bust=raj1r0qlhsgg8e4qcfl2jsmdag:58)
    at d (directus.min.js?bust=raj1r0qlhsgg8e4qcfl2jsmdag:7)
    at Object.trigger (directus.min.js?bust=raj1r0qlhsgg8e4qcfl2jsmdag:7)
    at directus.min.js?bust=raj1r0qlhsgg8e4qcfl2jsmdag:58
    at buttonClick (eval at <anonymous> (directus.min.js?bust=raj1r0qlhsgg8e4qcfl2jsmdag:4), <anonymous>:1:113)
    at HTMLInputElement.onclick (test_extension:1)
```
What I don't understand about this is in the example extension, the "Page One"/"Page Two" links show http://127.0.0.1:8888/directus/ext/example_extension#ext/example_extension/pageone , but goes to http://127.0.0.1:8888/directus/ext/example_extension/pageone ?

Alternately I could set my link reference to 
```html
location.href="test/export"
```
and this works, however navigating to another page afterwards will cause an pop up dialog to appear with the message "You don't have permission to view that page or it doesn't exist". I noticed that, for example if I navigate to the example extension, the link becomes
http://127.0.0.1:8888/directus/ext/test/ext/example_extension .

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/44)
