### ISSUE TITLE
Collection name collision in the UI

### ISSUE THREAD

**Issue by navanshu** [directus/directus#21274]
### Describe the Bug

When two collection has similar names like data and _data, both of these are shown as Data in triggers and multiple other places

### To Reproduce

Make two collection with names data and _data

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
That's currently working as intended. The app will try to auto-generate a human readable version of the technical key, which means that `data` `Data` `_data` all will default to `Data`. You can set display names for collections by changing the "translation" in the collection settings 👍🏻
