### ISSUE TITLE
API: Improve IP detection for accountability

### ISSUE THREAD

**Issue by joselcvarela** [directus/directus#21272]
### Describe the Improvement

In order to check the IP address when checking against the IP Access on Role, we are using the utility `getIPFromReq`:
https://github.com/directus/directus/blob/main/api/src/middleware/authenticate.ts#L19
https://github.com/directus/directus/blob/main/api/src/utils/get-ip-from-req.ts#L6

Although, on activity tracking (Directus Activity) we are using different approach:
https://github.com/directus/directus/blob/main/api/src/server.ts#L78

On our scenario the second approach is detecting the real client IP as expected while first approach it's detecting the internal machine address (like 10.0.7.82).

Since the second approach works better and since we need to use IP Access to restrict which devices can login, my suggestion is to this on `getIPFromReq` (https://github.com/directus/directus/blob/main/api/src/utils/get-ip-from-req.ts#L7):
```ts
	let ip = req.headers['x-forwarded-for'] || req.socket?.remoteAddress || req.ip;
```

Then use the `getIPFromReq` on activity tracking as well: https://github.com/directus/directus/blob/main/api/src/server.ts#L78

**Comment by joselcvarela** [comment]
Meanwhile, the workaround for us is to use `IP_CUSTOM_HEADER` to get the header with the IP address
But I believe some services may not pass the IP in any header

**Comment by rijkvanzanten** [comment]
The `server.ts` emitter IP address is not related to activity tracking. It creates a `response` event for use in hooks / flows, but that's not relied on by any of the system code. 

The IP address used in accountability is the same IP address that's saved to directus_activity:

https://github.com/directus/directus/blob/f34e05bd307f2d0c01843175590a00a1af9966f6/api/src/services/items.ts#L253-L261
