### ISSUE TITLE
Notification Bell not Updating in Real-Time

### ISSUE THREAD

**Issue by paesjr** [directus/directus#21278]
### Describe the Bug

I have observed that when making a comment, the notification bell (🔔) only appears after refreshing the browser. It seems like the notification feature might have a bug or is not updating in real time.

### To Reproduce

1. Open Directus.
2. Make a comment.

![Screenshot 2024-02-01 at 9 18 10 AM](https://github.com/directus/directus/assets/109459733/43fbb982-e0e2-440e-a053-70e67b9d4752)

3. Check for the notification bell; it doesn't appear until the browser is refreshed.

Expected Behavior:
The notification bell should update in real time without requiring a manual browser refresh.

![Screenshot 2024-02-02 at 9 25 55 AM](https://github.com/directus/directus/assets/109459733/d9c4efdc-1bbd-4910-95d9-c5e5cdec013e)

I appreciate your attention to this matter.

Thank you!

Ricardo Paes

### Directus Version

v10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
The app does not have real time features.

**Comment by paesjr** [comment]
> The app does not have real time features (yet).

Got it, I will make a feature request then, thanks!
