### ISSUE TITLE
Api: Clear extensions cache if extensions have changed

### ISSUE THREAD

**Issue by joselcvarela** [directus/directus#21279]
### Describe the Improvement

When we call the extensions endpoints, those requests are being cached.
Also, whenever we put new (maybe also update) custom extensions on the project, we know those requests should bring new data.
Because of that, Directus could compare the extensions state before and after and if there's differences, it would clear the extensions cache.

**Comment by hanneskuettner** [comment]
After trying to replicate this with the most recent version (v10.10.5) I can not find any cases in which the extensions endpoint reports any out of date data in the Data Studio.

I've tried with both `CACHE_AUTO_PURGE` enabled and disabled.

**Comment by joselcvarela** [comment]
Don't see this issue any longer so I am closing this one
