### ISSUE TITLE
CORS errors on createItem method

### ISSUE THREAD

**Issue by kostyaostapuk** [directus/directus#21277]
### Describe the Bug

I was trying to execute the code:

`const { data: os_invoices } = await useAsyncData('os_invoices', () => {
		return useDirectus(
			createItem('os_invoices', {
				status: 'status',
			}),
		);
	});`
	
I was trying to add this variables to config:
`CORS_ENABLED="true"`
`CORS_ORIGIN="true"`
	
Result:
	
<img width="945" alt="Screen Shot 2024-02-01 at 19 35 34" src="https://github.com/directus/directus/assets/16259513/3e61e0c5-5572-4753-a7de-d7946f930b28">
<img width="955" alt="Screen Shot 2024-02-01 at 19 35 54" src="https://github.com/directus/directus/assets/16259513/dd48eab8-c806-4dc5-a25f-5d1d6c53da3b">
<img width="957" alt="Screen Shot 2024-02-01 at 19 36 00" src="https://github.com/directus/directus/assets/16259513/7ac1cca3-ff2d-4891-922b-a2a28a9e42fd">

Looks like it's the same problem: https://github.com/directus/directus/issues/20577

### To Reproduce

`const { data: os_invoices } = await useAsyncData('os_invoices', () => {
		return useDirectus(
			createItem('os_invoices', {
				status: 'status',
			}),
		);
	});`

### Directus Version

9.26

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by kostyaostapuk** [comment]
@rijkvanzanten can you look?

**Comment by rijkvanzanten** [comment]
Make sure to update to the latest version. v9 is deprecated and no longer support by the Directus team 👍🏻
