### ISSUE TITLE
pino-pretty seems to have a problem with pm2 cluster mode that logs cant be displayed

### ISSUE THREAD

**Issue by Aokoooooo** [directus/directus#21271]
### Describe the Bug

start directus app directly by `npx directus start` or start it by pm2 in fork mode, all logs could be dispalyed
but if I change pm2 to cluster mode, only the logs printed by pino-http-print could be displayed(the old version of directus' logger used pino-colada, it work well too)

i've checked some issues from pino-pretty, https://github.com/pinojs/pino/issues/318, https://github.com/pinojs/pino-pretty/issues/303, i think the pino-pretty is the heart of this matter, but i didnt got any solutions

and i checked here https://github.com/Unitech/pm2/issues/3675, someone used child_process to start directus, it could work, the logs could be displayed, but it'll cause a new problem that cluster mode cant work well: different child_process cant share the same port, so only one thread could work, other child_process' server closed due to port conflicts(it fall back to a special kind of fork mode...).....

I'd like to ask if anyone else has had this problem, and if so, how you solved it.

### To Reproduce

just change the default ecosystem.config.js file's script from 'cli.js' to 'node_modules/directus/cli.js'

### Directus Version

v10.15.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by Aokoooooo** [comment]
for now i just used patch-package to rewrite @directus/api/dist/logger.js that change `pino-pretty` to `pino-http-print`
dirty but work..

```
if (env['LOG_STYLE'] !== 'raw') {
    pinoOptions.transport = {
        target: 'pino-http-print',
        options: {
            all: true,
            translateTime: 'SYS:HH:MM:ss',
            prettyOptions: {
                ignore: 'hostname,pid',
                sync: true,
            },
        },
    };
    httpLoggerOptions.transport = {
        target: 'pino-http-print',
        options: {
            all: true,
            translateTime: 'SYS:HH:MM:ss',
            relativeUrl: true,
            prettyOptions: {
                ignore: 'hostname,pid',
                sync: true,
            },
        },
    };
}
```

**Comment by br41nslug** [comment]
Perhaps you can take some inspiration from the docker image running pm2 in cluster mode without this issue.

**Comment by rijkvanzanten** [comment]
I'd recommend setting LOG_LEVEL to `raw` when using pm2 or Docker so you can ingest those logs into whatever your intended log strategy is in a machine readable format. 'Pretty' is better suited for local testing / development.

**Comment by Aokoooooo** [comment]
> Perhaps you can take some inspiration from the docker image running pm2 in cluster mode without this issue.

it's wired cause I've kept the configuration consistent as much as i can aside from not using docker...

**Comment by rijkvanzanten** [comment]
> this problem is not about the log style

Didn't you say pino-pretty was at the heart of the issue? `LOG_STYLE=raw` disables the use of pino-pretty

**Comment by Aokoooooo** [comment]
> Didn't you say pino-pretty was at the heart of the issue? `LOG_STYLE=raw` disables the use of pino-pretty

oh....you are right.. i didnt know this config could change this behavior, thx a lot

but I'm not sure there's any other way to solve the problem..
