### ISSUE TITLE
Large Video File Preupload Fails

### ISSUE THREAD

**Issue by mdbarr73** [directus/directus#2128]
When dragging/selecting large video files(211MB test file) to upload to files, Directus throws a javascript error in Firefox: "allocation size overflow". Error occurs on /app/helpers/file.js:48:11

## Version Info
  - Directus version and branch (Or commit hash): 6.4.7
  - PHP version: 7.1
  - MySQL version: Aurora MySQL 5.6.10a
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: Docker Directus

## Expected Behavior
File preloads in the browser and shows the thumbnail on the upload page.

## Actual Behavior
JS error "allocation size overflow" occurs.

## Steps to Reproduce
 1. Go to Files>Upload
 2. Choose > Select large video file (tested w/ 211MB)
 3. Wait, error will appear in lower right corner.

## Schema Dump, Logs, or Screenshots
![image](https://user-images.githubusercontent.com/30296775/38953700-91772424-431d-11e8-8c95-263a146324c6.png)

**Comment by dynamikapps** [comment]
Hi, I’m having a the same issue when downloading large video files to directus. I’m storing the files in s3 but getting error on preload. Any updates or any idea on what the issue could be?

**Comment by benhaynes** [comment]
Kamino cloned this issue to [directus/api](https://github.com/directus/api/issues/514)

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/45)
