### ISSUE TITLE
Support for International Email Addresses in Login Form Fails Due to type=email Validation

### ISSUE THREAD

**Issue by sensedrive** [directus/directus#21309]
### Describe the Bug

We have identified a critical issue in our application's login form, specifically related to users attempting to log in with international email addresses that contain non-ASCII characters, such as Umlaute (ä, ö, ü) or other Unicode characters. The issue arises because the email input field is currently set to use type=email, which appears to enforce strict validation rules that do not fully accommodate internationalized email addresses as per RFC 6531 standards.

Is there any workaround for that?

Is it possible to modify the login form?

Nevertheless, it seems to be more a browser validation issue. **Not** using type=email would however solve the issue.

### To Reproduce

1.     Navigate to the login page of the app.
2.     Attempt to log in using an international email address that includes non-ASCII characters (e.g., jürgen@example.com).
3.     Observe that the login attempt fails with a validation error indicating an invalid email address.

### Directus Version

v10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Underlying w3 issue https://github.com/whatwg/html/issues/4562

**Comment by sensedrive** [comment]
OK, well ... this is working technically ^^, but ...

Would it be a solution to remove the type=email attribute in the form?

**Comment by rijkvanzanten** [comment]
I'm also having some trouble understanding why the native browser validation would fail for valid email addresses in the first place 🤔

**Comment by br41nslug** [comment]
> I'm also having some trouble understanding why the native browser validation would fail for valid email addresses in the first place 🤔

because the "native browser validation" (or rather the w3 spec which all browsers have implemented) uses this regex to validate `/^[a-zA-Z0-9.!#$%&'*+-/=?\^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/` which does not support unicode characters.

This issue is know and marked as "wont fix"

**Comment by rijkvanzanten** [comment]
> This issue is know and marked as "wont fix"

Have a source? Wanna learn more!

**Comment by br41nslug** [comment]
The link above for the whatwg issue (https://github.com/whatwg/html/issues/4562) and they link to this w3 bug https://www.w3.org/Bugs/Public/show_bug.cgi?id=15489
