### ISSUE TITLE
Save as copy not working properly

### ISSUE THREAD

**Issue by kkmahawar** [directus/directus#21310]
### Describe the Bug

After save as copy,

Deep level links not coied.

### To Reproduce

Try to save as copy any item which have B2A relationship.
This will not copied (Invalid entry error)

### Directus Version

v9.26.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by DanielBiegler** [comment]
Hi there! First of all I'm not sure what you mean by B2A relationship, secondly it'd be appreciated if you could provide more than a sentence for issues but most importantly your version is nearly 1200 commits ago. Please try updating and if the issue persists please let us know. Thank you! :+1:
