### ISSUE TITLE
Filter _and in relations 

### ISSUE THREAD

**Issue by mrjajcom** [directus/directus#21334]
### Describe the Bug

To filter the following web service, when the _or command is used, the results return true, but when the **_and** command is used, the results return **empty**.

**data without filter:**
query: null
result: 
![image](https://github.com/directus/directus/assets/23034751/ba936266-fef1-42ef-b9b8-88783a9c1486)

**with _or filter:**
query: 
query>filter>_or>...
![image](https://github.com/directus/directus/assets/23034751/79ead5c6-c182-4907-9e80-9f1372d2148c)

result: found 2 items
![image](https://github.com/directus/directus/assets/23034751/a5704c6c-0a40-4b30-bc0c-fd38aec00e37)

**with _and filter:**
query:
query>filter>_and>...
![image](https://github.com/directus/directus/assets/23034751/f26b0500-ab4a-4e76-8483-10540a5f7134)
result: empty
![image](https://github.com/directus/directus/assets/23034751/f50ea2d8-9e25-48e3-a4df-4c5020ad0502)

This issue is important to us, how can we fix this issue?

### To Reproduce

1. Create many-to-many input (ex:product_attributes) for a collection (ex: products)
2. filter items with _and for two relational attributes
3. response is empty

### Directus Version

last

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
The issue with the `_and` filter is that you're filtering for `attributes->attributes_id->key _eq "tdh"` AND `attributes->attributes_id->key _eq "flow"` which cannot both be true hence no results.

**Comment by mrjajcom** [comment]
How can I do this?
Can I get products that have both attributes?

**Comment by br41nslug** [comment]
You'll want to make use of the `_some/_none` relational operators https://docs.directus.io/reference/filter-rules.html#some-vs-none-in-one-to-many

**Comment by mrjajcom** [comment]
I want to make a filter similar to the following command:
Returns Products whose **FLOW value is between 1 and 100** and whose **TDH value is between 200 and 300**. Flow and TDH are **Attributes**.

How to use _same command for this filter?
