### ISSUE TITLE
Apple OpenID doesn't work

### ISSUE THREAD

**Issue by Gunther-443** [directus/directus#21339]
### Describe the Bug

Hello, I've noticed a problem with Apple's openID.
I followed Apple's procedure: https://developer.apple.com/help/account/configure-app-capabilities/configure-sign-in-with-apple-for-the-web
It works with Google's openID.

I tried the official documentation: https://docs.directus.io/self-hosted/sso-examples.html#oauth-2-0

### To Reproduce

Here are my environment variables: 

AUTH_APPLE_DRIVER="openid" \
AUTH_APPLE_CLIENT_ID="eu.xxxxxx.appid" \
AUTH_APPLE_CLIENT_SECRET="XXXXXX" \
AUTH_APPLE_ISSUER_URL="https://appleid.apple.com/.well-known/openid-configuration" \
AUTH_APPLE_SCOPE="name email" \
AUTH_APPLE_IDENTIFIER_KEY="email" \
AUTH_APPLE_PARAMS="{"response_mode":"form_post"}"

Here's the error message :
invalid_request
response_mode must be form_post when name or email scope is requested.

————

I also tried this discussion page : https://github.com/directus/directus/discussions/9313

AUTH_APPLE_DRIVER="openid"
AUTH_APPLE_CLIENT_ID="eu.xxxxxx.appid"
OAUTH_APPLE_TEAM_ID="XXXXXX"
AUTH_APPLE_CLIENT_SECRET=« XXXXXX »
AUTH_APPLE_ISSUER_URL="https://appleid.apple.com/.well-known/openid-configuration"
AUTH_APPLE_ALLOW_PUBLIC_REGISTRATION="true"
AUTH_APPLE_IDENTIFIER_KEY="sub"
AUTH_APPLE_DEFAULT_ROLE_ID=« XXXX »
AUTH_APPLE_SCOPE="openid"
AUTH_APPLE_ICON="apple"

Here's the error message :
invalid_request
Invalid client id or web redirect url.

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Gunther-443** [comment]
Anyone? Bug, documentation to review, or just me?

**Comment by rijkvanzanten** [comment]
No clue! Directus implements the OpenID spec, so if Apple's provider service adheres to the spec, it should just work. That being said, Apple is really difficult to debug and test with, so I don't know when we'll be able to get to it. 

@aidenfoxx I vaguely remember this coming up in the past. If memory serves me well, Apple was doing some non-standard shenanigans? 🤔

**Comment by aidenfoxx** [comment]
The issue was that Apple doesn't return anything useful if you don't use "form_post" as your response method, so we added support for it and updated the docs to specify `AUTH_APPLE_PARAMS="{"response_mode":"form_post"}"`. Could be an escaping issue with the quotes since it seems like it's not being picked up.

@Gunther-443 When you're redirected to the Apple sign in page, could you check the URL and see if it contains a "response_mode" parameter.

**Comment by ninogjoni** [comment]
@Gunther-443 
Here is the env config that works on my server. As @aidenfoxx already mentioned, the `AUTH_APPLE_PARAMS` is very important! Just ignore the "exports" and "quotation marks"
```
export AUTH_APPLE_DRIVER="openid"
export AUTH_APPLE_CLIENT_ID=""
export AUTH_APPLE_CLIENT_SECRET=""
export AUTH_APPLE_ISSUER_URL="https://appleid.apple.com/.well-known/openid-configuration"
export AUTH_APPLE_ALLOW_PUBLIC_REGISTRATION="true"
export AUTH_APPLE_DEFAULT_ROLE_ID=""
export AUTH_APPLE_SCOPE="name email"
export AUTH_APPLE_IDENTIFIER_KEY="email"
export AUTH_APPLE_PARAMS="{\"response_mode\":\"form_post\"}"
export AUTH_APPLE_ICON="apple"
```

**Comment by rijkvanzanten** [comment]
I'm going to assume the `form_post` was the missing piece to the puzzle, so I'll close this for now. Lemme know if it doesn't work!
