### ISSUE TITLE
Error when opening a table

### ISSUE THREAD

**Issue by ksraghavendra** [directus/directus#2133]
## Version Info
  - Directus version and branch (Or commit hash): latest
  - PHP version: 7.1.3
  - MySQL version: 
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: Debian 4.9.65

## Actual Behavior
Error when opening one of the tables. On clicking the red error popup, the page is stuck on "Loading data".  Unable to add records to the table because of this issue.

**Error**
Error: Uncaught Error: Parse error on line 1:<br>{{name} - {id}}
------^
Expecting 'CLOSE', 'CLOSE_UNESCAPED', 'STRING', 'INTEGER', 'BOOLEAN', 'ID', 'DATA', 'SEP', got 'INVALID'
File: http://35.200.188.39/directus/directus/assets/js/libs/handlebars.js?bust=aba7727c527125d35e1fc97219ef2ea7c7a8098d
Line:306

## Schema Dump, Logs, or Screenshots
![errir](https://user-images.githubusercontent.com/533841/39239818-ac0b5b7a-489f-11e8-93ed-e7a6407fdb69.JPG)

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/46)
