### ISSUE TITLE
Flow confirmation dialog appears above select drawer

### ISSUE THREAD

**Issue by paescuj** [directus/directus#21344]
### Describe the Bug

The flow confirmation dialog appears above the select drawer of the "Collection Item Dropdown" field:
https://discord.com/channels/725371605378924594/741317677397704757/1204538086814650439

Related to #20952

### To Reproduce

- Create a manual Flow with confirmation dialog
- Configure a "Collection Item Dropdown" field
- Go to collection, open the Flow dialog and try to select an item for the  "Collection Item Dropdown" field

### Directus Version

10.9.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by JoshTheDerf** [comment]
This is a workflow-breaking issue for us. :(

**Comment by rijkvanzanten** [comment]
(@JoshTheDerf For what it's worth, I believe the Vue ID is generated per build, so it should remain "stable" for the duration of 10.9.0)
