### ISSUE TITLE
many-to-any not deleting the junction record if an Article is deleted

### ISSUE THREAD

**Issue by bastion-tom** [directus/directus#21352]
### Describe the Bug

When an article is deleted outside of the component, the component doesn't remove the article. It just shows a blank article

![image](https://github.com/directus/directus/assets/156729968/03f3ffb4-76cc-4e24-a966-2f679ddf6f2a)

### To Reproduce

1. Create an article in an m2m/m2a.
2. Delete the related article
3. Open the original field again

### Directus Version

v10.8.3

### Hosting Strategy

Directus Cloud

**Comment by br41nslug** [comment]
It looks like you're referring to a many-to-many (or many-to-any) relation in which case did you set the delete triggers to anything other than nullify? which is what the screenshot looks like.

Closing this issue for now, but happy to re-open if more info becomes available.

**Comment by bastion-tom** [comment]
Still produces the same problem even with the relation trigger update

<img width="595" alt="image" src="https://github.com/directus/directus/assets/156729968/40f309a1-fe93-4ebe-9be1-4664ccc6230a">

**Comment by bastion-tom** [comment]
Any update on this?
