### ISSUE TITLE
PHP SDK create user permission issue

### ISSUE THREAD

**Issue by imknight** [directus/directus#2135]
## Version Info
  - Directus version and branch (Or commit hash):
  - PHP version: 7.2
  - MySQL version:  MariaDB  10.2.12
  - Web server: (Ex. Apache, nginx or IIS?)  Nginx
  - OS name and version: Mac High Seira

## Expected Behavior
trying to use the API create user, it should return a user object when success

## Actual Behavior
it return 403 forbidden error. 
Client error: `POST http://data.test/api/1.1/tables/directus_users/rows` resulted in a `403 Forbidden` response: { "success":false, "error":{ "message":"[Group #6 User #5] Write (set) access forbidden to table `directus_users 

## Steps to Reproduce
 1.  create user, given access to direct_user.
 2. doing the php sdk call using the user token.
 3. getting the 403 error.

**Comment by benhaynes** [comment]
Kamino cloned this issue to [directus/directus-sdk-php](https://github.com/directus/directus-sdk-php/issues/37)

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/47)
