### ISSUE TITLE
Webhook IP Denial Error after Upgrading to v10.9.0

### ISSUE THREAD

**Issue by dzevs** [directus/directus#21351]
### Describe the Bug

After upgrading our Directus instance from v10.8.3 to v10.9.0, our webhooks began failing with the error: "Requested URL resolves to a denied IP address". This issue was not present before the upgrade, and the webhook URLs have not changed. The problem causes all outbound webhook requests to fail, which is critical to our operations. Downgrading back to v10.8.3 resolves the issue, suggesting a regression or change in IP handling in the newer version.

![Screenshot from 2024-02-07 08-47-14](https://github.com/directus/directus/assets/25576759/95857e55-d321-40c6-8616-2f60d8fe7a7b)

#### Additional Context:
The issue was temporarily resolved by _downgrading_ to v10.8.3. We suspect there might be a change in how outbound IP addresses are handled or validated in the new version, which could be inadvertently blocking legitimate requests.

### To Reproduce

1. Upgrade Directus instance from v10.8.3 to v10.9.0.
2. Set up a webhook pointing to an external URL.
3. Trigger the webhook.
4. Observe that the webhook fails with the error message: "Requested URL resolves to a denied IP address".

### Directus Version

v10.9.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Could you check your `IMPORT_IP_DENY_LIST`[^1] config?

Also do you see additional information in the server logs? For example if the server failed to resolve the domain, it should get logged as `Couldn't lookup the DNS for URL ...`

[^1]: https://docs.directus.io/self-hosted/config-options.html#security

**Comment by dzevs** [comment]
Thank you for the prompt response. I have not explicitly set the `IMPORT_IP_DENY_LIST` configuration in my environment. I also attempted to set it to an empty string as a test, but the issue persisted.

Unfortunately, I did not capture the server logs at the time of the error. I will attempt to reproduce the issue and check the server logs for any messages that could provide further insight, especially any related to DNS resolution as you mentioned.

**Comment by dzevs** [comment]
Hello [@paescuj](https://github.com/paescuj) and team,

I've followed up on the issue and managed to capture the relevant server logs during the error occurrence. It seems that there is an issue with the `IMPORT_IP_DENY_LIST` configuration, even when it's not explicitly set or set to an empty string. Below is the snippet from the server logs:

```
buzzerstacks-directus-1 | [05:18:11] POST /flows/trigger/52dae981-39ef-4788-bb58-696e6fcf56a2 200 321ms
buzzerstacks-directus-1 | [05:18:11.120] WARN: Invalid "IMPORT_IP_DENY_LIST" configuration
buzzerstacks-directus-1 | [05:18:11.120] WARN: Cannot read properties of undefined (reading 'trim')
buzzerstacks-directus-1 | err: {
"type": "TypeError",
"message": "Cannot read properties of undefined (reading 'trim')",
"stack":
TypeError: Cannot read properties of undefined (reading 'trim')
at getIP (/directus/node_modules/.pnpm/ip-matching@2.1.2/node_modules/ip-matching/lib/ip.js:480:19)
at IPv4.matches (/directus/node_modules/.pnpm/ip-matching@2.1.2/node_modules/ip-matching/lib/ip.js:148:20)
at matches (/directus/node_modules/.pnpm/ip-matching@2.1.2/node_modules/ip-matching/lib/index.js:29:17)
...
}
```

This error seems to suggest that the application is attempting to access a `trim` method on an undefined variable, which I presume is related to the `IMPORT_IP_DENY_LIST`. The error persists regardless of whether the `IMPORT_IP_DENY_LIST` is unset or set as an empty string.

The linked pull request #21370 mentions a fix is on the way, which is great news. I appreciate the quick action on this matter. Thank you!

**Comment by ymc-sise** [comment]
@paescuj I still have the same error in 10.9.3. What am I doing wrong? I trigger a flow what calls a custom webhook endpoint on the same system:

```
{
  "url": "/custom-endpoint",
  "body": "$trigger.body.keys[0]",
  "headers": [
    {
      "value": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZiYjViYjc2LTdmODctNGQxYS1hMGM3LTdjOTc1Y2I5MGQxNCIsInJvbGUiOiJjMzEwZDM0Ni01MTM3LTRkMWYtYWIwNC0xOWFkNDVhYzkxOWIiLCJhcHBfYWNjZXNzIjoxLCJhZG1pbl9hY2Nlc3MiOjEsImlhdCI6MTcwOTkxNDMyMywiZXhwIjoxNzA5OTE1MjIzLCJpc3MiOiJkaXJlY3R1cyJ9.tltphDjdwhmsM2mV51_vznuU0u86K7aPoskMMX1iyuA",
      "header": "Authorization"
    }
  ]
}
```

results in

```
{
  "name": "Error",
  "cause": {
    "name": "Error",
    "stack": "Error: Requested domain \"localhost\" resolves to a denied IP address\n    at deniedError (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/request/agent-with-ip-validation.js:3:33)\n    at Socket.<anonymous> (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/request/agent-with-ip-validation.js:29:35)\n    at Socket.emit (node:events:517:28)\n    at GetAddrInfoReqWrap.emitLookup [as callback] (node:net:1359:12)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:8)",
    "message": "Requested domain \"localhost\" resolves to a denied IP address"
  },
  "message": "Requested domain \"localhost\" resolves to a denied IP address"
}
```

Some versions before everything was okay. I don't have any `IMPORT_IP_DENY_LIST` configured.

**Comment by paescuj** [comment]
By default, requests to local network interfaces are blocked for security reasons - see https://docs.directus.io/self-hosted/config-options.html#security.
If you really need to access "localhost", you need to override `IMPORT_IP_DENY_LIST`, for example by setting it to:
```ini
IMPORT_IP_DENY_LIST="169.254.169.254"

### default
# IMPORT_IP_DENY_LIST="0.0.0.0,169.254.169.254"
```
