### ISSUE TITLE
Display translated column content in translated table

### ISSUE THREAD

**Issue by mrleblanc101** [directus/directus#2136]
## Version Info
  - Directus version: 6.4.0
  - PHP version: 7.1
  - MySQL version: 5.7.21
  - Web server: nginx
  - OS name and version: macOS 10.13.4

If I follow the medium tutorial to setup translation in the official documentation, everything work.
The problem is that my main table only display the number of translation, not the column content in the admin using the default language (the one set in the settings for exemple).
Instead of seeing "Title: Project title" and "Body: Project body..." column, I see "Translation: 2" which is not very usefull since i have no way of knowing which item is which ! The ugly solution i found is having a "title" in my "projects" table and another "title" in my "projects_translation" table too, one which is translated, one which is not.

## Schema Dump, Logs, or Screenshots
![capture d ecran 2018-04-25 a 14 43 16](https://user-images.githubusercontent.com/17392251/39266274-8e3d9e58-4897-11e8-9e29-cd2ed849fd22.png)
![capture d ecran 2018-04-25 a 14 43 10](https://user-images.githubusercontent.com/17392251/39266275-8e48e5ba-4897-11e8-8b13-5dc9779fabb1.png)

**Comment by rijkvanzanten** [comment]
Hey @mrleblanc101! This is actually not a bug, but the intended behavior. However, I really like the idea you just mentioned. For "regular" users, it makes more sense to have the translated value shown, however, for admin users it might make more sense to show the total amount to give a better "unopinionated" view of the data.

**Comment by mrleblanc101** [comment]
Thanks for the reply.
But honestly, regular user or admin, you should be able to see the value of the translated content. Otherwise, how are you suppose to know which « Project » is which, open them all one by one ??? I don’t think having multiple « Title » column (one in both table, one translated and the other not) is the right solution.

**Comment by benhaynes** [comment]
Kamino cloned this issue to [directus/app](https://github.com/directus/app/issues/1038)

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/48)
