### ISSUE TITLE
Add new env variable for file uploads allow list

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#21375]
### Describe the Improvement

Right now we allow any file type to be uploaded in the system (on purpose!). However, for more heavily controlled instances, we should have an environment variable that allows the sys admin to control what specific file mimetypes are allowed to be uploaded.

**Comment by paescuj** [comment]
Maybe I'm misunderstanding something, but I think we already have `FILES_MIME_TYPE_ALLOW_LIST` [^1] for that purpose.

Slightly related issue: #17123

[^1]: https://docs.directus.io/self-hosted/config-options.html#upload-limits
