### ISSUE TITLE
Issue with redirects when using an AWS ELB

### ISSUE THREAD

**Issue by GerMcMahon** [directus/directus#2139]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus version and branch (Or commit hash): 6.4.9
  - PHP version: 7.0.28
  - MySQL version: 5.7
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: Ubuntu 16.04

## Expected Behavior
I have Directus install on 2 AWS EC2 instances and when i login in to either instances directly with the IP (e.g. xx.xxx.xx.xxx/directus/login.php) I get the login screen and i am able to successfully login.

However when i put an AWS ELB (either application or classic) in front of the EC2 issues, I am unable to login in. I hit login via the elb address (e.g. xxxxxxxxxxx-us-east-1.elb.amazonaws.com/directus/login.php) and i am directed to the login page successfully. I then enter credentials and press login. I then receive an error with too many redirects and I am unable to login.

## Steps to Reproduce
 1. 
 2. 
 3. 

## Schema Dump, Logs, or Screenshots

![image](https://user-images.githubusercontent.com/2283784/39423738-348b58be-4c6b-11e8-8fc4-21b93565c4a9.png)

![image](https://user-images.githubusercontent.com/2283784/39423818-aaa7b84e-4c6b-11e8-9d06-a6975b6b9b73.png)

It keeps looping around the login.php and /directus/

![image](https://user-images.githubusercontent.com/2283784/39423918-15b373bc-4c6c-11e8-98cc-2a135d68dda8.png)

![image](https://user-images.githubusercontent.com/2283784/39423942-381a9dcc-4c6c-11e8-92bb-6e9d284ca1db.png)

**Comment by bjwyse** [comment]
On a side note I am struggling to install the latest version of Directus on a similar setup on EC2 and having a lot of issues. I don't suppose you can share the setup steps?

**Comment by GerMcMahon** [comment]
I manage to figure that directus must maintain session state on the server that serves the login. If you front directus with a load balancer with round robin, then the second instance does not know about the login and presents the login page. If you set the load balancer to have session stickiness then all works.

My apologies but my installation is scripted now in our companies automation so I am not able to provide.

I just followed the information from the directus install instructions and that was all clear and worked.

**Comment by rijkvanzanten** [comment]
Hey @GerMcMahon! Good to hear that you figured it out 🙂 Directus 6.x indeed uses sessions to manage login state. From the next major version onwards we move away from sessions in favor of an access token based system (JWT), so that hopefully solves problems with load balancers too 👍

**Comment by GerMcMahon** [comment]
That is great news. Will their be an authentication module that can integrate with something like ldap or enterprise token authorities.

**Comment by GerMcMahon** [comment]
Apologies, I meant if we will be able to integrate to enterprise authentication systems for single signon. Enterprise's may have LDAP and OAuth token authorities who create the token based on the users credentials.

**Comment by benhaynes** [comment]
@GerMcMahon – Our SSO system is modular, so you can create any new services that needed.

SCIM supports Active Directory (AD). Since LDAP is just a protocol for communicating with AD then in principle that should also work.
