### ISSUE TITLE
Folder translation overlay bug

### ISSUE THREAD

**Issue by LevelUpGit** [directus/directus#21399]
### Describe the Bug

When adding folder for collections and translation for it slide out window for translation is not accessible. 
![Screenshot_11](https://github.com/directus/directus/assets/69863985/1e398439-b9dc-44ff-b26e-cffd3edbd540)

### To Reproduce

1. Go to data mode
2. Make a folder
3. Add translation for it

### Directus Version

v10.9.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
This has already been fixed in #21368 which will be available with the next release 👍
