### ISSUE TITLE
Meta Title: Why do we have "Directus · <Project Name>" now?

### ISSUE THREAD

**Issue by A4TIF** [directus/directus#21394]
### Describe the Bug

Previously, we had dynamic meta titles for each page. If I moved around the collections, the tab names were obvious. With recent release, it is static showing "Directus · <Project Name>". This is annoying as I work on multiple tabs using Directus.

This needs to revert back to what it was before! There's no need to add Directus there, just the project name was good enough as suffix along with the actual collection / settings page title.

### To Reproduce

Run the latest version and check meta title for each page as reflected in the tab names.

### Directus Version

v10.9.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
I'm assuming something went awry when updating the dependencies. This is not something that was actively changed afaik 🤔
