### ISSUE TITLE
Dropdown: Status, Default Configuration Error

### ISSUE THREAD

**Issue by JugaadiTek** [directus/directus#21409]
### Describe the Bug

With Color Match theme, Have not tested with others yet.
`Background Color` has an unexpected value on the display configuration
![image](https://github.com/directus/directus/assets/106853815/62c65167-09b5-4e80-8653-1f7d24ef65ab)

### To Reproduce

1. Create a new Collection
2. Select the default Field "status"
3. Configure the display

### Directus Version

10.9.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by DanielBiegler** [comment]
Hi there & thanks! Can confirm, it leads to:

```
Error: Unable to parse color from string: color-mix(in srgb, #fff, #E35169  10%)
```

Which then crashes that interface and leads to the error message.

**Comment by DanielBiegler** [comment]
Just to clarify upon my last comment: @JugaadiTek & others, in case you want/need to make it work before theres a fix from our side, theres a workaround. If you change the variable you want to use, for example primary-background, to a proper CSS color then the form-fields wont error out on you. Go to the Appearance Settings and under your Light/Dark Theme Customizations inside `globals` you can set the `primaryBackground` to something like for example `#FFFFFF`.

For maintainers/contributors: You gotta fix `useColor` inside of `select-color.vue`, thats where `Color()` throws

**Comment by rijkvanzanten** [comment]
> For maintainers/contributors: We gotta fix useColor inside of select-color.vue, thats where Color() throws

Most likely the same issue that existed in the color display! Added a try/catch here around the color usage: https://github.com/directus/directus/blob/f7b11b9a49d2d08e799903cc5f28c430a0b8d855/app/src/displays/color/color.vue#L22-L30

**Comment by hanneskuettner** [comment]
We could consider switching to `colorjs.io`[^1] which seems to be a more spec compliant (though less used) implementation of color parsing that also does not support CSS Color Level 5, but at least all of Level 4 and is extendable with hooks, so we could roll our own `color-mix` parsing.

[^1]: https://github.com/color-js/color.js
