### ISSUE TITLE
Singleton sidebar doesn't show flows

### ISSUE THREAD

**Issue by LevelUpGit** [directus/directus#21402]
### Describe the Bug

Singleton collection doesn't show flows assigned to it.

### To Reproduce

1. Create singleton collection and add some fields
2. Create manual flow and assign it to singleton

### Directus Version

v10.9.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
I am unable to reproduce this. 

https://github.com/directus/directus/assets/9389634/4e148124-a0ea-4ab1-8651-ac9a9e6ff9f4

**Comment by LevelUpGit** [comment]
My bad, you have to save one filed in singleton to be able to see right sidebar. Maybe add note or something before.
![Screenshot_12](https://github.com/directus/directus/assets/69863985/d0b33f04-b4c7-46da-a443-29debc784ec3)
