### ISSUE TITLE
Question about many to many relation

### ISSUE THREAD

**Issue by dramosBC** [directus/directus#2140]
I have added a many to many relation in order to test the application. 

. Content 
   . id
   . title
   . description

. Metadata
   . id
   . name

. Content_Metadata
   . content_id
   . metadata_id
   . value (*)

I've set a many to many relation between Content & Metadata. As a result, I can choose the metadata into the Content form. This is ok, but in my case I need to complete the field "value" (*) that should be save into Content_Metada.

Is there a way to do this directly with the tool?
What about the one to one relations? Is there a way to implement it?

Best

**Comment by rijkvanzanten** [comment]
Hey @dramosBC. The current implementation of the many to many interface doesn’t support setting fields in the junction table as well directly. You could edit the fields in the junction table directly, or copy the many to many interface and create your own custom implementation to support this feature.

The core directus team is working full time on getting the next major version of the platform (7) ready for launch. Next to support for many-to-many-many relations (sometimes refered to as _matrix fields_, I would love to natively support this feature in the next version of the platform.

**Comment by dramosBC** [comment]
Thanks... Meanwhile, I while take a look to how to implement this with an interface.

**Comment by janokay** [comment]
Hello, I'm trying to archive the same thing.
Is there a way now to edit additional values assigned to the many-to-many junction?
Thank you very much for your work & help!

**Comment by rijkvanzanten** [comment]
@janokay there's no way to edit additional rows in the junction table of a m2m relationship

**Comment by benhaynes** [comment]
@janokay — you can upvote that here: https://github.com/directus/app/issues/761
