### ISSUE TITLE
Entry js file takes a long time (minutes) to load

### ISSUE THREAD

**Issue by lucastoneatto** [directus/directus#21416]
### Describe the Bug

Script: /admin/assets/index.chbv01TP.entry.js

I deployed Directus in a DO droplet and after the first page load (which takes a long time) it works normally, but if I open another browser it takes a long time again.
And it's not that the droplet sleeps because I'm using it in parallel in another browser
Which may be?

The weird thing is that once it loads everything, it never does it again.
For example, when it was already working fast, I associated it with a domain. And when I wanted to access from the domain the same thing happened to me again regarding the loading time
I am concerned that this will happen to every person who wants to connect to the system for the first time.

When I try to connect from a cell phone the same thing happens, that's why I'm worried about whether it will happen on the first connection of each device.

### To Reproduce

I have this droplet to test Directus deployment
http://64.23.140.229:8055/
http://slickbud.com:8055/

### Directus Version

10.9.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
This is heavily dependent on server infrastructure, CDN usage, and local internet speeds I'm afraid.. Lowering the bundle size for the Directus app itself is a longer term ongoing goal which will help this a bit as well (by spreading the download over multiple files), but I'll close this issue for now as there's no one specific bug we can resolve.
