### ISSUE TITLE
How to create an event between two custom interface

### ISSUE THREAD

**Issue by tumraja** [directus/directus#2141]
## Version Info
  - PHP version: 7.1
  - MySQL version: 5.6
  - Web server: nginx
  - OS name and version: macOS Sierra

## Expected Behavior
I have created two different custom interface which are extending the core CustomUIView and UIComponent. The new customs interface are located in the custom folder as follows:

customs/interfaces/my-custom-interface-1 (dropdown)
customs/interfaces/my-custom-interface-2 (dropdown)

The values on the my-custom-interface-2 are affected based on the selection on the my-custom-interface-1.  

The behaviour, I would like to archive here is to have an event that is initiated from my-custom-interface-1 and then listen this event in the my-custom-interface-2.

Please, How can I archive this?

**Comment by rijkvanzanten** [comment]
You can target the elements in the DOM directly, add an eventlistener to your own no.1 input and set the changes in your no.2 interface on change of the first.

Directus 6 has no internal way of listening / reacting to other interfaces.
