### ISSUE TITLE
Can't update primary key

### ISSUE THREAD

**Issue by bastion-tom** [directus/directus#21413]
### Describe the Bug

The content slug is not being updated. I'm able to edit the slug and click save, however the changes to take affect

### To Reproduce

Edit the slug and click on save.

### Directus Version

v10.8.3

### Hosting Strategy

Directus Cloud

**Comment by rijkvanzanten** [comment]
I'm not entirely sure what you mean.. There's no default slug field in the platform, so I'm assuming you have a custom collection with a custom slug field. Could you share some more details on how we'd be able to reproduce your issue?

**Comment by bastion-tom** [comment]
@rijkvanzanten 

![image](https://github.com/directus/directus/assets/156729968/f7078fea-be4d-4d44-b4fb-bdce826b33b2)
If I change this to "slug2" and update, it will go back to "slug1"

**Comment by bastion-tom** [comment]
@rijkvanzanten 

I take it as it's the primary key so it won't save? if so, is there anyway around this?

Can't seem to find any permission issues etc..  I'm using the admin role too

![image](https://github.com/directus/directus/assets/156729968/f142b31b-e672-4946-9bbe-4ba94d3720e9)
![image](https://github.com/directus/directus/assets/156729968/db2d65a1-235c-4f60-9e88-fc410666e353)
![image](https://github.com/directus/directus/assets/156729968/fc209c73-d351-40bf-9aec-cef332571a3a)

**Comment by br41nslug** [comment]
The big thing would be to not use primary keys for values you may want to update. The workaround is to edit the primaryKey then "save as copy" and then delete the old one.

**Comment by rijkvanzanten** [comment]
Ah that's correct then. The primary key can't be updated currently. I'd recommend using a regular unique identifier as the primary key, and making the slug a common field if you're planning on updating it over time 👍🏻
