### ISSUE TITLE
Migration between environtments

### ISSUE THREAD

**Issue by dramosBC** [directus/directus#2142]
Hi guys, I am testing directus in my local computer and I would like to know if there is a way (plugin or something) to migrate the new tables that I've created with all the information that I've filled on it to a staging server and so on.

I ask this because I feel like if I create a script for migrate the DB I will loose some stuff in the middle.

Best

**Comment by rijkvanzanten** [comment]
Hey @dramosBC! We don’t have a native way of exporting / importing data between environments yet. You should be good by just copying over the raw DB records from one env to another.

**Comment by lennerd** [comment]
Are there any plans on supporting migrations between environments? What are you guys doing when working on client projects and different envs with different schemes?

**Comment by rijkvanzanten** [comment]
We have an open feature request to be able to export / import the schema and data, so migrations between environments will be easier:

https://github.com/directus/api/issues/31

**Comment by lennerd** [comment]
Thanks for the link and the quick response!

Still, still whould be nice to hear your ideas and best practices on how to handle migrations between envs in the current state of Directus. If you like to share them of course. 😉

**Comment by rijkvanzanten** [comment]
For me personally the demands of what to migrate and what not have been so diverse that i have been doing manual database dumps / imports of specific tables ^^

**Comment by prasadbandur** [comment]
Hi @directus team, even I/we are also looking if there is any option to migrate DB schema of directus to another environment. I feel this is the most important feature, as no one wants to re do the same manual steps to create schema in PROD also. Let us know if you have any plan to release that feature. Thanks in advance. Regards, Prasad

**Comment by benhaynes** [comment]
We're discussing internally how this should be handled, and plan to include it in version 9. Though it probably won't be in the initial release, it should come sooner after. If you have any insight into how you'd like to see this feature used, or how it should be implemented, please post on the relevant discussion in `directus/next` repo.

**Comment by nithiz** [comment]
@benhaynes Do you have a link to that discussion? I can't find it.

**Comment by WoLfulus** [comment]
I copied over an old repository issue to the latest discussion to keep it visible

https://github.com/directus/directus/discussions/2984
