### ISSUE TITLE
SDK method updateMe: request header sent Content-Type:  text/plain;charset=UTF-8 

### ISSUE THREAD

**Issue by Drunkenpilot** [directus/directus#21426]
### Describe the Bug

SDK method:  **updateMe**
Request header sent by default.

> Content-Type:  text/plain;charset=UTF-8

No update has been made

### To Reproduce

"@directus/sdk": "^15.0.0"

```typescript
const directus = createDirectus<CustomDirectusTypes>(
   DIRECTUS_URL
).with(rest());

const body = {last_name: 'Demo'};
const accessToken = 'a_token';

 const data = await directus.request(
      withOptions(updateMe(body), {
        headers: {
          "Content-Type": "application/json",    // content can only be updated with this option
          Authorization: `Bearer ${accessToken}`,
        },
      })
    );
```

### Directus Version

10.9.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
The SDK defaults to `"Content-Type": "application/json"` however the `withOptions` helper allows you to override these defaults (it looks like you're overwriting the entire `header` list with you're custom headers). If you simply intend to add a token to your request i recommend either the `staticToken` composable or the `withToken` handler.

https://docs.directus.io/guides/sdk/authentication.html#set-a-token-for-single-requests
