### ISSUE TITLE
Closing because of GOaway and rst stream

### ISSUE THREAD

**Issue by SalishKumar** [directus/directus#21438]
### Describe the Bug

I am getting 400 bad request frequently error while uploading files
![image](https://github.com/directus/directus/assets/54025715/3bc64820-41ec-44c3-b9c5-3f1853c7b67f)

### To Reproduce

It is not happening always but it is frequent while uploading files

### Directus Version

v10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by azrikahar** [comment]
Are you using a particular hosting or proxy in your setup? I'm under the impression that the error shown in the screenshot is not directly from Directus, but rather something else in between. That being said,

- would you be able to provide any errors/logs from the Directus container instead?
- do you mind trying with the latest version of Directus (10.9.2 as of now)?
- what storage provider are you using for files?

Closing this for now as we do not have enough information to diagnose what could be going on here, but we'll re-open once more information arises and it is confirmed to be a bug in Directus.

**Comment by SalishKumar** [comment]
@azrikahar I am not using any proxy server and here are docker logs
1, <img width="281" alt="image" src="https://github.com/directus/directus/assets/54025715/fcd30c52-7bb9-4f41-9649-537174d94993">
2, sure will try 
3, local disk (can that be an issue?)
