### ISSUE TITLE
JSON type on M2M field with <collection>_by_version query 

### ISSUE THREAD

**Issue by Abusoss** [directus/directus#21447]
### Describe the Bug

I wanted to retrieve the categories of an article using the <collection>_by_version query. Simple fields like a string or a JSON return fine, but if you have an picture it only return the id, maybe this is intended. Well when you have an M2M field it always return a an array of JSON. This JSON is composed of the current item id(in this case the article id) and a integer id. I suspect that it return the junction of the M2M relation.

### To Reproduce

1. Install directus 10.9.2 locally with docker or just with npm or pnpm, i use a local postgreSQL database but it doesn't matter, use any supported  database you want.

2. add a new collection named Article :
![image](https://github.com/directus/directus/assets/9333311/4035da78-f99d-465c-85f7-dce8649e5032)
![image](https://github.com/directus/directus/assets/9333311/41d2ed93-f3e7-4830-a49c-cd9070f2fca4)

3. add a new collection named Category the same way :
![image](https://github.com/directus/directus/assets/9333311/c541eec2-893d-4afc-a240-eacf86ea8fa4)
![image](https://github.com/directus/directus/assets/9333311/5f0baf4d-cdfe-411a-8cb3-87e854f76380)

4. add a new field "name" in the Category collection : 
![image](https://github.com/directus/directus/assets/9333311/be95493e-fcc7-4cdb-80f7-705d37537af6)

5. add a new M2M field named "categories" to the Article collection like so : 
![image](https://github.com/directus/directus/assets/9333311/dc8ec58f-e859-4e02-8724-6bc1d597ac25)

6. Enable versionning in the Article collection
7. Give the public role permission to look at those collection and the system collection "directus_versions"
8. Create a new article with a new category

9. use any API testing tool, i use hoppscotch, and make this request using graphql at the url http://localhost:8055/graphql:

```
query{
	article_by_version(id:"TheIdOfYourArticle",version:"main"){
      categories
    }
}
```

This will be the response(it looks like the junction data) : 

```
{
  "data": {
    "article_by_version": {
      "categories": [
        {
          "article_id": "TheIdOfYourArticle",
          "id": 1
        }
      ]
    }
  }
}
```

Specifying the name field is not possible because categories is of type JSON where it should be of type Category.
So this doesn't work : 
```
query{
	article_by_version(id:"TheIdOfYourArticle",version:"main"){
      categories{
        name
        id
    }
}
```

### Directus Version

v10.9.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
when accessing the `main` branch (or the regular item) you should use the `*_by_id` query to get the proper types, for any other but the `main` branch this type is correct.
