### ISSUE TITLE
Invalid query when # char is present

### ISSUE THREAD

**Issue by davibaldin** [directus/directus#21442]
### Describe the Bug

The bellow filter will not work:

```
?filter={"_and":[{"status":{"_nin":["Resolved"]}},{"summary":{"_contains":"Fwd: #"}}]}
?filter={"_and":[{"status":{"_nin":["Resolved"]}},{"summary":{"_contains":"Fwd: [Ticket#2024021444999138] [Vulnerabilidades críticas] - XXX_221"}}]}
```

Result:

```json
{
    "errors": [
        {
            "message": "Invalid query. Invalid filter key \"_eq\" on \"issue\".",
            "extensions": {
                "code": "INVALID_QUERY",
                "reason": "Invalid filter key \"_eq\" on \"issue\""
            }
        }
    ]
}
```

### To Reproduce

http://directus/items/issue?filter={"_and":[{"status":{"_nin":["Resolved"]}},{"summary":{"_contains":"Fwd: #"}}]}

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
This is because `#` is a special character in URLs (similar to `/` and `?`). Make sure to URL encode any payloads/arguments that may have these special character in them https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI

> http://directus/items/issue?filter=%7B%22_and%22%3A%5B%7B%22status%22%3A%7B%22_nin%22%3A%5B%22Resolved%22%5D%7D%7D%2C%7B%22summary%22%3A%7B%22_contains%22%3A%22Fwd%5D%28http%3A%2F%2Fdirectus%2Fitems%2Fissue%3Ffilter%3D%257B%2522_and%2522%3A%255B%257B%2522status%2522%3A%257B%2522_nin%2522%3A%255B%2522Resolved%2522%255D%257D%257D%2C%257B%2522summary%2522%3A%257B%2522_contains%2522%3A%2522Fwd%29%3A%20%23%22%7D%7D%5D%7D
