### ISSUE TITLE
Can't Login After Installation - get 404 Error

### ISSUE THREAD

**Issue by BenSegni** [directus/directus#2144]
**For security issues, please email support@getdirectus.com directly.**

## Version Info
  - Directus version: 6.4.9
  - PHP version: 5.7
  - Web server: Apache

## Expected Behavior
Click login, access GUI

## Actual Behavior
Click Login Button - this error: 
http:/my_url/projects/calculator/cms/api/1.1/auth/login 404 (Not Found)

I've followed the instructions to installing directus using filezilla, where I am currently testing the success of an application I have built locally. I have tried to deploy the cms several times have been met with the same error. I have the config set up correctly (I think) and am still getting this error.

**Comment by rijkvanzanten** [comment]
Hey @BenSegni! Could you confirm the `directus_path` is setup right?

https://github.com/directus/directus/blob/master/api/config_sample.php#L31

**Comment by rijkvanzanten** [comment]
Is apache setup correctly with mod_rewrite? Maybe the API URL doesn't get rewritten to the correct format?

**Comment by rijkvanzanten** [comment]
It's most likely a configuration issue on your specific instance..

**Comment by BenSegni** [comment]
So from an installation perspective, the ftp from the latest build went without an issue. I noticed that the ModRewrite was marked as No once the database details had been entered, but as I understand it, this is a bug and installation completed with no problem.

I will contact my technical support to see if this is the issue RE: Apache and relay back to you.

**Comment by BenSegni** [comment]
Hi @rijkvanzanten, I have just spoken with my technical support and can confirm: Apache is running on the server and mod_rewrite permissions are also in place.

**Comment by rijkvanzanten** [comment]
@BenSegni Did you copy over the `.htaccess` files? That's what controls the rewrites.

All requests to `/api/<whatever>` are remapped to `/api.php` by those files. I know some FTP clients hide hidden files (starting with `.`) by default..

**Comment by BenSegni** [comment]
Hi @rijkvanzanten yes, the .htaccess files are there too. I unchecked Rewrite in the root directory .htacces but this didn't fix it.

**Comment by WellingGuzman** [comment]
@BenSegni How does the `VirtualHost` looks like? can you take a look at the VirtualHost our docker uses: https://github.com/directus/directus-docker/blob/master/directus-base-layer/etc/apache2/sites-available/000-default.conf

**Comment by WellingGuzman** [comment]
Oh I see you don't have access to the server. How did you install Directus?

**Comment by BenSegni** [comment]
Hi I installed Directus via ftp - uploaded the most recent build to my server.

**Comment by BenSegni** [comment]
@WellingGuzman I used your medium post to install. To give some context, this is a LAMP Bundle on shared hosting, not cloud hosted.

**Comment by BenSegni** [comment]
@WellingGuzman @rijkvanzanten Hi Guys, have you any more suggestions or things we could look at to get to the bottom of why this is not working? Many thanks in advance.

**Comment by BenSegni** [comment]
@rijkvanzanten @WellingGuzman I have contacted my hosting provider who have run a fresh install and have returned the following correspondence: 
"This is an update regarding your case with the directus installation. As we have tried this on our end to also install manually. We get the same error message after installing and trying to log in. We will be forwarding this case our our administrators in order for them to check if this CMS is possible to run on the shared hosting package, Since all the requirements are met by our server."

I would appreciate some help on this if possible. Many thanks.

**Comment by rijkvanzanten** [comment]
What is the hosting provider you use? Is there a way we can reproduce the exact same setup? We’ve used the platform on multiple different environments (including shared hosts) but never ran in to this specific issue 😞

Love to get it sorted out!

**Comment by BenSegni** [comment]
Hi @rijkvanzanten I am on slack and happy to set you up with a ftp account (and send them to you via DM?) to reproduce the issue? I host with 1and1.co.uk. Could that work?

**Comment by BenSegni** [comment]
A quick update, have placed an ssl over the domain and this hasn't fixed it, sadly. 

I have run an additional test deployment at a higher level on the server and the post method still doesn't complete. This one is just one directory down. 

I have a db and ftp user account set up if @rijkvanzanten would like to see what is causing the issue. 

I am working with php 7, mysql 5.5 and Apache. It's on a shared hosting platform with 1and1.co.uk.

**Comment by rijkvanzanten** [comment]
Good to hear @BenSengi!! 

@wellingguzman, I’ve never had or heard of this problem with the htaccess file when using it in a sub folder before. Can we checkout whats up with that? 

Thanks for helping out what’s causing this @BenSengi

**Comment by WellingGuzman** [comment]
Yeah we actually had experience this before (See a [comment here](https://github.com/directus/directus/blob/master/api/.htaccess#L7-L8) in the `.htaccess`). I don't recall correctly what it was but I think it was related to how the VirtualHost was configured.

@BenSegni Can you show us how you VirtualHost looks like?

**Comment by BenSegni** [comment]
Hi @rijkvanzanten @WellingGuzman - so the install was a fresh one onto a shared hosting platform, so unfortunately, I don't have access to these config files. Not working in the cloud. :/ 

I followed the article @rijkvanzanten wrote on medium (working with ftp) and actually sent the problem over to my hosting providers, as I was totally lost as to why this wasn't working. They found the solution. 

I can show you my own virtual host file on my local machine, but this may not be useful. 

I think Directus is great and I have another project backed up to use it for again. The rationale for the bombardment (which I apologise for) was to successfully implement the product onto a live server as a test - as this will be my maiden voyage with Directus. I have to deploy this product to Live, along with it's front end tomorrow (which will in fact, be housed on Digital Ocean) - I have a dev ops guy to assist in the implementation tomorrow also. 

I'm not sure if this helps in the future, but thanks for all the great work on this - it's going to be such a great tool for projects moving forward. :) I hope to have a great use case to show you very soon. Thanks again.

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/49)

**Comment by byt3-m3** [comment]
> comment here

Hello is it possible to get the .htaccess file?, I am currently having the same issue

**Comment by rijkvanzanten** [comment]
@byt3-m3 this issue related to an older version of Directus. Please open a new issue if you have any problems with Directus 7+
