### ISSUE TITLE
Bug: create-directus-project fails in Node.js 20.x

### ISSUE THREAD

**Issue by totallygideon** [directus/directus#21445]
### Describe the Bug

In commit 206a7ca the minimum Node.js version to run `create-directus-project` was raised to 18.17.0 and [a check was added](https://github.com/directus/directus/commit/206a7cae0b4b5da292f90dbda7b8130fcc61e6be#diff-b2382970aa5e345ef6ce5dd05444b777794b34f67893646e1ec8b9da84ac9be1) to make sure the version was >18.17.

```javascript
const nodeVersion = process.versions.node.split('.');
const major = +nodeVersion[0];
const minor = +nodeVersion[1];

if (major < 18 || minor < 17) {
    // ...error
}
```

On Node.js v20.x.x this check fails as the latest version is 20.11.1 (minor = 11).

### Possible fix
```javascript

if (major < 18 || (major === 18 && minor < 17)) {
    // ...error
}
```

### To Reproduce

- Install latest Node.js LTS (20.11.1)
- Run `create-directus-project`

![image](https://github.com/directus/directus/assets/47083178/0e6bac3d-0802-4987-8c92-d81d49a1d063)

### Directus Version

v10.9.2 (create-directus-project v10.0.3)

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
We don't support Node.js v20 yet, see https://docs.directus.io/self-hosted/cli.html#requirements.
The requirements check in `create-directus-project` will be updated once we officially support Node.js v20 👍
