### ISSUE TITLE
Quickstart guide npm install failed

### ISSUE THREAD

**Issue by ad-sarang** [directus/directus#21451]
### Describe the Bug

The quickstart commad install by npm do not work. Gives our error for updating the node version even if the the node version is updated. 
![image](https://github.com/directus/directus/assets/148765889/762f65cf-9680-45dd-9207-031ad2f012e6)
my node version is greater than 18.16 still it gives out to update the node version

### To Reproduce

npm init directus-project@latest SampleProject

### Directus Version

latest

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
We don't support Node.js > 18 yet - see https://docs.directus.io/self-hosted/cli.html#requirements.
The requirement check in `create-directus-project` will be updated once we officially support Node.js v20 👍

**Comment by ad-sarang** [comment]
Thanks, @paescuj, I tried different versions it worked by the version 18.19.1 of node.
