### ISSUE TITLE
Customize title of the login page

### ISSUE THREAD

**Issue by Xinnerpeace** [directus/directus#21469]
### Describe the Improvement

the "Directus" part in the title of login page to be customizable.
Currently, it shows "Directus · {{ Project Name }}" in the tab next to the favicon.
>![image](https://github.com/directus/directus/assets/69332224/f5cb39eb-3578-43a1-a96f-dbba7c7c138d)

**Comment by br41nslug** [comment]
I have my doubts about making this configurable just for the login page. The `Directus ·` part is dynamic too depending on the page you're looking at.

For the moment you can use an `embed` extension to overwrite the document title.

**Comment by Xinnerpeace** [comment]
> I have my doubts about making this configurable just for the login page. The `Directus ·` part is dynamic too depending on the page you're looking at.
> 
> For the moment you can use an `embed` extension to overwrite the document title.

I understand your point, it's not necessary to make it configurable.
But this makes it harder for the project to be truly white-labeled. 
I suggest changing the "Directus" part in login page to other text like "Login".
