### ISSUE TITLE
Errors when translating texts

### ISSUE THREAD

**Issue by wfpaisa** [directus/directus#21463]
### Describe the Request

Before translate:
![image](https://github.com/directus/directus/assets/1735752/0cfac5d7-f6f4-4439-8ad9-094fd5cd39e1)

After translate:
![image](https://github.com/directus/directus/assets/1735752/4551bc7f-4d00-4c9c-8a79-ea5ea7803787)

### Maintainence Strategy

it would be very good to add the tag: translate=no to the icons, as indicated in the documentation.

Thank you very much:
https://github.com/angular/components/pull/14889

**Comment by DanielBiegler** [comment]
Thank you for the suggestion, nice little improvement!
