### ISSUE TITLE
Bug DB Upgrade from 6.4.8 to 6.4.9 doesn´t work

### ISSUE THREAD

**Issue by MaximilianUE** [directus/directus#2146]
```
Warning: mysqli::__construct(): (HY000/2002): No such file or directory in /Users/mbecher/Sites/da.localhost/web/directus/vendor/directus/migrations/lib/Ruckusing/Adapter/MySQL/MySQLBase.php on line 1296

Fatal error: Uncaught 
MySQLBase.php(1298) : 

Could not connect to the DB, check host / user / password



  thrown in /Users/mbecher/Sites/da.localhost/web/directus/vendor/directus/migrations/lib/Ruckusing/Adapter/MySQL/MySQLBase.php on line 1298
```

**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus version and branch (Or commit hash): 6.4.8 to 6.4.9 
  - PHP version: 7.1
  - MySQL version:  Ver 14.14 Distrib 5.7.20
  - Web server: (Ex. Apache, nginx or IIS?) .localhost
  - OS name and version: mac OS high sierra 10.13.4

## Expected Behavior
updating via git pull and then being able to update my Database via 
`$ bin/directus db:upgrade`
after composer install.

## Actual Behavior
Returns error (see top)

**Comment by DanielRuf** [comment]
webserver: Apache

**Comment by rijkvanzanten** [comment]
Heya! Could you try reinstalling the vendor dependencies just to make sure there isn’t anything funky going on in there? You should be good by deleting the vendor folder and running `composer install`. Lemme know if that helped 🙂

**Comment by MaximilianUE** [comment]
Composer install run without an error. Unfortunately the error stays

`composer install  `
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 32 installs, 0 updates, 0 removals
  - Installing psr/simple-cache (1.0.1): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing league/flysystem (1.0.45): Loading from cache
  - Installing doctrine/cache (v1.7.1): Loading from cache
  - Installing cache/cache (1.0.0): Loading from cache
  - Installing directus/migrations (dev-master 5a0a884): Cloning 5a0a8843de from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
  - Installing intervention/image (2.4.1): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.3): Loading from cache
  - Installing league/oauth1-client (1.7.0): Loading from cache
  - Installing paragonie/random_compat (v2.0.12): Loading from cache
  - Installing league/oauth2-client (2.3.0): Loading from cache
  - Installing league/oauth2-facebook (2.0.1): Loading from cache
  - Installing league/oauth2-github (2.0.0): Loading from cache
  - Installing league/oauth2-google (2.2.0): Loading from cache
  - Installing slim/slim (2.6.2): Loading from cache
  - Installing slim/extras (dev-master 06ecb8d): Cloning 06ecb8d5bf from cache
  - Installing swiftmailer/swiftmailer (v5.4.9): Loading from cache
  - Installing twig/twig (v1.35.3): Loading from cache
  - Installing zendframework/zend-stdlib (3.2.0): Loading from cache
  - Installing zendframework/zend-db (dev-directus ef55371): Cloning ef55371343 from cache
  - Installing phpunit/php-token-stream (1.2.2): Loading from cache
  - Installing symfony/yaml (v2.8.39): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (1.2.3): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing phpunit/php-code-coverage (1.2.18): Loading from cache
  - Installing phpunit/phpunit (3.7.38): Loading from cache
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
league/flysystem suggests installing spatie/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing srmklive/flysystem-dropbox-v2 (Allows you to use Dropbox storage for PHP 5 applications)
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
cache/cache suggests installing ext-apc (APC extension is required to use the APC Adapter)
cache/cache suggests installing ext-apcu (APCu extension is required to use the APCu Adapter)
cache/cache suggests installing ext-memcache (Memcache extension is required to use the Memcache Adapter)
cache/cache suggests installing ext-memcached (Memcached extension is required to use the Memcached Adapter)
cache/cache suggests installing ext-mongodb (Mongodb extension required to use the Mongodb adapter)
cache/cache suggests installing ext-redis (Redis extension is required to use the Redis adapter)
cache/cache suggests installing mongodb/mongodb (Mongodb lib required to use the Mongodb adapter)
intervention/image suggests installing ext-imagick (to use Imagick based image processing.)
intervention/image suggests installing intervention/imagecache (Caching extension for the Intervention Image library)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
slim/slim suggests installing ext-mcrypt (Required for HTTP cookie encryption)
zendframework/zend-db suggests installing zendframework/zend-eventmanager (Zend\EventManager component)
zendframework/zend-db suggests installing zendframework/zend-hydrator (Zend\Hydrator component for using HydratingResultSets)
zendframework/zend-db suggests installing zendframework/zend-servicemanager (Zend\ServiceManager component)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.0.5)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
```

After some research I´ve found out that it might have the "host"-name. 
In `ruckusing.conf.php`
it reads:
>  'host' => defined('DB_HOST') ? DB_HOST : 'localhost',

I´ve tried to change it to da.localhost (my actual project name) but it doesn´t seem to work... 
Maybe I need to "reinstall" the config or something?

the Directus-Update itself works fine, just my database isn´t able to get updated.

**Comment by WellingGuzman** [comment]
Hey @MaximilianUE, unfortunately Ruckusing uses `mysqli` and some php 7 installation has this extension disabled. You have to enable `mysqli` on your php environment.

**Comment by WellingGuzman** [comment]
If you are using MAMP take a look at this [comment](https://github.com/directus/directus/issues/1954#issuecomment-344365593)

**Comment by DanielRuf** [comment]
Afaik we have mysqli enabled (it is in phpinfo and enabled).

**Comment by DanielRuf** [comment]
We also do not use MAMP. We use Boxen + Apache. Not sure why this issue was closed then as this does not help so far. The `php` binary is available on the path.

**Comment by WellingGuzman** [comment]
@DanielRuf probably is disabled on the cli version of your php. Run `which php` and see which php are you using and `php --ini` to locate the `php.ini`

**Comment by WellingGuzman** [comment]
We can keep the conversation, I closed it as this is probably the same issue we have experienced before. The PHP CLI has not `mysqli` extensions enabled.

**Comment by WellingGuzman** [comment]
I want to add if you run `php -m` do you see the `mysqli` extension?

**Comment by DanielRuf** [comment]
```shell
which php
/opt/boxen/phpenv/shims/php
```

```shell
php -m
[PHP Modules]
...
mysqli
mysqlnd
...
```

**Comment by DanielRuf** [comment]
So the extension is enabled by default otherwise we could not do many of the daily tasks (drush, composer, update schemas on the cli, ...)

**Comment by DanielRuf** [comment]
```shell
echo $PATH
/Users/druf/bin:/Users/druf/.composer/vendor/bin:/opt/boxen/rbenv/shims:/opt/boxen/rbenv/bin:/opt/boxen/ruby-build/bin:/opt/boxen/phpenv/shims:/opt/boxen/phpenv/bin:/opt/boxen/phpenv/plugins/php-build/bin:/opt/boxen/nodenv/shims:/opt/boxen/nodenv/bin:/opt/boxen/node-build/bin:/opt/boxen/homebrew/bin:/opt/boxen/homebrew/sbin:/opt/boxen/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/opt/X11/bin
```

So it is already in the path.

**Comment by WellingGuzman** [comment]
can you try running `php bin/directus db:upgrade` instead of `bin/directus db:upgrade`?

**Comment by Radiergummi** [comment]
Just a little note I'd like to throw in: I just moved our Directus installation to a new, clean box. I set up PHP with mysqli and mysql-pdo, installed MariaDB and got `Database connection failed.` on accessing Directus (tables set up, credentials working).  
The solution for me was to set the correct path to the `mysqld.sock`, but it was an awful way to find that out. It would be nice if you'd add the exception message in [`Bootstrap.php#L409`](https://github.com/directus/directus/blob/master/api/core/Directus/Bootstrap.php#L409), so users have a clue what's going wrong. There's `DIRECTUS_ENV` too, so maybe check for `development` first.

**Comment by MaximilianUE** [comment]
I´ve been testing for mysqli and I got the same results like @DanielRuf meaning 

```
which php
/opt/boxen/phpenv/shims/php
```
```
php -m
[PHP Modules]
...
mysqli
mysqlnd
...
```

Also 'php bin/directus db:upgrade' leads to the same issue as before :/

**Comment by WellingGuzman** [comment]
I want to ask you to go to `/Users/mbecher/Sites/da.localhost/web/directus/vendor/directus/migrations/lib/Ruckusing/Adapter/MySQL/MySQLBase.php on line 1298` and just echo/dump/see the value of `$this->conn->connect_error` (the actual error)?

**Comment by MaximilianUE** [comment]
Good news: We (@DanielRuf and I) found the problem:
Our local dev system based on boxen + 'nude' apache uses a custom socket that wasn´t referenced anywhere inside `ruckusing.conf.php`.
I´ve opened a pull request (see above) to address this issue, but I´m not sure if there needs to be an reference elsewhere for optimal clarity for the user.

**Comment by DanielRuf** [comment]
At least it was not quite clear where we had to change something. Would be useful to change the sample config and add two lines for custom sockets which are not active by default.

Is this specific usecase mentioned in the docs? If not then we should add and properly document it.

**Comment by DanielRuf** [comment]
> The solution for me was to set the correct path to the mysqld.sock, but it was an awful way to find that out. It would be nice if you'd add the exception message in Bootstrap.php#L409, so users have a clue what's going wrong. There's DIRECTUS_ENV too, so maybe check for development first.

This was the right hint but not quite clear enough as we had to check which configs were used and where the socket was set.

**Comment by benhaynes** [comment]
Hey @WellingGuzman – let's add a note regarding this to the Docs somewhere (or perhaps this GitHub issue is enough?)
