### ISSUE TITLE
Directus Themes: Search Collections Field

### ISSUE THREAD

**Issue by JugaadiTek** [directus/directus#21461]
### Describe the Improvement

| Dark & Light Base Themes | Color Match & Minimal Theme |
| :-: | :-: |
|Feels Centered|Feels Like its off|
|![image](https://github.com/directus/directus/assets/106853815/ed8ffdda-70ea-42b8-b1d0-bb74bc518019)|![image](https://github.com/directus/directus/assets/106853815/0605d1e0-cccf-4e29-9773-2ac0d2831991)|
|![image](https://github.com/directus/directus/assets/106853815/7050b48a-5c64-49ed-9c7f-a6a67cbc7f81)|![image](https://github.com/directus/directus/assets/106853815/a1581fd7-3596-4391-9117-6c5cf12a72ce)|
|The parent html element for search collection and select collection are the same color|The parent elements for both are different colors, which causes search collection to feel like its positioning is off|

*its still technically centered between the two content containing blocks, its just the background color shift at play.

---
- **Directus Version:** `10.9.2`
- **Database:** `Postgres`
- **Environment:** `Docker -> Railway`

**Comment by formfcw** [comment]
I will fix it
