### ISSUE TITLE
Access Control - directus_users Read - Field Permissions for non-App/non-Admin users are disabled for most fields

### ISSUE THREAD

**Issue by kulogix** [directus/directus#21471]
### Describe the Bug

Field Permissions in Custom READ Permissions for non-App/non-Admin roles on directus_users system collection are disabled for most fields; will be all enabled or all disabled depending on previously selected permissions (All Access or No Access, respectively).

This doesn't appear to affect Add or Edit permissions; doesn't affect directus_files - not sure about other system collections.

### To Reproduce

Setup a role that is non-App + non-Admin.
Settings > Access Control > System Collections

By default, directus_users has Read = No Access.
Change to Custom, and go to Field Permissions (with or without setting Item Permissions).
BUG: Most fields (first_name, last_name, title, description, etc) cannot be checked (are disabled, unselected).

Workaround (kind-of):
Temporarily change to All Access, then change to Custom.
All fields (including sensitive fields) will now be checked (but most are still disabled, cannot be unselected).

### Directus Version

v10.9.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Not exactly sure what the bug is here, all fields being pre-selected or not selected depending on whether you are changing from no-access or all-access seems logical.
