### ISSUE TITLE
Expose the flowsmanager to execute flows

### ISSUE THREAD

**Issue by Attacler** [directus/directus#21484]
### Describe the Improvement

Hi there,

In some cases it would be great to be able to use flows to prep data within your extensions.
For this we would need the getFlowManager function from api/src/flows.ts.
However, it is not exposed at this moment.
Can we maybe expose this on the same level as getSchema/env ect is exposed?

Example usecase:
Data preperation for a PDF.
Someone can select the right flow inside of an interface and the backend exension(s) would use that + the ID of a record to generate the PDF.

**Comment by Attacler** [comment]
I would be willing to make this happen.

**Comment by JoshTheDerf** [comment]
There's a _lot_ that could be done with this, including "loop" operations, which would be amazing.

**Comment by br41nslug** [comment]
I dont think exposing the flowmanager itself is wise in it's current state. However we could expose a some usable functions through the `FlowsService` like triggering a flow for example.

**Comment by rijkvanzanten** [comment]
I'll close this for now, as I too don't think it's a good idea to expose the whole flows manager. There's a lot of other system internals happening in there that can't safely be executed out of the server's startup execution order. Feel free to open [a new feature request](https://github.com/directus/directus/discussions/new?category=draft-feature-requests) to outline the features you'd like to access from the flows manager so they can be included as a separate extensions api 🙂
