### ISSUE TITLE
Unable to save table when "Single Item" is checked

### ISSUE THREAD

**Issue by lorenzone** [directus/directus#2149]
Hi there, I guess there's a little mistake on table editing when someone tries to create a 'Single Item' table, the table won't update :p 

## Version Info
  - Directus version and branch (Or commit hash): 6.4.9, master, commit aba7727c527125d35e1fc97219ef2ea7c7a8098d
  - PHP version: 7.0.29
  - MySQL version: 10.0.35-MariaDB
  - Web server: Apache
  - OS name and version: linux

## Expected Behavior
The table should save when I check "Single Item" and click save in the admin settings

## Actual Behavior
Returns the following error : 
```
Error
Error: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
File: http://porro.loren.zone/app/modules/tables/views/EditView.js?bust=aba7727c527125d35e1fc97219ef2ea7c7a8098d
Line:233
```

## Steps to Reproduce
 1. As Administrator, go to Admin Settings
 2. Inside Tables & Fields click Manage
 3. Then Select a Table to manage
 4. Check 'Single Item'
 5. Click Save
 6. Error
 
 I tried with and without adding new columns => same result

## Schema Dump, Logs, or Screenshots
![image](https://user-images.githubusercontent.com/38143579/39864241-486f5d7c-5449-11e8-9955-29a5a728357e.png)

Is there a way to directly change this in the database ? even that quick fix should be okay for me, for the moment.

**Comment by rijkvanzanten** [comment]
Heya! There should be a tinyint column called `single` in directus tables that controls that.

Have you seen this error before @wellingguzman?

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/50)
