### ISSUE TITLE
GraphQL subscriptions not working when using redis cache starting at 10.9.0

### ISSUE THREAD

**Issue by g-pichler** [directus/directus#21497]
### Describe the Bug

When subscribing to a collection using `graphql` (REST might also be affected; not tested), no events are being sent when items in the collection are updated/added.
The behavior is only present when `redis` is used as cache. Versions after and including v10.9.0 are affected. Versions tested: v10.8.3, v10.9.0, v10.9.2

### To Reproduce

1. Set up a directus docker container (v10.9.0 or above) according to the instructions, using redis cache and websockets enabled:
   ```
   WEBSOCKETS_ENABLED: true
   CACHE_STORE: 'redis'
   REDIS: 'redis://cache:6379'
   ```
1. Create a sample collection and subscribe to it using `graphql-ws` as the admin user.
1. Create a new item in the sample collection.
1. No events are being reported
1. Downgrade directus to <=10.8.3 *or* disable redis:
   ```
   WEBSOCKETS_ENABLED: true
   #CACHE_STORE: 'redis'
   #REDIS: 'redis://cache:6379'
   ```
   ==> events are correctly sent

### Directus Version

`>= 10.9.0`

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Thanks for opening this issue! This has already been fixed in #21479 which will be available in the next release 👍
