### ISSUE TITLE
Collections endpoint search

### ISSUE THREAD

**Issue by xyzones** [directus/directus#21490]
### Page

https://docs.directus.io/reference/system/collections.html#list-collections

### Describe the Inaccuracy

The `SEARCH` method is not accepting the query object , would be good to remove the generic text
```
If using SEARCH you can provide a [query object](https://docs.directus.io/reference/query.html) as the body of your request.

[Learn more about SEARCH ->](https://docs.directus.io/reference/introduction.html#search-http-method)
```

**Comment by rijkvanzanten** [comment]
Thanks for the heads up 🙂
