### ISSUE TITLE
Can't select items in the kanban layout

### ISSUE THREAD

**Issue by hauzdigital** [directus/directus#21492]
### Describe the Improvement

When we have a collection with a configured layout other than a table, and this collection is selected within an item using a relational field (one to many, for example), the item selection drawer is displayed in the format of the configured layout .

As a result, it is no longer possible to select an item when the layout is applied to the collection, for example the kanban or the calendar. What could be considered a bug?

Therefore, to ensure that the user can select an item, whose collection has a layout other than a table, the "Table" layout could be applied by default for display in drawers.

https://github.com/directus/directus/assets/151585180/022847fc-eedb-4a42-b8b7-60579a4f3ed4

Using Directus 10.9.2, Self-hosted with docker-image

**Comment by rijkvanzanten** [comment]
Every layout should have a selection mode. This feels like a bug in the kanban layout itself, as you can in fact select items from every other layout type 🙂

**Comment by albanallee** [comment]
Same bug identified with the Calendar view on relational selection @rijkvanzanten
