### ISSUE TITLE
directusctl npm package does not exist

### ISSUE THREAD

**Issue by akvadrako** [directus/directus#21504]
### Describe the Bug

The docs mention:

> For the client-side CLI, all functionality can be accessed by running npx directusctl <command>

but this results in:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/directusctl - Not found
npm ERR! 404
npm ERR! 404  'directusctl@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

### To Reproduce

npx directusctl

### Directus Version

v10.9.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
Did you npm install the `@directus/cli` package? `directusctl` is shipped with that.

**Comment by akvadrako** [comment]
I did figure that out, but it isn't what the docs say.

**Comment by phazonoverload** [comment]
We are currently working on a complete overhaul of our docs - including platform, content, and structure. As that project is being worked on, I am going to close this issue as it's already acknowledged and handled within this work. We're expecting to launch it this fall.
