### ISSUE TITLE
Getting message 'needs to have GD Library enabled' & Multibyte String extension from time to time

### ISSUE THREAD

**Issue by evanzummeren** [directus/directus#2150]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus version and branch (Or commit hash): 6.4.9
  - PHP version: 7.0
  - Web server: Apache
  - OS name and version: Ubuntu 16.04.1

## Expected Behavior
Accessing the login panel and being able to access tables

## Actual Behavior
From time to time I am not able to enter the login panel. I am getting a message which says I need to have the GD library and multibyte string extension enabled. Which I actually do (see logs). When I am able to enter the panel, then I often get an internal server error.

## Schema Dump, Logs, or Screenshots
```GD Support => enabled
GD headers Version => 2.1.1
GD library Version => 2.1.1


/etc/php/7.0/cli/conf.d/20-mbstring.ini,
Zend Multibyte Support => provided by mbstring
mbstring
mbstring extension makes use of "streamable kanji code filter and converter", which is distributed under the GNU Lesser General Public License version 2.1.
mbstring.detect_order => no value => no value
mbstring.encoding_translation => Off => Off
mbstring.func_overload => 0 => 0
mbstring.http_input => no value => no value
mbstring.http_output => no value => no value
mbstring.http_output_conv_mimetypes => ^(text/|application/xhtml\+xml) => ^(text/|application/xhtml\+xml)
mbstring.internal_encoding => no value => no value
mbstring.language => neutral => neutral
mbstring.strict_detection => Off => Off
mbstring.substitute_character => no value => no value```

![image](https://user-images.githubusercontent.com/7700089/39888535-5c27e57c-5495-11e8-80ed-a938f627a1c7.png)

**Comment by WellingGuzman** [comment]
Hey @evanzummeren, can you show us the Directus `logs` in `api/logs` directory?

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/51)
