### ISSUE TITLE
Incorrect Node.js version detected during project initialization

### ISSUE THREAD

**Issue by leonardodipace** [directus/directus#21514]
### Describe the Bug

When initializing a new Directus project using `npm init directus-project`, the CLI suggests updating Node.js even when running the latest version. This occurs consistently when creating a project with Node.js v21.6.2.

### To Reproduce

1. Ensure Node.js v21.6.2 is installed
2. Run npm init directus-project my-project
3. The CLI suggests upgrading Node.js, despite v21.6.2 being the latest stable version

![image](https://github.com/directus/directus/assets/63299726/2e28f94c-97eb-4768-9fc2-0b3f5dfe3da9)

### Directus Version

create-directus-project@10.0.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
Directus requires Node.js 18 (at least 18.17), Node.js 20/21 is not supported yet. See also https://docs.directus.io/self-hosted/cli.html#requirements.

Unfortunately, the message from `create-directus-project` is a bit misleading. This has been fixed in #21453 and will be updated on  next release.
