### ISSUE TITLE
Error: install process keeps throwing 'Your host needs to have File Information extension enabled to run this version of Directus!' while the fileinfo module is activated.

### ISSUE THREAD

**Issue by MaximilianUE** [directus/directus#2151]
install process keeps throwing 'Your host needs to have File Information extension enabled to run this version of Directus!' while the fileinfo module is activated.

## Version Info
  - Directus version and branch (Or commit hash): 6.4.9 (newest)
  - PHP version:  PHP 7.1.7 (cli) (built: Jul 25 2017 09:24:45) ( ZTS MSVC14 (Visual C++ 2015) x86
)
  - MySQL version: 
  - Web server: (Ex. Apache, nginx or IIS?) MAMP on Windows 10 (Apache)
  - OS name and version: Windows 10

## Expected Behavior
fileinfo is activated and directus setup finishes

## Actual Behavior
Installation keeps throwing Error ```Your host needs to have File Information extension enabled to run this version of Directus!```

I´ve tried this multiple times including:
1. completely removing all directus files again
2. restarting computer
3. restarting MAMP

## Steps to Reproduce
 1. git clone directus
 2. activate php module fileinfo in `/m/MAMP/bin/php/php7.1.7/php` in file php.ini by commenting in `extension=php_fileinfo.dll`
 2. composer install
 3. in browser: localhost:81/../directus (trying to finish setup)

```$ php -m
[PHP Modules]
bcmath
calendar
com_dotnet
Core
ctype
date
dom
fileinfo
filter
hash
iconv
json
libxml
mbstring
mcrypt
mysqlnd
odbc
openssl
pcre
PDO
pdo_mysql
Phar
Reflection
session
SimpleXML
soap
sockets
SPL
standard
tokenizer
wddx
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]
```

**Comment by MaximilianUE** [comment]
![ice_screenshot_20180513-185003](https://user-images.githubusercontent.com/24892204/39969603-820cc050-56de-11e8-9efe-bf8aca17e3d0.png)
Having the index.php in the /install dir replaced with `<?PHP phpinfo (); ?>` lists the module too

**Comment by rijkvanzanten** [comment]
Odd! I'm running Directus through MAMP myself and I've never seen this issue before.. 

@WellingGuzman any idea what's causing this?

**Comment by MaximilianUE** [comment]
Sorry for the absence but now I finally got around to test it out:

Both dumps returned `bool(false)` for me.

I´ve also tried calling `phpinfo` inside `directus/api/core/functions.php` to see if I can find a difference between having the module active and not. 
While "php -m" shows me the difference via a listing, phpinfo does not (though I don´t know if it even would since I was just trying stuff out for the first time...)

I´ve read on stackOverflow (https://stackoverflow.com/a/32719213) about a way to check if the module is active by using: 
`$ php -i | grep fileinfo` but it returned `stdout is not a tty` (whatever this might mean 😯)
so I´ve tried using `php -i` instead and found 
```
fileinfo
fileinfo support => enabled
```
so apparently my system is setup as expected, at least this appears to be the case.

Any ideas what else I could try to fix this?

**Comment by samuelantonioli** [comment]
Although it already said that fileinfo was installed, it wasn't (`var_dump(class_exists('finfo'));` returned `false`).

I've installed `php7-fileinfo` (on alpine, `apk --no-cache --update php7-fileinfo`) using the system package manager (depends on your system).  
  
If this doesn't help, try to add `extension=fileinfo.so` (linux) or uncomment `extension=php_fileinfo.dll` in your php.ini file.

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/52)
