### ISSUE TITLE
Markdown Editor: can't select file from library

### ISSUE THREAD

**Issue by abenz1267** [directus/directus#21519]
### Describe the Bug

When using the markdown editor, it is impossible to select a file from the library. The overlay is blocking the selection-area.

![2024-02-22T10:51:11,529025077+01:00](https://github.com/directus/directus/assets/7055955/56dd5d79-d454-433d-8fd5-e5c15d47eeba)

### To Reproduce

Use markdown editor > try adding image from library.

### Directus Version

v10.9.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by abenz1267** [comment]
Just tested: issue starts appearing with 10.9.0

**Comment by DanielBiegler** [comment]
Can confirm its reproducible in 10.9.2 - thank you for reporting this! :handshake:
