### ISSUE TITLE
 Cannot find package '@directus/errors'

### ISSUE THREAD

**Issue by dpozzan** [directus/directus#21533]
### Describe the Bug

I've updated Directus to the latest version. I noticed that when my Directus version is superior to 10.6.1, I get this error in the output of the 'docker-compose up' command:

**WARN: Cannot find package '@directus/errors' imported from /directus/extensions/hooks/...**
**Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@directus/errors' imported from /directus/extensions/hooks/ ...**

I'm using Directus with image 10.9.2 and MySQL 8.0.

### To Reproduce

- Start a project with version 10.6.1 and create a hook managing an error like in this example (by importing createError from '@directus/errors').--> [(https://docs.directus.io/extensions/hooks.html#filter)](https://docs.directus.io/extensions/hooks.html#filter)
- Update the directus version to 10.6.2 or superior

### Directus Version

10.9.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by dpozzan** [comment]
I also noticed that when I start the Docker container for Directus, the 'node_modules' directory inside the container seems to be quite empty. I can find the '@directus' directory inside, and then at the second level 'api' and 'update-check' directories, but there's no reference to the 'errors' package. Eventually, if I use the command 'npm update' inside the container in interactive mode, the 'errors' package is shown.

**Comment by br41nslug** [comment]
Did you add `@directus/errors` as dependency for your extension before building and deploying?

**Comment by dpozzan** [comment]
Hi @br41nslug, thank you for your reply. I didn't actively add the dependency. My package.json is generated automatically when I run Docker. Where could I eventually define the dependencies that should be added?

**Comment by br41nslug** [comment]
In your extensions package.json is where you define dependencies for your extension.
