### ISSUE TITLE
Collection data gets null after insert even if payload has values

### ISSUE THREAD

**Issue by abelbayon02** [directus/directus#21544]
### Describe the Bug

Im trying to insert to a collection and after the insert the data in null , I already checked the payload and it has values. I tried it in my POSTMAN and this is the sample issue 
![Screenshot 2024-02-24 155741](https://github.com/directus/directus/assets/80704559/0d5b72bd-6640-4de6-94a3-cfb2fd15b434)

### To Reproduce

I dont have ways to reproduce the issue but you can base on the screenshot i provided

### Directus Version

10.4.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hoachnt** [comment]
Have you tried insert the collection through an ui of directus itself? it would be nice to see on the network tab of  how the data is sent

**Comment by abelbayon02** [comment]
![Screenshot 2024-02-24 165309](https://github.com/directus/directus/assets/80704559/a048939c-7181-4741-9abe-258acbd5bbb7)
Yes , I've tried that also and its empty. 
here's the network tab
![Untitled](https://github.com/directus/directus/assets/80704559/f3e58166-424a-411d-9399-d5bd45d5ee5a)

only the Default fields of directus has values

**Comment by hoachnt** [comment]
> ![Screenshot 2024-02-24 165309](https://private-user-images.githubusercontent.com/80704559/307508088-a048939c-7181-4741-9abe-258acbd5bbb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NjU5MDQsIm5iZiI6MTcwODc2NTYwNCwicGF0aCI6Ii84MDcwNDU1OS8zMDc1MDgwODgtYTA0ODkzOWMtNzE4MS00NzQxLTlhYmUtMjU4YWNiZDViYmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA5MDY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMTNlYWJjNGRhNDBjMmM0MmU2MzVkMDkyYjcxMGFiNGM0ZDQ3MjJkZGVhMTgwNTQyNjJhMTE3MGNmYTYzN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jIgQxxS87MgvTbvWRIckKE9qx7glA6bmFnu1p3EHa1o) Yes , I've tried that also and its empty. here's the network tab ![Untitled](https://private-user-images.githubusercontent.com/80704559/307508430-f3e58166-424a-411d-9399-d5bd45d5ee5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NjU5MDQsIm5iZiI6MTcwODc2NTYwNCwicGF0aCI6Ii84MDcwNDU1OS8zMDc1MDg0MzAtZjNlNTgxNjYtNDI0YS00MTFkLTkzOTktZDViZDQ1ZDVlZTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA5MDY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyYTA1YmViMmIxMDMwODYxYzgxNzk1N2YxNjVkZDA4Y2Y2MzU1NTdjZmQ1ZTRhYzQ0OWZhZmEzYzc0ZjhhMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kj1431Z7YK8o7LOe9G5o3K-yJWe2QQr_YQ9HfRX8I58)
> 
> only the Default fields of directus has values

Can you show the data types of the fields you created?

**Comment by hoachnt** [comment]
Can you show the data types of the fields you created? @abelbayon02

**Comment by abelbayon02** [comment]
![Screenshot 2024-02-24 175510](https://github.com/directus/directus/assets/80704559/9900b74d-2c92-4646-9266-13bd05344c2b)
Dtr_date: DateTime
dtr_time: DateTime
employee_id: Many to one (employees collection)
intSeq: Integer
overtime_status: integer

**Comment by hoachnt** [comment]
at first glance everything seems fine... I'll have to repeat this error to understand what the heck is going on

**Comment by abelbayon02** [comment]
Yeah , That's what i'm wondering too , but i tried recreate a collection separate name  example: dtr (and all fields duplicated from employee_dtr) , the saving is fine but when i recreate another collection named employee_dtr (deleted the existing) that's issue persists. is it possible because of the name of the collection?

**Comment by paescuj** [comment]
First, I recommend to upgrade your instance to the latest version. 10.4.0 dates back to Jun 23, while the latest version currently is [10.9.3](https://github.com/directus/directus/releases/tag/v10.9.3). We've released a lot of new features, improvements and bug fixes in the meantime and chances are that this already solves your issue.

Secondly, could you check if there's a custom extension or Flow which manipulates that data?

**Comment by abelbayon02** [comment]
I think i got it now , its because of the flow that i haven't finish setting up which i totally forgot. Thank you so much for answering my questions

**Comment by paescuj** [comment]
Great, thanks for your feedback 🎉
