### ISSUE TITLE
Just a 404 link

### ISSUE THREAD

**Issue by triplecasquette** [directus/directus#21547]
### Page

https://docs.directus.io/guides/headless-cms/live-preview/nextjs.html#set-up-live-preview-with-next-js

### Describe the Inaccuracy

There's a dead link on the word guide on this page.

![Capture d’écran 2024-02-25 à 16 56 03](https://github.com/directus/directus/assets/81014220/56301a11-1c42-4e02-8c22-6fd967e14203)

With Love for the White Rabbit :ra :)

**Comment by paescuj** [comment]
Thanks! With love back 🐰
