### ISSUE TITLE
App: Add "Open image" button from Block interface 

### ISSUE THREAD

**Issue by joselcvarela** [directus/directus#21567]
### Describe the Improvement

Right now it is only possible to select or upload a new image from Block interface.
Although, it would be useful to open image directly from Block interface in order to edit image like Cropping.

https://github.com/directus/directus/assets/14039341/8979a49b-0f17-49a3-84c2-81d871fe343a

**Comment by d3v1an7** [comment]
Thank you! We use the block editor exclusively, so this will be a big help for the users trying to manage images within content.
