### ISSUE TITLE
Deprecate unmaintained CLI client

### ISSUE THREAD

**Issue by br41nslug** [directus/directus#21564]
### Describe the Improvement

The `@directus/cli` tool mentioned here https://docs.directus.io/self-hosted/cli.html#client has not seen much maintenance recently. To prevent confusion we'll remove the mention of it in the docs and depecrate the `@directus/cli` package.

**Comment by rijkvanzanten** [comment]
> has not seen much maintenance recently

Nor really _any_ use (according to npm download counts) nor interest from the community (based on discussions/issues/discord messages) 🙃

**Comment by phazonoverload** [comment]
Related: #21504

**Comment by phazonoverload** [comment]
Reopened because we actually need to deprecate the client. Who can handle that? From a docs perspective, this is handled within the new docs content.

**Comment by rijkvanzanten** [comment]
@phazonoverload Repo archived, npm package deprecated 👍🏻
