### ISSUE TITLE
File manager Images don't display until after 2 or 3 minutes

### ISSUE THREAD

**Issue by alexchudnovsky** [directus/directus#21584]
### Describe the Bug

When Manually uploading files ( drop and drag ) into the file manager, the thumbnails images do not appear, after refreshing a few times I will see them in recently uploaded folder, but no other folders display them, if I then wait for about 2 or 3 minutes and then refresh the screen only then I will start seeing them in the other folders. 

I have used directus quite a lot on various servers and locally I have not seen this before 

Is this a bug ?

### To Reproduce

1) Setting up a linode account and installing Ubuntu on it 
2) Installing Docker
3) Running the latest version of the directus image ( v10.9.3) 
4) Dragging and dropping images into the file manager 

### Directus Version

v10.9.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

In case of large images, please ensure your server has enough resources available for asset transformation or you may want to tweak the related config options, like `ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION` [^1].

[^1]: https://docs.directus.io/self-hosted/config-options.html#assets
