### ISSUE TITLE
best pratice for relational fields in same table

### ISSUE THREAD

**Issue by jasonmarysael** [directus/directus#2160]
I want to create a table that stores multiple items and for each item I want to add a field that stores related items (from the same table). What would be the best practice for this situation? I can't seem to figure out which user interface would suites this purpose and how I need to set it up.

**Comment by honzabilek4** [comment]
Hey,
why do you want to link items from the same table? 😮 Isn't the problem actually in your database design?I'd suggest to rethink your data structure, maybe it'll help you to figure out the right interface afterwards. 🙂

**Comment by rijkvanzanten** [comment]
Hey @jsonmarysael! You can set this up with any of the relational interfaces (M2O, O2M, or M2M) see https://medium.com/directus/understanding-relationships-it-isnt-complicated-35e0dcf78450.

As @honzabilek4 rightfully pointed out: it’s fairly uncommon to end up with a scenario like this.. Do you have a specific example of what you’re trying to achieve? There might be a better way altogether 😄

**Comment by benhaynes** [comment]
Hey @jasonmarysael – the best way to accomplish this is to use a many-to-many (M2M). Basically if you have `items` that you want to relate to itself, you create a junction table called `items_related`. So your schema would look like this:

```
items
* id
* whatever field
* whatever field
* whatever field

items_related
* id
* item_a
* item_b
```

Then you use the M2M interface to connect it all together (check out our Docs). We try not to give "advice" here as it's for bugs, so I'll close this.

@honzabilek4 – this is often used for Products and Related Products.
