### ISSUE TITLE
Unable to use extensions in directus-self hosting

### ISSUE THREAD

**Issue by srikanthgarimilla1996** [directus/directus#21612]
### Describe the Bug

Hi, I am trying this example to create display extension: https://docs.directus.io/guides/extensions/displays-date-to-age.html.
I was able to create a extension named directus-display-age-of-user.
![image](https://github.com/directus/directus/assets/161418213/966507fa-454b-4673-a278-a74d26399b24)
And next i have created a collection named birthdates.
![image](https://github.com/directus/directus/assets/161418213/e0d1aff8-f59e-4f33-8f2f-fc234a15d34a)
In display tab, I could not see the extension i have created.
![image](https://github.com/directus/directus/assets/161418213/f3460a2f-1bd5-42cb-b7f3-3d811c381fb1)

may I know whether something is missing?
Any help would be appreciated.
Thanks

### To Reproduce

This is my display.vue in the display extension:
![image](https://github.com/directus/directus/assets/161418213/c1db26a5-7e32-468b-8881-d7425447a26f)

This is my index.js:
![image](https://github.com/directus/directus/assets/161418213/2a032b0b-7093-44c7-8305-b524205af381)

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Move your extension to the root of the extensions folder instead of using the legacy extension specific folders.

https://docs.directus.io/extensions/installing-extensions.html#installing-through-the-extensions-folder

**Comment by srikanthgarimilla1996** [comment]
Thanks a lot @br41nslug . The solution you've provided above is working.
It would be really helpful if directus team could mention this solution in the below example given to create an extension.
https://docs.directus.io/guides/extensions/displays-date-to-age.html.

**Comment by br41nslug** [comment]
It is mentioned there https://docs.directus.io/guides/extensions/displays-date-to-age.html#add-display-to-directus

> When Directus starts, it will look in the extensions directory for any subdirectory starting with directus-extension-, and attempt to load them.

> To install an extension, copy the entire directory with all source code, the package.json file, and the dist directory into the Directus extensions directory.
