### ISSUE TITLE
Error installing directus via CLI Node 20.11.1

### ISSUE THREAD

**Issue by scharez** [directus/directus#21629]
### Describe the Bug

When i try to install directus via the cli i get the following error. (see image below)

<img width="971" alt="image" src="https://github.com/directus/directus/assets/34278251/2231d171-739a-4b80-9512-36b67963e994">

Node version is 20.11.1

### To Reproduce

Terminal --> npm init directus-project directus

### Directus Version

v10.9.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
It seems like the message was not clear enough, do you have a suggestion for improvement?

**Comment by scharez** [comment]
> As the error says `Directus requires node 18, ...`

Or Higher?

**Comment by br41nslug** [comment]
> Or Higher?

Node 18, specifically `18.17` or higher (so `>18.17` and `<19`)

**Comment by br41nslug** [comment]
> do you have a suggestion for improvement?

Honestly there have been 2 or more pr's trying to "fix wording" here, lets either use technical notiation without room for interpretation `node >18.17 || <19`. But i'd much rather spend time on just getting the node 20 support going instead.

**Comment by rijkvanzanten** [comment]
@br41nslug @paescuj out of curiosity, what's the current blocker for v20? I've been using that in Dev for a little while now seemingly without issues 🙂

**Comment by br41nslug** [comment]
I believe it was a limitation of one of our dependencies but havent looked into it for a bit

**Comment by paescuj** [comment]
> @br41nslug @paescuj out of curiosity, what's the current blocker for v20? I've been using that in Dev for a little while now seemingly without issues 🙂

- https://github.com/laverdet/isolated-vm/issues/424
  
  From https://github.com/laverdet/isolated-vm?tab=readme-ov-file#requirements
   > 🚨 If you are using a version of nodejs 20.x or later, you must pass --no-node-snapshot to node.
  
  So we _may_ need to update the Dockerfile (depending whether it is macOS only or not) and we _need_ to update the docs

- I'd like to have it generally checked & tested for other issues before officially moving to Node.js v20
