### ISSUE TITLE
RegExp /u unicode flag support

### ISSUE THREAD

**Issue by cliqer** [directus/directus#21627]
### Describe the Bug

Something like this `/^[\p{L} \-'.]+$/u` for i.e. First Name validation, doesn't work.
- `\p{L}` matches any kind of letter from any language.
- The `u` flag enables Unicode mode, which is necessary for `\p{L}` to work correctly. 

### To Reproduce

In `roles -> directus_users -> update -> Field Validation` select `first_name` -> `Matches RegExp` and add `/^[\p{L} \-'.]+$/u`. Any field updates will throw an error.

### Directus Version

v10.9.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
We currently don't support RegExp flags at all.

**Comment by rijkvanzanten** [comment]
Closing this as supporting Regexes is a bigger new feature that should be discussed in a feature request first. Please [open a new feature request](https://github.com/directus/directus/discussions/new?category=draft-feature-requests) instead. Thanks!
