### ISSUE TITLE
HookInterface is not usable for action hooks

### ISSUE THREAD

**Issue by arboehme** [directus/directus#2162]
## Version Info
  - Directus version and branch (Or commit hash): 5375f1247b7381a5d68ee1598e020c12e0454502, Branch: develop
  - PHP version: 7.2.5
  - MySQL version: 5.7
  - Web server (Ex. Apache, nginx or IIS?): Apache
  - OS name and version: Debian 9.4

## Expected Behavior

Use of `HookInterface` works as expected for the *filter* hooks. Expected to use the interface for the *action* hooks as well

## Actual Behavior

If I use custom class implementing the `HookInterface` for the *action* hooks `table.insert:after` and `table.update:before` as described in the developer documentation [here](https://docs.getdirectus.com/6.4.0/#Hooks) , the compilation exception occurs saying that the signature of the method `handle` with two parameters is incompatible to the interface. If I reduce the signature to one parameter, it represents only the table name and the data is not available.

## Steps to Reproduce
 1. Define the custom action hook for the `table.insert:after` in the configuration.php as class implementing the `HookInterface` 
 2. Implement the `handle`method
 3.  Update some entry in Directus

**Comment by arboehme** [comment]
PS: Currently I use the workaround via `__invoke($table, $data)` without `... implements HookInterface`

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/55)
