### ISSUE TITLE
Default language wrong for translations not working (10.9.3)

### ISSUE THREAD

**Issue by notflip** [directus/directus#21626]
### Describe the Bug

My user language is set to Dutch, the default language for the app is set to Dutch, and I set the translation field settings to use the current language, however the wrong language is shown as default.

I updated to 10.9.3, since this is supposed to be fixed in 10.9.2 (https://github.com/directus/directus/pull/21065)

_Default language in app_
![Screenshot 2024-02-29 at 06 51 48](https://github.com/directus/directus/assets/4146384/ff9cd279-a005-46e2-a0e5-0b8de5eb6410)

_Default language for user_
![Screenshot 2024-02-29 at 06 52 09](https://github.com/directus/directus/assets/4146384/1e63adc0-bcb9-4433-bdc7-febbc4b8e4bb)

_Set language to current on the model "translations" field_
![Screenshot 2024-02-29 at 06 52 35](https://github.com/directus/directus/assets/4146384/a13bf240-4bd5-409d-8f1f-5befbea6f66f)

_Result_
![Screenshot 2024-02-29 at 06 53 06](https://github.com/directus/directus/assets/4146384/abff6a62-ee11-4e05-b6fa-de7269f86f54)

### To Reproduce

- (Models were created before the update to 10.9.3)
- Update to version 10.9.3
- Set setting as shown in screenshots above

### Directus Version

v10.9.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by notflip** [comment]
If I set default language to NL in the translation  field settings:

![Screenshot 2024-02-29 at 07 35 44](https://github.com/directus/directus/assets/4146384/7233999c-b776-4077-9927-0a46edf7ba43)

NL is shown twice.

![Screenshot 2024-02-29 at 07 35 01](https://github.com/directus/directus/assets/4146384/ef6605e3-d8a0-4149-be09-73e4c969bd30)

**Comment by notflip** [comment]
@paescuj I'm don't understand what you mean, is it possible in my instance of having 'nl' as the first language? What actions do I need to take to achieve that? Thank you.

**Comment by paescuj** [comment]
Most likely, you're just missing an item for the `nl-NL` language in the referenced collection used for the translations.

1. Go to the translation field settings -> Relationship -> get the name of the "Related Collection"
2. Open the content view for that Collection (you may need to unhide it to be able to access it)
3. Add an new item for `nl-NL`

You may follow the screenshots posted above.

**Comment by notflip** [comment]
Thanks for writing this out, however I don't see "Relationship" in the settings for the translation field?

<img width="856" alt="Screenshot 2024-02-29 at 17 38 42" src="https://github.com/directus/directus/assets/4146384/9f95dae2-2b81-464b-af49-44d6f6d59b2b">

**Comment by paescuj** [comment]
Oh sorry, I've missed that for translation fields it's called different: it is under "Translations" -> "Languages Collection"
<img width="833" src="https://github.com/directus/directus/assets/5363448/8f43d9a3-5ff1-4106-b086-5e4b6333ad9f">

**Comment by notflip** [comment]
@paescuj Ah thanks, I do see the 'nl' entry in there.

<img width="607" alt="Screenshot 2024-02-29 at 17 44 49" src="https://github.com/directus/directus/assets/4146384/72df5ff2-b699-4976-8c49-a17c7abf384f">

**Comment by notflip** [comment]
@paescuj  I just added a sort field, sorted 'nl' in front of 'en' and now it seems to pop up first!

**Comment by paescuj** [comment]
> @paescuj Ah thanks, I do see the 'nl' entry in there.
> <img alt="Screenshot 2024-02-29 at 17 44 49" width="607" src="https://private-user-images.githubusercontent.com/4146384/309004465-72df5ff2-b699-4976-8c49-a17c7abf384f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMjU2MjYsIm5iZiI6MTcwOTIyNTMyNiwicGF0aCI6Ii80MTQ2Mzg0LzMwOTAwNDQ2NS03MmRmNWZmMi1iNjk5LTQ5NzYtOGM0OS1hMTdjN2FiZjM4NGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjlUMTY0ODQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzAxN2RkNzRmYWVjYWVjM2QyNGYxN2JjMzkxYzgyMGI1NjI1OGYxZTNiYjAyMzg1NThkNmNkNjBiM2Y3YTBiNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ikaKYIT22vxFas0lcQZ6dUQRNfERDj3qfIjoAu_C6uM">

I think the "Code" should follow the <language>-<COUNTRY/VARIANT> pattern, e.g. `nl-NL` instead of just `nl`.
