### ISSUE TITLE
Ensure that the system default language is used as the default language when creating a new custom translation via the system-input-translated-string interface

### ISSUE THREAD

**Issue by formfcw** [directus/directus#21633]
### Describe the Improvement

When you create a new translation using the system-input-translated-string interface, the language field is always unset. You must select a value manually. Using the system default language as the default language would ensure consistency because it would behave the same way as the field name translation field.

https://github.com/directus/directus/assets/78852214/ab1ca11f-e0a4-4625-8d10-aaacb18e02a5

**Comment by formfcw** [comment]
i will make a pr

**Comment by rijkvanzanten** [comment]
Thanks Florian!
