### ISSUE TITLE
Flow creation error with SAVEPOINT not supported, but still created

### ISSUE THREAD

**Issue by mrbarletta** [directus/directus#21630]
### Describe the Bug

Creating a Flow (item.create / Event Hook / Action non-blocking )
I get this error: 
`[INTERNAL_SERVER_ERROR] SAVEPOINT trx3805; - ER_CHECK_NOT_IMPLEMENTED: The storage engine for the table doesn't support SAVEPOINT`

I tested 2 different servers, directus 10.8.2 and 10.9.3, both have the same issue.

The Flow IS created, which is weird.

### To Reproduce

1.  Create a Flow
2.  Select Event Hook
3.  Select Action
4.  Item.create
5.  Choose a table  (very large, about 2M records)

I made sure the table is INNODB.

I check the mysql general log , and there are multiple queries using SAVEPOINT tx123 so it does work, I couldn't find 

I checked the mysql library but didn't find much info about the error, they just translated the `ER_CHECK_NOT_IMPLEMENTED` to `The storage engine for the table doesn't support %` .

thanks

### Directus Version

v10.9.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
This seems to be a configuration issue within the database, I'm afraid we can't do much from our side.
I'm closing this issue for now, but happy to keep discussing in this thread.

Do you have a standard DB setup? MySQL or MariaDB?

**Comment by mrbarletta** [comment]
Thanks @paescuj - Its a MariaDB 10.11 and 10.6.
How do you know is a configuration issue?
 I can't find anything that could help me in the debugging of this issue.!
