### ISSUE TITLE
Live Demo not working

### ISSUE THREAD

**Issue by lcpichette** [directus/directus#21646]
### Describe the Bug

When trying to use the interactive live demo I'm unable to sign in using the provided credentials. The guy on loop is fun for the first 15 seconds but after that I just feel mocked :,(

Both typing "password"
![2024-02-29 23 23 44](https://github.com/directus/directus/assets/54318714/82bade79-f2d4-4b98-8e3f-15d0727d79f1)

And copying and pasting it...
![2024-02-29 23 27 00](https://github.com/directus/directus/assets/54318714/3183ee31-fee2-4afb-850f-e1da3056ced4)

<img width="1013" alt="Screenshot 2024-02-29 at 11 24 00 PM" src="https://github.com/directus/directus/assets/54318714/8320f2ca-7ee7-4120-a493-d7f8baf53d0d">

There is an issue that already describes this problem, but it was closed back in 2019: https://github.com/directus/directus/issues/2280 

### To Reproduce

1. Go to: https://directus.pizza/admin/login
2. Attempt to login via username: `admin@examples.com` and password: `password`. 
3. Get error about incorrect auth

### Directus Version

na

### Hosting Strategy

Directus Cloud

**Comment by azrikahar** [comment]
> When trying to use the interactive live demo I'm unable to sign in using the provided credentials. The guy on loop is fun for the first 15 seconds but after that I just feel mocked :,(

Really sorry to hear that! Can you try logging in again with the following credentials (particularly `example` instead of `examples`):

- email: `admin@example.com`
- password: `password`

I've proceeded to fix the displayed credentials on the login page to prevent any further confusions. Thank you very much for bringing this up 👍

**Comment by lcpichette** [comment]
I just want to confirm that the fields automatically being filled is the desired result?

![2024-03-01 08 28 50](https://github.com/directus/directus/assets/54318714/bcfff3b7-2909-4442-8247-d9c6c42d10b7)
