### ISSUE TITLE
Upstash Redis, IPv6 problem, Fly.io

### ISSUE THREAD

**Issue by clickersmudge** [directus/directus#21659]
### Describe the Bug

Hi,
I have a containerised Directus application that deploys to Fly.io. Fly.io has a connection to the Upstash Redis service.

My local instance configuration (working)
```
REDIS="redis://user:password@127.0.0.1:16379"
```

My configuration on Fly.io (not working)
```
redis://user:password@fly-example.upstash.io:6379
```

While debugging, I found that for Redis to work you need to set the "family: 6" flag so that the connection is over IPv6. Redis only works on IPv6.
https://community.fly.io/t/connect-to-redis-app-via-internal-network-failing/2776/15

However, I do not know how to set this in Directus.
There seems to be no such flag in the ENV.
https://docs.directus.io/self-hosted/config-options.html#redis

### To Reproduce

Only Deploy on Fly.io.

### Directus Version

10.9.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
Thanks for opening this issue!

I think you should be able to set the IP family in one of these ways:
- Via `REDIS` config option (connection string): 
  ```ini
   REDIS=redis[s]://[[username][:password]@][host][:port][/db-number]?family=6
  ```
- Via `REDIS_FAMILY` config option, if you don't use the `REDIS` config option:
  ```ini
  REDIS_FAMILY=6
  ```

See also https://docs.directus.io/self-hosted/config-options.html#redis.

Leaving this issue open, so we can improve the docs, to the effect that it is possible to configure advanced connection options via `REDIS_<OPTION>` - besides the currently documented ones.
 
Would be great if you could give feedback on whether it worked for you 🚀

**Comment by clickersmudge** [comment]
@paescuj Thank you very much for your help. It works.

**Comment by paescuj** [comment]
Leaving open for docs 👍

**Comment by joggienl** [comment]
Stumbled upon this today on fly.io. Can I add a PR that documents this in the docs?

I did wonder (did not check the code), for the env option, don't we have to add the `socket` key? I thought that if you configure redis via an object, the `family` option is part of the `socket` configuration. 

```js
// example

const client = createClient({
    username: 'default',
    password: 'secret',
    socket: {
        host: 'host',
        port: 6379,
        family: 6
    }
});
```

The connection string option with `?family=6` worked well (and there is also no socket).
