### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by dur41d** [directus/directus#2165]
Getting an error installing directus for the first time.

## Version Info
  - Directus version and branch (Or commit hash): release 6.4.9
  - PHP version: PHP 7.2.5-nfsn1 (cli) (built: Apr 30 2018 02:03:43) ( NTS )
  - MySQL version: 10.1.18-MariaDB-1~xenial - mariadb.org binary distribution
  - Web server: Apache
  - OS name and version: FreeBSD

## Expected Behavior
go to the login page

## Actual Behavior
getting an error message

`Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'maakom3.directus_tables' doesn't exist in /home/public/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:239 Stack trace: #0 /home/public/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute() #1 /home/public/api/core/Directus/Database/Schemas/Sources/MySQLSchema.php(87): Zend\Db\Adapter\Driver\Pdo\Statement->execute() #2 /home/public/api/core/Directus/Database/SchemaManager.php(332): Directus\Database\Schemas\Sources\MySQLSchema->getTables(Array) #3 /home/public/api/core/Directus/Database/TableSchema.php(869): Directus\Database\SchemaManager->getTables() #4 /home/public/api/core/Directus/Bootstrap.php(472): Directus\Database\TableSchema::getTablesSchema(Array, true) #5 [internal function]: Directus\Bootstrap::acl(NULL) #6 /home/public/api/core/Directus/Bootstrap.php(84): call_user_func('Directus\\Bootst...', NULL) #7 /home/public/api/core/Directus/Bootstrap.php(740): Dire`

## Steps to Reproduce
 1. ftp directus-build-6.4.9-20180403074823.tar.gz to the server public directory
 2. tar zxfv the file
 3. chmod 777 for the following folders: api, api/logs, storage/uploads
 3. visit the the server in the browser and see the installation page
 4. put the the user info and db info.
 5. see Yes for everything (except Imagick)
 6. click install button

## Notes

I see that the table 'directus_schema_migrations' is created in the database.

## Schema Dump, Logs, or Screenshots

https://www.dropbox.com/s/xruja9e2dbf9hmd/Capture.JPG?dl=0
https://www.dropbox.com/s/z6qnno3b3nz21wr/development.log?dl=0

**Comment by hnkumar** [comment]
I have same issue.  I'm using MySQL and I can see table already created.  My error log says

2018/07/08 22:08:43 [error] 19838#19838: *205 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'directus.directus_tables' doesn't exist in /directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:239
Stack trace:
#0 /websites/research/directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute()
#1 /websites/research/directus/api/core/Directus/Database/Schemas/Sources/MySQLSchema.php(87): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#2 /websites/research/directus/api/core/Directus/Database/SchemaManager.php(332): Directus\Database\Schemas\Sources\MySQLSchema->getTables(Array)
#3 /websites/research/directus/api/core/Directus/Database/TableSchema.php(869): Directus\Database\SchemaManager->getTables()
#4 /websites/research/directus/api/core/Directus/Bootstrap.php(472): Directus\Database\TableSchema::getTablesSchema(Array, true)
#5 [internal function]: Directus\Bootstrap::acl(NULL)
#6 /websites/research/directu" while reading response header from upstream, client: 127.0.0.1, server: directus.localtest.me, request: "GET /api/1.1/ping HTTP/1.0", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "directus.localtest.me"

**Comment by hnkumar** [comment]
OK, I got it work.  I followed NGINX configuration at https://github.com/directus/server-configs-nginx.

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/56)
