### ISSUE TITLE
Directus SDK v15.0.1 Module Import Error

### ISSUE THREAD

**Issue by emrahaydemir** [directus/directus#21653]
### Describe the Bug

Hello, I am running directus sdk on the server side in a Next.js application. In version 15.0.0, the sdk was running smoothly. When I updated to version 15.0.1, I got a critical error message in my directus.config file in my server console. My Next.js API services stopped completely. The error says that I need to import ESM packages. In my directus.config file I simply build and export directus with base url. I changed the Directus SDK version back to 15.0.0 and the bug is fixed.

error message: `Module not found: ESM packages (@directus/system-data) need to be imported`
console error:
<img width="1242" alt="image" src="https://github.com/directus/directus/assets/35865864/236f8a79-ef5b-4b70-9ce9-3716be9131ff">

directus.config.js file:
<img width="676" alt="image" src="https://github.com/directus/directus/assets/35865864/3763fe66-2ae6-4ef8-938d-90f70af88e46">

### To Reproduce

Simply build the Directus SDK (v15.0.1) on the server side with Next.js.

### Directus Version

v15.0.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
This has been fixed in #21614, which will be available with the next release.
