### ISSUE TITLE
Question: Custom API to increment views.

### ISSUE THREAD

**Issue by shabbir21** [directus/directus#2166]
## Version Info
  - Directus version and branch (Or commit hash): 6.4.9 master
  - PHP version: 7.0.30
  - MySQL version: 
  - Web server: Apache
  - OS name and version: Ubuntu 16.04

I have setup a `Posts` table. The table has a column `views`.
Is it possible to write a custom API which will increment the value of `views` in `Posts` table?

**Comment by benhaynes** [comment]
In this old version it can be accomplished with hooks:

https://github.com/directus/docs/blob/master/developer-guide/hooks.md

Or custom endpoints in the new API version:

https://docs.directus.io/extensions/custom-endpoints.html#creating-custom-endpoints

**Comment by shabbir21** [comment]
@benhaynes this link(https://github.com/directus/docs/blob/master/developer-guide/hooks.md) is not working.

**Comment by benhaynes** [comment]
Thanks @shabbir21 – I updated the link: https://github.com/directus/docs/blob/master/extensions/hooks.md
