### ISSUE TITLE
403 when a call tries the API Activity endpoint

### ISSUE THREAD

**Issue by apochalypze** [directus/directus#2167]
## Version Info
  - Directus version and branch (Or commit hash): 6.4.9
  - PHP version: 7.0.30
  - MySQL version: 10.1.33-MariaDB
  - Web server: Apache
  - OS name and version: Linux 3.10.0-714.10.2.lve1.4.79.el7.x86_64 (shared server on midphase.com)

## Expected Behavior
a response that is not a 403

## Actual Behavior
Aetting a 403 when trying to access the Activity API from the admin. Just selecting any table this call happens and results in a 403.

## Steps to Reproduce
 1. http://lightsoundstudios.net/webmin/api/1.1/activity/?currentPage=0&perPage=200&sort=id&sort_order=ASC&status=1,2&last_updated[articles]=1&columns_visible=type,action,identifier,table_name,row_id,user,data,id

2. This call seems to fail due to certain fields in the columns_visible not existing. If you remove the columns_visible from the query...

http://lightsoundstudios.net/webmin/api/1.1/activity/?currentPage=0&perPage=200&sort=id&sort_order=ASC&status=1,2&last_updated[articles]=1

No 403 and a valid response. The system is generating these links to I'm not sure what is going on here.

## Schema Dump, Logs, or Screenshots
Chrome Console Log
GET http://lightsoundstudios.net/webmin/api/1.1/activity/?currentPage=0&perPage=200&sort=id&sort_order=ASC&status=1%2C2&last_updated%5Barticles%5D=1&columns_visible=type%2Caction%2Cidentifier%2Ctable_name%2Crow_id%2Cuser%2Cdata%2Cid 403 (Forbidden)

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/57)
