### ISSUE TITLE
Problem with adding Custom Read Permissions to directus_user collection

### ISSUE THREAD

**Issue by bryantgillespie** [directus/directus#21678]
### Describe the Bug

Scenario: You have an API only user that you want to set custom permissions for on the directus_users collection. You want to limit the user from seeing certain fields.

For roles that don't have app access, the UI prevents you from changing fields that are available and behaves as if App Access is enabled, even though App Access isn't enabled.

![ScreenShot_2024-03-04_at_07 57 282x](https://github.com/directus/directus/assets/23302570/bb8d6770-0349-4e71-835a-b4fad6855599)

![ScreenShot_2024-03-04_at_07 57 212x](https://github.com/directus/directus/assets/23302570/17e359c5-268e-4028-8c6e-1afe08bd9b18)

### To Reproduce

1. Create a user role without app access
2. Try creating a custom read permission on directus_user collection > Field Permissions tab

### Directus Version

v10.9.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Fixed in #21543 which will be available with the next release.
