### ISSUE TITLE
Keycloak auth refresh not working

### ISSUE THREAD

**Issue by useEffects** [directus/directus#21682]
### Describe the Bug

`/auth/refresh` failing after logging in with keycloak as SSO 

### To Reproduce

docker images for keycloak and directus

### Directus Version

v10.x.x

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Make sure to provide all asked/required information for the issue to be reproduced on our side. A repo with an empty bootstrap are not reproduction steps.

9 out of 10 times the issue is with the cookie domain (or other cookie settings). Is the cookie being correctly set in the browser and sent with the refresh request?

**Comment by aidenfoxx** [comment]
I would advise checking your instance logs for errors marked with "[OpenID]" for more information. To get more extensive log information add  `LOG_STYLE: "raw"` to your configuration.

**Comment by aidenfoxx** [comment]
We would expect to see an OpenID error in the Directus server logs for the behavior you are describing. If the "refresh" endpoint only fails for Keycloak and not Google, it's almost certainly an error from the Keycloak refresh token endpoint, which always logs when throwing a 401. I would advise messing around with your Keycloak refresh token settings to try and solve the issue. Without an underlying error we're basically shooting in the dark.

If possible, you can reset your Keycloak settings to default, which is known to work with Directus (unless newer Keycloak versions broke something).

**Comment by aidenfoxx** [comment]
The last time it was properly tested would probably have been around 2 years ago.

**Comment by aidenfoxx** [comment]
I'm not suggesting you use an old version. We have many community members using more recent Keycloak versions who do not have the same issue.

**Comment by aidenfoxx** [comment]
Just verified with Keycloak 24.0.2 and Directus 10.10.4. Stock Keycloak configuration. Everything works as expected.

Config used:
```
AUTH_PROVIDERS="keycloak"
AUTH_KEYCLOAK_DRIVER="openid"
AUTH_KEYCLOAK_MODE="session"
AUTH_KEYCLOAK_CLIENT_ID="directus"
AUTH_KEYCLOAK_CLIENT_SECRET="qLNfNn51ZraNx0jPyUJiHt90hTXmzoAn"
AUTH_KEYCLOAK_ISSUER_URL="http://localhost:8080/realms/master/.well-known/openid-configuration"
AUTH_KEYCLOAK_DEFAULT_ROLE_ID="0e6ebb1c-4a04-4a15-ae73-d30088642ce7"
AUTH_KEYCLOAK_IDENTIFIER_KEY="email"
AUTH_KEYCLOAK_ALLOW_PUBLIC_REGISTRATION="true"
```

![image](https://github.com/directus/directus/assets/5548518/61693e98-88c0-4b6b-a524-7c43456cc770)

**Comment by paescuj** [comment]
> can you elaborate more on how you have installed keycloak? Also, i am able to create users its just i cant login

Please make sure to always include as much relevant information as possible 🙏 That makes it much easier for other people to help 👍 

> can you elaborate more on how you have installed keycloak? Also, i am able to create users its just i cant login

For example: How did you install & configure Keycloak? What's the error message when logging-in? ...

**Comment by aidenfoxx** [comment]
Just to clarify when you say "I am able to create users its just i cant login", do you mean the users are automatically created when logging in, or you have manually created the users? If the users are manually created you must ensure the "Provider" is Keycloak. It is not possible to have multiple login providers for the same external identifier.

 I just ran a local Keycloak dev server using the portable server "zip".

**Comment by danieljwestman** [comment]
Same for us. Using Keycloak for SSO. Not possible to log in anymore (it worked fine a couple of weeks ago, before 10.10.3 I think...)

**Comment by aidenfoxx** [comment]
I managed to reproduce it. The error is "Invalid payload. The refresh token is required in either the payload or cookie." on refresh, and I only get it when I define the "MODE" variable to something other than "session" aka `AUTH_KEYCLOAK_MODE="cookie"`. Removing the `AUTH_KEYCLOAK_MODE` var or setting it to "session" works fine.

Almost certainly related to https://github.com/directus/directus/pull/21239 CC: @br41nslug

**Comment by br41nslug** [comment]
> Removing the AUTH_KEYCLOAK_MODE var or setting it to "session" works fine.

Thats strange, setting the `MODE` back to `cookie` should behave identical as before the `session` was introduced 🤔 
There seem to be a couple different conversations mixing here tho, danieljwestman thats probably a configuration issue as the OP can login check out the breaking change notes.

@aidenfoxx when reproducing did you specify the `mode` to match the configured sso mode on the refresh request?

**Comment by aidenfoxx** [comment]
I'm just using the standard SSO login flow from the admin page. Steps are:

- Update configuration to use `AUTH_KEYCLOAK_MODE="cookie"`
- Start Directus
- Login via SSO link in Directus admin
- Be redirected from provider
- Get kicked back to the admin login because the associated `refresh` request returns a 400

I have a hunch where the issue is, so I'll just do a quick check.

**Comment by aidenfoxx** [comment]
No hunch required. The issue is that the login button in the admin seems to default to `mode=session`. I guess the fix is to use the correct mode in the frontend based on configuration. 😁

**Comment by aidenfoxx** [comment]
No hunch required. The issue is just that the `/refresh` endpoint uses `mode=session` even though the driver is configured otherwise.

**Comment by br41nslug** [comment]
Ah yeah thats what confused me as of 10.10.4 the App itself only does `session` mode. `cookie` mode is there as a backwards compatibility feature for external systems and will not work with our App itself.

**Comment by aidenfoxx** [comment]
Makes sense. I would like to suggestion that a better backwards compatible way to handle this would be, in the case that a different `MODE` is defined, to set both the legacy "token" cookie, and the new "session" cookie, so that the admin UI would continue to work?

**Comment by br41nslug** [comment]
`backwards compatible` compatible may have been a bad choice of words on my part, "so that external systems can keep working while migrating to the session token".

We cannot re-introduce the cookie mode in the App unfortunately as this was explicitly replaced with the session token as security fix for our external security audit.

**Comment by aidenfoxx** [comment]
Okay, so the takeaway is everything is working as expected, and there might be something funky going on with your `AUTH_KEYCLOAK_MODE` @useEffects. I would try removing the param and it should work. 🤞

**Comment by paescuj** [comment]
Thanks for the feedback, @useEffects 👍
