### ISSUE TITLE
Issue with WebSockets Subscription Event Updates in Flow

### ISSUE THREAD

**Issue by dbuarque** [directus/directus#21680]
### Describe the Bug

We're experiencing an issue where WebSocket subscription events for updates do not trigger as expected when integrating with Flow. Interestingly, when utilizing the App Studio environment for update model, the subscription events are received and processed without any issues. However, the problem arises when we attempt to update models using Flow; the events are not received.  Any insights or solutions to ensure consistent event handling across both environments would be greatly appreciated?

### To Reproduce

Utilizing App Studio:

1. Initiate a WebSocket Subscription: Start by setting up a basic WebSocket subscription for a specified collection.
2. Record Creation: Use the App Studio interface to create a new record within the collection.
3. Record Update: Modify the previously created record directly through the App Studio.
4. Subscription Notification: Following these actions, you should successfully receive a notification message through the WebSocket subscription, confirming the update.

Modifying the Model via Flow:

1. Model Modification through Flow: Initiate the process by configuring a flow specifically designed to alter the model.
2. Activate the Flow: Execute the configured flow to implement changes to the model.
3. Subscription Notification Issue: Contrary to expectations, the expected message from the WebSocket subscription fails to be received following the model change triggered by the flow.

### Directus Version

v10.8.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
When editing data using Flows did you enable the "emit events" option? Which is disabled by default so people dont shoot themselves in the foot with infinitely looping events.
![image](https://github.com/directus/directus/assets/9389634/a1aa4607-221d-4679-8a0f-1c39d8822aaf)


Closing the issue for now but happy to re-open if needed 😄

**Comment by dbuarque** [comment]
Thank you!
