### ISSUE TITLE
WYSIWYG QuickTime video/media blank video box

### ISSUE THREAD

**Issue by GabrieliusGarmus** [directus/directus#21681]
### Describe the Bug

When uploading a QuickTime video to a WYSIWYG field, on Chrome it shows blank video square, works on Safari. Removing the type="video/QuickTime" from source tag seems to fix the issue.
![Screenshot 2024-03-04 at 9 49 55 AM](https://github.com/directus/directus/assets/108263280/be6ecf9c-3a53-4198-96c9-3df419272919)

### To Reproduce

On Chrome browser embed an apple QuickTime (.mov) video to a WYSIWYG editor

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Chrome, Firefox or others do not support apples QuickTime video codec as far as im aware. I recommend using `video/mp4` instead for better compatibility across devices.

**Comment by GabrieliusGarmus** [comment]
But it works fine if you remove the type attribute from the source tag

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by br41nslug** [comment]
@GabrieliusGarmus The mentioned workaround probably only works for chrome on Mac not on other operating systems. Do you have an example video in quicktime to test on other systems?

**Comment by GabrieliusGarmus** [comment]
I don’t have a video of it, but I had a colleague test it on his windows OS

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
