### ISSUE TITLE
There is a mistake in the docs about /version or /versions

### ISSUE THREAD

**Issue by VincentKempers** [directus/directus#21690]
### Page

https://docs.directus.io/reference/system/versions.html#request-2

### Describe the Inaccuracy

There is/was some confusion about the REST option here on POST here.

It says on the Reference header it's `POST /version` but on the the example it says `POST /versions`.
Which is a bit confusing. 

As you can see in the image here: 
![image](https://github.com/directus/directus/assets/14160793/26cef230-3565-4492-b3d8-8831c67e5529)

**Comment by paescuj** [comment]
Fixed in #21672 👍
