### ISSUE TITLE
Installation redirect loop when the php session directory is not writable

### ISSUE THREAD

**Issue by override2k** [directus/directus#2169]
## Version Info
- Directus version and branch (Or commit hash): aba7727
- PHP version: 7.1
- MySQL version: 5.7
- Web server: nginx
- OS name and version: Ubuntu 16.04

## Expected Behavior
When the php session directory is not writable by the webserver, will be nice to obtain a warning about that in the installation requeriments step.

## Actual Behavior

The installation process enters into a redirect loop that gets aborted by the browser. With this, the user cannot proceed the installation.

## Steps to Reproduce
1. Set the php session directory without write permission for the webserver
2. Try to launch directus installation process

## Schema Dump, Logs, or Screenshots

The bug is caused as php is unable to save session data, all the previous step progress is lost.

So when the installation reaches step 1 and the function `install_can_do()` checks if previous steps are pending (install.functions.php:123), the check fails, `isPending()` is always returning `false` for step 0, causing the installation program to reditect to step 0 again.

This derives into an infinite loop between step 0 and 1.

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/58)
