### ISSUE TITLE
Extensions shows missing after migrating to 10.10.0 

### ISSUE THREAD

**Issue by melrefaie** [directus/directus#21717]
### Describe the Bug

<img width="909" alt="image" src="https://github.com/directus/directus/assets/25461028/49fbeee6-0a75-4271-879e-3520e40ef93e">

after migrating to v10.10.0 i upgraded my Legacy extension type directory-based structure to this
https://docs.directus.io/releases/breaking-changes.html#deprecated-typed-extension-folders
and removed old folders 
it works fine but it show 2 extensions but i only have one.

### To Reproduce

just migrating any Legacy extension type directory-based  to new update.
you will get 2 extensions. 1 is missing. when i only have one.

### Directus Version

v10.10.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
Missing extensions refer to those that are in the database but not on the filesystem so this is probably a reference to your extension before the migration.

**Comment by terafirmanz** [comment]
a clean option "delete button" would be nice as the extensions table isn't particularly friendly to manually manipulate. I was able to clean mine by finding all local entries in the table and removing them after shifting all the extensions to the market place one and removing the files in the app extensions folder.
