### ISSUE TITLE
Marketplace migration fails if two bundles are installed that both have a sub-extension with the same name

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#21714]
### Describe the Bug

The latest [marketplace migration](https://github.com/directus/directus/blob/main/api/src/database/migrations/20240204A-marketplace.ts) seems to fail if you have two bundle extensions which both have a child with the same name.

E.g:
- bundleA
  - hook
- bundleB 
  - hook
  
**This is most likely a combination of the facts that:**

1. Bundle children previously have been named with the schema `parent/name`, which is now changed to create a single entry for children:
https://github.com/directus/directus/blob/6a4b9ba942bff8054deb63940e8fe1b36d4c23e2/api/src/database/migrations/20240204A-marketplace.ts#L45-L48

2. Previously there was a PK on the name, which is only removed at the end of the migration: https://github.com/directus/directus/blob/6a4b9ba942bff8054deb63940e8fe1b36d4c23e2/api/src/database/migrations/20240204A-marketplace.ts#L68-69

When the children are now stored as a single entry before the PK on the name is removed, the migration will fail, as it tries to create a second entry with the name `hook`

### To Reproduce

Try to update from a previous directus version to 10.10. There must be two bundle extension installed, whcih both have a child with the same name

### Directus Version

v10.10

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Same issue as warned for here https://github.com/directus/directus/issues/21017

**Comment by Dominic-Marcelino** [comment]
> Same issue as warned for here #21017

From what I understand this issue is about the api endpoint urls. My issue is just about the migration that fails due to the order. If the primary constraint would be removed earlier everything should work in this case.

This does not only applies to custom endpoints but all extension types.

**Comment by paescuj** [comment]
> > Same issue as warned for here #21017
> 
> From what I understand this issue is about the api endpoint urls. My issue is just about the migration that fails due to the order. If the primary constraint would be removed earlier everything should work in this case.
> 
> This does not only applies to custom endpoints but all extension types.

On it 👍
