### ISSUE TITLE
Marketplace "is down"

### ISSUE THREAD

**Issue by paulvonber** [directus/directus#21712]
### Describe the Bug

Just upgraded to v10.10.0 and doesn't seem that marketplace feel healthy :)

![image](https://github.com/directus/directus/assets/37245111/d1e04633-6db7-4d8c-bf6d-1b0b29dcc41c)

![image](https://github.com/directus/directus/assets/37245111/23c07e08-ad50-42be-9937-62cd09d71fa7)

### To Reproduce

Upgrade to v10.10.0

### Directus Version

v.10.10.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Thank you for opening the issue! Unfortunately, the registry went down. This has been fixed in the meantime and we improved some checks for the registry to better detect this case.
