### ISSUE TITLE
Can't create VARCHAR column via API

### ISSUE THREAD

**Issue by bensteers** [directus/directus#2172]
Creating a VARCHAR column via the API reports a SQL error:

POST query to `/api/1.1/tables/mytable/columns`

### Working query
request: `{'column_name': 'number', 'data_type': 'INT'}`
response: `{'meta': {'type': 'item', 'table': 'directus_columns'}, 'data': {'id': 'number', 'name': 'number', 'column_name': 'number', 'type': 'INT', 'column_type': 'int(11)', 'length': 0, 'precision': 10, 'scale': 0, 'sort': 9999, 'default_value': None, 'nullable': True, 'key': '', 'extra': '', 'extra_options': [], 'options': [], 'table_name': 'nodes', 'required': False, 'system': False, 'ui': 'numeric', 'hidden_input': False, 'relationship': None, 'comment': "''", 'relationship_type': None, 'related_table': None, 'junction_table': None, 'junction_key_right': None, 'junction_key_left': None}}`

### The query with an error
request: `{'column_name': 'words', 'data_type': 'VARCHAR'}`
response: `{'success': False, 'error': {'message': 'Statement could not be executed (42000 - 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'DEFAULT NULL COMMENT "\'\'"\' at line 1)'}, 'code': 0, 'class': 'Zend\\Db\\Adapter\\Exception\\InvalidQueryException', 'file': '/var/www/html/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php', 'line': 244}`

## Version Info
  - Directus version and branch (Or commit hash): 6.4.9
  - PHP version: 7.1.17
  - MySQL version: Ver 14.14 Distrib 5.5.60, for debian-linux-gnu (x86_64) using readline 6.3
  - Web server: (Ex. Apache, nginx or IIS?) 
  - OS name and version: Debian GNU/Linux 8 (jessie)

## Steps to Reproduce
 1. create table 
 2. make the two requests above

**Comment by beac0n** [comment]
It's sad, that this error still persists.
You have to provide a `length` property in your POST request, since VARCHAR needs a length.

This is NOT documented in https://api.getdirectus.com/1.1/#Create_Column 
I only figured this out, because I reverse engineered the API, using the GUI

**Comment by benhaynes** [comment]
My sincere apologies for this not being addressed sooner. Our Core staff has spent the past year working on the new version and we made the decision early on to stay focused on that rather than splitting time between both versions. 

The new version is out and has 100% of our attention. We're working hard to get our docs perfect...

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/60)
