### ISSUE TITLE
Marketplace extensions not working

### ISSUE THREAD

**Issue by Lucas-Gruber** [directus/directus#21724]
### Describe the Bug

When i want to install a extension through the marketplace, it appears as missing.
![image](https://github.com/directus/directus/assets/72545889/bd5e6022-e4bb-4326-9beb-923b326223be)

edit: the first extension is legacy, the others are from marketplace.

### To Reproduce

- Go to any extension in the marketplace and click install
- Click on extensions

### Directus Version

v10.10.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Do you see any warnings/errors in the server logs? Is this still the case after refreshing page?

**Comment by Lucas-Gruber** [comment]
In the logs is nothing. But i fixed it now.

The Solution is to completely clear the extension folder and clear the extension table in the db.

**Comment by br41nslug** [comment]
How are running Directus? It sounds like for example in a docker the `/directus/extension/.registry` folder is not writeable

**Comment by Lucas-Gruber** [comment]
I run it normaly through docker compose. And the extensions-folder is with 777 permissions and as docker volume

**Comment by paescuj** [comment]
What database are you using?

**Comment by Lucas-Gruber** [comment]
PostgreSQL in the compose stack with redis as cache

**Comment by makowey** [comment]
If you combine some extensions like `@directus-labs/aubergine-theme` with `directus-extension-computed-interface` you should be able to replicate it. Not all the extensions works well together. I use Directus on railway.app with PostgreSQL.
