### ISSUE TITLE
Redirect after SSO not working on 10.10.0 and 10.10.1 with Cookie Mode

### ISSUE THREAD

**Issue by Cel51** [directus/directus#21739]
### Describe the Bug

Redirect after SSO on the two latest version using the Cookie mode don't work

### To Reproduce

Using Google Auth provider as an example and version ^10.10.0:

```env
AUTH_GOOGLE_DRIVER="openid"
AUTH_GOOGLE_MODE="cookie"
AUTH_GOOGLE_CLIENT_ID="<clientid>"
AUTH_GOOGLE_CLIENT_SECRET="<clientsecret>"
AUTH_GOOGLE_ISSUER_URL="https://accounts.google.com"
AUTH_GOOGLE_IDENTIFIER_KEY="email"
AUTH_GOOGLE_ICON="google"
AUTH_GOOGLE_LABEL="Google"
AUTH_GOOGLE_ALLOW_PUBLIC_REGISTRATION="true"
AUTH_GOOGLE_DEFAULT_ROLE_ID="<my uuid>"
```

redirect to http://localhost:8055/admin/login?reason=SIGN_OUT with no login

And the same .env but without cookie mode in version 10.9.3 works perfectly
```env
AUTH_GOOGLE_DRIVER="openid"
AUTH_GOOGLE_CLIENT_ID="<clientid>"
AUTH_GOOGLE_CLIENT_SECRET="<clientsecret>"
AUTH_GOOGLE_ISSUER_URL="https://accounts.google.com"
AUTH_GOOGLE_IDENTIFIER_KEY="email"
AUTH_GOOGLE_ICON="google"
AUTH_GOOGLE_LABEL="Google"
AUTH_GOOGLE_ALLOW_PUBLIC_REGISTRATION="true"
AUTH_GOOGLE_DEFAULT_ROLE_ID="<my uuid>"
```

### Directus Version

v10.10.0 | v10.10.1 

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
If I understand you correctly, you're trying to use 'cookie' mode for accessing the Directus app. This isn't supported anymore as of v10.10.0. The app requires the 'session' mode (which is the new default). See https://docs.directus.io/releases/breaking-changes.html#session-cookie-based-authentication for more information.

If you however use the 'cookie' mode with an external app and want to redirect to an external URL, you need to add that URL to the allow list introduced in v10.10.0, see https://docs.directus.io/releases/breaking-changes.html#introduced-allow-list-for-oauth2-openid-saml-redirects.

I'm closing this issue for now, as it seems to work as expected. Happy to keep discussing in this thread, and we'll reopen if it should turn out to be an actual issue 👍🏻
