### ISSUE TITLE
Not showing custom error message text for non-admins from a flow

### ISSUE THREAD

**Issue by ymc-sise** [directus/directus#21738]
### Describe the Bug

When throwing an error message in a "Run Script" operation on a filter event hook flow, the message is only readable for admin user. For non admin user it's called "An unexpected error occurred."

```
module.exports = async function(data) {
    const input = data.$trigger.payload;

    throw {
		message: 'My custom error message',
		extensions: {
	                 code: 400,
                         field: 'accounting_period',
			type: 'neq',
			invalid: input.accounting_period,
		},
	};
}
```

<img width="440" alt="Bildschirmfoto 2024-03-07 um 10 16 20" src="https://github.com/directus/directus/assets/1014016/d6ea6418-1a1a-489e-8e71-02295d0b787c">

It's the same discussion as here https://github.com/directus/directus/discussions/16342#discussioncomment-4192092 but it is closed and locked.

Could you please fix this and show the custom error message for non admins? I think it would not be a lot of effort to fix this and it would be very helpful for UX for our users.

Here the stacktrace has been removed https://github.com/directus/directus/pull/18421 but it still not working.

Or could you give me an example how to show a custom error message to non admin users? Do I have to implement a custom operation?

### To Reproduce

- Create filter event hook flow
- Create Run Script and throw error message

```
module.exports = async function(data) {
    const input = data.$trigger.payload;

    throw {
		message: 'My custom error message',
		extensions: {
	        code: 400,
            field: 'accounting_period',
			type: 'neq',
			invalid: input.accounting_period,
		},
	};
}
```

- Login as non admin user
- Trigger the flow
- See error message "An unexpected error occurred." instead of "My custom error message".

### Directus Version

v10.9.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by ivangrosse** [comment]
+1 to this, it would be really useful to have the ability to send custom API error responses visible for all users interacting with the API

**Comment by rijkvanzanten** [comment]
Can you try throwing a `DirectusError` rather than a plain object? Directus has a check to see if it's a known error type before returning it to the client. Try `npm install @directus/errors`, and then use it [to create an error](https://docs.directus.io/packages/@directus/errors/#creating-a-new-error-class) you can throw:

```ts
import { createError } from '@directus/errors';

interface ForbiddenErrorExtensions {
	collection: string;
	field: string;
}

const ForbiddenError = createError<ForbiddenErrorExtensions>(
	'FORBIDDEN',
	"You don't have permissions to see this.",
	403,
);

--snip--

throw new ForbiddenError({
	collection: 'articles',
	field: 'title',
});
```

**Comment by ymc-sise** [comment]
@rijkvanzanten And how does it work in "Run Script"?

**Comment by paescuj** [comment]
FWIW, we already mention it in the docs for Custom Filter Hooks: https://docs.directus.io/extensions/hooks.html#filter

However, this neither works in Run Script Operation nor (correctly) with Sandboxed Extensions, in which we might want to expose the errors package.

**Comment by floux-digital** [comment]
have a feature request approved for this. Look for: https://github.com/directus/directus/discussions/18634

**Comment by ymc-sise** [comment]
@rijkvanzanten I have solved it using a custom operation and your code example with `createError`. Non admin user will see the error message now, this is a huge improvement.Thx!

**Comment by timspi** [comment]
Custom errors are only displayed when the error is a Directus error (to not leak data). The check for a Directus error is implemented [here](https://github.com/directus/directus/blob/main/packages/errors/src/is-directus-error.ts).

Therefore, if you want to return a custom error message from a flow, you have to set the name property of the error to `DirectusError`. This is usually done in the background when using the `createError` function, but as it is not available in a flow, the name should be set manually.

For example, with this Run Script operation:

```
class CustomError extends Error {
	name = 'DirectusError'; // this line is key!
	code = 'CUSTOM_ERROR_CODE';
	status = 418;

	constructor() {
		super('Some custom error message.');
	}

	toString() {
		return `${this.name} [${this.code}]: ${this.message}`;
	}
};
module.exports = async function(data) {
	throw new CustomError();
}
```
