### ISSUE TITLE
Mail service doesn't return driver/transport result anymore

### ISSUE THREAD

**Issue by keesvanbemmel** [directus/directus#21740]
### Describe the Bug

[Since 10.10.0](https://github.com/directus/directus/pull/21683) the result of an email transport is not being return anymore. There is no option to get this result, while we have production services relying on this result.

The usecase: we send out mails with Directus and store the id of the transport email message so we can pickup webhooks later on those messages.

@paescuj asked me to create this issue.

### To Reproduce

n/a

### Directus Version

v10.10.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Thanks @keesvanbemmel! Do you use the mail service via Extensions and/or Flows?

**Comment by keesvanbemmel** [comment]
Extensions.

```
const mailResult = (await mailService.send(mailConfig)) as any;
    const driverId = mailResult.id?.slice(1, -1);
  // Store data returned by the mail service as well as sent date and stage.
  const updateNotificationObject = {
    date_sent: new Date().toISOString(),
    metadata: JSON.stringify(mailConfig, null, 2),
    driver_id: driverId,
    status: 'sent',
    to,
    cc,
    bcc,
    subject: mailConfig.subject,
  };

  await notificationItemsService.updateOne(id, updateNotificationObject);
```
