### ISSUE TITLE
Existing Custom Extensions Not Working After Directus Update to 10.10.1

### ISSUE THREAD

**Issue by kashyap-7span** [directus/directus#21743]
### Describe the Bug

I updated Directus from 10.9.3 to 10.10.1 and ran directus bootstrap. Now, my custom extensions, including endpoints and hooks in a single bundle, aren't working. Additionally, I have registered the bundle in package.json under dependencies.

**Expected Behavior:**
After the update and bootstrap, existing custom extensions should work as before.

**Actual Behavior:**
Custom extensions, previously functional, are now broken after the update.

**Additional Info:**
No errors were reported during the update or bootstrap process.

### To Reproduce

**To Reproduce:**

1. Update Directus to version 10.10.1.
2. Run directus schema migration command `npx directus database migrate:latest`.
3. Try using existing custom extensions.
4. Notice that the extensions, including endpoints and hooks, are not functioning.

### Directus Version

v10.10.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
Please read the breaking changes notes for the release and update your extensions accordingly.

https://docs.directus.io/releases/breaking-changes.html#version-10-10-0

**Comment by kashyap-7span** [comment]
@br41nslug What changes do I have to make can you help me with that for this structure

Root package.json
`{
  "main": "index.js",
  "scripts": {
    "start": "npx directus start",
    "build": "npm run build-extensions-bundle-crm"
  },
  "dependencies": {
    "@directus/sdk": "^11.0.3",
    "@discordjs/rest": "^2.2.0",
    "directus": "^10.9.3",
    "directus-extension-crm": "./custom-extentions/bundles/crm/"
  }
}`

Bundle's package.json
`{
  "name": "directus-extension-crm",
  "version": "1.0.0",
  "type": "module",
  "icon": "extension",
  "directus:extension": {
    "host": "^10.1.14",
    "type": "bundle",
    "path": {
      "app": "dist/app.js",
      "api": "dist/api.js"
    },
    "entries": [
      {
        "type": "endpoint",
        "name": "endpoint-name",
        "source": "src/routes/endpoints/endpoint-a.js"
      },
      {
        "type": "hook",
        "name": "hook-name",
        "source": "src/routes/hooks/hook-1.js"
      },
      {
        "type": "module",
        "name": "module-name",
        "source": "src/modules/module-a"
      },
      {
        "type": "interface",
        "name": "interface-name",
        "source": "src/interfaces/interface-a"
      },
      {
        "type": "display",
        "name": "display-name",
        "source": "src/display/display-a"
      },
    ]
  },
  "keywords": [
    "directus",
    "directus-extension",
    "directus-custom-bundle"
  ],
  "scripts": {
    "build": "directus-extension build",
    "dev": "directus-extension build -w --no-minify",
    "link": "directus-extension link",
    "add": "directus-extension add"
  },
  "devDependencies": {
    "@directus/extensions-sdk": "10.1.14"
  }
}`
