### ISSUE TITLE
Login redirect 

### ISSUE THREAD

**Issue by jreid06** [directus/directus#2174]
**For security issues, please email support@getdirectus.com directly.**

## Version Info
  - Directus version and branch (Or commit hash):
  - PHP version: 7.2
  - MySQL version: 5.5
  - Web server: Apache
  - OS name and version: 

## Expected Behavior
1. My directus data is stored in a folder called "/backend"
2. When logged in successfully i expect it to redirect user to their dashboard either '**backend**/tables' or their last location e.g '**backend**/tables/blog_posts'

## Actual Behavior
1. User is logged in successfully is credentials match and url will match their last location e.g  '**backend**/tables/blog_posts'; HOWEVER they see the index.php in the project root so the front end of the website and not the admin side
2. The only way then to access the backend is to then visit '/backend' and then the user is redirected to directus and can view/edit/ content for their website. 
3. This issue only happens when on the server and cannot reproduce it on my local machine. I use a Mac book pro for local development 

## Schema Dump, Logs, or Screenshots
**The actual result below** 
<img width="1127" alt="screen shot 2018-07-06 at 09 51 06" src="https://user-images.githubusercontent.com/19251469/42369555-3a5ac7cc-8102-11e8-901c-31f0dcd024fd.png">

**The expected result** 
<img width="895" alt="screen shot 2018-07-06 at 09 51 30" src="https://user-images.githubusercontent.com/19251469/42369579-4ec5dc1a-8102-11e8-9212-00e3a8da4f8a.png">

**Comment by jreid06** [comment]
Any ideas why this is happening? has anyone else had the same issue

**Comment by marcozellweger** [comment]
I'm having the same issue. User is logged in successfully is credentials match and url will match their last location. e.g. /admin/tables. But they see a 404 error. They must remove tables from the url and load the page again. Then the user get successfully redirected to /admin/tables

**Comment by jreid06** [comment]
Did you have any luck solving this issue? @marcozellweger

**Comment by rijkvanzanten** [comment]
Could you check the value of `DIRECTUS_PATH` in `config.php`? I think that might be the thing that controls where Directus redirects to on login:

https://github.com/directus/directus/blob/ab5a935073324389db2e3444b5f1272753f7780f/api/config_sample.php#L31

**Comment by jreid06** [comment]
The directus path is set to "/backend/" where my directus instance is located. On my local version everything works fine and the user is redirected to the dashboard however on the server it redirects then to the root path of the website showing index.php

**Comment by jreid06** [comment]
I then have to use javascript to redirect user to the dashboard. However This isn't an efficient solution. For now it works but i would like to fix this issue asap

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/61)
