### ISSUE TITLE
Promoted version overwrites other versions in addition to the Main version

### ISSUE THREAD

**Issue by AndriyStankevych** [directus/directus#21748]
### Describe the Bug

When we have un-updated 'backup' version of main version and we promote any changes from another version to 'Main' the 'backup' version takes the all changes from promotion too.
Here is the link with issue replication 
[https://drive.google.com/file/d/1Vy4JmBZDcooobkyv2RznWgRf5lqaQZkt/view](https://drive.google.com/file/d/1Vy4JmBZDcooobkyv2RznWgRf5lqaQZkt/view)

### To Reproduce

1. Open a simple document with minimal data
2. Create a version - set key and name (name it 'backup') - save
3. Don’t make any changes in created version ('backup'), switch to Main
4. Create another version - set key and name (name it 'temp') - save
5. Edit name in new ('temp') version - save it
6. Switch to the new ('temp') version again and click Promote
7. Confirm promotion, click Keep on the dialogue

AR: See Main, 'backup' and 'temp' versions are exactly the same.
ER: 'backup' version mustn't be updated on promotion of the other versions to Main 

### Directus Version

v10.10.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
> 3. Don’t make any changes in created version ('backup'), switch to Main

Content versions stored the updated data (diffs) not the entire object so you cannot use it as "backup" like this. If you do not make any changes on the version it will be an "empty version difference" thus be identical to the main item.

**Comment by AndriyStankevych** [comment]
@br41nslug 

Thank you so mush for quick update on issue.

Now I understand how the versioning are implemented and can adjust our scenarios of using it.

Seems to me your explanation is totally different from what is described under directus official documentation [link](https://docs.directus.io/guides/headless-cms/content-versioning.html#concepts)
> Version: A version is a snapshot of a piece of content at a particular point in time.

Is it on the roadmap to implement versioning like a snapshot of data?

**Comment by br41nslug** [comment]
Oh hmmm, you're very right that description there gives a very different impression. We'll definitely want to update that 😃 re-opening this issue to update the docs
