### ISSUE TITLE
skip_activity_log not working for /rows/bulk

### ISSUE THREAD

**Issue by bensteers** [directus/directus#2175]
`?skip_activity_log=1` is not disabling activity logging for bulk row uploads.

## Version Info
- Directus version and branch (Or commit hash): 6.4.9
- PHP version: 7.1.17
- MySQL version: Ver 14.14 Distrib 5.5.60, for debian-linux-gnu (x86_64) using readline 6.3
- OS name and version: Debian GNU/Linux 8 (jessie)

I suspect that this is the needed update:
```php
// directus/api/core/Directus/Database/TableGateway/RelationalTableGateway.php, line 2018
...
// change
    public function updateCollection($entries)
    {
        $entries = ArrayUtils::isNumericKeys($entries) ? $entries : [$entries];
        foreach ($entries as $entry) {
            $entry = $this->updateRecord($entry);
            $entry->save();
        }
    }
// to
    public function updateCollection($entries)
    {
        $entries = ArrayUtils::isNumericKeys($entries) ? $entries : [$entries];
        foreach ($entries as $entry) {
            $entry = $this->updateRecord($entry, $this->getActivityMode());
            $entry->save();
        }
    }
...
```
I just haven't had a minute to test before submitting a pull request.

**Comment by benhaynes** [comment]
Kamino cloned this issue to [directus/api](https://github.com/directus/api/issues/515)

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/62)
