### ISSUE TITLE
Getting and already authenticated Session Token

### ISSUE THREAD

**Issue by emahuni** [directus/directus#21757]
### Describe the Improvement

I have realised that there is no way of getting the session token in the new Directus ^v10.10.0 since the session cookie is Http Only, meaning that only the server can access it. This is very good for preventing XSS attacks and is very welcome. 

However, when one tries to use an existing authentication session, eg: in an extension to authenticate something like a websocket using `handshake` mode for instance, hell will have its revenge on them because there is no way of getting that token from the client side.

Unless there is an undocumented method of doing this, or maybe I am missing it somewhere, I think this was not considered or documented for the new version.

The only way I have been able to get that token was to create an `endpoint` extension then get the token using an `api.get` call. Here is the simple code that, that I think should be part of the core to address that issue ~~without compromising the new security measures~~:

```js
import { defineEndpoint } from '@directus/extensions-sdk';

export default defineEndpoint(
    {
        id     : 'auth',
        handler: (router) => {
            router.get('/get-session-token', (_req, res) => {
                // Read the session token from the HTTP-only cookie
                const sessionToken = _req.cookies['directus_session_token']; 

                if (!sessionToken) {
                    // Handle the case when the token is missing
                    return res.status(401).json({ error: 'Session token not found' });
                }

                // Send the session token in the response
                res.json({ sessionToken });
            });
        },
    },
);

```

Then use the api to get the token:

```js
            import { useApi } from '@directus/extensions-sdk';
            
            const api = useApi();
            const response = await api.get('/auth/get-session-token'); 

            if (response.status !== 200) {
                throw new Error(`ERROR: getting session token!`);
            }

            // ... for the handshake this works
            ws.send(JSON.stringify({ type: 'auth', access_token: response.data.sessionToken }));
```

What's good about this is that it will only get the token of the authenticated user as they send the request from the authenticated client. So there is ~~no~~ apparent security hole I can think of that's not already exposed by the http only session cookie.

... and this needs to be documented as well.

**Comment by br41nslug** [comment]
Building in a feature to bypass the httpOnly setting of cookies would undermine all the security advantages of having httpOnly cookies (a malicious script would only have to call the endpoint to get access to the plaintext token which was not supposed to be known to JS to prevent exactly that).

To achieve this same effect but less hidden we could make `httpOnly` configurable so people can disable the behavior when really needed however i dont think this address the issue you're trying to solve.

I believe the real solution here to implement session based authentication for WebSockets.

**Comment by g-pichler** [comment]
While I do agree, that the proper way of fixing this is to enable WebSockets to send the authorization cookie with the initial request, I don't think this is feasible. After spending some time investigating, _hell did have its revenge on me_. I do not believe that it is possible with JS websockets to enable CORS credentials, at least not easily. Thus, IMO, the `session` mode effectively breaks the WebSocket feature of directus.

Thus, as it stands, we are caught between a rock and a hard place:
Using `cookie` mode, GraphQL websocket subscriptions work, but the App does not. With `session` mode, the App works, but websockets do not.

**Comment by rijkvanzanten** [comment]
As was discussed in https://github.com/directus/directus/discussions/21715 as well, we currently don't have any plans to explicitly expose the access or session tokens to the JS in the Directus app itself, for the security reasons that are mentioned above as well. That being said, the previous cookie based auth still exists and can still be used through the API for use in your own apps.

For the WebSocket connection / SDK specifically, I agree that we're in need of a feature there where it can authenticate using the existing session cookie. We'll track that here: https://github.com/directus/directus/issues/21825

As for this issue, not having access to the tokens in client side JS when using the `session` mode is the intended behavior so I'll close this issue 👍🏻
