### ISSUE TITLE
Bundle extension loading but not working in 10.10.1

### ISSUE THREAD

**Issue by boncossoftware** [directus/directus#21758]
### Describe the Bug

My custom bundle extension seems to be loading and visible in the Settings -> Extensions tab (see image).
![Screenshot 2024-03-08 at 09 47 05](https://github.com/directus/directus/assets/5249176/27ef45e2-9c20-4a8b-896e-48c4e4cfcd0c)

But they are not displayed in the collection item forms and are show up as "...not found" in the field interface settings (see image bellow).
![Screenshot 2024-03-08 at 09 49 50](https://github.com/directus/directus/assets/5249176/fda17b7c-8b3a-4b50-81cc-923dd8bc3b79)

Also, the endpoints and hooks don't seem to be working. 

I have made sure my bundle meets all of the latests requirements  explained here https://docs.directus.io/releases/breaking-changes.html#deprecated-typed-extension-folders. The bundle is currently being imported as a npm package (not placed in the extensions folder).

Also one more thing to note is that when I check the "/extensions/sources/index.js" being loading from the app it seems to be completely empty (see image).

![Screenshot 2024-03-08 at 09 58 29](https://github.com/directus/directus/assets/5249176/e10e2986-4be7-49a9-a0ab-bca292fa16b2)

### To Reproduce

Wouldn't know exactly how to reproduce the issue with other extensions. I have a bundle type extension in typescript with many interfaces, endpoints, hooks and some displays and not sure if one of these is causing the issue. Might also be how the npm package is being build.

### Directus Version

v10.10.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by boncossoftware** [comment]
Forgot to mention that the bundle extension was working in version 10.9.3.

**Comment by br41nslug** [comment]
Judging from your screenshot of the dist this seems to be an issue with building the extension rather than loading it. Did you update the extensions-sdk for your extension when updating the Directus instance?

**Comment by boncossoftware** [comment]
Yes, is currently at 11.0.1

**Comment by boncossoftware** [comment]
![Screenshot 2024-03-08 at 11 06 08](https://github.com/directus/directus/assets/5249176/1f67c9e5-cbe1-44c2-ae71-ef08b859ba80)

![Screenshot 2024-03-08 at 11 07 04](https://github.com/directus/directus/assets/5249176/92d9cf8c-cb69-4859-9e57-083d6b149d47)

I can also see that the built app.js exports the interfaces, etc.

**Comment by KayhanB** [comment]
Hi, I experienced the same issue and found a workaround. When I deleted the records in the directus_extensions collection and restarted directus, the newly added extension started working. Make sure your  bundle is packaged with the new extension before restarting.

**Comment by wolfgang-hartl** [comment]
> I experienced the same issue and found a workaround. When I deleted the records in the directus_extensions collection and restarted directus, the newly added extension started working. Make sure your bundle is packaged with the new extension before restarting. @wolfgang-hartl

Thank you very much @KayhanB ... that works for me as well!! 👍

**Comment by malipetek** [comment]
> I experienced the same issue and found a workaround. When I deleted the records in the directus_extensions collection and restarted directus, the newly added extension started working. Make sure your bundle is packaged with the new extension before restarting. @wolfgang-hartl

Thanks, this was the case for my bundle extension as well. I guess this has something to do with starting with a faulty `package.json`

**Comment by aldoprogra** [comment]
I have hooks and endpoint working local but when deploying on railway they result to be enabled but they do no work. Should I build extensions when deploying? create a script that builds ? Thank you in advance

**Comment by wolfgang-hartl** [comment]
> I have hooks and endpoint working local but when deploying on railway they result to be enabled but they do no work. Should I build extensions when deploying? create a script that builds ? Thank you in advance

Can only speak for myself, but deploying the extensions work fine for me. Make sure, that the dist folder is present when deploying your extensions. I guess it's also adviseable to change the version in the package.json in your extension if you modify an already deployed extension.

**Comment by aldoprogra** [comment]
> > I have hooks and endpoint working local but when deploying on railway they result to be enabled but they do no work. Should I build extensions when deploying? create a script that builds ? Thank you in advance
> 
> Can only speak for myself, but deploying the extensions work fine for me. Make sure, that the dist folder is present when deploying your extensions. I guess it's also adviseable to change the version in the package.json in your extension if you modify an already deployed extension.

Thank you very much! dist was in the .gitignore and removing it of course solved the problem. Thank you very much for the fast solution wolfgang!
