### ISSUE TITLE
Dashboard pages try to load all activity

### ISSUE THREAD

**Issue by bensteers** [directus/directus#2177]
When you go to a dashboard edit page, e.g. `/tables/[table]/1`, it tries to load all of the revisions into the right sidebar. But when I was dealing with #2176, our `directus_activity` table got to ~7 million records, so the pages just wouldn't load and they would hang on the Loading Data message. It wasn't until I dumped the directus_activity rows that I was able to use those pages again. I'd recommend limiting that query to something like ~100 revisions, just so that even if the directus_activity does explode, the app is still usable.

**Comment by benhaynes** [comment]
Kamino cloned this issue to [directus/api](https://github.com/directus/api/issues/516)

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/63)
