### ISSUE TITLE
Filtering throws exception

### ISSUE THREAD

**Issue by michaelbriordan** [directus/directus#2178]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus version and branch (Or commit hash): 6.4.0
  - PHP version: 7.1.9
  - MySQL version: 10.1.31-MariaDB
  - Web server: (Ex. Apache, nginx or IIS?) Apache 2.4.27
  - OS name and version: CentOS Linux release 7.4.1708 (Core)

## Expected Behavior

HTTP/1.1 200 OK
Date: Thu, 12 Jul 2018 13:21:17 GMT
Server: CentOS WebPanel: Protected by Mod Security
X-Powered-By: PHP/7.1.9
Cache-Control: no-store,no-cache,must-revalidate
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8

{"meta":{"table":"EDITIONS","type":"item"},"data":{"id":126,"Year":1603,"Title":"... <etc>

## Actual Behavior

500 Internal Server Error

## Steps to Reproduce
Call API on multiple platforms. Tried Paw, browser, cURL and PHP (with/without Guzzle). 

The HTTP request sent was:
GET /api/1.1/tables/EDITIONS/rows?filters%5BDate%5D%5Beq%5D=1603 HTTP/1.1  
# Paw automatically encodes '[' and ']' - I have tried it in the browser with '[' and ']'
Authorization: Basic * * * *
Cookie: PHPSESSID=dv2u2340v6ov96n4iri8biu39i
Host: directus.michaelriordan.uk
Connection: close
User-Agent: Paw/3.1.7 (Macintosh; OS X/10.13.5) GCDHTTPRequest

## Schema Dump, Logs, or Screenshots

tail apache error_log:
[internal function]: Directus\\Database\\TableGateway\\RelationalTableGateway->processFilters(Object(Directus\\Database\\Query\\Builder), Array) in /home/mbr50/cms/directus/api/core/Directus/Database/TableGateway/RelationalTableGateway.php on line 1171

**Comment by benhaynes** [comment]
Kamino cloned this issue to [directus/api](https://github.com/directus/api/issues/517)

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/64)
