### ISSUE TITLE
Changing user field from M2O to User Created

### ISSUE THREAD

**Issue by maettyhawk** [directus/directus#2179]
There's some weird behaviour when I change a table's field "user" from M2O (referencing Directus user table) to User Created. As seen in screenshot 3 the change causes an error when trying to add a new entry. Also the table settings show a M2O relation for the "user" field, which is not displayed if one sets the field type to User Created or Modified from the very beginning.

## Version Info
  - Directus version: 6.4.9
  - PHP version: 7.2
  - MySQL version: 5.7.21
  - Web server: Apache
  - OS name and version: Ubuntu

## Expected Behavior
Changing a "user" field from M2O to User Modified/Created causes no error when trying to add a new entry to that table.

## Actual Behavior
Changing a "user" field from M2O to User Modified/Created causes an error when trying to add a new entry to that table.

## Steps to Reproduce
1. Add a new table
2. Add a new field "user" (M2O -> referencing directus_user -> id)
3. Try to add a new entry (should work)
4. Change the field type of "user" to User Modified or Created
5. Try to add a new entry (error appears)

## Schema Dump, Logs, or Screenshots
![directus-1](https://user-images.githubusercontent.com/1299262/42687037-126c8a5c-8698-11e8-9cd3-65462200d98e.png)
![directus-2](https://user-images.githubusercontent.com/1299262/42687036-1253d278-8698-11e8-9415-01e3a2a5e2c6.png)
![directus-3](https://user-images.githubusercontent.com/1299262/42687035-12380908-8698-11e8-925a-ab1cb64cf49c.png)

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/65)
