### ISSUE TITLE
Item is not duplicating, even after checking all the duplication fields

### ISSUE THREAD

**Issue by bastion-tom** [directus/directus#21790]
### Describe the Bug

When I "Save as copy", not all the contents are duplicated. I've tried to enable all the fields in the data model (also, is there a way I can wildcard everything? Saves clicking on 50+ fields etc). 

Especially in the builder, the types come across but nothing inside the types

### To Reproduce

Edit content and "save as copy"

### Directus Version

v10.9.2

### Hosting Strategy

Directus Cloud

**Comment by br41nslug** [comment]
Please provide enough information to reproduce the issue:
- What does the collection look like that you're duplicating?
- What fields are not copying? and what fields are?
- How did you configure the duplication fields for the collection?

**Comment by bastion-tom** [comment]
These are the fields for he data. model:
<img width="817" alt="image" src="https://github.com/directus/directus/assets/156729968/a7e0a5a4-1121-4b4f-8303-d8c0f76ec05d">

This is how the items are checked:
<img width="848" alt="image" src="https://github.com/directus/directus/assets/156729968/5fee7360-9c00-44f6-ace4-c1b7889b67b5">

Example of the result when saved (Builder information didn't come across)
<img width="544" alt="image" src="https://github.com/directus/directus/assets/156729968/23457b35-72ef-464d-897a-2ebc72b3e115">

**Comment by bastion-tom** [comment]
Just bumping this

**Comment by bastion-tom** [comment]
@br41nslug  - Is there any other information you need?

**Comment by paescuj** [comment]
Heya, thanks for opening the issue!

This has now been fixed via #21896 which will be available in the next release.
After the fix has been released, you'll be able to select the related field at root level and all items will be copied as expected:
<img width="200" src="https://github.com/directus/directus/assets/5363448/43ae586d-cab7-4b57-9077-bf194011dbf0">

> (also, is there a way I can wildcard everything? Saves clicking on 50+ fields etc).

This will be tracked in a separate issue 👍
