### ISSUE TITLE
forbidden to import Users (No Permission)

### ISSUE THREAD

**Issue by Triggsy22** [directus/directus#21799]
### Describe the Bug

If you try to import Users inside the Directus _User Directory_, the following Error is thrown:
`{message: "You don't have permission to access this.", extensions: {code: "FORBIDDEN"}}`

### To Reproduce

1. Go to the User Directory
2. Export a User as CSV
3. Delete that User
4. Try to import the CSV
5. Error happens

### Directus Version

v10.9.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Triggsy22** [comment]
This was already fixed 2022: https://github.com/directus/directus/pull/14065
I think it has something todo with: https://github.com/directus/directus/blob/4575ce3a205e49336f390a8f57d82438dca3ad58/api/src/services/import-export.ts#L52C46-L52C64

**Comment by paescuj** [comment]
Are you trying to import under a non-admin user? As you've noticed yourself, this is currently blocked [^1].
However, we should either update this check to allow non-admins with create permission to import as well or else completely hide the import functionality for non-admins in the app.

[^1]: https://github.com/directus/directus/blob/4575ce3a205e49336f390a8f57d82438dca3ad58/api/src/services/import-export.ts#L52C46-L52C64

**Comment by Triggsy22** [comment]
The User has _Admin Access_ enabled.

**Comment by Triggsy22** [comment]
It was my fault :(
I had additional fields in the user part and the error happend because of them.
