### ISSUE TITLE
Global bookmark updates don't propagate

### ISSUE THREAD

**Issue by echocrow** [directus/directus#21807]
### Describe the Bug

When editing the config of a global bookmark (`/admin/settings/presets/{id}`), the changes are not reflected immediately after saving. Affected changes include e.g. the bookmark name, filters, or layout table columns.

After several minutes (5? 15? unsure how long) and a page refresh, only then are the changes applied when viewing the bookmark on an items page.

Seems as though there may be a cached state that lives longer than it should?
We're also only observing this bug in Directus Cloud, but not locally (further hinting towards this being cache related).

### To Reproduce

Creating global bookmarks:

1. Go to `Settings > Bookmarks > +` (`/admin/settings/presets/+`) and configure a global bookmark:
    1. Choose a collection
    2. Set scope to `Global: All Users`
    3. Set a name, e.g. `TEST`
    4. Save
2. Go back to Content
    - Expected: See the new global bookmark under the collection it was associated with (in step 1.1.).
    - Actual: No new global bookmark shown.

Updating global bookmarks:
1. Under Content, on an existing global bookmark click `⋮ > Edit Global Bookmark`
    - (this directs you to `/admin/settings/presets/{id}`)
2. Edit the bookmark:
    1. Change the name, e.g. to `TEST 2`
    2. Change the filters in any way
    3. Save
3. Go back to Content
    - Expected: See the same global bookmark with the updated name. Navigating to it applies its new filters.
    - Actual: Global bookmark still displays the old name. Clicking it applies the old filters.
4. Edit the same bookmark again:  Click `⋮ > Edit Global Bookmark` again
    - (this directs you to the same `/admin/settings/presets/{id}` URL again)
    - Expected: Bookmark form fields are filled in with the new name and filters.
    - Actual: Bookmark form fields are filled in with the old name and filters, as though nothing was edited.

In both cases, waiting several minutes until viewing Content and editing the bookmark again yields the expected behavior.

### Directus Version

10.9.3

### Hosting Strategy

Directus Cloud

**Comment by rijkvanzanten** [comment]
> We're also only observing this bug in Directus Cloud, but not locally (further hinting towards this being cache related).

Interesting! When testing locally, did you rely on Redis for caching or just memory? Also were you testing it with a load-balanced setup? (Eg multiple processes/containers)

No worries if not, just trying to pinpoint this a bit more 🙂

**Comment by echocrow** [comment]
> Interesting! When testing locally, did you rely on Redis for caching or just memory?

Running super bare-bone locally:
- close to the OOTB Directus env config (including `CACHE_STORE=memory`)
- no load-balancing or anything fancy

(TBH, not even Docker; just a straight `directus start` 😅)

**Comment by rijkvanzanten** [comment]
Thanks for the heads up! That makes me think the problem here might be a cache-state invalidation between processes or containers in a load balanced environment 🤔

**Comment by licitdev** [comment]
This behaviour should be fixed in `10.10` via https://github.com/directus/directus/pull/21702.
Kindly revert if this issue still persists. Thank you!
