### ISSUE TITLE
Can't select any option for the "is one of" filter

### ISSUE THREAD

**Issue by nskartoredjo** [directus/directus#21816]
### Describe the Bug

If you use the 'is one of' filter on a collection with an option field available, you won't be able to select any of the provided options. You can manually add the option yourself (for instance if you use a panel inside a dashboard) which indicates that the query is still working as intended. Providing an empty array will result into a `bad request`.

I couldn't find a relatable issue to see if this already got resolved in later releases, but I might be mistaken.

#### Small side note

This issue got notices because it broke a dashboard. For me this raises the question: if one panel fails to load it's required data, why would this error propagate to the whole dashboard? I would kinda expect that the each panel fails/succeeds independent of one another.

### To Reproduce

To reproduce the bug, you need perform the following steps:

- Create a new collection
- Create a dropdown field `x` and provide some placeholder options
- Fill your collection with some random data
- Now, use the `is one of` filter on said collection for field `x`
- Select one of the provided placeholder options
- Observe that the filter doesn't use any of selected options

https://github.com/directus/directus/assets/5946359/d1cbed2f-f368-4320-a154-10e9b1784b40

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
https://github.com/directus/directus/assets/4376726/0506c79c-6941-42f1-99f0-0e4f1ef37435



We haven't been able to reproduce this in version 10.10.7 based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻
