### ISSUE TITLE
[Login] Retrieve a temporary access token Graphql Update to 10.10.3

### ISSUE THREAD

**Issue by javargasm** [directus/directus#21820]
### Describe the Bug

I updated from Directus 10.10.0 to 10.10.3 and the login started failing

`mutation Login($email: String!, $password: String!) {
  auth_login(email: $email, password: $password) {
    access_token
    refresh_token
    expires
  }
}
`
console message:

 "type": "GraphQLError",
"message": "Schema is not configured to execute mutation operation.",
"stack":
GraphQLError: Schema is not configured to execute mutation operation.
at executeOperation (/directus/node_modules/.pnpm/graphql@16.8.1/node_modules/graphql/execution/execute.js:325:11)

### To Reproduce

call POST /graphql/system

### Directus Version

v10.10.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by javargasm** [comment]
I downgraded to version 10.10.2 and it works fine

**Comment by rijkvanzanten** [comment]
Thanks for the heads up! Gut feeling says this is the graphql schema caching getting confused between the system and non-system endpoints. PR incoming
