### ISSUE TITLE
Add support to authenticate a WebSocket through the session cookie

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#21825]
### Describe the Improvement

When relying on the new `session` mode for authentication, you can't re-use the already authenticated user for WebSocket connections. This in turn means you either have to re-authenticate the user on the socket, or fallback to the previous less-secure `cookie` auth mode to be able to get the access token

**Comment by g-pichler** [comment]
Noticing that the pull request mentions that 

> There is no way to include cross domain cookies when opening a websocket

I wonder: Would this solution also work in the (probably quite common) scenario where Directus is at, e.g., `https://directus.example.com` and some page at `https://www.example.com` is opening a websocket to `wss://directus.example.com/websocket`?

**Comment by br41nslug** [comment]
> I wonder: Would this solution also work in the (probably quite common) scenario where Directus is at, e.g., https://directus.example.com and some page at https://www.example.com is opening a websocket to wss://directus.example.com/websocket?

That should work if the cookie is set on the root domain `example.com` and `sameSite` is set to `lax` or `none`.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#define_where_cookies_are_sent
