### ISSUE TITLE
readMe function from SDK is missing types

### ISSUE THREAD

**Issue by thijserven** [directus/directus#21829]
### Describe the Bug

When fetching the currently authenticated user with the `readMe()` function from the Directus SDK (v15.0.3). I'm getting incorrect type hinting when trying to select nested fields with the `fields` parameter. 

For some reason `theme_light_overrides` and `theme_dark_overrides` are the only fields from `directus_user` showing up as valid options:

![Screenshot 2024-03-12 at 22 49 21](https://github.com/directus/directus/assets/51750966/6f75efce-4b1e-4802-b83f-d35f91219ac0)

But when finding users with the `readItems('directus_users')` function, the other nested fields of `directus_user` do show up as expected:

![Screenshot 2024-03-12 at 22 53 03](https://github.com/directus/directus/assets/51750966/1d404d65-559d-43fc-9be6-1249444f6824)

### To Reproduce

```ts
// Simplified versions of the collection types generated by [directus-extension-models](https://github.com/ChappIO/directus-extension-models)
interface DirectusFile {
    charset: string | null;
}
interface DirectusUser {
    email: string | null;
    avatar: DirectusFile | string | null;
}
interface Collections {
    directus_users: DirectusUser[]
}

const directus = createDirectus<Collections>(url, options).with(authentication("json", { credentials: "include" })).with(rest());

const response = await directus.request(readMe({fields: [{avatar: ['*']}]})) // Typescript error

const response = await directus.request(readItems('directus_users', {fields: [{avatar: ['*']}]})) // No typescript error
```

### Directus Version

v10.9.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Looks like the generated types are incorrect (or rather not fully compatible with the SDK), adding custom fields to a core collection follows this structure:
```ts
interface MySchema {
	// regular collections are array types
	collection_a: CollectionA[];
	// singleton collections are singular types
	collection_c: CollectionC;
	// extend the provided DirectusUser type 
	directus_users: CustomUser; 
}

interface CustomUser { 
	custom_field: string; 
} 
```
https://docs.directus.io/guides/sdk/types.html#custom-fields-on-core-collections

If you're not adding custom fields you don't need to provide types for the core collections as they are shipped with the SDK.

The SDK is an abstraction over the API so you cannot use `readItems` to call `directus_*` core collections (which would result in an invalid `/items/directus_users` call).

**Comment by thijserven** [comment]
@br41nslug Thanks for the response and explanation! When I create a new directus instance using the schema you provided in your example Typescript doesn't complain anymore. But I get no type completion for available relational fields. Is this intentional?

So `fields: ['']` gives me all available options:

![Screenshot 2024-03-14 at 22 39 27](https://github.com/directus/directus/assets/51750966/1e3693ae-af65-4ae3-a437-4fd40ba84b5d)

But `fields: [{''}]` gives me no options for relational fields:

![Screenshot 2024-03-14 at 22 39 36](https://github.com/directus/directus/assets/51750966/2870a838-7fe6-4547-86fe-d33ede832ee8)

It would be nice if `fields: [{''}]` would also return a list with valid options (like avatar or CustomUser as per your example). Just like `fields: ['']` does for non-relational fields.

Code snippet used (in case I did something wrong):
```js
import {
    createDirectus,
    rest,
    readMe,
} from "@directus/sdk";

interface MySchema {
    // extend the provided DirectusUser type 
    directus_users: CustomUser; 
}

interface CustomUser { 
    custom_field: string; 
}

const directus = createDirectus<MySchema>('url').with(rest());

await directus.request(readMe({
    fields: [{'avatar': ['*']}] // No ts error anymore
}))
```

**Comment by br41nslug** [comment]
Thats a known bug mentioned in the docs link shared above
![image](https://github.com/directus/directus/assets/9389634/04a6a0ef-bc89-4b16-b87d-d3c0d69f6449)

https://github.com/directus/directus/issues/19815
