### ISSUE TITLE
Auth mode Cookie doesn't work for SSO

### ISSUE THREAD

**Issue by keesvanbemmel** [directus/directus#21834]
### Describe the Bug

I had a SSO provider that worked fine until the upgrade to 10.10.x

After upgrading it also works fine with the default session authentication mode.

However, some external applications that make use of this seamless sso don't support session mode yet, so I wanted to change it to cookie mode, given this documentation: https://docs.directus.io/self-hosted/sso.html#seamless-sso

I added these to my (working) sso env variables:
```
AUTH_<PROVIDER>_MODE="cookie"
REFRESH_TOKEN_COOKIE_DOMAIN="api.fivespark.dev"
REFRESH_TOKEN_COOKIE_SECURE="true"
REFRESH_TOKEN_COOKIE_SAME_SITE="None"
```

But this results in the Directus app not working with SSO anymore. Logging in results in a redirect to the login screen.

### To Reproduce

- Set up a working openid SSO
- Change it to cookie mode
- Try to login in the directus app

### Directus Version

10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
The app uses `session` based authentication as of 10.10 https://docs.directus.io/releases/breaking-changes.html#session-cookie-based-authentication

**Comment by keesvanbemmel** [comment]
You are right. However that doesn't answer my initial required behavior: my external app needs cookie based auth on the same SSO provider... How can I arrange this then?

**Comment by br41nslug** [comment]
You will either need to:
- update the external app for session tokens
- downgrade directus < 10.10
- run 2 sso configurations one for session and one for cookie tokens

**Comment by keesvanbemmel** [comment]
And with the last option, is it possible to hide one configuration from the Directus app?

**Comment by paescuj** [comment]
> And with the last option, is it possible to hide one configuration from the Directus app?

Nope, I think we should add one 👍
