### ISSUE TITLE
Detail group field resets fields

### ISSUE THREAD

**Issue by jeffersonsolorzano** [directus/directus#21830]
### Describe the Bug

Hi, when i try to create a group of fields for a given collection, it always resets fields positions after check collection schema again

https://github.com/directus/directus/assets/5363448/90d6e328-a1bd-4239-9c23-9065eaa6b763

### To Reproduce

- Create a detail group field
- Insert already created fields inside this group
- Go check records related to this collection
- Go back to collection settings
- Wait a few secords if neccesary

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
I haven't been able to reproduce this locally based on the steps given, so I'll have to close this for now. Happy to reopen and keep discussing when more information becomes available.

What database vendor are you using? Are you using Redis for caching?
