### ISSUE TITLE
M2A item selction

### ISSUE THREAD

**Issue by FutureBuddha** [directus/directus#21848]
### Describe the Bug

in the Relationship setting of a M2A field i can only deselect one collection if i add other before. Also it add them multiply times to the Relation Collection.
![image](https://github.com/directus/directus/assets/149382049/bfb02161-f6c5-41fe-88db-227524bac235)

### To Reproduce

just create a M2A field and test out to add and remove the Related Collections

### Directus Version

v10.10.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by FutureBuddha** [comment]
I updated to the newest version 10.10.5 and it is still the same behavior. The same issue it is not fixed! Please check again!
![image](https://github.com/directus/directus/assets/149382049/3457933e-8e86-4eb3-9882-f03d4c61c927)
![image](https://github.com/directus/directus/assets/149382049/35585739-2eea-4582-ad38-3f08a07eb127)

**Comment by paescuj** [comment]
> I updated to the newest version 10.10.5 and it is still the same behavior. The same issue it is not fixed! Please check again! ![image](https://private-user-images.githubusercontent.com/149382049/324726820-3457933e-8e86-4eb3-9882-f03d4c61c927.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NTc3MzMsIm5iZiI6MTcxMzg1NzQzMywicGF0aCI6Ii8xNDkzODIwNDkvMzI0NzI2ODIwLTM0NTc5MzNlLThlODYtNGViMy05ODgyLWYwM2Q0YzYxYzkyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QwNzMwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTI3NDI5NWQ5YzA5MzhmYTBjYjY3OGUzODA1YWY1ZjI1MmNlYzBkZTAxYmU2ZjFhMWQ5YTFhMGQwMTE0OTg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4oAuGK7TjQqa0UF1zBaWAJoslW0-F7o5g1UsjwmGrLs) ![image](https://private-user-images.githubusercontent.com/149382049/324726982-35585739-2eea-4582-ad38-3f08a07eb127.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NTc3MzMsIm5iZiI6MTcxMzg1NzQzMywicGF0aCI6Ii8xNDkzODIwNDkvMzI0NzI2OTgyLTM1NTg1NzM5LTJlZWEtNDU4Mi1hZDM4LTNmMDhhMDdlYjEyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QwNzMwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjkzODBiZDNmZTZiZWVlNjM4YjliM2JiY2RhODdlYmZmODA2NWYxMzE1Mzk1ZDEwODVhZTUzZDJiN2UwNTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dPho7goU0DiOVCK6GjkcUm9s5jSkv4LMc1lcHyrVz9o)

The fix has been released in 10.10.6.

**Comment by FutureBuddha** [comment]
ok my fault i saw it wrong
