### ISSUE TITLE
Unable to find column after sort by ALIAS field

### ISSUE THREAD

**Issue by RadioSchattenwelt** [directus/directus#2184]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus version and branch (Or commit hash): 6.4.9 downloaded from release page
  - PHP version: 5.6.33
  - MySQL version: ?
  - Web server: (Ex. Apache, nginx or IIS?) ?
  - OS name and version: ?

## Expected Behavior
You should be able to sort the items in the table view by each column you like.

## Actual Behavior
If you try to sort the table entries by a ALIAS field from m2m relation you get the error "unable to find column X". From this moment on you are unable to access the table.

## Steps to Reproduce
 1. Create a table with m2m relationship
 2. Try to sort the table view by the m2m ALIAS field

## Schema Dump, Logs, or Screenshots
![image](https://user-images.githubusercontent.com/14234451/42999837-8cd49b72-8c1f-11e8-933b-709948be7078.png)
![image](https://user-images.githubusercontent.com/14234451/42999853-9ee99024-8c1f-11e8-887d-22b7ef7195e8.png)

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/68)
