### ISSUE TITLE
Error on installation with charset & mysqli query

### ISSUE THREAD

**Issue by fishtankmike** [directus/directus#2185]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus version and branch (Or commit hash): #2181
  - PHP version: 7.1.14
  - MySQL version: 5.1.73
  - Web server: Apache
  - OS name and version: 

## Expected Behavior
Complete the install in browser.

## Actual Behavior
At step 4 i get two errors:

- mysqli::set_charset(): Error executing query
- Could not set charset utf8mb4

It tells me run composer install (already done)

## Steps to Reproduce
 1. Ran the 3 SSH comand lines from the website to install on subdomain - https://getdirectus.com/pricing
 2. ran install in the browser
 3. errors at stage 4

## Schema Dump, Logs, or Screenshots
![screen shot 2018-07-20 at 13 34 44](https://user-images.githubusercontent.com/33543845/43002720-b2759cd0-8c21-11e8-9edd-c7210dbdc9af.png)

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/69)
