### ISSUE TITLE
File uploads in chunks

### ISSUE THREAD

**Issue by Nerglej** [directus/directus#21852]
### Describe the Improvement

When files are uploaded to the File Library, there really only is a limit in the form of MAX_PAYLOAD_SIZE, in Directus, right until you serve Directus from a cloud provider. Currently we're using Google Cloud Run, and they've got a max payload size of 32m, and this is not something that you can change.

I found an old locked Feature Request that #12937 that didn't describe much, but asked for the same feature, though with Cloudflare as a provider, which also has a payload size limit of 32m, which supports the general idea of sending bigger files in chunks, no matter what provider you use.

I put this in the 'Tiny weak' category, but I must admit that I don't know how much this involves. I would gladly work on the feature, but my company that I work for isn't really interested in me spending my time and their money on that, so this is purely a request, without the detail. I'm sorry if I miscategorized it.

Other than that, have a nice day!

**Comment by br41nslug** [comment]
Directus uses `multipart/form-data` for uploading which is chunked by nature and should be able to bypass the limit for single requests.

**Comment by Nerglej** [comment]
Hello!
I'm using the Directus App. As soon as I hit 32 megabytes for an image, it throws an error from my Google Cloud Run hosted service.
But yes, I would think you're correct, since the name implies that it's multipart😅

I'll look into it again tomorrow when I'm back at work again, but thanks for the reply, I really appreciate it😄

**Comment by rijkvanzanten** [comment]
@br41nslug I believe the 32mb limit might just be for the whole http request. The multipart body is multiple-parts in one request. In this case, it's a hard limit of the service unless we implement some sort of semi-proprietary way of handling single-file-as-multiple-requests uploads, like https://tus.io/

**Comment by br41nslug** [comment]
Ah that would explain it, wasnt 100% sure so left it open 😄

**Comment by rijkvanzanten** [comment]
> I found an old locked Feature Request that https://github.com/directus/directus/discussions/12937 that didn't describe much, but asked for the same feature, though with Cloudflare as a provider, which also has a payload size limit of 32m, which supports the general idea of sending bigger files in chunks, no matter what provider you use.

For cloudflare use specifically, the max upload size is tied to what "plan" you're on (eg more $$ is more upload size). For Cloud Run, it looks like it's a hard limit. Very unfortunate!

Implementing Tus or something similar is a way to upload a single large file through multiple smaller requests, but that's definitely not a tiny tweak.. I'll happily take a feature requests detailing how that could / should / would work in these different hosting providers, but for now I'll have to close this as a tweak 👍🏻
