### ISSUE TITLE
created user column not saving in O2M editor

### ISSUE THREAD

**Issue by heho** [directus/directus#2187]
We manage our posts in channels where we collect the in a O2M relation.

## Version Info
  - Directus version and branch (Or commit hash): directus-build
  - PHP version: 7.2.6
  - MySQL version: 10.1.33-MariaDB
  - Web server: Apache
  - OS name and version: Windows 7

## Expected Behavior
When editing a post from a channel and saving it a created user(we named it author) is the user that created it

## Actual Behavior
it is NULL however the internal created by and modified values by seem to be intact

## Steps to Reproduce
 1. Create a table B with a column "user created" and a column for table B id
 2. Create a table A with a M2O to table B
 3. create a new row 1 in table A
 4. from row create a new row 2 in table B and save it
 5. save row 2, save row 1

![](https://puu.sh/B35rF/67d045f405.png)
![](http://puu.sh/B35tT/9475257978.png)

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/71)
