### ISSUE TITLE
Firebase / Supabase as Authentication Provider for Directus. 

### ISSUE THREAD

**Issue by anandfursule** [directus/directus#21882]
@reev-create mentioned that they achieved it but I cannot seem to figure it out or make it work. Any chance somebody figured it out without messing up with the actual codebase of Directus?

If possible @reev-create could you share it with us?

Yes, I managed to get endpoints work for us to make Firebase as an authentication provider. If you want I could share it with you.

_Originally posted by @reev-create in https://github.com/directus/directus/discussions/4635#discussioncomment-3708070_

**Comment by br41nslug** [comment]
Firebase and Supabase are not officially supported as authentication providers at this time. Feel free to create a [feature request](https://github.com/directus/directus/discussions/new?category=feature-requests) instead 😄

**Comment by anandfursule** [comment]
Could any of these be used as SSO or OAuth?

**Comment by br41nslug** [comment]
Sure if they provide standard oauth2, openid or saml SSO authentication that should work.
