### ISSUE TITLE
wysiwyg editor can't set different format (p, H1, H2)

### ISSUE THREAD

**Issue by RamaHerbin** [directus/directus#21883]
### Describe the Bug

Hi there,
I can't manage to put an h1 title with a simple paragraph p.  
There's only one type of format authorised per instance of wysiwyg, which isn't really practical.

How can I stop this behavior ?

https://github.com/directus/directus/assets/41597427/3bc3e086-c407-4fed-b6ce-5f828eb1f817

In advance thank you for your help

### To Reproduce

Create a wysiwyg

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
I have not been able to reproduce this, please provide enough details to reproduce the issue:
- what browser are you using?
- what kind of relation are you using?
- any settings on the wysiwyg or other related configuration?

https://github.com/directus/directus/assets/9389634/790f363e-eb14-4269-a452-dc7805a2d51b

**Comment by rijkvanzanten** [comment]
There's not enough information available for us to reproduce. I'll close this for now but happy to reopen if more information becomes available.

**Comment by RamaHerbin** [comment]
thank you for your prompt replies

@br41nslug 
what browser are you using? 
Chrome v122

what kind of relation are you using?
Builder M2A

are you seeing the same when directly editing/creating a "Article Text"?
No I don't have the problem when I'm editing an object of the collection.
It's also working great when I'm setting custom format
