### ISSUE TITLE
Allow to disable update checks

### ISSUE THREAD

**Issue by stafyniaksacha** [directus/directus#21884]
### Describe the Request

On each start of direcus cli, checks for updates are made, we should let users to disable it.

### Maintainence Strategy

An env variable should be enought to disable it, while keeping on by default to not change behaviour

**Comment by rijkvanzanten** [comment]
Why do you need to disable it?

**Comment by stafyniaksacha** [comment]
> Why do you need to disable it?

We may want to start directus on an offline network without waiting for timeout, also if directus constantly restart it won't flood logs. It also gains extra milliseconds at startup

**Comment by rijkvanzanten** [comment]
It's an important bit of information we're not currently surfacing elsewhere in the platform, so I'd rather not make it optional here. I'm down to discuss alternatives like surfacing that information to admins in the app, but until we do, I'd rather keep it in the cli for everybody 👍🏻
