### ISSUE TITLE
All items in "files" are requested (even if they aren't on the viewport yet) can result in a too many requests error

### ISSUE THREAD

**Issue by VincentKempers** [directus/directus#21893]
### Describe the Bug

Locally this is kind of hard to debug but It's possible to see the requests here.
When having a collection which contains a "files" field. Having this full of images.

When visiting this collection for the first time it will result in a lot of requests at the same time.
![blurredout](https://github.com/directus/directus/assets/14160793/c6ce83e8-718e-42e3-840a-a4959a80785f)

This can reproduced if you have it hosted somewhere or we also see this happen on cloud.
-------

@rijkvanzanten Noticed that we removed the v-image and used the regular img tag.
Which removed the throttling of the images (and in the images of this case). 
Which we removed in this PR: https://github.com/directus/directus/pull/21239

### To Reproduce

To reproduce. Have a lot of images in the files field in a collection. Visit that collection and you will notice a spike of requests even though they aren't loaded in. 

These result in 429 errors:
```
{
  "errors": [
    {
      "message": "Too many requests, retry after 73ms.",
      "extensions": {
        "code": "REQUESTS_EXCEEDED",
        "limit": 50,
        "reset": "2024-03-18T15:38:03.234Z"
      }
    }
  ]
}
```

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by joselcvarela** [comment]
@VincentKempers you have mentioned this same issue on "Which we removed in this PR: https://github.com/directus/directus/issues/21893" 😅

Just want to add that this may cause project to crash due to all the transformations it does when viewing file library, either on Files module or within a drawer relationship

**Comment by rijkvanzanten** [comment]
Correct PR link should be https://github.com/directus/directus/pull/21239 I think

**Comment by VincentKempers** [comment]
@joselcvarela Updated, my bad
