### ISSUE TITLE
Postgress 16: permission denied for schema public

### ISSUE THREAD

**Issue by AAverin** [directus/directus#21890]
### Describe the Bug

Running postgress 16, with a clean database setup, I am getting an error `permission denied for schema public`.
There have been some changes in Postgress 15 regarding permissions handling.
Is Postgess 15+ supported by Directus?
Any specific setup required?

### To Reproduce

Run directus against newly created postgress 16

### Directus Version

latest

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Im unable to reproduce this I've just tested a new postgres 16 database and it works without issue out of the box.
![Docker_Desktop_IBiTQkDgnz](https://github.com/directus/directus/assets/9389634/c3f32377-56b0-4277-98aa-5855f3e7e871)

**Comment by AAverin** [comment]
@br41nslug I am using a managed postgress provided by digital ocean, setup can be different from your local container.
Are there any defaults that are adjusted? Which user is used for the connection?

**Comment by br41nslug** [comment]
I am using the defaults (except user/pass ofc) i cannot say what settings DO sets for you.

**Comment by AAverin** [comment]
@br41nslug on DO I create a new user to use for directus. 
Here is some info regarding changes to user permissions management in Postgress 15.

https://www.percona.com/blog/public-schema-security-upgrade-in-postgresql-15/#:~:text=In%20Postgres%2015%2C%20now%20new,Postgres%2014%20and%20previous%20versions.

**Comment by br41nslug** [comment]
Make sure your new user has the correct permissions to write to the public schema, example included in the link you've shared.

**Comment by AAverin** [comment]
@br41nslug maybe anything regarding that needs to be added to the directus documentation and setup for postgress 15 and higher?

**Comment by br41nslug** [comment]
Because issue seems to be specific to the digital ocean provider configuration not to the postgres 15/16 database itself I dont see what we should add to the docs. If extra configuration was needed out of the box I'd agree but we do not manage cloud provider specific guides.
