### ISSUE TITLE
Error : calendar_has_malformed_options_json

### ISSUE THREAD

**Issue by kangfarih** [directus/directus#2190]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus version and branch (Or commit hash): 6.4.9
  - PHP version: 7.2.4
  - MySQL version:  5.0.12
  - Web server: Apache
  - OS name and version: Win 10

## Actual Behavior
**Error message**
directus.min.js?bust=0t0i7322hn2etbf7821qj6f1bv:23 
calendar_has_malformed_options_json

![image](https://user-images.githubusercontent.com/12198166/43671361-94f892dc-97c2-11e8-86c5-bb265fe90482.png)

## Steps to Reproduce
 1. Install Directus
 2. Add table
 3. Add items

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/73)
