### ISSUE TITLE
API delay after creating item in directus gui

### ISSUE THREAD

**Issue by semorur** [directus/directus#21909]
### Describe the Bug

when I create a new item in Directus GUI, I don't see it immediately through API. Sometimes I need to wait for several minutes
also edited field in GUI not changing immediatelly.

I had a case when I created an item by API, it appeared in GUI immediatelly. But when I wanted to get all items though API, this newly created item was missing. It appeared after some time. I am worried about this delay. Sometimes it works well

### To Reproduce

1. create a new item in Directus GUI
2. try Postman for example to authenticate and GET /items/:collection
3. sometimes you can see added item, but sometimes you need to wait
4. update one of fields in one of items in Directus GUI
5. try GET /items/:collection, sometimes you don't see updates on any fields

after several minutes I get correct information

I had version v10.9.3, now I have updated to v10.10.4, but the problem remains

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Do you have caching enabled? In that case, please ensure to enable the `CACHE_AUTO_PURGE` [^1] option and additionally ensure there's no third-party cache between the instance and your client which could interfere.

I'll close this issue for now, under the assumption that it is related to the above option, but happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

[^1]: https://docs.directus.io/self-hosted/config-options.html#cache

**Comment by semorur** [comment]
Thank you very much!
It works!


best regards,
Sergey Morozov

**Comment by paescuj** [comment]
Great, thanks for your feedback!
