### ISSUE TITLE
user_created is overwritten during import by the user_id of the importer

### ISSUE THREAD

**Issue by Triggsy22** [directus/directus#21903]
### Describe the Bug

If you import a CSV File with the Directus-Import-Tool and you have _user_created_ set inside the import file, this value will be overwritten by the userId of the User that is importing the file.

### To Reproduce

0. Login with an Admin User.
1. Create a new collection and add the created_by field.
2. Create an entry to this collection.
3. Export the Items.

Example:
```
"id","user_created"
1,"5d7ea4af-48dc-4adc-8195-4a29d0abae2d"
```

5. Change the _user_created_ Id to another UserId that exists. And remove Id

Example:
```
"user_created"
"8562df77-8c72-4fcd-9805-96c029c476f1"
```

6. Import the Item.
7. The user_created is overwritten by the id of the user, that imports the item.

**Why this is a Problem?**
My Permissionsystem is based on user_created, to determine if an item belongs to a user.

### Directus Version

v10.9.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Triggsy22** [comment]
Thanks, that would be nice.
But if you let Directus create the user_created field as an _Optional Field_ on Collectioncreation, its not UUID, its string. 
So the On Create Action can not be changed.
Tested on Version 10.10.4

**Comment by br41nslug** [comment]
> But if you let Directus create the user_created field as an Optional Field on Collectioncreation, its not UUID, its string.
> And of course its a relation to the directus_user collection.

Not sure im following, i didnt suggest making it optional or switching away from `uuid`. It should stay a required relation of type `uuid` but simply without the trigger to always overwrite the uuid with the current user.

**Comment by Triggsy22** [comment]
I postet a Video above, to proof what im talking about.

If i create a normal input field, and set it to uuid, everything is right like you explained in your first post.
But the preconfigured user_created fields are not uuid, even in the database they are not. And so, the 'on Create Action' cannot be changed.

MariaDB supports UUID since Version 10.7
We are using 10.6.17
According to your documentation you support this, even if string is a fallback.

**directus_fields in the Database:**
![directus_fields](https://github.com/directus/directus/assets/33725296/5ce279e7-04aa-4487-a98e-f2823b5fb22a)

**manual created uuid, like expected**
![manual_uuid_user_created_field](https://github.com/directus/directus/assets/33725296/c11f672d-cb9b-4a88-90f8-587cf970e52e)

**predefined user_created. automatically created by directus on the creation of the collection.**
![predefined_user_created_field](https://github.com/directus/directus/assets/33725296/52c93965-3c02-4c16-8dc2-48ff35b4e13c)

**Comment by br41nslug** [comment]
The video only shows you creating a new collection and selecting preconfigured field, so it didnt add much, the actual screenshot of user_created helps. 

However as you mention yourself:
```
MariaDB supports UUID since Version 10.7
We are using 10.6.17
```
according to those number you've posted you're not on a version that supports uuid's so it would make sense the platform automatically falls back to string 🤔 

So my first suggestion is updating mariadb to a version after uuid support was added, still strange as the pre-defined fields are just that, pre-defined they should be identical to manually creating a user_created field.

**Comment by Triggsy22** [comment]
Yeah, im going to upgrade the DB.
My problem should be solved now.
Thanks :)

If its a bug or not, is your choice.
But if you not want to fix it, you should at lease change the minmal supported Maria DB Version to 10.7

**Comment by br41nslug** [comment]
I was going to make a new issue for this but found one already existed https://github.com/directus/directus/issues/21635

**Comment by Triggsy22** [comment]
Even after the MariaDb Update to 10.11.7 a new created uuid field is converted to char(36) in the database.
It doesnt matter if the field is created manually as uuid or is an automatically created user_created field.

**Manually created UUID Field in Directus**
![image](https://github.com/directus/directus/assets/33725296/0eca195b-8e28-4e56-a144-889fc4b1b6a7)


**Automatically created user_created field on table creation**
![image](https://github.com/directus/directus/assets/33725296/d2544f50-0af5-40e5-ac67-0a4545dc4837)


**Column in the Database**
![image](https://github.com/directus/directus/assets/33725296/e3224bcb-84ae-44b5-b48d-ba84b5b0c3b6)


**Row in directus_fields in the Database**
![image](https://github.com/directus/directus/assets/33725296/e408bc98-9cb9-474b-9c8f-9604d4bf972a)
![image](https://github.com/directus/directus/assets/33725296/bcfb4368-3928-4aa2-924c-edeb4fb9c406)


So, the Database Update didnt solve the Problem at all.

**Comment by paescuj** [comment]
The oddity with the UUID special type is tracked in #21635.
