### ISSUE TITLE
Add topic 'mariadb' to GitHub repository

### ISSUE THREAD

**Issue by ottok** [directus/directus#21900]
### Describe the Improvement

Hi! Directus docs state clearly that is supports MariaDB. Could you please also add the topic 'mariadb' in the project, so people looking for MariaDB tools on GitHub are more likely to find it?

![image](https://github.com/directus/directus/assets/668724/f3a6a0e7-278d-4841-a0c4-e23f98f1346c)

The [popularity of MySQL is slowly declining](https://salsa.debian.org/mariadb-team/mariadb-server/-/wikis/Home#popularity) so it would be good for Dolt to ensure MariaDB users can easily find it.

**Comment by rijkvanzanten** [comment]
Ty for the suggestion :)
