### ISSUE TITLE
[UI] Logical operator OR always produces AND request

### ISSUE THREAD

**Issue by blex41** [directus/directus#21919]
### Describe the Bug

The UI allows to filter items using an AND or OR logical operator. Here is an example using OR, to only keep items which either don't have an expiration date or have one set in the future:  

<img width="408" alt="image" src="https://github.com/directus/directus/assets/8618076/60f8bc22-f7ed-4ab9-bf7c-d709a2819e7d">

However, no matter if I select AND or OR, the UI always makes a request to the backend using `_and`, which returns no result, in my case. This is the request being made:

```
https://our-directus-instance.com/items/articles?filter[_and][1][expiration_date][_null]=true&filter[_and][2][expiration_date][_gt]=$NOW&aggregate[countDistinct][0]=id
```

### To Reproduce

Try to filter items using an OR logical operator on a given field. Look at the resulting request in the Network tab of your browser devtools.

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Dont forget to nest your filters under the `OR` anything on the top level will default to `AND`.

![image](https://github.com/directus/directus/assets/9389634/1c5a64e7-6c6c-4ea5-ad70-972749eb3c0c)

**Comment by blex41** [comment]
Aw, thank you! I did try to nest them before posting this issue, but without success, I must not have drag'n'dropped them properly. It works now, when I do
