### ISSUE TITLE
New extensions in bundle aren't reloaded in development mode

### ISSUE THREAD

**Issue by ChappIO** [directus/directus#21922]
### Describe the Bug

Whenever I edit my extension's package.json while developing, directus does not reload it. Even een reboot does not solve my issue. I have to drop my database and rebootstrap.

### To Reproduce

1. Create a directus extension folder in `extension/demo` with the "bundle" type.
2. Add a hooks extension to the bundle called "hooks1"
3. Bootstrap and run directus with `EXTENSIONS_AUTO_RELOAD=true`
4. Add another hooks extension to the bundle called "hooks2"
5. The demo/hooks2 extension is not loaded
6. Restart directus
7. The demo/hooks2 extention is not loaded
8. Drop database and rebootstrap
9. The demo/hooks2 extension is loaded

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Custom)

**Comment by ChappIO** [comment]
We (very) briefly discussed this in Discord: https://discord.com/channels/725371605378924594/1145983898644389908/1217565350594609213

**Comment by br41nslug** [comment]
Are you rebuilding the bundle extension after changes? I dont see that crucial step in the reproduction steps.

**Comment by ChappIO** [comment]
> Are you rebuilding the bundle extension after changes? I dont see that crucial step in the reproduction steps.

Yes, fair enough. My extension is running in watch mode. And the Directus logs even show "Extensions reloaded" when I restart the directus sdk. The `dist` folder also contains the sources for my new hook. But http://localhost:8055/admin/settings/extensions doesn't show my new extension.

**Comment by ChappIO** [comment]
No idea if it helps but I just removed all records from `directus_extensions` and restarted directus. That was sufficient to trigger a rescan.
