### ISSUE TITLE
Broken links on the support page

### ISSUE THREAD

**Issue by br41nslug** [directus/directus#21923]
### Describe the Request

When trying to share our default "no estimated timelines" message i noticed some of the links used no longer exist on the [Support Page](https://docs.directus.io/getting-started/support.html)

Broken links:
1. "Reporting a Bug"(https://docs.directus.io/contributing/introduction#bug-reporting) should link to "https://docs.directus.io/contributing/introduction.html#report-a-bug" (occurs twice in the "troubleshooting steps")
2. "80/20 Rule"(https://docs.directus.io/contributing/introduction#feature-requests) not sure if this link is intended, I'd expect this link to go to a place explaining the "80/20 rule" which itself is not mentioned on the page the link takes you to
3. "Sponsoring Expedited Fixes"(https://docs.directus.io/getting-started/support.html#expedited-fixes) non-existent link (twice on the page)
4. "Commissioning New Features"(https://docs.directus.io/getting-started/support.html#commissioned-features) non-existent link (twice on the page)

![image](https://github.com/directus/directus/assets/9389634/8a638b19-9b6f-4993-95c6-2a996d2fc38a)

### Maintainence Strategy

Perhaps we can automatically check for non-existent URL in the docs (specifically non-existent hash links which do not return a 404).

**Comment by rijkvanzanten** [comment]
Closed in #22995
