### ISSUE TITLE
Resizing image makes it transparent

### ISSUE THREAD

**Issue by honzapatCZ** [directus/directus#21920]
### Describe the Bug

Images that get resized will be transparent. This issue seems to only occur for images that are higher or wider than 1000pixels.

Incorrect:
![image](https://github.com/directus/directus/assets/26117393/2c8efcd2-489f-40d0-8803-b5bd476a3c37)

Correct(not necesarrily size-wise):
![image](https://github.com/directus/directus/assets/26117393/693ca98b-c2de-45bb-a046-eb4f3bb5df58)

### To Reproduce

I've uploaded a png image with 1024x1024 size. 

### Directus Version

10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

Please ensure you're on the latest version (currently [v10.10.4](https://github.com/directus/directus/releases/tag/v10.10.4)). is still present after the update, please submit more information (where does the issue occur, what are your settings, ...). Thank you!

**Comment by honzapatCZ** [comment]
Just for anyone wondering, this was probably local to 10.8.3 as the latest(currently 10.10.4) doesn't have the issue.

**Comment by paescuj** [comment]
Thanks for your feedback!
