### ISSUE TITLE
Document `AUTH_<PROVIDER>_ALLOW_PUBLIC_REGISTRATION` for public sso user registration

### ISSUE THREAD

**Issue by j0weiss** [directus/directus#21936]
### Page

https://docs.directus.io/self-hosted/config-options.html#sso-oauth2-and-openid

### Describe the Inaccuracy

When I was trying to setup authentication via OpenID with Keycloak (and later on with GitHub) I couldn't get it to work with the provided example configuration:

Here ist the example from the docs for GitHub:
```
AUTH_PROVIDERS="github"

AUTH_GITHUB_DRIVER="oauth2"
AUTH_GITHUB_CLIENT_ID="99d3...c3c4"
AUTH_GITHUB_CLIENT_SECRET="34ae...f963"
AUTH_GITHUB_AUTHORIZE_URL="https://github.com/login/oauth/authorize"
AUTH_GITHUB_ACCESS_URL="https://github.com/login/oauth/access_token"
AUTH_GITHUB_PROFILE_URL="https://api.github.com/user"
```

I always ended up with an error, saying "Invalid username or password". It was a fresh setup, so no users where present in the Directus DB. Only after I set
```
AUTH_<PROVIDER>_ALLOW_PUBLIC_REGISTRATION=true
```
I could sucessfully login with a new user. I found various articles/issues where this behaviour is documented, which helped me to narrow down the problem:
* https://learndirectus.com/how-to-add-sso-to-directus/
* https://github.com/directus/directus/discussions/10445
* https://www.restack.io/docs/directus-knowledge-directus-azure-sso-integration

While it makes sense, that users have to be created in some way or another within Directus, it is not clear from the docs, that without public registration set to `true`, SSO is somewhat useless. The idea of SSO is to not duplicate users in an application, at least not manually, so public registration needs to be `true` as far as I can see.

If I'm not overlooking something, I suggest to add the following line to the example above:
```
AUTH_GITHUB_ALLOW_PUBLIC_REGISTRATION=true
```
and also to the other SSO examples, which are documented here: https://docs.directus.io/self-hosted/sso-examples.html

Or adding a short paragraph explaining the fact, that public registration is needed for SSO to work out of the box without further handling of user creation within Directus itself.

I'm happy to help via a pull request.

**Comment by Jan0707** [comment]
Okay, I have been banging my head against this for _two_ days wondering what was wrong with my setup. And **THIS** was the solution. IMHO this needs to be added to the documentation ASAP.

Also worth mentioning that the error that pops up otherwise "invalid credentials" is not helpful, not at all.

Thank you very much @j0weiss !
