### ISSUE TITLE
Extensions: Adding a new entry to bundle does not update extensions list

### ISSUE THREAD

**Issue by joselcvarela** [directus/directus#21946]
### Describe the Bug

After adding a new entry to the bundle, in this case a display, this new entry does not appear on extensions list.
Although the entry is usable, at least the ones of type display.

### To Reproduce

- Create a folder
- Run `npx create-directus-extension@latest` and choose bundle
- Enter newly created folder
- Run `npm run add` and choose `display` with name "lorem"
- Copy files to extensions folder
- Run `npm run add` and choose `display` with name "ipsum"
- Go to Extensions and check that "ipsum" display does not appear there

### Directus Version

10.10.4 (main)

### Hosting Strategy

Self-Hosted (Custom)

**Comment by Zehir** [comment]
FIY the workaround until the fix get released is to remove each lignes inside the database (`directus_extensions`) for the bundle and each of bundle entries. And then restart Directus.

**Comment by NilsBaumgartner1994** [comment]
@Zehir any way to edit these lines/rows with the directus frontned?

**Comment by Zehir** [comment]
@NilsBaumgartner1994 No I don't think but the fix is already merge, the release should be out soonish I hope

**Comment by NilsBaumgartner1994** [comment]
FYI: I moved my extension outside the extension folder, started directus, removed the extension from the settings menu, removed the extension back in, restarted directus. This temporally fixed this issue.

The issue just occured when adding a new hook/panel/... but not when changing the source code.

Yeah lets hope for a quick release :-)
