### ISSUE TITLE
Wrong version shown in admin

### ISSUE THREAD

**Issue by Pachat** [directus/directus#21943]
### Describe the Bug

Just installed "version": "11.0.4",
but in admin it reads Directus 10.10.4

### To Reproduce

Create a project with CLI

### Directus Version

v11.0.4

### Hosting Strategy

Self-Hosted (Custom)

**Comment by ComfortablyCoding** [comment]
The latest release is indeed `10.10.4` see [releases](https://github.com/directus/directus/releases). I am not sure how an `11.0.4` version was installed, I would confirm the correct package was installed and confirm that it is indeed showing `11.0.4` for directus in the `package.json`. 

Due the reasons mentioned I am closing the issuefor now. Happy to open it up if new information is provided that requires investigation.

**Comment by Pachat** [comment]
Thank you for pointing my mistake.
It was based on `node_modules/@directus/app/package.json` content
```
{
  "name": "@directus/app",
  "version": "11.0.4",
  "description": "App dashboard for Directus",
  "homepage": "https://directus.io",
  "repository": {
    "type": "git",
    "url": "https://github.com/directus/directus.git",
    "directory": "app"
  },

```
which lead to the wrong interpretation.
