### ISSUE TITLE
Field gets empty when updating directly from alias (M2M) field

### ISSUE THREAD

**Issue by jasonmarysael** [directus/directus#2194]
## Version Info
  - Directus version and branch (Or commit hash): 6.4.9
  - PHP version: 7.0.30
  - MySQL version: Ver 14.14 Distrib 5.7.23
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version:  "Ubuntu" "16.04.3 LTS (Xenial Xerus)"

So I have a table named "Work categories" which contains an alias field (many-to-many) named "works". When I select one of the works directly from the "Work categories - works" column and try to update the content from an existing (wysiwyg full) field, the field gets empty. When adding a new item or try to update the item directly under the original "work" table I have no issues.

![directus](https://user-images.githubusercontent.com/28600053/44140890-c92afa74-a07b-11e8-8369-9fc54788d905.png)

**Comment by truefalse10** [comment]
i just figured out that if you click outside of the text area after editing (blur the input) and then hit the save button it gets updated correctly. If i click it directly i am getting the same error

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/74)
