### ISSUE TITLE
m2m/multiple files vs API

### ISSUE THREAD

**Issue by Muphet** [directus/directus#2195]
So i created "properties" table, something like real estate. I have  standard fields like title, description. There is also a relation/alias called "pictures" set as multiple files (m2m) as follows:
estates  junctionTable   relatedTables
  ID       ->    estate_id
                    photo_id <-    id

Now, when I visit my api (http://api.domykrosno.pl/api/1.1/tables/nieruchomosci/rows/) it does show my estates together with pictures (called "zdjecia").
The problem is, 7/10 tries api does not include photos at all. Now, even though it sometimes does show related images, when i fetch data using sdk, it still does not receive that part of data (only takes depth=1 of json, does not retrieve any deeper objects if that makes sense)

How am i supposed to fetch image info using REST call?

**Comment by Muphet** [comment]
yeah this is what concerns me.
when i visit endpoint, i sometimes see field `zdjecia` and sometimes not.
i noticed, that when i log in into cms, `zdjecia` field appears (except client doesn't see it regardless)

**Comment by rijkvanzanten** [comment]
I see it now without being authenticated. As soon as you log into the CMS, you're cookie will be send to the API as well. Therefore, when you're logged into the CMS, the "raw" API endpoints will return like you're logged in.

**Comment by Muphet** [comment]
issue can be closed as solved, i realised that i have to make directus directory "directus_files" as public (read rights to public user) in order to access data (or admin user).
