### ISSUE TITLE
SDK realtime client regression (14.0.0 -> 15.0.3) / websocket blocked / lost messages

### ISSUE THREAD

**Issue by zguig52** [directus/directus#21952]
### Describe the Bug

Hello,

After upgrading to latest version of the SDK, my realtime client doesn't behave properly anymore.

I followed the official guide on how to implement it.

It seems that first messages are lost and authentication message is not received by "onWebSocket" method anymore.

Authentication is properly received on Directus side but the event is not received on client application.

Dirty workaround is to force subscription even without having received the auth / ok message.

Reproduction code is given for you to quickly identify the issue.

### To Reproduce

Here is a repro code that can be used (we only miss a public test Directus instance for being able to give easy running repro code).

Works ("@directus/sdk": "14.0.0"):
https://stackblitz.com/edit/github-qytiun-slld9m?file=components%2FWebSocket.vue

Doesn't work ("@directus/sdk": "15.0.3"):
https://stackblitz.com/edit/github-qytiun-sesbl7?file=components%2FWebSocket.vue

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Please provided detailed and clear reproduction instructions, I have not been able to reproduce the issue as described on v15. The following code snippet works as expected
```ts
const client = createDirectus("http://localhost:8055")
  .with(staticToken('admin'))
  .with(realtime())

client.onWebSocket("message", (message) => console.log("[WS] Message", message));

const { subscription: a1 } = await client.subscribe("test_1", {
  query: { fields: ["*"] },
  uid: '1'
})

for await (const item of a1) {
  console.log('subscription1', { item });
}
```
![firefox_8Nxu6iF6AA](https://github.com/directus/directus/assets/9389634/0bc59136-ca0e-4832-b717-d9662dcb075b)


Closing this issue for now until more information becomes available.

**Comment by zguig52** [comment]
Hi @br41nslug,

Websocket is properly handled, the issue is linked to: client.onWebSocket('message'

I based my implementation on official directus doc from here:
https://docs.directus.io/guides/real-time/getting-started/websockets.html

Repro details are available here:
https://stackblitz.com/edit/github-qytiun-sesbl7?file=components%2FWebSocket.vue

Here some comments on the test code you have used:
```
const client = createDirectus("http://localhost:8055")
  .with(staticToken('admin'))
  .with(realtime())

// Here you will not see the auth message
client.onWebSocket("message", (message) => console.log("[WS] Message", message));

// Subscription shall be performed after the auth / ok message - here it is forced even if auth is KO
const { subscription: a1 } = await client.subscribe("test_1", {
  query: { fields: ["*"] },
  uid: '1'
})

for await (const item of a1) {
  console.log('subscription1', { item });
}
```

Official docs full example have an error. They call the subscribe function after auth as described. But the function is not defined here and they force the subscription like you did. Here the full code from the docs with comments also:
```
<!DOCTYPE html>
<html>
  <body>
    <script>
      import {
        createDirectus,
        staticToken,
        realtime,
      } from 'https://www.unpkg.com/@directus/sdk/dist/index.js';

      const url = 'wss://your-directus-url/websocket';
      const access_token = 'your-access-token';
      const collection = 'messages';

      const client = createDirectus(url)
        .with(staticToken(access_token))
        .with(realtime());

      await client.connect();

      client.onWebSocket('open', function () {
        console.log({ event: 'onopen' });
      });

      client.onWebSocket('message', function (message) {
        const { type, data } = message;
        if (message.type == 'auth' && message.status == 'ok') {
// HERE THE FUNCTION IS NOT DEFINED
          subscribe();
          console.log({ event: 'onmessage', data });
        }

      });

      client.onWebSocket('close', function () {
        console.log({ event: 'onclose' });
      });

      client.onWebSocket('error', function (error) {
        console.log({ event: 'onerror', error });
      });

// HERE THE SUBSCRIPTION IS FORCED NOT LIKE DESCRIBED IN THE ARTICLE
      const { subscription } = await client.subscribe(collection, {
        event: 'update',
        query: { fields: ['user', 'text'] },
      });

      for await (const item of subscription) {
        console.log(item);
      }

      function createItem(text, user) {
        client.sendMessage({
          type: 'items',
          collection: collection,
          action: 'create',
          data: { text, user },
        });
      }

      function readLatestItem() {
        client.sendMessage({
          type: 'items',
          collection: collection,
          action: 'read',
          query: { limit: 1, sort: '-date_created' },
        });
      }
    </script>
  </body>
</html>
```

Hereafter the full example corrected as should be:
```
      const url = 'wss://your-directus-url/websocket';
      const access_token = 'your-access-token';
      const collection = 'messages';

      const client = createDirectus(url)
        .with(staticToken(access_token))
        .with(realtime());

      await client.connect();

      client.onWebSocket('open', function () {
        console.log({ event: 'onopen' });
      });

      client.onWebSocket('message', function (message) {
        const { type, data } = message;
        if (message.type == 'auth' && message.status == 'ok') {
          subscribe();
          console.log({ event: 'onmessage', data });
        }

      });

      client.onWebSocket('close', function () {
        console.log({ event: 'onclose' });
      });

      client.onWebSocket('error', function (error) {
        console.log({ event: 'onerror', error });
      });

      // THIS IS REMOVED AND REPLACED BY THE SUBSCRIBE FUNCTION NEEDED AND SHOWN IN THE EXAMPLE / CREATE A SUBSCRIPTION
      // const { subscription } = await client.subscribe(collection, {
      //   event: 'update',
      //   query: { fields: ['user', 'text'] },
      // });
      async function subscribe() {
        const { subscription } = await client.subscribe('messages', {
          event: 'update',
          query: { fields: ['user', 'text'] },
        });

        for await (const item of subscription) {
          console.log(item);
        }
      }

      function createItem(text, user) {
        client.sendMessage({
          type: 'items',
          collection: collection,
          action: 'create',
          data: { text, user },
        });
      }

      function readLatestItem() {
        client.sendMessage({
          type: 'items',
          collection: collection,
          action: 'read',
          query: { limit: 1, sort: '-date_created' },
        });
      }
```

Hereafter the quick test code based on your minimal code:
```
const client = createDirectus("http://localhost:8055")
  .with(staticToken('admin'))
  .with(realtime())

 client.onWebSocket('message', function (message) {
    const { type, data } = message;
    if (message.type == 'auth' && message.status == 'ok') {
      subscribe();
      console.log({ event: 'onmessage', data });
    }
});

async function subscribe() {
  const { subscription } = await client.subscribe('messages', {
    event: 'update',
    query: { fields: ['user', 'text'] },
  });

  for await (const item of subscription) {
    console.log(item);
  }
}

```

Here some screenshots of v14 behaviour:
![image](https://github.com/directus/directus/assets/12774668/80f60c23-e267-4fdc-937b-1c1c6eb20c2b)

Here some screenshots of v15 behaviour:
![image](https://github.com/directus/directus/assets/12774668/d54e7027-ba12-40d1-9ecf-f9d0a063111a)

Websocket opening is working, this is the first messages that get lost (and then the subscribe process is not triggerred after successfull authentication).

If you dirty force the subscription as you did without waiting for auth success reply makes it work, but anyway, some messages are lost.

**Comment by br41nslug** [comment]
Tracking the issue here #21955 to keep the root issue clear and consise.

> I saw that you did not use the client.connect() method as described in docs.

Connect is not explicitly required if you're subscribing but its still good practice.
