### ISSUE TITLE
Error in creating update cookie when logging in with Google in production environments with different subdomains in Directus

### ISSUE THREAD

**Issue by CristianDev0160** [directus/directus#21958]
### Describe the Bug

When trying to sign in with Google, after selecting an account, the "directus_refresh_token" cookie that should be created is not generated correctly. Instead, a 302 error occurs in the server console. This issue specifically occurs when the domain specified in the Directus refresh_token_cookie_domain setting is different than the domain of the server hosting Directus. It appears that the cookie domain setting is causing this failure to create the refresh cookie, preventing the correct login flow.

### To Reproduce

1. Set up a Google sign-in system using Directus 10.9.3.
2. Use the following configuration variables for Google Single Sign-On (SSO) in Directus:

```plaintext
AUTH_PROVIDERS: "google"
AUTH_GOOGLE_DRIVER: "openid"
AUTH_GOOGLE_CLIENT_ID: "[Google Customer ID]"
AUTH_GOOGLE_CLIENT_SECRET: "[Google Client Secret]"
AUTH_GOOGLE_ISSUER_URL: "https://accounts.google.com/.well-known/openid-configuration"
AUTH_GOOGLE_IDENTIFIER_KEY: "email"
AUTH_GOOGLE_ICON: "google"
AUTH_GOOGLE_LABEL: "Google"
AUTH_GOOGLE_DEFAULT_ROLE_ID: "[Directus default role ID]"
AUTH_GOOGLE_ALLOW_PUBLIC_REGISTRATION: true
```

3. Configure the following variables related to Directus update cookies:

```plaintext
REFRESH_TOKEN_COOKIE_DOMAIN: "my-directus-app.domain.com"
REFRESH_TOKEN_COOKIE_SECURE: false
REFRESH_TOKEN_COOKIE_SAME_SITE: "lax"
```

4. Make sure your client application and Directus are on the same domain, but on different subdomains.
5. Sign in with Google using the following initial redirect:

```javascript
window.location.href = `https://my-directus-app.dominio.com/auth/login/google?redirect=https://my-next-app.dominio.com/auth/login/google/callback `;
```

6. You notice that after selecting a Google account, the "directus_refresh_token" cookie is not created correctly.
7. In the server console, a 302 error will appear, indicating a problem with the creation of the cookie.
8. This issue specifically occurs when the domain specified in the Directus `REFRESH_TOKEN_COOKIE_DOMAIN` setting is different than the domain of the server hosting Directus.

---

With these detailed steps, you will be able to reproduce the error and better understand the problem we are facing.

### Directus Version

v10.9.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by CristianDev0160** [comment]
It is important to note that if `refresh_token_cookie_domain` matches the Directus domain, the cookie is created correctly. However, having different domains, even if the cookie is generated, you face read limitation due to the security policies of the browser.

**Comment by CristianDev0160** [comment]
It is important to note that if `refresh_token_cookie_domain` matches the Directus domain, the cookie is created correctly. However, having different domains, even if the cookie is generated, you face read limitation due to the security policies of the browser.

**Comment by CristianDev0160** [comment]
The correct configuration to use cookies between subdomains of the same domain is the following:
```
REFRESH_TOKEN_COOKIE_SAME_SITE=none
REFRESH_TOKEN_COOKIE_SECURE=true
REFRESH_TOKEN_COOKIE_DOMAIN=mydomain.com
```
With this configuration I can now use the cookie

**Comment by simulieren** [comment]
@CristianDev0160 thank you so much! I almost gave up on this until I found your solution. I have no idea why it's so confusing.

**Comment by CristianDev0160** [comment]
I also had a lot of problems, but in the end I was able to log in with Google and other providers.
If you need help or have any questions, don't hesitate to contact me. I'm here to help

**Comment by br41nslug** [comment]
Make sure to try and get your setup working on sameSite `lax` tho as google will start cracking down on sameSite `none` sites.
