### ISSUE TITLE
"Save as Copy" not working when File required

### ISSUE THREAD

**Issue by Kinzi** [directus/directus#2196]
I have a post table with an image field(`featured_image` // Single File) that is set to required. When I hit "Save as Copy" I get the error: `Featured Image: This field is required` - even though the field is actually populated. Other save options work as expected without error.

If the field is not set to required the entry gets duplicated without any error.

## Expected Behavior
Duplication of the entry

## Actual Behavior
Error message saying "field is required" even though field is populated

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/75)
