### ISSUE TITLE
Right clicking on WYSIWYG editor does not give native right click options

### ISSUE THREAD

**Issue by OliverSpeir** [directus/directus#21987]
### Describe the Bug

When right clicking on WYSIWYG editor the only option presented is link

<img width="227" alt="" src="https://github.com/directus/directus/assets/115520730/05b64a30-962e-4be3-b8c5-c401e82d8741">

### To Reproduce

Right click on text inside WYSIWYG editor

### Directus Version

10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
You are correct that is the only link the context menu.
So what is the issue you're describing here?
Are you expecting anything else, or did it used to be different, if so then which options are you expecting.

Closing this issue for now but happy to re-open if enough information becomes available.
