### ISSUE TITLE
Search filter not showing terms from related table

### ISSUE THREAD

**Issue by kathleenazali** [directus/directus#21996]
### Describe the Bug

When I search a table, it won't show any result if the search term is from a related table. I thought this was just in my own self-hosted instance (running version 10.10.4), but I tested this in the demo site https://directus.pizza (version 10.9.3) and it also seems to happen. 

![Peek 2024-03-27 18-51](https://github.com/directus/directus/assets/11498979/01941b0d-2663-436a-9cc9-44584e682c7b)
Here is an example from https://directus.pizza/admin/content/posts. In the all post, I want to search for posts by Bunny Daniels. But when I enter `Daniels` in the search field, it says No result. I tried using `Author` field filter, and still No result shown when searching Daniels. It's only when I filter by `Author > Author name`, the results show. 

Here is another example using `Project Details > Built With` field. 
![Peek 2024-03-27 19-08](https://github.com/directus/directus/assets/11498979/d3b54cce-52cb-4666-99f9-bd6d878960fd)

Results only show when you do very specific filter will not work for non-tech users who don't understand the relations between the tables. I vaguely remember that this didn't happen in the earlier version of Directus, but TBH I'm not too sure either as I've only recently started testing.  

### To Reproduce

1. Find or add a field/attribute that's not native to the table, e.g. from the examples above, Author or Project Details > Built With 
2. Search with a term from the related field
3. Expected result: Entries related to that searched term should show. 
4. Real result: No results shown. 

### Directus Version

10.9.3 in directus.pizza, 10.10.4 in my own self-hosted instance

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
This is expected behavior, the search functionality is not smarter than doing a top level search against the current collections fields (foreach field LIKE searchValue) it does not traverse relations unless you explicitly filter for them as you've seen.
