### ISSUE TITLE
Unable to assign and value when trying to create new record using Graphql

### ISSUE THREAD

**Issue by beatlecz** [directus/directus#21992]
### Describe the Bug

I have a problem that after some development of new models etc I am unable to assign many-to-one relation when creating new record.
I have tried to create two new models with mant-to-one relation on my current directus and on clean one. I am still unable to assign relation when creatign but on clean instance it is not a problem.

Edit:
So now I cannot assign any param to new created record using graphql create mutation.

I am using Postgresql.

Have anyone experienced such an issue? Any solution? 

### To Reproduce

Don't know

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Please provide all the needed information to reproduce the issue.

For example:
- what queries are you doing?
- what are the errors you're getting?
- what are the differences between the instance where it works and the one where it doesnt?

Closing the issue for now but happy to re-open if we can get it reproducable

**Comment by beatlecz** [comment]
So I know where is the problem!!! It was caused by blocking Event hook flow on create on this collection. When I set the flow to be non-blocking then it works normally!!!
