### ISSUE TITLE
Defining action hooks on tables not woking

### ISSUE THREAD

**Issue by rainst** [directus/directus#2199]
## Version Info
  - 6.4.9 (ab5a935073324389db2e3444b5f1272753f7780f)
  - PHP version: 5.6.33
  - MySQL version: MariaDB 10.1.30
  - Web server: Apache 
  - OS name and version: Windows (Xampp)

I'm trying to implement an action hook after updating or inserting a new row in a table called _pages_, this is the expected implementation following the reference:

```
    'hooks' => [
        'table.update.pages:after' => function ($table, $data) {
            file_put_contents('testing.txt', $table . ":\r\n" . json_encode($data) . "\r\n", FILE_APPEND);
        },
        'table.insert.pages:after' => function ($table, $data) {
            file_put_contents('testing.txt', $table . ":\r\n" . json_encode($data) . "\r\n", FILE_APPEND);
        }
    ]
```
but when I try to insert or edit something I get this response from the API, where line 81 is the one where the update hook is defined.
```
{
  "success":false,
  "error":{
    "message":"Missing argument 2 for Directus\\Bootstrap::{closure}()"
  },
  "code":2,
  "class":"ErrorException",
  "file":"C:\\xampp\\htdocs\\directus\\api\\configuration.php",
  "line":81
}
```

If I remove the _pages_ filter it works as expected, it triggers for every table
` 'table.update:after' => function ($table, $data) { ... } `

What am I doing wrong here?
thank you!

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/76)
