### ISSUE TITLE
Field order in user profile page

### ISSUE THREAD

**Issue by HemboPagi** [directus/directus#22009]
### Describe the Bug

I added two new fields to **directus_users** table: text field and a _separator_. As one can not move the fileds between the default fields I exected fields to be shown at the bottom of the profile page. But when rendered out the separator is after the First Name and the Project field after Last Name.

<img width="744" alt="Screenshot 2024-03-28 at 14 01 31" src="https://github.com/directus/directus/assets/95413906/e5a93b76-2581-4942-adfd-c326c5a5c4a0">
<img width="744" alt="Screenshot 2024-03-28 at 14 01 12" src="https://github.com/directus/directus/assets/95413906/024a352c-0e29-4834-abae-ae19bf89094c">

### To Reproduce

1. Go to Settings -> Data Model
2. Select directus_users (under System Collections)
3. Add some extra columns

### Directus Version

10.8.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
Please update to the latest version, this was a bug that has been fixed

**Comment by br41nslug** [comment]
This was fixed in this PR https://github.com/directus/directus/pull/20910
