### ISSUE TITLE
Unable to set values in create mutation when blocking flow event hook is configured on collection "on create" event

### ISSUE THREAD

**Issue by beatlecz** [directus/directus#22007]
### Describe the Bug

When I configure blocking event hook on "on create" then I am unable to set record values when create using graphql mutation

### To Reproduce

Configure new Flow this way:
<img width="846" alt="image" src="https://github.com/directus/directus/assets/3007851/eb8a758f-252d-442e-a02b-3304d6484b1e">
and then try to create new record using graphql mutation

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Please provide more information about your Flow. What are the steps and specifically the final return value of the Flow?
