### ISSUE TITLE
include a feature for rebuild some static generated site

### ISSUE THREAD

**Issue by cocodrino** [directus/directus#2201]
Hi guys, would be possible that everytime that you make a change in the db fire some command for rebuild your static site generator???...

thank you so much...by the way...when will be released directus 7???

**Comment by rijkvanzanten** [comment]
The best way would be to create [a Hook](https://docs.getdirectus.com/6.4.0/#Hooks). A hook allows you to run any arbitrary PHP which you can use to trigger your static build process elsewhere.

> when will be released directus 7???

As soon as possible! We really want to release, but we ran into some issues while testing we'd like to fix before properly releasing it 🙂
