### ISSUE TITLE
Crash: Small Instance Unstable Thumbnailing

### ISSUE THREAD

**Issue by josias-r** [directus/directus#22025]
### Describe the Bug

I have a small directus instanced hosted on DigitalOcean cloud platform (512mb, 1vCPU, shared)

Very few simple image request are able to completely crash the instance, causing DigitalOcean to restart it, without any logs other then `was terminated`

<img width="1000" alt="Screenshot 2024-03-31 at 15 58 08" src="https://github.com/directus/directus/assets/11424820/dd1f265b-5fff-4d39-a140-e9b574bface4">

While I understand that a small instance like that might not be very stable, I think just a few images by a single user should not be able to completely crash the system causing it to restart

### To Reproduce

I think the simplest way to reproduce it is:

- Create the 512mb, 1vCPU shared directus instance on DO
- Using the directus API: Upload around 10 jpg images (around 4000x6000px, 3mb each)
- Simply open the directus app and navigate to the folder you uploaded the files to

This should cause the app to generate thumbnails the first time you open it up. The directus instance will most likely crash (I have a 100% success rate with 10 fresh images 🙂)

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Image transformation is a very CPU/Memory intensive process. The images you mention "around 4000x6000px, 3mb each" are almost the default MAX transform size of 6000x6000px and doing multiple of those may require more than the minimum specs.

Can you try lowering the `ASSETS_TRANSFORM_MAX_CONCURRENT` config to see if it results in a more  stable experience? And perhaps increasing the `ASSETS_TRANSFORM_TIMEOUT` could help too.

**Comment by josias-r** [comment]
Even having `ASSETS_TRANSFORM_MAX_CONCURRENT ` at `2` immediately crashes the server. It basically crashes immediately much earlier before any timeout comes into play

**Comment by br41nslug** [comment]
I am closing this issue since I unfortunately can only conclude that this was a resource limitation somewhere when handling the images (be it not enough RAM or CPU). This is unfortunately something we cannot currently fix at the minimum required resources https://docs.directus.io/self-hosted/docker-guide.html#requirements

Definitely feel free to create a new issue if it turns out to related to the specific images used or something along those lines 😄
