### ISSUE TITLE
Gett entries in category - m2m

### ISSUE THREAD

**Issue by beyer-johannes** [directus/directus#2202]
## Version Info
  - Directus version and branch (Or commit hash): master #ab5a935  
  - PHP version: 7.2
  - MySQL version: 5.6.38
  - Web server: (Ex. Apache, nginx or IIS?) Apache

I have following m2m relation:
audios < audio_categories_junction > audio_categories

## Expected Behavior
I need to get all audio-entries in the category with the id 1.

## Question
Is there a filter operator or anything other, who can give me 
the expected entries like this:
<url>/api/1.1/tables/audios/rows?filters[categories][has]=1 
(I know the "has" means, "Has one or more related entries")

Thanks for any help!

**Comment by rijkvanzanten** [comment]
You can target nested values using _Dot Notation_:

`filters[field.nestedField]=value`

**Comment by beyer-johannes** [comment]
There it is!

Have a big thanks for you fast response!
