### ISSUE TITLE
Authentication and authorization

### ISSUE THREAD

**Issue by beyer-johannes** [directus/directus#2203]
I have a vue spa (no SSR) and directus (version 6) as api.

Now I want to add an authentication- and autorization process (sign in, sign up), 
to protect my vue app. This users only should can login into the vue app. Not into directus, 
BUT should can be manageable in directus.

Is it possible to use a directus user table (with username, email and password) to handle this, 
without manual programm all the registration and login logic (send Mail, forget password etc.)?

I want to avoid the giant SSO providers like okta or auth0...

Thanks for any idea and help!

**Comment by beyer-johannes** [comment]
Is there a recommended way to handle this?

**Comment by rijkvanzanten** [comment]
> This users only should can login into the vue app. Not into directus

The directus users table controls who has access to directus, so what your asking isn’t available.

**Comment by benhaynes** [comment]
You would need to create a new table to handle this, eg `users`

**Comment by beyer-johannes** [comment]
Okay, I need to implement okta for this. Thank´s for your answers!
