### ISSUE TITLE
New etag not being generated on changing data in Bookmarks / Presets, so admin interface displays old data even after saving

### ISSUE THREAD

**Issue by JosephCarrington** [directus/directus#22055]
### Describe the Bug

Dashboard -> Settings -> Bookmarks displays incorrect/old data after a change to the data.
![2024-04-01 11 39 06](https://github.com/directus/directus/assets/1017852/21221a8d-9302-4c5d-8b08-205fecb8ddec)

### To Reproduce

When I make a change to a 
Settings -> Bookmarks -> Item
(as distinct from making a change to a bookmark from the content screen)
And change, for instance, it's user scope, it saves the data correctly. However, when the browser redirects me back to the list view, I do not see the data as having ben changed. I believe that this is because the request is sending along a conditional GET request, where the 'If-None-Match' is set to the etag that the browser has. The server does not appear to generate a new etag for some time however, so the browser continues to get old data. This makes it challenging to create presets that apply to all users.

### Directus Version

v10.9.2

### Hosting Strategy

Directus Cloud

**Comment by paescuj** [comment]
Good news, this has been fixed via #21702, which has been released with [v10.10.0](https://github.com/directus/directus/releases/tag/v10.10.0) 👍 (See also #21807)
