### ISSUE TITLE
Issue with depth param

### ISSUE THREAD

**Issue by psuplat** [directus/directus#2206]
I am either using it incorrectly (the docs don't give you an explicit example) or the depth param is not working as expected.

Here is my table layout:
![image](https://user-images.githubusercontent.com/14207860/46750169-4e4fdd00-ccaf-11e8-82d0-1278098452ce.png)

and the definition of the image field:
![image](https://user-images.githubusercontent.com/14207860/46750253-73445000-ccaf-11e8-8b22-e9bb69d6297f.png)

When i call the api like so:
`http://localhost/api/1.1/tables/sliders/rows`
the json with all rows is returned as expected, but the image property contains only the id of the file (which is the correct  behaviour)

![image](https://user-images.githubusercontent.com/14207860/46750677-5bb99700-ccb0-11e8-9f6b-61b543fa4f8a.png)

in order for me to get the path to the file, I should specify the dept, like so:
`http://localhost/api/1.1/tables/sliders/rows?depth=2`

however that does not work. No matter if I set the param to 2, 5 or 20 I only ever get the file ID.

**Comment by psuplat** [comment]
Duh, dumbass!
Never mind, it all works as expected.

Since this is still in early stages of development on localhost, my tables were given public users unauthenticated access to content (VIEW only). I forgot to add the same to the directus files table, and due to lack of auth token access to the relation was blocked.

**Comment by rijkvanzanten** [comment]
Good to hear you figured it out 😄
