### ISSUE TITLE
Discuss Different OSS Licenses

### ISSUE THREAD

**Issue by shahabafshar** [directus/directus#2208]
Hi dear Directus team.

We love what you do and we certainly crave to use it in our projects, but your licensing method is preventing us from using it inside our projects. is it possible for you to change the licensing or provide a dual license option to **MIT** or **BSD**?

keep up the good work!

**Comment by rijkvanzanten** [comment]
Why is GPL-3.0 specifically preventing you from using it?

**Comment by shahabafshar** [comment]
GPL enforces a specific copyleft approach which limits the usage to GPL-freindly license types "only". on the other hand we have frameworks like symfony which are MIT based and are used inside a lot of solutions which we use and love, such as drupal and many others.
I believe there is a big potential here, and the dual licensing approach may open many doors for developers and solutions with other license types from opensource to proprietary.
We love what you do and hope that you give us a chance to use your product in such ways.
any way, we appreciate your views and follow what you do.

**Comment by rijkvanzanten** [comment]
(I'm not a lawyer)

Usage of the Directus platform itself is not bound by any licenses is it? 

As far as I know, the license only applies to the code. Only if you were to make your own Fork of Directus to add in some proprietary strictly licensed code and _then_ re-publish it as a new project you would run into the licensing business.

Also, Drupal is GPL-2 licensed 😉

**Comment by shahabafshar** [comment]
dear rijkvanzanten,

Thank you for your reply. Well you exactly mentioned my point, Drupal is GPL, and it uses symfony because symfony license terms are based on MIT which **"permits"** using it inside GPL projects; though it doesn't work the other way around! GPL projects are ONLY usable inside other GPL projects (and very few other forks of GPL).

And yes, one of the points where you come to a dead-end is exactly when you want to integrate Directus into other projects or make mashups of frameworks to make something bigger.

Any way choice is surely yours to do so or not, it's your code after all. providing a dual licensing would surely make us happy though!

Wish you and your team the best!

**Comment by Chris533** [comment]
@shahabafshar 
Yes, we only applied to one project due to this Licenses issue in the last year.
We are considering creating a separate dashboard(MIT).
Let's stay away from the GPL.

**Comment by rijkvanzanten** [comment]
@Chris553 Could you elaborate? How did Directus using GPL-3.0 restrict you from using the platform?

**Comment by mccolin** [comment]
It's been a while since this topic has stagnated, but I would be curious to know if more consideration on license alternatives has taken place with new and recent releases.

My team is looking to incorporate Directus as a component of a project we  plan to offer both as Open Source Software and build commercial products atop. More permissive licensing would remove a grey area from licensing for customer Directus extensions, as well as the entire composite system.

As far as things stand, today, GPL is a non-starter for many of our target OSS adopters and services customers.

**Comment by rijkvanzanten** [comment]
> My team is looking to incorporate Directus as a component of a project we plan to offer both as Open Source Software and build commercial products atop

By _incorporate_, do you mean make a copy of the source code and adjust it to fit as a part of a bigger project? In that case, you'd have to license/attribute it according to GPL3. If your project only _uses_ Directus as a platform, the licensing shouldn't be any problem AFAIK

> As far as things stand, today, GPL is non-starter for many of our target OSS adopters and services customers.

That's an interesting statement! Care to elaborate? 

Historically, major open source platforms (like WordPress and Drupal) have (successfully) relied on GPL licenses, and seeing [the bizarre marketshare on the web of those projects](https://kinsta.com/wordpress-market-share/), I'd assume the license wasn't an issue for most.

**Comment by benhaynes** [comment]
Just to add that when we have the available financial resources, we'll be working with our legal counsel to provide clarity around our current license, and also look into other options for licenses.

But to be clear, while I recognize that MIT and other permissive licenses are a great option for smaller libraries, there are implications for our actual _commercial revenue_ (which is how we pay our engineers to keep maintaining this premium OSS). MIT doesn't require modifications to be open-sourced, whereas the GPL does. So if we were MIT, any big company could just take our IP and fork their own closed-source version to run us out of business.

Other MIT/permissive vendors actually have dual-licenses (often paid) for key features... which is a way to get around that. But I really don't see that as true FOSS, to begin with. But I digress.

Again, very happy to continue this conversation, but it's not something that will likely quickly/easily change. I hope all this makes sense... IANAL. ❤️🧑‍⚖️

**Comment by mccolin** [comment]
Thank you for the quick and excellent responses @benhaynes and @rijkvanzanten 👍 

I can 100% appreciate the risk for Directus' business that a less-strict license (e.g., MIT or Apache) would hold. I'm sure there will be important team debates re: a potential dual-license future or other options (re: your point of FOSS 😊)

Regarding the feedback we've taken from potential target clients: much of the fear/uncertainty/doubt we're seeing for our potential use case comes into play around:
* What constitutes _modifying_ the work? Extensions? By the letter of the license, there's nuance that's hard to pinpoint
* What differentiates between use as a copied component vs. a modified component of a larger system – i.e., what's the exposure/risk for a project that uses Directus in an unmodified way as a standalone component of its infrastructure?

My read of the license is inline with yours @rijkvanzanten in that Directus as a piece of infrastructure is not modification and wouldn't require a share-alike licensing of the entire system, but the fear comes from the existence of over zealous lawyers 😉 

Is the Directus team open to separate/customized (potentially paid?) licensing terms for partners?

Excellent discussion. I'm so glad you both responded to and reopened this conversation!

**Comment by rijkvanzanten** [comment]
> [...] but the fear comes from the existence of over zealous lawyers

I'm wondering if we can tackle that by extending the GPL3 license with a dedicated extensions clause outlining exactly what we consider in and out of scope for "modifications" 🤔 

> Is the Directus team open to separate/customized (potentially paid?) licensing terms for partners?

Always down to discuss, but it feels like a very tricky thing to maintain over time, as every new version release would have to be re-licensed and re-distributed 🤔

**Comment by benhaynes** [comment]
Hey @mccolin — all great points, and this is exactly what we want to clarify once we have the legal resources. I think an extended license might help clarify the gray points of GPLv3.

**Comment by DigNZ** [comment]
Just joining in on this as I've noticed that the client side javascript SDK is also GPL licenced. GPL and client-side Javascript seems to have a complicated relationship but its seems on the face of it that using the javascript SDK inside a custom frontend would make the whole frontend subject to the GPL and as it runs on client's browers its being distributed. That seems like a limitation where the GPL is preventing an expected use of the platform.

As mentioned in my discussions question on the topic happy to contribute to the core of directus if we make modifications there but need to be able to make custom clients and serverside extensions that incorporate propritary work.

I think even the LGPL would be a better fit or - as many other projects do - licence the SDKs with a liberal licence and the core platform with the GPL.

**Comment by rijkvanzanten** [comment]
Good point @DigNZ! There's no reason to have the SDK be GPL. We're already more openly licensing most of our other open source licenses (like https://github.com/directus/format-title), so I'm totally down relicensing the SDK to MIT as it's just a thin wrapper around `axios` to allow interfacing with the platform 👍🏻

**Comment by maxmblack** [comment]
Since directus closed the Series A funding (congrats 🥳) - can we expect clarification/extension on the current license in the future?

The information I collected until now is: 
The usage of directus in a project (for example as backend) **shouldn't** require the whole project to be licensed as GPL as well. Created extensions **shoudn't** force the project to be GPL licensed as well, but this is more tricky and no one is really sure. 

But in the end these are unclear statements, correct?

**Comment by benhaynes** [comment]
@maxmblack — thanks, and a great topic to cover! We're starting to create more resources on this (see below), but to be clear, the GPL license does not restrict any software extensions (they do _not_ need to inherit the OSS license, and can be proprietary). We'll keep posting on this to help clarify.

https://directus.io/blog/libre-vs-gratis-what-is-free-and-open-source-software/

More importantly, we will *not* be changing our license. Our core software is and will remain completely free and OSS.
