### ISSUE TITLE
users.update hook is called in every call inside Directus

### ISSUE THREAD

**Issue by TOAD-Joey** [directus/directus#22093]
### Describe the Bug

Not 100% if this is really a bug or something that is not completely clear for me. But when i create a hook extension for Directus and put the following code in it: 

`export default ({ action }) => {
	action('users.update', () => {
		console.log('USER UPDATED!');
	});
};`

When i open any page on Directus this hook is being fired, not sure why. Maby i has to do something with the notifications being checked. The payload of that hook trigger contains a previous url so i can imagine it tries to set the last url. Is there a hook/trigger we can use so this will only fire when we edit the user by the users form? 

![image](https://github.com/directus/directus/assets/2589049/9aabbe47-81b3-4cff-bc45-a59845fbda59)

### To Reproduce

- Installed Directus with the newest version via Docker
- Created a new extension
- Added a 'action' hook for 'users.update'

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Correct there is a "last visited page" field on users which gets updated on each page visit in the App.
