### ISSUE TITLE
Items created through flows don't trigger event hooks

### ISSUE THREAD

**Issue by JackMullinkosson** [directus/directus#22108]
### Describe the Bug

Event hook flow is triggered when an item is created manually but not when an item is created through a separate directus flow. No entry shows up in the logs.

### To Reproduce

1. Create a flow that creates items in the DB for example "reservations". In my case it's a webhook that receives post requests and creates and relates an item to multiple other collections.
2. Create a flow that is triggered on an event hook - the scope should be items.create, it should be action (non blocking), and in the "reservations" collection. The flow should update something in the "reservations" collection for the reservation item that triggered the flow. In my case I update the venue to be related to a certain venue.
3. Trigger the first flow then check logs in the event hook flow - observe that the second flow did not get triggered.

### Directus Version

v10.10.4

### Hosting Strategy

Directus Cloud

**Comment by br41nslug** [comment]
Make sure your Flow operation is configured to "emit events"
![image](https://github.com/directus/directus/assets/9389634/65e9a1da-999d-4cf3-8604-c965cce085fa)
