### ISSUE TITLE
v7 - Unable to select non-US timezones

### ISSUE THREAD

**Issue by christiaangoossens** [directus/directus#2210]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus version and branch (Or commit hash): 7.01 release zip from Github
  - PHP version: 7.2
  - MySQL version: 10.1
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: CentOS

## Expected Behavior

Interface for new user creation showing all timezones

## Actual Behavior

Interface for new user creation only shows US timezones

## Steps to Reproduce
 1. Login to Directus 7
 2. Create a new user
 3. Look at the timezone field

## Schema Dump, Logs, or Screenshots

![image](https://user-images.githubusercontent.com/9487666/47044180-ca569300-d18f-11e8-88b5-c64b06591c0b.png)

**Comment by christiaangoossens** [comment]
Btw, this may not be relevant right away after a full rewrite, just reporting it for future purposes.
Good job on creating version 7!

**Comment by benhaynes** [comment]
Thanks @christiaangoossens – this one's my fault... the other devs warned me that I only had US timezones. 😬 

I wasn't able to (quickly) find a good list of world timezones where there was only ONE in each timezone. Most had every major world city (way too many options). If you or anyone else can find a good list we will definitely update!

I'll try to find a good one too... or make one.

https://github.com/directus/api/search?q=New+York&unscoped_q=New+York

**Comment by rijkvanzanten** [comment]
@benhaynes apparently the API has the whole list in it already:

https://github.com/directus/api/blob/6051b07c3f8b5c8c6eb295ce26c3943fbe14d966/src/helpers/all.php#L590

However, just copying this into the interface options will cause a huge unusuable drop down. We might be better off coming up with a new interface to select a time zone. Maybe a map like the macOS settings?

<img width="668" alt="zeo2b" src="https://user-images.githubusercontent.com/9141017/47052217-72ab2e00-d175-11e8-90f4-5daee17a4c13.png">

**Comment by christiaangoossens** [comment]
I would alternatively propose something like this:

https://i2.wp.com/angularscript.com/wp-content/uploads/2018/01/Timezone-Selector-For-Angular-2.png?ssl=1

So search + titles.

I find that map in macOS pretty hard to work with generally, its hard to find the exact right one, and selection may be very difficult for irregular timezones (for instance good luck clicking Bhutan (+6) but not India or China who both use irregular timezone patterns.

**Comment by benhaynes** [comment]
I like the search + dropdown option for the extended list. Another thought would be to simply have a dropdown of the time offsets – would that also work? In this case the user would have to know their offset, (eg: `+5`) but it would be a far more simple solution.

To make this option a bit more intuitive we could show a list of most major cities (in that timezone) on hover/select.

Thoughts?

**Comment by benhaynes** [comment]
I've moved this ticket here:

https://github.com/directus/app/issues/1041

We're removing the directus/directus issues to keep all in the main repos
