### ISSUE TITLE
[OKTA Saml Integration] Showing can't be used to redirect after login

### ISSUE THREAD

**Issue by fswbt1995** [directus/directus#22109]
### Describe the Bug

Following this blog https://docs.directus.io/blog/configuring-okta-sso.html, i hit this issue below

{"errors":[{"message":"Invalid payload. URL \"http://localhost:8055/admin/login?continue=\" can't be used to redirect after login.","extensions":{"code":"INVALID_PAYLOAD","reason":"URL \"http://localhost:8055/admin/login?continue=\" can't be used to redirect after login"}}]}

After configuring OKTA and the .env, I successfully started the Directus server. After I clicked "login with OKTA", I hit this issue

![image](https://github.com/directus/directus/assets/155092115/2b45ab6b-8592-47af-9105-6b0481c388e4)

It's confirmed that the OKTA setting is correct, coz I tried to by pass the redirect issue, and successfully login via OKTA. 

Based on the configuration, OKTA redirect me to "http://localhost:8055/auth/login/okta/acs", which is expected. 

![image](https://github.com/directus/directus/assets/155092115/38a534f2-da43-47dd-aac2-3c79817085fd)

### To Reproduce

1. Setup a OKTA IDP service
2. Config corresponding param in .env
3. Start the directus service
4. Try "sign in with OKTA"

### Directus Version

v10.10.5

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by fswbt1995** [comment]
Update:

After I read the source code, and tried manually replace with "http://localhost:8055/auth/login/okta?redirect=/admin/login?continue=". The whole SAML login flow is good. So wonder why the original source code will add "http://localhost:8055" to param redirect = , while, the source code expects relative path only. 

![image](https://github.com/directus/directus/assets/155092115/29dad0b8-a548-414b-998a-d4dbf4cad886)

**Comment by paescuj** [comment]
As it's the case for all SSO setups, you need to configure the `PUBLIC_URL` variable, see https://docs.directus.io/self-hosted/config-options.html#sso-oauth2-and-openid.

@phazonoverload We may want to link this config section in the blog article?

**Comment by Zehir** [comment]
For future people finding this issue after they upgrade to directus 10.10.X checkout this breaking change;
https://docs.directus.io/releases/breaking-changes.html#introduced-allow-list-for-oauth2-openid-saml-redirects

**Comment by Mathijs003** [comment]
> As it's the case for all SSO setups, you need to configure the `PUBLIC_URL` variable, see https://docs.directus.io/self-hosted/config-options.html#sso-oauth2-and-openid.
> 
> @phazonoverload We may want to reference this config section in that blog article

This should be more clear in the docs
