### ISSUE TITLE
Upload file not working (10.10.4) 

### ISSUE THREAD

**Issue by Psaugues** [directus/directus#22107]
### Describe the Bug

Im trying to upload a file to my Directus server but i got this error : No files were included in the body

For my test i set the file public access control (add read edit)

### To Reproduce

 ```
const title = 'Example';
const file = new Blob(["Test"], { type: 'text/plain' });
const fileName = 'example.txt';

const formData = new FormData();
formData.append('title', title);
formData.append('file', file, fileName);

const result = await client.request(uploadFiles(formData));
```

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
I am unable to reproduce the issue as described, I've ran the provided code snippet in nodejs and it seems to work as expected.

https://github.com/directus/directus/assets/9389634/a3cfe500-390c-4bcd-96b3-1df057ccc601
