### ISSUE TITLE
Current location marker not update automatically when changing position  

### ISSUE THREAD

**Issue by armanhadifatah** [directus/directus#22119]
### Describe the Bug

Using the map when I do select my position and move around I expect the current position marker will follow me like google map but its not a need to press my current location multiple times to make my current position marker to move to my current position 

### To Reproduce

Just create map field for a data model  and then try insert and select current location on the map and move with a phone to see that current location pointer not changing.

### Directus Version

v10.10.5

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by armanhadifatah** [comment]
![photo_5231346226560097071_y](https://github.com/directus/directus/assets/48276427/5de23393-a1ec-4d18-9782-ec25d28dfcd0)

**Comment by br41nslug** [comment]
Your current position is a single moment in time (the time you press the button) it is not supposed to be tracking you indefinitely.
