### ISSUE TITLE
Missing headers for invalid file uploads

### ISSUE THREAD

**Issue by SvenBudak** [directus/directus#22114]
### Describe the Bug

I just noticed that Directus does not set the CORS headers correctly in the event of an error when uploading a file. They are simply missing. When the upload is successful, all headers are present as expected.

![image](https://github.com/directus/directus/assets/4930169/846887a9-fc8a-4d81-b23a-1419b2ea88a7)
![image](https://github.com/directus/directus/assets/4930169/a48ca2da-cd06-44d7-89c7-701d80ab394e)

This error has already been discussed here: https://github.com/directus/directus/issues/15194
Apparently, it was fixed for GraphQL APIs. It seems the fix has been missed for the file APIs.

### To Reproduce

Upload an image that is too large.

### Directus Version

10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
I am unfortunately not able to reproduce the described issue using the given reproduction steps on 10.10.5.

Could it be the proxy in between not properly passing the headers along in an error situation?

![image](https://github.com/directus/directus/assets/9389634/c9ea1752-2a91-4e67-b33e-603f90122fcc)

**Comment by SvenBudak** [comment]
Thank you very much, br41nslug! The problem was indeed that our nginx allowed 10 MB and Directus also allowed 10 MB. So, when you uploaded a file larger than 10 MB, nginx rejected it, and the response in the app was not from Directus. Hence the missing headers. Thank you for your help!
