### ISSUE TITLE
Visual issue with Flows

### ISSUE THREAD

**Issue by 1241751430** [directus/directus#22129]
### Describe the Bug

There was an issue when creating the process, as the created process did not have corresponding arrow lines and could not connect to subsequent processes.

### To Reproduce

![image](https://github.com/directus/directus/assets/45428553/72e406e3-07a8-48df-88c1-d7510834cfa0)

### Directus Version

v10.10.5

### Hosting Strategy

Self-Hosted (Custom)

**Comment by licitdev** [comment]
I can't reproduce this issue in `10.10.5`. It looks like you're facing a visual bug. Are you using custom CSS?

The `Read Data` and `Run Script` operations look active as they are not greyed out.
Please update your project to `10.10.5` as your screenshot shows `10.9.3`.

<img width="742" alt="image" src="https://github.com/directus/directus/assets/26413686/00bde524-06b4-4479-a027-435c00bc1845">
