### ISSUE TITLE
Slack icon link in directus.io footer is incorrect

### ISSUE THREAD

**Issue by Joshua-Sherer-Bose** [directus/directus#2213]
Current link is to: https://slack.directus.io/ when the correct link is: https://slack.getdirectus.com/ 

![ss](https://user-images.githubusercontent.com/21686488/47112114-68476d80-d223-11e8-84c2-c9d7d56728a7.png)

**Comment by benhaynes** [comment]
Thanks @Joshua-Sherer-Bose! Wishful thinking that we'd have all of our domain shifts complete by now... this has been resolved! We'll update it back to the new link once it's working. 😄
