### ISSUE TITLE
Field Permissions - Unable to select fields 

### ISSUE THREAD

**Issue by adam-bubela** [directus/directus#22132]
### Describe the Bug

The checkboxes with field names look clickable but they are not. All of them are selected even though they weren't before the update.
![image](https://github.com/directus/directus/assets/9866755/6ac0fa55-f369-4f8f-b326-f5ce1e09df34)

### To Reproduce

Migrate the database to v 10.5.4 or higher. It could have happened earlier around 10.10.0.

### Directus Version

v10.5.4

### Hosting Strategy

Self-Hosted (Custom)

**Comment by adam-bubela** [comment]
The only solution I found so far:
Go to the database find table `directus_permissions` and manually remove `*` from the `fields` column.
Somehow bizarrely an update caused adding asterisks everywhere as per the below snapshot
 
![image](https://github.com/directus/directus/assets/9866755/6b4b383b-da03-44ce-8650-58e9804bee9c)

**Comment by izoukhai** [comment]
I have the exact same issue on one instance, but not the other

**Comment by izoukhai** [comment]
Just a quick update on the issue, it seems like access control is completely broken. Try the following:

1. Restrict all access on a collection
2. Click on "Use Custom"
3. Select the fields you want the Public role to see
4. Fetch the API with the Public role
5. All fields are visible
