### ISSUE TITLE
PM2 Log File Configuration

### ISSUE THREAD

**Issue by the-other-dev** [directus/directus#22131]
### Describe the Request

At the moment, it is possible to configure a few PM2 settings via environment variables (https://docs.directus.io/self-hosted/config-options.html#pm2).

Due to compliance reasons, I'd like to configure the path for `error_file` and `out_file` as well (see https://pm2.keymetrics.io/docs/usage/application-declaration/#log-files).

I could achieve this now by overwriting the `ecosystem.config.cjs` in my own Dockerfile (extending the official one) but then it is harder to see upstream changes on that file.

Would it make sense to add more entries in the `ecosystem.config.cjs` so they can be changed easily via environment variables like the other entries in that file?

Example:

```js
module.exports = [
    {
        // [...] Everything that is already there

        // Logs
        error_file: process.env.PM2_LOG_ERROR_FILE,
        out_file: process.env.PM2_LOG_OUT_FILE
    },
];

```

I would gladly contribute this change as well if it is accepted.

### Maintainence Strategy

The additional environment variables would need to be added to the section about configuring PM2 (https://docs.directus.io/self-hosted/config-options.html#pm2).

Apart from that, it would be the same maintenance as for other PM2 configuration parameters.

**Comment by rijkvanzanten** [comment]
Makes sense to me! Go for it 🙂

**Comment by the-other-dev** [comment]
Hey @rijkvanzanten! Thanks for the swift reply! I created the corresponding pull request https://github.com/directus/directus/pull/22155
