### ISSUE TITLE
Default table column order

### ISSUE THREAD

**Issue by MartsTech** [directus/directus#22137]
### Describe the Improvement

Currently columns in a table seem to be sorted in alphabetical order based on the key of their field. Every user can set a custom sort of the table which is only for him and is saved in the directus_presets table as layout_query. Ideally the admin should be able to set a default order by ordering the fields in the data model.

**Comment by br41nslug** [comment]
> Ideally the admin should be able to set a default order by ordering the fields in the data model.

I am not directly seeing what this would add over setting a global preset with the desired ordering? 🤔 

Admins can already set global presets that are the global default or a role default.
![image](https://github.com/directus/directus/assets/9389634/bdd355dd-eb08-4a2f-a1c6-0d51eb546c89)
