### ISSUE TITLE
WYSIWYG should not add 'target="_self"' attribute when not opening in new tab

### ISSUE THREAD

**Issue by jonaskohl** [directus/directus#22133]
### Describe the Improvement

Some routing/SPA frameworks ignore a link when a `target` attribute is set, even when the default value of `_self` is explicitly set. The only way to bypass this is to omit the `target` attribute altogether. Thus to ensure maximum compatibility with SPA frameworks, I suggest to omit that attribute when the *Open in new tab* checkbox is unchecked.

The offending part is the assignment to `linkHtml` inside of `useLink()#saveLink()` in the file [/directus/app/src/interfaces/input-rich-text-html/useLink.ts:131-133](https://github.com/directus/directus/blob/ce0da9cd7671a38dcc8d3a2fb61a204c1d6f7922/app/src/interfaces/input-rich-text-html/useLink.ts#L131-L133):

To fix this, these lines:
```typescript
const linkHtml = `<a href="${link.url}" ${link.title ? `title="${link.title}"` : ''} target="${
    link.newTab ? '_blank' : '_self'
}" >${link.displayText || link.url}</a>`;
```

have to be changed into something like this:
```typescript
const linkHtml = `<a href="${link.url}" ${link.title ? `title="${link.title}"` : ''} ${
    link.newTab ? 'target="_blank"' : ''
}>${link.displayText || link.url}</a>`;
```

**Comment by br41nslug** [comment]
Can you explain on how this change will "to ensure maximum compatibility with SPA frameworks"? And why this specifically impacts VueJS which is the SPA framework used and thus the only one that it really needs to be compatible with.

**Comment by jonaskohl** [comment]
For example, at work we're rebuilding our website using Directus as our CMS (we use a custom block-based structure) and use SvelteKit for the actual site. We have several instances where we use WYSIWYG editors, the most prominent example being a "Richtext block" collection with literally just a WYSIWYG field. We then take that field (let's call it `content`) and render it on the site using Svelte's `@html` tag. So our `BlockRichtext` component (`BlockRichtextComponent.svelte`) looks something akin to this:

```svelte file=BlockRichtextComponent.svelte
<script lang="ts">
    import type { BlockRichtext } from "$lib/blocks/BlockRichtext.ts";
    export let block_data: BlockRichtext;
</script>

<div class="block block--richtext">
    {@html block_data.content}
</div>
```

If I include a link to another page on our site inside of the WYSIWYG editor, that link will cause a full refresh, because SvelteKit will skip past any links that have a `target` attribute. Also, from what I could find, it seems to be somewhat standard behavior for SPA frameworks to ignore all links with a `target` attribute present.
