### ISSUE TITLE
Loading up Flow Logs with large data sets and many log objects will cause crash with 500 error

### ISSUE THREAD

**Issue by JayShoe** [directus/directus#22143]
### Describe the Bug

I'm testing flows and I have some large datasets inside of a JSON field. Everything works fine at first but after running the flow on 100000's of objects the logs will not load. I receive a 500 error, and then it fails. 

I suggest limiting the query when logs are being viewed so it only load 10 items at a time. This way we never retrieve too many logs when loading them. 

EDIT: it doesn't appear to be loading too many log objects. It appears that the log objects are individually too large. We have JSON read from API, and then JSON save to database operations so the logs are saving a ton of data. https://github.com/directus/directus/issues/20823

### To Reproduce

1. Create a collection with a JSON field. 
2. Load up datasets with approximately 4000 lines of JSON. Create many of them.
3. Create a flow to read each one of those items. 
4. Run the flow a bunch of times so that you are creating a bunch of logs. 
5. Go into the flow which reads those items. 
6. Click Logs to view the logs. 

Directus will crash with a 500 error. Sometimes the pressure limiter will hit. 

### Directus Version

v10.10.5

### Hosting Strategy

Directus Cloud

**Comment by rijkvanzanten** [comment]
This is the same underlying issue as https://github.com/directus/directus/issues/17894 and the resolution will be tracked there. Thanks!
