### ISSUE TITLE
Allow `MailService.send(EmailOptions)` to be filtered

### ISSUE THREAD

**Issue by luistar15** [directus/directus#22145]
### Describe the Improvement

In my extension I use `MailService` and I need to use liquid templates in the subject of the email.
For this I added a second paramenter `optionsFilter` to the `send`  method.

https://github.com/luistar15/directus-email-inline-template/commit/76a73c826e973e0fd1a008212864e92a8e6c17dc
```ts
export class MailService {
	async send<T>(options: EmailOptions, optionsFilter?: Function): Promise<T> {
		if ( optionsFilter ) {
			options = await optionsFilter( options, { liquidEngine } );
		}
		//...
	}
}
```

Now I can use it like this to apply liquid render to the subject:
```js
const mailService = new MailService(...);

const templateData = {
	name: 'John Doe',
};

const options = {
	to: 'user@mail.com',
	subject: 'Hello {{ name }}',
	template: {
		content: 'Hello {{ name }}!',
		data: templateData,
	},
};

const optionsFilter = async ( options, { liquidEngine } ) => {
	options.subject = await liquidEngine.parseAndRender( options.subject, templateData );
	return options;
};

await mailService.send( options, optionsFilter );
```

**Comment by luistar15** [comment]
I think It would be better to add it as another option in the [hook system (action, filter)](https://docs.directus.io/extensions/hooks.html#custom-api-hooks).

```js
export default ({ filter, action }) => {
	filter('email.send', ( options ) => {
		console.log('Sending email!');
	});

	action('email.send', ( options, result ) => {
		console.log('Email sent!');
	});
};
```

**Comment by ComfortablyCoding** [comment]
The `email.send` filter was added in `v10.13.2` . See https://github.com/directus/directus/pull/23024
