### ISSUE TITLE
Website article on Directus not showing thumbnail on Google search 

### ISSUE THREAD

**Issue by jittimak** [directus/directus#22153]
### Describe the Bug

Hello! I'm facing the problem of Website article that I create on Directus.
It's not showing thumbnail on Google search like any other competitor.

![S__1181294](https://github.com/directus/directus/assets/166573809/b9fcd8f6-1437-44fe-b938-f979ed6a7b6a)

I've already add photo to on my article but not sure about any thing I should do next, in order to let Google AI learn and pick the photo to display as a thumbnail on Google search

I just wondering, has anyone facing the same problem with me?
And any thing I can do to have thumbnail like other website.

**Comment by hanneskuettner** [comment]
Since Directus only acts as your data source, this is more a problem with the code generating your website and not an issue with Directus itself, which is why I'm closing this issue.

But you might want to have a look into JSON-LD to tell Google what image to show. https://schema.org/BlogPosting

**Comment by jittimak** [comment]
thank you
