### ISSUE TITLE
Flows

### ISSUE THREAD

**Issue by semorur** [directus/directus#22154]
### Describe the Bug

Hello, 
i don't know if it is a bug or I am making something not correct.

I have a project. For each project I have tasks. Tasks must have special numerator based on amount of tasks in certain project.

I have a flow on task creation, non-blocking. The flow Reads data, makes some calculation in a script and updates serial number of the task.
I expect that my flow will run for every created task one by one. When I create 1 task - it works, but when I create a bunch of tasks - all tasks have the same serial number.

I have tried several approaches:
1) on creation count tasks in a project and write this number to a task.
my flow: Trigger - read data - script - write data
Here I Read data with "count" aggregation. I decided that somehow creation works after all flows, so I moved on to the next approach

2) in project I created an integer field. On task creation this field has to be updated +1 and write this number in a task.
my flow: Trigger - read data - script - write data to project - write data to task

The problem that Read data gives me the same payload for all items that were created in one bunch.

### To Reproduce

1. I have a task list in project, I want to create new (create new.png)
<img width="829" alt="create new" src="https://github.com/directus/directus/assets/152224102/66ef55a7-23e8-4bf9-8642-bf1f07cb5d25">

2. here I get two more tasks, but they are not in database at the moment. I need to apply changes (new data.png)
<img width="827" alt="new data" src="https://github.com/directus/directus/assets/152224102/09b19d57-9553-43e0-b1f4-68ba85d5edbf">

3. here is my flow, I can see in logs two items with the same time of creation (my flow.png)
<img width="1395" alt="my flow" src="https://github.com/directus/directus/assets/152224102/f6338bf8-168e-4111-9475-6ab85659282d">

4. read data - payload is the same for both items, but I expected that the first created task flow will write data before second task flow reads it. So Read data would be different

### Directus Version

v10.10.5

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
That is expected, as all items are created within the same action. You need to adjust your flow to handle multiple items.
Both, the "Read Data" and "Update Data" operations accept multiple items (IDs) as input.
