### ISSUE TITLE
Added unix socket option for Database connection

### ISSUE THREAD

**Issue by hal869** [directus/directus#2215]
Currently, PHP mysql extension does support sockets, Directus does not.

Policy often mandates using unix sockets, not TCP connections, for internal servers.

Requesting the addition of socket support for mariadb/mysql (et al) connections, similar to

> Added socket option for Redis #2153

, adding the possibility to specify the 'socket' => '/path/to/mysql.sock' option in the 'database' configuration. If given, it should ignore hostname and port and connect to mariadb/mysql using $client->connect($socket) instead.

cc @WellingGuzman , per request

**Comment by WellingGuzman** [comment]
Thanks @hal869,

The PDO object accepts socket connection, but directus use different naming for the configuration and that's why you started whitelisting the configuration, but the `unix_socket` wasn't one of them.

If someone wants to pick this issue and open a Pull Request, please let me know.

Reference: https://github.com/directus/api/blob/master/src/core/Directus/Application/CoreServicesProvider.php#L679-L689

**Comment by hal869** [comment]
confirming --

manually,
```
	mysql \
	 --socket='/var/run/mdb/mdb.sock' \
	 --user='test_user' \
	 --password='test_pass'
```

verifying socket connection
```
	mysqladmin processlist
		+----+-------------------+-----------+----+---------+------+--------------------------+------------------+----------+
		| Id | User              | Host      | db | Command | Time | State                    | Info             | Progress |
		+----+-------------------+-----------+----+---------+------+--------------------------+------------------+----------+
		| 1  | system user       |           |    | Daemon  |      | InnoDB purge coordinator |                  | 0.000    |
		| 4  | system user       |           |    | Daemon  |      | InnoDB purge worker      |                  | 0.000    |
		| 3  | system user       |           |    | Daemon  |      | InnoDB purge worker      |                  | 0.000    |
		| 2  | system user       |           |    | Daemon  |      | InnoDB purge worker      |                  | 0.000    |
		| 5  | system user       |           |    | Daemon  |      | InnoDB shutdown handler  |                  | 0.000    |
		| 24 | test_user         | localhost |    | Sleep   | 29   |                          |                  | 0.000    |
		| 27 | root              | localhost |    | Query   | 0    | Init                     | show processlist | 0.000    |
		+----+-------------------+-----------+----+---------+------+--------------------------+------------------+----------+
```

with
```
	cat api.php
		...
		'database' => [
			'type' => 'mysql',
	//		'host' => '127.0.0.1',
	//		'port' => 3306,
			'socket' => '/var/run/mdb/mdb.sock',
			'name' => 'directus',
			'username' => 'test_user',
			'password' => 'test_pass',
			'engine' => 'InnoDB',
			'charset' => 'utf8mb4'
		],
		...
```

nav to & login at

	https://test.example.com/directus/#/users/1

does, now, appear to connect/work.

o/ !
