### ISSUE TITLE
Data inconsistencies and permission problems

### ISSUE THREAD

**Issue by johannes-richter** [directus/directus#22157]
### Describe the Bug

We have a 3 Tier architecture with dev, test & prod instances. When I open the GUI of 2 or more of them, e.g. to make some tweaks, I get some funny behaviour. I have no idea how Directus works under the hood, but let me give you an example:
I have created a flow that will trigger a webhook event, it's a Deletion call to a dedicated url that fits the cluster =>
Dev Directus will trigger cache eviction for Dev Data and so on. The url has the word "dev" inside it. 
When I trigger that same flow on Test Directus, the GUI SHOWS me the correct url with "test" in it. But whenever that is triggered, it does not work. Inspecting the logs shows me that Directus has succesfully triggered the webhook, but it was sent to the "dev" url. It should be impossible to even exist inside Test Directus.

Another problem is, that the permissions get mixed up. When I log into prod and then open dev or test (even as admin), I suddenly cannot see any data anymore because of supposed access limitations.

I am now using Incognito Tab and not working parallel on any of the instances but it took me a while to figure out what was going on. I checked the database when I faced an issue and the tables looked right. Although I gotta admit I'm no expert in that field.

Sorry if this is a bit blurry, but these things happen randomly and I am not always sure how I trigger them explicitly. 

### To Reproduce

It's a bit of a hassle, but using multiple Directus instances at the same time and in the same browser will probably lead to some behaviour like the one I described. 

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
It seems like you're running the instances under the same parent domain. Please ensure you've configured all instances with the corresponding values [^1]:
- `PUBLIC_URL` should be explicitly set on all instances
- Correct cookie configs (default values should be fine)
- Correct DB / Redis hosts on the respective instances

Also please update and try with the latest version (currently [v10.10.5](https://github.com/directus/directus/releases/tag/v10.10.5)).

I'll close this issue for now, as it most likely related to wrong configuration / setup. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

[^1]: https://docs.directus.io/self-hosted/config-options.html

**Comment by johannes-richter** [comment]
Hi @paescuj 
Thanks for taking your time to review this.
I have checked the configuration, the PUBLIC_URL is already set explicitly, for all instances. I'm checking all the other config options now but any hint to where this problem could be routed is greatly appreciated
