### ISSUE TITLE
Select box text is cut off when Directus Minimal theme is selected

### ISSUE THREAD

**Issue by guycalledseven** [directus/directus#22160]
### Describe the Bug

Directus Minimal - cut off text:

![Directus Minimal - cut off](https://i.imgur.com/f8nO5mc.png)

Directus Default theme - everything ok:

![Directus Default theme - everything ok](https://i.imgur.com/ASLgCtQ.png)

### To Reproduce

Create collection, add O2M relation field to other collection. Make relation.

Change theme through Directus / Appearance from Directus Default to Directus Minimal.

### Directus Version

v10.10.5

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by formfcw** [comment]
This should be fixed with https://github.com/directus/directus/pull/21854
