### ISSUE TITLE
Deploying build-v7 with docker-compose shows permission error in browser

### ISSUE THREAD

**Issue by jellevdp** [directus/directus#2217]
## Version Info
  - Directus version and branch (Or commit hash):
build-v7
  - PHP version: n/a
  - MySQL version: n/a 
  - Web server: (Ex. Apache, nginx or IIS?) n/a
  - OS name and version: Ubuntu 16.04 (clean DGO droplet)

## Expected Behavior
After starting the build-v7 via docker-compose to see the application in the browser.

## Actual Behavior
Browser shows an error (see log below)

## Steps to Reproduce
 1. Setup clean instance of Ubuntu 16.04
 2. Install docker and docker-compose
 3. Clone directus with `git clone -b build-v7 https://github.com/directus/directus.git`
 4. Cd into directory and run `docker-compose up -d`
 5. Open <ip>:8080 in browser
  
## Schema Dump, Logs, or Screenshots

```Fatal error: Uncaught UnexpectedValueException: The stream or file "/var/www/html/logs/error.2018-10-24.log" could not be opened: failed to open stream: Permission denied in /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107 Stack trace: #0 /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array) #1 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\Handler\AbstractProcessingHandler->handle(Array) #2 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(616): Monolog\Logger->addRecord(400, Object(Directus\Exception\NotInstalledException), Array) #3 /var/www/html/src/core/Directus/Application/CoreServicesProvider.php(199): Monolog\Logger->error(Object(Directus\Exception\NotInstalledException)) #4 [internal function]: Directus\Application\CoreServicesProvider->Directus\Application\{closure}(Object(Directus\Exception\NotInstalledException)) #5 /var/www/html/src/core/Directus/Hook/Emitter.php in /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107```

PS. an additional section in https://docs.directus.io/install.html on how to install with docker would be great!

**Comment by rijkvanzanten** [comment]
It seems that the php user inside the docker's ubuntu doesn't have the right permissions to write the log files 🤔 

I don't know enough about Docker unfortunately to fix it.. @WoLfulus any thoughts?

**Comment by rijkvanzanten** [comment]
Moved this to https://github.com/directus/directus/issues/2217, since it's an issue in the APIs docker setup specifically
