### ISSUE TITLE
v7 - Unable to sort by M2M relation

### ISSUE THREAD

**Issue by shota-mentesh** [directus/directus#2218]
## Version Info
  - Directus version and branch (Or commit hash): **5d1e014b13c1b20502ef969b0fcb10b60566327e**
  - PHP version: **PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )**
  - MySQL version: **mysql  Ver 14.14 Distrib 5.7.24, for Linux (x86_64) using  EditLine wrapper**
  - Web server: (Ex. Apache, nginx or IIS?): **nginx version: nginx/1.14.0 (Ubuntu)**
  - OS name and version: **Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-33-generic x86_64)**

## Expected Behavior
When adding M2M relation you should be able to sort by number of related items.

## Actual Behavior
After sorting by M2M field you get an error saying that field is invalid and you no longer have access to collection's browse page because sorting is saved in **directus_collection_presets.view_query**.

## Steps to Reproduce
 1. Add M2M relation
 2. Make field visible on browse
 3. Try to sort by that field

## Schema Dump, Logs, or Screenshots
{"error":{"code":202,"message":"Invalid field \"favorites\""}}

**Comment by benhaynes** [comment]
I've moved this ticket to the API repo, we'll be closing all issues on `directus/directus` since it is just the "combined build".

https://github.com/directus/api/issues/521
