### ISSUE TITLE
GUI crashes after login with many users

### ISSUE THREAD

**Issue by tom-wmg** [directus/directus#2219]
- Directus version and branch (Or commit hash): 6.4.9 (but downwards also)
  - PHP version: 7.1
  - MySQL version: 5.6.38 
  - Web server: Apache 
  - OS name and version: Mac OS / MAMP 

## Expected Behavior

User can log in and view GUI

## Actual Behavior

Log in successful but blank screen of death. JS error.

## Steps to Reproduce

Upon creating new users via the GUI they cannot access the gui. Login works but then blank screen appears. 

We have 1700 directus_users. If I trim this number to below 1000 I can login fine with a newly created user. I suspect there's a limit somewhere on a API call which means GUI code is expecting data that doesn't exist. 

## Schema Dump, Logs, or Screenshots

(This is from a dev version as gives better debug than the production version)

EntriesModel.js?bust=ab5a935073324389db2e3444b5f1272753f7780f:272 Uncaught TypeError: Cannot create property 'avatar_file_id' on boolean 'false'
    at UsersModel.<anonymous> (EntriesModel.js?bust=ab5a935073324389db2e3444b5f1272753f7780f:272)
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (underscore.js?bust=ab5a935073324389db2e3444b5f1272753f7780f:78)
    at UsersModel.parseRelational (EntriesModel.js?bust=ab5a935073324389db2e3444b5f1272753f7780f:167)
    at UsersModel.parse (EntriesModel.js?bust=ab5a935073324389db2e3444b5f1272753f7780f:36)
    at UsersModel.Backbone.Model (backbone.js?bust=ab5a935073324389db2e3444b5f1272753f7780f:252)
    at UsersModel.EntriesModel [as constructor] (EntriesModel.js?bust=ab5a935073324389db2e3444b5f1272753f7780f:830)
    at new UsersModel (UsersModel.js?bust=ab5a935073324389db2e3444b5f1272753f7780f:126)
    at Array.<anonymous> (main.js:191)
    at j (jquery-1.11.0.js:3099)

**Comment by tom-wmg** [comment]
Yes, 6.4.9 (corrected now, sorry). 

The situation is this: I have an admin id (user ID 1) which can log in and display the gui fine. Another admin (user ID 1699) can log but the error previous described then occurs (gui doesn't display). If, however, I delete 700+ users in the middle of this range, this error then goes away. I tested how many users we could have before the bug manifests itself - this threshold seems to be 1000, hence my theory of this being a limit somewhere.

I didn't quite understand your comments but please let me know what else I can do to debug. 

Also, just to be clear error is pasted from a 6.4.5 dev (I think) as it's not the directus.min build, so I assume it gives more info. The symptoms are exactly the same in both versions.

**Comment by benhaynes** [comment]
Ahh, in that case it does sound like there is a `LIMIT 1000` being passed on one of the `directus_users` queries. I don't have time to look into this now, but a codebase search for `1000` or even `LIMIT 1000` (the latter might not work if parameterized) should help find and increase that limit.

**Comment by tom-wmg** [comment]
OK, amazing. Let me look at that first and I'll come back to you to tell you where it is for future reference.

**Comment by tom-wmg** [comment]
Et voila... Line 257 of /index.php - there's a limit within the getUsers function.

Thanks for that. I guess some better error handling is needed so it doesn't crash when there isn't the expected data within the object.

**Comment by benhaynes** [comment]
Awesome! Yeah, my guess is we added that to avoid the query from returning too many items and avoid pagination. If you don't see a slow-down I'd say up it to whatever you need!

I'll close this since it's "resolved" and on v6. Glad we got it figured out!

**Comment by tom-wmg** [comment]
Thanks for helping me figure it out.
