### ISSUE TITLE
Many to one relations does not support MEDIUMINT

### ISSUE THREAD

**Issue by dekyfin** [directus/directus#2220]
## Version Info
  - Directus version and branch (Or commit hash): v7.0.2 Master 
  - PHP version:  7.0
  - MySQL version: MariaDB 10.1.14
  - Web server:  Apache
  - OS name and version: Ubuntu 16.04.1 LTS

## Expected Behavior
The m2o interface should support MEDIUMINT data type just as it supports other numeric types. I also notice that the m2o support SMALL datatype which should be SMALLINT instead. 

## Actual Behavior
Trying to use the SMALL type results in an error

## Steps to Reproduce
 1. Assign a table field with MEDIUMINT data type
 2. Try to set up the field to use m2o interface

## Schema Dump, Logs, or Screenshots
![screenshot_20181026_152418](https://user-images.githubusercontent.com/8211774/47576194-640e0500-d933-11e8-8523-089670c1f235.png)

I'm submitting a pull request

**Comment by rijkvanzanten** [comment]
Hey @dekyfin! Based on the screenshot, this is actually Directus 6 (which we are currently sunsetting for v7).

> I'm submitting a pull request

Thanks 😄

**Comment by dekyfin** [comment]
@rijkvanzanten... Didn't know I was using v6. I downloaded and started trying it out today, so I figured it would be the latest. The Version & Updates section in the Settings is greyed-out, so I couldn't figure out the version

**Comment by rijkvanzanten** [comment]
Yeah sorry 'bout that. We _just_ soft-launched v7, so we're about to move it to the master branch as combined build. We ran into some small but important issues we needed to get rid off before we would make it the master branch

**Comment by dekyfin** [comment]
Looking forward to it
