### ISSUE TITLE
Filter on translation of nested entity in M2A relationship

### ISSUE THREAD

**Issue by LCorentinL** [directus/directus#22225]
### Describe the Request

Hello,

I've a problem with M2A relationship.
I've a data model with M2A relationship. In the nested entity i've translation field with text inside.

When i call my first entity, i want to filter the translation of the nested entity in the request.

Like this is an example return payload with my current request : 
```
{
 "data": [
        {
            "fieldOfMyFirstEntity": [
                   "testValue" : "test",
            ],
            "content": [
                {
                    "collection": "blog_text",
                    "item": {
                        "translations": [
                            {
                                "id": 1,
                                "blog_text_id": 1,
                                "languages_code": "en-US",
                                "title": "us example title",
                            },
                            {
                                "id": 2,
                                "blog_text_id": 1,
                                "languages_code": "fr-FR",
                                "title": "fr example title",
                            }
                        ]
                    }
                },
            ]
         }
     ]
}
```

As you can see i can filter my field of first entity like this : 
deep[fieldOfMyFirstEntity][_filter][testValue][_eq]=test

It's working fine.

But as soon as i want to filter the field of my nested collection like this : 
deep[content][item][translations][_filter][languages_code][_eq]=fr-FR

Then nothing is filtering, and all my languages are return.

I didnt find anything in documentation, so for now i right a workaround for removing all the non wanted languages in data return after the request, but it would be great if i can filter this directly in request.

### Maintainence Strategy

.

**Comment by br41nslug** [comment]
Looks like you're missing the `collection-scope` when querying the m2a relation.
https://docs.directus.io/reference/query.html#many-to-any-union-types

**Comment by br41nslug** [comment]
The same format holds for filtering `item:collection-scope`

**Comment by LCorentinL** [comment]
i tried this now : 
/items/blog?fields[]=content.item:blog_text.translations.*&filter[]=content.item:blog_text.translations.languages_code=fr-FR

So filtering like this : 
content.item:blog_text.translations.languages_code=fr-FR

But doesnt work : 
`{
    "errors": [
        {
            "message": "Invalid query. Invalid filter key \"0\" on \"blog\".",
            "extensions": {
                "code": "INVALID_QUERY",
                "reason": "Invalid filter key \"0\" on \"blog\""
            }
        }
    ]
}`

**Comment by br41nslug** [comment]
double check your filter you had the right format originally just not the complete/correct names but changed it in your last response for some reason. You can also use `json` formatting instead of url encoding up to you.

https://docs.directus.io/reference/query.html#filter

**Comment by LCorentinL** [comment]
filter[content][item:blog_text][translations][languages_code][_eq]
this doesnt work

**Comment by br41nslug** [comment]
`filter[something][item:collection][field][_eq]=value` this is the correct format and have confirmed it works. You'll have to double check your query against your data-model.

**Comment by LCorentinL** [comment]
Yeah it works for simple value in nested collection, but nor for translations, as i said filter[content][item:blog_text][translations][languages_code][_eq]=fr-FR return this  : 
`"data": [
        {
            "content": [
                {
                    "item": {
                        "translations": [
                            {
                                "id": 1,
                                "blog_text_id": 1,
                                "languages_code": "en-US",
                                "title": "Tout savoir sur la couleur",
                                "subtitle": "À chacune sa couleur",
                                "text": "Pour un changement capillaire radical ou subtile, les prestations de coloration proposées par les experts DESSANGE vous permettent de donner libre cours à vos envies et d’exprimer pleinement votre personnalité. La coloration permanente permet d’inscrire votre couleur dans la durée. L’expertise DESSANGE vous guidera dans le choix de la couleur qui vous ressemble le plus. Faites confiance au savoir-faire et à l’excellence DESSANGE pour une coloration profonde et naturelle."
                            },
                            {
                                "id": 2,
                                "blog_text_id": 1,
                                "languages_code": "fr-FR",
                                "title": "Tout savoir sur la couleur",
                                "subtitle": "À chacune sa couleur",
                                "text": "Pour un changement capillaire radical ou subtile, les prestations de coloration proposées par les experts DESSANGE vous permettent de donner libre cours à vos envies et d’exprimer pleinement votre personnalité. La coloration permanente permet d’inscrire votre couleur dans la durée. L’expertise DESSANGE vous guidera dans le choix de la couleur qui vous ressemble le plus. Faites confiance au savoir-faire et à l’excellence DESSANGE pour une coloration profonde et naturelle."
                            }
                        ]
                    }
                },`

**Comment by LCorentinL** [comment]
Yeah it works for simple value in nested collection, but not for translations, as i said this doesnt work : 
filter[content][item:blog_text][translations][languages_code][_eq]

It returns this : 
`"data": [
        {
            "content": [
                {
                    "item": {
                        "translations": [
                            {
                                "id": 1,
                                "blog_text_id": 1,
                                "languages_code": "en-US",
                                "title": "us title",
                            },
                            {
                                "id": 2,
                                "blog_text_id": 1,
                                "languages_code": "fr-FR",
                                "title": "fr title",
                            }
                        ]
                    }
                },`

**Comment by br41nslug** [comment]
That looks like the correct result if you're filtering against relations, you have an item there that contains a `item:blog_text` which contains a translation with language code 'FR'. That is what you're filtering for.

**Comment by LCorentinL** [comment]
Ok so i think i've been missunderstand.
I want to remove the us-US (or other language) form the result.
For simple request i made : deep[translations][_filter][languages_code][_eq]
Like this it only return the lanuages_code i choose.

**Comment by LCorentinL** [comment]
Ok working fine like this : deep[content][item:blog_text][translations][_filter][languages_code][_eq]
