### ISSUE TITLE
Issue with Sending Attachments via Directus Email Workflow

### ISSUE THREAD

**Issue by Mondherjendoubi** [directus/directus#22221]
### Describe the Improvement

Currently, the Directus email workflow allows users to send emails using templates; however, these templates are limited to text only, with no functionality to include attachments. This restriction can impede the workflow's versatility, as users cannot send important documents or media files alongside their templated messages. Enhancing this feature to support attachments would significantly broaden the utility of the email templates, making them more adaptable to varied communication needs.

**Comment by br41nslug** [comment]
This is more than a "tiny tweak" that can be implemented without discussion/questions. Please make a [feature request](https://github.com/directus/directus/discussions/new?category=feature-requests) for this :)
