### ISSUE TITLE
CACHE_AUTO_PURGE doesn't work in Data Studio

### ISSUE THREAD

**Issue by Pixizio** [directus/directus#22232]
### Describe the Bug

With CACHE_AUTO_PURGE enabled, creating / deleting / updating items doesn't get reflected in the admin panel.
Same goes for collections.

Fetching data from the API seems ok

### To Reproduce

- Create a new item
- Go back to the collection page
- The new item doesn't appear until the cache is cleared

- Create a new field in a collection
- The new field doesn't appear until the cache is cleared

(same thing when you update or delete a field / item)

### Directus Version

v10.10.6

### Hosting Strategy

Self-Hosted (Docker Image)

### Config file
CACHE_ENABLED=true
CACHE_STORE=redis
CACHE_AUTO_PURGE=true
CACHE_SCHEMA=false
REDIS=hidden

**Comment by rijkvanzanten** [comment]
cc @hanneskuettner
