### ISSUE TITLE
Containers getSchema throwing "hit infinite loop"

### ISSUE THREAD

**Issue by u12206050** [directus/directus#22243]
### Describe the Bug

When our containers are scaling we found many of them crashing, looking at the logs we found this error.

This started happening after updating from 10.9.3 to 10.10.7

<img width="617" alt="Screenshot 2024-04-18 at 13 23 25" 
src="https://github.com/directus/directus/assets/6641242/09ed4922-3397-44dc-97b5-8d11e6c7eae1">

### To Reproduce

Scale up to multiple containers running directus 10.10.7

### Directus Version

v10.0.7

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Can you try clearing Redis cache? this can be cause by lock in the cache that wasnt properly cleared

**Comment by u12206050** [comment]
From the code I notice there is no flow path for what has to happen after the MAX_ATTEMPTS has been reached. I can make a PR that fixes that, since it should probably fall back to attempt fetching the schema itself. In a single container the retry logic doesn't make sense either, since there could be multiple requests waiting on the getSchema, causing all of them to be very close together when timing out.

**Comment by u12206050** [comment]
I just realised that the schema isn't being cached to redis at all. Seems like this `await sharedSchemaCache.set('schema', schema);` is missing from the `setSchemaCache` function

**Comment by br41nslug** [comment]
Before diving into the code have you tried clearing the redis cache as asked? 

> Seems like this await sharedSchemaCache.set('schema', schema); is missing from the setSchemaCache function

Thats not missing i think as it's likely not supposed to do that, the actual schema is stored with `localSchemaCache` where `sharedSchemaCache` stores a hash to sync multiple instances.

**Comment by that1matt** [comment]
I had this exact same issue when upgrading to 10.10.5 for our development setup. I ended up removing the `CACHE_SYSTEM_TTL` env which was previously set to `CACHE_SYSTEM_TTL=100` and restarted the container, and haven't seen this issue since.

**Comment by rijkvanzanten** [comment]
This was resolved in https://github.com/directus/directus/pull/23141
