### ISSUE TITLE
[SKD]: readAssetBlob() TypeError: r2.blob is not a function

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#22244]
### Describe the Bug

When using the sdk to request an assetBlob I get an error:
```
TypeError: r2.blob is not a function
```

At first I thought that there might be an issue on my side, as I just switched to session based authentication, to not need to pass a token manually.
But when I use `readAssetArrayBuffer` instead and build a blob from the response it works just fine.

### To Reproduce

Request a file with the sdk and `readAssetBlob()` via rest

### Directus Version

10.10.5

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
I cannot reproduce this in the browser or in nodejs.

`Response.blob()` is part of the fetch specification so should be there unless you're using a `fetch` implementation that is not feature complete (or doesnt follow the spec).

https://developer.mozilla.org/en-US/docs/Web/API/Response#instance_methods

Happy to re-open if more information becomes available.

**Comment by Dominic-Marcelino** [comment]
Indeed, it's an issue with nuxt $fetch / ofetch. Have opened an issue there:
https://github.com/nuxt/nuxt/issues/26843

**Comment by br41nslug** [comment]
Does the nuxt ofetch allow you to do `$fetch.native()` I believe that would solve the compatibility issue?

**Comment by Dominic-Marcelino** [comment]
In general it would work by using the default `fetch` (nuxt doesn't overrides it by default), it's passed as a fetch instance to the directus-sdk initialisation.

In my case I'm using a [nuxt-directus-module](https://github.com/becem-gharbi/nuxt-directus) where it makes sense to use the nuxt ofetch and I'm pretty sure that it used to work 😅  For now I'll just wait what the nuxt team will response. As a workaround I use `readAssetArrayBuffer` and convert it to a blob (in case anybody else stumbles over this)
