### ISSUE TITLE
SDK - Missing _icontains operator in types

### ISSUE THREAD

**Issue by MarcosGin** [directus/directus#22249]
### Describe the Bug

Hi, I'm trying to use the **_icontains** operator, but it returns a typscript error because it doesn't exist.
However, you can send the request ignoring the typescript error and it works correctly.

<img width="1107" alt="image" src="https://github.com/directus/directus/assets/26859121/ae3c835d-27d2-42ad-a4d6-628471747eff">

### To Reproduce

```ts
 const data = await client.request(
    aggregate("cars_inventory", {
      query: {
        filter: {
          _and: matches.map((match) => ({
            excerpt: {
              _icontains: match,
            },
          })),
        },
        limit: 5,
      },
      aggregate: { count: "*" },
      groupBy: ["maker", "model", "trim", "year"],
    }),
  );
```

### Directus Version

^15.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by MarcosGin** [comment]
Type on package: 
<img width="977" alt="image" src="https://github.com/directus/directus/assets/26859121/cd18db01-a2ce-4504-82bb-b7e5c8b52aa5">

**Comment by MarcosGin** [comment]
@br41nslug any update about this ? thanks

**Comment by br41nslug** [comment]
@MarcosGin Issues on GitHub are public, you can see all the updates right here without needing to ask.
