### ISSUE TITLE
Incorrect version number in Directus 7.0.4

### ISSUE THREAD

**Issue by jameswill** [directus/directus#2225]
I have made manual installation on one of my test server and found that the file src\core\Directus\Application\Application.php contains version number as  "DIRECTUS_VERSION" = 2.0.4 

Can anyone let me know which is the correct version 7.0.4 or 2.0.4. If it is 7.0.4 then which file defines the correct version number.

**Comment by Mu9tafa-Online** [comment]
The app is separated from the API, so both versions are correct.

**Comment by jameswill** [comment]
If I want to fetch the version 7.0.4 then from where we can get that ?

**Comment by Mu9tafa-Online** [comment]
https://github.com/directus/directus/releases

**Comment by jameswill** [comment]
Not from the files. From the files itself..

In Directus v6.4.9 we were getting version from /api/core/Directus/Application/Application.php

**Comment by jameswill** [comment]
> 
> 
> Not from the files. From the files itself..
> 
> In Directus v6.4.9 we were getting version from /api/core/Directus/Application/Application.php

I mean I wanted version not from the github , but from the package files

**Comment by rijkvanzanten** [comment]
The app's version can be found here:
https://github.com/directus/app/blob/790d221059ef9e84ca29b77e9e7fc6f98b73799b/package.json#L3

Do you need to programmatically extract it from the combined build directus/directus? Right now package.json isn't distributed in the production builds, because it has no other use.

**Comment by jameswill** [comment]
Yes. I think it is feasible to provide version in every release.

Not just to me, to other users as well. How can anyone detects which version they are on ? Also if in case in future anyone wants to upgrade the existing 6.4.x installation how will one suppose to upgrade to latest version ?

**Comment by rijkvanzanten** [comment]
> How can anyone detects which version they are on? 

You can hover the little "Powered by Directs" message on the login screen 😁 

<img width="224" alt="image" src="https://user-images.githubusercontent.com/9141017/47653847-eb3fc080-db5f-11e8-858e-fdfe3c1d64cf.png">

> Also if in case in future anyone wants to upgrade the existing 6.4.x installation how will one suppose to upgrade to latest version?

6 to 7 is a complete rewrite and is a breaking change (hence the major version change). We haven't gotten around to creating a migration tool, but you should be able to copy paste your existing (non directus_*) tables from 6 into 7.
