### ISSUE TITLE
Logout activity

### ISSUE THREAD

**Issue by skmony** [directus/directus#22266]
### Describe the Improvement

As per compliance rules logout activity is also mandatory which is missing, in our activity logs we are using version 9.22.3. 

Please help us with the issue

**Comment by hanneskuettner** [comment]
Thanks for opening the issue! However this concern should be submitted as a feature request, so do kindly open a [new feature request](https://github.com/directus/directus/discussions/new?category=feature-requests) instead. I'll proceed to close this issue, thanks again!
