### ISSUE TITLE
Export functionality in role management 

### ISSUE THREAD

**Issue by skmony** [directus/directus#22267]
### Describe the Improvement

Hi Team, 

I need to implement an export feature for Directus users which will give us the following data of all users in a csv file

Kindly help me with the issue. We are using Directus 9.22.3

**Comment by hanneskuettner** [comment]
I don't know how it is in v9.22.3 since that version is now 1.5 years old. But in the current version you can export up to 1000 users as CSV at once in the user management section of the Data Studio.

As this concerns such an old version and the feature is present I'll close this issue.
