### ISSUE TITLE
Condition of dropdown field Data model isn't working

### ISSUE THREAD

**Issue by linfnn** [directus/directus#22289]
### Describe the Bug

I am currently developing a task management system for a team similar to Jira, where tasks are displayed in Kanban layout, categorized by the completion status of tasks including: Proposed, Todo, Doing, Paused, Done, Approved, Closed, and Canceled. The issue I am facing lies in the interface designed for staff; I do not want the columns for Approved, Closed, and Canceled statuses to appear. Therefore, I have utilized conditions for those fields as shown below, aiming to determine the role of the current logged-in user and display accordingly. However, it seems like the conditions are not working; all status columns still appear on the Task page unnecessarily. How can I address this issue?

this is condition i have written at Status field:
![condition_status](https://github.com/directus/directus/assets/123627538/3df5bacb-cba6-40a8-b2dc-e0b8a4287e55)

![interface_condition_status](https://github.com/directus/directus/assets/123627538/d66678d5-ef79-4921-9e36-a65a2738f8c9)

this is default value of status field:
![default_interface_status](https://github.com/directus/directus/assets/123627538/0506abd9-d570-45c2-9862-1972a96f7d2c)

i want when staff login, staff cann't see  the columns for Approved, Closed, and Canceled, but them still appear look like this below pic:
![staff_task_page](https://github.com/directus/directus/assets/123627538/ec1d3fb1-1fc4-481f-a460-8adca48683f1)

### To Reproduce

I hope Directus development team can review this issue and address it so that the conditions can function as intended. Thanks a lot.

### Directus Version

v10.10.5

### Hosting Strategy

Directus Cloud

**Comment by hanneskuettner** [comment]
Thanks for opening the issue! However this concern should be submitted as a feature request, so do kindly open a [new feature request](https://github.com/directus/directus/discussions/new?category=feature-requests) instead. 

The conditions you are setting up are only applicable to the dropdown interface but not to the Kanban layout and are not intended to work like this at the current point. Right now all possible options defined in the field configuration are shown. I could however see the possibility to add a filter to the Kanban groups.

An additional work around would be using a M2O relation and a separate `task_status` collection. This way the visible groups can be restricted using Access Control filters.

I'll proceed to close this issue, thanks again!
