### ISSUE TITLE
Need a feature to download details of a particular role

### ISSUE THREAD

**Issue by skmony** [directus/directus#22285]
### Describe the Improvement

We need to download the details of the role like createdAt, createdBy etc

**Comment by hanneskuettner** [comment]
Thanks for opening the issue! However this concern should be submitted as a feature request, so do kindly open a [new feature request](https://github.com/directus/directus/discussions/new?category=feature-requests) with some added details instead. I'll proceed to close this issue.

**Comment by br41nslug** [comment]
https://docs.directus.io/reference/system/roles.html#retrieve-a-role
