### ISSUE TITLE
Split directus in two image : Front-end & Back-end

### ISSUE THREAD

**Issue by nicolasbrieussel** [directus/directus#22296]
### Describe the Improvement

**Context**

We've been using Directus in production for two years now on a Kubernetes cluster. As our extension codebase grows, Directus now requires a significant amount of memory for startup (>800 MB RAM), while it only uses 200 MB at rest and increases to 300-350 MB under pressure.

The issue is that requiring 800 MB for startup is excessive. For stability concerns, I've chosen to set resource.limit.memory equal to resource.request.memory ([Here](https://home.robusta.dev/blog/kubernetes-memory-limit) is a pretty good article explaining why it's a good practice). This means I have a pod requesting 800 MB on the cluster but using much less, resulting in overprovisioning for no reason. And things get worse when the service needs to scale.

When Directus is used, it needs to scale rapidly in our use case. Just one frontend user can use up to 1 vCPU, forcing scaling events to occur if we don't want to impact our Quality of Service (QoS). Another 800 MB left.

Although it might not be relevant, here is a partial extract of our .env, just in case people could find ways to optimize the memory usage of our Directus instance 👀
[env.txt](https://github.com/directus/directus/files/15079297/env.txt)

**The tweak request** 

It would be sooo convenient to be able to split the frontend and the backend into different Docker images, which could scale independently. The load is primarily on the backend side - at least for our use case - but the backend does not need the modules, interfaces, and other UI extensions, just the backend ones. And fewer extensions mean less memory on startup. Which means saving money 💰

I don't feel like it would be complicated to propose an alternative where Directus is split into 2 Docker images, but I haven't touched Directus since v10 was released, so I might be wrong.

Ideally, I would love to be able to scale each extension independently, but I feel this one could be a headache, which is why I propose 'just' a backend/frontend split.

**Comment by br41nslug** [comment]
This is not a "tiny tweak" that can be implemented without discussion/RFC.
Please make a [feature request](https://github.com/directus/directus/discussions/new?category=feature-requests) instead so this can be properly discussed and evaluated.
