### ISSUE TITLE
Get Item by ID returns 403 for not existing keys

### ISSUE THREAD

**Issue by frekvent-szabolcs** [directus/directus#22306]
### Describe the Bug

Requests to collections using `GET /items/:collection/:id` throw `403 You don't have permission to access this.` errors if the requested `:id` does not exists.

![kép](https://github.com/directus/directus/assets/135596489/f3a4b126-5c5a-49a8-8527-96f7e093e00e)
![kép](https://github.com/directus/directus/assets/135596489/0510c420-3976-4d7c-a6ff-35b5ad8613e0)

I would expect HTTP 404 or 204 or 200 with the error mentioning there is no such a resource. 

### To Reproduce

Any collection I try behaves like this. 

### Directus Version

v10.10.7

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
This is intentional and expected behavior
