### ISSUE TITLE
Install/App Path: Error code 14

### ISSUE THREAD

**Issue by erkand-imeri** [directus/directus#2232]
After i install directus with the following git command:

git clone https://github.com/directus/directus.git

And i redirect from browser to directus/public folder i get the following error:

`{
"error": {
"code": 14,
"message": "This instance of the Directus API has not been configured properly. Read More at: https://github.com/directus"
}
}`

Does it need additional step for configuration, as far as i know it doesn't because 1 week ago i installed directus and everything was fine. Strangely now it doesn't work.

**Comment by shealavington** [comment]
Please try to append `/admin` after public.

**Comment by erkand-imeri** [comment]
It works. Thank you.

**Comment by rijkvanzanten** [comment]
I think option 1 is the best solution.

2 can't be done, as there's no guarantee the admin is going to be at /admin seeing it can be a stand alone install as well

**Comment by benhaynes** [comment]
I agree. I can make make this change tomorrow...

**Comment by rijkvanzanten** [comment]
@benhaynes you made the change for all API instances though. For people who installed the API from the non-combined bundle (eg directus/api), this information will be wrong..

**Comment by benhaynes** [comment]
Is it wrong though? I specifically wrote it to effectively say:

This API is not installed yet, so...
1. Use an App to install (for example, `/admin`)
2. Otherwise do it manually (Docs)

I was trying to use the `eg` as: _Hey, try this because it might be where your app is._ But you could use `directus.app` too, right? Any App should do.

**Comment by rijkvanzanten** [comment]
> This Directus API instance has not been configured. Install via **the Directus App (eg: /admin)** or read more about configuration at: https://docs.directus.io/install.html#configure

I'm just afraid that we'll see a "/admin doesn't exist issue on the API repo" soon.. But I guess there's no better solution at this point.

**Comment by benhaynes** [comment]
Yeah, I can make it more descriptive... I was just trying to keep it shorter.

```
This Directus API instance has not been configured. Install using a Directus App (eg: https://directus.app) or, if using the Directus Suite, try adding /admin to this URL. Read more about configuration at: https://docs.directus.io/install.html#configure
```
