### ISSUE TITLE
Incorrect extensions submodule loading selection between DEV and PROD

### ISSUE THREAD

**Issue by shasha79** [directus/directus#22329]
### Describe the Bug

https://github.com/directus/directus/blob/main/app/src/extensions.ts#L32

The bug is the reverse check for DEV - if it is true, the "directus-extensions" should be loaded from source, otherwise from submodule, e.g. the correct line should be:

customExtensions = import.meta.env.DEV
			? await import(/* @vite-ignore */ `${getRootPath()}extensions/sources/index.js`);
			: await import(/* @vite-ignore */ '@directus-extensions')

### To Reproduce

any run

### Directus Version

v10.10.7

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
No, the check is correct. It is used for dev mode (when running `pnpm dev` inside `/app`), where the extensions have to be loaded via virtual `@directus-extensions` module.
It seems that you have a different problem. In this is the case, please open a new issue with a detailed description. Thanks!
