### ISSUE TITLE
`v-input` behavior for numbers `> MAX_SAFE_INTEGER`

### ISSUE THREAD

**Issue by hanneskuettner** [directus/directus#22334]
### Describe the Bug

`<input type="number">` elements have some weird behavior for numbers larger than `Number.MAX_SAFE_INTEGER`.

This leads to problems inputting large numbers, for example into a `Big Integer` field. 

https://github.com/directus/directus/assets/4376726/b4c11e1d-ba42-4db6-8908-7e1e637a4469

### To Reproduce

- Have a field of type Big Integer
- Try typing in numbers larger than `MAX_SAFE_INTEGER`

### Directus Version

v10.10.7

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Could that be a duplicate of #20287? 👀
