### ISSUE TITLE
Disable emit in SDK updateItem method

### ISSUE THREAD

**Issue by jacob-israel-turner** [directus/directus#22341]
### Describe the Improvement

Hello!

I'm just getting started working with flows in Directus. It's been awesome to learn this project - great work team!

I'm using a webhook to do some data processing which I pass to another step in the flow to update an item. In the webhook I set the item's status to 'parsing', and I noticed it recursively sets off a bunch of update events.

The flow builder update card allows you to disable emitting update events. It would be nice to have the option of disabling emitting via the SDK as well!

Thanks!

**Comment by br41nslug** [comment]
Flow operations can do this since they are backend features (like the ItemsService's). This is not something we can do over the API.
