### ISSUE TITLE
Unnecesseary creation of another realted collection inide M2O relationship

### ISSUE THREAD

**Issue by lukagranevo** [directus/directus#22354]
### Describe the Bug

When creating a M2O connection inside a table. I creat a M2O key and then define the related collection. If the related collection is typed instead of selected, it'll show green text that that exact collection exists in the data model but it'll still create a new related collection without the last letter of the related collection. It seems that a creation of another related collection happens without the previous validation.
![Posnetek zaslona 2024-05-01 163121](https://github.com/directus/directus/assets/138971955/aa08657c-10a8-43e1-b668-877bb88a5c15)

### To Reproduce

Try manualy entering the value of an existing related collection instead of selecting it via dropdown.

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
This has been fixed in #22090, which has been released in [v10.10.6](https://github.com/directus/directus/releases/tag/v10.10.6).
