### ISSUE TITLE
Setting up translation interface

### ISSUE THREAD

**Issue by olinescu** [directus/directus#2235]
# Version Info
Directus version: master branch (7.0.5)
PHP version: PHP 7.2.10-0ubuntu0.18.04.1
MySQL version: 5.7.23-0ubuntu0.18.04.1
Web server: Apache/2.4.29 (Ubuntu)
OS name and version: Ubuntu 18.04.1 LTS

# Behavior
I tried to set up a collection ("tokens") using a related translation collection ("tokens_translations"). 
- In the "Editing Item" view the dropdown of "translations" lists the language.name elements. Selecting however switches to the language.code elements
- When I try to save I get a "Call to a member function getType() on null" error

# Schema Dump, Logs, or Screenshots
Table directus_relations:

![directus_relations](https://user-images.githubusercontent.com/44788834/48031058-46bb1100-e153-11e8-8c3f-22c28895ec5c.png)

Table directus_fields (custom rows):

![directus_fields](https://user-images.githubusercontent.com/44788834/48031060-46bb1100-e153-11e8-9fbb-92e4536850fa.png)

Directus Log on this:
`api[_].ERROR: Error: Call to a member function getType() on null in /var/www/api/src/core/Directus/Application/CoreServicesProvider.php:564
Stack trace:
#0 [internal function]: Directus\Application\CoreServicesProvider->Directus\Application\{closure}(Object(Directus\Hook\Payload))
#1 /var/www/api/src/core/Directus/Hook/Emitter.php(291): call_user_func_array(Object(Closure), Array)
#2 /var/www/api/src/core/Directus/Hook/Emitter.php(151): Directus\Hook\Emitter->executeListeners(Array, Array, 1)
#3 /var/www/api/src/core/Directus/Database/TableGateway/BaseTableGateway.php(1524): Directus\Hook\Emitter->apply('item.create:bef...', Array, Array)
#4 /var/www/api/src/core/Directus/Database/TableGateway/BaseTableGateway.php(774): Directus\Database\TableGateway\BaseTableGateway->applyHook('item.create:bef...', Array, Array)
#5 /var/www/api/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(264): Directus\Database\TableGateway\BaseTableGateway->executeInsert(Object(Zend\Db\Sql\Insert))
#6 /var/www/api/src/core/Directus/Database/TableGateway/BaseTableGateway.php(385): Zend\Db\TableGateway\AbstractTableGateway->insert(Array)
#7 /var/www/api/src/core/Directus/Database/TableGateway/BaseTableGateway.php(359): Directus\Database\TableGateway\BaseTableGateway->addRecordByArray(Array)
#8 /var/www/api/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(189): Directus\Database\TableGateway\BaseTableGateway->addOrUpdateRecordByArray(Array)
#9 /var/www/api/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(676): Directus\Database\TableGateway\RelationalTableGateway->manageRecordUpdate('tokens_translat...', Array, Array, Array, false, Array)
#10 /var/www/api/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(511): Directus\Database\TableGateway\RelationalTableGateway->addOrUpdateToManyRelationships(Object(Directus\Database\Schema\Object\Collection), Array, Array, false, Array)
#11 /var/www/api/src/core/Directus/Services/ItemsService.php(154): Directus\Database\TableGateway\RelationalTableGateway->updateRecord('1', Array, Array)
#12 /var/www/api/src/endpoints/Items.php(126): Directus\Services\ItemsService->update('tokens', '1', Array, Array)
#13 [internal function]: Directus\Api\Routes\Items->update(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Array)
#14 /var/www/api/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Array)
#15 /var/www/api/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Array)
#16 /var/www/api/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#17 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Slim\Route))
#18 /var/www/api/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\UserRateLimitMiddleware), Array)
#19 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Slim\Route))
#20 /var/www/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Slim\Route))
#21 /var/www/api/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(80): Slim\Route->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#22 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#23 /var/www/api/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\AuthenticationMiddleware), Array)
#24 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#25 /var/www/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#26 /var/www/api/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#27 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#28 /var/www/api/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\TableGatewayMiddleware), Array)
#29 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#30 /var/www/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#31 /var/www/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#32 /var/www/api/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#33 /var/www/api/vendor/slim/slim/Slim/App.php(515): Slim\Route->run(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#34 /var/www/api/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))`

**Comment by benhaynes** [comment]
There are a few known bugs with the translation interface that came up today... but I've drafted some initial Docs to explain setup:

https://docs.directus.io/app/admin/relationships.html#translations

**Comment by olinescu** [comment]
Thanks Ben, second listed (and main) problem solved! 

I did everything like you documented now - except setup step 6: The note "Language _Primary_ Key Field" and placeholder "_code_" (from my understanding) pointed to the field "_code_" in collection "languages" ... not the "Language _Foreign_ Key field" in my translation collection. 

I set the latter "Language Foreign Key field" in the translation collection to type "lang" - thus I understood it's tagged therefore can be found automatically. (However the same applies to the primary key of the languages collection, granted ;)

Concerning the first "problem" I listed. Question: This is intentionally? (See also attached picture, "zh" instead of "Chinese"). Quote:
> - In the "Editing Item" view the dropdown of "translations" lists the language.name elements. Selecting however switches to the language.code elements" 

Another small UI glitch in the translation field rendering: The size of a "Text-Area" type generated html textarea does not adhere to it's "field-wrapper" class div.

![bildschirmfoto 2018-11-07 um 12 36 33](https://user-images.githubusercontent.com/44788834/48129471-e37fca80-e289-11e8-9d08-07f45637ee87.png)

Thanks for your support!

**Comment by sebj54** [comment]
I had the same issue today too. After 2 hours of testing and reproducing the bug, I discovered this issue! 
I ended up with the same conclusions :)

Just so you know, the column in the `languages` table (or whatever you called it) has to be `name` or you won't see labels in the select field. I named it in French before and I had the same issue.

![image](https://user-images.githubusercontent.com/5880435/48368495-2c81b580-e6b4-11e8-9015-43552f043f1e.png)

I figured it out by checking this blog post (now outdated): https://medium.com/directus/multilingual-content-setup-in-directus-i18n-4f243f72e554.

Also, in this blog post, we can see a gif of the translation field: 

![image](https://user-images.githubusercontent.com/5880435/48368576-65218f00-e6b4-11e8-8908-b65f314a7fc1.png)

It looks like we can set a default language to be displayed when we edit or create a record, but I can't make it work. Each time I add a record, the translation field is disabled:

![image](https://user-images.githubusercontent.com/5880435/48368675-b29dfc00-e6b4-11e8-80f2-2fc3905a2a6e.png)

I had to add a field to the table (useless in my case) so I can save the record. After saving, I can edit the record and use the translation field:

![image](https://user-images.githubusercontent.com/5880435/48368832-1294a280-e6b5-11e8-8312-bb150fb10a84.png)

But, as you can see, there is a default option: `--`. How can we remove this default option? When I set a default value for the translation field, it is not saved and when I set a default value to the language code field of the associative, it is not taken in account.

Like said before, thanks for your support and your amazing work on this project :) 👍

**Comment by rijkvanzanten** [comment]
> But, as you can see, there is a default option: --. How can we remove this default option? 

It shouldn't be selectable. I changed the default `--` to `Choose Language...` to provide some more context.

> When I set a default value for the translation field, it is not saved

That's because the translation field is technically not a field at all. It's an alias that's stored only in directus_fields, not as a real column in the database. The default value for fields is saved in MySQLs default_value for a column, which explains why default values are ignored. Now that I'm thinking about this, the default value input should be hidden for O2M / translation type fields (added a new issue: https://github.com/directus/app/issues/1124).

I'll add another option for the default language!

**Comment by rijkvanzanten** [comment]
I've added a couple options which should make the translations interface way more useful!

I have two more questions for you @olinescu @sebj54:

1) Right now, on the listing overviews, the interface displays `3 Items`. I don't feel like that's the most useful thing to show. Do you guys have any idea on what could be a useful display there?

2) This translations interface has a full relational setup. There's a total of 3 collections needed, which results in a lot of setup. Alternatively, we cloud add a translations interface that saves everything as JSON in a single column. This means that there's virtually no setup, but it also means that we lose search and filtering on the actual translations.. (no more `lang=nl-NL`) in the API.. Is this something you think is worth pursuing, or is this something you guys would never use?

Thanks in advance! 😄

**Comment by benhaynes** [comment]
I like both of these ideas!

1. I think the most important (non-relational) info we can show is how many translations have been saved, so `3/3` looks good! We _won't_ know if the whole translation is "complete" (we're working on a different interface for that) but at least knowing that there's a record of each language is good.

2. I really like the idea of having an _option_ (not forcing it) to create the translation junction table for translations... or even all M2Ms. We might have a ticket for that already.

Thoughts on these two points, @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
Point 2 has been coming up a lot lately. Setting up relationships currently is a tedious process, and can be greatly optimized by taking away the need to setup the junction tables manually. @benhaynes we should probably open a new issue for it to have a centralized place to discuss it.

Point 1 sounds good to me! We do need to figure out when a language is "done" (eg when it's going from 0/3 to 1/3). Is 1 character in any field enough? What's going to be the rule there?

**Comment by sebj54** [comment]
We could keep the actual behavior (I guess just counting records on the association table) and just add languages count.
This is just changing the label but could be very helpful!

I'm not sure about extending this behavior to all M2M relations. This could be unnecessary if the total count is huge. This could also be a performance issue on large tables, am I right?
Maybe it can be optional? Enabled by default on a translation relation?

What about the possibility to display a label for each record? For example, if I have a `countries` table, I'd like to display the translated name in my language like this: _France, Spain, Germany_. We already have the possibility to set a display template for M2M relations, maybe this template can be used for this feature?

**Comment by rijkvanzanten** [comment]
> I'm not sure about extending this behavior to all M2M relations.

Nah I'm not too sure if it makes sense for M2M relations in general. "This user favorited 15 out of 350.000 movies"

> This could also be a performance issue on large tables, am I right?

This is a very good point, right now the total count of relational items aren't fetched, so this might introduce quite the performance hit. Not too sure how to implement this without introducing some real nasty delays..

> Maybe it can be optional? Enabled by default on a translation relation?

Yes, we should definitely add this as an option.

> What about the possibility to display a label for each record? 

I really like this idea! We could use the same display template option as the M2M. However, what language should it use to render the value? The current user's language?

**Comment by sebj54** [comment]
> However, what language should it use to render the value? The current user's language?
That makes sense to me! If the language does not exist, it could use the default language set in the translation interface

**Comment by benhaynes** [comment]
I know it's not translatable, but I like the idea of being able to say: `{{count}} Languages` for the templated interface output.
