### ISSUE TITLE
Websocket not triggering update event when using cron triggered flow

### ISSUE THREAD

**Issue by tomkyriacou64** [directus/directus#22358]
### Describe the Bug

Hey everyone,

I'm encountering an issue with websockets, im thinking its a Directus bug or possibly my workflow. I've subscribed to my websocket, and it functions properly when I manually click to save and update content. However, I have a flow set up to run every 10 minutes via cron, which updates the collection item (changing its status to active and inactive), but it doesn't seem to trigger the websocket.

The websocket works fine when I manually update the item, and the flow successfully updates the item, but it doesn't seem to trigger a websocket update event when it updates via the cron flow.

I've asked a few people and they reckon it might be a bug with Directus. Any help would be greatly appreciated!

![flow_1](https://github.com/directus/directus/assets/85596842/3df40aba-58a2-44dc-851d-53f5db468b55)

![flow_2](https://github.com/directus/directus/assets/85596842/af9fb49c-8331-476a-ae7f-b6ce3a425bba)

### To Reproduce

Set up a flow with a cron trigger.
Configure the flow to update an item within a collection.
Observe that the websocket fails to detect the update triggered by the cron job.

### Directus Version

v10.10.7

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
As discussed before emit events is not enabled in your update operation, so the events the websocket subscriptions listen to are not emitted
