### ISSUE TITLE
Connecting newrelic

### ISSUE THREAD

**Issue by boo-code** [directus/directus#22361]
Hi. Anyone has a solution how to integrate newrelic into the latest release of Directus?

I found only this solution, but I can't figure out how to make it running in Directus 10.

https://github.com/directus/directus/discussions/12626_

**Comment by hanneskuettner** [comment]
Hi! Thank you for opening this issue. However, I would like to point out that this is more a support question that should be asked in our [Community Discord](https://directus.chat/) as this is no bug . Thank you for understanding!

As a side-note, the solution in #12626 could probably still work, as the `startServer` function still exists and just moved to the `@directus/api` package.
