### ISSUE TITLE
Preselection Feature:

### ISSUE THREAD

**Issue by Lord-KalEl** [directus/directus#22367]
### Describe the Improvement

As I often find myself performing the same tasks when creating a new collection, it would be beneficial to make certain settings editable within the system collections and allow for preselections. This would enable users to customize the default settings according to their preferences.

For instance, I consistently utilize the "Status" field. By accessing the collection where this is configured, I could set a default value of "true" for preselection. Consequently, when the form appears prompting me to include the status field in the collection from the start, the checkbox would already be selected.

Alternatively, I never use ascending numerical IDs, opting instead for either generated UUIDs or strings. If I could modify this value in the system collections, it would significantly streamline the process of creating new collections.

It's important to note that this feature would be optional, and users who do not require it can choose not to utilize it.

This feature would provide the flexibility to make quick adjustments as needed, enhancing efficiency and user experience. It simply needs to be implemented.

Thank you for considering this suggestion.

**Comment by rijkvanzanten** [comment]
Heya! Thanks for your suggestion. I believe this is the same as a feature request we've seen in the past: https://github.com/directus/directus/discussions/19887.

It didn't quite garner enough community upvotes to make it into the fold back then, but you're welcome to open a new feature request to have it considered!
