### ISSUE TITLE
Upgrading guide from 6 to 7

### ISSUE THREAD

**Issue by andrejguran** [directus/directus#2237]
Hello,
Firstly I would like to thank the whole team for giving us a new version of directus that looks awesome. But I couldn't find any docs to upgrade from 6 to 7. The database structure changed quite a lot, is it somewhere documented how to migrate?

**Comment by shealavington** [comment]
> Legacy Upgrades
> **Directus 7 is a major release with significant breaking changes from previous versions.** Therefore there is no automated way to migrate your settings and configuration from v6 to v7. However, because Directus stores your content as pure SQL, that data is always portable between versions._

https://docs.directus.io/install.html#installing-the-directus-suite

**Comment by benhaynes** [comment]
Thanks @andrejguran – what @shealavington mentioned it accurate, and we don't have any migration scripts planned. There's would be no reliable way to update settings programmatically since they are so different.  However I will write some general steps for upgrading from v6 to help understand this process.

**Comment by andrejguran** [comment]
hey @benhaynes 
I didn't mean any automatic script. But at least list of breaking changes would help so we can upgrade to the newer version.
Thanks

**Comment by benhaynes** [comment]
Hopefully this helps anyone trying to upgrade. I wrote it pretty quickly so let me know if there is anything I missed and I'l add it.

https://docs.directus.io/legacy-upgrades.html

**Comment by atonse** [comment]
hi @benhaynes none of those links work. As someone that's eager to move our two Directus 6 sites over to 7 (mainly for the multi-tenancy), we would love to just know what to expect. If you could post working links to the legacy upgrade page, it would be appreciated. We too have limited resources, and would rather not spend days trying to hunt down subtle bugs.

**Comment by shealavington** [comment]
Here you go @atonse, simply typing "Lagacy Upgrades" into the docs search bar would've provided the result you're after. 💯 

https://docs.directus.io/advanced/legacy-upgrades.html
