### ISSUE TITLE
Creat new Collection Failure

### ISSUE THREAD

**Issue by Jerrygu113** [directus/directus#22383]
### Describe the Bug

When I try to creat a new collection, it shows page not found 
![image](https://github.com/directus/directus/assets/132370852/89a3b652-eb2d-4eb0-88dd-90144d30eeb0)
and when I want to try one more time it shows already exist, but didn't show in the home page.

### To Reproduce

1. create a collection call phone_Number_test
![image](https://github.com/directus/directus/assets/132370852/eb03b10c-0458-483b-aa96-de77c3b91662)
![image](https://github.com/directus/directus/assets/132370852/672b2e78-b9ec-416b-b24a-5d151723f737)

3. show error
![image](https://github.com/directus/directus/assets/132370852/39f7ea98-fb87-49f1-8dd3-0e56b06d28fe)

### Directus Version

v10.6.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
I don't have any problem creating an collection with the name you provided. 

For us to understand and pinpoint this issue, can you please provide the database vendor you are using, the URL of the page where you are seeing the 404, any logs that could surface the error (browser and/or API logs), any configuration values that might different from a standard installation of Directus, etc.

**Comment by hanneskuettner** [comment]
I'll proceed to close this now, as we do not have any info to go on. I'm happy to reopen as soon as more information becomes available.
