### ISSUE TITLE
Editing a collection item - an improvement for wide screens [low priority]

### ISSUE THREAD

**Issue by zawoj** [directus/directus#22387]
### Describe the Bug

The problem is only with styles for wide screens.
![image](https://github.com/directus/directus/assets/79516803/f8e058bf-2cd5-4744-9a3a-32092be2ebf1)
![image](https://github.com/directus/directus/assets/79516803/6b42a961-d3fc-4412-a8c9-47e079510d26)

After change styles:
from
`grid-template-columns: [start] minmax(0, var(--form-column-max-width)) [half] minmax(0, var(--form-column-max-width)) [full] 1fr [fill];`

to:
```grid-template-columns: [start] minmax(0, 1fr) [half] minmax(0, 1fr) [full]; ```

Everything looks nice:
![image](https://github.com/directus/directus/assets/79516803/7e69a5aa-ac8d-439b-9fb9-07822ac387cc)
![image](https://github.com/directus/directus/assets/79516803/3f0efede-f34d-4eda-be99-8a613a35e334)

### Directus Version

V10.10.7

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
Most interfaces (except for groups) already support setting the width to "Fill Width" which will stretch the field to the full available width. This includes the `translations` interface that you highlighted in your initial issue. 

<img width="268" alt="Screenshot 2024-05-06 at 10 47 58" src="https://github.com/directus/directus/assets/4376726/1c4a7adb-c191-419d-9c10-0f3d968936fd">

With "Fill Width" the translation interface will look just like you would expect it on large screens.

<img width="1097" alt="Screenshot 2024-05-06 at 10 47 05" src="https://github.com/directus/directus/assets/4376726/7b9b5032-9d70-4252-8988-8d94f0b580da">

As this seems like it should fulfill your needs I'll proceed to close this now, but if I missed something feel free to comment below.
