### ISSUE TITLE
Redis fails to store keys since 10.9.0  ( last worked in 10.8.2 )

### ISSUE THREAD

**Issue by kropsi** [directus/directus#22403]
### Describe the Bug

We had a working setup in `10.8.2` with Redis for caching, when we were to update to the latest version `10.10.7` we realised that Redis stopped working. After a longer investigation we can see that the problem since `10.9.0`.

We host it in Digitalocean with managed Redis

```yaml
REDIS: '<connection_string>'

CACHE_ENABLED: true 
CACHE_STATUS_HEADER: 'REDIS-Cache-Status'
CACHE_NAMESPACE: 'project-cache'

RATE_LIMITER_ENABLED: true
RATE_LIMITER_STORE: 'redis'

SYNCHRONIZATION_STORE: 'redis'
SYNCHRONIZATION_NAMESPACE: : 'project-sync'

MESSENGER_STORE: 'redis'
MESSENGER_NAMESPACE: 'project-messenger'
```
`connection_string` was configured with a public url to Redis database and with app platform as a trusted source. This setup works perfectly in `10.8.2`.

When we rolled out the `10.10.7` version we added the following:

```yaml
REDIS_ENABLED: true
```

From version `10.9.0` we experience that the only Key that gets added to Redis store is: `sets:namespace:project-cache_schema_shared:system-cache_schema_shared:hash`, so there is a connection, but all other keys are not added. We testet all the versions and flushed redis db for keys for each version and it works only in `10.8.2`. Maybe we oversee something, but the only change I can find in `10.9.0` is https://github.com/directus/directus/pull/21136/commits

### To Reproduce

1. Install version `10.9.0` or any later version with:
```yaml
REDIS_ENABLED: true
REDIS: '<connection_string>'

CACHE_ENABLED: true 
CACHE_NAMESPACE: 'project-cache'

RATE_LIMITER_ENABLED: true
RATE_LIMITER_STORE: 'redis'

SYNCHRONIZATION_STORE: 'redis'
SYNCHRONIZATION_NAMESPACE: : 'project-sync'

MESSENGER_STORE: 'redis'
MESSENGER_NAMESPACE: 'project-messenger'
```
2. Flush keys from redis in terminal
```bash
redli --tls -h <host> -a <pass> -p <port>
FLUSHDB
```
3. Run admin and access some collections
4. Check keys in terminals
```bash
KEYS *
```

### Directus Version

v10.10.7

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Could you try with quotes around the boolean values? E.g.
```yml
CACHE_ENABLED: 'true'
```

**Comment by kropsi** [comment]
Thank you @paescuj it resolved it. It is not obvious why boolean values must be specified as strings, can you elaborate on that? Is it safe to change all booleans to strings? Thank you in advance!

**Comment by hanneskuettner** [comment]
This is a know issue (#21744) that will be resolved in the upcoming release :)
