### ISSUE TITLE
Add a clearer disclaimer to the create a module extension docs how to enable the sidebar icon

### ISSUE THREAD

**Issue by steveHimself1397** [directus/directus#22400]
## Short description

I completely overread the already existing mention about the need to enable a new extension in the system settings.
I understood the existing explenation as making sure that the extension is enabled under Settings -> Extensions.

I was not aware that there is another location within the settings under "Settings -> Settings -> Modules" where you can enable the menu item.

This part of the docs should be improved. I'd be happy to provide a PR for this!

## Location in the docs

[https://docs.directus.io/extensions/modules.html](https://docs.directus.io/extensions/modules.html)

## Current state

A warning box is displayed at the end of the route component part of the page

## Proposed future state

Moving the sidebar handling to it's own small subsection to really make it clear how to handle this

### Maintainence Strategy

This change would only require maintenance in case the default state changes (if modules would be added to the sidebar by default) or if the location on where to add this changes.

**Comment by rijkvanzanten** [comment]
Great suggestion, thanks @steveHimself1397!
