### ISSUE TITLE
Revision will not be updated with ItemsService.updateByQuery (custom endpoint

### ISSUE THREAD

**Issue by Thomas-GBS** [directus/directus#22414]
### Describe the Bug

It looks like the revisions are written correctly in an update REST call (patch) with query, but not when I execute the exact same request in a custom endpoint.

### To Reproduce

If I invoke the following REST call:

```
PATCH {{host}}/items/events
Authorization: Bearer {{staticBearer}}
Content-Type: application/json

{
  "query": {
    "status": "archived"
  },
  "data": {
    "status": "approved"
  }
}
```

the revisions will be updated as you can see in the admin panel: 
<img width="296" alt="2024-05-07_11-54-38" src="https://github.com/directus/directus/assets/137383368/1afa82e8-ba6c-4550-af53-8f0ddde3dd5e">

I generated an endpoint that invokes the following code:

```
const entitiyItemService = new services.ItemsService("events", {schema: req.schema}) as ItemsService;
await entitiyItemService.updateByQuery(
	{
		filter: {
			status: "approved"
		}
	}, {status: 'archived', active: false }
);
```

The code updated the status from approved to archived: 
<img width="825" alt="2024-05-07_12-01-15" src="https://github.com/directus/directus/assets/137383368/d5485222-7fc6-4b8f-9653-2d77911bf395">

But the revision is empty. If I change the status by hand within the admin panel I can see, that 3 fields are updated:
<img width="165" alt="2024-05-07_12-03-16" src="https://github.com/directus/directus/assets/137383368/31e7ef6b-9167-4929-8605-8148fa30949c">
but after opening the review I only see one.
<img width="273" alt="2024-05-07_12-04-01" src="https://github.com/directus/directus/assets/137383368/c9bfea98-dda2-4526-a4bd-599568ea57f6">

What exactly is the problem here? In my opinion, it is not possible to reliably track what has been changed and when with the revision, it is inconsistent.

### Directus Version

v10.10.7

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
Looks like you forgot to pass along the `accountability` when initializing the service.

**Comment by Thomas-GBS** [comment]
Yes thats right. 
Why is it necessary to add the accountability to enable the revision? I would like to execute the request without user rights, I would like to execute the request with all rights. That's the reason why I skipped the accountability.

If I added the accountability the revision will be logged.

**Comment by br41nslug** [comment]
> Why is it necessary to add the accountability to enable the revision?

Because revisions are linked to the user that made the change as determined by accountability
