### ISSUE TITLE
Flow icon column is to small

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#22411]
### Describe the Bug

Some available icons like `text_select_move_forward_character` have more than 30 characters and therewith can't be stored as a flow icon.

As a solution a migration should be added which increases the column length.

### To Reproduce

Create a flow and select an icon with more than 30 characters (e.g `text_select_move_forward_character `)

### Directus Version

v10.10.7

### Hosting Strategy

Self-Hosted (Custom)

**Comment by hanneskuettner** [comment]
Indeed, the longest icon we have available is `signal_cellular_connected_no_internet_4_bar` with a whopping `43` characters.

![signal_cellular_connected_no_internet_4_bar_24dp_FILL0_wght400_GRAD0_opsz24 (1)](https://github.com/directus/directus/assets/4376726/b7df9918-7837-4b79-adbc-f75472e09ec6)

**Comment by paescuj** [comment]
Same for presets and insights 👍

**Comment by hanneskuettner** [comment]
Good call!
