### ISSUE TITLE
Directus Extension Reload Not Working For New Extension Way

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [directus/directus#22418]
### Describe the Bug

As others also mention: https://github.com/directus/directus/issues/20380 i am also facing the problem.
By creating in docker hosted directus i can create multiple hooks in my bundle and when i start they are shown. But as soon as i add another hook, and restart the directus docker, the newly added are not shown.

### To Reproduce

-

### Directus Version

v10.10.7

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by NilsBaumgartner1994** [comment]
And as https://github.com/directus/directus/issues/18721#issuecomment-1896116589 is for windows i am running docker on mac.

**Comment by hanneskuettner** [comment]
What you're actually facing is this issue #21946. A fix for this has just been merged and will be in the next release.
