### ISSUE TITLE
Directus-Extension Jssoup Bug

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [directus/directus#22417]
### Describe the Bug

After successfully building my extension and starting directus, my directus instance crashes loading the extension. The error shown was:

```
backend-directus-master-1  |     err: {
backend-directus-master-1  |       "type": "TypeError",
backend-directus-master-1  |       "message": "Cannot read properties of undefined (reading 'Tautologistics')",
backend-directus-master-1  |       "stack":
backend-directus-master-1  |           TypeError: Cannot read properties of undefined (reading 'Tautologistics')
```

I believe it is due to some error related with jssoup.

### To Reproduce

1. Create an extension
2. Create a hook extension with jssoup import:
```
import JSSoup from 'jssoup';
...
```
3. Install jssoup library
4. build the package
5. Start the server

### Directus Version

v10.10.7

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Please refer to the libraries docs. It looks like `jssoup` is a CJS library.
![image](https://github.com/directus/directus/assets/9389634/87e04e75-d41a-4e13-a607-5acce8a206d5)
https://github.com/Aghajari/JSSoup

**Comment by NilsBaumgartner1994** [comment]
@br41nslug perfect. Thank you very much
