### ISSUE TITLE
SSO Cookie Mode Breaks

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [directus/directus#22428]
### Describe the Bug

So when i am defining google as auth provider without specifing MODE or setting MODE to `session` everything works fine.
But changing the AUTH_GOOGLE_MODE to `cookie` doe not show up the provider anymore.

### To Reproduce

```
      AUTH_GOOGLE_DRIVER: "openid"
      AUTH_GOOGLE_MODE: "cookie" # Session is the default value, thats why we want to change it here
      AUTH_GOOGLE_CLIENT_ID: "${AUTH_GOOGLE_CLIENT_ID}"
      AUTH_GOOGLE_CLIENT_SECRET: "${AUTH_GOOGLE_CLIENT_SECRET}"
      AUTH_GOOGLE_ISSUER_URL: "https://accounts.google.com"
      AUTH_GOOGLE_IDENTIFIER_KEY: "email"
      AUTH_GOOGLE_ICON: "google"
      AUTH_GOOGLE_LABEL: "Google"
      AUTH_GOOGLE_ALLOW_PUBLIC_REGISTRATION: "true"
      AUTH_GOOGLE_DEFAULT_ROLE_ID: "${DEFAULT_ROLE_ID}"
      ```

### Directus Version

v10.11.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
This is intended, the Data Studio only works with `session` mode 👍

**Comment by NilsBaumgartner1994** [comment]
> This is intended, the Data Studio only works with `session` mode 👍

How can i then support SSO logins for my native apps?
I would have to choose either to support login on the Data Studio OR in my Native App?

**Comment by NilsBaumgartner1994** [comment]
@paescuj Also now the Enpoint for the Auth Providers also does not show them anymore. So how do i know as a client that such a provider is supported?

**Comment by br41nslug** [comment]
> Also now the Enpoint for the Auth Providers also does not show them anymore. So how do i know as a client that such a provider is supported?

The auth providers endpoint still returns all sso providers unless you're using the `?sessionOnly` flag

**Comment by NilsBaumgartner1994** [comment]
> > I would have to choose either to support login on the Data Studio OR in my Native App?
> 
> You could make that choice or update the native app to use the session token getting things back to the way you had them.
> 
> > Also now the Enpoint for the Auth Providers also does not show them anymore. So how do i know as a client that such a provider is supported?
> 
> The auth providers endpoint still returns all sso providers unless you're using the `?sessionOnly` flag

Okay sorry to bother you, but i am having now multiple questions:

Just to make sure: Setting it to "cookie" will result, that the SSO provider will also not be visible in the Data Studio?

1. A client then can't decide if he wants to login with the mode "cookie" or "session" as this is decided by the server.

2. It seems not possible (and intended) to the a Refresh Token out of the Session Token? So my users would need to relogin every 15 minutes, since the session token is then outdated?

3. Can confirm: Auth provider is shown by the client, when using "cookie" mode. Can i somehow get the refresh_token (in the backend) from the user_id or the session_token?

**Comment by br41nslug** [comment]
1. the client cant decide because the App only supports `session` as security improvement over the legacy `cookie` mode. So they would be deciding between being able to log in or not.
2. "It seems not possible (and intended) to the a Refresh Token out of the Session Token?" wording is a bit awkward but a session token acts as both access token and refresh token so you can refresh them as desired (the only change is that you will need to refresh before it expires since it is a single token)
3. In order to get a `cookie` mode refresh token you'll have to log in using `cookie` mode (you can't turn one type of token into another, without backend extensions)

**Comment by NilsBaumgartner1994** [comment]
> 1. the client cant decide because the App only supports `session` as security improvement over the legacy `cookie` mode. So they would be deciding between being able to log in or not.
> 
>     2. "It seems not possible (and intended) to the a Refresh Token out of the Session Token?" wording is a bit awkward but a session token acts as both access token and refresh token so you can refresh them as desired (the only change is that you will need to refresh before it expires since it is a single token)
> 
>     3. In order to get a `cookie` mode refresh token you'll have to log in using `cookie` mode (you can't turn one type of token into another, without backend extensions)

So that is nice, that we only need the session_token now and not also a refresh_token extra. And it is also nice, that we can just refresh that token.
Uff, okay that means a bit of changes in our app. But thanks.

How is the refresh now done? https://docs.directus.io/reference/authentication.html#refresh
The docs still state only the old method (refresh and access token).

>  acts as both access token and refresh token
Or is it really both?

**Comment by br41nslug** [comment]
> Or is it really both?

It really is both so if you were using cookie mode before the refresh endpoint flow works the same, do a request with the cookie then the cookie is replaced and expiry time returned.

**Comment by NilsBaumgartner1994** [comment]
> > Or is it really both?
> 
> It really is both so if you were using cookie mode before the refresh endpoint flow works the same, do a request with the cookie then the cookie is replaced and expiry time returned.

I have done using "json" before. So by using the `directus_session_token` this should work?

```
//console.log("authenticate_with_access_token set refresh_token to directus_access_token")
await ServerAPI.simpleAuthentificationStorage?.set({
	access_token: directus_access_token,
	refresh_token: directus_access_token,
	expires: null,
	expires_at: null,
});

console.log("CALL NOW THE REFRESH");
const result = await client.request(refresh('json', directus_access_token));
```

**Comment by NilsBaumgartner1994** [comment]
@br41nslug so why does the json refresh then not work with the session_token?

‘‘‘
//console.log("authenticate_with_access_token set refresh_token to directus_access_token")
await ServerAPI.simpleAuthentificationStorage?.set({
	access_token: directus_access_token,
	refresh_token: directus_access_token,
	expires: null,
	expires_at: null,
});

console.log("CALL NOW THE REFRESH");
const result = await client.request(refresh('json', directus_access_token));
‘‘‘

I am getting BAD REQUEST as error?

**Comment by NilsBaumgartner1994** [comment]
> because you arent using `session` mode, the session token "behaves" like a refresh token it is not identical to one.

Uff okay. So in need to call: client.refresh(‚session‘, session_token) ?
