### ISSUE TITLE
Session Mode Missing Doc Explanation

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [directus/directus#22435]
### Page

https://docs.directus.io/reference/authentication.html#login

### Describe the Inaccuracy

Okay, so first, sorry to bother with this topic. But as now the default moves to the new "sesseion" mode, alot of things are now making life hard.

The documentation is missing how to login with a directus_session_token. As for our native app users we would like to safe somewhere the credentials the question arises, how to safe the session token?

Also the question arises, how to refresh with a passed session token?

As the directus SDK client does not support SSO logins for native app users, we have no clue on how to give them access to the app, as we need somehow to pass the token to the users. It is also neccessary to pass the tokens in headers for getting images, as we cannot rely on cookies always.

**Comment by NilsBaumgartner1994** [comment]
As a workaround it would be nice to know how to generate an access_token and refresh_token out of the session token, as the session token is not the same.

**Comment by br41nslug** [comment]
> The documentation is missing how to login with a directus_session_token.

If you have a session token then you have already logged in. Logging in is what returns you the token for the mode used. That token is then used to authenticate to endpoints in the API.

> how to refresh with a passed session token?

This would be the same as any other endpoint. Do a request with the session cookie set in the headers. Since the browser handles cookie management for you this may require extra configuration/dependencies/etc for a native non-browser platform.

> As for our native app users we would like to safe somewhere the credentials the question arises, how to safe the session token?

I'm no expert in native mobile development but my first instinct would be that there are probably options to deal with cookies (considering thats a commonly used method of authentication on the web) however if they cant support cookies for some reason i would assume there'd be a platform specific secure form for storing credentials.

**Comment by NilsBaumgartner1994** [comment]
Well the problem is with native SSO login the following:

you are in the app, you open the browser for the SSO login and get authenticated in the browser. Now the Directus instances redirects the user to the mobile app. 
by that redirect the native app has no access to the cookie set. Therefore it is required to pass the token to the app via url.

So it is required to pass the token to the app somehow.

or I would need somehow to set and get the session token from within the app.

**Comment by NilsBaumgartner1994** [comment]
Could you otherwise tell me how to create/get access and refresh tokens within a custom endpoint from the session token?

this would work as a workaround.

**Comment by NilsBaumgartner1994** [comment]
Also using cookies would have the negative effect, when using a native app, the user would be logged out when the browser cache is resseted.

**Comment by NilsBaumgartner1994** [comment]
Created a temporary workaround to get refresh token for "session" auth providers: https://github.com/directus/directus/discussions/22427

**Comment by br41nslug** [comment]
> Well the problem is with native SSO login the following:
> 
> you are in the app, you open the browser for the SSO login and get authenticated in the browser. Now the Directus instances redirects the user to the mobile app. by that redirect the native app has no access to the cookie set. Therefore it is required to pass the token to the app via url.
> 
> So it is required to pass the token to the app somehow.
> 
> or I would need somehow to set and get the session token from within the app.

So quick curiosity in this native workflow, do you really need the session mode? It doesnt look like you are actually sharing the SSO login between the native app and the directus instance which would mean there is no real need to be "compatible with the browser data studio" 🤔 

Couldnt you open the browser directly to the SSO provider of your users choice (`/auth/login/:provider`) using the authentication mode that works best for you / you were using before?
https://docs.directus.io/reference/authentication.html#login-using-sso-providers

**Comment by NilsBaumgartner1994** [comment]
> > Well the problem is with native SSO login the following:
> > you are in the app, you open the browser for the SSO login and get authenticated in the browser. Now the Directus instances redirects the user to the mobile app. by that redirect the native app has no access to the cookie set. Therefore it is required to pass the token to the app via url.
> > So it is required to pass the token to the app somehow.
> > or I would need somehow to set and get the session token from within the app.
> 
> So quick curiosity in this native workflow, do you really need the session mode? It doesnt look like you are actually sharing the SSO login between the native app and the directus instance which would mean there is no real need to be "compatible with the browser data studio" 🤔
> 
> Couldnt you open the browser directly to the SSO provider of your users choice (`/auth/login/:provider`) using the authentication mode that works best for you / you were using before? https://docs.directus.io/reference/authentication.html#login-using-sso-providers

Well I am open in the native browser the SSO provider directly. But this causes that the app is left and the native browser is opened. This results in not being able from within the app to access the cookie.

export const ButtonAuthProvider = ( {provider}: SsoProvider) => {
	const isDebug = useIsDebug();

	const translation_log_in_with = useTranslation(TranslationKeys.sign_in_with);

	let providerName = provider.name;
	// capitalize first letter
	providerName = providerName.charAt(0).toUpperCase() + providerName.slice(1);

	const accessibilityLabel = translation_log_in_with+': '+providerName;
	let text = translation_log_in_with+': '+providerName;

	const url = ServerAPI.getUrlToProviderLogin(provider);

	const disabled = !isSsoLoginPossible();

	if (disabled) {
		text += '\n'
		text += 'Does not work on local ExpoGo'
	}

	if (isDebug) {
		text += '\n'
		text += 'Debug: URL: '+url
	}

	const onPress = () => {
		CommonSystemActionHelper.openExternalURL(url)
	}

	return (
	// @ts-ignore
		<ButtonAuthProviderCustom key={'ssoButton'+provider.name} disabled={disabled} accessibilityLabel={accessibilityLabel} onPress={onPress} icon_name={provider.name} text={text} />
	);
};

**Comment by br41nslug** [comment]
So i am a little confused now

> This results in not being able from within the app to access the cookie.

How were you doing this before? because before session mode was introduced you had to use `cookie` mode which also required you to deal with that refresh cookie. That specific flow of SSO redirect then receive a cookie which you can refresh hasnt changed in that respect only what the token in the cookie is capable of.

**Comment by NilsBaumgartner1994** [comment]
> So i am a little confused now
> 
> > This results in not being able from within the app to access the cookie.
> 
> How were you doing this before? because before session mode was introduced you had to use `cookie` mode which also required you to deal with that refresh cookie. That specific flow of SSO redirect then receive a cookie which you can refresh hasnt changed in that respect only what the token in the cookie is capable of.

Before I used the Json mode. And I let the user redirect to a custom Directus endpoint. This endpoint took the „refresh_token“ and added it to a redirect to the native app deep link

**Comment by NilsBaumgartner1994** [comment]
The current workaround uses the session mode and creates a new refresh token and adds this also to the redirect.

**Comment by br41nslug** [comment]
> Before I used the Json mode. And I let the user redirect to a custom Directus endpoint. This endpoint took the „refresh_token“ and added it to a redirect to the native app deep link

So then what was stopping you from carrying on with this original workflow? this authentication is unrelated to the Directus Studio authentication and specific to the native app as far as im reading

**Comment by NilsBaumgartner1994** [comment]
> > Before I used the Json mode. And I let the user redirect to a custom Directus endpoint. This endpoint took the „refresh_token“ and added it to a redirect to the native app deep link
> 
> So then what was stopping you from carrying on with this original workflow? this authentication is unrelated to the Directus Studio authentication and specific to the native app as far as im reading

You are totally correct. But regarding the increasing native app amount, it would be beneficial for Directus to also support these kind of native auth flows. For me I will stick to this workaround but I would love to see a support of this also as for SDK clients.

**Comment by arladmin** [comment]
@br41nslug 

> > It is also neccessary to pass the tokens in headers for getting images, as we cannot rely on cookies always.
>
> Cookies are passed as a header too! But there is a bunch of extra logic surrounding it in browsers dealing with domain security / js access / formatting the header / parsing response cookies and such.

I'm facing this issue as well. In the current use-case, i need to create URLs (including `access_token` parameter) to access the assets. But, without the token, it's now not possible.

And no, browsers don't allow access to the stored cookies using JS.

**Comment by NilsBaumgartner1994** [comment]
Yeah, that’s the point I already mentioned before. But I think security issues are higher. That’s why I created my workaround Beste Grüße,Nils BaumgartnerAm 17.07.2024 um 19:51 schrieb arladmin ***@***.***>:﻿
@br41nslug


It is also necessary to pass the tokens in headers for getting images, as we cannot rely on cookies always.

Cookies are passed as a header too! But there is a bunch of extra logic surrounding it in browsers dealing with domain security / js access / formatting the header / parsing response cookies and such.

I'm facing this issue as well. In the current use-case, i need to create URLs (including access_token parameter) to access the assets. But, without the token, it's now not possible.
And no, browsers don't allow access to the stored cookies using JS.

**Comment by rijkvanzanten** [comment]
The Directus studio itself now relies on the new session mode for authentication, as it's the safest way to handle auth in a web-browser environment. For authenticating from a native app, the previously available methods (json / cookie) are both still there and can be used. For logging in through SSO from a custom source, like a native app, the combo of the JSON auth mode + a custom redirect URL should do the trick. There's a lot of ground to make up in docs around using SSO from custom sources though, so this issue is a good reminder of that, tho I'm not quite sure I understand what the issue is in the original post.

**Comment by NilsBaumgartner1994** [comment]
I think the main issue is one of the following:- Native Example for SSO login- Providing resources in the docs at the login and auth. section on how to use create the trick for nativeBeste Grüße,Nils BaumgartnerAm 22.07.2024 um 22:33 schrieb Rijk van Zanten ***@***.***>:﻿
The Directus studio itself now relies on the new session mode for authentication, as it's the safest way to handle auth in a web-browser environment. For authenticating from a native app, the previously available methods (json / cookie) are both still there and can be used. For logging in through SSO from a custom source, like a native app, the combo of the JSON auth mode + a custom redirect URL should do the trick. There's a lot of ground to make up in docs around using SSO from custom sources though, so this issue is a good reminder of that, tho I'm not quite sure I understand what the issue is in the original post.

**Comment by rijkvanzanten** [comment]
That's what I thought, though @arladmin started mentioning it's a design flaw and breaking change/bug so I got confused 🤷🏻

**Comment by arladmin** [comment]
> That's what I thought, though @arladmin started mentioning it's a design flaw and breaking change/bug so I got confused 🤷🏻

@rijkvanzanten 

My main reason for terming this a 'design flaw' is: when using the 'session mode', in a web app, if i want to generate standalone URLs for assets (which require the use of the current 'auth token' as per Directus defined API specs; `/assets/<file-id>?access_token=<token>`), there seems to be no way (SDK/Browser APIs) to retrieve the 'token' to pass on to the assets endpoint.

Whereas, in the `cookie` mode, one is able to retrieve that 'token' simply using `client.getToken()`;

My current workaround is to create a Flow that reads the current token from the headers and then returns it, which i then append to the Asset URL. The expectation being: this should be doable at the Client itself, without the need for Flows/Custom Endpoints.

Do share if this is not the case or i'm missing something here!

**Comment by arladmin** [comment]
> That's what I thought, though @arladmin started mentioning it's a design flaw and breaking change/bug so I got confused 🤷🏻

@rijkvanzanten 

My main reason for terming this a 'design flaw' is: when using the 'session mode', in a web app, if i want to generate standalone URLs for assets (which require the use of the current 'auth token' as per Directus defined API specs; `/assets/<file-id>?access_token=<token>`), there seems to be no way (SDK/Browser APIs) to retrieve the 'token' to pass on to the assets endpoint.

---

In `session` mode `client.getToken()` returns ->
`null`


Whereas, in the `cookie` mode, `client.getToken()` returns a usable token -> 
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkOTIyNzRjLWExNTYtNGFmNy04NjdmLWExN2I2YWM3ZDg5ZiIsInJvbGUiOiJlZGMyZTg2My1lMmM0LTRlZTMtYmNiZC1kMDkwZGYyOTExZTEiLCJhcHBfYWNjZXNzIjp0cnVlLCJhZG1pbl9hY2Nlc3MiOmZhbHNlLCJpYXQiOjE3MjE3MDYwMjgsImV4cCI6MTcyMTcwNjkyOCwiaXNzIjoiZGlyZWN0dXMifQ.WIE5bQcygb7N86D4iw-oIw79er44UcnZp_4sSZmsUmI`

---

My current workaround is to create a Flow that reads the current token from the headers and then returns it, which i then append to the Asset URL. The expectation being: this should be doable at the Client itself, without the need for Flows/Custom Endpoints.

Do share if this is not the case or i'm missing something here!

**Comment by rijkvanzanten** [comment]
> My main reason for terming this a 'design flaw/bug' is: when using the 'session mode', in a web app, if i want to generate standalone URLs for assets (which require the use of the current 'auth token' as per Directus defined API specs; /assets/<file-id>?access_token=<token>), there seems to be no way (SDK/Browser APIs) to retrieve the 'token' to pass on to the assets endpoint.

The session token is a cookie, so when you open the assets endpoint in the browser it'll use that cookie session token. You don't have to include any tokens manually when you're already authenticated through a session token 👍🏻

**Comment by arladmin** [comment]
> > The session token is a cookie, so when you open the assets endpoint in the browser it'll use that cookie session token. You don't have to include any tokens manually when you're already authenticated through a session token 👍🏻 
>

@rijkvanzanten 

Yes, i do know that. Which i why i mentioned 'standalone URL', because one of the use-case is sharing those URLs. And once shared, they would then require the access token in the query parameters to work (in someone else's browser)

**Comment by rijkvanzanten** [comment]
Once you share an access token in a public readable URL, you have effectively leaked this user's access to the system. I don't fully understand your use case, but if you're sharing this image publicly for use on somebody else's browser or account, I'd just make the image public instead as there's no difference in access control security at that point.

**Comment by phazonoverload** [comment]
We are currently working on a complete overhaul of our docs - including platform, content, and structure. As that project is being worked on, I am going to close this issue as it's already acknowledged and handled within this work. We're expecting to launch it this fall.
