### ISSUE TITLE
Still unable to install on php 5.6

### ISSUE THREAD

**Issue by jameswill** [directus/directus#2243]
Hi,

I tried again with new version (7.0.6) on PHP 5.6 with CGI and API handler both modes. However installation does not gets completed.

Post filling database details, when I click on "Save" to complete the installation, the credentials are stored in api.php but it does not populate database.

**Comment by Mu9tafa-Online** [comment]
same issue here ( **using PHP 5.6.32** ) - But works fine on (**PHP 7.x** ).
@jameswill can't you just upgrade your PHP version to 7.x ?? I think nowadays most web server support it.

**Comment by jameswill** [comment]
> 
> 
> same issue here ( **using PHP 5.6.32** ) - But works fine on (**PHP 7.x** ).
> @jameswill can't you just upgrade your PHP version to 7.x ?? I think nowadays most web server support it.

Ofcourse I can upgrade to PHP 7.0. But as stated in requirement, it should run on 5.6, if not then they should update their documentation.

**Comment by rijkvanzanten** [comment]
Based on PHPs website, 5.x isn't officially supported anymore, so maybe it's time for Directus to drop support for it as well.

Seeing that security patches aren't being made for 5, I don't think it's that unfair to drop official directus support for it as well. Thoughts `@channel`? 

http://php.net/supported-versions.php

**Comment by benhaynes** [comment]
I had spoken with @WellingGuzman about this a few weeks ago. We were planning on dropping 5.6 support when it hit EOL in December. That said, I'm totally fine pulling the trigger a month early to avoid these unexpected issues.

**Comment by jameswill** [comment]
Hi, 

@benhaynes I request you to update the documentation as well. May I know any ETA for next release with this fix ?

@shealavington Yes, I was installing 7.0.7 package, and I had not manually updated api.php. I was trying to run its installer only.

**Comment by benhaynes** [comment]
Hey @jameswill — we've updated the Docs to let users know that we are only supporting PHP 7.1+ from this point on. Which is inline with PHP EOL in a few weeks:

http://php.net/supported-versions.php

**Comment by benhaynes** [comment]
Also, we have weekly releases on Fridays... though sometimes (like this past Wednesday) we push hotfixes mid-week.
