### ISSUE TITLE
`collection_func.count` is not working

### ISSUE THREAD

**Issue by abdonrd** [directus/directus#22443]
### Describe the Bug

From Directus v10.11.0, `collection_func.count` has stopped working.

With a GraphQL query like this (each battle has a list of videos):

```graphql
{
  battles {
    id
    videos_func { count }
  }
}
```

I get this error:

```json
{
  "errors": [
    {
      "message": "An unexpected error occurred.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

And if I remove the `videos_func { count }` it works.

It was working before update to v10.11.0.

### To Reproduce

Create a GraphqQL query with `_func.count`.

### Directus Version

v10.11.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
Heya, I've tried replicating this in v10.11.0 on my end, but so far my GraphQL queries seem to work just find for m2m and o2m relations.

Can you please share your collection setup, DB vendor and maybe even a stack trace you might be seeing in your Directus logs?

**Comment by abdonrd** [comment]
Right!

With this query:

```graphql
{
  battles {
    id
    videos_func { count }
  }
}
```

The error is:

> ERROR: select "battles"."id", (select count(*) from "videos" as "kaggh" left join "matchdays" as "jjvhv" on "videos"."matchday" = "jjvhv"."id" left join "battles" as "xcswd" on "videos"."battle" = "xcswd"."id" where "kaggh"."battle" = "battles"."id" and ((("jjvhv"."status" = 'published' or "xcswd"."status" = 'published')))) AS "videos_count" from "battles" where (("battles"."status" = $1)) order by "battles"."id" asc limit $2 - invalid reference to FROM-clause entry for table "videos"

Using PostgreSQL v15.

And the collection is (both matchday & video are M2O):

<img width="838" alt="Screenshot 2024-05-09 at 7 03 21 AM" src="https://github.com/directus/directus/assets/1007051/2659aa0c-4a65-4310-ada2-323b8c29851c">

**Comment by hanneskuettner** [comment]
Are you seeing this in the app or when querying the API? Because the DB query looks like some additional filters are applied? 
It would help if you could share the whole request. Thank you!

**Comment by abdonrd** [comment]
Just with the query:

`POST /graphql`

Payload:
```
{"query":"{\n  battles {\n    id\n    videos_func { count }\n  }\n}","variables":null}
```

**Comment by hanneskuettner** [comment]
Just to double check, you're not using any custom hooks or flows that might transform that query before it hits the DB?

**Comment by abdonrd** [comment]
Yes, no custom hooks / flows.

**Comment by hanneskuettner** [comment]
The missing piece to reproducing this were the `Item Permissions` for the `videos` collection. With this filter I can reproduce this error.

```json
{"_and":[{"_or":[{"battle":{"status":{"_eq":"published"}}},{"matchday":{"status":{"_eq":"published"}}}]}]}
```
