### ISSUE TITLE
s3 config doc need a simple fix

### ISSUE THREAD

**Issue by floux-digital** [directus/directus#22447]
### Describe the Request

Today I lost 3~4 hours trying to config S3 bucket as Storage for my directus installation following the documentation and doubting every time of myself, believing that I have doing somehting wrong.

Maybe I'm a dummie, but the fact is when I read a doc saying that exist a default value, I believe it. But, in this case, after 3~4 hours running accross the internet, I found a blessed video where the guy (after 1 hour trying to solve the same issue) make a simple and stupid comentary about the param STORAGE_<LOCATION>_ENDPOINT :"here not be my bucket endpoint?"

So, if have someone here that could update the documentation to help anothers, please, fix it. "s3.amazonaws.com" need to be "s3.{your_bucket_region}.amazonaws.com"

### Maintainence Strategy

Just follow possible changes from AWS Amazon.

**Comment by shubhusion** [comment]
assign this issue to me. I will make the changes

**Comment by rijkvanzanten** [comment]
As far as I'm aware, if the `BUCKET` and `REGION` variables are correctly set, `ENDPOINT` becomes optional. That being said, it doesn't hurt to add so I'll add in a little note 🙂
