### ISSUE TITLE
platform is failing

### ISSUE THREAD

**Issue by Edmcloughlin** [directus/directus#22449]
### Describe the Bug

I was looking to compare columns headers with the data contained within the header and set up 10+ columns which appears to have crashed the system. Is there a way to remove a column after adding it?

![502 error](https://github.com/directus/directus/assets/145032609/3e86e24c-fe8b-46a3-a7ec-1a30d10edf29)
![bundles columns](https://github.com/directus/directus/assets/145032609/94375277-bf9f-4d72-a3ee-50a72d9fd7c1)

### To Reproduce

add columns 

### Directus Version

v10

### Hosting Strategy

Directus Cloud

**Comment by paescuj** [comment]
When you click on the column, a menu appears. There you can remove the column by clicking on "Hide Field":
<img width="266" src="https://github.com/directus/directus/assets/5363448/73ff65ab-8f48-4fa8-8f52-6cdec121e6d6">

You could also adjust/reset the current layout via Settings -> Bookmarks where you can update or delete the corresponding Bookmark.

**Comment by Edmcloughlin** [comment]
got it. thanks.
u can close this out
