### ISSUE TITLE
Unable to manage data

### ISSUE THREAD

**Issue by michaelbriordan** [directus/directus#2244]
I have installed directus 7, to use with an existing dataset. But I can't "Manage" any data, without getting "Trouble processing request". 

What is the way around this? Can I, say, import something from SQL? Otherwise, what is the use of the app in the first place... I really don't understand.

**Comment by shealavington** [comment]
To answer your question, yes, you can use Directus with existing data.

But to answer the "trouble processing request" or "the way around this", I don't think there's enough information to know what's going wrong with your setup, did the install work, are you getting any browser console errors, anything logged that will help, what did you do step-by-step, what's the version of Directus, mysql etc? That way, hopefully someone else can try to replicate the issue or point out what's wrong.

**Comment by benhaynes** [comment]
Hey @michaelbriordan – this is an important issue and one that we'd like to make sure is resolved, but @shealavington is right... we need a bit more info to properly debug this. Could you provide us with some steps to reproduce or a schema.sql file we can use to replicate?

**Comment by WellingGuzman** [comment]
@michaelbriordan we need more info to debug this issue.

- What's your web server setup? are you using nginx or apache?
- Where are you getting that error?
- Can you check if there's logs in the api `logs` directory related to this error?
- Can you check the http request that respond with that error, if any? Example in the developer tools network tab.

**Comment by benhaynes** [comment]
I'll close this for now, @michaelbriordan feel free to post some more details on your setup so we can re-open and help out!
