### ISSUE TITLE
Show logs on docker image when using extensions hooks

### ISSUE THREAD

**Issue by kevinmamaqi** [directus/directus#22469]
### Describe the Bug

```
import { defineHook } from "@directus/extensions-sdk";

export default defineHook(({ filter }, { logger }) => {
  filter("items.create", async (payload, meta, context) => {
    try {
      console.error("Hook triggered: items.create");
      logger.info("Payload:", payload);
    } catch (error) {
      console.error("Error in items.create hook:", error);
    }
  });

  filter("auth.create", async (payload, meta, context) => {
    try {
      console.error("Hook triggered: items.create");
      logger.info("Payload:", payload);
    } catch (error) {
      console.error("Error in items.create hook:", error);
    }
  });

  filter("directus_users.create", async (payload, meta, context) => {
    try {
      console.error("Hook triggered: items.create");
      logger.info("Payload:", payload);
    } catch (error) {
      console.error("Error in items.create hook:", error);
    }
  });
});

```

Docker logs don't show logs for directus extensions hook. The code above never appears in the logs. Creating users via admin ui, and via graphql api using the create_users_item.

### To Reproduce

1. Use directus in a docker image.
2. Create extension under extensions, name hooks, using extensions sdk to execute. Choose typescript
3. Copy paste code above.
4. Try to create user via admin UI
5. Try to create user via graphql endpoint
6. Users are created.

Hook is not triggered.

### Directus Version

v10.11.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
As documented here https://docs.directus.io/extensions/hooks.html#available-events :
- `items.create` isnt applicable since users are a core collection
- `auth.create` is only applicable for SSO `[1] Available for ldap, oauth2, openid and saml driver.`
- `directus_users.create` is invalid and should be `users.create`

Update the code to hook into `users.create` instead and you'll see your logs fire.
