### ISSUE TITLE
Uploading svg file using the image field shows an unsupported media type

### ISSUE THREAD

**Issue by robinsonjohn** [directus/directus#22461]
### Describe the Bug

When uploading or displaying an already uploaded .svg file (may occur with other file types, I only tested with .svg) from the image field, an "unsupported media type" error is shown.

When uploading, the POST request to `/files` returns a 200 status code and does, in fact, upload correctly.

There seems to be no issue when uploading an .svg file directly from the file library.

This bug may have been introduced in https://github.com/directus/directus/pull/22307.

![Screenshot 2024-05-10 at 9 05 27 AM](https://github.com/directus/directus/assets/24327848/925c6cce-3f4b-413d-b502-14382151b394)

### To Reproduce

Upload an .svg image using the "image" field.

### Directus Version

v10.11.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by steveHimself1397** [comment]
Can confirm. I have the same issue in directus 10.11.0 running in a docker compose project. File is properly uploaded and available via the api but in the backend UI it displays the image error as mentioned by OP

**Comment by hanneskuettner** [comment]
It is indeed just a visual bug that is being addressed in an upcoming PR ✌️
