### ISSUE TITLE
Unable to connect to Azure Redis Cache after Directus v10.9.0 update

### ISSUE THREAD

**Issue by seyfi-ab** [directus/directus#22465]
### Describe the Bug

We have been successfully connecting to Azure Redis Cache using a connection string prior to version `10.9.0 `of Directus. However, after updating to version `10.9.0` or later, we are encountering connectivity issues and receiving the following error:

`2024-05-10T15:11:48.790243038Z [ioredis] Unhandled error event: Error: read ECONNRESET
2024-05-10T15:11:48.790313439Z at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
2024-05-10T15:11:48.792794373Z [ioredis] Unhandled error event: Error: read ECONNRESET
2024-05-10T15:11:48.792818773Z at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
2024-05-10T15:11:59.061673066Z [ioredis] Unhandled error event: Error: read ECONNRESET
2024-05-10T15:11:59.061722967Z at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
2024-05-10T15:12:01.936389042Z [ioredis] Unhandled error event: Error: read ECONNRESET
2024-05-10T15:12:01.936430843Z at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
`
It appears that the connection to Azure Redis Cache is being reset unexpectedly, resulting in the inability to establish a connection.

### To Reproduce

Update Directus to version  `10.9.0`  or later.
Attempt to connect to Azure Redis Cache using the same connection string as before.
Observe the ECONNRESET error in the logs.
Expected Behavior:
We expect Directus to successfully connect to Azure Redis Cache without encountering any connection reset errors, as it did before the update to version  `10.9.0` .

Additional Information:

We have verified that the connection string used is correct and has not changed.
The Azure Redis Cache instance is accessible and operational from other services and environments.
There have been no changes to the network configuration or Azure setup that would affect outbound connections.
Directus configuration settings related to Redis have not been altered.
This issue is consistently reproducible after updating to Directus version 9.0.0 or later.
Any assistance in resolving this issue would be greatly appreciated. Thank you!

### Directus Version

>=v `10.9.0` 

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Major version 9.0 was a complete rewrite in another language with another ecosystem so it's not unthinkable this may have broken for one reason or another however considering the `9.0.0` release was about 2.5 years ago could you reproduce this issue on the latest supported version? `10.11.0`

**Comment by seyfi-ab** [comment]
I apologize for the typo. We meant to use version `10.9.0` instead of `9.0.0`. We tried various versions, including the latest one, but Redis didn't work. The newest working version we found was `v10.8.3`. I fixed the description of the issue.

**Comment by seyfi-ab** [comment]
We were able to resolve the issue by implementing a change in the Redis URL format. Previously, we were using:

`[AZURE_REDIS_URL]:[PORT],password=[PASSWORD],ssl=True,abortConnect=False`

We have now transitioned to the following format, and it has reinstated the expected functionality:

`rediss://default:[PASSWORD]@[AZURE_REDIS_URL]:[PORT]`

I appreciate your support throughout this process, and I believe we can now consider this issue resolved. 

Thank you.

**Comment by rijkvanzanten** [comment]
Ah! Thanks for confirming 👍🏻
