### ISSUE TITLE
email templates path not working

### ISSUE THREAD

**Issue by sharkfin009** [directus/directus#22473]
### Describe the Bug

This seems like a really simple issue but it has me stuck. I have an endpoint extension that sends an email and it can't seem to read the template files. I am on the latest version and I did see this in breaking changes:
```

Moved Email Templates Out of Extensions
Email Templates are no longer considered an extension type as of this release. The templates extensions directory must be migrated.

Place email templates in the ./templates directory, or set the new location in the EMAIL_TEMPLATES_PATH environment variable.
```

I have done exactly this, trying the ./templates option and also trying setting a new location in the .env variable.

Error response when the endpoint receives a request :
directus  | DirectusError: Invalid payload. Template "enquiry" doesn't exist.
directus  |     at MailService.renderTemplate (file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_odrjvwlnfqlgyznoalys6xyvne/node_modules/@directus/api/dist/services/mail/index.js:65:19)
directus  |     at async MailService.send (file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_odrjvwlnfqlgyznoalys6xyvne/node_modules/@directus/api/dist/services/mail/index.js:48:20)

### To Reproduce

use the mailService.send method , passing in options including template.name where name is an existing .liquid filename inside ./templates

### Directus Version

10.11.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by sharkfin009** [comment]
hmm, i have forked the directus repo to try to reproduce the issue and I haven't succeeded, ie template being targetted fine.
But I wish I knew why it was happening in my project

**Comment by sharkfin009** [comment]
ah! I figured it out. Now that the templates directory is not inside the extensions directory, we need to obviously create a docker volume for it ... facepalm ;)

**Comment by PhilipZi** [comment]
dude how did you solve it? we have the same issue. Cant read access the custom-template.liquid

**Comment by PhilipZi** [comment]
we tried ./templates and extensions/templates and restart the docker

**Comment by sharkfin009** [comment]
hey! in your docker-compose.yml, your directus container must have this ( ie add the templates volume):
  volumes:
      - ./extensions:/directus/extensions
      - ./templates:/directus/templates

**Comment by sharkfin009** [comment]
pleasure! yes i did

**Comment by PhilipZi** [comment]
can you send me a structure of your base.liquid?

**Comment by PhilipZi** [comment]
![Bildschirmfoto 2024-05-15 um 11 29 06](https://github.com/directus/directus/assets/102238180/876e91d8-ce3e-4624-81fd-a14c8c6fbb45)
![Uploading Bildschirmfoto 2024-05-15 um 11.29.43.png…]()


look this is my structure for the folders
still not working

**Comment by PhilipZi** [comment]
![Bildschirmfoto 2024-05-15 um 11 29 43](https://github.com/directus/directus/assets/102238180/579403bb-1ba9-4059-b43b-9d63a36147b8)

**Comment by PhilipZi** [comment]
![Bildschirmfoto 2024-05-15 um 11 32 09](https://github.com/directus/directus/assets/102238180/0af29e4d-eda3-4e64-8622-a47f357339f6)

**Comment by PhilipZi** [comment]
![Bildschirmfoto 2024-05-15 um 11 32 37](https://github.com/directus/directus/assets/102238180/b79e380a-9725-496e-a73c-41c62d43383e)

thats my followup.template.liquid file... and it wont find or access this one. I have no idea anymore...

**Comment by PhilipZi** [comment]
i get this error 
 "name": "DirectusError",
      "extensions": {
        "reason": "Template \"followup-template\" doesn't exist"
      },
      "code": "INVALID_PAYLOAD",
      "status": 400

**Comment by sharkfin009** [comment]
hmm... you have rebuilt the docker-compose?

**Comment by sharkfin009** [comment]
I'm not useing a base template, but thats not relevant really. Are you on the latest version? 10.11.0?

**Comment by PhilipZi** [comment]
yes we did we found the error now! 
we also have to add this to the docker compose.yml 
![Bildschirmfoto 2024-05-15 um 11 35 56](https://github.com/directus/directus/assets/102238180/5418e30a-936b-4b2a-bd59-6bdcd2801519)

**Comment by PhilipZi** [comment]
working now!

**Comment by sharkfin009** [comment]
AH yes, forgot about that, Cool man glad its working. Always good to know I'm not the only one tearing my hair out about these things lol

**Comment by PhilipZi** [comment]
bro the docu is so bad about this... i am a big fan of directus but this stuff is really not fair to configure... actually so simple but if you dont know you dont know... 
happy we are a bit a head now! All the best and thanks for reaching out and you did help us!

**Comment by sharkfin009** [comment]
I know, the docs are behind the latest version in many places. But i can imagine it's really hard for the guys to keep the docs up to date along with all the issues. I did a docs PR for the added templates volume in the example docker-compose file, and it was merged in. Hoping to find time to do more docs PRs

**Comment by PhilipZi** [comment]
good job mate! your are right
