### ISSUE TITLE
Web UI: Unexpected Error: INVALID_TOKEN

### ISSUE THREAD

**Issue by ppom0** [directus/directus#22472]
### Describe the Bug

Hi!
First thanks for this amazing piece of software, Directus really is an awesome software!

So, I just upgraded from 10.8.2 to 10.11.0.

While loading the Web UI, all I have is an empty screen with this error in the middle:
![Unexpected error screen](https://github.com/directus/directus/assets/38916722/06b7bb3e-2568-4f76-a82a-30f2a62a9b92)

I could work around this by emptying the cache, but some users of the Directus instance are not comfortable with computers, so I'll tell them the necessary steps (and on Chrome, it's difficult to remove the site data only for a website).

Could the Web UI delete its tokens and present the login UI instead of crashing?

### To Reproduce

- Have a valid session on a Directus 10.8.2 instance
- Close the tab
- Upgrade Directus to 10.11.0
- Reopen a tab to this instance
- ![Unexpected error screen](https://github.com/directus/directus/assets/38916722/06b7bb3e-2568-4f76-a82a-30f2a62a9b92)

It did happen on instances served on a subpath of a domain. Another instance served directly at root didn't have this issue. Not sure if it's relevant though.

### Directus Version

v10.11.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by izoukhai** [comment]
Same issue here, exact same setup

**Comment by DanielBiegler** [comment]
Hi there! Thank you so much for the kind words (I forwarded them to the Team :heart: ) and thank you for opening this issue. We are aware of this and fixes are on the way for example [here](https://github.com/directus/directus/pull/22459) so I will close this issue.
