### ISSUE TITLE
Cannot NULL relation to directus_users

### ISSUE THREAD

**Issue by sergey-safarov** [directus/directus#22481]
### Describe the Bug

I have created a collection `tenant` and one filed have a relation to `directus_users`.
I have created one item of the `tenant` collection and set the reference field.
Saved item and then opened to `NULL` (clear) reference to the `directus_users`.
This operation failed with the error:
> [10:54:51] PATCH /items/tenant/b5cc5154-4411-4658-bb88-dbd399e4e731 500 8ms
[10:54:51.500] ERROR: Unexpected token ]
    err: {
      "type": "SyntaxError",
      "message": "Unexpected token ]",
      "stack":
          SyntaxError: Unexpected token ]
              at toPath (/directus/node_modules/.pnpm/micromustache@8.0.3/node_modules/micromustache/dist/micromustache.cjs:181:19)
              at Function.toPathCached [as cached] (/directus/node_modules/.pnpm/micromustache@8.0.3/node_modules/micromustache/dist/micromustache.cjs:198:18)
              at get (/directus/node_modules/.pnpm/micromustache@8.0.3/node_modules/micromustache/dist/micromustache.cjs:237:18)
              at renderMustache (file:///directus/node_modules/.pnpm/@directus+utils@file+packages+utils_vue@3.4.27_typescript@5.4.5_/node_modules/@directus/utils/dist/shared/index.js:159:21)
              at file:///directus/node_modules/.pnpm/@directus+utils@file+packages+utils_vue@3.4.27_typescript@5.4.5_/node_modules/@directus/utils/dist/shared/index.js:166:34
              at Array.map (<anonymous>)
              at renderMustache (file:///directus/node_modules/.pnpm/@directus+utils@file+packages+utils_vue@3.4.27_typescript@5.4.5_/node_modules/@directus/utils/dist/shared/index.js:166:17)
              at file:///directus/node_modules/.pnpm/@directus+utils@file+packages+utils_vue@3.4.27_typescript@5.4.5_/node_modules/@directus/utils/dist/shared/index.js:142:57
              at Array.map (<anonymous>)
              at applyOptionsData (file:///directus/node_modules/.pnpm/@directus+utils@file+packages+utils_vue@3.4.27_typescript@5.4.5_/node_modules/@directus/utils/dist/shared/index.js:142:29)
    }
 

### To Reproduce

described above

### Directus Version

v10.11.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

used docker image `postgis/postgis:13-master`

**Comment by hanneskuettner** [comment]
Do you have any flows that hook into item updates?

**Comment by sergey-safarov** [comment]
Sorry for bothering you.
It looks like this because I have attached the filter flow which returns a limited dataset. I have disabled flow execution and the error disappeared.

**Comment by sergey-safarov** [comment]
I have rechecked the issue and it looks like it is related to the `Read Data` step.
I have created the flow on the screenshot.
![image](https://github.com/directus/directus/assets/2562241/0e59a464-fdfd-4745-a5d3-b882349a3319).
On the "Run Script" configured
```
module.exports = async function (data) {
	console.log(data);

    return data.$trigger.payload;
};
```
If you execute this flow, then the error will be reproduced.
If you delete `Read Data` step from the flow then JSON object will be printed into the log.

**Comment by hanneskuettner** [comment]
That's probably because you have an invalid id variable string (`{{ $trigger.keys[] }}`). You need to drop the `[]`.
Closing again, as this is a setup / flow problem and not a Directus Core problem. If you have any further questions to this don't hesitate to ask on our [Community Discord Server](https://directus.chat).

**Comment by sergey-safarov** [comment]
Thanks for the explanation.
I have tested `{{ $trigger.keys }}` and this does work. I got error message in the console
> [12:54:45.930] ERROR: select "tenant"."id", "tenant"."user_created", "tenant"."date_created", "tenant"."user_updated", "tenant"."date_updated", "tenant"."name", "tenant"."status", "tenant"."user_owner", "tenant"."company_owner" from "tenant" where "tenant"."id" = $1 order by "tenant"."id" asc limit $2 - invalid input syntax for type uuid: "{"b5cc5154-4411-4658-bb88-dbd399e4e731"}"
    err: {
      "type": "DatabaseError",
      "message": "select \"tenant\".\"id\", \"tenant\".\"user_created\", \"tenant\".\"date_created\", \"tenant\".\"user_updated\", \"tenant\".\"date_updated\", \"tenant\".\"name\", \"tenant\".\"status\", \"tenant\".\"user_owner\", \"tenant\".\"company_owner\" from \"tenant\" where \"tenant\".\"id\" = $1 order by \"tenant\".\"id\" asc limit $2 - invalid input syntax for type uuid: \"{\"b5cc5154-4411-4658-bb88-dbd399e4e731\"}\"",
      "stack":
>          
>      "length": 135,
>      "name": "error",
>      "severity": "ERROR",
>      "code": "22P02",
>      "file": "uuid.c",
>      "line": "134",
>      "routine": "string_to_uuid"
>    }

It looks like ID compared with json object
>  invalid input syntax for type uuid: \"{\"b5cc5154-4411-4658-bb88-dbd399e4e731\"}\"",

Then I tried to use `{{ $trigger.keys[0] }}` and in this case, flow works as expected.

Question.
Should selectors `{{ $trigger.keys[0] }}` and `{{ $trigger.keys[] }}` works both?
