### ISSUE TITLE
multiple Flow runs in multi-instance PM2

### ISSUE THREAD

**Issue by javargasm** [directus/directus#22489]
### Describe the Bug

By increasing the value of the PM2_INSTANCES environment variable from 1 to 2, all flows regardless of the trigger are executed twice

<img width="1318" alt="Captura de pantalla 2024-05-14 a la(s) 8 57 28 a  m" src="https://github.com/directus/directus/assets/50146841/38e2de72-1ad2-48e2-8712-ce29a7f9fee1">

### To Reproduce

PM2_INSTANCES = 2 and create Flow CRON

### Directus Version

v10.10.7

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 16

**Comment by br41nslug** [comment]
Have you configured redis synchronization? https://docs.directus.io/self-hosted/config-options.html#synchronization

**Comment by javargasm** [comment]
> Have you configured redis synchronization? https://docs.directus.io/self-hosted/config-options.html#synchronization

SYNCHRONIZATION_STORE: redis

Thank you very much, configuring redis is executed only once
