### ISSUE TITLE
Unable to boot up a mysql instance of Directus

### ISSUE THREAD

**Issue by Noprop** [directus/directus#22490]
### Describe the Bug

Running on Mac M1 with Docker version 25.0.1, build 29cf629

Directus always tries to connect before the database is initialized and thus can never boot up; even after container restarts.

### To Reproduce

Create a fresh folder, create a docker-compose.yml and run this:

```version: "3"
services:
  database:
    platform: linux/amd64
    image: mysql:8.0
    volumes:
      - ./data/database:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "directus_db"
      MYSQL_USER: "directus"
      MYSQL_PASSWORD: "directus"

  directus:
    image: directus/directus:10.11.0
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/public/directus/uploads
    depends_on:
      - database
    environment:
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"

      DB_CLIENT: "mysql"
      DB_HOST: "database"
      DB_PORT: "3306"
      DB_DATABASE: "directus_db"
      DB_USER: "directus"
      DB_PASSWORD: "directus"

      ADMIN_EMAIL: "email@gmail.com"
      ADMIN_PASSWORD: "admin"
```

### Directus Version

v10.11.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

MySQL 8.0

**Comment by br41nslug** [comment]
In order to wait for the database docker to be ready you'll have to add a health check 
https://stackoverflow.com/questions/42567475/docker-compose-check-if-mysql-connection-is-ready

Closing this issue for now as this can be solved using docker 😄
