### ISSUE TITLE
Upload CSV File Error

### ISSUE THREAD

**Issue by Jerrygu113** [directus/directus#22504]
### Describe the Bug

When I try to upload something on Directus with CSV file, it only shows blank in the system.

### To Reproduce

1.Create the csv file.
[Test upload 2.csv](https://github.com/directus/directus/files/15325958/Test.upload.2.csv)
2. try to upload to Directus collection with upload function
3. Show blank info

![image](https://github.com/directus/directus/assets/132370852/b6ad68a0-c80a-4151-9d06-ddb8c4491ffe)

### Directus Version

v10.6.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
The provided CSV does not look to be correctly formatted. The field names / headers / first row seems to have some unintended whitespacing resulting in `" input1 "` not being equal to `"input1"`.
[Test.upload.2.csv](https://github.com/directus/directus/files/15335274/Test.upload.2.csv)
