### ISSUE TITLE
Add docs for updateBatch methods

### ISSUE THREAD

**Issue by alexvdvalk** [directus/directus#22516]
### Describe the Request

There are alternative update methods which allow users to update an array of objects in a single request. Those aren't currently documented for either the API or the SDK.

Corresponding issue can be found [here](https://github.com/directus/directus/issues/22510)

### Maintenance Strategy

Limited maintenance required. It's a core API that is available in Directus today.

**Comment by rijkvanzanten** [comment]
Closed in favor of https://github.com/directus/directus/issues/22982
