### ISSUE TITLE
V-drawer showing up behind the manual workflow run confirmation dialog

### ISSUE THREAD

**Issue by baguse** [directus/directus#22521]
### Describe the Bug

![image](https://github.com/directus/directus/assets/36828138/3b5a9b38-6f55-43a5-8712-33e4262f5cef)

The V-drawer to select an item showing up behind the confirmation dialog of Workflow run

### To Reproduce

Run a manual workflow that has a `Collection Dropdown interface`.
The case is on the Agency os `Create Project` workflow

### Directus Version

v10.9.0

### Hosting Strategy

Self-Hosted (Docker Image)

```[tasklist]
### Tasks
- [ ] Check the z-index of the v-dialog
```

**Comment by hanneskuettner** [comment]
Can you please update to the most recent version of Directus (v10.11.0), it looks like it has been fixed in the meantime.
