### ISSUE TITLE
The data volume of active and revisions will become larger and larger

### ISSUE THREAD

**Issue by GanHuaLin** [directus/directus#22524]
### Describe the Bug

How do you clear active and revisions from a certain time ago。
I hope you can add clear active and revisions to the Settings, because I don't know how to do it manually。

### To Reproduce

I hope you can add clear active and revisions to the Settings, because I don't know how to do it manually。

### Directus Version

10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by GanHuaLin** [comment]
What if I want to clear it manually?

**Comment by br41nslug** [comment]
You can use Flows or extensions to clear these tables manually or follow the appropriate work attempting to resolve this https://github.com/directus/directus/issues/17894
