### ISSUE TITLE
Directus Paging issue

### ISSUE THREAD

**Issue by PrakashK775** [directus/directus#22527]
### Describe the Bug

Facing issue for pagination controls, Attached SS and screen recording for the same

![Screenshot 2024-05-21 at 12 47 06 PM](https://github.com/directus/directus/assets/145122655/df1e7829-5809-40d6-9460-d8de20c0606a)

https://github.com/directus/directus/assets/145122655/74ff1d86-72e2-4147-9f2d-45abc48def2e

### To Reproduce

N/A

### Directus Version

v10.11.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
Can you please add additional information on what you think the issue is here, I can see multiple and would like to clarify what you're actually reporting. Are there any other issues apart from the obvious misalignment of the page button?

**Comment by br41nslug** [comment]
And are you using any theming and/or custom css?

**Comment by PrakashK775** [comment]
@hanneskuettner 
I have a dataset collection in my project which includes a field for files (images). There are over 50+ images uploaded in this collection. When I attempt to navigate through the pages using the pagination controls, I encounter the following issues:
**Pagination Stops Working After Page 2:**
When I try to move to the next page (page 3 and beyond), the pagination controls fail to function correctly, and I cannot access images beyond page 2.
**Tab View Functionality:**
Interestingly, when I switch to the tab view, the pagination seems to work, and I can navigate through all the images without any issues. This suggests that the problem might be specific to the pagination controls in the default view.

**Comment by hanneskuettner** [comment]
Anything you're seeing in your browser logs?

**Comment by PrakashK775** [comment]
@br41nslug : Not used any custom theming and/or css
@hanneskuettner Browser logs
![Screenshot 2024-05-22 at 5 33 31 PM](https://github.com/directus/directus/assets/145122655/bf13be86-5162-4f32-9ca6-09c6c78719ac)
