### ISSUE TITLE
Error when opening the media-library

### ISSUE THREAD

**Issue by rene-qore** [directus/directus#22528]
### Describe the Bug

Hi guys, I am facing a wierd issue with the media-library, when trying to insert an image from the media-library anywhere, I get a "Unexpected error" message. I am running Directus version 10.10.7.

The console log gives the following error:
`TypeError: Cannot read properties of null (reading 'length') at Proxy.<anonymous> (index.CIHrN2LG.entry.js:3384:59435)`

Video of issue: https://www.loom.com/share/be581a98477446a8a38422cfe8367782?sid=7c408d7e-3ef8-4517-9572-a0b6984fe693

### To Reproduce

I am not sure how you could reproduce this. Please see video. Application is hosted on [StackHero](https://www.stackhero.io/)

### Directus Version

10.10.7

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
I'm able to reproduce this. For me it happens if an image fails loading, e.g. if the actual file has been removed from disk.
You can follow #22530 to see when the fix lands.

**Comment by rene-qore** [comment]
Will this fix be shipped with a new version? For now I'll check for the missing image in the liberary. Thanks!
