### ISSUE TITLE
TypeError Cannot read properties of undefined (reading 'primary')

### ISSUE THREAD

**Issue by divick-vama** [directus/directus#22545]
### Describe the Bug

I am using the latest (10.10.7) version of Directus with postgres 11.9.3 and and for some reason suddenly when a user logs in, I get the following error:

```
[10:08:55] POST /auth/login 500 257ms
[10:08:55.806] ERROR: Cannot read properties of undefined (reading 'primary')
err: {
"type": "TypeError",
"message": "Cannot read properties of undefined (reading 'primary')",
"stack":
TypeError: Cannot read properties of undefined (reading 'primary')
at ActivityService.createOne (file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_n4quapn3gjscmyyd32fo3dq3em/node_modules/@directus/api/dist/services/items.js:75:74)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async AuthenticationService.login (file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_n4quapn3gjscmyyd32fo3dq3em/node_modules/@directus/api/dist/services/authentication.js:177:13)
at async file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_n4quapn3gjscmyyd32fo3dq3em/node_modules/@directus/api/dist/auth/drivers/local.js:70:56
}
```

I didn't change anything or upgrade anything  and it was working absolutely fine. Suddenly it has started to log this error. I tried upgrading to latest version 10.11.1 of directus but that didn't help. Nor did similar issues that people have posted w.r.t. running migrations etc.

It is really weird and directus doesn't even log if it is an authentication issue, permission issue or setup issue.

### To Reproduce

I am not sure what steps I can use to reproduce it as it works on one system but on another system it has suddenly stopped working.

### Directus Version

v10.10.7

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgresql 11.9.3

**Comment by br41nslug** [comment]
> Cannot read properties of undefined (reading 'primary')

This error would generally be thrown if the `schema` doesnt contain the collection that is being queried not sure how that could be caused on login tho 🤔 
Have you tried clearing the cache?

**Comment by divick-vama** [comment]
@br41nslug I dug and figured that the cause was directus_activity not having primary key. I added all the tables which had composite primary keys via DB_EXCLUDE_TABLES csv env var and added id as explicit primary key in directus_activity. It seems that somehow the primary key got removed. Not sure why it happened though.

**Comment by br41nslug** [comment]
Thats a weird issue, yeah the activity table really needs that primary key. Glad you managed to figure out the issue and please do let us know if you ever find out how this primary key was removed (that really shouldnt happen)
