### ISSUE TITLE
OpenAPI 3.0 Spec — Generate Directus API Clients (SDKs)

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#2255]
We already have most of our Directus API 2.x endpoints/params within Paw for testing. We could finish adding _all_ of these and then potentially use their code generators to create SDKs for our secondary languages.

https://paw.cloud/docs/extensions/create-code-generator

We also have a Swagger file for 98% of API 1.1 — so we could update that (and make sure that OpenAPI allows for our filtering syntax now).

https://app.swaggerhub.com/apis/directus/directus/1.1#/

I'd love to get some thoughts from the community (and Core team) on this so we can finally get some momentum and wrap this up!

**Comment by ybelenko** [comment]
Quote of @wing328:
> Myself and 40+ top contributors have decided to fork Swagger Codegen so as to maintain a community-driven version called [OpenAPI Generator](https://github.com/openapitools/openapi-generator) with a better governance structure to move the project forward. Now there are 10+ core team members and contributors with proper rights to merge PRs so I think we've better PR management in OpenAPI Generator. Please refer to the [Q&A](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/qna.md) for the reasons behind the fork.

Right now openapi-generator is in 4.0.0-beta version. That version contains a lot of new features, codegens and even more important breaking changes.

I've created MySQL schema generator and I'm responsible for most of PHP Slim generator updates.

You can check difference of Slim generator output:
https://github.com/OpenAPITools/openapi-generator/tree/master/samples/server/petstore/php-slim
https://github.com/swagger-api/swagger-codegen/tree/master/samples/server/petstore/slim

Quote of @wing328 again:
> It's perfect time to try Openapi Generator and give us feedback so that the project team can incorporate your feedback into the 4.0.0 stable release.

**Comment by benhaynes** [comment]
Hey @ybelenko — we have been struggling with OpenAPI/Swagger for a while, specifically with nested deepObjects used within our filtering parameters.

```
GET /items/users?filter[category][eq]=vip
```

We would _love_ to find an alternative that supports this syntax — do you know if OpenAPI Generator does?

Ref: https://docs.directus.io/api/reference.html#filtering

**Comment by benhaynes** [comment]
## Looking for a Directus API Client?

### Please consider 👍 this issue: https://github.com/OAI/OpenAPI-Specification/issues/1706

_As soon as that ticket is resolved then we can generate Directus SDKs in all the popular languages!_

**Comment by fl034** [comment]
Hey guys, I've been testing other headless CMSs that support automatic OpenAPI documentation. Those I've found are lacking other features that Directus supports.

So why wait until OAS is fully supporting nested filtering?
Why don't we start with a subset of features (and maybe mark the OpenAPI documentation as beta)?

Another useful idea would be to use Directus bookmarks and make API routes out of them, also documented via OAS.
With that we could setup some static filters that our mobile app needs for some use cases.

How do you think about that @benhaynes ?

**Comment by rijkvanzanten** [comment]
> Another useful idea would be to use Directus bookmarks and make API routes out of them, also documented via OAS.

Could you expand on this? I'm not really following what you mean

**Comment by fl034** [comment]
Maybe an example helps:
Let's assume I want to develop an App natively for Android and iOS.
Via Directus I want to manage data that is being displayed. Let's say `podcast items` and `podcast series`, to group multiple items.

In the app I want to display the podcast series, but only the ones that have one or more items in it.
My idea is to be able to create a bookmark (e.g. `seriesFilteredForApp`) that is filtered like this and make it manageable via API and documented via OAS.

In my mobile apps I could simply generate the networking client via the OpenAPI generator and be able to access this endpoint.

With this approach we would achieve some kind of static filtering, which could be useful for basic things like my example.

**Comment by rijkvanzanten** [comment]
Ohh, so you'd use the bookmark as a "shortcut" endpoint in a way? Eg `/items/podcast?bookmark=15` or `/bookmarks/15` would return all the items that match the filters / options in that bookmark?

**Comment by benhaynes** [comment]
Interesting. Almost like an interface for creating [custom endpoints](https://docs.directus.io/extensions/custom-endpoints.html).

**Comment by fl034** [comment]
Exactly. Should I file an extra feature-request issue for that :)?
And what do you guys think about offering a "beta" OAS generation?

**Comment by benhaynes** [comment]
You could add that as an API feature request! See what the community thinks... 

We have a spec from our old API (1.1) but can't spend the time to update this since we have no reassurance that OAS will support our filter syntax. If it were a lesser feature, maybe... but filtering is a _huge_ part of the platform.

If you would like to take a shot updating the spec, we can offer guidance!

https://app.swaggerhub.com/apis/directus/directus/1.1

**Comment by fl034** [comment]
I created a [feature request for the bookmarks idea](https://github.com/directus/api/issues/927).
And maybe I get to look into the OAS stuff, but can't make any promises yet.

**Comment by jhult** [comment]
Any news on this?

**Comment by benhaynes** [comment]
This is out of our hands... we (and many other people) are waiting on this issue to get resolved:

https://github.com/OAI/OpenAPI-Specification/issues/1706

**Comment by LouizFC** [comment]
Don't know if relevant, but the answer at https://github.com/OAI/OpenAPI-Specification/issues/1706#issuecomment-517837638 gives an alternative to use the "content" field on the parameters.

**Comment by rijkvanzanten** [comment]
@LouizFC Yeah! A bit more annoying to use though. For v9, we've made the params more flexible (by adding support for  "raw json" in the query param), which in turn also means that the openapi specs are now fully possible 🙂

**Comment by LouizFC** [comment]
@rijkvanzanten You are right. I tried parsing the parameters with a java parser using the mentioned workaround and the parse logic got way more complex than I expected.

Good to know that v9 will make possible to the api to be expressed with openapi, that makes alot easier to implement clients for other languages without you guys needing to support everything directly (less overhead is always good). OpenAPI truly is a blessing.

**Comment by rijkvanzanten** [comment]
This has been added in v9. You can download a customized OAS spec in your api from `/server/specs/oas`

**Comment by Eliophot** [comment]
Hello, `/server/specs/oas` does not seem to take into account custom endpoints.
How can we ensure that they are taken into account?

**Comment by rijkvanzanten** [comment]
> Hello, `/server/specs/oas` does not seem to take into account custom endpoints.
> How can we ensure that they are taken into account?

There's currently no way to have custom endpoint inject definitions into the generated specs

**Comment by staminna** [comment]
How about to manually add the extra collection fields exported from the schema? Total newby here but I think there might be possible.
Any progress on this regards?

**Comment by rijkvanzanten** [comment]
@staminna This is a closed issue from years ago, I have no clue what you're talking about! If you have a question or issue, please open a new discussion or issue 👍🏻
