### ISSUE TITLE
Cloudinary Storage: Old image returned after replacing/editing

### ISSUE THREAD

**Issue by paescuj** [directus/directus#22556]
### Describe the Bug

With Cloudinary storage, the old image is still displayed after replacing or editing an image via the File Library.

As pointed out by @joselcvarela in https://github.com/directus/directus/pull/22551#issuecomment-2127691145, this comes from the fact that the files aren't invalidated.

### To Reproduce

- Setup Cloudinary Storage [^1]
- Upload an image to the File Library
- Replace/Edit that image

https://github.com/directus/directus/assets/5363448/9040096b-855e-4549-b77f-f9d7cfcb0601

(After editing, the image isn't loading anymore inside the image editor, not sure if that is a consequence of the issue)

[^1]: https://docs.directus.io/self-hosted/config-options.html#cloudinary-cloudinary

### Directus Version

10.11.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

N/A

**Comment by sethkaufee** [comment]
First off, thank you all for getting #22551 out so quickly! 

Our team is experiencing caching issues after editing a photo with Cloudinary as a backend. It is my understanding a temporary file is created and then "moved" ([renamed](https://cloudinary.com/documentation/image_upload_api_reference#rename)) to the original asset. If the Cloudinary docs are accurate, we can use an [`invalidate` parameter](https://cloudinary.com/documentation/invalidate_cached_media_assets_on_the_cdn) to ensure the asset fetched is up to date. Without contacting Cloudinary support, the editing feature will likely seem broken when Cloudinary is used as a backend. 

The [Cloundary upload API Documentation](https://cloudinary.com/documentation/image_upload_api_reference) states the `invalidate` param is supported in most API calls, but, as @rijkvanzanten may know the Cloudinary docs leave a lot to be desired.


My initial thoughts on solutions would be:
1. Add `invalidate=true` on move.
2. Add a storage configuration option for the Cloudinary driver to always (or on certain methods) pass this param.
3. Some combination of 1 + 2.

Let me know what y'all think!

**Comment by cesar-augusto-ramirez** [comment]
If the issue is caused by caching, and the caching issue is caused by Directus' use of signed URLs, I believe it would make sense to toogle using/not using signed URLs based on the public status of the Cloudinary setup (i.e. `STORAGE_<LOCATION>_ACCESS_MODE`)

Just my 2 cents, thanks for the amazing support!

**Comment by seanmangar** [comment]
If I understand this issue + PR correctly, would this also work for assets delivered by a CDN(e.g Cloudfront) in front of Directus CMS?  File storage driver is AWS S3.
