### ISSUE TITLE
Installation stuck

### ISSUE THREAD

**Issue by dpejinovic** [directus/directus#2256]
# Bug Report

## Steps to Reproduce

1. installed directus via git
2. run /admin in browser
3. filled user details and SQL details
4. Save
5. Logged in
6. API was successfully created message
7. stuck in admin/#/collections (spinning)

## Expected Behavior
load the next view

## Actual Behavior
stuck in admin/#/collections

## Other Context & Screenshots
- Database was created
- config/api.php was created

Server logs:

Warning | (104)Connection reset by peer: mod_fcgid: error reading data from FastCGI server, referer: http://mydomain.com/admin/ |   |   |   | Apache-Error

Error || Premature end of script headers: index.php, referer: http://mydomain.com/admin/

## Technical Details

- PHP Version: [eg: 7.1.24]
- Database: [eg: MySQL 5.5.55 ]
- Install Method: [eg: cloned `master` branch]

**Comment by WellingGuzman** [comment]
Hey @dpejinovic, Is there any errors in the browser and API logs?  You can find the API logs in the `logs` directory and the browser logs using the developer tools console log.

**Comment by benhaynes** [comment]
No response in months — I'll close this now (no need to wait for `stalebot`.
