### ISSUE TITLE
Bundle extension labels as enabled when all nested packages are disabled

### ISSUE THREAD

**Issue by licitdev** [directus/directus#22569]
### Describe the Improvement

Bundle extensions label as `enabled` when all their nested packages are disabled.

<img width="487" alt="image" src="https://github.com/directus/directus/assets/26413686/01c6d510-ae09-46fc-9c04-b07edd7ae023">

However, when a nested package is enabled, it's labelled as `partially enabled`.

<img width="487" alt="image" src="https://github.com/directus/directus/assets/26413686/6d47bf29-bf7a-4eb5-a537-e4a2bc5cc881">

Perhaps the parent bundle extension's enabled status should be updated when a nested package is enabled and disabled. 🤔

**Comment by br41nslug** [comment]
> Perhaps the parent bundle extension's enabled status should be updated when a nested package is enabled and disabled. 🤔

This should already be happening 🤔 or at least when i reviewed the PR adding this feature, perhaps there is an edge case missing here
https://github.com/directus/directus/blob/main/api/src/services/extensions.ts#L248
