### ISSUE TITLE
Public role allow to create empty user. 

### ISSUE THREAD

**Issue by rem2akhmad** [directus/directus#22570]
### Describe the Bug

Directus allow to create an "empty" user without email and password.

### To Reproduce

1. Install Docker image Directus 10.11.1
2. Allow Public role create records in 'directus_users' collection
3. open terminal and execute `curl -X POST --location "http://<your-host>:8055/users" -d '{}'`
4. check user directory.
Expected: HTTP 400 Bad request. User should not be created
Actual: HTTP 204. User successfully created.

### Directus Version

v10.11.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgis:13-3.4-alpine

**Comment by mahsamirzapour** [comment]
Did you pass the role to new user?

**Comment by rem2akhmad** [comment]
> @rem2akhmad Did you pass the role to new user? in access control under system collections, directus_users use custom for Create and check email, password and role

There is no user before the call. It's "Public" role which is system role with "null" PK

**Comment by hanneskuettner** [comment]
You need to move the "email isn't null" and "email isn't" empty checks into the `AND` group, like so:

<img width="596" alt="Screenshot 2024-05-26 at 10 04 01" src="https://github.com/directus/directus/assets/4376726/90878724-a144-4b94-af29-bddc0483246d">

**Comment by rem2akhmad** [comment]
> You need to move the "email isn't null" and "email isn't" empty checks into the `AND` group, like so:
> 
> <img alt="Screenshot 2024-05-26 at 10 04 01" width="596" src="https://private-user-images.githubusercontent.com/4376726/333863693-90878724-a144-4b94-af29-bddc0483246d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MTEwMDgsIm5iZiI6MTcxNjcxMDcwOCwicGF0aCI6Ii80Mzc2NzI2LzMzMzg2MzY5My05MDg3ODcyNC1hMTQ0LTRiOTQtYWYyOS1iZGRjMDQ4MzI0NmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjZUMDgwNTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzFhOWJmMDhlZGQxYTYzYmFiMjMyYzUyM2M4OTc4ODYwODNiMTkyNWFhYTJiMWQ4YTk0MzgwOGMzYzY0NTUxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.__kNMnoSjTIs9rG40ijqdDhsg-n_UfLdxjKMJPoAVjs">

same result
<img width="400" alt="Screenshot 2024-05-26 at 1 06 20 AM" src="https://github.com/directus/directus/assets/116604742/7e836fb9-d224-42fd-8c71-258d31d858d1">

**Comment by rem2akhmad** [comment]
Seems like you are trying to check email if it exist in request, but there is no way to make this field required. At least I don't know how to do that.

https://github.com/directus/directus/blob/main/api/src/services/users.ts#L176

**Comment by hanneskuettner** [comment]
That was indeed a bit quick to assume that it would work with the changes from my end, sorry about that.
After looking at it a bit more it looks like is a identical problem as in https://github.com/directus/directus/issues/21873#issuecomment-2068972019 which is tracked in https://github.com/directus/directus/issues/22278. 

As for your problem, I just verified that the exact workaround suggested in https://github.com/directus/directus/issues/21873#issuecomment-2068972019 works here as well. 
Set the field preset for `"email"` to `null` 


<img width="854" alt="Screenshot 2024-05-26 at 10 23 30" src="https://github.com/directus/directus/assets/4376726/059a6f6b-8d52-4ced-80b8-b80972891827">

**Comment by rem2akhmad** [comment]
@hanneskuettner Great. That works. Thank you so much.
