### ISSUE TITLE
"Enable Create Button" and "Enable Select Button" not shown in Many-to-One relations

### ISSUE THREAD

**Issue by rowild** [directus/directus#22583]
### Describe the Bug

When a collection uses a Many-to-One field, where the "Enable Create Button" and "Enable Select Button", those buttons are actually not displayed, when adding content to that collection. (It seems they only appear in "Many-to-many" relations.) See screenshots.

HINT: I do not use 10.11.1, but 10.10.4, because updating is another bug problem that I will report (update does not work).

The "opus_title" is a many-to-one relation:
![01](https://github.com/directus/directus/assets/213803/a38fd925-cc4f-4ff8-89b3-9c3006d6cd86)

Both buttons (create, select) are activated...
![02](https://github.com/directus/directus/assets/213803/f596a3bf-32e0-42d0-a58f-fb5d320576aa)

...but the do not show up:
![03](https://github.com/directus/directus/assets/213803/49181c89-87f0-40b6-8a58-8334005053c4)

### To Reproduce

- In a collection, create a Many-to-One relation
- Activate the "Enable Create Button" and "Enable Select Button"
- Go to the "Content" area and add content
- Look for those 2 buttons... they won't be there

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

SQLite

**Comment by NigmaX** [comment]
@rowild do you maybe have a condition on that field?

**Comment by rowild** [comment]
@NigmaX No, nothing. - Do you use Many-to-One fields? And if so, do the buttons show up? Could you provide a screenshot, please?

**Comment by NigmaX** [comment]
@rowild I am, but I'm using the latest version.
Maybe it's locked under permissions?

**Comment by rowild** [comment]
Not at the computer now, but the permission idea sounds reasonable. I will
look into that tomorrow and provide feedback then. (Meanwhile I am also
using the latest version.)
Thank you!

GBSTR ***@***.***> schrieb am Mo., 27. Mai 2024, 13:22:

**Comment by br41nslug** [comment]
many-to-one link a single item in your screenshot you've already selected an item, deselect that first then you'll be able to "create a new item" or "select a new one"

![image](https://github.com/directus/directus/assets/9389634/ea13bd3c-8e6d-447f-b8f8-e2e5d950e50b)

Closing this issue for now since the "missing buttons" never existed for many-to-one relation those are available on relations that support multiple items.
