### ISSUE TITLE
Items not displaying in Calendar view

### ISSUE THREAD

**Issue by ZettianMaximus** [directus/directus#22609]
### Describe the Bug

Appointment items are not displaying properly when refreshing a page.

### To Reproduce

They're by default not working; to temporarily fix, select Deselect in the Start Date Field options, then refresh and select the appropriate field. 

(Not working)
![2024-05-29 17_00_30-](https://github.com/directus/directus/assets/70172378/548522d9-92a6-475d-9a4a-4d07fb8e1d23)

(Remove fields and refresh)
![2024-05-29 17_26_37-Appointments · ChiroCare](https://github.com/directus/directus/assets/70172378/0b575860-bd0f-48db-9169-a8b902fa6b78)

(Re-add fields to display items)
![2024-05-29 17_29_17-Appointments · ChiroCare](https://github.com/directus/directus/assets/70172378/d6d4d2ac-9c3f-4d21-9086-fdcaf83ebddb)

### Directus Version

v10.11.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
The start date field is required for the calendar layout, an upcoming PR will address this confusion by auto-selecting a date field 👍

**Comment by robinsonjohn** [comment]
I also wish to have the calendar layout open to the current date by default, so I currently have a filter applied to `directus_presets` to `delete data.$trigger.payload.layout_options.calendar.viewInfo.startDateStr` from being saved to the database.

This allows the calendar to select the current date by default and as of [v10.11.1](https://github.com/directus/directus/releases/tag/v10.11.1)'s calendar fix, it seems to be loading okay for me (so far).

**Comment by gla23** [comment]
Yes this is a nasty bug. For me it went like this:
1. All event disappeared suddenly disappear in the calendar (even though it says "6 items" next to the search bar)
2. When I deselect the start and end dates, refresh the page, then select ONLY the start date again (as @ZettianMaximus suggests) the events appear 🎉 (with just the start date though!)
3. Next I add the end date... and all the events disappear and you go back to the start.
4. I thought it was impossible to get the range to work, however I managed to get it to work when filtering for events where the end date isn't null.

When it crashes, the console gives an error that I assume is events without an end date crashing the range code: `Cannot read properties of null (reading 'match')`.

**Comment by MarkBurvs** [comment]
> Yes this is a nasty bug. For me it went like this:
> 
> 1. All event disappeared suddenly in the calendar (even though it says "6 items" next to the search bar)
> 2. When I deselect the start and end dates, refresh the page, then select ONLY the start date again (as @ZettianMaximus suggests) the events appear 🎉 (with just the start date though!)
> 3. Next I add the end date... and all the events disappear and you go back to the start.
> 4. I thought it was impossible to get the range to work, however I managed to get it to work when filtering for events where the end date isn't null.
> 
> When it crashes, the console gives an error that I assume is events without an end date crashing the range code: `Cannot read properties of null (reading 'match')`.
> 
> I'm on v10.12.1

Yeah can confirm I'm getting exactly the same thing. If there are any entries where the end date is null, then nothing appears at all. As @gla23 suggested, adding a filter for end dates not being null is a workaround. :)

**Comment by rijkvanzanten** [comment]
I believe this was resolved in https://github.com/directus/directus/pull/23106 as well. @SP12893678 can you confirm? 🙂

**Comment by SP12893678** [comment]
Sure, the issued has been addressed in #23106 

The following demo, re-test refresh situation (only choose start date)

https://github.com/user-attachments/assets/c888f9df-b9c3-46f2-b54d-02591dd8ea02
