### ISSUE TITLE
Permissions Dublicate - Fix

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [directus/directus#22618]
### Describe the Improvement

So based on this issue: https://github.com/directus/directus/issues/22613

When having dublicates of permissions no ID is shown in the frontend, leaving users in a "soft-lock".

Tiny tweak:
- Include a small script which auto removes dublicate entries. Maybe remove older dublicates.
- Show in the UI frontend one of the Ids please
- In the get permissions show the id also

**Comment by br41nslug** [comment]
Can you show reproduction steps for how to get into the state of having duplicated permissions in the first place?

**Comment by NilsBaumgartner1994** [comment]
See the isse #22613 by using the REST API. The issue was found since a script ran and added the same role, collection and action twice.
Also the same problem is already mentioned in: https://github.com/directus/directus/issues/21965
https://github.com/tractr/directus-sync?tab=readme-ov-file#remove-permission-duplicates

I think it would be better to close the issue here and mention it in the original #21965 as of duplicate.

This way two permissions are created resulting in the soft lock state, as mentioned in the issue referenced.

```js
const response = await fetch(`http://127.0.0.1/api/permissions`, {
            agent: httpsAgent,
            method: 'POST',
            headers: {
                "Cookie": headers.get('cookie'),
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                role: permission.role,
                collection: permission.collection,
                action: permission.action,
                fields: permission.fields,
                permissions: permission.permissions,
                validation: permission.validation,
            }),
        });
 ```

**Comment by br41nslug** [comment]
Closing this in favor of #21965 the optimal solution here would be to prevent duplicate permissions instead of deduplicating them after the fact (that can be done as a one time fix)
