### ISSUE TITLE
Schema change based on user permissions

### ISSUE THREAD

**Issue by alexdess** [directus/directus#22614]
### Describe the Bug

I have a many2many relationship between an executed_post table and an adjustment table. An adjustment also has a relationship to a mission table. If I grant (or remove) edit permissions on the mission table from the web interface, the behavior of the GraphQL API becomes strange.

The used request is
```
mutation Update_executed_post_item {
    update_executed_post_item(
        id: "25"
        data: { adjustements: [{ title: "missing tool", mission_id: { id: 25 } }] }
    ) {
        id
    }
}
```

Error without edit permissions on the mission table:
```
ERROR: Variable "$data" got invalid value { id: 193 } at "data.adjustements[14].mission_id"; Int cannot represent non-integer value: { id: 193 }
```
However, with the rights, it works correctly.

What seems strange to me is that in both cases, I never modify the mission, I only reference its ID. Is this the desired behavior? Somehow, this means that the graphql schema is modified according to rights.

### To Reproduce

1. Create a many2one relationship between 2 tables executed_post and mission for example. Give full access on executed_post and readonly on mission table.
2. Lauch the query
```
mutation Update_executed_post_item {
    update_executed_post_item(
        id: "25"
        data: { adjustements: [{ title: "missing tool", mission_id: { id: 25 } }] }
    ) {
        id
    }
}
```
3. You will have an error like "Int cannot represent non-integer value"
4. Give write access to the table "mission"
5. The request will work

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Looks like you're trying to create a new "mission" with a specific ID which logically fails if you dont have permission to do so. The error is pretty on-point there, you cannot assign an object (non-int) to an integer field:

```
mutation Update_executed_post_item {
    update_executed_post_item(
        id: "25"
        data: { adjustements: [{ title: "missing tool", mission_id: 25 }] }
    ) {
        id
    }
}
```

Closing this issue for now since it looks to be an invalid payload for the permissions you've set. Happy to re-open if that is not the case.

**Comment by alexdess** [comment]
I agree that if the user does not have creation/modification rights, then they should only populate mission_id. 

However, in this perspective, populating only the ID should also work for a user with modification rights, which is not currently the case, and another exception is raised. This is why GraphQL types "change" depending on the rights, which I believe is a problem.
