### ISSUE TITLE
ERROR: "DB_CLIENT" Environment Variable is missing

### ISSUE THREAD

**Issue by BernardMcWeeney** [directus/directus#22620]
### Describe the Bug

Hello I seen this issue was [raised before](https://github.com/directus/directus/issues/12202)  but the problem for them was they were in the wrong directory. I am not making that mistake yet I am getting the error message below.

When running npx directus database migrate:latest I get the error of "ERROR: "DB_CLIENT" Environment Variable is missing"

In my docker-compose.yml DB_CLIENT is defined

![image](https://github.com/directus/directus/assets/99593468/a3b31b46-16da-49f3-b253-46a3671daf12)
<img width="286" alt="image" src="https://github.com/directus/directus/assets/99593468/3b379231-6d74-421d-bd82-d02827b79a0d">

### To Reproduce

Follow docker selfhost quickstart guide https://docs.directus.io/self-hosted/quickstart.html

cd directus
run docker compose up
npm update
npx directus database migrate:latest

### Directus Version

v10.11.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

sqlite

**Comment by BernardMcWeeney** [comment]
![image](https://github.com/directus/directus/assets/99593468/710243ed-5396-4a1b-b9e3-8e1d154d549d)

Seems when I am in the container itself and run the migration command it works without error ?

**Comment by br41nslug** [comment]
When using docker you will need to run it inside the container, a handy shortcut to do so is:
```
docker compose exec directus npx directus database migrate:latest

docker compose exec <container namer> <command to run>
```

**Comment by BernardMcWeeney** [comment]
Thank you!
