### ISSUE TITLE
ROUTE_NOT_FOUND - Verify a Registration

### ISSUE THREAD

**Issue by suchkovcode** [directus/directus#22635]
### Describe the Bug

directus: 10.11.2
sdk: 16.0.2
nuxt: 3.11.2
![hero-3](https://github.com/directus/directus/assets/105043724/325471b7-0dd9-4997-a1f8-4b770cf7fbb7)
USER_REGISTER_URL_ALLOW_LIST=https://app.amorfy.net/verification

```
export default defineEventHandler(async (event) => {
   const { directus, registerUserVerify } = useDirectus();
   const { token } = await readBody(event);

   const data = await directus.request(registerUserVerify(token));

   return data;
});
```

### To Reproduce

You can register
https://app.amorfy.net/

### Directus Version

10.11.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 16

**Comment by licitdev** [comment]
Casting the env to `array` should resolve the issue.

```
USER_REGISTER_URL_ALLOW_LIST=array:https://app.amorfy.net/verification
```

Ref: https://docs.directus.io/self-hosted/config-options.html#environment-syntax-prefix

**Comment by licitdev** [comment]
On second thought, it should be improved to accept a single URL. Thank you for the report! 👍

**Comment by licitdev** [comment]
This issue has been patched via https://github.com/directus/directus/pull/22599, kindly update your Directus SDK after the upcoming release. Thank you.

**Comment by npostulart** [comment]
Until SDK update you can call the endpoint manually, e.g.:

```
await client.request(
    customEndpoint<void>({
        path: "/users/register/verify-email",
        params: { token },
        method: "GET",
    }),
);
```
