### ISSUE TITLE
Permissions error when using pg_restore

### ISSUE THREAD

**Issue by wolfgang-hartl** [directus/directus#22631]
### Describe the Bug

✅ Directus Version: 10.11.0 & 10.11.2
✅ Run all "Troubleshooting Steps"

Whenever creating a new Collection, it doesn't create an entry for that collection in the directus_permissions table, which seems to break some functionality when restoring a complete backup with the pg_restore command:

Please let me know if you need any additional information about this possible bug.

### To Reproduce

1. Create a Directus Collection name "Qwertz"
2. Create a backup using pg_dump
3. delete the collection created before
4. restore that backup using pg_restore
5. See that error:
<img width="681" alt="image" src="https://github.com/directus/directus/assets/75800215/e99b48af-5a2f-4dcd-96e9-f6eb8a3b9c53">

6. Head over to access-control
7. Set "read only" for any user role for that particular collection
8. Undo that action again
9. Now it should work as expected (you have to reload the page to see the entries of that collection properly)

After undoing step #7 the entry in directus_permissions gets deleted again, but it seems that there is some task running in the background which makes the collection available again in the admin ui. 

<img width="769" alt="image" src="https://github.com/directus/directus/assets/75800215/10a39066-6c41-4bd1-beff-9e2a5d32f3af">

### Directus Version

v 10.11.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgres:13

**Comment by br41nslug** [comment]
The forbidden error you're seeing is likely your cache not being updated/cleared yet resulting in a 404 (thrown as forbidden). The permission record is created when you edit the permissions for that table (there is no background process doing that).

Make sure to also include the Directus system tables in your complete backup and restores. Closing the issue for now but happy to reopen if more information becomes available.

**Comment by wolfgang-hartl** [comment]
Hey @br41nslug, thanks for your answer. I first thought of a caching issue too, but it didn't resolve neither after time nor when refreshing without cache.

I included the complete database in my backup. I will investigate more to maybe find out if it's related to specific pg_restore / pg_dump configs or something else. Will let you know if I find additional information :-)

**Comment by br41nslug** [comment]
pg_dump and pg_restore work outside of the context of Directus. They *should* backup and restore the database to the exact same state as before but if they dont there is little Directus can do about it 🤔

**Comment by wolfgang-hartl** [comment]
Yes that's probably the case... with the "background process" thing it woudl've make sense, but maybe it's really related to my config or a caching issue.

If I'll find the cause of that problem i will post it here for future me's struggling with that ;-)

**Comment by br41nslug** [comment]
Yeah definitely let us know if you do find out what's happening there 😄
