### ISSUE TITLE
Cannot load extension bundle on windows after updating Directus from 10.8.3 to 10.11.1

### ISSUE THREAD

**Issue by itszeeshan** [directus/directus#22639]
I have a bundle folder inside my local directus extensions folder that includes the dist (Built extension) and package.json file. It was working properly in version 10.8.3 but after updating my directus to 10.11.1 it is throwing this error.

![image](https://github.com/directus/directus/assets/35112049/3c434c61-7312-4893-84be-3d81eccf4f90)

Even tho my package.json file includes the same content as it had in 10.8.3. 
![image](https://github.com/directus/directus/assets/35112049/f47860a6-e4b2-4067-8f0c-2dc0905e5ee7)

I thought this `Value for field "name" in collection "directus_extensions" can't be null.` had something to do with the objects entries for extensions in package.json but I dont think it is an issue in here. I believe that it is related to postgres, I'll check if the field exists if not I'll try to manually create a field "name"  in "directus_extension" in postgres and will see if it works. Creating an issue right now so maybe somebody can tell me whats happening after we update our directus? Like are the missing fields being automatically generated in our postgres or do we have to create it every single time manually? 

### To Reproduce

1. Create a Directus bundle extension (in that bundle I have endpoint, displays, module, interface and hooks extension)
2. Build that bundle extension and put the dist folder generated after building the extension along with your package.json file in your local directus app extension folder.
3. Upgrade directus to 10.11.1 and run the app.

### Directus Version

10.11.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 14.4

**Comment by br41nslug** [comment]
Have all migrations run successfully in the upgrade? have you tried removing the invalid record from the `directus_extensions` table? (or clearing that table all together)

**Comment by itszeeshan** [comment]
Yes all the migrations are successful and also just saw that the field name does exist and i dont see any null values there as well

![image](https://github.com/directus/directus/assets/35112049/008bf957-a960-469e-a5de-6a4b55369d40)

**Comment by rijkvanzanten** [comment]
@itszeeshan Can you reproduce this on a fresh installation, or does it only happen during that upgrade? I haven't been able to reproduce this based on the instructions provided, but am happy to reopen when more information becomes available 🙂
