### ISSUE TITLE
Permission inconsitency

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [directus/directus#22630]
### Describe the Bug

I was configurating the permissions of my database. So when i tick for creation all fields seperately vs. when i press all the behaviour differs.
Selecting each permission field results in a permission not allowed.
Selecting allow all results in a success.

### To Reproduce

Table: Profile 1:n Food_Feedbacks
Food_Feedbacks 1:n Feedback_Labels

### Directus Version

v10.11.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Postgres 13

**Comment by br41nslug** [comment]
I have not been able to reproduce this issue using the given reproduction steps/information.
![image](https://github.com/directus/directus/assets/9389634/57a9d46b-c6a5-4f6e-934e-12d464b5096e)
![image](https://github.com/directus/directus/assets/9389634/3ce1cedf-32be-4c58-9f34-1a3232a4ab55)


Please provide more detailed reproduction steps. Have you set any other permissions besides the field permissions? Did you add fields/relations after manually selecting all fields (those would be missing)? What request are you doing that gets the error?

Closing this issue for now but happy to re-open if we can get this reproducable
