### ISSUE TITLE
Environment variables: AUTH_<PROVIDER>_FIRST_NAME_KEY and AUTH_<PROVIDER>_LAST_NAME_KEY do not work

### ISSUE THREAD

**Issue by misterEugene** [directus/directus#22632]
### Describe the Bug

When setting up the openid provider, I found that two environment variables: AUTH_<PROVIDER>_FIRST_NAME_KEY and AUTH_<PROVIDER>_LAST_NAME_KEY do not work as I think they should work by name. Then I looked into the api/src/auth/drivers/openid.ts file and found that on lines 196 and 197, the keys storing the first and last name of the user being created have static values ​​and are in no way affected by environmental changes AUTH_<PROVIDER>_FIRST_NAME_KEY and AUTH_<PROVIDER>_LAST_NAME_KEY. 

If I'm doing something wrong, correct me. If this is a small error in Directus, please give the necessary rights, I want to make a merge request to fix this error.
![Screenshot from 2024-06-02 03-12-47](https://github.com/directus/directus/assets/123299569/1063d61f-328b-4a7a-ac25-a88303a5aa9c)

### To Reproduce

you need to set up an openid provider that will store the user's last name and first name in the token_id under a name other than "given_name" and "family_name" and then set the environment variables AUTH_<PROVIDER>_FIRST_NAME_KEY and AUTH_<PROVIDER>_LAST_NAME_KEY as the value to pass the desired ones give you the keys to access your last name and first name

### Directus Version

10.11.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by hanneskuettner** [comment]
Heya! Thank you for opening this issue. 

It looks like you're trying to use configuration values that are only available for OAuth SSO, see https://docs.directus.io/self-hosted/config-options.html#oauth-2-0, with an OpenID provider. Those are two different things and different configuration variables apply to them, see https://docs.directus.io/self-hosted/config-options.html#sso-oauth2-and-openid.

OpenID has a set of standard user claims defined[^1], including `given_name` and `surname`, which is what is used in the OpenID SSO driver. Not having worked with SSO as much, I wonder if you can give me a valid use case where an OpenID provider would deviate from those standard claims 🤔. If not I'd like to close this as "Not Planned" for now, with the possibility of opening an improvement request should we come up with a valid need for this configuration.

[^1]: https://openid.net/specs/openid-connect-basic-1_0.html#StandardClaims

**Comment by misterEugene** [comment]
Thanks for your reply 🤝
I realized that I would need to configure my openid provider.  Didn't know about standard claims. I thought they could be configured for each client separately.
