### ISSUE TITLE
Allow user to use a Collection as a specific field type

### ISSUE THREAD

**Issue by rw3iss** [directus/directus#2264]
# Feature Request

## What problem does this feature solve?
This solves a few problems, namely not having to setup tedious and confusing relationships between collections, and also allows for vast improvements to the editing experience as far as custom content types go. 

## How do you think this should be implemented?
When I define a new collection, I'm thinking of it as a data type, and this data type should then become selectable as a field type in any new collection definition.
Currently, if I want to setup a relationship to a collection, I have to define it from both sides, or with an independent table (M2M). Instead, it could be possible to allow the user to just set a specific field within a collection to use *another* collection as its field type. This should implicitly setup the relationship in the background, and the editor modal for the main type could show the same relationship select box that it does now (or 'create new'). 
For instance, in my experience: if I have a Carousel Slide collection, that I want to use in multiple other collections, I have to setup all those relationships independently if I want to choose one (or a set) or Carousel Slides from within the other collection items. 
It would be convenient to just define a field of type "Carousel Slide" within the new Collection (let's call it Homepage), and specify whether its 'multiple' (multi-select/array), or 'single'. Then, when editing a parent item of Homepage, I can just select the array of Carousel Slides that I want to use. On another page collection type, I could define a single selection of this type and then select only one Carousel Slide to use for a specific field value. 
That seems highly convenient, and will probably need to do all the same things that relationships currently do behind the scenes, but shouldn't really require so much user input. 

## Would you be willing to work on this?
Yeah, but will definitely take collaboration.

**Comment by benhaynes** [comment]
I believe I'm following what you're proposing — and it seems that this could be done entirely in the App (not API). It's a significant change, so let's discuss it a bit and if the core team (and community) agree we can start with some design mocks!

@rijkvanzanten thoughts?

**Comment by rijkvanzanten** [comment]
The problem I'm hearing is the fact that it's tedious to setup relationships. @benhaynes we've discussed automatically setting up relationships, and only providing the manual setup as an advanced feature. That would solve the same underlying problem right? 😄

**Comment by rw3iss** [comment]
@rijkvanzanten Yeah, basically. Not sure what you have in mind, and sounds like it'd be fine, however, I would also like to see this sort of "easy" ability to define a field type as some other data type (ie. just changing the Collection's add/edit field modal to show Collections as choices, if some setting of them allows it), otherwise I'm not sure what you might have in mind for defining the relationships automatically.

Initial impressions cause me to think that it wouldn't require any large overhaul of the backend/API, with a bit of massaging of the App frontend:

-add Collections as Field Types (if their settings allow it, by default yes), which show in the field add/edit dialog.
-maybe ask user to customize which fields to show (or even fetch automatically upon querying?) from this collection, in the relationship (by default, initial implementation should just show all fields for now?)

I think the smoothest/most intuitive frontend change for editing the collection would be to show the field selection with Collections as choices, but then there should also just be a simple checkbox that asks if it is singular, or supports multiple item selection... 

When editing an item, I think the custom field type would automatically show as it currently does (ie. 'add new/select existing table'), since I think it's the same kind of relationship setup in the backend, so I think the only semi-major refactoring is the field add/edit modal for a collection, and the backend API logic to automatically setup the relationships based on the fields and types it sees, maybe.

**Comment by rw3iss** [comment]
Guess I should also mention another problem currently seems to be some bugginess with defining relationships, and then changing some of them. I have seen it multiple times in working with relationships the past few days. If I do things even remove entire related columns, then read, I don't see the changes picked up in the DB sometimes, and get console errors, and all these things. Sure, I know I should be careful in doing this, and am, but the whole app shouldn't bug out so much in these cases, instead should guide the user or fallback somehow. Just wanted to mention that, if we're going to be making changes to this area, can maybe try to hit some of those as well.

**Comment by dev7ch** [comment]
I am not sure if see the entire scope of the issue but maybe to make the collection tree draggable and introduce a children array into data would be a possible solution.

Insiration https://www.npmjs.com/package/vue-draggable-nested-tree

**Comment by rijkvanzanten** [comment]
This is currently possible (to an extent) by using the `repeater` interface. We're working on a relational version of the repeater interface that does exactly what you say (choose another collection as base for the repeatable rows in a field.

**Comment by strujillosuarez** [comment]
Hi @rijkvanzanten I am very interested in the development of this feature. My need is the following: I would like a Repeat interface, to display a Section Title AND a list of values (Mine only) from a Selected Collection... Ideally, the user can control the sorting of the values: https://prnt.sc/r7l7ih

Is this what you had in mind for this feature?

**Comment by rijkvanzanten** [comment]
Not quite, what you're referring to is what I call a _Relational Repeater_, where each row of the repeater is an item in a related collection. Seeing the row is now it's own relational item, you'd be able to use a one to many nested in this relational repeater, giving you the use case you describe

**Comment by rijkvanzanten** [comment]
Relational interface aren't possible in the 'standard' repeater interface, as it saves everything in flat JSON.

**Comment by strujillosuarez** [comment]
@rijkvanzanten Thanks for your quick reply. I already considered the "Many to Many" field as a "Relational Repeater" interface. The only problem is that the user can not manipulate the sorting of the selected values, which in my case is very important. Is there any way around it?

**Comment by rijkvanzanten** [comment]
@strujillosuarez You should be able to add a `sort` column to the junction table 🙂

**Comment by strujillosuarez** [comment]
@rijkvanzanten Thanks a lot! It works just as I wanted.
