### ISSUE TITLE
Setting a preset for all users isn't working properly.

### ISSUE THREAD

**Issue by VincentKempers** [directus/directus#22648]
### Describe the Bug

When creating a preset for a collection directus_files for example. This preset should contain a simple change from a default (card) view to a table view. What it's happening setting this for Global is not setting for all users. Also when creating a new user it's not setting it will still display cards. When deleting all presets and setting again it will still not set a new preset for global.

Tried this locally and on directus cloud and it doesn't set.
Also encountered some odd behaviour when deleting a preset. Sometimes the deletion would not happen.
Or the preset would not update to Global users.

### To Reproduce

Create a preset for global users that directus_files needs to be a table.
Create a new user or check a pre-existing one that does not have a preset set and see if the preset has been set.
On a new user you would still see cards (this still happened after emptying cache).

Regarding the presets deletion this happend a bit sporadically but I could capture this on video.

Videos
https://github.com/directus/directus/assets/14160793/d6482d49-aa72-4078-9dad-f4e19d93c7bc

https://github.com/directus/directus/assets/14160793/94aa026a-e5b9-421b-ba5e-9df068b8d3fb

### Directus Version

v10.11.2

### Hosting Strategy

Directus Cloud

**Comment by hanneskuettner** [comment]
This seems to be caused by the presets store not considering presets that have a name.

See https://github.com/directus/directus/blob/3e7b8544a369c859f6363598d2e5f5c973ffea13/app/src/stores/presets.ts#L266

**Comment by hanneskuettner** [comment]
We document this behavior in our docs, and also state the difference between Bookmark and Default preset there

> For Administrators, the process to create either a Default or a Bookmark is almost exactly the same. The key difference is that if you set a value for Name, the preset becomes a Bookmark. If Name is left blank, the preset will be a Default.

https://docs.directus.io/user-guide/settings/presets-bookmarks.html#create-a-preset

So now I'm wondering if this is correct and expected behavior and we should close this issue.

@VincentKempers This seems to be in line with your screen recording, can you confirm that the problem disappears if you remove the Bookmark name?

Also see this recording for the different behavior



https://github.com/user-attachments/assets/e2fdc972-989a-4e37-a003-6064e336d960

**Comment by VincentKempers** [comment]
> We document this behavior in our docs, and also state the difference between Bookmark and Default preset there
> 
> > For Administrators, the process to create either a Default or a Bookmark is almost exactly the same. The key difference is that if you set a value for Name, the preset becomes a Bookmark. If Name is left blank, the preset will be a Default.
> 
> https://docs.directus.io/user-guide/settings/presets-bookmarks.html#create-a-preset
> 
> So now I'm wondering if this is correct and expected behavior and we should close this issue.
> 
> @VincentKempers This seems to be in line with your screen recording, can you confirm that the problem disappears if you remove the Bookmark name?
> 
> Also see this recording for the different behavior
> 
>  Screen.Recording.2024-07-25.at.08.29.07.mov

@hanneskuettner and @alexchopin 
My apologies for answering this late. It seems to be working when removing the name. Tested this **locally** and on **cloud**.
Thank you for reviewing this and apologies for the issue here, totally missed this.
I think we can close this now.
