### ISSUE TITLE
Images get stored to cloudinary as "Raw" instead of "Image" when uploading via Directus

### ISSUE THREAD

**Issue by DonCastillo** [directus/directus#22687]
### Describe the Bug

I have no problem uploading an image directly to Cloudinary, but when I upload via Directus (using Cloudinary as media storage), some images, particularly the image I attached with this bug report, they get stored to Cloudinary as "Raw" instead of "Image" 

Here is the image:
![testxxx](https://github.com/directus/directus/assets/51107521/351dcb68-e44f-4550-aba3-8f68cab34f59)

when I upload directly to Cloudinary (by dragging and dropping the file), the image gets stored as "IMAGE"
original filename is used, "testxxx.JPG"
![image](https://github.com/directus/directus/assets/51107521/d2b3cd68-4523-4052-9a11-b5840f467946)

when I upload to Cloudinary via Directus, the image gets stored as "RAW"
original filename used, testxxx.JPG; directus renamed it as f532f750-f696-4bc8-8702-e48954896b2e.JPG
![image](https://github.com/directus/directus/assets/51107521/ede98572-b967-490f-a630-96cd3f374244)

### To Reproduce

* Spin up a local instance of docker-based Directus
* Integrate Cloudinary with the following .env variables:

STORAGE_CLOUDINARY_DRIVER="cloudinary"
STORAGE_CLOUDINARY_ROOT="/testing"
STORAGE_CLOUDINARY_HEALTHCHECK_THRESHOLD=750
STORAGE_CLOUDINARY_CLOUD_NAME="...."
STORAGE_CLOUDINARY_API_KEY="...."
STORAGE_CLOUDINARY_API_SECRET="...."
STORAGE_CLOUDINARY_ACCESS_MODE="public"
FILES_MAX_UPLOAD_SIZE="100mb"
FILES_MIME_TYPE_ALLOW_LIST="*/*"

* Other services used:
 mysql:5.7.8
 redis:6
 directus:10.12.0

### Directus Version

v.10.12.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

mysql:5.7.8

**Comment by turbolaserhawk** [comment]
Same issue. 

Cloudinary has confirmed that Directus is uploading some images using type "raw" rather than image and it results in the asset being treated as a binary file and therefore not displayable.   I think the issue is related to capitalization of "JPG" in file extensions rather than "jpg" or "jpeg". 

<img width="810" alt="image" src="https://github.com/directus/directus/assets/60415816/803f60fa-5e4d-4d86-8a38-eae5551b28ce">

**Comment by hanneskuettner** [comment]
Good find on the extension casing! Looks like we indeed only compare the extension in it's raw form against a list of lowercase known image extensions. I've created a PR, if you have the possibility to test it for me, I'd be super grateful, as I don't have a cloudinary account flying around at the moment.
