### ISSUE TITLE
Unable to Install Suite

### ISSUE THREAD

**Issue by ironshu** [directus/directus#2269]
# Bug Report

## Steps to Reproduce

Followed all installation steps. Set permissions on folders and confirmed requirements are met. Manually configured the app.

## Expected Behavior
Expected to be able to log into admin.

## Actual Behavior
Login screen posts message "Couldn't reach API"
/server/ping is throwing a 404.

## Other Context & Screenshots
I've spend an entire weekend trying to get this to work on my Digital Ocean instance - no luck.
I've tried installing and configuring the api and the app separately but still the same error.

## Technical Details

- Device: [eg: Desktop, iPhone6, etc]
- OS: [eg: MacOS 10.13.6, Windows 10.1803]
- Web Server: [eg: Apache 2.4.37]
- PHP Version: [eg: 7.2.0]
- Database: [eg: MySQL 8.0.12]
- Install Method: [eg: cloned `master` branch]

**Comment by shealavington** [comment]
> Manually configured the app.

Could you expand on this, what have you configured, have you also configured the API, (setup an api.php file)? (Just want to be sure)

**Comment by rijkvanzanten** [comment]
> Digital Ocean instance 

Is this on a LAMP stack? If so, can you confirm you have `php_curl` installed and `mod_rewrite` enabled?

**Comment by ironshu** [comment]
Aarg.. mod_rewrite was not enabled. I missed that nugget in your docs. I have enabled it and now it works - thank you!

As a suggestion, I would recommend you itemize all the necessary steps in a single document instead of having an "full list of requirements page?". This was definitely me overlooking the docs - just something to consider.

**Comment by rijkvanzanten** [comment]
Ah! 

One of the features that we're focussing on next is a page in the installation flow that shows you if all the necessary requirements have been met. That should clear up a lot of confusion as well 😄

**Comment by ironshu** [comment]
Most excellent :)
