### ISSUE TITLE
SDK autoRefresh stop working after page reload

### ISSUE THREAD

**Issue by ricardovigatti** [directus/directus#22703]
### Describe the Bug

The autoRefresh feature in SDK it's not working as expected. Well... it works when I first call login() to authenticate a user. But if I reload the page once, there are no subsequent calls to auto refresh the token.

Its an Angular app. Directus ACCESS_TOKEN_TTL is set to 1 minute so I can debug and follow the log of requests being made. I have tried to analyse the code in https://github.com/directus/directus/blob/main/sdk/src/auth/composable.ts, but couldn't find what the issue is.

```
// directus .env
ACCESS_TOKEN_TTL="1m"
REFRESH_TOKEN_TTL="7d"
REFRESH_TOKEN_COOKIE_SECURE=false
```

```typescript
// angular directus.service.ts
this.directusSDK = createDirectus<MySchema>(environment.directusServer)
            .with(authentication('cookie', { credentials: 'include' }))
            .with(graphql({ credentials: 'include' }))
            .with(rest({ credentials: 'include' }));
```

```typescript
// angular auth.service.ts
signIn() {
    this.directusSDK.client.login(credentials.email, credentials.password) [...]
}

signInUsingToken() {
    this.directusSDK.client.request(refresh()).then((response) => {
        this._directusService.client.setToken(response.access_token);
        // Also, note that I need to manuall set the token into Directus SDK after refresh().
        // I was expecting this to be handled automatically by the SDK, as its already done in login().
    });
}
```

### To Reproduce

We can split the reproduction steps in two.

1. After user signs in, autoRefresh just works as expected.

a. When a user first visits the page, the signIn form is filled and login() is called using the SDK.
b. I'm able to debug the requests being made and I see a /auth/refresh every 30 seconds.

2. After subsequent page reloads, autoRefresh doesn't work

a. An already authenticated user gets back to the site or reloads the page
b. My Angular app identifies the refresh cookie and auto sign in the user again calling the signInUsingToken() method.
c. The auto refresh feature isn't called anymore.

Also, please note that I need to manually set the access token after refresh().  I was expecting this to be handled automatically by the SDK, as its already done in login().

### Directus Version

v10.12.0

### Hosting Strategy

Self-Hosted (Custom)

### Database

MySQL 8

**Comment by br41nslug** [comment]
You are doing a manual refresh request in combination with the `authentication` handler. If you choose to do manual requests you will have to manually handle tokens and refreshing too. 

For the authentication composable's autoRefresh to work as expected you'll want to stick to its authentication functions (like `client.refresh()`)
https://docs.directus.io/guides/sdk/authentication.html#using-the-authentication-composable

**Comment by ricardovigatti** [comment]
Oh man, that's awesome. I didn't realize I was calling refresh() from inside a client.request(). So now its working as expected. Thank you!!
