### ISSUE TITLE
The main search function does not include the Translations fields

### ISSUE THREAD

**Issue by Vahagn-Zaqaryan** [directus/directus#22709]
### Description
The problem when using the main search on nested content like translation models when searching in Armenian the it system doesn't bring any results this is a blocking issue for our release. It seems this problem exists in both English and Armenian languages.

### Actual behavior
The user receives no items found even if they search for the exact title of the book.

### Expected behavior
The system searches through the collections including the translation fields and brings the correct results.

### Database information
Verison: PostgreSQL 15
Hosting Strategy: Self-hosted (Docker Image)
Docker Image: postgres:15-alpine

### To Reproduce

As an example, we'll create a collection ok books with multilingual title.

- Create a clean installation of Directus CMS
- Create a new collection for Languages (not a singleton)
- Add at least 2 languages in the collection
- Create a new collection of books (not a singleton)
- Add a translation model within the collection
- Create a title field in the translation model
- Add book items in the collection with titles
- Try to search using the title of the book

### Directus Version

v10.12.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 15

**Comment by hanneskuettner** [comment]
This is a known limitation of the search function and there is an open Feature Request to supported searching related fields here #10517. I'm going to close this here and ask to please upvote the feature request over there, to show your interest as well! :)

**Comment by Vahagn-Zaqaryan** [comment]
Hey @hanneskuettner, thanks for the quick reply, I just upvoted 😊
