### ISSUE TITLE
get_cfg_var not working for max_upload_size

### ISSUE THREAD

**Issue by cheehau** [directus/directus#2271]
Hi,

Is that any reason why we want to use get_cfg_var vs ini_get to get the max_upload_filesize?

This is causing some issue with using CPanel as I have no access to the php.ini. but instead ini_get will work as it is getting value from runtime as opposed to from the ini file.

Thanks

**Comment by WellingGuzman** [comment]
What's the problem you are getting exactly? Are you using `/` or `/<project>` endpoint?

Are you trying to increase your upload size?

> Is that any reason why we want to use get_cfg_var vs ini_get to get the max_upload_filesize?

We try to use `get_cfg_var` to get the `php.ini` configuration value (for global reference) and `ini_get` to fetch the runtime value, the actual max size for that execution in specific (real one?).

**Comment by cheehau** [comment]
Hi,

When doing a request to /public endpoint to get server configuration, in my case the max_uploadfilesize I am getting is 0 value. Tracing the codes allow me to determine that because it is using get_cfg_var instead of ini_get.

I have double check my loaded configuration php file, which seems to point to a file which I can't access. So this could cause some issue with people who are using a shared hosting service such as cpanel. Not sure if we could update the code to work around this issue. Or if we decide to ignore such people.

Currently what I did is to hardcode the $global to true. so it will always be using ini_get

**Comment by WellingGuzman** [comment]
Hey @cheehau, which endpoint is that? `http://domain.tld/_/` or `http://domain.tld/`?

From [php docs](http://php.net/manual/en/function.get-cfg-var.php):

> This function will not return configuration information set when the PHP was compiled, or read from an Apache configuration file.
> 
> To check whether the system is using a configuration file, try retrieving the value of the cfg_file_path configuration setting. If this is available, a configuration file is being used.

Do you know what's your stack? This might be the problem, can you confirm this?

Either way I will fallback the value to use `ini_get` instead, that way we have a value returned.

**Comment by WellingGuzman** [comment]
Fixed by https://github.com/directus/api/commit/236192e0758b1c312fe07c1f04e738d052a0c915

**Comment by cheehau** [comment]
thanks @WellingGuzman for the PR, guess this will be robust for different stack.
