### ISSUE TITLE
Trying to mimic website normal navigation menu to internal pages.

### ISSUE THREAD

**Issue by avifatal** [directus/directus#2272]
Hi,
Im comming from the world of fully featured traditional CMS and im trying to bring some of the concepts to my content modeling. (working with angular 6 if that matter)

I need to build a website with 5 different pages, each page has different content structure.
On top of that, I need a "Navigation" model that will have hold the site menus.
The navigation needs to hold a relation to a page. but since the pages are really different, each page is in a different collection.

Is there a way to build a dynamic relation. some sort of one to any? meaning, in runtime when the content guy add a new navigation item, he will choose which collection/page typme to relate this nav item, cascading field... choose the collection and the row...?

I hope I was clear enogh.
Maybe im doing something wrong here and there is a better way to controll the site navigation.

Thanks

**Comment by benhaynes** [comment]
Docs! https://docs.directus.io/guides/relationships.html#many-to-any

Feature Request! https://github.com/directus/app/issues/712

This is _technically_ possible, but I'd say we won't officially support it until we have the M2X relation/interface available to make this easier.

You're not doing anything wrong with your data model — that seems like the best way to approach this. 😄
