### ISSUE TITLE
Add composer.json to the repository

### ISSUE THREAD

**Issue by WellingGuzman** [directus/directus#2273]
Add the missing `composer.json` file, to prevent issue when installing new packages.

Ref 1: https://github.com/directus/api/issues/620
Ref 2: https://github.com/directus/docs/issues/83

**Comment by tassoman** [comment]
Also having *vendor* directory versioned inside the project is an uncommon way of project distribution.

Vendors distribution it's considered a lack of security. Someone could point the repository may use modified unfair vendors instead of originals.

`composer install` deals library pulling and grants that sources are from official repositories.

**Comment by benhaynes** [comment]
Hey @tassoman — agree, but the point of this repo is to offer a "one-click" combined build of Directus (including all dependencies). Users looking for a more customizable (or secure, in your words) installation should use the dedicated API/App repositories. The "suite" at `directus/directus` is more for convenience (eg: shared host users with no command line access).

**Comment by ybelenko** [comment]
Let's say that I'm skilled enough to install api and app repos. 

- I still don't understand how to clone repos in one folder as soon as I need dasboard and API all together?
- In most cases I need to write my own code(hooks, tests, extensions) and use version control. It means that I need to separate my code from Directus sources and sure, fork can handle that, but fork of what repo? It still requires from me to do `git pull upsteam master` and `git rebase master` over and over again.

It's bad that there is no option to install Directus as dependency, it's possible with WP, you can even find recommended `.gitignore` for WP projects.

**Comment by rijkvanzanten** [comment]
> I still don't understand how to clone repos in one folder as soon as I need dasboard and API all together?

`git clone https://github.com/directus/directus.git` is enough

> In most cases I need to write my own code(hooks, tests, extensions) and use version control. It means that I need to separate my code from Directus sources and sure, fork can handle that, but fork of what repo? It still requires from me to do git pull upsteam master and git rebase master over and over again.

How would you imagine this working otherwise?

> It's bad that there is no option to install Directus as dependency

Why?

> it's possible with WP

How?

> you can even find recommended .gitignore for WP projects.

What does it ignore?

You propose changes to the project to change whatever you want to change, that's the beauty of open source 😄 Let everyone know how you would love to see all of this work and we can discuss and implement @ybelenko

**Comment by ybelenko** [comment]
> git clone https://github.com/directus/directus.git is enough

It doesn't contain `composer.json`, so I cannot add my own dependencies. I cannot add my own scripts to `composer.json`.

> it's possible with WP How?

I used that package to install WP https://packagist.org/packages/johnpbloch/wordpress-core-installer

> What does it ignore?

When WP is just a dependency installed out of `vendor` folder. Recommended `.gitignore` helps to hide all WP source files and track only changes in the `theme` folder, where user usually adds his implementation.

**Comment by ybelenko** [comment]
So, will `directus/directus` repo include `composer.json`? Or I should clone api and app repos in one folder somehow if I need that file? I'm 100% sure that I need it.

What I found related to topic yesterday:

You should choose composer package type which most fits for you. [The composer.json schema - Type](https://getcomposer.org/doc/04-schema.md#type)

[Setting up and using custom installers](https://getcomposer.org/doc/articles/custom-installers.md) - guide describes how to convert composer library into installer which downloads dependencies into folder outside of `vendor` when required. And what is more important you can extend `Composer\Installer\LibraryInstaller` class to do actions on package install(run SQL queries to setup database for instance, check PHP version and required extensions), on uninstall etc.

Also I found this package [composer/installers](https://packagist.org/packages/composer/installers). If I understand the purpose of this package correct, you can give an option for Directus plugin/extensions creators to install plugin by simple `composer require extension-author/directus-awesome-extension`. Anyway, somebody with native english can check this out, I'm not sure that I understand it correct. This package provided by Composer creators, so I would say that it's official solution.

**Comment by rijkvanzanten** [comment]
Yeah I'm pretty sure we'll add it in. I'm not 100% sure if that will be next release right away, as I need to make sure it doesn't have any unwanted side effects.

**Comment by benhaynes** [comment]
@rijkvanzanten @WellingGuzman — can we get this figured out and added in for this week's release? Would there be any potential side effects?

**Comment by WellingGuzman** [comment]
I don't think there's a side effect by including the file, but @rijkvanzanten is best suitable to get a better response on how to add this to the build process.

**Comment by ArshadVayani** [comment]
+1 we badly need this kind of setup.

**Comment by tassoman** [comment]
If it could help, I would like to suggest to add the other two base projects as dependencies, then filling this repo only with necessary configurations and files. I pretty enojy your choice! Go team! 😄 thank you!

**Comment by tassoman** [comment]
More, if you are concerned about "composer scared people" you can always build a binary zip filled with the whole and share it with its checksum for validation.
But I think its difficult avoiding composer for people who enjoy PHP7.x in 2019, don't be the wordpress guys 😁

**Comment by rijkvanzanten** [comment]
> if you are concerned about "composer scared people" you can always build a binary zip filled with the whole

That's basically how we treated the `master` branch in this repo with the `directus/api` repo being the composer-installable flexible version.

Changing the master branch to be two submodules and a composer.json file now would be a massive breaking change 🤔 

For now, we'll add the `composer.json` file out of the API repo in the next build (on directus/directus).

> don't be the wordpress guys

Ha, duly noted 😄

**Comment by rijkvanzanten** [comment]
We'll add this file to next the release so I'll close this now 👍

**Comment by dev7ch** [comment]
Just some thoughts:

A solution could be to make the `master` [READ ONLY] and a `dev` for contributions, CI Test, Composer based deploys or people who would like to have a strict composer deployment.

I am not 100% sure but in that condition I think you are able to fork the `directus/directus` and set your forked master upstream to the remote `dev` branch. (I didn`t test it)

To deploy different environment stages i like the awesome https://github.com/deployphp

You can easily install composer (example below) and all needed dependencies (including your own) to set up a php project from scratch.

```php
<?php
require 'vendor/deployer/deployer/recipe/common.php';

env('bin/composer', function () {
    if (commandExist('composer')) {
        $composer = run('which composer')->toString();
        
        if (isVerbose()) {
            writeln("Use global installed composer: " . $composer);   
        }
    }
    if (empty($composer)) {
        run("cd {{release_path}} && curl -sS https://getcomposer.org/installer | {{bin/php}}");
        $composer = '{{bin/php}} {{release_path}}/composer.phar';
    }
    
    $installYourPlugin= (has('installYourPlugin)) ? get('installYourPlugin') : true;
    
    if ($installYourPlugin) {
        run("cd {{release_path}} && ".$composer." global require \"you/your-plugin:^1.0.0\"");
    }
    
    return $composer;
});

env('composer_options', function() {
    $args = null;
    if (has('ignorePlatformReqs')) {
        $args = ' --ignore-platform-reqs';
    }
    return 'install --no-dev --verbose --prefer-dist --optimize-autoloader --no-progress --no-interaction' . $args;
});
```

**Comment by benhaynes** [comment]
Thanks @dev7ch — @WellingGuzman will review this as soon as he has time!

**Comment by rijkvanzanten** [comment]
> …and a dev for contributions, CI Test, Composer based deploys or people who would like to have a strict composer deployment.

This is already possible by using the directus/api and directus/app repositories. Adding a new dev branch to the combined directus repo will only add to the confusion in my opinion.
