### ISSUE TITLE
Custom fields for Users

### ISSUE THREAD

**Issue by kkar** [directus/directus#2274]
# Custom fields for Users

## It would be awesome if we had the option to add new fields just like in the collections.

**Comment by benhaynes** [comment]
# This exists now! If you add additional fields to `directus_users` they will show

**Comment by kkar** [comment]
@benhaynes I am sorry, but I am unable to find the page where I can add additional fields. Could you please explain where such functionality is located? Sorry again, but I really can't find it. (I have the latest version of Directus)

**Comment by benhaynes** [comment]
Ahh, the App doesn't show the Collections in the App, but you can add them manually in the database for now and it should work. Here is a ticket you can follow for when this will be possible within the App GUI:

https://github.com/directus/app/issues/830

**Comment by andgar2010** [comment]
Hi. @benhaynes 
I understand that you explained how to customize fields in directus_users table, but I want to place an M2O field from another self-created collection (not directus_ table). How to do it?

**Comment by benhaynes** [comment]
Just follow the normal M2O flow in field setup... no difference then.

https://docs.directus.io/guides/relationships.html#many-to-one

**Comment by andgar2010** [comment]
@benhaynes 
😳 I'm sorry I asked the wrong question before. I'm going to clarify how to do it with this diagram. I want to add an "area" field (from another collection) to "directus_user"
illustration:
![image](https://user-images.githubusercontent.com/19521054/73616752-6c002e80-45e5-11ea-9285-4f94684269ab.png)

**Comment by benhaynes** [comment]
Ahh, reversed! This would be a manually set up M2O on the Directus users table. We'll be making this available in the app soon, but for now you can set this up manually in the database.

**Comment by andgar2010** [comment]
Excuse me, how do you make manual adjustment from a database? 
I must do this:
`ALTER TABLE directus_user ADD FOREIGN KEY (area_id) REFERENCES area(id);`
Is correct, Automatically insert M2O on UI?

**Comment by benhaynes** [comment]
No, it's done through new records within `directus_fields` and `directus_relations`. we don't have official documentation for that since it's not officially supported. But you can look at how other many to one relationships are set up in the system tables to understand how it works.

**Comment by rdsubhas** [comment]
Even though the Admin UI doesn't show it, we can force navigate to it by hacking the URL to `admin/#/settings/collections/directus_users`

**Comment by benhaynes** [comment]
That sounds about right @rdsubhas — it's nearly possible/supported, but we haven't spent the time to formally get it working since we want to focus on stability/bugs first.

**Comment by rdsubhas** [comment]
This is one of those "nice quirks" we can live with for as long :) The workaround pretty much works for us. Thanks a lot @benhaynes :)
