### ISSUE TITLE
SDK type error on readItems when using 'datetime' literal

### ISSUE THREAD

**Issue by LewisMcReu** [directus/directus#22755]
### Describe the Bug

For the reproduction snippet compiled within my Angular 18 app, I'm getting a type error on the assignment of the read data to a variable of what I assume to be a compatible type, since it's the same as is defined on the Schema.

![image](https://github.com/directus/directus/assets/4019489/63bcf475-15f3-4fe9-9758-f462ade88c35)

The code as such won't compile.

### To Reproduce

Paste the following snippet in a TS file in an Angular 18 project. IntelliJ IDEA immediately marks the assignment of `ds` to `dummies` to be a problem. When compiling, the same issue gets shown in the log.

```typescript
import {createDirectus, readItems, rest} from "@directus/sdk";

type Dummy = {
  id: string;
  date: 'datetime';
}

type Schema = {
  dummies: Dummy[]
}

const client = createDirectus<Schema>("url").with(rest());

let dummies: Dummy[];

client.request(readItems('dummies')).then(ds => dummies = ds);
``` 

### Directus Version

v10.12.1 (@directus/sdk 16.1.0)

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Oracle 23.4.0.0

**Comment by br41nslug** [comment]
`Dummy` is your schema input type and will not equal the generated output type. https://docs.directus.io/guides/sdk/types.html#working-with-generated-output

**Comment by LewisMcReu** [comment]
@br41nslug So if I understand correctly, we should use different types for our schema vs the output of the client?

**Comment by rijkvanzanten** [comment]
I believe he's saying that the generated output type of the SDK can be different from the defined schema specific input into the SDK constructor. You can actually see it in your screenshot as well. The type of `ds` is `ReadItemOutput<..>[]` rather than just `Dummy[]`
