### ISSUE TITLE
Flows logs are not shown in flow sidebar

### ISSUE THREAD

**Issue by pmorin17** [directus/directus#22753]
### Describe the Bug

I tried to create some basic flows just to see what I could do with this feature and I noticed that I don't see any logs in the flow sidebar.
I created a basic flow with a manual trigger and a "Log to console" operation. I can see the logging in the console, but I don't see anything under "Logs" in the flow sidebar.

### To Reproduce

1. Create a new flow with a manual trigger
2. Manually trigger the flow
3. Navigate back to the flow
4. In the flow sidebar, it shows "No logs yet"

### Directus Version

v.10.12.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

MSSQL

**Comment by br41nslug** [comment]
Make sure your flow is set up to track logs. 
![image](https://github.com/directus/directus/assets/9389634/8f383ca1-216d-4ced-835f-86bdcf8ece79)
