### ISSUE TITLE
docker-compose up  installation fails

### ISSUE THREAD

**Issue by tvld** [directus/directus#2275]
First time heard of Directus thinking to use it for our new app development department... though to fire up Docker (as we only use Docker for all we do). 

# First Attempt Bug Report
## Steps to Reproduce - First Attempt, with **api**

1. Run ``git clone https://github.com/directus/api.git``
2. Go to api folder ``cd api``
3. Run ``docker-compose up``
4. Containers seem to run and ``api-php-apache`` log works ...but...
5. Visiting ``http://localhost:8080/`` gives:

## Expected Behavior
I expect to see the Directus installer?

## Actual Behavior
```
Warning: require(/var/www/html/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/src/web.php on line 7

Fatal error: require(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/src/web.php on line 7
```
# Second Attempt with **app**

This works, on ``http://localhost``, but app connects to the demo cloud database.. I assume I can change config parameters to connect to the api as above, but I decided to try suite first..

# Third Attempt  with **suite**
Same procedure as above with __api__ 

## Visiting http://localhost:8080
but now when I visit ``http://localhost`` I get an unfriendly and insecure, as too much info for hackers, error message:
```

Fatal error: Uncaught UnexpectedValueException: The stream or file "/var/www/html/logs/error.2019-01-02.log" could not be opened: failed to open stream: Permission denied in /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107 Stack trace: #0 /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\Handler\StreamHandler->write(Array) #1 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\Handler\AbstractProcessingHandler->handle(Array) #2 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(707): Monolog\Logger->addRecord(400, 'Directus\\Except...', Array) #3 /var/www/html/src/core/Directus/Application/CoreServicesProvider.php(204): Monolog\Logger->error('Directus\\Except...') #4 [internal function]: Directus\Application\CoreServicesProvider->Directus\Application\{closure}(Object(Directus\Exception\NotInstalledException)) #5 /var/www/html/src/core/Directus/Hook/Emitter.php(291): call_user_func_array(Object(Closure), Array) #6 in /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107
```
## Visiting http://localhost:8080/admin
I get login prompt, but ``admins@example.com`` and ``password`` does not work and the login window shows in small red print: `` Unknown error. Try again later. ``
### Expected
I would have assumed to be able to set up first admin user... 

## Note
[Installation manual](https://docs.directus.io/advanced/other-install-methods.html#manual) for Directus on Docker is missing, so I have no clue if I even got the right repository.... 

## Technical Details

- Device: Dell XPS15-9560
- OS: Ubuntu 18.04
- Install Method: Docker

### Some thoughts:
For first time user and experienced professional, two hours struggle to just fire up a simple docker container and no progress at all, is not encouraging )).... It's time for a coffee )))

**Comment by shealavington** [comment]
As you cloned the API, you would need to install manually, you won't see an installer, that only comes with the Suite.

Looks like it couldn't find the config file (when you cloned /API and used docker). Did you create the config, and import the databse schema? 

https://docs.directus.io/advanced/app/standalone.html#configuration

**Comment by tvld** [comment]
Thank you...
> As you cloned the API

I had _three_ attempts, including the Suite, where I never saw installer as well. 

> On another note, if you can provide versions for your PHP & MySQL,

As you read, I am running _Directus_ Docker... which comes with PHP and MySQL obviously. 

>  As it's failing to search for the API config

When I just copy ``/config/api-sample.php`` to ``/config/api.php``  The suite fails completely. Clearly api-sample.php has mistakes in it?

>Did you create the config, and import the database schema?

Really? Containers have been invented to exactly mimic our dev stations (5) test suites (2) and production (3) servers. Additional commands jeopardize our production flow...  For the sake of it, how can I import database schema? I could not find link to the documentation

**Comment by tvld** [comment]
@shealavington  I might be direct in my sharing of experience but I would not spend time if we are not seriously interested to use and contribute. Sorry for the misunderstanding.

What I understand now that it is misconception of the use of Docker. As you can see [here ](https://github.com/directus/directus/blob/master/docker-compose.yml) Directus ``docker-compose`` pulls in the _latest version_ by itself. You do not have direct control over the PHP version, that's what the compose file does for you :)

In addition, there is no direct command interface for the database, for the same reason. That's why I cant import a schema without explicit Directus tools. Of course, I can go into a container, which is imho not how containers should work on first install. But I could and run the manual schema import. If needed, I will be glad to take it from there. 

But, as I said, being new on this project, I would like to follow convention first before sharing my 2 cents ))

**Comment by shealavington** [comment]
I see, so the latest versions would've been fine to say 😋 

I'm afraid I don't think there's anything I can do to help, sorry.

The best advice I can offer is to follow the manual install process to get your database working so you can link your API to it.

Sorry I can't be much more help.

**Comment by rijkvanzanten** [comment]
@tvld We're moving away from the included Dockerfile to this stand alone repo https://github.com/directus/docker. It's still an early version, but there's a bigger community of docker devs working on it and available to answer questions 😄

**Comment by tvld** [comment]
ah, ok, thanks Rijk. Maybe good to remove the docker files then from the other repo's to avoid confusion )
