### ISSUE TITLE
The s3 file health-xxxxx generated by the health check was not cleared successfully

### ISSUE THREAD

**Issue by theowenyoung** [directus/directus#22763]
### Describe the Bug

I'm using Backblaze as s3 service, I can see the bucket has many `health-xxx` files, it looks like generated by the endpoint `/server/health`

![CleanShot 2024-06-16 at 01 24 01@2x](https://github.com/directus/directus/assets/62473795/45e81203-19a6-4ef3-8bfe-4767071cdf00)

### To Reproduce

Deploy a new instance with Backblaze s3 config.

### Directus Version

v10.12.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

sqlite

**Comment by the-other-dev** [comment]
Could it be that these files are not cleaned up when there is a timeout? We can configure the health check threshold, see https://docs.directus.io/self-hosted/config-options.html#file-storage

Would it be possible to configure the storage path for the health check? That would make it easier to configure S3 lifecycle policies to clean up these health check files?

**Comment by theowenyoung** [comment]
Thank you , I'll try to increase `STORAGE_S3_HEALTHCHECK_THRESHOLD` to 5000, the default value is 750 ms

**Comment by theowenyoung** [comment]
Just tested it and it works now! Thank you very much for your help!
