### ISSUE TITLE
Relational groupBy not implemented

### ISSUE THREAD

**Issue by rickyitexpert** [directus/directus#22779]
### Describe the Improvement

**Improvement**
Directus has relational Sort implementation but doesn't have relational groupBy implementation.

Logic for relational groupBy would be same as sort. 

It will help in getting relational collection unique rows when fields are fetch &  groupBy is used on relation collection by applying  on rootCollection with left joins and fields are fetch from another relatedCollection.

**Use Case** 

Let say we have filter 15000 rows of data from directus api but limited it to 15 rows only for performance. For additional filtering we need product dropdown selection but this select  must not contain all products but the products which are in these 15000 datasets out of let say 1000000 and those valid products are just 5. so we wont be loading 15000 products rows repeated which will results in large array processing and network transfer

If above groupBy on relation collection is implemented. it will help is passing same params with group by option on any relational collection and will be transferred of network and processed in effecient way.

**Comment by rijkvanzanten** [comment]
The current groupBy implementation is only applicable in combination with the aggregation query parameter, so I don't think supporting relationships in there really achieves the use case you're describing. This feels like a bigger discussion around supporting grouping globally and then supporting relationships, which I'm happy to take [a new Feature Request](https://github.com/directus/directus/discussions/new?category=feature-requests) for 👍🏻 

I'll close this for now as it's not a small tweak ready to be implemented in the platform yet. Thanks!
