### ISSUE TITLE
Some operations are missing when querying via `/operations` endpoint

### ISSUE THREAD

**Issue by antongit** [directus/directus#22770]
### Describe the Bug

When querying operations via `/operations` endpoint some operations are missing.
I know that an operation exists, it is there in the UI and also listed in the Flow, when pulling `/flows`.
Querying that operation directly via `/operations/:id` returns the operation correctly.

I'm querying these endpoints as Admin.

### To Reproduce

Can't really catch when it happens, but I'm suspecting, that maybe these are the operations copied via `Copy To...` in the UI.

### Directus Version

v10.12.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

sqlite3

**Comment by br41nslug** [comment]
I am unable to reproduce the issue, if there were operations missing there then those would also not be shown in the App when editing/viewing flows.

Be aware that the Trigger is not an operation.
