### ISSUE TITLE
auth/refresh 400 error

### ISSUE THREAD

**Issue by ranaharoon3222** [directus/directus#22798]
### Describe the Bug

I'm trying to use sameless SSO with Github oauth2 provider. I do all configuration guide that provided in directus single sign-on docs. But the problem is when i redirected to page that i specified in auth/login/github url, the cookie is successfully set but when i sending refresh token request without payload  **credentials: 'include** to get access_token, always give me 400 error and it seems it can't read directus_refresh_token from cookies.

### To Reproduce

Just send a post request without payload to auth/refresh with   credentials: 'include'  after redirected to my page. my directus server is on docker and my front running locally.

when i manually checked the cookies after login, the directus_refresh_token was successfully set

Sending request

 await fetch('https://one-api.13.77.2.205.sslip.io/auth/refresh', {
            method: 'POST',
            credentials: 'include',
            body: JSON.stringify({ mode: 'session' }) 
        });

       - 'PUBLIC_URL=https://one-api.13.77.2.205.sslip.io'
      - 'AUTH_GITHUB_ACCESS_URL=https://github.com/login/oauth/access_token'
      - 'AUTH_GITHUB_AUTHORIZE_URL=https://github.com/login/oauth/authorize'
      - AUTH_GITHUB_CLIENT_ID=Ov23li...
      - AUTH_GITHUB_CLIENT_SECRET=a35b6....
      - AUTH_GITHUB_DRIVER=oauth2
      - 'AUTH_GITHUB_PROFILE_URL=https://api.github.com/user'
      - AUTH_PROVIDERS=github
      - AUTH_GITHUB_ALLOW_PUBLIC_REGISTRATION=true
      - 'AUTH_GITHUB_REDIRECT_ALLOW_LIST=http://localhost:3000'
      - AUTH_GITHUB_MODE=session
      - SESSION_COOKIE_DOMAIN=one-api.13.77.2.205.sslip.io
      - SESSION_COOKIE_SECURE=false
      - SESSION_COOKIE_SAME_SITE=lax
      - CORS_ENABLED=true
      - CORS_ORIGIN=http://localhost:3000

### Directus Version

latest:10

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgres

**Comment by br41nslug** [comment]
Make sure you are either running `localhost` (for local development) or on a domain with `https://` and have `SESSION_COOKIE_SECURE` set to `true`.

`directus_refresh_token` is not applicable here since you're using `session` tokens.

**Comment by ranaharoon3222** [comment]
thanks

> Make sure you are either running `localhost` (for local development) or on a domain with `https://` and have `SESSION_COOKIE_SECURE` set to `true`.
> 
> `directus_refresh_token` is not applicable here since you're using `session` tokens.

**Comment by weboblige** [comment]
Hello,
You marked it as completed. Can you please give us the solution?
Thanks

**Comment by ranaharoon3222** [comment]
i changed my command to this 

`    "dev": "next dev --experimental-https -H haroon.dev", `

and use https in local development so all work great

**Comment by ranaharoon3222** [comment]
i used Next js as my frontend

**Comment by weboblige** [comment]
Thanks :-)
