### ISSUE TITLE
File Library card thumbnails dissapear when adding a relation to itself

### ISSUE THREAD

**Issue by stepugnetti** [directus/directus#22807]
### Describe the Bug

When I add to the `directus_files` collection a field of type Image (Settings -> Data Model -> System collections -> directus_files) relating the collection to itself, the cards in the File Library are displayed with an icon ("insert_drive_file") instead of a thumbnail. Is this expected?

### To Reproduce

Click Settings -> Data Model -> System collections -> directus_files.
Add a field of type Image.
Browse to File Library.

### Directus Version

v10.12.1, v10.11.1, v9.21.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 12

**Comment by stepugnetti** [comment]
My use case is that I want to enable the User to upload a preview image for those files which are not images themselves. I don't expect this preview to be shown in File Library though, I just want to enable the User to upload it. I did not expect that adding this field to `directus_files` would disable thumbnail previews of image files as well.

**Comment by br41nslug** [comment]
What happens is the layout picks the wrong "image source" to display.
![image](https://github.com/directus/directus/assets/9389634/ec842262-e2e6-4fe3-8839-655a44ccf09d)

Setting that back to thumbnail after adding the custom field will solve it for you :)
![image](https://github.com/directus/directus/assets/9389634/e6ad0b7d-be26-4c0d-8441-b6e8c76343f2)
