### ISSUE TITLE
Does anyone have turtorial to intergrate AWS X-ray with Directus on ecs fargate?

### ISSUE THREAD

**Issue by huypd6946-cowell** [directus/directus#22813]
### Describe the Bug

I want to intergrate AWS X-ray with Directus on ecs fargate but not found any posts about this. I need your help.

### To Reproduce

I want to intergrate AWS X-ray with Directus on ecs fargate but not found any posts about this. I need your help.

### Directus Version

10.x.x

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
Heya! Issues are specifically for tracking issues of the Directus itself. Any question, including this one, are better placed in our [Community Discord](https://directus.chat).
