### ISSUE TITLE
`module_bar` in settings doesn't take an array. 

### ISSUE THREAD

**Issue by hamzace** [directus/directus#22814]
### Page

https://docs.directus.io/reference/system/settings.html

### Describe the Inaccuracy

Hey everyone,

I'm trying to enable/disable modules using the SDK, according to the [doc](https://docs.directus.io/reference/system/settings.html) and your code I should fill up the `module_bar` field using an array of `{ type, id, enabled, locked }` objects. However the typescript type checker is annoyed as this `module_bar` actually takes only `"json"` or null.

I'm not sure how I can perform this, any lead is appreciated.

**Comment by br41nslug** [comment]
Before suggesting an improvement could you please elaborate on the error you're seeing that makes "typescript type checker is annoyed"
