### ISSUE TITLE
Filtering a collection using comparison operators on String fields results in 400 Bad Request Error

### ISSUE THREAD

**Issue by knassik** [directus/directus#22822]
### Describe the Bug

Hi there,

I am encountering an issue when attempting to filter a **Team** collection using comparison operators on fields of type `String`. The collection has the following structure:
- **id**: UUID;
- **first_name**: String;
- **last_name**: String;
- **job_title**: String;
- [ ... other collection fields ].

When I use an equality operator (_eq) to filter the collection, it works without any problems. The bellow GraphQl queries are working just fine:

```javascript
// Filter by ID:
query {
    team ( filter: { id: { _eq: "some-private-id" } } ) {
        id
        first_name
        last_name
        job_title
    }
} 

// Filter by first_name:
query {
    team ( filter: { first_name: { _eq: "Obi-Wan" } } ) {
        id
        first_name
        last_name
        job_title
    }
} 
``` 

However, when I try to filter using comparison operators like `_gt`, `_gte`, `_lt`, `_lte`, etc., on a field of type `String`, I get a `400 Bad Request` error. Here is an example:
```javascript
query {
    team ( filter: { first_name: { _gt: "O" } } ) {
        id
        first_name
        last_name
        job_title
    }
} 
``` 

I don't know if I missed something, or if I'm incorrectly using the framework, but I think that comparison operators are not supported for the `String` type fields, which would be very useful to have in some use cases.

If there is a workaround or if additional information is needed, please let me know.

Thank you very much for your assistance.

### To Reproduce

1. Create any collection with a `String` field.
2. Write a GraphQl query to fetch the data from the created collection using a comparison operator.
3. The server responds with a `400 Bad Request` error.

### Directus Version

v10.12.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

MySQL v8.0.36

**Comment by br41nslug** [comment]
Im closing this issue for now as this is expected behavior, comparing strings using numeric operators can be done in a variety of ways however these can be very unintuitive if that method of assigning a number to a string does not match you're usecase.

For example which of these examples would be "expected behavior"?
```
"AAAA" > "AA" ? true if looking at string length or false alphabetically
"10" > "5" ? true if length or number based or false alphabetically
"6HSFPAmfAR" > "6mfPFfseZ" ? 
```

However please do feel free to create a feature request instead.

**Comment by knassik** [comment]
Thank you for your response. I understand the concern regarding the ambiguity of comparison methods for strings. However, I believe that the handling of string and other data type comparisons should be delegated to the database, as databases have well-defined and widely accepted methods for these operations.

If we consider that the Team collection contains the following values:
```javascript
id: 1, first_name: 'AAAA'
id: 2, first_name: 'AAA'
id: 3, first_name: 'aa'
id: 4, first_name: 'Obi-Wan'
``` 

We would expect that the following GraphQL query:
```javascript
query {
    team(filter: { first_name: { _gt: "AA" } }) {
        id
        first_name
    }
}
``` 

Returns the result:
```javascript
id: 1, first_name: 'AAAA'
id: 2, first_name: 'AAA'
id: 4, first_name: 'Obi-Wan'
``` 

Which is the same result as the SQL query:
```javascript
SELECT * FROM team WHERE first_name > 'AA';
``` 

Since MySQL compares strings lexicographically based on the character set and collation defined for the column or database. Which means that strings are compared character by character using their ASCII or Unicode values.

And the expected output of your examples should be:
```javascript
'AAAA' > 'AA';               -- Returns TRUE
'10' > '5';                  -- Returns FALSE (lexicographically "1" < "5")
'6HSFPAmfAR' > '6mfPFfseZ';  -- Returns FALSE (lexicographically "H" < "m")
```

I hope this clarifies my perspective on handling string comparisons., if there are any further questions or considerations, please let me know. Meanwhile, I will open a feature request explaining the specific use case I need.
