### ISSUE TITLE
Order of "Related Collection" tables is not alphabetically

### ISSUE THREAD

**Issue by rowild** [directus/directus#22825]
### Describe the Bug

When creating a collection with any of the m:n / m2a / etc relationships, the "Related Collection" dropdown never pops up alphabetically. This is particularly cumbersome, when the project contains of dozens of m:m relationships. 

I would like to suggest to provide an option to sort those tables alphabetically and/or provide a (fuzzy) filter.

Even though I report this with Directus v10.12.1 this already happens since v9. 

### To Reproduce

1. Create a collection (e.g. "test-collection") and many more other collection to which this table should have a relation (e.g. "one_relation_table", "second_relation_table", "third_relation_table"); use non-alphabetical terms.
2. in "text_collection" create a one2many or many2many or many2all field.
3. Choose a related table. Those tables pop up in non-alphabetical order

The following screenshot are from my personal setup and showcase the problem for each relational table:

![01](https://github.com/directus/directus/assets/213803/3b691cee-4d2f-4bad-a55f-4a945aeab8e8)
![02](https://github.com/directus/directus/assets/213803/b43dfc6c-1734-484e-a23d-656fd318c2e8)
![03](https://github.com/directus/directus/assets/213803/7355615e-3027-4525-898f-dcc867a62024)
![04_m2a](https://github.com/directus/directus/assets/213803/4459aa6f-94f0-495b-aa8a-6b1be2d14303)
![05_m2m](https://github.com/directus/directus/assets/213803/0aa95fa2-f142-49e0-84de-69de441f2cad)
![06_o2m](https://github.com/directus/directus/assets/213803/4a96e724-bc02-48b3-9c8f-f82a147b3bd1)
![07_treeView](https://github.com/directus/directus/assets/213803/dbd8bb8b-f529-4e7c-b4f6-14c9fe475edf)
![08_m2o](https://github.com/directus/directus/assets/213803/221b1e55-4047-48bc-8255-fa08d5c1ff52)

### Directus Version

10.12.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

sqlite3

**Comment by br41nslug** [comment]
The dropdowns for relational collections doesnt get sorted alphabetically because it renders in the way you've sorted the collections in your instance:
![image](https://github.com/directus/directus/assets/9389634/bb6de38e-b494-460a-b685-b65df52fe59f)
![image](https://github.com/directus/directus/assets/9389634/cdeacde0-eb8c-4052-8180-072086d5a3e0)

re-ordered:

https://github.com/directus/directus/assets/9389634/a598cbeb-17f8-4f68-9335-ac30b538aca5

**Comment by hanneskuettner** [comment]
Additionally there is currently a bug related to sorting grouped collection. See this PR #22392

**Comment by rowild** [comment]
@br41nslug Thank you very much for providing a video!!! What a service!
@hanneskuettner Thank you, too, for pointing me to the link!

Am I right when I assume that grouping collections in dedicated folders does not influence the order either? I moved all my mm-tables into an mm-folder as shown in the screenshot (and I have lots of those).

![dedicated folders for collections](https://github.com/directus/directus/assets/213803/491462ab-ce9c-41e5-b625-3953d83887e9)

Also, what do you guys think about the idea of implementing a fuzzy search / filter for those fields? Would it be at all possible? What would be arguments against this idea?

**Comment by MarkBurvs** [comment]
I'm confused by this. The order of the collections in the Related Collection dropdown selector doesn't remotely resemble the order of the Collections in my own Data Model as @br41nslug's video suggests it should. It's always just a complete random jumble for me.

As my project is growing, this is becoming a serious pet-hate. 

The list of Collections when you're setting up a Flow trigger is always alphabetical and it's so much easier. I'm sure somewhere else there is a similar selector for Collections which has a fuzzy search box as @rowild suggests, but I can't remember where I've seen this right now. 

I would seriously love a fix for this. I'm so bored of scrolling up and down that list trying to find the one I'm looking for.
