### ISSUE TITLE
Inaccuracy on "Data Model" page

### ISSUE THREAD

**Issue by r1010a** [directus/directus#22821]
### Page

https://docs.directus.io/app/data-model.html

### Describe the Inaccuracy

This paragraph:

> To do this, we can remove the author_name column from the blog table and replace it with an author_id foreign key table, which stores foreign keys from the users table.

should be:

> To do this, we can remove the author_name column from the blog table and replace it with an author_id foreign key column, which stores foreign keys from the users table.

**Comment by hanneskuettner** [comment]
Heya! Thank you for pointing that out. We'd be happy to accept a post request for that quick fix!
