### ISSUE TITLE
Directus SDK doesn't return file relational data

### ISSUE THREAD

**Issue by chrcit** [directus/directus#22833]
### Describe the Bug

Directus SDK seems to "swallow" the REST response for file relational data. 

I'm reading an item like this
```
const data = await directusClient.request(
    readItems('contact_page', {
      fields: [
        '*',
        {
          tree: ['slug'],
        },
        {
          locations: ['*'],
        },
        {
          documents: [
            '*',
            {
              file: ['*'],
            },
          ],
        },
        {
          locations: [
            '*',
            {
              people: ['*'],
            },
          ],
        },
      ],
      filter: {
        bundesland: {
          _eq: state,
        },
      },
    }),
  )
```

Which results in the following request being sent to the Directus instance:
```
https://stage-cms.meinbezirk.at/items/contact_page?fields=*%2Ctree.slug%2Clocations.*%2Cdocuments.*%2Cdocuments.file.*%2Clocations.*%2Clocations.people.*&filter=%7B%22bundesland%22%3A%7B%22_eq%22%3A%22burgenland%22%7D%7D
```

Here the correct data is being returned (including the file relational data).

But when logging the result from the SDK call the file relational data is missing:
```
...,
documents: [
    {
      id: 2,
      user_created: '5e58ecdf-8495-4ed7-a86e-6d99d6e6b3c1',
      date_created: '2024-02-26T13:14:19.000Z',
      user_updated: 'fe685643-90be-46e9-9ff2-3f5d238b2126',
      date_updated: '2024-06-24T11:16:26.000Z',
      filename: 'Tarife Print und Online',
      link: 'https://www.regionalmedien.at/wp-content/uploads/2022/12/Tarif_2024_20231220.pdf',
      sort: 1,
      contact_page_id: 1,
      file: '3915266f-7c34-49bd-b9d8-9109c22a6d57'
    },
    {
      id: 1,
      user_created: '5e58ecdf-8495-4ed7-a86e-6d99d6e6b3c1',
      date_created: '2024-02-26T13:13:46.000Z',
      user_updated: 'fe685643-90be-46e9-9ff2-3f5d238b2126',
      date_updated: '2024-06-24T11:16:26.000Z',
      filename: 'Mediadaten',
      link: 'https://www.regionalmedien.at/wp-content/uploads/2024/03/1_RegionalMedien_Salzburg_stellen-sich-vor_2024-04-04.pdf',
      sort: 2,
      contact_page_id: 1,
      file: 'e5228c24-6d00-4ae6-bfc9-1d179e63baeb'
    }
  ],
...
```

So to me it seems like the SDK is internally removing this extra data for some reason. I upgraded to version `16.1.0` (latest) just to be sure this is an active bug! 

### To Reproduce

- Setup Directus with an item which has a file relational
- Do a readItem request which includes the relational file data 

### Directus Version

v10.10.7

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Are you authenticating your request? And does that user have access to files?
Most often if you're missing data from your API requests it is a permission issue.

> So to me it seems like the SDK is internally removing this extra data for some reason.

The SDK is a lightweight fetch wrapper and doesnt do any data manipulation out of the box, the log you're seeing is 1on1 what the API returns.

I am unable to reproduce the issue using the given reproduction steps:

![image](https://github.com/directus/directus/assets/9389634/71288e1a-b2cf-4f07-ae3e-fa6f41fbfafa)

1. result using admin credentials:

```ts
[
  {
    "id": 1,
    "file": {
      "id": "e025d1b0-783d-481f-a7c4-b7ef14a81cbc",
      "storage": "local",
      "filename_disk": "e025d1b0-783d-481f-a7c4-b7ef14a81cbc.jpg",
      "filename_download": "0pHFv4ndDOBosfefX2qr_aaWsreImW9NvO4QkEFQCOI.jpg",
      "title": "0p H Fv4nd Do Bosfef X2qr Aa Wsre Im W9 Nv O4 Qk Efqcoi",
      "type": "image/jpeg",
      "folder": null,
      "uploaded_by": "e4603e10-8233-48fd-9253-763cf4cf5186",
      "uploaded_on": "2024-06-05T11:30:45.678Z",
      "modified_by": null,
      "modified_on": "2024-06-05T11:30:45.701Z",
      "charset": null,
      "filesize": "1166463",
      "width": 4383,
      "height": 1745,
      "duration": null,
      "embed": null,
      "description": null,
      "location": null,
      "tags": null,
      "metadata": {},
      "focal_point_x": null,
      "focal_point_y": null,
      "test": null
    }
  }
]
```

2. result using test credentials:

```ts
[
  {
    "id": 1,
    "file": null
  }
]
```

**Comment by chrcit** [comment]
Thanks for the swift response!

You were correct about the permissions. The file in general was readable to the public due to a folder filter but none of the fields were accessible and thus Directus returned just the file id.
