### ISSUE TITLE
FilesService: filename_disk ignored

### ISSUE THREAD

**Issue by stx-chris** [directus/directus#22846]
### Describe the Bug

When using `uploadOne(...)` from `FilesService` in a custom endpoint, the parameter `filename_disk` is ignored since it is set to a fixed value in the code, see [here](https://github.com/directus/directus/blob/68898441f19550450fa4cfaba435f823e7aa8e6f/api/src/services/files.ts#L42)

```
   // The filename_disk is the FINAL filename on disk
   payload.filename_disk = primaryKey + (fileExtension || '');
```

### To Reproduce

When uploading a csv-file `my_sample.csv` like this:

```
       const data = {
		storage: "mystorage",
		type: "text/csv",
		filename_disk: fileName,            // <---- IGNORED
		filename_download: fileName
	};

	var stream = new Readable();
	stream.push(content);
	stream.push(null);

	const id = await filesService.uploadOne(stream, data);
```

the file is created as `{id}.csv` instead of `my_sample.csv` as specified in the storage. I'm using Cloud Storage but seems to be the same for all storages.

### Directus Version

v10.12.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL

**Comment by rijkvanzanten** [comment]
Originally, all file modifications and actions relied on the primary key being the filename. That was changed a long time ago, so this might be the last holdover from having a hardcoded filename on disk.
