### ISSUE TITLE
Calendar View does not refresh when switching content type

### ISSUE THREAD

**Issue by jbmolle** [directus/directus#22854]
### Describe the Bug

When we have two content types, each with a calendar layout, the calendar won't refresh when we switch from one content type to the other.

### To Reproduce

Let's create 3 content types:
- Cleaner: firstname, lastname
- Schedule: cleaner.lastname, start_cleaning_date, end_cleaning_date
- Holidays: cleaner.lastname, start_holiday_date, end_holiday_date

Cleaner content is displayed as a table.
Schedule and Holidays are displayed as Calendar Layout with display template cleaner.lastname and start date / end date respectively start_cleaning_date / end_cleaning_date and start_holiday_date / end_holiday_date.

If we go on Schedule content everything looks good. We can then switch to cleaner table and then holiday content.
But if we switch from schedule content directly to holiday content or vice versa, the layout is not updated.
We get an error in Firefox developer console: "TypeError: e is undefined"
It probably comes from the fact that the Vue component is not unmounted / remounted and probably calls a value that should not be undefined after onMounted.

### Directus Version

v11.0.0-rc.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 15

**Comment by jbmolle** [comment]
When I run the app locally with pnpm --filter app run dev and link it to api on 8055, it works.
But when I use the Docker image v11.0.0-rc.2 it doesn't.
I get an error "Cannot read properties of undefined (reading 'match')"
I guess the error is in date-fns /src/parse/_lib/utils.ts line 28 where dateString is undefined.
This is called in Directus layouts/calendar/index.ts line 314 with date-fns parse function.
We have `const date = parse(item[endDateField.value], 'yyyy-MM-dd', new Date());` but parse doesn't accept undefined value.
item is of type Item which is a Record<string, any> and we check that endDateField.value is not null but item[endDateField.value] can be null so maybe we should check `if (endDateField.value && item[endDateField.value]`

**Comment by hanneskuettner** [comment]
Just to verify, you're running into this problem with an admin account?

**Comment by jbmolle** [comment]
Yes with an admin account.

**Comment by jbmolle** [comment]
And just when I switch from Calendar to Calendar. If I switch from Calendar to a Table Content and then to a Calendar I don't have the problem
