### ISSUE TITLE
/admin takes me to login screen not installed

### ISSUE THREAD

**Issue by thepurpleblob** [directus/directus#2286]
# Bug Report

## Steps to Reproduce

Following https://docs.directus.io/getting-started/installation.html#setup

1. Cloned from git
2. Ran composer install
3. Pointed apache alias to /public directory
4. Brought up website. 
5. Got error about using /admin
6. Put /admin on the end. Got a login screen with "Couldn't reach API" message in Red]
stuck

## Expected Behavior

I was expecting some sort of installation process

## Actual Behavior

As above, stuck on login screen

## Technical Details

- PHP Version: 7.2
- Database: Didn't get that far
- Install Method: cloned `master` branch

**Comment by thepurpleblob** [comment]
Ok - Apache needs 'AllowOverride On' to enable the .htaccess file. 

A line in the instructions would have saved me a lot of time :)

**Comment by WayneEld** [comment]
@thepurpleblob maybe check this Medium post out. https://medium.com/directus/installing-directus-7-on-lamp-defc9c5b63e1

 Helped a lot and presented an installation process, as you intended in your comment

**Comment by thepurpleblob** [comment]
The Medium post is spot on. 

As I mentioned, just a one line to alert to mod-rewrite in the main docs would have been nice

**Comment by WellingGuzman** [comment]
I added a short note to the docs about `mod_rewrite` and `AllowOverride` with https://github.com/directus/docs/commit/04d75aa6a68d35df186e19e7acd1b8c9711a019a.

**Comment by benhaynes** [comment]
I'll consider this one closed, let us know if there is additional info that would make this even clearer/easier!

**Comment by thepurpleblob** [comment]
That's great - thanks!

**Comment by ethanchen** [comment]
I'm using `mattrayner/lamp` docker to install directus and has checked that `mod_rewrite` and `AllowOverride` enabled, but I also get the same issue.  It directly take to login page and get 'Couldn't reach API' message. I check the .htaccess but have no idea. Is there any better way to debug ?

**Comment by thepurpleblob** [comment]
Just to note that this isn't mentioned in the github installation readme. That's a shame, because that's where the 'Download' button from the main website leads you.

**Comment by motorvor** [comment]
I too am having the same issues described above. Mod_rewrite and AllowOverride are both enabled, I've set the document root to be directus, but when I navigate to /admin, nothing is found. If I go to /directus/public/admin, then the login screen appears but it errors out with an 500 error with SSO endpoint. I know there has to be something I'm missing here, but I'm not sure. Any help would be appreciated. Thanks
