### ISSUE TITLE
Allow filter operators like _gt _lt _gte _lte on string fields

### ISSUE THREAD

**Issue by datnv9** [directus/directus#22868]
### Describe the Improvement

We need to filter some manual entered (string) id fields like `code` between `M001001` and `M001010`

**Comment by knassik** [comment]
Hi @datnv9,

I have the same issue, I already opened an issue ( #22822 ) 5 days ago, I wondering if we have the same use case...

**Comment by br41nslug** [comment]
There is not enough detail here to implement this without discussion as a "tiny tweak" so i'll be closing this issue for now. Feel free to open a [feature request](https://github.com/directus/directus/discussions/new?category=draft-feature-requests) instead 😄
