### ISSUE TITLE
Docs menu collapses on third level menu

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#22898]
### Describe the Improvement

Currently the docs menu collapses in cases where a page is selected which is part of a third-level menu. Nothing big, but feels a bit annoying when switching between different docs of a section:

[Bildschirmaufnahme 2024-07-02 um 13.53.43.webm](https://github.com/directus/directus/assets/46492597/2f430e48-e355-44a8-bf3f-b7d4521e0639)

**Comment by rijkvanzanten** [comment]
@phazonoverload marking this as assigned and blocked seeing that this whole setup is being replaced by you already 🙂

**Comment by phazonoverload** [comment]
Death to third level menus! Probably also death to second level menus! My WIP new docs platform doesn't have any collapsible menus, though we'll see how they feel once all pages are in.

**Comment by phazonoverload** [comment]
We are currently working on a complete overhaul of our docs - including platform, content, and structure. As that project is being worked on, I am going to close this issue as it's already acknowledged and handled within this work. We're expecting to launch it this fall.

**Comment by phil-sola** [comment]
Any ideas on when these new docs will be released? The current docs are awful and this behavious or closing menu items makes them unusable without wasting a lot of time. 

Super excited to hear efforts on the docs are being made and excited to see what comes next!
