### ISSUE TITLE
Can't filter records by GeoJSON data after update to latest version

### ISSUE THREAD

**Issue by ubzor** [directus/directus#22893]
### Describe the Bug

Hi! I'm just upgraded from `v9` to `v11.0.0-rc.2` and filters that use `_intersects_bbox` operator are not working anymore.
I've tried to modify the query as in [this answer](https://github.com/directus/directus/issues/10869#issuecomment-1807276072) but result is the same.

### To Reproduce

Create collection `some_collection`, add field `some_field` of type Coordinates (Point) to it, assign permissions, fill in some data and check this query:
```
items/some_collection?filter={"some_field":{"_intersects_bbox":{"type":"Polygon","coordinates":[[[33.7,43.9],[39.1,43.9],[39.1,39.2],[33.7,39.2],[33.7,43.9]]]}}}
```
The result is:
```
You don't have permission to access field "type" in collection "some_collection" or it does not exist. Queried in root.
```
Also tried this query (as of [this answer](https://github.com/directus/directus/issues/10869#issuecomment-1807276072)):
```
items/some_collection?filter={"some_field":{"_intersects_bbox":{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[33.7,43.9],[39.1,43.9],[39.1,39.2],[33.7,39.2],[33.7,43.9]]]}}}}
```
This produces almost the same error:
```
You don't have permission to access fields "geometry", "type" in collection "some_collection" or they do not exist. Queried in root.
```

### Directus Version

v11.0.0-rc.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

mysql:5.7 with geojson

**Comment by hanneskuettner** [comment]
Heya! Thank you for reporting this! This is most likely an oversight when migrating to policies on our end. I will have a look later today and report back.

**Comment by paescuj** [comment]
Fixed in #22915

**Comment by ubzor** [comment]
Thank you for fixing it! One more question - we are using Directus as docker image, getting it [here](https://hub.docker.com/r/directus/directus/tags). Any chances you will update it soon? 🙏

**Comment by hanneskuettner** [comment]
There will be, most likely today 🤞
