### ISSUE TITLE
Cache problems!

### ISSUE THREAD

**Issue by alvarocabanas** [directus/directus#2289]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus API version (Or commit hash): 7.0.6
  - PHP version: PHP 7.1
  - MySQL version: 
  - Web server: (Ex. Apache, nginx or IIS?)  Apache
  - OS name and version:

## Expected Behavior

When caching it should only cache when using the API from a user that is not the admin.

## Actual Behavior

If you activate the cache, you get everything cached, so when using the Vue cms the calls get cached and you don't see the newly created items. It actually expects tags to be set up to the cache and there is no point to set those tags, -In my case I removed that from the if condition in caceResponse-. 

## Steps to Reproduce
 1. Activate Cache (In my case Redis)
 2. Create for example a new collection
 3. Refresh the page

**Comment by benhaynes** [comment]
Thanks @honzabilek4!

@WellingGuzman — is this a `duplicate`?

**Comment by alvarocabanas** [comment]
Yes it is, thanks for the quick response!
