### ISSUE TITLE
Issue creating two image fields in one collection

### ISSUE THREAD

**Issue by lukesammy** [directus/directus#22905]
### Describe the Bug

Issue occurs when trying to create two or more image fields in one collection. First works fine, but after that any further image field creations results in an error response in the /relations call. The field is still created, but the relationship has not been set up correctly (see I1, vs I2)

I1 (working)
<img width="850" alt="Screenshot 2024-07-02 at 20 55 53" src="https://github.com/directus/directus/assets/30597521/91b80652-b5b1-4b81-a92f-d7fa1503a78f">

I2 (not working)
<img width="839" alt="Screenshot 2024-07-02 at 20 55 45" src="https://github.com/directus/directus/assets/30597521/bcfdabe5-2c26-4bc6-bcc2-38d53ec1c199">

### To Reproduce

To reproduce, simply create a new collection, and add more than one image field.

### Directus Version

v10.10.7

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Azure MS SQL

**Comment by rijkvanzanten** [comment]
@lukesammy Can you try setting the "On Delete of directus_files" option to "Do nothing"? I believe some versions of Azure SQL have an odd rule where you can't have more than one foreign key field with a constraint on it.

**Comment by lukesammy** [comment]
@rijkvanzanten thanks for the quick response - which of these options?

<img width="612" alt="Screenshot 2024-07-02 at 21 10 44" src="https://github.com/directus/directus/assets/30597521/1bf429b0-a159-489e-a0ed-98204edab808">

**Comment by lukesammy** [comment]
Prevent the deletion - seems to have done the trick
