### ISSUE TITLE
Loading errors of css files from /public/extensions/core/interfaces, multiple files (duplications?)

### ISSUE THREAD

**Issue by dev7ch** [directus/directus#2290]
# Bug Report

## Steps to Reproduce

1. Go to a created collection in the app admin overview page, which contains the default fields and some text fields.

2. Open the dev console and compare the console output with the screenshot below.

3. See error

## Expected Behavior

no console errors. 

## Actual Behavior

It seems it loads the wrong name css of the file and some changes haven't been completely adapted to the file system.

e.g.:

`/extensions/core/layouts/tabular/layout.css` may should be `/extensions/core/layouts/tabular/options.css`

or 

`/extensions/core/interfaces/<interface-name>/display.css` may should be `/extensions/core/interfaces/<interface-name>/input.css`

After further inspections of `/public/extensions/core/interfaces` i saw multiple js files with almost the same content (e.g. text-input, see screenshot below)

https://github.com/directus/directus/tree/master/public/extensions/core/interfaces/text-input

## Other Context & Screenshots

![image](https://user-images.githubusercontent.com/15183757/51938734-21fece80-240e-11e9-9e56-479b5ca08569.png)

![image](https://user-images.githubusercontent.com/15183757/51938967-b23d1380-240e-11e9-81d3-37f019ba482d.png)

![image](https://user-images.githubusercontent.com/15183757/51939593-275d1880-2410-11e9-86bf-ccf14e6b3457.png)

I am using the directus suite, totally locally.

Or is there a reason for the file duplications?

Thank you for your effort!

## Technical Details

- Device: [Desktop]
- OS: [MacOS Mojave]
- Web Server: [Apache 2.4.37 (locally) ]
- PHP Version: [eg: 7.2.0]
- Database: [eg: MySQL 8.0.12]
- Install Method: [directus suite, all stuff locally]

**Comment by benhaynes** [comment]
Thanks again @dev7ch! This is known issue (dup of https://github.com/directus/app/issues/1242) ... but we'd love your opinion on that ticket!
