### ISSUE TITLE
Enable SSO login with a valid JWT from IdP

### ISSUE THREAD

**Issue by greenGizmo** [directus/directus#22924]
### Describe the Improvement

It should be possible to login with a valid token from an IdP using the POST /auth/login/:provider endpoint. This would enable to use the Directus API by clients that are authorized by the IdP.

**Comment by rijkvanzanten** [comment]
Heya! There isn't enough information here for me to be able to execute this request. Mind opening [a new feature request](https://github.com/directus/directus/discussions/new?category=draft-feature-requests) instead? Thanks!
