### ISSUE TITLE
Adding custom access control to directus_fields or directus_collections tables gives access to all rows

### ISSUE THREAD

**Issue by danybol** [directus/directus#22927]
### Describe the Bug

Custom access filters on the directus_fields or directus_collections system collections are not respected, so if you grant custom access to a role then that role can see all rows in those collections (even ones which should be excluded by the filter)

### To Reproduce

1. Create two collections, e.g. "public_col" and "private_col"
2. Under access control, open the Public role and find the directus_collections row
3. Under the 'Read' column, select 'Use custom'
4. Under 'Item Permissions', add a filter which is "collection Equals public_col"
5. As a logged-out user, visit `https://your-directus-url/collections`

Expected to only see the 'public_col' collection listed, but instead I can see both 'public_col' and 'private_col'

### Directus Version

v10.12.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Postgresql 16

**Comment by danybol** [comment]
After some more experimenting it looks like the user can see all collections that their role has access to, even if those are excluded by the custom access rule - so perhaps this is by design?

**Comment by hanneskuettner** [comment]
> After some more experimenting it looks like the user can see all collections that their role has access to, even if those are excluded by the custom access rule - so perhaps this is by design?

That is indeed the case. I agree that this should be surfaced more clearly, but overall this seems to be working as expected?

**Comment by danybol** [comment]
Ok cool, just wanted to check. Yes might be good to have a warning on the Custom Access modal for those fields perhaps? Or something in the documentation (if it doesn't exist already). It doesn't seem too harmful since the user already has access to those collections anyway, but it was just a bit surprising as it worked differently to other collections.
