### ISSUE TITLE
Api bug

### ISSUE THREAD

**Issue by rayenbenhassen07** [directus/directus#22926]
### Describe the Bug

I have table that contains 128 items but the api data only contains 100 items

### To Reproduce

i opened api link and i found only 100 items that were availble instead of 128 items

### Directus Version

10.12.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

 PostgreSQL 16

**Comment by hanneskuettner** [comment]
That is because the API has a default limit of `100`, see https://docs.directus.io/reference/query.html#limit. You will have to either request more items by setting the limit to `-1` or deal with pagination.

**Comment by zguig52** [comment]
Hi, you are just stuck with default response lenght defined in directus.
Either you can:
- change this limit in your server: QUERY_LIMIT_DEFAULT https://docs.directus.io/self-hosted/config-options.html#general
- change this in your request: ?limit=200 https://docs.directus.io/reference/query.html#limit

**Comment by rayenbenhassen07** [comment]
thank you so much guys .... it worked =)
