### ISSUE TITLE
File upload regression - 204 return message

### ISSUE THREAD

**Issue by zguig52** [directus/directus#22925]
### Describe the Bug

After migration tests on latest version of Directus, with TOS file upload support, when files are uploaded, API response has changed.

Before, the response was 200 with details on the file uploaded:
![RequestStack_PreviousRelease](https://github.com/directus/directus/assets/12774668/c0f48720-8d64-4b0f-bd64-84c44b780ea1)
![RequestDetails_PreviousRelease](https://github.com/directus/directus/assets/12774668/613c02cf-6131-49c3-9cd3-0e6faa443b1a)

Now, the response is 204 with empty body:
![RequestDetails_NewRelease](https://github.com/directus/directus/assets/12774668/c131f786-b3e1-466c-9c9a-d3391b38f207)
![RequestStack_NewRelease](https://github.com/directus/directus/assets/12774668/58622444-e0fa-454b-b053-8148750aba03)

NB: it is the same code, same call, same file, same directus configuration, only the directus version is changed here (10.12.1 & 10.13.0)

Please note also that it doesn't seems to be related to this issue but the final response is:
https://github.com/directus/directus/issues/22649

I sadly cannot use the SDK yet for files uploads as discussed here (no upload status available yet with fetch):
https://github.com/directus/directus/discussions/13882

I would suspect the TOS implementation has provided some behaviour change here? Is there something to change in my code, thus I would have expected this evolution to pass in next major release or at least a big warning note on this change in the breaking changes, don't you think?

### To Reproduce

Try to upload a file without the SDK with progress callback as described here:
https://github.com/directus/directus/discussions/13882

```
        const xhr = new XMLHttpRequest();
//Here to be put Directus API root URL
        const url = useRuntimeConfig().public.apiURL as string;
//Here to be put Directus current token to be used if authentication required
        const authHeader = useAuth().token.value;
        response = await new Promise((resolve) => {
          xhr.upload.addEventListener("progress", (event) => onUploadProgress(event));
          xhr.addEventListener("progress", (event) => onUploadProgress(event));
          xhr.open("POST", url + "/files", true);
          xhr.onload = function(event) {
            resolve({data: JSON.parse(xhr.responseText)?.data, status: xhr.status});
          };
          if(authHeader){
            xhr.setRequestHeader("Authorization", authHeader);
          }
          xhr.send(formData);
        });
        if(response && response.status == 200){
          response = response.data;
        }else{
          if(response.status == 204){
            throw("Upload file success, but cannot read it (permissions issue)");
          }else{
            throw("Cannot upload file: " + response.status + " / " + response);
          }
        }
```

The response is 204 as you get when there are read permissions associated (but that I totally understand that you could send but not read if you don't have permissions).

### Directus Version

v10.13.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
Heya!

I'm wondering if this might be related to this PR I created to address a problem that was raised internally: https://github.com/directus/directus/issues/22925

Could you verify the access rights of the user trying to create the file for the `tus_id` field on the `directus_files` collection?

**Comment by zguig52** [comment]
Hi @hanneskuettner,

You are totaly right!! 

Files read access restrictions were enabled and new fields introduced by the TUS protocol were not readeable (tus_id and tus_data).

Once I allow read on tus_id only, everything is fine, behaviour comes back to previous.

So:
- workaround with V10.13 => add read permissions on tus_id field is good
- your commit will certainly fix the regression

Thanks a lot!

**Comment by hanneskuettner** [comment]
Perfect! Thank you for confirming my hunch!
