### ISSUE TITLE
Create multiple items and Update multiple items inconsistent behaviour.

### ISSUE THREAD

**Issue by loongmxbt** [directus/directus#22923]
### Describe the Improvement

In https://docs.directus.io/reference/items.html#create-multiple-items, the body is an array of objects and looks like this:
```json
[
	{
		"title": "Hello world!",
		"body": "This is our first article"
	},
	{
		"title": "Hello again, world!",
		"body": "This is our second article"
	}
]
```
In https://docs.directus.io/reference/items.html#update-multiple-items, the body can only be an object. Which means I should update all items to the same object values.
```json
{
	"keys": [1, 2],
	"data": {
		"status": "published"
	}
}
```
I think it would be nice to update different items different objects, the body looks like:
```
{
	"keys": [1, 2],
	"data": [{
           "title": "title1",
	  "desc": "111"
	},{
           "title": "title2",
	  "desc": "222"
	}]
}
```
Meaning that data support both object and array of objects. Now the response message is:
```json
{
  "errors": [
    {
      "message": "Invalid payload. \"data\" must be of type object.",
      "extensions": {
        "code": "INVALID_PAYLOAD",
        "reason": "\"data\" must be of type object"
      }
    }
  ]
}
```

**Comment by hanneskuettner** [comment]
What you are looking for is called a batch update and can be achieved by sending a JSON array as the body of your `PATCH` request, where each object in that array is one update you want to perform, like so

```json
[
	{
           "id": 1,
           "title": "title1",
	   "desc": "111"
	},
        {
           "id": 2,
           "title": "title2",
           "desc": "222"
	}
]
```

**Comment by loongmxbt** [comment]
Thanks a lot!
