### ISSUE TITLE
oracle 11g support

### ISSUE THREAD

**Issue by sacesare** [directus/directus#22930]
### Describe the Bug

It seems directus cant's support database without support of json type (and check IS for type constraint  a'la  "check column is json"), is that true?

### To Reproduce

Sample initialization script:
```
create table "directus_collections" (
  "collection" varchar2(64) not null, 
  "icon" varchar2(30), 
  "note" clob, 
  "display_template" varchar2(255), 
  "hidden" number(1, 0) default '0' not null check (
    "hidden" in ('0', '1')
  ), 
  "singleton" number(1, 0) default '0' not null check (
    "singleton" in ('0', '1')
  ), 
  "translations" varchar2(4000) check ("translations" is json),  --- that not work because, there's no json type and no support for check types "IS"
  "archive_field" varchar2(64), 
  "archive_app_filter" number(1, 0) default '1' not null check (
    "archive_app_filter" in ('0', '1')
  ), 
  "archive_value" varchar2(255), 
  "unarchive_value" varchar2(255), 
  "sort_field" varchar2(64)
)
```

### Directus Version

v11.0.0-rc.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

oracle 11g, 11.2 release

**Comment by hanneskuettner** [comment]
Directus only supports the LTS versions of the databases, see https://docs.directus.io/self-hosted/docker-guide.html#supported-databases

Oracle 11g has been out of extended support for 3+ years now.
<img width="836" alt="Screenshot 2024-07-04 at 20 43 09" src="https://github.com/directus/directus/assets/4376726/0078e9af-da59-498c-a79a-87e3078a007d">

Closing this, as we encourage you to use the most recent LTS versions of the databases available.
