### ISSUE TITLE
Reloading extensions in workspaces

### ISSUE THREAD

**Issue by bernatvadell** [directus/directus#22948]
### Describe the Bug

I found a similar issue and discussion:
#14922
#14939

In my case, I am working in a workspace with pnpm.
Until now, what I did was install my extensions as dependencies, e.g.:
```json
"dependencies": {
  "directus": "^10.11.2",
  "@enovam/ge-extensions": "workspace:"
 }
```

The load extensions works correctly, but the changes are not updated.

Pulling the thread, then I saw that only the local extensions are added to the watch:

```ts
if (this.options.watch && !wasWatcherInitialized) {
  this.updateWatchedExtensions(Array.from(this.localExtensions.values()));
}
```

Once this was confirmed, what I did was remove the extension as a dependency and "installed" it with a symbolic link within the directus extensions folder.

In this way I was already detecting the changes.

My question is: Should the installed extensions method also work within the workspace?

### Directus Version

v10.11.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by bernatvadell** [comment]
Hi! 

@rijkvanzanten If you give me a few instructions on how you want to do it, I can make a PR.

The easiest thing would be to change:
```ts
if (this.options.watch && !wasWatcherInitialized) {
  this.updateWatchedExtensions(Array.from(this.localExtensions.values()));
}
```

by:
```ts
if (this.options.watch && !wasWatcherInitialized) {
  this.updateWatchedExtensions(this.extensions);
}
```

or

```ts
if (this.options.watch && !wasWatcherInitialized) {
  this.updateWatchedExtensions([...this.extensions]);
}
```

Although, I do not know the implications it may have, or the reason why it was not done this way from the beginning.

**Comment by rijkvanzanten** [comment]
Hi @bernatvadell! I vaguely remember discussing watching npm packages as well way back when this was first designed, but I can't quite remember what the reasoning was behind it. I think it was to reduce the overall number of watched file handles (as `node_modules` can have thousands of files) and because the (wrong) assumption was made that npm based extensions don't change that often (the thinking was that you'd `npm install` them once; but in a pnpm workspace you'd be updating them in real time.

@nickrum Do you remember any other reasoning on this?

I'd say lets go ahead with a PR with the suggested tweak so we can kick the tires on a dev copy 🙂

**Comment by bernatvadell** [comment]
Perfect! I've been checking, and the extensions property already returns a filtered list of directus extensions. I don't know to what extent a Directus instance can have thousands of extensions installed.

In any case, it would only penalize development environments since it is correctly conditioned.

If that's okay with you, I'll start the PR (which isn't much of a mystery) and we'll work on it from there.

Many thanks for your work!

**Comment by rijkvanzanten** [comment]
Lets do it! 🙌🏻 Thank you too 😄

**Comment by nickrum** [comment]
@rijkvanzanten When extension reloading was introduced, it watched both local as well as non extensions (by watching the root `package.json`, the `package.json`s of extensions and the resolved extension entry points to reduce the number of watched files to a minimum) for changes. This must have been remove/broken with some of the more recent changes.
