### ISSUE TITLE
Adding profile Images to Tutors - Error [UNKNOWN] Request failed with status code 413

### ISSUE THREAD

**Issue by WesleyEkman** [directus/directus#22946]
### Describe the Bug

When trying to add a profile image to Tutors the error [UNKNOWN] Request failed with status code 413 keeps popping up

### To Reproduce

Log into Admin in Directus 
Click user directory in the left list
Select user i.e Alicia Knowles
Navigate down to the Avatar section
Click to add an avatar 
Select file 
![Alicia Knowles](https://github.com/directus/directus/assets/167199476/8b10a7e4-f93f-48cf-9b79-bc4122907db9)

### Directus Version

10.12.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Directus 10.12.1

**Comment by rijkvanzanten** [comment]
Are you using an admin user? If not, does the user you're using have permissions to upload new files?

**Comment by WesleyEkman** [comment]
@rijkvanzanten - spot on - image size. Thanks for the help.
