### ISSUE TITLE
Multiple Redis connections on startup

### ISSUE THREAD

**Issue by clayboc** [directus/directus#22958]
### Describe the Improvement

I notice when Redis Cache is enabled in .env config, there are suddenly many redis connections established when directus starts up.  I'm wondering if this is on purpose, or perhaps multiple connections are being created instead of one getting created and reused. As always, thanks for your work and a great project.

**Comment by rijkvanzanten** [comment]
This is on purpose. We balance commands across multiple connections, and have to rely on separate connections for certain things like namespacing or pub/sub connections 🙂
