### ISSUE TITLE
Typescript errors with @vercel/node on @directus/sdk

### ISSUE THREAD

**Issue by 50l3r** [directus/directus#22971]
### Describe the Bug

When i try to execute a Vercel serverless function in local with `vercel dev` i recieve multiple TS errors in runtime;

![image](https://github.com/directus/directus/assets/5095592/cc0fa93b-c84d-4ff9-a77d-1f023ada332b)

```
node_modules/@directus/sdk/dist/index.d.ts:3039:140 - error TS1005: ';' expected.
3039 declare const updateWebhook: <Schema, const TQuery extends Query<Schema, DirectusWebhook<Schema>>>(key: DirectusWebhook<Schema>['id'], item: Partial<DirectusWebhook<Schema>>, query?: TQuery) => RestCommand<UpdateWebhookOutput<Schema, TQuery>, Schema>;
```

```
node_modules/@directus/sdk/dist/index.d.ts:3039:192 - error TS1128: Declaration or statement expected.
3039 declare const updateWebhook: <Schema, const TQuery extends Query<Schema, DirectusWebhook<Schema>>>(key: DirectusWebhook<Schema>['id'], item: Partial<DirectusWebhook<Schema>>, query?: TQuery) => RestCommand<UpdateWebhookOutput<Schema, TQuery>, Schema>;
```

### I use...
- @directus/sdk: 16.1.1
- typescript: 5.5.3
- @vercel/node: 3.2.2

### To Reproduce

1. Execute `vercel dev`
2. Call endpoint `GET /api/test`
3. Recieve 1191 errors in `node_modules/@directus/sdk/dist/index.d.ts` in runtime

### Directus Version

10.10.7

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
What version of TypeScript does vercel's dev rely on?

**Comment by 50l3r** [comment]
If I'm not wrong it use version `4.9.5` 

https://github.com/vercel/vercel/blob/main/package.json

**Comment by rijkvanzanten** [comment]
Hm OK! We're using the current release 5.4 so I'm assuming their usage of the outdated TS 4 is causing these issues. I'm afraid there's nothing we can do about that. From a quick search, it seems to be a known issue that has a workaround: https://github.com/vercel/vercel/issues/8680

**Comment by 50l3r** [comment]
> Hm OK! We're using the current release 5.4 so I'm assuming their usage of the outdated TS 4 is causing these issues. I'm afraid there's nothing we can do about that. From a quick search, it seems to be a known issue that has a workaround: [vercel/vercel#8680](https://github.com/vercel/vercel/issues/8680)

I try to override modules witouth success.

This is my package.json

```
{
    "dependencies": {
        "@fortawesome/fontawesome-svg-core": "^6.5.1",
        "@fortawesome/free-solid-svg-icons": "^6.5.1",
        "@fortawesome/vue-fontawesome": "^3.0.6",
        "axios": "^1.6.7",
        "cors": "^2.8.5",
        "dayjs": "^1.11.10",
        "dotenv": "^16.3.1",
        "jsonwebtoken": "^9.0.2",
        "mitt": "^3.0.1",
        "pinia": "^2.0.33",
        "pinia-plugin-persistedstate": "^2.4.0",
        "strong-soap": "^4.0.1",
        "sweetalert2": "^11.10.6",
        "vue": "^3.3.8",
        "vue-router": "^4.2.5",
        "vue-toastification": "^2.0.0-rc.5"
    },
    "devDependencies": {
        "@directus/sdk": "^16.1.1",
        "@types/jsonwebtoken": "^9.0.5",
        "@types/morgan": "^1.9.9",
        "@typescript-eslint/eslint-plugin": "^6.11.0",
        "@typescript-eslint/parser": "^6.11.0",
        "@vercel/node": "^3.2.2",
        "@vitejs/plugin-vue": "^4.5.0",
        "@vue/eslint-config-typescript": "^12.0.0",
        "autoprefixer": "^10.4.16",
        "eslint": "^8.54.0",
        "eslint-config-prettier": "^9.0.0",
        "eslint-plugin-vue": "^9.18.1",
        "postcss": "^8.4.31",
        "postcss-nesting": "^12.1.2",
        "prettier": "^3.2.5",
        "prettier-plugin-classnames": "^0.6.1",
        "prettier-plugin-merge": "^0.6.0",
        "prettier-plugin-tailwindcss": "^0.5.11",
        "sass": "^1.70.0",
        "tailwindcss": "^3.3.5",
        "typescript": "^5.5.3",
        "vercel": "^34.3.1",
        "vite": "^4.4.10",
        "vite-plugin-pwa": "^0.16.5",
        "vue-tsc": "^1.8.22"
    },
    "overrides": {
        "@vercel/node": {
            "ts-node": "10.9.2",
            "typescript": "5.5.3"
        },
        "vercel": {
            "ts-node": "10.9.2",
            "typescript": "5.5.3"
        }
    }
}
```

Any ideas to avoid the errors? Try with `exclude` in tsconfig.json without success

**Comment by 50l3r** [comment]
Much thanks for your time @rijkvanzanten. I'l continue my issue in vercel :)
