### ISSUE TITLE
Metadata of the Marketplace extension page is not well aligned with the content column

### ISSUE THREAD

**Issue by formfcw** [directus/directus#22979]
### Describe the Improvement

![issue](https://github.com/directus/directus/assets/78852214/8af8cbef-fda6-49f7-989b-065e17a724eb)

I will fix it!

**Comment by rijkvanzanten** [comment]
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExOXc4eW9jMGlnYnA3bGI4NGZrY3ZtdGt2ZDk3anN0MmNlam1mem9iZCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/lqVVqkqMolh9S/giphy.gif)
