### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by RNGR** [directus/directus#23]
Page listing messages: 

- Inbox
- Sent
- Archived

Unread items: Bold text and green side indicator

Messages with media have paperclip icon

**Item** messages have a arrow icon

**Comment by WellingGuzman** [comment]
@benhaynes can you give more details into this one?

**Comment by benhaynes** [comment]
Sure! It's on the wishlist milestone, so not a priority, but here's the details:

* The ability to archive messages
* Tab navigation for viewing:
    * Inbox messages
    * Messages you've sent
    * Messages you've archived
* Messages that are unread are shown as Bold/Green on the listing page
* Comments (messages attached to Items) are shown here with an icon (arrow) that links to the item detail

**Comment by benhaynes** [comment]
**[Migrated to FeatHub](http://feathub.com/directus/directus/+1)**

Please use the [Directus FeatHub](http://feathub.com/directus/directus) to vote for features or make new request. Accepted feature requests will be added to GitHub Issues.
