### ISSUE TITLE
No changes made after building the source code.

### ISSUE THREAD

**Issue by markos2000** [directus/directus#23004]
### Describe the Bug

I made some modifications to the translation files and after running `pnpm build` command and start the server I don't see any of the changes that I did apply to the admin app.

### To Reproduce

- Modify code or translation file
- run `pnpm build`
- run `npx directus start`
- no changes were made to the app

### Directus Version

v10.13.0

### Hosting Strategy

Self-Hosted (Custom)

### Database

PostgreSQL 16

**Comment by hanneskuettner** [comment]
Where are you running `pnpm run build`? In the `app` package directly or in the top level directory?

**Comment by rijkvanzanten** [comment]
Pretty sure `npx directus start` will use whatever the most recent deployment on `npm` is, instead of your local copy. See https://docs.directus.io/contributing/running-locally.html#running-dev-environment for more information on how to run a development copy locally.

**Comment by markos2000** [comment]
> Where are you running `pnpm run build`? In the `app` package directly or in the top level directory?

Running the command in the top level directory

**Comment by markos2000** [comment]
> Pretty sure `npx directus start` will use whatever the most recent deployment on `npm` is, instead of your local copy. See https://docs.directus.io/contributing/running-locally.html#running-dev-environment for more information on how to run a development copy locally.

how do I run my local copy of directus instead of the npm package?

**Comment by rijkvanzanten** [comment]
See https://docs.directus.io/contributing/running-locally.html#running-dev-environment for more information on how to run a development copy locally.
