### ISSUE TITLE
[Bug] registration successful despite the email already used

### ISSUE THREAD

**Issue by yipivan** [directus/directus#23000]
### Describe the Bug

Just try to sign up using an email already exists, it shows register successful. We expect an error is thrown so the users know they need to try a different email.

### To Reproduce

Just try to sign up using an email already exists, it shows register successful. 

### Directus Version

v10.11.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

mysql

**Comment by hanneskuettner** [comment]
This is intended behavior in order to avoid leaking information on which emails are registered, see 

https://github.com/directus/directus/blob/596fb8b10908d720fe65709e28883db1af68070d/api/src/services/users.ts#L551-L555
