### ISSUE TITLE
`down` migration for V11 policies does not work

### ISSUE THREAD

**Issue by hanneskuettner** [directus/directus#23018]
### Describe the Bug

Currently the down migration for the V11 policies upgrade is broken if the user add's a new permission to their system as a foreign key constraint fails.

### To Reproduce

* Migrate up
* Add permission + policy
* Try migrate down

### Directus Version

v11.0.0-rc.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
Closed in #23097
