### ISSUE TITLE
Repo seems to be out of sync with API repo?

### ISSUE THREAD

**Issue by SharkWipf** [directus/directus#2301]
# Bug Report
I'm going through the docs for creating my own page extensions, but, while [the documentation](https://github.com/directus/docs/blob/master/extensions/pages.md) and [the api repo](https://github.com/directus/api/tree/master/extensions/core/pages/_demo) seem to be in sync, this directus/directus repo seems to have a [different, non-compatible and seemingly not documented system in place](https://github.com/directus/directus/tree/master/public/extensions/core/pages/_demo).

As far as I understand from #2229, the last link is supposed to be in sync with the API repo.

Following the API docs and attempting to create a page as per the instructions results in a blank page and 404 errors in the console for page.js and page.css.

## Steps to Reproduce

1. Install Directus Suite
2. Follow the Extension docs to create a custom page

## Expected Behavior
A functional plugin

## Actual Behavior
A different, non-compatible API is in place.

## Other Context & Screenshots
I understand this is a free/FOSS project, but my time with Directus has been far more complicated than necessary so far.
Having just fully set up and integrated a Directus 6 environment weeks before Directus 7 came out and Directus 6 support got dropped entirely, both maintaining Directus 6 and migrating to Directus 7 has been a confusing mess as half of the documentation either ended in dead links, outdated docs, things being entirely undocument, or outright conflicting documentation, spread out over multiple places (Github, the website, Medium, Github issues and more).
The application seems to be in decent shape now, I would suggest whipping the documentation into shape soon.

## Technical Details
N/A

**Comment by shealavington** [comment]
IMO: It seems rather quick to blame the software for being out of sync and not up to date, as far as I'm aware, the Directus/Directus repo is up to date — remember to look at versions and not the master.

I'm also not quite sure what your issue here? The title of this issue seems subjective — is your issue just that you're getting some resource 404s in the browser console, or is it that you just don't understand how Directus/Directus is insync with the other repos?

If your issue is difficulty creating an extension, then the best thing for you to do here, is to explain exactly what you did so someone can see, rather than saying "I followed the docs", as commonly, it ends up as one small missed instruction that ends up as an "oh my bad".

**Comment by SharkWipf** [comment]
@shealavington As per the linked docs: 

A Page is made up of at least two core files. You can create a page from scratch or use the [included page extension demo](https://github.com/directus/api/tree/master/extensions/core/pages/_demo). Simply remove the prepended underscore (`_`) to enable the demo.

The format of the linked `_demo` folder is different than the `_demo` folder in directus/directus, and copying the demo folder from the documentation/API repo over to the directus/directus instance behaves as I've explained above, it doesn't display anything and the console throws 2 404s, for the seemingly undocumented and unformatted page.js and page.css files the directus/directus application looks for.

**Comment by SharkWipf** [comment]
On closer inspection, it does seem that, when checking out by tag, all tags of version 2.0.0 and above seem to have [the same structure as the directus/directus repo](https://github.com/directus/api/tree/v2.0.17/public/extensions/core/pages/_demo).
So then this becomes an outdated documentation issue and should probably be moved to the documentation repo.
@shealavington thanks for pointing out the tag issue, I assumed that since directus/directus and directus/documentation were using the master repo, so would the directus/api repo.  
I'll close this issue here now and open a new issue in the documentation repo.
