### ISSUE TITLE
`aggregate[count]='*'` not working

### ISSUE THREAD

**Issue by hanneskuettner** [directus/directus#23021]
### Describe the Bug

`aggregate[count]=*` does not work after the policies update. Instead of the correct count I am seeing 

```
You don't have permission to access field \"*\" in collection \"articles\" or it does not exist. Queried in root.
```

Request with a explicit field work as expected.

### To Reproduce

- Create a collection
- Request the count with field wildcard

### Directus Version

v11.0.0-rc.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Fixed in #23022
