### ISSUE TITLE
When uploading a replacement file with a different extension, filename_disk extension is not updated.

### ISSUE THREAD

**Issue by that1matt** [directus/directus#23045]
### Describe the Bug

When using the replace file option for image, replacing the file with a different extension type, `filename_disk` extension is not updated.

Note: The `type` and `filename_download` are updated properly.

Initial Upload
<img width="892" alt="initial" src="https://github.com/user-attachments/assets/49691b06-e7db-408b-99bd-ddd6296ae55b">
Replaced Upload
<img width="889" alt="replaced" src="https://github.com/user-attachments/assets/88039365-40a8-414d-909a-262f944e59f3">

### To Reproduce

1. Upload a file with any extension (i.e .png)
2. Replace file with a new file and extension type (i.e .jpg)
3. `filename_disk` is not updated to reflect the new file extension type.

### Directus Version

v10.13.1

### Hosting Strategy

Directus Cloud

**Comment by that1matt** [comment]
I am happy to push up a fix for this.

**Comment by rijkvanzanten** [comment]
That'd be great @that1matt! ❤️
