### ISSUE TITLE
Session Token usability issue in SDK

### ISSUE THREAD

**Issue by arladmin** [directus/directus#23049]
How exactly is the 'session mode for authentication' expected to be used, and where is that specified?

---

> > It is also necessary to pass the tokens in headers for getting images, as we cannot rely on cookies always.
>
> Cookies are passed as a header too! But there is a bunch of extra logic surrounding it in browsers dealing with domain security / js access / formatting the header / parsing response cookies and such.

I'm facing this issue as well. In the current use-case, i need to create URLs (that include the `access_token` parameter) to access the file assets. But, without the token, it's now not possible!

And no, browsers don't allow access to the stored cookies using JS.

---

Additionally, 'not returning the token in a retrievable format' seems more to be a 'breaking change/bug' rather than a 'DX' issue

_Originally posted by @arladmin in https://github.com/directus/directus/issues/22435#issuecomment-2233879949_

**Comment by rijkvanzanten** [comment]
@arladmin how does this issue differ from the linked #22435?

**Comment by arladmin** [comment]
> @arladmin how does this issue differ from the linked #22435? 

@rijkvanzanten 
The linked issue seems to focus more on this being a docs issue (the title says so as well as the labels).

What I'm highlighting here is that it's more than that: it's a serious usability issue, almost a design flaw.

**Comment by rijkvanzanten** [comment]
OK lets keep the discussion in the same issue then rather than diverging the conversation about the same topic in two places 👍🏻
