### ISSUE TITLE
SDK Typing Comparison Filters not Allowed on Date Fields

### ISSUE THREAD

**Issue by jofmi** [directus/directus#23040]
### Describe the Bug

Using the SDK, filters such as "_gte" are not allowed by typescript - even though they work in practice.

Maybe it is because the type is set to "never"? 

![grafik](https://github.com/user-attachments/assets/5d0f9743-e19f-4a0e-8655-db76e727f456)

### To Reproduce

```ts
await directus.request(
  readItems("my_collection", {
    filter: {
      my_date_field: { _gte: my_value },
    },
  }),
)
```

### Directus Version

v10.12.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Is the "datetime" field correctly typed in the schema?
https://docs.directus.io/guides/sdk/types.html#setting-up-a-schema

[Typescript Playground Reproduction Demo](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbwFB1XAxlApgQxlgEWG3RgFcBnAGjmwphuxwBMBJfECpAXzgDMoEEHABEAAWbEspSgHoKzANYikSGAE8wWOAFl1AYQgAbI9JjAIAOzgBeRCjQh1AfWZ4szvsCxHmALjgAcjd8cxAsQIBuHlUNLTgAZXQACywQHFt7NDgnZ3RjU1ILSwC9QxMzYoBtAF1o7lV8y3o4SRJyCkzMXHwidsoAHiTU9IA+AApAsigjQIBKADoAd2AYZPG6GHG5udUcJZxV1qkZCgXsAEcyLHpxhyY2DgpxkVz8iqKrERpkbK8jfBQAK-bI5FwhDxeHz+RBwZwAc3wAUCuQAbjgjNdAnBuFQHKhcQ5uHM8XMgA)

Closing this issue for now until more information becomes available

**Comment by jofmi** [comment]
You are correct, I had not used the correct type in the schema. Very sorry for reporting a false bug!

Upon fixing the schema, I encountered another problem. How do I correctly assign a value to a datetime field? Neither string nor date seems to work. See [Typescript Playground Reproduction Demo](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbwFB1XAxlApgQxlgEWG3RgFcBnAGjmwphuxwBMBJfEajJ-drEJAF84AMygQQcAEQABZsSylKAegrMA1lKRIYATzBY4AWV0BhCABsLimMAgA7OAF5EKNCF0B9ZniyeRwFgWzABccADkPvi2IFjhANyoyspw9FDA9gDmQtp6BnAAyugAFvw4zq5ocB6e6JbWpHb2YSbmVjZNANoAuvE5SHX29HDyJOQUFZi4+ERjlAA8RaUgOAB8ABThZFAW4QCUAHQA7sAwxet0MOt7e9o4RzinIwpKFAfYAI5kWPTrbkxsDgUdZSGp1dqNBxSGjIKoBCz4KBhWFVapeKJ+AJBUKIOCeTL4MLhGoANxwFm+4TggioblQNLcgj2tNuSHuj3goxslHeWC+Pyubimvj4IBBYPqHShMLpaO8vn8gWCYSkACYAAyqgAsAFp1QB2HWq1UAFQNIS1+pCAFYABwHACM+tVAC0tPTmUhWeynlzXrz+b8hTwsKLxV5wQ1bNLKu50Qqscq4PYsEc4ARfNdGZ7vQ9fS9xgHvkHUMLeBxw7VJZD7NDY6gahjFdiVRiYlh3dSc0ggA)

**Comment by br41nslug** [comment]
That other error is unfortunately a known issue yet to be resolved https://github.com/directus/directus/issues/21599
