### ISSUE TITLE
Upload Image via API?

### ISSUE THREAD

**Issue by jesstucker** [directus/directus#2306]
# Feature Request
Hi there,
Not sure whether this is already implemented.  We have directus configured to upload images to s3, which works fine from the web browser admin interface.  Is this same functionality implemented in the API?  It seems that the image field currently only accepts a primary key integer.  Leads me to believe if I want to associate a record item with an image, I've got to manually write to the files endpoint, and manually upload to the s3 bucket.  Am I way off base?

## What problem does this feature solve?
make api as useful as web browser admin interface
## How do you think this should be implemented?
as automagically as the web browser admin interface
## Would you be willing to work on this?
maybe, especially if I have to implement it myself in our project

**Comment by rijkvanzanten** [comment]
Hey @jesstucker! The application uses the API for everything under the hood: if something is possible in the app, it's possible in the API.

The way the application does it is by uploading the file to the `/files` endpoint using enctype `multipart/form-data`. If you've configured to use S3 in the config file, it will save the file to S3.

See https://docs.directus.io/extensions/storage-adapters.html#using-aws-s3 for more info on how to set that up.

**Comment by rijkvanzanten** [comment]
> It seems that the image field currently only accepts a primary key integer

The field interface right now is a relational field to the directus_fields component. You would first save the file to `/files` and save the ID that is returned nested in the item in which you want to add the file.

* It's theoretically possible to inline the file right there in the item itself, but that only works using a base64 data string of the file which is not very performant. I would highly recommend uploading the file separately using the `/files` endpoint first.

**Comment by jesstucker** [comment]
Great, prompt feedback.  Thanks so much!  I'll fiddle with this.  Just out of curiosity, is this kind of thing in your docs?  I couldn't seem to find much on POSTing via the api.  Only a single paragraph here: https://docs.directus.io/api/reference.html#create-items

**Comment by jesstucker** [comment]
Oh I see this bit here now: https://docs.directus.io/api/reference.html#files
I apologize as I am occasionally hasty

**Comment by rijkvanzanten** [comment]
No worries 🙂

**Comment by ashx404** [comment]
> > It seems that the image field currently only accepts a primary key integer
> 
> The field interface right now is a relational field to the directus_fields component. You would first save the file to `/files` and save the ID that is returned nested in the item in which you want to add the file.
> 
> * It's theoretically possible to inline the file right there in the item itself, but that only works using a base64 data string of the file which is not very performant. I would highly recommend uploading the file separately using the `/files` endpoint first.

Can you explain the latter approach, I am using v8.6.2. Trying to upload an image directly to the field.

**Comment by donavan-tangible** [comment]
> Oh I see this bit here now: https://docs.directus.io/api/reference.html#files
> I apologize as I am occasionally hasty

404

**Comment by AntvissMedia** [comment]
> > Oh I see this bit here now: https://docs.directus.io/api/reference.html#files
> > I apologize as I am occasionally hasty
> 
> 404

https://docs.directus.io/reference/files.html
