### ISSUE TITLE
Internal Rate Limiter not working

### ISSUE THREAD

**Issue by Xyz3R** [directus/directus#23067]
### Describe the Bug

I set up the internal rate limiting according to the docs with the following configuration options (+plus the required options):

```
NODE_ENV=production
RATE_LIMITER_ENABLED=true
RATE_LIMITER_POINTS="3"
RATE_LIMITER_DURATION="10"
RATE_LIMITER_GLOBAL_POINTS="3"
RATE_LIMITER_GLOBAL_DURATION="10"
RATE_LIMITER_REGISTRATION_ENABLED=true
RATE_LIMITER_REGISTRATION_POINTS=3
RATE_LIMITER_REGISTRATION_DURATION=120
```

These are set very strict for testing purposes.

Now I would expect to be able to trigger the rate limiter in my local testing environment by calling any endpoint more than 3 times in 10 seconds. However, I can call any endpoint any number of times.

I even tried setting points to 1 or 0 and the duration to over 100s. This did not change anything whatsoever. I also tried both doing public requests without authentication and using authentication. 

### To Reproduce

Spin up a local directus instance and enable the rate limiter with the options provided in the issue description. Then execute several get requests quickly on the same endpoint from the same ip

### Directus Version

v10.13.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 16

**Comment by paescuj** [comment]
Cannot reproduce:

https://github.com/user-attachments/assets/1c8341ba-aa67-496c-a019-f25a05540ed0

Please ensure the config is correctly applied.
Also note that in your config above, the `RATE_LIMITER_GLOBAL_ENABLED` setting is missing, and you would need to set higher values for the global rate limiter than the IP-based one.
