### ISSUE TITLE
autoRefresh timer stop on page reload or new route 

### ISSUE THREAD

**Issue by safwat-fathi** [directus/directus#23072]
### Describe the Bug

I am creating directus client with the following authentication config:

```typescript
directusClient = createDirectus<DirectusSchema>(process.env.NEXT_PUBLIC_BASE_API_URL)
  .with(
    authentication("json", {
      storage: {
        get: async () => {
          const authData = await getAuthDataAction();

          return authData;
        },
        set: async (value) => await setAuthDataAction(value),
      },
      autoRefresh: true,
      msRefreshBeforeExpires: 10000,
    })
  )
  .with(rest());
```

On Nextjs v14, after login using client the autoRefresh seems to work fine as it sends the refresh request as intended, But when redirecting or reloading the page the timer does not work as expected.

**Side not: any readItem / readSingleton return "Token expired" error knowing that the item has public access.**

## Using Nextjs v14 (app router): 
- Login using SDK
- stay on the same page
- redirect to other page the auto refresh stops

**I am storing auth data in cookies using server actions**

## my Directus env file related fields:

ACCESS_TOKEN_TTL="30s"
REFRESH_TOKEN_TTL="7d"
REFRESH_TOKEN_COOKIE_SECURE=false
REFRESH_TOKEN_COOKIE_SAME_SITE="lax"
REFRESH_TOKEN_COOKIE_NAME="refresh_token"

### Directus Version

v10.13.0

### Hosting Strategy

Self-Hosted (Custom)

### Database

PostgreSQL 14.12

**Comment by paescuj** [comment]
You need to ensure you're re-using the same instance of the SDK across Next.js pages, otherwise the current state of the auto refresh timer will be lost.

You can find an example of such a setup here: https://docs.directus.io/guides/headless-cms/build-static-website/next.html#create-a-helper-for-the-sdk

**Comment by safwat-fathi** [comment]
That is exactly what i am doing:

```javascript
import { authentication, createDirectus, rest } from "@directus/sdk";

import { getAuthDataAction, setAuthDataAction } from "@/app/[locale]/actions";
import { DirectusSchema } from "@/types/models/schema.model";

export const directusClient = createDirectus<DirectusSchema>(process.env.NEXT_PUBLIC_BASE_API_URL)
  .with(
    authentication("json", {
      storage: {
        get: async () => {
          const authData = await getAuthDataAction();

          return authData;
        },
        set: async (value) => await setAuthDataAction(value),
      },
      autoRefresh: true,
      msRefreshBeforeExpires: 10000,
    })
  )
  .with(rest());
```

**Home page**

```javascript
type Props = {
  params: {
    locale: AppLocale;
  };
};

const Home = async ({ params }: Props) => {
  const query = {
    fields: ["*", { translations: ["*"] }],
    deep: { translations: { _filter: { languages_code: { _eq: LocaleMapper[params.locale] } } } },
  } satisfies Query<DirectusSchema, HomePage>;

  const home = await directusClient.request(readSingleton("home", query));

  if (!home || !home.translations) {
    return notFound();
  }

  const { title } = home.translations[0];

  return (
    <main>
      <Hero />
      <LatestLibraries />
      <RecentRecords />
      <Statistics />
      <RecentAuthors />
    </main>
  );
};

export default Home;
```

**Comment by paescuj** [comment]
The autoRefresh timer needs to be initialized, either by performing a `login` or `refresh` call. So if you don't login after a page reload (e.g. because the user is already authenticated), you need to call `refresh` in order to initialize the timer (and also to verify the current auth data).

See also https://docs.directus.io/guides/sdk/authentication.html#using-the-authentication-composable.

**Comment by safwat-fathi** [comment]
I think calling refresh() on every page request is really cumbersome behavior and bad performance wise

**Comment by paescuj** [comment]
> I think calling refresh() on every page request is really cumbersome behavior and bad performance wise

It's only required on full page load & refreshes, where the current SDK state is not available yet resp. lost. So as long as you do client-side page navigation [^1], the state should be retained and the timer will keep running.

[^1]: https://nextjs.org/docs/pages/api-reference/components/link
