### ISSUE TITLE
Turning off Nullable drops Default Value in schema settings

### ISSUE THREAD

**Issue by mikolajkazmierczak** [directus/directus#23081]
### Describe the Bug

When I turn off the _Nullable_ setting in the schema settings for a field, the previously set value in the _Default Value_ setting is dropped after saving the changes. Vice versa, setting a _Default Value_ turns on the _Nullable_ setting.

This only happens when you take certain steps, and you can go around it:
- when you change _Default Value_ **when _Nullable_ is off**, it sets _Nullable_ on after saving
- when you change _Nullable_ (on to off or off to on) **when _Default Value_ is set**, it clears _Default Value_ after saving
- when you edit both settings, both changes are applied normally after saving

### To Reproduce

Here is one way to reproduce this (though I provided more information in the description):

1. Create a new field:
    - set _Key_ to "test"
    - set _Default Value_ to "test"
    - save
2. Edit the field:
    - turn off _Nullable_
    - save
3. Check the field again and _Default Value_ is cleared

### Directus Version

works on v10.13.0 and v11.0.0-rc.3 but I imagine there are more

### Hosting Strategy

Self-Hosted (Custom)

### Database

sqlite3@5.1.7

**Comment by echocrow** [comment]
+1, was about to report the same issue.

Adding to the above, there seems to be a two-way issue, where setting a Default Value _enables_ Nullable, and unchecking Nullable clears the Default Value. (This is only observed after submit, not while editing the form.)

## Setup

- Directus: 10.13.0 & 10.13.1 (haven't tested other versions)
- Database: PostgreSQL 13

## Repro

- Create or find an existing field that has no default value and is not nullable
- Edit that field: Set a Default Value and save
  - Expected: default value set, still not nullable
  - Actual: default value set, now nullable(!)
- Edit the same field again: Uncheck Nullable
  - Expected: no longer nullable, default value persists
  - Actual: no longer nullable, default value was unset(!)

Here is a quick screen captcha demoing this behavior:
- https://github.com/user-attachments/assets/8656b7ed-acc9-4754-a8d7-ba27f8029230

**Comment by rijkvanzanten** [comment]
@echocrow Is this a new thing you started noticing 10.13+ or has it been an issue previously?

**Comment by echocrow** [comment]
@rijkvanzanten we only _noticed_ it recently, but this would explain some other odd nullable configs I spotted elsewhere.

I just tried some older versions, and am seeing identical or similarly broken behaviour:
- `10.12.1`: Same broken behaviour
- `10.11.1`: Same broken behaviour
- `10.10.2`: Same broken behaviour
- `10.8.3`: Also broken, but slightly differently

Unlike newer versions, in `10.8.3`, seems like updating Default Value (setting or clearing it) would enable nullable, but unchecking nullable did (correctly) not clear the default value.
Not sure if relevant, but here's a screen capture of the behavior in 10.8.3:
- https://github.com/user-attachments/assets/de708131-1dac-43aa-9b67-b87fed676170

**Comment by rijkvanzanten** [comment]
Thanks for checking! Was trying to figure out if this is a recent regression, or a sneaky bug that's hard to spot that has been there for a while 🙂 

The place we're modifying these two field properties is here:

https://github.com/directus/directus/blob/a9cca2cea61247687699b4449ccb9a9505d7b123/api/src/services/fields.ts#L768-L794

I'm wondering if there's a `knex` default that will default the default value to empty on any change for example

**Comment by echocrow** [comment]
> I'm wondering if there's a knex default that will default the default value to empty on any change for example

@rijkvanzanten I believe you're right. Looks like this is also known & expected behavior in Knex. See [this warning](https://knexjs.org/guide/schema-builder.html#alter) for `alter()` in their docs:

> [!WARNING]  
> […] if you like to add notNullable and keep the old default value, the alter statement must contain both […]. If one just tries to add .notNullable().alter() the old default value will be dropped.

i.e. the following code:
```ts
await knex.schema.alterTable('repro', (table) => {
const column = table.dateTime('date_created', {useTz: false})
    column.notNullable()
    column.alter()
})
```
will clear the default value. In order to keep the default value, it'll need to be explicitly set - at least when nullable is modified.

Modifying `addColumnToTable()` to something like this:
```ts
const default_value = field.schema?.default_value !== undefined
	? field.schema.default_value
	: alter?.default_value;
if (default_value !== undefined) {
	// ...
}

const is_nullable = field.schema?.is_nullable !== undefined
	? field.schema.is_nullable
	: alter?.is_nullable
if (is_nullable) {
	column.nullable();
} else {
	column.notNullable();
}
```
seems to do the trick. This will always explicitly set the default (unless undefined) and nullable/not-nullable, but I don't think there is a meaningful performance improvement to gain here.

Some more testing is advisable (particularly for `null` vs `undefined` defaults). Doesn't look like any tests are in place for this behavior yet. Thoughts on next steps?

**Comment by rijkvanzanten** [comment]
> This will always explicitly set the default (unless undefined) and nullable/not-nullable, but I don't think there is a meaningful performance improvement to gain here.

I think that's fine. Seeing that it drops the default value otherwise, I believe the performance characteristics are the same 👍🏻 

> Thoughts on next steps?

I'd say it's time for a PR with this suggested fix! 🙂
