### ISSUE TITLE
ID field missing in Flow webhook payload when creating new M2M item

### ISSUE THREAD

**Issue by GarthWood** [directus/directus#23107]
### Describe the Bug

When having a M2M relationship and using a Flow trigger with wehbook, the event payload does not contain the id of the newly created item, when using the `Create New` button.

Not having the `id` included in the payload makes it impossible to reference the item later.

### To Reproduce

1. Create a collection called `paragraphs` with a string input field called `value`.
2. Create a collection called `documents`, and add a `paragraphs` field with a M2M relationship  to `paragraphs`.
4. Ensure the `Create New`button is enabled on the `paragraphs` field.
5. Setup a data Flow to invoke a webhook for the `items.create` and `items.update` triggers on the `documents` collection. Use POST and `{{ $last }}` as the body for the webhook.
6. Create a new document and click `Create New` to create a new paragraph with value `test`.
7. Save the document and check the webhook event payload.

Notice the `paragraphs_id` object in the payload does not contain the `id` of the newly created paragraph, it only contains the content.

```
{
  "event": "documents.items.create",
  "payload": {
    "paragraphs": {
      "create": [
        {
          "paragraphs_id": {
            "value": "test"
          }
        }
      ],
      "update": [],
      "delete": []
    }
  },
  "key": 1,
  "collection": "documents"
}
```

### Directus Version

v10.13

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

mysql

**Comment by hanneskuettner** [comment]
For a `filter` hook that is expected behavior, as it receives the item *before* the value is inserted into the DB, i.e. before an ID is assigned. If you want to have the item including the ID you need to listen to the `action` hooks if possible. Those include the newly created item IDs. 

I'm closing this, as this is expected behavior.

**Comment by GarthWood** [comment]
I forgot to mention that in my description. I'm using `Action (non-blocking)` as the type.

Is this what you're referring to?

**Comment by GarthWood** [comment]
Please can this issue be reopened based on the new information I have provided.

**Comment by rijkvanzanten** [comment]
The `key` field is the primary key of the item that's saved. The nested relational item will trigger the hook for the corresponding collection when it is relationally inserted, so in this case you'd want to listen to `paragraphs.items.create`

**Comment by GarthWood** [comment]
Thanks, but as mentioned in the description the ID field is not present in the payload I showed, which when using the action type it should be, as mentioned above.
