### ISSUE TITLE
errors.SERVICE_UNAVAILABLE upload assets

### ISSUE THREAD

**Issue by carlospjobgether** [directus/directus#23109]
### Describe the Bug

When I try to upload an asset it shows me this error
[SERVICE_UNAVAILABLE] Couldn't save file d04e71e9-88a5-42bc-9bc0-4acdda6521c1.jpeg
![image](https://github.com/user-attachments/assets/8e6ce36d-4fbd-44a8-b4bc-9a710db707ed)

### To Reproduce

Go to /admin/files/folders/c0a2c680-4d0b-4ef5-bfb3-860f3a1d69e4
Upload image .png

### Directus Version

v9.16.1

### Hosting Strategy

Directus Cloud

**Comment by hanneskuettner** [comment]
Since you're running Directus version 9.x is not supported anymore I will close this issue, as I would assume the problem probably has been fixed in the last few years.
