### ISSUE TITLE
There is a caching issue when using Roles & Permissions for different users

### ISSUE THREAD

**Issue by sharmahemal** [directus/directus#23125]
### Describe the Bug

There is a caching issue when using Roles & Permissions for different users. The problem occurs when assigning the "Department" module to the "Staff Member" role.

### To Reproduce

**Steps to Reproduce:**

1. Create two roles: "Admin" and "Staff Member".
2. Create two modules: "Department" and "Staff Member".
3. Assign the "Department" module to the "Staff Member" role.
4. Log in as a user with the "Staff Member" role.

**Expected Behavior**:
The "Department" menu should be visible to users with the "Staff Member" role immediately after the assignment.

**Actual Behavior:**
The "Department" menu does not appear for the "Staff Member" role until the ECS (Elastic Container Service) is restarted.

**Environment:**
```
CACHE_SCHEMA:60 seconds
ACCESS_TOKEN_TTL: 1d
REFRESH_TOKEN_TTL: 1d
CACHE_AUTO_PURGE: true
CACHE_SYSTEM_TTL: 300
```

### Directus Version

9.14.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

mysql aurora

**Comment by hanneskuettner** [comment]
The 9.14 version has been released two years ago and plenty of new versions have been released. I would assume that a fix was part of the last two years worth of releases, as this issue does not occur in the most recent version. So, if possible, please consider upgrading to the most recent version.
