### ISSUE TITLE
AxiosError: Network Error

### ISSUE THREAD

**Issue by koddr** [directus/directus#23122]
### Describe the Bug

```json
{
  "message": "Network Error",
  "name": "AxiosError",
  "code": "ERR_NETWORK",
  "config": {}
}
```

<img width="695" alt="Снимок экрана 2024-07-29 в 07 53 30" src="https://github.com/user-attachments/assets/d6dca20a-d22e-42e7-b3f8-02b7e7197b15">

On Docker console:

```console
[07:21:06.415] WARN: Connection Error: Connection ended unexpectedly
2024-07-29T07:22:36: PM2 log: Launching in no daemon mode
2024-07-29T07:22:36: PM2 log: App [directus:0] starting in -cluster mode-
2024-07-29T07:22:39: PM2 log: App [directus:0] online
```

### To Reproduce

1. Go to collection;
2. Start edit collection's fields;
3. Switch tab on the browser for 1-3 min.;
4. Return to Directus tab;
5. See error.

### Directus Version

v10.13.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 16

**Comment by hanneskuettner** [comment]
Can you provide us with more information to go on? Because this could very well be an internet connectivity or something along those lines. Does the browser console offer any more information? Can you see which API request fails?

**Comment by rijkvanzanten** [comment]
Closing this for now as this is most likely a client-side network error (like the connection being dropped, the internet being down, etc), rather than a bug in Directus. The AxiosError is only thrown if the client isn't able to reach the server at all 👍🏻
