### ISSUE TITLE
Cannot revert user to default provider

### ISSUE THREAD

**Issue by nicolaracco** [directus/directus#23136]
### Describe the Bug

When a user is assigned to a SSO provider, their provider cannot be reverted to the default one.
<img width="421" alt="image" src="https://github.com/user-attachments/assets/146459bc-5132-4b1f-a000-d85b367f42f2">

### To Reproduce

- Log in via SSO on a directus instance
- From the backoffice, open the user detail page
- Observe the Provider field is set to the SSO
- Observe that once the Provider field is clicked, the "default" provider isn't shown
- Open the detail page of a user which is not using the SSO
- Observe the Provider field value is "default"

### Directus Version

v10.13.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
You can reset a user to the default provider using the following "reset to default" link
![image](https://github.com/user-attachments/assets/10dba862-07ce-47be-ab0c-f14439e0838f)
