### ISSUE TITLE
Unable to listen on a Unix socket

### ISSUE THREAD

**Issue by McSundae** [directus/directus#23142]
### Describe the Improvement

I currently tried to host the current version of Directus on my hoster Mittwald. Sadly it's necessary to enter a socket as a port for any nodejs app on Mittwald. Therefore it would be necessary to make the Integer Check for the port optional.

I think about a config flag that you could set to false to disable this check.

The check is being executed in `/node_modules/@directus/api/dist/server.js`:
```js
const port = parseInt(env['PORT']);
```

In Combination with the flag that I image it could look like this:
```
const port = env['PORT_CHECK'] ? parseInt(env['PORT']) : env['port];
```

**Comment by rijkvanzanten** [comment]
> Sadly it's necessary to enter a socket as a port for any nodejs app on Mittwald

Mind sharing some documentation around this? This is the first time ever this has come up! 👀

**Comment by rijkvanzanten** [comment]
Instead of adding a new flag, I'd rather drop the `parseInt` from the `server.js` file and rely on the regular env var value parsing from `@directus/env` instead

**Comment by McSundae** [comment]
The PORT Option will usually look something like that on Mittwald:
PORT="/tmp/.mwservice/html%2Fdirectus.sock"

Just dropping the parseInt would be also okay for me, I don't need it anyway :D

**Comment by rijkvanzanten** [comment]
@McSundae I think dropping parseInt here should work just fine 🙂 Wanna open a PR with that tweak? 🚀

**Comment by McSundae** [comment]
I just opened a PR:
https://github.com/directus/directus/pull/23150

**Comment by ComfortablyCoding** [comment]
> > Sadly it's necessary to enter a socket as a port for any nodejs app on Mittwald
> 
> Mind sharing some documentation around this? This is the first time ever this has come up! 👀

It is possible I misunderstood but per the mittwald docs they accept a port for express apps? Is that not possible here @McSundae ?

https://developer.mittwald.de/docs/v2/platform/workloads/nodejs/#expressjs
