### ISSUE TITLE
Query "functions" syntax is not allowed in TypeScript types

### ISSUE THREAD

**Issue by pomeh** [directus/directus#23145]
### Describe the Bug

Documentation references [Functions **for "live" modification of values stored in a field**](https://docs.directus.io/reference/query.html#functions), for example `filter[year(date_published)][_eq]=2021`. That's very nice to have :)

The problem is, when using the **JavaScript SDK** with **TypeScript types**, this syntax is not recognized and thus is not allowed.

For example, I have a collections with a `date_updated` field, so this syntax works fine:

```ts
client.request(
    readItems('trainings', {
        fields: ["date_updated"],
    })
);
```

while this syntax triggers a TypeScript error:

```ts
client.request(
    readItems('trainings', {
        fields: ["date_updated", "year(date_updated)"],
    })
);
```

The given error is:

`Type '"year(date_updated)"' is not assignable to type '"*" | "sort" | "id" | "date_updated" | [...]'. Did you mean '"date_updated"'?`

![error](https://github.com/user-attachments/assets/708892c5-17ab-4115-9ad4-423c4cc0c67b)

The value `year(date_updated)` is also not listed by the VS Code autocompletion system:

![autocomplete](https://github.com/user-attachments/assets/9fec5bc8-10d0-4183-a233-692ab615b0a8)

The same problem occurs for both `fields` and `filter` properties from `readItems` query.

I'm using a custom Directus Docker image, based on Directus v10.13.1 + a few custom extensions, but I don't think it's relevant here.
I'm using NPM package `@directus/sdk` version `16.0.2` (and Next.JS as front app).

As a side note, TypeScript validations fails, but the code is still working and the functions are applied as expected.

### To Reproduce

Use the "Functions" syntax with the `readItems` SDK api:

```ts
client.request(
    readItems('trainings', {
        fields: [
            "date_updated",           // this is OK
            "year(date_updated)"      // this triggers a TS error
        ], 
        filter: {
                "date_created": {             // this is OK
                        "_eq": "whatever",
                },
                "year(date_created)": {       // this triggers a TS error too
                        "_eq": "2024",
                },
        },
    })
);
```

### Directus Version

v10.13.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
Is the `date_updated` field properly typed as being `'datetime'` on the `Schema`? This determines whether it accepts datetime functions or is considered to be a regular string.
https://docs.directus.io/guides/sdk/types.html#collection-field-types

Closing the issue for now but happy to re-open if needed 😄

**Comment by pomeh** [comment]
Indeed this works when I change the type of the property. Thanks for pointing this out, for the playground and for your reactivity :)

I used `/server/specs/oas` endpoint to generate OpenAI Spec, then `directus-typescript-gen` npm package to convert to TypeScript types.

In the OAI spec, typing looks correct:

```json
          "date_updated": {
            "nullable": true,
            "type": "string",
            "format": "timestamp"
          }
```

Although the "Versions" core object has also a `date_updated` field, but it's typing is different (`date-time` vs `timestamp`):

```ts
          "date_updated": {
            "description": "When the Content Version was updated.",
            "type": "string",
            "example": "2022-05-11T13:14:53Z",
            "format": "date-time",
            "nullable": true
          },
```

Any reason why ?

Both ends with type `string` in the resulting TypeScript defintition code. I will look into `directus-typescript-gen package to understand why.

Also, although it's veryyy minor, is there anything doable to fix the VS Code autocompletion system for this case ?

Lastly, in the playground you wrote `Hmm this looks like it could be a different new issue`. What do you mean ? Is there anything I should or can do for this ?
