### ISSUE TITLE
Image manipulation on the fly

### ISSUE THREAD

**Issue by Laurensvdmaas** [directus/directus#2314]
# Feature Request
Imagine manipulation on the fly.

## What problem does this feature solve?
Faster, smaller websites & less storage needed. No need to pre-define image.

## How do you think this should be implemented?
Being able to call an image with ?width=325&height=150&fit=crop&quality=75

## Would you be willing to work on this?
Yes, al tho my php knowledge isn't the best.

**Comment by rijkvanzanten** [comment]
Is this what you're looking for?

https://docs.directus.io/guides/thumbnailer.html

**Comment by Laurensvdmaas** [comment]
Wouldn't thumbnailer require me to specify the dimensions/fit first?

**Comment by Laurensvdmaas** [comment]
I just read the docs a bit better you're right.
