### ISSUE TITLE
Nested fields not shown in Field Validations in the new Policy

### ISSUE THREAD

**Issue by samehhady** [directus/directus#23158]
### Describe the Bug

When I try to create a policy with permissions and add custom rule then select item permissions I can find the nested fields to select from in my relation, yet If I select field validation I don't see any nested values.

I am not sure If that was done in purpose or not, but for sure will be helpful if we have them returned to properly set permissions.
<img width="611" alt="Screenshot 2024-08-01 at 10 27 57 PM" src="https://github.com/user-attachments/assets/f61ac36f-f985-4492-a0d6-216b870248f3">
<img width="622" alt="Screenshot 2024-08-01 at 10 27 41 PM" src="https://github.com/user-attachments/assets/a37e877d-d2c6-42dc-9d4d-13b68cf6698f">

### To Reproduce

Access Policy -> Policy -> Custom rule for create -> field validations

### Directus Version

11.0.0-rc.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
This seems to be in line with how it is presented in the latest v10.13.1 version, see `user_created`  in the screenshot below

<img width="673" alt="Screenshot 2024-08-02 at 15 54 50" src="https://github.com/user-attachments/assets/3cdcf81e-c715-43b4-a226-7045379b5f69">

This was purposefully implemented here https://github.com/directus/directus/pull/14818
