### ISSUE TITLE
Sorting of aggregated result returns server error

### ISSUE THREAD

**Issue by licitdev** [directus/directus#23189]
### Describe the Bug

Sorting of aggregated queries was added in https://github.com/directus/directus/pull/19568 but it currently returns a server error. 

The aggregation works only if the sort query is removed.

`"You don't have permission to access field \"sum\" in collection \"v11_agg\" or it does not exist. Queried in root."`

`GET /items/v11_agg?aggregate[sum]=value&groupBy=type&sort[]=sum.value`

There's a pending documentation PR https://github.com/directus/directus/issues/21014 for this functionality.

### To Reproduce

Create a collection named `v11_agg` with a type (string) and value (integer) field.
Populate some records.
Perform a `GET /items/v11_agg?aggregate[sum]=value&groupBy=type&sort[]=sum.value`

### Directus Version

v11.rc3

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

pg

**Comment by hanneskuettner** [comment]
Fixed in #23193
