### ISSUE TITLE
Query time logging leaks memory for failed queries

### ISSUE THREAD

**Issue by hanneskuettner** [directus/directus#23183]
For failed database queries the time tracing leaks memory. The query ID is only removed in case of a successful query, but not for the `query-error`[^1] event.

https://github.com/directus/directus/blob/d57ec3ba45d7d785c449a6bacfbdf9abeb3b2c9f/api/src/database/index.ts#L169-L183

[^1]: https://knexjs.org/guide/interfaces.html#query-error

**Comment by Sanket-0510** [comment]
@hanneskuettner can I work on this?

**Comment by hanneskuettner** [comment]
You want to tackle this issue?

I think it's only necessary to add an `on('query-error')` event handler that tries to remove the entry in the `times` map, similar to how it is removed in the success handler.

**Comment by hanneskuettner** [comment]
Sure!
