### ISSUE TITLE
No Logs in Flow

### ISSUE THREAD

**Issue by dataheadless** [directus/directus#23196]
### Describe the Bug

Suddenly there are no logs in the flow, although flow webhook receives the requests

### To Reproduce

N/A

### Directus Version

v9.x

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL

**Comment by hanneskuettner** [comment]
Heya! The v9 release is at least a year old and is not supported anymore as we are only tracking open issues in the most recent release. As such I will close this issue and implore you to update to the most recent version of Directus with the most recent features and bug/security fixes.
