### ISSUE TITLE
Policies not returned for user

### ISSUE THREAD

**Issue by stx-chris** [directus/directus#23229]
### Describe the Bug

Calling `readMe()` or using the REST interface `/users/me` would not return the `policies` object. These are the fields returned:

```
{
  "data": {
    "id": "31f7ed1d-da1c-0000-0000-b98de1c1b559",
    "first_name": "First name",
    "last_name": "Last name",
    "email": null,
    "password": null,
    "location": null,
    "title": null,
    "description": "",
    "tags": null,
    "avatar": null,
    "language": null,
    "tfa_secret": null,
    "status": "active",
    "role": "...",
    "token": "**********",
    "last_access": null,
    "last_page": null,
    "provider": "default",
    "external_identifier": null,
    "auth_data": null,
    "email_notifications": true,
    "appearance": null,
    "theme_dark": null,
    "theme_light": null,
    "theme_light_overrides": null,
    "theme_dark_overrides": null
  }
}
```

### To Reproduce

`readMe()` in SDK or using the REST interface `/users/me`

### Directus Version

v11.0.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
This is what I am seeing for my local admin user

```json
{
  "data": {
    "id": "3860a5d3-1d77-45c5-875c-1409367be995",
    "first_name": "Admin",
    "last_name": "User",
    "email": "admin@example.com",
    "password": "**********",
    "location": null,
    "title": null,
    "description": null,
    "tags": null,
    "avatar": null,
    "language": null,
    "tfa_secret": null,
    "status": "active",
    "role": "b2f7e681-c8ee-4798-b4b1-03618f33747e",
    "token": null,
    "last_access": "2024-08-07T12:41:32.000Z",
    "last_page": "/content",
    "provider": "default",
    "external_identifier": null,
    "auth_data": null,
    "email_notifications": true,
    "appearance": null,
    "theme_dark": null,
    "theme_light": null,
    "theme_light_overrides": null,
    "theme_dark_overrides": null,
    "policies": []
  }
}
```

So it definitely has the policies. Could it be a permissions issue where the user is not allowed to see the `policies` field? Or is the user you're looking at also an admin?

**Comment by stx-chris** [comment]
Thanks @hanneskuettner, but never mind. Since we use a minimal access policy, policies are not returned it the user has no access to the new `directus_access` collection. Adding this table and allowing read access was enough.
![CleanShot 2024-08-07 at 13 34 43](https://github.com/user-attachments/assets/0edf494a-7a7e-480a-9825-89d623153454)

**Comment by stx-chris** [comment]
How can I get the policy name then? In real scenarios, we compare the list of policies, such as "allow.ui.config" and so on. For some reason, I cannot manage to get the policy names from the user. 

Tried `filter: *,policies.*`, accessing name directly and so on, but all I get is access to the ids. Does someone know how to get the policy names a user has from `/users/me` without accessing the policies/access tables directly?

![CleanShot 2024-08-07 at 13 47 06@2x](https://github.com/user-attachments/assets/e86e9c8e-1264-4bd9-aa9b-d92df96f2133)

**Comment by hanneskuettner** [comment]
You might also need to give access to the `directus_policies` collection (and maybe limit that with `$CURRENT_USER` and `$CURRENT_ROLES`).

This is what I see for an admin user with all permissions.

![CleanShot 2024-08-07 at 13 55 38](https://github.com/user-attachments/assets/dbe36ac9-b7ac-4962-9bf3-e57c11094a46)


It's generally a good idea to compare the output you see with an admin account (which has all permissions by virtue of being an admin) to a test account to see if it might be a permissions problem or a general problem.

**Comment by stx-chris** [comment]
Indeed! Thanks a lot. So in summary, a user needs access to the following tables in order for this to work:

```
directus_access
directus_policies
directus_users

```
![CleanShot 2024-08-07 at 14 32 09@2x](https://github.com/user-attachments/assets/342c9626-9091-4383-9cf2-05f9ebabc581)
