### ISSUE TITLE
Release 11 schema apply breaks

### ISSUE THREAD

**Issue by keesvanbemmel** [directus/directus#23235]
See comment on issue below @paescuj, I suspect this is the same thing. Migration went ok, but after applying our own schema again (in our CI/CD flow) the parent column from the directus_roles table was dropped again.

Please add all system tables/columns to the "exclude" list from schema apply!

              Good catch! Thanks @keesvanbemmel!

_Originally posted by @paescuj in https://github.com/directus/directus/issues/22584#issuecomment-2136668166_

**Comment by hanneskuettner** [comment]
Looks like it already is added to the `@directus/system-data` package, see 

https://github.com/directus/directus/blob/7dc49e5e442d9e73f1db4673873d3ceb2c4e3dd8/packages/system-data/src/fields/roles.yaml#L34-L47

So now I wonder what the issue might be in this case.

**Comment by keesvanbemmel** [comment]
hmmm let me check! will be back!

**Comment by hanneskuettner** [comment]
Any news from your side?

**Comment by keesvanbemmel** [comment]
No nothing. After two hours of trying to figure out what went wrong we reverted back to 10 to try again in a week or so.

**Comment by hanneskuettner** [comment]
Thank you for the info! Did you perform similar debugging steps as in the issue you referenced? Are you seeing any inconsistencies in the schema diff? Do you have any steps I could try to reproduce this on my end?

Thank you again!

**Comment by keesvanbemmel** [comment]
I can't reproduce this... will close for now.
