### ISSUE TITLE
Projects/databases and using Directus to manage content for multiple projects

### ISSUE THREAD

**Issue by justrealmilk** [directus/directus#2323]
I just finally got up and running on nginx (everywhere I turn, mod_rewrite burns me) and I have a few questions now that I've got into admin.

I read that the project uses database and "project" somewhat interchangeably but then I got into Global Settings and noticed the database name as a value for the project name field (that was confusing, I know).

I'm one of i expect many who would like to use directus for multiple projects. So far, my understanding is that I should create separate instances for each project, each with its own database

Is there a better solution?

---

I originally sent these lines to the chat bot thing on the Directus web site but it's been 7 hours 👀

Since then, I've learnt more by skimming about 10 issues including #2303 

So, would I be correct in assuming that I could use a single Directus databases to store collections for various purposes and that I could then use Users and Roles to hide, show, allow, and deny access to them?

What can be achieved with https://docs.directus.io/api/reference.html#project-prefix ?

As I am using NGINX, I did need to perform a more manual setup (the shell scripts were great), and I never had the pleasure of experiencing the Install wizard

**Comment by theharshin** [comment]
Hello @justrealmilk, let me help you with some setup ideas.

Directus can handle multiple databases with the single setup of an APP(which is static front-end code) & an API(which is backend code).
So if you need to manage multiple projects, you can follow the stepes:

1. Clone and host APP and API.

2. Configure `api.php` which contains the default project config. The API endpoint for this setup will be `your-setup-url/_/`.

3. Now for other database instances, create `api.<instance-name>.php`. The API endpoint for this setup will be `your-setup-url/<instance-name>/`.

4. Now to login into multiple instances, add the above URLs in `config.js` which can be found in APP [here](https://github.com/directus/directus/blob/master/public/admin/config.js#L9)

Let me know if this makes sense 🙂 

If the purpose of both the projects is same, you can handle it in single instance with the help of `roles` to give partial permissions of viewing and editinng the data.

**Comment by justrealmilk** [comment]
Oh okay this look great! 

With this approach, what should I be using the API environment for, if anything?

**Comment by rijkvanzanten** [comment]
@justrealmilk 

> I originally sent these lines to the chat bot thing on the Directus web site but it's been 7 hours 

I was asleep! 😄 

> With this approach, what should I be using the API environment for, if anything?

It depends on the kind of project you're building. By using multiple projects (/ databases) on the same API, you only need to update one API for all your connected projects. Some others like to use these database copies as a staging / prod setup.

**Comment by justrealmilk** [comment]
### Well this is excellent, awesome.

Is there any flags I can send along with `bin/directus install:database` that didn't make the docs?

I was dumping my api.php so I could trick the script into installing a new "sub" database

**Comment by rijkvanzanten** [comment]
I don't think the CLI has any other options. Can you confirm this @bjgajjar?

I'm closing this as the original question has been answered.
