### ISSUE TITLE
Endpoint route doesn't exist

### ISSUE THREAD

**Issue by Pachat** [directus/directus#23238]
### Describe the Bug

After creating the endpoint (see code below) rebuild, restart docker, still get "route doesn't exist".
Might be a lack in documentation.

### To Reproduce

Scaffold an endpoint with the following code inside src/index.js
```
export default {
  id: 'testendpoint',
  type: 'endpoint',
  handler: ({ router, services, exceptions }) => {
    router.get('/signup', (req, res) => {
      res.json({ message: 'Signup GET endpoint is active' });
    });

    router.post('/signup', (req, res) => {
      res.json({ message: 'Signup POST endpoint is active' });
    });

    console.log('Signup extension: Routes registered');
  },
};
```
npm run build

restart directus docker container

If of any interest here, my proxy .conf contains
```

    ProxyPass / http://localhost:8031/
    ProxyPassReverse / http://localhost:8031/
    ProxyPreserveHost On

    # Serve the connect page directly
    RewriteEngine On
    RewriteRule ^/inscription$ /var/www/app.mysite.com/html/inscription.html [QSA,L]
    <Location /inscription>
        ProxyPass !
    </Location>

```
where inscription.html is the html form that sends the POST request to the endpoint
`https:app.mysite.com/testendpoint`

package.json
```
{
	"name": "directus-extension-endpoint-testendpoint",
	"description": "Direct signup",
	"icon": "extension",
	"version": "1.0.0",
	"main": "dist/index.js",
	"keywords": [
		"directus",
		"directus-extension",
		"directus-extension-endpoint"
	],
	"type": "module",
	"files": [
		"dist"
	],
	"directus:extension": {
		"type": "endpoint",
		"path": "index.js",
		"source": "src/index.js",
		"host": "^11.0.0"
	},
	"scripts": {
		"build": "directus-extension build",
		"dev": "directus-extension build -w --no-minify",
		"link": "directus-extension link"
	},
	"devDependencies": {
		"@directus/extensions-sdk": "11.0.9"
	}
}

```

the extension is in `/extensions/directus-extension-endpoint-testendpoint`
and is correctly loaded on Directus start as per logs.

But never got 'Signup extension: Routes registered'

### Directus Version

v11.0.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgis:15-master

**Comment by izoukhai** [comment]
I think you forgot to wrap it with defineEndpont

```
export default defineEndpoint({
  id: "api",
  handler: (router, ctx) => {
    setupRoutes(router, ctx);
  },
});
```

**Comment by hanneskuettner** [comment]
The endpoint would be available to `https:app.mysite.com/testendpoint/signup`

**Comment by rijkvanzanten** [comment]
Closing this as it seems like a usage problem rather than a bug in Directus itself. Happy to reopen if that's not the case

**Comment by Pachat** [comment]
Thanks for the indication.
