### ISSUE TITLE
ERROR: "DB_CLIENT" Environment Variable is missing during project init

### ISSUE THREAD

**Issue by ComfortablyCoding** [directus/directus#23255]
### Describe the Bug

Initializing a project via `npm init directus-project@latest <project-name>` errors with `ERROR: "DB_CLIENT" Environment Variable` after database is selected and credentials provided. Upon investigation this seems to occur on during the `runMigrations` stage.

Based on the investigation this is caused by the recent addition of `getSchemaInspector` to the `Permission Policies` migration in https://github.com/directus/directus/pull/23253. When `getSchemaInspector` is called for the first time it will trigger a `getDatabase` which requires a `.env` file to be present. As the `.env` file has not been generated yet the error is thrown.

### To Reproduce

1. npm init directus-project@latest tester
2. Select sqlite (applies to any db)
3. Select file location
4. Observe error 

<img width="558" alt="Screenshot 2024-08-08 at 4 12 45 PM" src="https://github.com/user-attachments/assets/1e7a7aa3-0a4b-4b22-9a32-1d883d45d343">

### Directus Version

v11.0.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by McSundae** [comment]
I can confirm that error - tried installing a fresh Directus instance and also ran into this issue

**Comment by ComfortablyCoding** [comment]
> I can confirm that error - tried installing a fresh Directus instance and also ran into this issue.
> 
> Maybe noteworthy this is not connected to docker hosting, it's also affecting CLI Install

That was my error on the report, it should have said self hosted (Custom). This should only affect the CLI install.
