### ISSUE TITLE
Querying related items fails if primary key access is not given

### ISSUE THREAD

**Issue by NecoHorne** [directus/directus#23250]
### Describe the Bug

On V11.0.0 When calling `items/item` API using the `fields=*.*.*` It returns a 403 on a relation fields id(primary key)

Pre v11 on the role system when read access was configured for relational items it was not needed to include read access to the id field, it would return the relevant data that the role does have access to read. on V11 it looks like read access to the primary key must be given to access any data from the relational item. 

Example below: 

listings has a O2M relationship with booking. 

I only want a few data fields from the booking to be sent back to the front-end
permissions for listing grants read access to bookings. 

![image](https://github.com/user-attachments/assets/90f4c8b3-b35c-4dce-8e3b-133e03403291)
![image](https://github.com/user-attachments/assets/b211070e-1ea0-40dd-8030-ee53c21ffef7)

With the role based permissions this worked correctly as calling `/items/listings?fields=*.*.*` would return an array of listings, and only the selected data from the bookings table but on the new policies system it throws a 403 on the id field of the booking table. 

*Asked on discord if this was intentional and was asked to open an issue.

### To Reproduce

Create an item with a O2M relation to another item. 

in the relational item do not give read access to the policy for the id/primary key.

### Directus Version

v11.0.0

### Hosting Strategy

Self-Hosted (Custom)

### Database

MySQL V8.0.39-0ubuntu0.22.04.1

**Comment by rijkvanzanten** [comment]
It was released in 11.0.2 4 hours ago 👍🏻
