### ISSUE TITLE
Question: Force login possible?

### ISSUE THREAD

**Issue by lookingdown** [directus/directus#2327]
Is it possible to force login? User is already in other system (website) with jasny/sso and I would like to have transparente access to directus without another login.. 
User is already logged in on a trusted site would like to force login for user in directus..  database is the same, same usertable.
Thankful for pointersor how .. to force or autologin user.

**Comment by benhaynes** [comment]
I'm not sure, but this could also benefit internal platforms like Directus Cloud. 

Thoughts @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
Sounds useful. There isn't a way currently to achieve this. I also have some trouble imagining how this would work 🤔

**Comment by benhaynes** [comment]
Perhaps the authenticated external application could generate a one-time-use token through the API? Could that be passed in the headers (not sure if a query string would be secure enough) to the Directus App to login?

**Comment by scottconrad** [comment]
@rijkvanzanten, you'd want to look at allowing for JWT auth scheme. leave it up to them to ensure they have a . prefix on the cookie so it can be SSO, if they have to do a double redirect or whatever that'd be fine. If we decide to use this, I'll be happy to share some examples on how to implement.

**Comment by rijkvanzanten** [comment]
We're already (half) using JWTs for auth, so I think that would be a good direction to go in. We're discussing the “ideal” way the JWT flow should work in https://github.com/directus/app/issues/1342#issuecomment-465377623. I'd love to hear your comments on that as well 🙂

**Comment by rijkvanzanten** [comment]
Lets continue this in https://github.com/directus/app/issues/1342#issuecomment-465377623
