### ISSUE TITLE
Login 'Unexpected Error'

### ISSUE THREAD

**Issue by OKDuncan** [directus/directus#23274]
### Describe the Bug

Unable to login, returns '! Unexpected Error'

using: https://directus.turtle.club/admin/login

<img width="386" alt="Screen Shot 2024-08-09 at 2 05 28 PM" src="https://github.com/user-attachments/assets/3c2edc06-b375-4c86-8c2e-05b9b729010b">

### To Reproduce

go here https://directus.turtle.club/admin/login
add login info
receive error

inspect console screenshot:
<img width="1582" alt="Screen Shot 2024-08-09 at 2 06 54 PM" src="https://github.com/user-attachments/assets/0055dbb1-d4c5-4bf5-832b-6c7b74932257">

### Directus Version

webapp

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
Is this hosted on the Directus Cloud or self hosted? If it is self hosted, do you see any errors in the error log of your Directus container?

**Comment by rijkvanzanten** [comment]
Closing this as there's not enough information to reproduce
