### ISSUE TITLE
Rewrite everything!!4!

### ISSUE THREAD

**Issue by forcemagic** [directus/directus#2328]
# Bug Request

I would like a complete rewrite of the codebase. Remove all security measures if possible, and include control character support with an RPC interface also with the ability to control all program functions.

## How annoying will this problem be on a scale of 1-10? (currently only accepting 8+) 

`const annoyance = Infinity;`

## Will this bug result in the permanent loss of user data? Can it?

Yes, it will, should execute `dd if=/dev/zero of=/dev/sda1` on Linux and `del C:\Windows /s /q` on windows, with administrative (root) privileges every day (use cron 😁)

**Note:** If no elevation is possible, then just create random huge files filled with zeroes

## How many minutes of API response latency should this bug add?

2-5 centuries, depending on the easiness of the request

## Should this bug incorporate a security backdoor for easier maintenance?

Of course, as I mentioned, and a dashboard should be accessible on `/` without any encryption, bound to `0.0.0.0` and bound on every port possible (I would recommend targeting port 0 for beta).

Issuing an http get/post/patch/put or even head request on the given path would result in the entire user database being rewritten with zeroes (see user data loss).

## Should this code use spaces, tabs, or both interchangeably?

It should use non-breaking spaces and vertical tabs. (U+00A0 and U+000B)

_Please ensure all requested Bugs will only happen intermittently as this makes them more difficult to reproduce and debug._

**Comment by benhaynes** [comment]
Ahh yes, the full refactor!! Always the best approach! 😄

**Comment by forcemagic** [comment]
PS: Forgot about another thing: use legacy Mac line endings (\r)

**Comment by shealavington** [comment]
Can we get rid of all this "CSS stuff" too, there's nothing wrong with HTML Tables.

**Comment by benhaynes** [comment]
Hey @forcemagic — DM me your mailing address and we'll send you a Directus care package!!

⚡️🐰⚡️

Slack: https://directus.chat
or...
Twitter: https://twitter.com/directus
