### ISSUE TITLE
Error using field configuration "Value has to be unique"

### ISSUE THREAD

**Issue by bke-xuan** [directus/directus#23282]
### Describe the Bug

When configuring "**value has to be unique**" for a field, after saving, all fields of the collection will disappear from the collection editing interface. In the content management interface, a notification will be received: **[FORBIDDEN] You don't have permission to access this.**

After restarting the container the errors are gone but will return when doing the above operation again.

<img width="1222" alt="Screenshot at Aug 11 14-06-10" src="https://github.com/user-attachments/assets/3375e2f0-f040-4e6c-b142-dc18cd2288b4">
<img width="1158" alt="Screenshot at Aug 11 14-06-36" src="https://github.com/user-attachments/assets/b4fdf81d-03a2-4667-967f-d7747e95e619">
<img width="1059" alt="Screenshot at Aug 11 14-06-54" src="https://github.com/user-attachments/assets/52302ff3-f940-4708-af30-9b35c796819c">

### To Reproduce

Test date: 08/11/2024
Version used: 11.0.1
Deployment method: docker compose
Operating system: Mac OS
Database: Mariadb

### Directus Version

11.0.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

mariadb

**Comment by hanneskuettner** [comment]
Can you provide the full collection, field configuration and permissions for the user that is seeing the error. I'm unable to reproduce this locally with the steps you provided.
