### ISSUE TITLE
O2M fields allow deletion even if both add buttons are not visible

### ISSUE THREAD

**Issue by terbshaeusser** [directus/directus#23285]
### Describe the Improvement

In the current version (11.0.1 as of writing) O2M fields allow to delete list items when the add new and the add existing buttons are not visible. 
To me it doesn't make sense why a user should only be able to delete items. Therefore, I purpose to show the delete icon only if either one of the add buttons is shown.
The fix is quite simple and I'll create a PR asap.

**Comment by hanneskuettner** [comment]
I can definitely see cases where it might be intended to only have the delete button enabled, for example for a comment moderation system, where a moderator only has the permission to remove comments of a user, but not the ability to create comments in a users name. So I think this should still be separated and individually controllable through assigning the correct permissions.

**Comment by terbshaeusser** [comment]
Maybe I should have described my intentions: O2M and M2M fields both have this behavior.
If I set either O2M or M2M fields to readonly, the side bar is not opening anymore when I click on them. This is especially annoying for M2M since these can also contain additional fields beside the 2 referenced ids. If the connection table is hidden in the table view there is no possibility to look at these additional fields.
If we would make the delete button's visibility dependent on the visibility of the add buttons, it would be possible to prevent addition and deletion and the user can still click on the list item and see all the fields.

But if there is a use case for deletion only maybe we could add a setting whether the deletion button should be visible or not like the show add new, add existing buttons?

Anyhow, I'll rename the issue to M2M instead of O2M.

**Comment by hanneskuettner** [comment]
The behavior you are describing can be achieved by correctly configuring the permissions of the M2M junction table. 

If you set the permissions for the user such that they are only allowed to read the junction table entries but not create, update or delete them, neither the create, select nor delete buttons are shown, but the user can still click on an item to view the properties of the item and the junction table, see attached video.


https://github.com/user-attachments/assets/be28c927-78e4-40d8-94f2-b11f025ca67a

**Comment by terbshaeusser** [comment]
Thank you for your detailed answer. However, if I understand correctly the permissions do not solve my problem.

Basically I have 3 collections:
A has a M2M relation to B and the connection collection A_TO_B has additional fields beside the ids of A and B.
If I archive an entry of A, the entry should not be changeable anymore. If I set the M2M field in collection A with a condition to readonly, I cannot longer click on it, meaning that I cannot see the additional fields coming from A_TO_B.
Hiding the deletion button would have been a simple option to hide all buttons without setting the field to readonly and still be able to click on the field.

I think the main problem here is that a readonly M2M field is not clickable. Is there already an issue for that? I think i've seen one but I cannot find it anymore.

**Comment by hanneskuettner** [comment]
I see! I haven't seen an issue either, so feel free to create an improvement request for that! I just want to make sure that we don't accidentally introduce dependencies between create, update and delete, as there are very valid use cases to have all of them separated.

**Comment by hanneskuettner** [comment]
Seem like there might have been a regression at some point, since I found this PR making them clickable in the first place. https://github.com/directus/directus/pull/15824
