### ISSUE TITLE
Database issue with fresh install (MySQL 8.0.33)

### ISSUE THREAD

**Issue by maholick** [directus/directus#23281]
### Describe the Bug

I tried to upgrade my Directus 10.13.2 installation to 11.0.1 and got following error.
Then I tried to install it on a fresh new database with same result.

**Install and error log:**

Attaching to docker-directus.
docker-directus | [06:23:17.513] INFO: Initializing bootstrap...
docker-directus | [06:23:17.539] INFO: Installing Directus system tables...
docker-directus | [06:23:18.688] INFO: Running migrations...
docker-directus | [06:23:18.700] INFO: Applying Remove Collection Foreign Keys...
docker-directus | [06:23:18.815] INFO: Applying Remove System Relations...
docker-directus | [06:23:18.826] INFO: Applying Remove System Collections...
docker-directus | [06:23:18.843] INFO: Applying Remove System Fields...
docker-directus | [06:23:18.850] INFO: Applying Add Cascade System Relations...
docker-directus | [06:23:19.684] INFO: Applying Change Webhook URL Type...
docker-directus | [06:23:19.718] INFO: Applying Add Relations Sort Field...
docker-directus | [06:23:19.746] INFO: Applying Remove Locked Fields...
docker-directus | [06:23:19.775] INFO: Applying Webhooks Collections Text...
docker-directus | [06:23:19.821] INFO: Applying Add Refresh Interval...
docker-directus | [06:23:19.849] INFO: Applying Make Filesize Nullable...
docker-directus | [06:23:19.916] INFO: Applying Add Collections Accountability...
docker-directus | [06:23:19.938] INFO: Applying Remove Files Interface...
docker-directus | [06:23:19.945] INFO: Applying Rename Interfaces...
docker-directus | [06:23:19.993] INFO: Applying Restructure Relations...
docker-directus | [06:23:20.133] INFO: Applying Add Foreign Key Constraints...
docker-directus | [06:23:20.170] INFO: Applying Add System Fk Triggers...
docker-directus | [06:23:20.869] INFO: Applying Add Collections Icon Color...
docker-directus | [06:23:20.890] INFO: Applying Add Insights...
docker-directus | [06:23:21.050] INFO: Applying Add Deep Clone Config...
docker-directus | [06:23:21.073] INFO: Applying Change Filesize Bigint...
docker-directus | [06:23:21.147] INFO: Applying Add Conditions to Fields...
docker-directus | [06:23:21.175] INFO: Applying Add Default Folder...
docker-directus | [06:23:21.251] INFO: Applying Replace Groups...
docker-directus | [06:23:21.272] INFO: Applying Add Required to Fields...
docker-directus | [06:23:21.305] INFO: Applying Update Groups...
docker-directus | [06:23:21.313] INFO: Applying Change Image Metadata Structure...
docker-directus | [06:23:21.321] INFO: Applying Add Geometry Config...
docker-directus | [06:23:21.357] INFO: Applying Remove Limit Column...
docker-directus | [06:23:21.391] INFO: Applying Add Auth Provider...
docker-directus | [06:23:21.621] INFO: Applying Webhooks Collections Not Null...
docker-directus | [06:23:21.682] INFO: Applying Move Module Setup...
docker-directus | [06:23:21.740] INFO: Applying Webhooks URL Not Null...
docker-directus | [06:23:21.776] INFO: Applying Add Collection Organization...
docker-directus | [06:23:21.833] INFO: Applying Replace Fields Group...
docker-directus | [06:23:21.896] INFO: Applying Replace M2M Interface...
docker-directus | [06:23:21.901] INFO: Applying Rename Login Action...
docker-directus | [06:23:21.912] INFO: Applying Update Presets...
docker-directus | [06:23:21.950] INFO: Applying Add Auth Data...
docker-directus | [06:23:21.994] INFO: Applying Add Webhook Headers...
docker-directus | [06:23:22.010] INFO: Applying Set Unique to User Token...
docker-directus | [06:23:22.063] INFO: Applying Update Special Geometry...
docker-directus | [06:23:22.068] INFO: Applying Remove Collections Listing...
docker-directus | [06:23:22.098] INFO: Applying Add Notifications...
docker-directus | [06:23:22.268] INFO: Applying Add Shares...
docker-directus | [06:23:22.548] INFO: Applying Add Project Descriptor...
docker-directus | [06:23:22.577] INFO: Applying Remove Default Project Color...
docker-directus | [06:23:22.608] INFO: Applying Add Bookmark Icon and Color...
docker-directus | [06:23:22.652] INFO: Applying Add Translation Strings...
docker-directus | [06:23:22.676] INFO: Applying Rename Field Typecast Flags...
docker-directus | [06:23:22.681] INFO: Applying Add Field Validation...
docker-directus | [06:23:22.712] INFO: Applying Fix Typecast Flags...
docker-directus | [06:23:22.720] INFO: Applying Add Default Language...
docker-directus | [06:23:22.852] INFO: Applying Remove Default Value Panel Icon...
docker-directus | [06:23:22.872] INFO: Applying Add Flows...
docker-directus | [06:23:23.235] INFO: Applying Add Color to Insights Icon...
docker-directus | [06:23:23.260] INFO: Applying Drop Non Null From IP of Activity...
docker-directus | [06:23:23.302] INFO: Applying Drop Non Null From Sender of Notifications...
docker-directus | [06:23:23.348] INFO: Applying Rename Hook Trigger to Event...
docker-directus | [06:23:23.356] INFO: Applying Update Notifications Timestamp Column...
docker-directus | [06:23:23.387] INFO: Applying Add Custom Aspect Ratios...
docker-directus | [06:23:23.417] INFO: Applying Add Origin to Accountability...
docker-directus | [06:23:23.456] INFO: Applying Update Material Icons...
docker-directus | [06:23:23.502] INFO: Applying Add Preview Settings...
docker-directus | [06:23:23.533] INFO: Applying Migrate Translation Strings...
docker-directus | [06:23:23.576] INFO: Applying Require Shares Fields...
docker-directus | [06:23:23.776] INFO: Applying Add Content Versioning...
docker-directus | [06:23:23.976] INFO: Applying Themes...
docker-directus | [06:23:24.312] INFO: Applying Update CSV Fields to Text...
docker-directus | [06:23:24.317] INFO: Applying Update Panel Options...
docker-directus | [06:23:24.325] INFO: Applying Add Extensions...
docker-directus | [06:23:24.340] INFO: Applying Add Focalpoints...
docker-directus | [06:23:24.384] INFO: Applying Add Report URL Fields...
docker-directus | [06:23:24.414] INFO: Applying Marketplace...
docker-directus | [06:23:24.534] INFO: Applying Change Useragent Type...
docker-directus | [06:23:24.573] INFO: Applying Deprecate Webhooks...
docker-directus | [06:23:24.630] INFO: Applying Public Registration...
docker-directus | [06:23:24.707] INFO: Applying Add Session Window...
docker-directus | [06:23:24.725] INFO: Applying Add Tus Data...
docker-directus | [06:23:24.776] INFO: Applying Update Files Date Fields...
docker-directus | [06:23:24.856] INFO: Applying Permissions Policies...
docker-directus | Error: alter table `directus_permissions` modify  `policy` char(36) not null  - Cannot change column 'policy': used in a foreign key constraint 'directus_permissions_policy_foreign'
docker-directus |     at Packet.asError (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/packets/packet.js:728:17)
docker-directus |     at Query.execute (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/commands/command.js:29:26)
docker-directus |     at Connection.handlePacket (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/connection.js:481:34)
docker-directus |     at PacketParser.onPacket (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/connection.js:97:12)
docker-directus |     at PacketParser.executeStart (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/packet_parser.js:75:16)
docker-directus |     at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/connection.js:104:25)
docker-directus |     at Socket.emit (node:events:517:28)
docker-directus |     at addChunk (node:internal/streams/readable:368:12)
docker-directus |     at readableAddChunk (node:internal/streams/readable:341:9)
docker-directus |     at Readable.push (node:internal/streams/readable:278:10) {
docker-directus |   code: 'ER_FK_COLUMN_CANNOT_CHANGE',
docker-directus |   errno: 1832,
docker-directus |   sqlState: 'HY000',
docker-directus |   sqlMessage: "Cannot change column 'policy': used in a foreign key constraint 'directus_permissions_policy_foreign'",
docker-directus |   sql: 'alter table `directus_permissions` modify  `policy` char(36) not null '
docker-directus | }
docker-directus | [06:23:30.403] INFO: Skipping CLI extensions initialization due to outstanding migrations.
docker-directus | [06:23:30.414] INFO: Initializing bootstrap...
docker-directus | [06:23:30.435] INFO: Database already initialized, skipping install
docker-directus | [06:23:30.435] INFO: Running migrations...
docker-directus | [06:23:30.452] INFO: Applying Permissions Policies...
docker-directus | [06:23:30.473] INFO: Done
docker-directus | 2024-08-11T06:23:31: PM2 log: Launching in no daemon mode
docker-directus | 2024-08-11T06:23:31: PM2 log: App [directus:0] starting in -cluster mode-
docker-directus | 2024-08-11T06:23:34: PM2 log: App [directus:0] online
docker-directus | [06:23:36.577] WARN: Upload directory (/directus/uploads) is not read/writeable!
docker-directus | [06:23:36.834] INFO: Server started at http://0.0.0.0:8055

The instance is up and running, but I also can't login with the configured default user.

ADMIN_EMAIL="admin@xxx.de"
ADMIN_PASSWORD="directus"

The directus_users table (and also directus_permissions, directus_roles etc. - I assume they are emtpy on fresh install) are empty.

### To Reproduce

Setup a new instance with docker-compose and MySQL 8.0.33 or upgrade from 10.13.2.

### Directus Version

v11.0.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

MySQL 8.0.33

**Comment by maholick** [comment]
Just recognized #23234 which seems to be the same issue, with a different MySQL version.

**Comment by hanneskuettner** [comment]
Do you mind sharing your MySQL setup? I'm unable to reproduce this with the development MySQL docker setup. Do you have a docker setup you could share?

**Comment by maholick** [comment]
Thank you @hanneskuettner. It might be related to shared hosting of netcup in my case. I will try to export the config variables. Something specific I could look for?
![image](https://github.com/user-attachments/assets/3afa90b7-1e35-4a39-9d5e-30f17168007a)

**Comment by maholick** [comment]
I only got limited access and can't access the mysql config or logs. Here an export of the system and status variables.

[mysql_system_variables.txt](https://github.com/user-attachments/files/16575965/mysql_system_variables.txt)

I also tried the setup using a differend shared hosting service (Mittwald) with a different MySQL version. Same behaviour.

**Error:**
oeoo-test-directus | Error: alter table `directus_permissions` modify  `policy` char(36) not null  - Cannot change column 'policy': used in a foreign key constraint 'directus_permissions_policy_foreign'
oeoo-test-directus |     at Packet.asError (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/packets/packet.js:728:17)
oeoo-test-directus |     at Query.execute (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/commands/command.js:29:26)
oeoo-test-directus |     at Connection.handlePacket (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/connection.js:481:34)
oeoo-test-directus |     at PacketParser.onPacket (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/connection.js:97:12)
oeoo-test-directus |     at PacketParser.executeStart (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/packet_parser.js:75:16)
oeoo-test-directus |     at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/connection.js:104:25)
oeoo-test-directus |     at Socket.emit (node:events:517:28)
oeoo-test-directus |     at addChunk (node:internal/streams/readable:368:12)
oeoo-test-directus |     at readableAddChunk (node:internal/streams/readable:341:9)
oeoo-test-directus |     at Readable.push (node:internal/streams/readable:278:10) {
oeoo-test-directus |   code: 'ER_FK_COLUMN_CANNOT_CHANGE',
oeoo-test-directus |   errno: 1832,
oeoo-test-directus |   sqlState: 'HY000',
oeoo-test-directus |   sqlMessage: "Cannot change column 'policy': used in a foreign key constraint 'directus_permissions_policy_foreign'",
oeoo-test-directus |   sql: 'alter table `directus_permissions` modify  `policy` char(36) not null '
oeoo-test-directus | }


See system and status variables from Mittwald setup:
[mysql_system_variables_mittwald.txt](https://github.com/user-attachments/files/16576027/mysql_system_variables_mittwald.txt)


--

I tested also with a local MySQL database with default configuration within the Directus docker setup without any issues. 
Also upgrading from 10.13.x worked. 

As workaround I can switch to a dockerized mysql instance, but it was very convinient to use a free and managed MySQL database.

**Comment by gostelna** [comment]
We probably have the same issue. DB on AWS RDS: 8.0.mysql_aurora.3.05.2 and when trying to update from 10.13.2 to 11.0.1 we get the same error: 
`Error: alter table `directus_permissions` modify `policy` char(36) not null - Cannot change column 'policy': used in a foreign key constraint 'directus_permissions_policy_foreign'`

**Comment by hanneskuettner** [comment]
Does anyone impacted by this issue have the option to build Directus from source and can test to see if an upcoming PR solves the issue for you? I'm still having trouble reproducing this in any shape or form with a standard MySQL docker.

**Comment by hanneskuettner** [comment]
@Anthonyythomas can you share your MySQL setup? Are you using a dockerized MySQL instance? What version/flavor of MySQL?

**Comment by Anthonyythomas** [comment]
@hanneskuettner Thank you for your quick response
@gostelna and I we have the same issue

Here is my configuration:
Instance configuration
Instance type
Serverless v2
Minimum capacity
1 ACUs (2 GiB)
Maximum capacity
8 ACUs (16 GiB)


Configuration
DB instance ID
instance-1
Engine version
8.0.mysql_aurora.3.05.2
DB name
directus

**Comment by hanneskuettner** [comment]
I've just created PR #23327. If you have the possibility to run Directus from source and confirm that this works for you, that would be very much appreciated!

**Comment by fchavant-cl** [comment]
> I've just created PR #23327. If you have the possibility to run Directus from source and confirm that this works for you, that would be very much appreciated!

Building from source using that PR's branch indeed does fix the problem: the migration runs successfully.

**Comment by Anthonyythomas** [comment]
@hanneskuettner It seems to work locally, now we need to test it live because sometimes the behavior can be different. However, I appreciate the prompt response and the fix! 🤗

**Comment by hanneskuettner** [comment]
Very good to hear. We will have to do some additional testing to ensure that this does not break the migration for of the other database vendors we support. But I think we're on to something.

**Comment by Anthonyythomas** [comment]
@hanneskuettner I upgraded to 11.0.1 `pnpm add directus@latest -w` and ran this command line "pnpm directus database migrate:latest" but I still get this error, maybe I did things wrong...

`PS C:\Users\Anthony\Desktop\projects\test\directus> pnpm directus database migrate:latest
[17:40:46.690] INFO: Skipping CLI extensions initialization due to outstanding migrations.
[17:40:46.693] INFO: Running migrations...
[17:40:46.717] INFO: Applying Add Session Window...
[17:40:46.811] INFO: Applying Add Tus Data...
[17:40:46.934] INFO: Applying Update Files Date Fields...
[17:40:47.145] INFO: Applying Permissions Policies...
[17:40:48.118] ERROR: alter table `directus_permissions` modify  `policy` char(36) not null  - Cannot change column 'policy': used in a foreign key constraint 'directus_permissions_policy_foreign'
    err: {
      "type": "Error",
      "message": "alter table `directus_permissions` modify  `policy` char(36) not null  - Cannot change column 'policy': used in a foreign key constraint 'directus_permissions_policy_foreign'",
      "stack":
          Error: alter table `directus_permissions` modify  `policy` char(36) not null  - Cannot change column 'policy': used in a foreign key constraint 'directus_permissions_policy_foreign'
              at Packet.asError (C:\Users\Anthony\Desktop\projects\test\directus\node_modules\.pnpm\mysql2@3.10.0\node_modules\mysql2\lib\packets\packet.js:728:17)
              at Query.execute (C:\Users\Anthony\Desktop\projects\test\directus\node_modules\.pnpm\mysql2@3.10.0\node_modules\mysql2\lib\commands\command.js:29:26)
              at Connection.handlePacket (C:\Users\Anthony\Desktop\projects\test\directus\node_modules\.pnpm\mysql2@3.10.0\node_modules\mysql2\lib\connection.js:481:34)
              at PacketParser.onPacket (C:\Users\Anthony\Desktop\projects\test\directus\node_modules\.pnpm\mysql2@3.10.0\node_modules\mysql2\lib\connection.js:97:12)
              at PacketParser.executeStart (C:\Users\Anthony\Desktop\projects\test\directus\node_modules\.pnpm\mysql2@3.10.0\node_modules\mysql2\lib\packet_parser.js:75:16)
              at Socket.<anonymous> (C:\Users\Anthony\Desktop\projects\test\directus\node_modules\.pnpm\mysql2@3.10.0\node_modules\mysql2\lib\connection.js:104:25)
              at Socket.emit (node:events:514:28)
              at addChunk (node:internal/streams/readable:376:12)
              at readableAddChunk (node:internal/streams/readable:349:9)
              at Readable.push (node:internal/streams/readable:286:10)
      "code": "ER_FK_COLUMN_CANNOT_CHANGE",
      "errno": 1832,
      "sqlState": "HY000",
      "sqlMessage": "Cannot change column 'policy': used in a foreign key constraint 'directus_permissions_policy_foreign'",
      "sql": "alter table `directus_permissions` modify  `policy` char(36) not null "
    }`

**Comment by hanneskuettner** [comment]
Yeah, the fix is for v11.0.2 (which is released right now btw!) so running it with 11.0.1 is expected to fail. That's why I explicitly asked for people to build from source :)

**Comment by Anthonyythomas** [comment]
@hanneskuettner Lovely!!! Thank you very much if I can contribute on simple tickets I would be happy to help you :)

**Comment by hanneskuettner** [comment]
Definitely have a look at the open issues tagged with ["Good First Issue"](https://github.com/directus/directus/issues?q=is:open+is:issue+label:%22:star:+Good+First+Issue%22) are one that our team considers easy to pick up and get started with. PRs on those are always welcome!

**Comment by Anthonyythomas** [comment]
@hanneskuettner Is this error normal?

PS C:\Users\Anthony> docker pull directus/directus:11.0.2
Error response from daemon: manifest for directus/directus:11.0.2 not found: manifest unknown: manifest unknown

**Comment by hanneskuettner** [comment]
The docker image isn't available yet. The build typically take 20 minutes longer than the release in GitHub/npm.

Check https://hub.docker.com/r/directus/directus to see when it's available

**Comment by Anthonyythomas** [comment]
Everything works great in production 😍
Thank you!
