### ISSUE TITLE
Marketplace extensions not accessible

### ISSUE THREAD

**Issue by xfatboy** [directus/directus#23280]
### Describe the Bug

Fresh directus install - nothing special, just standard docker setup following the install guidelines.

Click on Marketplace and I can see the extensions listed, but any extension I click automatically generates an error 500 being reported from the registry,

Reported in console (while debugging):

`ERROR: Request failed with status code 500 Internal Server Error: GET https://registry.directus.io/extensions/1a74df86-166f-436c-a29d-ec4e2a5983b9
    err: {
      "type": "HTTPError",
      "message": "Request failed with status code 500 Internal Server Error: GET https://registry.directus.io/extensions/1a74df86-166f-436c-a29d-ec4e2a5983b9",
      "stack":
          HTTPError: Request failed with status code 500 Internal Server Error: GET https://registry.directus.io/extensions/1a74df86-166f-436c-a29d-ec4e2a5983b9
              at function_ (file:///home/xfatboy/lgcc-directus/node_modules/ky/distribution/core/Ky.js:28:29)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Ky._retry (file:///home/xfatboy/lgcc-directus/node_modules/ky/distribution/core/Ky.js:184:20)
              at async result.<computed> [as json] (file:///home/xfatboy/lgcc-directus/node_modules/ky/distribution/core/Ky.js:54:39)
              at async describe (file:///home/xfatboy/lgcc-directus/node_modules/@directus/extensions-registry/dist/index.js:153:20)
              at async file:///home/xfatboy/lgcc-directus/node_modules/@directus/api/dist/controllers/extensions.js:96:21
      "response": {},
      "request": {},
      "options": {
        "method": "GET",
        "headers": {},
        "hooks": {
          "beforeRequest": [],
          "beforeRetry": [],
          "beforeError": [],
          "afterResponse": []
        },
        "prefixUrl": "",
        "retry": {
          "limit": 2,
          "methods": [
            "get",
            "put",
            "head",
            "delete",
            "options",
            "trace"
          ],
          "statusCodes": [
            408,
            413,
            429,
            500,
            502,
            503,
            504
          ],
          "afterStatusCodes": [
            413,
            429,
            503
          ],
          "maxRetryAfter": null,
          "backoffLimit": null
        },
        "throwHttpErrors": true,
        "timeout": 10000,
        "signal": {},
        "duplex": "half"
      },
      "name": "HTTPError"
    }`

### To Reproduce

Do a fresh install.

Try to load any marketplace extension.

### Directus Version

11.0.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

mariadb 10.3.39

**Comment by hanneskuettner** [comment]
This is a known issue at the moment, a solution is being worked on, so it will hopefully be resolved after the weekend.

I'll keep this issue open tho, just so we can track the progress on this and everyone searching for the same problem.

**Comment by hanneskuettner** [comment]
Closing this, as it has been solved through a configuration change on our end.
