### ISSUE TITLE
Translations interface requests language collection with `direction` field, even if the field does not exist

### ISSUE THREAD

**Issue by hanneskuettner** [directus/directus#23299]
### Describe the Bug

The translations interface requests the `languages` collection (or configured equivalent) with the `direction` field, even if no `languageDirectionField` is configured in the translation interface. This is due to the interface defaulting to `direction` if no field is configured.

Before v11 this has not led to any problems, as field existence was less stringently checked for admin users

### To Reproduce

- Configure a translations field
- Remove the `direction` field from your `languages` collection
- Navigate to collection with translations field, see error, even as admin user

![Screenshot 2024-08-12 at 13 52 51](https://github.com/user-attachments/assets/dfde047d-e90b-4fcf-a82e-04396986a548)

### Directus Version

v11.0.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by roelvan** [comment]
Has this bug fix already been released? Or will this be in the next version (11.0.2)? Thanks.

**Comment by hanneskuettner** [comment]
It will be in the next version (11.0.2)
