### ISSUE TITLE
Digital Ocean 1 Click Install Issue

### ISSUE THREAD

**Issue by jessejamesrich** [directus/directus#2329]
Just a small note. I couldn't really figure this out. The Quick Start guide wasn't much use. First SSH in I was being stupid and didn't read the instructions because I'm stupid. Had to tease out that the default Port Number 3306 should be 22. Took me a while to figure it out. So just some small suggestions. **Quickstart Guide** more in-depth. Default port 22.

**Comment by rijkvanzanten** [comment]
Heya! What do you mean by `Had to tease out that the default Port Number 3306 should be 22` exactly? Port 3306 is MySQL which in safe mode doesn't have any incoming network requests attached. Port 22 is SSH. Do you mean you tried logging into the database externally and had to use SSH (on port 22) instead of 3306?

**Comment by jessejamesrich** [comment]
The default setting seems to be 3306. Traditionally I wouldn't use this because I'll always SSH tunnel in remotely, but assumed this would be what needed to be done since it's the initial install. So it took me some time to put together that the default value shouldn't be 3306 and should be 22. (unless I did it wrong - which is totally possible).

**Comment by rijkvanzanten** [comment]
I'm not entirely following.. What do you mean by "the default value"? The default value of what?

**Comment by jessejamesrich** [comment]
I'll go through the steps. I've just done this to try an reproduce.

1) Create droplet with SSH key. 
2) Login
3) # vi /root/.digitalocean_password
4) Project information (Admin email/Admin password) - attached image
5) Database Connection (default, default, default, password, default, readonly) - attached image

<img width="709" alt="Screen Shot 2019-04-05 at 8 45 45 AM" src="https://user-images.githubusercontent.com/13437954/55639964-7c563b80-577f-11e9-9a55-7781ad58e9c0.png">

<img width="712" alt="Screen Shot 2019-04-05 at 8 50 56 AM" src="https://user-images.githubusercontent.com/13437954/55640184-f686c000-577f-11e9-9ae2-405ee874e951.png">

Now, I figured I solved this by entering port 22 original as per my original feature request, but at this point I can't get the connection to work at all. No combination of information on this one click works. 

What am I doing wrong?

**Comment by rijkvanzanten** [comment]
Make sure to use the `directus` database user with the `directus` database user password coming from that `/root/.digitalocean_password` file

**Comment by jessejamesrich** [comment]
Ok, I'm gonna run through the entire process again. Should root not be able to connect using the root password?

**Comment by jessejamesrich** [comment]
Ok, so actually the issue wasn't the port default value in the setup, it was the user defaulting to root and not directus. Directus will connect (seemingly on both 22 and 3306?)

**Comment by rijkvanzanten** [comment]
I don't think Directus will be able to connect over 22 as that's not the / a mysql port..

I'll clear out the pre-filled database user, as it will be different for everyone (it's `directus` by default on DO one click, but `root` for people using `MAMP`, etc) so it forces the user to look up the correct user.

**Comment by rijkvanzanten** [comment]
Ref https://github.com/directus/app/commit/c5acf872d5a2fe046c0a8f628198491b8e2186e3

**Comment by jessejamesrich** [comment]
It is root as default on DO. Just spun up a new one to make sure I wasn't crazy. Also, you can use port 22. This is sort-of where the confusion laid with my initial testing.

**Comment by rijkvanzanten** [comment]
We already requested to have the marketplace quick start updated a little while ago to clarify, I'll nudge the folks over DO again to see if we can get this updated asap 🙂

**Comment by rijkvanzanten** [comment]
For others running into a similar problem: 
You want to use the `directus` user with the password in `/root/.digitalocean_password` connecting to the database on port `3306`.
