### ISSUE TITLE
Reload notifications after manual Flow-trigger

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#23305]
### Describe the Improvement

When a user manually triggers a flow, this can add a custom notification through the notifications operation. If the notification is added for the current user he'll only get notified in the browser once he navigates away from the page, as notifications are only fetched with each route change. 

As this ends in a non-optimal UX I'd suggest to fetch the new notifications directly after the manual flow-call has finished. This way it would be sure that the user get's the notification before he'd navigate away.

**Comment by Dominic-Marcelino** [comment]
Wanted to take a look into it, but having issues with flow in dev mode. Just created a normal notification flow and trigger it manually. Takes a while and then creates the flow-log:

```
{
  "name": "KnexTimeoutError",
  "message": "Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?"
}
```
Local dev-instance uses sqlite. Any idea what could be the issue?

**Comment by rijkvanzanten** [comment]
@Dominic-Marcelino That seems to indicate it's trying to write to SQLite while another transaction already has a lock on the file 🤔 

Mind sharing your flow setup so I can try reproducing on my end?

**Comment by Dominic-Marcelino** [comment]
@rijkvanzanten Seems to be independent of the flow as long as I include a notification operation and running on sqlite. Just switched the dev instance to pg and it works.
Transferred the original flow and operation entries from the sqlite database to be sure I haven't changed any config without noticing...
