### ISSUE TITLE
Persist opened detail in sidebar-detail-group

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#23304]
### Describe the Improvement

Directus stores the state of the sidebar in the local storage. This makes sure the sidebar-state stays the same between page-reloads.

For a better UX I suggest to also persist the currently expanded section. This is useful as if a user navigates through the page it feels wrong that the sections always open / close the same section (e.g flows)

https://github.com/directus/directus/blob/939423f2571437790f9419b4fe64badafe1e7459/app/src/views/private/components/sidebar-detail-group.vue#L8-L9

Siebar-state:
https://github.com/directus/directus/blob/939423f2571437790f9419b4fe64badafe1e7459/packages/stores/src/app.ts#L13-L14

**Comment by hanneskuettner** [comment]
I'm also happy to accept a PR for this improvement. It would need to take care of making sure the sections actually exist I think.
