### ISSUE TITLE
Cannot get a custom page extension via API

### ISSUE THREAD

**Issue by sitawit** [directus/directus#2330]
# Bug Report
Cannot get a custom page extension via API.

## Steps to Reproduce

1. Fresh install directus and setup normally. In this step, the admin page works fine.
2. Rename "_demo" to "demo", in \public\extensions\core\pages
3. Call GET /_/pages/demo (actually with static access token)

## Expected Behavior
I don't actually know but it should return some page? What is it actually intend for? I am trying to test it out but it isn't working.

## Actual Behavior
{
    "error": {
        "code": 1,
        "message": "Not Found"
    }
}

## Other Context & Screenshots

One thing that is very confuse to me is, the Page api is actually looks only in "public\extensions\core\pages" directory while there is another one in "public\extensions\custom\pages", judging from the routing setting in "\src\web.php".

And a possible cause is the way, this Page api loads the page is the same way with "endpoints" which is actually shouldn't because the page and the endpoints is not the same. So we may need a routing config in the "pages" folder? I can't see it in any document. So this ... is a bug?

## Technical Details

- Device: Desktop
- OS: Windows 10
- Web Server: Apache 2.4.38
- PHP Version: 7.2.15
- Database:  5.0.12-dev
- Install Method: cloned `master` branch

**Comment by rijkvanzanten** [comment]
A page extension is a part of the front-end that the application will dynamically load in. The API has a `pages` endpoint that will return an array of all the available extensions that the application in turn will download and use to render the pages.

> "public\extensions\core\pages" directory while there is another one in "public\extensions\custom\pages", judging from the routing setting in "\src\web.php".

Where did you see this? That doesn't sound right..

**Comment by sitawit** [comment]
Here it is:
https://github.com/directus/directus/blob/a12970d7013f53ac29fc747e89aab2c43682a37a/src/web.php#L201
I see that the function is looking only from "core/page", so what is the actual reason for "custom/page"?

It seems a page is only for use in the Front-end but there is a document here.
https://docs.directus.io/api/reference.html#get-page
Which suggest you can get the page from API too and that is the reason I'm open a ticket. But when you looking at the code, it is not supposed to be able to load from API. This is where I'm confused.

After I read the document, I think I can create a custom page and call it via API and you get an HTML as a result? So I can use it on a client website without having to create another piece of code on the client website.

**Comment by rijkvanzanten** [comment]
That looks strange 🤔 I just tried custom interfaces the other day, that seems to have the `core` one hardcoded similarly. I think the API might extract that somewhere else..? I'll verify that

> After I read the document, I think I can create a custom page and call it via API and you get an HTML as a result? So I can use it on a client website without having to create another piece of code on the client website.

No, it will return a JSON object outlining the details of the page extension for use in the application. The application will then in turn fetch the JS files required to render the page.

**Comment by sitawit** [comment]
> That looks strange 🤔 I just tried custom interfaces the other day, that seems to have the `core` one hardcoded similarly. I think the API might extract that somewhere else..? I'll verify that
> 
Cool, thanks.
> > After I read the document, I think I can create a custom page and call it via API and you get an HTML as a result? So I can use it on a client website without having to create another piece of code on the client website.
> 
> No, it will return a JSON object outlining the details of the page extension for use in the application. The application will then in turn fetch the JS files required to render the page.
Ah.. ok, but I have a problem that it says "not found" which is the actual problem of this issue. I'll look at the code again to see what could be the cause. I could make a mistake but I'm not so sure where.

**Comment by rijkvanzanten** [comment]
Ah gotcha. It seems like that endpoint was never implemented. That's okay actually, as the main `/pages` interface returns the same data, and the application doesn't rely on getting the individual info files through this method. I've updated the docs to reflect this.
