### ISSUE TITLE
Upgrade to 11.0.1 doesn't show a module extension anymore

### ISSUE THREAD

**Issue by keesvanbemmel** [directus/directus#23307]
### Describe the Bug

We are using a marketplace extension: https://github.com/maltejur/directus-extension-generate-types

This worked fine in 10x but after upgrading to 11.0.1 the extension is not visible anymore in the Settings page under modules and it also doesn't show up in the sidebar.

The weird thing is: the response of the /settings call the settings page makes, clearly shows this:
```
{
                "type": "module",
                "id": "generate-types",
                "enabled"
}
```

So the extension is loaded by the backend. Just doesn't show up in the app anymore.

I think [this commit](https://github.com/directus/directus/commit/0c092deedc6706d515e2ae8b2c3e6cd8f5c5c8cc#diff-0d3b8e02eafe8d22cc04b2d5596ee2a1363f3570e61765fa9e0e9ebfb2a5d38e) broke this functionality in the system-modules.vue file. Cant' be certain though.

### To Reproduce

- Install the module extension in 10.x
- Notice the generate-types extension listed in the modules bar in the settings
- Enable it
- reload page
- see extension in sidebar
- upgrade to 11.x
- extension is gone in sidebar and in settings list

### Directus Version

11.0.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PG15

**Comment by hanneskuettner** [comment]
The problem is that the `admin_access` property moved from the user role to the user itself, so the check in the modules pre-register check fails. Please contact the module author for them to update their extensions (in a backwards compatible) way to v11.

**Comment by keesvanbemmel** [comment]
Thanks!
