### ISSUE TITLE
Disable tinymce toolbar if no elements are selected

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#23309]
### Describe the Improvement

In case you select no elements for the tinymce toolbar (makes sense if it's readonly) the toolbar is still rendered.
Tinymce allows to disable the toolbar completely by passing `false` as a value.

I'd suggest to completely hide the toolbar in case no elements are selected. Haven't tested it yet, but assume we'd just need to use `false` in case the `toolbarString` is empty

https://github.com/directus/directus/blob/ce626ab7ec625f368d1eb45bd470dede6ef4e860/app/src/interfaces/input-rich-text-html/input-rich-text-html.vue#L203

https://www.tiny.cloud/docs/tinymce/latest/toolbar-configuration-options/#disabling-the-toolbar

**Comment by hanneskuettner** [comment]
Happy to accept a PR for this tiny improvement! 👍
