### ISSUE TITLE
Dynamic variables in permissions get cached

### ISSUE THREAD

**Issue by hanneskuettner** [directus/directus#23319]
### Describe the Bug

The dynamic variable insertion takes place before the permission are stored in the cache. As such the cached permissions contain fixed values where there should be dynamic placeholders.

### To Reproduce

- Create a permission with `$NOW` or `$CURRENT_USER.some_field` and see that the permissions are not updated when the field changes.

### Directus Version

v11.0.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by u12206050** [comment]
Was just about too open this issue . At first I thought "surely only the permissions with the dynamic variable placeholders get cached" but yes we see the same issue where we are updating the `active_tenant` field on a user, but his permissions don't seem to reflect that.

**Comment by u12206050** [comment]
Would be nice to be able to add additional scopes to the caching of permissions, then we could add the tenant field or other changes that could affect dynamic values?
