### ISSUE TITLE
Support for Graph-style schema

### ISSUE THREAD

**Issue by creactiviti** [directus/directus#2331]
# Feature Request

Support for a Graph-style schema

## What problem does this feature solve?

I'd like to be able to use Directus to update content that does not reside in a typical schema where each table is a content type. 

Here is my schema

```
create table node (
  id          varchar(64) primary key,
  node_type   varchar(64) not null,
  created_at  timestamp not null default current_timestamp,
  modified_at timestamp,
  properties  jsonb not null,
  deleted     boolean not null default false
);

create table edge (
  id           varchar(64) primary key,
  edge_type    varchar(64) not null,
  created_at   timestamp not null default current_timestamp,
  modified_at  timestamp,
  from_node_id varchar(64) not null references node (id),
  to_node_id   varchar(64) not null references node (id),
  properties   jsonb not null,
  deleted      boolean not null default false
);
```

## How do you think this should be implemented?

REST API database adapter.

## Would you be willing to work on this?

Possibily.

**Comment by benhaynes** [comment]
I'm certainly not technical enough to properly respond to this request, but....

Why wouldn't Directus support this schema now? It seems like it's two collections, each with a primary key, some timestamp fields, a status field (`deleted`), a JSON field using our JSON interface or a custom interface to be more friendly (`properties`), and some M2O/O2M relational fields (from/to node). All of this works out of the box with Directus.

I would assume that you're more interested in the GUI (App) presentation of this data, or the API output. Both of those are extensible. 

So for the App you would likely want a custom Layout extension. The Layout determines how you see the data... like a table, cards, or calendar. In this case you could map/show these nodes in a appropriate visual way.

For the API, you can write a custom API endpoint or add a custom API response filter to tailor the output to these Graph-schema needs.

Maybe I'm totally misunderstanding your request... but it all seems like it fits within the relational database model and would be optimized with extensions.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
