### ISSUE TITLE
EMAIL_FROM is set but I receive mails without sender

### ISSUE THREAD

**Issue by twoends** [directus/directus#23320]
### Describe the Bug

This is my configuration:
```
      EMAIL_VERIFY_SETUP: "true"
      EMAIL_FROM: "noreply@xxx.it"
      EMAIL_TRANSPORT: "smtp"
      EMAIL_SMTP_POOL: "true"
      EMAIL_SMTP_HOST: "smtps.aruba.it"
      EMAIL_SMTP_NAME: "smtps.aruba.it"
      EMAIL_SMTP_PORT: "465"
      EMAIL_SMTP_USER: "noreply@xxx.it"
      EMAIL_SMTP_PASSWORD: "xxx"
      EMAIL_SMTP_SECURE: "true"
      EMAIL_SMTP_IGNORE_TLS: "false"
```

I also tried using non-ssl connection with the same result and even the EMAIL_FROM format suggested in another issue ("Company" \<noreply@xxx.it\>). I receive the email but this is how it looks:

![image](https://github.com/user-attachments/assets/2aa07316-e0d3-4a91-ad6a-53dd806cc593)
(no sender)

![Screenshot 2024-08-13 alle 13 08 32](https://github.com/user-attachments/assets/751ee4d5-b562-4d22-95f3-ccb72f7c4be7)

### To Reproduce

use the same configuration i suppose

### Directus Version

v10.11.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by twoends** [comment]
Sending the email from the provider webmail works just fine:
![Screenshot 2024-08-13 alle 15 05 21](https://github.com/user-attachments/assets/821eb32f-abf0-4082-b411-e2d0ea2bcd75)

**Comment by rijkvanzanten** [comment]
While I'm not familiar with aruba.it, I'm 99% sure it's a restriction of aruba as a hosting provider. A lot of email providers will prevent you from setting an email_from address that's not directly registered against the smtp provider to combat spam.

Given that you can't reproduce it using `webmail` and that I'm not able to reproduce it through Sendgrid and AWS SES leaves me to believe the solution lies with aruba.it instead. Thanks!

**Comment by twoends** [comment]
After further investigation I found there is an actual bug. Apparently I was in the extremely unfortunate situation of having the Directus project called **Re:Anime**. This name gets prepended to the email address while sending the mails from directus and this is what happened in various scenarios:

1. Sending email from project called Re:Anime, looking in the .eml I find `From: Re:Anime <xxx@xxx.it>;`, unknown sender in my mail client
2. Sending email from provider webmail with mail named Re:Anime, looking in the .eml I find `From: "Re:Anime" <noreply@reanime.it>`, with name between double quotes and correctly displayed by my mail client
3. Sending email from project called Re Anime, looking in the .eml I find `From: Re Anime <noreply@reanime.it>`, correctly displayed by my mail client

**Comment by rijkvanzanten** [comment]
Thanks for the extra info! I see you've already created a new issue about the same thing so we'll continue this thread there :
