### ISSUE TITLE
App crash with datetime field

### ISSUE THREAD

**Issue by IbyG** [directus/directus#23331]
### Describe the Bug

When adding a datetime field and uncheck the 'Use 24-Hour Format' then change the field type to 'Date' the app stop working and crashes requiring me to reload the page.

### To Reproduce

1. Log into directus 
2. Go to data model and edit a collection
3. Create a Datetime field.
4. uncheck the field 'Use 24-hour Format' 
5. Change the Type to 'Date'

The crash should happen here. 
The page freezes and you cannot do anything until you reload the page. 

### Directus Version

11.0.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 16

**Comment by rijkvanzanten** [comment]
Strange! Sounds like an infinite loop somewhere.
