### ISSUE TITLE
403 error for M2A related fields, in v11+

### ISSUE THREAD

**Issue by arladmin** [directus/directus#23338]
### Describe the Bug

After upgrading from `v10.13.2` to `v11.0.1`, requests with `fields=*,blocks.item:block_richtext,blocks.item:block_gallery` now result in

```
{
    "errors": [
        {
            "message": "You don't have permission to access collection \"block_columns\" or it does not exist. Queried in \"blocks.item:block_columns\".",
            "extensions": {
                "reason": "You don't have permission to access collection \"block_columns\" or it does not exist. Queried in \"blocks.item:block_columns\".",
                "code": "FORBIDDEN"
            }
        }
    ]
}
```

![image](https://github.com/user-attachments/assets/9c07a5a1-62d6-413c-86f5-5ce8644c49da)

---

Why?

### To Reproduce

^

### Directus Version

v11.0.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Pg

**Comment by hanneskuettner** [comment]
I can reproduce this, working on a fix now :)
