### ISSUE TITLE
Selection interfaces: misleading notice in case of no choices

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#23344]
### Describe the Improvement

Selection interfaces currently always print a warning `Choices configured incorrectly ` if not choice exists. The message doesn't fit in case it's intended to have no global choices. 

**Example:**
You add choices for some cases via conditions. In all other cases there simply shouldn't be any choice.

**Suggested solution**
The easiest would be to replace the text with something like "No choices available".

Optionally this could also be conditional: If there's choices, but not for the current case, display "No choices available". If there's no choice at all (no global and no conditional for other cases) display the current warning.

**Interfaces:**
https://github.com/search?q=repo%3Adirectus%2Fdirectus+choices_option_configured_incorrectly+language%3AVue&type=code&l=Vue

**Comment by hanneskuettner** [comment]
This seems to be related to https://github.com/directus/directus/issues/21972 and has been fixed for one of the interfaces here https://github.com/directus/directus/pull/23092

**Comment by SP12893678** [comment]
Oh, in #23092, just fix the select-dropdown issue.
We also have select-multiple-dropdown, select-radio, select-multiple-checkbox interfaces need to fixed it.
I could help to work on this.
