### ISSUE TITLE
Flows Logs Loading Very Slow

### ISSUE THREAD

**Issue by dataheadless** [directus/directus#23349]
### Describe the Bug

Logs on flows are loading after 20 seconds (10 seconds to load the numbers on the log and rest to load the actual), don't rest of the system is working well only logs are lagging

### To Reproduce

Go to flows, look for logs

### Directus Version

v11.RC

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL

**Comment by rijkvanzanten** [comment]
This is most likely due to the logs table being very large. There's a separate in-flight issue to resolve that, so I'll close this as a duplicate. Thanks! 

Ref https://github.com/directus/directus/issues/23166
