### ISSUE TITLE
Getting Service Unavailable Error

### ISSUE THREAD

**Issue by dataheadless** [directus/directus#23354]
### Describe the Bug

Regularly getting service unavailable errors in directus 11 RC

![image](https://github.com/user-attachments/assets/dd09ccb5-73d3-4b14-928b-2f4c15a62671)

### To Reproduce

- Happens often in Flows

### Directus Version

v11.RC

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
Is that something new you're seeing in v11? What are the specs of the machine you're running the instance on? Are the flows resource intensive? The under pressure happens if the machine you're running Directus on sees a lot of CPU utilization.

**Comment by dataheadless** [comment]
> Is that something new you're seeing in v11? What are the specs of the machine you're running the instance on? Are the flows resource intensive? The under pressure happens if the machine you're running Directus on sees a lot of CPU utilization.

i am using Cloud Run instance, attaching metrics, that's happening after i upgraded from 9.x to 11.RC

![image](https://github.com/user-attachments/assets/af559a15-e289-4f5d-af2d-8857af679747)
![image](https://github.com/user-attachments/assets/08621c6e-c0f5-4627-922e-93e10064cc91)
![image](https://github.com/user-attachments/assets/fdb0b2e5-3a40-4720-82c4-bedd59a3db0c)

App is not Live yet so we don't have much load on this server. CPU is allocated on request

**Comment by dataheadless** [comment]
I don't think flows are doing that much work, just two steps one is webook and other is API call, i noticed logs are not loading for flows for almost 10 seconds to show the number of logs and another 8 seconds to load those, it was quite a quick before
