### ISSUE TITLE
Creating a user without selecting status creates inaccessible user

### ISSUE THREAD

**Issue by thepurpleblob** [directus/directus#2335]
# Bug Report

## Steps to Reproduce

Go to User directory > Creating item
Fill in all the fields but do NOT select a status option at the top

## Expected Behavior

The new user should appear in the list of users

## Actual Behavior

No user appears

## Other Context & Screenshots

If you check the database table, the user is there with a status of 'raf'. However, this user seems completely inaccessible through the UI

**Comment by rijkvanzanten** [comment]
This is a duplicate of https://github.com/directus/app/issues/1382
