### ISSUE TITLE
Set default markdown interface mode (or dependant on user access)

### ISSUE THREAD

**Issue by Eggwise** [directus/directus#23352]
### Describe the Improvement

Example:

We have made a collection called "Document". It has a title and "content".
Some users can only see the fields and not edit them.  Ofcourse i want to show them the rendered markdown in this case and not the "edit" version of the markdown.

But the markdown interface is always put on "edit" mode. Even when a user doesn't have edit access.
![image](https://github.com/user-attachments/assets/0429644b-2e38-46da-b02d-c1f55d613807)

It would be nice if you could configure the default selected mode. Or maybe put it to read mode if the user only has read access to the field and not show "edit" at all (would actually make sense).

**Comment by paescuj** [comment]
Absolutely agree that it makes sense to present the interface in "preview" mode when it's a read-only field.
However, not so sure about making the mode configurable. I wonder about the actual benefit of this is and I'm afraid it could be even a bit confusing for users if the initial mode is "preview". As far as I know, we do not offer similar options in other interfaces either.

**Comment by Eggwise** [comment]
Well, if you make the configuration optionable, so nullable, or put it on edit by default it is not confusing right.
Also if its configurable in the interface it can be configured based on **conditions**, so for example: if the field has a value make it "preview". Without this option in the interface this is not possible at all.

a.t.m every user always has to click preview before he can see the markdown, even if there is already markdown to be rendered. This is a big bottleneck when your application just wants to show rendered markdown.

@paescuj 

I mean these conditions (in the field editor)
<img width="766" alt="image" src="https://github.com/user-attachments/assets/cd9ca116-d52d-40f1-b7ca-ed1544ef0a1b">

**Comment by hanneskuettner** [comment]
> As far as I know, we do not offer similar options in other interfaces either.
What are other interfaces that have this split view mode possibility anyways? WYSIWYG just renders everything as it appears, same with the block editor 🤔 =

**Comment by Eggwise** [comment]
Thank you for your support guys. Keep up the good work! @rijkvanzanten @hanneskuettner
