### ISSUE TITLE
Is it possible to use the API without authentication (in v7)??

### ISSUE THREAD

**Issue by thepurpleblob** [directus/directus#2336]
I see this similar question for D6, https://github.com/directus/directus/issues/1129

However, I can no longer find a screen with a similar UI.

For using Directus behind a straightforward CMS, what's the 'approved' way of accessing data where authentication is not required. 

Or am I completely missing something?

**Comment by rijkvanzanten** [comment]
If you head over to settings > roles & permissions there is a Public role you can use to control what parts of the data should be publicly accessible 😄

**Comment by thepurpleblob** [comment]
Great - thanks :-D
