### ISSUE TITLE
Creating a new file in Directus flows with data blob from previous operation

### ISSUE THREAD

**Issue by JSDA123** [directus/directus#23361]
### Describe the Request

First: apologies if this question is posted in the wrong section, it seemingly impossible to verify a new Discord account so cannot ask for help there.

I have a Directus flow that uses a webhook to generate a pdf from an external api, and it returns the pdf as a blob available as {{ $last.data }}.

Following the API Reference at https://docs.directus.io/reference/files.html, I have an Authorization header (that works), and another header "Content-Type: multipart/form-data; boundary=boundary".

My request body looks like this:

```
--boundary
Content-Disposition: form-data; name="file"; filename="example.pdf"
Content-Type: application/pdf

{{ $last.data }}

--boundary
```

However the flow returns the following error:

```
{
  "status": 500,
  "statusText": "Internal Server Error",
  "headers": {
    "server": "openresty",
    "date": "Wed, 14 Aug 2024 17:55:59 GMT",
    "content-type": "application/json; charset=utf-8",
    "content-length": "95",
    "connection": "close",
    "content-security-policy": "script-src 'self' 'unsafe-eval';worker-src 'self' blob:;child-src 'self' blob:;img-src 'self' data: blob: https://raw.githubusercontent.com https://avatars.githubusercontent.com;media-src 'self';connect-src 'self' https://*;default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';object-src 'none';script-src-attr 'none';style-src 'self' https: 'unsafe-inline'",
    "x-powered-by": "Directus",
    "etag": "W/\"5f-yG67qE+4k4w0xWzhdsoI68szXyo\""
  },
  "data": {
    "errors": [
      {
        "message": "Unexpected end of form",
        "extensions": {
          "code": "INTERNAL_SERVER_ERROR"
        }
      }
    ]
  }
}
```

Can the documentation be updated to clarify what must be done to create files within a flow from payload data in a previous operation?

### Maintenance Strategy

I'm really just asking for help, but if maintainers agree this could be added to the documentation it may not require frequent maintenance as the API specification is presumed to be stable.

**Comment by Tasztalos69** [comment]
I'm also experiencing this error.

**Comment by rijkvanzanten** [comment]
Heya! Flows currently don't support file binary contents, so this is not possible at the moment. Feel free to [open a new feature request](https://github.com/directus/directus/discussions/new?category=draft-feature-requests) so this can hopefully be supported in the future 🚀

**Comment by JSDA123** [comment]
Thank you for the feedback. As suggested, I created a feature request:  https://github.com/directus/directus/discussions/23555
