### ISSUE TITLE
Replace jboss/keycloak with quay.io/keycloak/keycloak

### ISSUE THREAD

**Issue by EdwardLi-coder** [directus/directus#23367]
### Describe the Bug

I'm using an M1 Mac to run docker-compose.yml. However, it failed on jboss/keycloak because Keycloak now uses quay.io/keycloak/keycloak. The environment variables in the docker-compose.yml file need to be updated.

I can submit a PR to resolve this issue if team members think it needs to be updated.

### To Reproduce

Run : docker-compose.yml up -d

### Directus Version

v11.0.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
Just as an FYI, the docker compose in this repository is used for development (of Directus) only, and not for general production use case. They are just provide a common set of containers that we, the developers working on Directus, can spin up to test the integrations with various DBs/services.

That being that, if you want to improve the experience for developing Directus, you're more than welcome to open a PR.

**Comment by EdwardLi-coder** [comment]
> Just as an FYI, the docker compose in this repository is used for development (of Directus) only, and not for general production use case. They are just provide a common set of containers that we, the developers working on Directus, can spin up to test the integrations with various DBs/services.
> 
> That being that, if you want to improve the experience for developing Directus, you're more than welcome to open a PR.

It's used for development only. Direcuts is open-source and anyone can contribute. We could make contributing easier.

**Comment by hanneskuettner** [comment]
Got it! Just wanted to make sure this isn't accidentally used as a template for usage in a production environment, as that isn't the target audience of that file.

Seems like keycloak migrated to quay.io a couple of years ago, and also mention this image in their official getting started guide. So a PR for making that change would be super welcome!

https://www.keycloak.org/getting-started/getting-started-docker
