### ISSUE TITLE
Wrong permissions typing in SDK

### ISSUE THREAD

**Issue by EdouardDem** [directus/directus#23375]
### Describe the Bug

`DirectusPermission` should now have a `policy` property, but it still have `role`.

https://github.com/directus/directus/blob/66b1f63d7562d6c02433c378e5c15543d0682863/sdk/src/schema/permission.ts#L9

Should be 

```typescript
{
  // ...
  policy: DirectusPolicy<Schema> | string | null;
  // ...
}
```

### To Reproduce

Import `DirectusPermission` from `@directus/sdk`.

### Directus Version

v11.0.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
Good catch! Mind opening a quick PR for that one?

**Comment by EdouardDem** [comment]
It's done.
