### ISSUE TITLE
Default value 0 changed to null on schema apply/snapshot

### ISSUE THREAD

**Issue by u12206050** [directus/directus#23379]
### Describe the Bug

We were wondering why the default values weren't set on out total_qty column, and found that a recent schema apply changed the `default_value` from 0 to null. I believe there is probably some logic testing and since 0 is falsy, it sets the default to null instead of `0`

![Screenshot 2024-08-16 at 13 10 26](https://github.com/user-attachments/assets/f3e39aa1-3013-4c5e-9414-14d49b7aa3f8)

### To Reproduce

Create an integer column and set the default to 0. Also, set is_nullable to false.
Run a schema snapshot
Check column, correct
Run schema apply
Check column, wrong
Run a schema snapshot
Check column, wrong

### Directus Version

v11 , v10

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

mysql 8

**Comment by hanneskuettner** [comment]
Could be related to https://github.com/directus/directus/pull/23151?
