### ISSUE TITLE
"Webhook/Request url" in flow url can not request two-way mtls api?

### ISSUE THREAD

**Issue by liuzz99** [directus/directus#23371]
### Describe the Bug

I am trying to create a new flow, and at one point, I need to request an API on a gateway, but the gateway must use MTLS to make the request.
I am unable to upload certificates and keys in the "webhook/request url", nor can I read certificates and keys from environment variables.

### To Reproduce

"Webhook/Request url" in flow url can not request two-way mtls api. Is there a way for me to use a weekly book to request the MTLS API?

### Directus Version

v10.13.1

### Hosting Strategy

Self-Hosted (Custom)

### Database

PostgreSQL

**Comment by paescuj** [comment]
Thanks for opening the issue! However this concern should be submitted as a feature request, so do kindly open a [new feature request](https://github.com/directus/directus/discussions/new?category=feature-requests) instead. I'll proceed to close this issue, thanks again!
