### ISSUE TITLE
WYSIWYG editor does not appear

### ISSUE THREAD

**Issue by thepurpleblob** [directus/directus#2338]
# Bug Report

## Steps to Reproduce

1. Created a new collection 
2. Added a field of the WYSIWYG type 
3. Added content into the new collection

## Expected Behavior

Some sort of WYSIWYG editor

## Actual Behavior

Just a plane text box. 

## Other Context & Screenshots

I'm guessing I'm missing something, but couldn't track it down in the docs

**Comment by thepurpleblob** [comment]
Realised it is working - just expected a toolbar.

**Comment by srsgores** [comment]
Also having this.  Please advise on any pending fixes

**Comment by Nitwel** [comment]
To have a toolbar, you have to use the WYSIWYG Full field.
