### ISSUE TITLE
"Create Item" pre-filled when used from Bookmark page

### ISSUE THREAD

**Issue by edobez** [directus/directus#23396]
### Describe the Improvement

Pre-fill the fields when creating a new item from a bookmark page, using information from the applied filters.
Fall back to cleared new item if it's not possible to apply the pre-filling, which can happen if the filter was accepting multiple values.

### Example
Bookmark page is created with a filter selecting items with field "foo=true". Then whenever I create an item using the button from within the bookmark page, the item will be pre-filled with that filter setting.

**Comment by rijkvanzanten** [comment]
Closing this in favor of open feature request https://github.com/directus/directus/discussions/23056
