### ISSUE TITLE
Server crashed after trying to access deleted file

### ISSUE THREAD

**Issue by huzaifahj** [directus/directus#23415]
### Describe the Bug

A file was deleted and then an attempt was made to retrieve the file again. This caused the server to crash.

```
Error: ENOENT: no such file or directory, open '/directus/uploads/880e5611-c29f-4b44-8cc6-d867557d2a39__7abd30a2f63f675625d6888e2ed9d65992751e3c.avif'
[15:50:19.927] ERROR: ENOENT: no such file or directory, stat '/directus/uploads/880e5611-c29f-4b44-8cc6-d867557d2a39__7abd30a2f63f675625d6888e2ed9d65992751e3c.avif'
    err: {
      "type": "Error",
      "message": "ENOENT: no such file or directory, stat '/directus/uploads/880e5611-c29f-4b44-8cc6-d867557d2a39__7abd30a2f63f675625d6888e2ed9d65992751e3c.avif'",
      "stack":
          Error: ENOENT: no such file or directory, stat '/directus/uploads/880e5611-c29f-4b44-8cc6-d867557d2a39__7abd30a2f63f675625d6888e2ed9d65992751e3c.avif'
      "errno": -2,
      "code": "ENOENT",
      "syscall": "stat",
      "path": "/directus/uploads/880e5611-c29f-4b44-8cc6-d867557d2a39__7abd30a2f63f675625d6888e2ed9d65992751e3c.avif"
    }
```

### To Reproduce

Delete file and attempt to access deleted files.

Expected behaviour: error sent to client without crashing Docker server.

### Directus Version

Latest

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL Latest

**Comment by hanneskuettner** [comment]
Does the container actually crash? Or does the endpoint just return a 500 error and the Directus instance continues to respond to other requests?

**Comment by huzaifahj** [comment]
The Directus container crashes and the user sees a 502 error (if NGINX configured)

**Comment by hanneskuettner** [comment]
I'm unable to reproduce this with the standard Docker image we provide.

Do you have anything configured different from the default values for file storage? 
Do you have any caching setup?

When you say deleting a file causes the issue, what are you deleting? The file through Directus or the underlying file on the file system? I'm unable to reproduce this with either method.

When you're saying latest version, you are on 11.0.2, correct?

**Comment by JSDA123** [comment]
I have also experienced this issue when deleting all the images in a folder using the data studio.  In my case, they were newly uploaded images via a webhook, and so thumbnails were maybe still being generated as I clicked 'select all' and 'delete'.   v11.02
