### ISSUE TITLE
Prevent entering non valid default data to JSON fields

### ISSUE THREAD

**Issue by LevelUpGit** [directus/directus#23424]
### Describe the Improvement

Prevent entering non valid default data to JSON fields, i just happened to add custom field to users, and it prevented me form logging in.

**Comment by LevelUpGit** [comment]
I have created a bug raport https://github.com/directus/directus/issues/23426

**Comment by paescuj** [comment]
> I have created a bug raport #23426

Perfect, thank you! I'm closing this issue in favor of #23426 👍
