### ISSUE TITLE
Unexpected error in content page

### ISSUE THREAD

**Issue by shiing** [directus/directus#23438]
### Describe the Bug

![截圖 2024-08-21 下午8 14 38](https://github.com/user-attachments/assets/09c2abfa-a579-4494-bef0-6e9bb671e0d1)
Recently we didn't do any change. And it shows unexpected error in content page. Please see attached image

It shows 403 no permission error. Due to article.thumbnail. We don't article.thumbnail for a very long time. Also my account is admin account. I should have enough permission to do any action. Therefore I guess it's a system error, not the permission issue

Please kindly suggest what should I do to address this issue. Thanks

Ryan

### To Reproduce

Navigate to a specific content page

### Directus Version

v11.0.2

### Hosting Strategy

Directus Cloud

**Comment by hanneskuettner** [comment]
Can you see what query is issues to show load the content for the collection page?

What happens if you reset the page preferences?

**Comment by shiing** [comment]
Thanks for your reply. Here are more details regarding my error


The default layout is `Table`, it will show this error
<img width="1246" alt="截圖 2024-08-22 下午7 28 21" src="https://github.com/user-attachments/assets/989f737e-694d-4a20-8006-951c783a1df8">

Here is the curl. Please note I remove some sensitive information from the curl
`curl '{DIRECTUS_DOMAIN}/items/article_section?limit=25&fields\[\]=article.%27$thumbnail%27&fields\[\]=article.title&fields\[\]=article.id&fields\[\]=header_number&fields\[\]=status&fields\[\]=title&fields\[\]=id&sort\[\]=header_number&page=1&filter\[status\]\[_neq\]=deleted' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9,zh-TW;q=0.8,zh;q=0.7' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: 
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"'`

If I change the layout to `Kaban`, I can view the listing
<img width="1246" alt="截圖 2024-08-22 下午6 07 14" src="https://github.com/user-attachments/assets/7fd02530-37b6-4f97-aabe-f8e8017fcd10">

However still got the error after clicking a specific object
<img width="1364" alt="截圖 2024-08-22 下午6 08 01" src="https://github.com/user-attachments/assets/6b0f82dc-0ec3-4934-8654-a1a525e4af79">

Here is the curl. Please note I remove some sensitive information from the curl
`curl '{DIRECTUS_DOMAIN}/items/article/2?fields\[\]=%27$thumbnail%27&fields\[\]=title&fields\[\]=id' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9,zh-TW;q=0.8,zh;q=0.7' \
  -H 'Connection: keep-alive' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"'`

**Comment by hanneskuettner** [comment]
We are currently investigating this issue. Could you reach out to me at hannes[at]directus.io and let me know your Cloud project slug, so we can identify possible causes?

Right now we are thinking this might have been introduced a while ago when migrating from v8 to v9, but hasn't been caught until the recent changes to the permissions system with v11.

**Comment by hanneskuettner** [comment]
For the time being, you can manually check if there are any (relational) fields that have a display template configured that looks like this, notice the extra `'` around the thumbnail. 

![image (1)](https://github.com/user-attachments/assets/8387e12d-071d-4616-a2e7-d4d4ac93c932)

The problem can only be seen if you inspect the raw value of the field, it will not show up in the configuration field itself. You can remove the `{{'$thumbnail}}` part in the raw value, safe and the collection should work again. Sorry for the labor required to fix this!

**Comment by shiing** [comment]
Thank you. After followed your steps to remove the `{{$thumbnail}}` in the raw value. This issue has been fixed.

Appreciate for your help!

**Comment by basisbit** [comment]
Can this issue please be reopened? The actual buggy behaviour in Directus is not fixed. The above is a workaround, not a fix.

**Comment by hanneskuettner** [comment]
The problem is a bug in an old v8 to v9 migration script that left artifacts in some display and interface configurations that are now causing problems. Directus itself is behaving correctly, ie. not allowing access to a field that does not exist in your data model.

The solution is a one-time fix you will have to apply to your display template configuration and the problem is gone. The V8 migration script has already received a bug fix about 1 year ago.

The easiest way to identify impacted fields is calling the `/fields` endpoint as an admin user and searching for `'$thumbnail'` in the response. Notice the extra `'`. Once you identified the fields you will have to fix it by going to the display template configuration and selection the "Edit raw value" option, where the thumbnail field will show up. Remove that and you're all set :+1:

**Comment by basisbit** [comment]
Well, then please let staff of the hosted Directus offering know about that, so that they can apply this fix for various affected customers, instead of requiring every affected customer to by chance find this here thread and then requiring them to have enough understanding of Directus to apply this fix by them self.

**Comment by hanneskuettner** [comment]
Please reach out to support@directus.io and let them know your project details so they can have a look for you.
