### ISSUE TITLE
Rich text - open link new tab label is confusing

### ISSUE THREAD

**Issue by simboonlong** [directus/directus#23435]
### Describe the Improvement

Currently the text copy for `Open link in` "New tab" vs "Current tab" label is confusing, when presented with checkbox interface:

https://github.com/user-attachments/assets/1e661dd5-49db-48be-9ed2-7c4faebf2e96

I would expect "New tab" text to persist, only the checkbox should checked or unchecked. Line at [here](https://github.com/directus/directus/blob/d7847a7a31f80442fabe081f6f0ad9b15f2cc19a/app/src/interfaces/input-rich-text-html/input-rich-text-html.vue#L352).

**Comment by rijkvanzanten** [comment]
@simboonlong Wanna open a PR for this? 🙂

**Comment by Abhishek7Tech** [comment]
@rijkvanzanten Can I work on this?
