### ISSUE TITLE
V-Color select interface doesn't support CSS-Variables

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#23441]
### Describe the Bug

When trying to setting a css-variable in the color-interface it shows an error in the interface:
 
![Bildschirmfoto 2024-08-21 um 17 53 44](https://github.com/user-attachments/assets/f95cf1de-3388-4bdc-b4e1-bb278506b4c7)

### To Reproduce

1. Click: edit raw value
2. Insert a css variable, e.g `var(--v-list-item-color-active)`
3. Save

**Result:** 
The css variable is used, but the interface is broken. 

**Possible solution:**
Add a third mode: 'css variable' to the interface, which is stored as string. This would also allow to insert the variable through the nterface (instead going through the `Edit raw`-approach)

### Directus Version

v10.12.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Dominic-Marcelino** [comment]
## Update:
Turns out that the interface won't throw an error, and display the dot-preview + the resolved css color value, if the css variable is known in it's current context.

## Testing
- use  a globally known variable, e.g `var(--theme--navigation--list--foreground-active)`
- After saving it will display a dot-preview + the current hex-value

## Result
Therewith i still think a third mode `css-var` should be added, in order to:
- not break if the variable isn't known in the current context
- After saving, I think the css-variable name should be displayed (instead of the resulting hex-value) as this could be misleading

**Comment by paescuj** [comment]
Similar to #21409
