### ISSUE TITLE
Delete notifications from App

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#23440]
### Describe the Improvement

And I'm back with another tiny issue regarding notifications: Currently there's no way of deleting notifications via the app.

I'd expect to have a third `delete` button at the top of the notification-actions. 

Related to [#22265(comment)](https://github.com/directus/directus/issues/22265#issuecomment-2298753869) there could be either a `delete all` or an `select all` button in combination with a second buttton to delete the selected ones

**Comment by paescuj** [comment]
Would it make sense to provide the delete option only in the archived view? Or were you thinking of displaying this in the inbox as well? With the latter, I'm afraid that the archive option would become less meaningful.

Note: We might want to add a delete permission preset to the default app permissions: https://github.com/directus/directus/blob/122d683eb5a488b4a34ab82e80813cbdc4f0ca95/packages/system-data/src/app-access-permissions/app-access-permissions.yaml

**Comment by Dominic-Marcelino** [comment]
> Would it make sense to provide the delete option only in the archived view? Or were you thinking of displaying this in the inbox as well? With the latter, I'm afraid that the archive option would become less meaningful.

Have been thinking about it too. I think based on the use-case of the notifications both would make sense.
