### ISSUE TITLE
Local Directus doesn't show Permissions and Roles

### ISSUE THREAD

**Issue by thedarkknight197** [directus/directus#23455]
### Describe the Bug

Missing Permissions and Roles section on administration panel 

### To Reproduce

create a new local application using:
```
npm init directus-project@latest <project-name>
cd <project-name>
npx directus start
```

node -v =>  v18.20.4

### Directus Version

i don't know, i think latest

### Hosting Strategy

Self-Hosted (Custom)

### Database

sqlite

**Comment by hanneskuettner** [comment]
Can you provide more details? Like a screenshot for example? With the newest version of Directus the Permission and Roles section of the settings have been separated into "User Roles" and "Access Control".

I'll be closing this, as I can reproduce this locally with your reproduction steps. A newly created Directus instance has these sections for me.

**Comment by thedarkknight197** [comment]
Hi @hanneskuettner, here can you see the screenshot.

As you see on setting sidebar is missing the section relate to Permissions and Roles. Today i see a live streaming and there are

![immagine](https://github.com/user-attachments/assets/ff3f090e-99e2-4f5a-aefe-c48961ed421a)

**Comment by thedarkknight197** [comment]
I need this section to manage the api access.

Where i can find it now?
![immagine](https://github.com/user-attachments/assets/d3e20e53-9fc4-49a1-bfa6-ca0da1e232f7)

**Comment by hanneskuettner** [comment]
They are right there, are they not?

As I said, with Directus 11 the roles and permissions section has been reworked into "User Roles" and "Access Policies".

The new concept is that you manage the permissions in policies and assign those policies to your user roles. One level of indirection, that allows you a lot more possibilities in the end.

**Comment by thedarkknight197** [comment]
Oh great, now is clear! Sound's very cool! Thank you for your patience

**Comment by rayenbenhassen07** [comment]
" Access to fetch at 'http://-----------:8055/items/trips/3' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. "
i did a simple fetch but this error happened .. do i have to insert localhost on the input Public policy => ip Access ?
