### ISSUE TITLE
ENV-Variables Security table not rendered correctly

### ISSUE THREAD

**Issue by maxsteinwand** [directus/directus#23459]
### Page

https://docs.directus.io/self-hosted/config-options.html#security

### Describe the Inaccuracy

The Table is not displayed correctly and broken. The whole security section is displayed as one string. Probably due to the additional `|---` at the header from the commit in https://github.com/directus/directus/pull/22986

**Comment by hanneskuettner** [comment]
Good catch! 

Do you mind opening a quick PR to get this fixed?
