### ISSUE TITLE
Directus SSO Support for Native Apps - PKCE OAuth2

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [directus/directus#23468]
### Describe the Request

A lot of discussions has been opened for this problem:

https://github.com/directus/directus/discussions/11080
https://github.com/directus/directus/discussions/12174
https://github.com/directus/directus/discussions/4463
https://github.com/directus/directus/discussions/22894
https://github.com/directus/directus/discussions/22427
https://github.com/directus/directus/discussions/16741
https://github.com/directus/directus/discussions/8867

Problem: How to login from a native app (example react native) with my directus configured sso providers.

In the classic way login into directus with a SSO would trigger the normal OAuth2 flow. This way the user currently gets the credentials as cookie, saved secure in the browser.

The doc of Directus SDK does not help here:
https://docs.directus.io/guides/sdk/authentication.html
```
type LoginOptions = {
	/** The user's one-time-password (if MFA is enabled). */
	otp?: string;
	/** Whether to retrieve the refresh token in the JSON response, or in a httpOnly cookie. One of `json`, `cookie` or `session`. Defaults to `cookie`. */
	mode?: AuthenticationMode;
	/** Use a specific authentication provider (does not work for SSO that relies on browser redirects). */
	provider?: string;
};
```

As we can see: ```does not work for SSO that relies on browser redirects``` which is almost every OAuth2 provider?

*Possible Solution 1: * Implicit Login Flow

In this Flow the directus instance would just redirect to the app with a deep link and provides an access_token. While this method works (https://github.com/directus/directus/discussions/22427#discussioncomment-9360985) is is not recommended as it inherits security risks:
```
[Implicit login](https://docs.expo.dev/guides/authentication/#implicit-login)
Because there was no secure way to do this to store client secrets in your app bundle, historically, many providers have offered an "Implicit flow" which enables you to request an access token without the client secret. This is no longer recommended due to inherent security risks, including the risk of access token injection. Instead, most providers now support the authorization code with PKCE (Proof Key for Code Exchange) extension to securely exchange an authorization code for an access token within your client app code. Learn more about [transitioning from Implicit flow to authorization code with PKCE](https://oauth.net/2/grant-types/implicit/).
```

Possible problem would be if a malicous website opens a new browser window, which opens the directus instance with the redirect url and then grabs the access token. Also a check for allowed redirect url's can't help here.

*Possible Solution?:*

So as we see due to the many dicussions and issues, this is a real problem, which could increase the usage of my beloved Directus CMS. As Expo mentions before here a possible solution could be ```PKCE (Proof Key for Code Exchange)``` as this is commonly used today ```most providers now support the authorization code``` 

I just mentioned you guys here, as we had this issue in the past several times. Others are open to join this issue :-)
@rijkvanzanten @br41nslug 

### Maintenance Strategy

As PKCE is very commonly used today, why not also use it in directus?

This would be a one time change?

**Comment by customautosys** [comment]
Why don't we just allow to authenticate using the ID token of the OpenID provider?

That way, we pass along the full info from the OpenID provider including the sub, email and name. There would also be no need to muck around with redirects. We just need to call an API route / SDK function (probably an equivalent of the current login method with some modifications) and it will return the directus access token. The OpenID ID token can be passed as bearer, in post data or whatever.

**Comment by NilsBaumgartner1994** [comment]
Any updates on this?

**Comment by NilsBaumgartner1994** [comment]
> Why don't we just allow to authenticate using the ID token of the OpenID provider?
> 
> That way, we pass along the full info from the OpenID provider including the sub, email and name. There would also be no need to muck around with redirects. We just need to call an API route / SDK function (probably an equivalent of the current login method with some modifications) and it will return the directus access token. The OpenID ID token can be passed as bearer, in post data or whatever.

The problem is, that you would require a ```client_secret``` like directus holds. The problem is, that public clients as react native apps (ios or android) and single page applications (SPA) cannot hold secrets. Their binary can be easily decompiled.

Therefore they cannot use the normal flow.

This is where PKCE would be handy: https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow-with-pkce

But this has another flaw, as we cannot verify if the client is valid, as mobile apps have no way to see if they are truly who they say they are: https://www.hackmanit.de/en/blog-en/123-when-pkce-cannot-protect-your-confidential-oauth-client

**Comment by NilsBaumgartner1994** [comment]
@rijkvanzanten I implemented a first draft of PKCE https://github.com/directus/directus/discussions/23611
I would therefore close this here.

**Comment by NilsBaumgartner1994** [comment]
We implemented the first draft: https://github.com/directus/directus/discussions/23611
