### ISSUE TITLE
 Boolean field default value `false` is not stored

### ISSUE THREAD

**Issue by danmichaelo** [directus/directus#23466]
### Describe the Bug

If I try setting the default value of a boolean field to `false`, the field is stored with no default value.

### To Reproduce

1. Add a new boolean field. Set the default value to "false". 
2. Save. 
3. Re-open the field. The default value should still be "false", but is instead "NULL"

### Directus Version

v11.0.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Postgres 16

**Comment by danmichaelo** [comment]
Seems to be fixed in #23427

**Comment by jaads** [comment]
duplicate of https://github.com/directus/directus/issues/23379
