### ISSUE TITLE
Policies cannot be added to Role using SDK

### ISSUE THREAD

**Issue by aramcheck** [directus/directus#23467]
### Describe the Bug

We have a tool that runs data migrations implemented using the SDK. We're having issues migrating our implementation to the new Policies model, we're not sure if we're missing something or the implementation lacks support.

### To Reproduce

Try to create a new policy and assign it to a role.

To create the policy we found two approaches that work (but with type errors):

**Approach 1** Create the policy first and then create the permissions related to that policy. In this approach `name` is required but gives a TypeScript error. (fixed here: https://github.com/directus/directus/issues/23386)

```
const policy = await client.request(
  createPolicy({
    name: 'Example policy'
  })
);
await client.request(
  createPermissions([
    ...assistants,
    ...conversations,
    ...messages
  ].map((p) => ({ ...p, policy: policy.id })))
);
```

**Approach 2** Create the policy using partial permission objects. Execution **works** but TypeScript compiler complains that `permissions` should have `id`. Our permission objects look like this:

```
  {
    collection: 'assistants',
    action: 'read',
    permissions: {},
    validation: {},
    presets: null,
    fields: ['*']
  }
```

**Ignoring the type error execution works and permissions are created as expected.** We're not sure if this is a valid use, however.

```
const policy = await client.request(
  createPolicy({
    name: 'Example policy',
    permissions: [...assistants, ...conversations, ...messages]
  })
);
```

However, we have not found a way to assign a policy or set of policies to a role. This seems to be related to the **M2M** relationship, that is, the **ID** of the policy is not what is expected by the **roles** collection but the ID of the junction collection that does not exists yet. So for example this:

```
await client.request(updateRole('id', {
  policies: [policy.id]
}
```

Fails with:

```
error
 errors: [
  {
    "message": "You don't have permission to access this.",
    "extensions": {
      "code": "FORBIDDEN"
    }
  }
]
```

If we use the HTTP API we can patch the role successfully. How can we update users and roles using the SDK? We looked into the documentation and couldn't find specific examples related to policies management.

### Directus Version

v11.0.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 16

**Comment by hamzace** [comment]
> If we use the HTTP API we can patch the role successfully.

I'm having the same issue here, even when using the http api. Can you please share your workaround?

**Comment by linaGirl** [comment]
Seems to work when adding roles to policies usind the SDK, may as well work when adding policies to roles (i didn't test):

```typescript
directus.request(updatePolicy(rowId, { roles: [{ role: roleId }] }, ['id']))
```
