### ISSUE TITLE
'w is undefined' in insights

### ISSUE THREAD

**Issue by Nebula-Developer** [directus/directus#23469]
### Describe the Bug

I am unable to get any insight panels to work, some are completely blank, and others print 'w is undefined'. There are no logs in docker.

![image](https://github.com/user-attachments/assets/1e8a19bb-431d-4223-8fc8-2d32809085da)

### To Reproduce

Create a directus docker instance, make a new panel in an insight.

### Directus Version

v11.0.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

sqlite3

**Comment by hanneskuettner** [comment]
Can you specify for which panel you see the `w is undefined` error message and for which ones you would expect output but do not see any?

**Comment by Nebula-Developer** [comment]
Some panels (about half) will show nothing, and others will state the error (`w is undefined`).

The ones I have tested to show the error are:
- Time Series
- Pie or Donut Chart
- Meter
- Line Chart

And pretty much everything else.
This happens on fresh directus docker projects too, not just this current one (which is also a fairly new project).

**Comment by hanneskuettner** [comment]
Do you have any extensions installed/enabled? Because I'm unable to reproduce it with a fresh Directus install on my end.

Can you share the full error trace you are seeing in the console, if any?

**Comment by Nebula-Developer** [comment]
> Do you have any extensions installed/enabled? Because I'm unable to reproduce it with a fresh Directus install on my end.
> 
> Can you share the full error trace you are seeing in the console, if any?

There are no errors in the console. When I click copy I get:
```json
{   "fileName": "http://localhost:8055/admin/assets/index.ZEGekNQg.entry.js",   "lineNumber": 52,   "columnNumber": 83899,   "message": "w is undefined" }
```

I have one extension, `directus-extension-display-link`, and the problem remains when I remove it.

When I modify a panel, I get the logs:
2024-09-18 15:03:23 [03:03:23] GET /users/me?fields=id 304 12ms
2024-09-18 15:03:30 [03:03:30] GET /users/me?fields=id 304 10ms
2024-09-18 15:03:32 [03:03:32] PATCH /users/me/track/page 204 25ms
2024-09-18 15:03:44 [03:03:43] PATCH /users/me/track/page 204 18ms
Which I presume are fine based on the status codes.
