### ISSUE TITLE
Link to "Good first issues" is broken

### ISSUE THREAD

**Issue by FatumaA** [directus/directus#23463]
### Page

https://docs.directus.io/contributing/pull-request-process.html

### Describe the Inaccuracy

Clicking on the "Good first issues" links to an empty GitHub issue search result. Giving the impression that there are no open good first issues. But the issues are there just labelled as "":star: Good First Issue" instead.

Illustration: 
![Screenshot 2024-08-23 at 11 19 53](https://github.com/user-attachments/assets/aa19de6f-2e82-438a-997c-bac5a5c895b2)

![Screenshot 2024-08-23 at 11 20 05](https://github.com/user-attachments/assets/be52828d-2434-43c4-9eeb-6a32d7172b69)

Updating the link should fix this, I'd be happy to open a PR for this.

**Comment by paescuj** [comment]
> Updating the link should fix this, I'd be happy to open a PR for this.

We would appreciate a PR 🚀

**Comment by FatumaA** [comment]
> > Updating the link should fix this, I'd be happy to open a PR for this.
> 
> We would appreciate a PR 🚀

Done 😌
