### ISSUE TITLE
CORS Missing Allow Origin With AgencyOS and Directus

### ISSUE THREAD

**Issue by BradPerbs** [directus/directus#23471]
### Describe the Bug

I've freshly installed Directus with AgencyOS and I'm getting CORS Missing Allow Origin when navigating through the pages.

If I reload the page then it loads, but when navigating for example using the menu, it returns CORS Missing Allow Origin.

### To Reproduce

Freshly Installed AgencyOS and Directus

### Directus Version

10.13.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
Heya!

This is either a problem with AgencyOS itself or a configuration problem on your end, not something related to Directus itself. Please have a look in our [Community Discord](https://chat.directus.io) for people having similar problem or [open an issue in the AgencyOS repository](https://github.com/directus-labs/agency-os/issues).
