### ISSUE TITLE
Missing authentication() in documentation Home

### ISSUE THREAD

**Issue by thedarkknight197** [directus/directus#23476]
### Describe the Request

In https://docs.directus.io/ on authentication tab is missing the authentication import from directus@sdk

Previous:
```javascript
import { createDirectus, rest, createUser } from '@directus/sdk';
const client = createDirectus('https://xyz.directus.app').with(rest());

const newUser = await client.request(
	createUser({
		email: 'user@example.com',
		password: 'd1r3ctu5'
	})
);

const user = await client.login('user@example.com', 'd1r3ctu5');
```

New:
```javascript
import { createDirectus, rest, createUser, authentication } from '@directus/sdk';
const client = createDirectus('https://xyz.directus.app').with(rest()).with(authentication());

const newUser = await client.request(
	createUser({
		email: 'user@example.com',
		password: 'd1r3ctu5'
	})
);

const user = await client.login('user@example.com', 'd1r3ctu5');
```

### Maintenance Strategy

i don't know what put here

**Comment by rijkvanzanten** [comment]
Where is this? The examples on https://docs.directus.io/reference/authentication.html seem correct to me, but I might be missing something 🙂

**Comment by hanneskuettner** [comment]
On the main page in the "Authentication" code sample

**Comment by thedarkknight197** [comment]
@rijkvanzanten here is missing with(authentication) on authentication tab in https://docs.directus.io/

![immagine](https://github.com/user-attachments/assets/cdd39388-6574-4ebc-a260-db2ec2f130c7)
