### ISSUE TITLE
Project name with colon in it breaks client mail sender parsing

### ISSUE THREAD

**Issue by twoends** [directus/directus#23475]
### Describe the Bug

Following the erroneously closed issue [23320](https://github.com/directus/directus/issues/23320)

After further investigation I found there is an actual bug. Apparently I was in the extremely unfortunate situation of having the Directus project called **Re:Anime**. This name gets prepended to the email address while sending the mails from directus and this is what happened in various scenarios:

1. Sending email from project called Re:Anime, looking in the .eml I find `From: Re:Anime <xxx@xxx.it>;`, unknown sender in my mail client
2. Sending email from provider webmail with mail named Re:Anime, looking in the .eml I find `From: "Re:Anime" <xxx@xxx.it>`, with name between double quotes and correctly displayed by my mail client
3. Sending email from project called Re Anime, looking in the .eml I find `From: Re Anime <xxx@xxx.it>`, correctly displayed by my mail client

### To Reproduce

Just create a project with a name like My:Project and send an email

### Directus Version

v10.13.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
Wanna open a PR? The formatting currently happens here: https://github.com/directus/directus/blob/1458f410e79664124f8322efdd7bad44e1d1c1ff/api/src/services/mail/index.ts#L67

Wrapping the project name in `"` characters might be enough 🙂

**Comment by shaietz** [comment]
Hello! i have created a PR with the proposed change that should fix the issue.
I want to start contributing and found this issue with the good first issue tag and thought it would be a good place to start :)
