### ISSUE TITLE
MariaDB errors on introspection

### ISSUE THREAD

**Issue by jaads** [directus/directus#23486]
### Describe the Bug

While testing something for MariaDB, I noticed that it throws an error after logging in (or more specifically: when introspecting the database). In the logs in basically says

```
You have an error in your SQL syntax;
```
In the UI you see this after logging in.

<img width="590" alt="Screenshot 2024-08-26 at 10 40 14" src="https://github.com/user-attachments/assets/32e8477a-be1a-432a-9423-e4f2f18b5690">

It seems something is wrong with the last join of the `columnInfo` introspection query.

### To Reproduce

- Setup a MariaDB (Docker image `mariadb:11.4`) 
- Bootstap the database with the Directus tables 
- Start the server and the editor
- Log in. You will see the unexpected error

### Directus Version

main

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

MariaDB

**Comment by hanneskuettner** [comment]
Possibly introduced in https://github.com/directus/directus/pull/23149?

**Comment by jaads** [comment]
Yes it seems so
