### ISSUE TITLE
z-index issue for translation-drawer on bookmark creation / editing

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#23499]
### Describe the Bug

When creating / editing a bookmark and trying to add a new translation the drawer is behind the modal and it's background
![Bildschirmfoto 2024-08-27 um 13 13 13](https://github.com/user-attachments/assets/49492866-6c53-4f4f-b72c-3cdd5475fe9f)

### To Reproduce

1. Create a collection
2. Create a bookmark
3. For the name select "new custom translation" 

### Directus Version

v10.12.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
Ahh tricky one. The dialogs expect to be a higher priority than drawers at all times (as they're used for error messages and user confirms etc), but that's conflicting with the bookmark use here.
