### ISSUE TITLE
To be able to embed Directus editor on another web site

### ISSUE THREAD

**Issue by sitawit** [directus/directus#2350]
# Feature Request
To be able to embed an editor on another web site.

## What problem does this feature solve?
Instead of creating our own editor (practically, using the existing editor), we can easily use a built-in editor in our own web site. Or in case, we create a custom data type. We don't have to implement the same editor in a different location. (One in Directus and another in our web site).

## How do you think this should be implemented?
The editor can be embedded using some javascript. Actually, it should be the same javascript as Directus but also having the embedded save button which sends the data directly back to Directus. Could it be a like another page extension? But this time, it can be embedded in another website.

## Would you be willing to work on this?
I would like to use it if it makes sense to create this feature in Directus. My only concern is I may not be able to cover all possible editor in Directus myself or in a short time. 

## Note
If this is already possible, please let me know. I'm quite new to Directus anyway.

**Comment by shealavington** [comment]
I'm going to confidently go ahead and say this won't be a feature built into the Directus Core. 
By your explanation, this is something you could do yourself using the API.

Directus provides an API layer around your data, therefore, you coul:
* Authenticate yourself on your website.
* Load the data into a WYSIWYG, 
* Make the changes you need
* Save and and update.

On another note, you mentioned, you don't want to implement another editor in your website, however, I would suggest that's exactly what you do. It wouldn't be good practice to be sharing resources like that across applications. The WYSIWYG depends on the Directus Styles, therefore if Directus changed styling, it might not work for you on your site anymore.

However, on a positive note, Directus is extendable, therefore, if this is a feature you would really like to build, you are welcome to go ahead and try to do so.

https://docs.directus.io/getting-started/contributing.html#feature-requests

**Comment by rijkvanzanten** [comment]
I'll have to agree with @shealavington on this one. The interfaces inside Directus are proprietary to Directus. Even if you were able to import the code into your own project, your project needs to use the same store structure, have the same css variables available, provide the same props, listen to the same events etc etc etc. I don't think this is something that's applicable to most (if any) projects that are made on Directus....
