### ISSUE TITLE
Block editor image attributes such as "Stretch image" are buggy in admin UI

### ISSUE THREAD

**Issue by HeikoMueller** [directus/directus#23504]
### Describe the Bug

The Block Editor Image component has attributes such as "With border", "Stretch image" and "With background". If you enable one of these in the "Click to tune" popup, the attributes symbol gets highlighted. However, once you close the popup and later re-open it, the symbol is shown as disabled again, even if the attribute is actually stored as true. The first issue is that you do not have a reliable representation of the current state. The second issue is that you cannot disable an attribute later on, since if you re-open the item, it will always be shown as disabled, regardless of its actual state in the db.   

### To Reproduce

Issue 1:
- Insert an image in the Block editor
- Click on the "Click to tune" button
- Enable one of the attributes and close the popover
- Click on the "Click to tune" button again => The before enabled attributes are not shown as enabled.

Issue 2:
- Open an item that includes Block Editor code with an Image that has for example "Stretch image" enabled
- Click on the "Click to tune" button => The "Stretch image" symbol is not highlighted. You are unable to disable it. 

### Directus Version

v11.0.2

### Hosting Strategy

Self-Hosted (Custom)

### Database

SqlLite3 v5.1.7

**Comment by rijkvanzanten** [comment]
I'm wondering if this bug is Directus specific, or an issue in the downstream editor.js library. Anywho, good catch 🙂

**Comment by HeikoMueller** [comment]
> I'm wondering if this bug is Directus specific, or an issue in the downstream editor.js library. Anywho, good catch 🙂

Hm ... At least if you look at the editor.js demo, https://editorjs.io/ , image attributes seem to work as expected
