### ISSUE TITLE
Install procedure of Directus

### ISSUE THREAD

**Issue by kkar** [directus/directus#2352]
Hello,
I have used Directus in the past for experimental purposes and I think it's time to get into it for my next project. Thank you for this awesome piece of software!

I have a question (not an issue report) about the installation and the behavior of the latest stable version.

I downloaded Directus, extracted it in my UwAmp's directory and browsed my localhost url to access the installation wizard. Instead I got redirected to Directus' login page. After logging in with the default credentials I saw that there was demo content in the admin panel and in the upper-left corner was saying "Demo", along with a remote directus demo url. I deleted all of the collections, then Directus showed an error and prompted me to refresh the page, which I did, and the collections were magically back (!).

Am I doing something wrong? Isn't there any Installation wizard anymore? Shouldn't it ask me for my database information etc? I am totally confused, and it seems hard to find information about it in the manual. The manual states that I should see a wizard, if I understand correctly.

Any directions will be appreciated.

**Comment by rijkvanzanten** [comment]
> I downloaded Directus, extracted it

Does this mean that you downloaded the zip from the releases page? I remember someone posted a comment that the app config file contained the wrong reference. That was swiftly fixed but might've not propagated into the .zip file? Could you check the `/public/admin/config.js` file to see if the path to the API is correct? This is what it should look like: https://github.com/directus/directus/blob/master/public/admin/config.js

**Comment by shealavington** [comment]
This issue arose in Slack too with Zver. 
When downloading the latest release it was set to the DemoAPI.
I believe this is fixed in the master branch.

**Comment by ziguane** [comment]
> I downloaded Directus, extracted it in my UwAmp's directory and browsed my localhost url to access the installation wizard. Instead I got redirected to Directus' login page.

Hi all,
I encounter the same problems and I will be curious to know the solution ...

Installed on debian 8 with mysql 5.7 with the following command git clone https://github.com/directus/directus.git

**Comment by rijkvanzanten** [comment]
@ziguane any errors in the devtools? Does the API work when you access it directly?

**Comment by rijkvanzanten** [comment]
I'm closing this as the OP has been solved.
