### ISSUE TITLE
Allow save and stay on user-role editing

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#23524]
### Describe the Improvement

When editing a user role whenever we save, the user get's redirected to the role overview. For a better UX I'd suggest to allow an 'save and stay'.

Ideally even as a default option, but could understand that it's not intended as default for consistency reasons.

--- 
Somehow related to discussion https://github.com/directus/directus/discussions/4081

**Comment by Dominic-Marcelino** [comment]
Update: `cmd + s` works (binding must have been overwritten based on a previous action in my test).

I still think the button-option as in the items could be added.

**Comment by dev-jenish** [comment]
Hi @Dominic-Marcelino and @rijkvanzanten,

I understood the improvement regarding the save functionality. Currently, the save button click triggers saveAndQuit, while `cmd + s` uses saveAndStay. I’ve replaced the save button’s click method with saveAndStay for consistency.

May I create a PR for this change?

Thanks!
