### ISSUE TITLE
Ability to add second M2M field after initial relationship creation

### ISSUE THREAD

**Issue by danielrosehill** [directus/directus#23536]
### Describe the Improvement

Hi everyone!

Apologies if this already exists and I missed it.

When setting up an M2M relationship, Directus's default behavior is to:

1: Create the join table
2: Create a field in the table where the user creates the M2M from

There is an option to create a _corresponding field_ but this is disabled by default and (correct me if I'm wrong) not available in the regular creation UI:

![image](https://github.com/user-attachments/assets/d15051a5-6215-4712-8bcd-ad4f176c4147)

There are a few M2Ms I set up the "easy" way and realised after the fact that setting up the corresponding field would be helpful. 

I would like to preserve the relationships I've created to date, however. 

Is there any way to add this corresponding field to an M2M after the fact? If not, that's my "tweak" frequest!

**Comment by rijkvanzanten** [comment]
> Is there any way to add this corresponding field to an M2M after the fact?

You can just create a new m2m field on the other collection and reuse the junction table and fields 🙂

**Comment by danielrosehill** [comment]
> > Is there any way to add this corresponding field to an M2M after the fact?
> 
> You can just create a new m2m field on the other collection and reuse the junction table and fields 🙂

Ah! Thank you!
