### ISSUE TITLE
Nested "Bundle" type extensions

### ISSUE THREAD

**Issue by omega-800** [directus/directus#23533]
### Describe the Bug

Well hello there :) 
I'm pretty new here, but in love with directus already! I want to apologize if the following issue is intended, but I just couldn't find any info describing it. 
When adding an extension with type "bundle" to another bundle extension through the command `directus-extension add` , an empty folder gets created, without the index.{js,ts} file referenced by the new entry inside of the parent extension's package.json. 
Neither does the new entry inside of the parent bundle's package.json get modified to include the property "entries" inside of the child-bundle entry, where the child-bundle's extensions would be defined.
Here's the parent's package.json `directus:extension.entries` property:

```
"entries": [
  {
    "type": "bundle",
    "name": "directus-extension-bundle-child",
    "source": "src/directus-extension-bundle-child/index.ts"
  }
]
```

And here's the automatically created folder structure:

```
$ exa --tree -a ./src 
src
└── directus-extension-bundle-child
```

The [documentation](https://docs.directus.io/extensions/bundles.html) mentiones that 

> The bundle extension type currently doesn't support the migration extension type    

but I couldn't find anything about nested bundle-type extensions.       
So my question would be: Is this behavior expected, meaning that an extension of type bundle can't contain another extension of type bundle?
If so, would it be possible to include that in the documentation or remove the "bundle" selection from the `directus-extension add` command to prevent confusion?
If not, how would one define the sub-extensions of a child-bundle inside of the topmost-bundle extension's package.json?

Thanks for the awesome work on this project :)
Cheers

### To Reproduce

1. Have a directus v11.0.0 instance running with postgres 16 as the DB
2. `cd` into the extensions folder
3. run `npx create-directus-extension@latest` and select `bundle`, `directus-extension-bundle-parent`, `y`
4. run `cd directus-extension-bundle-parent`
5. run `npm run add` and select `bundle`,  `directus-extension-bundle-child`, `typescript`

### Directus Version

v11.0.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 16

**Comment by br41nslug** [comment]
Bundles inside bundles are indeed not supported and should not be selectable using the `directus-extension add` command 🤔

**Comment by omega-800** [comment]
Gotcha, thanks for the quick response :)
