### ISSUE TITLE
Basic Installation failed - Apache + MySQL - Error: SQLSTATE[42000]

### ISSUE THREAD

**Issue by 365degreetotalmarketing** [directus/directus#2354]
Basic Installation of _directus-master.zip_ failed with error "SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes" after entering database connection details.

**Comment by 365degreetotalmarketing** [comment]
Solution: go to directus-master/migrations/db/schemas and change line 33 
` $table->addColumn('title', 'string', [
            'limit' => 255,`

to

` $table->addColumn('title', 'string', [
            'limit' => 191,`

**Comment by careyhead** [comment]
> Solution: go to directus-master/migrations/db/schemas and change line 33

Which file?
