### ISSUE TITLE
I have an issue with API authorizations.

### ISSUE THREAD

**Issue by rayenbenhassen07** [directus/directus#23543]
### Describe the Bug

hello i set up directus on my vps alsi i finished every things related to database and now i wanna use my api in nextjs app 
----> the problem is when i try to fetch api it didn't work 
Error |
3:1 Access to fetch at 'http://75.119.------:8055/items/trips/3' from origin 'http://localhost:3000/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### To Reproduce

i dont know

### Directus Version

11.0.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
You can set the `CORS` environment variables to control the cors headers that Directus returns. See [https://docs.directus.io/self-hosted/config-options.html#cors](https://docs.directus.io/self-hosted/config-options.html#cors) for all available settings

**Comment by rijkvanzanten** [comment]
@localjo The default CORS settings should work with most frontends. If not, send an email to support@directus.io and they can take a look and adjust your project as needed 🙂
