### ISSUE TITLE
not able to create deleted field - keep saying field exist

### ISSUE THREAD

**Issue by Kvarkas** [directus/directus#23541]
### Describe the Bug

I am using docker with directus 11.0.2 on Ubuntu 22
Created collection, add column "title" then decide to delete it (successfully) after a while tried to create it again but getting error:

```json
{
  "errors": [
    {
      "message": "Invalid payload. Field \"title\" already exists in collection \"mycollection\".",
      "extensions": {
        "reason": "Field \"title\" already exists in collection \"mycollection\"",
        "code": "INVALID_PAYLOAD"
      }
    }
  ]
}
```

### To Reproduce

Create collection, add text column, add data, delete data, delete column, restart directus, try to add same name column to directus to same collection

### Directus Version

v11.0.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgis latest

**Comment by Kvarkas** [comment]
solution is manually delete this column from directus_fields

**Comment by rijkvanzanten** [comment]
I haven't been able to reproduce this with on Directus v11.0.2 on PostgreSQL 13.14 w/ Postgis  the given information, so I'll close this for now.

@Kvarkas Could you elaborate on your hosting setup? Are you using Redis for caching f.e.? Any other information that could help us reproduce this issue?

**Comment by Kvarkas** [comment]
hello, just to update you, I tried to recreate it again with a new collections and that not occurred, however issue i have was with collection created in directus 10 what was migrated to 11, maybe something goes not as planned then and what's why I catch that issue. will keep eye on such if manage to recreate will update you again.
