### ISSUE TITLE
[UNKNOWN] Request failed with status code 413

### ISSUE THREAD

**Issue by hamza-bahaa** [directus/directus#23557]
### Describe the Bug

[UNKNOWN] Request failed with status code 413

I was trying to upload a picture from my device to the admin and this happens when I try to upload fine pictures as well

### To Reproduce

I was trying to upload a picture from my device to the admin and this happens when I try to upload fine pictures as well

### Directus Version

10.6.0

### Hosting Strategy

Self-Hosted (Custom)

### Database

sqlite

**Comment by rijkvanzanten** [comment]
Closing this as 10.6 is almost a year out of date. Happy to reopen if the problem persists in the latest release.
