### ISSUE TITLE
Flow is creating an extra empty item on item creation

### ISSUE THREAD

**Issue by hmaskat17** [directus/directus#23562]
### Describe the Bug

I have a Flow triggering on item.create and item.update. It does some simple checks, fetches data and creates or updates an item.

The issue occurs when creating a new item, it will always create two items. It will create the item that the Flow creates but also an extra empty item, i.e. an item with all it's fields as empty except for any default values for those fields which are displayed. 

Looking at the logs, it seems to be making only one POST request.

When creating an item from the API, the API responds with the empty items ID. When looking at the Flows create operation logs, it returns the correct item ID.

Updating an item is working normally.

(On a side note, is it somehow possible to have a Flow exit and continue the create/update process as it would normally, without having to create the create/update operations for them on a reject/exit? For example, if an external origin triggers the Flow by creating an item, then exit the Flow immediately but have Directus continue the create action? If i just exit the Flow it will not create anything.)

The Flow:

![image](https://github.com/user-attachments/assets/d8a8a994-0a8a-48b3-9098-6286facb9a43)

### To Reproduce

Create a Flow with Filter and item.create, item.update. Create an item in App or API.

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 15.7

**Comment by br41nslug** [comment]
It looks like your Flow itself is creating an item in the `location` collection (ending operation top right) based on when a new item is created in Directus (triggering on the `location` `items.create` `filter event`) which would result in a second item being created for each created item. The empty item is likely the original item that triggered the flow, it doesn't look like the Flow is returning the received/edited payload as expected.
https://docs.directus.io/extensions/hooks.html#filter

Either erroring out the flow after manually creating the item or returning the data used to create the item should resolve this issue 😄

**Comment by hmaskat17** [comment]
Omg, that did it. I replaced all the create/update operations with a transform payload operation instead. Thanks! I just didn't fully understand yet that the Flow expects the payload object as the last value. Perhaps this was an issue on my end, but it might help if the documentation clarified this further?
