### ISSUE TITLE
Ignoring whitespace in tags inserts "null" into the tags

### ISSUE THREAD

**Issue by spee** [directus/directus#23577]
### Describe the Bug

For a tags field, the app offers an interface option to specify how whitespace should be handled, like removing the whitespace, or replacing whitespace with a hyphen or underscore. When no option is selected, I'd expect whitespace to be left alone, but instead, it inserts `null` into the tag.

Thus, `foo bar` becomes `foonullbar`.

### To Reproduce

- Add a tags field to a collection.
- In the Interface section of the field, deselect the value of the "Whitespace" option. 
- Create an item in the collection, and enter a tag containing a space, e.g. "foo bar".
- In the added tag, the space is replaced by "null", e.g. "foonullbar".

### Directus Version

v11.0.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
This seems to only show up when you've previously set the option to something else, and then "Deselect" the selected option.

**Comment by spee** [comment]
I can confirm that we previously had it set to "Remove whitespace".
