### ISSUE TITLE
How to build Directus Suite

### ISSUE THREAD

**Issue by fnicastri** [directus/directus#2357]
I'm working to a project using Directus as backend, I will use the suite due to hosting limitations.
I would like to build the suite from the api's and app's repos to be aligned to the lasts releases/commits and possibly be able to contribuite to the project.
What's the procedure to build it?

Thanks

**Comment by rijkvanzanten** [comment]
The suite is nothing more than a combination of the `build` branches of the api and app repos.

You can work on the API locally by cloning the repo and installing the composer dependencies.
You can work on the application locally by cloning the application repo, installing the npm dependencies with `npm install` and fire up the buildchain with `npm run dev`.

**Comment by fnicastri** [comment]
Basically the app code goes in public/admin?
Any other change?

**Comment by benhaynes** [comment]
Is this information helpful? It's our full deploy process:

https://docs.directus.io/advanced/deploying-versions.html

**Comment by fnicastri** [comment]
@benhaynes That's exactly what I was looking for!

Thanks!
