### ISSUE TITLE
Inconsistent Date/Time Formats in API Response

### ISSUE THREAD

**Issue by a14e** [directus/directus#23586]
### Describe the Bug

The DateTime field is described in the protocol as using the ISO8601 Date format. However, it does not return a timezone for certain fields. For prebuilt types like date_updated, the response includes a timezone.

For example, I received the following response:
```
{
    "data": {
        "Customer_Subscription": [
            {
                "id": "4c14008f-db8f-48cc-b215-df070d48576a",
                "date_created": "2024-09-05T21:35:26.836Z",
                "date_updated": "2024-09-05T21:46:19.462Z",
                "expiration": "2024-09-04T12:00:00"
            }
        ]
    }
}
```
Both expiration and date_created are of the same type, but they have different formats in the response.

My library cannot parse the same type with different formats, and this inconsistency seems to be an error.

### To Reproduce

-

### Directus Version

v10.13.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgresql 16

**Comment by rijkvanzanten** [comment]
The Directus `datetime` type is a datetime without a timezone, whereas the `timestamp` type is a datetime with a timestamp. In this case, `date_created` / `date_updated` are of type `timestamp` whereas you `expiration` field is presumably a `datetime`. If you create that field as a `timestamp` instead all date outputs in your example will return in the same format 👍
