### ISSUE TITLE
Redirect / to /admin

### ISSUE THREAD

**Issue by fnicastri** [directus/directus#2358]
wouldn't it be better to redirect / to / admin?
any contraindication using `RedirectMatch ^/$ /admin/` or `RewriteRule ^$ /admin [L]`  in public/.htaccess?

Thanks

**Comment by rijkvanzanten** [comment]
There's an `/` endpoint in the api that returns info about the api. Redirecting that to /admin would break the app (& be a breaking change)

**Comment by fnicastri** [comment]
@rijkvanzanten  Don't you think that could be better to move this endpoint somewhere else?
This is not a great user experience.

**Comment by rijkvanzanten** [comment]
That's a matter of opinion. Also, you can host the app wherever separately from the api to end up with whatever url structure you believe is a good user experience.

**Comment by fnicastri** [comment]
Obviously it is a matter of opinions.
In mine it's not a good experience if the end user find this kind of response in the root of the backend  domain: `{"error":{"code":3,"message":"Unauthorized request"}}`,
That's all.

**Comment by rijkvanzanten** [comment]
One could also argue that it makes sense that `api.example.com/` is the data api for `example.com`, with `api.example.com/admin` being the admin backend that manages that API.

Either way, changing `/` to always redirect to `/admin` is a breaking change and would only work for the combined build (the app has to be at that exact path). It's also possible to install the app and API separately and set it up in whatever url structure makes sense for your individual project. We can keep discussing this for future major versions, but it's not something we will / can change right now.

**Comment by fnicastri** [comment]
I was not asking to change it right now, that's obvious.
I see that it is a breaking change and there is a lot more works to do on Directus 7 right now.
It was only an opinion/suggestion.
BTW thanks for the work on this project!

Frank

**Comment by dev7ch** [comment]
I assume if you change the mode from production into dev or development in thr api configs at the top you get some more infos about the error (at least on localhost)

**Comment by dev7ch** [comment]
So probably ths mechanism could be used to adjust the outputs

**Comment by fnicastri** [comment]
@dev7ch  I'm already in dev mode. Tried both, same message.

**Comment by rijkvanzanten** [comment]
@fnicastri I feel like this a bigger question of what Directus is to begin with. Do we consider Directus to be the API, with the admin app a tool to manage said API, or is Directus a CMS (app) that exposes the data through an API? I have been operating under the first, but from your suggestion I feel like you're more in the second mindset 🙂

@benhaynes thoughts on this? (Again not something to change anytime soon, but it might be good to have this vision documented somewhere)

**Comment by benhaynes** [comment]
My answer to this has changed over time, but as of now I see Directus as an API with an optional GUI for managing things. My reasoning is that while both are decoupled and can be used separately, the App does not work without the API, but the API in no way requires the App.
