### ISSUE TITLE
Wrong illustration in the M2A doc section

### ISSUE THREAD

**Issue by CVirus** [directus/directus#23600]
### Page

https://docs.directus.io/app/data-model/relationships.html#many-to-any-m2a

### Describe the Inaccuracy

The illustrative image in the M2A section doesn't reflect the example described.

**Comment by paescuj** [comment]
Thanks for creating this issue! However, there is not enough information available. For me, the illustration seems to match the description. Therefore, I'll close this issue for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻
