### ISSUE TITLE
Help for flows

### ISSUE THREAD

**Issue by JeremyMAQUAIRE** [directus/directus#23603]
### Describe the Bug

Hello,

I use directus v11 with a docker image.
I created a flow that is triggered when a user changes.
After searching I did not find the answer to my 2 questions:
1 - How to retrieve the user id modify when triggered.
2 - How to make the trigger take place on a field only. I want the Flow to be triggered after a particular field has been modified.

Thank you for your help on these 2 points.

### Directus Version

V11

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL

**Comment by domdus** [comment]
> 1 - How to retrieve the user id modify when triggered.

When the flow triggers you should the event in the flows logs panel on the right.

**Example: Users title got modified**
<img width="537" alt="image" src="https://github.com/user-attachments/assets/ea14b29b-1a8e-41c6-b3db-3b45a6c874fc">

The `keys` array contains the user id. It will contain 1 user id for single user updates and multiple in case of batch updates.
You can access it with `{{$trigger.keys[0]`}} other operations or when in Run Script `data.$trigger.keys[0]`.

-------------------------------------------------------

> 2 - How to make the trigger take place on a field only. I want the Flow to be triggered after a particular field has been modified.

It will trigger on all updates at first anyway (that's normal). You can conditionally check for a particular field change e.g. the `title` field, in order to proceed or skip the flow.


**A) Use a Condition Operation:**
<img width="536" alt="image" src="https://github.com/user-attachments/assets/c45f6de5-7394-4747-a12b-4ef594557a91">

**B) Use Run Script operation:**
<img width="538" alt="image" src="https://github.com/user-attachments/assets/d2186604-8aef-44b3-894e-425067af30dc">

**Code:**
```
module.exports = async function(data) {
    // Does the title field exist in payload?
    // If it exists it got updated
	if (data.$last.payload?.title) { // title !== undefined
        // Do something with the title
        const title = data.$last.payload.title
        
       	// Do something with the user id
        const userId = data.$last.keys[0];

        // Pass info to the next operation
        return {
        	"userId": userId,
            "newTitle": title
        };
    } else {  
        throw new Error("Title did not change");
    }
}
```

**Comment by JeremyMAQUAIRE** [comment]
Hello, the id indicated in your answer is that of the user who has modified but that of the one who is modified. So I do not know to recover the one that is modified

**Comment by domdus** [comment]
There are a lot of other events for `user.update` trigger, where e.g. `last_page` is modified for your own user.

The event where I change **another** users title is somehwere in between:
<img width="178" alt="image" src="https://github.com/user-attachments/assets/3d21f6ed-00b6-491c-b4a1-57f32755a1de">

 And for this event:
- `keys` array contains user item id(s) that got modified/changed (red arrow)
- `$accountability` object contains the user who performed the change - that's me (blue arrow)
<img width="527" alt="image" src="https://github.com/user-attachments/assets/209580f2-a201-4ab0-841e-9b02be3459bb">

**Comment by JeremyMAQUAIRE** [comment]
![image](https://github.com/user-attachments/assets/8ee446ff-bd2c-4879-ac3c-ddfc06246101)
![image](https://github.com/user-attachments/assets/bedb7f01-2435-4379-99fc-e79cb7a308ab)

I do not have the variable accountabilty. My setting is it correct trigger?

**Comment by domdus** [comment]
The trigger setting is correct.
The screen you posted shows a sort of internal event, where directus tracks `last_page` (it happens of every navigation).
You will not get $accountabilty for this as it is not a change, that someone (a user) actively performed.

1.  Go to /users, select some user and modify any fields -> email, first_name, last_name
2.  Save changes
3.  In flow log, look for the one event where payload contains email, first_name, last_name. This t is the change performed by you (`$accountabilty`)
<img width="527" alt="image" src="https://github.com/user-attachments/assets/9ef03f74-4996-495b-8d32-ace0883335cc">

**Comment by JeremyMAQUAIRE** [comment]
Following your instructions I still don’t have the variable accountablity.
Can you make me a screen of your trigger setting?

**Comment by JeremyMAQUAIRE** [comment]
![image](https://github.com/user-attachments/assets/eb20fcd6-910e-4a5e-a8f2-ecb90b9a761a)

**Comment by JeremyMAQUAIRE** [comment]
![image](https://github.com/user-attachments/assets/7d29f8a8-2370-413b-913d-484586db0053)
![image](https://github.com/user-attachments/assets/d109273a-5c4a-49c4-a625-1cc3ccefe4b2)
![image](https://github.com/user-attachments/assets/e23fbeac-cee2-4aaf-9dcd-78b5ed142549)


I finally found the info. However how to retrieve it in the script of the next step?

**Comment by paescuj** [comment]
Hey @JeremyMAQUAIRE, you can retrieve the ID of the modified user in the "Run Script" operation via `data.$trigger.keys[0]` as explained by @domdus in https://github.com/directus/directus/issues/23603#issuecomment-2336779657.

Please join our Discord server and ask for help over there if you have any additional questions. Issues on GitHub are reserved for discussing feature requests and bugs, see https://docs.directus.io/contributing/community.html#online-community. Thank you!

Thanks @domdus for your help here ❤️

**Comment by JeremyMAQUAIRE** [comment]
@domdus
hi for recup the id, when I modify a user j have 4 logs in the log. in 1 j have the right info but in the script I get the info of 2. you know why?
![image](https://github.com/user-attachments/assets/c6282018-6446-43e2-9e84-79ef74d52d2b)

**Comment by domdus** [comment]
> when I modify a user j have 4 logs in the log. in 1 j have the right info but in the script I get the info of 2

All(!) events will hit your Run Script operation, also irrelevant ones.
You now need to figure out how to filter & handle only the ones you're looking for.
- If payload contains fields like `title`, `email` -> this was a modifcation -> do something
- If payload contains something different like `last_page` -> this is not a relevant modifcation -> ignore it

Check my first comment on how to do it with Run Script: https://github.com/directus/directus/issues/23603#issuecomment-2336779657

**Comment by JeremyMAQUAIRE** [comment]
Thank you for your patience and I’m beginning to understand the principle. last question once the id recovers how do I retrieve the mail corresponding to this id?
![image](https://github.com/user-attachments/assets/dc11920d-bc42-43a4-835f-3508ff7ef111)

**Comment by domdus** [comment]
- Add a Read Data operation
- Click the `{ }` icons to manually input the collection (directus_users) and the IDs (keys)
<img width="734" alt="image" src="https://github.com/user-attachments/assets/d4df0497-4fe5-4d0f-888f-879d59497bc3">

**Comment by JeremyMAQUAIRE** [comment]
It's done....thanks you very very very much....

**Comment by JeremyMAQUAIRE** [comment]
![image](https://github.com/user-attachments/assets/b436c738-e165-4439-8b74-774c3d920887)
![image](https://github.com/user-attachments/assets/6d324762-361c-4e62-8941-7f4b81d8f625)
Last little question, in the read data tab, I get back the mail that I want to integrate into the JSON of the url. How I fit it

**Comment by domdus** [comment]
>  I get back the mail that I want to integrate into the JSON of the url. How I fit it

You have two options:

1. In your case - Read Data operation is the "last" one before the webhook/fetch. 
So you can get the email from Read Data result with: `{{$last.email}}`

2. Each operation has unique `key` option on top. See screen below, here the key is: `item_read_6th0e`
You can access the result of that operation (or any other) with the key: {{item_read_6th0e.email}}
<img width="527" alt="image" src="https://github.com/user-attachments/assets/5747cac1-0cc0-4236-a166-9451abc322dc">
