### ISSUE TITLE
Something is wrong with this instance’s server or database.  Try again later or login to another instanc

### ISSUE THREAD

**Issue by GaneshKandu** [directus/directus#2360]
# Bug Report

## Steps to Reproduce

1. Go to 'admin/index.html#/collections'
2. Enter email user and password
3. Press enter

## Expected Behavior
Successful login after entering correct user and password 
## Actual Behavior
Should get logined

## Other Context & Screenshots

![Directus](https://user-images.githubusercontent.com/12833130/57275494-5ee8fa00-70bc-11e9-8ac1-6af1db6bccbd.png)
[error.2019-05-07.log](https://github.com/directus/directus/files/3151022/error.2019-05-07.log)

## Technical Details

- Device: Desktop
- OS: Windows
- Web Server: Apache 2.4.39
- PHP Version: 7.1.28
- Database: 5.7.26
- Install Method: 190503A using web browser

**Comment by benhaynes** [comment]
Thanks @GaneshKandu — this is almost certainly an issue with your configuration/stack.

I'll close this as it's definitely not an actual bug with the login code. If you need more help setting up Directus please reach out over Slack:

https://directus.chat

**Comment by alexgenovese** [comment]
Hello, 

I'm getting the same issue. 
I have checked:
- Apache configurations
- installed aws/aws-sdk-php 

It seems nothing is changed.
How can I fix that? 

Thanks

**Comment by rijkvanzanten** [comment]
@alexgenovese also make sure you have all the required php extensions and that your apache user has write permissions to the logs and public folders of Directus

**Comment by alexgenovese** [comment]
I attached some screenshots 

![Schermata 2019-09-03 alle 16 45 07](https://user-images.githubusercontent.com/423745/64183571-5e921d00-ce6a-11e9-93f0-4d741b603d6e.png)
![Schermata 2019-09-03 alle 16 44 14](https://user-images.githubusercontent.com/423745/64183570-5e921d00-ce6a-11e9-9ffd-ee2778516b14.png)
![Schermata 2019-09-03 alle 16 41 27](https://user-images.githubusercontent.com/423745/64183568-5e921d00-ce6a-11e9-9095-de44d1ccfe67.png)
![Schermata 2019-09-03 alle 16 45 31](https://user-images.githubusercontent.com/423745/64183572-5f2ab380-ce6a-11e9-8b5f-52f88eeaeeb4.png)

**Comment by ateymoori** [comment]
Same Issue with the latest version. I am getting this error and can not use the portal anymore.
It's happened after saving new Role and Permission changes.

**Comment by leonsranjit** [comment]
I am also experiencing same issue after I made changes to the directus system group permissions for a newly created role group

**Comment by lucaswerner90** [comment]
Also facing the same issue after creating a new role with different directus system permissions.

**Comment by asaurina** [comment]
Go to the database and verify that your user has an administrator role.
