### ISSUE TITLE
Axios in a flow with run script module

### ISSUE THREAD

**Issue by JeremyMAQUAIRE** [directus/directus#23619]
### Describe the Bug

I found information but none allowed me to solve my problem.
I created a direct stream giving me a JSON with 2 object. I want to use axios to send an email with the info of the 2 objects (loop with BREVO endpoint API for sending). he will be able to have many more objects.

Thanks for the help to use axios in a run script module.

![image](https://github.com/user-attachments/assets/65d7070f-4970-428c-9669-ae9c5b62ac1f)

### Directus Version

v11.0.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL

**Comment by paescuj** [comment]
As outlined in https://docs.directus.io/app/flows/operations.html#run-script the "Run Script" operations is fully sandboxed for security reasons, which means neither external modules can be used nor network request can be made.

Please use the "Request URL" operation for that instead, see https://docs.directus.io/app/flows/operations.html#webhook-request-url.

**Comment by JeremyMAQUAIRE** [comment]
Thank you for these precisisons, how to create a loop on a "Request URL"

**Comment by paescuj** [comment]
As already mentioned in https://github.com/directus/directus/issues/23603#issuecomment-2338001372, please join our [Discord](https://directus.chat/) server and ask questions there. GitHub issues are only meant for bug reports or similar. Thank you!
