### ISSUE TITLE
aggregation and group by with m2m field

### ISSUE THREAD

**Issue by Poorandy** [directus/directus#23616]
### Describe the Request

how to aggregation and group by with m2m fields
e.g.  products has m2m field tags, how to get count product with grouping  by tags

### Maintenance Strategy

----------------

**Comment by paescuj** [comment]
Relational grouping is not supported, see also https://github.com/directus/directus/issues/22779#issuecomment-2176423825.

That being said, depending on what exactly you want to achieve, it may be possible to do this in another way.
You may want to join our Discord server and ask for some inputs over there: https://docs.directus.io/contributing/community.html#online-community
