### ISSUE TITLE
Streaming logs is breaking the regular REST websocket

### ISSUE THREAD

**Issue by br41nslug** [directus/directus#23625]
### Describe the Bug

The introduction of the logs streaming endpoint (on path `/websocket/logs`) is interfering with the pre-existing REST websocket endpoint (on path `/websocket`). When connecting to the old websocket no authentication confirmation is ever received!

Current workarounds:
- Disable streaming logs (`WEBSOCKETS_LOGS_ENABLED=false`)
- ~Change the REST websocket path (`WEBSOCKETS_REST_PATH="/different"`)~

Example code:
```js
const socket = new WebSocket("ws://localhost:8055/websocket");
console.log("Socket initialized");

socket.addEventListener("open", () => {
  console.log("Socket open");

  socket.send(
    JSON.stringify({
      type: "auth",
      access_token: "<credentials>",
    })
  );
});

socket.addEventListener("message", (msg) => console.log("message received", msg.data));
socket.addEventListener("close", () => console.log("socket closed"));
socket.addEventListener("error", () => console.log("socket error!"));
```

Expected result (version 11.0.2):
![image](https://github.com/user-attachments/assets/1d24aee0-8731-4367-81b7-e08f2552b214)

Current result (version 11.1.0):
![image](https://github.com/user-attachments/assets/ab2574bd-085a-4b32-bce8-ce8ee61c37fd)

### To Reproduce

- Ensure that both websockets REST and logs streaming are enabled (they are by default)
- use the above script (or any other method) to connect to the rest websocket
- no authentication confirmation will ever be received

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Postgress

**Comment by AlphaMoonbaseBerlin** [comment]
We are having this issue also on the DirectusCloud and as it seems currently no way of disaling the streamingLogs.

**Comment by ArcanDemirci** [comment]
To reproduce, make sure that there is no “directus_session_token” in the cookies.

**Comment by br41nslug** [comment]
> I even tried to change the endpoint name as was first indicated, but nothing change... Is there something else I missed to do in order to workaround this issue or do I have to downgrade to 11.0.2?

If the workaround doesnt work then downgrading till the fix is merged and released is the last option im afraid

**Comment by zguig52** [comment]
Just tried latest version, I can confirm that it works now (with and without websocket logs enabled).
Thanks a lot!!
