### ISSUE TITLE
Streaming logs app-side configuration 

### ISSUE THREAD

**Issue by br41nslug** [directus/directus#23623]
### Describe the Bug

When disabling the streaming logs feature using `WEBSOCKETS_LOGS_ENABLED=false` the app does not disable the frontend module for this feature. I'd expect either the menu item for this not to be rendered or the page to throw a warning/error notifying that this feature is disabled.

~~Secondly when changing the streaming logs endpoint path using `WEBSOCKETS_LOGS_PATH="/logs"` this does not currently get propagated to the app because this information is missing from the `/server/info` endpoint. Currently changing the logs path will happily update the backend path but the app will keep connecting to the default `/websocket/logs` path.~~

### To Reproduce

- set `WEBSOCKETS_LOGS_ENABLED: false`
- open the app > settings > logs
- this page still renders as usual and tries to connect to the disabled socket

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgress

**Comment by licitdev** [comment]
Setting `WEBSOCKETS_LOGS_ENABLED="false"` should hide the system log module as shown. 🤔 

![image](https://github.com/user-attachments/assets/048a41f3-3b32-4602-bd93-4fcb701e9f9e)
