### ISSUE TITLE
Sass mixed-decls deprecation warnings

### ISSUE THREAD

**Issue by EdwardLi-coder** [directus/directus#23630]
### Describe the Request

When I run the command pnpm --filter app dev, I encounter too many Deprecation Warnings like this
```
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

   ╷
65 │ ┌     &::after {
66 │ │         width: 16px;
67 │ │         height: 16px;
68 │ │     }
   │ └─── nested rule
69 │       pointer-events: none;
   │       ^^^^^^^^^^^^^^^^^^^^ declaration
   ╵
    src/styles/lib/_mapbox.scss 69:2  @import
    src/styles/main.scss 10:9         root stylesheet

Sourcemap for "/Users/lifei/WebstormProjects/directus/sdk/dist/index.js" points to missing source files
```

### Maintenance Strategy

I can follow these rules in the [Sass documentation](https://sass-lang.com/d/mixed-decls) to resolve the issue

**Comment by paescuj** [comment]
Thanks for opening the issue! The warnings were bothering me as well, so I've submitted a PR to fix it 👌

**Comment by EdwardLi-coder** [comment]
> Thanks for opening the issue! The warnings bothered me too, so I've submitted a PR to fix it 👌



> Thanks for opening the issue! The warnings bothered me too, so I've submitted a PR to fix it 👌

I initially planned to submit a PR to resolve the issue directly, but I wasn't entirely sure if it was necessary, so I created an issue instead. I didn't expect you to resolve it so quickly! 😁 Regardless, we're all working together to make Directus even better.
