### ISSUE TITLE
Use data coming from a pull stream in body URL query weeb

### ISSUE THREAD

**Issue by JeremyMAQUAIRE** [directus/directus#23638]
### Describe the Bug

Hello,

I trigger a stream to get an array of objects and send it to another stream.
How can we use this data in the 2nd feed to fill the body of the webhook/URL request.

I didn’t get a response on discord
Thank you for your help.

### Directus Version

V11

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Seems like you missed my response: https://discord.com/channels/725371605378924594/1151320093565927504/1283048246012547132
Additionally, I've just posted another resource, see https://discord.com/channels/725371605378924594/1151320093565927504/1283449396624756757

Let's keep such discussions on Discord. Thank you!
