### ISSUE TITLE
EXTENSIONS_AUTO_RELOAD does not work

### ISSUE THREAD

**Issue by BorisKamp** [directus/directus#23649]
### Describe the Bug

Using Docker self hosted, running locally in docker, when I add `EXTENSIONS_AUTO_RELOAD` to my `docker-compose.yml`, it does say `directus-1  | [11:06:20.241] INFO: Watching extensions for changes...`, but when I change something in one of my extensions `index.ts` file, it does not reload?

Is this a bug?``

> 

### To Reproduce

Fire up directus self hosted, create a endpoint extension, add `EXTENSIONS_AUTO_RELOAD` and see if it auto reloads?

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgres

**Comment by ComfortablyCoding** [comment]
I cannot reproduce this issue.

`EXTENSIONS_AUTO_RELOAD` watches for changes in the package(s) `dist` folder, it will not rebuild your extension on changes to `.ts` files. To watch for file changes on `.ts` you need to use the `dev` command (or equivalent) on the respective package which adds the `--watch` flag.

If you are on windows see https://github.com/directus/directus/issues/18721
