### ISSUE TITLE
How does uploading files (to collection) work?

### ISSUE THREAD

**Issue by thepurpleblob** [directus/directus#2364]
I want a collection that contains an image. I can see that this is done by adding a field that links to directus_files using a relation. However, I can't get it to work. It just tells me that the (required) field is blank. 

Is there any documentation for setting up this scenario? I can't find anything...

**Comment by benhaynes** [comment]
I don't really understand your question. Are you just saying that you can't get the `file` interface to work?

**Comment by rijkvanzanten** [comment]
Use the `file` interface

**Comment by thepurpleblob** [comment]
No... I don't really see what the file interface is for. So I suspect that's not what I need. 

In the (admin) App. How does one create a collection that contains an uploaded image. There is an option for a 'file' field but I can't get it to work. When populating the collection through the App interface - I haven't got as far as the api yet - it doesn't work. It always says that a required field is blank.

**Comment by benhaynes** [comment]
It seems like you should go through the docs a bit more to learn the different pieces of Directus:

https://docs.directus.io/getting-started/concepts.html#interface

Directus is just a database wrapper, so you should understand how a relational database works first.

* Database (Project)
  * Table (Collection)
    * Column (Field)
      * UI (Interface)

You don't add a file to a collection, you would add it to an _item_ within the collection.

**Comment by thepurpleblob** [comment]
Ok - I'm (amongst other things) a DB admin, so I know how they work.  It's still not answering my confusion. I'm sorry if I'm not asking a sensible question. 

The file field appears to be a foreign key to Directus's file system - the directus_file table. What I'm saying is that I can't get this to work through the app.

**Comment by thepurpleblob** [comment]
<img width="688" alt="Screenshot 2019-05-10 at 17 10 35" src="https://user-images.githubusercontent.com/664139/57541364-bb5f4a00-7346-11e9-8300-d07b6fa0af8c.png">

<img width="679" alt="Screenshot 2019-05-10 at 17 10 54" src="https://user-images.githubusercontent.com/664139/57541376-c1edc180-7346-11e9-905c-e4aa6b614836.png">

So, I create a new record...

<img width="734" alt="Screenshot 2019-05-10 at 17 11 50" src="https://user-images.githubusercontent.com/664139/57541396-ce721a00-7346-11e9-8a37-b37bf9cfe4de.png">

Click the tick and I get the 'required field is blank' error

Log says.... 

[2019-05-10 17:11:35] api[_].ERROR: Directus\Validator\Exception\InvalidRequestException: status: This value should not be blank. in /home/collection/directus/src/core/Directu
s/Services/AbstractService.php:188

What am I missing / not understanding / not reading / being stupid about?

**Comment by rijkvanzanten** [comment]
![Screen Recording 2019-05-10 at 12 09 05 PM](https://user-images.githubusercontent.com/9141017/57541609-66f3a480-731d-11e9-8a8a-a83d77489d97.gif)

This isn't working for you

**Comment by rijkvanzanten** [comment]
```
Click the tick and I get the 'required field is blank' error

Log says....

[2019-05-10 17:11:35] api[_].ERROR: Directus\Validator\Exception\InvalidRequestException: status: This value should not be blank. in /home/collection/directus/src/core/Directu
s/Services/AbstractService.php:188
```

Add a value to the status field; the error is unrelated to the file interface :)

**Comment by benhaynes** [comment]
As Rijk mentioned, this field should not be optional or blank:

![Screen Shot 2019-05-10 at 12 18 28 PM](https://user-images.githubusercontent.com/522079/57541772-c8b40e80-731d-11e9-8dc5-c9561ca8cd49.png)

@rijkvanzanten perhaps we should _force_ this interface to be required since clearly it's needed for permissions (or something)?

**Comment by thepurpleblob** [comment]
@rijkvanzanten Yep - I'm saying that doesn't work. However, it doesn't say *which* field is missing, so I might have messed up something else. Hang on....

**Comment by thepurpleblob** [comment]
D'oh... you're right. I didn't tick the status box. 

It would help *a lot* if it said which was the missing field ;-)

**Comment by rijkvanzanten** [comment]
Wellll, it did say `status: This value should not be blank.` 😁 Although when the field is named status, it's easy to mistake that for a system status

**Comment by thepurpleblob** [comment]
@rijkvanzanten That's exactly what threw me :-D

Anyway... onwards. Thanks very much for your help and patience!

**Comment by benhaynes** [comment]
Ref: https://github.com/directus/app/issues/834
