### ISSUE TITLE
DB_CHARSET conflict between .env, 10 to 11 migrations and queries on M2A relationships (MySQL 8)

### ISSUE THREAD

**Issue by martabitbrain** [directus/directus#23648]
### Describe the Bug

I have reasons to believe not everything on directus system is taking into account the new collation requirements for the mysql2 driver implementation. Or maybe the system is not really prepared to work with mysql2 driver and MySQL v8+, I'm not really sure.

I'll detail here what I found out during the last two days.

## 1. Setting up a new collection fails
New collections cannot be added when a collation different from `UTF8_GENERAL_CI` is specified con the DB_CHARSET env variable. (From documentation: https://docs.directus.io/self-hosted/config-options.html#database)

## 2. Database migration from 10.12.1 to 11.x fails
If the the migration from 10.x to 11.x is executed after setting this variable with the new value (utf8mb4_0900_ai_ci on this case with MySQL 8), the migration fails.

## 3. Navigating M2A relationships fails
Navigating M2A relationships fails on MySQL 8 databases if DB_CHARSET is not set to utf8mb4_0900_ai_ci.

## Conclusion

- If I want to create collections, I have to comment `DB_CHARSET="utf8mb4_0900_ai_ci"` variable and restart directus.
- If I want to run queries that use M2A relationships, I have to uncomment `DB_CHARSET="utf8mb4_0900_ai_ci"` variable and restart directus.

Is this working as intended?

## 1. Setting up a new collection fails

**1. Define the connection parameters with default mysql8 collation utf8mb4_0900_ai_ci**
```
DB_CHARSET = "utf8mb4_0900_ai_ci"
```

**2. Try to create a collection**

Create a minimal collection "test_collection" with default values. An error is displayed and the collection creation fails:

```
{
  "errors": [
    {
      "message": "create table `test_collection` (`id` int unsigned not null auto_increment primary key) default character set utf8mb4_0900_ai_ci - Unknown character set: 'utf8mb4_0900_ai_ci'",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

## 2. Database migration from 10.12.1 to 11.x fails
**1. Update directus to latest**
**2. Run database migration**
```
$ npx directus database migrate:latest
[10:28:02.830] INFO: Skipping CLI extensions initialization due to outstanding migrations.
[10:28:02.850] INFO: Running migrations...
[10:28:02.876] INFO: Applying Permissions Policies...
[10:28:02.892] ERROR: create table `directus_policies` (`id` char(36), `name` varchar(100) not null, `icon` varchar(64) not null default 'badge', `description` text, `ip_access` text, `enforce_tfa` boolean not null default '0', `admin_access` boolean not null default '0', `app_access` boolean not null default '0', primary key (`id`)) default character set utf8mb4_0900_ai_ci - Unknown character set: 'utf8mb4_0900_ai_ci'
    err: {
      "type": "Error",
      "message": "create table `directus_policies` (`id` char(36), `name` varchar(100) not null, `icon` varchar(64) not null default 'badge', `description` text, `ip_access` text, `enforce_tfa` boolean not null default '0', `admin_access` boolean not null default '0', `app_access` boolean not null default '0', primary key (`id`)) default character set utf8mb4_0900_ai_ci - Unknown character set: 'utf8mb4_0900_ai_ci'",
      "stack":
          Error: create table `directus_policies` (`id` char(36), `name` varchar(100) not null, `icon` varchar(64) not null default 'badge', `description` text, `ip_access` text, `enforce_tfa` boolean not null default '0', `admin_access` boolean not null default '0', `app_access` boolean not null default '0', primary key (`id`)) default character set utf8mb4_0900_ai_ci - Unknown character set: 'utf8mb4_0900_ai_ci'
              at Packet.asError (/var/www/cms-help-center/node_modules/mysql2/lib/packets/packet.js:738:17)
              at Query.execute (/var/www/cms-help-center/node_modules/mysql2/lib/commands/command.js:29:26)
              at Connection.handlePacket (/var/www/cms-help-center/node_modules/mysql2/lib/connection.js:481:34)
              at PacketParser.onPacket (/var/www/cms-help-center/node_modules/mysql2/lib/connection.js:97:12)
              at PacketParser.executeStart (/var/www/cms-help-center/node_modules/mysql2/lib/packet_parser.js:75:16)
              at Socket.<anonymous> (/var/www/cms-help-center/node_modules/mysql2/lib/connection.js:104:25)
              at Socket.emit (node:events:517:28)
              at addChunk (node:internal/streams/readable:368:12)
              at readableAddChunk (node:internal/streams/readable:341:9)
              at Readable.push (node:internal/streams/readable:278:10)
      "code": "ER_UNKNOWN_CHARACTER_SET",
      "errno": 1115,
      "sqlState": "42000",
      "sqlMessage": "Unknown character set: 'utf8mb4_0900_ai_ci'",
      "sql": "create table `directus_policies` (`id` char(36), `name` varchar(100) not null, `icon` varchar(64) not null default 'badge', `description` text, `ip_access` text, `enforce_tfa` boolean not null default '0', `admin_access` boolean not null default '0', `app_access` boolean not null default '0', primary key (`id`)) default character set utf8mb4_0900_ai_ci"
    }
```

**3. Extra: Correct DB_CHARSET needed to navigate M2A relationships**

If the DB_CHARSET is not set, running a query that navigates a M2A relationship throws an `Illegal mix of collations` error when perfoming the "CAST":

Query & log: 
```
Error: select `product_versions`.`item`, `product_versions`.`collection`, `product_versions`.`product_id`, `product_versions`.`sort`, `product_versions`.`id` from `product_versions` left join `software_version` as `urzbk` on `product_versions`.`collection` = 'software_version' and `product_versions`.`item` = CAST(`urzbk`.`id` AS CHAR(255)) where (`urzbk`.`status` = 'published' and `product_versions`.`product_id` in (27, 28, 36, 37, 10, 11, 24)) order by `product_versions`.`sort` asc limit 25000 - Illegal mix of collations (utf8mb4_0900_ai_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
```

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Custom), Also tested in Docker (same outcome)

### Database

MySQL 8.039, MySQL 8.2.0

**Comment by paescuj** [comment]
Hey, thanks for opening the issue!

The charset is actually just `utf8mb4`, that's why your MySQL server errors out with `Unknown character set: 'utf8mb4_0900_ai_ci'`.
To use `utf8mb4_0900_ai_ci` as the collation, I think you need to set the following config option (I know, the naming is a bit confusing):
```ini
# Mapping from here: https://github.com/sidorares/node-mysql2/blob/3d2327d683254ad3642b9c3644ebc486dab7797e/lib/constants/charsets.js#L227
DB_CHARSET_NUMBER=255
```

Under the assumption that this will solve your problem, I'll proceed to close this issue for now. Happy to keep discussing in this thread, and we'll reopen if it turns out to be a different issue 👍🏻

**Comment by martabitbrain** [comment]
Thanks @paescuj , I'll check it right now. Maybe the entry on the documentation table got me confused, It seemed that DB_CHARSET and DB_CHARSET_NUMBER where synonims, since the example value only mentions one value.

**Comment by martabitbrain** [comment]
To give this a little closure (and just in casy anyone gets confused as I was), these are the steps that I've followed:

**1. Set the correct DB_CHARSET_NUMBER**
- Removed `DB_CHARSET=...`
- Added `DB_CHARSET_NUMBER=255`

Reference provided by @paescuj, (see mysql2 library charset exports https://github.com/sidorares/node-mysql2/blob/3d2327d683254ad3642b9c3644ebc486dab7797e/lib/constants/charsets.js#L227)

_A note on the docs explaining what is DB_CHARSET_NUMBER and where it comes from could be very helpful._ 

**2. Execute database update**
```
/directus # npx directus database migrate:latest
[13:54:58.541] INFO: Skipping CLI extensions initialization due to outstanding migrations.
[13:54:58.550] INFO: Running migrations...
[13:54:58.560] INFO: Applying Update Files Date Fields...
[13:54:58.679] INFO: Applying Permissions Policies...
[13:54:59.649] INFO: Applying Update Icon Fields Length...
[13:55:00.214] INFO: Database up to date
```
Success 🥲

**3. Retrieve data from an M2A**
Success 🥲

**3. Create Collection test**
Success 🥲

Thank you again for the help @paescuj !!
