### ISSUE TITLE
Markdown field is not working

### ISSUE THREAD

**Issue by Eggwise** [directus/directus#23668]
### Describe the Bug

Markdown field doesnt work somehow.

https://www.loom.com/share/08254cc0b97e474eb5a8d8bc7c9bd685?sid=3587f57e-d749-4cd0-8559-ad084ecddc2d

I use "preview mode as default" but somehow i don't see anything and i cannot change it.

### To Reproduce

use markdown field.
See its not working

### Directus Version

11

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Postgres

**Comment by paescuj** [comment]
This has been fixed in #23599 which will be available in the next release.
