### ISSUE TITLE
The accountability property when instantiating a service does not default to admin

### ISSUE THREAD

**Issue by alchi** [directus/directus#23662]
### Page

https://docs.directus.io/extensions/services/introduction.html

### Describe the Inaccuracy

> If no accountability is provided, the service will default to using administrator permissions - you should be careful about this since endpoints are always publicly accessible. Setting accountability to null will use public permissions

Currently, the absence of the `accountability` property in the options object of the constructor defaults to `null`.
This means that the service created without `accountability` has public rights.
From source code
```
constructor(collection: Collection, options: AbstractServiceOptions) {
		this.collection = collection;
		this.knex = options.knex || getDatabase();
		this.accountability = options.accountability || null;
		this.eventScope = isSystemCollection(this.collection) ? this.collection.substring(9) : 'items';
		this.schema = options.schema;
		this.cache = getCache().cache;

		return this;
	}
```

Previously, this service would operate with admin rights
```
const itemsService = new ItemsService('collection_name', {
      schema: await getSchema()
});
```
Now to achieve the same, one would initialize a service like this
```
const itemsService = new ItemsService('collection_name', {
      schema: await getSchema(),
      accountability: {
                admin: true
            }
});
```

**Comment by hanneskuettner** [comment]
Having an accountability of `null` does not mean the service is created with public access. The user only has public level access if there are no roles present in the `accountability` object. Instead, an `accountability` of `null` indicates "system-level" access, which in the sense of permissions is equal to admin level access. 

Do you see any behavior when passing in no accountability that would indicate public level access?

**Comment by alchi** [comment]
@hanneskuettner after we have upgraded to 11.0.2, the service created with  `accountability:null` began to return an error 
```
ERROR: Cannot read properties of null (reading 'admin')
     err: {
      "type": "TypeError",
       "message": "Cannot read properties of null (reading 'admin')",
       "stack":
     }
```
The function which was giving the error is `updateOne` in the `ItemsService`
When we changed to `accountability:{admin:true}` the error has gone and everything works as it should

Not sure if this answers your question. But what I experienced is that `no accountability != admin level` as it was in previous versions.
The same applies to version `11.1.0` (just tested it)

**Comment by hanneskuettner** [comment]
Can you see where this error originates from specifically? Could it be some custom extension? Because internally not passing in an accountability during service creation is used quite extensively, so I would be surprised if this error is present in `updateOne`.

**Comment by hanneskuettner** [comment]
Do you purposefully cut of the stack of the error message? Because that is the important part that might give us a clue to understand where the error is happening.

**Comment by alchi** [comment]
@hanneskuettner that's the problem -- stack is empty, or rather it looks like I that

**Comment by hanneskuettner** [comment]
But right now the error object is not valid JSON. So I would expect something to be printed right after the `"stack":`.

**Comment by hanneskuettner** [comment]
What happens if you `JSON.stringify` the whole `err` before logging?

**Comment by alchi** [comment]
```
this.logger.error(JSON.stringify(err))
```
results in
```
[10:13:53.639] ERROR: {}
```

**Comment by alchi** [comment]
I would probably check the newer functions added when policies feature was introduced.
But anyway, if you cannot reproduce it then we can put it on hold for now.
I can try to test it on the fresh installation.
