### ISSUE TITLE
After changing sort of primary field: Primary key must be unique

### ISSUE THREAD

**Issue by u12206050** [directus/directus#23667]
### Describe the Bug

Not sure if it is specific to mysql, but it doesn't set `is_unique` to `true` from `primary keys` and so when we simply did a small update such as the sort, and do a schema snapshot and apply on a different environment, we get the following error:

```js
 err: {
      "type": "",
      "message": "Invalid payload. Primary key must be unique.",
      "stack":
          DirectusError: Invalid payload. Primary key must be unique.
              at FieldsService.updateField (file:///Users/gerardlamusse/DirectusProjects/bcc-event/cms/node_modules/@directus/api/dist/services/fields.js:392:31)
              at async file:///Users/gerardlamusse/DirectusProjects/bcc-event/cms/node_modules/@directus/api/dist/utils/apply-diff.js:163:25
      "name": "DirectusError",
      "extensions": {
        "reason": "Primary key must be unique"
      },
      "code": "INVALID_PAYLOAD",
      "status": 400
    }
```
   

### To Reproduce

Create a collection with an id field obviously.
Take a snapshot and apply it in a different db.
On first db alter the id field such as sorting it differently.
Take a new snapshot and attempt to apply to db number 2. (There has to be a change on the field in order for `updateField` to be called.

### Directus Version

11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Mysql2

**Comment by u12206050** [comment]
I would say this check can be skipped for mysql2 and possibly some other dbs

**Comment by ComfortablyCoding** [comment]
Possibly due to recent addition of https://github.com/directus/directus/blob/22738ebaff6e6726b6e3342f20ca732246c36c9c/api/src/services/fields.ts#L520
