### ISSUE TITLE
Aggregate and Filter ?

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [directus/directus#23674]
### Page

https://docs.directus.io/reference/query.html#aggregation-grouping

### Describe the Inaccuracy

So what i was trying to to is to count from a table how many items have "likes" set to true:

```ts
export type FoodsFeedbacksLabelsEntries = {
  id: string;
  food?: string | Foods | null;
  label?: string | FoodsFeedbacksLabels | null;
  dislike?: boolean | null;
};
```

So i was trying to do:

```
client.request<CollectionScheme[]>(aggregate(this.collection,{
    aggregate: {
     // Now i have no clue
    },
));
```

My idea was to countByDistinct on the ID and to filter for ```dislike: true```?

Maybe the docs can be enhanced here?

**Comment by NilsBaumgartner1994** [comment]
https://github.com/directus/directus/issues/23043
No idea what he was "sorry" for?

**Comment by hanneskuettner** [comment]
The global `filter` parameter applies to "normal" retrieval of results as well as the results considered for an aggregation. 

In the SDK this can be provided in the form of `query.filter`, like

```ts
client.request<CollectionScheme[]>(aggregate(this.collection,{
    aggregate: {
        count: '*'
    },
    query: {
        filter: {...}
    }
));
```

see https://docs.directus.io/packages/@directus/sdk/rest/functions/aggregate.html

**Comment by NilsBaumgartner1994** [comment]
I mean as a small example

**Comment by hanneskuettner** [comment]
Feel free to shoot a quick PR that improves the existing aggregation example in the docs! :)

**Comment by NilsBaumgartner1994** [comment]
@hanneskuettner can i also use readItems and as a query like in the extensionsdk?:

´´´
import type { Filter } from './filter.js';
export type Query = {
    fields?: string[] | null;
    sort?: string[] | null;
    filter?: Filter | null;
    limit?: number | null;
    offset?: number | null;
    page?: number | null;
    search?: string | null;
    version?: string | null;
    versionRaw?: boolean | null;
    export?: 'json' | 'csv' | 'xml' | null;
    group?: string[] | null;
    aggregate?: Aggregate | null;
    deep?: NestedDeepQuery | null;
    alias?: Record<string, string> | null;
};
```

**Comment by NilsBaumgartner1994** [comment]
@hanneskuettner can i also count the same field twice?

```
let result: Record<string, { amount_likes: number, amount_dislikes: number }> = {};

	for(let visibleLabel of visibleLabels) {
		console.log("visibleLabel", visibleLabel);
		// Create a query that counts entries for each visible feedback label for the given foodId
		const defaultQuery = {
			aggregate: {
				count: "*"
			},
			query: {
				filter: {
					_and: [
						{
							food: {
								_eq: foodId
							}
						},
						{
							label: {
								_eq: visibleLabel
							}
						},
					]
				},
			}
		};

		const queryForLikes = JSON.parse(JSON.stringify(defaultQuery));
		queryForLikes.query.filter._and.push({
			dislike: {
				_eq: false
			}
		});

		const queryForDislikes = JSON.parse(JSON.stringify(defaultQuery));
		queryForDislikes.query.filter._and.push({
			dislike: {
				_eq: true
			}
		});

		let resultForLikes = await foodCollectionHelper.aggregateItems(queryForLikes);
		let resultForDislikes = await foodCollectionHelper.aggregateItems(queryForDislikes);
```

like i want to get how many likes and dislikes are set?

**Comment by NilsBaumgartner1994** [comment]
Ah okay, thats what the groupBy is used for.

```
console.log("visibleLabel", visibleLabel);
		// Create a query that counts entries for each visible feedback label for the given foodId
		const defaultQuery = {
			aggregate: {
				count: "*"
			},
			groupBy: ['dislike'], // Groups by the dislike field (true/false)
			query: {
				filter: {
					_and: [
						{
							food: {
								_eq: foodId
							}
						},
						{
							label: {
								_eq: visibleLabel
							}
						},
					]
				},
			}
		};

		let resultForLikes = await foodCollectionHelper.aggregateItems(defaultQuery);

		console.log("-- resultForLikes", resultForLikes);
```

Result:
```
[
  {
    "dislike": false,
    "count": "1"
  },
  {
    "dislike": true,
    "count": "1"
  }
]
```
