### ISSUE TITLE
Can't find how to control collection listing

### ISSUE THREAD

**Issue by thepurpleblob** [directus/directus#2367]
I created a new collection but the list of items doesn't show anything useful...

<img width="797" alt="Screenshot 2019-05-11 at 11 35 04" src="https://user-images.githubusercontent.com/664139/57568549-e6967780-73e0-11e9-8165-1ee497b5ff80.png">

I have a 'name' text field (for example) that I'd like displayed in the list but I can't see any option for this. 

I assume it's possible as there are examples in the docs with different fields in these listings.

**Comment by rijkvanzanten** [comment]
If you hit the `(i)` icon in the top right, you'll have the ability to set what fields are displayed here and in what order 🙂 

![image](https://user-images.githubusercontent.com/9141017/57570176-53077b80-73cd-11e9-941f-30465b3c97a9.png)
