### ISSUE TITLE
Table view for content types doesn't display records

### ISSUE THREAD

**Issue by damianryann** [directus/directus#23670]
### Describe the Bug

I noticed in the latest version when I go to any content type the table view does not show content for me. If I switch to cards for example the data shows correctly. 

I have not modified any settings for my user permissions group or anything of this kind.
If you use the search it may eventually display content matching the query but this isn't always the case.

### To Reproduce

- Go to any content
- Content does not display as a table
- Open Layout Options change Table > Cards
- Content displays

<img width="1311" alt="Screenshot 2024-09-15 at 13 52 17" src="https://github.com/user-attachments/assets/3df2babd-6cd4-4e24-a735-7ab8e45ded46">
Shows data if I attempt to search a few times.

<img width="1243" alt="Screenshot 2024-09-15 at 13 52 27" src="https://github.com/user-attachments/assets/a562422b-f996-4507-8118-f6192b8bb658">
Refresh or go to by default, no data shows at all

<img width="1238" alt="Screenshot 2024-09-15 at 13 52 33" src="https://github.com/user-attachments/assets/d0373935-8f64-4b5f-9368-5e2b4a018e9c">
Change to Card view reveals data.

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 16

**Comment by hanneskuettner** [comment]
Do you see any errors in your browser console?

**Comment by damianryann** [comment]
Hi @hanneskuettner nothing in the console whatsoever.

<img width="1717" alt="Screenshot 2024-09-16 at 19 19 09" src="https://github.com/user-attachments/assets/d9ccb558-a438-4921-b8bc-11af0f6f3615">

**Comment by damianryann** [comment]
Also there is data for that particular fetch.

<img width="1720" alt="Screenshot 2024-09-17 at 07 50 13" src="https://github.com/user-attachments/assets/f1f3bdf8-7e2f-4a89-b4d6-1f3f622c4fc4">
