### ISSUE TITLE
Empty One Fields Value whenever I change Another field

### ISSUE THREAD

**Issue by venkatesh-gp** [directus/directus#23677]
### Describe the Improvement

I have fields category and sub-category.
Whenever I change category field Sub-category field should become empty and I should select the sub-category again

**Comment by hanneskuettner** [comment]
Could you please provide a detailed example setup, eg. your collections and fields, that allows us to reproduce the issue?

**Comment by venkatesh-gp** [comment]
I have four collections with fields as mentioned below

1. Category
    - Category name

2. Subcategory L1
   - Subcategory L1 Name
   - Category_id (M2O with Category Collection)
 
3. Subcategory L2
   - Subcategory L2 Name
   - Subcategory_L1_Id(M2O with Subcategory L1 Collection)

4. Taxonomy
   - Category_id(M2O with Category Collection)
   - Subcategory_L1_Id(M2O with Subcategory L1 Collection)
   - Subcategory_L2_Id(M2O with Subcategory L2 Collection)


In Taxonomy collection I've implemented a filter when category is selected respective Items in Subcategory L1 Collection will showup and When Subcategory L1 is Selected respective Subcategory L2 Collection Items will show up.

<img width="1084" alt="Screenshot 2024-09-24 at 9 24 10 AM" src="https://github.com/user-attachments/assets/51b4b2ee-d49f-4583-9b2f-d8cfc565b959">

Say If I select a Category and then its respective SubCategory L1 and then again the Category.
In this case SubCategory L1  stays as previous selected value and its not clearing out as the category is changed.

Is there any way when I select a category and then its SubCategory and again Change Category should cause SubCategory value to clear out?
