### ISSUE TITLE
Enable to translate and customize registration-wrapper 

### ISSUE THREAD

**Issue by Pachat** [directus/directus#23701]
### Describe the Bug

When the default language is other than English, we still have in English
Don't have an account? Sign up now

It would be nice also to be able to set up the Sign up now URL, for those who want a complete custom registration form.

### To Reproduce

Set `Default language` to anything else than English and refresh the login page

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
The problem, why "Sign up now", etc is not translated is probably that those translations are not available in the language you selected, so it defaults back to the default language, which is English. You can head over to our [Crowdin](https://crowdin.com/project/directus) page to help translate Directus to your language. Any translations contributed there will be automatically included in the next release.

Regarding the custom registration form: If you want to see this natively supported in Directus please file a full [Feature Request](https://github.com/directus/directus/discussions/new?category=draft-feature-requests) so it can be properly considered.

**Comment by Pachat** [comment]
Thanks for the explaination. The problem with the Crowdin link is that French is not even in the list.
There is only fr-CA which is different from fr-FR or should it be taken instead?

Also, is there a template for the login page?
Because the question about the link is still open.

Thank you for your time.

**Comment by hanneskuettner** [comment]
French is definitely in that list.

<img width="663" alt="Screenshot 2024-09-19 at 20 06 51" src="https://github.com/user-attachments/assets/96dcdca6-fdfc-4ece-8f93-6a45c66b0ae6">

There currently is no user-editable template for the register / login page. Dircetus provides you with a set up default pages that are configurable to some extend. If you want to fully customize them you will have to roll your own, or open a Feature Request.
