### ISSUE TITLE
/files route is completely public exposing all files that are "public"

### ISSUE THREAD

**Issue by u12206050** [directus/directus#23705]
### Describe the Bug

Visiting a directus instance's url with `/files` displays a list of all files that are publicly accessible! The intention is of course that those files can be accessed by just knowing their id, but the thought was the id isn't simply shared with anyone, that is of course we realised that anyone can just request the `/files` directory and view all those files!

### To Reproduce

Update a few files that you might think you can share with only those who you want, but since view the `yourdomain.com/files` url and see all those files!

### Directus Version

11

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

N/A

**Comment by br41nslug** [comment]
Files that have public read permissions are publicly accessible very much by design 😬 If the listing of files is the underlying issue there is a feature request to add listing permissions to address this here https://github.com/directus/directus/discussions/11464
