### ISSUE TITLE
Insight - Line Diagram - Step Size?

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [directus/directus#23725]
### Describe the Improvement

So what i have is the balance on a card of students. This balance ranges from 0-75€. I am able to display them but i would like group them by 1€ steps.
Currently it goes by every found mini step... any ideas how to make this work?

<img width="1044" alt="Bildschirmfoto 2024-09-24 um 02 47 24" src="https://github.com/user-attachments/assets/a3aba2f5-977c-4c0e-966e-5c3283e7ad5d">

**Comment by rijkvanzanten** [comment]
There's currently no way to set rounding to nearest values on individual lines in the line chart. [Feel free to open a new feature request though](https://github.com/directus/directus/discussions/new?category=draft-feature-requests)!
