### ISSUE TITLE
Is it possible to (a) bulk upload table items from a CSV file and/or (b) bulk upload files as a single zip?

### ISSUE THREAD

**Issue by thepurpleblob** [directus/directus#2372]
I suspect the answer is currently no...

If there isn't anything existing to do either of these things, I'd appreciate some pointers in extending the app to do so. I read https://docs.directus.io/extensions/#extension-types and nothing really leaps out at me as the obvious type of extension.

**Comment by benhaynes** [comment]
Directus is just a database wrapper, so you can use _any_ tool to import data into SQL and Directus will work with that migrated data.

You can easily bulk upload files to the server (Directus' upload directory) but there is no way yet to process those into `directus_files` items. I'd 👍 a feature request for that though!

Ref:
https://github.com/directus/app/issues/711
https://github.com/directus/app/issues/765

**Comment by thepurpleblob** [comment]
Ok - but it's not really the question I was asking. 

Rather than adding all of this functionality to my own application on the client side I was scoping out how straightforward it would be to extend the Directus app to do this (me doing it that is). As I've not written a line of Directus code a nudge in the right direction or examples of similar extensions would be useful. Or even, "that's crazy, it'll be really difficult to do"

**Comment by benhaynes** [comment]
If this isn't a recurring thing then you could write a stand-alone script that has nothing to do with Directus. Or, if it will be something that happens more often you'd want to create a custom API endpoint that you can call:

https://docs.directus.io/extensions/custom-endpoints.html

Parse the CSV and [insert items ](https://docs.directus.io/advanced/api/data.html) into the database. Or upload files and then write a script to add the `directus_files` items. Shouldn't be too crazy... but it completely depends on what your data looks like.

**Comment by thepurpleblob** [comment]
Ok thanks. Makes sense. I'll have a go at that.

**Comment by dataexcess** [comment]
> Directus is just a database wrapper, so you can use _any_ tool to import data into SQL and Directus will work with that migrated data.
> 
> You can easily bulk upload files to the server (Directus' upload directory) but there is no way yet to process those into `directus_files` items. I'd 👍 a feature request for that though!
> 
> Ref:
> https://github.com/directus/app/issues/711
> https://github.com/directus/app/issues/765

Hi I am also in need of this. Will this feature ever be implemented? Basically I am installing Directus on top of an existing database which has a table images where some field is the 'path' to some (not-in-the-directus-directoy) place on the server's filesystem. 
I would like to have those existing images show up in the directus File Library, so that I can take advantage of the Directus thumbnail features etc.

Is this really only possible by uploading all those images one by one through the interface? Or is there another way :) 

Thank you!

**Comment by diegoleme** [comment]
Does that solve it?
https://docs.directus.io/reference/system/utilities/#import-data-from-file
