### ISSUE TITLE
Donut Chart Coloring

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [directus/directus#23721]
### Describe the Request

Maybe i oversee something but you can choose the color of the segments: https://docs.directus.io/user-guide/insights/charts.html#pie-or-donut-chart

But what i would like is to use coloring for the primary keys. For example I want a chart with:

Users Providers: Google vs. Apple

And therefore i would like to color it in specific colors, depending on the value "google" or "apple" of the Directus Users Provider.

### Maintenance Strategy

Is it possible to use dynamic values here too?

**Comment by rijkvanzanten** [comment]
It's not currently possible to set the colors based on the value, but make sure to [open a feature request for it](https://github.com/directus/directus/discussions/new?category=draft-feature-requests)! 🙂
