### ISSUE TITLE
Filtering items that have all specified related items (many-to-many relation) does not work

### ISSUE THREAD

**Issue by coeing** [directus/directus#23732]
### Describe the Bug

Unfortunately I just found those old issues, but they describe the issue pretty well:
https://github.com/directus/v8-archive/issues/967

The `and` filter was one of my first tries as well, but it returns an empty result. 

### To Reproduce

Please check https://github.com/directus/v8-archive/issues/967 for good use cases (posts & tags).

### Directus Version

v10.12.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 14

**Comment by br41nslug** [comment]
Unfortunately i cannot reproduce the issue using the linked issue. The linked issue is a feature request and was for a different platform (Directus was completely rewritten in v9).

There are a few things raised in the comments of the linked issue but im not directly sure what the exact issue is you are running into or the exact filters that are failing for you.

Please describe the issue you're running into for the current version.

**Comment by Disura-Randunu** [comment]
@coeing Have you tried using ``` _in ``` operator? You may need to try out that as well
```
"_and": [
      { 
           "tags": { "_in": ["TagA_ID"] } 
      },
      {    
           "tags": { "_in": ["TagB_ID"] } 
      },
      { 
           "tags": { "_in": ["TagC_ID"] }
      }
]
```

**Comment by dkophelyi** [comment]
I have the exact same problem.

**Comment by br41nslug** [comment]
Duplicate of #20614

**Comment by coeing** [comment]
> @coeing Have you tried using `_in` operator? You may need to try out that as well
> 
> ```
> "_and": [
>       { 
>            "tags": { "_in": ["TagA_ID"] } 
>       },
>       {    
>            "tags": { "_in": ["TagB_ID"] } 
>       },
>       { 
>            "tags": { "_in": ["TagC_ID"] }
>       }
> ]
> ```

@Disura-Randunu Thanks for your idea. Unfortunately this does not work either. 

@br41nslug Thanks for referencing the other issue, I will follow that one and hope that there will be a solution soon 👍
