### ISSUE TITLE
Insight Dashboards - Panels Move Multiple

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [directus/directus#23738]
### Describe the Improvement

When creating the dashboards, sometimes i want to "insert" a new panel on top. Is there a way to move all other down, without moving every one by one?

**Comment by rijkvanzanten** [comment]
There's no way to do that currently, but I'd love [a new feature request](https://github.com/directus/directus/discussions/new?category=draft-feature-requests) to get that added to the queue 🙂
