### ISSUE TITLE
cloudflare r2 not working 

### ISSUE THREAD

**Issue by anisafifibd** [directus/directus#23733]
### Describe the Bug

This is my selfhosted directus docker compose storage configuration here local work but Cloudflare R2 (S3-compatible) not work someone plese help me

      ` # assets uploading configuration
      STORAGE_LOCATIONS: "local,s3"

      # Local storage configuration
      STORAGE_LOCAL_DRIVER: "local"
      STORAGE_LOCAL_ROOT: "./uploads"

      # Cloudflare R2 (S3-compatible) configuration
      STORAGE_S3_DRIVER: "s3"
      STORAGE_S3_KEY: "79******f" 
      STORAGE_S3_SECRET: "0*****19"
      STORAGE_S3_REGION: ""
      STORAGE_S3_BUCKET: "self-branding-public" 
      STORAGE_S3_ENDPOINT: "https://*******/bucket"`

### To Reproduce

not know what to do

### Directus Version

v11.0.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by jamaluddinrumi** [comment]
i can confirm these setting works for my directus@11.1.1 self-hosted version without docker image:

first, you must double check your R2 Token, generate it on https://dash.cloudflare.com/?to=/:account/r2/api-tokens
two, R2 Endpoint, it must be **without** slash following pathname,
three, R2 Region (e.g. apac,us-west-1,etc), https://developers.cloudflare.com/r2/reference/data-location/#available-hints choose one.

```.env
STORAGE_LOCATIONS="s3"
STORAGE_S3_DRIVER="s3"
STORAGE_S3_KEY="[CLOUDFLARE_R2_TOKEN_ACCESS_KEY_ID]"
STORAGE_S3_SECRET="[CLOUDFLARE_R2_TOKEN_SECRET_ACCESS_KEY]"
STORAGE_S3_BUCKET="[R2_BUCKET_NAME]"
STORAGE_S3_REGION="[R2_REGION]"
STORAGE_S3_ENDPOINT="https://xxxxxxxx.r2.cloudflarestorage.com"
```

**Comment by twodft** [comment]
If you config `STORAGE_LOCATIONS: "local,s3"` then it will use local first, you should remove the local and use s3 only. 

`STORAGE_LOCATIONS: "s3"`
