### ISSUE TITLE
Retrieve Item subset in JS SDK

### ISSUE THREAD

**Issue by phoenixtechnam** [directus/directus#2373]
Hi, 

Is it possible to request all items in a collection while receiving only specific fields ? 
The default getItems() returns all items and fields which may be slow for items with many fields in large collections. 
filter: {} blocks out items but not fields or am I missing something ?

Example:

collection PROJECTS structure:
**ID  NAME  DESCRIPTION  DATA**

I want to request a list of ALL projects, NOT transmitting the DATA field which may be large in size.

Thanks

**Comment by benhaynes** [comment]
Yeah, you can use the fields parameter:

https://docs.directus.io/api/reference.html#fields
