### ISSUE TITLE
Impossible to read directus_users table in a flow

### ISSUE THREAD

**Issue by dlepaux** [directus/directus#23742]
### Describe the Bug

The Directus Flows don't allow to **READ** the `directus_users` table anymore !
I need to send an email to a user. It's as simple as that. 
We should be able to read anything within those flows by the way, all directus tables should be accessible by flows.

### To Reproduce

Create a Flow in directus: `Read Data`.

Manually add `directus_users` table (it's not in the select list) by adding it with **Edit Raw Value**.

Then in the IDs field add the **user id** or the variable like **{{my_variable}}** (press enter to add it).

Then execute the flow and you should have this error: 
```
{
  "name": "DirectusError",
  "message": "You don't have permission to access this."
}
```

Note: Have Trigger or Full access doesn't change anything.

Here the **Options** of the Read Data:

```
{
  "key": [
    "b1cb4800-39d2-445a-a24a-847cf28d3775"
  ],
  "query": {
    "fields": [
      "id",
      "email"
    ]
  },
  "collection": "directus_users",
  "permissions": "$full"
}
```

### Other problem

I've created an API user to be able to query the user with the API. The user have an Administrator role and when I do try to get the information of the user I also have the same error. I suppose there is a misconfiguration about the Administrator role / policy that miss critical permission to function.

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

MariaDB 10.3.39

**Comment by hanneskuettner** [comment]
Are you sure the item with the id `b1cb4800-39d2-445a-a24a-847cf28d3775` actually exists in the `directus_users` table? Because from a quick test the read data operation is perfectly able to read the `directus_users` table and the error only occurs when trying to read an item that does not exist.

**Comment by dlepaux** [comment]
It appears you are right, I have an other table in between the user one... My bad.
Thanks for the quick reply.
