### ISSUE TITLE
Using role uuid as recipient for a notification fails

### ISSUE THREAD

**Issue by UPSxACE** [directus/directus#23747]
### Describe the Bug

Using a role uuid as recipient for a notification of a flow is throwing the following error:

{
    "name": "DirectusError",
    "extensions": {
        "collection": "directus_notifications",
        "field": "recipient"
    },
    "code": "INVALID_FOREIGN_KEY",
    "status": 400
}

### To Reproduce

-> Create a flow
-> Add a webhook POST trigger
-> Add a send notification trigger
-> Insert a role UUID in the field that says "Enter a UUID..." 
-> Set permissions to "Full Access"
-> Save, copy the webhook endpoint, and try it out

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Postgis 13 docker image

**Comment by hanneskuettner** [comment]
That is because the recipient of a notification can only be one or multiple users, defined by their user uuid. Using role uuids for this field is not valid, see https://docs.directus.io/app/flows/operations.html#send-notification

If you need this feature, please open a feature request.

**Comment by UPSxACE** [comment]
> That is because the recipient of a notification can only be one or multiple users, defined by their user uuid. Using role uuids for this field is not valid, see https://docs.directus.io/app/flows/operations.html#send-notification
> 
> If you need this feature, please open a feature request.

Well, I'm sorry for bothering then, but i thought [this guide ](https://learndirectus.com/how-to-send-a-notification/)was official, and it states there that we can use role UUIDs (check step 1, second paragraph)

If it is somehow official, you guys should fix it

**Comment by phazonoverload** [comment]
It isn't - only on our own docs and website will you find officially-authored content. Tim is lovely though so I'll reach and ask for that to be amended.
