### ISSUE TITLE
Self referencial table

### ISSUE THREAD

**Issue by ernie58** [directus/directus#2374]
# Feature Request
We have a table where records must be linked to other records from the same table.
Currently we've added a M2M relationship for that.

Problem is that 'direction matters', so the results differ from where you place the link.
If you have a record A and you link it to record B, and you do this action on the detailpage for A, it will:
- show up in the detail from A, in the linked list
- it will not be visibible in the linked list from detail B

In our case the desired behavior is, that it would be visible on both details A en B, only be making this reference once. Is there any way of achieving this in directus? A self-referential relation should be perfect

## What problem does this feature solve?
You could reference records from the same table without the direction matters

## How do you think this should be implemented?
A new kind of relation

## Would you be willing to work on this?
Could try to, if it would make it to the official release

**Comment by rijkvanzanten** [comment]
> only be making this reference once

Am I understanding correct that what you're looking for is a one-to-one relationship between items in the same collection? Do you have an example use case so it's easier to understand what we're trying to achieve?

**Comment by herrbomm** [comment]
Likely that could be "related" files or something like that. This is a common need from my point of view 🙄

**Comment by ernie58** [comment]
Sure,

We have a table with 'concepts'. Those 'concepts' have a title and a description, and they are used to feed a concept map visualisation, like the thing below in the image:
<img width="724" alt="Schermafbeelding 2019-05-29 om 15 39 19" src="https://user-images.githubusercontent.com/598177/58561703-fe1a9080-8227-11e9-9598-02e5d7012e6d.png">

The square are concepts, and the dots are tags.
One can select a tag, and sees all the concepts linked to it, or vice versa.
We also want to be able to link concepts directly one to another. (square to square)

Its indeed something like 'related products' or 'related files', like @herrbomm mentioned

**Comment by rijkvanzanten** [comment]
That does both sound like a many to one / one to many to me. "Thermisch uitzetten en krimpen" would have a many to one to "Materialen" which in turn allows the "Materiaal" to have a one to many (list) of items that have been connected to that one "Thermisch uitzetten en krimpen"

Linking the concepts together sounds like a many to many, as you can have many concepts connected to many other concepts. In this case you can have a many to many that uses a junction table to the same collection.

_Volgens mij zou dat moeten werken in deze situatie 🙂_

**Comment by benhaynes** [comment]
Perhaps this example should be a M2M, but we should still support self-referencing for M2O and O2M. A very common case is:

`projects.related_project` -> `projects.id`

This could be either an M2O or O2M depending on which way you want to see the data.

**Comment by rijkvanzanten** [comment]
That already works @benhaynes 🙂

**Comment by ernie58** [comment]
@rijkvanzanten In our experience, it doesn't work.
The direction from were you link 2 items matters.
When you link record A to record B (same table) the related item will show up on the detail of A, but not on the detail of B. That's because the junction table has 2 foreign keys concept_id_1 and concept_id_2. Making a relation starting from record A will fill the foreign key to record B in concept_id_2. When you go to detail of record B, the system will look for all related items that have record B filled in at concept_id_1, and vice versa...

**Comment by dev7ch** [comment]
i am not sure if understand, totally but this case sound a bit like a taxonomy concept, is this not realizable by tagging contents?

Doest it have to be real relation or would a tagging concept work as well?

https://www.keypointe.com/examples-of-website-taxonomy-how-classification-helps-on-the-web/

(btw i realized tags interface doesnt support autocompletion which would be very usefull)

**Comment by herrbomm** [comment]
> (btw i realized tags interface doesnt support autocompletion which would be very usefull)

Yep, im absolutely with you! Tagging just makes sense if autocomplete works so we can filter contents via API by same tags over ALL collections/contents!

**Comment by benhaynes** [comment]
If someone wants to add a feature request for `Add autocomplete option to Tags interface` I'll vote for it! 😄

**Comment by benhaynes** [comment]
Well, it's a useful option. Otherwise we're looking at a `relational tags` interface: https://github.com/directus/app/issues/749

**Comment by rijkvanzanten** [comment]
The OP can be achieved by using the same junction table for two m2m fields on the both tables. 

We can continue the discussion on relational tags over on https://github.com/directus/app/issues/749
