### ISSUE TITLE
[FORBIDDEN] You don't have permission to access this.

### ISSUE THREAD

**Issue by m430** [directus/directus#23754]
### Describe the Bug

I am using the admin’s static token to access the REST API, but I keep getting a 403 error and have no clue why.

### To Reproduce

1. generate the admin user's static token
2. create a collection type
3. use curl command to test the static token like this:
```bash
curl --location --request GET 'http://localhost:8055/items/:collection' \
--header 'Authorization: Bearer<your token>' \
``` 

You will see the error.

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

mysql8.4

**Comment by hanneskuettner** [comment]
Does the collection you're trying to access? If it literally is `:collection` that is expected, as that collection does not exist.

**Comment by m430** [comment]
> Does the collection you're trying to access exist? If it literally is `:collection` that is expected, as that collection does not exist.您尝试访问的集合是否存在？如果它的字面意思是`:collection` ，这是预期的，因为该集合不存在。

I’m certain `:collection` exists. Initially, after setting up the Directus service using docker-compose, I created a collection named ‘location’ and was able to use the admin’s static token to access the API and import data without any issues. However, after deleting the ‘location’ collection, I can no longer use the admin’s static token. Even after deleting the MySQL database volume and setting everything up again with docker-compose, it’s still not working.

**Comment by hanneskuettner** [comment]
So which collection are you trying to access? 

After setting up everything again, did you regenerate a new static token and are using that now?

**Comment by m430** [comment]
I tried regenerating the static token to access the REST API, but it still didn’t work. So, I carefully reviewed the documentation related to Access Tokens. Then, I used the admin user’s email and password to access the login API and obtained an access_token. I used this access_token as a URL parameter to access the API for the previously mentioned ‘location’ collection, but I still got the same error. I’m feeling hopeless.

**Comment by hanneskuettner** [comment]
What you're describing now is very different from your initial bug report. Can you explain your steps in detail, including the URL paths you're trying to call?

**Comment by Marcio-RF** [comment]
I have the same issue here. First I created an automation that imported my google contacts into a collection I created. Everything worked. I can use the token to access the items normally. However, when I try to patch or post an item, I get:

{
    "errors": [
        {
            "message": "You don't have permission to access this.",
            "extensions": {
                "code": "FORBIDDEN"
            }
        }
    ]
}

**Comment by Marcio-RF** [comment]
I thought this was a permission issue. Then I went to the docs and it tells to go to Settings > Access Control. However, my app doesn't show this option...

![image](https://github.com/user-attachments/assets/b53d2a82-1f7f-4b9b-b7c6-ba936bcfb7c0)

**Comment by hanneskuettner** [comment]
> Then I went to the docs and it tells to go to Settings > Access Control. However, my app doesn't show this option...

Oh! Do you mind telling us which page that is, because that just means we forgot to update this when updating our docs to the latest changes with regards to the new v11 policy based system.

For configuring permissions you will have to go to "Access policies" and edit or create a policy with the desired permissions there and then assign it to your role or user in "User Roles"

**Comment by Marcio-RF** [comment]
I'm just starting to develop with directus. I'm trying to do just a simple thing and, honestly, this kind of problem takes away my confidence in using the platform....

**Comment by hanneskuettner** [comment]
Permission are a tricky topic. There never is a super simple solution if you start considering the plethora of use cases Directus can be used for and the different requirements everyone has. I urge you to give it a try tho, since your problem sounds like it has a simple solution.

**Comment by hanneskuettner** [comment]
If you have an access token you can try calling `/users/me` or /permissions/me` to verify that the token is correctly used.

**Comment by m430** [comment]
I’m really sorry, I discovered the cause of the issue. I had defined the collection name as `location`, but I assumed the API would default to the plural form `locations`, which caused the error. The API should be accessed using `location`, and now it works.
