### ISSUE TITLE
Network error on saving a new collection

### ISSUE THREAD

**Issue by saskia-compono** [directus/directus#23760]
### Describe the Bug

```json
{
  "message": "Network Error",
  "name": "AxiosError",
  "code": "ERR_NETWORK",
  "config": {}
}
```

### To Reproduce

Create a new collection and save it

### Directus Version

v11.1.0

### Hosting Strategy

Directus Cloud

**Comment by rijkvanzanten** [comment]
A network error indicates that your browser wasn't able to connect to the API, which is often caused by a lapse in internet connection or something else preventing the app from reaching the API. I'll close this for now as there's no way for me to reproduce this
