### ISSUE TITLE
Additional transformation field not working with boolean values

### ISSUE THREAD

**Issue by pklenovic** [directus/directus#23779]
### Describe the Bug

I am trying to use lossless compression in Transformation Presets, Additional Transformations fields, but for some reason I get an error:
```err: {
    ERROR: Cannot read properties of undefined (reading 'apply')
}
          at async file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/controllers/assets.js:139:36
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
          at AssetsService.getAsset (file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/services/assets.js:128:24)
          at Array.forEach (<anonymous>)
          at file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/services/assets.js:128:75
      TypeError: Cannot read properties of undefined (reading 'apply')
  "stack":
  "message": "Cannot read properties of undefined (reading 'apply')",
  "type": "TypeError",
```
additional transformation value:
```
[
    [
        "lossless",
        true
    ]
]
```
Generally, image transformation worked well for us in the past. The issue only occurs when using boolean argument values. I tried putting true inside the array but still get an error.

### To Reproduce

Create a transformation preset with some operation in the Additional Transformation field using a boolean as an argument. Call an asset with the key you just created and that should be it. Example of a transformation we get an error for:
<img width="824" alt="Screenshot 2024-10-03 at 13 54 58" src="https://github.com/user-attachments/assets/6a0ed722-d9d1-4950-b9e9-d943a0aa1b98">

### Directus Version

10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL

**Comment by br41nslug** [comment]
The error shown here is to be expected 🤔 neither `"progressive"` nor `"lossless"` are sharp transformations https://sharp.pixelplumbing.com/api-operation but rather seem like they could be output options

Boolean operations like `flip` work just fine on my end
![image](https://github.com/user-attachments/assets/aced9a72-b654-4e96-be17-1fcff7dd2806)
