### ISSUE TITLE
Typescript errors on latest @directus/themes

### ISSUE THREAD

**Issue by keesvanbemmel** [directus/directus#23826]
### Describe the Bug

Upgraded from Directus 11.1.0 to 11.1.1 and now my TSC compiler throws 262 errors in the theme.d.ts file like this:
node_modules/@directus/themes/dist/schemas/theme.d.ts:270:454 - error TS1109: Expression expected.

`270         LineWidth: import('@sinclair/typebox', { with: { "resolution-mode": "require" } }).TUnion<[import('@sinclair/typebox', { with: { "resolution-mode": "require" } }).TString, import('@sinclair/typebox', { with: { "resolution-mode": "require" } }).TLiteral<"thin">, import('@sinclair/typebox', { with: { "resolution-mode": "require" } }).TLiteral<"medium">, import('@sinclair/typebox', { with: { "resolution-mode": "require" } }).TLiteral<"thick">]>;`

The typescript version in our project is ^4.7.2 and everything else works fine.

How can I fix this?

### To Reproduce

Upgraded directus to 11.1.1, keep ^4.7.2 typescript and do TSC compile on extensions within directus project.

### Directus Version

v11.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PG15

**Comment by hanneskuettner** [comment]
Directus is using TypeScript 5.6.2 which was recently bumped from 5.4.5, see https://github.com/directus/directus/commit/e8d96d47066613c5a026f7af52cbe9e961ac0017

So I would assume there is some incompatibility between those TypeScript versions. Generally it is recommended to use the latest version when working with Directus.
