### ISSUE TITLE
Hard-coded email subjects (invite, password reset)

### ISSUE THREAD

**Issue by stafyniaksacha** [directus/directus#23839]
### Describe the Bug

`You've been invited`, `Password Reset Request` email subjects default values are hard-coded, which makes them difficult to translate.

https://github.com/directus/directus/blob/ad5361a34fb84a6c862b01769d21dc9f9cdfa565/api/src/services/users.ts#L550

https://github.com/directus/directus/blob/ad5361a34fb84a6c862b01769d21dc9f9cdfa565/api/src/services/users.ts#L358

Setting them via project settings, env variables, or via default api routes would be great

### To Reproduce

Simply send invite request or password reset request

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 16

**Comment by madc** [comment]
**Workaround:** We use a flow to fix the subjects before the mails go out:

![image](https://github.com/user-attachments/assets/71f28563-a140-41cc-bcbf-89219dd90f6a)

This is the script code:

```js
module.exports = async function(data) {
    let subject = data.$trigger.payload.subject;
    
	switch(data.$trigger.payload.template.name) {
        case 'user-registration':
            subject = 'Bitte bestätigen Sie Ihre Registrierung';
            break;
        case 'password-reset':
            subject = 'Setzen Sie Ihr neues Passwort';
            break;
        case 'user-invitation':
            subject = 'Einladung zu Website Name';
			break;
    }
	
    return {
    	to: data.$trigger.payload.to,
        subject,
        template: data.$trigger.payload.template,
    };
}
```

This is far from perfect, but I hope it is useful for your project until this feature is implemented.

**Comment by paescuj** [comment]
Closing this issue in favor of the pending feature request in #8239.
