### ISSUE TITLE
CSP 'none' Directive Breaks with Directus v11.1.1 due to Helmet v8

### ISSUE THREAD

**Issue by saifurrehmanx** [directus/directus#23849]
### Describe the Bug

After upgrading to Directus v11.1.1, which uses Helmet v8 for security headers, the application returns a 500 Internal Server Error when serving assets. The issue arises from stricter CSP validations introduced in Helmet v8. Using 'none' as a directive value without proper quoting causes the following error:

`ERROR: Content-Security-Policy received an invalid directive value for "default-src"`

This change in Helmet's behavior is documented in [this commit](https://github.com/helmetjs/helmet/commit/7b94a6c87a2e403c64fd9c180f6424c6295df0ab), where Helmet now throws an error if CSP directive values like `'none'` are not properly quoted. This results in blocked content and pages failing to load properly.  

### **Solution**  
To resolve this issue, update the CSP configuration by properly quoting `'none'`. 

Locate the following code in the **Directus assets controller** file:  
**[api/src/controllers/assets.ts, Line 142](https://github.com/directus/directus/blob/cc528d1f1e2cded05b2df510655ebec967c83003/api/src/controllers/assets.ts#L142)**  

#### Before (Incorrect):
```javascript
directives: {
    defaultSrc: ['none'], 
}
```

#### After (Correct):
```javascript
directives: {
    defaultSrc: [`'none'`],  // Properly quoted 'none'
}
```

### To Reproduce

1. Install or upgrade to **Directus v11.1.1**.  
2. Start the Directus server.  
3. Access any page or asset, such as:  
   ```
   /assets/f6332121-067e-4b3c-8339-b1405a792db5
   ```
4. Observe the **500 Internal Server Error** in the logs, along with the following error message:  
   ```
   ERROR: Content-Security-Policy received an invalid directive value for "default-src"
   ```

### Directus Version

v11.1.1

### Hosting Strategy

Self-Hosted (Custom)

### Database

MYSQL 8

**Comment by br41nslug** [comment]
Older docker images should have the non-backported version bundled in it so they'll hopefully be fine :)
