### ISSUE TITLE
Extensions not loading in 11.1.1

### ISSUE THREAD

**Issue by rybber78** [directus/directus#23843]
### Describe the Bug

Upgraded Docker install to 11.1.1. Extensions install fine in folder, and show extensions manager, but they do not load. extensions folder exists and files have been downloaded here.

Have followed tihs guide:  https://www.restack.io/docs/directus-knowledge-directus-extension-load-issue

![directus](https://github.com/user-attachments/assets/688f964e-d402-459d-8e82-ee6b33c96850)

### To Reproduce

Install 11.1.1 over existing install

### Directus Version

11.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

MySQL

**Comment by br41nslug** [comment]
restack.io is not affiliated with Directus and I would recommend avoiding their AI generated SEO docs

**Comment by rybber78** [comment]
Wierd, it's working again now. Must have been a browser caching issue...
