### ISSUE TITLE
sdk types not accurate

### ISSUE THREAD

**Issue by N0SAFE** [directus/directus#23850]
### Describe the Bug

on the latest sdk type the type of the function readRelation dot not require a Query but use a generic callled TQuery as a Directus.Query into the ReadRelationOutput where his generic require the ItemObject (the DirectusRelation type)

![image](https://github.com/user-attachments/assets/02ca6d0c-7004-4064-83d0-6760401946d5)
 

### To Reproduce

install the latest version of the sdk package

### Directus Version

v11.1.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
What is the exact issue you're seeing here? Both the `readRelations` and `readRelationByCollection` endpoints do not support query parameters.
- https://docs.directus.io/reference/system/relations.html#request
- https://docs.directus.io/reference/system/relations.html#list-relations-in-collection

**Comment by N0SAFE** [comment]
Yes exactly I just was wondering why the readRelation have a Generic for the query and why it pass to the type ReadRelationOutput where the generic as to be the returned object (pass Tquery where the extend require the object to return) this made no sense and messed up the return of the function readRelation
