### ISSUE TITLE
directus_refresh_token missing from collection item preview

### ISSUE THREAD

**Issue by me-marcel** [directus/directus#23864]
### Describe the Bug

When opening a collection item preview the `directus_refresh_token` cookie is not being set within the iframe. The cookie is nowhere to be found within any of the response headers. Thus, the token refresh within the preview iframe fails.

---

The following things can be assumed about the technical configuration of the setup:

- The Directus version is `10.13.2`.
- The Directus base url is `https://cms.group.test.de`.
- The Preview from the IFrame runs at `https://preview.group.test.de`.
- The environment environment variable `REFRESH_TOKEN_COOKIE_DOMAIN` is set to `.group.test.de`.
- The environment environment variable `REFRESH_TOKEN_COOKIE_SECURE` is set to `true`.
- The environment environment variable `REFRESH_TOKEN_COOKIE_SAME_SITE` is set to `None`.
- The `Directus SDK` version `17.0.2` is used to communicate with the Directus instance. The versions `^15.0.3` and `16.1.2` have also been checked against.

**Note:** The report depicts an abstract variant of the problem; However, it correctly resembles dependencies between configuration parameters at https://docs.directus.io/self-hosted/config-options.html.

---

Furthermore, the following things can be assumed:

- Setting the refresh token cookie worked fine with Directus 10.8.2 and the above parametrization when it was first implemented.
- The feature supposedly stopped working somewhere between the versions 10.8.2 and 10.13.2.
- The behaviour has been confirmed using Google Chrome 129.0.6668.103, Brave 1.70.126 and Microsoft Edge 129.0.2792.89. Brave and Microsoft Edge where checked against without any plugins being installed.

---

When searching for potential solutions the following things where checked to assure compatibility with the browsers mentioned above:

- The cookie configuration matches strict browser policies for setting cross-domain cookies (`Secure` is `true` and `SameSite` is `none`).
- The cookie domain matches the wildcard `.group.test.de` between Directus and preview domain.
- The Directus client initialization has `withCredentials` set to `true` (see client initialization within the issue reproduction description).

---

I checked the issue with three additional people before reporting it. However, it could well be the case that we've all missed something. In that case I'd be glad if you could briefly point out the issue to me so it can be fixed on my part asap. Thanks in advance!

### To Reproduce

1. Install an older version of Directus (e.g. `10.8.2`) setting the appropriate environment variable values mentioned above (please adapt to the domain of your setup).
2. Configure a preview for a collection initializing the client using the following code:
```
import { authentication, AuthenticationClient, createDirectus, rest, RestClient } from '@directus/sdk';

getClient(url: string): AuthenticationClient<any> & RestClient<any> {
  const client = createDirectus(url)
    .with(rest())
    .with(authentication('cookie', { credentials: 'include' }));

  client.refresh();

  return client;
}
```
3. Gradually update to the newest `v10` version of Directus.

**Expected (faulty) behaviour:** It should no longer be possible to read data from the Directus API.

### Directus Version

v10.13.3

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 15.7

**Comment by hanneskuettner** [comment]
With Directus version 10.10 the Studio switched over to using the `session` mode by default, where both, access and refresh token have been rolled into a single session cookie, you can read about it here https://docs.directus.io/releases/breaking-changes.html#session-cookie-based-authentication.

Since it seems like you're relying on the authentication cookie to be set by the Directus Studio, I suggest switching over your configuration to the `SESSION_COOKIE_*` environment variables and using the authentication mode `'session'` instead of cookie, when setting up the `authentication` in your SDK initialization. 

Let me know if this solves the issue for you.

**Comment by me-marcel** [comment]
@hanneskuettner Thanks a lot! This is great advice. I will get to testing it straight away.

I must have not seen the change when updating instances back then since `10.10` was skipped. That one's on me. I'll quickly report back after testing to document this for future reference.

**Comment by me-marcel** [comment]
As promised I would like to share my experience with the suggested changes. They made the token refresh become functional. A session token is returned and saved to the `directus_session_token` cookie. However, it still doesn't seem to be possible to access any items through the items API. No authentication data seems to be passed along with this request causing a `403 Forbidden` response.

The respective code can be found below. 

```
// directusService

import { authentication, AuthenticationClient, createDirectus, rest, RestClient } from '@directus/sdk';

getClient(url: string): AuthenticationClient<any> & RestClient<any> {
  const client = createDirectus(url)
    .with(rest())
    .with(authentication('session', { credentials: 'include' }));

  client.refresh();

  return client;
}
```

```
// genericService

constructor(@Inject(GENERIC_CONFIG) config: GenericConfig) {
  this.directusClient = this.directusService.getClient(config.directusUrl);
}

getItem(key: string, locale: string): Observable<GenericInternalItem | undefined> {
  if (!this.directusClient) return of();

  return from(
    this.directusClient.request<GenericDirectusItem>(
      readItem('generic_collection' as never, key, {
        fields: ['*', 'something_else.*'],
      })
    )
  ).pipe(map((item) => this.mapItem(item, locale)));
}
```

Sadly, I had to redact some of it. However, it should be enough to get a hold of the issue I'm facing.

It might just be a really dumb issue that I am blind towards. Who knows...

Thanks in advance to anyone who is willing to help!

**Comment by hanneskuettner** [comment]
Have you verified that the user can actually access the item and fields you're trying to access in the preview code?

**Comment by me-marcel** [comment]
Yes, I have. The user in question has full administrative rights on the Directus instance so all collections should be readable. To my knowledge the administrative role cannot be restricted.

**Comment by hanneskuettner** [comment]
> To my knowledge the administrative role cannot be restricted.

True. If you inspect the request made within the iframe, do you see the cookies attached to the API request?

**Comment by hanneskuettner** [comment]
> I suppose the cookie may not be able to be read because when I tried to output the access_token attribute of the result that the refresh promise returns then it is null.

With the session cookie that is the expected result, as the session cookie is an `HttpOnly` cookie, that the JS can't read. 

Can you give it a try without calling `refresh()`? The app/SDK should handle the cookie refresh for you automatically. The correct session cookie should be transmitted along the request to the Directus API. If you don't see that happening I strongly suspect there is some configuration problem going one, that could be related to cookie settings, CSP on your preview page, etc..

**Comment by me-marcel** [comment]
When removing the `refresh()` call the response of the items API is still the same. Sadly, I do not seem to see the expected behaviour. Not even on a local setup where Directus runs on `localhost:8055` and the preview application on `localhost:4200`. The latter being an Angular DEV server without any Content Security Policy, whatsoever. I'll go check some of these basics tomorrow again. Maybe I've missed something.

**Comment by me-marcel** [comment]
**For future reference:** We were able to solve the issue by specifically telling the REST client to include the credentials. So the working code for the client initialization looks something like this:

```
getClient(url: string): AuthenticationClient<any> & RestClient<any> {
  const client = createDirectus(url)
    .with(rest({ credentials: 'include' }))
    .with(authentication('session', { credentials: 'include', autoRefresh: true }));

  return client;
}
```

I'm closing the issue for good. Huge thanks to the Directus support team! Specifically @joselcvarela and colleagues 🙂
