### ISSUE TITLE
SSO Open ID - Redirect Error

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [directus/directus#23872]
### Describe the Bug

When configuring an open id provider: https://oidc-proxy.aai.dfn.de/.well-known/openid-configuration they redirect and therefore i get an error.

This is due to a problem openid-client?

```js
[16:31:04.966] ERROR: [OpenID] Failed to fetch provider config
err: {
  "type": "OPError",
  "message": "expected 200 OK, got: 303 See Other",
  "stack":
      OPError: expected 200 OK, got: 303 See Other
          at processResponse (/directus/node_modules/.pnpm/openid-client@5.6.5/node_modules/openid-client/lib/helpers/process_response.js:41:11)
          at Issuer.discover (/directus/node_modules/.pnpm/openid-client@5.6.5/node_modules/openid-client/lib/issuer.js:151:18)
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  "error": "expected 200 OK, got: 303 See Other",
  "name": "OPError"
}
```

### To Reproduce

      AUTH_DFN_DRIVER: "openid"
      AUTH_DFN_MODE: "session"
      AUTH_DFN_CLIENT_ID: "${AUTH_DFN_CLIENT_ID}"
      AUTH_DFN_CLIENT_SECRET: "${AUTH_DFN_CLIENT_SECRET}"
      AUTH_DFN_ISSUER_URL: "https://oidc-proxy.aai.dfn.de" # https://oidc-proxy.aai.dfn.de/.well-known/openid-configuration redirects with an 303 status. Check later if this is fixed
      AUTH_DFN_IDENTIFIER_KEY: "sub"
      AUTH_DFN_ALLOW_PUBLIC_REGISTRATION: "true"

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by NilsBaumgartner1994** [comment]
for openid-client ^6.0.0 there is a way to follow redirects:

```js
import * as client from 'openid-client'

const issuer = new URL('https://oidc-proxy.aai.dfn.de')
await client.discovery(issuer, '<clientId>', undefined, undefined, {
  [client.customFetch]: (url, options) => {
    if (url === `${issuer.href}.well-known/openid-configuration`) {
      options.redirect = 'follow'
    }

    return globalThis.fetch(url, options)
  }
})
```

Depending on the version Directus uses this might be implmented?

**Comment by br41nslug** [comment]
I'll be closing this issue for now considering the response on the dependency issue here https://github.com/panva/openid-client/issues/707. As the spec explicitly expects a 200 response here I am seeing this an issue on the service providers side. 

It being possible by hijacking the `fetch` implementation could be a thing but will be required to go through a feature request (and we'll need to update to ^6)
