### ISSUE TITLE
Creating a relationship to an image fails

### ISSUE THREAD

**Issue by l10rdev** [directus/directus#23875]
### Describe the Bug

{
  "errors": [
    {
      "message": "alter table `test` add constraint `test_image_foreign` foreign key (`image`) references `directus_files` (`id`) on delete SET NULL - Can't create table `directus`.`test` (errno: 150 \"Foreign key constraint is incorrectly formed\")",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

### To Reproduce

create and field on a datamodel.
Select image as datatype

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Custom)

### Database

mariadb

**Comment by br41nslug** [comment]
I am unable to reproduce the issue using the given information

https://github.com/user-attachments/assets/253142ad-19a9-4984-a7d3-62020506a85b
