### ISSUE TITLE
blank in Internet Explorer

### ISSUE THREAD

**Issue by Derilka** [directus/directus#2388]
# Bug Report

## Steps to Reproduce

1. open login page in IE 11
2. get a blank page (there is some source code in the browser - however blank page for user)
this is the loaded source code:
`
<!DOCTYPE html><html lang=en><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1"><link rel="shortcut icon" href=favicon.ico><link rel=manifest href=/manifest.webmanifest><title>Directus</title><link rel=stylesheet href=./style.css><link href=css/app.8f35ad4a.css rel=preload as=style><link href=js/app.bf32c5e5.js rel=preload as=script><link href=js/chunk-vendors.40083d29.js rel=preload as=script><link href=css/app.8f35ad4a.css rel=stylesheet></head><body><noscript><strong>We're sorry but Directus doesn't work without JavaScript enabled. Please enable it to continue.</strong></noscript><div id=app></div><script src=./config.js></script><script src=./script.js></script><script src=js/chunk-vendors.40083d29.js></script><script src=js/app.bf32c5e5.js></script></body></html>`

## Expected Behavior
login screen comes up for user

## Actual Behavior
no login page - nothing

## Other Context & Screenshots
did do fresh new install today
console in dev tools says - crititacal error:
SCRIPT1002: Syntaxfehler format-title.umd.js (1,76728)

## Technical Details
    Device: Laptop
    OS: Win 10 64Bit + IE 11.0.125
    Web Server: IIS 10
    PHP Version: php-7.3.6-nts-Win32-VC15-x86
    Database: MySQL - 'SELECT @@Version;' gives me 5.7.23-log
    Install Method: cloned zip copy (today)

**Comment by rijkvanzanten** [comment]
Directus explicitly doesn't support Internet Explorer:

**Comment by Derilka** [comment]
Oh, ok, thx. I did not know. That sets me quite some decision point now: all in or all out.
From other projects my experience is, that getting something to see in IE is usually not that hard, whereby making the experience the same often requires much effort.
If I would myself dedicate to get something to see IE, would you allow me to contribute changes to your project or would you send me doing this in a forked environment?
The forked env. would mean all out for me, whereby you allowing me to contribute in that respect would mean some extra preparation and work for me to do.

**Comment by rijkvanzanten** [comment]
We're relying heavily on Vue and Vue CLI which are both moving away from IE support too. Trying to add support for IE will add so much overhead in terms of polyfills and refactors that it's most likely not worth the effort. Besides, IE itself is only in security update mode and isn't actively supported by MS either. The best we can do is show a message that Internet Explorer is not supported and that the user should use Edge or download another browser
