### ISSUE TITLE
I Can not upload image 

### ISSUE THREAD

**Issue by joneadoerd** [directus/directus#23883]
### Describe the Bug

i am using docker composer with Postgres database 

### To Reproduce

i am using docker composer with Postgres database 

### Directus Version

v11.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL

**Comment by hanneskuettner** [comment]
Can you enlighten us with any details how to reproduce this? Image uploading in its most basic form is certainly working using the docker image and the most recent version of Directus.

**Comment by triplecasquette** [comment]
I can confirm that I use docker, postgres and Images uploading just works fine.
Better look to Nginx settings or even if you had define an upload folder to persist images.

If you have error you can share the code and message :)

**Comment by metalsoftware** [comment]
I have same problem. I am using Directus 11.1.1 (self-hosted docker image) and MariaDB. This is new setup no previous versions used. When I try to upload any images to Directus I am getting following error [FAILED_VALIDATION] Validation failed for field "uploaded_on". Value is required.

![image](https://github.com/user-attachments/assets/bbcf7171-df4d-4ed2-bfa4-ad214c38ffc4)

**Comment by metalsoftware** [comment]
Got fixed the issue, I needed to change on directus_files table the uploaded_on column default value to be current timestamp.
That fixed the problem, default was something 0000-00-00 or something like that.
