### ISSUE TITLE
Search request for forbidden email field will return users

### ISSUE THREAD

**Issue by moritzgvt** [directus/directus#23894]
### Describe the Bug

A request for the directus_users collection with a search parameter for a email address will return an user object even if there's no read permission for the directus_users email field.

One cannot access the email field but one can filter with it.

### To Reproduce

1. Add partial public reading permissions for the directus_users collection, but not for the field email
2. Create user with example@your-mail.de
3. Make a get requests: 
- `/users?fields=*`
This request will return all accessible fields but won't get you the email field
- `/users?fields=email`
That will fail with _You don't have permission to access field \"email\" in collection \"directus_users\" or it does not exist._
- `/users?search=@your-mail.de` 
This request will return all accessible fields of the users having in `@your-mail.de` as a substring in the email field

Expectation: 
Not readable fields shouldn't be searchable.

### Directus Version

v11.0.1

### Hosting Strategy

Self-Hosted (Custom)

### Database

Postgres

**Comment by br41nslug** [comment]
This is a security issue that has already been reported as security advisory. I'm removing the info provided here.
