### ISSUE TITLE
Directus App: Drawer on data modelling page resets the page scroll

### ISSUE THREAD

**Issue by yfi** [directus/directus#23890]
### Describe the Bug

When modelling data in the directus app, opening the drawer resets the scroll of the page.
This breaks the expected behaviour of a modal form and is quite frustrating when working on fields below the fold as you constantly have to search for where you left off.

This does not happen on other pages that use the drawer component ( settings page, item fields in a collection etc )

### To Reproduce

On the data model page, create or open a collection with lots of fields (ie. directus_files ). 
Scroll down to any field below the fold and click it.
The page's scroll position is reset as the drawer opens.

### Directus Version

v11.11

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

mariadb, directus 11.11 docker image

**Comment by AlexGaillard** [comment]
This was I believe fixed in: https://github.com/directus/directus/pull/23920
