### ISSUE TITLE
directus_access collection not created on migration v10.13.2 to v11.0.1

### ISSUE THREAD

**Issue by Pachat** [directus/directus#23914]
### Describe the Bug

When migrating from v10.13.2 to v11.0.1, the directus_access is not created.
neither after running `npx directus database migrate:latest`

### To Reproduce

In the docker-compose.yml change  v10.13.2 to v11.0.1
At logging a user, we have
```
error: select "directus_policies"."admin_access", "directus_policies"."app_access", "directus_policies"."ip_access" from "directus_access" left join "directus_policies" on "directus_policies"."id" = "directus_access"."policy" where "role" in ($1) - relation "directus_access" does not exist
at Parser.parseErrorMessage (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/parser.js:283:98)
```
and having a look to the DB, we see that directus_access table is missing.

### Directus Version

v10.13.2 => v11.0.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 15

**Comment by hanneskuettner** [comment]
Can you observe any errors when running the migration from 10.13.2 for the first time?

**Comment by Pachat** [comment]
No visible error during migration.

What i can add, is that i made a migration following this path:
10.2.1 => 10.3.0 => 10.10.7 => 10.13.2

Then tried 11.0.1 then 11.1.1 but directus_access was not created.
Did I jumped over a version that should have created it?
I did not found which one as directus_access is not mentionned in the versions pages.

**Comment by Pachat** [comment]
Since creating directus_access and directus_policies seems straightforward from directus_roles when coming from v10, do you think if i import the structures from a v11 installation and then populate them, that would be acceptable to complete a v11 migrated from v10?

**Comment by hanneskuettner** [comment]
> Since creating directus_access and directus_policies seems straightforward from directus_roles when coming from v10, do you think if i import the structures from a v11 installation and then populate them, that would be acceptable to complete a v11 migrated from v10?

If the table are not present it seems like the migration must have failed. So a better bet is to go back to a backup of the database of a previous version and re-attempt the migration. The way the collections are set up requires them to be created through the migration, otherwise you lose the whole permission setup.

**Comment by Pachat** [comment]
That's a good advide. So I reverted to v10.13.2
Then I modified the version in the docker-compose.yml and reduild the whole.

- directus_policies is created which shows that somehow the migration was activated,
- but directus_access is not created.
So the migration stays uncomplete.

**Comment by hanneskuettner** [comment]
And you don't see any errors in the console? There should be some logged if the migration does not finish

**Comment by Pachat** [comment]
Actually there were errors (I didn't see it before because I ran with detached -d)
The errors showed that I needed to disable some triggers.
Then the direct migration from 10.2.1 to 11.1.1 worked like a charm in about 1 minute.
For the record, I had to move the extensions up one subfolder. And there you have it.
It's really impressive to go from 50 versions behind to the latest in a snap.

**Comment by hanneskuettner** [comment]
Glad to hear it worked for you!

> For the record, I had to move the extensions up one subfolder. 

That tracks, as that is a breaking change documented here: https://docs.directus.io/releases/breaking-changes.html#version-10-10-0
