### ISSUE TITLE
Directus v10.13.3 is missing in NPM

### ISSUE THREAD

**Issue by RonaldKools** [directus/directus#23918]
### Describe the Bug

npm ERR! code ETARGET
npm ERR! notarget No matching version found for directus@10.13.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

v10.13.3 exists in the list of releases: 
https://github.com/directus/directus/tree/v10.13.3

but we cannot pull it from npm:
https://www.npmjs.com/package/directus?activeTab=versions

### To Reproduce

run npm install for 10.13.3

### Directus Version

v10.13.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment]
Missed this earlier! The last release did make it to npm as expected. Something in the release automation must've failed. Seems like the last deployment went out as expected, so I'll close this as I don't think there's an actionable item at this point. Ty!
