### ISSUE TITLE
403 error for M2A related fields, in v11.1.1

### ISSUE THREAD

**Issue by madc** [directus/directus#23912]
### Describe the Bug

We still see the behavior described in #23338. #23293:

Having multiple collections with different fields results in a permission error similar to this one:

`"You don't have permission to access field \"field_a\" in collection \"collection_b\" or it does not exist. Queried in \"m2a.item:collection_b\"."`

Related Fields (1:n, n:n) seem not to be affected.

### To Reproduce

Create a M2A field containing different fields and query via graphql.

### Directus Version

v11.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL

**Comment by hanneskuettner** [comment]
Can you share the full query? Do you have any relevant permission on the `collection_b` that might result in this error?

**Comment by madc** [comment]
@hanneskuettner Thanks for getting back to be that quickly. Here are more details, let me know, if I can provide any other information or test something.

Public permissions are all open for the collections:
![image](https://github.com/user-attachments/assets/bffbb082-32ac-4ba9-af98-9c533be78a3e)

No tokens or other auth is sent.

This is the query:

```
fragment ce_form on content_element_form {
  id
  body
  config
  template
}

fragment ce_image on content_element_image {
  id
  template
  body
  image {
    ...image
  }
}

fragment image on directus_files {
  id
  title
  description
  filename_download
  width
  height
  type
}


query GetHomepage {
  pages(filter: { translations: { slug: { _empty: true } } }, limit: 1) {
    translations {
      meta_title
      meta_description
      slug
      title
      body
      body_nodes {
        id
        collection
        item {
          ...ce_form
          ...ce_image
        }
      }
      languages_code
    }
  }
}
```

This is the Result:
```
{
  "errors": [
    {
      "message": "You don't have permission to access field \"config\" in collection \"content_element_image\" or it does not exist. Queried in \"translations.body_nodes.item:content_element_image\".",
      "extensions": {
        "code": "FORBIDDEN",
        "reason": "You don't have permission to access field \"config\" in collection \"content_element_image\" or it does not exist. Queried in \"translations.body_nodes.item:content_element_image\"."
      },
      "locations": [
        {
          "line": 30,
          "column": 3
        }
      ],
      "path": [
        "pages"
      ]
    }
  ]
}
```

Removing the `config` (a JSON field) from `content_element_form` successfully returns content. `content_element_image` does not have a config field. Adding the `config` field to this collection would also resolved the issue, but makes no sense. :)

**Comment by hanneskuettner** [comment]
> Public permissions are all open for the collections:

Not seeing `collection_b` in there

**Comment by madc** [comment]
This currently is a really blocking issue, does any one has experience? Only workaround so far is to create the fields, which defeats the purpose of M2A.

**Comment by madc** [comment]
Yes, you are right. This also explains, why we don't have this issue in some other projects. There we did exactly this, but I thought it was an issue with the gql library.

This is definitely an acceptable workaround. I'd be OK closing this issue in favor of #14276.
