### ISSUE TITLE
Inconsistent GraphQL schema after changing field type

### ISSUE THREAD

**Issue by joezak11** [directus/directus#23917]
### Describe the Bug

I had a field key `features` was a dropdown menu that I changed afterwards. I dropped the `features` field and created a new field with the same key `features` type being `M2M` relationship with a collection called `feature` but when I use GraphQL to query this collection it still shows `features` as a string with a value of null instead of being a relationship.

The rest API is showing correctly, it's just GraphQL that shows `null`

### To Reproduce

1. Create a field in `CollectionA` of type dropdown key `features`
2. Drop that field and create a new collection `feature`
3. Create a new field in `CollectionA` with key `features` of type `M2M` with collection `feature`
4. Use GraphQL to query `CollectionA` and select field `features`

### Directus Version

v11.1.1

### Hosting Strategy

Self-Hosted (Custom)

### Database

Sqlite3 ^5.1.7

**Comment by hanneskuettner** [comment]
Does this issue persist if you restart the instance?

**Comment by joezak11** [comment]
Yes, it does.

**Comment by hanneskuettner** [comment]
Do you have external caching configured through a Redis instance that could persist during restarts?
Could it maybe be a permission issue, where the user trying to access the GraphQL API does not have read permissions for the junction, or the related table?

**Comment by joezak11** [comment]
Yes, thanks a lot actually it was a permission issue and since I was logged in through the browser it showed the data in the rest API but not through GraphQL.
