### ISSUE TITLE
Outdated Shares Roles Query?

### ISSUE THREAD

**Issue by yfi** [directus/directus#23924]
### Describe the Bug

When attempting to select a role in a "new share" drawer the roles selection is empty.

The app issues a series of requests to directus_roles asking for the admin_access field which I think has been moved to directus_policies table.

The requests are:
`/roles?filter[admin_access][_eq]=false&aggregate[countDistinct]=id`

`/roles?limit=25&fields[]=icon&fields[]=name&fields[]=description&fields[]=id&sort[]=name&page=1&filter[admin_access][_eq]=false`

`http://localhost:8055/roles?aggregate[countDistinct]=id&filter[admin_access][_eq]=false`

Which all return the same response:

```json
{
    "errors": [
        {
            "message": "You don't have permission to access field \"admin_access\" in collection \"directus_roles\" or it does not exist. Queried in root.",
            "extensions": {
                "reason": "You don't have permission to access field \"admin_access\" in collection \"directus_roles\" or it does not exist. Queried in root.",
                "stack": "DirectusError: You don't have permission to access field \"admin_access\" in collection \"directus_roles\" or it does not exist. Queried in root.\n    at createFieldsForbiddenError (/Users/yfi/Projects/CONTACT/directus-dev/api/src/permissions/modules/process-ast/utils/validate-path/create-error.ts:16:9)\n    at validatePathExistence (/Users/yfi/Projects/CONTACT/directus-dev/api/src/permissions/modules/process-ast/utils/validate-path/validate-path-existence.ts:16:9)\n    at processAst (/Users/yfi/Projects/CONTACT/directus-dev/api/src/permissions/modules/process-ast/process-ast.ts:51:3)\n    at RolesService.readByQuery (/Users/yfi/Projects/CONTACT/directus-dev/api/src/services/items.ts:500:9)\n    at <anonymous> (/Users/yfi/Projects/CONTACT/directus-dev/api/src/controllers/roles.ts:66:18)",
                "code": "FORBIDDEN"
            }
        }
    ]
}
```

### To Reproduce

Pick any item. Click Shares -> New Share -> Select a Role.

https://github.com/user-attachments/assets/37a61d78-2de9-430f-b351-dd7c862f3802

### Directus Version

v11.1.1

### Hosting Strategy

Self-Hosted (Custom)

### Database

mariadb

**Comment by hanneskuettner** [comment]
This is a known issue and is actively being worked on, see https://github.com/directus/directus/issues/23017.

I'll close this issue, as it strictly speaking is a duplicate.
