### ISSUE TITLE
User updated and user created fields are no longer being populated

### ISSUE THREAD

**Issue by u12206050** [directus/directus#23954]
### Describe the Bug

After updating to 11.1.2 and running migrations, all user_updated and user_created fields stopped being set when users insert or update items! In our case this breaks a number of processes.

This is a how the field now looks in ui:
![Screenshot 2024-11-01 at 08 46 07](https://github.com/user-attachments/assets/ed73348d-31a7-4277-9802-f1830c0a42b2)

### To Reproduce

Upgrade to 11.1.2
create an item, ensure user_created is set and isn't null
update an item, ensure user_updated is set and isn't null.

### Directus Version

v11.1.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

mysql

**Comment by u12206050** [comment]
Even creating a brand new collection with the tow user fields, shows as above and doesn't allow setting default value to $CURRENT_USER

**Comment by hanneskuettner** [comment]
Closing this, as it turns out after a debugging session with @u12206050 , that everything works just as expected.
