### ISSUE TITLE
Boss wanted to know if Directus security 

### ISSUE THREAD

**Issue by JbalTero** [directus/directus#2395]
Hello, I am currently under the process of promoting directus to use in the organization.

Is Directus free from at least all OWASP Top 10 web application risks and SANS Institute/Common Weakness Enumeration (CWE) Top 25 Software Errors? Any idea? Thanks

**Comment by benhaynes** [comment]
Being open-source, we don't have the staff to keep these specific checks up-to-date, but we have had several independent security audits that are only returning very small-level issues (which can be reviewed in our GitHub issues). So I am relatively confident Directus doesn't contain any of those major risks.

**Comment by JbalTero** [comment]
Thanks
