### ISSUE TITLE
Many to one relationship gives permission error after v11 update

### ISSUE THREAD

**Issue by craigharman** [directus/directus#23965]
### Describe the Bug

I have 2 collections with one connected to the other via a Many to One relationship. Since upgrading from Directus 10 to 11 visiting the collection with the relationship field now gives a permission error:

"You don't have permission to access field".

This occurs despite:
1. Being logged in as administrator
2. It working fine in v10
3. The sidebar listing working and including the field supposedly not having permission to view

Note: Hiding the m2o relationship field from the collection allows the collection detail form to display without error.

### To Reproduce

In Directus v10 create 2 collections. In second collection have a column named in all capitals like PINS.
In the 1st collection create an m2o relationship that displays the PINS field.
Upgrade to v11 and visit the 1st collection details page. You receive a permissions error on the "pins" field (note casing). Clicking on the field to see the 2nd collections details correctly shows the PINS column.

### Directus Version

v11.1.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL

**Comment by hanneskuettner** [comment]
Can you share more information on what the field datatypes are? Is `PINS` a simple string field or a O2M alias? Can you share the request that triggers the error (can be found in the network panel of your browser, or you API console).

**Comment by craigharman** [comment]
Sure! `PINS` is a `string`.
The request that triggers is the GET request to /items/collection1

The remainder of the request/response has proprietary data in so won't share here. But can send privately as required.
