### ISSUE TITLE
Directus week() function: Need help changing default week start to Monday

### ISSUE THREAD

**Issue by yavuz** [directus/directus#23961]
### Describe the Improvement

I'm using a Directus query with week grouping, but it's setting Sunday as the start of the week, while I need it to start from Monday.

Here's an example of my request:
```
http://localhost:8055/items/reviews?filter={
  "review_date":{
    "_between":["2024-10-05","2024-11-03"]
  },
  "status":{
    "_eq":"published"
  }
}&groupBy=sentiment&groupBy=year(review_date),week(review_date)&aggregate={"count":["id"]}
```

Here's my current code:

```
const response = await getItems({
  collection: 'reviews',
  params: {
    filter: {
      review_date: {
        _between: [
          `${props.dateRange.from.split('.').reverse().join('-')}`,
          `${props.dateRange.to.split('.').reverse().join('-')}`
        ]
      },
      status: { _eq: 'published' }
    },
    groupBy: ['sentiment', `year(review_date)${
      props.datePeriod === 'monthly' ? ',month(review_date)' :
      props.datePeriod === 'weekly' ? ',week(review_date)' :
      ',month(review_date),day(review_date)'
    }`],
    aggregate: {
      count: ['id']
    }
  }
})
```

I've tried using week(review_date,1) and week(review_date,3), but neither worked. The grouping still starts from Sunday. Any ideas on how to make the week start from Monday?

**Comment by hanneskuettner** [comment]
Since Directus relies on SQL functions to extract the week from a datetime you will have to look into how you can change the default starting date for your specific database. Since you didn't provide that information I can't point you to the right resources, but you can have a look here to understand what function is used in your dialect https://github.com/directus/directus/tree/main/api/src/database/helpers/fn/dialects

**Comment by yavuz** [comment]
I solved it by adding the line

my.cnf file

```
[mysqld]
default_week_format=1
```

to my my.cnf file. However, when I want to pass a parameter to the WEEK method, I'm unable to do so. It would be great if this feature were available. For example:

`SELECT WEEK('2024-11-04', 1);`

Here, the parameter 1 seems to set the start day of the week. Thanks!
