### ISSUE TITLE
unexpected errors in file fields with google cloud storage at version 11.1.2 

### ISSUE THREAD

**Issue by dwoeschka** [directus/directus#23969]
### Describe the Bug

After update from 11.1.1. to 11.1.2 the file fields are showing the message "unexpected errors". With the same files and version 11.1.1 the system operates without issues. We us google cloud storage as file storage provider. 

### To Reproduce

Update to 11.1.2.
You will see no images in file fields 

![image](https://github.com/user-attachments/assets/db0b3f20-7fea-4d04-abe0-cfe8cfa77102)

### Directus Version

v11.1.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgreSQL  16

**Comment by hanneskuettner** [comment]
Any chance you're able to share the error that is shown in your Directus API console? This should give us an idea of what is going wrong.

**Comment by hanneskuettner** [comment]
Looks like this might be related to https://github.com/directus/directus/issues/23969

Do you have any custom content security header values set in you configuration?

**Comment by dwoeschka** [comment]
Did you mean this? But that are the same values as in V11.1.1. 

![image](https://github.com/user-attachments/assets/31f697af-254f-42b4-9d06-1f9015a0b478)

**Comment by hanneskuettner** [comment]
Sorry! I meant to link this PR https://github.com/directus/directus/pull/23853

**Comment by br41nslug** [comment]
> Did you mean this? But that are the same values as in V11.1.1.
> 
> ![image](https://private-user-images.githubusercontent.com/49706666/383052807-31f697af-254f-42b4-9d06-1f9015a0b478.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5ODM5NTEsIm5iZiI6MTczMDk4MzY1MSwicGF0aCI6Ii80OTcwNjY2Ni8zODMwNTI4MDctMzFmNjk3YWYtMjU0Zi00MmI0LTlkMDYtMWY5MDE1YTBiNDc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDEyNDczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmM2Y1NzdmM2Y0NTEzMDE0MTcyYjUyYzE4NzQyZWM4YTFjYzA4YjY0NzE4MmJlOWZiNGZlNjY5Y2Y5NTkzOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8td2GF4U8kxjvo2sT6g3hrNb_Euv3bQw0AmjeaKjkEM)

Are these all the `ASSETS_CONTENT_....` environment variables set?
The first environment variable shown `ASSETS_CONTENT_SECURITY_POLICY="..."` is invalid but that should not create an error and should be ignored as unknown configuration.
The second variable looks ok and should not error if properly parsed as an array (if not and used as a string it could throw the error shown in this issue 🤔).

On my local system these settings do not error, does explicitly adding quotes change anything on your end?
```
ASSETS_CONTENT_SECURITY_POLICY_DIRECTIVES__MEDIA_SRC="array:'self',blob:,https://*"
```
Or as space separated string should work aswell:
```
ASSETS_CONTENT_SECURITY_POLICY_DIRECTIVES__MEDIA_SRC="'self' blob: https://*"
```
