### ISSUE TITLE
Cannot Create Comment with @mention in Directus – “FORBIDDEN” Error

### ISSUE THREAD

**Issue by hakanhakan** [directus/directus#23970]
### Describe the Bug

When attempting to use the @mention feature in the comments section in Directus, we encounter a “FORBIDDEN” error message. This issue persists even after performing a fresh installation and testing with a newly created item.

JSON:
```
{
  "errors": [
    {
      "message": "You don't have permission to access fields \"admin_access\", \"app_access\" in collection \"directus_roles\" or they do not exist. Queried in \"role\".",
      "extensions": {
        "reason": "You don't have permission to access fields \"admin_access\", \"app_access\" in collection \"directus_roles\" or they do not exist. Queried in \"role\".",
        "code": "FORBIDDEN"
      }
    }
  ]
}
```

### To Reproduce

	1.	Set up a fresh installation of Directus (self-hosted Docker image).
	2.	Create a new item within any collection.
	3.	Attempt to comment on the item and use @mention to tag another user.
	4.	Observe the “FORBIDDEN” error in the response.

### Directus Version

v.11.1.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
Looks like this slipped the review in a recent PR, see https://github.com/directus/directus/pull/23612/files#r1827589703

**Comment by ComfortablyCoding** [comment]
Semi duplicate of https://github.com/directus/directus/issues/22961
