### ISSUE TITLE
sdk schemaSnapshot not working

### ISSUE THREAD

**Issue by emabiz** [directus/directus#23974]
### Describe the Bug

Hi,
I am not able to use schemaSnapshot api.
If I do a rest request, it works.
I also tried using "cookie", instead of "json", but it doesn't work.
From the documentation I am not able to understand how to use it.

Maybe I am missing something in the authentication, but I don't know what.

Can you help me on this, please?

Thank you

### To Reproduce

This is the code I used:

```
import { createDirectus, rest, authentication,login,logout,schemaSnapshot} from '@directus/sdk';
import fetch from 'cross-fetch';
import fs from 'fs';

const URL = 'http://127.0.0.1:8055';
const email='admin@example.com';
const password='admin'



async function exportSchema(){
    try{
        const client = createDirectus(URL).with(authentication('json')).with(rest());
        let {access_token}=await client.request(login(email, password));

        //let schema = await client.request(schemaSnapshot());
        const response = await fetch(`${URL}/schema/snapshot?access_token=${access_token}`);
        const { data } = await response.json();
        let schema = JSON.stringify(data,null,4);
        fs.writeFileSync('schema.json', schema);
        await client.request(logout(access_token,'json'));
    }catch(error){
        console.error('error exporting schema',error);
    }
}


exportSchema()
```

### Directus Version

11.1.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
> From the documentation I am not able to understand how to use it.

Considering in the code here you're not actually using the SDK authentication handler to login or logout or handle tokens it doesnt matter how it is configured (you can remove the obsolete `.with(authentication())` part, more info here https://docs.directus.io/guides/sdk/authentication.html#using-the-authentication-composable)

The approach you've taken here is the "manual REST" approach to authentication where you are in full control of storing tokens, sending them with requests and refreshing them. https://docs.directus.io/guides/sdk/authentication.html#using-the-rest-composable

Using this approach here you'll want to use the `withToken` helper on requests that require authentication:
```js
let schema = await client.request(withToken(schemaSnapshot(), access_token));
```

(or switch the code up and make use of the authentication handler in the SDK)

**Comment by emabiz** [comment]
Thank you,
this works:
```
import { createDirectus, rest, login,logout,withToken,schemaSnapshot} from '@directus/sdk';
import fetch from 'cross-fetch';
import fs from 'fs';

const URL = 'http://127.0.0.1:8055';
const email='admin@example.com';
const password='admin'



async function exportSchema(){
    try{
        const client = createDirectus(URL).with(rest());
        let {access_token}=await client.request(login(email, password));

        let schema = await client.request(withToken(access_token,schemaSnapshot()));
        let schema_str = JSON.stringify(schema,null,4);
        fs.writeFileSync('schema.json', schema_str);
        await client.request(logout(access_token,'json'));
    }catch(error){
        console.error('error exporting schema',error);
    }
}

exportSchema()
```

if authentication is obsolete as you said, I will not try to use it

**Comment by emabiz** [comment]
Ah, then how to use it with schemaSnapshot?

**Comment by emabiz** [comment]
Thank you,
your example is perfectly working.
Before to open this issue I tried to use the documentation, but without success. The reason seems that it is mandatory to specify 'json' as parameter of authentication, at least this is what I have to do on my pc. Otherwise only login works, but not refresh and logout (and also the schemaSnapshot of the previous example is not working)
```
//example from official documentation
async function tryAuthentication(){
	try{
		//const client = createDirectus(URL).with(rest()).with(authentication('json')); //working
		//const client = createDirectus(URL).with(authentication('json')); //working
		const client = createDirectus(URL).with(authentication()); //not working
		
		console.log('before login');
		await client.login(email, password);
		console.log('after login');
		
		console.log('before refresh');
		await client.refresh();
		console.log('after refresh');
		
		console.log('before logout');
		await client.logout();
		console.log('after logout');
		
	}catch(error){
        console.error('error tryAuthentication',error);
    }
}
```

**Comment by br41nslug** [comment]
> The reason seems that it is mandatory to specify 'json' as parameter of authentication, at least this is what I have to do on my pc.

This is likely because you are not running this code inside a browser from the looks of it, both the `cookie` mode and its successor `session` mode rely on cookies to store the credentials which are generally only available in browsers (out-of-the-box) and will fail if there is no cookie storage available.

**Comment by emabiz** [comment]
Is this correct?
![image](https://github.com/user-attachments/assets/527e1e0b-8fdb-4033-a545-d31faa6903f7)

**Comment by br41nslug** [comment]
This is correct for the HTTP API / REST (for which these docs were originally written) however the SDK authentication component defaults to `session` (which is why this example explicitly defines `'json'` so it works on copy-paste)

**Comment by emabiz** [comment]
Anyway, I undertood from your example how to use it.
Thank you again
