### ISSUE TITLE
add a way to filter a collection from the other way

### ISSUE THREAD

**Issue by N0SAFE** [directus/directus#23982]
### Describe the Improvement

inside the directus_file there is no fields for the directus user if this file used as an avatar and it is normal because the directus_files can be used inside many other collection
but the probleme is that i can't filter to read the directus_file when the file is an avatar used by the current user because the filter is made that we can just filter by the fields of the actual collection
what i can suggest is to change the way the filter work to be able to filter on a collection from the other side like from the directus user that is connected to the file because in this way we can access the property avatar
![image](https://github.com/user-attachments/assets/991cda29-a877-41b3-b1de-ab828b54112d)

**Comment by rijkvanzanten** [comment]
You can setup a one-to-many interface on `directus_users` yourself to add that filter in 🙂 I don't want to auto-add every one to many for m2o fields, as that can quickly become overwhelming
