### ISSUE TITLE
Array Indexing in Templated Expressions Works in URL Path Parameters but Fails in JSON Payloads in Directus Flows

### ISSUE THREAD

**Issue by scharez** [directus/directus#23989]
### Describe the Bug

Hey there!

When triggering a flow in Directus, array indexing within expressions (e.g., {{$trigger.body.keys[0]}}) works correctly when used in URL path parameters to a webhook endpoint. However, the same expression fails when placed within a JSON payload in the request body.

The body results to {}

### To Reproduce

1. Create a flow in Directus that triggers a webhook endpoint.
2. In the flow configuration:
- Use {{$trigger.body.keys[0]}} as a URL path parameter in the webhook, which correctly interprets the first element of the keys array.
- Attempt to use {{$trigger.body.keys[0]}} within the JSON payload sent to the same webhook endpoint.
3. Observe that the JSON payload fails to process {{$trigger.body.keys[0]}}, even though it works in the URL path parameter.

### Directus Version

v11.1.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by hanneskuettner** [comment]
Can you share the parts of the JSON payload you are trying to set using the `{{..}}` syntax?

**Comment by scharez** [comment]
@hanneskuettner yes

`{
"count_users": {{$trigger.body.count_users}},
"customer_id": {{$trigger.body.keys[0]}}
}`

This is the payload, which I am sending to my custom endpoint

**Comment by hanneskuettner** [comment]
And the method is set to `POST`? What happens if you hardcode the body?

**Comment by scharez** [comment]
When i hardcode the body it does work and the method is set to post

It also works when i do 

`{ "count_users": {{$trigger.body.count_users}}, "customer_id": {{$trigger.body.keys}} `

Without the array indexing
