### ISSUE TITLE
NPM init directus project taking too long to install ->  npm init directus-project@latest cool-website

### ISSUE THREAD

**Issue by techwithtwin** [directus/directus#23988]
### Describe the Bug

`npm  init directus-project@latest cool-website`
This command is taking too long to run

### To Reproduce

Run the command `npm init directus-project@latest cool-website`

### Directus Version

latest

### Hosting Strategy

Self-Hosted (Custom)

**Comment by hanneskuettner** [comment]
Can you specify what you mean by "too long"? Is this a regression that you have noticed when running this command on previous versions?

The speed of the initial project setup is very much dependent on your computer and internet speed, so it might vary vastly under different circumstances.
