### ISSUE TITLE
save the role and policies and the flows when doing an export as yaml 

### ISSUE THREAD

**Issue by N0SAFE** [directus/directus#23984]
### Describe the Improvement

i think it can be a good idea to save also the role, policies and flows when doing an schema export because this thinghs as to be rewrite when doing an import and a lot of thing inside the schema like filter can be base on the id of roles, policies or flows taht are going to change when manually recreating it in the import

**Comment by br41nslug** [comment]
Schema exports are currently intended to just export the structure of your database structure without any content. 
This feature request seems to match your request https://github.com/directus/directus/discussions/22110 please upvote and add extra context there if need be 😄
