### ISSUE TITLE
How to config Directus on CentOS Apache  properly

### ISSUE THREAD

**Issue by sitawit** [directus/directus#2399]
I am having difficulty installing Directus on Apache in CentOS.
This is a config in my Apache (Directus install on aaa folder).

Alias /aaa /aaa/public
<Directory /aaa/public>
 Options Indexes FollowSymLinks
 RewriteEngine On
 AllowOverride All
 DirectoryIndex index.php
 DirectoryIndex index.html
 Order allow,deny
 Allow from all
</Directory>

But when I navigate to my domain/cms I have a pop up asking a user and a password. I don't see this in my development environment but I use Windows for development so it can't be compared.

I've never set Apache Auth anywhere so this is very confusing to me. If I removed .htaccess file completely from the public folder. I can open a page but the app will not work. However, I can only see it is related to .htaccess config but inside it, it is only a just a rewrite config.

**Comment by benhaynes** [comment]
What kind of user/pass are being requested? This might have nothing to do with Directus at all... perhaps a specific host issue. Could you post some more info/screenshots?

**Comment by sitawit** [comment]
This is a pop up. When open a /public folder.

<img width="342" alt="popup" src="https://user-images.githubusercontent.com/3954702/60948801-f3bade80-a31d-11e9-93ad-aa8b05e6f197.png">

If I cancel the box, this is what it looks like

![web](https://user-images.githubusercontent.com/3954702/60948838-0d5c2600-a31e-11e9-922b-dc1e4a05fba1.png)
The response header has 401 unauthorized.

The same pop up happen, if I open an admin page. 

![admin page](https://user-images.githubusercontent.com/3954702/60949140-c15db100-a31e-11e9-915e-a4b8270a3044.png)

The API has a 401 as well (/server/ping).

Yes, I agree, it could be a host setting but I can't figure it out. Tt doesn't happen to my other website and it doesn't happen to Directus on my localhost.

**Comment by rijkvanzanten** [comment]
That login box is HTTP Basic Auth. Please double check your Apache config and virtual hosts (besides .htaccess).

Somewhere in these, you're looking for something along the lines of

```
  AuthType Basic
  AuthName "Basic Authentication"
  AuthUserFile /etc/httpd/conf/.htpasswd
  require valid-user
```

This is also most likely the reason that the application itself can't reach the api.

I'm closing this for now as it's a server configuration problem rather than a bug in Directus itself.

**Comment by dev7ch** [comment]
probably your api is located on a server wich requires HTTP Basic auth.

@rijkvanzanten i asked about the extension to integrate this in the team channel, actually i think this could be an easy and effective improvement to allow the app to access the api with HTTP Basic auth.

then the api url would look like e.g. `https://username:password@api.directus.dev`

### Why?

At current dev state of the api (no unit tests, no security standard, no resources to get this done in a few days) it would be bring this application to a higher business level.

Ok, a http basic auth can be cracked quite easy, but at least its a good option too preventing  spam bot to hijack the php mailer or retrieve data.

D`ont forget directus is already quite famous ;)

**Comment by rijkvanzanten** [comment]
> then the api url would look like e.g. https://username:password@api.directus.dev

Which would be publicly visible in the JS config file of the app, which completely negates having the basic auth in the first place.. 😬

**Comment by dev7ch** [comment]
ahh yes 🙈 ... mmh so sth like a middleware on php side would be required to make it secure an possible

**Comment by rijkvanzanten** [comment]
In that case you're adding authentication to the API, which it..... already has 😁

**Comment by sitawit** [comment]
It isn't a bug in Directus but it happens only when I'm trying to install Directus on my server. It doesn't happen to any other project.

I think it is about my server setting and how Directus interact with the server.

First of all, there is no "AuthType" setting anywhere in my configuration. And there are no ".htpasswd" anywhere too.

I'm installing a Suite version of the Directus so API and Admin page are in the same folder.
As you can see, the admin login page can be accessed without asking for any user and password (popup).

But only the API part.

This is very confusing to me. The only possible clue I can think of is the authentication logic of the API itself which isn't wrong but it interacts strangely under this environment but why.

**Comment by sitawit** [comment]
Ok, I think I got some clue. I'll come back to write a solution again.

**Comment by sitawit** [comment]
Alright, it is about the server configuration. The Authentication is very **misleading**. 

I want to set up a Directus Suit as a seperated directory outside web root. I do this using apache alias setting and this conflict with a rewrite rule inside **public** folder. This is where the problem began. I remove all other rewrite rule that conflict with Directus's rule.

And now I got 404 error.

"aaa/public/index.php" not found.

This is rewrite trace.
[perdir /aaa/public/] strip per-dir prefix: /aaa/public/ -> 
[perdir /aaa/public/] applying pattern '^admin/(.*)' to uri ''
[perdir /aaa/public/] strip per-dir prefix: /aaa/public/ -> 
[perdir /aaa/public/] applying pattern '^admin' to uri ''
[perdir /aaa/public/] rewrite '' -> 'index.php?'
split uri=index.php? -> uri=index.php, args=<none>
[perdir /aaa/public/] add per-dir prefix: index.php -> /aaa/index.php
[perdir /aaa/public/] internal redirect with /aaa/public/index.php [INTERNAL REDIRECT]

Actually, this is correct.  But the file is actually existing. I'm confused now.

**Comment by benhaynes** [comment]
@bjgajjar @rijkvanzanten — thoughts? Can we transfer this to App/API, close it, and/or update the Docs with some helpful info?

**Comment by hemratna** [comment]
@benhaynes I think this looks server config. As you suggested, Can we create one repo specific for server configs?

**Comment by benhaynes** [comment]
Cool — let Rijk or I know if you need any blank repos for this!

**Comment by sitawit** [comment]
Thanks, that would be great.

**Comment by hemratna** [comment]
@benhaynes Please create a repo to list out all the server config and give access to me and @bjgajjar.

**Comment by benhaynes** [comment]
Sure thing! Here is the repo, and the whole @directus/api-team has `write` access. Let's plan on organizing all server options within directories of this repo...

https://github.com/directus/server-configs

**Comment by rijkvanzanten** [comment]
Lets also add a big fact disclaimer in the readme of that repo that they're all examples and that your mileage may vary. We still officially only support Apache, as we don't have the resources to make sure that everything works perfectly everywhere all the time.

**Comment by benhaynes** [comment]
All set:

https://github.com/directus/server-configs/blob/master/README.md
