### ISSUE TITLE
Unable to search on list o2m

### ISSUE THREAD

**Issue by u12206050** [directus/directus#24004]
### Describe the Bug

Unable to search, event as admin on the list-m2o component.

![list-m2o-fail](https://github.com/user-attachments/assets/65e6c19c-eefd-4514-a579-8f63a6fcd235)

### To Reproduce

Add m2o relationship and select the list mode. Add enough records and then attempt to search.

### Directus Version

11.1.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Mysql

**Comment by br41nslug** [comment]
Did you mean an o2m relation? as m2o can only have a single value so a list view makes little sense there 🤔

**Comment by u12206050** [comment]
Ah correct o2m

**Comment by hanneskuettner** [comment]
This has been fixed in 11.2.0, see https://github.com/directus/directus/pull/23973
