### ISSUE TITLE
Invalid chunkSize provided - breaking changes in 11.2.x when using gcs-storage-driver

### ISSUE THREAD

**Issue by asitanc** [directus/directus#24001]
### Describe the Bug

After updating from v11.1.2 to the latest v11.2.x the container keeps crashing and restarting with error `Invalid chunkSize provided` 

The endpoint `/server/health` is failing which would in docker/k8s cause problems with healthchecks and restarts.

Even with `TUS_ENABLED` set to `false`, if I don't have `TUS_CHUNK_SIZE` defined with appropriate value such as `1024kb`, it would throw this error as the default value for the `gcs` storage driver is incorrect.

Docs:
https://github.com/directus/directus/blob/main/docs/self-hosted/config-options.md

> The TUS_CHUNK_SIZE for storage-driver-gcs must be a power of 2 with a minimum of 256kb (e.g. 256kb, 512kb, 1024kb).

Default value:
https://github.com/directus/directus/blob/main/packages/env/src/constants/defaults.ts#L129

> TUS_CHUNK_SIZE: '10mb',

The default value for the `storage-driver-gcs` for this to work and closest to the `10mb` point would be `8192kb` or `16384kb`

My opinion is that if I have `TUS_ENABLED` set to false, I should not need to set `TUS_CHUNK_SIZE` value at all. 

![firefox_xA9SfSCM3J](https://github.com/user-attachments/assets/bd5ac224-2bf0-4c24-8f15-3169609be68d)

### To Reproduce

I have a deployment with k8s and of course you need gcs storage, otherwise you can have just a config with the database and the storage and thats it.

### Directus Version

v11.2.0 + v11.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Postgresql 16

**Comment by u12206050** [comment]
Also not working even with TUS enabled.

**Comment by u12206050** [comment]
Confirm it works again when setting CHUNK_SIZE to 1024kb
But we don't actually want TUX enabled as we don't want the cron job that gets set with it.

**Comment by schroedan** [comment]
Please correct the default value as it violates the validation rule.

**Comment by keesvanbemmel** [comment]
Found similar issue, confirmed it works again after reverting to 11.1.x

**Comment by ComfortablyCoding** [comment]
> Confirm it works again when setting CHUNK_SIZE to 1024kb But we don't actually want TUX enabled as we don't want the cron job that gets set with it.

As mentioned in the original report `TUS_ENABLED` does not need to be set. The current workaround is to set the `TUS_CHUNK_SIZE` to a valid value for gcs, that will resolve this issue irrespective of the `TUS_ENABLED` value.

#24002 should resolve this issue once merged and released

**Comment by luismts** [comment]
I'm having the same issue. I will test the proposed workaround.
