### ISSUE TITLE
Tweak default status colors

### ISSUE THREAD

**Issue by gavalierm** [directus/directus#24009]
### Describe the Improvement

Because "status" field is "default" system optional field to chose i suggest to add new theme variable like 

- published
- draft
- archived

Because now is set by "primary color" from theme and this is very hard to tweak inside custom CSS - because no explicit class in status component.

In file is defined what color have to be set by default when the status filed is chosen. 

https://github.com/directus/directus/blob/main/app/src/modules/settings/routes/data-model/new-collection.vue

**Comment by rijkvanzanten** [comment]
Those default options are just that: defaults. You can set those colors to be whatever you want! I don't think adding a separate set of variables for something so specific and for something that can easily be configured to whatever you need it to be is something I'd like to do at this point. Thanks!
