### ISSUE TITLE
'clear' does not exist in type 'BuildStorage'

### ISSUE THREAD

**Issue by kevincam3** [directus/directus#24016]
### Describe the Bug

When trying to build the docs from source I the following error: 
`src/cache.ts(43,9): error TS2353: Object literal may only specify known properties, and 'clear' does not exist in type 'BuildStorage'.`

### To Reproduce

From the docs source code run the "build" script in the package.json file

### Directus Version

v11.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
Did you install all the dependencies of the mono repo? Since the docs build part of the packages for generating type docs those are required.

**Comment by kevincam3** [comment]
I did initally install all the dependencies
