### ISSUE TITLE
Translation Split-View always opens with the same language

### ISSUE THREAD

**Issue by eremannisto** [directus/directus#24023]
### Describe the Bug

When selecting the split view for translations, the second view is intended to open with an alternative language. However, the current behavior is that both views are always open with the base language rather than displaying the translation.

<img width="839" alt="issue" src="https://github.com/user-attachments/assets/97c9ce06-7082-4fdd-9172-943b76b9df52">

### To Reproduce

1. Ensure at least 2 languages are configured in the system, such as `en` and `fi`.
2. Within a collection, set a `translation` field.
3. Configure the field to use the `Split-View` mode.
4. When accessing the `translation` field, the expectation is that the second view should display the alternative language (e.g. `fi`), but the current behavior is that both views show the base language (`en`).

<img width="845" alt="reproduce" src="https://github.com/user-attachments/assets/3d2073f2-60b0-499a-b3eb-da4e8a87b074">

### Directus Version

v11.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 15

**Comment by eremannisto** [comment]
1. If a default language is left empty, it will still select the `en` for both
2. If the default language is anything except `en`, it shows the split view as `other`/`en`

So based on this, it seems that the split view's right side always selects the first language from the language collection, even if the language matches the default language.

**Comment by eremannisto** [comment]
Possibly related to [this](https://github.com/directus/directus/commit/261c77bc0497b3c0f996aaed8cae234f5fb5f82f)

**Comment by hanneskuettner** [comment]
> Possible fix already [here](https://github.com/directus/directus/commit/261c77bc0497b3c0f996aaed8cae234f5fb5f82f)?

This was merged a while ago, so if it still is broken (I haven't confirmed that yet) then it might be related but isn't fixed yet.

**Comment by eremannisto** [comment]
I think this is related to this: [23597](https://github.com/directus/directus/pull/23597/commits/e5e20b4120114604d20da02b72765004688dcb7e)

The current logic seems to be reversed, right?

```mermaid
graph TD
    subgraph "❌ Current Logic"
        A1[Check userLanguage.value] -->|exists| B1[Use defaultLanguage.value]
        A1 -->|doesn't exist| C1[Use null]
    end

    subgraph "✅ Correct Logic"
        A2[Check userLanguage.value] -->|exists| B2[Use userLanguage.value]
        A2 -->|doesn't exist| C2[Check defaultLanguage.value]
        C2 -->|exists| D2[Use defaultLanguage.value]
        C2 -->|doesn't exist| E2[Use null]
    end
```
