### ISSUE TITLE
Do you have any hidden bugs?

### ISSUE THREAD

**Issue by elieobeid7** [directus/directus#2403]
I'm looking for an open-source simple, self-hosted headless CMS (not for blogging). Here's my research so far

- Being a laravel guy, haven't found any laravel cms that has a decent rest api, not convinced by October cms. I was told that directus has some package to map eloquent?

- The sheer number of stars on strapi is impressive, tried to run it without docker, too many errors, the issue tracker there is a massacre. 

That brings me to directus and cockpit, both are almost equal with an edge to directus in terms of stars. Things I don't like about cockpit

- I have to use mongodb
-  The issue tracker has more open issues and less active users answering
- The biggest disaster is on [discourse](https://discourse.getcockpit.com/), you find there unforgivable open issues, I start to wonder, how are people are even using strapi or cockpit? there are severe unaddressed problems and bugs on both platforms to the point where they're unusable.

Let's get back to directus then, I didn't try it yet, haven't found any issue, but users on Reddit and HackerNews say they switched from directus to cockpit because the former had too many bugs, UI is broken and some apis didn't work. But the issue tracker is clean, is there some bugs I cannot see? Is there merit to those claims? 

Strapi shook my confidence in headless cms, it is supposed to be the best of the best, la creme de la creme.

**Comment by rijkvanzanten** [comment]
Heya! 

I'm at a festival right now, so apologies for the short response to a long question:

There's separate issues for the app and api so the issues are tracked separately too. See https://github.com/directus/app and https://github.com/directus/api. We use GH projects for feature requests and triaging the bugs do check those out too. 

Don't be discouraged in headless cmses as a whole based on experiences with individual implementations 🤗

**Comment by elieobeid7** [comment]
Thank you so much

**Comment by benhaynes** [comment]
Hey @elieobeid7 — these are all newer technologies, and many are open source... but that's no excuse for buggy software or bad UI.

Much of our core team has been busy for months on client projects, but we're finally able to dedicate more full time developers to Directus. So over the next few weeks/months we'll be really focusing on stability and docs. Most of our remaining issues are for specific edge cases, so I'd say give Directus a try and let us know if you run into any problems... we'll be quick to resolve them! 😊

**Comment by herrbomm** [comment]
I implemented translation as described in the docs. When creating the translations inside the "main-content-container", i dont see the radio-buttons to set the state (deleted, draft, published) which means im not able to set the state besides accessing the table of every translated instance to set the individual state there. 

Anyone experience the same issue?

**Comment by elieobeid7** [comment]
@herrbomm I think it might be better if you create a different issue for that

**Comment by herrbomm** [comment]
sorry - misinterpreted the thread-subject ;)

**Comment by rijkvanzanten** [comment]
Ha good point @herrbomm. Lets rename that title to prevent that from happening again 🙂
