### ISSUE TITLE
Item count broken in table view of O2M lists since 11.2.1

### ISSUE THREAD

**Issue by MarkBurvs** [directus/directus#24037]
### Describe the Bug

Since upgrading to Directus 11.2.1, a O2M list in "Table" view always incorrectly shows "No items" despite there being many items in the list.

### To Reproduce

Create a O2M relationship within a collection and set the view to Table view.
Add several items to the list. 
Observe that the item count incorrectly says "No items"

![Screenshot 2024-11-13 at 10 20 10](https://github.com/user-attachments/assets/4ba2a83f-1a0b-4b52-8962-327f3fe0abec)

(related minor issue... the "open in new window" icon at the end of each row also now sometimes overlaps the content of the row)

### Directus Version

v11.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
Good catch! Looks like an oversight in #23973
