### ISSUE TITLE
Changing password of user / deactivating her account : should kill all her connected sessions

### ISSUE THREAD

**Issue by ImaCrea** [directus/directus#24032]
### Describe the Bug

> disclaimer : we're not using the latest Directus version as we're not in a position to do so for the moment. So, I'm sorry if you find out this has been solved meanwhile (this will actually be a valuable info to push to us to update). Given this is security related and that I couldn't find other tickets/PR related to this, I thought there's a reasonable chance it's still active and so opening a ticket would be helpful.

At the moment, if you change the password of an user or even archive her account : any logged in session is not killed and user can keep using the app meanwhile.

### To Reproduce

- Have a user connected to the app
- On another private tab connected as admin, change the password of the connected user or change its status to `archived`
- See that the user is still connected and can keep using the app.

### Directus Version

10.9.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
This was fixed in `v10.11` if i recall correctly

**Comment by ImaCrea** [comment]
Thank you for the fast answer @br41nslug !
