### ISSUE TITLE
Save button should be disabled when M2A linked collection is readonly

### ISSUE THREAD

**Issue by carlo-salinari** [directus/directus#24050]
### Describe the Bug

I have an M2A collection to link various kinds of lab-test results to products in a catalog.

The problem is that when a user with a read-only policy for items in the lab-test results collections opens them, the 'Save' button is still active. This happens even though all fields are clearly grayed out, which can confuse the user.

The correct behavior, I believe, should be for the 'Save' button to also appear grayed out.

![image](https://github.com/user-attachments/assets/143acc9d-2cf6-48c3-bc7d-1d2e020f73ba)

### To Reproduce

Create a M2A collection with some items.
Create a policy for Users that gives them read-only access.
As such a User, open one of the items (see picture above).

### Directus Version

v11.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Postgres 16

**Comment by ComfortablyCoding** [comment]
Potentially resolved by https://github.com/directus/directus/pull/24045
