### ISSUE TITLE
Directus Cloud: If Appearance -> Project  Color is set to white, notifications email link text colour is white on white background

### ISSUE THREAD

**Issue by geoffyuen** [directus/directus#24073]
### Describe the Bug

As per title, if your project color is white, notification emails with links use the text color set to white on a white background. Even using <a> tags with inline styling to set the text to black doesn't work. 

### To Reproduce

1. Set Project Color to white (#ffffff) under Directus Cloud Settings. 
2. Send a notification using the REST api with the message containing urls and email addresses
3. Check your email using anything but Gmail in a browser.

### Directus Version

v11.2.1

### Hosting Strategy

Directus Cloud

**Comment by rijkvanzanten** [comment]
There's quite a lot of things where we're using the project color where matching the project color to the background color would be a bad idea, like buttons, links, etc. 

Even though it might be considered a bug, I'm filing this under a configuration issue. I'd like to keep allowing any hex value in theming properties to allow people to set just the right shade of their brand color, but that does in turn mean there's the ability for people to destroy parts of it by setting it to colors that don't quite work, in this case a pure white project color.

Thanks!
