### ISSUE TITLE
Remove case sensitivity in filter search

### ISSUE THREAD

**Issue by MattatDirectus** [directus/directus#24072]
### Describe the Improvement

Filters should be non-case sensitive be default - if we add something like " around the search term, it could be exact.

**Comment by hanneskuettner** [comment]
If you are referring to the `search` query parameter, that one is already case insensitive. 
If you are referring to filter operators like `_contains`, there a case insensitive variants of most of them, like `_icontains`.

**Comment by hanneskuettner** [comment]
Closing this, as the functionality already exists.
