### ISSUE TITLE
Creating version for singleton fails due to wrong type

### ISSUE THREAD

**Issue by TECHNOFAB11** [directus/directus#24082]
### Describe the Bug

When creating new content versions for a singleton the request contains an int for "item":
```json
{"key":"aaa","name":"aaa","collection":"somesingleton","item":1}
```
It should be a string though (editing the request to make it a string and resending worked fine)

The bug currently results in this error:
```json
{
  "errors": [
    {
      "message": "Invalid payload. \"item\" must be a string.",
      "extensions": {
        "reason": "\"item\" must be a string",
        "code": "INVALID_PAYLOAD"
      }
    }
  ]
}
```

### To Reproduce

Create any singleton and try to create a new version for it

### Directus Version

v11.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
Ahh good find. For regular items, the ID is pulled from the URL making it a string by default. For singletons it's pulled from the data making it the type of the underlying data — in this case an integer
