### ISSUE TITLE
CORS ERROR

### ISSUE THREAD

**Issue by 0xSaurabhx** [directus/directus#24081]
### Describe the Bug

Frontend Error:
![image_2024-11-24_12-58-12](https://github.com/user-attachments/assets/e46c3e5c-77b1-4ade-8589-9497650982e3)

netlify config:
![image_2024-11-24_12-56-13](https://github.com/user-attachments/assets/a9e28edf-b23d-4c40-aa3f-649ab9c254e7)

vite config, proxied api call:
![image_2024-11-24_13-03-42](https://github.com/user-attachments/assets/182a1fc9-a41d-4f53-8845-40eef44f1635)

cors of app service azure:
![image](https://github.com/user-attachments/assets/63c7d720-ce7b-4f57-8cb4-793e897c2945)

I have deployed directus backend on azure app service
My frontend is made using vuejs and i have deployed it on netlify
On local - I am able to login easily but on deployed url i am not able to login.
I am confused which part is giving me error: netlify, azure or directus?

### To Reproduce

Login on my frontend netlify app - it gives error of cors

### Directus Version

v11.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Postgresql

**Comment by pratik149** [comment]
Hi @0xSaurabhx, did you manage to solve it? if yes, how?
