### ISSUE TITLE
Not possible to create policies with REST API

### ISSUE THREAD

**Issue by danieljwestman** [directus/directus#24084]
### Describe the Bug

I'm trying to create policies with the REST API, but it doesn't seem to be working...

### To Reproduce

Sending a POST request to `myhost.com/policies` with the JSON body;

```
{
	"name": "Intern Policy",
	"icon": "verified_user",
	"description": null,
	"admin_access": false,
	"app_access": true
}
```

I'm getting a status `OK 200` but the response is a list with all policies, nothing is created.

### Directus Version

v11.2.2

### Hosting Strategy

Self-Hosted (Custom)

### Database

PostgreSQL

**Comment by rijkvanzanten** [comment]
Hmm odd.. That system endpoint isn't really any different from the others. Are you experiencing similar problems with other endpoints like `/presets`?

**Comment by hanneskuettner** [comment]
Can you provide more info? The `/policies` endpoint is used in the Studio app and works without problems there. 
Since you are receiving a list of policies back, could it be that you are actually making a `GET` request? The `POST` would never return a list of all policies, afaict.

**Comment by danieljwestman** [comment]
Nope, it's a POST request in Postman.. 🤔

**Comment by hanneskuettner** [comment]
Checking all options here: Do you also see the request show up as POST on the server?
