### ISSUE TITLE
Directus Live Demo Sandbox is outdated

### ISSUE THREAD

**Issue by sksar** [directus/directus#24080]
### Describe the Bug

Directus live demo sandbox https://directus.pizza, is outdated, and shows version 10.13.1

### To Reproduce

Go to https://directus.pizza

### Directus Version

v10.13.1

### Hosting Strategy

Directus Cloud

**Comment by rijkvanzanten** [comment]
Thanks for the heads up! @bryantgillespie mind kicking the box? 😄

**Comment by rijkvanzanten** [comment]
Up to date now 🙂 Thanks again~

**Comment by sksar** [comment]
@rijkvanzanten Thank you !!
