### ISSUE TITLE
SSO "Log In with GitHub" fails if GitHub user doesn't have email in profile

### ISSUE THREAD

**Issue by alexey-yarmosh** [directus/directus#24099]
### Describe the Bug

Since the deploy of v11, our users without email in the GitHub profile can't sign up. Error looks like these for them:

<img width="1206" alt="image" src="https://github.com/user-attachments/assets/4c0e53eb-07e0-4a78-9969-64fddbdd14f4">

Looks like the reason is the `email` field, in the `user` object. It has `undefined` value and makes the validation fail:
https://github.com/directus/directus/blob/2991169f82ad5d0c461e82e7fdcb268ef737896c/api/src/services/users.ts#L164-L165

<img width="788" alt="image" src="https://github.com/user-attachments/assets/85dd38f3-55b1-4ee9-96c0-73afd9a46259">

Also nothing related is logged even with TRACE level, only:
```
[17:23:10] GET /admin/login?reason=FAILED_VALIDATION 304 1ms
```

> 

### To Reproduce

- Set up github SSO in Directus v11.
- Sign up with user without email (e.g. https://github.com/test-user-bdf-2)

### Directus Version

v11.2.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
The fix for this should be as easy as making sure that that `data.email` field isn't undefined in the line you already outlined:

https://github.com/directus/directus/blob/2991169f82ad5d0c461e82e7fdcb268ef737896c/api/src/services/users.ts#L164

@alexey-yarmosh wanna open a PR for this? 🙂
