### ISSUE TITLE
v-table html specs issue

### ISSUE THREAD

**Issue by robsoncombr** [directus/directus#24091]
### Describe the Bug

When running in development mode, I see a Vie's recommendation about HTML Specifications for v-table that makes sense to me.

`11:04:31 PM [vite] warning: <th> cannot be child of <thead>, according to HTML specifications. This can cause hydration errors or potentially disrupt future functionality.
284|                    </table-header>
285|                    <thead v-if="loading" class="loading-indicator" :class="{ sticky: fixedHeader }">
286|                            <th scope="colgroup" :style="{ gridColumn: fullColSpan }">
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
287|                                    <v-progress-linear v-if="loading" indeterminate />
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
288|                            </th>
   |  ^^^^^^^^^
  Plugin: vite:vue
  File: /directus/app/src/components/v-table/v-table.vue`

### To Reproduce

Just run the App in Dev and the error will pass in the screen.

`pnpm --filter app dev`

### Directus Version

v11.2.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

not applicable

**Comment by robsoncombr** [comment]
**File:**
[app/src/components/v-table/v-table.vue](https://github.com/directus/directus/blob/v11.2.2/app/src/components/v-table/v-table.vue)

**Current code:**
```
<thead v-if="loading" class="loading-indicator" :class="{ sticky: fixedHeader }">
	<th scope="colgroup" :style="{ gridColumn: fullColSpan }">
		<v-progress-linear v-if="loading" indeterminate />
	</th>
</thead>

```
**Error:**

`11:04:31 PM [vite] warning: <th> cannot be child of <thead>, according to HTML specifications. This can cause hydration errors or potentially disrupt future functionality.
284|                    </table-header>
285|                    <thead v-if="loading" class="loading-indicator" :class="{ sticky: fixedHeader }">
286|                            <th scope="colgroup" :style="{ gridColumn: fullColSpan }">
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
287|                                    <v-progress-linear v-if="loading" indeterminate />
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
288|                            </th>
   |  ^^^^^^^^^
  Plugin: vite:vue
  File: /directus/app/src/components/v-table/v-table.vue`
  
**Fixed code:**
  
```
<thead v-if="loading" class="loading-indicator" :class="{ sticky: fixedHeader }">
	<tr>
		<th scope="colgroup" :style="{ gridColumn: fullColSpan }">
			<v-progress-linear v-if="loading" indeterminate />
		</th>
	</tr>
</thead>
```

**Comment by rijkvanzanten** [comment]
Good shout! Thanks for the PR 🙂

**Comment by robsoncombr** [comment]
Hi @rijkvanzanten
Just f.y.i. left a comment to you at https://github.com/directus/directus/pull/24093/files
Cheers!

**Comment by rijkvanzanten** [comment]
@robsoncombr Not seeing a comment over there, only seeing that my request for change was resolved without change 🤔 Not sure if something went wrong there! 🙂
