### ISSUE TITLE
Field Validation logic not working with is_one_of $CURRENT_USER and custom value

### ISSUE THREAD

**Issue by u12206050** [directus/directus#24103]
### Describe the Bug

When trying to update role on `directus_users`we want to only allow to set it to one of the roles the current user has, or the unassigned role.

However when testing this we get the error: `The following fields have invalid values: Role: Value has to be one of ["role1", "role2", "role3"]` All the current user roles are in the array, except the id for the unassigned role

Doesn't work:
![Screenshot 2024-11-27 at 11 36 08](https://github.com/user-attachments/assets/ed64a175-8c4a-4d4a-9fbd-0326168146f9)

Doesn't work:
![Screenshot 2024-11-27 at 11 36 53](https://github.com/user-attachments/assets/919a2b13-c39c-4bce-8156-447d4f56715b)

### To Reproduce

I think this should be reproducible with any m2m relationship that you can access via $CURRENT_USER.
Set the field validation as shown above, adding an additional custom value that doesn't exist via the $CURRENT_USER.relation.

Attempt to update the field to the custom value.

### Directus Version

11.2.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

mysql

**Comment by licitdev** [comment]
I'm unable to reproduce this issue with either filter on `mysql`. Could you share a screenshot of the junction table used for `directus_users.roles`? 🤔 

```json
{"_and":[{"role":{"_in":["$CURRENT_USER.roles.role","c6e387fd-39f7-436e-9f50-ae4129e8594d"]}},

{"_or":[{"role":{"_in":["$CURRENT_USER.roles.role"]}},{"role":{"_eq":"c6e387fd-39f7-436e-9f50-ae4129e8594d"}}]}]}
```
### Validation filter
![image](https://github.com/user-attachments/assets/5280166b-4ead-40ce-9ad7-aa1962ed0eca)

### Validation working
![image](https://github.com/user-attachments/assets/ad42ca10-d1d5-43c6-9b7e-b367692d93f8)

### M2M relation `roles` in `directus_users` with `directus_roles`
![image](https://github.com/user-attachments/assets/87617628-eaf8-45ad-a5f3-6bed58cf1cc8)

### Junction table
![image](https://github.com/user-attachments/assets/400a13aa-6c6b-4384-8da0-4d453f0a0fe6)
