### ISSUE TITLE
After trying to get more items in flow this issue facing 

### ISSUE THREAD

**Issue by Jeyakumarrathnaselvi** [directus/directus#24104]
### Describe the Bug

![image](https://github.com/user-attachments/assets/feba914d-8ec7-45e0-934b-530bfeb479b6)

I am using it in cloudron

### To Reproduce

Trying to get more items in flow

### Directus Version

V11.2.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL

**Comment by rijkvanzanten** [comment]
There's not enough information here for me to be able to help out or debug what's happening. Please at minimum share what you're trying to achieve, what you've tried so far, and how we can reproduce this issue. Thanks!
