### ISSUE TITLE
Import OAS definition in hoppscotch AIO latest don't work

### ISSUE THREAD

**Issue by Eliophot** [directus/directus#24116]
### Describe the Bug

Importing the OAS definition of a Directus into https://hoppscotch.io/ via URL or file gives an error

### To Reproduce

If I import the URL without a token, it works.
With a token (https://api.ndd.com/server/specs/oas?access_token=xxxxx) to get the full OAS, I get an error.
I can't find out what the problem is, though.

### Directus Version

v11.2.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

MySQL

**Comment by rijkvanzanten** [comment]
I'm curious if this has the same underlying reason as https://github.com/directus/directus/issues/24121 which was resolved in #24123

**Comment by Eliophot** [comment]
ko with the old editor : https://editor.swagger.io/
```
Semantic error at paths./comments/{id}
Declared path parameter "id" needs to be defined as a path parameter at either the path or operation level
Jump to line 0
 ```
~ ok with the news swagger editor : https://editor-next.swagger.io/

```
items: schema
The value of "items" MUST be either a valid JSON Schema or an array of valid JSON Schemas.
```
and
```
All other properties in a "$ref" object are ignored
```

**Comment by rijkvanzanten** [comment]
@Eliophot We just shipped the fix for the other OAS problem in 11.3.1. Mind checking again on that version to see if the problem persisted?

**Comment by Eliophot** [comment]
Hello, 
Unfortunately, I've just tested, no.
I create an issue on Hoppscotch : https://github.com/hoppscotch/hoppscotch/issues/4588
Perhaps ?
Thanks

**Comment by rijkvanzanten** [comment]
I think there's a spec problem in the API output. Lets consolidate and track over on https://github.com/directus/directus/issues/24155 👍🏻
