### ISSUE TITLE
Item search does not work if we have cyrillic symbols

### ISSUE THREAD

**Issue by philosophman** [directus/directus#24117]
### Describe the Bug

If my field in a collection has cyrillic symbols like "Полина" and are enter in search field the first symbol the app will find nothing.
I have started the app as is from docker.

### To Reproduce

- enter cyrillic symbols in a field in your collection
- look for this symbols
expected: an entry should be found.
result: no entry is found.

Data:
![image](https://github.com/user-attachments/assets/a2d821d1-1375-498b-8a0a-41256bb8f1c5)
Search result:
![image](https://github.com/user-attachments/assets/cbf2dcc5-adc3-4d93-9cc3-8ebc20fb6754)

### Directus Version

v11.2.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
What database are you using @philosophman? The search is provided as-is to a `%LIKE%` query in the database, so gut feeling says this is related to the collation or charset of the database in use 🤔

**Comment by philosophman** [comment]
i dont know which database is used in docker-image (available here https://hub.docker.com/r/directus/directus/tags?name=11.2.2).

**Comment by rijkvanzanten** [comment]
Ah, I'm assuming that you're using SQLite then. By default SQLite [only searches with ASCII characters](https://www.sqlite.org/faq.html#q18). For production use, I'd highly recommend using a (managed) database server like Postgres, which in turn also enabled full unicode text search 🙂
