### ISSUE TITLE
 unexpected 'class' (T_CLASS), expecting identifier (T_STRING)

### ISSUE THREAD

**Issue by sfister-tibco** [directus/directus#2412]
Upon completion of installation, I am receiving the "Couldn't reach API" error on the login page at /admin. The apache error log is showing:

PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/html/directus/src/web.php on line 136, referer: http://hostname/admin/

Any ideas?

**Comment by benhaynes** [comment]
Did you check to make sure your server supports our minimum requirements? You'll need to provide a bit more info on your stack/server/setup for us to help with this. In the meantime, I'll close this one since it's almost certainly a configuration error.
