### ISSUE TITLE
Code field interface not working

### ISSUE THREAD

**Issue by danieljwestman** [directus/directus#24131]
### Describe the Bug

Interface shows error message `Unexpected Error`

<img width="937" alt="Screenshot 2024-12-02 at 21 03 41" src="https://github.com/user-attachments/assets/68a1fb46-db92-4bf3-82ad-8c66af222ac3">

### To Reproduce

Add a Code field to a collection. The interface won't work.

<img width="849" alt="Screenshot 2024-12-02 at 21 03 53" src="https://github.com/user-attachments/assets/56c8f7e5-956e-4372-b58d-3fcf1208fbf1">
<img width="835" alt="Screenshot 2024-12-02 at 21 03 58" src="https://github.com/user-attachments/assets/3abf11c4-9f38-46f2-8ec2-ad9462a05a11">

### Directus Version

v11.2.2

### Hosting Strategy

Self-Hosted (Custom)

### Database

PostgreSQL

**Comment by hanneskuettner** [comment]
I tried replicating this in 11.2.1 and was unable to do so.

What browser are you using?
Any info in the browser console as to what the error might be? 
Do you have any conditions or anything set on the interface? 
Does this happen as an admin user or only for users with reduced permissions?
