### ISSUE TITLE
Enum type,tinyint 

### ISSUE THREAD

**Issue by ccrohit** [directus/directus#24132]
### Describe the Bug

What Happen if i have one scenario male, female, transgender. How to defined enum data type their is no option visible in Type.

### To Reproduce

![image](https://github.com/user-attachments/assets/3d021974-e15c-462a-884a-b34fd6c78f2c)

### Directus Version

11.3.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by the-other-dev** [comment]
Hi,

would it make sense for your scenario to define _Choices_? There you can define a set of options that the user can select via radio buttons. It's also mentioned in the documentation: https://docs.directus.io/app/data-model/fields/selection.html#radio-buttons

![directus_example_with_choice](https://github.com/user-attachments/assets/78c37c26-fe5e-4689-b4be-b985e3692ba9)

**Comment by rijkvanzanten** [comment]
Closing this as @the-other-dev's recommendation is the correct approach here 🙂 There's no native `enum` type in Directus atm
