### ISSUE TITLE
"user_created" and "user_updated" fields have misleading thumbnail display template

### ISSUE THREAD

**Issue by gavalierm** [directus/directus#24146]
### Describe the Improvement

The default users fields in all new added collections have "$thumbnail" in display template. And this reflect direct url path?

I you change in interface "Show avatar in circle" nothing happens.

You need to go to display template remove it and add "Avatar Firstname Lastname" as correct tag for "Avatar" instead of "$thumbnail".

Note:
I do not know where the files is in the projects if i will have some time i try to find it and do some PR. But meantime maybe some body knows where templating is and can do PR.

<img width="595" alt="Snímka obrazovky 2024-12-04 o 16 54 21" src="https://github.com/user-attachments/assets/8d5b8566-a64f-4ff3-81eb-6c869a3e2335">
<img width="613" alt="Snímka obrazovky 2024-12-04 o 16 54 04" src="https://github.com/user-attachments/assets/446d3dd8-2ad3-4643-b80d-df8d56771b4c">
<img width="379" alt="Snímka obrazovky 2024-12-04 o 16 53 54" src="https://github.com/user-attachments/assets/4d80674a-21ff-427f-857c-59f67484133b">
<img width="413" alt="Snímka obrazovky 2024-12-04 o 16 53 42" src="https://github.com/user-attachments/assets/73ba3b92-6a5e-46f2-87b5-65b16ab39740">
<img width="565" alt="Snímka obrazovky 2024-12-04 o 16 53 30" src="https://github.com/user-attachments/assets/a75b9b0d-e9cb-4004-bf57-ae5db5664ee3">

**Comment by rijkvanzanten** [comment]
Those templates are defined here:

https://github.com/directus/directus/blob/437c6201d2ef27f0e4692dc76bbe2b7d5c2ceb2f/app/src/modules/settings/routes/data-model/new-collection.vue#L315

**Comment by gavalierm** [comment]
Your link return 404. i think you need replace hash id with "main".

There it is...

I think it have to be

`template: '{{avatar}} {{first_name}} {{last_name}}',`

instead of

`template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}',`

but i can not test this out, because i do not have test enviroment right now

Is there anybody who can test this?

**Comment by rijkvanzanten** [comment]
Looking good! PR was merged, thanks again @gavalierm 🙂
