### ISSUE TITLE
Multiple Edite (required fields don`t work , can save empty)

### ISSUE THREAD

**Issue by pavelIsaa** [directus/directus#24143]
### Describe the Bug

The list has the required fields. When selecting multiple items for editing, I can save items with empty fields.

<img width="1698" alt="image" src="https://github.com/user-attachments/assets/2fd2ccd1-78e0-4d36-b35c-98df19ec8aef">The list has required fields. When selecting multiple items for editing, I can save items with empty fields

### To Reproduce

Add any not-nullable(required) input in the list items, after selecting items for the list. Choose edit action and we can change required fields and save with an empty value.

### Directus Version

v10.13.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Make sure to mark your field as "non nullable" (database setting) besides "Required" (frontend setting).

![image](https://github.com/user-attachments/assets/43b2b321-061a-40dd-8ab7-e17f1b42c452)
![image](https://github.com/user-attachments/assets/d5f1f4ae-2b0c-49cc-9e67-efedf8d39548)

**Comment by pavelIsaa** [comment]
@br41nslug Thanks a lot its help me
