### ISSUE TITLE
Unzipping new releases with winrar drag and drop causes windows explorer to crash

### ISSUE THREAD

**Issue by ezvr** [directus/directus#2414]
something is wrong with the file:
stringWrapperInterface.php

Every time windows is doing the move/replace action called by winrar drag and drop, the transfer stops at said file, freezes windows and crashes explorer.

**Comment by rijkvanzanten** [comment]
I'm wondering if this is something that we can resolve or if there's a problem with WinRar specifically. I can confirm that zipping / unzipping the package seems to be working fine in Linux / macOS environments

**Comment by ezvr** [comment]
We best wait for someone else to try to replicate. It may be on my end as well.

**Comment by 7jp** [comment]
@ezvr you might send it to your friend and ask for checking. 7-zip is also very popular in windows.
