### ISSUE TITLE
Multiple Data Sources

### ISSUE THREAD

**Issue by selcukbeyhan** [directus/directus#24153]
### Describe the Request

Hello,

Can I manage data from multiple data sources or do I have to use the database I configured at the setup?

Thank you.

### Maintenance Strategy

No specific expectation.

**Comment by rijkvanzanten** [comment]
As of right now, Directus uses the configured database for collections/fields. You can interact with third party data sources through flows and extensions, but not for data modeling 👍🏻

**Comment by selcukbeyhan** [comment]
thank you.
