### ISSUE TITLE
directus auth from localhost

### ISSUE THREAD

**Issue by sraihandzaky** [directus/directus#2415]
so I just know directus yesterday, successfully installed it, and want to get the Auth Token.

I tried using: http://localhost:8888/directus/api/1/auth/request-token in postman and It said
The requested URL /directus/api/1/auth/request-token was not found on this server.

does my url incorrect?

*directus in the url is the project folder name in my local directory

**Comment by rijkvanzanten** [comment]
That's the endpoint for version 6 with a very old version of the API. Where did you find the documentation for this? 🤔 

This is the up to date reference on logging in: https://docs.directus.io/api/reference.html#get-auth-token

**Comment by vladaman** [comment]
It's not clear to me how to get access token either. Documentation is not clear on this.

**Comment by rijkvanzanten** [comment]
@vladaman have you seen https://docs.directus.io/api/authentication.html#tokens?

**Comment by easaw** [comment]
> @vladaman have you seen https://docs.directus.io/api/authentication.html#tokens?

This page is now giving a 404, please can you link to the correct information?

thank you

**Comment by rijkvanzanten** [comment]
@easaw see https://docs.directus.io/reference/api/authentication.html
