### ISSUE TITLE
Return query for construction of pagination pagination

### ISSUE THREAD

**Issue by anderson-scherer** [directus/directus#2416]
In the query return, only the return 'data'. In the docutmentation examples a query like '_ / items / articles? Limit = 10 & page = 3' should return 'meta' and 'data', and in my case only 'date' is returned. Can anyone explain why?
Note: Query on public tables. (edited)

**Comment by rijkvanzanten** [comment]
The `meta` parameter can be used to return different meta fields https://docs.directus.io/api/reference.html#metadata
