### ISSUE TITLE
Images not loading after upgrade from 10.13.1 to 10.13.2

### ISSUE THREAD

**Issue by KenElman** [directus/directus#24169]
### Describe the Bug

after upgrading directus from 10.13.1 to 10.13.2 all of the images are giving the error FORBIDDEN.
I further upgraded to 10.13.4 it did not fix the issue.
The db and file folder are showing the correct files.
I've tried to ensure that the folder and file permissions are set as suggested.

### To Reproduce

https://acpdev.pages.dev/en-CA
Imediately after uploading a new image:
![image](https://github.com/user-attachments/assets/88adff46-ae27-42c3-b830-24045c7a6016)

After stopping and restarting the docker:
![image](https://github.com/user-attachments/assets/1376a840-e3b8-491a-aa7e-939378ba7dd6)

### Directus Version

10.13.4

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

MSSQL Server 2016

**Comment by KenElman** [comment]
This is the docker-compose.yml

services:
  directus:
    restart: always
    image: directus/directus:10.13.4
    ports:
      - 2087:8055
    volumes:
      - /home/iterum/cw-dev-qconsole/uploads:/directus/upload
      - /home/iterum/cw-dev-qconsole/extensions:/directus/extensions
    environment:
      KEY: <hidden>
      SECRET: <hidden>
      DB_CLIENT: 'mssql'
      DB_HOST: '10.38.47.112'
      DB_PORT: '1433'
      DB_DATABASE: <hidden>
      DB_USER: <hidden>
      DB_PASSWORD: <hidden>
      DB_OPTIONS__ENCRYPT: 'false'
      DB_CHARSET: 'ISO-8859-1'
      CORS_ENABLED: 'true'
      CORS_ORIGIN: '*'
      CORS_METHODS: 'GET,POST,PATCH,DELETE,OPTION'
      CORS_CREDENTIALS: 'true'
      CORS_ALLOWED_HEADERS: 'Accept,x-Request-With,Content-Type,Authorization,Origin'
      ADMIN_EMAIL:<hidden>
      ADMIN_PASSWORD: <hidden>
      STORAGE_LOCATIONS: 'local'
      STORAGE_LOCAL_DRIVER: 'local'
      STORAGE_LOCAL_ROOT: './uploads'
      EXTENSIONS_PATH: './extensions'
      STORAGE_LOCAL_HEALTHCHECK_THRESHOLD: '750'
      MAX_RELATIONAL_DEPTH: 20
      EMAIL_TEMPLATES_PATH: '/directus/extensions/templates'
      EMAIL_FROM: 'orders@canadawide.ca'
      EMAIL_TRANSPORT: 'sendgrid'
      EMAIL_SENDGRID_API_KEY:<hidden>
      PASSWORD_RESET_URL_ALLOW_LIST: 'https://acpdev.iterum.pro/reset-password,https://devconsole.iterum.pro/admin/reset-password'
      host: '10.38.47.6'
      PUBLIC_URL: 'https://devconsole.iterum.pro'
      ERP_CLIENT: <hidden>
      ERP_KEY: <hidden>
      ERP_USER: <hidden>
      ERP_PASS: <hidden>
      ERP_URL: <hidden>
      REPAY_KEY: <hidden>

**Comment by rijkvanzanten** [comment]
Looks like you made a typo in your configuration. Your volume is `/directus/upload`, but you have Directus configured to `./uploads. That in turn means that all files are deleted whenever the container restarts as it's on the ephemeral container storage rather than the volume.

**Comment by KenElman** [comment]
oh man!!!!!!   Thank you!  I had been staring at this for hours.
Feeling dumb..  but mostly releived.

Have a wonderful day!

**Comment by rijkvanzanten** [comment]
No prob 🙂 I'm relieved it's not a "Directus deletes all files unexpectedly" bug haha
