### ISSUE TITLE
Flows: cannot modify a Run script action (error 403)

### ISSUE THREAD

**Issue by calvarez-lydia** [directus/directus#24162]
### Describe the Bug

I have an admin account on directus, I have this issue when trying to save a **Run Script** action 
`[UNKNOWN] Request failed with status code 403`

  It happens in any flow (existing or not), I can add the **Run Script** action and save it only it contains the default code. As soon as I modify the code, as example putting `return data;` just to see, it fails with the 403. More than that, I also get the error if I only modify the default comment without changing anything.

What can I do ?

Note: it's self hosted but I don't know if docker or custom.

### To Reproduce

Create a **Manual Trigger** on any collection. Add a **Read Data** action, then add a **Run Script** action, modify the script content and try to save.

### Directus Version

v10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
v10.8.2 is about 1 year old at this point, with a myriad of bug fixes in between and I can not reproduce this issue with your information on the current version. 

Do you have the option to upgrade your Directus installation and try reproducing it there?

**Comment by rijkvanzanten** [comment]
Closing this as we're only supporting v10 for security patches. Thanks!
