### ISSUE TITLE
Marketplace not accessible

### ISSUE THREAD

**Issue by arladmin** [directus/directus#24173]
### Describe the Bug

![image](https://github.com/user-attachments/assets/f00f96e4-1e22-4e6c-a3ca-fb6cb2e6c842)

```
{
  "errors": [
    {
      "message": "Request failed with status code 500 Internal Server Error: GET https://registry.directus.io/extensions?limit=10&sort=popular&sandbox=true",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### To Reproduce

.

### Directus Version

v11.3.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Postgres

**Comment by ComfortablyCoding** [comment]
This is not an issue with Directus but the marketplace server. The underlying issue was resolved and the marketplace should be available again.
