### ISSUE TITLE
Directus not working in Firefox 115.18.0esr (64-bit)

### ISSUE THREAD

**Issue by support337** [directus/directus#24182]
### Describe the Bug

Not working in Firefox browser 115.18.0esr (64-bit)

### To Reproduce

Use Firefox 115.18.0esr (64-bit) to access directus admin interface, observe blank screen and the following message in console:

Uncaught TypeError: Intl.Segmenter is not a constructor
    <anonymous> http://192.168.1.1:8055/admin/assets/index.C5tO8wIX.entry.js:1394

### Directus Version

v11.3.2

### Hosting Strategy

Self-Hosted (Custom)

### Database

mysql8

**Comment by hanneskuettner** [comment]
Heya!

Looks like Firefox ESR 115 is officially EOL since a couple of months, see https://endoflife.date/firefox 
Do you have the option to update to the latest ESR version (128)?

**Comment by rijkvanzanten** [comment]
Closing this as Firefox 115 is end of life and shouldn't be relied on. The current version supported by Mozilla is 133, with 128 being the extended support release. Thanks!
