### ISSUE TITLE
Sort field change value on update in a Many To Many relation

### ISSUE THREAD

**Issue by hmnetograycell** [directus/directus#24195]
### Describe the Bug

A have a collection called Banner, BannerElement joined with a BannerBannerElement.
![image](https://github.com/user-attachments/assets/f68b32a5-9bf5-4d44-9cc6-523ced76c382)

At the first time I edit the value of BannerElement the sort field change value.

Before update:
![image](https://github.com/user-attachments/assets/70ccb152-cb11-4bbb-a76a-c6c7cc98b3bf)

After Update Banner 3.
![image](https://github.com/user-attachments/assets/2e4e0099-45c2-4d08-b49f-7a6d500c1a47)

After I re-sort the BannerElements, the problem does not occur. I can edit all the BannerElements without changing the sort.

### To Reproduce

A have a collection called Banner, BannerElement joined with a BannerBannerElement.
![image](https://github.com/user-attachments/assets/f68b32a5-9bf5-4d44-9cc6-523ced76c382)

At the first time I edit the value of BannerElement the sort field change value.

Before update:
![image](https://github.com/user-attachments/assets/70ccb152-cb11-4bbb-a76a-c6c7cc98b3bf)

After Update Banner 3.
![image](https://github.com/user-attachments/assets/2e4e0099-45c2-4d08-b49f-7a6d500c1a47)

After I re-sort the BannerElements, the problem does not occur. I can edit all the BannerElements without changing the sort.

### Directus Version

v11.3.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 16

**Comment by paescuj** [comment]
This has been fixed in #24172 which will be available in the next release 👍
