### ISSUE TITLE
Unable to delete directus_user

### ISSUE THREAD

**Issue by bonito135** [directus/directus#24197]
### Describe the Bug

Unable to delete directus_user
<img width="917" alt="Screenshot 2024-12-11 at 19 46 49" src="https://github.com/user-attachments/assets/9086c15e-91bb-4343-a1cd-233925136350" />

### To Reproduce

Open users directory, invite user, try to delete it.

### Directus Version

11.3.2

### Hosting Strategy

Self-Hosted (Custom)

### Database

PostgreSQL 17.2

**Comment by paescuj** [comment]
It sounds like you're not running Directus with the Docker image. If that's indeed the case, this means you need to manually run the migrations when upgrading to a newer version: https://docs.directus.io/self-hosted/upgrades-migrations.html#upgrading-updating-a-project
In this case it seems like you didn't run the migrations yet and therefore the `directus_comments` collection (introduced in [v11.1.2](https://github.com/directus/directus/releases/tag/v11.1.2)) is missing.

If you did run the migrations or if you're using the Docker image, please check your logs for any issues that occurred during the upgrade.

I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻
