### ISSUE TITLE
Can't create new collection item when creating from triggered flow

### ISSUE THREAD

**Issue by LevelUpGit** [directus/directus#24191]
### Describe the Bug

We created flow that triggers another flow, which creates an item in collection, and it fails with error: 

```json
{
  "name": "DirectusError",
  "message": "Value for field \"item\" in collection \"directus_activity\" can't be null."
}
```

![Screenshot_7](https://github.com/user-attachments/assets/d057173d-3a89-47b7-b83b-a13382979a18)

Create action is standard with permission level "Full access".

Note: Error says it's creating item in "directus_activity", but we are not, we are creating in members collection.

### To Reproduce

1. Create first flow trigger when item is created
2. Create second flow that will create item in separate collection
3. Call second flow from first, you can pass any data.

### Directus Version

v11.3.2

### Hosting Strategy

Self-Hosted (Custom)

### Database

MySQL

**Comment by rijkvanzanten** [comment]
I'm seeing that the key that's returned from that create operation is `null` as well, which is a bit suspicious. Mind sharing a minimal reproduction of a flow configuration that's behaving like this? The output from the `/flows` and `/operations` endpoints would be ideal

**Comment by LevelUpGit** [comment]
It was logic mistake after testing, you can close this issue.
