### ISSUE TITLE
Deleting fields while applying the same snapshot

### ISSUE THREAD

**Issue by bonito135** [directus/directus#24192]
### Describe the Bug

When I try to apply the same schema second time Directus wants to delete fields.

<img width="494" alt="Screenshot 2024-12-10 at 17 23 12" src="https://github.com/user-attachments/assets/a4b1a2ef-5d84-4613-939c-74eba2ed769c">

### To Reproduce

Start new directus instance on clean postgres database with "directus bootstrap", "directus schema apply ./snapshot.yaml" (schema already provided) and "directus start", stop the server and run the same script again.

### Directus Version

11.3.2

### Hosting Strategy

Self-Hosted (Custom)

### Database

PostgreSQL 17.2

**Comment by rijkvanzanten** [comment]
Can you share a schema snapshot where this is happening? Does your pandascore hook do anything that could cause an issue here?
