### ISSUE TITLE
Catch error when Websockets logs is enabled, but Websocket Rest disabled

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#24210]
### Describe the Bug

When using the following config the server won't start due to a missconfiguration.

```
### WebSockets
WEBSOCKETS_ENABLED=true
WEBSOCKETS_REST_ENABLED=false
WEBSOCKETS_GRAPHQL_ENABLED=false
WEBSOCKETS_LOGS_ENABLED=true
```

The problem is, that the wss logs endpoint requires wss rest. In that case either an error should be logged or the wss log should still be disabled, as wss rest is disabled.

**Comment by br41nslug** [comment]
A bit pedantic i know but please use the "bug" template for reporting bugs

**Comment by br41nslug** [comment]
The error is being caused by `WEBSOCKETS_HEARTBEAT_ENABLED` defaulting to `true` even tho REST is disabled, if you explicitly disable the heartbeat the server will start again.
