### ISSUE TITLE
Warning on bundle build

### ISSUE THREAD

**Issue by Silbad** [directus/directus#24217]
### Describe the Bug

When I build an bundle extension, have this warning :

⠹ Building Directus extension..."createElementVNode" is imported from external module "vue" but never used in "src/toto/module.vue?vue&type=script&lang.ts", "src/toto/module.vue", "src/module-test/pages/Contacts.vue?vue&type=script&lang.ts", "src/module-test/pages/Contacts.vue", "src/module-test/components/Navigation.vue" and "src/module-test/pages/Settings.vue?vue&type=script&setup=true&lang.ts".
✔ Done

### To Reproduce

Create bundle extension with module extensions child
build

### Directus Version

v11.3.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

sqlite

**Comment by ComfortablyCoding** [comment]
I haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

### Reproduction Attempt
https://github.com/user-attachments/assets/c4b7ec41-51e3-4787-a1c8-4de5962c422b
