### ISSUE TITLE
All fields exposed for public, even if filtered

### ISSUE THREAD

**Issue by chrney** [directus/directus#24221]
### Describe the Bug

When adding read permissions for "directus_fields", these are available at /fields. Even though I limit anything (fields, or by condition/filtering), I receive all fields when requesting /fields. 

### To Reproduce

Add read access for the public user. Set filters and/or choose what fields to show.

### Directus Version

v11.2.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

MySQL

**Comment by br41nslug** [comment]
The `/fields` endpoint and underlying logic does not support filtering beyond what the core already does based on permissions. You'll always receive all fields you have access to as determined by configured permissions.

I am unable to reproduce this issue, if I enable read permissions on the public permissions I only receive the fields on the `directus_fields` collection.

**Configured Permissions**
![image](https://github.com/user-attachments/assets/73c0901f-a2df-464e-aa0b-43b99daa2580)

**Public /fields**
![image](https://github.com/user-attachments/assets/c3b7420f-ff59-42ee-ad34-1d6538007e88)

**Admin /fields**
![image](https://github.com/user-attachments/assets/076190fc-0eff-467b-be7e-11d3ef361030)
![image](https://github.com/user-attachments/assets/3d558365-45bd-437e-8060-7f30877b9a57)
