### ISSUE TITLE
Flow creates error if field value is 0 (integer)

### ISSUE THREAD

**Issue by Posoroko** [directus/directus#24225]
### Describe the Bug

I have  a collection called activity_record that keeps track of user activity.  It has a filed called "postedArticles" that gets incremented every time the user create a new item in articles collection.

I'm setting up a flow that queries the user's activity_record, and I'm setting up a script that reads the record, increments the value of "postedArticles" and returns the updated record so the "update data" event can update the item.

But, when users get first created, this activityRecord is brand new and the value of "postedArticles" is 0 (number).  this created an error, in the script event.  If the value is 1 or higher, it works fine. but if it's 0, it doesn't work.  Is there a check for falsy values ?

### To Reproduce

new collection: activity_records with user file (m2o pointing to directus_users)

in directus_users: activity_record field (m2o pointing to activity_records)

in the flow:

read data: query the activity_record :{ "filter": { "user" : { "_eq" : {{$accountability.user}} }}}

run script:  
let last = {{$last}}
let record = last[0]

return record.uploadedArticles

### Directus Version

11.0.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Posoroko** [comment]
Actually, run script simply can't return the number 0 .  Is that what's intended ?

**Comment by hanneskuettner** [comment]
> But, when users get first created, this activityRecord is brand new and the value of "postedArticles" is 0 (number). this created an error, in the script event

What is the error you are seeing? 

> Actually, run script simply can't return the number 0 . Is that what's intended ?

This seems to be a visual only bug, where the payload does not show up in the flow logs that a presented in the Studio, I created a new issue for that, see https://github.com/directus/directus/issues/24230

**Comment by Posoroko** [comment]
that's the log I get when my "run script" returns 0
```
{
  "code": "module.exports = async function(data) {\n\tconst record = data.getRecord[0];\n    let num = record.postedFinds\n\trecord.postedFinds = num + 1;\n\treturn 0;\n}"
}
```

**Comment by Posoroko** [comment]
you're right, it's an error. This is the return value of a "run script " that returns 0.  It might be that it doesn't show the payload. I didnt test to see what the payload actually contains.

**Comment by Posoroko** [comment]
You are right, if I pass the payload to another script and return { value: data.$last},  the payload is there and valid

**Comment by hanneskuettner** [comment]
Great! Then I'll close this issue as the fix for the other issue has been merged and will be in the next release.
