### ISSUE TITLE
Strange behavior about images 

### ISSUE THREAD

**Issue by Arsenii-Zhelobetskyi** [directus/directus#24222]
### Describe the Bug

Newly uploaded images to directus_files by an authenticated user are inaccessible if the Public Policy lacks read access, even though the user has full access via their User Policy. This issue affects only new uploads.

### To Reproduce

I have a User Policy with full access to directus_files and a Public Policy with read access to directus_files. When a user uploads an image to directus_files, if the Public Policy includes read access, the user can retrieve and view the uploaded image. However, if the Public Policy lacks read access, newly uploaded images become inaccessible — even to the user who uploaded them.

To clarify, this behavior occurs when the user is authenticated and authorized as a user. Is this behavior intended?

### Directus Version

v11.1.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by ComfortablyCoding** [comment]
I haven't been able to reproduce this based on the given information (see attempt below), so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻


https://github.com/user-attachments/assets/b25c28a2-a7ee-4322-886d-5289a0841ff8
