### ISSUE TITLE
Custom module extension under bundle gives 404 page

### ISSUE THREAD

**Issue by sookoll** [directus/directus#24236]
### Describe the Bug

Standalone module extension worked and got rendered on /admin/<module_id> (/admin/csv-import)
When move this as part of bundle, it is correctly listed in Settings/Extensions and I created new link in Settings/Settings/Modules, but address /admin/<module_id> gives me Error 404 page. 

<img width="423" alt="Screenshot 2024-12-17 at 11 24 30" src="https://github.com/user-attachments/assets/8de15096-355d-4954-958e-b93184c0f0b9" />

<img width="1092" alt="Screenshot 2024-12-17 at 11 21 45" src="https://github.com/user-attachments/assets/1e1e069d-234e-47a8-bcef-c686a4ac0353" />

<img width="848" alt="Screenshot 2024-12-17 at 11 25 21" src="https://github.com/user-attachments/assets/b88f0c48-4509-4a52-ab62-068873762834" />

<img width="518" alt="Screenshot 2024-12-17 at 11 25 55" src="https://github.com/user-attachments/assets/ae4c722d-80b4-48d0-a453-0c6a1a444828" />

What I'm missing here or is it a bug?

### To Reproduce

Create fresh docker compose directus, map your bundle extension to directus extensions folder. 

### Directus Version

v11.3.3

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 13

**Comment by rijkvanzanten** [comment]
Heya! I just tried reproducing this, but have not been able to. Made a new extension bundle using `directus-extension create bundle` and added a module with `pnpm run add module` and it does indeed show up when I pull up `/admin/custom` (`custom` is the default id for a new module).

Did you rebuild the module after changing the ID? Directus will load in the `dist`, not the `src`. If that's not it, is your extension logic source code available somewhere to reproduce? Thanks!

**Comment by rijkvanzanten** [comment]
I'll close this for now as I haven't been able to reproduce based on the instructions given, but am happy to keep discussing down below 👍🏻
