### ISSUE TITLE
To improve `_and` operator in M2M relationship

### ISSUE THREAD

**Issue by james-gates-0212** [directus/directus#24235]
### Describe the Improvement

Directus: 10.4.3

The table 1
```ts
interface A {
  id: number;
  name: string;
  tags: Array<number>;
}
```

The table 2
```ts
interface B {
  id: number;
  name: string;
}
```

The table 3(it is generated by M2M)
```ts
interface A_B {
  id: number;
  A_id: number;
  B_id: number;
  type: 'negative' | 'positive';
}
```

All records have negative and positive tags.

I used the query to search for `negative` + tag1 and `positive` + tag2 as follows.

```ts
const result = directus.request(readItems('A', {
  filter: {
    _and: [
      { A: { type: 'negative', B_id: 1 } },
      { A: { type: 'positive', B_id: 2 } },
    ]
  }
}));
```

But the result is empty. So I updated the query to search for that.

```ts
const AIds = _.intersection(
  ..._.map(
    await Promise.all(
      tagGroups.map(
        async (tagGroup) =>
          await directus.request(
            aggregate('A_B', {
              aggregate: { count: '*' },
              groupBy: ['A_id'],
              query: {
                filter: {
                  _and: [
                    { B_id: { _in: tagGroup.tags } },
                    { type: { _eq: tagGroup.type } },
                  ],
                },
              },
            }),
          ),
      ),
    ),
    (results) => _.map(results, 'A_id'),
  ),
);

const result = directus.request(readItems('A', {
  filter: { id: { _in: [0, ...AIds] } }
}));
```

So I got the correct result that I expected.

But it is a long query sometimes and I think it isn't suitable to search for that.

In this case, how do I use a query for searching records with the tags - `negative` + tag1 and `positive` + tag2?

**Comment by rijkvanzanten** [comment]
I'm not entirely sure what you're trying to achieve.. The query from example 1 is very different from the one in example 2. Both look valid. In a m2m field, you're always querying against a junction table and then related table, so you will end up with a bit more nesting. This is done on purpose, as you can have custom fields on the junction table — just like you have with `type`. I'll close this for now as I don't believe this is a bug in Directus. Thanks!
