### ISSUE TITLE
Users shouldn't be able to delete themselves

### ISSUE THREAD

**Issue by bitsnaps** [directus/directus#24248]
### Describe the Bug

I tried an account using a self-hosted/docker method on a cloud account, I've then created a new user with "admin" and "app" options using the CLI from the command line (shell access).
I played with the UI (create a collection...), then I delete my own account from the newly created user, then I got a bench of errors because of the missing delete user, this is intentionally to mis-use the app to see if my clients (with no shell access) can workaround that issue by they own.

### To Reproduce

- Set up the CMS using the self-hosted/docker method on a cloud account.

- Create a new user with "admin" and "app" permissions via the CLI.

- Log in to the CMS using the newly created user.

- Create a new collection and perform basic operations.

- Attempt to delete the user's own account from the CMS UI.

- Observe the errors and system behavior post-deletion.

- Additional Information:
The issue was tested in a controlled environment to simulate potential misuse by clients with no shell access.
The goal is to ensure that the CMS is robust against such scenarios to maintain data integrity and user experience.

### Directus Version

v11.3.3

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

sqlite

**Comment by br41nslug** [comment]
Can you share the actual errors you're seeing? Errors after deleting users can be because they are still referenced in relation fields like `user_created` or `user_updated` these should however by default prevent the deletion of the user 🤔

**Comment by bitsnaps** [comment]
> Can you share the actual errors you're seeing? Errors after deleting users can be because they are still referenced in relation fields like `user_created` or `user_updated` these should however by default prevent the deletion of the user 🤔

@br41nslug Sorry, I've deleted that user account, what you just said is 100% correct and I totally agree on the root cause of the error. However, it's a common practice to prevent user from deleting their own account (or show a big red warning to say the least) before allowing this action, I'd rather prefer (IMHO) to use another account or just use the CLI to do so.

**Comment by br41nslug** [comment]
> or show a big red warning to say the least before allowing this action

There is a big warning before deleting any user (not specifically yourself)
![image](https://github.com/user-attachments/assets/96d5f826-c70e-4942-a69c-8ac5d0cd4bd4)

> I'd rather prefer (IMHO) to use another account or just use the CLI to do so.

By default non-admin accounts cannot delete themselves unless you explicitly open up those permissions.
![image](https://github.com/user-attachments/assets/dd6daa5a-961d-412a-83f5-fcec66502338)

**Comment by bitsnaps** [comment]
@br41nslug hmm, I'm trying to think from end-user perspective (not from developer side), as end-user If had no other backup admin account, I wouldn't be able to login again to fix that issue, the good news is that we directus doesn't allow deleting the last account (which is presumably the last admin account), so the end-user should open a new support ticket for that issue which could be avoided if we prevent this action beforehand.

If we decided to allow this action, more features would be nice to have, like: giving choice whether user want to keep his own data (cascade-delete), and auto-logout right after this action to avoid raising any runtime issue, that would be nice from UX/UI side.

**Comment by br41nslug** [comment]
> s end-user If had no other backup admin account, I wouldn't be able to login again to fix that issue, the good news is that we directus doesn't allow deleting the last account

This is indeed already prevented :)

> I'm trying to think from end-user perspective (not from developer side)

Who the "end-user" is is very project dependent of course but in this scenario where these restrictions are desired I believe the end-user here should probably be a non-admin user (as those get these requested features out of the box). Admin accounts are privileged accounts that cannot be limited without extensions.

> giving choice whether user want to keep his own data (cascade-delete)

This can be configured at the data-model level by an admin account, "prevent delete" is the default I think. This is handled by the database so is difficult to do on a per-user basis but should apply to any delete action happening in the database.

> and auto-logout right after this action to avoid raising any runtime issue

Would you mind raising this as it's own separate issue as you really should be logged out if you have the permissions to delete yourself.

**Comment by bitsnaps** [comment]
> Would you mind raising this as it's own separate issue as you really should be logged out if you have the permissions to delete yourself.

Okey, in this case this has to be done also for non-admin account, here is a new issue: https://github.com/directus/directus/issues/24258
