### ISSUE TITLE
Filename Issue in Files Collection with Period (.) Symbol

### ISSUE THREAD

**Issue by ramazanhoyladi** [directus/directus#24246]
### Describe the Bug

There is an issue with the **filename_download** field in the Files collection. If the filename contains a period (.) symbol, the downloaded file does not retain the expected name. Instead, it results in an unexpected file name format during the download process. This behavior affects the user experience and could lead to confusion or file mismanagement.

### Proposal for Enhancing Extension Filtering in File Download Names

To improve functionality and flexibility, it is recommended to update the file download name handling mechanism to include enhanced extension filtering. This adjustment would ensure that unsupported or invalid file extensions are automatically flagged or filtered out during the download process.

Key Updates:
- Validate the extension field in the download name to prevent unintended or insecure file downloads.
- Introduce customizable extension filters to allow users to define accepted formats based on their requirements.
- Provide error handling and clear feedback for unsupported extensions to ensure a seamless user experience.
- Support multi-dot extensions (e.g., .tar.gz, .backup.zip) to accommodate complex file formats used in various applications.

By implementing these enhancements, the system will offer better reliability, security, and flexibility in handling diverse file types.

### Directus Version

v11.3.2

### Hosting Strategy

Self-Hosted (Custom)

### Database

Mysql 8.x.x

**Comment by ramazanhoyladi** [comment]
Contextual Example and Detailed Explanation:

Currently, when setting the downloadable filename in the system, if the chosen filename does not explicitly include an extension, the resulting downloaded file may lose its original extension. For instance, consider a file originally named "9.1.5053 - Product A (0005553444).pdf". If we only specify "9.1.5053 - Product A (0005553444)" as the download name (omitting the “.pdf” extension), the system ends up delivering the file as "9.1" without any recognizable extension.

This issue arises because the system attempts to interpret the last portion of the filename after a period as an extension. In more complex filenames, like those containing multiple dots or additional descriptors, the intended download name might be truncated and the correct extension lost. As a result, end users receive files without their proper extensions, potentially causing confusion, difficulty in opening the files, and a negative user experience.

Request:
To address this problem, it is requested that if the user-defined download name does not contain an explicit extension, the system automatically falls back to using the original file’s extension. This ensures that any file, regardless of how many dots or segments are in its name, will still be downloaded with the correct extension—improving clarity, maintainability, and user satisfaction.

**Comment by hanneskuettner** [comment]
> For instance, consider a file originally named "9.1.5053 - Product A (0005553444).pdf". If we only specify "9.1.5053 - Product A (0005553444)" as the download name

This seems to be something that your operating system does automatically. Try renaming a file in your explorer to the latter and you will see that it behaves the same. 

The `filename_download` is meant to replicate the filename that the file should have after the download. If you drop the extension from it your OS will interpret as a file without extension and do whatever it likes with it.

This does not seem to be a problem of Directus. If you want to restrict a user updating the `filename_download` you should be able to restrict it through Access Policies. By default Directus will just use the supplied filename when uploading a file and will expect the `filename_download` to be set to the filename that will work on the users system.

I'm closing this issue as I don't see how Directus could behave better in this situation.
