### ISSUE TITLE
Can't upgrade directus

### ISSUE THREAD

**Issue by mosch** [directus/directus#24262]
### Describe the Bug

When updating directus the `Update Icon Fields Length` migration fails

> directus-1  | [20:20:29.678] INFO: Skipping CLI extensions initialization due to outstanding migrations.
> directus-1  | [20:20:29.691] INFO: Initializing bootstrap...
> directus-1  | [20:20:29.695] INFO: Database already initialized, skipping install
> directus-1  | [20:20:29.696] INFO: Running migrations...
> directus-1  | [20:20:29.707] INFO: Applying Update Icon Fields Length...
> directus-1  | Error: FOREIGN KEY constraint failed
> directus-1  |     at client.transaction.connection (/directus/node_modules/.pnpm/knex@3.1.0_pg@8.13.0/node_modules/knex/lib/execution/runner.js:272:23)

### To Reproduce

Use version 10.13.3 update to 11.x.x

### Directus Version

11.x.x

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Sqlite

**Comment by licitdev** [comment]
I attempted to run the migration from a fresh `10.13.2` SQLite db to `11.3.5`, but could not reproduce this issue.

I think there might be some database inconsistency here, could you check if there are invalid `null` values?

```sql
SELECT * FROM directus_dashboards WHERE icon IS NULL;
SELECT * FROM directus_roles WHERE icon IS NULL;
```

If there is, try updating with the default values and confirm if that fixes the issue.

```sql
UPDATE directus_dashboards SET icon = 'dashboard' WHERE icon IS NULL;
UPDATE directus_roles SET icon = 'supervised_user_circle' WHERE icon IS NULL;
```

<details>

<summary>Upgrade attempt logs</summary>

![image](https://github.com/user-attachments/assets/dbea2014-0f3b-4d7c-bec0-aa2322a0997d)

</details>

**Comment by mosch** [comment]
All entries in these table had an icon set. Also there are no foreign keys defined on the icon anyway. Its stored as plain text without referencing anything. 🤷‍♂️

**Comment by licitdev** [comment]
Thank you for the confirmation. Would you be able to provide the results for these?

```sql
PRAGMA table_info('directus_collections');
PRAGMA table_info('directus_dashboards');
PRAGMA table_info('directus_flows');
PRAGMA table_info('directus_panels');
PRAGMA table_info('directus_presets');
PRAGMA table_info('directus_roles');

PRAGMA foreign_key_list('directus_collections');
PRAGMA foreign_key_list('directus_dashboards');
PRAGMA foreign_key_list('directus_flows');
PRAGMA foreign_key_list('directus_panels');
PRAGMA foreign_key_list('directus_presets');
PRAGMA foreign_key_list('directus_roles');
```

**Comment by mosch** [comment]
Btw, in your log it says that the `Permissions Policies` Migration is executed as well. Not in mine. Looking at my migrations i already have the Permissions Policies migration in the logs. But they should only be run in v11? Maybe this is where the inconsistency was created?

**Comment by licitdev** [comment]
Thank you for providing the info. May I ask if the log from the PR description was the first run or a retry? 

The migration to update icon fields length runs after the permissions policies migration on `v11`, so that should be expected for reruns should the migration error out.

Your database seems to be in an odd state where `ip_access`, `enforce_tfa`, `admin_access`, `app_access` should not be present in `directus_roles`. The following should be the expected data structure after the permissions policies migration.

Do you have a backup of your database prior to the upgrading of Directus? It would be great if you could test a fresh upgrade from `v10` to `v11`.

![image](https://github.com/user-attachments/assets/c385779c-a1d6-4953-951c-3a2fbecc9101)

On the other hand, could you kindly provide the following details?

```sql
PRAGMA table_info('directus_access');
PRAGMA table_info('directus_permissions');
PRAGMA table_info('directus_policies');
PRAGMA table_info('directus_roles');

PRAGMA foreign_key_list('directus_access');
PRAGMA foreign_key_list('directus_permissions');
PRAGMA foreign_key_list('directus_policies');
PRAGMA foreign_key_list('directus_roles');
```

**Comment by mosch** [comment]
```
sqlite> PRAGMA table_info('directus_access');
sqlite> PRAGMA table_info('directus_permissions');
0|id|INTEGER|1||1
1|role|char(36)|0||0
2|collection|varchar(64)|1||0
3|action|varchar(10)|1||0
4|permissions|json|0||0
5|validation|json|0||0
6|presets|json|0||0
7|fields|TEXT|0||0
sqlite> PRAGMA table_info('directus_policies');
0|id|char(36)|0||1
1|name|varchar(100)|1||0
2|icon|varchar(64)|1|'badge'|0
3|description|TEXT|0||0
4|ip_access|TEXT|0||0
5|enforce_tfa|boolean|1|'0'|0
6|admin_access|boolean|1|'0'|0
7|app_access|boolean|1|'0'|0
sqlite> PRAGMA table_info('directus_roles');
0|id|char(36)|1||1
1|name|varchar(100)|1||0
2|icon|varchar(30)|1|'supervised_user_circle'|0
3|description|TEXT|0||0
4|ip_access|TEXT|0||0
5|enforce_tfa|boolean|1|'0'|0
6|admin_access|boolean|1|'0'|0
7|app_access|boolean|1|'1'|0
8|parent|char(36)|0||0
sqlite> PRAGMA foreign_key_list('directus_access');
sqlite> PRAGMA foreign_key_list('directus_permissions');
0|0|directus_roles|role|id|NO ACTION|CASCADE|NONE
sqlite> PRAGMA foreign_key_list('directus_policies');
sqlite> PRAGMA foreign_key_list('directus_roles');
sqlite> 


```

**Comment by licitdev** [comment]
The permissions policies migration looks to have resulted in an invalid state for your DB. 
Could you back up your D, try to revert the migration and re-attempt an upgrade to v11? https://docs.directus.io/self-hosted/upgrades-migrations.html#downgrading-a-project

**Comment by mosch** [comment]
Hey @licitdev – thanks for your support in here. I'm really grateful and this is more than I expected. Thank you. 

Here is how I fixed it: 

1. Manually fix broken foreign key constrains in the db.
2. Check the db for the migration that failed and execute the rest of it manually. 
3. Add the half-failed migration to the executed migrations db.
4. Rerun migrations.
