### ISSUE TITLE
Erroneous quotes around German translation of "Access Policies"

### ISSUE THREAD

**Issue by jonaskohl** [directus/directus#24263]
### Describe the Improvement

There are erroneous quotes around the German translation of "Access Policies".

This is the English version;
![grafik](https://github.com/user-attachments/assets/88f45c7a-695f-4af9-a0d4-7f7f2b33ca48)

And this is the German version:
![grafik](https://github.com/user-attachments/assets/05ec98d8-a92f-4e55-878a-a3809b45af3c)

**Comment by AlexGaillard** [comment]
Closing this out as it's a Crowdin issue and not fixed in the repo

**Comment by rijkvanzanten** [comment]
Thanks for the heads up @jonaskohl 🙂 Our translations are managed through Crowdin which is accessible to anybody through https://locales.directus.io. I see it was since resolved in there, so we'll consider this completed 🙌🏻
