### ISSUE TITLE
[SERVICE_UNAVAILABLE] Couldn't save file

### ISSUE THREAD

**Issue by abbyrobinson13** [directus/directus#24261]
### Describe the Bug

![directus error](https://github.com/user-attachments/assets/48b3887c-2ad3-4641-a524-6fd3cbb64138)
When I upload a file to my production directus I am getting this error (not happening on development when I restart my own docker file) :

{
  "errors": [
    {
      "message": "Couldn't save file e1058a1a-4fb0-4472-99e7-ec6925f63158.pdf",
      "extensions": {
        "code": "SERVICE_UNAVAILABLE",
        "service": "files"
      }
    }
  ]
}

and in the console:

[20:21:04.044] WARN: Couldn't save file 86ab5670-2e9f-4f5a-89cb-9184617afc7e.pdf
[20:21:04.044] WARN: Resolved credential object is not valid
    err: {
      "type": "Error",
      "message": "Resolved credential object is not valid",
      "stack":
          Error: Resolved credential object is not valid

I am able to save other information to directus no problem, it's only when uploading a file. 

I saw a previous thread here with the same issue and the solution was to ensure the directus/uploads file is under user node:node, I can confirm this is correct and the uploads still are not working.

![nodeuploads](https://github.com/user-attachments/assets/68fe8c2a-9f67-4e2f-b7b7-a20da912e4df)

### To Reproduce

Upload a file to directus

### Directus Version

Latest

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by abbyrobinson13** [comment]
Not useful, confirmed my /uploads file is node:node but still having this issue

**Comment by hanneskuettner** [comment]
Just throwing the error message you are seeing into Google points me to AWS S3. Do you have an S3 storage location configured by any chance?

**Comment by abbyrobinson13** [comment]
Yes

**Comment by hanneskuettner** [comment]
Sounds like that is intended? If so, it looks like the credentials might be wrong and making the local `uploads` folder writable does not solve any problems. 

Please refer to https://docs.directus.io/self-hosted/config-options.html#s3-s3 to see which options are available and confirm that the values are correctly set.

**Comment by abbyrobinson13** [comment]
Yes it is intent for holding the files, I can confirm it is set correctly

**Comment by licitdev** [comment]
@abbyrobinson13 Can you provide your config here with the confidential values redacted?

**Comment by robsoncombr** [comment]
hey there!
@abbyrobinson13 I'm wondering if there is any sub-folder that could have wrong permissions or ownership, sometimes this happens here, mainly when we deal with docker volumes. Not saying it is your case, but given the past history on this I would consider it is something to check.

You can run the following find shell command, you can run it inside your Directus container, remember to set the correctly path to uploads root folder.

`find /directus -type d \( \! -user node -o \! -perm 775 \) -exec ls -ld {} +`

I will make a fast demonstration below on how it will look like, I will use my local machine for this so the user here will be 'ubuntu' instead of node, for the record.

```
ubuntu@oci-sampa-n0:~$ pwd
/home/ubuntu

ubuntu@oci-sampa-n0:~$ mkdir -p owner-check-test/depth1/depth2/depth3

ubuntu@oci-sampa-n0:~$ find /home/ubuntu/owner-check-test/ -type d \( \! -user ubuntu -o \! -perm 775 \) -exec ls -ld {} +

ubuntu@oci-sampa-n0:~$ sudo chown root:root owner-check-test/depth1/depth2

ubuntu@oci-sampa-n0:~$ find /home/ubuntu/owner-check-test/ -type d \( \! -user ubuntu -o \! -perm 775 \) -exec ls -ld {} +
drwxrwxr-x 3 root root 4096 Dec 22 11:04 /home/ubuntu/owner-check-test/depth1/depth2
```

So the idea is that if there is any wrongly assigned folder it will show you.

Please let me know if you are able to find anything.

**Comment by abbyrobinson13** [comment]
Hi I did run this in my directus docker container, it did not seem to resolve the issue. 

Getting this as my output 
drwxr-xr-x    2 node     node             6 Dec 21  2022 /directus/uploads

Here is the directus config:

module "directus" {
  source  = "app.terraform.io/project/directus/aws"
  version = "1.4.1"

  name                 = "directus-${lower(local.environment)}"
  domain               = var.directus_domain
  admin_email          = "admin@email.com"
  root_domain          = "project.domain"
  environment          = local.environment
  project_name         = data.terraform_remote_state.shared.outputs.project_name
  company_name         = data.terraform_remote_state.shared.outputs.company_name
  vpc_id               = data.terraform_remote_state.shared.outputs.vpc_id
  cluster_name         = data.terraform_remote_state.shared.outputs.ecs_cluster_name
  ecs_service_role_arn = data.terraform_remote_state.shared.outputs.ecs_service_role_arn
  rds_host             = data.terraform_remote_state.shared.outputs.rds_host
  load_balancer_arn    = data.terraform_remote_state.shared.outputs.load_balancer_arn
  database_user        = "api_${lower(local.environment)}"
  database_password    = local.db_password
  database_name        = lower(local.environment)
  container_env = [
    {
      name  = "EMAIL_FROM"
      value = ""
    },
    {
      name  = "EMAIL_SMTP_HOST"
      value = ""
    },
    {
      name  = "EMAIL_SMTP_PASSWORD"
      value = ""
    },
    {
      name  = "EMAIL_SMTP_PORT"
      value = ""
    },
    {
      name  = "EMAIL_SMTP_SECURE"
      value = "false"
    },
    {
      name  = "EMAIL_SMTP_USER"
      value = ""
    },
    {
      name  = "EMAIL_TRANSPORT"
      value = "smtp"
    },
    {
      name  = "STORAGE_LOCATIONS"
      value = "s3"
    },
    {
      name  = "STORAGE_S3_DRIVER"
      value = "s3"
    },
    {
      name  = "STORAGE_S3_BUCKET"
      value = "media.project.ca"
    },
    {
      name  = "STORAGE_S3_ROOT"
      value = local.environment == "Production" ? "" : "/${lower(local.environment)}"
    },
    {
      name  = "STORAGE_S3_REGION"
      value = "us-west-2"
    },
  ]
  policy_arns = [aws_iam_policy.directus_bucket_permission.arn]
  include_dns = var.include_dns
}

**Comment by ComfortablyCoding** [comment]
Is the bucket public? If not per the above reference you are missing the [`STORAGE_S3_KEY` and `STORAGE_S3_SECRET` settings for your driver](https://docs.directus.io/self-hosted/config-options.html#s3-s3). It would result in a `Resolved credential object is not valid` error most likely.

**Comment by ComfortablyCoding** [comment]
Happy to hear, as this has been resolved I will go ahead and close the issue.
