### ISSUE TITLE
Can't replace the standard liquid templates in docker using EMAIL_TEMPLATES_PATH 

### ISSUE THREAD

**Issue by agorem** [directus/directus#24272]
### Describe the Bug

I am installed Directus as a Docker container
I have created a copy of the 4 standard liquid templates to translate them to Spanish.
I have created a templates volume and I have placed the 4 translated templates.
I have added EMAIL_TEMPLATES_PATH env variable pointing to the templates volume.
When I request the password reset, I always receive the original messages in english.

### To Reproduce

Create a template volume
Add to the template volume the 4 standard templates.
Modify then to identify which template is using.
Add the EMAIL_TEMPLATE_PATH pointing the volume,
Restart the Docker container
Request the password reset

### Directus Version

v11.3.5

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

mysql

**Comment by ComfortablyCoding** [comment]
Can you share a sample of your docker compose as well as a template? 

P.S. You should not need to set the `` as you can load the templates straight into the correct path via the volume definition. 

e.g. 
```
 - ./some-path/templates:/directus/templates
 ```

**Comment by agorem** [comment]
Hi,
I am using the Docker Plesk extension and the standard Directus docker image.
The volumes 
/var/www/.../directus/uploads:/uploads
/var/www/.../directus/extensions:/extensions
/var/www/.../directus/templates:/templates

Like the docker workdir is /directus the volume related env VARS are

EXTENSIONS_PATH=/directus/extensions
STORAGE_LOCAL_ROOT=/directus/uploads
EMAIL_TEMPLATES_PATH=/directus/templates (Setting or not settings this variables doesn't change the result)

The zip include the liquid templates placed in the /directus/templates.

[templates.liquid.es.zip](https://github.com/user-attachments/files/18232960/templates.liquid.es.zip)

**Comment by ComfortablyCoding** [comment]
Can you post the actual templates along with their names? I would prefer not to download a random file. That being said, I have not been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

### Reproduction Attempt
- added `./templates:/directus/templates` as a volume in my docker compose
- created `./templates/password-reset.liquid`
- added the following content
```html
<!doctype html>
<html lang="en">
<head>
	<title></title>
</head>
<body>
	<h1>Hola </h1>
</body>
</html>
```
- triggered a password reset
- received the following email
<img width="382" alt="Screenshot 2024-12-24 at 12 50 36 PM" src="https://github.com/user-attachments/assets/d0b38bfe-3668-492d-9557-1255971b1af8" />

**Comment by agorem** [comment]
Thanks for you support.
I have identified the problem and it is related with volume permissions.
I have uploaded the templates files as zip because the liquid extension is not supported by github
