### ISSUE TITLE
Send Email returns INTERNAL_SERVER_ERROR Cannot convert undefined or null to object after receiving the mail successfully

### ISSUE THREAD

**Issue by omarabdelwahabmb** [directus/directus#24289]
### Describe the Bug

**I'm updating a record that triggers a flow that sends mail.
The mail is received but I get Internal server error as in the following screenshot:**
![Screenshot from 2024-12-26 23-57-07](https://github.com/user-attachments/assets/b6c2def8-8c9e-47d4-b3ca-dd55075b4517)

**I raised the debugging level to TRACE and got the following log:**
[SendEmailBug.txt](https://github.com/user-attachments/files/18256511/SendEmailBug.txt)

**The flow log in the screenshot below shows that all the flow has been executed smoothly:**
![2024-12-27_03-25](https://github.com/user-attachments/assets/d25b56bb-daa2-453c-88be-6a2c17bac481)

**Send Email Operation Config:**
![2024-12-27_03-29](https://github.com/user-attachments/assets/078e4487-1bd8-4d75-ae25-3881ca839d6a)

Docker Environment email vars
      EMAIL_TRANSPORT: "smtp"
      EMAIL_SMTP_HOST: "SMTP_HOSTNAME"
      EMAIL_SMTP_PORT: "465"
      EMAIL_SMTP_USER: "user@examle.com"
      EMAIL_SMTP_PASSWORD: "password"
      EMAIL_FROM: "user@example.com"
      EMAIL_SMTP_SECURE: "true"
      EMAIL_SMTP_IGNORE_TLS: "false"
      EMAIL_SMTP_POOL: "true"
      

### To Reproduce

Mentioned above.

### Directus Version

v11.3.4

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgresSQL 17.2

**Comment by licitdev** [comment]
Is your trigger a `filter` or `action` type?

![image](https://github.com/user-attachments/assets/de87efac-b772-4958-9ccb-33a2c814d291)

If `filter` is used, it's blocking and the payload for the update operation have to be returned. Here's an example of returning the incoming payload in the response body.

![image](https://github.com/user-attachments/assets/ee41f888-e243-447c-a0c4-a536a1d8c5ba)

**Comment by omarabdelwahabmb** [comment]
Thank you so much.
This solved my error.

But I don't notice the difference in the Payload.

It's the same trigger payload when I chose Data of Data of Last Operation:
```javascript
{
  "payload": {
    "title": "P1t"
  },
  "event": "Treatment_Sessions.items.update",
  "keys": [
    "1"
  ],
  "collection": "Treatment_Sessions"
}
``` 

Either I choose Data of Last Operation or $trigger.payload --> The Payload content is the same.

But the Data of Last Operation results in an error, and $trigger.payload doesn't.

**Comment by licitdev** [comment]
When using `$trigger.payload`, the update's payload is set as:

```json
{
    "title": "P1t"
}
```

However the data of your last operation is `mail`, which has no return value. The `item.update` could not proceed with the updating using the `undefined` result if it's a blocking flow.

Glad to know the issue is resolved. 👍

**Comment by omarabdelwahabmb** [comment]
Now I got it.

Many thanks.
