### ISSUE TITLE
Same Field Name for Related Tables

### ISSUE THREAD

**Issue by kotakkreatif** [directus/directus#24283]
### Describe the Bug

I I have 2 table relationships, `Products` and `Product_Categories`.

Both have the same 2 columns, named "`title`", when I am on the `Products` page, the "`title`" column for `Products` and `Product_Categories` only displays the "`title`" data from `Products`. I am unable to display the "`title`" data from `Products_Categories`.

### To Reproduce

`Products` table

![{F786C393-1F62-42F2-83DE-4056B4EFB218}](https://github.com/user-attachments/assets/8febf3f2-cb80-4c54-a017-cdf76275da1d)

`Product_Categories` table

![{C67DF87F-CD24-410B-9366-BF7223E268B4}](https://github.com/user-attachments/assets/7198e603-50f0-4f53-a701-f094526447f8)

M2M relationship on `Products` table, I selected "title" for `Product_Categories` table relation

![{E1BC83BD-A26A-421B-8E74-483900C7F463}](https://github.com/user-attachments/assets/916858d2-87ff-4fda-83d0-82bb1578bb28)

"`title`" field for `Products` table shows the correct data, but "`title`" for the `Produt_Categories` table shows the wrong data from `Products` table

![{174F1EDD-D479-4799-8CB2-D3751D497589}](https://github.com/user-attachments/assets/fe0b1cd2-a954-4a08-a58a-68626aefffcf)

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

MariaDB

**Comment by ComfortablyCoding** [comment]
I haven't been able to reproduce this on the latest version (v11.3.5) based on the given information (see attempt below), so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

### Reproduction Attempt

https://github.com/user-attachments/assets/884413b9-e4d5-4bcb-af77-19980c0cbe18
