### ISSUE TITLE
Could not send mail in "mail" operation

### ISSUE THREAD

**Issue by 0xSaurabhx** [directus/directus#24282]
### Describe the Bug

Directus Logs:
![Screenshot from 2024-12-25 21-42-12](https://github.com/user-attachments/assets/990700e1-e1b7-4e8f-b5bb-3024e5f044b6)

Directus Flow:
![Screenshot from 2024-12-25 21-40-13](https://github.com/user-attachments/assets/08e74a36-8081-4d23-9741-652c138682ef)

server console logs:
2024-12-25T16:01:05.118249421Z [16:01:05.117] ERROR: Could not send mail in "mail" operation
2024-12-25T16:01:05.118273328Z     err: {
2024-12-25T16:01:05.118278015Z       "type": "Error",
2024-12-25T16:01:05.118281665Z       "message": "write EPIPE",
2024-12-25T16:01:05.118284765Z       "stack":
2024-12-25T16:01:05.118287626Z           Error: write EPIPE
2024-12-25T16:01:05.118316124Z               at afterWriteDispatched (node:internal/stream_base_commons:160:15)
2024-12-25T16:01:05.118319287Z               at writeGeneric (node:internal/stream_base_commons:151:3)
2024-12-25T16:01:05.118322437Z               at Socket._writeGeneric (node:net:962:11)
2024-12-25T16:01:05.118325533Z               at Socket._write (node:net:974:8)
2024-12-25T16:01:05.118328847Z               at writeOrBuffer (node:internal/streams/writable:392:12)
2024-12-25T16:01:05.118332213Z               at _write (node:internal/streams/writable:333:10)
2024-12-25T16:01:05.118335066Z               at Writable.write (node:internal/streams/writable:337:10)
2024-12-25T16:01:05.118337987Z               at LastNewline.ondata (node:internal/streams/readable:809:22)
2024-12-25T16:01:05.118341103Z               at LastNewline.emit (node:events:517:28)
2024-12-25T16:01:05.118343876Z               at addChunk (node:internal/streams/readable:368:12)
2024-12-25T16:01:05.118346911Z       "errno": -32,
2024-12-25T16:01:05.118349943Z       "code": "EPIPE",
2024-12-25T16:01:05.118353059Z       "syscall": "write"
2024-12-25T16:01:05.118356180Z     }

I have created flow for sending email as soon as new user is added to directus.users , but in console i keep getting error. above i have attached image of flow

### To Reproduce

Create flow as given in image and create new user.

### Directus Version

v11.3.5

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL

**Comment by rijkvanzanten** [comment]
What email configuration did you set in your env vars? Are you using smtp?

**Comment by mahsamirzapour** [comment]
It's working well, I'm using gmail smtp in my env and works perfectly :D

**Comment by mahsamirzapour** [comment]
@0xSaurabhx do it like this:
env or docker-compose:

EMAIL_FROM="your gmail"
EMAIL_TRANSPORT="smtp"
EMAIL_SMTP_HOST="smtp.gmail.com"
EMAIL_SMTP_PORT=587
EMAIL_SMTP_USER="your gmail"
EMAIL_SMTP_PASSWORD="your app password"
EMAIL_SMTP_NAME="Gmail"

**Comment by 0xSaurabhx** [comment]
> @0xSaurabhx do it like this: env or docker-compose:
> 
> EMAIL_FROM="your gmail" EMAIL_TRANSPORT="smtp" EMAIL_SMTP_HOST="smtp.gmail.com" EMAIL_SMTP_PORT=587 EMAIL_SMTP_USER="your gmail" EMAIL_SMTP_PASSWORD="your app password" EMAIL_SMTP_NAME="Gmail"

      EMAIL_FROM: "support@domain.app"
      EMAIL_TRANSPORT: "smtp"
      EMAIL_SMTP_HOST: "smtp.gmail.com"
      EMAIL_SMTP_PORT: 587
      EMAIL_SMTP_USER: "support@domain.app"
      EMAIL_SMTP_PASSWORD: "vblw bqzd gaii nojq"
      EMAIL_SMTP_NAME: "Gmail"
      
      
      i am getting :
      
      {
  "level": 40,
  "time": 1735198519479,
  "msg": "Invalid login: 535-5.7.8 Username and Password not accepted. For more information, go to\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials d9443c01a7336-219dca0194bsm114804955ad.248 - gsmtp"
}

**Comment by 0xSaurabhx** [comment]
Thanks it worked !, but how can give custom design? I have html templates.

> @0xSaurabhx do it like this: env or docker-compose:
> 
> EMAIL_FROM="your gmail" EMAIL_TRANSPORT="smtp" EMAIL_SMTP_HOST="smtp.gmail.com" EMAIL_SMTP_PORT=587 EMAIL_SMTP_USER="your gmail" EMAIL_SMTP_PASSWORD="your app password" EMAIL_SMTP_NAME="Gmail"

**Comment by ComfortablyCoding** [comment]
> Thanks it worked !, but how can give custom design? I have html templates.
> 
> > @0xSaurabhx do it like this: env or docker-compose:
> > EMAIL_FROM="your gmail" EMAIL_TRANSPORT="smtp" EMAIL_SMTP_HOST="smtp.gmail.com" EMAIL_SMTP_PORT=587 EMAIL_SMTP_USER="your gmail" EMAIL_SMTP_PASSWORD="your app password" EMAIL_SMTP_NAME="Gmail"

See https://docs.directus.io/self-hosted/email-templates.html#email-templates. As the original issue has been resolved I will go ahead and close this as resolved.

**Comment by 0xSaurabhx** [comment]
What if i have html email templates how to use it? and if i self hosted using docker method where to find /templates location?


> > Thanks it worked !, but how can give custom design? I have html templates.
> > > @0xSaurabhx do it like this: env or docker-compose:
> > > EMAIL_FROM="your gmail" EMAIL_TRANSPORT="smtp" EMAIL_SMTP_HOST="smtp.gmail.com" EMAIL_SMTP_PORT=587 EMAIL_SMTP_USER="your gmail" EMAIL_SMTP_PASSWORD="your app password" EMAIL_SMTP_NAME="Gmail"
> 
> See https://docs.directus.io/self-hosted/email-templates.html#email-templates.
> 
> P.S. As the original issue has been resolved I will go ahead and close it

**Comment by ComfortablyCoding** [comment]
> What if i have html email templates how to use it? and if i self hosted using docker method where to find /templates location?
> 
> 
> > > Thanks it worked !, but how can give custom design? I have html templates.
> > > > @0xSaurabhx do it like this: env or docker-compose:
> > > > EMAIL_FROM="your gmail" EMAIL_TRANSPORT="smtp" EMAIL_SMTP_HOST="smtp.gmail.com" EMAIL_SMTP_PORT=587 EMAIL_SMTP_USER="your gmail" EMAIL_SMTP_PASSWORD="your app password" EMAIL_SMTP_NAME="Gmail"
> > 
> > See https://docs.directus.io/self-hosted/email-templates.html#email-templates.
> > 
> > P.S. As the original issue has been resolved I will go ahead and close it
> 
> 

As mentioned in the linked doc all templates are liquid files, it accepts html. See https://liquidjs.com/ for any relevant usage.

Volumes would be utilized for linking the local templates folder to your docker instance. See https://docs.directus.io/self-hosted/docker-guide.html#persistence for a sample volume setup
