### ISSUE TITLE
File permission (Read) did not hide files for user

### ISSUE THREAD

**Issue by Dominic-Preap** [directus/directus#24290]
### Describe the Bug

I created new policy call "Editor" and update `directus_files` Read permission to current uploaded user only and assigned one user to this policy. When I login as editor and go to files, I can see all the fields in there but cannot read it content. 

I should not should any files in if the files are not uploaded by current user. 

### To Reproduce

1.  Create user policy call Editor, choose Reset system permission to  "Recommended Defaulted"
2.  Update Read permission on `directus_files` with "uploaded_by Equal $CURRENT USER"
3.  Create one new user and assign this Editor policy.
4. Login as new user and go to "files" you'll see all files in there but can't read the content. (it should not show anything here)

![image](https://github.com/user-attachments/assets/bdf5265a-a083-4d0f-82e7-cc990bf5bf2b)

![image](https://github.com/user-attachments/assets/568af082-9d01-481a-8142-d717ea23926c)

### Directus Version

v11.3.5

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

MySQL 8

**Comment by licitdev** [comment]
I cannot reproduce this issue. Does the user have a role? 
Policies attached to users are merged with their role permissions.

<details>

<summary>Testing Screenshots</summary>

![image](https://github.com/user-attachments/assets/eb1164ed-f862-4789-be87-f7be44a84037)
![image](https://github.com/user-attachments/assets/d9990d11-c576-4606-9ec8-0f2dc5923060)

</details>

**Comment by Dominic-Preap** [comment]
@licitdev No, I create a policy, then create a role with that policy and assigned to a user.
![image](https://github.com/user-attachments/assets/41f5e13d-382e-430d-b873-15195b6b5d0c)

**Comment by licitdev** [comment]
I'm still unable to reproduce this issue. 🤔 

I wonder if it could be a caching issue, please test if clearing the cache helps https://docs.directus.io/reference/system/utilities.html#clear-the-internal-cache

On a similar note, are you using any CDN for caching?

![image](https://github.com/user-attachments/assets/d24bc3f1-baa9-4e88-baed-4aca41af1195)

**Comment by Dominic-Preap** [comment]
As I try to clear cache, it seem the images are gone, it's probably is caching. Thank you.
