### ISSUE TITLE
Public policy returns 403

### ISSUE THREAD

**Issue by BorisKamp** [directus/directus#24302]
### Describe the Bug

On Directus 11.3.5, I added the following public policies:
<img width="836" alt="Screenshot 2024-12-30 at 13 00 30" src="https://github.com/user-attachments/assets/c16ae587-3988-41a9-bfc0-6acb3f578c68" />
Now when I try to use GQL introspection in Postman, I get zero query options AND a 403 for the settings collection:
<img width="1088" alt="Screenshot 2024-12-30 at 13 01 04" src="https://github.com/user-attachments/assets/3d48e3e7-b529-45bf-bfec-94a8a68eb706" />

Im losing my patience here as I really cannot find the cause of this. Does anybody have a suggestion?

### To Reproduce

See above

### Directus Version

11.3.5

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

pg17

**Comment by hanneskuettner** [comment]
Did you add this policy to the public role as well?

Are you able to access the collection using the REST API instead of the GraphQL API?

**Comment by BorisKamp** [comment]
> Did you add this policy to the public role as well?
> 
> Are you able to access the collection using the REST API instead of the GraphQL API?

Pff silly me, although I do expect it to be like this by default when you initialize Directus for the first time. The Public policy was not connected to the public role indeed.
That solved it, thanks!
