### ISSUE TITLE
Image shows as number in the API request!

### ISSUE THREAD

**Issue by HashemKhalifa** [directus/directus#2436]
Hello,

after calling the API I get all the data normally except the image source file. I'm getting it as a number I don't know why!

I'm using the method getItems to fetch the collection `client.getItems("campaign")`.

I created a file field and uploaded an image!

```
[
  {
    "id": 1,
    "status": "published",
    "created_by": 1,
    "created_on": "2019-09-20 15:37:32",
    "img": 2,
    "title": "Hello world"
  }
]
```

**Comment by rijkvanzanten** [comment]
For others finding this:

Use `?fields=*.*` to fetch all relational information nested.

https://docs.directus.io/api/reference.html#fields
