### ISSUE TITLE
ACL behaviour

### ISSUE THREAD

**Issue by ghena** [directus/directus#2441]
Dear sirs,

I tried to create a new role, using the admin role.
Then I Login and this role is able to edit , maybe also delete, the admin user.

So How it is possible ?
Please let me know.
Regards.

# Bug Report

## Steps to Reproduce

3. Scroll down to '...'

## Technical Details

- Device: [eg: Desktop, iPhone6, etc]
- OS: [eg: MacOS 10.13.6, Windows 10.1803]
- Web Server: [eg: Apache 2.4.37]
- PHP Version: [eg: 7.2.0]
- Database: [eg: MySQL 8.0.12]
- Install Method: [eg: cloned `master` branch]

**Comment by rijkvanzanten** [comment]
Please see the docs: https://docs.directus.io/guides/roles.html or ask on [StackOverflow](https://stackoverflow.com) or the [#support channel on Slack](https://directus.chat)
