### ISSUE TITLE
Can I split the query bus?

### ISSUE THREAD

**Issue by ztj1993** [directus/directus#2451]
I'm very interested in directus table API query, especially the implemented interface method, but I don't want to use directus existing user mode and authority authentication. Can I separate directus API query into a new extension?

Or I can set directus's own data to one db and my own table to another db.

---

The above content comes from software translation.

**Comment by rijkvanzanten** [comment]
I'm not entirely sure what you mean by circumventing the directus user modes, but regarding your second question "Or I can set directus's own data to one db and my own table to another db.", this is currently not possible.

**Comment by ztj1993** [comment]
@rijkvanzanten I mean, I'm very interested in directus's table query API, and I want to use only this part.

I'm looking forward to multiple databases of data.

**Comment by rijkvanzanten** [comment]
See https://docs.directus.io/advanced/api/data.html#fetching-data-within-hooks-and-endpoints for how to use the internal table gateway in custom code.
