### ISSUE TITLE
2FA authentication for Directus

### ISSUE THREAD

**Issue by LukasNavickas** [directus/directus#2460]
I have tried to enable the 2FA for accessing Directus, but there is no "Enable 2FA" button in the User Profile as described in the docs [https://docs.directus.io/guides/auth.html#two-factor-authentication-2fa](https://docs.directus.io/guides/auth.html#two-factor-authentication-2fa)
Is there a way on how I coudl add 2FA to my directus?

Thank you in advance
Lukas

**Comment by LukasNavickas** [comment]
Issue can be resolved, as 2FA can be enabled in the User Profile page. The problem we are having is that we are unable to assign the users to roles, getting the following issue:
`{code: 204, message: "Duplicate key "3-3" for collection "directus_user_roles""}
I'm going to open a new issue concerning this problem`

**Comment by bjgajjar** [comment]
Hey @LukasNavickas - Thanks for taking the time to report the issue.

> The problem we are having is that we are unable to assign the users to roles

This issue is already added in API repo. https://github.com/directus/api/issues/1376
