### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by xiaogangfighting** [directus/directus#2463]
![image](https://user-images.githubusercontent.com/5702303/68650687-926f7a00-0560-11ea-9205-4b87786fa573.png)

[2019-11-12 07:24:40] api[_].ERROR: RuntimeException: Session start failed in /data/directus/directus-master/src/core/Directus/Session/Storage/NativeSessionStorage.php:82
Stack trace:
#0 /data/directus/directus-master/src/core/Directus/Application/CoreServicesProvider.php(871): Directus\Session\Storage\NativeSessionStorage->start
#1 /data/directus/directus-master/vendor/pimple/pimple/src/Pimple/Container.php(118): Directus\Application\CoreServicesProvider->Directus\Application\{closure}
#2 /data/directus/directus-master/src/core/Directus/Container/Container.php(27): Pimple\Container->offsetGet
#3 /data/directus/directus-master/src/core/Directus/Application/CoreServicesProvider.php(719): Directus\Container\Container->get
#4 [internal function]: Directus\Application\CoreServicesProvider->Directus\Application\{closure}
#5 /data/directus/directus-master/src/core/Directus/Hook/Emitter.php(291): call_user_func_array
#6 /data/directus/directus-master/src/core/Directus/Hook/Emitter.php(119): Directus\Hook\Emitter->executeListeners
#7 /data/directus/directus-master/src/core/Directus/Services/AuthService.php(55): Directus\Hook\Emitter->run
#8 /data/directus/directus-master/src/endpoints/Auth.php(50): Directus\Services\AuthService->loginWithCredentials
#9 [internal function]: Directus\Api\Routes\Auth->authenticate
#10 /data/directus/directus-master/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
#11 /data/directus/directus-master/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#12 /data/directus/directus-master/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->__invoke
#13 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#14 /data/directus/directus-master/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#15 [internal function]: Slim\DeferredCallable->__invoke
#16 /data/directus/directus-master/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#17 /data/directus/directus-master/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#18 /data/directus/directus-master/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
#19 /data/directus/directus-master/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
#20 /data/directus/directus-master/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#21 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#22 /data/directus/directus-master/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#23 [internal function]: Slim\DeferredCallable->__invoke
#24 /data/directus/directus-master/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#25 /data/directus/directus-master/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#26 /data/directus/directus-master/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#27 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#28 /data/directus/directus-master/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#29 [internal function]: Slim\DeferredCallable->__invoke
#30 /data/directus/directus-master/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#31 /data/directus/directus-master/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#32 [internal function]: RKA\Middleware\IpAddress->__invoke
#33 /data/directus/directus-master/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#34 [internal function]: Slim\DeferredCallable->__invoke
#35 /data/directus/directus-master/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#36 /data/directus/directus-master/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->Slim\{closure}
#37 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#38 /data/directus/directus-master/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#39 [internal function]: Slim\DeferredCallable->__invoke
#40 /data/directus/directus-master/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#41 /data/directus/directus-master/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(54): Slim\App->Slim\{closure}
#42 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#43 /data/directus/directus-master/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#44 [internal function]: Slim\DeferredCallable->__invoke
#45 /data/directus/directus-master/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#46 /data/directus/directus-master/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#47 /data/directus/directus-master/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#48 /data/directus/directus-master/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#49 /data/directus/directus-master/src/core/Directus/Application/Application.php(161): Slim\App->run
#50 /data/directus/directus-master/public/index.php(5): Directus\Application\Application->run [] []

**Comment by benhaynes** [comment]
Closing due to a lack of information.

**Comment by Pelletan** [comment]
Got the same problem just after updating from v7.11 to v8-rc1
`error: {code: 3, message: "Unauthorized request"}
code: 3
message: "Unauthorized request"`

**Comment by rijkvanzanten** [comment]
That's a different error in a different version. I'm locking this to prevent errors unrelated to the OP to pile on. 

@Pelletan feel free to open a new issue to discuss this in
