### ISSUE TITLE
Possibility to add support for custom file storage

### ISSUE THREAD

**Issue by lvtz** [directus/directus#2472]
Hello,

I'm using other file storage than Amazon S3. I have the possibility to upload files using API, and I wonder is any way to modify the Directus upload function to get it working with my CDN Storage. I'll do it by myself, but please let me know how can I do that and which source components I should touch?

Best,
LVTZ

**Comment by rijkvanzanten** [comment]
Duplicate of https://github.com/directus/docs/issues/238

Please open your issue just once, we see it regardless of what repo its on
