### ISSUE TITLE
Directus 8 Cannot access the API

### ISSUE THREAD

**Issue by HashemKhalifa** [directus/directus#2473]
# Bug Report

## Steps to Reproduce

1. Go to 'directusAPI/public/_/items/collection name'

## Expected Behavior
to see the collection data
## Actual Behavior

```javascript{
    "error": {
        "code": 3,
        "message": "Unauthorized request"
    }
}```

<!-- Any other relevant information, screenshots, or schema files to help explain your problem -->
fresh install with directus v8.0.0-rc.1

I can access the API neither with enabling the public access or token.

## Technical Details

- Device: Desktop
- OS: MacOS 10.15.2
- Web Server: [eg: Apache 2.4.37]
- PHP Version: 7.3.8
- Database: MySQL 57.26
- Directus Release Version:v 8.0.0-rc.1]
- Install Method: cloned

**Comment by rijkvanzanten** [comment]
Do you have a project named _ configured in the /config/ file?

**Comment by HashemKhalifa** [comment]
@rijkvanzanten I think this should be configured during the installation by default!

**Comment by rijkvanzanten** [comment]
It does, did you upgrade from an existing v7 install?

**Comment by HashemKhalifa** [comment]
not at all, this is a fresh installation. the problem is accessing the API

I can't anymore with the token or with public permission.

- Try a fresh installation 
- create a test collection
try to access the API to get whatever collection you made.
I tried it in windows and mac machines

**Comment by rijkvanzanten** [comment]
What did you call your project during install?

**Comment by HashemKhalifa** [comment]
I did try `API` and 'test' 
also, it creates in the config folder a config with the project name

**Comment by rijkvanzanten** [comment]
Ok. In the API, the project name is in the URL. In your example `directusAPI/public/_/items/{collection_name}`, `_` is the project name. So if you don't have a project called `_`, it's not going to work. Try `directusAPI/public/API/items/{collection_name}` or `directusAPI/public/test/items/{collection_name}` instead

**Comment by HashemKhalifa** [comment]
@rijkvanzanten oh, that's totally new to me.
still, with the project name default `_` I think I need to update the documentation :)
