### ISSUE TITLE
Directus Files Interface Duplicating elements on DDBB

### ISSUE THREAD

**Issue by Veiss** [directus/directus#2477]
Directus 7.0.19.

When adding new files from Existing selector, the files are automatically duplicated.
This behaviour doesnt happens if files added from PC, only when selected from existing library.
It not possible to select previus uploaded files because item files appear duplicated. 

To reproduce the issue add Files interface to some collection:
- Add new files from PC to one item.
- Save the item.
- Edit current item adding new file from existing library, not from PC.
- Save.
- Items appear with duplicated files.

Cheers

**Comment by benhaynes** [comment]
@bjgajjar @rijkvanzanten — lets figure out if this is the API or App...

**Comment by Veiss** [comment]
@benhaynes I have this issue in the App.

**Comment by benhaynes** [comment]
Right, but the app is powered by the API, so it could still be either.

**Comment by rijkvanzanten** [comment]
Let's figure out if this still happens in the latest v7 and V8. V7.0.19 is very outdated @benhaynes

**Comment by benhaynes** [comment]
Oh my... I didn't realize this was for 7.0.19! That is _very_ old... over a year old if I'm not mistaken. 

Yes, we'll need to close this one as not replicable. If you still have this issue after updating to a current version we can re-open.
