### ISSUE TITLE
Last estable versión of Directus (Question)

### ISSUE THREAD

**Issue by Veiss** [directus/directus#2478]
What is the last estable versión of directus Suite?
I only view on tags 7.0.19 as last of 7 and release candidate of version 8.
I previously installed version 8 but translations doesnt work as expeted and the 7.0.19 has an issue with files interface.
Thanks a lot!

**Comment by benhaynes** [comment]
`7.11.0` (with a suite version that was different since the App and API wasn't bundled then)
https://github.com/directus/directus/releases
