### ISSUE TITLE
can't load images from remote front-end

### ISSUE THREAD

**Issue by juandjara** [directus/directus#2483]
# Bug Report

## Steps to Reproduce

1. Create a collection with a field image using the admin app
2. Set visibility of the files collection to world readable using the admin app
3. Connect a remote front-end to your API using the public role to obtain the image urls
4. Display the urls obtained for your front-end in a <img /> tag
5. Deploy your front-end to a remote location
6. Images are displayed on localhost but not on the remote host

## Expected Behavior
You can view the images everywhere

## Actual Behavior
You can only view image from localhost or the admin app

## Other Context & Screenshots
The front-end is deployed on now.sh and built with next.js

## Technical Details

- Device: 13 inch MacBook Pro 2017
- OS: MacOS 10.15.1
- Web Server: Last Nginx as of today
- PHP Version:  7.2
- Database: MySQL 8.0.12
- Directus Release Version: v8.0.0-rc.2
- Install Method: LEMP + cloned `master` branch

**Comment by rijkvanzanten** [comment]
The files are statically returned by your webserver, so that shouldn't make a difference between localhost and a live server. What are you using exactly? The `full_url` field in an `<img>` tag?

**Comment by juandjara** [comment]
Yes. full_url in an img tag. I think it may be related to the CORS configuration or some other http-header-related config. I'll send you my nginx configuration later

**Comment by rijkvanzanten** [comment]
Putting any external image source in an `<img>` tag shouldn't cause any cors issues. I would recommend checking out the Nginx config, as the file isn't passed through Directus at all when using `full_url`.

I'll close this as it's not a problem in Directus itself we can fix, as the image isn't served by Directus
