### ISSUE TITLE
Archive project?

### ISSUE THREAD

**Issue by mvhirsch** [directus/directus#2489]
Shouldn't this repository archived, since it was abandoned after introducing https://github.com/directus/app and https://github.com/directus/api?

As far as I know, this repository was the last stable version of v6. Why upgrading to v8 again? Isn't that somehow confusing to people out there, using/developing Directus?

**Comment by mvhirsch** [comment]
I just read in [v8.0.0 release notes](https://github.com/directus/directus/releases/tag/v8.0.0) that Directus is now combined (again). Though I cannot understand why this step was done, it's surely necessary for this project. (Just out of curiosity, why?)

Could you please than archive directus/app and directus/api, signaling to the community that these projects are now abandoned? Since many users might get confused too, this should happen with a clear statement in the README files.

**Comment by rijkvanzanten** [comment]
This repo was never abandoned to begin with. V7 was released on this repo as well. 

Likewise, the app and api repos are still in use

**Comment by mvhirsch** [comment]
I see, thanks for making things a bit clearer!

So how is the development flow? Using app/api merging into this repo? Or the other way around? Clarifying the development flow would help to build code where it belongs :-)

**Comment by rijkvanzanten** [comment]
The app and api repos contain the source code and is where we're building the software. On release, we create a production build for both, and merge them into directus/directus. This allows the user to clone directus/directus and use it directly, without having to do any build step
