### ISSUE TITLE
No thumbnails in file library

### ISSUE THREAD

**Issue by alengodev** [directus/directus#2494]
Hi,

after a fresh install of v.8.1.0 no thumbnails will be generated in the file library.
Creating a collection + entry with a reference to a file, will generate a thumbnail in the assets-folder.

Server: Debian 9 with Apache
PHP Version: 7.2
Database: MySQL 5.7
Directus Release Version: v.8.1.0

**Comment by rijkvanzanten** [comment]
Duplicate of https://github.com/directus/api/issues/1533
