### ISSUE TITLE
Clear value dropdown not showing up in field name

### ISSUE THREAD

**Issue by lluishi93** [directus/directus#2502]
# Bug Report

The dropdown with clear value, reset value and so on is not showing up when clicking in the field's name.

## Steps to Reproduce

1. Go to whatever field you want
2. Try to show the dropdown for clearing and reseting values by click on the field's name

## Expected Behavior

The dropdown should appear

## Actual Behavior

The dropdown is not showing up

## Other Context & Screenshots

![image](https://user-images.githubusercontent.com/14786440/70622016-44ab6780-1c1b-11ea-8319-2045f4692327.png)

## Technical Details

- Device: [eg: Desktop, iPhone6, etc]
- OS: [eg: MacOS 10.13.6, Windows 10.1803]
- Web Server: [eg: Apache 2.4.37]
- PHP Version: [eg: 7.2.0]
- Database: [eg: MySQL 8.0.12]
- Directus Release Version: [eg: v8.0.0-rc.1]
  - App Version: [eg: 7.11.0] (include if Directus Release Version <=`190927A`)
  - API Version: [eg: 2.6.0] (include if Directus Release Version <=`190927A`)
- Install Method: [eg: cloned `master` branch]

**Comment by benhaynes** [comment]
Hey @lluishi93 — could you note why you closed in case someone else has the same issue and finds this ticket?
