### ISSUE TITLE
Getting Server Error

### ISSUE THREAD

**Issue by aynomjb** [directus/directus#2506]
# Bug Report

## Steps to Reproduce

1. The Error Occured while adding a user to Public role

## Actual Behavior
Logs:
[2019-12-12 10:55:33] api[taxwinblog].ERROR: Directus\Permissions\Exception\ForbiddenCollectionReadException: Reading items from "directus_relations" collection was denied in C:\wamp64\www\directus\src\core\Directus\Permissions\Acl.php:993
Stack trace:
#0 C:\wamp64\www\directus\src\core\Directus\Database\TableGateway\BaseTableGateway.php(1141): Directus\Permissions\Acl->enforceReadOnce
#1 C:\wamp64\www\directus\src\core\Directus\Database\TableGateway\RelationalTableGateway.php(1169): Directus\Database\TableGateway\BaseTableGateway->enforceReadPermission
#2 C:\wamp64\www\directus\src\core\Directus\Database\TableGateway\RelationalTableGateway.php(1295): Directus\Database\TableGateway\RelationalTableGateway->fetchItems
#3 C:\wamp64\www\directus\src\core\Directus\Database\TableGateway\RelationalTableGateway.php(879): Directus\Database\TableGateway\RelationalTableGateway->fetchData
#4 [internal function]: Directus\Database\TableGateway\RelationalTableGateway->getItems
#5 C:\wamp64\www\directus\src\core\Directus\Services\AbstractService.php(346): call_user_func_array
#6 C:\wamp64\www\directus\src\core\Directus\Services\AbstractService.php(290): Directus\Services\AbstractService->getDataAndSetResponseCacheTags
#7 C:\wamp64\www\directus\src\core\Directus\Services\ItemsService.php(82): Directus\Services\AbstractService->getItemsAndSetResponseCacheTags
#8 C:\wamp64\www\directus\src\core\Directus\Services\RelationsService.php(76): Directus\Services\ItemsService->findAll
#9 C:\wamp64\www\directus\src\endpoints\Relations.php(33): Directus\Services\RelationsService->findAll
#10 [internal function]: Directus\Api\Routes\Relations->all
#11 C:\wamp64\www\directus\vendor\slim\slim\Slim\Handlers\Strategies\RequestResponse.php(40): call_user_func
#12 C:\wamp64\www\directus\vendor\slim\slim\Slim\Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#13 C:\wamp64\www\directus\src\core\Directus\Application\Http\Middleware\AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#14 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#15 C:\wamp64\www\directus\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#16 [internal function]: Slim\DeferredCallable->__invoke
#17 C:\wamp64\www\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#18 C:\wamp64\www\directus\src\core\Directus\Application\Http\Middleware\AuthenticationMiddleware.php(124): Slim\Route->Slim\{closure}
#19 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#20 C:\wamp64\www\directus\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#21 [internal function]: Slim\DeferredCallable->__invoke
#22 C:\wamp64\www\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#23 C:\wamp64\www\directus\src\core\Directus\Application\Http\Middleware\TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#24 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#25 C:\wamp64\www\directus\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#26 [internal function]: Slim\DeferredCallable->__invoke
#27 C:\wamp64\www\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#28 C:\wamp64\www\directus\src\core\Directus\Application\Http\Middleware\DatabaseMigrationMiddleware.php(15): Slim\Route->Slim\{closure}
#29 [internal function]: Directus\Application\Http\Middleware\DatabaseMigrationMiddleware->__invoke
#30 C:\wamp64\www\directus\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#31 [internal function]: Slim\DeferredCallable->__invoke
#32 C:\wamp64\www\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#33 C:\wamp64\www\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#34 C:\wamp64\www\directus\vendor\slim\slim\Slim\Route.php(268): Slim\Route->callMiddlewareStack
#35 C:\wamp64\www\directus\vendor\slim\slim\Slim\App.php(503): Slim\Route->run
#36 C:\wamp64\www\directus\src\core\Directus\Application\Http\Middleware\AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#37 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#38 C:\wamp64\www\directus\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#39 [internal function]: Slim\DeferredCallable->__invoke
#40 C:\wamp64\www\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#41 C:\wamp64\www\directus\vendor\directus\proxy-detection\src\ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#42 C:\wamp64\www\directus\src\core\Directus\Application\Http\Middleware\ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#43 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#44 C:\wamp64\www\directus\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#45 [internal function]: Slim\DeferredCallable->__invoke
#46 C:\wamp64\www\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#47 C:\wamp64\www\directus\vendor\akrabat\ip-address-middleware\src\IpAddress.php(113): Slim\App->Slim\{closure}
#48 [internal function]: RKA\Middleware\IpAddress->__invoke
#49 C:\wamp64\www\directus\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#50 [internal function]: Slim\DeferredCallable->__invoke
#51 C:\wamp64\www\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#52 C:\wamp64\www\directus\src\core\Directus\Application\Http\Middleware\CorsMiddleware.php(71): Slim\App->Slim\{closure}
#53 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#54 C:\wamp64\www\directus\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#55 [internal function]: Slim\DeferredCallable->__invoke
#56 C:\wamp64\www\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#57 C:\wamp64\www\directus\src\core\Directus\Application\Http\Middleware\ResponseCacheMiddleware.php(62): Slim\App->Slim\{closure}
#58 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#59 C:\wamp64\www\directus\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#60 [internal function]: Slim\DeferredCallable->__invoke
#61 C:\wamp64\www\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#62 C:\wamp64\www\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#63 C:\wamp64\www\directus\vendor\slim\slim\Slim\App.php(392): Slim\App->callMiddlewareStack
#64 C:\wamp64\www\directus\vendor\slim\slim\Slim\App.php(297): Slim\App->process
#65 C:\wamp64\www\directus\src\core\Directus\Application\Application.php(161): Slim\App->run
#66 C:\wamp64\www\directus\index.php(5): Directus\Application\Application->run [] []

## Other Context & Screenshots

on visiting any url 
![directus error](https://user-images.githubusercontent.com/42889941/70707172-8ad8f780-1cfd-11ea-9044-2c42c4b822a9.PNG)

## Technical Details

- Device: [eg: Desktop]
- OS: [, Windows 10.1803]
- Web Server: [eg: Apache 2.4.39]
- PHP Version: [eg: 7.2.18]
- Database: [eg: MySQL 5.7.26]
- Directus Release Version: [eg: v8.0.0-rc.1]

**Comment by benhaynes** [comment]
The public role is not meant to accept users, it is a role to set permissions for when a user/credentials aren't provided. @rijkvanzanten right?

Perhaps we should clarify this on the docs and/or add a clearer error message.

**Comment by rijkvanzanten** [comment]
That's correct. The public role is the role that controls what people without a user account are allowed to do. Assigning a user to the public role is therefore not something you should or can do

**Comment by aynomjb** [comment]
Thank You so much
