### ISSUE TITLE
Couldn't Reach API

### ISSUE THREAD

**Issue by qaribhaider** [directus/directus#2510]
# Bug Report

## Steps to Reproduce

1. Cloned latest version of the directus to the server, using:
`git clone https://github.com/directus/directus.git`
2. Made sure all the requirements are met, including server specifications, details below:
```
Apache 2.4.10 (Debian)
PHP 7.3.12
Tried both MySQL 5.7 and MariaDB 10.3
All PHP extensions are installed and setup-ed
Made sure mod_rewrite and AllowOverride are enabled
Set the document root to the /public directory
```
3. Ran the installer using /admin of the project URL
4. Installed without any issues
5. Redirected to the login page

## Expected Behavior
Login using the set credentials in the setup 

## Actual Behavior
Tries to login using the credentials but is shown the error that "Couldn't Reach API". 

Major issue is that there is no detailed log anywhere else, not in logs folder (which seem to be logging everything else perfectly fine e.g. unauthorized access), not in console logs as well.

I have also made sure there is no caching layer on the server affecting this, including disabling Cloudflare performance and caching for all the URLs.

Shows correct status:
[https://directus.hugbeta.com/server/ping](https://directus.hugbeta.com/server/ping)

## Other Context & Screenshots

[https://directus.hugbeta.com/admin/#/login](https://directus.hugbeta.com/admin/#/login)

<img width="479" alt="Screen Shot 2019-12-16 at 3 57 55 PM" src="https://user-images.githubusercontent.com/7008519/70905258-dbfa2b80-201c-11ea-9973-0472b956edb9.png">

## Technical Details

- Device: Desktop
- OS: MacOS 10.15.1 
- Web Server: Apache 2.4.10
- PHP Version: 7.3.12
- Database: MariaDB 10.3
- Directus Release Version: v8.3.0
- Install Method: Cloned `master` branch

**Comment by benhaynes** [comment]
Thank you @qaribhaider — we're on it!

@rijkvanzanten @bjgajjar @WoLfulus — obviously this same install process works for us and most others, but we're still getting reports of this sort of issue.  Let's figure out what's going on here, and make sure that not only it's fixed... but that we improve the error reporting/logging so that users can actually report what problem they're experiencing.

**Comment by qaribhaider** [comment]
@benhaynes Thank you for the prompt response. I'm more than happy to share the access to my server where I have deployed this with you, if that can help to solve this (I'm already on the Slack channel so you can ping me there)

**Comment by rijkvanzanten** [comment]
@qaribhaider could you verify that Directus has write access to its folders too?

**Comment by qaribhaider** [comment]
@rijkvanzanten I believe so, as it writes to the config folder during the setup and logs folder as I mentioned earlier

**Comment by WoLfulus** [comment]
@qaribhaider have you solved it? I don't see the error on the links you provided

**Comment by qaribhaider** [comment]
@WoLfulus Sorry but how have you tested it? I haven't shared any login details with you yet. Can you please review the details I have shared in the main thread

**Comment by WoLfulus** [comment]
Sorry, I missed the "when you try to login" - usually that message appears just by opening the login screen when you're unable to reach the api. So I assumed it was working. 

I'll be on slack in a few hours though. DM me if you want :)

**Comment by qaribhaider** [comment]
@WoLfulus No worries man, will ping you on Slack, Cheers!

**Comment by rijkvanzanten** [comment]
Could you create a dummy account and send the credentials to either @WoLfulus or myself on Slack? That would help out a lot 🙂

**Comment by qaribhaider** [comment]
@rijkvanzanten shared the details with you and @WoLfulus both :)

**Comment by edenprojectde** [comment]
So I don't know how far it's been discussed  but I want to give a list of common things that do go wrong and should probably have an error message.
1. Check for folder permissions
2. Check for CORS errors(and maybe a tip or tips that help) 
3. Failed DB connection
4. Check for correct boilerplate in DB
5. Check for at least one User in DB if not show info about DB missing at least one user - or - show a registration form? 
6. Also related to the http and https issue, maybe check for wrong protocol too or maybe even make a silent fallback to self select the protocol no matter what the base url is?

**Comment by qaribhaider** [comment]
@edenprojectde No progress on this so far, I have tried to debug from my end as much as possible, but all in vain. The issue with error reporting, as there is no log related to this, and the error is very generic, which could be happening due to a number of reasons. 

Below are my comments on your points:

- **Check for folder permissions**
They are correct, as I can see other logs, e.g. related to base URL redirect to admin URL
- **Check for CORS errors(and maybe a tip or tips that help)**
Tried with allowed origin "*" as well, still doesn't work, I tried to replicate the one similar to demo, the only difference is I have requests routed through nginx
- **Failed DB connection**
As I mentioned, installation goes through successfully, wouldn't happen if db had an issue
- **Check for correct boilerplate in DB**
Its fine, checked with rijkvanzanten 
- **Check for at least one User in DB if not show info about DB missing at least one user - or - show a registration form?**
It is there, tested this with rijkvanzanten as well
- **Also related to the http and https issue, maybe check for wrong protocol too or maybe even make a silent fallback to self select the protocol no matter what the base url is?**
I have tried for both, with or without SSL, force SSL redirect for all calls as well

**Comment by nayabraheel** [comment]
Any progress on this issue, i am facing the same error. changed the allowoverride to all but still nothing.

**Comment by benhaynes** [comment]
Nothing as of now — we would need to debug an actual broken instance, as this is almost certainly a server-specific config/requirements issue.

**Comment by nayabraheel** [comment]
i have changed the httpd.conf as per some recommendation "AllowOverride All" but still nothing.

**Comment by rijkvanzanten** [comment]
@nayabraheel keep in mind that you're problem might be caused by something completely different from the OP. This error is the generic "app couldn't reach the api" error which can be caused by anything that would cause the API to not run at all.

**Comment by qaribhaider** [comment]
@rijkvanzanten @benhaynes I would suggest stronger debugging information, as currently, the error we get is too generic, as mentioned by you it can be caused by multiple reasons. Generic error is not leading us anywhere, as I have tried numerous configuration parameters, and it does not work.

Once the issue here is identified, it needs to be incorporated in the requirements analysis page, which appears before the installation begins for the CMS.

I can confirm that this is related to server configuration, as I have successfully tested the deployment on AWS EBS PHP instance and it worked like a charm. 

The server I'm having this issue on is from Cloudways, Digital Ocean, they spawn instances based on the existing configuration recipes they have. For production, this is the platform I use mostly, as it is fully managed by them. On the other hand, I have used their services for a multitude of PHP based applications, including custom apps, WordPress, Drupal, CodeIgniter, Laravel, Magento, even a nodeJs based app, some apps with SAP third-party integration as well, all of these run smoothly.

**Comment by GraxMonzo** [comment]
Having same problem with `error: {code: null, message: "Session start failed"}` response

**Comment by GraxMonzo** [comment]
ERROR: RuntimeException: Session start failed in /var/www/directus-backend/src/core/Directus/Session/Storage/NativeSessionStorage.php:82

**Comment by GraxMonzo** [comment]
Hurray!
`sudo chown root:nginx /var/lib/php/session`
Solved my problem

**Comment by criscmaia** [comment]
May be completely unrelated, but as it tagged as "not reproducible" I'll share my experience:
I get the same error message detailed by @qaribhaider , but it gets more strange.
If I type one correct username/password it works fine. I can access. Then I can logout and do it again without any problem.
But... if I logout, try to login with wrong credentials it shows me the "Couldn't Reach API" error. Bit strange but okay. Then if I use the same correct credentials I used just before, it doesn't work anymore, at all. It keeps getting the same message.
If I try on a different device, the correct credentials, it works fine.

Summary:
1) correct credentials: works fine
2) logout
3) wrong credentials: "Couldn't Reach API"
4) correct credentials: "Couldn't Reach API"
5) go to the login page on a different device
6) correct credentials: works fine

**Comment by Veiss** [comment]
I have the same issue. In my local enviroments works fine, but in production the authenticate request response was OK, the cookie and the session file was correctly created on browser and lib/php/session, but the login form return  "Couldn't Reach API" message and nothing cant do.
Authenticate post response: 
`{"data":{"user":{"id":"1","status":"active","role":"1","first_name":"Admin","last_name":"User","email":"alex@veiss.com","timezone":"America\/New_York","locale":"es-ES","locale_options":null,"avatar":null,"company":null,"title":null,"external_id":null,"theme":"auto","2fa_secret":null}},"public":true}`
Then it mades a get request to: 
https://apiestadioberria.fundacionvital.eus/project-name/
And response: 
`{"data":{"api":{"requires2FA":false,"project_logo":null,"project_color":"blue-grey-900","project_foreground":{"full_url":"https:\/\/apiestadioberria.fundacionvital.eus\/uploads\/fundacion-estadio\/originals\/53ca9057-5901-5c2f-8456-1461edd02376.svg","url":"\/uploads\/fundacion-estadio\/originals\/53ca9057-5901-5c2f-8456-1461edd02376.svg"},"project_background":{"full_url":"https:\/\/apiestadioberria.fundacionvital.eus\/uploads\/fundacion-estadio\/originals\/373751b6-b5a4-5c15-b581-0c6dfee28f86.jpg","url":"\/uploads\/fundacion-estadio\/originals\/373751b6-b5a4-5c15-b581-0c6dfee28f86.jpg"},"default_locale":"es-ES","telemetry":true,"project_name":"fundacion estadio","project_public_note":null}},"public":true}`

On DDBB appear row on directus_user_sessions

I dont know what happens
Thanks

**Comment by qaribhaider** [comment]
@Veiss My issue is similar to this as well. 

I believe the second call to /project-name should not return public:true. But unfortunately, I haven't got anywhere with this due to the lack of debugging information.

**Comment by Veiss** [comment]
@qaribhaider 
You are corerct, on development enviroment the return response has another key called 'server':

`{"data":{"api":{"version":"8.3.1","requires2FA":false,"database":"mysql","project_logo":null,"project_color":"blue-grey-900","project_foreground":{"full_url":"http:\/\/fundacionestadio8.local\/uploads\/fundacion-estadio\/originals\/53ca9057-5901-5c2f-8456-1461edd02376.svg","url":"\/uploads\/fundacion-estadio\/originals\/53ca9057-5901-5c2f-8456-1461edd02376.svg"},"project_background":{"full_url":"http:\/\/fundacionestadio8.local\/uploads\/fundacion-estadio\/originals\/373751b6-b5a4-5c15-b581-0c6dfee28f86.jpg","url":"\/uploads\/fundacion-estadio\/originals\/373751b6-b5a4-5c15-b581-0c6dfee28f86.jpg"},"default_locale":"es-ES","telemetry":true,"project_name":"fundacion estadio","project_public_note":null},"server":{"max_upload_size":25165824,"general":{"php_version":"7.2.1-1+ubuntu16.04.1+deb.sury.org+1","php_api":"apache2handler"}}}}`

**Comment by Veiss** [comment]
@qaribhaider 
I found a partial solution for my project.
When i put the project on production server, the api calls doesnt works and allways return auth error. Searching on differents sources i found that if i include an additional directive of apache:
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
The api works correctly, but now the admin cant logged. So i put only that directive on https additional directive and set empty on http directive, so i have to call to api using https and use the admin panel from http

**Comment by timchambers** [comment]
I just encountered this problem when signing in with my admin user. I had been working on [enabling S3 storage](https://docs.directus.io/extensions/storage-adapters.html#using-aws-s3), following the docs trying to get composer to install dependencies with moderate success. After that, I could no longer sign into the Directus app with my administrator account, though I noticed another API user I had created was still able to authenticate with the API just fine.

I had 2FA enabled on my admin user account, and after I NULLed the `2fa_secret` field in in my user record in the database, I could once again sign in. I tried enabling 2FA again, but the "Couldn't Reach API" error returned. 2FA is now broken.

So perhaps my form of this issue is related to 2FA breaking after updating composer dependencies? Let me know if there is any more info about my particular set up that I can provide to be helpful.

**Comment by ithiru** [comment]
Got the same error, eventhough the /server/ping returned 200, console shows returns 500
![image](https://user-images.githubusercontent.com/5761990/72719200-61817600-3b9d-11ea-8bc7-00c1c7bc1bd0.png)
![image](https://user-images.githubusercontent.com/5761990/72719205-65ad9380-3b9d-11ea-96be-6cac8f77a016.png)

Tried to switch back to 8.3.1 release, same issue.

**Comment by ithiru** [comment]
Downloaded the code locally and tried to simulate, looks like for some reason the server block is not returned from the response. so this line of code in login.vue is failing and throwing this error that server not found.

![image](https://user-images.githubusercontent.com/5761990/72726018-546c8300-3bad-11ea-9797-94015b34bb60.png)

					const { max_upload_size } = projectInfo.server;

My server is running on apache but proxied by nginx, not sure that would make a difference.

```
{"data":{"api":{"requires2FA":false,"project_logo":null,"project_color":"#263238","project_foreground":null,"project_background":null,"project_public_note":null,"default_locale":"en-US","telemetry":true,"project_name":"CMS"}},"public":true}
```

But pointing to demo.directus.io, returns the server block and works fine.

```
{"data":{"api":{"version":"8.4.0","requires2FA":false,"database":"mysql","project_name":"Thumper","project_logo":{"full_url":"http:\/\/localhost:8080\/uploads\/thumper\/originals\/19acff06-4969-5c75-9cd5-dc3f27506de2.svg","url":"\/uploads\/thumper\/originals\/19acff06-4969-5c75-9cd5-dc3f27506de2.svg"},"project_color":"#4CAF50","project_foreground":{"full_url":"http:\/\/localhost:8080\/uploads\/thumper\/originals\/f28c49b0-2b4f-571e-bf62-593107cbf2ec.svg","url":"\/uploads\/thumper\/originals\/f28c49b0-2b4f-571e-bf62-593107cbf2ec.svg"},"project_background":{"full_url":"http:\/\/localhost:8080\/uploads\/thumper\/originals\/03a06753-6794-4b9a-803b-3e1cd15e0742.jpg","url":"\/uploads\/thumper\/originals\/03a06753-6794-4b9a-803b-3e1cd15e0742.jpg"},"telemetry":true,"default_locale":"en-US","project_public_note":"**Welcome to the Directus Public Demo!**\n\nYou can sign in with `admin@example.com` and `password`. Occasionally users break things, but don’t worry… the whole server resets each hour."},"server":{"max_upload_size":20971520,"general":{"php_version":"7.2.24-0ubuntu0.18.04.2","php_api":"apache2handler"}}}}```

**Comment by ithiru** [comment]
After install the permission table was empty, thought that could be an issue, loaded the demo-data from the demo-data repo, logged in with admin@example.com - still the same issue... not sure this is due to nginx proxy.. 

somehow the service thinks it is public api / not loggeded in, that's why it returns just the public info, and public: true value without the server and api version details..

any clue?

**Comment by benhaynes** [comment]
## Please Read This Before Posting Here

Hey everyone (including @ithiru )... first off, thank you all for helping resolve these issues by providing useful details!!

However, just a reminder that this is a very _general_ error message from the API that is returned when almost anything goes wrong. We're working on getting more detailed error reporting in the new API port, but in the meantime, everyone should probably be opening **individual** tickets for these issues. It doesn't help us to have them all piled in here since they all probably have different root causes.

Thank you! 🐰

**Comment by WoLfulus** [comment]
I've opened a PR to solve OP's request on this one, but maybe it's not the same thing as @benhaynes mentioned. For anyone wondering if it's the same problem, check the PR branch (as it's not merged/released yet) and open a new issue if it persists.

**Comment by ithiru** [comment]
Found the root cause, but don't know why this is happening. When the request comes to Apache the header has both Authorization (with empty array) and Cookies. The below code in src/helpers/all.php checks for access-token, php-auth-user, Authorization and Cookie. Since the apache is receiving Authorization header with empty value, its failing, switching to Check Cookie first and then Authorization worked fine. 

Any idea who sets the Authorization header with empty value? Will try to figure out.!

```
    function get_request_authorization_token(Request $request)
    {
        $response = [];

        if ($request->getParam('access_token')) {
            $response['type'] =  DirectusUserSessionsTableGateway::TOKEN_JWT;
            $response['token'] =  $request->getParam('access_token');
        } elseif ($request->hasHeader('Php-Auth-User')) {
            $response['type'] =  DirectusUserSessionsTableGateway::TOKEN_JWT;
            $authUser = $request->getHeader('Php-Auth-User');
            $authPassword = $request->getHeader('Php-Auth-Pw');

            if (is_array($authUser)) {
                $authUser = array_shift($authUser);
            }

            if (is_array($authPassword)) {
                $authPassword = array_shift($authPassword);
            }

            if ($authUser && (empty($authPassword) || $authUser === $authPassword)) {
                $response['token'] =  $authUser;
            }
        } elseif ($request->hasHeader('Authorization')) {
            $response['type'] =  DirectusUserSessionsTableGateway::TOKEN_JWT;
            $authorizationHeader = $request->getHeader('Authorization');

            // If there's multiple Authorization header, pick first, ignore the rest
            if (is_array($authorizationHeader)) {
                $authorizationHeader = array_shift($authorizationHeader);
            }

            if (is_string($authorizationHeader) && preg_match("/Bearer\s+(.*)$/i", $authorizationHeader, $matches)) {
                $response['token'] = $matches[1];
            }
        } elseif ($request->hasHeader('Cookie')) {
            $response['type'] = DirectusUserSessionsTableGateway::TOKEN_COOKIE;
            $authorizationHeader = $request->getCookieParam(get_project_session_cookie_name($request));
            $response['token'] = $authorizationHeader;
        }
        return $response;
    }
}
```

**Comment by qaribhaider** [comment]
@WoLfulus Man you are brilliant, thank you very much for getting this sorted.

I can confirm that the issue has been fixed.

**Comment by WoLfulus** [comment]
My pleasure! Sorry it took so long!

**Comment by benhaynes** [comment]
Nice job @WoLfulus !!

@ithiru — does this solve it for you too?

**Comment by rijkvanzanten** [comment]
Another potential cause + solution is forced `Cache-Control` headers. If your webserver adds the `cache-control` header to every request, the directus admin app isn't able to differentiate between authenticated and non-authenticated requests

**Comment by azizulhakim-f** [comment]
I am facing this issue in Directus Version 8.7.2 again.
First I faced this issue after upgrading from 8.4 to 8.7 with git pull. 
Then came here and read every issue about this bug. Tried everything listed above.
I though it might be because of some upgrade issues, So I installed Directus again from scratch, but facing same issues.
 
I'm using apache server and every install requirements are met. It was working fine with version 8.4

**Comment by GaneshKandu** [comment]
Hi,

I am also getting same issue in Directus 8.7.2 while login
it doesn't write any log in log file
no error in browser console

![Directus](https://user-images.githubusercontent.com/12833130/83256046-571c5c00-a1cf-11ea-881d-a3884822f057.png)

**Comment by acamenhas** [comment]
I had the same problem, downgraded to 8.7.0 and it worked

**Comment by benhaynes** [comment]
Check that you're using HTTPS on webservers and local... that is a new requirement added in 8.7.2 due to a cookie policy change by Chrome et al. If it STILL is an issue, please open a new ticket with exact/specific information. Thanks! 👍 

Also, just as a reminder, this is a VERY generic error and could shown for several different root causes. More specific error handling/codes is something we're adding in v9.

**Comment by sensotix** [comment]
Hi @benhaynes thanks, enabling SSL fixed it! But since this is not mentioned in the release notes I guess a lot of people might stumble across this error. Any chance you will add this as a breaking change to the notes? Thx!

**Comment by wisskam** [comment]
Hi @benhaynes, same here - thank you for explanation! As soon as I set HTTPS everything worked fine.

**Comment by azizulhakim-f** [comment]
Hi @benhaynes, thanks. HTTPS fixed my issues too.

**Comment by GaneshKandu** [comment]
@benhaynes 
http is supported or not  or it will be supported or not?

**Comment by benhaynes** [comment]
I believe you need HTTPS now, but I defer to @rijkvanzanten if there's a way to still work on HTTP

**Comment by rijkvanzanten** [comment]
Browsers started requiring HTTPS for httpOnly cross-site cookies now, so it's out of our control unfortunately. HTTPS will be required moving forwards.

**Comment by YuriiLeso** [comment]
Yes, installation `ssl` certificate should solve this problem.

Here is brief how to get it :)
```
# enable https protocol by firewall
sudo firewall-cmd --permanent --zone=public --add-service=https

# install cerbot
sudo apt-get update
sudo apt-get install software-properties-common
sudo add-apt-repository universe
sudo add-apt-repository ppa:certbot/certbot
sudo apt-get update
sudo apt-get install certbot python3-certbot-apache

# get and install certificate
sudo certbot --apache

#follow instructions :)
```

**Comment by thakurPooja2494** [comment]
@rijkvanzanten  hi 
i have one issue on my working direct us suddenly from yesterday evening m getting 401 error.. what it the reason for that

**Comment by samuelecarpene** [comment]
In my case i solved using https. I added a local apache self signed certificate and all is working ok. If i use http instead of https the login is showing error as described in the issue.

**Comment by erkand-imeri** [comment]
Can someone explain in details, if u are using the docker image, what do u need to do? How to use the https?

Any insight on this, this should definitely be included in docker-compose.

**Comment by WoLfulus** [comment]
I've added an example on how to get https to some of the examples inside docker repository last week. You'll need an extra container in that case though, since we have no plans to support `https` out of the box inside directus container itself.

**Comment by mja9877** [comment]
I've this problem too. I just use **CTRL +F5** then its work :)

**Comment by InfamousStarFox** [comment]
I had a similar problem to @ithiru in 8.8.1 which was caused by `/src/helpers/all.php` however mine was caused by .htaccess authentication.

In 8.8.1 the code has changed to look like:
```
    function get_request_authorization_token(Request $request)
    {
        $response = [];

        if ($request->getParam('access_token')) {
            $response['type'] = DirectusUserSessionsTableGateway::TOKEN_JWT;
            $response['token'] = $request->getParam('access_token');

            return $response;
        }

        if ($request->hasHeader('Php-Auth-User')) {
            $response['type'] = DirectusUserSessionsTableGateway::TOKEN_JWT;
            $authUser = $request->getHeader('Php-Auth-User');
            $authPassword = $request->getHeader('Php-Auth-Pw');

            if (is_array($authUser)) {
                $authUser = array_shift($authUser);
            }

            if (is_array($authPassword)) {
                $authPassword = array_shift($authPassword);
            }

            if ($authUser && (empty($authPassword) || $authUser === $authPassword)) {
                $response['token'] = $authUser;
            }

            return $response;
        }

        if ($request->hasHeader('Authorization')) {
            $response['type'] = DirectusUserSessionsTableGateway::TOKEN_JWT;
            $authorizationHeader = $request->getHeader('Authorization');

            // If there's multiple Authorization header, pick first, ignore the rest
            if (is_array($authorizationHeader)) {
                $authorizationHeader = array_shift($authorizationHeader);
            }

            if (is_string($authorizationHeader) && preg_match("/Bearer\s+(.*)$/i", $authorizationHeader, $matches)) {
                $response['token'] = $matches[1];

                return $response;
            }

            // let it fallback to cookie checks if authorization is empty or invalid format
        }

        if ($request->hasHeader('Cookie')) {
            $response['type'] = DirectusUserSessionsTableGateway::TOKEN_COOKIE;
            $authorizationHeader = $request->getCookieParam(get_project_session_cookie_name($request));
            $response['token'] = $authorizationHeader;

            return $response;
        }

        return $response;
    }
```


Notice  that `if ($request->hasHeader('Php-Auth-User')) { ... }` was added before 'Authorization' and 'Cookie'


This means that if your server is setup using .htaccess to protect the directory, for example on a shared host, the server will check the .htaccess credentials before checking the credentials a user entered into the login field.

Moving the statement `if ($request->hasHeader('Php-Auth-User')) { ... }` to after the `if ($request->hasHeader('Cookie')) { ... }` statement will allow the server to correctly process the order of credentials, taking user entered credentials in the login field as a priority over .htaccess credentials.

**Comment by sharazy** [comment]
I encountered same problem on recent 8.8.1. Could not reach API.

Logs on server side is not even show anything related with this error. Somehow we did a hard reset on Chrome, and it worked.

INSPECT ELEMENT > Right click on Reload > Choose "Empty Cache & Hard Reload".

The Directus logged in and display its dashboard like usual.

**Comment by staminna** [comment]
> I've added an example on how to get https to some of the examples inside docker repository last week. You'll need an extra container in that case though, since we have no plans to support `https` out of the box inside directus container itself.

Can you let us know what extra container is needed for HTTPS support and how to connect them both? Thanks!

**Comment by azrikahar** [comment]
@staminna I believe it's meant as a reverse proxy, and there are Caddy, Traefik, Nginx, HAProxy to name a few. Highly recommend checking out #3307 for this topic, and also maybe Caddy to start with. Here's a quick and simple Caddyfile: https://github.com/directus/directus/discussions/3307#discussioncomment-1496777. 

If you have any further questions, please do follow up in that discussion (or a new discussion if that's preferred). Let's not comment further in old threads like this one as to not ping all the past participants here. Thanks!
