### ISSUE TITLE
Directus basic installation is not working properly

### ISSUE THREAD

**Issue by ozcanoguz** [directus/directus#2511]
# Bug Report
I've used installation document which seems quite easy, but stucked in the place that i need to navigate admin panel :

https://docs.directus.io/getting-started/installation.html#configure

1. When i've tried to access admin panel, i get this message : 
http://ec2-18-184-173-146.eu-central-1.compute.amazonaws.com/admin
https://pasteboard.co/ILzDaKM.jpg

2. When i try to create a config manually by usage of command: 
bin/directus install:config -u directus -p directus

```
PHP Warning:  file_get_contents(/var/www/directus/config/__api.json): failed to open stream: No such file or directory in /var/www/directus/src/core/Directus/Console/Modules/InstallModule.php on line 135
PHP Notice:  Undefined index: super_admin_token in /var/www/directus/src/core/Directus/Console/Modules/InstallModule.php on line 136
Creating config files required: db_name, db_user, super_admin_token
```
3. bin/directus help install shows that i need to set -a parameter
install:config -k my-project -h db_host -n db_name -u db_user -p db_pass -d directus_path -a super_admin_token

But i don't know what to set as a value here, but when i try to set simple values like 123, it blocks :
```
PHP Warning:  file_get_contents(/var/www/directus/config/__api.json): failed to open stream: No such file or directory in /var/www/directus/src/core/Directus/Console/Modules/InstallModule.php on line 135
Permission denied: Superadmin Only
```

## Steps to Reproduce

1. Try installation via https://docs.directus.io/getting-started/installation.html

## Expected Behavior
Normal installation.
## Actual Behavior
Can't achieve the installation.
## Technical Details

- Device: Desktop
- OS: Ubuntu 18.04.3 LTS
- Web Server: Apache/2.4.29 (Ubuntu)
- PHP Version: PHP 7.2.24-0ubuntu0.18.04.1 (cli) (built: Oct 28 2019 12:07:07) ( NTS )
- Database: mysql  Ver 14.14 Distrib 5.7.28, for Linux (x86_64) using  EditLine wrapper
- Directus Release Version:  v8.3.1
- Install Method: https://docs.directus.io/getting-started/installation.html

**Comment by benhaynes** [comment]
@rijkvanzanten — let's go over these install methods and docs tomorrow. Also, I wonder if the CLI takes the superadmin password into account.

**Comment by SharadKumar** [comment]
Hi Team, 
I've been trying to get my head around how to access the new (apparently... from 8.x release notes?) way of creating projects. I can't figure how to though. If there can be a hint in docs how to create projects on Dev and also Docker, it would be really helpful. So far I have been running /bin install.

There is also a mention of Admin config some places but can't find one in v8. Perhaps we should have a comment in the bottom to highlight which major release the docs map relevant to now.

Once I start getting my head around, I am hoping to be able to contribute to the docs.

**Comment by rijkvanzanten** [comment]
@ozcanoguz PHP isn't being run on your server. Please make sure you meet all the requirements of Directus

http://ec2-18-184-173-146.eu-central-1.compute.amazonaws.com/server/projects returns raw PHP

**Comment by ozcanoguz** [comment]
@rijkvanzanten , what should i do to make it "run" on server, installation guide is not pointing out that i need to run something besides setting root directory to "public" folder for apache configuration ?

PHP is already installed on server as i've written version here :

PHP Version: PHP 7.2.24-0ubuntu0.18.04.1 (cli) (built: Oct 28 2019 12:07:07) ( NTS )

**Comment by ozcanoguz** [comment]
After doing some configurations, i was able to enable php module with apache2, thanks for your support.
