### ISSUE TITLE
Problems with auto sign out

### ISSUE THREAD

**Issue by onlinelessons** [directus/directus#2513]
I get logged out from the app after some minutes, although my auto sign out value is set to 10080. I'm not even signed out correctly so that I get redirected to the login screen. I stay in the app, but nothing works anymore, which is quite bad if you work on a record for some minutes (get signed out in the meanwhile), hit save and it fails, because you got logged out...
If i then try to login again, i get the message "could not reach API", although the API is still working. After some minutes I am able to login again.
Could you also tell me which unit the "auto sign out" value has? Really minutes? Is it possible to get never signed out? Or if I get signed out after a longer time, that I get redirected to the login screen?

## Technical Details

- Web Server: Apache
- PHP Version: 7.2.22
- MySQL 5.7.27
- Directus Release Version: 8.3.0

**Comment by benhaynes** [comment]
@rijkvanzanten — App or API?

**Comment by rijkvanzanten** [comment]
Not sure. The API will re-set the cookie on every request from the app, and the app pings the API every 10 seconds. As long as you're actively using Directus, you shouldn't be signed out at all. 

How did you install Directus @onlinelessons?

**Comment by onlinelessons** [comment]
I downloaded the ZIP File, uploaded the extracted files and did a frech install. Afterwards I manually imported the database tables from my directus 190927A version by transforming the data to the new structure...

**Comment by onlinelessons** [comment]
any thoughts on this issue. It is impossible to work in the backend for a longer period. Is it possible to deactivate the auto sign out?

**Comment by rijkvanzanten** [comment]
This should've been addressed by the change to cookies for authentication.. I'm a little confused as to why it still happens when you are on 8.3.0, as that already uses the new cookie flow. Do you have a live environment somewhere I can take a peek at?
