### ISSUE TITLE
The list of items in a collection shows very few, having many

### ISSUE THREAD

**Issue by emilianovelasco** [directus/directus#2518]
# Bug Report
I use the API by making a call via CURL with PHP, I have also tried inserting directly to the DB, the result in both cases is the same. I use the Directus app with at least 8 projects DB configs (all new, I'm slowly filling them with data). If I do a search, the rest of the articles appear in the results.

## Steps to Reproduce

1. Go to 'Collection'
2. See error
![Captura de pantalla 2019-12-20 a las 15 40 48](https://user-images.githubusercontent.com/1174579/71262209-7c16c400-233f-11ea-8d94-166baa8cfa34.png)

## Expected Behavior
See all results or many more.

## Actual Behavior
It only shows one or two.

## Technical Details

- Device: Desktop
- OS: MacOS 10.14.5
- Web Server: LiteSpeed
- PHP Version: 7.2.25
- Database: 10.2.30-MariaDB
- Directus Release Version: v8.3.1
- Install Method: Download zip and upload to Linux server

**Comment by benhaynes** [comment]
@rijkvanzanten @bjgajjar @WoLfulus — this seems like the same issue where the full item count wasn't being returned. App or API?

**Comment by bjgajjar** [comment]
It's API @benhaynes. Maybe you are talking about https://github.com/directus/api/pull/1573

**Comment by emilianovelasco** [comment]
> @rijkvanzanten @bjgajjar @WoLfulus — this seems like the same issue where the full item count wasn't being returned. App or API?

I am a programmer who is studying in the first year. But I download Directus from https://github.com/directus/directus/releases and when a new version comes out, I update by downloading the ZIP and replacing. I have registered the 8 projects by creating 8 configuration files with their respective data.

**Comment by bjgajjar** [comment]
@emilianovelasco - Glad to know that you are using the Directus. But as I mentioned in the above comment this issue is already resolved. And you'll get it in our next release. :) 

Meanwhile, you can manually update that file in your code until our next version not getting released.

**Comment by bjgajjar** [comment]
Let's connect in our slack [channel](https://directus.chat) for further discussion. You can find me **`@Binal`** over there.

**Comment by emilianovelasco** [comment]
@bjgajjar Great for hearing that! Thank you very much, I will wait then. It was only to report it :)

**Comment by rijkvanzanten** [comment]
Did we confirm if that change actually fixed this issue @bjgajjar ? 

@emilianovelasco If you're up for the challenge, could you verify if the change that we made fixes it on your end?

You can do this by replacing line 2287 in`/src/core/Directus/Database/TableGateway/RelationalTableGateway.php` file directly 🙂 

Before:

```
unset($entries[$key]);
```

after:
```
$parentRow[$relationalColumnName] = null;
```

**Comment by emilianovelasco** [comment]
@rijkvanzanten Yes, it works perfectly 💯

**Comment by rijkvanzanten** [comment]
Perfect. Thanks for verifying that! I'll close this issue then as it will be released very soon
