### ISSUE TITLE
authentication error:  "You are not allowed to sign in from this location" (DigitalOcean install)

### ISSUE THREAD

**Issue by klickers** [directus/directus#2521]
# Bug Report
"You are not allowed to sign in from this location" error received when accessing Directus installation from public ipv4 address

## Steps to Reproduce

1. Install Directus on DigitalOcean
2. Navigate to http:/[ipv4]/admin
3. Set up (admin account, database, etc.)
4. Navigate to http:/[ipv4]/admin on another browser (e.g. different user signed in on Chrome, guest browser)
5.  Error occurs

## Expected Behavior
Login page with user/password fields appears.

## Actual Behavior
Login page without user/password fields and "Something is wrong with this project:  You are not allowed to sign in from this location" warning appears.

## Notes

I can access Directus normally on the original Chrome browser I used to create the DO droplet (using the public ipv4 address), but when I navigate to Guest or another user's Chrome browser, I get the error page (described under "Actual Behavior").

I also tried accessing from a Floating IP but received the same error.

## Technical Details

accessed with Chrome browser on Windows 10 desktop
- PHP Version: 7.2
- Database: MySQL 5.7.28
- Directus Release Version: v8.2.0
- Install Method: DigitalOcean one-click install

**Comment by klickers** [comment]
Not sure what the problem was, but deleting the droplet and creating a new one solved the issue.

**Comment by rijkvanzanten** [comment]
It sounds like the IP Whitelist feature kicked in
