### ISSUE TITLE
Upgrade Process via Git

### ISSUE THREAD

**Issue by dshastry** [directus/directus#2525]
I installed Directus 8.1.0 from the Git installation guide[ here](https://docs.directus.io/installation/git.html). I tried to upgrade from 8.1.0 to the latest (8.3.1) and I keep getting merge conflicts and the upgrade fails.

I thought that the Directus upgrade process was setup so I could just git pull to upgrade, or atleast that was my assumption. I haven't personally modified any of these files and so not sure if I can discard changes and pull, or if it will damage my data if I do so. How should I proceed?

Here's a dump of the terminal output when I run the git command:

`directus# git pull origin
Updating 171bcc34b..7c2e88764
error: Your local changes to the following files would be overwritten by merge:
	LICENSE.md
	migrations/install/20180220023217_create_roles_table.php
	migrations/install/20180220023243_create_settings_table.php
	migrations/install/20180220023248_create_users_table.php
	public/admin/css/app.002001cf.css
	public/admin/css/chunk-0b43c986.3432afb8.css
	public/admin/css/chunk-0cb328a2.26018590.css
	public/admin/css/chunk-1161a7fa.9dd84fb8.css
	public/admin/css/chunk-1232e627.b0d0c2bb.css
	public/admin/css/chunk-1331861a.54a659d9.css
	public/admin/css/chunk-166a9ff5.b667286f.css
	public/admin/css/chunk-187d43cb.e8000a72.css
	public/admin/css/chunk-1f542a74.6712dd8a.css
	public/admin/css/chunk-27dab218.b479a725.css
	public/admin/css/chunk-2938b383.eebf396c.css
	public/admin/css/chunk-2a584de4.5f988d55.css
	public/admin/css/chunk-35c389cd.81f2e7c4.css
	public/admin/css/chunk-3a0e3a85.6708e64d.css
	public/admin/css/chunk-43678214.184a7af8.css
	public/admin/css/chunk-4ecfa3b6.6f716505.css
	public/admin/css/chunk-4f5a601d.07db74d2.css
	public/admin/css/chunk-58391d8a.7174a40e.css
	public/admin/css/chunk-637c9dd7.1f667890.css
	public/admin/css/chunk-6a17d04e.8bce18c8.css
	public/admin/css/chunk-6db5c4ec.87859126.css
	public/admin/css/chunk-6df86ead.7577fa17.css
	public/admin/css/chunk-7541401a.437df4f3.css
	public/admin/css/chunk-7e0cb5f2.23fdc61d.css
	public/admin/css/chunk-7f5401c0.b6cf8375.css
	public/admin/css/chunk-9b75bb9a.60699f39.css
	public/admin/css/chunk-b67f3d98.34a87308.css
	public/admin/css/chunk-bf564c7a.3e80f0f7.css
	public/admin/css/chunk-dc2774f4.f00e7e73.css
	public/admin/css/chunk-f950521a.a8ff6aa0.css
	public/admin/css/chunk-fbc1c4b8.073c0909.css
	public/admin/css/chunk-fe18e448.de92bd8d.css
	public/admin/index.html
	public/admin/js/app.db449593.js
	public/admin/js/app.db449593.js.map
	public/admin/js/chunk-00b3f8b0.c9db5b8f.js
	public/admin/js/chunk-00b3f8b0.c9db5b8f.js.map
	public/admin/js/chunk-057e1e9a.5a0dca1e.js
	public/admin/js/chunk-057e1e9a.5a0dca1e.js.map
	public/admin/js/chunk-05e79fc2.4b8f2280.js
	public/admin/js/chunk-05e79fc2.4b8f2280.js.map
	public/admin/js/chunk-0b43c986.6cebbc7a.js
	public/admin/js/chunk-0b43c986.6cebbc7a.js.map
	public/admin/js/chunk-0cb328a2.c6bbb354.js
	public/admin/js/chunk-0cb328a2.c6bbb354.js.map
	public/admin/js/chunk-0d62948c.c7956224.js
	public/admin/js/chunk-0d62948c.c7956224.js.map
	public/admin/js/chunk-1161a7fa.b745b0ff.js
	public/admin/js/chunk-1161a7fa.b745b0ff.js.map
	public/admin/js/chunk-1232e627.63f1469f.js
	public/admin/js/chunk-1232e627.63f1469f.js.map
	public/admin/js/chunk-1331861a.e450b036.js
	public/admin/js/chunk-1331861a.e450b036.js.map
	public/admin/js/chunk-166a9ff5.39dc96af.js
	public/admin/js/chunk-166a9ff5.39dc96af.js.map
	public/admin/js/chunk-179106c6.01a7caa2.js
	public/admin/js/chunk-179106c6.01a7caa2.js.map
	public/admin/js/chunk-1854878c.f3d0d038.js
	public/admin/js/chunk-1854878c.f3d0d038.js.map
	public/admin/js/chunk-187d43cb.fe4b3374.js
	public/admin/js/chunk-187d43cb.fe4b3374.js.map
	public/admin/js/chunk-18b83708.5f6451f8.js
	public/admin/js/chunk-18b83708.5f6451f8.js.map
	public/admin/js/chunk-1f542a74.2323d6d8.js
	public/admin/js/chunk-1f542a74.2323d6d8.js.map
	public/admin/js/chunk-2122bd6c.3f7999af.js
	public/admin/js/chunk-2122bd6c.3f7999af.js.map
	public/admin/js/chunk-24ff38de.2d61b9f1.js
	public/admin/js/chunk-24ff38de.2d61b9f1.js.map
	public/admin/js/chunk-27773815.7928de9b.js
	public/admin/js/chunk-27773815.7928de9b.js.map
	public/admin/js/chunk-27dab218.7fa55614.js
	public/admin/js/chunk-27dab218.7fa55614.js.map
	public/admin/js/chunk-2920ad94.c1273824.js
	public/admin/js/chunk-2920ad94.c1273824.js.map
	public/admin/js/chunk-2938b383.cc0d7b08.js
	public/admin/js/chunk-2938b383.cc0d7b08.js.map
	public/admin/js/chunk-2a584de4.3b5de005.js
	public/admin/js/chunk-2a584de4.3b5de005.js.map
	public/admin/js/chunk-2d0b21f1.a6500848.js
	public/admin/js/chunk-2d0b21f1.a6500848.js.map
	public/admin/js/chunk-2d0c847f.28572442.js
	public/admin/js/chunk-2d0c847f.28572442.js.map
	public/admin/js/chunk-2d22497b.b803bf6f.js
	public/admin/js/chunk-2d
Aborting
`
Running Directus 8.1.0 on DigitalOcean. PHP 7.4 FPM/Nginx

Thanks for your assistance!

**Comment by benhaynes** [comment]
@rijkvanzanten — thoughts?

**Comment by rijkvanzanten** [comment]
Both `LICENSE.md` and `migrations/` should be ignored by Git. Updating https://github.com/directus/directus/blob/static-info/.gitignore will make sure this doesn't happen in future releases.

**Comment by rijkvanzanten** [comment]
This is resolved in a later version
