### ISSUE TITLE
Gatsby plugin under the directus umbrella

### ISSUE THREAD

**Issue by jooola** [directus/directus#2529]
I'm not sure if this is the right place to open this ticket, but it seems this repo in targetting  the entire directus ecosystem. Also sorry if I didn't kept the issue template.

My question is whether directus had enough man power to maintain the Gatsby directus plugin. A few old plugins are already here and there but it could be nice to move it under the directus umbrella.

I don't know if this project is aiming that way so I simply wanted to ask.
Thanks a lot for the nice work !

**Comment by rijkvanzanten** [comment]
I'm not sure about that.. We're a very small core team with our hands full on the main project. I have no problem putting an 'official' Gatsby plugin in the directus/ namespace, but its going to be tricky to maintain it. Added to that is we don't really use Gatsby ourselves for (client) projects which makes it a little harder to justify the time investment. 

Is this something you'd be interested in steering / maintaining @jooola ?

**Comment by jooola** [comment]
I'm not sure I'll have the time for maintaining it alone but I'll be glad to gather people around from the previous plugins and work together. The existing plugins doesn't seem really complicated, it's mostly about keeping compatibility with directus that is challenging.

I hope that if we add this plugin under the directus umbrella, people will automatically come here to contribute instead of writing there own plugin.

 So I'd be happy to create a initial plugin for directus 8 based on the existing work @ https://github.com/Jonesus/gatsby-source-directus7

**Comment by jooola** [comment]
Haha, I just came across another new plugin https://github.com/loganwishartcraig/gatsby-source-directus-cms

What do you people think of this ticket @Jonesus @iKonrad @loganwishartcraig

**Comment by jooola** [comment]
What I propose is that we create a new repo for this plugin, grant some users maintainers rights, and with the approval of @loganwishartcraig, squashing his initial work in this repo.

I'm sure if we do this @loganwishartcraig will want to have proper right over the repo or he won't even consider working here.

**Comment by rijkvanzanten** [comment]
I'm totally down for that. Like I mentioned, I don't have the time to fully develop or maintain it myself, but I'll happily share the keys to the repo to people who are willing to do so!

**Comment by iKonrad** [comment]
Sure, if you need any help from my side I'm down as well

**Comment by loganwishartcraig** [comment]
Hey, for what it's worth, I'd be keen to help out however possible. Just let me know!

**Comment by rijkvanzanten** [comment]
@jooola @iKonrad @loganwishartcraig Thanks 😄 I've [invited](https://github.com/directus/gatsby-source/invitations) you all to the `directus/gatsby-source` repo 😄 

What would be a good next step? It sounds like we'll be merging some of these into a single official package and deploying it under `@directus/gatsby-source` on NPM 🙂

**Comment by rijkvanzanten** [comment]
Also, we have a public [Slack workspace](https://directus.chat) in case y'all wanna chat on there 🙂

**Comment by jooola** [comment]
@rijkvanzanten Thanks for the repo and workspace. I'll continue the discussion there.

**Comment by jooola** [comment]
@Jonesus @iKonrad @loganwishartcraig Which project should we start with ?

I saw @loganwishartcraig's project and it seems pretty complete, but not necessarily mature. But I'm all for making a lot of testing.

**Comment by loganwishartcraig** [comment]
@jooola

Yeah - I don't have any tests for mine :(  But it's built in TypeScript, and I'd be able to write up some clearer documentation/diagrams for it if we wanted to use it as a starting point. 

Feel free to take a peek at the source, happy to answer any questions or talk about adding features.

I'm also in the ```#gatsby``` channel on Slack if you want to chat there.

**Comment by Jonesus** [comment]
Hey!

This looks great! I haven't really had time to keep maintaining my plugin and while I had been wanting to rewrite it in Typescript I never really got around to doing it, so you did the right choice picking @loganwishartcraig's version as the starting point.

I had started writing some tests for my version a while ago but probably never even pushed them, so if I manage to clear up my calendar I could help with getting those started in the new project :)

**Comment by sapkra** [comment]
@jooola What happend with the [directus/gatsby-source](https://github.com/directus/gatsby-source) repository.

**Comment by benhaynes** [comment]
Moved to the v8 archive... https://github.com/directus/v8-archive/tree/master/gatsby-source

**Comment by sapkra** [comment]
Will there be a new version for 9.x?

**Comment by benhaynes** [comment]
Yes, in time. Stability and Docs first!

**Comment by sapkra** [comment]
I created a discussion to have it on track: https://github.com/directus/directus/discussions/3643
