### ISSUE TITLE
Migration from 7 to 8: upgrading databases and hosting API and App separately

### ISSUE THREAD

**Issue by justrealmilk** [directus/directus#2530]
Hello 👋🏼

I've just managed to complete a somewhat turbulent manual upgrade and everything appears functional again. 

I was wondering if there's any sort of database upgrade script I need to run like we did in the past?

And can the API and App no longer live apart from one another?

**Comment by benhaynes** [comment]
When you access the API for the first time after upgrading, the database migrations will automatically run. 

@directus/team — can we add this to the Docs?

**Comment by rijkvanzanten** [comment]
What part? About the app and api being one thing?

**Comment by dobl1** [comment]
Starting directus 8 on 7's database was not working for me.
Do I need to manually edit something / run migration script ?

Regards

**Comment by obruehl** [comment]
I have a similar problem. After changing settings in config/_.php following instructions in https://github.com/directus/directus/releases/tag/v8.0.0 I tried to enter CMS and see the error page:

![image](https://user-images.githubusercontent.com/417516/78537174-5975c180-77ef-11ea-9fb4-0b34e39d9a3f.png)

Is it possible to run migration script manually that it is supposed to run automatically?

**Comment by benhaynes** [comment]
@obruehl — yes, migrations run automatically when you access the API after upgrading. Though the CLI does have a command for it too: https://docs.directus.io/guides/cli.html#upgrade-directus-schema

**Comment by dev7ch** [comment]
I had quite same migration problems (404 on `/me` after login) and was able to solve it by just deletion the table `directus_settings` and `directus_users` on a imported d7 DB on a D8 installation and manually imported these tables from a fresh working d8 installation ... somehome the CLI migration script did not take an effect
