### ISSUE TITLE
Directus 8 migration from 7 have some trouble with collections

### ISSUE THREAD

**Issue by dobl1** [directus/directus#2533]
Starting directus 8 (docker directus/directus:v8-apache) on 7's database was not working, I am able to login but none of my collections are available.

Do I need to manually edit something / run migration script ?

Regards

**Comment by dobl1** [comment]
Nothing is explained here regarding potential database update to do https://github.com/directus/directus/releases/tag/v8.0.0 btw.

**Comment by rijkvanzanten** [comment]
There's no database upgrade script you have to run manually. @WoLfulus any thoughts?

**Comment by dobl1** [comment]
To try to migrate just part of my data regarding previous version (7), how I am supposed to run the install script (I am on Kubernetes) ?

I have provided database connection by env vars.

Running :
```bash
./bin/directus install --email email@example.com  --password d1r3ctu5
```
is giving me `Error: Missing module name or command.`

Thanks

**Comment by dev7ch** [comment]
May just try `php bin/directus install:install -e admin@directus.local -p password -t "Directus Example" -k directus`

@dobl1 did you tried to prepend php?

https://docs.directus.io/guides/cli.html#example

**Comment by dev7ch** [comment]
on the v7 > v8 update in my case replaced the `directus_users` and `directus_settings` and replace with from a fresh d8 install and cleaned/lost the revision/activity log to avilod UI error messages

**Comment by rijkvanzanten** [comment]
Database migrations run automatically when needed. If there's a specific issue with upgrading between Docker containers, please add an issue over on github.com/directus/docker/ 🙂
