### ISSUE TITLE
Sortable collections

### ISSUE THREAD

**Issue by Sceko** [directus/directus#2550]
![Screenshot 2020-01-22 at 00 56 26](https://user-images.githubusercontent.com/2323952/72853574-1ad17000-3cb2-11ea-91cb-fc582d10db91.png)
Add sortable collections

And for bookmark to, and protect to can not add bookmark without name

**Comment by rijkvanzanten** [comment]
You can override the collections in here, including the order and grouping, from the role settings. The option is called _Collection Listing_

**Comment by benhaynes** [comment]
FYI: I added some docs for this:

https://docs.directus.io/guides/roles.html#collection-listing
