### ISSUE TITLE
Delete activity from activity page

### ISSUE THREAD

**Issue by Sceko** [directus/directus#2551]
Add posibiliti to delete activity whitout open every time if wont delete
and if click ... save to copy Method Not Allowed remove that

and if i wont delete Trouble processing request. Try again after refreshing the page.

**Comment by rijkvanzanten** [comment]
There's no way to delete rows in activity through the API right now. If you want, feel free to open a feature request for that on the [`directus/api`](https://github.com/directus/api) repo.

**Comment by benhaynes** [comment]
This is for security reasons, and we would really need to think through how this would work.

Activity is what gives accountability to actions in Directus. If we ever enabled deleting activity it would be an admin only feature with several safeguards. For now, this must be performed directly in the database.

**Comment by iryanrachman** [comment]
> This is for security reasons, and we would really need to think through how this would work.
> 
> Activity is what gives accountability to actions in Directus. If we ever enabled deleting activity it would be an admin only feature with several safeguards. For now, this must be performed directly in the database.

does doing it can make another problem or we leave it as it is ..?

**Comment by rijkvanzanten** [comment]
@iryanrachman you can delete directus_activity if you want, just keep in mind that you lose the accountability and revisions history
