### ISSUE TITLE
Delete collections from collections page

### ISSUE THREAD

**Issue by Sceko** [directus/directus#2552]
Add posibility to delete collections from collections page

**Comment by rijkvanzanten** [comment]
You can delete collections from the collections settings page already. Go to _Settings_ > _Collections & Fields_  choose a collection and click the delete button in the top right.

**Comment by benhaynes** [comment]
Deleting collections is a **really** big deal... so we won't allow bulk deleting from the Collection Listing page. So the only way to do it through the app is individually on each's detail page.
