### ISSUE TITLE
Login error introduced in v8.4.0

### ISSUE THREAD

**Issue by adamjgrant** [directus/directus#2557]
# Bug Report

## Steps to Reproduce

1. Upgrade a non v8 installation to v8 using `git pull origin master`

## Expected Behavior

1. Admin authentication page allows for login
2. Admin authentication page shows dropdown of projects with project names

## Actual Behavior

1. Page shows each of my projects as just "api" instead of their real names 
2. Error message saying "Something is wrong with this project"

## Other Context & Screenshots

Tailing the logs I see 

~~~
[2020-01-24 02:59:12] api[api].ERROR: Error: Undefined class constant 'TYPE_USER_CREATED' in /app/migrations/upgrades/20191123053252_update_directus_files_field.php:119
~~~

## Technical Details

I tried testing with different git tags: v8.3.1 the error does not happen, but it does on v8.4.0

**Comment by adamjgrant** [comment]
Looks like I hadn't run the manual v8 migration steps, which I've done now and 8.4.0 works.

![Screen Shot 2020-01-23 at 8 30 28 PM](https://user-images.githubusercontent.com/320494/73044629-40c85300-3e1f-11ea-8fb6-51a2b6ea991a.png)

Based on this, I thought just a git pull would be sufficient, but perhaps this happened because the above applies only to the api, not the suite?

**Comment by rijkvanzanten** [comment]
The above applies to updating versions of v8 to newer versions of v8. There are indeed breaking changes between v7 and v8 that need to be (manually) addressed (hence the major version number)

**Comment by adamjgrant** [comment]
Thanks for the followup, @rijkvanzanten

**Comment by woeterman94** [comment]
How did you fix this? Which scripts did you manually run?
