### ISSUE TITLE
support React-Admin framework

### ISSUE THREAD

**Issue by razakpm** [directus/directus#2560]
Support React Admin: A frontend Framework for building admin applications running in the browser

It will help to create browser specific React UI easily

React admin can't directly use the [ra-data-json-server](https://www.npmjs.com/package/ra-data-json-server) package, as `X-Total-Count` and `X-Custom-Header` must be included in list API. Then only we can achieve list in React admin: see `https://marmelab.com/admin-on-rest/RestClients.html#writing-your-own-rest-client`

**Comment by rijkvanzanten** [comment]
We have no interest in providing specialty support for React Admin at this point in time, as we have a dedicated admin app out of the box. Besides, it should be entirely possible to write a small middleware function that parses Directus' API output to fit the required input for React Admin. We can't update the API to natively fit with every possible package out there.
