### ISSUE TITLE
Handling files in directus 8 regarding directus 7

### ISSUE THREAD

**Issue by dobl1** [directus/directus#2563]
Hello,

This is a feature request, but for some people that are migrating from directus 7 as I am, this is more a considered as a bug.

The new filename_downloaded / filename_disk is causing some trouble regarding our implementation as we are use the Directus API to displays our images in the frontend.. but with the auto-generated names, absolutely not meaningful this not a great thing.

Will be great to have an option for having the filename-downloaded use in api to get a file, as it is better for migration, having ni impact on the current frontend.

Regards.

**Comment by dobl1** [comment]
Hello, 
![image](https://user-images.githubusercontent.com/9740002/73284833-6f667500-41f5-11ea-9646-1a93870b9e5a.png)
We have the ability to do that, but in fact I have found a bug regarding that, the underscores are replaced by dashes.

Why this behaviour ?

**Comment by benhaynes** [comment]
So is this actual feature request: `Don't change underscores to dashes when using the "Readable File Naming" setting`?

**Comment by dobl1** [comment]
Yes exactly :)

**Comment by dobl1** [comment]
Do you have a quick way to adress this ? (some line doing the underscores to dashes change I can edit in some php file ? )
Thanks

**Comment by dobl1** [comment]
I have found some code into

**Files.php** (line 580, function `processUpload`)

```php
    private function processUpload($filePath, $targetName)
    {
        // set true as $filePath it's outside adapter path
        // $filePath is on a temporary php directory
        $fileData = $this->getFileInfo($filePath, true);
        $mediaPath = $this->filesystem->getPath();

        $fileData['title'] = Formatting::fileNameToFileTitle($targetName); // HERE

        $targetName = $this->getFileName($targetName);
        $finalPath = rtrim($mediaPath, '/') . '/' . $targetName;
        $data = file_get_contents($filePath);

        $this->emitter->run('file.save', ['name' => $targetName, 'size' => strlen($data)]);
        $this->write($targetName, $data);
        $this->emitter->run('file.save:after', ['name' => $targetName, 'size' => strlen($data)]);

        $fileData['name'] = basename($finalPath);
        $fileData['date_uploaded'] = DateTimeUtils::nowInUTC()->toString();
        $fileData['storage'] = $this->config['adapter'];

        return $fileData;
    }
```


**Formatting.php** (line 10, function `fileNameToFileTitle`)

```php
    public static function fileNameToFileTitle($fileName)
    {
        $ext = pathinfo($fileName, PATHINFO_EXTENSION);
        $name = strtolower(basename($fileName, '.' . $ext));
        $name = str_replace(['_', '-'], [' ', ' '], $name); // HERE
        $name = ucwords($name);

        return $name;
    }
```

Not sure if this related to the database column `filename_disk` ?

**Comment by rijkvanzanten** [comment]
> Will be great to have an option for having the filename-downloaded use in api to get a file

This was already implemented in https://github.com/directus/api/pull/1626 and will be available in the next release 🙂

**Comment by dobl1** [comment]
Hello,

Can we repoen this ticket ? As in the latest version 8.5.3, we still have the issue of the `_` replaced by `-` in the filename on disk, that is used in the url to get the files.

Regards.

**Comment by dobl1** [comment]
So to be precis two things :
- The filename-disk still replace the `_` by `-`
- And the filename-download is not used when choosing to use the `File Name (Readable)` for the links. (still using the filename-disk)

**Comment by rijkvanzanten** [comment]
Can you open that as a new issue on the API repo @dobl1? https://github.com/directus/api/issues/new

**Comment by dobl1** [comment]
Here https://github.com/directus/api/issues/1730
