### ISSUE TITLE
Relationship error One-To-Many and Many-To-One

### ISSUE THREAD

**Issue by mehmetaydogan** [directus/directus#2576]
When I create a relationship One-to-Many  between 2 collections, I cannot select and save anything in the selection popup.
![image](https://user-images.githubusercontent.com/18116509/74020920-daa10b80-499a-11ea-9784-b34e08f47b5a.png)
When i click Done, nothing happen.

And when i create a relationship Many-To-One, I have always the loading animation with multiples errors
![image](https://user-images.githubusercontent.com/18116509/74020560-20110900-499a-11ea-87e5-c716f884c2a2.png)

I already tried to modify the values ​​of the relations directly in database, that does not work. I have the ID displayed on the field but always with the loading animation.
![image](https://user-images.githubusercontent.com/18116509/74020706-6bc3b280-499a-11ea-8f0b-197d456c2695.png)

**Comment by adamkobor** [comment]
> When I create a relationship One-to-Many between 2 collections, I cannot select and save anything in the selection popup.
> ![image](https://user-images.githubusercontent.com/18116509/74020920-daa10b80-499a-11ea-9784-b34e08f47b5a.png)
> When i click Done, nothing happen.
> 
> And when i create a relationship Many-To-One, I have always the loading animation with multiples errors
> ![image](https://user-images.githubusercontent.com/18116509/74020560-20110900-499a-11ea-87e5-c716f884c2a2.png)
> 
> I already tried to modify the values ​​of the relations directly in database, that does not work. I have the ID displayed on the field but always with the loading animation.
> ![image](https://user-images.githubusercontent.com/18116509/74020706-6bc3b280-499a-11ea-8f0b-197d456c2695.png)

Which version are you using? 8.5.4 should be fine (we've faced the same issue on 8.5.1 - 8.5.3)

**Comment by mehmetaydogan** [comment]
> > When I create a relationship One-to-Many between 2 collections, I cannot select and save anything in the selection popup.
> > ![image](https://user-images.githubusercontent.com/18116509/74020920-daa10b80-499a-11ea-9784-b34e08f47b5a.png)
> > When i click Done, nothing happen.
> > And when i create a relationship Many-To-One, I have always the loading animation with multiples errors
> > ![image](https://user-images.githubusercontent.com/18116509/74020560-20110900-499a-11ea-87e5-c716f884c2a2.png)
> > I already tried to modify the values ​​of the relations directly in database, that does not work. I have the ID displayed on the field but always with the loading animation.
> > ![image](https://user-images.githubusercontent.com/18116509/74020706-6bc3b280-499a-11ea-8f0b-197d456c2695.png)
> 
> Which version are you using? 8.5.4 should be fine (we've faced the same issue on 8.5.1 - 8.5.3)

I'm using 8.5.3. I have to upgrade to 8.5.4 ?

**Comment by adamkobor** [comment]
Sure, it seems to be solved in 8.5.4
