### ISSUE TITLE
Option Files & Thumbnails Broken

### ISSUE THREAD

**Issue by MathiRa** [directus/directus#2604]
# Bug Report

## Steps to Reproduce

1. Go to 'Settings->Global Settings'
2. Click on 'Default Limit' and change to 15.
3. Go to some 'Collections' that contains field type **file**
3.1 Try upload an image. You can upload but it will not show the preview.

##  Screenshots
**If Settings is by default you could see the following settings**

![image](https://user-images.githubusercontent.com/13860804/75887395-7f7eff00-5e08-11ea-9441-887cb677562f.png)

**And you have the following option: Files & Thumbnails**

![image](https://user-images.githubusercontent.com/13860804/75887272-4fcff700-5e08-11ea-9174-f7b91fad2daf.png)

**And you can upload an image and see you preview.**

![image](https://user-images.githubusercontent.com/13860804/75887938-54e17600-5e09-11ea-9cd4-d1b606b1c59f.png)

**BUT If you change the option setting Default Limit to 15**

![image](https://user-images.githubusercontent.com/13860804/75887434-8ad22a80-5e08-11ea-9900-f1a2007e5295.png)

**You can't see the option: Files & Thumbnails**
![image](https://user-images.githubusercontent.com/13860804/75887455-94f42900-5e08-11ea-889a-1508076947cf.png)

**And you can't see the preview.**

![image](https://user-images.githubusercontent.com/13860804/75887989-69be0980-5e09-11ea-8d3b-d0633e9f3007.png)

## Technical Details

- Device: Desktop
- OS: Windows 10
- Web Server:  Apache
- PHP Version: 7.2.0
- Database: MySQL
- Directus Release Version: v8.5.6
- Install Method: cloned `master` branch

**Comment by MathiRa** [comment]
Hi @benhaynes , 

Could you give me with this issue?.

Regards.

**Comment by benhaynes** [comment]
I don't know what that means? This issue will go through our normal triage process...

**Comment by MathiRa** [comment]
> I don't know what that means. This issue will go through our normal triage process...

@benhaynes I'm sorry the question was wrong. What I wanted to ask you is if you could help me with this issue

**Comment by benhaynes** [comment]
Ahh, gotcha. No need to request specific people — every morning we go through and triage/prioritize all new tickets/comments.

**Comment by rijkvanzanten** [comment]
@MathiRa did you change anything else? Is this on a fresh installation?

**Comment by MathiRa** [comment]
> @MathiRa did you change anything else? Is this on a fresh installation?

@rijkvanzanten This issue exist in a fresh installation too.

**Comment by MathiRa** [comment]
Hi @rijkvanzanten how are you? I believe that I found the fix to this issue but I don't know how to continue the publishing process because it should be done in project Directus-SDK.
The function **getSettings();** is called in a compiled file js in the Directus project. I understand that to get the application settings Directus call to the function in the following way **await api.getSettings();** and I understand that this function belongs to the SDK-js project.

I think that if we add the parameter **?limit=-1** to the **/settings** endpoint it will work fine because if we use the **default limit** value (set in the database, for example, set 15 like default) to get the settings from the API we would have fewer options. Because if **default limit** value is less than the total options in directus_settings table, we can't get all settings and it won't work fine like you can see in this example that I exposed in this issue.

I did a small test hardcode PHP in the Directus project and it works fine. But I continued researching to try to apply the best possible solution. In the file "SDK.ts" from the project Directus-SDK, you can see the following code 
 
```javascript

  // #region settings

  /**
   * Get Directus' global settings
   * @param {QueryParamsType?} params
   */
  public getSettings(params: QueryParamsType = {}) {
    return this.api.get<ISettingsResponse>("/settings", params);
  }
```

As mentioned before, I think that if we add **?limit=-1** in the function **getSettings** it will work fine.

Regards.

**Comment by rijkvanzanten** [comment]
Ah interesting. That makes total sense! Would you mind opening a new issue on the SDK repo about that and closing this one? Thanks!

This same issue probably applies to a lot of other things as well, for example fetching fields or users

**Comment by MathiRa** [comment]
@rijkvanzanten thanks for your answered. I created a new issue in the following link: [154](https://github.com/directus/sdk-js/issues/154)
