### ISSUE TITLE
Server error page after logging it

### ISSUE THREAD

**Issue by criscmaia** [directus/directus#2626]
# Bug Report

## Steps to Reproduce
1. I don't know what caused it.
From what I was able to track, it is something database related.
Any way to narrow it down to a specific table/row?

## Actual Behavior
1. Login works fine.
2. Then I get the following error page:
![image](https://user-images.githubusercontent.com/9072422/77210767-b25c0f00-6af9-11ea-8e0b-e61a614359e8.png)

## Other Context & Screenshots

No related error logs are generated.

I have a completely pure-JS separate page which gets the data from the same Directus installation via API and displays it  - they all work fine.
This page checks if a user is logged in (using .../api/users/me) and if not redirects to the login page - works fine as well.

 .../server/ping is giving me:
`{"error":{"code":3,"message":"Unauthorized request","class":"Directus\\Exception\\UnauthorizedException","file":"\/var\/www\/scate\/src\/helpers\/app.php","line":287}}`

## Technical Details
![image](https://user-images.githubusercontent.com/9072422/77211003-6198e600-6afa-11ea-9831-0b95b5e71486.png)

**Comment by rijkvanzanten** [comment]
Could you check if your user has an avatar associated with it that doesn't exist anymore in directus_files?

**Comment by criscmaia** [comment]
I've tried 4 different logins
Only 1 have a avatar (.directus_users.avatar) value. Others are null

**Comment by rijkvanzanten** [comment]
Can you try replicating the request made, removing the query parameters one by one until it works, and let me know which one seems to cause the problem?

**Comment by criscmaia** [comment]
the queries work fine, for example:
http://scate.mdx.ac.uk/api/items/module?sort=id&fields=*,created_by.first_name,created_by.last_name,created_by.email
or
http://scate.mdx.ac.uk/api/items/learning_object?filter[unit_id][eq]=44&sort=id&fields=*,created_by.first_name,created_by.last_name,created_by.email

the only issue is accessing the Directus system bit.
The one that should load after I log-in.

**Comment by criscmaia** [comment]
not sure how relevant it is, but the /ping page returns the following error message:

`{"error":{"code":3,"message":"Unauthorized request","class":"Directus\\Exception\\UnauthorizedException","file":"\/var\/www\/scate\/src\/helpers\/app.php","line":287}}`

**Comment by rijkvanzanten** [comment]
Ah, could it be that either: 
• the authorization header doesn't go through at the server level (apache setting), or 
• cookies are blocked / automatically removed
• the auto_sign_out time in directus_settings is 0?

**Comment by criscmaia** [comment]
Maybe the auto_sign_out, I'll check it.

For the queries, I'm checking if the user is signed in using:
```
$.ajax({
    url: "http://scate.mdx.ac.uk/api/users/me",
    statusCode: {
        500: function() {
            console.log("Likely that user is not logged in...");
            window.location.replace("http://scate.mdx.ac.uk/admin/#/login");
        }
    }
})
```
and it works! 
but still the /ping doesn't...

**Comment by rijkvanzanten** [comment]
Does /ping return anything?

**Comment by criscmaia** [comment]
![image](https://user-images.githubusercontent.com/9072422/77213951-a45fbb80-6b04-11ea-845b-20a20634ce78.png)

ping with error but /api/users/me returns everything

**Comment by rijkvanzanten** [comment]
This is `/ping` though, you mentioned `/server/ping` returns the same?

**Comment by criscmaia** [comment]
I'm not very clever.
/server/ping returns pong.
Sorry.

so, back to the main and only issue:
this:
![image](https://user-images.githubusercontent.com/9072422/77214351-a4f95180-6b06-11ea-91ff-f7140f31c6f4.png)

followed by this:
![image](https://user-images.githubusercontent.com/9072422/77214356-acb8f600-6b06-11ea-877d-38c24ade06b7.png)

**Comment by rijkvanzanten** [comment]
That /users/me request in the devtools requests with a couple query parameters (notice the &field[4]=etc bit?) Could you try it with those too? One of those must be the culprit..

**Comment by criscmaia** [comment]
Sorry, I don't follow you on this one.
My /users/me has no parameters:
![image](https://user-images.githubusercontent.com/9072422/77214996-be4fcd00-6b09-11ea-9e87-1e4a7c49e840.png)

I'm just checking if it returns something to see if user is logged in

**Comment by rijkvanzanten** [comment]
Yeah, that's what makes me think that one of the query parameters makes it fail!

The app opens that same endpoint but gets a 500, the only difference being that the app adds a couple query params that you don't 🙂

**Comment by criscmaia** [comment]
![image](https://user-images.githubusercontent.com/9072422/77224965-8e80e380-6b62-11ea-9627-acb12e9b37ec.png)

tried one by one. all of them.
they all returned the correct value without any error message :(

**Comment by criscmaia** [comment]
I think I have a good lead on what it may be.
The http://scate.mdx.ac.uk/api/collections returns error 500.
And it's the only one with error message on the Network tab.

What could have broken it?

![image](https://user-images.githubusercontent.com/9072422/77225254-6777e100-6b65-11ea-8685-76de45b05594.png)

**Comment by criscmaia** [comment]
FIXED! 
There was an unknown ROW in the directus_collections table.
I've removed it, and it's all back to normal now!
No clue how this row got there.

Thanks for all the help!

**Comment by rijkvanzanten** [comment]
Oh my, glad to have figured that out!
