### ISSUE TITLE
[Upload File] Request Entity Too Large error when uploading a 43 MB file

### ISSUE THREAD

**Issue by Castafiore** [directus/directus#2627]
I changed changed `post_max_size` to 1024M and `upload_max_filesize` to 1024M of php.ini file and I can see on directus page the max file size to upload is 1G now. But when I try to upload a file even with a small size 1.1 MB, I go error 413 with msg: Request Entity Too Large. Could you help me on this?

**Comment by pacocastillo** [comment]
I have same error. Could you tell me how you solved it?

**Comment by gramakri** [comment]
See https://github.com/directus/directus/issues/11049
