### ISSUE TITLE
"translation-independant" mode for Fields

### ISSUE THREAD

**Issue by stouch** [directus/directus#2629]
# Feature Request

## What problem does this feature solve?
Sometimes it's useful to have an item field that does not change depending on app language (for example: the png cover for a news item , on which there is no wordings... you don't want to set it in all the languages of your app).

## How do you think this should be implemented?
In  the Field  API, a new key _translation_independant_ :
```
{
  "field": "test",
  "type": "string",
  [...]
  "translation_independant": true
}
```

In the Backoffice interface, the field is set for all the translations, and so does not change when you change the item language.

## Would you be willing to work on this?
Not for now...

**Comment by rijkvanzanten** [comment]
All the fields that you add to the table that aren't part of the related translations collection won't be translated per language, so this is already possible 🙂
