### ISSUE TITLE
[File Upload]  Error: timeout of 600000ms exceeded when uploading a large file

### ISSUE THREAD

**Issue by Castafiore** [directus/directus#2631]
I have changed relative settings of apache2 so that I can upload a large file (max is 2 GB), but when I try to upload a 1.82 GB file, it gave me `error.js:9 Error: timeout of 600000ms exceeded` after 10 minutes execution. Then I've found there is an axios setting `timeout: 10 * 60 * 1000` in the [sdk-js API file](https://github.com/directus/sdk-js/blob/master/src/API.ts), so could you provide a feature to make the timeout modifiable or set it to a larger value? I have cloned the app repo to my machine then changed the timeout in nodes_modules/@directus/skd-js/src/API.ts to 30 * 60 * 1000, then built it then pushed the dist  folder to my directus repo's public as admin folder (I know it is not good) then try again, still get 600000 ms exceeded error.

**Comment by benhaynes** [comment]
Not sure if this is a Directus or server issue... @directus/team ?

**Comment by Castafiore** [comment]
@benhaynes I think it  is caused by the  line 99 `timeout: 10 * 60 * 1000, // 10 min` of [https://github.com/directus/sdk-js/blob/master/src/API.ts](https://github.com/directus/sdk-js/blob/master/src/API.ts) coz I can see error log from browser console that the directus/app uses it. So it will be helpful if you could increment the timeout value or make it configurable on directus app web page. Thanks.

**Comment by rijkvanzanten** [comment]
Closed in favor of https://github.com/directus/sdk-js/issues/165
