### ISSUE TITLE
Customise navigation sidebar

### ISSUE THREAD

**Issue by ahmadsholehin** [directus/directus#2633]
# Feature Request

Is there a way for the left collections sidebar to be customised?

## What problem does this feature solve?

Currently the leftmost shows modules (and custom modules) and then the one next to it shows collections and bookmarks. We would want to create links to custom modules inside the collections panel. From a UX perspective, users would think that the leftmost panel is the parent, and the inner panel is for children links of the module. From the current implementation, it is quite confusing as to why collections would appear statically despite clicking on custom modules that does not have anything to do with managing collections. We're actually trying to not show collections all together, for users that are just consuming custom modules.

## How do you think this should be implemented?

Make the collections panel be somewhat configurable?

## Would you be willing to work on this?

I can get my team to hack a solution just for the use case (eg hiding collections panel using CSS), but I don't think this will work well for the overall direction of Directus.

**Comment by benhaynes** [comment]
We have that...

https://docs.directus.io/guides/roles.html#collection-listing

**Comment by benhaynes** [comment]
The other update you mentioned (nav updating based on module) is in-work now for v9 and will be out in Alpha in the next week or so.
