### ISSUE TITLE
Can't login without user's role having READ access to Settings (Directus System Collection)

### ISSUE THREAD

**Issue by amirakbulut** [directus/directus#2645]
# Bug Report

## Steps to Reproduce

1. Go to '/admin/#/:project/settings/roles'
2. Create a new role:
- Toggle Directus System Collections to see it's permission options.
- By default, the Settings collection has READ ALL permission enabled, change it to 'None'.

Now the role shouldn't have any permission regarding the Settings collection.

3. Now create a new user and assign him the new role.
4. Log in with that user, and you'll receive the error.

## Expected Behavior
Log in succesfully, the current user should have no permission to visit '/admin/#/:project/settings'.

## Actual Behavior
When logging in, it will show an error saying:

Server Error
Something is wrong with this instance’s server or database.

## Other Context (console errors)
![Console errors](https://i.imgur.com/O2VVF1R.png)

## Technical Details

- Device: Desktop
- OS: Windows 10
- Web Server: Apache 2.4.37
- PHP Version:  7.2.10
- Database: MySQL 8.0.12]
- Directus Release Version: v8.6.2
- Install Method: cloned `master` branch

**Comment by amirakbulut** [comment]
Anyone?

**Comment by rijkvanzanten** [comment]
This is expected behavior. If the user isn't able to read the settings, the app can't apply them.

**Comment by amirakbulut** [comment]
Well, how do I prevent my users for visiting anything that belongs to the Directus System Collection?

**Comment by rijkvanzanten** [comment]
I'm not sure what you mean or try to achieve. If the user isn't able to read the Directus system collections like collections, fields, or settings, how would they be able to use the app?

**Comment by amirakbulut** [comment]
> I'm not sure what you mean or try to achieve. If the user isn't able to read the Directus system collections like collections, fields, or settings, how would they be able to use the app?

I'm trying to use Directus for my front end users as well, and I don't want them to see anything related to the settings stuff..

**Comment by rijkvanzanten** [comment]
If they are not an admin, they don't have the settings module activated. Only admin users have the gear icon and access to settings.

**Comment by rijkvanzanten** [comment]
If they are not an admin, they don't have the settings module activated. Only admin users have the gear icon and access to settings.

**Comment by amirakbulut** [comment]
> If they are not an admin, they don't have the settings module activated. Only admin users have the gear icon and access to settings.

Yes, but they're still able to access '/admin/#/:project/settings' though the URL bar, and see the all the settings etc. If they know I'm using Directus ofcourse.
