### ISSUE TITLE
Can't get the custom demo module to show up

### ISSUE THREAD

**Issue by sabatale** [directus/directus#2646]
I have deployed Directus (git yesterday) on Ubuntu 18.04 with Apach & Mysql, following the guide, and I'm now trying to setup a custom module as indicated here: [https://docs.directus.io/extensions/modules.html]( https://docs.directus.io/extensions/modules.html). I have not modified the example files' content.

I've created both meta.json and module.vue in the /var/www/directus/public/extensions/custom/modules directory, then used parcel the same way as described in the guide. This gets me the following ls:

```
**/var/www/directus/public/extensions/custom/modules$ ls**
meta.json  module.css  module.js  module.vue  node_modules  package.json
```

However the module is not shown in the left sidebar after restarting Apache2. Am I missing something? I looked into Settings / Interface to check whether I had to enable something (although my guess is that a module would not be listed as an interface), but couldn't find anythin.

Thanks!

![image](https://user-images.githubusercontent.com/50220345/77831393-5ac73000-7105-11ea-8397-0533ed7fb5ba.png)

**Comment by sabatale** [comment]
Well, it looks like all I had to do was creating a folder with the name of the module first (e.g. "demo-module"). It was not clear to me from the guide but it may just be me who is confused about it.

```
**/var/www/directus/public/extensions/custom/modules/demo-module$ ls**
meta.json  module.css  module.js  module.vue  node_modules  package.json
```

![image](https://user-images.githubusercontent.com/50220345/77833160-94059d00-7111-11ea-898f-80de6d6d93bc.png)

**Comment by mdocter** [comment]
@benhaynes It's still not clear in the docs that there should be a module/extension folder. Currently it states that you have to copy the contents of the dist folder (which is a index.js file) to the `extensions\modules` folder. That will make people wonder how they would add multiple extensions.

**Comment by benhaynes** [comment]
@mdocter — hmm, I can see why that might cause confusion. Do you have any recommendations for how this could be clarified? Perhaps a small PR of tweaks to the Docs we could review? ❤️
