### ISSUE TITLE
Database permissions

### ISSUE THREAD

**Issue by Varulv1997** [directus/directus#2656]
Hello there, I finally figured out how to connect the (Cloud SQL) database to Directus (latest version) running on App Engine, all server requirements are met.
When I run the setup, in the database configuration it connects now successfully unlike many many failed tries, however running the installation fires up the following alert:
`Permission denied: Superadmin Only`
GCP doesn't allow users to have the SUPER privileges on Cloud SQL
Is there any way to make directus only uses the privileges I already have ?
And is there anyway I can create the tables myself in the database and bypass that ?
If yes please provide me the tables I should create and how I can configurate the config files to run with the database (if there are any new files created, possibly an API folder as  I read somewhere or anything else, I will appreciate it if I can get a detailed method).

Thanks !

**Comment by rijkvanzanten** [comment]
Hey @Varulv1997! That error means that you didn't pass the super admin token when installing subsequent projects. See https://docs.directus.io/api/projects.html#create-a-project

**Comment by Varulv1997** [comment]
@rijkvanzanten The problem is, I still never ran the installation, just in the middle of it whilst connecting the database in the setup it fires up that error, it's because Google's Cloud SQL service doesn't allow its users to have the super privileges, what I'm asking is, is there any way so that Directus can use lower privileges beyond Cloud SQL's limits.
Thanks

**Comment by rijkvanzanten** [comment]
> it's because Google's Cloud SQL service doesn't allow its users to have the super privileges

No, that's what I'm saying. The error `Permission denied: Superadmin Only` comes from Directus:

https://github.com/directus/api/blob/68135be20c7cd5df80926c80c20fca722afc9969/src/core/Directus/Config/SuperAdminToken.php#L86

It has nothing to do with the required permissions on Cloud SQL

**Comment by Varulv1997** [comment]
Hmm you're right because somehow I fixed it, I don't really remember what I did, I played with the instance database's flags and I got it to work.

Thanks anyways.

**Comment by Varulv1997** [comment]
Hmm you're right because somehow I fixed it, I don't really remember what I did, I played with the instance database's flags and I got it to work.

Thanks anyways.
