### ISSUE TITLE
trouble with updating: problem loading extensions

### ISSUE THREAD

**Issue by adrian-filipow** [directus/directus#2661]
# Bug Report

I updated from version 8.4.0 to 8.6.2 with git pull. I tested this on a fresh installation and it worked.

Then I did the same in my production environment.

It still shows version 8.4.0 and I get following error when I open global settings.

![Slice 1(15)](https://user-images.githubusercontent.com/33333299/79057967-8dc20580-7c67-11ea-8ee5-d125ed23c1f9.png)

## Technical Details

- Web Server: [eg: Apache 2.4]
- PHP Version: [eg: 7.3]
- Database: [MySQL 8.0.15]
- Directus Release Version: [v8.6.2]
- Install Method: [cloned `master` branch]

**Comment by benhaynes** [comment]
@directus/team — App or API?

**Comment by rijkvanzanten** [comment]
> It still shows version 8.4.0

Are you sure you updated it then? It sounds like it didn't actually update in that case.
