### ISSUE TITLE
Trouble in connecting to Google Cloud MySQL Instance 

### ISSUE THREAD

**Issue by ashx404** [directus/directus#2671]
I am trying to connect my directus instance which is running in docker on my local with Google Cloud MySQL. I tried running directus image from dockerhub and passed an .env file for my Cloud DB credentials. Can someone explain how to get it done.

**Comment by benhaynes** [comment]
Could you provide more technical details on your setup? Directus version, PHP, MySQL versions, etc.

**Comment by ashx404** [comment]
Directus Image v8.6.2
MySQL 5.7
I followed https://docs.directus.io/installation/docker.html to setup it on local, it was really smooth.

**Comment by benhaynes** [comment]
Ahh, of course Docker has all these included  🤦 

It must be something specific to the Google Cloud DB config then. We don't test on that infra, so I don't know if we'll have an answer, but I believe there was another ticket regarding this in one of our repos. I'd check there, or chat with folks in our Slack: https://directus.chat

**Comment by ashx404** [comment]
Alright. Thanks I will discuss there.
