### ISSUE TITLE
Collapse divider

### ISSUE THREAD

**Issue by lluishi93** [directus/directus#2682]
# Feature Request

## What problem does this feature solve?

Sometimes, you have a collection that has a lot of fields for whatever reason. When the user has to scroll through the whole form, it can be very user unfriendly. Allowing the user to collapse sections would be a nice UX improvement IMO.

## How do you think this should be implemented?
Enabling a checkbox within the divider interface to turn it into a collapse can be a good way to go. Or even a new interface called collapse, if that makes things easier. It really doesn't matter as long as the option is there.
Maybe a standard collapse like the Boostrap one would be enough.

## Would you be willing to work on this?

I do not have time to work on this ATM.

**Comment by benhaynes** [comment]
While we could use the divider to delimit groups, we're looking into proper grouping (and therefore collapsing) using "field groups" in v9 / v10. 

Ref: https://github.com/directus/app/issues/773
