### ISSUE TITLE
Verify authenticated users in socket server

### ISSUE THREAD

**Issue by analyserdmz** [directus/directus#2753]
Hello, i am trying to let my websocket server know which user is connecting to it, after the user has successfully logged in with directus API call. Is there any API call that my websocket server can request for to get back user's data whatsoever? A little help guys.. thanks a lot!

**Comment by rijkvanzanten** [comment]
You can use `/users/me` to fetch information about the current user 👍

**Comment by analyserdmz** [comment]
You probably didn't get my question. I have a web app and a separate socket server. User logs in to web app and the socket server must know which user is trying to connect on it. @rijkvanzanten

**Comment by rijkvanzanten** [comment]
Yeah, your webapp has the user's auth token and ID at that point, so you can send that along in the socket message and use that server side to retrieve what user it is who sends the message. You can use either `/users/me` with a token or `/users/:id` with the ID serverside

**Comment by analyserdmz** [comment]
> 
> 
> Yeah, your webapp has the user's auth token and ID at that point, so you can send that along in the socket message and use that server side to retrieve what user it is who sends the message. You can use either `/users/me` with a token or `/users/:id` with the ID serverside

Thank you very much! I appreciate your help!!
