### ISSUE TITLE
Don't pipe output of db into to /dev/null, it hides DB init errors

### ISSUE THREAD

**Issue by MiniDigger** [directus/directus#2903]
Was trying to figure out why directus wouldn't setup my tables after switching to postgres.

since the output of the db init is hidden from the user, I wasn't seeing this error message
`error: create table "directus_collections" ("collection" varchar(64), "icon" varchar(30), "note" text, "display_template" varchar(255), "hidden" boolean not null default '0', "singleton" boolean not null default '0', "translations" json, "archive_field" varchar(64), "archive_app_filter" boolean not null default '1', "archive_value" varchar(255), "unarchive_value" varchar(255), "sort_field" varchar(64)) - no schema has been selected to create in`
my error was that I typoed DB_SEARCH_PATH to DB_SEARCHPATH, making postgres complaining that I don't have a schema selected.
https://github.com/directus/next/blob/6b345193c120ec058e9c154afd4fc37a483e55f0/.github/actions/build-images/rootfs/directus/images/main/rootfs/usr/bin/entrypoint#L83

I am not sure how else you would detect if DB init was successful or if it wasnt needed, but there gotta be a better way.

**Comment by rijkvanzanten** [comment]
This was fixed in fac2e280dd65ecbe25761b734c0141bf4a4b56c3
