### ISSUE TITLE
SQLite Initialization/Migration Fails

### ISSUE THREAD

**Issue by nickrum** [directus/directus#2904]
Trying to upgrade a SQLite database fails with the error message "Method implemented in the dialect driver". It seems like `dropForeign()` is not implemented for the SQLite driver.
As the migrations are run when initializing a database this error shows up, even though the initialization works.

**Comment by mstapp** [comment]
Is there a workaround for this? I'd like to try out directus using sqlite and can't get past the npx create-directus-project step. Thanks.

**Comment by kassemz** [comment]
Installing with SQLite doesn't work on Ubuntu 18 and Windows 10:

```
root@box:~# npx create-directus-project test
npx: installed 54 in 4.965s
? Choose your database client SQLite (Beta)
? Database File Path: /root/test/data.db

Something went wrong while seeding the database:

[Error] Sqlite does not support alter column.

Please try again

? Database File Path: /root/test/data.db

Something went wrong while seeding the database:

[Error] Database is already installed

Please try again

? Database File Path: /root/test/data.db

Something went wrong while seeding the database:

[Error] Database is already installed

Please try again

? Database File Path: /root/test/data.db

Something went wrong while seeding the database:

[Error] Database is already installed

Please try again

? Database File Path: /root/test/data.db

Something went wrong while seeding the database:

[Error] Database is already installed

Please try again

Couldn't seed the database. Exiting.
(node:17991) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: npx directus init
    at makeError (/root/.npm/_npx/17991/lib/node_modules/create-directus-project/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/root/.npm/_npx/17991/lib/node_modules/create-directus-project/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.create (/root/.npm/_npx/17991/lib/node_modules/create-directus-project/lib/index.js:73:2)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17991) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17991) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by azanov** [comment]
Any news on this issue? The PR https://github.com/knex/knex/pull/4092 in Knex was merged long ago.

**Comment by benhaynes** [comment]
@nickrum has mentioned he would like to take on these vendor issues, so I defer to him on his thoughts. However, this is our official standpoint on providing updates/timelines:

[**Unfortunately, we can not provide estimates on features or fixes**](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍 . Or contribute a pull-request... after all, this is OSS!

**Comment by nickrum** [comment]
Unfortunately, the linked PR only fixed part of the problem causing this issue. There is still one operation missing from Knex which is needed to get this to work, namely the same thing causing issue #2948.

As it is not exactly an easy fix, I also can not provide any estimates but, due to popular demand, I will tackle this issue first.

**Comment by fjdumont** [comment]
> As it is not exactly an easy fix, I also can not provide any estimates but, due to popular demand, I will tackle this issue first.

Is there any way I can help solve this issue? Is there an ongoing issue in the Knex repo?

**Comment by benhaynes** [comment]
Thank you for offering your help, @fjdumont!! @nickrum is leading the support for SQLite, so I'll let him respond in reference to how you can help! Finding issues and reporting them on GitHub is always a big help... even adding insight into the existing tickets labeled for #sqlite.

**Comment by nickrum** [comment]
@fjdumont Fixing this issue is a rather linear process, so there is nothing really I can outsource. Once the implementation is ready though, it would be nice if anyone willing to help would test SQLite support with various configurations and report any issues.
I haven't found an open issue in the Knex repo, but I will open a PR within the next few days.
