### ISSUE TITLE
Add "Dynamic Link" interface button

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#2911]
Options:
* URL: eg `https://example.com/articles/{{id}}?preview=123acb`
    * Is referencing this item's fields enough?
    * What about adding other dynamic parameters for auth?
* ~~Button or Link? (maybe always a button?)~~
* ~~Worth having an option to include source in `iframe`?~~
* ~~Send POST variables?~~

**Comment by dimitrov-adrian** [comment]
Is it covered by https://github.com/directus/directus/pull/3677

**Comment by benhaynes** [comment]
Yup!! Just need to get that reviewed and merged. We've been focused on stability, bugs, and Docs... should get to review/merge most PRs this/next week though!

**Comment by rijkvanzanten** [comment]
Added in https://github.com/directus/directus/pull/3677
