### ISSUE TITLE
Custom webhook return payload invalid 

### ISSUE THREAD

**Issue by botzill** [directus/directus#2912]
I return from custom webhook endpoint on `items.delete.before` and 500 error, but it tells me this:

<img width="579" alt="Screen Shot 2020-11-11 at 10 44 54" src="https://user-images.githubusercontent.com/4686040/98789501-09a54b80-240b-11eb-9b09-e30eb19734bd.png">

What is the proper response and format to show here the proper message ?

**Comment by benhaynes** [comment]
Can we get this in the updated docs? Want to make sure all `documentation` issues are closed so the docs are truly set. @rijkvanzanten

**Comment by rijkvanzanten** [comment]
This return structure has since been fixed, and the example in the docs is accurate 👍🏻 Lemme know if you still have problems with it @botzill and we can reopen
