### ISSUE TITLE
Add Validation Pane to Field Setup Flow

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#2916]
This will use the same JSON permissions interface as in Role, but will be required for all field values. This means we will also need to add a `_regex` operator to the JSON builder. One thing that still needs to be discussed is where relational validation will occur (eg: min/max items, etc).

### The Validation Flow:
1. Ensure user's role permissions and validation passes
2. Ensure field validation passes

**Comment by MichaelNussbaumerGOWEST** [comment]
ref: https://github.com/directus/directus/discussions/2979
