### ISSUE TITLE
Add _regex to permission builder

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#2917]
We need support for `_regex` in the permission builder, but this operator will only be allowed for certain use cases.

**Comment by rijkvanzanten** [comment]
\+ Use this to validate directus_users.email, as per https://github.com/directus/directus/issues/4159#issue-811502669

**Comment by MichaelNussbaumerGOWEST** [comment]
When you start on this feature, it would be great to consider adding a possibility to add validation on field level. 

In my  opinion it is more common that a validation (example email address) applies to more then one user role. Also in  it makes more sense to define the validation of a value directly when creating that field.

**Comment by benhaynes** [comment]
@MichaelNussbaumerGOWEST — absolutely. That's why we haven't done this yet, it needs more thinking to be done correctly. We need Field-Level validation (so an email field only needs to be set up once), and also Role-Level validation (so certain roles can have more strict/lenient rules).

I _think_ the main thing we need is how to _merge_ these two validation sets. Right? @rijkvanzanten

**Comment by rijkvanzanten** [comment]
> I think the main thing we need is how to merge these two validation sets. Right? @rijkvanzanten

Correct!

Luckily we already prepared a lot of this merging permissions business in https://github.com/directus/directus/pull/4004.

Which makes me think, the _permissions_ merging is an _OR_, cause whichever permissions set is more flexible is the one that "wins", but for validation, it should be _AND_ right? 🤔 

I'm imagining that you'll have a generic email regex on the field, but then a "has to be .com" on the role for example

**Comment by rijkvanzanten** [comment]
A second "problem" with regex (and probably future operators), is that they'll only work in the _validation_ step, and not in _permissions_. EG you can set "Field has to be valid regex", but you can't set "Can only read items with a valid email", as we can't run regexes on the database during read
