### ISSUE TITLE
Resizing table layout columns resets when dragging too long

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#2920]
~~If you click to drag column sizes... if you wait too long (2s) the columns will reset to 200px each.~~

**Comment by Nitwel** [comment]
I was not able to reproduce this, please reopen when this is still an issue.

**Comment by benhaynes** [comment]
Wow. This was bugging me for so long, and you're right... it's just not happening anymore! Must have been some other PR/fix or a browser update... but either way, glad it's resolved!

**Comment by Nitwel** [comment]
It might has been the bookmark fix I did which cleaned alot of stuff up in presets, but I don't really know for sertain.

**Comment by rijkvanzanten** [comment]
> It might has been the bookmark fix I did which cleaned alot of stuff up in presets, but I don't really know for sertain.

Pretty sure this was it 👍🏻 The problem before is that it would update the bookmark in the API and then override the local state _while_ you were dragging, effectively resetting you back to the way it was before

**Comment by benhaynes** [comment]
Welp, good job then @Nitwel !! 🥳
