### ISSUE TITLE
Cannot add an image field to the collection

### ISSUE THREAD

**Issue by adrianhajdin** [directus/directus#2922]
Directus 9.0.0-rc.13

Cannot add an image field to the collection (next button is disabled) even though all I've put the values in all the required fields.

**Comment by mdespeuilles** [comment]
I have exactly the same issue.
@adrianhajdin have you solved this issue?

**Comment by benhaynes** [comment]
This is a very odd one, but no one here is able to reproduce it. If someone can provide more info on database vendor or steps to replicate the problem, we'll re-open!
