### ISSUE TITLE
NULL files and assets error

### ISSUE THREAD

**Issue by metalmarco** [directus/directus#2924]
Clean installation of 9.0.0-rc.14
It looks like Directus images (like the login page and menu logos) are not loaded, because it's requestiong a NULL asset.

<img width="1362" alt="login page" src="https://user-images.githubusercontent.com/7231582/99156366-a2182600-26c0-11eb-86b3-8a1d81f74720.png">

<img width="1362" alt="menu logo" src="https://user-images.githubusercontent.com/7231582/99156363-a04e6280-26c0-11eb-8c64-b9694cdfc2d3.png">

When I access the Project Configuration a call to NULL files items is performed.

<img width="1362" alt="project configuration page" src="https://user-images.githubusercontent.com/7231582/99156362-9d537200-26c0-11eb-9998-2c5021647038.png">

---

### Project details
Directus Version: 9.0.0-rc.14
Environment: production
OS: macOS Big Sur (11)
Node: 14.14.0

**Comment by metalmarco** [comment]
> Ahh I think I remember reading something about MariaDB reporting the default value as `"NULL"` instead of `NULL` (MySQL). Lemme check

Did you manage to take a look at it @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
Nope! I'll update back here when I find anything
