### ISSUE TITLE
Incorrect TSQL syntax on /users endpoint

### ISSUE THREAD

**Issue by kukulaka** [directus/directus#2931]
**Directus**: 9.0.0-beta.1
**Node**: v12.18.3
**SQL Server**: 15.0.2000.5

Issue with SQL used in `/users/me?fields=*,avatar.*,role.*`  endpoint. Error suggests incorrect parsing of ID values and there should not be double brackets around ` ((@p1, @p2))`

`select top (@p0) * from [directus_roles] where [id] in ((@p1, @p2)) order by [id] asc - Incorrect syntax near ','.`

The correct form for given ID is not a number should be: 
`select top (@p0) * from [directus_roles] where [id] in (@p1, @p2) order by [id] asc`

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/directus/pull/4140
