### ISSUE TITLE
Slug does not have a linked field

### ISSUE THREAD

**Issue by maartenvn** [directus/directus#2932]
**Directus**: 9.0.0-beta.2
**Node**: v14.10.0
**MySQL**: Ver 14.14

There is no option to link a slug to an existing field.

![image](https://user-images.githubusercontent.com/6013068/94472503-24a95c80-01cb-11eb-819c-23b8b3bc3bff.png)

**Comment by prikr** [comment]
Is there any update on this @rijkvanzanten?

**Comment by benhaynes** [comment]
[**Unfortunately, we can not provide estimates on features or fixes**](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍 . Or contribute a pull-request... after all, this is OSS!

**Comment by prikr** [comment]
@benhaynes crystal clear!

**Comment by benhaynes** [comment]
Could this be solved with extension bundles? Then we could bundle an event hook with this interface that handles the API/logic side, right? @rijkvanzanten

**Comment by rijkvanzanten** [comment]
Yeah! That's one way :)

**Comment by jordie23** [comment]
> We're trying to think through how to implement this in a way that the API can enforce it as well. By adding an interface option and handling it on the client side, this would only work when using the Directus app to create an item, but will be ignored when creating an item through the API directly

Personally I don't think this would be a problem. Maybe I'm just thinking of my own use case, I get you guys need to think more broadly, but I'd see this ability as just a way to help make it easier to create the content item in the app. I think living in the client side app is the right place for that. If I were to create an item through an API request I'd find it annoying to not be able to manually set this value.

I guess I'm basing my concept of it on how wordpress does it. If you haven't touched the slug field, it bases the value on the title field and changes as you change the title. You can click to edit the slug field and from then on it won't auto-generate from the title field. The final value would essentially be a manually curated value, so you could expect the API requirements for the field would be to pass in a manually created value.

This reason I see it this way is that I see the slug is a fairly "technical" field, as in it's not a field that the content writers usually concern themselves with (when it's usually based on the title) so it'd be very helpful if this was a field that they rarely have to touch but can if they need to.

**Comment by benhaynes** [comment]
The current thinking is to merge this interface with the `text input` (soon to be called `input`) interface. We'll see what Rijk comes up with for the API logic side, but if that doesn't work out, then an App-only solution would suffice. Ideally Interfaces have an API  side too though.
