### ISSUE TITLE
Foreign Key name too long

### ISSUE THREAD

**Issue by kukulaka** [directus/directus#2935]
**Node**: 12.18.3
**Oracle**:  19.3
**Directus**: 9.0.0-beta.2

There is a hard limit on foreign key name length in oracle which is 30 chars. 

Foreign key names will need to be shortened to this length or we can use base64 encoded sha1 of that name instead.
Oracle has removed this limitation for tables and other objects but not keys it would appear :| 

@rijkvanzanten how do you think we should progress?

**Comment by yapnel** [comment]
I'm getting the same error.

Automatically generated name "directus_fields_collection_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
...

Something went wrong while seeding the database:

undefined alter table "directus_fields" add constraint "directus_fields_group_foreign" foreign key ("group") references "directus_fields" ("id") on update CASCADE on delete SET NULL - ORA-00905: missing keyword

@rijkvanzanten - is there a fix for this please?

**Comment by rijkvanzanten** [comment]
> Automatically generated name "directus_fields_collection_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.

This is a warning, and doesn't seem to interfere with installation otherwise 🤔 

> undefined alter table "directus_fields" add constraint "directus_fields_group_foreign" foreign key ("group") references "directus_fields" ("id") on update CASCADE on delete SET NULL - ORA-00905: missing keyword

I believe this was fixed in a subsequent update 🙂 

I'll close this for now. We can reopen if it turns out to be problematic

**Comment by stoconnor** [comment]
**Node:** 14.15.4
**Oracle:** 19.8
**Directus:** 9.0.0-rc.51

I'm getting the same error as outlined above when connecting to an Oracle DB. Project initiation fails:

`[Error] alter table "directus_fields" add constraint "directus_fields_group_foreign" foreign key ("group") references "directus_fields" ("id") on update CASCADE on delete SET NULL - ORA-00905: missing keyword`
