### ISSUE TITLE
OracleDB Version

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#2941]
@kukulaka — do you have the tested version of OracleDB for the Docs? We still have it listed as TBD.

**Comment by benhaynes** [comment]
We have the OracleDB version in the Docs as `19+`, and https://github.com/directus/directus/issues/2935 should handle the other part of this ticket.

**Comment by kukulaka** [comment]
Hi both, I will get some of the examples where they are too long once I set up again. Should be within the next day or two
