### ISSUE TITLE
Authentication with oauth providers

### ISSUE THREAD

**Issue by danieljwestman** [directus/directus#2943]
Directus 9 beta10
PG 12

I’m missing docs/guide for how to add my own oauth provider in v9. Something like in v8 would be nice.

**Comment by bitbaggi** [comment]
I tried this too.
But directus redirects me only to http://localhost:8055/auth/oauth/keycloak?redirect=http://localhost:8055/admin/login
My Env Variables are
`OAUTH_KEYCLOAK_KEY: "client_id"
 OAUTH_KEYCLOAK_SECRET: "client_id"
 OAUTH_KEYCLOAK_SCOPE: "openid email"
 OAUTH_KEYCLOAK_AUTHORIZE_URL: "https://sso-host.de/auth/realms/master/protocol/openid-connect/auth"
 OAUTH_KEYCLOAK_ACCESS_URL: "https://sso-host.de/auth/realms/master/protocol/openid-connect/token"
`

**Comment by benhaynes** [comment]
This has been completed...

https://docs.directus.io/guides/api-config/#oauth-single-sign-on-openid
