### ISSUE TITLE
No way to set unique fields

### ISSUE THREAD

**Issue by WoLfulus** [directus/directus#2944]
I'm trying to set an `unique` field in the schema section of a collection and I couldn't find any way to do it.

**Comment by sercanvirlan** [comment]
> We'll have to wait for [knex/knex-schema-inspector#20](https://github.com/knex/knex-schema-inspector/issues/20) before we can show the toggle in the app

PR sent to inspector for mysql and postgres!

**Comment by rijkvanzanten** [comment]
Thanks @sercanvirlan! Would you be able to add it in for the other 3 as well? 😁

**Comment by sercanvirlan** [comment]
I'll do my best :) but we need to add tests for three of them first. I think i can handle it, let's see for tomorrow!

**Comment by rijkvanzanten** [comment]
Thanks a lot! That's the biggest step in getting unique constraint support in Directus ❤️

**Comment by sercanvirlan** [comment]
Update: mysql, postgres, mssql and sqlite support are okey for inspector

**Comment by rijkvanzanten** [comment]
> Also I wanna ask about Oracle, should we really support oracle

Good question, I've been wondering the same about MySQL, MS SQL, and SQLite.. 👀  hihi

Seriously though, from what I can tell by some—super limited—googling is that OracleDB seems to be used about as often as MS SQL, but like I said, I don't have the metrics to back this article up myself: https://scalegrid.io/blog/2019-database-trends-sql-vs-nosql-top-databases-single-vs-multiple-database-use/

**Comment by sercanvirlan** [comment]
Okey then 😀 

I'll waste some times to cover Oracle, I hope i can figure this out.

**Comment by sercanvirlan** [comment]
Sorry, I tried hard but i couldn't connected Oracle db instance both cloud and local instances (vm, docker)

Gave up. 😢

**Comment by rijkvanzanten** [comment]
@sercanvirlan That's OK! I've struggled with that myself as well.. 

Rest of the PR good to go?? 🙂

**Comment by sercanvirlan** [comment]
Awesome!

There are some possible improvements about foreign_keys, but in this state it's good to go, I will maintain if anything needed.

**Comment by workatease** [comment]
are we also planning to support composite indexes?

**Comment by rijkvanzanten** [comment]
@workatease lets figure that out as part of https://github.com/directus/directus/issues/2910
