### ISSUE TITLE
Sqlite does not support alter column

### ISSUE THREAD

**Issue by dimitrov-adrian** [directus/directus#2948]
Changing interface of field trigger error

```
08:15:50 🚨 Sqlite does not support alter column. 
Error: Sqlite does not support alter column.
    at TableCompiler_SQLite3.addColumns (/directus/node_modules/knex/lib/dialects/sqlite3/schema/tablecompiler.js:35:11)
    at TableCompiler_SQLite3.TableCompiler.alterColumns (/directus/node_modules/knex/lib/schema/tablecompiler.js:184:10)
    at TableCompiler_SQLite3.TableCompiler.alter (/directus/node_modules/knex/lib/schema/tablecompiler.js:77:8)
    at TableCompiler_SQLite3.TableCompiler.toSQL (/directus/node_modules/knex/lib/schema/tablecompiler.js:34:20)
    at TableBuilder.toSQL (/directus/node_modules/knex/lib/schema/tablebuilder.js:45:42)
    at SchemaCompiler_SQLite3.alterTable (/directus/node_modules/knex/lib/schema/compiler.js:89:25)
    at SchemaCompiler_SQLite3.toSQL (/directus/node_modules/knex/lib/schema/compiler.js:72:26)
    at SchemaBuilder.toSQL (/directus/node_modules/knex/lib/schema/builder.js:79:43)
    at /directus/node_modules/knex/lib/runner.js:31:36
    at /directus/node_modules/knex/lib/runner.js:277:24
08:15:50 ✨ request errored PATCH 500 /fields/table1/body 18ms
```

---

### Project details
Directus Version: 9.0.0-beta.13
Environment: production
OS: Linux 4.19.76-linuxkit
Node: 14.13.1

**Comment by trogmaniac** [comment]
The lack of activity regarding this (and other) bugs makes me question my decision to choose Directus for my latest project. Do i have to go back to Strapi?

It's not that i need sqlite, it's just the fact that this issue (which in all likelyhood is a simple fix) is still not solved after 4 months.

**Comment by benhaynes** [comment]
> The lack of activity regarding this (and other) bugs makes me question my decision to choose Directus for my latest project. Do i have to go back to Strapi? It's not that i need sqlite, it's just the fact that this issue (which in all likelyhood is a simple fix) is still not solved after 4 months.

@trogmaniac — First off, let me state a few things:

* The ticket is 3 months old, not 4... and throughout that time we're been building other (still unreleased) products/services within our ecosystem.
* We're focused on certain DB vendors at a time. MySQL and Postgres were first, now we're preparing to work on SQLite.
* v9 is still in RC, and SQLite is labeled as Alpha/Beta in the CLI
* This is an OSS project, built by a small/passionate team, offered completely free
* If you want something to go faster, submit a PR or sponsor the work. Especially if you think this ticket is easy.

Threatening to move to a competitor doesn't make us work faster — if you want to go pay for some other platform, that's your decision. We're not trying to build something _quick and dirty_, we're making sure what we build/fix is done so correctly, and that takes a little longer.

**Comment by maggie0002** [comment]
And when trying to install with an existing database:

```
npx create-directus-project my-project
npx: installed 53 in 8.79s
? Choose your database client SQLite (Beta)
? Database File Path: /tmp/data.db

Something went wrong while seeding the database:

[SQLITE_READONLY] create table `directus_collections` (`collection` varchar(64), `icon` varchar(30), `note` text, `display_template` varchar(255), `hidden` boolean not null default '0', `singleton` boolean not null default '0', `translations` json, `archive_field` varchar(64), `archive_app_filter` boolean not null default '1', `archive_value` varchar(255), `unarchive_value` varchar(255), `sort_field` varchar(64), primary key (`collection`)) - SQLITE_READONLY: attempt to write a readonly database

Please try again
```

**Comment by zabbal** [comment]
Can confirm - the `npx create-directus-project directus-example` command from quickstart guide fails with that error on latest ubuntu.
