### ISSUE TITLE
Check for app access in more places

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/directus#2951]
If a users has a role which doesn't have "Admin Access" enabled, but "App Access" enabled, cannot login to the app.

![Screenshot_20](https://user-images.githubusercontent.com/15796397/97403263-b1f4e380-1926-11eb-85da-6f3d64d087af.png)
![Screenshot_21](https://user-images.githubusercontent.com/15796397/97403269-b3261080-1926-11eb-960c-ee8573035177.png)

Version: 9.0.0-rc.2

**Comment by MichaelNussbaumerGOWEST** [comment]
Now I got this a second time. 

I started a new project and here is how you can reproduce this issue:

- Create a new User and use the `+` for `Create Item` to create a new role

If you create the role that way, the permissions are not set at all which causes the problem.

**Comment by rijkvanzanten** [comment]
Ref https://github.com/directus/directus/issues/3505
