### ISSUE TITLE
Add validation for o2m-type relations

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#2959]
We should be able to setup validation, like `required`, for o2m type fields. This includes specialized flags for things like "min/max number of items".

@benhaynes can you think through how to configure this in the field setup flow?

**Comment by benhaynes** [comment]
Did we just change our thinking on this? I like the idea of having this in the schema/relationship, though it also could go under Validation using a `COUNT()`. I'm wondering which makes more sense... @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
@benhaynes It's the question of data integrity vs permissions 🤔 Setting it on the relationship makes it kinda like "allow null" in a way where it's globally the same for everybody, while doing it on the validation step makes it more a "As a public user, you can only like 3 things at once"

**Comment by benhaynes** [comment]
Yeah, that's what I was thinking too. Both are useful, we can always extend permissions in the future with `COUNT()`, so we just need to decide if having a strict rule on the relationship is important too.
