### ISSUE TITLE
Ensure version is dynamic in Actions

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#3125]
@WoLfulus I noticed there's two places under `/.github/actions` that has hardcoded (outdated) version numbers:

https://github.com/directus/directus/blob/d44f99331c3929603afaafb0bb5b2a17e15e8b52/.github/actions/Makefile#L3

and

https://github.com/directus/directus/blob/d44f99331c3929603afaafb0bb5b2a17e15e8b52/.github/actions/build-images/rootfs/directus/images/main/examples/docker-compose.yml#L16

What do these do? Can we make sure these stay up to date?

**Comment by WoLfulus** [comment]
Makefile can be set to any version, its just for local building/testing. 

docker-compose once it gets out of RC we can set it to only `v9`
