### ISSUE TITLE
Can't seed the database [Postgres12 v12.3-1]

### ISSUE THREAD

**Issue by M0ko** [directus/directus#3128]
Directus_9_rc_15
Postgres12 v-12.3-1
Node v12.16.1
npm 6.13.4
 I got this error after the configuration of de the database when trying to create a new directus project. 

![image](https://user-images.githubusercontent.com/43095432/99656180-e149cc80-2a5c-11eb-86b4-0730eaab114d.png)

**Comment by rijkvanzanten** [comment]
Are you sure the credentials to the database are correct? The `ECONNRESET` error in Node means that there was a connection error to the DB

**Comment by M0ko** [comment]
Thanks for your reply, seems like there is indeed something wrong with our server.

**Comment by rijkvanzanten** [comment]
I'll close this issue for now then 🙂
