### ISSUE TITLE
Installation on DigitalOcean Managed MySQL

### ISSUE THREAD

**Issue by lintoncaldecott** [directus/directus#3129]
I get the following error
![image](https://user-images.githubusercontent.com/7962870/99658872-bcf3ed00-2a68-11eb-9acd-6b0db141dfed.png)

Running the following `SET sql_require_primary_key=0
SELECT @@sql_require_primary_key;
`
results in that value being 0, however I still get the same error after running the install again.

**Comment by rijkvanzanten** [comment]
Strange, it's definitely marked as primary 

https://github.com/directus/directus/blob/290d272b5446c7b708630c4a86cf75f32436f16d/api/src/database/seeds/01-collections.yaml#L4-L7

**Comment by everyx** [comment]
@lintoncaldecott Maybe you should set some [Global SQL Mode](https://www.digitalocean.com/docs/databases/mysql/how-to/set-sql-mode/) like this below.

![image](https://user-images.githubusercontent.com/1665522/99866717-61ec0280-2bee-11eb-911f-29c5ab969d02.png)

**Comment by rijkvanzanten** [comment]
Closed in favor of https://github.com/knex/knex/issues/4141
