### ISSUE TITLE
Use render-template in repeater header

### ISSUE THREAD

**Issue by MiniDigger** [directus/directus#3135]
# what I expect

the template of a parent repeater should use the template of the child repeater, to display that field

# what I experience

the value displayed is [object Object]

repeater config:
![image](https://user-images.githubusercontent.com/2185527/99684554-e1a88e80-2a81-11eb-81d3-7a58dd92c83c.png)

in collection:
![image](https://user-images.githubusercontent.com/2185527/99684782-216f7600-2a82-11eb-9cd4-f14a6911fbfb.png)

(running rc 13)

**Comment by Nitwel** [comment]
This could be tricky to do but would be helpful, there are just a few problems in the way we have to figure out first.
Micromustache which renders the template doesn't support array rendering natively so we might have to look for a different library.
I'm not sure if it would make sense to plainly just check if the field is a repeater or not.

A workarround that works right now would be to use `{{ hours[0].start }} {{ hours[0].end}}`.

**Comment by rijkvanzanten** [comment]
This would effectively mean that we'd have to let the user setup displays for the individual "virtual" fields next to the interfaces. 

I'm wondering if we should leave that up to the "relational repeater", instead of trying to reinvent all these wheels to work on static JSON 🤔

**Comment by tylerforesthauser** [comment]
Since this is still open, I just wanted to throw my opinion in here. I think it'd be super helpful to at least offer a somewhat more robust toolset for dealing with the JSON content, perhaps by swapping Micromustache for something like Handlebars. If I'm understanding @rijkvanzanten's comment correctly, allowing the repeater itself to control its own display and then referencing that repeater in the parent display template would make these [helper functions](https://handlebarsjs.com/guide/builtin-helpers.html#if) from Handlebars that much more useful.

**Comment by Kematia** [comment]
I agree with tyler! Having the possibility to extend the logic would be great...

One of my use cases would be to display the value of a repeater by the current language of the user.

**Comment by rijkvanzanten** [comment]
@tylerforesthauser @Kematia I hear ya! The only thing I'm wondering about all this is how much we'd want to re-invent the display-template wheel for static JSON, while a relational repeater would support all of this ootb (presumably), cause it'll be able to rely on the existing display-template and rendering logic as regular relational fields 🤔

**Comment by Kematia** [comment]
Wouldn't that kind of logic be usable in a lot of other places? Not only in repeaters display... something like if the user is an admin show something, if it's an editor show something else.

**Comment by rijkvanzanten** [comment]
@Kematia Yeah! But that would be an extension to our display template setup we got right now. The problem in this OP is whether or not we should try to recreate the render-template stuff for use with "static" JSON instead of on fields 🤔

**Comment by benjaminpreiss** [comment]
I think it would still be great to have a different templating engine, like mustache.js for example...
