### ISSUE TITLE
Disabling seconds in datetime element should truncate the seconds

### ISSUE THREAD

**Issue by MiniDigger** [directus/directus#3136]
![image](https://user-images.githubusercontent.com/2185527/99684933-4cf26080-2a82-11eb-9fe4-8ff606b59e31.png)

this is inside a (nested) repeater if that matters:
![image](https://user-images.githubusercontent.com/2185527/99685030-6bf0f280-2a82-11eb-909c-5b8effc60179.png)

(running rc 13)

**Comment by rijkvanzanten** [comment]
I believe this was resolved in rc.14:

https://github.com/directus/directus/blob/290d272b5446c7b708630c4a86cf75f32436f16d/app/src/interfaces/datetime/datetime.vue#L269

Let me know, we can reopen if I'm mistaken 🙂

**Comment by MiniDigger** [comment]
nope, it still adds seconds on rc15

**Comment by MiniDigger** [comment]
(this is only an issue with the template in repeaters, for a "normal" date field it works)

**Comment by MiniDigger** [comment]
thinking more about this, maybe #3135 will fix this then?

**Comment by rijkvanzanten** [comment]
Ohhh I see I see, yes, the repeater currently prints just the "raw value", and doesn't use the actual configured displays. #3135 should fix that!
