### ISSUE TITLE
Auth Refresh throws Invalid Credentials if using german date format

### ISSUE THREAD

**Issue by MiniDigger** [directus/directus#3139]
RC 15, using a postgre db (version 12.3). this DB uses a non public search path, `directus`, if that matters.

reproduceable by logging in an pressing f5, you will be redirected to login pack and can see in browser console that /auth/refresh failed with 401 -> `{"errors":[{"message":"Invalid user credentials.","extensions":{"code":"INVALID_CREDENTIALS"}}]}`

I narrowed it down to this check:
https://github.com/directus/directus/blob/290d272b5446c7b708630c4a86cf75f32436f16d/api/src/services/authentication.ts#L128

it fails, because `record.expires` is `null`
debug code:
```js
const record = yield database_1.default
                .select('directus_sessions.*', 'directus_users.email', 'directus_users.id')
                .from('directus_sessions')                   
                .where({ 'directus_sessions.token': refreshToken })
                .leftJoin('directus_users', 'directus_sessions.user', 'directus_users.id')
                .first();                           
            if (!record || !record.email || record.expires < new Date()) {
                console.log("refresh failed: ");
                console.log(record);                                                                           
                console.log(record.email);                           
                console.log(record.expires);
                console.log(record.expires < new Date());                                  
                throw new exceptions_1.InvalidCredentialsException();           
            }
```

output:
```
refresh failed:
--
  | {
  | token: '-Aw_Wg_tdQ7owc2QsQGQc6li4zVrVwEjIvJgi1ryWyqYVmvzPVCpv1-4jGzM6YVx',
  | user: '2c9a94b5-bf9d-44e4-806f-c946f105261b',
  | expires: null,
  | ip: '10.58.0.32',
  | user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36',
  | email: 'martin.benndorf@xxxx',
  | id: '2c9a94b5-bf9d-44e4-806f-c946f105261b'
  | }
  | martin.benndorf@xxxxx
  | null
  | true
  | 17:34:36 ✨ request completed POST 401 /auth/refresh 14ms

```

directus_sessions table:
| token | user | expires | ip | user\_agent |
| :--- | :--- | :--- | :--- | :--- |
| -Aw\_Wg\_tdQ7owc2QsQGQc6li4zVrVwEjIvJgi1ryWyqYVmvzPVCpv1-4jGzM6YVx | 2c9a94b5-bf9d-44e4-806f-c946f105261b | 2020-11-26 16:34:09.006000 | 10.58.0.32 | Mozilla/5.0 \(Windows NT 10.0; Win64; x64\) AppleWebKit/537.36 \(KHTML, like Gecko\) Chrome/86.0.4240.183 Safari/537.36 |

directus_users table:
| id | first\_name | last\_name | email | password | location | title | description | tags | avatar | language | theme | tfa\_secret | status | role | token | last\_access | last\_page |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 2c9a94b5-bf9d-44e4-806f-c946f105261b | NULL | NULL | martin.benndorf@xxxxx | xxxxx | NULL | NULL | NULL | NULL | NULL | en-US | auto | NULL | active | 9347cf8e-6288-4cef-874b-117ef5286b6a | xxxxx| 2020-11-19 16:34:22.993000 | /settings/data-model |

manually doing the query works:
```sql
select directus.directus_sessions.*, directus.directus_users.email, directus.directus_users.id
from directus.directus_sessions
left join directus.directus_users on directus.directus_sessions.user = directus.directus_users.id
where directus_sessions.token = '-Aw_Wg_tdQ7owc2QsQGQc6li4zVrVwEjIvJgi1ryWyqYVmvzPVCpv1-4jGzM6YVx'
```
| token | user | expires | ip | user\_agent | email | id |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| -Aw\_Wg\_tdQ7owc2QsQGQc6li4zVrVwEjIvJgi1ryWyqYVmvzPVCpv1-4jGzM6YVx | 2c9a94b5-bf9d-44e4-806f-c946f105261b | 2020-11-26 16:34:09.006000 | 10.58.0.32 | Mozilla/5.0 \(Windows NT 10.0; Win64; x64\) AppleWebKit/537.36 \(KHTML, like Gecko\) Chrome/86.0.4240.183 Safari/537.36 | martin.benndorf@xxxxx | 2c9a94b5-bf9d-44e4-806f-c946f105261b |

**Comment by MiniDigger** [comment]
@rijkvanzanten took a closer look at this todo, this does seem like a knex resolves the filed as text. when I log the knex response, the expires field is this:
```
Field {
   name: 'expires',
   tableID: 19823,
   columnID: 3,
   dataTypeID: 1184,
   dataTypeSize: 8,
   dataTypeModifier: -1,
   format: 'text'
   },
```

**Comment by rijkvanzanten** [comment]
@MiniDigger That's strange.. On my end, `expires` is parsed to a `Date` before it's returned by knex. Given, I'm in the `public` schema. Lets see if that makes a difference

**Comment by rijkvanzanten** [comment]
@MiniDigger I can't seem to reproduce this on my end at all :/

The fact that `expires` is `null` doesn't make any sense to me. In your post, you clearly mention that the expires value does exist in the DB right? 

Would you be able to share a database dump so I can try setting this up exactly the same as you have it?

**Comment by MiniDigger** [comment]
yeah, it exists in the DB, ill check on monday, maybe I get setup directus locally and connect to my remote DB so I can take a closer look at whats happening. if you got any pointers where to look at that would help.

Not sure if I can share a full DB dump, but I get I can export the session and user table, will do that too.

**Comment by MiniDigger** [comment]
HA!

this is a date format issue. postgres-date can't handle my date "08.12.2020 18:50:41.728 CET"

don't ask me why the pg lib seems my date that way tho
in the db, I see
| token | user | expires | ip | user\_agent |
| :--- | :--- | :--- | :--- | :--- |
| 6x22wkg59QZZeu\_K\_mWnIygSUIswwuhpyMLl4f338O9DvlhBR5fiMW7f3k3KWq9Z | 2c9a94b5-bf9d-44e4-806f-c946f105261b | 2020-12-08 17:50:41.728000 | ::1 | Mozilla/5.0 \(Windows NT 10.0; Win64; x64\) AppleWebKit/537.36 \(KHTML, like Gecko\) Chrome/86.0.4240.183 Safari/537.36 Edg/86.0.622.63 |

maybe its because of my PC timezone?

**Comment by rijkvanzanten** [comment]
Wow that's obscure, good catch! Now we'll have to figure out where that date format is created in the first place 🤔

**Comment by MiniDigger** [comment]
for now, I have just hacked in support for the german date format into postgres-date:
https://www.jstoolset.com/diff/35af048c328a4a8f

I have no idea why the pg client reads/receives my date in the german format tho. 
`show datestyle` returns `ISO, DMY`, as I would expect.

**Comment by rijkvanzanten** [comment]
Super strange.. It also means that this bug occurs "before" it reaches Directus it sounds like. "We" receive `null` as a value, so it must go south when Knex tries converting the date to a `Date` but it receives an "invalid" format? 🤔

**Comment by MiniDigger** [comment]
no, the conversion happens in the pg client it seems.
pg client uses pg types, to convert some types to native JS types, for the rest it returns text.
since timestampz is handled by pg types, it uses pg date to try to convert to date, but fails since my format is "wrong" (it only handles iso which seems like a big in itself?)
pg types allows overriding the default type parsers, so it would be fixable for us to overrride the timestampz parser with smth like moment which actually handles dates properly I guess.
I haven't had time to look into how to do that too.

I am not sure what the best solution would be. I see 3 places where it could be tackled
* force my time format to ISO (however I would do that, since my DB seems to be ISO as far as I can tell)
* patch pg date to accept my date format (thats what I did as hacky fix for now, so the issue doesn't annoy me anymore)
* override the timestampz parser (and other date parsers I guess) via directus with a parser that understands multiple formats

**Comment by rijkvanzanten** [comment]
I don't think this is something we should hack in on the Directus side 🤔 

We rely on `pg` -> `knex` to abstract that date processing away. Overriding things that low-level in the Directus layer is bound to cause trouble cross DB vendor / version. 

> since timestampz is handled by pg types, it uses pg date to try to convert to date, but fails since my format is "wrong" (it only handles iso which seems like a big in itself?)

This to me sounds like we should look into improving the underlying pg / pg-date handling rather than try to hack in workarounds in the directus layer 👍🏻

**Comment by MiniDigger** [comment]
yeah, pretty sure my fix for this is to patch some lib, maybe I should look into upstreaming that, not sure why I didn't

**Comment by Attacler** [comment]
I'm on Directus RC90 right now and i have the same issue, is there any news on it?

**Comment by rijkvanzanten** [comment]
@Attacler Are you sure you have the same problem? If you see in this thread, there was a very specific subset of variables in order to get the problem to show up (and subsequently resolve). It's probably best to open a new issue 👍🏻
