### ISSUE TITLE
Add "filter" option to m2o/o2m/m2m

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#3143]
Allows you to scope what users can select from

**Comment by MichaelNussbaumerGOWEST** [comment]
It would be great to consider a combination with https://github.com/directus/directus/discussions/2993 to make it possbile to have field related filter.
 
For Example show just states of the selected country. :)

**Comment by rijkvanzanten** [comment]
Yes! That's a very good idea

**Comment by magomimmo** [comment]
> Yes! That's a very good idea

Agree. It's a very common scenario. In the mean time have you any workaround?

**Comment by benhaynes** [comment]
@magomimmo — yes, a custom interface 😉

**Comment by magomimmo** [comment]
Thanks @benhaynes, I appreciate
