### ISSUE TITLE
Implement Deploy Buttons

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#3149]
We need to configure all of the different auto-deploy buttons on the various IaaS platforms. Depending on config options available, we could also have "Basic" (SQLite) vs "Advanced" (Postgres+Redis) options Below is a running list of those to add:

* DigitalOcean
* Platform.sh
* Heroku

![Screen Shot 2020-11-20 at 9 59 34 AM](https://user-images.githubusercontent.com/522079/99814576-292d2a00-2b17-11eb-800c-e39a40cae7f7.png)

**Comment by benhaynes** [comment]
@rijkvanzanten @WoLfulus — any other services we want to add? Anything we want to add to these guides? It seems like we have these three:

https://docs.directus.io/getting-started/installation/#one-click-installs

Is this ticket done?

**Comment by rijkvanzanten** [comment]
To me it's done _enough_ to close. There might be more we want to add in the future, but we'll open tickets for those when they pop up 👍🏻
