### ISSUE TITLE
Manuel type selection in M2M queries

### ISSUE THREAD

**Issue by Cilenco** [directus/directus#3157]
When querying M2M relations we have to select the direction of the relation within the query. What I mean by that is more easily explained in an example. Consider the following situation:

```
movie                     movie_actor                actor
+--------+                +----------+               +--------+
| id     |                | id       |               | id     |
+--------+                +----------+               +--------+
| ...    |                | movie_id |               | ...    |
+--------+                +----------+               +--------+ 
| actors |                | actor_id |
+--------+                +----------+
```
To query a list of movies with their related actors my GraphQL query would look something like this:

```
query MovieList($limit: Int, $skip: Int) {
    items {
        movie(limit: $limit, offset: $skip) {
            actors {                             // of type movie_actor
                actor_id {                       // of type actor
                    ...
                }
            }
        }
    }
}
```

Notice that actors are of type `movie_actor` and I have to select the actor object myself. This results in an unnecessary nesting in the JSON output but worse is, that it enables me to write endless recursive queries trough fragments when I select the movie again here. I would expect actors to be of type `[actor]` here which resolves both problems.

**Comment by rijkvanzanten** [comment]
The reason for this is that you can have custom fields on the junction table, and also because the M2M relationship type doesn't really exist (it's a o2m-m2o combo). This is by design, and won't be changed in the core codebase. I'm down to discuss a feature to "auto-skip" the junction table with a query param / attribute, but lets open that up in a standalone feature discussion 🙂

**Comment by Cilenco** [comment]
Isn't the combo of O2M and M2O a strengthening point for this? And for the case of the custom fields: Shouldn't the junction collection endpoint be used for this?

**Comment by rijkvanzanten** [comment]
> Isn't the combo of O2M and M2O a strengthening point for this

Not sure if I'm following what you mean here.

> And for the case of the custom fields: Shouldn't the junction collection endpoint be used for this?

I don't see why that would / should / has to be a requirement
