### ISSUE TITLE
Issue Seeding with npx install on a MSSQL database

### ISSUE THREAD

**Issue by Mortalife** [directus/directus#3158]
I've given the following error after selecting MSSQL as my database.

> Something went wrong while seeding the database:
>
>[EREQUEST] ALTER TABLE [directus_fields] ADD CONSTRAINT [directus_fields_group_foreign] FOREIGN KEY ([group]) REFERENCES >[directus_fields] ([id]) ON UPDATE CASCADE ON DELETE SET NULL - Could not create constraint or index. See previous errors

I have MSSQL running in docker using the following tag: mcr.microsoft.com/mssql/server:2017-latest

I have run the command directly against the database with the following errors:

> Msg 1785, Level 16, State 0, Line 1
> Introducing FOREIGN KEY constraint 'directus_fields_group_foreign' on table 'directus_fields' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.
>
>Msg 1750, Level 16, State 1, Line 1
>Could not create constraint or index. See previous errors.

**Comment by mdmazzotti** [comment]
I'm experiencing the same issue when trying to install directus using MSSQL

**Comment by legendaryaman** [comment]
Got the similar error.

`Something went wrong while seeding the database:`

`[ECONNREFUSED] connect ECONNREFUSED 127.0.0.1:5432`

**Comment by Helder-Hernandez** [comment]
I also get the same error when trying to create a directus project with sql server and when seeding the database the error occurs (attached capture)

![image](https://user-images.githubusercontent.com/47677287/102302764-522aba00-3f1f-11eb-819d-8f4b20539803.png)

**Comment by nsteinfeld** [comment]
Still get similar error when using 
`npx directus bootstrap`
Do I need to open a new Issue?

**Comment by rijkvanzanten** [comment]
@nsteinfeld yes, and please include what DB + version 👍🏻
