### ISSUE TITLE
Add file upload to wysiwyg interface

### ISSUE THREAD

**Issue by jooola** [directus/directus#3160]
Currently the WYSIWYG editor don't handle file upload.

The TinyMCE editor is capable of handling file upload while inserting a media. But the Directus app is missing the [file upload handler function](https://www.tiny.cloud/docs/general-configuration-guide/upload-images/#images_upload_handler). I was wondering whether tinymce should handle this or the directus app ?

Anyone already though/worked on this ?

**Comment by benhaynes** [comment]
I thought this has been added into v9 already... if not, this is a priority feature to get included. We're pretty swamped with getting the rest of the v9 ecosystem launched, so any PRs would be welcome!

**Comment by danieljwestman** [comment]
Nope, its not possible to upload files/images in the wysiwyg. Would be a great enhancement, not to be forced to copy-paste an asset url as source. Also to be able to choose in which root folder uploaded files will end up.

**Comment by jooola** [comment]
@rijkvanzanten Any chances that a cherry pick from v8 work ?

**Comment by dimitrov-adrian** [comment]
Sounds good option, but I am a bit unsure about the behaviour.

If I drag&drop a file, for example image, what URL it will produce for the img source, asset or file URI, and if asset which one? Also if I D&D for a some non image file, will it produce a link (anchor)?

It will be handy if the image and media plugins support file picker (this used for file interface) next to source field.

**Comment by naif51191** [comment]
> I thought this has been added into v9 already... if not, this is a priority feature to get included. We're pretty swamped with getting the rest of the v9 ecosystem launched, so any PRs would be welcome!


function example_image_upload_handler (blobInfo, success, failure, progress) {
  var xhr, formData;

  xhr = new XMLHttpRequest();
  xhr.withCredentials = false;
  xhr.open('POST', 'postAcceptor.php');

  xhr.upload.onprogress = function (e) {
    progress(e.loaded / e.total * 100);
  };

  xhr.onload = function() {
    var json;

    if (xhr.status === 403) {
      failure('HTTP Error: ' + xhr.status, { remove: true });
      return;
    }

    if (xhr.status < 200 || xhr.status >= 300) {
      failure('HTTP Error: ' + xhr.status);
      return;
    }

    json = JSON.parse(xhr.responseText);

    if (!json || typeof json.location != 'string') {
      failure('Invalid JSON: ' + xhr.responseText);
      return;
    }

    success(json.location);
  };

  xhr.onerror = function () {
    failure('Image upload failed due to a XHR Transport error. Code: ' + xhr.status);
  };

  formData = new FormData();
  formData.append('file', blobInfo.blob(), blobInfo.filename());

  xhr.send(formData);
};

tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  images_upload_handler: example_image_upload_handler
});

**Comment by seanmars** [comment]
Is there way to pick image file from uploaded file?

**Comment by rijkvanzanten** [comment]
Added in https://github.com/directus/directus/pull/3263
