### ISSUE TITLE
Required value is not enforced on a field

### ISSUE THREAD

**Issue by patvong** [directus/directus#3163]
**Steps to reproduce**
* Configure a field with `Required value` enabled
* Create a new item and omit any values for that field
* Save the item

**Actual Behavior**
The item is created successfully.

**Expected Behavior**
The UI should block the item creation.

**Environment**
Version: v9.0.0-rc.17
Database: Postgresql

**Comment by MiniDigger** [comment]
Required maps to null on the db. If you have a string field and don't enter anything, it's not null, it's empty, that why directus let's you proceed with saving. 
There was an discussion about this in discord before, this is intentional. You would enforce your requirement via rules.

**Comment by Fusseldieb** [comment]
@patvong Snippet from discord:

> Rijk:
> You're saving an empty string which is technically not nothing
> You can add _nempty to your permissions to check for empty strings as well
>
> Rijk:
> Required == not nullable in the DB
> That way we can maintain the DB mirroring approach in the required state
> That's also why we added the additional _nempty filter (next to _nnull) in validation so you can still mimick the "old" required flow

It's intentional. It doesn't work like v8.
