### ISSUE TITLE
PostgreSQL - Support for other schemas (not only public)

### ISSUE THREAD

**Issue by eklam** [directus/directus#3164]
Hi, I'm testing Directus for the first time.

I just hooked it up to my PostgreSQL database but Directus only lists my tables under the public schema on the collections page.

I couldn't find anything on how to setup other schemas... Is it currently supported?

**Comment by benhaynes** [comment]
I don't believe so, to get proper database abstraction across all vendors we need to focus support on those features that are also shared across all vendors. There has been interest in adding support for other postgres schemas, but that's not likely to be implemented soon unless we get a pull request or it becomes sponsored.
