### ISSUE TITLE
Allow configuring connection pool size

### ISSUE THREAD

**Issue by msravi16** [directus/directus#3165]
I tried to install directus9 with pgsql database and getting "error: too many connections for role"
I had faced the same issue with other CMS, after the decreasing default pool size from 10 to 3 solved the problem.
How will I decrease the pool size to 3, I could not see any configuration for this.

Could you please help me to achieve this.

**Comment by rijkvanzanten** [comment]
What server environment is this on? Directus doesn't support setting the connection pool size (yet), but a maximum amount of 3 feels fairly small 🤔

**Comment by msravi16** [comment]
Yes, pool size 3 is very small, for evaluation purpose i used shared PGSQL where the max pool limit is 3.
Thats when I got this error.

Good to see my issue is marked as improvement.
