### ISSUE TITLE
Img File-Type doesn't work in rc17

### ISSUE THREAD

**Issue by TorbenHammes** [directus/directus#3166]
Hey there, fyi in rc 17 the file tye Single File doesn't work correctly. I can't create this filetype in a collection

---

### Project details
Directus Version: 9.0.0-rc.17
Environment: production
OS: macOS Big Sur (11)
Node: 12.18.4

**Comment by rijkvanzanten** [comment]
Doesn't work correctly how? Any errors in creating the field? fyi, in rc 17 it seems to work as expected:

![CleanShot 2020-11-23 at 09 35 08](https://user-images.githubusercontent.com/9141017/99974792-6c81d580-2d6f-11eb-8cae-1e224e65d058.png)

![CleanShot 2020-11-23 at 09 36 45](https://user-images.githubusercontent.com/9141017/99974801-6ee42f80-2d6f-11eb-96b0-1026b53369fb.png)

**Comment by TorbenHammes** [comment]
I created Directus with ``yarn create directus-project project-name``. When I start Directus then, the blue field above the name is kept. So I cannot save the file type. Should I use the Git Repo instead? 

![Bildschirmfoto 2020-11-23 um 20 11 20](https://user-images.githubusercontent.com/12980389/100004681-2311a480-2dc8-11eb-9a9d-4048cacaa766.png)

**Comment by rijkvanzanten** [comment]
I'm not sure what you mean by "the blue field above the name is kept" 🤔 

What's wrong in the provided screenshot? Can't you go to the next page and finish setting up the field?

**Comment by TorbenHammes** [comment]
Oh sorry, now it works 🥳  the first time the arrow in the upper right corner was greyed out. The blue field does not matter. I had the wrong idea.

Thank you for your time, and good luck. I am curious what's new. 😄

**Comment by rijkvanzanten** [comment]
Glad to hear it worked out, you got me worried there for a second 🙂

**Comment by TorbenHammes** [comment]
And again it doesn't work 🙈  I don't know what's the reason for that. Do I have to do something special for adding the image file type?

![Bildschirmfoto 2020-11-23 um 20 46 18](https://user-images.githubusercontent.com/12980389/100007863-fa3fde00-2dcc-11eb-922a-1ebe31c3a3aa.png)

**Comment by rijkvanzanten** [comment]
hmm weird. Do you have an accurate way of reproducing it? Eg does it happen every time? Or only when.........?

**Comment by TorbenHammes** [comment]
I don't know. This is a new instance of directus. On the first instance it did not work even after several reboots. Here it worked with one collection and this time it didn't work again. The collection it worked for was named the same as the new one.

And I'd like to mention: The user list doesn't load for me either, but I can open a new ticket for that.

**Comment by TorbenHammes** [comment]
maybe it works if I add the image file type at the beginning and afterwards other collection types?! I will try it

**Comment by TorbenHammes** [comment]
Sometimes I get this error in the console: Transaction was implicitly committed, do not mix transactions and DDL with MySQL
