### ISSUE TITLE
Review colored dot display in cards layout

### ISSUE THREAD

**Issue by jfavlam** [directus/directus#3171]
![color-card](https://user-images.githubusercontent.com/1150632/100002199-84d00f80-2dc4-11eb-8736-410efb261353.png)

By using the cards layout, the display of colored dots (from a "color" property) are cropped as showed above.    
Expected behavior could be to have those dots inline (like current status dots).

**Comment by rijkvanzanten** [comment]
I actually believe it's because that rendered piece of text before it isn't inline 🤔

**Comment by jfavlam** [comment]
Seems the text (for "name" property in capture above) is already an inline span, but div.color-dot isn't. I believe that updating div.render-template to flex may solve all that...

**Comment by rijkvanzanten** [comment]
This was fixed in https://github.com/directus/directus/commit/1f96d89646a53448d12402f9b7f85f29bee33c9a#diff-392d692d9ed33a36ef86003197851d826b3f07413f9fd85ae67383028d28a75fL53
