### ISSUE TITLE
Incorect pagination

### ISSUE THREAD

**Issue by botzill** [directus/directus#3176]
Currently, if I set 25 items per page, I get this number of items:

<img width="232" alt="Screen Shot 2020-11-24 at 04 19 31" src="https://user-images.githubusercontent.com/4686040/100038380-8e7d6580-2e0c-11eb-9340-43bf4d6d6980.png">

after some pages it just shows this:

<img width="913" alt="Screen Shot 2020-11-24 at 04 22 29" src="https://user-images.githubusercontent.com/4686040/100038506-abb23400-2e0c-11eb-92f8-085a58413364.png">

If I set items per page to 250, it shows the correct number:

<img width="171" alt="Screen Shot 2020-11-24 at 04 23 29" src="https://user-images.githubusercontent.com/4686040/100038699-d7351e80-2e0c-11eb-9c7a-66f1257c4c3b.png">

**Comment by rijkvanzanten** [comment]
@botzill Does this happen after a refresh on the same page too? I found a bug where it doesn't properly reset the counts when switching between collections, so my working theory is that you have a collection that has 1,189 items after which you switched to another one that doesn't at which point you saw this issue. Is that correct?

**Comment by rijkvanzanten** [comment]
If that's not it, can you let me know how I can reproduce this on my end? I just tried it with a collection with 246 items in it, and don't seem to be able to reproduce it.

**Comment by benhaynes** [comment]
Just pinging here to see if anyone can reproduce this. We'll give it one more shot on our side, but if we can replicate the issue we'll close this ticket.

**Comment by rijkvanzanten** [comment]
I'll close this for now. Lemme know if you still run into it @botzill 👍🏻
