### ISSUE TITLE
API returns 500 instead of 409 when unique constraint is violated

### ISSUE THREAD

**Issue by patvong** [directus/directus#3185]
**Steps to reproduce**
* Configure a collection with a unique constraint on one of the field
```
CREATE UNIQUE INDEX index_name ON table_name(column_name);
```
* Create two items with the same field value

**Actual behavior**
A 500 error is returned and no hints on the UI why it failed:
```
{
  "errors": [
    {
      "message": "insert into \"collection_name\" (\"date_created\", \"field_name\", \"user_created\") values ($1, $2, $3) - duplicate key value violates unique constraint \"collection_name_idx_field_name\"",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

```

**Expected behavior**
On DIrectus v8 a 409 error would be returned and a notification is shown on the UI.
The same should happen on v9.

### Project details
Directus Version: 9.0.0-rc.17
Environment: production
OS: Linux 5.4.39-linuxkit
Node: 14.15.1
Database: Postgresql

**Comment by rijkvanzanten** [comment]
Closed in favor of #2944
