### ISSUE TITLE
Build API to `lib` instead of `dist`

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#3189]
Makes importing things like types a little nicer:

```ts
import { HookRegisterFunction } from 'directus/lib/types';
```

**Comment by danieljwestman** [comment]
@rijkvanzanten Why would that be nicer? 🤔

**Comment by rijkvanzanten** [comment]
@danieljwestman Reads a little cleaner when importing parts of the Directus library, purely personal preference!

There is never going to be a `src` included through `npm`, so the name `dist` doesn't really make sense in this context. npm doesn't allow you to set a "root" directory, so we'll always have to have the built files in some folder 🤔 

Ideally, it would be `directus/types` instead of `directus/<something>/types`, but that seems to be out of the question for now

**Comment by rijkvanzanten** [comment]
Instead, we'll focus on exposing the types through a root `index.d.ts` on distribution, instead of renaming dist->lib
