### ISSUE TITLE
Filtering permission by $CURRENT_ROLE not working

### ISSUE THREAD

**Issue by metalmarco** [directus/directus#3198]
If I setup a custom Item Permission based on $CURRENT_ROLE, the data returned is always empty.

Example permission: 

```
{
    "directus_roles_id": {
        "_in": "$CURRENT_ROLE"
    }
}

```
Returns

```
{
    "data": []
}

```

If I edit the permission specifying the ID of the role, it works:

```
{
    "directus_roles_id": {
        "_in": "f6b147d2-132b-4045-bffa-7710364b8de6"
    }
}

```
Returns:

```
{
    "data": [
        {
            "id": 3,
            "web_menuitems_id": 2,
            "directus_roles_id": "f6b147d2-132b-4045-bffa-7710364b8de6"
        },
        {
            "id": 10,
            "web_menuitems_id": 3,
            "directus_roles_id": "f6b147d2-132b-4045-bffa-7710364b8de6"
        }
    ]
}
```

---

### Project details
Directus Version: 9.0.0-rc.17
Environment: production
OS: Linux 5.4.0-1029-aws
Node: 14.15.1

**Comment by danieljwestman** [comment]
I'm not sure, but shouldn't you use `_eq` instead of `_in` in this case?

**Comment by metalmarco** [comment]
You are right, I was trying to simplify an example which was filtering a M2M relation.

In any case, it doesn't work with either _eq nor _in

**Comment by rijkvanzanten** [comment]
@metalmarco What's the request you do to get this data?

**Comment by rijkvanzanten** [comment]
If I setup the permissions like you mentioned in the OP, it works as expected on my end 👍

**Comment by metalmarco** [comment]
I don't know what to say, but it works now.
I'm sorry, I thought I tested it a lot before opening the issue.
