### ISSUE TITLE
Title not translating - Showing raw JSON

### ISSUE THREAD

**Issue by Fusseldieb** [directus/directus#3210]
When a title isn't translated, it shows up as raw JSON, which is the case of German and Portuguese, at least:

![image](https://user-images.githubusercontent.com/4715129/100355404-748c8000-2fd0-11eb-8fae-07322589d72d.png)

This above happens when looking in a collection.

In English this does not happen

**Comment by rijkvanzanten** [comment]
This is a known problem for most languages.. We haven't updated our locales provider yet, so the languages are out of date.

Closed in favor of https://github.com/directus/directus/issues/2962
