### ISSUE TITLE
Directus 9 - pino-colada outputs gibberish on Windows 10

### ISSUE THREAD

**Issue by lescinskiscom** [directus/directus#3217]
```
13:58:56 Γ£¿ Server started at port 8055
```

Consider allowing users to use a different pino prettifier, such as pino-pretty, similar to how you allow users to select database connectors.

Maybe something like
`
LOG_PINO_PRETTIFIER=pino-pretty
`

and have users install it on their own.

**Comment by benhaynes** [comment]
I believe those characters are the emoji, not sure why they don't render on Windows.
