### ISSUE TITLE
Directus 9 - Cannot read property 'knex' of undefined

### ISSUE THREAD

**Issue by iamvaliyev** [directus/directus#3218]
When create custom endpoint and init ItemsService i get this error: **Cannot read property 'knex' of undefined**

**Comment by metalmarco** [comment]
I had the same problem, the sample code on the docs didn't work.
After a lot of trial and errors, I got it working.

You have to declare your service passing the schema and the accountability.
`const worklife_purchase_orders = new ItemsService("worklife_purchase_orders", {schema: req.schema, accountability: req.accountability});
`
If you don't pass the accountability, then the permissions won't work (i.e. any user can perform any action).

Keep in mind I'm new to node.js, so the answer may be incorrect.

**Comment by iamvaliyev** [comment]
> Keep in mind I'm new to node.js, so the answer may be incorrect.

Me too, thanks I'll go check))

**Comment by ilamarche** [comment]
> `const myTableService = new ItemsService("mytable", {schema: req.schema, accountability: req.accountability}); `

I have got this error

(node:29249) UnhandledPromiseRejectionWarning: Error: fields.splice is not a function

`    router.get('/', (req, res) => {
        const recipeService = new ItemsService('quiz_response', {schema: req.schema, accountability: req.accountability});
        recipeService.readByQuery({fields: '*'})
            .then(results => res.json(results))
            .catch(error => {
                throw new ServiceUnavailableException(error.message)
            });
    });`

**Comment by metalmarco** [comment]
`{fields: ['*']}`

**Comment by ilamarche** [comment]
> `{fields: ['*']}`

Thanks you it's work fine

**Comment by Kematia** [comment]
Is there a more elegant way to fix this? Having to declare the service for every endpoint (seeing you have to provide the schema and accountability from the request) is a bit ugly... also TS complains a lot :P 
![image](https://user-images.githubusercontent.com/17851386/101327578-2b112000-386f-11eb-9c65-6cd0c1fac86f.png)

**Comment by rijkvanzanten** [comment]
@Kematia Feel free to [open a discussion](https://github.com/directus/directus/discussions/new) outlining how you think it should work 🙂

**Comment by Kematia** [comment]
Eheh way above my paygrade for now 😄  I thought I was using it incorrectly but from digging in the api source code you guys do the same 😃  

How do you deal with the schema and accountability properties type safety? Should I use another interface for the request and response arguments?

**Comment by rijkvanzanten** [comment]
I'm extending Express in here; there must be a way to pull that in right? 🤔 

https://github.com/directus/directus/blob/main/api/src/types/express.d.ts

**Comment by Kematia** [comment]
mhhh seems to be missing in my node_module package
![image](https://user-images.githubusercontent.com/17851386/101363377-9ffd4d80-38a1-11eb-91d9-2cf374248007.png)

path is: /node_modules/directus/dist/types

**Comment by Kematia** [comment]
![image](https://user-images.githubusercontent.com/17851386/101466137-13a26780-3941-11eb-94bc-7858338c034e.png)

I redeclared it manually, it seems to be working for now!
