### ISSUE TITLE
Missing primary key error if Postgres database contains any views

### ISSUE THREAD

**Issue by samuliasmala** [directus/directus#3229]
If Postgres database contains any views `/server/info` endpoint returns `503 Service Unavailable` with error message "_Collection "test_view" doesn't have a primary key column_" when trying to log in.

Postgres database views cannot have primary keys so I see two options to solve this:
1. Exclude views
2. Relax the primary key requirement

What would be the preferred approach? Is it possible to use views for collections in e.g. MySQL?

**Comment by rijkvanzanten** [comment]
We can't really relax the primary key requirement, as Directus heavily relies on primary keys in routing/relations/internal logic.

That being said, I think the first step is to exclude views, so we at least don't break when the user has views setup in the database, and then secondly, start supporting views "natively" down the road 👍

**Comment by samuliasmala** [comment]
Ok! I will create a PR to exclude views when using Postgres.
