### ISSUE TITLE
Translations interface broken on v9.0.0-rc19

### ISSUE THREAD

**Issue by Jonesus** [directus/directus#3230]
Reproduction:
1. Create a new project with a clean database
2. Log in to admin UI
3. Create a new collection with a translations field (we'll call it `Movies`)
4. Create a new field in the translations collection (a simple text interface works, we'll call it `Title`)
5. Try to create a new item into `Movies`
6. the Title-field doesn't show the usual list of languages, instead a singular text input field is shown regardless of the `Title`'s interface type

While I was trying to confirm that this actually worked on `v9.0.0-rc18` I noticed that if you create a project with API from `rc18` but then use `npx directus start` so that a `rc19` app connects to the old backend, everything works as it should including new features from `rc19` (m2a), so it would seem that the cause of this problem is not in the app's code but the api's

**Comment by AlexisWalravens** [comment]
I have the same issue.

**Comment by AlexisWalravens** [comment]
Seems that the interface is not set in the directus_fields table
  
![image](https://user-images.githubusercontent.com/1764824/100516061-4ef2a880-3181-11eb-96b9-990b5911c3c0.png)


Setting it to `translations` fixes the issue.

**Comment by rijkvanzanten** [comment]
Fixed in dacdce677
