### ISSUE TITLE
Allow adding/removing collections from M2A relationship config

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/directus#3231]
I took a look into the M2A builder and it is pretty nice. Thank you for the great work. 

Never the less I already found some things which should be improved. 

1. The Builder should have a sorting possibility
2. You cannot add a new collection once you created a m2a field

**Comment by benhaynes** [comment]
I think Rijk added sorting, you just need to have a `sort` column set on the junction collection. #2 might be a bug...

**Comment by danieljwestman** [comment]
Yes, being able to change (both add and remove) collections/relations within the m2a interface is an important aspect of a "page builder" experience. 
In most cases you'll build more types of "content blocks" (collections) over time, and you'll want to add these to the builder (m2a interface). I had this discussion with @rijkvanzanten in Discord a couple of days ago.

**Comment by rijkvanzanten** [comment]
> (both add and remove)

This _and remove_ is the tricky bit. We'll have to make sure that you don't have any of the about-to-be-removed collections in use

**Comment by MichaelNussbaumerGOWEST** [comment]
@rijkvanzanten how is it handled when you delete a collection which is in use by M2A? Should follow a similar logic.

**Comment by sensedrive** [comment]
@MichaelNussbaumerGOWEST

> 2. You cannot add a new collection once you created a m2a field

It is possible to add new collections by editing the corresponding directus_relations field in the database. Anyway I would not suggest to delete it this way, in order to prevent errors in the app.

**Comment by benhaynes** [comment]
Just ran into this — I know it's tricky to _remove_ tables from the allow-list, but we definitely need to support adding new ones. I'll do it in the DB directly for now.
