### ISSUE TITLE
Duplicate field with unwanted characters 

### ISSUE THREAD

**Issue by juancarlosjr97** [directus/directus#3237]
**Environment:**

* Directus rc.19

**Step to reproduce**

* Click on duplicate a field and allow to add `/` and any other characters. e.g,. `test_new_field/test` and that makes the page to redirect to `https://directus-example.local/admin/settings/data-model/test_collection/test_new_field/collection`.

Adding spaces makes the creation of the new duplicate field to fail, but adding a `/`

**Comment by juancarlosjr97** [comment]
I tried to do it on my own as a PR, I found the field and everything, but I got confused how to do it to replace using the structure, so I am creating the issue instead :(

**Comment by dimitrov-adrian** [comment]
The field is not the problem, I had made a PR that add db-safe attribute as in other places where db naming is used.

What I am thinking is that the API itself doesn't seems to make validations and it's possible to use "some.field" which will be resolved as <table>.<column> or even worst using ` (tilde) in names.

**Comment by benhaynes** [comment]
We should probably strip those characters out when using the App, and throw an error if using them directly in the API.

**Comment by juancarlosjr97** [comment]
Exactly my idea @benhaynes but I failed doing that :(...

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/directus/pull/3238
