### ISSUE TITLE
Duplicating a field doesn't duplicate relations

### ISSUE THREAD

**Issue by flayks** [directus/directus#3239]
I tried to duplicate an image field from a collection to another, and I noticed that on the duplicated field, I can't access `id`, `title`, `width` or `height` (or any field actually) using GraphQL.  
GraphiQL doesn't even give me the available options, just the field with the id of the image.

An okay workaround I found is to create a new image field on the collection instead of duplicating it, but it's not ideal especially if we have to use it often on different collections.

Using v9-rc19 and MySQL

**Comment by josias-r** [comment]
@rijkvanzanten I would love to know how you solved this when you got a solution.
I'm setting up a cronjob that duplicates entries with an M2M relationship. If you find some automated way of duplicating in a recursive matter, I'd like to take a look at that 😄

**Comment by rijkvanzanten** [comment]
@josias-r I most likely will search through all relations to find the matching relations for the current field, and swap out the "old" name for the "new" name and save those as new records 👍
