### ISSUE TITLE
Readme missclick

### ISSUE THREAD

**Issue by Meldiron** [directus/directus#3244]
On https://github.com/directus/directus/tree/main/app/src/components/v-card the readme says:
![image](https://user-images.githubusercontent.com/19310830/100600735-fac30200-3301-11eb-83d2-e7843514a31e.png)

`</v-card-test>`should be `</v-card-text>`

Simple issue but I am not good with pull requests so I just open an issue.

**Comment by Meldiron** [comment]
Also, there is `<v-card-actions>` 2 times, one of them should be closing `</v-card-actions>`

**Comment by benhaynes** [comment]
I think you're right @Meldiron — but I'll defer to @rijkvanzanten on this one...

**Comment by rijkvanzanten** [comment]
Thanks @Meldiron!

GitHub has a handy inline-editor for these kinds of fixes 🙂 

![CleanShot 2020-11-30 at 10 04 24](https://user-images.githubusercontent.com/9141017/100626184-7cf7fa00-32f3-11eb-8098-e0d784504421.png)
