### ISSUE TITLE
Error: Collection "pg_stat_statements" doesn't have a primary key column 

### ISSUE THREAD

**Issue by euvs** [directus/directus#3251]
Followed instructions as per the doc
1. `npx create-directus-project my-project`
2. Configure Postgress
3. `npx directus start`

Result:

`http://localhost:8055/admin` returns a blank screen.

`http://localhost:8055/server/info` endpoint returns the following error

```
{
    errors: [
        {
            message: "Collection "pg_stat_statements" doesn't have a primary key column",
            extensions: {
                service: "database",
                table: "pg_stat_statements",
                code: "SERVICE_UNAVAILABLE"
            }
        }
    ]
}
```

Note, `pg_stat_statements` extension is installed.

Any suggestions how to fix this?

**Comment by disfasia** [comment]
Happened to me as well when trying to check Directus behavior when new tables are added externally (IE: command line) 
I created a simple table, with only one int column - no primary key.
