### ISSUE TITLE
Datetime interface doesn't show currently selected value in a relation

### ISSUE THREAD

**Issue by MiniDigger** [directus/directus#3252]
Similar to #3137 

![image](https://user-images.githubusercontent.com/2185527/100729140-afbff200-33c8-11eb-976c-29e3f526815c.png)

if you set it in that view, it stays selected in the display, but if you save the view and open it again, the display and the interface are empty again.

this is a one to many relation, but I would assume this is true for all of them.

rc.19

**Comment by rijkvanzanten** [comment]
I'm wondering if this is caused by the same as https://github.com/directus/directus/issues/3137
