### ISSUE TITLE
CLI getting stuck when using Redis for cache

### ISSUE THREAD

**Issue by WoLfulus** [directus/directus#3256]
CLI commands seems to be getting stuck for some reason, making it impossible to automate stuff.

`directus roles create ...` for example creates the role but the command never exists.

Already happening on on `rc.13`, versions < `rc.13` raises a knex error

**Comment by rijkvanzanten** [comment]
What environment is this under?

**Comment by WoLfulus** [comment]
- Docker 
- PG 12.1
- Redis 6

**Comment by rijkvanzanten** [comment]
Can you try it without the redis connection?

**Comment by WoLfulus** [comment]
It's what I'm trying right now. Which RC we did the constructor fix?

**Comment by rijkvanzanten** [comment]
Around that time you mentioned (6-7-8 ish)

**Comment by WoLfulus** [comment]
`.19` works with redis disabled :(

seems to be related somehow, weird thing is that the redis is configured properly

**Comment by rijkvanzanten** [comment]
Most definitely because keyv-redis keeps the connection alive. The CLI already closes the database connection once it's done inserting the role (/user), but we don't actively close the redis connection(s) 👍

**Comment by WoLfulus** [comment]
that makes sense. can we force a process.exit in cli for all cases? if it's on the "bootstrap" functions it allows for programatically invoking cli commands too (needed that yesterday but had to workaround with `cross-spawn` instead)

**Comment by rijkvanzanten** [comment]
Lets see if we can cleanly close the connection first and let the process exist naturally before yanking it with a process.exit call manually 👍
