### ISSUE TITLE
M2M relations can only be deleted by users with admin rights

### ISSUE THREAD

**Issue by JLueke** [directus/directus#3265]
Only users with admin rights can remove entries from M2M junction tables.
The "x" buttons to delete the entries from the M2M junction table are only visible for the admin user.
I don't know if it's only a frontend UI problem or involves the backend, too.

Tested with official Docker Image v9.0.0-rc.17 and v9.0.0-rc.19.

DB Dump with minimal example data (directus tables + collection foo, bar and junction table bar_foo):
[dump-main-20201202-12-20.zip](https://github.com/directus/directus/files/5629528/dump-main-20201202-12-20.zip)

Admin:
admin@example.com
password

User with full permissions to collections foo, bar and junction table bar_foo, but not admin:
john@example.com
password

**Comment by benhaynes** [comment]
Thanks @JLueke — this seems like a permissions config issue, but we'll check it out. Also, I'm so impressed that you provided a dump and creds in the ticket... that really helps us debug faster!! 👍

**Comment by rijkvanzanten** [comment]
The dump doesn't contain the actual m2m interface configured unfortunately ^^

**Comment by JLueke** [comment]
> The dump doesn't contain the actual m2m interface, nor permissions configured unfortunately ^^

It does contain everything, I just tested it, but unfortunately the JSON was exported as binary.

I got error messages while importing.
The import only worked after [fixing the dump](https://stackoverflow.com/a/42029919).

Next time I'll test the import beforehand.

**Comment by rijkvanzanten** [comment]
@JLueke  No problem! Luckily it was easy enough to reproduce the issue by setting up a m2m interface from scratch 🙂

**Comment by Damras610** [comment]
Hello @rijkvanzanten , is it possible to reopen the issue as the problem is not fixed, is it ?
I created #3389 (duplicate of this issue as well).

PS : happy new year :)
