### ISSUE TITLE
Installation with Oracle DB Error

### ISSUE THREAD

**Issue by yapnel** [directus/directus#3266]
Nodejs version of Directus i'm installing.

When setting up the connection to the Oracle database during the installation process, it is throwing the error below even though i have supplied the correct database configurations (tested on sqldeveloper). 

Something went wrong while seeding the database:
undefined ORA-12170: TNS:Connect timeout occurred

1) How do i go about troubleshooting this issue please?
2) I notice in the questions, nothing is asked about the service name or SID

Thanks

**Comment by rijkvanzanten** [comment]
We're still actively working on wrapping up support for MS SQL and Oracle, so it could be that we missed something here 🙂

**Comment by yapnel** [comment]
Digging into knex to understand how connection is established for oracle, it is using the below string

client.connectionSettings.host + '/' + client.connectionSettings.database


So, if you have non default port, it has to be specified as part of the host variable as hostname:port 

The database value is the service name of the oracle database. Suggest add this do the directus documentation

**Comment by rijkvanzanten** [comment]
This is happening in Knex itself you said?

**Comment by yapnel** [comment]
> This is happening in Knex itself you said?

Yes.

https://www.github.com/knex/knex/tree/master/lib%2Fdialects%2Foracledb%2Findex.js

Line 101.

**Comment by rijkvanzanten** [comment]
I'd recommend using `DB_CONNECTION_STRING` in your `.env` instead of the individual for the time being :)

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/knex/knex/pull/4147

**Comment by kibertoad** [comment]
Released in knex 0.21.13
