### ISSUE TITLE
Directus 9 MySQL 8

### ISSUE THREAD

**Issue by josias-r** [directus/directus#3267]
I read somewhere that v9 should support MySQL 8?

I installed the latest v9 version and set-up a MySQL 8 DB.
The first problem I encountered was the DB user password encryption from v8 caused a "client outdated" error or something similar. Then I switched that to legacy encryption. Authentication worked fine but I got a different error during the setup. Some SQL error.

To reproduce just run the npx create directus command and try to connect a MySQL 8 DB.

Is this feature still WIP?

**Comment by rijkvanzanten** [comment]
Directus 9 should run just fine under MySQL 8. The only thing—which you already encountered—is the fact that `mysql` / `knex` under Node don't support MySQL 8's default authentication strategy.

> but I got a different error during the setup. Some SQL error.

What error?

**Comment by josias-r** [comment]
@rijkvanzanten I went and reproduced the error:
```
[UNKNOWN_CODE_PLEASE_REPORT] create table `directus_collections` (`collection` varchar(64), `icon` varchar(30), `note` text, `display_template` varchar(255), `hidden` boolean not null default '0', `singleton` boolean not null default '0', `translations` json, `archive_field` varchar(64), `archive_app_filter` boolean not null default '1', `archive_value` varchar(255), `unarchive_value` varchar(255), `sort_field` varchar(64)) - UNKNOWN_CODE_PLEASE_REPORT: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.
```

**Comment by josias-r** [comment]
.. Im running a Digitalocean cluster with the default configurations

**Comment by rijkvanzanten** [comment]
Ahh right. DigitalOcean's managed MySQL enforces a SQL setting that isn't compatible with `knex` (the DB abstraction we use) see https://github.com/knex/knex/issues/4141#issue-752526907 :/

I'd recommend using managed Postgres on DO instead, that doesn't have this issue

**Comment by josias-r** [comment]
I actually thought of that too and tried out Postgres 12 as well, but with postgres I got a knex error too, I think it was a timeout :/

**Comment by rijkvanzanten** [comment]
That sounds more like a configuration issue (eg wrong hostname/user/password/port/certificate etc) than a bug 🤔

**Comment by josias-r** [comment]
I tried entering the credentials multiple times. But let me try it again and show you the exact error I got if I get it again 😄

**Comment by rijkvanzanten** [comment]
Is this when using a regular Droplet, or in App Platform? DigitalOcean requires the use of SSL when connecting to the DB, so you might either have to set `NODE_TLS_REJECT_UNAUTHORIZED` to `0`, or pass the CA certificate to Directus by using `DB_SSL__CA` = `-----BEGI.......`

**Comment by josias-r** [comment]
@rijkvanzanten Okay I don't get that timeout error I got last time and yes now I have problems with the SSL.
SSL disabled error: `[28000] no pg_hba.conf entry for host "myip", user "testuser", database "testdb", SSL off`
SSL enabled error: [SELF_SIGNED_CERT_IN_CHAIN] self signed certificate in certificate chain

I'm not used to working with postgresql. I have a regular Database cluster. Can you point me to where I can go generate the SSL CA which I need?

**Comment by rijkvanzanten** [comment]
You can download it from DO directly:

![CleanShot 2020-12-02 at 12 41 03](https://user-images.githubusercontent.com/9141017/100910310-ca16d000-349b-11eb-9bfc-c0f5b5496b92.png)

**Comment by josias-r** [comment]
Awesome thanks, finally got it running 🥳 
What would be the alternative to NODE_TLS_REJECT_UNAUTHORIZED?
I tried setting DB_SSL_CA (its DB_SSL_CA not DB_SSL__CA, right?) but that did not seem to work. Though I'm not sure if it only didn't work because the init command didn't read the env file?

Thanks for helping out!

**Comment by rijkvanzanten** [comment]
> What would be the alternative to NODE_TLS_REJECT_UNAUTHORIZED?

If the CA is passed on correctly, you don't need the above, as it will pass the authorization.

It's `DB_SSL__CA` (double underscore)! And you're right, the `init` command actually creates the env file, so it doesn't read that.. I don't want to add too many extra questions into init, as it's already getting pretty long, but lets think of a way to pass on the CA during init 🤔

**Comment by josias-r** [comment]
Maybe make the question conditional so it only appears when SSL mode is true.

I would also love to see a way to run `init` which just ready from the `.env` file instead of writing it. This way I could easily set-up multiple databases without having to enter all the values that stay the same every time manually. I.e. running init for a second DB where host/user/password etc stays the same 😄

**Comment by rijkvanzanten** [comment]
There is `directus database install` to fresh install the DB, and then `directus roles create` and `directus users create` to insert roles/users. We're exploring adding a `directus bootstrap` that effectively does the same as init, bar creating the .env file 👍

**Comment by josias-r** [comment]
Awesome! Will, there be programmatic usage for these commands?
I'm thinking of automating the process of creating new installs on an infrastructure that simply calls the DB setup programatically + afterwards [deploys a new app](https://www.digitalocean.com/docs/app-platform/how-to/add-deploy-do-button/)

**Comment by rijkvanzanten** [comment]
Yeah that's exactly what we're looking to support here 🙂 We need a single command that we can run every time the app starts up that either populates / initializes the DB, or runs migrate:latests when it already exists 👍 (cc @WoLfulus)

**Comment by josias-r** [comment]
This is awesome, I already fell in love with this cms after trying out a number of alternatives 🥳

**Comment by josias-r** [comment]
@rijkvanzanten I'm not sure whether the certificate env variable works 🤔
My env setup (a part of it):
<img width="673" alt="Screenshot 2020-12-03 at 11 35 57" src="https://user-images.githubusercontent.com/11424820/100998374-ba5ec080-355b-11eb-98c2-dc8c80ae1f3f.png">
As you can see I point the certificate to the one [provided by digitalocen](https://www.digitalocean.com/docs/app-platform/how-to/use-environment-variables/).

Did I misunderstand something?

**Comment by rijkvanzanten** [comment]
Make sure you provide the others (port, host etc) too if you haven't already
I'm currently running v9 in prod with:

![CleanShot 2020-12-03 at 09 32 37](https://user-images.githubusercontent.com/9141017/101041900-96df4a00-354a-11eb-97d4-7fa65d3872b2.png)

(and `DB_CLIENT` = `pg`)

**Comment by josias-r** [comment]
I have them set too 🤔
My setup works as soon as I add `NODE_TLS_REJECT_UNAUTHORIZED=0` again. (I got`DB_CLIENT` &`DB_SSL` hardcoded)

<img width="667" alt="Screenshot 2020-12-03 at 17 24 22" src="https://user-images.githubusercontent.com/11424820/101057572-7a640180-358c-11eb-9db4-f33948a62c73.png">

**Comment by rijkvanzanten** [comment]
Ohh, hold up, you can't have `DB_SSL` _and_ `DB_SSL__CA` at the same time.. 

(Reason being that this configuration is passed on to node-postgres, which works by nesting the SSL options under the SSL, key, so `DB_SSL` == `{ ssl: true }` and `DB_SSL__CA` = `{ ssl: { ca: '' }}`)

**Comment by josias-r** [comment]
Ooooooooooh... Thanks for the clarification 🙏🏻

**Comment by arladmin** [comment]
Still unable to access DigitalOcean managed MYSQL 8 from docker based Directus (v9.0.0-rc.86), see: 
https://github.com/knex/knex/issues/4141#issuecomment-887230556
