### ISSUE TITLE
Feature: Support DB connection URL ENV inplace of seperate ENV vars

### ISSUE THREAD

**Issue by josias-r** [directus/directus#3280]
I would love to see support for database connection strings like this:
`postgresql://user:password@host:port/database?sslmode=require`

Specific use case is the integration with DigitalOcean Apps where you can connect a database and they will set the `DATABASE_URL` for you.
(Would be cool if this feature would work with the "DATABASE_URL" alias too next to your "DB_" convention, though I guess this alias is easy to set-up for yourself)

This would also be nice to have during the `init` command, where at the first step you could paste the full string for a faster process 😄

... I would love to contribute myself, but I'm currently still getting familiar with the project

**Comment by rijkvanzanten** [comment]
This already exists 🙂 

It's called `DB_CONNECTION_STRING`:

https://github.com/directus/directus/blob/6685391505fc98ae6d591ec87b290ad2f8c7e939/api/src/database/index.ts#L23

**Comment by rijkvanzanten** [comment]
Ref https://github.com/directus/directus/blob/main/docs/reference/environment-variables.md

**Comment by josias-r** [comment]
Awesome!

**Comment by josias-r** [comment]
@rijkvanzanten I'm getting this error using the digital ocean DB_URL :
```
error: no pg_hba.conf entry for host "myhostip", user "mydbuser", database "mydbname", SSL off
```
My setup:
<img width="667" alt="Screenshot 2020-12-04 at 10 21 59" src="https://user-images.githubusercontent.com/11424820/101145819-9910d980-361a-11eb-9e2a-00f523a9f0d0.png">

In the error it says `SSL=off`, but the original DB string says SSL mode `require`, could that be the problem?

**Comment by rijkvanzanten** [comment]
Yep! DO's `DB_CONNECTION_STRING` doesn't actually add `?ssl=true` in the connection string 🙈 

I _think_ you might be able to force it in with `${mydbcluster.DATABASE_URL}&ssl=true` ...

**Comment by josias-r** [comment]
@rijkvanzanten Just tried that, unfortunately, it doesn't work :/ Going to rely on specific env vars for now. I think it doesn't work because the DO string already contains `ssl=require`.

Anyways, not too big of a deal 😄

**Comment by rijkvanzanten** [comment]
Oh that could've changed then! Last time I tried they had `?ssl-mode=require`, but no `ssl` if I recall correctly 🤔  Oh well, individual ones sounds like the way to go! 🙂
