### ISSUE TITLE
Add API Auth Details to Docs

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#3284]
Ref: https://github.com/directus/directus/discussions/3283#discussioncomment-146091

**Comment by lubenard** [comment]
Yes, with examples, it would be great !
This new version seems cool, but suffer a cruel lack of documentation

**Comment by jasonfx13** [comment]
I would love to find some documentation on how to get user data after login, (i.e. email, name, etc...). The login success response only returns tokens and an expiration, and there is no documentation on how to get the user data after login.

**Comment by lubenard** [comment]
Hello ! You can get the users datas using this endpoint: ```/users/me``` as described [here](https://docs.directus.io/reference/api/users.html)

As for the Token returned after Auth, you need to pass it in the header of your request.

Here is how i did  it in JS to get datas about the logged-in user:
```
const headers = {
      "Content-type": "application/json",
      "Authorization": "Bearer " + <Your Auth Token>,
}

let res = await fetch('http://192.168.99.102:8055/users/me', {headers});
let json = await res.json();
```

It return a json response.

Do not forget to configure directus with the right authorizations

**Comment by jasonfx13** [comment]
> Hello ! You can get the users datas using this endpoint: `/users/me` as described [here](https://docs.directus.io/reference/api/users.html)
> 
> As for the Token returned after Auth, you need to pass it in the header of your request.
> 
> Here is how i did it in JS to get datas about the logged-in user:
> 
> ```
> const headers = {
>       "Content-type": "application/json",
>       "Authorization": "Bearer " + <Your Auth Token>,
> }
> 
> let res = await fetch('http://192.168.99.102:8055/users/me', {headers});
> let json = await res.json();
> ```
> 
> It return a json response.
> 
> Do not forget to configure directus with the right authorizations

Awesome, thank you! I must've glazed right over that in the docs!

**Comment by rijkvanzanten** [comment]
This was added in #3951
