### ISSUE TITLE
UI - filter by boolean field can't be unchecked

### ISSUE THREAD

**Issue by botzill** [directus/directus#3289]
I try to filter by boolean field in the UI and I can't uncheck it:

<img width="299" alt="Screen Shot 2020-12-03 at 19 26 54" src="https://user-images.githubusercontent.com/4686040/101065257-9a4ff100-359d-11eb-93b3-1f1b5b7552fe.png">

it always stays checked no matter what I do.

**Comment by rijkvanzanten** [comment]
Fixed in eca57e5be
