### ISSUE TITLE
Add custom page to main route

### ISSUE THREAD

**Issue by iamvaliyev** [directus/directus#3293]
I need to add a landing page to a project how to do it?

**Comment by danieljwestman** [comment]
Tip: check out Discord post by @rijkvanzanten 

https://discord.com/channels/725371605378924594/741330910594465823/781528954121093140

As mentioned this is exeprimental as for now.

**Comment by iamvaliyev** [comment]
> Tip: check out Discord post by @rijkvanzanten
> 
> https://discord.com/channels/725371605378924594/741330910594465823/781528954121093140
> 
> Fun fact (and this is very experimental still, and not documented yet because of that), buuuut:
> 
> The Directus express app is exported in the `directus` package too, so you should be able to add `directus` as an endpoint of another express (compatible) based project!
> 
> So you can do something like
> 
> ```js
> const express = require('express');
> const directus = require('directus/dist/app');
> 
> const app = express()
>   .get('/directus', directus)
>   .get('/', (req, res) => res.render('my-app'))
>   .listen(8080);
> ```

I get error : **Error: Route.get() requires a callback function but got a [object Object]**

**Comment by rijkvanzanten** [comment]
That's where the "So you can do something _like_" part comes in

Seeing we use TS w/ esm exports, you might have to use 

```
const directus = require('directus/dist/app').default;
```

instead, and it's

`express.use('/directus', directus)`, not `.get`
