### ISSUE TITLE
Filtering on self referencing collections leads to errors

### ISSUE THREAD

**Issue by eXaminator** [directus/directus#3294]
Hi,

I'm trying out v9 and ran into some issues with a self referencing collections.

I have a collection (`bsf_pages`) with a O2M reference to itself. I also selected the "mirrored" reference, so the collection as a "parent" and a "children" field.

If I try to add a filter on the collection view for a field on parent (like parent -> title), I get the following error:

```json
{
  "errors": [
    {
      "message": "select \"bsf_pages\".\"title\", \"bsf_pages\".\"status\", \"bsf_pages\".\"navigation\", \"bsf_pages\".\"module\", \"bsf_pages\".\"id\", \"bsf_pages\".\"sort\", \"bsf_pages\".\"parent\" from \"bsf_pages\" left join \"bsf_pages\" on \"bsf_pages\".\"parent\" = \"bsf_pages\".\"id\" where \"bsf_pages\".\"title\" like $1 order by \"sort\" asc limit $2 - table name \"bsf_pages\" specified more than once",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

I get a similar message when trying the same filter via GraphQL. It seems the JOINed table has the same alias as the "base" table.

As a side note: Am I missing something or is it not possible to filter on the pure absence of a referenced field? Basically for "WHERE parent = NULL". Might be helpful, especially since I cant filter for "parent.id = NULL" if I don't want the ID to be visible in the table).

**Comment by rijkvanzanten** [comment]
@eXaminator What DB is this under? 

> Basically for "WHERE parent = NULL".

This is possible using `filter[parent][_null]=true` (/or `filter={"parent": { "_null": true }}`)

**Comment by eXaminator** [comment]
> What DB is this under?

This on a postgres 12 (docker image).

> This is possible using `filter[parent][_null]=true` (/or `filter={"parent": { "_null": true }}`)

Where do I set that? I was doing this via the "Advanced Filter" UI on the right side of the Collection table / Preset. Also graphql doesn't know the "_null" filter:

`bsf_pages(filter:{parent: {_null:true}}) { ... }`

`{"errors":[{"message":"Field \"_null\" is not defined by type \"bsf_pages_filter\".","locations":[{"line":3,"column":46}]}]}`
