### ISSUE TITLE
feature: custom fields for file data model 

### ISSUE THREAD

**Issue by TheOneAndOnlyGarcia** [directus/directus#3295]
it would be nice if we could add fields to the file date model. we're using a lot of licensed images that need to display copyright information or other information. yes, with references it is possible, but it would be much more comfortable if we could add optional fields to the file data model directly, like location info.

**Comment by rijkvanzanten** [comment]
Heya! You can go into settings > data model and select "System Collections" in the right sidebar filter to add any new fields to the system collections 👍
