### ISSUE TITLE
Discard changes modal does not get closed

### ISSUE THREAD

**Issue by lluishi93** [directus/directus#3300]
Create collection A.
Create M2A field and associate some collections.
Add an item to the relation.
Disable the item.
Select another collection from the sidebar.
Click discard.
Check that the modal is still opn.

![image](https://user-images.githubusercontent.com/14786440/101141879-2f420100-3615-11eb-887f-310e4c95125e.png)

**Comment by benhaynes** [comment]
Thanks for reporting this! Question: Could you clarify what you mean by "Disable the item"?

**Comment by lluishi93** [comment]
Probably I meant to unselect or unrelate the item from collection b from collection a in the m2m field.

**Comment by benhaynes** [comment]
Ahh, so deleting the item from the relational field? Is it an M2M or an M2A? Or does that matter?

**Comment by benhaynes** [comment]
Hey @lluishi93 — do you remember if this was a M2M or M2A? It will help us in debugging and closing... 🙂

**Comment by lluishi93** [comment]
@benhaynes M2A

**Comment by Nitwel** [comment]
I tried to reproduce this but couldn't get it to not work. Could you try to be even more precice on how to reproduce this?
Did this happen to you just once or does this occur every time you try it?

**Comment by Nitwel** [comment]
Please reopen this issues if it still still a problem and / or you encounter this bug again.
If so, please add even more steps on how to reproduce this or even a DB dump would be very helpful.
