### ISSUE TITLE
Speed up MySQL information_schema read

### ISSUE THREAD

**Issue by jsthind** [directus/directus#3301]
I did a fresh installation using on my computer (running Ubuntu 20)

`npx create-directus-project my-project`

Selected MySQL for the database. The MySQL server is running on an HP1 Proliant server on the LAN. Tried to login, the login seems to work fine but the http://127.0.0.1:8055/admin/collections page times out. 

See screenshot:

![directus-error](https://user-images.githubusercontent.com/456605/101148551-c45bee80-3643-11eb-91e5-1aa5c2a779bc.png)

**Comment by rijkvanzanten** [comment]
That `ERR_EMPTY_RESPONSE` feels suspicious to me. What kind of response are you seeing there? What webserver are you running locally to serve this? Just Node?

**Comment by jsthind** [comment]
I am running on Node. No other proxy or server. 

The /fields endpoint keeps waiting for a response and then times out with an ERR_EMPTY_RESPONSE error.

**Comment by rijkvanzanten** [comment]
But you are able to login? It feels like the query to the DB to extract the fields information times out 🤔 How are you connecting to MySQL? Does your MySQL user have a restricted permissions set?

**Comment by jsthind** [comment]
I have been using the same MySQL installation with the same credentials (username and password) for years without any issue. It is a standard MySQL installation on Ubuntu. And Directus is able to communicate with MySQL just fine because the installation completed successfully and I can see all the newly created tables in the DB.

I thought maybe my network is causing issues, so I tried installing Directus on the same server which hosts MySQL and got exactly the same error.

**Comment by rijkvanzanten** [comment]
@jsthind Can you try setting the `LOG_LEVEL` environment variable to `trace` and see where it hangs?

**Comment by jsthind** [comment]
Ok, will get the details for you tomorrow from the office. I am in a different timezone and it is 10:00 PM here.

Let me know if you need any other details.

**Comment by rijkvanzanten** [comment]
Anything that'd help me reproduce this on my end would be very welcome 🙂

**Comment by Fusseldieb** [comment]
@jsthind Did you get any further on this?

**Comment by jsthind** [comment]
I added the trace log as suggested and found that the code blocked at the below query:

`select `c`.`TABLE_NAME`, `c`.`COLUMN_NAME`, `c`.`COLUMN_DEFAULT`, `c`.`DATA_TYPE`, `c`.`CHARACTER_MAXIMUM_LENGTH`, `c`.`IS_NULLABLE`, `c`.`COLUMN_KEY`, `c`.`EXTRA`, `c`.`COLLATION_NAME`, `c`.`COLUMN_COMMENT`, `c`.`NUMERIC_PRECISION`, `c`.`NUMERIC_SCALE`, `fk`.`REFERENCED_TABLE_NAME`, `fk`.`REFERENCED_COLUMN_NAME`, `fk`.`CONSTRAINT_NAME`, `rc`.`UPDATE_RULE`, `rc`.`DELETE_RULE`, `rc`.`MATCH_OPTION` from `INFORMATION_SCHEMA`.`COLUMNS` as `c` left join `INFORMATION_SCHEMA`.`KEY_COLUMN_USAGE` as `fk` on `c`.`TABLE_NAME` = `fk`.`TABLE_NAME` and `fk`.`COLUMN_NAME` = `c`.`COLUMN_NAME` and `fk`.`CONSTRAINT_SCHEMA` = `c`.`TABLE_SCHEMA` left join `INFORMATION_SCHEMA`.`REFERENTIAL_CONSTRAINTS` as `rc` on `rc`.`TABLE_NAME` = `fk`.`TABLE_NAME` and `rc`.`CONSTRAINT_NAME` = `fk`.`CONSTRAINT_NAME` and `rc`.`CONSTRAINT_SCHEMA` = `fk`.`CONSTRAINT_SCHEMA` where `c`.`TABLE_SCHEMA` = 'directus'`


I googled a bit and found that slow information_schema in MySQL is a common problem. And the fact that my server has approx 450 databases and a few thousand tables only make this query worse.

Not sure if you can implement a workaround for this.

**Comment by rijkvanzanten** [comment]
> Not sure if you can implement a workaround for this.

No idea! I don't think we can pull all the required information from another source 🤔
