### ISSUE TITLE
Hide user directory for custom role

### ISSUE THREAD

**Issue by aleksejssaburovs92** [directus/directus#3302]
Directus version: v9.0.0-rc.20

Create new role, assign to new user. Restrict read for Directus users.
<img width="949" alt="Screenshot 2020-12-04 at 12 19 55" src="https://user-images.githubusercontent.com/12848012/101152041-2c520b00-362b-11eb-84b8-fb6808af8e88.png">

Expected result: User with new role don't have access to tab User Directory

Actual result:
<img width="1188" alt="Screenshot 2020-12-04 at 12 22 42" src="https://user-images.githubusercontent.com/12848012/101152229-6de2b600-362b-11eb-9b70-698e5dbf1f82.png">

**Comment by rijkvanzanten** [comment]
Does this role have app access enabled?

**Comment by aleksejssaburovs92** [comment]
<img width="934" alt="Screenshot 2020-12-04 at 18 05 16" src="https://user-images.githubusercontent.com/12848012/101186055-47d50a00-365b-11eb-96af-e215d5f79280.png">
Here are settings

**Comment by pkokorev** [comment]
I have the same issue. Current workaround is to enable read-only access to users for custom logins, but it's a huge security hole as any logged in user can see all other platform users.

**Comment by rijkvanzanten** [comment]
@pkokorev Sounds like you have the opposite issue here. The OP is saying the users do not show up, while it sounds like you're trying to hide them.

> Current workaround is to enable read-only access to users for custom logins

You can also configure the permissions so users can only see their own, other users with the same role, or based on a value in any of the other fields, or your own added fields.

> but it's a huge security hole

Why? Without any reason why it sounds like an opinion to me 🤷🏻

**Comment by pkokorev** [comment]
@rijkvanzanten it's the same issue, but different view angle.

> "Expected result: User with new role don't have access to tab User Directory"

I also expect them not to have access to users tab. And I also see "no app access" error instead. But as I absolutely need these custom users to log in, I just enabled the real-only access to "Directus Users" for my custom role. Now my new users can log in, but they can see each other and even admins in the "Users" tab which I don't want.

**Comment by rijkvanzanten** [comment]
Fixed in #4004

**Comment by bernardnongpoh** [comment]
This will reset User directory access
