### ISSUE TITLE
M2O Wrong Corresponding Field Name

### ISSUE THREAD

**Issue by bherbruck** [directus/directus#3303]
When you create an O2M Corresponding field from the M2O field editor, it defaults the field name to the 'one' side of the relationship instead of the 'many' side. It would be nice if it would default to the 'many' side (expressed in plural form if possible).

In the example of the screenshot below, it currently defaults to creating customer.customer instead of customer.order[s].
![Screenshot 2020-12-03 135656](https://user-images.githubusercontent.com/5258126/101166934-13cff980-3607-11eb-8a78-bd253199ad75.png)

**Comment by benhaynes** [comment]
Good catch!!
