### ISSUE TITLE
Download file only works if directus_files has a public read permission

### ISSUE THREAD

**Issue by TheAzack9** [directus/directus#3305]
It seems that when downloading an image inside directus then it doesn't use the users role, but defaults back to the public role. So when trying to download an image you just get refered to a new tab with the following error message:

```
{
  "errors": [
    {
      "message": "You're not allowed to read item \"011acaa0-ca74-4b58-9444-f4c7cf1915d5\" in collection \"directus_files\".",
      "extensions": {
        "collection": "directus_files",
        "item": "011acaa0-ca74-4b58-9444-f4c7cf1915d5",
        "action": "read",
        "stack": "Error: You're not allowed to read item \"011acaa0-ca74-4b58-9444-f4c7cf1915d5\" in collection \"directus_files\".\n    at AuthorizationService.<anonymous> (C:\\Projects\\directus\\api\\src\\services\\authorization.ts:412:10)\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Projects\\directus\\api\\src\\services\\authorization.ts:6:65)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
        "code": "FORBIDDEN"
      }
    }
  ]
}
```

----------------

Steps to reproduce:

1. Ensure that your role has read access to directus_files, but public does not have access.
2. Upload a random file
3. Go to said file in the file library
4. Try to press the download button

**Comment by rijkvanzanten** [comment]
Already fixed this thing in the sidebar's "Open in new Window" button, but forgot the main download button 🙈

**Comment by mcqueena9845** [comment]
I'm still getting this in rc24 when trying to download the file from the item instead of the file library.

**Comment by rijkvanzanten** [comment]
@mcqueena9845 Sounds like a similar issue in a different location. Mind opening a new issue>
