### ISSUE TITLE
Entering views causes console errors and empty lists

### ISSUE THREAD

**Issue by aleksejssaburovs92** [directus/directus#3309]
Version: v9.0.0-rc.20
Installation and running: CLI (npx)
DB: mysql
Surfing app as Admin

Entering Administrator role causes errors in console
<img width="1512" alt="Screenshot 2020-12-04 at 18 14 38" src="https://user-images.githubusercontent.com/12848012/101187343-e877f980-365c-11eb-8ee2-87455ddb5c9d.png">

Same in created collection, entering view causes errors and empty page (should be filled)
<img width="1692" alt="Screenshot 2020-12-04 at 18 15 04" src="https://user-images.githubusercontent.com/12848012/101187419-06455e80-365d-11eb-886e-583b088ab12e.png">

After restarting DB and project seems fixes it.
Expected to be logged somewhere this errors

**Comment by rijkvanzanten** [comment]
> After restarting DB and project seems fixes it.

This makes it nearly impossible for me to reproduce 😬 

Any step by step on how to get this error to show up?

**Comment by aleksejssaburovs92** [comment]
Sending [link to video](https://www.youtube.com/watch?v=I9ZgzH9UZM0), now these errors are always shown

**Comment by aleksejssaburovs92** [comment]
Debug is showing on this field, that causes error
![Uploading Screenshot 2020-12-07 at 15.20.27.png…]()

**Comment by kaYcee** [comment]
We can second this. We've set up three Directus instances on Ubuntu with the latest MySQL and it happens sometime after creating the first collections and adding documents. Once this happens, the system is unusable. Have switched to Postgres now where we haven't encountered this issue so far.

**Comment by benhaynes** [comment]
Can anyone provide a SQL dump of the unusable database?

**Comment by rijkvanzanten** [comment]
This was fixed in https://github.com/directus/directus/commit/7032eb4797b8c5560b999b7981d6622307bc9fee#diff-cda6d007b21a92862aa1ccdc4452b6bc439362a820c4436900447bc38538af2a
