### ISSUE TITLE
Add "show hidden" toggle for admin users in collections nav

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#3310]
It's very useful for admins to be able to temporarily show the hidden collections in the nav sidebar for debugging purposes.

@benhaynes thoughts on a design direction for this? It could be a small checkbox stuck at the very bottom of the nav list

**Comment by benhaynes** [comment]
Yeah! Seems good to have some access to those without hacking the URL. Could just be a show/hide toggle too. I'll draft a mock-up!

**Comment by benhaynes** [comment]
![Screen Shot 2021-02-10 at 1 01 32 PM](https://user-images.githubusercontent.com/522079/107551364-2c790480-6ba0-11eb-9f50-b97ab984b6d5.png)

Something like this? Or should it be more of a toggle at the _bottom_ of the nav bar?

**Comment by rijkvanzanten** [comment]
I think it should be visually a little more different from the menu items, so it feels more like a control and not like another link 🤔

**Comment by benhaynes** [comment]
![Screen Shot 2021-02-11 at 3 29 22 PM](https://user-images.githubusercontent.com/522079/107694948-f4e08a00-6c7d-11eb-849d-4bd8b939a605.png)

If we think either of these options is going to be too intrusive for normal usage (normally even admins won't need to see hidden collections), then I'd recommend adding it within the Page Info sidebar... or better yet, **adding it on a Right-Click event**!

**Comment by piotr-cz** [comment]
If anyone is wondering how to show Hidden collections, here's how to: Docs > [Hiding Collections](https://docs.directus.io/configuration/data-model/#hiding-collections)
