### ISSUE TITLE
Remove dependency on `one_primary` and `many_primary`

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#3311]
With the updated schema flow, we no longer need to rely on these fields in `directus_relations`, but can instead rely on the passed `schema`.

**Comment by benhaynes** [comment]
Would this be a breaking change? Do we need to add this to the 9.0.0 Milestone? @rijkvanzanten

**Comment by rijkvanzanten** [comment]
No and no 👍🏻 Just an optimization internally
