### ISSUE TITLE
Non persistent user session after logging in

### ISSUE THREAD

**Issue by leonardodipace** [directus/directus#3313]
The JavaScript SDK doesn't seem to store cookies to make the current user logged in after calling the `directus.auth.login()` method.
I'm able to successfully log in, but after a page refresh I get a 401 error when trying to fetch the current user.

Here's my setup:
```
const directus = new DirectusSDK("http://localhost:8055", {
  auth: {
    mode: "cookie",
    autoRefresh: true,
  },
})
```

I also get a 400 error right after logging in. The error seems to belong to the `/auth/refresh` endpoint.

**Comment by rijkvanzanten** [comment]
How/when are you calling the current user info? Could it be that you're not awaiting login before accessing the user?

**Comment by leonardodipace** [comment]
I'm calling `directus.users.me.read()` in a useEffect in my _app.js.

**Comment by rijkvanzanten** [comment]
OK, that doesn't really mean that much to me... I don't know your app / _app.js / effects structure 😁 

I just wanna make sure you're awaiting the promise for `login` before calling this read, like:

```
await directus.auth.login();
^^^^^

directus.users.me.read();
```

and/or use a promise

```
directus.auth.login()
  .then(() => {
    directus.users.me.read()
  });
```

**Comment by leonardodipace** [comment]
My _app.js is made up of a simple useEffect:

```
useEffect(async () => {
    await directus.auth.login() // Just added, still not working
    const me = await directus.users.me.read()
    console.log(me)
  }, [])
```

And that's what I get after adding `await directus.auth.login()`:

![console](https://user-images.githubusercontent.com/63299726/101223808-2ab92f00-368d-11eb-98f9-2a015c11b80b.jpg)

**Comment by rijkvanzanten** [comment]
You're not passing any user credentials to login, so it doesn't log you in. See https://docs.directus.io/reference/sdk-js.html#reference

> My _app.js is made up of a simple useEffect:

Keep in mind that not everybody uses React or is familiar with those concepts :) I have no idea what useEffect does, why the file is called _app.js or what that empty array is for 😁

**Comment by leonardodipace** [comment]
You're right, sorry for that! 😄
I just removed the credentials here on github by the way.
Let me be a little clearer:
I have a login page where I ask the user to enter their credentials and then I pass them to the `directus.auth.login()` method.
The user successfully logs in, but has to login again after a page reload.
What I'd like to achieve is a persistent session, without having to manually login every time.
Thanks!

**Comment by apstanisic** [comment]
So here's the problem. First time the user logs in, access token is saved in memory, and everything works, but when user refreshes the page, there is no access token and request fails. Running `auth.refresh()` does not work because axios is not sending cookies by default. When I change source code of sdk to send cookies with  `withCredentials: true`, it throws CORS error. Even after fixing CORS errors `auth/refresh` expects access token that is lost after refresh.

I'll create a pull request in the next couple of days fixing this, I just have to find cleanest way to fix CORS, but I don't think there is, we have to specify every domain in CORS_ORIGIN.

**Comment by rijkvanzanten** [comment]
@apstanisic You can configure the CORS rules in Directus, so for the SDK, we can set withCredentials 👍

**Comment by apstanisic** [comment]
When I add `withCredentials`, it throws this error:
```
Access to XMLHttpRequest at 'http://localhost:8055/users/me' from origin 'http://localhost:3000' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
```
We have to specify in `.env` domains that can access api with cookies.
CORS_ORIGIN must be changed from `CORS_ORIGIN=*` to `CORS_ORIGIN=https://localhost:3000` or other domain that are used. 
I do not know a way that we can configure an api to accept without specifying each domain.
@rijkvanzanten Do you have any ideas? How did you solve this problem in v8 sdk?

**Comment by rijkvanzanten** [comment]
@apstanisic Can you try setting `CORS_ORIGIN` to `true`? That should cause it to return the referrer as the cors origin header, as per https://expressjs.com/en/resources/middleware/cors.html:

> origin: Configures the Access-Control-Allow-Origin CORS header. Possible values:
>   * Boolean - set origin to true to reflect the request origin, as defined by req.header('Origin'), or set it to false to disable CORS.

**Comment by apstanisic** [comment]
It works! There are couple small errors that I need to fix, and I'll create PR.

- If user uses auto refresh, it should be called automatically after loading sdk, not after accessing sdk.auth
- New refresh timeout is created with every access to sdk.auth
- Don't send auto refresh request if user is not logged in
- Access token should be stored so it can be used after page refresh
- I think `/auth/refresh` api requires valid access token to refresh, running `sdk.auth.refresh()` after page refresh and sending cookie still returns 401

**Comment by rijkvanzanten** [comment]
Sounds good @apstanisic!

One small thing:

> Don't send auto refresh request if user is not logged in

The SDK can't know if the user is logged in or not, as the refresh token can/will be in a `httpOnly` cookie, meaning we can't read it from JS (for security reasons)

**Comment by apstanisic** [comment]
But we can save access token, so even if access token is expired, at least we know that at some time user was logged in. Or at least when user successfully logs in, we can set a login flag to true. And simply destroy that value on logout.

Something like:
```ts
login() {
    loginStuff()
    localStorage.setItem('directus_logged_in', 'true');
}
refresh() {
    if (localStorage.getItem('directus_logged_in) !== 'true') return;
    refreshStuff()
```

**Comment by rijkvanzanten** [comment]
Good point! Lets go with that 👍

**Comment by apstanisic** [comment]
Here's the PR #3337  that should fix this.
