### ISSUE TITLE
SSL Cert issue on digitalocean

### ISSUE THREAD

**Issue by rnewton** [directus/directus#3314]
Hitting this error when deploying `v9.0rc.20` on digitalocean app platform:

```
$ directus start
Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1502:34)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:711:12) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}
error Command failed with exit code 1.
```

I have set the environment variables as 

```
DB_HOST=${db.HOSTNAME}
DB_PORT=${db.PORT}
DB_DATABASE=${db.DATABASE}
DB_USER=${db.USERNAME}
DB_PASSWORD=${db.PASSWORD}
DB_SSL__REJECT_UNAUTHORIZED=true
DB_SSL__CA=${db.CA_CERT}
```

What am I missing?

**Comment by rijkvanzanten** [comment]
That looks good to me. Is your connected db component called `db`?

**Comment by rnewton** [comment]
Correct. I was able to work around by setting `NODE_TLS_REJECT_UNAUTHORIZED=0` in env. That generates a warning about it being insecure, obviously, but it gets me to the next step.

**Comment by rijkvanzanten** [comment]
What other env vars have you set? There must be some sort of conflict 🤔 

![CleanShot 2020-12-07 at 08 52 00](https://user-images.githubusercontent.com/9141017/101358955-9657f380-3869-11eb-82e6-57ac0626cbe7.png)

This (combined with `DB_CLIENT=pg`) does the trick on my end

**Comment by seanmars** [comment]
I got the same problem when I `npx create-directus-project` with PostgreSQL with SSL

**Comment by YannickMol** [comment]
Hi @rnewton , did you get this fixed in the end?

**Comment by rnewton** [comment]
No, I ended up using my workaround (`NODE_TLS_REJECT_UNAUTHORIZED=0`). I was only evaluating if I wanted to use directus rather than being concerned about a secure production deploy.

**Comment by rijkvanzanten** [comment]
I'll close this for now, as I'm assuming it's a configuration quirk. (+ we can confirm it's working as expected with the correct config)

**Comment by YannickMol** [comment]
@rijkvanzanten I have asked a similar question on Discord, maybe you can have a look there.

**Comment by dosandco** [comment]
I'm having the same problem here using the CLI on DigitalOcean

![image](https://user-images.githubusercontent.com/48129960/103216215-669e8780-490d-11eb-9663-fd29128e7ac4.png)

Is there any workaround to this?

**Comment by rijkvanzanten** [comment]
@dosandco See above. Either run with `NODE_TLS_REJECT_UNAUTHORIZED` set to `0`, or create your `.env` manually and run `directus bootstrap` instead

**Comment by chishaku** [comment]
> I'll close this for now, as I'm assuming it's a configuration quirk. (+ we can confirm it's working as expected with the correct config)

What is the correct config here?

I just ran into this problem and fortunately found this issue.

The env variables I have set:  `DB_CLIENT=pg`, `DB_CONNECTION_STRING=...`

I couldn't connect until add this workaround: `NODE_TLS_REJECT_UNAUTHORIZED=0`.

I'm using DigitalOcean managed postgres:11.

**Comment by rijkvanzanten** [comment]
@chishaku Have you tried [these env vars](https://github.com/directus/directus/issues/3314#issuecomment-739931706)

**Comment by chishaku** [comment]
I will try those now.  But forgive my ignorance, what would the value for `DB_SSL__CA` be?

**Comment by rijkvanzanten** [comment]
You can pull that from DO's environment variables: 

https://www.digitalocean.com/docs/app-platform/how-to/use-environment-variables/

It's the name of your database component + `.CA_CERT`

**Comment by chishaku** [comment]
@rijkvanzanten Downloaded the cert from the DO admin panel and those env vars worked.  

Thank you for the quick response!

Have had my eye on directus for a couple years and am very excited about the postgres support.  

So far so good so thank you again!

**Comment by eliteproxy7** [comment]
i get the same error but when I observe the logs I see 


```
connection authorized: user=doadmin database=defaultdb application_name=do-pruned SSL enabled (protocol=TLSv1.3, cipher=TLS_AES_256_GCM_SHA384, bits=256, compression=off) 

postgresql-13.service  [17-1] pid=9444,user=doadmin,db=defaultdb,app=do-pruned,client=127.0.0.1 LOG  disconnection: session time: 0:00:00.029 user=doadmin database=defaultdb host=127.0.0.1 port=57908 
 postgresql-13.service  [15-1] pid=9451,user=[unknown],db=[unknown],app=[unknown],client=[local] LOG  connection received: host=[local] 
postgresql-13.service  [16-1] pid=9451,user=postgres,db=defaultdb,app=[unknown],client=[local] LOG  connection authorized: user=postgres database=defaultdb application_name=do-pruned 
postgresql-13.service  [17-1] pid=9451,user=postgres,db=defaultdb,app=do-pruned,client=[local] LOG  disconnection: session time: 0:00:00.016 user=postgres database=defaultdb host=[local] 
postgresql-13.service  [15-1] pid=9468,user=[unknown],db=[unknown],app=[unknown],client=[local] LOG  connection received: host=[local] 
 postgresql-13.service  [16-1] pid=9468,user=postgres,db=defaultdb,app=[unknown],client=[local] LOG  connection authorized: user=postgres database=defaultdb application_name=do-pruned 
postgresql-13.service  [17-1] pid=9468,user=postgres,db=defaultdb,app=do-pruned,client=[local] LOG  disconnection: session time: 0:00:00.015 user=postgres database=defaultdb host=[local] 
```

so looks like it connects but i get this in the deployment logs

```

[2021-05-20T04:06:13.580051488Z] > aws-sdk@2.910.0 postinstall /workspace/node_modules/aws-sdk
[2021-05-20T04:06:13.580056462Z] > node scripts/check-node-version.js
[2021-05-20T04:06:13.580059937Z] 
[2021-05-20T04:06:13.848594114Z] added 769 packages in 24.871s
[2021-05-20T04:06:13.874665081Z] 
[2021-05-20T04:06:22.828954216Z] Running custom build command: npx directus bootstrap
[2021-05-20T04:06:23.772968927Z] 04:06:23 ✨ Initializing bootstrap...
[2021-05-20T04:06:23.863754644Z] (node:575) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
[2021-05-20T04:06:49.031880268Z] 04:06:49 🚨 Can't connect to the database
[2021-05-20T04:06:49.039814754Z] building: exit status 1
[2021-05-20T04:06:49.043479184Z] ERROR: failed to build: exit status 1
[2021-05-20T04:06:55.671335010Z] 
[2021-05-20T04:06:55.671365727Z] For documentation on the buildpacks used to build your app, please see:
[2021-05-20T04:06:55.671371813Z]    Node.js: https://do.co/apps-buildpack-node
[2021-05-20T04:06:55.672967074Z] 
[2021-05-20T04:06:55.673447703Z]  ! Build failed (145)
```

i set my variables on the app level

![image](https://user-images.githubusercontent.com/5486268/118918188-5e68d800-b900-11eb-868b-d847e4a9215a.png)

**Comment by rijkvanzanten** [comment]
@eliteproxy7 It seems like you're setting "reject unauthorized" to true on the DB, but then disable it globally in node (the "node tls reject unauthorized" one). Try removing the NODE_TLS one 👍🏻 

Also make sure that your connected service in DO app platform is using the correct user in these environment variable. I believe the `CA_CERT` is connected to a specific user, see the "Settings" pane in DO:

![CleanShot 2021-05-20 at 10 19 01@2x](https://user-images.githubusercontent.com/9141017/118995312-0a3c1300-b955-11eb-85d5-a5083f0b6644.png)

**Comment by kropsi** [comment]
> @rijkvanzanten Downloaded the cert from the DO admin panel and those env vars worked.
> 
> Thank you for the quick response!
> 
> Have had my eye on directus for a couple years and am very excited about the postgres support.
> 
> So far so good so thank you again!

Hello @chishaku I am having the same trouble here. I can see that you wrote that you managed to do this by downloading CA from DO. But what did you do with it exactly. Can you please share some more insights on how you made it work?

**Comment by timyau** [comment]
I have a solution to make it work, actually the procedure should be like this:
1) Create database in DigitalOcean Platform.
2) Fill-in the database connection detail from the newly created DO database into the local .env file in Directus.
3) In .env, **DB_SSL__REJECT_UNAUTHORIZED must set to FALSE**
4) Execute "npx directus bootstrap" **LOCALLY**. Then the database for Directus should be created successfully.
5) Prepare another environment variable file for DO use. 
6) Push all code (not local .env) to Github, with the config for DO App Platform.
7) Create App in DO App platform, choose your Repo with your Directus code.
8) Attach the DO Database into the App instead of creating a new one.
9) Only set environment variable regarding to database connection, and CONFIG_PATH to your config file.
11) Again, **DB_SSL__REJECT_UNAUTHORIZED must set to FALSE**.
12) **Don't** set **npx directus bootstrap** in build command, only **npx directus start** in start command.
13) Deploy.
14) Then you should be able to make it work on Digital Ocean App Platform.

**Comment by rijkvanzanten** [comment]
@timyau I've also had success by using:

1) Create database in DigitalOcean Platform.
2) Setup a new App Platform instance
3) Setup all the environment variables, and attach the database instance
    Use `DB_SSL__REJECT_UNAUTHORIZED=true` and `DB_SSL__CA=${my-database-component-name.CA_CERT}`. Make sure to substitute `my-database-component-name` for the name of your connected database service
4) Use `npx directus bootstrap && npx directus start` as the start command

**Comment by kropsi** [comment]
@rijkvanzanten and @timyau, thank you both for the support. I managed to configure App platform, and as mentioned in my own [thread](https://github.com/directus/directus/discussions/6832) it was because of the "trusted sources" setting in the managed database instance. Simply put, currently, you cannot limit access to your managed database directly inside Digitalocean. That is something that is being worked on. In my case, I blindly added the generated IP into trusted sources and after a re-build, it stopped working as the IP for App platform instances is changing after each re-build. I didn't realize that that was the problem until much later.

**Comment by mdocter** [comment]
Ran into this issue from a local Docker dev setup. In my case I also had to set the `DB_SSL__REQUIRE` environment variable: 

DB_SSL__REQUIRE=true
DB_SSL__REJECT_UNAUTHORIZED=false
DB_SSL__CA=/etc/ssl/certs/ca-certificate.crt

**Comment by havardox** [comment]
> What other env vars have you set? There must be some sort of conflict thinking
> 
> ![CleanShot 2020-12-07 at 08 52 00](https://user-images.githubusercontent.com/9141017/101358955-9657f380-3869-11eb-82e6-57ac0626cbe7.png)
> 
> This (combined with `DB_CLIENT=pg`) does the trick on my end

To anyone reading this in the future:

If you write EXACTLY the way listed above, then it should work. Double check for any selling issues, that's what caused my config to fail.

**Comment by M-GRV** [comment]
For anybody in the future seeing this using CLI...

DB_SSL__REJECT_UNAUTHORIZED=false

add this to your .env 

than run bootstrap

**Comment by rijkvanzanten** [comment]
> For anybody in the future seeing this using CLI...
> 
> DB_SSL__REJECT_UNAUTHORIZED=false
> 
> add this to your .env
> 
> than run bootstrap

I'd recommend against that. It disables SSL checking for the connection. Instead, make sure to configure `DB_SSL__CA` with the CA_CERT value provided by DigitalOcean

**Comment by LeonManolo** [comment]
Im stuck right now, Im having the same issue. My directus app is running on a DO Droplet with managed postgres database(also on DO).
Error:
```
ERROR: Can't connect to the database.
[10:48:57.380] ERROR: self-signed certificate in certificate chain
    err: {
      "type": "Error",
      "message": "self-signed certificate in certificate chain",
      "stack":
          Error: self-signed certificate in certificate chain
              at TLSSocket.onConnectSecure (node:_tls_wrap:1550:34)
              at TLSSocket.emit (node:events:514:28)
              at TLSSocket._finishInit (node:_tls_wrap:967:8)
              at ssl.onhandshakedone (node:_tls_wrap:743:12)
      "code": "SELF_SIGNED_CERT_IN_CHAIN"
    }
    ```
    
To configure the database connection in Directus, I've set the following environment variables for my docker container:
DB_CLIENT=pg
DB_CONNECTION_STRING
DB_SSL=true
DB_SSL__CA // This contains the value extracted from the `.crt`(CA certificate) file provided by Digital Ocean for the managed database.
DB_SSL__REQUIRE=true

What am I doing wrong here?

**Comment by LeonManolo** [comment]
> Im stuck right now, Im having the same issue. My directus app is running on a DO Droplet with managed postgres database(also on DO). Error:
> 
> ```shell
> ERROR: Can't connect to the database.
> [10:48:57.380] ERROR: self-signed certificate in certificate chain
>     err: {
>       "type": "Error",
>       "message": "self-signed certificate in certificate chain",
>       "stack":
>           Error: self-signed certificate in certificate chain
>               at TLSSocket.onConnectSecure (node:_tls_wrap:1550:34)
>               at TLSSocket.emit (node:events:514:28)
>               at TLSSocket._finishInit (node:_tls_wrap:967:8)
>               at ssl.onhandshakedone (node:_tls_wrap:743:12)
>       "code": "SELF_SIGNED_CERT_IN_CHAIN"
>     }
> ```
> 
> To configure the database connection in Directus, I've set the following environment variables for my docker container:
> 
> ```shell
> DB_CLIENT=pg
> DB_CONNECTION_STRING
> DB_SSL=true
> DB_SSL__CA // This contains the value extracted from the `.crt`(CA certificate) file provided by Digital Ocean for the managed database.
> DB_SSL__REQUIRE=true
> ```
> 
> What am I doing wrong here?

Nevermind I fixed it by using only these env variables:
```shell
DB_PORT
DB_HOST
DB_USER
DB_PASSWORD
DB_DATABASE
DB_SSL__CA # copy and paste the content of the CA certificate provided by digital ocean here
```

**Comment by BlackDahlia313** [comment]
> > For anybody in the future seeing this using CLI...
> > DB_SSL__REJECT_UNAUTHORIZED=false
> > add this to your .env
> > than run bootstrap
> 
> I'd recommend against that. It disables SSL checking for the connection. Instead, make sure to configure `DB_SSL__CA` with the CA_CERT value of you database provided by DigitalOcean

this works great!

**Comment by weberet** [comment]
Encountered this issue recently and talked to another on Discord who also experienced it this issue so I wanted to record a bit of what the solution looked like for myself. I tried a lot of the work around environment variables such as disable checks. Was experiencing this error on both AWS Postgres RDS and Digital Ocean Managed Postgres.

My setup is Directus on a Digital Ocean droplet with Docker, and a Digital Ocean managed PostgreSQL database. 

As suggested elsewhere in this thread I downloaded SSL certificate from Digital Ocean (the .crt file), and extracted its contents to put into the docker-compose.yml file

Due to the lengthy nature of SSL certificates, YAML formatting can be a bit complex. I found that using the DB_SSL__CA: | syntax in the docker-compose.yml file allowed for a straightforward inclusion of the entire SSL certificate, seems to have resolved it for me and avoided needing to disable SSL checks with other variables.

Below is the **docker-compose.yml** configuration that I used successfully, sensitive information has been replaced with 'XXXXX':

```
version: "3"
services:

  cache:
    image: redis:6

  directus:
    image: directus/directus:10.8.2
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
    depends_on:
      - cache
    environment:
      KEY: "XXXXXXXXXXXXXXXXX"
      SECRET: "XXXXXXXXXXXXXX"
      ADMIN_EMAIL: "XXXXXXXX"
      ADMIN_PASSWORD: "XXXXXXXXXXXXX"
      DB_CLIENT: "postgres"
      DB_HOST: "XXXXXXXXXXXXX.ondigitalocean.com"
      DB_PORT: "25060"
      DB_DATABASE: "XXXXXXX"
      DB_USER: "XXXXXXXX"
      DB_PASSWORD: "XXXXXXXXXXXXX"
	  
      # The variable that resolves the issue, ensure you are complying with YAML as you do this as its a long string with characters that you need to escape if you do it another way
      DB_SSL__CA: |
        -----BEGIN CERTIFICATE-----
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        -----END CERTIFICATE-----

      WEBSOCKETS_ENABLED: "true"

      EMAIL_VERIFY_SETUP: "true"
      EMAIL_FROM: "XXXXXXXXXX"
      EMAIL_TRANSPORT: "ses"
      EMAIL_SES_CREDENTIALS__ACCESS_KEY_ID: "XXXXXXXXXXXX"
      EMAIL_SES_CREDENTIALS__SECRET_ACCESS_KEY: "XXXXXXXXXXXX"
      EMAIL_SES_REGION: "us-west-1"

      MAX_PAYLOAD_SIZE: "20mb"

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6379'
```
