### ISSUE TITLE
M2A doesn't use saved sort value

### ISSUE THREAD

**Issue by emrahnazif** [directus/directus#3315]
Hi all,

m2a is great, to make it better why not to have a sorting feature.
For now it doesn't work. 

- create m2a relationship
- add a sort field to Junction collection
- edit m2a and select newly created sort field as the sort field from interface tab. 
- sorting hamburger menu appears (when you try to add/modify an item)
- when you sort them, it just doesn't work.

What do you think?
Thanks

**Comment by rijkvanzanten** [comment]
> when you sort them, it just doesn't work.

Could you elaborate on this? Is there an error thrown? Or does it not sort at all?

If the latter, what browser is this on?

**Comment by ctheprinter** [comment]
I'll jump on this issue to explain the issue I mentioned in discord.

### Issue: many-2-any field does not save the sortation of items.

### Steps to Recreate:
While trying to create a page builder type.

Using a many-2-any (m2a) field builder. created with default/ obvious values, there is no option to create a sort field, so left blank. Then once the junction table is created, I have created a sort column in the junction column. Then back in to the m2a field I have added the sort field as an option.

When adding items to the m2a field in the editor, I can drag and move the items in order and appears to work.

However once I save it and refresh the page it hasn't actually saved the sortation of the items.

**Comment by emrahnazif** [comment]
> Could you elaborate on this? Is there an error thrown? Or does it not sort at all?
> If the latter, what browser is this on?

There is no error thrown. It do not sort at all. Browser chrome v87.0.4280.88. Also tested with safari v14.0.2, doesn't work at all. 

@ctheprinter Exactly same steps to produce the bug. 

any update on this? The goal is to sort m2a items.

**Comment by emrahnazif** [comment]
new info:
- Create an m2a field
- Create a sort field at junction table (to be able to sort items in your m2a)
- Edit your m2a field (from data model) and select your newly created "sort" field as the sort field (from interface tab)
- Create some random content in your m2a and save
- Click your item to edit. Sort the items in your m2a and save.
- Click your item to edit again displaying m2a items will not respect your order (it will display depending on ID number, I believe) BUT in the database actually sort fields have correct value respecting with your sorting. 
- In this stage if you save again, your sorting will be overwritten as it was not displayed good already.

I checked the database. After sortin&saving items in m2a, sort field at the Junction table updated with the correct order. But when you try editing the Item (in the collection with m2a). The sort order in doesn't taken in to account and it displays items as originally (I believe with the ID in the Junction table) created. So in db items has correct sorting numbers but in admin it doesn't display them with respecting this order. 

This cause a problem while editing, because if you add/remove/modify any item in the m2a field, it overwrites the sorting. So you lose sorting even it is not displayed correctly in admin. 

Explaining this is harder than I thought. 👍

**Comment by benhaynes** [comment]
I am getting a _related_ error where I can not set the `Sort Field` for the Many-to-Any interface. This is an existing interface that is confirmed to be working, but I can't configure the Sort Field. I already have an `INT` sort field on the junction (also set to Collection Sort)... but can't select it in the Settings.

![Screen Shot 2021-01-12 at 4 24 07 PM](https://user-images.githubusercontent.com/522079/104376618-410ba380-54f3-11eb-958f-09976c4885a1.png)

**Comment by nagman** [comment]
This is still true with directus 9.0.0-rc.30.

The issue seems to be related to the vue.js view, not to the backend.
Because as you mentioned, @emrahnazif, the database is correctly ordered.
There should be some sorting to arrange in the frontend listing.

Also, having an automatically generated `sort` field when creating a M2A field would be a nice improvement.

But the priority is to correct that sorting. Because the administrators (or "clients", or "not developers", or whatever you call them) would be confused when editing their website, as they won't understand why the list is reordered in `id` order at page refresh.

I've looked at the request made from the back-office to gather all entries, and there's no sorting made:
```
Request URL: https://foo.bar/items/posts?filter=%7B%22id%22:%7B%22_in%22:[2,3,4,5,6,7]%7D%7D&fields[]=id&fields[]=item&fields[]=collection
```
Which gives in readable format:
```
filter={"id":{"_in":[2,3,4,5,6,7]}}&fields[]=id&fields[]=item&fields[]=collection
```
You actually just need to add `sort=sort` to this request and voilà!
But I have no idea where that request is triggered...

**Comment by autr** [comment]
I've been using 9.0.0-rc.28 and I noticed the sort parameter is missing / disabled by default when creating an M2A. I would go first to the junction model to create an integer sort field, then back to the model to select it - and don't seem to have had any troubles yet. What I would hope for though is for this to be done by default when the junction is first created :)

**Comment by benhaynes** [comment]
Yes, we'll definitely be adding an option to include `sort` when configuring the O2M, M2A and M2M... will make that process much faster and more intuitive!
