### ISSUE TITLE
Multiple upload field issue on directus@9.0.0-rc.19

### ISSUE THREAD

**Issue by hamid-kamalpour** [directus/directus#3316]
Hi,

Seems there is an issue regarding the multiple files upload field, When we have two multiple upload fields in a collection they will affect each other, For example, When we add an image to field A, the image will add to field B automatically after saving.

Have a look at the following gif to better understand,

![ezgif-6-d0f2398015ea](https://user-images.githubusercontent.com/3541858/101235297-d473dc80-36dc-11eb-80f1-3b5357cdfa4a.gif)

**Comment by rijkvanzanten** [comment]
I can't reproduce this issue on my end. I'm assuming you're using the exact same relationship setup for both fields, which causes the update of one to propagate in the other (which is expected, as the files are saving to the same junction table).

Make sure that you're using a different relational setup for Gallery than for Gggggg. 

I can see how this confusion started; the relationship setup defaults to the same name for the junction table, so the second files field you setup uses the same name for the junction collection and foreign key fields. We'll update the app to append an identifier on subsequent relations to the same related collection 👍
