### ISSUE TITLE
Section-title displayed as Json code in some languages

### ISSUE THREAD

**Issue by thildebrandt** [directus/directus#3317]
In some languages (for example german) the "section-title" in a collection-view is displayed as Json code. This is probably because a special character occurs in the JSON code...?!

---

### Project details
Directus Version: 9.0.0-rc.20
Environment: production
OS: Windows_NT 10.0.19041
Node: 14.15.1

**Comment by rijkvanzanten** [comment]
Duplicate of https://github.com/directus/directus/issues/3297, duplicate of https://github.com/directus/directus/issues/3210, see https://github.com/directus/directus/issues/2962
