### ISSUE TITLE
App – Cannot read property 'one_collection' of undefined

### ISSUE THREAD

**Issue by taylorbourne** [directus/directus#3331]
Getting a javascript error while running the app.. Once I click on my "Recipes" collection, the error is thrown and everything kind of soft locks. Switching to other collections doesn't work until I refresh my browser.

<img width="1153" alt="Screen Shot 2020-12-06 at 11 02 46 PM" src="https://user-images.githubusercontent.com/6217194/101319738-4a7c5e80-3817-11eb-9587-376dc880e18b.png">

<img width="822" alt="Screen Shot 2020-12-06 at 11 05 42 PM" src="https://user-images.githubusercontent.com/6217194/101319901-97603500-3817-11eb-8403-d4b94bea0bc4.png">

This collection deals with standard fields, though it does have 2 repeater fields. Let me know what other information you need. I've tried 

- Deleting all the items in the impacted collection
- Restarting the server

Update – if it helps, switching to a singleton collection allows me to view other collections besides "Recipes". Clicking "Recipes" again after that will soft lock things again.

**Comment by taylorbourne** [comment]
Feel free to close this out? I ended up double checking the "display" property of each of my repeater fields. Removed the JSON selection and re-added it.

**Comment by aleksejssaburovs92** [comment]
@taylorbourne how you done filtering data models by Pages/Content?

**Comment by rijkvanzanten** [comment]
@taylorbourne Could you share the setup that causes the issue? I'd like to handle those configuration issues a little more gracefully if possible

**Comment by taylorbourne** [comment]
@rijkvanzanten sure! What's the best way to share that info? I found that I was also in this weird state where if I linked a "Recipe" item to a "Post" (another collection) item I would get an error on the UI telling me the Recipe requires 2 fields that were actually properly filled out, and that the Post in question is missing a required title that was also filled out haha.

**Comment by rijkvanzanten** [comment]
Either here, or [on Discord](https://directus.chat) if it contains (semi-)private data
