### ISSUE TITLE
sqlite seeding issue on npx create-directus-project

### ISSUE THREAD

**Issue by JeremyPittard** [directus/directus#3334]
error - Something went wrong while seeding the database 

steps to recreate
1 - npx create-directus-project
2 - select sqlite
3 - confirm path for db to save

I have tried this on multiple machines (all running windows 10 though) 
with npm 15.3.0, 14.9.0 and 14.4.0

**Comment by rijkvanzanten** [comment]
Duplicate of https://github.com/directus/directus/issues/2904
