### ISSUE TITLE
Nav Items should not wrap

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#3335]
All items should trim with an ellipses, and use a delayed tooltip to show the full name.

![Screen Shot 2020-11-30 at 3 38 55 PM](https://user-images.githubusercontent.com/522079/101371694-0e79e580-3879-11eb-9fa9-f217978bd16a.png)

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/directus/pull/4035
