### ISSUE TITLE
Arrow keys are not working in relational setup inputs

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#3336]
![Screen Shot 2020-11-22 at 5 04 07 PM](https://user-images.githubusercontent.com/522079/101372550-07070c00-387a-11eb-866f-adf2911fa94a.png)

The keyboard arrow keys don't allow you to navigate between characters within the input.

**Comment by rijkvanzanten** [comment]
Most likely because db-safe in v-input doesn't allow any non-safe character, which is a little too harsh as it should still support keys like tab, esc, enter, and the arrows
