### ISSUE TITLE
i18n - "collections" key

### ISSUE THREAD

**Issue by yesez5** [directus/directus#3345]
Hi! currently @ en-US\index.json the property `collections`  has the following structure: `"collections": "Collections"`
However the other files have this structure: 
```
"collections": {
    "directus_activity": "Actividad",
    "directus_files": "Archivos",
    "directus_users": "Usuarios"
  }
```

I tried to change the value through *locales.directus.io* but the key/context does not appear.
![firefox_4Pe0u93qS2](https://user-images.githubusercontent.com/1390475/101441485-cc838a80-38de-11eb-83b6-3b8e97efe650.jpg)

This issue originates a visual  bug on `collection.vue -> v-breadcrumb`

![error](https://user-images.githubusercontent.com/1390475/101441860-b0ccb400-38df-11eb-81f0-f2859cf39c7b.jpg)

Let me know if I can help with something.
Thanks for your support guys!

**Comment by Fusseldieb** [comment]
> I tried to change the value through locales.directus.io but the key/context does not appear.

I'm almost sure the translation needs to be approved first in order to work in Directus

Also, similar to #3210, #3297 and #3317

**Comment by yesez5** [comment]
@Fusseldieb true that! Thank you.
