### ISSUE TITLE
Js error when using with any relationships

### ISSUE THREAD

**Issue by shlaing** [directus/directus#3346]
![Screenshot 2020-12-08 at 3 37 47 PM](https://user-images.githubusercontent.com/811734/101454077-55480800-396b-11eb-89ab-b388f5165af6.png)
Js error when using with any relationships.
---

### Project details
Directus Version: v9.0.0-rc.20
Environment: production
OS: MacOS 11.01
Node: v.12.18.3

**Comment by rijkvanzanten** [comment]
There's a bunch of unrelated warnings thrown here it seems.. What is that connection refused about on /collections and /server/info for example? What is the relationship you configured? Are you able to send a DB dump where this happens?

**Comment by shlaing** [comment]
Duplicate with #3322
