### ISSUE TITLE
Related values crashes when in translations

### ISSUE THREAD

**Issue by shi-rudo** [directus/directus#3350]
After setting up the translation table the list view of it does not load. Switching to card view does display the entries. The translations table always displays "Loading...".

Filtering (deselecting fields) does not help.

Using docker: 
image: postgres:latest
image: directus/directus:v9.0.0-rc.20

**Comment by shi-rudo** [comment]
update: 
it does happen if I set the field "languages_code" to _display_ "related values". Without any setting for _display_ the list view does show again.

**Comment by rijkvanzanten** [comment]
What settings did you use for the `related values` display?

**Comment by shi-rudo** [comment]
this setting:

![Image of Error](http://www.dlds.de/001.jpg)

leads to this:

![Image of Error](http://www.dlds.de/002.jpg)

**Comment by benhaynes** [comment]
We should add placeholder text for all Display Templates so it's clearer **how** to set that up. Something like:

```
Add field values by clicking the icon to the right...
```

**Comment by rijkvanzanten** [comment]
Yeah! And prevent it from crashing when empty of c 🙂
