### ISSUE TITLE
Directus installation fails w/ mysql 5.6

### ISSUE THREAD

**Issue by KOREAN139** [directus/directus#3355]
## Versions
OS: Ubuntu 18.04.5 LTS
DB: Mysql 5.6.44 (AWS RDS)
Node: v14.15.1
npm: 6.14.8

## Description
Directus installation with command `npx create-directus-project` fails with error below.

```
Something went wrong while seeding the database:

[ER_PARSE_ERROR] create table `directus_collections` (`collection` varchar(64), `icon` varchar(30), `note` text, `display_template` varchar(255), `hidden` boolean not null default '0', `singleton` boolean not null default '0', `translations` json, `archive_field` varchar(64), `archive_app_filter` boolean not null default '1', `archive_value` varchar(255), `unarchive_value` varchar(255), `sort_field` varchar(64)) - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json, `archive_field` varchar(64), `archive_app_filter` boolean not null default' at line 1
```

Since environments above satisfies [all requirements](https://github.com/directus/directus#-requirements) which directus says on README.md, installation should be work.

Found some issues from this repo, but seems like none of them are related to me.

Can you guys help me to set up CMS w/ directus?

**Comment by rijkvanzanten** [comment]
Good catch, Directus requires MySQL 5.7.8 or higher.

Generally speaking, we aim to supporting the "current" and "latests" active versions of third party software, so in this case MySQL 5.7(.8) and 8 and newer at time of writing

![CleanShot 2020-12-08 at 16 16 50](https://user-images.githubusercontent.com/9141017/101542595-fd140480-3970-11eb-8151-e3f7f284de0e.png)
