### ISSUE TITLE
CLI install does not work on CentOS 7.9

### ISSUE THREAD

**Issue by cliqer** [directus/directus#3356]
![image](https://user-images.githubusercontent.com/3495993/101548144-4aa96500-39a3-11eb-85ca-67f1dee77ad3.png)
```
-sh-4.2$ npx create-directus-project test
npx: installed 46 in 1.583s

-sh-4.2$ ls test
extensions  node_modules  package.json  package-lock.json  uploads
```

I use v8 for quite some time and wanted to test v9.
Unfortunately in my case, I do not get any database selection to proceed; just finishes without an error.

Also tried with yarn with no avail but now I get the 'fsevents' error:
```
-sh-4.2$ yarn create directus-project test
yarn create v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-directus-project@9.0.0-rc.21" with binaries:
      - create-directus-project
[#####################################################################] 266/266⠋Done in 12.65s.
-sh-4.2$
```
CentOS Linux release 7.9.2009 (Core)

**Comment by cliqer** [comment]
...neither on windows with SQLite. 
```cmd
[4/4] Building fresh packages...
success Installed "create-directus-project@9.0.0-rc.22" with binaries:
      - create-directus-project
? Choose your database client SQLite (Beta)
? Database File Path: C:\Users\John\WebstormProjects\api.konpoli.eu\api\data.db

Something went wrong while seeding the database:

[Error] Method implemented in the dialect driver

Please try again
```

**Comment by rijkvanzanten** [comment]
> ...neither on windows with SQLite.

Pretty sure that's caused by:

https://github.com/directus/directus/issues/2904

which is unrelated to the OP

**Comment by davidsandoz** [comment]
I also got the same behaviour. No database selection and finishes without any error:
```
$ npx create-directus-project test-cms
npx : 46 installed in 5.365s

$ ls -a test-cms
extensions  node_modules  package.json  package-lock.json  uploads
```

Output of `uname -a`:
```
Linux od-a038e6 4.9.0-0.bpo.9-amd64 #1 SMP Debian 4.9.168-1+deb9u5~deb8u1 (2019-08-13) x86_64 GNU/Linux
```

**Comment by rijkvanzanten** [comment]
There must be an issue in (our use of) [`commander`](https://www.npmjs.com/package/commander) that prevents it from doing it's thing under certain flavors of Linux

**Comment by Stiropor** [comment]
I had the same issue - I don't know if this might be connected or even useful but this is what helped me (found this on Discord): https://github.com/ranisalt/node-argon2/issues/276

I rebuilt that argon2 libary and started working. Hope this help!

**Comment by davidsandoz** [comment]
I've tried a workaround by running `npx create-directus-project test-cms` locally with the DB parameters of the remote DB. This worked well and the DB got populated as expected.

Then I uploaded the files to the remote server (excluding `node_modules`), which is the Linux machine with which the `npx` command doesn't work.

There I ran `npm install` and I updated `DB_HOST` in `.env` to be `127.0.0.1` instead of the remote hostname of the server.

After that I tried `npx directus start`, but nothing happens. The commands exits without any output.

I also tried to add a `start` script in `package.json` with `directus start`, and run `npm start`, but that leads to the same result.

So it's a non-working workaround, but maybe it can help figure out the root cause.

**Comment by vitaliy-v** [comment]
The same issue with centos 7.9 (VPS hosting), after I run I see installing directus line and then normal exit like it installed. But no new line where I can choose type of DB.
Node 14.15.4, 
npm, npx 6.14.10
On windows locale machine it works.

**Comment by loganaaaflag** [comment]
We're having the same issue as @davidsandoz. No DB selection prompt on `create-directus-project`, and when we setup `.env` manually (or copy the setup from a machine that's known to work) and run `npm start` the `directus start` command exits with no message.

We're in an Azure VM running Ubuntu. `uname -a` output below:
```
Linux a3-directus 5.4.0-1036-azure #38~18.04.1-Ubuntu SMP Wed Jan 6 18:26:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by davidsandoz** [comment]
As stated by @Stiropor above, one way to fix this is to rebuild the `node-argon2` dependency, which can be done by running

```
npm rebuild argon2 --build-from-source
```

That may work in some situations, but it requires to have `cc` installed and it's not the case on my host server on which I don't have admin access.

**Comment by loganaaaflag** [comment]
Thanks for that @davidsandoz and @Stiropor - unfortunately after running that on a fresh directus project, `argon2` was rebuilt, but it didn't seem to have any affect for me :/

However, I was running this all on `node@13.0.1, npm@6.14.4` using `nvm`. I switched to `node@14.15.4, npm@6.14.10` (a fresh install using `nvm install v14`) and the `npx create-directus-server project-name` command just worked as expected. Not exactly what the fix was there, but maybe this will help someone who may experience the same issue.

**Comment by abertay-university** [comment]
I managed to get this working on Centos 7 with the following steps:

1. Make sure gcc and gcc-c++ are installed `yum install gcc gcc-c++`
2. Make sure your database of choice is installed and an empty database is created. A user with all privileges is required for directus.
3. Install some dependencies in global `npm i -g typescript rollup lerna node-pre-gyp node-gyp`
4. Go to /var/www/ and create a directus project `npx create-directus-project my-project`
5. Go into the project directory `cd my-project`
6. rebuild argon2 as suggested above `npm rebuild argon2 --build-from-source`
7. Run the initialize project script `npx directus init` this will set up the database config for you project.
8. Lastly start directus as normal `npx directus start`

**Comment by rijkvanzanten** [comment]
@abertay-university Thanks for these clear instructions!

I think we've found the underlying problem! @nathanvogel discovered an issue in his environment, which was swallowed by the CLI. That meant that it wasn't able to run, and wouldn't show what was wrong. Fixing https://github.com/directus/directus/issues/3761#issue-790290843 (which is what i'm doing right now) will most likely help out a ton in this issue as well 👍🏻

**Comment by rijkvanzanten** [comment]
The CLI will now show what went wrong during installation. If there was a problem in `argon2`, try rebuilding it using:

`npm rebuild argon2 --build-from-source`

If there's a specific issue that we can fix in Directus' CLI that's specifically related to CentOS, please open a new issue

**Comment by prikr** [comment]
> The same issue with centos 7.9 (VPS hosting), after I run I see installing directus line and then normal exit like it installed. But no new line where I can choose type of DB.
> Node 14.15.4,
> npm, npx 6.14.10
> On windows locale machine it works.

Have you managed to get this working already?

**Comment by zimkha** [comment]
I have this same problem since this morning on the installation of directus, the console simply affcieh that it did not pass but I have no details

**Comment by azrikahar** [comment]
> the console simply affcieh

I assume that means outputs or display? That said, have you tried the recommended steps shared in the comments above? 

You can also check whether your platform/hosting, node version, and database vendor/version meets the [current supported versions listed here](https://github.com/directus/directus#-requirements).

**Comment by zimkha** [comment]
Hello I have the Lts version of node 16.13.1 and version 8 of npm my server
has a ubuntu v20 system... but I still have the same error on my server I
can't install directus Le ven. 7 janv. 2022 à 07:02, Azri Kahar <
