### ISSUE TITLE
Relationship selection UI doesn't respect user-defined display template

### ISSUE THREAD

**Issue by theonlynexus** [directus/directus#3366]
Present in rc20 with MySQL, not sure about later revisions or DBs

Currently the selection interface displays all the collection's fields in the order they are specified in the table instead of the specified template.

**Table structure**
![image](https://user-images.githubusercontent.com/1515004/101720301-9285d480-3ae8-11eb-8b3d-0c54d163c39a.png)

**Many-to-one relationship with specified display template**
![image](https://user-images.githubusercontent.com/1515004/101720291-8ac63000-3ae8-11eb-801c-05bce510be6a.png)

**Relationship selection UI**
![image](https://user-images.githubusercontent.com/1515004/101720903-1db39a00-3aea-11eb-84c1-86a75ed438e6.png)

**Comment by rijkvanzanten** [comment]
The display template here is what's shown on the dropdown of the m2o, not what's visible in the list view.

The layout view that's visible in the m2o the same as how you'd look at this collection regularly, and can be configured through presets

**Comment by theonlynexus** [comment]
I am sorry but I stated the problem correctly, so you seem to have misunderstood me.

Every field in Directus has two settings:
- Interface: how the field should appear to the user when inputting it
- Display: how the field should appear to the user when being listed

If you look above, I clearly set the Interface option of the relationship field, so I expected the list to appear according to that setting, not according to the general view settings of the collection.

Please verify and hopefully re-open the bug.

**Comment by rijkvanzanten** [comment]
> I clearly set the Interface option of the relationship field, so I expected the list to appear according to that setting

That's what I'm saying.. The display template option of the many to one interface controls the preview inside the _dropdown_ of the interface. It _does not_ control what the list looks like once you are selecting an item. The view in that drawer on the right is the same as how you'd normally view that related collection, and is thus configurable through presets

**Comment by theonlynexus** [comment]
I am sorry, but then what is the display template in the "Display" section of the relationship for? I thought that was what controlled the looks of the dropdown contents...
I am kind of confused...

**Comment by benhaynes** [comment]
Displays are for how the values are shown inline throughout the App. The dropdown is the interface, so any options for controlling that are under the "Interface" section.
