### ISSUE TITLE
Decimal fields aren't created with defined precision

### ISSUE THREAD

**Issue by theonlynexus** [directus/directus#3368]
Float and decimal fields are not created with the user defined precision

**Field definition**
![image](https://user-images.githubusercontent.com/1515004/101722699-21492000-3aee-11eb-801f-69d0f38158ee.png)

**Actual table**
![image](https://user-images.githubusercontent.com/1515004/101722703-26a66a80-3aee-11eb-95c4-f464dbb17a24.png)

**Comment by maartenvn** [comment]
Hi, thanks for taking the time to create an issue.

Can you please provide your environment:

* Which DBMS are you using (MySQL, Postgres, ...)
* Which deployment are you using (npx, docker, ...)

**Comment by theonlynexus** [comment]
Hi, this is an rc20 docker install backed by MySQL

2020년 12월 10일 (목) 오후 5:33, Maarten Van Neyghem <notifications@github.com>님이
작성:
