### ISSUE TITLE
Database migration routine always exits with `1`

### ISSUE THREAD

**Issue by gtriggiano** [directus/directus#3370]
I noticed that the routine in `./api/src/cli/commands/database/migrate.ts` exits the process with `1` even on succesful migrations.

In my CD automation the migration command is invoked just before deploying the new release. As exit code `1` means failure the whole CD pipeline breaks on that step.

I would consider this a bug, unless I'm missing something and this behavior has been intentionally coded.

**Comment by gtriggiano** [comment]
Just opened https://github.com/directus/directus/pull/3371 in case you would like to fix this. Thanks.

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/directus/pull/3371
