### ISSUE TITLE
[RC21] Field Validation leads to Internal Server Error

### ISSUE THREAD

**Issue by h2bear** [directus/directus#3375]
if i use Field Validation to ensure there is a user who can just add other users by a special role i get the following error:

```
{
    "errors": [
        {
            "message": "Cannot convert undefined or null to object",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}
```

My Steps to reproduce:

i add custom permissions for this user to the "directus_users" collection for "create" and set a field validation:

```
{
    "role": {
        "_eq": "ROLE_ID"
    }
}
```

Error occurs now by trying to create a new user, without the field validation there is no error

**Comment by aaron-manning** [comment]
Getting this error in 9.4.3 and 9.5 when trying to add validation to directus_users to stop admins from being able to make more admin users.

```
{
	"_and": [
		{
			"role": {
				"admin_access": {
					"_eq": false
				}
			}
		}
	]
}
```

```
{
    "errors": [
        {
            "message": "\"role\" must be of type object",
            "extensions": {
                "code": "FAILED_VALIDATION",
                "field": "role"
            }
        }
    ]
}
```
