### ISSUE TITLE
Oauth doesn't works

### ISSUE THREAD

**Issue by pulsarpoint** [directus/directus#3380]
Hi, 

I tried to connect the new instance of directus to github as an auth provider. I guess the only configuration that's needed for successful connection to external OAuth provider specified in "grant" package is to add these lines in .env file.

OAUTH_PROVIDERS="github"
OAUTH_GITHUB_KEY="d3bbdeac5c6558585edf"
OAUTH_GITHUB_SECRET="***************************************"

when I click on the link for Github authentication, the request is redirected to the:
http://localhost:8055/auth/oauth/github?redirect=http://localhost:8055/admin/login

where I get an empty page. Last request in the console:

22:22:56 ✨ request completed GET 200 /auth/oauth/github?redirect=http://localhost:8055/admin/login 30ms
no redirection to the GitHub auth page has occurred.

**Comment by danieljwestman** [comment]
You need to tell Directus what url/endpoint to get the auth code/token from?

Like https://github.com/login/oauth/authorize

**Comment by pulsarpoint** [comment]
But isn't that information stored in grant package which is used by directus to perform OAuth handshake. These parameters are defined in grant/conf/oauth.json file. And there are url's for ~200 OAuth providers. 

As I see in code there are only OAuth providers that have to be specified in .env file, then Directus use that parameter to get url's from grant package. Or I looking in the wrong place.

**Comment by danieljwestman** [comment]
Aha, okay. That sound about right.

Hope you can get some assistance from the core team here.

**Comment by theonlynexus** [comment]
Having the same issue on rc22 on docker

**Comment by chomamateusz** [comment]
@rijkvanzanten any update on that? or any workaround? it is possible to overwrite that `/oauth/:provider` with valid implementation?

**Comment by rijkvanzanten** [comment]
@theonlynexus That checks if the provider exists, and returns a 404 if it doesn't. The problem here is that `respond` at the end. It should only call next, and have it be handled by the next router:

`router.use(grant.express()(grantConfig));`

**Comment by B-Esmaili** [comment]
I am trying to integrate `next-auth` with `directus`, previously I had done it with strapi following [this article](https://nirmalyaghosh.com/articles/2020-10-06-authentication-in-next-js-with-strapi-and-next-auth). I noticed directus offers a similar endpoint (`/aut/oauth/<provider>/callback`) to verify OAuth tokens but when I submit the token to that endpoint I get error message mentioned in this issue. Am I using the right endpoint? Does directus support this kind of authentication workflow at all?

**Comment by benhaynes** [comment]
> I am trying to integrate `next-auth` with `directus`, previously I had done it with strapi following [this article](https://nirmalyaghosh.com/articles/2020-10-06-authentication-in-next-js-with-strapi-and-next-auth). I noticed directus offers a similar endpoint (`/auth/oauth/<provider>/callback`) to verify OAuth tokens but when I submit the token to that endpoint I get error message mentioned in this issue. Am I using the right endpoint? Does directus support this kind of authentication workflow at all?

@B-Esmaili — this should be a new GitHub Discussion, not a comment on an already closed ticket.

**Comment by B-Esmaili** [comment]
> > I am trying to integrate `next-auth` with `directus`, previously I had done it with strapi following [this article](https://nirmalyaghosh.com/articles/2020-10-06-authentication-in-next-js-with-strapi-and-next-auth). I noticed directus offers a similar endpoint (`/auth/oauth/<provider>/callback`) to verify OAuth tokens but when I submit the token to that endpoint I get error message mentioned in this issue. Am I using the right endpoint? Does directus support this kind of authentication workflow at all?
> 
> @B-Esmaili — this should be a new GitHub Discussion, not a comment on an already closed ticket.

Sorry I had multiple GitHub windows open I accidentally posted on wrong post.
