### ISSUE TITLE
Use `db-safe` for repeater `field` option

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#3391]
Right now it's a regular input. This value is used as key in the JSON value

**Comment by YannickMol** [comment]
Not sure where to find this. @rijkvanzanten, can you guide me in the right direction?

**Comment by rijkvanzanten** [comment]
@YannickMol The `v-input` component has a `db-safe` attribute you can use to only allow input that is safe for use in the database:

https://github.com/directus/directus/blob/d56b8cf836a7a30ca35bedad2b19c9ad24fc2681/app/src/components/v-input/v-input.vue#L124-L127

We should probably add an option to the `text-input` interface to expose that db-safe attribute as an option:

https://github.com/directus/directus/blob/d56b8cf836a7a30ca35bedad2b19c9ad24fc2681/app/src/interfaces/text-input/index.ts#L11

 and then use that option in the `field` option for the repeater interface:

https://github.com/directus/directus/blob/d56b8cf836a7a30ca35bedad2b19c9ad24fc2681/app/src/interfaces/repeater/options.vue#L79
