### ISSUE TITLE
Duplicate field: auto focus on name, enter to submit

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#3392]
Makes it just that little nicer to use

**Comment by mrbenosborne** [comment]
Want me to pick this up?

**Comment by benhaynes** [comment]
Yeah! That would be great... 😄

**Comment by mrbenosborne** [comment]
I tried bringing up the project but got a bunch of errors relating to db client, I'm using MySQL, I'll give it another go at the weekend.

**Comment by benhaynes** [comment]
Hey @mrbenosborne — all our general MySQL errors should be squashed, in case you had time to give this another try! :)

**Comment by mrbenosborne** [comment]
Great, I'll give it another go

**Comment by benhaynes** [comment]
Awesome, thank you!!
