### ISSUE TITLE
Installation fails with ER_PARSE_ERROR when using MariaDB 10.1+

### ISSUE THREAD

**Issue by 3logy** [directus/directus#3399]
Hello i have an issue when installing directus 9.0.0-rc.22 

1) The issue and what you expected to happen
    The installation fails when creating the migrations table because of json data type (https://mariadb.com/kb/en/json-data-type/)

2) Exact steps to reproduce this issue
    run: yarn create directus-project . 

3) Your environment:
    Which DBMS are you using (MariaDB 10.1.47).
    Which deployment are you using (npx, yarn).
    What browser are you using (Chrome 87).

<img width="1456" alt="grafik" src="https://user-images.githubusercontent.com/745075/101959451-a70bbf00-3c05-11eb-972d-383839c42a38.png">

**Comment by rijkvanzanten** [comment]
Directus only supports MariaDB 10.2 and up (just updated the docs to reflect this). We aim to support actively maintained versions of the third party software, and MariaDB 10.1 is officially end of life as per October 2020 (see https://mariadb.org/about/#maintenance-policy)
