### ISSUE TITLE
Presets List: Column "name" is showing JSON string after change lang

### ISSUE THREAD

**Issue by soyjimmysaenz** [directus/directus#3401]
Hello,

Currently @ `admin/settings/presets` there is a table with the column **Name**. if I change the language from `en-US` to something else (e.g: es-ES), every cell of that column shows a **JSON string** instead of the word **default**.

![bug1](https://user-images.githubusercontent.com/1390475/101968539-4e2c2e80-3be5-11eb-86b0-15d6be2ff7f9.jpg)

The Vue component is [/settings/routes/presets/collection/collection.vue](https://github.com/directus/directus/blob/main/app/src/modules/settings/routes/presets/collection/collection.vue#L81)

I was looking for the bug and I think it happens in the following line (`src/lang/index.ts`):

```
const translations = await import(`@/lang/translations/${lang}.yaml`).catch((err) => console.warn(err));
```

Using that sentence, the **module object** is created with a `default property` and that would explain the weird behavior with that specific word (default)

Hope this helps, I don't create a PR because I do not know if the best/quick fix would be just change the word (maybe `defaults`) on every YAML file.

## Project details

Directus Version: 9.0.0-rc.22
Environment: development
OS: Windows 10
Node: 14.15.1

**Comment by benhaynes** [comment]
Oh man.. those scroll bars in the module/nav!! 😐

**Comment by rijkvanzanten** [comment]
This was added in #3447

**Comment by rijkvanzanten** [comment]
> Oh man.. those scroll bars in the module/nav!! 😐

It overflow scrolls when the list is taller than what fits in the container, so this must be a _long_ list or _tiny_ screen 😁
