### ISSUE TITLE
Adding/Changing filters for presets does not work immediately

### ISSUE THREAD

**Issue by eXaminator** [directus/directus#3402]
When creating a new preset I do the following:

1. Select a collection
2. Select any scope
3. Select "Table" layout

Now I proceed to add an advanced filter:
1. Open the select with the filed names
2. Select any field

Result: The select closes, but the filter is not added (is simply doesn't show up as if I never added it).

Now, if I change to any other scope the filter will suddenly show up. This seems to be reproducible no matter which scope I select initially or which scope I change to after trying to add a filter.

Some more observations:
- It does not change anything if I change the scope twice before adding a filter
- It does not change anything if I select the layout before selecting a scope

**Comment by MichaelNussbaumerGOWEST** [comment]
I am on RC23 and I wasn't able to reproduce this issue.

@eXaminator do you have any additional input like logs which helps to reproduce the issue.

**Comment by eXaminator** [comment]
I wish I could. It's still happening to me in rc.23 and there are not errors or any other logs on my console when doing this.

But here is a video showing the behavior, maybe it helps:
https://www.dropbox.com/s/thstnqhrohg5os3/DirectusFilterBug.mp4?dl=0

Any additional pointers of where to look to find out anything are appreciated and I'll see if I can find out anything. I also switched my locale to english, just to be sure, but it didn't do anything.

**Comment by MichaelNussbaumerGOWEST** [comment]
@eXaminator ah, my fault. I checked it on the collection overview. I got the same behaviour here. Just checked it on the wrong route.
