### ISSUE TITLE
Support fragments (GraphQL)

### ISSUE THREAD

**Issue by eXaminator** [directus/directus#3405]
I was just playing around with the graphQL endpoint and noticed, that the server does not seem to properly support fragments for some reason.

Here is a simple example:

The following works as expected:
```
query {
  items {
    bsf_pages {
      id
    }
  }
}
```

which results (as expected) in something like this:
```
{
  "data": {
    "items": {
      "bsf_pages": [
        {
          "id": 1
        },
        {
          "id": 2
        }
      ]
    }
  }
}
```

But the following query does not work the same way (though imo it should):

```
fragment pageData on bsf_pages {
  id
}

query {
  items {
    bsf_pages {
      ...pageData
    }
  }
}
```

This results in:
```
{
  "data": {
    "items": {
      "bsf_pages": [
        {
          "id": null
        },
        {
          "id": null
        }
      ]
    }
  }
}
```

I'm not sure what is going on here, but I guess it might have something todo with typing?
This seems to be true for all fields in that collection.

**Comment by rijkvanzanten** [comment]
This was added in https://github.com/directus/directus/pull/3852
