### ISSUE TITLE
Invalid date format when editing the date_created field of an existing item

### ISSUE THREAD

**Issue by cor-vo** [directus/directus#3412]
Hi,

We're migrating content from an existing website to Directus. We also have some news items where the creation date lays in the past. When you expose the date_created field on the edit page of an item and edit an existing item inside directus you'll get an invalid datetime format error.

This only occurs when editing an existing item, when you create a new item and leave the field empty or set it to an other date the error doesn't occur.

We're running Directus RC23 running on a Mariadb database server.

**Comment by irishburlybear** [comment]
I just ran into this issue.

**Comment by rijkvanzanten** [comment]
@cor-vo Could you share an example of the format the date is stored in before it was edited by Directus?

**Comment by cor-vo** [comment]
@rijkvanzanten Did a new test on version v9-rc.30.

Steps to reproduce:


1. Create a new collection
2. Enable the default date_created field.
3. Enable ```Show field on Detail``` on the date_created field.
4. Disable the ```On create``` option
5. Disable read only.

Now when you create a new item you have the option to set a custom date_create field with a datepicker. 

When you enter a date or click ```Set to now``` and save the new item you'll get the following error:

<img width="519" alt="Screenshot 2021-01-21 at 20 50 05" src="https://user-images.githubusercontent.com/244885/105405172-217b2600-5c2b-11eb-951f-d674a755f2ca.png">

**Comment by rijkvanzanten** [comment]
Closed in favor of https://github.com/directus/directus/issues/3655
