### ISSUE TITLE
Extend validation 

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#3420]
Directus' validation only supports "simple" object structures, like

```json
{
  "field": {
    "_eq": "value"
  }
}
```

we should extend this with the same support for nesting and logical operators as filters and permissions

**Comment by mazero** [comment]
yes for example filter by user who have a relationship with a specific company data model with dynamic values...but how can we create or access at of the list of dyamic values ? thx

**Comment by benhaynes** [comment]
Ref: https://github.com/directus/directus/discussions/2993
Ref: https://github.com/directus/directus/discussions/3914
