### ISSUE TITLE
Update docs to include schema

### ISSUE THREAD

**Issue by erik-konrad** [directus/directus#3423]
If I create a new custom endpoint like in the documentation (https://docs.directus.io/guides/extensions/api-endpoints.html#_3-restart-the-api) the Endpoint is not working. 

Error: 
`
13:42:29 ⚠️  Couldn't register endpoint "recipes"
13:42:29 ⚠️  Cannot read property 'knex' of undefined
`

Tested on ddev environment. directus version: ^9.0.0-rc.23

**Comment by gulshan11** [comment]
I do have the same issue.

**Comment by rijkvanzanten** [comment]
You need to provide the `schema` to the service:

```js
...

new ItemsService('xxx', { schema: req.schema }});

...
```

**Comment by rijkvanzanten** [comment]
This was since added 👍🏻 

https://docs.directus.io/guides/api-endpoints/#full-example
