### ISSUE TITLE
There is no way to clear the value of a date picker

### ISSUE THREAD

**Issue by theonlynexus** [directus/directus#3429]
I wasn't sure whether to input this as a bug or feature request, please excuse me if I chose the wrong category.

1) There is no way to clear the value of a date picker (I am assuming datetime picker too) 

2) Exact steps to reproduce this issue
- Have a record with a date field and value, where the field value is not required
- Try removing the date value before "Save as copy"

3) Your environment:
   rc20 on docker backed by MySQL

4) Suggestion:
  Like there is a "Set to now" button, add a "Clear field" button if the field is not required.

**Comment by rijkvanzanten** [comment]
![CleanShot 2020-12-16 at 09 55 55](https://user-images.githubusercontent.com/9141017/102364839-e5e2a180-3f84-11eb-9f88-58e3bdad9b79.png)

Every field has a "Clear Value" option 🙂 

Regardless, I agree it's nice to have a dedicated `x` button on the right of the interface 👍

**Comment by theonlynexus** [comment]
As a follow up:
Now that you pointed it out I managed to see the arrow that indicates the contextual menu, but I think that the fact that it is invisible until one hovers over the field's name is really bad design.

Please consider making it permanently visible and, maybe, replacing it with an hamburger or triple dots.

**Comment by rijkvanzanten** [comment]
> the fact that it is invisible until one hovers over the field's name is really bad design.

Without any deeper explanation as to why you think this (regardless of whether or not I agree with you), I'll have to consider this an opinion and a bit of an hyperbole..

**Comment by theonlynexus** [comment]
The explanation is that it is invisible unless one hovers over the element: I never put my mouse over the field name before you shared your image because it doesn't look interactive in any way.
Also, think about mobile users: they have no way to hover, so they would need to know about the feature in advance.
To me it clearly is a usability issue, hopefully my reasoning makes sense.

**Comment by rijkvanzanten** [comment]
Yes it totally does, and I kinda assumed that's what you were going for. Without that explanation though, I can't know where you're coming from or why I should take your proposed changes into account 🙂

**Comment by theonlynexus** [comment]
I just found about this [Dave Hogue's presentation on Interaction Design](http://www.idux.com/downloads/MAX2010_HOGUE_Interaction_Design_Principles.pdf).

It is a very good read and, although I am sure you guys already know him and his work, I though it might be worth sharing.

**Comment by benhaynes** [comment]
Thanks @theonlynexus! While I agree about the "clear value" being an important feature that shouldn't be hidden, the other options are simply helpers, and I'm fine with them being more _discoverable_. I think that all interfaces should offer a native way to clear the value... and this is simply a reliable fall back.

There's a balance to usability and UX/UI clutter, and I think what we have now is an acceptable learning curve. Always down to discuss though!

To resolve the ticket, we need to add the native "x" to this interface.
