### ISSUE TITLE
Unsaved changes dialog pops up when clicking "Save as copy"

### ISSUE THREAD

**Issue by theonlynexus** [directus/directus#3430]
1) Description:
Clicked "Save as copy", expected the usual green confirmation popup, instead got the "Unsaved changes" dialog.

2) Steps to reproduce:
I am not entirely sure, but this seems to happen on records that were input in the DB directly via SQL and not via the app.
I tried filling in the user_created, date_created, user_user modified and date_modified to see if that was the cause of the issue, but no luck.

3) Your environment:
rc20 on docker backed by MySQL

Sorry about the mosaic in the GIF below, but the data is confidential and I couldn't replicate the issue in other simpler test databases that I setup. If more information is needed, please let me know.

![directus_save_as_copy_bug gif](https://user-images.githubusercontent.com/1515004/102316386-2a883000-3fb9-11eb-9420-823dd6665bd5.gif)

**Comment by theonlynexus** [comment]
I can confirm the bug in rc22 on Docker + MySQL

**Comment by rijkvanzanten** [comment]
@theonlynexus Would it be possible to share a DB dump of just the schema? I'm trying to reproduce it on my end, but am not able to..

**Comment by theonlynexus** [comment]
> @theonlynexus Would it be possible to share a DB dump of just the schema? I'm trying to reproduce it on my end, but am not able to..

I had meant to do an anonymized dump for the past few days but have been caught up with work. I'll take care of it today.

**Comment by theonlynexus** [comment]
@rijkvanzanten  In the meantime here is the schema.

https://pastebin.pl/view/0fb32d4d

**Comment by theonlynexus** [comment]
@rijkvanzanten Sorry but I have been very busy and I only managed to dump and sanitize the data today. I have anonymized everything I can, but I had to drop the contents of the revisions, sessions and presets tables. I hope it is not an issue.

[directus_copy_no_rev.zip](https://github.com/directus/directus/files/5848306/directus_copy_no_rev.zip)

**Comment by rijkvanzanten** [comment]
No problem! Super busy here as well 🙂 

This helps out a lot, thanks!

**Comment by rijkvanzanten** [comment]
@theonlynexus I think it might've been caused by a validation error in a hidden field, I'm seeing this once I click keep-editing:

![CleanShot 2021-01-29 at 17 59 16](https://user-images.githubusercontent.com/9141017/106335902-b8636600-625b-11eb-9f85-12065932d4e1.png)

Lemme make sure it doesn't try navigating on validation errors on _save as copy_ 👍🏻
