### ISSUE TITLE
floats with more than 2 decimals not possible

### ISSUE THREAD

**Issue by julrei** [directus/directus#3431]
There is no datatype which would represent for example latitude and longitude values. Float datatype only with 2 decimals in database. Precision settings are ignored.

---

### Project details
Directus Version: 9.0.0-rc.23
Environment: production
OS: Linux 4.18.0-147.8.1.el8_1.x86_64
Node: 15.4.0

**Comment by benhaynes** [comment]
The root cause is the precision, which I think was resolved (but not released) with this: https://github.com/directus/directus/issues/3368
