### ISSUE TITLE
Translations field does not show related values

### ISSUE THREAD

**Issue by shi-rudo** [directus/directus#3432]
Postgres 13.1,
Docker version 20.10.0, docker-compose version 1.27.4
Directus v9.0.0-rc.23

After creating the translation field (and setting it up) the interface does only show the related values and not the actual related entries.

1. Translation do exist
![Image](http://www.dlds.de/pub/lang/list.jpg)

2. But it does display only the list of languages codes
![Image](http://www.dlds.de/pub/lang/error.jpg)

3. Changing the interface setting does not help. Also selecting no value does only display the list of lang code
![Image](http://www.dlds.de/pub/lang/setting.jpg)
![Image](http://www.dlds.de/pub/lang/setting2.jpg)

4. It **should** look like this❗️
![Image](http://www.dlds.de/pub/lang/should.jpg)

**SQL DUMP**
http://www.dlds.de/pub/lang/dump.sql

**UPDATE:**
If I set the displayed value to "id". They also disappear from the list view. Only by setting the "raw value"  the ids reoccur on the list view. Maybe this phenomenon is related to the interface problem.

**Comment by shi-rudo** [comment]
**workaround:** by setting the database interface value to null in can force the desired interface:

![Image](http://www.dlds.de/pub/lang/workaround.jpg)

**Comment by benwalch** [comment]
I have the same problem.
The display template in the section "Interface" does work.
The configuration below
<img width="948" alt="Screenshot 2021-01-03 at 09 51 16" src="https://user-images.githubusercontent.com/7903333/103474983-6852ca00-4da9-11eb-8256-1827ae985039.png">
changes the interface as follows:
<img width="832" alt="Screenshot 2021-01-03 at 09 43 46" src="https://user-images.githubusercontent.com/7903333/103474989-8a4c4c80-4da9-11eb-8175-06d33d1790e6.png">

**BUT**
I want to see a summary of the translated values in the interface. It seems this is not supported so far? I played around a bit and it seemed that configuring the "Display" section only affects the value being displayed in the table view, but this does not work either. The configuration below
<img width="946" alt="Screenshot 2021-01-03 at 09 51 32" src="https://user-images.githubusercontent.com/7903333/103475043-0d6da280-4daa-11eb-9f4b-d7e0171dabb3.png">
leads to this (in the table view)
<img width="183" alt="Screenshot 2021-01-03 at 09 44 02" src="https://user-images.githubusercontent.com/7903333/103475045-19596480-4daa-11eb-9bf6-5ee8b748aa65.png">

**AWESOME** would be:
To configure a display template for the interface, to see a **summary** of the translated fields for each language. I modified the screenshot from above to show what I mean. This would make the most sense and would simplify work for editors, when changing their model translations. Should I open an extra feature request for this?
What do you think about this?
<img width="841" alt="Screenshot 2021-01-03 at 10 02 20" src="https://user-images.githubusercontent.com/7903333/103475160-ebc0eb00-4daa-11eb-94a3-ec7215408e3d.png">

**Comment by altezza04** [comment]
This seem to be important, especially for editor to view which content need to update in single page, instead of click on each translation

**Comment by rijkvanzanten** [comment]
> AWESOME would be:
> To configure a display template for the interface, to see a summary of the translated fields for each language. I modified the screenshot from above to show what I mean. This would make the most sense and would simplify work for editors, when changing their model translations. Should I open an extra feature request for this?
> What do you think about this?

I love it! No need to open a feature request 😉 

I went ahead and implemented it basically exactly the way you described / designed it 🙂 

<img width="771" alt="Screen Shot 2021-05-24 at 8 48 00 PM" src="https://user-images.githubusercontent.com/9141017/119423463-55e21a00-bcd1-11eb-8150-feee193ac8f7.png">

Based on two display templates:

<img width="641" alt="Screen Shot 2021-05-24 at 8 48 27 PM" src="https://user-images.githubusercontent.com/9141017/119423486-672b2680-bcd1-11eb-9426-d2d837aa6206.png">
