### ISSUE TITLE
Filtering on nested objects does not work

### ISSUE THREAD

**Issue by shi-rudo** [directus/directus#3434]
Postgres 13.1,
Docker version 20.10.0, docker-compose version 1.27.4
Directus v9.0.0-rc.23

As soon as I start to use GraphQl to filter on deeper nested objects the filtering does fail. 

Collection
--> relation (does work)
--> relation --> relation (does not work)

I've build an example dump where you can replicate the issue. 

✔️✔️✔️ This query does work:

```graphQl
query{
    items {
        articles {
            id
            title
            translations(filter: {languages_code: {code: {_eq: "de-DE"}}}) {
                id
                headline
                languages_code {
                    code
                    name
                }
            }
        }
    }
}
```

RESULT: Does only display the wanted translations passed by filter "de-DE"
```json
{
    "data": {
        "items": {
            "articles": [
                {
                    "id": "15b6bc45-5abf-4a46-bf11-031fe4cc77b9",
                    "title": "my second article",
                    "translations": [
                        {
                            "id": "4",
                            "headline": "mein zweiter artikel",
                            "languages_code": {
                                "code": "de-DE",
                                "name": "German"
                            }
                        }
                    ]
                },
                {
                    "id": "f980ebb7-6624-430b-a2a7-c27e65fd6e9d",
                    "title": "my first article",
                    "translations": [
                        {
                            "id": "7",
                            "headline": "mein erster article",
                            "languages_code": {
                                "code": "de-DE",
                                "name": "German"
                            }
                        }
                    ]
                }
            ]
        }
    }
}
```

❌❌❌ This query does not work on filtering:  Does NOT only display the wanted translations passed by filter "de-DE". Instead all languages are returned.

```graphQl
query{
    items {
        ingredients {
            id
            reference_object {
                id
                translations(filter: {languages_code: {code: {_eq: "de-DE"}}}) {
                    id
                    title
                    languages_code {
                        code
                        name
                    }
                }
            }
        }
    }
}
```

```json
{
    "data": {
        "items": {
            "ingredients": [
                {
                    "id": "52e3dffb-7c8b-4f06-bfbc-26da4d1c5b96",
                    "reference_object": {
                        "id": "1939a0d8-0ff6-41ed-9f04-dba50fe12fe2",
                        "translations": [
                            {
                                "id": "1",
                                "title": "Butterfish",
                                "languages_code": {
                                    "code": "de-DE",
                                    "name": "German"
                                }
                            },
                            {
                                "id": "2",
                                "title": "escolar",
                                "languages_code": {
                                    "code": "en-US",
                                    "name": "English"
                                }
                            }
                        ]
                    }
                },
                {
                    "id": "527c4828-f2c5-49c4-8c1e-894edcd2d212",
                    "reference_object": {
                        "id": "943c0bd8-a6c7-486b-94b8-d209fb56f4c3",
                        "translations": [
                            {
                                "id": "3",
                                "title": "Lemon",
                                "languages_code": {
                                    "code": "en-US",
                                    "name": "English"
                                }
                            },
                            {
                                "id": "4",
                                "title": "Zitrone",
                                "languages_code": {
                                    "code": "de-DE",
                                    "name": "German"
                                }
                            },
                            {
                                "id": "5",
                                "title": "Citronnier",
                                "languages_code": {
                                    "code": "fr-FR",
                                    "name": "French"
                                }
                            },
                            {
                                "id": "6",
                                "title": "レモン",
                                "languages_code": {
                                    "code": "jp-JP",
                                    "name": "Japanese"
                                }
                            }
                        ]
                    }
                }
            ]
        }
    }
}
```

The sql dump
http://www.dlds.de/pub/query/dump.sql

**Comment by TammyLopez** [comment]
same here, current workaround is not to use nested relations. would be nice if a bugfix comes soon :)

**Comment by Oreilles** [comment]
I just faced the same issue in the user interface.
In the sidebar if you click `Add filter` then select a non relation field, a new input row is appened. But if you select a relation field instead, nothing happens. No error.

**Comment by nathanvogel** [comment]
I think I'm facing the same issue over the REST API.
Sorting also doesn't seem to work.

**Comment by TheOneAndOnlyGarcia** [comment]
+1

this problem is not a dealbreaker, but it is quite annoying, as it forces us to unnecessarily inflate the business logic of the backend or frontend. 

@rijkvanzanten is there an eta regarding the solution of this bug?

**Comment by rijkvanzanten** [comment]
[**Unfortunately, we can not provide estimates on features or fixes**](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍 . Or contribute a pull-request... after all, this is OSS!

**Comment by TheOneAndOnlyGarcia** [comment]
if it sounded rude, I sincerely apologise. of course i understand that you have limited resources. we are a group of students who use your cms day in and day out and appreciate it very much. keep up the great work, directus is awesome!

**Comment by benhaynes** [comment]
No worries! Just our generic auto-response for ETA requests (we get a lot of them)... ❤️

**Comment by rijkvanzanten** [comment]
> if it sounded rude, I sincerely apologise. of course i understand that you have limited resources. we are a group of students who use your cms day in and day out and appreciate it very much. keep up the great work, directus is awesome!

Appreciate it 🙂 

I think this might actually be caused by the fact that the GraphQL services uses `deep` to enable these nested filters, but that `deep` itself doesn't support "double-nested" queries yet (in OPs case  ingredients->reference_object->translations) https://github.com/directus/directus/issues/3919

**Comment by CapitaineToinon** [comment]
Any news on this? I've been trying something similar, the REST equivalent works just fine like this, to filter `category` based on the name of the nested object `game` : 

```
/items/category?filter[game][name][_eq]=DarkSouls
```

But when I try something like this with graphql, it filters the game by replacing the value by `null` but doesn't filter the category out. Any other attempts at filtering that I could think of just results in an error. 

```
query {
    category {
      id
      name
      game(filter: { name: { _eq: "Dark Souls" } }) {
        id
        name
      }
    }
  }
```

outputs: 

```
0: {id: 1, name: "Any%", game: {id: 1, name: "Dark Souls"}}
1: {id: 2, name: "Any%", game: null}
```

Item 1 here didn't match and should be removed, but isn't. 

I know I could just use the REST endpoint but I'd love to use graphql everywhere in my app and not a mix of both if possible.

**Comment by rijkvanzanten** [comment]
@CapitaineToinon It's the difference between 

_"Get me all categories that have a nested game called Dark Souls"_

and

_"Get me all categories, but only nest the game if it's called Dark Souls"_

🙂 

The same actually applies to the REST API: \
The first would be the example you shared:

`/items/category?filter[game][name][_eq]=Dark Souls`

The second would be

`/items/category?deep[game][_filter][name][_eq]=Dark Souls`
