### ISSUE TITLE
Search function doesnt work with UUID field

### ISSUE THREAD

**Issue by goggi** [directus/directus#3443]
Hi!

When I try to search with a UUID string on a UUID field in the Search function it doesn't return any results.

![image](https://user-images.githubusercontent.com/1946339/102480478-9c678480-4060-11eb-9323-ce2652085f9a.png)
![image](https://user-images.githubusercontent.com/1946339/102480522-ad17fa80-4060-11eb-8bbf-2b44b1379632.png)

If I use the Advanced filter function and set the condition to equals it works, it doesn't work with contains. 
![image](https://user-images.githubusercontent.com/1946339/102480580-c1f48e00-4060-11eb-89e5-ea45a77461bf.png)
![image](https://user-images.githubusercontent.com/1946339/102480639-d46ec780-4060-11eb-9abe-6071aa30499a.png)

Might not be a bug if it's intended to work like this, but I thought I would bring it up.

---

### Project details
Directus Version: 9.0.0-rc.23
Environment: production
OS: Linux 4.15.0-88-generic
Node: 14.7.0

**Comment by shlaing** [comment]
By the way, Export data function works for you?

**Comment by goggi** [comment]
> By the way, Export data function works for you?

I just did a test, and it seems to work fine with JSON format, but CSV seems a bit buggy

**Comment by rijkvanzanten** [comment]
Note to self: Postgres doesn't seem to like searching with LIKE in a UUID type

**Comment by Oreilles** [comment]
> Note to self: Postgres doesn't seem to like searching with LIKE in a UUID type

https://github.com/directus/directus/blob/909417151710fadcfca7ddd813df7f122d137156/api/src/utils/apply-query.ts#L49

```javascript
this.orWhereRaw(`LOWER(??) ~ ?`, [column.column_name, `.*${query.search!}.*`]); 
```

Maybe that would work ? I tried to test it but I'm facing `Proxy error: Could not proxy request / from localhost:8080 to http://localhost:8055/ (ECONNREFUSED).`when running `npm run dev` after following the contributing docs.

**Comment by benhaynes** [comment]
Rijk is closing this by allowing a direct (`==`) search, but if we want a `LIKE` search for partials, then we would need to cast the UUID as text... which would require getting casting abstracted in knex (or our fork of knex).

https://stackoverflow.com/questions/46433459/postgres-select-where-the-where-is-uuid-or-string
