### ISSUE TITLE
Check if columns exist before querying on them

### ISSUE THREAD

**Issue by apstanisic** [directus/directus#3444]
Send GET request with filter for non existing field. This should return 400 Bad Request, because it's user's error, not server's.

```ts
sdk
      .items("test")
      .read({ filter: { ids: "value" } })
      .then(console.log);
```

Requested url: `http://localhost:8055/items/test/?filter=%7B%22ids%22:%22value%22%7D`
Response: 
```json
{"errors":[{"message":"select \"test\".\"id\", \"test\".\"val\" from \"test\" where (\"test\".\"ids\" = $1) limit $2 - column test.ids does not exist","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}
```

Postgres 12, Directus RC24, npx

**Comment by rijkvanzanten** [comment]
The SDK now helps prevent this situation, but the API hasn't been updated yet to return a 400 instead of 500

**Comment by rijkvanzanten** [comment]
This has since been addressed. The API only queries the database for fields that actually exists as columns. Invalid names are ignored
