### ISSUE TITLE
filters _nnull, _null, _empty, _nempty require boolean value, but don't use it

### ISSUE THREAD

**Issue by apstanisic** [directus/directus#3448]
API requires that we provide boolean for this filter, but it just ignores provided value. Users might think that value can reverse operation. But id does not do anything

https://github.com/directus/directus/blob/5024493f6938586a13b675ae0fde7a5824be0bca/api/src/utils/apply-query.ts#L197

**Comment by rijkvanzanten** [comment]
Cause there's only one available option: on or not, which is the difference between no query params, or `?filter[field][_empty]`. In the SDK/GraphQL, it needs a value, so `true` is the best option there IMO

Are you referring to the typing in the SDK here when you say "API requires that we.." ?

**Comment by apstanisic** [comment]
It requires that we pass valid boolean. If we don't it throws 400.

https://github.com/directus/directus/blob/5024493f6938586a13b675ae0fde7a5824be0bca/api/src/utils/validate-query.ts#L68

**Comment by rijkvanzanten** [comment]
Orrr

> User might expect that it will reverse result

We can make it reverse the result!

**Comment by apstanisic** [comment]
That's cool idea! Should I create PR? 🙂

**Comment by rijkvanzanten** [comment]
Sure thing!
