### ISSUE TITLE
Custom collection over 9 signs cannot resolve type

### ISSUE THREAD

**Issue by sembsa** [directus/directus#3449]
Issue exists in graphQL extension. In case of configuring relation there's only possible to use collections which length is no longer than 9. This limitation provides isses in case of using database tables that are used next to directus tables. 

For example table employee_details cannot be resolved and throws error.  In code mentioned below You can find that substring is used. Is there any reason why it's like this? because rebuilding existing database is not an option (in bigger project this limitation is devastating DB).

In file graphql.ts:
`const relatedType = relatedIsSystem
? schema[relationForField.one_collection!.substring(9)].type
: schema.items[relationForField.one_collection!].type;`

**Comment by rijkvanzanten** [comment]
I'm not sure what you're talking about.. The explanation doesn't seem to match your reported issue 🤔 

This bit:

```js
const relatedType = relatedIsSystem ? schema[relationForField.one_collection!.substring(9)].type : schema.items[relationForField.one_collection!].type;
```

means that it removes the `directus_` part from the name when accessing a system collection as a type, as the type for `directus_users` is saved/used as `users` in the context of the GraphQL service.

What do you mean by

> **In case of configuring relation** there's only possible to use collections which length is no longer than 9

what relation?

**Comment by sembsa** [comment]
Thank You for You answer it helped us. Most probably we get an error when we've tried to join to directus_* tables. 
Currently we are using directus_user table to join our tuseruser table and we'll handle this in differrent way, because we just use wanted to have all relations but this one is not needed. 

Thank You, 
Most probably issue on our side in understanding relation o2m and its config.
