### ISSUE TITLE
Numeric fields can't be cleared

### ISSUE THREAD

**Issue by eXaminator** [directus/directus#3450]
Optional numeric fields cannot be cleared after a value was set. Once saved they will be changed to 0 (but should be empty / NULL).

This is also true for internal numeric fields, like the min or max settings for said integer fields. Once I have set a minimum value for a numeric field I can no longer remove it and it will always reset to 0, thus requiring a minimum number of 0 for that input.

The app also doesn't differentiate between 0 and an empty input, as the save button of a collection item will stay disabled (as if the item is unchanged) if I try to delete a 0 from a numeric field.

**Comment by benhaynes** [comment]
Ref: https://github.com/directus/directus/issues/3429

The same applies here. You can click the field label to reset any field, but all of these interfaces need a native "clear" button.

**Comment by rijkvanzanten** [comment]
> but all of these interfaces need a native "clear" button.

I don't agree in the context of a numeric field. The numeric interface should stage an empty input as `null`, and a value as the value 🙂 (no need for a dedicated X)

**Comment by benhaynes** [comment]
That works too! Let me re-phrase: each interface needs a native way to delete the value (in this case, submitting an empty one that parses as `null`).
