### ISSUE TITLE
File Download Error

### ISSUE THREAD

**Issue by mcqueena9845** [directus/directus#3451]
File download has the wrong permissions when downloading from an item.  Trying to open in a new tab, shows that it's using the public credentials to download instead of the logged in user.  To recreate, upload a file to a file field in and item and then try to download again.  Files can be downloaded from the file library.

---

### Project details
Directus Version: 9.0.0-rc.24
Environment: production
OS: Linux 5.4.0-58-generic
Node: 14.15.1

**Comment by rijkvanzanten** [comment]
This refers to the image/file interface
