### ISSUE TITLE
Allow updating own profile in system default permissions

### ISSUE THREAD

**Issue by mcqueena9845** [directus/directus#3454]
Restricted users can't edit their own profile, such as name, theme, and avatar.  To recreate, create a non-admin role, add a user to the role, login with user, and try to edit own profile.  Error on save:
`{
  "message": "You're not allowed to update item \"b37f1a92-aef2-45a9-9984-82dc2c6dc087\" in collection \"directus_users\".",
  "extensions": {
    "collection": "directus_users",
    "item": [
      "b37f1a92-aef2-45a9-9984-82dc2c6dc087"
    ],
    "action": "update",
    "code": "FORBIDDEN"
  }
}`

---

### Project details
Directus Version: 9.0.0-rc.24
Environment: production
OS: Linux 5.4.0-58-generic
Node: 14.15.1

**Comment by rijkvanzanten** [comment]
What permissions does this user role have?

**Comment by mcqueena9845** [comment]
System defaults.

![image](https://user-images.githubusercontent.com/75855426/102542709-2e32ba00-4080-11eb-8f4f-b93c9a02d723.png)
