### ISSUE TITLE
Field Order In Layout

### ISSUE THREAD

**Issue by mcqueena9845** [directus/directus#3458]
The order of the fields in the layout sidebar for non-selected fields seems random.  It's same for other field selection drop-downs.  They should be alphabetical or the order they were added in the collection.

![image](https://user-images.githubusercontent.com/75855426/102543847-e319a680-4081-11eb-9532-835a0635089a.png)

_Originally posted by @mcqueena9845 in https://github.com/directus/directus/discussions/3455_

**Comment by rijkvanzanten** [comment]
Everywhere we show the fields that isn't form-grid or settings, it should be in alphabetical order
