### ISSUE TITLE
Return null on `create an item`  in Public mode

### ISSUE THREAD

**Issue by shlaing** [directus/directus#3459]
`POST /items/{collection}`
 "Create an item" returns nothing in public mode but the item was added.
 
 It should return a JSON response.
 
 **Your environment:**
 DBMS : Postgres 12
 npx
 Chrome
 Linux

**Comment by shealavington** [comment]
Just to confirm, were you expecting it to be added? 
Was the collection open to the public to allow the item or not?

Either way, there's an issue:
1) if the user wasn't supposed to be able to add then item shouldn't have been added
2) if the user was supposed to add then the response shouldn't have been null.

**Comment by rijkvanzanten** [comment]
@shealavington If the user has create permission, but no read permission, you can create an item, but you won't get it returned 🙂 

@shlaing Can you check / share your permission setup? I'll close this for now as I'm assuming that's what it is

**Comment by shlaing** [comment]
Thanks, @rijkvanzanten,

You are right, I didn't give read permission because this is the lead table, so I can't let the users see all the records.

@rijkvanzanten  @shealavington 
I understand that I don't get any data because I don't have permissions.
However, I am expecting a response from the API but not null.

( At least, I can check the status code 200 or not )

**Comment by shealavington** [comment]
> @shealavington If the user has create permission, but no read permission, you can create an item, but you won't get it returned 🙂 
> 
> @shlaing Can you check / share your permission setup? I'll close this for now as I'm assuming that's what it is

    Even with a null stats, you should still be able to check response status?

**Comment by shlaing** [comment]
> Even with a null stats, you should still be able to check response status of 200?

Yes, the function is working but the response is null. 
I can see/get the status code is 200.
