### ISSUE TITLE
E-Mail Template creates wrong link

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#3466]
Next to the missing logo in the Emails (#3453 ) the link is also not correct.
The button contains the following link: _x-webdoc://admin/accept-invite?token=_the-token-_ instead of the base-url.

Exact steps to reproduce this issue
    Create a project and invite a user

Environment:
    - MySQL 8
    - npm

**Comment by rijkvanzanten** [comment]
@Dominic-Marcelino Do you have the PUBLIC_URL environment variable set?

**Comment by Dominic-Marcelino** [comment]
@rijkvanzanten Forgot to restart after defining missing environment variables
