### ISSUE TITLE
Links to docs do not work on the admin application

### ISSUE THREAD

**Issue by aschoijett** [directus/directus#3467]
No matter what link I click on, nothing is shown.   Is it possible that something did not install properly or is this a bug?

![image](https://user-images.githubusercontent.com/76222555/102642023-0ba9ab00-412b-11eb-939a-8e895c859b95.png)

**Comment by TimFau** [comment]
Same for me. Sidebar links work, but all the links on the main "admin/docs/" page are just set to "#"

Also, many of the links on docs subpages seem to be incorrect. For example, on "/admin/docs/concepts/activity-and-versions" the "Activity Module" link goes to "/concepts/app-overview#actvity-history" which shows a "Page Not Found" error.

**Comment by benhaynes** [comment]
This page will be removed, and the default page will be the Docs Intro.

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/directus/pull/3989 🙂
