### ISSUE TITLE
collections with public read permission return 403 forbidden

### ISSUE THREAD

**Issue by easychen** [directus/directus#3477]
I set coworker collections to public can read as this: 
![image](https://user-images.githubusercontent.com/1294760/102709413-62f37b00-42e5-11eb-8f46-f75eda8af997.png)

but when send get request to /items/coworkers , it return 403 
![image](https://user-images.githubusercontent.com/1294760/102709425-7e5e8600-42e5-11eb-9692-e9fed7e833df.png)

---

### Project details
Directus Version: 9.0.0-rc.24
Environment: production
OS: macOS Mojave (10.14)
Node: 14.15.3

**Comment by apstanisic** [comment]
Collection name is 'coworker' and you're requesting 'coworkers'.

**Comment by easychen** [comment]
> Collection name is 'coworker' and you're requesting 'coworkers'.

Thanks.  /items/coworker is OK. I got confused with the strapi documentation
