### ISSUE TITLE
Cannot log in as the first user when using docker-compose installation

### ISSUE THREAD

**Issue by JowieXiang** [directus/directus#3484]
# Cannot log in as the first user when using docker-compose installation

## steps to reproduce
    1. added the `ADMIN_PASSWORD` and `ADMIN_EMAIL` environment variables in `docker-compose.yaml` under `directus` service in the [official example](https://docs.directus.io/guides/installation/docker.html#docker-compose)
    2. `docker-compose up` 
    3. open `localhost:8055`, got redirected to `admin/login`
    4. entered the `ADMIN_PASSWORD` and `ADMIN_EMAIL` as the credentials but got `wrong username/password` error.
   
## Environment
    Directus: v9.0.0-rc.24
    DBMS: Postgres 12
    deployment:  Docker
    browser Chrome 87

I haven't tried `npx create-directus-project my-project` on my host machine, but I suppose that will work. I guess some initial setting-up steps are missing in the docker-compose installation? Please help...

## Solution
I upped the docker-compose services separately and it worked!
`docker-compose up -d database`
`docker-compose up -d cache`
`docker-compose up -d directus`
Maybe adding a `depends_on` in the example will make things better?
Thanks :+1:

**Comment by richardwhatever** [comment]
why was this closed? i'm having the same issue. thanks

**Comment by JowieXiang** [comment]
> why was this closed? i'm having the same issue. thanks

Hi there. I updated the `solution` section in the issue post and it should be clearer now. Let me know if you are still stuck.
