### ISSUE TITLE
Allow multiple files in browse

### ISSUE THREAD

**Issue by DKhalil** [directus/directus#3490]
Hello!

Is there an option for a multiple file upload field or is the integrated upload restricted to a single file at a time?

_Originally posted by @DKhalil in https://github.com/directus/directus/discussions/3489_

So, apparently it is very well possible already. After playing around with the upload function, I found out that by using drag and drop, you can already upload multiple files at once, but not if you open the file upload dialog manually.

**Comment by benhaynes** [comment]
@rijkvanzanten this slipped through our triage... can we label/respond?

**Comment by rijkvanzanten** [comment]
The `files` type interfaces should all support multiple-files-at-a-time uploads, yes
