### ISSUE TITLE
File upload fails

### ISSUE THREAD

**Issue by tim-carlo** [directus/directus#3496]
I am curently unable to upload files which are larger than about 2mb.
where do I set the limitations higher ? The docs, as far as I know, doesn't says anything about it.  
The debug says: 
```
Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)
```
---

### Project details
Directus Version: 9.0.0-rc.26
Environment: production
OS: Linux 4.19.0-13-amd64
Node: 14.15.3

**Comment by rijkvanzanten** [comment]
What webserver is this using? Directus doesn't have a hard 2mb limit, so I'm assuming this is caused by whatever webserver you're using as proxy

**Comment by tim-carlo** [comment]
I solved this issue on my own, thank your for your help. 
Someone who also uses NGINX reverse proxy, needs to set the 
``client_max_body_size`` to a more realistic value than the current default of 1M.
