### ISSUE TITLE
Non admin user can't change it's own data by default

### ISSUE THREAD

**Issue by apstanisic** [directus/directus#3505]
When creating user with app access and without admin access, by default user should be able to change it's own data.

**Comment by benhaynes** [comment]
Could you clarify what you mean by "their own data"? All access is based on permissions, is there an issue with your explicitly defined permissions?

**Comment by apstanisic** [comment]
Yes. When you create new role, for example `end-user` with app access, permissions that user has by default does not allow him/her to change it's own user info. He can't go to his own profile and change first name, email...

**Comment by apstanisic** [comment]
Also, admin options are shown for non admin users in profile page.
![rsz_screenshot_from_2020-12-23_20-20-13](https://user-images.githubusercontent.com/19491605/103030573-5f1d5e00-455c-11eb-9d14-c28585439350.png)

**Comment by myzinsky** [comment]
I confirm this bug. Just a quick idea: using a filter might help?

```json
{
    "ID": {
        "_is": "$CURRENT_USER"
    }
}
```

however I tried it and it does not work. Maybe im too dump to do the filter correctly.

**Comment by myzinsky** [comment]
Ah yes I'm dump:

```json
{
    "id": {
        "_eq": "$CURRENT_USER"
    }
}
```

this should do the job

**Comment by apstanisic** [comment]
Yeah, IMO that should be default behavior for when new role is created.

**Comment by benhaynes** [comment]
That's crazy — I guess I've been an Admin too long... never noticed that. We'll get the default user settings updated so that users can update their own settings (only theirs) out of the box. Thanks for reporting this!

**Comment by apstanisic** [comment]
It should have some restrictions, users should not be able to change their role, status.

**Comment by benhaynes** [comment]
Correct:

1. "Current" user should not be able to change anything under the "Admin Options" section
2. "Other" users shouldn't be able to edit any fields, and should not be able to see "User Preferences" fields
    * Also, I think "other" users should not see the inputs for first/last name, email, password, or avatar... all of this info is in the user header, and so the inputs can safely be hidden. Although the data itself shouldn't be hidden, since that needs to have _READ_ so it can be fetched for the header.

Not sure how all of this would work outside of the User Detail page, eg: a User Drawer in a relational field.
