### ISSUE TITLE
API delivers old data

### ISSUE THREAD

**Issue by myzinsky** [directus/directus#3513]
In the GUI I changed a data item: 

<img width="285" alt="image" src="https://user-images.githubusercontent.com/1970554/103133541-5e471200-46ab-11eb-973c-44d9267467f0.png">

It says modified 10 minutes ago. 

When I query the field *date_updated* over the API it shows me a date/time from yesterday... Definitely not 10 minutes ago ;-) 

Has somebody an idea?

**Comment by benhaynes** [comment]
Hmm, do you have any caching enabled?

**Comment by rijkvanzanten** [comment]
Fixed in c54f9f70d
