### ISSUE TITLE
Record visibility inside transactions

### ISSUE THREAD

**Issue by magomimmo** [directus/directus#3516]
Suppose to have a city collection with  a name property only (just for simplification). 
Then, suppose to have a person collection with a name and two cities properties: one to record her/his birthplace and the other to record her/his residence place. 

When you create a new entry for a person, if she/he has the residence in the same city of her/his birthplace and that city is not already available, but it's being created while creating the person, you don't find the city created as birthplace while creating the person's residence city and if you create the city again, you end up with two duplicated city.

---

### Project details
Directus Version: 9.0.0-rc.26
Environment: production
OS: Linux 5.4.0-58-generic
Node: 14.15.3

**Comment by benhaynes** [comment]
If you create it in one field/interface, that _staged_ value should also be available to other fields on the page.
