### ISSUE TITLE
M2A doesn't show the number of items in the table view

### ISSUE THREAD

**Issue by magomimmo** [directus/directus#3517]
When I define an M2M relation, the corresponding table view of its records shows the number of items of the target of the relation.

Instead, when I define an M2A relation, the corresponding table view of its records does not show the number of items of the targets of the relation. The expected behavior  should the same as the M2M ones. Am I wrong?  

---

### Project details
Directus Version: 9.0.0-rc.26
Environment: production
OS: Linux 5.4.0-58-generic
Node: 14.15.3

**Comment by benhaynes** [comment]
That seems to make sense. We'll check it out, unless you want to dive into a PR first! 😉

**Comment by YannickMol** [comment]
@magomimmo, I am trying to reproduce the issue, but unfortunately am not able to. Can you share a video or some screenshots perhaps?

**Comment by rijkvanzanten** [comment]
@YannickMol Heb je ook Discord?? Maakt 't misschien wat makkelijker om te overleggen 🙂 Dit is de Directus server: https://directus.chat
