### ISSUE TITLE
Added attribute to M2M relation not showing in detailed view of the originating collection

### ISSUE THREAD

**Issue by magomimmo** [directus/directus#3531]
Suppose to have a classical recipes/ingredients M2M relationship. Then you want to add field to that M2M relationship that is not a standard field, but a M20 relationship, for example the role of the ingredient in the recipe which is defined as a collection as well. As you can see form the screenshot, the role is not shown in the detail view of the recipe, while it is shown in the row detail of the selected ingredient.

![issue-01](https://user-images.githubusercontent.com/1448905/103219781-f00a8580-491e-11eb-97be-4de00999ec20.png)
---

![issue-02](https://user-images.githubusercontent.com/1448905/103220353-5b088c00-4920-11eb-906f-42ddf2907ec4.png)

### Project details
Directus Version: 9.0.0-rc.26
Environment: production
OS: Linux 5.4.0-58-generic
Node: 14.15.3

**Comment by rijkvanzanten** [comment]
I believe this was resolved in https://github.com/directus/directus/pull/4093. We can reopen if the problem still occurs 🙂
