### ISSUE TITLE
Route /fields/ doesn't exist.

### ISSUE THREAD

**Issue by tim-carlo** [directus/directus#3540]
While trying to add a many to many collection:
{   "errors": [     {       "message": "Route /fields/ doesn't exist.",       "extensions": {         "code": "ROUTE_NOT_FOUND"       }     }   ] }

### Project details
Directus Version: 9.0.0-rc.27
Environment: production
OS: Linux 4.19.0-13-amd64
Node: 14.15.3

**Comment by rijkvanzanten** [comment]
What server is this on? Are you using anything as a reverse proxy?

**Comment by tim-carlo** [comment]
I am using nginx reverseproxy, but this issue has´tn bee seen again !
