### ISSUE TITLE
Update Docs for Custom Interfaces

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#3550]
Ref: https://github.com/directus/directus/discussions/3538#discussioncomment-250517

**Comment by georgexchelebiev** [comment]
Have you planned how complex the example interface would be? I could possibly chip in here.

**Comment by benhaynes** [comment]
I think as long as it uses all the "features" of custom interfaces that should be enough. I defer to @rijkvanzanten on what those might be... and we can use that referenced ticket as guidance too.

**Comment by rijkvanzanten** [comment]
No specced out plan yet. Interfaces can range from "simple inputs" to full blown "mini apps" to save a value, so it's a little difficult to come up with one "correct" example

**Comment by georgexchelebiev** [comment]
After developing the [dictionary interface](https://github.com/georgexchelebiev/directus-dictionary), I'd say the dev experience would greatly benefit  from having information about what can go in the `options` property. Finding out how to use the default interfaces there was key in the process. 

As for the example, maybe going over one of the default interfaces can work. [Hash ](https://github.com/directus/directus/blob/main/app/src/interfaces/hash/hash.vue)is not too heavy on the Vue.js so it's documentation won't end up being Vue.js tutorial.

**Comment by rijkvanzanten** [comment]
unrelated:

@georgexchelebiev i love the progress bar you added to this 🙂 

@benhaynes Would be a cool (future) "group" style interface where you can "wrap" any other set of fields, and have it render a progress bar at the top to show how many of the fields have a value

**Comment by benhaynes** [comment]
> Would be a cool (future) "group" style interface where you can "wrap" any other set of fields, and have it render a progress bar at the top to show how many of the fields have a value

Absolutely! I think this can be even better once we have proper validation, since then "complete" fields are qualified beyond just "not null". Also, I see this as a Progress "Group" type... similar to tabs/dividers.

**Comment by nickrum** [comment]
The referenced code snipped has already been added to the docs. Should we keep this issue open to track the addition of more complex examples?

**Comment by rijkvanzanten** [comment]
@nickrum I think that's good enough to close this ticket. The docs are an ongoing thing, and we have a bigger push on extensions very soon, so that'll help clear things up too! 🙂
