### ISSUE TITLE
Disable permissions for non-editable permissions

### ISSUE THREAD

**Issue by andriusign** [directus/directus#3552]
Public permissions are set not to allow accessing /collections or /relations end-points.
However permissions are ignored and items being returned by GET method.

---

### Project details
Directus Version: 9.0.0-rc.24
Environment: production
OS: Linux 5.4.0-48-generic
Node: 14.15.2
Running in Docker

**Comment by rijkvanzanten** [comment]
This is intended. /collections, /fields, /relations, and some other system endpoints return data that shows what access the current user has. This allows external apps, the GraphQL endpoint, and internal features of Directus to build out an access graph / schema.

I'll leave this issue open to disable those checkboxes in the app

**Comment by andriusign** [comment]
Thank you.
