### ISSUE TITLE
Date created: "in less than a minute"

### ISSUE THREAD

**Issue by khromov** [directus/directus#3557]
Sometimes when creating new items, it looks like this:

![2021-01-03 07_08_04-Directus](https://user-images.githubusercontent.com/1207507/103472845-8fea6800-4d92-11eb-84d9-4094dddd8316.png)

"in less than a minute" doesn't make any sense, there's probably a bug somewhere in the "timeago" calculation functionality.

It should be changed to "just now", "now" or "a few seconds ago".

**Comment by rijkvanzanten** [comment]
Just to confirm, are your server's and computer's dates correctly configured? (Eg the server time itself isn't ahead by a couple minutes?)

**Comment by benhaynes** [comment]
I can not reproduce this. Not sure if the "Date Created" is from the server time or database NOW(), but those times are outside of the scope of Directus. I doubt this is a rounding issue in the contextual time library, so I'll close this for now. If more people report it and can verify that their server times are accurate, then we'll re-open!
