### ISSUE TITLE
Add migration guide (8 to 9)

### ISSUE THREAD

**Issue by justrealmilk** [directus/directus#3560]
Less a bug report and possibly more of a documentation request...

I understand that version 9 is currently a release candidate but I haven't been able to find anything about 8 anywhere...

If it has been discussed somewhere, could it be pinned in a notable place?

Thanks

**Comment by jroxendal** [comment]
I got pretty far by just fetching from v.8 /items api endpoint and POST-ing to v9 /items endpoint using a simple script, after first manually having created a datamodel that mirrored the old one. If your data is simple enough, that will be enough. But as for how to migrate the media library and its references: I have no clue.

**Comment by benhaynes** [comment]
Just to add, we'll certainly be writing this guide... we just need to get v9 stable and wrap up the other Docs first. Coming very soon!!
