### ISSUE TITLE
Adding a default value for a JSON field throws an error

### ISSUE THREAD

**Issue by jroxendal** [directus/directus#3568]
When creating a new json field and attempting to supply a default json structure, an error is raised:
`ER_BLOB_CANT_HAVE_DEFAULT: BLOB, TEXT, GEOMETRY or JSON column`. MySQL version 8.0.22.

This seems related to https://stackoverflow.com/questions/61169030/mysql-set-default-value-to-a-json-type-column

The GUI gives no indication as to what went wrong. Ideally, it should disable the default value input if the db doesn't support it. 

<details>
directus: 15:41:50 🚨 alter table `place` modify `latlong` json not null default '{\n    \"lat\": \"58\",\n    \"lng\": \"13\"\n}' - ER_BLOB_CANT_HAVE_DEFAULT: BLOB, TEXT, GEOMETRY or JSON column 'latlong' can't have a default value
directus: Error: ER_BLOB_CANT_HAVE_DEFAULT: BLOB, TEXT, GEOMETRY or JSON column 'latlong' can't have a default value
directus:     at Query.Sequence._packetToError (/Users/johan/dev/directus-9/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
directus:     at Query.ErrorPacket (/Users/johan/dev/directus-9/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
directus:     at Protocol._parsePacket (/Users/johan/dev/directus-9/node_modules/mysql/lib/protocol/Protocol.js:291:23)
directus:     at Parser._parsePacket (/Users/johan/dev/directus-9/node_modules/mysql/lib/protocol/Parser.js:433:10)
directus:     at Parser.write (/Users/johan/dev/directus-9/node_modules/mysql/lib/protocol/Parser.js:43:10)
directus:     at Protocol.write (/Users/johan/dev/directus-9/node_modules/mysql/lib/protocol/Protocol.js:38:16)
directus:     at Socket.<anonymous> (/Users/johan/dev/directus-9/node_modules/mysql/lib/Connection.js:88:28)
directus:     at Socket.<anonymous> (/Users/johan/dev/directus-9/node_modules/mysql/lib/Connection.js:526:10)
directus:     at Socket.emit (events.js:321:20)
directus:     at addChunk (_stream_readable.js:297:12)
directus:     --------------------
directus:     at Protocol._enqueue (/Users/johan/dev/directus-9/node_modules/mysql/lib/protocol/Protocol.js:144:48)
directus:     at Connection.query (/Users/johan/dev/directus-9/node_modules/mysql/lib/Connection.js:198:25)
directus:     at /Users/johan/dev/directus-9/node_modules/knex/lib/dialects/mysql/index.js:134:18
directus:     at new Promise (<anonymous>)
directus:     at Client_MySQL._query (/Users/johan/dev/directus-9/node_modules/knex/lib/dialects/mysql/index.js:128:12)
directus:     at Client_MySQL.query (/Users/johan/dev/directus-9/node_modules/knex/lib/client.js:168:17)
directus:     at Runner.query (/Users/johan/dev/directus-9/node_modules/knex/lib/runner.js:151:36)
directus:     at Runner.queryArray (/Users/johan/dev/directus-9/node_modules/knex/lib/runner.js:243:19)
directus:     at /Users/johan/dev/directus-9/node_modules/knex/lib/runner.js:38:25
directus:     at /Users/johan/dev/directus-9/node_modules/knex/lib/runner.js:277:24
</details>

**Comment by rijkvanzanten** [comment]
It seems like most, if not all, other support database vendors don't have any trouble with setting default values in text / json type fields. We'd rather not start hacking in little tweaks and exceptions based on the database vendor used (especially not in the app context), so this is considered a vendor limitation of MySQL and won't be addressed in Directus itself. That being said, we do strive to "translate" as many of those more common errors into our own exceptions, so we can render the errors nicer in the app 👍🏻
