### ISSUE TITLE
Missing "scope" parameter in OAuth request for Microsoft

### ISSUE THREAD

**Issue by theonlynexus** [directus/directus#3573]
First of all: I am not entirely sure this is a Directus issue, it might need to be escalated to grant.

1) The issue and what you expected to happen

Missing "scope" parameter in the OAuth request.

![image](https://user-images.githubusercontent.com/1515004/103555748-1b2f3f00-4ef4-11eb-8dac-a03ddc94991c.png)

2) Exact steps to reproduce this issue
Setup OAuth with Microsoft, try to login.

3) Your environment:
v9-rc.28 on Docker backed by MySQL

**Comment by theonlynexus** [comment]
The relevant page on MS's docs is [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent).

For simple login the scope parameter should be set to `openid`.

**Comment by theonlynexus** [comment]
I have been investigating the issue and I think this is a bug in the grant library: the `oauth.json` file contains all the common configuration parameters for the available providers, and Microsoft's object looks like the following:
```
  "microsoft": {
    "authorize_url": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
    "access_url": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
    "oauth": 2,
    "scope_delimiter": " "
  }
```

The `openid` scope is clearly missing.

**Comment by theonlynexus** [comment]
I tried making a [pull request](https://github.com/simov/grant/pull/215) with what I believed to be more sane defaults, but grant's author rejected my request indicating that it is the application's responsibility, and grant is really there just to provide endpoints.

Now I need to understand how to properly expose/configure the desired scope similarly to the application's id and secret key (via environment vars or similar). I am currently not aware of such possibility, but if that's already the case I beg your pardon.

**Comment by rijkvanzanten** [comment]
@theonlynexus All oauth env vars are passed directly to Grant's config for the provider, could you try setting

```
OAUTH_<PROVIDER>_SCOPE="openid"
```

and see if that does the trick?

**Comment by stephan-schmidt** [comment]
> and see if that does the trick?

Having the similar issue with Google SSO and tried just now
OAUTH_GOOGLE_SCOPE="openid" 

Result is a redirect to the Google page with 

`Authorization Error
Error 400: invalid_request
Missing required parameter: scope`

**Comment by theonlynexus** [comment]
> @theonlynexus All oauth env vars are passed directly to Grant's config for the provider, could you try setting
> 
> ```
> OAUTH_<PROVIDER>_SCOPE="openid"
> ```
> 
> and see if that does the trick?

To progress I had to set the following:
```
OAUTH_MICROSOFT_SCOPE: 'openid'
OAUTH_MICROSOFT_AUTHORIZE_URL: 'https://login.microsoftonline.com/<app-id>/oauth2/v2.0/authorize
OAUTH_MICROSOFT_ACCESS_URL: 'https://login.microsoftonline.com/<app-id>/oauth2/v2.0/token
```

This solved the scope error and the following tenancy related error (the default endpoints provided by grant only work for multi-tentat applications).

Now I am faced with the following: `AADSTS500111: The reply uri specified in the request has an invalid scheme.`

**Comment by theonlynexus** [comment]
> Having the similar issue with Google SSO and tried just now
> `OAUTH_GOOGLE_SCOPE="openid" `

Depending on the environment the syntax might be a little different. For example I am using docker and the syntax for environment vars there is `varnname: value`. How did you deploy?

**Comment by stephan-schmidt** [comment]
> **Update**: I set the `PUBLIC_URL` environment variable and the request now executes, but I am getting the following error from directus itself: `{"errors":[{"message":"Couldn't extract email address from SSO provider response","extensions":{"service":"oauth","provider":"microsoft","code":"SERVICE_UNAVAILABLE"}}]}`
> 
> I think the issue is in `api\src\utlis\get-email-from-profile.ts`.

Came that far too now. Same response. 

Setup: 
```
OAUTH_PROVIDERS ="google"
OAUTH_GOOGLE_KEY = "xxxxx"
OAUTH_GOOGLE_SECRET=  "xxxxx"
```
`OAUTH_GOOGLE_SCOPE="openid"`

JSON Response:
`  "errors": [
    {
      "message": "Couldn't extract email address from SSO provider response",
      "extensions": {
        "service": "oauth",
        "provider": "google",
        "code": "SERVICE_UNAVAILABLE"
      }
    }
  ]
}`

**Comment by simov** [comment]
Probably it's because `openid` returns just `sub` and `picture` keys for both Google and Microsoft.

So instead you have to request the `email` scope as well:

```bash
OAUTH_GOOGLE_SCOPE="openid email"
OAUTH_MICROSOFT_SCOPE="openid email"
```

Note the empty space between the scopes. This is the correct scope delimiter for both Google and Microsoft.

**Comment by rijkvanzanten** [comment]
Thanks @simov! And also lots of love and thanks for your great work on Grant 🙂 ❤️

**Comment by theonlynexus** [comment]
> Probably it's because `openid` returns just `sub` and `picture` keys for both Google and Microsoft.
> 
> So instead you have to request the `email` scope as well:
> 
> ```shell
> OAUTH_GOOGLE_SCOPE="openid email"
> OAUTH_MICROSOFT_SCOPE="openid email"
> ```
> 
> Note the empty space between the scopes. This is the correct scope delimiter for both Google and Microsoft.

Thanks, I'll try it, but I don't understand why that would be the case: I also have a Flask application for which I have configured the scope to `openid` only, and it works correctly.

**Comment by rijkvanzanten** [comment]
@theonlynexus I was actually working on a PR to integrate OpenID _next to_ oAuth, but it seems like you can already sneak in openid through Grant for at least some providers 🤔

**Comment by simov** [comment]
@rijkvanzanten, Grant supports the basic authentication flow of OpenID Connect.

Here is the list of know OpenID providers in Grant so far:

```
apple, asana, auth0, authentiq, cognito, familysearch, fusionauth, google, ibm, line, logingov, microsoft, okta, onelogin, paypal, phantauth, salesforce, twitch, yahoo
```

As long as the provider in question implements the OpenID Connect specification correctly, all you need to do is add the appropriate scopes in Grant, such as:

```
openid email profile
```

Keep in mind that there might be some inconsistencies between different provider implementations.

Then you can set the `profile_url` for that provider to be the one found in the discovery endpoint for that OpenID Connect provider and Grant will pull the profile from there.

Here is an example: https://github.com/simov/grant/blob/master/config/profile.json#L234

Taken from there: https://accounts.google.com/.well-known/openid-configuration

**Comment by adam-axis** [comment]
I am facing the same issue ("Couldn't extract email address from SSO provider response"). My config looks like this:
```
OAUTH_PROVIDERS: "microsoft"
OAUTH_microsoft_KEY: "---"
OAUTH_microsoft_SECRET: "---"
OAUTH_MICROSOFT_SCOPE: "openid email"
```

@simov Any clues?
