### ISSUE TITLE
Date is compared to string (MySQL)

### ISSUE THREAD

**Issue by oski646** [directus/directus#3575]
When I try to reach this endpoint: ` /items/invoices?filter={%22date_of_payment%22:{%22_empty%22:true}}&meta=filter_count&fields=[]` it gives me error 500.

VPS with Ubuntu 20.04
MySQL: 8.0.22-0ubuntu0.20.04.3
Directus: 9.0.0-rc.28
Browser: doesn't matter

Console in directus shows:
```
select invoices.id from invoices where (invoices.date_of_payment is null or invoices.date_of_payment = '') limit 100
Error: ER_WRONG_VALUE: Incorrect DATE value: ''
request errored GET 500 /items/invoices?filter={%22date_of_payment%22:{%22_empty%22:true}}&meta=filter_count&fields=[]
```

Even if I don't have items in invoices collection it gives me error.

Here is a screenshot from directus.
![brave_QMK9w0pfoB](https://user-images.githubusercontent.com/28627427/103561430-ca9af000-4eb9-11eb-9280-b747ab3cd380.png)

**Comment by rijkvanzanten** [comment]
The `_empty` filter will check for an empty string value. Use `_null` if you wanna check if a column is `null` 👍🏻
