### ISSUE TITLE
GraphQL Cache doesn't work

### ISSUE THREAD

**Issue by nagman** [directus/directus#3577]
I've set `CACHE_ENABLED` to `true` in my `.env` file, and then restarted the node process for directus (which is running in background thanks to `pm2`).

I've tried some GraphQL requests using `https://graphiql-online.com/graphiql`, and... no improvement in the requests' speed.

Sometimes the request takes 1 second, sometimes it takes 200ms, and having `CACHE_ENABLED` on `false` or `true` does not change anything.

**Comment by rijkvanzanten** [comment]
@nagman I'm pretty sure GraphiQL sets the `Cache-Control` to `no-cache`, so it's expected that you won't see any difference 👍🏻

**Comment by nagman** [comment]
Oh ok. But I have the same issue with my next.js website.

I use `fetch` to query my data on the server-side, and I've not set any `Cache-Control` header.
Do I need to explicitly set it to some value in order for the cache to be taken into account?
