### ISSUE TITLE
Cannot add a "Code" Interface to a repeater

### ISSUE THREAD

**Issue by jojomillennium** [directus/directus#3579]
Directus 9.0.0-rc.23

When setting a repeater with a field of Type _String_ and Interface _Code_, it does not save the code I put in.
I could not find any documentation on how this interface works, and its purpose, so maybe I'm missing something.

![2021-01-05_10-04-43 (1)](https://user-images.githubusercontent.com/6372094/103627327-be587680-4f3d-11eb-8d1b-0627659c7a10.gif)

What I am trying to do:
1. Test the code interface by putting javascript that would return as value always "OK"
2. Try to use the Code interface to concatenate two other repeater field value (not sure it is possible?). 

At the end, as I do not like the time fields, not user-friendly, I want my repeater to have three fields :
- From_hour : a dropdown of integer between 1 and 23, 
- From_minutes: a dropdown of integers from 0 to 55 (step of 5)
- From_time: note editable, it would concatenate From_hour and From_minutes into a value, like "14:45"

**Comment by rijkvanzanten** [comment]
@jojomillennium Could you try updating to the latests version of Directus? Seems like this issue might've been resolved already: https://github.com/directus/directus/commit/87e6e54e13a9c7c31852289a3d4621286cd457ae

**Comment by jojomillennium** [comment]
Hi @rijkvanzanten , updated to rc28, the field is properly saved.
Nevertheless, I relized my purpose will not be fullfilled using this :) Do I need to create a custom interface then?

**Comment by rijkvanzanten** [comment]
@jojomillennium yeah, there's no sort of concatenated-value-interface as of right now
