### ISSUE TITLE
M2O Relationship Corresponding Field

### ISSUE THREAD

**Issue by AndreyKindin** [directus/directus#3580]
when creating the M2O relationships, the Corresponding Field (o2m) is created in the same table and not in the related collection

---

### Project details
Directus Version: 9.0.0-rc.28
Environment: production
OS: Linux 4.15.0-128-generic
Node: 12.20.0

**Comment by h2bear** [comment]
i've got the same issue on RC27 with mysql

**Comment by mehmetuken** [comment]
Fixed #3638.
