### ISSUE TITLE
Email verification link not working

### ISSUE THREAD

**Issue by andriusign** [directus/directus#3591]
Trying to reset my password from the back end. Email configured to use SMTP. After I get email, there is no project logo display (image not found) and the link is: mail://admin/reset-password?token=....

Actual: no prefixed project URL at the beginning, link fails to open:
Expected: link should have project URL, etc. https://example.com/admin/reset-password?token=....

---

### Project details
Directus Version: 9.0.0-rc.24
Environment: production
OS: Linux 5.4.0-58-generic
Node: 14.15.2
Running in Docker

**Comment by juancarlosjr97** [comment]
Additionally, if the host is replaced for the correct one, there is a route error.

`{"errors":[{"message":"Route /reset-password doesn't exist.","extensions":{"code":"ROUTE_NOT_FOUND"}}]}`

**Comment by rijkvanzanten** [comment]
@andriusign Make sure you have the `PUBLIC_URL` env var set

**Comment by andriusign** [comment]
Indeed you are right. I thought it was enough to have "/" for a value. Updated my _.env_ file: 

- **before** PUBLIC_URL=/
- **now** PUBLIC_URL=http://localhost:8055
- **later** PUBLIC_URL=https://example.com/api
- 
Note that we don't need trailing slash "/" for the URL. I got an email with the correct link afterwards. However I have noticed in this email template that the image is missing. Tried setting .svg and .png file as project logo. Inspecting the email shows <img> tag with no _src_.

![1](https://user-images.githubusercontent.com/14263959/103945856-7c4a5300-513e-11eb-9c87-ba12f3fdb229.png)
![2](https://user-images.githubusercontent.com/14263959/103945862-7eacad00-513e-11eb-99c5-f00fe2f9fa6c.png)
