### ISSUE TITLE
Error: GUID validation fails on Equality Check during User Invite

### ISSUE THREAD

**Issue by RANSoftRA** [directus/directus#3597]
I am getting a 400 when trying to invite a user to a specific role with POST /users/invite

It seems like the validation does not take the whole GUID into account, but only the first character.

May be related to: #3590

Request:
POST localhost:8055/users/invite

Request-Body:
```
{
    "role": "7613135e-f8f4-4a0e-8642-7a921e42220d",
    "email": "text@example.com"
}
```

End-point settings for Public role (directus_users / Create):
Item permissions: role, email, status
Field validation:
```
{
    "role": {
        "_eq": "9ee3ef44-2437-4ca6-9806-b2cfc4e57bb1"
    }
}
```

Returns 400:
```
{
    "errors": [
        {
            "message": "\"role\" must be [9]",
            "extensions": {
                "field": "role",
                "type": "eq",
                "valid": "9",
                "code": "FAILED_VALIDATION"
            }
        }
    ]
}
```

**Project details**
Directus Version: 9.0.0-rc.28
Environment: production
OS: Windows 10
Node: 14.15.4

**Comment by andriusign** [comment]
Hello. Just wanted to check if there any updates on this ticket.

**Comment by rijkvanzanten** [comment]
@andriusign If there's no comments / activity on the issue, there aren't any updates 👍🏻

**Comment by andriusign** [comment]
I agree with you. When can we expect the fix for this bug since it is very important user feature.

**Comment by benhaynes** [comment]
Ref: https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix

**Comment by andriusign** [comment]
I've become a supporter and sent you an email with additional details.

**Comment by andriusign** [comment]
Hello. Just wanted to check when we can expect a fix for this issue.

**Comment by benhaynes** [comment]
[**Unfortunately, we can not provide estimates on features or fixes**](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍 . Or contribute a pull-request... after all, this is OSS!
