### ISSUE TITLE
M2A Display Template Not Being Honored

### ISSUE THREAD

**Issue by ddcollins** [directus/directus#3601]
I have a Lesson data model with a `steps` M2A relation. On that `lesson_steps` relation model I added a custom field called "title". 
![Image 2021-01-06 at 11 58 06 AM](https://user-images.githubusercontent.com/38921476/103803644-76f1e900-5016-11eb-9554-8b3aa997e5f8.png)

For the Lesson `steps` I set the "Display Template" to show "Title".
![Image 2021-01-06 at 11 57 45 AM](https://user-images.githubusercontent.com/38921476/103803601-680b3680-5016-11eb-9e64-cbf95afa676c.png)

However, any value I select for the "Display Template" does not modify what actually gets displayed on the content side, and it always stays as the relation type and the ID:
![Image 2021-01-06 at 11 59 03 AM](https://user-images.githubusercontent.com/38921476/103803738-97ba3e80-5016-11eb-84cc-b08b5717c6ce.png)

I would expect the listings under "Steps" to show the custom `title` field I set up on the `lesson_steps` data model.

---

### Project details
Directus Version: 9.0.0-rc.28
Environment: production
OS: Linux 4.15.0-58-generic
Node: 14.15.3

**Comment by rijkvanzanten** [comment]
The display template option in your screenshot controls what's used in the Display (which is the component used on the listing pages). This is not a setting for the many to any builder interface.

As of right now, the M2A interface relies on the collection-level display template to render out the individual rows

**Comment by nagman** [comment]
So... is the display tab useful for anything?

Actually, I've not seen the purpose of this from the beginning of my directus project.
I always pick "raw values", whatever the field type (it's not only related to M2A, same for input fields, M2M, M2O, O2M, File, etc.), because I never see any changes anywhere.

And for the listing, we already have the display template sidebar: 
![image](https://user-images.githubusercontent.com/16116486/104810154-2edf7d00-57f3-11eb-9a77-aa870b1da841.png)

@rijkvanzanten Could you show us an example of this display tab utility?
There's nothing on this in the docs.

**Comment by rijkvanzanten** [comment]
The display is what's used on the layouts. So for example in the table in this last screenshot for example, the display controls how the value is rendered in there 👍🏻

**Comment by nagman** [comment]
Mmh... it's not really clear to me.
You actually can change the layout through the display sidebar:
![image](https://user-images.githubusercontent.com/16116486/104817350-04a4b400-5821-11eb-86ca-d5bef6148a8e.png)

So this sidebar is useful, we do agree on that.

But what about the "display" section in the field creation process?
![image](https://user-images.githubusercontent.com/38921476/103803601-680b3680-5016-11eb-9e64-cbf95afa676c.png)

**Comment by zaunermax** [comment]
I'd like to know that as well. Showing users related values via the UUID is not a good UX unfortunately :/

**Comment by rijkvanzanten** [comment]
@zaunermax Use the related values display for the m2o column. That allows you to configure what relational fields to show 👍🏻

**Comment by chris-saunders-rocketlab** [comment]
I have what I assume to be exactly the same problem but the display template almost never works.

I've been able to get the dropdown display to work by only allowing one related collection which is of very little use:
<img width="268" alt="image" src="https://user-images.githubusercontent.com/74514057/155928627-e83e978d-e9ca-48c7-bb63-61a481edc235.png">

When I go in to edit the collection entry it does not work, it's still all IDs:
<img width="413" alt="image" src="https://user-images.githubusercontent.com/74514057/155928941-c08d6b47-6a1d-40bb-892a-249ef6494837.png">

I'm also unable to change which collections can be used to add a second so I have to delete and recreate the field with more than one collection assigned to it, the result is that now no form of template will ever work (drop down shown, editing is the same as above - all IDs):
<img width="252" alt="image" src="https://user-images.githubusercontent.com/74514057/155930075-c3c2e6fb-1dc6-4b9a-9676-fb06e6b0b43d.png">
and the template was:
<img width="607" alt="image" src="https://user-images.githubusercontent.com/74514057/155930193-08235a96-90e9-4bb9-97f2-6aa96647622c.png">
where Title is from one collection and Content Reference from the other.

I'm obviously fine for only one of them to work, but none of them work, nor does adding these to the collection level display template as described above (which doesn't really make sense to me anyway).

I'm also on the latest (9.5.2 right now).

Has anyone set this up successfully? (particularly with more than one collection - I really do need Many to ANY).
Also is there any plan to document how to set up display templates for the M2A field type?

**Comment by nmauersberg** [comment]
@chris-saunders-rocketlab I was first confused by the display template in the sidebar, setting up the fields.

For me it worked, when I used the display template in the main options (collection setup) of the data model that will be linked, below the option to add new fields.

**Comment by chris-saunders-rocketlab** [comment]
@nmauersberg I see, what I had missed was that the display template must be applied to the target collections.
The template options for the quick-view drop down aren't that great but at least I can show the target collection names.
Thanks for the help.

**Comment by gpietro** [comment]
I'm experiencing the same issue.

**Comment by rijkvanzanten** [comment]
> I'm experiencing the same issue.

Mind making a new issue? This one is over two years old, so there's most likely a different root issue 👍🏻

**Comment by danielcampagne** [comment]
Same issue here

**Comment by rijkvanzanten** [comment]
> Same issue here

.. Mind making a new issue? This one is over two years old, so there's most likely a different root issue 👍🏻

**Comment by Xinnerpeace** [comment]
> Same issue here

same here, did you make an issue?
