### ISSUE TITLE
"Page Not Found" For Users

### ISSUE THREAD

**Issue by myzinsky** [directus/directus#3602]
Hey Folks, 

the *User* Group, cannot edit items in the collection:

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/1970554/103819201-40de5480-506a-11eb-897e-d46b01d54b03.png">

Instead a page not found message is showing up. Admins can indeed change the values.

The right management looks also correct in my opinion:

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/1970554/103819315-784d0100-506a-11eb-8a74-5e30fd2169a0.png">

**Comment by myzinsky** [comment]
It seams that the page is loaded sucessfully and then again an Ajax load happens that fails. The browser JavaScripts console gives this error: 

```json
{
    "errors": [
        {
            "message": "Cannot destructure property 'collection' of 'collectionsRequested.find(...)' as it is undefined.",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}
```

**Comment by benhaynes** [comment]
Not sure what your schema is, but did you confirm that all the needed system collection permissions are set? You can click the button below permissions to expand and see them.

**Comment by myzinsky** [comment]
I reset the system collection permissions. No differences.

I did a workaround. I created a new role "Benutzer" and copied all users of the role "User" to the new one. The problem vanishes. 

Comparing the two roles in the database does not really show a difference...

```
directus=# select r.name as role, p.collection, p.action, p.permissions from directus_permissions as p join directus_roles as r on p.role = r.id where collection='questions';
   role   | collection | action |                         permissions
----------+------------+--------+--------------------------------------------------------------
 User     | questions  | delete |
 User     | questions  | update |
 User     | questions  | read   |
 User     | questions  | create |
 Benutzer | questions  | update |
 Benutzer | questions  | read   |
```

Strange, anyway the workaround fixed the problem.

**Comment by rijkvanzanten** [comment]
@myzinsky Can you send over a DB dump where this is happening? 

I'll close this for now, as it seems like you resolved it
