### ISSUE TITLE
User Account Cannot Create Comments

### ISSUE THREAD

**Issue by myzinsky** [directus/directus#3603]
The user account cannot create comments:

<img width="530" alt="image" src="https://user-images.githubusercontent.com/1970554/103820164-2016fe80-506c-11eb-95cf-f9d187090e49.png">

I can't set this anywhere in the permissions. So it seams that this is a bug?

**Comment by myzinsky** [comment]
```json
{
    "errors": [
        {
            "message": "You don't have permission to access this.",
            "extensions": {
                "code": "FORBIDDEN"
            }
        }
    ]
}
```
this is the JSON error message... says basically the same

**Comment by benhaynes** [comment]
Did you open up the system collection permissions? There is a button to open this at the bottom of the normal role permissions.

**Comment by myzinsky** [comment]
<img width="815" alt="image" src="https://user-images.githubusercontent.com/1970554/103824452-3a54da80-5074-11eb-9e2d-9d014da99a32.png">

Which one includes the comments?

**Comment by benhaynes** [comment]
Comments are stored in `directus_activity.comment`.

**Comment by myzinsky** [comment]
Thanks, issue solved
