### ISSUE TITLE
Add "expand_more" icon to right of sidebar detail component

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#3621]
Makes it a little more obvious that sidebar sections can be opened, when in expanded view (larger screens)

**Comment by benhaynes** [comment]
Adding to this:

We should always have SOMETHING open when in "wide-screen mode" and the drawer is open by default. It seems like `Info` is the easy choice here... since it should be on all pages.

**Comment by rijkvanzanten** [comment]
> It seems like Info is the easy choice here... since it should be on all pages.

Lets just use whatever's the first one. If in any case info is missing, it'll default to whatever's the top one 🙂

**Comment by Nitwel** [comment]
I didn't implement the top one being open by default, because for this we would have to do some serious trickery with css-variables / js which would be very ugly.
