### ISSUE TITLE
Prefix package name on CLI init

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#3622]
Right now, the tool uses `npm init -y` which will name your package the same as the folder name. However, when you name your folder the same as any of the dependencies (including `directus`), npm will fail installing as you're trying to install `directus` into `directus`.

We should prefix the generated package name with something like `directus-project-` so this naming conflict doesn't occur

**Comment by Nitwel** [comment]
I just tried `npx create-directus-project directus` and then `npx directus start` and everything worked without any issue.
What would be the exact steps to reproduce this?

**Comment by rijkvanzanten** [comment]
The problem used to be that `npm` complained about installing a package called `directus` _into_ a package called `directus`, as the name of the folder is used in the package.json that's generated by npm

**Comment by Nitwel** [comment]
Hmm, so should we close this because for me everything seemed fine?

**Comment by rijkvanzanten** [comment]
Hmmmm might be an npm version thing! It doesn't crash in NPM 7+, but I remember it causing problems before

**Comment by rijkvanzanten** [comment]
Yup! `npm` < 6 crashes:

<img width="1131" alt="CleanShot 2021-04-07 at 12 04 12@2x" src="https://user-images.githubusercontent.com/9141017/113897964-67ab4480-9799-11eb-8b15-13d36dab2c3f.png">

**Comment by rijkvanzanten** [comment]
Seeing that NPM already fixed this in a later version, I don't think we have to add any additional overhead to our side of things for older versions of NPM
