### ISSUE TITLE
Make file fields readonly (or hide) when editing in drawer

### ISSUE THREAD

**Issue by martijnboland** [directus/directus#3623]
When editing file (image) properties in a drawer, all fields are editable, including the ones that are normally displayed in the sidebar. Our users have no idea what to do with these fields. Is there a possibility to also hide these fields in when editing a file in a drawer?

![Screenshot 2021-01-08 at 15 35 48](https://user-images.githubusercontent.com/167455/104027609-e955fb00-51c7-11eb-9b0d-ec5cfd67af60.png)

_Originally posted by @martijnboland in https://github.com/directus/directus/discussions/3620_

**Comment by rijkvanzanten** [comment]
ref:

https://github.com/directus/directus/blob/82f9af67e0b5a8dd0d113b858e6daa2240a605db/api/src/database/system-data/fields/files.yaml#L90-L118
