### ISSUE TITLE
Cache is not invalidating when reordering items

### ISSUE THREAD

**Issue by dimitrov-adrian** [directus/directus#3627]
1) The issue and what you expected to happen
    When have cache is enabled, items are returned by order. When reordering items using manual sort, the items endpoint does not respect last changes. If turn off the cache - they are.

2) Exact steps to reproduce this issue
    1. Enable redis or memcache
    2. Requests items
    3. Reorder items using manual sorting
    4. Request items

3) Your environment:
    Directus 9r28

4) Any other relevant information we might need to reproduce this issue
    I think the issue could comes from utils endpoint, since it do direct db mutation and does not invalidate the cache

**Comment by rijkvanzanten** [comment]
@dimitrov-adrian To confirm, this is direct to/from API right? Or are you seeing this behavior in the app? Do you have cache-auto-purge enabled? (https://docs.directus.io/reference/environment-variables.html#cache)

**Comment by dimitrov-adrian** [comment]
Yes, it was because of not set CACHE_AUTO_PURGE, I though it was set by default when using cache, feels very dump.
