### ISSUE TITLE
items.create hook emits before the entry is saved to the database

### ISSUE THREAD

**Issue by dmtkpv** [directus/directus#3635]
#### The hook
```javascript
const mysql = require('mysql');

const connection = mysql.createConnection({
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    user: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DATABASE
});

module.exports = function () {
    return {
        'items.create' (event) {
            const table = event.collection;
            const id = event.item[0];
            const query = `SELECT * FROM ${table} WHERE id=${id}`;
            connection.query(query, (_, results) => {
                console.log(query);
                console.log(results); // []
            });
        }
    }
};
```

#### What is expected?
`console.log(results)` outputs an array with created item

#### What is actually happening?
`console.log(results)` outputs an empty array

#### Any other relevant information we might need to reproduce this issue
The first time hook may output a correct result, because the query() is delayed by connection

**Comment by WoLfulus** [comment]
you're not using Directus connection to fetch the item. creation is done inside a transaction and only commited after hooks finishes, this is probably why you're not getting your data back. try using event parameters instead.

**Comment by dmtkpv** [comment]
I think the problem is this:
**create method** of [ItemsService](https://github.com/directus/directus/blob/main/api/src/services/items.ts) emits `create` inside `this.knex.transaction`
However **update method** emits `update` after `this.knex.transaction`, and `items.update` hook works fine with my example
