### ISSUE TITLE
/assets/ breaks on 206 partial content requests

### ISSUE THREAD

**Issue by nagman** [directus/directus#3640]
When you upload a video on directus then try to get it from the `/assets/...` endpoint, you can't seek to a point in video.
[Here's a demo](https://user-images.githubusercontent.com/16116486/103086498-165db780-45e5-11eb-9ce9-67273dacab16.mp4)

I've already talked about this in this post:  https://github.com/directus/directus/discussions/3510
I've made a separate thread because the issue is not due to the absence of extension in the endpoint (which was what I thought in my first thread).

In between, I've found this post on stackoverflow: [HTML5 video will not loop](https://stackoverflow.com/a/9549404/4936168)

I quote: 

> As it turns out, looping (or any sort of seeking, for that matter) in `<video>` elements on Chrome only works if the video file was served up by a server that understands partial content requests. i.e. the server needs to honor requests that contain a "Range" header with a 206 "Partial Content" response. This is even the case if the video is small enough to be fully buffered by chrome, and no more server-round trips are made: if your server didn't honor chrome's Range request the first time, the video will not be loopable or seekable.

So it seems related to this **206 "Partial Content" response**.

Before you test in your browser, be sure to use a private window, because I had issues with cache (the video was seekable, whereas it shouldn't, and in private window it wasn't seekable anymore).

I'm using;
- directus 9.0.0-rc.30
- MySQL (Ver 15.1 Distrib 10.3.25-MariaDB)
- Opera 73.0.3856.344

**Comment by MarkBurvs** [comment]
I've just hit a similar issue trying to play a video in an iOS app using the Directus cms. Videos just don't play at all, and the following error is returned:

2021-01-29 15:52:36.910466+0000 vidtest3[2257:132333] [] [15:52:36.910] -[FigHTTPRequestSessionDataDelegate URLSession:dataTask:didReceiveResponse:completionHandler:] signalled err=-12939 (**kFigHTTPRequestError_ServerDoesNotSupportByteRanges**) (no content length/range with byterange request) at /Library/Caches/com.apple.xbs/Sources/EmbeddedCoreMedia_Sim/EmbeddedCoreMedia-2765.6/Prototypes/FigHTTP/FigHTTPRequestNSURLSession.m:1907


Strangely, it plays fine on Android, although, as @nagman experienced, seeking does not work. 
We're working around this for now by accessing the files directly using the file path, but it's far from ideal as I don't really want to have to make them publicly accessible.

**Comment by GreatSembo** [comment]
> I've just hit a similar issue trying to play a video in an iOS app using the Directus cms. Videos just don't play at all, and the following error is returned:
> 
> ```
> 2021-01-29 15:52:36.910466+0000 vidtest3[2257:132333] [] [15:52:36.910] -[FigHTTPRequestSessionDataDelegate URLSession:dataTask:didReceiveResponse:completionHandler:] signalled err=-12939 (**kFigHTTPRequestError_ServerDoesNotSupportByteRanges**) (no content length/range with byterange request) at /Library/Caches/com.apple.xbs/Sources/EmbeddedCoreMedia_Sim/EmbeddedCoreMedia-2765.6/Prototypes/FigHTTP/FigHTTPRequestNSURLSession.m:1907
> ```
> 
> Strangely, it plays fine on Android, although, as @nagman experienced, seeking does not work.
> We're working around this for now by accessing the files directly using the file path, but it's far from ideal as I don't really want to have to make them publicly accessible.

I have the same issue.
How do you point directly to the public files? Can you explain your workaround? 
Thank you

**Comment by MarkBurvs** [comment]
@GreatSembo you should just be able to append the video file extension (".mp4" etc)  onto whatever Directus returns for the video file, and then just go straight to that file in the root of your file storage path.

So for example, my collection is called "tutorials", and the field for the video file is "videofile".
To get the file from the cms I query my list of tutorial items like so:

https://cms.mything.com/items/tutorials/
..which returns me list of videos:

{
    "data": [
        {
            "date_created": "2021-01-29T17:34:50Z",
            "description": "How To Use The App!",
            "id": 9,
            "thumbnail": "b3d3b708-a988-4c0f-8af2-a7663dabef47",
            "title": "Quick Start",
            "videofile": "b45fa936-a2e8-41dc-a5f8-50b68a338148"
        } ....

I'm using a Digital Ocean "Space" as my filestore, and I know that the path to it is:
https://mything.digitaloceanspaces.com/

so I use the "videofile" value that the CMS returned, manually add the file extension, and get it here:

https://mything.digitaloceanspaces.com/b45fa936-a2e8-41dc-a5f8-50b68a338148.mp4

It's a pain in the bum though, as every time we upload a new video using the Directus CMS, I have to manually go into the Digital Ocean Spaces console and set that file to be publicly readable, and obviously it's not great having to have them public in the first place.

**Comment by altezza04** [comment]
> @GreatSembo you should just be able to append the video file extension (".mp4" etc) onto whatever Directus returns for the video file, and then just go straight to that file in the root of your file storage path.
> 
> So for example, my collection is called "tutorials", and the field for the video file is "videofile".
> To get the file from the cms I query my list of tutorial items like so:
> 
> https://cms.mything.com/items/tutorials/
> ..which returns me list of videos:
> 
> {
> "data": [
> {
> "date_created": "2021-01-29T17:34:50Z",
> "description": "How To Use The App!",
> "id": 9,
> "thumbnail": "b3d3b708-a988-4c0f-8af2-a7663dabef47",
> "title": "Quick Start",
> "videofile": "b45fa936-a2e8-41dc-a5f8-50b68a338148"
> } ....
> 
> I'm using a Digital Ocean "Space" as my filestore, and I know that the path to it is:
> https://mything.digitaloceanspaces.com/
> 
> so I use the "videofile" value that the CMS returned, manually add the file extension, and get it here:
> 
> https://mything.digitaloceanspaces.com/b45fa936-a2e8-41dc-a5f8-50b68a338148.mp4
> 
> It's a pain in the bum though, as every time we upload a new video using the Directus CMS, I have to manually go into the Digital Ocean Spaces console and set that file to be publicly readable, and obviously it's not great having to have them public in the first place.

Thanks for the work around. Obversely, the best way is to solve 206 code issues. Just want to check is it possible to set the access permission of the file inside Directus instead of going thru DO spaces console?

**Comment by rijkvanzanten** [comment]
> Just want to check is it possible to set the access permission of the file inside Directus instead of going thru DO spaces console?

Directus doesn't manage any permissions of your third party storage provider. I believe DO has a setting to make the whole Spaces instance public at once though 🤔 

That being said, this issue is very high on the priority list, so hopefully this workaround won't be needed anymore soon 🙂

**Comment by rijkvanzanten** [comment]
Good news @nagman @MarkBurvs @GreatSembo @altezza04 🙂 

It was surprisingly finicky cross-browser, but we've implemented Range requests on /assets:

https://user-images.githubusercontent.com/9141017/108274963-94e95800-7143-11eb-873d-261b8e2b0a40.mp4

_Shameless plug for my band [Heavenly Faded](https://open.spotify.com/artist/1VzpogOest0cp0xytyp36k)_

**Comment by MarkBurvs** [comment]
Brilliant. Thank you @rijkvanzanten

**Comment by mscbpi** [comment]
Hi,

`range` request  to /assets fails when using `azure` as storage driver, resulting in CDN failing to cache:

```
▶  curl -v -o nul --range "0-80000000" localhost:8055/assets/38e68a3f-79d4-441e-b059-1d17cc3bf457
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1:8055...
* Connected to localhost (127.0.0.1) port 8055 (#0)
> GET /assets/38e68a3f-79d4-441e-b059-1d17cc3bf457 HTTP/1.1
> Host: localhost:8055
> Range: bytes=0-80000000
> User-Agent: curl/7.88.1
> Accept: */*
>
< HTTP/1.1 206 Partial Content
< Content-Security-Policy: default-src none;style-src 'unsafe-inline'
< X-Powered-By: Directus
< Content-Type: image/jpeg
< Content-Disposition: inline; filename="my-super-file.jpg"
< Accept-Ranges: bytes
< Cache-Control: public, max-age=2592000
< Vary: Origin, Cache-Control
< Last-Modified: Mon, 16 Oct 2023 15:38:57 GMT
< Content-Range: bytes 0-93268/93269
< Content-Length: 93269
< Date: Tue, 17 Oct 2023 16:35:18 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
{ [32143 bytes data]
100 93269  100 93268    0     0  14951      0  0:00:06  0:00:06 --:--:--     0* transfer closed with 1 bytes remaining to read
100 93269  100 93268    0     0  14950      0  0:00:06  0:00:06 --:--:--     0
* Closing connection 0
curl: (18) transfer closed with 1 bytes remaining to read
```

Notice the 

```
curl: (18) transfer closed with 1 bytes remaining to read
```

Same works OK when using `local` as storage.

**Comment by rijkvanzanten** [comment]
@mscbpi this issue is over 2 years old, so whatever the original bug/fix was, it's certainly no longer relevant for any bugs you'd find now 🙂 Mind opening a new issue? Ty!

**Comment by mscbpi** [comment]
@rijkvanzanten  thanks, done :)

https://github.com/directus/directus/issues/20055
