### ISSUE TITLE
[sdk-js] auth.logout() does not include refresh_token required by /auth/logout API 

### ISSUE THREAD

**Issue by rafiqrahim** [directus/directus#3641]
https://github.com/directus/directus/blob/d9dc466f9acdb5f53ecec3773ca01e40e6294bdc/packages/sdk-js/src/handlers/auth.ts#L93

**Comment by apstanisic** [comment]
I've added commit to #3337 for using refresh token for json logout. 
I currently have some trouble with setting up monorepo, so I haven't tested it yet, but will try to find time soon.

**Comment by ralphniederer** [comment]
I have the same error.
