### ISSUE TITLE
Formatting issue in New Field drawer header

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#3648]
![Screen Shot 2021-01-06 at 5 09 45 PM](https://user-images.githubusercontent.com/522079/104213896-cd8b6880-5404-11eb-987c-bee0420fb795.png)

Also, it would be nice if we could include the current field name and current table in this header at all times (once we know it). Maybe that's what the comma was for?

**Comment by rijkvanzanten** [comment]
The comma's are a copy-paste issue:

https://github.com/directus/directus/blob/5845b9bc3515069999f6bbd5328bd3f093ff9a39/app/src/lang/translations/en-US.yaml#L79-L86

**Comment by rijkvanzanten** [comment]
@Nitwel I think you might've linked #4129 wrong. Your PR doesn't address this issue

**Comment by Nitwel** [comment]
> Also, it would be nice if we could include the current field name and current table in this header at all times (once we know it). 

You already removed the commas and this was the only problem left.

**Comment by rijkvanzanten** [comment]
way to go past me ✨ 😅
