### ISSUE TITLE
Incorrect date formatting when updating timestamp field

### ISSUE THREAD

**Issue by nelolka** [directus/directus#3655]
### Steps to reproduce
1. Open any existing item with a **timestamp** field (create if needed).
2. Change the value of this field.
3. Click Save 
4. Incorrect datetime value. 
![image](https://user-images.githubusercontent.com/24505418/104227243-c3dc2200-5451-11eb-8a69-f7db2a5823bc.png)

### My environment:
1. MySQL 5.7.32
2. Chrome 87.0.4280.141 
3. Directus v9.0.0-rc.28

**Comment by rijkvanzanten** [comment]
Hmmmmm could be a version issue in MySQL 🤔  Seems to work fine in MySQL 8.0.22 (what I use locally)

https://user-images.githubusercontent.com/9141017/104520363-feb49600-55c8-11eb-9154-3d3c519fa5d6.mp4

**Comment by nelolka** [comment]
I've updated MySQL to 8. Now it's okay. Maybe add compatibility with old versions?

**Comment by rijkvanzanten** [comment]
Yeah it should work under mysql 5.7.x too, i was just mentioning it 🙂

**Comment by flystyle** [comment]
I have the same issue on MariaDB 10.3
`update 'payments' set 'date_created' = '2021-01-02T00:00:20+05:00', 'date_updated' = '2021-01-17 17:49:05.008'`

**Comment by rijkvanzanten** [comment]
@flystyle where is this query coming from?

`update 'payments' set 'date_created' = '2021-01-02T00:00:20+05:00', 'date_updated' = '2021-01-17 17:49:05.008'`

**Comment by flystyle** [comment]
I'm trying to change the Date Created field right in Admin

![alt text](https://i.imgur.com/hQ0JsQQ.png)

**Comment by djmtype** [comment]
Getting a similar issue when using the `date_published`.

```
{
  "message": "insert into `articles` (`content`, `date_created`, `date_published`, `status`, `title`, `user_created`) values ('<p>Lorem ipsum whatever</p>', '2021-03-05 16:17:28.927', '2021-03-05T16:10:06-05:00', 'published', 'First Post Title', 'abe8c680-16fd-44e7-8b7e-5df422af4847') - ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2021-03-05T16:10:06-05:00' for column 'date_published' at row 1",
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR"
  }
}
```

**Comment by workatease** [comment]
This happens in mysql and MariaDB as discussed in discord this happens for timestamp. We should convert those ISO8601 strings to a JS Date, and pass that to Knex as suggested by @rijkvanzanten

**Comment by cdwmhcc** [comment]
Incorrect datetime value.I also received the same error, my data was migrated from v8 to v9. @rijkvanzanten

**Comment by cdwmhcc** [comment]
directus 9.0.0-rc.56 I also received the same error
