### ISSUE TITLE
"Mirror" foreign keys between DB and directus_relations

### ISSUE THREAD

**Issue by Oreilles** [directus/directus#3664]
When installing directus on a pre-existing database that has table with foreign keys, none of these foreign keys are recognized as such. Directus only sees them as having standard types: int, string... Which mean you would have to recreate all the relations from within the app, making a migration really hard.

Environment:
    Postresql 13
    npx

**Comment by Oreilles** [comment]
Could you point me to where I could maybe start working on this @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
There's https://github.com/directus/directus/discussions/3074 and this. I _think_ the schema overview function should retrieve all foreign keys as well, so we can merge those with the relationships on schema retrieval 🤔 

It's similar to fields/columns and collections/tables. I treat the directus_fields and directus_collections info as "optional metadata" on top of the actual columns / fields. I think we should treat directus_relations the same. This does mean that we'll have to update the directus/schema package to retrieve the foreign keys as well

**Comment by Oreilles** [comment]
Oh, I actually thought that relations in directus were actual foreign keys.. that is pretty scary.

**Comment by Kematia** [comment]
If I got this right you're dropping the directus_relationships system? Reading directly from the db FKs...
This would enable to control the db structure with knex or other ORMs, if I got this right?

**Comment by rijkvanzanten** [comment]
> If I got this right you're dropping the directus_relationships system? Reading directly from the db FKs...

No it won't be dropping it, as we still need a place to store meta-information like what the field name is for the "returning" o2m, what the sort field is etc. You can compare it best to how directus_collections / fields works right now as well. The database is the "core" source for the data, with the directus_* stuff adding on additional metadata to enhance

> This would enable to control the db structure with knex or other ORMs?

That's correct! It'd mean that fields that have a foreign key constraint configured will automagically work as a many-to-one within directus
