### ISSUE TITLE
GraphQL query does only return 100 items

### ISSUE THREAD

**Issue by TheOneAndOnlyGarcia** [directus/directus#3667]
environment:
docker, postgres 13, directs v9 r27

Hello, 

i am trying to retrieve an object list via graph ql. My collection contains 9600 objects and it is essential that I can a perform a graphql query where I fetch all objects. 

```
{
  directus {
    items {
      my_objects {
        id
      }
    }
  }
}
```

is returning exactly 100 results. Is this a bug or feature? If it is a feature, how or where can I set the limit?

Thanks a lot guys!

**Comment by rijkvanzanten** [comment]
The default value for the `limit` argument (/ query param in REST) is `100`, so this is a feature 🙂 

You can set 

```graphql
{
  directus {
    items {
      my_objects(limit: 5000) {
        id
      }
    }
  }
}
```

you can use `-1` to fetch everything, just keep in mind that this can have potential performance/memory problems if you query tables with _a lot_ of records 🙂

**Comment by benhaynes** [comment]
Let's add info regarding this to the GraphQL Docs (if not there already) @philleepflorence 🔔

**Comment by philleepflorence** [comment]
Will do...

**Comment by Silbad** [comment]
Hello, if I limit to 1 => my_objects(limit: 1), can I get a random data ?

**Comment by benhaynes** [comment]
Hmm, I don't think so. We're waiting on the `sort=?` to be added back in.
