### ISSUE TITLE
Missing entries on Crowdin

### ISSUE THREAD

**Issue by t7tran** [directus/directus#3686]
1) The issue and what you expected to happen
    There are many Vietnamese translations are not visible in the app (see sample attached images for User detail page) even though there are equivalent string definitions on Crowdin. I suspect the same issue affecting other languages too. Later noticed that the translation context in Crowdin doesn't match, e.g. Description string belongs to `fields -> directus_files -> description`. We should have corresponding translation entries for all messages in the app.

![image](https://user-images.githubusercontent.com/76130324/104537342-e9457780-566d-11eb-8ebe-2e41bd1f9ee7.png)
![image](https://user-images.githubusercontent.com/76130324/104537379-fa8e8400-566d-11eb-9960-677da50af663.png)

2) Exact steps to reproduce this issue
    Change User language preference to Vietnamese and revisit a user's detail. The `Description` page in this example isn't translated.

3) Your environment:
    Which DBMS are you using: MySQL 5.7
    Which deployment are you using: Docker
    What browser are you using: Chrome 87

4) Any other relevant information we might need to reproduce this issue
    NA

**Comment by benhaynes** [comment]
This could be due to translations being added in Crowdin, but not released with a new version of Directus yet. I believe each update to Crowdin only gets added once a new Directus release is made...

**Comment by rijkvanzanten** [comment]
There's a delay in Crowdin -> PR to Directus -> Directus release. There's at least a couple days before things entered in Crowdin show up in Directus releases

**Comment by t7tran** [comment]
Just a simple question then. How can we translate the `Description` label in User Detail page (screenshot above)? I couldn't find the corresponding entry on Crowdin.
