### ISSUE TITLE
Directus JS SDK shoud not add an extra slash to the API before the query question mark

### ISSUE THREAD

**Issue by ZiedHf** [directus/directus#3687]
Using Directus JS SDK; this line of code will call the API with an extra slash before the query
`directus.items('configuration').read({ single: true });`
The API :  `/items/configuration/?single=true` with an **/?**
The expected end point should be `/items/configuration?single=true`
The response of the first end point is an error 404 Not found.

**Comment by rijkvanzanten** [comment]
Directus itself doesn't discriminate between the routes with or without a trailing slash. What version of Directus are you using with what webserver?

`/items/my_collection?single=true` is the same as `/items/my_collection/?single=true` within the context of Directus

**Comment by apstanisic** [comment]
If for some reason you MUST remove `/?`, there is a way with interceptors, jsaenzr was right:
```ts
axios.interceptors.request.use(async (config) => {
  const qmIndex = config.url.lastIndexOf('/?');
  if (qmIndex !== -1) {
    config.url = config.url.substring(0, qmIndex) + config.url.substring(qmIndex + 1);
  }
  return config;
});

```

**Comment by egidiusmengelberg** [comment]
I have the exact same issue. I made a temporary fix using the code provided by @apstanisic. I'm using multi tenancy maybe that has something to do with it? Even in the browser an extra slash after an item does not work. It returns a 404. 
currently i've tested GET and POST. These do not work with the extra slash.

But when updating an item the extra slash is fine. So the patch method does not care about the extra slash.

**Comment by rijkvanzanten** [comment]
@egidiusmengelberg 

> I'm using multi tenancy

How are you using multi-tenancy? Are you using v8 perhaps?

**Comment by egidiusmengelberg** [comment]
I'm using V8.8.1 and multi tenancy with multiple databases. 

One important note is that I use the docker container with traefik as a reverse proxy. But I do not think this has anything to do with it because I get the error page from directus.

**Comment by benhaynes** [comment]
@egidiusmengelberg — this repository is only for Directus 9 (Node.js), you should post within:
https://github.com/directus/v8-archive

**Comment by egidiusmengelberg** [comment]
ah sorry you're right. I just commented to @ZiedHf issue. thanks anyway.
