### ISSUE TITLE
User Invite Email URL Missing Domain

### ISSUE THREAD

**Issue by ddcollins** [directus/directus#3694]
The URL that is within the user invite email is missing the domain. I assume it's trying to pull the "Project URL" set in the settings page, but I have that set and it's still missing.

I don't see any documentation on how to set this, so my assumption is it's a bug.

e.g. The url in the email is is:
https://admin/accept-invite?token={fulltoken}

---

### Project details
Directus Version: 9.0.0-rc.28
Environment: production
OS: Linux 4.15.0-58-generic
Node: 14.15.3

**Comment by rijkvanzanten** [comment]
@ddcollins Do you have the PUBLIC_URL environment variable set correctly?

**Comment by ddcollins** [comment]
@rijkvanzanten That was it, thank you!
