### ISSUE TITLE
Can't login to demo on platform.sh

### ISSUE THREAD

**Issue by timuric** [directus/directus#3703]
After using "one-click" installation on platform.sh the password reset is not working and neither the guide mentions the default credentials.

**Comment by rijkvanzanten** [comment]
I believe you can set the initial admin/password for platform by using the `INIT_ADMINUSER` and `INIT_ADMINPW` environment variables

https://github.com/platformsh-templates/directus/blob/c1d7988ba6fca09db27ce916e80992b0e1f32496/.environment#L1-L3

@chadwcarlson Is there support for `sendmail` / `smtp` on Platform.sh?

**Comment by timuric** [comment]
@rijkvanzanten thanks, it worked! The guide should definitely mention these default variables

**Comment by benhaynes** [comment]
🔔  @philleepflorence — might want to update the platform.sh Docs with this...

**Comment by chadwcarlson** [comment]
@rijkvanzanten There is. Let me take a look at it. 👍

**Comment by philleepflorence** [comment]
@benhaynes - Should this also be updated: [Environment Variables](https://docs.directus.io/reference/environment-variables.html#misc)

**Comment by rijkvanzanten** [comment]
@philleepflorence don't think so, as this is platform.sh deployment specific 👍🏻

**Comment by philleepflorence** [comment]
@rijkvanzanten - Okay just: [Platform.sh One-Click Install](https://docs.directus.io/guides/installation/platformsh-one-click.html)

**Comment by chadwcarlson** [comment]
@rijkvanzanten @benhaynes @timuric Fixed in https://github.com/platformsh-templates/directus/pull/3
