### ISSUE TITLE
Environment variable type issue

### ISSUE THREAD

**Issue by mustafa-online** [directus/directus#3705]
## MySQL v5.7.24

node_modules/mysql/lib/protocol/Parser.js:437 throw err; // Rethrow non-MySQL errors

![drcts_error](https://user-images.githubusercontent.com/5323832/104725257-8241c480-573a-11eb-87eb-8e2e0c7b5062.PNG)

After alot of searching I tried to increase the MySQL password lenght to 8 characters (It works fine and the issue is gone).
The old password was "1234". I opened this issue just in case it encountered someone else.

**Comment by rijkvanzanten** [comment]
The underlying issue here is that Directus sees `1234` as a number, and thus passes it on to MySQL wrong!
