### ISSUE TITLE
Some problems with access for custom Role

### ISSUE THREAD

**Issue by iksent** [directus/directus#3711]
1. I created a new role "Editor" - he can manage all models' data, but can't change its structure
2. Here are the settings:

![image](https://user-images.githubusercontent.com/32956521/104760473-3cf5b500-5783-11eb-9b15-2d1ced93a849.png)

3. Then I login to Editor-user, and admin dashboard was fully empty
4. Then I manually go to a collection `http://localhost:8055/admin/collections/doctor`
5. I see empty menu at left:

![image](https://user-images.githubusercontent.com/32956521/104760257-ec7e5780-5782-11eb-9cd3-9d9cf331b532.png)

BTW: I didn't receive registration Email :( Spam is empty also

---

### Project details
Directus Version: 9.0.0-rc.28
Environment: production / Really production? I ran Directus with `yarn create directus-project my-project`
OS: macOS Big Sur (11)
Node: 14.15.4

**Comment by benhaynes** [comment]
For the navigation, did you add anything into Nav Override or Module Override for this role?

**Comment by iksent** [comment]
Probably not, just created a new role and changed permissions for it, as seen on screenshots.

**Comment by benhaynes** [comment]
You can try to "Reset" the system permissions (bottom of that permissions interface) to see if that fixes it... there might be some relational system data that is missing in your new role permissions. At least then we know it's actually a permissions issue.

**Comment by iksent** [comment]
1. I ran "Reset" for permissions = No changes = Menu is still hidden
![Снимок экрана 2021-01-20 в 10 38 27](https://user-images.githubusercontent.com/32956521/105131927-bdae0b80-5b0b-11eb-9a87-17819283e7f1.png)

2. Upgraded Directus to the latest rc30 and still no changes

**Comment by rijkvanzanten** [comment]
@iksent What's the configured value under "module list" down below on the roles page?

**Comment by iksent** [comment]
Oh, yes! That was the issue: I have one module with empty data there. Sorry for that, closing the issue.

**Comment by rijkvanzanten** [comment]
np!
