### ISSUE TITLE
Language change applies to my browser

### ISSUE THREAD

**Issue by nelolka** [directus/directus#3714]
### Issue
The language changes in my browser when I change it for other user.

### Steps to reproduce
1. Open any user profile (except yours).
2. Change the language.
3. Click Save.
4. The language will be changed in your browser.

https://user-images.githubusercontent.com/24505418/104785010-315dba80-5792-11eb-8e3d-b4c169e77353.mp4

### My environment
MySQL 8.0.22
Chrome 87.0.4280.141
Directus v9.0.0-rc.29

**Comment by nelolka** [comment]
Bug still exists :<

**Comment by nelolka** [comment]
Now it works vice versa. If you change the language for the other user, it changes in your browser. If you change it for yourself, it doesn't change.

**Comment by rijkvanzanten** [comment]
ha whoops
