### ISSUE TITLE
Many-to-any (M2A) not deleting entries in the database

### ISSUE THREAD

**Issue by nagman** [directus/directus#3715]
When you delete an entry from a M2A field, it doesn't remove it from the database.
It just replaces the junction id of the field by `NULL`.

Here's a video showing that: 
https://user-images.githubusercontent.com/16116486/104809248-29caff80-57ec-11eb-8f12-bd2930122eb6.mp4

I have a table named `articles_vedette` (featured posts, in french), which is a singleton, and I have this table named `articles_vedette_articles` which is the many-to-any field.

The `articles_vedette_id` is just the junction field that links `articles_vedette_articles` to `articles_vedette` (so the value will always be `1`, because `articles_vedette` is a singleton).

The correct behavior would be to simply remove the entire row from the table.

My environment:
- directus 9.0.0-rc.30
- MySQL (Ver 15.1 Distrib 10.3.25-MariaDB)

**Comment by rijkvanzanten** [comment]
This is by currently design. We don't offer constraints for relational fields yet, and can't just assume that we can safely delete the related item as there can be other fields and user data that is not intended for deletion. There's an open feature request to support custom constraints for user collection relationships: https://github.com/directus/directus/discussions/3074
