### ISSUE TITLE
Many-to-any (M2A) field not displaying nested data through the GraphQL API

### ISSUE THREAD

**Issue by nagman** [directus/directus#3718]
When you create a M2A field, you should be able to query all nested collections through the GraphQL API.

Though it always returns `null`.

Let me explain.

Here's my M2A listing:
![image](https://user-images.githubusercontent.com/16116486/104809560-87604b80-57ee-11eb-9d48-2b4b65804474.png)

I now create a GraphQL request that gets all entries and their corresponding title:
```graphql
query MyQuery {
  items {
    articles_vedette_articles {
      collection
      item {
        ... on actualites {
          title
        }
        ... on temoignages {
          title
        }
        ... on conseils {
          title
        }
      }
    }
  }
}
```

And here's the answer:
```json
{
  "data": {
    "items": {
      "articles_vedette_articles": [
        {
          "item": null,
          "collection": "actualites"
        },
        {
          "item": null,
          "collection": "conseils"
        },
        {
          "item": null,
          "collection": "conseils"
        },
        {
          "item": null,
          "collection": "temoignages"
        },
        {
          "item": null,
          "collection": "temoignages"
        },
        {
          "item": null,
          "collection": "temoignages"
        }
      ]
    }
  }
}
```

If I request shallow fields (by shallow, I mean directly accessible fields in the table: `id`, `collection` and `sort`) it works.
But the [inline fragments](https://graphql.org/learn/queries/#inline-fragments) in the `item` field always returns `null`.

I've found the responsible row in the database `directus_relation` table:
| id | many_collection           | many_field | many_primary | one_collection | one_field | one_primary | one_collection_field | one_allowed_collections         | junction_field      |
|----|---------------------------|------------|--------------|----------------|-----------|-------------|----------------------|---------------------------------|---------------------|
| 1  | articles_vedette_articles | item       | id           | NULL           | NULL      | NULL        | collection           | actualites,conseils,temoignages | articles_vedette_id |

If you delete this row, the `item` field returns the entry's `id` (as a REST request would).
But the point of GraphQL is to avoid multiple queries by querying nested fields.

The back-office use multiple REST queries to display entries on the frontend.
And that's the only way I've found to do the same on my website.

But all my other requests are made in GraphQL and I want to use that `... on FooBar {` syntax to get all data in one single request.

I think this is related to the backend structure of the GraphQL resolvers.

My environment:
- directus 9.0.0-rc.30
- MySQL (Ver 15.1 Distrib 10.3.25-MariaDB)

**Comment by KonradDeskiewicz** [comment]
maybe it has something to do with fact that the `__typename` inside item shows the wrong one:
![image](https://user-images.githubusercontent.com/17060750/105530559-3ff32700-5ce8-11eb-98aa-d47bd05b3296.png)

**Comment by KonradDeskiewicz** [comment]
@rijkvanzanten Is there any maintenance schedule for this bug? To be honest this one is now holding me with Directus use as my primary solution :-)

**Comment by rijkvanzanten** [comment]
[**Unfortunately, we can not provide estimates on features or fixes**](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍 . Or contribute a pull-request... after all, this is OSS!

**Comment by rijkvanzanten** [comment]
If you wanna take a swing at this, it's this bit:

https://github.com/directus/directus/blob/f056918dd3a38bb5c07edbe098655193df788acf/api/src/services/graphql.ts?ts=3#L160-L172

The problem here is that we need to access the parent junction row value in that resolver function in order to extract the related collection name, and thus be able to serve GraphQL the correct type definition.

**Comment by tstec-polypoly** [comment]
Hi,

I'm using the latest RC as of now, v9.0.0-rc.32

M2M fields are also not displaying in GraphQL... the relationship tables are there, but the M2M fields within a collection just show as leaves with the value 'null'. This is a showstopper for me, and I'll probably spend the weekend porting my big schema to another solution.

The reason I'm using M2M fields in the first place is that OTM fields don't seem to be working at all. So fixing OTM fields would also un-block me.

Please help!
