### ISSUE TITLE
Add foreign key constraint support

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#3719]
Currently, relational interfaces (m2m/m2a) can't delete junction rows, because we don't offer configurable key constraints, and can't just assume that the junction row is safe to delete.

We should address this by allowing key constraints to be configured during field setup, which allows the user to configure junction rows to be deleted (instead of nullified-current default).

From https://github.com/directus/directus/discussions/3074

**Comment by Oreilles** [comment]
This + https://github.com/directus/directus/issues/3664 would be a massive improvement to Directus!

**Comment by rijkvanzanten** [comment]
Duplicate of #2942
