### ISSUE TITLE
Cannot install monorepo without npx and global packages

### ISSUE THREAD

**Issue by emregency** [directus/directus#3744]
1) The issue and what you expected to happen
    I cannot `npm install` the  monorepo `v9.0.0-rc.30` without certain globally installed packages or adding `npx` before `rimraf` & `copyfiles`. I have identified so far (as I still couldn't install) `lerna`, `node@12` and `typescript`. 

2) Exact steps to reproduce this issue
    Remove all globally installed packages > clone the repo > `npm install`

3) Your environment:
     Windows 10, VS Code, `node@10`

4) Any other relevant information we might need to reproduce this issue
    N/A

_The issue seems to be that the monorepo sub-folders cannot access the packages installed by the root level of the monorepo._

**Comment by emregency** [comment]
**Update after 6 hours**

Managed to install the monorepo `v9.0.0-rc.30` :

0.  Make sure you have `node@12` installed by using `node -v`
1.  Install the following packages globally:
`npm i -g typescript rollup lerna node-pre-gyp node-gyp` 
2. Modify the following scripts:

- in `/api/package.json` `scripts.build` to `"npx rimraf dist && tsc --build && npx copyfiles \"src/**/*.*\" -e \"src/**/*.ts\" -u 1 dist"`
- in `/app/package.json` `scripts.build` to `"node ../node_modules/@vue/cli-service/bin/vue-cli-service.js build"`
- in `/packages/format-title/package.json` `scripts.prebuild` to `"npx rimraf dist"`
- in `/packages/sdk-js/package.json` `scripts.prebuild` to `"npx rimraf dist"`

**Update after 12 hours**

Most probably the previous steps will allow the completion of the installation. Now comes the initialization with the `cli`.

1. Modify the following scripts:

- in `/api/package.json` `scripts.cli` to `"npx cross-env DIRECTUS_DEV=true NODE_ENV=development npx ts-node --script-mode --transpile-only src/cli/index.ts"`
- in root `package.json` `scripts.cli` to `"npx cross-env DIRECTUS_DEV=true NODE_ENV=development DOTENV_CONFIG_PATH=api/.env npx ts-node -r dotenv/config --script-mode --transpile-only api/src/cli/index.ts"`

2. You may need to recompile `argon2` at the root level as mentioned [here](https://github.com/ranisalt/node-argon2/issues/276) using `npm rebuild argon2 --build-from-source`

These steps will allow you the completion of the initialization. Now comes the development with `npm run dev`.

1. The `/api` may not find the `.env`. Duplicate the `.env` in the root folder to the `/api` folder.
2. Modify the following scripts:

- in `/api/package.json` `scripts.dev` to `"npx cross-env DIRECTUS_DEV=true NODE_ENV=development node ../node_modules/ts-node-dev/lib/bin.js --files --transpile-only --respawn --watch \".env\" --inspect --require dotenv/config src/start.ts`"
- in `/app/package.json` `scripts.dev` to `"node ../node_modules/@vue/cli-service/bin/vue-cli-service.js serve"`
- in `/docs/package.json` `scripts.dev` to `"npx npm-watch build"`
- in `/packages/schema/package.json` `scripts.dev` to `"npx npm-watch build"`
- in `/specs/package.json` `scripts.dev` to `"npx npm-watch build"`
3. You may need to rebuild `sharp` at the root level using `npm rebuild sharp`

**Comment by rijkvanzanten** [comment]
Feel free to open a pr for all that 👍🏻 

> [...]  or adding npx before [...]

This must be a platform / new thing in Node, under *nix at least, it would always use the locally installed copy of a package when used in that fashion (without npx) 🤔🤷🏻

**Comment by emregency** [comment]
Honestlly, I think there is a weird situation in my case. I do not know what's wrong with my installation. For example, I wanted to contribute to the `/app` by fixing some issues. But I cannot run storybook. All dependencies seem to be installed at the root level, so there is no storybook node module at the `/app` level. Thus, I cannot execute any script. That is the same problem with all other dependencies at the package level. That explains why I need to use npx. 

What I do not understand is why you guys don't have this same issue.

**Comment by rijkvanzanten** [comment]
> All dependencies seem to be installed at the root level, so there is no storybook node module at the /app level. Thus, I cannot execute any script. That is the same problem with all other dependencies at the package level.

Ah yeah, this is expected, as all dependencies are hoisted to the rootscope (to prevent duplications of node_modules). I run all dev commands from the root using lerna (see the `dev` script for example, that'll run `lerna` on your behalf). Running `npm install` and `npm run dev` from the root should work 🤔

**Comment by emregency** [comment]
Yeah it works that way unless I do the modifications that I mentioned above. 

How do you run storybook for the front-end for example?

**Comment by rijkvanzanten** [comment]
> How do you run storybook for the front-end for example?

You can run any npm command through `npx lerna exec <command> --scope <package>`

**Comment by emregency** [comment]
That's what I get. I really don't understand 😞

![lerna_exec_app_storybook](https://user-images.githubusercontent.com/10894960/105241479-07c7d900-5b6e-11eb-9965-2e3518691fda.PNG)

**Comment by rijkvanzanten** [comment]
The scope is the name of the package as per package.json/npm, so it'll be `--scope @directus/app`

**Comment by emregency** [comment]
Oh yes! Sorry for that. It really seems like packages cannot reach the root `node_modules`.

![lerna_exec_app_storybook](https://user-images.githubusercontent.com/10894960/105325093-82bfdc80-5bcc-11eb-99c4-89181547a0bb.PNG)

**Comment by rijkvanzanten** [comment]
TBH I haven't spun up storybook in a little while (there were numerous breaking changes between storybook and vue in patches/minor releases), so I kinda left it for a little too long 😬 I think this is more a problem with our storybook config now then the way we're running commands 🙂

**Comment by emregency** [comment]
I am not sure 🤔. I would rather say with something that happens with lerna and its package management. 

I need to give it a try on a *nix platform soon.

**Comment by Nitwel** [comment]
Is this still an general issue or couldn't you install it because of your setup?

**Comment by rijkvanzanten** [comment]
I was just able to install Directus fresh from source on a new laptop, so ehhhhhhhh _Works on my Machine™_ 🤷🏻 

It has to be some sort version/windows-vs-\*nix/npm thing?

**Comment by emregency** [comment]
Will give another try today, I will let you know.

**Comment by emregency** [comment]
Ok.. Still doesn't work.

I have installed WSL2 with an Ubuntu distro just for that issue. So no global installs, everything is fresh. 

`npm ERR! Cannot read property 'swagger-cli' of undefined`

**Comment by rijkvanzanten** [comment]
That's so strange! And this is from the root of the repo??

That error message confuses me a little too, we don't "read property 'swagger-cli'" anywhere. What version of NPM are you using?

**Comment by emregency** [comment]
Yep I am at the root. Here is a complete error log.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.11
3 info using node@v12.20.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle directus-monorepo@~prebuild: directus-monorepo@
6 info lifecycle directus-monorepo@~build: directus-monorepo@
7 verbose lifecycle directus-monorepo@~build: unsafe-perm in lifecycle true
8 verbose lifecycle directus-monorepo@~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/emregency/directus/node_modules/.bin:/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/emregency/directus/node_modules/.bin:/home/emregency/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle directus-monorepo@~build: CWD: /home/emregency/directus
10 silly lifecycle directus-monorepo@~build: Args: [ '-c', 'lerna run build' ]
11 info lifecycle directus-monorepo@~build: Failed to exec build script
12 verbose stack Error: directus-monorepo@ build: `lerna run build`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:314:20)
12 verbose stack     at maybeClose (internal/child_process.js:1022:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
13 verbose pkgid directus-monorepo@
14 verbose cwd /home/emregency/directus
15 verbose Linux 5.4.72-microsoft-standard-WSL2
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
17 verbose node v12.20.2
18 verbose npm  v6.14.11
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error directus-monorepo@ build: `lerna run build`
23 error spawn ENOENT
24 error Failed at the directus-monorepo@ build script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by rijkvanzanten** [comment]
@emregency Could it be that some build tools that node requires on under the hood are missing? I just came across this SO question with a similar message:
https://stackoverflow.com/a/60526334/4859211

**Comment by emregency** [comment]
I do have all of them. `gcc` `g++` `make` basically all `build-essentials`.

**Comment by alvincrespo** [comment]
@emregency I'm curious if you were able to nail down what the issue was exactly? I ran into this thread thanks in part to your log above. I'm running into the same `spawn` issue on another project.

**Comment by alvincrespo** [comment]
Interestingly enough I got past this issue on another project going from 12.16.1 ➡️ 16.10.0. Seems like an issue with Node child processes and WSL2 incompatibility.
