### ISSUE TITLE
"Make sure to define driver" error

### ISSUE THREAD

**Issue by 7aklhz** [directus/directus#3748]
Hi,

1) The issue and what you expected to happen
Hi,

I have installed the latest version of Directus using Docker. As such, I'm defining environment variables and here are the ones I have defined
<img width="299" alt="Capture d’écran 2021-01-19 à 13 08 02" src="https://user-images.githubusercontent.com/4387078/105067646-3071a500-5a80-11eb-8fa9-8fedb66cbd9a.png">

In STORAGE__DRIVER I'm putting s3. However, when I try to upload an image, I get the following error
<img width="519" alt="Capture d’écran 2021-01-19 à 13 05 28" src="https://user-images.githubusercontent.com/4387078/105067664-36678600-5a80-11eb-8b50-32821b313515.png">

Can you please help me ?

Thank you,

el_even

3) Your environment:
    DBMS : Mysql 5.7
    Deployment: Docker
    Browser: Brave

**Comment by rijkvanzanten** [comment]
What's the value for `STORAGE_LOCATIONS` ? I'm assuming there's a naming conflict between your storage location name, and the `STORAGE_<name>_DRIVER` (and the other) variables

**Comment by 7aklhz** [comment]
Thank you for getting back to me @rijkvanzanten . 

Here is a more detailed view of my variables
STORAGE_LOCATIONS=amazon
STORAGE_amazon_DRIVER=s3
STORAGE_amazon_PUBLIC_URL=xxxx

etc.

(FYI : i'm using a PaaS, Caprover, for running my docker images/Directus)

**Comment by rijkvanzanten** [comment]
> Here is a more detailed view of my variables
> STORAGE_LOCATIONS=amazon
> STORAGE_amazon_DRIVER=s3
> STORAGE_amazon_PUBLIC_URL=xxxx

This is different from what i'm seeing in the screenshot above though. Make sure you have it configured as follows:

```
STORAGE_LOCATIONS=amazon
STORAGE_AMAZON_DRIVER=s3
etc
```

**Comment by 7aklhz** [comment]
(it is different because I was just showing a part of it)
... ah, so you mean it has to be in capital letters. Yes, not it works ! Thank you for your help 👍
