### ISSUE TITLE
Revisions limit

### ISSUE THREAD

**Issue by nelolka** [directus/directus#3764]
### Issue
Admin app shows only first 100 revisions, while it should show all the revisions.

### Steps to reproduce
1. Make over 100 changes in the item.
2. The revisions list will contain only first 100 revisions and the counter will show 100.

### My environment
MySQL 8.0.22
Chrome 87.0.4280.141
Directus v9.0.0-rc.30

**Comment by benhaynes** [comment]
Yeah, this is a general pagination issue. We just need to add pagination to the end of that revision component.

**Comment by masterwendu** [comment]
Hi,

How should we implement it?

- A: next / prev page buttons, or even numbers of pages
- B: Load more button and just enlarge the list
- C: Automatically load more when user reaches the end and there are more revisions to load and enlarge the list.

I would go for B or C, because it's already a very long list with 100 entries.

Additional improvements would be make:
- Make date collapseable / collapse all, so you can find your desired date.
- Filter by user/date

**Comment by benhaynes** [comment]
Nice! Some thoughts...
> * A: next / prev page buttons, or even numbers of pages

This is what we use for data navigation now, so it does feel the most consistent. However, there's limited room in the info sidebar... so it might not fit. Another nice thing here is being able to quickly go to the first page (item creation).

> * B: Load more button and just enlarge the list

I like this, but worry about keeping hundreds of DOM items on the page.

> * C: Automatically load more when user reaches the end and there are more revisions to load and enlarge the list.

Could work, but we don't lazy load anywhere else (got rid of that from v8).

> * Make date collapseable / collapse all, so you can find your desired date.

Interesting idea! Could be manually toggled by clicking, and/or include a toggle all option.

> * Filter by user/date

If we were to add this, I think there should be a small text header for toggling on the filter inputs. I wonder how useful this would be, or how often it would be used (80/20)... might be a pretty power user feature.

**Comment by masterwendu** [comment]
Yeah then we can go for A.
When it's because of limited room we could use `<<` `<` `>` `>>` links. First, prev, next, last.

>     * Filter by user/date
Yeah you are right, I think it won't happen often, it's just if it happens and you have to search for 10 minutes it's not nice :)

**Comment by rijkvanzanten** [comment]
> When it's because of limited room we could use << < > >> links. First, prev, next, last.

This sounds like the most workable (and technically foolproof) way to me 👍🏻

**Comment by benhaynes** [comment]
Agree. I think our pagination component should work here... can't remember, but maybe we can set the "pages" prop to `0`?

**Comment by masterwendu** [comment]
I'll check it out.
