### ISSUE TITLE
Send email issue

### ISSUE THREAD

**Issue by amiraiouaz** [directus/directus#3771]
I am running directus locally with a MySQL database in a Docker container and when I try to request a password using the following endpoint:

http://localhost:8055/auth/password/request
body:
```json
{
"email": "{myemail}"
}
```

I can see that the request was successful but I am not getting any emails:

![image](https://user-images.githubusercontent.com/22788646/105347479-42218c80-5be7-11eb-8aac-62abf8f18f6c.png)

My environment variables:
```
EMAIL_FROM="{myemail}"
EMAIL_TRANSPORT="smtp"
EMAIL_SMTP_HOST="{myhost}"
EMAIL_SMTP_PORT="{myport}"
EMAIL_SMTP_USER="{myemail}"
EMAIL_SMTP_PASSWORD="{mypassword}"
```

When I start directus I get the following:

![image](https://user-images.githubusercontent.com/22788646/105347914-dab80c80-5be7-11eb-96c8-f6a7e0c467b4.png)

I know my smtp information are working because I am using them in another project.

Any ideas why this is not working?

Thank you!

---

### Project details
Directus Version: 9.0.0-rc.30
Environment: production
OS: macOS Big Sur (11)
Node: 15.3.0
Docker Image for MySQL: mysql/mysql-server

**Comment by rijkvanzanten** [comment]
No clue! Everything you've shared seems OK to me. 

Are you 100% sure all the credentials are correct? Maybe the SMTP host requires secure to be set? Maybe the "from email" isn't authorized in your smtp provider? Maybe it went to spam?

**Comment by amiraiouaz** [comment]
Hi there,

Thanks for the reply. I am 100% sure that the credentials are correct. I use the exact same ones in another project (using Strapi) and I don't have any issues, the emails are sent.

I have also already checked the spams and nothing is there.

I am trying to install it in one of my environment to see if I still have the same issue. I'll come back with this asap.

**Comment by rijkvanzanten** [comment]
You could also try using mailtrap.io or a similar debugger just to confirm everything is sending as expected

**Comment by amiraiouaz** [comment]
Hi again,

Thanks for mailtrap.io, I didn't know this solution.

So just you know, I did install directus in an environment in Jelastic Cloud. For some reasons I was not able to install it using the CLI in a Jelastic Cloud Node.js server so I used your Docker image directus/directus.

It worked and I received the email after calling {myhost}/auth/password/request. So I guess it is an issue in local. I'll try to investigate a bit more.

Question: Do you know when the following docs will be ready: [https://docs.directus.io/guides/extensions/email-templates.html#_1-setup-the-boilerplate](https://docs.directus.io/guides/extensions/email-templates.html#_1-setup-the-boilerplate)

I would like to customize the email that is sent in order to redirect it to a custom page.

Thanks.

**Comment by rijkvanzanten** [comment]
> Question: Do you know when the following docs will be ready: https://docs.directus.io/guides/extensions/email-templates.html#_1-setup-the-boilerplate

No I can't promise any timeline on that. Keep an eye on https://github.com/directus/directus/discussions/3104 for updates re that

**Comment by amiraiouaz** [comment]
All right, I will!

Just want to say that I was checking a bit the discussions/PR and I think you guys are really creating an amazing solution with v9. I am convinced it is going to be the best Headless CMS.

**Comment by rijkvanzanten** [comment]
Thanks! Really appreciate that ❤️
