### ISSUE TITLE
How to access current user details from custom interface and perform db queries?

### ISSUE THREAD

**Issue by jakeceballos** [directus/directus#3773]
I'm creating a custom interface to show select items pulled from an external API. How can I determine who the user is so that I can retrieve additional information from the database to perform the API request?

Thank you in advance!

**Comment by benhaynes** [comment]
Please add this as a GitHub discussion... Issues are for bugs and approved Feature Requests.

GitHub removed the ability for us to convert issues to discussions, otherwise I would do this.
