### ISSUE TITLE
Custom API Hook (before) does not allow modifying the payload

### ISSUE THREAD

**Issue by soyjimmysaenz** [directus/directus#3776]
Hello,
 I am trying to modify a specific property inside input/payload using a **custom API Hook** (`items.update.before`) 
this is my code:

```
return {
    "items.update.before": function(input, context) {
        if (context.collection !== "businesses") return input;
        return { ...input, status: "submitted" }; //it could be a default status like 'published' or 'draft'
    },
};
```

But it does not apply the change over status property.
I was debugging the directus source code, specifically this snippet (`services\items.ts`):

```
const customProcessed = await emitter.emitAsync(`${this.eventScope}.update.before`, payload, 
    event: `${this.eventScope}.update.before`,
    accountability: this.accountability,
    collection: this.collection,
    item: key,
    action: 'update',
    payload,
    schema: this.schema,
});

if (customProcessed) {
    payload = customProcessed[customProcessed.length - 1];
}
//(...)
```

I realized the **emitter module** always register an aditional event (`api/src/emitter.ts`):

```
emitter.on('*.*.before', (input) => input); 
```

That is the reason why the variable `customProcessed` is always an array with my modified payload and the original (* . *). I have confirmed it invoking `emitter.eventNames()` before `emitter.emitAsync` 

As a result, the payload is never modified. I think it applies to `.create.before` as well.

I would really appreciate your help.

## Environment:
DB: Postgres 13
Env: npx, localhost
Browser: Firefox 84.0.2
Node: v14.15.1
OS: Windows 10 (last build)
Directus: 9.0.0-rc.28

**Comment by Oreilles** [comment]
I had that issue the other day.

I figured out that whatever you try to return from the before hook, it actually is the input object that is passed along.

So the solution is to return Object.assign(input, { status: 'foo' }), or a similar option which returns the same input object as the one you got.
