### ISSUE TITLE
TLS E-mail

### ISSUE THREAD

**Issue by mscbpi** [directus/directus#3778]
1) The issue and what you expected to happen
Email connection fails on TLS (MX from Office365)

2) Exact steps to reproduce this issue

```
  EMAIL_FROM: directus@domain.com
  EMAIL_SMTP_HOST: domain.mail.protection.outlook.com
  EMAIL_SMTP_POOL: true
  EMAIL_SMTP_PORT: 25
  EMAIL_SMTP_SECURE: true
  EMAIL_TRANSPORT: SMTP
```

```
Email verification error: Error: 139737332825416:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
```
3) Your environment:
- Postgresql
- Kubernetes
- Any browser (not related
- directus 9.0.0-rc28

4) Any other relevant information we might need to reproduce this issue

**Comment by rijkvanzanten** [comment]
Can you try setting the port to 465 instead of 25? That seems to have helped for others:

https://github.com/nodemailer/nodemailer/issues/165#issuecomment-457291992

**Comment by mscbpi** [comment]
live.com a bit different from office365 enterprise.

The smtp relay host with auth (user licence needed) would be smtp.office365.com. We don't use this option.

The other option is direct send to MX server (another DNS record) and a connector to allow relay based on IP of the sender. 

This is what we chose. It used to work with directus. It uses port 25 only.

![image](https://user-images.githubusercontent.com/28528210/105541692-6a4ce080-5cf8-11eb-99a6-ea70648c0ea0.jpeg)

https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365

**Comment by christianrr** [comment]
Recently, the mail service login on _smtp.office365.com_ started to report with a 401 Unauthorized. I figured out, that Microsoft apparently started to enforce the use of TLS even on Port 25. For this reason, I thought EMAIL_SMTP_SECURE must be set to true. However, this returned the "SSL3 wrong version" error from above.

Surprisingly, the opposite is the case, EMAIL_SMTP_SECURE must be set to **false**. If unset or true the connection could not be established in my case. I guess, that if set to false the TLS version is chosen (correctly) during handshake.

So this config works for me for _smtp.office365.com_:

```
EMAIL_TRANSPORT="smtp"
EMAIL_SMTP_HOST="smtp.office365.com"
EMAIL_SMTP_PORT=25
EMAIL_SMTP_USER="from@domain.com"
EMAIL_SMTP_PASSWORD="..."
EMAIL_SMTP_SECURE="false" # this is important!!!
```

**Comment by TonyLovesDevOps** [comment]
> Surprisingly, the opposite is the case, EMAIL_SMTP_SECURE must be set to **false**. If unset or true the connection could not be established in my case. I guess, that if set to false the TLS version is chosen (correctly) during handshake.

I don't know _how_ you thought to try this, but thank you! 🦄  This was also required to send email via Postmark. 📫

**Comment by rijkvanzanten** [comment]
Interesting! Setting "secure" to false will _enable_ TLS 🤯 

> if true the connection will use TLS when connecting to server. If false (the default) then TLS is used if server supports the STARTTLS extension. In most cases set this value to true if you are connecting to port 465. For port 587 or 25 keep it false

https://nodemailer.com/smtp/
