### ISSUE TITLE
sorting in relational fields not working

### ISSUE THREAD

**Issue by erik-konrad** [directus/directus#3781]
The sorting defined in the app on relational fields is working in the app, but the API ignores the configuration. In the API response, the data on second relationlevel is only sorted by ID ascending. In V8 the sorting settings are working in the API on second level too.

**Comment by rijkvanzanten** [comment]
You can rely on `?deep[nested_field][sort]=my_sort_field`. Directus doesn't sort by default as of time of writing 👍🏻

**Comment by jarikus18** [comment]
Hi! I have the same problem, can't sort data by deep field
https://directus.webstaginghub.com/items/articles_translations?fields=*.*&meta=*&deep[articles_id][_sort]=-date_created

**Comment by rijkvanzanten** [comment]
Hi @jarikus18! `deep` is meant to operate on nested data-sets (eg arrays). In this case, `articles_id` is a single m2o record, so there's nothing to "sort" in there.

What you're looking for is the ability to sort the top-level items based on the nested relational value, which is currently not possible (see https://github.com/directus/directus/discussions/4502)
