### ISSUE TITLE
i18n object not available for custom extensions

### ISSUE THREAD

**Issue by miguelsimoes** [directus/directus#3782]
The VueI18n object is not available on custom extensions since:
1. `defineInterface` can't be accessed to be overwritten
2. The extensions are initialized expecting an object and not a function than can have the context (i18n) injected

**Comment by rijkvanzanten** [comment]
What version of Directus are you using? Where are you trying to use i18n? (In the index.js, or vue component?)

**Comment by miguelsimoes** [comment]
Hi @rijkvanzanten , I am trying to use it on version 9 under the index.js.

**Comment by rijkvanzanten** [comment]
Starting with https://github.com/directus/directus/commit/93f8b7720c948e8e5c6dd810d63efb0c6be4f047, interfaces no longer directly use `i18n` in the index config, but instead rely on `$t:` prefixed strings in the index 👍🏻
