### ISSUE TITLE
Use display template in drawer title

### ISSUE THREAD

**Issue by KonradDeskiewicz** [directus/directus#3783]
I'm not sure if this is something working wrong or I simply am misguided by how it works in other areas:

Here I am inside translations setup for my collection, and I'm setting up a display template to include language name:
![image](https://user-images.githubusercontent.com/17060750/105494870-b6c5fb00-5cbb-11eb-83c3-095ec8cb6996.png)

However when editing item in the collection with those translations title of the editor header stays intact:
![image](https://user-images.githubusercontent.com/17060750/105495007-e5dc6c80-5cbb-11eb-90af-4381852c9a31.png)

There is absolutely no information about which language is open at the moment.
Do I get the display template wrong?

**Comment by rijkvanzanten** [comment]
> I simply am misguided by how it works in other areas:

This! The detail page uses the display template in the header bar, but we must've forgotten to use it in the drawers 🙂 

Seeing that drawer more or less mirrors the detail page, it makes total sense that its title should work the same as the detail page title.

**Comment by Nitwel** [comment]
I would suggest using a title prop on the item-drawer which overrides the default values.
Now we have to transform `Hi {name}` to `Hi Rijk`, do we have a fuction for this already because I only could find the render-template component?

**Comment by rijkvanzanten** [comment]
@Nitwel We should do it the same way the collections module does it:

https://github.com/directus/directus/blob/8d0a23e2e65f50e1c84ac06e2a291f624dafbbce/app/src/modules/collections/routes/item.vue#L13-L23

**Comment by Nitwel** [comment]
My idea would be to add a title prop to drawer item which then passes it down to v-drawer and displays the formatted title with the render-template utils.

**Comment by rijkvanzanten** [comment]
No, lets use a `title` _slot_ instead of a _prop_ on v-drawer, so we can have consistency between the regular private-view and the v-drawer (which is effectively a "small" private-view in an overlay)
