### ISSUE TITLE
Unable to update multiple fields on one custom interface

### ISSUE THREAD

**Issue by miguelsimoes** [directus/directus#3786]
On version 8, we could something like `this.$store.dispatch("stageValue", args)` to update other fields that are not directly associated with the interface.

On version 9, there doesn't seem to exist a way to do the same. Already tried to inject `values` and do something like:
`this.values.value['field_name'] = newVal` but this doesn't mark the form updated nor changes the value of the field.

If the same is executed after the $emit event is triggered, the values argument is not even updated.

**Comment by benhaynes** [comment]
@rijkvanzanten — is this supported in v9? If not, we should convert this to a Discussion Feature Request. If it is, we should make sure it's working and add it to the Docs. 👍

**Comment by rijkvanzanten** [comment]
This is nearly the same as https://github.com/directus/directus/discussions/3583, so lets use that to track both 👍🏻
