### ISSUE TITLE
Low contrast on text editors while in dark mode

### ISSUE THREAD

**Issue by WoLfulus** [directus/directus#3788]
When using Markdown and/or WYSIWYG editors in dark mode, the caret color is black and some stylings doesn't contrast with the background, making it impossible to read the text, for example markdown headers.

![image](https://user-images.githubusercontent.com/412397/105516245-6bf4b500-5cb4-11eb-8033-0791fe5f5f47.png)

**Comment by MiniDigger** [comment]
I especially noticed this in the custom formats editor of a wysiwyg field
