### ISSUE TITLE
Pasting values into the search function doesn't trigger the search

### ISSUE THREAD

**Issue by goggi** [directus/directus#3792]
Hi!

If I paste a value into the search input the search isn't triggered. It gets triggered if I type or if I paste a value and add a space later.

Reproduce: 
1. Copy a text
2. Open a collection
3. Press on Search Icon
![image](https://user-images.githubusercontent.com/1946339/105554688-23ff7d80-5d08-11eb-82d9-529493e9caef.png)
4. Paste the value
5. Nothing happens. 
= This should trigger the search, but doesn't. 

Cheers!
---

### Project details
Directus Version: 9.0.0-rc.31
Environment: production
OS: Linux 4.15.0-88-generic
Node: 14.7.0

**Comment by shlaing** [comment]
@goggi It works with lowercase letters only.
FYI.

**Comment by goggi** [comment]
Hi! 

Now it reacts when i past the value, but the results are a bit strange. It doesnt find the value, but it showes its for a short second. See video: https://i.imgur.com/PJOimt8.gif

**Comment by Nitwel** [comment]
I might have fixed this in the bookmarks fix. The problem was that the value before pasting was null which caused the items not to update.
