### ISSUE TITLE
There is no way to create fields using @directus/sdk-js

### ISSUE THREAD

**Issue by mendo-** [directus/directus#3797]
1/2. Attempting to seed data and there is no way to create fields using the `"@directus/sdk-js": "^9.0.0-rc.31"`.
For example, using `directus.fields.create(payload)` or `directus.items('fields').create(payload)` you get:
`"errors":[{"message":"Route /fields/ doesn't exist.","extensions":{"code":"ROUTE_NOT_FOUND"}}]}`

This is expected because the endpoint should be `/fields/${collection}`, but `item.js` create function has the endpoint as `/fields/`.

**Update**: A work around is to pass in the fields on collection creation instead.

3. Postgres 12, Docker

**Comment by Kematia** [comment]
Another workaround is to use the sdk axios module

![image](https://user-images.githubusercontent.com/17851386/110207977-b5751a00-7e86-11eb-86ce-55d39bf2c74d.png)

**Comment by Kematia** [comment]
I'm working on some fields creation logic, and I'm noticing a couple issues: 

1. the .read() endpoint does not return the fields ID, so subsequent update/delete actions are impossible
2. the .read() endpoint does not use the passed filter, returning every item in directus_fields
3. the .create() endpoint does not work at all, requiring the above

@rijkvanzanten is it me/us doing something wrong or is the endpoint not working as intended? Willing to work on this

**Comment by rijkvanzanten** [comment]
> the .read() endpoint does not return the fields ID, so subsequent update/delete actions are impossible

Updates / deletes are done based on the field key, not the ID as stored in directus_fields, so this is false

> the .read() endpoint does not use the passed filter, returning every item in directus_fields

This is correct, and known behavior

> the .create() endpoint does not work at all, requiring the above

That seems to be a bug in the SDK 👍🏻

**Comment by Kematia** [comment]
> > the .read() endpoint does not return the fields ID, so subsequent update/delete actions are impossible
> 
> Updates / deletes are done based on the field key, not the ID as stored in directus_fields, so this is false
> 
> > the .read() endpoint does not use the passed filter, returning every item in directus_fields
> 
> This is correct, and known behavior

Cool! Maybe the misunderstanding stems from the docs? It says it works similarly to the .items() endpoint, so I assumed updates/deletes/query would behave the same, ie: pass a query to return the ids of the desired items and then use those to update/delete. 

> > the .create() endpoint does not work at all, requiring the above
> 
> That seems to be a bug in the SDK 👍🏻

I'll give it a look in the next couple days!
