### ISSUE TITLE
[ECONNREFUSED] on install

### ISSUE THREAD

**Issue by glowkeeper** [directus/directus#3802]
I'm running `npx create-directus-project blah`, but no matter what I enter, after being prompted for database and admin user details, I get:
```
[ECONNREFUSED] connect ECONNREFUSED 127.0.0.1:5432
```
etc.

Is there something I'm doing wrong? Any tips on what I could look into to solve this? I really wanna give directus a spin!

I can see in `blah`'s _package.json_ that I'm installing `directus 9.0.0-rc.31` and `pg ^8.5.1`. 

I'm running node v14.15.0 on a Macbook running Mojave. 

(ps. I tried going down the `npm install directus --save` then `npm install pg` route instead, but the docs don't contain anything like enough info' to get that working)

**Comment by rijkvanzanten** [comment]
Looks like you aren't able to connect to the database. Can you confirm your database credentials are correct?

**Comment by glowkeeper** [comment]
The install and for the credentials!

Why have you closed this?

**Comment by glowkeeper** [comment]
Ah - but I see, I should install this on an _existing_ database instance. Doh! But maybe the docs should make that clear?

**Comment by rijkvanzanten** [comment]
> The install asks for the credentials, so they must be right!

The installer asks for the credentials, but if you enter the wrong host/port combination, it won't be able to connect, thus causing the `ECONNREFUSED` being thrown by `pg` 🙂 

I don't know your setup of course, but this sounds like you don't have a Postgres database running under the host/port you're trying to connect to in the setup.

> Why have you closed this?

Because this is most likely a configuration issue, and not a bug in the installer 👍🏻

**Comment by pierrevanrensburg** [comment]
I agree that the documentation should tell you the pre-requisites (i.e. have a dB server, create the database, etc).

**Comment by sangdth** [comment]
I agree that the installation documentation should state the pre-requisites, that we already have a DB running already.

**Comment by azrikahar** [comment]
The docs does have a warning stating that the database should be running except for SQLite 👍

![image](https://user-images.githubusercontent.com/42867097/169949402-94654bb5-f404-452d-bee0-402de9c47b50.png)

**Comment by ImaCrea** [comment]
> The docs does have a warning stating that the database should be running except for SQLite 👍
> 
> ![image](https://user-images.githubusercontent.com/42867097/169949402-94654bb5-f404-452d-bee0-402de9c47b50.png)

I have to admit I did the same mistake. Maybe this info. would be more visible in a pre-requisite instead of a warning placed after the instruction.

**Comment by azrikahar** [comment]
Maybe there can be an additional step such as `Confirm database is already running` so that it'll be more obvious when skimming from top to bottom, but I'll defer to @erondpowell for the best approach here 🙂
