### ISSUE TITLE
[Feature suggestion] Lock of db structure

### ISSUE THREAD

**Issue by KonradDeskiewicz** [directus/directus#3803]
During a couple of previous projects that involved "CMS that can change DB structure" I was facing the problem of data/app corruption by "accidental clicks" from unaware users. Yes, I know that there are roles and permissions that can prevent that to some extent, but this problem is still valid if "unauthorized" access occurs.
What I want to suggest is adding an "env" flag like `DB_STRUCTURE_LOCKED = true` that should simply hide elements for data structure management once an app is delivered to a client, to avoid such accidents.

**Comment by rijkvanzanten** [comment]
Heya! We keep all feature requests under Discussions: https://github.com/directus/directus/discussions

Feel free to open it there 🙂
