### ISSUE TITLE
Minio/S3 Driver UnknownEndpoint

### ISSUE THREAD

**Issue by tonyisworking** [directus/directus#3807]
I'm using minio with the S3 driver for storage and it seems like the environment variables are not setup the same in v9 as it was in v8. I get a "UnknownEndpoint: Inaccessible host" error.

I'm running  Docker - image: directus/directus:v9.0.0-rc.31

Using the following env variables:

```
STORAGE_LOCATIONS=local
STORAGE_LOCAL_DRIVER=s3
STORAGE_LOCAL_ROOT=/media
STORAGE_LOCAL_ENDPOINT=https://sub.miniourl.org
STORAGE_LOCAL_KEY=xxx
STORAGE_LOCAL_SECRET=xxx
STORAGE_LOCAL_REGION=region1
STORAGE_LOCAL_BUCKET=bucket
```
The **STORAGE_LOCAL_BUCKET** variable gets prepended to the **STORAGE_LOCAL_ENDPOINT** and connects to "bucket.sub.miniourl.org".  which gives an **"UnknownEndpoint: Inaccessible host"** error.

If I change the variables to 

```
STORAGE_LOCAL_ENDPOINT=https://miniourl.org/bucket
STORAGE_LOCAL_BUCKET=sub
```

Files would be uploaded to the correct **bucket** but does not add to root folder **media**

If I change the endpoint to

```
STORAGE_LOCAL_ENDPOINT=https://miniourl.org/bucket/media
```

Then everything works and gets uploaded to where it should be.
The **STORAGE_LOCAL_ROOT** doesn't seem to be used.

Not sure if the docs should be updated to the correct behavior or should variables be corrected or if this is just an issue for minio users on v9 on nodejs.

I don't see anything on https://github.com/Slynova-Org/flydrive either for this bucket issue

But for anyone using Minio put the subdomain into the bucket area and append your actual bucket to the endpoint.

**Comment by rijkvanzanten** [comment]
> The STORAGE_LOCAL_ROOT doesn't seem to be used.

Yeah, as per the docs, that's used when using the `local` storage adapter:

![CleanShot 2021-01-26 at 10 36 25](https://user-images.githubusercontent.com/9141017/105866825-648a2000-5fc2-11eb-82ef-5d5fdb391938.png)
