### ISSUE TITLE
oAuth uses memory session

### ISSUE THREAD

**Issue by nathanvogel** [directus/directus#3814]
Hi! 

When starting directus with `NODE_ENV=production npx directus start` for example, I get the following warning: 

```
Warning: connect.session() MemoryStore is not designed for a production environment, as it will leak memory, and will not scale past a single process.
```

It happens directly on fresh Directus installs. Is that expected? 

This happens on my Windows machine, as well as on my Linux server, with the latest 9.0.0-rc32 and a MariaDB instance.

Thank you

**Comment by rijkvanzanten** [comment]
It's harmless in our use (this only used within oAuth callbacks) 👍🏻

**Comment by nathanvogel** [comment]
Okay cool thank you :)
