### ISSUE TITLE
Docs from official site takes to master branch docs

### ISSUE THREAD

**Issue by juancarlosjr97** [directus/directus#3817]
### Steps to reproduce

1. Click on edit the docs from the official site. e.g: https://docs.directus.io/reference/sdk-js.html#installation
2. Click on "Edit this page"
3. The page opened to https://github.com/directus/directus/edit/master/docs/getting-started/backing-directus.md

I tried to find where on the repository the branch is specified just like the VuePress documentation shows: https://docs.directus.io/reference/sdk-js.html#installation but I could not find it.

Thanks.

**Comment by rijkvanzanten** [comment]
This has been updated 👍🏻
