### ISSUE TITLE
Invite Email URL

### ISSUE THREAD

**Issue by Kingtona123** [directus/directus#3821]
I have sent the PUBLIC_URL="https://www.example.com/" as I am running behind a reverse proxy and when I invite a user they get an email with a link but it's broken as it comes through as https://www.example.com//admin/accept-invite?xxxxxxx

When I change the PUBLIC_URL="https://www.example.com/" to PUBLIC_URL="https://www.example.com" it breaks more stuff but as by default it is set to  PUBLIC_URL="/" I would expect it to be there! Is there a way around this or is this a bug?

---

### Project details
Directus Version: 9.0.0-rc.31
Environment: production
OS: Linux 5.4.0-52-generic
Node: 10.19.0

**Comment by rijkvanzanten** [comment]
> it breaks more stuff

What sort of stuff? We tend to use `PUBLIC_URL="https://www.example.com"` format and haven't seen any issues

**Comment by Kingtona123** [comment]
Apologies think I was setting it wrong, changing the top Public_URL to PUBLIC_URL="https://www.example.com" worked but as the OAuth documentation shows you need to use PUBLIC_URL="https://www.example.com/" I got confused. Working now.
