### ISSUE TITLE
Oauth flow redirects me to an empty page.

### ISSUE THREAD

**Issue by bitbaggi** [directus/directus#3832]
Hi Guys, 

i'm running a directus/directus:v9.0.0-rc.24 docker container.
I tried to add my own single sign on provider to directus oauth feature.

Now i can see a button under the noraml login button.
When i click it directus redirects me only to http://localhost:8055/auth/oauth/keycloak?redirect=http://localhost:8055/admin/login with an empty page on it.

My Env Variables are:
OAUTH_KEYCLOAK_KEY: "client_id"
OAUTH_KEYCLOAK_SECRET: "client_id"
OAUTH_KEYCLOAK_SCOPE: "openid email"
OAUTH_KEYCLOAK_AUTHORIZE_URL: "https://sso-host.de/auth/realms/master/protocol/openid-connect/auth"
OAUTH_KEYCLOAK_ACCESS_URL: "https://sso-host.de/auth/realms/master/protocol/openid-connect/token"

Any ideas why it not redirects me to my given OAUTH_KEYCLOAK_AUTHORIZE_URL?

**Comment by benhaynes** [comment]
Hey @bitbaggi — since this is more of a config/question, could you re-open it as a GitHub Discussion instead? GitHub removed the ability for us to "convert" this issue, otherwise we'd do it for you. Thanks!
