### ISSUE TITLE
Fix O2M treating new items as existing if they have a manual primary key

### ISSUE THREAD

**Issue by jojomillennium** [directus/directus#3834]
Directus v9.0.0-rc32

When trying to setup a O2M field, and updating it, the added item is not saved (see gif below).
I want to setup for my Amenity collection a field that will rely on another collection to record the "feedback criteria" I want.
I've setup the feedback criteria collection, then in my amenity collection I've setup the O2M relationship.
But when then I want to add feedback criteria to an amenity, it does not work.
Is it maybe because of the translation field in the feedback critera collection?
![2021-01-28_16-31-27 (2)](https://user-images.githubusercontent.com/6372094/106162447-6998cc00-6188-11eb-97ea-491f2ceca5cd.gif)

**Comment by jojomillennium** [comment]
Here are error logs I see in the console and network:
This shows up when I open the translation fields:

Query : /items/feedback_criteria_translations?fields[]=id&fields[]=languages_code&filter=%7B%22id%22:%7B%22_in%22:[]%7D%7D

![image](https://user-images.githubusercontent.com/6372094/106478690-bf7fb380-64a9-11eb-9445-c0f925a7af04.png)

**Comment by rijkvanzanten** [comment]
@jojomillennium Would you be able to share a DB dump where this happens?

**Comment by jojomillennium** [comment]
Sure @rijkvanzanten , here it is
[backup.sql.zip](https://github.com/directus/directus/files/5904995/backup.sql.zip)

**Comment by jojomillennium** [comment]
@rijkvanzanten was the dump helpful? Do you need anything else?
Many thanks

**Comment by rijkvanzanten** [comment]
Haven't had a chance to look yet, I'll let you know 👍🏻

**Comment by jojomillennium** [comment]
@rijkvanzanten were you able to have a look? Have I done a wrong configuration of my collection? Or is it coming from translations part of a O2M collection?
Thanks

**Comment by mscbpi** [comment]
This is indeed annoying. Any milestone planned for this one @benhaynes  @rijkvanzanten ?

Thanks

**Comment by benhaynes** [comment]
[**Unfortunately, we can not provide estimates on features or fixes**](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍 . Or contribute a pull-request... after all, this is OSS!
