### ISSUE TITLE
GraphQL UI crashes when you got multiple m2a relations

### ISSUE THREAD

**Issue by MiniDigger** [directus/directus#3835]
1. create 2 m2a relations
1. watch that directus created junction tables with item fields
1. go to directushost/path/graphql
1. observed the following error

```
{
"errors": [
{
"message": "Schema must contain uniquely named types but contains multiple types named \"item\".",
"extensions": {
"code": "INTERNAL_SERVER_ERROR"
}
}
]
}
```

rc32

since directus created those junction tables with the item field, I can't rename them (and I bet it would break directus if I renamed them manually in the db)

**Comment by rijkvanzanten** [comment]
> since directus created those junction tables with the item field, I can't rename them (and I bet it would break directus if I renamed them manually in the db)

You should be able to rename the field to whatever you want:


https://user-images.githubusercontent.com/9141017/106296390-9b10a680-621f-11eb-9669-0b0aca296537.mp4

That being said, it should still work in GraphQL ofc, even with duplicate names 👍🏻
