### ISSUE TITLE
Property batchEditAllowed checked in batchArchive button

### ISSUE THREAD

**Issue by pstuifzand** [directus/directus#3836]
The wrong property is checked in the batchArchive button. Is `batchEditAllowed`, but should be `batchArchiveAllowed`.

https://github.com/directus/directus/blob/959872b4990aef230426a7d6a20b122740fdc10d/app/src/modules/collections/routes/collection.vue#L114

**Comment by rijkvanzanten** [comment]
@pstuifzand Wanna open a PR for that one?
