### ISSUE TITLE
GraphQL Not fully supported? I get Schema is not configured for [..]

### ISSUE THREAD

**Issue by Hurdock** [directus/directus#3868]
Hello guys.

I'm trying to use the GraphQL interface and whenever I'm trying to do a mutation or a subscription it's saying that the schema is not configured for mutations / subscriptions.

Any ways to fix that or is that supposed to happen because the graphql support is not fully ?

**Comment by benhaynes** [comment]
Correct. I believe this is on the priority list for 9.0.0, but we're focused on stability first...

Closing as a duplicate for now:
https://github.com/directus/directus/discussions/3052
