### ISSUE TITLE
Add pagination to relational interfaces

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#3889]
If you have > 10 languages, the list gets too long. We should truncate after the first X, and have a "show all" button

This also extends to the repeater interface

**Comment by Nitwel** [comment]
Should the full list be opened in a modal (scrollable) or something different?

**Comment by benhaynes** [comment]
I'd like to hear @rijkvanzanten's thoughts, but one option is to open inline 0-10, expand inline for 10-20, and open in a drawer if 20+. If that's too complicated, I think inline will still work... this just avoids the issue of making it hard to scroll past when there are a LOT.

**Comment by rijkvanzanten** [comment]
Agreed. We'll have to figure out how to scale this to m2m/o2m too btw, especially if they're going to have a similar GUI structure (rows vs tables). Languages won't realistically be 150+ items, so we can theoretically render them all inline, but that won't fly for o2m/m2m

**Comment by Nitwel** [comment]
> We might want to treat this issue as "figure out pagination for relational interfaces"

I would say figure out pagination for lists in general because now, everything uses lists and when we get pagination there, it should be fairly easy to then apply this to m2m, o2m, m2a.

**Comment by rijkvanzanten** [comment]
We already have pagination for tabular/cards layouts if that's what you're saying. I'm referring to this new "inline-list" style for all of these. Having a "load the next 10 items" load-more button feels like a logical next step, but doesn't really help for relational sets of over 100 items. In that case, having the regular v-pagination (eg `[1] [2] [...] [21] [22]`) might make more sense, but without a way to sort/filter inline, it's still inconvenient. 

> and open in a drawer if 20+

This is another approach to solve that, but would that mean that the interfaces itself turn into a "manage" button once the set grows over `n` items? We might want to show the first 10 still, and then have a button to "show all" that opens the drawer-list. @benhaynes we should also come up with a way to be able to use "advanced filters" in the drawer-list 🤔

**Comment by benhaynes** [comment]
Yeah, it's important to know how that will work. Lists can be any size, so I wonder if there should be different ways to paginate. I think the _inline_ "Show More" works until you hit X (eg: 25+) threshold... then we need proper pagination. The drawer seems like a good standard for longer lists... but as Rijk mentioned, we need to make that full-featured with things like Advanced Search.

I agree that even if you have a lot of related items and a drawer is required, the interface should still show a preview of items (eg: up to 25) and then the "Show More" would open the full list in the drawer. It's also important to remember that sort might not work well when paginated... although I think Rijk's new manual sorting approach might not need the full list to work.

One other thing to keep in mind is that the M2A won't natively be able to go into a columnar table layout in the drawer. For these, we'd probably want to use the display template and have them render in a _single_ column.
