### ISSUE TITLE
Public_url not working

### ISSUE THREAD

**Issue by AgricolaJKB** [directus/directus#3901]
Hey guys.

I am more of an programming amateure and perhaps my problem/question is pretty obvious. But: I installed directus on my server, worked fine after a bit of tuning. I don't want it on my main url, but on "/directus". I have set the rewriteRules, that seems to work, the request is passed to directus hearing on port 8055. My problem is, that directus apparently assumes, that the extension /directus is an API-endpoint. I changed the public_url in .env from "/" to "/directus" and "{myDomain}/directus", but that didn't help. I am still getting this error message when trying to access directus:
{"errors":[{"message":"Route /directus doesn't exist.","extensions":{"code":"ROUTE_NOT_FOUND"}}]}

Do you know how to fix this problem?

I am using npx and Mariadb 10.3.

Thanks a lot!

**Comment by AgricolaJKB** [comment]
Just to be clear: The installation itself was successful, "npx directus start" starts the directus-server. But the API and, because of that, the webapp is not working because of the routing problem.

**Comment by benhaynes** [comment]
Hey @AgricolaJKB — this is not really a bug/issue, it's more of a config question. For that reason, I'll close this, but you can open a GitHub Discussion if you'd like: https://github.com/directus/directus/discussions
