### ISSUE TITLE
One-to-Many relationship with item using 'manually entered string' identifier not working

### ISSUE THREAD

**Issue by mpretty-cyro** [directus/directus#3908]
When attempting to add a new item in the Directus UI the item appears to be successfully created but does not get added (to the list, individual item collection or in the database).

<img width="832" alt="Screen Shot 2021-02-03 at 5 22 03 pm" src="https://user-images.githubusercontent.com/15862619/106706831-5f714480-6644-11eb-89e7-55d60bb989e7.png">
<img width="997" alt="Screen Shot 2021-02-03 at 5 22 11 pm" src="https://user-images.githubusercontent.com/15862619/106706843-61d39e80-6644-11eb-936b-3ff3f155fdce.png">

---

If you create the item directly in its collection you are able to link it via the relationship.

<img width="624" alt="Screen Shot 2021-02-03 at 5 23 04 pm" src="https://user-images.githubusercontent.com/15862619/106706966-934c6a00-6644-11eb-928e-bd375e077717.png">
<img width="812" alt="Screen Shot 2021-02-03 at 5 23 10 pm" src="https://user-images.githubusercontent.com/15862619/106706974-947d9700-6644-11eb-9ce7-771e66af778e.png">
<img width="860" alt="Screen Shot 2021-02-03 at 5 23 14 pm" src="https://user-images.githubusercontent.com/15862619/106706980-96475a80-6644-11eb-955f-3f0846fd9c1f.png">

But when you subsequently click on the item you receive an error

<img width="564" alt="Screen Shot 2021-02-03 at 5 24 00 pm" src="https://user-images.githubusercontent.com/15862619/106707032-a65f3a00-6644-11eb-929a-b7631d1bd0cf.png">

---

**Note:** If you use a UUID or an auto-incrementing integer for the identification field this seems to work correctly, just not for the 'manually entered string' identifier.

I'm running Postgres 12, using Docker with v9.0.0-rc.34 and Vivaldi 3.5.2115.87 (which is built on Chromium, so basically chrome).

**Comment by Nitwel** [comment]
I need a bit more information here. Could you describe how exactly you DB is setup?

Like
Collection A
- Field A: text-input | is to set the id
- Field B: alias | o2m field

Collection B
- Field C: numeric | generated id

**Comment by rijkvanzanten** [comment]
A DB dump where this is happening would be even more useful 🙂

**Comment by mpretty-cyro** [comment]
@Nitwel No worries so the setup is:

**Careers** _Note: This has "Treat as single object" selected_
id: UUID (Generated on Create)
job_listings (O2M relationship with job_listing - `id -> job_listing.careers`)

**Job Listing**
slug: Manually entered string (primary key)
status: Built-in status
sort: Built-in sort
date_updated: Built-in date_updated
careers (M2O relationship with careers - `careers -> careers.id`)
job_title: String (required)
location: String
excerpt: String (required)
description: Text (required, Markdown)

I captured a video for reference - I go to the careers page, try to add a job but when I go to save the job it dismisses the modal as though it succeeded but no job has been added (and no error appears in the console so it has silently failed):
https://user-images.githubusercontent.com/15862619/108641625-4bf32400-74f4-11eb-8227-093008b2e375.mov
