### ISSUE TITLE
Add invalid state to code editor in JSON mode

### ISSUE THREAD

**Issue by MiniDigger** [directus/directus#3911]
Rc34, custom interface that accepts a json.

when I enter invalid json (totally on purpose of course...) into the interface options, I can still save the field (and I dont get an error), but the value in the DB isnt changed (cause its invalid).

similarly, when I switch from the interface step to the field step back, my input gets reverted too.

I would expect some kind of error to inform the user that his input was invalid and didnt save.

**Comment by benhaynes** [comment]
I agree that it would make sense to always validate JSON before saving (for JSON type fields). If the value isn't going to save, then the user needs to know that.

**Comment by rijkvanzanten** [comment]
The code interface validates JSON:

<img width="412" alt="CleanShot 2021-04-23 at 19 09 35@2x" src="https://user-images.githubusercontent.com/9141017/115938072-77987900-a467-11eb-8158-5a435dbd708d.png">

By using that in your interface option, it should prevent any confusion
