### ISSUE TITLE
Directus 8.6.1 is not being configured

### ISSUE THREAD

**Issue by bilal-mahoon** [directus/directus#3912]
Hi, 
i am trying to configure Directus 8.6.1 on my machine but it is causing 
`{"error":{"code":14,"message":"This Directus instance has not been configured. Install via the Directus App (eg: \/admin) or read more about configuration at: https:\/\/docs.directus.io\/getting-started\/installation.html#configure"}}`

When i hit `http://localhost/directus-8.6.1/public` it automatically redirects to `http://localhost/directus-8.6.1/public/admin/#/install` but when i check into console its showing that error which is preventing directus installation. I tried to find solution inside old bugs but not be able to find proper solution because there are some links provided in solutions, those links are not accessible now.

Operating System: Window 10
PHP version: 8
using xammp server

Please help me out, I am stuck with this issue since yesterday

**Comment by MichaelNussbaumerGOWEST** [comment]
@bilal-mahoon https://github.com/directus/v8-archive

This repository is directus v9.

**Comment by bilal-mahoon** [comment]
Sorry i didn't checked
