### ISSUE TITLE
Permission Error when saving m2m relations

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/directus#3915]
When I try to update or create an item with a m2m relation, I get an permission error. (logged in as admin)

![image](https://user-images.githubusercontent.com/15796397/106743692-4cb13c80-6651-11eb-89d9-7a00c13b488b.png)

---

### Project details
Directus Version: 9.0.0-rc.34
Environment: production
OS: Linux 4.18.0-147.8.1.el8_1.x86_64
Node: 15.5.1

**Comment by rijkvanzanten** [comment]
@MichaelNussbaumerGOWEST Can you share a dump with a reproduction of this? That forbidden error is sometimes shown when it's trying to read a non-existing item through a relationship, so I'm wondering if this is an issue in the m2m interface, or if it's a data problem caused by something else

**Comment by MichaelNussbaumerGOWEST** [comment]
@rijkvanzanten I tried to send you the file via Discord but I can't :) Let me knwo how I can send you the file

**Comment by rijkvanzanten** [comment]
You can email it to rijk@directus.io 🙂

**Comment by MichaelNussbaumerGOWEST** [comment]
@rijkvanzanten done

**Comment by MichaelNussbaumerGOWEST** [comment]
@rijkvanzanten got the error, it is a custom hook which did the problem.
