### ISSUE TITLE
Issues editing text fields as non-admin user

### ISSUE THREAD

**Issue by martijnboland** [directus/directus#3916]
When editing **text** fields as **non-admin** users two issues happen:
- Code fields are not editable at all;
- WYSIWYG fields look like they're readonly, but are editable.

This happens in all browsers.

![image](https://user-images.githubusercontent.com/167455/106770967-c8ee5480-663e-11eb-9326-3a87bfbd873f.png)

**Comment by giuscia** [comment]
if you have the "developer tools" active on the Chrome browser and you reload the page, the code field becomes "editable".

can you fix it?

thanks

**Comment by YannickMol** [comment]
It looks like this has to do with when the "disabled" property is being called. It works indeed if the page is refreshed, but doesn't work if you are navigating to a different page in the app and navigate back. 

https://user-images.githubusercontent.com/13256289/107990831-98f76780-6fd5-11eb-8379-62c56005137e.mp4

**Comment by YannickMol** [comment]
Also, part of this is duplicated by #2907.

**Comment by rijkvanzanten** [comment]
@YannickMol I'll close #2907 in favor of this one (as this also covers `code`)

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/directus/pull/4085

**Comment by YannickMol** [comment]
@rijkvanzanten, the first part of the issue (the code part) is not fixed by #4085, that was a styling issue only. Can you reopen this issue?
