### ISSUE TITLE
Collections suddenly inaccessible; missing primary key.

### ISSUE THREAD

**Issue by tstec-polypoly** [directus/directus#3922]
1) I should be able to access the Cookies Collection ... instead I get an error in the browser "Unexpected Error".

<img width="323" alt="Screen Shot 2021-02-04 at 12 05 55" src="https://user-images.githubusercontent.com/63229617/106884251-571b1700-66e1-11eb-9c2b-1d2d00ae65b0.png">

Here's the paste from copying the error details.
```
{
  "errors": [
    {
      "message": "You don't have permission to access this.",
      "extensions": {
        "code": "FORBIDDEN"
      }
    }
  ]
}
```

Also, the following line shows up repeatedly in the log.

> directus_1  | 11:02:23 ⚠️  Collection "cookies" doesn't have a primary key column and will be ignored

I will try to fix this by manually adding the key back in Postgresql.

2) **Reproducing**

I'm unsure of how this occurs, but I assume the primary key gets deleted at some point.

3) **My environment:**
* Docker
  * Postgres 12
  * Redis 6
  * Directus v9.0.0-rc.34
* Brave 1.18.70

**Comment by rijkvanzanten** [comment]
> I'm unsure of how this occurs, but I assume the primary key gets deleted at some point.

Fields aren't (and obviously shouldn't be) deleted just out of nowhere 👀 

It's going to be near impossible to fix this (assuming it was caused by Directus) without an accurate way to reproduce it 😞 If it happens again, let me know here with exactly what steps you took before it happened so we can try to figure out what's going on 👍🏻

**Comment by rokdd** [comment]
I have the same problem and luckily have a productive instance as a backup. I am a bit worried that at some point it will also happend in the productive instance. Is there any update which might be the reason that the primary keys are getting destroyed?
