### ISSUE TITLE
Updating schema of field breaks when type isn't provided

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#3928]
Posting

```json
{
  "schema": {
    "default_value": "Example"
  }
}
```

to PATCH /fields/:collection/:field

throws `table[field.type] is not a function` cause of the `type` property missing. `type` shouldn't be required on update

**Comment by asharonbaltazar** [comment]
Hello, I'd like to help out. However, after following the contributing instructions on your website, I keep getting an error:

![image](https://user-images.githubusercontent.com/58940073/106928760-23d48a00-66d9-11eb-886c-c6d29f06e8fa.png)

Any help would be appreciated.

**Comment by rijkvanzanten** [comment]
@asharonbaltazar Looks like your postgres database isn't running on port 5432, or your credentials are wrong. Are you sure SSL has to be enabled for localhost Postgres?
