### ISSUE TITLE
Check Interface and Display names

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#3934]
Rename `wysiwyg` to `rich_text_html` or `html`

Change `m2a-builder`, `many-to-many`, `many-to-one`, and `one-to-many` for more UI descriptive set of names

eg: `m2a-builder` / `m2m-table` / `o2m-table` / `o2m-repeater`

**Comment by rijkvanzanten** [comment]
Rename `tabular` layout to `table`

**Comment by rijkvanzanten** [comment]
| Before                       | After                        |
| ---------------------------- | ---------------------------- |
| `button-links`               | `presentation-links`         |
| `checkboxes`                 | `select-multiple-checkbox`   |
| `code`                       | `input-code`                 |
| `color`                      | `select-color`               |
| `datetime`                   | `datetime`                   |
| `divider`                    | `presentation-divider`       |
| `dropdown`                   | `select-dropdown`            |
| `dropdown-multiselect`       | `select-multiple-dropdown`   |
| `file`                       | `file`                       |
| `hash`                       | `input-hash`                 |
| `icon`                       | `select-icon`                |
| `image`                      | `file-image`                 |
| `m2a-builder`                | `list-m2a`                   |
| `many-to-many`               | `list-m2m`                   |
| `many-to-one`                | `list-m2o`                   |
| `markdown`                   | `input-rich-text-md`         |
| `notice`                     | `presentation-notice`        |
| `numeric` <sup>[1]</sup>     | --                           |
| `one-to-many`                | `list-o2m`                   |
| `radio-buttons`              | `select-radio`               |
| `repeater`                   | `list`                       |
| `slider`                     | `slider`                     |
| `slug` <sup>[1]</sup>        | --                           |
| `tags`                       | `tags`                       |
| `text-input`                 | `input`                      |
| `textarea`                   | `input-multiline`            |
| `toggle`                     | `boolean`                    |
| `translations`               | `translations`               |
| `tree-view`                  | `list-o2m-treeview`          |
| `user` <sup>[2]</sup>        | --                           |
| `wysiwyg`                    | `input-rich-text-html`       |
| `\_system/collection`        | `system-collection`          |
| `\_system/collections`       | `system-collection-multiple` |
| `\_system/display-template`  | `system-display-template`    |
| `\_system/field`             | `system-field`               |
| `\_system/interface`         | `system-interface`           |
| `\_system/interface-options` | `system-interface-options`   |
| `\_system/scope`             | `system-scope`               |
| `\_system/system-language`   | `system-language`            |
| `\_system/tfa-setup`         | `system-tfa-setup`           |
