### ISSUE TITLE
no proper way of nullifying a date

### ISSUE THREAD

**Issue by coolov** [directus/directus#394]
The helper method ```serializeArray``` in jQuery returns an empty string when a ```<input type="hidden">``` lacks a value. If we submit the empty string to the the API it will trow an error. Writing empty strings to a datetime column is forbidden! There is no proper way of nullifying a date!

**Comment by benhaynes** [comment]
**[Migrated to FeatHub](http://feathub.com/directus/directus/+4)**

Please use the [Directus FeatHub](http://feathub.com/directus/directus) to vote for features or make new request. Accepted feature requests will be added to GitHub Issues.
