### ISSUE TITLE
Auth token refresh doesn't work with tab in background in Chrome

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#3940]
1) The issue and what you expected to happen\
Right before the access token expires, Directus will refresh it to keep the session alive. However, when Directus is in a tab in the background it doesn't seem to do this (or isn't able to). We should come up with a way where it tries re-authenticating on first user interaction after an idle time.

2) Exact steps to reproduce this issue\
Open Directus in a new tab, and don't use it for the expiration time of the token. You'll be greeted with the login page saying "Session Expired". On refresh, you'll still be logged in (as the refresh token hasn't expired yet).

3) Your environment:
    - Directus v9.0.0-rc.34
    - Chrome 87

**Comment by nickluger** [comment]
I think this is affecting security and should get more attention, as people tend to use very refresh token timeouts to avoid having to re-login all the time and many people use Chrome.

**Comment by rijkvanzanten** [comment]
What do you mean by "as people tend to use very refresh token timeouts to avoid having to re-login" ?

**Comment by nickluger** [comment]
very **long** timeouts, sorry, missed that word 😅. The default timeout was 15 min. One might set it up to several days if one does not want users to constantly login or hard-refresh the page.
