### ISSUE TITLE
No width/height generated for gif asset

### ISSUE THREAD

**Issue by jianliao** [directus/directus#3949]
When upload a png file, the server will return width/height in api call. But it is not true for gif.
```
{
    "data": {
        "width": null,
        "id": "d0b4d91b-7e14-4e25-b3e1-0b2c87d7fff1",
        "filename_download": "behavior-animating_4Gs7c2U8UUYe6pmR9yfwT9.gif",
        "height": null,
        "description": "Key example of a tooltip in a neutral variant with a gray color. The tooltip fades in and out upon a cursor hover interaction with a button, label Save. Tooltip label, Saving applies your new settings right away.",
        "modified_on": "2021-02-02T20:21:03Z"
    }
}
```

Directus version:
v9.0.0-rc.34

**Comment by workatease** [comment]
we only calculated the metadata for below types and GIF is not part of it.
['image/jpeg', 'image/png', 'image/webp']

https://github.com/directus/directus/blob/79eff4d5b253ee263d35fa40b44245ff12a2b0f8/api/src/services/files.ts#L51

do we need to add other types of images

**Comment by rijkvanzanten** [comment]
We should be able to extend it to these, though not all are supported for image manipulation (eg resizing):

https://sharp.pixelplumbing.com/#formats

**Comment by workatease** [comment]
I agree... Do you think we can add all the supporting file type or gif for now and enhance it based on needs

**Comment by rijkvanzanten** [comment]
Yeah totally, we should _read_ the metadata from more file types (including .gif), but only allow _generating_ for the ones that are actually supported 🙂
