### ISSUE TITLE
Add default displays to directus_users

### ISSUE THREAD

**Issue by dimitrov-adrian** [directus/directus#3971]
1) The issue and what you expected to happen

If switch users list from cards to list view, the role is displayed with ID, the same is applied to avatar as well.

It will be better if role name is displayed and image for avatar.

![image](https://user-images.githubusercontent.com/1009639/107280004-735fe080-6a60-11eb-8cdd-084a16a7572d.png)

2) Exact steps to reproduce this issue

Go /admin/users.
Set display mode to list view

3) Your environment:
c049daf

**Comment by YannickMol** [comment]
I can get the avatar to work by adding `display: image`. However, not sure how to set the name of a related collection field in a display field. Any help?

**Comment by rijkvanzanten** [comment]
@YannickMol You can use the `related-values` display and give it a display-template like `{{ name }}` 🙂
