### ISSUE TITLE
Remove Overview from Docs

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#3988]
This page should be deleted. It is not part of our docs and has all broken links. **Getting Started > Intro** should be the initial page of the Docs module.

![Screen Shot 2021-02-09 at 2 52 47 PM](https://user-images.githubusercontent.com/522079/107420159-97660500-6ae6-11eb-9699-ab9cb99e80f3.png)

**Comment by rijkvanzanten** [comment]
This was fixed in #3951
