### ISSUE TITLE
SDK - Persistent login not working

### ISSUE THREAD

**Issue by juancarlosjr97** [directus/directus#4013]
1) The issue and what you expected to happen
    After a user has logged in, and the page is refreshed the user will still be logged in.

2) Exact steps to reproduce this issue
- Create a global configuration of Directus
```
import DirectusSDK from "@directus/sdk-js";
import localforage from "localforage";

import environment from "@environment";

export const directus = new DirectusSDK(environment.API_URL, {
  auth: {
    storage: localforage,
    mode: "json",
    autoRefresh: true,
  },
});
```
- Login using the SDK
```
 directus.auth
    .login(userCredentials)
    .then(() => {
      const authenticationStatus = true;
      store.dispatch(authenticationSlice.actions.updateAuthenticationStatus({ authenticationStatus }));

      store.dispatch(
        notificationsSlice.actions.enqueueNotification({
          key: keyGenerator(),
          message: "Logged in successfully.",
          variant: "success",
          duration: 5000,
          verticalPosition: "top",
          horizontalPosition: "center",
          closeButtonText: "OK",
        })
      );
    })
    .catch((error) => {
      props.setLoadingValue(false);

      const errorMessage = getErrorMessageSignIn(error.response.data.errors[0].message);

      store.dispatch(
        notificationsSlice.actions.enqueueNotification({
          key: keyGenerator(),
          message: errorMessage,
          variant: "error",
          verticalPosition: "top",
          horizontalPosition: "center",
          closeButtonText: "OK",
        })
      );
    });
```
- After the user has been logged in successfully, refresh the page and the user will be logged out. 
- Requesting 
```
    console.log(
      directus.users.me
        .read()
        .then((data) => console.log(data))
        .catch((error) => console.error(error))
    );
```
Returns an error that the user does not have access because if not logged in, even though the key `directus_refresh_token` is set and valid.

3) Your environment:
- Directus rc.34
- AWS RDS PostgreSQL
- React 16 + TypeScript Version 3.9.7

4) Additional information

I tested also using 

```
export const directus = new DirectusSDK(environment.API_URL, {
  auth: {
    mode: "cookie",
    autoRefresh: true,
  },
});
```

But it did not work.

**Comment by nexflo** [comment]
Yup seeing the same.
Also when I try to logout and login again... (as the autorefresh token hits the endpoint...) I cant login as it says:
message: "Token expired.", extensions: {code: "INVALID_CREDENTIALS"}

**Comment by workatease** [comment]
I am able to replicate it. I see that refresh endpoint id not called after the autorefresh is set.
The return statement below stops the method from executing further.

https://github.com/directus/directus/blob/f7a9b25e3b20740518798f9c3cb54432c2575544/packages/sdk-js/src/handlers/auth.ts#L95

**Comment by workatease** [comment]
> I am able to replicate it. I see that refresh endpoint id not called after the autorefresh is set.
> The return statement below stops the method from executing further.
> 
> https://github.com/directus/directus/blob/f7a9b25e3b20740518798f9c3cb54432c2575544/packages/sdk-js/src/handlers/auth.ts#L95
due to this the autorefrresh cannot be used in the setting. and when setting it to false it works

**Comment by rijkvanzanten** [comment]
@workatease Wanna open a PR for that?? 🙂

**Comment by workatease** [comment]
sure @rijkvanzanten will open PR in some time
