### ISSUE TITLE
Filter - is empty / isn´t empty for datetime error

### ISSUE THREAD

**Issue by nordcart** [directus/directus#4023]
Filtering **empty**/**isn´t empty** for datetime-fields in presets/bookmarks/collections results in error. 

This happens when some datetime-fields are empty.

This happens with postgresql databases. MySQL works fine.

---

### Project details
Directus Version: 9.0.0-rc.36
Environment: production
OS: Linux 5.4.72-microsoft-standard-WSL2
Node: 14.15.5

**Comment by rijkvanzanten** [comment]
Duplicate of https://github.com/directus/directus/issues/3747
