### ISSUE TITLE
Preset & Bookmark redirects to main collection after editing a field

### ISSUE THREAD

**Issue by nordcart** [directus/directus#4025]
Preset & Bookmark redirects to main collection after editing or adding data, shouldn´t it be redirected to the bookmark?

---

### Project details
Directus Version: 9.0.0-rc.36
Environment: production
OS: Linux 5.4.72-microsoft-standard-WSL2
Node: 14.15.5

**Comment by rijkvanzanten** [comment]
I'm not sure what you're talking about.. 

> after editing or adding data

Editing / adding data where? 

If you're in Settings > Presets & Bookmarks and edit a preset there, it should redirect you back to the Settings > Presets & Bookmarks page.

**Comment by nordcart** [comment]
1. Open an item from a bookmark
2. Save the item or go back
3. You are now redirected to the main collection (should go back to the bookmark from which you opened the item)

**Comment by Nitwel** [comment]
We have this on purpose because there was a bug redirecting back to the last page which I sadly don't remember and I only could find this commit but not the issue that was related to it. https://github.com/directus/directus/commit/cad36ee04254f48a574f30b619827d3ad167a362

**Comment by rijkvanzanten** [comment]
@Nitwel We had "true" back before (eg going to history -1 = last page), but that turned out to be more confusing than anything. The back button currently opens the collection you're currently in. We could consider adding a `?bookmark=132` parameter when you navigate to the single item, which would allow us to navigate back to the correct bookmark on back 🤔

**Comment by nordcart** [comment]
> @Nitwel We had "true" back before (eg going to history -1 = last page), but that turned out to be more confusing than anything. The back button currently opens the collection you're currently in. We could consider adding a `?bookmark=132` parameter when you navigate to the single item, which would allow us to navigate back to the correct bookmark on back 🤔

This might work, it is really confusing editing an item from the bookmark and then being redirected to a different view.
