### ISSUE TITLE
Many to Many fields and Multiple File field erroring out.

### ISSUE THREAD

**Issue by MichaelEPope** [directus/directus#4040]
1) The issue and what you expected to happen

When you create a 'Multiple files' field or a 'Many to Many' field in Directus, there is an error.

2) Exact steps to reproduce this issue

-Install a fresh directus (in Docker for me)
-Create a Collection called 'products' (checkmark all of the sort, created date, etc. fields)
-Start creating a 'multiple files' field called 'files' (or you could also do this with a 'many to many' field for another collection)
-In the relationships section, let 'Auto Fill' pick the appropriate junction collection name and field names in the junction collection.
-You can select a corresponding field if you want (it's not required)
-In the Interface section note that 'Sort Field has a yellow triangle mark.  This might be related to what is causing the error (and it's because the auto-created collection doesn't have a sort field)
-In display, select either Raw Value or Related Values, it doesn't matter.
-You get a Internal Server Error:

The Yellow Triangle
![image](https://user-images.githubusercontent.com/19957372/107832648-d776f300-6d45-11eb-9547-6dcf346d37ec.png)
The Error
![image](https://user-images.githubusercontent.com/19957372/107832683-f07fa400-6d45-11eb-8199-131b24c1383e.png)
Docker Log for Directus Container
![image](https://user-images.githubusercontent.com/19957372/107832729-11e09000-6d46-11eb-88b3-6cb0ab627602.png)
There was not any interesting information in the Cache or Database logs.

3) Your environment:

I'm using Directus v9.0.0-rc.36.
Databse is Postgres, whatever version you are using in Docker
Deploying using Docker
Viewing in Brave (pretty much Chrome)

4) Any other relevant information we might need to reproduce this issue

Nothing else I can think of.

**Comment by MichaelEPope** [comment]
Also, I ran it in Chrome and Firefox, and I'm still getting the same error, so I'm pretty sure it's not browser related.  Feel free to let me know if you need more information.

**Comment by MichaelEPope** [comment]
On doing some more testing, the yellow triangle sort warning might not be related after all.  I manually created a collection join table beforehand, and it still had the error, even though that particular warning was resolved.

**Comment by rijkvanzanten** [comment]
This was fixed and released in rc.37 👍🏻

**Comment by MichaelEPope** [comment]
Thanks!  Your the best!
