### ISSUE TITLE
System collections are visible to the public

### ISSUE THREAD

**Issue by pzehle** [directus/directus#4043]
On a clean installation of rc37, even though the "public" role has no permissions to view system collections, these are visible to the public. Calling `/collections` or `/fields` or whatever other system collection that does not have permissions from the public role, are completely visible.

**Reproduce:**
Clean installation.
Run from postman: http://localhost:8055/collections
Make sure that on the public role, system collections are all turned off.

**Installation info:**
What version of Directus you are using. rc37
Which DBMS are you using. Postgres
Which deployment are you using. npx
What browser are you using. Chrome, but technically any browser.

**Other issue:**
This issue also happens when creating a custom endpoint. I remember back in v8, calling any item service inside custom endpoint, without any authentication information, depending on the role permissions would return a forbidden error. In this last version, calling any service that has no access from a specific role, will anyway return the results inside. This can be a separate issue if requested, but imo I think this comes from the same place, no acces rights checked.

Thank you.

**Comment by pzehle** [comment]
Ok. I deleted the whole installation and made a new one. Don't know what happened but now it doesn't return anything, unless I give specific permissions to it. Two points remain though:

1. If the role doesn't have permission to view the collection, then the http status code will be 200, but no information will be returned. I assume it should return http status code forbidden and return a json response saying the role/user has no permissions to view that collection.
2. Still when creating a custom endpoint exactly as in the docs example, creating that recipes collection and giving NO access to the public user, though accessing that endpoint through the API, it WILL return the results, so the issue remains.

Thank you.

**Comment by rijkvanzanten** [comment]
> Still when creating a custom endpoint exactly as in the docs example, creating that recipes collection and giving NO access to the public user, though accessing that endpoint through the API, it WILL return the results, so the issue remains.

You have to pass the accountability object to the service in order to have it check for permissions. I've updated the example in the docs to include this 👍🏻
