### ISSUE TITLE
Can't update existing alias-type field

### ISSUE THREAD

**Issue by magomimmo** [directus/directus#4048]
upgrading from rc.34 to rc.37 breaks even the simplest m2m relationships (e.g. recipe/ingredient)

https://user-images.githubusercontent.com/1448905/107878409-c3143100-6ed2-11eb-92ee-318a18e96c66.mp4

---

### Project details
Directus Version: 9.0.0-rc.37
Environment: production
OS: Linux 5.4.0-65-generic
Node: 14.15.5

**Comment by jianliao** [comment]
Same error occurred when specify sort field for M2A collection.
