### ISSUE TITLE
sort by numeric field is being done alphabetically

### ISSUE THREAD

**Issue by brpaz** [directus/directus#4049]
When I have a collection with a numeric field, the sorting on the list view is being done alphabetically and not by value.

Ex: If I have records with a value 10, 3, 12, when sorting it becomes 10, 12, 3. and not 3 , 10, 12.

**To reproduce**

Create a collection with a numeric field and apply a sort by that value on the list view

**Environment:**

Directus: v9.0.0-rc.37 Docker image with Postgres 12 database

**Comment by benhaynes** [comment]
Is this in the App, API or both?

**Comment by rijkvanzanten** [comment]
Fairly sure this is when you sort "client side" (eg when your total amount of rows in the DB is less than the current page size), as that sorts based on the rendered value in the table instead of SQL ORDER BY

**Comment by rijkvanzanten** [comment]
Hmm, this seems to work as expected on my end:

https://user-images.githubusercontent.com/9141017/110040720-3dd1ae80-7d11-11eb-838b-199aed0e7c9a.mp4

Are you sure the column you're sorting on is a numeric type, and not accidentally a string? Do you have any hooks that might cause trouble?

I'll close this for now as I confirmed it working on a newly setup numeric field on PG 12.3 (and SQLite), but we can reopen if we can reproduce 👍🏻
