### ISSUE TITLE
Archiving an already archived post deletes said post.

### ISSUE THREAD

**Issue by cristobalbahe** [directus/directus#4051]
Hello everyone, 

I don't know if this is how archiving it's supposed to work, but I've just come across it and I think it could be classified as a bug.

I have a collection that have a status field and two choices for values: Published and Archived.

From the list view, if I select a post (or several) that is already archived and then click on archive, this post get deleted.

I think the archive button should not be available if posts are already archived, but more importantly should not delete these posts.

I've checked my database and they are effectively deleted.

Also, thanks everyone working on Directus for doing such an amazing job!

**Comment by benhaynes** [comment]
Thanks for reporting this! Can you send over the archive settings for that Collection, Directus version, database vendor, etc?

**Comment by cristobalbahe** [comment]
Sure!
Directus Version: 9.0.0-rc.34
Environment: production
OS: Windows_NT 10.0.18363
Node: 12.18.2
Database: mysql
Regarding the archive settings, i just ticked the status option when creating a new collection under Optional System Fields.
The fields created is a String type field, with key name = status.
I don't know what more info I can provide to clarify but please let me know if you need any.

**Comment by rijkvanzanten** [comment]
This was fixed in https://github.com/directus/directus/commit/3103d9d7eab1ff1afdcfed7fedb28cf929ee8a41
