### ISSUE TITLE
Infinite loop auth/refresh when using ACCESS TOKEN TTL 30d

### ISSUE THREAD

**Issue by Silbad** [directus/directus#4054]
Hello, when I'm login in app, I have an infinite loop request auth/refresh (9.0.0 rc-37, mysql8)
![image](https://user-images.githubusercontent.com/31576982/107962047-d8f32600-6fa6-11eb-90fc-4b302dbec0f4.png)

**Comment by rijkvanzanten** [comment]
@Silbad Do you have any extensions / settings running that might cause trouble here? I'm not able to reproduce it on my end 🤔

**Comment by Silbad** [comment]
I just change ACCESS_TOKEN_TTL & REFRESH_TOKEN_TTL... I tell you more info tomorrow...

**Comment by rijkvanzanten** [comment]
@Silbad What did you change those values to? If the access token TTL is low/invalid, it might have to refresh very often 🤔

**Comment by Silbad** [comment]
I don't have access to the server now (I'm at home), I put REFRESH_TOKEN_TTL="90d" but I'm not sure for ACCESS_TOKEN_TTL... Maybe I made a mistake.

**Comment by Silbad** [comment]
Ok I managed to access the server, I put ACCESS_TOKEN_TTL="30d"

**Comment by Silbad** [comment]
I test today with ACCESS_TOKEN_TTL="15m" and it's ok ;)
with ACCESS_TOKEN_TTL="30d" => ko
with ACCESS_TOKEN_TTL="45800m" => ko

**Comment by rijkvanzanten** [comment]
TIL `setTimeout` in JS breaks with numbers bigger than `2147483647`. `30d` in ms is `2592000000` which makes `setTimeout` reset to `0` which means it refreshes non-stop.
