### ISSUE TITLE
[M2A] Can't delete/edit reference in a M2A collection 

### ISSUE THREAD

**Issue by jianliao** [directus/directus#4058]
1. In M2A, user can create reference any type, but user can't delete or edit it.
![image](https://user-images.githubusercontent.com/1207520/107972470-c0fcb180-6f68-11eb-87f9-d56134a90240.png)

Warning message when clicked delete:
![image](https://user-images.githubusercontent.com/1207520/107972524-d245be00-6f68-11eb-860e-973b6095f6f8.png)

Warning message when clicked edit:
![image](https://user-images.githubusercontent.com/1207520/107972557-df62ad00-6f68-11eb-8f83-b649d7bb4500.png)

2. rc.37

**Comment by jianliao** [comment]
#4077

**Comment by rijkvanzanten** [comment]
Fixed in #4077
