### ISSUE TITLE
getDBQuery generates invalid group by clause on some RDBMS types

### ISSUE THREAD

**Issue by martijnboland** [directus/directus#4078]
The fix for issue #3798 introduces a group by clause in Select queries that is invalid for MS SQL Server, Oracle and I also think MySQL could be affected, depending on the ONLY_FULL_GROUP_BY SQL setting.

The problem is that on these databases, with a group by query, all select columns MUST be either an aggregate or in the group by expression. This is not the case. Only the id column is in the group by expression to prevent duplicate results.

It might be possible that this issue can be fixed with a select distinct query instead of the group by, but to be honest, I'm not sure whether this would cause any unwanted side-effects.

**Comment by rijkvanzanten** [comment]
Worth a shot! Looks like `knex` has a `.distinct()` we can use instead 👍🏻 http://knexjs.org/#Builder-distinct

**Comment by martijnboland** [comment]
Unfortunately, .distinct() does not work with mssql because there are columns with the 'text' type (the json columns) and those are not allowed to be in a distinct select. This is because knex defaults to the 'text' datatype for databases that have no proper json support.

Usually, when I try to avoid cartesian products when filtering on o2m joined tables, I use a subquery instead of a join 
```
where table.id in (select fk_id from joined_table where [filter])
``` 
or 
```
where exists (select 1 from joined_table where joined_table.fk_id = table.id and [filter])
```

Is it perhaps possible to change the SQL generation of these filters to use subqueries instead of joins? I think it's only relevant for  o2m relations btw.

**Comment by rijkvanzanten** [comment]
> does not work with mssql because there are columns with the 'text' type (the json columns) and those are not allowed to be in a distinct select

☹️ boooo

> Is it perhaps possible to change the SQL generation of these filters to generate subqueries instead of joins?

Yes we could! 

> I think it's only relevant for o2m relations btw.

That's correct. We only use joins right now in the relational where clauses anyways, it's not used to _fetch_ relational data, as those are batched.

We'd have to rewrite this function to rely on subqueries instead of joins:

https://github.com/directus/directus/blob/7c1d0ba325ebbe9ae4c7d0bd0f175af4b9f3cad5/api/src/utils/apply-query.ts#L39

**Comment by martijnboland** [comment]
I might have a go at this one, but I'm a little reluctant to break anything important. Are there perhaps any (integration) tests I could run to verify if things still work as they should?

**Comment by rijkvanzanten** [comment]
> I might have a go at this one, but I'm a little reluctant to break anything important. Are there perhaps any (integration) tests I could run to verify if things still work as they should? At a quick glance, I couldn't find any.

Unfortunately not yet.. Feel free to open a PR though, I'll manually review and test on various dbs too
