### ISSUE TITLE
Set CORS_CREDENTIALS to true by default

### ISSUE THREAD

**Issue by altezza04** [directus/directus#4080]
Upgrading from RC.34 to RC.37 Auth no longer work in default setting, need to set CORS_CREDENTIALS to TRUE in .env (as oppose to the documentation which the value is suppose to be TRUE by default)

Error
The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

**Comment by workatease** [comment]
Yes I see that the default values are are not set for some of the keys but I see CORS_ENABLED is set 
https://docs.directus.io/reference/environment-variables/#cors
https://github.com/directus/directus/blob/main/api/src/env.ts
