### ISSUE TITLE
SDK-js Auth logout does not clear the storage

### ISSUE THREAD

**Issue by workatease** [directus/directus#4082]
1) The issue and what you expected to happen
I am seeing that directus SDK-js does not clear the values in storage when we use 
`directus.auth.logout()`

below three values has to be remove
directus_access_token
directus_access_token_expires
directus_refresh_token

2) steps to reproduce this issue

const directus = new DirectusSDK("http://localhost:8055/", {
  auth: { storage: localForage, mode: "json", autoRefresh: true },
});
directus.auth.logout()

check in the storage location we can still see the values
![image](https://user-images.githubusercontent.com/57198612/108018800-bb45b100-6fe6-11eb-8f6e-9e45ce58fe2a.png)

3) Your environment:
Directus: v9.0.0-rc.37
Browser: Chrome Version 88.0.4324.15 
SDK version:9.0.0-rc.37

**Comment by rijkvanzanten** [comment]
Closed in favor of https://github.com/directus/directus/issues/4097

**Comment by workatease** [comment]
I think we need to reopen this issue as we are still facing issue when we don't clear the storage when we logout.

**Comment by rijkvanzanten** [comment]
Yeah you're right, the other issue turned out to be a configuration issue 👍🏻

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/directus/pull/4163
