### ISSUE TITLE
Logout error in sdk-js

### ISSUE THREAD

**Issue by NickSettler** [directus/directus#4097]
1) Cannot logout
    `auth.logout()` method should logout me from account and delete `directus_access_token` and `directus_access_token_expires` from LocalStorage. But instead of it it always creates HTTP error with code 400.
    Also response returns json body 
    ```
    {"errors":[{"message":"\"refresh_token\" is required in either the JSON payload or Cookie","extensions 
    {"code":"INVALID_PAYLOAD"}}]}
    ```
    I tried to changed `AuthOptions` storage and mode params in the `DirectusSDK` constructor, but nothing has changed.

2) Exact steps to reproduce this issue
    1) Creat empty Vue project
    2) Install `@directus/sdk-js`
    3) Create object of DirectusSDK class in the main.js file
    4) Add login method and provide credentials
    5) Add logout method in `then` callback function

    After these steps error happens

3) Environment:
    Directus version: `directus/directus:v9.0.0-rc.24`
    DBMS: `postgres:12`
    Cache: `redis:6`
    Deployment: Docker via `docker-compose.yml` file
    Browsers:
    - Chrome 88.0.4324.150
    - Chrome Mobile 88.0.4324.152

**Comment by NickSettler** [comment]
Not sure, but maybe the reason was in env variables in docker-compose file in my deployment. Added two lines
```
REFRESH_TOKEN_COOKIE_SAME_SITE: 'none'
REFRESH_TOKEN_COOKIE_SECURE: 'true'
```
This helped to change `SameSite` in the `Set-Cookie` header to None and add Secure attribute, so setting cookie locally started working normally.

**Comment by rijkvanzanten** [comment]
Good point! Very plausible that the browser stripped out the cookie because of those values. Browsers are getting more and more finicky in how they're handling cookies (for good reason)

**Comment by NickSettler** [comment]
Looks like this.
Firstly, in the network tab near `Set-Cookie` header was exclamation mark. It said, that cookie cannot be set, because of `SameSite=Lax`, but api domain and my app domain mismatch. After changing to `SameSite=None`, it said that Secure attribute must be set to use `SameSite=None`.
Surely, it's not very complicated, but it took me two hours determinating and solving the problem

**Comment by rijkvanzanten** [comment]
> but api domain and my app domain mismatch

Ah yes, that'll do it.. I'll close this issue as it's not something we can inherently fix, as it's a browser restriction.

I should definitely add a note in the docs somewhere 🤔 Any thoughts on where you'd expect to see this @NickSettler ?

**Comment by NickSettler** [comment]
Maybe it would be suitable in the page **Environment Variables**, in the **Security** section after the table. The two environment variables, controlling `Set-Cookie` header referenced exactly there.

**Comment by rijkvanzanten** [comment]
Agreed. We're also integrating Algolia's DocSearch soon, which should make the discoverability a little better

**Comment by workatease** [comment]
I see only more issue on the logout. even after calling directus.auth.logout() and there is no directsus_session . i am able to list the authencated user via /users/me
