### ISSUE TITLE
Need to fetch all collections when retrieving collections for collections and data model views rather than using the default API limit of 100

### ISSUE THREAD

**Issue by jpetryk** [directus/directus#4109]
@jpetryk That's a different issue caused by a very similar reason: The default limit for the API is 100, so the app has to explicitly state to fetch all items. The fact that it only the first 100 items could be considered a good thing for the inline preview of the o2m (as it would otherwise potentially blow up the browser if it tries fetching 10k+), but for the amount of collections, it should definitely fetch all

_Originally posted by @rijkvanzanten in https://github.com/directus/directus/issues/3743#issuecomment-780169306_

**Comment by rijkvanzanten** [comment]
@jpetryk I'm also very curious to learn more about your specific use case here. I'm not too used to seeing Directus instances with 100+ collections 😄 Do you mind hitting me up on Discord? 👉🏻 https://directus.chat
