### ISSUE TITLE
Gatsby plugin v9rc.40 - Unexpected Token '.'

### ISSUE THREAD

**Issue by strategore** [directus/directus#4115]
When I execute `gatsby develop`, the plugin produces the following error : 

```
Error: /Users/nikosgpet/WebstormProjects/strategore/node_modules/@directus/gatsby-source-directus/gatsby-node.js:66
const hasEmail = auth?.email && auth?.email?.length > 0;
                      ^
SyntaxError: Unexpected token '.'
```

I am using version "9.0.0-rc.40" of the plugin.

**Comment by strategore** [comment]
Nevermind, I think it was because of using a previous Node version.

**Comment by olehkhalin** [comment]
I have the same issue when I'm trying to deploy the website on Netlify
