### ISSUE TITLE
 permissions.flat is not a function

### ISSUE THREAD

**Issue by blumarling** [directus/directus#4118]
Hello!
I have a  **permissions.flat is not a function** error when trying to access front end app and I am a custom role user.
The error happen on this call  **/server/info?limit=-1** and I get a 500

To reproduce just create any new role and permission even with standard settings and assign it to a new user. Then enter the frontend app (/admin) as this new user.

my env:
- Directus 9.0.0-rc.38
- node v10.23.0

**Comment by rijkvanzanten** [comment]
Node v10 coming in strong once again 😄

Btw, be aware that Node 10 is EOL in April of this year 🙂

**Comment by blumarling** [comment]
You're right @rijkvanzanten. Is the node version.
**I just tested in the v12.19.0 and it works.**
If you want you can close this.

**Comment by rijkvanzanten** [comment]
We officially support the currently supported versions of Node, so I consider this a bug. Come April 2021, we'll stop supporting Node 10 as well, and I can use `.flat()` to my heart's content 😉
