### ISSUE TITLE
Saving item options not working in different language

### ISSUE THREAD

**Issue by NickSettler** [directus/directus#4123]
1) Cannot use keyboard shortcut for "Save and Stay" or "Save and Create New"
    The shortscuts `Ctrl+S` and `Ctrl+Shift+S` doesn't save item in collection, when using keyboard language different from English or other where position of `KeyS` differs.

2) Exact steps to reproduce this issue
    1) Install app and login
    2) Create empty collection with at least one field
    3) Open create item page to create item in the collection
    4) Change keyboard language to another, where KeyS doesn't matches its position on the keyboard or not exists at all
    5) Try using shortcut for "Save and Stay" (`Ctrl+S`) or "Save and Create New" (`Ctrl+Shift+S`)

3) Environment:
    Directus version: `directus/directus:v9.0.0-rc.24`
    DBMS: `postgres:12`
    Cache: `redis:6`
    Deployment: Docker via `docker-compose.yml` file
    Browsers:
    - Chrome 88.0.4324.150
    - Chrome Mobile 88.0.4324.152

**Comment by Nitwel** [comment]
Could you tell what language you are using?

**Comment by NickSettler** [comment]
> Could you tell us what language you are using?

Russian

**Comment by NickSettler** [comment]
Have an idea how to fix this issue. `key` property can be changed to `code` in `keydown` listener in the [use-shortcut.ts](https://github.com/directus/directus/blob/main/app/src/composables/use-shortcut/use-shortcut.ts) file. `key` property in the KeyboardEvent is language-dependent, but `code` property is language-independent.
`key` and `code` properties have different format. So when `key` property is "s", the `code` property is "KeyS". But after changing keyboard language, `key` will be different, and `code` will be the same as for english language so for other languages.
But this solution requires all shortcut strings used in code to be changed.

**Comment by Nitwel** [comment]
First I thougt it would make sense to make this language independend but we can't do that. If we wanted to have the `ctrl + z` shortcut somewhere, it would not work with German keyboards for example because for German keyboards `z` and `y` are swapped.

**Comment by rijkvanzanten** [comment]
@Nitwel I can't imagine `code` in that case would be `KeyZ` for the `y` letter... right?

**Comment by Nitwel** [comment]
![grafik](https://user-images.githubusercontent.com/22577866/108234666-505ebc00-7145-11eb-89f7-3f85e1a5a0b1.png)

**Comment by rijkvanzanten** [comment]
Yeah that's not ideal either. I have no idea how this is normally handled in non-latin keyboards! 

@NickSettler What's the key-combo for "save" in most apps on your end?

**Comment by NickSettler** [comment]
It's same like in latin keyboards - `Ctrl+S`. Latin letters are displayed on russian keyboard buttons and they have same positions like on the most common latin keyboards (QWERTY).
In all apps, when I press `Ctrl+S`, save command triggers even if I'm using russian language.

**Comment by rijkvanzanten** [comment]
Oh interesting, but the `key` value for that letter is in russian/cyrillic, or.. ?

**Comment by NickSettler** [comment]
`key` value is in russian if using russian keyboard and in english if using english keyboard.
`code` value is in english no matter what keyboard is used.

**Comment by rijkvanzanten** [comment]
Learn something new everyday 🌈 ✨ 

@Nitwel seems like `code` is the way to go here (https://hacks.mozilla.org/2017/03/internationalize-your-keyboard-controls/)

**Comment by Nitwel** [comment]
I added a fallback to `code` when the true char is not from the latin language which should solve this, please tell us if this still didn't fix it!
