### ISSUE TITLE
"Invalid undefined scheme" with empty permissions object

### ISSUE THREAD

**Issue by Fma965** [directus/directus#4135]
1) The issue and what you expected to happen

sending POST to /items/logs just results in the below error, works fine on rc34 and below
```
{
  "errors": [
    {
      "message": "Invalid undefined schema",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

```
2) Exact steps to reproduce this issue
    POST request to create a item, the collection is a simple text and date created field

3) Your environment:
    What version of Directus you are using. v9-rc40
    Which DBMS are you using (MySQL 8, Postgres 12, ...): MYSQL
    Which deployment are you using (npx, Docker, ...): Docker
    What browser are you using: Insomnia REST Client

![image](https://user-images.githubusercontent.com/1707290/108260311-1946d580-715a-11eb-9fa8-dd6618936941.png)

**Comment by Fma965** [comment]
I'm not really sure what information you want but happy to provide what is needed, if i roll back to RC34 it works fine

**Comment by rijkvanzanten** [comment]
I don't think that error is thrown by Directus itself 🤔 

Can you check on the API side if there was anything useful logged? (It logs to STDOUT, so it should be visible in terminal/console/wherever you run it)

**Comment by Fma965** [comment]
Registries
Settings
 A new version is available
Portainer 2.0.0
Container logs admin
Containers > syn3updater > Logs my account  log out
 Log viewer settings
Auto-refresh logs  
Wrap lines 
Display timestamps 
Fetch
All logs
Search
Filter...
Lines
100
Actions   
      
20:22:35 ✨ Initializing bootstrap...


20:22:36 ✨ Database already initialized, skipping install


20:22:36 ✨ Running migrations...


20:22:36 ✨ Done


20:22:37 ✨ Server started at port 8055


20:22:55 🚨 Invalid undefined schema 


Error: Invalid undefined schema


    at new module.exports (/directus/node_modules/@hapi/hoek/lib/error.js:23:19)


    at module.exports (/directus/node_modules/@hapi/hoek/lib/assert.js:20:11)


    at Object.internals.schema (/directus/node_modules/joi/lib/compile.js:33:5)


    at Object.exports.schema (/directus/node_modules/joi/lib/compile.js:17:26)


    at internals.Base.$_compile (/directus/node_modules/joi/lib/base.js:645:24)


    at /directus/node_modules/joi/lib/types/keys.js:260:92


    at Object.exports.tryWithPath (/directus/node_modules/joi/lib/common.js:176:16)


    at internals.Base.method [as keys] (/directus/node_modules/joi/lib/types/keys.js:260:32)


    at Object.args (/directus/node_modules/joi/lib/types/keys.js:49:23)


    at Object.internals.generate (/directus/node_modules/joi/lib/index.js:259:31)


20:22:55 ✨ request errored POST 500 /items/logs 38ms

**Comment by rijkvanzanten** [comment]
Do you have any create permissions configured for the `logs` collection?

**Comment by Fma965** [comment]
Not sure what you mean, i can create from this bearer token without issue on RC34 and below but anything above does not work, when i roll back to RC34 it works fine again.

**Comment by rijkvanzanten** [comment]
There's something going wrong in constructing the validation schema for creation for this particular user, so I'm looking for a way to reproduce that exact setup on my end so I can confirm what's causing this 🙂 

Would you be able to share a DB dump where this is happening?

**Comment by Fma965** [comment]
Sure, do you have some means of sending this as I'd prefer to not share it publically.

**Comment by Fma965** [comment]
I've emailed the email in your profile with subject "Invalid undefined scheme with simple post request #4135" hopefully this reaches you.

**Comment by Fma965** [comment]
So i seem to have fixed it by doing 
![image](https://user-images.githubusercontent.com/1707290/108355572-e85eb300-71e2-11eb-9fc2-d888ffd0dfcf.png)
Reset to recommended on the custom role

Here is before / after
![image](https://user-images.githubusercontent.com/1707290/108355604-f3194800-71e2-11eb-8af6-745578a59a2e.png)
![image](https://user-images.githubusercontent.com/1707290/108355609-f44a7500-71e2-11eb-8b91-d333a2f56a04.png)

**Comment by rijkvanzanten** [comment]
(@benhaynes we should update the `--highlight` color in dark mode 👨🏻‍🎨 )

**Comment by rijkvanzanten** [comment]
> I've emailed the email in your profile with subject "Invalid undefined scheme with simple post request #4135" hopefully this reaches you.

**Comment by benhaynes** [comment]
> (@benhaynes we should update the `--highlight` color in dark mode 👨🏻‍🎨 )

Pushed a fix for this!

**Comment by Fma965** [comment]
Thanks guy's I'll leave it with you, I didn't find any other reports of this on the internet and i researched for hours, for me it's working after resetting permissions so i'll let you guys investigate from here :)

If you need anything else let me know.

**Comment by rijkvanzanten** [comment]
I believe this was fixed in https://github.com/directus/directus/commit/4144cecef58448c1b05c1e1a1683841f8aab4f9c#diff-3df48479a0e1c0941bbcfd1d6d915e08734993902548c65815bec31971cd5a51
