### ISSUE TITLE
RC40 SDK, Token Expired error

### ISSUE THREAD

**Issue by altezza04** [directus/directus#4145]
After upgrade to RC40, the SDK will give "token expired" error after logged in for a while, and try to call /auth/refresh or /auth/login again. It seem the token inside localforage cannot be updated.

````
const api = new DirectusSDK(URL, {
  auth: {
    storage: localforage,
    mode: 'json',
    autoRefresh: true
  }
})
```

{message: "Token expired.", extensions: {code: "INVALID_CREDENTIALS"}}
extensions: {code: "INVALID_CREDENTIALS"}

**Comment by rijkvanzanten** [comment]
Probably related to https://github.com/directus/directus/issues/4082, not sure if duplicate

**Comment by workatease** [comment]
@altezza04 Please check with RC42 it has a fix for clearing the values after logout

**Comment by altezza04** [comment]
> @altezza04 Please check with RC42 it has a fix for clearing the values after logout

Thanks, it's fixed. Good job 👍

**Comment by altezza04** [comment]
It seem when the Token expired, then I call the auth.logout() function, the api won't allow my program to logout (give Token Expired error again)

I was wondering how does the autoRefresh work? Should it be even the Token had expired, then when making a next api call, it will auto refresh the token?

**Comment by workatease** [comment]
I think the error would be when the refresh is called and receives the 401 error it does not clear the token stored in the SDK.
as the token is already expired so the user should already logged out.
but as the token is not cleared and it still exists it shows as valid.

we need to handle catch for 401 status here
https://github.com/directus/directus/blob/01ecf994d448856dd8c900221218a59ea474ef8c/packages/sdk-js/src/handlers/auth.ts#L110

**Comment by altezza04** [comment]
> I think the error would be when the refresh is called and receives the 401 error it does not clear the token stored in the SDK.
> as the token is already expired so the user should already logged out.
> but as the token is not cleared and it still exists it shows as valid.
> 
> we need to handle catch for 401 status here
> https://github.com/directus/directus/blob/01ecf994d448856dd8c900221218a59ea474ef8c/packages/sdk-js/src/handlers/auth.ts#L110
> 
> @rijkvanzanten @WoLfulus what are your suggestions

Thanks, that should be the problem

**Comment by dataexcess** [comment]
Is this fixed? I still get the error.. 

a4618ee.js:2          GET https://subneu.live/api/users/me 403 (Forbidden)
bc75317.js:1 Error: Token expired.
    at be.<anonymous> (a4618ee.js:2:349121)
    at Generator.throw (<anonymous>)
    at h (a4618ee.js:2:323277)

To be honest I don't understand why this error is showing even at all. Shouldn't an expired access_token be refreshed by the refresh_token? I thought this should be handled by the SDK behind the scenes. Can you explain me why I am seeing this error and how can I fix it. 

Thnx

**Comment by benhaynes** [comment]
What version of Directus are you on? Other details of your setup?

**Comment by dataexcess** [comment]
client: "@directus/sdk": "^9.5.1",
server: "directus": "^9.6.0"

initialising the SDK without any config object.

**Comment by rijkvanzanten** [comment]
Can you open a new issue? This one is over a year old, and about a version that's very different 👍🏻
