### ISSUE TITLE
Updating one translation triggers On Update of all translations for the same item

### ISSUE THREAD

**Issue by Mrmiffo** [directus/directus#4147]
**The issue and what you expected to happen**
When saving a change of a translation from within an item, all translations of that item gets updated (date_updated).
**Expected**: Only the modified translation gets updated.
**Issue**: If item permissions have been set on the translations, such as a user is only allowed to edit a specific language, the change will throw a FORBIDDEN error when the user tries to edit the translation as he/she does not have permission to edit the other languages. See #3351

**Exact steps to reproduce this issue**
1. Create a collection called "product"
2. Add a translations field. (default settings)
3. Add a standard field "title" to the translation collection.
4. Add a TimeStamp field "date_updated", set On Update: Save Current Date/Time
5. Create a product and some translations. Save.
6. Enter the product and modify the title of one of the translations. Save
7. The "date_updated" is now set to the exact same timestamp for all translations of that product, but only one of them have an actual change.

**Your environment:**
    MySQL 8
    npx rc40
    Chrome

**Any other relevant information we might need to reproduce this issue**
[Dump20210218.zip](https://github.com/directus/directus/files/6001832/Dump20210218.zip)

**Comment by Nitwel** [comment]
This seems to be a bug within the api updating dates for items that haven't changed.
Sending `[{"languages_code":"de-DE","id":1,"text":"heyaa1aa"},2,3]` to the api, not only updates item with id of 1 but also 2 and 3.

**Comment by Mrmiffo** [comment]
I tried creating a collection without the "date_updated"/"user_updated" fields, and added item_permissions for only updating german translations. But I still get the FORBIDDEN error for it trying to update other languages... So even without these fields, it still tries to update other languages. Having these fields just make it obvious.

**Comment by Mrmiffo** [comment]
Created a simple webhook to see if I can filter the changes as a workaround. Just to see what happens I made the following:
```
module.exports = function registerHook({ services }) {
	const { ItemsService } = services;

	return {
		'items.update': async function (input) {
            console.log(input);
        }
    };
}
```
And the resulting printouts are a bit surprising...

First off is the actual update I made of the Swedish translation (adding an 'a' to the title):
```
{
  event: 'items.update',
  accountability: {... },
  collection: 'product_translations',
  item: 7717,
  action: 'update',
  payload: {
    language: 'sv',
    id: 7717,
    title: 'Srixon Soft Feela',
    product: '17'
  },
 ...
}
```
Then comes an update for the English and German  translation:
```
{
  event: 'items.update',
  accountability: { ... },
  collection: 'product_translations',
  item: 7735,
  action: 'update',
  payload: { id: 7735, product: '17' },
 ...
 },
{
  event: 'items.update',
  accountability: { ... },
  collection: 'product_translations',
  item: 7743,
  action: 'update',
  payload: { id: 7743, product: '17' },
...
}
```
And then an update of an unknown item:
```
{
  event: 'items.update',
  accountability: { ... },
  collection: 'product_translations',
  item: [],
  action: 'update',
  payload: { product: null },
...
}
```
Followed by the final update of the actual product, which contains the IDs of the English and German translations for some reason:
```
{
  event: 'items.update',
  accountability: { ... },
  collection: 'products',
  item: '17',
  action: 'update',
  payload: { translations: [ [Object], 7735, 7743 ] },
...
}
```

This doesn't make any sense as I have 5 different languages:
![image](https://user-images.githubusercontent.com/8545443/108353190-24484700-71e8-11eb-8c1c-917b60f456a4.png)

I'm not sure what to do with all this, but hope this info can help :P
