### ISSUE TITLE
Cannot read property 'timestamp' of null

### ISSUE THREAD

**Issue by doodlemania2** [directus/directus#4160]
On RC.40 + MySQL
When opening to view an item in a collection, following Stacktrace from a custom role:

```json
{
  "stack": "TypeError: Cannot read property 'timestamp' of null\n    at https://myurl/admin/js/app.45a3fda8.js:1:969076\n    at yn (https://myurl/admin/js/chunk-vendors.8c1f1fb6.js:121:6865)\n    at https://myurl/admin/js/chunk-vendors.8c1f1fb6.js:121:28236\n    at p (https://myurl/admin/js/app.45a3fda8.js:1:969022)",
  "message": "Cannot read property 'timestamp' of null"
}
```

Role is set to "Recommended Defaults" + "View Revisions"
Role is then granted CRU (not delete) on the collection.
Role is also granted CRU (not delete) on all related collections (several M2M) - Junction collections included.

Admin users don't experience this. Can't find where that timestamp error is coming from.

**Comment by rijkvanzanten** [comment]
I believe it's trying to read the timestamp from directus_activity in the sidebar detail for revisions

**Comment by doodlemania2** [comment]
Good thought. I gave the role these permissions with same error:
![image](https://user-images.githubusercontent.com/5252217/108446681-1f08ed80-7224-11eb-825b-a36da1e4e5ca.png)
(This is different than default perms on that).

**Comment by doodlemania2** [comment]
As an update, I gave this role Read access to all collections (both system and created) - same issue:

**Comment by doodlemania2** [comment]
Another update - I made this role a reader of ALL collections and a full admin of all System Collections. Same Issue :(

![image](https://user-images.githubusercontent.com/5252217/108755853-6259a980-750d-11eb-886a-a9bd8010caaf.png)

**Comment by rijkvanzanten** [comment]
Follow-up question, did you ever truncate `directus_activity` or `directus_revisions`, but not the other?

**Comment by rijkvanzanten** [comment]
Could be that it's trying to relationally read the activity timestamp that goes with the revision, but the activity for that revision doesn't exist / can't be found 🤔

**Comment by doodlemania2** [comment]
Never truncated either, but can if you think it'll clear the issue?

**Comment by rijkvanzanten** [comment]
Worth a shot! Before you do though, can you make a backup of those tables so we don't accidentally lose the cause of this issue? 🙂 

If possible, could you share a dump where this is happening? That is the easiest way for me to reproduce and fix 👍🏻

**Comment by doodlemania2** [comment]
That did it! I cleared `directus_revisions` then attempted to truncate `directus_activity` and it threw a constraint error, so I cleared that table manually. Once both were cleared, boom - up and running!

I bet I busted it when I did a data load directly to that table - is that a no no?

**Comment by rijkvanzanten** [comment]
Ahh did that data load include the primary keys, or where those generated? Sounds to me like there was a revision that had a foreign key to a non-existing activity record

**Comment by doodlemania2** [comment]
Whoopsie - yep, they did contain keys - I just dumped and reloaded the offending table and let it generate. All looks MUCH happier now. Thank you so much!

**Comment by doodlemania2** [comment]
This has cropped back up - I wonder if there is a genuine bug in how M2M related collections get updated. No bulk DB operations have happened, just working with the interface or REST. Any way to troubleshoot it? I can send you a dump if you like, but would need to sanitize first, so let me know.

Most recent error is the same as the original.

**Comment by doodlemania2** [comment]
BTW - I can "clear" the error by truncating `revisions` without truncating `activities` - perhaps that is a tell? The M2M relationships aren't getting recorded correctly or something?

**Comment by rijkvanzanten** [comment]
> I can send you a dump if you like, but would need to sanitize first, so let me know.

This would be most useful to me!

**Comment by doodlemania2** [comment]
Can I ping you on Discord with a link to scrubbed data?

**Comment by rijkvanzanten** [comment]
Yeah totally 👍🏻

**Comment by doodlemania2** [comment]
<3
