### ISSUE TITLE
Change translations from drawer to tabs presentation

### ISSUE THREAD

**Issue by YannickMol** [directus/directus#4169]
Would it be an idea to change the presentation for translations from drawer to a tabs presentation? Here a quick sketch on what it might look like:
![image](https://user-images.githubusercontent.com/13256289/108495901-a6e50b00-72a9-11eb-84a3-c748f45b6f45.png)

**Comment by Nitwel** [comment]
It's an cool idea but there are some major drawbacks.
- the title must be very short to fit many translations in there
- there is a limit on how many translations we can display here before wrapping to a new line
- you can't see whats in the translation until you click on it
- we are looking into adding a progress bar to translations that wouldn't fit in the tabs.

But having this as a community made custom interface would be really nice! 😉

**Comment by YannickMol** [comment]
> the title must be very short to fit many translations in there
I assume that mostly the language name is used, which would still fit approx 7 on the screen. 

> there is a limit on how many translations we can display here before wrapping to a new line
We could make it a dropdown if there are more than the width of the first line?

> you can't see whats in the translation until you click on it
Actually, I believe this is the case at the moment. In the proposed solution, you would see the content of your main language when opening the page, which is more than what you see at the moment.

> we are looking into adding a progress bar to translations that wouldn't fit in the tabs.
Curious to see what that looks like! 😄

**Comment by Nitwel** [comment]
> I assume that mostly the language name is used, which would still fit approx 7 on the screen. Also, I don't think there will be many use cases where the number of languages is more than 7.

Having nl_NL isn't very practical, most people would probably like to have a full country name here which are wider than a few characters. Also there will be someone who needs more than 7. 😄 

> We could make it a dropdown if there are more than the width of the first line?

That could work.

> Actually, I believe this is the case at the moment. In the proposed solution, you would see the content of your main language when opening the page, which is more than what you see at the moment.

Yes, but hopefully not for long, our goal is to maybe have a render-template option here to give insight in the translation.

> Curious to see what that looks like! 😄

Ben added a mockup of how this could look like in the issue below.
https://github.com/directus/directus/issues/2919

**Comment by YannickMol** [comment]
That mockup looks great! 🥇 If that's implemented then there wouldn't be room for the tabs layout, so I'll close this issue 😉

**Comment by rijkvanzanten** [comment]
> Also, I don't think there will be many use cases where the number of languages is more than 7.

You'd be surprised!

**Comment by rijkvanzanten** [comment]
Also, in regards to tabs w/ inline fields:

@benhaynes and I have gone back and forth countless times on nested relational fields on the detail page. The main problem we face is nesting and recursiveness. We'd have to have a way to visually distinguish what fields are the "nested group" compared to the regular fields on the parent level (eg what's to say that WYSIWYG is a translated field instead of just a regular field on the parent?). The "obvious" solution is to indent it in some sort of box:

```
id
note
translations
  title
  wysiwyg
another-field
```

but then the question becomes: how to handle nested fields _within_ a nested translation? What if you'd have a repeater that opens items inline as well? Would you get

```
id
note
translations
  title
  wysiwyg
  one-to-many
    - title
      another-related-value
      and-another
    - title
      another-related-value
      and-another
another-field
```

In terms of UI, this gets cluttered / confusing _really_ fast (also you'd run into serious space constraints after like 2 levels). Food for thought!

**Comment by benhaynes** [comment]
Exactly what @rijkvanzanten said. There are a _lot_ of benefits to keeping translations on the parent page (easier access, more room, side-by-side translations, etc), but the UX just gets so cluttered and messy when you allow for nested fields. There's just no good way to nest fields more than one level deep, and it's inconsistent to allow nested fields only one level deep (this breaks most relational interfaces).

Totally down to discuss this further... especially if anyone has some ideas around nested field UX!
