### ISSUE TITLE
Permission issue when patching a collection item

### ISSUE THREAD

**Issue by nickThomasson** [directus/directus#4179]
Today directus startet to throw an error regarding missing permissions when patching an collection item.

**So this is the situation:**

I have a collection named 'categories' and a collection named 'products'. Within categories a have an many-to-many relation field named 'products' which links the collection items from products to a collection item in categories. The junction collection is called 'categories_products'.
 
I'm making an API call via JavaScript/Axios: PATCH: <url>/items/categories/id

**This is my request body:**

`{
  "products": [
    98,
    {
      "products_id": {
        "status": "published",
        "name": "Product name",
        "user_group": "e205c57c-1541-468d-9ddf-9e0d16e369ce"
      }
    }
  ]
}
`

**Here is the response:**

_**403 Forbidden**_

`{
	"errors": [
		{
			"message": "You don't have permission to access this.",
			"extensions": {
				"item": 98,
				"collection": "categories_products",
				"code": "FORBIDDEN"
			}
		}
	]
}`

This error only appears the second time I'm creating a new item. The first time, if there isn't any other item, it works just fine. And till recently there was no problem at all. I checked all the permissions and even as administrator I get this message. When I'm reproducing the same procedure in the directus user interface, I don't get this error. First I thought it was a problem with the code in my branch, but others devs had the same problem and it appeared for everyone around the same time.

**Env:**

- Directus 9.0.0-rc.28
- Ubuntu 20.04
- Node v12.20.1
- PostgreSQL 12.6
- Firefox latest & Chrome latest
- Vue 2.x
- Running with NPX / CLI Install

I'm a bit puzzeld by this and I hope you can help me.

**Comment by rijkvanzanten** [comment]
> When I'm reproducing the same procedure in the directus user interface, I don't get this error.

This is weird! The app itself uses the API the same way you would, so there must be a difference there.

Would you be able to share a DB dump where this is happening? How are you authenticating into the API?

When you send `{ "errors": [ { "message": "You don't have permission to access this.", "extensions": { "item": 98, "collection": "categories_products", "code": "FORBIDDEN" } } ] }`, does item `98` exist in `categories_products`?

**Comment by nickThomasson** [comment]
Hi, if I clear it with my team, I may provide you with a db dump. I may even provide you with a preview link of our app. As for the authentication method, I'm using the bearer token. I guess the directus ui is using cookies?

**Comment by rijkvanzanten** [comment]
> I guess the directus ui is using cookies?

The app is using the same auth flow as described on https://docs.directus.io/reference/api/rest/authentication/ and https://docs.directus.io/reference/api/authentication/. There's no "special" internal API stuff for the admin app.

---

I'd recommend inspecting the network request that the app makes when it works, and comparing that to what you're doing in the API. It might be as simple as a slightly wrongs structure, or a wrong primary key or something along those lines 🙂

**Comment by rijkvanzanten** [comment]
I'll close this for now, as it sounds like a usage problem (seeing the request works as expected in the app itself)

**Comment by WayneEld** [comment]
I was getting this error using a static token for serverless functions to communicate with the Directus API. I was logged in as the Admin user and using a static token, associated with the Admin user, to make API calls patching certain collections with custom information. (Still all in development and running locally hence the not-so-great token association). When I patched/updated a collection via the API, using the static token, and moved around the app interface as the Admin user it obviously disassociated the access JWT and static token. Therefore even as the admin user, I was "Forbidden" to see the collection because the token got mixed up. @nickThomasson I hope this helps your issue.

**Comment by staminna** [comment]
I have recreated an M2M relationship between two collections with default options, as Administrator, disabled 2FA, and still getting the same error, precisely as described by the OP @nickThomasson. @WayneEld Can you explain how to address the JWT issue and the "and moved around the app interface" I don't see how it should be done. I can see the Axios error on the console.

use-sync-7318fa3d.js:29          GET http://localhost:8055/items/Article/21 403 (Forbidden)

<img width="1703" alt="Captura de ecrã 2023-01-16, às 21 51 47" src="https://user-images.githubusercontent.com/515180/212770926-e8e561d5-627e-47ee-a5d1-903643dd2b80.png">

I am seeing this and using Docker and the latest version of Directus, as of today.

**Comment by samlof** [comment]
I'm seeing the same problem with static bearer token. Getting Forbidden as admin user with static bearer token when it works through UI with jwt tokens.
