### ISSUE TITLE
Revisions Drop Down disappear if # of revisions over 1000

### ISSUE THREAD

**Issue by tedcao** [directus/directus#4187]
The revisions drop down is disappear if we have over 100 revisions.

Environment:
    Version of Directus: v9.0.0-rc.41
    DataBase: Mysql 8.0.20

It would be great if we can have a Env variable to limit the max number of revisions for each collection and drop the oldest revisions.

**Comment by rijkvanzanten** [comment]
> It would be great if we can have a Env variable to limit the max number of revisions for each collection and drop the oldest revisions. 

This sounds like [a new feature request](https://github.com/directus/directus/discussions/new) to me 🙂
