### ISSUE TITLE
Prioritize environment variables over config file stored vars

### ISSUE THREAD

**Issue by isawk** [directus/directus#4191]
After upgrade to latest version, it appears my existing environment variables such as DB_HOSTare overridden by those in .env previous version was not behaving that way. No I have to commit out definitions in .env so my environment variables take precedence. 

---

### Project details
Directus Version: 9.0.0-rc.42
Environment: production
OS: Linux 4.4.0
Node: 12.20.1

**Comment by isawk** [comment]
This issue appears to have resurfaced, upgraded Directus from version v9.8.0 and all env configurations are superseded by .env. this is cause applications on GAE (Google App Engine) not to work since all env_variables are ignored/superseded by .env

**Comment by rijkvanzanten** [comment]
@isawk Wouldn't you be able to omit the `.env` file in favor of using GAEs way of injecting env?

**Comment by piotr-cz** [comment]
Some kind of workaround is to omit variables from `.env` file, as the later takes precedence
https://github.com/directus/directus/blob/6e4738e4c0b75ee6030600867f1e6eb6058f34ac/api/src/env.ts#L269-L273
