### ISSUE TITLE
rc42 - M2M relationship does not allow any more to configure the interface/display of the relationship

### ISSUE THREAD

**Issue by magomimmo** [directus/directus#4193]
To reproduce:
- create a recipe collection with a name field
- create ad ingredient collection with a name field
- create an M2M recipe/ingredient relationship
- the relationship configuration of interface/display does not work anymore

See attached screen recording

https://user-images.githubusercontent.com/1448905/108592067-4e2a7680-736c-11eb-968d-e1a4f18eb2d9.mp4
---

### Project details
Directus Version: 9.0.0-rc.42
Environment: production
OS: Linux 5.4.0-65-generic
Node: 14.15.5

**Comment by Nitwel** [comment]
Seems to be the same issue as in #3935
