### ISSUE TITLE
Related values are not shown for M2A

### ISSUE THREAD

**Issue by YannickMol** [directus/directus#4195]
After #4168, the related values are not shown for M2A.

![image](https://user-images.githubusercontent.com/13256289/108601462-0243f580-739d-11eb-8698-bde8131761f8.png)

**Comment by magomimmo** [comment]
Hi @YannickMol , it seems to me that in rc.44 the related values are not shown for M2A: To reproduce:

1. Define a `son` collection with only a `name` field
2. Define `daughter` collection with only a `name` field
3. Define a `parent` collection with a `name` field and a `children` M2A field with `son` and `daughter`  as related collection. 

First thing I do not understand is the need to reach a forth level to configure `Item` as the `Display Template` of the `Related Values` associated with the `Display` configuration for the relation. 
 
![m2a](https://user-images.githubusercontent.com/1448905/109383895-d6b79280-78e9-11eb-944a-891aa2457598.png)

That said, even if I can see the number of children (sons or daughters) associated with a parent, I still can't see their names.

![parent](https://user-images.githubusercontent.com/1448905/109383986-47f74580-78ea-11eb-9b45-ca2c0c3807f7.png)

![children](https://user-images.githubusercontent.com/1448905/109383994-5d6c6f80-78ea-11eb-8df0-e2d99355759d.png)

![detail](https://user-images.githubusercontent.com/1448905/109384058-aae8dc80-78ea-11eb-9c61-5459c6d9a2e1.png)
