### ISSUE TITLE
refresh_token cookie cannot be set for sameSite: "none"

### ISSUE THREAD

**Issue by emregency** [directus/directus#4205]
1) The issue and what you expected to happen
When the environment variables are set to the following: in docker-compose:

```
REFRESH_TOKEN_COOKIE_SECURE: "true"
REFRESH_TOKEN_COOKIE_SAME_SITE:  "none"
```

the `app` (on https) receives a cookie with the sameSite: "none" option BUT without the secure flag. In this config, Chrome prevents the cookie to be set.

2) Exact steps to reproduce this issue
    On localhost, it is hard to reproduce, but when I log `typeof env.REFRESH_TOKEN_COOKIE_SECURE` it returns a boolean where the `auth` controller expects a string (?) 
     On production, Directus is deployed to Azure through App Services, with valid certificates from azurewebsites.net and still no secure flag.

```
		if (mode === 'cookie') {
			res.cookie('directus_refresh_token', refreshToken, {
				httpOnly: true,
				maxAge: ms(env.REFRESH_TOKEN_TTL as string),
				secure: env.REFRESH_TOKEN_COOKIE_SECURE === 'true' ? true : false,
				sameSite: (env.REFRESH_TOKEN_COOKIE_SAME_SITE as 'lax' | 'strict' | 'none') || 'strict',
			});
```

3) Your environment:

version: directus-v9.0.0-rc.42
deployment method: docker-compose, Azure App Services
browser: Chrome 88.0.4324.182

**Comment by rijkvanzanten** [comment]
Good catch!
