### ISSUE TITLE
Rotate JPG image on upload

### ISSUE THREAD

**Issue by ptsans** [directus/directus#4206]
### Some JPG images with EXIF info are not automatically rotated after uploading. 
Directus version: 9.0.0-rc.42

Before upload:
![Screenshot_20210222_005409](https://user-images.githubusercontent.com/18110232/108632184-89ca5b00-74a8-11eb-8337-1509a0d27283.png)

After upload:
![Screenshot_20210222_005518](https://user-images.githubusercontent.com/18110232/108632212-b7170900-74a8-11eb-8bb2-a087b95a1bc3.png)

A possible solution is to add the [rotate](https://sharp.pixelplumbing.com/api-operation#rotate) method to the sharp pipeline:
```js
// api/src/services/files.ts#L54

...
const pipeline = sharp();
pipeline
     .rotate()
     .metadata()
     .then((meta) => {...}
```

After upload with the solution attached:
![Screenshot_20210222_010451](https://user-images.githubusercontent.com/18110232/108632518-5983bc00-74aa-11eb-858d-767bb1264c30.png)

**Comment by workatease** [comment]
I agree we need to add it to the assets services too.
https://github.com/directus/directus/blob/055ebcb69b54038ddb0c2acb6d2ff536a17772c2/api/src/services/assets.ts#L63

Let's discuss and see if we can do it. Please check if this can be done. @rijkvanzanten 
Happy to submit a PR if we can do it

**Comment by workatease** [comment]
> I agree we need to add it to the assets services too.
> https://github.com/directus/directus/blob/055ebcb69b54038ddb0c2acb6d2ff536a17772c2/api/src/services/assets.ts#L63
> 
> Let's discuss and see if we can do it. Please check if this can be done. @rijkvanzanten 
> Happy to submit a PR if we can do it

As I see the thumbnail generated are also missing the rotation

**Comment by rijkvanzanten** [comment]
@workatease Sounds good to me! Lets add that `.rotate` flag on upload 👍🏻 

It shouldn't matter for the generation of the thumbnail, as the source file should be in the right orientation at that point

**Comment by ptsans** [comment]
Are there any cases where you may need to not rotate the image according to EXIF orientation on uploading?

Otherwise, it is worth doing this optionally with a toggle in the project settings.

**Comment by workatease** [comment]
> Are there any cases where you may need to not rotate the image according to EXIF orientation on uploading?
> 
> Otherwise, it is worth doing this optionally with a toggle in the project settings.


Users usually like to see their files upright and the same way it is in their local.
if you think its valid case we can explore in adding that option.

**Comment by rijkvanzanten** [comment]
I can't think of any right now. I can't remember having ever seen such a setting in other photo-management-tools like Google Photos or iCloud etc 🤔 

For now, lets go with the good-default of rotating on upload, and we can discuss if the need ever arises.

I don't think adding an additional toggle for this would be really [80/20](https://docs.directus.io/contributing/introduction/#feature-requests) at this point

**Comment by ptsans** [comment]
I'm asking because the use of rotate implies the removal of the EXIF Orientation tag, if any.

And in a project like Strapi this is made exactly optional.

The only limitation I see now is that on each upload would have to check this flag from the db.
