### ISSUE TITLE
PATCH users/:id gives 500 server error

### ISSUE THREAD

**Issue by andriusign** [directus/directus#4207]
Server error 500

Patch /users/{myUserId}?fields?fields=*,role.name,authors.*

`{"errors":[{"message":"update \"directus_users\" set \"first_name\" = $1, \"last_name\" = $2, \"location\" = $3, \"title\" = $4, \"description\" = $5, \"tags\" = $6, \"language\" = $7, \"username\" = $8 where \"id\" in ($9) - invalid input syntax for type json","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}`

Permissions for users:
```
{
    "id": {
        "_eq": "$CURRENT_USER"
    }
}
```
---

### Project details
Directus Version: 9.0.0-rc.42
Environment: production
OS: Linux 4.15.0-29-generic
Node: 14.15.5

**Comment by andriusign** [comment]
Noticed that this was happening when I was trying to pass "tags" property for the user. I am passing string, but it is failing.

**Comment by rijkvanzanten** [comment]
`tags` is an array of strings, not a single string 👍🏻
