### ISSUE TITLE
Still creates column on error

### ISSUE THREAD

**Issue by Baser-T** [directus/directus#4211]
---
When I tried to create a many to one relationship I got prompted with the error: invalid_payload. However when I checked the table the column was still created which in turn prompts an error since the column was created and the column you are trying to create already exists.

### Project details
Directus Version: 9.0.0-rc.36
Environment: production
OS: macOS Catalina (10.15)
Node: 14.15.4

**Comment by Nitwel** [comment]
What are the exact steps to reproduce this?

**Comment by Baser-T** [comment]
create two tables, one with just a standard string, and for the other create a new field with a many to one relationship. Point to the other table's column and fill out the first page. On the second "relationship tab click the create field under corresponding field and select ID. Under interface select many to one and select ID. Under display select related values and select the string field. It'll then prompt an invalid_payload error but it will still create the column.
