### ISSUE TITLE
Forbidden prompt on user read

### ISSUE THREAD

**Issue by Baser-T** [directus/directus#4212]
Forbidden access to other users still allows details to be viewed.
---

I've created a basic user role, due to the directus setup permission they still have access to directus users. However when I click on the admin user it prompts an Forbidden access notice. When I click on dismiss I am still on the user page. I can't edit any values but it does allow me to see the user's email, first name, lastname etc.

Can easily be reproduced by login in with a user in the dashboard that isn't admin and navigating to an admin account or perhaps even any account for that matter.

### Project details
Directus Version: 9.0.0-rc.36
Environment: production
OS: macOS Catalina (10.15)
Node: 14.15.4

**Comment by rijkvanzanten** [comment]
Could you share the exact permissions you have configured for this role?

I think the 

> it prompts an Forbidden access notice

is the app trying to read the related file under `avatar`, not the user itself

**Comment by Baser-T** [comment]
These are the permissions the role has on the directus side of things, I haven't touched them at all since the role's creation.
![image](https://user-images.githubusercontent.com/71784948/108733118-7bbf1d80-752e-11eb-9ab2-306277b63202.png)

**Comment by YannickMol** [comment]
Apparently this behaviour is intended, you can set the access permissions to minimum at the bottom of the Permissions section. 

![image](https://user-images.githubusercontent.com/13256289/108763928-3d3b5a00-7552-11eb-9766-f05863c78073.png)

@rijkvanzanten, should it be this way or should the standard be that the default user only has access to his own profile?

**Comment by rijkvanzanten** [comment]
> should the standard be that the default user only has access to his own profile?

That _is_ the app access minimum 🤔 When using the "Recommended Defaults", the user has read access to all directus_files and directus_users

**Comment by rijkvanzanten** [comment]
That Forbidden error is thrown as the app is trying to read the Role, but the recommended defaults don't include role read access 👍🏻

**Comment by rijkvanzanten** [comment]
@Baser-T if you reset your app recommended permissions for this role (in rc.43+), the forbidden error will be gone 👍🏻

**Comment by Baser-T** [comment]
@rijkvanzanten it's more that I don't want the user to be able to see other people's personal information. Is there any way to avoid that?

**Comment by rijkvanzanten** [comment]
@Baser-T Yeah, like @YannickMol pointed out above, you don't have to use the "recommended" permissions. By default, the app-minimum permissions only allow the user to view their own profile
