### ISSUE TITLE
Error first time load

### ISSUE THREAD

**Issue by 7aklhz** [directus/directus#4214]
1) The issue
After being idle for a while, when I load a website with Directus content, the content does not load. In the console, I see  500 error. However, when I reload the website a second time, the content from Directus is loaded.

This is the precise error message I get

{"errors":[{"message":"select `ip_access` from `directus_roles` where `id` is null limit 1 - read ECONNRESET","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}

It's like Directus goes to "sleep" every xxx minutes, and I need to wake it up to get its content.

3) Your environment:
Directus : v9.0.0-rc.28
Mysql 8
Directus deployment : Docker
Browser : Brave

Any ideas where the issue comes from ? 

Thank you in advance.

**Comment by rijkvanzanten** [comment]
`ECONNRESET` in Node means that the "other end" of the connection abruptly closed the connection. I'm afraid this is an issue in your particular environment (between server - database), and not something we can address in Directus directly necessarily..

**Comment by 7aklhz** [comment]
ah, indeed. Thank you for your response @rijkvanzanten 

For those having the same issue, here a start : https://success.mirantis.com/article/ipvs-connection-timeout-issue
For caprover users : https://caprover.com/docs/troubleshooting.html#connection-timeouts

Cheers

**Comment by rijkvanzanten** [comment]
Funny that you mention it, I literally just implemented that yesterday 😄 ✨ 

https://github.com/directus/directus/commit/81bb7cfa53b1fde8a7442cfb6d516af2fa29cf2e

**Comment by 7aklhz** [comment]
Great ! :) I can't see the .43 version yet on docker hub but will implement it ass soon as possible. Thank you !! Cheers

**Comment by rijkvanzanten** [comment]
Correct! I'm working on getting that out of the door today 😁 

https://github.com/directus/directus/milestone/32

**Comment by 7aklhz** [comment]
Hi again. Ok, I have installed v9-rc.43. When I put DB_POOL_MIN=0 I get the following error 
Error: Tarn: opt.min must be an integer >= 0

When I put DB_POOL_MIN=1 it works

Any ideas ?

**Comment by rijkvanzanten** [comment]
Depending on where you run, that `0` might be considered as a "false" ? Try using an explicit `DB_POOL_MIN="number:0"` (https://docs.directus.io/reference/environment-variables/#environment-syntax-prefix)

**Comment by 7aklhz** [comment]
Tried it twice during the last hour and it seems to be working. Thank you @rijkvanzanten . 

Cheers.
