### ISSUE TITLE
Validate incoming data type

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#4221]
Right now, we attempt to save whatever the user provided to the API to the database (after permissions checks obv). However, we can already know ahead of time that certain things won't work, like saving a plain string to a JSON field, or saving a boolean to a float. 

We should validate not only for permissions, but also for used datatype. (so we can return 400s w/ proper error messages instead of 500s)

**Comment by emregency** [comment]
Wouldn't the graphql endpoint handle that natively?

**Comment by rijkvanzanten** [comment]
> Wouldn't the graphql endpoint handle that natively?

Yes, but GraphQL is only a small part of the full Directus suite 😉 (it also has to work in Rest / CLI / web sockets (in the future) )

**Comment by emregency** [comment]
Oh yes indeed. 🙂 Do you plan to use an automation tool that generates runtime checks directly from typescript?

**Comment by rijkvanzanten** [comment]
We use Joi to do object validation 🙂 I already wrote a function that generates the validation schema based on the given filter set, so in order to implement this we'll add `schema` into the mix too 

https://github.com/directus/directus/blob/main/api/src/utils/generate-joi.ts

**Comment by rijkvanzanten** [comment]
We've since started abstracting various database errors for this exact purpose. Things like illegal values, invalid constraints, unique constraint matches etc are returned by the database, and abstracted properly by Directus
