### ISSUE TITLE
UUID fields are transformed into textfields

### ISSUE THREAD

**Issue by web-devil** [directus/directus#4227]
Goal: Adding an additional unique constraint to an existing collection (urlslug) besides auto-increment ID field

Steps to reproduce: 
- edit collection
- add "uuid" field, On Create: Do nothing (=> Intention
- Save
- the field is transformed into textfield

Expected:
UUID field is created, so that user can create (text-)fields with a unique constraint

Alternative approach (preferred):
Add option for adding unique constraint to fields

---

### Project details
Directus Version: 9.0.0-rc.40
Environment: production
OS: Linux 5.4.0-1031-azure
Node: 12.19.0
Database: MySQL: 5.7

**Comment by rijkvanzanten** [comment]
> the field is transformed into textfield

MySQL 5.7 doesn't have a UUID type, so it's expected that CHAR(32) is used in that context 👍🏻 

> Add option for adding unique constraint to fields

This is absolutely the preferred approach (ref #2944)
