### ISSUE TITLE
Translate (expected) error messages (e.g. duplicate entry)

### ISSUE THREAD

**Issue by web-devil** [directus/directus#4229]
If you violate a unique constraint (manually entered ID field), then the plain error message is returned. 

![image](https://user-images.githubusercontent.com/18443024/108766205-24807380-7555-11eb-80eb-fb00d18ad485.png)

Expected: 
Translated error messaged which explains the error for endusers. 

---

### Project details
Directus Version: 9.0.0-rc.40
Environment: production
OS: Linux 5.4.0-1031-azure
Node: 12.19.0

**Comment by rijkvanzanten** [comment]
I'm considering this part of https://github.com/directus/directus/issues/2944
