### ISSUE TITLE
Export only exports 100 lines

### ISSUE THREAD

**Issue by Fma965** [directus/directus#4244]
Is it known that export only exports 100 lines?
rc40

**Comment by rijkvanzanten** [comment]
[100 is the default for `limit`. You can use `limit=-1` to fetch all items](https://docs.directus.io/reference/api/query/#limit)

**Comment by Fma965** [comment]
Think you missed my point, when pressing EXPORT on the Web Interface you only get 100 rows, there is no indication this will be the case and it seems unituitive for the user to have to add ?limit=-1 to the URL before pressing that button to get all rows
![Uploading image.png…]()

**Comment by Fma965** [comment]
@rijkvanzanten

**Comment by rijkvanzanten** [comment]
> Think you missed my point

Well.. you didn't really make that point in your post, so yeah I obviously missed it 😂

**Comment by rijkvanzanten** [comment]
I've created a new feature request for you here: 

https://github.com/directus/directus/discussions/4248

**Comment by Fma965** [comment]
I wasn't aware that there was any other "Export" function other than via the GUI button labelled "EXPORT" but either way thanks.
