### ISSUE TITLE
It is not possible to create a custom interface for relationship or alias types

### ISSUE THREAD

**Issue by adam-axis** [directus/directus#4256]
On v9.0.0-rc.43, you can't create a custom interface for m2o, o2m, m2a, or alias types. Only standard local types work.

Here is the interface index for example, for an m2o interface:
```
import InterfaceComponent from './interface.vue';

export default {
    id: 'eg-m2o',
    name: 'Example many-to-one',
    icon: 'search',
    component: InterfaceComponent,
    types: ['uuid', 'string', 'text', 'integer', 'bigInteger'],
    relationship: 'm2o',
    localTypes: ['m2o'],
    recommendedDisplays: ['related-values'],
};
```

This interface only appears when creating a non-relationship field (eg. standard string). Only the system "Many-To-One" interface appears otherwise.

The same issue is there for any relationship or alias interfaces, you can't create custom ones.

Related: https://github.com/directus/directus/discussions/3985

**Comment by rijkvanzanten** [comment]
Can you try adding the `groups` flag to this index?

This is the system's m2o field:

https://github.com/directus/directus/blob/01e1a8c9587cc6f120afaa97f9a713763e5a3b88/app/src/interfaces/many-to-one/index.ts#L5-L16

**Comment by rijkvanzanten** [comment]
Can confirm that adding `m2o` to `groups` makes it show up under the relational setup 👍🏻 

<img width="1010" alt="CleanShot 2021-02-24 at 09 23 06@2x" src="https://user-images.githubusercontent.com/9141017/109014229-f187ce00-7681-11eb-92e6-52717775d45b.png">

**Comment by benhaynes** [comment]
> Can you try adding the `groups` flag to this index?
> 
> This is the system's m2o field:
> 
> https://github.com/directus/directus/blob/01e1a8c9587cc6f120afaa97f9a713763e5a3b88/app/src/interfaces/many-to-one/index.ts#L5-L16

Should we have something for this in the Docs for creating custom interfaces?

**Comment by rijkvanzanten** [comment]
That's what the referenced commit does @benhaynes 👍🏻

**Comment by benhaynes** [comment]
Hahah, I missed the small print! Thanks for being on top of your game! ❤️
