### ISSUE TITLE
Cards layout is broken

### ISSUE THREAD

**Issue by adam-axis** [directus/directus#4257]
On v9.0.0-rc.43, any page where you select the built-in cards layout doesn't work. 

The server responds with a 500 to a request for /items/{item name}.

This has been the case for at least the last 2 releases.

**Comment by Nitwel** [comment]
If the PR doesn't fix your problem, please reopen this issue so we can investigate further.

**Comment by rijkvanzanten** [comment]
@adam-axis please fill out the issue template next time, it's there for a reason 🙂 Trying to reproduce an issue like this without any information on what version, what environment, what the error _is_, etc is near impossible.
