### ISSUE TITLE
Export button doesn't use project URL

### ISSUE THREAD

**Issue by adam-axis** [directus/directus#4258]
On v9.0.0-rc.43 (and pretty much all previous releases as well), the export button in the collections module sidebar takes the user to `/items`, without respecting the project URL if it is set in project settings. Perhaps it should prepend the project URL.

**Comment by rijkvanzanten** [comment]
> Perhaps it should prepend the project URL.

Why should it? The app is served from the API, so it should be safe to assume that the `/items` endpoint next to `/admin` exists.

**Comment by adam-axis** [comment]
Sorry my mistake this is not related to the project URL. 

When serving the app behind a reverse proxy, the app makes all the API calls correctly to the relative path (eg. (domain)/api/...). However, this export request is the only one being made to the absolute path (always (domain)/...).
