### ISSUE TITLE
Directus does not set Content-Type header for GraphiQL

### ISSUE THREAD

**Issue by simpleauthority** [directus/directus#4264]
1) The issue and what you expected to happen
  When using Directus combined with a reverse proxy, unless the reverse proxy has some sort of intelligent and automatic content type negotiation, GraphiQL simply loads as plain text and cannot be used. I would expect to be able to use Nginx and Directus together and still be able to use GraphiQL. If you access Directus without going through Nginx, GraphiQL loads fine. I think the solution is for Directus to set a Content-Type header on GraphiQL explicitly.

2) Exact steps to reproduce this issue
1. Create a new Directus installation
2. Create a reverse proxy with nginx (you can use this config: https://gist.github.com/simpleauthority/26719864479100e36518ee0be6f576b3)
3. Try to access your installation's graphiql page. It will simply be plaintext html.

3) Your environment:
Directus version: v9.0.0-rc.43
Using MariaDB 10.5.8
Deployed via npx
Testing on Firefox 85.0.2

4) Any other relevant information we might need to reproduce this issue
As this problem is not related to a specific schema, any Directus install should do.

**Comment by MiniDigger** [comment]
Worth noting that this is also an issue with other reverse proxies (caddy for example tries to intelligently find the doc type but can't), it seems the only reason it works without a reverse proxy is that browsers are super intelligent and can detect the html

**Comment by rijkvanzanten** [comment]
I'm wondering if we should move this to [`express-graphql`](https://github.com/graphql/express-graphql) seeing we don't manually set those headers 🤔
