### ISSUE TITLE
Bad visibility half-width fields on mobile

### ISSUE THREAD

**Issue by YannickMol** [directus/directus#4276]
![Screenshot_20210224-230316_Chrome.jpg](https://user-images.githubusercontent.com/13256289/109072010-bffc1a80-76f4-11eb-8776-2dd73f8b9a1b.jpg)

**Comment by benhaynes** [comment]
It must be because these are in "proprietary" Settings pages... I think all half-width fields are already supposed to go to full-width at certain breakpoints.
