### ISSUE TITLE
[M2A] New item has no sort property

### ISSUE THREAD

**Issue by jianliao** [directus/directus#4280]
1) When you create an any item, the sort property would not be automatically generated until you re-order it with d&d. After parent object saved, the null sortProperty would lead to unpredictable content generated for static site.

See the screen record: 
https://user-images.githubusercontent.com/1207520/109110695-73acdc80-76ec-11eb-9478-6b2bf86243e9.mp4

2) v9.0.0rc.43

**Comment by Nitwel** [comment]
What exactly is the bug here? What would be the unexpected behavior?

It is intended that the sort field only gets set after d&d.

**Comment by rijkvanzanten** [comment]
> It is intended that the sort field only gets set after d&d.

From a technical perspective, it makes sense _why_ it does this. That being said, from a user-perspective it's expected that the sort value as rendered in the app is propagated to how it's saved in the DB. We should set the sort value of newly added items to `highest-sort-value + 1` on creation 👍🏻

**Comment by jianliao** [comment]
The site generator will sort the section content array by sortField when generate the static site. If the sortField is null, it will end up random order. To work around this issue now, content editor has to d&d the new created item to trigger the sortField get set. It is very inconvenient and easy to forget, especially when user create multiple new content items.
