### ISSUE TITLE
Assets API: image letterboxing background is always black

### ISSUE THREAD

**Issue by metalmarco** [directus/directus#4292]
When resizing an image using the assets API (https://docs.directus.io/reference/api/assets/#requesting-a-thumbnail), setting fit=contain and a higher width than the original image, the letterbox background is black, which I think ruins the image.
We thing the letterbox background should be transparent, or (preferably) a parameter in the querystring.

Example:

Source image is 278 × 181 pixel
![images](https://user-images.githubusercontent.com/7231582/109194701-fc358680-7799-11eb-8491-7abf22ace3c9.jpeg)

When resizing it to be square:
https://<directus_url>/assets/841bccde-b095-43e6-bad5-88edead11e95?access_token=<token>&fit=contain&height=200&width=200
![image](https://user-images.githubusercontent.com/7231582/109194925-33a43300-779a-11eb-88bb-88e055292eea.jpeg)

**Comment by metalmarco** [comment]
As a possibile solution, the Sharp library as a "options.background" property that can be set to transparent

See: https://sharp.pixelplumbing.com/api-resize

**Comment by rijkvanzanten** [comment]
Do you want it to remain a letterboxed square? You could also use `fit=inside` to don't have letterboxes altogether

**Comment by rijkvanzanten** [comment]
See https://github.com/directus/directus/discussions/4293

**Comment by metalmarco** [comment]
> Do you want it to remain a letterboxed square? You could also use `fit=inside` to don't have letterboxes altogether. I'll open a feature request to make that bg configurable 👍🏻

We do actually need to set the image to a width and height, filling the extra space transparent.
Thanks @rijkvanzanten
