### ISSUE TITLE
GIF asset lost animation after upload to Directus

### ISSUE THREAD

**Issue by jianliao** [directus/directus#4297]
1) D&D this gif to directus, then open the asset. It is a static image now and no more animation. The original file size should be 61KB and Directus show 59KB, but if you download it from directus, it will be only 3KB(first frame). GIF asset works well until very recent. I guess it is a regression.
![rating_behaviors_clear-rating@2x](https://user-images.githubusercontent.com/1207520/109206018-354f0600-775c-11eb-9a0a-a56c2f691ad8.gif)

2) v9.0.0 rc.43

**Comment by jianliao** [comment]
Perhaps relates to #4206

**Comment by jianliao** [comment]
I checked and confirmed that the file saved on my S3 bucket is 3KB.

**Comment by workatease** [comment]
this is because of #3949 when the metadata is calculated it strips off the frames to get height and width information

**Comment by rijkvanzanten** [comment]
@workatease we might want to rely on a passthrough steam to extract the metadata from, and only upload the rotated source to drive 🤔

**Comment by jianliao** [comment]
Yes, it should be enable to extract the meta data and upload the complete file at the same time.

**Comment by workatease** [comment]
> @workatease we might want to rely on a passthrough steam to extract the metadata from, and only upload the rotated source to drive 🤔

do you think if it is a good idea to create a copy(clone) of the stream for this purpose

**Comment by rijkvanzanten** [comment]
@workatease 

Hmm I suppose we could try only fetching the metadata _after_ this promise is done!

https://github.com/directus/directus/blob/main/api/src/services/files.ts#L97

So we'll only call `rotate()` during that first pipeline creation, and then call `metadata()` on it after the promise for uploading the file is done.

If that doesn't work out, then copying the stream sounds like the next best thing to me 👍🏻

**Comment by workatease** [comment]
sure Let me test that code to check . will keep you posted
