### ISSUE TITLE
Image upload crash "TypeError: Cannot read property 'config' of undefined" using docker

### ISSUE THREAD

**Issue by NeoN0x** [directus/directus#4312]
Dear all,

Thank you for this awesome product !

Using Directus direcly works fine, but I'm struggling to use Directus on a docker image in order to release it.

**Version: v9.0.0-rc.43
Environment: production**

I'm able to upload / delete any file type, but when uploading specifically an image (jpeg), I got the following error :

![Sélection_650](https://user-images.githubusercontent.com/1714902/109318151-c94cca80-784d-11eb-88aa-f964baf2d7c2.png)

Which output this : (this is not helpful for me)

```json
{
  "stack": "TypeError: Cannot read property 'config' of undefined\n    at p (http://localhost:9876/admin/js/app.172336ae.js:1:449049)\n    at async s (http://localhost:9876/admin/js/app.172336ae.js:1:936569)\n    at async Promise.all (index 0)\n    at async s (http://localhost:9876/admin/js/app.172336ae.js:1:956361)\n    at async c (http://localhost:9876/admin/js/app.172336ae.js:1:874099)",
  "message": "Cannot read property 'config' of undefined"
}

```

This is my docker file

```
# Use node 14.16.0 alpine as a base image
FROM node:14.16.0-alpine3.13

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

# Install dependencies
RUN npm install --only=production

# Copy source code into
COPY . .

# Entry point
CMD [ "npm", "start" ]
```

Storage config : default (local using ./uploads folder).

I try runnig the image using "-v /somedir:/usr/src/app/uploads" or without it (to store it inside the container), each case reproduce the same error, and I'm unable to have aditionnal information.

I'm also not able to change the Directus environnement which stays into "production", maybe additional debugs will help.

The issue might be related to thumbnails, I do not know how to have additional information on it.

Do you have any idea of what could be the issue, or how I can help further with additional information?

Thanks a lot!

**Comment by rijkvanzanten** [comment]
What are your environment variables for the storage locations? I believe that `.config` is the diskStorage config, could that be missing?

**Comment by rijkvanzanten** [comment]
These:  https://docs.directus.io/reference/environment-variables/#file-storage (obviously redact out your actual keys if you use an external service)

I'm expecting there to be a mismatch in the `STORAGE_LOCATIONS` and the rest of the config

**Comment by NeoN0x** [comment]
Thank you for your reply.

I'm using the default settings

```
####################################################################################################
## File Storage

STORAGE_LOCATIONS="local"
STORAGE_LOCAL_PUBLIC_URL="/uploads"
STORAGE_LOCAL_DRIVER="local"
STORAGE_LOCAL_ROOT="./uploads"
```

I tried absolute path as well, each time, it works using directly directus, and crash the same way using the docker image (only for picture uploads, showing that it is able to read/write files).

Images files copy pasted from original directory are visible, so it do not seems to be a path issue or a read/write issue.

**Comment by rijkvanzanten** [comment]
How are you passing these environment variables to your Docker image?

**Comment by NeoN0x** [comment]
Yes, the .env file is mounted correctly.

Details: 

General config
```
####################################################################################################
## General
PORT=8055
PUBLIC_URL="http://localhost:9876/"
```

Execution
```
docker run -t \
     -v `pwd`/.env:/usr/src/app/.env \
     -v /tmp/storage:/usr/src/app/uploads \ # Testing with (storage on host) and without (storage on container), same behaviour
     -p 9876:8055  \
     --name directustest \
     directustest
```

Accessing localhost:9876. Everything works as expected but the picture uploads.


More logs, one regular pdf file upload, one png file upload

```
(Upload pdf file, from choose file to upload)
15:54:15 ✨ request completed POST 200 /files 104ms
15:54:15 ✨ request completed GET 200 /files?limit=25&fields[]=id&fields[]=modified_on&fields[]=type&fields[]=uploaded_on&fields[]=title&fields[]=type&fields[]=filesize&fields[]=folder&sort=-uploaded_on&page=1&filter=%7B%22_and%22:[%7B%22type%22:%7B%22_nnull%22:true%7D%7D,%7B%22folder%22:%7B%22_null%22:true%7D%7D]%7D 24ms
15:54:15 ✨ request completed GET 200 /files?limit=0&fields=id&meta[]=filter_count&meta[]=total_count&filter=%7B%22_and%22:[%7B%22type%22:%7B%22_nnull%22:true%7D%7D,%7B%22folder%22:%7B%22_null%22:true%7D%7D]%7D 33ms
15:54:16 ✨ request completed PATCH 200 /users/me/track/page 25ms
(works as expected, write file db update, etc)



(pick an image, upload progress...)
15:54:25 ✨ request completed PATCH 200 /users/me/track/page 28ms
(crash without logs, only console logs shown above + write empty file (hash.png) + create database file entry (size: 0)
```

**Comment by rijkvanzanten** [comment]
And all of those requests are made through the app right?

> (crash without logs, only console logs shown above + write empty file (hash.png) + create database file entry (size: 0)

This is very strange! I'd at least expect some error stack trace puke in your stdout 🤔

**Comment by rijkvanzanten** [comment]
@WoLfulus can you reproduce this on Docker

**Comment by NeoN0x** [comment]
(sorry for the post length but I share my analysis)

I digg into it to have a better understanding.

Btw, the stock docker image seems broken. Latest, start issue : 

```
# docker run -p 8055:8055 directus/directus
Unable to find image 'directus/directus:latest' locally
docker: Error response from daemon: manifest for directus/directus:latest not found: manifest unknown: manifest unknown.
```
Tag v9.0.0-rc.44, issue with SQLite

```
docker run -p 8055:8055 directus/directus:v9.0.0-rc.44

# docker run -p 8055:8055 directus/directus:v9.0.0-rc.44
Unable to find image 'directus/directus:v9.0.0-rc.44' locally
v9.0.0-rc.44: Pulling from directus/directus
e95f33c60a64: Pull complete 
26e60022b4e3: Pull complete 
3735863698a8: Pull complete 
d4cc1a999352: Pull complete 
b02f75d2f888: Pull complete 
f2798b3b1fe6: Pull complete 
0d0a23662df3: Pull complete 
343facd38058: Pull complete 
215ab5164a00: Pull complete 
46fc7963d1f5: Pull complete 
12910ad9b54e: Pull complete 
758fee8a1ec1: Pull complete 
Digest: sha256:349063909972f4e6938e4fc87ed6b77aa3d07ab7b242475ca971ce7bb7973bd6
Status: Downloaded newer image for directus/directus:v9.0.0-rc.44
09:18:58 ⚠️  >
09:18:58 ⚠️  >                         WARNING!
09:18:58 ⚠️  >
09:18:58 ⚠️  >  The KEY and SECRET environment variables are not set. Some
09:18:58 ⚠️  >  temporary variables were generated to fill the gap, but in
09:18:58 ⚠️  >        production this is going to cause problems.
09:18:58 ⚠️  >
09:18:58 ⚠️  >                        Reference:
09:18:58 ⚠️  > https://docs.directus.io/reference/environment-variables.html
09:18:58 ⚠️  >
09:18:58 ⚠️  >
09:18:59 ✨ Initializing bootstrap...
09:18:59 ✨ Installing Directus system tables...
09:18:59 ✨ Setting up first admin role...
09:18:59 ✨ Adding first admin user...
09:18:59 ✨ No admin email provided. Defaulting to "admin@example.com"
09:18:59 ✨ No admin password provided. Defaulting to "itEThIAttkjH"
09:18:59 ✨ Running migrations...
Error: Sqlite does not support alter column.
    at TableCompiler_SQLite3.addColumns (/directus/node_modules/knex/lib/dialects/sqlite3/schema/tablecompiler.js:35:11)
    at TableCompiler_SQLite3.TableCompiler.alterColumns (/directus/node_modules/knex/lib/schema/tablecompiler.js:184:10)
    at TableCompiler_SQLite3.TableCompiler.alter (/directus/node_modules/knex/lib/schema/tablecompiler.js:77:8)
    at TableCompiler_SQLite3.TableCompiler.toSQL (/directus/node_modules/knex/lib/schema/tablecompiler.js:34:20)
    at TableBuilder.toSQL (/directus/node_modules/knex/lib/schema/tablebuilder.js:44:42)
    at SchemaCompiler_SQLite3.alterTable (/directus/node_modules/knex/lib/schema/compiler.js:89:25)
    at SchemaCompiler_SQLite3.toSQL (/directus/node_modules/knex/lib/schema/compiler.js:72:26)
    at SchemaBuilder.toSQL (/directus/node_modules/knex/lib/schema/builder.js:79:43)
    at /directus/node_modules/knex/lib/runner.js:31:36
    at /directus/node_modules/knex/lib/runner.js:277:24
```

I can the stock image with my database, and *it worked* fine.

`docker run -p 8055:8055 --name dtest -e DB_CLIENT=mysql -e DB_HOST=192.168.1.89 -e DB_PORT=3306 -e DB_DATABASE=scpisign -e DB_USER=root -e DB_PASSWORD=root directus/directus:v9.0.0-rc.44
`

 So it does not seems to be an issue with docker itself or the implementation.

I saw an image related commit (#4317), perhaps it enhance the image handling somehow.

I upgraded my project with the rc.44, and tried again. **And it worked :smile: **
