### ISSUE TITLE
Problem with access Admin in Subdirectory

### ISSUE THREAD

**Issue by HerrHase** [directus/directus#4313]
I use the brand new 9.*

I have a Problem to use Subdirectories,

\<domain\>/\<subdirectory\>/admin

Nginx Configuration looks like this,

```
location /<subdirectory>/ {
        rewrite ^/<subdirectory>/(.*)$ /$1 break;

        proxy_pass http://127.0.0.1:8055;

        proxy_read_timeout 720s;
        proxy_connect_timeout 720s;
        proxy_send_timeout 720s;

        proxy_http_version 1.1;
        proxy_cache_bypass $http_upgrade;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
}
```
It loads fine until he try to load the assets, in the Html they path remain on /admin/*. I seems there is no way to change the configuration.

Kind regards :)

**Comment by rijkvanzanten** [comment]
When you say 

> It loads fine until he try to load the assets

Do you mean everything works as expected except for the files??

**Comment by HerrHase** [comment]
That's right, i get /<subdirectory>/admin a 200, for all styles, images and scripts i get a 404.

I have already tried without <subdirectory> and it works.

**Comment by rijkvanzanten** [comment]
Did you set the `PUBLIC_URL` environment variable to match your setup? The API will use that to prefix the static files for the app 🙂

**Comment by HerrHase** [comment]
Doh, i have tried this, but not restart the pm2 process :/ Sorry! I leave my desk now in shame... Thanks for your help!

By the way, the new Version is really great! :)

**Comment by rijkvanzanten** [comment]
Glad to hear it works now 🙂 

> By the way, the new Version is really great! :)

Thanks! ❤️

**Comment by Alluuu** [comment]
Hi, in my case only some assets are loaded from the specified subdirectory by PUBLIC_URL env variable.

**Didn't load correctly:**
 - logo-light.1a93a59d.svg
 - - http://192.168.99.100/admin/assets/logo-light.1a93a59d.svg
 - Inter-Bold.f0f54a06.woff2
 - - http://192.168.99.100/admin/assets/Inter-Bold.f0f54a06.woff2
 - Inter-Medium.a4e1e7e6.woff2
 - - http://192.168.99.100/admin/assets/Inter-Medium.a4e1e7e6.woff2
 - Inter-Black.5ab3de07.woff2
 - - http://192.168.99.100/admin/assets/Inter-Black.5ab3de07.woff2
 - Inter-SemiBold.af44b8a2.woff2
 - - http://192.168.99.100/admin/assets/Inter-SemiBold.af44b8a2.woff2
 - material-icons-outline.28c199c2.woff2
 - - http://192.168.99.100/admin/assets/material-icons-outline.28c199c2.woff2
 - Inter-Black.f11705b0.woff
 - - http://192.168.99.100/admin/assets/Inter-Black.f11705b0.woff
 - Inter-SemiBold.3041a990.woff
 - - http://192.168.99.100/admin/assets/Inter-SemiBold.3041a990.woff
 - Inter-Bold.cd06b48a.woff
 - - http://192.168.99.100/admin/assets/Inter-Bold.cd06b48a.woff
 - Inter-Medium.f500bbb9.woff
 - - http://192.168.99.100/admin/assets/Inter-Medium.f500bbb9.woff

**loaded correctly:**
 - login
 - - http://192.168.99.100/subdirectory/admin/login
 - vendor.d2724e38.js
 - - http://192.168.99.100/subdirectory/admin/assets/vendor.d2724e38.js
 - index.ff2ee405.js
 - - http://192.168.99.100/subdirectory/admin/assets/index.ff2ee405.js
 - vendor.90828bcd.css
 - - http://192.168.99.100/subdirectory/admin/assets/vendor.90828bcd.css
 - index.9d26c130.css
 - - http://192.168.99.100/subdirectory/admin/assets/index.9d26c130.css
 - interfaces/
 - - http://192.168.99.100/subdirectory/extensions/interfaces/
 - displays/
 - - http://192.168.99.100/subdirectory/extensions/displays/
 - layouts/
 - - http://192.168.99.100/subdirectory/extensions/layouts/
 - modules/
 - - http://192.168.99.100/subdirectory/extensions/modules/
 - refresh
 - - http://192.168.99.100/subdirectory/auth/refresh
 - extn-utils.html
 - - chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/data/js/extn-utils.html
 - extn-utils.js
 - - chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/data/js/extn-utils.js
 - android-chrome-192x192.png
 - - http://192.168.99.100/subdirectory/admin/img/icons/android-chrome-192x192.png
 - info?limit=1
 - - http://192.168.99.100/subdirectory/server/info?limit=-1
 - oauth/
 - - http://192.168.99.100/subdirectory/auth/oauth/
 - safari-pinned-tab.svg
 - - http://192.168.99.100/subdirectory/admin/img/icons/safari-pinned-tab.svg
 - app_icon-light_bg-color-locked-24.svg
 - - chrome-extension://aeblfdkhhhdcdjpifhhbdiojplfjncoa/inline/images/icons/app_icon-light_bg-color-locked-24.svg
 
 So, essentially fonts and one logo.
 But where it get's more messy is when attempting a login where
  - http://192.168.99.100/admin/assets/index.41d00480.js
  - http://192.168.99.100/admin/assets/index.baa03203.css
  - http://192.168.99.100/admin/assets/vendor.d2724e38.js
  - http://192.168.99.100/admin/assets/vendor.90828bcd.css
  are loaded incorrectly and never received.
