### ISSUE TITLE
Error when selecting Card LayoutOption for collection that contains Many-To-Any field.

### ISSUE THREAD

**Issue by Naxos84** [directus/directus#4316]
Hi. I revisited directus since you now have the feature to add Many-To-Any relation fields.
I want to achieve a page --> component structure.

**1)** When changing the LayoutOptions of a collection that contains a Many-to-Any field I expect the layout to be changed while it shows the following error: 

```json
{
  "errors": [
    {
      "message": "select `page`.`id`, `page`.`status` from `page` where not `page`.`status` = 'archived' group by `page`.`id` order by `page`.`components` asc limit 25 - ER_BAD_FIELD_ERROR: Unknown column 'page.components' in 'order clause'",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

**2)** Create the collections `page`, `headercomponents`, `linkcomponent` and add at least 1 field of type Many-To-Any to the "page" collection.. name the field components.

(I also added the fields "slug" and System field "status")

Related collections: `headercomponents`, `linkcomponent`.

Leave everything else as is.
Create an item for the page and add "components".
Change the LayoutOptions to "Card".

**3) My environment:**

Directus: 9.0.0-rc.43 
DBMS: MariaDB
Which deployment are you using: npx
Browser: Chrome Version 88.0.4324.190 (Official Build) (64-bit)

**4) Any other relevant information we might need to reproduce this issue**

When changing from Table Layout only "ID, slug, status" are selected.
    
When I inspect the database: I see that there is no "components" column in the "page" collection. there is only a "page_components" collection.
    
If you need any other information: please let me know.

**Comment by rijkvanzanten** [comment]
The Card layout defaults to the first non-hidden field for `sort`, but you can't sort by a non-existing field (like a m2a/o2m/m2m) which causes it to fail

**Comment by Naxos84** [comment]
I do understand that I can't sort by a non-existing field. But even though `components` is not a field but instead handled via another connection it is shown as if it is a field. (Could be confusing).

Anyway: I have the following fields in my collection:
![image](https://user-images.githubusercontent.com/17813025/109418471-d215db80-79c8-11eb-9416-2426fbc6ac95.png)

So there are definitely other fields that directus should pickup when attempting to sort.
Is ther any other place I should check?
