### ISSUE TITLE
Wrong width and height on upload

### ISSUE THREAD

**Issue by ptsans** [directus/directus#4323]
### Images whose `meta.orientation >= 5` have the wrong width and height.

![exif-orientation-values](https://user-images.githubusercontent.com/18110232/109417785-02c53780-7a00-11eb-9cfc-c514345efd3e.png)

Directus version: 9.0.0-rc.44

Meta from source:

![Screenshot_20210228_204942](https://user-images.githubusercontent.com/18110232/109419081-913cb780-7a06-11eb-8d3e-23a0ba3dcf49.png)

Response from files api:

![Screenshot_20210228_205401](https://user-images.githubusercontent.com/18110232/109419179-28a20a80-7a07-11eb-83b9-c7e46f704403.png)

A possible solution is to add something like this to the file service:

```javascript
if (meta.orientation && meta.orientation >= 5) {
   [payload.width, payload.height] = [payload.height, payload.width]
}
```

Relate to #4206

**Comment by rijkvanzanten** [comment]
@ptsans Could you share the image you're testing this with? I tried finding some exif-included test files, but they all seem to function as expected on my end 🤔

**Comment by ptsans** [comment]
@rijkvanzanten [This is an image from example.](https://drive.google.com/file/d/1ead6huA7iTyMX7x6DU8QLg6HKOabYmNM/view)

The random image was shot on iPhone XR.

**Comment by rijkvanzanten** [comment]
Thanks! Lovely job on the popcorn wall paint
