### ISSUE TITLE
m2a entries can not be sorted when using MariaDB

### ISSUE THREAD

**Issue by Naxos84** [directus/directus#4324]
1) I want to sort M2a fields on a collection. Like Page --> Components.
I already asked for help in the discord.
This feature works when using PostgreSQL but not with MariaDB.

2) Create 3 collections:
 - heading
 - link
 - page

 Add fields:
  - heading --> name (string)
  - link --> url (string)
  - page --> title (string)

Add a Many-To-Any relation field. Name it "components".
Relationship:
  - Related Collections: "heading", "link"
  - Sort Field "sort"
Display:
  - Item
  
Create a page entry.
give it a title.
Create heading component and give it a name.
Create link component and give it a url.

Save everything.
Open that page again.

I expect that the component entries are sortable.

They are not sortable when using MariaDB.
They are sortable when using PostgreSQL.

3) Your environment:
    9.0.0-rc.44
    DBMS MariaDB
    Deployment npx
    Browser Version 88.0.4324.190 (Official Build) (64-bit)

4) sql dumps for mariadb and postgre

[sqldumps.zip](https://github.com/directus/directus/files/6057886/sqldumps.zip)

**Comment by rijkvanzanten** [comment]
Are both instances using the same settings / installed fresh? In case your MariaDB already existed, did you run `directus database migrate:latest` when updating to rc.44?

**Comment by Naxos84** [comment]
Hi Rijk,

To be honest: I had a MariaDB database already setup. I only deleted all custom created tables. I did not run `directus database migrate:latest` after updating to rc.44.

Let me check the following:
 - Try rc44 with an empty MariaDB database.

 - Setup an rc.43 version with an empty MariaDB.
 - Add everything
 - Update directus and run migration
 
 I'll let you know when I'm done and wether the issue is resolved or not.

**Comment by Naxos84** [comment]
Alright.
Under rc44 with a clean Database it is working! 👍 

But creating with rc43 then updating/migrating seems not to work.
I'm not 100% sure wether I did everything correct when trying to setup an older version.
The field was not sortable in rc43.
After updating/migrating the old field was not sortable.
When I create a new field, the new field is sortable though.
maybe I'm just missing something.

Anyway: this issue could be closed cause setting it up with the latest version and an empty db it worked for me.

**Comment by rijkvanzanten** [comment]
@Naxos84 The way the `sort` configuration for relational interfaces is handled changed between rc43 and rc44 🙂 

The newly included db migration will search through all relational interfaces, and re-configure the sort field: https://github.com/directus/directus/blob/main/api/src/database/migrations/20210225A-add-relations-sort-field.ts

Sounds to me like there was a configuration mismatch in the previous rc43 install 🤔
