### ISSUE TITLE
Users with role can't see other users

### ISSUE THREAD

**Issue by xesjkeee** [directus/directus#4330]
### The issue and what you expected to happen

The user with new role does not see other users when opening «User Directory» page while it should happened

### Exact steps to reproduce this issue

1. Login via admin
1. Create new role with **all enabled permissions**
1. Create new user (user#1)
1. Create another one user (user#2)
1. Add user (user#1) to the created role
1. Add user (user#2) to the created role
1. Login via user (user#1) in new browser
1. Go to the «User Directory» page
1. Expected to see other user (user#2) in list, but here is only me (user#1)

<img width="1106" alt="Снимок экрана 2021-03-01 в 12 16 27" src="https://user-images.githubusercontent.com/17751886/109476410-f5539000-7a87-11eb-9ece-9e77524aaa06.png">

_Please, turn your attention to the count text («1-3 of 3 items»), but in list only one_

### My environment:

directus@9.0.0-rc.42
Postgres 12
npx
Chrome 88

**Comment by rijkvanzanten** [comment]
> Create new role with all enabled permissions

Just to confirm, is this including all permissions for the system collections?

**Comment by xesjkeee** [comment]
> Just to confirm, is this including all permissions for the system collections?

Yes

<img width="815" alt="Снимок экрана 2021-03-01 в 17 45 13" src="https://user-images.githubusercontent.com/17751886/109513181-e2f04b00-7ab5-11eb-8312-912294fca041.png">

**Comment by xesjkeee** [comment]
So I started new project with clear database and this problem was fixed, I applied «App Access Minimum» permissions to my new role and users now can see other users. Probably my database was broken xd ¯\_(ツ)_/¯ 

anyway @rijkvanzanten thanks for paying attention

**Comment by rijkvanzanten** [comment]
Ah!.. Ok! That's both a good and a bad thing. Anyways, lemme know in case you run into the same problem again so we can re-investigate 🙂
