### ISSUE TITLE
O2M interface doesn't show edits on second click

### ISSUE THREAD

**Issue by ghost** [directus/directus#4331]
When editing a related item using the O2M interface, the edits are registered but are cleared when opening the drawer for the second time, so to the user it looks like their edits were gone.

To reproduce this issue:
1. Create a O2M field and add the default interface.
2. Visit the collections module page to render an item's form that includes the O2M interface
3. Add a new O2M item using "Create new" button in the O2M interface
4. After saving, open the item again and try editing the O2M item previously created
5. Click the top right check box in the drawer to save some edits
6. Click the O2M item again and your edits will appear to be gone in the drawer

Details:
Directus Version: 9.0.0-rc.44
Database: Postgresql 9.6
Node: 14.15.4
OS: Windows 10

**Comment by doodlemania2** [comment]
+1 - i think what's happening here is that when you Add a new item in the 'related' entity from the 'primary' entity, the changes aren't saved before returning to the 'primary' entity.

**Comment by doodlemania2** [comment]
Any thoughts on this one? It's funny cause M-M works but O2M doesn't (junction tables!)

**Comment by rijkvanzanten** [comment]
The m2m is a different interface with different logic than the o2m, so it's not impossible for them to be different. 

>  i think what's happening here is that when you Add a new item in the 'related' entity from the 'primary' entity, the changes aren't saved before returning to the 'primary' entity.

This sounds very likely to me! I think it stages the changes correctly for saving to the API, but on second click it fails to re-use those previously made edits as the starting point for the drawer

**Comment by rijkvanzanten** [comment]
This lookup is most likely the culprit:

https://github.com/directus/directus/blob/7bd5dc5c9f2d5f778f15aab1b14393c594b03f52/app/src/interfaces/one-to-many/one-to-many.vue#L360-L362

**Comment by doodlemania2** [comment]
Could very well be - one other odd behavior - sometimes (but not always), it DOES save, but it saves the wrong item as the related entity. It's consistently the SAME wrong item, regardless of what I select. Just wanted to throw that in there to muck things up even more :)

**Comment by rijkvanzanten** [comment]
I added an additional syntax for updating nested relational items in the API 2 weeks ago: https://github.com/directus/directus/pull/4295

It's time to re-work the o2m/m2m interfaces to use that instead 😄 (Together with https://github.com/directus/directus/issues/3889)

**Comment by doodlemania2** [comment]
Excited to try it out! It's got us blocked at the moment but we're able to work around it with direct SQL inserts.
