### ISSUE TITLE
auth.login.before hook does not include clear text password

### ISSUE THREAD

**Issue by sensedrive** [directus/directus#4333]
1) Short description:
The payload of auth.login.before hook does not include clear text password.

2) Exact steps to reproduce this issue
Create a auth.login.before hook in the extensions folder.

Long story (our use case):

We want to switch from firebase to directus. We need to verify user data from firebase authentication export, which is JSON with the fields _email_ and _password hash_. We need the clear text password of a directus login attempt in order to hash it and compare it with the firebase auth export. If this succeeds, we want to save the argon2 hashed password in the directus database. This should happen silently in the background. The first user login attempt should work.

Is it a security vulnerability to include the clear text password?

Thank you in advance!

**Comment by rijkvanzanten** [comment]
> Is it a security vulnerability to include the clear text password?

That's what I was gonna ask you @sensedrive! 

I'm not sure.. It feels like something we shouldn't make available, as it's super sensitive data. I'm mostly thinking about third-party extensions that can inject to any hook, I wouldn't want a third party extension to start farming raw passwords 🤔
