### ISSUE TITLE
Fields=*.* not works on M2M with UUID

### ISSUE THREAD

**Issue by proceau** [directus/directus#4334]
Version RC44
MySQL

1. Create Table1 with ID UUID
1. Create Record Data on Table1
1. Create Table 2 with ID UUID
1. Create record Data on Table2
1. Create Link M2M on Table1 to Table2 ( with create Link record on Table2 )
1. Add data on Table1
1. Add data on Table2 et link to record 1 on Table1
1. Allow Security Public for Table1 and Table2 and Joint Table

`wget -qO - 'https://localhost/items/table1?fields[]=*.*' | jq`

```json
{
  "data": [
    {
      "id": "deb70be6-104a-4456-8ff3-858395a51b1a",
      "status": "draft",
      "data": "titi"
    }
  ]
}
```

record link on listed ( with ID autoincrement it's listed )

**Comment by rijkvanzanten** [comment]
> Allow Security Public for Table1 and Table2

Do you have read access to the junction table between Table1 and Table2 too?

**Comment by proceau** [comment]
yes ( i'm add on issue )

**Comment by rijkvanzanten** [comment]
Is that nested `data` field the one that is the m2m relationship?

**Comment by proceau** [comment]
non data it's random "row data"
normaly the reply it's

{
  "data": [
    {
      "id": "deb70be6-104a-4456-8ff3-858395a51b1a",
      "status": "draft",
      "data": "titi"
      "link": [ "23b70be6-124a-1256-12f3-858395a51bef" ]
    }
  ]
}

**Comment by rijkvanzanten** [comment]
Can you share a DB dump where this is happening? It's a little tricky to reproduce exactly without it :)

**Comment by proceau** [comment]
When recreate from none, it's works :/
i'm search and problem it's upgrade of database ( the test it's initiate with all directus version )
