### ISSUE TITLE
Error on file deletion

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#4342]
When trying to delete files, I always get the attached error.
After that the file is not listed in the File-Manager anymore, but still on the local directory.

Exact steps to reproduce this issue
    Upload a file and then try to delete it

Your environment:
    Directus: 9.0.0-rc.42
    Database: MySQL
    Running on Phusion Passenger / Plesk
    Storage: local

```
{
  "errors": [
    {
      "message": "E_UNKNOWN: An unknown error happened with the file ec3be452-cc8b-4da0-828b-f6782234bbdb.\n\nError code: undefined\nOriginal stack:\nTypeError: fs_1.promises.opendir is not a function\n    at LocalFileSystemStorage._flatDirIterator (/var/www/vhosts/[...]/node_modules/@directus/drive/dist/LocalFileSystemStorage.js:218:45)\n    at _flatDirIterator.next (<anonymous>)\n    at FilesService.<anonymous> (/var/www/vhosts/[...]/node_modules/directus/dist/services/files.js:165:108)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/vhosts/[...]/node_modules/directus/dist/services/files.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:89:5)",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

**Comment by rijkvanzanten** [comment]
@Dominic-Marcelino What version of Node are you running?

**Comment by Dominic-Marcelino** [comment]
Running on Node 12.4.0

**Comment by rijkvanzanten** [comment]
Weird! Node 12.x does supposedly ship with `opendir`, so I'm a little confused why it would throw an undefined on your end 🤔 

https://nodejs.org/docs/latest-v12.x/api/fs.html#fs_fspromises_opendir_path_options

**Comment by Dominic-Marcelino** [comment]
Just noticed right now that it has only been added in: v12.12.0

**Comment by rijkvanzanten** [comment]
No kidding! Good to know, thanks 🙂
