### ISSUE TITLE
Can't revise dropdown change

### ISSUE THREAD

**Issue by Fusseldieb** [directus/directus#4344]
In Directus 9.0.0-rc44 (Using Postgres 13.1) using Chrome 88 when I change a dropdown, the revision change window remains completely blank and I also can't revert the change if I click on the orange "Revert" button.

![image](https://user-images.githubusercontent.com/4715129/109707644-2bbd0800-7b79-11eb-86ca-4158fd7969e7.png)

**Comment by rijkvanzanten** [comment]
> when I change a dropdown

A regular dropdown, or a many-to-one?

Are there any errors in the devtools? I'm kinda surprised that the notice is missing here too 🤔 

<img width="976" alt="CleanShot 2021-03-03 at 20 04 58@2x" src="https://user-images.githubusercontent.com/9141017/109894607-c8f06d00-7c5b-11eb-9333-7648d446d7c0.png">

**Comment by Fusseldieb** [comment]
> > when I change a dropdown
> 
> A regular dropdown, or a many-to-one?
> 
> Are there any errors in the devtools? I'm kinda surprised that the notice is missing here too 🤔
> 
> <img alt="CleanShot 2021-03-03 at 20 04 58@2x" width="976" src="https://user-images.githubusercontent.com/9141017/109894607-c8f06d00-7c5b-11eb-9333-7648d446d7c0.png">

A regular one! What did you do that it appeared there? Do you use another DB?

**Comment by rijkvanzanten** [comment]
Postgres 12.3 and SQLite 3.31.0 both seemed to do work on my end 😱 

What are the interface options for that dropdown? Maybe there's some combination of `value` that makes it go 💥

**Comment by Fusseldieb** [comment]
> Postgres 12.3 and SQLite 3.31.0 both seemed to do work on my end 😱
> 
> What are the interface options for that dropdown? Maybe there's some combination of `value` that makes it go 💥

Hmmm, nothing fancy, really. Just tried it out with a new collection, same thing:

![image](https://user-images.githubusercontent.com/4715129/110007786-ce9c9000-7cf9-11eb-9b47-2b35cce53b9f.png)

![image](https://user-images.githubusercontent.com/4715129/110007809-d52b0780-7cf9-11eb-8d6a-b1134e2cb1ca.png)
