### ISSUE TITLE
Safari Drag and Drop Sorting not working

### ISSUE THREAD

**Issue by abertay-university** [directus/directus#4345]
When using Safari, the drag and drop feature is not working. I've tested in the Data Model editor, Layout Options and the Many to Any interface. There is no movement or console error.

I'm using Safari 14.0.3 on macOS Big Sur 11.2.2 with Directus 9.0 r44

Works as expected in Chrome and Firefox.

See Gif:
![dragndrop](https://user-images.githubusercontent.com/31690037/109733711-93924380-7bb7-11eb-897b-054230963a1e.gif)

**Comment by rijkvanzanten** [comment]
Ref https://github.com/SortableJS/Sortable/issues/1571#issuecomment-566734677
