### ISSUE TITLE
Prevent autocomplete on user and password field in the app

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/directus#4348]
When I try to edit a user as admin, the username and password getting prefilled as I saved it for login to the application. 

So I always have to clear the two fields to be able to save for example the access_token. (E-Mail also can't be just empty, it has to contain the email address, so I have to set the original email)

![image](https://user-images.githubusercontent.com/15796397/109759958-79408000-7c20-11eb-9ef1-c7d1eff944f2.png)

**Comment by benhaynes** [comment]
This seems like your browser password manager trying to auto fill those fields, not Directus. Please disable the browser extension or try in an incognito window... if the issue persists we can reopen.

**Comment by MichaelNussbaumerGOWEST** [comment]
@benhaynes yes I know why it happens, but you should prevent that anyway as I will not be the only one with that problem :)

There is a HTML tag for that case: `autocomplete="off"` and `autocomplete="new-password"` (https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion)
