### ISSUE TITLE
Wysiwyg picture or video modal is hidden

### ISSUE THREAD

**Issue by rperon** [directus/directus#4354]
Hello,

On a wysiwyg content, when you want to add a picture (or video), the modal to select the picture to add appears behind the Insert/Edit Image page.

<img width="754" alt="Screenshot 2021-03-03 at 17 05 29" src="https://user-images.githubusercontent.com/692098/109835018-190f0580-7c43-11eb-86b1-6ac1d0d9c17f.png">

The modal to select the picture should be above the "insert/Edit Image".

The issue is present on directus-rc44. It is similar with this issue : https://github.com/directus/directus/issues/4173

**Comment by damusix** [comment]
Same issue. Made a gif for you guys.
![2021-03-03 12 06 05](https://user-images.githubusercontent.com/4218587/109847655-742e0180-7c1d-11eb-864a-240eeed48115.gif)

**Comment by rijkvanzanten** [comment]
This is being worked on in https://github.com/directus/directus/pull/4309 🙂

**Comment by lahdekorpi** [comment]
Anyone looking for a temporary workaround for this, you could override the z-index of the TinyMCE modal with:

```css
.tox.tox-tinymce-aux {
    z-index: 499 !important;
}
```

This even works if you add this in the custom CSS in project settings.

**Comment by rijkvanzanten** [comment]
@iksent That's why it's a temporary workaround, and not the solution as worked on in #4309 😉
