### ISSUE TITLE
Non-JS files inside of the custom migrations folder crashes directus

### ISSUE THREAD

**Issue by reolat** [directus/directus#4357]
When the custom migrations folder (`directus/extensions/migrations`) contains non-js files (ts typings for example), the command `directus database migrate:up` crashes with the following error:

```
Running migrations... directus/extensions/migrations/20210222A-create-init.d.ts:1
import Knex from 'knex';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
```

I am fairly certain that this behavior is caused by the following [code](https://github.com/directus/directus/blob/679fff1736366f2f589b52df927ec3cb3ab4dde4/api/src/database/migrations/run.ts#L17):

```ts
let migrationFiles = await fse.readdir(__dirname);
const customMigrationsPath = path.resolve(env.EXTENSIONS_PATH, 'migrations');
const customMigrationFiles = ((await fse.pathExists(customMigrationsPath)) && (await fse.readdir(customMigrationsPath))) || [];

migrationFiles = migrationFiles.filter((file: string) => file.startsWith('run') === false && file.endsWith('.d.ts') === false);

const completedMigrations = await database.select<Migration[]>('*').from('directus_migrations').orderBy('version');

const migrations = [
	...migrationFiles.map((path) => parseFilePath(path)),
	...customMigrationFiles.map((path) => parseFilePath(path, true)),
];
```

As you can see, migrationFiles are filtered (does not consider the run file and files which end with `.d.ts`), but customMigrations are not, so every file is considered and later on required() as javascript code.

I would suggest to either filter out all `*.d.ts` files or only allowing `.js` files from the `customMigrationFiles` array.
If you want I can submit a PR for this :)

**Comment by rijkvanzanten** [comment]
> If you want I can submit a PR for this :)

Yes please!
