### ISSUE TITLE
Some interfaces still allow editing even when disabled 

### ISSUE THREAD

**Issue by adam-axis** [directus/directus#4370]
The multiple files interface, even if disabled, allows removing the files by clicking the close button.
A JSON repeater interface with slider interfaces in it still allows moving the sliders.

Details:
Directus Version: 9.0.0-rc.44
Database: Postgresql 9.6
Node: 14.15.4
OS: Windows 10

**Comment by adam-axis** [comment]
Fixed for those two interfaces, thanks. The problem still remains for the M2M interface now.

**Comment by rijkvanzanten** [comment]
Tracked that as https://github.com/directus/directus/issues/4527 🙂
