### ISSUE TITLE
Deleting an user from its detail page results in an error

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/directus#4379]
Where you are located on the detail page of an user and delete it, you get an error message in the console: 

![image](https://user-images.githubusercontent.com/15796397/109952832-e122c380-7d11-11eb-8a6f-a056b31f5797.png)

I tested it on 2 installations (one older without any customizations [rc.24]), both had the same error. Deletion from the overview works fine.

---

### Project details
Directus Version: 9.0.0-rc.44
Environment: production
OS: Linux 4.18.0-147.8.1.el8_1.x86_64
Node: 15.5.1

**Comment by rijkvanzanten** [comment]
Most likely the user preview at the top trying to render the box without the user info existing anymore
