### ISSUE TITLE
Build from repo - issues and steps to solve (WSL2/Ubuntu 20.04)

### ISSUE THREAD

**Issue by asteinarson** [directus/directus#4383]
1) The issue and what you expected to happen
Cloning directus/directus from Github, installing, building and running should work. 
What happens: `npm install` fails and later (after fixing the first) `npm run start` fails.

2) Exact steps to reproduce this issue
Clone the repo directus/directus to local directory: _directus_
Then trying to install it: `$ cd directus && npm install` fails with error messages.

3) Your environment:
    What version of Directus you are using: **9.0.0 - rc.44**
    Which DBMS are you using: **Postgres 12**
    Which deployment are you using: **WSL2, Ubuntu 20.04**
    What browser are you using: **Chrome 88**

4) Any other relevant information we might need to reproduce this issue

**After quite a bit of work, I got it running, through some updates and manual steps. I post my steps below, as a reply**

Maybe this can help someone else with getting Directus to run, building directly from the GitHub repo.

**Comment by asteinarson** [comment]
I'm on Win 10, WSL2, having an install of Ubuntu 20.04. 

Initially **npm install** failed with varying error messages. I was on Ubuntu 20.04 and the installed version of npm was something like 6.19.  (The error messages was along the lines _undefined property exists on undefined_).  

The solution to this was:  `npm install -g npm@latest` (which took me to **npm** version 7.5.6). 
After that, running `npm install` in the _directus_ directory went through. All those errors gone. 
(I don't know which version of npm fixed it - but 7.5.6 certainly did). 

Before that I had downgraded **node** (with nvm) from 15.10 to 12.21 (as it was mentioned in another directus issue). I don't know if that affected anything. 

Then there was building (the main **lerna** sdcript), which failed mysteriously, for me, with all WSL terminals dying. 

It turned out the builds (I think in particular _rollup_) used up all memory on my machine. The solution was to close lots of browser tabs and other windows apps using significant memory. Then, the Lerna build went through. 

However trying `cd api` and `npx directus start` failed with first a stack trace for the _argon2_ module. (There was a path _lib/binding_ within it that node was looking for that had not been built). 

Some research on that made me install **python3** and a package **python-is-python3** (not sure if it was needed). 

Then I went into _node_modules/argon2_ and ran `npm run install`. It built things into the _lib/binding_ directory. (I suppose the top level `npm install` should do that - but then it didn't). 

Trying `cd api` and `npx directus start` another module failed, this time _sharp_. Doing the same here, manually going into that module and running  `npm run install` completed the build and created the required directories. 

Both of the modules that failed to build (from the top level) has a binary build step (**node-gyp** or **node-pre-gyp**). 

After this, `npx directus start` succeeded, and the app came up just fine, with my DB scheme and all. 

BTW, great work on the Directus 9 project guys!

**Comment by rijkvanzanten** [comment]
Thanks for the detailed overview 🙂 

On my end, the steps listed on https://docs.directus.io/contributing/running-locally/ work as expected, but that's most likely because my OS (macOS Big Sur) just happens to play nicely with everything. 

> npm install fails with error messages.

What were the exact error messages? Anything we can adjust to smoothen that out? 

---

Generally speaking, it seems that there's some breaking changes between npm 6 and 7 (especially in the package-lock file handling and workspaces), so I think it's time to make Node 15 / npm 7 a requirement for the local dev setup 🤔

**Comment by asteinarson** [comment]
When running with npm 6.x (exact version lost in closing my terminal), the errors didn't make sense to me. 

On searching, I landed on this page: https://npm.community/t/crash-npm-err-cb-never-called/858/1  (I had that error message). What I understand, a maintainer of **npm** did a fix (post #62) - (_a canary_) - for that issue - around version 6.21 or so. 

Then there was an error where `existsSync` was not found (in some module context). It led me here: https://github.com/ezolenko/rollup-plugin-typescript2/issues/154 

It also went away by the npm update. 

I'm convinced npm >= 7.0 is a requirement, yes.

**Comment by asteinarson** [comment]
When I cloned from GitHub I did not find the docs you pointed to (contributing/running_locally). I think a link to these local build instructions, in topmost **readme.md** would help.  

Maybe trying a few different Ubuntu / CentOS / ... (in some VM/container) can point out exactly what the reqs are (to make it easier for people to get started.
