### ISSUE TITLE
Treat _eq=null as _null

### ISSUE THREAD

**Issue by Slations** [directus/directus#4386]
When trying to filter a request using JavaScript SDK I keep getting errors. I have worked out if I pass the var NULL with _eq it errors and I would use the null operator but this is a variable string and sometimes it's null and sometimes it's a number so I cannot do it this way.

In Postman I just get `{  "data": []  }` but if I remove the null it then works fine. I have included the filters from my SDK the top one fails the bottom one does.

```
filter: {
    status: {_eq: "published"},
    slug: {_eq: path_array[i]}, (path_array[0] = about-us)
    parent: {_eq: parent_id} (parent_id = null)
}
```

But if the request isn't on a root page it works fine:

```
filter: {
    status: {_eq: "published"},
    slug: {_eq: path_array[i]}, (path_array[1] = item-one)
    parent: {_eq: parent_id} (parent_id = 11)
}
```

---

### Project details
Directus Version: 9.0.0-rc.43
Environment: production
OS: Linux 5.4.0-52-generic
Node: 10.19.0

**Comment by rijkvanzanten** [comment]
Have you tried using `_null` instead of `_eq = null`?

**Comment by Slations** [comment]
I have and it works but it's in a for loop so when it loops through the URL as an array so (example.com/about-us/media) would be `["about-us", "media"]` the root item "about-us" had a parent id of null then the "media" has a parent of 4 which is set in the loop, code included below :) 

```
for (i = 0; i <= path_count; i++) {
    json_content = await directus.items('pages').read({
        filter: {
            status: {_eq: "published"},
            slug: {_eq: path_array[i]},
            parent: {_eq: parent_id}
        },
        fields: '*.*'
    });
    parent_id = json_content.data[0].parent;
}
```

**Comment by rijkvanzanten** [comment]
Yeah makes sense, would be easier if `_eq` would just support `null` 👍🏻

**Comment by Slations** [comment]
I have updated both Directus and the JS-SDK to v9.0.0-rc.45 but I am still getting a 500 internal server error with the code above as before but again when changing the parent from null to 0 in the DB then requesting with parent = 0 it works fine 😖 I have included the requests being sent to the server (redacted the domain and Auth Bearer)

`'GET /items/pages/?filter=%7B%22status%22:%7B%22_eq%22:%22published%22%7D,%22slug%22:%7B%22_eq%22:%22about-us%22%7D,%22parent%22:%7B%22_eq%22:null%7D%7D&fields=*.* HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nAuthorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\r\nUser-Agent: axios/0.21.1\r\nHost: cms.domain.org.uk\r\nConnection: close\r\n\r\n',`

```
var parent_id = null;
json_content = await directus.items('pages').read({
            filter: {
               status: {_eq: "published"},
               slug: {_eq: path_array[i]},
               parent: {_eq: parent_id}
            },
            fields: '*.*'
});
```

**Comment by rijkvanzanten** [comment]
`GET /items/customers?access_token=admin&filter[first_name][_eq]=null` seems to work as expected in the latest version 👍🏻  A lot has changed in the meantime, so there's a good chance this is resolved by one of those changes.

I'll close this for now, as I believe it's no longer a problem. Let me know if it still happens for you @Slations
