### ISSUE TITLE
Required m2o value cause validation error when updated from One collection

### ISSUE THREAD

**Issue by Mrmiffo** [directus/directus#4395]
**1) The issue and what you expected to happen**
 Directus throws the following error when updating a Many item, which has a required m2o relation, from the One item:
![image](https://user-images.githubusercontent.com/8545443/110141796-cb76d200-7dd5-11eb-9292-7145fc9bc456.png)
Even though the required field is populated.

**Expected:** Updating items that have a required value populated should not throw a validation error on said required value.

**2) Exact steps to reproduce this issue**

1. Create a collection called `product_type` with a text field `name`.
2. Create collection called `product` with a text field called `name`.
3. Add a m2o relation to `product` called `product_type`, check `Requires value`.
4. Create a  `product_type` item with any `name`.
5. Create a  `product` and select the  `product_type` item and give it any `name`.
6. Enter item details of the  `product_type` item.
7. Press the product.
8. Update the name of the product and save.
9. Save the product type changes.
10. Directus throws the error above.

**3) Your environment:**
    Directus npx 9.0.0rc44
    MySQL 5.7 and MySQL 8
    Chrome browser

**4) Any other relevant information we might need to reproduce this issue**
Please see attached DB dump (MySQL 5.7)
[Dump20210305.zip](https://github.com/directus/directus/files/6091836/Dump20210305.zip)

**Comment by benhaynes** [comment]
Hey! Just wanted to thank you for the detailed error report. Also, the SQL dump makes it far easier for us to debug... 👍

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/directus/pull/5615
