### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by djmtype** [directus/directus#4397]
I'm trying to install with the Directus CLI on MacOS 11.2.1.
MAMP Pro 6.3
Node v14.15.0
MySQL 5.7.32

The user and password are set to `root`.

It's failing: 
```
Something went wrong while seeding the database:
[ECONNREFUSED] connect ECONNREFUSED 127.0.0.1:8889
```

I also tried with database on port 3306.

**Comment by rijkvanzanten** [comment]
That error indicates a wrong host/port combination. Are you sure MySQL can be reached on port 8889 from wherever you're running Node?

**Comment by djmtype** [comment]
I don't know if this is something MAMP Pro had disabled or not with an update, but under MySQL settings, "Allow network access to MySQL" was disabled.
