### ISSUE TITLE
Localization issue on layouts, interfaces and displays

### ISSUE THREAD

**Issue by dimitrov-adrian** [directus/directus#4399]
There is an issue with translating some core UI components.

Layout names like tabular and cards are not translated. It seems the same issue affects also translations and layouts. May be the issue comes from the fact that these components are registered with translated names before the main app loads (so the language comes) and not use translatable names.

https://github.com/directus/directus/blob/fa7daa1f867a71e1fede4395018482f5b10953b9/app/src/main.ts#L60-L69

And how is registered

https://github.com/directus/directus/blob/fa7daa1f867a71e1fede4395018482f5b10953b9/app/src/layouts/tabular/index.ts#L4-L9

---

### Project details
Directus Version: 9.0.0-rc.44
Environment: development
OS: macOS Big Sur (11)
Node: 15.11.0

**Comment by rijkvanzanten** [comment]
Yeah that sounds about right to me! It's the same thing that caused #3384.
