### ISSUE TITLE
Date published error

### ISSUE THREAD

**Issue by djmtype** [directus/directus#4403]
I'm unsure if this has something to do with the general timestamp error already posted. But, I'm getting an issue for the `date_published` field upon save. With this error, it's impossible to save the entry, without leaving the `date_published` field empty (null).

```
{
  "message": "update `articles` set `date_published` = '2021-03-05T16:38:23-05:00', `user_updated` = 'abe8c680-16fd-44e7-8b7e-5df422af4847', `date_updated` = '2021-03-05 16:40:22.094' where `id` in ('1') - ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2021-03-05T16:38:23-05:00' for column 'date_published' at row 1",
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR"
  }
}
```

Server version: 5.7.32 - MySQL Community Server (GPL)
PHP version: 7.2.34
Directus 9.0.0-rc.44

**Comment by rijkvanzanten** [comment]
Can you try updating to the minimum required MySQL version to make sure it's not a versioning problem? 🙂 

The minimum required version is 5.7.8 as per [the docs](https://docs.directus.io/guides/installation/cli/#_1-confirm-minimum-requirements)

**Comment by djmtype** [comment]
@rijkvanzanten As I mentioned above, I'm running 5.7.32 which is greater than 5.7.8 according to how MySQL is versioned here: https://downloads.mysql.com/archives/community/ 
Correct?

The demo @benhaynes presented a couple weeks ago on YouTube shows him using MAMP Pro and it appears to be working with his version, MySQL 5.7.26. 

It's also not recommended that MySQL be upgraded/downgraded separately from MAMP Pro which why I'm hesitant to downgrade.

**Comment by rijkvanzanten** [comment]
On second look, and you already correctly commented on this, this is most likely the same problem as https://github.com/directus/directus/issues/3655, so I'll close it as a duplicate 👍🏻
