### ISSUE TITLE
Builder (M2A) interface breaks with singleton

### ISSUE THREAD

**Issue by tylerforesthauser** [directus/directus#4406]
Hey guys! I just noticed with the newest version that the M2A Builder interface gets very angry if you try adding a singleton.

1. Set up a new collection and make it a singleton
2. Set up a second collection (do not make it a singleton)
3. Add a Many to Any relationship field to your non-singleton collection and add your singleton
4. Create a new item in your non-singleton collection
5. In your Many to Any builder field, click on "Create New" and choose the singleton type
6. Enter some values into the item and save it (this should navigate you back to your collection view)
7. Start editing your collection item again
8. You'll notice that you can't edit the singleton item in your M2A builder
9. Check the console, and you'll see something along the lines of `TypeError: t.find is not a function` in your browser console

#### Environment Details
Directus 9.0.0-rc.45
PostgreSQL 13.2 (Debian)
npx
Firefox v86

**Comment by benhaynes** [comment]
I'm not sure about the root cause here, but if I'm understanding you correctly, it seems odd to use a singleton collection on the any side of that relationship type.

**Comment by tylerforesthauser** [comment]
I've got a "Pages" collection that has a page-builder sort of functionality with components whose content is mostly unique to each page except for a couple components which would be identical regardless of which page they are on (those would be my singletons). 

Regardless, my initial thinking was that the error was related to fetching the display template for the related item and that it may be different for singletons. 🤷‍♂️

**Comment by tylerforesthauser** [comment]
<img width="596" alt="Screen Shot 2021-03-07 at 5 38 33 PM" src="https://user-images.githubusercontent.com/1226786/110261112-188cac80-7f6c-11eb-8fcf-0f168b76e24f.png">

**Comment by rijkvanzanten** [comment]
> Regardless, my initial thinking was that the error was related to fetching the display template for the related item and that it may be different for singletons. 🤷‍♂️

Sounds very plausible to me 👍🏻

**Comment by benhaynes** [comment]
> I've got a "Pages" collection that has a page-builder sort of functionality with components whose content is mostly unique to each page except for a couple components which would be identical regardless of which page they are on (those would be my singletons).
> 
> Regardless, my initial thinking was that the error was related to fetching the display template for the related item and that it may be different for singletons. 🤷‍♂️

Ahh, that all makes sense, thanks for the clarification!

**Comment by rijkvanzanten** [comment]
I don't think adding a _singleton_ into a parent m2a with _multiple_ items is something we should support 🤔 The fact that it is a singleton kind of breaks the idea of what a m2a is currently (having multiple copies of the same type, intertwined/sorted). It sounds like that the true solution for this use case would be to create a _one-to-many_ style M2A type, where every related section can only exist in a single parent (just like o2m vs m2m).

**Comment by tylerforesthauser** [comment]
Unfortunately that would not work for me as the idea of a page builder is that you can have that builder available on multiple pages. All I want to be able to accommodate is adding singleton components whose content doesn't change alongside other "dynamic" components whose contents change depending on their individual instances.

**Comment by rijkvanzanten** [comment]
We'll open a new discussion for that specific use case 👍🏻

**Comment by rijkvanzanten** [comment]
> I guess I'm saying that I fail to see the issue with supporting this functionality. Allowing singletons simply allows for more flexibility, in my mind.

Yeah makes sense! I get the usefulness; I'll have to consider it a new feature request (hence the discussion) instead of a bug in the app, as it was never intended to work in the first place 👍🏻

**Comment by tylerforesthauser** [comment]
> ...as it was never intended to work in the first place 👍🏻

Ahhh I gotcha I gotcha. Yeah, I would love to see this as a feature. Clearly 😜
