### ISSUE TITLE
Migration to Directus v.9 causes authentication to fail - Argon2

### ISSUE THREAD

**Issue by NCorreia100** [directus/directus#4413]
Hello,
I was trying to upgrade our application from Directus v.8 to v.9, so I did a fresh installation and was able to skim through error after error (related to db missing fields relative to previous version) until I hit a roadblock.

When server goes online (locally), it correctly identifies when password or email is incorrect, but then authentication is terminated when it should succeed.

Here's the stacktrace:
![image](https://user-images.githubusercontent.com/29066146/110224805-81a8ed00-7ea4-11eb-823a-a4b556cf61ad.png)

Apparently this is caused by argon2 which is responsible for hashing the password and verify if it matches the hash stored for the user. Argon2 calls `verify()` to check that input password matches stored hash, however, when argon2 calls `deserialize(digest)` to process the hashed password, the resulting object is missing `m`, `t`, `p` and `data` properties:
      
    const verify = async (digest, plain, options) => {
      const { id, version = 0x10, params: { m, t, p, data }, salt, hash } = deserialize(digest)

![image](https://user-images.githubusercontent.com/29066146/110225801-6b079380-7eae-11eb-9b33-4d5326713154.png)

Eve if I programmatically set the values of `m`, `t` and `p` (as per https://github.com/P-H-C/phc-winner-argon2#library) it still doesn't work, throwing an error stating that `Salt is too short`.

Tried 3 different versions of argon2 and 2 operating systems (Windows 10 and CentOS 8) to no avail.
I'm using MySQL. Let me know if you need my configs.
Thanks in advance.

**Comment by rijkvanzanten** [comment]
> I was trying to upgrade our application from Directus v.8 to v.9, so I did a fresh installation and was able to skim through error after error (related to db missing fields relative to previous version) until I hit a roadblock.

To confirm, you installed v9 on top of a v8 database, and manually adjusted the db until it worked on V9? Could it be that you're trying to use a v8 password in this v9 installation? The hashing algorithm changed between the two (from bcrypt to argon2), so passwords created in v8 are incompatible with v9.

**Comment by NCorreia100** [comment]
Thank you @rijkvanzanten, that makes perfect sense.

The ideal scenario is to keep using v.8 until there are no errors/bugs with v.9. However, we would have to store a new password hash for all users, correct?

Is there a more effective way to upgrade the version of Directus, other than just rebuild all functionality from scratch? I mean, from all the work already done, I'm confident that storing new passwords is still far away from performing the many adjustments required until completion, and we can't afford to have a whole week of downtime for maintenance work.

**Comment by benhaynes** [comment]
Just want to mention, it is pretty rare to see any software with no bugs at all. Also, v9 is already far more stable (fewer errors) than v8. 😊

We have an unofficial migration script, and are hoping to have that finished up and made official soon. However even that can't migrate everything, because there are simply too many fundamental differences between the versions.

**Comment by NCorreia100** [comment]
Thank you for the clarification @benhaynes. 

I ran the script `npx directus database migrate:latest` to update the database but the progress has been slow, because every time it fails for FK contraints being missing, for instance, it doesn't check if these were dropped already so I got a ton of prep work to do prior to running the script each time. Will there be  another script available?

I feel like this migration work that I'm doing is going to waste as there's just too many fundamental differences as you guys pointed out. Just a simple concrete example, on the directus_relations table, collection_one and collection_many fields in v9 becomes one_collection and many_collection. I've seen this discrepancy all over the database, including users and roles.
 
Directus is pretty solid as a platform, so far the only real problems I've seen relate to M2M relations, though I've only explored a quarter of all the features.

I look forward to your progress regarding making migrations to v9 more feasible.

**Comment by rijkvanzanten** [comment]
> I ran the script npx directus database migrate:latest to update the database but the progress has been slow, because every time it fails for FK contraints being missing, for instance, it doesn't check if these were dropped already so I got a ton of prep work to do prior to running the script each time. Will there be another script available?

Just to clarify, the v9-included `npx directus database migrate:latest` is to upgrade a v9-powered database to the latest version of v9, and is not supposed to migrate a v8-database to v9. There will be a standalone tool and guide on how to (semi-)automatically migrate a v8 instance to v9 👍🏻

**Comment by NCorreia100** [comment]
Got it, thanks @rijkvanzanten!
Please let me know when it becomes available and how long will the application need to be down for maintenance. About 300k users see our platform per day, it might be not even feasible to upgrade.

**Comment by rijkvanzanten** [comment]
@NCorreia100 Downtime can be minimized, depending on your deployment strategy and project usage. I'm assuming you're using Directus to power an external platform, in which case you could setup a new v9 instance, get it all migrated and ready to go, and "flip the switch" as it were from the old to the new. You could even re-launch your platform on a standalone IP, and use DNS to flip the switch, in which case you wouldn't have any downtime on the user-side whatsoever. There's options 🙂  It's hard to say exactly what the best way to go is though, without deep insider knowledge about your project and it's infrastructure

**Comment by benhaynes** [comment]
Just checking in on the intended action points here — it's labeled as "Needs more info"... what else do we need to resolve this? It's not clear what needs to happen to close this issue.

**Comment by rijkvanzanten** [comment]
There's no actionable points. We won't migrate passwords between v8 and v9, as we are relying on a different hashing algorithm. Ref https://github.com/directus/directus/discussions/4718

**Comment by dannycoulombe** [comment]
Suggestion: the command `npx directus database migrate:latest` should be added to `package.json`. I haven't find anything in the doc regarding this command aside from this thread.

**Comment by rijkvanzanten** [comment]
@dannycoulombe https://docs.directus.io/guides/projects/#upgrading-updating-a-project
