### ISSUE TITLE
Search filter shared between multiple files field and File library

### ISSUE THREAD

**Issue by TheAzack9** [directus/directus#4416]
Hey there!

1) The issue and what you expected to happen
    In short, it seems that the filter is shared when adding a file in a multiple files field and in the file library. It might be intentional behavious, but it puzzled me for a minute where all my images went :)

When adding the filter here:
![image](https://user-images.githubusercontent.com/2140448/110239967-f5e99c00-7f49-11eb-949a-7deb5524c7b2.png)
When i exit and go the the file library it's still filled. (Might be intentional? i was confused at least lmao)
![image](https://user-images.githubusercontent.com/2140448/110239977-fda94080-7f49-11eb-863a-d926deaa06a5.png)

I would expect the filters to behave independent of eachother.

2) Exact steps to reproduce this issue
Setup a collection with a multiple files field and then try to add an existing file. Add a search filter 

3) Your environment:
Directus 9.0.0 rc-45
MySQL 8
Azure as deployment (but running docker in the back)
Chrome version:  88.0.4324.190
    What version of Directus you are using.
    Which DBMS are you using (MySQL 8, Postgres 12, ...).
    Which deployment are you using (npx, Docker, ...).
    What browser are you using (Chrome 87, Safari 14, ...).

4) Any other relevant information we might need to reproduce this issue
I do rely on Azure for storage and database, but i do not think it is relevant for this issue :) 

If you need more info, please ask and i will try my best to provide them!

**Comment by benhaynes** [comment]
Hmm, yeah, that seems confusing. I think the interfaces should _use_ the preferences of the main layout, but not save anything into the user's preferences.
