### ISSUE TITLE
Building the code in RC45 fails

### ISSUE THREAD

**Issue by danieljwestman** [directus/directus#4418]
macOS
Directus RC45
PG 12

Can't build the code (running `npm install` on clean clone install).

Errors:

```
src/types/field.ts(1,24): error TS2307: Cannot find module '@directus/schema/dist/types/column' or its corresponding type declarations.
src/types/collection.ts(2,23): error TS2307: Cannot find module '@directus/schema/dist/types/table' or its corresponding type declarations.
src/utils/get-local-type.ts(2,24): error TS2307: Cannot find module '@directus/schema/dist/types/column' or its corresponding type declarations.
src/utils/get-default-value.ts(2,24): error TS2307: Cannot find module '@directus/schema/dist/types/column' or its corresponding type declarations.
```

Building RC44 is working fine.

**Comment by benhaynes** [comment]
Did you try...

1. Delete all `node_packages` folders
2. `npx lerna clean`
3. `npm i`

**Comment by rijkvanzanten** [comment]
Pretty sure the above will help, if not we'll reopen

**Comment by danieljwestman** [comment]
@benhaynes @rijkvanzanten the node_modules dirs doesn’t comes with a clean new git clone... Therefore it’s nothing to be cleaned...

Maybe I should try delete som package-lock files... 🤷🏽

**Comment by rijkvanzanten** [comment]
Also make sure you're on Node 15+ / NPM 7 when you do, there've been some breaking changes in NPM itself, causing npm < 7 to have some trouble with package-lock files created in 7+ ᕕ( ᐛ )ᕗ

**Comment by danieljwestman** [comment]
@rijkvanzanten Hm, nope.. No difference...

Node v15.11.0 
NPM v7.6.0

RC45 doesn't build (errors like above). 
RC44 build as it should.
