### ISSUE TITLE
sqlite support error

### ISSUE THREAD

**Issue by potros** [directus/directus#4423]
when i try to init a new app with sqlite and run npx directus start the terminal show this error:

```
[Error: SQLITE_CANTOPEN: unable to open database file] {  
  errno: 14,                                              
  code: 'SQLITE_CANTOPEN'                                 
} 
```                                                       

commands  
`npx create-directus-project my-project`  
`cd my-project`  
`npx directus start`  

my environment:
    What version of Directus you are using : directus rc-45
    Which DBMS are you using : sqlite
    Which deployment are you using : npx
    What browser are you using : Chrome 87

**Comment by rijkvanzanten** [comment]
What OS is this on @potros? It seems to create the database file on install on my end (macOS), so it might be a difference in OS? 🤔 

<img width="622" alt="CleanShot 2021-03-08 at 12 20 50@2x" src="https://user-images.githubusercontent.com/9141017/110356953-c51c6c00-8008-11eb-877e-89d99e640dde.png">

**Comment by rijkvanzanten** [comment]
> if you tried npx directus start it shows some error

Yup! It shouldn't be a difference though, as both `init` and `start` will access the database using the configured `Database File Path`, so if one works, the other should too.

If you look in your `.env`, what is the file path for `DB_FILENAME` ? 

Did you happen to move the installation folder after installing?

**Comment by potros** [comment]
no i did nothing i created the project && cd into it && run npx directuus start

**Comment by potros** [comment]
error message :
[Error: SQLITE_CANTOPEN: unable to open database file] {
  errno: 14,
  code: 'SQLITE_CANTOPEN'
}

**Comment by rijkvanzanten** [comment]
What's the path saved in your `.env` file?

**Comment by potros** [comment]
C:\......\database_path

**Comment by potros** [comment]
ok i tried v9.0.0-rc.53 and problem solved for me so i'm closing this issue

**Comment by surfmuggle** [comment]
I am running into the same issue. 



![output_after_npx_directus_start](https://user-images.githubusercontent.com/1271555/141707425-432644c2-e066-44d3-ac62-6eae6528700c.png)

If i open the sqlite-database data.db in DBeaver it seems to be broken.

![DBeaver_data.db_seems_coruppt](https://user-images.githubusercontent.com/1271555/141707571-074e4741-b440-4527-947c-5a503c599d92.png)

**Comment by surfmuggle** [comment]
I updated npm. 
I installed it manuall with yarn as written here https://npm.io/package/create-directus-project unsing. This did AFAIR use a newer version 

`yarn create directus-project my-project`

I changed the path to the database to this

```
## Database

DB_CLIENT="sqlite3"
DB_FILENAME=".\data.db"

```

And one of this seems to did the trick: directus is now running.

**Comment by azrikahar** [comment]
@surfmuggle Thanks for the update, and glad it's resolved! On a surface level, it might just be some io related issue where the creation process got interrupted by the OS or something, rather than Directus itself, but yea hard to pinpoint with the current info at hand.

With that said, if the problem ever resurfaces, it is recommended to create a new issue whilst also referencing past issues that you may think are related. This way we won't end up pinging other users in this issue that already have their issue resolved 👍
