### ISSUE TITLE
M1 chip specific issue: Won't build sharp dependency

### ISSUE THREAD

**Issue by dhhdev** [directus/directus#4424]
But here is how to fix it: https://sharp.pixelplumbing.com/install#apple-m1

The script doesn't take this into account when creating a new directus project. This obviously only affect Apple Silicon users, but would be good to mention - or maybe even check for somehow.

I just wanted to quickly share it, as well as the solution. (I simply used brew to install vips.)

Now to finally check out directus 😄

**Comment by rijkvanzanten** [comment]
> - or maybe even check for somehow.

Instead of checking / working around it in Directus itself, I think I prefer waiting for Sharp's official "intended" implementation, as per their comment:

> _When this new ARM64 CPU is made freely available to open source projects via a CI service then prebuilt binaries can be provided._

**Comment by dhhdev** [comment]
> > or maybe even check for somehow.
> 
> Instead of checking / working around it in Directus itself, I think I prefer waiting for Sharp's official "intended" implementation, as per their comment:
> 
> > _When this new ARM64 CPU is made freely available to open source projects via a CI service then prebuilt binaries can be provided._

I am totally with you on this one, but might be good to have mentioned in the documentation for now.

**Comment by rijkvanzanten** [comment]
Yeah! Which I did in https://github.com/directus/directus/commit/3308b9b3fce7c7a4f02e446fab6c8f824515d065 🙂

**Comment by davidpfahler** [comment]
In the meantime, the sharp documentation has changed and is now giving the wrong instructions regarding the directus installation. As long as direcutus is referencing sharp version 0.27 (currently 0.28 is current), you need to install libvips via homebrew beforehand (which is no longer explained in the sharp documentation, as this has changed for sharp 0.28). See https://github.com/lovell/sharp/commit/4264c0577e8a0e74164a768bcd17e26d9593cd59#diff-162b45a313f5f057a233411edbe31e72a13185f4df0ae0e1af2c13521bc05d5a
