### ISSUE TITLE
Install fails: CXXABI_1.3.9 not found

### ISSUE THREAD

**Issue by yakou32** [directus/directus#4426]
Hello!
I'm coming back to Directus to test the newest version.
But I can't install it. I just follow the quick start guide with this command:
`npx create-directus-project example-project`

I get this:
```
npx: installed 53 in 3.685s
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by [...]/directus-cms/node_modules/argon2/lib/binding/napi-v3/argon2.node)
```

Any idea of what I could do?

**Comment by dhhdev** [comment]
I suspect you need the build-essential package. If you run a Debian variant like Ubuntu, you can simply do:

`sudo apt install build-essential`

You simply do not have the tools required/installed to be able to compile the code for use.

**Comment by rijkvanzanten** [comment]
What @dhhdev mentioned sounds right to me. I'll close this for now. We can reopen if that didn't fix it 👍🏻
