### ISSUE TITLE
Global Query Parameter *Deep* does not work as intended

### ISSUE THREAD

**Issue by flicksolutions** [directus/directus#4428]
The deep filter does not work as intended.
For rc44 it worked when using square brackets and just didn't apply a filter when using Object syntax.
Now, in rc45 you get an error 500 when using Object syntax and no filter is applied when using square brackets.

As an example:
Using the Javascript SDK the following code does **not** work:
```
directus.items(directory).read({
	fields: fields,
	deep: { 
		"translations": {
			"filter": {
				"languages_code": {
					"_eq": "en"
					}
				}
			}
		}
	}
)
```
For rc44: Using this syntax, no filter is applied. For rc45 this gives a error 500

But this code works in rc44:
```
directus.items(directory).read({
	fields: fields, 
	"deep[translations][filter][languages_code][_eq]": "en"
	}
)
```

For rc44: Using this syntax the filter is correctly applied. For rc45 no filter is applied

-----------------------

I am using the standard Digital Ocean Marketplace build. Npm, PostgreSQL 12, Node.js 14

Thank you for looking into this!

**Comment by rijkvanzanten** [comment]
Heya! `deep` requires the "query" to be prefixed with an underscore (similarly to filter operators) in order to support deep-deep nesting 🙂 

https://docs.directus.io/reference/api/query/#deep

`"deep[translations][filter][languages_code][_eq]": "en"` would be `"deep[translations][_filter][languages_code][_eq]": "en"`

**Comment by flicksolutions** [comment]
Hey Rijk!
Thanks for your answer and the clarification!
So square bracket annotation works and I get the change and why it's necessary. Thanks! That's nice!
I'm sorry to ask then, but Object-Syntax just produces an HTTP 500 error. Is that also something I've overlooked on my end?

At least this still does:
```
deep: { 
		"translations": {
			"_filter": {
				"languages_code": {
					"_eq": "en"
					}
				}
			}
		}
	}
```

**Comment by rijkvanzanten** [comment]
IIRC that should be parsed to the same structure in the API. Could you double check in the network tab what the "actual" request is that's being made? I forgot if Axios (underlying http lib in the sdk) does any sort of flattening of that object ahead of time.

FWIW

```
deep: { 
		"translations": {
			"_filter": {
				"languages_code": {
					"_eq": "en"
					}
				}
			}
		}
	}
```

should be equal to

```
deep[translations][_filter][languages_code][_eq]=en
```

so if the latter works, so should the first

**Comment by flicksolutions** [comment]
If I use square brackets these are the actual parameters of the request (taken straight from the network tab): `fields[]=translations.title&fields[]=id&fields[]=date&deep[translations][_filter][languages_code][_eq]=en`

If I use Object-annotation, these are the parameters: `fields[]=translations.title&fields[]=id&fields[]=date&deep=%7B%22translations%22:%7B%22_filter%22:%7B%22languages_code%22:%7B%22_eq%22:%22en%22%7D%7D%7D%7D`

Parsed curly brackets go directly into the request...

**Comment by rijkvanzanten** [comment]
Ahh yeah I see, small oversight on my end. Filters are sanitized as an object if the whole object is passed in, `deep` isn't (yet) 👍🏻
