### ISSUE TITLE
Some small UI issues

### ISSUE THREAD

**Issue by iksent** [directus/directus#4442]
I have found a small UI problems, that appeared with Russian language.
Directus' design is just ideal and I think you are interested to fix such a small problems too ;)

1. Export data checkbox

![2021-03-09_10-15-22](https://user-images.githubusercontent.com/32956521/110422190-ad082380-80c0-11eb-89c8-6f54c8ae1355.jpg)

2. Unsaved changes

![2021-03-09_10-12-46](https://user-images.githubusercontent.com/32956521/110422209-b98c7c00-80c0-11eb-9e98-f40fd91900bb.jpg)

3. Very likely there should not be "ID", but only a model name (not connected with Russian, this is for all languages)

![2021-03-09_10-23-01](https://user-images.githubusercontent.com/32956521/110422669-9dd5a580-80c1-11eb-97f2-ae9e2f9264a1.jpg)

---

### Project details
Directus Version: 9.0.0-rc.45
Environment: production
OS: macOS Big Sur (11)
Node: 14.15.4

**Comment by benhaynes** [comment]
Definitely! I think this will always be an issue though. It would be too difficult to make every bit of Core App text work with any length, and different languages might have big swings in translation length. I think we can do the following:

* Add recommended text lengths to Crowdin
* Add overflow ellipses and tooltips to certain places in the App
* Request shorted translations for certain strings

**Comment by iksent** [comment]
I think wrapping on a new line and ellipses texts is the best choice, because it's a simple and universal solution.

**Comment by benhaynes** [comment]
The code fix is for the specific Export Data issue, and I also updated a max-length in Crowdin to resolve the "Keep Editing" length. The ID suffix is expected if that is in the schema.
