### ISSUE TITLE
Supporting relative paths

### ISSUE THREAD

**Issue by MoltenCoffee** [directus/directus#4451]
Hi!
I'm trying to run Directus locally on windows. 
Everything works fine, up until the point I want to change my configuration file to a `config.js` file in the project directory. 

### Problem

In order to implement this in a script in package.json, I use cross-env to set a env variable:

```json
{
  "scripts": {
    "start": "cross-env CONFIG_PATH='./config.js' directus start"
  }
}
```

However, when I do this, I receive the error "Cannot find module". I've tracked down the error to `env.js` of the `directus` module.

#### Environment

Windows 10
Node v15.5.0
NPM 7.3.0

Project created using the npx script.

### Diagnosis

The thing is, this checks for `process.env.CONFIG_PATH` (which is set) and stores it as `configPath`.
It then checks if this file exists using `fs.existsSync(configPath)`, and if it does and the file extension is `.js`, it will try to load the contents using `require(configPath)`.

This, however, _does not work_, and gives the "cannot find module" error. This is because `existsSync` uses the "current working directory" (`process.cwd()`), to resolve a path (which is the project directory), and require tries to use `__dirname` first, which is the location of the current script file (buried in `node_modules`). For absolute paths, this is not a problem, but it is for relative paths.

### Solution

I do think this is a bug. As `require()` and `existsSync()` are fundamentally different in how they treat paths, the same variable cannot be passed to them without processing.  

I think the solution is quite easy to implement:

```js
// Current
// directus/api/src/env.ts

function getEnv() {
  const configPath = process.env.CONFIG_PATH || defaults.CONFIG_PATH;
```

```js
// Solution
// directus/api/src/env.ts

function getEnv() {
  const configPath = path.resolve(process.env.CONFIG_PATH) || defaults.CONFIG_PATH;
```

This would always use process.cwd() as its starting point. Earlier in the same file, `path.resolve()` is already used to set `defaults.CONFIG_PATH`.

**Comment by rijkvanzanten** [comment]
Wanna open a PR for that @MoltenCoffee? 

Groetjes!

**Comment by MoltenCoffee** [comment]
Sure! #4453

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/directus/pull/4453
