### ISSUE TITLE
Can't output inner translations field

### ISSUE THREAD

**Issue by iksent** [directus/directus#4457]
1. I have Articles and Categories
2. Articles has Categories (M2M)
3. Categories has translations
4. Each category translation has "Name" field
5. Each category has "Name" field (for testing only)
![Снимок экрана 2021-03-10 в 13 45 10](https://user-images.githubusercontent.com/32956521/110602983-59710500-81a8-11eb-96e7-dc1d20a9c517.png)
6. Editing categories translations works OK from categories:
![Снимок экрана 2021-03-10 в 13 45 20](https://user-images.githubusercontent.com/32956521/110603143-81606880-81a8-11eb-8ba5-6e1aaeac32db.png)
7. But displaying categories name from translations and editing it not working at Articles:
![2021-03-10_14-01-09](https://user-images.githubusercontent.com/32956521/110603725-21b68d00-81a9-11eb-8f73-1bfeac59e093.jpg)
![2021-03-10_14-00-40](https://user-images.githubusercontent.com/32956521/110603758-2c712200-81a9-11eb-9c53-c5cb3cc0e7a1.jpg)
8. I have selected Name for table from translations:
![Снимок экрана 2021-03-10 в 13 47 59](https://user-images.githubusercontent.com/32956521/110603333-b8cf1500-81a8-11eb-9d4f-15e98ac31aae.png)

MariaDB dumb: 
[dump-1.sql.zip](https://github.com/directus/directus/files/6114597/dump-1.sql.zip)

### Project details
Directus Version: 9.0.0-rc.45
Environment: production
OS: Linux 5.4.0-65-generic
Node: 14.16.0

**Comment by rijkvanzanten** [comment]
This is because `name` is nested inside of an array of `translations`, so there's no known display configured for that field 🤔

**Comment by iksent** [comment]
I just can't understand why it works for my Categories:
https://yadi.sk/i/_f0lN0-WtWQjtg

And doesn't work for tags, which has very similar structure (except the "Name" field, that I don't use for display...):
https://yadi.sk/i/Q2pEYtNprON1kA

**Comment by iksent** [comment]
> This is because `name` is nested inside of an array of `translations`, so there's no known display configured for that field 🤔

May be can get an element, that will match user's language (but this will suits only translations) or just get the first element...

**Comment by iksent** [comment]
> And doesn't work for tags, which has very similar structure (except the "Name" field, that I don't use for display...):

I have added "Name" field for Tags and they also started to work!
What a strange behavior...

**Comment by rijkvanzanten** [comment]
This was fixed in https://github.com/directus/directus/commit/cb4bf88e66a2883031b965ea924f25fc1dc6f831 (we no longer allow selecting nested items in a o2m setting). 

> May be can get an element, that will match user's language (but this will suits only translations) or just get the first element...

This is exactly the plan! We're planning on adding a dedicated `translations` display that will render a template for the current user's language 🙂

**Comment by iksent** [comment]
By the way I think my problem is very similar to https://github.com/directus/directus/issues/3432
