### ISSUE TITLE
sometimes relation fields (O2M, M2M) appear as string fields for graphql api

### ISSUE THREAD

**Issue by FabriceLapeyrere** [directus/directus#4458]
Hi everyone and thanks for this amazing project !

I have an issue with the graphql api : sometimes relation fields (O2M, M2M) appear as string fields. Sometimes means it's not on every collection, some work as expected... strange...

As a result I get that error when i try to fetch data :
`Field "slugs" must not have a selection since type "String" has no subfields.`

![slugs](https://user-images.githubusercontent.com/1675984/110633745-6a6e4600-81a9-11eb-9ba8-d221befca02b.jpg)
![slugs2](https://user-images.githubusercontent.com/1675984/110633128-afde4380-81a8-11eb-8f12-5b4c2fa46183.jpg)

---

### Project details
Directus Version: 9.0.0-rc.45
Environment: production
OS: Linux 5.4.0-62-generic
Node: 10.23.0

**Comment by rijkvanzanten** [comment]
This is most likely caused by the relationship information missing / being corrupted in `directus_relations`. Somebody ran into a similar problem the other day, so I'm assuming this might've been caused by the same problem: 

https://github.com/directus/directus/issues/4245

**Comment by FabriceLapeyrere** [comment]
#4245 didn't solve my case... I tried many things, including delete and recreate the collection and relations, but I still don't understand... I'm on 9.0.0-rc.46 now : same behaviour.

A csv export (directus_collections, directus_fields, directus_relations) : [csvs.zip](https://github.com/directus/directus/files/6122191/csvs.zip)

I found something else : 
![Screenshot_2021-03-11 GraphiQL](https://user-images.githubusercontent.com/1675984/110771404-bf1dc980-825a-11eb-953a-9e293a5a5e57.png)
![Screenshot_2021-03-11 GraphiQL(1)](https://user-images.githubusercontent.com/1675984/110771502-db216b00-825a-11eb-827f-58bfde65b08d.png)

**Comment by rijkvanzanten** [comment]
Does the user you're using have permission to read from `artistes`? Is there a junction table between `audios` and `artistes`?

**Comment by FabriceLapeyrere** [comment]
I have permission (same behaviour with admin access_token).
I have a table named audios_artistes :
```
CREATE TABLE `audios_artistes` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `artistes_id` int(11) DEFAULT NULL,
  `audios_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```
Here is the full db schema : 
[directus.sql.txt](https://github.com/directus/directus/files/6123173/directus.sql.txt)

**Comment by FabriceLapeyrere** [comment]
Ok, I found the bug !
I have many relations on this project and there is a default limit set at 100 in database/run-ast.ts so graphql does not get the full relations table but a troncated one.
Setting the limit to 1000 in run-ast.ts line 149 solves my issue :

`	queryCopy.limit = typeof queryCopy.limit === 'number' ? queryCopy.limit : 100;`
 ->
`	queryCopy.limit = typeof queryCopy.limit === 'number' ? queryCopy.limit : 1000;`

I don't know the project deep enough, but maybe in services/graphql.ts the limit should be explicitly set (no limit).

**Comment by rijkvanzanten** [comment]
Great find!

**Comment by viters** [comment]
I've started to experience the same issue on 9.4.3. I have 62 collections atm (both collections and hidden collection like for m2m). Last relations I have created (the first ones on 9.4.3 though) are returning String as type in GraphQL schema.
