### ISSUE TITLE
Unable to run migrations from rc.45 to rc.46

### ISSUE THREAD

**Issue by maartenvn** [directus/directus#4470]
Migrating from rc.45 to rc.46 fails to start due to a database constraint error:

```
07:58:17 ✨ Initializing bootstrap...
07:58:17 ✨ Database already initialized, skipping install
07:58:17 ✨ Running migrations...
error: alter table "directus_activity" drop constraint "directus_activity_collection_foreign" - constraint "directus_activity_collection_foreign" of relation "directus_activity" does not exist
    at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 166,
  severity: 'ERROR',
  code: '42704',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '10799',
  routine: 'ATExecDropConstraint'
}
```

---

### Project details
Directus Version: 9.0.0-rc.46
Database: Postgres 13
Environment: production
OS: Linux 5.4.0-65-generic
Node: 14.16.0

**Comment by iksent** [comment]
Got the same error, just skipped migrations and everything is working OK 🤷‍♂️

**Comment by lahdekorpi** [comment]
This happens on MySQL as well.

**Comment by maartenvn** [comment]
> Got the same error, just skipped migrations and everything is working OK 
> (MariaDB)

The problem is that Docker automatically runs migrations between versions. There is no way to skip.

**Comment by margusk** [comment]
![image](https://user-images.githubusercontent.com/15229388/110756004-4dda1880-8252-11eb-9639-c1a8e070247c.png)

Migrations from rc.45 to rc.46 fails here too and when try to update field created before migrations gives error related to database

**Comment by will83** [comment]
Same with fresh install with MySQL 8.0
![Capture d’écran 2021-03-11 à 09 42 25](https://user-images.githubusercontent.com/804476/110759619-1b2e2100-824e-11eb-9e3d-7a4f843e4a78.png)
