### ISSUE TITLE
Throw 400 on missing filter value 

### ISSUE THREAD

**Issue by iksent** [directus/directus#4471]
1. Filters works OK, when they were passed:

![2021-03-11_13-02-06](https://user-images.githubusercontent.com/32956521/110755064-58081100-826a-11eb-8e11-b63b43cfe79d.jpg)

2. But query has errors, when no arguments passed for filters:

![Снимок экрана 2021-03-11 в 13 03 53](https://user-images.githubusercontent.com/32956521/110755158-73731c00-826a-11eb-9537-dca64d8c603a.png)

3. Neither with `_in`, nor with `_eq`

![Снимок экрана 2021-03-11 в 13 04 17](https://user-images.githubusercontent.com/32956521/110755234-8b4aa000-826a-11eb-9f8f-f410ac97fe43.png)

```
query getArticleListWithFilters($cat_id: ID) {
  items {
    article(filter: {categories: {id: {_eq: $cat_id}}}) {
      id
      status
      date_created
      date_updated
      categories {
        id
        category {
          name
        }
      }
    }
  }
}
```

MariaDB dump: [dump-2.sql.zip](https://github.com/directus/directus/files/6121383/dump-2.sql.zip)

### Project details
Directus Version: 9.0.0-rc.46
Environment: production
OS: Linux 5.4.0-65-generic
Node: 14.16.0

**Comment by iksent** [comment]
Oh... why throw 400? :) But how to avoid filtering when not passing variables to graphql filters?

**Comment by rijkvanzanten** [comment]
Cause you're trying to filter by `_eq` = `undefined`, which is illegal, so it should be a bad request? 🤔

**Comment by iksent** [comment]
This depends on how to process the received parameters.
For example I have a GraphQL query with several filters. How can I achieve filtering by only passed params from client?
There are situations when not all filters are active.

**Comment by rijkvanzanten** [comment]
That sounds more like an implementation problem where you're creating this GraphQL query than a Directus validation problem to me 🤔 

IMO If you send an invalid filter, Directus should throw an error that the filter is invalid. (It currently already does, as it crashes when trying to execute the invalid filter) (Similarly to trying to read a field/collection that doesn't exist)

**Comment by iksent** [comment]
One thing is when we are trying to create any item with required field - we should definitely return an error for invalid fields, that are required.

And the other thing, is when we are trying to search or filter items - I think we should just ignore null or undefined params, like if they were not passed

**Comment by rijkvanzanten** [comment]
>  I think we should just ignore null or undefined params, like if they were not passed

There would be a difference between `null` and `undefined` in that case though. `_eq: null` should be treated like `_null`

**Comment by iksent** [comment]
What is “treated like null”? Is it equals to ignore?

I tried to pass null and it doesn’t work either - there was the similar problem.

**Comment by rijkvanzanten** [comment]
See https://github.com/directus/directus/issues/4386

**Comment by iksent** [comment]
`_eq: null` should be treated like `_null`

Hm.. If I understood it right, then it won't help in my case.
When I'll pass `null` to filter argument, then it will compare this item's field value to `null`, is it right? But it's not null, only passed filter is null.

**Comment by iksent** [comment]
The main problem for me is that GraphQL doesn't allow not to pass defined variables:

```
query getArticleListWithFilters($cat_id: ID) {
  items {
    article(filter: {categories: {id: {_eq: $cat_id}}}) { <<< I just can't skip filter param when $cat_id in null...
      id
      status
      date_created
      date_updated
      categories {
        id
        category {
          name
        }
      }
    }
  }
}
```

This can be easily avoided at the REST, where you have full control over your variables.

**Comment by TheSunNeverSetsOnDream** [comment]
by the way ,bloom filter also

**Comment by iksent** [comment]
@TheSunNeverSetsOnDream, what do you mean? :)

**Comment by iksent** [comment]
Wow!
Will test it ASAP, thanks!

**Comment by rijkvanzanten** [comment]
@iksent I went ahead and did it the way you preferred it 😉 Instead of throwing an error for missing filter values, it just ignores the filter completely

**Comment by iksent** [comment]
I've tried filtering via GraphQL again, and here is the result:

GraphQL query:
```
query getArticles($cat_slugs: [String]) {
  article(
    filter: {
      status: { _eq: "published" }
      categories: { category: { slug: { _in: $cat_slugs } } }
    }
  ) {
    id
    status
    categories {
      category {
        id
        slug
        translations(filter: { languages_code: { code: { _eq: "ru-RU" } } }) {
          name
        }
      }
    }
    ...
```

Trying to execute a query without passing a `cat_slugs` variable and getting the next error:
```
Undefined binding(s) detected when compiling SELECT. Undefined column(s): [mepbk.slug] query: select `article_category`.`article` as `article` from `article_category` left join `category` as `mepbk` on `article_category`.`category` = `mepbk`.`id` where `mepbk`.`slug` in (?)
```

**Comment by rijkvanzanten** [comment]
@iksent TIL that GraphQL reports that exact example as `[undefined]` instead of `undefined` :|

**Comment by iksent** [comment]
Something else is wrong...

I am getting not all Articles, but only those, which have Categories.
This is for my previous query also (https://github.com/directus/directus/issues/4471#issuecomment-828670002)

I have checked, that this filter (with `[undefined]` value) is ignoring now, but something else is filtering Articles... Can it be something inside `addWhereClauses` or `addJoins`?

**Comment by rijkvanzanten** [comment]
@iksent What is the exact query you're executing here?

**Comment by rijkvanzanten** [comment]
@iksent This is the same as the new issue you posted right? https://github.com/directus/directus/issues/5551

**Comment by rijkvanzanten** [comment]
Ohh yeah now I see 👍🏻 Mind opening a new issue with this specific problem as well? Little easier to discuss than on a previous issue. I think the problem arises once you filter on a nested field from what it seems
