### ISSUE TITLE
When upload image to WYSWYW editor, the uploader be masked.

### ISSUE THREAD

**Issue by wind13** [directus/directus#4472]
When I try to use WYSWYW editor upload an image, the uploader showed behind the image source dialog, so I can not click image uploader to upload image.

---

### Project details
Directus Version: 9.0.0-rc.45
Environment: production
OS: Linux 5.4.0-67-generic
Node: 14.15.4

**Comment by iksent** [comment]
Duplicate of https://github.com/directus/directus/issues/4354
