### ISSUE TITLE
M2M Filtering with '_and' operator not working

### ISSUE THREAD

**Issue by JH1ller** [directus/directus#4478]
Example situation:

Vehicles collection with fields:
`options: m2m -> Options`

Options collection with fields:
`value: string`

We now want to get all vehicles that have an option with value `climate_control` AND an option with value `navigation`

A very similar situation is described in this old directus8 issue:
https://github.com/directus/v8-archive/issues/967

What we tried: (excerpt of directus-sdk call)
```typescript
_and: [
            {
              options: {
                options_option_id: {
                  value: {
                    _eq: 'climate_control'
                  }
                }
              },
            },
             {
              options: {
                options_option_id: {
                  value: {
                    _eq: 'navigation'
                  }
                }
              },
            },
          ]
```

The API returns 200 OK, but with an empty array as the data.
The problem seems to be having the same object twice in the `_and` array, because when we combine two different collection field filters with `_and`, it works.
We also tried doing the same thing via the Admin App, by adding two filters the same way as in the code above, and we also get no results. 
And btw; the request that the Admin App generates for this is also the same as directus-sdk did.

### Project details
Directus Version: 9.0.0-rc.43
Environment: production
OS: Linux 4.19.121-linuxkit
Node: 14.16.0

**Comment by rijkvanzanten** [comment]
In this case, this technically makes sense. The filter statement "ID equals climate control AND ID equals navigation" is invalid.

🤔

**Comment by JH1ller** [comment]
I just updated from rc43 to rc45 and it seems to work now! Sorry for not using the very newest version in the first place.
I will try some stuff and if it all works, I will close the issue.
