### ISSUE TITLE
Permission rules are not working correctly for related records/collections

### ISSUE THREAD

**Issue by BartCRMstrategen** [directus/directus#4485]
1) The issue and what you expected to happen
We expect the permission rules to join in a good way:

```json
{
    "organisatie": {
        "gebruikers": {
            "id": {
                "_eq": "$CURRENT_USER"
            }
        }
    }
}
```

2 tables:
Organisaties on test
Directus_users on Organisaties

2) Exact steps to reproduce this issue
It happends while creating the following:
Collections:
Test: http://i.imgur.com/IrUEvMZ.png (this is where the permission rule is active)
Organisaties: https://i.imgur.com/HBV6KTT.png

Test is connected to Organisaties trough "organisatie"
http://i.imgur.com/XKs0Xxm.png

Directus_users are linked to Organisaties trough "Gebruikers"
http://i.imgur.com/I5UoofT.png
Query that it generates:

```sql
select `test`.`naam`, `test`.`id` from `test` left join `organisation` as `DaY7SwAe` on `test`.`organisatie` = `DaY7SwAe`.`id` where (`uT7luTDb`.`id` = '99fd0221-12f1-48b7-a498-bb65616f4e5f') limit 100
ER_BAD_FIELD_ERROR: Unknown column 'uT7luTDb.id' in 'where clause'
```

it seems like it does not join directus_users.

3) Your environment:
   Directus: v9.0.0-rc.45
   db: MySQL 8
   deployment: npx
   browser: Chrome 87

**Comment by rijkvanzanten** [comment]
![](https://i.imgur.com/I5UoofT.png)

This part doesn't look right to me 🤔 It seems like you're saving the organization ID into `directus_users.id`, which is it's primary key, and not a foreign key back to organization.

**Comment by rijkvanzanten** [comment]
Also potentially fixed in https://github.com/directus/directus/pull/4493

**Comment by BartCRMstrategen** [comment]
http://i.imgur.com/bntI0by.png

After removing and readding the field "gebruikers"

output of graphql:
```js
{
  "errors": [
    {
      "message": "select `code`.`naam`, `code`.`id`, `code`.`organisatie` from `code` left join `organisaties` as `dhkkk` on `code`.`organisatie` = `dhkkk`.`id` where (`ceixb`.`id` = '8') limit 100 - ER_BAD_FIELD_ERROR: Unknown column 'ceixb.id' in 'where clause'",
      "locations": [
        {
          "line": 34,
          "column": 5
        }
      ],
      "path": [
        "items",
        "code"
      ]
    }
  ],
  "data": {
    "items": {
      "code": null
    }
  }
}
```

**Comment by BartCRMstrategen** [comment]
@rijkvanzanten do you have an update yet?

**Comment by benhaynes** [comment]
Automated-Response: [**Unfortunately, we can not provide estimates on features or fixes**](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍 . Or contribute a pull-request... after all, this is OSS!

**Comment by BartCRMstrategen** [comment]
Tried something else and got this filter to work:
```js
{
    "organisatie": {
        "users": {
            "id": "$CURRENT_USER"
        }
    }
}
```
But this returns everything that has a organisatie linked to it

**Comment by BartCRMstrategen** [comment]
After trying to debug it myself, i found out:
There is no support for O2M so far.
Made an if:
const isO2M = relation.many_collection !== parentCollection && relation.one_field === pathParts[0];
to: https://github.com/directus/directus/blob/main/api/src/utils/apply-query.ts#L117
And it will generate 1 more join, but it does not create all joins needed.
I did not find a good way in the Where section of the file.
