### ISSUE TITLE
Sort field for M2M with autogenerated table doesn't work

### ISSUE THREAD

**Issue by iDobrounig** [directus/directus#4488]
When generating an M2M field with a sort field the sorting is not saved in the autogenerated table.
Sometimes it spontaneously works and the order will be saved in the autogenerated table, but the reason is not obvious.

I attached a video:
https://user-images.githubusercontent.com/4222276/110815901-2489ae80-828b-11eb-800a-6ae694b434db.mp4

I'm using version 9.0.0-rc.48 but problem exists for several versions.

I'm using MariaDB 10.3.28, npx and latest Google Chrome

Best Ingo

**Comment by rijkvanzanten** [comment]
> Sometimes it spontaneously works and the order will be saved in the autogenerated table, but the reason is not obvious.

This is gonna make it fairly tricky to reproduce.. Is there any known flow where this happens consistently?

**Comment by DaxCax** [comment]
Same behavior here.

Recreated the collections several times with the same result. Adding a M2M field to a collection (without any other relational fields) and then adding items from related M2M collection. In my case it's a navigation structure. Trying to manually sort those items results in nothing unfortunately. 

Have a "sort" column in my join table. Even tried setting the sort value directly in DB, but seems it doesn't use them when the collection is presented.

Made the join table visible, and in there was no problems manually sorting. Well there another problem arose, when tried to show the corresponding id titles, got the error from here #4481, so I'll have to pace myself at the moment.

9.0.0-rc.48 and earlier
MariaDB 10.3.22
NodeJS 12.21.0

@rijkvanzanten and co. keep up the good work! Thanks

**Comment by iDobrounig** [comment]
We found the issue.
At the beginning of the first RCs the documentation about updating from one to another version was missing one important information about migrating the database after update.
my colleague, who was constantly updating to the latest version,  forgot to run the db migration command "npx directus database migrate:latest" since rc17. after migration everything is back to normal and it seems that this was the only reason for that issue.
Thank you for your commitment - directus is so awesome!

**Comment by rijkvanzanten** [comment]
@DaxCax does that thumbs up mean you had to migrate too, or does the issue still persist?


Thanks for the kind words both! ❤️

**Comment by DaxCax** [comment]
Yes, also missed the migration part. Possibly a bit to trigger happy here.

Only problem that persist is if you add subitems from related collection and start sorting them _before_ saving, it blows up. Meaning error consists of items get the same sort value and then eventually disappears. But that's another issue and haven't tested it thoroughly though.

**Comment by rijkvanzanten** [comment]
Gotcha! I'll close this issue for now then 👍🏻
