### ISSUE TITLE
Mssql - can not update a field

### ISSUE THREAD

**Issue by martijnboland** [directus/directus#4495]
When updating a field with MS Sql Server as db, the following error appears:

![image](https://user-images.githubusercontent.com/167455/110868677-4c980280-82c9-11eb-9e80-cf3281300a49.png)

In the generated SQL, Directus is trying to update the id column, but this is not allowed because it's an identity column (and updating makes no sense anyway, I guess).

**Comment by rijkvanzanten** [comment]
Hmm yeah, field updates are send as the full object of the field meta, including the ID to update, which gets send straight to the DB 🤔

**Comment by andrealmei** [comment]
I have the same issue.
Any news?

**Comment by martijnboland** [comment]
Are there unwanted side-effects with just always removing the primaryKeyField from the update payload just before updating? This solves the problem for me locally.

**Comment by rijkvanzanten** [comment]
@martijnboland Little hesitant to promise that without double checking 😬 Can you confirm you don't have duplicate rows in directus_fields after updating without the ID included in the meta object?

**Comment by martijnboland** [comment]
Nope, no duplicates in directus_fields

**Comment by rijkvanzanten** [comment]
Perfect. On second look in the code, that actually checks out. It pulls the ID from the schema info, not from the submitted values:

https://github.com/directus/directus/blob/40f53fdeb0e702b93d4dce204792c6e66145eaa5/api/src/services/fields.ts#L266-L268

In that case, we're good to go with this approach!

> Are there unwanted side-effects with just always removing the primaryKeyField from the update payload just before updating? This solves the problem for me locally.
