### ISSUE TITLE
Many to many interface field is broken with non admin users

### ISSUE THREAD

**Issue by MarcioBarrientos** [directus/directus#4497]
I get this message when I try to use the many to many interface with  "app access" only user and full permissions, with "admin access" user this interface works perfectly.
"the relationship hasn't been configured correctly"

In the console I get this warning:
TypeError: Cannot read property 'many_collection' of undefined

---

### Project details
Directus Version: 9.0.0-rc.49
Environment: production
OS: Linux 4.9.0-8-amd64
Node: 12.18.0

**Comment by rijkvanzanten** [comment]
Does this user have read access to the junction collection as well?

**Comment by MarcioBarrientos** [comment]
Sorry, I tried to set all CRUD permissions to all collections and didn't work, but then I deleted the collection (the junction collection too) and add again the field and relation, now is working fine

**Comment by Feuerhamster** [comment]
Same issue here.
My user has the permissions but the collections have infinite loading.
The browser's console throws: `TypeError: Cannot read property 'many_collection' of undefined`

**Directus version:** 9.0.0-rc.51
**Database type:** SQLite
**Node version:** 14.15.3

**Comment by Feuerhamster** [comment]
I think I found the problem and how to fix it:
You have to give the user the permissions on the collection that joins the many2many relation.
