### ISSUE TITLE
Custom display for M2M (or other array types) not being available

### ISSUE THREAD

**Issue by Piteraguayo** [directus/directus#4500]
The origin of the the problem:
with the new upgrade of Directus, the M2M fields, when listed are showing the items count and not the values selected on the display on the data model. So, I decided to create a custom display to show the values and not the count. 
Here a screenshot of the list showing the count:
![M2M_list_count](https://user-images.githubusercontent.com/5360439/110942621-56a61980-833a-11eb-90a7-0742ea04a653.png)

1) The issue and what you expected to happen
    I create the custom display with the following values on index.js:
 `id: 'ea.custom.display.arrayValues',
	name: 'EA customised array display',
	description: 'Display to show values of array',
	icon: 'box',
	component: ArrayValuesDisplay,
	types: ['string','CSV','JSON','M2M'],`
I run `npx rollup -c` 
I expect to have this display available on the displays options when I create a field M2M

2) Exact steps to reproduce this issue
    - Create the display
    - Go to a collection
    - Create a M2M field on it
    - On the displays options, look for the customised display (does not appear)

3) Your environment:
    Directus Vesion: 9.0.0-rc.49
    DBMS: MYSQL
    Deployent: npx
    Browser: Chrome
4) Any other relevant information we might need to reproduce this issue
    No other relevent information

**Comment by rijkvanzanten** [comment]
I'd swear I answered this this morning, but maybe it got lost in the GH server outage earlier..

---

You can add the `group` where this display is shown for in the index.js object 👍🏻

**Comment by Piteraguayo** [comment]
Thank you @rijkvanzanten 
Unfortunately, this is not working for me. This is my index now:
```
import ArrayValuesDisplay from './display.vue';

export default {
	id: 'ea.custom.display.arrayValues',
	name: 'EA customised array display',
	description: 'Display to show values of array',
	icon: 'box',
	component: ArrayValuesDisplay,
	types: ['string'],
	groups: ['m2m','m2o','o2m']
};
```
But in the display options my custom display do not appear:
![Display_options](https://user-images.githubusercontent.com/5360439/111014783-b685da00-83a5-11eb-9a14-cd3723f6bada.png)

It should be expected to have my custom display below the 2 default displays options as a new option?
Is there something I'm missing? 
Thank you again

**Comment by rijkvanzanten** [comment]
Is the bundled dist folder of this display in the right location in your extensions path? Eg `./extensions/displays/<my-display>/index.js`

**Comment by Piteraguayo** [comment]
Hi @rijkvanzanten yes I did

**Comment by Piteraguayo** [comment]
I changed the "types" on index.js with the following:
`types: ['alias', 'string', 'uuid', 'integer', 'bigInteger', 'json'],`
The difference with the previous is that I had only "string" as type. Don't know the reason.
Now I see the option as display when I create the field but on the lists, the content of the Vue file is not appearing.
Maybe because it takes the display as "alias"?

**Comment by Piteraguayo** [comment]
FOUND the problem: on the index.js, I was referencing the Vue with a key "component" but I found on the docs that it has to be "handler". My mistake. 

Thank you
