### ISSUE TITLE
Can't reorder custom fields in system collections

### ISSUE THREAD

**Issue by ghost** [directus/directus#4517]
You can't reorder system fields in any system collection - that's a separate issue.

This issue is about reordering custom fields created in a system collection. If you create custom fields, then reodrder them (just by drag-drop in the web UI), this breaks something where they interfere with the order of the system fields.

I can reproduce this in directus_users, where adding new fields then resorting them puts them at the top of the form.

Project Details:
Directus Version: 9.0.0-rc.50
Database: Postgresql 9.6
Node: 14.15.4
OS: Windows 10

**Comment by danieljwestman** [comment]
The quick fix is to manually set the `sort` values in the database.

**Comment by xl-1200** [comment]
Yeah that's been my hack to fix it so far

**Comment by Nitwel** [comment]
I tried to reproduce this and sorting newly added fields to system collections worked fine for me.
Please provide exact steps on how to do this.

**Comment by rijkvanzanten** [comment]
Seeing that the OPs account was deleted, I don't think we'll get a response 👀
