### ISSUE TITLE
DigitalOcean Space S3 File Storage ->  Directus 9.0.0-rc.50 

### ISSUE THREAD

**Issue by hermesalvesbr** [directus/directus#4529]
Hi, i'm using the  Directus 9.0.0-rc.50 with psql. 

```
{
  "errors": [
    {
      "message": "E_INVALID_CONFIG: Make sure to define driver for digitalocean disk",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

```
![Captura de Tela 2021-03-13 às 14 58 47](https://user-images.githubusercontent.com/379850/111039448-e5836680-840c-11eb-8ec9-f0628e3a99b4.png)
![Captura de Tela 2021-03-13 às 14 57 57](https://user-images.githubusercontent.com/379850/111039456-ecaa7480-840c-11eb-9f7d-122e85eebe78.png)

Maybe storage location or driver was wrong, or it's a bug.

**Comment by rijkvanzanten** [comment]
You called your storage location "digitalocean", but configured the env vars for a location called "cloud". Either use "cloud" for the storage location, or change the env vars to be STORAGE_DIGITALOCEAN_XX
