### ISSUE TITLE
Can't create or update activity comment

### ISSUE THREAD

**Issue by dorb4n** [directus/directus#4535]
Moin,

I'm using the Directus Javascript SDK in Nuxtjs. I'm getting an 404 from Directus when i try to create an activity comment (directus.activity.comments.create). The SDK tries to call ```/activity/comments``` instead of ```/activity/comment```.

Direcuts 9.0.0 rc.50
MariaDB
Safari, Firefox

**Comment by rijkvanzanten** [comment]
@WoLfulus could you make sure this is corrected in #4510? 🙂

**Comment by WoLfulus** [comment]
Should do!
