### ISSUE TITLE
Custom display M2M field: values from relationship

### ISSUE THREAD

**Issue by Piteraguayo** [directus/directus#4537]
Hi, I have created a basic custom display that I want to use for M2M fields. The value I receive on the display is the id of the junction collection, but I want to get the value of a specific field of the related collection,

1) The issue and what I expect to happen
**The relationship of collections** I have is a table "news" and a table "news_categories". On the table "news", I have a field M2M "categories" that has a junction collection "news_news_categories"
On the custom display, I receive the value of the field "id" of the junction collection. I would like to receive the field "name" of the table "news_categories"

2) Exact steps to reproduce this issue
- Create a simple custom display that display the value received. 
- On the M2M field (previously having created the relationship), assign the custom display
- On the list of the main collection (in my case "news") you will see an array with the id's selected where I would like to see the names of the selected cateogories (in my case)

3) My environment:
    Directus version:  9.0.0-rc49
    DBMS: MYSQL
    Deployment: npx
    Browser: Chrome
4) Any other relevant information you might need to reproduce this issue
Maybe the solution is to have "options" on the custom display to select the fields I want to get (as for the default "Related Values" display) but I don't find on the official DOCS an example to do this (add options to the custom display).

Here some screenshots to help understanding

![Display_data_model](https://user-images.githubusercontent.com/5360439/111142779-5b124280-8585-11eb-8b50-868ef9fd4379.png)

![list_result](https://user-images.githubusercontent.com/5360439/111142795-5ea5c980-8585-11eb-9f7d-10cf55218092.png)

**Comment by rijkvanzanten** [comment]
You can provide [an array of fields](https://github.com/directus/directus/blob/main/app/src/displays/user/index.ts#L56) or a [function that returns an array of fields](https://github.com/directus/directus/blob/main/app/src/displays/related-values/index.ts#L23) to request more data. 

(Yes, this is very under-documented still.. )

**Comment by rijkvanzanten** [comment]
Ref https://github.com/directus/directus/issues/4541

**Comment by Piteraguayo** [comment]
Thank you @rijkvanzanten I trtied it and was the solution.

**Comment by Piteraguayo** [comment]
Hi, even if this issue is closed, I have a related question. I want to access the related collection from the View display code but I can not import the following:
`import getRelatedCollection from '@/utils/get-related-collection';`

 as it's not available. Directus is on the pacakege with the following:
`"vue": "^2.6.12",`

But I guess that what is available is only the API. How can I access the APP dependencies?
Thank you

**Comment by rijkvanzanten** [comment]
@Piteraguayo That internal util isn't exposed to extensions (yet). You could either duplicate that function (as you do have access to the stores used), or you can open a PR to include that (and other useful) utils into the `system` provided stuff 🙂

**Comment by Piteraguayo** [comment]
Thank you @rijkvanzanten I will do the PR but I want to try to replicate the funcion. Can you give me an example about how to access the stores?

**Comment by rijkvanzanten** [comment]
Yeah! Directus uses Vue's provide/inject system to provide the internal stores under the `system` key:

https://github.com/directus/directus/blob/45a9f2a06cc1ebf55581a79d2f64b8dcbe576655/app/src/app.vue#L108-L116

That means that you can use something like:

```js
export default {
  inject: ['system'],
  created() {
    const fieldsStore = this.system.useFieldsStore();
    const fields = fieldsStore.getFieldsForCollection('articles');
  }
}
```

**Comment by Piteraguayo** [comment]
Thank you @rijkvanzanten !!!
