### ISSUE TITLE
Table Resize Handle Mobile

### ISSUE THREAD

**Issue by mehmetuken** [directus/directus#4542]
Version: Latest

Table resize handle don't control on mobile devices.

**Comment by rijkvanzanten** [comment]
This part is using `mousedown` in particular:

https://github.com/directus/directus/blob/37b2ec8a2742f1642fcd9d3427c539fbd3459df8/app/src/components/v-table/table-header/table-header.vue#L37

We should use `pointerdown` (and `pointermove` etc) instead
