### ISSUE TITLE
Order by relational column cause INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by iksent** [directus/directus#4543]
Here is a process video: https://yadi.sk/i/4O6GBe6KzySYxg

1. Add auto-generated "Translations"
2. Show "Translations" column at the table
3. Order table by this column (ordering works at Client side)
4. Refresh page and get error:

```
[INTERNAL_SERVER_ERROR] select `article`.`date_created`, `article`.`date_updated`, `article`.`status`, `article`.`id`, `article`.`image` from `article` where not `article`.`status` = 'archived' order by `article`.`translations` asc limit 25 - ER_BAD_FIELD_ERROR: Unknown column 'article.translations' in 'order clause'
```

MariaDB dump: [dump-2.sql.zip](https://github.com/directus/directus/files/6142890/dump-2.sql.zip)

**UPD: You can order by any column with relation type - this is not connected with Translations.**

This bug is really annoying, because you can accidentally click on column header and then it will be required to reset table settings... And you'll need to configure all the settings again.

### Project details
Directus Version: 9.0.0-rc.50
Environment: production
OS: Linux 5.4.0-65-generic
Node: 14.16.0

**Comment by iksent** [comment]
Hello again!
I've just upgrade directus to the latest v53 and:
1) Now I can't sort by translations = no error
2) But I can still sort by many to many = getting the same error:

![2021-03-30_22-37-56](https://user-images.githubusercontent.com/32956521/113031858-9f6a2900-91a8-11eb-8792-134f35c4d011.jpg)


```
{
  "errors": [
    {
      "message": "select `article`.`id`, `article`.`status`, `article`.`is_pinned`, `article`.`date_updated`, `article`.`date_created`, `article`.`image`, `article`.`user_updated`, `article`.`user_created` from `article` order by `article`.`categories` asc limit 25 - ER_BAD_FIELD_ERROR: Unknown column 'article.categories' in 'order clause'",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

**Comment by rijkvanzanten** [comment]
Back to the drawing board @Nitwel 😄

**Comment by Nitwel** [comment]
Oh, I thought there was a m2m in that list bug I guess not. We just have to add it to the list too. https://github.com/directus/directus/blob/a5eadd1ec44a17d1472c9bd70c52f1b37bca1b14/app/src/layouts/tabular/tabular.vue#L467
