### ISSUE TITLE
How do pass user id to reference table in POST METHOD

### ISSUE THREAD

**Issue by groovyrb** [directus/directus#4545]
I am creating a new user from API and At the same time, I need to create data of the user to another table you can find my JSON below! here $new_user_created_id I need to pass which is created recently so How can I get or pass the last inserted id in API so my mapping or relation does not break? Need #help or how to achieve this?

```json
{
    "status": "active",
    "first_name": "keep",
    "last_name": "Smiling",
    "email": "keepsmiling@gmail.com",
    "password": "jhdjshfjsfbsjb",
    "role": "3",
    "title": "Dreemnj",
    "user_data": {
        "phone_number": "2566522560",
        "users": **$new_user_created_id**
    }
}
```

**Comment by rijkvanzanten** [comment]
There's no way to do that currently. You could however go "the other way" by inserting into the `user_data` table, and do the following:

```json
POST /items/user_data

{
  "phone_number": "2566522560",
  "user": {
      "status": "active",
      "first_name": "keep",
      "last_name": "Smiling",
      "email": "keepsmiling@gmail.com",
      "password": "jhdjshfjsfbsjb",
      "role": "3",
      "title": "Dreemnj"
  }
}
```

(I'm making some assumptions about your schema here, not sure if `user` exists / is an m2o, not sure if `user_data` is the name of the collection)
