### ISSUE TITLE
project_name: value required

### ISSUE THREAD

**Issue by emrahnazif** [directus/directus#4547]
If you have a collection named "projects", you are not able to save items inside it. I suspect there is a conflict with the directus "project_name".
I can work around this easily by changing the collection name yet I would like to inform you guys. 

- clean install v9 + mysql
- create a collection named "projects".
- add any field to "projects" collection.
- try to create a new item in the "projects" collection.
- Error: project_name: value required

![Screenshot 2021-03-15 at 22 05 35](https://user-images.githubusercontent.com/33692017/111221808-45c80300-85db-11eb-824a-e9398c6fab10.png)

A+

---

### Project details
Directus Version: 9.0.0-rc.50
Environment: production
OS: macOS Big Sur (11)
Node: 14.16.0

**Comment by rijkvanzanten** [comment]
There is no reference in the api to anything called `projects`, so I'd be surprised if the name of the collection is the culprit 🤔 Are you sure there isn't a hidden field in your collection called `project_name` that has required enabled?

**Comment by emrahnazif** [comment]
@rijkvanzanten yes, I am sure. There is no hidden fields in the collection. I thought like you at first and made 5-6 clean installs with fresh dbs to confirm it and test other possible bugs, nothing else found. 

![Screenshot 2021-03-15 at 22 43 52](https://user-images.githubusercontent.com/33692017/111225837-92faa380-85e0-11eb-9a01-cb53c2ac78b7.png)

**Comment by Silbad** [comment]
Hello,
I have a similar issue with the rc51
![image](https://user-images.githubusercontent.com/31576982/111441090-42319a80-8707-11eb-8f8a-3bde61751b96.png)

**Comment by Silbad** [comment]
mm not the same pb... sorry

**Comment by rijkvanzanten** [comment]
@emrahnazif could you try updating to rc.51? There was a small issue in mysql where it sometimes would read columns out of the wrong database. Curious to see if that is what caused this

**Comment by emrahnazif** [comment]
> @emrahnazif could you try updating to rc.51? There was a small issue in mysql where it sometimes would read columns out of the wrong database. Curious to see if that is what caused this

I confirm with rc.51, it works without any problem. That small issue was causing the problem.
