### ISSUE TITLE
Unable to Provide User Defined Sort for Relations.

### ISSUE THREAD

**Issue by loganaaaflag** [directus/directus#4552]
## Overview

After upgrading to rc.50, we're experiencing an issue with user defined sorting on M2M/O2M relation fields.
We're unable to set field that specifies sorting, nor the sort order of the items in the field. I believe this is a regression from our prior version, rc.30, but I cannot confirm because I'm unable to pin our install to the old version.

If I can provide any more info or help, please just let me know! Thank you.

## Replication

1. Set up a new collection and a `files` field on it (or any M2M/O2M)
2. Define a sort column on the junction table (integer type)
3. Edit the `files` field created in step 1 to use sorting stored in the column created in step 2

## Expected Functionality

We should be able to set the sort field, populate the related files list, then use the drag/drop UI to sort the entries.

## Actual Functionality

We're unable to specify/update the sort field to use with the M2M field, and the drag and drop UI has no effect on the sorted order. Examples below

Setting sort field: 

![Peek 2021-03-15 14-11](https://user-images.githubusercontent.com/55156743/111229938-08944e80-85a4-11eb-9302-51cd43cfd203.gif)

Applying user sort:

![Peek 2021-03-15 15-06](https://user-images.githubusercontent.com/55156743/111228387-5fe4ef80-85a1-11eb-90e4-57df35ca18fc.gif)

## Project Details

- Directus Version: 9.0.0-rc.50
- Database: Postgresql  13.1
- Node: 14.15.4
- OS: Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1036-azure x86_64)

## Further Notes

It appears the `directus_field` entry in our SQL table does include the `"sortField": "sort"` entry in the corresponding `options` column for fields created **before** we upgraded, but those created after do not.

Manually setting the `sort` values in our junction table seems to have no effect.

Slightly more concerning, if you try to type out the field name, the system warns you it's about to create an entirely new junction table, which if saved, results in a miss-configured field requiring SQL to resolve. See below

![image](https://user-images.githubusercontent.com/55156743/111230120-4f824400-85a4-11eb-8013-7d017a1a5daa.png)

Possibly related to #4517 #4380

Again, if there's anything further I can provide, let me know! Thank you!

**Comment by rijkvanzanten** [comment]
Did you run the database migrate command after updating your directus instance? https://docs.directus.io/reference/command-line-interface/#upgrade-the-database

**Comment by rijkvanzanten** [comment]
Just to confirm, does the same effect happen on O2Ms instead of M2Ms? There might be something wrong with that field picker on just M2M 🤔

**Comment by loganaaaflag** [comment]
Applying the DB migration seems to have resolved the issue - not sure how I missed that in the docs. Will definitely keep that in mind moving forward.

Really appreciate the assistance here, apologies for the time waste/mini heart attack :sweat_smile: 

Thanks for being so responsive!

**Comment by rijkvanzanten** [comment]
No problem! Glad to hear there wasn't a bigger issue in the platform itself :)
