### ISSUE TITLE
Assets quality parameter

### ISSUE THREAD

**Issue by aleksejssaburovs92** [directus/directus#4557]
Upload image to admin panel (amazon s3)

Try to load image with quality param
http://localhost:8055/assets/8a2e7f70-0900-49a4-b26a-513cd93b9ca4?fit=cover&width=300&quality=20

Actual result:
Quality is the same as loading image without parameter
http://localhost:8055/assets/8a2e7f70-0900-49a4-b26a-513cd93b9ca4?fit=cover&width=300

Expected result:
Quality is compressed, also size is changed(compressed)

Version: v9.0.0-rc.50
Installation and running: CLI (npx)
DB: mysql8
File storage: AWS s3

<img width="1708" alt="Screenshot 2021-03-16 at 15 58 20" src="https://user-images.githubusercontent.com/12848012/111321643-d00e7680-8670-11eb-9dc2-249411803fc4.png">
<img width="1745" alt="Screenshot 2021-03-16 at 15 58 26" src="https://user-images.githubusercontent.com/12848012/111321654-d1d83a00-8670-11eb-91b9-b88ef9d99f43.png">

**Comment by workatease** [comment]
should the quality be consider as a dynamic value as it is not a thumbnail resize option.

https://github.com/directus/directus/blob/dd6f4c07d3679640cba36ae727438bb6ebda4417/api/src/services/assets.ts#L48

and Sharp library also considers quality as a output option
https://sharp.pixelplumbing.com/api-output#toformat

what do you think is the better option 
1) save the file with quality as a resize value.
2) or return the value in runtime.

both options has its own pros and cons

https://github.com/directus/directus/blob/dd6f4c07d3679640cba36ae727438bb6ebda4417/api/src/services/assets.ts#L53-L72

**Comment by rijkvanzanten** [comment]
> save the file with quality as a resize value.

I think this is the preferred direction right now. We should handle it just like we're doing with width/height 👍🏻 

The only thing we have to check is supported file types. Compression quality exists for JPEG, but I'm not sure what it should do for png/tiff/svg/etc

**Comment by workatease** [comment]
> > save the file with quality as a resize value.
> 
> I think this is the preferred direction right now. We should handle it just like we're doing with width/height 👍🏻 
> 
> The only thing we have to check is supported file types. Compression quality exists for JPEG, but I'm not sure what it should do for png/tiff/svg/etc

I think we it support resize thumbnail for three types jpeg,png,webp and sharp supports quality for all these types ... So I think we can support
https://github.com/directus/directus/blob/dd6f4c07d3679640cba36ae727438bb6ebda4417/api/src/services/assets.ts#L45

I would also suggest that we need to add the support types in the asset docs
