### ISSUE TITLE
Better error when trying to Invite an existing user

### ISSUE THREAD

**Issue by TheAzack9** [directus/directus#4568]
1) The issue and what you expected to happen
    When using the "Invite Users" button and using an existing email, then you get a "INTERNAL_SERVER_ERROR" where it fails to insert the user instead of a better warning. It would be nice to have a more descriptive error for non-technical users :)

![image](https://user-images.githubusercontent.com/2140448/111432393-45278d80-86fd-11eb-8bd8-5ea12f396f9e.png)

2) Exact steps to reproduce this issue
    Go to Users directory
    Click the "Invite Users"
    Add an email that already exists as an account

3) Your environment:
Directus 9.0.0 rc 45
MySQL 8
Docker
Chrome 89

4) Any other relevant information we might need to reproduce this issue
I am using azure blob storage, but doubt this is the issue here :)

**Comment by rijkvanzanten** [comment]
Unique constraints (and their proper errors) have been implemented in rc.46 (just one update away!!)

**Comment by TheAzack9** [comment]
Oof, so close :p Should've checked the commits. ;)
