### ISSUE TITLE
Signing in with SSO without an account

### ISSUE THREAD

**Issue by TheAzack9** [directus/directus#4570]
And the last one :)

1) The issue and what you expected to happen
    The _ _ does _ _ when _ _ while it should _ _
    When signing in with SSO without an account in Directus does one just get redirected to a page with a json error. 

![image](https://user-images.githubusercontent.com/2140448/111436046-d13bb400-8701-11eb-92ba-b7c4179f11ab.png)

I haven't researched this too in depth, but i think it is an uncaught exception from this function: https://github.com/directus/directus/blob/76b31eda78d53f7866040f897376fa514e7b1202/api/src/controllers/auth.ts#L261-L263

I would expect to be redirected back and perhaps see something like "Login failed" or "The user does not exist" error on the login page.

![image](https://user-images.githubusercontent.com/2140448/111436272-12cc5f00-8702-11eb-9423-9bbb8395459f.png)

2) Exact steps to reproduce this issue
    Set up a SSO provider
    Try to sign into a user that doesn't exist in the Directus users table. (I just changed the email of my user to test this :) )
    Sign out and Sign in with the SSO provider
    You should see this error on the callback

3) Your environment:
Directus 9.0.0 rc 45
MySQL 8
Docker
Chrome 89

4) Any other relevant information we might need to reproduce this issue
The SSO provider is Google with OAuth 2.0 :)

**Comment by TheSunNeverSetsOnDream** [comment]
What should I do for reproduce this issue? And ,ect

**Comment by workatease** [comment]
@rijkvanzanten 
what do you think is the right way to handle this to the redirect flow as I am stuck with use case.

**Comment by workatease** [comment]
> What should I do for reproduce this issue? And ,ect

you can reproduce it 

- by configuring [SSO](https://docs.directus.io/guides/api-config/#oauth-single-sign-on-sso-openid) 
- in the [environment variables](https://docs.directus.io/reference/environment-variables/#oauth)
- and login to the directus admin site with a SSO email which is not register with directus

**Comment by workatease** [comment]
`	let authResponse: { accessToken: any; refreshToken: any; expires: any; id?: any };
		try {
			authResponse = await authenticationService.authenticate({
				email,
			});
		} catch (error) {
			if (redirect) {
				const query = QueryString.stringify({ reason: 'INVALID_USER' });
				return res.redirect(redirect + '?' + query);
			}
			throw error;
		}
		const { accessToken, refreshToken, expires } = authResponse;
		if (redirect) {
			res.cookie('directus_refresh_token', refreshToken, {
				httpOnly: true,
				domain: env.REFRESH_TOKEN_COOKIE_DOMAIN,
				maxAge: ms(env.REFRESH_TOKEN_TTL as string),
				secure: env.REFRESH_TOKEN_COOKIE_SECURE ?? false,
				sameSite: (env.REFRESH_TOKEN_COOKIE_SAME_SITE as 'lax' | 'strict' | 'none') || 'strict',
			});`

will this block be able to handle this error

**Comment by rijkvanzanten** [comment]
> what do you think is the right way to handle this to the redirect flow as I am stuck with use case.

Ideally, it redirects you to the redirect URL regardless, and puts the error in a query param so it can be handled on the front-end. The snippet you sent above seems like the right direction to me, though it's not a given that _every_ error is an "INVALID_USER" error, so we'll have to be a little careful with that

**Comment by workatease** [comment]
> > what do you think is the right way to handle this to the redirect flow as I am stuck with use case.
> 
> Ideally, it redirects you to the redirect URL regardless, and puts the error in a query param so it can be handled on the front-end. The snippet you sent above seems like the right direction to me, though it's not a given that _every_ error is an "INVALID_USER" error, so we'll have to be a little careful with that

so it is better to throw a generic exception ? 
As I see  that we can throw these types of error 
InvalidCredentialsException
InvalidOTPException

so what do you think we can throw instead of INVALID_USER

**Comment by rijkvanzanten** [comment]
Well, ideally we can extract that from `error`? And then either return invalid_user or a generic error to the front-end in the query param. We should be able to do something like `if (error instanceOf InvalidCredentialsException)`

**Comment by workatease** [comment]
> Well, ideally we can extract that from `error`? And then either return invalid_user or a generic error to the front-end in the query param. We should be able to do something like `if (error instanceOf InvalidCredentialsException)`

yes. let me submit a PR with the above suggestion we can groom the error message in the review

**Comment by jeet0007** [comment]
I had the same issue i fixed by updating my refresh token settings this is for openid
```
KEY="some-key"
SECRET="some-secret"
ENCRYPTION_ALGORITHM="aes-256-cbc"
ENCRYPTION_SALT="salt"

ACCESS_TOKEN_TTL="15m"
REFRESH_TOKEN_TTL="7d"
REFRESH_TOKEN_COOKIE_SECURE=false
REFRESH_TOKEN_COOKIE_SAME_SITE="lax"
```
