### ISSUE TITLE
Delesect button is not displayed on m2m items list

### ISSUE THREAD

**Issue by chernandezweb** [directus/directus#4572]
Hi, 

I upgraded to rc 51 and I'm using multiple m2m collections. 

The issue is that the deselect button on m2m items is not available when it's on the main content page, but it's available when the items are in a v-drawer.

**Comment by seanmars** [comment]
I upgrade to rc.53, but still got this issue.

**Comment by seanmars** [comment]
And I found this issue just happended when first time enter the item and try to edit it. If I refresh(press F5) the page the button will appeared.

**Comment by seanmars** [comment]
@rijkvanzanten Could check this issue, please?

**Comment by rijkvanzanten** [comment]
#4093 removed the tables for relational interfaces completely, so this should no longer be an issue
