### ISSUE TITLE
HEAD request to /assets returns less headers than GET request

### ISSUE THREAD

**Issue by HCl-not-HCi** [directus/directus#4578]
When making a HEAD request to the `/assets` endpoint, some headers are missing which are returned in case of a GET request (in my case I especially miss the `Content-Type` because the app I'm using infers the file type from the HEAD request or file extension).

But the response headers from a HEAD request should be identical to the headers from a GET request.

Response from a HEAD request to `/assets/<id>?access_token=<access token>`:
```
X-Powered-By: Directus
Vary: Origin
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Content-Range
Accept-Ranges: bytes
Content-Length: 587667
Date: Wed, 17 Mar 2021 21:53:42 GMT
Connection: close
```

Response from a GET request to `/assets/<id>?access_token=<access token>` (+ = headers missing in HEAD):
```
X-Powered-By: Directus
Vary: Origin
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Content-Range
+ Content-Type: image/jpeg
Accept-Ranges: bytes
+ Cache-Control: private, max-age=1800000
Content-Length: 587667
Date: Wed, 17 Mar 2021 22:20:21 GMT
Connection: close
```

I think, the HEAD request should at least return the `Content-Type` or what do you think?

**Comment by rijkvanzanten** [comment]
Yes I agree. We're quitting early on head requests as not to download the full file for HEAD requests, but we're quitting just a tad bit too early here:

https://github.com/directus/directus/blob/d65469c974fefdfb9c766ff9213fc39dbe144cc0/api/src/controllers/assets.ts#L124-L130

**Comment by HCl-not-HCi** [comment]
Thank you, that was fast ❤️
