### ISSUE TITLE
no latest Tag availablle

### ISSUE THREAD

**Issue by jurrack** [directus/directus#4583]
Hi, 

when trying to pull your current image it will fail:

```docker pull directus/directus ```

Its fails with:
``` 
Using default tag: latest
Error response from daemon: manifest for directus/directus:latest not found: manifest unknown: manifest unknown 
```

Seems like the latest tag is not set. When using a fixed version tag I works fine.

**Comment by benhaynes** [comment]
@WoLfulus — do we have the `latest` tag yet? Any ETA on this?

**Comment by rijkvanzanten** [comment]
Duplicate of https://github.com/directus/directus/issues/3661
