### ISSUE TITLE
CSV export - filtered items still shows

### ISSUE THREAD

**Issue by nordcart** [directus/directus#4588]
Exporting to CSV from a bookmark (presents) includes all data from a collection. 

The CSV does not include only the filtered items, it includes everything with the column-settings from the bookmark

9.0.0 RC50

**Comment by Nitwel** [comment]
I just tested creating a bookmark / having something in the search bar and it properly only exported only the filtered items.
Could you provide more details on how you got this bug?

**Comment by nordcart** [comment]
The export works if I have something in the searchbar. 
But if something is filtered through the menu on the right. Everything from the collection is exported, not only what is on the screen.

![image](https://user-images.githubusercontent.com/12813484/112993457-e7ba2480-9171-11eb-82bf-25046d03f20b.png)

**Comment by JKnorr91** [comment]
I have the same Problem with the current 9.0.0 RC61 (and before). Filtered Export is not Possible. The Filters are always ignored. The Export ist always limited to 100 Elements. Only Search is working. It does not matter whether the filter is applied to a relation or directly to the data record. The table in Directus shows the filtered values, but the export always remains the same. 

Tried it with different Node versions (12 and 14).
Tested on a local System with MySQL 5 and a production System with MySQL 8.

**Comment by atticoding** [comment]
Same issue here.

directus:v9.0.0-rc.61
postgres:13.2
redis:6.2
