### ISSUE TITLE
M2A fields cleared when M2A field of item in same collection was changed

### ISSUE THREAD

**Issue by ps73** [directus/directus#4589]
The M2A field of a collection is cleared each time another M2A field of a item of the same collection is changed. I'm expected that other items won't be changed. 

Exact steps to reproduce this issue
https://user-images.githubusercontent.com/17291660/111606490-8ee4a680-87d7-11eb-84f5-510ad25b953e.mp4

Environment:
    What version of Directus you are using: 9.0.0-rc-51
    Which DBMS are you using: MariaDB 10.3.25
    Which deployment are you using: npx

**Comment by Nitwel** [comment]
Could you provide exact steps on how to recreate this?
Is this still a but in the lasted version / is your DB up to date?

**Comment by ps73** [comment]
I did not checked the newest version, but I could not reproduce this issue yet.

**Comment by rijkvanzanten** [comment]
We'll close this for now then 👍🏻 

If it pops up again and we have a way to reproduce, we can reopen
