### ISSUE TITLE
CORS_ORIGIN with a CSV of domains does not work

### ISSUE THREAD

**Issue by sebj54** [directus/directus#4593]
Hi guys, I am actually getting trouble with correct values to use with CORS settings. I assumed I needed to let everything with default values and it would work.

I am using latest API and JS SDK, but I noticed the docs are wrong about `CORS_ORIGIN`:

> Value for the Access-Control-Allow-Origin header. Use true to match the Origin header, or provide a domain or a CSV of domains for specific access

I used a value like this one: `localhost,example.com,example.onrender.com`.

The fact is nothing is done with this value, it is transferred as is in the `access-control-allow-origin` header value.

I think it should be splitted and tested against the current Origin to determine which value to set.

**Comment by rijkvanzanten** [comment]
Heya! Can you try telling it it's an array by using `array:localhost,example.com,example.onrender.com` as the value?

**Comment by sebj54** [comment]
I just tried it locally, with the value you suggested and it works, but I tried to remove `localhost` from the array and the header's value is still `true`.

Is it the expected behavior? I expected to see a CORS error here:

![image](https://user-images.githubusercontent.com/5880435/111754496-5a84ef00-8898-11eb-89f7-e6e1222324f2.png)

**Comment by rijkvanzanten** [comment]
I'm not sure actually! We pass that config on to express' cors middleware:

https://github.com/directus/directus/blob/3c6688ee9ea42cb4f3187e2be3c49b8b4cb29015/api/src/middleware/cors.ts#L9-L14

so we'll have to do some more research over on https://expressjs.com/en/resources/middleware/cors.html to figure out exactly what's what 🙂

**Comment by rijkvanzanten** [comment]
> Is it the expected behavior? I expected to see a CORS error here:

Another thing to keep in mind is that some browsers treat `localhost` differently in the context of CORS 🤔

**Comment by sebj54** [comment]
I don't think Firefox treat localhost differently, I have seen too many CORS errors in my console 😂 

I just checked Express docs and what Directus do here seems to be correct. I hope it's not a PEBKAC and it will not waste your time.

By the way, there are two things which can improve the docs (and maybe would have avoided the creation of this issue):

- In this section: https://docs.directus.io/reference/environment-variables/#type-casting-and-nesting, the `STORAGE_LOCATIONS` example does not use the `array:` syntax
- The CORS section (https://docs.directus.io/reference/environment-variables/#cors) should mention that `CORS_ORIGIN` should never be set to `*` if used with DIrectus SDK (because of the `withCredentials` setting on the XHR, more info: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials)

**Comment by rijkvanzanten** [comment]
It seems to work as expected 🤔 We're passing it straight on to Express as is, so any other issues that might happen in there should be directed straight there.

One thing of note:

When trying this out locally, I noticed something interesting. It doesn't work when you omit the `Origin` header. When I add it, the header gets set correctly as long as my Origin header matches one of the provided values in the env var. 

![CleanShot 2021-05-04 at 20 22 31@2x](https://user-images.githubusercontent.com/9141017/117084943-7ba18200-ad16-11eb-8e69-1c8a7a0581c6.png)

Might be worth checking what the Origin header is that's sent by the browser 🤔 Maybe it has to be `http://localhost:8055` instead of just `localhost`?

**Comment by hckhanh** [comment]
Can I work on CORS origin with regex? @rijkvanzanten

**Comment by joselcvarela** [comment]
Hey @hckhanh let's keep the discussion on your opened issue:
https://github.com/directus/directus/issues/8522
