### ISSUE TITLE
Mssql - Unique index is not read from database

### ISSUE THREAD

**Issue by martijnboland** [directus/directus#4594]
When adding a unique field to a collection with MS SQL Server as database, the unique index is created properly, but the not read (in the admin, the unique checkbox is unchecked, even though the unique constraint exists). 

This results in an error when updating the field because the unique index is not dropped before altering the table.

**Comment by rijkvanzanten** [comment]
Ref https://github.com/knex/knex-schema-inspector/blob/master/lib/dialects/mssql.ts#L182

**Comment by prikr** [comment]
It's also when you're trying to POST a new article (or whatever) to the database and the primary field already exists. The output is 400 error.

```

"error"
: 
{
 
 
 
 
 
 
 
 
 
 
"name"
: 
"StatusCodeError"
,
 
 
 
 
 
 
 
 
 
 
"statusCode"
: 
400
,
 
 
 
 
 
 
 
 
 
 
"message"
: 
"400 - {\"errors\":[{\"message\":\"Field \\\"undefined\\\" has to be unique.\",\"extensions\":{\"code\":\"RECORD_NOT_UNIQUE\",\"collection\":\"PRIMARY\",\"invalid\":\"5247784\"}}]}"
,
 
 
-
 
 
 
 
 
 
 
"error"
: 
{
 
 
-
 
 
 
 
 
 
 
 
 
"errors"
: 
[
 
 
-
 
 
 
 
 
 
 
 
 
 
 
{
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
"message"
: 
"Field \"undefined\" has to be unique."
,
 
 
-
 
 
 
 
 
 
 
 
 
 
 
 
 
"extensions"
: 
{
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
"code"
: 
"RECORD_NOT_UNIQUE"
,
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
"collection"
: 
"PRIMARY"
,
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
"invalid"
: 
"5247784"
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
}
 
 
 
 
 
 
 
 
 
 
 
 
 
 
}
 
 
 
 
 
 
 
 
 
 
 
 
]
 
 
 
 
 
 
 
 
 
 
}
,
 ````

**Comment by rijkvanzanten** [comment]
@prikr That sounds like a new feature request to me 🙂  (the ability to "upsert" through an endpoint)

**Comment by rijkvanzanten** [comment]
This is an issue in `knex-schema-inspector`: https://github.com/knex/knex-schema-inspector/issues/35

**Comment by prikr** [comment]
> @prikr That sounds like a new feature request to me 🙂  (the ability to "upsert" through an endpoint) 

Oh well, will create an ticket on Tuesday then! No time tomorrow.

**Comment by martijnboland** [comment]
Thanks @rijkvanzanten! Looks like it had a bit of impact, right?

**Comment by rijkvanzanten** [comment]
@martijnboland Was a tricky one to fix! Our unique logic only checked for unique constraints, while Knex only creates unique _indexes_. However, reading the index was way more trouble than reading the constraint! 

I did ran into one more issue on the unique side in ms sql though, so we're not 100% there yet.. (https://github.com/directus/directus/issues/4644)
