### ISSUE TITLE
Not possible to freeze Directus version

### ISSUE THREAD

**Issue by Mrmiffo** [directus/directus#4598]
**The issue and what you expected to happen**
For production purposes, I want to make sure that my server runs a specific, internally verified, version of Directus, especially since different release candidate version may have breaking changes. However, installing a "frozen" version will still install the latest version of Directus. This is an issue when hosting in a load balanced environment such as Elastic Beanstalk (one of the recommended installation environments) as EB may spin up a new node at any time which has an incompatible newer version than was initially installed.

Exact steps to reproduce this issue
1. Setup a default installation of Directus using the CLI instructions.
- Optionally remove the node_modules folder and package-lock.json file for a clean install.
2. Freeze the Directus version by changing the `package.json` file dependencies from `"directus": "^9.0.0-rc.50",` -> `"directus": "9.0.0-rc.50",`. 
```
  "dependencies": {
    "directus": "9.0.0-rc.50",
    ...
  }
```
2. Run `npm install` (automatically run by Elastic Beanstalk when starting up a new node) to download the node_modules and create the package-lock.json file.
3. Run `npx directus start` 
4. Navigate to the settings page of directus.

**Expected:** Directus is running version 9.0.0-rc.50.

**Actual:** Directus is running version 9.0.0-rc.51 (or higher)

I believe this is because the internal requirements of Directus such as "directus/app" are not frozen to the current version, but the highest possible version. This can be seen in the generated `package-lock.json` file:
```
"directus": {
      "version": "9.0.0-rc.50",
      "resolved": "https://registry.npmjs.org/directus/-/directus-9.0.0-rc.50.tgz",
      ...
      "requires": {
        "@directus/app": "^9.0.0-rc.50",
        "@directus/drive": "^9.0.0-rc.50",
        "@directus/drive-azure": "^9.0.0-rc.50",
        "@directus/drive-gcs": "^9.0.0-rc.50",
        "@directus/drive-s3": "^9.0.0-rc.50",
        "@directus/format-title": "^9.0.0-rc.50",
        "@directus/schema": "^9.0.0-rc.50",
        "@directus/specs": "^9.0.0-rc.50",
       ...
     },
...
}
```

3) Your environment:
Directus 9.0.0-rc.50
MySQL 8
npm deployment on Elastic Beanstalk and windows dev machine.
Chrome 89

4) Any other relevant information we might need to reproduce this issue
Full package.json for EB environment:
```
{
  "name": "my-directus-environment",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "npx directus start"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "directus": "9.0.0-rc.50",
    "mysql": "2.18.1"
  }
}
```

**Comment by rijkvanzanten** [comment]
Apparently lerna overrides these versions on every release and adds the `^` back. Lerna's `version` command has an `--exact` flag, but `lerna publish` doesn't seem to.
