### ISSUE TITLE
Drag & drop issue on Safari

### ISSUE THREAD

**Issue by vannivalle** [directus/directus#4600]
In the admin panel, there is a problem with dragging and dropping fields in layout options, using Safari, within collections.

---

### Project details
Directus Version: 9.0.0-rc.51
Environment: production
OS: macOS Big Sur (11)
Node: 15.8.0

**Comment by rijkvanzanten** [comment]
> there is a problem with dragging and dropping fields in layout options

What is the problem?

**Comment by vannivalle** [comment]
does not work

Inviato da iPhone

**Comment by Kematia** [comment]
I'll chime in as I probably encoutered the same error on a client's computer (clients OBVIOUSLY have to use safari or IE).

The mouse changes icon on hover, but when you click and try to drag nothing happens.

**Comment by Kematia** [comment]
![in](https://user-images.githubusercontent.com/17851386/111914701-5bbe4380-8a73-11eb-9a4f-be2321575f61.gif)

here it is, safari 12.01

**Comment by rijkvanzanten** [comment]
@Kematia Is that on the latest version of Directus? I'm on Safari too (though 14 instead of 12)
