### ISSUE TITLE
M2A - GraphQL "Sort" Argument Not Sorting

### ISSUE THREAD

**Issue by ddcollins** [directus/directus#4601]
M2A relations are not being "sorted" when the sort argument is provided in GraphQL:

```graphql
{
  items {
    course(search: "afae26e4-e8fc-445e-b58d-d1952c35f4da") {
      id
      title
      description
      transcript
      instructorNames
      thumbnailUrl
      trailerVideoUrl
      accessLevelTag {
        id
        title
      }
      lessons(sort: "sort") {
        sort
        id
        canPreview
        title
        description
        thumbnailUrl
        durationSeconds
        steps(sort: "sort") {
          id
          canPreview
          stepName
          collection
          sort
        }
      }
    }
  }
}
```

```json
"steps": [
  {
    "id": "05c4b8bf-57f4-40e0-926e-32e94ed828bc",
    "canPreview": false,
    "stepName": "Quiz",
    "collection": "question_set",
    "sort": 1
  },
  {
    "id": "2105c621-42ac-4027-baee-c6d84aed8211",
    "canPreview": true,
    "stepName": "Video",
    "collection": "lesson_video",
    "sort": 0
  }
]
```

I do have the `sort` field configured on the data model itself, and I have observed the sort argument working for all other cases other than our M2A relation. The `sort` field is also configured on the "steps" relation.
![Image 2021-03-19 at 4 10 19 PM](https://user-images.githubusercontent.com/38921476/111842548-9f774880-88cd-11eb-9a4b-62feca57d54a.png)
![Image 2021-03-19 at 4 11 56 PM](https://user-images.githubusercontent.com/38921476/111842728-e6fdd480-88cd-11eb-8c74-1d19b5eec9e9.png)

---

### Project details
Directus Version: 9.0.0-rc.44
Environment: production
OS: Linux 4.15.0-58-generic
Node: 14.16.0

**Comment by ddcollins** [comment]
@rijkvanzanten 
**Update**: The `search` argument also doesn't seem to be working. This might be a general "arguments" issue when sub querying like this.

The arguments **do** work when querying at the `lessonStep` top level, but when I try to pull navigating through the hierarchy below, it does not. 

Doesn't work:
```
{
  items {
    course(search: "afae26e4-e8fc-445e-b58d-d1952c35f4da") {
      lessons(sort: "sort") {
        steps(sort: "sort") {
          id
          sort
        }
      }
    }
  }
}
```

Works:
```
{
  items {
    lessonSteps (sort: "sort") {
      id
      sort
    }
  }
}
```

**Comment by ddcollins** [comment]
I bumped to `v9.0.0-rc.51` from `rc.44` and this appears to be working now

**Comment by rijkvanzanten** [comment]
Ohhh totally missed that you were on an older version! But yeah, the deep-nesting was implemented in https://github.com/directus/directus/issues/3919, which launched as rc.45 🙂
