### ISSUE TITLE
Passing "reset_url" to reset password endpoint does not work

### ISSUE THREAD

**Issue by andriusign** [directus/directus#4610]
Trying to access path /auth/password/request gives the following error:

Error:
{"errors":[{"message":"Url \"https://example.com/reset-password\" can't be used to reset passwords.","extensions":{"code":"INVALID_PAYLOAD"}}]}

Request headers:
headers:
email: "user@email.com"
reset_url: "https://example.com/reset-password"

I am sure this was working previously. Did this functionality get removed? If so, why?

---

### Project details
Directus Version: 9.0.0-rc.51
Environment: production
OS: Linux 4.15.0-29-generic
Node: 14.16.0

**Comment by rijkvanzanten** [comment]
You have to specify the allowed URLs in `PASSWORD_RESET_URL_ALLOW_LIST`. See https://docs.directus.io/reference/environment-variables/#security.

This was added to ensure strangers couldn't request a password for another account with a fake reset url 👍🏻
