### ISSUE TITLE
nested table directus_files returning NULL if requesting more than 100

### ISSUE THREAD

**Issue by PeterEhses** [directus/directus#4612]
I'm trying to query a collection that references files. Collection seeds has items with exactly one file. Seeds is a custom collection made entirely through the dashboard, files is the directus_files collection.

Instead of returning an object with the expected file metadata, null is returned in the field, if I request above 100 items at once. The more items I request (101, 200, 2000, -1, ...) the more items are returned with null instead of data for the file reference. 

The request `/items/seeds?limit=100&fields=image.height&sort=-date_created&offset=100&meta=*`
returns
```json
{
    "meta": {
        "total_count": 1202,
        "filter_count": 1202
    },
    "data": [
        {
            "image": {
                "height": 800
            }
        },
        {
            "image": {
                "height": 800
            }
        },
        {
            "image": {
                "height": 800
            }
        },
        [...]
```

while `https://api.tangled-garden.net/items/seeds?limit=-1&fields=image.height&sort=-date_created&offset=100&meta=*`
returns
```json
{
    "meta": {
        "total_count": 1202,
        "filter_count": 1202
    },
    "data": [
        {
            "image": null
        },
        {
            "image": null
        },
        {
            "image": null
        },
        {
            "image": {
                "height": 800
            }
        },
        {
            "image": null
        },
        [...]
```

This happens on the official directus 9.0.0-rc.24 docker,
with postgres 12 and local file storage. The bug is browser-independent.
I'm using PLESK for nginx / apache / SSL certificate management and Portainer for docker management.
I'm on a v-server with ubuntu 18 installed and plenty of resources to spare.
I'm not getting errors in any log as far as I can see.

Any help would be appreciated.

**Comment by rijkvanzanten** [comment]
Can you try updating to the latest release? There's a non-zero chance this issue doesn't happen in the last release 👍🏻

**Comment by PeterEhses** [comment]
Thanks! That fixed it. Just out of curiosity, was it a problem with the docker or in directus?

**Comment by rijkvanzanten** [comment]
The docker image itself doesn't really do anything, so this was an issue in Directus itself 🙂 IIRC, the problem was that the default limit of 100 items was applied internally for the total count of o2m items, instead of per-row.
