### ISSUE TITLE
Using `deep` for translations on a m2m relation

### ISSUE THREAD

**Issue by pzehle** [directus/directus#4613]
It is still unclear to me how to use `deep` as it is intended to be used to query "as deep as possible" in table relations. I don't really know if this is a bug or it is just me doing something wrong.

I can't manage to query translations on a m2m relation. I have 2 scenarios:

When I have a translations field in a collection, using the API, I can just use the `deep` parameter to query for a specific language, like so:

`deep[content_translations][_filter][languages_id][iso_code][_eq]=en`

This will return only the "English results" of my collection. I have a "content" collection, which has a field "translations", which is connected to a "languages" collection, which the language code is called "iso_code", if it is "en", then return the results. So far so good, and it works.

Second scenario, the same collection "content", has a m2m field, connected to another collection, "sections". This "sections" collection, also contains translations. So my logic would tell me to call the query like this:

`deep[sections_id][sections_translations][_filter][languages_id][iso_code][_eq]=en`

But it doesn't work at all. It just returns all the languages. "sections_id" is the field of the relation, "sections_translations" contains the translations, languages and so on. My problem, specifically, is that I cannot seem to go "deep" enough. It seems to fail with the "sections_id" part. As I said, I don't know if this is a bug (couldn't find any other issue like this) or I am just doing it wrong.

The response from the API is as follows, so you can give yourself an idea of the data structure:

```json
{
    "data": {
        "sections": [
            {
                "sections_id": {
                    "sections_translations": [
                        {
                            "menu_item_text": "Home",
                            "section_slug": "home",
                            "image_alt_text": "Creating websites and apps that awaken emotions",
                            "content": "<p><img src=\"http://206.81.27.36:8055/assets/429ed12d-4ccf-4a18-a9fb-6ae87ec35754?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc2Yzg4M2M0LTRjNDYtNDg4Yy04NjAwLTRiMDhkMmFkM2I0YiIsImlhdCI6MTYxNjM0NDA0NCwiZXhwIjoxNjE2MzQ0OTQ0fQ.i8k9Nkk4-zDQK7yGGSDlZ3zrv9JzFbRn2yi4at503nk\" alt=\"Logo artn.digital white\" width=\"1920\" height=\"505\" /></p>\n<h1>Creating <strong>websites</strong> and <strong>apps</strong> that awaken emotions</h1>\n<p><a href=\"#belief\">Our belief</a></p>",
                            "languages_id": {
                                "name": "English",
                                "iso_code": "en"
                            }
                        },
                        {
                            "menu_item_text": "Home",
                            "section_slug": "home",
                            "image_alt_text": "Wir kreieren Webseiten und Apps, die Emotionen erzeugen.",
                            "content": "<p><img src=\"http://206.81.27.36:8055/assets/429ed12d-4ccf-4a18-a9fb-6ae87ec35754?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc2Yzg4M2M0LTRjNDYtNDg4Yy04NjAwLTRiMDhkMmFkM2I0YiIsImlhdCI6MTYxNjM0NDA0NCwiZXhwIjoxNjE2MzQ0OTQ0fQ.i8k9Nkk4-zDQK7yGGSDlZ3zrv9JzFbRn2yi4at503nk\" alt=\"Logo artn.digital white\" width=\"1920\" height=\"505\" /></p>\n<h1>Wir kreieren <strong>Webseiten</strong> und <strong>Apps</strong>, die Emotionen erzeugen.</h1>\n<p><a href=\"#ueberzeugung\">Unsere &Uuml;berzeugung</a></p>",
                            "languages_id": {
                                "name": "Deutsch",
                                "iso_code": "de"
                            }
                        },
                        {
                            "menu_item_text": "Inicio",
                            "section_slug": "inicio",
                            "image_alt_text": "Creando sitios web y aplicaciones que despiertan emociones",
                            "content": "<p><img src=\"http://206.81.27.36:8055/assets/429ed12d-4ccf-4a18-a9fb-6ae87ec35754?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc2Yzg4M2M0LTRjNDYtNDg4Yy04NjAwLTRiMDhkMmFkM2I0YiIsImlhdCI6MTYxNjM0NDA0NCwiZXhwIjoxNjE2MzQ0OTQ0fQ.i8k9Nkk4-zDQK7yGGSDlZ3zrv9JzFbRn2yi4at503nk\" alt=\"Logo artn.digital white\" width=\"1920\" height=\"505\" /></p>\n<h1>Creando <strong>sitios web</strong> y <strong>aplicaciones</strong> que despiertan emociones</h1>\n<p><a href=\"#creencia\">Nuestra creencia</a></p>",
                            "languages_id": {
                                "name": "Español",
                                "iso_code": "es"
                            }
                        }
                    ]
                }
            }
        ]
    }
}
```

It doesn't really matter what I put in the `deep` query, it just returns all languages. I hope you can help me. Thank you!

**Comment by rijkvanzanten** [comment]
Heya! Have you tried / could you try 

`deep[sections][section_id][sections_translations][_filter][languages_id][iso_code][_eq]=de`

?

**Comment by pzehle** [comment]
Hey! Thanks for the response.

I think it was my bad, maybe I didn't specify it correctly. I am in fact using:

`deep[sections][section_id][sections_translations][_filter][languages_id][iso_code][_eq]=de`

Trust me, after hours of debugging this, I just tried every single level possible (haha), but still, that didn't fix it.

What fixed it was, to just delete all the collections involved and just try again, and it worked. This is always my last resource solution with Directus, I know it is not intended, but I assume when tampering directly with the database can be a little hard on some stuff. So just started again and it works normally :)

I am going to be working on translations a lot, and if this is a bug I will create or re-open this issue, as it was really annoying for me yesterday, but sadly (and gladly) I couldn't reproduce it anymore. I will let you know of anything.

As usual, thank you very much for the help.

**Comment by rijkvanzanten** [comment]
Okay! Glad to hear the deep parameter in fact works as intended. Not so great to hear that somewhere during the setup something went sideways.. Anyways, please let me know if you run into it again, and know what steps you took exactly to get there 🙂  (it might be related to https://github.com/directus/directus/issues/4245 🤔 )
