### ISSUE TITLE
Replace `path.normalize` with `normalize-path`

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#4628]
Currently, we're relying on `path.normalize` for normalizing the root configuration:

https://github.com/directus/directus/blob/2f163a91b440e753216fcfe5f5d1aea8687f23c4/packages/drive-azure/src/AzureBlobWebServices.ts#L48

However, this causes trouble under Windows, as these third party services rely on Unix paths exclusively (eg `/` instead of `\`).

For Azure, GCS, and S3, we should rely on https://www.npmjs.com/package/normalize-path instead of Node's native `path.normalize`

**Comment by WoLfulus** [comment]
Lets make sure to strip the first ´/` too if it exists so we don't end up with `//` on urls.

**Comment by mdocter** [comment]
@rijkvanzanten This issue can be closed.
