### ISSUE TITLE
RC51 appears to ignore .env file

### ISSUE THREAD

**Issue by vacri** [directus/directus#4630]
1) The issue and what you expected to happen
    Settings in the .env file appear to be ignored in v9.0.0.rc-51. Same setup with rc-42 didn't have this issue.

2) Exact steps to reproduce this issue

1. create a .env file with one entry: `PORT=9999`
2. create a dockerfile that imports the official image, and does nothing else except copy the .env file into place
3. docker build && docker run, and the logs report that Directus is serving on 8055, not 9999
4. docker run the same image with an added env var (`docker run -e PORT=7777`) and it serves on 7777

The same Dockerfile will read the .env file on rc42, if you don't use an sqlite db (42 crashes on that)

shell:

```
# these are the only two files in this directory
paul@edmund:~/tmp/env-problem$ ls -al
total 8
drwxr-xr-x 1 paul paul   28 Mar 23 18:24 .
drwxr-xr-x 1 paul paul 3398 Mar 23 18:21 ..
-rw-r--r-- 1 paul paul   95 Mar 23 18:24 Dockerfile
-rw-r--r-- 1 paul paul   10 Mar 23 18:22 .env

# content of both files is minimal
paul@edmund:~/tmp/env-problem$ cat .env
PORT=9999
paul@edmund:~/tmp/env-problem$ cat Dockerfile 
#FROM directus/directus:v9.0.0-rc.42
FROM directus/directus:v9.0.0-rc.51
COPY .env /directus/

# build the image
paul@edmund:~/tmp/env-problem$ docker build -t env-test .
Sending build context to Docker daemon  3.072kB
Step 1/2 : FROM directus/directus:v9.0.0-rc.51
 ---> a406e78d814e
Step 2/2 : COPY .env /directus/
 ---> Using cache
 ---> 4133022e96f4
Successfully built 4133022e96f4
Successfully tagged env-test:latest

# run the image, look for the announced port
paul@edmund:~/tmp/env-problem$ docker run env-test
07:27:08 ⚠️  > [snip key/secret warning]
07:27:08 ✨ Initializing bootstrap... [ snip sqlite bootstrap ]
07:27:10 ✨ Done
07:27:11 ✨ Server started at port 8055                               # not the port in the .env file
^C07:27:26 ✨ Shutting down...
07:27:26 ✨ Database connections destroyed
07:27:26 ✨ Directus shut down OK. Bye bye!

# run the image, but supply the port through a docker-supplied env var
paul@edmund:~/tmp/env-problem$ docker run -e PORT=7777 env-test
07:27:38 ⚠️  >  [snip key/secret warning]
07:27:39 ✨ Initializing bootstrap... [snip sqlite bootstrap]
07:27:40 ✨ Done
07:27:42 ✨ Server started at port 7777                           # is the port in the docker-supplied env var

```

I've also tried with a docker-compose setup that has some extra env vars for use with a mysql DB (rc42 crashes with sqlite). If I flip the RC version back to v42, the .env file is picked up. Flip it back to v51, and it's ignored again, as evidenced by the 'server started at port XXXX' line.

3) Your environment:
    What version of Directus you are using. v9.0.0-rc.51
    Which DBMS are you using: mysql 8, but also seen on default sqlite. 
    Which deployment are you using: docker 20.10.5
    What browser are you using: n/a

4) Extra info

Issue was first noticed deploying to the cloud, when rc51 ignored the env file vars describing the external mysql host, and kept creating a new local sqlite db on every deploy. The above test with PORT was just quicker and easier to confirm locally. So I think it's ignoring the whole .env file, rather than something specifically related to PORT.

**Comment by rijkvanzanten** [comment]
Are you sure the .env is in the correct location in the Docker image? FWIW, Directus does seem to read the `.env` as expected, based on it's location as set in the `CONFIG_PATH` environment variable 🤔

**Comment by vacri** [comment]
Okay, I think I've figured out the problem here. The issue is, I think, that the precedence of variables changed. In rc42, the env file entries were higher priority than the real env vars. (Both rc42 and rc51 have similar env vars assigned on their docker images, which is why I think there was a precedence change somewhere)

The problem is that the env vars on the docker image re-specify the default values. And because they already exist on the docker image as genuine env vars, you can't change them with a .env file since the real env vars take precedence.

I've been playing around with the `DB_XXXX` variables and just could not get rc51 to recognise a mysql db in those values... then I realised the docker image has an env var `DB_CLIENT` set to `sqlite3`. If the real env vars take precedence, then it doesn't matter what I set in the file, the engine will always be set to `sqlite3` - and this matches the behaviour I've seen.

Almost all of the 'root' env vars have pre-set values in the docker image (`PORT`, `DB_CLIENT`, `STORAGE_LOCATIONS`, etc). I did my testing with `PORT` and `DB_CLIENT`, and could not get rc51 to recognise either of those settings if listed in `.env`. However `ADMIN_EMAIL` and `ADMIN_PASSWORD` are _not_ set as env vars in the docker image, and rc51 does change behaviour on those.

So... I think that what is happening is the env file is being read, but being overwritten by the genuine env vars that the docker image supplies - meaning that we can't change most settings on the stock docker image using an env file, only with docker-supplied env vars.

a test env file I've been playing around with
```
PORT=9991           
DB_CLIENT=mysql
DB_HOST=192.168.20.245
DB_PORT=3306
DB_DATABASE=directus
DB_USER=directus
DB_PASSWORD=directus
ADMIN_EMAIL=env1@example.com
ADMIN_PASSWORD=directus
KEY=8da064c2-96ef-4b62-ad08-42f700021979
SECRET=be12625a-3b32-430f-bc5b-5e56c9c511cb
```
(oddly, both rc42 + rc51 ignore the key/secret in the env file (startup logs give boilerplate warning), but don't give a warning if they're supplied as env vars - I think this is a separate issue)

With the above file copied into `/directus/.env`, rc42 correctly uses the port and mysqldb (matches the env file above), but rc51 uses the default port and sqlite3 db (matches the docker image env vars)

The ADMIN_ login items do change the behaviour of rc51, so yes, the env file is actually being read by 51:

```
00:28:32 ✨ Adding first admin user...                       # with no ADMIN_ vars in the env file
00:28:32 ✨ No admin email provided. Defaulting to "admin@example.com"
00:28:32 ✨ No admin password provided. Defaulting to "M326RIAj6t4E"
00:28:32 ✨ Running migrations...
```
```
00:26:19 ✨ Setting up first admin role...                  # with ADMIN_ vars in the env file
00:26:19 ✨ Adding first admin user...
00:26:19 ✨ Running migrations...
```

**I think the fix here is simply not to pre-set the env var values on the docker image.** The code has default values whether or not it runs within docker, so there's no point duplicating them in the docker image anyway. Then you can add an env file and have some non-default values read. Then you can supersede that env file with (docker-supplied) env vars if you need (or just use real env vars anyway)

Ultimately, as it currently stands, I cannot get the stock docker image for rc51 to use a mysql db using an env file (regardless of `CONFIG_PATH`). That's the root problem I'm trying to solve at the moment. I can get it to use the mysql db if I use docker-supplied env vars (basically replacing the ones in the image), just not with an env file.

---

just for reference, these are the env vars on rc51's dockerhub image
```
$ docker image inspect directus/directus:v9.0.0-rc.51 | jq .[].ContainerConfig.Env
[
  "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
  "NODE_VERSION=14.16.0",
  "YARN_VERSION=1.22.5",
  "PORT=8055",
  "PUBLIC_URL=/",
  "DB_CLIENT=sqlite3",
  "DB_FILENAME=/directus/database/database.sqlite",
  "RATE_LIMITER_ENABLED=false",
  "RATE_LIMITER_STORE=memory",
  "RATE_LIMITER_POINTS=25",
  "RATE_LIMITER_DURATION=1",
  "CACHE_ENABLED=false",
  "STORAGE_LOCATIONS=local",
  "STORAGE_LOCAL_PUBLIC_URL=/uploads",
  "STORAGE_LOCAL_DRIVER=local",
  "STORAGE_LOCAL_ROOT=/directus/uploads",
  "ACCESS_TOKEN_TTL=15m",
  "REFRESH_TOKEN_TTL=7d",
  "REFRESH_TOKEN_COOKIE_SECURE=false",
  "REFRESH_TOKEN_COOKIE_SAME_SITE=lax",
  "OAUTH_PROVIDERS=",
  "EXTENSIONS_PATH=/directus/extensions",
  "EMAIL_FROM=no-reply@directus.io",
  "EMAIL_TRANSPORT=sendmail",
  "EMAIL_SENDMAIL_NEW_LINE=unix",
  "EMAIL_SENDMAIL_PATH=/usr/sbin/sendmail"
]
```

**Comment by vacri** [comment]
Update: I've solved my problem by reworking my setup to use docker-supplied env vars rather than a config/env file, so I'm relatively happy from here.

I still think the issue above is worth reviewing, because as I understand it, env files won't work properly on the stock docker image - values in the env file will be overwritten by the explicit env vars configured on the docker image.

**Comment by rijkvanzanten** [comment]
@WoLfulus any thoughts on the above??

**Comment by WoLfulus** [comment]
This is expected behavior. 

In this case we might have fixed a bug without know it existed, because the old version was the one behaving the way it shouldn't.

You'll always read the more "static" (or harder to change) configuration before the easier ones. This allows you to quick switch a configuration for example having a default PORT being 8055 in .env, but as soon as you need to run two instances for some reason you can `PORT=8056 npx directus start`.

So full expected behavior is:

- Start with the default values setup by the application 
- Merge config files if any
- Merge the environment file (.env) if any
- Merge the process environment
- Merge command line arguments
- Normalize values if needed

> I think the fix here is simply not to pre-set the env var values on the docker image.

I agree, but since we still need to get a basic config working because we want official container images to run ootb without having to set any flags other than `--port`, I'll move those environment variables present in the Dockerfile to a bundled `.env` file, as this would also solve the problem whenever you're copying a new `.env` file to the container and replacing the old one.

Also, imho, avoid copying `.env` files into the container since they are easy to get into production environments if this image is pushed. You can work around that by using `--env-file` flag in either `docker` or `docker-compose`, or even set `env_file` option in your docker-compose file so it loads it automatically without messing up with the container contents.
