### ISSUE TITLE
SSO for Facebook fails

### ISSUE THREAD

**Issue by workatease** [directus/directus#4641]
Hi, 

1) The issue and what you expected to happen
    When I configured the SSO for facebook and try to login it throws of the below error as it is not able to extract the email id
`{"errors":[{"message":"Couldn't extract email address from SSO provider response","extensions":{"code":"SERVICE_UNAVAILABLE","service":"oauth","provider":"facebook"}}]}`

expected to login using the facebook

2) Exact steps to reproduce this issue
    setup following keys- OAUTH_FACEBOOK_KEY ,OAUTH_FACEBOOK_SCOPE,OAUTH_FACEBOOK_SECRET
    use the same email to login into facebook when it asks for the user
    

3) Your environment:
    What version of Directus you are using. 9.0.0-rc.51
    Which DBMS are you using (MySQL 8, Postgres 12, ...). Postgres 12
    Which deployment are you using (npx, Docker, ...). npx
    What browser are you using (Chrome 87, Safari 14, ...). Chrome

**Comment by rijkvanzanten** [comment]
What scopes are you requesting from FB? -> `OAUTH_FACEBOOK_SCOPE`

**Comment by workatease** [comment]
OAUTH_FACEBOOK_SCOPE="public_profile email"

**Comment by workatease** [comment]
This is a test account logs from the console
![image](https://user-images.githubusercontent.com/57198612/112222727-54c43c00-8bff-11eb-8343-ec1ebe51dedb.png)

{
 access_token: 'EAAEg4SLzhGxxxx',  profile: {
   name: 'Jacob Alfeceghbfjcd Vijayvergiyaman',
 id: 'XxXxxx'
  }
}

**Comment by workatease** [comment]
> What scopes are you requesting from FB? -> `OAUTH_FACEBOOK_SCOPE`

OAUTH_FACEBOOK_SCOPE="public_profile email"

**Comment by rijkvanzanten** [comment]
Weird, from your profile response example, it seems like the `email` is missing from that profile 🤔 

@simov sorry to bother you, but do you happen to know if Facebook needs some special love to retrieve the email?

**Comment by workatease** [comment]
> Weird, from your profile response example, it seems like the `email` is missing from that profile 🤔
> 
> @simov sorry to bother you, but do you happen to know if Facebook needs some special love to retrieve the email?

from the [facebook documentation](https://developers.facebook.com/docs/facebook-login/web)  I see that it does not response back with the email

**Comment by rijkvanzanten** [comment]
Huh.. then what's the point of the `email` scope haha

**Comment by workatease** [comment]
> Huh.. then what's the point of the `email` scope haha

I believe there are more scope available in facebook api. so they are giving the access token based on the scope and we can retrieve the required data using the token.

do you think we can enhance the utils code  get-email-from-profile to grab the email from facebook api
https://github.com/directus/directus/blob/main/api/src/utils/get-email-from-profile.ts

**Comment by rijkvanzanten** [comment]
No, that should be handled in `grant` ideally. I'd like to prevent having a million if/elses in the codebase for all these different providers 🙂

**Comment by simov** [comment]
Yes, as you can see not every provider is following the spec. I guess you need to request some other user related scope from their graph API in order to get the user profile instead. Then you can use the `profile_url` configuration in Grant to specify the get user endpoint URL and Grant will pull that data from the endpoint. That can fail in some cases too, but for Facebook it was tested at some point, so unless they changed something it should work. You also need to explicitly tell Grant that you want the profile data returned by using the `response` configuration with `['token', 'profile', 'jwt', 'raw']`. Hope that helps.

**Comment by rijkvanzanten** [comment]
Wouldn't be surprised if FB sneakily changed something 😄 I've been burned by their Instagram API countless times before haha

We'll debug further and report back / PR into grant if we find anything of use 👍🏻

**Comment by workatease** [comment]
I was able to get it working after by using the below config 
`OAUTH_FACEBOOK_SCOPE="email"`
`OAUTH_FACEBOOK_RESPONSE="tokens,profile"`
`OAUTH_FACEBOOK_PROFILE_URL="https://graph.facebook.com/me?fields=email"`

its a issue with the facebook they have changed the way the information is send in the profile url

**Comment by workatease** [comment]
do we need to updated our docs ?

**Comment by rijkvanzanten** [comment]
Hmm yeah, we don't really have a good spot in the docs for that 🤔 

@simov is this something you'd like to have added by default in FB's profile link within `grant`, or is it too usage-specific?

**Comment by simov** [comment]
I'm trying to keep track of those things, but I don't think that it should be there by default. The email field will be available only if you request the email scope and other users may need other fields and scopes. I also don't have a good place to put this right now, but eventually once I have a wiki or something like that I can add it there.

**Comment by rijkvanzanten** [comment]
Makes sense! It's a difficult thing to document, as it's impossible to keep track of every change in every supported API 🤔

**Comment by workatease** [comment]
May be we can have a placeholder in the directus docs to update for different provider and get the communities help to update the docs

**Comment by rijkvanzanten** [comment]
@benhaynes Any ideas for if/how to put this in the docs? The TL;DR is:

Most SSO providers have a couple finicky _gotchas_ you need to keep into account (for example, Facebook requires you to add `?fields=email` to the login url) that are useful to have readily available somehow. However..... It'll be impossible to properly maintain all these gotchas for every oAuth-specced endpoint 🤔 

(Regardless, I'll close this issue for now as we found the correct flags to make Facebook play nice)

**Comment by workatease** [comment]
> @benhaynes Any ideas for if/how to put this in the docs? The TL;DR is:
> 
> Most SSO providers have a couple finicky _gotchas_ you need to keep into account (for example, Facebook requires you to add `?fields=email` to the login url) that are useful to have readily available somehow. However..... It'll be impossible to properly maintain all these gotchas for every oAuth-specced endpoint 🤔
> 
> (Regardless, I'll close this issue for now as we found the correct flags to make Facebook play nice)

it would be good to maintain the document. I think the community will help in updating the document.
as there are many discussion in discord regarding SSO just lost as we dont have a place for document

**Comment by rijkvanzanten** [comment]
Yeah I think it makes sense to have a "reference" of at least the most "popular" options (Facebook, Google, Twitter?, Okta?)

**Comment by benhaynes** [comment]
It seems like we'd want to add notice boxes for the _big_ name SSO options here:
https://docs.directus.io/guides/api-config/#oauth-single-sign-on-sso-openid

Does that seems about right?

**Comment by rijkvanzanten** [comment]
yeah that works for me!
