### ISSUE TITLE
Provide user context

### ISSUE THREAD

**Issue by xesjkeee** [directus/directus#4653]
I want to register user after his first login, so I created `auth.login.before` hook, then I got only email in input argument without other context

SSO also provides more context about user, for example: `first_name`, `last_name`, `username`, `roles` etc

Here you got email:  
https://github.com/directus/directus/blob/main/api/src/controllers/auth.ts#L257

And then dropped context:  
https://github.com/directus/directus/blob/main/api/src/controllers/auth.ts#L259

How can I get full context from oauth callback response?

**Comment by rijkvanzanten** [comment]
> How can I get full context from oauth callback response?

You can't as of right now. There's no special oAuth hook.

I think the ideal way forwards would be to have a dedicated oAuth hook, that's different from just `auth` so you can hook into this specifically

**Comment by rijkvanzanten** [comment]
Wanna open a PR for that?

**Comment by rijkvanzanten** [comment]
> SSO also provides more context about user, for example: first_name, last_name, username, roles etc

Btw, this really depends on the provider and exact config.. but yeah, still useful to get this info in custom hooks

**Comment by workatease** [comment]
> Wanna open a PR for that?

I would like to take it if no one is working on the custom hooks for oauth

**Comment by xesjkeee** [comment]
> > Wanna open a PR for that?
> 
> I would like to take it if no one is working on the custom hooks for oauth

I would love for you to take it

**Comment by Fl0pZz** [comment]
> > Wanna open a PR for that?
> 
> I would like to take it if no one is working on the custom hooks for oauth

That would be awesome!

**Comment by workatease** [comment]
I am waiting for this PR #4675 to be reviewed to start on it, as it will be handle one of the use case

**Comment by xesjkeee** [comment]
@workatease Hey, Pyll 👋 

PR was merged, maybe you need some help to do it? I would be excited about the hook 🤩

**Comment by workatease** [comment]
> @workatease Hey, Pyll 👋 
> 
> PR was merged, maybe you need some help to do it? I would be excited about the hook 🤩

I was trying to get hold of @rijkvanzanten in discord to get the right approach to start as I see we don't call the hooks in controller we call it from our service ... So was think on what is the standard to use here... 
There were many issues closed in past week so rijk was busy...
I would be great if we could pair or discuss more on discord and start on this

**Comment by workatease** [comment]
great . will start working on it will submit a PR for review in some time

**Comment by liho00** [comment]
May i know why oauth hook has been removed at the v9.6.0 latest version? how do i set the first_name by other key from third party profile api?

**Comment by rijkvanzanten** [comment]
@liho00 This issue is from way before the GA release of 9.0.0. Discussions are better suited for new questions 👍🏻

**Comment by liho00** [comment]
@rijkvanzanten I found the  exactly same opened issue at here, lets track the thread here https://github.com/directus/directus/pull/11306
