### ISSUE TITLE
Make the "delete" item icon always visible on m2o interface

### ISSUE THREAD

**Issue by Kematia** [directus/directus#4654]
If there's too many columns the icon gets hidden by the overflow, hiding it from the user.
![image](https://user-images.githubusercontent.com/17851386/112352045-b9989880-8cca-11eb-93b1-f81eca2c2842.png)

possible solutions:

1. move it to the left, before the first column
2. have it positioned absolutely either left or right - but it could overlap the content, will need to shrink the actual row to take that into account

Also it would be nice to attach a confirmation modal to the delete action. 
And maybe change the icon to a red "trashbin" icon? 

Willing to work on this.

**Comment by Kematia** [comment]
Ok, I had a look at the table-row code, and I was thinking of simply adding an "item-prepend" slot, and to use that on the relational interface.

Quick and dirty edit:
![image](https://user-images.githubusercontent.com/17851386/112483539-6893ad80-8d79-11eb-92d9-5d4b89bdfe7c.png)

What do you think?

**Comment by rijkvanzanten** [comment]
I like your thinking. I'm not totally sold on the left-side though 🤔 We have `x` on the right everywhere else, so I'm wondering if the left side is the expected place.

Also we'll have to take https://github.com/directus/directus/issues/3647 into account. This might not be an issue once that's pushed through

**Comment by Kematia** [comment]
![image](https://user-images.githubusercontent.com/17851386/112485256-06d44300-8d7b-11eb-9715-4e4c543c0a14.png)

Yeah, right side would be the expected position, but this is a little bit trickier to implement (it needs to be absolute to the table width, not the row), and it covers some of the content.
 
![image](https://user-images.githubusercontent.com/17851386/112486051-d50fac00-8d7b-11eb-87e9-44ae5e24cfe2.png)

**Comment by benhaynes** [comment]
I definitely prefer the consistency of keeping all actions on the right (other than sort, which is traditionally on the left). I also prefer the full icons being shown, as opposed to a "..." context menu. That said, I am intrigued by the hover-only icon idea... that doesn't block content, and allows us to add additional icons/options without crowding the UI!

**Comment by Kematia** [comment]
hey bad boys

https://user-images.githubusercontent.com/17851386/112626212-32653500-8e30-11eb-86cc-9967193e5abc.mp4

I added another slot for the row-actions, as the item-append could be useful for other things apart from actions (ie, external links, displays etc).

Couple things I'd like some feedback on: 

do we want all the rows actions to display when the user has scrolled to the far right, or we only want to see the hovered ones.
all:

![image](https://user-images.githubusercontent.com/17851386/112625728-9c310f00-8e2f-11eb-8ea8-e31bd642108c.png)

only hovered:
![image](https://user-images.githubusercontent.com/17851386/112625880-c08ceb80-8e2f-11eb-8aab-04caa4deb5dd.png)

Do we want a modal on deselect? I'd love that personally

**Comment by Kematia** [comment]
we could flip them around...
![image](https://user-images.githubusercontent.com/17851386/112626945-38a7e100-8e31-11eb-8420-b4d80a13ff69.png)

![image](https://user-images.githubusercontent.com/17851386/112627055-62f99e80-8e31-11eb-87b0-37bffa50364f.png)

**Comment by benhaynes** [comment]
Nice job!! Here are my thoughts:

* Let's keep the icons on the right
* Let's keep delete on the far-right, since it has priority over duplicate/others
* Let's make sure to keep the icon spacing consistent with how it was before and the rest of the App. These are far more spaced out.
* I'd like @rijkvanzanten 's opinion too, but I think having these actions **always on hover** might be a nice way to clean up the UI!

**Comment by rijkvanzanten** [comment]
@benhaynes Like I mentioned above, lets not forget about https://github.com/directus/directus/issues/3647 which effectively negates all of this 👀 (unless we wanna keep the tables of course)

**Comment by Kematia** [comment]
how far along is it? this could be a good at-interim solution...

@benhaynes got it!

**Comment by benhaynes** [comment]
> @benhaynes Like I mentioned above, lets not forget about #3647 which effectively negates all of this 👀 (unless we wanna keep the tables of course)

Can't those string templates still be long enough to overflow-x? Wouldn't that cause the same issue? Or are you saying that we'd have to recode this solution regardless?

**Comment by Kematia** [comment]
it's pretty simple to refactor tbf, it's just a column with position: sticky... I spent more time on figuring out how to increase the columns and grid spacing ahahah 

lemme open a PR so you guys can see what's going on

**Comment by rijkvanzanten** [comment]
> Can't those string templates still be long enough to overflow-x? Wouldn't that cause the same issue? Or are you saying that we'd have to recode this solution regardless?

The string-previews will ellipsis, so this problem shouldn't arise in the context of those "card" style rows 👍🏻

**Comment by rijkvanzanten** [comment]
Fixed in #4093
