### ISSUE TITLE
User invite url not working

### ISSUE THREAD

**Issue by lurza** [directus/directus#4655]
When I invite a user, the link in the email goes to: //admin/accept-invite?token=... 

The project URL is set in the Project Settings

![afbeelding](https://user-images.githubusercontent.com/20967950/112353773-5d367880-8ccc-11eb-8cd1-7ae553bc4420.png)

---

### Project details
Directus Version: 9.0.0-rc.51
Environment: production
OS: Linux 5.4.0-58-generic
Node: 14.16.0

**Comment by rijkvanzanten** [comment]
@lurza Make sure the `PUBLIC_URL` environment variable is configured properly 👍🏻
