### ISSUE TITLE
Sqlite database doesn't login in versions > rc.45

### ISSUE THREAD

**Issue by henriquegogo** [directus/directus#4662]
I had tried many versions. Since version rc.46 the /auth/login return an error 400 with sqlite database.
The last version stable for this database was rc.45

---

### Project details
Directus Version: 9.0.0-rc.51
Environment: production
OS: Linux 5.4.0-66-generic
Node: 14.16.0

**Comment by zanami** [comment]
Duplicate #4489 
Will be fixed as soon as new release of knex is pushed
https://github.com/knex/knex/pull/4376
I had to patch knex and then remove the .bd, then _npx directus bootstrap_.
