### ISSUE TITLE
Cannot upload files via s3 for alibaba OSS

### ISSUE THREAD

**Issue by cdwmhcc** [directus/directus#4665]
```
{
  "errors": [
    {
      "message": "E_UNKNOWN: An unknown error happened with the file uploads\\63e9c350-a998-4616-8019-ea009bcfd9d4.jpeg.\n\nError code: Forbidden\nOriginal stack:\nForbidden: null\n    at Request.extractError (\\node_modules\\aws-sdk\\lib\\services\\s3.js:692:35)\n    at Request.callListeners (\\node_modules\\aws-sdk\\lib\\sequential_executor.js:106:20)\n    at Request.emit (\\node_modules\\aws-sdk\\lib\\sequential_executor.js:78:10)\n    at Request.emit (\\node_modules\\aws-sdk\\lib\\request.js:688:14)\n    at Request.transition (\\node_modules\\aws-sdk\\lib\\request.js:22:10)\n    at AcceptorStateMachine.runTo (\\node_modules\\aws-sdk\\lib\\state_machine.js:14:12)\n    at \\node_modules\\aws-sdk\\lib\\state_machine.js:26:10\n    at Request.<anonymous> (\\node_modules\\aws-sdk\\lib\\request.js:38:9)\n    at Request.<anonymous> (\\node_modules\\aws-sdk\\lib\\request.js:690:12)\n    at Request.callListeners (\\node_modules\\aws-sdk\\lib\\sequential_executor.js:116:18)",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

Current Version: Directus 9.0.0-rc.51 

```
STORAGE_LOCATIONS="Alibaba"
STORAGE_ALIBABA_DRIVER="s3"
STORAGE_ALIBABA_ROOT="uploads"
STORAGE_ALIBABA_KEY="*****"
STORAGE_ALIBABA_SECRET="*****"
STORAGE_ALIBABA_BUCKET="test"
STORAGE_ALIBABA_REGION="cn-shanghai"
STORAGE_ALIBABA_ENDPOINT="oss-cn-shanghai.aliyuncs.com"
```

With the above configuration, I can upload files normally in the v8 version.

**Comment by rijkvanzanten** [comment]
You're 100% sure those credentials are correct? The error `Error code: Forbidden` is thrown by the S3 endpoint directly 🤔 

Does Alibaba OSS need any other settings? Do they rely on S3's path style? I know that's a problem with Minio.. Try adding `STORAGE_ALIBABA_S3_FORCE_PATH_STYLE=true` ?

**Comment by cdwmhcc** [comment]
Please allow me to say something unrelated to this issue here.

I have successfully migrated most of the data from v8 to v9 and displayed it correctly (for example: the previous tags stored text, but now json etc. have been resolved). Although there are still some problems, I am confident that they can be solved slowly.

After many days of actual use, I felt the great logic processing of the v9 version. It is also very comfortable to use, both in terms of user experience and performance, the v9 version has brought huge changes and improvements.

Sincerely thank the developer team for their contributions!

**Comment by rijkvanzanten** [comment]
@cdwmhcc Have you tried the `STORAGE_ALIBABA_S3_FORCE_PATH_STYLE=true` option? I don't have a Aliyun account to test with so I don't really know how to debug this best 😁 

> After many days of actual use, I felt the great logic processing of the v9 version. It is also very comfortable to use, both in terms of user experience and performance, the v9 version has brought huge changes and improvements.

Thanks! ❤️

**Comment by cdwmhcc** [comment]
> @cdwmhcc Have you tried the `STORAGE_ALIBABA_S3_FORCE_PATH_STYLE=true` option? I don't have a Aliyun account to test with so I don't really know how to debug this best 😁
> 
> > After many days of actual use, I felt the great logic processing of the v9 version. It is also very comfortable to use, both in terms of user experience and performance, the v9 version has brought huge changes and improvements.
> 
> Thanks! ❤️

Yes, I tried it before replying, it didn't work, it showed the same error message.

I confirm that my configuration is correct, because I use it not only in directus, but also in nodejs and other systems.

But I have never used alibaba oss through s3. I suspect that alibaba oss and s3 are not very compatible. It may also be that some configuration parameters are missing.

Is it possible to separate it, like the v8 version.

**Comment by cdwmhcc** [comment]
> > but also in nodejs and other systems.
> 
> Do you have an example of the integration from Node? If S3 doesn't work out as expected, we can look into making a dedicated `@directus/drive-alibaba` package. I just personally have no idea how any of alibaba's stuff works 😄

Yes, but it contains my secret key. Can you give me an email and I will send it to you?

**Comment by rijkvanzanten** [comment]
Sure thing! You can send it to rijkvanzanten@me.com

**Comment by cdwmhcc** [comment]
> Sure thing! You can send it to [rijkvanzanten@me.com](mailto:rijkvanzanten@me.com)

It has been sent to this mailbox. I wonder if you have received the email.

**Comment by rijkvanzanten** [comment]
Yes I did 👍🏻

**Comment by cdwmhcc** [comment]
> Yes I did 👍🏻

Hi, Rijk van Zanten, is my configuration wrong or other reasons.😍

**Comment by rijkvanzanten** [comment]
I don't know yet. I'll let you know here when I find anything

**Comment by kroawen** [comment]
Hi, @cdwmhcc , same alibaba configuration with your, it workes for me. 

`
STORAGE_LOCATIONS="Alibaba"
STORAGE_ALIBABA_DRIVER="s3"
STORAGE_ALIBABA_ROOT="images"
STORAGE_ALIBABA_KEY="XXX"
STORAGE_ALIBABA_SECRET="XXX"
STORAGE_ALIBABA_BUCKET="XXX"
STORAGE_ALIBABA_REGION="cn-shenzhen"
STORAGE_ALIBABA_ENDPOINT="oss-cn-shenzhen.aliyuncs.com"
`
this is api response: 

`{
    "data": {
        "id": "08e0649a-f9b0-4eb6-952d-9a367e0dcb37",
        "storage": "Alibaba",
        "filename_disk": "08e0649a-f9b0-4eb6-952d-9a367e0dcb37.png",
        "filename_download": "EiiBz93XYAMbIGX.png",
        "title": "Eii Bz93 Xya Mb Igx",
        "type": "image/png",
        "folder": null,
        "uploaded_by": "1861f7a1-3180-4103-bd12-ddedb7b5837a",
        "uploaded_on": "2021-03-30T09:32:52+08:00",
     }
}
.......
`
and this is OSS bucket file path 
![image](https://user-images.githubusercontent.com/6927999/112920399-7790ac00-913b-11eb-9c1d-5c3c3cba99ea.png)

my Version: Directus 9.0.0-rc.52

If your configure oss Bucket Policy 'AliyunOSSFullAccess' to your RAM account. I hope that it will help you .

**Comment by cdwmhcc** [comment]
> I don't know yet. I'll let you know here when I find anything

It is indeed possible to upload files in 9.0.0-rc.52. I used the same configuration and I don't know what happened.

But at the same time there is another problem. Filedisk_name in v8 saves the file name, while in v9 it uses the `uuid + file extension` method. I don't know how to display the files uploaded before.

In addition, the extension of the jpg file uploaded before is `jpg`, now it has become `jpeg`. If the file uploaded before has two file extensions: `jpeg/jpg`, it will become confusing.

**Comment by cdwmhcc** [comment]
![image](https://user-images.githubusercontent.com/8030134/112966714-112c7d80-917d-11eb-87ee-e0ead2f5f4d1.png)

There is another question，I set ROOT `test`, but after uploading, it is not displayed under the folder

![image](https://user-images.githubusercontent.com/8030134/112966907-41741c00-917d-11eb-80c3-30d5ff34e4ef.png)

**Comment by cdwmhcc** [comment]
@kroawen The configuration I used is the same as the configuration you gave, but it does not work in rc.51. Rc.52 was released yesterday, and it can now upload files normally. I don't know what happened. Thanks for help!
