### ISSUE TITLE
Wrong setup for existing M2M relation

### ISSUE THREAD

**Issue by yellowBanano** [directus/directus#4670]
When I tried to attach directus M2M relation for existing relations, I found that M2M after creating relation transforms to O2M. In collection view it display error message (screenshots attached). I tried to investigate `directus_field` and `directus_relations` and found that *one* side (in my case "course" collection) have wrong name (have "course_course_categories_category", instead of "course_categories_category")

My version of directus --  Directus 9.0.0-rc.51 
DB -- MySQL 8
deployment -- npx

![изображение](https://user-images.githubusercontent.com/32203047/112489208-4573f880-8d8f-11eb-92d7-be0b46206169.png)
![изображение](https://user-images.githubusercontent.com/32203047/112489237-515fba80-8d8f-11eb-9da2-37bdd0106c0d.png)

**Comment by yellowBanano** [comment]
FYI, I resolve issue by just removing redundant prefix, but this bug took me some time to research internals of directus

**Comment by rijkvanzanten** [comment]
Ref https://github.com/directus/directus/issues/3664
