### ISSUE TITLE
On reorder collections redirects to details 

### ISSUE THREAD

**Issue by yellowBanano** [directus/directus#4672]
When drag some row in collection & drop it, then window redirects instantly to row details. It might not reorder and save fully all entities in database, because of instant redirect. Expected that it will just reorder rows on collections page without dip dive into row details.

My version of directus -- Directus 9.0.0-rc.51
DB -- MySQL 8
deployment -- npx

![изображение](https://user-images.githubusercontent.com/32203047/112503794-465f5700-8d9c-11eb-9443-29cc1eb688fe.png)

**Comment by rijkvanzanten** [comment]
What browser is this on?

**Comment by yellowBanano** [comment]
Mozilla Firefox latest version (Firefox 86) for Linux
