### ISSUE TITLE
Can't create mirrored slug field

### ISSUE THREAD

**Issue by emrahnazif** [directus/directus#4693]
With directus 7 and/or directus 8, we were able to create mirrored slug field. 
I don't know if it is on purpose or something missing at v9.0.0-rc.51 that is no longer possible (or I am missing something?)

- Create a string field (as "title")
- Create another string field (as "title_slug") and from the interface tab select "Slug". 

And there is no option to mirror "title" as a "title_slug". This was very helpful feature. 
Am I missing something or this is a normal behaviour?

A+
---

### Project details
Directus Version: 9.0.0-rc.51
Environment: production
OS: macOS Big Sur (11)
Node: 14.16.0

**Comment by rijkvanzanten** [comment]
Heya! We're discussing that over here: https://github.com/directus/directus/discussions/4231 🙂
