### ISSUE TITLE
Logo visibility readme dark theme

### ISSUE THREAD

**Issue by YannickMol** [directus/directus#4695]
![Screenshot_20210326-195831_GitHub.jpg](https://user-images.githubusercontent.com/13256289/112680564-d4574280-8e6d-11eb-8d5f-6eb57c62af51.jpg)

**Comment by benhaynes** [comment]
I think there is a CSS `@media` condition for dark mode (`prefers-color-scheme`), but I'm not sure about adding that level of CSS to the markdown readme. @rijkvanzanten , do we want to go that route?

**Comment by rijkvanzanten** [comment]
Nope! (Also, I don't think GHs readme's support that level of CSS customization 🤔 )

**Comment by rijkvanzanten** [comment]
The only real "solution" is to use a logo that'll work on both light and dark

**Comment by benhaynes** [comment]
A background color agnostic image is less than ideal... I'll close for now.\
