### ISSUE TITLE
Clicking on any line in a custom collection opens details with ID of "1"

### ISSUE THREAD

**Issue by pkokorev** [directus/directus#4714]
I have issue with a custom collection that has a lot of many-to-one references to other collections.

### Bug description

The interface considers that all items in the table have an ID of "1". Any items that I click opens the details of the entry with ID of "1". Clicking on the checkbox to select an entry selects them all (as they have ID of "1"?).

### Workaround

I tried clearing the layout options directly in the database, changing view mode to cards - same issue. My only workaround is to display the ID in a column and then manually edit the URL to change "1" to the required number.

![directus-issue](https://user-images.githubusercontent.com/5184701/112763398-9ccece80-9004-11eb-9cb2-b52bb5c085e9.gif)

### Project details
Directus Version: 9.0.0-rc.51
Environment: production
OS: Linux 5.4.0-66-generic
Node: 14.16.0

**Comment by Nitwel** [comment]
Could you provide more information on how to reproduce this and what your db setup looks like?

**Comment by pkokorev** [comment]
I can't recreate the bug anymore, but it definitely was there for a while, so I could record the original video. I will close the ticket and open a new one if I manage to recreate the bug again.
