### ISSUE TITLE
Extension URLs don't respect PUBLIC_URL env var

### ISSUE THREAD

**Issue by MiniDigger** [directus/directus#4733]
rc51.
using a reverse proxy, I serve directus from apps.my.tld/app/directus/ and thus set the PUBLIC_URL to /app/directus/. This works for all the statics and requests, but the requests to the extensions don't work:
https://apps.my.tld/extensions/interfaces/
https://apps.my.tld/extensions/displays/
https://apps.my.tld/extensions/layouts/
https://apps.my.tld/extensions/modules/

**Comment by Jonesus** [comment]
I'm having the same issue, but noticed that the endpoint is actually working if I use a trailing slash, for example when reverse-proxying Directus behind `/api`:

`website.com/api/extensions/interfaces` -> redirects to `website.com/extensions/interfaces`
but
`website.com/api/extensions/interfaces/` -> returns data appropriately and
`website.com/api/extensions/interfaces/custom-interface/index.js` works

This was tested with Caddy as the reverse proxy with a pretty basic Caddyfile of

```
localhost {
    route /api/* {
        uri strip_prefix /api
        reverse_proxy localhost:8055
    }
}

```

Maybe one fix would be to have the Directus App use a trailing slash in its extension calls? For example in here:
https://github.com/directus/directus/blob/ecd5526b55aaab3b04e20f9e21285df3600b02ca/app/src/interfaces/register.ts#L18

the line would be changed to

```
const customResponse = await api.get('/extensions/interfaces/'); 
```

**Comment by MiniDigger** [comment]
I can't fully confirm this fix. when I change the `api.get('/extensions/interfaces')` to have a trailing slash,
`https://apps.my.tld/app/direcuts/extensions/interfaces/` gets created as expected, but `https://apps.my.tld/extensions/interfaces/conditional-fields/index.js` is still wrong, it seems like this import also needs to be adjusted? https://github.com/directus/directus/blob/ecd5526b55aaab3b04e20f9e21285df3600b02ca/app/src/interfaces/register.ts#L23

**Comment by rijkvanzanten** [comment]
> it seems like this import also needs to be adjusted?

This sounds like the true problem to me 👍🏻 

In here, we're setting the root for webpack imports within the context of the admin app:

https://github.com/directus/directus/blob/de1b6367f9e83a80b594e88ce6536fa5e9c95b1d/app/src/main.ts#L3

But that import for extensions from the API ignores that (on purpose, cause it's not in the app codebase), but is missing the "getRootPath" bit 👍🏻
