### ISSUE TITLE
The Tree-View interface has several problems

### ISSUE THREAD

**Issue by cdwmhcc** [directus/directus#4736]
Version: Directus 9.0.0-rc.52

| filed | type | Configuration |
| ----- | ----- | ----- |
| id | uuid | |
| name | String | |
| parent | many to one | |
| children | one to many | Tree View |

1. Unable to configure display template in `Interface`

![image](https://user-images.githubusercontent.com/8030134/112889237-f5d35b00-9107-11eb-9041-ee6e1416c3cd.png)

Configuration in `Display` doesn’t work either

![image](https://user-images.githubusercontent.com/8030134/112889305-0b488500-9108-11eb-8c29-25347c4f5ae4.png)

It can work if you configure it in the collection, but I think this logic is incorrect.

![image](https://user-images.githubusercontent.com/8030134/112889690-8dd14480-9108-11eb-9001-6842535afa0d.png)

2. If the category already has a parent category, you cannot change it with the button below, because after clicking the button below, only all parent categories and categories without parent categories will be displayed. If I want to change it, I must switch to this category and modify its parent category.

![image](https://user-images.githubusercontent.com/8030134/112889971-e6a0dd00-9108-11eb-85b8-2cbd7878450e.png)

3. If I click on the value in the red box below, all data will be cleared.

![image](https://user-images.githubusercontent.com/8030134/112892694-3c2ab900-910c-11eb-9935-80e0ab1666ce.png)

**Comment by Nitwel** [comment]
I agree with that it is confusing to setup the display template inside the collection and not the interface. Lets see what @rijkvanzanten has to say to this.

**Comment by rijkvanzanten** [comment]
Yeah we should add the display template option in options as well. The interface itself already accepts the template option 👍🏻
