### ISSUE TITLE
Password request - SDK missing url parameter

### ISSUE THREAD

**Issue by workatease** [directus/directus#4739]
we are missing the below url parameter 

https://github.com/directus/directus/blob/6a495e9636a17706ca0b7d20169a032660a11463/api/src/controllers/auth.ts#L170

https://github.com/directus/directus/blob/6a495e9636a17706ca0b7d20169a032660a11463/packages/sdk-js/src/handlers/auth.ts#L159

Are we going to targeting with the [new sdk ](https://github.com/directus/directus/tree/sdk-update) or the current branch?

**Comment by rijkvanzanten** [comment]
> Are we going to targeting with the new sdk or the current branch?

New SDK 👍🏻
