### ISSUE TITLE
File Storage status FORBIDDEN

### ISSUE THREAD

**Issue by y-a-20** [directus/directus#4745]
With the upgrade to version 52, there is no access to the file storage.
Before that, it was version 44 and all settings remained the same.
There is .env file.
<img width="492" alt="Снимок экрана 2021-03-30 в 12 03 46" src="https://user-images.githubusercontent.com/76753006/112973209-5cc93200-9151-11eb-96c9-7dc44caaceb4.png">

And what I have in App
![Снимок экрана 2021-03-30 в 12 14 37](https://user-images.githubusercontent.com/76753006/112973348-82563b80-9151-11eb-92c8-e91b5edfd383.png)
---

### Project details
Directus Version: 9.0.0-rc.52
Environment: production
OS: Linux 5.4.0-1029-aws
Node: 10.19.0

**Comment by Mrmiffo** [comment]
I've updated to rc52 as well using and I'm **not** facing any issues. The only difference in my settings is that I'm **not** using the STORAGE_AMAZON_ROOT parameter (it doesn't exist in my settings file). It could be a clue?

**Comment by y-a-20** [comment]
@Mrmiffo Yeah, it works. Thanks
STORAGE_AMAZON_ROOT is superfluous there.
