### ISSUE TITLE
STORAGE__ROOT configuration error

### ISSUE THREAD

**Issue by cdwmhcc** [directus/directus#4751]
![image](https://user-images.githubusercontent.com/8030134/112967169-8b5d0200-917d-11eb-9627-5fb5a6796ddb.png)

I set ROOT `test`, but after uploading, it is not displayed under the folder

`STORAGE_ALIBABA_ROOT="test"`

![image](https://user-images.githubusercontent.com/8030134/112966907-41741c00-917d-11eb-80c3-30d5ff34e4ef.png)

`STORAGE_ALIBABA_ROOT="public/uploads/_/originals"`

![image](https://user-images.githubusercontent.com/8030134/112976783-df6ce400-9187-11eb-8c50-bdd344f64f58.png)

After the upload is complete, `ROOT path` is appended to the beginning of the file name and is not uploaded to the specified folder.

**Comment by rijkvanzanten** [comment]
Is this on RC.52? https://github.com/directus/directus/pull/4643 should've fixed this 🤔 

(The problem is that your local machine uses `\` instead of `/` for the path separator)

**Comment by rijkvanzanten** [comment]
Strange 🤔 

You can't, it's a bug 👍🏻 

This line:

https://github.com/directus/directus/pull/4643/files#diff-591359d8ac8ca9a6f3e83b88a901febf794c31b0ce1836db8b73a1416de2255cR51

is supposed to make sure the path is normalized regardless of platform you're on 🤔

**Comment by cdwmhcc** [comment]
> Strange 🤔
> 
> You can't, it's a bug 👍🏻
> 
> This line:
> 
> https://github.com/directus/directus/pull/4643/files#diff-591359d8ac8ca9a6f3e83b88a901febf794c31b0ce1836db8b73a1416de2255cR51
> 
> is supposed to make sure the path is normalized regardless of platform you're on 🤔

I tried a fresh installation to RC.53, but the problem still exists.😇😇

**Comment by cdwmhcc** [comment]
![image](https://user-images.githubusercontent.com/8030134/113036744-3b0a9200-91c7-11eb-972e-31f613452129.png)

It worked!

**Comment by rijkvanzanten** [comment]
Nice!

Weird that it doesn't work with normalize-path though 🤔 That `$root` on 33 should be with `/` because of https://www.npmjs.com/package/normalize-path#usage

**Comment by WoLfulus** [comment]
@cdwmhcc are you running it on windows by any chance?

it does make sense because normalize-path is used only to normalize root, but `_fullPath` will mess it up again when calling `path.join`

**Comment by cdwmhcc** [comment]
> @cdwmhcc are you running it on windows by any chance?
> 
> it does make sense because normalize-path is used only to normalize root, but `_fullPath` will mess it up again when calling `path.join`

Yes,running it on windows.
