### ISSUE TITLE
Horizontal line in WYSIWYG showing as three dots

### ISSUE THREAD

**Issue by TheAzack9** [directus/directus#4752]
When adding a horizontal line in wysiwyg you get three dots instead of an actual horizontal line, which looks a bit odd. 

I assume it is probably just a css conflict, but hard to say :) 

![image](https://user-images.githubusercontent.com/2140448/112991832-dd932880-9167-11eb-9c4a-62212b2bc296.png)

How to reproduce:

- Create a new collection and add a WYSIWYG field, make sure the Horizontal line option is enabled
- Create a new element and try create a new element
- Add a horizontal linke

Environments:
Direcuts 9.0.0 rc. 52
MySQL 8
Docker deployment
Chrome 89.0.4389.90

**Comment by rijkvanzanten** [comment]
Bug, or a feature @benhaynes?

**Comment by benhaynes** [comment]
Haha, it was a feature... but I agree that's too opinionated for this design. Let's plan on making this a normal 2px line (`--border-normal`) instead.
