### ISSUE TITLE
Cannot query from directus endpoint

### ISSUE THREAD

**Issue by VanjaRadovanovic** [directus/directus#4754]
### Project details
Directus Version: 9.0.0-rc.51
Environment: production
OS: Linux 5.4.0-67-generic
Node: 10.19.0

I'm using latest installment of Directus and I'm trying to query from graphql endpoint with axios
![image](https://user-images.githubusercontent.com/69380881/113006669-dc68f800-9175-11eb-8f49-fc5956ae3740.png)

And I'm getting this as a response 
![image](https://user-images.githubusercontent.com/69380881/113007022-23ef8400-9176-11eb-9474-dbe4987528ae.png)
![image](https://user-images.githubusercontent.com/69380881/113007306-66b15c00-9176-11eb-93da-ef1b10c74ac7.png)
 
Any idea why is this happening?

**Comment by rijkvanzanten** [comment]
You're providing the query wrong in Axios 🙂 

https://medium.com/@stubailo/how-to-call-a-graphql-server-with-axios-337a94ad6cf9 has a good example on how to do a GraphQL query request from Axios 👍🏻

**Comment by RageBrahimi** [comment]
```javascript
const axios = require('axios');

let data = JSON.stringify({
  query: `query {
    items {
      project {
        title,
        id
      }
    }
  }`,
  variables: {}
});

let config = {
  method: 'get',
  url: 'http://localhost:8055/graphql',
  headers: {
    'Content-Type': 'application/json'
  },
  data: data
};

axios(config)
  .then((response) => {
    console.log(JSON.stringify(response.data));
  })
  .catch((error) => {
    console.log(error);
  });
```

Code straight from Postman. Or use the link above from @rijkvanzanten

**Comment by VanjaRadovanovic** [comment]
Thanks, I was querying like this for wp-graphql
