### ISSUE TITLE
Broken image link in docs after clean install

### ISSUE THREAD

**Issue by AaronBeaudoin** [directus/directus#4764]
At the path http://localhost:8055/admin/docs/concepts/application in the UI:

![image](https://user-images.githubusercontent.com/26592486/113057222-63b46c80-9172-11eb-82aa-0b0704ed526c.png)

Here is the `img` element `src` attribute in dev tools:

![image](https://user-images.githubusercontent.com/26592486/113057332-86468580-9172-11eb-9163-499a0a5930e9.png)

Directus Version: 9.0.0-rc.53
Database: SQLite3
Deployment: npx
Browser: Chrome 89

**Comment by benhaynes** [comment]
The asset seems to be loading in the dev mode (locally for me), but not in prod mode (?). It is not working on a Cloud Demo I created.
