### ISSUE TITLE
O2M-Relationship "Sort Field"

### ISSUE THREAD

**Issue by alengodev** [directus/directus#4769]
Hi,

in the latest version – RC53 – there is an issue @ O2M-Relationship "Sort Field".

I can't select any field or especially the sort column.

If I manually add the column "sort" (@ directus_relations) to the sort_field everything works fine.

Best,
Alex

- v9.0.0-rc.53
- MariaDB 10.3.24

<img width="952" alt="Bildschirmfoto 2021-03-31 um 07 55 47" src="https://user-images.githubusercontent.com/25492962/113097750-c4d25380-91f7-11eb-831b-64838c502f2a.png">
<img width="1015" alt="Bildschirmfoto 2021-03-31 um 08 04 44" src="https://user-images.githubusercontent.com/25492962/113097772-cd2a8e80-91f7-11eb-91ba-10c8fe7f6f12.png">
<img width="1013" alt="Bildschirmfoto 2021-03-31 um 08 04 20" src="https://user-images.githubusercontent.com/25492962/113097783-d156ac00-91f7-11eb-8035-b18a698b1271.png">

**Comment by Nitwel** [comment]
The sort field has to be of type integer but you can also write your own name in that field to generate a new one.
Does this resolve the issue?

**Comment by alengodev** [comment]
No unfortunately not - i can't type anything in the field or select any suggestion.
