### ISSUE TITLE
Not checked checkboxes for Toggle Interface

### ISSUE THREAD

**Issue by yellowBanano** [directus/directus#4804]
Displaying empty checkbox for Toggle Interface (Boolean in Db) on load. Should be displayed checked checkbox. If make this checkbox checked, then nothing has changed as it was already true. In order to make it falsy, I have to check it twice. In Db it's stored as 1 for true and 0 for false. In the previous version (v9.0.0-rc.51) it works good, but not in current (v9.0.0-rc.53).

My setup: 
Directus -- v9.0.0-rc.53, 
DB -- MySQL 8, 
Browser -- latest Firefox Mozilla, 
Deployment -- npx
![изображение](https://user-images.githubusercontent.com/32203047/113298547-a27a2c00-9304-11eb-9088-c64041b92192.png)

![изображение](https://user-images.githubusercontent.com/32203047/113298225-44e5df80-9304-11eb-8f16-24249116e0f8.png)

**Comment by Nitwel** [comment]
Is there a way to reproduce this? How did you add that field?

**Comment by yellowBanano** [comment]
**In DB it's just tinyint value. 1 -- true, 0 -- false**
![изображение](https://user-images.githubusercontent.com/32203047/113420663-61e8e400-93d2-11eb-8c91-69721eb851d3.png)
![изображение](https://user-images.githubusercontent.com/32203047/113420774-92308280-93d2-11eb-90d6-b591cf4884a4.png)

**If I go to collection layout, then if 0 then displayed as ":cross:" and if 1 then as ":checked:"**

![изображение](https://user-images.githubusercontent.com/32203047/113420965-ed627500-93d2-11eb-9ffb-afb014f01662.png)

**When I go to details in row with ":cross:" then I can see no checked** 

![изображение](https://user-images.githubusercontent.com/32203047/113421201-577b1a00-93d3-11eb-9404-020e7f9aeb42.png)

**When I go to details in row with ":checked:" then I can see same view** . Expected to see checked.

![изображение](https://user-images.githubusercontent.com/32203047/113421278-7c6f8d00-93d3-11eb-9304-319c55e51608.png)

**If I click to make it checked, then I can save it. Nothing changed in DB as it's already have "1" value**
![изображение](https://user-images.githubusercontent.com/32203047/113421390-b3de3980-93d3-11eb-9188-ef2f718c0bb9.png)
![изображение](https://user-images.githubusercontent.com/32203047/113421486-dff9ba80-93d3-11eb-9248-323678c396ed.png)

**When I make it cheched , then click it to make unchecked, it saved as needed**
![изображение](https://user-images.githubusercontent.com/32203047/113421616-1a635780-93d4-11eb-8314-b29dbd5002ae.png)
![изображение](https://user-images.githubusercontent.com/32203047/113421656-28b17380-93d4-11eb-94a1-2829cce7846b.png)

**Here is view in config admin panel**
![изображение](https://user-images.githubusercontent.com/32203047/113421731-47176f00-93d4-11eb-9341-37b9192fc339.png)
![изображение](https://user-images.githubusercontent.com/32203047/113421774-54ccf480-93d4-11eb-877e-806547f98b8e.png)
![изображение](https://user-images.githubusercontent.com/32203047/113421812-5e565c80-93d4-11eb-8069-9c024ac812b4.png)

**And in database**
![изображение](https://user-images.githubusercontent.com/32203047/113421903-80e87580-93d4-11eb-928e-228c4f718308.png)


I guess it cannot recognize values that come from DB and just make value by default "false", but in database it's "true"

**Comment by YannickMol** [comment]
Might this be related to the fact that the field you are saving to the database has a data type of `boolean` whereas the field in the collection has a `tinyint` data type? It works fine in PostgreSQL when the field is set up through the app.

**Comment by rijkvanzanten** [comment]
I just setup a fresh installation on MySQL 8, created a boolean field, and everything seems to work as expected. @yellowBanano Did you set this field up through Directus, or directly in the DB?

**Comment by RemiMatrod** [comment]
Hello, the same issue with the Toggle interface still occurs in v9.0.0-rc.95. The value I want to display is a `tinyint(1)` that was not created through Directus, and is considered as a `Boolean` in the data model page.
Database version: MySQL 5.7.

**Comment by rijkvanzanten** [comment]
@RemiMatrod Mind making a new issue? This thread is pretty old and related to a very different setup 🙂
