### ISSUE TITLE
API Queries Inconsistent Returns

### ISSUE THREAD

**Issue by doodlemania2** [directus/directus#4808]
If I do this:  `https://mydirectus/items/sku/`
And then I do this: `https://mydirectus/items/sku`

I get different results. My "public" role has this as a permission set for SKU:
`{
    "status": {
        "_eq": "published"
    }
}`

Similarly, if I issue a deeper query, I get different/strange results, like this:
`https://mydirectus/items/sku/?fields=sku_name,features.feature_name,group.group_name,aliases` returns some data that is "published," but not all data that is "published."

Tried removing the security to return all and that makes the first quirk fix (trailing slash) but doesn't fix the second quirk (deeper query).

One other note: related item Features and Group have the same public security trimming (_eq:published)

**Comment by rijkvanzanten** [comment]
Do you have caching enabled? Could it be that the `sku` collection changed in the meantime, ending up with a different cached state for `/` vs no-`/` ? 🤔

**Comment by doodlemania2** [comment]
Yes, and that was my first thought - so set up Postman to send no-cache headers to no avail. Also, the data set itself is fairly static (no changes in several moons and several reboots for RC revs).

**Comment by doodlemania2** [comment]
Shit... limit 100 by default. Sorry :(
