### ISSUE TITLE
Can't assign new users to a role

### ISSUE THREAD

**Issue by fatihky** [directus/directus#4810]
**1) The issue and what you expected to happen**
I wanted to add a user to a role, but I just got an error message.

**2) Exact steps to reproduce this issue**
1. Create a new user.
2. Create a new role.
3. Go to role's edit page (`/admin/settings/roles/:pk`).
4. Add newly created user through the `Add Existing` button under the `Users in Role` field.

**3) Your environment:**
Directus  `v9.0.0-rc.53` with MySQL

**Comment by rijkvanzanten** [comment]
What's the error message?

**Comment by fatihky** [comment]
@rijkvanzanten sorry, here it is:
```
[UNKNOWN] update `directus_roles` set `users` = '[\"{user_id}\"]' where `id` in ('{role_id}') - ER_BAD_FIELD_ERROR: Unknown column 'users' in 'field list'
```
