### ISSUE TITLE
Strange tab key and focus behavior

### ISSUE THREAD

**Issue by manuelwehrli** [directus/directus#4813]
When pressing the tab key inside a modal of the admin app, for example editing fields of a collection, the focus does not go linearly from one to the next element, sometimes it seems to get stuck on an invisible element in between (maybe on the hidden dropdown menu to edit the raw value), and on number fields the tab key puts the focus on each of that increment/decrement button inside the field, so it only gets to the next field after pressing three times. Can we have a more standard tab behavior?
Generally, there is no visual feedback where the current focus is on. Could this be improved so we can make use of the default key shortcuts, e.g. space bar to select/deselect checkbox or to open a dropdown menu?

Environment: Directus v9.0.0-rc.53 / Postgres 13.2 / Docker / Firefox 87.0

**Comment by Nitwel** [comment]
Directus right now is not really designed to work with tab navigation. This will probably change in the future because its a very important keypoint in accessability but for now, it's not really a main goal to have that working.

**Comment by benhaynes** [comment]
Correct. To get this right will require a dedicated, app-wide sprint. We are wrapping up bugs and v9 now, but this (and other a11y issues) are high on the list after that.
