### ISSUE TITLE
Broken public access in GraphQL

### ISSUE THREAD

**Issue by manuelwehrli** [directus/directus#4817]
Public (or limited role) access does not work in graphql without exposing the whole data model. Rest behaves well and graphql should work the same way, exposing only what needed. directus_collections and directus_fields should be without read access and this should not block graphql queries over the fields with access configured. The behavior is correct in v9.0.0-rc.51. If all the graphql schema info is needed during development, passing an admin token does the magic.

Environment: Directus v9.0.0-rc.53 / Postgres 13.2 / Docker / Firefox 87.0

**Comment by RageBrahimi** [comment]
I think and @rijkvanzanten can correct me if I’m wrong, this has been address in this commit[commit](https://github.com/directus/directus/commit/f90c31b798940163da641fbc8659d29222585e13) which is a part of [v9.0.0-rc.54](https://github.com/directus/directus/milestone/41)

**Comment by RageBrahimi** [comment]
I think and @rijkvanzanten can correct me if I’m wrong, this has been address in this [commit](https://github.com/directus/directus/commit/f90c31b798940163da641fbc8659d29222585e13) which is a part of [v9.0.0-rc.54](https://github.com/directus/directus/milestone/41)

**Comment by rijkvanzanten** [comment]
Yup
