### ISSUE TITLE
Wrong field metadata in m2m junction collection

### ISSUE THREAD

**Issue by manuelwehrli** [directus/directus#4828]
When creating two collections and a m2m relationship, a virtual field (no column in the database) is added to the parent collection which refers to the related collection, and optionally a corresponding reverse field is added to that related collection too. Now, when creating an additional standard field in the junction collection, e.g. a number, using the same name as one of those virtual fields in the other collections and then editing it, the modal shows it as alias type along with the relationship tab instead of number type with its correspondig options. The admin app seems to interpret some metadata the wrong way.

Environment: Directus v9.0.0-rc.53 / Postgres 13.2 / Docker / Firefox 87.0

**Comment by Nitwel** [comment]
Could you give more insight / exact steps on how to reproduce this.
What I did and what did work was the following:
1. Create collection `articles` and `tags`
2. Create m2m junction from articles to tags and vice versa with fields called `atricles.tags` and `tags.atricles`
3. Create fields called `tags` and `articles` in the junction

And everything seemed to work.

**Comment by manuelwehrli** [comment]
This is the way I did. Now, on the junction collection click the tags or articles field to open the edit modal. There will appear the submenu Relationship which should not for a standard field and under Schema it shows alias type instead of the options for a standard field. Under Interface and Display there are options for relationship type instead of the ones for e.g. integer or string.

**Comment by Nitwel** [comment]
Oh, it wasn't really clear to me that you meant the field settings and not editing a item in the junction.
