### ISSUE TITLE
error installing Directus 9 on postgresql 13.2-1 on windows

### ISSUE THREAD

**Issue by aurelien-joro** [directus/directus#4831]
this my error when I install directus 9 using postegresql 13.2-1 on windows

npx: installed 54 in 16.046s
? Choose your database client PostgreSQL / Redshift
? Database Host: 127.0.0.1
? Port: 52724
? Database Name: directus
? Database User: postgres
? Database Password: *******
? Enable SSL: No

Something went wrong while seeding the database:
[Error] Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
Please try again

**Comment by rijkvanzanten** [comment]
Are you sure those credentials are correct?

**Comment by aurelien-joro** [comment]
Yes, all credentials are correct.

**Comment by rijkvanzanten** [comment]
Are you absolutely sure? The error message `Timeout acquiring a connection` can only mean that Directus wasn't able to connect to the database with the given credentials and host/port.. 😬 

(I'll close this for now, we'll reopen if this turns out to be a problem in Directus itself)

**Comment by aurelien-joro** [comment]
sorry for the delay my answer, I should create first my databases !
Thank's for your help @rijkvanzanten
