### ISSUE TITLE
Display Template not working with relational (M2O) fields

### ISSUE THREAD

**Issue by nickluger** [directus/directus#4838]
# Example

We have a collection `author` and a collection `article`, with a M2O-relationship, one author writing multiple articles, i.e. an article `written_by` one author. 

`author` has only one non-standard-field `name`, and `article`has only `title` and `written_by`-M2O-field.

Now an `article` has a **Display Template** using `title`, **but also `author.name`**, `{{title}} by {{written_by.name}}` as raw value !

![Bildschirmfoto 2021-04-04 um 11 35 57](https://user-images.githubusercontent.com/32647249/113504684-ed30b980-9539-11eb-8ae6-40121a24cb9f.png)

![Bildschirmfoto 2021-04-04 um 11 47 36](https://user-images.githubusercontent.com/32647249/113504887-8f9d6c80-953b-11eb-99f7-7410728d578e.png)

# Expected result
Now we have an example author: _Adam Smith_, who wrote _The Wealth of Nations_. So now, when opening `/admin/collections/article/1` it should read on the displayed title/title-container:

**_The Wealth of Nations by Adam Smith_**

# What happens instead

It reads **_The Wealth of Nations by  --_**, which seems like the nested field of the associated M2O-table cannot be loaded in the title:

![Bildschirmfoto 2021-04-04 um 11 46 11](https://user-images.githubusercontent.com/32647249/113504858-5c5add80-953b-11eb-9215-1a957cbae69c.png)

---

### Project details
Directus Version: 9.0.0-rc.53
Environment: production
OS: macOS Big Sur (11)
Node: 14.16.0

**Comment by Nitwel** [comment]
Right now, it is only so far implemented that it works for values like string or number but not for relational values.
We would either have to fetch those values in the render-template or before that.

**Comment by rijkvanzanten** [comment]
@Nitwel We'll have to fetch the item separately for the title so we can fetch the correct fields before rendering it 👍🏻

**Comment by fballan93** [comment]
I'm having the same issue with one of my tables where i have two M2O relations. in Display it works . however when i wanted to edit the interface itself I can only fetch the top level id or reference. this would be extremely helpful to implement

**Comment by gitllermopalafox** [comment]
Hi, I'm having the same issue with translations:

I selected translations -> title in the collection config:

![](https://i.ibb.co/QXp769Z/Captura-de-pantalla-2021-04-21-a-la-s-00-45-21.png)

Then created a new record, go back to the record and the display name is empty:

![](https://i.ibb.co/rFqz0rZ/Captura-de-pantalla-2021-04-21-a-la-s-01-05-09.png)

**Comment by rijkvanzanten** [comment]
@gitllermopalafox This has popped up more often (like in https://github.com/directus/directus/discussions/5165 recently). The main question to answer is: Seeing `translations` is a _list_ of things, what do you expect it to display? Would it show the value of the first item? Would it show a "2 Items" with a dropdown in the title?

**Comment by gitllermopalafox** [comment]
Hi @rijkvanzanten,

Maybe I misunderstood the functionality of display template with translations.

In the collection config I set translations -> title, in raw format it looks like ```{{translations.title}}``` so I'd expect (in this case) the field 'title' that is in translations in the language of admin panel setted by the user.

An example what I mean:

![](https://i.ibb.co/BVB0FJK/directus-image.jpg)

---------

BTW

I'd expect the same in the list view, but I think this would be more an improvement.

**Comment by rijkvanzanten** [comment]
@gitllermopalafox Yeah! I understand that part 🙂 

I meant the following:

When you have a m2o-relationship, like articles->authors, you can do something like `{{ author.name }}`, because author is a single nested object, for example:

```
{
	id: 5,
	author: {
		name: "Rijk"
	}
}
```

However, when talking about translations, it's a nested list of things:

```
{
	id: 5,
	translations: [
		{ title: "Hello World", lang: "en-US" },
		{ title: "Hallo Wereld!", lang: "nl-NL" }
	]
}
```

With that in mind, what would you expect for `{{ translations.title }}`? Should it default to the first translation in the list? Should you explicitly state that with `{{ translations[0].title }}`? Should it show an aggregate, like `2 translations` with a hover/dropdown?

**Comment by benhaynes** [comment]
@gitllermopalafox — I'd recommend opening a new GitHub Discussion for this Feature Request. What we have now works, but you're looking for an enhancement where: **The Translation Display uses the current user's selected language as a default when rending the template.** 👍

**Comment by gitllermopalafox** [comment]
@rijkvanzanten @benhaynes sorry for the mess up.

What I expected is exactly what @benhaynes says.

I'll open a new feature request for this.

Thank you for your replies.
