### ISSUE TITLE
No critical - GraphQL as minimum health endpoint not working

### ISSUE THREAD

**Issue by juancarlosjr97** [directus/directus#4839]
By default, a clean installation with a public role entirely empty permissions, cannot open the `graphql` endpoint, in contrast, REST API can call `/server/health`. GraphQL endpoint only becomes available when the `Directus Fields` collection becomes readable.

Either adding to the documentation or making GraphQL to bypass at least the health endpoint.

**Comment by rijkvanzanten** [comment]
This is already resolved in https://github.com/directus/directus/pull/4625 🙂

**Comment by juancarlosjr97** [comment]
Great, thank you @rijkvanzanten :)
