### ISSUE TITLE
npx create-directus-project failed | npx: installed 54 in 4.922s  Unexpected token function

### ISSUE THREAD

**Issue by davebibo** [directus/directus#4869]
We have a clean centos installed machine and installed nodejs on it and want to install directus:

[centos@ip-adress nodejsroot]$ npx create-directus-project my-project
npx: installed 54 in 4.922s
Unexpected token function

environment:

CentOS Linux release 7.9.2009 (Core)

npm -v
3.10.10

node -v
v6.17.1

**Comment by Nitwel** [comment]
https://docs.directus.io/guides/installation/cli/#_1-confirm-minimum-requirements
You are using node version 6 where as directus requires at least version 12 to function.
