### ISSUE TITLE
GraphQL API query fails when upgrading to rc54

### ISSUE THREAD

**Issue by shi-rudo** [directus/directus#4873]
1) The issue and what you expected to happen
**After upgrading to rc54 the graphl Api does not respond**

2) Exact steps to reproduce this issue

---
**rc51**
query via postman to `http://127.0.0.1:8883/graphql`

```javascript
{
  items {
    articles {
      id
    }
  }
}
```

**RESPONSE OK** ✅

---

**rc54**
query via postman to `http://127.0.0.1:8883/graphql`
or
query via postman to `http://127.0.0.1:8883/graphql/system`

```javascript
{
  articles {
    id
  }
}
```

nor 

```javascript
{
  items {
    articles {
      id
    }
  }
}
```

**RESPONSE FAILURE** ❌

```
{
    "errors": [
        {
            "message": "Cannot read property 'fields' of undefined",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}
```

3) Your environment:
directus docker: directus/directus:v9.0.0-rc.54  
db docker: postgres:latest

Do I miss anything?

**Comment by TomasSestak** [comment]
Yeah, also the /graphql  in directus app is unavailable

**Comment by ddcollins** [comment]
@shi-rudo I had this same issue and discovered I had some lingering `directus_fields` and `directus_collections` that mapped to a table that didn't exist anymore. 

Once I cleaned them out the app started working again.

**Comment by shi-rudo** [comment]
> @shi-rudo I had this same issue and discovered I had some lingering `directus_fields` and `directus_collections` that mapped to a table that didn't exist anymore.
> 
> Once I cleaned them out the app started working again.

that did get the cms running again, but I still can't get access to my collections.

The graqhql explorer now shows directus but only with system collections, and not my articles etc.

![screenshot](http://www.dlds.de/pub/directus/snap.jpg)

**Comment by rijkvanzanten** [comment]
> The graqhql explorer now shows directus but only with system collections, and not my articles etc.

Make sure you're using `/graphl` and not `/graphql/system` 🙂

**Comment by shi-rudo** [comment]
> > The graqhql explorer now shows directus but only with system collections, and not my articles etc.
> 
> Make sure you're using `/graphl` and not `/graphql/system` 🙂

i do :-/ because I can't access the directus GraphIQl I am trying it via my gatsby frontend:

trying to access directus via `http://127.0.0.1:8883/graphql` or postman I get
```
{"errors":[{"message":"Must provide query string.","extensions":{"code":"INVALID_PAYLOAD"}}]}
```

and with gatsby grapqhl pointing to http://127.0.0.1:8883/graphql I get **no response**, with http://127.0.0.1:8883/graphql/system only the fields shown above

**Comment by rijkvanzanten** [comment]
That's odd! Seems like there's an illegal character in your field name somehow 🤔 

`vitamin_V1TB12_B12_mcg\r`

Is that `\r` part of your field name, or is that a carriage return that snuck in somehow?

**Comment by shi-rudo** [comment]
unfortunately not

```
ingredient_nutrients	trace_element_id_iodide_mcg
ingredient_nutrients	vitamin_VITC_C_mg
ingredient_nutrients	vitamin_VITD_D_mcg
ingredient_nutrients	vitamin_VITE_E_mg
ingredient_nutrients	id
ingredient_nutrients	status
ingredient_nutrients	sort
ingredient_nutrients	user_created
ingredient_nutrients	date_created
ingredient_nutrients	user_updated
ingredient_nutrients	date_updated
ingredient_nutrients	title
ingredient_nutrients	water_WATER_water_g
ingredient_nutrients	protein_PRO_protein_total_g
ingredient_nutrients	protein_PROTCAA_protein_amino_acid_composition_g
ingredient_nutrients	fat_FAT_fat_total_g
ingredient_nutrients	fat_FATNLEA_fatty_acid_triacyl_glycerol_g
ingredient_nutrients	fat_FASAT_saturated_fatty_acids_g
ingredient_nutrients	fat_FAMS_monounsaturated_fatty_acids_g
ingredient_nutrients	fat_FAPU_polyunsaturated_fatty_acids_g
ingredient_nutrients	cholesterol_CHOLE_cholesterol_mg
ingredient_nutrients	carbohydrate_CHOCDF_carbohydrate_total_g
ingredient_nutrients	carbohydrate_CHOAVLM_monosaccharide_g
ingredient_nutrients	fiber_FIBSOL_soluble_dietary_fiber_g
ingredient_nutrients	fiber_FIBINS_insoluble_dietary_fiber_g
ingredient_nutrients	fiber_FIBTG_dietary_fiber_total_g
ingredient_nutrients	minerals_ASH_minerals_g
ingredient_nutrients	preperation_method
ingredient_nutrients	ingredient_id
ingredient_nutrients	energy_enerc_energy_kj
ingredient_nutrients	trace_element_p_phosphorus_mg
ingredient_nutrients	fat_fatnlea_fatty_acid_triacyl_glycerol_g
ingredient_nutrients	vitamin_THIA_B1_mg
ingredient_nutrients	vitamin_RIBF_B2_mg
ingredient_nutrients	vitamin_V1TB12_B12_mcg
ingredient_nutrients	vitamin_VITK_K_mcg
ingredient_nutrients	vitamin_VITA_A_mcg
ingredient_nutrients	vitamin_FOL_folic_acid_mcg
ingredient_nutrients	vitamin_PANTAC_pantothenic_acid_mg
ingredient_nutrients	vitamin_BIOT_biotin_mcg
ingredient_nutrients	vitamin_NIA_niacin_mg
ingredient_nutrients	vitamin_VITB6A_B6_mg
ingredient_nutrients	fat_fat_fat_total_g
ingredient_nutrients	fat_fasat_saturated_fatty_acids_g
ingredient_nutrients	fat_fams_monounsaturated_fatty_acids_g
ingredient_nutrients	fat_fapu_polyunsaturated_fatty_acids_g
ingredient_nutrients	cholesterol_chole_cholesterol_mg
ingredient_nutrients	carbohydrate_chocdf_carbohydrate_total_g
ingredient_nutrients	carbohydrate_choavlm_monosaccharide_g
ingredient_nutrients	fiber_fibsol_soluble_dietary_fiber_g
ingredient_nutrients	fiber_fibins_insoluble_dietary_fiber_g
ingredient_nutrients	fiber_fibtg_dietary_fiber_total_g
ingredient_nutrients	minerals_ash_minerals_g
ingredient_nutrients	trace_element_na_sodium_mg
ingredient_nutrients	trace_element_k_potassium_mg
ingredient_nutrients	trace_element_ca_calcium_mg
ingredient_nutrients	trace_element_mg_magnesium_mg
ingredient_nutrients	trace_element_fe_iron_mg
ingredient_nutrients	trace_element_zn_zinc_mg
ingredient_nutrients	trace_element_cu_copper_mg
ingredient_nutrients	trace_element_se_selenium_mcg
ingredient_nutrients	trace_element_cr_chromium_mcg
ingredient_nutrients	trace_element_mo_molybdenum_mcg
ingredient_nutrients	vitamin_vita_a_mcg
ingredient_nutrients	vitamin_vitc_c_mg
ingredient_nutrients	vitamin_vitd_d_mcg
ingredient_nutrients	vitamin_vite_e_mg
ingredient_nutrients	vitamin_vitk_k_mcg
ingredient_nutrients	vitamin_thia_b1_mg
ingredient_nutrients	vitamin_ribf_b2_mg
ingredient_nutrients	vitamin_nia_niacin_mg
ingredient_nutrients	vitamin_vitb6a_b6_mg
ingredient_nutrients	vitamin_v1tb12_b12_mcg
ingredient_nutrients	vitamin_fol_folic_acid_mcg
ingredient_nutrients	vitamin_pantac_pantothenic_acid_mg
ingredient_nutrients	vitamin_biot_biotin_mcg
ingredient_nutrients	trace_element_mn_manganese_mg
ingredient_nutrients	source
ingredient_nutrients	water_water_water_g
ingredient_nutrients	protein_protcaa_protein_amino_acid_composition_g
ingredient_nutrients	protein_pro_protein_total_g
```

**Comment by rijkvanzanten** [comment]
@shi-rudo Would you be able to share a database dump where this is happening? That way I can reproduce it on my end 🙂 

Either here or in private through [email](mailto:rijk@directus.io) or [Discord](https://directus.chat)

**Comment by shi-rudo** [comment]
ha! Your tip was right. Just before I was going to run a postgres dump. I deleted the above collection on a test basis and lo and behold, directus rc54 now runs! Probably an illegal character hidden somewhere, as you said.

massive thanks for your support! 💚👍

**Comment by rijkvanzanten** [comment]
Strange! Well glad to hear that solved the issue 🙂 

I've also pushed up a fix that doesn't crash as aggressively on empty / no permission queries, so with that we'll consider this done 💪🏻

**Comment by shi-rudo** [comment]
great! i will update as soon as the new docker image is available.

**Comment by rijkvanzanten** [comment]
@shi-rudo It'll be up in about 10 minutes 👍🏻
