### ISSUE TITLE
Error set token auth sdk

### ISSUE THREAD

**Issue by Nisgrak** [directus/directus#4879]
I download the new JS SDK `@directus/sdk`, try to set the token manualy but it's fail.
```js
import { Directus } from "@directus/sdk";

const directus = new Directus(process.env.API);
directus.auth.token = process.env.TOKEN_LOGIN;
```

Give this error:
![image](https://user-images.githubusercontent.com/19597708/113873725-5b34e500-97b5-11eb-8597-385041b89c31.png)

The prop token is read only, this is a console log of the directus object
![image](https://user-images.githubusercontent.com/19597708/113873848-79024a00-97b5-11eb-8a85-e0b0a60d8c87.png)

I'm using 9.0.0-rc.54 in the server and client.

**Comment by WoLfulus** [comment]
The docs are wrong in this case, I'll update them, but since you're logging in with static tokens, use `static` instead.

```ts
await sdk.auth.static('static');
```
