### ISSUE TITLE
Switching collections sends wrong relational sort-parameter once

### ISSUE THREAD

**Issue by nickluger** [directus/directus#4880]
Sorry I'm not sure whether this is related to https://github.com/directus/directus/issues/4543 or something completely different. 

When a collection is sorted by a relational parameter, e.g. `articles` by their `authors`, and you switch to any other collection e.g. `dogs`, the frontend sends a request to the `items/dogs` endpoint with the `sort=authors` set, which results in `500` internal server error, as dogs do not have an `author` field, of course.

This happens only once on collection-switch. After that the correct sort parameter is sent (e.g. `race` or `weight`, whatever dogs are sorted by...🐶 )

It does not happen if the collection you switch **from** is sorted by a regular field, and it also doesn't happen, if you initially load the page with the collection (`articles`), only when switching to any other collection like `dogs`.

### Project details
Directus Version: 9.0.0-rc.54
Environment: production
OS: Linux 4.14.225-169.362.amzn2.x86_64
Node: 14.16.0

**Comment by rijkvanzanten** [comment]
I can't seem to reproduce this 🤔 I think I followed exactly what you said:

* Created an `articles` table with a `authors` m2o column to `directus_users`
* Created a `dogs` table with 2 other unrelated "regular" sort fields
* Made sure all presets are cleared, so there's no accidental defaulting going on to the new collection
* Navigated to `articles`, sorted by `author`
* Noted that the preset for `articles` was saved as expected
* Navigated to `dogs`, which sorted by `id` (which is the expected correct default)

Could it be that you have any global default presets with an invalid sort field perhaps? Would you be able to share a database dump?

I'll close this for now, but we can reopen if it's accurately reproducible 🙂

**Comment by nickluger** [comment]
Thank you, @rijkvanzanten for taking a look at it. 🙏
I will try to create an accurate reproduction, or find out, if global presets are affecting this, so we can narrow it down.
