### ISSUE TITLE
Manually entered string as primary key can break admin ui

### ISSUE THREAD

**Issue by kees-tce** [directus/directus#4896]
Hi all,

Can you please provide:

1) The issue and what you expected to happen
    When a collection has an id/primary key field that is a "manually entered string" the value of that ID field can break the admin UI.

2) Exact steps to reproduce this issue
    - Add a new collection
- make the id field type "manually added string"
- add an object to the collection and set "AB#ab" as the id value.
- go back to your collections overview and try to open the newly created object. Will result in a 403 FORBIDDEN error, because the url to that object ends in "AB" instead of "AB#ab"

3) Your environment:
    9 rc 53 on MySql
4) Any other relevant information we might need to reproduce this issue
    N/A

**Comment by rijkvanzanten** [comment]
I'm wondering if this is a bug we can fix, or something that's inherently not going to be supported in Directus 🤔 

Seeing that we rely on the PK in the context of URLs, special characters like `#` or `/` etc in the URL can cause problems 🤔 

I suppose we could URL escape the links in the app dynamically to prevent this

**Comment by kees-tce** [comment]
I think escaping it in the admin url is a good solution. The thing, for example, is that Manufacturer Part Numbers (MPN) for hardware products can easily consist of # or / characters for example. These are supposed to be uniquely identifiable.

**Comment by kees-tce** [comment]
By the way, if there is any way to update an object without the need of sending the primary key along, this issue for me personally is moot. I don't mind having an additional id field that is auto incremented. I just want to be able to update an object where "mpn = 'AB#ab'" so without knowing the primary key.

**Comment by rijkvanzanten** [comment]
Not as of right now. That being said, I'm looking to support update/delete by filter query in the (near) future: https://github.com/directus/directus/discussions/3119
