### ISSUE TITLE
Extensions are not loading with Directus 9.0.0-rc.55

### ISSUE THREAD

**Issue by martijnboland** [directus/directus#4902]
After upgrading Directus from 9.0.0-rc.54 to 9.0.0-rc.55, my custom modules, hooks and endpoints are not working anymore. It seems that none of the extensions are loaded. 

Downgrading to 9.0.0-rc.54 resolves the issue.

Windows 10, PostgreSQL 12

**Comment by martijnboland** [comment]
Installed 9.0.0-rc.56 and extensions are still not loading on Windows. Should I create a new issue?

**Comment by benhaynes** [comment]
Seems like the same issue, so we'll reopen.

**Comment by Jakob-em** [comment]
I just tried out custom extensions after the update and they seem to work as expected, so maybe your problem is related to something different.
Are there any errors in the browser console when opening directus?

**Comment by martijnboland** [comment]
I did see some errors in the console, if I remember well. I’ll try to check these tonight.

**Comment by rijkvanzanten** [comment]
I think this might've been fixed in 56 🙂  I'll close it for now, we can reopen if the problem persists

**Comment by martijnboland** [comment]
Found the specific issue: 

In my situation, I have a single rollup config for all my extensions (multiple inputs, via a 'multiInput' plugin). Rollup generates a common chunk that is put into the root '/extensions' folder. Directus does not serve this common chunk anymore in rc.56 (404 error, although the file does exist on disk). Until rc.54, this common chunk was served as well.

So, would it be possible that Directus serves these common chunks again? Or do I need to change the Rollup config?

**Comment by rijkvanzanten** [comment]
Ahhh I see.. it was never meant to work in the first place, so didn't realize people where relying on it. There's definitely a need for an optimized loading strategy (as per https://github.com/directus/directus/issues/4834), but we should figure that out in a more "officially" supported fashion.

Could you share your rollup config? Curious to see how you put it together like that in the first place (cc @Jonesus)

**Comment by martijnboland** [comment]
I have a directus folder and an extensions source folder that has the same structure as the final extensions folders.

![image](https://user-images.githubusercontent.com/167455/114319888-b1868880-9b13-11eb-8c18-daf888a6d357.png)

This is my single rollup config for all extensions. With the multiInput plugin, you can use a glob pattern for the inputs and all extensions end up nicely in the directus/extensions folder.

```js
import multiInput from 'rollup-plugin-multi-input';
import { terser } from 'rollup-plugin-terser';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import vue from 'rollup-plugin-vue';

export default {
	input: ['src/**/index.js'],
	output: {
		format: 'es',
		dir: '../directus/extensions',
	},
	plugins: [multiInput(), terser(), resolve(), commonjs(), vue()],
};
```
