### ISSUE TITLE
Can't upload Image bigger than 1MB.

### ISSUE THREAD

**Issue by TomasSestak** [directus/directus#4931]
When uploading image larger than 1MB I get 413 error, entity too large, I didn't find any documentation where to set the limit in directus 9. Could you please navigate me a little how to do it? We got the images hosted on AWS (if it makes difference?)

**Comment by xesjkeee** [comment]
I think it handles by your ingress (like `nginx`) of your storage

Have same error and resolve it by expanded the request size on `nginx`
