### ISSUE TITLE
Forbidden error in collection list

### ISSUE THREAD

**Issue by Thomasparsley** [directus/directus#4933]
I install latest (rc.56) Directus.

I created some data models for the purpose of the test. I created a test user and assigned him a test role. The test role is set to see only one field from one model data.
![image](https://user-images.githubusercontent.com/41927757/114180758-ebebfc00-9940-11eb-8d45-8923654c9437.png)

When I log in to a test user, I only see one collection correctly in the collections.

But when I open the "Team Category" collection I get this forbidden error
When I set the permissions  for the test role "read all", everything works fine.

![image](https://user-images.githubusercontent.com/41927757/114181331-abd94900-9941-11eb-8091-4ce5c39bfc50.png)

Directus 9.0.0-rc.56
DBMS: MariaDB 10.3.25
Deployment: npx
Browser: Chrome 89 - 64x
Node: 14.16.0
Local VM - Ubuntu  20.10

**Comment by benhaynes** [comment]
Difficult to say without more info. Does the Team Category collection have relational fields? Did you turn off any of the _system_ collection permissions? (Button a the bottom of the permissions list). Can you paste the permissions JSON here for review?

**Comment by Thomasparsley** [comment]
> Does the Team Category collection have relational fields?

No. Team category has no relational fields. But some other data models refer to the "Team category" (The data model "Events team record" has m2o for "team category")

> Did you turn off any of the system collection permissions?

No. 

> Can you paste the permissions JSON here for review?

I don't know, what you mean permissions JSON?
You mean JSON in items permissions for "team category"?
![image](https://user-images.githubusercontent.com/41927757/114199814-ebf5f700-9954-11eb-961b-99065c4d5594.png)
![image](https://user-images.githubusercontent.com/41927757/114199873-f9ab7c80-9954-11eb-9c82-73c6cdd838d6.png)

**Comment by benhaynes** [comment]
Ahh, this is likely due to turning off the READ of the `id` field. By respecting that permission, the App no longer has a way to identify the item. You can turn on that one field and it should work.

**Comment by Thomasparsley** [comment]
Ah, interesting. When I turn on read of `id` I still get 403 / FORBIDDEN. But when I also turn on read of `status`, then I dont get 403.

So when I create data model with `status`, then app required `id` and `status` to get permissions? 

I understand why app need  `ID`. But why is also required `status`? When i have no restricting for status and I only want to show name of team category.

**Comment by Thomasparsley** [comment]
It occurred to me to look in the console.
![image](https://user-images.githubusercontent.com/41927757/114209852-64fa4c00-995f-11eb-88b8-4435c301bae9.png)

I don't know how App creating request for API. But it's interesting send queries for unnecessary fields.

Now, with turned on `id` and `status` again I get 403.

**Comment by benhaynes** [comment]
Ahh, yes, if you used the auto-generated field during Collection creation, you probably have `status` set as the Archive field. I defer to @rijkvanzanten on if this check can be bypassed, but the permissions issue probably comes from the API needing to check that the item was not soft-deleted (archived).

**Comment by rijkvanzanten** [comment]
> but the permissions issue probably comes from the API needing to check that the item was not soft-deleted (archived).

~~API~~ App yeah!

The app will automatically filter out all archived items on the front-end, but seeing that your user doesn't have access to read the status field to read the archived value, that filter fails

**Comment by Thomasparsley** [comment]
> Now, with turned on id and status again I get 403.

I forget to reset page preferences.

It would be nice have this information in documentation. (If this info is already in docs, than sorry :D) Tomorrow i check docs and will edit corresponding page.

At this moment I assume the issue is solved. Thanks :)

**Comment by benhaynes** [comment]
This is probably _not_ in the Docs. I'll try to find time to add it today, otherwise, we'll gladly accept your PR! 🙂

**Comment by rijkvanzanten** [comment]
@benhaynes Should we look into "force-enabling" fields that are required for app use when app-access is enabled? In this case `id`, and `status` are required for app-access in this collection 🤔

**Comment by benhaynes** [comment]
https://github.com/directus/directus/commit/5d538a13697d248c909bd381dd2dc2cf5d594629
