### ISSUE TITLE
/lib64/libstdc++.so.6: version CXXABI_1.3.8 not found CentOS 7

### ISSUE THREAD

**Issue by abertay-university** [directus/directus#4935]
After update to r56 I received the following error on the CLI:
`/lib64/libstdc++.so.6: version CXXABI_1.3.8 not found`

This is due to CentOS 7 having only having gcc v3.8.5 installed by default.

To fix this error, I had to compile a newer version gcc then symlink the new /usr/local/lib64/libstdc++.so.6 to /lib64/libstdc++.so.6

Here is the code all in one (change version as needed). Please note it takes ~1 hour to complete.
`yum install gmp-devel mpfr-devel libmpc-devel wget`
`wget https://ftp.gnu.org/gnu/gcc/gcc-8.3.0/gcc-8.3.0.tar.gz`
`mkdir gcc-8.3.0-build`
`tar xf gcc-8.3.0.tar.gz`
`cd gcc-8.3.0-build`
`../gcc-8.3.0/configure --enable-languages=c,c++ --disable-multilib`
`make && make install`
`export PATH=/usr/local/bin:$PATH`
`export LD_LIBRARY_PATH=/usr/local/lib64:${LD_LIBRARY_PATH}`
`rm /lib64/libstdc++.so.6`
`ln -s /usr/local/lib64/libstdc++.so.6 /lib64/libstdc++.so.6`

Confirm gcc version with:
`gcc -v`

Confirm supported CXXABI versions:
`strings /lib64/libstdc++.so.6 | grep '^CXXABI_'`

**Comment by rijkvanzanten** [comment]
Thanks for the heads up!

We'll close this for now as it's not something we can address within Directus itself as it seems to be an npm-issue in building native dependencies
