### ISSUE TITLE
GraphQL error on date - Field error: value is not an instance of Date

### ISSUE THREAD

**Issue by TheAzack9** [directus/directus#4938]
1)
When trying to fetch any kind of date with GraphQL do i get error `Field error: value is not an instance of Date`. 

![image](https://user-images.githubusercontent.com/2140448/114209063-7f7ff580-995e-11eb-9076-f43821c17ef2.png)

2) 
1. Setup some kind of collection with a DateTime field
2. Add any item and set the date to today
3. Query it through graphql

3)
Directus 9.0.0 rc 56
MySQL 8
Docker
chrome version 89.0.4389.114

Not sure what else to provide so feel free to ask if you need more info :) 😅

**Comment by TheAzack9** [comment]
Aha, i decided to look into this further and seems the issue is that Directus tries to return a string as a Date. 
So when `getGraphQLType` returns and expects timestamp or dateTime to be a `GraphQLDate` while what the database reads is a string :)  (Here: https://github.com/directus/directus/blob/ecd5526b55aaab3b04e20f9e21285df3600b02ca/api/src/utils/get-graphql-type.ts#L20)

I see two potential fixes for this, not sure what is best or safest...

The easier solution is to simply return `GraphQLString` for datetime and timestamp aswell and one will have to parse the string to a date externally. 

The "more advanced" and probably more proper solution is to fix the return value.

It might also be that this was fixed in a migration script and that i somehow migrated incorrectly... If that is the case am i very sorry for bugging you with this 😅 Please call me out if that is the case :)

**Comment by rijkvanzanten** [comment]
The Directus API relies on ISO8601 date strings for input/output through JSON 🤔 So in this case, the result object is an ISO8601 string where GraphQL expects a Date?

**Comment by rijkvanzanten** [comment]
How does GraphQL otherwise return a Date in JSON? Dates aren't a JSON native thing, so it must have it's own sort of string-based format to use 🤔

**Comment by TheAzack9** [comment]
i actually wanted to check that myself so i tested :) I just simply bruteforced a field to return a Date instead.

Seems the difference is marginal and is mostly the same!

When using the GraphQLDate i get "2021-04-09T15:57:36.000Z" returned 

When just using the string type i get the expected "2021-04-09T17:57:36". 

Seems the only difference is that GraphQL defines that it is returned in the local timezone while Directus keeps this undefined. (indicated by the Z)

**Comment by rijkvanzanten** [comment]
so GraphQL's date is literally just `Date`'s `.toJSON()` string, which in turn is ISO8601 haha

**Comment by rijkvanzanten** [comment]
Directus keeps the timezone agnostic based on whether timestamp or datetime is used! Timestamp contains TZ, datetime doesn't

**Comment by TheAzack9** [comment]
> so GraphQL's date is literally just `Date`'s `.toJSON()` string, which in turn is ISO8601 haha

Seems so :)

> Directus keeps the timezone agnostic based on whether timestamp or datetime is used! Timestamp contains TZ, datetime doesn't

Aha, i see!

**Comment by rijkvanzanten** [comment]
So then the question remains.. Do we return the date as a string in GraphQL, or do we try parsing the ISO string back to a JS Date, to then have Graphql parse it back to the ISO string? 🤔

**Comment by TheAzack9** [comment]
I would say unless there is some underlying features you get from using the GraphQL type then i think it is better to just return the date as a string. Especially since there is a difference in timestamp and datetime which would be lost in the case of converting to a Date object :) (It is also the simpler solution for now)

**Comment by rijkvanzanten** [comment]
Agreed! Especially because the GraphQLDate type is not even a "native" GraphQL scalar, so I don't think there'll be a lot of external plugins based around that

**Comment by rijkvanzanten** [comment]
![CleanShot 2021-04-09 at 18 43 21@2x](https://user-images.githubusercontent.com/9141017/114247603-7ba2a200-9963-11eb-8503-fd9d9c25261f.png)

🥳
