### ISSUE TITLE
Selected text in Markdown repeators is invisible as the color is very similar to the background.

### ISSUE THREAD

**Issue by TomasSestak** [directus/directus#4947]
![directus markdown](https://user-images.githubusercontent.com/27310585/114233377-7eaa8c00-997d-11eb-9679-8dc901d0c544.png)

It is possible to see the color difference if you really, really zoom the picture onto the first Markdown text

**Comment by benhaynes** [comment]
I fixed this yesterday, it will be in our next release: https://github.com/directus/directus/commit/4ddfc5ef4779c82fb0cece981b2902813697be97
