### ISSUE TITLE
Sorting M2M field does not work

### ISSUE THREAD

**Issue by myzinsky** [directus/directus#4960]
Sortine M2M fields does not work:

<img width="190" alt="image" src="https://user-images.githubusercontent.com/1970554/114269412-2ddf7580-9a07-11eb-810d-7fda6fcacf00.png">

Also it would be nice to have here a kind of tags view.

**Comment by benhaynes** [comment]
This will be closed by:

https://github.com/directus/directus/pull/4093
https://github.com/directus/directus/issues/3647

We'll be using a Display Template, so the sorting won't be an issue any more.
