### ISSUE TITLE
graphql endpoint with no query string no longer works in Directus 9.0.0-rc.54 through 9.0.0-rc.57

### ISSUE THREAD

**Issue by cdanny358** [directus/directus#4965]
Calling `localhost:8055/graphql` in rc.54 through rc.57 returns the following error:

`{"errors":[{"message":"Must provide query string.","extensions":{"code":"INVALID_PAYLOAD"}}]}`

This worked properly in rc.53 and lower.

**Comment by cdanny358** [comment]
To clarify, releases rc.53 and lower returned a GraphiQL screen similar to this. Releases rc.54 and up do not, at least not for me.
![graphiql](https://user-images.githubusercontent.com/390911/114315895-ebc13d00-9ab5-11eb-82aa-e2eb52b29df4.jpg)

**Comment by Jakob-em** [comment]
I think this change is intended. At least @rijkvanzanten wrote on discord:
> [...] We no longer expose GraphiQL by default, so that error is GraphQL saying that you didn't provide a query (which would be correct) [...]

**Comment by cdanny358** [comment]
Well, that's unfortunate. GraphiQL is incredibly useful for figuring out queries. Is there a flag or .env variable to enable it?

**Comment by Jakob-em** [comment]
I don't think so, but you could use an external graphql client like [altair](https://altair.sirmuel.design) or something integrated in your IDE.

**Comment by rijkvanzanten** [comment]
We moved away from express-graphql, which itself shipped with that basic version of GraphiQL. People where already complaining that the shipped version of GraphiQL wasn't advanced enough, or that we should change to _insert personal preference here_, so to me it makes more sense right now to keep those kind of development tools out of the production bundle (we wouldn't ship a copy of Postman either), and (like @Jakob-em mentioned) refer to something like Altair, GraphiQL-online or an extension in your IDE

**Comment by TomasSestak** [comment]
But am I able somehow expose whole schema?
