### ISSUE TITLE
Wrong redirects to custom extensions

### ISSUE THREAD

**Issue by MarcioBarrientos** [directus/directus#4966]
Using rc57

I cant load custom extensions using reverse proxy (I use kong), all is working fine except the custom extensions, it doesn't respect the PUBLIC_URL variable to make the redirect

Directus make this redirects
domain.xyz/app/extensions/displays
domain.xyz/app/extensions/interfaces
domain.xyz/app/extensions/layouts
domain.xyz/app/extensions/modules

to
domain.xyz/extensions/displays/
domain.xyz/extensions/interfaces/
domain.xyz/extensions/layouts/
domain.xyz/extensions/modules/

If i manually open the url domain.xyz/app/extensions/displays/ (with the trailing slash) I can see the extensions list
That happened before with the root path without the trailing slash but with rc57 is fixed with the new ROOT_REDIRECT variable

I don't know if this is the same issue #4733 but is not fixed on rc57

**Comment by MiniDigger** [comment]
this will be fixed by #5015

**Comment by rijkvanzanten** [comment]
Fixed in #5015
