### ISSUE TITLE
Breaking change in `sort` attribute

### ISSUE THREAD

**Issue by ellion** [directus/directus#4970]
Hi everyone,

I ran into some troubles using ```sort``` when querying in my extension on **rc.54**. 

Lets assume I have a collection ```kids``` with the attribute ```name```.

Usually I'd query like this:

```
const service = new ItemsService('kids', { schema: req.schema, accountability: req.accountability });

service
  .readByQuery({ fields: ['name'], sort: 'name' })
  .then((results) => res.json(results.map((item) => { return item.name })))
  .catch((error) => {
    return next(new ServiceUnavailableException(error.message));
  });
```

this does throw a ```query.sort.map is not a function```. I had a deeper look and found this commit:

https://github.com/directus/directus/commit/2a738b7b52cafb1105cc7c51f3caaa312958e8f8#diff-2e2cf1b071c11ed335918d351c9805acf2e17c4d3ff49532a10bfc89111b9ed8

It does in fact change the expected format of ```sort```. So the working version of above query is now:

```
.readByQuery({ fields: ['name'], sort: [ { column: 'name' } ] })
```

Is this expected behavior? From my understanding it's breaking and already published in rc.54.

**Comment by rijkvanzanten** [comment]
Yeah this is expected behavior. We're still tweaking the exact final implementation details for these exposed internals (which is also why they aren't documented yet), so as long as we're in `rc`, keep an eye out for these types of changes 👍🏻
