### ISSUE TITLE
Cant access any assets without a token

### ISSUE THREAD

**Issue by NightlyFlux** [directus/directus#4985]
Tried to access an asset without an access token and got this (I already changed the public permissions to _all_):

_http://localhost:8055/assets/79e03931-e9e5-452b-9516-fcf2ee25897f_

**Response**
`{
  "errors": [
    {
      "message": "An unexpected error occurred.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}`

**Error on console**
```Cannot destructure property 'collection' of 'collectionsRequested.find(...)' as it is undefined. 
TypeError: Cannot destructure property 'collection' of 'collectionsRequested.find(...)' as it is undefined.
    at AuthorizationService.<anonymous> (C:\Users\night\Documents\Projects\Personal\mimenu\node_modules\directus\dist\services\authorization.js:45:25)
    at Generator.next (<anonymous>)
    at C:\Users\night\Documents\Projects\Personal\mimenu\node_modules\directus\dist\services\authorization.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\night\Documents\Projects\Personal\mimenu\node_modules\directus\dist\services\authorization.js:4:12)
    at AuthorizationService.processAST (C:\Users\night\Documents\Projects\Personal\mimenu\node_modules\directus\dist\services\authorization.js:35:16)
    at ItemsService.<anonymous> (C:\Users\night\Documents\Projects\Personal\mimenu\node_modules\directus\dist\services\items.js:215:50)        
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\night\Documents\Projects\Personal\mimenu\node_modules\directus\dist\services\items.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

It seems to work just fine using the access token but the frontend doesn't have a login screen.

---

### Project details
Directus Version: 9.0.0-rc.55
Environment: production
OS: Windows_NT 10.0.19042
Node: 15.14.0

**Comment by rijkvanzanten** [comment]
@NightlyFlux What database is this happening under? Does this happen on all assets, or only a specific one? 

I just setup a fresh installation, but can't reproduce this 🤔

**Comment by NightlyFlux** [comment]
I'm using MySQL, tried with every image in the assets panel and getting the same result

**Comment by rijkvanzanten** [comment]
Could you share a dump of your permissions / db? I'm on mysql too 🤔

**Comment by NightlyFlux** [comment]
Sure man here:
[info.zip](https://github.com/directus/directus/files/6299898/info.zip)

**Comment by rijkvanzanten** [comment]
@NightlyFlux Thanks! There's a bunch of `\n` characters in this CSV export.. Is that an export problem, or are those actually saved in your DB?

**Comment by NightlyFlux** [comment]
They are saved as NULL in the DB

![image](https://user-images.githubusercontent.com/54598567/114465415-53ee4c80-9ba4-11eb-95b3-07f659976cfd.png)

**Comment by rijkvanzanten** [comment]
Ahhh I see. You have 2 rows with the same `role=null collection=directus_files action=read` combo which makes it barf up!

**Comment by rijkvanzanten** [comment]
Removing one of those duplicates directly from the DB will solve it 👍🏻 I'll look into making it ignore duplicates in the meantime

**Comment by NightlyFlux** [comment]
> Removing one of those duplicates directly from the DB will solve it 👍🏻 I'll look into making it ignore duplicates in the meantime

Yup that fixed it! Thanks for the help don't know why it got duplicated but deleting it make it work like a charm again! 👍

**Comment by rijkvanzanten** [comment]
I'll leave this open for a sec while we implement a fix to ignore duplicates like this 👍🏻

**Comment by NightlyFlux** [comment]
Sure man no problem!
