### ISSUE TITLE
Directus slow after update

### ISSUE THREAD

**Issue by nordcart** [directus/directus#4989]
Update from somewhere between v9.0.0-rc.51-53 to 56 made directus slow.

Is there anyway I can troubleshoot?

v9.0.0-rc.57
Postgres 12
Redis 6
Docker Desktop 3.3.0

**Comment by benhaynes** [comment]
Can you be more specific? What pages/routes/requests are slow now? What does your schema look like? Can you give actual latencys for "slow".

**Comment by nordcart** [comment]
I´m using One to many - Many to one fields

Slow on loading data in collections/bookmarks or editing an item. 3-7seconds. Before the update everything was instant.

Where could I easily take a screenshot of the schema?

**Comment by benhaynes** [comment]
You should be able to do a database dump to get the schema (whole DB is ideal for debugging), if it's private you can share over Discord DM: https://directus.chat

**Comment by Oreilles** [comment]
I though I was crazy, but I noticed the same thing.
What's even weirder is that going back and forth between commits to find when it happened exactly, the issue ended up disappearing.

**Comment by rijkvanzanten** [comment]
@Oreilles Could it be this change from 2 weeks ago? https://github.com/knex/knex-schema-inspector/commit/c38d1b7a3165bfd1fdc88161d96ab4598faeec88#diff-241a92bc77a6f7efb5e272de443b7ea90213da7142d15ed3b3fe9d27d867511c That's the only thing that really could affect something like this on a global level within the context of Postgres 🤔

**Comment by zenati** [comment]
<img width="924" alt="Screenshot 2021-04-10 at 12 53 41" src="https://user-images.githubusercontent.com/5849907/114550158-2e277d00-9c62-11eb-864c-5b25bd11c8d6.png">

I'm also having a slow behaviour that blocks the pages. It's like a memory leak somewhere.

**Comment by rijkvanzanten** [comment]
Ohhhhhhhhhhhhhhhhhhhhhh are we talking about an app problem here? I was under the impression something went sideways in the postgres-api side of things. @nordcart @Oreilles can you confirm that this is showing up in the _app_ and _not_ the API?

**Comment by rijkvanzanten** [comment]
@zenati Could you share some insight on how that layout is setup? It could be that one of the displays is causing trouble

**Comment by nordcart** [comment]
> Ohhhhhhhhhhhhhhhhhhhhhh are we talking about an app problem here? I was under the impression something went sideways in the postgres-api side of things. @nordcart @Oreilles can you confirm that this is showing up in the _app_ and _not_ the API?

I can confirm that it's an app issue. Sorry, I should have lead with that.

**Comment by benhaynes** [comment]
I wasn't sure if I was imagining it, but I've noticed some slower loads on Item browse/detail pages after pulling the latest. eg: Listings of 7 items take ~1-2s to load. It seems to "go away", but that's likely the cache.

**Comment by rijkvanzanten** [comment]
@nordcart does this happen consistently on the same collection?

**Comment by Oreilles** [comment]
@rijkvanzanten Yes, it is an app issue !

**Comment by rijkvanzanten** [comment]
Same question to you @Oreilles 😄 Does this happen consistently on the same layout/collection?

**Comment by Oreilles** [comment]
I cannot give you much information unfortunately, as I said going back and forth between tags to find when the issue started, it ended up disappearing by itself. I'm currently working on the `map-layout` branch,  based on tag `rc56` and am not seeing slowdowns anymore.

**Comment by benhaynes** [comment]
Using the demo schema, `Clients` Collection, and moving between pages is the easiest way to reproduce it. I'm seeing the issue on the Table Layout, but it goes away if I only have the `id` column visible... and then comes back when I add other fields/displays to the Table Layout options. With a few fields visible, it takes about 10s for the page to load and unlock.
