### ISSUE TITLE
filter top-level item based on values in m2a-related item

### ISSUE THREAD

**Issue by flicksolutions** [directus/directus#4990]
Hello again! As discussed on [Discord](https://discord.com/channels/725371605378924594/741319183060566077/830453169842683915) last week, I'm trying to filter a request in the following pattern:

```
filter: {
  "relation-table": {
    "item":  {
      "id": {
        "_eq": 1
      }
    }
  }
}
```

The field _relation-table_ is the standard connection-table you get, using a m2a-builder. Its fields are _xx-id_, _collection_, _item_.
The response from the Server is a `500`.

When I try the same request in a o2m-relationship works. Therefore, I think this must be a bug.

My current workaround is to replace the m2a-relation with two separate m2o-relations which is suboptimal.

Thanks for your views on that!

---

### Project details
Directus Version: 9.0.0-rc.57
Environment: production
OS: Linux 5.4.0-70-generic
Node: 14.16.0

**Comment by rijkvanzanten** [comment]
Heya! The filter can't dynamically guess what sub-collection you're trying to filter in, so there's no way for it to know where that `id` field is to be found. That being said, the ID itself is stored on the `item` field within `relation-table`, so you should be able to do:

```js
filter: {
  "relation-table": {
    "item":  {
      "_eq": 1
    }
  }
}
```
