### ISSUE TITLE
Couldn't load custom interface "my-custom-interface"

### ISSUE THREAD

**Issue by mattiaz9** [directus/directus#4994]
I'm trying to register a custom interface but the app throws an error when trying to push the imported module.

This is the error I managed to find:
`TypeError: undefined is not an object (evaluating 'a.value.default')`

Where `a` is the imported module:
`const a = await import(Object(n["b"])() + `extensions/interfaces/${e}/index.js`);`

If I understood it correctly the statement should be: `a.default` not `a.value.default`.

**Comment by fballan93** [comment]
did you try this solution first mentioned by @Mrmiffo in issue #4401 ? it is not official but it worked for me

**Comment by Jakob-em** [comment]
Seems to be related to: https://github.com/directus/directus/pull/4986

**Comment by mattiaz9** [comment]
> Seems to be related to: #4986

yes, looks like it. 
I'm closing this issue. Hopefully it will get merged soon!
