### ISSUE TITLE
Unique error does not tell what is wrong.

### ISSUE THREAD

**Issue by Thomasparsley** [directus/directus#4995]
Hello,
In one of my fields I have marked that value has to be unique. When I try write second same value I get error, but error does not tell what is wrong.
![image](https://user-images.githubusercontent.com/41927757/114374388-e16d7480-9b83-11eb-867d-6ce003e8d70d.png)

Field is string (255) with slug interface, no hooks related for this field,  field has no translations and field is not hidden.

Directus 9.0.0-rc.57
DBMS: MariaDB 10.3.25
Deployment: npx
Browser: Chrome 89 - 64x
Node: 14.16.0
Local VM - Ubuntu 20.10

**Comment by rijkvanzanten** [comment]
I'm wondering if MariaDB has a different error format than MySQL does, causing the extraction to fail 🤔

**Comment by Thomasparsley** [comment]
@rijkvanzanten 
`SQL Error [1062] [23000]: (conn=280) Duplicate entry 'unique-string' for key 'test_UN'`

**Comment by Thomasparsley** [comment]
I checked MySQL and MariaDB error codes and both for duplicate entry use:
Error number: 1062; Symbol: ER_DUP_ENTRY; SQLSTATE: 23000
