### ISSUE TITLE
Limit login attempts

### ISSUE THREAD

**Issue by paescuj** [directus/directus#5003]
I've just noticed that there is currently no limit on login attempts, only a [rate limit for the API](https://docs.directus.io/guides/api-config/#rate-limiting).

I think this should be enabled by default (amount of attempts could be configurable).

**Comment by rijkvanzanten** [comment]
Duplicate https://github.com/directus/directus/issues/2969

**Comment by paescuj** [comment]
Sorry, haven't seen this one.

**Comment by rijkvanzanten** [comment]
No problem!
