### ISSUE TITLE
Auth shouldn't check for access tokens

### ISSUE THREAD

**Issue by WoLfulus** [directus/directus#5011]
The authentication endpoints seems to be handling access tokens as if we are logged in (giving 403), making it impossible to login if an expired/invalid token is given to the auth endpoints.

**Comment by rijkvanzanten** [comment]
@joeinnes actually made a good point here: https://github.com/directus/directus/issues/4883#issuecomment-818156425

> The more I think about it, the more I think that maybe it does make sense for the server to reject a request with an invalid or expired token, and it should be the client's responsibility not to send a request with a bad token

**Comment by rijkvanzanten** [comment]
Lets keep the discussion open here, but I'm leaning towards agreeing with Joe here that it might make more sense to make this the responsibility of the client, not the API 🤔

**Comment by joeinnes** [comment]
If I'm not mistaken, fixing it in the API looks to be as simple as modifying:

https://github.com/directus/directus/blob/119ad0c1ee820a8d1fe3179bbdf04766600a74fd/api/src/middleware/authenticate.ts#L22

to be:

`if (!req.token || req.baseUrl === "/auth") return next();`

(although I haven't actually checked that, it seems like it would do the trick)

**Comment by rijkvanzanten** [comment]
@joeinnes Yeah totally, it shouldn't be too difficult to figure this out properly, but I'm not convinced we should do it in the first place 🤔

**Comment by rijkvanzanten** [comment]
I think I'm erring on the side of consistency here and say that the API will throw an error for invalid tokens regardless of what endpoint is used. This is also in-line with how GraphQL would react, where there isn't a differentiation between different mutations in authentication status.

**Comment by MonksterFX** [comment]
Hey is stumbled over the same issue here.

I'm not able to relogin, with Directus/SDK after token expires because cookie and bearer token will be send with request and the middleware is not allowing to reach /auth.

Do I understand you right that this issue will be fixed in directus/sdk or in the backend it self, or do we have to do it by our self. (I dont have access to the cookies, so how to delete them when they are httpOnly?)

Thanks for clarify this.
