### ISSUE TITLE
Slider label cuts number (missing padding?)

### ISSUE THREAD

**Issue by danieljwestman** [directus/directus#5017]
Directus v9.0.0-rc.57
PG 12
macOS
Safari 14.0.3 (16610.4.3.1.7)

__

![Skärmavbild 2021-04-13 kl  09 27 31](https://user-images.githubusercontent.com/20950568/114513790-dcb7c780-9c3a-11eb-95c3-1b19828bf823.png)

**Comment by YannickMol** [comment]
Can't reproduce this in Chrome, Firefox or Edge, so might be related to Safari?

**Comment by YannickMol** [comment]
@danieljwestman, can you also share the setup of the field's interface?
![image](https://user-images.githubusercontent.com/13256289/114610561-5930c180-9ca0-11eb-8c60-16888dd6ade1.png)

**Comment by danieljwestman** [comment]
![Skärmavbild 2021-04-14 kl  09 38 26](https://user-images.githubusercontent.com/20950568/114672232-3389d380-9d05-11eb-998f-767c0f79da45.png)

**Comment by danieljwestman** [comment]
(Yes, in other browser it works for me too, this seems to be a Safari issue)
