### ISSUE TITLE
The drawer-collection does not emit layout filters to parent component

### ISSUE THREAD

**Issue by Kematia** [directus/directus#5024]
I don't know if I'm using it incorrectly or it's a missing feature, but the drawer-collection does not emit the layout filters.

I have a custom layout which is a tabular layout with a custom interface to add and remove filters. It works fine in the collection view, but the filters do not work when the collection is opened in a drawer inside a custom interface. You can see it here at 6 seconds: 

https://user-images.githubusercontent.com/17851386/114533394-265ddd80-9c4e-11eb-87aa-213ec8e5c8dc.mov

--- 
Adding the following code fixes the issue:

![image](https://user-images.githubusercontent.com/17851386/114529013-d4b35400-9c49-11eb-9fd9-7dcb4eedd2b3.png)

![image](https://user-images.githubusercontent.com/17851386/114529379-2e1b8300-9c4a-11eb-865d-7347cec637ff.png)

If the above code is ok, and I'm using the component correctly I can open a PR for this!

I see the filters are getting passed to the component (and it does work when I set them in the parent component), but they are not getting emitted to the parent component.

**Comment by rijkvanzanten** [comment]
> If the above code is ok, and I'm using the component correctly I can open a PR for this!

Yeah! Go ahead. The only reason why collection-drawer didn't propagate that event is because nothing in Directus itself has that two-way binding for filters 🙂
