### ISSUE TITLE
Extensions unable to load

### ISSUE THREAD

**Issue by georgexchelebiev** [directus/directus#5028]
Custom interface extensions fail to load and `Couldn't load custom interface "<extension_name>"` gets printed in the console.

To reproduce, install a custom interface extensions (I tried both [Directus Dictionary](https://github.com/georgexchelebiev/directus-dictionary) and [Directus Conditional Fields](https://github.com/MiniDigger/directus-conditional-fields)) and navigate to the app.

My environment:
Version: directus v9.0.0-rc.57
DBMS: Postgres 12
Deployed with: Docker
Browsers: Chrome, Firefox, Edge

**Comment by georgexchelebiev** [comment]
This was also mentioned by @sabinehoi in #4859

**Comment by MiniDigger** [comment]
This is fixed by 
https://github.com/directus/directus/pull/4986
and a better error message would be printed by 
https://github.com/directus/directus/pull/5015
