### ISSUE TITLE
Field name problems after duplicating a field 

### ISSUE THREAD

**Issue by iksent** [directus/directus#5030]
1. Create a simple text field ("Name"):
![Снимок экрана 2021-04-13 в 17 09 31](https://user-images.githubusercontent.com/49946588/114550227-64bdc180-9c7b-11eb-9360-e17f60f76b69.png)

2. Duplicate it with another key ("origin")
![Снимок экрана 2021-04-13 в 17 15 25](https://user-images.githubusercontent.com/49946588/114550667-e3b2fa00-9c7b-11eb-8dc1-d88da71a5ce4.png)
PS: See, that default name was not changed ("Name" at the header)

3. Change "Field Name Translations" and save it:
![Снимок экрана 2021-04-13 в 17 09 43](https://user-images.githubusercontent.com/49946588/114550290-74d5a100-9c7b-11eb-98e5-98c7b2bc1ea1.png)

4. And It's not working:
![Снимок экрана 2021-04-13 в 17 09 59](https://user-images.githubusercontent.com/49946588/114550366-89199e00-9c7b-11eb-986c-0f6a92449a2a.png)

### Project details
Directus Version: 9.0.0-rc.57
Environment: production
OS: Linux 5.4.0-66-generic
Node: 14.16.0

**Comment by benhaynes** [comment]
Hey @iksent — I've just tested this on the latest release and things seem to be working for me. Could you just confirm _how_ you duplicated the initial field? Perhaps pul the latest and see if this is still an issue? Here's what I did:

1. Create New Standard (text input): `name`
2. Duplicate the `name` field, rename as `origin`
    * There was one issue: the tooltip for the field name and type were `undefined` (see below). I thought this might be related, but it went away when refreshing the page. To be clear, I did _not_ refresh the page during this process, and it still worked though.
    * I should note that the drawer title _did_ work, and said `Origin` for me. 
3. Add Field Name Translations to `origin`
4. Review on Item Detail... everything looks good!

![Screen Shot 2021-04-21 at 5 45 59 PM](https://user-images.githubusercontent.com/522079/115626635-c90c0100-a2cb-11eb-91a8-860fa01870a6.png)

![Screen Shot 2021-04-21 at 5 46 18 PM](https://user-images.githubusercontent.com/522079/115626657-cf9a7880-a2cb-11eb-86dc-cf8c3447be7c.png)

![Screen Shot 2021-04-21 at 5 56 27 PM](https://user-images.githubusercontent.com/522079/115626683-d6c18680-a2cb-11eb-8acd-b3fc80102530.png)

I will close this for now, as I tried very hard to repeat the issue and couldn't. Let me know if you (or anyone else) has any insight into reproducing.
