### ISSUE TITLE
Add encryption option for mssql

### ISSUE THREAD

**Issue by TheAzack9** [directus/directus#5032]
Azure requires all communication to be encrypted in order to communicate with a MSSQL database. So in order to be able to use a mssql database in Azure is it necessary to add "encryption: true" to the Knex options here: https://github.com/directus/directus/blob/ecd5526b55aaab3b04e20f9e21285df3600b02ca/api/src/cli/utils/create-db-connection.ts#L13-L65.

Optimally would it be nice (for future proofing) that one could somehow pass environmentvariables from .env down to the database, but i'm not quite sure how that would work :) Perhaps doing something like `DB_CONFIG_ENCRYPT=true` or something similar.

More info here: https://github.com/tediousjs/tedious/issues/188

Currently you would only get the following error if you try to set up an mssql database in azure and set it up with `npx directus database install` :)

```
ConnectionError: Server requires encryption, set 'encrypt' config option to true.
    at ConnectionError (C:\Users\robin\Documents\Repos\kvarteret\personaldatabase-eksempel\node_modules\tedious\lib\errors.js:13:12)
    at Message.<anonymous> (C:\Users\robin\Documents\Repos\kvarteret\personaldatabase-eksempel\node_modules\tedious\lib\connection.js:2521:64)
    at Object.onceWrapper (node:events:475:28)
    at Message.emit (node:events:381:22)
    at endReadableNT (C:\Users\robin\Documents\Repos\kvarteret\personaldatabase-eksempel\node_modules\readable-stream\lib\_stream_readable.js:1094:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: 'EENCRYPT'
}
```

**Comment by TheAzack9** [comment]
Huh, actually. Looking into it further it should be passed given that the tedious version is above 6.0.0, which from the package.lock it seems to be... https://tediousjs.github.io/tedious/getting-started.html so not sure why i'm getting an error then 🤔

**Comment by TheAzack9** [comment]
Nvm, seems knex defaults it back to false again: https://github.com/knex/knex/blob/master/lib/dialects/mssql/index.js
Hehe, wild ride :)

**Comment by rijkvanzanten** [comment]
Where in the connectionConfig does this encrypted key go?

> Optimally would it be nice (for future proofing) that one could somehow pass environmentvariables from .env down to the database, but i'm not quite sure how that would work :)

This is already the case! Every `DB_*` env var is passed to the connection config of Knex, so `DB_ENCRYPT="true"` might already work 🙂

**Comment by TheAzack9** [comment]
> Where in the connectionConfig does this encrypted key go?
> 
> > Optimally would it be nice (for future proofing) that one could somehow pass environmentvariables from .env down to the database, but i'm not quite sure how that would work :)
> 
> This is already the case! Every `DB_*` env var is passed to the connection config of Knex, so `DB_ENCRYPT="true"` might already work 🙂

Oh damn! i didn't know :) I tried adding it and worked like a charm! Thanks :) 

Supposedly it goes in the options, so the encryption added would be something like:
```
	connection = {
		host: host,
		port: Number(port),
		database: database,
		user: user,
		password: password,
		options: {
			encrypt: true,
		}
	};
```

But it isn't necessary since the .env solution worked! :) Might be worth adding a note to the docs at some point tho :)

**Comment by rijkvanzanten** [comment]
> Might be worth adding a note to the docs at some point tho :)

You mean like this? 😄 

<img width="824" alt="CleanShot 2021-04-13 at 11 28 24@2x" src="https://user-images.githubusercontent.com/9141017/114578947-62dc0a00-9c4b-11eb-96f2-0901039c0329.png">

**Comment by TheAzack9** [comment]
jeez, i need to learn read too! 😆
