### ISSUE TITLE
Invalid foreign key in SQLite

### ISSUE THREAD

**Issue by SantoshAvaji** [directus/directus#5069]
Hello Team, 
Recently i upgraded from version v9.0.0-rc.45 to v9.0.0-rc.58
After updating to Version: v9.0.0-rc.58
I am not able to login to local directus instance
Getting unexpected error while login in 
Getting  below error 
Request URL: http://localhost:8055/auth/login
and payload : 
`{email: "admin@example.com", password: "admin", mode: "cookie"}
email: "admin@example.com"
mode: "cookie"
password: "admin"`

Response is 
`{"errors":[{"message":"Invalid foreign key.","extensions":{"code":"INVALID_FOREIGN_KEY"}}]}`

DBMS used  local SQLite.

![image](https://user-images.githubusercontent.com/7732953/114835427-2e08b800-9def-11eb-92b2-c50e7f7ecc55.png)

**Comment by rijkvanzanten** [comment]
I just did a fresh installation of Directus on SQLite, and can't seem to reproduce this issue 🤔 

I think that foreign key constraint might be a duplicate ID on directus_activity (for the login method), or maybe an avatar file or role that no longer exists?

Would you be able to share the DB where this is happening?

I'll close it for now as I think it's an issue in the DB, not Directus 🤔

**Comment by joselcvarela** [comment]
I found some problems too when upgrading.
But running `yarn directus database migrate:latest` solved them all.
