### ISSUE TITLE
Collection auto-refresh persistence

### ISSUE THREAD

**Issue by ernst86913** [directus/directus#5073]
New auto-refresh setting in collections view is not persisted as preset... therefore when changing it and navigating to different pages the changes are lost.

---

### Project details
Directus Version: 9.0.0-rc.58
Environment: development
OS: Windows_NT 10.0.18363
Node: 15.9.0

**Comment by rijkvanzanten** [comment]
@ernst86913 Did you migrate the database after upgrading? It's persisting and saving to the `refresh_interval` field as expected on my end

**Comment by ernst86913** [comment]
OK - so that might be an issue then on my side. Sorry. Can you just help me for a second with that.

I am using   "npm run dev" for the application and "npm run dev" for the api to develop in those 2 and avoid creating a separate project and have more insights.... how can I trigger a database migration?   Thanks for you help in advance.

**Comment by rijkvanzanten** [comment]
I would run `npm run dev` from the repo root (it'll spin everything up at the same time). You can use `npm run cli <command>` to run any of the "npx directus" commands from source, so in this case `npm run cli database migrate:latest`

**Comment by ernst86913** [comment]
Thanks a lot!!!

LG,
Roman

Von meinem iPhone gesendet
