### ISSUE TITLE
Image Upload failed: filesize is required

### ISSUE THREAD

**Issue by kmeinke** [directus/directus#5075]
Hello,

sadly the very first thing I tried in directus failed :( 
I just pulled and run the docker image (https://docs.directus.io/guides/installation/docker/) logged in and tried to upload a avatar image for the administrator. i get the error message: validation failed, filesize is required:
![grafik](https://user-images.githubusercontent.com/6384256/114858439-bedc9500-9de9-11eb-80a2-193dea5e306e.png)

The same error occurs if i try to upload something into the file library

do you have a tipp whats going wrong?

kind regards - knut

---

### Project details
Directus Version: 9.0.0-rc.58
Environment: production
OS: Linux 4.19.0-16-amd64
Node: 14.16.1

**Comment by DamienMrtl** [comment]
Same issue after updating to 9.0.0-rc.58 from .53

**Comment by kmeinke** [comment]
thank you :)

**Comment by seanmars** [comment]
@rijkvanzanten I'm update to rc59 but got this issue too

**Comment by rijkvanzanten** [comment]
@seanmars make sure to run the database migrate after you update 👍🏻
