### ISSUE TITLE
Invite user by mail wrong URL in link

### ISSUE THREAD

**Issue by DamienMrtl** [directus/directus#5076]
Using the option to invite users by emails, the link in the received mail does not contain the domain name in the url only the path:  https://admin/accept-invite?token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

It should be : https://my.domain.com/admin/accept-invite?token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

---
Using SMTP to send mails

### Project details
Directus Version: 9.0.0-rc.58
Environment: production
OS: Linux 3.10.0
Node: 14.16.0

**Comment by rijkvanzanten** [comment]
Make sure your `PUBLIC_URL` environment variable matches your actual public url 👍🏻
