### ISSUE TITLE
Translated collection names are missing

### ISSUE THREAD

**Issue by lahdekorpi** [directus/directus#5078]
Translations of collection names are missing in /admin/collections until you open /admin/settings/data-model and navigate back:

![image](https://user-images.githubusercontent.com/570545/114889413-c82e2780-9e12-11eb-8b6e-1dd076a3315a.png)
1. Missing names.

![image](https://user-images.githubusercontent.com/570545/114889503-d9773400-9e12-11eb-8a3f-0562035811c1.png)
2. Navigate to data model.

![image](https://user-images.githubusercontent.com/570545/114889557-e2680580-9e12-11eb-9f9f-00aba4761857.png)
3. Navigate back to collections.

Using MySQL, Node 15.11, Chrome 89

Migrated from a previous version, not sure if that affects this.

**Comment by lahdekorpi** [comment]
Collections without translated names show up correctly. Probably either a race condition with translation loading or not loading them until the data-model is opened?

**Comment by rijkvanzanten** [comment]
> Probably either a race condition with translation loading or not loading them until the data-model is opened?

Exactly this! The call to `i18n.t` to set the name isn't reactive, and the language is set after the i18n.t call is made. I'm updating the set-language logic now to re-init the name translations for collections/fields as well (next to extensions from the other day)
