### ISSUE TITLE
Some interface parts are not translatable

### ISSUE THREAD

**Issue by lahdekorpi** [directus/directus#5079]
Divider titles, help texts and placeholders, including those in project settings by default, are not translatable / translated.

For example in Project settings while the interface is in Finnish:
![image](https://user-images.githubusercontent.com/570545/114893049-fc571780-9e15-11eb-8c19-f130add47e37.png)
"Login & Logo Background" and "Public Pages" are not translated nor translatable in Crowdin.

**Comment by lahdekorpi** [comment]
This is probably a larger issue since there are multiple things not translatable, like the text values of dropdown items, etc.

**Comment by rijkvanzanten** [comment]
@lahdekorpi @Nitwel and I actually just started supporting a special syntax for these things to support making them translatable 🙂 You can now add a `$t:` prefix to the _value_ of interface options, and they'll be treated as a translate key!

The next step for this is going to be to replace all hardcoded English in the system data (like here: https://github.com/directus/directus/blob/07b85b7eb79692c0b0fb063202dd6433a06b18ca/api/src/database/system-data/fields/settings.yaml#L11) with `$t:my_placeholder` strings, and making sure those are in the default English translations: https://github.com/directus/directus/blob/main/app/src/lang/translations/en-US.yaml

Is that something you'd be able to help out with? 😄

**Comment by rijkvanzanten** [comment]
We're also looking into the best way to inject any custom translation key into the "pool" of translations. Right now I'm debating between a `.yaml` file (like an api extension type), or a JSON field in Project Settings. That'll allow you to add custom translations for your own field-interface-options too. Any thoughts on that?

**Comment by lahdekorpi** [comment]
> We're also looking into the best way to inject any custom translation key into the "pool" of translations. Right now I'm debating between a `.yaml` file (like an api extension type), or a JSON field in Project Settings. That'll allow you to add custom translations for your own field-interface-options too. Any thoughts on that?

Why not both?

But at least having the option to handle translations in a file, instead of having to use an interface is a must. Most companies, my company included, uses external tools to manage translations (like Weblate) that can work directly with a git repo.  
So having the translations in a file is quite important.
For smaller companies, however, it may be more user friendly to be able to add those from the UI.

**Comment by rijkvanzanten** [comment]
Having one way is always a little easier to build/maintain/explain, but you're right 👍🏻

**Comment by lahdekorpi** [comment]
> ) with `$t:my_placeholder` strings, and making sure those are in the default English translations: https://github.com/directus/directus/blob/main/app/src/lang/translations/en-US.yaml

These should probably go under fields? For example, the settings would go under `fields.directus_settings`. And if they are just a general word or term used globally, is having them on the root ok?

**Comment by rijkvanzanten** [comment]
Good question 🤔 `fields.<collection>.<field>` is already used dynamically for the field-name translation, so altering that might cause conflicts there. We could add a `field_options.<collection>.<field>` or a similarly named scope?

The root would be preferred for most, unless they're very specific. The more that can be shared the better

**Comment by lahdekorpi** [comment]
> Good question 🤔 `fields.<collection>.<field>` is already used dynamically for the field-name translation, so altering that might cause conflicts there. We could add a `field_options.<collection>.<field>` or a similarly named scope?
> 
> The root would be preferred for most, unless they're very specific. The more that can be shared the better

`field_options` seems like a clear key name.

**Comment by neo7-studio-web** [comment]
Sign-in page as well (when already logged in)
![signin](https://user-images.githubusercontent.com/18073828/115111885-d0a57000-9f82-11eb-9747-8ff82648cd20.jpg)

**Comment by jaycammarano** [comment]
fixed in #7554
