### ISSUE TITLE
Interface components are created before value is fetched

### ISSUE THREAD

**Issue by Oreilles** [directus/directus#5097]
When the interface component is created and attached, the value is not yet fetched, and we don't know if one is going to arrive.

This poses a problem for the Map interface, where we want to initialize the map at the current value location - but for that we need to know if a value is being fetched, so that we know when we can stop waiting for it.

It would be very convenient if we had a `loading` prop for that purpose.

**Comment by rijkvanzanten** [comment]
> This poses a problem for the Map interface, where we want to initialize the map at the current value location - but for that we need to know if a value is being fetched, so that we know when we can stop waiting for it.

One quick additional thought: there's the possibility that the value is changed externally after the interface is already rendered, so we'll have to take re-renders based on value changes into account here too

**Comment by Oreilles** [comment]
> One quick additional thought: there's the possibility that the value is changed externally after the interface is already rendered, so we'll have to take re-renders based on value changes into account here too

Can this happen ? What is the behaviour in other interfaces when there is a conflict between the two values ?

**Comment by rijkvanzanten** [comment]
The main use case (which is not currently a thing yet) is that one field can dynamically set/update the field of another value. You can imagine that a future map interface field might set a lat/long in 2 different columns that are configured. We'll have to keep in mind that the value could be set by external factors.

There shouldn't be a conflict in values, as it's considered an override, and props shouldn't necessarily be an issue, cause it should every only be in the context of the current edit form

**Comment by Oreilles** [comment]
There was many thing I have to though when implementing the map layout, which I though wouldn't be a problem in the interface because switching from an item edit page to another item one's necessarily involves a component unmount.

If the component properties (including the current value) may change while the component is mounted, then there are many thing to change is the current interface implementation. Should I care about it for now ?

**Comment by rijkvanzanten** [comment]
I think it should be safe for the foreseeable future to ignore changes in the props/options, but it would be nice to be aware of potential changes in "runtime" on the `value` prop 👍🏻
