### ISSUE TITLE
On update a wysiwyg field inside translation images are not saved

### ISSUE THREAD

**Issue by gitllermopalafox** [directus/directus#5118]
When update a wysiwyg field inside translations, images are not saved.

Steps to reproduce this issue:

1. Create a collection and Set up translations
2. Inside of translations add a wysiwyg field
3. Save the collection
4. Create an item of this collection
5. Set a translation and select an image inside wysiwyg field
6. Save the item (At this point, everything is fine)
7. Edit the last item created
8. Edit a translation and select an image inside wysiwyg field, then save
9. Edit a translations again and you'll notice the image inside the wysiwyg wasn't saved

---

### Project details
Directus Version: 9.0.0-rc.59
Environment: local
OS: macOS High Sierra (10.13)
Node: 15.6.0

**Comment by Mrmiffo** [comment]
This seems similar, but not the same as this: https://github.com/directus/directus/issues/5142

Maybe the same workaround could work here?

**Comment by rijkvanzanten** [comment]
@Mrmiffo I think you're right. Sounds to me like the changes from the modals aren't correctly triggering the events 👍🏻 

I'll close this in favor of #5142 as I believe the underlying problem to be the same
