### ISSUE TITLE
Custom Translations field is broken after updating it

### ISSUE THREAD

**Issue by mattiaz9** [directus/directus#5121]
After creating a translations field with custom relationships I cannot change the fields without the app resetting it.

Basically after creating the translations field the relationships are disabled and reset to the default field names, hence when I save the field again, the columns names are changed to non existing columns, breaking the translations.

To reproduce:
 - create a custom translations field
 - customise the columns name to be different than the default ones
 - save
 - click again on the field to edit it
 - save
 - now the translation field is broken 

PS: I used migrations to create the tables.

<img width="831" alt="Screenshot 2021-04-17 at 14 18 48" src="https://user-images.githubusercontent.com/9766700/115112943-13b61200-9f88-11eb-92c9-7b34d22e7d21.png">

**Comment by Mrmiffo** [comment]
Same as this issue: https://github.com/directus/directus/issues/3361
