### ISSUE TITLE
When changing toolbar in WYSIWYG in interface tab, the image upload is broken

### ISSUE THREAD

**Issue by TomasSestak** [directus/directus#5125]
**WITH DEFAULT OPTIONS:**
![Screenshot 2021-04-17 at 17 15 15](https://user-images.githubusercontent.com/27310585/115117902-1e30d580-9fa1-11eb-8365-89ef1e646e37.png)

**WHEN CHANGING TOOLBAR OPTIONS:**
![Screenshot 2021-04-17 at 17 15 42](https://user-images.githubusercontent.com/27310585/115117900-1709c780-9fa1-11eb-852c-8d72e1598f31.png)
 

RC57

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/directus/pull/4962

**Comment by TomasSestak** [comment]
I'm sorry I updated the version to 59 and then changed the options but both the image and media buttons dissappeared from toolbar in WYSIWYG

**Comment by TomasSestak** [comment]
I got it back by changing the _custom-image_ and _custom-media_ to _image_ and _media_ in db

**Comment by TomasSestak** [comment]
related to #5155 ?
