### ISSUE TITLE
User page not found on non admin access

### ISSUE THREAD

**Issue by NightlyFlux** [directus/directus#5130]
Just updated to RC.59 and the permissions started failing, wasn't able to check my assets or my user page even with the permissions turned on, only the collections were working.
I thought it was because of the update so I created a brand new project and the error kept appearing.

Steps to reproduce:
1. Create a new directus project
2. Create a new role with admin access unchecked (only app access)
3. Add a new user to the role
4. Log in using the new user, try to go the user module(http://localhost:8055/admin/users/{user id})

![image](https://user-images.githubusercontent.com/54598567/115133000-133a6d00-9fc2-11eb-9c6a-e70e1ab314dd.png)

---

### Project details
Directus Version: 9.0.0-rc.59
Environment: production
OS: Windows_NT 10.0.19042
Node: 15.14.0
Database: MySQL

**Comment by lemankk** [comment]
Found the same result, and also cannot access Files from navigation even file & folder have all access.

**Comment by Feuerhamster** [comment]
Same Issue here.

Directus version: v9.0.0-rc.57
Environment: Production
Database: Postgres
Deployment: Docker

**Comment by d-schoenfeld** [comment]
Same here.

Directus Version: 9.0.0-rc.59
Environment: production
OS: Debian GNU/Linux 10 (buster)
Node: v14.16.1
Database: MySQL

**Comment by rakanus** [comment]
same issue with me , 
can you publish a release ? (for Docker)

**Comment by rijkvanzanten** [comment]
@rakanus we'll be publishing a release later today. You can always rollback to 58 until that's out 👍🏻

**Comment by h2bear** [comment]
Hi @rijkvanzanten are there any news on this topic?
I ran into the same problem, do you know when the new release will expected to be out?

Best regards and thanks for your effort!

**Comment by rijkvanzanten** [comment]
@h2bear We had a couple other things on the rc.60 to-do list, all of which are now completed 🙂 Just doing some last checks to make sure everything is as it should be, and it'll go live 👍🏻
