### ISSUE TITLE
Invite user 500 error

### ISSUE THREAD

**Issue by aleksejssaburovs92** [directus/directus#5135]
Try to invite user, expected email will be sent
Actual result: 

```json
{
  "errors": [
    {
      "message": "write EPIPE",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

```
directus    | 09:51:15 🚨 write EPIPE 
directus    | Error: write EPIPE
directus    |     at afterWriteDispatched (internal/stream_base_commons.js:156:25)
directus    |     at writeGeneric (internal/stream_base_commons.js:147:3)
directus    |     at Socket._writeGeneric (net.js:785:11)
directus    |     at Socket._write (net.js:797:8)
directus    |     at writeOrBuffer (_stream_writable.js:352:12)
directus    |     at Socket.Writable.write (_stream_writable.js:303:10)
directus    |     at LeWindows.ondata (_stream_readable.js:719:22)
directus    |     at LeWindows.emit (events.js:315:20)
directus    |     at LeWindows.EventEmitter.emit (domain.js:486:12)
directus    |     at addChunk (_stream_readable.js:309:12)
directus    | 09:51:15 ✨ request errored POST 500 /users/invite 74ms
```

Version: v9.0.0-rc.59
Installation and running: Docker (docker-compose)
DB: Postgres 12
OS: macOs Catalina

env variables for email:
EMAIL_FROM="no-reply@directus.io"
EMAIL_TRANSPORT="sendmail"
EMAIL_SENDMAIL_NEW_LINE="unix"
EMAIL_SENDMAIL_PATH="/usr/sbin/sendmail"

![Screenshot 2021-04-19 at 12 54 50](https://user-images.githubusercontent.com/12848012/115217747-79cca180-a10e-11eb-9f5d-649cd1788e85.png)

![Screenshot 2021-04-19 at 12 55 38](https://user-images.githubusercontent.com/12848012/115217834-8fda6200-a10e-11eb-99fc-c4d8ec776672.png)

**Comment by rijkvanzanten** [comment]
Are you sure `sendmail` exists and works at that configured path? `EPIPE` in Node means that the receiving end closed the connection/process, so my best guess is that it's the configuration between Directus and `sendmail` 👍🏻 

(I'll close this for now, as I'm fairly sure it's a configuration problem. We can reopen if there's a problem in the email handling of Directus)
