### ISSUE TITLE
I'm unable to save tags of File

### ISSUE THREAD

**Issue by TomasSestak** [directus/directus#5140]
Hi,

it's me again, first, thank you for your work on Directus.

https://docs.directus.io/reference/api/system/files/
Docs say that tags are supposed to be CSV format but in the json it's displayed as string. But the problem is that I'm unable to  save the field with string. 

RC59

**Comment by rijkvanzanten** [comment]
It's an Array of strings 👍🏻 I'll update the docs to match

**Comment by TomasSestak** [comment]
Oh i see, I have to press enter to add Tag :))
