### ISSUE TITLE
User invite error message for existing invite

### ISSUE THREAD

**Issue by wahyuhenditya** [directus/directus#5157]
### The issue
When tried to invite existing users, it shown error message `Cannot read property 'startsWith' of undefined`
![image](https://user-images.githubusercontent.com/67947626/115355618-08abed80-a1e5-11eb-822c-2dc0577d1794.png)

### Expected
Shown proper error message like "User/Email already existed/invited"

### Reproduce Step
1. Go to `User Directory`
2. Click `User Invite` button
3. Input existing emails on `Emails` field
4. Click `Submit` button

### Environment
Version:  Directus 9.0.0-rc.58 
DBMS: MySQL
Deployment: Docker
Browser: Google Chrome 89.0.4389.128

**Comment by rijkvanzanten** [comment]
I'm seeing the correct error under rc.60 👍🏻 

<img width="685" alt="CleanShot 2021-04-23 at 18 36 34@2x" src="https://user-images.githubusercontent.com/9141017/115936303-dd363680-a462-11eb-9212-796e538d314d.png">

That being said, we can make this a little nicer by looking for `RECORD_NOT_UNIQUE` errors and presenting them in a nicer error message

**Comment by benhaynes** [comment]
Confirming this happens on MySQL (`5.7.26`)

**Comment by rijkvanzanten** [comment]
Must be a difference in MySQL 5.7 v 8.x 👍🏻
