### ISSUE TITLE
Filesize is required - while uploading file

### ISSUE THREAD

**Issue by BartCRMstrategen** [directus/directus#5163]
1) The issue and what you expected to happen
    When i try to upload an image, i get the following error:
    
    ![image](https://user-images.githubusercontent.com/77833517/115404709-deaaf900-a1ed-11eb-8904-c6ab0e7102e8.png)

    When i take a look in my google console is see this response:
    {"errors":[{"message":"\"filesize\" is required","extensions":{"code":"FAILED_VALIDATION","field":"filesize","type":"required"}}]}
    The expected output is an uploaded image!
2) Exact steps to reproduce this issue
   Upload an image (.png) in the files section

3) Your environment:
    What version of Directus you are using: v9.0.0-rc.59
    Which DBMS are you using: Postgres 13.1
    Which deployment are you using npx
    What browser are you using Chrome Version 90.0.4430.72 (Official Build) (64-bit)
    I have no hooks or extensions based on the files.

**Comment by BartCRMstrategen** [comment]
probably same issue as https://github.com/directus/directus/issues/5075

**Comment by benhaynes** [comment]
Yup!
