### ISSUE TITLE
Unable to add child item in M2A reference with Graphql mutation query

### ISSUE THREAD

**Issue by SPJames** [directus/directus#5174]
1. Problem
When following the [API Reference docs](https://docs.directus.io/reference/api/introduction/#one-to-many-many-to-many-many-to-any) I would expect when using a mutation query I'm able to add a child item to a M2A reference. However this causes an error.
I have an item called Pages, which contains a M2A reference to multiple types of layout items. Using the following graphql mutation query I would expect it would create a new M2A reference: 

```graphql
mutation {
   update_pages_item(id: <PAGE_ID>, data: {
     layouts: [<NEW_LAYOUT_ID>]
   }) {
     id
   }
}
``` 

This query throws the following error: 

```json
{
   "message":"GraphQL validation error.",
   "extensions":{
      "code":"GRAPHQL_VALIDATION_EXCEPTION",
      "graphqlErrors":[
         {
            "message":"Expected value of type ""update_pages_layouts_input"", found 20.",
            "locations":[
               {
                  "line":4,
                  "column":21
               }
            ]
         }
      ]
   }
}
```

2. Reproduce
In order to reproduce this first create an item which will get a M2A reference to at least 2 items.
Create the 2 child items. Add them to the M2A reference.
Using an external Graphql tool use the mutation query above to insert a newly created child item into the M2A reference.

3. Versions:
Version 9.0.0-rc59 (but this problem has been there from the version 9.0.0-rc54 when the Graphql 2.0 was introduced)
Postgres 12
Running in Docker (directus and database are different containers)

4. Extra information
I'm creating a webapp using Angular, however I don't think this has any impact.

**Comment by rijkvanzanten** [comment]
I believe that `layouts` in this example is a o2m to the junction table (presumably named something like `pages_layouts`. Have you tried:

```graphql
mutation {
	update_pages_layout(data: {
		layouts: [
			{
				layouts_id: <NEW_LAYOUT>
			}
		]
	}) {
		id
	}
}
```

?
