### ISSUE TITLE
Current user API responses are cached

### ISSUE THREAD

**Issue by paescuj** [directus/directus#5175]
# Issue
I'm using the JS SDK and noticed that the responses from `directus.users.me.read()` ("/users/me" API route) are getting cached by the browser. Using Directus v9.0.0-rc.59 and Firefox.

The retrieved `Cache-Control` header looks like this:
```
Cache-Control: private, max-age=537933
```

This is a problem, e.g. with the following scenario:
1. Login as user A
2. Fetch user infos (-> is now in cache)
3. Logout and login as user B
4. Fetch user infos (-> getting infos about user A instead of user B)

There might be other API routes / scenarios which are affected by the same issue.

# Proposal
I think this could be solved by sending the following `Cache-Control` header:
```
Cache-Control: no-cache
```
Which means the response can still be cached but will be revalidated.

**Comment by rijkvanzanten** [comment]
I'm wondering if we should hard-code the header into certain methods of the SDK, or if we should have a dedicated way to override the options / headers on a per-request level 🤔 

It feels a little nicer to me personally to have something like

```js
directus.users.me.read({ cache: false });
```

or

```js
directus.users.me.read({ headers: { 'Cache-Control': 'no-cache' })
```

@WoLfulus thoughts?

**Comment by WoLfulus** [comment]
By default the SDK caching should be completely disabled, but while having control on a per-request level is nice, I'm not sure right now how much stuff will change, I'll have to check.

What we can do is accept an optional default caching behavior (enabled/disabled) as an option in the SDK constructor, and have a cache flag on the requests that overrides it if specified, but again, I'll have to check the second part.

**Comment by paescuj** [comment]
While some cache options on the client side (SDK) would be nice, I think this is something which should be addressed on the server side (at least in the case of the "/users/me" API route) - it just doesn't make sense to send `Cache-Control: private, max-age=...` here IMO.
If I understand it correctly, setting the header to `Cache-Control: no-cache`  would be a good solution, because responses can still be cached, but would be revalidated.

**Comment by rijkvanzanten** [comment]
> server side (at least in the case of the "/users/me" API route) - it just doesn't make sense to send Cache-Control: private, max-age=... here IMO.

I don't agree it's something that should be different on a route-by-route basis. The same applies when you're fetching data based on a current user and permissions set. 

That being said, one could argue that `Cache-Control: no-cache` should be used instead of `Cache-Control: private` for authorized requests, regardless of endpoint. Would you agree with that @paescuj

**Comment by paescuj** [comment]
> I don't agree it's something that should be different on a route-by-route basis. The same applies when you're fetching data based on a current user and permissions set.

You're right - there might be different cache behaviors on route-by-route basis.

> That being said, one could argue that Cache-Control: no-cache should be used instead of Cache-Control: private for authorized requests, regardless of endpoint. Would you agree with that @paescuj?

Generally, I think it would make more sense to use `Cache-Control: no-cache` for authorized requests - although I'm not sure whether Directus has already implemented some cache-logic...

**Comment by rijkvanzanten** [comment]
This is not affecting the internal cache, so that's good. The main issue here is that the browser is caching the authenticated request, which we should probably avoid like you suggest 👍🏻

**Comment by paescuj** [comment]
> This is not affecting the internal cache, so that's good. The main issue here is that the browser is caching the authenticated request, which we should probably avoid like you suggest 👍🏻

Okay! Yup, that would be great 👍🏻

**Comment by paescuj** [comment]
Wow, thanks for the quick fix! Exactly as I imagined it.
