### ISSUE TITLE
M2M when deselect relation, just make NULL one side instead of deletion

### ISSUE THREAD

**Issue by yellowBanano** [directus/directus#5195]
When try to deselect record in the interface, it disappears, but in the database, it just makes NULL, instead of full deletion. In my case, it broke NOT NULL validation. I think it adds junk data with further unique index unexpected validation errors
![изображение](https://user-images.githubusercontent.com/32203047/115743313-3a19ea00-a39a-11eb-96f4-77fc24bb3ee5.png)

My env: 
DB -- MySQL 8
Deployment -- npx
Browser -- latest Mozilla Firefox

**Comment by benhaynes** [comment]
Hey @yellowBanano — I believe this is a duplicate of https://github.com/directus/directus/issues/2942 — which covers cascading deletes that will give additional options for how these orphans get handled.
