### ISSUE TITLE
Server crash somehow in GET /

### ISSUE THREAD

**Issue by Goxiaoy** [directus/directus#5206]
I am using directus `v9.0.0-rc.59`. And the server crashed once with the following stacktrace. This was triggered by end users, so I do not know how to reproduce this 

```
01:14:32 ✨ request completed GET 302 / 2ms
internal/url.js:259
  throw new ERR_INVALID_URL(input);
  ^

TypeError [ERR_INVALID_URL]: Invalid URL: http://
    at onParseError (internal/url.js:259:9)
    at new URL (internal/url.js:335:5)
    at new URL (internal/url.js:332:22)
    at /app/node_modules/directus/dist/server.js:66:29
    at /app/node_modules/lodash/lodash.js:10118:25
    at Object.onceWrapper (events.js:421:28)
    at ServerResponse.emit (events.js:327:22)
    at onFinish (_http_outgoing.js:766:10)
    at callback (internal/streams/writable.js:513:21)
    at afterWrite (internal/streams/writable.js:466:5) {
  input: 'http://',
  code: 'ERR_INVALID_URL'
}
```

I see some updates in latest `v9.0.0-rc.60`, but it seems it is still unsafe to use `url.parse`
https://github.com/directus/directus/blob/d9b0fc1e339419a9ae4fd954b9e8a6edc4b3bdd8/api/src/server.ts#L40

**Comment by rijkvanzanten** [comment]
> I see some updates in latest v9.0.0-rc.60, but it seems it is still unsafe to use url.parse

This was indeed resolved in rc.60. 

> but it seems it is still unsafe to use url.parse

How so? Always open to suggestions 👍🏻

**Comment by Goxiaoy** [comment]
This issue should be fixed in rc.60
`url.parse`  is not recommend to use. I thought it was deprecated, but it seems to deprecation revoked

https://nodejs.org/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost
