### ISSUE TITLE
The default behavior of image uploading in WYSIWYG will cause security issue

### ISSUE THREAD

**Issue by Goxiaoy** [directus/directus#5216]
The token is automatically inserted into url link when someone uploads assets in WYSIWYG interface, which may cause token leak. And also, this behavior is different from MarkDown interface
https://github.com/directus/directus/blob/2ca5fdb86c3f8793408ecdb12cad6fdad6fc7ecb/app/src/interfaces/wysiwyg/useImage.ts#L62-L71

**Comment by rijkvanzanten** [comment]
It seems to be assumed that the token option of the wysiwyg interface is set. However, when it's not, it's defaulting to the current user's token, which isn't wanted (@Nitwel)
