### ISSUE TITLE
Update an item from a singleton model return an error (only on v9.0.0-rc.60)

### ISSUE THREAD

**Issue by johackim** [directus/directus#5217]
1) The issue and what you expected to happen

Admin panel return error when I save/update an item from a singleton model : 

`There were validation errors for the following hidden fields: data: validationError.FAILED_VALIDATION`

2) Exact steps to reproduce this issue

- Create a new collection with singleton mode enable (/admin/settings/data-model/+)
- Update an item from your new collection (/admin/collections/my-new-collection)
- An error appear : `There were validation errors for the following hidden fields: data: validationError.FAILED_VALIDATION`

3) Your environment:

docker run -p 8055:8055 directus/directus:v9.0.0-rc.60

4) Any other relevant information we might need to reproduce this issue

This error ONLY appear on the last version of directus : v9.0.0-rc.60

**Comment by rijkvanzanten** [comment]
Closed in https://github.com/directus/directus/pull/5209
