### ISSUE TITLE
Hidden Collections are always visible to users with limited permissions

### ISSUE THREAD

**Issue by DamienMrtl** [directus/directus#5223]
When enabling custom colections navigation in role settings it doesn't limit access to hidden collections when the user right clicks on the collection list in side panel.

When settings read permission to OFF on the role, it correctly hides the collections, but then the relations aren't working and the user can't access data in nomal non-hidden collections (error in console).

---

### Project details
Directus Version: 9.0.0-rc.60
Environment: production
OS: Linux 3.10.0
Node: 14.16.0

**Comment by rijkvanzanten** [comment]
What you're describing is exactly how it's supposed to work 🤔 

Hidden collections are only hidden from sight in the sidebar for convenience reasons, not for permissions reasons. 

What you're asking about sounds like https://github.com/directus/directus/discussions/3144 to me—the ability to allow read permissions but only if you're coming "through" a relational field

**Comment by DamienMrtl** [comment]
Yes for the permission part I agree, its the same as #3144.

But the behavior I find very strange is that I can limit access to some collections by defining "custom colections navigation" and selecting only the collections I want shown to the user. But this doesn't disable visibility of hidden collections.

I think when defining colection navigation it should also hide access to hidden collections.

**Comment by rijkvanzanten** [comment]
> is that I can limit access to some collections by defining "custom colections navigation" 

That's the misunderstanding here. You can't _limit access_ by defining a custom navigation structure, it's just that: a custom structure for the navigation. Limiting access is done through permissions 🙂
