### ISSUE TITLE
O2M can't save more than one item

### ISSUE THREAD

**Issue by mcqua007** [directus/directus#5224]
**1) The issue and what you expected to happen**

Issue arises when  trying to use one to many relationship. I  expect to create a one to many relationship and adding multiple selections (add existing) will save to the record. IIf I try and select multiple items to save (I.e. have a post that has o2m tags field, saving 2 tags to the post). If I save then go back in to look at the saved data only 1 tag is saved. Another issue, If I have on tag saved then try and create another. It creates blank tag. 

**2) Exact steps to reproduce this issue**

Example create a posts collection and a tags collection. Create a o2m field on posts in reference to tags. So one post can have many tags. Using the foreign key  tags.id. Go to tags and create a few tags. Then go to posts to select tags to save to a post. Then try creating a new tag while you have one already selected.

**3) Your environment:**

What version of Directus you are using? v9.0.0-rc.60
Which DBMS are you using ? MySQL
Which deployment are you using ? npx
What browser are you using (Chrome 87, Safari 14, ...)? chrome 90

**Comment by rijkvanzanten** [comment]
> Using the foreign key tags.id

This sounds like you're using the primary key of `tags` as the foreign key field that holds the primary key for `posts`, which might cause all sorts of trouble.

When I setup your example using the following relation:

<img width="621" alt="CleanShot 2021-04-23 at 17 48 57@2x" src="https://user-images.githubusercontent.com/9141017/115933126-40709a80-a45c-11eb-8cfb-ff579928dff4.png">

everything seems to work as expected 👍🏻
