### ISSUE TITLE
API URL

### ISSUE THREAD

**Issue by altezza04** [directus/directus#5247]
According to the doc

https://docs.directus.io/reference/sdk/#get-set-api-url

`// Get the API base URL
console.log(directus.url); // => https://api.example.com/

// Set the API base URL
directus.transport.url = 'https://api2.example.com';`

However only 'directus.transport.url' work in RC60

**Comment by WoLfulus** [comment]
Thanks!

Closed in https://github.com/directus/directus/commit/63c45a6ae4cbfa20064808d4002e2f5fc8269a9f
