### ISSUE TITLE
Can't PATCH user via REST-API on RC60

### ISSUE THREAD

**Issue by Kinzi** [directus/directus#5257]
1) The issue and what you expected to happen
After updating to latest RC60 (from 45) and migrating DB my app fails to patch the user table via API:

PATCH /users/:id

I get a 403:

```
{
    "errors": [
        {
            "message": "You don't have permission to access this.",
            "extensions": {
                "code": "FORBIDDEN"
            }
        }
    ]
}
```

This used to work with the previous version (rc45). I used to have custom policies in place, but even with full access I get the error. I can still GET.

<img width="842" alt="Bildschirmfoto 2021-04-26 um 17 29 18" src="https://user-images.githubusercontent.com/6689405/116100421-8ffdd300-a6b5-11eb-8feb-250a31cab9fd.png">

Your environment:
    D9_RC60
   MySQL
    npx on Dokku

**Comment by WoLfulus** [comment]
This is probably related to #5207 , can you try using SDK at .59 instead and check if it works?

**Comment by Kinzi** [comment]
@WoLfulus 

Nope, this is a straight REST API request.

However, I also have similar trouble now in a custom REST endpoint of mine which is using the SDK I guess?!?

It's the same user role as above with full privileges:
```
const userDBservice = new UsersService({
        accountability: req.accountability,
        schema: req.schema,
      });
      ```
      
    A request that used to work previously now returns empty. I need to initiate the service without accountability for it to work:
    
    ```
    const newUser = await userDBservice.readByQuery({
        filter: { email: { _eq: req.body.email } },
      });
      ```

**Comment by Kinzi** [comment]
This fails even when I give public full access to update directus users...
