### ISSUE TITLE
Image preview in WYSIWYG : Couldn't extract EXIF information from file 

### ISSUE THREAD

**Issue by fballan93** [directus/directus#5274]
when upload any image through WYSIWYG preview is broken . i can see the file uploaded successfully and can see it in the file manager but not in preview. i thought it was an issue connecting to my azure blob . so i changed it back to local . and still face the same issue 

2021-04-27T09:22:36.826924941Z 09:22:36 ⚠️  Couldn't extract EXIF information from file
2021-04-27T09:22:36.827290953Z 09:22:36 ⚠️  Invalid EXIF data: buffer should start with "Exif".
2021-04-27T09:22:36.870591911Z 09:22:36 ✨ request completed POST 200 /files 489ms

Directus v9.0 rc61
Azure app service instance
MySQL DB
npx deployment

**Comment by rijkvanzanten** [comment]
What is the file you're trying this with? Sounds familiar to https://github.com/directus/directus/issues/3535

**Comment by fballan93** [comment]
> What is the file you're trying this with? Sounds familiar to #3535

Literally every image extension. or typically any file . first i thought it is my azure blob. but when i open the files module every single image is their with the thumbnail . and the same env file was used since rc 48

**Comment by fballan93** [comment]
I would like to note that Im using Azure Blob as the File storage . and would like to highlight that it working flawlessly because i can see all the file in the file manager and when previewing too . I tried to debug by changing it to the local storage but still the same issue

**Comment by rijkvanzanten** [comment]
@fballan93 To confirm, this only happens when uploading through the WYSIWYG?

**Comment by fballan93** [comment]
> @fballan93 To confirm, this only happens when uploading through the WYSIWYG?

yes only when uploading via WYSIWYG. and the file is uploaded successfully and i can see it in the fiel manager however preview is broken inside the item in collection and even after uploading and btw i tried many formats jpeg and png with diffrent dimensions and sizes

<img width="948" alt="CleanShot 2021-04-27 at 23 50 22@2x" src="https://user-images.githubusercontent.com/9093101/116311028-6aef8a00-a7b3-11eb-8399-bdbf39e8eb9c.png">

<img width="966" alt="CleanShot 2021-04-27 at 23 50 45@2x" src="https://user-images.githubusercontent.com/9093101/116311038-6e831100-a7b3-11eb-9682-36e8d9c46f6c.png">

**Comment by rijkvanzanten** [comment]
Ohh I see. I think you're missing the `token` option in the WYSIWYG interface. That controls what token is added to the images within the wysiwyg interface, and thus the HTML output stored to the database. If you don't want to add a token to the actual source, you can make read access to `directus_files` publicly available so files can be read regardless of user 👍🏻
