### ISSUE TITLE
Can't save emojis with MySQL

### ISSUE THREAD

**Issue by johackim** [directus/directus#5297]
1) The issue and what you expected to happen

Directus does not save emojis with MySQL.

```
{
  "message": "insert into `test` (`test`) values ('test🔒qwdqwd') - ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\\xF0\\x9F\\x94\\x92qw...' for column `directus`.`test`.`test` at row 1",
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR"
  }
}
```

2) Exact steps to reproduce this issue

- Create a collection "test" with a text field "test".
- Create a new item with an emoji like "🔒".

3) Your environment:

- Directus -> v9.0.0-rc.61
- MySQL -> 5.7.34 (or MariaDB 10.5.9)
- Docker -> 20.10.6

4) Any other relevant information we might need to reproduce this issue

My database, table, and field are all set to use utf8-mb4 charset and encoding :

```
MariaDB [directus]> SELECT default_character_set_name FROM information_schema.SCHEMATA S WHERE schema_name = "directus";
+----------------------------+
| default_character_set_name |
+----------------------------+
| utf8mb4                    |
+----------------------------+
1 row in set (0.001 sec)

MariaDB [directus]> SELECT CCSA.character_set_name FROM information_schema.`TABLES` T, information_schema.`COLLATION_CHARACTER_SET_APPLICABILITY`CCSA WHERE CCSA.collation_name = T.table_collation AND T.table_name = "test";
+--------------------+
| character_set_name |
+--------------------+
| utf8mb4            |
+--------------------+
1 row in set (0.002 sec)

MariaDB [directus]> SELECT character_set_name FROM information_schema.`COLUMNS` WHERE table_name = "test" AND column_name = "test";
+--------------------+
| character_set_name |
+--------------------+
| utf8mb4            |
+--------------------+
1 row in set (0.002 sec)
```

```yml
# docker-compose.yml
# ....
mariadb:
  image: mariadb:10.5.9
  command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
# ....
```

**Comment by rijkvanzanten** [comment]
@johackim [`mysql` seems to have a dedicated `charset` option for the connection](https://www.npmjs.com/package/mysql#connection-options). This should be fixed by setting this option using `DB_CHARSET="utf8mb4_unicode_ci"` 👍🏻

**Comment by johackim** [comment]
Thanks !

`DB_CHARSET="utf8mb4"` works for me ;)

**Comment by justrealmilk** [comment]
I'd propose making a note of this in the docs

**Comment by rijkvanzanten** [comment]
@justrealmilk Where would you deem most appropriate? 🤔 Could go under "env vars", or maybe under a new "Notes on different database vendors" section (we'll have to have more database specific explainers, for timezones, geometry types, etc) (cc @jacobrienstra)

**Comment by justrealmilk** [comment]
> @justrealmilk Where would you deem most appropriate? 🤔 Could go under "env vars", or maybe under a new "Notes on different database vendors" section (we'll have to have more database specific explainers, for timezones, geometry types, etc) (cc @jacobrienstra)

**Prominently** under _Environment Variables, Database_. Maybe even prior to _Additional Database Variables_. It'd also be great to better highlight _Environment Variables_ from the relevant _Getting Started_ sections but that's for another day.

**Comment by rijkvanzanten** [comment]
> Prominently under Environment Variables, Database.

Hmm yeah, the only issue I have with that is that it's only applicable to MySQL specifically 🤔

**Comment by justrealmilk** [comment]
> > Prominently under Environment Variables, Database.
> 
> Hmm yeah, the only issue I have with that is that it's only applicable to MySQL specifically 🤔

Fair point but if there are any other database-specific variables it would make sense... Whether there are any is beyond me though 😅

**Comment by rijkvanzanten** [comment]
We'll track that here: https://github.com/directus/directus/issues/7702 Lemme know if you have any other ones that would be useful to add 🙂
