### ISSUE TITLE
Incorrect header in drawer for new items in relational interfaces

### ISSUE THREAD

**Issue by danieljwestman** [directus/directus#5326]
macOS Big Sur (M1)
Directus 9.0.0-rc.61
PG 12
Node v15.14.0

--

Something funky in the m2a interface (and maybe other relation interfaces). The header in the drawer is acting weird when creating new items (clicking button **Create New**).

1. Go to an item with a m2a interface
![Screenshot of Editing Item in Settings](https://user-images.githubusercontent.com/20950568/116416433-9f5a5900-a83a-11eb-9e0d-fbd68d1675e8.jpg)

2. Click on **Create New** button. 
![Screenshot of Editing Item in Settings (1)](https://user-images.githubusercontent.com/20950568/116416576-be58eb00-a83a-11eb-9b12-15da399b28ac.jpg)

3. The header is empty (suppose to be?). Close the drawer.
![Screenshot of Editing Item in Settings (2)](https://user-images.githubusercontent.com/20950568/116416649-cadd4380-a83a-11eb-9603-8819fec17732.jpg)

4. Click and open an existing item in the list. The header is correct. Close the drawer.
![Screenshot of Editing Item in Settings (3)](https://user-images.githubusercontent.com/20950568/116416703-d6c90580-a83a-11eb-877c-6ced635b0ae1.jpg)

5. Click the **Create New** button again. Whut?! The header is prefilled with the previous items title...
![Screenshot of Editing Item in Settings (4)](https://user-images.githubusercontent.com/20950568/116416843-011ac300-a83b-11eb-8a15-df5c3c7fc56d.jpg)

Some funny business going on here... 🥸

**Comment by jianliao** [comment]
I saw the same problem, too.
After the debugging, I found that the title was computed correctly on this [function - drawer-item.vue#L124](https://github.com/directus/directus/blob/c225bbf762d6e3b0ae14518b27276893f93aba37/app/src/views/private/components/drawer-item/drawer-item.vue#L124). But somehow it didn't apply to the template correctly.

```
<h1 class="type-title" v-else>
    <render-template :collection="templateCollection.collection" :item="templateData" :template="template" />
</h1>
```

It is very confusing when creating a new item. Here is the screen recording to reproduce it.
https://user-images.githubusercontent.com/1207520/116457808-b720e580-a818-11eb-808f-869ccaa746c7.mp4
