### ISSUE TITLE
Can't enter to app after update to rc.61

### ISSUE THREAD

**Issue by DaanMoura** [directus/directus#5345]
I was on rc.58 and I update the directus to rc.61. But now, every time I try to open the app, it doesn't open and I get this error on backend:
```
error select "collection", "singleton", "note", "sort_field", "accountability" from "directus_collections" - column "accountability" does not exist
````

Actually does not exists this column on the table. But what I have to do to make it work?
I'm using MySQL, btw.

**Comment by rijkvanzanten** [comment]
Migrate the database after updating. See https://docs.directus.io/guides/projects/#upgrading-a-project 👍🏻
