### ISSUE TITLE
BAD_FIELD_ERROR after directus update.

### ISSUE THREAD

**Issue by amiraiouaz** [directus/directus#5350]
Hello,

I am having an issue since I updated directus 9.0.0-rc.57 to directus 9.0.0-rc.61

After I run npx directus start, everything seems to be working but when I tried to connect to Admin App I get this:

![image](https://user-images.githubusercontent.com/22788646/116513878-8600ed80-a8ca-11eb-941d-a8a3156a2217.png)

I tried to reinstall all packages many times, I tried to run  npm rebuild argon2 --build-from-source because there was an issue with this package with CentOS. I never had issues before when I was updating directus.

Any ideas?

Thanks in advance!

### Project details

Directus Version: 9.0.0-rc.61
Environment: production
OS: CentOS-7
Node: 15.3.0
MySQL: 8.0.22

**Comment by madc** [comment]
This comment should help you: https://github.com/directus/directus/issues/5345#issuecomment-828887541

**Comment by nickrum** [comment]
What @madc said 👍

(@rijkvanzanten Maybe we should make it somehow more prominent that it is necessary to run the migrations after running `npm update`)

**Comment by amiraiouaz** [comment]
Thanks a lot! It did the trick!
