### ISSUE TITLE
Revisions endpoint not working properly

### ISSUE THREAD

**Issue by GustavoMoreiraPT** [directus/directus#5356]
1) The issue and what you expected to happen
    
Hi everyone,
I am using Directus v9.0.0-rc.61 from source code, and when using the [revisions endpoint](https://docs.directus.io/reference/api/system/revisions/), I am seeing a strange behavior, when I can see the entire object when I create an item, but after I update that same item, all relational information becomes just an ID. 

2) Exact steps to reproduce this issue
- Create a collection called "TestCollection"
- Add to that collection a new field of type "translation".
- Add to the translation table, a field "value" of type "String" and interface text-input.
- Create an item on TestCollection
- From, eg Postman, request the following: http://localhost:8080/revisions?fields[]=data&sort=-activity&filter[collection]=testcollection&filter[item]=1
- At this point, you should see something similar to this:

`{
            "data": {
                "version": 1,
                "name": "test",
                "Localizations": [
                    {
                        "languages_code": "de-DE",
                        "value": "testValue"
                    }
                ],
                "id": 1
            }
        }`
- Go back to the item you created, and change anything in there.
- Go back to Postman and request the same endpoint, you should see something like this
 `{
    "data": [
        {
            "data": {
                "id": 1,
                "version": 2,
                "name": "test",
                "Localizations": [
                    1
                ]
            }
        },
        {
            "data": {
                "version": 1,
                "name": "test",
                "Localizations": [
                    {
                        "languages_code": "de-DE",
                        "value": "testValue"
                    }
                ],
                "id": 1
            }
        }
    ]
}`

As you can see, the second revision does not bring me the entire "Localization" object, but just the ID, which is different behavior than the first revision.

I was expecting this:

`{
    "data": [
        {
            "data": {
                "id": 1,
                "version": 2,
                "name": "test",
                "Localizations": [
                    {
                        "languages_code": "de-DE",
                        "value": "testValue"
                    }
                ]
            }
        },
        {
            "data": {
                "version": 1,
                "name": "test",
                "Localizations": [
                    {
                        "languages_code": "de-DE",
                        "value": "testValue"
                    }
                ],
                "id": 1
            }
        }
    ]
}`

What I changed was the "version" fielf, from '1' to '2', but the localization object is just returning me the ID of the relation table instead of the complete table, as it is sent in the first revision.

3) Your environment:
    What version of Directus you are using --> Directus v9.0.0-rc.61
    Which DBMS are you using ---> SQLite
    Which deployment are you using (npx, Docker, ...) --> Following [running locally instructions](https://docs.directus.io/contributing/running-locally/)
    What browser are you using ---> Chrome

Thank you in advance for looking into this.

Gustavo

**Comment by rijkvanzanten** [comment]
This is know. Revisions don't track relational data. The reason it's available in the first creation, is that the relational data is part of the first creation payload. Everything after that is only tracking the top level item. There's a couple discussions about ways to track data relationally here: https://github.com/directus/directus/discussions/4796,  https://github.com/directus/directus/discussions/3117, https://github.com/directus/directus/discussions/3110, it also ties in directly with https://github.com/directus/directus/discussions/2975
