### ISSUE TITLE
Add support for non-auto-increment default-value based primary keys (like UUID)

### ISSUE THREAD

**Issue by calsch03** [directus/directus#5358]
I have connected Directus with an existing MS SQL database. The primary keys use the datatype uniqueidentifier and this results in an error when I change the field in Directus or use it in a M2O relationship.

1) The issue and what you expected to happen
I can create new items using the `newid()` command in the primary key field. But when I edit the primary key field in the Directus data model Directus gives an invalid payload error.
![image](https://user-images.githubusercontent.com/19907926/116527925-7f2ea680-a8db-11eb-82d0-7e9b373dce7c.png)

2) Exact steps to reproduce this issue
- Create a MS SQL database and a table with a primary key of data type uniqueidentifier.
- Connect Directus to the MS SQL database.
- In Directus data model: change the primary key field (for example make it read only) and Directus throws the error.

3) Your environment:
- Directus: 9.0.0-rc.61
- MS SQL server: 15.0.2080.9
- Which deployment are you using: npx
- What browser are you using: Microsoft Edge 90.0.818.46

**Comment by rijkvanzanten** [comment]
The same applies to Postgres' `generate_uuid()` (plugin) function, and potentially other default value based values

**Comment by jyotivarade** [comment]
@paescuj , is this issue related to version. because i have also install extension 
![image](https://user-images.githubusercontent.com/50901499/116862100-e1601200-ac21-11eb-952a-e7dfc8268315.png)
