### ISSUE TITLE
Gatsby plugin v9rc.60 - Unexpected Token '.'

### ISSUE THREAD

**Issue by arango** [directus/directus#5377]
_Originally posted by @olehkhalin in https://github.com/directus/directus/issues/4115#issuecomment-802790463_

As mentioned here, this issues is occurring with Netlify as well as Gatsby Cloud.

 const hasToken = auth?.token && auth?.token?.length > 0;
                      ^
SyntaxError: Unexpected token '.'

**Comment by rijkvanzanten** [comment]
As per the same issue (https://github.com/directus/directus/issues/4115#issuecomment-780387434), make sure your version of Node is up to date 👍🏻

**Comment by arango** [comment]
My version of node is up to date. I can build it locally. Netlify and Gatsby Cloud cannot build it.

**Comment by rijkvanzanten** [comment]
They both support NODE_VERSION:

https://support.gatsbyjs.com/hc/en-us/articles/360052322954-Environment-Variables-Specific-to-Gatsby-Cloud

https://docs.netlify.com/configure-builds/manage-dependencies/
