### ISSUE TITLE
Video doesn't play from Cloud storage

### ISSUE THREAD

**Issue by workatease** [directus/directus#5380]
1) The issue and what you expected to happen
    Video is not playable from cloud storage but play good from local storage.

2) Exact steps to reproduce this issue
   https://user-images.githubusercontent.com/57198612/116629518-6fd14c80-a91f-11eb-8679-8d2eb513043e.mov

3) Your environment:
    What version of Directus : Directus 61.RC
    Which DBMS are you using: Postgres 12
    Which deployment are you using local
    What browser are you using: Chrome

**Comment by rijkvanzanten** [comment]
Must be something to do with the Range request to DigitalOcean Spaces (and/or S3 in general): https://github.com/directus/directus/blob/main/packages/drive-s3/src/AmazonWebServicesS3Storage.ts#L213

**Comment by workatease** [comment]
I was able to play it if i get a signed url from storage
