### ISSUE TITLE
Custom format using data field symbol table didn´t work RC.61

### ISSUE THREAD

**Issue by hermesalvesbr** [directus/directus#5396]
![Captura_de_Tela_2021-04-29_as_14 17 47](https://user-images.githubusercontent.com/379850/116716745-7d81e300-a9ae-11eb-9b18-01550e2c203c.png)

1) Date type field show me the display option for using custom format, following the data field symbol table: https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table , but didn´t display with custom. 

2) Exact steps to reproduce this issue
   Settings -> Data Model -> Collection -> Add/Edit Date type field -> Display

3) Your environment:
    v9.0.0-rc.61
    Tested with PostgreSQL 9.2.24 and PostgreSQL 13
    npx
    Chrome, Firefox and Safari

**Comment by rijkvanzanten** [comment]
It's `yyyy` not `YYYY`. `YYYY` are [week-numbering years](https://github.com/date-fns/date-fns/blob/master/docs/unicodeTokens.md#popular-mistakes) 👍🏻
