### ISSUE TITLE
Using DB_SEARCH_PATH with multiple schemas on Postgres results in a blank screen

### ISSUE THREAD

**Issue by gboor** [directus/directus#5397]
I am using Directus on a Postgres database that has multiple schemas. After initially running it, it worked fine and I was able to see and set up all tables in the public schema.
When I changed the `DB_SEARCH_PATH` env var to "lcia" - another schema in the DB - it also worked fine and I could set that up, though it did set up a completely new set of tables for directus.

After some searching on how to combine this, I found that someone suggested using "array:public,lcia" for the env var and while it does start up, I get a blank screen the moment I go to the interface, resulting from a 500 error on a call to `/server/info?limit=-1`.

Looking at the logs I see;

```
TypeError: Cannot read property 'primary' of undefined at Object.<anonymous> (/directus/node_modules/directus/dist/utils/get-ast-from-query.js:41:81) at Generator.next (<anonymous>) at /directus/node_modules/directus/dist/utils/get-ast-from-query.js:11:71 at new Promise (<anonymous>) at __awaiter (/directus/node_modules/directus/dist/utils/get-ast-from-query.js:7:12) at Object.getASTFromQuery [as default] (/directus/node_modules/directus/dist/utils/get-ast-from-query.js:19:12) at SettingsService.<anonymous> (/directus/node_modules/directus/dist/services/items.js:212:57) at Generator.next (<anonymous>) at /directus/node_modules/directus/dist/services/items.js:27:71 at new Promise (<anonymous>)
```

I tried various combinations of having the directus tables in only 1 schema, no schemas, both schemas - all result in the same error.

How do I use Directus with multiple schemas and how to I make sure the directus tables are only created in one of them? The earlier tickets about this I found suggest that the array: syntax should work if all schemas are bootstrapped, but that would mean an additional 15 tables per schema. It also doesn't actually work; I tested it.

Directus docker image v9.0.0-rc.61
PostgreSQL 11
Docker image deployed on Kubernetes
Firefox 88

**Comment by rijkvanzanten** [comment]
> How do I use Directus with multiple schemas and how to I make sure the directus tables are only created in one of them? 

You can't. This is not officially supported at this point. See https://github.com/directus/directus/discussions/5395#discussioncomment-680087 for a discussion around this 🙂
