### ISSUE TITLE
German Umlauts in a WYSIWYG text field are shown as ampersand codes in a row preview

### ISSUE THREAD

**Issue by ZusorCode** [directus/directus#5410]
When I write some text with an umlaut in a WYSIWYG text field, that text is correctly shown inside the WYSIWYG editor.
But when previewing the row in the collections tab, instead of the umlaut the HTML ampersand code is shown.

Correct inside of WYSIWYG editor:
![image](https://user-images.githubusercontent.com/23165606/116792878-b52e7f00-aac3-11eb-942f-9a43153c203e.png)
Umlaut is swapped with ampersand code:
![image](https://user-images.githubusercontent.com/23165606/116792868-acd64400-aac3-11eb-9b38-830db7e2d12a.png)

---

### Project details
Directus Version: 9.0.0-rc.61
Environment: production
OS: Windows_NT 10.0.19042
Node: 14.4.0

**Comment by benhaynes** [comment]
This is most likely the wysiwyg editor converting the umlaut to an HTML entity. There should be an option in this library to save the actual character, but that may cause issues depending on your database and encoding.

**Comment by rijkvanzanten** [comment]
> we could also have the formatted display show HTML entities correctly.

I'd say this is the ideal solution 👍🏻

**Comment by ZusorCode** [comment]
Thank you!
