### ISSUE TITLE
Custom "Directus Users" update permissions not disabling fields

### ISSUE THREAD

**Issue by NightlyFlux** [directus/directus#5411]
**Steps to reproduce:**

1. Create a role with app access
2. Go to system collections, select "update" and "use custom" from the Directus Users collection
3. Select the fields you want to enable (Example: Language, Theme and 2FA only)
4. Log in with the non admin user
5. Go to the user's profile
6. All the fields get enabled, and if you try to edit them it wont let you but they are supposed to be disabled

**Directus App**
![image](https://user-images.githubusercontent.com/54598567/116796903-869dad80-aa9d-11eb-8ac5-384bef912cb5.png)

**DB Row**
![image](https://user-images.githubusercontent.com/54598567/116796892-5950ff80-aa9d-11eb-9a0b-f75abaea6bea.png)

---

### Project details
Directus Version: 9.0.0-rc.61
Environment: production
OS: Windows_NT 10.0.19042
Node: 15.14.0
Database: MySQL

**Comment by emekatoby** [comment]
yes. This is true. I thought i was doing something wrong
