### ISSUE TITLE
v-Tab Click Twice

### ISSUE THREAD

**Issue by ernst86913** [directus/directus#5414]
Clicking twice on a v-Tab element removes "active" state from that element (toggle).

Instead - active state should be kept.

**Comment by rijkvanzanten** [comment]
Do you have a minimal reproduction to test with?

**Comment by ernst86913** [comment]
Good example are the vertical tabs in field settings... open those and the first tab will be active... click again on the first tab and no tab is active.....

![image](https://user-images.githubusercontent.com/47870436/116901031-bb466c00-ac39-11eb-8e91-cc63546be6ce.png)
