### ISSUE TITLE
Hooks: items.create on intermediate relationship provides wrong knex instance

### ISSUE THREAD

**Issue by joselcvarela** [directus/directus#5460]
When listening for `items.create` in an intermediate relationship table, and if the item is created by a main collection, the knex instance fires an error complaining about a transaction is in progress.

This is the error (includes DEBUG=knex:*):
```
  knex:tx trx4: Transaction completed: update `section_contents` set `columns` = ?, `rows` = ? where `id` = ? +2ms
17:40:38 ⚠️  An error was thrown while executing hook "items.create"
17:40:38 ⚠️  Transaction query already complete, run with DEBUG=knex:tx for more info
```

I have found what is causing the issue is this:
https://github.com/directus/directus/blob/fe7ed3236f64563841ee9d512c41b9fb39755713/api/src/services/items.ts#L547-L554

We are creating items and dispatching the hook in the middle of a transaction.

I am opening an issue instead of a PR because I don't know how could this be handled.

**Comment by rijkvanzanten** [comment]
The after hook is called asynchronously (non-blocking), so it shouldn't rely on the transaction, but should only get the regular DB connection 👍🏻
