### ISSUE TITLE
Extend Backbone Model

### ISSUE THREAD

**Issue by WellingGuzman** [directus/directus#548]
*Extend Backbone Model*
Let's extend backbone model to a something like `DirectusModel` so we can encapsulate methods that are part of Directus, for example the delete record that can be updated or removed as it's described here #496.

**Comment by benhaynes** [comment]
**[Migrated to FeatHub](http://feathub.com/directus/directus/+11)**

Please use the [Directus FeatHub](http://feathub.com/directus/directus) to vote for features or make new request. Accepted feature requests will be added to GitHub Issues.
