### ISSUE TITLE
Thumbnail generation bug

### ISSUE THREAD

**Issue by cynova** [directus/directus#5485]
Problem: Sometimes directus crashes while generating an image (in my case probably an out of memory exception due to low limits).
This creates a file with size 0 that doesn't get cleaned up.
Any future requests to this thumbnail get served from disk - serving a file with size 0.

Proposed fix:
Either: Don't open file for write until the thumbnail is actually generated
Or: Check for 0 size when serving thumbnails and regenerate

**Comment by rijkvanzanten** [comment]
What do you mean by

> Don't open file for write until the thumbnail is actually generated

?

**Comment by rijkvanzanten** [comment]
Also wondering if this is something we can actually handle better on Directus itself, or if it's more a "you can't generate thumbnails for images over XXX size when you only have YYY memory" 🤔

**Comment by rijkvanzanten** [comment]
https://github.com/directus/directus/pull/5795 added options to control the memory overhead of asset generation 👍🏻
