### ISSUE TITLE
Button Links: URL Options should use "Template Display" input

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#5488]
An important aspect of the Button Links Interface is to configure "dynamic" links, eg: `https://directus.io/{{slug}}`... while this may work (based on the code), there is no way to know this from the options... and no clear sign that it's working within the input. 

We should update this option to use the correct input, where the right button provides hints and "dynamic" fields are highlighted.

![Screen Shot 2021-05-05 at 10 12 54 AM](https://user-images.githubusercontent.com/522079/117155089-7a11a180-ad8a-11eb-9550-1b786e351c01.png)

**Comment by jaycammarano** [comment]
Just clarifying, do you want the input box to validate the URL/slug and say if it's a valid URL? And syntax highlighting of the vars?
What kind of tool tips were you thinking of?

**Comment by rijkvanzanten** [comment]
@jaycammarano This input should use the same interface and structure as the "display template" inputs used elsewhere (like collection detail). In this url input, you can use `{{ field }}` to add in data from the fields in the current collection
