### ISSUE TITLE
Abort custom permissions

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#5500]
**1) The issue and what you expected to happen**
When no permissions are set and you open the "custom permission" drawer, close it again (via the close-button) the permission get set to "all access". Instead I would expect that nothing happens.

**3) Your environment:**
    What version of Directus you are using. 9.0.0-RC62

**Comment by rijkvanzanten** [comment]
This is the reason the permissions drawer didn't have a cancel button in the first place.. 😅
