### ISSUE TITLE
Incorrect OAS definition

### ISSUE THREAD

**Issue by Adri-Glez** [directus/directus#5504]
1) The issue is produced when you process the OAS definition. The OAS file that exports directus has some definitions missing: This is the error that show when I try to import it by swagger by example:

![image](https://user-images.githubusercontent.com/76236390/117223754-a40ca780-ae0e-11eb-8b4a-0ce1a85d641d.png)

There are 2 different problems:
- operationId conflicts (both GET /user/me and PATCH /user/me have the same operationId),
- more importantly, undefined path parameters in some cases (e.g. {id} or {collection} is present in path name, but not declared as path parameters in the route definition)

2) Exact steps to reproduce this issue:
    2.1) Export the oas definition generated by the URL: /server/specs/oas
    2.2) Try the import the definition with some client like Swagger: https://editor.swagger.io/
3) Your environment:
    Directus v9.0.0-rc.62
    DBMS MySQL 8
    Deployment Docker
   
4) Solution:
I can fix it manually my definition but when I create a new category I have to do again in the new one, is a bit tedious. 
It should not be very conplitate fix it in the directus code.

**Comment by aerdnach** [comment]
Hi, I'm having the same issue in rc94. Attached you can find yaml generated through /server/specs/oas api. 

![image](https://user-images.githubusercontent.com/9568794/134515048-599b7bb3-7eb8-41c5-adbf-c1410f0bc5c3.png)

[openapi.yaml.txt](https://github.com/directus/directus/files/7217943/openapi.yaml.txt)
