### ISSUE TITLE
Permission issue adding image on rich text editor

### ISSUE THREAD

**Issue by marciotoledo** [directus/directus#5505]
When you are adding image in some rich text editor, images looks break, but if you get the file url from Files with token, and replace in the image path field, it solves the issue.

https://prnt.sc/12jse2u

And changing the file path with access token

https://prnt.sc/12jsg95

---

### Project details
Directus Version: 9.0.0-rc.62
Environment: production
OS: Linux 5.4.0-65-generic
Node: 15.14.0

**Comment by benhaynes** [comment]
Thank you for reporting this. Perhaps it's a translation issue, but "Solve the issue.", is a bit demanding. 😐

**Comment by marciotoledo** [comment]
@benhaynes Sorry mate, I'm more designer than developer, I'm learning about api cms its completely new for me, I'm testing, trying, etc. I really would to help, but I feel that I dont have skills to help. I will try to find how to "Solve the issue".

Sorry my english (I'm brazilian) but if you try read again, I'm saying that when I replace the image path field with token, this action solve the issue. I was showing a possible solution for the issue.

But if I have a commercial project with a communite project aside using same core, and someone come to me find some issue, I'll really appreciate the time spent trying helping reporting the issue. 😕

**Comment by marciotoledo** [comment]
@benhaynes Fixed text 😅
And congratulations for this amazing project.

**Comment by rijkvanzanten** [comment]
This is working as it's supposed to. There's a "token" option in the wysiwyg that allows you to add a token 👍🏻

The images are inserted and saved without a token by default, which is the same as reading the image from the public role.
