### ISSUE TITLE
Collections created via API cannot be modified: Permission denied (403)

### ISSUE THREAD

**Issue by helge000** [directus/directus#5512]
### version: 
- v9.0.0-rc62
- docker w/redis
- backend: postgres

### steps
1. create a collection
2. delete this collection

### expected behaviour
Collection deleted

### actual behaviour
Error 403 returned, collection cannot be deleted

### example
```bash
$ curl -H "Content-Type: application/json" -H "Authorization: Bearer ey..." -X POST http://localhost:8055/collections -d '{"collection":"test"}'

{"data":{"collection":"test","meta":{"collection":"test","icon":null,"note":null,"display_template":null,"hidden":false,"singleton":false,"translations":null,"archive_field":null,"archive_app_filter":true,"archive_value":null,"unarchive_value":null,"sort_field":null,"accountability":"all"},"schema":{"name":"test","schema":"public","comment":null}}}

$ curl -H "Content-Type: application/json" -H "Authorization: Bearer ey..." -X DELETE http://localhost:8055/collections/test        
{"errors":[{"message":"You don't have permission to access this.","extensions":{"code":"FORBIDDEN"}}]}
```

**Comment by helge000** [comment]
Edit: This does not only affect deletions but any operations on that collection

**Comment by rijkvanzanten** [comment]
Directus ignores collections that don't have a primary key field, as more or less everything in the system relies on them. Therefore, deleting the collection fails as it's invisible to the system. That linked commit makes sure that every newly created collection has a primary key, which also means that deleting them will work as expected.

That being said, make sure to delete that table from the database and directus_collections @helge000 manually this one time, as my commit won't "fix" deleting ignored collections, as that's failing successfully

**Comment by helge000** [comment]
@rijkvanzanten , thanks for the head's up and the promt reaction.

 I've looked over ae1e22d but do **not** consider it a fix: Currently, [I am unable to create a collection via API that has a single field](https://docs.directus.io/reference/api/system/collections/). Please correct me if I'm wrong, but the workflow looks like this:

1. create collection POST /collections ; I basically can only supply a name and some metadata
2. create fields; POST /fields/:collection

What do I do if I need a UUID id field, for example?

**Comment by rijkvanzanten** [comment]
> create collection POST /collections ; I basically can only supply a name and some metadata

This is false. You can provide any fields during the initial collections creation, see https://docs.directus.io/reference/api/system/collections/#create-a-collection

> What do I do if I need a UUID id field, for example?

POST to `/collections` with something like:

```json
{
  "collection": "test",
  "fields": [
    {
      "field": "pk",
      "type": "uuid",
      "meta": {
        "hidden": true,
        "readonly": true,
        "interface": "text-input",
        "special": [
          "uuid"
        ]
      },
      "schema": {
        "is_primary_key": true,
        "length": 36,
        "has_auto_increment": false
      }
    }
  ],
  "meta": {
    "singleton": false
  }
}
```

(the above is exactly what the App sends when choosing "use auto generated UUID"

**Comment by helge000** [comment]
Ok, sorry - seems I'm blind :D - I was looking for this paragraph for some time today; this does make my life a lot easier:

>You are able to provide an array of fields to be created during the creation of the collection. See the fields object for more information on what properties are available in a field.

Thanks for the clarification.
