### ISSUE TITLE
REST API: Cannot bulk update multiple items with heterogenous data

### ISSUE THREAD

**Issue by OkayX6** [directus/directus#5514]
**1) The issue and what you expected to happen**

I used to be able in version 9.0.0.rc28 to bulk update multiple items using the REST API with

`PATCH http://myendpoint.com/items/work_items`

```
[
  {
    "id":87,
    "sort":0,
    "column":1,
    "swimlane":1
  },
  {
    "id":44,
    "sort":1
  }
]
```

Now I am getting a 
```
{
  "errors":[
    {
      "message":"\"value\" must be of type object",
      "extensions":{
        "code":"FAILED_VALIDATION"
      }
    }
  ]
}
```

**2) Exact steps to reproduce this issue**
![image](https://user-images.githubusercontent.com/1169339/117281030-68fd8900-ae8d-11eb-84d4-b487d65549d8.png)

The documentation is unclear about how to do it (only with the same partial data, which is less flexible): https://docs.directus.io/reference/api/items/#update-multiple-items

**3) Your environment:**
Directus 9.0.0.rc62
MariaDB
npx
Chrome 90

Is there anything I am missing? :)

Thanks for the help

**Comment by OkayX6** [comment]
(as a workaround, I am doing a big GraphQL mutation like this: 

```
mutation {
  item_87: update_work_items_item(id: 87, data: { sort: 0 }) {
    id
  }
  item_44: update_work_items_item(id: 44, data: { sort: 1 }) {
    id
  }
}
```

**Comment by rijkvanzanten** [comment]
Yup! This is by design. Doing updates to multiple items should be done in multiple mutations / endpoints.

I noticed you're doing just an increment on `sort`, so the sort utility might be a better fit here 🙂 https://docs.directus.io/reference/api/system/utilities/#manually-sort-items-in-collection

**Comment by pkro** [comment]
The documentation should be updated, it still says "An array of partial objects" here: https://docs.directus.io/reference/items/#request-body-4

I'll have to try the graphql workaround then too, as I don't want to make 20+ requests with individual items when one would suffice. Or write a custom endpoint, but there are so few examples and it could be so easy just using one client side request.

**Comment by jawngee** [comment]
I don't understand the rationale for this.  You should be able to do bulk updates (and bulk deletes) from the REST side.  It's in the API (itemsService.updateMany and itemsService.deleteMany).  

Our DAM potentially has to update 1000's of items in a single go.  We lose man hours writing and testing endpoints to handle bulk updates and deletes that should be a part of the REST API.  Just my opinion, but it seems like an arbitrary crimp in directus's otherwise fantastic DX.
