### ISSUE TITLE
Freeze when having multiple m2m collections in one

### ISSUE THREAD

**Issue by chernandezweb** [directus/directus#5516]
Hi there,

So my issue is that, in my project, I use a flow of multiple m2m collections in one. 

Each time I try to navigate out of a modal when multiple m2m collection are displayed, the page becomes really slow or even freezes.

So I ran a test that you could replicate easily. 

4 m2m collections in one m2m item from a m2m collection on the main page.

Even if there are no items related to those 4 m2m, you can feel already the page getting slower or freeze when saving or quitting the modal.

![image](https://user-images.githubusercontent.com/22950332/117303074-4f871d80-ae4a-11eb-9730-3010523a311a.png)

**Comment by rijkvanzanten** [comment]
I'm wondering if this is a single bug we can fix within the m2m, or just a general performance limitation of trying to render multiple highly reactive interfaces within a portal-vue instance. This might actually be improved a lot already on the `vue3` branch @nickrum

**Comment by benhaynes** [comment]
Hopefully Vue3 helps fix this. I realize these are reactive (the whole app is), but what makes these _empty_ interfaces so complex that they would slow things down?

**Comment by rijkvanzanten** [comment]
@benhaynes there is no technical difference between an empty and a "filled" m2m interface. They both watch for changes to the data, they both have the handlers for create-new/add-existing, they both have the drawers waiting to go etc etc etc. The presentation of the pre-existing items is only a very small part of what the m2m is 👍🏻

**Comment by benhaynes** [comment]
Does it matter if this is on an Item Detail page or a drawer? Having 4 M2Ms on an Item Detail would be super common.

**Comment by rijkvanzanten** [comment]
Yes, a bit. The drawers are rendered outside of the app context, which means the portal library has to keep track of changes and events itself outside of the main app context itself. It's a user-land add-on, so it can't fully rely on Vue's main rendering. That being said, Vue 3 has a native "teleport" element we'll be using for drawers, so that should also improve things here

**Comment by rijkvanzanten** [comment]
@chernandezweb What version of Directus is this? What browser (/version) and OS? What are the general specs of your machine? 

I don't think this is something we can just fix in the m2m itself, so i'll close this in favor of #5339, as that'll improve the general performance of component rendering by a lot, especially when rendering in a portal

**Comment by chernandezweb** [comment]
Sorry for the late answer.

The version was the rc 62, but I just upgraded to rc 69 and it seems to be fixed. 
I assume the Vue 3 port was in those updates.

Thank you for the help
