### ISSUE TITLE
Adding fields to directus_users - bug or expected behavior? in detail view

### ISSUE THREAD

**Issue by crhampton1** [directus/directus#5520]
Adding fields to the Directus Users doesn't seem to match layout. See screenshots below of layout and detail page. Almost looks like it adds the fields sorted alphabetically. Is this expected behavior or bug? If I move any of my custom fields it also changes where the fields go in detail, but not in the order I place them. Quite possible I'm doing something wrong too. Fantastic product btw, loving it so far!

![image](https://user-images.githubusercontent.com/1928925/117357271-bde7d200-ae82-11eb-94ec-a1998fd9c5cd.png)

![image](https://user-images.githubusercontent.com/1928925/117357474-fb4c5f80-ae82-11eb-92a2-bb344a07e094.png)

---

### Project details
Directus Version: 9.0.0-rc.62
Environment: production
OS: Linux 4.14.225-168.357.amzn2.x86_64
Node: 14.16.1

**Comment by benhaynes** [comment]
That is not expected behavior. All of the system User fields should stay exactly as-is — and any additional custom fields should be added to the end of the list and allow normal organization after that.

**Comment by tylerforesthauser** [comment]
Just out of curiosity, what is the reason we cannot organize existing fields?

**Comment by rijkvanzanten** [comment]
@tylerforesthauser those system fields don't exist in the database, so can't be altered on the fly

**Comment by crhampton1** [comment]
Let me know if you need me to try/do anything on my end.

Also, I was planning on adding quite a few fields in there, based on an existing database. Is it considered best practice to put them there, or to make a collection and connect it to a user?

**Comment by rijkvanzanten** [comment]
> Is it considered best practice to put them there, or to make a collection and connect it to a user?

That's totally up to you! If it's always going to be a single set of info tied to a single user, you might as well add it to the users table 👍🏻

**Comment by ernst86913** [comment]
If connecting it to the user.... how can I display the user fields within the form of the collection?  Is there any smart way to do that?

**Comment by rijkvanzanten** [comment]
> If connecting it to the user.... how can I display the user fields within the form of the collection?

Which collection?

**Comment by crhampton1** [comment]
Found another part of this. It also appears to be messing up in collections too. These two bottom fields are supposed to be aliases for dividers. They are not in the correct spot or even showing as dividers.

![Screen Shot 2021-05-10 at 5 40 55 PM](https://user-images.githubusercontent.com/1928925/117728269-3d451080-b1b7-11eb-8856-b6007db40e9c.png)
![Screen Shot 2021-05-10 at 5 43 13 PM](https://user-images.githubusercontent.com/1928925/117728272-3ddda700-b1b7-11eb-81bb-c1a40a0f6d15.png)

**Comment by rijkvanzanten** [comment]
@crhampton1 did you upgrade to the latest version, and if so, migrated the database using `npx directus database migrate:latest` when you did? Looks like it's defaulting to a text-input for an unknown interface

**Comment by crhampton1** [comment]
@rijkvanzanten Thanks, just ran the database migrate. That did bring he headers back to headers, but they are still in the wrong locations: 
<img width="946" alt="Screen Shot 2021-05-10 at 6 45 04 PM" src="https://user-images.githubusercontent.com/1928925/117733696-ff001f00-b1bf-11eb-9325-8503cfa13ad9.png">
