### ISSUE TITLE
Cannot delete user if they're signed in

### ISSUE THREAD

**Issue by digitaljohn** [directus/directus#5528]
When attempting to delete a user which is currently signed in to Directus, it fails. This is likely due to relational field locking?

```json
{
  "errors": [
    {
      "message": "delete from `directus_users` where `id` in ('********-****-****-****-************') - ER_ROW_IS_REFERENCED_2: Cannot delete or update a parent row: a foreign key constraint fails (`****`.`directus_sessions`, CONSTRAINT `directus_sessions_user_foreign` FOREIGN KEY (`user`) REFERENCES `directus_users` (`id`))",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

Possibly related to or will be fixed by https://github.com/directus/directus/issues/2942

---

### Project details
Directus Version: 9.0.0-rc.61
Environment: production
OS: Linux 4.4.0
Node: 14.16.1

**Comment by andriusign** [comment]
v69 still the same issue https://github.com/directus/directus/issues/6095

**Comment by rijkvanzanten** [comment]
Correct, as this was released in 70
