### ISSUE TITLE
Can't update user when providing it's (current) email

### ISSUE THREAD

**Issue by hy-ntyni** [directus/directus#5538]
Hi, it looks like a PATCH request over the REST API on a user no longer works if the request specifies an email address that is unchanged from the current one.

A test case is running something like

`curl -X PATCH -H 'Content-Type: application/json' -d '{"email": "none@example.org" }' -s -H "Authorization: Bearer $DIRECTUS_TOKEN" https://directus/users/XXXX`

on a project with an existing user having ID XXXX and email "none@example.org".

I would expect this to be a no-op when the user's email address is unchanged. This was the case until v9.0-rc.56, but since v9.0-rc.57, up to and including v9.0-rc.62, it returns this error:

`{"errors":[{"message":"Field \"email\" has to be unique.","extensions":{"code":"RECORD_NOT_UNIQUE","collection":"directus_users","field":"email","invalid":"none@example.org"}}]}`

Looking at the change history, I assume it broke with 1b1e500ee9f06711c2edc0560518714f8e4521f0 but I haven't verified that. I'm testing with the images at https://hub.docker.com/r/directus/directus .

Many thanks for your work on Directus!

**Comment by hy-ntyni** [comment]
Hi, thanks for looking at this. Unfortunately the issue still persists with v9.0.0-rc.68.

**Comment by rijkvanzanten** [comment]
Ah yeah, thanks for the heads up. Closed for real in b84d3be 👍🏻

**Comment by rijkvanzanten** [comment]
Mind opening a new issue? Thanks! (cc @Oreilles)
