### ISSUE TITLE
RC.63  Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.

### ISSUE THREAD

**Issue by cdwmhcc** [directus/directus#5545]
![image](https://user-images.githubusercontent.com/8030134/117504462-0b645c00-afb5-11eb-9010-75f44b2d0090.png)

**Comment by rijkvanzanten** [comment]
@cdwmhcc What database is this on?

**Comment by cdwmhcc** [comment]
> ~@cdwmhcc What database is this on?~
> 
> Guessing MySQL 5 (without support for JSON types in options). Migration has been fixed 👍🏻 You can roll back and try again, or manually delete the `options` column contents for fields where `options` starts with with `{"0": "{", "1": ` if you haven't made a backup before migrating 👍🏻

![image](https://user-images.githubusercontent.com/8030134/117509099-3b632d80-afbc-11eb-9670-0e0da74597c0.png)

set null?

**Comment by rijkvanzanten** [comment]
yes
