### ISSUE TITLE
Getting internal server error after M2M sorting

### ISSUE THREAD

**Issue by iDobrounig** [directus/directus#5553]
Running directus v9.0.0-rc.64

I have a collection with a M2M to another collection with a sort field.
Adding items and saving alements works, but if I change the order I get an internal server error:
<img width="574" alt="Bildschirmfoto 2021-05-08 um 23 51 33" src="https://user-images.githubusercontent.com/4222276/117554488-63a06a00-b058-11eb-9306-3ca6615f9f86.png">

I always updated using npm and migrated the DB.
Thanks for your help

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/directus/pull/5763
