### ISSUE TITLE
POST /users/invite is broken

### ISSUE THREAD

**Issue by andriusign** [directus/directus#5555]
Calling POST /users/invite results in 500 error.

Directus v9.0.0-rc.64

![Screenshot from 2021-05-09 04-47-09](https://user-images.githubusercontent.com/14263959/117558679-10461000-b088-11eb-975a-9325ba7e0273.png)

![Screenshot from 2021-05-09 04-46-21](https://user-images.githubusercontent.com/14263959/117558680-10dea680-b088-11eb-982d-06563916d31f.png)

![Screenshot from 2021-05-09 04-46-36](https://user-images.githubusercontent.com/14263959/117558682-11773d00-b088-11eb-8a2b-e27864e916b7.png)

Version 59 is working fine. What might me wrong?

**Comment by andriusign** [comment]
How come you not have any kind of tests to prevent such issues from happening when you change code?

**Comment by rijkvanzanten** [comment]
> Version 59 is working fine. What might me wrong?

The changes introduced by @Kinzi and @danieljwestman expose a point in the lookup flow that needs to be a bit more defensive:

https://github.com/directus/directus/blob/a86c0832b05cfdc62e2626669dc80a264efd99ac/api/src/services/mail/index.ts#L76

> How come you don't have any kind of tests to prevent such issues from happening when you change code?

Setting up full coverage for everything Directus does takes a massive amount of time and effort, and there's only so many people helping out in doing so. Investing all those resources personally during the RCs doesn't make too much sense to me personally, as we're still actively shaping how things are supposed to work. During RCs, we're generally going 10 steps ahead, and 2 back per release, once we're releasing v9.0.0 proper, that'll go to 5 steps ahead and 0 back, as stability becomes way more important than iteration speed 👍🏻

**Comment by andriusign** [comment]
Thanks for the clarification. I appreciate your and your team's effort developing Directus.

**Comment by andriusign** [comment]
Shall this fix be included in v9.0.0-rc.65?

**Comment by rijkvanzanten** [comment]
Yup!
