### ISSUE TITLE
M2M invalid field value

### ISSUE THREAD

**Issue by tonxxd** [directus/directus#5558]
I have 2 tables (users and vehicles) and a M2M field in users tables (inquires) 
I am trying to create an inquiry entry ["on the fly"](https://docs.directus.io/reference/api/introduction/#one-to-many-many-to-many) when creating a user using the following code
```js
await directus.items("users").creatOne({
   inquires:[{vehicles_id: id}]
})
```
but the API returns 
```js
{"errors":[{"message":"\"users_id\" contains an invalid value","extensions":{"code":"FAILED_VALIDATION","field":"users_id","type":"nnull"}}]}
```

I also tried to create the user and then update it with the inquiry value like this
```js
let {id:userid} = await directus.items("users").createOne({
   ...
})
await directus.items("users").updateOne(userid, {    // makes correct request to api.com/items/users/id
   inquires:[{vehicles_id: id}]
})
```
but, even if the user is created successfully and the id is returned correctly, the update request throws the same error

**Comment by ps-rseidl** [comment]
I just had the same error message when removing an entry from a M2M relation of my user object. In my case the relation was misconfigured and I had to change the relational triggers from "Nullify the user_id field" to "Delete the users_2_schedule_config item".

![directus-relation-issue](https://github.com/directus/directus/assets/88653925/fe03fe3d-8849-4bd2-af45-0c34c2a95da3)
