### ISSUE TITLE
Cookie is not cleared on logout when using the cookie options

### ISSUE THREAD

**Issue by broodroosterdev** [directus/directus#5596]
1) The issue and what you expected to happen
    The logout endpoint does not set the right cookie options 
    when using cookie based login 
    while it should use the options provided in the environment variables

2) Exact steps to reproduce this issue
    

- Set the following environment variables

```
REFRESH_TOKEN_COOKIE_SAME_SITE=none
REFRESH_TOKEN_COOKIE_SECURE=true
```
- Make a login request from a different domain as the directus instance using the cookie method.
- Make a logout request using cookies
- Check the set-cookie header

3) Your environment:
    What version of Directus you are using: v9.0.0-rc.64
    Which DBMS are you using (MySQL 8, Postgres 12, ...): Postgres 13
    Which deployment are you using (npx, Docker, ...): Docker
    What browser are you using (Chrome 87, Safari 14, ...): Chrome 90

4) Any other relevant information we might need to reproduce this issue
    I am testing my app on `http://localhost`, while my directus instance has an `https://` domain.
    I am using the Directus SDK, however this issue also occurs when using the Fetch API

**Comment by paescuj** [comment]
Thanks @broodroosterdev 😄 I actually had this on my radar, but wasn't entirely sure weather the options are required...
