### ISSUE TITLE
Problem in the "Roles & Permissions".

### ISSUE THREAD

**Issue by x37ts52** [directus/directus#5597]
Hey Guys,

i found a problem in the "Roles & Permissions".

If you give some user (or public) true permissions it works well.

But if you take the permission away from him, than he still have the permission in the connected session!

I tested this behavior in "Postman" in the register "Authorization" and "Bearer Token / No Auth".

I use the docker container. If I restart the docker instance, the permissions are memorized how I wanted.

regards

---

### Project details
Directus Version: 9.0.0-rc.24
Environment: production
OS: Linux 5.4.0-73-generic
Node: 14.15.2

**Comment by rijkvanzanten** [comment]
> But if you take the permission away from him, than he still have the permission in the connected session!

Do you have caching enabled by any chance? The "If I restart the docker instance, the permissions are memorized how I wanted." part makes me think the caching is enabled with storage in memory, which 

> Directus Version: 9.0.0-rc.24

Make sure to update to the latest version! 24 is very far behind and is missing some significant updates 🙂 

I'll close this for now, as I believe this is a configuration issue 👍🏻

**Comment by x37ts52** [comment]
I tried a POST request with "no-cache header" in Postman. Now it still works. Thanks.

I read the doc, but I think I read over the part with the cache ;-)
https://docs.directus.io/guides/api-config/#cache
