### ISSUE TITLE
User without admin permissions cannot create/update relation, PATCH forbidden

### ISSUE THREAD

**Issue by Carobit** [directus/directus#5624]
A user with full access to the collections but without admin access (only default admin permissions) cannot update a relation through the parent collection. I've tested through the directus web interface. The admin user can do the same action successfully. Enabling "admin access" in the role settings makes it possible to edit the relation. However manually adding all the admin permission does not help.

How to reproduce:
- Create collection "news"
- Create collection "news_comments"
- Add e.g. text field to "news_comments"
- Add many-to-one relation in news_comments as news_article referring to news.id, allow automatically creating the opposite (one-to-many) in the news collection like news.news_comments
- Add full permission for these collections for the actual role ("editor")
- Log in as the editor
- Create a news item
- During news item creation or editing an existing news item, try to create a new or edit an existing comment through the news item, (pretty strange that 1-2 times i could add an existing comment to the news, but most of the times it also fails).
- The PATCH request to items/news/1 with payload: `{"news_comments":[{"id":2,"comment":"<p>comment 1</p>\n<p>test</p>"}]}`
fails with `{"errors":[{"message":"You don't have permission to access this.","extensions":{"code":"FORBIDDEN"}}]}` response. 
- When removing a relation, PATCH request succeeds.

Playing with the permissions:
- Go to roles & permissions, open "editor" check "Admin access" Enabled
- Go back to collections as that editor user and retry => SUCCESS
- But it's definitely what I want...

- Go to roles & permissions, revoke Admin access, but enable all the Admin permissions manually
- Go back to collections as that editor user and retry => FAIL
I assume it would be the same as adding Admin access, but for some reason it is not.. Maybe it's not the root cause, but a strange behavior.

### Project details
Directus Version: 9.0.0-rc.64
Environment: production
OS: Linux 5.10.34-1-MANJARO
Node: 14.16.1

Project is created via docker-compose using image: directus/directus:v9.0.0-rc.64, basically the and default docker-compose.yaml

Maybe related to or duplicate of:
https://github.com/directus/directus/issues/5564
https://github.com/directus/directus/issues/5257

**Comment by christianrr** [comment]
Same issue here on 9.0.0-rc.64, when trying to patch a one-to-many field from the parent collection, e.g.
{
    "id": 32,
    "side_channels": [
        {
            "id": 202,
            "material": "Value 1"
        }
    ],
}

Permissions are correctly configured and request was working in 9.0.0-rc.62...

**Comment by jonochong** [comment]
Same issue here on v9.0.0-rc.67. 

Custom role cannot patch / edit relation - in my case its a translation relation.

**Comment by seanmars** [comment]
Will fixed this issue in next RC? thanks

**Comment by christianrr** [comment]
Not working in latest version rc.68 - any idea what the problem could be?

One side-node for reproducing the issue: as mentioned by @Carobit, it just happens with non-admin users...

Many thanks!

**Comment by rijkvanzanten** [comment]
> Not working in latest version rc.68 - any idea what the problem could be?

Yeah, this issue wasn't fixed / released 😅

**Comment by christianrr** [comment]
> > Not working in latest version rc.68 - any idea what the problem could be?
> 
> Yeah, this issue wasn't fixed / released 😅

Yeah, got that... However, it's a pretty major bug in my opinion and that's why it would be interesting to locate the issue asap ;)

**Comment by rijkvanzanten** [comment]
@christianrr / @Carobit can you share an overview of your `directus_relations` table? Everything seems to work as expected on my end when I set is up fresh as per the OP 🤔

**Comment by sksar** [comment]
@rijkvanzanten  I created a fresh Directus installation on localhost and documented the whole bug in screen recording,

[Dropbox Download Link](https://www.dropbox.com/s/9w5jf9dckrubocm/Collections%20-%20Google%20Chrome%202021-05-18%2010-14-22.mp4?dl=1)
[Dropbox View Link](https://www.dropbox.com/s/9w5jf9dckrubocm/Collections%20-%20Google%20Chrome%202021-05-18%2010-14-22.mp4?dl=0)

### Summary 
I create two tables/collections, then I set up many to many relationships on them. 
Admin user was successfully able to do everything, add / edit / remove.
Then I created a non-admin user and allowed the permissions in the non-admin role.
I signed back as the non-admin user and it shows the same, Forbidden.
I also tried giving all access to the non-admin role, even the Directus internal stuff, still the issue persists. 

Note: Everything is fully documented in the screen recording video.. 
_(PS: The video is in HQ but for some reason, Dropbox page shows it blurry, so I advise download and watch the video)_

### Project details
Directus Version: 9.0.0-rc.64
Environment: production
OS: Windows_NT 10.0.19042
Node: 14.16.1

**Comment by nickluger** [comment]
I was no longer able to reproduce this with `rc.69`.

**Comment by sksar** [comment]
> @rijkvanzanten I created a fresh Directus installation on localhost and documented the whole bug in screen recording,
> 
> [Dropbox Download Link](https://www.dropbox.com/s/9w5jf9dckrubocm/Collections%20-%20Google%20Chrome%202021-05-18%2010-14-22.mp4?dl=1)
> [Dropbox View Link](https://www.dropbox.com/s/9w5jf9dckrubocm/Collections%20-%20Google%20Chrome%202021-05-18%2010-14-22.mp4?dl=0)
> 
> ### Summary
> I create two tables/collections, then I set up many to many relationships on them.
> Admin user was successfully able to do everything, add / edit / remove.
> Then I created a non-admin user and allowed the permissions in the non-admin role.
> I signed back as the non-admin user and it shows the same, Forbidden.
> I also tried giving all access to the non-admin role, even the Directus internal stuff, still the issue persists.
> 
> Note: Everything is fully documented in the screen recording video..
> _(PS: The video is in HQ but for some reason, the Dropbox page shows it blurry, so I advise download and watch the video)_
> 
> ### Project details
> Directus Version: 9.0.0-rc.64
> Environment: production
> OS: Windows_NT 10.0.19042
> Node: 14.16.1

After Upgrading the same project to Directus Version: 9.0.0-rc.69, the problem was no longer there. I have not tried it with a fresh install again. But for now, in the dev project, and in my product project, the problem no longer exists. 
Upgrading to rc.69 seems to fix the problem as of now.
