### ISSUE TITLE
Required/trimmed text field is not validated against whitespaces

### ISSUE THREAD

**Issue by dsheiko** [directus/directus#5628]
As an admin I have TITLE field of type text with "allow NULL value" OFF and "trim the start and end" ON.
When creating a new article and entering only whitespaces and pressing SAVE, the system accept it.

Expected behavior: it shall block saving and warn the user the value is empty (assuming the whitespaces are trimmed)

Project details
Directus Version: 9.0.0-rc.64
Environment: production
OS: Ubuntu 18.04.2 LTS
Node: 11.15.1

![d01](https://user-images.githubusercontent.com/1393963/117950110-23b8db80-b313-11eb-81bf-b2b7c9c0c923.PNG)
![d02](https://user-images.githubusercontent.com/1393963/117950118-26b3cc00-b313-11eb-820e-91815b091666.PNG)
![d1](https://user-images.githubusercontent.com/1393963/117951755-c1f97100-b314-11eb-8ca0-2e3adb710abb.PNG)

**Comment by benhaynes** [comment]
I assume this is saving as an empty string (which is allowed), not NULL. We'll be adding a **Field** option for "required" that will limit empty strings as values. @rijkvanzanten do we have a ticket for that?

**Comment by rijkvanzanten** [comment]
@benhaynes is right. As a matter of fact, in the screenshot above that's explicitly enabled. @dsheiko see the "Cleared Value" option 👍🏻
