### ISSUE TITLE
Problem with filtering M2M items

### ISSUE THREAD

**Issue by iksent** [directus/directus#5632]
1. Create Articles, that have Categories (M2M)

2. Use GraphQL query to retrieve a list of articles with specific categories, filtered by slug:

```
query getArticles($cat_slugs: [String]) {
  article(
    filter: {
      status: { _eq: "published" }
      categories: { category: { slug: { _in: $cat_slugs } } }
    }
  ) {
    id
    status
    categories {
      category {
        id
        slug
      }
    }
    ...
```

3. **And don't pass a `$cat_slugs` variable to the query**

4. You will get not all Articles, but only those, which have at least one category.

PS: This is a follow-up to the previous issue https://github.com/directus/directus/issues/4471

---

### Project details
Directus Version: 9.0.0-rc.64
Environment: production
OS: Linux 5.4.0-66-generic
Node: 10.19.0

**Comment by iksent** [comment]
Do we need to add a check for a `value` for `undefines` at here: https://github.com/directus/directus/blob/main/api/src/utils/apply-query.ts#L62?

**Comment by rijkvanzanten** [comment]
@iksent Yeah, or filter them out earlier up the tree already 🤔 Instead of doing it in `apply-filters` and `apply-query`, we could skip them out in the `sanitize-query` step, that would ensure these invalid filters never trickle down further into the data flow

**Comment by joselcvarela** [comment]
Hello @iksent 
This issue seems now to be solved.
The current behaviour does not return any data if the variable is not defined.
___
> If you think this is not solved yet, feel free to reach us in order to reopen.

**Comment by iksent** [comment]
> The current behaviour does not return any data if the variable is not defined.

Are you sure this is the correct behavior?

I expect to ignore a variable if it is not passed (equals to `undefined`) and get all the data as if the variable doesn’t exist at all. This is due to the fact that we cannot ignore the client-side variable in GraphQL, and we can just control the entire client-side filter in JS, which is not very convenient in some situations.

**Comment by joselcvarela** [comment]
I think this can be interpreted on both sides.

Taking this into account:
```gql
categories: { category: { slug: { _in: $cat_slugs } } }
```

and knowing `$cat_slugs` is undefined / empty, we should read:

1 - "Get all categories which slug is in nothing / empty". This is my interpretation

2- "Get all categories if slug is in nothing / empty otherwise give me the only ones that are on that group". I think this is your interpretation.

Don't really know which one we should rely on 🤔 but on client perspective I know the pain 😅

**Comment by rijkvanzanten** [comment]
@joselcvarela The other interesting difference is the difference between `null` and `undefined` in these cases (even though graphql ironically enough doesn't differentiate between the two in typings)
