### ISSUE TITLE
BOOLEAN interface not showing in detailed view

### ISSUE THREAD

**Issue by ernst86913** [directus/directus#5643]
(latest version / commits)

![image](https://user-images.githubusercontent.com/47870436/118046449-a3799100-b379-11eb-95b8-b6505435a977.png)

**Comment by rijkvanzanten** [comment]
Did you run the database migrations? `toggle` has been renamed to Boolean which is included in migration `20210506A-rename-interfaces`

**Comment by ernst86913** [comment]
Yes... here you can see the DB values...

![image](https://user-images.githubusercontent.com/47870436/118054809-3d940600-b387-11eb-8dfb-a79aaaddf747.png)

**Comment by ernst86913** [comment]
Interface name is toggle:

![image](https://user-images.githubusercontent.com/47870436/118054942-7d5aed80-b387-11eb-9e1a-9f0a10f06893.png)

**Comment by ernst86913** [comment]
My fault - I did not click the Toggle interface in the definition... therefore its not showing.

**Comment by ernst86913** [comment]
... seems that the behavior was different before.

**Comment by rijkvanzanten** [comment]
Ohhh I see. It's defaulting to a non-existent interface 👍🏻
