### ISSUE TITLE
Filtering not working for M2M fields in GUI

### ISSUE THREAD

**Issue by dotslash21** [directus/directus#5644]
I have 2 models `question` and `question_topic` which have a `many-to-many` relationship. When I try to filter the items in the `question` collection by a field `title` in `question_topic`, I can't access it from the `Add filter` under `Advanced Filter`.

### Filter
![image](https://user-images.githubusercontent.com/20253878/118076654-3f35ec00-b3d0-11eb-806e-e8ed4e7aecc6.png)

I can't expand the Question Topic ID

### `question` Model
![image](https://user-images.githubusercontent.com/20253878/118076466-d8b0ce00-b3cf-11eb-8565-9f5792b7045b.png)

### `question_topic` Model
![image](https://user-images.githubusercontent.com/20253878/118076571-08f86c80-b3d0-11eb-9a17-2b874e7f4d21.png)

---

### Project details
Directus Version: 9.0.0-rc.64
Environment: production
OS: Linux 5.4.0-1045-aws
Node: 14.17.0

**Comment by dotslash21** [comment]
## SQL Dump of DB
https://drive.google.com/file/d/1TC_FxZkn-IGhLTx7if_eaF9EXmX16VFb/view

**Comment by domdus** [comment]
Hi,

can confirm this - just ran into the same issue as described.
The filter option menu does not expand (it actually collapses)  when trying to select a related field (m2m)(on rc.69 here).

**Comment by rijkvanzanten** [comment]
Filtering on a nested one-to-many/many-to-many field wasn't supposed to work like this, and has been resolved in a later release. Linked commit fixes the "The filter option menu does not expand (it actually collapses) when trying to select a related field" issue 👍🏻

**Comment by rijkvanzanten** [comment]
Fixed in 158316f
