### ISSUE TITLE
Mailer cannot send using SMTP that requires no authentication.

### ISSUE THREAD

**Issue by Bodom78** [directus/directus#5652]
1) The issue and what you expected to happen
    Not setting a SMTP user/pass results in a `Missing credentials for "PLAIN"` error.
    I would like to use MailHog to test local emails and this issue is blocking that.

2) Exact steps to reproduce this issue
    Send an email with the Mail service using a mail server that does not require auth.

3) Your environment:
    Using Directus9 rc.64

4) Any other relevant information we might need to reproduce this issue
    Solution appears to be setting the nodemailer auth param to false when credentials are not required from here:
    https://github.com/nodemailer/nodemailer/issues/1142#issuecomment-635182293

   If no SMTP user and pass provided then would set false here: https://github.com/directus/directus/blob/9e93342af0a6b0689a6d23ea144a02eb1940d372/api/src/services/mailer.ts#L19

**Comment by rijkvanzanten** [comment]
@Bodom78 Wanna open a PR for that? 🙂 Should be as simple as checking if user/pass are both empty, and then setting auth to false instead of that object

**Comment by Bodom78** [comment]
@rijkvanzanten No problem, pull request https://github.com/directus/directus/pull/5673
