### ISSUE TITLE
CORS not working for multiple domains connecting to the same Directus instance

### ISSUE THREAD

**Issue by pzehle** [directus/directus#5657]
I have tried many possibilities, still CORS won't let me get through this.

I have a project on https://wolfsc.mx and another project on https://services.wolfsc.mx. Both connect to a Directus instance on https://content.wolfsc.mx via the Directus SDK.

Whatever domain I open first (root domain or subdomain) will load correctly but the other one will give a CORS error, I assume because of cache-control.

No matter what I put in the .htaccess of both files, or even add a CSV of the domains in the .env file (as suggested in the docs, which of course gives error of 'multiple values but only one allowed') I still get the same CORS block error.

Is there a way to address this? I need both the root and the subdomain to be able to connect to Directus, but I just don't seem to understand how. Thank you.

**Comment by rijkvanzanten** [comment]
Have you tried

```
"array:domain1.com,domain2.com"
```

as value for the option?

**Comment by pzehle** [comment]
Hey @rijkvanzanten 

Yes, my env looks like:

`CORS_ORIGIN="array:services.wolfsc.mx,wolfsc.mx"`

And I get this error:

`Access to XMLHttpRequest at 'https://content.wolfsc.mx/items/languages/?fields[]=*&fields[]=language_flag.id' from origin 'https://services.wolfsc.mx' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by rijkvanzanten** [comment]
Could you try adding the `https://` part to the CORS_ORIGIN setup? 🤔

**Comment by pzehle** [comment]
Now it at least loads. The problem is the same as before, whichever domain I load first, it will just cache the origin and won't let me reload the second. You can try opening both domains, then reload both and you will see that one of them will get CORS error and won't load anymore. :(

**Comment by pzehle** [comment]
My env looks like this:

```
CORS_ENABLED="true"
CORS_ORIGIN="array:https://services.wolfsc.mx,https://wolfsc.mx"
CORS_METHODS=GET,POST,PATCH,DELETE
CORS_ALLOWED_HEADERS=Content-Type,Authorization
CORS_EXPOSED_HEADERS=Content-Range
CORS_CREDENTIALS="true"
CORS_MAX_AGE=18000
```

I don't know if I should change something or if it is OK.

**Comment by rijkvanzanten** [comment]
Very odd! CORS is handled before the cache checks for cached responses, and Directus doesn't cache the headers 🤔 

Do you have any CDN in front that might be doing some header caching? Have you tried submitting `Cache-Control: no-cache` to see if that helps?

**Comment by pzehle** [comment]
> Very odd! CORS is handled before the cache checks for cached responses, and Directus doesn't cache the headers 🤔

Yeah personally I hate CORS, always the same.

> Do you have any CDN in front that might be doing some header caching? Have you tried submitting Cache-Control: no-cache to see if that helps?

No CDN. I installed Directus at https://content.wolfsc.mx, and using the SDK on both projects to fetch the data. Funny thing, localhost works for both without any problem.

Where should I put this? `Cache-Control: no-cache`

**Comment by pzehle** [comment]
I added this `Cache-Control: no-cache` in both `.htaccess` files. Still the same...

**Comment by rijkvanzanten** [comment]
> Yeah personally I hate CORS, always the same.

Agreed 😑

---

With the following env vars:

```
CORS_ENABLED="true"
CORS_ORIGIN="array:https://rijks.website,https://test.rijks.website"
CORS_METHODS=GET,POST,PATCH,DELETE
CORS_ALLOWED_HEADERS=Content-Type,Authorization
CORS_EXPOSED_HEADERS=Content-Range
CORS_CREDENTIALS="true"
CORS_MAX_AGE=18000
```

It seems to work as expected in a dev environment with no webserver (Apache) in between:

### Request 1

#### Request:
GET /relations?access_token=admin HTTP/1.1
**Origin: https://test.rijks.website**
Host: localhost:8055
Connection: close
User-Agent: Paw/3.2.2 (Macintosh; OS X/11.3.1) GCDHTTPRequest

#### Response:
HTTP/1.1 200 OK
X-Powered-By: Directus
**Access-Control-Allow-Origin: https://test.rijks.website**
Vary: Origin
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Content-Range
Content-Type: application/json; charset=utf-8
Content-Length: 2738
ETag: W/"ab2-wqXh98Xk6GzAxvu761Y/vuBVI88"
Date: Thu, 13 May 2021 19:55:19 GMT
Connection: close

### Request 2

#### Request
GET /relations?access_token=admin HTTP/1.1
**Origin: https://rijks.website**
Host: localhost:8055
Connection: close
User-Agent: Paw/3.2.2 (Macintosh; OS X/11.3.1) GCDHTTPRequest

#### Response
HTTP/1.1 200 OK
X-Powered-By: Directus
**Access-Control-Allow-Origin: https://rijks.website**
Vary: Origin
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Content-Range
Content-Type: application/json; charset=utf-8
Content-Length: 2738
ETag: W/"ab2-wqXh98Xk6GzAxvu761Y/vuBVI88"
Date: Thu, 13 May 2021 19:57:16 GMT
Connection: close

---

I noticed you mentioned `.htaccess` a couple times. Could it be that Apache itself is not passing on the Origin header and/or is caching headers somewhere somehow?

**Comment by pzehle** [comment]
I've removed it from the `.htaccess` files and I added it directly to Apache configuration. Still the same problem :(

Isn't there a way to use hardcode the headers from the Directus SDK? Any other workaround? I'm about to lose it and delete the project and never look back haha

**Comment by rijkvanzanten** [comment]
> Any other workaround?

Don't know yet! The problem here seems to exist somewhere between Directus and Apache, as it seems to behave as expected once we take Apache out of the equation 🤔 

What is the virtualhost configuration you're using in Apache? I'm assuming you have something along these lines somewhere?:

```
<VirtualHost *:80>
        ServerAdmin admin@example.com
        ServerName node.example.com
        ErrorLog /var/log/httpd/error.log
        CustomLog /var/log/httpd/access.log combined
        ProxyRequests On
        ProxyPass / http://localhost:8055
        ProxyPassReverse / http://localhost:8055
</VirtualHost>
```

**Comment by pzehle** [comment]
Yeah it is like this:

```
ServerAdmin **REMOVED**
ServerName content.wolfsc.mx
ServerAlias www.content.wolfsc.mx
DocumentRoot /var/www/content.wolfsc.mx
ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined

ProxyRequests On
ProxyPass / http://localhost:8055/
ProxyPassReverse / http://localhost:8055/
```

**Comment by pzehle** [comment]
Added all possible directives on both Apache config file and all my .htaccess files. Still the same. I even added the no-cache directives on the vhost file of Directus. Nothing.

**Comment by pzehle** [comment]
Isn't there a no-cache directive I can give to the .env file or even directly on express?

**Comment by rijkvanzanten** [comment]
You can turn caching off on the Directus side in the .env file, yeah. That will rule out Directus' caching altogether

**Comment by pzehle** [comment]
At this point I don't really care. Shouldn't be so hard to enable to informative websites. Now that this has become an issue, I am moving on future projects to nginx, damn Apache.

> You can turn caching off on the Directus side in the .env file, yeah. That will rule out Directus' caching altogether

Would you mind telling me exactly where should I put this?

**Comment by pzehle** [comment]
I actually have this in my .env file:

`CACHE_ENABLED=false`

So apparently I don't even have cache enabled.

**Comment by rijkvanzanten** [comment]
There's a `CACHE_ENABLED` environment variable (https://docs.directus.io/reference/environment-variables/#cache). You can set that to `false`.

---

I just tried hitting your URL manually setting the Origin header to both URLs you're mentioning... And it actually seems to work as expected 🤔🤔

![CleanShot 2021-05-13 at 16 24 21@2x](https://user-images.githubusercontent.com/9141017/118183089-b8046a80-b407-11eb-91a0-8838c5c6a1af.png)

![CleanShot 2021-05-13 at 16 24 52@2x](https://user-images.githubusercontent.com/9141017/118183152-c6eb1d00-b407-11eb-8a04-011fe0267eb2.png)

**Comment by pzehle** [comment]
Could you please try going directly to https://wolfsc.mx (check if it loads). Then go to https://services.wolfsc.mx and also check if it loads. Then go back to https://wolfsc.mx and it won't load anymore, stating that the header belongs to services so it blocks it.

**Comment by rijkvanzanten** [comment]
I think this might actually be the browser's cache!! 😵

When I open the devtools on your website everything worked. Once I re-enabled the browser cache and reloaded the issue started to show up

**Comment by pzehle** [comment]
Yeah the last website I visit caches the headers and won't let me load the past website. If this is indeed problem from the browser, maybe unrelated, but any ideas on how to bypass this?

**Comment by rijkvanzanten** [comment]
Very good question 🤔 I'm no expert on CORS myself, but here's what we know so far:

* The browser seems to be caching response headers based on the root domain
* CORS is based around the specific domain (so subdomain !== root domain)
* This causes the issue, as the browser uses the cached version that comes from the wrong subdomain

This is kinda strange, as the response explicitly states that the browser should invalidate the cache on every request:

<img width="338" alt="CleanShot 2021-05-13 at 16 31 35@2x" src="https://user-images.githubusercontent.com/9141017/118184090-eb93c480-b408-11eb-9d38-816836aedd60.png">

As per [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control):

> `no-cache`
> The response may be stored by any cache, even if the response is normally non-cacheable. However, the stored response MUST always go through validation with the origin server first before using it

It looks like the browser is caching the response headers, and only invalidates the actual body? 🤔

**Comment by rijkvanzanten** [comment]
Seems to be a known thing in Chromium https://bugs.chromium.org/p/chromium/issues/detail?id=260239 / https://bugs.chromium.org/p/chromium/issues/detail?id=159082. These tickets are saying that the problem shouldn't happen if you have the `Vary: Origin` header in the response (MDN says the same thing: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#cors_and_caching). However, Directus does in fact already set this header...

<img width="518" alt="CleanShot 2021-05-13 at 16 43 33@2x" src="https://user-images.githubusercontent.com/9141017/118185295-5e516f80-b40a-11eb-9712-4c0bd8c3b3a8.png">

**Comment by rijkvanzanten** [comment]
I'll close this issue for now, as Directus seems to do what it's instructed to do (the CORS Origin header is returned correctly). We can keep the discussion going tho

**Comment by pzehle** [comment]
Yeah you can close it, thanks.

Anyway, if this issue comes from the browser, there is nothing I can do? So Apache is not the problem, Directus not the problem. It is just the browser is doing what it wants? What can I do then? :(

**Comment by pzehle** [comment]
Would it be any different if I used axios or fetch API directly instead of the Directus SDK?

**Comment by rijkvanzanten** [comment]
From what I can tell, we (you and me) do everything right: We set the origin header based on the incoming domain, we set the Vary: Origin header, we set the cache-control header to the correct value, but for whatever reason firefox and chromium don't play along nicely :C 

> Would it be any different if I used axios or fetch API directly instead of the Directus SDK?

I don't think that matters, as it's the browser itself that does this caching on the XHR level (The SDK relies on Axios, which itself relies on XMLHttpRequest, so it's all the same thing).

---

One potential workaround is to explicitly tell the browser never-ever to store the cache by forcing the `Cache-Control` header to be `no-store` instead of no-cache 🤔

**Comment by pzehle** [comment]
> One potential workaround is to explicitly tell the browser never-ever to store the cache by forcing the Cache-Control header to be no-store instead of no-cache 🤔

Do you have any idea exactly where to put it? I did already tried on every .htaccess I have, on every vhost file and it makes no difference. I am about to become a gardener and never touch code again in my life haha

**Comment by rijkvanzanten** [comment]
If I recall correctly, you can add `Header always set Cache-Control "no-store"` in [your virtual host configuration](https://github.com/directus/directus/issues/5657#issuecomment-840805080)

> I am about to become a gardener and never touch code again in my life haha

Right there with ya! This stuff is impossible to debug/deal with 😭

**Comment by rijkvanzanten** [comment]
... Another workaround is putting that page under `https://wolfsc.mx/services` instead of `https://services.wolfsc.mx`, though I'm sure there's a range of reasons why it's on it's own subdomain in the first place 🙂

**Comment by pzehle** [comment]
> If I recall correctly, you can add Header always set Cache-Control "no-store" in your virtual host configuration

Tried this, still the same.

> ... Another workaround is putting that page under https://wolfsc.mx/services instead of https://services.wolfsc.mx, though I'm sure there's a range of reasons why it's on it's own subdomain in the first place 🙂 The upside of this is that you could enable the cache in Directus, and utilize the browser cache instead of fight it, which would improve the performance of your website a lot too 🤔

Yes this is also my last resort. We are using different subdomains becuase one is the website and the other is a hub for a lot of landing pages. Because both projects have different styles, it is a complete mess to have it inside a single React project. Also, this was the decision of the customer, so nothing to do there. Of couse I will do this if nothing else works, but yeah, makes sense then.

> ... Or you could set the cors origin to *, though that's not that secure

This doesn't work because Directus forces the 'Include Credentials' directive, and with that, you cannot use '*' as the origin. Unless there is a way to tamper with the Directus SDK (which I have no idea how and where), this is not an option :(

**Comment by rijkvanzanten** [comment]
> Yes this is also my last resort. We are using different subdomains becuase one is the website and the other is a hub for a lot of landing pages. Because both projects have different styles, it is a complete mess to have it inside a single React project. Also, this was the decision of the customer, so nothing to do there. Of couse I will do this if nothing else works, but yeah, makes sense then.

You could keep it two different react apps, and use Apache's virtual proxy to point it to both, but yeah i get what you're saying

> This doesn't work because Directus forces the 'Include Credentials' directive, and with that, you cannot use '*' as the origin. Unless there is a way to tamper with the Directus SDK (which I have no idea how and where), this is not an option :(

@wolfulus went full overkill on the SDK side. I'm pretty sure you can override the underlying Transport it uses to make requests, and therefore alter the headers sent etc.

Are you going to be doing any authenticated requests? Any logins from these apps? If not, this might be the best solutino

**Comment by pzehle** [comment]
> You could keep it two different react apps, and use Apache's virtual proxy to point it to both, but yeah i get what you're saying

Apache sucks, CORS sucks, so no thanks haha it has to be a single project or multiple projects in different domains.

> Are you going to be doing any authenticated requests? Any logins from these apps? If not, this might be the best solutino

Not really, this is only a website with information, and landing pages for marketing. It has forms, but no authentication whatsoever. It would be nice to solve this on the SDK side not to spend a lot of time joining the projects together.

**Comment by WoLfulus** [comment]
@pzehle try overriding the request config using an interceptor. Let me know if that works

```ts
const sdk = new Directus();
sdk.transport.axios.interceptors.request.use((config) => {
  config.withCredentials = false;
  return config;
}, (error) => Promise.reject(error));
```

**Comment by pzehle** [comment]
@WoLfulus thank you.

Sorry for the trouble, but as you can see I am a noob with this stuff. Could you please point me in the right direction?

I am initializing Directus like this:

`const directus = new DirectusSDK('https://content.wolfsc.mx/');`

Should this code go here? Or somewhere else? Thank you.

**Comment by rijkvanzanten** [comment]
@pzehle I believe you'd add @WoLfulus 's example right below that:

```js
// What you already have:
const directus = new DirectusSDK('https://content.wolfsc.mx/');

// What you add:
directus.transport.axios.interceptors.request.use((config) => {
  config.withCredentials = false;
  return config;
}, (error) => Promise.reject(error));
```

**Comment by pzehle** [comment]
`TypeError: Cannot read property 'axios' of undefined`

HAHA! One more error like this and I am shutting down this project xD

**Comment by pzehle** [comment]
So, guys, as usual thank you very much. I ran into too much trouble trying to fix it, but I talked to the customer and decided to go for the subdirectory. I guess I will continue to hate CORS and now caching in general. Anyway, it is fixed, and it is good to know that this is not possible, or even a pain in the back to acomplish something like this, note for the future.

Thank you very much!
