### ISSUE TITLE
🚨 Potential Cross-site Scripting (XSS) - Stored

### ISSUE THREAD

**Issue by huntr-helper** [directus/directus#5677]
👋 Hello, @rijkvanzanten, @benhaynes, @dependabot-preview[bot] - a potential high severity Cross-site Scripting (XSS) - Stored vulnerability in your repository has been disclosed to us.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/1-other-directus/directus** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by rijkvanzanten** [comment]
Security vulnerabilities should be reported through security@directus.io, as per https://github.com/directus/directus/blob/main/security.md.

Bugs with bounties can be found on our IssueHunt: https://issuehunt.io/r/directus/directus.
