### ISSUE TITLE
Auth0 login complains about missing `refresh_token`

### ISSUE THREAD

**Issue by arienkock** [directus/directus#5680]
1) The issue and what you expected to happen
  I've configured Auth0 OAuth on top of an existing user database. I've tried logging in with a user whose email address already existed in the user table. The Auth0 logs show that the login was successful. However, Directus redirects me to `http://localhost:8055/admin/login?reason=SERVICE_UNAVAILABLE` and the DevTools console shows a 400 HTTP error:
```
{"errors":[{"message":"\"refresh_token\" is required in either the JSON payload or Cookie","extensions":{"code":"INVALID_PAYLOAD"}}]}
```

2) Exact steps to reproduce this issue
    1. Create Diretctus instance with one admin user. 
    2. Stop directus, config Auth0 as only OAuth provider.
    3. Log in with admin user email using Auth0

3) Your environment:
    What version of Directus you are using: ^9.0.0-rc.64

    Which DBMS are you using (MySQL 8, Postgres 12, ...).: SQLite
    Which deployment are you using (npx, Docker, ...): Npx
    What browser are you using (Chrome 87, Safari 14, ...): Latest Chrome

4) Any other relevant information we might need to reproduce this issue
    A SQL dump of the setup:  (Local playground environment) [dump.txt](https://github.com/directus/directus/files/6479136/dump.txt)
    
   What third party services you rely on (S3, managed database, ...): Auth0

**Comment by rijkvanzanten** [comment]
@arienkock Directus sets that refresh token in a cookie on successful login. Could it be that you have cookies disabled or some other thing/extension running that might interfere with that?

**Comment by arienkock** [comment]
I just checked. I disabled the only browser extension I have, and got the same behavior. Also there was a different cookie successfully set:
<img width="716" alt="Screen Shot 2021-05-14 at 18 22 30" src="https://user-images.githubusercontent.com/2857600/118299729-65977c80-b4e1-11eb-89b4-e81842fe7711.png">

**Comment by rijkvanzanten** [comment]
What environment variables do you have configured? There's 3 related to Cookie security that might cause havoc on localhost:

https://docs.directus.io/reference/environment-variables/#security

**Comment by arienkock** [comment]
After further debugging (adding copious amounts of `console.log`) I discovered that the problem lay in a missing env variable `OAUTH_AUTH0_PROFILE_URL` which is different per Auth0 domain/app, and thus requires configuration.. The default behavior of the `grant` library was to fetch the profile from `https://127.0.0.1:443` for some odd reason. Sorry for the false alarm. Hopefully this will save someone some time.

**Comment by rijkvanzanten** [comment]
Ahh! Good to know 👍🏻
