### ISSUE TITLE
"Enforce 2FA" doesn't trigger on login

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#5682]
1) The issue and what you expected to happen

When logging in with a user in a role that has enforce 2fa enabled, the app should force you into the tfa-setup flow immediately.

2) Exact steps to reproduce this issue

Enable enforce 2fa, and login

**Comment by zappatero** [comment]
I have the issue in 9.0.0 rc64 that I can't activate 2FA on the user in the backend.
Shouldn't this be a checkbox to activate 2FA instead of an empty string field?
![image](https://user-images.githubusercontent.com/42898262/118323354-c4202300-b500-11eb-8fb1-ea39d36ab77d.png)

**Comment by Nitwel** [comment]
How would we want to enforce that the user sees the tfa setup flow?
We can't just use the user page with the 2fa setup field as there is no way to activate that.

Should this maybe be a new feature to the login flow so when you just logged in and have 2fa enforced, you get to a custom 2fa setup flow that looks the same way as the public page?

**Comment by rijkvanzanten** [comment]
> Should this maybe be a new feature to the login flow so when you just logged in and have 2fa enforced, you get to a custom 2fa setup flow that looks the same way as the public page?

That's the only thing we can do, yeah. We do also have to think through permissions in that case, cause you end up in a weird in-between state where you're semi-logged in (logged in enough to setup TFA, but not logged in enough to use the app) 🤔

**Comment by Nitwel** [comment]
I've made it now that you always get redirected to `/tfa-setup` when logged in while `enforce tfa` is enabled and you haven't set it up yet. Makes it less complicated than having some sort of semi logged in state. Enforcing this only on the app side should be enough as you don't really use tfa from somewhere else.
