### ISSUE TITLE
🚨 Potential Execution with Unnecessary Privileges

### ISSUE THREAD

**Issue by huntr-helper** [directus/directus#5686]
👋 Hello, @rijkvanzanten, @benhaynes, @dependabot-preview[bot] - a potential high severity Execution with Unnecessary Privileges vulnerability in your repository has been disclosed to us.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/3-other-directus/directus** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by ranjit-git** [comment]
Hi @rijkvanzanten ,
Its safe to use https://huntr.dev/ for security vulnerability  validation . They maintain private database to keep the vulnerability details private .
You can validate the bug details there .
Or you can keep the details private there  so that it will be visible to only repo maintainer .
Huntr is security platform for open  open-source project .
Thanks

**Comment by rijkvanzanten** [comment]
Security vulnerabilities should be reported through security@directus.io, as per https://github.com/directus/directus/blob/main/security.md.

Bugs with bounties can be found on our IssueHunt: https://issuehunt.io/r/directus/directus.

**Comment by JamieSlome** [comment]
@rijkvanzanten - will send these reports via your preferred process now (#5686 #5677 #5678).

Cheers! 🍰

**Comment by ranjit-git** [comment]
@JamieSlome  those report has been sent through email . 
 Some of them are validated .
Should i send you the details so that you can validate them in huntr

**Comment by JamieSlome** [comment]
@ranjit-git - apologies, sure! 👍
