### ISSUE TITLE
Cannot login after initial setup.

### ISSUE THREAD

**Issue by Oreilles** [directus/directus#5688]
This appeared somewhere between `rc.64` and `rc.65`.
Reproduce:
* Run `npm cli bootstrap` on a fresh database
* Try to login with the given admin username and password
* `401: Wrong username or password`

Tested on postgres:13.

**Comment by rijkvanzanten** [comment]
Found it, pushing up a fix now 👍🏻

**Comment by LeRouxJonathan** [comment]
Having this same issue on self-hosted directus on linux ubuntu 22.04. Username and password are invalid no matter what. Literally have the .yaml file used for setup in front of me and copy-pasting in the username and password, also manually typed it verbatim as well.

**Comment by rijkvanzanten** [comment]
@LeRouxJonathan This is an issue from over 2.5 years ago. Whatever problem you're facing in the latest version is nearly guaranteed not related to a bug in v9.0.0-rc.65; mind opening a new issue? Thanks
