### ISSUE TITLE
Display Template does not match values shown in table view

### ISSUE THREAD

**Issue by David-Lor** [directus/directus#5690]
**Issue:**

The values displayed on relation columns in table view do not match the configured Display Template.

Having this relationship with a configured Display Template (although the name is "Container ID", this is not the primary key of the associated table):
![relationship](https://user-images.githubusercontent.com/17401854/118339853-6698d000-b51a-11eb-8499-0a1591795f7f.png)

Shows the incorrect value on table view (shows the id-primary key field instead of what is configured on the Display Template):
![table view](https://user-images.githubusercontent.com/17401854/118339937-a2339a00-b51a-11eb-9175-17f7f1deb414.png)

The detail view shows the **correct value**:
![detail view](https://user-images.githubusercontent.com/17401854/118340039-e0c95480-b51a-11eb-872e-656b8b24d364.png)

Here's a preview of the associated table:
![associated table](https://user-images.githubusercontent.com/17401854/118340069-f63e7e80-b51a-11eb-821f-61fb09f93070.png)

No errors in logs.

**Things tried:**

- Open from other browser
- Set empty Display Template, then set desired Display Templated
- Change Display Template to the shown value, then set desired Display Template

**Setup:**

- directus:v9.0.0-rc.64 (docker)
- postgres 12.6

**Comment by rijkvanzanten** [comment]
The interface options don't affect the displays used on the layouts. Configure the Display instead 👍🏻 (In this case you're looking for the Related Values display)

**Comment by David-Lor** [comment]
@rijkvanzanten Thank you, now I got it, I guess what I'm looking for is under Display > Related Values:

![imagen](https://user-images.githubusercontent.com/17401854/118340634-8c26d900-b51c-11eb-89c6-35eb614e1966.png)

I think it's a bit confusing though.
