### ISSUE TITLE
Column directus_relations.many_primary does not exist

### ISSUE THREAD

**Issue by aleksejssaburovs92** [directus/directus#5691]
1) When upgrading to rc-66, logging in causes 

[INTERNAL_SERVER_ERROR] select "directus_relations"."id", "directus_relations"."many_collection", "directus_relations"."many_field", "directus_relations"."one_collection", "directus_relations"."one_field", "directus_relations"."one_collection_field", "directus_relations"."one_allowed_collections", "directus_relations"."junction_field", "directus_relations"."sort_field", "directus_relations"."one_deselect_action", "directus_relations"."many_primary", "directus_relations"."one_primary" from "directus_relations" order by "directus_relations"."id" asc - column directus_relations.many_primary does not exist

2) Upgrade directus to rc-66, log in as always

3) Your environment:
    Directus rc-66
   PostgreSQL 9.3.16
    Docker, docker-compose

<img width="1792" alt="Screenshot 2021-05-15 at 02 32 59" src="https://user-images.githubusercontent.com/12848012/118340928-e4160d80-b525-11eb-9775-72a667dc9979.png">

**Comment by marendra** [comment]
same here, just installed a few minutes ago

**Comment by emekatoby** [comment]
So sad

**Comment by doodlemania2** [comment]
+1 same here

**Comment by rijkvanzanten** [comment]
Seems like some residual files from a non-main branch snuck into the distribution (potentially from a build cache?). Just pushed out a new dist from a clean pull which should do the trick 👍🏻

**Comment by doodlemania2** [comment]
Updating now!

**Comment by marendra** [comment]
@doodlemania2  can you tell me how to the update? thanks

**Comment by doodlemania2** [comment]
i just swapped up to .67 on the docker image, however, still getting the same error - looking at the logs to see if there was a db migration in there requiring a db rollback

**Comment by marendra** [comment]
i just create new clean directus using CLI and not docker, and create those errors

**Comment by doodlemania2** [comment]
yeah, looks like there's still a bug here - standing by for our leader to advise!

**Comment by marendra** [comment]
@rijkvanzanten sir, please open this issue again, due to the bug still there

**Comment by doodlemania2** [comment]
yeah, looks like a db migration snuck in there called "Restructure Relations" - could be simple fix, looking for that migration now.

**Comment by doodlemania2** [comment]
can't seem to find 20210510A in any of the recent tags, expanding search

**Comment by doodlemania2** [comment]
Found it! https://github.com/directus/directus/blob/relations/api/src/database/migrations/20210510A-restructure-relations.ts
Now, just need to figure out how to "downgrade" without hosing everything further.

**Comment by Bodom78** [comment]
Upgrading from .64 to .67 and running migrations resulted in this error as well.

Unless I missed something, perhaps a future enhancement to the `directus database migrate` could be to ask to create a backup prior to running.

**Comment by botzill** [comment]
Having the same issue upgrading to `.67`. What can we do at this point ?

**Comment by botzill** [comment]
Downgrade to `.64` still having same error:

<img width="799" alt="Screen Shot 2021-05-15 at 08 17 12" src="https://user-images.githubusercontent.com/4686040/118348905-f90a9500-b555-11eb-941d-b762786fddb1.png">

**Comment by botzill** [comment]
@doodlemania2 let us know if you find anything on how to downgrade easily.

Thx!

**Comment by botzill** [comment]
What I did for now to make it start in `.67`, just added this 2 columns in DB directly, set them to `null`. 
 Once this is fixed, I will just remove them from db as well manually, hope this will fix the issue. 
 
<img width="433" alt="Screen Shot 2021-05-15 at 08 33 11" src="https://user-images.githubusercontent.com/4686040/118349233-2b1cf680-b558-11eb-8060-8ff30fda775c.png">

**Comment by botzill** [comment]
OK, upgraded to `.67` and added `many_primary` and `one_primary` to `id`. I checked some older backup and I see I have only `id` value for these columns. 

Now it's running ok.

**Comment by neo7-studio-web** [comment]
Same here upgrading and migrating from .64 to .67

**Comment by martinemmert** [comment]
So this means the structure of the relations will change again with this migration? 
Having written my own database seed script do add custom collections and their fields & relations. 

Regularly changing the structure and behavior of inner workings shouldn't be part of a release candidate.
Those are breaking changes and should be flagged as such :-|

**Comment by marendra** [comment]
@martinemmert not just updating, me trying clean sheet, has the same error too

**Comment by martinemmert** [comment]
I backtracked the version which introduced this error inside clean Docker installs.
The last working version is `9.0.0-rc.64`
`9.0.0-rc.65` is not released and can't be installed
`9.0.0-rc.66` introduced this bug.

The difference is the missing field `many_primary` in the table, like the error message is telling us.

**Comment by neo7-studio-web** [comment]
> 
> 
> OK, upgraded to `.67` and added `many_primary` and `one_primary` to value `id`. I checked some older backup and I see I have only `id` value for these columns.
> 
> Now it's running ok.

What do you mean by added `many_primary` and `one_primary` to value `id` ?

**Comment by martinemmert** [comment]
> yeah, looks like a db migration snuck in there called "Restructure Relations" - could be simple fix, looking for that migration now.

This is really odd:
How could this be unseen for the last 2 releases since it is coming up right after logging in to the admin?
Also, How could the file be included in any release since it is not available on any tag? 🤔

**Comment by martinemmert** [comment]
I worked around this issue currently by creating my own Dockerfile and remove the migration file after `npm install`

```
FROM directus/directus:v9-rc.67

WORKDIR /directus

COPY package.json package-lock.json ./

RUN npm install
RUN rm ./node_modules/directus/dist/database/migrations/20210510A-restructure-relations.js
```

**Comment by rijkvanzanten** [comment]
> How could this be unseen for the last 2 releases since it is coming up right after logging in to the admin?

Your second question answer this:

> Also, How could the file be included in any release since it is not available on any tag? 🤔

This is what I'm trying to figure out right now!

The reason this didn't show up earlier is that.. it didn't exist on main / in the release tests

**Comment by rijkvanzanten** [comment]
There was indeed a problem in the deployment flow where residual files weren't cleaned up in some cases, which is resolved in the commit linked above.

For those affected by this, you can:

* Rollback the wrong migration `20210510A` by using `npx directus database migrate:down`
* Set the `many_primary` / `one_primary` column in `directus_relations` to `id`
* Update to rc.68 

and you're back to normal 👍🏻 

That bad migration is scheduled to be released very soon, but not _this_ soon

**Comment by doodlemania2** [comment]
Do I do all of those steps or just one?

**Comment by marendra** [comment]
@rijkvanzanten how about the one to create from clean sheet?

**Comment by rijkvanzanten** [comment]
@doodlemania2 All of them in order 👍🏻 The first two undo the damage from this build artifact, the third makes sure this doesn't happen again 👍🏻 

> @rijkvanzanten how about the one to create from clean sheet?

@marendra You can just install rc.68 like normal, no changes required there 👍🏻

**Comment by emregency** [comment]
I need also help here 😢 

1. How can I run the rollback for a docker-compose deployment?
2. What does exactly `Set the many_primary / one_primary column in directus_relations to id` look like in SQL?

**Comment by rijkvanzanten** [comment]
> How can I run the rollback for a docker-compose deployment?

Seeing that docker-compose boots up the container at a given version, I'd imagine you'd run the migration manually once outside of docker compose, and then have it run the specified version.

> What does exactly Set the many_primary / one_primary column in directus_relations to id look like in SQL?

```sql
UPDATE directus_relations SET many_primary = "id", one_primary = "id";
```

**Comment by nedvajz** [comment]
based on @Bodom78 I run `npx directus database migrate:latest` what solves the problem for me  
  
I moved project from one machine to another and newer directus version on new machine cause me trouble .. thanks for hints ..
