### ISSUE TITLE
Unable to use Directus after upgrade, fails to start missing relation table errors

### ISSUE THREAD

**Issue by isawk** [directus/directus#5702]
After upgrading directus and running npx directus bootstrap to update database tables if need be, application is crashing with database relational table missing error.

### Product details
Directus Version: 9.0.0-rc.68
Environment: production
OS: Linux 4.4.0
Node: 14.16.1

### Steps to reproduce

- npm update
- npx directus bootstrap 
to update database tables, based on description assuming necessary to run this command after every upgrade
- npx directus start

After above try login to directus, and errors below are produced

### Error Message

```

{
  "errors": [
    {
      "message": "select \"directus_relations\".\"id\", \"directus_relations\".\"many_collection\", \"directus_relations\".\"many_field\", \"directus_relations\".\"one_collection\", \"directus_relations\".\"one_field\", \"directus_relations\".\"one_collection_field\", \"directus_relations\".\"one_allowed_collections\", \"directus_relations\".\"junction_field\", \"directus_relations\".\"sort_field\", \"directus_relations\".\"one_deselect_action\", \"directus_relations\".\"many_primary\", \"directus_relations\".\"one_primary\" from \"directus_relations\" order by \"directus_relations\".\"id\" asc - column directus_relations.many_primary does not exist",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```
![Error Screenshot](https://user-images.githubusercontent.com/21027753/118382364-db403d00-b5f4-11eb-9acd-3572cae64233.png)

**Comment by martinemmert** [comment]
https://github.com/directus/directus/issues/5691
