### ISSUE TITLE
Validation error shown in wrong form context

### ISSUE THREAD

**Issue by CodeAndWeb** [directus/directus#5707]
Validation for "unique" entries is wrong on many to many relation ships.

Model 1: 

    Ingredient
      name: string, unique

Model 2:

    Recipe:
     name: unique
     ingredients: Ingredient[]

- Create some ingredients - e.g. "Sugar"
- Create a new recipe
- Click on "Add new" in the ingredients list, add "Sugar" again (should display an error here since it already exists)
- Click on Save.

-> Result is a save error, with Recipe.name highlighted. Which is wrong.

---

### Project details
Directus Version: 9.0.0-rc.68
Environment: production
OS: Linux 5.10.25-linuxkit
Node: 14.16.1

**Comment by rijkvanzanten** [comment]
Note to self: Validation errors that are thrown from a nested data set are shown as validation errors on the top level form. Ideally, the API could return a path of where the error is thrown (eg `ingredients.ingredient.name` instead of just `name`)

**Comment by CodeAndWeb** [comment]
Sorry... not interested anymore.... found another solution.

**Comment by rijkvanzanten** [comment]
OK! That doesn't mean that the issue is resolved though 🙂

**Comment by CodeAndWeb** [comment]
Can somebody please clone this issue? I don't want to keep it hanging in my "open issues" in GitHub...
