### ISSUE TITLE
Cannot unregister myself (delete my account)

### ISSUE THREAD

**Issue by Meldiron** [directus/directus#5708]
MySQL: MariaDB 10
Directus: RC68

When I try to delete DIrectus user (admin), it shows this error:

![image](https://user-images.githubusercontent.com/19310830/118409306-1e002480-b68a-11eb-8e9b-6fb315aad6d2.png)

It may be happening because user is currently logged into an administration.

**Comment by rijkvanzanten** [comment]
Duplicate of https://github.com/directus/directus/issues/5528
