### ISSUE TITLE
Users cannot be assigned multiple roles

### ISSUE THREAD

**Issue by BinaryBen** [directus/directus#5720]
1) The issue and what you expected to happen
    Adding an user with the role admin to another role locks them out of the admin portal. A user should be able to be assigned to multiple roles and inherit the highest permissions for each resource.

2) Exact steps to reproduce this issue
    From a fresh install, add the original admin user to the member role

3) Your environment:
    Not relevant, but can provide if needed

I'm assuming I can fix the issue of being locked out manually in the database. But I am anticipating a lot of use cases where I want to be able to assign users different roles without having to create roles that are supersets.

For example, a "member" might also be a "contributor" but a "contributor" might not be a "member"

**Comment by paescuj** [comment]
See https://github.com/directus/directus/discussions/4959
