### ISSUE TITLE
Thumbnail generaton on S3

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [directus/directus#5722]
Hi all, I am trying to upload my files with directus v9.0.64

I have configured `.env` file using S3 in this way:

```
STORAGE_LOCATIONS="aws"
STORAGE_AWS_DRIVER= "s3"
STORAGE_AWS_KEY= "KEY"
STORAGE_AWS_SECRET= "XXX
STORAGE_AWS_BUCKET= bucket"
STORAGE_AWS_REGION= "eu-west-1"
```

I can see that the file is uploaded with success but it doesn't create thumbnails and I have errors inside CMS because I can't see thumbnails.

How can I solve this?
Bucket S3 has all permissions to create files.

Thanks.

**Comment by rijkvanzanten** [comment]
Hard to say without more specifics on your exact configuration in both Directus and AWS's permissions for this bucket. I can confirm that it seems to work as expected on a new installation on my end, so I'm assuming this is a configuration problem 🤔

**Comment by WayneEld** [comment]
> Hi all, I am trying to upload my files with directus v9.0.64
> 
> I have configured `.env` file using S3 in this way:
> 
> ```
> STORAGE_LOCATIONS="aws"
> STORAGE_AWS_DRIVER= "s3"
> STORAGE_AWS_KEY= "KEY"
> STORAGE_AWS_SECRET= "XXX
> STORAGE_AWS_BUCKET= bucket"
> STORAGE_AWS_REGION= "eu-west-1"
> ```
> 
> I can see that the file is uploaded with success but it doesn't create thumbnails and I have errors inside CMS because I can't see thumbnails.
> 
> How can I solve this? Bucket S3 has all permissions to create files.
> 
> Thanks.

I can see generate thumbnails from the credentials types added above. All seems to be working.
