### ISSUE TITLE
All required fields are required when updating item

### ISSUE THREAD

**Issue by broodroosterdev** [directus/directus#5723]
1) The issue and what you expected to happen
    The GraphQL endpoints returns an validation error about missing required fields 
    when updating a single field
    while it should simply update the single field and leave the required fields as-is

2) Exact steps to reproduce this issue

1. Add a custom field to the directus_users tabel
2. Update that field of the user with `update_users_item` `data: { your-field: "value" }`
3. Check the response for the returned validation errors

3) Your environment:
    What version of Directus you are using: v9.0.0-rc.68 (Latest)
    Which DBMS are you using (MySQL 8, Postgres 12, ...): Postgres 13
    Which deployment are you using (npx, Docker, ...): Docker
    What browser are you using (Chrome 87, Safari 14, ...): Firefox 88

4) Any other relevant information we might need to reproduce this issue
    None

**Comment by broodroosterdev** [comment]
It seems like its related to this issue: https://github.com/directus/directus/issues/5544
In particular, this part: https://github.com/directus/directus/blob/9e93342af0a6b0689a6d23ea144a02eb1940d372/api/src/services/graphql.ts#L317

This problem did not exist on version `v9.0.0-rc.64`

**Comment by rijkvanzanten** [comment]
Good one. The `GraphQLNonNull` part should be ignored in updates I suppose 🤔

(This is another interesting quirk in GraphQL.. To me, required !== not null. In the case of this update, the field isn't allowed to be value `null`, eg non-null. However, in GraphQL this means that the field has to be passed in the payload :C )

**Comment by rijkvanzanten** [comment]
We'll remove all the non-nulls in update types. For future readers, please see https://github.com/graphql/graphql-spec/issues/476 for more information.

**Comment by shkreios** [comment]
I still run into this bug when trying to create a translation. I created the translation table automatically. Is this expected behavior?

### Project details
Directus Version: 9.0.0-rc.69
Environment: production
OS: Linux 5.4.0-73-generic
Node: 14.16.1

**Comment by rijkvanzanten** [comment]
@shkreios The fix wasn't released yet. See the milestone in the right hand sidebar 👍🏻 

<img width="429" alt="Screen Shot 2021-05-25 at 6 30 10 PM" src="https://user-images.githubusercontent.com/9141017/119576725-4cb38480-bd87-11eb-984e-e205e57317aa.png">

**Comment by wc-matteo** [comment]
@rijkvanzanten trying to insert an item with graphql requires you to input the pk (which is autogenerated in this case).

The graphql type `create_<collection>_item`:
![image](https://user-images.githubusercontent.com/10562635/119888872-2ed85200-bf36-11eb-95b6-be37bf096b46.png)

the "required" graphql annotation shouldn't be present for columns that have a default value

---

on `mssql 2016` / `v9.0.0-rc.69`
