### ISSUE TITLE
directus tries to create a nullable primary key when the type is NOT `auto-incremented integer`

### ISSUE THREAD

**Issue by wc-matteo** [directus/directus#5730]
Trying to create a collection with a primary key of type `Generated UUID` or `Manually entered string` results in:
```
[INTERNAL_SERVER_ERROR] CREATE TABLE [foobar] ([id] uniqueidentifier null, CONSTRAINT [foobar_pkey] PRIMARY KEY ([id])) - Could not create constraint or index.
```

#### Software
- Directus v9.0.0-rc.68
- Microsoft SQL Server 2016
- Docker
- Chrome

**Comment by rijkvanzanten** [comment]
We should add `.notNull()` here:

https://github.com/directus/directus/blob/ceb5788602005a6e56dbdb9e2da726125a4ac27b/api/src/services/fields.ts#L434-L436

Wanna open a PR for that @wc-matteo?
