### ISSUE TITLE
this_1.parseDefaultValue is not a function 

### ISSUE THREAD

**Issue by ferdigokdemir** [directus/directus#5733]
Directus version: 9.0.0-rc.68
Database: Postgresql
Deployment: Docker
Browser: Chrome 90

**Comment by ferdigokdemir** [comment]
<img width="971" alt="Screen Shot 2021-05-17 at 22 16 11" src="https://user-images.githubusercontent.com/23097465/118543843-81a75200-b75d-11eb-943d-cd5ff2e8252c.png">

**Comment by rijkvanzanten** [comment]
@Oreilles / @aidenfoxx guess https://github.com/knex/knex-schema-inspector/pull/47/files had a little unintended breaking changes side-effect 👀

**Comment by fairhat** [comment]
@rijkvanzanten could you pin the dependencies for the next rc? ^1.3.0 assumes that 1.5.2 will work since this is not considered a breaking semver change

**Comment by Oreilles** [comment]
Oopsie. 🥬
By the way, shouldn't we use `tableInfo` and `columnInfo` here ? The SQL code is essentially the same and serves that exact purpose.

**Comment by rijkvanzanten** [comment]
>  could you pin the dependencies for the next rc? ^1.3.0 assumes that 1.5.2 will work since this is not considered a breaking semver change

No, cause we want those updates to come in still. This external breaking change was an accident

**Comment by rijkvanzanten** [comment]
> By the way, shouldn't we use tableInfo and columnInfo here ? The SQL code is essentially the same and serves that exact purpose.

Not necessarily. The schema overview sql is optimized to fetch just the parts we need within Directus' schema handling (it's the least amount of info possible).

> Also, it's really confusing that columnInfo is used in fields.ts and not here: depending on where you are in the application, the column schema are different.

I disagree. Similar to the first point, the schema overview used by the services internally is a minimal overview of the whole schema, while the output of the fields service (eg the `/fields` endpoint / mutation) is a "full view" of the fields/columns. They serve very different purposes 👍🏻

**Comment by fairhat** [comment]
> > could you pin the dependencies for the next rc? ^1.3.0 assumes that 1.5.2 will work since this is not considered a breaking semver change
> 
> No, cause we want those updates to come in still. This external breaking change was an accident

which rc can we downgrade to to get it working while the bug is still there?
tried down to rc62 and it still didn't work

**Comment by rijkvanzanten** [comment]
@fairhat you can install `knex-schema-inspector@1.3.0`

**Comment by fairhat** [comment]
> @fairhat you can install `knex-schema-inspector@1.3.0`

Thanks, putting it under "resolutions" in package.json made it work with yarn

**Comment by nickluger** [comment]
Still experiencing this on `9.0.0-rc.69`

**Comment by fairhat** [comment]
> Still experiencing this on `9.0.0-rc.69`

add
```json
"resolutions" {
   "knex-schema-inspector": "1.3.0"
}
```
to your package.json and run "yarn install"

**Comment by nickluger** [comment]
Sorry, my fault. `"knex-schema-inspector": "1.3.0"` and `resolutions` is not necessary. Had to delete my `yarn.lock` file, though.

**Comment by rijkvanzanten** [comment]
Pinning it to 1.3.0 is no longer necessary @fairhat 👍🏻
