### ISSUE TITLE
Bug - O2M relations with directus_fields

### ISSUE THREAD

**Issue by averdesca** [directus/directus#5748]
Trying to add a O2M relations with the collection directus_fields breaks the Admin UI. 

Steps:
1) create a new collection meta_fields with a field named "field" as O2M linked to the field meta_id of the collection directus_fields

2) Go to /admin/collections/ and select the collection "Meta Fields".

3) Try to create a new Item
4) Try to add an existing Field 

Current Behaviour:
Cannot select one value. If I check one value, all values are selected. If I uncheck one value, all values are unchecked.

Expected Behaviour: 
Only one value to be checked

Env:
Directus version: v9.0.0.rc64
DBMS: MYSQL 8

**Comment by rijkvanzanten** [comment]
It's currently not possible to have relationships from/to certain system collections, including collections and fields. Collections, fields, and relations all don't rely on "regular" primary keys you'd find in any other collections, but are based around the table(+column) name of the database column, which also means that they might not even have a row under the `directus_*` collections.

We'll add a check that prevents these non-usable collections from showing up in the relational setup flow, and add a new feature request to allow for relationships to exist to these specific system fields 👍🏻

**Comment by rijkvanzanten** [comment]
Ref https://github.com/directus/directus/discussions/5819
