### ISSUE TITLE
registerDisplays function does not use EXTENSIONS_PATH variable.

### ISSUE THREAD

**Issue by B-Esmaili** [directus/directus#5758]
At following line you use `extensions/displays` as constant literal and this results in conflict with API route `/extensions/<textension-type>` route.
https://github.com/directus/directus/blob/801e86855452bd32d49475d8b07ce151c11e962a/app/src/displays/register.ts#L27

**Comment by rijkvanzanten** [comment]
This is how it's supposed to be 🤔 

> and this results in conflict with API route /extensions/<textension-type> route.

what do you mean in results in conflict? Are you getting any errors?

> registerDisplays function does not use EXTENSIONS_PATH variable.

It shouldn't? The extensions folder path isn't publicly accessible through the regular endpoints, but it's contents are served through the scoped `/extensions/<type>` route. `/extensions/displays` returns the names of all available displays, `/extensions/displays/image/index.js` returns the actual display. ref https://github.com/directus/directus/blob/main/api/src/controllers/extensions.ts

**Comment by B-Esmaili** [comment]
> This is how it's supposed to be 
> 
> >

shouldn't it be something like

```
const result = await import(				
/* webpackIgnore: true */ getRootPath() + `${EXTENSIONS_PATH}/displays/${displayName}/index.js`				);

```
?



> what do you mean in results in conflict? Are you getting any errors?
> 
> >

yes i am getting following error :
![Capture](https://user-images.githubusercontent.com/9152515/119004427-cfad9700-b9a3-11eb-81a6-ac762ac34604.PNG)

**Comment by rijkvanzanten** [comment]
> shouldn't it be something like

Nope! The app isn't aware of the environment variables on the API, and the API is handling the routing from the /extensions endpoint to the actual file on disk 👍🏻 

> yes i am getting following error :

That's very odd 🤔 It seems to load just fine on my end. How are you running Directus? Any extensions or server software in between that might cause issues?

<img width="510" alt="CleanShot 2021-05-21 at 10 26 19@2x" src="https://user-images.githubusercontent.com/9141017/119153170-007ee200-ba1f-11eb-87bc-c55d8ff0da49.png">

**Comment by B-Esmaili** [comment]
I am running directus locally by issuing `npx directus start` command. Is there any boilerplate/sample for directus with extension?

**Comment by rijkvanzanten** [comment]
See https://docs.directus.io/guides/displays/ 👍🏻

**Comment by B-Esmaili** [comment]
One more thing. It is apparent from my highlighted area that the request is trying to load a javascript file right? And if i am not mistaken there is an endpoint with `/extensions/<extension-type>s` as following image :
![Capture](https://user-images.githubusercontent.com/9152515/119187478-a87fc400-ba8e-11eb-862e-4677531d3bf5.PNG)
this is what I have mentioned in the original post(the conflict). But still, I have no idea how it's working on your end.

**Comment by rijkvanzanten** [comment]
@B-Esmaili `/extensions/displays` returns an array of all available displays. `/extensions/displays/<id>/index.js` returns the bundled display itself

**Comment by B-Esmaili** [comment]
Ok, thanks for the clarification. But any idea what's the problem with my case?

**Comment by rijkvanzanten** [comment]
What does your display look like?

**Comment by B-Esmaili** [comment]
![Capture2](https://user-images.githubusercontent.com/9152515/119188928-9c950180-ba90-11eb-9961-a3e88e121b96.PNG)
This is the directory structure of my project. And following is the content of `meta.json` file :

`{"name":"mydisp","version":"1.0.0","icon":"person","types":["string"],"options":{}}`

**Comment by rijkvanzanten** [comment]
@B-Esmaili Make sure to take a look at the guide I linked earlier: https://docs.directus.io/guides/displays/ 🙂 There's a couple requirements that you're missing 👍🏻 

Also, it looks like the setup for this is from a v8 or earlier version of Directus. Are you following an outdated tutorial somewhere?

**Comment by B-Esmaili** [comment]
> @B-Esmaili Make sure to take a look at the guide I linked earlier: https://docs.directus.io/guides/displays/  There's a couple requirements that you're missing 👍🏻

Ok. Although I have read it once, I'll double-check the points.




> Also, it looks like the setup for this is from a v8 or earlier version of Directus. Are you following an outdated tutorial somewhere?

One last thing I tried is requesting both endpoints and the following is the result: 

![Capture](https://user-images.githubusercontent.com/9152515/119189883-de727780-ba91-11eb-8753-2c73bd4b4ae9.PNG)
and based on warning I received in `chrome dev-tools`.it's expecting the response to be a javascript file whereas its a JSON string right now.

**Comment by B-Esmaili** [comment]
Any improvements on this issue? It'll be great if you provide the community with some boilerplate to get started with plugin dev.

**Comment by rijkvanzanten** [comment]
This is the minimal boilerplate we have for displays at this point in time:

https://docs.directus.io/guides/displays/
