### ISSUE TITLE
Errors - Cannot query field "files" on type "Directus". Did you mean "items"?"

### ISSUE THREAD

**Issue by jlouis-onrr** [directus/directus#5767]
Installed via docker-compose:  https://docs.directus.io/guides/installation/docker/

1) The issue and what you expected to happen
    Expect to query files from /graphql/system endpoint

2) Exact steps to reproduce this issue
    Add folders and files to files directory, set permissions to be readable, get error

3) Your environment:
    MacOS Big Sur 11.3.1
    Version 90.0.4430.212 (Official Build) (x86_64)
    Version:  Directus 9.0.0-rc.24
    version: '3.2'
services:
  database:
    container_name: database
    image: postgres:12
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:v9.0.0-rc.24
    ports:
      - 8055:8055
    volumes:
      # By default, Directus images writes uploads to /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume When using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'

networks:
  directus:

**Comment by rijkvanzanten** [comment]
Update your version of Directus. `9.0.0-rc.24` is very outdated and doesn't contain the system resolvers yet 👍🏻
