### ISSUE TITLE
<Select> component hit area missing

### ISSUE THREAD

**Issue by tarwin** [directus/directus#5774]
The Vue select component looks to have a small issue with the hit area.

There is a single pixel (I think only 1xp) between items in the select dropdown, and when clicked it closes the Select.

This is only a small problem but could cause frustration when a user thinks they have selected an item and then save, not realising it hasn't been changed.

![directus-v-select-single](https://user-images.githubusercontent.com/646149/118902867-65c1be80-b8cb-11eb-8a0c-563ecbfd48ed.gif)

**Comment by Victor-Nikliaiev** [comment]
https://github.com/directus/directus/blob/477c36d86771190f8c314b0fa641a86f3ee1a3fb/app/src/components/v-select/v-select.vue#L311


Did you try play with line-height?

**Comment by rijkvanzanten** [comment]
Ideally, the top-level v-menu is able to listen to the actual click event that's triggered by those menu items. Right now, it's based on any click interaction within that dropdown context, as it's not aware of the contents of the "dropdown sheet".

That being said, I think a proper best-next-thing approach would be to explicitly ignore the "dropdown sheet" background thing on the click-inside checker, so it only triggers on interactions on the actual content of the sheet, and not the sheet itself 👍🏻

**Comment by tarwin** [comment]
@Victor-Nikliaiev I've only been using it with `npx` so far, so haven't got into deving on it. I'm guessing `line-height` would fix it as long as the line height matches the actual button size.

@rijkvanzanten the simple approach to ignore clicks on the background element would fix the problem of confusion. You would still have a very small problem of a click that is ignored but that's way better than the confusion.
