### ISSUE TITLE
GraphQL Slug Validation error

### ISSUE THREAD

**Issue by TheAzack9** [directus/directus#5786]
Hello again,

Upgraded to Directus version 9.0.0-rc69 (From rc64) and suddenly i get this graphql Error on all collections containing a slug.
`Fields \"slug\" conflict because they return conflicting types \"String\" and \"String!\". Use different aliases on the fields to fetch both if this was intentional.`

It works perfectly fine when querying the collection itself, the problem only occurs when you try to query through a M2A relation. (Or so it seems to me)

How to reproduce:

1. Create a new collection containing at least a slug
2. Create another collection with M2A to previous collection
3. Insert some data
4. Query the data through GraphQL :)

Environment:
Directus 9.0.0-rc69
MySql 8
Docker (through Azure)
Chrome 90.0.4430.212

**Comment by TheAzack9** [comment]
Nvm me, seems i got my databases mixed up in the update so i never ran the migrations... 🤦 :)

**Comment by TheAzack9** [comment]
Aha, i think i might understand the cause. Revised step plan to reproduce:

1. Create a collection with a field named slug and make sure that it is set to not null
2. Create another collection with a field named slug and make sure that it is set to nullable
3. Create a third collection with a M2A relation that relates to both the above collections
4. Add some data
5. Query the third collection through GraphQL

Seems the issue relates to types on M2A fields with the same name, not sure why tho...

**Comment by rijkvanzanten** [comment]
Apparently that's a GraphQL thing!

When I query that in my GraphQL debugger (Altair in this case), I'm getting the following:

<img width="723" alt="CleanShot 2021-05-24 at 14 22 26@2x" src="https://user-images.githubusercontent.com/9141017/119390749-7b543100-bc9b-11eb-8f4b-d844c080d5be.png">

Adding an alias to the field(s) makes it work as expected:

```graphql
query {
  pages {
    sections {
      item {
        ... on blog {
          blogSlug: slug
        }
        
        ... on articles {
          articleSlug: slug
        }
      }
    }
  }
}
```
