### ISSUE TITLE
Delete Collection fails

### ISSUE THREAD

**Issue by ernst86913** [directus/directus#5793]
Delete collections fails with latest commits / updates

![image](https://user-images.githubusercontent.com/47870436/119051247-3aba9600-b9c3-11eb-9daa-c92d097be7cf.png)

Potential issue might be that the data migration also fails... telling me that table "test" is used multiple times... but not sure whether this is related to above error...

![image](https://user-images.githubusercontent.com/47870436/119051402-676ead80-b9c3-11eb-8022-469dde8f66a7.png)

**Comment by rijkvanzanten** [comment]
Would you be able to share a DB dump of the offending tables / rows in directus_collections? Could it be you have a recursive relationship from test->test?

**Comment by ernst86913** [comment]
I had a recursive tree there... which I deleted now... but still same issue... 

In addition I have a M2O relationship from "asdfasf" table... I assume this is causing the issue... 

![image](https://user-images.githubusercontent.com/47870436/119059512-bd961d80-b9d0-11eb-9bcc-c4b662ba8bf8.png)


Here is the plain text dump:
[dump.txt](https://github.com/directus/directus/files/6519117/dump.txt)
