### ISSUE TITLE
field duplicated in the app ui based on the number of sql indexes that reference it

### ISSUE THREAD

**Issue by wc-matteo** [directus/directus#5815]
- create a collection
- create an index `CREATE INDEX bar ON foo (id)`

(doesn't matter what field or what type of index)

### result

![Screenshot 2021-05-21 215049](https://user-images.githubusercontent.com/10562635/119192020-be39bd00-ba7f-11eb-9965-999b2f5e5623.png)

### elsewhere

![Screenshot 2021-05-21 215131](https://user-images.githubusercontent.com/10562635/119192152-f0e3b580-ba7f-11eb-9d72-43e9a4fe1468.png)

![Screenshot 2021-05-21 215228](https://user-images.githubusercontent.com/10562635/119192179-fc36e100-ba7f-11eb-851f-e808eb292595.png)

### `directus_fields` and the api don't have the duplicate field

![Screenshot 2021-05-21 215456](https://user-images.githubusercontent.com/10562635/119192189-00fb9500-ba80-11eb-9b33-4cda3542f09e.png)

![image](https://user-images.githubusercontent.com/10562635/119192500-8e3ee980-ba80-11eb-9bed-59f9d8a7920c.png)

### notes
the more indexes reference a field, the more copies it has. Copies start from the second reference onwards, so 1 reference is allowed. It also happens with composite indexes

---

#### Software
- Directus v9.0.0-rc.69
- Microsoft SQL Server 2016
- Docker
- Chrome

**Comment by wc-matteo** [comment]
The issue is in [here](https://github.com/knex/knex-schema-inspector/blob/01f7c359f089938711397a7232638538c0340c98/lib/dialects/mssql.ts#L194).
The query doesn't handle the fact that the joined tables may contain multiple rows per column (like `[sys].[indexes]`)

**Comment by rijkvanzanten** [comment]
The main reason we're joining in the indexes there is to extract the primary key index. We should probably do de-duplication in JS after the results are fetched, as we can't just rely on fetching the first index 🤔

**Comment by wc-matteo** [comment]
I think it could be done in sql.

replacing this:
```sql
LEFT JOIN [sys].[index_columns] [ic] ON [ic].[object_id] = [c].[object_id] AND [ic].[column_id] = [c].[column_id]
```

and this:

```sql
LEFT JOIN [sys].[indexes] AS [i] ON [i].[object_id] = [c].[object_id] AND [i].[index_id] = [ic].[index_id]
```

with this:

```sql
LEFT JOIN (
	SELECT [ic].[object_id],
		[ic].[column_id],
		[i].[is_unique],
		[i].[is_primary_key],
		ROW_NUMBER() OVER(PARTITION BY [ic].[object_id], [ic].[column_id] ORDER BY [i].[is_primary_key] DESC, [i].[is_unique] DESC) AS index_priority
	FROM [sys].[index_columns] [ic]
	JOIN [sys].[indexes] AS [i] ON [i].[object_id] = [ic].[object_id] AND [i].[index_id] = [ic].[index_id]
) AS [i] ON [i].[object_id] = [c].[object_id] AND [i].[column_id] = [c].[column_id]
```

and adding to the where clause:

```sql
([i].index_priority = 1 OR [i].index_priority IS NULL)
```
