### ISSUE TITLE
Missing Required option in fields

### ISSUE THREAD

**Issue by aliemba** [directus/directus#5836]
I am missing the "required" option in the fields config.

![image](https://user-images.githubusercontent.com/44196248/119269497-3c20d400-bbf8-11eb-8a4d-e8f5e7d5668a.png)

Fields that are set to required does not show either. And the option is not visible when creating new fields

---

### Project details
Directus Version: 9.0.0-rc.69
Environment: production
OS: Linux 5.4.78-2-pve
Node: 12.18.2

**Comment by rijkvanzanten** [comment]
Required was renamed to Allow Null more closely match how it actually functions in the database. You can find it under schema 👍🏻

**Comment by benhaynes** [comment]
Also, we'll be splitting the required logic out of `Allow NULL`, and putting that under a dedicated field `Required` toggle. This will be happening when we add Conditional Fields, or the new Field Setup Flow (whichever comes first). 👍

**Comment by tylerforesthauser** [comment]
> This will be happening when we add Conditional Fields, or the new Field Setup Flow (whichever comes first).

Speaking of which, is this planned before v9 release or is it lower priority than that?

**Comment by benhaynes** [comment]
> Speaking of which, is this planned before v9 release or is it lower priority than that?

The new field flow will be in 9.0.0 (pre-release), conditional fields is in the process of being sponsored, and will likely come just after release.

**Comment by tylerforesthauser** [comment]
So with the new field flow, am I right that this would enable the possibility of something like a dynamic slug field that could be populated based on the contents of another field? Or is that a different thing altogether?

**Comment by benhaynes** [comment]
> So with the new field flow, am I right that this would enable the possibility of something like a dynamic slug field that could be populated based on the contents of another field? Or is that a different thing altogether?

Altogether different. The new field flow is just a more intuitive/simplified UI option for creating fields in the App.
