### ISSUE TITLE
[Docker: v9.0.0-rc.69] Admin not allowed to log in on fresh docker install behind proxy

### ISSUE THREAD

**Issue by alexanderwolz** [directus/directus#5881]
I've set up a NGINX Reverse Proxy for hosting the dockerized directus v9 on https://www.domain.tld/directus.
Using "_PUBLIC_URL: /directus_", the login page and assets are loaded correctly. (The same behaviour if PUBLIC_URL is set to https://www.domain.tld/directus or  https://www.domain.tld/directus/)

But after successful login, the admin user is declined access to the admin portal "No App Access. This user is not allowed to use the admin app"

The log throws "refresh_token is required in either the JSON payload or Cookie" prior to the login. 

According to the logs, signin seems to be successful. Also a curl request to POST https://www.domain.tld/directus/auth/login returns 200

directus logs:
====
---20:25:31 ✨ Initializing bootstrap...
20:25:31 ✨ Installing Directus system tables...
20:25:32 ✨ Running migrations...
✨ Applying Remove Collection Foreign Keys...
✨ Applying Remove System Relations...
✨ Applying Remove System Collections...
✨ Applying Remove System Fields...
✨ Applying Add Cascade System Relations...
✨ Applying Change Webhook URL Type...
✨ Applying Add Relations Sort Field...
✨ Applying Remove Locked Fields...
✨ Applying Webhooks Collections Text...
✨ Applying Add Refresh Interval...
✨ Applying Make Filesize Nullable...
✨ Applying Add Collections Accountability...
✨ Applying Remove Files Interface...
✨ Applying Rename Interfaces...
20:25:32 ✨ Setting up first admin role...
20:25:32 ✨ Adding first admin user...
20:25:32 ✨ Done
20:25:34 ✨ Server started at port 8055
20:29:54 ✨ request completed GET 302 / 13ms
20:29:54 ✨ request completed GET 200 /admin 3ms
20:29:54 ✨ request completed GET 200 /admin/css/chunk-vendors.2ac9cbb8.css 14ms
20:29:54 ✨ request completed GET 200 /admin/css/app.bd9e8a4b.css 30ms
20:29:54 ✨ request completed GET 200 /admin/js/app.e81a952f.js 48ms
20:29:54 ✨ request completed GET 200 /admin/js/chunk-vendors.2bd9296a.js 49ms
20:29:55 ✨ request completed GET 200 /admin/img/icons/android-chrome-512x512.png 11ms
20:29:55 ✨ request completed GET 200 /admin/img/icons/android-chrome-192x192.png 14ms
20:29:55 ✨ request completed GET 200 /extensions/displays/ 132ms
20:29:55 ✨ request completed GET 200 /extensions/modules/ 144ms
20:29:55 ✨ request completed GET 200 /extensions/layouts/ 146ms
20:29:55 ✨ request completed GET 200 /extensions/interfaces/ 153ms
20:29:55 🐛 "refresh_token" is required in either the JSON payload or Cookie
20:29:55 ✨ request completed POST 400 /auth/refresh 23ms
20:29:55 ✨ request completed GET 200 /admin/fonts/Inter-Medium.c709803c.woff2 27ms
20:29:55 ✨ request completed GET 200 /server/info 28ms
20:29:55 ✨ request completed GET 200 /admin/img/icons/safari-pinned-tab.svg 2ms
20:29:56 ✨ request completed GET 200 /admin/img/logo-light.3b43f888.svg 45ms
20:29:56 ✨ request completed GET 200 /admin/fonts/Inter-Black.b5dc0c80.woff2 8ms
20:29:56 ✨ request completed GET 200 /admin/fonts/Inter-SemiBold.46633223.woff2 9ms
20:29:56 ✨ request completed GET 200 /admin/fonts/Inter-Bold.0564381b.woff2 13ms
20:29:56 ✨ request completed GET 200 /admin/fonts/material-icons-outline.f17eb849.woff2 11ms
20:29:56 ✨ request completed GET 200 /auth/oauth/ 39ms
20:32:47 ✨ request completed POST 200 /auth/login 249ms
20:32:47 ✨ request completed GET 200 /users/me 36ms
20:32:47 ✨ request completed GET 200 /collections 195ms
20:32:47 ✨ request completed GET 200 /presets 194ms
20:32:47 ✨ request completed GET 200 /fields 286ms
20:32:47 ✨ request completed GET 200 /presets 270ms
20:32:47 ✨ request completed GET 200 /presets 269ms
20:32:47 ✨ request completed GET 200 /settings 270ms
20:32:47 ✨ request completed GET 200 /relations 281ms
20:32:47 ✨ request completed GET 200 /permissions 280ms
20:32:47 ✨ request completed GET 200 /server/info 280ms
20:32:48 ✨ request completed GET 200 /users/me 24ms
20:32:48 ✨ request completed GET 200 /admin/css/private-view.ef7a6025.css 3ms
20:32:48 ✨ request completed GET 200 /admin/js/private-view.0535847b.js 4ms
20:32:48 ✨ request completed PATCH 200 /users/me/track/page 25ms

Docker version 20.10.6, build 370c289

Docker Compose:
===
  directus:
    container_name: directus
    image: directus/directus
    restart: unless-stopped
    environment:
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: d1r3ctu5
      LOG_LEVEL: debug
      LOG_STYLE: pretty
      PUBLIC_URL: /directus
      KEY: myKey
      SECRET: mySecret
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - uploads:/directus/uploads
      - database:/directus/database
      - extensions:/directus/extensions

NGINX conf:
===
  location ~* ^/directus(/.*)$ {
    set $upstream       directus:8055;
    proxy_pass          http://$upstream$1;
  }
  
proxy.conf
====
proxy_redirect          off;

proxy_set_header        X-Real-IP           $remote_addr;
proxy_set_header        Host                $host;
proxy_set_header        X-Forwarded-For     $proxy_add_x_forwarded_for;
proxy_set_header        X-Forwarded-Proto   $scheme;
proxy_set_header        X-Forwarded-Host    $host;
proxy_set_header        X-Forwarded-Port    $server_port;

client_max_body_size    2048M;
client_body_buffer_size 128k;
proxy_connect_timeout   90;
proxy_send_timeout      90;
proxy_read_timeout      90;
proxy_buffers           32 4k;

**Comment by rijkvanzanten** [comment]
Heya! Did you confirm if it works as expected before adding the Nginx proxy? 

The Directus logs you shared above are what you'd see on a successful login 🤔

**Comment by alexanderwolz** [comment]
Hi,

it indeed works if I use a subdomain (e.g. https://directus.domain.tld) but I need to run it on a path location. 

To be more precise: The login and the API are **working**. I could even use the credentials to access the /users /roles etc. via REST. Also token refresh works - Only the admin app does not let me in. (I also tear down the containers using the -v flag to have a clean setup)

---
<img width="549" alt="Bildschirmfoto 2021-05-26 um 23 37 27" src="https://user-images.githubusercontent.com/84812593/119734466-58807300-be7b-11eb-8669-3f614607da9c.png">

**Comment by Oreilles** [comment]
Shouldn't the `PUBLIC_URL` be `https://www.domain.tld/directus` rather than `/directus` ?

**Comment by alexanderwolz** [comment]
I tried different variations for PUBLIC_URL:

- /directus
- /directus/
- https://www.domain.tld/directus
- https://www.domain.tld/directus.

All with the same results.

**Comment by Oreilles** [comment]
I'm not well versed enough with nginx to know what you're doing wrong exactly, but here's a minimal `nginx.conf` I used that just works (tested just now with `nginx:latest` and `directus:latest`

`PUBLIC_URL` is set to: `http://localhost/directus/` (as @rijkvanzanten told me on Discord when I had a similar issue, it's better to put to whole URL as it might be used to generate links in emails and such)


```nginx
events {
}
http {
  server {
    listen 80;

    location /directus/ {
      proxy_pass http://directus:80/;
    }
  }
}
```

**Comment by alexanderwolz** [comment]
Shouldn't the port be 8055? (At least that port is defined in the EXPOSE tag of the Dockerfile.)

I changed my config to `PUBLIC_URL: https://www.domain.tld/directus/` and switched to your NGINX example (except that I use directus:8055) - what shall I say.. It works now :)

I used to have the same config as your example a few days ago with a relative `PUBLIC_URL` and the directus login window and content showed but no app access. I then switched to the RegEx-Definition that in fact had the same outcome.. So I guess the trailing slash in the end of the URL made the difference?

Thank you for your support!!

**Comment by Oreilles** [comment]
> So I guess the trailing slash in the end of the URL made the difference

It absolutely does, `nginx` is very picky on that.

**Comment by alexanderwolz** [comment]
So strange fact:

If I switch to 

  location /directus/ {
    set                   $upstream directus:8055;
    proxy_pass            http://$upstream/;
   }
   
  Then it does not work anymore and the browser answers with "too many redirects". I use that config in order to not get errors if nginx is started earlier than directus...

 I guess this seems to be a NGINX issue with my config now and not directus-related - do you have any experience on that?

**Comment by Oreilles** [comment]
```nginx
location /directus/ {
  set $upstream directus:8055;
  proxy_pass http://$upstream/;
}
```
As I said I don't know anything about `nginx` but this looks very much like a infinite recursive loop, and the `too many redirects` also suggests so.

**Comment by alexanderwolz** [comment]
I fixed it. For all who run into similar issues: 

Do not use `set $upstream`

```nginx
location /directus/ {
  set $upstream directus:8055;
  proxy_pass http://$upstream/;
}
```

Instead use correct upstream directive in the http section.
```nginx
upstream directus {
    server directus:8055;
}

server {
  listen                  443 ssl http2;
  server_name             www.domain.tld;

  location /directus/ {
    proxy_pass            http://directus/;
  }
}
```

**Comment by alexanderwolz** [comment]
Fixed it. For all wo have similar issues:

If you want to use directus v9 with a variable in proxy_pass, you need to specify arguments, too.
(Using variables in proxy_pass will start NGINX even if the remote server is offline)

This worked for me:

```Nginx
  location ~* ^/directus(/.*)$ {
    set $upstream       directus:8055;
    proxy_pass          http://$upstream$1$is_args$args;
  }
```
