### ISSUE TITLE
Can't specify custom parameters for grant/sso

### ISSUE THREAD

**Issue by MiniDigger** [directus/directus#5891]
For my azure ad b2c oauth flow its required to pass a policy param `p`, without that no login is possible.

Grant allows passing custom parameters: https://www.npmjs.com/package/grant#connect-custom-parameters
these are json. if you configure grant via env vars, its not possible to specify json: it gets escaped somewhere.

Maybe a syntax like `OAUTH_MICROSOFT_CUSTOM_PARAMS_name = "value"` which then turns into `config['microsoft'].custom_params = { name: 'value'}` would be good here?
Not sure if casing would be important.

additionally, sadly directus swallows grant errors, which makes configuring sso more difficult than it needs to be, maybe check if(hookpayload['error']) and log the error with some error level?
https://github.com/directus/directus/blob/main/api/src/controllers/auth.ts#L287

**Comment by rijkvanzanten** [comment]
Added in https://github.com/directus/directus/pull/6155
