### ISSUE TITLE
Focusing items with TAB

### ISSUE THREAD

**Issue by Fusseldieb** [directus/directus#5892]
I would like to mention a thing that was working on v8 but isn't on v9.

- Focusing items with TAB (works partially)
- While a dropdown is focused, pressing the initial letter and it jumping to the entry.

Just mentioning that here, since I didn't find any open issue that discusses this :)

This would massively improve the usability and usage speed of the App imo

**Comment by rijkvanzanten** [comment]
This is part of a bigger ongoing approach around accessibility and keyboard usability, see https://github.com/directus/directus/discussions/4825

**Comment by Fusseldieb** [comment]
Ahh, didn't see that, thanks!
