### ISSUE TITLE
Creation of collection through API with a field array including a repeater doesn't add the repeater correctly

### ISSUE THREAD

**Issue by moekify** [directus/directus#5893]
1) The issue and what you expected to happen
    Firstly, I exported all fields of a collection including a repeater field via the fields API (export=json). Then I tried to create a new collection with these fields via the API. This works well except for the repeater field that shows an error on the interface type.
    The expectation would be for this to work as expected and creating a repeater field.
    
2) Exact steps to reproduce this issue
    - Export fields of a collection including a repeater interface
    - Create a new collection via the api with those fields
    - Repeater is broken interface

3) Your environment:
    What version of Directus you are using.   v9-rc69
    Which DBMS are you using (MySQL 8, Postgres 12, ...). POSTGRES
    Which deployment are you using (npx, Docker, ...). NPX
    What browser are you using (Chrome 87, Safari 14, ...). doesn't apply

4) Any other relevant information we might need to reproduce this issue
    
![image](https://user-images.githubusercontent.com/19408385/119660958-1716a600-be30-11eb-889e-1f0bd9da9d3c.png)

FWIW, it is totally possible to reset the interface and then re-select repeater which works and even keeps the underlying repeater fields. Just think this should work outside the box :)

**Comment by rijkvanzanten** [comment]
Was the export made in the same version of Directus? The only thing I can think of that might cause this is the rename of interfaces that was introduced recently. Repeater was renamed to `list` 🤔

**Comment by moekify** [comment]
@rijkvanzanten Indeed the versions are different :( (rc.61 was the one where the export originated) 

I didn't consider this. I'll update to rc.69 and very likely the problem will be resolved :) 

Closing this for now, I'll reopen if the problem persists.

**Comment by moekify** [comment]
@rijkvanzanten Bit tedious for me to reproduce now, but when I upgraded the version from rc.61 to rc.69 it broke the repeater in a similar fashion. I also had to reset the interface and select repeater again for it to work. 

The error message here was then "No interface 'list' could be found" 

If you'd like I can try to do a reproduction of that locally, but don't have the time right now.

**Comment by rijkvanzanten** [comment]
> but when I upgraded the version from rc.61 to rc.69 it broke the repeater in a similar fashion

Did you run the database migrations?

**Comment by moekify** [comment]
Should have specified, I'm running this as a docker container and from what I can see in the logs migrations are automatically run when the container is started.

**Comment by rijkvanzanten** [comment]
Hmm odd. Could you double check the DB under directus_fields to see what the interface name is now?
