### ISSUE TITLE
Browser hangs when choosing date

### ISSUE THREAD

**Issue by Fusseldieb** [directus/directus#5903]
I just discovered a bug when using the date chooser.

When I try to select any of the red marked boxed below, the whole tab hangs indefinitively.

<img src="https://user-images.githubusercontent.com/4715129/119731937-ee050e00-be4d-11eb-89b1-525114334d2a.png" height="200px">

<img src="https://user-images.githubusercontent.com/4715129/119732169-3cb2a800-be4e-11eb-9fbc-fc97806e4b72.png" height="100px">

Using v9.0.0-rc.69 and Chrome 90.0.

EDIT: Just tried in Firefox and there it doesn't hang... Strange.

**Comment by rijkvanzanten** [comment]
Hey! That sounds like https://github.com/directus/directus/issues/5826 (cc @hakki264ulku)

@Fusseldieb Does it happen every time? Is there a specific sequence of steps when it starts happening??

> EDIT: Just tried in Firefox and there it doesn't hang... Strange.

_Please don't be a Chromium bug, please don't be a Chromium bug, please don't be a Chromium bug_

**Comment by rijkvanzanten** [comment]
Does it only happen for those two dropdowns? Does it work for mês?

**Comment by Fusseldieb** [comment]
> Does it only happen for those two dropdowns? Does it work for mês?

Yes, it works for Mês

**Comment by rijkvanzanten** [comment]
Does it happen every time? Or sporadic?

**Comment by Fusseldieb** [comment]
Every time, I tested it multiple times and it crashed every time.

Em qua., 26 de mai. de 2021 18:47, Rijk van Zanten ***@***.***>
escreveu:

**Comment by Fusseldieb** [comment]
> Hey! That sounds like #5826 (cc @hakki264ulku)

It's not the same, it does open without any problem, but upon selecting the whole browser tab becomes unresponsive and doesn't do anything. After a while a message pops up saying that the tab stopped responding and if I want to "Wait" or "Close" it.

**Comment by rijkvanzanten** [comment]
> EDIT: Just tried it on my home PC and there it doesn't crash... Strange. Same Chrome version v90.0.

.. uh oh :| 

 Any obvious differences between your home PC and work PC?

**Comment by Fusseldieb** [comment]
> > EDIT: Just tried it on my home PC and there it doesn't crash... Strange. Same Chrome version v90.0.
> 
> .. uh oh :|
> 
> Any obvious differences between your home PC and work PC?

Not that I'm aware. Same OS, both are Intel... I really don't know.

**Comment by rijkvanzanten** [comment]
Thanks!

**Comment by Fusseldieb** [comment]
Restarted the PC and it still crashes.

**Comment by rijkvanzanten** [comment]
I believe this was fixed in https://github.com/directus/directus/pull/5339 🙂  (I can't reproduce it anymore in Chromium browsers)
