### ISSUE TITLE
Change own password should be the default in the reccomended user role.

### ISSUE THREAD

**Issue by cupcakearmy** [directus/directus#5927]
Related to: https://github.com/directus/directus/discussions/5911

The _recommended defaults_ presets are an aweseome time saver! One thing I think should be added though is letting the user change his/her password, email and name at least. What do you think? 

If this is by design feel free to just close the issue :)

**Comment by cupcakearmy** [comment]
Sure thing, will do

**Comment by cupcakearmy** [comment]
@rijkvanzanten I've done the changes, would like to test them first though

I've followed the official guide https://docs.directus.io/contributing/running-locally/ but could not get the admin interface running under localhost.

Tried executing steps 1-7, but i get a server at 8080 that wants to proxy 8085, which is not running.
also tried running `npm run cli bootstrap` and `npm run cli start` but no luck.
What am I missing?

**Comment by rijkvanzanten** [comment]
Try building the platform first (`npm run build`) from root, and then run `npm run dev` to start it up

**Comment by cupcakearmy** [comment]
Well now it worked, feel dumb now 😆

**Comment by cupcakearmy** [comment]
PR is done  #5943

**Comment by rijkvanzanten** [comment]
Closed in #5943 ✨
