### ISSUE TITLE
Multiple Files UI is saving SORT correctly, but displaying out of order sometimes

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#596]
Everything seems to be working properly most of the time. I can add new items, reorder, and save these images in the multiple_files UI and things seem to work as expected.

Sometimes the UI doesn't display the items in the correct order though. The database is saving them correctly, but then when reloading the page you get items in a different order. I'm not sure if it's ordering the sort column as a string (so that "11" comes after "1") or if it's simply sorting on the wrong field.

Also, if I delete all sort values in the DB and save a sorted list, sometimes the first item is saved with a NULL instead of a "0". There seems to be some issues with the saving and displaying of this UI – maybe of all relational sorting?

**Comment by WellingGuzman** [comment]
It was actually that, the number being returned as a string.
I did what you wrote and when I convert the sort column to string the sorting stay the same.

If for some reason the random sorted happens again let me know how it was trigger, but we should be good to go with this one.

Solving the string as date and we all done with sorting by now.

**Comment by benhaynes** [comment]
The first part of this (displaying in the correct order) seems to be solved, but there is still a small issue saving. If you have 5 items (saved in the junction table) with sort == NULL... if you drag and drop them and save you get:

**NULL, 1, 2, 3, 4**
*It should save:*
**0, 1, 2, 3, 4**

I think this orders OK still, but we should correct this eventually. I'm changing this to minor for now.

**Comment by WellingGuzman** [comment]
I fixed the issue, in [PR#600](https://github.com/RNGR/directus6/issues/600)

**Comment by benhaynes** [comment]
Great!

**Comment by benhaynes** [comment]
I'm seeing this issue again... can we check to see if the previous fix is still working?

**Comment by benhaynes** [comment]
OK, fixed!
