### ISSUE TITLE
We're sorry but Directus doesn't work without JavaScript enabled. Please enable it to continue

### ISSUE THREAD

**Issue by botzill** [directus/directus#5992]
I setup directus using nginx and I have some errors trying to access the default `/admin/collections/` page, I get:

`We're sorry but Directus doesn't work without JavaScript enabled. Please enable it to continue.`

<img width="703" alt="Screen Shot 2021-06-02 at 13 30 32" src="https://user-images.githubusercontent.com/4686040/120465430-a4b14300-c3a6-11eb-8d99-eee2a31eb5e1.png">

I do access this using a google chrome browser. It was working before, I noticed after some upgrade it stopped working . 

Now I have the latest version: rc.70.

Thx

**Comment by Fusseldieb** [comment]
I couldn't reproduce this issue.

Both rc.69 and rc.70 work just fine under `/admin/collections`, **however**, please note that _Javascript is disabled_ in the Preview window, which means that you get this message if you look in the Preview window, but the page itself will work fine.

![image](https://user-images.githubusercontent.com/4715129/120475090-53418d80-c37f-11eb-8670-c6af004d61f9.png)

**Comment by botzill** [comment]
Well, the prob start that `admin/collections` is blank for some reason and when I inspect the page I see that.

**Comment by Fusseldieb** [comment]
Have you tried bootstrapping the database after upgrading, I have to do that sometimes after an update.

`npx directus bootstrap`

**Comment by botzill** [comment]
What does that? Note that all the other parts work OK, `admin/users/` or other parts, except that endpoint only.

**Comment by Fusseldieb** [comment]
From the help command:

`bootstrap           Initialize or update the database`

You can try it and see if it solves the issue. If not, we need to gather more info...

**Comment by rijkvanzanten** [comment]
99% sure this is a server proxy configuration issue. I'm assuming the page appears blank in the browser because the browser isn't able to retrieve the static assets (eg css / js) required to run the app

**Comment by botzill** [comment]
Strange, having the same version deployed on kubernetes as 2 separate databases and one is working OK as is, the other gives this issue.
