### ISSUE TITLE
M2O fails when creating table representing a directed edge between users.

### ISSUE THREAD

**Issue by Haffi112** [directus/directus#6009]
1) The issue and what you expected to happen
    I've created a collection called "directed_edge". I'm trying to create a "source" user and "sink" user both as M2O relations. When I try to add a M2O field in this collection then I get the error "Invalid payload" ([INVALID_PAYLOAD] "type" is required). I expected a field to be created but for some reason, it won't happen.

2) Exact steps to reproduce this issue
    See above. The user is from the directus_user table.

3) Your environment:
    I'm using Directus as a freshly installed droplet on Digital Ocean (edit: Directus 9.0.0-rc.70).

**Comment by rijkvanzanten** [comment]
What version of Directus are you on?

**Comment by Haffi112** [comment]
Directus 9.0.0-rc.70

**Comment by Haffi112** [comment]
The error occurs if I choose to add a corresponding field in the directus_user table when creating the M2O field for a source/target user in the "directed edge" collection. If I do not choose to add that field to the directus_user then I can make it work.
