### ISSUE TITLE
Translation interface are broken after migrations in rc70

### ISSUE THREAD

**Issue by dsivokhin** [directus/directus#6010]
UPD: After update to rc70, migratios created foreign keys, then translation interface not work correctly.

![изображение](https://user-images.githubusercontent.com/4669992/120524816-240f3880-c3e0-11eb-8b59-304e133a5013.png)

if remove foreign keys in translation table, or rename, translation interface works again.
Possibly, a single case, if the charset/collation by default and table, are not equal when creating foreign keys. 

Directus 9.0.0-rc70,
MySQL 5.7.33

**Comment by rijkvanzanten** [comment]
I'm not sure what you mean by 

> rc70 broke my translation field, because name for relations field in interface set manualy

How did r70 change things? The migrations for rc70 didn't update the values within directus_relations, so I'm not sure what you mean 🤔

**Comment by dsivokhin** [comment]
@rijkvanzanten 
https://github.com/directus/directus/blob/main/api/src/database/migrations/20210510A-restructure-relations.ts

sorry not my field, translate interface, if table `products` and related field != products_id

**Comment by rijkvanzanten** [comment]
How can I reproduce this?

**Comment by dsivokhin** [comment]
Need set custom related field name, not "Auto fill"

![изображение](https://user-images.githubusercontent.com/4669992/120531471-57a19100-c3e7-11eb-8273-3f2fda0e94e0.png)

**Comment by dsivokhin** [comment]
@rijkvanzanten 
Sorry, I don’t know how exactly, but it’s not field name issue, it’s somehow related to the foreign keys, that was created by the migrations, if remove foreign keys in translation table, or rename, translation interface works again.
