### ISSUE TITLE
Extend right click target beyond list in nav

### ISSUE THREAD

**Issue by supermx1** [directus/directus#6016]
Environment:
    Directus 9.0.0 RC71
    DBMS MySQL
    npx
    Chrome 
    2020 Macbook Pro Intel
    
    
    
The right-click to show hidden collection is not working anymore. Before RC70 and 71. If you have a hidden collection you can show it in the collections module by right-clicking and selecting the hidden collection.

**Comment by supermx1** [comment]
https://user-images.githubusercontent.com/9326922/120564261-6a758f00-c402-11eb-83d2-4031abbf42ec.mp4

**Comment by rijkvanzanten** [comment]
@supermx1 The problem here is that the contextmenu listener is on the nav list, not the bounding parent container 🙂
