### ISSUE TITLE
MySql migrations - Couldn't add foreign key constraint

### ISSUE THREAD

**Issue by avatarbabe** [directus/directus#6028]
I just updated from RC69 to RC71, running the latest migrations, I get several errors like these:

> Couldn't add foreign key constraint for pages.image->directus_files
14:17:25 alter table `pages` add constraint `pages_image_foreign` foreign key (`image`) references `directus_files` (`id`) on delete SET NULL - ER_CANT_CREATE_TABLE: Can't create table `directus-69`.`pages` (errno: 150 "Foreign key constraint is incorrectly formed")

Seems like the issue is caused by different collations on the columns: 
pages.image (**uft8_general_ci**)
directus_files('id') (**latin1_swedish_ci**)

Why are the `directus_` tables using latin1_swedish_ci and the directus-generated collections using `utf8_general_ci`? Is it possible to change it?

---

### Project details
Directus Version: 9.0.0-rc.71
Environment: production
OS: Linux 5.4.0-1031-azure
Node: 14.15.1

**Comment by avatarbabe** [comment]
Ok I'm closing this, probably an error on my end when setting up the database. Had to manually change the collation of all the tables that were incorrect, but not it works as expected!

**Comment by rijkvanzanten** [comment]
@avatarbabe Directus doesn't explicitly set the collation, so it uses whatever is set as the default in the database, or what is configured on the connection 👍🏻
