### ISSUE TITLE
Error when configuring existing foreign_key

### ISSUE THREAD

**Issue by metalmarco** [directus/directus#6029]
Directus: **9.0.0-rc.71**
DB: **MySQL**

I have two tables related as following `dm_publications.property` -> `dm_properties.id` via an existing foreign key called `fk_dm_property_publications_dm_properties`

When I try to configure the table on Directus Admin, I receive the following error:
**ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'dm_property_publications_property_foreign'; check that column/key exists**

It's like Directus is trying to drop a foreign key that doesn't exists.

**Existing Foreign Key**
<img width="1005" alt="Schermata 2021-06-03 alle 15 07 27" src="https://user-images.githubusercontent.com/7231582/120649778-6c306880-c47d-11eb-9cae-368916184cdd.png">

**Trying to configure the table/field on Directus Admin**
<img width="850" alt="Schermata 2021-06-03 alle 15 02 44" src="https://user-images.githubusercontent.com/7231582/120649217-ce3c9e00-c47c-11eb-89fd-cdb3a8aad5ea.png">

**Error received**
<img width="640" alt="Schermata 2021-06-03 alle 14 59 11" src="https://user-images.githubusercontent.com/7231582/120648767-4c4c7500-c47c-11eb-883a-57ae8617ab01.png">

**Comment by supermx1** [comment]
I have this problem too

**Comment by rijkvanzanten** [comment]
> It's like Directus is trying to drop a foreign key that doesn't exists.

This is correct. You can't alter existing foreign keys in SQL, so Directus tries dropping it and then recreating it. The problem here is that Knex defaults to a specific naming system for foreign keys, which fails (as the key has a non-knex generated name). We can resolve this by first looking up the exact name of the foreign key and then drop it by key name, instead of relying on knex to figure that out

**Comment by supermx1** [comment]
So it has a manual fix?

**Comment by rijkvanzanten** [comment]
Nope! I meant that as: we (developers) can update Directus so it doesn't crash on this use case "by first looking up the exact name of the foreign key and then drop it by key name" 🙂

**Comment by supermx1** [comment]
https://user-images.githubusercontent.com/9326922/120703841-bb8e8d00-c4ad-11eb-9955-7906b99690dd.mp4

**Comment by metalmarco** [comment]
> > It's like Directus is trying to drop a foreign key that doesn't exists.
> 
> 
> 
> This is correct. You can't alter existing foreign keys in SQL, so Directus tries dropping it and then recreating it. The problem here is that Knex defaults to a specific naming system for foreign keys, which fails (as the key has a non-knex generated name). We can resolve this by first looking up the exact name of the foreign key and then drop it by key name, instead of relying on knex to figure that out

Thanks @rijkvanzanten that should be the solution. Other than that, incredible work on this foreign key feature, I bet it wasn't easy! For us it's extremely helpful and needed.

**Comment by rijkvanzanten** [comment]
Thank you! It definitely was not an easy one to get to work across the different vendors. I'm really excited to have it out in the world (even though there's a couple of these edge cases here and there 😁 )

**Comment by supermx1** [comment]
Sorry when will rc 72 be released? So we can update our builds? or is it better we downgrade for now?

**Comment by rijkvanzanten** [comment]
Within 30 minutes 👍🏻 

The patch update for `vue` apparently had an unintended breaking change, so I'm just making sure that the app still works now and it'll go out

**Comment by supermx1** [comment]
Still having that issue
![Screen Shot 2021-06-04 at 1 48 48 AM](https://user-images.githubusercontent.com/9326922/120729428-05d83400-c4d7-11eb-904b-d4d120314f42.jpg)

If i make any changes and click the check mark again. I get this immediately after
![Screen Shot 2021-06-04 at 1 49 35 AM](https://user-images.githubusercontent.com/9326922/120729468-21433f00-c4d7-11eb-81dc-b574905b70aa.jpg)

**Comment by rijkvanzanten** [comment]
AFAIK the OP was fixed. I believe the screenshot you sent just now is https://github.com/directus/directus/issues/5999 👍🏻
