### ISSUE TITLE
Error when viewing unconfigured collections in the data model

### ISSUE THREAD

**Issue by rwatts3** [directus/directus#6050]
After creating a brand new schema directly via the database to scaffold a project, I refreshed the UI under data model and the existing collections were missing. 

After further testing I realized the when unchecking "unconfigured collections" they re-appear. 
The following error displays in the console if "unconfigured collections" is checked. 

```
chunk-vendors.108c346c.js:181 TypeError: Cannot read property 'color' of null
    at fn (app.ce130664.js:1)
    at r (chunk-vendors.108c346c.js:181)
    at a.It [as _t] (chunk-vendors.108c346c.js:181)
    at fn (app.ce130664.js:1)
    at r (chunk-vendors.108c346c.js:181)
    at Zt.It [as _t] (chunk-vendors.108c346c.js:181)
    at app.ce130664.js:1
    at Zt.Pt [as _l] (chunk-vendors.108c346c.js:181)
    at Nr (app.ce130664.js:1)
    at Jt (chunk-vendors.108c346c.js:181)
```

I then manually added 1 of the unconfigured collections to the `directus_collections` table and obviously could now see the table in the list. 

My belief is that the new functionality for collection colors has introduced a bug that requires "color" to be set on a collection even if it has not been configured yet. 

The expected behavior is that all collections that have not been configured should not immediately inherit any constraints such as "color" if the record does not exist in "directus_collections" and it has not been configured yet. 

This feels more like a regression as I've done this exact process a few releases ago and did not see this bug. 

---
 
### Project details
Directus Version: 9.0.0-rc.72
Environment: production
OS: Linux 4.15.0-142-generic
Node: 14.17.0

**Comment by rijkvanzanten** [comment]
@Oreilles fyi 🙂
