### ISSUE TITLE
Auto Format Casing Adding Spaces and Capitalizing Incorrectly In Display

### ISSUE THREAD

**Issue by revaul** [directus/directus#6057]
1) The issue and what you expected to happen
    In display, if you select auto-format casing on a text field and then have a field with multiple Capital Letters in a row and followed by lower case letters in the same word, the system will add a space in display prior to the last capital letter and view it as a new word.

2) Exact steps to reproduce this issue
https://user-images.githubusercontent.com/20709208/120738818-79ba1280-c4be-11eb-870e-bcbac357c4d5.mp4

3) Your environment:
    What version of Directus you are using. **9.0.0-rc.72**
    Which DBMS are you using **Postgres**
    Which deployment are you using **Yarn**
    What browser are you using **Google Chrome 91.0.4472.77**

4) Any other relevant information we might need to reproduce this issue

    What third party services you rely on **DigitalOcean**

**Comment by rijkvanzanten** [comment]
That works as expected! The auto title formatter is meant to automatically transform `underscore_values`, `camelCase` or `hyphenated-values` into human-readable text. See https://www.npmjs.com/package/@directus/format-title for more information on how that works 🙂

**Comment by benhaynes** [comment]
Thanks @revaul — it's an interesting one, but keep in mind you can override these names with the "translations" option in the App.

@rijkvanzanten we could look into making that conversion a bit smarter so that it ignores multiple sequential uppercase letters maybe? Those examples wouldn't camelCase... just a thought.

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten we could look into making that conversion a bit smarter so that it ignores multiple sequential uppercase letters maybe? Those examples wouldn't camelCase... just a thought.

Nope! `APIRequest` should become `API Request`, so the multiple uppercase thing is working exactly as planned..
