### ISSUE TITLE
/lib64/libc.so.6: version 'GLIBC_2.25' not found on bootstrap in rc73

### ISSUE THREAD

**Issue by neo7-studio-web** [directus/directus#6071]
Just updated from rc71 to rc73

When running **npx directus bootstrap** : 
`/lib64/libc.so.6: version 'GLIBC_2.25' not found (required by [...] /node_modules/argon2/lib/binding/napi-v3/argon2.node)`

Centos 7.9

New requirement with new version of argon ?

**Comment by Enhed** [comment]
same error, cant run directus on docker FROM node:14.17

**Comment by Enhed** [comment]
`npm install argon2 --build-from-source`
fix that error

**Comment by dsivokhin** [comment]
Ubuntu 16.04, node 14.17, npm 7.16, rc 73

Same error
```
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /srv/www/directus9.dev/node_modules/argon2/lib/binding/napi-v3/argon2.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1127:18)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/srv/www/directus9.dev/node_modules/argon2/argon2.js:9:56)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
```

**Comment by rijkvanzanten** [comment]
Make sure to check https://github.com/ranisalt/node-argon2/issues/276 and https://github.com/ranisalt/node-argon2/issues/294. It sounds like you're missing some required components in your host machine for Node to properly be able to build native extensions. This is not something we can address in Directus itself

**Comment by Fusseldieb** [comment]
> npm install argon2 --build-from-source

This solved my issue, thank god ahahaha

**Comment by neo7-studio-web** [comment]
> `npm install argon2 --build-from-source`
> fix that error

This works great for an existing project. Unfortunately, it doest not work for a new project

> npx create-directus-project my-project

Results in : 

> /lib64/libc.so.6: version `GLIBC_2.25' not found (required by ...node_modules/argon2/lib/binding/napi-v3/argon2.node)

**Comment by neo7-studio-web** [comment]
Anyway I manged to install manually.

**Comment by prikr** [comment]
If someone is using Directus inside a docker environment, try using `npm install argon2 --build-from-source` after the actual npm install. 

In my example these were my dockerfileLines:
`{
  "schemaVersion": 2,
  "dockerfileLines": [
    "FROM node:14.5.0",
    "RUN mkdir -p /usr/src/app",
    "WORKDIR /usr/src/app",
    "ADD https://www.google.com /time.now",
    "COPY ./package.json /usr/src/app/",
    "RUN npm install && npm cache clean --force",
    "RUN npm install argon2 --build-from-source",
    "COPY ./ /usr/src/app",
    "ENV NODE_ENV production",
    "ENV PORT 8055",
    "EXPOSE 8055",
    "CMD [ \"npm\", \"start\" ]"
  ]
}`

**Comment by rijkvanzanten** [comment]
@neo7-studio-web Did you try installing with `--build-from-source` ?

**Comment by neo7-studio-web** [comment]
Yes I did. Didn't work.

**Comment by rijkvanzanten** [comment]
Okay, any particular issue in the build? By building from source, node will require all the development tools (including gcc, make) to be available and at a version that's compatible with the dependencies that use native binaries, like argon2. I'm no CentOS user myself, but assuming all the build dependencies are available, there shouldn't be any reason why Directus itself wouldn't run, as centos is just x86 linux at the end of the day

**Comment by rijkvanzanten** [comment]
I just tried it out on a clean CentOS 7 installation coming from Docker, and assuming you have your dependencies and build tools up to date, it seems to work just fine:

On my Mac:

```
docker run -ti -p 8055:8055 centos:7
```

Within the container:

```bash
yum update -y
yum -y install curl
curl -sL https://rpm.nodesource.com/setup_16.x | bash -
yum install -y nodejs

yum install -y gcc-c++ make

yum install -y centos-release-scl
yum install -y devtoolset-7-gcc*
scl enable devtoolset-7 bash

mkdir my-project
cd my-project

npm init -y
npm i directus --build-from-source

touch .env
vi .env

## Set to:
# KEY=example-centos
# SECRET=my-secret-string
# ADMIN_EMAIL="admin@example.com"
# ADMIN_PASSWORD="password"
# DB_CLIENT="sqlite3"
# DB_FILENAME="./data.db"
##

npx directus bootstrap
npx directus start

```

**Comment by neo7-studio-web** [comment]
Thank you for taking all this time to test, I really appreciate.
I don't know what to say. Last updates are resulting in this error as from rc 73. I assume devtools are installed on my CentoOS as directus was working before. This is a production environment I can't do a fresh install. I assume there is an update to make to GLIBC but I don't know how (tried several things from the net).

**Comment by neo7-studio-web** [comment]
I think I found a solution here : https://github.com/ranisalt/node-argon2/issues/276#issuecomment-854306499 
`yum install yum install gcc gcc-c++ kernel-devel`
then
`npm rebuild argon2 --build-from-source`

Actually I had gcc and gcc-c++ already installed but not kernel-devel

Now it works !

**Comment by curious-monggo** [comment]
*wipes sweat
Thank you @neo7-studio-web !
I have scoured the web for a solution, tried use make command to build the specific 2.25 version, changed some env vars. Was not able to understand a thing. This on the other hand, simply worked, YAAY PROGRAMMING! 
I can finally sleep!
(Note: directus still not running

PUBLIC_URL should be a full URL > hehe totally no idea
Upload directory is not read/writeable!  > maybe I only need to change it to 755
Database doesn't have Directus tables installed. > running the command for db driver might help
But the fight must go on!
)

**Comment by rijkvanzanten** [comment]
@curious-monggo FWIW

> PUBLIC_URL should be a full URL > hehe totally no idea

The environment variable should be a full valid URL, like `https://directus.example.com/`

> Upload directory is not read/writeable! > maybe I only need to change it to 755

Correct, whatever you have configured as the storage location can't be read/written from/to

> Database doesn't have Directus tables installed. > running the command for db driver might help

Yeah! You can run `directus bootstrap` to bootstrap the database 👍🏻

**Comment by curious-monggo** [comment]
Thank you, @rijkvanzanten !
I really appreciate the response, great tech!

**Comment by cdwmhcc** [comment]
Same, mark

**Comment by kroawen** [comment]
On centos 7.9, I update glibc 2.1 to 2.28 , it works:
1、Check Glibc version:   strings /lib64/libc.so.6 | grep GLIBC , On my System ,it get: 
`GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_2.13
GLIBC_2.14
GLIBC_2.15
GLIBC_2.16
GLIBC_2.17
GLIBC_PRIVATE`.   
I need update GLIBC_2.17 to higher version , recommend Glibc 2.28.

**First please update gcc ,make,bison ,then install Glibc 2.28):**
recommend update:
---------------------------------
**gcc 8.2.0 :** 
# gcc -v
# yum -y install wget bzip2 gcc gcc-c++ glibc-headers
download pakage ：https://mirrors.tuna.tsinghua.edu.cn/gnu/gcc 

# wget -c -P /software/ https://mirrors.tuna.tsinghua.edu.cn/gnu/gcc/gcc-8.2.0/gcc-8.2.0.tar.gz

# cd /software/
# tar -zxvf gcc-8.2.0.tar.gz

# cd gcc-8.2.0
# ./contrib/download_prerequisites   
result：
gmp-6.1.0.tar.bz2: OK
mpfr-3.1.4.tar.bz2: OK
mpc-1.0.3.tar.gz: OK
isl-0.18.tar.bz2: OK
All prerequisites downloaded successfully.

# mkdir build
# cd bulid
# ../configure --prefix=/usr/local/gcc-8.2.0 --enable-bootstrap --enable-checking=release --enable-languages=c,c++ --disable-multilib

# make 
My system exec make at least 3 hours, please waiting it complete.

then: 
# make install

# echo -e '\nexport PATH=/usr/local/gcc-8.2.0/bin:$PATH\n' >> /etc/profile.d/gcc.sh && source /etc/profile.d/gcc.sh

# ln -sv /usr/local/gcc-8.2.0/include/ /usr/include/gcc

#  ldconfig -v    

# ldconfig -p |grep gcc
result: 
libgcc_s.so.1 (libc6,x86-64) => /lib64/libgcc_s.so.1

check version 
#  gcc -v 

------------------------------------
**make 4.2.1:**
First download make 4.2.1 from https://ftp.gnu.org/gnu/make/
# make -v 
# tar -zxvf make-4.2.1.tar.gz
# cd make-4.2.1
# mkdir build
# cd build
# ../configure --prefix=/usr
# sh build.sh
# make install
check result 
#make -v

----------------------------------------
**bison 3.0.4**
# bison -V
if not found result ,need install:

# yum install -y bison

--------------------------------------------------------
all complete , you can install glibc-2.28

download glibc-2.28 from http://ftp.gnu.org/gnu/glibc. 
put it into /software

You can adopt the following steps：

# tar -xf glibc-2.28.tar.gz
# cd glibc-2.28
# mkdir build
# cd build
# ../configure --prefix=/usr --disable-profile --enable-add-ons --with-headers=/usr/include --with-binutils=/usr/bin

# cd build
# ../configure --prefix=/usr --disable-profile --enable-add-ons --with-headers=/usr/include --with-binutils=/usr/bin
# make
# make install 
# ls -l /lib64/libc.so.6

Last, check version : 
# strings /lib64/libc.so.6 | grep GLIBC
.....
GLIBC_2.26
GLIBC_2.27
GLIBC_2.28
GLIBC_PRIVATE

It complete.

Other : 
bootstarp Directus , maybe get error: 
Import Error: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found, you reed update CXXABI : 

# strings /usr/lib64/libstdc++.so.6 | grep 'CXXABI'

download:[ libstdc++.so.6.0](https://www.02405.com/uploads/soft/201124/1-2011241A414.zip)
put it into /usr/lib64 

#  cd /usr/lib64
# rm -rf libstdc++.so.6
# ln -s libstdc++.so.6.0.22 libstdc++.so.6

**Comment by flawlessweb** [comment]
> Anyway I manged to install manually.

how?

**Comment by kellvembarbosa** [comment]
> https://www.02405.com/uploads/soft/201124/1-2011241A414.zip

Thanks for the tutorial, first it worked, now this link is offline, can you help me?

**Comment by cube-dan** [comment]
Here's what worked for me for on CentOS 7: 
1) Install this SCL: https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/ — thanks for the hint @toilandtrouble, here: https://github.com/ranisalt/node-argon2/issues/117#issuecomment-373164783

```bash
# install SCL
sudo yum install centos-release-scl
sudo yum-config-manager --enable rhel-server-rhscl-7-rpms
# install devtoolset-7
sudo yum install devtoolset-7
# enable devtoolset-7 (probably doesn't matter that I do this step from the root of the project; same folder as node_modules)
scl enable devtoolset-7 bash
```

2) Freshen node_modules and package-lock.json (reinstall everything)

```bash
rm -Rf node_modules package-lock.json
npm install
```

3) rebuild argon2 from source — thanks for the hint @davidsandoz, here: https://github.com/ranisalt/node-argon2/issues/276

```bash
npm rebuild argon2 --build-from-source
```

That’s it ... you can now run directus:

```bash
npm run start
```

**Comment by hakulamtta** [comment]
> make install

I tried these commands to install gcc. It's more faster and easier to do~
`$ sudo yum install centos-release-scl
 $ sudo yum install devtoolset-8-gcc*
 $ scl enable devtoolset-8 bash
  $gcc -v`
You can replace step 2 into `sudo yum install devtoolset-7-gcc*` if you want to install version 7.

**Comment by jrbe228** [comment]
kroawen's answer works for me in a container. But only when executing commands interactively. Still trying to fix the [Dockerfile](https://stackoverflow.com/questions/76409227/why-do-commands-work-using-interactive-container-but-fail-in-dockerfile?noredirect=1#comment134736667_76409227). Any ideas why?

**Comment by kpsanmao** [comment]
> lib64

Hi，I'm  the webmaster of the 02405 site and I apologize for the change in the file url due to the rewrite, I have uploaded a copy of that file.I hope it can help you.
[1-2011241A414.zip](https://github.com/directus/directus/files/12213159/1-2011241A414.zip)
