### ISSUE TITLE
Can not select related column when creating o2m

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#6079]
directus v9 rc73

Reproduce:
0) create collection `parent`
0) create collection `child`
0) try to add o2m field to `parent`

expected: `child` collection can be selected as related collection and the PK can be selected as foreign key
actual: all entries in the related collection foreign key field are disabled

![grafik](https://user-images.githubusercontent.com/26493/120810437-56897480-c54b-11eb-803e-a38918efa710.png)

**Comment by benhaynes** [comment]
Seems obvious, but can you confirm that both `day.uuid` and `timeslot.uuid` are set to the actual `uuid` type (not just named "UUID")? The only reason I know that options are disabled in that menu is because the fields don't have exactly matching data-types.

**Comment by laszlokorte** [comment]
Hm I just realized I might have made a mistake. Obviously there is not foreign key column on the child collection yet so I would have to create it instead of selecting it.

But what actually does not work is to add a m2o to the child first and then create a reverse o2m field on the parent and select the m2o field as foreign key because it's of type m2o and not uuid.

I will update the original issue later.

**Comment by rijkvanzanten** [comment]
> as foreign key because it's of type m2o and not uuid.

Lets track that in a separate issue 👍🏻
