### ISSUE TITLE
Row reordering changes include entire client cache on request

### ISSUE THREAD

**Issue by casey-chow** [directus/directus#6085]
## Steps to Reproduce

1. Create a `rows` collection, with a `entries` m2a field holding (sorted) items from a `cells` collection.
2. In the cells collection, set up a further nested m2o field called `value` with an item from a `values` collection.
3. In the `cells` display template, show both `cells.id` and `cells.value.id`.
3. Give a restricted user permissions to create/read/update `rows` and `cells`, but only read permissions on `values`.
4. As admin, create two `cells` containing non-null `values` items. Put these cells in a `rows` item.
5. As a restricted user, attempt to re-order.

## Expected and Actual Behavior

I expect to be able to reorder these items, but instead, I get a `Forbidden` exception. Going into the network debugger, I notice the shape of the request is as follows:

```ts
{
  "entries": [
    {
      "0": {
        "$index": 0,
        "entity": "cell",
        "entity_id": {
          "id": 1,
          "value": {
            "id": 1
          }
        },
        "id": 1,
        "sort": 1
      }
    }
    ... etc ...
  ]
}
```

## Environment

This is a followup to #6041, where similar behavior was occurring, but for ostensibly different reasons. I'm using Directus v9.0.0-rc.73 on macOS + npx, using Firefox 88.

**Comment by casey-chow** [comment]
(I should say I do appreciate how fast it took you guys to resolve #6041, it's been bothering me for a while but I've only now had time to file the bug report. Much thanks!)

**Comment by mpretty-cyro** [comment]
Just to add a little more info to this - it looks like when the reordering change is saved it'll actually override any of the data provided. So if you use a Display Template and only retrieve part of the data of a related object for display it'll fail to save if there are required fields you have excluded.

**Comment by casey-chow** [comment]
@rijkvanzanten Hey there! This item is probably my biggest pain point when using Directus at the moment (and I get multiple complaints from team members on a daily basis for it). I'd have a few cycles to work through this if I got a couple of code pointers where I might be able to identify the problematic behavior, do you know where the reordering logic is focused around in the app?

**Comment by rijkvanzanten** [comment]
Right here:

https://github.com/directus/directus/blob/06925af99188cbab30ae49bf8386594f83565f74/app/src/interfaces/list-m2a/list-m2a.vue#L640-L668
