### ISSUE TITLE
JSON field - default value not properly formated

### ISSUE THREAD

**Issue by botzill** [directus/directus#6088]
Using latest version of the directus: rc.73

When I have a JSON field that has default values, is showing to edit it as:

<img width="645" alt="Screen Shot 2021-06-05 at 09 15 55" src="https://user-images.githubusercontent.com/4686040/120882195-b2e9a400-c5de-11eb-8268-27df3c134586.png">

If we want to add a new item here we have the error:
```json
{
  "errors": [
    {
      "message": "alter table \"services\" alter column \"booking_hours\" set default '08:00,08:15,08:30,09:00,09:30,10:00,10:30,11:00,11:30,12:00,12:30' - invalid input syntax for type json",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

Value in default should be left in JSON format so that we can easily add new items here. To fix this I had to go to DB and remove the invalid value from the default schema.

**Comment by rijkvanzanten** [comment]
What database is this on?

**Comment by botzill** [comment]
PG

**Comment by paescuj** [comment]
Just came across this using PSQL 13. Interestingly, in my case the default value is getting validated... and is then displayed as follows:
![Screenshot 2021-06-09 at 21-54-52 Test](https://user-images.githubusercontent.com/5363448/121425221-76b59b00-c972-11eb-8deb-4acaebe6d93b.png)
