### ISSUE TITLE
mssql boolean default misinterpreted by directus `1`/`0` vs `true`/`false`

### ISSUE THREAD

**Issue by wc-matteo** [directus/directus#6090]
Microsoft SQL Server uses `1` and `0` as values for boolean (bit) fields. Directus uses `true` and `false`.
A boolean field with default value `0` in mssql is seen in directus as with default `true`.

The fact that editing the default value in directus puts `true` and `false` as default values doesn't seem to bother mssql, tho

---
```
mssql 2016 / v9.0.0-rc.73
```

**Comment by Oreilles** [comment]
I think that's intended:

https://github.com/directus/directus/blob/801e86855452bd32d49475d8b07ce151c11e962a/api/src/utils/get-default-value.ts#L40-L41

If mssql doesn't bother, seems like feature, not a bug ?

**Comment by wc-matteo** [comment]
the issues is:

> A boolean field with default value 0 in mssql is seen in directus as with default true.

**Comment by rijkvanzanten** [comment]
If only all the database vendors would just agree on how to store booleans 🙈

**Comment by rijkvanzanten** [comment]
@wc-matteo Do you happen to know if this changed in later versions of MS SQL? I'm using 2019 for my debugging, but don't see any problems around the default value for boolean fields 🤔

**Comment by wc-matteo** [comment]
the default has to be created in mssql.

Try in sql manager
![image](https://user-images.githubusercontent.com/10562635/121482166-2ae40f80-c9cd-11eb-93ae-cc48b511d507.png)
(the parenthesis are added atuomatically)

that value is is seen as default `true` in directus

**Comment by wc-matteo** [comment]
these are the 2 kinds of default `false` values as seen in `INFORMATION_SCHEMA.COLUMNS`

![image](https://user-images.githubusercontent.com/10562635/121483030-03da0d80-c9ce-11eb-9cb9-cf7bd72f1092.png)

**Comment by rijkvanzanten** [comment]
Ahh my DB manager app defaulted input value `0` to `('0')` instead of `((0))`. Lets give that another shot

**Comment by Oreilles** [comment]
Just tested on latest release with both `(false)` and `((0))` as default values, and they are correctly interpreted as `false`.
