### ISSUE TITLE
editing a field properties in data model sometimes changes that field order unexpectedly

### ISSUE THREAD

**Issue by wc-matteo** [directus/directus#6091]
It happened several times during the last week but I didn't notice a pattern, until now.
I think it has to do with the type of change: if the change touches the sql field underneath in a "big" way, it happens.

**EDIT** nvm, it also happens with alias fields (e.g. dividers) or just by changing the field icon.

For example, changing a field `Allow NULL value` triggers this bug.
The new value in the `sort` field is a high number (e.g. 175) compared to the rest (e.g. 1-20)

---
```
mssql 2016 / v9.0.0-rc.73
```

**Comment by nickluger** [comment]
Can confirm that with `rc.73`, also when updating relational triggers. Changing a relational trigger moves the field to an unexpected position in the table/model.
