### ISSUE TITLE
not waiting for a relational o2m field to load means creating a new item instead of editing the existing one

### ISSUE THREAD

**Issue by wc-matteo** [directus/directus#6094]
### `italiano` is loading (it has an item)

![image](https://user-images.githubusercontent.com/10562635/120896830-7d1ade80-c623-11eb-8a91-52eccefa4279.png)

### clicking while it's loading results in `creating`

![image](https://user-images.githubusercontent.com/10562635/120896880-c834f180-c623-11eb-9056-6c3c72ce5fd7.png)

### while waiting for it to load

![image](https://user-images.githubusercontent.com/10562635/120897102-d46d7e80-c624-11eb-84cd-f9b00da7a5f3.png)

### results in `editing`

![image](https://user-images.githubusercontent.com/10562635/120896900-ea2e7400-c623-11eb-8805-0b63a68ff8f9.png)

---
```
mssql 2016 / v9.0.0-rc.73
```

**Comment by benhaynes** [comment]
So weird!! I guess that somehow makes sense though...

**Comment by rijkvanzanten** [comment]
Simple issue with a simple fix: the translations interface doesn't disable the click on the rows while the item content is loading. There's a small window between where the languages are loaded, but the items themselves haven't
