### ISSUE TITLE
UI: Camera Image save

### ISSUE THREAD

**Issue by RNGR** [directus/directus#61]
A custom UI that allows you to take a picture with your computers camera. Good for user avatars.

http://www.xarg.org/project/jquery-webcam-plugin/

**Comment by WellingGuzman** [comment]
we can forgot about that jquery plugn and use some native solutions such as: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

**Comment by benhaynes** [comment]
Perfect – much better! Also, we should focus on making the *existing* UIs better. So I don't think we should make this a NEW UI... but an option within the `Single File` UI

**Comment by benhaynes** [comment]
**[Migrated to FeatHub](http://feathub.com/directus/directus/+2)**

Please use the [Directus FeatHub](http://feathub.com/directus/directus) to vote for features or make new request. Accepted feature requests will be added to GitHub Issues.
