### ISSUE TITLE
[M2M] New item has no sort property

### ISSUE THREAD

**Issue by stepugnetti** [directus/directus#6111]
When adding related junction items through an M2M interface, new items will have their sort field set to null. I would have expected a not-null default value that preserve the ordering displayed in the front end, as discussed in issue #4280 for M2A relations.

To reproduce this, create two collections like so:
* Collection A with a string field "name"
* Collection B with a M2M relation to collection A

Then add a few items to collection B, create one item in collection A and then use "Add Existing" to add junction field relations to add one or more items of collection B. After saving, the records of the junction table will have a null sort attribute.

I am using the Docker deployment of version v9.0.0-rc.73.

**Comment by nayeem01** [comment]
@stepugnetti @rijkvanzanten 
hi there
I would love to work on this
can you help me to get started?

**Comment by miguelurtado** [comment]
Hello I have same problem in v9.0-rc.83
