### ISSUE TITLE
Says "invalid payload" for invalid email in login

### ISSUE THREAD

**Issue by azharul-islam** [directus/directus#6115]
Login page shows "invalid payload" for invalid email, while it should show error for invalid email format

Type "test@test.cob" in email field and any password in password field and click login to reproduce it.

Environment: MySQL 8, rc.73
<img width="439" alt="Screen Shot 2021-06-07 at 10 43 40 PM" src="https://user-images.githubusercontent.com/38819502/121079498-dbda8680-c7e2-11eb-8f10-299a77e8eb82.png">

**Comment by paescuj** [comment]
Request already returns `"\"email\" must be a valid email"`, it just needs to be parsed accordingly in the UI.

**Comment by rijkvanzanten** [comment]
For this particular use case, it should just show the same "wrong username/password" message I think
