### ISSUE TITLE
Problems with fields default values

### ISSUE THREAD

**Issue by Yomayo** [directus/directus#6130]
Hello,
If field's default value is null (I leave field empty). All ok.
But if I need select default value (example for dropdown), I get similar error every time.
![image](https://user-images.githubusercontent.com/831352/121152046-8dae9d00-c84d-11eb-8a10-96e68a7d1bd4.png)

Basically everywhere where i need set default value like true or false for status.

Where I get error:
Every time I use standard field.

---
### Using with Boolean:
Shema:
![image](https://user-images.githubusercontent.com/831352/121153749-006c4800-c84f-11eb-9609-211fcdb4365d.png)

Error:
![image](https://user-images.githubusercontent.com/831352/121153884-20037080-c84f-11eb-86f5-d2333cc1ea2c.png)

---
### Using Input:
Shema:
![image](https://user-images.githubusercontent.com/831352/121154196-71abfb00-c84f-11eb-91fc-6d5bbdda30af.png)

Error:
![image](https://user-images.githubusercontent.com/831352/121154257-8092ad80-c84f-11eb-8e95-88ada416750a.png)

---
### Using Input as Dropdown:
Shema:
![image](https://user-images.githubusercontent.com/831352/121154708-dcf5cd00-c84f-11eb-8c28-1f5e164ecc1f.png)

Interface:
![image](https://user-images.githubusercontent.com/831352/121155813-cef47c00-c850-11eb-962f-86c9acdd5dc8.png)

Error:
![image](https://user-images.githubusercontent.com/831352/121156175-2561ba80-c851-11eb-81f8-5d7d32041c17.png)

---

### Project details
Directus Version: 9.0.0-rc.74 and v9.0.0-rc.73
Environment: production
OS: Linux 4.19.0
Node: 14.17.0
Database: MariaDB
Database version: 10.5 (1:10.5.10+maria~focal)

Host:
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
Version: 10.9
Architecture: amd64

Docker:
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:45 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by HitomiTenshi** [comment]
We are facing the same issue using `MariaDB 10.3.29` on `Ubuntu 20.04 LTS`. We can't change the status field that gets autogenerated, to change it we would have to delete it and recreate it with our changes. Can get very tiresome when setting up new databases.

**Comment by paescuj** [comment]
@rijkvanzanten The ALTER TABLE statement is indeed wrong. It should be `varchar(<size>)` (e.g. `varchar(255)`) instead of `varchar`.
Should be fixable somewhere here, I guess:
https://github.com/directus/directus/blob/a40638a3bf5148cc44090fd6a48fb36463d0bc18/api/src/services/fields.ts#L418-L433

If you'd push me in the right direction, I can submit a PR.

**Comment by Yomayo** [comment]
I recreated a container with Directus and PostgreSQL 12 database. So far so good. Problems appears while using MariaDB or any MySQL database. For my current project PostgreSQL will be ok.
In Directus v9.0.0-rc.64 and MariaDB 10.5 all good.

**Comment by rijkvanzanten** [comment]
@paescuj Seems like max_length is not set properly there on 423
