### ISSUE TITLE
Custom permissions not working as expected

### ISSUE THREAD

**Issue by leonardodipace** [directus/directus#6133]
Hi, I'm creating a blog and I'm using Directus. I want to limit authors so that they can only edit the posts they created, without allowing them to update those posts that don't belong to them.

I tried setting this custom permission:
`{
    "created_by": {
    	"_eq": $CURRENT_USER
    }
}`

but it automatically changes it to 
`{
    "created_by":  {}
}`
after i save.

Checking the console, I noticed this error:
![immagine](https://user-images.githubusercontent.com/63299726/121172401-f4d14f00-c857-11eb-85f9-5ab9591378dd.png)

I'm using Directus v.9.0.0-rc.74 with MySQL 8 running on a VPS and the browser I used is Firefox 89.0

**Comment by rijkvanzanten** [comment]
`{ "created_by": { "_eq": $CURRENT_USER } }` isn't valid JSON, use

```json
{ "created_by": { "_eq": "$CURRENT_USER" } }
```
