### ISSUE TITLE
SyntaxError when adding directus to PM2 with package.json script in Windows.

### ISSUE THREAD

**Issue by NirvanKS** [directus/directus#6138]
1) The issue and what you expected to happen
    An error is thrown when using pm2 start npm --name "app name" -- start with a start script in package.json, while it should successfully start the application on pm2.

2) Exact steps to reproduce this issue
    
- In the package.json file, have a scripts section like this:
```
 "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "npx directus start"
  },
```
- Then, successfully install pm2 globally.
- Navigate to the project folder in the command prompt and run `pm2 start npm --name "app name" -- start`
- The following error occurs:
```
SyntaxError: Unexpected token ':'

at wrapSafe (internal/modules/cjs/loader.js:984:16)

at Module._compile (internal/modules/cjs/loader.js:1032:27)

at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)

at Module.load (internal/modules/cjs/loader.js:933:32)

at Function.Module._load (internal/modules/cjs/loader.js:774:14)

at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainerFork.js:33:23)

at Module._compile (internal/modules/cjs/loader.js:1068:30)

at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)

at Module.load (internal/modules/cjs/loader.js:933:32)

at Function.Module._load (internal/modules/cjs/loader.js:774:14)
```

3) Your environment:
    Windows Server 2019
    What version of Directus you are using - 9.0.0-rc.68
    Which DBMS are you using - Postgres 12 
    Which deployment are you using - npx
    PM2 v5.0.4
    What browser are you using Chrome 91.

Please let me know if there are any insights on my problem. I am amazed at the work the directus crew has put into this repo and I hope I can bring light to this potential issue others may face.

If this issue cannot be resolved soon, I am willing to try hosting directus using iisnode with the help of the new documentation from @nichols-green in v9.0.0-rc.71

**Comment by nichols-green** [comment]
I'm not at all familiar enough with PM2 to diagnose this, but it seems this is a problem with PM2 and NPM. See [this issue](https://github.com/Unitech/pm2/issues/3657) in the PM2 repo to see how I came to that assumption. Specifically, there is a comment with many reactions that seems to offer a solution to this. Good luck!

**Comment by NirvanKS** [comment]
Thank you very much for your help, I was able to successfully get it up and running.

A summary for others:

Instead of running `pm2 start npm --name "app name" -- start` , replace npm in the line with the absolute location of the script you want to run. In my case, it was directus start.

The line that should work will be :

`pm2 start D:\dev\myapp\node_modules\directus\dist\start.js --name "myapp" -- start`
