### ISSUE TITLE
Existing foreign keys not mirrored inside Directus

### ISSUE THREAD

**Issue by calsch03** [directus/directus#6149]
When installing Directus on an existing PostgreSQL database the existing Foreign Key constrains and relationships aren't created inside the Directus admin app. I'm unsure if my foreign keys are setup in a way Directus doesn't detected them or if there is an issue with Directus.

Exact steps to reproduce this issue:
    - I simply created a PostgreSQL database using the pgAdmin 4 UI tool.
    - Created a new table with a primary key.
    - Created a second table with a primary key and foreign key constraint to the first table.
    - Installed Directus to the database and Directus doesn't detect the foreign key field as a relational field.

My environment:
    Directus: rc.74
    DBMS: PostgreSQL 13
    Deployment: npx

**Comment by rijkvanzanten** [comment]
@calsch03 Would you be able to share a DB dump with foreign key constraints in it?

**Comment by calsch03** [comment]
Sure, I'll send you the database dump.

**Comment by rijkvanzanten** [comment]
I tried reproducing it with this very minimal setup, but it seems to work as expected:

```sql
CREATE SEQUENCE IF NOT EXISTS articles_id_seq;

CREATE TABLE "public"."articles" (
    "id" int4 NOT NULL DEFAULT nextval('articles_id_seq'::regclass),
    "author" int4,
    "title" varchar,
    PRIMARY KEY ("id")
);

CREATE SEQUENCE IF NOT EXISTS authors_id_seq;

CREATE TABLE "public"."authors" (
    "id" int4 NOT NULL DEFAULT nextval('authors_id_seq'::regclass),
    "name" varchar,
    PRIMARY KEY ("id")
);

ALTER TABLE "public"."articles" ADD FOREIGN KEY ("author") REFERENCES "public"."authors"("id");
```

**Comment by calsch03** [comment]
Could be a problem with my setup then. I've mailed you a database dump, if you would like to check.

**Comment by rijkvanzanten** [comment]
Seems to be an issue in how knex-schema-inspector reads capitalized tables/columns. The fields are returned wrapped in quotes `\"ExampleColumn\"` instead of `ExampleColumn`
