### ISSUE TITLE
Messages polling trigger render

### ISSUE THREAD

**Issue by WellingGuzman** [directus/directus#615]
I wanted to open this issue to remember that even when there's not new data from the server it still render, and this it is not necessary I believe.

**Comment by WellingGuzman** [comment]
@benhaynes while working on this I think messages polling should be called notification polling, so it would be more easy to handle whether is a new message, fetching a specific message or just getting info about whether is there a new message or not.

This would also help if in the future there would be any other type of notification implemented.

**Comment by benhaynes** [comment]
@WellingGuzman That sounds good to me. Are you only talking about the naming?

**Currently:**
* Messages are the emails that are sent within Directus (/messages)
* Comments are messages attached to a specific table-item (seen at the bottom of the edit pages)
* Notifications are the errors/alerts/warnings/notifications that come up in the bottom-right of the screen at times

**Comment by WellingGuzman** [comment]
@benhaynes exactly, I'm talking about keep thing as they are but the polling system need to be moved to a new object that only handles polling, and by means it would include new messages which would trigger the Notification showing a "notification" of the new message.

In other word anything that is coming from that object you know is polling for notification activities, which I believe as right now are only message, in the future could be more.

What do you think?

**Comment by benhaynes** [comment]
@WellingGuzman That sounds good. Would the sidebar still update if there are new messages (the green dot next to "Messages"? And if you are on the "Messages" page would you see a new message appear without refreshing?

If so, this sounds good!

**Comment by WellingGuzman** [comment]
@benhaynes Everything would work as it's working now, just the object that listen and trigger the event alerting there's new message would be a new one.

**Comment by benhaynes** [comment]
@WellingGuzman Perfect.

**Comment by benhaynes** [comment]
@WellingGuzman Do you want to keep this issue open to reference your comment above? Or is there another ticket for this?

**Comment by WellingGuzman** [comment]
@benhaynes there's not new ticket open referencing the commented above, we can keep this open, until the notification object is implemented.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/12c6955fb296caaab80f86e0b89dd92aa1b02dd4

**Comment by benhaynes** [comment]
Two years later!! Finally squashed – nice!
