### ISSUE TITLE
API doesn't delete collection from "one_related_collections" on collection delete

### ISSUE THREAD

**Issue by ludi81** [directus/directus#6161]
Hi,
I just updated to rc.74 and get some strange problems. I tried it with the npx version and the source version.

If I execute the following request with an none admin user it works fine:

`items/screens?access_token={{bearer}}&fields=*,components.*,components.item.*.*`

But If I use an admin bearer the following exception will be thrown:
![2021-06-09_21-08-21](https://user-images.githubusercontent.com/25344341/121414368-d7d77180-c966-11eb-8d08-7d632734b7bf.png)

Without the last fields attribute `components.item.*.*` it works fine. components is a o2a relationship.

**Comment by rijkvanzanten** [comment]
Are you sure this is related to the admin user, and not the difference in `fields`? The fact that you mention 

> Without the last fields attribute `components.item.*.*` it works fine.

and the shown error message it makes me think it's the `fields` parameter that might be causing issues?

**Comment by ludi81** [comment]
> Are you sure this is related to the admin user, and not the difference in `fields`? The fact that you mention
> 
> > Without the last fields attribute `components.item.*.*` it works fine.
> 
> and the shown error message it makes me think it's the `fields` parameter that might be causing issues?

Yes I am sure:

this works
`GET {{host}}/items/screens?access_token={{bearer}}&fields=*,components.*,components.item.*.*`

this does not work
`GET {{host}}/items/screens?access_token={{bearerAdmin}}&fields=*,components.*,components.item.*.*`

the only difference is the bearer

but this works again (even with the admin bearer)
`GET {{host}}/items/screens?access_token={{bearerAdmin}}&fields=*,components.*`

**Comment by rijkvanzanten** [comment]
Would you be able to share a database dump (either here on in private through rijk@directus.io) of where this is happening?

**Comment by ludi81** [comment]
> Would you be able to share a database dump (either here on in private through [rijk@directus.io](mailto:rijk@directus.io)) of where this is happening?

I send you the database dump to your email.

**Comment by rijkvanzanten** [comment]
@ludi81 The reason this is happening is because a collection is configured in the m2a that no longer exists (component_nutrition) 🤔 

On delete of a collection, Directus should be cleaning up the relationship information automatically. Did you delete that collection through Directus, or directly in the database?

**Comment by ludi81** [comment]
Thanks for your help.

I deleted the component_nutrion and a second one within directus. In this case directus does not clean every relation correctly.

**Comment by rijkvanzanten** [comment]
Gotcha! I'll consider this thread the issue for that problem then 👍🏻
