### ISSUE TITLE
Creating a new collection displays an error

### ISSUE THREAD

**Issue by supermx1** [directus/directus#6181]
Directus 9.0.0 rc.74
MySQL 8
Cpanel

Getting this error every time I want to create a collection and check all the fields i.e sort, user_created, user_updated, etc. If I refresh the page I see the collection, but it shows this error first. If I create another collection and I don't select any of the default fields then it works perfectly.

https://user-images.githubusercontent.com/9326922/121513907-49550580-c9e3-11eb-851e-467385996948.mp4

**Comment by supermx1** [comment]
![Screen Shot 2021-06-10 at 12 05 44 PM](https://user-images.githubusercontent.com/9326922/121514688-34c53d00-c9e4-11eb-9719-987c60a10719.jpg)

**Comment by supermx1** [comment]
![Screen Shot 2021-06-10 at 12 09 48 PM](https://user-images.githubusercontent.com/9326922/121515157-c3d25500-c9e4-11eb-8522-a56b4d1e002a.jpg)

Then I discovered that if I create a collection and I don't select `user_created` and `user_updated` the collection is created successfully.

**Comment by supermx1** [comment]
Creating M2M fields too causes a similar error too. I tried creating multiple files upload (M2M relationship) and a similar error also popped up. Which I think is an issue with the foreign key relationship

**Comment by supermx1** [comment]
![Screen Shot 2021-06-10 at 3 49 29 PM](https://user-images.githubusercontent.com/9326922/121546754-73b6bb00-ca03-11eb-9875-df028a492a15.jpg)


![Screen Shot 2021-06-10 at 4 40 30 PM](https://user-images.githubusercontent.com/9326922/121555061-94ceda00-ca0a-11eb-9bc3-7a0e803ab518.jpg)

**Comment by rijkvanzanten** [comment]
I'm having some trouble reproducing this locally on a fresh installation. Could you share a DB dump where this is happening?

**Comment by rijkvanzanten** [comment]
Directus doesn't set the collation / character set, so that's controlled by the connection / database itself.. 

You can use `DB_CHARSET` to force it to a given string though, if you wanna enforce the database connection to always default to a specific one 👍🏻

**Comment by supermx1** [comment]
> Directus doesn't set the collation / character set, so that's controlled by the connection / database itself..
> 
> You can use `DB_CHARSET` to force it to a given string though, if you wanna enforce the database connection to always default to a specific one 👍🏻

hmmm. I guess i will have to google this. Not sure i understand your advice.

**Comment by rijkvanzanten** [comment]
MySQL is a little confusing around this.. You can have different character sets for different tables/columns. This characterset that's used is controlled on the database itself (default), then connection-wide, then in the actual queries that are ran. Directus doesn't use character sets in the queries directly, but you can configure additional flags on the `mysql` package that's used for the connection. All of these can be controlled through environment variables in Directus: https://www.npmjs.com/package/mysql#connection-options (f.e. `DB_CHARSET="utf8mb4"`)

**Comment by supermx1** [comment]
![Screen Shot 2021-06-10 at 11 31 28 PM](https://user-images.githubusercontent.com/9326922/121605314-1a22b080-ca44-11eb-9c04-e6b898011717.jpg)

I think it is set to utf8
