### ISSUE TITLE
Env var "false" treated as true

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#6189]
@paescuj Ran into a little bug coming from the _FILE update:

https://github.com/directus/directus/blob/4ac610c795532b92df53af4ecc4a3e8d97f63cfc/api/src/env.ts#L223-L226

`!!'false' === true`, so setting an env var to "false" will now make it act like true

**Comment by paescuj** [comment]
I'm sorry! 🙈 I've misinterpreted !!

**Comment by rijkvanzanten** [comment]
No worries, easy fix 🙂
