### ISSUE TITLE
App can't render on sub-folder in domain

### ISSUE THREAD

**Issue by HitomiTenshi** [directus/directus#6192]
1) The issue and what you expected to happen:
    Directus works

2) Exact steps to reproduce this issue:
    Sign in page looks fine, but after signing in everything is a mess.

![msedge_2021-06-10_23-48-57](https://user-images.githubusercontent.com/7304212/121602618-dcc02200-ca47-11eb-8297-efed360d1f31.png)

3) Your environment:
    What version of Directus you are using: `v9.0.0-rc.75`
    Which DBMS are you using: `MariaDB 10.3.29`
    Which deployment are you using `npx`
    What browser are you using `Chrome 91` and `Edge 91`

    I have followed all 8 steps in troubleshooting without success.

4) Any other relevant information we might need to reproduce this issue:
    The dev tool is spamming the following errors in the sign in page and after signing in:

## 1
![chrome_2021-06-10_23-56-32](https://user-images.githubusercontent.com/7304212/121602415-8eab1e80-ca47-11eb-8554-62114605c59b.png)

## 2
![ShareX_2021-06-11_00-03-00](https://user-images.githubusercontent.com/7304212/121603013-6f60c100-ca48-11eb-8255-5e3e33777b5c.png)

## 3
![chrome_2021-06-10_23-56-56](https://user-images.githubusercontent.com/7304212/121602432-94086900-ca47-11eb-9c3e-f39051ea4150.png)

**Comment by supermx1** [comment]
![Screen Shot 2021-06-10 at 11 01 31 PM](https://user-images.githubusercontent.com/9326922/121602858-cf9f3500-ca3f-11eb-9f0f-05160e9214a1.jpg)

Same here. Completed messed mine up too. Lol. I feel like i am always drawing the short straw. Lol. I happen to always run into these kinda of issues all the time.

**Comment by HitomiTenshi** [comment]
According to the error `Failed to decode downloaded font` it seems like it is trying to access the font at the wrong location. My Directus Instance is hosted with the following settings in `.env`:

```
PORT=8055
PUBLIC_URL="/api/"
```

It seems like with the current version it stopped honoring the `PUBLIC_URL` setting. It should request the fonts from `www.myurl.com/api/<font url>`, atleast that is what it was doing in the previous `rc.74`.

**Comment by HitomiTenshi** [comment]
@rijkvanzanten Another thing I noticed is that `rc.75` does not log the following during startup anymore:

> ✨ Email connection established

It just logs `✨ Server started at port 8055`. Not sure if that is related to this error. I use SMTP settings.

To anyone trapped in this nightmare ( @supermx1 ), you can free yourself from this pain by executing the following commands (assuming you are using the `npx` directus cli):

1. Stop the currently running directus instance
2. `npx directus database migrate:down` 
3. `npm install directus@v9.0.0-rc.74`
4. Start the directus instance again

**Comment by rijkvanzanten** [comment]
> does not log the following during startup anymore:

Yup! That's correct 👍🏻 We're making sure no connections are made that aren't used (yet) on file imports to officially support server less architectures in the future
