### ISSUE TITLE
Document `_FILE` environment variables

### ISSUE THREAD

**Issue by paescuj** [directus/directus#6203]
https://docs.directus.io/reference/environment-variables/

Documentation for `_FILE` environment variables (#6101) is currently missing.

Also, the introduction text is a bit misleading IMO, since besides the `.env`file variables are also coming from, well, the environment:
> Environment Variables are used for all configuration within Directus projects. They are managed in the root .env file, which is created during the installation process.

**Comment by rijkvanzanten** [comment]
Weird.. I'd swear I wrote a little note on that PR branch :S Must've forgotten to push it up? 🤔

**Comment by paescuj** [comment]
Hello branch, u still here? 🤔

**Comment by rijkvanzanten** [comment]
New branch, who dis
