### ISSUE TITLE
Multiple indexes on same column makes field show up multiple times

### ISSUE THREAD

**Issue by Mrmiffo** [directus/directus#6204]
**The issue and what you expected to happen**
When a unique index is added using two columns of a table, the given columns will appear twice in the Directus App.
Expected: The fields used in the unique key index should only be displayed once. 

![image](https://user-images.githubusercontent.com/8545443/121655678-13755700-ca9f-11eb-8cda-98d9ddb8de53.png)
![image](https://user-images.githubusercontent.com/8545443/121656072-65b67800-ca9f-11eb-9f5b-dc52db5430c2.png)

```
CREATE TABLE `product_category_translations` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `product_category` int unsigned DEFAULT NULL,
  `language` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `date_created` timestamp NULL DEFAULT NULL,
  `date_updated` timestamp NULL DEFAULT NULL,
  `user_updated` char(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_category_language` (`product_category`,`language`),
  KEY `idx_category` (`product_category`),
  KEY `idx_language` (`language`),
  CONSTRAINT `product_category_translations_language_foreign` FOREIGN KEY (`language`) REFERENCES `languages` (`code`) ON DELETE SET NULL,
  CONSTRAINT `product_category_translations_product_category_foreign` FOREIGN KEY (`product_category`) REFERENCES `product_categories` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
```

**Exact steps to reproduce this issue**
1. Create a collection called test
2. Add a translations field using default settings.
3. Create a unique key index on the translations table using `CREATE UNIQUE INDEX idx_test_language ON test_translations (test_id, language_code);`

The fields "language_code" and "test_id" will now appear twice in the Directus App.

**Your environment**
  rc.73
  MySQL 8
  npx
  Chrome

**Any other relevant information we might need to reproduce this issue**
See table details above.

**Comment by rijkvanzanten** [comment]
@paescuj Yeah seems to be the same problem, different database 👍🏻

**Comment by carolin-skiply** [comment]
Same here ! We cannot using a unique key and a foreign key on the same field without having this field duplicates in our front: not friendly at all for our users :( . Did you find a fix ?

**Comment by rijkvanzanten** [comment]
@carolin-skiply see https://github.com/directus/directus/issues/5815 with fix https://github.com/knex/knex-schema-inspector/commit/bcb0dc60a578dbb02ef7b5304b1f1ea0ebe6aba1. We'll have to do the same for the other DB vendors as well. Wanna open a PR?

**Comment by Beiri22** [comment]
But what about just deduplicating the result list of knex in directus?

**Comment by Beiri22** [comment]
It's good to see, that you @Nitwel have assigned the topic. If I can help with additional information or testing, just say so.

**Comment by keesvanbemmel** [comment]
> It's good to see, that you @Nitwel have assigned the topic. If I can help with additional information or testing, just say so.

If I can help or help reproduce based on #8377 than let me know @Nitwel

**Comment by keesvanbemmel** [comment]
@Nitwel I hate asking this, but do you have a timeline on this issue? 🙏

**Comment by Nitwel** [comment]
I was able to fix it for MariaDB but not other Databases as I'm not familiar with them.

We can't really give an estimate on this as we're OSS + the issue is part of the knex-schema-inspector.

**Comment by Beiri22** [comment]
Can't we remove the duplicates in directus after gathering the list from Schema Inspector? Column names are unique, so that should Not Pose too much of a risk

**Comment by Oreilles** [comment]
> Can't we remove the duplicates in directus after gathering the list from Schema Inspector? Column names are unique, so that should Not Pose too much of a risk

This is a bug with knex-schema-inspector, so that is were we should fix it.
I'll look into it.

**Comment by dstoyanoff** [comment]
Hey guys,
for me on Postgres, this problem was resulting in #8377, where the collection will just not load in the UI due to having primary and unique key on the same field.

I have create a temporary patch to resolve this. What I did was to create a patch script that runs after I take the snapshot. This patch takes all fields and unsets "is_unique" for the fields that are already "is_primary_key". 

Here is a gist of the patch file - https://gist.github.com/dstoyanoff/6471b66724b2e37bc2246df4a4a6badc
With that, my script looks like this:
```
"schema:snapshot": "npx directus@latest schema snapshot snapshot.json -y --format json -y && ts-node ./patch-snapshot.ts && prettier --write snapshot.json"
```

**Comment by Beiri22** [comment]
Just checked with rc98; the issue seems to be still there in my case ( multi-key-unique) ... can anyone confirm/correct?

**Comment by rijkvanzanten** [comment]
@Beiri22 this issue hasn't been closed, so that's correct

**Comment by justoverclockl** [comment]
Solved in the rc.100 for me

**Comment by Oreilles** [comment]
Closed with https://github.com/knex/knex-schema-inspector/pull/74
