### ISSUE TITLE
Creating JSON field results in Text field creation in SQL Server 

### ISSUE THREAD

**Issue by Oreilles** [directus/directus#6206]
Reproduce:
* Create a JSON Field
* It's created and shown as Text with length -1.

Tested on `v9.0.0-rc.74`, with `mcr.microsoft.com/mssql/server:2019-latest` image present in the root `docker-compose.yml`

**Comment by paescuj** [comment]
As far as I know, JSON is usually stored as NVARCHAR in MSSQL, so this might be intended.

**Comment by Oreilles** [comment]
It wasn't, but thanks for you comment as it reminded me of issue #5944 for which the fix https://github.com/directus/directus/commit/85d33d9ffc8f3a9278f8266c7414a846a7f0480b introduced the current bug.

Cheers.
