### ISSUE TITLE
Many to One interface not working on fresh install with existing foreign keys

### ISSUE THREAD

**Issue by calsch03** [directus/directus#6207]
Found an issue with a fresh install of Directus on a database with existing foreign keys/ relationships setup. The `Many to One` interface doesn't display when you enable it for existing foreign keys. Might be caused by the foreign key field not existing in the `directus_relations` table, as this table remains empty when enabling the interface.

Exact steps to reproduce this issue
    - Create a database with two tables.
    - Table one with a primary key.
    - Second table with primary key and foreign key to table one.
    - Install Directus on the database.
    - Inside Directus `Data Model` settings, go to the second table and enable the `Many to One` interface for the foreign key field.
    - When creating an item for table two in Directus the foreign key field will be empty and the browser console will throw an error.

![image](https://user-images.githubusercontent.com/19907926/121663200-75858a80-caa6-11eb-84c3-b92485e98c14.png)
![image](https://user-images.githubusercontent.com/19907926/121663275-8cc47800-caa6-11eb-856e-afc53f98bfdd.png)

Environment:
    - Directus: rc75
    - DBMS: Postgres 13
    - Deployment: npx

**Comment by ilijaNL** [comment]
Have the same problem on existing data

**Comment by calsch03** [comment]
Hi @rijkvanzanten, Looks like this issue also causes problems with `one-to-many` interfaces and existing foreign keys with no meta row 😅. Might be an issue for other relational interfaces as well.

**Comment by rijkvanzanten** [comment]
@calsch03 I'm wondering if the one to many is able to operate without that info 🤔 We need the `one_field` stored under directus_relations to know what relationship the one to many applies to. How did you setup the o2m field without going through the relational setup?

**Comment by calsch03** [comment]
I did use the relational setup and targeted a foreign key, but I'm having difficulties to reproduce it. I'll do some more tests.

**Comment by calsch03** [comment]
Sorry @rijkvanzanten, it was my bad. I simply selected the wrong foreign key and that cased the `one-to-many` interface to break. When selecting the right foreign key there are no issues.

**Comment by rijkvanzanten** [comment]
Gotchu! Thanks for confirming :)
