### ISSUE TITLE
WYSIWYG fields are blank after upgrading to rc.75

### ISSUE THREAD

**Issue by Kamalito75** [directus/directus#6217]
Hi
After upgrading to rc.75 the WYSIWYG fields are no more displayed. Empty white areas are displayed instead.

My env :
- Directus : 9.0.0-rc75
- Node 16.3.0
- The bug appears on all browsers

**Comment by domdus** [comment]
Was about to report the same - Confirming.

**Comment by Kinzi** [comment]
Same here!

**Comment by pietervandendungen** [comment]
Experienced the same thing. When inspecting the raw value, data still seems to be there but fields are not visible in UI.

**Comment by nathanhere** [comment]
Style attribute specifies that elements are hidden, for some reason.
![Screen Shot 2021-06-13 at 7 35 07 PM](https://user-images.githubusercontent.com/1151667/121827272-0617c280-cc81-11eb-939b-e03ab668135c.png)
![Screen Shot 2021-06-13 at 7 28 21 PM](https://user-images.githubusercontent.com/1151667/121827273-0617c280-cc81-11eb-9d49-460564b0d26b.png)

**Comment by masterwendu** [comment]
Hi,
I can reproduce the issue too.

@nathanhere it's not because of the hidden text area, this is actually a placeholder for the value. It was always hidden.

I'll check if I can find the issue.
