### ISSUE TITLE
rc.75 - "Discard Changes" action not working with plain text in WYSIWYG field

### ISSUE THREAD

**Issue by domdus** [directus/directus#6218]
When trying to discard item editing - the exit dialog (discard or keep?) reappears endless times.

---

### Project details
Directus Version: 9.0.0-rc.75
Environment: false
OS: Linux 4.19.0-16-amd64
Node: 14.15.4

**Comment by domdus** [comment]
UPDATE:
The issue is more specific than I thought. In general the discard action works when editing/creating items via the app.

You can only run into this when you import plain text to a WYSIWYG field via the API.
The next time you edit the item (in app) - WYSIWYG will format it and add the required tags, which results in item-changed-state. 
! At this point it's not possible to discard editing !

However, the formatting is required there and can be saved - which works.
After that there is no more issue with discard item editing.

**Comment by domdus** [comment]
In other words:
If I initially wrap my content with <p> during API import like this:
`{
    "description": "<p>test test test</p>"
}`

...the item does not appear in changed-state just by accessing it (in app) for the first time.

**Comment by rijkvanzanten** [comment]
Interesting!

The first load of the interface converts the raw text value into HTML, which causes the "change". The discard action reverts to raw text, but between it discarding the changes and it navigating, the interface has already re-converted it to HTML, causing the new change 🔁
