### ISSUE TITLE
Calendar layout filter is not correct

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/directus#6226]
I think the filter of the calendar layout is not 100% correct.

The situation I have is, that my `item` is more than one month long. (season for hotel pricing) The current filter just displays events which start in the current month. So even a event starting on the last day of the previous month wouldn't be displayed.

Current filter:
```
{
    "_and": [
        {"start":{"_gte":"###FIRST###"}},
        {"start":{"_lte":"###LAST###"}}
    ]
}
```
This filter should include events starting before:
```
{
    "_or": [
        {
            "_and": [
                {"start":{"_lte":"###FIRST###"}},
                {"end":{"_gte":"###FIRST###"}}
            ]
        },
        {
            "_and": [
                {"start":{"_gte":"###FIRST###"}},
                {"start":{"_lte":"###LAST###"}}
            ]
        }
    ]
}
```

---

### Project details
Directus Version: 9.0.0-rc.75
Environment: false
OS: Linux 4.18.0-147.8.1.el8_1.x86_64
Node: 15.5.1

**Comment by Oreilles** [comment]
Closing in favour of https://github.com/directus/directus/pull/9914
