### ISSUE TITLE
Custom Display causes `Cannot read property '_c' of undefined` error after upgrading to version RC 75.

### ISSUE THREAD

**Issue by B-Esmaili** [directus/directus#6229]
1) The issue and what you expected to happen
   After upgrading to version RC 75 i get following error :
` Cannot read property '_c' of undefined`

2) Exact steps to reproduce this issue
  Just created a custom display following [docs](https://docs.directus.io/guides/displays/) : and use that display in admin panel.List item would not render anything.

3) Your environment:
    What version of Directus you are using. -> RC 75
    Which DBMS are you using (MySQL 8, Postgres 12, ...). -> Sqlite
    Which deployment are you using (npx, Docker, ...). -> npx
    What browser are you using (Chrome 87, Safari 14, ...). -> Chrome 90

**Comment by nickrum** [comment]
We switched from Vue 2 to Vue 3 in Directus version `v9.0.0-rc.75` and haven't yet updated the docs for custom app extensions. There is a note explaining this at the top of the [release notes](https://github.com/directus/directus/releases/tag/v9.0.0-rc.75).

**Comment by B-Esmaili** [comment]
@nickrum Thanks for the helpful comment. I followed the updated docs but still the same error occurs.

**Comment by nickrum** [comment]
That's odd, for me it is working fine with the updated docs. Could you share the bundled extension entrypoint, so I can test this on my end?
