### ISSUE TITLE
Potential merging/JSON of Directus proprietary tables

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#623]
**Just a reminder for later:** This might be a bad idea or against the mentality of Backbone's data model – but some of these optimizations feel cleaner and less bloated. Any thoughts @WellingGuzman ? If we were to change the schema this drastically I would want to do it before any announced release.

* **`directus_bookmarks`** Should this become a JSON string saved within `directus_users->bookmarks`?
* **`directus_ip_whitelist`** Should this become a JSON string (ip, description) saved within `directus_groups->ip_whitelist`?
* **`directus_settings` and `directus_storage_adapters`** Would there be any advantage to the following tables being combined into a JSON string?
* **`directus_social_feeds` and `directus_social_posts`** Are these actually used by core directus or are those utility tables?
* **`directus_tab_privileges`** Should this become a JSON string saved within `directus_groups->default_nav_blacklist`?
* **`directus_ui`** Should this table be turned into a JSON string within `directus_columns->ui-options`? Probably not... since currently it saves/remembers the settings from previously set UIs.

**Comment by benhaynes** [comment]
I wonder about the **`directus_storage_adapters`** table too... when deploying a site to production or updating all data in the database this table is always excluded since it's tied to the server directories. Should this storage adapter data move to the untracked config/configuration file? The only downside is that that directus_files references the storage adapter in the DB.

Thoughts @WellingGuzman ?

**Comment by WellingGuzman** [comment]
@benhaynes about `directus_storage_adapters` this is a little bit extra code, but we can create a php code that runs after we git push to production, and there we can update table with default values or something else.

But first, when you deploy to production how do the files and directories are pushed to the production server? via git or ftp or something else?

I'm still reading more about this so I could give some ideas about the table to JSON subject.

**Comment by benhaynes** [comment]
Just another note to change "snapshots" to "bookmarks" throughout the system. Snapshots seems to imply that the data within won't change... in reality these are simply bookmarks to specific filtered pages.

**Comment by benhaynes** [comment]
**[Migrated to FeatHub](http://feathub.com/directus/directus/+39)**

Please use the [Directus FeatHub](http://feathub.com/directus/directus) to vote for features or make new request. Accepted feature requests will be added to GitHub Issues.
