### ISSUE TITLE
rc.75 Interfaces are not loading 

### ISSUE THREAD

**Issue by bernzJ** [directus/directus#6230]
The request seems to hit but nothing is loaded on the app. I tried fresh install with vue 2 and with the latest single file vue compiler. The rollup config and vue component are the same as in the docs.

My package:
```json
{
  "name": "super-cool-stuff",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "build": "npx rollup -c"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^19.0.0",
    "@rollup/plugin-node-resolve": "^13.0.0",
    "@vue/compiler-sfc": "^3.1.1",
    "rollup": "^2.51.2",
    "rollup-plugin-terser": "^7.0.2",
    "rollup-plugin-vue": "^6.0.0"
  },
  "dependencies": {
    "vue": "^3.1.1"
  }
}
```

**Comment by nickrum** [comment]
This is related to the Vue 2 to Vue 3 switch. You can take a look at the updated build config in #6232.
