### ISSUE TITLE
DB_SSL environment variable breaks when set to false

### ISSUE THREAD

**Issue by Illubyte** [directus/directus#6231]
I just updated from rc 69 to rc 75, so I'm not exactly sure at which release this issue was introduced. 

When working with a database that is not SSL enabled (my local test database doesn't utilize SSL), setting `DB_SSL="false"` in the environment variables returns the following error when attempting to start the server.  
```
Error: The server does not support SSL connections
    at Socket.<anonymous> ([...]/node_modules/pg/lib/connection.js:71:37)
    ...
```
Curiously, when I delete the `DB_SSL="false"` line from my env, the server starts up just fine.

I checked to see if it was just an issue with my project by creating a new database and generating a new Directus project from scratch using the `npx create-directus-project my-project` CLI tool, and found the same result. 

Notes:
I am utilizing a PostgreSQL database. 
When you select 'no' for database SSL in the CLI, it automatically adds `DB_SSL="false"` to the generated env file.

**Comment by paescuj** [comment]
This has been fixed in #6190 and should work again once v9.0.0-rc.76 is released.

**Comment by Illubyte** [comment]
Oh, I see. I apologize for the duplicate. Looked around a bit, but somehow never found #6189. Thank you very much for the information!

**Comment by paescuj** [comment]
No problem! You're welcome!
