### ISSUE TITLE
rc.75 - [UNKNOWN] T.refresh is not a function dialog at item deletion & archiving

### ISSUE THREAD

**Issue by domdus** [directus/directus#6249]
`{
  "stack": "TypeError: T.refresh is not a function\n    at batchDelete (https://<domain>/admin/assets/index.ff2ee405.js:1:118144)",
  "message": "T.refresh is not a function"
}`

- Message appears only on list view (collection) -> select 1-n items with check mark
- Actual deletion or archiving is still processed no matter the message

1.  Select item(s) from list (collection view)
2.  Click delete/archive
3.  Confirm the "Are you sure..."-dialog, notice it does not disappear
4.  Click "Cancel" to see the error message dialog

---

### Project details
Directus Version: 9.0.0-rc.75
Environment: false
OS: Linux 4.19.0-16-amd64
Node: 14.15.4

**Comment by dnndev** [comment]
I am also receiving this message after upgrading to RC75. The delete occurs, but the UI does not update.
