### ISSUE TITLE
Web UI not displaying related items in item view

### ISSUE THREAD

**Issue by bastianhjaeger** [directus/directus#6251]
Hello

we are running directus in a docker-compose setup. Working great so far. :heavy_check_mark:
These are the containers we apply:

```
docker container
	directus:
		directus/directus:v9.0.0-rc.75
	database:
		postgres:12
	cache:
		redis:6
```
We have a collection of project. Each project has 
- m2m connection for `related_users`
- m2m connection for `related_sensors`
- o2m connection for `active_sensors`

In the collection overview of "projects" we see this
![Screenshot from 2021-06-14 13-01-14](https://user-images.githubusercontent.com/26868917/121884062-c6012000-cd12-11eb-9e79-f21776309f03.png)
(You see a project with 4 related and active sensors and 3 related users)

But clicking on the projects shows (in 19 or 20 cases more or less) this:
![Screenshot from 2021-06-14 13-01-47](https://user-images.githubusercontent.com/26868917/121884077-ca2d3d80-cd12-11eb-9ae0-3e6fddb65d9a.png)
(No items shown for `related_sensors` or `related_users`). On loading it looks like a list is present for a millisecond, but it disappears. Only in a few rare cases the list is displayed.

In addition this messages pops up on loading the project sometimes (also in around 5% of the cases): 
![Screenshot from 2021-06-14 13-10-44](https://user-images.githubusercontent.com/26868917/121884084-cc8f9780-cd12-11eb-9240-2e324661f8c9.png)

Tested with 
- Firefox 89.0 (64-bit) on Ubuntu 20.04 
- Chrome Version 90.0.4430.212 (Official Build) (64-bit) on Ubuntu 20.04

**Comment by benhaynes** [comment]
Could this difference between listing/detail be because of that caching issue we were seeing, @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
@benhaynes No, that doesn't apply to self-hosted instances

**Comment by bastianhjaeger** [comment]
Happy to see your fast reactions.
I would have a look to it too, but unfortunately that stuff is not my wheelhouse. 

Lokking forward for an analysis or fix.

**Comment by rijkvanzanten** [comment]
I think this might've been a side-effect of https://github.com/directus/directus/issues/6189 which was fixed and released in 76. Could you try it out and let me know @bastianhjaeger? 🙂

**Comment by bastianhjaeger** [comment]
Yes. Thanks. That resolved it.

Side questions (because I crashed my database in between):
- what is the recommended way (preferably for the docker-compose setup) to make a backup/snapshot from the directus databases (in total)?
- are there safety mechanism in place to not corrupt data when switching directus versions (because I also have issues when updating from rc64 to rc75)?

**Comment by rijkvanzanten** [comment]
> what is the recommended way (preferably for the docker-compose setup) to make a backup/snapshot from the directus databases (in total)?

That's up to you! Depends on what database you're using, and how you'd like your database to be stored. For postgres, a simple `pg_dump` would be enough.

> are there safety mechanism in place to not corrupt data when switching directus versions

Directus ships with migrations for any changes that need to be applied between versions for Directus to work, if that's what you're asking about
