### ISSUE TITLE
Admin assets not all served from specified PUBLIC_URL path

### ISSUE THREAD

**Issue by Alluuu** [directus/directus#6276]
**The issue and what you expected to happen**
I expect to be able to use the API deployed to be reachable from a subdirectory of a domain, while accessing through NGINX proxy that rewrites and passes the queries to the node service.

Some assets are loaded from the specified subdirectory by PUBLIC_URL env variable.

**Didn't load correctly:**
 - logo-light.1a93a59d.svg
 - - http://192.168.99.100/admin/assets/logo-light.1a93a59d.svg
 - Inter-Bold.f0f54a06.woff2
 - - http://192.168.99.100/admin/assets/Inter-Bold.f0f54a06.woff2
 - Inter-Medium.a4e1e7e6.woff2
 - - http://192.168.99.100/admin/assets/Inter-Medium.a4e1e7e6.woff2
 - Inter-Black.5ab3de07.woff2
 - - http://192.168.99.100/admin/assets/Inter-Black.5ab3de07.woff2
 - Inter-SemiBold.af44b8a2.woff2
 - - http://192.168.99.100/admin/assets/Inter-SemiBold.af44b8a2.woff2
 - material-icons-outline.28c199c2.woff2
 - - http://192.168.99.100/admin/assets/material-icons-outline.28c199c2.woff2
 - Inter-Black.f11705b0.woff
 - - http://192.168.99.100/admin/assets/Inter-Black.f11705b0.woff
 - Inter-SemiBold.3041a990.woff
 - - http://192.168.99.100/admin/assets/Inter-SemiBold.3041a990.woff
 - Inter-Bold.cd06b48a.woff
 - - http://192.168.99.100/admin/assets/Inter-Bold.cd06b48a.woff
 - Inter-Medium.f500bbb9.woff
 - - http://192.168.99.100/admin/assets/Inter-Medium.f500bbb9.woff

**loaded correctly:**
 - login
 - - http://192.168.99.100/subdirectory/admin/login
 - vendor.d2724e38.js
 - - http://192.168.99.100/subdirectory/admin/assets/vendor.d2724e38.js
 - index.ff2ee405.js
 - - http://192.168.99.100/subdirectory/admin/assets/index.ff2ee405.js
 - vendor.90828bcd.css
 - - http://192.168.99.100/subdirectory/admin/assets/vendor.90828bcd.css
 - index.9d26c130.css
 - - http://192.168.99.100/subdirectory/admin/assets/index.9d26c130.css
 - interfaces/
 - - http://192.168.99.100/subdirectory/extensions/interfaces/
 - displays/
 - - http://192.168.99.100/subdirectory/extensions/displays/
 - layouts/
 - - http://192.168.99.100/subdirectory/extensions/layouts/
 - modules/
 - - http://192.168.99.100/subdirectory/extensions/modules/
 - refresh
 - - http://192.168.99.100/subdirectory/auth/refresh
 - android-chrome-192x192.png
 - - http://192.168.99.100/subdirectory/admin/img/icons/android-chrome-192x192.png
 - info?limit=1
 - - http://192.168.99.100/subdirectory/server/info?limit=-1
 - oauth/
 - - http://192.168.99.100/subdirectory/auth/oauth/
 - safari-pinned-tab.svg
 - - http://192.168.99.100/subdirectory/admin/img/icons/safari-pinned-tab.svg
 
 So, essentially fonts and one logo.
 But where it get's more messy is when attempting a login where
  - http://192.168.99.100/admin/assets/index.41d00480.js
  - http://192.168.99.100/admin/assets/index.baa03203.css
  - http://192.168.99.100/admin/assets/vendor.d2724e38.js
  - http://192.168.99.100/admin/assets/vendor.90828bcd.css
 
are loaded incorrectly and never received and hence the admin pages are not displayed.

Since all API routes work properly and some assets are loaded with correct subdirectory paths I can assume the NGINX routing and the PUBLIC_URL in Directus conf work properly, but some assets do not follow the protocol of appending the PUBLIC_URL.

**Exact steps to reproduce this issue**
Set up a directus api with nginx to be reached from any subdirectory and access /subdirectory/admin pages.

**Your environment:**
What version of Directus you are using. **9.x latest**
Which DBMS are you using (MySQL 8, Postgres 12, ...). **SQLite**
Which deployment are you using (npx, Docker, ...). **Self built Docker container**
What browser are you using (Chrome 87, Safari 14, ...). **Chrome 90**

**Comment by HitomiTenshi** [comment]
You are not using the latest directus version. You are using version `9.0.0-rc.75` which has this bug, I can confirm that `9.0.0-rc.76` has fixed this issue.

All admin pages on our side work with `rc.76` under a sub-directory.

**Comment by Alluuu** [comment]
@HitomiTenshi You're very correct! I hadn't noticed that another version had released and this issue is surely not existing on rc.76. Thank You for pointing this out!
