### ISSUE TITLE
inserting a record returns the wrong record in the response when the pk is generated outside directus

### ISSUE THREAD

**Issue by wc-matteo** [directus/directus#6279]
this happens with a guid as primary key. I noticed the record returned is the first record ordering by primary key desc. I stumbled upon this bug in the panel by using ctrl+s to save and the interface updated with an unrelated record but it happens with the api as well.

Is the record returned after inserting obtained with something like "top 1 order by primary key desc"?

---
```
mssql 2016 / v9.0.0-rc.75
```

**Comment by rijkvanzanten** [comment]
If the primary key exists in the payload—as is the case when you use Directus' UUID type—it will use that to retrieve the item. If that's not the case, it falls-back to exactly what you said.

Are you generating this UUID outside of Directus?

**Comment by rijkvanzanten** [comment]
This is a tricky situation, as not all databases support "returning" statements on inserts 🤔 

I think the next-best-thing is to try using returning for DBs that support it, before falling back to the auto-int primary retrieval

**Comment by wc-matteo** [comment]
> Are you generating this UUID outside of Directus?

yes, the pk has as default value `newid()`

**Comment by wc-matteo** [comment]
> it falls-back to exactly what you said
this issue with this is that it can be really unreliable. Not only for this case in particular but also with concurrent inserts...

**Comment by wc-matteo** [comment]
maybe it should be a requirement that the pk be _always_ generated by directus otherwise directus should use (vendor) specific sql (e.g. sql server: https://stackoverflow.com/a/7917874/6291804) to return the pk for the insert

**Comment by Oreilles** [comment]
If that may help, taken from `knex` documentation:

> For MSSQL, triggers on tables can interrupt returning a valid value from the standard DML statements. You can add the includeTriggerModifications option to get around this issue. This modifies the SQL so the proper values can be returned. This only modifies the statement if you are using MSSQL, a returning value is specified, and the includeTriggerModifications option is set.
```js
// Adding the option includeTriggerModifications allows you 
// to run statements on tables that contain triggers. Only affects MSSQL.
knex('books')
  .returning(['id','title'], { includeTriggerModifications: true })
  .insert({title: 'Slaughterhouse Five'})
```

**Comment by wc-matteo** [comment]
just to confirm: this bug applies also to identity columns, right? Since the pk value is generated by sql, directus returns the "top 1 order by primary key desc" in that case as well?

**Comment by rijkvanzanten** [comment]
yup!

**Comment by ravolta-io** [comment]
Any updates or workarounds on this?
