### ISSUE TITLE
Calendar is not in the user's language - just english

### ISSUE THREAD

**Issue by hermesalvesbr** [directus/directus#6290]
1) The issue and what you expected to happen
    The show me in English, while it should  in Portuguese language.
3) Your environment:
    Directus rc.76
    Postgres 12
    Docker
    Chrome

![Captura de Tela 2021-06-15 às 16 46 41](https://user-images.githubusercontent.com/379850/122114813-1c955980-cdfa-11eb-9623-5af214f07868.png)

Since the rc.73 version I went to https://locales.directus.io/ and helped to translate the calendar to Portuguese, but it's still showing in English.

![Captura de Tela 2021-06-15 às 16 49 38](https://user-images.githubusercontent.com/379850/122114924-3df64580-cdfa-11eb-90f9-7af2f6ccb30d.png)

Please let me know if I need to contribute anywhere else so that the calendar stays in my language.

**Comment by rijkvanzanten** [comment]
We'll have to tap into Fullcalendar's translation configuration in order to sync that with Directus' language 👍🏻
