### ISSUE TITLE
Fetch preview values based on selection on new items too

### ISSUE THREAD

**Issue by benosman** [directus/directus#6293]
This is a difficult one to explain, but the issue is that the One to Many interface can't access nested field values immediately after the 'Create New' operation, but does work after a save/reload cycle.

![image](https://user-images.githubusercontent.com/305317/122117512-db637080-ce1e-11eb-98c0-3046546ce913.png)

### Steps to Reproduce

1. Create a collection called Category, with a title field
2. Create a collection called Article with a title field
3. Create an intermediate collection very similar to the one used on many to many fields between Category and Article. The only difference is that category_id is not hidden, and there is an additional boolean field called featured.
![image](https://user-images.githubusercontent.com/305317/122118176-a86dac80-ce1f-11eb-8db6-25f22f1822fc.png)
4. Create the one to many field on the Article with a relationship set up to the intermediate article_category collection.
![image](https://user-images.githubusercontent.com/305317/122118430-e9fe5780-ce1f-11eb-9778-5c888d57ed65.png)
5. Set the Display template to access the nested title of the Category Id field.
![image](https://user-images.githubusercontent.com/305317/122118630-27fb7b80-ce20-11eb-9a76-05585589f656.png)
6. Prepopulate some Category items
7. Create new Article, use Create New button to add a new article_category item and assign the Category id to one of the existing items. Save to return back to the top level form. 

### What happens
The One to many interface shows blank values in place of the category_id.name field that should be shown.

If you save the Article record and reload, the label shows correctly.

### Notes

Apologies for the image heavy post, but I wanted to show the steps. The reason for using this setup instead of the regular many-to-many interface (using junction field) is that I wanted the additional boolean field to be present on the form when adding a category.

---

### Project details
Directus Version: 9.0.0-rc.76
Environment: false
OS: macOS Catalina (10.15)
Node: 16.3.0

**Comment by rijkvanzanten** [comment]
This actually makes total sense from a technical perspective. By selecting an existing value, the app stages the primary key of the related item (not the full nested object). This combined with the fact that the app can't fetch the existing values for this item (as it's added new) means that it can't display that nested value 🤔 

For what it's worth, this:

> The reason for using this setup instead of the regular many-to-many interface (using junction field) is that I wanted the additional boolean field to be present on the form when adding a category.

can be done with a regular M2M as well :) If you add custom columns to the junction table, they'll show up when editing the row on the many to many interface 👎🏻

**Comment by rijkvanzanten** [comment]
I'll have to look into if this is something we can / want to fix. The only way I can think of in which this would work is if the app scans through the nested tree of the newly created item to see if any existing items where selected, and then fetches and injects previews for just those, without touching the parent item that was newly created 🤔

**Comment by benosman** [comment]
I do appreciate the quick reply with suggestions, and background info.


> This actually makes total sense from a technical perspective. By selecting an existing value, the app stages the primary key of the related item (not the full nested object). This combined with the fact that the app can't fetch the existing values for this item (as it's added new) means that it can't display that nested value 🤔
> 

Understood, partially at least from working with this kind of structure in different systems. I realise that this is a tricky and niche issue. A random thought, without knowing all the details - could it be detected if it is a new item added and at least display some text to indicate that so it's not just empty.

> For what it's worth, this can be done with a regular M2M as well :) If you add custom columns to the junction table, they'll show up when editing the row on the many to many interface 👍🏻

When setting up this to make sure it was reproducible I did notice that actually. The UX isn't quite the way I would want, as in it is only when you go back and edit rather than on addition, but I could put up with that for now, if it wasn't that the real referenced entity has loads of fields (an inherited project) and so the new field(s) would likely be buried under a long scroll.

I will discuss with the client though and see which is preferred for now.

**Comment by benhaynes** [comment]
Definitely agree that we should at _least_ mark the item as new so it doesn't seem broken (ideally we can get the data pulled in). We are also working on _styling_ list items based on if they are new or edited.

Interesting, so the M2M doesn't show the junction fields on create... only on edit? If that's the case, we should open a separate issue to track that.

**Comment by benosman** [comment]
> Interesting, so the M2M doesn't show the junction fields on create... only on edit? If that's the case, we should open a separate issue to track that.

I went back to check, but with M2M and O2M the terminology is different - in M2M creation refers to adding the related item, whereas in O2M it refers to adding the junction/intermediate record, so my explanation wasn't accurate.

###M2M
*Create New* - Shows the creation form for related type (e.g. Category) and the junction fields _are_ shown. (junction record is added implicitly)
*Add Existing* - Select from an existing related type item from the layout list - no mechanism to set the junction field until after it is set, and you go back and edit.

###O2M
*Create New* - Shows creation form for intermediate type, with interfaces to select or insert a final related item along with the junction field.
*Add Existing* - not very useful here, at least for my setup.

**Comment by rijkvanzanten** [comment]
> Add Existing - Select from an existing related type item from the layout list - no mechanism to set the junction field until after the relation is set, and you go back and edit. (junction record is again added implicitly)

Interesting point! When adding an "existing" item, you're still creating a new junction row under the hood. @benhaynes would it be worth exploring a direction where "select existing" on a many to many context is closer to a "create junction + select related"? This would obv only be applicable in cases where you have custom fields on the junction table itself

**Comment by joselcvarela** [comment]
Hello @benosman 
This seems to be fixed in the meantime. Here's the actual behaviour:

https://user-images.githubusercontent.com/14039341/147480095-b3c40322-4f2d-4cb3-972f-26d4ac00d40f.mov

___
> If you think this is not solved yet, feel free to reach us in order to reopen.
