### ISSUE TITLE
Folder foreign key constraint fails

### ISSUE THREAD

**Issue by aidenfoxx** [directus/directus#6310]
When uploading a file, the foreign key constraint fails on the folder field, due to the input value being string `'null'` rather than `null`. This prevents files from being uploaded to the base folder.

 I've tracked this down to the following code:

https://github.com/directus/directus/blob/main/api/src/controllers/files.ts#L39

Busyboy pulls the `folder` value as a string null from the form data.

Env:
- Directus rc76
- OracleDB
- Firefox

**Comment by rijkvanzanten** [comment]
> When uploading a file

This on the file detail page specifically?

**Comment by rijkvanzanten** [comment]
@nickrum Could this be from the updated logic that sets the current folder from the routing on the Vue 3 change?

**Comment by aidenfoxx** [comment]
@rijkvanzanten Not sure what you mean by file details page? Starting from the "File Landing" page I just select "Create Item" and select a file to upload. The upload request will then fail with a foreign key constraint failure error.

**Comment by rijkvanzanten** [comment]
That's exactly where I was talking about 😉 

I was wondering if this was an upload in the "Files" module, or from an interface, or any other api endpoint or 🤷🏻

**Comment by nickrum** [comment]
@rijkvanzanten Could be, yes! I had to switch from using a `preset` prop with type object to a `folder` prop with type string and a default value of `null` on the `AddNew` component.

I can't reproduce this on my end, though.

**Comment by aidenfoxx** [comment]
Just set up a fresh install against MySQL which is failing in the same way.

![image](https://user-images.githubusercontent.com/5548518/122245439-0228b200-cec6-11eb-8a8c-ac176df0b023.png)

**Comment by Intevel** [comment]
I actually have the same error, when using SQLite and trying to import a folder/files
