### ISSUE TITLE
Cannot create a new item with ItemService.createOne (or even ItemService.create)

### ISSUE THREAD

**Issue by gustavodipietrogva** [directus/directus#6315]
Hi,
I'm trying to create a new item in a collection that has a `user_created` field as a foreign key to `directus_users` and is set as "special `user-created`".

The collection has been created with the following migration:

```js
const shortlistTable = 'shortlists'; 
const directusUsersCollectionName = 'directus_users';
 
module.exports = {
  async up(knex) {
    // Create the property collection table and its Directus collection row
    await knex.schema.createTable(shortlistTable, (table) => {
      table.increments('id').primary();
      table.string('name', 255).notNullable();
      table.uuid('user_created').notNullable();
 
      table.foreign('user_created').references('id').inTable(directusUsersCollectionName);
    });
 
    await knex('directus_collections').insert({
      collection: shortlistTable,
    });
 
    // Create a many to many relationship between the shortlists and users
    await knex('directus_relations').insert([
      {
        many_collection: shortlistTable,
        many_field: 'user_created',
        many_primary: 'id',
        one_collection: directusUsersCollectionName,
        one_primary: 'id',
      },
    ]);
 
    // Setup the Directus interface fields
    await knex('directus_fields').insert([
      {
        collection: shortlistTable,
        field: 'user_created',
        interface: 'select-dropdown-m2o',
        options: '{"template": "{{first_name}} {{last_name}}"}',
        display: 'related-values',
        display_options: '{"template": "{{first_name}} {{last_name}}"}',
        sort: 2,
        special: 'user-created',
      },
    ]);
  },
 
  async down(knex) {
    ...
  },
};
```

When working on the collection via the REST api I can easily create new items and Directus correctly auto-populates the `user_created` field. With the SDK, however, I'm always getting the following error:

```json

{
    "errors": [
        {
            "message": "Value for field \"user_created\" can't be null.",
            "extensions": {
                "code": "NOT_NULL_VIOLATION",
                "collection": "shortlists",
                "field": "user_created",
                "stack": "Error: Value for field \"user_created\" can't be null.\n    at notNullViolation (C:\\Users\\galfarano\\GVARepos\\datahub\\node_modules\\directus\\dist\\exceptions\\database\\dialects\\mysql.js:100:12)\n    at Object.extractError (C:\\Users\\galfarano\\GVARepos\\datahub\\node_modules\\directus\\dist\\exceptions\\database\\dialects\\mysql.js:29:20)\n    at Object.translateDatabaseError (C:\\Users\\galfarano\\GVARepos\\datahub\\node_modules\\directus\\dist\\exceptions\\database\\translate.js:25:28)\n    at C:\\Users\\galfarano\\GVARepos\\datahub\\node_modules\\directus\\dist\\services\\items.js:106:41\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
            }
        }
    ]
}
```

What I'm trying is:

```js
     const user = await usersService.readOne(accountability.user);
     const shortlistService = new ItemsService('next_shortlists', { schema });

     const shortList = await shortlistService.createOne({
        name: 'TEST',
        //user_created: user.id,
        //user_created: user,
      });
```

What I expect is the I do not need to pass `user_created` at all (consistently with the REST Api behavior). However, even passing the whole user object, or forcing the id, I'm still getting the very same error and in the end I'm not able to insert new items via SDK in any way.

Stepping into Directus code, it seems that a certain point within `services/items.js/createOne()` `user_created` is set to `null` for whatever reasons and it breaks from there.

Any help? Thanks

**Comment by rijkvanzanten** [comment]
Here:

```js
     const shortlistService = new ItemsService('next_shortlists', { schema });
```

you're creating a service for a collection called `next_shortlists`, however, in your first migration example, the table you're creating is called `shortlists`, not `next_shortlists`. Are you sure you're operating on the correct collections? For what it's worth, the REST API directly passes the payload to the same method:

https://github.com/directus/directus/blob/fb715cc66a2013474968bf079bf402d464b5e55b/api/src/controllers/items.ts#L33

so the logic should be the same 🙂 

> Stepping into Directus code, it seems that a certain point within services/items.js/createOne() user_created is set to null for whatever reasons and it breaks from there.

Where exactly? I don't see any reference to `user_created` under services/items

**Comment by gustavodipietrogva** [comment]
@rijkvanzanten  Sorry again, I don't see why this has been closed since I'm still not able to create the object and the code nullifying fields and then complaining about them being null is not something I'd expect. Thanks

**Comment by rijkvanzanten** [comment]
> I don't see why this has been closed

Closed it, as your original example was wrong, but that turned out to be a typo 🙂 

I only go over my notifications a couple times a day, so won't re-open _immediately_ on every comment 👍🏻

**Comment by rijkvanzanten** [comment]
Also, a lot has changed since `rc.69`. Could you update to the latest version and confirm it's still a problem, before we end up chasing a ghost?
