### ISSUE TITLE
One 2 Many

### ISSUE THREAD

**Issue by sebastianjooo** [directus/directus#6316]
There are 2 Tables, boat and color. I wanna create an o2m relation between boat and color.  
After selecting the related collection, it is not possible to select the foreign key, or it is possible but not allowed.
![image](https://user-images.githubusercontent.com/9371171/122232308-6db95200-cebb-11eb-8f2c-58affd1e89e1.png)
![image](https://user-images.githubusercontent.com/9371171/122232630-abb67600-cebb-11eb-8b1a-90e2e77f32eb.png)
![image](https://user-images.githubusercontent.com/9371171/122232688-b96bfb80-cebb-11eb-8917-24aae389e786.png)
After the changes are applied, this error appears
![image](https://user-images.githubusercontent.com/9371171/122232775-c7ba1780-cebb-11eb-90cc-fb8225547975.png)
{
  "errors": [
    {
      "message": "alter table `color` add constraint `color_id_foreign` foreign key (`id`) references `boat` (`id`) on delete SET NULL - ER_CANT_CREATE_TABLE: Can't create table `$HOSTNAME$`.`color` (errno: 150 \"Foreign key constraint is incorrectly formed\")",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
---

### Project details
Directus Version: 9.0.0-rc.76
Environment: false
OS: Linux 5.4.0-73-generic
Node: 14.17.0
DB: mysql

**Comment by benhaynes** [comment]
Are the key fields using the exact same type? eg: autoincrement integer

**Comment by sebastianjooo** [comment]
yes

**Comment by rijkvanzanten** [comment]
You can't select any field in the dropdown, as you don't have any fields on `color` that can hold the primary key of `boat`.

This is an illegal relationship:

![](https://user-images.githubusercontent.com/9371171/122232688-b96bfb80-cebb-11eb-8917-24aae389e786.png)

as you're trying to save the primary key of `boat` in the primary key field of `color`.

Try entering `boat_id` under the foreign key field of `color`. That will tell Directus to create a new field automatically 👍🏻

**Comment by rijkvanzanten** [comment]
(PS, watch the markdown syntax of the issues, little hard to read like this 😅 )

**Comment by sebastianjooo** [comment]
Ah okay , sorry . I just pasted it in 😅. 
thank you for ur answer . 
I didn’t expect that this should be the container of the fk .
