### ISSUE TITLE
Add/Edit collection throws error after adding Translations relation (Postgres)

### ISSUE THREAD

**Issue by bilalajanjua** [directus/directus#6370]
Hi,

I created a collection named homepage and added translations to it. When I edit the content for the homepage, the console logs the following error and don't show anything in translation drawer:

`error select "homepage_translations"."id", "homepage_translations"."languages_code" from "homepage_translations" where "homepage_translations"."homepage_id" = $1 order by "homepage_translations"."id" asc limit $2 - invalid input syntax for type integer: "+"` 

I am using Postgresql 13. I already tried updating the integer datatype of id to UUID but the error is still the same. I don't get from where it is passing "+" to the query above.

---

### Project details
Directus Version: 9.0.0-rc.76
Environment: false
OS: Windows_NT 10.0.19041
Node: 12.16.3

**Comment by haidv1992** [comment]
still error 500 in O2M tree view

 error select "menu"."name", "menu"."switch_link", "menu"."new_tab", "menu"."id", "menu"."parent_menu", "menu"."page" from "menu" where ("menu"."id" not in ($1) and "menu"."parent_menu" is null) order by "menu"."id" asc limit $2 - invalid input syntax for type integer: "+"

**Comment by haidv1992** [comment]
![image](https://user-images.githubusercontent.com/86423592/132839270-d2d93232-7942-4645-9fef-910d9a4b402d.png)

**Comment by rijkvanzanten** [comment]
@haidv1992 sounds like a similar but unrelated problem. Mind opening a new issue?

**Comment by sarente** [comment]
Hi,

I could not use becouse of this error. How can I solve and use Directus?

{
  "errors": [
    {
      "message": "select \"companies_translations\".\"id\", \"companies_translations\".\"companies_id\", \"companies_translations\".\"languages_code\" from \"companies_translations\" where \"companies_translations\".\"companies_id\" = $1 order by \"companies_translations\".\"id\" asc - invalid input syntax for type uuid: \"+\"",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

Best,
Usame

**Comment by joselcvarela** [comment]
@sarente What version are you using?
Seem like is the same issue as the OP, but this should have been fixes on rc.79 (https://github.com/directus/directus/pull/6453)

**Comment by sarente** [comment]
My package.json is like below,

`{
  "name": "directus-playground",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "directus": "^9.0.0-rc.93",
    "pg": "^8.7.1"
  }
}
`

Best
