### ISSUE TITLE
Public file permissions lead to GraphQL error

### ISSUE THREAD

**Issue by nilsmich** [directus/directus#6396]
Hello, 
I have a collection that has public read access (set in /admin/settings/roles/public). This collection contains a few fields. One is used for images (created as a single file type). This is its configuration.
Everything works when fetching the data via GraphQL. I receive the data including the key for the image. 
As expected it is not publically accessible when entering https://backend.com/assets/209c62d9-6058-4a3c-a3e6-c2c201bbe1be.

I then changed the permission for Directus Files to read for public users. https://backend.com/assets/209c62d9-6058-4a3c-a3e6-c2c201bbe1be works now. 
However, the original GraphQL Query throws an error saying that string is not the right format for the image field. 

The resolution was to remove the image field from the Data Model and recreate it AFTER changing the permission. Was no problem for me as I had test data only for now. But maybe nice if this was not required ;). 

It seems as if the schema changed in both cases. In the first case, I received a string. In the second I had to use 
image_field{
  id
}

IMHO it would be good to keep the schema consistent for images. 

Thank you for the great work. Really joyful to use Directus :). 

---

### Project details
Directus Version: 9.0.0-rc.71
Environment: production
OS: Linux 4.4.0-1093-aws
Node: 14.17.0

**Comment by rijkvanzanten** [comment]
> It seems as if the schema changed in both cases. In the first case, I received a string. In the second I had to use

```graphql
image_field{
  id
}
```

This is correct, before you could only read the value stored on the actual column, afterwards you have access to the actual nested relational data.

> IMHO it would be good to keep the schema consistent for images.

I wish we could! GraphQL doesn't allow for multiple types on the root key (eg `image` as a string or a nested image object), so this is the best we can do within the constraints of the gql spec 👍🏻
