### ISSUE TITLE
Save operation on many-to-many will cause its title disappear

### ISSUE THREAD

**Issue by jianliao** [directus/directus#6407]
1) The save operation on many-to-one will cause the item title disappear while it should show title as before
2) Steps to reproduce:
![Jun-21-2021 11-17-21](https://user-images.githubusercontent.com/1207520/122808976-5e9f1f00-d282-11eb-99bc-625cc8ec6aca.gif)
3) version: rc.76

**Comment by rijkvanzanten** [comment]
Would you be able to share some more specifics on the setup of this interface? I just tried it out with a new instance and can't seem to reproduce it 🤔 

https://user-images.githubusercontent.com/9141017/123008864-aeb4d900-d389-11eb-9d4a-ea9451eb5e3b.mp4

**Comment by jianliao** [comment]
Hi @rijkvanzanten ,
Sorry I just checked the relation, it is a many-to-many.
![image](https://user-images.githubusercontent.com/1207520/123009549-c2544580-d371-11eb-9a66-9bbabe7e8fe4.png)

**Comment by rijkvanzanten** [comment]
Ah! Yes I see it now, thanks!

**Comment by jianliao** [comment]
Thanks @rijkvanzanten
