### ISSUE TITLE
In tabular layout, pagination is diplayed if limit is less than itemCount (and less than 25)

### ISSUE THREAD

**Issue by phampphi** [directus/directus#6418]
1) While using tabular layout, the limit value in layoutQuery props is default to 25 and pagination will be displayed if the number of items is greater than 25.
However if limit is less than 25, it is not taken into account in pagination logic.

2) Step to reproduce
- Passing limit props into tabular layout through layout query props: {"fields":["field1", "field2", "field3"], limit: 10}
- The number of items is larger than limit value (there are 20 items)
- The tabular layout display correctly only 10 items
- However, the pagination is displayed with 2 pages and it is impossible to navigate to next pages (page 2)
 
It is expected that the pagination should not be displayed.

3) Root cause
In src/composables/use-items/use-items.ts, limit value is not taken into account when getting item count

```js
async function getItemCount() {
		if (!primaryKeyField.value || !endpoint.value) return;

		const response = await api.get(endpoint.value, {
			params: {
				limit: 0,
				fields: primaryKeyField.value.field,
				meta: ['filter_count', 'total_count'],
				search: searchQuery.value,
				...filtersToQuery(filters.value),
			},
		});

		totalCount.value = response.data.meta.total_count;
		itemCount.value = response.data.meta.filter_count;
	}
```

While limit (<25) is used to get the items, this causes itemCount to be greater than limit, hence results in totalPages > 1; therefore the pagination is displayed.

4) Directus 9.0.0-rc.78

**Comment by rijkvanzanten** [comment]
> Passing limit props into tabular layout through layout query props

Where / how are you doing this?

**Comment by phampphi** [comment]
I'm building a custom interface which uses the Tabular layout.
The Tabular layout is used by creating a Vue dynamic component and the limit is passed through layoutQuery prop.
`<component
        is="layout-tabular"
        :collection="collection"
        :layoutQuery="layoutQuery"
        :filters="filters"
        selectMode="multiple"
      >`

**Comment by rijkvanzanten** [comment]
I can't really comment on how this is supposed to work with non-standard values, as the layout is made with it's default limit options in mind 🤔 (so its technically working as expected)

(In general, the internal APIs of the components are subject to change, especially during the RC phase.)
