### ISSUE TITLE
directus change type of filed

### ISSUE THREAD

**Issue by 3DIQE** [directus/directus#6419]
The problem does happen when i created filed with UUID type and i expected it would be save the same type but when i checked ,it was different and directus change to string while it should be as UUID
another problem is when i  want to have foriegn key for one to many relation it doesn't show any filed between my tables.
id of any table is as UUID.
for more explain i set my problem as pic:
![image](https://user-images.githubusercontent.com/82942259/122892325-23d8cd80-d2fa-11eb-83ae-89c9ddfa8ae8.png)
![image](https://user-images.githubusercontent.com/82942259/122890024-2c300900-d2f8-11eb-97b3-29435db197dd.png)
![image](https://user-images.githubusercontent.com/82942259/122890103-3e11ac00-d2f8-11eb-83ad-3deda5a4832b.png)

---

### Project details
Directus Version: 9.0.0-rc.69
Environment: production
OS: Linux 4.9.0-11-amd64
Node: 12.4.0
USING:google chrome

**Comment by rijkvanzanten** [comment]
What database are you using?

**Comment by 3DIQE** [comment]
Mysql

**Comment by 3DIQE** [comment]
> What database are you using?

Mysql

**Comment by rijkvanzanten** [comment]
What version of MySQL? InnoDB or MariaDB?

**Comment by 3DIQE** [comment]
> What version of MySQL? InnoDB or MariaDB?

mysql  Ver 15.1 Distrib 10.3.29-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by rijkvanzanten** [comment]
Can you try updating to the latest version of Directus and see if you still run into the issue? I don't see it on rc80+

**Comment by Topfreelancerdeveloperr** [comment]
![uuid_problem](https://user-images.githubusercontent.com/67451110/124345397-cdb73480-dbed-11eb-8878-d16e916eb5b9.png)

Same problem here 
Directus Version: 9.0.0-rc.83
Doesn't let me choose id as foreign key when type is UUID in O2M relations.

**Comment by rijkvanzanten** [comment]
@Topfreelancerdeveloperr That's not the same problem. The reason you can't chose any existing field on the right is because you don't have a UUID field under `company` that can hold the primary key of bookmark. If you type in a new column name in that Foreign Key field, it will generate the column for you on the fly. (I'd recommend going with `bookmark_id` 👍🏻 )
