### ISSUE TITLE
Admin UI not unsetting cache after update

### ISSUE THREAD

**Issue by aidenfoxx** [directus/directus#6420]
After updating to rc78 I find Directus is not correctly unsetting cache after updating items. For example:

- Edit Directus user
- Change their name
- Save
- The update is not reflected in the UI
- Wait an undetermined period of time
- The update is reflected in the UI

This also affects collections we have defined.

This wasn't an issue previously. I assume it's caused by #6355, and Directus using `no-cache` inside the admin UI which wasn't updated?

Env:
- Firefox/Chrome
- OracleDB
- Directus rc78
- Redis Cache

**Comment by nachogarcia** [comment]
Isn't that behaviour handled by the `CACHE_AUTO_PURGE ` env variable? Or should the directus APP always jump cache?

**Comment by aidenfoxx** [comment]
@nachogarcia The admin app should always jump cache, otherwise you end up with a situation like I described where I update a users details, but the updated details don't show up until cache expires. You should immediately see changes you make in the admin.

I'd say `CACHE_AUTO_PURGE` should be for consuming GraphQL and REST calls.

**Comment by aidenfoxx** [comment]
For those that don't use `CACHE_AUTO_PURGE` we need some way to clear the cache admin side, since otherwise you end up with a situation like I described where we update a users details, but the updated details don't show up until cache expires.
 
I guess the nicer way to do things would be to have `CACHE_AUTO_PURGE` always enabled for the admin since that allows the admin to use caching, but doesn't cause the aforementioned issue.
