### ISSUE TITLE
Missing user's name on login screen when role permissions set to App Access Minimum

### ISSUE THREAD

**Issue by licitdev** [directus/directus#6475]
# Issue
Authenticated user's first and last name does not show up in `/admin/login` when the role is using **App Access Minimum** permissions. Only the user's `id` is returned through the `/users/me` endpoint.

<img width="382" alt="Screenshot 2021-06-24 at 2 07 34 PM" src="https://user-images.githubusercontent.com/26413686/123211094-8ba73800-d4f5-11eb-9a6a-0cc28ec41d81.png">

# Reproduction Steps
1. Create a new role, allow **App Access only**.
2. Open role permissions, set to **App Access Minimum**. 
3. Attach a user to this role
4. Authenticate as the user
5. Navigate to `/admin/login`

Note: When the role permission is set back to **Recommended Defaults**, the user's name can be retrieved via the `/users/me` endpoint.

# Project details

Directus Version: 9.0.0-rc.80
Environment: Production
OS: Ubuntu 20.04.2 LTS
Node: 16.4.0

**Comment by benhaynes** [comment]
I'm a bit confused why this is being reported, actually. Being able to login is the _minimum_ requirement, why is the name required?

**Comment by licitdev** [comment]
@benhaynes As shown in screenshot, an end user is unable to recognize which account is currently logged in by the name of Unknown User, as guided by the text.

The name of the logged in user can currently only be seen after clicking continue in the login screen and by clicking onto the profile icon. The two steps can be eliminated when the currently logged in name is shown.

**Comment by benhaynes** [comment]
Understood. I guess it's a pretty blurry line about what "required" is.
