### ISSUE TITLE
Can't save "0" as default value for integer type

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#6478]
It's probably thinking that's `false`

**Comment by supermx1** [comment]
Sorry, What Database and version of Directus does this affect?

**Comment by benhaynes** [comment]
Haha, calling me out! I like it. I am using using a dedicated Cloud instance, on PostgreSQL. In the App, I can save `NULL` (default), and 1+... but saving `0` resets to NULL.

**Comment by benhaynes** [comment]
No longer seeing this issue. It appears to have been resolved in a previous fix or indirectly via a knex update. Thanks @jaycammarano !
