### ISSUE TITLE
I can't create field of type "multiple files" 

### ISSUE THREAD

**Issue by bernatvadell** [directus/directus#6487]
Yep.

I am trying to create a new field of the type "multiple files" however I cannot continue with the wizard. 

The steps to reproduce it (in version v9.0.0-rc.80):
- Create a new data model
- Create a "multiple files" field

You shouldn't be able to finish the wizard 

![image](https://user-images.githubusercontent.com/17298604/123319556-d4c8ad80-d530-11eb-8b3d-5e46e45f3085.png)

The summary of actions is:

![image](https://user-images.githubusercontent.com/17298604/123319627-f32ea900-d530-11eb-822d-675ec1382a01.png)

Any ideas?

**Comment by david-noe** [comment]
I have the same issue

**Comment by dasmeet** [comment]
same here
