### ISSUE TITLE
Date filters does not work

### ISSUE THREAD

**Issue by masterwendu** [directus/directus#6494]
1) The issue and what you expected to happen
When there is a filter on a date or a date time field for =, >=, <=, <, >, != the API returns wrong data.
Because of this issue also the calendar layout is not working at all.

Example:
I have a collection with a date field with 3 items, `2021-06-01`, `2021-06-24` and empty

Filter(s): [_eq, _gt, _gte]: 2021-06-01
Result: 0 items

Filter(s): [_neq, _lt, _lte]:
[data.zip](https://github.com/directus/directus/files/6713990/data.zip)
 2021-06-01
Result: 2 items without the empty one

Filter(s): {"_between":"2021-06-01,2021-06-25"}}
Result: 0 items

2) Exact steps to reproduce this issue
    Add a collection with a date field

3) Your environment:
   Directus as dev server -> main branch
    DBMS: sqlite3
    Browser: tested on Firefox 89.0.1

4) Any other relevant information we might need to reproduce this issue
    A SQL dump of the setup.
    What third party services you rely on (S3, managed database, ...).

See my SQLite db in the attachments

**Comment by Krugmor** [comment]
Same problem. From version 87 to current time, the date filter returns data 1 day earlier.
For example:
?filter[date][_eq]=2021-08-12
Returns data where date=2021-08-11

**Comment by davidsandoz** [comment]
I have the same issue with a MySQL DB.

**Comment by pchebro** [comment]
We have the same issue on v9.0.0-rc.64 with a MySQL DB. I have a collection with a date field and trying to add a filter to the field as below in field permissions for contributor role. But it's giving error that date filed should be a number. Is there any work around to implement validation rule for date fields and raise exception?
{
	"effective_date": {
		"_gt": "$NOW"
	}
}
