### ISSUE TITLE
Numeric value is out of range

### ISSUE THREAD

**Issue by Enhed** [directus/directus#6504]
filesize in database directus_files is integer, cos impossible attach large files, can its be fixed?
i creating something like video hosting and very needed that. Can i just change integer to bigint or decimal?

**Comment by Enhed** [comment]
i change type to bigint, thats working, but will be its working with feature migrations?

**Comment by rijkvanzanten** [comment]
It most likely won't. Do you wanna open a PR to make it a big int by default?

**Comment by Enhed** [comment]
> It most likely won't. Do you wanna open a PR to make it a big int by default?

yes, please

**Comment by miguelBinpar** [comment]
https://github.com/directus/directus/pull/6516#issuecomment-1621479583
