### ISSUE TITLE
Search is not available on mobile

### ISSUE THREAD

**Issue by supermx1** [directus/directus#6505]
MySQL 8
Directus 9.0.0 rc80

So I wanted to filter or search my records on mobile and for some reason it the search icon is hidden. Even if i click the arrow. Not thing shows. The same goes with trying to filter through many to one field options. So looking for an item through hundreds of records is impossible. Is there a CSS fix? 

https://user-images.githubusercontent.com/9326922/123483489-b03b0700-d5fe-11eb-9bb9-dbdfc9f1a6f2.mp4

**Comment by fballan93** [comment]
It is a bug That we noticed also in our deployment of rc76 too. I hope it has been fixed in the latest RC
