### ISSUE TITLE
users/me API not working anymore

### ISSUE THREAD

**Issue by kkahara** [directus/directus#6508]
/users/me  API worked fine about a week ago, but I am getting an error message now.

The error message:

      
{
  "errors": [
    {
      "message": "Invalid user credentials.",
      "extensions": {
        "code": "INVALID_CREDENTIALS"
      }
    }
  ]

I am passing 

Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZC..."

in the header. 

Is this a bug?

**Comment by paescuj** [comment]
Can you please provide more information? What's your environment, browser, Directus version, ...?
How are you using the API? Please note that tokens have an expiry date and you need to refresh them or issue a new one: https://docs.directus.io/reference/api/authentication/

**Comment by kkahara** [comment]
Thank you. I have tried to call theAPI from my React.JS app and a REST client tool but got the same error. 

Here is my React code:

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [userToken, setUserToken] = useState("");
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [message, setMessage] = useState("");

  async function handleSubmit(event) {
    event.preventDefault();

    axios
      .post(
        "https://directus.isaiahinstitute.jp/auth/login",
        {
          email: email,
          password: password,
        },
        {
          headers: {
            "content-type": "application/json",
          },
        }
      )
      .then((response) => {
        // Handle success.
        localStorage.setItem("userToken", response.data.access_token);
        localStorage.setItem("userIsLoggedIn", true);
        setIsLoggedIn(true);
        setUserToken(response.data.data.access_token);
        setMessage("successfully obtained the token");
      })
      .catch((error) => {
        // Handle error.
        console.log("An error occurred:", error.response);
        setMessage(
          "確認できませんでした。ユーザー名かパスワードをお確かめください。"
        );
        if (error.response.statusCode === "400") {
          setMessage("確認できませんでした。");
        }
        setIsLoggedIn(false);
      });

    axios
      .get("https://directus.isaiahinstitute.jp/users/me", {
        Authorization: "Bearer " + userToken,
      })
      .then((response) => {
        // Handle success.
        setMessage("ようこそ、" + response.data.first_name + "さん");
        localStorage.setItem("userEmail", response.data.data.email);
        localStorage.setItem("userID", response.data.data.id);
        setTimeout(() => browserHisotry.goBack(), 1000);
      })
      .catch((error) => {
        // Handle error.
        console.log("An error occurred:", error.response);
        if (error.response.statusCode === "400") {
          setMessage("ユーザー情報を入手できませんでした。");
        }
        setIsLoggedIn(false);
      });
  }


Below is a screenshot of my REST client app:

![image](https://user-images.githubusercontent.com/47410653/123504714-08cace00-d618-11eb-97d2-4ce5ab098d3b.png)

I can successfully obtain the access_token but don't know the next step--to obtain the user info by using the access_token. I don't think I can use /users/:id API because I don't have the id yet. I also don't know what permission I need to give to the role of the user to obtain the info. 

![image](https://user-images.githubusercontent.com/47410653/123504818-b807a500-d618-11eb-83e8-961337156605.png)

Thank you

**Comment by paescuj** [comment]
As this is not a issue with Directus itself but a question, can you please close this issue and open up a thread under https://github.com/directus/directus/discussions.
Just mention me there and I will try to help you!
