### ISSUE TITLE
In Collection Navigation configuration under roles and permissions , type once changed to "start open" cannot revert back to always open

### ISSUE THREAD

**Issue by shivam95** [directus/directus#6529]
### What version of Directus are you using?

v9.0.0-rc.81

### What version of Node.js are you using?

Docker Image 

### What database are you using?

Postgres

### What browser are you using?

Edge (Chromium)

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

### Describe the Bug

In Collection Navigation Configuration, type once changed to Start Open or Start Collapsed cannot revert back to Always open even it is showing Always Open

![image](https://user-images.githubusercontent.com/11583651/123616905-5b78d580-d824-11eb-85c4-fc708adacc38.png)

But it remains to "Start Open or Collapsed"

![image](https://user-images.githubusercontent.com/11583651/123617098-895e1a00-d824-11eb-934a-09cdd3954e69.png)

I cannot go back to **Always Open**

The only way is to delete all the groups and recreate them

### To Reproduce

Create a group 
Add Collections 
Save 
Change type to Start Open - Works as expected
Change back to Always Open - Stays Opened

**Comment by rijkvanzanten** [comment]
I believe this was fixed in https://github.com/directus/directus/commit/337557b3165158c34f82a84ffc40bf06f4bf8c7f
