### ISSUE TITLE
Couldn't load custom layouts

### ISSUE THREAD

**Issue by ejrasmussen1** [directus/directus#6550]
### Describe the Bug

Custom layout does not load. It appears all the '/' from the file path have been removed. The following error is in the console:

Not allowed to load local resource: file:///C:/pathtodirectusextensionslayoutscustomindex.js

With a warning: "Couldn't load custom layouts"

### To Reproduce

1. Create a custom layout by following the guide at https://docs.directus.io/guides/layouts/
2. Visit a Collection page

### What version of Directus are you using?

v9.0.0-rc.81

### What version of Node.js are you using?

v14.17.0

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally

**Comment by relisyss** [comment]
same problem occurs with custom modules

**Comment by bryantcarlos** [comment]
I'm still running into the same issue in version 9.0.0-rc.83 on Windows

![directus_logs](https://user-images.githubusercontent.com/59461140/124410923-02f28c80-dd7e-11eb-8e80-7f1584e41e26.png)

**Comment by nickrum** [comment]
@bryantcarlos The fix hasn't been released yet.

**Comment by bryantcarlos** [comment]
@nickrum Ohhh okay, sorry. Thank you.
