### ISSUE TITLE
CSS in app extensions not working

### ISSUE THREAD

**Issue by nickluger** [directus/directus#6556]
### The issue 
Using custom CSS via `<style>...</style>` in Vue files (in custom extensions) is no longer possible due to:

1. This upstream issue at rollup: https://github.com/vuejs/rollup-plugin-vue/issues/364. There's a workaraound for this, but it cannot be used with Directus, due to:
2. The new `@directus/extension-sdk`, which has its own rollup config and does not allow us to add a custom rollup configuration.

### Current Workaround:
**Do** use your custom rollup config including CSS plugins & mimic Directus' rollup-config importing `SHARED_DEPS`, to be able to use Directus global components. Use `rollup -c` again instead of `directus-extension build`

```
// ... other imports
import { SHARED_DEPS } from "@directus/shared/constants";

export default {
  input: ...
  output: ...
  // use Directus global components 
  external: SHARED_DEPS,
  plugins: [
   // use CSS in Vue files
    vue({ preprocessStyles: true }),
    postcss(),
    nodeResolve(),
     ...
  ],
};
```

### Suggested solution
Allow extending the Directus' rollup-config used by `@directus/extension-sdk`. This way, not only CSS could be used, but also Sass, less or whatever i want as a dev.

### To Reproduce

1. Create a custom interface or display
2. Use `<style>` and some CSS in it.
3. Run `npx directus-extension build` 
4. Get `Unexpected token (Note that you need plugins to import files that are not JavaScript)`

### What version of Directus are you using?

9.0.0-rc.82

### What version of Node.js are you using?

>=14

### What database are you using?

postgres:12.5

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
Lets open a separate feature request discussion for adding the ability to add additional plugins to the internal rollup config 👍🏻
