### ISSUE TITLE
fields groups break fields columns (half width)

### ISSUE THREAD

**Issue by wc-matteo** [directus/directus#6557]
### Describe the Bug

creating a field group with half width fields inside it makes other half width fields not respect their columns

### To Reproduce

1. create 2 half width fields besides each other
2. create a field group
3. create 1 half width field and put it inside the group

![image](https://user-images.githubusercontent.com/10562635/123777858-e2838780-d8d0-11eb-8f82-532511fd3b40.png)

![image](https://user-images.githubusercontent.com/10562635/123777880-e6afa500-d8d0-11eb-8161-9d2821414327.png)

### What version of Directus are you using?

v9.0.0-rc.82

### What version of Node.js are you using?

n/a

### What database are you using?

mssql 2016

### What browser are you using?

chrome

### What operating system are you using?

win 10

### How are you deploying Directus?

k8s

**Comment by wc-matteo** [comment]
btw a field group without an inteface shows up as an input field without any labels, is that expected or is it a bug?

**Comment by rijkvanzanten** [comment]
> btw a field group without an inteface shows up as an input field without any labels, is that expected or is it a bug?

Good one. It's "failing successfully". Directus defaults to a regular input if it can't determine what to render for any given field, but that'll fail for groups. Technically a separate issue, but I'll fix it in the same PR 👍🏻

**Comment by xesjkeee** [comment]
I faced with the similar bug

In `directus@9.0.0-rc.81`:

<img width="1113" alt="1" src="https://user-images.githubusercontent.com/17751886/123852186-b42f9780-d924-11eb-8e7a-93d250316c3c.png">

In `directus@9.0.0-rc.82`:

<img width="1112" alt="2" src="https://user-images.githubusercontent.com/17751886/123852225-c01b5980-d924-11eb-885c-f5732efb00b0.png">
