### ISSUE TITLE
Field with same name is clearing when switching between collections

### ISSUE THREAD

**Issue by tim-smart** [directus/directus#6569]
### Describe the Bug

When I switch between collections in the editor UI, a field with the same name is being cleared.

Video: https://youtu.be/QMyJ3ZrvOJY

### To Reproduce

https://youtu.be/QMyJ3ZrvOJY

### What version of Directus are you using?

v9.0.0-rc83

### What version of Node.js are you using?

Whatever docker is using

### What database are you using?

postgres 11

### What browser are you using?

Brave

### What operating system are you using?

macOS

### How are you deploying Directus?

docker

**Comment by rijkvanzanten** [comment]
I believe this was since fixed in #6733

**Comment by tim-smart** [comment]
Looks like that fixed it :)
