### ISSUE TITLE
Files created with extra dots between filename and extension

### ISSUE THREAD

**Issue by akrantz01** [directus/directus#6573]
### Describe the Bug

When uploading a file, an extra dot `.` is added between the extension and filename if an extension is already present in the filename. This occurs because `path.extname` preserves the `.` while `mime-types.extension` does not.

It should be just modifying [these lines](https://github.com/directus/directus/blob/main/api/src/services/files.ts#L49-L51) to read something like:
```js
const fileExtension = path.extname(payload.filename_download) || (payload.type && '.' + extension(payload.type));

payload.filename_disk = primaryKey + fileExtension;
```

### To Reproduce

1. Upload or import a file to Directus with an extension
2. Open the uploads folder, and there will be a file named in the format `<primary key>..<extension>`
  Ex: `73702653-ade6-402f-bb75-9572c7d16414..png`

### What version of Directus are you using?

v9-rc.82

### What version of Node.js are you using?

16.3.0

### What database are you using?

Postgres 13

### What browser are you using?

Firefox

### What operating system are you using?

Ubuntu 20.04

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
@akrantz01 Wanna open a PR for this? 🙂
