### ISSUE TITLE
"Current collection" not shown in translations field setup

### ISSUE THREAD

**Issue by wc-matteo** [directus/directus#6582]
### Describe the Bug

there seems to be something wrong with translations fields. Maybe related to the introduction of field groups.

![image](https://user-images.githubusercontent.com/10562635/123993542-ce24b500-d9cc-11eb-88fa-69ebcb6e7ea6.png)

and

![image](https://user-images.githubusercontent.com/10562635/123993580-d5e45980-d9cc-11eb-9c0f-5702c3b7143b.png)

### To Reproduce

create a translation field

### What version of Directus are you using?

v9.0.0-rc.82

### What version of Node.js are you using?

n/a

### What database are you using?

mssql 2016

### What browser are you using?

chrome

### What operating system are you using?

win 10

### How are you deploying Directus?

k8s

**Comment by wc-matteo** [comment]
I updated to v85 but I still see:

![image](https://user-images.githubusercontent.com/10562635/125912092-9b52b6f4-11be-480b-92c8-4c01669b66a0.png)

in the past the "translations fields" could be clicked to navigate to that collection. Has that been intentionally removed?

**Comment by rijkvanzanten** [comment]
> Has that been intentionally removed?

Yes that was changed intentionally 👍🏻  We're revamping that effort to work the same for every relational field, instead of being a hardcoded one-off for translations
