### ISSUE TITLE
Field "multiple files" causes error 500

### ISSUE THREAD

**Issue by narduin** [directus/directus#6600]
### Describe the Bug

Hello,

I'm encountering a weird bug that I can't seem to solve:

Whenever I create a "multiple files" field, I get an error when querying the whole collection (I'm using graphql).
The error:
```javascript
TypeError[my_collection_directus_files.directus_files_id]: Definition object should contain 'type' property: Object({ type: undefined })
```

I tried many different approaches like setting the permissions before and after adding any element to the field or using custom collections names vs default names…
The weirdest part is that I successfully created a multiple files field in a previous collection using the exact same settings.

Thank you!

### To Reproduce

1. Create a collection
2. Add a "multiple files" field
3. leave auto fill values (or use custom) for junction collection
4. add a `sort` field
5. select `nullify` or `delete` for the relational triggers
7. display template: `Filename (download)`
8. display related values
9. allow access to public inside permissions
10. add one or many files to the field
11. query the collection whit graphql

### What version of Directus are you using?

tested on v9.0.0-rc.74 and v9.0.0-rc.83

### What version of Node.js are you using?

14.16.1

### What database are you using?

SQLite

### What browser are you using?

firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
Is this using the same user? One potential reason I can think of is that you're making the call as a different user, causing it to have a different underlying schema, which is missing something for some reason 🙂

**Comment by narduin** [comment]
Yes, I only ever had one user on this instance.
I can send the db if necessary.

What do you mean when you say:
> making the call

**Comment by rijkvanzanten** [comment]
@narduin Executing the GraphQL request using a different access token which has a different set of permissions 👍🏻 

> I can send the db if necessary.


That would be very helpful!

**Comment by narduin** [comment]
I haven't set specific permissions yet, I'm using the unauthenticated `public` role when sending request.
I think the error is specific to my db because I tried on a fresh install and it worked as intended.
I used my db on the fresh install and it failed. I tried to create the field on a new collection on my db and it failed as well.

There must be a misconfiguration inside the db somewhere…

**Comment by narduin** [comment]
@rijkvanzanten [here is the db](https://www.swisstransfer.com/d/94fa7ae0-4922-4de2-a2d3-271e55f1a4ea) (downloadable 1 time over 7 days)
I can provide more info if you need.

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten here is the db (downloadable 1 time over 7 days)
> I can provide more info if you need.

Mind sending it to me directly at rijk@directus.io? Someone else already downloaded it apparently

**Comment by narduin** [comment]
I might have more insight.

I decided to start over on a fresh install (rc-83). I recreated all my collections and fields. All went great, I could use multiple files fields and query them in graphql.

However, in order to display them, I call this url: `http://localhost:8055/assets/71b1a8d3-4f49-4a48-a847-26fb1f5372b7`
Without allowing `public` to access the `directus files` collection, the images don't show. But when setting those permissions, I get an error 400 or the original error 500.

I might not be requesting images correctly but I don't know how else…

**Comment by rijkvanzanten** [comment]
I can't seem to reproduce the OP. If the problem still occurs, can you send me a dump directly to rijk@directus.io? 

> Without allowing public to access the directus files collection, the images don't show

This makes sense, as the /assets endpoint uses the same permissions as Files.

> But when setting those permissions, I get an error 400 or the original error 500.

What permissions did you configure?

---

I'll close this for now as the original problem doesn't seem to occur in the latest version. We can reopen if needed

**Comment by Attacler** [comment]
I have this same issue on RC90.

How its setup right now:

I have a field on files named: public (boolean)
I also have a rule on it, public means that its visible to the public role.

Then when i add products, i have the filter on active is true, that works.
But when i add a single file field into it, it wont work anymore.
It gives me the same error.
Stacktrace:
13:14:54 🚨 TypeError[producten.preview]: Definition object should contain 'type' property: Object({ type: undefined }) 

Error: TypeError[producten.preview]: Definition object should contain 'type' property: Object({ type: undefined })
    at TypeMapper.convertOutputFieldConfig (/directus/node_modules/graphql-compose/lib/TypeMapper.js:230:27)
    at ObjectTypeComposer.setField (/directus/node_modules/graphql-compose/lib/ObjectTypeComposer.js:162:46)
    at /directus/node_modules/graphql-compose/lib/ObjectTypeComposer.js:168:18
    at Array.forEach (<anonymous>)
    at ObjectTypeComposer.addFields (/directus/node_modules/graphql-compose/lib/ObjectTypeComposer.js:167:32)
    at getTypes (/directus/node_modules/directus/dist/services/graphql.js:237:105)
    at getReadableTypes (/directus/node_modules/directus/dist/services/graphql.js:284:62)
    at GraphQLService.getSchema (/directus/node_modules/directus/dist/services/graphql.js:115:41)
    at GraphQLService.execute (/directus/node_modules/directus/dist/services/graphql.js:80:29)
    at /directus/node_modules/directus/dist/controllers/graphql.js:27:40

producten.preview = the single file field.

So how i solved it:
There where no fields selected on the files custom rule, when i added the ID field to it, it was solved.

Maybe a solution to this: give back an GraphQL error when there is no permission to atleast 1 field?
