### ISSUE TITLE
Warms & Bugs when migrate database rc69 to rc83

### ISSUE THREAD

**Issue by Silbad** [directus/directus#6608]
### Describe the Bug

Hello,
I update Directus rc69 to rc83.
I have few "WARN rm not removing" =>.bin (16 files)
And when I migrate database, I have a few differents bugs : 

* Couldn't add foreign key constraint... (3 times)
* Ignoring authors_books_2.books_id<->books. Tables don't exist. (an old table I had removed)
* Encountered one or more corrupted relationships. Please check the following rows in "directus_relations": 15 (a relationship with the table authors_books_2 I had removed)

Is this important or not?
Thanks

### To Reproduce

-

### What version of Directus are you using?

9.0.0-rc.83

### What version of Node.js are you using?

12.20.1

### What database are you using?

MySQL 8.0.21

### What browser are you using?

Tauri

### What operating system are you using?

Windows

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
> Is this important or not?

Not necessarily! They're warnings telling you if it skipped over setting up a foreign key constraint that is "illegal". 

Your example is a good example of this: there was a record in directus_relations left over from before that is now pointing to a table that doesn't exist. That's skipped. The `Encountered one or more corrupted relationships` message tells you which of the relationships in directus_relations are deemed illegal, so you can manually address those if you want to
