### ISSUE TITLE
PG filter timestamp with time zone filed as empty

### ISSUE THREAD

**Issue by botzill** [directus/directus#6615]
### Describe the Bug

I try to filter items by null `timestamp with time zone` field:

```
service_filters['_or'] = [
    // {
    //   pre_book_datetime: {
    //     _gte: pre_book_datetime
    //   }
    // },
    {
      pre_book_datetime: {
        _empty: true
      }
    }
  ]
```
  
And the query it creates check if `is null` and `pre_book_datetime = ""` 

we get the error:

```
invalid input syntax for type timestamp with time zone: ""
```

I guess for this type of fields we need to check only `is null` ?

Thx. 

### To Reproduce

Do a filter on a timestamp field that is null like:

```
service_filters['_or'] = [
    {
      pre_book_datetime: {
        _empty: true
      }
    }
  ]
```

### What version of Directus are you using?

v9.0.0-rc.82

### What version of Node.js are you using?

12.0.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
> I guess for this type of fields we need to check only is null ?


Yup! Use `_null` instead of `_empty`. `_empty` checks for empty string 👍🏻
