### ISSUE TITLE
Read hook doesn't fire on readByQuery

### ISSUE THREAD

**Issue by lluishi93** [directus/directus#6622]
### Describe the Bug

The custom hooks are not being triggered for the read action.

![image](https://user-images.githubusercontent.com/14786440/124280315-d6096400-db48-11eb-8b4a-349f168c936c.png)
![image](https://user-images.githubusercontent.com/14786440/124280407-f1746f00-db48-11eb-9b75-3c50e2a81c4e.png)
![image](https://user-images.githubusercontent.com/14786440/124280461-fd603100-db48-11eb-96f1-d7ec8add88b4.png)

### To Reproduce

Cretate any collection with some field, give it public permissions, create a custom hook with a read event trigger, and check that the hook is not being triggered.

### What version of Directus are you using?

RC.83

### What version of Node.js are you using?

16

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

Linux Mint

### How are you deploying Directus?

Locally

**Comment by benhaynes** [comment]
That's because READ hooks don't exist yet! 😄 

Ref: https://github.com/directus/directus/discussions/3736

**Comment by lluishi93** [comment]
Ok, I tried it because it appears in the docs: https://docs.directus.io/guides/api-hooks/
Looking forward to that feature.

**Comment by benhaynes** [comment]
Oh, interesting! Maybe that is supposed to have the `1` (Feature Coming Soon) note? @rijkvanzanten

**Comment by rijkvanzanten** [comment]
Read hooks where added in https://github.com/directus/directus/pull/6341 🙂

**Comment by rijkvanzanten** [comment]
I think the problem comes from the fact that the read hook was added to `readMany` and `readOne` by @MoltenCoffee, but this endpoint is using `readByQuery`, which misses this execution 👍🏻 

https://github.com/directus/directus/pull/6341/files#diff-e64a17bacef22ff280bf0917d6089c96e034e1ea55c090cc8f98fe4fd3af2eec

**Comment by MoltenCoffee** [comment]
> I think the problem comes from the fact that the read hook was added to `readMany` and `readOne` by @MoltenCoffee, but this endpoint is using `readByQuery`, which misses this execution 👍🏻

I copied this behavior from existing hooks, like `updateMany` and `deleteMany`. These will trigger on `updateMany`, not on `updateByQuery`. The difference here is that `updateOne` is just a wrapper around `updateMany`. 

Would it make sense to move the call to `readByQuery`?

**Comment by rijkvanzanten** [comment]
@MoltenCoffee The difference is that those call each other in a slightly different manner. For example, a createMany will call call createOne multiple times. `readMany` calls `readByQuery`, but `readByQuery` can also be called standalone. We should move the `readMany` hook to `readByQuery`, and that should do the trick 👍🏻

**Comment by MoltenCoffee** [comment]
I'll have a look right away!

**Comment by rijkvanzanten** [comment]
Thanks! ❤️

**Comment by MoltenCoffee** [comment]
Ah, looking at the code I remember another reason I did it the way I did. 

The queries are constructed in the `readOne` and `readMany` methods, and passed to `readByQuery`. This means `readByQuery` has no direct access to the `keys` array, which is usually passed to hooks.

We could "reconstruct" this array from the returned `records` with something like `records.map(item => item.id)` (or a plain for-loop for a possible small reduction of overhead), but this will result in an overhead for _every_ database read, even if no hooks are actually registered. The overhead is small, but will of course become larger the larger the query is.

**Comment by rijkvanzanten** [comment]
> This means readByQuery has no direct access to the keys array, which is usually passed to hooks.

That's fine! For readOne / readMany you read by the key(s), so you know what keys where requested. For readByQuery, we can pass on the query, as that's the most accurate "request info" available 👍🏻

**Comment by MoltenCoffee** [comment]
> For readByQuery, we can pass on the query, as that's the most accurate "request info" available 👍🏻

So if I understand correctly, you want to return the query as `item`? Or do you want a seperate `query` key?

After clarification I'll change it in #6645

**Comment by rijkvanzanten** [comment]
@MoltenCoffee We should probably have a dedicated "query" key, or use `payload` 👍🏻
