### ISSUE TITLE
Search Filter not working correctly

### ISSUE THREAD

**Issue by supermx1** [directus/directus#6638]
### Describe the Bug

The search filter doesn't filter properly. Using the search field to filter for an item present in a collection returns no results meanwhile I can see the result there. I don't know if this is a bug or I am not filtering records correctly The search meanwhile

https://user-images.githubusercontent.com/9326922/124370817-267ce080-dc73-11eb-8416-d8302a1370ac.mp4

### To Reproduce

Copy a random record and paste it in the search field.

### What version of Directus are you using?

RC.83

### What version of Node.js are you using?

14.15.3

### What database are you using?

10.4.17-MariaDB - Source distribution

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
What type of column is "Company ID" ?

It'll use a like search for text/string based columns, as per

https://github.com/directus/directus/blob/5936c8b2d9135f9df9b42b4e572f6ac604c52d75/api/src/utils/apply-query.ts#L478-L485

**Comment by supermx1** [comment]
Varchar field. String

**Comment by supermx1** [comment]
Now, I think this just affects one collection. I have tried the same search filter with other collections and they work, But on just that collection the search filter doesn't work (Note: Other collections that have this same field "Company ID" I can search and it works. Like eg `dqWeb8vg8O38qSS62ml6D` if i search for that in the affected collection it shows Not Found, but if I search for it in a different collection it shows the result of a company with that ID). Now for some reason, it is doing this; 

Uploading screencast 2021-07-04 12-51-41.mp4…

**Comment by rijkvanzanten** [comment]
Odd! @supermx1 could you share a database dump of the schema for this one collection?

**Comment by supermx1** [comment]
https://user-images.githubusercontent.com/9326922/124384002-5c4bb480-dcc7-11eb-8a50-c5fc28db3c13.mp4

**Comment by supermx1** [comment]
Sent it to your email @rijkvanzanten

**Comment by supermx1** [comment]
And just like that, it starts working on its own.... I literally have no idea what just happened or has been happening. Its no longer doing the page not found thing, but the search filter doesn't work

**Comment by rijkvanzanten** [comment]
Using your dump (I didn't know what email was yours at first 👀), this seems to work as expected on the latest version. I'm able to copy/paste search for those `company_id` without trouble.

I'll close this for now.

@supermx1 Does this still happen for you on the latest version? If so, could you share the exact configuration of that particular collection+field that doesn't work? I'm wondering if it might recognize it as a non-string type column somehow

**Comment by supermx1** [comment]
Works fine now.. Thanks. Worked some RCs back too
