### ISSUE TITLE
CSV type is JSON not string[]

### ISSUE THREAD

**Issue by nilsmich** [directus/directus#6653]
### Describe the Bug

Hello
There seems to be a small bug in the types for CSV fields. They are supposed to be of the type array of strings according to https://docs.directus.io/concepts/types/ ("CSV — A comma-separated value, returned as an array of strings"). 

In the GraphQL Schema they are shown as JSON. 

I am using @graphql-codegen/cli to generate the types and to ensure type safety from end to end. JSON would be equivalent to object. An array of strings would be the correct type that would also transfer to the front-end type-script typing system. 

Thank you a lot for looking into this. 
Best 

### To Reproduce

1. Create a new field of type CSV in the data model
2. The Interface could be tags or Dropdown multiple
3. Open an item in the collection and add the value (This would not even be required)
4. Access the GraphQL schema (e.g. https://lucasconstantino.github.io/graphiql-online/)
5. The type of the field is JSON 

### What version of Directus are you using?

^9.0.0-rc.83 (on local); ^9.0.0-rc.71 (on Prod)

### What version of Node.js are you using?

v14.17.0 (local)

### What database are you using?

 MYSQL Version: 5.7.34 (npm package version: ^2.18.1)

### What browser are you using?

Chrome: 91.0.4472.114

### What operating system are you using?

Windows

### How are you deploying Directus?

Local and Heroko

**Comment by rijkvanzanten** [comment]
Wanna open a PR to add that in? 

This is where that type is being extracted:

https://github.com/directus/directus/blob/e753e37cef35608aaa3f34b19fd85350f40b7a71/api/src/utils/get-graphql-type.ts#L13-L19
