### ISSUE TITLE
No error message from password reset request

### ISSUE THREAD

**Issue by dannycoulombe** [directus/directus#6658]
### Describe the Bug

When posting the wrong payload to /auth/password/request, it returns a 200 with empty data. It took me a while to determine that I was in the wrong because I was sure that everything was fine since the status code was OK.

Directus should let us know if the payload is incorrect.

### To Reproduce

Post the following to /auth/password/reset

{ email: { email: "email@domain.com" } }

### What version of Directus are you using?

v9.0.0-rc.83

### What version of Node.js are you using?

v12.21.0

### What database are you using?

MySQL 8

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying Directus?

locally

**Comment by MoltenCoffee** [comment]
I'd say this is as it should be. Otherwise, you'd provide a way to check if an account exists with a certain address.

**Comment by dannycoulombe** [comment]
> I'd say this is as it should be. Otherwise, you'd provide a way to check if an account exists with a certain address.

Not exactly. It should return a 400 Bad request since the payload is incorrect. This does not expose if an account is existing or not.

**Comment by dannycoulombe** [comment]
> I'd say this is as it should be. Otherwise, you'd provide a way to check if an account exists with a certain address.

Just to clarify, I agree with you that this should return a 200:
`{ email: "email@domain.com" }`

but not this:
`{ email: { email: "email@domain.com" } }`

**Comment by MoltenCoffee** [comment]
Ah, I misunderstood. I thought you meant sending a non-existent email address. Nvm!

**Comment by rijkvanzanten** [comment]
@dannycoulombe Wanna open a PR for that? 🙂 

We should add an additional check in here that makes sure that typeof == string:

https://github.com/directus/directus/blob/c4c6d7a4b930ca8c4d1cd69dbde4027f83c2d45a/api/src/controllers/auth.ts#L161-L166
