### ISSUE TITLE
Wrong mime type

### ISSUE THREAD

**Issue by grapix** [directus/directus#6671]
### Describe the Bug

When uploading a .gltf file (3D model), the mime type in Directus is "application/octet-stream" – but it should be "model/gltf+json".

### To Reproduce

Upload a .gltf file in Directus. Then make an api request for this file and check the mime type.

### What version of Directus are you using?

9.0.0-rc.83

### What version of Node.js are you using?

15.12.0

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

maxOS, Debian Linux

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
We get the mimetype from [`busboy`](https://www.npmjs.com/package/busboy), which pulls it from the content type header in the multipart upload. We're not extracting / setting the mimetype in Directus itself 👍🏻 

When using multipart form-data uploads, you can set the mime type in the file chunk, for example `"file=@./fake-mp3.mp3;type=audio/mpeg"`
