### ISSUE TITLE
v-input emits string when used with number type

### ISSUE THREAD

**Issue by baranelitez** [directus/directus#6672]
### Describe the Bug

Hi. I've added a repeater interface for my JSON object, and set the fields as follows:
itemid: integer
quantity: integer

When requested from the API, the numbers are returned as strings. Example response:
`[{"itemid":"3","quantity":"5","stackable":true}]`

Note that the boolean type works correctly as opposed to integers.

### To Reproduce

- Create a collection with a JSON field
- Choose "Repeater" interface for the JSON field
- Set JSON property types to Integer
- Add an item to the collection, and to the field by using the "Repeater" interface
- Request the object from the API
- Observe that the value is String, as opposed to Number on API response.

### What version of Directus are you using?

9.0.0-rc.83

### What version of Node.js are you using?

16.3.0 (in docker image)

### What database are you using?

sqlite

### What browser are you using?

chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by baranelitez** [comment]
UPDATE:

this happens when a new item is added with the repeater instance OR its value is replaced with a new input. If incremental arrows are used it'll return as a number. Here's the example:

- Add a new item with properties itemid:3 and quantity:5
- Save the field, save the item and do an API call
- You'll see the response as {itemid:"3", quantity:"5"}
- Go back to item. replace itemid:3 with 5.
- Save the field, save the item and do an API call
- You'll see the response as {itemid:"5", quantity:"5"}  (value changed, but still string)
- Go back to item. Change the itemid value by using the incremental arrows on the field.
- Save the field, save the item and do an API call
- Response will be {itemid:5, quantity:"5"}

**Comment by rijkvanzanten** [comment]
I believe it's due to the fact that a browser `input type="number"` technically allows for text (for things like `1e5`)
