### ISSUE TITLE
System fields are editable

### ISSUE THREAD

**Issue by supermx1** [directus/directus#6684]
### Describe the Bug

So this going to sound funny. So I wanted to adjust the layout (full width or half-width) and translation of some fields in the Directus_users collection. This small change literally causes the fields or should say any field I adjust (either layer or translation) to turn into an input field (This includes fields like language, 2fa, tags, etc). Now they all don't work. The data still gets submitted to the database, but it is not as it should be. 

I don't know if it is a bug or a feature, but it sure feels unsafe to use.

![Screen Shot 2021-07-07 at 1 44 45 AM](https://user-images.githubusercontent.com/9326922/124683433-ead95500-dec4-11eb-9fba-7f106bc7485e.jpg)

![Screen Shot 2021-07-07 at 1 45 43 AM](https://user-images.githubusercontent.com/9326922/124683495-0e040480-dec5-11eb-8887-d6fe55e31113.jpg)

### To Reproduce

Go to the directus_user collection and adjust either layout or transalation. Especially special fields like drop downs, 2fa etc

### What version of Directus are you using?

RC.83

### What version of Node.js are you using?

14.15.3

### What database are you using?

10.4.17-MariaDB - Source distribution

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

Digital Ocean

**Comment by rijkvanzanten** [comment]
System fields aren't (supposed to be) user editable 👍🏻

**Comment by ConnorSimply** [comment]
@rijkvanzanten  Me being the fool I am, also messed with the system fields and was trying to just hide some fields in the app. And now it has made my entire Directus instance come to a halt.

Any idea how I can just restore it to how it was? I just clicked hide within app on preferences_divider, theme, and tfa and now every page in Directus errors.

Version: ^9.0.0-rc.85

![image](https://user-images.githubusercontent.com/12714889/126428294-3a635de8-1fc7-42f8-a28d-b5045c0929cb.png)

![image](https://user-images.githubusercontent.com/12714889/126428167-6fd506af-bd05-4501-a372-e5ec9bb4a547.png)

![image](https://user-images.githubusercontent.com/12714889/126428224-e40441d3-da18-4450-98db-c3f39bfa4e04.png)

![image](https://user-images.githubusercontent.com/12714889/126427894-96e5dcb8-486e-4656-acd6-cc0ce4763ddb.png)

**Comment by rijkvanzanten** [comment]
Removing all the records that relate to the `directus_*` collections from `directus_fields` should revert you back 👍🏻

**Comment by supermx1** [comment]
@rijkvanzanten can we now edit directus_users? In the new RC85 without it breaking? I don’t want to risk testing it out. Lol. Thanks for the support mahn

**Comment by rijkvanzanten** [comment]
You can (and always could) add/edit/remove custom fields. The bug was that the locked system fields rendered double which enabled editing the system fields, which can't be edited 👍🏻
