### ISSUE TITLE
Can't duplicate a field to another collection if it's inside a group

### ISSUE THREAD

**Issue by narduin** [directus/directus#6693]
### Describe the Bug

Hello!

I think I found a small bug: when duplicating a field that is inside a group to another collection, the field does not show up inside that collection.
Looking inside the database shows that the field is correctly duplicated but is keeping its `group` value (an id of the original group it was in).

### To Reproduce

1. Create a collection
2. Create a group
3. Create a field and place it inside the group
4. Create a second collection
5. Duplicate the field from the first collection to the second collection

### What version of Directus are you using?

v9.0.0.0-rc.83

### What version of Node.js are you using?

v14.16.1

### What database are you using?

SQLite

### What browser are you using?

firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
We should clear the `group` value on duplicate, should be a fairly easy fix. Wanna open a PR for that @narduin? 🙂

**Comment by narduin** [comment]
I'm not familiar at all with opening PR. Am I supposed to propose a fix and send it for review through PR?
I'm more of a front-end dev but I'd love to learn how to contribute like this :)

**Comment by rijkvanzanten** [comment]
This is a pretty good overview of the exact flow: https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/

The actual code that needs to be changed is this bit: 

https://github.com/directus/directus/blob/5760b177c335e3050c4f4bbef4b0a58b5623ae08/app/src/modules/settings/routes/data-model/fields/components/field-select.vue#L258-L266

As you can see, the new field that is to be created as the duplicated copies over the whole current field (`...props.field`), but we should add a `if (field.meta?.group) delete field.meta.group` after that to make sure the group is cleared

**Comment by narduin** [comment]
I followed [this guide](https://docs.directus.io/contributing/running-locally/) but I'm getting a 404 on `localhost:8055` when running `npm run dev`
I tried `/app` `/api` but 404 as well… sorry I'm a bit lost 😬
