### ISSUE TITLE
"Save as Copy" breaks M2M Relations

### ISSUE THREAD

**Issue by erik-konrad** [directus/directus#6695]
### Describe the Bug

If I duplicate an entry in a table with M2M relations, the relation table makes an update, not a create. This removes the M2M relations from the parent / original entry and sets it to the copy.

### To Reproduce

Change an entry with a M2M relation, click the dots right from the save button and click "Save as Copy".

### What version of Directus are you using?

9.0.0-rc.83

### What version of Node.js are you using?

15.4.0

### What database are you using?

10.3.22-MariaDB-0+deb10u1

### What browser are you using?

Google Chrome

### What operating system are you using?

Windows 10 + WSL Debian

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
You can control what is copied with the following option under data model settings:

<img width="1023" alt="Screen Shot 2021-07-07 at 11 51 33 AM" src="https://user-images.githubusercontent.com/9141017/124738926-adeb7d80-df19-11eb-910c-0cce5906be42.png">

See https://github.com/directus/directus/issues/4434 for a long thread on all the different thoughts and angles that went into making that 🙂 

By default, the app will just copy what the API sends when you fetch the item. With the above settings, you can control what parts are copied. By configuring it to not copy the junction table ID, it'll create a new one on save, which results in what you're asking for above 👍🏻

**Comment by erik-konrad** [comment]
Aaahhhh, thank you very much :-) that works.
