### ISSUE TITLE
Calendar range render

### ISSUE THREAD

**Issue by bernatvadell** [directus/directus#6699]
### Describe the Bug

When u specify an entity with two Date's fields, if u select layout calendar, and pick start date & end date, the range rendered resolved without the end date.

### To Reproduce

Create an entity with two fields:

- start_date (type: Date)
- end_date (type: Date)

Configure a layout Calendar to work with that fields

Create a record with start date & end date filled.

Record example:
![image](https://user-images.githubusercontent.com/17298604/124748145-0a06cf80-df23-11eb-9dbe-3adf21da9187.png)

Calendar example:
![image](https://user-images.githubusercontent.com/17298604/124748283-31f63300-df23-11eb-93ba-559fcbf2cee0.png)

### What version of Directus are you using?

v9.0.0-rc83

### What version of Node.js are you using?

v16.3.0

### What database are you using?

postgres

### What browser are you using?

edge chromium

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
When setting end date to July 14th, the date range on the calendar will end July 14th 00:00:00, which is visually correct with your screenshot. Is that what you're referring too?

**Comment by bernatvadell** [comment]
in the calendar, when the field type is date (without time), I understand that the event should be marked from the start date to the end date (both inclusive)
