### ISSUE TITLE
Cannot read property 'TABLE_NAME' of undefined

### ISSUE THREAD

**Issue by wc-matteo** [directus/directus#6703]
### Describe the Bug

I think it happens because the query is violating a unique constraint, [here](https://github.com/directus/directus/blob/77e00b7db49cb35d724dd5d496fd4f65499d58af/api/src/exceptions/database/dialects/mssql.ts#L36). Only for some reason `constraintUsage` must be `undefined`.

in my case it happens when doing an `updateOne` call with the js sdk
![image](https://user-images.githubusercontent.com/10562635/124762323-1135d980-df33-11eb-90c5-d1e9eb51f91e.png)

### To Reproduce

violate a unique constraint

### What version of Directus are you using?

v9.0.0-rc.82

### What version of Node.js are you using?

n/a

### What database are you using?

mssql 2016

### What browser are you using?

chrome

### What operating system are you using?

win 10

### How are you deploying Directus?

k8s

**Comment by wc-matteo** [comment]
yes, so I'm using `updateOne` to update an existing record which also has a translation relation. I'm doing this:
```js
directus.items('foobar').updateOne(1, {
	x: 'a1',
	translations: [
		{
			languages_id: 'it-IT',
			y: 'b1',
		},
	],
})
```

There's a unique contraint for `(foobar_id, languages_id)` in `foobar_translations`. In this case the update first inserts the updated translation row then deletes the old one?

**Comment by rijkvanzanten** [comment]
> In this case the update first inserts the updated translation row then deletes the old one?

That's correct 👍🏻

**Comment by wc-matteo** [comment]
and what do you think of _first_ deleting the old records and then inserting the new/updated ones?

**Comment by rijkvanzanten** [comment]
That makes total sense and should be the way moving forward 👍🏻
