### ISSUE TITLE
Cannot view revisions as a restricted user

### ISSUE THREAD

**Issue by casey-chow** [directus/directus#6743]
### Describe the Bug

Revisions are not showing for restricted-access users.

<img width="310" alt="image" src="https://user-images.githubusercontent.com/378216/125137108-e083aa80-e0c0-11eb-8f96-b89ddf51da75.png">

I found the following error in the console:

```
TypeError: e.revision.activity is undefined
```

### To Reproduce

1. Create a user with partial permissions into a collection.
2. Create and save, update an entity as the user.
3. Open the revision history for the user for the entity. 

Here are the system permissions for the restricted user:

<img width="809" alt="image" src="https://user-images.githubusercontent.com/378216/125137497-a49d1500-e0c1-11eb-8784-2b105ef43990.png">

### What version of Directus are you using?

v9.0.0-rc.83

### What version of Node.js are you using?

14

### What database are you using?

Postgres 13

### What browser are you using?

Firefox 89.0.2

### What operating system are you using?

macOS Big Sur

### How are you deploying Directus?

Heroku

**Comment by Jason-CKY** [comment]
Hi I am still experiencing this exact issue where I am unable to view revisions made by other users, even though permissions to read revisions is set to all access.

The restricted user is only able to view part of the revisions that is made by the user himself, and not by other users. Is this supposed to be the case? If so, how do I give permissions for the user to view revisions made by other people? Admin users are able to view revisions made by all users, and I do not want to grant the user admin access just to view all revisions.

**Comment by rijkvanzanten** [comment]
@Jason-CKY What are the permissions you have configured for this role?

**Comment by Jason-CKY** [comment]
I solved the issue by overwriting the default item permissions in the activities system tables. :) 

![image](https://user-images.githubusercontent.com/27609953/126185651-a5ba13ee-ec66-4a10-933a-bf648b8883dd.png)

**Comment by MarvinXu** [comment]
> <img alt="image" width="310" src="https://user-images.githubusercontent.com/378216/125137108-e083aa80-e0c0-11eb-8f96-b89ddf51da75.png">

I have problem same as this. I add all permissions of `directus_revisions` for the role.
