### ISSUE TITLE
Keycloak SSO gives SERVICE_UNAVAILABLE error

### ISSUE THREAD

**Issue by phxgbl** [directus/directus#6749]
### Describe the Bug

I am trying to Authenticate Directus using the Keycloak OIDC server. My Oauth Config in .evn file is as follows
```
OAUTH_PROVIDERS="keycloak"
OAUTH_KEYCLOAK_KEY="directus-ui"
OAUTH_KEYCLOAK_SECRET="a1db583a-9aa5-4d4e-a727-47dd6d2deb8b"
OAUTH_KEYCLOAK_AUTHORIZE_URL="http://localhost:9090/auth/realms/Adapt/protocol/openid-connect/auth"
OAUTH_KEYCLOAK_ACCESS_URL="http://localhost:9090/auth/realms/Adapt/protocol/openid-connect/token"
OAUTH_KEYCLOAK_SCOPE="openid email"
OAUTH_KEYCLOAK_PROFILE_URL="http://localhost:9090/auth/realms/Adapt/protocol/openid-connect/userinfo"
```
When i try to login using keycloak provider ,  I am getting this error:
11:58:43 ✨ request completed GET 302 /auth/oauth/keycloak/callback?session_state=71f3e431-e486-4405-989f-83c769755020&code=d973de6a-6c22-4e01-b4c1-a891725fee60.71f3e431-e486-4405-989f-83c769755020.31203554-330b-444b-b866-3726cde36310 
No error is logged in Keycloak server
Please see the screens attached below.
[Screens.zip](https://github.com/directus/directus/files/6796468/Screens.zip)

### To Reproduce

try to connect to Keycloak using  settings

OAUTH_PROVIDERS="keycloak"
OAUTH_KEYCLOAK_KEY="directus-ui"
OAUTH_KEYCLOAK_SECRET="a1db583a-9aa5-4d4e-a727-47dd6d2deb8b"
OAUTH_KEYCLOAK_AUTHORIZE_URL="http://localhost:9090/auth/realms/Adapt/protocol/openid-connect/auth"
OAUTH_KEYCLOAK_ACCESS_URL="http://localhost:9090/auth/realms/Adapt/protocol/openid-connect/token"
OAUTH_KEYCLOAK_SCOPE="openid email"
OAUTH_KEYCLOAK_PROFILE_URL="http://localhost:9090/auth/realms/Adapt/protocol/openid-connect/userinfo"

![Screenshot from 2021-07-11 12-25-13](https://user-images.githubusercontent.com/37118923/125185568-3718f200-e243-11eb-9bc1-7f20150cc3ed.png)
![Screenshot from 2021-07-11 12-25-39](https://user-images.githubusercontent.com/37118923/125185571-384a1f00-e243-11eb-8f5e-053e073c5d2c.png)
will get the error 
![Screenshot from 2021-07-11 12-11-47](https://user-images.githubusercontent.com/37118923/125185586-5152d000-e243-11eb-9650-7ec428e76b55.png)
when try to login

### What version of Directus are you using?

v9.0.0-rc.83

### What version of Node.js are you using?

16

### What database are you using?

postgresql 13.2.1

### What browser are you using?

chrome

### What operating system are you using?

ubuntu 20.04

### How are you deploying Directus?

commandline(npx)

**Comment by phxgbl** [comment]
@rijkvanzanten  I think I found out the cause. I created a user in Keyclock which has the same email as the Directus Admin user. I was able to log in. To confirm the same I created another user in Directus using the email of an existing Keycloak user, that user was also able to log in. So my question is, do we have to create Directus and Keycloak user for this auth to work?

**Comment by phxgbl** [comment]
@rijkvanzanten  one more thing worth mentioning. I have multiple UI applications using SSO login under the same Keycloak server. The principle idea is that once login to any application can redirect to others without any further login. It works for other apps but for Directus it gets redirected to the login page.  but ironically, if we sign in to Directus first, can redirect to other applications without login. Any comments on that as well?

**Comment by rijkvanzanten** [comment]
> I think I found out the cause. I created a user in Keyclock which has the same email as the Directus Admin user. I was able to log in. To confirm the same I created another user in Directus using the email of an existing Keycloak user, that user was also able to log in. So my question is, do we have to create Directus and Keycloak user for this auth to work?

This is correct. Directus uses the sso provider as a way to authenticate an existing user into Directus. There's an in-works discussion/pr to implement the ability to automatically create new users on SSO login here: https://github.com/directus/directus/pull/3955

As for your second question, I have no idea. I have no experience with keycloak. I'm assuming they're setting some sort of cookie to authenticate into other apps, which isn't part of the oAuth spec as far as I'm aware.

**Comment by phxgbl** [comment]
Thanks, @rijkvanzanten. Below is the Browser authentication flow of Keycloak, As u said it will look for cookies first.
![Screenshot 2021-07-12 at 6 03 43 PM](https://user-images.githubusercontent.com/37118923/125288230-84788a80-e33b-11eb-8ceb-68eab405cb31.png)

sorry, I have one more doubt. I mean the reverse process is working,   if we sign in to Directus first, then I am able to redirect to other apps without login.  ie, the cookie-based auth is working I guess.    so will that be anything to do with the login code in  Directus?

**Comment by rijkvanzanten** [comment]
@phxgbl When you login to Directus, Directus itself will set a refresh cookie for Directus. That being said, Directus doesn't recognize the Keycloak cookie directly, so won't work if you don't login to Directus.

**Comment by phxgbl** [comment]
@rijkvanzanten, it's clear now. thanks for your time and help :)

**Comment by rijkvanzanten** [comment]
No problem! Do you happen to know if Keycloak relies on a standardized flow for setting this client cookie? Would be nice to officially support in Directus too 🙂

**Comment by phxgbl** [comment]
@rijkvanzanten AFAIK Keycloak adheres to standards.  The above image posted is the default 'browser authentication flow' that I followed for the testing.  But it's highly customizable and flexible. I will try to sort out the Directus Keycloak issue and give more insights on the same.

**Comment by phxgbl** [comment]
@rijkvanzanten  Sorry I missed updating you. Actually, Directus SSO aligns with standards, and it's working fine. All I had to is change the URL to something like `http://localhost:8050/auth/oauth/keycloak?redirect=http://localhost:8050/admin/collections` so that would redirect to the Keycloak server and if already authenticated by some other client will redirect back to the collections page without any login. This was required since Directus by default looks for Basic login instead of Oauth2.

**Comment by phxgbl** [comment]
@rijkvanzanten one more question, Can I add a column, let it be tenant_id programmatically, I mean when a user creates a collection, the column tenant_id should also get added.  Is it possible?

**Comment by rijkvanzanten** [comment]
That sounds unrelated to this issue, and is better asked on [Discord](https://directus.chat) or [Discussions](https://github.com/directus/directus/discussions).

That being said, yes, you can assign a "preset" value to the role permissions for the `create` action, and set the preset to `{ "tenant_id": "$CURRENT_USER" }`

**Comment by phxgbl** [comment]
sorry ... don't know ... I cannot make it work .. 
![Screenshot from 2021-07-21 22-29-10](https://user-images.githubusercontent.com/37118923/126529523-bf7328b8-1bf1-46e1-a534-fdffe0ee750b.png)
![Screenshot from 2021-07-21 22-31-09](https://user-images.githubusercontent.com/37118923/126529527-2ba8b398-a0ab-47f4-9e4f-331d9f965f36.png)
![Screenshot from 2021-07-21 22-31-57](https://user-images.githubusercontent.com/37118923/126529530-05b6077e-d244-4736-bb8b-7573e7c7ad73.png)
shall i open a new discussion?

**Comment by rijkvanzanten** [comment]
Yeah that's best 👍🏻
