### ISSUE TITLE
How to cancel file upload?

### ISSUE THREAD

**Issue by hellojayjay** [directus/directus#6752]
### Describe the Bug

when i use sdk, and use default transport(axios internal).but there is no CancelToken in sdk.axios, so how can i cancel an upload reuqest?

### To Reproduce

post /files, want to cancel this request

### What version of Directus are you using?

9.0.0-rc.83

### What version of Node.js are you using?

12.21.0

### What database are you using?

maybe do not care

### What browser are you using?

maybe do not care

### What operating system are you using?

maybe do not care

### How are you deploying Directus?

maybe do not care

**Comment by benhaynes** [comment]
Hey, thanks for asking. Just so you know, questions should be going into GitHub Discussions, Issues are reserved for bug reports.
