### ISSUE TITLE
Cannot login if setting admin email with ".local" domain

### ISSUE THREAD

**Issue by ansidev** [directus/directus#6762]
### Describe the Bug

Cannot login if setting admin email with ".local" domain

### To Reproduce

- Setting ADMIN_EMAIL using `.local` domain, ex: 'admin@example.local'
- Start Directus.
- Try to login and fails.

### What version of Directus are you using?

v9.0.0-rc.83 (Docker)

### What version of Node.js are you using?

Shipped with Docker image

### What database are you using?

MariaDB 10.5

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

docker-compose (locally)

**Comment by rijkvanzanten** [comment]
The email address needs to be a valid email. `.local` isn't a valid TLD, so the email address is invalid and can't be used with Directus.

**Comment by ansidev** [comment]
> The email address needs to be a valid email. `.local` isn't a valid TLD, so the email address is invalid and can't be used with Directus.

That 's right but not for local development, and even if you want to apply this point, you should improve these things:
- The message on error is not meaningful: "Wrong username or password". This is a bad message (wrong logical meaning) because it does not give the right information to the users, so it must be change.
- There are many application allow this email pattern on local development, so you should add a NOTICE to your document.

**Comment by rijkvanzanten** [comment]
Feel free to open a PR or two 👍🏻
