### ISSUE TITLE
Don't use tags interface for equals in CSV fields

### ISSUE THREAD

**Issue by domdus** [directus/directus#6778]
### Describe the Bug

Advanced filtering (in app) using a CSV field causes an HTTP 400 for the filter request.

My "tags" field is of type CSV.

Request made by the app when filtering for tag (string) "Interview":
`https://<domain>/items/articles?limit=25&fields[]=id&fields[]=image.modified_on&fields[]=image.type&fields[]=image.filename_disk&fields[]=image.storage&fields[]=image.id&fields[]=date_created&fields[]=tags&sort=-date_created&page=1&filter=%7B%22tags%22:%7B%22_eq%22:[%22interview%22]%7D%7D`

Error:
`[
  {
    "message": "The filter value for \"_eq\" has to be a string, number, or boolean",
    "extensions": {
      "code": "INVALID_QUERY"
    }
  }
]`

![image](https://user-images.githubusercontent.com/67951828/125456310-13a1af46-5d30-40eb-bf6b-f4c7ea8fdfa5.png)

### To Reproduce

- Create a field of type CSV in a collection and use interface "tags"
![image](https://user-images.githubusercontent.com/67951828/125459002-6b24bb3b-3b48-4fb6-8302-ba259d3137a8.png)
![image](https://user-images.githubusercontent.com/67951828/125459100-0b98fb14-aa6e-4a65-8ee4-599d8db78fc8.png)

- Assign any tags to your items, e.g.: "Interview"
- Use Advanced Filter on a CSV field (string) "Interview":
![image](https://user-images.githubusercontent.com/67951828/125455783-e0753b52-83e7-4dc4-97a8-9ca32b655ec6.png)

- On submission of the input (press return) nothing happens. Result list is not filtered, but the HTTP 400 is thrown - see description:
![image](https://user-images.githubusercontent.com/67951828/125455834-65e8e4a7-3a72-4389-88c8-a80f3019dc91.png)

### What version of Directus are you using?

v9.0.0-rc.83

### What version of Node.js are you using?

14.15.4

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying Directus?

PaaS

**Comment by rijkvanzanten** [comment]
Your filter is `&filter={"tags":{"_eq":["interview"]}}`, which isn't a string 🙂 

Try `&filter={"tags":{"_eq":"interview"}}` or `&filter={"tags":{"_contains":"interview"}}`

**Comment by domdus** [comment]
Hey @rijkvanzanten,

I'm talking about the directus app itself creating these requests/params, it's not me trying to build it.

Notice: There seems to be some ui change made in the past (past rc.78?). The advanced filter input for a CSV field allows multiple search values in a single filter:
![image](https://user-images.githubusercontent.com/67951828/125476123-f2bd241c-4926-454e-be21-f07eb008c6ef.png)

I guess that change probably causes the issue..?

**Comment by rijkvanzanten** [comment]
Ahh gotcha

**Comment by galdames** [comment]
The same happens for  json attributes
