### ISSUE TITLE
Can't install directus with npx create-directus-project

### ISSUE THREAD

**Issue by jfrancarioInera** [directus/directus#6786]
### Describe the Bug

I tried to follow the instructions to install Directus through cli command but unsuccessfully.
Here is the log:

> Need to install the following packages:
  directus
Ok to proceed? (y) y
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
(node:54764) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: npx directus init
    at makeError (/usr/local/share/.config/yarn/global/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/usr/local/share/.config/yarn/global/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Command.create (/usr/local/share/.config/yarn/global/node_modules/create-directus-project/lib/index.js:71:2)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:54764) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:54764) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate

### To Reproduce

Run `npx create-directus-project my-project`

### What version of Directus are you using?

9

### What version of Node.js are you using?

14

### What database are you using?

MySql

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
I noticed that your path for the installed modules seems to be Yarn's cache

/usr/local/share/.config/**yarn/global/node_modules**/create-directus-project/

Did you install using yarn?

**Comment by jfrancarioInera** [comment]
I tried with both npm and yarn. 
Didn't notice that, I'll try removing yarn and using only npm

**Comment by rijkvanzanten** [comment]
Thanks! I'll push a tweak that wraps that async execution so it at least shows a proper error 👍🏻

**Comment by uzziellite** [comment]
On Ubuntu 20.04, the error gets reproduced. On 18.04, the installation works smoothly.

**Comment by rijkvanzanten** [comment]
@jfrancarioInera Are you on ubuntu 20.04 too?

**Comment by jfrancarioInera** [comment]
@uzziellite Yes i am on ubuntu 20.04. I've tried disinstalling yarn and using only npxy
, but got the same result.
It's probably something related to the installation of the directus package, i get this if i try to install it on his own: 

> npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm ERR! code 1
npm ERR! path /home/james/node_modules/argon2
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/james/.npm/_logs/2021-07-16T07_29_12_054Z-debug.log

Could be something broken with my node and npm, but I tried a clean install with no results.

**Comment by rijkvanzanten** [comment]
Could it be that your ubuntu environment is missing some node/npm build tools? IIRC you need `build-essential` under ubuntu for node-gyp to build it's native extnesions

**Comment by jfrancarioInera** [comment]
> Could it be that your ubuntu environment is missing some node/npm build tools? IIRC you need `build-essential` under ubuntu for node-gyp to build it's native extnesions

Maybe this caused the issue.  I was using node installed with snap, maybe for this reason it couldn't detect the build essential package? I tried to reinstall node with sudo apt-get nodejs, it installed node 16.4.1 and the installation works. 
This or the problem was node 14.
I'll try to install node 14 without snap and see what happens

**Comment by jfrancarioInera** [comment]
Downgraded to node 14.17.3 with `npm install -g node@14.17.3` and the installation went through. The problem was with my installation of node through snap. 
Thanks, can close the issue.

**Comment by rijkvanzanten** [comment]
Thanks for confirming that!

**Comment by nilsarp** [comment]
Hi I was having the same issue but this time with keystone installtion downgraded king like work but I just did what node told me to was 
root@invierte-stellar-horizon-testnet:~# npm install -g node@14.17.3
npm --force install -g node@14.17.3 and "it works"
npm ERR! code EEXIST
npm ERR! path /usr/bin/node
npm ERR! EEXIST: file already exists
npm ERR! File exists: /usr/bin/node
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-05T17_30_35_642Z-debug.log
root@invierte-stellar-horizon-testnet:~# npm --force install -g node@14.17.3
npm WARN using --force Recommended protections disabled.

added 2 packages, and audited 3 packages in 4s

✔ What directory should create-keystone-app generate your app into? · my-app

✔ Installed dependencies with yarn.

🎉  Keystone created a starter project in: my-app

  To launch your app, run:

  - cd my-app
  - yarn dev

  Next steps:

  - Read my-app/README.md for additional getting started details.
  - Edit my-app/keystone.ts to customize your app.
  - Open the Admin UI (​http://localhost:3000​)
  - Open the Graphql API (​http://localhost:3000/api/graphql​)
  - Read the docs (​https://next.keystonejs.com​)
  - Star Keystone on GitHub (​https://github.com/keystonejs/keystone​)

root@invierte-stellar-horizon-testnet:~# cd my-app
root@invierte-stellar-horizon-testnet:~/my-app# yarn dev
yarn run v1.22.15
$ keystone-next dev
✨ Starting Keystone
⭐️ Dev Server Starting on http://localhost:3000
⭐️ GraphQL API Starting on http://localhost:3000/api/graphql
✨ Generating GraphQL and Prisma schemas
✨ sqlite database "keystone.db" created at file:./keystone.db
✨ Your database is now in sync with your schema. Done in 294ms
✨ Connecting to the database
✨ Creating server
✅ GraphQL API ready
✨ Generating Admin UI code
✨ Preparing Admin UI app

**Comment by rijkvanzanten** [comment]
Ehh I appreciate the competitive research, but this is Directus, not Keystone @nilsarp! I think you're in the wrong repo 😄
