### ISSUE TITLE
Mailgun integration doesn't work for EU region domains

### ISSUE THREAD

**Issue by kropsi** [directus/directus#6787]
### Describe the Bug

Mailgun US endpoint: api.mailgun.net
Mailgun EU endpoint: api.eu.mailgun.net

Here is refference: https://documentation.mailgun.com/en/latest/api-intro.html

It requires ability to set EMAIL_MAILGUN_HOST for the API as addition to:
EMAIL_MAILGUN_API_KEY
EMAIL_MAILGUN_DOMAIN

### To Reproduce

Setup mailgun domain for EU region and try to configure Directus for sending mails via Mailgun, you will get

> [INTERNAL_SERVER_ERROR] UNAUTHORIZED

### What version of Directus are you using?

v9.0.0-rc.83

### What version of Node.js are you using?

12

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

PaaS

**Comment by rijkvanzanten** [comment]
We'll have to add the `host` env var into here:

https://github.com/directus/directus/blob/3bc5f7ff4f532e819dd8ce827eb2991efc703132/api/src/mailer.ts#L37-L42

@kropsi Wanna open a PR for that? :)
