### ISSUE TITLE
Fix release pipeline

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#6798]
The improved build/release pipeline has a couple critical issues:

- [x] npm isn't authenticated as the correct user in the lerna publish step
- [ ] the ARM docker image fails building
- [x] node-oracledb prevents image from being built

ref: https://github.com/directus/directus/pull/6759, https://github.com/directus/directus/pull/6796 

@paescuj It seems like SQLite is trying to build the native dependencies from source, but fails doing so as Python isn't available on the image

cc @SeanDylanGoff @nickrum FWIW, the NPM token in the repo secrets is an [Automation Token](https://github.blog/changelog/2020-10-02-npm-automation-tokens/) tied to my account.

**Comment by SeanDylanGoff** [comment]
@rijkvanzanten OK let's debug the NPM issue first. I just tested with my own token, with this code: https://github.com/cynova/directus/blob/build-test/.github/workflows/release.yml
Can you maybe run this aswell? Should take < 1 min and we can exclude one possible error.

**Comment by rijkvanzanten** [comment]
> Should take < 1 min

It does mean pushing out new tags etc, not the quickest to do unfortunately. 

Would it be easier to add a new action that has a manual trigger just to check the npm whoami?

**Comment by SeanDylanGoff** [comment]
> > Should take < 1 min
> 
> It does mean pushing out new tags etc, not the quickest to do unfortunately.
Hmm OK true especially without messing up the history.
I used `git add --all && git commit -m test && git push && npx lerna version --exact --force-publish --yes patch` to test quickly.

> Would it be easier to add a new action that has a manual trigger just to check the npm whoami?
I guess that would also work

**Comment by SeanDylanGoff** [comment]
@rijkvanzanten About ARM: Should we maybe just disable this for now? 
Not sure if holding back rc-84 for it makes sense as there could be heaps of errors after the current one...

**Comment by rijkvanzanten** [comment]
Yeah, might not be a bad idea, though... I _think_ oracle, sqlite, and argon2 are the main dependencies that have a deeper native binding that needs building, so it might be worth fixing for Sqlite, and checking where that puts us
