### ISSUE TITLE
Caching with memcached throws errors

### ISSUE THREAD

**Issue by Moeriki** [directus/directus#6823]
### Describe the Bug

Caching with memcached throw errors in some cases.

<img width="667" alt="CleanShot 2021-07-15 at 15 35 43@2x" src="https://user-images.githubusercontent.com/38758/125797130-a5e5a66c-f5c0-4275-a894-d16a55a64afd.png">

I made a minimal reproducible.

### To Reproduce

```sh
git clone https://github.com/Moeriki/bug-directus-cache-memcached
cd bug-directus-cache-memcached/
docker-compose up -d
# wait like a minute
cat directus.sql | docker exec -i bug-directus-cache-memcached-db /usr/bin/mysql -u root --password=root directus
npm install
npx directus start
```

Open the [post item](http://localhost:8055/admin/collections/posts/1) and login with admin@example.com / admin.

### What version of Directus are you using?

9.0.0-rc.83

### What version of Node.js are you using?

14.16.0

### What database are you using?

mysql 5.7

### What browser are you using?

Firefox Developer Edition 90.0b12 (64-bit)

### What operating system are you using?

macOS

### How are you deploying Directus?

Not.

**Comment by rijkvanzanten** [comment]
> Caching with memcached throw errors in some cases.

Do you have a more specific example of when this happens exactly? I tried reproducing it, but it's seemingly working as expected on my end 🤔 

```
Caching with memcached throw errors in some cases.

**Comment by rijkvanzanten** [comment]
Nevermind! Found the problem 👍🏻
