### ISSUE TITLE
Can't update dependency 'stream-json', Because can't found dependency stream-chain@2.2.4

### ISSUE THREAD

**Issue by kroawen** [directus/directus#6850]
### Describe the Bug

npm ERR! notarget No matching version found for stream-chain@^2.2.4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'stream-json'

### To Reproduce

npm update

### What version of Directus are you using?

RC.83

### What version of Node.js are you using?

14.15.1

### What database are you using?

Mariadb 12.23

### What browser are you using?

Chrome

### What operating system are you using?

centos 

### How are you deploying Directus?

locally

**Comment by paescuj** [comment]
Can you please try again after running:
```bash
npm cache clean --force
```

**Comment by kroawen** [comment]
> Can you please try again after running:
> 
> ```shell
> npm cache clean --force
> ```

Yes, I run npm cache clean --force ,then update again, error info still exists:

xxx@iZwz94q6zra85xqio72esaZ di9]# npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.

[xxx@iZwz94q6zra85xqio72esaZ di9]# npm update
npm WARN deprecated querystring@0.2.0: The
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp@1.x: the non-scoped 'node-pre-gyp' package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! code ETARGET
npm ERR! notarget No matching version found for stream-chain@^2.2.4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'stream-json'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-16T09_54_54_167Z-debug.log

**Comment by rijkvanzanten** [comment]
Weird! `stream-chain` is a sub dependency of `stream-json`. `stream-chain@2.2.4` seems to be the latest that exists on NPM  https://www.npmjs.com/package/stream-chain

<img width="127" alt="CleanShot 2021-07-16 at 09 42 59@2x" src="https://user-images.githubusercontent.com/9141017/125957449-900ba08e-9a1e-4e08-991a-76caa7af4541.png">

Are you using any custom proxy to NPM or a non-standard mirror to NPM?

**Comment by rijkvanzanten** [comment]
I'll close this for now, as it doesn't seem to be a problem in the main Directus project. We can keep debugging here though 🙂
