### ISSUE TITLE
Cannot create a new item with ItemService.createOne (or even ItemService.create)

### ISSUE THREAD

**Issue by gustavodipietrogva** [directus/directus#6853]
### Describe the Bug

Hi,
I've already described te bug in https://github.com/directus/directus/issues/6315
At the time, I was experiencing it on rc.69. I just updated to rc.85 and I have the very same error you can see described in the referenced issue.

Basically the following code:

```javascript
const newcustomerSelectionId = await customerSelectionService.createOne({
  id: uuid(),
  name: shorlistName,
  user_created: 'ad9860ac-2b82-4629-88fd-695276677f2e'
});
```

Gives the error:

```sh
12:33:37 🐛 Value for field "user_created" can't be null.
```
It doesn't matter whether I put `user_created` in the dictionary or not since the error is always the same (hence, Directus doesn't auto-populate `user_created` as I'd expect if not passed, and ignores it if passed). The field `user_created` is defined as follows in a migration:

```javascript
  [...]
  await knex.schema.createTable(shortlistTable, (table) => {
    [...]
    table.uuid('user_created').notNullable();
    [...]

    table.foreign('user_created').references('id').inTable(directusUsersCollectionName);
  });
  [...]

  await knex('directus_relations').insert([
    {
      many_collection: shortlistTable,
      many_field: 'user_created',
      many_primary: 'id',
      one_collection: directusUsersCollectionName,
      one_primary: 'id',
    },
  ]);
  [...]

  await knex('directus_fields').insert([
    [...]
    {
      collection: shortlistTable,
      field: 'user_created',
      interface: 'select-dropdown-m2o',
      options: '{"template": "{{first_name}} {{last_name}}"}',
      display: 'related-values',
      display_options: '{"template": "{{first_name}} {{last_name}}"}',
      sort: 2,
      special: 'user-created',
    },
    [...]
  ]);
```

### To Reproduce

See the description

### What version of Directus are you using?

v9 rc.85

### What version of Node.js are you using?

 v15.14.0.

### What database are you using?

Mysql

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

 running locally

**Comment by rijkvanzanten** [comment]
Where is that code snippet? Is this in a custom hook? How can I reproduce this? How is the service initialized?

**Comment by rijkvanzanten** [comment]
Can you try updating your endpoint example to the following:

```js
module.exports = function registerEndpoint(router, { exceptions, services }) {
	const { ItemsService } = services;
	const { InvalidCredentialsException } = exceptions;

	router.get(
		'/test',
		async (req, res) => {
			const { accountability, schema } = req;

			if (!accountability.user) {
				throw new InvalidCredentialsException();
			}

			const testService = new ItemsService('test-table', {
				schema,
				accountability // <<<<<<< add this
			});

			await testService.createOne({
				name: 'test name',
			});

			res.json({
				data: 'ok',
			});
		}
	);
};
```

The user created transform is extracted from the current user who creates the item. If there's no user to create the item (eg service doesn't use accountability), then the user created column will be `null` which breaks your constraint

**Comment by gustavodipietrogva** [comment]
Thanks, @rijkvanzanten, this solved the issue. In other parts of the code `accountability` is always used, but here.
