### ISSUE TITLE
MariaDB on Linux creates query error

### ISSUE THREAD

**Issue by Kminkjan** [directus/directus#6854]
### Describe the Bug

When I try to install Directus on a MariaDB instance that's running on a linux OS. GET queries on collections will result in the following error message:

```
{
    "errors": [
        {
            "message": "select `testitems`.`id`, `testitems`.`status`, `testitems`.`testfield` from `testitems` where (`testitems`.`id` in (select *)) order by `testitems`.`id` asc limit 100 - ER_NO_TABLES_USED: No tables used",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}
```

I've made a clean directus instance using NPX on a MariaDB database. I've tried it on a Cent OS server, a docker image for MariaDB version 10.4.20 and on my local maching using a windows distribution. Then I've added a collection called testitems and executed the following API call:

`localhost:8055/items/testitems`

On the windows based database everything is well. But the linux based databases result in the error as described above.

### To Reproduce

The easiest way to reproduce it is using a MariaDB database (version 10.4.20) on a linux machine (or use the https://hub.docker.com/_/mariadb docker image, using the tag 10.4.20).

Then connect a directus instance and initialize it using npx directus init to that database. Create a collection an use the API to retrieve that collection.

e.g. `localhost:8055/items/testitems`

### What version of Directus are you using?

v9.0.0-rc.85

### What version of Node.js are you using?

14.17.0

### What database are you using?

MariaDB 10.4.20

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying Directus?

Locally

### Database dump
I will leave a database dump al well. This one works on the Windows db instance, but fails on the Linux db instance.

https://raw.githubusercontent.com/Kminkjan/directus-dump/main/dump.sql

**Comment by rijkvanzanten** [comment]
Odd! I fail to understand how the difference of Windows vs Linux would make the error show up, as they're both running Node and have the DB in a docker container (if i understand your op correctly) 🤔 

Are you making both requests as the same user? Does the table have any relationships associated with it?

The offending bit of SQL looks like it's trying to do the subquery to filter for a o2m parent for some reason

`from `testitems` where (`testitems`.`id` in (select *))`

**Comment by Kminkjan** [comment]
Thanks you for your reaction!

I've narrowed the issue down further and the issue is not the database, it's the Directus instance. So the specific instance of Directus that is running on one server is creating this error, regardles of the database it is connected to.

Might have to do something with the argon2 library, that I had to rebuild to get Directus running.

**Comment by rijkvanzanten** [comment]
> No idea where to start looking for what's making the instance on that machine create invalid SQL though.

The only thing I could think of is that one of the two instances uses a database instance that contains some corrupt data somehow. Are both using the same dump?

**Comment by Kminkjan** [comment]
Yes even if the two instances are using the same database the error occurs on the the one specific instance. Quite strange!
