### ISSUE TITLE
single file error

### ISSUE THREAD

**Issue by 3DIQE** [directus/directus#6877]
### Describe the Bug

when i created a signal file and do all step and setup it then i checked it and see some error :in interface and display didnt show any thing despoite, i setup it at begin
![image](https://user-images.githubusercontent.com/82942259/126143398-4b9ea876-9270-4ac0-aa73-b98f4c98d473.png)
![image](https://user-images.githubusercontent.com/82942259/126143424-f69e23a6-9656-47b2-ad83-449d4de09ae0.png)
![image](https://user-images.githubusercontent.com/82942259/126143450-705dae5d-6d0b-4832-950d-c1efe9500512.png)

### To Reproduce

1-create single file field
2-setup all steps

### What version of Directus are you using?

9.0.0-rc.69

### What version of Node.js are you using?

12.4.0

### What database are you using?

mysql 5.7.28

### What browser are you using?

chrome Version 91.0.4472.124

### What operating system are you using?

Linux

### How are you deploying Directus?

shared host

**Comment by rijkvanzanten** [comment]
@3DIQE Can you try updating to [the latest version](https://docs.directus.io/getting-started/support/#troubleshooting-steps)? We'll reopen is the problem still exists on the latest version 👍🏻
