### ISSUE TITLE
Auth0 Login Integration Not Completing Login Flow

### ISSUE THREAD

**Issue by dvanmali** [directus/directus#6897]
### Describe the Bug

Currently I am configuring my system to integrate with my [Auth0](auth0.com) login system. Through the docs, I added the following environment variables but the login system still doesn't complete the login flow. Instead, Directus redirects me to http://localhost:8055/admin/login?reason=SERVICE_UNAVAILABLE even though the Login Cookie is set in the Browser. (Prior similar issues #5680)

Is there something I'm missing?

```.env
      PUBLIC_URL: 'http://localhost:8055'
      OAUTH_PROVIDERS: 'auth0'
      OAUTH_AUTH0_KEY: 'xxxxxxxx'
      OAUTH_AUTH0_SECRET: 'xxxx-xxxx'
      OAUTH_AUTH0_AUTHORIZE_URL: 'https://<DOMAIN>.auth0.com/authorize'
      OAUTH_AUTH0_ACCESS_URL: 'https://<DOMAIN>.auth0.com/oauth/token'
      OAUTH_AUTH0_PROFILE_URL: 'https://<DOMAIN>.auth0.com/userinfo'
```

_**Also, I'm not sure how the user is tied internally to Directus, but the email field may not always be provided. I believe the unique key should be tied to a user_id instead.**_

### To Reproduce

**You can use this Local Dockerfile to help (fill in the xxxx and <DOMAIN> parts as needed)**

```docker-compose.yml
# Creates an environment system on the local machine for testing
# Uses a local Postgre image

version: '3.2'

services:

  database:
    container_name: database
    image: library/postgres:13
    volumes:
      - my-db:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:9.0.0-rc.85
    ports:
      - 8055:8055
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      # Local PostgreSQL Database
      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      PUBLIC_URL: 'http://localhost:8055'
      OAUTH_PROVIDERS: 'auth0'
      OAUTH_AUTH0_KEY: 'xxxxxxxx'
      OAUTH_AUTH0_SECRET: 'xxxx-xxxx'
      OAUTH_AUTH0_AUTHORIZE_URL: 'https://<DOMAIN>.auth0.com/authorize'
      OAUTH_AUTH0_ACCESS_URL: 'https://<DOMAIN>.auth0.com/oauth/token'
      OAUTH_AUTH0_PROFILE_URL: 'https://<DOMAIN>.auth0.com/userinfo'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'

networks:
  directus:

volumes:
  my-db:
    driver: local
```

### What version of Directus are you using?

9.0.0-rc.85

### What version of Node.js are you using?

Dockerhub Image (16-Alphine?)

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by leetosc** [comment]
I am running into a similar issue. I am trying to log in via microsoft Azure AD and it looks like it is coming back correctly but it is giving the SERVICE UNAVAILABLE error
```
03:37:39 ✨ request completed GET 302 /auth/oauth/microsoft?redirect=https://directus.leeto.dev/admin/login 21ms
03:38:02 ✨ request completed GET 302 /auth/oauth/microsoft/callback?code=0.AS4AVHHEtWPVjUKfGzIW4kNdFBr_ba0kyWpHv9eZi_s_Oe8uAAA.AQABAAIAAAD--DLA3VO7QrddgJg7Wevr3x5MjYcW9iUGdmfUm-4GzJH5_MjBPnvonXIXYyQA4-DuaikOc5OeNn1ITYEGgDzbFRSKDQlgbvytyOIkPT2w-jWmoRUFnp38YH9XX85R9lwEhwRFOaRNu0u6noTwGZtkIOZztElEvjC19D7VdJ_wAPu2DLDpphhJUZSgOjKhQTGXtFX_Dq9Vxsueoa-_46NTo-jvS3AnHcqzxVgqKESVoAKE_yONth1YZJxpfyqursX3Q148ry2ex6mzo1SSq367gRFK4P5EHNpuDCoZhJqlM7XnCFURkuZb0smcCzaC8RKlNhwH1Eh3iSOXhjwQ9VxR04i6lfFWrdxNMQZShwxswZIGZ45EYDYY1xWoF7CIOE2WvP9OI9p4Nsw7GRNa8jUf3AVe9KvOPzwlx0jm7rfR8JYx4KWpEmncrWMV71Kh_KLNt8xSiqM7CT6U0tKHnfMfkRtGG0_gH7QDRVQjDf88XKlu91P_RoWE2FmhebwXg8fNs9WTOjuD-qn8Sxg4--ZFpoZJeC37Mz8_LsNKI_0Ft0fxmSqmSQXSB-XT5j-1mj1dHDzsgxmboI0KlIknSzqYuUF6HM1jYxZStDHwKrpRInjkz0lt5Y4bgw-gRwveVCOhhFIDYnGTlPM9Sf5xO_fjqOCh17gclMehafGC3r_uJ0MxRpEuYQY755iGOHJiKwIgAA&session_state=7a04775b-18d6-4c4c-b49d-2ad676685a59 823ms
03:38:03 ✨ request completed GET 200 /admin/login?reason=SERVICE_UNAVAILABLE 1ms
```

**Comment by wc-davide** [comment]
I had the same issue and I fixed it by adding this env variable:
```
OAUTH_AUTH0_SCOPE=openid email
```

hope it helps 👍

**Comment by leetosc** [comment]
I have the following env variables set, but no luck: 

```
      OAUTH_PROVIDERS: "microsoft"

      OAUTH_MICROSOFT_KEY: "ad6dff1axxxxx"
      OAUTH_MICROSOFT_SECRET: "73b7c1b3xxxxxx"
      OAUTH_MICROSOFT_SCOPE: "openid email profile"
      OAUTH_MICROSOFT_AUTHORIZE_URL: "https://login.microsoftonline.com/b5c47154xxxxxx/oauth2/v2.0/authorize"
      OAUTH_MICROSOFT_ACCESS_URL: "https://login.microsoftonline.com/b5c47154xxxxxx/oauth2/v2.0/token"
```

**Comment by leetosc** [comment]
> I have the following env variables set, but no luck:
> 
> ```
>       OAUTH_PROVIDERS: "microsoft"
> 
>       OAUTH_MICROSOFT_KEY: "ad6dff1axxxxx"
>       OAUTH_MICROSOFT_SECRET: "73b7c1b3xxxxxx"
>       OAUTH_MICROSOFT_SCOPE: "openid email profile"
>       OAUTH_MICROSOFT_AUTHORIZE_URL: "https://login.microsoftonline.com/b5c47154xxxxxx/oauth2/v2.0/authorize"
>       OAUTH_MICROSOFT_ACCESS_URL: "https://login.microsoftonline.com/b5c47154xxxxxx/oauth2/v2.0/token"
> ```

I figured out my problem, it was due to my `OAUTH_MICROSOFT_SECRET` being incorrect, and after setting it correctly it worked.  I was only able to figure this out by building directus locally and adding some console logs in https://github.com/directus/directus/blob/main/api/src/controllers/auth.ts.  Maybe it would help others self-debug in the future if errors in this area showed up in the logs.

```
directus: grant response {
directus:   error: {
directus:     error: 'invalid_client',
directus:     error_description: 'AADSTS7000215: Invalid client secret is provided.\r\n' +
directus:       'Trace ID: 87e10da6-8ede-4c52-8196-2c8a994b8400\r\n' +
directus:       'Correlation ID: 940d51c9-30eb-41b9-81b9-0904cf5614b7\r\n' +
directus:       'Timestamp: 2021-07-31 16:48:20Z',
directus:     error_codes: [ 7000215 ],
directus:     timestamp: '2021-07-31 16:48:20Z',
directus:     trace_id: '87e10da6-8ede-4c52-8196-2c8a994b8400',
directus:     correlation_id: '940d51c9-30eb-41b9-81b9-0904cf5614b7',
directus:     error_uri: 'https://login.microsoftonline.com/error?code=7000215'
directus:   },
directus:   profile: { error: { error: [Object] } }
directus: }
directus: error ServiceUnavailableException [Error]: Couldn't extract email address from SSO provider response
directus:     at Object.getEmailFromProfile [as default] (/Users/denny/Projects/directustest2/api/src/utils/get-email-from-profile.ts:24:9)
directus:     at /Users/denny/Projects/directustest2/api/src/controllers/auth.ts:314:37
directus:     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
directus:   status: 503,
directus:   code: 'SERVICE_UNAVAILABLE',
directus:   extensions: { service: 'oauth', provider: 'microsoft' }
directus: }
```

**Comment by rijkvanzanten** [comment]
> Maybe it would help others self-debug in the future if errors in this area showed up in the logs.

Yeah totally. It sounds like most of these problems come down to a configuration problem or other

**Comment by rijkvanzanten** [comment]
@dvanmali The following configuration works for me with auth0:

```
OAUTH_PROVIDERS="auth0"

OAUTH_AUTH0_KEY="twfJx[redacted]bwK2c"
OAUTH_AUTH0_SECRET="ZocSB[redacted]4ZkYt"
OAUTH_AUTH0_AUTHORIZE_URL="https://rijk.us.auth0.com/authorize"
OAUTH_AUTH0_ACCESS_URL="https://rijk.us.auth0.com/oauth/token"
OAUTH_AUTH0_PROFILE_URL="https://rijk.us.auth0.com/userinfo"
OAUTH_AUTH0_SCOPE="array:openid,email"
```

Auth0 doesn't return the email in the profile response by default, so you have to explicitly request it in the scope. The referenced PR above vastly improves the error logging in stdout on failed sso login, so this should be easier to debug moving forwards.

**Comment by mp-itconsulting** [comment]
The bug is still existing. AUTH0 configured correctly (like dvanmali) but still got the reply "Invalid user credentials" and redirected to "../admin/login?reason=INVALID_USER"
Attributes are retrieved from AUTH0 but email seems not to be verified. Other apps with similar settings are working fine.
Tested also with several scope definitions: "openid email", "array:openid,email" or ["openid","email"]. But no success at all

Kr
Michael
