### ISSUE TITLE
HTML <small> in the documentation

### ISSUE THREAD

**Issue by RSickenberg** [directus/directus#6905]
### Describe the Bug

![image](https://user-images.githubusercontent.com/16922548/126460879-361301b9-b7ca-4940-b351-c65e9b8cd2c4.png)

We can see some HTML characters in the doc (as well on the `.md`).

### To Reproduce

Just go to `docs/guides/api-hooks`

### What version of Directus are you using?

9.0.0-rc.85

### What version of Node.js are you using?

Docker image with node 16.5.0

### What database are you using?

MariaDB

### What browser are you using?

Chrome 91

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by benhaynes** [comment]
I'm not sure when/why it stopped working, but these `<small>` tags were creating the "Extension" badge. We shouldn't remove them, we should figure out why that CSS isn't rendering now.

**Comment by paescuj** [comment]
@benhaynes Thanks for your feedback. Closing #6909 in favor for a real fix, then.

**Comment by rijkvanzanten** [comment]
@benhaynes Looks like raw HTML in that markdown is escaped instead of rendered as an element (which makes sense, as all MD in the app is sanitized by default) (these are the in-app docs, not the web-docs)
