### ISSUE TITLE
SDK and API accept user invite don't match (Post and Patch)

### ISSUE THREAD

**Issue by MajesteitBart** [directus/directus#6915]
### Describe the Bug

Accepting a user invite with the SDK doesn't work correctly. I'm not sure if the request should be using patch or post, as the documentation is not consistent. In the SDK it seems like patch, but in the API docs, its described as Post. 

The error received is `Status Code: 404 Not Found`

### To Reproduce

Create an invite, using the correct invite URL, try to accept the invite on the page that matches this URL. Response is 404.

### What version of Directus are you using?

9.0.0.rc85

### What version of Node.js are you using?

14.17.0

### What database are you using?

Postgres 10.17

### What browser are you using?

Edge Chromium

### What operating system are you using?

Linux

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
The docs are correct, it's `POST /users/invite/accept`.

**Comment by rijkvanzanten** [comment]
Wanna open a PR? Should be a quick fix 🙂 

https://github.com/directus/directus/blob/d487f691a3d5c3f9acfd1a3027ec840506966452/packages/sdk/src/handlers/invites.ts#L20-L23

**Comment by paescuj** [comment]
Fixed in #6925
