### ISSUE TITLE
Reset Password Form giving "Invalid Payload"

### ISSUE THREAD

**Issue by dwene** [directus/directus#6927]
### Describe the Bug

Reset password flow on RC-85 appears broken. After clicking the link and filling out the new password, the form gives a validation error "Invalid Payload"

Inspecting the network the real error is:
 `{"errors":[{"message":"\"token\" field is required.","extensions":{"code":"INVALID_PAYLOAD"}}]}`
 
 But looking at the payload it appears the token is being passed in the body.
 
 ```
 {"password":"password","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlcmVrQGxhbWJkYWN1cnJ5LmRldiIsInNjb3BlIjoicGFzc3dvcmQtcmVzZXQiLCJpYXQiOjE2MjY5NjQ2MDIsImV4cCI6MTYyNzA1MTAwMn0.2lsiTBvy46Tswc9YHPNq1zfvUwimOWqIwO0Bb7l-06Y"}
 ```
 
Screenshots:

<img width="481" alt="Screen Shot 2021-07-22 at 9 37 03 AM" src="https://user-images.githubusercontent.com/12628251/126657948-cc558da9-24e3-4e68-a556-1c5c48ef4fe4.png">
<img width="719" alt="Screen Shot 2021-07-22 at 9 37 43 AM" src="https://user-images.githubusercontent.com/12628251/126657953-dd525a8c-ad1c-4239-b1b0-8c9df6d4c657.png">
<img width="1438" alt="Screen Shot 2021-07-22 at 9 38 00 AM" src="https://user-images.githubusercontent.com/12628251/126657959-0caa7234-9f5d-4dcc-bc8a-5d8964d1501c.png">

### To Reproduce

Using Directus 9.0.0-rc-85, go through the reset password flow, attempt to update your password and receive the error indicated above.

### What version of Directus are you using?

9.0.0-rc-85

### What version of Node.js are you using?

Whatever is in the Directus docker image

### What database are you using?

Mariadb latest

### What browser are you using?

Brave

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by aidenfoxx** [comment]
Fixed this in an upcoming PR.

**Comment by ravolta-io** [comment]
Any ETA for when this will be merged? This issue is blocking launch of a project. Thanks!

**Comment by aidenfoxx** [comment]
@ravolta-io It's marked to be released with rc87. Since rc86 went out a couple of days ago I'd assume at least another week, but it might be earlier.

**Comment by ravolta-io** [comment]
@aidenfoxx Thanks for the reply! Hmm, another week will be tough for me. Is there a way I can fix it myself until RC87 releases? I tried looking at the Directus codebase in node_modules, but changing stuff there doesn't seem to work.

**Comment by aidenfoxx** [comment]
If you're manually deploying the project you can modify the "node_modules/directus/dist/controllers/auth.js" file, and that should work until your next `npm install`. If you're using a container or some kind of automated deployment, then it'll be difficult to workaround.

The fix can be seen here, where the 2 validation statements were missing the `typeof` qualifier. https://github.com/directus/directus/pull/6942/files#diff-2e0966802490ef6b64754924c1f0da2807f05359551e77bf115ce40384d56e0fR201

**Comment by ravolta-io** [comment]
@aidenfoxx I'll try that and see if it works. Thanks for your quick replies! Loving Directus so far :)

**Comment by rijkvanzanten** [comment]
I might cherry pick the fix so we can close/release it a little faster while we get the bigger modular auth overhaul reviewed and merged 👍🏻

**Comment by ravolta-io** [comment]
It seems this change isn't present in my version. 
Tried:
- Tweaking the auth.js file with the same fix (still errors)
- Reinstalling Directus from scratch

Is there something I'm missing?
Thanks! :)

**Comment by rijkvanzanten** [comment]
I just fixed it in the main branch a couple hours ago, it will be included in the next release
