### ISSUE TITLE
Column "Footer" should always be on

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#693]
We should be able to remove the "Footer" option from the Settings page, and have it controlled at the column level... or just ALWAYS be on for the numeric data-types (INT, FLOAT, etc).

We'd remove this option:
![screen shot 2015-03-08 at 3 26 59 pm](https://cloud.githubusercontent.com/assets/522079/6547204/de01d772-c5a7-11e4-956e-76be02c4f3c3.png)

And either add it at the field level here, or ALWAYS have it on (no Settings to toggle):
![screen shot 2015-03-08 at 3 30 11 pm](https://cloud.githubusercontent.com/assets/522079/6547219/51ff7d32-c5a8-11e4-8859-acd3a20b52fc.png)

I think ALWAYS ON might be easier... but let me know.

**Comment by benhaynes** [comment]
@WellingGuzman This one relates to this issue:
https://github.com/RNGR/Directus/issues/694

Hopefully we can remove both these fields (Footer and Junction Table)

**Comment by benhaynes** [comment]
@WellingGuzman I think for now we can just have the footer default to on (no field level control yet). This will simplify the Settings interface and give useful footer info all the time.

**Comment by WellingGuzman** [comment]
@benhaynes cool then, for now it would be ALWAYS ON for any numeric field. Working on it.

**Comment by WellingGuzman** [comment]
I'll close it, later when we want to implement it by field level, or similar, we can reopen it.

Any thoughts @benhaynes ?

**Comment by benhaynes** [comment]
@WellingGuzman Much better! Though the footer item itself seems to be displaying in the wrong column. Also, it would be nice if it were below the table (not the last row with highlighting)... is there a way to do this? I know it needs to technically be in the table for column spacing... but perhaps it can _appear_ below by using a negative bottom margin or something?

![screen shot 2015-08-17 at 11 34 59 am](https://cloud.githubusercontent.com/assets/522079/9308893/91e3a56c-44d4-11e5-8e7c-1a42247c4cb0.png)

**Comment by WellingGuzman** [comment]
@benhaynes you want it to be separate like, having a space between the footer and the last row?

**Comment by benhaynes** [comment]
@WellingGuzman Yeah, ideally. So that little "speech bubble" goes below the table/card view.

**Comment by WellingGuzman** [comment]
@benhaynes This still on the table but looks like it's out of the table.

What do you think?
![screen shot 2015-08-17 at 12 15 51 pm](https://cloud.githubusercontent.com/assets/1531291/9309714/6e7b6d4e-44d9-11e5-9bda-1d843e7048db.png)

**Comment by benhaynes** [comment]
perfection!

**Comment by benhaynes** [comment]
Looks great! At some point we should adjust the page padding so the page height doesn't "jump" when you roll-over the footer bubble. But that's a small change!

**Comment by WellingGuzman** [comment]
Hey @benhaynes, now I'm seeing this on M2M UI table.

![screen shot 2015-08-19 at 11 47 19 pm](https://cloud.githubusercontent.com/assets/1531291/9375260/a4d47a30-46cc-11e5-92bd-d455287007ce.png)

_I'm checking why is this appearing on a non-numeric column._ But my question is, is this footer also need to be visible on M2M UI  table as well?

**Comment by benhaynes** [comment]
Hey @WellingGuzman – This footer should only exist on listing pages, not on UI/detail pages. We should disable it there if possible.

**Comment by WellingGuzman** [comment]
@benhaynes we should be good now. closing it.

**Comment by benhaynes** [comment]
Let's disable the footer for now – it needs to be column-level (not table-level) which is why we're running into issues with this.
