### ISSUE TITLE
Relational fields go missing on save as copy

### ISSUE THREAD

**Issue by Alluuu** [directus/directus#6963]
### Describe the Bug

When editing an item, which has a model with relational fields, then save as copy creates a copy but that copy no longer has relations the original one had. The relations in question are of type many-to-many.

### To Reproduce

Create a new directus instance.
Create a model with standard fields to be used for relations.
Create a model with standard fields and a many-to-many relationship to the previously created model.
Create an item for the relational field model.
Create an item for the main one, using that relationship in many to many, created previously.
Save.
Then edit created item, keeping relationships.
Save as Copy.
When viewing the newly created item, the relationships are no longer there.

### What version of Directus are you using?

v9.0.0-rc.83

### What version of Node.js are you using?

v12.22.1

### What database are you using?

MySQL8

### What browser are you using?

Chrome, Safari, any

### What operating system are you using?

Windows 10, Mac OS, problem exists in all

### How are you deploying Directus?

Docker, but problem exists in local as well.

**Comment by rijkvanzanten** [comment]
Use the "Item Duplication Fields" option in the collection settings to control what is and isn't copied when using the Save as Copy feature

**Comment by Alluuu** [comment]
@rijkvanzanten I have all the fields selected in the data model "Item Duplication Fields" Except ID, but definitely including the relational fields

**Comment by rijkvanzanten** [comment]
@Alluuu What's the configuration you're using right now? What are you trying to achieve?

From what you're saying

> then save as copy creates a copy but that copy no longer has relations the original one had

it sounds like it's using the original existing row ID for the junction table, which effectively moves over the relationship instead of copying the content of the row. Try deselecting the ID column of the junction table record, leaving everything else enabled

**Comment by stouch** [comment]
I have the same problem. Even by delecting ID column (https://github.com/directus/directus/issues/4434#issuecomment-970860920)

**Comment by stouch** [comment]
Do you think we could re-open this ?

**Comment by rijkvanzanten** [comment]
@stouch no, lets open a new issue 👍🏻
