### ISSUE TITLE
Admin role - 'no user' option shouldn't be there

### ISSUE THREAD

**Issue by arladmin** [directus/directus#6990]
### Describe the Bug

While experimenting on my local directus instance, i created a new role and added myself, the only admin, to it, without knowing that a user can belong to only one role at a time. Surprisingly, i got added to the new role and got removed from the Admin role! Now my directus instance is without an admin user and i can't access any of the admin stuff, anymore  :-/ 

My suggestion: removing the only user from the Admin role should never be possible.

### To Reproduce

1. Local directus docker setup, with only 1 user who is also the admin
2. Create a new role
3. Add the above user to the new role and save
4. The Admin role becomes empty

### What version of Directus are you using?

9.0.0-rc.86

### What version of Node.js are you using?

16.5.0

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by supermx1** [comment]
Makes sense. Never tried this but I always had the fear

**Comment by rijkvanzanten** [comment]
It already limits you from changing your last admin role from the user detail page, just missed the users o2m on the roles page 👍🏻
