### ISSUE TITLE
rc86 Route / doesn't exist

### ISSUE THREAD

**Issue by neo7-studio-web** [directus/directus#6993]
### Describe the Bug

After upgrade to rc86 

Error accessing App with JSON message : 
Route / doesn't exist
ROUTE_NOT_FOUND
`Error: Route / doesn't exist.\n    at notFound (/home/aimerdieu/domains/backend.aimerdieu.fr/aimerdieu/node_modules/directus/dist/controllers/not-found.js:25:14)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

### To Reproduce

Upgrade to rc86, access App

### What version of Directus are you using?

v9.0.0-rc86

### What version of Node.js are you using?

12.18.1

### What database are you using?

MySQL

### What browser are you using?

Firefox

### What operating system are you using?

CentOS

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
How are you running Directus? What's the value for `NODE_ENV`? What are your configuration values for `ROOT_REDIRECT` and `SERVE_APP`?

https://docs.directus.io/reference/environment-variables/#general

**Comment by neo7-studio-web** [comment]
I'm running Directus locally on CentOS with pm2
`ROOT_REDIRECT` and `SERVE_APP` are not set.

Error appears with `NODE_ENV` set to `development`
But is OK with `NODE_ENV` set to `production`
