### ISSUE TITLE
Advanced filter not working

### ISSUE THREAD

**Issue by supermx1** [directus/directus#7026]
### Describe the Bug

Can't select any fields.

https://user-images.githubusercontent.com/9326922/127254080-5df46c98-c77e-41fe-9b10-426ff7de5b0b.mp4

### To Reproduce

Open advanced filter and try to select any field

### What version of Directus are you using?

RC.86

### What version of Node.js are you using?

14.15.3

### What database are you using?

10.4.17-MariaDB - Source distribution

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
Duplicate of https://github.com/directus/directus/issues/7004
