### ISSUE TITLE
Translated words are not translated

### ISSUE THREAD

**Issue by dimitrov-adrian** [directus/directus#7033]
### Describe the Bug

Translated phrases in the yaml files are not recognized and displayed. 

### To Reproduce

Just check for "delete" somewhere in the interface, for example in Bulgarian or most of the languages have it translated.

It seems that the issue is come from yaml importing in 

https://github.com/directus/directus/blob/206f2380b52c2b9faba7ffe33fa6dba7e25c214d/app/src/lang/set-language.ts#L25

As `translations.delete` is always empty, it seems that such reserved words cannot be used here with yaml import

Ref: https://github.com/rollup/plugins/blob/8748b8cd3bbab3c5ac6190556930219f19060e63/packages/pluginutils/src/makeLegalIdentifier.ts#L4

### What version of Directus are you using?

rc86

### What version of Node.js are you using?

16

### What database are you using?

sqlite

### What browser are you using?

chrome

### What operating system are you using?

macos/linux

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
What a wonderfully edge-case specific bug. Thanks for the heads up!

**Comment by rijkvanzanten** [comment]
@nickrum another wonderful rollup quirk
