### ISSUE TITLE
Errors are not logged

### ISSUE THREAD

**Issue by m0rtis0** [directus/directus#7039]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Only HTTP 200 requests are shown in Directus output, no errors are logged, despite the web app not responding correctly, regarding to bug #7004 . My filters don't work, but unlike @nickluger I do not get any errors.

### To Reproduce

Install the newest directus version

Set logging level to "trace"

Produce errors on purpose

No errors shown in console

### What version of Directus are you using?

v9.0.0-rc.86

### What version of Node.js are you using?

14.16.0

### What database are you using?

Postgres 13.3

### What browser are you using?

Brave, Firefox

### What operating system are you using?

Linux (Arch Linux)

### How are you deploying Directus?

local

**Comment by rijkvanzanten** [comment]
Are you on `v9.0.0-rc.68` or `v9.0.0-rc.86`? 🙂

**Comment by m0rtis0** [comment]
> Are you on `v9.0.0-rc.68` or `v9.0.0-rc.86`?

v9.0.0-rc.86

**Comment by rijkvanzanten** [comment]
How are you running Directus locally? fwiw, when I set `LOG_LEVEL="trace"` it seems to work as expected on my end 🤔 (using `npm run dev`)

**Comment by m0rtis0** [comment]
Okay, weird. I used `npx create-directus-project` and then I use `npx directus start` to run

**Comment by rijkvanzanten** [comment]
What error are you causing on purpose? 

> Produce errors on purpose

I'd like to reproduce exactly what you're seeing 🙂

**Comment by m0rtis0** [comment]
Sure :smile: I just try to add advanced filters which should produce an error in this version, this error specifically:

```
runtime-core.esm-bundler.js:218 Uncaught TypeError: Cannot read property '0' of undefined
    at addFilterForField (filter-sidebar-detail.vue:146)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164)
    at emit (runtime-core.esm-bundler.js:993)
    at _createBlock.onClick._cache.<computed>._cache.<computed> (field-list-item.vue:5)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164)
    at HTMLLIElement.invoker (runtime-dom.esm-bundler.js:349)
```

**Comment by rijkvanzanten** [comment]
Ohhhhhh yeah! That doesn't show up in the error logs on the API, as that error didn't happen on the API side 🙂 

It was a JavaScript bug that only happened in the Vue app 👍🏻

**Comment by m0rtis0** [comment]
> Ohhhhhh yeah! That doesn't show up in the error logs on the API, as that error didn't happen on the API side 
> 
> It was a JavaScript bug that only happened in the Vue app 👍🏻

Ahh, that makes sense! How do I set up a dev environment to receive these errors?

**Comment by rijkvanzanten** [comment]
Client-side errors aren't sent to the server currently, so there's no flag to enable them to show up there somehow

**Comment by m0rtis0** [comment]
> Client-side errors aren't sent to the server currently, so there's no flag to enable them to show up there somehow

OMG I am stupid :smile: .It was in the browser debug console all the time, of course as it is a javascript error :D 
Thanks for your help anyways!

I have found another bug regarding conditional fields, will open an issue

**Comment by rijkvanzanten** [comment]
Thanks!
