### ISSUE TITLE
Cannot click/interact with Checkboxes or Dropdowns in Field Groups (Dividers)

### ISSUE THREAD

**Issue by m0rtis0** [directus/directus#7047]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Changing the value of a checkbox or Dropdown in a Field Group that is configured to Divider mode only works once, changing it back does not work, nothing happens when you click

![ezgif com-gif-maker](https://user-images.githubusercontent.com/65440078/127364676-26cec25b-d125-4fc2-9e22-cb3469b0968c.gif)

### To Reproduce

- Install the latest directus version
- Create a collection
- Create a field group with mode "divider"
- Create a dropdown or checkbox field
- Create new element
- Try to change the value of the dropdown twice

### What version of Directus are you using?

~~v9.0.0-rc.68~~ v9.0.0-rc.86

### What version of Node.js are you using?

14.16.0

### What database are you using?

Postgres 13.3

### What browser are you using?

Brave, Firefox

### What operating system are you using?

Linux (Arch Linux)

### How are you deploying Directus?

local

**Comment by m0rtis0** [comment]
Oh no, not again the version ,... :trollface:

**Comment by rijkvanzanten** [comment]
Can you share the setup of this dropdown field? I tried it on my end, but it seems to work as expected

**Comment by m0rtis0** [comment]
:+1:
