### ISSUE TITLE
List 'context' parameter availability in hooks

### ISSUE THREAD

**Issue by arladmin** [directus/directus#7064]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

This is my hook file:
```
module.exports = function registerHook({ exceptions, services }) {
    return {
         'items.update': async function (input, context){
            if(input) console.log('I\n',input);   //1.
            if(context) console.log('C\n',context);   //2.
            return input;
        },
    };
```
The output produced is only for the first console.log statement and not the second.
Also, the output contains all the properties of the ```context``` parameter, like ```  event, accountability, collection, item, action, payload, schema, collections, relations, permissions, database ``` instead of the expected ```input``` properties.

The output is fine though, for the ```items.update.before``` handler function:

```
module.exports = function registerHook({ exceptions, services }) {
    return {
         'items.update.before': async function (input, context){
            if(input) console.log('I\n',input);   //1.
            if(context) console.log('C\n',context);   //2.
            return input;
        },
    };
```

Haven't yet checked for other scopes and actions.

### To Reproduce

1. Create a hook file.
2. Create a handler function as shown above.
3. Update an item.
4. Check the docker container's console.

### What version of Directus are you using?

v9.0.0-rc.87

### What version of Node.js are you using?

16.5.0

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
Only the `before` hooks have the additional `input` parameter, as they're called synchronously and allow for updating the `input` before it's being saved. The regular hooks don't have the input parameter, as the crud operation is already done.

**Comment by arladmin** [comment]
@rijkvanzanten Thanks for the information!

**Comment by rijkvanzanten** [comment]
I'll leave it open as a reminder to add a note to the docs 🙂
