### ISSUE TITLE
Can't start the local dev environment. Error: connect ECONNREFUSED 127.0.0.1:8055

### ISSUE THREAD

**Issue by maxacarvalho** [directus/directus#7068]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

After following the instructions [here](https://docs.directus.io/contributing/running-locally/), the application won't load.

This is probably a silly mistake, something basic that I'm missing.  
Everything works as expected until I try to open the local app `http://localhost:8080/admin/`, the database tables were created correctly and everything else seems to work as fine as it should, but, apparently, there's no connection to the API.

The `api/.env` is the standard one, the only thing I changed was the `DB_PASSWORD` variable.

From the console, I can see an error when I try to load the app:
```
@directus/app: 10:00:02 AM [vite] http proxy error:
@directus/app: Error: connect ECONNREFUSED 127.0.0.1:8055
@directus/app:     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1142:16) (x6)
```

### To Reproduce

Simply follow the *Running Locally* steps [here](https://docs.directus.io/contributing/running-locally/)

### What version of Directus are you using?

latest `main` branch

### What version of Node.js are you using?

v16.5.0

### What database are you using?

PostgreSQL

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Running locally

**Comment by maxacarvalho** [comment]
I might have found the solution for my own issue. I guess I had to start the `api` from within the `api` dir by running `npm run dev` there as well?

**Comment by paescuj** [comment]
I've noticed this too. It happens when running `npm run dev` for the first time.
An modified files is detected and the api then fails to restart (I guess...):
```
directus: [INFO] 12:25:09 Restarting: [...]directus/packages/shared/dist/cjs/constants/extensions.js has been modified
```

Simply stopping the process and running `npm run dev` again solves this problem.

You can use this as a workaround 😄:
```bash
(npm run dev & pid=$!; sleep 10 && kill $pid) && sleep 5 && npm run dev
```

**Comment by maxacarvalho** [comment]
Hi @paescuj 

I got it working by running `npm run dev` from **inside** the `api` directory, and then running `npm run dev` again from the root directory. So I ended up having two tabs open, running `npm run dev`, one from the `api` and one from the `root`.

Are you saying that it should be enough to run `npm run dev` **only** from the `root directory`?

Thanks.

**Comment by paescuj** [comment]
> Are you saying that it should be enough to run `npm run dev` **only** from the `root directory`?

Yes, but as I wrote you need to run it twice in a row.

**Comment by maxacarvalho** [comment]
Thanks @paescuj it worked!

**Comment by paescuj** [comment]
@maxacarvalho You're welcome! In my opinion, you can keep this issue open since it's something which should get fixed...

**Comment by maxacarvalho** [comment]
@paescuj makes sense

**Comment by rijkvanzanten** [comment]
@paescuj I don't think it's something we can fix tbh, it's a problem upstream in the watching of ts-node-dev which gets overloaded by the changes in the sub dependencies. 

One solution would be to update the docs to use `npm run dev -- --scope directus --scope @directus/app` instead of just `npm run dev`. That'll skip the watching on all the sub-packages, which alleviates a lot of process overhead (and cpu usage for that matter) on things that will most likely not be worked on

**Comment by paescuj** [comment]
> @paescuj I don't think it's something we can fix tbh, it's a problem upstream in the watching of ts-node-dev which gets overloaded by the changes in the sub dependencies.
> 
> One solution would be to update the docs to use `npm run dev -- --scope directus --scope @directus/app` instead of just `npm run dev`. That'll skip the watching on all the sub-packages, which alleviates a lot of process overhead (and cpu usage for that matter) on things that will most likely not be worked on

I see! Thanks for updating the documentation! This is going to make contributors life a bit easier 😄👍

**Comment by joelbqz** [comment]
Guys, I'm having this issue again:

```
@Directus#5887/app: 10:23:37 AM [vite] http proxy error:
@Directus#5887/app: Error: connect ECONNREFUSED 127.0.0.1:8055
@Directus#5887/app:     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16)
``` 

Node v16.9.0

I already did what @paescuj and @rijkvanzanten but isn't working in this case :(

**Comment by joselcvarela** [comment]
@joelbqz if you follow exactly how it's described here you should be fine: https://docs.directus.io/contributing/running-locally/

if you encounter any problem you would need to share more information in order to help you.

**Comment by joelbqz** [comment]
hey @joselcvarela thanks for the quick response! basically It was working the last week, I'm working on a pull request and received a response yesterday, so I pulled the latest changes from main into the branch I'm working on https://github.com/directus/directus/pull/7906

I already removed node_modules on all folders, did npm install, npm run build, then I run the following dev command:

`npm run dev -- --scope directus --scope @directus/app`

![image](https://user-images.githubusercontent.com/19965325/133292296-9aee5c77-9aab-4419-8a36-d556121b525b.png)

**Comment by rijkvanzanten** [comment]
@joelbqz Make sure to merge the latest from `main` into your branch, and try again 🙂

**Comment by joelbqz** [comment]
@rijkvanzanten my branch `feature/event-auth.jwt.before` is up to date with `main`

**Comment by joselcvarela** [comment]
I think the problem is that you are running app before the api.
Try to run the api first with `npm run dev -- --scope directus` and wait until you see this:
![image](https://user-images.githubusercontent.com/14039341/133294284-0dc4e85d-1c74-4db8-ae5a-9fc3371994f8.png)

Then run the app with `npm run dev -- --scope @directus/app`

**Comment by joelbqz** [comment]
Thanks, @joselcvarela @rijkvanzanten sorry guys, my mistake is I was merging the latest from `origin/main` instead of `upstream/main` Its working perfectly now! 

Best!!
