### ISSUE TITLE
Not possible to access  /admin/collections

### ISSUE THREAD

**Issue by kropsi** [directus/directus#7069]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Not possible to access /admin/collections after manipulating module navigation for a role. The screen is white and there is an error
![CleanShot 2021-07-29 at 11 39 43](https://user-images.githubusercontent.com/946662/127469668-fccb7287-32f8-4e6f-bad2-1b8b4dee7633.png)

I tried to delete module navigation for that role, but now the normal /collections are affected by this.
I moved the user to another role and the user was able to access /collections, but when moved back to the original role the experience was again the same the access was damaged

### To Reproduce

1. Create a new role
2. Assign a user
3. Create module navigation "data" to "/collections"
4. Login with a user

Not able to reproduce again.

### What version of Directus are you using?

  v9.0.0-rc.87

### What version of Node.js are you using?

v12.22.3

### What database are you using?

Postgres 13

### What browser are you using?

Chrome, Safari, Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

App Platform (DO)

**Comment by rijkvanzanten** [comment]
> Not able to reproduce again.

That makes it difficult to.. reproduce!

@kropsi Does your current instance still show this behavior? Could you share the configuration for "collection listing" for that particular role?

**Comment by kropsi** [comment]
@rijkvanzanten yes I know. The only way to fix this issue was to delete the role which naturally that removed the problem. It is of course not a solution for anything. After that, I was not able to reproduce this behaviour again. Let's close it. I can re-open it again if I will be able to destroy it again. The bug can reappear.

**Comment by rijkvanzanten** [comment]
That works!
