### ISSUE TITLE
Enabling redis cache causes directus  broken.

### ISSUE THREAD

**Issue by hermesalvesbr** [directus/directus#7076]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When start the redis, the directus broken.

npm notice New minor version of npm available! 7.19.1 -> 7.20.2,
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.20.2>,
15:17:51 ✨ request completed GET 304 /admin/img/icons/safari-pinned-tab.svg 6ms,
npm notice Run `npm install -g npm@7.20.2` to update!,
15:17:51 🚨 error select "directus_users"."id", "directus_users"."first_name", "directus_users"."last_name", "directus_users"."email", "directus_users"."password", "directus_users"."location", "directus_users"."title", "directus_users"."description", "directus_users"."tags", "directus_users"."avatar", "directus_users"."language", "directus_users"."theme", "directus_users"."tfa_secret", "directus_users"."status", "directus_users"."role", "directus_users"."token", "directus_users"."last_access", "directus_users"."last_page", "directus_users"."prefeitura", "directus_users"."secretaria" from "directus_users" where "directus_users"."id" = $1 order by "directus_users"."id" asc limit $2 - column directus_users.prefeitura does not exist ,
error: select "directus_users"."id", "directus_users"."first_name", "directus_users"."last_name", "directus_users"."email", "directus_users"."password", "directus_users"."location", "directus_users"."title", "directus_users"."description", "directus_users"."tags", "directus_users"."avatar", "directus_users"."language", "directus_users"."theme", "directus_users"."tfa_secret", "directus_users"."status", "directus_users"."role", "directus_users"."token", "directus_users"."last_access", "directus_users"."last_page", "directus_users"."prefeitura", "directus_users"."secretaria" from "directus_users" where "directus_users"."id" = $1 order by "directus_users"."id" asc limit $2 - column directus_users.prefeitura does not exist,
npm notice ,
15:10:55 ⚠️  PUBLIC_URL is not a valid URL,
    at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:287:98),
15:10:56 ✨ Server started at port 8055,

### To Reproduce

When I use directus with redis it breaks. When using directus with redis disabled, it works normally on v.rc.87. It's a strange thing, since directus shouldn't have any relationship with the redis cache and stop working.

### What version of Directus are you using?

v9.0.0-rc.87

### What version of Node.js are you using?

node --version v16.5.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS, Windows

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
@hermesalvesbr Is this no longer a problem?

**Comment by hermesalvesbr** [comment]
Sorry for this issue. The problem was in redis. The redis was mixing cache data.
