### ISSUE TITLE
Relational Field value display gets corrupted when filter is applied

### ISSUE THREAD

**Issue by arladmin** [directus/directus#7081]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Whenever any filter is applied to a relational field, the display values of the said field go from normal to ```[object object]```.

See: https://www.loom.com/share/d663e8e9727c4849957024f5f49a9fc9

### To Reproduce

1. Create a collection with a relation to another collection.
2. Filter the 1st collection on the basis of any criteria on the relational field.

### What version of Directus are you using?

v9.0.0-rc.87

### What version of Node.js are you using?

16.5.0

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by Nitwel** [comment]
You can temporarly fix this by setting the display of the `list` field to "Related Values" and select the id for the display template.

**Comment by Oreilles** [comment]
Closing this issue as it seems to be fixed as of v9.0.1.

**Comment by Oreilles** [comment]
Closing this issue as it seems to be fixed as of v9.0.1.
