### ISSUE TITLE
Can't read fields in o2m nested in m2a field

### ISSUE THREAD

**Issue by Kinbaum** [directus/directus#7086]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

After upgrading from rc.86 to rc.87, my simple query no longer works.

```gql
{
    pages {
        slug
        # This is a M2O relationship
        featured_benefits {
            name
            # This is a M2A relationship
            highlights {
                id
                item {
                    ... on cards {
                        featured
                        # `translations` field is causing the issue as of rc.87
                        # When this field is omitted, it returns data
                        translations {
                            title
                        }
                    }
                }
            }
        }
    }
}
```

After executing this query, the server responds with:

```json
{
    "errors": [
        {
            "message": "Cannot read property 'fields' of undefined",
            "locations": [
                {
                    "line": 2,
                    "column": 5
                }
            ],
            "path": [
                "pages"
            ]
        }
    ],
    "data": {
        "pages": null
    }
}
```

Now if I query for my cards collection directly, I am able to return the data without issue:

```gql
{
    cards {
        featured
        # This works no problem
        translations {
            title
        }
    }
}
```

I have also tried this using REST instead of GraphQL. Here is the endpoint to return the same depth of information:
`/items/pages?fields=*.*.*.*%20&deep={%20"translations":%20{%20"_filter":%20{%20"languages_code":%20{%20"_eq":%20"en-US"%20}}}}`

When hitting this endpoint, the server responds with:

```json
{
    "errors": [
        {
            "message": "An unexpected error occurred.",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}
```

### To Reproduce

There is information I'm unable to share here, but I've listed out the types of relationships that should hopefully make the reproduction of this straightforward. There is no custom code involved here. 

As I mentioned above, this worked as of rc.86. This seems to be related to translations of the collections. 
When I query for `translations { __typename }` at that deepest level, the query executes, but the translations return `null`. This would explain the error when I try to access the properties of that translations object.

### What version of Directus are you using?

v9.0.0-rc.87

### What version of Node.js are you using?

16.5.0

### What database are you using?

SQLite

### What browser are you using?

Chrome - Testing GQL queries through Altair

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
Are you logged in as a user when making this request? What are the permissions for this request?

**Comment by Kinbaum** [comment]
I am sending an anonymous request, but have enabled everything as read

**Comment by rijkvanzanten** [comment]
I can't seem to reproduce this on a fresh installation. Could you share a DB dump where this is happening?

**Comment by filipproch** [comment]
I am having the same issue, although with PostgreSQL as my database.
After enabling verbose logging this is the output:

```
21:45:32 🔍 [14.292ms] select "ip_access" from "directus_roles" where "id" is null limit $1 [1]
21:45:32 🔍 [14.092ms] select * from "directus_permissions" where "role" is null []
21:45:32 ✨ request completed POST 200 /graphql 71ms
```

and the response from the server

```
{
  "errors": [
    {
      "message": "Cannot read property 'fields' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "pages"
      ]
    }
  ],
  "data": {
    "pages": null
  }
}
```

my query

```
query {
  pages {
    content {
      sections {
        item {
          __typename
          ... on page_sections_large_headline {
            title
          }
        }
      }
    }
  }
}
```

the request is as an anonymous user on a "Many to Any" collection

---

in sense of permissions, my Public role has read access to all custom collections
and Directus Files (double checked)

**Comment by rijkvanzanten** [comment]
@filipproch Would you be able to share a database dump where this is happening? Either here or on rijk@directus.io 🙂

**Comment by filipproch** [comment]
@rijkvanzanten sent
