### ISSUE TITLE
Fix SDK usage of Auth (JSON vs Cookie, Static vs Dynamic)

### ISSUE THREAD

**Issue by kees-tce** [directus/directus#7112]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] #8942

### Describe the Bug

Not sure if it is supposed to work but when I copy paste the advanced example from the SDK docs [here](https://docs.directus.io/reference/sdk/#advanced-example) it fails to run and errors out at await auth.refresh()

### To Reproduce

Copy paste the advanced solution and try to run it.

### What version of Directus are you using?

RC86

### What version of Node.js are you using?

Na

### What database are you using?

Na

### What browser are you using?

All

### What operating system are you using?

Na

### How are you deploying Directus?

Na

**Comment by rijkvanzanten** [comment]
Seeing that that example starts with `WARNING: OK, not exactly a warning, but this isn't needed at all.`, I figured it was a little less confusing to just _not_ have that (broken) example in there at all. Was there anything in the regular examples you were trying to do but got stuck on @kees-tce?

Groetjes!

**Comment by j3n57h0m45** [comment]
@rijkvanzanten
ok, so with the advanced example gone... how can I set up the directus authentication to force "json" - while keeping Transport and Storage as the default values?

**Comment by kees-tce** [comment]
> @rijkvanzanten
> ok, so with the advanced example gone... how can I set up the directus authentication to force `json` - while keeping Transport and Storage as the default values?
> 
> The `json` mode is quite useful if utilizing directus auth within 3rd party apps (such as svelte).

@rijkvanzanten this was exactly what I was also trying to achieve, so I guess this is the answer to your question above :)

**Comment by keesvanbemmel** [comment]
Bump @rijkvanzanten :)

Of in mooi Nederlands: vergeet-me-nietje!

**Comment by j3n57h0m45** [comment]
This it what I use in a svelte project. However you need to make sure that the `window` object is available or `LocalStorage()` will fail.

```javascript
import { Directus, Auth, LocalStorage, AxiosTransport } from '@directus/sdk'

let sdk = {}

const url = ''
const storage = new LocalStorage() // : new MemoryStorage()
// Transport used to communicate with the server.
const transport = new AxiosTransport(url, storage, async () => {
  await auth.refresh() // This is how axios checks for refresh
})
const options = {
  mode: 'json',
  refresh: { auto: true, time: 3000}
}
// Auth is how authentication is handled, stored, and refreshed.
const auth = new Auth(transport, storage, options)
sdk = new Directus(url, { auth, storage, transport })

export { sdk }
```

**Comment by keesvanbemmel** [comment]
> ```js
> // This is how axios checks for refresh
> ```

Thanks for this! However, the problem with this example (and the one in the docs) is that your line which says "// This is how axios checks for refresh" gives me "compile" errors because "auth" is not available there.

**Comment by rijkvanzanten** [comment]
@keesvanbemmel 😄 

![image](https://user-images.githubusercontent.com/9141017/131760495-ff214f0d-5586-41a6-956f-091064f74a5c.png)

**Comment by jacobrienstra** [comment]
Hello all, working on fixing the auth for the SDK, and thought I'd outline the scenarios for which we want it to work, so we can better triage how it will work.

1. **Static Token** (great, very easy to do)
+ **Email and Password**
    + Browser
        4. Auto refresh just works, uses cookies
        5. Auto refresh just works, uses jwt
        6. Manual refresh/token management
    + Nodejs
        6. Auto refresh just works, uses jwt
        7. Manual refresh/token management
        
Does this seem like it covers everything? Are there any customizations people may want to make that this wouldn't allow for?
I think the problem before was that the defaults for Transport or Storage weren't created usually. I'm not sure we need a use case for custom Transport, honestly, but I could be wrong.

**Comment by rijkvanzanten** [comment]
> Does this seem like it covers everything?

I believe these three would cover all the use cases, yeah

>  I'm not sure we need a use case for custom Transport, honestly, but I could be wrong.

I agree with that. We can just make axios an internal dependency. No need to overcomplicate that.

**Comment by joselcvarela** [comment]
Hello all,
After studying a bit the SDK these are my conclusions:
- Is very flexible, since it allows developers pass their custom handlers for almost everything;
- Has default handlers in case users do not pass them
- The default handler for authentication tries to do refreshes automatically. In my opinion, this is a good point.

So, in the end, my suggestion is to just to handle this:
```js
sdk.auth.mode = 'json'
```

Let me hear your thoughts @rijkvanzanten .

**Comment by joselcvarela** [comment]
@rijkvanzanten yeah I think that too.
Although, what they were talking is about the `mode` passed to `Auth`. This defines if SDK should use `cookies` or `jwt`. By default, it uses `cookies` for browser and `jwt` for environments without `window` like Node.js.
My suggestion is expose everything on `directus` instance.
By default, this should work
```js
const sdk = new Directus('http://localhost:8055', 'static_token')
// OR
// const sdk = new Directus('http://localhost:8055')
// await sdk.auth.login({email, password})
await sdk.items('articles').readMany();
```


But for a more configurable way, we could provide this:
```js
const sdk = new Directus('http://localhost:8055')
sdk.auth.mode('json').autoRefresh(true).deltaTime(3000)
sdk.auth.storage.prefix('_my_app_')
```

**Comment by rijkvanzanten** [comment]
There's no reason why we couldn't have both tho! I do believe however that for the 80/20 case it's easier to have a single config object to initialize with, and then have the methods available to adjust later on if you ever have the use case to change the values after the fact 👍🏻
