### ISSUE TITLE
External Storage (DigitalOcean Spaces) integration is not working

### ISSUE THREAD

**Issue by arladmin** [directus/directus#7114]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Even after configuring all the environmental parameters for using an external S3 based storage, DigitalOcean Spaces in this case, the storage doesn't become available to be used in the app.

My (partial) config:
```
STORAGE_LOCATIONS=digitalocean,local

STORAGE_DIGITALOCEAN_DRIVER=s3
STORAGE_DIGITALOCEAN_ROOT=Directus

STORAGE_DIGITALOCEAN_KEY=key
STORAGE_DIGITALOCEAN_SECRET=secret
STORAGE_DIGITALOCEAN_BUCKET=bucket_id
STORAGE_DIGITALOCEAN_REGION=region
STORAGE_DIGITALOCEAN_ENDPOINT=https://region.digitaloceanspaces.com
#STORAGE_DIGITALOCEAN_ACL
```

### To Reproduce

In a fresh Directus, docker instance, configure the external storage parameters in the .env file.

In the Directus app, access ```Project Settings > Storage Default Folder``` , the Digital Ocean spaces is not available.

Also, if the ```local``` option is removed from ```STORAGE_LOCATIONS``` in the .env and then a file is tried to upload from the app, the logs show an error:
```
14:53:50 🚨 The "path" argument must be of type string. Received null
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at new NodeError (node:internal/errors:370:5)
    at validateString (node:internal/validators:119:11)
    at Object.join (node:path:1172:7)
    at AmazonWebServicesS3Storage._fullPath (/directus/node_modules/@directus/drive-s3/dist/AmazonWebServicesS3Storage.js:39:56)
    at AmazonWebServicesS3Storage.exists (/directus/node_modules/@directus/drive-s3/dist/AmazonWebServicesS3Storage.js:86:25)
    at /directus/node_modules/directus/dist/controllers/assets.js:42:67
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### What version of Directus are you using?

v9.0.0-rc.87

### What version of Node.js are you using?

16.5.0

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
The app only uses the first configured storage adapter (https://docs.directus.io/guides/api-config/#file-storage) 👍🏻

**Comment by arladmin** [comment]
> The app only uses the first configured storage adapter (https://docs.directus.io/guides/api-config/#file-storage) 👍🏻

@rijkvanzanten i'm a bit confused here. 
1. This https://docs.directus.io/guides/api-config/#multiple-storage-adapters says that i can "choose where files are being uploaded on a file-by-file basis. "
2. Even if i do set my config for DigitalOcean only, like so:
```
STORAGE_LOCATIONS=DIGITALOCEAN
```
and then try to upload the file, i see this error:
![image](https://user-images.githubusercontent.com/64059154/127755205-fab5c6b6-b35b-4623-a990-afe5482bcc22.png)

```
00:14:02 ⚠️  Couldn't save file ba883816-f956-49f3-a242-bf1c7afe4667.jpg
00:14:02 ⚠️  E_UNKNOWN: An unknown error happened with the file Directus/ba883816-f956-49f3-a242-bf1c7afe4667.jpg.

Error code: InvalidArgument
Original stack:
InvalidArgument: null
    at Request.extractError (/directus/node_modules/aws-sdk/lib/services/s3.js:714:35)
    at Request.callListeners (/directus/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/directus/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/directus/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/directus/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/directus/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /directus/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/directus/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/directus/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/directus/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
00:14:02 ✨ request errored POST 503 /files 283ms
```
3. Additionally, if i set my config to use both, 
```
STORAGE_LOCATIONS=DIGITALOCEAN,local
```
There's no option available in the App to upload a file to the chosen storage places, as mentioned in the above link.
Just the error from 2. repeats itself.

**Comment by ConnorSimply** [comment]
If it helps, these are my .env variables and Spaces set-up that works.

ENV Variables
`
STORAGE_LOCATIONS="DIGITALOCEAN"

STORAGE_DIGITALOCEAN_DRIVER="s3"

STORAGE_DIGITALOCEAN_KEY="redacted"
STORAGE_DIGITALOCEAN_SECRET="redacted"
STORAGE_DIGITALOCEAN_BUCKET="redacted"
STORAGE_DIGITALOCEAN_REGION="sfo3"
STORAGE_DIGITALOCEAN_ENDPOINT="sfo3.digitaloceanspaces.com"
STORAGE_DIGITALOCEAN_ROOT="./storage"
STORAGE_DIGITALOCEAN_PUBLIC_URL="/storage"
`
Digital Ocean
![image](https://user-images.githubusercontent.com/12714889/127802934-7373b363-7a45-4591-8c8d-683808d24168.png)

**Comment by arladmin** [comment]
@ConnorSimply Thanks a lot, finally got it working!

```
STORAGE_DIGITALOCEAN_ROOT="./storage"
STORAGE_DIGITALOCEAN_PUBLIC_URL="/storage"
```

These are the 2 ENV parameters that are missing from the docs, which were responsible for making this work.

**Comment by arladmin** [comment]
Hi @rijkvanzanten , could you tell me if there's any existing way to resolve this:
> **Would still like to find out, if someone has an insight, about this:**
> - how to set the path(s3 'key' property) for the file being uploaded to DO or AWS?
>   A key parameter is not available in the File Object and there doesn't seem any other way to determine the file's path.

?

Thanks.

**Comment by rijkvanzanten** [comment]
@arladmin I'm not sure what key you're talking about

**Comment by arladmin** [comment]
> @arladmin I'm not sure what key you're talking about

So, while searching for a way to upload files to a specific folder in the external S3 storage, i came across this:
https://stackoverflow.com/questions/51214518/upload-files-to-a-specific-folder-in-the-bucket-with-aws-sdk
where it mentions the usage of the key/path to upload the file to its destination.

I assumed that this must already be handled in the Directus code, but i couldn't find any parameter in the API (https://docs.directus.io/reference/api/system/files/#files) that corresponds with this 'key/path' property, or any other such property where i can set the complete path for my file.

**Comment by rijkvanzanten** [comment]
@arladmin The root environment variable sets the folder where files are uploaded. You can't specify further nested folders at this point

**Comment by arladmin** [comment]
@rijkvanzanten yeah, all the files are getting dumped in the root folder itself. 
I don't suppose there's some temporary workaround i could use to upload files in nested folders, is there?

**Comment by rijkvanzanten** [comment]
You could set the root path to be any folder: `STORAGE_DIGITALOCEAN_ROOT="/path/to/my/files"`

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/directus/pull/7170/commits/1828f7508b5716867ea0b2eaa8179d1c975d4683
