### ISSUE TITLE
Create demo site for framework

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#712]
To properly assess the framework, users need to be able to easily _use_ it (not just install it on their server). I suggest we build an online demo version with the following features:

* Non-admin user – screenshots will have to suffice for Settings area
* All data get's deleted every hour or so – might even be better if the whole system reinstalls every hour on a cron.
* Restrict hard-delete permissions
* Dummy schema that best reflects a typical install
* Build on separate server so it's sandboxed from marketing and dev sites

@WellingGuzman Let's chat about any concerns you might have with this, how we'll approach it, and when it can be ready for.

**Comment by benhaynes** [comment]
I need to wrap up this schema.

**Comment by liegeandlief** [comment]
Is this demo site being created? Love the idea of Directus and would love to be able to test it without the hassle of setting up the environment.

**Comment by benhaynes** [comment]
Hey @liegeandlief – we've been working on an exciting new Directus platform, but will wrap up a demo site soon (just finalizing a good schema that showcases all the features). I'll follow up here when it's complete.

**Comment by liegeandlief** [comment]
Thanks @benhaynes - can't wait to see the new platform!

**Comment by WellingGuzman** [comment]
@benhaynes Hey, are we still on with this one? or should we close this?

**Comment by benhaynes** [comment]
Now that we have a free online trial we don't need a demo. But we should add a more complete example schema into the install.

**Comment by Addvilz** [comment]
I would be nice to have a demo still. Not at all keen to give CC details just to evaluate it.

**Comment by benhaynes** [comment]
We'll have one eventually, but this is not a priority for our small team of developers. In the meantime, if you don't want to use a credit card you can download the free and open-source version.
