### ISSUE TITLE
New icon fields default to Search Icon

### ISSUE THREAD

**Issue by abertay-university** [directus/directus#7120]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When creating new items such as the Input Interface, where an Icon selection is available, the icon defaults to the search icon.

### To Reproduce

Create a new field that can have an icon

### What version of Directus are you using?

9.0.0r87

### What version of Node.js are you using?

14

### What database are you using?

MySQL

### What browser are you using?

Chrome, Safari, Firefox

### What operating system are you using?

MacOS

### How are you deploying Directus?

locally

**Comment by benhaynes** [comment]
Haha, I don't know if this is actually true... though I understand the confusion. I think what's happening here is that we SHOW the search icon to tell the user they can search for icon names... then that swaps out when one is selected. 

However, that search icon is not _selected_ and won't save, it's just being used for display. Any thoughts on how this could be made clearer?

**Comment by abertay-university** [comment]
I probably should have included screenshots. 

This is how it shows by default
![image](https://user-images.githubusercontent.com/31690037/127874907-48f91cbb-54ed-4200-a22c-3330c85dd273.png)

If I click the X (deselect), it appears like this:
![image](https://user-images.githubusercontent.com/31690037/127875039-b0485ac3-3fcd-4853-8f48-17d614acf665.png)

You'll see the class is set to .has-value:
![image](https://user-images.githubusercontent.com/31690037/127875378-131eda63-1d90-4bc6-9817-b73982989786.png)

I would expect it to be like this which conforms to the other fields around it:
![image](https://user-images.githubusercontent.com/31690037/127875586-5a756636-7b45-46e8-b115-1f9cdb6a7f44.png)

**Comment by abertay-university** [comment]
I can confirm when creating a new field, the search Icons are not added by default. So it's just cosmetic.
![image](https://user-images.githubusercontent.com/31690037/127876233-f79016be-819b-4b3f-9c25-9420b67cdcef.png)

**Comment by benhaynes** [comment]
Oh, weird! Here's what I see:

![Screen Shot 2021-08-02 at 10 18 37 AM](https://user-images.githubusercontent.com/522079/127876251-c9a4f2f3-d6bd-4ec0-8ee4-c5861b02d023.png)

But your config screenshots certainly look off... and that's quite confusing.

**Comment by benhaynes** [comment]
Can you confirm this still happens in Incognito mode (with no browser extensions)? @abertay-university

**Comment by abertay-university** [comment]
Same for incognito. I also just tested Firefox on another computer (windows) and have the same issue.

**Comment by rijkvanzanten** [comment]
<img width="990" alt="CleanShot 2021-08-02 at 10 32 31@2x" src="https://user-images.githubusercontent.com/9141017/127878102-88b66a79-8369-4259-bc5c-5fa1a852060f.png">

Can confirm the `search` thing on the interface options 👍🏻

**Comment by abertay-university** [comment]
Yay, nice to know it's not just me.

**Comment by benhaynes** [comment]
Haha, maybe because my Chrome is yelling at me to _Update_! Maybe a browser update is causing this?

**Comment by rijkvanzanten** [comment]
Could be! Could also be a quirk in the default values for the input options, though then I would've expected you to see it too
