### ISSUE TITLE
Use of layouts components inside extensions 

### ISSUE THREAD

**Issue by Guiqft** [directus/directus#7129]
Since the Vue3 migration, layouts components are initialized by using the `useLayout()` composable, which is not exposed to extensions.

The usage of layouts components inside extensions fill a lot of use cases so I think that a fix could be great.

_Originally posted by @Guiqft in https://github.com/directus/directus/discussions/7063_

**Comment by rijkvanzanten** [comment]
We'll keep #7063 as the feature request for this feature 👍🏻
