### ISSUE TITLE
Wrong cache-key generated for different requests

### ISSUE THREAD

**Issue by mscbpi** [directus/directus#7137]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Hi,

We have a deployment with REDIS cache enabled. 

It used to work well with Directus rc69.

Upgrading to 87 with cache enabled does not work: API request always get same response as first call whatever filter/parameter we set.

CACHE_ENABLED set to false recovers a normal behavior.

We are using Azure Redis (also before).

Thanks a lot for you help

### To Reproduce

CACHE_STORE=true
CACHE_ENABLED=true
CACHE_REDIS=redis://...

(Azure Redis)

`flushall` redis

postman request to API <directusUrl>/items/<collection>?filter[language]=en

Change the filter value
re-run the request
observe the result

=>  it will provide the same as first result, resulting in unusable data.

### What version of Directus are you using?

v9.0.0rc87

### What version of Node.js are you using?

from docker image 

### What database are you using?

Postgres 11

### What browser are you using?

Chrome, Safari

### What operating system are you using?

macOS, Windows, iOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/directus/pull/7139

**Comment by mscbpi** [comment]
Wow that was fast @rijkvanzanten
