### ISSUE TITLE
Duplicate field error

### ISSUE THREAD

**Issue by Alv-sys** [directus/directus#7146]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Hi,
First of all, let me tell you I am new to using Directus and I am very impressed with the concept, I really love it.
I am trying to discover everything I can to start to use it with actual clients, and I had the following issue duplicating a divider:

![image](https://user-images.githubusercontent.com/47535920/127918647-957a432c-4514-4201-9154-4f22c4632258.png)

It seems to be blocked, but I realized the click worked, even when seems not to be possible by having the Stop Icon on Hover.

Once duplicated, I positioned the field in the middle of the rest of the inputs, but the Divider always kept the position on the bottom, with the same text, even after I modified it. 

After that, I created a new Divider and deleted the previous (the duplicate), but now I can see the position modification I did was applied:
![image](https://user-images.githubusercontent.com/47535920/127919761-ef9f2a7c-9c76-4473-8056-ccc8b5aac0e2.png)

But the field is not anymore:
![image](https://user-images.githubusercontent.com/47535920/127920341-7a2e8a35-da90-4b72-90da-59ae6b117a91.png)

I restarted the project several times and I am not using cache.

### To Reproduce

1.- In the Datamodel Create a Divider Field
2.- Duplicate the Divider Field (it is possible to do it even having the block cursor icon)
3.- Modify the position and check if it was applied in the Collection View
4.- Return to the Datamodel and delete the duplicated Divider Field
5.- Check again the Collection, the deleted field should be still showing

### What version of Directus are you using?

9.0.0-rc87

### What version of Node.js are you using?

16.5.0

### What database are you using?

10.4.11-MariaDB

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
@Alv-sys Is this no longer a problem?

**Comment by Alv-sys** [comment]
Hey @rijkvanzanten , I closed when I saw the new version was released. I can't confirm is having the weird behavior I posted in the new version,  but I can see the duplicate button is still triggering the action, even when is blocked.
