### ISSUE TITLE
Support dynamic variables in conditional fields filter rules

### ISSUE THREAD

**Issue by christianrr** [directus/directus#7157]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I have experienced an issue when using dynamic variable in a field condition, e.g.

```
{
    "_and": [
        {
            "user_created": {
                "_eq": "$CURRENT_USER"
            }
        },
        {
            "acceptance": {
                "_neq": "accepted"
            }
        }
    ]
}
```
### To Reproduce

1. Create collection with an user_created field
2. Create a string field with name "acceptance"
3. Create a string field with name "conditional" with the following condition:
```
{
    "_and": [
        {
            "user_created": {
                "_eq": "$CURRENT_USER"
            }
        },
        {
            "acceptance": {
                "_neq": "accepted"
            }
        }
    ]
}
```

4. Create new entry, type something -> field is still visible

5. When the field condition is changed to 
```
{
    "acceptance": {
        "_neq": "accepted"
    }
}
```
the field gets hided as intended.

### What version of Directus are you using?

v9.0.0-rc88

### What version of Node.js are you using?

v14.16

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
@christianrr I think it's the `$CURRENT_USER` dynamic variable, not the _and that might be causing the trouble 🙂

**Comment by christianrr** [comment]
> @christianrr I think it's the `$CURRENT_USER` dynamic variable, not the _and that might be causing the trouble 🙂

I just doublechecked, you are right - it's the dynamic variable that does not work.

**Comment by rudgalvis** [comment]
Not sure if I should've opened a new issue, but I'd like to add that there's issue with `$NOW(<adjustment>)` when being used in custom API endpoint. 

When using dynamic variable as described in the [directus documentation](https://docs.directus.io/reference/filter-rules/#dynamic-variables):
```
<ItemsService>.readByQuery({
  filter: {
    date_created: {
        _gte: '$NOW(-1 year)'
    }
  }
}
````
Getting error:
```
ERROR:  invalid input syntax for type timestamp with time zone: "$NOW(-1 year)"
```

Using same environment as described in the original post

**Comment by rijkvanzanten** [comment]
> Not sure if I should've opened a new issue

Yes please! Sounds like an unrelated issue to the one posted above 🙂
