### ISSUE TITLE
Cannot migrate v8 tables to v9 with 'CURRENT_TIMESTAMP'

### ISSUE THREAD

**Issue by tshan007** [directus/directus#7180]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

All the existing tables with datetime/timestamp fields which contains default values as CURRENT_TIMESTAMP are failed to migrate and getting following error.

ER_INVALID_DEFAULT: Invalid default value for 'createdAt'

![image](https://user-images.githubusercontent.com/8465910/128110268-a2c3070d-52ff-459c-8959-3f77c3d287fc.png)

### To Reproduce

Host directus v9.
Migrate v8 to v9 via [migration tool](https://github.com/directus-community/migration-tool).

### What version of Directus are you using?

9.0.0-rc.87

### What version of Node.js are you using?

16.6.0

### What database are you using?

mysql 8.0.22

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

locally

**Comment by paescuj** [comment]
Can you post this issue on the [migration-tool](https://github.com/directus-community/migration-tool) repository instead?

**Comment by tshan007** [comment]
> Can you post this issue on the [migration-tool](https://github.com/directus-community/migration-tool) repository instead?

Well... Yes I can post there, but errors are getting from the directus v9 end. I didn't see any error on migration tool.

**Comment by paescuj** [comment]
Yes, but it is something which should be handled by the migration-tool. Thanks!
