### ISSUE TITLE
Interface WYSIWYG don't save options override

### ISSUE THREAD

**Issue by Adri-Glez** [directus/directus#7188]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When someone edit a field in a colletion definition with interface WYSIWYG they can't save  configurations in the 'options override'. is It not avaliable to changue the settings of  this component? TinyMCE if I not wrong.

### To Reproduce

1)In settings-data  model we select a collection that have a  field with WYSIWYG interface. If it don't have it we can create a field with this interface
2)we select the field that have a WYSIWYG interface.
3)In interface tab we introduce some   'options override' in json like :
`{fix_list_elements : false}`
or without {}:
`fix_list_elements : false`
4) we save the field edition an we save the colletion edition
5) we acces to the interface tab of the same field and the  'options override' is blank or only with empty {}

### What version of Directus are you using?

v9.0.0-rc.62

### What version of Node.js are you using?

server -> version provided in docker image; Client->v15.4.0

### What database are you using?

MySQL 8

### What browser are you using?

Chrome 90

### What operating system are you using?

Windows 10 as client, Linux RancherOs with docker as server

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
@Adri-Glez That setting uses JSON, not JavaScript for it's overrides. `{fix_list_elements : false}` isn't valid JSON. Try `{ "fix_list_elements": false }` instead 🙂
