### ISSUE TITLE
First Collection creation (via API) response states already exists

### ISSUE THREAD

**Issue by justrealmilk** [directus/directus#7190]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Using rc85 or rc88, one of the stranger issues I've been encountering is that prior to creating any collections, the response sent to the tool is 400 bad request. 

Recreation of the request and its payload results in Directus claiming the collection already exists. I'm looking at the database in another tab, smashing refresh, and it's just not there. 

Out of desperation, I thought to create a collection of the same name through the app interface, delete it, and try again. It now works and the problem doesn't crop up for subsequent collections.

### To Reproduce

Try the directus-community/migration-tool tool or perform the following POST request:

Endpoint:
POST /collections

Headers:
`Authorization` `Bearer TOKEN`
`Content-Type` `application/json`

Payload:
```json
{
  "collection": "blog",
  "meta": { "note": null, "hidden": false, "singleton": false, "icon": "book", "sort_field": null, "archive_field": "status", "archive_value": "deleted", "unarchive_value": "draft" },
  "schema": {},
  "fields": [
    { "field": "id", "type": "integer", "meta": { "note": "", "interface": null, "readonly": false, "hidden": true, "width": null, "sort": 1 }, "schema": { "has_auto_increment": true, "default_value": null, "is_primary_key": true, "is_nullable": false, "max_length": "10", "numeric_precision": "10", "numeric_scale": null } },
    {
      "field": "status",
      "type": "string",
      "meta": {
        "note": "",
        "interface": "select-dropdown",
        "readonly": false,
        "hidden": false,
        "width": "full",
        "sort": 2,
        "options": {
          "choices": [
            { "text": "Published", "value": "published" },
            { "text": "Draft", "value": "draft" },
            { "text": "Deleted", "value": "deleted" }
          ]
        }
      },
      "schema": { "has_auto_increment": false, "default_value": "draft", "is_primary_key": false, "is_nullable": true, "max_length": "20", "numeric_precision": "20", "numeric_scale": null }
    },
    { "field": "created_on", "type": "timestamp", "meta": { "note": "", "interface": "datetime", "readonly": true, "hidden": true, "width": "full", "special": ["date-created"], "sort": 3 }, "schema": { "has_auto_increment": false, "default_value": null, "is_primary_key": false, "is_nullable": true, "max_length": null, "numeric_precision": null, "numeric_scale": null } },
    { "field": "modified_on", "type": "timestamp", "meta": { "note": "", "interface": "datetime", "readonly": true, "hidden": true, "width": "full", "special": ["date-updated"], "sort": 4 }, "schema": { "has_auto_increment": false, "default_value": null, "is_primary_key": false, "is_nullable": true, "max_length": null, "numeric_precision": null, "numeric_scale": null } },
    { "field": "name", "type": "string", "meta": { "note": "", "interface": "input", "readonly": false, "hidden": false, "width": "full", "sort": 5 }, "schema": { "has_auto_increment": false, "default_value": null, "is_primary_key": false, "is_nullable": true, "max_length": "200", "numeric_precision": "200", "numeric_scale": null } },
    { "field": "slug", "type": "string", "meta": { "note": "", "interface": "input", "readonly": false, "hidden": false, "width": "full", "sort": 6 }, "schema": { "has_auto_increment": false, "default_value": null, "is_primary_key": false, "is_nullable": true, "max_length": "200", "numeric_precision": "200", "numeric_scale": null } },
    { "field": "tags", "type": "json", "meta": { "note": "", "interface": "tags", "readonly": false, "hidden": false, "width": "full", "sort": 9 }, "schema": { "has_auto_increment": false, "default_value": null, "is_primary_key": false, "is_nullable": true, "max_length": "2000", "numeric_precision": "2000", "numeric_scale": null } },
    { "field": "summary", "type": "text", "meta": { "note": "", "interface": "input-rich-text-md", "readonly": false, "hidden": false, "width": "full", "sort": 7 }, "schema": { "has_auto_increment": false, "default_value": null, "is_primary_key": false, "is_nullable": true, "max_length": "65535", "numeric_precision": "65535", "numeric_scale": null } }
  ]
}
```

### What version of Directus are you using?

9.0.0-rc.88

### What version of Node.js are you using?

v14.9.0

### What database are you using?

MySQL 8

### What browser are you using?

HTTP client

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
@justrealmilk What is the response of the 400?  It could be that it actually created the collection, but failed to create one of the fields for example 🤔 IIRC MySQL ignores transactions for DDL operations, so that would explain why you might have some residue stuff left behind where half the request failed.

**Comment by justrealmilk** [comment]
> @justrealmilk What is the response of the 400? It could be that it actually created the collection, but failed to create one of the fields for example 🤔 IIRC MySQL ignores transactions for DDL operations, so that would explain why you might have some residue stuff left behind where half the request failed.

```json
{
  "errors": [
    {
      "message": "Collection \"blog\" already exists.",
      "extensions": {
        "code": "INVALID_PAYLOAD"
      }
    }
  ]
}
```

**Comment by rijkvanzanten** [comment]
> or perform the following POST request:

I just tried this on a locally running Directus instance on a totally empty Postgres database, and it seemingly went through just fine, including all the fields 🤔 

<img width="1279" alt="CleanShot 2021-08-04 at 19 24 44@2x" src="https://user-images.githubusercontent.com/9141017/128268060-4b07924b-9446-42d2-9059-5fc225ceced7.png">

Are you sure your v9 instance is totally cleared out, and this isn't a problem in the migration tool?

**Comment by justrealmilk** [comment]
> > or perform the following POST request:
> 
> I just tried this on a locally running Directus instance on a totally empty Postgres database, and it seemingly went through just fine, including all the fields 🤔
> 
> <img alt="CleanShot 2021-08-04 at 19 24 44@2x" width="1279" src="https://user-images.githubusercontent.com/9141017/128268060-4b07924b-9446-42d2-9059-5fc225ceced7.png">
> 
> Are you sure your v9 instance is totally cleared out, and this isn't a problem in the migration tool?

I am sure. I _aggressively_ DROP tables using phpMyAdmin (old and trusted as you know) and restart the instances causing Directus to run its installing Directus tables action

**Comment by rijkvanzanten** [comment]
> I am sure. I aggressively DROP tables using phpMyAdmin (old and trusted as you know) and restart the instances causing Directus to run its installing Directus tables action

Do you also clear any stranded meta rows from directus_collections and directus_fields?

**Comment by justrealmilk** [comment]
> > I am sure. I aggressively DROP tables using phpMyAdmin (old and trusted as you know) and restart the instances causing Directus to run its installing Directus tables action
> 
> Do you also clear any stranded meta rows from directus_collections and directus_fields?

The database is emptied before reinitializing

**Comment by rijkvanzanten** [comment]
Still can't seem to reproduce this on a fresh installation by just hitting the API as per the instructions. I don't think this is a problem in Directus itself 🤔 

Lets open a new issue on the migration-tool and take it from there 👍🏻
