### ISSUE TITLE
Cards Layout truncates title

### ISSUE THREAD

**Issue by Alv-sys** [directus/directus#7197]
Playing with the Layout options of the collections, the "Cards" Layout, I realized when the title is longer than the space, it just turn into three points "...". Probably it should be nice to have by default the field always with the full title or if it is a problem the space, keeping some reasonable part of the string to recognize them better

![image](https://user-images.githubusercontent.com/47535920/128114044-1d3d6100-0e0e-49ea-a2cd-a234ec40ac5f.png)

_Originally posted by @Alv-sys in https://github.com/directus/directus/discussions/7182_

**Comment by benhaynes** [comment]
Haha, I wonder how you bypassed the Bug Report form?! We could have converted the Discussion to an Issue, but wanted to make sure that the form was filled out with relevant debugging details. 😉

**Comment by rijkvanzanten** [comment]
Yeahhhhhhhhhhhhhhhhhhhhh...

@Alv-sys Mind providing the info requested in https://github.com/directus/directus/issues/new?assignees=&labels=Bug+%28Potential%29&template=bug_report.yml? 😄

**Comment by rijkvanzanten** [comment]
<img width="1081" alt="CleanShot 2021-08-04 at 19 22 15@2x" src="https://user-images.githubusercontent.com/9141017/128267889-d89d81bb-6377-434b-9e2f-c325d5027298.png">

Looks good on my end (Edge Version 92.0.902.62)

**Comment by Alv-sys** [comment]
Thank you for the answer @rijkvanzanten, I repeated the process from scratch and it was working normally.

After doing some times, I realized the problem occurs when you give a formatted value 
![image](https://user-images.githubusercontent.com/47535920/128431578-2c62d1f9-2e98-43c5-9fc4-cb28f08c535f.png)
![image](https://user-images.githubusercontent.com/47535920/128431600-fa000de9-542c-49a5-ab7e-fbdb0985c256.png)

If I remove it, it works normally:
![image](https://user-images.githubusercontent.com/47535920/128431648-9d738160-9aa0-4796-9373-cc36bed02f52.png)
![image](https://user-images.githubusercontent.com/47535920/128431668-bfba0a4e-3a47-483d-b7ab-18bf45499486.png)
