### ISSUE TITLE
Updating Contextual Times

### ISSUE THREAD

**Issue by RNGR** [directus/directus#72]
All contextual datetimes "1 minute ago" should have a class such as .contextual_time and a data-attribute with the timestamp. Every minute they get looped over and updated to show the correct string time.

**Comment by WellingGuzman** [comment]
@benhaynes I moved this into the current release. any thoughts?

**Comment by benhaynes** [comment]
Yeah, I like that... this will help the app be more accurate when on the same page for a while. Also, it shouldn't be too difficult.

**Comment by WellingGuzman** [comment]
any element that has a `.contextual-date-updater` class and `data-date` attribute including the date, a date that `moment.js` can understand, should update that element every 60 seconds.

Although it should be a little bit smart, and update gradually, for example dates that are above 1hour it should update hourly. what about not including elements that are hidden or not visibles?

**Comment by benhaynes** [comment]
@WellingGuzman Excellent – is there a branch where I can test this?

**Comment by WellingGuzman** [comment]
@benhaynes development branch, read my previous message on how it works. and let me know how it turns out.

**Comment by WellingGuzman** [comment]
this was done. closing it.
