### ISSUE TITLE
Images with some types of EXIF data will fail to upload

### ISSUE THREAD

**Issue by justrealmilk** [directus/directus#7206]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Some images will fail to upload if they contain a... string. See the example for said string.

I am unsure what it's supposed to say but it's no longer readable and I can't think of a way to decode it if that's even possible. Looks like a .exe opened with Notepad

The request HTTP status code is 500 and Directus has this to say about it in terminal

```
update `directus_files` set `storage` = 'local', `filename_disk` = '436cae72-b967-42d4-9c6c-ffbf1851d229.jpg', `filename_download` = 'image.jpg', `title` = 'A Title', `type` = 'image/jpeg', `filesize` = 521615, `width` = 1500, `height` = 1000,
`description` = '�rǈ�O�a����c�l7�q�*A�\\M�Ռr�v�݄�J�3����p�\Z3%Y{�N�Ia���5;i�O�+䍽Dq�5#a��z����lP�[�@[�{�*�lw\b&��r�5\b�S�g�~z�>a��Z��>�\"�D�?��U�9����<�}TMX��%�3��Dy�=.��K���z��zr?i>��3Q�^��^����.
���P2�xS�u���\0�ƌ�@�r�ć�\ZQ��BF�4`��lق�\'�Oՙ�ӬO���[΋|���m��\n�F����jOi:M��*�d�\"y*Wr�9�p�#Ծ
�󷛥В���@�_.�˛�\b\0�Pk˛�0H�����;��~g�:���d��6����\'-�m�ڙ!��)�����R��g���XV�X\'��xҿe��a�\\l����\0L�_^
15bN�\0���!�+�R����iO�LP��*i��D1$g�\0���\"�\ZDjS\\�=�y\\(!�\0\b�E:�a�r�6�<�!��\r<C_��������f*nx징i����*�b�@ڛ��
�Ud��B�Z�qUE7�j7QM��Zb������@OO�[�ĊF��J��\n��)�~5q�\0�?���;h�P̩Riɷ�p+�7��K���Ē�P�@=\rqd�<�
�]�\0��������Qɡ����J˕�Xl�*�/��O8h�$z���tƈ$e�&�%\rkO���c�S���ɗ���N\Z����T��Y.\0X��r@j��~T�
y�ul�գ�b�Ѓ]�X(��ʓ�/����+,�����N�ٞB�6�c���r�U5�����g��`���R��Đ�u�U���\0����5a�9��E�VGN�m\n��x
\'N%\rYH�z�-��/�oɋ��M[B��4y\ti-�{\Z�E�\0̼Y�i8Y���y<��y!�&��Kjd�n%��<��|����6~��u}r}*�����,�Ϋ�����s���\n���
O��|����u42]��%��\t���e�@�S��4��,��7�F�&�6v�ʴ�xC�~@4��[T{��4�IZH��GUKlYA��\nO�C�Y�B
�W�TLU�6U��b��MG��\ts�شn}/I�x�\'�j��c~��S|P��w.#�����h]�=�����I}H4�R.���B>�*��U7_ɟ7�\tq-�
��;��R�������B쑱��E+G\"�ڭ�qV�\0IL*A\'~�إW��̭S�;�����5V�U�\n�\"�ت:bX�\0�~-�:�=�U�RaUQ��\Z��
~�@kھث���ŵ)%���ۥ�ȖA&��x�IQ��0ea�\Z�@���s���4�՝�\'�qJig拨�8fh�EC+\"��\Z[�L��ߟ~e�e��\'�����Sm/
������f2w���w��?3h����\'��rPvaة�N�\0,�z��?�]]��\"~�}��%;�ըq�\0���&9��މ��u=/DC�@��[��G^�q�e9p�r0j\0
�����<�v\0�[�x�\0�r��q�s������$,2�t�[D]r�MӠ�|_Z�\b���cǓ7����g`ѐ��9�O�����1\n����r�J�Aڌ�\0�/2���9�
Wy�Ouq-�����K�#nı���\0��H��K��S߮�>�,T�(�s�������[�T7z��*�=�=w��V�\\��hjw�[3�z�*��\t��唰ã
�R�OȨ#����B����p��8OJ�mUv�\0e�C��k�hMoWy\n�M�\\Y%����3�E#�D����\n�������l+���TW�\"���g
T�}�J���u���������\n����ZP1늣����@��\b�3\t\t�M76�0����M>��#�*���ATeߌ���n��U��2nO�-�C�ޞت�n8���T�a�?',
`tags` = '[\"Final Picks\",\"Pre-Picks\"]', `metadata` = '{\"icc\":{\"version\":\"2.1\",\"intent\":\"Perceptual\",\"cmm\":\"Lino\",\"deviceClass\":\"Monitor\",\"colorSpace\":\"RGB\",\"connectionSpace\":\"XYZ\",\"platform\":\"Microsoft\",\"manufacturer\":\"IEC\",\"model\":\"sRGB\",\"creator\":\"HP\",\"copyright\":\"Copyright (c) 1998 Hewlett-Packard C\",\"description\":\"sRGB IEC61966-2.1\",\"deviceModelDescription\":\"IEC 61966-2.1 Default RGB colour space - sRGB\",\"viewingConditionsDescription\":\"Reference Viewing Condition in IEC61966-2.1\"},\"exif\":{\"image\":{\"Make\":\"Canon\",\"Model\":\"Canon EOS REBEL T2i\",\"XResolution\":72,\"YResolution\":72,\"ResolutionUnit\":2,\"Software\":\"Adobe Photoshop Lightroom 6.14 (Macintosh)\",\"ModifyDate\":\"2020-07-25T19:29:35.000Z\",\"ExifOffset\":216},\"thumbnail\":{\"Compression\":6,\"XResolution\":72,\"YResolution\":72,\"ResolutionUnit\":2,\"ThumbnailOffset\":822,\"ThumbnailLength\":15848},\"exif\":{\"ExposureTime\":0.004,\"FNumber\":4,\"ExposureProgram\":1,\"ISO\":1600,\"ExifVersion\":{\"type\":\"Buffer\",\"data\":[48,50,51,48]},\"DateTimeOriginal\":\"2020-06-02T04:47:57.000Z\",\"DateTimeDigitized\":\"2020-06-02T04:47:57.000Z\",\"ShutterSpeedValue\":7.965784,\"ApertureValue\":4,\"ExposureBiasValue\":0,\"MaxApertureValue\":3.875,\"MeteringMode\":5,\"Flash\":16,\"FocalLength\":22,\"SubSecTimeOriginal\":\"77\",\"SubSecTimeDigitized\":\"77\",\"ColorSpace\":1,\"FocalPlaneXResolution\":5728.176795580111,\"FocalPlaneYResolution\":5808.403361344538,\"FocalPlaneResolutionUnit\":2,\"CustomRendered\":0,\"ExposureMode\":1,\"WhiteBalance\":1,\"SceneCaptureType\":0,\"BodySerialNumber\":\"1122534049\",\"LensSpecification\":[18,135,null,null],\"LensModel\":\"EF-S18-135mm f/3.5-5.6 IS\"}},\"iptc\":{\"keywords\":[\"Final Picks\",\"Pre-Picks\"],\"dateCreated\":\"20200602\"}}', `modified_by` = NULL, `modified_on` = '2021-08-04 15:18:08.620' where `id` in ('436cae72-b967-42d4-9c6c-ffbf1851d229') - ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF3\xB7\x9B\xA5\xD0\x92...' for column 'description' at row 1
Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF3\xB7\x9B\xA5\xD0\x92...' for column 'description' at row 1
```

My understanding is that on upload, Directus looks in common places for a description value to pre-fill the file's description property.

### To Reproduce

I sadly can not provide the image I used for privacy reasons. I've inspected the file myself with online and offline (IrfanView) EXIF readers looking for the problem property and I can't find it, _but_ it does only occur with specific sets of images.

For what it's worth, the database collation is set to `utf8mb4_0900_ai_ci` which I believe is the one that supports crazy Unicode characters

Oh, and they upload to Directus 8 just fine so it must be that new EXIF tech in 9!

### What version of Directus are you using?

9.0.0-rc.88

### What version of Node.js are you using?

v14.9.0

### What database are you using?

MySQL 8

### What browser are you using?

HTTP client/Directus app in Edge Dev

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
> I sadly can not provide the image I used for privacy reasons.

This makes sense, butttttttttttttt is there any non-private image that you've seen that causes the same behavior, or any way we could generate a redacted version? 😬 (I'll also gladly sign an NDA if you can/want to send it over in private at rijk@directus.io)

**Comment by rijkvanzanten** [comment]
I think this might've been resolved by https://github.com/directus/directus/pull/6922, but we can reopen if not

**Comment by paescuj** [comment]
Thanks @rijkvanzanten, I was going to suggest that #6922 might solve this, but you're too fast 😄
@justrealmilk In the meantime (until this PR has been shipped in a new version) you can see if `exifr` is able to handle your image by using the playground page at https://mutiny.cz/exifr/ (don't worry, your image won't be uploaded - it's processed locally in your browser)

**Comment by justrealmilk** [comment]
> Thanks @rijkvanzanten, I was going to suggest that #6922 might solve this, but you're too fast 😄
> @justrealmilk In the meantime (until this PR has been shipped in a new version) you can see if `exifr` is able to handle your image by using the playground page at https://mutiny.cz/exifr/ (don't worry, your image won't be uploaded - it's processed locally in your browser)

Checked it out! Same findings as the other apps I used to inspect. The file looks fine.

These images are either garbled in other ways that their demo tool doesn't reveal or something happens to them in the Directus flow.

In any case, I was using the API endpoint to upload them through URL from v8 and I simply sent a "blank" string as the description value as it takes precedence (I read the API source yay for v9 JS) and I got them in just fine.

**Comment by rijkvanzanten** [comment]
> These images are either garbled in other ways that their demo tool doesn't reveal or something happens to them in the Directus flow.

From your shared error above, it looks like the description value came through as binary instead of a string from the previous exif reader, which crashed when inserting that as a string into the description field. I'm hopeful the new exif reading flow won't have the same bug, therefore solving this issue 🙂
