### ISSUE TITLE
Password Reset Mail

### ISSUE THREAD

**Issue by AndreyKindin** [directus/directus#7221]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Hello,
after the update to .88 no password-reset mails are sent. With version .87 everything still worked.

### To Reproduce

```
POST /auth/password/request
{email: 'email@user.net'}
```

### What version of Directus are you using?

v9.0.0-rc.88

### What version of Node.js are you using?

v14.16.1

### What database are you using?

MariaDB

### What browser are you using?

Chrome

### What operating system are you using?

Server Linux / Workstation Windows

### How are you deploying Directus?

running locally on server

**Comment by rijkvanzanten** [comment]
Are you posting `{email: 'email@user.net'}`, or `{ "email": "email@user.net" }`? (One being JS, the other valid JSON)?

**Comment by rijkvanzanten** [comment]
I just tried this out on a fresh installation connected through SMTP to Mailtrap.io and it seems to go through fine:

Request:
```
POST /auth/password/request HTTP/1.1
Content-Type: application/json
Host: localhost:8055
Connection: close
User-Agent: Paw/3.2.3 (Macintosh; OS X/11.4.0) GCDHTTPRequest
Content-Length: 34

{
  "email": "admin@example.com"
}
```

Response:

```
HTTP/1.1 200 OK
X-Powered-By: Directus
Vary: Origin, Cache-Control
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Content-Range
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Thu, 05 Aug 2021 17:47:03 GMT
Connection: close
Content-Length: 0
```

Mailtrap.io:

<img width="739" alt="CleanShot 2021-08-05 at 13 47 59@2x" src="https://user-images.githubusercontent.com/9141017/128397102-b0ac425a-8a8d-4d92-9f64-bd4e89c279ef.png">

**Comment by AndreyKindin** [comment]
Sorry,
that was not precise enough from me, to send the request to the Directus I use Javascript SDK there also everything works correctly in my opinion, but the Directus sends no more mail out.

![mail_request](https://user-images.githubusercontent.com/9415025/128479886-a7b39c2f-9c6b-4c02-85e1-54805581c2b6.png)

**Comment by AndreyKindin** [comment]
this is the comparison of trace log from .87 and .88

.87
12:29:08 🔍 [0.611ms] select `ip_access` from `directus_roles` where `id` is null limit ? [1]
12:29:08 🔍 [0.883ms] select * from `directus_permissions` where `role` is null []
12:29:08 🔍 [0.737ms] select `id` from `directus_users` where `email` = ? limit ? [bla@bla.de, 1]
12:29:08 🔍 [0.732ms] select `project_name`, `project_logo`, `project_color` from `directus_settings` limit ? [1]
12:29:09 ✨ request completed POST 200 /auth/password/request 372ms

.88
12:43:37 🔍 [0.638ms] select `ip_access` from `directus_roles` where `id` is null limit ? [1]
12:43:37 🔍 [0.761ms] select * from `directus_permissions` where `role` is null []
12:43:37 ✨ request completed POST 200 /auth/password/request 22ms

**Comment by AndreyKindin** [comment]
and a small additional question how can I set subject with JavaScript SDK?

**Comment by rijkvanzanten** [comment]
Are you using the same settings for outgoing emails?

Errors don't propagate out in the api call response for security reasons (otherwise somebody could extract all the email addresses in your system). I'll add a new logger call when those errors happen though, so you can see what's going wrong here 👍🏻

**Comment by rijkvanzanten** [comment]
That PR doesn't necessarily solve any underlying problems, but I'm assuming the email problem is caused by external factors, as nothing else changed between 87 and 88 in the password request flow. This PR should show you what's wrong in terminal. If it turns out to be a bug in the request flow, we'll reopen this and fix the potential underlying problem 🙂

**Comment by AndreyKindin** [comment]
i don't think it's an external problem because i tested it with .87 it worked, then update to .88 - test it doesn't work, back to .87 it works, the whole several times without changing anything.
can this be the reason?https://github.com/directus/directus/pull/7105

**Comment by rijkvanzanten** [comment]
Possibly, though I would've expected to see the issue on my end then as well 🤔 Lets see what the logger added in #7248 prints and take it from there. 

If you're in an adventurous mood, you should be able get the same info by adding a `console.log(err);` to `node_modules/directus/dist/controllers/auth.js` in here:

```js
    catch (err) {
        console.log(err); // <<<<<<<<<<<<<<
        if (err instanceof invalid_payload_1.InvalidPayloadException) {
            throw err;
        }
        else {
            return next();
        }
    }
```

(between lines 161 and 162)

**Comment by AndreyKindin** [comment]
Yes I am
ReferenceError: performance is not defined
    at UsersService.requestPasswordReset (/var/www/customers/pic/directus_source/node_modules/directus/dist/services/users.js:273:27)
    at /var/www/customers/pic/directus_source/node_modules/directus/dist/controllers/auth.js:158:23
    at scoped (/var/www/customers/pic/directus_source/node_modules/directus/dist/utils/async-handler.js:5:60)
    at Layer.handle [as handle_request] (/var/www/customers/pic/directus_source/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/customers/pic/directus_source/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/www/customers/pic/directus_source/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/www/customers/pic/directus_source/node_modules/express/lib/router/layer.js:95:5)
    at /var/www/customers/pic/directus_source/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/var/www/customers/pic/directus_source/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/customers/pic/directus_source/node_modules/express/lib/router/index.js:275:10)

**Comment by rijkvanzanten** [comment]
Thanks! That helps out a lot 👍🏻

**Comment by Bacto** [comment]
Hi,

I got the same problem. Thanks for the patch that is coming :)

I'm commenting this issue because I'm surprised that this error didn't triggered a log and worse, the API request returned a 200 status.
Maybe there is something to improve on how errors are catched.

Anyway, thanks for Directus, I really like it so far :)

**Comment by rijkvanzanten** [comment]
> and worse, the API request returned a 200 status.

This is by design! If it were to throw an error for wrong emails, it'll inevitably expose all emails in your system, as someone could brute-force that endpoint to retrieve all the email addresses in the platform

**Comment by Bacto** [comment]
In that case, a library wasn't imported. I think it should return a 500 error.

But I totally agree that in normal scenario, if email isn't found, it should return a 200 and never a 404.
