### ISSUE TITLE
GraphQL can't auth when there is a space in a collection name

### ISSUE THREAD

**Issue by jaycammarano** [directus/directus#7224]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When trying to authenticate with GraphQL if any of the collection names have spaces it is unable to return an access token/refresh token.
REST API unaffected.

### To Reproduce

1. Create a table through the SDK that has spaces in it.
2. Try to authenticate at `http://localhost:8055/graphql/system` with
```
mutation {
    auth_login(
        email: "admin@example.com"
        password: "examplePassword"
        mode: json
    ) {
        access_token
        refresh_token
    }
}
```
it returns an HTML of 
```<pre>TypeError: Cannot assign to read only property &#39;extensions&#39; of object &#39;GraphQLError: Syntax Error: Unexpected Name &quot;create_My&quot;.&#39;<br> &nbsp; &nbsp;at errorHandler</pre>
```
and in the console
directus: 13:48:44 🚨 Syntax Error: Unexpected Name "create_My".
directus: GraphQLError: Syntax Error: Unexpected Name "create_My".

### What version of Directus are you using?

Latest-dev

### What version of Node.js are you using?

v16.4.0

### What database are you using?

PostGres

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/directus/pull/7223
