### ISSUE TITLE
Cannot create treeview O2M

### ISSUE THREAD

**Issue by bahamut657** [directus/directus#7228]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

It is not possible to configure parent->child where child is on the same collection

### To Reproduce

1) Create collection "topics" composed by id (PK) and name
2) Add O2M relation with the collection itself, selecting the PK as FK
=> Saving the relation will result in an error (Invalid SQL)

### What version of Directus are you using?

9.0.0-rc.88

### What version of Node.js are you using?

official dockerhub directus image

### What database are you using?

mysql

### What browser are you using?

Chrome

### What operating system are you using?

Armbian

### How are you deploying Directus?

docker

**Comment by rijkvanzanten** [comment]
This makes sense!

> Add O2M relation with the collection itself, selecting the PK as FK

You can't have it save the foreign key on top of the primary key field, as that would kill the current item (as you would replace the current parent item's ID with the ID of the child). Add a new field to use as the foreign key instead (something like a `parent_id` field 👍🏻 )
