### ISSUE TITLE
Invalid regular expression error on delete field

### ISSUE THREAD

**Issue by plazabjc** [directus/directus#7233]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I created a field with the following name:

`*violence_victim:`

on trying to delete the field using the directus vue app I get this error:

```
{
  "errors": [
    {
      "message": "Invalid regular expression: /\\b*victima_de_violencias:\\b/: Nothing to repeat",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### To Reproduce

1. Create a field that starts with * and ends with :

2. Try to delete the field

### What version of Directus are you using?

9.0.0-rc.88

### What version of Node.js are you using?

v14.15.1

### What database are you using?

sqlite

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
How did you create that field?

**Comment by rijkvanzanten** [comment]
This is an issue in `knex`. I've opened a new issue there 👍🏻  Ref https://github.com/knex/knex/issues/4608
