### ISSUE TITLE
API fails with value.toISOString is not a function on saving date object

### ISSUE THREAD

**Issue by plazabjc** [directus/directus#7235]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Saving a Date field with any value fails with the following error:
```

{
  "message": "value.toISOString is not a function",
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR"
  }
}
```

### To Reproduce

1. Create a Date field using the app
2. Edit an entry and try to save the date using the default DateTime interface
3. On clicking save the error above happens

Another way to replicate:
1. If you set the field from Allow Null true to false and try to input a default value it also fails 

NOTE: I tried with DateTime field and the error didn't happen so it seems to be related to Date only 

### What version of Directus are you using?

9.0.0-rc.88

### What version of Node.js are you using?

v14.15.1

### What database are you using?

sqlite

### What browser are you using?

chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
This should've been fixed in https://github.com/directus/directus/issues/6818 🙂
