### ISSUE TITLE
Error with accessing system collections

### ISSUE THREAD

**Issue by arladmin** [directus/directus#7262]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Unable to access the system collections, even with admin access (via REST/GraphQL).

I keep running into the error: ```You don't have permission to access this.``` when accessing the endpoint ```/items/directus_fields```. 
I'm using the admin account's auth token.

### To Reproduce

1. Access the REST api endpoint `http://ip:8080/items/directus_fields` or any other system collection
2. Use the admin auth token for Authorization
3. Receive error instead of the data

### What version of Directus are you using?

v9.0.0-rc.88

### What version of Node.js are you using?

16.5.0

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
It's /fields, not /items/directus_fields 👍🏻

https://docs.directus.io/reference/api/system/fields/

The system data in graphql can be found under /graphql/system. See https://docs.directus.io/reference/api/introduction/#system-data-in-graphql

**Comment by arladmin** [comment]
@rijkvanzanten Thanks! Seems like i missed the obvious docs!
