### ISSUE TITLE
Invalid MySQL query while filtering a JSON field of a one-to-many field

### ISSUE THREAD

**Issue by dannycoulombe** [directus/directus#7267]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

If a try to filter a JSON field from a table it's working, but if I'm trying to filter a JSON field of a join, it throws a MySQL query syntax error.

The query called is:
http://localhost:8055/items/notification?meta=filter_count&limit=10&page=1&fields=post.*,post.user_created.*&filter=%7B%22type%22:%22new_post%22,%22user_assigned%22:%7B%22_eq%22:%22a3cc8f56-1be0-497e-9af5-4243ab2a65a3%22%7D,%22post%22:%7B%22_or%22:[%7B%22topic%22:%7B%22_contains%22:%22book%22%7D%7D,%7B%22topic%22:%7B%22_contains%22:%22business%22%7D%7D]%7D%7D

Basically, I want to filter topics (JSON field of post table) from the notification table.

For clarify (because above URL is difficult to read), my params are the following:

```
meta: filter_count
limit: 10
page: 1
fields: post.*,post.user_created.*
filter: {"type":"new_post","user_assigned":{"_eq":"a3cc8f56-1be0-497e-9af5-4243ab2a65a3"},"post":{"_or":[{"topic":{"_contains":"book"}},{"topic":{"_contains":"business"}}]}}
```

My tables:

```
create table notification
(
    id            int unsigned auto_increment
        primary key,
    date_created  timestamp            null,
    user_assigned char(36)             null,
    type          varchar(16)          not null,
    post          char(36)             null,
    acknowledged  tinyint(1) default 0 not null,
    constraint notification_post_foreign
        foreign key (post) references post (id)
            on delete set null,
    constraint notification_user_assigned_foreign
        foreign key (user_assigned) references directus_users (id)
            on delete set null
);
```

```
create table post
(
    id                char(36)                     not null
        primary key,
    status            varchar(255) default 'draft' not null,
    user_created      char(36)                     null,
    date_created      timestamp                    null,
    user_updated      char(36)                     null,
    date_updated      timestamp                    null,
    title             varchar(255)                 not null,
    language          varchar(2)   default 'en'    not null,
    total_words       int                          null,
    read_time         int                          null,
    excerpt           varchar(255)                 null,
    topic             json                         null,
    total_corrections int          default 0       not null,
    total_comments    int          default 0       not null,
    body              text                         null,
    constraint post_user_created_foreign
        foreign key (user_created) references directus_users (id),
    constraint post_user_updated_foreign
        foreign key (user_updated) references directus_users (id)
);
```

### To Reproduce

Follow the instructions mentioned above.

### What version of Directus are you using?

9.0.0-rc.83

### What version of Node.js are you using?

v14.17.3

### What database are you using?

8.0.26-0ubuntu0.20.04.2 for Linux on x86_64

### What browser are you using?

Vivaldi 4.1.2369.15 (Stable channel) stable (64-bit), REV d577756a1a91db75d91b8ea77de9ed59460daf85

### What operating system are you using?

Ubuntu

### How are you deploying Directus?

Locally

**Comment by dannycoulombe** [comment]
Forgot to add the final error message:

500
INTERNAL_SERVER_ERROR
```
select `notification`.`post`, `notification`.`id` from `notification` where `notification`.`type` = 'new_post' and `notification`.`user_assigned` = 'a3cc8f56-1be0-497e-9af5-4243ab2a65a3' and `notification`.`post` = {"topic":{"_contains":"book"}}, {"topic":{"_contains":"business"}} order by `notification`.`id` asc limit 10 - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', '[object Object]' order by `notification`.`id` asc limit 10' at line 1
```

**Comment by rijkvanzanten** [comment]
Directus currently can't search through JSON objects stored in the database, as not every database has native JSON querying capabilities.

I've opened a new feature request discussion to support searching in JSON objects here: https://github.com/directus/directus/discussions/7277
