### ISSUE TITLE
INTERNAL_SERVER_ERROR when try to use $NOW(<adjustment>) $NOW(-1 year), $NOW(+2 hours)

### ISSUE THREAD

**Issue by hermesalvesbr** [directus/directus#7280]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

[INTERNAL_SERVER_ERROR] alter table "individuo" alter column "nascimento" set default '$NOW(-1 year)' - invalid input syntax for type date: "$NOW(-1 year)"
content_copy

### To Reproduce

I'm trying to use $NOW(-1 year) like docs: https://docs.directus.io/reference/filter-rules/#dynamic-variables

Just works without <adjustment> 

[INTERNAL_SERVER_ERROR] alter table "individuo" add column "nascimentotime" timestamptz null default '$NOW(-1 year)' - invalid input syntax for type timestamp with time zone: "$NOW(-1 year)"
content_copy

I have tried with timestamp, date and datetime. 

### What version of Directus are you using?

v9.0.0-rc.88

### What version of Node.js are you using?

node --version v16.5.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS, Windows

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
@hermesalvesbr Where are you using this? It's trying to set it as the default value 🤔

**Comment by hermesalvesbr** [comment]
Yes, i did some wrong? 

![Screenshot_20210809-161017_Chrome.png](https://user-images.githubusercontent.com/379850/128761094-31c28a19-d167-4dab-b217-f694f77c5069.png)

**Comment by rijkvanzanten** [comment]
Ah yeah, those dynamic variables are used in the filter rules, f.e. in filters, permissions, validation, etc. The default value under `schema` is the default value used for the database column.
