### ISSUE TITLE
Cannot read property 'related_collection' of undefined

### ISSUE THREAD

**Issue by ddcollins** [directus/directus#7286]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I bumped from `rc.80` to `rc.88`.

When I navigate to any record of two of my collections I receive the attached errors. The errors don't seem to be breaking any functionality on the page as far as I can tell. Uncertain where these errors are coming from, but my guess is the relation records. I've inspected them and don't see any issues. 

![Image 2021-08-09 at 1 42 03 PM](https://user-images.githubusercontent.com/38921476/128758143-0a897f29-e0cb-4a8f-ba5d-21c3cb8190b8.jpg)

### To Reproduce

I don't know how to reproduce this quite yet. But my two data models have relations
Image, Many to One, Many to Any

### What version of Directus are you using?

9.0.0-rc.88

### What version of Node.js are you using?

directus/directus:9.0.0-rc.88

### What database are you using?

Postgres 11 Alpine

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
Would you be able to share a DB dump with a minimal reproduction? I tried setting up a collection with a file, m2o, and m2a field, but can't get the error to show up..

**Comment by ddcollins** [comment]
> Would you be able to share a DB dump with a minimal reproduction? I tried setting up a collection with a file, m2o, and m2a field, but can't get the error to show up..

I removed out all of my data and still see the error when I open up the create page for a new record, so this seems to be Directus field related. I have a snapshot system around my tables for version controlling and deploying to environments so wondering if I've caused this somehow.

I dumped out just the lesson fields to see if maybe you spot any oddities with it, before I try to dump the entire database (have some things I'd need to remove privacy wise).

[081021_directus_fields.csv](https://github.com/directus/directus/files/6962558/081021_directus_fields.csv)

**Comment by rijkvanzanten** [comment]
The `related_collection` part is read from the relation, so I think we'll have to look for the problem under `directus_relations` instead of `directus_fields` 🙂

**Comment by ddcollins** [comment]
> The `related_collection` part is read from the relation, so I think we'll have to look for the problem under `directus_relations` instead of `directus_fields` 🙂

Solid point! Thinking it'll be easier to just dump the whole database. Let me work on that after a few meetings this morning, but here's the relations table in the mean time.

[081021_directus_relations.csv](https://github.com/directus/directus/files/6962649/081021_directus_relations.csv)

**Comment by rijkvanzanten** [comment]
> Thinking it'll be easier to just dump the whole database.

Yeah.. definitely. Little hard to see anything wrong without knowing the rest of the setup 👍🏻

**Comment by ddcollins** [comment]
> > Thinking it'll be easier to just dump the whole database.
> 
> Yeah.. definitely. Little hard to see anything wrong without knowing the rest of the setup 👍🏻

Am I able to share this dump with you outside of GitHub? Discord looks to block direct messages.

**Comment by rijkvanzanten** [comment]
@ddcollins Yeah! You can either add me as a friend on Discord to enable DMs (Rijk#8055), or send it through email on rijk@directus.io 👍🏻

**Comment by rijkvanzanten** [comment]
Turns out this was a missing row in `directus_relations` caused by a configuration/migration problem.
