### ISSUE TITLE
v-form performance with initialValues

### ISSUE THREAD

**Issue by supermx1** [directus/directus#7299]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

So this is funny. If I try to type in anything on the Data Models page, e.g A collection note or a placeholder text, there is a very serious lag. It takes about 4secs before what I typed appears

FYI: I use a 2020 MacBook Pro - 8GB, 512GB (Intel)

You can listen to the audio of the video to hear my keyboard sound as I type.

https://user-images.githubusercontent.com/9326922/128787633-5c9c5f73-4af4-4043-a4dd-dedf98cadc8d.mp4

### To Reproduce

Create a collection and try adding a note or placeholder text for a field.

### What version of Directus are you using?

RC.89

### What version of Node.js are you using?

14.15.3

### What database are you using?

10.4.17-MariaDB - Source distribution

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

locally

**Comment by supermx1** [comment]
Happening from RC88, and now 89

**Comment by rijkvanzanten** [comment]
How are you running Directus specifically? Is this the dev mode or production?

**Comment by supermx1** [comment]
I think production.
create directory > run. npx create-directus-project . > npx directus start.
That's how I use directus, I don't use the npm run dev

**Comment by supermx1** [comment]
Only a couple. Some are way faster. Still some microsecond lag, but very okay. The affected collections are unusuable. 

The affected collections has a number of relational fields. O2M fields (15 O2M fields)

**Comment by supermx1** [comment]
![Screen Shot 2021-08-10 at 9 45 58 PM](https://user-images.githubusercontent.com/9326922/128932704-ede8e7ff-cc97-45e3-845e-0cc97b9fe40d.jpg)

Plus I see this console error. Don't know why it has 3 errors

**Comment by rijkvanzanten** [comment]
@supermx1 I have a gut feeling that particular error might be a chrome plugin. Would you mind trying this out in an incognito tab and let me know if the error/problem still happens?

**Comment by supermx1** [comment]
https://user-images.githubusercontent.com/9326922/128937822-26e14312-9c80-4150-9de4-56b5661baee5.mp4

Same issue. The errors in the console don't show up in incognito, but the delayed keystroke is still present, even on collections that perform better. If I type really fast in a collection that usually isn't as slow, it will also slow down. My database is MariaDB, I use Xampp to serve the DB. I have a production version on Windows Server 2019, with Caddy as the server. Same issue there too. I tried Safari browser too, it was initially working normally, then a couple of seconds later it slowed down like chrome.

**Comment by rijkvanzanten** [comment]
Yeah noticed the slowdown too, it's updating things it shouldn't on input 👍🏻 

Thanks for confirming those JS errors, they were indeed unrelated

**Comment by rijkvanzanten** [comment]
This particular merge is slowing things down apparently:

https://github.com/directus/directus/blob/86ce598eddcf3b1ce25ad7fdbbc5c9f09c5428a4/app/src/components/v-form/v-form.vue#L135

Not sure why yet

**Comment by Nitwel** [comment]
Had to throttle my CPU 4x in Chrome to also get this problem.
It seems that `use-field-tree` gets calculated every keypress which takes the longest time to finish.
![grafik](https://user-images.githubusercontent.com/22577866/130419534-e50f75de-4a5a-4a3d-b457-6622c0e66a1b.png)

**Comment by Nitwel** [comment]
And `use-field-tree` updates onkeypress because we get the collection name from the injected values which also contain all other fields of the form so updates on every keypress. https://github.com/directus/directus/blob/86ce598eddcf3b1ce25ad7fdbbc5c9f09c5428a4/app/src/interfaces/_system/system-field-tree/system-field-tree.vue#L54-L64
