### ISSUE TITLE
Error inserting images into WYSIWYG UI from Firefox

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#730]
Trying to add an image into the WYSIWYG UI throws an error and doesn't seem to work.

```
InvalidNodeTypeError: The supplied node is incorrect or has an incorrect ancestor for this operation. jquery.js:2240
undefined app.js:60
```

![screen shot 2015-03-19 at 7 18 13 pm](https://cloud.githubusercontent.com/assets/522079/6743154/c8d5002c-ce6c-11e4-99fa-017b6bd98008.png)

**Comment by WellingGuzman** [comment]
This issue is not happening anymore to me, can you check it was fixed to you along the way, or maybe can you remember which version were you using?

**Comment by benhaynes** [comment]
This one seems to be working for me too. Must have been a browser-specific issue with an older version of FireFox. Closing...
