### ISSUE TITLE
Payload/Fields not separated when uploading multiple files via API

### ISSUE THREAD

**Issue by paescuj** [directus/directus#7305]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When uploading multiple files via the API, the payload / values of fields are not processed separately for each file. Instead values are applied to all files, e.g. when defining a title for the first file while omitting the title for the second one, the title for the second file will be the same as for the first file.

Maybe we should also take a look at https://github.com/node-formidable/formidable which could be a replacement for https://github.com/mscdex/busboy (last version has been released 2 years ago).

### To Reproduce

* Upload files:
```js
// similary to example in docs: https://docs.directus.io/reference/api/system/files/#upload-a-file
// "files" being an array, e.g. from a html form

const formData = new FormData();
formData.append('title', 'example1');
formData.append('file', files[0]);
// no title for second file
// formData.append('title', 'example2');
formData.append('file', files[1]);
await fetch(`${directusUrl}/files`, {
  method: 'POST',
  headers: { Authorization: bearer },
  body: formData,
});
```
* Second file will have title set to "example1", instead of filename of second file (https://github.com/directus/directus/blob/main/api/src/controllers/files.ts#L55)

### What version of Directus are you using?

v9.0.0-rc.89

### What version of Node.js are you using?

v16.6.1

### What database are you using?

Postgres 13

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
This is not handled by busboy 👍🏻  It's done in custom logic on our end. If last-release date is the benchmark, it doesn't seem like swapping to formidable is that much better of an option 😅

**Comment by paescuj** [comment]
> This is not handled by busboy 👍🏻 It's done in custom logic on our end. If last-release date is the benchmark, it doesn't seem like swapping to formidable is that much better of an option 😅

Ah okay, thanks 👍 True, although formidable seems to be maintained and they are planning to release v2 at some point 😄

**Comment by crebuh** [comment]
Is it intended that only the first uploaded file will accept the title? When I upload multiple files. The first file get's the correct title all other are named Blob, which is pretty weird 😅 ... but also an issue for working with the media directory. 

Is it possible to customize the name of alle uploaded files, when uploading multiple files at once?

<img width="822" alt="Screenshot 2022-08-16 at 14 25 28" src="https://user-images.githubusercontent.com/5765733/184879384-23332c20-ae8f-4b13-952e-ee557e3d17fe.png">

**Comment by rijkvanzanten** [comment]
@crebuh Is that when using the file uploader in the app, or through the API?

**Comment by crebuh** [comment]
Yes I'm using the API trough the Javascript SDK.

`
const formData = new FormData();

formData.append('file', file.file, file.title);

const result = await this.directusService.client.files .createOne(formData).catch((error) => this.directusService.catchError(error));
`

**Comment by rijkvanzanten** [comment]
If I remember my FormData syntax correctly, it's supposed to be:

```js
const formData = new FormData();

formData.append('title', file.title);
formData.append('file', file.file);

const result = await this.directusService.client.files.createOne(formData).catch((error) => this.directusService.catchError(error));
```

as the order of appending matters

**Comment by crebuh** [comment]
Yes, thank you! that worked 👍
