### ISSUE TITLE
Searching for items in app results in multiple requests

### ISSUE THREAD

**Issue by paescuj** [directus/directus#7307]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Using the search field in the app, e.g. to filter collection items or users, always results in (at least) 3 requests.

In the following example you can see that the request "http://localhost:8080/users?limit=0&fields=id&meta[]=filter_count,total_count&search=t&filter={}" is issued 3 times in addition to some other requests:
![recording](https://user-images.githubusercontent.com/5363448/128862347-7c45d5c3-3475-46df-8ad5-aac8de9c8a48.gif)

I'm not very familiar with Vue, but I assume that the query logic is happening here:
https://github.com/directus/directus/blob/11ea192368bbaf2fe501473ad753da4994e73e8a/app/src/composables/use-items/use-items.ts#L122-L138
When adding `console.log('calling getItems()');` on line 132, you can see that `getItems()` is called 3 times in a row each time the query is updated:
<img width="1657" alt="Screenshot 2021-08-10 at 14 00 40" src="https://user-images.githubusercontent.com/5363448/128863278-d5e93290-ff42-4320-86bf-6a32d5129970.png">

Ref #6093

### To Reproduce

Please see above

### What version of Directus are you using?

v9.0.0-rc.89

### What version of Node.js are you using?

v16.6.1

### What database are you using?

Postgres 13

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

Locally

**Comment by rijkvanzanten** [comment]
Noticed the same doing other operations in the same use-items composable. Gotta handle multi-updates a little cleaner in there 👍🏻

**Comment by rijkvanzanten** [comment]
(FWIW, there will always be 2 requests: one for the data, and one for the result-count. That's expected)

**Comment by paescuj** [comment]
> (FWIW, there will always be 2 requests: one for the data, and one for the result-count. That's expected)

Make sense 👍

**Comment by Nitwel** [comment]
This can be closed when @rijkvanzanten is done with his rewrite of the `useItems` composable. Just so we dont forget.
