### ISSUE TITLE
Directus files endpoint infrequently returns content from a different database

### ISSUE THREAD

**Issue by justrealmilk** [directus/directus#7311]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I was working on my own portfolio when I noticed the files endpoint was returning to me a client's uploads. Naturally I refreshed a few times and it soon returned the correct files. I would expect it sounds pretty strange and surprising.

It should be noted that I am deploying several docker containers which depend on the same Redis cache. Each Directus instance is on a different port and an NGINX server proxy passes each to a sub-directory.

### To Reproduce

I have no idea.

### What version of Directus are you using?

9.0.0-rc.88

### What version of Node.js are you using?

v14.9.0

### What database are you using?

MySQL 8

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
> It should be noted that I am deploying several docker containers which depend on the same Redis cache.

Make sure to use a custom `CACHE_NAMESPACE` value per client! Otherwise the cache keys will resolve to the same, resulting in this behavior 🙂

**Comment by justrealmilk** [comment]
Ah gees! Thanks Rijk
