### ISSUE TITLE
Add error event handler to file stream

### ISSUE THREAD

**Issue by crsgyj** [directus/directus#7340]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

when I use **AssetsService** to **getAsset** a file which is deleted, directus crashed.
I think the reason is that **getAsset** use a stream to read file but haven't handle '**error**' event.

### To Reproduce

Error screenshot:
![image](https://user-images.githubusercontent.com/49174703/128982543-49ece8b6-e2ba-4afe-a4c0-de58d4c37f71.png)
--------------------------------------------

### What version of Directus are you using?

9.0.0-rc.82

### What version of Node.js are you using?

15

### What database are you using?

pg

### What browser are you using?

edge

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
@licitdev We can resolve this by adding another "exists" check here:

https://github.com/directus/directus/blob/6e866487d7709eb8ee95f5bca32128511b8e0356/api/src/services/assets.ts#L50

and throwing a forbidden error when either the file meta record or the file itself are missing.
