### ISSUE TITLE
M2O doesn't account for singleton collection

### ISSUE THREAD

**Issue by jekuer** [directus/directus#7351]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

This started with of the last updates (worked before). Somewhere between  rc83 and rc88.

I have:
a) 1 collection (general) as single object with 1 item.
b) 1 collection (pages) with many items.

A has an O2M field with a relationship to B.
When I open an item of B (= pages), Directus throws the error "[ROUTE_NOT_FOUND] Route /general/1 doesn't exist."
When I click the M2O field within B, I also see strange information, saying "1 item" found, but then multiple lines.
<img width="622" alt="Looking-at-A-from-within-B" src="https://user-images.githubusercontent.com/8572883/129008725-ded0afa3-2401-4f17-81a6-375aa2e71431.png">

### To Reproduce

1. Create a single object collection.
2. Create a regular collection.
3. Add multiple items to the regular collection.
4. Add a O2M field within the single object collection and create the respectively necessary relationship field in the other collection during setup.
5. Maybe repeat the previous step (I have multiple O2M fields during those collections, but I think it should make not difference).
6. Try to connect them.
7. Go into an item of the regular collection -> should throw the error.

![image](https://user-images.githubusercontent.com/8572883/129009355-48c5ac40-740b-49da-8684-7a46b059cf2e.png)

### What version of Directus are you using?

9.0.0-rc.89

### What version of Node.js are you using?

The one from the Directus docker image

### What database are you using?

Postgres 11

### What browser are you using?

Chrome, Edge

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by AndreyKindin** [comment]
Have the Same issue on rc.90
