### ISSUE TITLE
Required flag unchecked after save field schema

### ISSUE THREAD

**Issue by nazariydj** [directus/directus#7356]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Required flag remains unchecked after save field schema. 

https://user-images.githubusercontent.com/17914536/129065347-9ff017c8-562e-44c1-b70e-bcb4545ae7f7.mp4

### To Reproduce

1. Open some Collection Data Model
2. Edit some field and make it Required
3. Save
4. Re-open field settings (field edit form)

### What version of Directus are you using?

9.0.0-rc.89

### What version of Node.js are you using?

16.6.1

### What database are you using?

MySQL:8.0.26

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
Is this a fresh installation or an upgraded one from an earlier version? If the latter, did you run all the database migrations?

**Comment by nazariydj** [comment]
```
{
    "collection": "events",
    "field": "start",
    "type": "dateTime",
    "schema": {
        "name": "start",
        "table": "events",
        "data_type": "datetime",
        "default_value": null,
        "max_length": null,
        "numeric_precision": null,
        "numeric_scale": null,
        "is_generated": false,
        "is_nullable": false,
        "is_unique": false,
        "is_primary_key": false,
        "has_auto_increment": false,
        "foreign_key_column": null,
        "foreign_key_table": null,
        "comment": ""
    },
    "meta": {
        "id": 56,
        "collection": "events",
        "field": "start",
        "special": null,
        "interface": "datetime",
        "options": null,
        "display": "datetime",
        "display_options": {
            "format": "dd/MM/yyyy HH:mm"
        },
        _"readonly": false,
        "hidden": false,_
        "sort": 8,
        "width": "half",
        "group": null,
        "translations": null,
        "note": null,
        "conditions": null,
        **"required": 1**
    }
}
```
