### ISSUE TITLE
Missing Translation for directus_webhooks

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#7361]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

![Screen Shot 2021-08-11 at 9 34 30 AM](https://user-images.githubusercontent.com/522079/129085906-11910f7a-b50a-470b-8fac-e2dc5f53d4b7.png)

### To Reproduce

See button text above

### What version of Directus are you using?

INTERNAL

### What version of Node.js are you using?

INTERNAL

### What database are you using?

INTERNAL

### What browser are you using?

Chrome

### What operating system are you using?

INTERNAL

### How are you deploying Directus?

INTERNAL

**Comment by rijkvanzanten** [comment]
I'm assuming we could easily fix this by using `collection.name` instead of `collection.collection` in that button
