### ISSUE TITLE
Strange status

### ISSUE THREAD

**Issue by Silbad** [directus/directus#7362]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Hello, I create a new project,

I change the locale in my admin profile (french) and I see this strange status :

![image](https://user-images.githubusercontent.com/31576982/129091622-9a784dd7-b93d-4822-aedd-51d14ba7ff98.png)

Thanks

### To Reproduce

create project
edit admin
change locale to french

### What version of Directus are you using?

rc.90

### What version of Node.js are you using?

12

### What database are you using?

mysql 8

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
I don't understand a lot of French, but I'm pretty sure that ain't it 🙇🏻‍♂️

**Comment by Silbad** [comment]
Oui je ne connais pas ce mot ^^
The issue is common to all languages.
Merci !

**Comment by Silbad** [comment]
Mm I see :)
![image](https://user-images.githubusercontent.com/31576982/129093204-dac4f0ab-1043-4894-8098-c3245409524b.png)

**Comment by rijkvanzanten** [comment]
Ahh! There it is, @dimitrov-adrian secretly snuck in some Bulgarian into the English language file 😄 

https://github.com/directus/directus/pull/7358/files#diff-df42ecafe708c5d98ddbebfb3a7238207aab0c3c3c93920d616221136c08ad6aR804

**Comment by dimitrov-adrian** [comment]
Oh, ugh.. sorry about that. Looks like copy/paste issue on my side.

**Comment by rijkvanzanten** [comment]
No worries! I totally glanced over it while reviewing that PR as well 👍🏻
