### ISSUE TITLE
Reported 2 issues @ huntr.dev

### ISSUE THREAD

**Issue by B3EF** [directus/directus#7432]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

XSS | SSRF via file upload

### To Reproduce

https://huntr.dev/bounties/1625583650823-directus/directus/
https://huntr.dev/bounties/1625583197189-directus/directus/

### What version of Directus are you using?

tested in the demo site

### What version of Node.js are you using?

tested in the demo site

### What database are you using?

tested in the demo site

### What browser are you using?

firefox/brave

### What operating system are you using?

tested in the demo site

### How are you deploying Directus?

tested in the demo site

**Comment by rijkvanzanten** [comment]
Hi @B3EF. As per our [Security Guidelines](https://github.com/directus/directus/blob/main/security.md), please email security@directus.io directly for any security problems.

**Comment by B3EF** [comment]
hi @rijkvanzanten i have tried to mail the security issues and didn't get any response

**Comment by rijkvanzanten** [comment]
Ah that was you. You just send the same exact links again on email..

**Comment by B3EF** [comment]
yes , these one are the adversary pages of the bugs can you check and verify it, @rijkvanzanten
