### ISSUE TITLE
Import / Export data issue on CSV type

### ISSUE THREAD

**Issue by minyangu-bgl** [directus/directus#7434]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When creating a CSV field, it will be saved into db as VARCHAR field with comma separated values. However, when I try use export/import for bulk updates on the row, the CSV field handling are different and result in data issues.

Export will change the `comma separated string` => `string[]`
But the import util via API will not change the exported `string[]` => `comma separated string`, hence resulted in seeing some extra `[` `]` and double quotes as well.

Expected behaviour: import/export tool should be consistent to the GUI handling, same logic should be applied when handling CSV field.

### To Reproduce

1. Create a CSV field and input two tag value. This is what I see inside DB table for this field:
```
mobile,desktop
```

2. When using the GUI to export the entire collection as CSV, the value exported in the file is:
```
["desktop","mobile"]
```

3. When calling the import util API (https://docs.directus.io/reference/api/system/utilities/#import-data-from-file) to update the collection by uploading previously exported file, it will mess up the table data since there is no Array=>String conversion: 
```
["desktop","mobile"]
```

and now I see this inside the GUI:
![image](https://user-images.githubusercontent.com/49973259/129577715-20c227b2-bdcd-4833-ac17-f29c4b1398ee.png)

### What version of Directus are you using?

v9.0.0-rc.90

### What version of Node.js are you using?

16.6.1

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

locally using docker compose

**Comment by minyangu-bgl** [comment]
Just highlight the fix here could be on the `csv export` function, so it should export as `comma separated string` rather than the array `string[]`. The import tool can then just import `comma separated string` without any problem.

**Comment by rijkvanzanten** [comment]
> Just highlight the fix here could be on the csv export function, so it should export as comma separated string rather than the array string[]. The import tool can then just import comma separated string without any problem.

Disagreed. The export should export the API format. If we start diverging in what formats the different save options generate, it'll become near impossible to properly import afterwards. 

The main thing is that we'll have to json parse the incoming values on the csv layer to make sure we cast any potential nested object structures back from a flat string.

**Comment by minyangu-bgl** [comment]
agree, makes more sense to fix on the importer itself.
