### ISSUE TITLE
Use the "Branch" value combining option, and use the "Show Selected" toggle

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#7443]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When showing only the selected items, it only shows the stored values, and doesn't allow expansion of a parent item to show the children. 

Children should be considered "selected" based on the chosen branching strategy

### To Reproduce

Use the "Branch" value combining option, and use the "Show Selected" toggle

### What version of Directus are you using?

rc.90

### What version of Node.js are you using?

16.6.1

### What database are you using?

Postgres 13

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

Locally

**Comment by azrikahar** [comment]
This should be resolved by #10125.
