### ISSUE TITLE
[SDK, TypeScript] Filter type does not accept logical operators

### ISSUE THREAD

**Issue by davidsandoz** [directus/directus#7475]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

The [`Filter` type](https://github.com/directus/directus/blob/main/packages/sdk/src/items.ts#L68) accepts only attributes of the entity it is filtering on, while it should also allow for [logical operators](https://docs.directus.io/configuration/filter-rules/#logical-operators).

This was reported first in discussion #4531.

### To Reproduce

Taking back the example from #4531:

```typescript
const target = await this.directus.items("users").readMany({  
  filter: {
    _or: [
      {
        userId: {
          _eq: 1
        },
      },
      {
        provider: {
          _eq: "google.com"
        }
      }
    ]
  }
});
```

This leads to the following error: `Object literal may only specify known properties, and '_or' does not exist in type 'Filter<User>'`

#### Workaround

Add `as any` to the filter:
```typescript
const target = await this.directus.items("users").readMany({  
  filter: {
    _or: [
      {
        userId: {
          _eq: 1
        },
      },
      {
        provider: {
          _eq: "google.com"
        }
      }
    ]
  } as any // <==========
});
```

### What version of Directus are you using?

v9.0.0-rc.90

### What version of Node.js are you using?

14.7.3

### What database are you using?

MySQL 5.7

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

Managed cloud server

**Comment by jaycammarano** [comment]
I believe the issue is that you are using deprecated syntax, `.read(). Which was replaced with `.readMany()` and `.readOne()`.

**Comment by rijkvanzanten** [comment]
[The SDK doesn't have a `.read()` method](https://github.com/directus/directus/blob/main/packages/sdk/src/base/items.ts). Make sure to be on the latest version of the SDK 👍🏻

**Comment by davidsandoz** [comment]
@rijkvanzanten It happens with `.readMany()` as well. Apologies for the old example. I've updated it.

We can actually see in the [type definition of `Filter<T>`](https://github.com/directus/directus/blob/main/packages/sdk/src/items.ts#L68) that it only accepts the attributes of `T`, which doesn't include the logical operators.

Can you please reopen the issue? 🙂

**Comment by davidsandoz** [comment]
@Oreilles Accepting filter operators as **value** was already the case before.

The issue here is about accepting *logical operators* (`_or`, `_and`, which are different from *filter operators*) as **attribute**, where we currently only accept `K in keyof T`.

**Comment by martijn-dev** [comment]
It looks like this issue is back in the new SDK. I'm getting type errors if I try to use operators like `_or` in the filter object.

```ts
 directus.request(
        readItems('users', {
          filter: {
            _or: [ //<- Type '{ _or: { name: string; }[]; }' is not assignable
              {
                name: 'martijn',
              },
              {
                name: 'directus',
              },
            ],
          },
        }),
      )
```

**Comment by br41nslug** [comment]
@martijn-dev I am aware and will be present in an upcoming release :) please do create a new issue when you find these things tho instead of commenting on an issue that has been closed for 2 years
