### ISSUE TITLE
Windows Compile Error

### ISSUE THREAD

**Issue by ernst86913** [directus/directus#7484]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Running latest version of Directus from source code Aug 18... on Windows.

a) Performed lerna clean
b) Performed Cache clean
c) Deleted NPM Cache Folder
d) Delete node_modules Folder

**1) Express-Pino-Logger not found**

PS C:\Users\rer\Documents\Coding\directus> npx directus start     
Error: Cannot find module 'express-pino-logger'
Require stack:
- C:\Users\rer\Documents\Coding\directus\api\dist\app.js
- C:\Users\rer\Documents\Coding\directus\api\dist\server.js
- C:\Users\rer\Documents\Coding\directus\api\dist\start.js
- C:\Users\rer\Documents\Coding\directus\api\dist\cli\index.js
- C:\Users\rer\Documents\Coding\directus\api\cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (C:\Users\rer\Documents\Coding\directus\api\dist\app.js:18:47)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\rer\\Documents\\Coding\\directus\\api\\dist\\app.js',
    'C:\\Users\\rer\\Documents\\Coding\\directus\\api\\dist\\server.js',       
    'C:\\Users\\rer\\Documents\\Coding\\directus\\api\\dist\\start.js',        
    'C:\\Users\\rer\\Documents\\Coding\\directus\\api\\dist\\cli\\index.js',   
    'C:\\Users\\rer\\Documents\\Coding\\directus\\api\\cli.js'
  ]
}

2) Installing express-pino-logger using npm

3) Running npx directus start again results in:

PS C:\Users\rer\Documents\Coding\directus> npx directus start                  
11:30:45 ­ƒÜ¿ "DB_CLIENT" Environment Variable is missing.

BUT - I have the .env file in API folder... and it was working in the past... any change regarding the location where the .env file should reside?

Thanks,
Roman

### To Reproduce

See above

### What version of Directus are you using?

v9.0.0-rc.90 + Latest Commits

### What version of Node.js are you using?

node: 'v16.7.0', npm: '7.20.3'

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

locally

**Comment by paescuj** [comment]
Have you performed all the steps from https://docs.directus.io/contributing/running-locally/?

**Comment by ernst86913** [comment]
Yes… and everything worked fine till adding recent code commits… 

LG,
Roman

Von meinem iPhone gesendet

**Comment by paescuj** [comment]
Cannot reproduce this with recent commits. Although I think you are not supposed to run `npx directus start` in a local version of the repository. Did you mean to run `npm run dev -- --scope directus --scope @directus/app`?

**Comment by ernst86913** [comment]
... in the past npx directus start worked for me... I think it actually was guidance from Ben or Rijk to do it that way... 

There seems to be something wrong with SHARP for WINDOWS:

Something went wrong installing the "sharp" module
directus: Cannot find module '../build/Release/sharp-win32-x64.node'

And I saw there were some new commits around "Sharp" recently....

**Comment by rijkvanzanten** [comment]
Can you try installing with `npm install --build-from-source`? That should make sure to build those sort of native bindings fresh 🤔
