### ISSUE TITLE
Rows are not removed from DB for m2m relation even when cascade delete is set

### ISSUE THREAD

**Issue by TonyWar** [directus/directus#7490]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When I unselect the m2m item with cascade delete set the row is not deleted from DB.

Structure:
I have a Todo collection with m2m relation to Todo Data.
in Todo Data I have a m2o relation to Event Type.

Triggers for m2o field:
![image](https://user-images.githubusercontent.com/35558401/129921180-97d03f39-e07e-441f-985c-d369cd349305.png)
Triggers for m2m field:
![image](https://user-images.githubusercontent.com/35558401/129921248-e25b24a2-6b34-4b58-bb23-960e297bd6b9.png)

when I remove an m2m Item I also want to remove Todo Data item:
![image](https://user-images.githubusercontent.com/35558401/129921471-64c41b18-a4e5-4db1-870a-71abbed360d8.png)

### To Reproduce

1. Create a collection, which you will use for m2o relation (event_type with string field)
2. Create a collection with m2o relation with previous one (ex. todo_data)
3. Create a collection with m2m relation (ex. todo)
4. Add some item to m2m relation in item of todo collection and save
5. Remove m2m item in edit item of Todo collection form
6. Check list of todo_data items

### What version of Directus are you using?

9.0.0-rc.90

### What version of Node.js are you using?

16.4.0

### What database are you using?

Postgress 12

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
If I understand your model correctly, it sounds like this is working correctly.

Your collection names are a little confusing, so let me illustrate with a m2m setup of users that can have multiple favorite articles.

You have `users <- favorites -> articles`. The cascade goes out from the foreign keys:

```
users    favorites         articles
         id
id ----> users_id       
         articles_id <---- id
```

In a m2m setup, you have 3 cascading options to configure:

1) What happens to favorites when you _deselect_ an article from the users detail page
2) What happens to favorites when you _delete_ a user
3) What happens to favorites when you _delete_ an article

You can't configure "Delete the user when the article is deleted", which is what I believe you're asking for 👍🏻
