### ISSUE TITLE
Fields are in random order for Advanced Filter and Layout Options

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#7491]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

They should be sorted using the field sort order (not alphabetical).

### To Reproduce

Go to the Filter sidebar in the App

### What version of Directus are you using?

INTERNAL

### What version of Node.js are you using?

INTERNAL

### What database are you using?

INTERNAL

### What browser are you using?

Chrome

### What operating system are you using?

INTERNAL

### How are you deploying Directus?

INTERNAL

**Comment by supermx1** [comment]
Great. This is super important.
