### ISSUE TITLE
File import doesn't return file object as documented

### ISSUE THREAD

**Issue by saptha** [directus/directus#7498]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

As per this reference, I tried importing a file and expecting the file object in return. 
https://docs.directus.io/reference/api/system/files/#import-a-file

The import is successful, I can see the file from the admin panel, but the API doesn't return the file object as expected.
It just says 1

### To Reproduce

https://docs.directus.io/reference/api/system/files/#import-a-file

### What version of Directus are you using?

v9.0.0-rc.75

### What version of Node.js are you using?

v14.17.0

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
Please update to the last version of Directus. If the problem still persists there, we can reopen and investigate 👍🏻

**Comment by saptha** [comment]
I updated to the latest version 9.0.0-rc.90 and the issue persists. It is not returning the file object on import.
However, I noticed that it is returning results for the admin user.

**Comment by rijkvanzanten** [comment]
Make sure the user you're uploading the file as has read access to directus_files 👍🏻

**Comment by saptha** [comment]
Yes, it is. Below are the permissions set.

`        {
            "uploaded_by": {
                "_eq": "$CURRENT_USER"
            }
        }`

Note, this issue happens only for file import, whereas file upload works fine as expected.

When I checked the database, I see the uploaded_by column is NULL for the imported files. 
Wondering how it could be so?
