### ISSUE TITLE
Default value gets set to 'NULL' when Allow NULL value is changed to true

### ISSUE THREAD

**Issue by dstoyanoff** [directus/directus#7522]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When a field's Allow NULL value setting is updated from false to true, the column's default value gets set to stringified 'NULL' 

### To Reproduce

- Create a new collection
- create 2 fields
  - field1 - Allow NULL value = true
  - field2 - Allow NULL value = false
- inspect the database - everything is ok.
- update field2 to have Allow NULL value = true
- inspect the database - field2's default value got updated to `NULL::character varying`

### What version of Directus are you using?

v9.0.0-rc.90

### What version of Node.js are you using?

v16.5.0

### What database are you using?

Postgres 12

### What browser are you using?

Edge

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
I think this might be a quirk in Postgres actually!

Before:

<img width="988" alt="CleanShot 2021-08-20 at 10 20 09@2x" src="https://user-images.githubusercontent.com/9141017/130247647-5b8fd653-c085-44e0-b274-02d6591ab3d7.png">

SQL:

```sql
ALTER TABLE articles
	ALTER COLUMN title SET NOT NULL,
	ALTER COLUMN title SET DEFAULT NULL;
```

After:

<img width="1010" alt="CleanShot 2021-08-20 at 10 22 34@2x" src="https://user-images.githubusercontent.com/9141017/130247971-73756dda-8709-4303-acdd-bc9368b2ef6b.png">

**Comment by rijkvanzanten** [comment]
It still seems to behave as expected though:

When inserting directly in SQL, omitting the value for title:

`ERROR:  null value in column "title" of relation "articles" violates not-null constraint`

In Directus:

<img width="595" alt="CleanShot 2021-08-20 at 10 26 43@2x" src="https://user-images.githubusercontent.com/9141017/130248542-6ee85a26-d135-4654-a89f-257d95ebcdd5.png">

**Comment by rijkvanzanten** [comment]
I think this is just a confusing quirk in Postgres on how it displays a default value NULL for string type columns that aren't nullable. No idea why it does that tho!
