### ISSUE TITLE
Only Admins can Delete Users

### ISSUE THREAD

**Issue by WellingGuzman** [directus/directus#753]

**Comment by WellingGuzman** [comment]
@benhaynes Do we want to delete users from the listing? or this is too much?

**Comment by benhaynes** [comment]
No need to do it on the listing page (yet)... but we can still delete them from the detail page. Right? If that's working then we can probably close this.

**Comment by benhaynes** [comment]
Currently admins can view/delete any users... however, the status column is also available to normal users for their OWN account. This means that a non-admin user can draft or delete their own account. This should be disabled.

Also, users should be able to see (view only) other user detail pages.

**Comment by WellingGuzman** [comment]
@benhaynes any user users regardless of group? I believe it will be best too only see your current group users details. what do you think?

**Comment by benhaynes** [comment]
I see the users listing and detail pages as a corporate directory – so I like the idea of people having view access to all users. We should hide certain fields for non-admins though (token, pass, email_messages, etc)... basically it's a profile page.

This will also help with this feature when we're ready to add it:
http://feathub.com/directus/directus/+5

**Comment by WellingGuzman** [comment]
@benhaynes now that's better Idea, maybe we should do that by default. I have more ideas to bring to this, but I wont think much so we don't get sidetracked.

---

In case I forgot, in case you want to open a Group that doesn't need to know there are more groups or who are in the other groups. A group that can see other group information too.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/4d6915cf894d11a67c96da0cc8e3d297e314cd4e and https://github.com/directus/directus/commit/9a9e04ea4974e7515219745a5474dcae4536d436
