### ISSUE TITLE
The AxiosTransport of the DirectusSDK produces error: 'TypeError: axios_1.default.create is not a function'

### ISSUE THREAD

**Issue by rdytogokev** [directus/directus#7538]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I am trying to follow the instructions for installing and using the SDK as stated in the documentation. While I don't think the error is related, I should point out that I am trying to use the SDK in a SvelteJS app using the Routify router and starter template.

### To Reproduce

(1) From the terminal, create a new folder to hold your app.
`md testsdkwithsvelte`

(2) From the terminal, navigate to your new folder.
`cd testsdkwithsvelte`

(3) From the terminal, install the Svelte Routify Starter Template.
`npx @roxi/routify init`

(4) From the terminal, install the Directus SDK.
`npm install @directus/sdk`

(5) Edit the main App component file (`testsdkwithsvelte\src\App.svelte`) to use the SDK.
```js
<script>
  import { Router } from "@roxi/routify";
  import { routes } from "../.routify/routes";
  import { Directus } from '@directus/sdk';

  const directus = new Directus('http://localhost:8055');
</script>

<style  global>
  @import "../assets/global.css";
</style>

<Router {routes} />
```

(6) From the terminal, try to run the App.
`npm run dev`

(7) Once the app is running, In the browser, visit `localhost:5000`.  You will see error in two ways: (1) a pretty print of the error overlaying the page and (2) in the console.

The console error should look something like the included image.
<img width="439" alt="Screen Shot 2021-08-21 at 6 41 18 PM" src="https://user-images.githubusercontent.com/2678654/130365356-1aed5ff4-f716-41bb-a00b-d6cd1bc4b70b.png">

### What version of Directus are you using?

v9.0.0-rc.90

### What version of Node.js are you using?

16.3.0

### What database are you using?

SQLite3 5.0.2

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by rdytogokev** [comment]
Update: The discussion related to this on the Directus Discord #SDK channel has led me to believe that the problem might be a conflict with the SDK and the Rollup bundler.  One of the other members said that when they use the Vite bundler, the problem does not exist. If this issue gets fixed, it will probably help all users of the Rollup bundler to use Directus. Because I now have a workaround using Vite, there is no rush for me personally to have this fixed. However, I ask that you do consider keeping this issue open and resolving this for Rollup users at your convenience.  Thanks.
```
AzraeL --
additional info: I tried out Routify + Vite 
(https://github.com/lamualfa/routify-vite) 
and directus works as well so I'm fairly 
certain it's a bundler related issue```

**Comment by rijkvanzanten** [comment]
As far as I can tell, the exports of the SDK are defined correctly:

https://github.com/directus/directus/blob/d3a8a133962359cb81224e1a4ab8b6752c6b537a/packages/sdk/package.json#L9-L15

(though to be honest, `npm`'s resolution, and the whole mess that is moving from CJS to ESM in Node doesn't make this any easier)

What was the specific rollup configuration used that failed?

In the meantime, with the exports seemingly looking correct, no clear direction on what to change to make it work, and the problem only happening on a single bundler with a specific configuration, I'll have to close this as something we can't actively fix
