### ISSUE TITLE
Incompatible JS String.prototype.replaceAll() function in older browser functions

### ISSUE THREAD

**Issue by Jason-CKY** [directus/directus#7540]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Not sure if this qualifies here, but I think it is important for browser compatibility of the directus app. The directus app uses `replaceAll()` function in `app/src/interfaces/input-rich-text-html/useMedia.ts` and `app/src/modules/docs/routes/static.vue` in the latest patch. These javascript versions are incompatible with older browsers like chrome version <84. 

There are 2 easy ways to solve this issue but I'm not sure if there are any issues with those:
1) use str.replace(new RegExp(find, 'g'), replace)
[https://stackoverflow.com/questions/1144783/how-to-replace-all-occurrences-of-a-string-in-javascript]
2) import 'core.js' to polyfill the functions for older browsers

Let me know if you need a PR to fix this issue

### To Reproduce

Run directus on an older version of browser like chrome 4-84, firefox 2-76, etc. 

### What version of Directus are you using?

v9.0.0-rc.90

### What version of Node.js are you using?

-

### What database are you using?

-

### What browser are you using?

Chrome 4-84

### What operating system are you using?

-

### How are you deploying Directus?

-

**Comment by rijkvanzanten** [comment]
I don't think this enough of an issue to warrant special treatment. Chrome 84 and Firefox 76 are both over a year old, and both have a very active (automated) release strategy. Besides, as per caniuse.com, these older versions are barely used. We aim to support the currently available versions of all the major browsers (which is already enough of a pain as is with Safari being the way it is).
