### ISSUE TITLE
Use custom role didn't work in Roles e Permissions

### ISSUE THREAD

**Issue by hermesalvesbr** [directus/directus#7584]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

https://user-images.githubusercontent.com/379850/130688585-cd58e3d8-8fc1-4eb0-b7ff-d0eb9e9dca2f.mov

When i set the new custom role for permission, didn't work. 

### To Reproduce

![Uploading Captura de Tela 2021-08-24 às 17.55.38.png…]()
It doesn't display the custom icon, and the custom permission doesn't work either.

### What version of Directus are you using?

v9.0.0-rc.91

### What version of Node.js are you using?

node --version v16.5.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS, Windows

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
@Nitwel I have a sneaking suspicion something in here might be a little too lenient: https://github.com/directus/directus/pull/7459

**Comment by zebapy** [comment]
This still seems like an issue in rc 90

**Comment by rijkvanzanten** [comment]
@zebapy the linked fix is marked as included in 92, so that's correct 👍🏻
