### ISSUE TITLE
Custom role user can not edit profile. 

### ISSUE THREAD

**Issue by u12206050** [directus/directus#7585]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

User can not edit own profile when having custom role.

<img width="893" alt="Screenshot 2021-08-24 at 23 14 58" src="https://user-images.githubusercontent.com/6641242/130691210-8b16ca7f-38d0-4edb-ac5f-ea5e0013a18e.png">

`Interface "input" not found.`

The role has App Access and just the default permissions for system collections.

Also have issues with my own collections that it just shows a blank page even though users should be able to view it.

### To Reproduce

Create a custom role
Create a user with the new custom role
Login as said user
Try to edit profile

### What version of Directus are you using?

9.0.0-rc.91

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

chrome

### What operating system are you using?

m1 mac osx

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
How did you install Directus? Is this an update on an older database?

**Comment by u12206050** [comment]
I installed via cli. V90, bfirst, but that also didn't work, I then updated
to V91 and did the directus database migration, with same result.
Only main difference I saw, was on V90 the sidebar still showed when
selecting a collection where as now in V91 the entire page is blank.

**Comment by u12206050** [comment]
Solved? I found since I was using oauth the language property was set on the user object. This caused all the issues, reverting it back to `en-US` fixed all the problems.

Someway to fallback to `en-US` if a translation isn't found?
