### ISSUE TITLE
Suspended user that logged in via oauth in redirect loop

### ISSUE THREAD

**Issue by u12206050** [directus/directus#7592]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Suspended user that logged in via oauth simply redirects to auth provider again and again. Just seeing a blank page with no message about what is going on.

Looking at the log output I see:

```
07:56:49 🐛 Invalid user credentials.
07:56:49 ✨ request completed GET 401 /server/info?limit=-1 4ms
07:56:49 ✨ request completed POST 200 /auth/refresh 9ms
07:56:49 🐛 Invalid user credentials.
07:56:49 ✨ request completed GET 401 /server/info?limit=-1 3ms
07:56:49 ✨ request completed POST 200 /auth/refresh 8ms
07:56:49 🐛 Invalid user credentials.
07:56:49 ✨ request completed GET 401 /server/info?limit=-1 4ms
07:56:49 ✨ request completed POST 200 /auth/refresh 16ms
07:56:49 🐛 Invalid user credentials.
……
```

### To Reproduce

1. Setup directus with outh login.
2. Create a user and in separate window login using oauth.
3. As admin suspend the user, by removing them from their role. 
4. Try to refresh the user window.

### What version of Directus are you using?

9.0.0-rc.91

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

chrome

### What operating system are you using?

m1 mac osx

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
Hi, it's been awhile but just wondering have you tested this with the latest version (rc.93)? I tried it with keycloak but I can't seem reproduce it. 

If this bug is still present for you, would you mind sharing what is the specific oauth provider you were using?

**Comment by u12206050** [comment]
Yes thanks this worked since rc92.
