### ISSUE TITLE
Multiple "Translations" on a collection breaks the collection

### ISSUE THREAD

**Issue by LevinGermann** [directus/directus#7613]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When I create more than 1 Translation fields on my data model, I can't access the collection anymore.
Opening the collection fails with:

```
{
  "errors": [
    {
      "message": "select \"trails\".\"identifier\", \"trails\".\"name\" from \"trails\" order by \"trails\".\"identifier\" asc limit $1 - column trails.name does not exist",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### To Reproduce

1. Create from scratch with new Postgres DB
2. Create new Collection, name “trails”, primary key “identifier”, manually entered string
3. create new field of type Translations called “name”, auto-generate
4. create new field of type Translations called “description”, auto-generate
5. go to collection “trails”

### What version of Directus are you using?

9.0.0-rc.9.1

### What version of Node.js are you using?

v16.7.0

### What database are you using?

PostgreSQL 13.2

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
This was fixed in the new translations interface https://github.com/directus/directus/pull/7727 🙂
