### ISSUE TITLE
Errors inside hooks dont go trough the API

### ISSUE THREAD

**Issue by Attacler** [directus/directus#7649]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When using a custom hook that throws an error, you do get the error in Directus itself but not trough the api.

Inside Directus:
![image](https://user-images.githubusercontent.com/42644889/131108283-e9f7b395-414a-4c75-83d9-2a93bf9b5f90.png)
Trough the API:
![image](https://user-images.githubusercontent.com/42644889/131108314-60a305ab-016b-49a0-b50d-24e13f1ca566.png)

### To Reproduce

Create a hook that throws an error on before edit/create.
After that try to trigger it trough the API and trough the Directus interface.

### What version of Directus are you using?

RC90

### What version of Node.js are you using?

v14.0.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by Attacler** [comment]
this will do:
`
module.exports = function registerHook() {
  return {
    "items.create.before": function () {
      throw new Error("test");
    },
  };
};`

When you try from within directus it will show up:
![image](https://user-images.githubusercontent.com/42644889/131222485-23d6e974-fae2-4e76-8af5-794f5c522550.png)

But with postman:
![image](https://user-images.githubusercontent.com/42644889/131222491-feb2df65-3f26-4117-af29-086978e64d3f.png)

**Comment by Markario** [comment]
Errors not extended from BaseException only append error details when an admin is authenticated.

https://github.com/directus/directus/blob/7ed486247a5c7957f3a2437b84e6a4ad394994f0/api/src/middleware/error-handler.ts#L63

**Comment by rijkvanzanten** [comment]
Good catch @Markario. That's actually by design, as you wouldn't want to leak any potential problems in your specific functionality as that could be a security risk.

@Attacler Try extending from BaseException (included in `exceptions`), or throw one of the exceptions that's already provided

**Comment by Attacler** [comment]
Indeed works, sorry for the late reply.

**Comment by Kematia** [comment]
> Try extending from BaseException

Extending from `BaseException` still gets blocked by the error handler:

![image](https://user-images.githubusercontent.com/17851386/135428363-4fcd4e2a-f7df-4aed-94bc-008282aa4bfc.png)
![image](https://user-images.githubusercontent.com/17851386/135428383-80332d11-2ff7-4005-8df8-5ce37f460c9f.png)
![image](https://user-images.githubusercontent.com/17851386/135428401-531decd8-1b3a-43fb-8d02-ccc155ea5397.png)


> That's actually by design, as you wouldn't want to leak any potential problems in your specific functionality as that could be a security risk.

Could we have an escape hatch for this? I'd like to provide specific errors from my custom hooks/endpoints to my frontend.

To keep the existing behaviour the developer could have to opt-in with a prefix (`error.code=PUBLIC_...`) or an error property (`error.public: true`).

@rijkvanzanten what do you think?

**Comment by rijkvanzanten** [comment]
> Extending from BaseException still gets blocked by the error handler:

That's very odd. How are you importing BaseException? Maybe it's a difference in imported object that we're comparing here?:

https://github.com/directus/directus/blob/e95404a1daea19b75f61a88ddc877b1f82ef5cb4/api/src/middleware/error-handler.ts#L18-L20

> Could we have an escape hatch for this? I'd like to provide specific errors from my custom hooks/endpoints to my frontend.

I'd rather not. The BaseException is itself a very thin wrapper around `Error` and should be used for purposes like this 👍🏻

**Comment by joselcvarela** [comment]
I found that `BaseException` is not being passed into `registerHook` as parameter. This probably happens because it's part of `shared`.

Maybe we could include it on `exceptions` parameter?

@Kematia are you importing `BaseException` like this:
`const { BaseException } = require('@directus/shared/exceptions');` 

Here is an working example:
```
const { BaseException } = require('@directus/shared/exceptions');

module.exports = function registerHook({ exceptions }) {
	return {
		'items.create.before': function () {
			throw new BaseException('test', 500, 'BLA');
		},
	};
};
```
![msedge_jDYXIutghf](https://user-images.githubusercontent.com/14039341/135578072-00289f4e-2f78-4e2f-93fe-1a272fa7c764.png)

**Comment by Kematia** [comment]
Here's my testing code:
![image](https://user-images.githubusercontent.com/17851386/135578276-de067e36-72d4-459a-82d6-183624793d58.png)


While authorized as admin via a static token, I get an error with mycustom message, but default code or status:
![image](https://user-images.githubusercontent.com/17851386/135578376-2171b567-f541-48e8-97ad-b80f6aa4a657.png)

While not authorized, I get the generic message:
![image](https://user-images.githubusercontent.com/17851386/135578443-03897b83-4acc-463c-937a-93d553936d33.png)

**Comment by Kematia** [comment]
> > Extending from BaseException still gets blocked by the error handler:
> 
> That's very odd. How are you importing BaseException? Maybe it's a difference in imported object that we're comparing here?:

See above ⬆️

> https://github.com/directus/directus/blob/e95404a1daea19b75f61a88ddc877b1f82ef5cb4/api/src/middleware/error-handler.ts#L18-L20
> 
> > Could we have an escape hatch for this? I'd like to provide specific errors from my custom hooks/endpoints to my frontend.
> 
> I'd rather not. The BaseException is itself a very thin wrapper around `Error` and should be used for purposes like this 👍🏻

Is BaseException supposed to pass the custom exception code and message? Or does it get overwritten by the error handler (if not an admin)?
