### ISSUE TITLE
Float & Decimal Input with Scale Saving Issue

### ISSUE THREAD

**Issue by vslzl** [directus/directus#7671]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When editing a float or decimal field, if you use scale part, field becomes null. 

eg: 
> input: 10
> output: 10

> input: 10,1
> output: null

I'm not sure but my computers language is tr-TR, and we use ',' as scale delimiter. UI doesn't allows me to type '.' instead. At the end, I think this leads decimal/float parsing error which results null value at database.

I'm using `MSSQL`

Workaround was changing float/decimal fields to integer and note it to the user to use eg: grams instead of kilograms. 

### To Reproduce

1. create any field with float/decimal with default settings.
1. set interface to manual input
1. go and add/edit collection items field with 10,2 (use ',' as scale delimiter which may depends on your browser language, I think. mine was tr-TR)
1. save
1. display the item

### What version of Directus are you using?

9.0.0-rc.91

### What version of Node.js are you using?

v14.15.4

### What database are you using?

MSSQL (2019-latest)

### What browser are you using?

Firefox 91.0.2 (64-bit)

### What operating system are you using?

MacOS Big Sur 11.4

### How are you deploying Directus?

local

**Comment by Nitwel** [comment]
This seems to be a bug in Firefox as Chrome validates the input properly.
Caused by passing a number into the value prop of the input instead of a string.
