### ISSUE TITLE
Window get scroll to top when click to field edit button

### ISSUE THREAD

**Issue by d1rOn** [directus/directus#7709]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Window get scroll to top when click to field edit button on collection edit page.

### To Reproduce

1. Create any collection with at least one field.
2. Scroll down the page a little.
3. Click the edit field button.
4. Window will be scrolled to top.

### What version of Directus are you using?

rc91

### What version of Node.js are you using?

14.17.2

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

Debian 10

### How are you deploying Directus?

locally

**Comment by Nitwel** [comment]
We kept it this way as the drawer that opens when you click on a field is techniclally a new page and tracking the scroll bar position over different pages causes a lot of trouble elsewhere. 
But thanks for taking your time creating an issue about this. 😄

**Comment by rijkvanzanten** [comment]
We track a feature request to handle the scroll position more gracefully on the data model detail here: https://github.com/directus/directus/discussions/6152

**Comment by benhaynes** [comment]
I didn't realize even the drawer would reset scroll position... that will be very messy when we add an option to open Layout items in a drawer (if the listing scroll resets). #6152 will be crucial when we make that change. 🤔
