### ISSUE TITLE
Cannot apply filter on /collections API endpoint

### ISSUE THREAD

**Issue by bahamut657** [directus/directus#7732]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

`
http://<DIRECTUS_HOST>/collections?filter[collection][_eq]=TESTNAME
`
It seems to return all collections, whatever filter or deep I try to apply. 

Is it possible to filter collections results?
How to filter only non-system collections?

Regards
Directus is amazing, thanks for your work

### To Reproduce

http://<DIRECTUS_HOST>/collections?filter[collection][_eq]=TESTNAME

All collections are returned

### What version of Directus are you using?

v9.0.0-rc.88

### What version of Node.js are you using?

12

### What database are you using?

MariaDB

### What browser are you using?

Chromium

### What operating system are you using?

macOS, Linux

### How are you deploying Directus?

Docker on local server

**Comment by rijkvanzanten** [comment]
Heya! This is correct. Some of the system endpoints don't currently support the query parameters. See https://docs.directus.io/reference/api/system/collections/#list-collections for example.

We're aiming to add support for query params in these endpoints as well at a later date. 

(Those particular endpoints (collections/fields/relations) don't return data from a database table, so we can't rely on the same SQL based querying capabilities as we can in the "normal" endpoints)
