### ISSUE TITLE
Image not displayed on the WYSIWYG editor when added using the toolbar button

### ISSUE THREAD

**Issue by gurumark** [directus/directus#7751]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I am using the docker edition of Directus. When I insert an image using the WYSIWYG editor by pressing the Add/Edit Image button on its toolbar, the image was not displayed in the editor.

https://vimeo.com/595914363/2c0fb18523

The video above does not show the image upload part but the popup does show on the off-canvas sidebar.

### To Reproduce

1- insert an image using the WYSIWYG editor by pressing the Add/Edit Image button on its toolbar
2-  the image is not displayed in the editor.

### What version of Directus are you using?

v9.0.0-rc.91

### What version of Node.js are you using?

v16.7.0

### What database are you using?

Mariadb 10.5.10

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
Hi there!

It seems like this was already resolved by #7583 which will be released in 92 🙂
