### ISSUE TITLE
Documentation links with hashtag resolve incorrectly

### ISSUE THREAD

**Issue by w0kyj** [directus/directus#7753]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

The links in the documentation that contain a "/#" get these values removed when launching the link.

e.g.
From page: http://localhost:8055/admin/docs/reference/api/authentication
Click "configure permissions for the public role" --> http://localhost:8055/concepts/roles/#public-role
Resolves to:  http://localhost:8055/admin/docs/concepts/rolespublic-role

Perhaps vue is seeing the "/#" as a value to remove?

### To Reproduce

1. Install Directus
2. Open App (public)
3. Navigate to Documentation --> API Reference --> Authentication
4. Click "configure permissions for the public role"

### What version of Directus are you using?

v9.0.0-rc.91

### What version of Node.js are you using?

v16.7.0

### What database are you using?

psql (PostgreSQL) 13.3

### What browser are you using?

Chrome

### What operating system are you using?

Manjora

### How are you deploying Directus?

Running locally

**Comment by rijkvanzanten** [comment]
I was right!
