### ISSUE TITLE
directus_users filter overriding

### ISSUE THREAD

**Issue by Fabio-Git-Hub** [directus/directus#7802]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Deep filtering for user status and user role returns all items with an active user while ignoring the users role

### To Reproduce

Collection 'works':
Field user_created is a many to one relation on collection directus_users (id)

Fetching the request _.../items/works?filter[user_created][role]=..._ returns correct data.
Fetching the request _.../items/works?filter[user_created][role]=...&filter[user_created][status]=active_ returns entries with active users but multiple different user roles.

### What version of Directus are you using?

9.0.0-rc.91

### What version of Node.js are you using?

/

### What database are you using?

/

### What browser are you using?

/

### What operating system are you using?

/

### How are you deploying Directus?

/

**Comment by joselcvarela** [comment]
Hey @Fabio-Git-Hub 
I have tried it locally and couldn't find any issues.

Is it possible to share a dump of your database or simple reproducible use case?

**Comment by rijkvanzanten** [comment]
Also please fill out the issue template. There's no way for us to accurately reproduce issues without that information being present.
