### ISSUE TITLE
sdk auth.login can't change mode to json

### ISSUE THREAD

**Issue by Pu5her** [directus/directus#7810]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

directus.auth.login() options.mode='json' doesn't work

### To Reproduce

call 
`return directus.auth.login(
      {
        email: email,
        password: password,
      },
      {
        mode: "json",
        refresh: {
          auto: true,
        },
      }
    );`

and you get no refresh_token in localstorage

i think it's because need to remove 'this' from 139 line of https://github.com/directus/directus/blob/main/packages/sdk/src/base/auth.ts

### What version of Directus are you using?

v9.0.0-rc.92

### What version of Node.js are you using?

v14.17.6

### What database are you using?

mariaDB

### What browser are you using?

chrome

### What operating system are you using?

linux

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
We're tracking this in https://github.com/directus/directus/issues/7112 🙂 Love to hear your thoughts around other improvements in the auth usage in the SDK as well 👍🏻
