### ISSUE TITLE
Users roles

### ISSUE THREAD

**Issue by WellingGuzman** [directus/directus#789]
I want to open this issue, as I reminder that we need to implement user roles instead of using groups as a role.

Right now, every user part of the group_id = 1, would be admin, we shouldn't depend on this to determine if the user is admin or no.

**Comment by benhaynes** [comment]
@WellingGuzman – how would this work? Would we add an "admin" boolean field to directus_groups? That seems like it might be best.

**Comment by WellingGuzman** [comment]
I was thinking of adding a new field on `directus_groups`, but I've been thinking a lot about how permissions/groups going to be handle, and I was thinking whether or not call a group to be "admin" or not, rather than this group has permission to this or it doesn't.

But again we need a "superadmin" which won't be group_id = 1 and we can take this from the group name which should be unique now, and it's the user `belongsTo('Administrator')`, it's an admin (superadmin).

What do you think? right now for permissions-related and All about one field with a json/array.

**Comment by benhaynes** [comment]
We can avoid using "admin" if we want, but still need to break apart the admin abilities into permissions:

Admin special abilities:
* Can add/edit/delete any user
* Access to settings (including adjusting permissions)
* Maybe some other things?

*All of this could be handled by our existing permissions:*
* add/big-edit/big-delete on directus_users
* add/big-edit/big-delete on directus_settings, directus_permissions, etc

So maybe we just determine it based on that? But what happens if a group only has partial permissions for settings? Would they not see the settings "gear" icon?

What is "super-admin" for? What can they do beyond the above? Do you think permissions in JSON is better than the fields I mentioned in my last email?

For directus_privileges (group access for each table):
table_name – Same
group_id – Same
status_id – Same
read_field_blacklist – Same
write_field_blacklist – Same
listed – [0,1] Reverses from unlisted, controls nav and table listing (no need for another navlisting field)
view – [0, 1, 2] Separate fields, 0=none, 1=view, 2=big-view
add – [0, 1] Separate fields, 0=none, 1=add
edit – [0, 1, 2] Separate fields, 0=none, 1=edit, 2=big-edit
delete – [0, 1, 2] Separate fields, 0=none, 1=delete, 2=big-delete
alter – [0, 1] Separate fields, 0=none, 1=alter

**Comment by WellingGuzman** [comment]
By admin I meant what you just said:

An user with abilities to:
add/edit/delete any user
Access settings (including adjusting permissions, **also create tables and fields**)

> All of this could be handled by our existing permissions:
>
> add/big-edit/big-delete on directus_users
> add/big-edit/big-delete on directus_settings, directus_permissions, etc

So here what if an user has `listed=0`, so this way the `Users` nav wont show up, same with settings and activity?

> But what happens if a group only has partial permissions for settings? Would they not see the settings "gear" icon?

as long as it has permission to `view => directus_ui`  the gear icon (next to the field right?) should be there, what can't be done (inside the settings of a field) is what it doesn't have permission to, (which boil down to add and edit, which)

> What is "super-admin" for? What can they do beyond the above?

By "super-admin" I was thinking about a group which do the same as admin, but a Group with permission to delete user, can't delete "super-admin" group, I don't know if this is going to far, but just was a thinking.

> Do you think permissions in JSON is better than the fields I mentioned in my last email?

I mean, I like the idea of having a field for each, so we get close to 1=1 with tables, so we can see _`directus_privileges`_ table and know it has `view, add, edit` fields and it could be easy to update the permission via Directus.

I just find that in term of updating/extending to more permissions, etc. this would be easier with json, but would be hard to edit this value directly via edit table without the implementation of [JSON editor UI](https://github.com/RNGR/Directus/issues/514) but again, we are going to mange this via Settings > Permissions.

I was thinking something like this.

```
{
    "group_id": 1,
    "table_name" : "directus_users",
    "status_id": 1,
    "read_field_blacklist": "",
    "write_field_blacklist": "",
    "permissions" : {
        "listed" : 1,
        "view" : 1,
        "add"   : 1,
        "edit" : 1,
        "delete": 1,
        "alter": 1,
    }
}

// 0=deny, 1=allow, 2=big-allow, 3=hard-allow, 4=big-hard-allow
```

so let's say we want to implement (very risky) but _just as an example_, `drop` permission, which let user to drop tables, we don't need to add a new table for it, neither create a new migration which alter the table group, we just need to add a default value to drop=false and we are good to go.

@benhaynes what do you think?

**Comment by benhaynes** [comment]
Hey @WellingGuzman – this is great. My thoughts:

It seems that our existing permissions can handle almost all of this (hiding system nav items, etc) – which is great! 

For the settings gear, I think we show the settings they have appropriate access for:

* Global Settings => directus_settings
* Media => directus_settings
* Tables & Inputs => directus_ui, directus_tables, directus_columns
* Permissions => directus_users, directus_groups, directus_privileges

As for Super-Admin, I like your thinking – but it might be overkill. Let's keep it simple for now so it's all based on these normal permissions.

I also see what you're saying with JSON versus fields for permissions – but I think fields will be a little clearer from a database perspective (especially if devs choose to edit directly in the DB). JSON syntax is too easy to mess up when editing by hand, and it's harder to write to individually. I don't think we'll be adding new permissions any time soon. We could also add in the "drop" field now but leave it unused – so it's in the schema... but that might be messy. It's easy to add a field later.

**Comment by WellingGuzman** [comment]
@benhaynes I'm sorry If I wasn't clear, but I wasn't talking about implementing a new user roles system, just not depending on `group_id` to know if the user is admin or not.

You are right, about the superadmin is a overkill.

but I think we can close this, as we are not going to keep it simple by now. And we can re-peon it later.

What do you think?

**Comment by benhaynes** [comment]
Ahh, I get it. So would we add an "Admin" field boolean to the directus_groups table? Or were you thinking that we would base it on the existing directus table privileges?

**Comment by benhaynes** [comment]
Thoughts? @WellingGuzman

**Comment by WellingGuzman** [comment]
@benhaynes so I think we agreed on add `show_settings` + `allow_alter` as combination of a "Admin", right?

**Comment by benhaynes** [comment]
Yes, but maybe it's "is_admin" instead of "show_settings" so it's clearer what that entails.

**Comment by WellingGuzman** [comment]
Agreed! :+1:

**Comment by benhaynes** [comment]
We've adjusted our approach to this problem – now we're using "allow_" prefixed permissions.
