### ISSUE TITLE
Issues/Updates for Map Interface

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#7895]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

![Screen Shot 2021-09-07 at 2 12 56 PM](https://user-images.githubusercontent.com/522079/132391599-2128fa09-65f3-49e5-a4e1-eddfdad482b4.png)

The following is what I've noticed on the "point" version of the map.

* My map is _very_ pixelated (see above) on a normal resolution monitor, I can only imagine how bad this looks on 4k
* I don't understand what the "OpenStreetMaps" dropdown in the bottom-left is for. I assume for toggling the map tiles? If so, this should be an interface option, not a UI option.
* All buttons need tooltips explaining what they are
* The compass (3rd button down) doesn't do anything for me (desktop). If this is for Resetting North, I'd say we should _always_ lock north and remove this button
* The marker itself is pixelated, ca we get this crisper/antialiased?
* Let's adjust the marker to be the primary color, and look into a more subtle/realistic drop shadow
* The marker add/select/delete workflow is a bit confusing. I would recommend the following:
    * Remove the "Delete Marker" button. The user can use the field's "Clear Value" option. Also, it'd be ideal if deleting was possible through the Delete keyboard key (if the marker is selected).
    * Let's also remove the "Add Marker" button. We should simply add an initial marker on a single click.
    * Is it possible to give the marker a hover style?
    * Is it possible to slightly animate the selected marker so it's clear it's selected?
* It is not clear that you need to click a marker before you can drag it to a new location. Is there a reason we don't simply allow it to be dragged? If not, can we add a tooltip on the marker that says "Click to Select"?
* Do we have _any_ control over the free map tile styling?

### To Reproduce

Create a Geometry/Map field.

### What version of Directus are you using?

RC-92

### What version of Node.js are you using?

16.6.1

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

**Comment by benhaynes** [comment]
Just a few updates now that I've spoken with Rijk and understand the "free base map" stuff.

* Let's figure out what free (no API key) license we can use to get not so blurry/pixelated base map tiles (if we can't find anything better, we might need to disable our Map support until they enter a key).
* I now see how to adjust rotation and pitch (right-click + drag)... but I'd rather disable these and remove the compass button
* Can we add a right-click context menu to the Maps? This might be good for hiding secondary buttons/features
    * Add Item Here
    * Fit Items in View
    * Reset Rotation/Pitch (only needed if we can't disable that feature altogether)
    * Change Map Tiles (if more than one available)
* For the Layout, can we only show the "X" button once you have some points selected?
* The "Locate Me" button takes a while to _do anything_. Can we swap this with a spinner while it's processing?
* I think the "Center Data" button (square brackets) could move to the right-click menu. It's also a bit finicky and doesn't work if you scroll away from data but don't hit "Search this area"
* On the Interface, let's remove the "Choose Tile Set" dropdown from the bottom-left. I'm getting a conflicting "MapLibre" watermark above it... and we can move this to the Right-Click anyway.
* On the interface, let's add a hover to the marker that says: "Click to edit location" / "Click to set location"
* For the Layout, the tooltip needs styling/dropshadow for contrast
* For the Layout, we need a way to configure the data shown in the tooltip... right now it's just the ID
* We need to adjust the color/styling of the Cluster circles (primary bg and white fg)

**Comment by benhaynes** [comment]
Keeping this separate, but we need to add an optional component for creating an inset shadow for Layouts. As of now, the Layout gray can be the exact same as the sidebar grays... leading to a muddled design. These shadows should support each side individually, so we can programmatically add it only to the sides that are needed.

**Comment by benhaynes** [comment]
Hey @Oreilles — this is looking so much better already!! This is officially my new favorite Layout! Thank you for all the hard work here. I've added a few more points below, which we can discuss on Monday:

* The Interface marker seems jagged/pixelated (see below). Anything we can do about that? If not, let's use the same circles on the Layout... those are clean!
* Let's also make the default maker green (our primary color)
    * Bonus points if we can actually tie this to the dynamic color variables!
* For the selected marker, how much control do we have? Can I design two marker states in vector with size/color/shadows?
    * Let's at least try using yellow instead of orange (hopefully enough contrast)
* Let's remove that hideous little baby shadow under the nonselected marker (or I can create a PNG that makes it subtle sexy)
* Can we add more shadow to the Layout marker tooltip (see below)? Also, there seems to be a lot of vertical padding here, let's minimize that, if possible.
* `Geometry format` & `Geometry type` & `Default view`  have incorrect casing (eg: "Format" should be capitalized)
* Can we hide these if they are disabled or aren't relevant/used?
    * Geometry format & Geometry type
* We need to add shadows to the sidebars... but this is something @rijkvanzanten will handle
* Can we add tooltips explaining the left buttons? Some aren't immediately clear. 
* I think I asked before, but is it possible to hide the "X" deselect button when nothing is selected?
* Can we make the search bar background white? Or ideally `background-page` color?
* When "always filter data to view bounds" is on, let's NOT have a popup jump in as soon as there's no data.
* Rename: `always filter data to view bounds` to `Auto-Filter within View` **(on by default)**
* Rename: `Activate clustering` to `Cluster Nearby Data` **(on by default)**
* When you use the geo-lookup search, it takes you there... but it's very difficult to know exactly where the middle (eg: address) is. Do we have any options to solve this? Some crosshairs, or (for the Interface) after searching, a popup option asking if you want to drop a pin on that location?

![Screen Shot 2021-10-15 at 6 22 45 PM](https://user-images.githubusercontent.com/522079/137560269-c52c1fa2-2784-4b9f-a88b-e125314c2cee.png)

![Screen Shot 2021-10-15 at 6 35 03 PM](https://user-images.githubusercontent.com/522079/137561395-bfd85353-5c60-4ac2-88f0-0298658a8fa5.png)


-----

>On the interface, let's add a hover to the marker that says: "Click to edit location" / "Click to set location"
>>Wouldn't it be a bit excessive to show a popup message every time an item is hovered ?

I meant a tooltip. 😉 

>For the Layout, we need a way to configure the data shown in the tooltip... right now it's just the ID
>>The template shown on the tooltip is the one used in the collection's own display template. Should we add another option to overwrite it?

Yeah, because if an Admin doesn't set this up there's no way for a user to change it.


> We need to adjust the color/styling of the Cluster circles (primary bg and white fg)
>>There currently are different colors for different cluster size. We could make them configurable - Actually, the whole style is customizable (item color, shape etc) according to the mapbox style specification. This used to be a layout option, but it has been removed since. Maybe we could add it back as global option (like the basemap settings) ?

Perfect! No need to make it configurable, let's just set it to the circles (as they are now), but with our colors:
1. Red (most)
2. Orange (we can remove this one if we only need 3)
3. Yellow
4. Green (fewest)

(Not sure how many we need, but I'm thinking this will make a "heat-map" style)

**Comment by rijkvanzanten** [comment]
> Trying to see if we can use the Display Template for these (the status field should show a green circle, not "published"). I know we might not be able to inject reactive components here, but perhaps there's something we can do to push the HTML in? (CC @rijkvanzanten)

The only thing I could think of might be to try to use a portal target within that popover, and have Vue render into that popover dynamically through the use of teleports. That's very hacky though, and i'm not sure if Vue will treat dynamically portals like that properly

**Comment by rijkvanzanten** [comment]
We don't currently have a GUI way to override the color palette (like --green etc), so that shouldn't be an issue. I'm only mentioning it because the flavor of green you're using right now is the current --green. If and when we tweak what --green is, the colors used in the map stuff will no longer fit in the design system. In order to prevent that, we should have them use --green etc

**Comment by rijkvanzanten** [comment]
> Since there are only two color used (orange and green), I don't think it's worth the hassle of creating a function to get the whole document computed style, get the css variable we need, then generating the style on the fly each time a map is rendered

I disagree. It's not just about the maintenance of it. I did say that we don't expose the colors as a config in the GUI, but we do support updating the color palette through the CSS vars. Things like the wysiwyg internal styles do the same trick. Consistency is key here. As for it looking ugly on a map, that's why the dot has a white border. It separates the marker color from the background color, meaning there will always be enough contrast 👍🏻 

>  just so we don't have to update 4 LOC when we update "--green"

This won't happen. People don't know that we're relying on vars in some places, and hardcoded variables elsewhere.

> so we don't have to update 4 LOC when we update "--green" (if ever, at what frequency ? )

Funnily enough, the --orange color was updated 3 times in the last 30 days.

**Comment by Oreilles** [comment]
> It separates the marker color from the background color, meaning there will always be enough contrast

For the point, sure, but for points and polygons it's a different story (those would look atrocious with an additional white border)

<img width="433" alt="Capture d’écran 2021-10-20 à 14 07 57" src="https://user-images.githubusercontent.com/33065839/138352181-e890170c-c357-47aa-af54-2fe31248546a.png">

I believe that having a pretty and readable style is more important than having it be 100% consistant with the app colors. ( The basemap themselves don't match it either anyway )

> Funnily enough, the --orange color was updated 3 times in the last 30 days.

Lol, ok I wasn't expecting this

**Comment by rijkvanzanten** [comment]
We're not doing brand / primary colors regardless in here. The question is whether or not we should use the variable for the color palette (so f.e. --green)

**Comment by benhaynes** [comment]
OK, here is a final list based on what I'm seeing on latest `main`:

## Global

* We need tooltips on these buttons:
![Screen Shot 2021-10-31 at 12 29 26 PM](https://user-images.githubusercontent.com/522079/139593241-ef7e6ce3-7eaa-4201-9c9d-fe4208f2a5c0.png)

* Can we change this placeholder to "Find Location..."?
![Screen Shot 2021-10-31 at 12 32 51 PM](https://user-images.githubusercontent.com/522079/139593359-f8345694-3ee1-4f8d-b183-fbc9e7fc930c.png)

* If you hover on the RIGHT side of the search button, it quickly toggles open/closed crazily. Some event issue with hit area.
![Screen Shot 2021-10-31 at 1 25 30 PM](https://user-images.githubusercontent.com/522079/139594989-36f9e2cd-58d6-4af8-8920-efbc5f3bb333.png)


## Layout

* Marker hovers need to be centered and offset above the marker by a bit, not like this:
![Screen Shot 2021-10-31 at 12 21 49 PM](https://user-images.githubusercontent.com/522079/139593107-e206ac57-1a34-425c-b1b0-54d9e622e4c5.png)

* Let's remove this, there's no reason to have this pop up just because no items are in the viewport:
![Screen Shot 2021-10-31 at 12 24 14 PM](https://user-images.githubusercontent.com/522079/139593134-f275452b-0f6e-42d6-b938-c0d189c7ad57.png)

* Let's remove the "Auto-filter within view and just **always* have it on.
![Screen Shot 2021-10-31 at 12 35 27 PM](https://user-images.githubusercontent.com/522079/139593461-f88e0fbf-844e-4cec-b138-9eac9675e5c2.png)

* Let's just NOT have this "X" button — users can always just click somewhere to deselect. Also, the "x" kinda feels like delete.
![Screen Shot 2021-10-31 at 12 35 10 PM](https://user-images.githubusercontent.com/522079/139594686-d1cfcefa-b0dd-4399-8b9f-b7b9d947ac5d.png)

* Let's rename this to `Field` or `Geospatial Field`... "Geometry" is too ambiguous.
![Screen Shot 2021-10-31 at 1 13 48 PM](https://user-images.githubusercontent.com/522079/139594838-3cbcca10-2420-4bda-80ce-281e79ef137c.png)

* Can we add a shadow to the left/right/top of the map? Eventually we'll add a global prop for any Layout to set this, but for now it would help avoid this unclear boundary:
![Screen Shot 2021-10-31 at 1 24 21 PM](https://user-images.githubusercontent.com/522079/139594950-c0c5d7cc-fae0-4509-a4d7-a51f64c5491b.png)

* Can we set a placeholder here saying: `Using Collection Default...`?
![Screen Shot 2021-10-31 at 1 27 21 PM](https://user-images.githubusercontent.com/522079/139595030-441605cc-d0f1-4359-89bf-5fbca667c45c.png)

* When going to the Layout (eg: returning from an Item Detail)... it does not remember where I was, and puts me in the Bermuda Triangle... literally. Can we save the map coordinates from when you were last on the Layout (eg: in local storage)? 
![Screen Shot 2021-10-31 at 1 29 32 PM](https://user-images.githubusercontent.com/522079/139595068-2aeedb36-c84e-4b43-abf2-6000dc6add81.png)



## Interface

* Can we hide the "delete" button until the marker is selected? Or it can delete everything in the interface... either way.
![Screen Shot 2021-10-31 at 12 33 24 PM](https://user-images.githubusercontent.com/522079/139593382-3211975e-56bf-47a2-ad6a-c0c958c1914a.png)

**Comment by Oreilles** [comment]
> Can we change this placeholder to "Find Location..."?

* [x] Done

> If you hover on the RIGHT side of the search button, it quickly toggles open/closed crazily. Some event issue with hit area.

* [x] Done

> Marker hovers need to be centered and offset above the marker by a bit, not like this

* [x] Done

> Let's remove this, there's no reason to have this pop up just because no items are in the viewport:

* [x] Done

> Let's remove the "Auto-filter within view and just *always have it on

* [x] Done

> Let's just NOT have this "X" button — users can always just click somewhere to deselect. Also, the "x" kinda feels like delete.

* [x] Done

> Let's rename this to Field or Geospatial Field... "Geometry" is too ambiguous

* [x] Done

> Can we set a placeholder here saying: Using Collection Default...?

* [x] Done

> Can we hide the "delete" button until the marker is selected? 

* [x] Done


> When going to the Layout (eg: returning from an Item Detail)... it does not remember where I was, and puts me in the Bermuda Triangle... literally

Well that's funny.. But unexpected. The last location is actually saved after each move in the current preset. When going back to the layout, the previous location is used to set the new one. I just verified that it works as expected.. Can you provide more info on this ?

> Can we add a shadow to the left/right/top of the map? Eventually we'll add a global prop for any Layout to set this, but for now it would help avoid this unclear boundary:

 Not possible to do from within the layout, the shadows must be added to the higher elements (navigation, sidebar, header-bar). We'll need to define a prop for this and make it available to those elements.

> We need tooltips on these buttons

This would require quite a rework on how they are currently created, I'll be working on it.

**Comment by benhaynes** [comment]
The Map Layout and Map Interface are both looking _tight_ now... thank you so much, @Oreilles!! ❤️
