### ISSUE TITLE
Hooks: Payload in from files.upload hook cannot be modified

### ISSUE THREAD

**Issue by pgegenfurtner** [directus/directus#7914]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I created a new field in directus_files and want to add a custom value derived from the uploader (see hook function below). 

But when using the files.upload event, the custom value does not get written to the file in the database.

Doing the same with the items.create.before event (other tables, not files) it works as wanted.

### To Reproduce

1. Add a new column to da directus_files data model: customer, textfield
2. Add the following (example) hook file

```
module.exports = function registerHook({ services, exceptions }) {
    const { InvalidPayloadException, ServiceUnavailableException,  } = exceptions;
    const { ItemsService } = services;

    return {
        'files.upload': async function (ctx) {
            const { payload, accountability, schema } = ctx;

            const userService = new ItemsService('directus_users', { accountability, schema });
            // Role can only see itself
            const user = await userService.readOne(accountability.user, { fields: ['email'] });

            payload.customer = user.email;

            return payload;
        },
    };
};
```

### What version of Directus are you using?

v9.0.0-rc.92

### What version of Node.js are you using?

16.8.0

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Official Docker Image

**Comment by rijkvanzanten** [comment]
This is correct. The upload hook fires as an async action, and doesn't wait for the result (it's an action, not a filter). There is no files.upload.before at this time 👍🏻
