### ISSUE TITLE
Field conditions not applied in system settings form

### ISSUE THREAD

**Issue by Oreilles** [directus/directus#7919]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Condition for fields set in the application settings yaml definition are not taken into account.

### To Reproduce

Add a condition to a system settings, go to the app system settings and check the condition rule.
See https://github.com/directus/directus/pull/7918

https://github.com/directus/directus/blob/a28c374a0b6c66aec24f4747068b3ec88cb99e6c/api/src/database/system-data/fields/settings.yaml#L321-L334

### What version of Directus are you using?

v9.0.0-rc.92

### What version of Node.js are you using?

16.8.0

### What database are you using?

SQLite

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

local

**Comment by rijkvanzanten** [comment]
@Oreilles Spotted the issue. Conditions is an array of conditions, not a single object. Try making it 

```yaml
     conditions: 
       - name: typeNeqRaster 
         rule: 
           type: 
             _neq: 'raster' 
         hidden: true 
```
