### ISSUE TITLE
Drawer headers should honor collection icon/color

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#7924]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

![Screen Shot 2021-09-08 at 12 17 38 PM](https://user-images.githubusercontent.com/522079/132546830-46459180-6876-43e8-80a2-365df519290a.png)

In the screenshot above, we can see the generic "box" icon in black/foreground. However, this "Careers" is configured with an icon and color... which is not being shown here. We should respect and show the correct icon/color in all collection drawers.

### To Reproduce

Click on a M2O/O2M interface to open its selection drawer... look at the header.

### What version of Directus are you using?

RC-92

### What version of Node.js are you using?

INTERNAL

### What database are you using?

INTERNAL

### What browser are you using?

Chrome

### What operating system are you using?

INTERNAL

### How are you deploying Directus?

INTERNAL

**Comment by rijkvanzanten** [comment]
Is the collection color currently used in that header icon?

**Comment by benhaynes** [comment]
Yeah, the Collection Detail page...

![Screen Shot 2021-09-08 at 12 33 39 PM](https://user-images.githubusercontent.com/522079/132549092-b8cf6853-177f-4964-aeab-ac7300d8152e.png)

**Comment by benhaynes** [comment]
In addition to Collection draw headers, we should customize a few of the one-offs. For instance, the Item Revisions drawer icon should be set to `change_history`.
