### ISSUE TITLE
Getting duplicate "create" revisions

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#7927]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I'm getting duplicate "Creation" events under revisions.

![Screen Shot 2021-09-08 at 12 56 34 PM](https://user-images.githubusercontent.com/522079/132552367-500559c0-6340-4eb8-9360-99810ae464d0.png)

### To Reproduce

1. Create an item
2. Look at revisions

### What version of Directus are you using?

RC-92

### What version of Node.js are you using?

INTERNAL

### What database are you using?

INTERNAL

### What browser are you using?

Chrome

### What operating system are you using?

INTERNAL

### How are you deploying Directus?

INTERNAL

**Comment by benhaynes** [comment]
The issue is here:

https://github.com/directus/directus/blob/main/app/src/views/private/components/revisions-drawer-detail/revisions-drawer-detail.vue#L22-L24

We're tracking the `create` revision separately so we know if an item was created "outside of Directus"... but it's not working as expected.

We're fetching a `response` and a `createdResponse` (seems way too heavy for getting this simple info), and we _could_ fix this by adding a `_neq` filter to the `response` query. However, I won't do that, because it seems like there's some room for improving how this operates. Perhaps we can get @rijkvanzanten to give it a glance. 🙂

**Comment by rijkvanzanten** [comment]
> We're fetching a response and a createdResponse (seems way too heavy for getting this simple info)

We fetch the last 100 revisions, and then the first in order to show the "created" message. If we wouldn't do it in 2 separate queries, there's no way to know what the first item was if you have 100+ revisions 👍🏻

**Comment by Nitwel** [comment]
This should be fixed by #6303 as the PR introduces pagination to revisions.
