### ISSUE TITLE
Activity Listing Selection

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#7935]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Items on the activity page can not be selected, but they have checkboxes... that don't do anything. We should see if it makes sense to allow selecting items (eg: admins removing legacy activity), or if we should remove the checkboxes.

Let's discuss! 

### To Reproduce

Go to the activity page, click on an item checkbox

### What version of Directus are you using?

RC-92

### What version of Node.js are you using?

Node: 16.6.1

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

DO

**Comment by rijkvanzanten** [comment]
This also ties into https://github.com/directus/directus/issues/7818. Layouts should support the difference between "No Select", "Select One", "Select Multiple"

**Comment by joselcvarela** [comment]
@rijkvanzanten can I proceed with that approach?

**Comment by rijkvanzanten** [comment]
@joselcvarela Totally!
