### ISSUE TITLE
Option on fields should collapse if another one is selected

### ISSUE THREAD

**Issue by LevinGermann** [directus/directus#7936]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I know this is a very minor and visual only issue which can probably even be ignored, but I decided to report it anyway.

While being in a collection, the 3 dots on the right open a menu (edit, half width etc...).
If another one is selected, I expect the already selected one to collapse and not stay open; instead it opens another popup behind the already existing one.

<img width="324" alt="image" src="https://user-images.githubusercontent.com/9347206/132586794-160e226b-7e30-408d-a4b5-2626a7374afa.png">

### To Reproduce

1. Create multiple fields in a collection
2. Select the menu on one, then select the menu on another one

### What version of Directus are you using?

9.0.0-rc.92

### What version of Node.js are you using?

v16.7.0

### What database are you using?

PostgreSQL 13.2

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
> I know this is a very minor and visual only issue which can probably even be ignored, but I decided to report it anyway.

It's small tweaks like this that greatly improve the overall (feeling of) stability, so thank you for reporting it anyway 😄
