### ISSUE TITLE
Boolean interface "Enabled" not being translated 

### ISSUE THREAD

**Issue by jrvidotti** [directus/directus#7937]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

![image](https://user-images.githubusercontent.com/5623041/132588013-7879dc1b-5816-478d-a9f8-c6346699b152.png)

I am using pt-BR and checked if translations are there.
```
enabled: Habilitado
```

### To Reproduce

1. Change language to pt-BR.
2. Add a boolean field
3. Check if text in boolean field is "Enabled" or "Habilitado"

### What version of Directus are you using?

v9.0.0-rc.92

### What version of Node.js are you using?

v16.8.0

### What database are you using?

Postgres 13.2

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu WSL2

### How are you deploying Directus?

local

**Comment by rijkvanzanten** [comment]
> Check if text in boolean field is "Enabled" or "Habilitado"

This text is actually configurable in the interface options, and not something that's auto-translated in the app. The ability to add custom translations for interface-option values is tracked here: https://github.com/directus/directus/discussions/3075
