### ISSUE TITLE
Presentation Button Link keeps old values

### ISSUE THREAD

**Issue by nathanhere** [directus/directus#7942]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

The Presentation button link seems to keep old url values, even when deleted and replaced. This behavior didn't seem to be present in prior versions. In prior versions, new collection items were created with correctly updated presentation button links, however, I noticed in RC 92 version that all subsequent items that were created contain the old url value.

### To Reproduce

1. Create presentation button link, fill out url field, save.
2. Create a new item in the corresponding collection.
3. Delete presentation button link from the collection data model.
4. Create a new presentation button link with a different url value.
5. Create a new item in the corresponding collection.
6. Click or hover over the button and observe that it still holds the old value.

### What version of Directus are you using?

RC92

### What version of Node.js are you using?

14.17.4

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

Docker Compose

**Comment by rijkvanzanten** [comment]
When you say

> Create a new presentation button link with a different url value.

Did you use the same field name for the presentation button? 🤔  Wondering where this overlap is coming from

**Comment by nathanhere** [comment]
My apologies. After more digging, I've found that the issue is that I thought a collection item's field that used a default value (which I used as a templating variable in the button link) would update if the default field value was changed in the data model.
