### ISSUE TITLE
Azure AD SSO doesn't work when deploying Directus to AWS Farget with more than 1 instance

### ISSUE THREAD

**Issue by younky-yang** [directus/directus#7943]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Packaged Directus and deployed it to AWS Fargate with Azure AD SSO enabled, If I just enable one instance on fargate, everything works as expected, but if I enabled more than 1 instance on Fargate, I keep getting the error: Grant: Missing provider or session configuration. 

Also with the same container image that I deployed on AWS, I have no issue to run it on local, with just one instance. 

### To Reproduce

Configuring Directus to enable Azure AD SSO login and deploy it to AWS fargate with more than 1 instances. 

### What version of Directus are you using?

9.0.0rc92

### What version of Node.js are you using?

16.8.0

### What database are you using?

Postgres 11

### What browser are you using?

Edge, Chrome, Firefox

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker and deployed on AWS Fargate

**Comment by aidenfoxx** [comment]
Are you using in-memory sessions? If so you'll need to enable to redis, memcached or database to enable persistent sessions across multiple fargate instances.

https://docs.directus.io/reference/environment-variables/#sessions

**Comment by younky-yang** [comment]
> Are you using the default in-memory sessions? If so you'll need to change your config to use redis, memcached or database sessions to allow persistent storage across multiple fargate instances.
> 
> https://docs.directus.io/reference/environment-variables/#sessions

thanks, I updated to database and now seemed works fine.
