### ISSUE TITLE
`fields.*.before` etc. should run before `ALTER TABLE` statements

### ISSUE THREAD

**Issue by nickluger** [directus/directus#7946]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When adding a `before`-hook to `fields`, and changing something, the `ALTER TABLE` DDL-statements are executed before the hook is run. This might be the same for `collections` etc., did not test that yet.

### To Reproduce

1. Create a table + field. 
2. Add a `fields.*.before`-hook and restart the server.
3. Make a change to the field, e.g. give it a default value or just create a new field.
4. See `ALTER TABLE` being executed before the hook is run. You can also check this by making another DB user owner of the table, which will result in `error alter table "MyTable" add column "foo" varchar(255) null - must be owner of table MyTable`, and the hook will never run.

### What version of Directus are you using?

9.0.0-rc.92

### What version of Node.js are you using?

v14.17.5

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
You're right. The FieldService doesn't explicitly emit the create/update events itself, but relies on the ItemsService to do it by default. The meta row is saved _after_ the schema is modified here:

https://github.com/directus/directus/blob/0575cb48364e15030a8137034317234952b62411/api/src/services/fields.ts#L294-L298

**Comment by nickluger** [comment]
Okay, I see. We're not relying on it currently, and as nobody else mentioned it, it might be low prio. Just wanted to mention it😄.

**Comment by rijkvanzanten** [comment]
Much appreciated 🙂
