### ISSUE TITLE
Switching collection from "Single Object" to normal breaks the collection display

### ISSUE THREAD

**Issue by infomiho** [directus/directus#7990]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Switching a collection from single object to normal collection breaks the API.

### To Reproduce

1. Create a new collection
2. Set "Use as a single object" to true
3. Add some data
4. Change the "Use as single object" to false

Here is a video with repro as well https://youtu.be/1LTC2vPtrdw

### What version of Directus are you using?

9.0.0-rc.92

### What version of Node.js are you using?

v12.20.2

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying Directus?

Kubernetes

**Comment by infomiho** [comment]
Just to add to discussion, it might as well be related to scaling the deployment to two instaces. 

I'm not sure why the inconsistency happens when using two separate instances connecting to the same DB. I'll investiage and post more details soon.

**Comment by rijkvanzanten** [comment]
@infomiho Are you using a shared provider for the cache? Like redis or memcached

**Comment by infomiho** [comment]
@rijkvanzanten Hey I've tried the same steps locally with running Docker and the same thing happens. Although I found this error in the logs
```
directus  | 20:12:25 ⚠️  An error was thrown while executing hook "items.read"
directus  | 20:12:25 ⚠️  Cannot destructure property 'collection' of 'undefined' as it is undefined.
directus  | 20:12:25 ✨ request completed GET 304 /items/test 8ms
```

**Comment by infomiho** [comment]
This seems related to `CACHE_SCHEMA` since after clearing the caches manually by using the `POST http://localhost:8055/utils/cache/clear` it all works again.

After inspecting the source code, it seems that schema cache is never cleared. Given that collection props like `singleton` can change on the fly, we should consider clearning the schema cache after editing collection props.

**Comment by rijkvanzanten** [comment]
> After inspecting the source code, it seems that schema cache is never cleared.

This is not entirely true. The schema cache is cleared in various operations:

https://github.com/directus/directus/blob/fa8ff60da9d44c1514e6dd9ac44b525d3570664f/api/src/services/collections.ts#L440-L442

That being said, it seems like it's not clearing it on update of a collection, which is an oversight 👍🏻

**Comment by infomiho** [comment]
Thanks man!

Sorry, I didn't mean to come off as saying you never cleared the cache, I just didn't find it with my primitive search, that's all 🙂
