### ISSUE TITLE
Canceling repeater drawer still creates blank item

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#7994]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

If you cancel the repeater create action, no blank item should be created.

### To Reproduce

1. Click "Add New Item" on a repeater
2. Click the "x" cancel button left of the drawer
3. Notice there is an empty repeater item

![Screen Shot 2021-09-13 at 9 06 35 AM](https://user-images.githubusercontent.com/522079/133094211-47370821-1999-464b-98a4-80a4374da4a2.png)

### What version of Directus are you using?

RC-92

### What version of Node.js are you using?

Node: 16.6.1

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

DO

**Comment by rijkvanzanten** [comment]
This is a similar setup as the problem we had with permissions. The empty item is created _first_, and then opened as a regular "edit". This means that cancelling cancels the "edit" operation, but not that initial creation.

**Comment by benhaynes** [comment]
So we should either switch this to a true "creat" flow, or find a way to remove/delete the item if you cancel.
