### ISSUE TITLE
Error Loading Calendar

### ISSUE THREAD

**Issue by hugopvl** [directus/directus#8004]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When I browse between bookmarks and then go back to the calendar, it doesn't load the information, if you refresh the page, the information is loaded normally.

![image](https://user-images.githubusercontent.com/81326296/133132023-35bfc294-4be4-4316-a7ed-1143a1cbd6b7.png)

![image](https://user-images.githubusercontent.com/81326296/133132067-c1fddd66-b6d2-4d3a-aa48-2b3291653188.png)

### To Reproduce

create a new bookmark - calendar

Start date - date
End date - date - (the same date)

### What version of Directus are you using?

9.0.0-rc.90

### What version of Node.js are you using?

14.17.0

### What database are you using?

SQL SERVER

### What browser are you using?

CHROME

### What operating system are you using?

WINDOWS 10

### How are you deploying Directus?

LOCALLY

**Comment by Nitwel** [comment]
This should be fixed by #7489 in the latest release.
Fell free to reopen this again if this is still an issue.
