### ISSUE TITLE
RangeError: Invalid time value

### ISSUE THREAD

**Issue by nickluger** [directus/directus#8015]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

A `RangeError: Invalid time value` is shown in the browser console, when visiting an item.

This is somehow related to`date-fns` date formatting, and I could track it down to [this line](https://github.com/date-fns/date-fns/blob/5f00a275cd5745b1c17fd7c9e811c8146c2cb3f9/src/format/index.js#L398) in date-fns. Certain dates seem to be evaluated to `Invalid Date` by `date-fns`.

Among those dates was `directus_users.last_access`, which I could track down by comparing its timestamp.

At first, I thought this might be due to a mismatch between my browser language (`en-US`) and my region setting on macOS (`Germany`), but after setting everything to US, I can confirm that also the second string shown below is not parseable by the dateformatter.

```
Tue Sep 14 2021 06:06:59 GMT+0200 (Mitteleuropäische Sommerzeit)
Tue Sep 14 2021 06:47:44 GMT+0200 (Central European Summer Time)
```

I put a `console.log(dirtyDate);` [into this function](https://github.com/date-fns/date-fns/blob/5f00a275cd5745b1c17fd7c9e811c8146c2cb3f9/src/format/index.js#L348) to print these strings before the error is thrown.

There was a similar issue, but quite old, so not sure whether related:
https://github.com/directus/directus/issues/3581

### To Reproduce

I'm not sure what led to this error, but basically it should be reproducible by visiting any item in a collection or creating a new item.
Interestingly it is **NOT** shown, when visiting a collection / list of items only or anything else like models, settings etc.

### What version of Directus are you using?

9.0.0-rc.92

### What version of Node.js are you using?

14

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
> it should be reproducible by visiting any item in a collection or creating a new item.

Wondering if it's the formatting for the activity/revisions in the right-sidebar 🤔

**Comment by nickluger** [comment]
I've found the underlying issue:

We have **hidden** `Timestamp` fields like `createdAt` which are automatically set by the database, using the idiomatic Postgres function `CURRENT_TIMESTAMP`.
```sql
"createdAt"    TIMESTAMP(3) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
```
These fields are hidden on the Detail-view and not marked as required in Directus (because Postgres should be responsible for creating them), but Directus still auto-reads the Postgres-function `CURRENT_TIMESTAMP` as default value and then somehow tries to convert the string `"CURRENT_TIMESTAMP"` to a date using date-fns. This obviously leads to the error described above.

This is how the fields look in Directus, see the default field filled with `CURRENT_TIMESTAMP` interpreted as constant string:

![Bildschirmfoto 2021-09-14 um 16 32 25](https://user-images.githubusercontent.com/32647249/133277325-e3f61fd7-8cee-4d37-bccd-8cd260aa25a5.png)

I think this issue is still valid, as quite many people use `CURRENT_TIMESTAMP` as default value in their PG timestamp columns and Directus should handle that gracefully.

Also, I'm not sure why these fields should be touched and converted at all, when they are not rendered and not required on the detail-view. Their interfaces shouldn't be loaded?

**Comment by HitomiTenshi** [comment]
I'm using `MariaDB 10.3.31` with a timestamp field that has `current_timestamp()` as its default value and we get the same issue.

In our case the field is not hidden and can be set by the user.

When creating a new item, the date input field stays empty. When clicking on it, all date fields in the dropdown are bugged and show NaN:

![chrome_2021-09-20_03-00-16](https://user-images.githubusercontent.com/7304212/133948911-942402af-d244-4f1b-bc07-ae24db879b4b.png)

The error Chrome throws is:

![chrome_2021-09-20_03-00-40](https://user-images.githubusercontent.com/7304212/133948927-a64d03c7-e80a-4976-a27e-559b7d12a393.png)
