### ISSUE TITLE
App displays all roles on filtered permissions

### ISSUE THREAD

**Issue by alwinzwets** [directus/directus#8021]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I have created a user role with permissions to view only a subset of other roles, however the app is showing all roles in the database.
When logging in as a user with this role I do get a filtered list of roles when assigning the new user a role.

Custom filter on Read access for roles:
![image](https://user-images.githubusercontent.com/710737/133223786-fb5bdd80-8779-424b-9e8c-6293dcc30fdc.png)

User managements is showing all roles in the side bar, even though Administrator is not in the filtered list:
![image](https://user-images.githubusercontent.com/710737/133223944-6e1ce023-f461-45b1-9ff0-f8f952df9cc4.png)

An error message is shown when clicking Administrator.

When assigning a role, I do get a filtered list: 
![image](https://user-images.githubusercontent.com/710737/133224064-20d82dc6-4b33-4d47-bdbf-b660c0679052.png)

### To Reproduce

- Create a few roles
- Add custom read rights on "Role":
```
{
  "id": {
    "_in": ["....", "..."]
  }
}
```
- Login as user with the filtered role and open user management.

### What version of Directus are you using?

v9.0.0-rc.92

### What version of Node.js are you using?

v16.6.1

### What database are you using?

Postgres 13.3

### What browser are you using?

Firefox 91

### What operating system are you using?

Ubuntu 21.04

### How are you deploying Directus?

Docker

**Comment by benhaynes** [comment]
I assume that navigation is pulling directly from the database, somehow bypassing the permissions. We'll look into this and get it resolved.

**Comment by rijkvanzanten** [comment]
> I assume that navigation is pulling directly from the database, somehow bypassing the permissions. We'll look into this and get it resolved.

Nope, nothing is ever pulled directly from the database. The app has no way to circumvent permissions in any way shape or form!

**Comment by rijkvanzanten** [comment]
> I have created a user role with permissions to view only a subset of other roles, however the app is showing all roles in the database.

What does this role look like? Does it have app access / admin access? Where did you configure this permission exactly? @alwinzwets

**Comment by alwinzwets** [comment]
I created a role with app access only, no admin access. On collection "Directus Roles", no permissions are granted except for Read access with "Use Custom"-permissions set to:
```json
{
    "id": {
        "_in": [
            "ef6514af-8d49-456f-9b27-4851d1c53fea",
            "9f99680d-87aa-4717-b57d-2b28437215de"
        ]
    }
}
```
This results in following database record:
```sql
INSERT INTO directus_permissions VALUES (166, '9f99680d-87aa-4717-b57d-2b28437215de', 'directus_roles', 'read', '{"id":{"_in":["ef6514af-8d49-456f-9b27-4851d1c53fea","9f99680d-87aa-4717-b57d-2b28437215de"]}}', NULL, NULL, '*');
```

**Comment by azrikahar** [comment]
Could this somehow be cache related (though I also tried it both cache on and off separately)? Can't seem to reproduce this on my end 😅

**Comment by alwinzwets** [comment]
It might be indeed. After restarting the instance and recreating a fresh user with this role all is displayed as expected. I'm not sure what kind of caching this can be as we don't have caching enabled on this instance. This issue can be closed, I'll report back if I encounter the issue again. :)

**Comment by rijkvanzanten** [comment]
Thanks for the heads up @alwinzwets! I wasn't able to reproduce this locally neither, so lets blame the internet gods for causing some havoc.
