### ISSUE TITLE
Catch errors thrown in CRON hook

### ISSUE THREAD

**Issue by dstoyanoff** [directus/directus#8022]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When creating a custom API hook, if there is an exception inside the implementation, it would fail silently, unless explicitly handled by the user.

Expected result: when creating the hook handler, Directus should wrap it in a try-catch block and report the errors to the console to provide better debugging experience.

### To Reproduce

Create a new custom hook that throws an error. Example:
```
export default defineHook(() => {
  return {
    "cron(* * * * *)": async () => {
      throw new Error("error");
    },
  };
});
```

Assert the API logs:
- Extension is loaded successfully
- With the above cron interval, the hook executes every minute. Logs do not output anything as if the hook didn't execute at all.

### What version of Directus are you using?

rc.92

### What version of Node.js are you using?

16

**Comment by nickluger** [comment]
Can confirm that for cron-hooks.

**Cannot** confirm that for event-driven (non-cron) hooks, like e.g. `items.create.before`.
```js
export default defineHook(() => {
  console.log("Registered hook");
  return {
    "items.create.before": async () => {
      throw new Error("error");
    },
  };
});
```
or plain function export without `defineHook`
```js
export default function registerHook() {
  console.log("Registered hook");
  return {
    "items.create.before": async () => {
      throw new Error("error");
    },
  };
}
```

both lead to
```
Registered hook
11:40:02 ✨ Server started at http://localhost:8055

.... creating new item ....

11:40:13 🚨 error
Error: error
    at EventEmitter.items.create.before (/Users/nickluger/bluepick/services/cms/dist/hooks/test/index.js:8:19)
    at EventEmitter.emitAsync (/Users/nickluger/bluepick/node_modules/eventemitter2/lib/eventemitter2.js:1156:36)
    at /Users/nickluger/bluepick/node_modules/directus/dist/services/items.js:79:44
    at /Users/nickluger/bluepick/node_modules/knex/lib/execution/transaction.js:221:22
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
11:40:13 ✨ request errored POST 500 /items/Item 180ms
```

as expected.

**Comment by dstoyanoff** [comment]
Thanks. Updated the title to only say cron hooks. It makes sense that event-driven hooks will throw some kind of error, because they are directly invoked by the app.
