### ISSUE TITLE
Multicolumn unique index: violation not handled in app

### ISSUE THREAD

**Issue by nickluger** [directus/directus#8028]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

This happens at least on Postgres 13.

If you have a `UNIQUE`-index/constraint on a single column and try to deliberately violate this constraint, the app UI handles the `400 - Bad Request` status code returned gracefully, by showing an error message alongside the affected field:

![Bildschirmfoto 2021-09-14 um 15 00 16](https://user-images.githubusercontent.com/32647249/133262087-895eb17e-d971-4cf0-b5ab-60722c2836e2.png)

If you have a **multicolumn** `UNIQUE` index/constraint on e.g. two fields like 

```sql
CREATE UNIQUE INDEX my_special_composite_index
    ON my_table (col_a, col_b);
```

Violating this index by creating a second row with already existing values for `col_a` and `col_b` will show no error message in the UI, although the API returns a `400 Bad Request`.
This is returned by the API and not catched and handled by the app:
```
{
  "errors": [
    {
      "message": "Field \"col_a, col_b\" has to be unique.",
      "extensions": {
        "code": "RECORD_NOT_UNIQUE",
        "collection": "my_table",
        "field": "col_a, col_b",
        "invalid": "item_1, cktjva3qy0002r8nghiig3pmp",
        "stack": "Error: Field \"col_a, col_b\" has to be unique.\n    at uniqueViolation (/Users/.../directus/dist/exceptions/database/dialects/postgres.js:44:12)\n    at extractError (/Users/.../node_modules/directus/dist/exceptions/database/dialects/postgres.js:21:20)\n    at translateDatabaseError (/Users/.../node_modules/directus/dist/exceptions/database/translate.js:28:48)\n    at /Users/.../node_modules/directus/dist/services/items.js:360:72\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
      }
    }
  ]
}
```

## What would be expected?

The error should be shown somehow to the user. Maybe in context of the affected columns, as the one-column-unique-index error, but not necessarily that precisely. 

At least a normal error message should be shown, similar to when an `Internal Server Error 500` or an `InvalidPayloadException` is thrown like this:

![Bildschirmfoto 2021-09-14 um 15 22 55](https://user-images.githubusercontent.com/32647249/133265434-faecbf89-e387-4cc8-833c-ce65c215f1e7.png)

### To Reproduce

1. Create a collection with a composite UNIQUE index.
2. Create an item in it.
3. Try to create another item with the same values.
4. No error shown, but item not created.
5. Take a look in the console and your network tab and see 400.

### What version of Directus are you using?

9.0.0-rc.92

### What version of Node.js are you using?

14

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
We don't technically support multi-column unique indexes yet, but I agree it would be nice to at least abstract the error properly 👍🏻
