### ISSUE TITLE
Updating nested M2O field breaks field preview 

### ISSUE THREAD

**Issue by alwinzwets** [directus/directus#8030]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

(First of all, thanks for your effort on the product and your responses to issues. Keep up the awesome work! :) )

I have a nested M2O model (Model > M2O > M2O > File). If I change the file in the most inner child M2O, the preview of the first M2O child on the root model disappears in the app. 
This is a minor display bug, when saving the root model and opening it again, the preview is restored.

This is on an Administrator account.

See the following video (27 sec):

https://user-images.githubusercontent.com/710737/133273435-7170fd23-6dbe-46f9-bbf4-59d9fcdb0c4f.mp4

### To Reproduce

- Create a model A with a file upload
- Create a model B with a M2O to model A
- Create a model C with a M2O to model B
- Create a record for all models
- Open Model C, from there open model B related record, from there open model A related record
- Change the file, save all
- Preview of model B on model C disappeared

### What version of Directus are you using?

v9.0.0-rc.92

### What version of Node.js are you using?

v16.8.0

### What database are you using?

Postgres 13.3

### What browser are you using?

Vivaldi/4.1.2369.21 Chrome/92.0.4515.159

### What operating system are you using?

Windows 10

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
This is effectively the same issue as https://github.com/directus/directus/issues/6293, but for m2o. I'll leave it open as a separate issue, as it's technically a different bit of the codebase, but the solve should be the same for both 👍🏻
