### ISSUE TITLE
Admin not cached when CACHE_AUTO_PURGE enabled

### ISSUE THREAD

**Issue by aidenfoxx** [directus/directus#8045]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

The Directus admin is not cached when using `CACHE_AUTO_PURGE` because navigating anywhere updates the users `last_page` value. This isn't a bug per-se, but it does undermine the value of enabling `CACHE_AUTO_PURGE`.

I'm happy to fix the issue, but first I'd like to understand how would be best to fix it. I have some ideas:

- Skip clearing cache when updating `last_page`
- Only purge items cache when clearing cache from `ItemsService`. Only clear schema cache when clearing cache from `CollectionsService`

The latter feels like the better solution overall.

### To Reproduce

Enable `CACHE_AUTO_PURGE` and browse the Directus admin. You will have latency comparable to having cache disabled.

### What version of Directus are you using?

rc92

### What version of Node.js are you using?

16.9.1

### What database are you using?

OracleDB

### What browser are you using?

Firefox

### What operating system are you using?

macOS, Ubuntu

### How are you deploying Directus?

K8S

**Comment by rijkvanzanten** [comment]
> The Directus admin is not cached when using CACHE_AUTO_PURGE because navigating anywhere updates the users last_page value. This isn't a bug per-se, but it does undermine the value of enabling CACHE_AUTO_PURGE.

Good point. This is a very difficult situation to solve for though 🤔 The user could be relationally nested under any other data point, so we can't just ignore user updates in the cache purging. 

The same goes for any other data that was altered. Ideally, we have some sort of way to know where the data point that was updated is cached, and only purge those particular cache records. I'd love to hear any thoughts you might have on how to achieve that

For now, i'll convert this to a feature request, as it's technically working as expected/intended
