### ISSUE TITLE
Can't update a table named user on Postgres

### ISSUE THREAD

**Issue by delucca** [directus/directus#8047]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Hi everyone.

I've configured my project with Directus, and it is running smoothly. The only issue I'm facing is specific with my "User" table.

I can update the data, remove and create new entities on any other table, but if I try to update my "User" table Directus simply doesn't work. By that I mean, it keeps loading without any other response or error.

I've already checked my container logs, but it throws me no error.

My user table is pretty simple, it contains the following columns:
- id `uuid` `UNIQUE`
- first_name `string`
- last_name `string`
- email `string` `UNIQUE`
- nickname `string`
- picture `string`
- gender `enum`
- role `string`
- linked_in_profile_address `string`
- about `string`
- authz_sub `string`
- created_at `date`
- updated_at `date`

Also, the table name is "user". In Postgres we always need to use double-quotes in those cases, since using `user` directly would fetch data from roles.

But, this issue is quite strange, before I model my data I was able to update a given user e-mail directly into Directus.

What should I do to troubleshoot this?

### To Reproduce

You can use my dump: https://drive.google.com/file/d/1hVd2sIZNJ5NLytLqCaSbwuz1baFQodGJ/view?usp=sharing

### What version of Directus are you using?

v9.0.0-rc.92

### What version of Node.js are you using?

15

### What database are you using?

Postgres 13

### What browser are you using?

Firefox

### What operating system are you using?

Linux

### How are you deploying Directus?

Kubernetes (in a Docker container)

**Comment by rijkvanzanten** [comment]
The dump says it's no longer available. Would you be able to share it here on GH so it doesn't disappear? 🙂

**Comment by rijkvanzanten** [comment]
I was able to create a collection named `user` in Directus just fine 🤔 

I'm wondering if you might've run into https://github.com/directus/directus/issues/8083, which has a very similar symptom

**Comment by delucca** [comment]
@rijkvanzanten sorry about that! I've just restored the file. Can you check now please?

I'm going to take a look on #8083 but I highly doubt it. I don't have any conditions in my data model for that table

**Comment by rijkvanzanten** [comment]
Dump backup for archiving: [dump.sql.zip](https://github.com/directus/directus/files/7211419/dump.sql.zip)

**Comment by delucca** [comment]
> @delucca I'm able to update your user table in the dump without a problem, so I'm expecting the problem to exist within the `directus_` tables.
> 
> > I'm going to take a look on #8083 but I highly doubt it. I don't have any conditions in my data model for that table
> 
> Yeah, makes sense. That being said, it was super easy to accidentally setup this corrupted row before, and it's very easy to miss, so I wouldn't rule it out right away slightly_smiling_face

Thanks!

[Here is](https://drive.google.com/file/d/1UdLMFzLIdPpaiKaGbJs71wGHHwiODZ7S/view?usp=sharing) the dump of my `directus_` tables.

**Comment by rijkvanzanten** [comment]
@delucca Can confirm this was caused by #8083 🙂 

![CleanShot 2021-09-27 at 18 43 19@2x](https://user-images.githubusercontent.com/9141017/134995170-3367dab2-c164-4f77-8a89-d6ee653bbd12.png)

Updating to the latest version, or removing the empty conditions row from your `user.gender` field should resolve the issue 👍🏻
