### ISSUE TITLE
HTTP SEARCH doesn't work

### ISSUE THREAD

**Issue by andraspalfi** [directus/directus#8071]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Based on doc (https://docs.directus.io/reference/api/introduction/#search-http-method) it is possible to send the query in the request body using SEARCH. 
Actually it doesn't work, tried several mode, directus just ignores the body - based on logs. 
Checking directussdk turned out that sends the parameter in url.

### To Reproduce

Just try out the SEARCH in the example

### What version of Directus are you using?

Directus 9.0.0-rc.92

### What version of Node.js are you using?

v14.15.4

### What database are you using?

postgresql

### What browser are you using?

safari,chrome, rest clients, postman

### What operating system are you using?

ubuntu, mac

### How are you deploying Directus?

local install, DigitalOcean droplet

**Comment by rijkvanzanten** [comment]
It seems to work as expected on my end:

```
SEARCH /items/articles HTTP/1.1
Content-Type: application/json
Host: localhost:8055
Connection: close
Content-Length: 92

{
  "query": {
    "filter": {
      "title": {
        "_eq": "Example"
      }
    }
  }
}
```

Is your content type header set to `application/json` ?

**Comment by andraspalfi** [comment]
🤦  you're right, it was the missing json content type, sorry. Works perfectly!
Thanks for the quick response!
Perhaps worth to add a note to doc for others as well.
Thanks,
Andras

**Comment by benhaynes** [comment]
> Perhaps worth to add a note to doc for others as well.

CC @alesvaupotic

**Comment by beschneider** [comment]
Would someone be able to provide an example for using "SEARCH" with Axios or fetch? I've been trying to get it to work in my Vue app. I keep getting CORS errors "Method SEARCH is not allowed by Access-Control-Allow-Methods in preflight response" which I'm not getting with simple GET requests using Axios.

This works:

```
const response = await this.$axios.get(`http://localhost:8055/items/collection?filter={"name":{"_contains": "${value}"}}`);
```

But I can't get "SEARCH" to work with either Axios or fetch.

```
const response = await this.$axios({
                    method: "SEARCH",
                    url: "http://localhost:8055/items/collection",
                    data: {
                        "query": {
                            "filter": {
                                "name": {
                                    "_contains": value
                                }
                            }
                        }
                    }
                });
```

and

```
const response = await fetch("http://localhost:8055/items/collection",{
                    method: "SEARCH",
                    headers: {
                        "Content-Type": "application/json",
                    },
                    body: JSON.stringify(`{
                        "query": {
                            "filter": {
                                "name": {
                                    "_contains": "${value}"
                                }
                            }
                        }
                    }`)
```

**Comment by azrikahar** [comment]
@beschneider Judging from `Method SEARCH is not allowed by Access-Control-Allow-Methods in preflight response`, perhaps you can try adding `SEARCH` to the `CORS_METHODS`: https://docs.directus.io/configuration/config-options/#cors

If that still doesn't work, it would be better to open a separate issue since your issue revolves around CORS, rather than the missing content type 👍
