### ISSUE TITLE
Fit parameter is ignored generating thumbnail

### ISSUE THREAD

**Issue by andraspalfi** [directus/directus#8072]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

According to doc (https://docs.directus.io/reference/api/assets/#requesting-a-thumbnail) the thumbnail generation mode can be influenced by using the 'fit' parameter. I found it generates the same always regardless of the four values or even removing that parameter.
Adding "invalid" value to "fit" however returns with error, so seems it is at least parsed - then not used.

### To Reproduce

try out according to docs

### What version of Directus are you using?

v9.0.0-rc.92

### What version of Node.js are you using?

v14.15.4

### What database are you using?

postgresql

### What browser are you using?

chrome, safari, postman

### What operating system are you using?

ubuntu

### How are you deploying Directus?

DigitalOcean droplet

**Comment by andraspalfi** [comment]
Using predefined presets the feature works

**Comment by Nitwel** [comment]
Did you also set the `width` and `height` parameters, as they are necessary to work for cropping?

**Comment by rijkvanzanten** [comment]
Seems to work as expected on my end 🤷🏻 

![CleanShot 2021-09-17 at 15 44 36@2x](https://user-images.githubusercontent.com/9141017/133845060-e84f15ac-e6b3-4157-bbbc-6e213f542640.png)

![CleanShot 2021-09-17 at 15 44 55@2x](https://user-images.githubusercontent.com/9141017/133845079-b9541db1-cf7b-4e62-b2dd-fc3bd49a76ce.png)

![CleanShot 2021-09-17 at 15 45 05@2x](https://user-images.githubusercontent.com/9141017/133845100-d8b61770-c096-4f54-899a-bdc5797d958f.png)

![CleanShot 2021-09-17 at 15 45 14@2x](https://user-images.githubusercontent.com/9141017/133845110-930c3c98-5d79-44a0-b4c7-3adb157c0bf3.png)

**Comment by andraspalfi** [comment]
I confirm it works. There were a typo in parameters and no error responded but used the other parameter which was correct which confused me because the image was resized. Sorry and thanks!
