### ISSUE TITLE
Empty row in conditional fields prevents saving

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#8083]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When you setup a new row in conditional fields, but don't actually configure anything, the app will no longer save the items detail page.

### To Reproduce

Setup a conditional fields row, without adding any rule or changes

### What version of Directus are you using?

rc92

### What version of Node.js are you using?

16

### What database are you using?

Pg 13

### What browser are you using?

Edge

### What operating system are you using?

macOS

### How are you deploying Directus?

DO

**Comment by mhdaouas** [comment]
You are right, wonder how this wasn't detected after all these commits and reached maturity :p ! Maybe the condition feature was added lately.

**Comment by rijkvanzanten** [comment]
@Nitwel actually detect this issue before in https://github.com/directus/directus/pull/7574, but missed another place where the same problem happens 😄  And yeah, conditional fields is still pretty new (since rc.86) 🙂
