### ISSUE TITLE
Validate for missing filename in multipart/form-data file upload

### ISSUE THREAD

**Issue by panchmp** [directus/directus#8101]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Can't upload a file with JAX-RS  client

### To Reproduce

With code 

```
@ClientHeaderParam(name = "Authorization", value = ["Bearer XXXXXXXXXXXXXXXXXXXXX"])
@Path("/files")
interface FileClient {

    @POST
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Produces(MediaType.APPLICATION_JSON)
    fun upload(@MultipartForm data: FileObjectUpload): ResponseItem<FileObject>

    class FileObjectUpload(
        @field:FormParam("file")
        @field:PartType(MediaType.APPLICATION_OCTET_STREAM)
        val file: File,
    )
}
```

```
fileClient.upload(
                    FileObjectUpload(
                        file = new File("somefile.jpeg")
                    )
                
```

I get error
```
05:19:45 ✨ request completed POST 200 /files 122ms
node:internal/errors:464
ErrorCaptureStackTrace(err);
^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
at new NodeError (node:internal/errors:371:5)
at validateString (node:internal/validators:119:11)
at Object.parse (node:path:1450:5)
at Busboy.<anonymous> (/directus/node_modules/directus/dist/controllers/files.js:51:72)
at Busboy.emit (node:events:394:28)
at Busboy.emit (/directus/node_modules/busboy/lib/main.js:37:33)
at PartStream.<anonymous> (/directus/node_modules/busboy/lib/types/multipart.js:214:13)
at PartStream.emit (node:events:394:28)
at HeaderParser.<anonymous> (/directus/node_modules/dicer/lib/Dicer.js:50:16)
at HeaderParser.emit (node:events:394:28) {
code: 'ERR_INVALID_ARG_TYPE'
}
```

Because directus expected response like
```
Content-Disposition: form-data; name="file"; filename="820846.jpg"
Content-Type: image/jpeg

```
but filename is not mandatory and doesn't provided by default for JAX-RS

Then I tried chage 
```
    class FileObjectUpload(
        @field:FormParam("file")
        @field:PartType(MediaType.APPLICATION_OCTET_STREAM)
        val file: File? = null,
    )
```    
    to 
```
    class FileObjectUpload(
        @field:FormParam("file")
        @field:PartType(MediaType.APPLICATION_OCTET_STREAM)
        @field:PartFilename("some-bla-bla.jpg")
        val file: File? = null,
    )
```
Then I  got error 
```
06:11:47 🐛 You don't have permission to access this.
```
But I used a token for the user from group admin and this user can upload images via UI

### What version of Directus are you using?

directus/directus:9.0.0-rc.93

### What version of Node.js are you using?

I don't know

### What database are you using?

not relevant

### What browser are you using?

JAX-RS client

### What operating system are you using?

Linux

### How are you deploying Directus?

K8s via Docker

**Comment by rijkvanzanten** [comment]
Directus requires the filename as well as the file contents to be set. I'm down to discuss ways to make that optional in a new feature request, but at this point in time, this seems to be working as expected. 

How are you authenticating into the API in this request?

**Comment by panchmp** [comment]
> his seems to be working as expected
Do you really expect that the app is crashed instead of 400 Bad Request?

> How are you authenticating into the API in this request?
@ClientHeaderParam(name = "Authorization", value = ["Bearer XXXXXXXXXXXXXXXXXXXXX"])

**Comment by rijkvanzanten** [comment]
> Do you really expect that the app is crashed instead of 400 Bad Request?

No.. You only mentioned you saw an error, didn't realize you meant crashes with a 500 with that 🙂

**Comment by panchmp** [comment]
@rijkvanzanten one more issue 
Wrong request (I miss @ for -F "file=somefile.jpg;type=image/jpg" so the value is just string instead of a binary stream)

```
curl  
  -X POST "https://directus.somesite.com/files"
  -H "Authorization: Bearer XXXXXXXXXXXXXXXXX"
  -H "Accept: application/json"
  -H "Content-Type: multipart/form-data" 
  -F "file=somefile.jpg;type=image/jpg"
  ```
return random FileObject instead of 400 Bad Request
