### ISSUE TITLE
Browser back button should navigate through overlays

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#811]
If you are on an edit page (for example) and you open up a relational field (like choosing a file) as an overlay – if you swipe back (or browser back) it should close the overlay, not take you back a page.

Whenever you are in an overlay (see image/icon below) browser-back should close the overlays sequentially... not just take you back to the previous page.

![screen shot 2015-06-03 at 3 51 10 pm](https://cloud.githubusercontent.com/assets/522079/7969942/777aba96-0a08-11e5-8238-ffe8a35a22be.png)

**Comment by benhaynes** [comment]
@WellingGuzman can't we do this by pushing a history state?

**Comment by WellingGuzman** [comment]
@benhaynes I believe this could be solve like that, when we open a overlay we should push a history state, silently, we can see if we can push the same, OR pushing a fake one but without reflecting the url, or using hash.

Hopefully this would solve this request/issue?

**Comment by benhaynes** [comment]
Yeah, I think that should do it!

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/78e4cc831ce80a0863999038c3e95d89d047bab7
