### ISSUE TITLE
Schema snapshot - group is persisted with an id

### ISSUE THREAD

**Issue by dstoyanoff** [directus/directus#8113]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I have found the same [issue](https://github.com/dstoyanoff/directus-auto-migrate/issues/6) that I have in directus-auto-migrate. It might happen with other fields too, but I caught it with the group.

The issue is basically that the group is persisted with an id. This id points to another field, but this is only the case in the local environment. This id would point to another field (or nothing) in another instance, which causes a problem.

### To Reproduce

Create a field-group and create one field inside of it. Then run the schema generation script and observe the result.

### What version of Directus are you using?

rc.93

**Comment by rijkvanzanten** [comment]
Ha sneaky sneaky order of entry. Good catch.

I think for both implementations, we should be able to solve it by inserting all the rows with group = null first, and then insert the other fields sorted by group ID

**Comment by dstoyanoff** [comment]
The problem is mostly how to generate proper data for the snapshot. For example I have done a setup with some grouping inside and I want to persist it. This would however persist the group with an ID, which is not optional as on the other environment this ID might mean something else (worst case as it would create a mess) or not mean anything at all and fail due to unmet constraint. 

In migrations I was trying to do some smart query (not much of luck with knex so far), where the update statement would actually use a select to get the field by it's name + collection (unique enough) and not id. But it's very specific and hard to do. This is however applicable for generating migrations. When dealing with snapshot file it's far harder to do. It's probably worth changing the structure a little or rethink how grouping works in general. At the moment in the UI there is no difference between grouping things and creating a presentational field before a group of fields, so you might just rework the functionality.

Needs some careful thinking

**Comment by rijkvanzanten** [comment]
I think a workable solution would be to rely on the field key instead of on the primary key of the directus_fields row for the "group" value. We know that the field name is unique per collection, and we know you can't have a field grouped within a field in another collection

**Comment by dstoyanoff** [comment]
I totally agree on that approach. It's straightforward and simple, yet would work flawlessly.
