### ISSUE TITLE
Hide split view button when there's only one translation language

### ISSUE THREAD

**Issue by HitomiTenshi** [directus/directus#8137]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

We only have one translation language and the translation split view button causes confusion, because it opens an empty split view with no other language selected:

The language select:
![chrome_2021-09-19_03-03-44](https://user-images.githubusercontent.com/7304212/133912331-837bc373-3f64-498e-a2f2-19f9f9efdf35.png)

Our languages table:
![chrome_2021-09-19_03-04-24](https://user-images.githubusercontent.com/7304212/133912333-91671323-6d9c-4f0c-bda6-b26f26f42d29.png)

The app we develop is primarily German, with English translations. Our **main tables** have all the text fields in German and when translations for specific fields are needed a translations table is being used with only the specific translatable fields.

As a workaround we currently use the following css to hide the split view button, but it would be nice if directus would check if more than 1 language is available to show the split view button:

```css
.translations .language-select .append-slot {
    display: none;
}
```

### To Reproduce

1. Only have 1 language in the languages table
2. Create a translation field
3. Press the split view button

### What version of Directus are you using?

v9.0.0-rc.93

### What version of Node.js are you using?

14.17.6

### What database are you using?

MariaDB 10.3.31

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally via npm package

**Comment by Nitwel** [comment]
This issue reminds me so much of this 😂:
> A QA engineer walks into a bar. Orders a beer. Orders 0 beers. Orders 99999999999 beers. Orders a lizard. Orders -1 beers. Orders a ueicbksjdhd. 

Awesome catch! ❤️

**Comment by benhaynes** [comment]
Hahahaha... I hadn't heard that one, love it! 🤣
