### ISSUE TITLE
Multiple level deep m2o field is initially empty even though a selection has been made

### ISSUE THREAD

**Issue by HitomiTenshi** [directus/directus#8139]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

This is what happens:

https://user-images.githubusercontent.com/7304212/133913404-2c184d73-3c42-4ed1-a066-15e8f8869b98.mp4

We have the following tables:

1. suppliers
2. addresses
3. countries

Starting from the suppliers table, this is how we set the relations up:

- `table: suppliers`
- `field: addresses` (m2m)
- - `table: addresses`
- - `field: country` (m2o, default selected value: 'DE')
- - - `table: countries`
- - - `field: code` (Identity)
- - - `field: name`

### To Reproduce

I have exported my schema, it is available here temporarily (until resolved):
https://dekinai.moe/PtgTBlcq.yaml

Do the following:

1. Create a few test countries
2. Go to suppliers collection
3. Add a new supplier
4. Add a new address for the supplier
5. You will now see the problem as shown in the video

### What version of Directus are you using?

v9.0.0-rc.93

### What version of Node.js are you using?

14.17.6

### What database are you using?

MariaDB 10.3.31

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally via npm package

**Comment by rijkvanzanten** [comment]
I believe this was resolved in https://github.com/directus/directus/pull/9711. We can reopen if the problem persists in 9.1.3+ 🙂
