### ISSUE TITLE
RelationItem in Javascript SDK with typescript bug

### ISSUE THREAD

**Issue by NickSettler** [directus/directus#8144]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I have two collections: `people` and `goods`. Each person in `people` collection have some goods in `goods` collection. So there is a O2M relation field in `people` collection named `used_goods`. When I'm getting data from people collection the used_goods field has an array of items (theirs IDs). And on the opposite - when I'm getting goods from goods collection each item of returned array contains a field person with ID of an item from people collection.

I am using Javascript SDK in my React project with Typescript. When I initialize a Directus instance I also specify these two collections types. Types look like this

```ts
type PeopleModel = {
  id: ID;
  first_name: string;
  last_name: string;
  goods: RelationItem<GoodsModel>;
};

type GoodsModel = {
  id: ID;
  name: string;
  count: number;
  price: number;
  person: RelationItem<PeopleModel>;
};
```

When I'm trying to use method `createOne` for creating a new good, I'm getting typescript error. I am creating an item like this

```ts
directus
  .items("goods")
  .createOne({
    name: "Good name",
    count: 1,
    price: 10,
    person: 1,
  })
```

The person key in the object specifies ID of a person from people collection. And without collections types this work properly. But when I set with generics types of collections I'm getting an error that person cannot be a number - it must contain all fields from `PeopleModel` type. And I suppose that it's wrong - I really need to pass only an ID of an item from `people` collection - not the whole item.

### To Reproduce

1) Create a typescript NodeJS project
2) Initialize Directus SDK 
3) Set Directus collection types with a generic like in the [documentation](https://docs.directus.io/reference/sdk/#typescript)
4) Try to create an item in the collection which has at least on relation with other collection using `createOne` method

### What version of Directus are you using?

v9.0.0-rc.93

### What version of Node.js are you using?

16.8.0

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker compose

**Comment by joselcvarela** [comment]
Hello,
The problem is not related with the Directus itself but how you are defining your models.
Since we are using generic templates, we just need to change your models for something like this
```
type GoodsModel = {
  id: ID;
  name: string;
  count: number;
  price: number;
  person: number | RelationItem<PeopleModel>;
};
```

notice the `number |` in `person` property
