### ISSUE TITLE
Deleting an item with unsaved changes warns about unsaved changes even though the item has already been deleted

### ISSUE THREAD

**Issue by HitomiTenshi** [directus/directus#8146]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I was editing an item and realized that it was not needed anymore, so I pressed the delete button.

First the dialog for "are you sure you want to delete" appears, if you press "Delete" another dialog pops up and asks "are you sure you want to leave this page" because of unsaved changes.

The issue now is that by pressing the "Delete" button, the item has already been deleted. The unsaved changes warning message that appears is somewhat confusing. If I press "Discard Changes" everything is fine and I land back at the collection page.

If I press "Keep Editing" I get back to the "are you sure you want to delete" dialog. Clicking "Cancel" here gets you back to the item you were editing, but the problem now is that in reality this item is already deleted and what you see is its ghost data 😄. 

When pressing the "Delete" button on an item with unsaved changes it should just delete it and not warn about unsaved changes.

### To Reproduce

1. Edit an item
2. Press delete
3. Confirm delete
4. Unsaved changes warning appears (but the item is already deleted)

### What version of Directus are you using?

v9.0.0-rc.93

### What version of Node.js are you using?

14.17.6

### What database are you using?

MariaDB 10.3.31

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally via npm package

**Comment by joselcvarela** [comment]
IMO, this is what should happen:
If we click the delete button, the delete popup should appear but the save changes popup should not appear.
