### ISSUE TITLE
Accept user invitation doesn't trigger users update hooks

### ISSUE THREAD

**Issue by gkielwasser** [directus/directus#8163]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Accepting user invitation is mutating the user. It updates its password and its status.
It should trigger the corresponding users update hooks (before/after).

### To Reproduce

Invite a user and accept the invitation.
No users update hooks are trigerred.

### What version of Directus are you using?

v9.0.0-rc.92

### What version of Node.js are you using?

v14.16.0

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

locally

**Comment by aidenfoxx** [comment]
@rijkvanzanten This is fixed in #6942.
