### ISSUE TITLE
The required field accepts the empty string

### ISSUE THREAD

**Issue by frapicc** [directus/directus#8165]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

In the directus documentation: 
Field Setup
Required — Toggles if a value for the Field is required.
Empty strings ('') and NULL are not accepted as a valid value.
But When setting up a new table, i specified that the field was required, however using Postman and the API when i entering an empty string as a value, i did not receive an error.

### To Reproduce

Create collection A
Create a text type field 

- required : true

finally, I insert an empty string in the API

### What version of Directus are you using?

rc 93

### What version of Node.js are you using?

v12.13.0

### What database are you using?

Mysql 8.0.23

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by joselcvarela** [comment]
The 'Field' section is related to how the field appears on app.
If you want to make the field required, you should disable the 'Allow NULL value'

Or, you can use a custom hook to verify if a property is missing before inserting into database using custom hooks.
https://docs.directus.io/guides/api-hooks/#custom-api-hooks

**Comment by frapicc** [comment]
The field has 'Allow NULL value' disabled but it is required in 'field', but the API on postman still accepts the empty string. it's normal?
The only way is to use a custom hook?

**Comment by rijkvanzanten** [comment]
"Allow NULL" controls whether or not the database accepts "null" as a value.
"Required" sets whether or not a value* needs to be provided on create

\* the meaning "a value" here is the tricky bit. We can't really assume what is considered a valid value. Technically speaking, `''` is a defined "value" (as it's not undefined), though I can see how that feels counterintuitive  for this example.

You don't have to create a custom extension to enable this sort of validation. You should be able to add a "nempty" rule to validation in permissions 👍🏻

**Comment by joselcvarela** [comment]
Sorry, my bad.
Here is what Rijk is mentioning:
![image](https://user-images.githubusercontent.com/14039341/134018846-0535fd76-b98d-4d96-880b-eab036e437e9.png)

https://docs.directus.io/reference/filter-rules/#filter-rules

**Comment by frapicc** [comment]
![image](https://user-images.githubusercontent.com/91060722/134026714-74f8be1b-8982-47ce-b4a6-207b8146c742.png)

like this?

**Comment by rijkvanzanten** [comment]
Yup 👍🏻
