### ISSUE TITLE
Translations not working on single object

### ISSUE THREAD

**Issue by TheAzack9** [directus/directus#8173]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

(I could not find any issues atleast detailing this 😅 )

It seems that when using single object collections that translations just doesn't quite work. It seems that it creates the translations correctly, but when reloading the page it cannot query it. Through some inspection it seems that it tries to query the api with `https://{{url}}/items/test_translations?fields=*&limit=-1&filter={"test_id":{"_eq":"+"}}`, so it would seem that instead of using an id that it instead defaults to +. 

### To Reproduce

Steps to reproduce:

1. Create a collection that is a single object (e.g named `test`)
2. Create a translation field
3. Create a some field in the translation collection (i made a text area with wysiwyg)
4. Go to the collection and insert some data into the item. 
5. Save the item
6. All translations are now blank (since it couldn't fetch them)

If you reveal the translation collection in the app does it seem to be there :)

### What version of Directus are you using?

9.0.0-rc 93

### What version of Node.js are you using?

16.0.0 (i guess, i use the docker image)

### What database are you using?

MySql 8.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker through azure :)

**Comment by TheAzack9** [comment]
Sorry for being flakey on the last issue, i will create a database dump if you cannot reproduce this :) (Feel free to ask!)

**Comment by rijkvanzanten** [comment]
haha no worries! The last issue was super difficult to reproduce, but this sounds way easier to figure out on our end 😄

**Comment by TheAzack9** [comment]
Ironically is the other issue fixed in a later version, so you somehow found it and squashed it :)
