### ISSUE TITLE
Query on nested relations skipped

### ISSUE THREAD

**Issue by gustavodipietrogva** [directus/directus#8187]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I have three collections:

* `dm_properties`
* * `id`
* `dm_property_units`
* * `id`
* * `property`
* `dm_units_availabilities`
* * `id`
* * `property_unit`

Each `dm_properties` has one or more `dm_property_units` and each `dm_property_units` has one or more `dm_units_availabilities`.

I've modeled this on `directus_relations` like this:

```json
  {
    "many_collection": "dm_property_units",
    "many_field": "property",
    "one_collection": "dm_properties",
    "one_field": "units",
    "one_deselect_action": "nullify"
  },
  {
    "many_collection": "dm_units_availabilities",
    "many_field": "property_unit",
    "one_collection": "dm_property_units",
    "one_field": "availabilities",
    "one_deselect_action": "nullify"
  }
```

also adding the virtual fields `units` and `availabilities` in `directus_fields`.

_The **read** operations on this do work._ I correctly get back a json describing the correct hierarchies with the correct data.

_I **can** filter `dm_properties` by units._ For instance, `/items/dm_properties?fields=*.*&filter[units][id]=1` gives me the correct result while `/items/dm_properties?fields=*.*&filter[units][id]=9999` yields no results since there's no `dm_properties` #9999.

_I **can** filter the `dm_property_units` by availabilities._ For instance, `/items/dm_property_units?fields=*.*&filter[availabilities][id]=1` gives me the correct result while `/items/dm_properties?fields=*.*&filter[availabilities][id]=9999` yields no results since there's no`dm_units_availabilities` #9999.

_However, I **cannot** filter `dm_properties` by availabilities_. It seems like the filtering mechanism falls apart when confronting an indirect relationship. I expect this to return no results `/items/dm_properties?filter[units][availabilities][id]=9999` but it returns the whole collection of `dm_properties` since, apparently, no filter is applied.

### To Reproduce

Create collections A, B and C, create two relations linking A to B and B to C and try to filter As by Cs.

### What version of Directus are you using?

9.0.0-rc.85

### What version of Node.js are you using?

15.0.0

### What database are you using?

MySQL 8.0.25

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
Please update to the latest version.

If the problem still persists there, we can reopen and continue the investigation 👍🏻
