### ISSUE TITLE
Dividers are always at the bottom

### ISSUE THREAD

**Issue by Attacler** [directus/directus#8216]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I have created a divider above the last 2 fields but somehow it doesnt appear that way:

![image](https://user-images.githubusercontent.com/42644889/134227730-2a0ea8cd-b766-4f5d-b7de-475b10c991f7.png)
![image](https://user-images.githubusercontent.com/42644889/134227743-7c9f746a-7513-4a82-b40b-10094e0dda81.png)

The divider is at the bottom.

### To Reproduce

Create a collection (singleton)
Create some fields in it
Place a divider between those fields
Go to the record page and it happend!

### What version of Directus are you using?

docker rc93

### What version of Node.js are you using?

docker

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker on linux

**Comment by benhaynes** [comment]
Mine did that too (after a recent update). Dragging them down, and then back into position fixed for me. I should have looked in the DB first to see if the divider field had a set `sort` value.

**Comment by Attacler** [comment]
> Mine did that too (after a recent update). Dragging them down, and then back into position fixed for me. I should have looked in the DB first to see if the divider field had a set `sort` value.

It indeed works after that, but it still happends when you add a new field under the divider

**Comment by Attacler** [comment]
so creating a divider
then create a field
