### ISSUE TITLE
Readonly condition if role different from status

### ISSUE THREAD

**Issue by mhdaouas** [directus/directus#8227]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I have a workflow where I use statuses on a specific content type that have specific roles as values. I want users who are still waiting for their workflow step to get fields as readonly. I tried this condition without success:
```
{
"status":{
   "_neq":"$CURRENT_USER.role"
}
}
```
Is my syntax correct?

### To Reproduce

See above

### What version of Directus are you using?

9.1.4

### What version of Node.js are you using?

14.16.1

### What database are you using?

Postgresql 13

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Locally on Visual Code

**Comment by benhaynes** [comment]
Try: `$CURRENT_ROLE` instead.

Also, this is not really a bug report, but more of a question on syntax... which should really be a GitHub Discussion.

**Comment by mhdaouas** [comment]
Thank you very much! You saved me! Sorry I couldn't find the right tag for the issue. Should I delete it?
