### ISSUE TITLE
Undo last applied migration, instead of newest migration, when running `migrate:down`

### ISSUE THREAD

**Issue by HitomiTenshi** [directus/directus#8254]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I chose the wrong time to upgrade I think 😂

I upgraded to the latest version `v9.0.0-rc.94` and faced issue #8253. No problem right? Just go back one version earlier right?

This is my migration log from when I upgraded the database after running `npm update`:

```
server@user:~/directus$ npx directus database migrate:latest
23:42:38 ✨ Running migrations...
23:42:38 ✨ Applying Add Insights...
23:42:39 ✨ Database up to date
```

After facing my issues I did the following things:

1. Stop the currently running directus instance
2. `npx directus database migrate:down`

This is the log I get now:

```
server@user:~/directus$ npx directus database migrate:down
00:12:32 ✨ Running migrations...
00:12:32 ✨ Undoing Move Module Setup...
00:12:33 ✨ Downgrade successful
```

This isn't the migration it was applying previously...

I did some more, I was brave:

```
server@user:~/directus$ npx directus database migrate:down
00:24:41 ✨ Running migrations...
00:24:41 ✨ Undoing Webhooks Collections Not Null...
00:24:41 ✨ Downgrade successful
server@user:~/directus$ npx directus database migrate:down
00:24:43 ✨ Running migrations...
00:24:43 ✨ Undoing Remove Limit Column...
00:24:43 ✨ Downgrade successful
server@user:~/directus$ npx directus database migrate:down
00:24:45 ✨ Running migrations...
00:24:45 ✨ Undoing Add Geometry Config...
00:24:46 ✨ Downgrade successful
```

The Add Geometry Config looked familiar from a way earlier version... It seems the migrations don't know about `Add Insights` even though I'm still on `v9.0.0-rc.94`.

I ran migrations to latest again and downgraded to `v9.0.0-rc.93`. Of course the old version pretty much doesn't work with the upgraded db.

I'm basically boned now.

### To Reproduce

Upgrade to `v9.0.0-rc.94`, then try downgrading to `v9.0.0-rc.93` again.

Terrible release imo, nothing against you guys though, love your work.

### What version of Directus are you using?

v9.0.0-rc.94

### What version of Node.js are you using?

14.17.6

### What database are you using?

MariaDB 10.3.31

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally via npm package

**Comment by azrikahar** [comment]
> I ran migrations to latest again and downgraded to v9.0.0-rc.93. Of course the old version pretty much doesn't work with the upgraded db.

Can you share what happens when you use rc.93 with an upgraded db? does it by any chance mentions "No App Access"?

technically this should still work because the Add Insights migration creates two new tables which doesn't interfere with other tables if left untouched, but yes it should be able to be reverted via "migrate:down" in the first place. Will get back to you once I confirmed some details with the team.

**Comment by HitomiTenshi** [comment]
@azrikahar I just installed rc.93 again with the db left upgraded (which I thought I did earlier today) but now its working without any issues. I think I tested it with one migration down which was `Undoing Move Module Setup`, because I thought maybe the naming was wrong or something.

So I'm not boned after all, phew 😂

Everything is back to working again now, thank you for helping me out with this one! I'll be skipping rc.94 because of the REST API issue (#8253). My db is now with rc.94 tables but it works. If I need to migrate down before upgrading to the next rc.95, could you please let me know? I just want to avoid getting more problems with my current weird db state. 👍

**Comment by azrikahar** [comment]
@HitomiTenshi that's great news! Thanks for the prompt response, though I understand the frustration caused by the migration. 

> My db is now with rc.94 tables but it works. If I need to migrate down before upgrading to the next rc.95, could you please let me know? I just want to avoid getting more problems with my current weird db state. 👍

Will do 👍 hopefully we can get this sorted out in time.

**Comment by joselcvarela** [comment]
@HitomiTenshi we advise to backup your data before any up/downgrades.
We appreciate your trust in us 😁 but issues happens.

https://docs.directus.io/guides/projects/#upgrading-updating-a-project

**Comment by HitomiTenshi** [comment]
@joselcvarela I guess this was my wake up call, next time I'll be prepared 👍

**Comment by rijkvanzanten** [comment]
The interesting thing here is that "migrate:down" undoes the last migration based on the _version_, not the date it was _applied_. That's definitely something we have to alter!

In this particular case, the migration _version_ of the insights migration is way older, as that PR has been in the works for a couple months.
