### ISSUE TITLE
Cannot filter NULL from dropdown list

### ISSUE THREAD

**Issue by nordcart** [directus/directus#8258]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Updating from rc.93 to rc.94 doesn´t let you manually force NULL value in the filters for a dropdown list. IS NULL / IS NOT NULL alternatives are also not in the filter list.

(There should be 1 result)
![image](https://user-images.githubusercontent.com/12813484/134461744-290fd524-b7ab-42c0-af64-f1cc24fbc4fe.png)

(Allow null is set on)
![image](https://user-images.githubusercontent.com/12813484/134460961-e9bfadc8-3063-4f76-a5fb-2349169e9447.png)

### To Reproduce

1. Open a collection
2. Advanced filter
3. IS NULL / IS NOT NULL is not available
4. Manually forcing NULL-value doesn´t work

### What version of Directus are you using?

9.0.0-rc.94

### What version of Node.js are you using?

don´t know

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by joselcvarela** [comment]
Hey,
Just tried here and everything seems normal.
I have also tried with string field.

Can you fresh install with rc94? Just to be sure if it's related with the upgrade or the rc94 itself.

**Comment by nordcart** [comment]
I did not fresh install rc94, but in the field interface settings, i unselected "Allow no Selection", I can now use "is empty/is not empty" for my project.

Do you get "is null, is not null" in the filter menu? For me, they are not an alternative in the advanced filters. Forcing "_null, or NULL" in the filters, doesn´t work eihter. Could it be something with postgres?

**Comment by nordcart** [comment]
I have Required value to be set unselected. It is still required.


![image](https://user-images.githubusercontent.com/12813484/134624929-7ac1a021-f1d9-40ce-bbc9-3dbee2119f15.png)

-----

![image](https://user-images.githubusercontent.com/12813484/134624863-e105b727-9835-4bb8-bb06-01e5215c3a25.png)

**Comment by joselcvarela** [comment]
Hey,
I don't know what I've done, but now I can replicate this issue.
I am making a PR for this.

**Comment by joselcvarela** [comment]
I don't know what I've done but now I can replicate this issue.
I am making a PR ;)
