### ISSUE TITLE
@directus/gatsby-source-graphql Error sourcing images via childImageSharp / GatsbyImage

### ISSUE THREAD

**Issue by TorbenHammes** [directus/directus#8263]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I've tried to use GatsbyImage (gatsby-plugin-image) with the graphql nodes created from your gatsby-source-directus plugin, but every time I get this error message:

```graphql
{
  "errors": [
    {
      "message": "Source GraphQL API: HTTP error 400 Bad Request",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "directus",
        "contact"
      ],
      "extensions": {
        "stack": [
          "Error: Source GraphQL API: HTTP error 400 Bad Request",
          "    at exports.fetchWrapper (/Users/XYZ/website/node_modules/gatsby-source-graphql/fetch.js:11:11)",
          "    at runMicrotasks (<anonymous>)",
          "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
        ]
      }
    }
  ],
  "data": {
    "directus": {
      "contact": null
    }
  },
  "extensions": {}
}
```

I'm. not sure if this plugin is ready for rc94 or the childImageSharp nodes, but I'm wondering why it's shown that they are available? Is this related to permissions? If yes: What can I do?

Greetings from Berlin!
Torben

### To Reproduce

I use Gatsby 3.11.0 and "@directus/gatsby-source-directus": "^9.0.0-rc.94",
Actually I'm working on a MacBook Pro in development.

### What version of Directus are you using?

9.0.0-rc.94

### What version of Node.js are you using?

14

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

VM with Ubuntu 20.x.x with pm2

**Comment by rijkvanzanten** [comment]
> Is this related to permissions?

Could very well be! What user are you using in the graphql plugin? Does that user have permissions to files?

**Comment by TorbenHammes** [comment]
I've created a user with read permissions to all content collections and the directus_files collection. Other system collections can't get accessed by this user. 
In the plugin, I'm using the user token. I also tried to use it without a token and changed all collections to public readable.

**Comment by JakubOlejnik1155** [comment]
I had the same issue. Even wich directus on localhost. Unfortuanetely i have no fix for that

**Comment by rijkvanzanten** [comment]
@JakubOlejnik1155 we'll take a good hard look at gatsby later today / early next week. Seems like some dependencies started causing conflicts that need to be resolved in the package itself

**Comment by joselcvarela** [comment]
Hello @TorbenHammes , @JakubOlejnik1155 
While fixing other issues about the Gatsby plugin I also experienced this issue.
The trick here is to request `id` under the `DirectusData_directus_files` type.

I have add this note to the documentation on the PR attached.
I would love if we could request the `id` automatically, but I think that's not feasible.
