### ISSUE TITLE
Multiple issues in data model edit view

### ISSUE THREAD

**Issue by paescuj** [directus/directus#8314]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

There are a few issues in the data model edit view (`admin/settings/data-model/<collection>`) under "Collection Setup":
* Only for system collections: Labels in the display template field can be removed by clicking on them while it's not possible to add them anymore since the field is actually read-only.
* Only for system collections: Value of "Note" field is not translated
* Wrong placeholder in "Color" field (same as in "Note" field)
* Value "Treat as single object" is not translated (when switching to another language)

#### Collection Setup of `directus_users`
![Screenshot 2021-09-25 at 17-53-48 Directus Users](https://user-images.githubusercontent.com/5363448/134777907-41a71dcb-6e33-4c4f-8d2b-609ad7581a76.png)

#### Removed labels
![Screenshot 2021-09-25 at 14-05-44 Directus Files](https://user-images.githubusercontent.com/5363448/134770946-7c872487-ddf7-4e34-9405-5a57ee0bdc22.png)

### To Reproduce

1. Go to Settings -> Data Model -> Open a system collection
2. Scroll down to "Collection Setup"
3. See issues

### What version of Directus are you using?

v9.0.0-rc.94

### What version of Node.js are you using?

Docker Image

### What database are you using?

Postgres 13

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by paescuj** [comment]
Was trying to solve those issues by myself but turns out I'm just too unfamiliar with the "app" code-base. Happy to try it again if someone could lead me into the right direction...

**Comment by rijkvanzanten** [comment]
> Was trying to solve those issues by myself but turns out I'm just too unfamiliar with the "app" code-base. Happy to try it again if someone could lead me into the right direction...

There's a system-data folder in the api codebase that holds this data
