### ISSUE TITLE
Cannot users_invite_accept (or any other "global" mutation)

### ISSUE THREAD

**Issue by SeanDylanGoff** [directus/directus#8319]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I cannot accept an invite over GraphQL - probably permissions related.

### To Reproduce

Directus started using: `docker run -p 8055:8055 -e KEY=asdfghjkl -e SECRET=asdfghjkl -e CORS_CREDENTIALS=true -e CORS_ORIGIN=true directus/directus:9.0.0-rc.94`

```
mutation($token: String, $password: String) {
	users_invite_accept(token: $token, password: $password)
}
```

fails with `Schema is not configured for mutations.`

Listing mutations with Altair gives an empty response, while users_invite_accept and a few others should be publicly visible by default.

### What version of Directus are you using?

rc.94

### What version of Node.js are you using?

-

### What database are you using?

SQLite, MariaDB

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
Are you using the /graphql/system endpoint?

**Comment by SeanDylanGoff** [comment]
> Are you using the /graphql/system endpoint?

Nope, that was it. Thanks! Not the first time either 🤭

**Comment by rijkvanzanten** [comment]
Cc @alesvaupotic we should mark that more obvious in the docs somewhere 🧐
