### ISSUE TITLE
Status field options not translated

### ISSUE THREAD

**Issue by supermx1** [directus/directus#8323]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I didn't know what to title this bug. Anyway, I bootstrapped an ENV file to quickly set up Directus, then I created a collection and check some default fields like "Status". Going to edit the status field I found this.

![Screen Shot 2021-09-25 at 10 53 57 PM](https://user-images.githubusercontent.com/9326922/134786870-fbeee2a7-9f09-42be-89e5-f47ad0993450.jpg)

I am guessing there is an error somewhere. Might be a small issue. Just thought to mention

### To Reproduce

As above

### What version of Directus are you using?

RC.94

### What version of Node.js are you using?

14.15.3

### What database are you using?

10.4.17-MariaDB - Source distribution

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
This will be fixed by #8104
