### ISSUE TITLE
Rename "Collections" Module to "Content"

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#8358]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

For someone less familiar with Directus and our terms, the "Collections" module, doesn't mean much. Changing this to "Content" is clear that you are editing the content of the database... and has overlap with Content Management Systems, which is a very common Directus use-case.

We should update the module name, file names, App routes, docs, and anything that saves these routes (bookmarks?)

### To Reproduce

Go to app, hover over first module... navigate to it!

### What version of Directus are you using?

RC-94

### What version of Node.js are you using?

Node: 16.6.1

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

DO

**Comment by rijkvanzanten** [comment]
One thing to keep in mind when implementing this: We might have to migrate / handle the case where people have the /collections route in the "last page" field under users

**Comment by benhaynes** [comment]
Yup! Or catch that with a graceful fallback if that route doesn't exist (I guess that's just a 404 re-route?)

**Comment by rijkvanzanten** [comment]
Yeah, it'll open a 404 on first open, and then work as expected from that point onwards. Might not really warrant a full migration

**Comment by benhaynes** [comment]
Any custom links to this section, really. Not sure if a redirect is worth the added code though. 🤔

**Comment by rijkvanzanten** [comment]
> Any custom links to this section, really. Not sure if a redirect is worth the added code though. 🤔

I'd advice against that. That's the sort of backwards compatible glue code that will introduce quite a bit of tech debt

**Comment by benhaynes** [comment]
Ref: https://github.com/directus/directus/discussions/8435

**Comment by azrikahar** [comment]
Implemented in #9441
