### ISSUE TITLE
Project logo disapears after every update

### ISSUE THREAD

**Issue by nordcart** [directus/directus#8366]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Everytime updating via CMD (docker-compose pull), logo must be uploaded again

![image](https://user-images.githubusercontent.com/12813484/135026669-e786bc31-4683-478c-87ee-423004c182a9.png)

### To Reproduce

Update Directus to latest version via docker-compose pull

### What version of Directus are you using?

v9.0.0-rc.95

### What version of Node.js are you using?

Dont know

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by joselcvarela** [comment]
Hello @nordcart,
This only happens when you do `docker-compose pull`?
I don't know if that's the case, but it seems you have not mounted a volume for uploads.
Can you share your docker-compose?

**Comment by nordcart** [comment]
version: '3'
services:
  database:
    container_name: database
    image: postgres:12
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: '*******'
      POSTGRES_PASSWORD: '*****'
      POSTGRES_DB: 'directus'

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:9.0.0-rc.95
    ports:
      - 8055:8055
 
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: '***************'
      SECRET: '***************'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: '********'
      DB_PASSWORD: '***********'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: '************'
      ADMIN_PASSWORD: '************'

networks:
  directus:

**Comment by azrikahar** [comment]
@nordcart You'll need to persist the `uploads` directory for directus similar to how you persist your database. Here's how it's mentioned in the docs:

![image](https://user-images.githubusercontent.com/42867097/135037316-d6ad7f8e-3dc7-4b90-b668-e1273aa3638a.png)

Link: https://docs.directus.io/guides/installation/docker/#docker-compose

**Comment by nordcart** [comment]
> @nordcart You'll need to persist the `/directus/uploads` directory for directus container similar to how you persist your database. Here's how it's mentioned in the docs:
> 
> ![image](https://user-images.githubusercontent.com/42867097/135037316-d6ad7f8e-3dc7-4b90-b668-e1273aa3638a.png)
> 
> Link: https://docs.directus.io/guides/installation/docker/#docker-compose

I can´t just add 
volumes:
- ./uploads:/directus/uploads 

and then run docker-compose up in cmd? It just results in error for that line.

**Comment by azrikahar** [comment]
Can you share the specific error shown? that'll be very helpful as we're basically in the dark here 😅

**Comment by nordcart** [comment]
volumes:
./uploads:/directus/uploads


![compose](https://user-images.githubusercontent.com/12813484/135072645-c591cb9f-67e9-49fa-a2f7-e9714594a665.png)

**Comment by azrikahar** [comment]
and what does line 30, column 13 entails? I believe your docker-compose.yml is not formatted properly.

in case you really did put this (I can't be sure are you pasting the wrong formatting here on GitHub or that's exactly what you're using):
```
volumes:
./uploads:/directus/uploads
```

then please do follow the docs I linked to you and do the following (the dash is important, as well as the indentation):
```yaml
volumes:
    - ./uploads/directus/uploads
```

You can also refer how you are currently writing the volumes section for your database service.
