### ISSUE TITLE
Broken migrations on rc.95 for [Azure SQL database] 

### ISSUE THREAD

**Issue by jahead** [directus/directus#8368]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Can't run bootstrap on fresh MSSQL Azure SQL Database due to migration "Applying Add Auth Provider..." failing. 

``` bash
❯ npx directus bootstrap
15:47:33 ✨ Initializing bootstrap...
15:47:34 ✨ Installing Directus system tables...
15:47:35 ✨ Running migrations...
15:47:35 ✨ Applying Remove Collection Foreign Keys...
15:47:35 ✨ Applying Remove System Relations...
15:47:35 ✨ Applying Remove System Collections...
15:47:35 ✨ Applying Remove System Fields...
15:47:35 ✨ Applying Add Cascade System Relations...
15:47:36 ✨ Applying Change Webhook URL Type...
15:47:36 ✨ Applying Add Relations Sort Field...
15:47:36 ✨ Applying Remove Locked Fields...
15:47:37 ✨ Applying Webhooks Collections Text...
15:47:37 ✨ Applying Add Refresh Interval...
15:47:37 ✨ Applying Make Filesize Nullable...
15:47:38 ✨ Applying Add Collections Accountability...
15:47:38 ✨ Applying Remove Files Interface...
15:47:38 ✨ Applying Rename Interfaces...
15:47:39 ✨ Applying Restructure Relations...
15:47:41 ✨ Applying Add Foreign Key Constraints...
15:47:41 ✨ Applying Add System Fk Triggers...
15:47:42 ✨ Applying Add Collections Icon Color...
15:47:42 ✨ Applying Add Insights...
15:47:42 ✨ Applying Add Deep Clone Config...
15:47:42 ✨ Applying Change Filesize Bigint...
15:47:42 ✨ Applying Add Conditions to Fields...
15:47:42 ✨ Applying Add Default Folder...
15:47:42 ✨ Applying Replace Groups...
15:47:42 ✨ Applying Add Required to Fields...
15:47:42 ✨ Applying Update Groups...
15:47:42 ✨ Applying Change Image Metadata Structure...
15:47:42 ✨ Applying Add Geometry Config...
15:47:42 ✨ Applying Remove Limit Column...
15:47:43 ✨ Applying Add Auth Provider...
RequestError: ALTER TABLE [directus_users] ALTER COLUMN [email] nvarchar(128) null - ALTER TABLE ALTER COLUMN email failed because one or more objects access this column.
    at Parser.<anonymous> (/mnt/c/Users/JoshuaHead/projects/modus-connect/repositories/mc-pharmacy-api/node_modules/tedious/lib/connection.js:1183:27)
    at Parser.emit (node:events:369:20)
    at Readable.<anonymous> (/mnt/c/Users/JoshuaHead/projects/modus-connect/repositories/mc-pharmacy-api/node_modules/tedious/lib/token/token-stream-parser.js:27:14)
    at Readable.emit (node:events:369:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Readable.push (node:internal/streams/readable:227:10)
    at next (node:internal/streams/from:98:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  code: 'EREQUEST',
  number: 4922,
  state: 9,
  class: 16,
  serverName: 'mc-pharmacy-dbs-dev-aue-nonprod',
  procName: '',
  lineNumber: 1
}
```

I think it's related to #6942 
api/src/database/migrations/20210903A-add-auth-provider.ts 
``` ts
export async function up(knex: Knex): Promise<void> {
	await knex.schema.alterTable('directus_users', (table) => {
		table.string('provider', 128).notNullable().defaultTo('default');
		table.string('external_identifier').unique();

		table.string('email', 128).nullable().alter();
	});
```

rc94 works perfectly.

### To Reproduce

1. Fresh Azure SQL database 
2. Fresh directus project@9.0.0.rc95
3. npx directus bootstrap

### What version of Directus are you using?

9.0.0.rc.95

### What version of Node.js are you using?

v15.14.0

### What database are you using?

Azure SQL Database

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### How are you deploying Directus?

locally

**Comment by aidenfoxx** [comment]
Ugh... At least Oracle isn't the only fussy provider. I wonder if this is a case where the new Knex `setNullable` method is required. 

@jahead Would you be willing to test a fix for me since I don't have access to an MSSQL DB atm.

- Open the `node_modules/directus/dist/database/migrations/20210903A-add-auth-provider.js` file in an editor
- Alter line 8 from:
```
table.string('email', 128).nullable().alter();
```
To:
```
table.setNullable('email');
```
- Re-run the migration to see if it worked

**Comment by jahead** [comment]
So, bad news, 
changing to
```
table.setNullable('email');
```
did not work on either r94 to r95 nor a fresh database. 
and the terminal crashed so I need to reproduce the test for a crash report. but it was complaining because the email column was already there. I'll edit the response in a sec

Getting rid of the line altogether makes all the migration pass but I suspect that's not a good thing? :D

**Comment by jahead** [comment]
@aidenfoxx 
I deleted my previous message because I believed it to be invalid. 
but it's still a no go.
``` bash
RequestError: alter table [directus_users] alter column  [email] nvarchar(128) null  - ALTER TABLE ALTER COLUMN email failed because one or more objects access this column.
    at Parser.<anonymous> (/mnt/c/Users/JoshuaHead/projects/modus-connect/repositories/mc-pharmacy-api/node_modules/tedious/lib/connection.js:1183:27)
    at Parser.emit (node:events:369:20)
    at Readable.<anonymous> (/mnt/c/Users/JoshuaHead/projects/modus-connect/repositories/mc-pharmacy-api/node_modules/tedious/lib/token/token-stream-parser.js:27:14)
    at Readable.emit (node:events:369:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Readable.push (node:internal/streams/readable:227:10)
    at next (node:internal/streams/from:98:31)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  code: 'EREQUEST',
  number: 4922,
  state: 9,
  class: 16,
  serverName: 'mc-pharmacy-dbs-dev-aue-nonprod',
  procName: '',
  lineNumber: 1
}
```

``` js
    await knex.schema.alterTable('directus_users', (table) => {
        table.string('provider', 128).notNullable().defaultTo('default');
        table.string('external_identifier').unique();
        table.setNullable('email');
    });
```

**Comment by jahead** [comment]
@aidenfoxx I'm looking into it. Seems you already had to do some work with knex :C, and with setNullable with sqlite, 
I couldn't see the same kind of code with the mssql dialect that you did with the sqlite, but i haven't really looked into it, so don't quote me.

**Comment by hugopvl** [comment]
> Ugh... At least Oracle isn't the only fussy provider. I wonder if this is a case where the new Knex `setNullable` method is required.
> 
> @jahead Would you be willing to test a fix for me since I don't have access to an MSSQL DB atm?
> 
> * Open the `node_modules/directus/dist/database/migrations/20210903A-add-auth-provider.js` file in an editor
> * Alter line 8 from:
> 
> ```
> table.string('email', 128).nullable().alter();
> ```
> 
> To:
> 
> ```
> table.setNullable('email');
> ```
> 
> * Re-run the migration to see if it worked

![image](https://user-images.githubusercontent.com/81326296/135059989-26c864de-93af-4888-bc4e-afa0f029edc8.png)

**Comment by jahead** [comment]
@hugopvl not sure if the logger is being  silly but I'm seeing `table.setnullable` not `table.setNullable` (missing capital N)

**Comment by aidenfoxx** [comment]
@jahead It seems knex used a standard query type for MySQL and MSSQL which generates the same query as a standard alter (which is why the output query from both errors are the same).

I'll look into this more on my lunch break, but I think it's MSSQL being unhappy with changing a constraint column. The fix might be to remove the unique constraint, set the column to nullable, and add the unique constraint back.

**Comment by jahead** [comment]
@aidenfoxx  from my googling, they did a similar thing for the drop column function. 
see https://github.com/knex/knex/issues/2492
and https://github.com/knex/knex/pull/3855 for the resulting PR. 

AFIAK the interesting code 
https://github.com/C0Nd3Mnd/knex/blob/598a56b029cbedf9d566ef49fe2f71e3ed10aa95/lib/dialects/mssql/schema/tablecompiler.js#L75-L89
``` js
      const baseQuery = `
              DECLARE @constraint varchar(100) = (SELECT default_constraints.name
                                                  FROM sys.all_columns
                                                  INNER JOIN sys.tables
                                                    ON all_columns.object_id = tables.object_id
                                                  INNER JOIN sys.schemas
                                                    ON tables.schema_id = schemas.schema_id
                                                  INNER JOIN sys.default_constraints
                                                    ON all_columns.default_object_id = default_constraints.object_id
                                                  WHERE schemas.name = '${schema}'
                                                  AND tables.name = '${this.tableNameRaw}'
                                                  AND all_columns.name = '${column}')

              IF @constraint IS NOT NULL EXEC('ALTER TABLE ${this.tableNameRaw} DROP CONSTRAINT ' + @constraint)`;
      this.pushQuery(baseQuery);
```

But they already have the lexor for dropUnqiue and unique so you could proportionally just chain the queryies without doing any changes to knex. 

My concern was that the email was being using for some database table relationship, so it breaking some foreign key constraint. 

Let me know if you need me to re-run any tests

**Comment by jahead** [comment]
@aidenfoxx 

Hey, good news, this works. 

![image](https://user-images.githubusercontent.com/5070464/135070182-e799f9ec-07a2-4cc1-886e-32e8212deb1a.png)

**Comment by aidenfoxx** [comment]
> 
> 
> @aidenfoxx
> 
> Hey, good news, this works.
> 
> ```js
>     await knex.schema.alterTable('directus_users', (table) => {
>         table.dropUnique('email')
>     });
> 
>     await knex.schema.alterTable('directus_users', (table) => {
>         table.string('provider', 128).notNullable().defaultTo('default');
>         table.string('external_identifier').unique();
>         table.string("email", 128).nullable().alter();
>     });
> 
>     await knex.schema.alterTable('directus_users', (table) => {
>         table.unique('email')
>     });
> 
>     await knex.schema.alterTable('directus_sessions', (table) => {
>         table.json('data');
>     });
> ```
> ```

Thanks, I hate it. 😂 

Sucks that we have to use these workarounds, but good job implementing the fix. We just need to make sure this doesn't break the other DB providers. I'm mostly concerned about how this would affect #8367

**Comment by jahead** [comment]
Is there an option that we only apply these to affected db provides?

Is there any E2E database migration tests? most db providers have a docker image (dunno about oracle) so it should be 'straight forward' to run a migration test for each provider? I wouldn't be able to help with this until the weekend

**Comment by aidenfoxx** [comment]
Yes. We selectively apply Oracle specific fixes in this file https://github.com/directus/directus/blob/main/api/src/database/migrations/20210312A-webhooks-collections-text.ts

**Comment by jahead** [comment]
Want me to do a PR using the same technique? AFIAK only the mssql has  this issue?

**Comment by aidenfoxx** [comment]
Not sure. I'm not 100% sure other providers aren't affected, and unsetting and resetting the unique constraint shouldn't be breaking. So we could probably get away without having to have special rule for MSSQL.

At the same time it might just be easier to have a special MSSQL rule. I'd be interested in what @rijkvanzanten thinks.

**Comment by hugopvl** [comment]
to clarify, did we replace the code in the image above (which is selected) with the new code?

![image](https://user-images.githubusercontent.com/81326296/135073458-75b5a375-66b9-4aba-a588-f9aea1b1002d.png)

**Comment by aidenfoxx** [comment]
If you want a quick fix you can use @jahead suggestion, but personally I'd stay on rc94 and wait for an official fix if you can. https://github.com/directus/directus/issues/8368#issuecomment-929052096

**Comment by jahead** [comment]
> Not sure. I'm not 100% sure other providers aren't affected, and unsetting and resetting the unique constraint shouldn't be breaking. So we could probably get away without having to have special rule for MSSQL.

I just saw your e2e action that has matrix for each db and I jiggled - #sorry. 

@hugopvl 

I only fixed the up not the down, if you use my quick fix, but don't fix the down, your going to be in a weird state when a fix comes in. Just pin to rc94 and your migrations **should** will work.

**Comment by rijkvanzanten** [comment]
@aidenfoxx @jahead i generally prefer to keep things consistent for each database whenever possible, to prevent unintended branching in the schema between vendors down the line. I believe the example you provided above should work for each vendor @jahead so let's try that first. 

As for the tests, the E2E test should already fire up a copy of MS SQL as well, so well have to check to see why that went through correctly even though the installation should've failed

**Comment by jahead** [comment]
@rijkvanzanten It's a bit late here now, i'm about to head to bed. 
If no one's done a PR  by tomorrow afternoon, I'll do one for you guys :) 

> As for the tests, the E2E test should already fire up a copy of MS SQL as well, so well have to check to see why that went through correctly even though the installation should've failed

AFIAK The E2E only run on main, and have been failing since 14 hours ago on the install deps (which is why i jiggled, it probably would have caught the error) 

see https://github.com/directus/directus/actions/runs/1280320563

A possible suggestion is that you can make actions fire based on a path, so if anyone adds a new migrations it would fire an e2e on the migrations. catch the error on the PR.

But yea sorry, I knew I should have primed a PR encase @rijkvanzanten was happy :D

**Comment by rijkvanzanten** [comment]
> AFIAK The E2E only run on main, and have been failing since 14 hours ago on the install deps (which is why i jiggled, it probably would have caught the error)

The e2e will fail in the short window a new release is being pushed out. This is because the repo already contains the new version number in the various package.json files, but those releases don't exist yet. Due to a bug in NPM workspaces, it'll resolve to NPM first before checking the locally registered workspaces packages (see https://github.com/npm/cli/issues/3637), which causes the tests to fail as long as the new version doesn't exist on npm yet.

> which is why i jiggled, it probably would have caught the error

It wouldn't and it didn't. We check the last e2e test on main before starting the release process 👍🏻

**Comment by rijkvanzanten** [comment]
@jahead some changes had to be made to improve the e2e runner to make sure errors during bootstrap are logged properly. @jaycammarano and I figured that out just now in https://github.com/directus/directus/commit/728a9397e7b6f69f683216283f9a65b46326c931 👍🏻

**Comment by jahead** [comment]
Thanks for the insight (I learned something), and PR!
