### ISSUE TITLE
Divider has margin-top even when first

### ISSUE THREAD

**Issue by dstoyanoff** [directus/directus#8374]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Even though the first field in the collection is a divider, it still has a top margin, which adds a lot of blank space on top. Would be better if the margin top is removed when the first field is a divider.
![image](https://user-images.githubusercontent.com/5079334/135062677-f10076e5-d811-4be7-b4f6-43f495f002e8.png)

### To Reproduce

Create a new collection with a divider as a first field

### What version of Directus are you using?

rc.95

### What version of Node.js are you using?

-

### What database are you using?

-

### What browser are you using?

-

### What operating system are you using?

-

### How are you deploying Directus?

-

**Comment by azrikahar** [comment]
Hi, just to be sure, this happens as you checked the Increase Top Margin option right? Specifically:

![chrome_ksbjSjkNOW](https://user-images.githubusercontent.com/42867097/135063646-14819d42-6305-4117-9e3a-62c2aa302e30.png)

**Comment by azrikahar** [comment]
Nvm seems like it's still there regardless of the Margin Top option. Due to:

https://github.com/directus/directus/blob/51148c11d6496b16a8be29860c6afa3ee4b942ba/app/src/interfaces/presentation-divider/presentation-divider.vue#L43
