### ISSUE TITLE
oAuth - Invalid Credentials

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [directus/directus#8378]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

The last update broke the oAuth login.

On Version: 9.0.0-rc.94 everything works fine. On the latest version it throws an error: ```myappdirectus | 10:40:39 ⚠️  Invalid user credentials. ```

FAQ:
- Yes the user is created
- Yes the user is activated

I can reproduce the problem.

### To Reproduce

Just simply create an own SSO service.
Used docker.

### What version of Directus are you using?

directus/directus:9.0.0-rc.95

### What version of Node.js are you using?

v14.15.4

### What database are you using?

postges

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by NilsBaumgartner1994** [comment]
> Same problem for me. AUTH0 configured correctly but still got the reply "Invalid user credentials" and redirected to "../admin/login?reason=INVALID_USER"
> 
> Attributes are retrieved from AUTH0 but email seems not to be verified. Other apps with similar settings are working fine. Tested also with several scope definitions: "openid email", "array:openid,email" or ["openid","email"]. But no success at all
> 
> Kr Michael

"Fixed" this problem by using version before latest -->     image: directus/directus:9.0.0-rc.94

**Comment by NilsBaumgartner1994** [comment]
But i can confirm, that i also have the problem with "INVALID_USER".

**Comment by mp-itconsulting** [comment]
Also downgraded to rc.94 and it´s working

**Comment by u12206050** [comment]
I have the same issue, but downgrading to rc.94 didn't work either.

**Comment by NilsBaumgartner1994** [comment]
> I have the same issue, but downgrading to rc.94 didn't work either.

be sure to purge docker

**Comment by u12206050** [comment]
Am not using docker, but have removed package-lock.json and node_modules and it still gives me INVALID_USER.
Will try rc.93

**Comment by u12206050** [comment]
Ah nevermind, realized now in my package.json that I need to have `"directus": "9.0.0-rc.94",` and NOT `"^directus": "9.0.0-rc.94",`

**Comment by darioguarascio** [comment]
Same problem here. OAUTH is ok (tested with other software) but directus is giving `INVALID_USER`

**Comment by isaacnass** [comment]
@darioguarascio I struggled with this all morning myself. I have been able to monkeypatch it by adding the following to ` node_modules/directus/dist/services/authentication.js:58`:

```
async login(providerName = constants_1.DEFAULT_AUTH_PROVIDER, payload, otp) {
        payload.email = payload.email || payload.identifier # <--- Added line
        var _a, _b;
        const STALL_TIME = 100;
        const timeStart = perf_hooks_1.performance.now();
```

As far as I can tell there is some sort of change in the way Google Oauth payloads are either returned or parsed. Since the default auth provider is used to parse the auth payload, it gets angry when there isn't an email there
