### ISSUE TITLE
Unable to filter `directus_activity` using `login`

### ISSUE THREAD

**Issue by licitdev** [directus/directus#8393]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

In order to filter for `login` in the Activity Feed, the term required is `authenticate`.

https://user-images.githubusercontent.com/26413686/135119106-8beb4553-01e4-4e47-a827-89dceb8b98b7.mov

Should there be a migration to rename `authenticate` to `login` in existing activities?
It will be consistent alongside #8326 should the `logout` activity be tracked.

### To Reproduce

Head over to Activity feed, set up a filter where action is equals to `login`.
Then change it to `authenticate`.

### What version of Directus are you using?

v9.0.0-rc.95

### What version of Node.js are you using?

v16

### What database are you using?

Postgres

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

PaaS

**Comment by workatease** [comment]
@rijkvanzanten should this too be done as part of #8326

**Comment by workatease** [comment]
Yes I am good with that then I need to wait till your changes are merged... I will wait for it no probs

**Comment by licitdev** [comment]
@workatease Done. Took some time trying to find where to update the colours used in `v-chip`.
