### ISSUE TITLE
Lost data when add exist items in many to many relationship 

### ISSUE THREAD

**Issue by luatdolphin** [directus/directus#8409]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [ ] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

![image](https://user-images.githubusercontent.com/2277080/135203981-e4a4b7ca-b75d-413b-9422-5ad3dc3dbd92.png)
Every time I add an item to this field, all the filled data will be reset. Please help me!!!

### To Reproduce

I am just a newbie

### What version of Directus are you using?

9.0.0-rc95

### What version of Node.js are you using?

14.15.5

### What database are you using?

SQLite

### What browser are you using?

Microsoft Edge

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment]
Unfortunately I can't reproduce this on my end:

![EIjR5qLqu8](https://user-images.githubusercontent.com/42867097/135213304-f45e99cd-80ac-4c11-a1d3-370ba639a350.gif)

Are there any error logs from Directus or console errors in DevTools?

**Comment by luatdolphin** [comment]
No, I didn't get any errors from the console log.
![0ayFBk25So](https://user-images.githubusercontent.com/2277080/135219385-f4afdca1-dfcd-46a9-be19-f71ba3b0723e.gif)

**Comment by rijkvanzanten** [comment]
@azrikahar Were you able to reproduce it? What are the exact reproduction steps? Do we have a database dump / schema file to reproduce this setup to debug locally?

**Comment by azrikahar** [comment]
@rijkvanzanten I noticed the main thing stems from the action that @luatdolphin did in the beginning, which is removing then re-adding m2m item(s). Notice how the UI shows "Creating item" after he re-added, rather than "Editing item", which is the only educated guess I can come up with as I wasn't able to resolve this yesterday. 

### Clearer video to show what I meant:

https://user-images.githubusercontent.com/42867097/135384513-4a757e67-739e-4cab-beb7-7e21b0951059.mp4

### Here are some additional findings:

- Initially when it's an array of ID, it properly open ups as "Editing". but after adding an item, _all_ of them became objects, which causes it to open as "Creating", which I presume is preventing the editing m2m item from working properly:

    https://user-images.githubusercontent.com/42867097/135384574-37a9ba96-6e7c-4a8b-b82b-5eb049b24e53.mp4

- However if we roll back to rc.93, only the "add existing" ones will become an object, while the rest remaining as ID, thus it still works for them (but still not working for newly added existing item):

    https://user-images.githubusercontent.com/42867097/135384803-4a2c99fa-b1f1-417d-80d9-02581c1c4f9d.mp4
    
Later on found out the regression happened here: https://github.com/directus/directus/pull/8051/files#diff-822c24a9309e6d99aeb01d12d51f3bd8e76b2a52ac9d65565a5c765061d18961 (causing everything to turn to objects)

but I believe the implementation before this regression still has the bug, just not as prominent. I believe this means we need to ensure it's all returned as ID for existing one by mapping the junction ID to the relation collection ID? the object syntax should be necessary only for "Add New" items so can't really flat out remove that. But once again unfortunately I am still pretty unsure with how it works so these are mostly guesses on my part.

**Comment by luatdolphin** [comment]
![RaGy18I1HH](https://user-images.githubusercontent.com/2277080/135488012-743d63c8-b542-4904-b9ac-2565b3fd834a.gif)
![xFngPDX6t9](https://user-images.githubusercontent.com/2277080/135489126-4f2f5167-e23f-4ff5-ae36-ababc6771e30.gif)

**Comment by luatdolphin** [comment]
In the first video, the data is lost value 5 in the rating field when I add a new user to the rating field.
In the second video, the data is lost when I delete a field in the data model.

**Comment by joselcvarela** [comment]
This seems very odd.
I can't reproduce this on my end.

@azrikahar what kind o relationship do you have? Also, are you on git `main` HEAD?

@luatdolphin what kind o relationship do you have?
Can you try create a new model, add an O2M or M2M relationship and try if this happens too?

**Comment by luatdolphin** [comment]
@azrikahar I use M2M relationship between posts field and directus_user field. O2M is the same situation

**Comment by azrikahar** [comment]
@joselcvarela yup just tested on main again, with m2m relationship. I believe the issue only happens when we remove then re-add items (must remove then re-add):

https://user-images.githubusercontent.com/42867097/135582600-9f5282a9-83f0-449e-a85f-3b4e2673ee73.mp4

However as the video shows, I could only reproduce it for the first item, not the second item. 🤔

Here's the schema snapshot:

<details>
<summary>snapshot.yaml</summary>

    version: 1
    directus: 9.0.0-rc.95
    collections:
      - collection: books
        meta:
          collection: books
          icon: null
          note: null
          display_template: null
          hidden: false
          singleton: false
          translations: null
          archive_field: null
          archive_app_filter: true
          archive_value: null
          unarchive_value: null
          sort_field: null
          accountability: all
          color: null
          item_duplication_fields: null
        schema:
          name: books
          schema: public
          comment: null
      - collection: books_categories
        meta:
          collection: books_categories
          icon: import_export
          note: null
          display_template: null
          hidden: true
          singleton: false
          translations: null
          archive_field: null
          archive_app_filter: true
          archive_value: null
          unarchive_value: null
          sort_field: null
          accountability: all
          color: null
          item_duplication_fields: null
        schema:
          name: books_categories
          schema: public
          comment: null
      - collection: categories
        meta:
          collection: categories
          icon: null
          note: null
          display_template: null
          hidden: false
          singleton: false
          translations: null
          archive_field: null
          archive_app_filter: true
          archive_value: null
          unarchive_value: null
          sort_field: null
          accountability: all
          color: null
          item_duplication_fields: null
        schema:
          name: categories
          schema: public
          comment: null
    fields:
      - collection: books
        field: id
        type: integer
        schema:
          name: id
          table: books
          data_type: integer
          default_value: nextval('books_id_seq'::regclass)
          generation_expression: null
          max_length: null
          numeric_precision: 32
          numeric_scale: 0
          is_generated: false
          is_nullable: false
          is_unique: true
          is_primary_key: true
          has_auto_increment: true
          comment: null
          schema: public
          foreign_key_schema: null
          foreign_key_table: null
          foreign_key_column: null
        meta:
          collection: books
          field: id
          special: null
          interface: input
          options: null
          display: null
          display_options: null
          readonly: true
          hidden: true
          sort: null
          width: full
          translations: null
          note: null
          conditions: null
          required: false
          group: null
      - collection: books
        field: title
        type: string
        schema:
          name: title
          table: books
          data_type: character varying
          default_value: null
          generation_expression: null
          max_length: 255
          numeric_precision: null
          numeric_scale: null
          is_generated: false
          is_nullable: true
          is_unique: false
          is_primary_key: false
          has_auto_increment: false
          comment: null
          schema: public
          foreign_key_schema: null
          foreign_key_table: null
          foreign_key_column: null
        meta:
          collection: books
          field: title
          special: null
          interface: null
          options: null
          display: null
          display_options: null
          readonly: false
          hidden: false
          sort: null
          width: full
          translations: null
          note: null
          conditions: null
          required: false
          group: null
      - collection: books_categories
        field: id
        type: integer
        schema:
          name: id
          table: books_categories
          data_type: integer
          default_value: nextval('books_categories_id_seq'::regclass)
          generation_expression: null
          max_length: null
          numeric_precision: 32
          numeric_scale: 0
          is_generated: false
          is_nullable: false
          is_unique: true
          is_primary_key: true
          has_auto_increment: true
          comment: null
          schema: public
          foreign_key_schema: null
          foreign_key_table: null
          foreign_key_column: null
        meta:
          collection: books_categories
          field: id
          special: null
          interface: null
          options: null
          display: null
          display_options: null
          readonly: false
          hidden: true
          sort: null
          width: full
          translations: null
          note: null
          conditions: null
          required: false
          group: null
      - collection: books_categories
        field: books_id
        type: integer
        schema:
          name: books_id
          table: books_categories
          data_type: integer
          default_value: null
          generation_expression: null
          max_length: null
          numeric_precision: 32
          numeric_scale: 0
          is_generated: false
          is_nullable: true
          is_unique: false
          is_primary_key: false
          has_auto_increment: false
          comment: null
          schema: public
          foreign_key_schema: public
          foreign_key_table: books
          foreign_key_column: id
        meta:
          collection: books_categories
          field: books_id
          special: null
          interface: null
          options: null
          display: null
          display_options: null
          readonly: false
          hidden: true
          sort: null
          width: full
          translations: null
          note: null
          conditions: null
          required: false
          group: null
      - collection: books_categories
        field: categories_id
        type: integer
        schema:
          name: categories_id
          table: books_categories
          data_type: integer
          default_value: null
          generation_expression: null
          max_length: null
          numeric_precision: 32
          numeric_scale: 0
          is_generated: false
          is_nullable: true
          is_unique: false
          is_primary_key: false
          has_auto_increment: false
          comment: null
          schema: public
          foreign_key_schema: public
          foreign_key_table: categories
          foreign_key_column: id
        meta:
          collection: books_categories
          field: categories_id
          special: null
          interface: null
          options: null
          display: null
          display_options: null
          readonly: false
          hidden: true
          sort: null
          width: full
          translations: null
          note: null
          conditions: null
          required: false
          group: null
      - collection: categories
        field: id
        type: integer
        schema:
          name: id
          table: categories
          data_type: integer
          default_value: nextval('categories_id_seq'::regclass)
          generation_expression: null
          max_length: null
          numeric_precision: 32
          numeric_scale: 0
          is_generated: false
          is_nullable: false
          is_unique: true
          is_primary_key: true
          has_auto_increment: true
          comment: null
          schema: public
          foreign_key_schema: null
          foreign_key_table: null
          foreign_key_column: null
        meta:
          collection: categories
          field: id
          special: null
          interface: input
          options: null
          display: null
          display_options: null
          readonly: true
          hidden: true
          sort: null
          width: full
          translations: null
          note: null
          conditions: null
          required: false
          group: null
      - collection: categories
        field: name
        type: string
        schema:
          name: name
          table: categories
          data_type: character varying
          default_value: null
          generation_expression: null
          max_length: 255
          numeric_precision: null
          numeric_scale: null
          is_generated: false
          is_nullable: true
          is_unique: false
          is_primary_key: false
          has_auto_increment: false
          comment: null
          schema: public
          foreign_key_schema: null
          foreign_key_table: null
          foreign_key_column: null
        meta:
          collection: categories
          field: name
          special: null
          interface: null
          options: null
          display: null
          display_options: null
          readonly: false
          hidden: false
          sort: null
          width: full
          translations: null
          note: null
          conditions: null
          required: false
          group: null
      - collection: categories
        field: description
        type: string
        schema:
          name: description
          table: categories
          data_type: character varying
          default_value: null
          generation_expression: null
          max_length: 255
          numeric_precision: null
          numeric_scale: null
          is_generated: false
          is_nullable: true
          is_unique: false
          is_primary_key: false
          has_auto_increment: false
          comment: null
          schema: public
          foreign_key_schema: null
          foreign_key_table: null
          foreign_key_column: null
        meta:
          collection: categories
          field: description
          special: null
          interface: null
          options: null
          display: null
          display_options: null
          readonly: false
          hidden: false
          sort: null
          width: full
          translations: null
          note: null
          conditions: null
          required: false
          group: null
      - collection: books
        field: related_categories
        type: m2m
        schema: null
        meta:
          collection: books
          field: related_categories
          special:
            - m2m
          interface: list-m2m
          options: null
          display: null
          display_options: null
          readonly: false
          hidden: false
          sort: null
          width: full
          translations: null
          note: null
          conditions: null
          required: false
          group: null
    relations:
      - collection: books_categories
        field: categories_id
        related_collection: categories
        schema:
          table: books_categories
          column: categories_id
          foreign_key_table: categories
          foreign_key_column: id
          foreign_key_schema: public
          constraint_name: books_categories_categories_id_foreign
          on_update: NO ACTION
          on_delete: SET NULL
        meta:
          many_collection: books_categories
          many_field: categories_id
          one_collection: categories
          one_field: null
          one_collection_field: null
          one_allowed_collections: null
          junction_field: books_id
          sort_field: null
          one_deselect_action: nullify
      - collection: books_categories
        field: books_id
        related_collection: books
        schema:
          table: books_categories
          column: books_id
          foreign_key_table: books
          foreign_key_column: id
          foreign_key_schema: public
          constraint_name: books_categories_books_id_foreign
          on_update: NO ACTION
          on_delete: SET NULL
        meta:
          many_collection: books_categories
          many_field: books_id
          one_collection: books
          one_field: related_categories
          one_collection_field: null
          one_allowed_collections: null
          junction_field: categories_id
          sort_field: null
          one_deselect_action: nullify
</details>
