### ISSUE TITLE
M2M and M2A reloads on every key press

### ISSUE THREAD

**Issue by nazariydj** [directus/directus#8417]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

After some change made to M2M field it items reloads on every key press on different fields.

https://user-images.githubusercontent.com/17914536/135244980-ff725db2-082b-4679-88c6-81ca5f9f4394.mp4

### To Reproduce

1. edit some item with m2m and other fields
2. make any changes to m2m (add, remove or edit some item)
3. click on other field (text) and press some keys

On every key press m2m items reloads and app makes about 2 request / key. I think it's non intended behavior.

PS: thank you guys for the excellent work you are doing and new features you are introducing.

### What version of Directus are you using?

9.0.0-rc.95

### What version of Node.js are you using?

16.9.1

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by nazariydj** [comment]
same behavior with m2a field

**Comment by rijkvanzanten** [comment]
Very similar to https://github.com/directus/directus/issues/7610. I'm assuming the change applied here should fix it for m2m/m2a as well: https://github.com/directus/directus/pull/7631/files#diff-fda8466b5a0ceaaab1d9164198b2994b0a1afd9e9dc19c2ad05231f10f510cc3R302
