### ISSUE TITLE
Firefox SSO results in 404

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [directus/directus#8420]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

As i am implementing an sso service it works quite well on chrome but in firefox will result in an 404 error.

### To Reproduce

Simply add an SSO service an login via firefox

These are my docker env. variables

```
REFRESH_TOKEN_COOKIE_SAME_SITE:  "lax"
CORS_ALLOWED_HEADERS: 'Accept,Accept-Encoding,Accept-Language,Access-Control-Request-Headers,Access-Control-Request-Method,Cache-Control,Connection,Host,Origin,Pragma,Referer,Sec-Fetch-Mode,User-Agent'```
```

### What version of Directus are you using?

directus/directus:9.0.0-rc.95

### What version of Node.js are you using?

v14.15.4

### What database are you using?

postges

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
When do you see the 404? What external service?

**Comment by NilsBaumgartner1994** [comment]
> When do you see the 404? What external service?

I just added an for chrome working SSO service. It is an by Grant defined custom external service. Since it works on chrome like a charm but not on firefox i think that this is a problem. I have a working (well failing) project if you want to test it.

**Comment by azrikahar** [comment]
Granted I have very limited experience with Firefox, is there a possibility that the Containers feature in Firefox is causing the issue?

**Comment by NilsBaumgartner1994** [comment]
> Granted I have very limited experience with Firefox, is there a possibility that the Containers feature in Firefox is causing the issue?

I hope so, but the SSO container successfully redirects me to directus, but then directus tells me there is no such session

**Comment by azrikahar** [comment]
This might be a lil far fetched, but would you mind checking the `network.http.sendRefererHeader` configuration for your Firefox browser and let us know what value is it set as? Reference: https://wiki.mozilla.org/Security/Referrer (first item in the list)

**Comment by NilsBaumgartner1994** [comment]
Okay i found out, that the problem only occurs, when using my network IP instead of a domain. I am not using localhost, 127.0.0.1 but instead: 

Firefox: does not work
Chrome: works
```
      OAUTH_STUDIP_PROFILE_URL: 'http://192.168.178.35/studip/api/getProfile'
      OAUTH_STUDIP_AUTHORIZE_URL: "http://192.168.178.35/studip/app/login"
      OAUTH_STUDIP_ACCESS_URL: "http://192.168.178.35/studip/api/verifytoken"
```


Firefox: works
Chrome: works
```
      OAUTH_STUDIP_PROFILE_URL: 'http://se-services.informatik.uos.de/studip/api/getProfile'
      OAUTH_STUDIP_AUTHORIZE_URL: "http://se-services.informatik.uos.de/studip/app/login"
      OAUTH_STUDIP_ACCESS_URL: "http://se-services.informatik.uos.de/studip/api/verifytoken"
```

**Comment by NilsBaumgartner1994** [comment]
> This might be a lil far fetched, but would you mind checking the `network.http.sendRefererHeader` configuration for your Firefox browser and let us know what value is it set as? Reference: https://wiki.mozilla.org/Security/Referrer (first item in the list)

Value is 2

**Comment by azrikahar** [comment]
> Okay i found out, that the problem only occurs, when using my network IP instead of a domain. I am not using localhost, 127.0.0.1 but instead:
> 
> Firefox: does not work Chrome: works
> 
> ```
>       OAUTH_STUDIP_PROFILE_URL: 'http://192.168.178.35/studip/api/getProfile'
>       OAUTH_STUDIP_AUTHORIZE_URL: "http://192.168.178.35/studip/app/login"
>       OAUTH_STUDIP_ACCESS_URL: "http://192.168.178.35/studip/api/verifytoken"
> ```
> 
> Firefox: works Chrome: works
> 
> ```
>       OAUTH_STUDIP_PROFILE_URL: 'http://se-services.informatik.uos.de/studip/api/getProfile'
>       OAUTH_STUDIP_AUTHORIZE_URL: "http://se-services.informatik.uos.de/studip/app/login"
>       OAUTH_STUDIP_ACCESS_URL: "http://se-services.informatik.uos.de/studip/api/verifytoken"
> ```

Hmm that's a great discovery. Is there any CORS related issues shown in the DevTools?

> Value is 2

Thank you for checking it out. Seems like that it won't be the cause here (some users reported had it at 0).

**Comment by NilsBaumgartner1994** [comment]
Yeah i read that also but none of this seemed to bring up the problem. Please keep me informed since i think it is for the development a critical problem but not for production.
Maybe it is related to firefox. By the way, the same error happend when using Safari.

**Comment by aidenfoxx** [comment]
The browser cookie shouldn't affect the flow, Same-Site, Secure or otherwise? The oauth provider doesn't require a cookie, and the session cookie should still exist when the user redirects back (assuming it's the same domain).

The new auth flow will still require a cookie, though not a session cookie.

**Comment by rijkvanzanten** [comment]
@aidenfoxx I believe the problem might be that grant uses a cookie that firefox might no longer allow by default on localhost (i believe they started requiring things like same-site=strict or secure=true, not sure on that).

If the browser doesn't allow the cookie to be set, the oauth callback will fail as it's no longer able to retrieve what the "open" session was 🤔

**Comment by aidenfoxx** [comment]
Cookies work in Firefox from localhost, I can assure you that. I use Firefox as my primary browser and haven't had issues with Directus.

**Comment by NilsBaumgartner1994** [comment]
> @aidenfoxx I believe the problem might be that grant uses a cookie that firefox might no longer allow by default on localhost (i believe they started requiring things like same-site=strict or secure=true, not sure on that).
> 
> If the browser doesn't allow the cookie to be set, the oauth callback will fail as it's no longer able to retrieve what the "open" session was 🤔

Well i wasn't testing on localhost directly. Since Nginx wont route well when using 127.0.0.1 or localhost, i had to use the ip of my computer in my network.

**Comment by aidenfoxx** [comment]
To me it feels like a domain name resolution issue. Do both the URLs respond the same when when you access them directly @NilsBaumgartner1994?

http://192.168.178.35/studip/api/getProfile vs http://se-services.informatik.uos.de/studip/api/getProfile for example?

**Comment by NilsBaumgartner1994** [comment]
> To me it feels like a domain name resolution issue. Do both the URLs respond the same when when you access them directly @NilsBaumgartner1994?
> 
> http://192.168.178.35/studip/api/getProfile vs http://se-services.informatik.uos.de/studip/api/getProfile for example?

Yes and since it works well on chrome, it drives me crazy that firefox somehow handles it differently.
I can offer you the project with that specific problem.

**Comment by aidenfoxx** [comment]
You can send it, but I can't promise I'll get a chance to look at it.

Just to be clear, the 404 happens when you redirect to the OAuth verification page? It's the verification page showing a 404, and not Directus?

**Comment by NilsBaumgartner1994** [comment]
> You can send it, but I can't promise I'll get a chance to look at it.
> 
> Just to be clear, the 404 happens when you redirect to the OAuth verification page? It's the verification page showing a 404, and not Directus?

It's nginx-proxy which show it, because directus (grant) says, he cant find any oauth providers.

**Comment by aidenfoxx** [comment]
I wonder if this has anything to do with it https://github.com/simov/grant/issues/144 🤔 

Otherwise I'm stumped.

**Comment by rijkvanzanten** [comment]
> Well i wasn't testing on localhost directly. Since Nginx wont route well when using 127.0.0.1 or localhost, i had to use the ip of my computer in my network.

Oh that changes things.. That's a bit of crucial information that certainly isn't covered in the "Simply add an SSO service an login via firefox" reproduction step.

> It's nginx-proxy which show it, because directus (grant) says, he cant find any oauth providers.

Wait now I'm confused. It's Directus that throws a 404 on `/auth/oauth/:provider` ? Or does this problem show up on the redirect back from the provider?

**Comment by NilsBaumgartner1994** [comment]
> > Well i wasn't testing on localhost directly. Since Nginx wont route well when using 127.0.0.1 or localhost, i had to use the ip of my computer in my network.
> 
> Oh that changes things.. That's a bit of crucial information that certainly isn't covered in the "Simply add an SSO service an login via firefox" reproduction step.
> 
> > It's nginx-proxy which show it, because directus (grant) says, he cant find any oauth providers.
> 
> Wait now I'm confused. It's Directus that throws a 404 on `/auth/oauth/:provider` ? Or does this problem show up on the redirect back from the provider?

I will upload the project and show it. Makes things more clearer.

**Comment by aidenfoxx** [comment]
> Wait now I'm confused. It's Directus that throws a 404 on `/auth/oauth/:provider` ? Or does this problem show up on the redirect back from the provider?

It sounds to me like Directus is failing to retrieve the user info from the oauth grant URL with a 404, which seems consistent with the issues in the ticket I linked.

**Comment by NilsBaumgartner1994** [comment]
> > Wait now I'm confused. It's Directus that throws a 404 on `/auth/oauth/:provider` ? Or does this problem show up on the redirect back from the provider?
> 
> It sounds to me like Directus is failing to retrieve the user info from the oauth grant URL with a 404, which seems consistent with the issues in the ticket I linked.

yeah, but why with only firefox and not with chrome (caching is disabled on both)

**Comment by rijkvanzanten** [comment]
I'm wondering if the fact that you're using nginx-proxy with an IP address instead of "pure" localhost causes Firefox's (/Safari's) more strict cross-site cookie prevention to kick in (https://support.mozilla.org/en-US/kb/third-party-cookies-firefox-tracking-protection). Just to confirm/rule that out, would you mind disabling that protection to test if it works then?

**Comment by NilsBaumgartner1994** [comment]
> I'm wondering if the fact that you're using nginx-proxy with an IP address instead of "pure" localhost causes Firefox's (/Safari's) more strict cross-site cookie prevention to kick in (https://support.mozilla.org/en-US/kb/third-party-cookies-firefox-tracking-protection). Just to confirm/rule that out, would you mind disabling that protection to test if it works then?

I will first upload the project, so that everyone can make their own picture of it

**Comment by NilsBaumgartner1994** [comment]
Okay i am back and uploaded it. I have to say that i am sorry for my bad Dockerfiles.
https://github.com/NilsBaumgartner1994/DirectusFirefoxProblem

If someone does not have that much time, here are some screenshots of the problem, side by side with Chrome and Firefox (left Firefox, right Chrome)
https://github.com/NilsBaumgartner1994/DirectusFirefoxProblem/tree/main/Screenshots

**Comment by rijkvanzanten** [comment]
@NilsBaumgartner1994 could you try my suggestion above? (https://github.com/directus/directus/issues/8420#issuecomment-932339792)

**Comment by aidenfoxx** [comment]
@rijkvanzanten Seems to be a Firefox issue with SameSite in localhost, I set up a test case on my machine and Firefox isn't sending cookies to localhost when they have SameSite="strict" set on them. Chrome works correctly.

**Comment by rijkvanzanten** [comment]
> If that's the case, it's strange that it doesn't inherit the session settings set by Directus. 🤷

That part makes sense, as Directus sets those flags explicitly when _we_ make a session cookie, however Grant does it under the hood in it's own magic

**Comment by NilsBaumgartner1994** [comment]
Well, it wonders me, that this problem had no other yet. I mean even if we set SameSite to "lax" this still occurs.

**Comment by aidenfoxx** [comment]
The issue seems to be this: https://bugzilla.mozilla.org/show_bug.cgi?id=1465402

From testing it's only the redirect that doesn't send the cookie. If I refresh the page after it's redirected I can see the cookie is being sent.

**Comment by aidenfoxx** [comment]
@rijkvanzanten Disabling tracking protections doesn't fix it either.

**Comment by aidenfoxx** [comment]
@NilsBaumgartner1994 Looking at this test case someone made, Lax should work. Or at least it does for me: https://cookie-lab-app.vercel.app/

**Comment by NilsBaumgartner1994** [comment]
> @NilsBaumgartner1994 Looking at this test case someone made, Lax should work. Or at least it does for me: https://cookie-lab-app.vercel.app/

I see, but the error still exists, even with using "lax":

https://se-services.informatik.uos.de/raiders/api/admin/login
You can try it with the "log in with Studiptest" Button at the botttom.

Works in Chrome, fails in Firefox

**Comment by NilsBaumgartner1994** [comment]
@rijkvanzanten the bug still exists i fear.

**Comment by aidenfoxx** [comment]
Did you try with the new oauth flow @NilsBaumgartner1994? I'm a Firefox user and I've had no issues with the 4 or so different providers I've tried

**Comment by NilsBaumgartner1994** [comment]
> Did you try with the new oauth flow @NilsBaumgartner1994? I'm a Firefox user and I've had no issues with the 4 or so different providers I've tried

Please try "Studiptest" on this example application: https://se-services.informatik.uos.de/raiders/api/admin/login
Once with Firefox and Once with chrome.

**Comment by aidenfoxx** [comment]
That site is using the old Oauth flow. Try using the new one

**Comment by NilsBaumgartner1994** [comment]
Was it mentioned, that the old oauth flow is no longer supported from firefox ?

**Comment by rijkvanzanten** [comment]
@NilsBaumgartner1994 The oauth flow was re-envisioned using different state management between the various requests that have to be made in order to authorize with the third party auth provider, this should also resolve the cookie issue in Firefox mentioned in the OP 👍🏻 

This was released in rc.99 and mentioned in the release notes here: https://github.com/directus/directus/releases/tag/v9.0.0-rc.99

**Comment by NilsBaumgartner1994** [comment]
thanks
