### ISSUE TITLE
`auth.login.before` hook fires too late

### ISSUE THREAD

**Issue by dschaefer7** [directus/directus#8440]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

it works only when user-email already exist in directus, otherwise this hook will be not execute.

### To Reproduce

```js
module.exports = function registerHook() {
return {
   'auth.login.before': async function ({payload}) {
      console.log('payload-->', payload);
      return payload;
    }
  }
}
```

### What version of Directus are you using?

95

### What version of Node.js are you using?

14

### What database are you using?

mariadb

### What browser are you using?

chrome

### What operating system are you using?

mac big sur

### How are you deploying Directus?

docker

**Comment by NilsBaumgartner1994** [comment]
Update to the new version and check then

**Comment by rijkvanzanten** [comment]
Good point @NilsBaumgartner1994

@dschaefer7 The authentication flow was revised quite drastically in #6942, with the hooks flow updated in #8027. I believe this was resolved in those two PRs 👍🏻 We can reopen if not!

**Comment by dschaefer7** [comment]
@NilsBaumgartner1994 @rijkvanzanten 
v.9.0.0
I have rewrite with new syntax:
 filter('auth.login', async (req) => {}
it's the same behavior, unfortunately
