### ISSUE TITLE
M2A drawer slower after update

### ISSUE THREAD

**Issue by nordcart** [directus/directus#8442]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Updating from 93 to 94 selecting an item from the drawer got slower. (now on 95 and still slow)

### To Reproduce

1. Create a new item for a collection
2. Select immediately an existing m2a item from the drawer (nothing happens).
3. Wait 2-3sec.
4. Select the existing m2a item again from the drawer. (It can now be selected)

![image](https://user-images.githubusercontent.com/12813484/135400107-38d5b3a9-7bbe-4975-9754-ac2870792258.png)

### What version of Directus are you using?

v9.0.0-rc.95

### What version of Node.js are you using?

Don´t know

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Hi, just have some additional questions to help us reliably reproduce on our end:

- What was the estimated time taken before it became 2-3 secs?
- Was there any substantial records being added on your end before you upgrade from rc.93 to rc.94/95? 
- Can you provide the schema snapshot of your Directus instance? Docs on how to do this: https://docs.directus.io/reference/command-line-interface/#migrate-schema-to-a-different-environment

**Comment by nordcart** [comment]
- Estimated time before = instant
- No substantial records before the upgrade.
- I will try to make a snapshot when I´m at the office.

The issue is that the checkbox doesn´t respond when instantly choosing an item from the drawer (**clicking outside the box, on the row**). It responds if you wait for a while.

**Comment by rijkvanzanten** [comment]
> The issue is that the checkbox doesn´t respond when instantly choosing an item from the drawer (clicking outside the box, on the row). It responds if you wait for a while.

I've noticed this bit before, though I don't think it's a timing problem per say. If you click the row 3 times quickly it will still toggle. There's some weirdness going on in the click-on-row handler vs the click-on-select-box logic, but that should already be resolved in https://github.com/directus/directus/pull/8010 which we aim to include in the next release 🙂

**Comment by rijkvanzanten** [comment]
This was resolved in https://github.com/directus/directus/pull/8010
