### ISSUE TITLE
Divider with note is overlapping

### ISSUE THREAD

**Issue by dstoyanoff** [directus/directus#8444]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When setting up a divider in a collection and adding a Note for it, the note does not add an offset from the divider itself, making it sticked to the line, which isn't consistent with the rest of the UI.
![image](https://user-images.githubusercontent.com/5079334/135403851-4f51649b-d9ef-42fa-83f4-e8facab2b456.png)

### To Reproduce

Create a presentation field of type Divider and add a note. Go to the collection and observe the result

### What version of Directus are you using?

rc.95

### What version of Node.js are you using?

-

### What database are you using?

-

### What browser are you using?

Chrome

### What operating system are you using?

-

### How are you deploying Directus?

-

**Comment by benhaynes** [comment]
That's correct! The divider was evenly spaced between the fields above and below. These new margins helped keep the divider closer to the section it was labeling... But unfortunately also his making the note too close.

Any ideas? 🤔

**Comment by licitdev** [comment]
@benhaynes Would this be okay? Removed the negative `margin-bottom`.

### Title + Note

<img width="438" alt="Screenshot 2021-09-30 at 10 14 05 PM" src="https://user-images.githubusercontent.com/26413686/135473109-6f840734-cbbd-4252-a488-50778cee5c83.png">

### Title + Note + Increase Margin Top

<img width="438" alt="Screenshot 2021-09-30 at 10 14 12 PM" src="https://user-images.githubusercontent.com/26413686/135473134-a9f13065-fa87-4a9c-aea8-5e8526b54aa3.png">

### Title

<img width="438" alt="Screenshot 2021-09-30 at 10 14 51 PM" src="https://user-images.githubusercontent.com/26413686/135473170-cb8fa543-3f3e-43b0-b0d1-5a00f0419171.png">

### Title + Increase Margin Top

<img width="438" alt="Screenshot 2021-09-30 at 10 15 03 PM" src="https://user-images.githubusercontent.com/26413686/135473189-c4418010-3e92-4b26-a3b3-1de8876954f3.png">

### Note

<img width="438" alt="Screenshot 2021-09-30 at 10 16 55 PM" src="https://user-images.githubusercontent.com/26413686/135473231-e524919a-97a7-440e-868b-d6c573fdd185.png">

### Note + Increase Margin Top

<img width="438" alt="Screenshot 2021-09-30 at 10 17 32 PM" src="https://user-images.githubusercontent.com/26413686/135473269-003033ca-728a-417a-9484-8ab9b751028c.png">

### Empty

<img width="438" alt="Screenshot 2021-09-30 at 10 16 25 PM" src="https://user-images.githubusercontent.com/26413686/135473303-736c7d9b-c1d1-4fa5-95f5-0e7706cfa8ae.png">

### Empty + Increase Margin Top

<img width="438" alt="Screenshot 2021-09-30 at 10 17 57 PM" src="https://user-images.githubusercontent.com/26413686/135473324-29a65554-522c-474f-8b6c-07f3a98492e5.png">

**Comment by benhaynes** [comment]
@licitdev — this is super helpful, thank you!! These options offer good customization, my main concern was that the normal/default state places the divider equally between form sections:

<img width="438" alt="135473109-6f840734-cbbd-4252-a488-50778cee5c83" src="https://user-images.githubusercontent.com/522079/135490199-55681fac-8c3e-451b-9355-e1e9f41026d7.png">

In this example, the divider is the same distance to the green button (above) as to the gray button (below). My design mind wants the divider always closer to the form section it is labeling (the part with the gray button). I know the "Margin Top" adds this, **but I think that should be the default.** @rijkvanzanten ?

Also, I decreased the form-gap-vertical a week ago, and that is helping here.

**Comment by rijkvanzanten** [comment]
Yeah i'm down to change the default value of that margin option to true, or just have it hardcoded enabled at all time (not sure why that needs to be configurable)

**Comment by licitdev** [comment]
> Yeah i'm down to change the default value of that margin option to true, or just have it hardcoded enabled at all time (not sure why that needs to be configurable)

@rijkvanzanten The add top margin defaults to true in my previous in #8379. 
@benhaynes The gap is reduced due to #8374.

**Comment by benhaynes** [comment]
I think the only reason to make the margin-top configurable is in case it's at the top of the form (so it doesn't just push everything down for no reason). If that is resolved somehow, I would love to ditch this option and just hard-code it!

**Comment by rijkvanzanten** [comment]
That should be doable with some css selection magic :

**Comment by licitdev** [comment]
> I think the only reason to make the margin-top configurable is in case it's at the top of the form (so it doesn't just push everything down for no reason). If that is resolved somehow, I would love to ditch this option and just hard-code it!

Yup that margin-top can be toggled now. We only have to remove `margin-bottom: -10px;`.

@benhaynes I would like to ask if you would still like to have the `margin-top: 10px`? 
Here's a sample without it removed.

<img width="442" alt="Screenshot 2021-10-01 at 12 14 24 AM" src="https://user-images.githubusercontent.com/26413686/135492684-811cafbc-f1fa-40a6-a985-53482c826ddc.png">

I had removed it to make it exactly vertically middle for the `Empty` type...
If this is okay, the fix will be simply to remove the entire code block below.

https://github.com/directus/directus/blob/cb7b6a91084d0c71e886a8d0481280ad066a6e63/app/src/interfaces/presentation-divider/presentation-divider.vue#L46-L49

**Comment by rijkvanzanten** [comment]
@licitdev @benhaynes we can't rely on negative margins for things like these, because it will always result in issues when used in a different context (as proven by this issue's existence) 👍🏻

**Comment by licitdev** [comment]
@rijkvanzanten Yup definitely. I just let the existing negative margin remain there as I don't wish to break the uniformity of UI. 😂👍🏻

**Comment by benhaynes** [comment]
OK, cool. So let's hardcode the interface to ALWAYS have the top margin, and remove the option altogether. 👍

**Comment by licitdev** [comment]
@benhaynes Do you mean to remove the `Increase Margin Top` option as shown in below screenshot?

The below screenshot shows the default options, whereby the additional margin top is set to TRUE.

The option to toggle is very helpful particularly if the divider contains no title and is just used as a line separator.
Hence if it is `ALWAYS` having the top margin except when it is the first divider, the divider becomes less flexible in my opinion... 🤔

<img width="617" alt="Screenshot 2021-10-01 at 12 42 43 AM" src="https://user-images.githubusercontent.com/26413686/135496617-e38574ac-ed87-4ef5-a7c1-2fa5fe87fae8.png">

**Comment by benhaynes** [comment]
Hmm, good point. What if we ALWAYS had the top margin when there is a Title, but NEVER have it if there is no title?

Also, not sure if I like the styling of the "Inline Title" option.

**Comment by licitdev** [comment]
> Hmm, good point. What if we ALWAYS had the top margin when there is a Title, but NEVER have it if there is no title?

Yes that should be possible, the divider will also need to have the top margin removed if it happens to be the first field.

I have tried to mess around with the CSS such as :first-child and parent selector etc, but couldn't get it working...
@rijkvanzanten Will require your guidance on css selection magic for scoped CSS. 🤓

**Comment by rijkvanzanten** [comment]
I think we should get rid of the "Margin Top" option completely, in favor of just doing it correctly by default 👍🏻

**Comment by rijkvanzanten** [comment]
> I have tried to mess around with the CSS such as :first-child and parent selector etc, but couldn't get it working...
@rijkvanzanten Will require your guidance on css selection magic for scoped CSS. 🤓

I can pick this up 🙂 Do you wanna prepare a PR and I'll add this in on top of that?

**Comment by licitdev** [comment]
> I think we should get rid of the "Margin Top" option completely, in favor of just doing it correctly by default 👍🏻

Would that mean that users will only have the latter option with a much bigger gap?

### Empty

<img width="438" alt="Screenshot 2021-09-30 at 10 16 25 PM" src="https://user-images.githubusercontent.com/26413686/135473303-736c7d9b-c1d1-4fa5-95f5-0e7706cfa8ae.png">

### Empty + Increase Margin Top

<img width="438" alt="Screenshot 2021-09-30 at 10 17 57 PM" src="https://user-images.githubusercontent.com/26413686/135473324-29a65554-522c-474f-8b6c-07f3a98492e5.png">

**Comment by rijkvanzanten** [comment]
I think that's where Ben's suggestion comes in: Only add the top margin when a Title has been configured 🙂

**Comment by licitdev** [comment]
Ah... Means if without a title, it'll be without the `margin-top`. Crystal clear now.

> I can pick this up 🙂 Do you wanna prepare a PR and I'll add this in on top of that?

Yup, working on it~
