### ISSUE TITLE
"Title of items" and "Title of a person" have the same translation on Crowdin.

### ISSUE THREAD

**Issue by vasia123** [directus/directus#8446]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

https://locales.directus.io/translate/directus/70/en-ru?filter=basic&value=0#q=title - Two different translations are needed here.

### To Reproduce

Now there is no way to translate these two lines separately from each other.

### What version of Directus are you using?

9.0.0-rc.95

### What version of Node.js are you using?

v14.17.1

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally

**Comment by paescuj** [comment]
@benhaynes You might be able to make those fields available for translation by adjusting the settings for "Duplicate Strings": https://support.crowdin.com/advanced-project-setup/#duplicate-strings

**Comment by benhaynes** [comment]
Probably just easier to duplicate and use different keys within Directus, right @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
@benhaynes We do by nesting them. `directus_users.title` isn't the same as `title` and shouldn't be considered the same in crowdin. I've updated the setting @paescuj mentioned which should resolve this issue 👍🏻 

<img width="779" alt="CleanShot 2021-09-30 at 11 53 37@2x" src="https://user-images.githubusercontent.com/9141017/135489442-73d10fdd-f4a1-46e2-bc94-403d9818cf01.png">

**Comment by paescuj** [comment]
Can confirm, it's working now 👍

![Screenshot 2021-09-30 at 17-55-41 en-US yaml - Directus - Crowdin translation](https://user-images.githubusercontent.com/5363448/135489753-422ee709-21bb-4024-bbe8-b7457a4d441f.png)

**Comment by paescuj** [comment]
@rijkvanzanten Could you please chose the option "Show, but auto-translate them" instead because now there are tons of untranslated strings...? 😄

**Comment by rijkvanzanten** [comment]
Done! I got confused by the next checkbox underneath that talked about adding auto-translated suggestions 🙄

**Comment by paescuj** [comment]
Gotcha 😄 Thanks!
