### ISSUE TITLE
Window switching between access token refresh causes error 403

### ISSUE THREAD

**Issue by licitdev** [directus/directus#8449]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Each time the browser window becomes active, an access token refresh is triggered.
When any new request is sent to the server right before the response for the access token refresh is received, it will result in a 403 if the server side has refreshed the access token.

https://user-images.githubusercontent.com/26413686/135439273-97c1f57b-d55b-44b2-9381-04a28833fcd8.mov

### To Reproduce

Switch to the app window and double click on a link that gets data from server.

### What version of Directus are you using?

v9.0.0-rc.95

### What version of Node.js are you using?

v16

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
> When any new request is sent to the server right before the response for the access token refresh is received, it will result in a 403 if the server side has refreshed the access token.

This is a little strange, technically the previous request should still go through as expected, as the user session is still active 🤔

**Comment by licitdev** [comment]
@rijkvanzanten My mistake, it's throwing a 401 and not 403. 😂

Found another issue which is

**Comment by licitdev** [comment]
@rijkvanzanten Sorry, my mistake, it's throwing a 401 for this instance and not 403. 😂 Too many errors gotten me confused, was testing with a 20s token expiry...

Found the issue whereby the authorization token being deleted would result in requests triggering errors...

https://github.com/directus/directus/blob/c32bd0564e9539343272417ee0271fce82e7644d/app/src/auth.ts#L79-L87

Pushing a fix to remove line 80, as there is no longer a need to delete the authorization header.

#8452 also resolves other possible issues. 
- When token is expired and refresh is in progress, server requests will be paused.
- Excessive token refresh

**Comment by rijkvanzanten** [comment]
Ahhhhhhhhhhhh that's the problem! It shouldn't delete the default header before the new refresh token is retrieved 🙂
