### ISSUE TITLE
GraphQL shows type = string for o2m when you don't have permissions to related collection

### ISSUE THREAD

**Issue by ngjoni** [directus/directus#8463]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

The translations are null if I request it via GraphQL. Translations are present in the directus UI and in the database. But not through a GraphQL request. 

### To Reproduce

Create some translation examples and try to fetch them with a GraphQL Client, e.g. https://graphiql-online.com/graphiql or postman. 

In my example, ID:1 should have translations
![image](https://user-images.githubusercontent.com/49320058/135483037-4fe2d7bb-2542-42d5-a726-a9566ff3b6a2.png)
![image](https://user-images.githubusercontent.com/49320058/135483170-493f88c6-a7bc-4a1a-bc6c-75833ede8efa.png)
![image](https://user-images.githubusercontent.com/49320058/135483319-3fdc2f3d-1bc4-4c4a-ab71-7e28301e0309.png)

### What version of Directus are you using?

v9.0.0-rc.95

### What version of Node.js are you using?

16.10.0

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
@ngjoni I'm not seeing this issue on a fresh installation + setup of a translations interface, so there must be something sideways in your particular schema unfortunately. Would you be able to share a database dump, either here or through rijk@directus.io so we can take a look?

**Comment by ngjoni** [comment]
@rijkvanzanten I hate to admit but I did not set the permission. It is working now!
