### ISSUE TITLE
Cannot use regex with CORS_ORIGIN 

### ISSUE THREAD

**Issue by hckhanh** [directus/directus#8522]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I cannot set the **CORS_ORIGIN** to a regular expression

### To Reproduce

set `CORS_ORIGIN=regex:/^(.+\.)?example.com$/` in `.env` file

### What version of Directus are you using?

9.0.0-rc.95

### What version of Node.js are you using?

14.18.0

### What database are you using?

Postgres 13

### What browser are you using?

Edge

### What operating system are you using?

Windows

### How are you deploying Directus?

PaaS

**Comment by joselcvarela** [comment]
Hello @hckhanh 
Regex patterns are passed into `new RegExp` constructor as a string.
So in order to make it work, try to remove your start and end slashes.

@rijkvanzanten should we support literal RegExp via `new Function`?

**Comment by hckhanh** [comment]
Hi @joselcvarela, now it works like a charm

`CORS_ORIGIN=regex:\.example\.com$`

I just followed the docs. It should be updated.

![image](https://user-images.githubusercontent.com/6380436/135803216-e087a9af-5249-4cb0-a105-21191860e805.png)

**Comment by benhaynes** [comment]
CC @alesvaupotic

**Comment by rijkvanzanten** [comment]
@joselcvarela No, we shouldn't do any code execution from an env var value if we can
