### ISSUE TITLE
Unable to use dynamic variable `$NOW` in new permission filter interface

### ISSUE THREAD

**Issue by licitdev** [directus/directus#8529]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

There is no text input field to manually input dynamic variable such as `$NOW`.

<img width="751" alt="Screenshot 2021-10-04 at 6 57 03 PM" src="https://user-images.githubusercontent.com/26413686/135840099-a420a198-4beb-4027-8e6b-fe8eff0ad05f.png">

### To Reproduce

1. Create a date or date time field in a collection
2. Head over to field conditions or custom permission
3. Verify that you can only set a static date

### What version of Directus are you using?

main branch

### What version of Node.js are you using?

v16

### What database are you using?

Postgres

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
@benhaynes Or... use the system one for the main "input", with an additional icon on the right for a toggle to open a popover to control the "NOW" stuff 🤔

**Comment by benhaynes** [comment]
That would be the last resort, yes. But that's not an ideal, or extensible workflow. I can't think of any other options, but multiple icons feels like a bummer.

**Comment by benhaynes** [comment]
Another thing to keep in mind is that the popover doesn't open on focus, only when you click the system icon. So the best we can do is have two icons... which will be hard to differentiate (tooltip will help, but isn't great).

**Comment by benhaynes** [comment]
Here is my proposed solution... and I am very happy with this. There are two icons, one for configuration (choose absolute/relative), and another for setting the date. The date icon should reinforce this with a tooltip, eg: `Select a Relative Date`

We should still be able to use a system date input here, since we can place our icon _over_ the system one, and set `pointer-events: none` to allow pass-through.

![Screen Shot 2021-10-04 at 5 03 08 PM](https://user-images.githubusercontent.com/522079/135924772-03b47e4e-63ff-4452-a4c5-b5e16a1676cd.png)

**Comment by licitdev** [comment]
I am working on an update for `$NOW` that allows users to filter by date ranges based on current period. 

For example: set a range from the start of this hour (set mins and seconds to 0) to the start of 3 hours later (same relative time, but set mins and seconds to 0).
The raw filter would look something like `$NOW(0 hour start)` and `$NOW(3 hours start)`.

Other possibilities include `$NOW(7 days end)` or even `$NOW(-1 year start)`

@benhaynes Will it be possible to include another toggle that allows for the setting of start or end?
@rijkvanzanten Any comments on the above implementation?

**Comment by benhaynes** [comment]
If I'm not mistaken, I think we have all this. We support `$NOW`, and functions for offsetting like `-2 weeks`, and there is a `between` operator that allows limiting to a range. Or... am I missing something?

Also, a lot of this will coalesce in some merges today.

**Comment by licitdev** [comment]
@benhaynes it's a new feature to set ranges based on the selected `time/date type` from current time / date.
I am not sure how to term it better. 😂
It works alongside the offsetting but it will allow users to set time ranges of current hour to next hour etc.

### Examples

From current month to 3 months later.
> set a range from `$NOW(0 month start)` to `$NOW(3 months end)`

Filter previous month data
> set a range from `$NOW(-1 month start)` to `$NOW(-1 month end)`

Hence I think the interface should allow for a selection of `current`, `start` and `end`, where `current` is simply how `$NOW` is.

**Comment by benhaynes** [comment]
Ahh, gotcha... that makes more sense!

**Comment by rijkvanzanten** [comment]
I'm not sure if we should make that part of the same "$NOW" syntax. To me, the parameter is an offset on _now_, but what you're referring to is more like "Last month" (eg 1–31 instead of _today - 31 days_)

**Comment by licitdev** [comment]
The new feature has to be used in conjunction with an offset.
It's like another layer of processing for `$NOW()`. 

Hmm I wonder if the word relativity makes sense?
After thinking about it again, it does make more sense to separate as the user may want a different type of relativity as compared to offset.
May I ask if the following syntax separated by a comma such as `$NOW(offset?, relativity?)` better?

Offset by 3 months, same as the current `$NOW()`
> `$NOW(3 months, current)`

30 minutes before, but at the start of that hour
> `$NOW(-30 minutes, start hour)`

current year end
> `$NOW(0, end year)`

**Comment by rijkvanzanten** [comment]
> May I ask if the following syntax separated by a comma such as $NOW(offset?, relativity?) better?

I'm not sure what the better/best approach is yet, as this is a new subject for me too 😄 

On first impression, I was a little lost in trying to figure out what you meant by "start" and "end" before. I'm wondering if we should see it as a modification on the "now" helper, or a totally new date modifier function altogether. I can also imagine it working as `setDate( $NOW(- 1 month), 1)` to force it to the "start" of the month (as the date is set to 1)

**Comment by harish0sim** [comment]
I love Metabase (http://metabase.io/) date filter technique it's simple and clear. See if helps.

https://user-images.githubusercontent.com/81331198/136034041-81670a02-132c-47ac-bbf5-9e29f0eb45a4.mp4

**Comment by rijkvanzanten** [comment]
@harish0sim That doesn't seem to have a way to "use current day minus a month, but use the start of the month" though does it? (Little hard to tell in the video, it flashed by very fast 😅 )

**Comment by licitdev** [comment]
> On first impression, I was a little lost in trying to figure out what you meant by "start" and "end" before.

I was finding it hard to explain... 🙈 I think probably I should use more examples.

### Examples
| relativity    | input               | output              |
|---------------|---------------------|---------------------|
| current ...   | no change           | no change           |
| start minute  | 14:18:31            | 14:18:00            |
| start hour    | 14:18:31            | 14:00:00            |
| start day     | 24/07/2021 14:18:31 | 24/07/2021 00:00:00 |
| start month   | 24/07/2021 14:18:31 | 01/07/2021 00:00:00 |
| start year    | 24/07/2021 14:18:31 | 01/01/2021 00:00:00 |
| end minute    | 14:18:31            | 14:18:59            |
| end hour      | 14:18:31            | 14:59:59            |
| end day       | 24/07/2021 14:18:31 | 24/07/2021 23:59:59 |
| end month     | 24/07/2021 14:18:31 | 31/07/2021 23:59:59 |
| end year      | 24/07/2021 14:18:31 | 31/12/2021 23:59:59 |

Week might be a challenge but should be possible, and will have to look into gap year too. Where there's Feb 29th.

> I'm wondering if we should see it as a modification on the "now" helper, or a totally new date modifier function altogether. 

Ah yes, but the term `DATE` does not make it sound very relative.

> I can also imagine it working as `setDate( $NOW(- 1 month), 1)` to force it to the "start" of the month (as the date is set to 1)

I am not very sure about the efficiency of this.
I suppose it may end up adding a lot more unnecessary bulk unless there are other functions requiring the parenting.

**Comment by harish0sim** [comment]
@rijkvanzanten I can record a slower video?

**Comment by harish0sim** [comment]
https://user-images.githubusercontent.com/81331198/136039592-385779ec-68aa-4717-9027-fea707f543f7.mp4
Need not be exact. Probably we can extract some good parts from this UI?

**Comment by rijkvanzanten** [comment]
@harish0sim Thanks for that example! Funnily enough, I don't think they actually support what we're talking about above 😄 

The "Previous", "Next", "Current" thing is what we currently support through "$NOW" with the modifiers, and the other filter params are the regular filter operators with a "hardcoded" specified date. However, what @licitdev is suggesting is a combination of the two. Instead of saying "Before September 1st, 2021", he's like to be able to say "Before the start of last month"

**Comment by harish0sim** [comment]
True that. I was focusing on pushing for single UI than proposed two popups :
1. Choose absolute or relative. 
2. UI rendered based on previous choice.
