### ISSUE TITLE
Emojis not working with API in V9

### ISSUE THREAD

**Issue by erik-konrad** [directus/directus#8561]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Its not possible to persist strings and texts with Emojis like  🛒 or  💛 over the API.

It throws the error
`ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\\xF0\\x9F\\x9B\\x92 u...' for column 'facebook_post_text' at row 1"`

Bare MySQL query works fine with the emojis. So the only potential possibility is a knex Bug or something else.

Tested it with v8.8.1 (works fine), v9.0.0-rc.95, v9.0.0-rc.64 (to check if its a newer bug) under MySQL 8 and MariaDB 10.3.31

### To Reproduce

Simply try to save 🛒 or  💛  (and much more emojis) in varchar or text field

### What version of Directus are you using?

v9.0.0-rc.95

### What version of Node.js are you using?

16.9.1

### What database are you using?

MariaDB 10.3.31

### What browser are you using?

Firefox / Chrome

### What operating system are you using?

Ubuntu 20.04.1

### How are you deploying Directus?

running locally & Docker

**Comment by rijkvanzanten** [comment]
What's the collation/charset of this column?

**Comment by erik-konrad** [comment]
We have tried it with utf8mb4 / utf8mb4_general_ci and utf8mb4_unicode_ci. Bare Mysql Query works fine. Its not the database charset. The Problem only appears if we try to write strings over the API. If we open the bare mysql row over the app, the app shows only "?" instead of the emojis.

**Comment by rijkvanzanten** [comment]
I believe the `mysql` package that handles the connection might have its own flag to set the charset. Might setting the "charset" option (https://www.npmjs.com/package/mysql#connection-options) through `DB_CHARSET` to match your database's charset see if that does the trick?

**Comment by erik-konrad** [comment]
That does the Trick. I thank you so much.

**Comment by rijkvanzanten** [comment]
Thanks for confirming! I'll add a note to the docs to alert MySQL/MariaDB users of this additional flag 👍🏻

**Comment by cdwmhcc** [comment]
@rijkvanzanten v9.0.0 still has this problem, mysql version is 8.0.24, I confirm that my database table uses utf8mb4_0900_ai_ci.

Everything works fine in v8.

**Comment by joselcvarela** [comment]
Hi @cdwmhcc 
Just to confirm, have you set `DB_CHARSET` on your environment variables?

**Comment by cdwmhcc** [comment]
> DB_CHARSET

![image](https://user-images.githubusercontent.com/8030134/140770181-54e96f06-70b8-49ec-a8ea-95c212c515d5.png)
![image](https://user-images.githubusercontent.com/8030134/140770233-de2d91e5-5aad-47d7-8271-19ebc4413fc3.png)

**Comment by joselcvarela** [comment]
@rijkvanzanten it seems mysql package is not updated since 2020-01-23: https://www.npmjs.com/package/mysql
There is an open PR to fix the issue @cdwmhcc is facing: https://github.com/mysqljs/mysql/pull/2099/files

My suggestion is to use `mysql2` since is supported by `knex` ([example](https://knexjs.org/#Installation-node)) and already fix this problem with charset
https://github.com/sidorares/node-mysql2/blob/07a429d9765dcbb24af4264654e973847236e0de/lib/constants/charsets.js

I believe the process should be seamless since this should be handled by `knex`. But don't know if the same works with `knex-schema-inspector`

**Comment by cdwmhcc** [comment]
> @rijkvanzanten it seems mysql package is not updated since 2020-01-23: https://www.npmjs.com/package/mysql There is an open PR to fix the issue @cdwmhcc is facing: https://github.com/mysqljs/mysql/pull/2099/files
> 
> My suggestion is to use `mysql2` since is supported by `knex` ([example](https://knexjs.org/#Installation-node)) and already fix this problem with charset https://github.com/sidorares/node-mysql2/blob/07a429d9765dcbb24af4264654e973847236e0de/lib/constants/charsets.js
> 
> I believe the process should be seamless since this should be handled by `knex`. But don't know if the same works with `knex-schema-inspector`

Thank you for your help.

I converted the database table to `UTF8MB4_GENERAL_CI` and modified .env to:

DB_CHARSET="UTF8MB4_GENERAL_CI"

It work.

But mysql 8 recommends using `UTF8MB4_0900_AI_CI`,Hope to follow up in the future.

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten it seems mysql package is not updated since 2020-01-23: https://www.npmjs.com/package/mysql There is an open PR to fix the issue @cdwmhcc is facing: https://github.com/mysqljs/mysql/pull/2099/files
> 
> My suggestion is to use `mysql2` since is supported by `knex` ([example](https://knexjs.org/#Installation-node)) and already fix this problem with charset https://github.com/sidorares/node-mysql2/blob/07a429d9765dcbb24af4264654e973847236e0de/lib/constants/charsets.js
> 
> I believe the process should be seamless since this should be handled by `knex`. But don't know if the same works with `knex-schema-inspector`

Yeah we can look into that 👍🏻 

We should also look into the possibility of relying on the new official mysql driver built by Oracle themselves (`@mysql/xdevapi`), but seeing that's not supported in `knex` (yet), that'll be a bigger adventure

**Comment by joselcvarela** [comment]
For reference:
https://github.com/directus/directus/discussions/4468
https://github.com/knex/knex/issues/3963

**Comment by cdwmhcc** [comment]
@rijkvanzanten 

.env
`DB_CHARSET="UTF8MB4_GENERAL_CI"`

When I create a new collection, it will prompt:

```
default character set UTF8MB4_GENERAL_CI - ER_UNKNOWN_CHARACTER_SET: Unknown character set: 'UTF8MB4_GENERAL_CI'
```

**Comment by rijkvanzanten** [comment]
@cdwmhcc I believe `UTF8MB4_GENERAL_CI` is a _collation_, not a _character set_. Try using `DB_CHARSET="utf8mb4"` 👍🏻
