### ISSUE TITLE
Settings page freezes after reordering additional fields

### ISSUE THREAD

**Issue by smilledge** [directus/directus#8587]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

If you add two additional fields to the `directus_settings` collection everything works as expected. However, if you re-order the fields the settings page will freeze next time you load it (Firefox responds after a few seconds, Brave never seems to respond).

https://user-images.githubusercontent.com/1536407/136191363-24e1c819-311f-44ed-9736-b27d785e2c98.mp4

### To Reproduce

1. Add two additional fields to `directus_settings` (any field type with any settings)
2. Change the order of the fields (any order, just needs to be changed)
2. Go to the setting page 
3. 💥💥💥 Setting page will freeze 💥💥💥 

### What version of Directus are you using?

9.0.0-rc.95 (also reproduced in 9.0.0-rc.94 and 9.0.0-rc.93)

### What version of Node.js are you using?

v16.0.0

### What database are you using?

Postgres 13

### What browser are you using?

Brave, Firefox

### What operating system are you using?

Ubuntu

### How are you deploying Directus?

Locally

**Comment by azrikahar** [comment]
Can confirm this is reproducible, albeit in my case it doesn't necessarily hang indefinitely, but requires more than 4-5s to be responsive. Something might be looping/processing unnecessarily & blocks the main thread.
