### ISSUE TITLE
API - deep sort on M2M does not work properly

### ISSUE THREAD

**Issue by nazariydj** [directus/directus#8606]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Hi guys, I can't found solution how to sort deep M2M items. 
I have two collections Posts and Categories with posts_categories M2M relation (id, post, category). 
I need to get last Category Posts (sort by -date_created). 

I'm trying with:
`&deep[posts][post][_sort]=-date_created`
and
`&deep[posts][post][_sort]=date_created`
but order of Posts don't change.

With LOG_LEVEL = trace the SQL queries seems to be correct: 
```select `posts`.`id` from `posts` where `posts`.`id` in (?, ?, ?) order by `posts`.`date_created` desc [3, 4, 5]```
and
```select `posts`.`id` from `posts` where `posts`.`id` in (?, ?, ?) order by `posts`.`date_created` asc [3, 4, 5]```
but order of posts in response is the same (id asc) even if i try to order by id and -id.

Initially i'm goin to open Q&A in Discussions but it seems like a bug.

### To Reproduce

https://user-images.githubusercontent.com/17914536/136378996-40dc5320-149b-48d1-aa65-62133c476b94.mp4

### What version of Directus are you using?

v9.0.0-rc.95

### What version of Node.js are you using?

16.10.0

### What database are you using?

MySQL 8.0.26

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
Think it's going wrong in here:

https://github.com/directus/directus/blob/b4bb1071f26a9313a08952293ebb4ac6ee37ec9a/api/src/database/run-ast.ts#L345-L365

**Comment by nazariydj** [comment]
hi @rijkvanzanten,
i make some debug and there is more problems i found
- the correct items order is received (from query result) one iteneration before inside m2o condition before the merge of items with junction table (where order breaks)
- then the items is reordered (for second time) where you show me but using the sort field of junction table (or id as default). i dont know if it can be solved here becouse this sort function can't sort any data type (like string or date) even if this fields is fetched
i don't know what could be the correct solution. maybe ignoring order of the junction table if there is deep sort query param. 
unfortunately i'm not very familiar with typescript (i'm a php developer) and it makes for me hard to open PR and search the solution for this.
anyway i hope my comments are helpful in solving this problem

thanks guys for the great job you are doing
i remain available in case I could help in any way

**Comment by mpartipilo-fincons** [comment]
I find in version 9.7 that the problem is also present for M2O relations. 
Here is my example:
I want to sort contracts (collection "contracts") for the "contract_type" code (collection "contracts_type"), the relation is an M2O. By running the following query:

/items/contracts?deep[contract_type][_sort]=code

I have no effect on the results.

Is there something wrong?

**Comment by rijkvanzanten** [comment]
@mpartipilo-fincons deep sorts a nested collection (array of items), it doesn't sort the top-level items based on a nested value. That's what #12084 aims to add 👍🏻
