### ISSUE TITLE
Problem with filter on api (Global Query Parameters)

### ISSUE THREAD

**Issue by f-g-s-e** [directus/directus#8607]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I'm experiencing an unexpected behavior with filtering on api requests. See the section "To Reproduce" for more details.

### To Reproduce

- Create a collection named **coll_a**, with a text field **field_a**
- Create a collection named **coll_b**, with a text field **field_b**
- Create a collection named **coll_c**, with a text field **field_c**
- Create a one to many relation form **coll_a** to **coll_b**, with a field on **coll_a** named **rel_o2m_with_b** and a field named **rel_m2o_with_a** on **coll_b**
- Create a one to many relation form **coll_b** to **coll_c**, with a field on **coll_b** named **rel_o2m_with_c** and a field named **rel_m2o_with_b** on **coll_c**.

When I try this request  `GET /items/coll_a?filter[rel_o2m_with_b][field_b][_eq]="b 1"`, I get all items from collection coll_a that have a relation with an item in collection coll_b with the field field_b equal to "b 1". But when I try this request 
`GET /items/coll_a?filter[rel_o2m_with_b][rel_o2m_with_c][field_c][_eq]="c 1"`, I expect to get all items from collection **coll_a** that have a relation with an item in collection **coll_b**, that have a relation with an item in collection **coll_c** with the field **field_c** equal to "c 1", but what I get are all the items from **coll_a**, no matter what are the conditions expressed with the filter.

### What version of Directus are you using?

v9.0.0-rc.95

### What version of Node.js are you using?

v16.8.0

### What database are you using?

mysql

### What browser are you using?

chrome

### What operating system are you using?

windows

### How are you deploying Directus?

locally

**Comment by Oreilles** [comment]
I just tried to replicate this on `9.5.1` and it seems the issue have been fixed, the filters are returning expected results on my end.
