### ISSUE TITLE
Translation of App login screen not working

### ISSUE THREAD

**Issue by neo7-studio-web** [directus/directus#8641]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When already logged in and opening directus app page, the login screen is not translated 
 

### To Reproduce

Open directus App page, the login screen is not translated ("Sign in", "Sign out", "Continue", "authenticated" should be in french) : 

![step1](https://user-images.githubusercontent.com/18073828/136555486-1d48f3c3-155f-459b-8285-8e1b30d6cbf3.jpg)

If I click on "continue" and then click on the back button of the browser, the login screen is correctly translated (in french in my example) :

![step2](https://user-images.githubusercontent.com/18073828/136555620-89766102-337f-41dc-8f6a-e3216cdf4ab6.jpg)

### What version of Directus are you using?

v9.0.0-rc96

### What version of Node.js are you using?

12.18.1

### What database are you using?

MySQL

### What browser are you using?

Firefox

### What operating system are you using?

CentOS

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
This will be resolved by https://github.com/directus/directus/pull/8196
