### ISSUE TITLE
Mandatories permissions on directus_users not applied

### ISSUE THREAD

**Issue by gkielwasser** [directus/directus#8649]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Permissions that should be applied by default on directus_users collection does not works.

### To Reproduce

1- Go on public role
2- on directus_users collection add read permissions on at least one field, let's say "email"
3- Public role is now able to read all users email

### What version of Directus are you using?

v9.0.0-rc.96

### What version of Node.js are you using?

v14.16.0

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

locally

**Comment by gkielwasser** [comment]
Ok, it might be a misunderstanding, but I thought because of this statement that is displayed as a warning:
``The following are minimum permissions required when "App Access" is enabled. You can extend permissions beyond this, but not below.``
```
{
  "id": {
    "_eq": "$CURRENT_USER"
  }
}
``` 
This permission would be applied by default.

**Comment by nxmad** [comment]
@rijkvanzanten Users permissions are actually most confused part in Directus for me. Is it possible to make only first name and avatar visible for other users (for e.g.), but all fields for admin and current user?
P.S. I'm sorry to bother, that's probably not the best place to ask questions. But I tried to ask in Discord million of times and no one answered ;(
