### ISSUE TITLE
Unable to delete field

### ISSUE THREAD

**Issue by tuxinside** [directus/directus#8655]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Unable to delete a field. Trying to delete field, cause following error message:

```
[INTERNAL_SERVER_ERROR] update `directus_fields` set `group` = NULL where `group` = 2 - ER_TRUNCATED_WRONG_VALUE: Truncated incorrect DOUBLE value: 'test'
```

I suppose that endpoint to delete field continue to refer to numeric group id instead group name after update since rc95.

### To Reproduce

Create a field, after that try to delete field

### What version of Directus are you using?

v9.0.0-rc.96 and v9.0.0-rc.95

### What version of Node.js are you using?

v16.10.0

### What database are you using?

8.0.26 - MySQL

### What browser are you using?

Safari

### What operating system are you using?

Ubuntu 20.04

### How are you deploying Directus?

Locally

**Comment by flayks** [comment]
Experiencing the same issue with MariaDB. Not really sure where this could come from but as for some context and testing:
1. When moving _all_ my fields from _all_ the groups I have, I can remove any field again
2. When adding a field to a group again, the error comes back
3. Removing all my groups from everywhere, it works again. Then when creating a new group and putting a field (new or existing) inside it: same error

**Comment by iksent** [comment]
I am experiencing the same issue at the latest 9.5.0

```
{
  "errors": [
    {
      "message": "update `directus_fields` set `group` = NULL where `group` = 'articles' and `collection` = 'docs_group' - ER_TRUNCATED_WRONG_VALUE: Truncated incorrect DOUBLE value: 'articles'",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

Should I open a new one? Or am I doing something wrong?
