### ISSUE TITLE
Field select uses wrong syntax for m2a

### ISSUE THREAD

**Issue by wc-matteo** [directus/directus#8697]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

the [correct syntax](https://docs.directus.io/reference/api/query/#many-to-any-union-types) is `<m2a-field>:<collection-scope>.<field>`.

the query in the collections view does this: `<m2a-field>.<field>:<collection-scope>`

### To Reproduce

create a m2a field and try to have its display template with nested related fields being honored

### What version of Directus are you using?

v9.0.0-rc.96

### What version of Node.js are you using?

n/a

### What database are you using?

postgres 13.3

### What browser are you using?

chrome

### What operating system are you using?

win 10

### How are you deploying Directus?

k8s

**Comment by fanglee101** [comment]
[b]https://icq.im/AoLGnKtUsQZKGmUTjTA

https://t.me/chinadebitbank


This is arqidarknet from

torre,zorldcard, market pro,

I sell first hand pos data,atm datas,resellers welcome,
usable pos,atm 

bank logs,email access,password
RDP
hack bibbles
Cvv=address
eu-usa-asia


minimum order is  10pieces 

no test for new clients* consideration could be consider on basis.

[/b]


![photo_2021-10-06_08-41-11](https://user-images.githubusercontent.com/92568711/137448982-d469b9ef-8b4d-4e1d-854b-8135b7923f46.jpg)
