### ISSUE TITLE
Error in Notifications

### ISSUE THREAD

**Issue by hugopvl** [directus/directus#8699]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

It is not possible to consult notifications, none of the options work, as shown in the attached image.

![image](https://user-images.githubusercontent.com/81326296/136834266-6c263d51-752b-48de-b1bf-065f592ea049.png)

### To Reproduce

Access Notifications

### What version of Directus are you using?

9.0.0-rc.96

### What version of Node.js are you using?

14.17.0

### What database are you using?

SQL SERVER

### What browser are you using?

CHROME

### What operating system are you using?

WINDOWS 10

### How are you deploying Directus?

LOCALLY

**Comment by paescuj** [comment]
Fixed by #8664
