### ISSUE TITLE
Conditions not working on create

### ISSUE THREAD

**Issue by Attacler** [directus/directus#8716]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

It looks like conditions only apply at edit and not at create.
Is this intentional or by mistake?

### To Reproduce

Make a condition to hide a field when another field is filled with a certain value (for example boolean).
Create a new record, while doing this all fields will show
After that, edit the record and then somehow the fields do hide when you trigger the condition.

### What version of Directus are you using?

rc96

### What version of Node.js are you using?

Docker

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
This is actually already reported in #8145 👍 With #8154 aiming to fix this.
