### ISSUE TITLE
Error Accessing a Collection

### ISSUE THREAD

**Issue by hugopvl** [directus/directus#8822]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I have a collection with only two fields, factory and status, it has no id, when I try to access the collection, it gives the error below.

But if I refresh the page, it asks again for the authentication data and already shows the collection data.

![image](https://user-images.githubusercontent.com/81326296/137480435-e4db5660-db19-4821-9987-fc460300721e.png)

![image](https://user-images.githubusercontent.com/81326296/137480468-a1c30121-1544-47c5-b01a-fba20da1e877.png)

### To Reproduce

I don't know how to reproduce the error, but the description is above

### What version of Directus are you using?

rc.97

### What version of Node.js are you using?

v14.17.0

### What database are you using?

MSSQL 

### What browser are you using?

CHROME

### What operating system are you using?

WINDOWS

### How are you deploying Directus?

LOCALLY

**Comment by rijkvanzanten** [comment]
@hugopvl How did you create this collection? What page is that exactly? What layout is used with this collection (the default tabular?) What happens when you reset the page preferences? Did it use to have a column called "id" that was later removed?

**Comment by alejandro-tss** [comment]
I have also experienced the same problem, the pattern is, apparently, when you enter the view of a collection it takes the name of the primary key field to sort by default the items, when you change collection if the primary key field has another name it fails, apparently it is a computed property of vue that stores that change if you change the collection.
