### ISSUE TITLE
Editing Presets and Bookmarks makes flash

### ISSUE THREAD

**Issue by GrefriT** [directus/directus#8845]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Hello. When changing Layout Options in Presets, the page blinks every time you change. But if you change Layout after that, then the page stops blinking

https://user-images.githubusercontent.com/45934058/137559009-37ed3887-0316-4967-a6aa-0f9c9aceada5.mp4

### To Reproduce

1. Go to Settings -> Presets and Bookmarks
2. Create preset
3. Try to edit Layout options, the page starts flashing with every change

### What version of Directus are you using?

9.0.0-rc.97

### What version of Node.js are you using?

16.11.0

### What database are you using?

MySQL 8

### What browser are you using?

Chrome

### What operating system are you using?

Windows_NT 10.0.19042

### How are you deploying Directus?

Locally

**Comment by licitdev** [comment]
@rijkvanzanten I am unable to reproduce this issue in the latest release & main branch. Can this issue be closed?

Also, is a refactor is required? There are several other views that have the `layoutWrapper` as its top-level wrapper.

**Comment by GrefriT** [comment]
@licitdev I am unable too, so I'm closing this issue
