### ISSUE TITLE
Choosing a date with the date picker saves an earlier date

### ISSUE THREAD

**Issue by flayks** [directus/directus#8875]
### Preflight Checklist

- [x] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When picking a specific date, here April 6th 2019, the datepicker is saving a day before the chosen date for some reason

### To Reproduce

https://user-images.githubusercontent.com/273716/137623479-a9fcedd9-3717-4937-be79-cb9726b22580.mp4

### Errors Shown

None

### What version of Directus are you using?

9.0.0-rc.98

### What version of Node.js are you using?

14.18.0

### What database are you using?

MySQL

### What browser are you using?

Brave

### What operating system are you using?

macOS Big Sur (11)

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
> Possibly a duplicate of #7383, my bad!

Yup it should be. no worries 👍 I'll proceed to close this as duplicate.
