### ISSUE TITLE
Error on multiple files field creation

### ISSUE THREAD

**Issue by devistar** [directus/directus#8904]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

An error is displayed when creating a multiple file field. Permissions are granted. 
Creating a single file field works.

### To Reproduce

Create a multiple file field

### Errors Shown

![image](https://user-images.githubusercontent.com/11228594/137728915-581cd7b2-8573-46e0-975c-e32db1cb6431.png)

### What version of Directus are you using?

9.0.0-rc.98

### What version of Node.js are you using?

14.15.4

### What database are you using?

MS SQL 2017

### What browser are you using?

Vivaldi

### What operating system are you using?

Windows_NT 10.0.19041

### How are you deploying Directus?

Running locally

**Comment by valdeirpsr** [comment]
Same problem with me

**Directus**

I use the Directus with Docker and MySQL 8+

```json
{
    "data": {
        "directus": {
            "version": "9.0.0-rc.98"
        },
        "node": {
            "version": "16.11.1",
            "uptime": 4558
        },
        "os": {
            "type": "Linux",
            "version": "5.11.0-37-generic",
            "uptime": 45291,
            "totalmem": 8287645696
        }
    }
}
```

**Request**

Use the file below with https://toolbox.googleapps.com/apps/har_analyzer/

[directus_har.zip](https://github.com/directus/directus/files/7369829/directus_har.zip)
