### ISSUE TITLE
Filtering related collections does consider only first filter

### ISSUE THREAD

**Issue by darioguarascio** [directus/directus#8909]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Calling the api this way:
```
/items/table1?access_token=x&filter[table2][code]=code&filter[table2][status]=published&sort=domain&limit=-1
```

Causes only the first filter ( `filter[table2][code]` ) to be considered.

### To Reproduce

I also tried swapping the first filter and the second, even in that case only the first ( `filter[table2][status]` after swapping ) is considered 

### Errors Shown

none

### What version of Directus are you using?

9.0.0-rc.98

### What version of Node.js are you using?

16.11.1

### What database are you using?

postgres:13

### What browser are you using?

Chrome

### What operating system are you using?

Linux 5.11.0-37-generic

### How are you deploying Directus?

Docker

**Comment by darioguarascio** [comment]
@rijkvanzanten  I think i missed the `_and` syntax. I mean, there is a mention in https://docs.directus.io/reference/filter-rules/ with the json format, but nothing in querystring format, and yes, this feels more natural.
Would you tell me what's the correct _and syntax ? or where the doc is explaining

**Comment by darioguarascio** [comment]
@rijkvanzanten just found out this is now causing a HTTP 500 in `v9.2.1` while it was working correctly in `v9.1.2`

**Comment by rijkvanzanten** [comment]
@darioguarascio What do you mean? What was working before exactly, what is the error thrown, and what is the schema we can use to reproduce with?

**Comment by darioguarascio** [comment]
@rijkvanzanten this thread started to clarify the correct syntax to use when querying apis with get parameters.
the one with `_and` operator is the preferred one: 
```
?filter[_and][][table2][code][_eq]=code
&filter[_and][][table2][status][_eq]=published
```

Which I adopted and worked correctly until I upgraded to v9.1.2, when it started throwing HTTP 500.

**Comment by azrikahar** [comment]
Hi @darioguarascio, would you be able to try this again with the latest version `v9.4.2`? I've did some testing on the latest version and it seems to work on my end. It also now works even if we _don't_ use the `_and` syntax.

<details>
<summary>Full data with <code>/items/bars?fields=*.*</code></summary>

```json
{
  "data": [
    {
      "id": 1,
      "name": "Bar 1",
      "foos": [
        {
          "id": 1,
          "name": "Foo A",
          "category": 1,
          "bar": 1
        },
        {
          "id": 2,
          "name": "Foo B",
          "category": 1,
          "bar": 1
        }
      ]
    },
    {
      "id": 2,
      "name": "Bar 2",
      "foos": [
        {
          "id": 3,
          "name": "Foo C",
          "category": 2,
          "bar": 2
        },
        {
          "id": 4,
          "name": "Foo D",
          "category": 2,
          "bar": 2
        }
      ]
    }
  ]
}
```

</details>

## With `_and` 

![chrome_Yp0byQ2MAz](https://user-images.githubusercontent.com/42867097/148331308-fa1b9534-8a1e-4397-8af3-33e5d2e23f69.png)

Set `category equal 2` to make sure it's using the 2nd filter as well:

![chrome_CSX2d3nD9K](https://user-images.githubusercontent.com/42867097/148331882-2b4861a4-3389-4ec3-aea6-8d130aa66072.png)

## Without `_and`

![chrome_0UisgIYJgK](https://user-images.githubusercontent.com/42867097/148331732-479f45ae-acab-459f-b963-3668a4eb483e.png)

Set `category equal 2` to make sure it's using the 2nd filter as well:

![chrome_o6LYNr0vTu](https://user-images.githubusercontent.com/42867097/148331738-117e7db4-5695-4df4-b0e7-23c8ae4c040c.png)

**Comment by rijkvanzanten** [comment]
I believe this was fixed in https://github.com/directus/directus/pull/10194 and the subsequent changes to improve the implicit filter structure 🙂 Lemme know if things are looking good on your end @darioguarascio. We'll reopen if not 👍🏻

**Comment by darioguarascio** [comment]
@rijkvanzanten @azrikahar good! i think this solved it
