### ISSUE TITLE
Set default presets for all system tables (eg: Webhooks)

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#8913]
Pages like Webhooks should have a global preset so they look nice when adding things (without the admin having to set that up). Not sure if there are any other pages, but we should at least do Webhooks.

![Screen Shot 2021-10-18 at 10 01 39 AM](https://user-images.githubusercontent.com/522079/137746555-25c039cc-1a4f-4168-8da8-9473b668a34c.png)

**Comment by azrikahar** [comment]
Since preset for Webhooks page was added, and the remaining "unchanged" pages, likely only Presets & Bookmarks may have tentative changes in the pipeline, opting to close this issue as resolved 👍
