### ISSUE TITLE
Rename the collections module name from "Collections" to "Content"

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#8919]

**Comment by supermx1** [comment]
Or can we set the module name ourselves? In case you don't want to use the term "content" or "collection"... In my case, I would like to call it data?

**Comment by rijkvanzanten** [comment]
Down to discuss that in a new feature request! As of right now, the name of the module is provided by the module itself, and used in things like page headings, navigation tooltips, etc. 

In the meantime, you could already hide it from the regular module nav, and add a custom link to /collections named data (that would allow you to set a custom icon too!)

**Comment by rijkvanzanten** [comment]
Implemented in https://github.com/directus/directus/pull/9441
