### ISSUE TITLE
unable to get local issuer certificate when uploading files to S3 from localhost using CMS project

### ISSUE THREAD

**Issue by pchebro** [directus/directus#8928]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I'm getting below error when uploading images from my localhost (http://localhost:8055/admin/files)

Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1514:34)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket.emit (domain.js:470:12)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:708:12)
    at handleError (C:\Users\n0200752\Portal\surety-portal-cms\node_modules\@directus\drive-s3\dist\AmazonWebServicesS3Storage.js:19:20)
    at AmazonWebServicesS3Storage.getStat (C:\Users\n0200752\Portal\surety-portal-cms\node_modules\@directus\drive-s3\dist\AmazonWebServicesS3Storage.js:162:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

### To Reproduce

Browse and try to  upload file under /admin/files

### Errors Shown

{
  "errors": [
    {
      "message": "E_UNKNOWN: An unknown error happened with the file 1f2df5f3-1f11-47f4-994d-07a653892e78.png.\n\nError code: NetworkingError\nOriginal stack:\nError: unable to get local issuer certificate\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1514:34)\n    at TLSSocket.emit (events.js:400:28)\n    at TLSSocket.emit (domain.js:470:12)\n    at TLSSocket._finishInit (_tls_wrap.js:936:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:708:12)",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

### What version of Directus are you using?

9.0.0-rc.64

### What version of Node.js are you using?

14.17.6

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
Please update to the latest version of Directus. If the problem still persists on the latest version, we can reopen and continue investigating 👍🏻
