### ISSUE TITLE
Move "Show Archived" to filter bar

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#8931]
I agree that it's far too difficult to know this feature is on right-click of the collection. Let's add it as a toggle below the "Add New Filter" button:

```
[ ] Include Archived Items
```

**Comment by azrikahar** [comment]
I believe we can close this in favor of #9523

**Comment by benhaynes** [comment]
Haha, I'm duplicating my own issues! At least we came up for a better place for this before it was implemented! 🙂 

Thanks @azrikahar!!
