### ISSUE TITLE
M2M relational update broken

### ISSUE THREAD

**Issue by nickluger** [directus/directus#8979]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

M2M updates are broken, like for example:

```User <=> UserAdress <=> Address```,

where `Address` has a field `users` of all people living at a certain address, and `User` has a field `addresses` of all their residences.

Before we updated, we used `rc.92`. On M2M relations, when running a relational update on the `Address.users` field, the `input` looked like:

```js
// rc 92
{
  users: [
   // IDs of EXISTING elements in the "UserAdress" JUNCTION TABLE!
   // These are already associated with this "Address", keep it like this!
   // (These will be simply ignored by Directus, as they already exist)
    "123",
    "456",
  // Associate the existing "User" with ID "789" with this "Address"!
  // (Directus will create a new entry in "UserAddress" table) 
    {
       userId: "789"
    },
     // On the fly create a new user (nested creation) and then associate with this "Address"!
     // (Directus will create a new entry in "User" table, and then in "UserAddress" table) 
    {
      name: "Mary Crawley",
      age: 25
    }
  ]
}
```
The same thing, the other way round:
```js
// rc 92
{
  addresses: [
    "123",
    {
      name: "Downton Abbey",
      type: "Country estate"
    }
  ]
}
```

This led to two very important attributes:

1. In **custom hooks**, we always knew what part of the relational input is an existing association, a new association or a new (combined) creation + association. This can be mandatory to run certain business/rules.validations, e.g. _restrict the number of addresses per user within a country_.
2. Usually the junction table `UserAddress` contains two **foreign keys** like `userId` and `addressId` and these fields have a **combined index/unique constraint** on them, as it doesn't make sense to have the same address connected twice to the same user. Directus respected that and **never tried to create the same junction table entry twice**.

In the current version, `rc.98`, both is no longer true, because the above input now looks like:
```js
// rc 98
{
  users: [
   // Cannot distinguish anything, Directus tries to recreate these entries in "UserAddress"!
   // Will fail due to unique constraint in DB!
    { userId: "123" },
    { userId: "456" },
   // Will work, but we cannot determine easily (as before), that this is an existing Item!
    { userId: "789" },
   // Will work
    {
      name: "Mary Crawley",
      age: 25
    }
  ]
}
```

So Directus now tries to **re-create the first two entries** in `UserAddress`which, leads to a database error + relational input is indistinguishable for hooks.

### To Reproduce

Build M2M-relationship described above and try to update `users` or `addresses` fields.

### Errors Shown

Database throws unique constraint error, if you have one set up. Otherwise, Directus will happily create the same basic relationship multiple times.

### What version of Directus are you using?

v9.0.0-rc.98

### What version of Node.js are you using?

14

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by nickluger** [comment]
Addendum: In our case, `UserAdress` has a separate `id`-primary key, while `userId` and `addressId` just have a unique constraint and are not the primary key. Maybe that has some effect, though everything is shown correctly in the M2M relationship-interface in Directus.

**Comment by licitdev** [comment]
@nickluger I have just tested on `v9.2.0` where M2M updates is back to `rc 92` above.
Please kindly confirm if the issue still persists after you have updated to the latest version. 
Thank you.

**Comment by AdiechaHK** [comment]
@nickluger @licitdev 

Can you please check my [PR#10368](https://github.com/directus/directus/pull/10368) This will solve this problem

**Comment by nickluger** [comment]
Hey guys, sorry, but we're no longer using Directus, so cannot verify that.

**Comment by rijkvanzanten** [comment]
This was fixed in https://github.com/directus/directus/pull/10368
