### ISSUE TITLE
Can't update user when providing it's (current) email

### ISSUE THREAD

**Issue by meoweloper** [directus/directus#8984]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [x] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

This is a relapse of the issue mentioned here https://github.com/directus/directus/issues/5538. With further details mentioned in this comment https://github.com/directus/directus/issues/5538#issuecomment-948015740

I would be happy to create a PR if you can just give me some directions

Thanks

### To Reproduce

Same steps to reproduce as in original issue. 

### What version of Directus are you using?

v9rc98

### What version of Node.js are you using?

v14.16.1

### What database are you using?

Postgres 12.2

### What browser are you using?

Brave/Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by aidenfoxx** [comment]
Fix added here #9024.

**Comment by meoweloper** [comment]
That was fast. Awesome work guys! Thanks 🙏
