### ISSUE TITLE
Field validation is ignored in side panel view

### ISSUE THREAD

**Issue by martijn-dev** [directus/directus#9006]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I created some relations to a collection (m2o, o2m, m2a, m2m). 
This related collection has some fields with validation (cannot be NULL etc.) 

Inside the "parent" collection I use the "Create New" button on the relation field. This will open a side view wherin I can create a new collection item of this related collection. But in this side view it ignores any kind of validation. I can just create items without it checking for empty fields etc.

### To Reproduce

- Create two collections (a parent and a related collection)
- Create some fields with validation on the related collection (Cannot be NULL, required field etc.)
- Create a relation field in the parent collection to the related collection (m2o, o2m, m2a, m2m)
- In the edit/live view click on the button "Create New" and try to create a related collection without setting any fields
![image](https://user-images.githubusercontent.com/73393707/138256513-18297581-2ba0-4970-8077-e4102b398d9a.png)

### What version of Directus are you using?

v9.0.0-rc.98

### What version of Node.js are you using?

v16.6.1

### What database are you using?

Postgres 13.3

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying Directus?

running locally

**Comment by Oreilles** [comment]
Closing is favour of https://github.com/directus/directus/issues/9176
