### ISSUE TITLE
Remove Status translations until we have a proper interface

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#9033]
I know this gives us translations, but it looks messy, and when you create new options its confusing why some look so technical. We need to revert to plain strings (eg: Published`) until we have a dedicated interface to display this correctly.

![Screen Shot 2021-10-21 at 6 38 23 PM](https://user-images.githubusercontent.com/522079/138367454-9871d4d2-5a27-469a-bae5-1b727da3f8f7.png)

**Comment by azrikahar** [comment]
Just to link these together as reference: #8323 #8104

**Comment by azrikahar** [comment]
![chrome_TlwmZb5cOQ](https://user-images.githubusercontent.com/42867097/141290324-953c5540-9cad-4654-b8b2-490a9adf282d.png)

This is actually resolved by #8104 now, so we won't need to remove them anymore. Shoutout to @joselcvarela again for wrapping up that PR!
