### ISSUE TITLE
The layout field in the collection item list is often missing

### ISSUE THREAD

**Issue by cdwmhcc** [directus/directus#9082]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

![image](https://user-images.githubusercontent.com/8030134/138509164-bdd866c1-f000-44ac-bd42-d8d1e40df145.png)
After I select the displayed fields, adjust their positions, and set the width of each field, it often happens that the positions are disordered and the fields are lost. I need to reset it.

v9.0.0 rc97、98、99

### To Reproduce

I don’t know how it happened, but I’m sure it happens often.

### What version of Directus are you using?

v9.0.0 rc97、98、99

### What version of Node.js are you using?

16.11.0

### What database are you using?

mysql 8.0

### What browser are you using?

chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally

**Comment by joselcvarela** [comment]
Hello @cdwmhcc 
I am trying to replicate locally without success.
Can you provide a screen recording while this happens?
Also, please show the Network tab on Developer tools.

**Comment by cdwmhcc** [comment]
This failure did not occur again these days. I want to close this issue.
