### ISSUE TITLE
Error with M2O and NOT Allowing NULL

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#9089]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I get a foreign key constraint error when trying to create/edit a M2O field with `Nullable` disabled (unchecked).

![Screen Shot 2021-10-22 at 8 39 31 PM](https://user-images.githubusercontent.com/522079/138535811-e589e8a6-c51c-4c08-9bd1-f3be9aa53f95.png)

### To Reproduce

1. Create M2O field
2. Turn "All NULL Value" Off
3. Hit Save

### Errors Shown

See above.

### What version of Directus are you using?

RC.99

### What version of Node.js are you using?

7.20.3

### What database are you using?

MySQL 5.7.26

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

locally

**Comment by Oreilles** [comment]
This is expected: the `onDelete` action is `SET NULL`-  Which means when deleting the referenced item, the database would try to set this column to NUL,L which would break this constraint - so MySQL prevent you from doing this.

( Interestingly, PostgreSQL doesn't complain about it until we actually try to delete the referenced item ).

We could disable the `onDelete` option and set it to `CASCADE` automatically when a user makes a relational field non nullable like in your case, but it might not be expected to some users and lead to mistakes. Ultimately it's probably better to leave it as is...

**Comment by benhaynes** [comment]
Ah, that makes sense but it was not obvious to me at all. I'd be fine disabling one of the two, or throwing a notification when both are set... at least explaining to users that they can't do this (before they save and get this technical error).
