### ISSUE TITLE
Error on select existing item from collection

### ISSUE THREAD

**Issue by Chernitsov** [directus/directus#9095]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

In a collection which is recursive related with hisself & used as singleton collection i receive an error if i try to add an existing item.

<img width="1792" alt="Bildschirmfoto 2021-10-23 um 15 32 02" src="https://user-images.githubusercontent.com/43566674/138559523-bb7958d9-60b2-475f-855e-2687a6e6e664.png">

### To Reproduce

1. Create a collection with following props/fields:
<img width="1527" alt="Bildschirmfoto 2021-10-23 um 15 59 05" src="https://user-images.githubusercontent.com/43566674/138559744-630bac28-9535-4526-b8a0-f2b6a206f089.png">

2. Create a root collection item, some collection items & set the sort of root collection to be first
3. Treat this collection as single object
4. Go to collection & try to add an existing item 

### Errors Shown

<img width="1792" alt="Bildschirmfoto 2021-10-23 um 15 32 13" src="https://user-images.githubusercontent.com/43566674/138559528-dc8187c6-dfac-4d13-acbc-7e806636074a.png">

### What version of Directus are you using?

9.0.0-rc.99

### What version of Node.js are you using?

12

### What database are you using?

Postgres 13

### What browser are you using?

Chrome 95.0.4638.54

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by Chernitsov** [comment]
What i try to do is, set a collection (Navigation) to singleton to avoid display the layout view and show directly the first collection item as root-item which have a tree-field (recursively related to his own Collection "Navigation") .. Is it in generally possible to use a collection by this way? 

I dont really want to use this collection as singleton, i want only the effect of displaying the first item. I think that was the problem, but regardless of it, it shouldnt display an error anyway.. 

This should be an approach to implement a multi layer navigation in a most clean way to modify, is there another way to realize a multilayer navigation?

**Comment by rijkvanzanten** [comment]
> I dont really want to use this collection as singleton, i want only the effect of displaying the first item. I think that was the problem, but regardless of it, it shouldnt display an error anyway..

> This should be an approach to implement a multi layer navigation in a most clean way to modify, is there another way to realize a multilayer navigation?

I'd personally probably go with a regular collection, and then use filters to only show the  menu items that don't have a "parent_item" themselves 👍🏻 

As for the original bug report, this problem doesn't seem to exist anymore in the latest version 🙂
