### ISSUE TITLE
New System Thumbnail and Image Interface Preview

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#9162]
Source image (landscape):

![og-image](https://user-images.githubusercontent.com/522079/138915648-182fbd1a-cf10-4e39-86f3-f12b8a255d2f.png)

Full width preview:

![Screen Shot 2021-10-26 at 11 53 47 AM](https://user-images.githubusercontent.com/522079/138915771-1253910e-050f-4ff1-bf44-51338addb1fc.png)

The problem is that Directus first creates a square cropped thumbnail... and then sets this to `cover` within the interface. This double crops it and looks horrible. We need to add a second system thumbnail that is set to contain (800 wide by 450 tall, ~60% quality, no cropping) and add an Interface option for fit: `cover` (or `crop`?) and `contain` (centered)... both of these would use the new un-cropped system thumbnail.

**Comment by azrikahar** [comment]
cc @licitdev

**Comment by licitdev** [comment]
@benhaynes Is this what you're looking for?

<img width="650" alt="Screenshot 2021-11-08 at 7 14 27 PM" src="https://user-images.githubusercontent.com/26413686/140732496-3c000aa2-61d3-43a0-950c-12ef285cd95a.png">

**Comment by benhaynes** [comment]
@licitdev Yes! That solves one issue, which is that the thumbnail was double-cropping... thank you!

The other issue is that this version still crops the top and bottom. I think we want to give users the option to show an uncropped version, centered, and with "letter-boxing" to fill in the sides. To enable this uncropped option, I think we'll need to generate a _second_ system thumbnail that uses "contain".

This would also allow the File Library to have an option controlling "Crop" / "Contain".

Does that make sense?

**Comment by benhaynes** [comment]
Oh, I just realized we already have a BUNCH of system thumbs!! We can just use these, but should add options to the Interface/Layout for which you want.

https://github.com/directus/directus/blob/main/api/src/constants.ts#L3-L28

**Comment by benhaynes** [comment]
Aaaand, hopefully this helps, it should close this issue (although I'd like to have the same thing for the Card Layout).

https://github.com/directus/directus/pull/9628

**Comment by licitdev** [comment]
@benhaynes Tested your fix, works very well! 👍🏻👍🏻

> Aaaand, hopefully this helps, it should close this issue (although I'd like to have the same thing for the Card Layout).

Not sure if this is what you meant, the crop / contain setting exists in the Card Layout.

<p float="left">
  <img width="217" alt="image" src="https://user-images.githubusercontent.com/26413686/140879195-5a91c80c-2f7f-45ae-8f32-14b552697522.png">
  
  <img width="144" alt="image" src="https://user-images.githubusercontent.com/26413686/140879656-64d7ef4e-ebf7-469f-be41-6e805d0682ab.png">
  
  <img width="144" alt="image" src="https://user-images.githubusercontent.com/26413686/140879681-e5d14ee8-569d-4a44-80f7-b296fd18087b.png">
</p>

**Comment by benhaynes** [comment]
Haha, of course it is... 🤦 

This issue is all set then!
