### ISSUE TITLE
Markdown Interface Updates

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#9167]
* `Editor` button text should be `Edit`
* Edit and Preview buttons should stay highlighted (Primary color) based on current mode
* Need to add an interface option for Font type (same as other interfaces) for Sans, Serif, Mono. Should we have two? One for editor and one for preview? I think both should default to `sans` (like this GitHub editor).
* **All** WYSIWYG CSS should get copied from the HTML WYSIWYG editor... which has correct styling for headings, body copy, etc.
* The Custom Block option (see below) should have placeholders in each input that explain how they can be used. Not sure if we should make the fields conditional based on inline/block.
* It would be nice if you could control the action buttons (which are on/off) like in the HTML WYSIWYG
* Let's use the `format_size` icon for headings

![Screen Shot 2021-10-26 at 12 28 37 PM](https://user-images.githubusercontent.com/522079/138921548-45868722-962a-4012-8874-aad60f3921bd.png)
![Screen Shot 2021-10-26 at 12 37 39 PM](https://user-images.githubusercontent.com/522079/138922985-f4131c75-1564-4566-a196-1b32e84fe30d.png)

**Comment by rclee91** [comment]
Hi @azrikahar , thanks for your feedback!

I've managed to change the preview text area to use the selected font, but I'm still having trouble with the editor text area. I'm wondering if it has to do with using `CodeMirror`? 

I've been reading the [CodeMirror manuscript](https://codemirror.net/doc/manual.html#styling), and it mentions we could override the font styles in the codemirror.css file, but I'm not sure how to achieve this dynamically. 

Any help would be appreciated!

**Comment by rclee91** [comment]
Hi @benhaynes , I have managed to complete everything else, except for 

>     * It would be nice if you could control the action buttons (which are on/off) like in the HTML WYSIWYG

For now, I am not entirely sure how to approach this.
Is it alright if I submit a pull request to have my code reviewed for the other completed parts first?

**Comment by rclee91** [comment]
I managed to think of a way to work with toolbars. 
I've submitted a pull request for this issue for review.
Thanks!

**Comment by benhaynes** [comment]
Awesome... we'll take a look!
