### ISSUE TITLE
Data validation fail on reference data model has no feedback on main view

### ISSUE THREAD

**Issue by jianliao** [directus/directus#9176]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

1. Main data model is referenced to another data model through M2A.
2. On referenced data model, it has two fields are required
3. When user create a invalid referenced data model instance through drawer, save operation on main data model would not show the data validation fail alert, but observed 400 bad request in browser console.

### To Reproduce

https://user-images.githubusercontent.com/1207520/138954093-b4824b62-05ff-4337-bec0-546df7d109f2.mp4

### Errors Shown

Extracted below error json response from Chrome debug console.
```
{
   "errors":[
      {
         "message":"\"text\" is required",
         "extensions":{
            "code":"FAILED_VALIDATION",
            "field":"text",
            "type":"required"
         }
      },
      {
         "message":"\"link\" is required",
         "extensions":{
            "code":"FAILED_VALIDATION",
            "field":"link",
            "type":"required"
         }
      }
   ]
}
```
### What version of Directus are you using?

9.0.0-rc.99

### What version of Node.js are you using?

16.10.0

### What database are you using?

Postgres 10

### What browser are you using?

Chrome

### What operating system are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by u12206050** [comment]
I have the same issue, whereby I have a uniqueness on two columns that I implemented in mysql using 
`ALTER TABLE `scans` ADD UNIQUE `ticket` (`activity`, `person`);`
However in Directus when I try saving I do not get any feed back in the UI, have to open up console and look at network response to see this:

![Screenshot 2021-11-10 at 10 26 29](https://user-images.githubusercontent.com/6641242/141086606-60c020bc-3fc1-4e6a-b022-004864a55a91.png)

**Comment by jianliao** [comment]
Hi,
Is there any update on this issue? I am still able to reproduce this issue on the latest v9.5.2.
