### ISSUE TITLE
directus tries to update computed field when using translation interface

### ISSUE THREAD

**Issue by wc-matteo** [directus/directus#9196]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

when trying to update a translation (through the translation interface in the "main" collection) that contains a computed field, directus tries to save the value of the computed field to the database

### To Reproduce

- create collection `foo`
- add `translations` field to `foo` _(as of v99 I need to manually setup the translation, cause of a [known issue](https://github.com/directus/directus/issues/9069); but that doesn't influence this issue; I'm using the default names for the setup)_
- add standard field `bar` to `foo_translations` of type `string`
- create an entry of `foo` with a value of your choosing for `bar` (1 language is enough)
![image](https://user-images.githubusercontent.com/10562635/139084307-c0ef7d91-d7ec-4ae4-a1df-eb4aab3f9e0b.png)

- add computed field `baz` to `foo_translations` through sql (`ALTER TABLE foo_translations ADD baz AS('imcomputed!')`)
- click on the field in the data model to configure it through directus (don't need to change anything)
- try to edit the entry of `foo` you inserted changing the value of `bar`
![image](https://user-images.githubusercontent.com/10562635/139075082-072c3100-66a2-44e7-bbc3-5d864506cb89.png)

- the entry cannot be edited and an error is shown:

### Errors Shown

![image](https://user-images.githubusercontent.com/10562635/139073918-2f2b962b-4ffa-4e19-8f38-cccae8a082f9.png)

```json
{
  "message": "update [foo_translations] set [foo_id] = @p0, [languages_id] = @p1, [bar] = @p2, [baz] = @p3 where [id] in (@p4);select @@rowcount - The column \"baz\" cannot be modified because it is either a computed column or is the result of a UNION operator.",
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR"
  }
}
```

### What version of Directus are you using?

v9.0.0-rc.99

### What version of Node.js are you using?

n/a

### What database are you using?

mssql 2016

### What browser are you using?

chrome

### What operating system are you using?

win 10

### How are you deploying Directus?

k8s

**Comment by wc-matteo** [comment]
@Oreilles this is not fixed in rc.101. The computed column is still sent to the api and the api tries to save the value to the db (same repro)

**Comment by rijkvanzanten** [comment]
This should be resolved as part of https://github.com/directus/directus/pull/13998 as this bug is the same as https://github.com/directus/directus/issues/13765 afaict 🙂
