### ISSUE TITLE
Ability to grant read access on folder collection is missing

### ISSUE THREAD

**Issue by d1rOn** [directus/directus#9207]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

In rc.98 we was able to grant access to folders the same as collections at `Roles & Permissions` page.
Since rc.99 folders are hidden on this page, and all users having role with no `Admin Access` option enabled can't see collections on the `Collections` page that are children of any folder.

### To Reproduce

1. Create a role with Admin Access option disabled.
2. Create a folder `Foo` and a collection `Bar`. Assign a `Bar` collection to `Foo` folder as a child.
3. Grant read access on newly created role to `Bar` collection.
4. Log in as user with new role. You will not see any collection on Collections page.

### What version of Directus are you using?

v9-rc.99

### What version of Node.js are you using?

14.17.2

### What database are you using?

MySQL 8.0.19

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally

**Comment by Slations** [comment]
@rijkvanzanten just on the issue I reported mine also included the fact the role based collection navigation is also not working, had a skim through this bug didn't see it but thought i'd mention it

**Comment by danieljwestman** [comment]
I'm running on the latest, v9.0.0.

Roles that isn't admin can't see any collections that belongs to a collections folder. I've tried with a new role with all permissions for everything but not admin access. All collections is shown in the Content module as they should, but when I create a collections folder and move the collections in there they all disappear. If I add admin access they come back.

_**Conclusion: A user must have admin access to be able to see/navigate collections in folders.**_

@rijkvanzanten is there any workaround for this? I recently sponsored the dynamic user variables for permissions/filtering, but it's useless when our content structure (multiple folders) is gone...

**Comment by d1rOn** [comment]
> I'm running on the latest, v9.0.0.
> 
> Roles that isn't admin can't see any collections that belongs to a collections folder. I've tried with a new role with all permissions for everything but not admin access. All collections is shown in the Content module as they should, but when I create a collections folder and move the collections in there they all disappear. If I add admin access they come back.
> 
> _**Conclusion: A user must have admin access to be able to see/navigate collections in folders.**_
> 
> @rijkvanzanten is there any workaround for this? I recently sponsored the dynamic user variables for permissions/filtering, but it's useless when our content structure (multiple folders) is gone...

For now, there are two variants: grant read access through API or directly by changing database.

**Comment by danieljwestman** [comment]
> For now, there are two variants: grant read access through API or directly by changing database.

Yes, I see that. But thats not going to work in the long run, just for testing. I think it should be possible to do in the GUI again (like in rc.98)

**Comment by benhaynes** [comment]
> @rijkvanzanten is there any workaround for this? I recently sponsored the dynamic user variables for permissions/filtering, but it's useless when our content structure (multiple folders) is gone...

I believe @d1rOn mentioned a workaround (have not tested), but this issue is here to correct the root problem and update the GUI. No estimates on resolution time though.

**Comment by danieljwestman** [comment]
> I believe @d1rOn mentioned a workaround (have not tested), but this issue is here to correct the root problem and update the GUI. No estimates on resolution time though.

Yes, that works. You can adjust the permissions through the API.

Is there any (good) reason why this was removed from the UI?

**Comment by benhaynes** [comment]
It comes from solving this issue: https://github.com/directus/directus/discussions/8922

Perhaps @rijkvanzanten can shed some light...

**Comment by rijkvanzanten** [comment]
> Is there any (good) reason why this was removed from the UI?

Yes, to prevent people from accidentally configuration read/create/update/delete permissions for the folder collections. The main problem here is that the collection response is based on whether or not you have read permission to any of the items within, but seeing that this folder type collection doesn't hold any items, it's a little strange. For example, there's no point in choosing what "fields" you have read access to in a folder collection, as those don't have any fields to begin with. 

@benhaynes We should think through whether we want to keep relying on permissions for these folders, by having a dedicated role-settings permissions-row for these folder types with a simple "read on or off" toggle rather than the full normal permissions, or if we want to base the read access of a folder type based on whether or not you have read permission to any of the nested collections 🤔 

The latter option prevents some maybe unnecessary config?

**Comment by danieljwestman** [comment]
> > Is there any (good) reason why this was removed from the UI?
> 
> Yes, to prevent people from accidentally configuration read/create/update/delete permissions for the folder collections. The main problem here is that the collection response is based on whether or not you have read permission to any of the items within, but seeing that this folder type collection doesn't hold any items, it's a little strange. For example, there's no point in choosing what "fields" you have read access to in a folder collection, as those don't have any fields to begin with.
> 
> @benhaynes We should think through whether we want to keep relying on permissions for these folders, by having a dedicated role-settings permissions-row for these folder types with a simple "read on or off" toggle rather than the full normal permissions, or if we want to base the read access of a folder type based on whether or not you have read permission to any of the nested collections 🤔
> 
> The latter option prevents some potentially unnecessary config?

I'd vote for a read on or off. Simple and intuitive. I think it would be more confusing to rely on nested collections permissions.

**Comment by rijkvanzanten** [comment]
@danieljwestman What should happen to the nested collections you have read access to when you don't have access to read the folder? Right now, the folder is only used for presentation in the app 🤔

**Comment by danieljwestman** [comment]
@rijkvanzanten You should still have permission to the nested collections, but not visible in the native content module? Only presentation as you said. In my case I reach these collections through other modules.

**Comment by azrikahar** [comment]
Perhaps we can also frame it as referencing typical ACLs (might be a stretch here) where an admin can knowingly deny a whole folder, despite the role has permissions to the child collections. Just in a presentation/content-module sense of course.

**Comment by Slations** [comment]
@rijkvanzanten @benhaynes Could we not just bring back collection navigation on a role basis like before with some setting which mean if you change one it syncs them all as I used to find it handy that different departments have different layouts to suite there needs but I cannot do this now. Although nobody can use the system now as they cannot see the items so rather a big problem!

**Comment by benhaynes** [comment]
Hey @Slations — let's keep the discussions organized on their appropriate tickets. We'll be working on that feature soon, but it's not on our immediate docket, as we'll be focusing on stability first.

**Comment by Oreilles** [comment]
Could we enable editing the folders' `read` property as `yes/no` instead of hiding them ? This will fit https://github.com/directus/directus/issues/9207#issuecomment-965410455 's view, only making the tree structure presentational in the app.

**Comment by benhaynes** [comment]
> or if we want to base the read access of a folder type based on whether or not you have read permission to any of the nested collections

@rijkvanzanten I'm gravitating to this option now. Basically, hide the folder if there's nothing visible in it. Could add a `visible`/`hidden` permission toggle for each collection so it's customizable per role.

**Comment by danieljwestman** [comment]
> ```json
> {
> 	"collection": "<enter your folder name here>",
> 	"action": "read",
> 	"role": "<enter the role UUID here>"
> }
> ```

This workaround doesn't work anymore... For a while we could add permissions for collection folders with the API, but now the folders (and it's collections) are always hidden for none-admins... Why? Has this been changed again? Something going on? @rijkvanzanten @benhaynes 

As for now none of our users with app access (only one admin) can do anything in the app... We have a very structured folder organization.

**Comment by christianrr** [comment]
As for now, the use of folders make the app pretty much unusable for non-admin users (since all collections disappear). That's pretty severe in my opinion, since removing the folder structure to fix this issue is not a valid option for me.

I would vote for a short-term fix as in #10005 (thanks @nazarhanov). Please merge asap.

On a more long-term side of things, it would be great to incorporate folders into the permissions system.

**Comment by benhaynes** [comment]
I don't think this PR is the ideal fix, but we'll be getting this resolved in today's release. CC: @rijkvanzanten

**Comment by danieljwestman** [comment]
> @benhaynes I don't think this PR is the ideal fix, but we'll be getting this resolved in today's release. CC: @rijkvanzanten

A fix today sounds great! We're pretty stuck here...
