### ISSUE TITLE
m2m interface bugs

### ISSUE THREAD

**Issue by d1rOn** [directus/directus#9210]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

1. Interface does not rendering any content if related item was just added/selected but current changes are not submitted.
2. Interface does not rendering new Directus translations display or any other display if related collection has a translations setupped with that display, and m2m interface display template configured on translations or translations.[child] field.
3. Under the same conditions as in the (2), editing of item of related collection is impossible because of it content fields are displayed empty.

### To Reproduce

1. Create a collection `bar`.
2. Create a `bar.translations` field. (It can be a little bit difficulty because of #9069)
3. Create field `title` in `bar_translations` collection.
4. Set up a translations display on `bar.translations` field with display template `{{title}}`.
5. Create a collection `foo`.
6. Create a m2m field `foo.bars` and set up it interface display template to `{{id}}`.
7. Create an item of `bar` collection with filled `translations.title` field.

### Issue 1
Let's start to create an item of `foo` collection. After selecting of `bar` item with drawer and clicking Save button, the interface will render an empty block until we will click on Save of our `foo`-item.

![image](https://user-images.githubusercontent.com/26179694/139159833-8fd9b7c6-d5bd-40db-8223-206dd3e37ce7.png)

**Now we need to change a `foo.bars` field interface settings with display template `{{translations}}` or `{{translations.title}}`.**

### Issue 2

Open recently created `foo`-item. m2m interface don't rendering any content. A rendering of Directus translation display was expected. This worked correctly in earlier versions of Directus.

![image](https://user-images.githubusercontent.com/26179694/139160197-6938497e-dae1-4d91-b87e-5d8fe2cd32cc.png)

### Issue 3

Let's open a drawer with our `bar`-item. `title` input is empty for all languages.

![image](https://user-images.githubusercontent.com/26179694/139160874-25836c1b-dec2-4c7d-9466-bfae9f01aa57.png)

### DB dump
[directus_test.zip](https://github.com/directus/directus/files/7429876/directus_test.zip)
Credentials: admin@example.com:nyoJilRh1F3r

### What version of Directus are you using?

v9-rc.99

### What version of Node.js are you using?

14.17.2

### What database are you using?

MySQL 8.0.19

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally

**Comment by Toilal** [comment]
I try to use Directus for the first time, it seems great. But I hit the first issue too. 

I have installed development environment and really happy to see it's written with vue 3, so I started to debug and it seems the problem lies here https://github.com/directus/directus/blob/f1f2d2895575b617f72ce67d93bd5d213477de57/app/src/displays/related-values/related-values.vue#L4

I suppose `type` prop is expected to be 'm2m', but it's value is `alias`. So vue doesn't loop on item array to render each item, but tries to render the array as an object.

**Comment by d1rOn** [comment]
@rijkvanzanten, can we re-open this issue, or would it be better to open a new one?

**Comment by rijkvanzanten** [comment]
@d1rOn The other two issues already have open issues: https://github.com/directus/directus/issues/6293 & https://github.com/directus/directus/issues/8872 👍🏻

**Comment by HemboPagi** [comment]
Hello

I run into the same issue with directus 9.7.1

<img width="760" alt="Screenshot 2022-03-28 at 11 10 51" src="https://user-images.githubusercontent.com/95413906/160354837-074924f3-38aa-4af2-bf74-ac87bf3f3bfd.png">

I am using m2m relationship to reference back to the same collection.

H
