### ISSUE TITLE
Page not found when trying to edit an item with a "collection" property

### ISSUE THREAD

**Issue by sebj54** [directus/directus#9227]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I have a collection called "products" and another one called "collections". These two collections are related (a product has one collection).

When trying to access a product (click on it to edit the item), the "page not found" error is shown. 

### To Reproduce

Create two Directus collections:

- collections
- products

Create a "collections" item and a product. Try to access the product again.

### Errors Shown

No error is shown in the console nor from the API but I tried to debug it and found that the error is cause by an hard check on the collection attribute:

![image](https://user-images.githubusercontent.com/5880435/139406122-920eefc7-62fa-4380-b3f6-91e9439ba80b.png)

![image](https://user-images.githubusercontent.com/5880435/139407685-384593d1-bc7a-473b-9e3a-191e479ea4ac.png)

I know it's minified code but it looks like this middleware:

https://github.dev/directus/directus/blob/037fbd231af76fb5246c458018c311fdf29b3460/api/src/middleware/collection-exists.ts#L19

I think a simple fix would to replace this line:

```ts
if (!req.params.collection) return next();
```

by this one (or something similar to test the string type):

```ts
if (!req.params.collection || typeof req.params.collection !== 'string') return next();
```

### What version of Directus are you using?

RC 99

### What version of Node.js are you using?

14.18.1

### What database are you using?

Postgres 11

### What browser are you using?

Firefox

### What operating system are you using?

Windows 10

### How are you deploying Directus?

locally and on Render.com

**Comment by Oreilles** [comment]
Mayeb related to https://github.com/directus/directus/issues/9182

**Comment by micheljacquot34** [comment]
I had the same problem in v99. 
So I did not use a Collection called collections, as it seems to interfere with internal naming.

**Comment by Oreilles** [comment]
Bug introduced in https://github.com/directus/directus/pull/8695, commit https://github.com/directus/directus/pull/8695/commits/da39f1c67060aa00afc3549e5f9f23ecbfa0ef32:

https://github.com/directus/directus/blob/e3bfe69de312f900aacd1b744c895e15e7f88f1f/app/src/composables/use-item/use-item.ts#L295-L297

I did some good ol' console-logging and `response.data.data.collection` never exists, whether it's a `get` , a `put` and a system collection or not. Never exists, unless the collection has a field named `collection`. And if that field isn't a string, this will crash.

**Comment by rijkvanzanten** [comment]
cc @paescuj

**Comment by sebj54** [comment]
@Oreilles Actually I think collections like `directus_fields` (which have a `collection` column) would have a value for `response.data.data.collection`, like my custom `products`  collection has this column. I didn't test it though.

**Comment by paescuj** [comment]
Thanks for reporting! I'm going to take a look into this right now 👍
