### ISSUE TITLE
json fields doesn't show the save document option

### ISSUE THREAD

**Issue by potros** [directus/directus#9245]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

json fields doesn't show the save document option when i type it's not show the green save option it still gray in the ui

### To Reproduce

use the latest directus version and add a json field and try to add and edit column 3 or more times

### Errors Shown

no errors are shown

### What version of Directus are you using?

letest

### What version of Node.js are you using?

17

### What database are you using?

sqlite

### What browser are you using?

chrome

### What operating system are you using?

linux

### How are you deploying Directus?

vps

**Comment by Oreilles** [comment]
If you're using the Code interface, the icon will stay gray until your input is valid JSON.
You can you online JSON validation tool like https://jsonlint.com/ to verify that.
Can you confirm that the icon stays grey even when your value is valid json ?
