### ISSUE TITLE
Cannot edit field translations in rc.100

### ISSUE THREAD

**Issue by neo7-studio-web** [directus/directus#9253]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When updating a field translation, there is no change.

### To Reproduce

Go to an existing field, edit a translation, save. Go to collection (e.g new or existing item), value was not edited.

### Errors Shown

No error shown

### What version of Directus are you using?

v9.0.0.rc-100

### What version of Node.js are you using?

14.16.1

### What database are you using?

MySQL 5.7.14

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### How are you deploying Directus?

locally

**Comment by Oreilles** [comment]
Probably related to https://github.com/directus/directus/issues/9182

**Comment by cosminepureanu** [comment]
I have the same issue with rc.100
I noticed that after editing the field via the App, no PATCH requests are being made, so the change doesn't seem to go to the API.
I tried editing fields like placeholder or default value which don't require relations.

**Comment by neo7-studio-web** [comment]
> 
> 
> Probably related to #9182

Hope it helps : the problem was not there in rc.99

**Comment by Oreilles** [comment]
@neo7-studio-web #9182 wasn't either 😉

**Comment by micheljacquot34** [comment]
Hi!

I created a new instance of Directus, using v100.

The Translations relation does not work:
when you create a new item in the Collection, the Translations don't show any item, like it does in v99. 

It display a cryptic mention: Enter Raw value.

DB: Psql
Chrome
