### ISSUE TITLE
SSO causes user password error

### ISSUE THREAD

**Issue by cdwmhcc** [directus/directus#9272]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

`Wrong username or password`

## 01 SSO newly created user

1. Use google openid to verify login and create a new user.
2. Log in to the user and set a password for the user.
3. Log in with the user's email address and password.

## 02 Users that already exist in the database

1. Modify the directus_users data table, and specify the Provider as google for the existing users, and the External Identifier as the user email
2. Log in with the user's email address and password.

The following error will be prompted at this time:

![image](https://user-images.githubusercontent.com/8030134/139579616-6dd43699-84ca-4bd0-9252-c5a82e04c44c.png)

### What version of Directus are you using?

v9.0.0 rc100

### What version of Node.js are you using?

16.11.0

### What database are you using?

mysql 8.0

### What browser are you using?

chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally

**Comment by aidenfoxx** [comment]
I'm going to guess you've not set the `AUTH_GOOGLE_IDENTIFIER_KEY="email"`? Try that and the users you updated in the DB should work.

**Comment by aidenfoxx** [comment]
This isn't a bug. If a user has an oauth provider, they cannot log in with the regular auth flow.
