### ISSUE TITLE
Cannot add/select a group field the new field creation flow

### ISSUE THREAD

**Issue by flayks** [directus/directus#9275]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

It is just impossible to select a group field with the new field creation flow

https://user-images.githubusercontent.com/273716/139580303-acb79806-5f06-4071-8b4d-d994ffe6d096.mov

### To Reproduce

Pick a group item when creating a field

### Errors Shown

```
vendor.6ad70522.js:5 TypeError: Cannot read properties of undefined (reading 'removeSchema')
    at zV (index.6cd9935b.js:21)
    at Proxy.update (index.6cd9935b.js:21)
    at Proxy.<anonymous> (vendor.6ad70522.js:9)
    at YF.set [as _setter] (index.6cd9935b.js:21)
    at YF.set value [as value] (vendor.6ad70522.js:2)
    at Proxy.f (index.6cd9935b.js:21)
    at onClick (index.6cd9935b.js:21)
    at Mh (vendor.6ad70522.js:5)
    at U1 (vendor.6ad70522.js:5)
    at HTMLButtonElement.r (vendor.6ad70522.js:5)
```

### What version of Directus are you using?

9.0.0-rc.100

### What version of Node.js are you using?

16.13.0

### What database are you using?

MySQL

### What browser are you using?

Brave

### What operating system are you using?

macOS Monterey (12)

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
Seems to work on my end. Would you mind trying a different browser or even a different machine? Just as an attempt to rule out browser-related possibilities.

**Comment by flayks** [comment]
Same behaviour on Safari 15.1 and Firefox 93.
In on the latest Macbook Pro 16", seems to be the same on an M1 Mac Mini.

**Comment by torstenhoegel** [comment]
same here, tested on docker & digitalocean deploys

**Comment by danilopolani** [comment]
Have you updated your project from 99 to 100? If you did, maybe there's something cached somewhere? Like npm cache or whatever, because I've tried [running directus from source](https://docs.directus.io/contributing/running-locally/) and the issue doesn't happen. 

Furthermore, does it happen with every schema or just a specific one?

**Comment by azrikahar** [comment]
This is odd. Can confirm it happens for the released rc.100 (tested on Docker), but can also confirm everything works fine when running Directus from source locally.

**Comment by mikkel1156** [comment]
I also ran into this one on my environment on Docker, running PostgreSQL and Redis. Running on Debian 10
