### ISSUE TITLE
Graphql selection sets starting with "__" (e.g. __typename) not removed from selection nodes in aggregated queries

### ISSUE THREAD

**Issue by 8byr0** [directus/directus#9278]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When a graphql client (tested apollo and urql) is configured to use a normalized cache, aggregation queries fail due to the `__typename` field being added to the query (standard behavior - used to cache efficiently). 
TLDR: this would not be an issue if the behaviour was the same whatever query you run (e.g. fail for all or work for all)

I have multiple concerns about this. 
First, this issue only occurs with aggregation queries. 
A normal query like this one will run properly (even if `__typename` is being added to the body):
```graphql
worktime { 
    duration
    id 
    __typename
}
```

On the other hand, an aggregation query with `__typename` added automatically will fail:
```graphql
 worktime_aggregated(
    filter: { billable: { _eq: true } } }
  ) {
    __typename
    sum {
      duration
      __typename
    }
  }
 ```

Second, the error triggered for this missing field is the whole SQL query:
```
select sum(\"duration\") as \"sum->duration\", sum(\"__typename\") as \"sum->__typename\" from \"worktime\" where \"worktime\".\"billable\" = $1 limit $2 - column \"__typename\" does not exist
```
Isn't there a vulnerability with:
- SQL request coming to the client (could be a generic error like "INTERNAL SERVER ERROR"?) - or maybe this is due to a kind of debug mode?
- the request being executed with a payload not checked before ? I mean... Wouldn't it be better to have a checkup on the data coming from the client instead of waiting for the request to fail?

### To Reproduce

- create a collection (named `worktime` in my example above)
- add two fields, one which is countable (`duration`: int) and another one for filtering (`billable`: boolean)
- create a few entries(2-3 is enough) with random data
- use whatever graphql client (graphiql, apollo devtools...) or a react app to run the two queries above

**note**: Running them with or without an actual client lib (apollo or urql) is not a requirement to reproduce, the queries I pasted are exactly as they've been triggered by both these tools

- see the errors returned by graphql server

Additionally if you use graphiql which loads schema from server, `__typename` is neither present in standard query nor aggregation one.

As a reminder here are the queries:
```graphql
query {
worktime { 
    duration
    id 
    __typename
}
 worktime_aggregated(
    filter: { billable: { _eq: true } } }
  ) {
    __typename
    sum {
      duration
      __typename
    }
  }
}
```

### Errors Shown

> select sum(\"duration\") as \"sum->duration\", sum(\"__typename\") as \"sum->__typename\" from \"worktime\" where \"worktime\".\"billable\" = $1 limit $2 - column \"__typename\" does not exist

### What version of Directus are you using?

v9.0.0-rc100

### What version of Node.js are you using?

14.17.0

### What database are you using?

Postgres 12

### What browser are you using?

Brave (chromium)

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by 8byr0** [comment]
After investigation I found that the code managing "__typename" behaviour is only available for fields (not selectionSets).
Defined here :
https://github.com/directus/directus/blob/ded3d4b1412a4da711dfaa31e72a4fd4e7e31acc/api/src/services/graphql.ts#L1467

I tested locally to filter on selectionSet nodes like so:
```javascript
query.aggregate[aggregateProperty] =
  aggregationGroup.selectionSet?.selections
    // This is my patch
    .filter((selectionNode) => !selectionNode.name.value.startsWith("__"))
    .map((selectionNode) => {
      selectionNode = selectionNode as FieldNode;
      return selectionNode.name.value;
    }) ?? [];
```

What are your thougts? I'm quite new to directus so I may miss important things / usecases that would be broken due to such update.

If you feel it's ok to update like this I can submit a PR!

**Comment by jaycammarano** [comment]
I think it's worth a PR.

**Comment by rijkvanzanten** [comment]
Agreed! We shouldn't try using any `__` prefixed fields in the directus data flow when it's coming in from GraphQL

**Comment by rijkvanzanten** [comment]
> SQL request coming to the client (could be a generic error like "INTERNAL SERVER ERROR"?) - or maybe this is due to a kind of debug mode?

Error stacks are only shown to admin users 👍🏻 

> the request being executed with a payload not checked before ? I mean... Wouldn't it be better to have a checkup on the data coming from the client instead of waiting for the request to fail?

Directus currently only checks against the permission rules configured, but not against the columns that exist (yet). Admin users have full access, so can end up requesting non-existing fields 👍🏻

**Comment by 8byr0** [comment]
There you go! 
First PR out there 🚀

**Comment by 8byr0** [comment]
> > SQL request coming to the client (could be a generic error like "INTERNAL SERVER ERROR"?) - or maybe this is due to a kind of debug mode?
> 
> Error stacks are only shown to admin users 👍🏻
> 
> > the request being executed with a payload not checked before ? I mean... Wouldn't it be better to have a checkup on the data coming from the client instead of waiting for the request to fail?
> 
> Directus currently only checks against the permission rules configured, but not against the columns that exist (yet). Admin users have full access, so can end up requesting non-existing fields 👍🏻

Seems fine to me. I'm currently migrating a big strapi project (company management platform) to directus and I made all testings without permissions restrictions.
