### ISSUE TITLE
Unable to delete collection field due to postgis_version() issue

### ISSUE THREAD

**Issue by nathanhere** [directus/directus#9279]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Unable to delete collection field due to error below:
```
database  | 2021-10-31 20:07:50.621 UTC [43] ERROR:  function postgis_version() does not exist at character 8
database  | 2021-10-31 20:07:50.621 UTC [43] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
database  | 2021-10-31 20:07:50.621 UTC [43] STATEMENT:  select postgis_version()
```

UI displays "Network Error" message.

### To Reproduce

Create a field in a collection. Attempt to delete. Encounter "Network Error" on UI.

### Errors Shown

Console:
```
database  | 2021-10-31 20:07:50.621 UTC [43] ERROR:  function postgis_version() does not exist at character 8
database  | 2021-10-31 20:07:50.621 UTC [43] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
database  | 2021-10-31 20:07:50.621 UTC [43] STATEMENT:  select postgis_version()
```

UI displays "Network Error" message.

### What version of Directus are you using?

v9.0.0-rc.100

### What version of Node.js are you using?

v16.13.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker Compose

**Comment by nathanhere** [comment]
**Caveat**: The attempted field to delete is a WYSIWYG field created using vRC-98. I was unable to delete the field using that version, and unable to delete the field after upgrading to vRC-100. I am currently unable to reproduce the issue with new fields :(

**Comment by nathanhere** [comment]
It seems I am also unable to hide the affected field, with the same error messages printed in the console and displayed in the UI.

**Comment by fitu86** [comment]
Try deleting it by api, then enter the application and in the collection configuration, you will see the field that you deleted still there but with a yellow triangle, but it will let you delete it.

**Comment by nathanhere** [comment]
@fitu86 That seemed to work without having to deal with any yellow triangle. Not sure if this should be left open for further investigation?
