### ISSUE TITLE
Bug with M2O aggregation

### ISSUE THREAD

**Issue by iksent** [directus/directus#9283]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

1) I have 2 models:
- Contest
- Subgovernance

2) Each Contest has one Subgovernance

3) Try to fetch aggregated contests for definite subgovernance

4) You'll get MYSQL error: `ER_NON_UNIQ_ERROR`

### To Reproduce

GraphQL:

```
query subgov($slug: String) {
  contest_aggregated(filter: {subgov: {slug: {_eq: $slug}}}) {
    countDistinct { # <<<<< THIS CAUSES THE PROBLEM
      id
    }
  }
}
```

Error:

```
select count(distinct `id`) as `countDistinct->id` from `contest` left join `subgov` as `mofez` on `contest`.`subgov` = `mofez`.`id` where (`mofez`.`slug` = 'main') limit 100 - ER_NON_UNIQ_ERROR: Column 'id' in field list is ambiguous
```

I believe ID from ```count(distinct `id`)``` must be prefixed with table name.

### What version of Directus are you using?

RC100

### What version of Node.js are you using?

v14.17.0

### What database are you using?

MariaDB

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

locally (production)

**Comment by joselcvarela** [comment]
Hello @iksent 
I am trying to reproduce but without success. It is working for me.
Can you share your MariaDB version?
I am using `mariadb:10.6` dockerized with node 16.10.0

<img width="512" alt="Screenshot 2021-11-01 at 17 39 39" src="https://user-images.githubusercontent.com/14039341/139715490-baf9f73b-576f-4afc-9e86-b69eafbf6885.png">
