### ISSUE TITLE
The multi-part identifier "cc.is_computed" could not be bound.

### ISSUE THREAD

**Issue by junaidbilal** [directus/directus#9302]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I'm getting this error while I have just installed directus 9.0.0 rc.100. Database using MSSQL 2019. I believe this error coming from SQL Server.

### To Reproduce

npx directus start

### Errors Shown

RequestError:
                        SELECT
                                c.TABLE_NAME as table_name,
                                c.COLUMN_NAME as column_name,
                                c.COLUMN_DEFAULT as default_value,
                                c.IS_NULLABLE as is_nullable,
                                c.DATA_TYPE as data_type,
                                c.CHARACTER_MAXIMUM_LENGTH as max_length,
                        cc.is_computed as is_generated,
                                pk.PK_SET as column_key,
                                COLUMNPROPERTY(OBJECT_ID(c.TABLE_SCHEMA + '.' + c.TABLE_NAME), c.COLUMN_NAME, 'IsIdentity') as is_identity,
                                COLUMNPROPERTY(OBJECT_ID(c.TABLE_SCHEMA + '.' + c.TABLE_NAME), c.COLUMN_NAME, 'IsComputed') as is_generated
                        FROM
                                [idata].INFORMATION_SCHEMA.COLUMNS as c
                        LEFT JOIN (
                                SELECT
                                        PK_SET = CASE WHEN CONSTRAINT_NAME LIKE '%pk%' THEN 'PRIMARY' ELSE NULL END,
                                        TABLE_NAME,
                                        CONSTRAINT_CATALOG,
                                        COLUMN_NAME
                                FROM [idata].INFORMATION_SCHEMA.KEY_COLUMN_USAGE
                        ) as pk
                        ON [c].[TABLE_NAME] = [pk].[TABLE_NAME]
                        AND [c].[TABLE_CATALOG] = [pk].[CONSTRAINT_CATALOG]
                        AND [c].[COLUMN_NAME] = [pk].[COLUMN_NAME]
                        INNER JOIN
                                [idata].INFORMATION_SCHEMA.TABLES as t
                        ON [c].[TABLE_NAME] = [t].[TABLE_NAME]
                        AND [c].[TABLE_CATALOG] = [t].[TABLE_CATALOG]
                        AND [t].TABLE_TYPE = 'BASE TABLE'
                         - The multi-part identifier "cc.is_computed" could not be bound.
    at RequestTokenHandler.onErrorMessage (E:\Webs\test\idata\node_modules\tedious\lib\token\handler.js:362:21)
    at Readable.<anonymous> (E:\Webs\test\idata\node_modules\tedious\lib\token\token-stream-parser.js:26:33)
    at Readable.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Readable.push (internal/streams/readable.js:204:10)
    at next (internal/streams/from.js:88:29)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'EREQUEST',
  number: 4104,
  state: 1,
  class: 16,
  serverName: '.\\SQLEXPRESS2019',
  procName: '',
  lineNumber: 9
}

### What version of Directus are you using?

9.0.0 -rc.100

### What version of Node.js are you using?

14.17

### What database are you using?

MSSQL 2019

### What browser are you using?

Chrome

### What operating system are you using?

Windows Server

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/directus/pull/9260
