### ISSUE TITLE
Problems in displaying and interfacing O2M translation labels

### ISSUE THREAD

**Issue by stouch** [directus/directus#9329]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I've got a O2M field of a collection A that points to a translated collection B. 
When I list the items of the collection A, it does not display correctly the related items of the O2M field.

### To Reproduce

I've got 3 collections : 
- _Menus_
- _Menus Items_ (translations)
- _Menus Items Translations_ (label : String)

My _Menus_ has `menus_items` O2M field, that points to _Menus Items_, with `translations`/`Label` as Display Template.

Here is what I got : 

![Capture d’écran 2021-11-01 à 17 57 50](https://user-images.githubusercontent.com/17531455/139751298-f951d5e6-527c-4152-acd3-4750c3fdc37d.png)
![Capture d’écran 2021-11-01 à 17 57 56](https://user-images.githubusercontent.com/17531455/139751301-d05fa017-13cc-4378-abf0-42499677afca.png)
e.

### What version of Directus are you using?

rc99

### What version of Node.js are you using?

latest

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
What's your configuration for the display template?

**Comment by stouch** [comment]
Label for _Menus Items Translations_ , and Translations/Label for _Menus Items_ 

I also tried just Translations for _Menus Items_

**Comment by rijkvanzanten** [comment]
Ah I meant the configuration for the _Display Template_ option of the one-to-many interface 👍🏻

**Comment by stouch** [comment]
> My _Menus_ has menus_items O2M field, that points to _Menus Items_, with translations/Label as Display Template.

The display template of the O2M `menus_items` is :
-> translations/Label

(translations are the translations of _Menus_items_)

**Comment by u12206050** [comment]
I think I have a similar issue, I have a simple collection with translations. I have a translated title on a resource and want to have it in the display on the collection page within the cards but it just shows as blank.

I am able to select it like so:
![Screenshot 2021-12-14 at 09 35 48](https://user-images.githubusercontent.com/6641242/145962531-9b327e70-b914-4295-8c26-dc2ddc33425f.png)

But it just shows `--`

**Comment by kuuroo3** [comment]
Similar thing here.

I have a collection with translations. Inside that collections item, everything looks correct.
The collections page shows:
![image](https://user-images.githubusercontent.com/43739995/146327704-6334b74c-2846-403b-887e-82b9693c7e90.png)
![image](https://user-images.githubusercontent.com/43739995/146328071-bed3713b-46aa-4177-84e3-a2bc11f258d2.png)

Maybe that is intended but I would very much want to see the translated title (or other fields) instead of "1 Item" which doesn't provide me any benefit at all.. :D

-----

When linking that collection to another via M2O it shows --
![image](https://user-images.githubusercontent.com/43739995/146327550-a78fcfc3-c354-47ad-9669-fb505fb165e5.png)
![image](https://user-images.githubusercontent.com/43739995/146327854-6d6d2932-9a7b-4395-b09d-cd20277c1134.png)

**Comment by kuuroo3** [comment]
> Similar thing here.
> 
> I have a collection with translations. Inside that collections item, everything looks correct. The collections page shows: ![image](https://user-images.githubusercontent.com/43739995/146327704-6334b74c-2846-403b-887e-82b9693c7e90.png) ![image](https://user-images.githubusercontent.com/43739995/146328071-bed3713b-46aa-4177-84e3-a2bc11f258d2.png)
> 
> Maybe that is intended but I would very much want to see the translated title (or other fields) instead of "1 Item" which doesn't provide me any benefit at all.. :D

Ah I just realised with this answer (https://github.com/directus/directus/issues/10401#issuecomment-996202922) that the display template changes the view in the overview section, so I could successfully change that part for me.
![image](https://user-images.githubusercontent.com/43739995/146515155-f5651edd-7b9e-46d3-a1e5-c48394b006b5.png)

Unfortunately this doesn't seem to work with linked colelctions. 
> When linking that collection to another via M2O it shows -- ![image](https://user-images.githubusercontent.com/43739995/146327550-a78fcfc3-c354-47ad-9669-fb505fb165e5.png) ![image](https://user-images.githubusercontent.com/43739995/146327854-6d6d2932-9a7b-4395-b09d-cd20277c1134.png)

**Comment by jaycammarano** [comment]
> I think I have a similar issue, I have a simple collection with translations. I have a translated title on a resource and want to have it in the display on the collection page within the cards but it just shows as blank.
> 
> I am able to select it like so: ![Screenshot 2021-12-14 at 09 35 48](https://user-images.githubusercontent.com/6641242/145962531-9b327e70-b914-4295-8c26-dc2ddc33425f.png)
> 
> But it just shows `--`

This is definitely still happening. 
<img width="249" alt="Screen Shot 2022-01-26 at 3 00 02 PM" src="https://user-images.githubusercontent.com/67079013/151238198-b211a38b-9758-4249-b22e-e19279b3552a.png">

<img width="193" alt="Screen Shot 2022-01-26 at 3 00 07 PM" src="https://user-images.githubusercontent.com/67079013/151237873-0cb9385e-0d2e-492e-ad85-4f36314afe01.png">

**Comment by u12206050** [comment]
Any update on this. A bummer Directus supports translations but only half of the displays work.
Works in collection view, but not in detail (o2m, m2m)
