### ISSUE TITLE
Missing documentation: Custom Vue Components

### ISSUE THREAD

**Issue by V1210N** [directus/directus#9364]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

The current documentation pages are missing the section about the custom Vue components in its API Reference area.

You can find it in the Wayback Machine, but not in the current docs:
https://web.archive.org/web/20210420151007/https://docs.directus.io/getting-started/introduction/
Go to Reference > Vue Components

Given that this documentation still stands, then it should be included.

### To Reproduce

Access the current documentation at:
https://docs.directus.io/getting-started/introduction/

Look at the sections present in the side navigation. Notice how none of them address Directus' custom Vue components.

### What version of Directus are you using?

latest

### What version of Node.js are you using?

.

### What database are you using?

.

### What browser are you using?

.

### What operating system are you using?

.

### How are you deploying Directus?

.

**Comment by benhaynes** [comment]
They have been moved to the wiki: https://github.com/directus/directus/wiki

Please let us know if there are actual broken links in the docs. We've added a note about these files moving to the top of the Contributing section's overview.
