### ISSUE TITLE
Can't edit translation field

### ISSUE THREAD

**Issue by pierre-H** [directus/directus#9398]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When I try to edit anything in a translation field, I've got an error `can't convert undefined to object`:

### To Reproduce

https://user-images.githubusercontent.com/6079305/140048402-b79da62b-4511-4082-9cc8-acbd2ed68e69.mp4

### Errors Shown

```json
{
  "fileName": "http://localhost:3103/admin/index.6cd9935b.js",
  "lineNumber": 21,
  "columnNumber": 292630,
  "message": "can't convert undefined to object"
}
```

According to me, this correspond to https://github.com/directus/directus/blob/f1f2d2895575b617f72ce67d93bd5d213477de57/app/src/modules/settings/routes/data-model/field-detail/store/index.ts#L210

### What version of Directus are you using?

9.0.0-rc100

### What version of Node.js are you using?

16.13.0 from Docker

### What database are you using?

Mariadb 10.6.4

### What browser are you using?

Firefox 94 and Chrome 95.0.4638.54

### What operating system are you using?

Windows 10

### How are you deploying Directus?

Docker

**Comment by danilopolani** [comment]
@pierre-H I think the issue has already been resolved (https://github.com/directus/directus/issues/9253) but will be released in `rc101`

**Comment by pierre-H** [comment]
I am not sure : in the issue #9253, no error is shown. This is not my case : i've got an error.

**Comment by rijkvanzanten** [comment]
This was fixed in https://github.com/directus/directus/pull/9324 👍🏻
