### ISSUE TITLE
Can't edit a field comment

### ISSUE THREAD

**Issue by pierre-H** [directus/directus#9399]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When I try to edit a field comment, the save button doesn't activate.

### To Reproduce

https://user-images.githubusercontent.com/6079305/140048922-b2827f91-accc-4467-aa91-337ff20969e6.mp4

### What version of Directus are you using?

9.0.0-rc100

### What version of Node.js are you using?

16.13.0 from Docker

### What database are you using?

Mariadb 10.6.4

### What browser are you using?

Firefox 94 and Chrome 95.0.4638.54

### What operating system are you using?

Windows 10

### How are you deploying Directus?

Docker

**Comment by Oreilles** [comment]
Does the save button activate when you edit another field property ? (for example, `Obligatoire`)
Does this bug affects only the collection you shown in video or every collection ?

**Comment by pierre-H** [comment]
> Does the save button activate when you edit another field property ? (for example, Obligatoire)
No, but I discovered that mapping informations are empty. I think the problem comes from here. I will check that.

![image](https://user-images.githubusercontent.com/6079305/140067099-525990db-de85-41ec-851b-9ee37942ddca.png)

**Comment by rijkvanzanten** [comment]
This was resolved in https://github.com/directus/directus/pull/9324
