### ISSUE TITLE
Display mode Related Values fails when rendering number

### ISSUE THREAD

**Issue by Toilal** [directus/directus#9406]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

render-template.vue may call translate function with a number. This cause an error in console and editor becomes stale (impossible to close it).

https://github.com/directus/directus/blob/62e5d22e3b76664b1c53e6883ffc93385bfe3e64/app/src/views/private/components/render-template/render-template.vue#L17

### To Reproduce

- Define a field display with Related Values and reference a number field in the template.
- Edit an item from this collection.

### Errors Shown

```
translate-literal.ts:6 Uncaught (in promise) TypeError: literal.startsWith is not a function
    at Proxy.translate (translate-literal.ts:6)
    at render-template.vue:17
    at renderList (runtime-core.esm-bundler.js:5763)
    at Proxy._sfc_render (render-template.vue:3)
    at renderComponentRoot (runtime-core.esm-bundler.js:460)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:4227)
    at ReactiveEffect.run (reactivity.esm-bundler.js:160)
    at setupRenderEffect (runtime-core.esm-bundler.js:4353)
    at mountComponent (runtime-core.esm-bundler.js:4136)
    at processComponent (runtime-core.esm-bundler.js:4094)
```

### What version of Directus are you using?

v9.0.0-rc.100 (main branch)

### What version of Node.js are you using?

v16.13.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying Directus?

locally (dev)

**Comment by Toilal** [comment]
This kind of error could be catched at build time with [vue-tsc](https://www.npmjs.com/package/vue-tsc)

**Comment by benhaynes** [comment]
Probably completely unrelated, but in case it's not... does this template control number formatting for the "Formatted Value" Display? Some types are missing formatting (the comma in the `Price`).
![Screen Shot 2021-11-03 at 9 26 27 AM](https://user-images.githubusercontent.com/522079/140068563-45020183-92ea-4583-a2ce-c2dacd53528d.png)

**Comment by Toilal** [comment]
It's doesn't seems so. 

But this kind of issue could occur if `parts` computed property has `undefined` component property where it should be defined, or if  `getDefaultDisplayForType` function doesn't work as expected.
