### ISSUE TITLE
Github OAuth2 fails

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [directus/directus#9410]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Following on the latest version and trying to add github as oauth provider (https://docs.directus.io/configuration/config-options/#sso-oauth2-and-openid) using the shown config and adapting the following:

Censored my custom client id and secret
      AUTH_GITHUB_CLIENT_ID: "XXXXXXX"
      AUTH_GITHUB_CLIENT_SECRET: "XXXXXXX"
      AUTH_GITHUB_ALLOW_PUBLIC_REGISTRATION: "true"

And using in the github OAuth Application settings (which should maybe mentioned when giving an example):

Homepage:
http://192.168.178.35/myapp/api

Authorization callback URL:
http://192.168.178.35/myapp/api/auth/login/github/callback

Will result in the following error on the console:
myappdirectus | 13:10:31 ⚠️  Failed to find user identifier for provider "github"
myappdirectus | 13:10:31 ⚠️  Invalid user credentials.

### To Reproduce

Following on the latest version and trying to add github as oauth provider (https://docs.directus.io/configuration/config-options/#sso-oauth2-and-openid) with using the docker-compose example

### Errors Shown

myappdirectus | 13:10:28 ✨ request completed POST 400 /auth/refresh 12ms
myappdirectus | 13:10:29 ✨ request completed GET 304 /admin/img/icons/android-chrome-192x192.png 7ms
myappdirectus | 13:10:29 ✨ request completed GET 304 /admin/assets/logo-light.1a93a59d.svg 2ms
myappdirectus | 13:10:29 ✨ request completed GET 304 /admin/img/icons/safari-pinned-tab.svg 2ms
myappdirectus | 13:10:29 ✨ request completed GET 304 /auth 22ms
myappdirectus | 13:10:30 ✨ request completed GET 302 /auth/login/github?redirect=http://192.168.178.35/myapp/api/admin/login?continue 26ms
myappdirectus | 13:10:31 ⚠️  Failed to find user identifier for provider "github"
myappdirectus | 13:10:31 ⚠️  Invalid user credentials.
myappdirectus | 13:10:31 ✨ request completed GET 302 /auth/login/github/callback?code=c578601bebaca5406589 500ms
myappdirectus | 13:10:31 ✨ request completed GET 304 /admin/login?reason=INVALID_USER 2ms
myappdirectus | 13:10:31 ✨ request completed GET 304 /admin/index.6cd9935b.js 9ms
myappdirectus | 13:10:31 ✨ request completed GET 304 /admin/assets/vendor.fe7856f0.css 11ms
myappdirectus | 13:10:31 ✨ request completed GET 304 /admin/assets/vendor.6ad70522.js 10ms
myappdirectus | 13:10:31 ✨ request completed GET 304 /admin/assets/use-sync.042e848f.js 2ms
myappdirectus | 13:10:31 ✨ request completed GET 304 /admin/assets/index.440d8ed4.css 5ms
myappdirectus | 13:10:31 ✨ request completed GET 200 /extensions/interfaces/index.js 39ms
myappdirectus | 13:10:31 ✨ request completed GET 200 /extensions/panels/index.js 56ms
myappdirectus | 13:10:31 ✨ request completed GET 200 /extensions/displays/index.js 57ms
myappdirectus | 13:10:31 ✨ request completed POST 400 /auth/refresh 62ms
myappdirectus | 13:10:31 ✨ request completed GET 200 /extensions/layouts/index.js 55ms
myappdirectus | 13:10:31 ✨ request completed GET 200 /extensions/modules/index.js 59ms
myappdirectus | 13:10:31 ✨ request completed GET 304 /admin/img/icons/android-chrome-192x192.png 2ms
myappdirectus | 13:10:31 ✨ request completed GET 304 /server/info?limit=-1 36ms
myappdirectus | 13:10:31 ✨ request completed GET 304 /admin/assets/Inter-Medium.a4e1e7e6.woff2 1ms
myappdirectus | 13:10:31 ✨ request completed GET 304 /admin/assets/logo-light.1a93a59d.svg 2ms
myappdirectus | 13:10:31 ✨ request completed GET 304 /admin/assets/Inter-Bold.f0f54a06.woff2 8ms
myappdirectus | 13:10:31 ✨ request completed GET 304 /admin/assets/Inter-Black.5ab3de07.woff2 9ms
myappdirectus | 13:10:31 ✨ request completed GET 304 /admin/assets/Inter-SemiBold.af44b8a2.woff2 11ms
myappdirectus | 13:10:31 ✨ request completed GET 304 /admin/assets/material-icons-outline.63af6c49.woff2 12ms
myappdirectus | 13:10:31 ✨ request completed GET 304 /admin/img/icons/safari-pinned-tab.svg 3ms
myappdirectus | 13:10:31 ✨ request completed GET 304 /auth 32ms

### What version of Directus are you using?

directus/directus:9.0.0-rc.100

### What version of Node.js are you using?

12

### What database are you using?

sqlite

### What browser are you using?

Brave (Chrome)

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by NilsBaumgartner1994** [comment]
> Or you can use your github username as an identifier by setting `AUTH_GITHUB_IDENTIFIER_KEY="login"`.

Wow thanks, yeah that is pretty studip to be honest. This works now.

**Comment by NilsBaumgartner1994** [comment]
But even if i set "AUTH_<PROVIDER>_SCOPE" to email or user, then the email should be always send or not ?

**Comment by NilsBaumgartner1994** [comment]
Well sorry to tell you, is it normal that firstname and lastname arent also sent even which scope for full private profile informations ?

**Comment by aidenfoxx** [comment]
@NilsBaumgartner1994 It's a quirk of github, and out of our control. They don't sent the email regardless of scope: https://stackoverflow.com/questions/35373995/github-user-email-is-null-despite-useremail-scope

> Well sorry to tell you, is it normal that firstname and lastname arent also sent even which scope for full private profile informations ?

That is intentional. Every OAuth implementation is different, and there is no guarantee on field naming, so we don't set full profile information for OAuth providers. Only email and identifier, if available.

OpenID services will get full profile information, as they use a standardized profile format.

**Comment by NilsBaumgartner1994** [comment]
> @NilsBaumgartner1994 It's a quirk of github, and out of our control. They don't sent the email in the profile response regardless of scope: https://stackoverflow.com/questions/35373995/github-user-email-is-null-despite-useremail-scope
> 
> We would have to add a special call `/user/emails` JUST for github, and that isn't a good solution.
> 
> > Well sorry to tell you, is it normal that firstname and lastname arent also sent even which scope for full private profile informations ?
> 
> That is normal for OAuth. Every OAuth implementation is different, and there is no guarantee on field naming, so we don't set full profile information for OAuth providers. Only email and identifier, if available.
> 
> OpenID services will get full profile information, as they use a standardized profile format.

Thank you for your time :-)
