### ISSUE TITLE
Cannot create new unique field on empty collection

### ISSUE THREAD

**Issue by ThaDaVos** [directus/directus#9411]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I am not able to create a new string based unique field on my just created collection, it's grayed out...
![image](https://user-images.githubusercontent.com/5251028/140068873-0a685df2-e6b8-4151-bfd3-40a18a69f113.png)

### To Reproduce

Create new collection, add new field and try to enable unique

### Errors Shown

No errors shown

### What version of Directus are you using?

v9.0.0-rc.100

### What version of Node.js are you using?

v14.18.1

### What database are you using?

MySql 5.7.x

### What browser are you using?

Firefox Developer Edition

### What operating system are you using?

Windows 11

### How are you deploying Directus?

Running on a VPS through a Nginx Proxy to get SSL

**Comment by ThaDaVos** [comment]
Checking the data sent to the front-end and corresponding code, one should be able to toggle the checkbox:

Data:
![image](https://user-images.githubusercontent.com/5251028/140074035-25aec79e-f730-433d-a3f0-d69f766f2571.png)

Code Fragment of field:
https://github.com/directus/directus/blob/84275b1642a34543ab4bb86fed41a53f9f3aa8df/app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-schema.vue#L282-L284

https://github.com/directus/directus/blob/84275b1642a34543ab4bb86fed41a53f9f3aa8df/app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-schema.vue#L144

I followed the code through the application and the checkbox should not be disabled:

![image](https://user-images.githubusercontent.com/5251028/140074529-059c2c5b-3118-4ab1-a88a-142511e6b42b.png)

But it is... maybe something went wrong with setting up the prop?

probably going wrong as `<component>` is used?
https://github.com/directus/directus/blob/84275b1642a34543ab4bb86fed41a53f9f3aa8df/app/src/components/v-checkbox/v-checkbox.vue#L1-L20

**Comment by azrikahar** [comment]
Unfortunately can't seem to reproduce this on my end. Would you mind upgrading to the latest version `v9.0.0` and let us know how it goes?

**Comment by ThaDaVos** [comment]
Consider this fixed in the latest version - in `v9.0.0-rc.100` it was still broken
