### ISSUE TITLE
Docs Homepage Overflow

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#9439]
Not properly responsive on smaller viewports.

![](https://cdn.discordapp.com/attachments/741327526240059483/905542562801123378/IMG_20211027_181833.jpg)

**Comment by rijkvanzanten** [comment]
What's with the grain :o Is that an android screenshot thing?

**Comment by MiniDigger** [comment]
All phones nowadays have some kind of filter like that if you want, sadly only some don't apply it to screenshots.
It's something like blue light filter, bedtime mode, night mode, whatever

**Comment by rijkvanzanten** [comment]
Interesting! From the iOS side, i'm just used to the one that makes it more yellow, but I'm not sure if that actually shows up in screenshots 🙂
