### ISSUE TITLE
Error applying schema when constraint name generated is 63 characters

### ISSUE THREAD

**Issue by faridsaud** [directus/directus#9444]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [ ] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When you have an association between 2 tables with large names (constraint name generated is 63 characters long), the constraint name generated through the command `npx directus schema snapshot` not always generate the same name inside the snapshot.yaml file. This leads to directus identifying that there is an update when applying the same schema twice instead of detecting that there are no changes to apply.

Here are examples of 2 different constraint name generated for the same relationship after: generating schema, applying schema, generating schema.
`videos_page_translations_asset_tab_videos_page_tr__fvcco_foreig` (first schema generated)
`videos_page_translations_asset_tab_videos_page_tr__xvosv_foreig` (second schema generated)

I can provide a simplified snapshot if needed.

PD: This is not the latest version of Directus, it is 9.0.0-rc.99. I will run the same test on the latest version and update my post.

### To Reproduce

1. Create 2 tables with large names.
2. Create a relationship of M2O

### Errors Shown

No errors in the console, just that Directus is trying to apply an update, that is not necessarily something new.

### What version of Directus are you using?

9.0.0-rc.99

### What version of Node.js are you using?

v16.12.0

### What database are you using?

Postgres 13

### What browser are you using?

NA

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
Good one! We should update the name generation of that key to use a hash of the table names involved instead of a random string to ensure the same output for the same input 👍🏻

**Comment by rijkvanzanten** [comment]
In here: https://github.com/directus/directus/blob/main/api/src/utils/get-default-index-name.ts
