### ISSUE TITLE
Presentation link field not editable

### ISSUE THREAD

**Issue by federicocappellotto97** [directus/directus#9452]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [ ] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I created a presentation link with v9.0.0-rc.99 and now with v9.0.0-rc.100 i can't edit the url of this field
This is the field:
<img width="940" alt="Schermata 2021-11-03 alle 10 03 32" src="https://user-images.githubusercontent.com/63153191/140041133-b6c4c8b1-1544-4d1c-8f42-1aee75a8841e.png">
This is the screen if i try to edit it, there is no url parameter to edit.
If i add a new interface, nothing appears, the button remains the same

### To Reproduce

Create a presentation link then try to edit it or add a button to it

### What version of Directus are you using?

9.0.0-rc.100

### What version of Node.js are you using?

14.18.1

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

macOS Monterey (12)

### How are you deploying Directus?

Locally

**Comment by danilopolani** [comment]
The fields flow has changed since RC100 and, for example, Presentation Links stopped work (at least for me): https://github.com/directus/directus/issues/9457

I'd wait for that issue to be solved/commented before trying to edit your link

**Comment by rijkvanzanten** [comment]
We'll track this in #9457 as the fix is the same 👍🏻
