### ISSUE TITLE
Failed import in RC.101

### ISSUE THREAD

**Issue by TomS-** [directus/directus#9456]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Since I've updated to RC.101 I'm not able to build my `SvelteKit` project. The errors I'm receiving are:
```
> Named export 'Directus' not found. The requested module '@directus/sdk' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@directus/sdk';
const { Directus } = pkg;
```
By trying to do a default import I get the following:
```
1: import Directus from '@directus/sdk';
          ^
2: 
3: export const directus = new Directus('https://******.***/');
> 'default' is not exported by node_modules/@directus/sdk/dist/sdk.esm.js, imported by src/lib/directus.js
```

### To Reproduce

Try to build Directus SDK with SvelteKit (Vite). I'm unsure if this effects everything, but judging by the error I assume it would.

### What version of Directus are you using?

RC.101

### What version of Node.js are you using?

14.17.6

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Digital Ocean

**Comment by rijkvanzanten** [comment]
It looks like SvelteKit w/ Vite might import the CJS version instead of the ESM build of the SDK. Not sure why though. Any thoughts @nickrum / @joselcvarela ?

**Comment by TomS-** [comment]
It's worth noting that downgrading to RC.100 works, so it's an issue that has changed between RC.100 and RC.101.

**Comment by rijkvanzanten** [comment]
Oh yeah I know exactly what change caused this 😁 (this one: https://github.com/directus/directus/pull/9443) That being said, the question is _why_ that as we (afaik) do the correct thing of pointing to the ESM version on `import` usage: https://github.com/directus/directus/pull/9443/files#diff-77164cc5c071d1488e1cf72c0f91fdd99dd8976edb5004c83198bbd517039572R10-R12

**Comment by nickrum** [comment]
@TomS- Which version of SvelteKit are you using? I can't reproduce this using `@sveltejs/kit@1.0.0-next.193` and a newly scaffolded Svelte project.

**Comment by TomS-** [comment]
> @TomS- Which version of SvelteKit are you using? I can't reproduce this using `@sveltejs/kit@1.0.0-next.193` and a newly scaffolded Svelte project.

I don't get the error until I try to build the project to `adapter-static`.
