### ISSUE TITLE
Insights - Time Series panel - Group precision "week" not working

### ISSUE THREAD

**Issue by faberv** [directus/directus#9495]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [x] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hello, I found little issue in new **Insight module**

When I create new **Time Series** panel with "**Week**" Group Precision - it has no effect on graph. Graph displays "day" precision instead:
![image](https://user-images.githubusercontent.com/2473221/140427877-5790fb6b-49e8-421d-b3ec-ab215e9b5bac.png)

This is JSON in **`options`** column saved to DB
```json
{
	"range": "1 year",
	"filter": { "datetime_paid": { "_nnull": true } },
	"function": "sum",
	"dateField": "datetime_paid",
	"precision": "week",
	"collection": "orders",
	"valueField": "final_price"
}
```

---

To be honest I think this is just a little something, but you should know about it.

### To Reproduce

1. Create new **Dashboard** in **Insights** module
2. Add new panel **Time Series** with "**Week**" Group precision
3. Graph will show day by day aggregation instead of week by week

### What version of Directus are you using?

9.0.0-rc.101

### What version of Node.js are you using?

17.0.1

### What database are you using?

MySQL 8.0.21

### What browser are you using?

Chrome

### What operating system are you using?

Linux 4.4.0-19041-Microsoft

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
Can confirm this on rc.101 from recent experience with Insights module. Thanks for the sharing the saved payload in the DB!
