### ISSUE TITLE
Simple hash function can generate negative hash

### ISSUE THREAD

**Issue by faridsaud** [directus/directus#9499]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The simple hash function added [here](https://github.com/directus/directus/pull/9448/files#diff-02702873f0ae928664ef62343467e5e643d0376250bf45503e4c9eb564ba57f3R5 can generate a negative hash which will have a length of 9 characters instead of 8. We just need to add Math.abs() on the return statement
```
return Math.abs(hash).toString(16);
```

### To Reproduce

Call the function getDefaultIndexName with the following arguments
```
getDefaultIndexName("foreign", "sell_landing_page_hero_carousel_slides", "sell_landing_page_translations")
```

### Errors Shown

Hash generated -652cafa6

### What version of Directus are you using?

main branch

### What version of Node.js are you using?

v16.13.0

### What database are you using?

Postgres (not needed)

### What browser are you using?

Edge (not needed)

### What operating system are you using?

macOS (not needed)

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
Easy bug, easy fix. Thanks for the heads up and solution 👍🏻
