### ISSUE TITLE
Cannot add any field to `group` fields

### ISSUE THREAD

**Issue by ThaDaVos** [directus/directus#9515]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

At the moment when I try to add a newly created field to a Group Field I get an internal server error as follows:
```Log
TypeError: Cannot read property 'slice' of undefined
    at foreignKeyViolation (/var/www/vhosts/v2/content-cms/node_modules/directus/dist/exceptions/database/dialects/mysql.js:132:37)
    at extractError (/var/www/vhosts/v2/content-cms/node_modules/directus/dist/exceptions/database/dialects/mysql.js:31:20)
    at translateDatabaseError (/var/www/vhosts/v2/content-cms/node_modules/directus/dist/exceptions/database/translate.js:47:53)
    at /var/www/vhosts/v2/content-cms/node_modules/directus/dist/services/items.js:332:72
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

### To Reproduce

1. Add Group Field to Collection
2. Create a new field or re-use an existing one
3. Drag it into the groups dropbox
4. Be pleased with an error

### Errors Shown

Directus Terminal:
```
TypeError: Cannot read property 'slice' of undefined
    at foreignKeyViolation (/var/www/vhosts/v2/content-cms/node_modules/directus/dist/exceptions/database/dialects/mysql.js:132:37)
    at extractError (/var/www/vhosts/v2/content-cms/node_modules/directus/dist/exceptions/database/dialects/mysql.js:31:20)
    at translateDatabaseError (/var/www/vhosts/v2/content-cms/node_modules/directus/dist/exceptions/database/translate.js:47:53)
    at /var/www/vhosts/v2/content-cms/node_modules/directus/dist/services/items.js:332:72
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Console just shows 500 error

### What version of Directus are you using?

v9.0.0

### What version of Node.js are you using?

v14.18.1

### What database are you using?

MySql 5.7.x

### What browser are you using?

Firefox Developer Edition

### What operating system are you using?

Windows 11

### How are you deploying Directus?

Running on a VPS through a Nginx Proxy to get SSL

**Comment by ThaDaVos** [comment]
Image of error:
![image](https://user-images.githubusercontent.com/5251028/140496246-1003ce5a-eba3-4a0e-ace4-ceef7be841c7.png)

**Comment by danilopolani** [comment]
I've tried with MySQL 5.7 and can't replicate the issue.
I guess it's because your Node version is old and an older version of `mysql` connector has been installed; note that Directus 9 requires [**node >= 16**](https://github.com/directus/directus/blob/main/package.json#L26) to run properly. Try to update Node.js and NPM (to 8), update your dependencies and see if it happens again.

**Comment by rijkvanzanten** [comment]
> Directus 9 requires node >= 16 to run properly.

@danilopolani This is actually not the case. The repo requires that for development purposes, as we rely on NPM workspaces to attach all the packages together. The production build runs on Node 12.20 and up 🙂

**Comment by rijkvanzanten** [comment]
I'm assuming it's the slices in here:

https://github.com/directus/directus/blob/a0e5d27a3aba5a3feb4500dd2e091a231851ddc1/api/src/exceptions/database/dialects/mysql.ts#L147-L165

@ThaDaVos What exact version of MySQL 5.7 are you running? We're bound to parsing the error strings coming from the database, and it sounds like your exact version throws errors in a slightly different format than expected.

**Comment by ThaDaVos** [comment]
I was wrong... it's not 5.7... it's:
`mysql  Ver 8.0.27 for Linux on x86_64 (MySQL Community Server - GPL)`

Apparently the system manager has updated it some time - thought it was 5.7

**Comment by rijkvanzanten** [comment]
I just tried reproducing this on a fresh installation of v9.4.2 running on MySQL 8.0.26 and I believe the issue mentioned in the original post is no longer in effect on the latest version:

https://user-images.githubusercontent.com/9141017/148297946-7fd6e337-13da-4cdd-b4f9-4d38b2e83cef.mp4

@ThaDaVos Can you confirm the issue still exists on your end? We'll reopen and continue investigating if so 🙂

**Comment by NecoHorne** [comment]
I am experiencing a similar issue with an instance that is connected to an RDS database. 

Directus: 9.4.3
Node: 14.16.0
OS: Linux 4.14.256-197.484.amzn2.x86_64
Database: RDS MySQL 8.0.23

Funnily enough I have another instance which has the same specs just the DB is running on an Ubuntu instance I spun up and this one is not showing any issues with the groups

Directus: 9.4.3
Node: 14.16.0
OS: Linux 4.14.256-197.484.amzn2.x86_64
Database: Ver 8.0.27-0ubuntu0.20.04.1 for Linux on x86_64
