### ISSUE TITLE
Quotes showing in M2O

### ISSUE THREAD

**Issue by supermx1** [directus/directus#9519]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I noticed after updating to v9.0.0, in my M2O field I realize there are quotes around the options.

![Screen Shot 2021-11-05 at 12 27 26 PM](https://user-images.githubusercontent.com/9326922/140503755-6ffa941d-c6bc-4bb1-8598-484e97e10a08.jpg)

This is unusual.

### To Reproduce

Same as above

### Errors Shown

None

### What version of Directus are you using?

v9.0.0

### What version of Node.js are you using?

16 and 14

### What database are you using?

10.4.17-MariaDB - Source distribution

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

Locally

**Comment by nazariydj** [comment]
same think on my end on very text field with raw display option set
