### ISSUE TITLE
Increase drag hitbox between field groups

### ISSUE THREAD

**Issue by jawngee** [directus/directus#9520]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

If you have multiple detail groups in a collection, re-ordering them is impossible as dragging one between others results in the group being nested in one or the other group.

![2021-11-05 18 55 49](https://user-images.githubusercontent.com/44449/140507045-9b65c78a-900e-4dcc-a445-b291479cb59c.gif)

### To Reproduce

Create a new collection and add 3 or more detail groups.  Try to reorder detail groups.

### What version of Directus are you using?

9.0.0-rc.101

### What version of Node.js are you using?

16.3

### What database are you using?

Postgres 12.2

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

Running local

**Comment by CYihan** [comment]
Hi,
If this is available, id like to contribute!

**Comment by benhaynes** [comment]
> Hi, If this is available, id like to contribute!

Go for it!! Thank you...
