### ISSUE TITLE
Scrollbar and template selectors steals header zindex

### ISSUE THREAD

**Issue by dimitrov-adrian** [directus/directus#9526]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

On code interface/component when scrolling the template selector and scrollbar thumb go over the header.

https://user-images.githubusercontent.com/1009639/140522772-3d80cc0f-fa46-40d2-a9e0-7440e883f68c.mov

Reproduced on Chrome 95, Safari 15

### To Reproduce

On css override on settings fill long text and scroll down.

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

16.12.0

### What database are you using?

mysql 5.7

### What browser are you using?

chrome

### What operating system are you using?

macOS Monterey (12)

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
Fixed in #9530
