### ISSUE TITLE
oAuth (facebook) profile request authorization header with 'bearer' instead of 'Bearer'

### ISSUE THREAD

**Issue by luisfontes** [directus/directus#9534]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hi, this one was hard to debug. I'm using facebook for social login/oAuth, I've set all the necessary env vars, tested my facebook app with other application, but could not make it work in Directus. Got a `Service returned unexpected response` every time I tried to signup with facebook.

Debugging I found that the error happens on the request for the profile data (from the env var AUTH_FACEBOOK_PROFILE_URL). Directus is making the request with a lower case `bearer` in the authorization header and facebook returns a Bad Request (400), throwing the unexpected response error. I've tested the exact request Directus is making (logged the request sent from openid-client in node_modules) in Insomnia/Postman and got the same Bad Request (400) when using `bearer` in lower case, but when using `Bearer` it works.

I don't know it this is a Directus issue or a openid-client issue.

### To Reproduce

- Set up facebook as an auth provider
- Try to sign in
- `Service returned unexpected response` error in the terminal

### Errors Shown

`Service returned unexpected response`

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

16.13

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
@aidenfoxx thoughts?

**Comment by aidenfoxx** [comment]
@rijkvanzanten This is all handled by `openid-client`. We just call the `userinfo()` function on the client and then it handles the request.

**Comment by aidenfoxx** [comment]
Okay, so here is some horrible irony for you. The reason the request is using "bearer" instead of "Bearer" is because it's what Facebook sends in their token response. By default `openid-client` would prefer "Bearer":

https://developers.facebook.com/docs/pages/access-tokens/

https://github.com/panva/node-openid-client/blob/b580dc53552ee080ed55af6c6897f54ff786d897/lib/client.js#L1064

One way to handle this would be for `openid-client` to capitalize the first letter of the `token_type`.

**Comment by jaycammarano** [comment]
>  We could also just send the `access_token` to `openid-client` instead of the full `tokenSet`.

That sounds doable. Just for facebook right?

**Comment by rijkvanzanten** [comment]
@jaycammarano I'd prefer not to have any service-specific glue code within Directus itself if at all possible. @aidenfoxx would that solution work for every vendor?

**Comment by aidenfoxx** [comment]
I would say "Just send the `access_token` all the time" will probably be sufficient. I think "Bearer" is the standard type for OAuth requests, so I don't foresee any issues with that. But who knows... maybe that breaks some other random vendor! 🤷

**Comment by batuhanbilginn** [comment]
Hey guys, is there any progress on this case? Unfortunately, I'm still not able to use Facebook oauth2 because of this issue? Thank you for help :)

**Comment by aidenfoxx** [comment]
@rijkvanzanten @jaycammarano This should do the trick #9598
