### ISSUE TITLE
unique field checkbox in field options always indeterminate

### ISSUE THREAD

**Issue by wc-matteo** [directus/directus#9540]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

![image](https://user-images.githubusercontent.com/10562635/140543930-a750ebd0-3d70-43b1-b5d2-892513f397fb.png)

### To Reproduce

try to set the value to true and save the field. The unique constraint is created but the checkbox is always indeterminate

![image](https://user-images.githubusercontent.com/10562635/140545340-c0c1b6a3-68da-46e5-8465-f5cf46392a4d.png)
this is the patch request. Is it correct that there are 2 fields for unique?

### What version of Directus are you using?

v9.0.0

### What version of Node.js are you using?

n/a

### What database are you using?

postgres 13.3

### What browser are you using?

chrome

### What operating system are you using?

win 10

### How are you deploying Directus?

k8s

**Comment by wc-matteo** [comment]
same issue in mssql but there the unique constraint is not created when flagging the checkbox and saving

**Comment by Beiri22** [comment]
I also experienced problems with the unique status. It's not just that the checkbox is indeterminate; but also that the unique constraint is not enforced. I am using postgres.

**Comment by azrikahar** [comment]
> this is the patch request. Is it correct that there are 2 fields for unique?

That is indeed not correct. Thank you for investigating it! It should be `is_unique`, but now the app saves it as `unique`. PR coming right up
