### ISSUE TITLE
Can't import `storage` with Typescript

### ISSUE THREAD

**Issue by andrenarchy** [directus/directus#9541]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Until recently, `storage` could be imported with Typescript (4.4.4) via
```typescript
import storage from 'directus/dist/storage'
```
but now it throws an error at run time (`Cannot find module 'node_modules/directus/dist/dist/storage.js'`).

### To Reproduce

The following code compiles but will throw an error when executed/imported.
```typescript
import storage from 'directus/dist/storage'

export interface File {
  storage: string
  filename_disk: string
}

export async function updateFileHashes(file: File) {
  const buffer = await storage.disk(file.storage).getBuffer(file.filename_disk)
  // ...
}
```

### Errors Shown

```
Error: Cannot find module '/home/andre/git-repos/ems-press/core/services/core-directus/node_modules/directus/dist/dist/storage.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:954:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:947:15)
    at resolveExports (node:internal/modules/cjs/loader:476:14)
    at Function.Module._findPath (node:internal/modules/cjs/loader:516:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:913:27)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/home/andre/git-repos/ems-press/core/services/core-directus/dist/lib/files/update-file-hashes.js:9:35)
    at Module._compile (node:internal/modules/cjs/loader:1095:14) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/andre/git-repos/ems-press/core/services/core-directus/node_modules/directus/package.json'
}
```

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

16.5.0

### What database are you using?

Postgresql 13

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying Directus?

locally

**Comment by andrenarchy** [comment]
Update: this might be related to the to the `exports` key introduced here: https://github.com/directus/directus/pull/9199.

This functionality is not yet supported in the stable Typescript version. It's available in the next RC (see https://www.typescriptlang.org/docs/handbook/esm-node.html) but I don't think it'd be good to expect TS users to upgrade to a non-stable version.

**Comment by nickrum** [comment]
@andrenarchy Yes, you are right, this is related to the addition of the `exports` field. Internal files now have to be imported without the `dist/`-part of the path: `import storage from 'directus/storage'`.

Unfortunately, we couldn't have waited with this until Typescript adds support for `exports` because it would have been a breaking change at any later point in time. Your best bet for now is to import storage as stated above and suppress the Typescript error using something like `// @ts-expect-error`.

**Comment by andrenarchy** [comment]
Maybe `storage` can just be exported from the index file (like `services`)? Or is it supposed to be an internal file? I'm wondering what the best practice is for working with storage in extensions...

**Comment by rijkvanzanten** [comment]
@andrenarchy I would prefer if we'd expose Storage straight through the parameters of the hooks/endpoints instead of relying on imports from the directus package itself. We won't treat anything that isn't explicitly exported to extensions as part of the public API, so I can't guarantee there won't be any breaking changes down the line in this sort of usage.

**Comment by andrenarchy** [comment]
That would indeed be even better! We'd just need to be able to import the type of `storage` so we can accept it as parameters elsewhere in our codebase.

**Comment by smilledge** [comment]
Here's my workaround if anyone else needs a solution...

Remove `dist` from any imports:
```typescript
import { flushCaches } from "directus/cache";
import { ExtensionContext } from "directus/types";
import getDatabase from "directus/database/index";
```

Add the following to `compilerOptions` in your `tsconfig.json`:
```
"paths": {
	"directus/*": ["./node_modules/directus/dist/*"]
}
```

If you're using jest you'll also need to add the following to `jest.config.js`
```typescript
moduleNameMapper: {
	"^directus/(.*)$": "<rootDir>/node_modules/directus/dist/$1",
},
```

**Comment by rijkvanzanten** [comment]
The OP is caused by TypeScript not yet supporting Node's exports syntax in package.json. The workaround above is the recommended solution. Alternatively, `// @ts-ignore` can be used
