### ISSUE TITLE
Maps Slightly Zooming Out on All Interactions

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#9543]
Not sure what's going on here, but on 9.0.0, every time I do anything in the Map Layout (zoom, pan, etc) the map spins (thinking) and then automatically zooms out a bit. Slowly working back to the global view. Weird!

https://user-images.githubusercontent.com/522079/140576336-cf876d34-7858-4c06-bb9e-0c4c1878f65d.mp4

Maybe this is related to clustering? Not sure why but my clustering is on but the checkbox is disabled (so I can't turn it off to try it without). I'd like to know why this is disabled and make sure we add a tooltip explaining why it can't be turned off.

CC @Oreilles

**Comment by azrikahar** [comment]
> Not sure why but my clustering is on

(In the context of the demo app)

Actually I turned it on via Presets just to experiment with it 😅 so it's definitely not something enabled by default in the Map layout or the codebase!

As for it being disabled, it should be due to here:

https://github.com/directus/directus/blob/be2d7b267d5dbc0212f64473774e7f1709a4a9c2/app/src/layouts/map/options.vue#L35

And that condition became true as there's no `geometryOptions.geometryType` in OP's scenario:

![image](https://user-images.githubusercontent.com/42867097/140615763-c037d5a2-79f6-49d2-a711-0ea4d1e160a8.png)

Setting it as `geometryOptions.geometryType && geometryOptions.geometryType !== 'Point'` seems to fix it, but maybe there's a better approach.

**Comment by benhaynes** [comment]
Ahh, good find! @Oreilles thoughts on that? I was confused because the demo _is_ using a "point"  location... right?

**Comment by benhaynes** [comment]
For the zooming, it does _not_ matter if clustering is on. The map _always_ zooms/centers on the current data... which is _very_ difficult to work with. We need to disable this, @Oreilles.

**Comment by Oreilles** [comment]
> Setting it as geometryOptions.geometryType && geometryOptions.geometryType !== 'Point' seems to fix it, but maybe there's a better approach.

There actually is, I made a mistake when refactoring the code in my latest commit and removed the line that set `geometryType` in `geometryOptions` so it was always undefined. I'll commit the fix when Ben's issue is solved too :)

@benhaynes Is your geometry field a native geometry, or a GeoJSON / CSV / WKT field ?

**Comment by benhaynes** [comment]
It's the `Locations` table in @azrikahar 's demo... "Geometry (All)". Is this what you're looking for?

![Screen Shot 2021-11-08 at 9 48 08 AM](https://user-images.githubusercontent.com/522079/140763223-031f0cdf-7cda-46dc-ba65-0187efa78e62.png)

**Comment by azrikahar** [comment]
Here's the detail of the field in `directus_fields`, hope it's helpful here:

![image](https://user-images.githubusercontent.com/42867097/140777817-34f0f967-57f1-410f-b13f-da38b3c94efa.png)

**Comment by Oreilles** [comment]
Thank you both!
So, here's where the problem come from. The map layout automatically adjust its position to fit the data whenever the user change the `collection`, `page`, `search` or `filter`.

On the other hand, Directus returns to page 1 whenever either of those change too. In previous versions, this was handled by the layout themselves, so I could add a special case to say "If the page is set to 1 automatically and *not* by the user, do not update the camera position". In newer versions, the check to go back to page 1 have been delegated to `useItems`:
https://github.com/directus/directus/blob/68cba874f6230eb2d3722bf3a9b7305dc81d4254/packages/shared/src/composables/use-items.ts#L80-L87

So the map layout does not know anymore whether that query change was automatic or user-initiated, and update its camera position in both cases. We'd need a way to change this...

**Comment by benhaynes** [comment]
Makes sense. Can we just remove all the "auto position" stuff? It could be nice to add in the future, but we should remove it until it works correctly. Hard to demo the map when it slowly zooms out all the time. 😆

**Comment by Oreilles** [comment]
Update: It actually was much simpler than that, pushing the fix in a sec 👍
