### ISSUE TITLE
Options for Formatted Value Display

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#9546]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Funded-%2300A156.svg" />](https://issuehunt.io/r/directus/directus/issues/9546)

### Discussed in https://github.com/directus/directus/discussions/9040

<div type='discussions-op-text'>

<sup>Originally posted by **benhaynes** October 21, 2021</sup>
Options for...
* Enable Links — (eg: url or email) when enabled, shows a `launch` icon (18px) on hover, clicking launches link
    * External links should auto open in new tab
* Enable Copy Button — when enabled, shows a `copy` icon (18px) on hover, clicking copies the value
* Better number formatting for `9,000`, not `9000` (could use locale for formatting)
    * Maybe we can pull this from the user locale?
* Prepend Text (useful for `$123,456`)
* Appended Text (useful for `123,456 Widgets`)
* Icon After — maybe conditionally disables when using link/copy?
* Conditional Formatting Repeater
    * Operator Dropdown
    * Value Input
    * Color Chooser
    * Icon Chooser</div>

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars.githubusercontent.com/u/522079?v=4' alt='benhaynes' width=24 height=24> benhaynes](https://issuehunt.io/u/benhaynes) ($50.00)
- $50.00 have been anonymously funded.
### Submitted pull Requests
- [#9773 Update formatted-value display](https://issuehunt.io/r/directus/directus/pull/9773)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/directus/directus/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by benhaynes** [comment]
Some design references:

![Screen Shot 2021-11-10 at 2 54 54 PM](https://user-images.githubusercontent.com/522079/141183963-ca71f13f-f2f8-4c17-88cb-54cd43bcd53e.png)

* Material design icons are set in 18px
* Icons are 2px right from the value
* Icons are 4px right of any previous icon

Let me know if you need any guidance on the interface options, @alejandro-tss!! ❤️

**Comment by alejandro-tss** [comment]
With this I have more than enough to start with, but I have some doubts that I leave here @benhaynes:

* Is the formatting of the numbers user defined or do we let them be displayed based on the current user's locale?
* Do the icons/buttons go at the end of the text or at the end of the cell space? I say this because, in a table it is very frequent that the texts have different sizes and appear in different positions.
* Do we allow links as phone number?
* Do we allow the output to be formatted dynamically, that would cover the case of append and prepend text and customize links. Example: https://example.com/{{value}}

**Comment by benhaynes** [comment]
Good questions!!

> Is the formatting of the numbers user defined or do we let them be displayed based on the current user's locale?

I think based on locale is best... no need for extra configurations.

> Do the icons/buttons go at the end of the text or at the end of the cell space? I say this because, in a table it is very frequent that the texts have different sizes and appear in different positions.

The end of the text. This is why I'd like to have the launch/copy icons on show on hover (except on touch devices), that way they never seem misaligned or add visual clutter... since you only see one at a time. The general "icon" would always be visible.

> Do we allow links as phone number?

I think so. The question is: will the admin set the link type (email, link, tel...) or can we pull that from the value with a regex or something?

> Do we allow the output to be formatted dynamically, that would cover the case of append and prepend text and customize links. Example: https://example.com/{{value}}

Ahh, that could work! Just a bit more work for users to remember to add `{{value}}`, and that no other variables are allowed. I'm fine thinking through this being a template string or two prefix/suffix fields.

**Comment by rijkvanzanten** [comment]
> Is the formatting of the numbers user defined or do we let them be displayed based on the current user's locale?

We can use `vue-i18n`s `n` function to automatically do that based on the user's locale 👍🏻 

> I think so. The question is: will the admin set the link type (email, link, tel...) or can we pull that from the value with a regex or something?

It'll have to be an option. Phone numbers come in all shapes and sizes, and we can't just assume that any number bigger than 3 digits is a phone number

**Comment by alejandro-tss** [comment]
@benhaynes, @rijkvanzanten I have created this PR: https://github.com/directus/directus/pull/9773
