### ISSUE TITLE
Use plain text displays in calendar layout

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#9560]
### Discussed in https://github.com/directus/directus/discussions/9559

<div type='discussions-op-text'>

<sup>Originally posted by **azrikahar** November  6, 2021</sup>
When we set translations fields as the display template, in this case `translations.title`, it shows up as undefined:

![image](https://user-images.githubusercontent.com/42867097/140617661-a0bb7e90-3aba-45b9-b960-ec8ba56ce9eb.png)

### To Reproduce

- Create an Articles collection with translations field

- Add `publish_date` datetime input to `articles` collection (for calendar view later)

- Add `title` string input to `articles_translations` collection

- Create new Article with publish date & title

- Go to Articles, set as calendar layout, set Display template as `Title`, start & end date field as `Publish Date`:
   ![image](https://user-images.githubusercontent.com/42867097/140617594-d8e57ca7-2521-4671-8435-8650a1b4b255.png)

   Sample screenshot of layout options:

   ![image](https://user-images.githubusercontent.com/42867097/140617575-74abfec8-e26d-4737-a5a9-9bce2a71200b.png)

### Errors Shown

No error shown.

### What version of Directus are you using?

v9.0.0 (main branch)

### What version of Node.js are you using?

16.13.0

### What database are you using?

PostgreSQL 13.4

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker</div>

**Comment by benhaynes** [comment]
Based on a conversation with Rijk, here is our idea:

Currently, Displays are used for **inline** representations of a field value, and output a Vue **component** by default. However, some use-cases can not handle or fit a Vue component and need a simpler **plaintext** output. For example, this calendar layout, the browser's tab title, etc.

We should add an option to _all_ Displays so that when using them, we can request a plaintext version. By default, this would simply return the raw value, stringified. However, we can progressively enhance the Display's code with a function to return "smarter" strings, for example:

* Tags: Return a CSV of formatted values
* Formatted text would return only the plain text with any prefix/suffix
* Labels (eg: status) would return the output text for the value
* Translations would return the configured language/fields as plaintext

**Comment by azrikahar** [comment]
> We should add an option to all Displays so that when using them, we can request a plaintext version.

I believe this is now technically resolved by #13263 and #13099 in the form of string handlers, but regarding the original "use translated title in calendar" issue, the calendar event title generation will probably need to be updated to leverage this new handler when applicable.

**Comment by rijkvanzanten** [comment]
That's correct!

**Comment by eikaramba** [comment]
i think this ticket is related to the problem i found in latest directus 9.12.1 that calendar view is not correctly rendering nested template values, see the following picture
![grafik](https://user-images.githubusercontent.com/1320525/172028698-3f7aca06-cf84-470a-840d-303f15179c63.png)

**Comment by eikaramba** [comment]
if you want i can create a separat ticket, otherwise i assume this one is correct.

i already tried to make a PR but i have no clue how i can contribute to the @directus package. i would need to somehow reference the local repo from my projects package.json.
My idea was to see how it works for tabular view and just replicate the logic ;)
