### ISSUE TITLE
In-app docs have broken internal linking

### ISSUE THREAD

**Issue by dimitrov-adrian** [directus/directus#9568]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Integrated docs module in the app have broken page linking.

Examples:
 - Activity Log  form the App Overview page
 - Creating an Item from the Content specifications (the whole block)

... and much more

### To Reproduce

Go docs module and try navigation

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

16.5.0

### What database are you using?

mysql 5.7

### What browser are you using?

chrome

### What operating system are you using?

macOS Big Sur (11)

### How are you deploying Directus?

locally

**Comment by benhaynes** [comment]
Just submitted like 10 PRs to fix these! Thank you!
