### ISSUE TITLE
Custom filters on permission collection

### ISSUE THREAD

**Issue by bernatvadell** [directus/directus#9573]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

After updating to the latest version, when I want to modify the access permissions to an element that already had some permissions configured, I get an error when loading the component. 

### To Reproduce

1) Install v9.0.0-rc85
2) Set up a collection
3) Create a new role
4) Set permissions for the new collection for a new read role
5) Update to the latest version of directus v9.0.0 (stable)
6) Access the maintenance of roles and permissions for the previously created collection, and the attached error should appear. 

### Errors Shown

RangeError: Maximum call stack size exceeded
    at Function.keys (<anonymous>)
    at al (<hidden_path>/admin/index.eae14d77.js:339:25569)
    at ln (<hidden_path>/admin/index.eae14d77.js:339:25603)
    at ln (<hidden_path>/admin/index.eae14d77.js:339:25647)
    at ln (<hidden_path>/admin/index.eae14d77.js:339:25647)
    at ln (<hidden_path>/admin/index.eae14d77.js:339:25647)
    at ln (<hidden_path>/admin/index.eae14d77.js:339:25647)
    at ln (<hidden_path>/admin/index.eae14d77.js:339:25647)
    at ln (<hidden_path>/admin/index.eae14d77.js:339:25647)
    at ln (<hidden_path>/admin/index.eae14d77.js:339:25647)

![image](https://user-images.githubusercontent.com/17298604/140659032-5dc0d238-58a1-4a8a-8a25-d27a5fd9b308.png)

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

14

### What database are you using?

postgres

### What browser are you using?

edge

### What operating system are you using?

windows

### How are you deploying Directus?

docker

**Comment by licitdev** [comment]
@bernatvadell does this issue still persist? 
Please kindly provide your rule by clicking on `Rule` and selecting `Raw value`. 

<img width="178" alt="image" src="https://user-images.githubusercontent.com/26413686/142403575-2e116985-c3ef-4bbf-ad97-c450eaeab0e3.png">

**Comment by rijkvanzanten** [comment]
Fairly sure this is caused by an invalid filter object being used in the permissions. @licitdev's suggestion will allow you to clear it out.

I'll push a fix to fail more gracefully 👍🏻
