### ISSUE TITLE
Most of system collection filter hooks aren't implemented

### ISSUE THREAD

**Issue by t7tran** [directus/directus#9575]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I just tried to refactor the hooks and noticed that `collections.delete` no longer works. It seems from the source code that only `fields.delete` is invoked via `emitter.emitFilter`.

![image](https://user-images.githubusercontent.com/76130324/140662551-1e57d6ed-3256-469e-a0d5-442917237a91.png)

### To Reproduce

```
const registerHook: HookConfig = (
  { filter, action },
) => {
  filter("collections.delete", async function (data: any) {
    // this doesn't get fired when a collection is being deleted
  });
  filter("fields.delete", async function (data: any) {
    // this DOES get fired when a field is being deleted
  });
};
export default registerHook;
```

### Errors Shown

NA

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

16.13.0

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying Directus?

Docker

**Comment by Oreilles** [comment]
Just tried in a docker setup, cloned from [this example](https://docs.directus.io/getting-started/installation/docker/#docker-compose) from the docs, create the hook file at `./extensions/test/index.js` with:
```js
module.exports = function registerHook({ filter , action }) {
  filter("collections.create" , (_) => console.log("collections.create"));
  filter("collections.delete" , (_) => console.log("collections.delete"));
  filter("fields.create"      , (_) => console.log("fields.create"));
  filter("fields.delete"      , (_) => console.log("fields.delete"));
};
```

and all events triggers just fine.

**Comment by t7tran** [comment]
It is indeed working. Must have been my mistake. Thanks for checking @Oreilles.
