### ISSUE TITLE
Calendar Layout Should Show Items for All Days

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#9577]
Currently, the Calendar Layout (month mode) only shows data for the current month... which makes sense, but all calendars will also include data on the other _shown_ days of the previous/next months. We should be doing the same.

![Screen Shot 2021-11-07 at 6 16 44 PM](https://user-images.githubusercontent.com/522079/140665553-343b789c-3376-42ce-a775-b303b5b1a201.png)

**Comment by azrikahar** [comment]
This might be related to #6226

**Comment by benhaynes** [comment]
Kind of, that one is about start/end dates that _span_ outside the filter (start and end dates)... this issue is about extending even _event_ items (only a start date, not a span) to be fetched for all _visible_ dates, not just this month.

Similar, but different!
