### ISSUE TITLE
deep filter on v9.0.0 doesn't work the same way as in rc versions

### ISSUE THREAD

**Issue by kwiatkk1** [directus/directus#9578]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

[deep](https://docs.directus.io/reference/query/#deep) query parameter is not working properly in 9.0.0:
- if the collection being queried has more than one item, a deep filter applied to every of its items returns no results (though they certainly should be matched)

### To Reproduce

I have a collection `foobar` with `foobar_translations` set up:

```
+----+-----------+----------------+---------+
| id | foobar_id | languages_code | name    |
+----+-----------+----------------+---------+
|  1 |         1 | cs             | cs text |
|  2 |         1 | en             | en text |
|  3 |         1 | pl             | pl text |
+----+-----------+----------------+---------+
```
When there is only on item, deep filter on translations works fine: 
- `GET: /items/foobar?fields=translations.*&deep[translations][_filter][languages_code][_eq]=en`
- produces: `{"data":[{"translations":[{"foobar_id":1,"id":2,"languages_code":"en","name":"en text"}]}]}`

But adding another item to `foobar` causes returned translations to be empty:
```
+----+-----------+----------------+-------------+
| id | foobar_id | languages_code | name        |
+----+-----------+----------------+-------------+
|  1 |         1 | cs             | cs text     |
|  2 |         1 | en             | en text     |
|  3 |         1 | pl             | pl text     |
|  4 |         2 | en             | 2nd en text |
+----+-----------+----------------+-------------+
```

- `GET /items/foobar?fields=translations.*&deep[translations][_filter][languages_code][_eq]=en`
- response: `{"data":[{"translations":[]},{"translations":[]}]}`

Notes:
- on `9.0.0-rc.*` it works fine: translations are properly returned
- tested on a fresh installation

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

14.17.4

### What database are you using?

mysql 8 / sqlite

### What browser are you using?

not applicable

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by DrMint** [comment]
Just wanted to mention that I had the same problem after updating from rc.98. I experimented a bit and realized it wasn't happen on newly created collections (created after upgrading to 9.0.0).

**Comment by MoltenCoffee** [comment]
We got the same problem, after updating from either rc.98 or rc.99 (not sure), using Postgres 13 and Node 16 on a Debian server.

**Comment by MoltenCoffee** [comment]
After some trial and error, reverting #9494 seems to fix this issue for me.

**Comment by nazariydj** [comment]
I think it’s work with deep[_filter][translations][languages_code][_eq]=en - inverting _filter and translations

**Comment by gkielwasser** [comment]
It seems I have the same issue with Directus v9.0.0. The following is now broken as it returns empty translations array:
```
/items?fields=*.*&deep={ "translations": { "_filter":  { "languages_code": {"_in": ["fr-CH"] }  } } }
```

**Comment by kwiatkk1** [comment]
> I think it’s work with deep[_filter][translations][languages_code][_eq]=en - inverting _filter and translations

I'm afraid it's not: this-way deep filtering doesn't work at all so everything is returned

**Comment by gkielwasser** [comment]
> > I think it’s work with deep[_filter][translations][languages_code][_eq]=en - inverting _filter and translations
> 
> I'm afraid it's not: this-way deep filtering doesn't work at all so everything is returned

What do you mean by "not supported at all" ? It was supported and working (at least in rc.98). Also it seems always [documented here](https://docs.directus.io/reference/query/#deep)

Do you mean it has been dropped in v9.0.0 ?

**Comment by kwiatkk1** [comment]
> > > I think it’s work with deep[_filter][translations][languages_code][_eq]=en - inverting _filter and translations
> > 
> > 
> > I'm afraid it's not: this-way deep filtering doesn't work at all so everything is returned
> 
> What do you mean by "doesn't work at all" ? It was supported and working (at least in rc.98). Also it seems always [documented here](https://docs.directus.io/reference/query/#deep)
> 
> Do you mean it has been dropped in v9.0.0 ?

No, sorry for not being clear: 
- I meant that swapping [translation] and [_filter] won't work (please notice, that the [docs](https://docs.directus.io/reference/query/#deep) that you are referring to have this order right)

**Comment by gkielwasser** [comment]
> > > > I think it’s work with deep[_filter][translations][languages_code][_eq]=en - inverting _filter and translations
> > > 
> > > 
> > > I'm afraid it's not: this-way deep filtering doesn't work at all so everything is returned
> > 
> > 
> > What do you mean by "doesn't work at all" ? It was supported and working (at least in rc.98). Also it seems always [documented here](https://docs.directus.io/reference/query/#deep)
> > Do you mean it has been dropped in v9.0.0 ?
> 
> No, sorry for not being clear:
> 
> * I meant that swapping [translation] and [_filter] won't work (please notice, that the [docs](https://docs.directus.io/reference/query/#deep) that you are referring to have this order right)

Didn't understood your issue was about the order of those parameters.

I have opened a dedicated [ticket](https://github.com/directus/directus/issues/9636) for my issue.

Also, even if this is not documented I have tried using the order you mention. 
```
&deep[_filter][translations][languages_code][_eq]=fr-CH
```
All entries are returned but I would say it makes sense.

**Comment by nazariydj** [comment]
I apologize for causing confusion. I encountered the same problem with **O2M** relation (parent/**childs**). It seemed solved by inverting parameters, but I didn't notice that it returns all elements without applying the filter.

**Comment by Oreilles** [comment]
I tried but couldn't replicate this issue on a fresh MySQL 8 instance.
Here are the exact step I followed:

* Create collection `foo` 
* Add text field `name` to `foo`
* Create collection `foo_translations`
* Add m2o  field `foo_id` to `foo_translations` related to `foo.id`
* Add text field `languages_code` to `foo_translations`
* Add o2m field `translations` to `foo` related to `foo_translations.foo_id`

I then inserted:
```
// in foo:
{ "name": "Sean" }
{ "name": "Joe" }
// in foo_translations
{ "name": "Jean", "languages_code": "fr-FR" }
{ "name": "Juan", "languages_code": "es-ES }
```

**Comment by Oreilles** [comment]
I tried but couldn't replicate this issue on a fresh MySQL 8 instance with the latest directus releaes docker image.
Here are the exact step I followed:

* Create collection `foo` 
* Add text field `name` to `foo`
* Create collection `foo_translations`
* Add m2o  field `foo_id` to `foo_translations` related to `foo.id`
* Add text field `languages_code` to `foo_translations`
* Add o2m field `translations` to `foo` related to `foo_translations.foo_id`

Then inserted:
```
// in foo:
{ "name": "Sean" }
{ "name": "Joe" }
// in foo_translations
{ "name": "Jean", "languages_code": "fr-FR" }
{ "name": "Juan", "languages_code": "es-ES }
```

Then checked both queries:
```
GET /items/foo?fields=translations.*
GET /items/foo?fields=translations.*&deep[translations][_filter][languages_code][_eq]=fr-FR
```

And get all translations in the first case, only french translations in the second.
@kwiatkk1, @gkielwasser, could you please confirm that the relations between your tables are properly configured in the settings advanced field detail, and provide a schema snapshot of your instance ?

@rijkvanzanten , I noticed something however which makes me think this might be cache related. If I GET `/items/foo?fields=translations.*` with only the authorization bearer token as a header, then add some translations, then rerun the GET query with the same token, I get the exact same results (that are outdated), which means I git the cache when it should have been invalidated.

**Comment by gkielwasser** [comment]
> deep[translations][_filter][languages_code][_eq]

Hi @Oreilles,

The part about authorization definitly put me on the right direction even if it sounds now really strange what is happening.

Querying my collection like above returns correct results when I give an admin authorization token. 
With a public access, I have an empty translations array that is returned.
```
GET /items/my_collection?fields=translations.*&deep[translations][_filter][languages_code][_eq]=fr-FR
```

I have tried to set all public read access to both of my collection (my_collection and my_collection_translations) but I have the same results described upper.

Is there anything else I could check to understand what happen?

Thanks

**Comment by rijkvanzanten** [comment]
I think this might be the same underlying issue as https://github.com/directus/directus/issues/9590#issuecomment-965231848. It seems like that's also related to how the permissions are handled on the nested level

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten , I noticed something however which makes me think this might be cache related. If I GET /items/foo?fields=translations.* with only the authorization bearer token as a header, then add some translations, then rerun the GET query with the same token, I get the exact same results (that are outdated), which means I hit the cache when it should have been invalidated.

Could be. Cache is opt-in though, what is your configuration for caching in the instance you're testing it in? Can you try disabling cache to confirm/rule it out as a problem?

**Comment by kwiatkk1** [comment]
Thanks @rijkvanzanten! I confirm that it works fine in version 9.0.1!
