### ISSUE TITLE
Interface Display Template for Repeater doesn't show configured values

### ISSUE THREAD

**Issue by minyangu-bgl** [directus/directus#9587]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The template for `Repeater` field type seems stops render on item details page after Directus version update from `9.0.0-rc.99` to `9.0.0`

checked on `9.0.0-rc.100` as well, appears this is already broken, but works on `9.0.0-rc.99`

### To Reproduce

1. Create a field as Repeater type, create two sub-fields `wagering_requirement` and `conversion_rate`, in the template field, I want to display as this: `Wagering Requirement: {{wagering_requirement}}, Conversion Rate: {{conversion_rate}}`
![image](https://user-images.githubusercontent.com/49973259/140695266-ac1416a1-7a37-4df2-b7a3-d09a27a82e5b.png)

2. In version `9.0.0-rc.100` and above, I see the UI is not rendering the template anymore, it only display the first sub-field value: 
![image](https://user-images.githubusercontent.com/49973259/140696123-8c6dc390-b029-4785-9fa3-401c87c58001.png)

However in `9.0.0-rc.99`, it shows up as expected
![image](https://user-images.githubusercontent.com/49973259/140696257-0811198d-1e95-4d2a-a4ce-2ac4df68d145.png)

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

16.13.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
@minyangu-bgl thanks for the detailed description, especially pinpointing which exact version did it started to not work! This helps a ton in finding out what was the regression introduced in rc.100.

Opened a PR to fix this 👍
