### ISSUE TITLE
"Add existing" 

### ISSUE THREAD

**Issue by joe-blocher** [directus/directus#9592]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a files list (multiple) in my contenttype. 
When I want to add an existing file to filelist: press "Add existing"
But this will delete all other file in the list! This is not what I expected!
When I press "Upload" a file it works.

### To Reproduce

- ![image](https://user-images.githubusercontent.com/93246850/140716970-bface900-7c8a-49eb-9c92-054aba6a8095.png)

- ![image](https://user-images.githubusercontent.com/93246850/140716924-bb1ed0ff-1dc0-4b27-8cfb-ff220b5e97b1.png)

- ![image](https://user-images.githubusercontent.com/93246850/140717199-90e5b129-2d83-4680-a902-c8b04a3cb463.png)

### What version of Directus are you using?

v9.0.0 

### What version of Node.js are you using?

v15.1.0 

### What database are you using?

mariadb 

### What browser are you using?

Chrome 

### What operating system are you using?

macOS 

### How are you deploying Directus?

running locally

**Comment by joselcvarela** [comment]
@licitdev

**Comment by licitdev** [comment]
Pushed a fix. 😁

**Comment by joe-blocher** [comment]
Thanks 👍
