### ISSUE TITLE
relational triggers cannot be modified once the field is created

### ISSUE THREAD

**Issue by wc-matteo** [directus/directus#9601]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Once a field is created, trying to modify its relational triggers does nothing. It does work when creating the field, tho

### To Reproduce

- Create collection foo
- Create collection bar
- Create an m2o field baz on bar towards foo
- After creation, try to set baz relational trigger: on delete of foo, delete the bar item (cascade)
- Refresh and see that it reverts back to `Nullify` instead of Delete the bar item (cascade)

### What version of Directus are you using?

v9.0.0

### What version of Node.js are you using?

n/a

### What database are you using?

postgres 13.3 / mssql 2016

### What browser are you using?

chrome

### What operating system are you using?

win 10

### How are you deploying Directus?

k8s

**Comment by kwiatkk1** [comment]
Hi @wc-matteo, I think I have a similar/same problem:
- the error I'm getting refers to violating foreign key constraint (`alter table foo modify bar int null - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'bar' and referenced column 'id' in foreign key constraint 'foo_bar_foreign' are incompatible.`) because of `unsigned` modifier is missing in the statement.

What does the error message look like in your case? Can you paste it here?
_(If its similar, then it may be the same bug, so I won't report it separately)_

**Comment by wc-matteo** [comment]
in my case there's no error. Just the trigger not getting created

**Comment by Oreilles** [comment]
@kwiatkk1 this looks like a different issue, please submit another bug report!
@wc-matteo I just tried on PostgreSQL 13 in a dev environment and all events got triggered, I'll try in a docker setup.

**Comment by Oreilles** [comment]
Just tried in a docker setup, cloned from [this example](https://docs.directus.io/getting-started/installation/docker/#docker-compose) from the docs, create the hook file at `./extensions/test/index.js` with:
```js
module.exports = function registerHook({ filter , action }) {
  filter("collections.create" , (_) => console.log("collections.create"));
  filter("collections.delete" , (_) => console.log("collections.delete"));
  filter("fields.create"      , (_) => console.log("fields.create"));
  filter("fields.delete"      , (_) => console.log("fields.delete"));
};
```

and all events triggers just fine.

**Comment by wc-matteo** [comment]
@Oreilles both. I tested again the repro and on my end the trigger doesn't get created:

### editing baz relationship
![image](https://user-images.githubusercontent.com/10562635/140915420-b4f07dc6-7b95-4c54-8e81-a9034db88ab5.png)

### trying to set the relational trigger: on delete of foo, delete the bar item (cascade)
![image](https://user-images.githubusercontent.com/10562635/140915533-da8a0c2f-4e91-43c7-b620-9d25cd305d67.png)

### save
![image](https://user-images.githubusercontent.com/10562635/140915565-442147df-518c-41dd-b0a5-4f3f9d720e50.png)

### reload the page in the browser
![image](https://user-images.githubusercontent.com/10562635/140915688-a2593089-5b80-4ddb-a496-56a02841efee.png)

### check baz relationship
![image](https://user-images.githubusercontent.com/10562635/140915715-84386f6f-be4e-4cb7-901e-d1de2cb0c9db.png)

**Comment by wc-matteo** [comment]
when saving after changing the relational trigger, the only network request that happens is this: `/users/me/track/page`. So it's not doing anything basically

**Comment by kitschpatrol** [comment]
I'm having the same issue on 9.0.0 + Postgres. Relational triggers are only respected if they're specified at field creation time, not if they're changed after the fact. (Even though the UI updates and retains the setting correctly, the actual triggers don't fire.)

**Comment by wc-matteo** [comment]
@kitschpatrol if you refresh the page (through the browser), the ui should show the old settings

**Comment by kitschpatrol** [comment]
Thanks @wc-matteo yes can confirm that the UI reflects the old setting after a refresh.

**Comment by admin-navigaite** [comment]
Good morning,

i have the latest version of directus 9.23.1.
And i have exactly the same error again. no changes after changing the relational trigger.
