### ISSUE TITLE
Deploy error when using Passenger Server with Directus 9.0.0

### ISSUE THREAD

**Issue by Eliophot** [directus/directus#9613]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hello,
I update to Directus 9.0.0 and I have this error on Passenger Application Server

```
internal/modules/cjs/loader.js:430
      throw e;
      ^

Error: Cannot find module '/home/iffhgwh/myapi.fr/node_modules/directus/dist/dist/logger.js'
```

dist/dist/logger.js instead dist/logger.js

### To Reproduce

Have an environnement with Passenger Application Server to deploy
npm update +  npx directus database migrate:latest
Everything is ok
I restart the server and then crash.

### Errors Shown

```
internal/modules/cjs/loader.js:430
      throw e;
      ^

Error: Cannot find module '/home/iffhgwh/myapi.fr/node_modules/directus/dist/dist/logger.js'
```

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

12.22.7

### What database are you using?

MySQL 8

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### How are you deploying Directus?

Passenger Application Server

**Comment by azrikahar** [comment]
Not familiar with Passenger here, but Directus does require at least Node.js 12.20 to run. Reference: https://github.com/directus/directus#-requirements

I'll close this issue for now, but we'll also reopen it if this still persists even after you're on the minimum supported Node.js version.

**Comment by Eliophot** [comment]
We use node 12.22.7, sorry I have put the npm version...

**Comment by azrikahar** [comment]
thanks for the correction. I'll reopen this.

**Comment by joselcvarela** [comment]
Hello @Eliophot 
Can you show how are you setting up the Passenger Server?
I suspect this could be related https://github.com/directus/directus/discussions/9603 which is fixed in https://github.com/directus/directus/pull/9616

**Comment by Eliophot** [comment]
I have no control over the settings, it is provided by our host. Before we were on the rc92, we did not have this issue...

**Comment by smilledge** [comment]
> node_modules/directus/**dist/dist**/logger.js

Are you importing logger directly? If you are, this is probably related to https://github.com/directus/directus/issues/9541

**Comment by Eliophot** [comment]
Nope, just the build generate the double dist...

**Comment by Eliophot** [comment]
Oh I user a server file to launch with : 
```
const { default: logger } = require('directus/dist/logger');
const { default: start } = require('directus/dist/start');

start().catch(function(err) {
    logger.error("Error", { err });
});
```

**Comment by Eliophot** [comment]
Ok I'll change this code by ;
```
var { startServer } = require('directus/server');

startServer();
```
And it's work ^^

https://docs.directus.io/getting-started/installation/plesk/

**Comment by ricardovigatti** [comment]
@quentinglorieux I'm also looking for that.

**Comment by ricardovigatti** [comment]
@quentinglorieux Here is the solution: https://github.com/directus/directus/discussions/18307#discussioncomment-5713382
