### ISSUE TITLE
Geometry field types are formatted incorrectly for MySQL schemas

### ISSUE THREAD

**Issue by justrealmilk** [directus/directus#9614]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Looks like lat and long need to be reversed just for MySQL 8... I bet this never came up in testing since no one from down under tried to insert this data 😛

https://dba.stackexchange.com/questions/242001/mysql-8-st-geomfromtext-giving-error-latitude-out-of-range-in-function-st-geomfr

```
{
  "message": "
    insert into `areas` (`id`, `location`, `name`) 
    values ('c38f629f-a69d-4e64-a3a9-e70a1cbfe1e4', 
      st_geomfromtext('MULTIPOLYGON (((148.19430559458425 -25.359817002954728, 150.07262775362693 -26.12884590315783, 148.19430559458425 -27.953799657646407, 148.19430559458425 -25.359817002954728)))', 4326), 
    'Test 2') 
    - UNKNOWN_CODE_PLEASE_REPORT: Latitude 148.194306 is out of range in function st_geomfromtext. It must be within [-90.000000, 90.000000].",
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR"
  }
}
```

Slightly formatted error message for easier reading

### To Reproduce

Configure a collection interface for MultiPolygon and draw a shape over... Australia for instance.

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

14.17.3

### What database are you using?

MySQL 8

### What browser are you using?

Chrome

### What operating system are you using?

Docker

### How are you deploying Directus?

Docker

**Comment by Oreilles** [comment]
Oh my, that is insane. Thanks a lot for reporting this.

**Comment by justrealmilk** [comment]
Also affects the Map content layout view 😂

**Comment by Oreilles** [comment]
Certainely, because `geometry.asText` also swap longitude and latitude for WGS84 (epsg:4326) data.
Because MySQL 5 and MySQL 8 have different behaviour for the same function (breaking compatibility), I choose to replace geometry creation in MySQL from `st_geomfromtext(wkt, 4326)` to `st_geomfromtext(wkt)`, which will solve the issue and preserve consistency across MySQL versions.
The PR is still open but it will hopefully be merged in by the next release.
