### ISSUE TITLE
Migration from rc94 to rc95 fails

### ISSUE THREAD

**Issue by Eicher-MA** [directus/directus#9655]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Trying to migrate the db from rc.94 to rc.95 fails.

Error: `ALTER TABLE [directus_users] ADD [provider] nvarchar(128) not null CONSTRAINT [directus_users_provider_default] DEFAULT 'default', [external_identifier] nvarchar(255) - Column names in each table must be unique. Column name 'provider' in table 'directus_users' is specified more than once`.

Trying to migrate the db from rc.94 to rc.96-101 fails too.
Error: `DROP INDEX [directus_users_email_unique] ON [directus_users] - Cannot drop the index 'directus_users.directus_users_email_unique', because it does not exist or you do not have permission`

### To Reproduce

Migrating the db from rc.94 to any higher version

### What version of Directus are you using?

rc.94

### What version of Node.js are you using?

16.13.0

### What database are you using?

MSSQL 2019

### What browser are you using?

...

### What operating system are you using?

Windows 10

### How are you deploying Directus?

locally

**Comment by Oreilles** [comment]
Seems like the migration `20210903A-add-auth-provider` has already been done, but not registered so Directus tries to run it again and fails.

Could you report back the result of these two queries ?
```sql
SELECT
  [ix].[name], COL_NAME([ic].[object_id], [ic].[column_id]) as column_name
FROM [sys].[indexes] AS [ix]
JOIN [sys].[index_columns] AS [ic]
  ON [ix].[object_id] = [ic].[object_id]
  AND [ix].[index_id] = [ic].[index_id]
WHERE  OBJECT_NAME([ic].[object_id]) = 'directus_users'
```
```sql
SELECT * from directus_migrations WHERE version = '20210903A'
```

**Comment by Eicher-MA** [comment]
First query:

| name| column_name|
| ----------- | ----------- |
| directus_users_pkey| id|

Second query:

nothing

**Comment by Oreilles** [comment]
Weird. If the columns `provider` and `external_identifier` are present in the `directus_users` table, and the column `data` present in the `directus_sessions` table, try manually deleting them:
```sql
ALTER TABLE directus_users DROP COLUMN provider;
ALTER TABLE directus_users DROP COLUMN external_identifier;
ALTER TABLE directus_sessions DROP COLUMN
```
It also seems like the `email` column of `directus_users` isn't unique when it should be, so try adding the constraint manually:
```sql
ALTER TABLE directus_users ADD CONSTRAINT directus_users_email_unique UNIQUE(email);
```
Then try running the migrations again.

**Comment by Eicher-MA** [comment]
Ty It worked. I'm on 9.0.0 now. 👍

**Comment by ajira86** [comment]
Hi, I have the same problem but after altering tables I still have this issue

```
[Error: DROP TABLE "directus_users" - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed] {
  errno: 19,
  code: 'SQLITE_CONSTRAINT'
}
```
