### ISSUE TITLE
Create Collection error

### ISSUE THREAD

**Issue by hugopvl** [directus/directus#9692]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

when I create a new collection, it gives me the following error:

![](https://cdn.discordapp.com/attachments/892037514645356554/908003294834724894/unknown.png)
![](https://cdn.discordapp.com/attachments/892037514645356554/908004015252582490/unknown.png)

But create the collection anyway.
but with error in user_update field
![](https://cdn.discordapp.com/attachments/892037514645356554/908003703229931691/unknown.png)

### To Reproduce

Creat a new collection and select all default fields. 

### What version of Directus are you using?

v.9.0.0

### What version of Node.js are you using?

16.13.0

### What database are you using?

MSSQL SERVER

### What browser are you using?

Chrome

### What operating system are you using?

server debian, user windows

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
I _think_ the problem might be that certain versions of SQL Server don't accept using two foreign key constraints with a trigger to the same related collection. In this case, that'd be user_created and user_updated. cc @jaycammarano

**Comment by Oreilles** [comment]
Apparently this is documented "feature":
https://docs.microsoft.com/sql/relational-databases/errors-events/mssqlserver-1785-database-engine-error

**Comment by paulboudewijn** [comment]
This 'bug' is the result of adding `ondelete set null` to the optional collection fields `uploaded_by` and `modified_by`  in PR #9305. @Oreilles is right, it's a known limitation of all versions of sqlserver. 
Normally the fix would be to use triggers instead, but then the content of this collection can't be edited anymore (#9704).

A workaround for MSSQL users is to use just one of those fields in a collection. 

@rijkvanzanten; could a fix be to remove the `ondelete set null` from those fields and implement an API hook on the `directus_users.items.delete` action instead?

**Comment by biapar** [comment]
I've the same problem.

**Comment by hugopvl** [comment]
Good morning guys,

Any information about this situation?

**Comment by Oreilles** [comment]
The underlying issue probably won't be fixed, as it is a limitation from SQL Server that cannot be worked around in a clean/safe way, at least to the best of our knowledge. If having a collection with several fields all related to a same collection is a requirement for you, your best bet currently is to use a database that support triggers on these (all supported ones except SQL Server).

In the future, please do not ask for ETA/updates for issues - we're either working on them, or too busy with other ones. If you need to be made aware of progression made on a specific issue, you can use the subscribe button 👍

**Comment by Oreilles** [comment]
That's right, removing the `ondelete` triggers and letting users manually set the trigger to `set null` or `delete` would solve this. @rijkvanzanten opinion ?

**Comment by hugopvl** [comment]
@Oreilles Sorry for picking up on this subject again, in fact I subscribed to the issue, and as I didn't really understand the outcome of this situation, that's why I asked again, but it doesn't happen again

**Comment by paulboudewijn** [comment]
> I didn't really understand the outcome of this situation

same here....

**Comment by paulboudewijn** [comment]
Hi @hugopvl,

Below a script to add the missing relation after creating a new collection with both the optional fields `uploaded_by` and `modified_by` on a sql server database.

Just change `<new-collection-name>` to the name of the collection and then run the script directly on the database (i.e. through sqlserver management studio).
Please let me know if it worked.

```
declare @collectionName as nvarchar(64);
set @collectionName = '<new-collection-name>'

-- step 1: create new collection in the app and select both the optional fields 'Created By' and 'Updated By'

-- step 2: ignore the 'Could not create constraint or index.' error

-- step 3: add user_updated foreign key to collection
declare @addUserUpdatedKey varchar(max)
set @addUserUpdatedKey = 'ALTER TABLE [dbo].[' + @collectionName + '] WITH CHECK ADD CONSTRAINT [' + @collectionName + '_user_updated_foreign] FOREIGN KEY([user_updated]) REFERENCES [dbo].[directus_users] ([id]); ALTER TABLE [dbo].[' + @collectionName + '] CHECK CONSTRAINT [' + @collectionName + '_user_created_foreign]'
exec(@addUserUpdatedKey);

-- step 4: store user_updated relation in directus_relations table
insert into [directus_relations] ([many_collection], [many_field], [one_collection], [one_deselect_action])
select top 1 @collectionName [many_collection], 'user_updated' [many_field], 'directus_users' [one_collection], 'delete' [one_deselect_action] from [directus_relations] where not exists (select 1 from [directus_relations] where [many_collection] = @collectionName and [many_field] = 'user_updated')

-- step 5: clear systemcache, i.e. by adding an extra field to this collection through the app
```

**Comment by hugopvl** [comment]
> Hi @hugopvl,
> 
> Below a script to add the missing relation after creating a new collection with both the optional fields `uploaded_by` and `modified_by` on a sql server database.
> 
> Just change `<new-collection-name>` to the name of the collection and then run the script directly on the database (i.e. through sqlserver management studio). Please let me know if it worked.
> 
> ```
> declare @collectionName as nvarchar(64);
> set @collectionName = '<new-collection-name>'
> 
> -- step 1: create new collection in the app and select both the optional fields 'Created By' and 'Updated By'
> 
> -- step 2: ignore the 'Could not create constraint or index.' error
> 
> -- step 3: add user_updated foreign key to collection
> declare @addUserUpdatedKey varchar(max)
> set @addUserUpdatedKey = 'ALTER TABLE [dbo].[' + @collectionName + '] WITH CHECK ADD CONSTRAINT [' + @collectionName + '_user_updated_foreign] FOREIGN KEY([user_updated]) REFERENCES [dbo].[directus_users] ([id]); ALTER TABLE [dbo].[' + @collectionName + '] CHECK CONSTRAINT [' + @collectionName + '_user_created_foreign]'
> exec(@addUserUpdatedKey);
> 
> -- step 4: store user_updated relation in directus_relations table
> insert into [directus_relations] ([many_collection], [many_field], [one_collection], [one_deselect_action])
> select top 1 @collectionName [many_collection], 'user_updated' [many_field], 'directus_users' [one_collection], 'delete' [one_deselect_action] from [directus_relations] where not exists (select 1 from [directus_relations] where [many_collection] = @collectionName and [many_field] = 'user_updated')
> 
> -- step 5: clear systemcache, e.g. by adding an extra field to this collection through the app
> ```

Hi @paulboudewijn thanks for sharing, it works beautifully :)

**Comment by koksikus** [comment]
Hi @paulboudewijn I have the same problem with relationships.  If I already have a collection and I have data in it and I have a user update column and i see in database that save the user data in it, but in directus it does not display user update and I do not have a tab relation in the field settings, I only make 4 point and manually add this relation to the directory base?

**Comment by paulboudewijn** [comment]
Hi @koksikus,

For existing collections you can ignore steps 1 & 2.

**Comment by koksikus** [comment]
So in Managment SQL studio in Directus database paste lines
declare @addUserUpdatedKey varchar(max)
set @addUserUpdatedKey = 'ALTER TABLE [dbo]. (...)
exec(@addUserUpdatedKey)

and

insert into [directus_relations] (...)

But before execution change any @collectionName with my collectionName @Items
Yes?

**Comment by paulboudewijn** [comment]
> So in Managment SQL studio in Directus database paste lines

Just paste the whole script, the steps you can ignore are just comments.

> But before execution change any @collectionName with my collectionName @Items

Yes indeed, you need to replace `<new-collection-name>` with the (internal) collectionname. But I doubt this is called `@Items`

**Comment by biapar** [comment]
So Directus will be patched in the next version?

**Comment by koksikus** [comment]
Hi @paulboudewijn thanks for the help. I inquired because I wanted to make sure that I wasn't spoiling anything (I'm new in SQL world :) . Of course, I don't have an @Item collection, but an Item. You change the world for the better ;)

**Comment by paulboudewijn** [comment]
> So Directus will be patched in the next version?

Well, PR #10168 fixes the underlying issue, but it's still under review. No milestone has been assigned so I'm not sure if it will be patched in the _next_ version.

The fix prevents the issue when creating a *new* collection, to fix *existing* collections you still need the above sql script.

**Comment by paulboudewijn** [comment]
> I inquired because I wanted to make sure that I wasn't spoiling anything

The sql script doesn't delete anything, just adds missing stuff. You should be safe :)

**Comment by koksikus** [comment]
@paulboudewijn It works perfect.  Thank you so much.
