### ISSUE TITLE
User role can not be restricted on item creation with filter on related item

### ISSUE THREAD

**Issue by eXsiLe95** [directus/directus#9733]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I tried to limit a user group: The user group should only be able to create an item when a related item has a specific value in on of its fields. When applying this filter on the edit-permission, the filter works just fine. However, when creating a new item and relating an existing item which fulfills the rule, the request fails with the following message (see Errors Shown)

### To Reproduce

1. Create an content type A with a text field
2. Create a content type B with a relation on A
3. Create an item of type A
4. Restrict the user on the creation of items of type B with any rule, e.g. `ContentType A -> Field equals 'abcd'`
5. Try creating an item of content type B with a relation on A which has a field different than abcd -> it won't work, as expected
6. Try creating an item of content type B with a relation on A which has a field equal to abcd -> it won't work, see screenshot above

### Errors Shown

```json
{
    "errors": [
        {
            "message": "\"regelungsart\" must be of type object",
            "extensions": {
                "code": "FAILED_VALIDATION",
                "field": "regelungsart"
            }
        }
    ]
}
```

In the frontend, the following error occurs: 
![image](https://user-images.githubusercontent.com/31202904/141334660-8e09bee8-bfcb-42de-85da-bbc017a5c34f.png)

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

16.13.0

### What database are you using?

Postgres 10

### What browser are you using?

Chrome

### What operating system are you using?

Linux 4.14.246-187.474.amzn2.x86_64

### How are you deploying Directus?

Docker

**Comment by eXsiLe95** [comment]
I noticed a difference in the implementation: When creating an item of content type A from the relation field, the whole object is sent. However, when relating an already existing item, only the identifier of this item is sent. Can this have anything to do with it?

**Comment by rijkvanzanten** [comment]
> However, when relating an already existing item, only the identifier of this item is sent. Can this have anything to do with it?

That's certainly it. If you setup the validation rule to require the following:

```json
{
  "user": {
    "name": {
      "_eq": "Rijk"
    }
  }
}
```

selecting an existing item won't pass, as you're not touching that "name" field:

```
// payload
{
  "user": 15
}
```

By setting the validation rule to 

```json
{
  "user": {
    "_eq": 15
  }
}
```

you're effectively requiring the use of the existing user.

**Comment by eXsiLe95** [comment]
Thanks for your reply!
So is this actually desired behaviour? From the options to set up a rule, I would expect directus to also check in existing related content if the rule says so. This would be quite useful in my use case where there is a "category content type" which needs to be checked in order to decide whether or not a user can create such an item (so basically I want to allow a group of users to only create items that relate to a specific category). 
Changing the validation rule to your last example would solve the problem, but is not that speaking - how do I set the rule like this in the first place? I tried to check for the id, but since the id only is sent, it cannot be accessed either.

**Comment by rijkvanzanten** [comment]
> So is this actually desired behaviour?

That's a very good question. We validate for the object the user submits, so if the validation rules requires a nested object to be sent, we validate for a nested object. That being said, I do agree that one might expect Directus to figure it out on the fly based on the relationship information, and nothing else. That being said being said though, that would mean you could never require people to use an existing item, as both validation rules would check against both.

You could maybe use a filter like:

```json
{
  "_or": [
    {
      "regelungsart": {
        "_in": [1, 2, 3, 4, 5] // IDs to check against
      }
    },
    {
      "regelungsart": {
        "nested_field": {
          "_eq": "Abc"
        }
      }
    }
  ]
}
```

**Comment by eXsiLe95** [comment]
Okay, so I'm assuming that checking out the related content when only an ID is sent along is against a design/architecture decision? Or would that also be a way to check the filters that can be created through the interface?

And then one more (maybe silly) question: how can I specify the rule as JSON? In this mask here, I have no way to check the value of the relation field against a string, since directus assumes this is an object.

![image](https://user-images.githubusercontent.com/31202904/141426349-fe3321a8-dc93-4e9e-9d30-736348b99474.png)

**Comment by azrikahar** [comment]
>  how can I specify the rule as JSON? In this mask here, I have no way to check the value of the relation field against a string, since directus assumes this is an object.

You should be able to edit the raw JSON value by hovering your mouse on the Rule (above `Any of the following) there 👍

**Comment by rijkvanzanten** [comment]
I believe the original question was answered. We can reopen if there's a bug preventing the correct operation 🙂

**Comment by eXsiLe95** [comment]
Friendly ping @rijkvanzanten @azrikahar :)

**Comment by rijkvanzanten** [comment]
Heya!

> With this settings, as a user, I would expect directus to check if the name of the related content (father) contains "Skywalker".

I think that's a little too over-generalized. I wouldn't be comfortable saying that feeling applies to every user.

In this particular case, there's an interesting difference between "Allow user to create new nested item with value X" versus "Allow user to select related item where value = X". There's no operators or functionality of the latter.

For this particular use case, I'd recommend setting up an _or rule so you can check for both selecting an existing item with ID = X, and allowing for an item to be created where field = Y.

**Comment by eXsiLe95** [comment]
Hey @rijkvanzanten :)

> In this particular case, there's an interesting difference between "Allow user to create new nested item with value X" versus "Allow user to select related item where value = X". There's no operators or functionality of the latter.

Yes, you're totally right with this, I didn't quite think that far. I just think, however, that this difference does not become that clear when not setting up the access rules with JSON but instead using the user interface. From what a user can see in this view, you (or more precisely: I) can not tell wether this applies to new content or existing content that is selected to be related.

![image](https://user-images.githubusercontent.com/31202904/146179816-7514e76d-e1d7-4eca-9c92-0c886a05ee67.png)

> For this particular use case, I'd recommend setting up an _or rule so you can check for both selecting an existing item with ID = X, and allowing for an item to be created where field = Y.

This would definitely be a workaround for my case! As stated above, it did not work for me to test against an identifier when relating an existing item (*). And still, as a non-programmer (or at least someone that doesn't understand JSON and/or the technique which evaluates these rules, as well as the difference in relating existing content or creating new related content) you couldn't configure such a rule.

Could you explain the difference in a "nested item" and a "related item", or do they both mean the same in regards of your statement to the difference between existing and new content?

(*) Here is the configuration that I was using as a rule to create a new child: 

```json
{
   "_and":[
      {
         "_or":[
            {
               "parent":{
                  "_eq":"dbc76afd-185a-44af-bac7-b15806640f1f"
               }
            },
            {
               "parent":{
                  "name":{
                     "_contains":"Frank"
                  }
               }
            }
         ]
      }
   ]
}
```

I have configured full access on `father`, but directus won't let me (a user with role "PermissionTest") add another child.
![image](https://user-images.githubusercontent.com/31202904/146184106-e4269f31-457d-4ba3-af5c-9c312d4cdfb7.png)
(Add button shows "Not Allowed" when hovering with the mouse)
![image](https://user-images.githubusercontent.com/31202904/146184787-55482f02-1586-4cbf-924e-12d65f4a1e6b.png)

**Comment by rijkvanzanten** [comment]
> Could you explain the difference in a "nested item" and a "related item", or do they both mean the same in regards of your statement to the difference between existing and new content?

Yeah that's the same thing. It's all about what the app will send to the API. When you select an existing item in a many-to-one, the only thing the app will send is the primary key (eg `{ field: 1 }`). However, if you make changes to that same related item, it's sent as `{ field: { id: 1, title: 'new title' }}`. The conditions are ran against what values are actually staged to be sent to the API.

I'm thinking through a way to optimize that, as you're right in saying that setting up conditional fields for relational fields isn't the most intuitive right now. I'm thinking we could fetch the full tree of fields that's used in conditions when opening the item, which in turn means you can use the rules a little more consistently, as the value would always be a nested object 🤔

**Comment by eXsiLe95** [comment]
Hey Rijk, thanks for the reply!

> I'm thinking through a way to optimize that, as you're right in saying that setting up conditional fields for relational fields isn't the most intuitive right now. I'm thinking we could fetch the full tree of fields that's used in conditions when opening the item, which in turn means you can use the rules a little more consistently, as the value would always be a nested object 🤔

I would love to see that and I'm willing to contribute (at the weekends) if you would like some help here.
