### ISSUE TITLE
Moving or zooming in map layout triggers an error

### ISSUE THREAD

**Issue by azrikahar** [directus/directus#9746]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Moving or zooming seems to trigger this error each time:

https://user-images.githubusercontent.com/42867097/141438339-9fe2ffd4-f057-4baa-ab90-32daba9323bd.mp4

Might be related to the fix in #9615.

### To Reproduce

Should be reproducible on map layout without any data (at least in my case):

https://user-images.githubusercontent.com/42867097/141438168-cb211e8d-fe47-4ab9-994b-03c3376b5ea0.mp4

### Errors Shown

Whenever the error popup occurs, a GET request gets a 400 response.

Request URL:

```js
https://<url here>/items/locations?limit=1000&fields[]=location&fields[]=name&fields[]=id&sort[]=id&page=1&filter=%7B%22location%22:%7B%22_intersects_bbox%22:%7B%22type%22:%22Polygon%22,%22coordinates%22:[[[-91.87273857268036,44.250154169852266],[-66.82128551912203,44.250154169852266],[-66.82128551912203,61.390294098284215],[-91.87273857268036,61.390294098284215],[-91.87273857268036,44.250154169852266]]]%7D%7D%7D&meta[]=filter_count&meta[]=total_count
```

Formatted Query Strings from above:

```
limit: 1000
fields[]: location
fields[]: name
fields[]: id
sort[]: id
page: 1
filter: {
   "location":{
      "_intersects_bbox":{
         "type":"Polygon",
         "coordinates":[
            [
               [
                  -91.87273857268036,
                  44.250154169852266
               ],
               [
                  -66.82128551912203,
                  44.250154169852266
               ],
               [
                  -66.82128551912203,
                  61.390294098284215
               ],
               [
                  -91.87273857268036,
                  61.390294098284215
               ],
               [
                  -91.87273857268036,
                  44.250154169852266
               ]
            ]
         ]
      }
   }
}
meta[]: filter_count
meta[]: total_count
```

Response Body:

```js
errors: [
  {
    "message": "\"_intersects_bbox\" has to be a valid GeoJSON object",
    "extensions": {
      "code": "INVALID_QUERY"
    }
  }
]
```

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

PostgreSQL 13.4

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
cc cartographer @Oreilles

**Comment by Oreilles** [comment]
This bug is caused by https://github.com/directus/directus/pull/9697
@licitdev I was wrong when telling you that filters couldn't contain nested array 😅, they do when you use geometric filters because they are GeoJSON object.
