### ISSUE TITLE
M2A sorting fails with image field

### ISSUE THREAD

**Issue by fabianbeiermeire** [directus/directus#9759]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

M2A sorting fails if an image is use in the related collection.

### To Reproduce

Create M2A-Field with a related Collection that uses an image.

### Errors Shown

[
    {
        "message": "\"storage\" is required",
        "extensions": {
            "code": "FAILED_VALIDATION",
            "field": "storage",
            "type": "required"
        }
    },
    {
        "message": "\"filename_download\" is required",
        "extensions": {
            "code": "FAILED_VALIDATION",
            "field": "filename_download",
            "type": "required"
        }
    }
]

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

v14.18.1

### What database are you using?

SQLite 3.36.0 

### What browser are you using?

Brave (Chrome), Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by Oreilles** [comment]
Thank you for reporting this issue, could you provide the API query that caused it ?

**Comment by joselcvarela** [comment]
Hey @Oreilles, I am currently working on sorting and relationships https://github.com/directus/directus/pull/9832
I can take from here, if you don't mind 👍

**Comment by joselcvarela** [comment]
Hello @fabianbeiermeire 
This seems to be fixed now. Tried with both Postgres and SQLite.

https://user-images.githubusercontent.com/14039341/147568654-1667874f-bf4a-416f-a18c-aa9ccc793ece.mov

___
> If you think this is not solved yet, feel free to reach us in order to reopen.
