### ISSUE TITLE
No directus field in graphql after succesful build

### ISSUE THREAD

**Issue by JakubOlejnik1155** [directus/directus#9767]
### Preflight Checklist

- [x] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [x] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [x] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hello,
I use @directus/gatsby-source-directus
I do not see a directus field in gatsby graphql. Project is building succesfully but i can see warning in console.

**_warn `createResolvers` passed resolvers for type `DirectusData_directus_files` that doesn't exist in the schema. Use `createTypes` to add the type before adding resolvers._**

"dependencies": {
    **"@directus/gatsby-source-directus": "9.0.0",**
    "@emotion/react": "^11.5.0",
    "@emotion/styled": "^11.3.0",
    "@mdx-js/mdx": "^1.6.22",
    "@mdx-js/react": "^1.6.22",
    "@mui/material": "^5.0.4",
    "babel-plugin-styled-components": "^1.13.2",
    "dotenv": "^10.0.0",
    **_"gatsby": "^3.11.1",_**
    "gatsby-background-image": "^1.5.3",
    "gatsby-plugin-gatsby-cloud": "^2.11.0",
    "gatsby-plugin-image": "^1.11.0",
    "gatsby-plugin-layout": "^2.12.0",
    "gatsby-plugin-manifest": "^3.11.0",
    "gatsby-plugin-mdx": "^2.12.0",
    "gatsby-plugin-offline": "^4.11.0",
    "gatsby-plugin-react-helmet": "^4.11.0",
    "gatsby-plugin-react-svg": "^3.0.1",
    "gatsby-plugin-sharp": "^3.11.0",
    "gatsby-plugin-styled-components": "^4.12.0",
    "gatsby-plugin-webfonts": "^2.1.1",
    "gatsby-source-filesystem": "^3.11.0",
    "gatsby-transformer-sharp": "^3.11.0",
    "gbimage-bridge": "^0.1.4",
    "glightbox": "^3.1.0",
    "gsap": "^3.8.0",
    "hamburgers": "^1.1.3",
    "html-to-text": "^8.1.0",
    "prop-types": "^15.7.2",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-helmet": "^6.1.0",
    "react-hook-form": "^7.15.0",
    "react-html-parser": "^2.0.2",
    "slugify": "^1.6.2",
    "styled-components": "^5.3.0",
    "swiper": "^7.0.1"
  },

### To Reproduce

use: 
directus 9.0.0
gatsby 3.11.1
@directus/gatsby-source-directus": "9.0.0"

### Errors Shown

**_warn `createResolvers` passed resolvers for type `DirectusData_directus_files` that doesn't exist in the schema. Use `createTypes` to add the type before adding resolvers._**

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

14.17.3

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Plesk

**Comment by unmaskz** [comment]
Had the same issue - quick fix for now is:

"@directus/gatsby-source-directus": "9.0.0-rc.95"

Drop down to the version above and should be fixed.

**Comment by JakubOlejnik1155** [comment]
@unmaskz It work's now Thank You!!!!!

**Comment by JakubOlejnik1155** [comment]
@unmaskz I reopened becouse localeFile is null when i want to query for images. Do You have any fix for that ?

**Comment by JakubOlejnik1155** [comment]
> Had the same issue - quick fix for now is:
> 
> "@directus/gatsby-source-directus": "9.0.0-rc.95"
> 
> Drop down to the version above and should be fixed.

Are you able to get photo? I have imageFile field null so i can not get it :/

**Comment by shi-rudo** [comment]
directus: 9.2.1

same problem here with **gatsby-source-directus 9.2.1**
```warn `createResolvers` passed resolvers for type `DirectusData_directus_files` that doesn't exist in the schema. Use `createTypes` to add the type before adding resolvers.```

switching to **gatsby-source-directus 9.0.0-rc.95**  as workaround resolves the issue
