### ISSUE TITLE
Issue on One to Many Relationship (Alias)

### ISSUE THREAD

**Issue by juliuscesario** [directus/directus#9771]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hi, i am using directus now and there is some bugs i think, when i create a collections with one to many relationship i can see that there are data with relations and no relations as attached on image below
<img width="1200" alt="Screen Shot 2021-11-13 at 07 17 23" src="https://user-images.githubusercontent.com/75230036/141597724-7739ee9a-b72e-41db-a1ed-60ef666e74db.png">

but when iam using API as you can see ID 14 and 15, 15 is no relations and 14 have data in relations showing empty as attached image
<img width="1308" alt="Screen Shot 2021-11-13 at 07 19 23" src="https://user-images.githubusercontent.com/75230036/141597786-d62d38b5-9f62-4dd1-bc04-9ae07f6581fa.png">

### To Reproduce

just create One to Many relationship (alias) then using API to get data form parent collections

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

16.13.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

Linux 5.11.0-1021-gcp

### How are you deploying Directus?

Manual Locally

**Comment by nazariydj** [comment]
I think this is caused by the same issue as #9578 and #9590 which was fixed in #9726. 
Try upgrade to v9.0.1.

**Comment by joselcvarela** [comment]
Hello @juliuscesario 
Can you check with the latest version as @nazariydj mentioned?

**Comment by juliuscesario** [comment]
Dear All,

Yes it's working now, sorry to not check deeply on this Issue Great Job all
