### ISSUE TITLE
Error on creating a new m2m field

### ISSUE THREAD

**Issue by krazyjakee** [directus/directus#9772]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When creating a new m2m field on a collection, the following error is thrown.

`[INVALID_PAYLOAD] Field "hardware_id" in collection "hardware_videos" doesn't have a relationship.`

The field is created but when querying the value through the API it is of type "string" and not an m2m field.

### To Reproduce

- Complete the steps in this issue to fix the "unable to delete field" bug: https://github.com/directus/directus/issues/8675#issuecomment-940940506
- Attempt to add an m2m field to any collection.

### Errors Shown

[INVALID_PAYLOAD] Field "hardware_id" in collection "hardware_videos" doesn't have a relationship.

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

14.0.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by paulboudewijn** [comment]
I'm experiencing the same problem on MS-SQL.

**Comment by joselcvarela** [comment]
Hello @krazyjakee 
Can you check if this is the issue you are experiencing?
https://github.com/directus/directus/pull/9392

It only happens after you removed a collection right?

**Comment by krazyjakee** [comment]
The bug is triggered when adding an m2m field to a collection.

I have removed collections in the past which didn't work but then https://github.com/directus/directus/issues/8675#issuecomment-940940506 fixed it.

**Comment by barrylow** [comment]
I can confirm that I get this error when creating M2M only after removing a collection as shown in #9392.

When I create a new M2M in a different collection that had no prior collection relationships it creates the M2M as expected.

**Comment by krazyjakee** [comment]
@barrylow yes, this is my bug exactly. Thanks for clarifying.

**Comment by joselcvarela** [comment]
Fixed in #9392
Try with latest version 👍
___
> If you think this is not solved yet, feel free to reach us in order to reopen.
