### ISSUE TITLE
Textarea field bug

### ISSUE THREAD

**Issue by federicocappellotto97** [directus/directus#9775]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a textarea field translatable and it refresh every time i write a char. Then i need to refocus the field to write something else.

https://user-images.githubusercontent.com/63153191/141646559-d9f1dec1-3a48-4e12-b575-ddc99ab5448b.mov

This happens only to translatable fields.

### To Reproduce

Create a textarea field translatable then try to edit it

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

14.18.1

### What database are you using?

Mysql

### What browser are you using?

Chrome

### What operating system are you using?

macOS Monterey (12)

### How are you deploying Directus?

Locally

**Comment by micheljacquot34** [comment]
Same issue.
Was already present in 9.0.0, and discussed in [#9324](https://github.com/directus/directus/pull/9324)

**Comment by federicocappellotto97** [comment]
> Same issue. Was already present in 9.0.0, and discussed in [#9324](https://github.com/directus/directus/pull/9324)

Oh sorry.. thanks!

**Comment by micheljacquot34** [comment]
Don't close this issue, it was not fixed.

**Comment by federicocappellotto97** [comment]
> Don't close this issue, it was not fixed.

Don't think i can reopen it :((

**Comment by federicocappellotto97** [comment]
Update: sometimes i can't even save the item when i update the translatable field

**Comment by azrikahar** [comment]
Duplicate of #9510
