### ISSUE TITLE
JSON custom interface

### ISSUE THREAD

**Issue by massimoliani** [directus/directus#9797]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I develop a custom interface to edit a JSON field.
The JSON object structure is driven by a template JSON object instructing the interface to create the different sub interfaces for editing.
All is working fine in a demo Vue app.
When installed in directus it look like directus can't recognize a modified object sent by input event.
I modify the values, the row editor show me the modified values, but the form interface can't recognize the modified object.

I found a temporary solution having the JSON field structured as an array of only one element and the element is my JSON object.
In this way the isEqual function from loadash can compare and fine the differences.

Using the raw editor can work, probably it skip the isEqual check using code mirror.

### To Reproduce

Try to edit a JSON field as an object { "subfield":"it's value" },without raw code editor.
If you send back the input event as argument the object you can't see the form interface identifying the change in the object.
If the same object as before is inside a single element array [{ "subfield":"it's value" }] and you change "subfield" value the form interface can see the difference and enable the save button for the current item.

### Errors Shown

Directus form editor doesn't highlight the green button to save modified data.

### What version of Directus are you using?

9.0.0.99

### What version of Node.js are you using?

16.0.0

### What database are you using?

MySql 8

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
Since you have checked ` I'm on the latest version of Directus`, would you mind checking the current latest version which is `9.0.1` instead of (presumably) `9.0.0-rc.99`? That'd be much appreciated in case it's not present anymore 👍

> Try to edit a JSON field as an object { "subfield":"it's value" },without raw code editor.

Does this mean it's present in the current code input in Directus? (assumed it is as you mentioned Code Mirror). However I can't seem to reproduce this issue on my end.

**Comment by massimoliani** [comment]
I'll check with lastest version at the end of the week as I have a demo with current software and would like to test before upgrading the EC2 instance.

With code mirror I can't see the error in rc99 too. Could be possible code mirror emit the string of JSON object? As using raw mode? Raw mode work without is equal test.

The possible

**Comment by azrikahar** [comment]
> I'll check with lastest version at the end of the week as I have a demo with current software and would like to test before upgrading the EC2 instance.

No worries, totally understandable.

> With code mirror I can't see the error in rc99 too. Could be possible code mirror emit the string of JSON object? As using raw mode? Raw mode work without is equal test.

It could be, but as there's quite many changes even from rc.99 to 9.0.1, just wanted to make sure it still exists as it is not uncommon for users to have their issues resolved after using the latest version.

If the issue does indeed persist after you have the chance to upgrade, it'd also be very helpful if you don't mind sharing the custom interface you mentioned. 

> The possible

I assume this message got cut off? 😄

**Comment by massimoliani** [comment]
I fully receive the message I'll check and share with you the code for the custom interface.

**Comment by massimoliani** [comment]
The problem persist on lastest version.
No way to update.
This is the interface:
[n2c_if_template.zip](https://github.com/directus/directus/files/7548504/n2c_if_template.zip)

"Tipologia di Template" is Scheda and "Config" is:
{
	"info": "Rif.<%riferimento%> - <%genere%>",
	"model": {
		"tipo": "form",
		"multi": false
	},
	"config": [
		{
			"nome": "riferimento",
			"label": "Riferimento",
			"stile": {},
			"default": null,
			"attributi": {
				"mode": "number"
			},
			"posizione": "left",
			"componente": "DxTextBox"
		},
		{
			"nome": "genere",
			"label": "Genere di gioiello",
			"default": null,
			"attributi": {
				"data-source": [
					"Anello",
					"Orecchino",
					"Pendente",
					"Cameo"
				]
			},
			"posizione": "right",
			"componente": "DxSelectBox"
		},
		{
			"nome": "fabbricatoIn",
			"label": "Fabbricato in",
			"default": null,
			"posizione": "left",
			"componente": "DxTextBox"
		},
		{
			"nome": "periodoProduzione",
			"label": "Anno/Periodo di produzione",
			"default": null,
			"posizione": "right",
			"componente": "DxTextBox"
		},
		{
			"nome": "materiale",
			"label": "MaterialeSpecifico",
			"default": null,
			"posizione": "left",
			"componente": "DxTextBox"
		},
		{
			"nome": "colore",
			"label": "Colore oggetto",
			"default": null,
			"posizione": "right",
			"componente": "DxTextBox"
		},
		{
			"nome": "ridimensionabile",
			"label": "Oggetto ridimensionabile",
			"valori": {
				"true": "si",
				"false": "no"
			},
			"default": null,
			"posizione": "left",
			"componente": "DxCheckBox"
		},
		{
			"nome": "pietre",
			"label": "Tipologia di pietre",
			"config": {
				"info": "<%pietra%>",
				"model": {
					"tipo": "tabs",
					"multi": true
				},
				"config": [
					{
						"nome": "numeroPietre",
						"label": "Numero di pietre",
						"attributi": {
							"mode": "number"
						},
						"posizione": "col1_4",
						"componente": "DxTextBox"
					},
					{
						"nome": "pietra",
						"label": "Pietra",
						"posizione": "col2_4",
						"componente": "DxTextBox"
					},
					{
						"nome": "castone",
						"label": "Castone",
						"posizione": "col3_4",
						"componente": "DxTextBox"
					},
					{
						"nome": "carati",
						"label": "Carati",
						"attributi": {
							"mode": "number"
						},
						"posizione": "col4_4",
						"componente": "DxTextBox"
					},
					{
						"nome": "colore",
						"label": "Colore",
						"posizione": "left",
						"componente": "DxTextBox"
					},
					{
						"nome": "purezza",
						"label": "Purezza",
						"posizione": "right",
						"componente": "DxTextBox"
					}
				],
				"elementi": {
					"stile": {},
					"attributi": {}
				},
				"contenitore": {
					"stile": {},
					"attributi": {}
				}
			},
			"default": null,
			"componente": "n2c_template"
		},
		{
			"nome": "marca",
			"label": "Marca",
			"default": null,
			"posizione": "left",
			"componente": "DxTextBox"
		},
		{
			"nome": "firma",
			"label": "Firma",
			"default": null,
			"posizione": "right",
			"componente": "DxTextBox"
		},
		{
			"nome": "certificato",
			"label": "Certificato gemmologico",
			"default": null,
			"posizione": "left",
			"componente": "DxTextBox"
		},
		{
			"nome": "expertise",
			"label": "Expertise del perito",
			"default": null,
			"posizione": "right",
			"componente": "DxTextBox"
		},
		{
			"nome": "revisione",
			"label": "Revisione",
			"default": null,
			"posizione": "left",
			"componente": "DxTextBox"
		},
		{
			"nome": "scatolaGaranzia",
			"label": "Scatola/Garanzia",
			"default": null,
			"posizione": "right",
			"componente": "DxTextBox"
		},
		{
			"nome": "condizione",
			"label": "Condizione",
			"default": null,
			"attributi": {
				"data-source": [
					"Nuovo",
					"Usato",
					"Resturato",
					"Rigenerato",
					"Pezzo unico"
				]
			},
			"componente": "DxSelectBox"
		}
	],
	"elementi": {
		"stile": {},
		"attributi": {}
	},
	"contenitore": {
		"stile": {},
		"attributi": {}
	}
}

Now I'm upgrading my customization to fullfill the lastest version modifications to hook etc etc.

Thank you for your help and sorry if part of the interface source is in italian!

**Comment by massimoliani** [comment]
Errata corriege:

this is the correct config object:
[
                    {
                        modello: "gioielli",
                        descrizione: "Gioielli",
                        label: "Scheda tecnica",
                        config: {
                            model: {
                                multi: false,
                                tipo: "form",
                            },
                            contenitore: {
                                stile: {
                                },
                                attributi: {
                                },
                            },
                            elementi: {
                                stile: {
                                },
                                attributi: {
                                },

                            },
                            info: "<%riferimento%> <%genere%>",
                            config: [
                                {
                                    nome: "riferimento",
                                    label: "Riferimento",
                                    componente: "DxTextBox",
                                    posizione: "left",
                                    attributi: {
                                        mode: "number",
                                    },
                                    stile: {
                                    },
                                    default: null,
                                },
                                {
                                    nome: "genere",
                                    label: "Genere di gioiello",
                                    componente: "DxSelectBox",
                                    posizione: "right",
                                    attributi: {
                                        "data-source": ["Anello", "Orecchino", "Pendente", "Cameo"],
                                    },
                                    default: null,
                                },
                                {
                                    nome: "fabbricatoIn",
                                    label: "Fabbricato in",
                                    componente: "DxTextBox",
                                    posizione: "left",
                                    default: null,
                                },
                                {
                                    nome: "periodoProduzione",
                                    label: "Anno/Periodo di produzione",
                                    componente: "DxTextBox",
                                    posizione: "right",
                                    default: null,
                                },
                                {
                                    nome: "materiale",
                                    label: "MaterialeSpecifico",
                                    componente: "DxTextBox",
                                    posizione: "left",
                                    default: null,
                                },
                                {
                                    nome: "colore",
                                    label: "Colore oggetto",
                                    componente: "DxTextBox",
                                    posizione: "right",
                                    default: null,
                                },
                                {
                                    nome: "ridimensionabile",
                                    label: "Oggetto ridimensionabile",
                                    componente: "DxCheckBox",
                                    posizione: "left",
                                    default: null,
                                },
                                {
                                    nome: "pietre",
                                    label: "Tipologia di pietre",
                                    componente: "n2c_template",
                                    config: {
                                        model: {
                                            multi: true,
                                            tipo: "tabs",
                                        },
                                        contenitore: {
                                            stile: {
                                            },
                                            attributi: {
                                            },
                                        },
                                        elementi: {
                                            stile: {
                                            },
                                            attributi: {
                                            },

                                        },
                                        info: "<%pietra%>",
                                        config: [
                                            {
                                                nome: "numeroPietre",
                                                label: "Numero di pietre",
                                                componente: "DxTextBox",
                                                posizione: "col1_4",
                                                attributi: {
                                                    mode: "number",
                                                },
                                            },
                                            {
                                                nome: "pietra",
                                                label: "Pietra",
                                                componente: "DxTextBox",
                                                posizione: "col2_4",
                                            },
                                            {
                                                nome: "castone",
                                                label: "Castone",
                                                componente: "DxTextBox",
                                                posizione: "col3_4",
                                            },
                                            {
                                                nome: "carati",
                                                label: "Carati",
                                                componente: "DxTextBox",
                                                posizione: "col4_4",
                                                attributi: {
                                                    mode: "number",
                                                },
                                            },
                                            {
                                                nome: "colore",
                                                label: "Colore",
                                                componente: "DxTextBox",
                                                posizione: "left",
                                            },
                                            {
                                                nome: "purezza",
                                                label: "Purezza",
                                                componente: "DxTextBox",
                                                posizione: "right",
                                            },
                                        ]
                                    },
                                    default: null,
                                },
                                {
                                    nome: "marca",
                                    label: "Marca",
                                    componente: "DxTextBox",
                                    posizione: "left",
                                    default: null,
                                },
                                {
                                    nome: "firma",
                                    label: "Firma",
                                    componente: "DxTextBox",
                                    posizione: "right",
                                    default: null,
                                },
                                {
                                    nome: "certificato",
                                    label: "Certificato gemmologico",
                                    componente: "DxTextBox",
                                    posizione: "left",
                                    default: null,
                                },
                                {
                                    nome: "expertise",
                                    label: "Expertise del perito",
                                    componente: "DxTextBox",
                                    posizione: "right",
                                    default: null,
                                },
                                {
                                    nome: "revisione",
                                    label: "Revisione",
                                    componente: "DxTextBox",
                                    posizione: "left",
                                    default: null,
                                },
                                {
                                    nome: "scatolaGaranzia",
                                    label: "Scatola/Garanzia",
                                    componente: "DxTextBox",
                                    posizione: "right",
                                    default: null,
                                },
                                {
                                    nome: "condizione",
                                    label: "Condizione",
                                    componente: "DxSelectBox",
                                    default: null,
                                    attributi: {
                                        "data-source": ["Nuovo", "Usato", "Resturato", "Rigenerato", "Pezzo unico"],
                                    },
                                },
                            ]
                        },
                    }]

the interface allow to select from an array of configuration object, usually fetched from the database, and dinamically create the interface to fill with data and store in the collection field the final data object with reference to the config template.
Let me know if you need any additional info.

Thank you in advance

**Comment by massimoliani** [comment]
Hi @azrikahar ,

I did several test during these days.

I tried to use @types/lodash but is only for TS.

I try to return alternatively data or [data] but every time the data, also different, go back to original object or array the form unset modifications.

So I use a different approach.
I return JSON.stringify(data) (as string is always a JSON object) and add a watch to value to go back to object with JSON.parse(value). Then in a hook, for the items of the collection I use this interface, I add the JSON.parse(field).

In this way the isEqual function can see the differences and set the modification flag of form.

I think isEqual can't compare object inside he see an object and return equal true. For the array it work only if see more or less elements (I never tried to change one single element).

You can try to use isEqual to compare to object and check if it work.

Code mirror as I understood return the string is of JSON object and isEqual can compare successfully. 

Hope these infos can help.

**Comment by rijkvanzanten** [comment]
I'll move this to a Q&A discussion, as I believe this is all implementation details for a custom interface, and not so much a bug in Directus itself we can fix 👍🏻
