### ISSUE TITLE
`Error: The stores could not be found` when using `useStores` inside the defineDisplay fields function

### ISSUE THREAD

**Issue by mattiaz9** [directus/directus#9802]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Using the function `useStores` in the `fields` prop of `defineDisplay` triggers an error.

I'm not sure if this is intended or not, but since many core displays use the stores inside the `fields` function we should be able to use them as well in our custom displays.

### To Reproduce

1. Create a simple display
2. Add the `fields` function. Example:
```
fields: () => {
    const stores = useStores();
    console.log('stores', stores);
    return ['id'];
},
```
3. Set the display to a field and navigate to the collection

### Errors Shown

`Error: [useStores]: The stores could not be found.`

What is not really clear to me is that the `console.log` correctly logs the store the first time before triggering the error, so it's like using the function the first time triggers the error for any use of the stores afterwards.

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

Postgres 13

### What browser are you using?

Safari, Chrome

### What operating system are you using?

macOS 12.0.1

### How are you deploying Directus?

locally

**Comment by licitdev** [comment]
Stores could be accessed in the following manner.

```js
import { useUserStore } from '@/stores';

...

fields: () => {
	const userStore = useUserStore();
	console.log(userStore.currentUser)
	return ['id'];
},
```

**Comment by mattiaz9** [comment]
@licitdev not for custom extensions. 
I'm working on my project not the directus repo, so I have to import `useStores` like this:
`import { useStores } from "@directus/extensions-sdk"`

**Comment by licitdev** [comment]
@mattiaz9 Do you have to use `useStores` within `defineDisplay`?
I have just tested that the stores can be accessed if it is used within the Vue component's `setup()`.
```js
import { useStores } from '@directus/extensions-sdk';

...

setup() {
        const stores = useStores();
        const userStore = stores.useUserStore();
        console.log(userStore.currentUser)
}
```

@joselcvarela There are two displays that uses `useStores` within it's `defineDisplay`, namely `translations` and `related-values` displays.
Is it intended for the stores to be accessible for custom extensions?

Please kindly refer to the below screenshot for the warnings and error when using `useStores` within `defineDisplay`.

<img width="608" alt="image" src="https://user-images.githubusercontent.com/26413686/142413104-31b02d2a-ae82-4a6b-b6ca-2a00b1a7c99c.png">

**Comment by mattiaz9** [comment]
well, what I need is an extension of the translations display (which I also created a pull request for https://github.com/directus/directus/pull/9776).
But since I don't know when, or if, it's getting merged I need one of my own for now.

My assumption was that if you can use stores in the core displays you should also be able to use them in custom displays.

**Comment by rijkvanzanten** [comment]
> My assumption was that if you can use stores in the core displays you should also be able to use them in custom displays.

That would be ideal, but they're technically not identical. The extension displays need to have the app internals explicitly passed to them through various injection points, as we include extensions in run time rather than build time.

We've never tried nor designed the composables to be accessible in the fields function. Seeing they're being run in and out of Vue component scopes, we'll have to look into how to make sure the composable injection will work in the various contexts the adjust-fields-for-display function is used. 

Mind opening a new feature request discussion so we can discuss what this should look like, and how to spec it out? 🙂

**Comment by mattiaz9** [comment]
@rijkvanzanten here https://github.com/directus/directus/discussions/10255
