### ISSUE TITLE
IStorage - Element is not accessible

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [directus/directus#9806]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When implementing the custom storage from https://docs.directus.io/reference/sdk/#auth it fails.
Renaming the IStorage with a custom name fixed the error "Element is not accessible" but results in the same error in the app.

### To Reproduce

WebStorm with installed directus sdk

### Errors Shown

Element is not accessible

TypeError: Super expression must either be null or a function
_inherits
node_modules/@babel/runtime/helpers/inherits.js:5
  2 | 
  3 | function _inherits(subClass, superClass) {
  4 |   if (typeof superClass !== "function" && superClass !== null) {
> 5 |     throw new TypeError("Super expression must either be null or a function");
  6 |   }
  7 | 
  8 |   subClass.prototype = Object.create(superClass && superClass.prototype, {
View compiled
(anonymous function)
src/myComponents/storage/MyStorage.js:3
  1 | import { IStorage, Directus } from '@directus/sdk';
  2 | 
> 3 | export class MyStorage extends IStorage {

### What version of Directus are you using?

directus/directus:9.0.1

### What version of Node.js are you using?

v14.15.4

### What database are you using?

sqlite

### What browser are you using?

Brave (Chrome)

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by joselcvarela** [comment]
Hello @NilsBaumgartner1994 
I was able to implement a custom storage and use it properly.
I believe this could be an issue from documentation.
Can you check if the example added here https://github.com/directus/directus/pull/9865 solve this issue?

**Comment by NilsBaumgartner1994** [comment]
Looks good, but I haven't testet it jet. But yours does make sense, since IAuth is an I telefaxe which extending does not make sense to me (thinking of Java, implements yes)

**Comment by joselcvarela** [comment]
Since I am not able to reproduce this, I am going to close for now.
___
> If you think this is not solved yet, feel free to reach us in order to reopen.

**Comment by NilsBaumgartner1994** [comment]
Well I may be post my docker-compose file for you
