### ISSUE TITLE
Abstract the primary key (id) column per table

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#981]
Currently Directus requires an `id` column to work properly – however many schemas have architectures that use different primary key naming conventions. While allowing a global alternate column name is an option, it would probably be best to allow the selection of this column on a table-by-table basis.

@WellingGuzman – any thoughts on how crazy this would be to implement? I know we've been assuming the `id` column throughout the codebase so it's pretty ingrained.

**Comment by benhaynes** [comment]
It was noted that we could inspect database tables for auto increment and unique keys to determine this information, which works for the vast majority of cases (notably not all though). We should look into this to see if we can avoid adding a setting to Directus, instead pulling from the schema directly.

**Comment by mikevalstar** [comment]
You may also want to use the indicated "Primary Key" in the table settings

**Comment by benhaynes** [comment]
Also, making a note that we should look into how we'd handle tables with *no* primary key. Having a dynamic name is complex, but possible – not having one at all might be problematic with our current architecture.

**Comment by WellingGuzman** [comment]
@benhaynes As we talking about, **not** having a primary key is it problematic, as it would be not having in any scenario out Directus. not having and primary key could end up being a table that can only insert, or we can ask for create a primary key.

are we going to disable "Primary" on table settings as we said we were going to, because it represents the "main" field rather than primary field/key. or when it's empty choose what's Directus guess what's the main field?

Custom keys are working as expected, I haven't had more issues regarding custom key recently.

**Comment by benhaynes** [comment]
@WellingGuzman I think we need to pull the primary key from the schema (maybe it's `id` or maybe something else). But Directus *needs* a primary key, so if the table doesn't have one (or it's a compound key), when you go to the table you would see an alert telling you to set one.

For the "primary field" that is within tables now, we should either change the name to the "Reference" field or remove it altogether (auto-select the first varchar field?).

Does that make sense?

**Comment by WellingGuzman** [comment]
This is related to #938.

What we can do at first is just do not allow anything but insert and view if the table doesn't have primary key.

How are we going to let the user create their own primary key name? by specify the default name on settings? or primary key name per table? or both?

**Comment by benhaynes** [comment]
I say let's require a primary key for all tables. No need to make it more complex by allowing view/insert. 

To SET the primary key, we should pull the key from the table schema. We can show it as a radio button in the table settings so admins can set it manually if they want. 

Tables created within Directus should have an `id` column by default.

**Comment by WellingGuzman** [comment]
We made it possible to use custom primary key table name in `6.4.x`, what's missing is how to treat table without it, it's not a easy task, as there's not way to reference a record.

Maybe we create a internal id either way, but that's a different topic, but let's enforce a primary key.
