### ISSUE TITLE
Filtering on two levels of o2m relation is not considering field condition

### ISSUE THREAD

**Issue by ajira86** [directus/directus#9818]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Filtering on two levels of o2m display the relations but don't apply condition on field

### To Reproduce

* Create species, classes and animals objects with name attribute
* Create o2m link from species to classes and classes to anima
* Ask API with a filter like items/species?fields=name,classes.name,classes.animals.name&filter[classes][animals]=Cats

The result is the whole species data which are liked with any classes as the following example

> /items/species?fields=name,classes.name,classes.animals.name&filter[classes][animals]=Cats

Returns

> {"data":[{"name":"Vertebrate","classes":[{"name":"Mammals","animals":[{"name":"Cats"}]}]},{"name":"Molluscs","classes":[{"name":"Gastropoda","animals":[{"name":"Snails"}]}]}]}

[Database dump](https://github.com/directus/directus/files/7539786/dump.zip)

### Errors Shown

No one

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

v16.13.0

### What database are you using?

PostgreSQL 13.4

### What browser are you using?

Chromium

### What operating system are you using?

Debian 8.3.0-6

### How are you deploying Directus?

docker

**Comment by Oreilles** [comment]
The `filter` url parameter only works for top level fields. If you want to filter against related fields, you need to use the `deep` parameter to write something like this: (untested) `items/species?deep[classes][animals][_filter][name][_eq]=Cats`
Relevant documentation: https://docs.directus.io/reference/query/#deep

**Comment by ajira86** [comment]
Thanks for information ... so, I tried and the only difference is that "Snails" disappear but the whole structure remains

```json
{
  "data": [
    {
      "name": "Vertebrate",
      "classes": [
        {
          "name": "Mammals",
          "animals": [
            {
              "name": "Cats"
            }
          ]
        }
      ]
    },
    {
      "name": "Molluscs",
      "classes": [
        {
          "name": "Gastropoda",
          "animals": []
        }
      ]
    }
  ]
}
```

My goal what to get the species data related to a specific animal but it seams to be the wrong way. Perhaps should I filter on animal first get and extract the whole species data from its grandchild ?

**Comment by Oreilles** [comment]
Oh, if that's what you want then you should simply turn your query the other way around:
```
items/animals?fields=*.*.*&filter[name][_eq]=Cats
```

**Comment by rijkvanzanten** [comment]
> The `filter` url parameter only works for top level fields. If you want to filter against related fields, you need to use the `deep` parameter to write something like this: (untested) `items/species?deep[classes][animals][_filter][name][_eq]=Cats`
> Relevant documentation: https://docs.directus.io/reference/query/#deep

Just to clarify something here:

The `filter` parameter filters _from_ the parent level, but can still do nested filtering. Take the following two examples:

```
/items/articles?filter[categories][name][_eq]=Recipes
```

```
/items/articles?deep[categories][_filter][name][_eq]=Recipes
```

The first example will only fetch articles that have a categories item where name = Recipes. 
The second example will fetch all articles, but will only nest the categories where name = Recipes.

---

@ajira86 I believe your filter is missing some things. In `&filter[classes][animals]=Cats`, `animals` is not a field with data, but another o2m field. We expect to find the value "Cats" in a field called `name`. Therefore, the filter should be `&filter[classes][animals][name][_eq]=Cats`

**Comment by ajira86** [comment]
Thanks @rijkvanzanten for your clarification. So, after your comment: I wanted to say that it was just a mistake in my report but after doing some tests I found the following results.

If I work only with first level name classes

> /items/species?fields=name,classes.name,classes.animals.name&filter[classes][name]=Mammals

Returns the excepted result.

But If I remove the field name as a mistake like this

> /items/species?fields=name,classes.name,classes.animals.name&filter[classes]=Mammals

The system returns an error like this

> {"errors":[{"message":"An unexpected error occurred.","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]} 

But if I'm in the second level doing the same things with OR without mistake, in all the case it returns me all the data from all species, classes and animals without any error.

> /items/species?fields=name,classes.name,classes.animals.name&filter[classes][animals][name]=Cats

or

> /items/species?fields=name,classes.name,classes.animals.name&filter[classes][animals]=Cats

or even with wrong field name like this

> /items/species?fields=name,classes.name,classes.animals.name&filter[classes][animals][wrong]=Cats

it returns the same as reported

> {"data":[{"name":"Vertebrate","classes":[{"name":"Mammals","animals":[{"name":"Cats"}]}]},{"name":"Molluscs","classes":[{"name":"Gastropoda","animals":[{"name":"Snails"}]}]}]}
