### ISSUE TITLE
Content type folder is showing only to admin

### ISSUE THREAD

**Issue by federicocappellotto97** [directus/directus#9820]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have this content types inside a folder (Pages)
<img width="210" alt="Schermata 2021-11-15 alle 16 47 38" src="https://user-images.githubusercontent.com/63153191/141811577-2304fc20-9d45-4632-9306-4074145316fe.png">

The problem is this content types are showing only to admin users. I've created a role with all permissions, but this is what this role sees:
<img width="221" alt="Schermata 2021-11-15 alle 16 47 49" src="https://user-images.githubusercontent.com/63153191/141811599-f2ef117c-7af4-43fc-b416-dfbf04b2cd20.png">

### To Reproduce

Create a folder and put inside some content types. Then create a role with all permissions.

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

14.18.1

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

macOS Monterey (12)

### How are you deploying Directus?

Locally

**Comment by Oreilles** [comment]
You currently cannot add permissions on folders, therefore non-admin users cannot currently display them.
See ongoing discussion here: https://github.com/directus/directus/issues/9820.
