### ISSUE TITLE
Assigning granular permission to collections contained in folders makes collection invisible when accessing as restricted role

### ISSUE THREAD

**Issue by darioguarascio** [directus/directus#9823]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

A new role that is given permissions to access a specific collection cannot see that collection if mentioned collection is nested within a group (folder) 

### To Reproduce

1. Create a new collection `test_table`
2. Crete a new role `test_role`
3. Assign permissions to `test_table` on `test_role`
4. Login as `test_role`:  `test_table` is visible
5. Login as Admin
6. Create folder in data model `test_folder`
7. Assign `test_table` as child of `test_folder` (IE: grouped)
8. Login as `test_role`: `test_table` disappeared from collection list

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

postgres:13

### What browser are you using?

Chrome

### What operating system are you using?

Linux 5.11.0-40-generic

### How are you deploying Directus?

Docker

**Comment by Oreilles** [comment]
You currently cannot add permissions on folders, therefore non-admin users cannot currently display them.
See ongoing discussion here: https://github.com/directus/directus/issues/9207.
