### ISSUE TITLE
Azure SQL Server: Errors on update/create constrains [INTERNAL_SERVER_ERROR]

### ISSUE THREAD

**Issue by biapar** [directus/directus#9844]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

We have the error [INTERNAL_SERVER_ERROR] when we create constrains, keys and relations.

### To Reproduce

Install Directus connected to Azure SQL Server

### Errors Shown

![image](https://user-images.githubusercontent.com/661517/141985823-20496016-bc6e-448c-a9b3-d2bf785470e2.png)

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

14

### What database are you using?

SQL Server on Azure

### What browser are you using?

Edge

### What operating system are you using?

MacOS

### How are you deploying Directus?

local

**Comment by biapar** [comment]
13:31:38 🚨 ALTER TABLE [DiaryItem] ADD CONSTRAINT [diaryitem_diaryid_foreign] FOREIGN KEY ([diaryid]) REFERENCES [Diary] ([id]) ON DELETE SET NULL - Could not create constraint or index. See previous errors.
RequestError: ALTER TABLE [DiaryItem] ADD CONSTRAINT [diaryitem_diaryid_foreign] FOREIGN KEY ([diaryid]) REFERENCES [Diary] ([id]) ON DELETE SET NULL - Could not create constraint or index. See previous errors.
    at RequestTokenHandler.onErrorMessage (/Users/biagioparuolo/ProjectsOnMac/virtusbackend/node_modules/tedious/lib/token/handler.js:362:21)
    at Readable.<anonymous> (/Users/biagioparuolo/ProjectsOnMac/virtusbackend/node_modules/tedious/lib/token/token-stream-parser.js:26:33)
    at Readable.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Readable.push (_stream_readable.js:212:10)
    at next (internal/streams/from.js:86:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by Oreilles** [comment]
This is most likely due to a known limitation in SQL Server, where you cannot have multiple update/delete triggers rules referencing the same table ( See https://github.com/directus/directus/issues/9692 ).
Can you confirm that you are in this situation and/or share a schema snapshot to double check ?

**Comment by biapar** [comment]
I'm in the same situation. So I've to wait a bug fixing and I don't use the relations. 
Meanwhile I've to change database and go on SQLite or MySQL.

**Comment by Oreilles** [comment]
Closing in favor of https://github.com/directus/directus/issues/9692
