### ISSUE TITLE
openId Facebook Login Problem

### ISSUE THREAD

**Issue by batuhanbilginn** [directus/directus#9848]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When I want to use Facebook login with OpenID it gives an error.

### To Reproduce

You can simply try to use Facebook SSO with OpenID.

### Errors Shown

<img width="965" alt="Screenshot 2021-11-16 at 16 49 48" src="https://user-images.githubusercontent.com/86785488/141997385-ecd45b1f-e9de-416a-87b9-d0fa5de582e1.png">

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

14.17.2

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker (Digital Ocean)

**Comment by aidenfoxx** [comment]
As @batuhanbilginn, Facebooks OpenID configuration is not compatible with Directus. You can use the OAuth configuration outlined here: https://github.com/directus/directus/discussions/9744#discussioncomment-1630700

We should add a note about this to the docs, and a specific error in the logs.

**Comment by batuhanbilginn** [comment]
> As @batuhanbilginn says, Facebooks OpenID configuration is not compatible with Directus. You can use the OAuth configuration outlined here: [#9744 (comment)](https://github.com/directus/directus/discussions/9744#discussioncomment-1630700)
> 
> We should add a note about this to the docs, and a specific error in the logs.

The main problem is OAuth doesn't auto-fill user's profile :(

**Comment by batuhanbilginn** [comment]
@rijkvanzanten Can we say that Directus will not support Facebook openId auth flow anymore?

**Comment by aidenfoxx** [comment]
> Can we say that Directus will not support Facebook openId auth flow anymore?

@batuhanbilginn Directus has never supported Facebook via OpenID. OpenID is a new flow and Directus would previously use OAuth for Facebook authentication. It is still the case that for Facebook you will have to rely on OAuth.

I added the following PR to display an error if trying to configure OpenID with a provider that doesn't support the required "code" flow: https://github.com/directus/directus/pull/9862

**Comment by batuhanbilginn** [comment]
> > Can we say that Directus will not support Facebook OpenID auth flow anymore?
> 
> @batuhanbilginn Directus has never supported Facebook via OpenID. OpenID is a new flow and Directus would previously use OAuth for Facebook authentication. It is still the case that for Facebook you will have to rely on OAuth.
> 
> I added the following PR to display an error if trying to configure OpenID with a provider that doesn't support the required "code" flow: #9862

Okay, thanks for the PR however we were able to get profile data with the old Facebook OAuth flow. Without auto-fill, social login is not fully beneficial. Can you guys help us to make this work?

**Comment by aidenfoxx** [comment]
@batuhanbilginn What do you mean you were able to get profile data with the old OAuth flow? That was never a feature of Directus as far as I know, unless you added your own custom functionality?

OAuth has no standardized profile format unlike OpenID, so there is no simple way to implement profile filling. You're welcome to try and implement it though.

If you want to do something custom, the OAuth access token is stored in the users session data, so you're free to query profiles yourself manually.

**Comment by batuhanbilginn** [comment]
> @batuhanbilginn What do you mean you were able to get profile data with the old OAuth flow? That was never a feature of Directus as far as I know, unless you added your own custom functionality?
> 
> OAuth has no standardized profile format unlike OpenID, so there is no simple way to implement profile filling. You're welcome to try and implement it though.
> 
> If you want to do something custom, the OAuth access token is stored in the users session data, so you're free to query profiles yourself manually.

Thank you for helping about this :)

When I check the `directus_session` I get this response. 

`{
    "token": "SIsStK_eZXfVIqoXCQrqxWWKx75_v_naHztDGmTX2-JVdemJYWuN3sN5gSPvHe09",
    "user": "30fb3cc0-5491-4bca-9e87-6aa8920949ba",
    "expires": "2021-12-05T20:01:55.660Z",
    "ip": "78.179.90.161",
    "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
    "data": {
      "code": "AQDii_GWjz9TF5i00FsIiHKytKEOOHZG88RVC-Q95ko1vB216Hmw1JxXZR49i9SYRQFIl3l59NpBs1L43vEJ6dF5Bp6xZ9GnzHB6fXfeKC_oJ9jvFPpG5VLCON_sTuhjzDjh_FzUYDxB7-z9RGvZ-O6ndB1fPlpXbeRmEX0Voe-CpDANI6gtFsna6XmwBDNtPA0NCXRlJVh_ifnBvhgoRKfMqK9LA_zVExs42Ps6lSfvEkkMW8j1L3NbhRs3oWVJS33_4nXdXDJ7m9toz6ysjLReoRNAoc39X7yTXoeHWgoxXfsXrZW6IG74y_OMSELZ0qKB7aQVU-AY2G-4zczrRkFtXV1y3PBXI33UaQAvOKOIhbiOkvqPw-MW1gSCH69LJ0Tqbdz9Vm-DD-_yA6noBXNOon_Mb2-J5M6zK5EvYmeY_lvb7KMrwL_i3lJUoTP5eWQ",
      "codeVerifier": "EOj5FRh4rh6SKHImSaD6dvdIJ75UrG4tl8mF2OcAUfI",
      "state": "Q9iTkrL06wghnn79ylBZpgFMKqJ2vDJl4JLdM6yVf04"
    }
  },`

Should I use `code` to exchange with access_token or do we already have one in another place?

**Comment by aidenfoxx** [comment]
Looks like your SSO provider doesn't send us a `refresh_token` and in that instance we don't store an `access_token` to make further OAuth requests with. So that doesn't seem like an option.

I guess you'll have to either work the functionality you want into the Directus core and submit a PR, or commission the Directus devs to implement the functionality you want.

**Comment by rijkvanzanten** [comment]
@batuhanbilginn Mind opening a new [feature request](https://github.com/directus/directus/discussions/new) detailing the profile extraction you are looking for? 🙂

Other than that, it seems like the situation/question in the original post was resolved/answered, so I'll close this for now 👍🏻
