### ISSUE TITLE
Update right for directus_users.tfa_secret missing at minimal app permissions

### ISSUE THREAD

**Issue by paulboudewijn** [directus/directus#9883]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Users with a role assigned with only the minimal or recommended system permissions are unable to activate 2FA since the update right on their tfa_secret field is missing.

~~I have a PR ready.~~

### To Reproduce

1. Create a new role with only minimal or recommended system permissions.
2. Create a new user with this role.
3. Enable 2FA for this user.
4. Scan the QR code.
5. Enter OTP

### Errors Shown

You don't have permission to access this.

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

v16.13.0

### What database are you using?

MSSQL

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally

**Comment by licitdev** [comment]
Thank you @paulboudewijn for the report, please do open a PR.

**Comment by paulboudewijn** [comment]
As @rijkvanzanten commented on [#9908](https://github.com/directus/directus/pull/9908#issuecomment-975848765):

I think the issue here is that the TFA setup flow allows you to go through, even with the TFA field being readonly on update, rather than the update permissions missing from the minimal permissions.

The minimal permissions are the permissions required for the app to run. The recommended permissions are the ones that include all the permissions we require you set in order to have the best experience in Directus. Being able to update the TFA secret isn't a requirement for the app to run, so shouldn't be in the minimal permissions.
