### ISSUE TITLE
Recommended system permissions gives users read rights on all users

### ISSUE THREAD

**Issue by paulboudewijn** [directus/directus#9886]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Users with a role assigned with only the _recommended_ system permissions have read permissions on _all_ users. 
So on the user directory **all** users are shown to this user.

As this doesn't happen if the role only has the _minimal_ permissions, it seems to me the _minimal_ permissions are not automatically enforced. Is this correct?

### To Reproduce

1. Create a new role with recommended system permissions.
2. Create a new user with this role.
3. Logon with this new user
4. Navigate to the user directory
5. Notice all users are shown
6. Logon as admin
7. Change role permissions of the role created at step 1 to minimal system permissions
8. Logon again with the user created at step 2
9. Navigate to the user directory
10. Notice only the user itself is shown

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

v16.13.0

### What database are you using?

MSSQL

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally

**Comment by benhaynes** [comment]
This almost certainly should be a discussion, not an issue, but first I'll ask:

Why is this being reported as a bug? It is intended behavior to show all users by default (recommended permissions)... and I'm confused why you would expect otherwise. 🤔

**Comment by paulboudewijn** [comment]
> Why is this being reported as a bug? It is intended behavior to show all users by default (recommended permissions)... and I'm confused why you would expect otherwise.

The "minimal permissions" deny read rights to a user, other then it's own user account.
The "recommended permissions" grant read rights to a user, for all user accounts.

That can't be as intended, minimal rights should only be overruled for admin accounts.

This is what the directus app says about it:

![image](https://user-images.githubusercontent.com/17253180/142207167-2ce4909c-33b4-471f-8da2-efd0f5d8c7b3.png)

It seems to me [appRecommendedPermissions](https://github.com/directus/directus/blob/785c4306d63981360dad65b79e00a2ada844c636/app/src/modules/settings/routes/roles/app-permissions.ts#L3) are used as a seperate set of permissions instead of being added on top of  [appMinimalPermissions](https://github.com/directus/directus/blob/785c4306d63981360dad65b79e00a2ada844c636/app/src/modules/settings/routes/roles/app-permissions.ts#L133).

**Comment by benhaynes** [comment]
They are two completely different permission sets. 

* **Minimum Permissions** are those required to run the app in general, and can be used as a starting point for minimal permission roles.
* **Recommended Permissions** are the permissions that provide the intended user experience within the App. The _User Directory_ is meant to provide a read-only directory of all users to everyone... not just Admins.

**Comment by paulboudewijn** [comment]
Hi @benhaynes ,

I'm sorry, my bad, while driving in my car I realized I got it all wrong. There are no 'deny' rules, only 'allow'. So it works as intended. 

Perhaps a discussion could be started on the question if it should be recommended to show users all other users in the user directory (including the admin account), but I'll leave it for now.

**Comment by paulboudewijn** [comment]
Now I know how I got confused, it's the `permissions` filter `id: {_eq: '$CURRENT_USER',}` on the `directus_users` `read` rule in `appMinimalPermissions`.

On the `directus_users` `read` rule in `appRecommendedPermissions` this one is gone. With one set named 'minimal' and another 'recommended' this caused some confusion at my end. But now I now, 'minimal' rights are solely meant for the app to work well.

**Comment by benhaynes** [comment]
Nice! Glad the structure makes sense now. Always open to discussing how to make this clearer, or what the "Recommended" settings should be,

**Comment by tylerforesthauser** [comment]
It could just be a matter of the wording. I had the same confusion initially. Perhaps something like "Bare Minimum Settings" or something more explicit?
