### ISSUE TITLE
When using the /auth/login endpoint : expires = 900000

### ISSUE THREAD

**Issue by torstenhoegel** [directus/directus#9887]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hello there,

Today I ran over the problem, that the api is sending me an expires time of 900000 on the auth/login request.

I've tried setting it up with ACCESS_TOKEN_TTL set to 15m which should be standard right?

Regards

### To Reproduce

install version 9.0.0 or 9.0.1 and request auth tokens via `POST /auth/login`

### What version of Directus are you using?

9.0.0 / 9.0.1

### What version of Node.js are you using?

packed in docker

### What database are you using?

Postgres 13

### What browser are you using?

Chrome + Firefox + Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

docker / local / PaaS DigitalOcean

**Comment by licitdev** [comment]
The `expires` is in milliseconds. Hence `15m` will be `900000`.

**Comment by torstenhoegel** [comment]
I got that 👍🏻  
dumb question .. sorry for opening this issue :/ just got this one wrong
