### ISSUE TITLE
Add in helper library for accessing data in database

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#989]
In addition to the API, this would be very useful to help people get (and put) data into the database. While most people will use their preferred libraries, providing one will help get people up-and-running faster.

**Comment by benhaynes** [comment]
This can be a simple version to start, then we can add in features as time goes on. The question is, what language would this be written in? PHP?

**Comment by WellingGuzman** [comment]
@benhaynes wouldn't be the same library as we use behind the API? or didn't I understand correctly what you mean by helper library?

As we talk about abstracting, we can use our current library, and decouple from the API, and make the API use it, it would be the same just taking it out form the API.

As an example:
```php
$peopleTable = new DirectusTable('people');
$peopleTable->insert(array(
  'name' => 'John Doe'
  'email' => 'j.doe@email.com'
));
```

```php
// requestPayload
// name: "John Doe"
// email: "j.doe@email.com"

$app->post('/people', function() {
  $peopleTable = new DirectusTable('people');
  return $peopleTable->insert($requestPayload);
});
```

Or are you talking about something else?

**Comment by benhaynes** [comment]
That's exactly what I mean. ;)

**Comment by WellingGuzman** [comment]
This also are going to be part of https://github.com/directus/directus-php-sdk

**Comment by benhaynes** [comment]
Should we remove it from here then? Maybe open a ticket specifically for the SDK?

**Comment by WellingGuzman** [comment]
Should we close this and open the ticket on the SDK? or should we keep it here as we are updating the Directus DB package?

**Comment by benhaynes** [comment]
We can move it to the SDK repo, but I'm worried it will be overlooked there. If we need to update Directus Core for this then we should leave it here until that's done. Thoughts?

**Comment by WellingGuzman** [comment]
I've been thinking about it, staying here will be best as it will be in Directus Core anyway, and will be used by the SDK.

**Comment by WellingGuzman** [comment]
we already have a [php-sdk](https://github.com/directus/directus-sdk-php) and a [node-sdk](https://github.com/directus/directus-sdk-javascript), which can be used as library to access the database
