### ISSUE TITLE
Error when i change template of M2O

### ISSUE THREAD

**Issue by federicocappellotto97** [directus/directus#9897]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a relation M2O and when i try to change display template it returns error
Video explain better

https://user-images.githubusercontent.com/63153191/142278988-30528e49-9aaf-4af3-9357-8416b3c51a33.mov

### To Reproduce

Create a M2O relationship and change the template.
This error doesn't appear everytime, i have the same relation in other content types with, and they don't give errors.

### Errors Shown

[INTERNAL_SERVER_ERROR] alter table `Spazi_page` modify `SEO` int null - ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'SEO': used in a foreign key constraint 'spazi_page_seo_foreign'
content_copy

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

14.18.1

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

macOS Monterey (12)

### How are you deploying Directus?

Locally

**Comment by Oreilles** [comment]
To prevent this kind of issues, I added a check some time ago to only update the column if the schema update is different from the current one, which for some reason is the case here - even though you didn't change anything.
https://github.com/directus/directus/blob/a920041c5b12eab72b5daeb71eaea11129cec8f8/api/src/services/fields.ts#L279-L281
Would you be able to share a schema snapshot so that we can investigate this ?

**Comment by federicocappellotto97** [comment]
Whit `DB_CHARSET="utf8"` it's working now! Thanks!!

**Comment by federicocappellotto97** [comment]
> With `DB_CHARSET="utf8"` it's working now! Thanks!!

No, i'm sorry, same error in another project even with `DB_CHARSET` :(

`[INTERNAL_SERVER_ERROR] alter table `Eventi_calendario` modify `categorie` int null - ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'categorie': used in a foreign key constraint 'eventi_calendario_categorie_foreign'
content_copy`

This happens in a relation M2O.
Model type A: Eventi_calendario (Calendar events in english)
Model type B: categorie_eventi_calendario (Calendar events categories in english)

B has a field called **title**, and i would like to show this title in the relation field of A instead of **ID**, but i can't edit the template.

**Comment by Oreilles** [comment]
Would you be able to share a dump of your database ?

**Comment by federicocappellotto97** [comment]
> Would you be able to share a dump of your database ?

Can i share it with you privately? Maybe on discord, or wherever you like!

**Comment by Oreilles** [comment]
Sure, I have the same name on Discord.

**Comment by mshihinski** [comment]
I have the same issue reported here with the following differences.

Node: v14.17.3
Directus: 9.2.0

I tried adding the charset with no luck. 

{
  "errors": [
    {
      "message": "alter table `Pages` modify `Parent` int null - ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'Parent': used in a foreign key constraint 'pages_parent_foreign'",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

**Comment by g-30** [comment]
@rijkvanzanten multiple people experiencing this, bumping to re-open

**Comment by paescuj** [comment]
> @rijkvanzanten multiple people experiencing this, bumping to re-open

This closed bug report dates back to 2021. It seems like the issue you're experiencing is tracked in #18247. If you feel like it's a different issue, please open up a new bug report instead! Thanks!
