### ISSUE TITLE
User permissions not applied to collection fields when edited as M2M related item

### ISSUE THREAD

**Issue by paulboudewijn** [directus/directus#9898]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

If I deny update rights to a user for a specific collection, all fields become readonly. That works as expected.
But when I use this collection in a M2M relation as the related item, it's fields become editable. 
Saving changes results (fortunately) in a permission denied error.

### To Reproduce

1. Create a collection 'book'
2. Deny update rights for this collection
3. Create a collection 'author'
4. Create a M2M relation between 'book' and 'author'
5. Notice that when editing a book item directly all fields are readonly (as expected)
6. Notice that when editing an author and then editing a related book through the M2M interface all book fields are editable

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

v16.13.0

### What database are you using?

MSSQL

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment]
I just added `disabled` support for `drawer-item` in #10663, so this issue should be trivially easy to fix now
