### ISSUE TITLE
Look into OData as an API standard

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#990]
http://www.odata.org/

Worth checking out if this can help standardize our API endpoints.

**Comment by benhaynes** [comment]
Any thoughts on this? If we did an API sprint for a week is this something we could incorporate?

**Comment by benhaynes** [comment]
Not pursuing this...

**Comment by u12206050** [comment]
@benhaynes  I can see this is very old :) Any idea why this wasn't pursued and if it might be relevant again to bring up, possible for v10?
OData seems to have become a quite common standard with companies like Microsoft and Google having implemented and using it.

**Comment by benhaynes** [comment]
Quite old indeed! I don't have any details on why this wasn't pursued, but I'm sure @rijkvanzanten can provide some insight. Do you have thoughts on what this would entail or any issues that might arise from adding support for this?

**Comment by rijkvanzanten** [comment]
There's many different (competing) standards (like JSON:API). OData didn't quite fit the technical design we were going for (in things like the `$filter` syntax, and some of the other conventions).

**Comment by u12206050** [comment]
Ok, so you chose JSON:API or some other standard, or is it custom?

**Comment by rijkvanzanten** [comment]
It's custom 👍🏻 A lot of the specs add quite a bit of bloat, and unlike GraphQL, there isn't really a single REST "spec" that's ubiquitous enough across other dev tooling to warrant using.
