### ISSUE TITLE
Gatsby Install Module for Directus Package subpath './public/extractFiles' is not defined by "exports"

### ISSUE THREAD

**Issue by doodlemania2** [directus/directus#9903]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Attempting to bring up a new Gatsby site (am brand new to this so please be patient!) 

Throws: 
~/directus1$ gatsby develop

 ERROR

Error in "/home/derek/directus1/node_modules/@directus/gatsby-source-directus/gatsby-node.js": Package subpath
'./public/extractFiles' is not defined by "exports" in /home/derek/directus1/node_modules/extract-files/package.json

  Error: Package subpath './public/extractFiles' is not defined by "exports" in /home/derek/directus1/node_modules/extra
  ct-files/package.json

### To Reproduce

`gatsby new
npm install --save @directus/gatsby-source-directus`

Then add the config to gatsby-config.js to activate the module.

Then: 
`gatsby develop`

### Errors Shown

gatsby develop

 ERROR

Error in "/home/derek/directus1/node_modules/@directus/gatsby-source-directus/gatsby-node.js": Package subpath
'./public/extractFiles' is not defined by "exports" in /home/derek/directus1/node_modules/extract-files/package.json

  Error: Package subpath './public/extractFiles' is not defined by "exports" in /home/derek/directus1/node_modules/extra
  ct-files/package.json

### What version of Directus are you using?

8

### What version of Node.js are you using?

v17.1.0

### What database are you using?

Postgres 12

### What browser are you using?

Edge

### What operating system are you using?

Windows 11

### How are you deploying Directus?

Docker

**Comment by joselcvarela** [comment]
Hello @doodlemania2 
I could found the root of this issue and it seems is a chain of dependencies issue, unfortunately.
I have opened an issue here: https://github.com/gatsbyjs/gatsby/issues/34042
We have a bot to update our dependencies automatically, so we will know when this should be fixed.

Since the issue does not come from Directus, I am closing this, but feel free to provide any additional feedback.
