### ISSUE TITLE
oAuth provider isn't showing up after being configured

### ISSUE THREAD

**Issue by limegorilla** [directus/directus#9915]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [x] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

So I have setup Microsoft as my oAuth provider as below:
```
AUTH_PROVIDERS="microsoft"

AUTH_MICROSOFT_KEY = "*****"
AUTH_MICROSOFT_SECRET = "******"
AUTH_MICROSOFT_SCOPE = "openid email"
AUTH_MICROSOFT_AUTHORIZE_URL = "https://login.microsoftonline.com/******/oauth2/v2.0/authorize"
AUTH_MICROSOFT_ACCESS_URL = "https://login.microsoftonline.com/*******/oauth2/v2.0/token"
# AUTH_MICROSOFT_ALLOW_PUBLIC_REGISTRATION = true (this option is currently commented out)
```

However when trying to login to my instance but I don't actually have a button to try and login:

<img width="498" alt="Screenshot 2021-11-18 at 14 50 31" src="https://user-images.githubusercontent.com/29333568/142438266-e2bb419d-a7df-408e-9f93-962976100876.png">

### To Reproduce

Try and login

### Errors Shown

Unfortunately due to using Plesk I do not have access to anything but Apache logs. Unfortunately moving away from Plesk - while something I would love to do - isn't permitted by my company currently.

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

MariaDB 

### What browser are you using?

Chrome/Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

Plesk

**Comment by limegorilla** [comment]
> You're missing `AUTH_MICROSOFT_DRIVER = "oauth2"` my friend.

This means my Directus instance won't boot :/

**Comment by aidenfoxx** [comment]
@limegorilla Then you have something wrong with your configuration. I'm sure the logs would tell you what the issue is. 🙄

**Comment by limegorilla** [comment]
<img width="1222" alt="Screenshot 2021-11-18 at 15 38 24" src="https://user-images.githubusercontent.com/29333568/142446905-856f7562-ef2d-4622-a3f2-1a61e6ff557f.png">

This is unfortunately all I can get :/

**Comment by aidenfoxx** [comment]
You would probably have more success using the openid provider: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc

**Comment by limegorilla** [comment]
@aidenfoxx seemed to have got this working!

Quick other one: What should the return URL be? The base url and /auth don't work

**Comment by aidenfoxx** [comment]
In your case I would assume it's `https://yourdomain.com/auth/login/microsoft/callback`
