### ISSUE TITLE
Impossible to add existing item from M2M interface

### ISSUE THREAD

**Issue by dstoyanoff** [directus/directus#9923]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

On 9.0.1, using the M2M interface to add existing items doesn't work anymore. This bug seems to only occurs if the related table has a user-input `varchar` primary key rather than the default auto-increment `id`.

https://user-images.githubusercontent.com/33065839/142850818-46111125-ed3a-4dc2-8e4a-17d060a98723.mov

### To Reproduce

- Create a collection `available_languages` with primary key `code` varchar
- Create a collection `general`
- Create a M2M field related to `available_languages` in `general`
- Create some items in `available_languages`
- Try creating a new `general` item, using the M2M interface to add existing `available_languages` to it.

### Errors Shown

```js
// POST http://localhost:8080/items/general
// That payload is wrongly generated. available_countries doesn't have an 'id'. Its PK is 'code.'
{
    "enabled_countries": [
    {
        "available_countries_code":
        {
            "id": "CA"
        }
    },
    {
        "available_countries_code":
        {
            "id": "FR"
        }
    }]
}

// Response
{
    "errors": [
    {
        "message": "\"code\" is required",
        "extensions":
        {
            "code": "FAILED_VALIDATION",
            "field": "code",
            "type": "required",
            "stack": "Error: \"code\" is required\n    at /Users/******/code/directus/api/src/services/authorization.ts:285:37\n    at Array.map (<anonymous>)\n    at /Users/******/code/directus/api/src/services/authorization.ts:285:20\n    at Array.map (<anonymous>)\n    at AuthorizationService.validatePayload (/Users/******/code/directus/api/src/services/authorization.ts:284:65)\n    at /Users/******/code/directus/api/src/services/items.ts:125:34\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
        }
    }]
}

```

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

16.13

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by Oreilles** [comment]
I think the field `id` is the one from the M2M junction collection, probably named `enabled_countries_general_enabled_countries` in your case.
This might have the same root cause as https://github.com/directus/directus/issues/9864

**Comment by Oreilles** [comment]
> Not sure why those nested ids appear, since my country model doesn't have an id.
The `id` is the one from the junction collection. I think this might have the same root cause as Fixes https://github.com/directus/directus/issues/9864.

**Comment by Oreilles** [comment]
> Not sure why those nested ids appear, since my country model doesn't have an id.

The `id` is the one from the junction collection. Could this be related to  https://github.com/directus/directus/issues/9864..?

Just tried to replicate on a fresh install and couldn't. Could you share the content of your `directus_relations` table ?

**Comment by dstoyanoff** [comment]
The last screenshot is from `directus_relations`, filtered by `many_collection=general_available_countries`. Is there any other relation you are interested in?

**Comment by Oreilles** [comment]
Your relations are configured properly. I tried creating the exact same setup, migrate from `9.0.0` to `9.0.1` and did not encounter your issue. I suggest maybe trying to downgrade to 9.0.0, verify that the relation works, upgrade again to `9.0.1` and confirm that the bug is still present. if that is the case, please share a schema snapshot so that we can dig a bit further.

**Comment by dstoyanoff** [comment]
Yep, it's exactly like that. I tried to start with 9.0.0 and then after changing to 9.0.1, it broke. Snapshot attached.
[snapshot.json.zip](https://github.com/directus/directus/files/7578350/snapshot.json.zip)

**Comment by Oreilles** [comment]
Thanks, I have been able to replicate your issue. It seems to be cause by https://github.com/directus/directus/commit/bbd6e13e1edd2ff13997c25ff08c710e1252c8f8 (reverting this commit solves the issue).

**Comment by Oreilles** [comment]
Related? https://github.com/directus/directus/issues/8979

**Comment by MiniDigger** [comment]
we are running into this too (of course only noticing it in prod, woo), the key here is that the foreign key is a string.
we found that because the reverse direction for us works, where the foreign key is a "normal" integer

**Comment by ghezeli** [comment]
Hi
I also have this problem and I have a lot of problems
Please tell me when this problem is solved

**Comment by MiniDigger** [comment]
@ghezeli as you can see, there is already a pull request attached. you could help the team by testing that!

**Comment by AdiechaHK** [comment]
@dstoyanoff 

Can you please check my [PR#10368](https://github.com/directus/directus/pull/10368) This will solve this problem

**Comment by kaziller** [comment]
Hi @AdiechaHK,

thank you for fixing this! I was not sure if my migrations went wrong of if this is an actual bug. I only see one minor issue though:

https://user-images.githubusercontent.com/23482966/145792793-5cb70787-6b7e-43df-bb27-714d5675366d.mp4

This time instead of code as primary key and `varchar`, the table `available_language` uses id as primary key and `uuid` as well as code and name as normal strings. 

When I add an existing item, the added field is shown as empty. Saving `general` item (in my case its `vehicle`) works though. When I open the `general` item again, the added item is shown correctly.

The behavior does not show when creating a new language item within the `general` item.

@rijkvanzanten as this issue is closed, should I open a new one?

Thanks you

**Comment by joselcvarela** [comment]
Hello @AdiechaHK 
Please do, this one could tricky to solve. But let's discuss it on new issue 👍
