### ISSUE TITLE
Request password reset API couldn't send email for non-admin users

### ISSUE THREAD

**Issue by saptha** [directus/directus#9925]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Error in the log file 
08:35:04 ⚠️  [email] Error: You don't have permission to access this.

### To Reproduce

We are using mailgun for the email service.

### Errors Shown

[email] Error: You don't have permission to access this.

### What version of Directus are you using?

9.0.0-rc.90

### What version of Node.js are you using?

17.0.1

### What database are you using?

mysql

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu 20.04

### How are you deploying Directus?

PaaS

**Comment by benhaynes** [comment]
I ran into this yesterday, I solved it by adding the following to the `.env` file:

```
EMAIL_SMTP_SECURE=false
```

Let us know if this solves it! If it does, we'll add it to the Docs.

**Comment by saptha** [comment]
yes this helps to solve the issue
Thanks

**Comment by USSCOD** [comment]
Unfortunately, this did not resolve my error. Indeed following the last update, I can no longer connect to the Directus interface, even with my Admin user. and when I reset my password, the email never arrives !

**Comment by rijkvanzanten** [comment]
@USSCOD what configuration for emails are you using?

**Comment by USSCOD** [comment]
**Describe the bug:**

When I reset my password, I get a notification that the reset email is gone. Except that it never reaches my mailbox. [Admin Profile]

This error is displayed when I open chrom to reach the Directus interface: POST https://exemple.com/auth/refresh 500 (Internal Server Error)

When I enter the admin amil as well as the password, I get an error on the console: POST https://exemple.com/auth/login 500 (Internal Server Error) and a notification on the front: unexpected error

**Reproduce**

Internally we use Outlook for the mail service.

**Displayed errors**

POST https://example.com/auth/refresh 500 (Internal Server Error)
POST https://example.com/auth/login 500 (Internal Server Error) and a notification on the front: unexpected error

**What version of Directus are you using?**

9.0.0-rc.92

**What version of Node.js are you using?**

Node v17.9.1
npm 7.23.0

**What database are you using?**

mysql 2.18.1

**What browser are you using?**

Google Chrome

**What operating system are you using?**

Debian 10

**How are you deploying Directus?**

I followed this guide: https://docs.directus.io/getting-started/quickstart/

**How directus was updated:**

npm update
Addition of the Headers column in the directus_webhooks table

**Comment by rijkvanzanten** [comment]
> Internally we use Outlook for the mail service.

How did you configure the email settings in your .env for Directus? It sounds to me like the email never makes it out 🤔

**Comment by USSCOD** [comment]
I only have a few lines that I found by default and with which it worked fine before the update. 

EMAIL_FROM="no-reply@directus.io"
EMAIL_TRANSPORT="sendmail"
EMAIL_SENDMAIL_NEW_LINE="unix"
EMAIL_SENDMAIL_PATH="/usr/sbin/sendmail"
EMAIL_SMTP_SECURE=false (j'ai rajouter cette ligne aprés la mise a jour).

**Comment by USSCOD** [comment]
I only have a few lines that I found by default and with which it worked fine before the update.

EMAIL_FROM=" no-reply@directus.io "
EMAIL_TRANSPORT="sendmail"
EMAIL_SENDMAIL_NEW_LINE="unix"
EMAIL_SENDMAIL_PATH="/usr/sbin/sendmail"
EMAIL_SMTP_SECURE=false (I add this line after the update).

**Comment by USSCOD** [comment]
You say email never does ! in this case, how can I recover my password for the first user (Admin) ?

**Comment by rijkvanzanten** [comment]
@USSCOD Does the machine you're running this on have sendmail at that path? Directus requires an email sending service configured in order to actually send emails. We default to sendmail as that is available on a lot to hosts / systems by default, but not all. See https://docs.directus.io/configuration/config-options/#email 👍🏻

**Comment by USSCOD** [comment]
Sure enough, sendmail didn't configure on this machine.

I tried with this config, it doesn't work.

EMAIL_FROM = "no-reply@directus.io"
EMAIL_TRANSPORT = "smtp"
EMAIL_SMTP_HOST = "smtp.office365.com"
EMAIL_SMTP_PORT = "587"

Do you have a typical setup that would allow me to test?

**Comment by USSCOD** [comment]
Finally I installed and configured **Sendmail** and updated my .env directus,

###############################################################################$
## Email

**EMAIL_FROM**="no-reply@directus.io"
**EMAIL_TRANSPORT**="sendmail"
**EMAIL_SENDMAIL_NEW_LINE**="unix"
**EMAIL_SENDMAIL_PATH**="/usr/sbin/sendmail"
**EMAIL_SMTP_SECURE**=false

However, I do not receive any reset email from directus.

However in the mail.log I have:

Nov 26 09:48:42 z-mngcohortes-a0 sendmail[4024]: 1AQ9mgwO004024: to=exemple@exemple.com, ctladdr=no-reply@directus.io (1001/1001), delay=00:00:00, xdelay=00:00:00, mailer=relay, pri=33304, relay=[127.0.0.1] [127.0.0.1], dsn=2.0.0, stat=Sent (1AQ9mgIj004025 **Message accepted for delivery**)

**Comment by rijkvanzanten** [comment]
@USSCOD I would recommend using a dedicated email service like Sendgrid or AWS SES as an SMTP server, that prevents most of these DevOps headaches 👍🏻

**Comment by u12206050** [comment]
@rijkvanzanten Is/how it possible to use sendgrid?
