### ISSUE TITLE
An error in console: Cannot read properties of null (reading 'deactivate')

### ISSUE THREAD

**Issue by koksikus** [directus/directus#9926]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When I enter a collection and then go to a specific record and then (after changes or without them) I leave record via the back button, everything is ok. However, if I am in the record (without even making any changes), I click on the next collection skipping the back button. I get an error in the console. 
![2021-11-19 112125](https://user-images.githubusercontent.com/90528895/142606914-848bbcf5-5f53-42fa-888b-a314fab89c2a.png)

### To Reproduce

Then go to the collection and then to the specific record. Exit it but by clicking directly on another collection (not via the back button). Check your console. 

### Errors Shown
        
       TypeError: Cannot read properties of null (reading 'deactivate')

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

Sql server 2017

### What browser are you using?

Edge 95.0.1020.53

### What operating system are you using?

Debian 11.1

### How are you deploying Directus?

locally

**Comment by LevinGermann** [comment]
I have some permissions set up which I believe should be correct (to view "Event Location" entries), but I got a similar error when opening the collection:

![image](https://user-images.githubusercontent.com/9347206/142742608-1c63c716-312d-4ed5-972f-a470caef4272.png)

(Chrome)

**Comment by LevinGermann** [comment]
I believe this is related to a permission issue when a user doesn't have all the necessary permissions.
An example on when this occurred to me was when a user has permissions for a translation field/collection, but not on the "Language" collection itself. After I added read access to the Language collection, the problem disappeared.

**Comment by azrikahar** [comment]
@koksikus Thanks for reporting. It is a known bug and should be resolved by #9334.

@LevinGermann Technically this error shouldn't relate to what you're experiencing, since it's just an error with the context menu not being able to remove (deactivate) a context menu that was never opened. Hence it's unlikely to affect any other operations. With that said, what you ended up with is indeed correct as we do need to provide read access to Language in this case. If the intent was to not show that collection to the end users, then you can hide the collection via Data Model page 👍

**Comment by koksikus** [comment]
Hi @azrikahar, 
(that also happens when I logged in as administrator. In my version redundant Collections are hidden in the Data Model). 

I have one more error in the Polish language version. When I go back to English, it doesn't appear. It happens when I am logged in as administrator with Polish language and I go to the users and choose a user to view.
![Zrzut ekranu 2021-11-22 071458](https://user-images.githubusercontent.com/90528895/142819814-0d319f97-ddfd-4f26-86a2-e9cd5dd8270e.png)

And one more, in each language version, regardless of the settings, also in chrome. After about an hour of non-use Directus, an error appears in the console. The user does not see it and I have had information several times that something has not been saved for him and he is very nervous. Maybe this error has an effect on it. 
![Zrzut ekranu 2021-11-20 121939](https://user-images.githubusercontent.com/90528895/142820714-8c54a377-234e-47f3-9356-9d8d4b587300.png)
Is there a possibility of the situation that I [described there.](https://github.com/directus/directus/discussions/9893)

**Comment by azrikahar** [comment]
> I have one more error in the Polish language version. When I go back to English, it doesn't appear. It happens when I am logged in as administrator with Polish language and I go to the users and choose a user to view.

@koksikus this sounds like a different issue. Would you mind opening a new issue for this? It'd also help if you can share what's the interface/display settings for said "input", at least based on what the error is saying here. 

>  After about an hour of non-use Directus, an error appears in the console. The user does not see it and I have had information several times that something has not been saved for him and he is very nervous. Maybe this error has an effect on it.

This sounds more along the lines of session expiring after being idle, but it's also difficult to discern what's happening here without more detail. If it still persists, do open a new issue 👍

**Comment by koksikus** [comment]
@azrikahar Thanks for offering your help. I have reverted back to the English version and I am basing on it, so its good for now ;) 
I have a question for you - I have a record with M2M relation and when I want to make a copy of this record, everything is copied except for the list which is M2M relation. Is it a Directus bug or I'm doing something wrong?
