### ISSUE TITLE
Any relationship field - not allowing display field to be anything other than foreign key

### ISSUE THREAD

**Issue by unmaskz** [directus/directus#9931]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Using any relationship field on 9.0.1 causes some issues in terms of how to display out the relationship field.

![image](https://user-images.githubusercontent.com/23451091/142647160-049b3979-e9eb-43b0-a428-c7b960a28653.png)

I have tried various tables but as soon as you use say a M2O it will always render out as the foreign key rather than another field from that collection. When you try go in and edit the field properties to display a 'name' field for example it breaks as the relationship is empty and you can't change it as it is disabled.

![image](https://user-images.githubusercontent.com/23451091/142647375-635f907a-1355-4c62-9556-a0edd76da361.png)

Even ignoring the above and trying to proceed with selecting 'show relational field' and going to select a relational field... you can't.

![image](https://user-images.githubusercontent.com/23451091/142647491-d5495591-cef1-4138-9f64-5e310047fc3e.png)

### To Reproduce

FYI: I am using Directus via Digital Ocean

Create two collections with one having a M2O field relating to the other. 

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

14

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

OS Ubuntu 18.04

### How are you deploying Directus?

Digital Ocean

**Comment by Oreilles** [comment]
This looks like a previous issue https://github.com/directus/directus/issues/9182 which should have been fixed in 9.0.0...

**Comment by Oreilles** [comment]
This looks like a previous issue https://github.com/directus/directus/issues/9182 which should have been fixed in 9.0.0...
And I cannot replicate this. Are you positive you're on 9.0.1 ? Are you seeing any error in the console?

**Comment by unmaskz** [comment]
Seems you were right apologies! I hadn't restarted the server so was still on prev version! Closed
