### ISSUE TITLE
Translation issue "On deselect" instead of "On delete" in Advanced Translation field relational trigger section

### ISSUE THREAD

**Issue by armen-asriev** [directus/directus#9936]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When adding an advanced translation field, in relational trigger section, there is a translation error.
It says "On deselect" instead of "On delete"

### To Reproduce

When adding an advanced translation field, in relational trigger section, there is a translation error.
It says "On deselect" instead of "On delete"

### Errors Shown

It says "On deselect" instead of "On delete"

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

12.0.0

### What database are you using?

cloud

### What browser are you using?

chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

cloud

**Comment by rijkvanzanten** [comment]
This is intended, as the setting controls what happens when you deselect the item from the relational interface, rather than delete the related item. Seeing you  closed this issue already, I believe you might've figured that out already 😉
