### ISSUE TITLE
An error in console: RangeError use `d` instead of `D` (in 'D MMM u')

### ISSUE THREAD

**Issue by koksikus** [directus/directus#9973]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

It happens in the Polish language version. When I go back to English, it doesn't appear. 
It happens when I am logged in as administrator with Polish language and I go to the users and choose a user to view. 
Then the following error appears in the console:
![Zrzut ekranu 2021-11-22 071458](https://user-images.githubusercontent.com/90528895/142849073-60a1ddbe-eb18-46c7-b865-2a91e1bad15d.png)

### To Reproduce

Change language to polish version and log in as administrator and go to the users module and choose a user to view. Check your console.

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

Sql server 2017

### What browser are you using?

Edge

### What operating system are you using?

Debian 11.1

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
https://github.com/directus/directus/blob/241dc13c65ef995d36990fe3a819a0a87daf5517/app/src/lang/translations/pl-PL.yaml#L335

**Comment by koksikus** [comment]
Hey, I don't know why, but the latest version 9.2.1 still has this bug in the Polish version. And when I log in as a user on the same computer, I have a slightly different error, but also only if I click on the user. 
![Zrzut ekranu 2021-12-08 092024](https://user-images.githubusercontent.com/90528895/145174733-c9c29879-cd25-4a5c-a199-84376f5ea0d6.jpg)
Maybe some environmental variable is causing this ??

Why does this window appear after logging in as a user (after admin)? After clicking the green button - everything is displayed properly.
![Zrzut ekranu 2021-12-08 092406](https://user-images.githubusercontent.com/90528895/145174748-41ffac0d-8098-4c58-9cd4-c395d6530c0e.jpg)

**Comment by rijkvanzanten** [comment]
@koksikus Thanks for heads up 👍🏻 I'll get that resolved on locales.directus.io
