### ISSUE TITLE
An error in console: Failed to load resource: the server responded with a status of 401 (Unauthorized)

### ISSUE THREAD

**Issue by koksikus** [directus/directus#9976]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

In each language version, regardless of the settings, also in chrome. After about an hour or more of non-use Directus, an error appears in the console. I can still make changes in Directus. After refreshing, the error disappears. I thought it was not saving the data, but I found a description of the M2M error of the relationship. I think it would be good if the user was logged out automatically. Then the user logs in and everything refreshes. One more idea - can it be introduced that there is currently service work and please log in, in x time. During this time, no one can log in.

![Zrzut ekranu 2021-11-22 120902](https://user-images.githubusercontent.com/90528895/142851224-d6a6beae-3eb1-4c82-92b3-75733d293c69.png)

Or
GET and 401 (Unauthorized) vendor.299bc11cjs:74

### To Reproduce

In database I have many M2M relationship (maybe this is important). After about an hour or more of non-use Directus (it is still open in the browser but I use different tabs),  and when I return to it it shows an error appears in the console. 

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

Sql server 2017

### What browser are you using?

Edge

### What operating system are you using?

Debian 11.1

### How are you deploying Directus?

locally

**Comment by licitdev** [comment]
Hmm, I wonder if the access token was successfully refreshed...

@koksikus Please help to test if adding the environment variable `DB_POOL_MIN=0` resolves the issue. 
If it doesn't, please keep the browser developer tools open, at the network tab to see whether `/auth/refresh` ran successfully prior to the 401 error. Do provide the response content of the requests that errored out.

As for your feature request, it seems to be similar with https://github.com/directus/directus/discussions/7395.
Do upvote it or provide your comments there.

**Comment by rijkvanzanten** [comment]
Just to confirm, you saw that particular error, but everything kept working as expected? You mentioned you could still make changes and whatnot. The app will automatically refresh and retry the current request if the access token happened to be expired in the meantime here:

https://github.com/directus/directus/blob/ba0e9691e3f790d6360bcbfe7c8089792729e6b3/app/src/api.ts#L72-L96

so if that's the case, this is working as expected.

**Comment by koksikus** [comment]
Yes, I can still add or delete data. This has no effect on the operation of the system. I opened it on another computer and the same thing appeared. There is no size of time, it happens at different times. I'm logged in as an administrator. 
 
![Zrzut ekranu 2021-11-22 190648](https://user-images.githubusercontent.com/90528895/142912911-45597048-46ab-4772-82bb-95536656151e.png)


After F5
![Zrzut ekranu 2021-11-22 191441](https://user-images.githubusercontent.com/90528895/142913896-44b6ffc5-5515-401e-a477-e751eb284034.png)
In processes there is 28 items (records).

**Comment by rijkvanzanten** [comment]
@koksikus That might be just regular expected operations then 🙂 The app will at times cancel requests to prevent racing conditions (which you see in the first screenshot), and it'll auto refresh and handle any 401 state coming from expired tokens. Unfortunately, we can't tell the browser that we expect a 4xx / cancelled state, so it'll show them in red. This doesn't necessarily mean there's a problem though 👍🏻 

I'll close this for now, as it sounds like things are operating as expected.

**Comment by koksikus** [comment]
So, I understand, not to worry about such warnings in the console. Besides, the system works normally. Thanks

![Zrzut ekranu 2021-11-23 073423](https://user-images.githubusercontent.com/90528895/142989855-e7a294ad-a8b9-454e-9236-154d51f1d38f.png)
