### ISSUE TITLE
Removing a field from a collection kills its relationships

### ISSUE THREAD

**Issue by sebescudie** [directus/directus#9987]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

If a collection has several O2M fields, adding a field to that collection and then deleting it nullifies all its relations. I would have expected the field to simply be removed without affecting the item's relations.

Been using Directus for a few days only, I might have missed something. If that's the case then I'm sorry :)

### To Reproduce

- Create two collections named `parents` and `children`
- Give them both a `name` field
- Add a children O2M field to `parents`
- In the Content section, add a new item to `parents` and add two `children` to it
- Now go back to the data model section and add an `address` field to the `parent` collection
- Validate the changes and check your Content section : you should still see children listed under parents
- Go back to the data model section, and delete the `address` field from `parents`
- The Content section now shows no children in the `parent` item

See a repro capture here

https://user-images.githubusercontent.com/8690430/142902097-ce08474c-a9e3-48f9-815f-90fdfee1c555.mp4

### Errors Shown

Nope

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

SQLite 3.34.1

### What browser are you using?

Firefox

### What operating system are you using?

W10

### How are you deploying Directus?

Locally

**Comment by rijkvanzanten** [comment]
I believe this is the same issue I've reported on knex (the database abstraction library)..  here: https://github.com/knex/knex/issues/4155 with in-works PR https://github.com/knex/knex/pull/4189

**Comment by liho00** [comment]
> I believe this is the same issue I've reported on knex (the database abstraction library).. here: [knex/knex#4155](https://github.com/knex/knex/issues/4155) with in-works PR [knex/knex#4189](https://github.com/knex/knex/pull/4189)

Since you said its sqlite specific issue, I have a question on it, because im now looking for alternate solution. 

Can i use postgresql instead of sqlite? Just want to double confirm postgresql does not having this issue before i migrate the database.

Thanks in advance.
