### ISSUE TITLE
Can't access item uploaded files from public

### ISSUE THREAD

**Issue by terion-name** [directus/directus#9997]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a product with images:

<img width="893" alt="Снимок экрана 2021-11-23 в 13 01 26" src="https://user-images.githubusercontent.com/1060205/143012874-e904c9eb-1d6d-4483-9660-0031cf557692.png">

Permissions are set:
<img width="830" alt="Снимок экрана 2021-11-23 в 13 02 34" src="https://user-images.githubusercontent.com/1060205/143013049-65a51e30-73a0-43df-afec-b8588c5f5d2b.png">

Docs say that I need to just use `assets/{id}?key={template}` or even without key: https://docs.directus.io/reference/files/#accessing-an-file 

Files are displayed in admin properly, but by the link I get forbidden (however yesterday, immediately after upload they worked).

```js
// 20211123125411
// http://localhost:8055/assets/55807c1d-7489-43e7-94c4-185422772c81?key=product-preview

{
  "errors": [
    {
      "message": "You don't have permission to access this.",
      "extensions": {
        "code": "FORBIDDEN"
      }
    }
  ]
}
```

### To Reproduce

Upload an image to collection item, try access it from public after a while (or probably in incognito mode)

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

v16.12.0

### What database are you using?

mysql

### What browser are you using?

brave

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by terion-name** [comment]
Ok, adding this permission resolved access. But isn't this an overkill? This permission gives far more access to file data than one ever wants for simply providing public links for thumbs and attachments. 

<img width="809" alt="Снимок экрана 2021-11-23 в 13 37 23" src="https://user-images.githubusercontent.com/1060205/143017605-e98cc255-7244-4c9d-bf48-3d9ef0a2b661.png">

**Comment by benhaynes** [comment]
These permissions make sense to me. If you want to limit permissions a bit more, set custom read filters and/or disable certain fields within `directus_files`.

**Comment by stormbyte** [comment]
The permission Files is for all uploaded files.
If you want to open the image you could send the authorization header with it to fetch the images.
I would personally not use the Directus server as the main image supplier.
Directus is more like a data provider, only authorized users are allowed to fetch / download the images.

You even can use a nginx reverse proxy to cache these images and add the header there:
```
proxy_set_header        Authorization "Bearer ${BEARER_TOKEN}";
```

But if you just want public access to all uploaded files give the `Public` user Read access to `directus_files`

**Comment by rijkvanzanten** [comment]
@terion-name Feel free to [open a new feature request](https://github.com/directus/directus/discussions/new) with any and all ideas you might have on how to improve public read access to files in a less "overkill" way 🙂

**Comment by ybelenko** [comment]
> @terion-name Feel free to [open a new feature request](https://github.com/directus/directus/discussions/new) with any and all ideas you might have on how to improve public read access to files in a less "overkill" way 🙂

I would set public access by url only. Like it was in version 7. Now, if you add public read permission to files you can list all of them with unauthorized request `GET: /files` which makes unguessable ids of that files useless.

In other words I would allow unauthorized `GET /files/aabbff`, but forbid general list request `GET /files`.

**Comment by yondr-luka** [comment]
Edit public settings here:
![image](https://user-images.githubusercontent.com/93581121/215061009-46d4d8b0-b626-413b-900f-69a98d0aef9b.png)
![image](https://user-images.githubusercontent.com/93581121/215061081-5159876c-c2e6-4cae-8f75-9bb6b5a14bd1.png)
